### PR TITLE
Revert "Marker obj and door opening for simple animals (currently only necromorphs)"

### PR DESCRIPTION
**Pull request by ComicIronic**
Reverts d3athrow/vgstation13#10742 because you don't self-merge Jesus

### CODE REVIEW

**Comment by gbasood** [comment]
Fuck off
If you think I'm abusing shit by self merging, talk to pomf
Revert the code if you have reason to, not to prove some point.

**Comment by ghost** [comment]
Sood, regardless of your status, you shouldn't self merge.

Also, this gives us a chance to re-approach the marker, because after seeing it in action, it needs some serious tweaks.

**Comment by PJB3005** [comment]
> Doubled issue count after I reviewed it.

Yeah definitely revert.

I mean IMO necromorphs are retarded, but eh.

**Comment by ghost** [comment]
That's kinda saying you look over PRs after they're merged and gain complaints ingame rather than reviewing them before merge

**Comment by gbasood** [comment]
Nothing to do with status
I allowed time for review and I thought I got it but apparently only contrib review matters
And I thought I bugged @PJB3005 but apparently I didn't
@clusterfack I know I bugged like three times to no avail

**Comment by PJB3005** [comment]
> but apparently only contrib review matters

Yeah because others definitely didn't see the what, 15 issues I pointed out?

**Comment by Konater** [comment]
:eggplant:

**Comment by ComicIronic** [comment]
MERGE WHEN NERDS

**Comment by PJB3005** [comment]
NOW

**Pull request merged**
