### PR TITLE
Fixes molotovs not working when hitting anything except a floor

### PR DESCRIPTION
**Pull request by ghost**
:cl:
 * bugfix: Fixed molotovs not working when hitting anything except a floor (remember to put welding fuel inside the bottle!)

### CODE REVIEW

**Comment by Exxion** [comment]
`throw_impact()` is called for everything on the tile it hits, including the turf, so t should have already worked. If it didn't, something else is wrong.

**Comment by ghost** [comment]
It breaks upon the first thing it hits, also if it worked that way you could stack as many things in one tile as you can to spawn one puddle of fuel per thing

**Comment by Exxion** [comment]
Well you couldn't have if it didn't splash the turf regardless of the thing it hit
But whatever

**Comment by ghost** [comment]
Molotovs rely on creating a fuel puddle which only happens if they splash the turf, I agree that molotovs are super wonky

**Comment by Exxion** [comment]
Yeah exactly
If they only splashed the thing they hit but *didn't* break immediately, they'd only leave one puddle

**Pull request merged**
