### PR TITLE
Xenoarch overhaul/rework thing.

### LINKED ISSUE #25709: Some xenoarch guns Vanish
(WEB REPORT BY: gunosaguki REMOTE: 206.221.180.138:7777)
I've noticed this twice now that some xenoarch revolvers/alien guns when you expend their ammo they go invisible and vanish entirely if you drop the gun itself.

### LINKED ISSUE #25854: Alien revolver(?) invisible
(WEB REPORT BY: neonphile REMOTE: 206.221.180.138:7777)
# Revision
f6c4dfcdec9131ecbca3b7dd4b8be5dfa659143d

# Description
This weird alien revolver thing the xenoarch found is invisible on the ground and on the UI, visible in-hand.
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by PJB3005**
[qol] [packed] [box] [deff] [meta] [roid] [snowmap] [wheel]

Cuts out a bunch of stupid crap from xenoarch in the interest of making it less painful and less confusing.

Fixed stupidity in the find excavation code so it's actually possible to 100% reliably dig stuff up cleanly.

Suspension field generators are no longer necessary and have been removed from all maps. They can still be bought from cargo because you can use them on people and jkn would kill me if I removed that.

You no longer need to heat density separated sample when processing samples. As soon as you mix the lithium sodium tungstate with the ground rock you can throw it into the analysis machines. This makes it *significantly* more streamlined to process samples and also means you aren't basically forced to use a laser scalpel to get anything done.

Distances have all been fixed to be 100cm instead of 200cm per tile.

RP spectrometry machines have been removed and the space on the maps has been replaced with some free space so do whatever with it. As an extension of this I re-mapped the outpost-y sections of roid a bit so that the anomaly/sample lab have the HI/FTS because they were previously in the spectrometry lab.

Fixed artifact destructions not correctly being logged in all cases.

Moved the digsite locator to its own file.

Also fixes #25854 and fixes #25709

:cl:
 * tweak: You no longer need a suspension field generator to do xenoarch stuff. They have been removed from the map (but can still be gotten from cargo).
 * rscdel: Xenoarch RP machinery in the spectrometry lab has been removed!
 * tweak: You no longer need to heat xenoarch samples
 * tweak: Xenoarch distances are now 100cm = 1 tile, from 200cm = 1 tile
 * bugfix: Xenoarch guns don't turn invisible anymore.

### CODE REVIEW

**Comment by tuypo1** [comment]
But I liked using the suspension fields, it was fun

**Comment by PJB3005** [comment]
Yeah, and having to haul around a big piece of machinery, set it up, turn the field on, etc... made your job way slower than it had to be.

**Comment by DrSnips** [comment]
The 100cm thing doesn't make sense scale wise and triggers my autism. Id rather that be left alone

**Comment by tuypo1** [comment]
If the tedium is really that much of a problem just make it a handheld device instead, but as is it also makes for fun scenarios where you get fucked because your escape route was blocked off by the suspension field generator

**Comment by PJB3005** [comment]
> The 100cm thing doesn't make sense scale wise and triggers my autism. Id rather that be left alone

Most of the rest of the code assumes a tile is 1 meter by 1 meter, namely because `CELL_VOLUME` is 2500 liters that comes out to 1x1x2.5 pretty cleanly.

**Comment by PJB3005** [comment]
> If the tedium is really that much of a problem just make it a handheld device instead

1. I already don't have enough hands when digging as a xenoarch, don't make the problem worse.
2. Then the "use suspension gen on person" thing would be kinda OP so we'd have to scrap that.

> but as is it also makes for fun scenarios where you get fucked because your escape route was blocked off by the suspension field generator

I am trying my best but just completely failing to imagine *any* sane situation in which this could *possibly* occur.

**Comment by DrSnips** [comment]
So be it then. Can we keep the tools to nice even and whole numbers(save the brush at 1cm) though? Seeing 0.5 cm brush is a bit *odd*.

**Comment by PJB3005** [comment]
I actually wanted to remove the brush entirely but the problem is that it's necessary to open up strange rocks. Guess I could replace the 1cm pick with a 1cm brush instead.

**Comment by DrSnips** [comment]
I think you misunderstood what I said. I want whole and even numbers and not odd numbers because unga bunga odd bad.

**Comment by PJB3005** [comment]
Nah I understood what you meant, just decided to ignore the unga bunga odd bad part but fix the decimals bad part.

**Comment by ArchSunder** [comment]
bless you

**Comment by Megautham** [comment]
It only took 5 months to fix invisible xenoarch guns. Great changes overall.

**Comment by icantthinkofanameritenow** [comment]
If you don't need the suspsension field, why are you keeping in all the now useless references to artifact materials?

**Comment by PJB3005** [comment]
@icantthinkofanameritenow because they're not useless, they still tell you what kind of finds can be found there, especially when using the advanced digsite locator.

**Comment by xeroxemnas** [comment]
The wiki will get updated to reflect the new changes right? Otherwise it gets super confusing like when welders could no longer uncover strange rocks.

**Comment by icantthinkofanameritenow** [comment]
@xeroxemnas
When you edit it, it will.

**Pull request merged**
