### PR TITLE
Adds 'Dance Dance Revolution' vault

### PR DESCRIPTION
**Pull request by unid15**
It's a vault containing 4 drunk russian dancers, a lot of booze, a superjuke and a Dance Dance Revolution game

The minigame consists of turning yourself together with the arrow, and, during the later stages of the game, resting / standing up. The minigame gradually speeds up, and losing is punished by brute damage. Winning unlocks a loot stash with a trophy, clownpiece suit (the flying one), advanced clown shoes, lipstick and a sepia camera. The stash is very secure and can't be broken into or telescience'd. Punishment for losing is 1-25 brute damage, spread evenly across your body

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
How are you stopping the looters?

**Comment by unid15** [comment]
The walls are invincible and the stash can't be accessed by telescience

**Comment by ihadtoregisterforthis** [comment]
And jaunting and near teleporting? The mech teleporter, phasing, reactive teleporter, RPD wall walk, blink, beacon deviation...

**Comment by unid15** [comment]
If they can do that then let them have it I guess. The loot isn't that overpowered

**Comment by Intigracy** [comment]
:+1:

**Comment by icantthinkofanameritenow** [comment]
Creative idea. I'm surprised the engine would be able to handle something like that.

**Comment by Intigracy** [comment]
Why not make it function like actual DDR?

Make it so you fail if you aren't standing on the correct corner instead of facing a direction.

**Comment by Probe1** [comment]
adv clown shoes worn by non clowns result in !!FUN!!

thats a twisted prize.

**Comment by clusterfack** [comment]
Conflicted with yourself!

**Comment by gbasood** [comment]
WHAT
COULD
GO
WRONG

**Pull request merged**
