### PR TITLE
Knight Armor hardsuits

### PR DESCRIPTION
**Pull request by NigglyWiggly**
Hardsuits based off of knight armor, for adminbus and shit
ss 2015-02-20 at 10 08 18

This is my first PR, and I have absolutely no idea what I'm doing, so let's hope I don't fuck up absolutely everything

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
Aaand forgot the item icon. Fuck.

**Comment by RoyalSev** [comment]
THE INHANDS, NESSY, WE TOLD YOU ABOUT THE INHANDS

**Comment by NigglyWiggly** [comment]
Apparently my branch is thousands of commits behind somehow even though I made it a few minutes ago right after redownloading everything. rip

**Comment by clusterfack** [comment]
Add vgstation13 as a remote, then git rebase vg/Bleeding-Edge

**Comment by NigglyWiggly** [comment]
I suppose I should have been using that tortoisegit thing that everything else suggested

**Pull request closed without merging**
