### PR TITLE
Changeling verb holders

### LINKED ISSUE #1705: Changelings become unresponsive if put inside sleeper while in regen stasis
Was playing earlier. Got blasted by a bomb as a changeling and went into regen stasis. An engineer ended up finding me and putting me in a sleeper on the escape shuttle. Attempted to wake from statis at least 4 times. Depleted chemicals as well. Was not able to wake up, even after someone removed me from the sleeper.

### PR DESCRIPTION
**Pull request by unid15**
Fixes #1705 and some other issues

### CODE REVIEW

**Comment by ComicIronic** [comment]
Needs a spell conversion, not more verb hacks

**Comment by 9600bauds** [comment]
Nobody knows how those work and not even the people that made them are using them

**Comment by 9600bauds** [comment]
Tested this for a little, seemed to work fine, cloning changelings works well

**Comment by clusterfack** [comment]
Pfff not knowing how spells work.

They're just very simple datums, basically plug and play. Look at group jaunt.

**Comment by clusterfack** [comment]
But either way I'm working on a long term verb to spell conversion, but hell this is fine if just to fix that regeneration bug for the time being

**Comment by clusterfack** [comment]
>TODO: check for unintended features

**Comment by 9600bauds** [comment]
Didja check for those unintended features yet

**Comment by unid15** [comment]
Should be good to go

**Pull request merged**
