### PR TITLE
Fixes mice spawning in vents where they really shouldn't be spawning

### LINKED ISSUE #23488: Plague Mouse spawn in SME
(WEB REPORT BY: askaris REMOTE: 206.221.180.138:7777)
# Revision
106e9d17accd7614718b17a92a2df0e547522cab

# Description

Spawned as a plague mouse in the SME vent. Died instantly. Spared the crew from the horrendous virology wild ride they deserved.

# Steps to Reproduce

Spawn as a plague mouse and see if you spawn somewhere instantly lethal.

# What you Expected

Spawning in and giving the crew aids.

# What Actually Happened

Supermatter chamber denying the crew their just desserts.

### PR DESCRIPTION
**Pull request by DeityLink**
76ijt8uekwh21

image**THIS GET IS CLAIMED BY THE MICE GANG** image

tenor

TakeThisRat_001

Fixes #23488

:cl:
* bugfix: Mice (both observers and plague mice) will no longer spawn in the supermatter chamber, as well as in Virology or Xenobiology if their vents aren't connected to the rest of the station.

### CODE REVIEW

**Comment by SonixApache** [comment]
nice GET

**Comment by boy2mantwicethefam** [comment]
Witnessed

**Comment by gurfan** [comment]
checked

**Comment by Eneocho** [comment]
Can you still spawn on vox outpost?

**Comment by Blithering** [comment]
donut

**Comment by Killette2** [comment]
Did this also get the atmospheric miners?

**Comment by DeityLink** [comment]
They were set to 0 on all maps by default. Also note that none of this apply to vents on Z Levels other than the main station and frankly if you want to spawn off-station just take what you get.

**Pull request merged**
