### PR TITLE
Fixes medical/security not having EVA access

### PR DESCRIPTION
**Pull request by Probe1**
I did not give it to paramedics.  My reasoning is they already have a special snowflake hardsuit.  I have added magboots to their paramedic EVA locker in return.

Also, the paramedic job is in its own dm file for some reason and I have questions about that.  For some reason paramedic and chaplain are not part of their respective archetypes (medical and civilian) but their own file.  Weird right?

Fixes https://github.com/d3athrow/vgstation13/issues/6477

### CODE REVIEW

**Comment by PJB3005** [comment]
Chaplain being seperated is probably because they have a lot of special code (religion selection and such).

**Comment by Probe1** [comment]
Alrighty should work fine after testing.  My config had ```var/jobs_have_minimal_access``` enabled for some reason, and I can't find out why so testing gave me some weird feedback.  But I checked and rechecked the code and it looks sound.

**Comment by PJB3005** [comment]
@Probe1 literally every server except /vg/ has minimal access enabled, pomf just has it on in the server configs.

**Comment by Probe1** [comment]
Based on feedback I have added magboots to the paramedic EVA locker.

**Pull request merged**
