### PR TITLE
added brighter slip zone

### PR DESCRIPTION
**Pull request by DDihanov**
[qol][tweak]

Made the slip zone glow brighter cause it was super hard to spot. Also there was some super long delay in between the shimmers which is now reduced.

Before:

before

After:

after

EDIT: 

Static:

static2

EDIT2:

This is with default brightness and increased frequency:

lube

EDIT3:

This actually uses the brightest frame of the default sprite animation and it's still really hard to spot.
(Notice the top right corner of the floor tiles)

Static "low brightness":

static_low_brightness

:cl:
 * tweak: Made slip zone(water, lube etc..) shimmer brighter.

### CODE REVIEW

**Comment by aceedex** [comment]
Very nice. Im surprised it took so long for someone to do it

**Comment by DDihanov** [comment]
Thanks to my fam @brndd for suggesting it.

**Comment by Killette2** [comment]
I think it's too frequent and too big of a leap. What were the exact times before? This looks like a 5x multiplier at least

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I think it should be a static poodle decal rather than a flashing animation

**Comment by DDihanov** [comment]
Static example:

static2

**Comment by spoonylove** [comment]
I'm torn I like the static example, but doesnt it lose some of the fun if people can see slippy zones?

**Comment by brndd** [comment]
I agree this might be a little bit too frequent on the shimmering. There should probably be at least a little downtime on the effect.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I think the flashing is bad altogether, slip hazards shouldn't be invisible at any point. Hard to notice at most, but a hard to notice static sprite if anything instead of a flashing sprite that can be invisible for several seconds

**Comment by brndd** [comment]
What about a "static" effect that creates a shimmer that rotates around the tile in a manner similar to the vent pump glow in the bottom gif, with some delay between each rotation?

**Comment by Killette2** [comment]
There's times in real life where you might not notice a puddle and slip. I feel like the same should apply here, because also slick surfaces are meant to be somewhat a stealthy surprise.

**Comment by Lunstra** [comment]
I always figured the shimmer effect is a stand in for how sometimes wet floors won't be visible and then the light shifts and suddenly you get blinded as the fucking sun is reflected full force into your face from an angle you didn't expect. So having it flash TOO frequently feels weird to me

**Comment by DDihanov** [comment]
So you guys like it, but want a bigger delay between shimmers? Or you want the static one less bright?

**Comment by brndd** [comment]
Either one of those options will work for me, yes. I'd still like it to be kind of tricky to spot, but just not borderline impossible like it is currently.

**Comment by ghost** [comment]
Did someone slip and die?

**Comment by brndd** [comment]
I'm sure lots of people slip and die every day, considering it's the predominant way combat currently flows. If you actually like that, I question the quality of your tastes.

**Comment by DDihanov** [comment]
This is with default brightness and increased frequency:

lube

It's still barely visible, but a little bit better. Opinions?

**Comment by Killette2** [comment]
I like that latest one you showed

**Comment by brndd** [comment]
Yeah that's pretty good.

**Comment by juanototo2** [comment]
I prefer fullbright more frequent

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Post a low brightness static decal for comparison

**Comment by DDihanov** [comment]
This actually uses the brightest frame of the default sprite animation and it's still really hard to spot.(Notice the top right corner of the floor tiles)

Static "low brightness":

static_low_brightness

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Perfect
I prefer that one

**Comment by DDihanov** [comment]
Welp it might be a good idea to run a poll since you like the static ones and other peeps like the flashing/flashing bright ones. @ShiftyRail maybe a poll ingame?

**Comment by brndd** [comment]
Both the "increased frequency, default brightness" or "static image, low brightness" are good IMO. A server poll might indeed be in order for this, especially since slips are a pretty important mechanic and are sure to evoke some feelings in players.

**Comment by DDihanov** [comment]
@ShiftyRail @SonixApache @jknpj

**Comment by SonixApache** [comment]
`default brightness and increased frequency` has my pref

**Comment by Kurfursten** [comment]
Slipping is such a major mechanic and this has received a relatively split vote, I'm tempted to take this to a server vote. I do appreciate that DD has made clear efforts to come to a solution agreeable to everyone where possible though.

We'll see if we can drum up some more emojis to make this decisive before going to that though.

**Comment by ComradeDispenser** [comment]
Either make it static, or make the animation constantly cycling and very slow, rather than fast and only on part of the time

**Comment by FudgePucker** [comment]
I like the static low brightness. It looks moist.
It's not noticable unless you know or are looking for slippery floors, and then you can try to traverse it without waiting for the shimmer.

IMO lube needs this nerf

**Comment by Hoshi-chan** [comment]
The ideal would be default brightness, but a constantly cycling (but much slower than what you've shown) animation.

**Comment by DDihanov** [comment]
@Hoshi-chan so basically the default one?

**Comment by Killette2** [comment]
If lube seems to be the real problem then shouldn't water and lube look different on floors?

**Comment by DDihanov** [comment]
Poll when? @Killette2 water is the same

**Comment by Kurfursten** [comment]
The numbers on this look more convincing after we let it cook a bit and I reached out on many channels.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
wait but which version was merged

**Comment by brndd** [comment]
"Default brightness more frequent shimmer" by the looks of it.

**Pull request merged**
