### PR TITLE
Spelling/grammar/wording/etc fixes 2: flavor text nazi boogaloo

### PR DESCRIPTION
**Pull request by Wizardcrying**
!!! DO NOT MERGE !!!

Continuing from the quest set forth in #12993 

**I NEED YOU!**
Request shit that you want a description for that could use one
Suggest a file to be looked at
Et cetera

:cl:
  * bugfix: MORE flavor text changes!

### CODE REVIEW

**Comment by despotate** [comment]
It's... worse. "Using" is a verb. Doesn't fit. Try "that uses" instead.

Old version was better.

**Comment by ghost** [comment]
Both work :woman_shrugging:

**Comment by Wizardcrying** [comment]
sure thing @despotate

**Comment by Wizardcrying** [comment]
making new pr

**Pull request closed without merging**
