### PR TITLE
A helmet which hides your hair doesn't shave you off completely anymore.

### PR DESCRIPTION
**Pull request by ShiftyRail**
It's subtle, but the guy has hair on his neck now.
I just took the hairstyles of the game and cropped them to fit the icons.

Need to take a double check at some of the problematic ones to see if it fits.

:cl:
- tweak: Wearing a helmet obscuring your hair doesn't shave you off completely anymore.

### CODE REVIEW

**Comment by iFlashYou** [comment]
waifu buffs...

**Comment by Intigracy** [comment]
Where'd hair_schierke_s go

**Comment by SonixApache** [comment]
he actually did it, the absolute madman

**Comment by ghost** [comment]
i approve

**Comment by ShiftyRail** [comment]
Fixes
- bald sprite no longer errors out
- re-added the lost sprite
- added a basic guide on how I did this
- Space helmets now correctly delete your hair (as they should)

**Comment by SonixApache** [comment]
also "an helmet" is bad grammar

**Comment by Durgen** [comment]
I predict that having a slightly less deindividualized sprite will lead to slightly more humane treatment of the crew.

https://en.wikipedia.org/wiki/Stanford_prison_experiment

**Comment by ghost** [comment]
If you're unfucking this, then it'd be nice if you could make the Vox raider equipment show their quills as they were intended to. No sprite cropping required!

**Comment by ShiftyRail** [comment]
@Emilc4h I'll try to give it a look

Maybe in a later PR, I'm not available for coding until the 20th and I would rather have this rounded up

**Pull request merged**
