### PR TITLE
Revert "Nerfs floor tiles buffs toolboxes"

### PR DESCRIPTION
**Pull request by TheFriggenSawbones**
Reverts d3athrow/vgstation13#9637

BAD UPDATE
NO SELF MERGE

SCREW OFF CLUSTER

### CODE REVIEW

**Comment by ghost** [comment]
I think it's fine. But, metal rods didn't need to be nerfed along with it, they're a little harder to get and we need SOMETHING cheesy.

**Comment by The-Albinobigfoot** [comment]
When was the last time sawbones opened a PR that wasn't a joke?
Has he ever?

**Comment by CptWad** [comment]
there was the first one he did where he fixed a bug

**Comment by TheFriggenSawbones** [comment]
i fixed a bug and did two pr sets of typo fixes, because im not a coder so srry

**Comment by ComicIronic** [comment]
WHERE
IS
THE
SERVER
VOTE

**Comment by JustSumBody** [comment]
> revert floortile/toolbox damage

image
DEMOCRACY HAS SPOKEN

**Comment by Iamgoofball** [comment]
buff them both tbh

**Comment by TheFriggenSawbones** [comment]
@Iamgoofball fuck off and die

**Comment by ComicIronic** [comment]
Nearly as many people haven't noticed as want it reverted, I say give it more time for people to make a judgement.

**Comment by clusterfack** [comment]
Okay one more fucking revert pr and you're going to be github banned

**Pull request closed without merging**
