### PR TITLE
Horizon's tiny holodeck

### LINKED ISSUE #27315: horizon has no holodeck
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
1f256d195689efba7424d1310c383a72871e538f

# Description
bruh
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by DamianX**
I read Kurf's suggestion in #27315 and I knew the end result would look too silly not to do it, so here it is.
holodeck_horizon
holodeck_3x3

Some rooms that didn't scale well down to 3x3 such as the checkers and chess board are not included, and don't appear on the console.
Some rooms are EXTREMELY stupid, such as the basketball court with the two hoops separated by a single tile, so I think it fits the theme of the map quite well.

Closes #27315

:cl:
- rscadd: Horizon now has a holodeck.

### CODE REVIEW

**Comment by Dacendeth** [comment]
port to packed when?

**Comment by DeityLink** [comment]
Emagged room that's just hyperspace and throws the people who enter it out of the ship bellow when?

**Comment by Kurfursten** [comment]
Nice.

I suggest changing the tinted windows to ordinary windows so you can look in and appreciate the minideck

**Comment by DamianX** [comment]
They look tinted but it's actually just the icon from the window/grille spawner I added a while back. They are clear windows so you can see through them, the airlock is also glassed.

**Comment by hbycyl** [comment]
petite perfection programmed promptly

**Comment by Lokiamis** [comment]
I love it

**Comment by SonixApache** [comment]
incredibly stupid and thus adorable
though i feel like 3x3 should be on packed and this should be 5x5 somehow but whatever

**Comment by Kurfursten** [comment]
You now enjoy mapping priority.

Current order:
**THIS PR**
#27356
#27287

**Pull request merged**
