### PR TITLE
Mushroom Men Customization

### PR DESCRIPTION
**Pull request by beesil**
The first of several mushroom-men content PRs. Converts the current mushroom cap to a color-able hairstyle and adds three new variations. Spawned or grown mushrooms will have the plump helmet hairstyle in purple. 

Will add a net stinkhorn and cordyceps option for the anon in the thread if I have energy later. ~~Bald is not pickable but shaving or radiation will make a cap-less mushroom man, which is janky but dunno how to fix it.~~  Added a `NO_BALD` anatomy flag that stops shaving/radiation from making you bald.

image 
From left to right, plump helmet (default), amanita, flat cap, and chanterelle. Slightly out of date: added better contrast to the amanita style.

:cl:
 * rscadd: Several new variations of mushroom-men have been spotted in NanoTrasen space and Shoal trading outposts.

### CODE REVIEW

**Comment by SageOfLight** [comment]
How does a capless one look anyway. Are they just a bald puffball?

image

**Comment by beesil** [comment]
@SageOfLight they look like this without hair, ideally no one will see it

image

**Comment by Buchse** [comment]
I still think you should just make the legs normal so you don't have to worry about fitting things

**Comment by Kurfursten** [comment]
You should make a species flag for species not intended to become bald (e.g.: mushmen, catbeasts)

**Comment by ShiftyRail** [comment]
Bald schroomies are ok

**Comment by beesil** [comment]
Changed the amanita hair to have slightly better contrast.

@Kurfursten 
Added and tested the `NO_BALD` flag but only added it to mushmen for the sake of atomicity (and laziness).

@SageOfLight 
re: puffball under hair, the puffball would have to be smaller than the other hairs so it wouldn't peek out. They shouldn't be able to become bald now through shaving or radiation so the hairless sprite won't come up outside of varediting/bugs. I can add puffball as an actual hairstyle if you'd like.

@Buchse 
IMO they look too much like humans with normal legs. Gonna leave them as-is for this PR. Since they're skinnier than humans most things fit okay.

**Comment by SageOfLight** [comment]
@otatoh A big ol puffball would be cool as a psuedo-afro.

**Comment by beesil** [comment]
@SageOfLight 
Will add it in the next mush PR.

**Pull request merged**
