### PR TITLE
Re-paths tools: the remake

### PR DESCRIPTION
**Pull request by DrSnips**
A remake of #29237 because of conflicts.
TLDR repaths tool, adds a parent for them, moves some welder code.

:cl:
 * experiment: Re-pathed common tools. Only a change code wise but MIGHT mess some stuff up. Report any issues with common tools (crowbars, wrenches, screwdrivers, etc.) please.

### CODE REVIEW

**Comment by DrSnips** [comment]
I'm not sure what the issue here is. This branch is made from a pull not even an hour or two old.

**Comment by GreatBigFailure** [comment]
This seems so obvious in retrospect

**Comment by DrSnips** [comment]
I've heard that it's just failing the map render check because of the amount/size of changes. It *should* be ok to go.

**Comment by ghost** [comment]
Test it in something like StrongDMM first, if the environment won't load it's because of code compilation errors, if it shows errors on loading items, it's the map rendering thing

**Comment by DrSnips** [comment]
It's successfully compiles on my end and it compiled here.

**Comment by ShiftyRail** [comment]
🤷‍♂️

**Pull request merged**
