### PR TITLE
Adds a pair of magboots to the captains locker

### LINKED ISSUE #8499: Suggestion: Give Cap his own Magboots
It's always been weird to me that the captain is forced to steal magboots from EVA that are already in short supply if the station gets fucked and he needs to use the spacesuit. giving him his own set of regular boots would prevent him from depriving some poor crewman of not falling all over the place during a singulo or other crisis.

### PR DESCRIPTION
**Pull request by ultraplen**
Fixes  #8499

Possible balance shift but any captain that wants a pair of magboots is just going to steal them from EVA anyways. This way some engineer or something wont be left without boots after the cap ganked em.

Edit: I just now realised there are two extra pairs of boots in EVA, which arguably makes this PR unnecessary.

### CODE REVIEW

**Comment by ghost** [comment]
????

**Comment by ihadtoregisterforthis** [comment]
Write it as Fixes #8499
This way it'll close the issue automatically

**Comment by ultraplen** [comment]
the "Merge pull request #1 from d3athrow/Bleeding-Edge  …" isnt supposed to be there, how do I remove it ? In the commits

**Comment by ihadtoregisterforthis** [comment]
It does nothing though

**Comment by PJB3005** [comment]
> he fucking made a PR to his fork to update it.

For shame.

**Comment by 9600bauds** [comment]
Maybe explain to him how not to do that

**Comment by ultraplen** [comment]
I checked the wiki guide and I realised there is a better way to update my fork, pls no lecture

**Comment by SonixApache** [comment]
git remains a convoluted mystery

**Pull request merged**
