### PR TITLE
reverts fuckup boots

### PR DESCRIPTION
**Pull request by SonixApache**
This reverts commit e1e6d3c11e9c11728e93e1654eb83a6b1cd445d8.

reasoning:
\>take fuckup boots
\>take instant blink
\>become an unstoppable breach machine
\>instant-kill any round 12:06

literally who thought this was a good idea

🆑 
 - rscdel: removed the fuck-up boots

### CODE REVIEW

**Comment by Allspice** [comment]
frick

**Comment by yackemflam** [comment]
You can still get ZAS'd with fuck up boots on

**Comment by SonixApache** [comment]
it doesn't fucking matter when you can just keep clicking on the teleport button and breach everything while sideways

**Comment by yackemflam** [comment]
you only breach if you move, you can't breach while stunned and teleporting doesn't count as moving for the boots

**Comment by Kharkov72** [comment]
why not just make it so you can't use mobility spells when it's active, give it an active-inactive toggle like magboots if it doesn't already have one, and have said toggle have a decent cooldown to not just be asking for a macro

**Comment by ghost** [comment]
please just nerf them instead of removing them they're fricking epic

**Comment by yackemflam** [comment]
They also MASSIVELY slow you down

**Comment by Buchse** [comment]
I hate wizards as the "lmao haha gunk" antag and I hate these boots. I'm in favor of anything that gives wizards less things to play with.

**Comment by ghost** [comment]
actually I changed my mind, if you change it to only remove them from the spellbook I'll give this an updoot

**Comment by tayachiya** [comment]
Make them random-bundle only, like disintegrate

**Comment by yackemflam** [comment]
just make them be unable to use a mobility spell

**Comment by ShiftyRail** [comment]
Make them a spell which activates fuckup during 8 or so seconds (no mobility allowed during those 8 seconds), and then a cooldown of 30 seconds

**Comment by tuypo1** [comment]
Why not just make it so you can't take both fuckup boots and teleport at the same time?

**Comment by SonixApache** [comment]
yeah this isn't the way to go on this

**Pull request closed without merging**
