### PR TITLE
removes N2 tanks from oxygen lockers, adds N2 lockers to arrivals

### PR DESCRIPTION
**Pull request by SonixApache**
Emergency O2 closets shouldn't have tanks in them that O2 breathers can't use.
To make up for it I added N2 closets to arrivals and maint on every map in rotation.
This was already the case for Bagel.

🆑 
 - tweak: O2 lockers no longer have N2 tanks in them
 - tweak: Every map now has N2 lockers near the trader dock, and maybe one or two in maint somewhere

### CODE REVIEW

**Comment by redbluefreak** [comment]
kill yourself

**Comment by IAGFPRMF** [comment]
henk

**Comment by TheFriggenSawbones** [comment]
kill yourself

**Comment by LeonVonFisher** [comment]
kill yourself

**Comment by SonixApache** [comment]
image
you mean like this?

**Comment by CptWad** [comment]
/>adds N2 lockers to arrivals
im sorry but I see no map changes

**Comment by SonixApache** [comment]
F5? The changes are there. Deff, meta, box and packed.

**Comment by ghost** [comment]
The github politics game has grown so convoluted I don't even know what's going on anymore.

**Comment by yclatious** [comment]
You have angered the metaclub sonix, god be with you and may he have mercy on your soul, because the fat furfag autists who play vox will not.

**Comment by Riekland** [comment]
There is literally no reason to have dangerous tanks of N2 in a locker clearly marked O2
This is nothing more than a health and safety update to follow union standards

**Comment by Diavill** [comment]
Vox usually take the extended tanks, scrub them, and fill them with oxygen anyway.

**Comment by Kurfursten** [comment]
Enough joke PRs

**Comment by small-boss** [comment]
who the fuck uses n2 to breathe anyways?

**Comment by Exxion** [comment]
Wait why are people upset?

**Comment by Exxion** [comment]
To clarify:
1. It makes sense
2. Part of vox balance is that their survival equipment is less common and harder to find, and having tanks everywhere kind of defeats that
3. It's moot anyway because vox spawn with, depending on job, one full-sized tank and 1-2 emergency tanks. I have never had to get a tank from a locker, ever. Honestly vox should use more nitrogen but that's a different issue

**Comment by redbluefreak** [comment]
Let me break down why people are responding with kill yourself and stop making joke prs.

Yesterday Pomf decided to whitelist vox for a round or a few, I don't know how long it lasted. He did this without informing anyone, and proceed to watch discord take a shit on itself trying to defend vox and to atleast get a reason for the whitelist. What SonixApache did at that time was make this PR just straight up removing all n2 from every lockers during the shitstorm and even linked it to the discord at the time.

This pr started as a joke pr to go along with Pomfs whitelist "prank" and now he is trying to make it an actual pr

Same shit valk did, make a pr during a vox hate period in discord and wondering why some people don't like it at all. PRs shouldn't be jokes at first then switch to actual non-joke PRs later on. It makes discussion on it into memes and dreams

**Comment by Kurfursten** [comment]
We should remove radios from the lockers too. :thinking: 

1. It makes sense. Radios are not O2 canisters.
2. Part of the telecoms balance is that you have to rely on wall radios, and having mobile radios everywhere kind of defeats that.
3. It's a moot point anyway because depending on your job, you have 1-2 wall mounted radios in your department anyway. Tons more if you work in medbay. Honestly I think there should be less radios but that's a different issue.

**Comment by Riekland** [comment]
God I fucking hate discord so much

**Comment by SonixApache** [comment]
this is not in any way a joke PR
I've been talking about this for a while and finally felt like doing it

**Comment by ihadtoregisterforthis** [comment]
What happened to the "This is a human station" movement?
Otherwise I propose an emergency plasma tank in every cabinet.

**Comment by CptWad** [comment]
^^ just add an alien emergency locker with N2 and plasma tanks ^^

**Comment by Exxion** [comment]
Ah. Yeah I was on the road and haven't been on Discord in a couple days

@Kurfursten Yes, an argument does change when you completely change the thing it's arguing for. Good job.

**Comment by SonixApache** [comment]
public plasma tanks seem like an even worse idea

**Comment by Exxion** [comment]
Plasmaflood in two easy steps with only public materials

Not exactly a lot of plasma, but you don't need much to start a fire

**Comment by ghost** [comment]
You can start a hardcore fire with a pie tin

**Comment by MusgardTiger** [comment]
it is always magical to see vox defense league on work.

**Comment by SonixApache** [comment]
going to wait for all the random mapping PRs that have been popping up to get merged before i resolve conflicts

**Comment by ghost** [comment]
Probably servervote this

**Comment by SonixApache** [comment]
Vote is up. http://ss13.moe/index.php/poll/131

**Comment by SonixApache** [comment]
The poll has closed.
WEAREGO
- 31x yes
- 10x no

Going to clear the maps and add the lockers.

**Comment by SonixApache** [comment]
okay, good to go

**Comment by Shadowmech88** [comment]
Your OP says that you've added N2 lockers to Arrivals, however your changelog says you've added them only to the trader dock and maintenance.
Is the changelog incorrect?

**Comment by SonixApache** [comment]
Updated OP to reflect changes.

**Comment by MadmanMartian** [comment]
what about packed station?

**Comment by SonixApache** [comment]
packed is in rotation and thus recieved lockers

**Pull request merged**
