### PR TITLE
The Bloodlust is now one-handed

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Sundowner
Reworks the Bloodlust to be a one-handed sub-type of the High-Frequency Machete rather than something you need to dual-wield. As a result this also makes it less defensive as it loses the offhand block that counted as a shield, bringing the chance to block an attack to 50%.
:cl:
 * tweak: The Bloodlust, a combined version of two high-frequency machetes, is now one-handed. It also blocks less often.

### CODE REVIEW

**Comment by Eneocho** [comment]
Imagine the high level autismo ninjaing you could do if you somehow got your hands on two bloodlusts.

**Comment by ghost** [comment]
>making the worse esword even worse

**Comment by SonixApache** [comment]
#13913 says that the two-hand/wielding mode was for insta-cutting kudzu and to may sure throwing it is ultra-shit, did you ensure this change doesn't fuck any of its features up?

**Comment by boy2mantwicethefam** [comment]
The kudzu-cutting being defined on both was because both were different type paths, and they both insta-cut kudzu while active. Now the bloodlust doesn't need its kudzu-cutting defined since it is a child of hfmachete, and both have identical procs, so the bloodlust will just activate like the hfmachete and start cutting like the hfmachete does (the same). Throwing it is also shit, but the thing is you can't even throw a Bloodlust in the first place since it sticks to your hand. I've checked and tested my code to make sure my changes did not break anything.

**Comment by Blithering** [comment]
I could have sworn this was onehanded already, I remember picking up two one round a mechanic mass produced them and becoming the human crab

**Pull request merged**
