### PR TITLE
Reverts Nu-Cryo

### PR DESCRIPTION
**Pull request by PrimeDSS13**
Reverts the following PRs: 
#24475, #25339,  #25374,  #25392,  #25393 

It's sat on the flames for a few weeks and has undergone some changes, but it seems that the majority of people just aren't really fans of it. This PR will bring it back to what it was before the cryo rework.

:cl:
 * rscdel: Reverts Nu-Cryo and PRs relating to it, re-implements chem duping.

### CODE REVIEW

**Comment by Kharkov72** [comment]
>it compiled

**Comment by PJB3005** [comment]
Nu cryo is in a good spot now that the balance has been improved. You can speedclone like 3-4 people worst case on a single beaker of dead-simple cryo mix and you can go way beyond that if you're willing to let them sit in the cloner for longer.

If 3-4 clones isn't enough then by the time you're running out, R&D already has bluespace beakers. Even basic bluespace beakers will literally double that and you'd need to *try* to run out.

Also removing nu cryo means there's once again way less incentive to even bother with defibs since the cloner is just flat better again.

Also, I liked actually having to care about the cryo mix as CMO. More shit to manage, more RIDE. Also making stock cryo mix is satisfying as hell so I can't believe you'd rob me of it like this.

:-1:

**Comment by PrimeDSS13** [comment]
>  it compiled

I was surprised as well

> Also making stock cryo mix is satisfying as hell so I can't believe you'd rob me of it like this.

take the COMPLEX MILLION CHEM TUBE pill. Putting loads of 1 - 5u's of chems in a cryo beaker to MINMAX is fun.

**Comment by PJB3005** [comment]
> take the COMPLEX MILLION CHEM TUBE pill. Putting loads of 1 - 5u's of chems in a cryo beaker to MINMAX is fun.

I said stock cryo mix. Not your top tier chemist fantasy.

I mean this one: https://cdn.discordapp.com/attachments/310555209753690112/663552324735598602/simplescreenrecorder-2020-01-06_02.19.03.webm

I've been using this one personally in medbay with 0 issues.

**Comment by robosperg** [comment]
having /something/ to discourage toolbox and clone is good, even if its bad as the dumpster fire of nucryo

**Comment by tuypo1** [comment]
>Also removing nu cryo means there's once again way less incentive to even bother with defibs since the cloner is just flat better again.

which would be solved if cloners just plain didn't work without the full cloning time, that change is all that is needed to fix the speed cloning problem

**Comment by PrimeDSS13** [comment]
>having /something/ to discourage toolbox and clone is good, even if its bad as the dumpster fire of nucryo

We can still work towards that, but people just don't like the way NuCryo function/work. We shouldn't shackle ourselves to this one solution when we can try out other methods that people might enjoy more.

**Comment by PrimeDSS13** [comment]
>having /something/ to discourage toolbox and clone is good, even if its bad as the dumpster fire of nucryo

We can still work towards that goal, but people just don't like how it's being done with NuCryo. There's no need to shackle ourselves to this specific change that people aren't a fan of, we can just revert and find a solution that people enjoy more.

**Comment by ShiftyRail** [comment]
The workers stand united against this unjust, unneeded, and dangerous cryo reform which heavily penalises cryo hardworkers and precarious jobs such as chemists while keeping the bourgeois virologists and geneticists unharmed and favoring the parastic ruling class of medbay : the chloral-addicted capitalistic CMOs

The meager concessions and "reworks" proposed by the github governments are but distractions meant to break the contestation with false compromises, but real downgrade of our hard-earned QoL improvements
They should be taken as signals to amplify and multiply the movement

All united until the revert of this unneeded cryo reform :fist_raised: :fist_raised: 

On ne lâche rien

**Comment by Zth--** [comment]
> we can just revert and find a solution that people enjoy more.

Do that instead. I personally won't merge this. I'm against the "new bad, old good". What do people enjoy more and what can we do to get there? and why nu-cryo fails at that?

I think changes like these are healthy for the game. I've seen people use nu-cryo on very different ways and that's the kind of system we should aim for.

**Comment by Accipitermaris** [comment]
right now, cryo's only use is for clones & genetic damage. and i guess to cool people off for some rare uses. in other words, it's basically only a cloning tube (part 2).

if that's our endgame, we should either totally integrate cryo into the cloning machines OR revert the change and once more make cryo a medical device that has multiple uses for triage and can stabilize patients.

it doesn't need to be so OP, but i don't see what fun interactions we're gaining by turning cryo into cloning episode 2. if the goal was solely to nerf cloning and speed cloning, we should've struck primarily at the cloning pods and their early eject feature

**Comment by jknpj** [comment]
Today i'll remind them

image

**Comment by PJB3005** [comment]
Make cryo have multiple swappable beakers slots so you can swap out the cryo mix to something else depending on what the patient needs. Also allows you more capacity by definition.

**Comment by jknpj** [comment]
I'd also ditch the buffer, too

**Comment by ghost** [comment]
just remove the locking mechanic from the cloning pods goddamn

**Comment by Kammerjunk** [comment]
this PR is the big gay for reasons I've stated many times over
@jknpj cryox and clonex last way longer now, chem duping isn't a thing, and I'm not sure what that last bit might be referring to other than the (really dumb) idea of "just put them in cryo until you can fix them"

**Comment by FudgePucker** [comment]
Unfinished clones should come out as abominations that have a garbled identity, can not talk, and missing limbs and organs. Cloning would be a horrific process IRL, the sheer horrors that are obstructed by that cloudy fluid, what monstrosity would come out if you forced it open. Probably not a person with mild genetic damage.

Unfinished clones should be headed for the surgury room or the incenerator, not the magic healing tube.

Edit:also seeing an unfinished clone should cause a chance of vomiting.

**Comment by tuypo1** [comment]
I don't know about vomiting since it's kind of an obstruction to roleplay, plenty of people have probably seen failed clones dozens of times to the point they got used to it
All the other stuff sounds great though

**Comment by SonixApache** [comment]
needs in-game vote tbh

**Comment by nuklearcellphoneg** [comment]
See now I tell ya what ya need to do now, in order to make your ole 5/5/5/5/5/5/ mixes, see go to Cargo, get fourteen large beakers from cargo, and fill them up with I dunno man, 90u keloderma, 100u bicard, 80u/20u AntitoxHyro,  100u honey, 90u clonex, 90u cryox, so on and so forth, all that good shit right and, now, put 'em on on a big old long table right? Then you grab regular old small beaker and ya do one of two things- you can set all the beakers to like, pour 5u, and make just like a whole bunch of little cryo mixes for any season or situation, or, you grab a syringe, right, then you can just go on and, if you're going for the old 5/5/5, I mean you can just draw from three beakers.

See how the casual medbay players cringe and shrink back from

**Comment by ComradeDispenser** [comment]
Trying to run damage control at the end of a round with a practically non-functioning medbay, nucryo makes this hell. 

I'm not trying to toolbox and clone people, I'm trying to clone bodies that are already basically mangled beyond recognition and get more people back into the round when we need them in a crisis scenario. It makes it especially difficult if you aren't a doctor, you're just trying to save some folks with the only help in the department being a mediborg, who are physically incapable of preparing new mix to refill the tubes when they run dry.

**Comment by PJB3005** [comment]
Then smash into chemistry if you have to. it takes all of one minute to refill the cryo tubes.

**Comment by Kammerjunk** [comment]
damage control is part of the ride
not saving everyone is part of the ride
medborgs can (given an extra minute or two) make a mix

**Comment by FudgePucker** [comment]
Or break into mechanics or science to use their chem dispenser if medbay is trashed.

Edit:if you want to min max chems into clones, just make pill bottles filled with horse pills for clones coming out of the cloner before you stick them in cyro.

**Comment by Kammerjunk** [comment]
If you could set injection rate in cryo at roundstart, it would be a great system: there are multiple viable mixes (I have looked at a few myself) that still get spent during the round, meaning that you have a reason to do any other treatment than clone/cryo, and you're rewarded for having any idea what you're doing without being completely useless if you don't

meme mixes literally (figuratively) never happened stop pretending you made super sick mixes

**Comment by aceedex** [comment]
My mixes are the sickest, dont pretend they arent

**Comment by KingofHONK** [comment]
Remove medbay imo. If youre shit enough to die at this game you deserve to go play tg with all the other babies.

**Comment by d3athrow** [comment]
remove cryo

**Comment by yackemflam** [comment]
If cloners are the problem, then nerf cloners, not cryo

**Comment by yackemflam** [comment]
Nerfing cryo also hurts defibs too and I think that coders needs to take a step back and look at their arguements
You could always make autism cryomix, before and after
Cloning then cryo is objectively harder/takes longer to do unless the body is fubar
The problem with cloning isn't cryo, it's how piss easy cloning is.
You just attach an IV drip full of chems to a monkeyman and you get enough synthmeat to last the entire round and then some

This doesn't help that there's no real downside to speed cloning other than taking up more of the cryomix

And this is from a person who LIKES nucryo

Also medbay mains tend to be autistic about any and all nerds to medbay despite how piss easy it is

Everyone is autistic why am I even rambling here

**Comment by Kammerjunk** [comment]
what the fuck did you just say

**Comment by aceedex** [comment]
Nucryo does nothing.
So what is the point

**Comment by Exxion** [comment]
dude just make the tubes directly call `on_mob_life()` of the reagents in it on the mob in it to simulate the old chem duping behavior without actually duping them

**Comment by tuypo1** [comment]
Yackem is right cloning is what needs major nerfs

**Comment by Kammerjunk** [comment]
no he isn't and he isn't because what @aceedex said is factually not true
also speedcloning is not even part of this issue

**Comment by yackemflam** [comment]
speed cloning is absolutely part of the issue

**Comment by ghost** [comment]
speedcloning is absolutely not THE issue, if you want to reduce reliance on cloning there are better ways to approach it than making it slower or more tedious

**Pull request merged**
