### PR TITLE
fixes switchtools being unable to remove modules

### LINKED ISSUE #15182: All switchtools cannot have their modules removed.
Holo switchtool pr made is so you couldn't remove modules from all switchtools rather than just the holo switchtool.

### PR DESCRIPTION
**Pull request by Intigracy**
fix https://github.com/vgstation-coders/vgstation13/issues/15182

also quite a bit of cleanup

~~still need to test~~
It works.

### CODE REVIEW

**Comment by DrSnips** [comment]
You want to toss the other switchtool fix in with this pr or make a seperate one for it? It's the one to fix switchtool hacking here #15130.

**Comment by Exxion** [comment]
Actually I think I'll do that
It's occurred to me that the proc solution has other uses

**Comment by Exxion** [comment]
You ever get around to testing this?

**Comment by Intigracy** [comment]
Not yet, I will tomorrow.

**Comment by gbasood** [comment]
2
days
later

**Comment by DrSnips** [comment]
On another note, how's the switchtool hacking fix going @Exxion ? The code to fix it already exists to fix that issue but you were saying something about fixing it along side something else?

**Comment by Exxion** [comment]
Sorry I've been busier than expected
I'll do it soon

**Comment by Intigracy** [comment]
Whoa I completely forgot about this, testing it now.

**Comment by Intigracy** [comment]
It works.

**Pull request merged**
