### PR TITLE
Ambience subsystem

### PR DESCRIPTION
**Pull request by FatCat1978**
Replaces the ambience """system"" on area/entered or whatever it was with an actual subsystem. probably works. I've tested it a little.

some issues I need to work out/have someone spoonfeed.

* space uses the "generic" ambience. I can't change this without fucking up literally every other area, as everything's a child of space.

* I could probably do some hacky shit in /New to replace it if the name's "space", but I want to think about a better way to do it before doing that.

### CODE REVIEW

**Comment by FatCat1978** [comment]
No clue why travis is failing. should compile

**Comment by ShiftyRail** [comment]
`code/game/area/areas.dm:433:error: Obj.areaMaster: undefined var`

Don't use areaMaster, I think we /getArea/ now

**Comment by FatCat1978** [comment]
man I don't update my branch for 3 days and there's new fangled stuff. I'll reopen this eventually:tm: with a clean branch.

**Comment by Exxion** [comment]
That change was quite a bit more than three days ago dude

**Pull request closed without merging**
