### PR TITLE
Add "WOAH MAMA" as a brain damage line

### PR DESCRIPTION
**Pull request by TheManNamedTom**
In memory of the late bobthomas (RIP)

### CODE REVIEW

**Comment by Kharkov72** [comment]
>+110 -109 adding a single line

🤔

**Comment by SonixApache** [comment]
good job on the whitespace changed you big idiot

**Comment by jknpj** [comment]
pls fix

**Comment by jknpj** [comment]
Ping me if you want to fix/reopen this

**Pull request closed without merging**
