### PR TITLE
Storage QoL HOTFIX

### PR DESCRIPTION
**Pull request by The-Albinobigfoot**
I'M SORRY BAUDS

### CODE REVIEW

**Comment by 9600bauds** [comment]
It's a good thing I already tagged the PR 100% tested!

**Comment by The-Albinobigfoot** [comment]
UNTAG IT, QUICK

**Comment by 9600bauds** [comment]
It's supposed to be a sarcasm tag :^)

**Comment by The-Albinobigfoot** [comment]
Oh, well, good job bauds!
btw this is :100:% :ok:

**Comment by clusterfack** [comment]
coders

**Pull request merged**
