### PR TITLE
Reworks various speech replacements into wordfilters

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[tweak][content]
Mostly species and disabilities.
:cl:
 * tweak: Many speech filters are now converted to regex speech_filter datums.
 * rscadd: Wordfilters are more fun now in general.

### CODE REVIEW

**Comment by Eneocho** [comment]
Does this solve the lowercase "Th" when yelling while lisping or the lowercase "ss" when yelling as skeleman?

**Comment by SECBATON-GRIFFON** [comment]
> Does this solve the lowercase "Th" when yelling while lisping or the lowercase "ss" when yelling as skeleman?

doesnt with catbeasts so no

**Comment by Eneocho** [comment]
> 
> 
> > Does this solve the lowercase "Th" when yelling while lisping or the lowercase "ss" when yelling as skeleman?
> 
> doesnt with catbeasts so no

How about the double "thth" when saying a word with "ss" somewhere (assassin becomes aththaththin).

**Comment by Eneocho** [comment]
Can you add a clause to NOT call some regex when speaking in certain languages? Like not lisping while clattering the bones, blubbling with slime, grinding joints with golem or farting with clown? For the immulsions. Related: #29242

**Comment by SonixApache** [comment]
Cool, need to remember this for the ninja wordfilter that's supposed to be in.

**Comment by Kurfursten** [comment]
This is nice, great to datumize this and make it more OOP. Is this bauds?

**Comment by SECBATON-GRIFFON** [comment]
> This is nice, great to datumize this and make it more OOP. Is this bauds?

no im goofball, clearly

**Pull request merged**
