### PR TITLE
NT Microstation fixes

### LINKED ISSUE #31476: Ministation
(WEB REPORT BY: sootybear42 REMOTE: 206.221.180.138:7777)
# Revision
ad228795b09491ed99577e0a0cca55e8851adce3

# Description
Ministation Issues-Since it's flipped sometimes the double doors are broken and there isn't a destruction analyser or chem dispenser to do research
# Steps to Reproduce
Find ministation doors broken
# What you Expected
Doors to be normal
# What Actually Happened
Doors not normal and flipped

### LINKED ISSUE #31553: NT Microstation vault lacks a Deconstructive Analyzer and Science Access issues.
In order to do research in general you need a DA to dissolve shit into tech levels. There is no such thing on microstation. Also, the circuitboards are unusable since you don't have science access to link the machines to the RnD console. 
Please map the machines themselves instead of circuitry and add a DA and Protolathe, pretty please.
[vault]

### LINKED ISSUE #31669: Ministation Engineering Design Errors
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
552d870af550fda58189a4cc0a136b70e0361e5d

# Description
Various bugs on Ministation (cool hobo-spawn vault!) related to engineering:

1) Disconnected atmos pipes in various areas.
2) Incorrectly set up SMES, there are two terminals attached to the APC below it and none to the SMES.
3) The power input from solars currently goes into the cable knot underneath the SMES. This is backwards. It needs to go into the SMES terminal (which isn't connected, despite the double-terminal below it attached to the APC). Power should output from the cable knot below the SMES.
4) No cable knots under the solar panels or solar tracker, so solars do not work until knotted. This is hard to notice because of the floor tiles under the solars.
5) Station does not use power (except for SMES when properly reset, provided by solars when properly reset).
6) Atmos straight up does not work for some reason, this may be related to in-game antics (admin was unable to tell if atmos was working somehow?) but should be checked.

### LINKED ISSUE #32097: The donut box on the NT Microstation is empty
#### Description of issue
On the NT Microstation, there is a donut box that shows it has donuts, but actually has no donuts

#### Difference between expected and actual behavior
Expected: Donuts
Actual: Box shows donuts, has no donuts

#### Steps to reproduce
Become a space hobo
Spawn on an NT Microstation
Go to the donut box
Find there aren't any donuts
starve to death

#### Specific information for locating
NT Microstation

[consistency] [bugfix]

### PR DESCRIPTION
**Pull request by ghost**
[vault][bugfix]
Closes #31476.
Closes #31669.
Closes #31553.
Closes #32097.

:cl:
 * bugfix: NT microstation now drains power.
 * bugfix: NT microstation solars and SME wiring is now proper.
 * bugfix: NT microstation donut box now has donuts in it.
 * bugfix: NT microstation now has manifold pipes initialise properly.
 * tweak: NT microstation now has a protolathe and DA circuit, as well as proper access on the circuit for the R&D console.

### CODE REVIEW

**Comment by Eneocho** [comment]
Is it too much to ask for an audio system so you could link the microstation juke and have music everywhere?

**Comment by DamianX** [comment]
Why is this a draft?

**Comment by Cartlord** [comment]
I just want to point out that, the one time I got to be on MicroStation, there was one room with no vents and completely fucked atmos so I got trapped by firelocks and had to break a window to leave.
Maybe fix that?

**Comment by ghost** [comment]
> Why is this a draft?

Couldn't get pipes to work, dunno how to load the vault in before initialisation of objects specifically to test them fully.

**Comment by DamianX** [comment]
You could hardcode a call to `load` the map element in `/datum/subsystem/map/Initialize`

**Comment by ghost** [comment]
Found another way to get it working, pipe issues fixed now.

**Pull request merged**
