### PR TITLE
Adds salt to pAI's Chemical Synthesizer

### PR DESCRIPTION
**Pull request by jknpj**
Adds salt to pAI's Chemical Synthesizer

pAI can now deal with borers fucking up with their masters.

:cl:
 * rscadd: "Adds salt to pAI's Chemical Synthesizer"

### CODE REVIEW

**Comment by ghost** [comment]
The war between borers and pAIs begins.

Borers have EMPs, pAIs have salt.

**Comment by Shadowmech88** [comment]
:+1: , though ideally a borer fucking up its host would just be banned.
They're not supposed to do that.

**Comment by 9600bauds** [comment]
ruh oh spaghetti-o's does pAI chem synthesizing have no HREF sanity whatsoever

**Comment by Intigracy** [comment]
H o n k

**Comment by Intigracy** [comment]
This can also be used to fuck with a human that isn't your master that steals you and has a borer.

**Comment by Intigracy** [comment]
Or salt plus smoke.

**Comment by Intigracy** [comment]
Think of the possibilities!

**Comment by Probe1** [comment]
image

how did this even happen

**Comment by Shadowmech88** [comment]
By not deleting the extra entries from the example in-body changelog.
That block is commented out so we don't see it, but maybe the bot does?

**Comment by Probe1** [comment]
Oh.

@jknpj you have to write the changelog at the BOTTOM.  It will parse /everything/ including the examples.  I think you already figured it out but just as a reference for anyone else.

**Comment by jknpj** [comment]
Learned my lesson

**Pull request merged**
