### PR TITLE
Deff requests by users

### PR DESCRIPTION
**Pull request by Probe1**
**(Deff)** Adds lights to xenobio slime cages 
Resolves https://github.com/vgstation-coders/vgstation13/issues/16874 https://i.imgur.com/SKj9k0C.png
**(Deff)** Adds monkey cube box bringing total to 3 in line with Metaclub
Resolves https://github.com/vgstation-coders/vgstation13/issues/16972 
**(Deff)** Adds air conditioner objects to maintenance.  I paired them around heater objects.
Resolves https://github.com/vgstation-coders/vgstation13/issues/16669
**(Deff)** Adds fire alarm to Bar
Resolves https://github.com/vgstation-coders/vgstation13/issues/16562 https://i.imgur.com/bfOcMcR.png
**(Deff)** Moves atmos alarm in Bar to be in range of the cameras for the AIs benefit.
Resolves https://github.com/vgstation-coders/vgstation13/issues/16561
**(Deff)** Adds garbage chute to Vox Outpost
Resolves https://github.com/vgstation-coders/vgstation13/issues/17305 https://i.imgur.com/uWAfllw.png
**(Deff)** Adds NT Default board to AI Upload.
Resolves https://github.com/vgstation-coders/vgstation13/issues/16882 https://i.imgur.com/Kp7jxR6.png

Please god don't give me map cleaner issues.  
Tested, compiled, things looked normal.

🆑 

* rscadd: Deff has had the following things added.  NT Default board in AI Upload.  Fire alarm in bar. Additional monkey cube in xenobio.  Lights in xenobio slime pens. Air Conditioners in Maintenance.  Garbage chute and trash bin in Vox Outpost. 

* tweak: Deff Bar atmos alarm moved to be in range of cameras for the AI.

### CODE REVIEW

**Comment by Probe1** [comment]
Whoever took my collab away gets the noose.  I'm bothered that I can't label this.

**Comment by Zth--** [comment]
Hi Probe. I missed you

**Comment by Probe1** [comment]
Hey dude.  I hope whatever your issues you need saving from can be fixed by casually mapping while watching baby driver.

**Comment by Kurfursten** [comment]
How do you feel about these?

untitled

**Comment by ShiftyRail** [comment]
Welcome back

**Comment by Probe1** [comment]
@Kurfursten they're fine but I'm not going to wangjangle it into this PR.  Medbay looks fine too.  Why do sleepers/scanners not have consoles?

**Comment by Kurfursten** [comment]
Consoles must be purged. Those of you who have the strength to save this code base, follow me -- the rest of you, get out of my sight.

In all seriousness though the consoles have caused years worth of snowflake headaches with their directionality and need for two components that reference each other and it's time for that particular meme to end I believe.

**Comment by Shadowmech88** [comment]
Is it not possible to make consoles true multi-tile objects, in the same way spacepods are, instead of two separate objects which smooth together?

**Comment by Probe1** [comment]
Images added, extra change added because I forgot I did it, and PRs been locally compiled, hosted, and tested.  Its good to go by my standards.

**Comment by Kurfursten** [comment]
@Shadowmech88 Perhaps not the best place to discuss it here since Probe isn't interested in waiting up for the refactor, but yes -- there is, by making them width = 2. It's actually apparently quite easy (just see multi_tile.dm for the more apt 2x1 airlock used in old pod doors). The question of whether we want that can wait for my own PR.

**Comment by Probe1** [comment]
idgaf I'm just not adding more onto this here pee arr lest I fuck something up or it sits in PR Conflict Hell.

**Comment by Probe1** [comment]
nani?

**Comment by Shadowmech88** [comment]
It looks like you might have force-pushed an out-of-date version of your branch. Since your branch is now even with Bleeding-Edge, the PR auto-closed.

**Comment by Probe1** [comment]
Yeah I listened to Celt who promised it wouldn't cause issues.  I listened to Celt.  I'm sure it's recoverable and if not it was like 10 minutes of work and 20 minutes of downloading byond.

**Comment by Shadowmech88** [comment]
It seems you also made the mistake of committing your changes to your Bleeding-Edge branch instead of making a new branch for the PR.

**Comment by Probe1** [comment]
Yeah.  Anyhow I'm just going to walk away https://github.com/vgstation-coders/vgstation13/pull/17460

**Pull request closed without merging**
