### PR TITLE
Maintenance Security Override and other stuff

### PR DESCRIPTION
**Pull request by toomykins**
[content] [tweak]
Definitely not the most atomic thing i've proposed.

- Security Officers no longer have Maint tunnel access on security level Green
- Security Officers gain Maint tunnel access on security level Blue
- Heads of Staff can swipe the keycard device to limit maintenance to Security only on Security level Red.
- Revocation of Maintenance overrides no longer requires an additional swiper on the keycard device.

Just bully me in the comments if you dislike it or want it split into different PR's.
Also added a neat little sound for the maint sec override; https://vocaroo.com/1iHj5iSU9gBr

:cl:
 * tweak: Security Officers no longer have Maint tunnel access on security level Green.
 * rscadd: Security Officers gain Maint tunnel access on security level Blue.
 * rscadd: Heads of Staff can swipe the keycard device to limit maintenance to Security only on Security level Red.
 * tweak: Revocation of Maintenance overrides no longer requires an additional swiper on the keycard device.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Sounds good, this allows for some intrigue at least for a little while such that Security doesn't just scour Maintenance casually

**Comment by ghost** [comment]
This is a bad take. There is no reason to limit security access into maint on any alert level. This will not solve anything, just increase the steps you need to take to access maint. Furthermore it will just be annoying to deal with.

So i say nay. Also stop following each others ridiculous posts with less ridiculous ones in order to pass the changes you want, like a pack of hyenas biting at the ankles of a zebra, you fucking c*der fiends.

**Comment by Kammerjunk** [comment]
the door has been opened again

**Comment by BomberBro** [comment]
Bad PR that either means perma code blue or sec being unable to get where any crime gets committed. Lots of effort for it though. I don't know the recent fascination with muddling around with maint access but it's gotten to the point where we have this PR where maint becomes something less for actual maintenance and a gameplay zone where antags can escape security.

**Comment by gurfan** [comment]
but why should their maint access be limited

**Comment by Dacendeth** [comment]
security not having it on greens a little weird, the rest seems okay.

**Comment by APCUnlocked** [comment]
Why would shaft miners have maint access but security officers not? Makes absolutely zero sense. Being able to limit maintenance access during code red is actually something i'd like to see though.

**Comment by ghost** [comment]
A very suitable compromise.  I like it a lot.

**Comment by TGFH** [comment]
Wow, it's almost like someone said this exact thing would happen in the comments on the other PR. What a shock.

**Comment by toomykins** [comment]
it seems to me most people don't like the 
- Security Officers no longer have Maint tunnel access on security level Green
- Security Officers gain Maint tunnel access on security level Blue

part. if I removed that would you vote for this PR? I can't find a deeper compromise in that.

**Comment by gurfan** [comment]
having the option to restrict maint access to only security is silly too, it's not a dedicated valid zone

**Comment by APCUnlocked** [comment]
Should make it emergency services only (security/engineering/paramedic) during code red, not sure if that's possible though

**Comment by dunsel-hordon** [comment]
seems like a good compromise. Would still say any job besides engineers should not have maint access.

**Pull request closed without merging**
