### PR TITLE
The Plate-less update

### LINKED ISSUE #30361: Sandwiches made with Nova Bread don't keep the Nova Bread's chems.
#### Description of issue
Title.
#### Difference between expected and actual behavior
Expected the novaflour and shit to still be on the sandwich, instead I only got some lame nutiment.
#### Steps to reproduce
Make nova bread.
Slice it.
Stick some food on top of it.
Scan with reagent scanner and see that the novaflour inside the nova bread is gone.
[bugfix][oversight]

### LINKED ISSUE #30362: Sandwiches made with novabread have the regular bread icon.
#### Description of issue
Novabread is light blue, so sandwiches made with some should logically have light blue bread. But when you make a sandwich with some novabread, the sandwich bread comes out brown, like a normal piece of bread.
#### Difference between expected and actual behavior
Expected cool looking sammich made with wacky bread.
Got generic looking bread sammich.
#### Steps to reproduce
Make Nova Bread.
Slice it.
Make a Sandwich.
Cry because your cool sammich isn't real.

[consistency][sprites]

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #30361
Fixes #30362

blueplatesslicedno_platelotsaplatesnovacrashimageimageimage

:cl:
* rscadd: Plates can now be stacked up, whether they are dirty or clean. You can clean a whole stack at once using soap. Be careful not to slip while carrying them.
* rscadd: You can remove plates from a stack either with an Alt Click, or a Mouse Drag onto yourself. Alternatively, clicking a stack with a food item will add a plate to it in your hand directly.
* rscadd: The Dinnerware now provides 5 stacks of 10 plates each, for a total of 50 plates, up from 20.
* rscadd: Plates now inflict 5 brute damage when thrown. They also have a 70 percent chance of shattering this way. Throwing a whole stack applies the chance to each individual plate but the damage isn't increased.
* rscadd: Infected food will transmit its diseases to custom snacks it is added to, including plates. The dirty plate will keep those diseases as well, so there is now some purpose to cleaning them up before using them again.
* imageadd: Plates have been removed from the sprites of most food items that had them.
* imageadd: Plates now have in-hand icons. Placing food on plates will give them the in-hand icon of the food item used.
* rscadd: Plates can be set up to look different depending on the food item, and have the item appear at an offset, which is useful for sprites that have visible pixels going below where the plate should be, such as for the dripping cheese on cheesy meat loafs.
* bugfix: Fixed custom sandwiches made using sliced nova bread not using the correct sprite nor carrying the nova bread's reagents. (eneocho)
* bugfix: Animated food items no longer stop animating when placed on a plate, such as for birthday cake slices.
* rscadd: Eating food without a fork now has a chance of spawning some crumbs under you. The crumbs are colored depending on the food item eaten.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
Make it so stacked plates let you throw a single plate from the stack one at a time, like ninja stars. Maybe make it require two-handing the stack for both logic and to allow you to throw the whole stack at once if you want.
Also, quality addition, good work

**Comment by Eneocho** [comment]
> 
> 
> Make it so stacked plates let you throw a single plate from the stack one at a time, like ninja stars. Maybe make it require two-handing the stack for both logic and to allow you to throw the whole stack at once if you want.

This holy fuck, this. NEED.

**Comment by kilozombie** [comment]
Doing more work to make cooking fun than Goof ever did

**Comment by amikawaii** [comment]
Do plates have a shatter chance if you slip while carrying?

**Comment by DeityLink** [comment]
>3am, lying in bed with my smartphone
>good day of spriting and stuff, time to sleep
>suddenly, a notification

> Do plates have a shatter chance if you slip while carrying?

Why can't I help myself coding good ideas right as I read them. I need to turn off my notifications.

**Pull request merged**
