### PR TITLE
New Excavation Suit Sprite

### PR DESCRIPTION
**Pull request by kol1th**
# Scope of PR

Adds a new excavation suit sprite. Skowron sprited it. The helmet's visor is a bit transparent, so you can see your face through it.

# Screenshotties
image
image

# Changelog
🆑 
* imgadd: The excavation suit now has a new sprite, thanks to Skowron!

### CODE REVIEW

**Comment by ghost** [comment]
make the old sprites something you can find through xenoarch

**Comment by kol1th** [comment]
Sure I'll do that in another PR.

**Comment by 9600bauds** [comment]
Hey this actually looks good, what server did you steal it from? ;^)

**Comment by Exxion** [comment]
>Skowron sprited it.

**Comment by 9600bauds** [comment]
is what is joke

**Comment by 9600bauds** [comment]
is what th joke

**Comment by Probe1** [comment]
God bless it I wish @N3X15 had never scripted more sprites into a dmi than it should be allowed to have I'm always nervous and check the DMIs when someone modifies clothing.

**Comment by N3X15** [comment]
So use more than one DMI, you dingus.

Also, you can make a python script that extracts the Description field from the DMI and parses it to see how many states it has and have Travis send out a warning if there's 512

**Comment by Probe1** [comment]
I know I just don't have the energy to depreciate all these overstuffed DMIs so I can rest easy when someone adds sprites and not check to make sure they didn't do something dumb without realizing it.

**Comment by SonixApache** [comment]
How do .dmi files handle folders? I wouldn't mind spending a few days trying to disperse the sprites as long as byond can handle them being seperated in a non-retarded way.

**Comment by gbasood** [comment]
this looks really familiar and i cant remember what it's from

**Comment by PJB3005** [comment]
@SonixApache they're just files in a file system, you can put them in folders.

The problem is the human icon code may not allow using different DMI files for the on mob overlays.

**Pull request merged**
