### PR TITLE
Malfunctioning AI Module: Explosive Hardware

### PR DESCRIPTION
**Pull request by gurfan**
New module available for Malfunctioning AIs: Explosive Hardware.

Causes your core and your cyborgs to create a small explosion upon death, after few second delay.
Your core will also play a noticeable sound before it is about to explode, giving people a chance to get away.

:cl:
 * rscadd: Malfunctioning AIs can now rig their core and their cyborgs to explode upon system failure.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I'm pretty sure the malf AI core already explodes on death

**Comment by gurfan** [comment]
It does not.

**Comment by boy2mantwicethefam** [comment]
I knew it did
At least the malf AI from the space vault explodes on death

**Comment by gurfan** [comment]
The malf AI from the space vault explodes because it has var/explosive set to 1.  Regular malf AIs don't have it set to 1 normally, this module changes that.

**Comment by boy2mantwicethefam** [comment]
fair enough

**Comment by Blithering** [comment]
Good for when the science team are trying to turn the AIs borgs against it by salvaging the wrecks.

**Comment by tuypo1** [comment]
Is the core explosion bigger than the borg explosion? I feel like it should be, far bigger even

**Comment by gurfan** [comment]
Slightly bigger

**Comment by SonixApache** [comment]
fix your :cl:

alert the collabs

**Comment by gurfan** [comment]
dun

**Pull request merged**
