### PR TITLE
Adds a toggle instrument preference

### PR DESCRIPTION
**Pull request by MadmanMartian**
After somebody was playing megalovania at ultra high speed on 6 different instruments at once, triggering my tinnitus, I personally need this, not sure about others.

:cl:
 * rscadd: Adds a preference toggle for hearing instruments.

### CODE REVIEW

**Comment by Irradiation** [comment]
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by jknpj** [comment]
i deaf pls nerf

**Comment by iFlashYou** [comment]
[Balance]

**Comment by Kitfox88** [comment]
had a bad time huh

**Comment by Chazach** [comment]
this is broken and keeps giving the blue goo all over the chatbox when adminned
ADMIN LOG: Error #: 0 - 
ADMIN LOG: Error #: 1 - no such column: hear_instruments

**Comment by SonixApache** [comment]
database gas

**Pull request merged**
