### PR TITLE
Gives warden binoculars and a custom baton >WIP

### PR DESCRIPTION
**Pull request by ghost**
WARDEN NEEDS SOME LOVE
their locker now starts with binoculars and a custom baton instead of an electric one, since TWO binoculars on station is lame the detective gets nightvision goggles instead of binoculars
the binoculars makes sense since you can watch more of brig through it
or maybe the detective should have both? right now detective doesn't start with any sechud
Maybe I should specific that the classic baton looking baton works like a normal sec baton but a bit better
:cl:
 * rscadd: warden now starts with custom baton and binoculars in their locker
 *rscadd: Detective now starts with nigh vision goggles instead of binoculars

### CODE REVIEW

**Comment by Anton-Kr** [comment]
Classic baton is power creep as fuck tbh.

**Comment by Shadowmech88** [comment]
It should be noted that the binoculars will double the view that the warden gets from all cameras, as well.

**Comment by ghost** [comment]
yes i know about the cameras, classic baton has a lower stun time than regular right?

**Comment by ghost** [comment]
maybe i should sprite a custom warden baton?

**Comment by Shadowmech88** [comment]
The classic baton is also capable of stunning borgs.

**Comment by ihadtoregisterforthis** [comment]
Classic baton is infinite instant stuns

**Comment by ghost** [comment]
>capable of stunning borgs
rip nvm this will never get merged with the silicon metaclub

:^)

**Comment by SonixApache** [comment]
fuck off

**Comment by ghost** [comment]
alright fags i'll just make a new baton for warden

**Comment by ghost** [comment]
image
OFF SPRITE

**Comment by ghost** [comment]
what if i make the PR entirely about the baton then

**Comment by Ephx1** [comment]
This is embarrassing

**Comment by ghost** [comment]
not really
JUST NEED TO GET THE SPRITE TO WORK

**Comment by ghost** [comment]
Oh yeah the custom stun baton will be a child of the normal sec batons

**Comment by ghost** [comment]
maybe I shouldn't​ make PRs when in really tired instead of waiting till the next day :thinking:

**Comment by yclatious** [comment]
You are bumfuck retarded if you think giving the most robust non traitor weapon out there to wardens roundstart, especialy with a shitty sprite to boot, alongside a detective only item meant to be used by detectives only is a good idea.

Also, you gave the detective night vission goggles. This isnt /TG/, you cant powercreep random crap just because you feel like shit needs to be more action focused, detectives dont even start with sechuds because they arent meant to do arests and shit, they are meant to investigate crimes first and foremost, not be sec with a 10 brute balistic taser and scanner, why would they even have a sechud?

**Comment by ghost** [comment]
It's gonna be a sec baton but with a slightly high stun time and charge use

**Comment by ghost** [comment]
Detective doesn't even get normal sunglasses for when the warden sets up flashers and he has to go to security, I could just make it sunglasses instead.  Don't see how it's so much power creep if it's just better mesons and you can get mesons roundstart

**Comment by yclatious** [comment]
A warden already has acess to stun batons all he wants or pleases and he can also order more by cargo. Your sprite is shit and the baton is useless, he doesnt need a unique item at all, especialy one that looks like shit when he can already get as many as he wants, either by going to the armory himself or using mythical interdepartmental interaction. Your special item is the fucking batering ram, your glorified all acess card, the whole armory and locking down perma, if these aint good enough shame. 

Its night vision goggles. Why would a detective ever have night vision goggles at all, how would it help in his job in any way, shape or form, he is a hired detective from nanotrasen, why the fuck does he have military grade equipment when he was asigned to a fucking research station to just investigate crimes and determine the culprit, he isnt even part of sec, he has no reason to be given, granted or permitted the ownership of shit used by operatives when he just determines who did crimes. Sunglasses would make sense but fucks sake, night vision goggles? Its gonna be X but its still Y, fuck off with your shitty TG tier balancing.

**Comment by jknpj** [comment]
https://www.youtube.com/watch?v=ugJfjmxOR2I

**Comment by ghost** [comment]
Night vision goggles let you detect things better
>Shit sprite

NOW THAT'S TOO FAR should I have gone with a nanotrasen color scheme?
>Battering ram

Wardens just law 2 AIs to open doors and if it's a rogue ai good luck not being shocked  though it's still pretty good but rarely used
The baton is supposed to mostly just look cool but it'll also stun for longer and consume more charge

**Comment by SonixApache** [comment]
Warden does not need a classic baton for any reason, stun batons are fine. If he really wants one he can be useless and fuck off to the derelict like everybody else.

Detective does not need roundstart NVGs for any reason, sunglasses are fine. If he really wants them he can be useless and fuck off to the satellite or R&D like everybody else.

this is a dumb PR

**Comment by yclatious** [comment]
Military equipment that a actual detective doesnt need, be a good goyim coder and dont start overequiping departments or people in the departments.

Honestly, just ask a spriter for one, you suck at spriting. If you want to have him have his own special baton, I dont isagree, so long as its a resprited normal baton instead of a police one.

Doesnt matter, its still a good item, negated or not by law 2s and roggu AIs. If its purpose is to look cool, resprite, no on the longer stun or more charge. Sonix is completely right, this is dumb as shit man, make some changes or this is unsalvageable shit.

**Comment by ghost** [comment]
It'll be a resprited sec baton that looks like an energy classic baton

I'll change the NVG to sunglasses when I can

**Comment by SonixApache** [comment]
They already have a special coat, hat, and other unique gear.
Why would you give more stuff to a job that should barely move?

**Comment by ghost** [comment]
To wave your fancy glowing baton at prisoners

**Comment by ghost** [comment]
Is MUH sprite really that bad?

**Comment by yclatious** [comment]
Ive seen a bowl of leftover fish rot for over 2 months and leave a unremovable mark on a wooden furniture piece. It looked better than your sprite.

**Comment by SonixApache** [comment]
kill this PR and code something useful like prescription sec/medHUDs

**Comment by AI-Is-Rogue** [comment]
I would prefer the detective to keep the binoculars. I see more use of them in the detective's hands than the warden's.

**Comment by ghost** [comment]
Or port more underwear

**Comment by ghost** [comment]
I'm only disappointed about the feedback about MUH sprite tbh

**Comment by yclatious** [comment]
If I never sprited and still managed to do a balloon inhands, you could have done a better sprite for a baton my lad. Also, please just edit posts or something, the constant double or tripple posting gets annoying quick.

**Comment by ghost** [comment]
Did I forget to mention is has an ON animation that glows

**Comment by Chazach** [comment]
that sprite looks like absolute shit, the warden already has his /fa/ hat and jacket for custom items

**Comment by ghost** [comment]
Im bad at spriting also 2many custom items

**Pull request closed without merging**
