### PR TITLE
Remove the crystal xenoarch artifact.

### PR DESCRIPTION
**Pull request by PJB3005**
It did literally nothing except drop glass shards on destruction.

:cl:
 * tweak: Lowered the find rate on the "crystal" xenoarch artifact. It did literally nothing except infuriate xenoarchs.

### CODE REVIEW

**Comment by Riekland** [comment]
I dun get it
aren't useless artifacts that you have to make up your own lore for the whole point of xenoarch

**Comment by PJB3005** [comment]
@Riekland we're not Bay. We don't care about "lore" or such.

**Comment by Aurx** [comment]
We're not TG either, we don't ignore "lore" completely in favor of power gay man.  

That said, RNG screwing your artifacts is badong.

**Comment by clusterfack** [comment]
Boo, this artifact was hilarious

**Comment by RealestEstate** [comment]
one time I found like 4 of these in the row and gave them to the chaplain. they make for some cool decorations.

**Comment by PJB3005** [comment]
Could make them a rare dig site find.

**Comment by RealestEstate** [comment]
sure, that would be better than just removing it, imo.

**Comment by gbasood** [comment]
@PJB3005 are you gonna do that or nah

**Comment by PJB3005** [comment]
Not sure I can be bothered...

**Comment by PJB3005** [comment]
Ah fuck it fine.

**Comment by gbasood** [comment]
changed your changelog a bit for you

**Comment by PJB3005** [comment]
> lowered find rate

That's not even remotely close to what I did...

**Comment by gbasood** [comment]
\>Could make them a rare dig site find.
did I misinterpret that then
I'll just nag people to update changelogs before merging from now on

**Comment by Exxion** [comment]
Yes, please do that instead of just guessing

**Pull request merged**
