### PR TITLE
packedstation.dmm tweak, adds Derelict RnD server and console, fixes Fore Starboard radiation tiles

### PR DESCRIPTION
**Pull request by bthomas2**
:cl:
* rscadd: Packed: added Derelict RnD server and console, floorpill spawner.
* tweak: Packed: added items for captain, HoS.
* bugfix: Packed: fixed F/S radiation.

Gave the captain a gold coin, a new cigar, and a zippo. Moved his matchbox to the new ashtray in his office. Gave the HoS a painting, a cigar, and a zippo. Added a floorpill spawner in the arrivals space airlock. Changed area above medbay to be fore starboard instead of medbay.
#24587 

packed3
packed1
packed2

### CODE REVIEW

**Comment by N3X15** [comment]
Could you describe the minor tweaks, please?

**Comment by bthomas2** [comment]
edited

**Comment by Intigracy** [comment]
🆑 is not formatted correctly

**Comment by bthomas2** [comment]
fixed

**Pull request closed without merging**
