### PR TITLE
Add new hotkeys to access storage contents more easily.

### PR DESCRIPTION
**Pull request by ShiftyRail**
## New hotkeys

- New verb (not hotkeyed to anything, configurable if you want) to access your backslot.
- Backpacks and storage items will now close if you click on them again with an empty hand, no need to click the red cross anymore.
- Key combination CTRL+1 to CTRL+9 will put the `n`th item in the current storage screen in your hands if possible, 

## Note

Tested on qwerty keybord map, it works, on azerty however some of the keys aren't correctly recognised by byond (`CTRL+é` in place of `CTRL+2`, for instance), so azerty have to press the caps lock or shift key to use this feature.

Finally, I've also added a `skin-azerty.dmf` files for frog people who don't want to painfully edit their hotkey map.

:cl:
- rscadd: You can use the combination of keys CTRL+1 to CTRL+9 to access storage slots if you have an open storage item. If you have an item in hand, it will try to insert it if possible.
- rscadd: Clicking on an storage item which is displayed on your screen will close it.
- rscadd: You can use and/or macro the verb "Get backpack" to get what is currently on your backslot.

### CODE REVIEW

**Comment by Dacendeth** [comment]
not a fan of losing my intent changing hotkeys, i use those. Though I guess I can just change it back locally right?

**Comment by ShiftyRail** [comment]
You can change it back locally, yeah. If you want the behaviour to be on `CTRL+1,2,...` instead of `1,2,...`, react with :tada: to this comment.

**Comment by ShiftyRail** [comment]
Alright, CTRL+NUMBER it is.

**Comment by ShiftyRail** [comment]
Need to update `skin_azerty.dmf` to include the second media window.

**Comment by Kurfursten** [comment]
what are the applications of getting to query backpack type via macro?

**Comment by ShiftyRail** [comment]
All it does is to simulate a click on the backpack slot, nothing more or less.
I /think/ you could use it to quick unzip an egun with the two hotkays, `B`(or whatever) + `CTRL+F1`, that's the only cheesy thing I can think of.

**Pull request merged**
