### PR TITLE
2 "new" Vox Seed Vendor contraband seeds.

### PR DESCRIPTION
**Pull request by Eneocho**
Found these on the seedcode, they work as gauze and ointment respectively.
Quickly stitched together while working on a small project.
:cl:
 * rscadd: Adds S'rendarr's Hand and Messa's Tear to the Vox Seed vendor's contraband seeds.

### CODE REVIEW

**Comment by Kurfursten** [comment]
It's a bad idea. Mtear contains honey, meaning it **completely** renders bees irrelevant. It's much easier to make chantergrass mtear than it is to beekeep and you can spam out honey a lot faster.

The idea of having plants used for ointment and gauze was later recycled for aloe instead of using Bay Tajaran plants. Say no to cat culture.

**Comment by Eneocho** [comment]
> 
> 
> It's a bad idea. Mtear contains honey, meaning it **completely** renders bees irrelevant. It's much easier to make chantergrass mtear than it is to beekeep and you can spam out honey a lot faster.
> 
> The idea of having plants used for ointment and gauze was later recycled for aloe instead of using Bay Tajaran plants. Say no to cat culture.

Hence why it's on vox seed vendors. Traders get chillbugs instead of bees, so no honey from them. Though I get it. 
Would a honey removal do?

**Comment by Kurfursten** [comment]
I still don't like it, but at least it doesn't make beekeeping pointless at this point or bloat the main botany vendor. (On that subject, some day someone is going to make a good vendor tab system for stuff like theater and botany vends)

**Comment by Eneocho** [comment]
> 
> 
>(On that subject, some day someone is going to make a good vendor tab system for stuff like theater and botany vends)

I dream of the day vending machines don't take 5 seconds per sale if you want to mass purchase stuff.

**Comment by Kurfursten** [comment]
That's actually a *feature* so that it can play the animation of an object dropping. Each one has a delay measured out to their animation time, in decisconds. So for example, for the seed vendor, it's 1.3 seconds of delay.

image

It would be pretty based if, like in real life, you could just dial in several purchases before hitting "go" with a single total.

**Comment by Eneocho** [comment]
> 
> 
> That's actually a _feature_ so that it can play the animation of an object dropping. Each one has a delay measured out to their animation time, in decisconds. So for example, for the seed vendor, it's 1.3 seconds of delay.
> 
> image
> 
> It would be pretty based if, like in real life, you could just dial in several purchases before hitting "go" with a single total.

So either the item appears before the animation ends, breaking immulshon, or someone who actually knows what the fuck he's doing codes it so you can get multiple shit at once with only one animation cycle.

**Comment by strawberrytan** [comment]
The vox can already make gauze and ointment with their plants as a fancy little feature, though this has been pointed out

**Comment by ghost** [comment]
As Kurfurst pointed out, these seeds are legacy Baycode meant to be for Tajaran-themed plants. Ideally they should be removed from the game entirely instead of made accessible, especially since there's already better alternatives that fill their niche.

**Comment by cloutcode** [comment]
have catbeasts spawn with one of both in their pockets at spawn

**Comment by 49bluesun** [comment]
While I am all for anything that gives hydroponics more autism to work with, they could probably use some new or different chems if they're gonna be anything special or desirable. The problems with giving them honey was already stated, so no need to repeat that

Stashing em in the Vox seedvend feels fine. I always try to do trading for vox seeds, but that's never a guarantee every round. Hunting down a catbeast spawn to get them actually sounds fun. I already don't need incentive to want to kill one. But, there's nothing stopping them from just dropping or trashing them out of spite to deny that small reward

**Comment by ghost** [comment]
these seeds apparently spawn in one of the vaults, so they arent totally dummied out

**Comment by Kurfursten** [comment]
Not enough support, but having them come off catbeasts as an extra little perk for killing them is a neat easter egg idea

**Pull request closed without merging**
