### PR TITLE
Revert "Revert "Minor fix for explosive chemical reactions""

### PR DESCRIPTION
**Pull request by N3X15**
Reverts vgstation-coders/vgstation13#17154

### CODE REVIEW

**Comment by ghost** [comment]
lmao

**Comment by small-boss** [comment]
epic

**Comment by ShiftyRail** [comment]
It didn't even pass Travis...

**Comment by ghost** [comment]
PJB fixed the issues in https://github.com/vgstation-coders/vgstation13/pull/17158 . Can ya just... not? Please? What the hell is going on. Are you having a party with ya bois Jack and Jim? Do ya need to talk about it?

**Comment by Boxe** [comment]
hmm

**Comment by 9600bauds** [comment]
#17158 isn't merged yet and shouldn't be merged until probably 24hrs, being a balance change

**Comment by ghost** [comment]
I mean, we've lived for years with having it for suicidals killing themselves all two doctors still treat. We could have went a couple days for people to stop memeing to see that all the issues with charcoal and the loss of explosion clearing being resolved. There was no point for this pr and at this point I'm worried about nex cause this is some crazy behavior.

**Comment by Boxe** [comment]
🍆

**Pull request merged**
