### PR TITLE
Honor Overhaul

### LINKED ISSUE #16108: pressing the scotland button should delete the shard
please remove shard memes from highlander

### PR DESCRIPTION
**Pull request by N3X15**
# Executive Summary
The original way I coded honor was retarded so I refactored it.  This also adds in warnings, pull/grab blocking, and new punishments.

# TODO
* [x] Universal admin dickery panel
 #<s>* Ability to set global honor battle</s>
* [x] Ability to change bomberman/highlander honor battles

## Later PRs:
* Duels
* Rage Cage Designation

# Closures
* Fixes #16108

# Changelog
:cl:
 - rscadd: Refactored highlander honor into the Honor Battle System.  Honor battles are currently only triggerable by admin events.
 - rscadd: Honor system will warn player of rules upon being locked into them.
 - rscadd: Players joining a Honor Battle will be forced into harm intent initially, and will be forced to stop pulling and grabbing things.
 - rscadd: Highlander is an Honor Battle with disarming, firearms, and pull banned. Dishonorable chemicals are also disabled.
 - rscadd: Bomberman is an Honor Battle with disarm, pull, firearms, grab, and unarmed melee banned. Dishonorable chemicals are also disabled.
 - tweak: Pulling during highlander won't work.
 - tweak: Trying to pull the supermatter crystal during any honor battle will result in ashing.
 - tweak: Trying to create a baguloth during any honor battle will result in failure.
 - tweak: Trying to activate the singularity particle accelerator during any honor battle will result in failure.

### CODE REVIEW

**Comment by Riekland** [comment]
but ganging up on the gay bombermen who disarm and shoving bombs in their every hole is the best part

**Comment by N3X15** [comment]
Bomberman has had anti-disarm for a couple of weeks now

This will let admins change the settings when they want, though.

**Comment by Shadowmech88** [comment]
Highlanders already can't use guns due to being hulks.
It won't hurt anything to leave the condition in there, but I figured I'd mention it.

**Comment by N3X15** [comment]
No actual secret repo conflicts, bot is lies.

**Comment by N3X15** [comment]
discord_2017-10-13_13-39-50

**Pull request closed without merging**
