### PR TITLE
Fix for kudzu seemingly resurrecting constantly when killed very quickly (i.e. with chemsprayer)

### PR DESCRIPTION
**Pull request by 9600bauds**
I blame Bay :^)

### CODE REVIEW

**Comment by PJB3005** [comment]
Have you tested this, because this shouldn't do anything.

I think you're looking for `gcDestroyed` instead of `src`.

**Comment by 9600bauds** [comment]
I tested it and it seemed to be working, but the problem seemed to be a lot worse in the live server than what I could reproduce locally so it might just not do anything. I asked in the IRC if !src would work but it was like 6am and nobody responded. Will see about gcDestroyed in a second

**Comment by 9600bauds** [comment]
PJB was right, also probably fixed Kudzu very rarely taking up the same space twice

**Comment by 9600bauds** [comment]
This is ready 2 go

**Pull request merged**
