### PR TITLE
cow_ears/tails

### PR DESCRIPTION
**Pull request by SonixApache**
i was told to make this PR so i did
image

:cl:
 - imageadd: added variant of cat ears that are cow ears

### CODE REVIEW

**Comment by SonixApache** [comment]
image
moved north-face tail down

**Comment by Kurfursten** [comment]
I can't even tell what the sprites are supposed to be just looking at them

**Comment by JonathanSpaceStation** [comment]
needs like a pink part to differentiate the inner ear

**Comment by adacovsk** [comment]
>people hate gnomes for being fetish shit
>cow ears and tails

**Comment by smalIboss** [comment]
looks like shit & i only see people using this for evil purposes

**Comment by ShiftyRail** [comment]
Non.

**Pull request closed without merging**
