### PR TITLE
Fixes communists worshipping Karl Max

### PR DESCRIPTION
**Pull request by Kammerjunk**
The deity of socialism is Karl Max. This fixes it to Karl Marx.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by jakmak3** [comment]
helicopter

**Comment by Probe1** [comment]
also good work fixing an unreported bug instead of the reported one with romans you fuzzball

**Comment by Kammerjunk** [comment]
¯\_(ツ)_/¯

**Comment by Intigracy** [comment]
this isn't a bug reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Pull request merged**
