### PR TITLE
Vampire rejuvenation blood cost is now 0 instead of 1

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
It's so close to 0 that it might as well not matter, but this fixes the dilemma of getting fucked out of your ability to hypnotize people as a fledgling vampire because you start with 10 blood (just enough for one hypnotize) and for some reason you use rejuvenate, which leaves you with 9 usable blood, making you unable to use hypnotize. Vampires everywhere rejoice.

:cl:
 * tweak: The vampire's rejuvenation ability is now free and no longer costs 1 blood.

### CODE REVIEW

**Comment by adacovsk** [comment]
Make sure to change the name of rejuvinate spell, which includes the cost of the spell. Also, you removed the wrong cost, I think

**Comment by boy2mantwicethefam** [comment]
Fixed the name. The cost change is fine.

**Comment by Blithering** [comment]
How spammable is rejuvenate after this change? Can you run around mashing it and be stun immune?

**Comment by Hinaichigo** [comment]
Alternatively you could give them 11 blood, or random between 11-15 or something to start.

**Comment by boy2mantwicethefam** [comment]
@Blithering It's still on a 3-minute cooldown.
@Hinaichigo I considered that but decided otherwise since it wouldn't be as fun and would look kinda arbitrary.

**Pull request merged**
