### PR TITLE
Pyrite slimes produce 5x as much cash

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I don't really have any arguments for this PR, I just asked "could i get away with making pyrite slimes give you 1000 credits instead of 100" and I got a response of "yes" and "yes but also no" so here I am
PR has been updated to give you 500 credits instead of 1000 because it kinda breaks the economy

:cl:
 * tweak: Pyrite slimes now produce 500 credit chips instead of 100

### CODE REVIEW

**Comment by calzilla1** [comment]
Maybe make it so that more plasma= more dosh

**Comment by SonixApache** [comment]
remember when we nerfed this

**Comment by boy2mantwicethefam** [comment]
@calzilla1 Would be rad but there are two problems: I have an on-going slime extract related PR and it will conflict if I change anything else and slime extracts are set to work with only syringes IIRC and syringes inject only 5u at a time, would be interesting though. A 1u = 50 credit ratio?

**Comment by dunsel-hordon** [comment]
Make it so you can inject it with the giant syringe for lethal injections and only then will it give you the big dosh. Just a suggestion no idea if it would actually work

**Comment by DrSnips** [comment]
Scaling reactions are kind of dumb if you ask me. They just don't pan out in practice. See the time stop effect.

**Comment by FudgePucker** [comment]
Fuck the economy

**Comment by PrimeDSS13** [comment]
make it 500 instead of 100, the way it is now seems like a bit TOO much of a jump.

**Comment by boy2mantwicethefam** [comment]
Current iteration is receiving positive feedback, I'll see what I can do if people will talk about pyrite slimes crashing the economy or something.

**Comment by SonixApache** [comment]
assistants get enough money at roundstart to buy out half a vending machine
which only requires about ~200 bucks

1000 bucks is actually a lot now, since the recent changes

**Comment by MadmanMartian** [comment]
Of course it's receiving positive feedback, it's a buff with no drawbacks.

**Comment by ghost** [comment]
This is basically infinite money for scientists on top of infinite phazons.
How are they going to spend it? I don't know and i don't wanna know, downboated.

**Comment by Killette2** [comment]
This will be one of the fastest ways to make money if pushed, only second to simply raiding debit cards/accounts

**Comment by boy2mantwicethefam** [comment]
I can see it being easy to farm money by using extract enhancers and the like, being able to get 3000 credits out of one extract or 9000 credits from one slime
I could try halving it

**Comment by FudgePucker** [comment]
What the fuck can 100 credits buy anyways? A fucking bag of jerky. Isnt this a higher level slime? The other cores of this level can make massive swarms of mobs, literal slaves that are bound to you, materials, rare food and drinks, and much more.

God forbid we buff the most worthless core that gives you... a camera

**Comment by MadmanMartian** [comment]
Almost anything from cargo, whereas 1000 would be anything from cargo, such as three pieces of supermatter

**Comment by SonixApache** [comment]
@FudgePucker 100 credits can buy out a quarter of your average vending machine, along with basically any item from cargo and most of the non-mining items in the mining vendor.

Or two and a half bags of jerky. And yes, a camera that seems ghosts. Gimmicky, sure, but cool regardless.

The fact that there is no actual argument *for* this PR, that it's literally just yet another thoughtless barry shovelware change, should count for something.

**Comment by boy2mantwicethefam** [comment]
There is a reason, the payout is too cheap.
I am reducing the change from 10x to 5x but my respect for Sonix' opinion about changes is still the same

**Pull request merged**
