### PR TITLE
(Packed) Changes tech storage to have regular walls instead of Reinforced walls.  Secure tech storage remains reinforced.

### PR DESCRIPTION
**Pull request by Probe1**
I made this mistake in my earlier Packed PR  https://github.com/vgstation-coders/vgstation13/pull/17730 .  vampirebat74 caught it and reported it directly in discord.

🆑 

 * bugfix: (Packed) Changes tech storage to have regular walls instead of Reinforced walls.  Secure tech storage remains reinforced.

dreammaker_2018-03-22_19-41-49

### CODE REVIEW

**Comment by Kurfursten** [comment]
Are you trying to tell me that this was

>settled in the discord

**Comment by Aurx** [comment]
No, just reported in the discord.

**Comment by Probe1** [comment]
image

**Comment by FudgePucker** [comment]
I disagree with this change.
There is a pair of yellow glubs in there.
The tech storage is for engineers and mechanics, not every assistant with a welding torch

**Comment by Probe1** [comment]
Thats how it is on other maps so take it up in an issue.
>gloves

Gloves are valuable but not high risk.

image

**Pull request merged**
