### PR TITLE
Small changes to boxstation

### LINKED ISSUE #3235: [Box] Sound System above Research
There are two sound systems above research pointed towards escape, one of them is on a wall but the other is inside glass on a grille. Please remove the sound system on a grille.

### PR DESCRIPTION
**Pull request by Konater**
removed the access buttons from the aft starboard solar control room
removed the airlock sensor in telescience and added a scrubber to the chamber turned off
moved the chapel north camera down one tile so that it can see the air alarm
removed the duplicate sound system in escape inside the R&D window
added intercoms to interrogation so the observation room can be used, freq is 140.1
moved the small light fixture in robotics so it is over the computer rather than the operating table
fixed the dorm 2 bolt controls
replaced the glass in aux tool storage so that it is no longer invisible
removed two duplicate cameras, one in the bar and one in the fitness room
replaced the unbreakable windows in the arrival pods with breakable ones again
radio transmitter room is no longer a vacuum floor
replaced the t valve in the incinerator with one that connects to the pipes
removed the phalanximine IV bags in medbay and added one to the CMO office under the stethoscope
Fixes #3235, #3070, #2946, #2888, #2869, #2819, #2404

### CODE REVIEW

**Comment by IratePirate** [comment]
Nice. Box has needed some maintaining recently.

**Comment by ComicIronic** [comment]
Rather than addresses, please use "Fixes". Github picks it up and autocloses issues.

**Comment by Konater** [comment]
if someone could tell me how to go back to step one and/or update my local repository I would appreciate it

**Comment by ComicIronic** [comment]
Ask in the IRC.

**Comment by 9600bauds** [comment]
Please close the issues that this fixed.

**Pull request merged**
