### PR TITLE
Fixes #10970

### LINKED ISSUE #10970: Attacking a posibrain or MMI with any item causes a ". attacks SINA-610 with the scalpel." message and has no attack cooldown

### PR DESCRIPTION
**Pull request by ghost**
Fixes #10970

### CODE REVIEW

**Comment by ComicIronic** [comment]
So I can't attack an MMI now?

**Comment by ghost** [comment]
@ComicIronic I did some testing - The "functionality" of this allows you to spam someone with a fireaxe, a welding tool, a hivehand, and I couldn't remember anything that did oxyloss/brain damage so I varedited it.
Turns out a brainmob is invincible, so the "damage" you did prior to this bugfix had no effect. I see no reason to keep this.

**Comment by Intigracy** [comment]
Or add an attack cooldown and make brains lose health when attacked.

**Comment by ghost** [comment]
@Intigracy If you read the post above you can see that it *does* damage but that damage is irrelevant because brains are invincible

**Comment by Intigracy** [comment]
But why?

**Comment by Shadowmech88** [comment]
Knowledge is power.

**Comment by ghost** [comment]
Who the heck knows

**Comment by chatsonf** [comment]
YOU'RE THE REASON WHY I CAN'T PLAY BRAIN INSTRUMENTS ANYMORE

**Pull request merged**
