### PR TITLE
Revert "Civil war of casters faction conversion of crew"

### PR DESCRIPTION
**Pull request by gurfan**
Reverts vgstation-coders/vgstation13#34097

Cancerous and low-effort shit content:

- Instant, Ranged, Reusable Conversions: Why fight people when you can click on them once from the edge of their screen?
- The wizard hat floating above you is always red, even if your team is blue.
- When you get converted your entire character gets painted. This gets washed off easily.
- Not both sides are guaranteed to pick the spell, so the station ends up looking like vampire thrallgunk instead of an actual war.
- Broken Spell Icon! pn7Lj6todZ
- The spell's name is literally "Convert To Faction" instead of something creative. 
- There is no description of what empowering the spell does until after you purchase the empowerment.
- Roundend screen does not show faction members.

Why such content is allowed to be merged is beyond me.

### CODE REVIEW

**Comment by west3436** [comment]
> Low-effort?

Yes. 

> Fun?

Yes!

**Comment by pedr69** [comment]
i had fun shooting down all blue people, also known as valids
it solves the problem where you don't know wherther you should murderise civilians as a wizard

**Comment by nervere** [comment]
It instantly ruins the round. Extremely lame, I don't know why this is in the game. If you want TDM, go somewhere else.

**Comment by ErrorsWindows** [comment]
hmm...
now where could my fun be...

KANEF!!!!!

**Comment by ManopolisJones** [comment]
Wololo

**Comment by west3436** [comment]
Downthumb because I'd rather see @SECBATON-GRIFFON fix the issues rather than revert it entirely. TDM rounds are fun v once in a blue moon (and wizards can already cause them via summon guns/spells) and this improves civil war of casters in getting the crew more involved.

**Comment by DorainGrey** [comment]
TDM is fine and this is probably a better replacement to the Survivor spell however unless someone commits to fixing this it should be reverted.

Aside from the numerous issues pointed out above, trading 40 spell points for ranged conversion is absurd. Wizards are now better Revs than revs themselves, as they have no cap, can convert sec, do it at range and have spells like blink etc

**Comment by SECBATON-GRIFFON** [comment]
> * When you get converted your entire character gets painted. This gets washed off easily.

i intended this as a feature unless people really hate it

**Comment by DorainGrey** [comment]
Changed my vote because I think the changes proposed in #34268 are good and fix most of the issues here.

**Comment by Kurfursten** [comment]
The alternative had much clearer support; you can re-try this after one week of nu-convert if you still hate it

**Pull request closed without merging**
