### PR TITLE
Deff tradeship

### PR DESCRIPTION
**Pull request by Probe1**
**Adds** a vox tradeship to Defficiency 
**Removes** the third escape pod in arrivals

### CODE REVIEW

**Comment by Arthurdentist** [comment]
P I C T U R E S

**Comment by Probe1** [comment]
I'm werkin on it jeez

dreamseeker_2016-05-31_10-10-18

**Comment by Probe1** [comment]
image

**Comment by ComicIronic** [comment]
> you have to go through spess

Fully support this. The distance should be bigger, though, and vox should spawn without masks, tanks, or suits.

**Comment by clusterfack** [comment]
So un-gas the vox?

**Comment by PJB3005** [comment]
Please no going through space. The shuttle will just decompress instantly.

**Comment by Probe1** [comment]
It didn't in testing when I used it normally.  I can add a canister of (air) if it makes it better.  

The forced EVA to get to the shuttle is the only "It's deff so it's a pain in the butt" part I liked about it.

**Comment by ihadtoregisterforthis** [comment]
> try to enter shuttle
> ZAS'd into the void

Isn't there a better place to set the port?
The chair between the tables needs to go somewhere else.
What's with all the grime?

**Comment by Probe1** [comment]
there's a catwalk right there you wouldn't be zas'd anywhere.

**Comment by Kurfursten** [comment]
Also traders get free no-slow magboots

It's actually the best part of being a trader

**Comment by 9600bauds** [comment]
You guys don't get it, it's a defficient docking port

**Comment by Probe1** [comment]
bauds understands

shitty but functional

**Comment by 9600bauds** [comment]
ha ha you said shitty butt

**Comment by Exxion** [comment]
Friendly Reminder that ZAS doesn't even have air pulling, only pushing, and that doesn't even work in space, so even without the magboots or the catwalk, the worst that could happen is getting knocked over

**Comment by Konater** [comment]
that single airlock bugs the hell out of me, is the tile at least unsimulated/blocking air?

**Comment by Probe1** [comment]
It is simulated and does not block air.

**Comment by Konater** [comment]
I'm fine with it getting merged anyway, the sooner the better so I can finish what I'm doing

**Pull request merged**
