### PR TITLE
Added sprites and code for species alts (again)

### PR DESCRIPTION
**Pull request by Buchse**
Right. This is the third time i've had to make this PR because I made a fucky-wucky and didn't update my shit. 

I added alt sprites for all the basic armor vests and such like bulletproof vests, ablatives, etc. 
I also added sprites for the syndicate red spacesuit, and the orange syndiesuit/prison softsuit.
Vox are now able to wear syndicate softsuits and helmets.
Sec and riot helmets currently lack any alternate sprites for vox, see below:
riotbrokenfront
riotbrokenside
sechelmetbrokenfront
sechelmetbrokenside
I made an attempt at alternate sprites for them. They're significantly different, I know, it's not for lack of trying to make the original styles work however. If they're despised I can remove them/change them for something different at another time, for now they can at least serve as placeholders.
newbirdriot
newbirdsec
[sprites]
[qol]
Feel free to discuss the sprites/ask for more content/call me a retard for having to make 3 PRs
:cl:
 * rscadd: Added a load of alternate species sprites and the code for them.

### CODE REVIEW

**Comment by SonixApache** [comment]
learn to fuckin git
add a showcase picture to the OP so people don't have to squint at icondiffbot's tiny renders

**Comment by ghost** [comment]
I wish the standard helmet sprites were open faced but these reworks are far far superior to the vox helmets we have right now.

Also i really like the design on the first one, it looks perfect for a futuristic military police type armor.

**Comment by Buchse** [comment]
> I wish the standard helmet sprites were open faced but these reworks are far far superior to the vox helmets we have right now.
> Also i really like the design on the first one, it looks perfect for a futuristic military police type armor.

I really did try for 3-4 hours to make a good looking open-faced alternate. Due to how dark vox sprites are, how their breathmasks work, and the fact that they don't hide mask/eye sprites underneath them, I settled on just making something enclosing that looks alright. 

Worst case scenario, these can serve as placeholders until something more fitting is sprited.

**Comment by cloutcode** [comment]
upvoted for retard bucket over head riot helmet vox

**Comment by Myrios** [comment]
Very nice, now all we need is for the base sec helmets and riot helmets to not look like ass as well.
Plus encouraging Vox to not wear their hardsuits whenever possible is always good.

**Comment by tuypo1** [comment]
>Plus encouraging Vox to not wear their hardsuits whenever possible is always good.

Agreed

**Pull request merged**
