### PR TITLE
Secret mode is now dynamic mode

### PR DESCRIPTION
**Pull request by MadmanMartian**
thrown together in like 5 minutes

### CODE REVIEW

**Comment by CptWad** [comment]
does this mean extended can proc

**Comment by gbasood** [comment]
isn't the whole point of dynamic that it's not extended

**Comment by ShiftyRail** [comment]
@gbasood a low-threat roll is essentially extended

**Comment by SkowronX** [comment]
The end of an era

**Comment by CptWad** [comment]
how else do I do my shitter safaris

**Pull request merged**
