### PR TITLE
The "Centre of mass doctrine" PR

### PR DESCRIPTION
**Pull request by ShiftyRail**
## Background

I got told on discord that #32779 was more or less intended to discourage or at least, mitigate evil POWERGAMERS targetting unarmoured outer limbs (such as hands or feet) as they were unarmoured and as such would be more likely to give you the full damage output.

This is especially true in melee fight when you're fighting, say, the HoS with an absurdly high armour score on the head, but nothing on the feet and hands.

I actually know at least **3** (three!) people who knew about this and, at times, "abused" it (especially for melee combat) and as such it's not as theoretical as it might sound in the first place.

To fix this *properly* this PR raises the chances to miss when aiming to the limbs by quite a bit.

## Numbers changed

Format : Ballistic+Melee/Laser (intended target% + other limb%)

Head : untouched

Legs, arms :
- Before : 86/110% chance to hit the target (!!!!) (80% intended target + 6% other limb/80% + 30% laser rifle bonus, so always intended target)
- Now : 58%/68% (40% + 18% / 55% + 13%, laser bonus included)

Hands, feet :
- Before : 65%/86% (50% + 15% / 80% + 6%)
- Now : 55%/58% (10% + 45% / 16% + 42%, so lots of chance to hit something else)

In short you will be more likely to miss, but you will only occasionally not hit anything at all. Most likely, you will not hit what you intend to when not targetting the centre of mass.

## Discussion

I realised, however, that it would make a lot of execution less funny if the HoS tried to shot at the guy in the feet for an example but failed again and again to do so. (I mean it *would* be funny but a bit unexpected and get old after a while). Which is why you will *always* hit the target if the mob has been idle for more than 5 seconds, and will have a 50% chance of landing a perfect shot if they have been idle more than 2 seconds and less than 5.

This might make the Nicholas Blaine type even more jumpy and try to keep that sweet less-than-two-seconds advantage, but frankly : 

a) it's funny
b) they are getting more targetted by this PR removing a less-than-known powergaming tactic to maximise DPS
c) it's very noticeable to refuse to stay idle for more than 2 seconds at a time so, in the end, they get more attention from admins and that's probably something they should avoid.

It is very much a small combat rework, particularly the part about the "shooting first" bonus, so feel free to give your thoughts.

## Recap

:cl:
- tweak: Aiming at the hands, legs, arms or feet is now more likely to miss or hit another body limb.
- tweak: You will always hit the limb you are targetting against a target that has been idle for the last 5 seconds.

### CODE REVIEW

**Comment by Eneocho** [comment]
Does it affect anything if you aim at a leg then fire at a simplemob humanoid?

**Comment by pedr69** [comment]
uhh the HOS armor covers the arms and legs too doesn't it?

**Comment by pedr69** [comment]
also, why not just have the shot be 100% accurate if you use the "aim and take people captive" gun mode, which noone uses ever

**Comment by ShiftyRail** [comment]
>Does it affect anything if you aim at a leg then fire at a simplemob humanoid?

No, simple mobs are explicitly unaffected, you will always hit center of mass.

**Comment by bathosbathtime** [comment]
I would rather the chance to hit something be if not larger then at least comparable to the chance to hit sonwthing at all. The 45% total miss chance isn't actually too bad to me. Could even raise it. But I think it would be better to make it more likely a player hits what they are aiming for instead of a compensation bodyshot as I don't view it as 'powergaming' to aim for high risk vulnerable spots. I do agree, however, that it should be decently hard to do so.

**Comment by ManopolisJones** [comment]
melee builds btfo'd

**Comment by adacovsk** [comment]
I think accuracy should improve if you're walking rather than running but maybe out of the scope of this PR

**Comment by Eneocho** [comment]
I'd buff the odds for a melee hit to go through when aiming at a limb, since it would be way easier to hit the arm with a toolbox swung at the general direction of the arm than aiming a gun while the guy's moving to specifically hit the arm.
This would also specialize combat in a way. Melee for limbs, boolets for chest.

**Comment by luigil101** [comment]
you should add head to the chance to miss too, just for kicks
headshots shouldn't be easy

**Comment by Servalfang** [comment]
wait advantage to hit if THEY'RE idle? I would be more in favor if you were (especially in a gunfight-give some small perk to having the balls to stand your ground)

**Comment by Hinaichigo** [comment]
58% seems a little too low for the limbs. Maybe 75% or so would be better. Agreed on the melee being more accurate than ballistics thing as well.

**Comment by Eneocho** [comment]
Alright. so the suggestions are:
Kicks to the head being less accurate.
Melee to limbs being overall very accurate because it's hard to fuck up when swinging a fuck off toolbox while aiming for the limbs.
Better limb aiming accuracy if you, your target or both are keeping still.
And better aiming accuracy if either you or your target is walking.

I'd make it so you can accurately kick the head with either clumsy (really flexible clowns fit on the tiny car) or strong (hurrdurrbalance), having 100% odds to hit accurately if both you and your target are idle for a few seconds, 80% if either is idle, 60% if neither is idle and maybe a flat 10% better aiming if either you or your target are walking.

**Comment by Blithering** [comment]
Could you have point blank shots (the harm intent click spessman one that gets the specific text) be 100% accurate, would alleviate the HoS execution problem and makes sense.

**Comment by Kromkar** [comment]
> Could you have point blank shots (the harm intent click spessman one that gets the specific text) be 100% accurate, would alleviate the HoS execution problem and makes sense.

Afaik harm intent shots from adjacent squares always hit when targeting head

**Comment by juanototo2** [comment]
I am morally obligated to downvote due to being insulted like this.

However, I don't particularly consider this change downright terrible to me -- I didn't tend to target them too much because gibbing or removing the limb results in the limb's health damage being not transferred to the overall health value of the target, and that means they could get back up.

Besides, armor isn't a problem anyways if you have the right stun-option for the job and can drag them back long enough for a kill-confirm -- it's only a real problem in lethal v. lethal combat. 

Remove the insult and I will remove my downvote.

**Comment by Hinaichigo** [comment]
It might be nice if for example missing the left hand would have a higher chance to hit the left arm and chest, than to hit the right foot.

There could be 3 levels of "peripherality", and a max of 2 "shifts" per attack
level 2 - hands, feet: attacking these has a chance to shift the attack to a connected level 1 body part instead (eg. left hand to left arm)
level 1 - arms, legs, head: attacking these has a chance to shift to a connected level 0 (eg. head to chest), and a smaller chance to shift to a connected level 2 (eg. left arm to left hand)
level 0 - chest, groin: attacking these has a chance to shift to a connected level 0 (eg. chest to groin) and a chance to shift to a connected level 1 (eg. chest to left arm)

Example: attempting to attack the right hand:
Roll for base chance to hit a level 2 body part (75%) - success.
Roll for chance to actually hit the right hand (50%) - failure.
Shift attack to right arm (-1 shift, 1 remaining).
Roll for chance to actually hit the right arm (75%) - failure.
Roll to determine if we shift inward (75%) or outward (25%) - inward. 
Shift attack to chest (-1 shift, 0 remaining).
Execute attack on chest.

**Comment by Hinaichigo** [comment]
In general though I'm not sure I like the idea of increasing the deflection by much.
It's not really powergaming to look for weak spots in an opponent's armor; that's been a huge part of combat since... the evolution of complex multicellular animals.
Why _should_ a sec officer get additional resistance to getting syringe stabbed in the head just because of his chestplate?
And as others have said it sort of amps up the stun meta even more. Good old fashioned pound-for-pound melee combat becomes harder, incentivizing stunning and and then magdumping or repeatedly toolboxing when they're on the ground. That's not to say stuns should be nerfed, but there should be viable alternatives.

**Comment by jwhitak** [comment]
The nerfs are more than 50% of their values. This is more than a tweak, this is sort of a fundamental change in how fighting handles on the station. I'd recommend a server vote (or at least an announcement for people to look and see these changes) before merging, so people know that their POWER GAMING STRATS don't work anymore.

I also really like the above change recommendations, such as melee chance to arms being higher.

I'll do that thumbs up thing when the above changes are commented on or otherwise implemented.

**Comment by Pastamadness** [comment]
I feel like this change as it is is a bit too radical and would be a nebulous nerf to fighting for those who don't keep up with the PRs here. Maybe tone down the nerfs for this PR and silently and gradually increase them like the usual coder.
I am only actually downvoting this this for ethical reasons for the simple fact that it's buffing sec in direct combat, specially the HoS.

**Comment by xeroxemnas** [comment]
Soulless PR. Hacking off limbs with an e-sword or cult blade is practically the only reason to use melee in the first place.

**Comment by Kromkar** [comment]
> The nerfs are more than 50% of their values. This is more than a tweak, this is sort of a fundamental change in how fighting handles on the station. I'd recommend a server vote (or at least an announcement for people to look and see these changes) before merging, so people know that their POWER GAMING STRATS don't work anymore.
> 
> I also really like the above change recommendations, such as melee chance to arms being higher.
> 
> I'll do that thumbs up thing when the above changes are commented on or otherwise implemented.

Server vote yeah, if it even passes emojicracy

**Comment by Eneocho** [comment]
`>aim an esword to the head`
`>end up cutting the left foot instead`
very cool and (((balanced)))

**Comment by ShiftyRail** [comment]
I've read the comments and I'll make the necessary changes ; probably in a second PR as this one is already tainted by emojicrazies 

@juanototo2 it is more of an homage really

@Hinaichigo 

"Why should a sec officer get additional resistance to getting syringe stabbed in the head just because of his chestplate?"

I am not sure this is what this PR does :)

**Comment by ShiftyRail** [comment]
Cannot work on this atm due to real life reasons

**Comment by Kurfursten** [comment]
What is the status on this? I was thinking it might be wise to take it to a server vote, but if you want to wait until after you can make some changes, we can wait

**Comment by githubuser4141** [comment]
Sad, we're not looking at reworking limb lethality? It'd be awesome to have better injuries for limbs, one could Google around for IRL injuries / causes / effects and go from there instead of "100 toe damage, no bleeding, no fluid loss, dead anyway"
It's fairly difficult to accurately target someone's individual limbs in actual, IRL combat anyway unless the other person's tied to a chair something.

**Comment by ghost** [comment]
Derelict PR, author is not interested in working on it atm, negative emojicracy bias. Feel free to re-open if revisted.

**Pull request closed without merging**
