### PR TITLE
Fix players seeing lights being toggled on or off at roundstart, and make rooms lit on an individual basis

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
This makes it so all the light, lightswitch, and lamp on-or-off toggling that depends on whether or not the room is occupied at roundstart, occurs before players are transferred into their bodies, so that the player won't see the lights changing right at the start of the round. To get this to work, these things are done before body transfer occurs:
- lightswitches, lamps, and lightbulbs themselves are force-updated 
- a complete tick of the lighting subsystem is forced to fire

Something changed in this also that I think is nice is that only lights in the exact area the player starts in will be toggled. So, if the only player starts in telescience, the lights in the robotics lab will be off. I think that could give a nice lonely vibe in lowpop but let me know if you think otherwise.

## Why it's good
Hopefully fix the longstanding issues relating to lights being on-or-off at roundstart. Also amp up the loneliness vibes a little.

## Changelog
:cl:
 * bugfix: Fixed being able to see lights toggling at roundstart based on crew occupancy.
 * tweak: Only occupied rooms have their lights on at roundstart; other unoccupied rooms in the same department will be dark, assuming they have lightswitches.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I like the approach but I don't like the station being even darker

**Comment by kilozombie** [comment]
hina PR

**Comment by wotisjanitor** [comment]
just stop, please. We don't need to dig up adacovsk shit. Just revert all of his roundstart changes or something

**Comment by jwhitak** [comment]
"Another thing I think is nice"

Unatomic. I like the first change: a long requested bug fix. I hate the "another thing," making the station even darker. The tiebreaker here is unatomic bad. Split the PR, please.

**Comment by Hinaichigo** [comment]
Okay.
But what's so bad about having the lights off? I like the atmosphere of having to turn them on, it makes it feel like the room was sitting there unused and I'm about to rummage through it for supplies or whatever.

**Comment by djkramer123** [comment]
"here I fixed this bug but also here's some other non bugfix related change" what compels coders

**Comment by Hinaichigo** [comment]
😭

**Pull request closed without merging**
