### PR TITLE
REMOVES WRONG FACTS

### PR DESCRIPTION
**Pull request by 9600bauds**
this is very important

### CODE REVIEW

**Comment by ghost** [comment]
Where does J appear then?

**Comment by 9600bauds** [comment]
In my subscriptions feed
https://www.youtube.com/watch?v=Oy8ZMFXS_5E
Also if you want to be a pissant then Q no longer appears since ununquadium was renamed a while back

**Comment by SysadminJeroen** [comment]
QUICK, PASS, MERGE AND RESTART!

**Comment by clusterfack** [comment]
Aren't a whole bunch of these false?

**Comment by ghost** [comment]
oshit, they finally gave the 110 series elements names?

Also, removing that fact about moths is just gonna start MOTHS WHEN

**Comment by 9600bauds** [comment]
Clusterfack do you have a brain bigger than a neanderthal's?

**Comment by Ephx1** [comment]
Ah, so the trick here is to not give Moths mouths and enable hardcore hunger.

**Comment by Exxion** [comment]
> When you die your hair still grows for a couple of months

PLEASE KINDLY GO FUCK YOURSELF WITH A SWORD WHOEVER WROTE THAT
Also remove it

**Comment by 9600bauds** [comment]
ok

**Comment by Kurfursten** [comment]
That video was total speculation on the name, not confirmed at all! Did you even watch it?

Also add new facts to replace ones removed.

**Comment by clusterfack** [comment]
Anyway let me know when you all are satisfied with this

**Comment by ghost** [comment]
:+1:

**Comment by 9600bauds** [comment]
Gibe new facts

**Comment by Exxion** [comment]
All the facts I can think of are about neutron stars (or at least types of neutron stars) and that might be too many facts about neutron stars
But I can still give you some

**Comment by Ephx1** [comment]
What about the one about Binary stars being the majority of star systems, is that one on there?

**Comment by PJB3005** [comment]
Did you know the brightest places in the universe are black holes?

**Comment by Exxion** [comment]
One teaspoon of neutron star material would weigh roughly 900 times as much as the Great Pyramid of Giza.
A magnetar has a magnetic field so strong it could strip the data from all credit cards on Earth from a distance halfway to the moon.
An object released one meter above the surface of a neutron star would hit the surface in approximately one microsecond and would do so at about 2000km/s.

All three would probably be too many facts about neutron stars, but you can pick one

**Comment by PJB3005** [comment]
@Exxion wouldn't said object in the third fact create the same amount of force as a nuke?

**Comment by PJB3005** [comment]
also https://www.reddit.com/r/AskReddit/search?q=fact&restrict_sr=on&sort=relevance&t=all

**Comment by Exxion** [comment]
@PJB3005 Depending on its mass, yes
The energy (in kilotons TNT) would  be about equal to .48 times the object's mass in kilograms, unless I'm an idiot and fucked up my math

**Comment by Kurfursten** [comment]
If you had a black hole the size of a nickle in your pocket, it would crush you before you knew what was going on and proceed to devour Earth.

**Comment by ghost** [comment]
"Thought of the day: If you crashed a cold sun into a hot sun what would happen?"

**Comment by NigglyWiggly** [comment]
@DrCelt That's fucking retarded.

The real question is "If a sun made of ice crashed into a sun made of lava what would happen?"

**Pull request merged**
