### PR TITLE
added send back to lobby button on player panel

### PR DESCRIPTION
**Pull request by 13spacemen**
## Changelog

:cl:
 * rscadd: Admins now have a button on the Player Panel to send players back to lobby

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
so, a kick feature basically? don't we have that already
oh and apparently it's just for ghosts. again, seems redundant to kicking
for me it's the ol classic setting the ckey to null do

**Comment by Eneocho** [comment]
> so, a kick feature basically? don't we have that already oh and apparently it's just for ghosts. again, seems redundant to kicking for me it's the ol classic setting the ckey to null do

I read it as a quick button for letting a ghost rejoin properly via the whole latejoin thing.

**Comment by kilozombie** [comment]
> so, a kick feature basically? don't we have that already oh and apparently it's just for ghosts. again, seems redundant to kicking for me it's the ol classic setting the ckey to null do

Setting a ckey to null makes their client crash, and kicking exits you from the game but doesn't put you in the lobby.

This is the equivalent of a well-established admin tool, `Spawn "new_player{ckey=""}`, which we use to let people rejoin or enter the lobby for various reasons.

**Comment by kilozombie** [comment]
Also nice for clientside testing of course, as previously the fastest way was `Spawn "new_player{ckey=""}` or Allow-player-to-respawn and the latter requires a config option. Just a nice thing to have imo.

**Comment by SECBATON-GRIFFON** [comment]
oh, interesting

**Comment by gurfan** [comment]
> so, a kick feature basically? don't we have that already oh and apparently it's just for ghosts. again, seems redundant to kicking for me it's the ol classic setting the ckey to null do

surely you can see the benefit of being able to accomplish this without forcing them to restart their game, and without having to use some hidden technique.
surely.

**Pull request merged**
