### PR TITLE
Removes carrot/imidazoline overdose

### LINKED ISSUE #7659: Remove imidazoline overdose
Currently it's possible to OD on fucking carrots. This is stupid. I also do not see a balance issue.

### PR DESCRIPTION
**Pull request by JustSumBody**
closes #7659

### CODE REVIEW

**Comment by ghost** [comment]
Remember to update the wiki if you're changing overdose values and such

**Comment by JustSumBody** [comment]
The entry for Imid already says it doesn't have an overdose limit, but I put it in the changelog as well now

**Comment by nuklearcellphoneg** [comment]
Overdoses and reagents are something we should probably go over together at some point- I don't think it matters much but I'm assuming this basically means if you have access to Imid you have a substitute for  a welding mask, goggles, etc

**Comment by JustSumBody** [comment]
The main issue is that the wiki says Imid doesn't have an overdose limit, but you can actually overdose from it.
On top of that, this also means you overdose when you eat too many carrots.
Honestly if we want to we can just update the wiki and close this, I'm just looking for merge valids

**Comment by Intigracy** [comment]
Carrots having an overdose is dumb.

Also I don't think that's actually a problem, nuke.

Having different ways to do things isn't a bad thing.

**Pull request merged**
