### PR TITLE
New basic chair sprites

### PR DESCRIPTION
**Pull request by ghost**
<S>Stolen</S> Ported from Hippie Station

Just plain better, sprite below. We 2016 chairs now

new_chair

### CODE REVIEW

**Comment by Zth--** [comment]
:+1:

**Comment by 9600bauds** [comment]
Do these replace the current chairs, or are they new ones?

**Comment by Shadowmech88** [comment]
Post pics of the other chair directions.

**Comment by ghost** [comment]
These replace the current base chair sprite

chair_back
chair_side

**Comment by CptWad** [comment]
rip nostalgia
what sort of chair were old chairs supposed to look like anyway?

**Comment by ghost** [comment]
The old chairs were pretty strange, some interpreted them as folding chairs, other as shoddily made metal chairs. This one clearly goes for the later, Goon has the former

**Comment by Shadowmech88** [comment]
What kind of real chair is this supposed to be?
Is it this?
image

If so, the North sprite doesn't really make sense. I've never seen any chairs where the legs were joined at the bottom on all sides except the front.

**Comment by ghost** [comment]
I think this is a metallic chair with leather cushions, the kind of cheap chairs you still find sometimes

**Comment by Shadowmech88** [comment]
Yeah I've seen those chairs, I'm saying that I've never seen one of those chairs where the legs were joined at the bottom of the left and right sides _and_ the back side.
For this reason, I think the North sprite should be changed such that the legs are not joined at the bottom of it.

**Comment by ghost** [comment]
I'm pretty sure the chair is joined at the front (Yeah, it's that kind of shitty uncomfortable chair)

**Comment by clusterfack** [comment]
These look better

**Comment by Shadowmech88** [comment]
The front legs are joined halfway down, not at the bottom.
Based on the sprite, the back legs are joined at the bottom.
I've just never seen an actual chair with that kind of leg design.

**Comment by ghost** [comment]
I guess we can try them as is ? I'm not opposed to having someone tweak them even more, but the current chairs are just so bad

**Comment by Shadowmech88** [comment]
I don't necessarily hate the new chair sprites, and if other people have no issue with them I wouldn't mind them being used.

I just think something like this would look more like an actual chair design that exists.
newchair

**Comment by 9600bauds** [comment]
But muh clunky metal chairs
I like the current ones

**Comment by ghost** [comment]
The main problem with this is that you have to change the electric chair sprites too

I'd wager to merge the currents, even if they get upgraded quickly

Also bauds, stop being nostalgic. It's 2016

**Comment by 9600bauds** [comment]
>doesn't even keep the old ones as an alternate constructible, like comfy chairs

Don't fix what ain't broke

**Comment by Shadowmech88** [comment]
It's THE CURRENT YEAR
How can people keep using the old sprites despite the fact that it is now THE CURRENT YEAR?

**Comment by clusterfack** [comment]
Muh nostalgia

**Comment by ghost** [comment]
@dylanstrategie It does change the electric chair sprites.

**Comment by CptWad** [comment]
I checked, electric chair exists and looks a bit better IMO

**Comment by SkowronX** [comment]
That reminds me. I gotta finish some shuttle chair sprites.

**Comment by ihadtoregisterforthis** [comment]
Hastily made chairs look more proper.
Dylan rebalancing sprites again.

**Comment by Zth--** [comment]
Stop being retarded. These chairs are 100x times better than current ones.

**Comment by ghost** [comment]
:+1:

**Comment by ihadtoregisterforthis** [comment]
There's something really sterile about the current ones, kinda like common plastic chairs, but made of metal. They might look better but will they fit literally everywhere?

**Comment by Imagebard** [comment]
:-1:

I like the current chairs, sorry m8. Don't fix what ain't broke.

**Comment by LordMyroc** [comment]
What @ihadtoregisterforthis said, I like the new sprite and all but they're gonna look out of place in certain areas. Shuttles immediately come to mind.

**Comment by ghost** [comment]
@LordMyroc @SkowronX says he's working on new shuttle chairs.

**Comment by 9600bauds** [comment]
My immediate concern is that the current chairs look like they're metal chairs welded or bolted to the floor, which to me sort of explains why they're not draggable.

**Comment by Shadowmech88** [comment]
I have to agree there, this chair definitely looks like you could pick it up as easily as a stool.

**Comment by ghost** [comment]
Well, maybe we could allow players to pick up and throw chairs down the line ? That sounds fun to me

**Comment by Zth--** [comment]
Yeah why not?

**Comment by Ephx1** [comment]
Only if you can fold them, for proper rage cage matches.

**Comment by 9600bauds** [comment]
Can we at least keep the old chairs as an alternative buildable like comfy chairs

**Comment by 9600bauds** [comment]
>bring a chair with you everywhere in your backpack
>plop it down and buckle yourself before opening firelocks so you don't get ZAD'd, then pick it back up

h a r d c o r e s

**Comment by clusterfack** [comment]
Tactical chairs

**Comment by sonime** [comment]
Throwing a chair makes you valid when?

**Comment by ghost** [comment]
Unless someone has an objection, looks good2merge for me

Small sprite tweaks can be done as hotfixes if someone really doesn't like it

**Comment by sonime** [comment]
But feature freeze.

**Comment by ghost** [comment]
Do we even respect it anymore at this point ? A bunch of non-fix changes were merged with approval

**Comment by sonime** [comment]
Well then brb, pushing my R-UST PR.

except I can't because I'm not at home and it isn't finished yet

**Comment by 9600bauds** [comment]
Can we at least keep the old chairs as an alternative buildable like comfy chairsCan we at least keep the old chairs as an alternative buildable like comfy chairsCan we at least keep the old chairs as an alternative buildable like comfy chairs

**Comment by ihadtoregisterforthis** [comment]
~~pomf's~~ Moe's Feature Freeze allows QOL, pre-freeze and "not a feature" merges in addition to bugfixes.

I'm not against adding these but I'm against removing the current ones.

**Comment by ghost** [comment]
You can always make a separate atomic PR to have the old chairs

**Comment by 9600bauds** [comment]
Or you could do it in this one
Turn feature loss into just features

**Comment by sonime** [comment]
Thank mr feature

**Comment by ghost** [comment]
The old chair sprites are awful and do not look like chairs. Let's not be nostalgic for the sake of it.

**Comment by Shadowmech88** [comment]
> do not look like chairs

Now you're just reaching.
They might not be great sprites but they definitely look like chairs.

**Comment by 9600bauds** [comment]
>this is not a microwave
>that is not a chair

> Visual agnosia is an impairment in recognition of visually presented objects. It is often due to bilateral damage in the posterior occipital and/or temporal lobe(s) in the brain.

Celt my man go get that checked

**Comment by ghost** [comment]
Other than looking like a 'h' I don't see how it's a chair, honestly.

**Comment by Shadowmech88** [comment]
> four legs, a seat, and a back
> 
> "Other than looking like a 'h' I don't see how it's a chair, honestly."

So you look at something like this, and you're not able to interpret that it's a chair?
Does it just look like some kind of modern art sculpture to you, or what?
image

**Comment by Ephx1** [comment]
A h!

**Comment by ihadtoregisterforthis** [comment]
First result in google for "metal chair"
metal-chair-220x230

**Comment by Ephx1** [comment]
I don't know what letter that is.

**Comment by Zth--** [comment]
It's maybe from the chinese alphabet

**Comment by ghost** [comment]
@ihadtoregisterforthis but that doesn't look like our old chairs

**Comment by ghost** [comment]
So, can we merge this yet ?

At absolute worst, someone can re-introduce the old chair sprites as another chair variant. And any chair pixel tweak can be hotfixed in

**Comment by 9600bauds** [comment]
>tagged Content
>made during Feature Freeze

In the meantime, why don't you add oldchairs back

**Comment by ihadtoregisterforthis** [comment]
Thanks a lot [Needs final decision] and discussing this overall

**Comment by ghost** [comment]
Custom vote started by DrCelt.
The new chairs are
Type vote to place your votes.
You have 60 seconds to vote.

Vote Result: Awful but still better than the old chairs with 16 votes
     Great, they should stay the same. had 4 votes
     Awful, and should be changed back had 15 votes

**Comment by 9600bauds** [comment]
Am I late

**Comment by clusterfack** [comment]
So people liked them, democracy!

**Comment by 9600bauds** [comment]
Majority of people said they are awful though

**Comment by Zth--** [comment]
I like them.

**Comment by Shadowmech88** [comment]
I think the sprites, in and of themselves, are okay.
I think they'd look silly in a lot of places on the station because they look like cheap office chairs, rather than the sturdy, solid metal, bolted-to-the-floor look that our current chairs have.

**Comment by clusterfack** [comment]
Majority of people said they were better than the old ones

**Comment by Shadowmech88** [comment]
Still awful though.
So how do we improve the sprite?

**Comment by Zth--** [comment]
Hire new spriters. We have very few

**Comment by 9600bauds** [comment]
If the majority of people say they are awful, and ~40% of people say they're even worse than the previous, that should tell you it's not a very good change

**Comment by clusterfack** [comment]
Nah people kneejerk everytime you change something before they get used to it

**Comment by ihadtoregisterforthis** [comment]
I can say that the merge was a kneejerk reaction to the freeze getting closed too.

**Comment by NigglyWiggly** [comment]
What the fuck, these look like shit.

They don't match our perspective at all, jesus christ.

**Comment by 9600bauds** [comment]
I mean I know this is already merged and all but holy wow these look worse in-game than I thought from the single image in the OP

**Pull request merged**
