### PR TITLE
Humans who lie down/crawl can pick up/use items.

### PR DESCRIPTION
**Pull request by ShiftyRail**
Requested by ChugMonkey on discord.
I'm not very confident about the change myself, especially with how powerful/fast crawling is right now.

I would highly advise against merging this before crawling allowing you to crawl at sanic speeds is fixed.
Also consider this : ordering someone to rest is no longer a guarantee that the person is harmless.

However, this does not change stunning people, which will still make them drop all of their items as well as rendering them unable to pick up for a few seconds.

Tested.
:cl:
- tweak; People who lie down/crawl can now pick up and use items. Form now on, be careful of unassuming supposedly dead corpses.

### CODE REVIEW

**Comment by SonixApache** [comment]
self surgery ahoy

**Comment by ShiftyRail** [comment]
@SonixApache Excellent call I forgot to check for that

**Comment by ghost** [comment]
why not allow self surgery only if you are on pain meds, otherwise, it will cause massive damage or just fail.

**Comment by EdXbtkOEwGw** [comment]
This makes every firefight in the game horizontal.

You can still shoot people and move around while lying down, which makes hitting you extremely hard because they have to click you directly (and even then, still can't hit you from far away if you move perpendicularly). So now there's no reason not to lie down while shooting.
Or you can just crawl up to them and baton them because nobody aims by manually clicking people.

This is ten times worse than crawling could ever hope to be.
_It really, really needs to be test merged for one whole week just to make sure it's never considered again even ironically._

**Comment by small-boss** [comment]
please no

**Comment by agentofzog** [comment]
Finally we can have dolphin diving.

**Comment by EenKogNeeto** [comment]
I'm personally against this because it cheapens the sole personal use of antag glue, which is to keep holding an item even when given the slipp.

**Comment by Fruktlimpa** [comment]
I'll have to say I'm against this as well because of two reasons.
Self-surgery should never work because it just jumps all the sharks possible.
Shooting while lying down is a big benefit as aforementioned.

**Comment by Killette2** [comment]
update: when resting have a 15% chance to bump your funny bone and stun yourself briefly

**Comment by ShiftyRail** [comment]
No more self-surgery should be possible.
I'm still not thrilled about the idea, mind you.

**Comment by Chazach** [comment]
>idea suggested by retard on discord 
>"I'm not very confident about the change myself"
>would obliterate all ranged combat
>buckling to beds no longer effective restrainment, can't even ask people to lie down as sec
>can crawl up to someone, disarm them, then use their gun against them all from the floor

epic addition to the code

**Comment by ShiftyRail** [comment]
It was a bad idea from the start anyway.

**Pull request closed without merging**
