### PR TITLE
pAI medbots

### PR DESCRIPTION
**Pull request by Zth--**
_**pAI medbots**_

Just like mulebots. 

With Q (or drop hotkey) you state there's a critical patient in the room.
With X (or swap hands) you switch mode. There are 2 modes, analyze mode and injection mode.
With clic you inject or analyze depending on your mode.

The pAI can't modify the medbot's settings, so what the medbot injects depends on humans and if there's a beaker loaded it or not.

Also adds a proc called state_controls_pai that prints text when a pAI enters an object. It is used here to print the controls and some extra info.

:cl:
 * rscadd: pAIs can be inserted into medbots. Instructions are printed when you enter one.

### CODE REVIEW

**Comment by Probe1** [comment]
Needs a hard delay on how often it can dispenses its freeheals.

**Comment by Zth--** [comment]
There's no attack delay _right now_. But if you inject somebody ONCE then you can't inject him again even if he's still hurt. I believe this is a fix of medbots overdosing people

**Comment by Kurfursten** [comment]
This will nullspace the pAI if the bot is destroyed

Needs Destroyed() behavior

**Comment by aceedex** [comment]
time to reap the salt that comes with a sentient mutagen injector

**Comment by AutismSpider** [comment]
>mutagen

Baby stuff you can make a walking talking poly acid smoke bot.

**Comment by Shadowmech88** [comment]
pAIs can buy MedHUD software, right? So they can see which people need injecting.

Does the bot itself supply any method for the pAI to monitor patients' health?

**Comment by AutismSpider** [comment]
they get medhud and medical records for 30 points

**Comment by Zth--** [comment]
@Kurfursten isn't this fixed by #13385?

I'll see if I can add a health analyzer inside the bot tonight

**Comment by Kurfursten** [comment]
You're right, should be handled upstream, good eye

**Comment by AutismSpider** [comment]
med bot is build with health analyzer though give pai med bot a verb to analyzer people on touch or some thing or med hud toggle?

**Comment by Zth--** [comment]
Ok now the medbot has 2 modes: injection mode and analyze mode. You switch them via switch_hands hotkey.

Also added a do_after to injection and cleaned some shit. This has been tested and is ready

**Comment by icantthinkofanameritenow** [comment]
What happens if the medibot is emagged?

**Comment by Probe1** [comment]
guaranteed balance issues

**Comment by AutismSpider** [comment]
@Probe1 and if it is a issue it get nip in the butt like the mule bot

**Comment by Probe1** [comment]
I'd still like to see pAI mulebots get a real job done for balance but I can only ask so much.

**Comment by AutismSpider** [comment]
Only issue with med bots is base on people fucking with the beaker inside of it means you need med id to unlock or emag.

**Comment by Zth--** [comment]
@Probe1 what's the problem with pAI mulebots? By the way should I make pAI beepsky? Or is that too much?

**Comment by AutismSpider** [comment]
need emag or med id to fuck shit up  with med bot and beakers loaded with poison etc.

**Comment by Probe1** [comment]
@Zth-- 

1.  Check for beepsky being locked
2.  Cooldowns and shit.
3.  Limitations.

What we're doing here is basically making a lesser class of borgs and what I'm scared about (as it was with mules, and I fear for medbots) is it'll be better than borgs without law restrictions.

**Comment by AutismSpider** [comment]
can't od them on base chems medbot have i try to do it.

Only risk is some one sticking beaker of some type of poison into the bot.

**Pull request merged**
