### PR TITLE
An Ayy Snack Machine Update (ZAM Madness)

### PR DESCRIPTION
**Pull request by Optimism333**
## ZAM! ##
Have you ever wondered to yourself as a Grayy working for Nanotrasen, "What did I eat in my childhood? When I was a small Grayyling, what captured the essence of my childhood whimsy?"

Well soon you need not wonder any more! Administrators are in talks with John P Nanotrasen himself to introduce a new snack machine to NT stations... Zam Snax! The Zam food labs on the mothership have been hard at work synthesizing drinks and snacks that will allow YOU to recapture your childhood in every slurp or burp.  

 * **Definitely "real" footage of John P Nanotrasen:** 
Screenshot (476)

**Disclaimer:** Recapturing of childhood is not guaranteed. Shipping fees and assembly required.

## The Actual PR ##

Anyways, lame roleplay aside, the actual pr stuff. This pr adds a Zam Snax vending machine, with several snack and drink options catered towards Grayy crewmembers. However, since Zam is attempting to expand into other markets, at least four of the products may also be enjoyed safely by non-Grayys. 

 * ### **Zam Snax Vending Machine and Recharge Pack Sprites:** ###
ZamSnaxScreenshot

 * ### **Zam Snax Snack and Drink Sprites:** ###
Screenshot (473)

Starting from left to right, snack prices, nutriment content, and reagent list:
- **Zam Moon Cheese:** A miniature piece of a very artificial cheese-like substance. Safe for anyone to enjoy. (Price = 16 credits) (Nutriment = 3) (Reagents = Nutriment, Salt)
- **Zam Biscuit:** A staple of every Grey worker's diet. (Price = 20 credits) (Nutriment = 4) (Reagents = Nutriment, Hyronalin, Cocoa, Sugar, Sulphuric Acid)
- **Zam Spider Slider:** Too poor to afford the whole microwave meal? No problem. (Price = 30 credits) (Nutriment = 5) (Reagents = Nutriment, Sulphuric Acid)
- **Zam NotRaisins:** They're really not! They're dried blecher berries. A bitter treat anyone can enjoy. (Price = 35 credits) (Nutriment = 6) (Reagents = Nutriment)

Starting from left to right, drink prices and reagents:
 * **Zam Nitro Freeze:** An absolutely frigid flavor in a bottle. Equally dangerous for anyone to enjoy. (Price = 20 credits) (Reagents = Nitrogen, Frost Oil)
 * **Zam Sulphuric Splash:** Somewhat unimaginative, but a classic. (Price = 16 credits) (Reagents = Sulphuric Acid, Lemon Juice)
 * **Zam Formic Fizz:** The cooler cousin of the above drink. (Price = 16 credits) (Reagents = Formic Acid, Lime Juice)
 * **Zam Trusty Tea:** It claims to be made with real opok juice, but can you really trust canned tea? (Price = 16 credits) (Reagents = Acid Tea, Berry Juice, Caffeine)
 * **Zam Tannic Thunder:** Despite the name, it's the mildest of all the drinks. Can be safely consumed by anyone. (Price = 20 credits) (Reagents = Orange Juice, Tannic Acid)

 * ### **Zam Snax Contraband:** ###
Screenshot (475)

From left to right, prices and reagents:
 * **Zam Radical Biscuit:** Some defective biscuits deemed unsafe for consumption. (Price = 20 credits) (Reagents = Nutriment, Uranium, Unstable Mutagen, Sulphuric Acid)
 * **Zam Biscuit Package:** Hacking the machine allows you to get two of these for free. (Price = FREE) (Nutriment = 4 x 3 (per package)) (Reagents = See the Zam biscuit entry above)
 * **Bottled Mineral Water:** An absolutely terrible poison. Why would anyone drink this? (Price = 100 credits) (Reagents = Water)

 * ### **Zam Snax Premium:** ###
Screenshot (482)

* **Zam Polytrinic Palooza:** A horrifically strong acidic and alcoholic drink that has been banned in all mothership controlled territories. Don't drink it, just don't. (Price = 1 coin) (Reagents = Hooch, Polytrinic Acid, Mindbreaker Toxin, Cocaine)

## Closing Thoughts ##
- This is my biggest pr so far, so it's very possible something went wrong or I forgot to do a thing. Please scrutinize it.
- This is also the first time I've attempted to do economic balancing. I looked at other vending machine prices and tried to make the Zam Snax prices reasonable. Let me know if some prices still require tweaking.
- Credit to the wonderful Blithering for most of the spritework that looks any good.

:cl:
 * rscadd: The Grayy food company Zam now has its own vending machine. Recharge packs may be purchased at cargo for 25 credits per 2 packs.
 * rscadd: Some unique snacks and drinks for Grayys have been added. Some are even safe for non-Grayys to consume! Experiment at your own risk.

### CODE REVIEW

**Comment by Optimism333** [comment]
Speaking of things going wrong, I have to try to figure out why this failed a check.

Edit: Not really sure what's going wrong here. The branch compiles fine locally. Could use some advice.

Edit 2: Going to fix what Eneocho spotted and see if that makes the check issue go away.

Edit 3: It's fixed. Thanks Eneocho!

**Comment by Eneocho** [comment]
A few thoughts:
1) Some of the quick descriptions you made don't mention the reagents (like the radical biscuits).
2) Why the hydrogen on the Zam H1 Breeze? What's the reasoning behind it?
3) Consider adding some premium whatevers to the zam machine, like a grayy rare-ish item or a really fuckin strong food (nutriment or chemwise). Some ideas for this are: A drink with TONS of pacid, a snack with diamond dust, a snack with 20u nutriment, a special token for whatever purpose, a spraybottle with water (the vilest of chems), a reusable token for zam stuff (works as a voucher but more than once), etc.

**Comment by Eneocho** [comment]
Also, you messed up the icon state for zam cheese and zam slider:
 UNIT TEST FAIL: /datum/unit_test/icons/food 0.8s
	REASON 1: FAILED FOR /obj/item/weapon/reagent_containers/food/snacks/zam_mooncheese :: "snack" with icon state: ""
	REASON 2: FAILED FOR /obj/item/weapon/reagent_containers/food/snacks/zam_spiderslider :: "snack" with icon state: ""

**Comment by Optimism333** [comment]
> A few thoughts:
> 
> 1. Some of the quick descriptions you made don't mention the reagents (like the radical biscuits).
> 2. Why the hydrogen on the Zam H1 Breeze? What's the reasoning behind it?
> 3. Consider adding some premium whatevers to the zam machine, like a grayy rare-ish item or a really fuckin strong food (nutriment or chemwise). Some ideas for this are: A drink with TONS of pacid, a snack with diamond dust, a snack with 20u nutriment, a special token for whatever purpose, a spraybottle with water (the vilest of chems), a reusable token for zam stuff (works as a voucher but more than once), etc.
### To Answer your questions: ###

1. **Some of the quick descriptions you made don't mention the reagents (like the radical biscuits).**

Yeah, that's completely fair. I was going to leave the reagents in those for curious code divers to find, but I'll add them now.

2. **Why the hydrogen on the Zam H1 Breeze? What's the reasoning behind it?**

It's actually a leftover from the first description I made as it was initially described to be basically flavorless, and hydrogen has no taste or smell. But now that I think about it, liquid nitrogen makes more sense for a ridiculously cold drink anyways, so I'll update it and change the name to "Zam Nitro Freeze" or some such.

3. **Consider adding some premium whatevers to the zam machine, like a grayy rare-ish item or a really fuckin strong food (nutriment or chemwise). Some ideas for this are: A drink with TONS of pacid, a snack with diamond dust, a snack with 20u nutriment, a special token for whatever purpose, a spraybottle with water (the vilest of chems), a reusable token for zam stuff (works as a voucher but more than once), etc.**

There is a premium drink already (it's mentioned briefly in the closing thoughts), but I purposefully left it off the lists above for mystery. I'll take some of these ideas into consideration however and draft some other premium item ideas.

Edit: I added the premium drink above. No sense hiding it when I'm looking for feedback.

**Comment by Kurfursten** [comment]
It's a little sad that pretty much all Grey food is dangerous to share so you won't see it out much. If you ever make more Grey kitchen food, make some that you can put out for everyone.

**Comment by Optimism333** [comment]
> It's a little sad that pretty much all Grey food is dangerous to share so you won't see it out much. If you ever make more Grey kitchen food, make some that you can put out for everyone.

Yeah... that thought process was part of the reason that I made at least three of the new consumables here safe for anyone to enjoy. 

If I do make more microwave recipes in a future pr I'll try to create more that anyone can try.

**Comment by Eneocho** [comment]
> 
> 
> > It's a little sad that pretty much all Grey food is dangerous to share so you won't see it out much. If you ever make more Grey kitchen food, make some that you can put out for everyone.
> 
> Yeah... that thought process was part of the reason that I made at least three of the new consumables here safe for anyone to enjoy.
> 
> If I do make more microwave recipes in a future pr I'll try to create more that anyone can try.

Make sure that the recipe itself doesn't add acid (instead working from the crop's chems) so if the chef/botanist makes a non-acidic pitcher, the food is normally edible.

**Comment by Optimism333** [comment]
I took the acid content off the NotRaisins so now 2 out of the 4 snacks are safe for anyone to try.

**Comment by Optimism333** [comment]
Per feedback from Bomber Harris, made some tweaks to the off and broken sprites of the vending machine. Screenshot has been updated.

**Comment by Eneocho** [comment]
If this gets merged we'll need a mapper to add one of these to the maps.

**Comment by Eneocho** [comment]
An idea: You could add a premium snack(or a corn oil can) that has corn oil instead of sacid so you can eat it to neutralize the sacid and safely eat the acidic foods. It would need to have 45u corn oil to neutralize 15u of sacids.

**Comment by Optimism333** [comment]
> An idea: You could add a premium snack that has corn oil instead of sacid so you can eat it to neutralize the sacid and safely eat the acidic foods. It would need to have 45u corn oil to neutralize 15u of sacids.

That is an interesting idea, and would be a clever use of chemistry to let people who aren't Grayys eat some of the more acidic stuff. I'll keep it in mind. The only thing that gives me pause is I'd have to try to keep the corn oil amount under about 15u because I think past that it starts to give heart damage.

**Comment by Eneocho** [comment]
> 
> 
> > An idea: You could add a premium snack that has corn oil instead of sacid so you can eat it to neutralize the sacid and safely eat the acidic foods. It would need to have 45u corn oil to neutralize 15u of sacids.
> 
> That is an interesting idea, and would be a clever use of chemistry to let people who aren't Grayys eat some of the more acidic stuff. I'll keep it in mind. The only thing that gives me pause is I'd have to try to keep the corn oil amount under about 15u because I think past that it starts to give heart damage.

You need 3 times oil to neutralize sacid, so for the cornoil food (Maybe just a bottle of corn oil) to work, it'd either need large amounts of corn oil or for the rest of the food to have less sacid. Besides, the heart damage is a only a 10% chance per tick, if you chug the oil fast then gobble the zamfood you'll probably be fine.

**Comment by TGFH** [comment]
Very cool.

**Comment by Kurfursten** [comment]
dmi conflicts, let me know if you need help

**Comment by Kurfursten** [comment]
today I will remind him

**Comment by Optimism333** [comment]
> today I will remind him

Been busier than usual, will try to fix it this week.

**Comment by wotisjanitor** [comment]
As an exclusive Gray player, I love anything that adds content for them. Good work. I would love to see more microwave recipes for Gray food.

**Comment by Optimism333** [comment]
Closing this conflicting pull. I should have a new one up soon that fixes the conflicts.

**Pull request closed without merging**
