### PR TITLE
Removes stone mask from spessmart

### LINKED ISSUE #14234: Infinite stone mask can and does spawn in spessmart
#### Description of issue
The Stone Mask Infinite Edition spawns in spessmart. It costs 150 credits and turns anyone (and everyone - it's infinite) into a vampire. Is this really a good idea?
image

#### Difference between expected and actual behavior
Instead of a fun trip to the mall you get a 20-man vampfest for the small price of some blood.

#### Steps to reproduce 
1. Load up spessmart
2. Repeat step one if the mask did not spawn
3. Check out that the mask is infinite
4. Turn everyone into a vamp

#### Specific information for locating

I'm guessing it happens because of this:
https://github.com/d3athrow/vgstation13/blob/c2163cfd52ae751de38055d8747d23e235c30846/maps/randomvaults/spessmart.dm
`var/list/clothing = existing_typesof(/obj/item/clothing) - typesof(/obj/item/clothing/suit/space/ert) - typesof(/obj/item/clothing/head/helmet/space/ert) - list(/obj/item/clothing/suit/space/rig/elite, /obj/item/clothing/suit/space/rig/deathsquad, /obj/item/clothing/suit/space/rig/wizard, /obj/item/clothing/head/helmet/space/bomberman, /obj/item/clothing/suit/space/bomberman) //What in the world could go wrong`

#### Length of time in which bug has been known to occur

Since spessmart was introduced, presumably

#### Server revision

f72fecb701a91a944378edf4eb41dfdbe4a3934b

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched "stone mask" and "spessmart"

### PR DESCRIPTION
**Pull request by Probe1**
Closes https://github.com/d3athrow/vgstation13/issues/14234

### CODE REVIEW

**Comment by Probe1** [comment]
Did it not compile or did travis fail.

I should have done this locally.

**Comment by Probe1** [comment]
I'll sort this bullshit out in the morning hopefully when travis is working.

**Comment by Shadowmech88** [comment]
You could always compile it locally and then ignore Travis, couldn't you?

**Comment by Probe1** [comment]
That's the plan.  It's already past midnight and I don't want to do it tonight, and I don't want to leave up a PR that may or may not compile.  

I'd be very happy if you whipped one up real quick.

**Comment by Shadowmech88** [comment]
Travis is probably going to meme on me just like it did you, but I'll give it a shot.

**Comment by Probe1** [comment]
This is why I love you even when fixing oversights

**Comment by Shadowmech88** [comment]
@Probe1 #14242

**Pull request closed without merging**
