### PR TITLE
deletes lootbox and all references

### PR DESCRIPTION
**Pull request by SonixApache**
some guy accidentally left an item in the code that gibs you when you use it without telling you that it does so, resulting in many new players accidentally destroying themselves
this joke item keeps accidentally showing up in various places, causing grief to many players, which then causes grief to the admins and lowers the playercount and general level of fun

this PR aims to rectify that

closes #24043

🆑 
 - rscdel: removed the suicide lootbox

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
It's funny for me to hear of the incidents
Maybe the lootbox users should go with the following mindset:
"I was gibbed by an item recently"
"I was pretty bummed about it"
"But at the same time I provided more joy to the people that have witnessed it than I have lost, meaning there is more joy in the world"
"So, whatever"

**Comment by SonixApache** [comment]
this isn't the place to plug your cuckoldry fetish @boy2mantwicethefam

**Comment by boy2mantwicethefam** [comment]
The only cuckoldry being done is your mind letting me live rent free motherfucker

**Comment by DrSnips** [comment]
This PR was made a week or two early. You're supposed to wait until another PR """""changes it for the better""""".

**Pull request closed without merging**
