### PR TITLE
Fix missing wire under Roidstation prison solar tracker

### PR DESCRIPTION
**Pull request by brndd**
## What this does

Adds a single missing wire under the RoidStation permabrig solar tracker which has been broken since the map's launch.

## Why it's good

It makes the solars in the RoidStation permabrig actually generate power.

## Changelog

:cl:
 * bugfix: RoidStation: Fixed the prison solar tracker

### CODE REVIEW

**Comment by brndd** [comment]
No idea if this is how we do mapping PRs these days. I was told something about TGMs in the Discord but couldn't find anything like that in the repo. I was also told about StrongDMM but I don't want to set that up, so I added the wire in using a text editor.

**Comment by toomykins** [comment]
strongdmm doesnt work with our current byond version so yeah this is the way to go

**Comment by kilozombie** [comment]
TGM is just a way of formatting .dmm files that prevents conflicts more often and maybe has some other advantages. I believe this might break map editors

**Comment by brndd** [comment]
I downloaded StrongDMM and did the change using that, and it resulted in exactly the same diff, so I think this should be fine. The hand-edited version also opens fine in StrongDMM.

**Pull request merged**
