### PR TITLE
Add mushmen spores to black market

### PR DESCRIPTION
**Pull request by arc166**
Seems harmless enough. Gives a way to access them without traders and without breaking into vox outpost. price may be off,. Dunno what a vox would charge for thse.

:cl:
* rscadd: The black market now sells mushman spores.

### CODE REVIEW

**Comment by Irradiation** [comment]
Probably the only good thing in the Black Market right now.

**Comment by Kharkov72** [comment]
now that's the spice

**Comment by utilitas-** [comment]
nothing, since vox traders either do not exist or do not trade
make this guy in charge of the black market, not fucking glasseclipse

**Comment by Kharkov72** [comment]
where's the changelog eggman

**Comment by BomberBro** [comment]
Pretty good, but you can already get mushmen normally. You just need to hack the vendor in botany and mutate plump helmets, it's not exclusive to v*x.

**Comment by AI-Is-Rogue** [comment]
You're thinking of walking mushroom seeds, moshrum seeds are vox only and do not mutate into or from anything.

**Comment by tuypo1** [comment]
Now if we really need to have a black market this is the sort of stuff we should be seeing.

**Comment by Kurfursten** [comment]
needs 🆑

**Pull request merged**
