### PR TITLE
fix icon state of syndie football helmet

### PR DESCRIPTION
**Pull request by nervere**
#32820 changed something it shouldn't have with the helmet, so I adjusted the icon state in the spritesheet to match it up.
[bugfix][sprites]
## Changelog
:cl:
 * bugfix: Syndie football helmet now displays properly on mobs.

### CODE REVIEW

**Comment by Eneocho** [comment]
I had forgotten to change that as well. Good catch.

**Comment by boy2mantwicethefam** [comment]
Doesn't that formatting shit the automatic changelog?

**Comment by Eneocho** [comment]
It does. It should only have the bugfix line under the :cl: icon, the rest above.

**Comment by nervere** [comment]
Sorry, it's been a while. Fixed it.

**Pull request merged**
