### PR TITLE
Adds wizard simple mob

### PR DESCRIPTION
**Pull request by unid15**
Shoots fireballs

Creates some smoke and disappears when dies (making it look like a teleport away)

image

### CODE REVIEW

**Comment by DeityLink** [comment]
The facial hair is good but they need some long hair on their back Dumbledore-style as well.

**Comment by ihadtoregisterforthis** [comment]
There are a few loose hunchback pixels on the east/west sprites. Also you didn't include a frontal view.

What is the SCYAR NILA thing?

**Comment by unid15** [comment]
They shout SCYAR NILA (random location) and create smoke when they die, making it look like a teleport away.

**Comment by Skullyton** [comment]
Ooh, we've got a sprite for a wizard called Nim that's unused in mob.dmi, could use that for a grandmaster wizard mob.

**Comment by clusterfack** [comment]
This is neat, wish they could cast more spells though.

**Comment by DeityLink** [comment]
They're still bald. Why are they bald? Best wizards aren't fully bald.

**Comment by unid15** [comment]
They aren't the best wizards, that's why they're simple mobs

**Pull request merged**
