### PR TITLE
Adds a new Space Vault: Syndicate Shuttle

### PR DESCRIPTION
**Pull request by small-boss**
Adds a new random vault to space which is a syndicate shuttle (which is not a actual working shuttle) Was able to compile with no errors, testing on a local server works.
screenshot_84

### CODE REVIEW

**Comment by jakmak6** [comment]
does the nuke function (if you had a functional code + disk) or is it a dummy nuke

**Comment by small-boss** [comment]
> does the nuke function (if you had a functional code + disk) or is it a dummy nuke

nuke does function like a normal one. i can change it if needed. figured that a syndicate shuttle would have a nuke on their ship for operations

**Comment by small-boss** [comment]
also the windows and the armory are blocked by a set of shutters which get opened by the cockpit button

**Comment by ghost** [comment]
It is weird to have a Discount Dan's machine on a syndicate ship using Gorlex Hardsuits, but I suppose it could have been stolen.  Really neat vault.

**Comment by small-boss** [comment]
> It is weird to have a Discount Dan's machine on a syndicate ship using Gorlex Hardsuits, but I suppose it could have been stolen. Really neat vault.

syndicate gotta cheap out on the food, can't have those premium vending machines with chocolate coins and all

**Comment by Blithering** [comment]
Could you add a stethoscope to the medbay, that way people can take a crack at the safe

**Comment by small-boss** [comment]
> Could you add a stethoscope to the medbay, that way people can take a crack at the safe

good idea

**Comment by SonixApache** [comment]
why discount dan and not donk pockets though

also wew lad even more free syndi shit and hardsuits

**Comment by small-boss** [comment]
I forgot donk pockets existed while making the map. I will replace the machine with that. And what can I do to balance more free syndicate shit? I have no creativity and just made a syndicate shuttle. I would replace some of the spacesuit armed ops but their counterparts have a burst fire laser that crits you if you get shot twice, and instacrits you when there are two of them attacking you on the same time. Because it's a laser you can't dodge it easily. But seeing how the loot you get is pretty good I might just add them in. Not like you shouldn't go into a fight with a whole shuttle of armed mercenaries unprepared.

**Comment by Riekland** [comment]
fucking no
one vault filled with syndies that you can loot and guns and shit was one too many
this is what, the third or fourth vault that lets you get syndie shit? fuck off
at least make it so there's no syndie hardsuits so you can't have a bunch of red suited fucks running around making people think there's nukies

**Comment by small-boss** [comment]
Whoops I am retarded, didn't realize that there was a type for suitless ops that use the c20. What about this?

screenshot_87

**Comment by SonixApache** [comment]
better, rather have this than that one with the wish granter in it

**Comment by Riekland** [comment]
That's better
I'd still rather just not have these syndie vaults but I can see I'm not holding the popular opinion
Surely the syndie loot spawns should all be in the safe and have shit that isn't explicitly syndie just lying around?

**Comment by SonixApache** [comment]
why would syndies keep syndie shit in a safe

**Comment by Riekland** [comment]
the same reason they have explosive implants
to keep nanotrasen fags from getting at their cool shit

**Comment by ghost** [comment]
Nuke's fine. It has its own different rng code, and they still need a disc to brute force one of 90,000 combinations without making a single mistake. Good on them if the comdom is worthless and the round lasts 1.5-5 hours.

**Pull request merged**
