### PR TITLE
Wizard Spell: Become Snakes

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds a new spell which allows the user to spawn 49 snakes and transmogrify himself into a snake.
It costs half the standard spell price.
It does not require robes to cast, and has a 30 second cooldown.

The spawned snakes are deleted the next time the spell is cast, so the user can't make infinite snakes.

If you are killed as this specific type of snake, you don't die for real, you just un-transmogrify.
Your spells do not recharge while you are a snake.

:cl:
 * rscadd: Added a new wizard spell which turns the caster into 50 snakes.

### CODE REVIEW

**Comment by Megamaw** [comment]
does using it again turn you back?

**Comment by Arthurdentist** [comment]
does this spell have any real utility? You''ll be easy as piss to kill as a snake.

**Comment by Shadowmech88** [comment]
>does using it again turn you back?

You don't have access to your spells while you're a snake. You do have access to a single spell that turns you back into your previous form.

>does this spell have any real utility? You''ll be easy as piss to kill as a snake.

You are one of 50 identical snakes within a small area. It can give you some time to catch your breath during combat and maybe even escape.
Also, if you are killed as this specific type of snake, you just un-transmogrify, you don't actually die for real.

**Comment by yclatious** [comment]
Spawning 49 extra Corpus snakes is such a fucking stupid awful idea, it works. Merge when?

**Comment by FudgePucker** [comment]
Considering this spell would be worthless if somebody used an AoE weapon (flame thrower polyacid smoke to name two) letting you recharge spells at a fourth of normal speed would make it worth the spell points.

**Comment by Shadowmech88** [comment]
I don't see how the ability to recharge spells while in snake form would help if your snake form is quickly killed along with all the other snakes by some AoE weapon.

**Comment by carshalash** [comment]
Do the snakes attack people at all, or do much?

**Comment by Shadowmech88** [comment]
They do nothing except wander a bit. Snakes are subtypes of cats, which are not hostile nor retaliatory.

**Comment by Blithering** [comment]
Would it be possible to make an upgrade/ancient spellbook version of this that uses spiderlings instead of snakes?

**Comment by Shadowmech88** [comment]
"Spawn 50 spiders at once" is a bit too powerful for a wizard, I think.

**Comment by Blithering** [comment]
I was going to point out they'd be spiderlings, but then I realised people would just sit in maints using the spell repeatedly to make an unstoppable spider wave, okay bad idea I admit.

**Comment by Intigracy** [comment]
This already passed travis before the last commit editing the dmis

**Comment by IAGFPRMF** [comment]
This spell is goofy. Why not sticks to snakes instead? That's pretty wizardy

**Comment by Exxion** [comment]
Oh yeah I was going to do that but then I forgot

**Pull request merged**
