### PR TITLE
Clowning Guns

### PR DESCRIPTION
**Pull request by Kurfursten**
PR for Luzzgawr
Does not work on their subtypes (e.g.: AEG, fancy glock).
The alternate shotgun will quack if pumped.

Fully tested

🆑 
* rscadd: You can clownify the pump shotgun, NT glock, or egun with a rainbow crayon. Bleach cleans them back to normal.

### CODE REVIEW

**Comment by Gazathor** [comment]
This is the high quality clownbuff content we have all been waiting for

**Comment by agentofzog2** [comment]
what about tasers

**Comment by Kurfursten** [comment]
He only made 3 sprites, only those mentioned can be crayoned

**Comment by KingofHONK** [comment]
Soon, all armories will learn to fear the power of the honkmother

**Comment by FudgePucker** [comment]
Can you clown more than one gun per crayon?
Something more fun to do in the armory than shooting all the guns

**Comment by Kurfursten** [comment]
Using the crayon on the gun does not consume the crayon, you can also queue up more than one gun to clown at once, assuming they are both within reach.

**Comment by Intigracy** [comment]
Could make clowning reverse the clumsy check's effects, popping for non clumsy people

**Comment by Kurfursten** [comment]
I feel like the clown having a bag full of functional eguns goes against his spirit as a job. He wants to vandalize guns but leave them behind to mock them, not hack a bunch of guns to powergame for himself.

Also, by merely changing the sprite and not the actual function, people will still *use* vandalized guns instead of just throwing them in lockup until someone can bring bleach.

**Comment by SonixApache** [comment]
~~fully tested? there's no sprites for the ~~glock~~ AEG, is there?~~
disregard, i suck cocks, etc

**Pull request merged**
