### PR TITLE
EHS QoL

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][qol][tested]

## What this does
Makes people with this character preference disability spawn with a space blanket and tinfoil hat.

## Why it's good
Makes them not immediately take pain and have a better chance of surviving outside it.

## Changelog
:cl:
 * rscadd: NT has finally equipped crew hypersensitive to electricity with shielding clothing.

### CODE REVIEW

**Comment by TurboGay** [comment]
Who is this quality of life even for considering it took a month for someone to notice how horrendously implemented it is in that it puts you into permanent paincrit almost instantly? Why not just fix that instead of snowflaking in three items for a roundstart disability?

**Comment by BomberBro** [comment]
This isn't really too obnoxious except for the APC being turned off, if you spawned as a scientist in RnD for example could you even turn it on without outside assistance? On second glance it gives you a crowbar too.... why?

**Comment by Eneocho** [comment]
Remove the APC disabling and we have a deal

**Comment by SECBATON-GRIFFON** [comment]
> On second glance it gives you a crowbar too.... why?

opening doors when the APC is off

**Comment by Kurfursten** [comment]
👎 for disabling the APC, just a huge hassle for other players and it's not like being in the middle of an island of power off even helps them. If you insist on disrupting gameplay more than adding an item, you could spawn them in the chapel which is fairly large and empty away from machines + inject 15 units tramadol to offset pain for the first 150 ticks of gameplay (300 seconds / 5 minutes).

I also believe some tweaks to EHS itself would make it much more livable. Machinery includes lights, but lightbulbs do NOT gain the BROKEN flag if the bulb is smashed, nor do they gain the NOPOWER flag if the lights are off. Both of these mean that breaking lights or turning them off does not protect the EHS victim at all - as far as I can tell.

**Comment by Dacendeth** [comment]
This mutation needs to be added to the list of ones you cant randomly start with as well.

**Comment by SECBATON-GRIFFON** [comment]
removed APC stuff

**Comment by SECBATON-GRIFFON** [comment]
@Kurfursten removed APC stuff

**Comment by Kurfursten** [comment]
Okay I took off my vote

If you want help with the other stuff I'll provide it, bit I won't force you to fulfill feature requests

**Comment by Kurfursten** [comment]
The other PR dealt with the issue by making electrosense more of a nuisance than crippling. This PR no longer seems needed. However, I will say that you are welcome to bring this PR again if you feel after at least 3 days there is still demand for it.

The PR would be in an entirely different era though. Because as of the new bleeding edge, these clothes would completely cancel the disability instead of just lowering it to 25%.

**Pull request closed without merging**
