### PR TITLE
Fix vox bald hairstyle + Adds some missing vox clothing sprites (mostly from paradise)

### LINKED ISSUE #34137: vox bald hairstyle
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
8f5ebc80422efe9dd4d9f6adfcef843761c7db2e
makes an F_STYLE error when wearing a helmet

### PR DESCRIPTION
**Pull request by gurfan**
Very dirty and messy PR, but I didn't want these sitting on my computer forever.

## What this does
Closes #34137
Adds a handful of missing vox clothing items. Some sprites by me, most of them taken from paradise (but altered slightly to fit /vg/ vox)
I was planning to separate all the new clothing sprites PRs by category, as done for insectoids, but I ended up going through clothing without much rhyme or reason to it.

### Clothing Added/Updated:

Jumpsuits:
- CIA Jumpsuit
- Missing Colored/Rainbow Jumpsuits
- Clown Jumpsuit
- Captains Tunic / Nun Tunic (now have vox-looking shoes)
- White Security Officer Uniform
- Security Skirt 
- Dresses / Wedding Dresses 
- BTC Bartender Uniform (tweaked to fit)
- Black Suits / Vice Suits
- Scratch Suit
- Green Suit
- Laborer Overalls
- Amish Suit
- Swimsuits
- Sexy Mime/Clown
- Psychic Suit
- Schoolgirl Uniform
- Redcoat Uniform
- Roman Uniform
- Tourist Suit
- Mankini
- Kilt
- Gladiator Uniform
- Owl Uniform
- Jester Suit

Ears:
- Headsets
- Earmuffs

Armor/Suits/Spacesuits: 
- Bomb Suit
- Fire Suit
- Carapace Armor (vox wearing them no longer look barefoot+gloveless)
- Radiation Suit (no longer appears barefoot)
- Captain Rigsuit (no longer appears barefoot)
- Psychic Robes
- Captain Rigsuit Visor (Now Animated)
- SWAT/Syndicate Mask (Now Animated)
- Chicken Suit

Hats:
- HoS Hat
- Gladiator Helmet
- Roman Helmet
- Cowboy Hat 
- Headband
- Rice Hat
- Hardhat (fixed light on sprite)
- Beanies
- Jester Hat
- Magus Helmet
- Beret
- Bear Pelt
- Garrison Cap
- Peaked Cap
- Chicken Hat

Gloves:
- Fingerless gloves

Masks:
- Pipes
- Fake Moustache
- Sexy Mime Mask
- HECU Mask

Shoes:
- Winter Boots (Tweaked)
- Clown Shoes / Psyche Clown Shoes
- Atmos Magboots / CE Magboots / Syndie Magboots
- Missing Colored/Rainbow Shoes
- Cowboy Shoes
- Leather Shoes
- Slippers
- Kneesocks
- Ninja Shoes
- Sandals
- Roman Shoes

Eyes:
- Thermonocle (how did they not have a fit for this already?)
- Night Vision Goggles
- Eyepatch
- Thermals

## Why it's good
It looks better.

## Changelog
:cl:
 * bugfix: Fixed an error with the Vox Bald hairstyle.
 * imageadd: Added new vox sprites for some clothing items.

### CODE REVIEW

**Comment by pedr69** [comment]
hang on the species fit flag makes the f style error?
you'd think it would make you unable to wear the stuff if you weren't in the whitelist

**Comment by gurfan** [comment]
The f_style error was because the bald hairstyle had no "under helmet" icon

**Comment by SonixApache** [comment]
i don't know if `template` under `masks.dmi` is necessary for anything but you've fucked it up pretty good

**Comment by gurfan** [comment]
its only used as a template but I'll fix it, whoops

**Comment by Eneocho** [comment]
keep the template as a vox mask clown disguise

**Comment by PrimeDSS13** [comment]
Fetish Content.

**Comment by SonixApache** [comment]
make sure there's no licensing issue with the sprites

**Comment by gurfan** [comment]
> make sure there's no licensing issue with the sprites

All icons from paradise are CC

**Pull request merged**
