### PR TITLE
Mechanic Clubhouse Vault

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Adds a small vault based on the ingenuity and independence of mechanics. I, and the mechanic who built it, don't know too much about engines so I used a self charging cell. I hope it works out for both of us. 
This is my first time contributing so sorry if I break the video game.
Thanks to Damian for the tweak to APC code.

mechclub

:cl:
 * rscadd: A small vault about a clever mechanic

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Oh yeah? Where's the binary encryption key or traitor encryption key? Where are the dozen syndie guard mobs? Where are all the free cool stuff that make you overpowered like the flawless bluespace crystal? Heh....turns out this vault was doomed from the start.......

**Comment by Kurfursten** [comment]
>plastic flaps and floors

plastic parts gang...

**Comment by tuypo1** [comment]
A special self charging cell or a standard radioactive one?

**Comment by GreatBigFailure** [comment]
> A special self charging cell or a standard radioactive one?

Standard radioactive. It's a pretty rad clubhouse.

**Comment by ghost** [comment]
You need to put a single cool item in there.

**Comment by Kurfursten** [comment]
Don't worry, he already snuck in a traitor device analyzer. That's like having an infinite number of guns inside.

**Comment by GreatBigFailure** [comment]
I have just learned you need to do more than put the map into the randomvaults folder to make your vault spawn. I did not do more than that. Woops.

**Comment by Kurfursten** [comment]
Oh yeah, you need to create a vault datum, hit up the coder discord if you need help

**Pull request merged**
