### PR TITLE
Grenade timer tweaking tweaking

### PR DESCRIPTION
**Pull request by MadmanMartian**
Grenades timer can now be anything between infinity and 3 seconds

:cl:
 * tweak: Flashbangs can no longer be set to detonate instantly
 * tweak: Flashbangs can now have their time set to anything between infinity and 3 seconds

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Fair to experiment
Maybe make it work from inventory, else this will be pretty clunky

**Comment by ghost** [comment]
Does it need to be three seconds minimum ?

Obviously 1-2 seconds timer is dangerous, but it's already possible on C4 and tank transfer valves

**Comment by ShiftyRail** [comment]
The whole point is that 1sec bangers are ubiquitous and unfun to play with/against

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This breaks the bangerboy religion conversion ritual, good otherwise

**Comment by SonixApache** [comment]
- >removing instant-bangers
- >removing 1sec bangers

- >no changelog

what the fuck my dude

**Comment by DrSnips** [comment]
Hold up just a second. This is a balance change since it does lock out previous past options. It doesn't matter how you feel about them but if you want to make it not a balance change allow all of the options as you could before.
Also make sure the banger boy thing that was recently added plays nicely with this.

**Comment by ghost** [comment]
Byond time is shit, it shouldn't have a minimum longer than 2 seconds. Especially after the flashbang nerfs.

**Comment by SonixApache** [comment]
can you reword it so it says "3 and infinity"
also why the fuck do you allow up to infinity?
also pop-up menus for setting timers would be a *big* detriment to their actual use in the field

also poll

**Comment by ghost** [comment]
Yeah, the pop-up has to go. C4 does it fine, right click to set time and then apply to nearest area

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It's literally the same popup as C4 except you use a screwdriver for popup instead of attackself

**Comment by bathosbathtime** [comment]
I'll make a poll.  I agree that it will be necessary after looking at those tags.

**Comment by ShiftyRail** [comment]
Update the changelog or make it so you can do it without needing to hold the nade in your hands because it's cancerous

**Comment by robosperg** [comment]
remove needing to hold in hands or add it to the PR description

**Comment by ghost** [comment]
Dear lord why is this getting polled. I'm gonna have to say no because 3 seconds minimum is gay

**Comment by bathosbathtime** [comment]
> dear lord why is this getting polled.
>
it's 12-3 in emojiocracy and six days old.  It almost certainly would've gotten merged in the next batch if there wasn't polled.  Probably still will if the emojiocracy is any actual indication of feeling of the community.

**Comment by MadmanMartian** [comment]
Update:
 Grenade tweaking now checks for adjacency, rather than if it's in the users hand.

**Comment by RealestEstate** [comment]
Bangerbois are keepers of the forbidden art of 1 second bangers. should possibly let a bangerboi chaplain be able to set bangers to 1 second and followers to set it to 2 seconds.

**Comment by jknpj** [comment]
>making the chaplain security's personal flashbang slave

no

**Comment by iFlashYou** [comment]
merge when?

**Comment by bathosbathtime** [comment]
Poll is still open: http://ss13.moe/index.php/poll/177
It will close on 2019-01-13 05:00:00

**Comment by iFlashYou** [comment]
merge when?

**Comment by jknpj** [comment]
@MadmanMartian remember the bangerboi religion

**Comment by SonixApache** [comment]
>can't actually set it to 3 seconds

good job

**Pull request merged**
