### PR TITLE
Bumcivillian recipe change.

### PR DESCRIPTION
**Pull request by Eneocho**
Bumcivillian is the sound sucking chem added in #32704.
### What this does
Changes the recipe for bumcivillian from Iron + Sacid and ringing a bell near the reaction in the last 3 seconds to dunking a metal sheet on sacid, which requires a comically large Erlenmeyer flask or jar.. It's the same reaction system used in #29331.
### Why it's good
Fits better with the original [source material](https://www.youtube.com/watch?v=GG4qEzPsbo8) (the bell was rung to prove the reaction happened, not to cause it), and makes it a viable compound to use. Does not touch bumcivillian's behaviour itself at all.
Won't be that big a balance change as the sound suppresion is limited to only the 7x7 area centered around the reaction. You can just move a couple tiles and speak again.
:cl:
 * tweak: Changes Bumcivillian (the sound sucking chemical)'s Recipe. To make bumcivillian you must dunk a metal sheet on sulphuric acid, this requires a comically large Erlenmeyer flask or a jar.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
I think a large part of the humor in the current implementation comes from the bell thing.

**Comment by west3436** [comment]
Pro: pretty sure you and I are the only ones whom have ever made this, so this could made it more frequently used.

Con: might turn this into a powergay chem and does take away the humorous novelty of it.

Upvoted because bumcivilian mentioned

**Comment by Eneocho** [comment]
Yes, it loses some novelty, but this definitely makes it useful. It is my firm belief that gimmick chems should be viable, even if suboptimal. Many of the gimmick/ghetto chems suffer from being either too convoluted to make at scale or having such a niche use they're pretty much never used.
Locutogen fills an extremely specific niche, but it is viable for the WGW enthusiast chemist. Simply pour 5u on all your pill batches and everyone will have to deal with WGW when getting treated. Or inject some into the chef's food, same effect.
Midazoline makes you perfectly immune to all chemical interactions (except mercury + midazoline) and has the added bonus of mass producing gold powder, sacid and clonexadone if you bother electrolysing.
Bumcivillian, on the other hand can't be used as freely as these two. And since you need to ring a bell to use, it is very conspicuous, 'cause everyone can see you dragging/building one. I don't think it will be abused to powergame levels, as Chloral is king there (the chance to dethrone chloral with Suxameth was wasted), and you can just move one screen in any direction in order to speak again.

**Comment by ErrorsWindows** [comment]
bro I still don't know how to make chloral without looking at the wiki or electrolyzing sleep toxin

**Comment by Eneocho** [comment]
> bro I still don't know how to make chloral without looking at the wiki or electrolyzing sleep toxin

I don't know it by heart cause I'm not a filthy chloral baby but I think it's ethanol, chlorine and water.
Yep, just checked, 1 ethanol, 3 chlorine, 1 water.

**Comment by gurfan** [comment]
Boring.

**Comment by Kurfursten** [comment]
Having tested the bumcivilian recipe today I can say the current recipe is EXTREMELY inconsistent. I was really struggling to get it to work but did twice. Have you tested yours?

Also I think bumcivilian would really benefit from some kind of visual effect to show what the hell is happening. It's going to be very confusing to players unfamiliar with it if this chemical is used more often. If not an effect, maybe at least a message?
`Suddenly, everything around \the [my_holder.atom] becomes perfectly silent...`

Final comment, which goes back to the first thing: shouldn't bumcivilian... "cook off" over time? As it is you just get left with a beaker full of this stuff that doesn't get used for anything (except electrolysis)

**Comment by west3436** [comment]
> Final comment, which goes back to the first thing: shouldn't bumcivilian... "cook off" over time? As it is you just get left with a beaker full of this stuff that doesn't get used for anything (except electrolysis)

Current design is accurate to the source material

**Comment by Kurfursten** [comment]
> > Final comment, which goes back to the first thing: shouldn't bumcivilian... "cook off" over time? As it is you just get left with a beaker full of this stuff that doesn't get used for anything (except electrolysis)
> 
> Current design is accurate to the source material

You're right, I went back and rewatched it.

**Comment by Eneocho** [comment]
> Having tested the bumcivilian recipe today I can say the current recipe is EXTREMELY inconsistent. I was really struggling to get it to work but did twice. Have you tested yours?

Yes, works as intended.
> Also I think bumcivilian would really benefit from some kind of visual effect to show what the hell is happening. It's going to be very confusing to players unfamiliar with it if this chemical is used more often. If not an effect, maybe at least a message? `Suddenly, everything around \the [my_holder.atom] becomes perfectly silent...`

That could be a thing. Would this work?
`var/location = get_turf(holder.my_atom)`
`	for(var/mob/M in viewers(5, location))`
`	to_chat(M, "<span class='warning'>Suddenly, everything around \the [my_holder.atom] becomes perfectly silent...</span>")`
I'd also try to make it mention the guy holding the jar in case the guy is holding it but not sure how to.

**Comment by Kurfursten** [comment]
visible_message already finds the turf, so you can just do
`holder.my_atom.visible_message(text)`

You can mention the guy holding it by using your choice of get_holder_at_turf_level or get_holder_of_type both documented in unsorted.dm -- the first is better if you want to be able to include stuff like "the beaker held by the chem dispenser" or the second is better if you only want to display "the beaker held by Joe Greyshirt"

you can make this display only if found with a simple ternary statement
```
var/atom/A = get_holder_at_turf_level(holder.my_atom)
holder.my_atom.visible_message("<span class='warning'>Suddenly, everything around \the [my_holder.atom] [A ? "held by \the [A] " : ""]becomes perfectly silent...</span>")
```

**Comment by Eneocho** [comment]
I was thinking more along the lines of:
"Suddenly, everything around GreyMcshirt Assistbro goes perfectly silent..."

**Comment by Kurfursten** [comment]
`holder.my_atom.visible_message("<span class='warning'>Suddenly, everything around [A ? "\the [A]" : "\the [my_holder.atom] "]becomes perfectly silent...</span>")`

If held by assistant
> Suddenly everything around Greyshirt becomes perfectly silent...

If held by chemmaster
> Suddenly everything around the chemmaster 3000 becomes perfectly silent...

If on the floor
> Suddenly everything around the bluespace beaker becomes perfectly silent

**Comment by Eneocho** [comment]
It seems to break at the [my_holder.atom] part. Not sure how to fix it.

**Comment by Kurfursten** [comment]
A typo in my code, that should be holder.my_atom not holder.atom

I also think there's a missing space after [A]

**Comment by Kurfursten** [comment]
did you test this? remember I have been on hydrocodone for several days straight

**Comment by Eneocho** [comment]
I did, it worked fine. You ok?

**Comment by adacovsk** [comment]
Get well soon

**Pull request merged**
