### PR TITLE
Role datums rebase

### PR DESCRIPTION
**Pull request by ShiftyRail**
>1647 commits

Hopefully I did this right
I checked, it compiles, I did the .dmi & the maps

Hopefully I didn't mess anything

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Some circuits boards to be checked, I'll do that later today

**Comment by ShiftyRail** [comment]
This last commit fixes Travis
Also this PR should work if merged correctly

**Comment by MadmanMartian** [comment]
I think Travis is having a heart attack

**Comment by ShiftyRail** [comment]
Travis finished
Github is just dumb
Click on the orange dot

**Comment by ShiftyRail** [comment]
@MadmanMartian YOU BROKE IT

**Comment by DeityLink** [comment]
image

why was this change done exactly?

**Pull request merged**
