### PR TITLE
Janitors do it for free on April Fools Day

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
:)

:cl:
 * tweak: On the most foolish of days of the year, janitors lose their income, toiling for no monetary compensation.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Please make it so that janitors receive 2 boxes of donk pockets as part of their starting equipment on April Fools, as alternative wages

**Comment by Irradiation** [comment]
We have actual tendies now, so give them tendies instead.

**Comment by ghost** [comment]
he will never have a real job

**Comment by Eneocho** [comment]
> 
> 
> We have actual tendies now, so give them tendies instead.

But which tendies do they get? Chicken Tendies in a box or tendie juice in a bottle?

**Comment by KillFurries** [comment]
Janitors should make no money on all days except April Fools

**Pull request merged**
