### PR TITLE
Normal Plasssssmamen Ssssspeech

### PR DESCRIPTION
**Pull request by SkowronX**
Ssstop it dammit.

### CODE REVIEW

**Comment by dylanstrategie** [comment]
But rolling "s" are so original, I swear guise

**Comment by ComicIronic** [comment]
Terrible.

**Comment by Intigracy** [comment]
Terrible.

**Comment by SkowronX** [comment]
Don't kick the plasmamen.

**Comment by Exxion** [comment]
I don't really have a problem with them having some kind of speech alteration, but I don't get the multiplication of the letter s. It just doesn't make sense. That is traditionally associated with lizards and snakes, which Plasmamen are very definitively not.

**Comment by Ephx1** [comment]
I had assumed it was simmering, like burning.

**Comment by clusterfack** [comment]
Clearly they should have their speech just interrupted by random screaming

**Comment by Cyadox** [comment]
If not remove it at least make the stutter easier to read. Half the line just being full of sssssss is just annoying as sin.

**Comment by SangriaMonkey** [comment]
Wordfilters are dumb.

**Comment by SkowronX** [comment]
gronk

**Comment by clusterfack** [comment]
Up to the chicken

**Comment by Intigracy** [comment]
Alternatively you can replace ss with "thh" and s with "th".

The order matters, ss needs to be replaced first or you'll just end with with "thth"

**Comment by Exxion** [comment]
>sss
>thhth

We may need regex

**Comment by N3X15** [comment]
Would be something like `s+` to capture one or more s.

**Comment by Rei1226** [comment]
get rid of this stupid shit entirely

**Comment by Probe1** [comment]
can we do this already

**Comment by ihadtoregisterforthis** [comment]
img_20151016_085127

Plasmamen should have a debuff, and this one seems fine enough
Keep the sssssssss-s

**Pull request closed without merging**
