### PR TITLE
Gives CMO locker a surgeons switchtool

### PR DESCRIPTION
**Pull request by robosperg**
Adds a surgeons switchtool to CMO locker
:cl:
 * rscadd: CMO locker now has a surgeons switchtool

### CODE REVIEW

**Comment by robosperg** [comment]
upboat/downboat this comment for interest in giving them a mobile operating table as well

**Comment by SonixApache** [comment]
powercreep

**Comment by robosperg** [comment]
Personally I think its disgusting the RD already has a better version of this

**Comment by SonixApache** [comment]
yes, hence powercreep - textbook powercreep

**Pull request merged**
