### PR TITLE
Medbots treat brute with tricord again to stop overdoses

### PR DESCRIPTION
**Pull request by ghost**
Back in https://github.com/d3athrow/vgstation13/pull/9275 medbots gained the ability to dispense a specialized chem based on the medkit it was made out of. So an O2 kit medbot would treat oxyloss with Dexalin instead of Tricord. Tox with Antitox. Fire with kelotane. Regular with bicard. The problem with that being that Bicard OD's at 30u and medbots inject with 15u at default making it easy to OD yourself if all 3 of the robotics medbots or a cluster of medbots from other sources get made and are close enough to inject someone all at once for brute damage. PR changes that back to Tricord.

Tested locally. Sandbox spawned medbots worked fine. Built 3 in robotics and they injected tricord for brute successfully as well.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Or instead of giving medibots cure-alls make them check if an injection would cause an OD and not inject if it does?

**Comment by ghost** [comment]
They had Tricord for years and the other brute healers are DD, nutriment, milk, tomato juice, cryox, clonex, rezadone, nanobots, off the top of my head. If you got advice on how to get 1 out of 3 medbots on the same tile to switch to tricord after two finish their injection when they all started at the same time I'm all ears.

**Comment by ghost** [comment]
Have a check for their amount before, then have a do_after, then check again, then inject either tricord or bicaridine

**Comment by Iamgoofball** [comment]
Rip off what we did at tg. Right before injection check the amount of bicard in the patient, if the amount plus injection amount is above OD threshold, don't inject. Simple as that.

**Comment by Iamgoofball** [comment]
Since BYOND still processes the medibots in order, it'll ensure no ODs.

**Comment by ghost** [comment]
I'll go look at the sleeper stuff for reagent checking then take a whack at it.

**Comment by Shadowmech88** [comment]
You could make a special medbot-only medicine that is a child of bicard, but with the `overdose` var set to 0.

**Comment by Iamgoofball** [comment]
That's a dumb way to do it

**Comment by Intigracy** [comment]
So, what's the plan with this?

**Comment by gbasood** [comment]
Would rather that medibots just not overdose people by figuring out that a nerd has too much of a chem to give them a safe dose.

**Comment by ComicIronic** [comment]
The simplest fix is to just put a an assess_patient after the wait - the proc already checks to see if the patient has meds in them in the first place, it just doesn't check again after waiting. Since this is not a  good solution: closing.

**Comment by Shadowmech88** [comment]
It might be a good idea to put this problem in an issue so that people don't forget it exists.

**Pull request closed without merging**
