### PR TITLE
fixes layering issues with pre-mapped tape

### LINKED ISSUE #26232: Engineering Tape Layering
Engineering tape seems to layer under doors now which makes the doors not opening very confusing

Happened on Roid (telescience)

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #26232

### CODE REVIEW

**Comment by DamianX** [comment]
???

**Comment by ShiftyRail** [comment]
Pre-mapped tape isn't layered correctly. It shows up under the airlocks it is supposed to cover. This fixes that by setting the correct layer on initialisation
I did test it

**Comment by DamianX** [comment]
Is there ever a situation in which the tape item doesn't need to be layered above doors?
Sounds to me like this should just be a var set on the tape item itself.

**Comment by ShiftyRail** [comment]
Fair point.

**Pull request merged**
