### PR TITLE
NTSL Stuff.

### PR DESCRIPTION
**Pull request by PJB3005**
I've decided to stop working on this, sadly, what I did do should be mergable.
- [x] Move **all** of NTSL to absolute pathing.
- [x] Move all the datums used to subtypes of `/datum`.
- [x] ~~Fix some NTSL bugs.~~
  - [x] `/` operator is broken.
  - [x] ~~HTML classes get fucked by NTSL.~~ @N3X15 said he was gonna fix this.
  - [x] `+=` operator did not work for lists.
  - [x] ~~`>` or `<` gets stripped out.~~
  - [x] Replace sometimes malfunctioned.
- [x] ~~Give the TCS IDE a **really fucking great IDE**, using [CodeMirror](http://codemirror.net/).~~
- [x] Add a **ton** more default functions.
- [x] ~~View server memory.~~

### CODE REVIEW

**Comment by Probe1** [comment]
:+1:

**Comment by PJB3005** [comment]
Because I don't feel like working on this anymore, I've decided to make this mergable and leave other stuff for later (or never...)

I'm working on better handling of operator type mismatches, once that's done (if it's even practical) I'll deem this as done.

**Comment by PJB3005** [comment]
Alright, done. Technically.

**Comment by N3X15** [comment]
Conflicts

**Pull request merged**
