### PR TITLE
Engine Access Split: Major / Minor. + Mechanic Promotion without Pay Increase.

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Replaces the access level "engine equipment" with "minor engines" and turns normal engine access into "major engines". Then adjusts a bunch of access requirements accordingly.

**What**

Effectively this splits engineering access into 2 tiers: minor and major. Minor access includes generally moving around engineering, rigsuits, and most importantly "minor engines". Major access is almost exclusively used for "major engines".
Minor here is for engines that don't generally end the round if they go sour/are seen as simple. So things like the AME.
Major is the opposite, so: supermatter, singulo, RUST. 

This changes access requirements for both doors and cargo crates relevant to this. For example, minor access lets you get into the AME. It also lets you order/open the shielding equipment for a singulo but not the singulo generator/PA parts. You now no longer need major (previously just "engine") access for ordered AME parts however, just minor access.

**Why**

Mechanics have been given minor engine access but not major engine access. This means it is now officially their job to set up the AME or solars, but not the shard or singulo. Retroactively makes all the wrong people right regarding engines being mechanic's job, and also makes all the right people still right regarding access = job, wow! 

**Door stuck**

This was done with a bit of haste. I did double check both the code and via mapping tools but it's likely I either missed something or mixed something up. A lot of airlocks aren't labeled well at all. Please report any issues with this. 

:cl:
 * tweak: Engine access now split into minor and major
 * tweak: Mechanics have been given minor engine access, but not major

### CODE REVIEW

**Comment by jwhitak** [comment]
Grudgecode, but good grudgecode. This leads the way to more nuance in access levels. HoP can now let the cargo techs or clown have basic engine access if we need power without letting them have "permission" to set up the shardularity engine.

**Comment by Optimism333** [comment]
Seems a better compromise than just granting them full access to all the engine equipment, since it keeps them somewhat distinct from proper engineers.

**Comment by GreatBigFailure** [comment]
>Grudgecode

Recent events definitely pushed me to put in the effort but it's something I thought was needed for a long time. I just thought it would be more work than this was so I never did it. So like, 50 50

**Comment by djkramer123** [comment]
good change

**Comment by RonPaul08** [comment]
Unless we add a separate door that would enable someone to get to the AME hall without going through engi, why deliniate when anyone with minor engine access can proceed to get glubbs from engineering foyer and now has AA

**Comment by west3436** [comment]
A much better implementation than what I proposed

**Comment by GreatBigFailure** [comment]
@RonPaul08 Please stop making me rant about how glubbs != access.

If you do not agree with this PR being merged: https://github.com/vgstation-coders/vgstation13/pull/31932
Then you do not agree that glubbs should effect how access interacts with what someone's job is.

**Comment by Optimism333** [comment]
> Unless we add a separate door that would enable someone to get to the AME hall without going through engi, why deliniate when anyone with minor engine access can proceed to get glubbs from engineering foyer and now has AA

If the capability to hack is equivalent to access, anyone with a multitool who knows the test wire has all access. Not even glubbs required.

But anyways, the point of this pr is to distinguish major and minor access requirements for engines, and by extension also carve out a role for mechanics to supply the station with some power while still remaining distinct from dedicated engineers.

**Comment by SonixApache** [comment]
this is just #31927 but with added "i don't want any responsibility"

**Comment by GreatBigFailure** [comment]
>Give mechanics no engine access
>Sonix complains mechanics don't make engines
>Give mechanics full engine access
>Sonix goes 5 minutes back in time to be the first one to screech about it
>Give mechanics some engine access but not the really special ones
>Sonix complains it's not full engine access

**Comment by west3436** [comment]
Sonix will just keep bitching until his (long reverted, shitty) PR to move Mechanics to Science is brought back

**Comment by Eneocho** [comment]
Does TEG qualify as minor or mayor engine? For most intents and purposes it is a very minor engine (literally wrench 5 cans and press 6 buttons) unless you go through the added trouble of making it self sustaining.
R-UST is only normally available on Deff, kinda weird to qualify it as a mayor engine. It might be, but making one (not counting the half-built deff one) is a roundlong project and WAY outside the scope of non-engineers making fast power to keep a round going. I'd keep the rust crates on minor, since it depends on TEG and noone would make one casually as emergency power.

**Comment by GreatBigFailure** [comment]
@Eneocho You're mixing it up. Minor engine access is for simple/less dangerous engines. So AME, TEG, solars. Major engines are the larger projects/dangerous ones, shard, singulo, RUST.

**Comment by Kurfursten** [comment]
conflicts

**Comment by GreatBigFailure** [comment]
> conflicts

I'm waiting for kanef to be super duper mega sure he fixed his PDA stuff before I fix them. You know I want to minimize my interactions with git.

**Comment by KingofHONK** [comment]
Make sure to include this into the wiki as well.

**Comment by Eneocho** [comment]
> Make sure to include this into the wiki as well.

I'll update the wiki as soon as it gets merged.

**Comment by WindowsErrors** [comment]
> as soon as it gets merged.

**Comment by DamianX** [comment]
fix the conflicts

**Comment by Eneocho** [comment]
Is this dead?

**Comment by GreatBigFailure** [comment]
I forgot I made this. I'll get back to it once I'm done my break.

**Comment by Eneocho** [comment]
@GreatBigFailure any news on this?

**Pull request closed without merging**
