### PR TITLE
Added 5 new paintings

### PR DESCRIPTION
**Pull request by JMWTurner**
And now for something completely different

paintings

I'd like to honor my namesake. Good job if you can identify some of them from this picture alone.

### CODE REVIEW

**Comment by SkowronX** [comment]
Resized images of paintings?

**Comment by JMWTurner** [comment]
Yep. Is that an issue? I can approximately redraw them if needed.

**Comment by SkowronX** [comment]
It's fine, just be careful of using copyrighted pictures.

**Comment by ghost** [comment]
This would be better in 64x64

**Comment by GenericGoose** [comment]
almost as classy as clown spacing a mime
do you have a painting of that btw?

**Comment by unid15** [comment]
don't joke about that @DrCelt

**Comment by clusterfack** [comment]
Yes it'll be fun to resize them when 64x64 returns

**Comment by JMWTurner** [comment]
I'll gladly do it when the time comes.

**Pull request merged**
