### PR TITLE
*TERMINATE* arrest setting.

### PR DESCRIPTION
**Pull request by ShiftyRail**
For when `*Arrest*` just doesn't convey the message well enough.
[content] [tweak] and obligatory [powercreep]

It's meant to be used against really armed and really dangerous foes. An Asimov AI or a borg spotting such a setting can reasonably believe the person who put them wishes to kill the suspect, and should act accordingly.

Beepskies and ED's will arrest and cuff as usual, but report the code "66" when doing so, signaling that the lad they arrested is top priority.

:cl:
- tweak: "Added the *High Threat* setting to the HuD list. It is meant to be used against foes that are armed and against which you should _really_ tase first, and ask questions later. Sprites courtesy of @otatoh."

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
It's treason then
Not sure how italics are going to parse into the changelog

**Comment by ShiftyRail** [comment]
I swear to God it compiled on my machine

**Comment by Kurfursten** [comment]
Here's how I see this going down

>Cultist kills 1 sec officer
>Uses shades to set random non-cultists to Terminate
>Security eguns them down "icon was T that means I can lethal them!!!!"

**Comment by ShiftyRail** [comment]
Maybe it could be a setting that's only selectable from the computers at brig ?

**Comment by KingofHONK** [comment]
the absolute state of sec play...

**Comment by SonixApache** [comment]
Would be useful to last-second [T] someone with the HUDs before the rads / succ takes your life.

**Comment by Hoshi-chan** [comment]
Add logging to sec records, so that you can see who set a status or added a note.

Also add a way to modify sec record logging, requiring a swipe of a valid ID (not just coming up to a console that was left logged in) or emagging the console, to put the frame on someone or otherwise clean up your logs when you're done.

**Comment by Kurfursten** [comment]
@SonixApache There is just no way it will work like that in functional play. There will never be an icon you can set with examine that lets you valid someone because of the situation I described above. In practice

>John Scientist is set to T, anyone know who set him to that?
>There's no records for this guy
>Search was clean should I let him go?
>Okay I'm gonna let him go

**Comment by Hoshi-chan** [comment]
What if it required code red to set?

**Comment by Kurfursten** [comment]
>Code Red is when officers are most likely to be killed
>Code Red is also when officers are least likely to take the time to follow up on an arrest status and carefully determine if it's accurate or phony
>Cultists kill 1 officer and set all the non cultist civilians to VALIDATE

The amount of hoops you would have to add to this to make it anything functional would be obscene.

Automatically stamping arrest records in general with the assigner's name (and possibly a timestamp) wouldn't be bad though. And if you want to have different arrest levels, Arrest-Minor and Arrest-Major could be a thing. I don't think a VALIDS button will ever work though.

**Comment by Blithering** [comment]
Maybe it could be linked to the newscaster wanted issue system somehow? Also I'd prefer if it was marking people as 'high threat', rather than a straight up murder order.

**Comment by Kurfursten** [comment]
Sec newscasters can do wanted issues, no one uses them

**Comment by Caboozles** [comment]
Just have it register who set this on the HUD or make it a warden thing.

**Comment by bathosbathtime** [comment]
You call it a problem but all I see is counter-play and subterfuge.  I like this how it is.

**Comment by Kurfursten** [comment]
What I'm saying is there are basically 2 ways this will go

>Admins give the go ahead to valid anyone with the T tag

Whoever labels people as T needs to be logged since they'll be responsible for the killing

>T tag is a meaningless tag or a misnamed "arrest but elevated urgency"

Can't lethal on sight because you still have to stun, investigate whether the T tag was justified, etc. Don't call it Terminate because it will make people think they're allowed to shoot people with this icon

**Comment by SonixApache** [comment]
>Admins give the go ahead to valid anyone with the T tag

just adhere to how it is now; whoever shoots is to be held responsible, but whoever set them to T is also to be held responsible.

**Comment by Kurfursten** [comment]
If what you're saying is "there are times when you can't terminate someone with the terminate tag and you should probably always tase and investigate" the name needs changing

**Comment by ShiftyRail** [comment]
An alternative would be to make the tag setting only available at the sec records, and requiring a swipe of an HoS-level id to activate it, adding an irremovable entry to the records.

**Comment by SonixApache** [comment]
Nah, that's not what I'm saying; I'm saying "Use your head".
If there's been no threat to anyone, and you have no idea why someone would be set to kill-on-sight (all of your team is doing fine, no people disappearing or any other weird reports, etc) you probably shouldn't shoot them. If any of those aren't the case, shoot, ask questions when the brain's in an MMI.
Having a [shoot this fucker] tag would be useful, and it'd be as easy to abuse as the [arrest this fucker] tag

**Comment by Blithering** [comment]
I still think [this fuckers armed] would be a more useful tag to be able to throw on people to [shoot this fucker]

**Comment by Kurfursten** [comment]
Blithering has it right I think.

**Comment by Dacendeth** [comment]
Now all we need is a "chloral and disposal" setting for medhuds.

**Comment by eplgr** [comment]
Awful PR that promotes validhunting. Simple as that.

**Comment by ShiftyRail** [comment]
This changes absolutely nothing in most applications.
A "T" setting would be used only for things like confirmed cultists (which you theoratically mark as such in the records, so you would already kill on sight) or a memelord with a radgun depopulating the station. Which already you would set to wanted and add a note for it.

**Comment by SonixApache** [comment]
@Blithering A vampire isn't necessarily armed. A corpse that was destroyed also isn't necessarily armed.

@ShiftyRail make sure to update the wiki (and maybe change the changelog to be less... aggressive?)

**Comment by Blithering** [comment]
Although vampires, cultists and the like are confirmed in character knowledge, I still don't think Nanotrasen systems should accommodate for the more supernatural elements of life on SS13

**Comment by SonixApache** [comment]
I thought about it for a bit.
It's a setting that shows to security personnel (and anyone checking the records) that an individual is so dangerous that they cannot be arrested or perhaps even approached safely - that they should be shot on sight, with lethals, to prevent any more damage or casualties.
I do feel that "terminate" rather than "beware" or some other lesser warning term is the most appropriate, though a bit hitlery.

As is, I've been using the notes to indicate people are armed and dangerous and comments to indicate exactly *how* armed and dangerous, but a lot of officers don't even read the notes / comments while engaging. As such, having the simple option to choose between [tase this fucker and bring him in] and [put slugs in head] would streamline the process greatly for the more simpleminded redshirts.

Still think you should change the changelog to be less aggressive.

**Comment by ShiftyRail** [comment]
Changed the wording a bit.
*High Threat* is maybe less "kill on sight". Maybe.

**Pull request merged**
