### PR TITLE
Species that do not have blood cannot spawn as round-start vampire

### PR DESCRIPTION
**Pull request by ghost**
- suggested by someone in the discord

my apologies to the lads doing antag datums, I'll make a PR to your branch with the same change if this goes through

### CODE REVIEW

**Comment by ghost** [comment]
wow @TheFriggenSawbones -1'd the PR holy heck I wasn't convinced it should be merged before but now I am

**Comment by gbasood** [comment]
but why

**Comment by RealestEstate** [comment]
wouldn't someone lacking in blood desire it most?

**Comment by ghost** [comment]
@RealestEstate huh that is a good point

**Comment by MadmanMartian** [comment]
pls stop making changes to antag code!

**Comment by ghost** [comment]
ok

**Pull request closed without merging**
