### PR TITLE
Even more canned heat

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Replaces the canned heat intro with the full song. Separate from #36609 cause that's strictly fix and this is more shitpost.
## Why it's good
The original file 7 seconds long file is bigger than the full song, so why not just _use_ the full song? 
:cl:
 * tweak: Canned heat cans will now play the full song.

### CODE REVIEW

**Comment by CrazyAmphibian** [comment]
having the whole song play seems a bit... overbearing?

**Comment by Eneocho** [comment]
sounds like you need some canned heat on your heels tonight

**Comment by Theophrastus1** [comment]
now if we can add virtual insanity to the Malf AI juke...

**Comment by DeityLink** [comment]
THAT WAS A JOKE

**Comment by Eneocho** [comment]
> THAT WAS A JOKE

I'm very much aware that it was, however, consider the following:
keepgoing

**Comment by SonixApache** [comment]
\>+4 mb
bruh

**Comment by SECBATON-GRIFFON** [comment]
meme PR to end all meme PRs

**Comment by Eneocho** [comment]
>+4 mb bruh

even funnier when you consider that deity's 7 seconds canned heat OGG file was BIGGER than the full song added by this PR

**Comment by jwhitak** [comment]
Having a 5 minute song play as a sound effect because the tator pulled the funny fire item out is gonna be a nope from me. Sorry.

**Comment by Eneocho** [comment]
looks like you didn't get enough canned heat on your heels, sad.

**Pull request closed without merging**
