### PR TITLE
Phenol properly reacts with plasticide for making plastic.

### PR DESCRIPTION
**Pull request by GoodG1448**
I made a plastellium plant that had Phenol and Plasticide, it didn't react to make plastic even when grinded. Phenol wasn't reacting with the plasticide since there was no reaction.

Copypasted the the recipe for plastic and replaced pacid with phenol. Not sure if it will work.

:cl:

rscadd: Phenol-Plasticide reaction now works

### CODE REVIEW

**Review by jknpj — DISMISSED** [review]
It's literally a feature. If you really want to do this use #20652 as example. We already have the PACIDS list, there's no need to make another reaction.

**Comment by Exxion** [comment]
No, it's a bug related to how reagent lists work. Either way though, this isn't the proper fix.

**Comment by jknpj** [comment]
I could swear it was fixed.

**Comment by Exxion** [comment]
You can see right above the changed lines here that it already uses the `PACIDS` list, so no

**Comment by GoodG1448** [comment]
If you want, go ahead and fix it for me because I have no idea how to read code other than copypasting things that are already there and replacing few things. Can't make it work because it seems that the reagent list is bugged.

EDIT: Oh wait, I'm fucking blind. It was PACIDS not PACID, I guess it is fixed now.
EDIT of the EDIT: No wait, it didn't even work with requirements set to PACIDS. Fix it for me.

**Comment by Exxion** [comment]
If memory serves, you can bandaid it by switching the order of the ingredients

**Pull request merged**
