### PR TITLE
Fixes a runtime with slime extracts

### LINKED ISSUE #9672: Slime reaction runtime
I can't find the bicon call someone else do this

``` DM
10:35:20 Runtime detected
Cannot read "adamantine slime extract".icon at browserOutput.dm:205
 proc name: bicon (/proc/bicon)
  source file: browserOutput.dm,205
  usr: Robot Man (/mob/living/carbon/human)
  src: null
  usr.loc: the floor (297,194,1) (/turf/simulated/floor)
  call stack:
bicon("adamantine slime extract")
/datum/reagents (/datum/reagents): handle reactions()
/datum/reagents (/datum/reagents): add reagent("plasma", 5, null)
/datum/reagents (/datum/reagents): trans to(the adamantine slime extract (/obj/item/slime_extract/adamantine), 5, 1, 1)
the syringe (/obj/item/weapon/reagent_containers/syringe): handle inject(the adamantine slime extract (/obj/item/slime_extract/adamantine), Robot Man (/mob/living/carbon/human))
the syringe (/obj/item/weapon/reagent_containers/syringe): afterattack(the adamantine slime extract (/obj/item/slime_extract/adamantine), Robot Man (/mob/living/carbon/human), 1, "icon-x=19;icon-y=13;left=1;scr...")
Robot Man (/mob/living/carbon/human): ClickOn(the adamantine slime extract (/obj/item/slime_extract/adamantine), "icon-x=19;icon-y=13;left=1;scr...")
the adamantine slime extract (/obj/item/slime_extract/adamantine): Click(null, "mapwindow.map", "icon-x=19;icon-y=13;left=1;scr...")

runtime error: Cannot read "adamantine slime extract".icon
proc name: bicon (/proc/bicon)
  source file: browserOutput.dm,205
  usr: Robot Man (/mob/living/carbon/human)
  src: null
  usr.loc: the floor (297,194,1) (/turf/simulated/floor)
  call stack:
bicon("adamantine slime extract")
/datum/reagents (/datum/reagents): handle reactions()
/datum/reagents (/datum/reagents): add reagent("plasma", 5, null)
/datum/reagents (/datum/reagents): trans to(the adamantine slime extract (/obj/item/slime_extract/adamantine), 5, 1, 1)
the syringe (/obj/item/weapon/reagent_containers/syringe): handle inject(the adamantine slime extract (/obj/item/slime_extract/adamantine), Robot Man (/mob/living/carbon/human))
the syringe (/obj/item/weapon/reagent_containers/syringe): afterattack(the adamantine slime extract (/obj/item/slime_extract/adamantine), Robot Man (/mob/living/carbon/human), 1, "icon-x=19;icon-y=13;left=1;scr...")
Robot Man (/mob/living/carbon/human): ClickOn(the adamantine slime extract (/obj/item/slime_extract/adamantine), "icon-x=19;icon-y=13;left=1;scr...")
the adamantine slime extract (/obj/item/slime_extract/adamantine): Click(null, "mapwindow.map", "icon-x=19;icon-y=13;left=1;scr...")
```

### PR DESCRIPTION
**Pull request by Exxion**
Fixes #9672 

Guaranteed tested

### CODE REVIEW

**Comment by Exxion** [comment]
Fuck off, Travis, it does compile

**Comment by PJB3005** [comment]
Alright build restarted.

**Comment by Exxion** [comment]
Thanks
It said no language specified in the details for some reason

Wait it always says that
So what broke?

**Comment by gbasood** [comment]
Sometimes the BYOND binaries go missing between build tasks for no apparent reason and it doesn't re-build them until a new task starts

**Comment by PJB3005** [comment]
I didn't a actually bother checking but it was probably an apt server going down for a second.

**Pull request merged**
