### PR TITLE
Quality pass on the recent changes to Boxstation maints (mainly Arrivals maintenance)

### PR DESCRIPTION
**Pull request by ghost**
Yep, it's that time again, gotta polish Box up a little. Having more complex Maintenance is cool and all but having it be quality-passed is better. Detailed changelog : 

Arrivals Maintenance:

* Removed most of the light bulbs, Maintenance shouldn't be lit like this. Some exceptional lightbulbs like the ones in specific rooms (gym, kitchen, marble room) and in front of Solars and Ghetto Bar were maintained
* Re-added a maintenance EVA access between Solars and Ghetto Bar. I know there's like dozens of those in Arrivals, but having stealthy EVA accesses that won't trip every single air alarm on station is important for antagonists. Ghetto Bar was squeezed east to make it fit
* Cleaned up the Ghetto Bar a little. APC is now wired correctly, there's now a light ready in the back room. Right side window now points to space, it's still partially destroyed but a local Atmos main covered it up waiting for repairs. Privacy Shutters now genuinely give you full privacy by covering all windows (also good when a space carp inevitably breaches it)
* Rage Cage and the VIP booth was heavily cleaned up. Removed all the random clutter inside the arena, VIP booth was made fancier and no longer has airlocks if someone wants to decon it for fun projects
* Removed the movement blockers under the Toilet. It's not fun having to decon garbage to be able to make a full loop around Maintenance
* A lot of items, notably stuff like randumb girders were removed to make it way easier to maneuver around Maintenance without having to dodge and weave like an obstacle course or maniacally wrenching everything. Detail is fine and all but you should be able to move through cleanly through if that's all you want to do
* The upper maintenance hallway that went to Security hallway was culled to restore Ghetto Bar's right vista to space, and the observation window under Detective's Office. This restores the infamous breach point into Security Hallway for dastardly Traitors, and it just looks nice. The old path was heavily redundant when you could enter like 10 tiles away and loop around the marble room
* Ghetto Shelter now has tacticool black tiling and the window bay is no longer obscured at roundstart. You can barricade it if needed with an added nearby barricade kit. External access airlock was replaced into a maintenaince airlock with a firedoor and a linked fire alarm for your atmos needs
* Ghetto Gym treadmill generators are actually linked up to the grid now for your VERY desperate power needs
* Moved the APC to a more central location. Heavily culled redundant wiring and added a redundant distribution loop going through the maintenance towards E.V.A. Removed the vent in the gym because gheto maintenance rooms like these shouldn't have ventilation

Further changes to other Maintenances:

* Engineering Maintenance Disposals was moved a bit to restore the two-tile wide E.V.A access, to make it easier to use for enterprising team antagonists (aka basically Nuke Cops). In the same maintenance, culled a grille that was blocking direct movement in a tunnel by Abandoned Office
* Some slight tweaks to Ghetto Xenobotany in Research Maintenance, mostly making the blockage one tile wide instead of two, and moved the locker that was in front of E.V.A access
* Tweaks to Chapel Maintenance. Removed rogue piping in Ghetto Theatre, tweaked the walls to align both Holodeck doors, made the radio room a full box again for the glory of radiation poisoning. Auxilliary Borg Station now has a shocked window like was intended years ago (wire knot was missing)
* Removed the vents and piping in Detective Maintenance. No natural air supply in Maintenance, ever

Overview of the new Arrivals maintenance in full: 
scrnshot1

:cl:
 * tweak: Boxstation map changes. Heavily reworked the new Arrivals northern maintenance. E.V.A maintenance access was worked back in between Solars and Ghetto Bar. Most of the lights were removed to stay in tune with other maintenances. A lot of clutter that got in the way of actually moving down maintenance was moved or culled (both this one and others). The ragecage no longer has 20 blockers including multiple view occluders inside it. Access to Security Hallway was removed in favor of re-adding the window bay
* tweak: Slight tweak to other maintenances on Boxstation to streamline movement, align some doors and generally make it -feel- nice. Also the Auxilliary Cyborg Charger window is now shocked, so, you know, don't space it hoping to get free insulated gloves, learn how to hack a fucking door

### CODE REVIEW

**Comment by jknpj** [comment]
REMOVE BOXING RING remove boxing ring you are worst deff. you are the deff idiot you are the deff smell.

**Comment by Riekland** [comment]
>Ghetto Shelter now has tacticool black tiling and the window bay is no longer obscured at roundstart. You can barricade it if needed with an added nearby barricade kit. External access airlock was replaced into a maintenaince airlock with a firedoor and a linked fire alarm for your atmos needs

I'm having a hard time figuring out what the ghetto shelter even is let alone where it is

**Comment by plosky1** [comment]
Nice changes, I support.

**Comment by plosky1** [comment]
Just check that the tinted windows in the now double-room area by art supply are actually tinted. If not I would recommend replacing those pieces of glass with wall so that the curtains actually do their job and block vision.

**Comment by Kurfursten** [comment]
I'd like to see the "ghetto shelter" renamed to "atmosphere shelter" or something since you're making it look nice now.

And make sure the new airlock has a reduced timer like an external one, that was the point of having it on there.

**Comment by Kurfursten** [comment]
Muh requests ree

**Pull request merged**
