### PR TITLE
Cyborg Bundle

### PR DESCRIPTION
**Pull request by Lokiamis**
This random syndicate bundle gives you a cyborg friend. 
-Pre-assembled cyborg endoskeleton (10k cell)
-Positronic brain
-Emag
-Flash
-Jetpack module
-Reset module
-Rename module
-Restart module

:cl: 
 * rscadd: Added cyborg bundle to the pool of random syndicate bundles

### CODE REVIEW

**Comment by Probe1** [comment]
This is the most unrobust bundle you could have possibly come up with.

I can't even lie about it.  Like holy shit just PDA a borg and tell it to come over and not to move or communicate.

**Comment by ghost** [comment]
>jetpack module

That only works on engi or mining borgs

**Comment by ghost** [comment]
>chance to get an overpowered murderbot that the crew is now aware of without any effort

**Comment by yclatious** [comment]
>5am
>suddenly get a urge to visit the github
>pr to get your own personal emagged borg for a fucking bundle

What the fuck is this pizza bomb tier shit, are the normal borgs and the AI not enough? Are all of your traitor tools so bad/ are you so devoid of any balls that you need to get your own personal borg bodyguard that inevitably comes with meta knowledge from being a possi to be a good antagonist? First that fucking god awfull bullshit nuke ops bundle pr and now this, cant say I didnt call for the slope because by fuck, I did, I just hoped I was wrong.

**Comment by AutismSpider** [comment]
nigger this should be nukes op thing only for 20 or more TC for red and black ops borg.

**Comment by yclatious** [comment]
>Nuke ops
>Wanting a unstunable, zas and heat imune taser/laser slinging loyal borg to save the asses of every single ops out there
Yeah, its a posibrain so its dependant on shit like observers but you dont give borgs to antags just like that, and much less combat borgs to the guys who are beyond well equiped too.

Did a shitter clown pass by, cause this is space lube slipery.

**Comment by AutismSpider** [comment]
@yclatious got one better for 40 TC they get mommi

**Comment by yclatious** [comment]
*buzz

**Comment by Yelier** [comment]
How about this:
-Emag
-Ebow
-Binary Encryption Key
-Handcuffs
-Flash
-Roburger
-MoMMI Spaghetti
-Cardborg Costume
A straight up free borg is kinda boring, and it's not really as gimmicky as most of the other bundles. While the shitty old viruses are shitty and old, I can confidently say at least the roburger will consistently work. Plus, none of it requires observers joining as posibrains, which can be a problem if it's the start of the round (which is basically when traitors would get a bundle).

**Comment by PJB3005** [comment]
What if we made a bundle that willingly transforms you into a emagged MoMMI with the laws to obey the syndicate and complete your former objectives?

**Comment by jakmak6** [comment]
>outright giving antags their own cyborg sex slave

no

**Comment by Aurx** [comment]
On one hand, I think this is a terrible idea just because "emagged borg" is so powerful.  Also because the posibrain can meta "Hey, dude who activated me is in maint and not the roboticist, he's a tator, better start typing up my radio call now" and rat the tator out the instant it's built.  

On the other hand, I absolutely love the idea of somebody fucking it up and getting arrested by their own borg, or being way too slow on the emagging and getting ratted out while they emagged the borg.  Those would be 10/10 butthurt ahelps.

**Comment by yclatious** [comment]
Funny ahelps are not worth shitty balancing and the issues with a personal murderbone borg aurx.

**Comment by jknpj** [comment]
Make the borg come with the syndicate module, onehuman'd AND with antimov as law 1 to 3

**Comment by Exxion** [comment]
>Onehuman Antimov

What, would you set your target as the one human?

**Comment by jknpj** [comment]
No, it would kill its master.

**Pull request closed without merging**
