### PR TITLE
adds NT USPs (and ammo) to ERT prep rooms

### LINKED ISSUE #16609: ERT could use a ballistic option
ERT currently spawn with eguns and advanced eguns as weapon choices, this leaves a bit of a problem in the event something EMPs them. 
I think it would be a good idea to put a rack of the currently unused .45 pistols in the ERT prep areas, as it would give them a ballistic option that's a midpoint between sec glocks and deathsquad's matebas, and give them more flexibility.

### PR DESCRIPTION
**Pull request by SonixApache**
adds 6 USPs to each prep room and double that in lethal mags
i wanted to add the fancy variant but it doesn't have an icon in the editor so i'm not sure if it has an icon at all and i cannot be assed to fix that right now
also both guns and magazines are kinda badly spread across the racks because i couldn't quickly figure out how to do that in a way that doesn't make me want to 🔫 
maybe should make magazine boxes at some point
pistols
resolves #16609

:cl:
 * rscadd: added NT USPs to ERT prep rooms

### CODE REVIEW

**Comment by SonixApache** [comment]
whoops missing area markers stand by for banic

**Comment by SonixApache** [comment]
banic resolved and double-checked
good to go

**Comment by PJB3005** [comment]
Conflicts, again.

**Comment by SonixApache** [comment]
god fucking damnit

**Comment by Blithering** [comment]
RIP

**Pull request closed without merging**
