### PR TITLE
Clown/wizard AI

### LINKED ISSUE #25707: [Suggestion] Clown AI
Add a 1/100 chance that if:

1. No players with AI preferred readied

2. Two or more players with Clown readied

Then, the clown will spawn in the AI chamber, with the AI Job title, with a camera console that lets them jump to players who speak over the radio, and open doors near that player with the console, with nothing to indicate to the crew that there is  just a clown in the AI Chamber. And a curtain they can open and close which, when closed, looks like one of the AI sprites, and a curtain that looks like the floor tiles to conceal the two extra consoles.

Edit:

Second thought I had: If there is no AI at round start and it's Wiz, spawn a special item for the Wiz that uses up some of his Spell selection to put him in the AI chamber , on the crew manifest, with the same conditions, for muh wizard of oz gimmick

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][honk]

## What this does
adds a 1 in 100 chance for a clown spawned in a round to become a "clown AI", provided there's at least 1 additional clown and no AIs.
moves them to the AI core, gives them an AI job title, a headset with all available channels to the AI, a borg helmet for extra voice authenticity, security cameras, a curtain that conceals themselves to show an AI core and the cameras to show a floor, and the ability to open doors through the console. the concealing curtain can be alt clicked to change the AI core icon state.
wizards can also invoke this by using the scroll of teleportation on the AI chamber if there is no active AIs, with an optional prompt for it. (but without the upgraded headset key) channeled spells work through it, and the new cardborg helmet counts as wizard garb. (can remove if this makes AI core wizard unfun)
admins can also call make_fake_ai() on any humanoid type mob to send them there like this.

Closes #25707.
## Why it's good
honk

## Changelog
:cl:
 * rscadd: Pay no attention to the person of honking behind that curtain in the AI core, on some very rare days.
 * rscadd: There is however, a very real wizard behind curtains in the AI core. And he's channeling spells.

### CODE REVIEW

**Comment by Servalfang** [comment]
Stupid and horrible. I like it.

**Comment by pedr69** [comment]
instead of giving them a spell you could also do door remotes i think doriangrey's working on them

**Comment by ErrorsWindows** [comment]
alright kanef, remember to make it an opt-in, i think that's why people didn't like the character setup role names

**Comment by SECBATON-GRIFFON** [comment]
> alright kanef, remember to make it an opt-in, i think that's why people didn't like the character setup role names

the wizard thing now has a prompt asking them if they want it for going into the core.

**Comment by Servalfang** [comment]
Also, what if you increased chances for the clown but also added a prompt. Don't want the clown to get forced into a situation, and they should get it more often if they do want it (2 clowns is already something we see what, once every 10 rounds?)

**Comment by ManopolisJones** [comment]
You call this Clown AI, but I just see this as the Wizard of Oz

**Comment by Eneocho** [comment]
It IS essentially a Wizard of Oz gimmick, but the original feature request called it Clown AI.

**Comment by githubuser4141** [comment]
The idea of a human operated AI is really cool! Imagine if we'd get console-controlled cyborgs and mechs that could be created in Robotics sometime? Like the BORIS module in /TG that lets AIs to control borgs, instead it's a human pushing buttons at a computer console.

**Comment by SECBATON-GRIFFON** [comment]
> The idea of a human operated AI is really cool! Imagine if we'd get console-controlled cyborgs and mechs that could be created in Robotics sometime? Like the BORIS module in /TG that lets AIs to control borgs, instead it's a human pushing buttons at a computer console.

i'd never be sure how well received the idea of taking a feature from TG is here. plus i remember some time ago pomf ported some weird walkable AI shells from some server ages ago and people didnt like it so it got removed

**Comment by Eneocho** [comment]
> > The idea of a human operated AI is really cool! Imagine if we'd get console-controlled cyborgs and mechs that could be created in Robotics sometime? Like the BORIS module in /TG that lets AIs to control borgs, instead it's a human pushing buttons at a computer console.
> 
> i'd never be sure how well received the idea of taking a feature from TG is here. plus i remember some time ago pomf ported some weird walkable AI shells from some server ages ago and people didnt like it so it got removed

As far as I know the shells got removed cause they were broken something fierce rather than people disliking it.

**Comment by Exxion** [comment]
Shells were removed by Pomf because he (correctly) didn't like them. They were also very broken, but that wasn't the main reason

**Comment by Eneocho** [comment]
Well, Pomf disliking them does not equal people (in the overall playerbase sense) disliking them, but aight. I can't comment cause I didn't play during the 2 or so weeks it was merged.

**Comment by tinysaturn** [comment]
> The idea of a human operated AI is really cool! Imagine if we'd get console-controlled cyborgs and mechs that could be created in Robotics sometime? Like the BORIS module in /TG that lets AIs to control borgs, instead it's a human pushing buttons at a computer console.

There is a very old PR (https://github.com/vgstation-coders/vgstation13/pull/11371) that tried to add a traitor item for roboticist that would let you build RC cyborgs to mess around with
Would be interesting to see this revived

**Comment by Exxion** [comment]
> Well, Pomf disliking them does not equal people (in the overall playerbase sense) disliking them, but aight. I can't comment cause I didn't play during the 2 or so weeks it was merged.

It doesn't, but as the host and codebase owner, Pomf has the final say on all matters.

From a design perspective, shells are anti-interactive. They allow the AI to directly do things it would otherwise need to command a cyborg to do. They would be nice in deadpop, but I personally agree that it's better to not have them in order to encourage player interaction in this multiplayer game. The requirement to delegate certain tasks to cyborgs also helps to maintain the AI as handling the big picture instead of distracting them with even more individual tasks to accomplish.
Theoretically, they also make the already very powerful AI even more powerful, but I don't think this particular concern is that big a deal since they can already do whatever a shell would do by just ordering a cyborg to do it for them.

**Comment by ErrorsWindows** [comment]
> They allow the AI to directly do things it would otherwise need to command a cyborg to do.

yellow gloves allow me to directly do things I would otherwise need to request a security officer or a head of personnel to do, but you don't see anybody throwing a shit fit about those

**Comment by Exxion** [comment]
> yellow gloves allow me to directly do things I would otherwise need to request a security officer or a head of personnel to do, but you don't see anybody throwing a shit fit about those

Note that the words "request" and "order" are not the same

**Comment by githubuser4141** [comment]
> > The idea of a human operated AI is really cool! Imagine if we'd get console-controlled cyborgs and mechs that could be created in Robotics sometime? Like the BORIS module in /TG that lets AIs to control borgs, instead it's a human pushing buttons at a computer console.
> 
> There is a very old PR (#11371) that tried to add a traitor item for roboticist that would let you build RC cyborgs to mess around with Would be interesting to see this revived

this is probably thread derailment, but this'd be wicked if it was a RnD printable item and access was limited to what access was on your current ID.

**Comment by adacovsk** [comment]
Is the sound synth able to play over the radio? Maybe with a megaphone? Because it should. Also, the sound synth should be able to play the delta.ogg

**Comment by tinysaturn** [comment]
>  The idea of a human operated AI is really cool! Imagine if we'd get console-controlled cyborgs and mechs that could be 
> this is probably thread derailment, but this'd be wicked if it was a RnD printable item and access was limited to what access was on your current ID.

Terrible, imagine all the things soyentists already do but now they can also fuck with people with absolutely zero risk involved for them.
It is a great idea for a traitor idea, however.

**Comment by SonixApache** [comment]
🤡

**Comment by ConfusedCactus** [comment]
this is deeply retarded which is why i'm upvoting it

**Comment by SECBATON-GRIFFON** [comment]
can someone in the code look into why the remote clicking to open doors or use spells thing through computer isn't working

**Comment by ShiftyRail** [comment]
I wonder if more or this could've been offloaded to outfit datums but eh.

**Comment by Eneocho** [comment]
ITS HAPPENING

**Comment by pedr69** [comment]
pretty sure this lets humans roll midround malf
t. human that rolled midround malf

**Comment by Exxion** [comment]
Midround malf looks pretty foolproof, though roundstart malf looks less so
What job were you?

**Comment by pedr69** [comment]
scigger
image
i was on the roid too

**Comment by Exxion** [comment]
It clearly happened, but I have no idea how. The midround malf ruleset explicitly excludes anyone who is not an actual AI mob. Unless there's something weird with admin-forced rulesets specifically, the only way I can see that it could happen is if you were in the candidates list twice somehow.

**Comment by Exxion** [comment]
Oh, never mind, that particular button doesn't actually use the midround ruleset. I'm guessing the problem is in the logic it uses instead.

**Comment by Exxion** [comment]
It was not this PR. This button has apparently been broken since at least 2019. The same bug happened on February 23, 2019.
This button has only been pressed five times in the server's history, and every time has either failed or malfed a human.

**Pull request merged**
