### PR TITLE
The chameleon jumpsuit fits on fat people.

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
You used to not be able to wear the jumpsuit if you were fat. This fixes it.
Tested.
:cl:
 * tweak: Syndicate scientists have managed to make the chameleon jumpsuit a bit larger, making it fit on fat people.

### CODE REVIEW

**Review by Kurfursten — CHANGES_REQUESTED** [review]
The reason for this is that there are a lot of sprites you can switch to that are missing fat variants.

What you should do is have the list filter to only ONESIZEFITSALL options if the person choosing appearance is fat.

**Comment by SonixApache** [comment]
@Iamgoofball  fix it

**Comment by Kurfursten** [comment]
Won't this cause a fat person to look skinny if they select a suit with no fat variant?

**Comment by boy2mantwicethefam** [comment]
No, at worst it makes the suit show up in purple and black textures, but this also fixes problems for things such as clothes with different sprites depending on gender not showing up with their proper gender-correct variants

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
