### PR TITLE
Add a box of cable coils

### PR DESCRIPTION
**Pull request by Efruit**
Also check 'em.

:cl:
 * rscadd: Added a crate of boxes of cable coils to the Cargo catalog
 * rscadd: Added boxes of cable coils

### CODE REVIEW

**Comment by Intigracy** [comment]
Nice repeating digits.

**Comment by N3X15** [comment]
Looks good to me

**Comment by Efruit** [comment]
Still needs a few things before it's :heavy_check_mark:.
 - [x] ~~Inclusion in the Electrical Maintenance cargo crate~~ _Added in its own crate_
 - [ ] ~~A few placed on Box in Engineering/Engineering Storage~~
 - [ ] ~~_Maybe_ inclusion in electrical lockers.~~

**Comment by Probe1** [comment]
The electrical maint crates have 2 or 3 electrical toolboxes which have cables.  And there's map PRs up like crazy so if you plan on getting this done before your new job and new classes.. Engineering already has vends with a bunch of cables in them, plus electrical toolboxes, plus lots of loose cable rolls laying around.

**Comment by Efruit** [comment]
Would it be preferable to add it as its own crate, then?

**Comment by Probe1** [comment]
I mean.. SURE that makes more sense than ordering a vending refill pack just for cables.

**Comment by Lokiamis** [comment]
A spool would be cool

**Comment by SonixApache** [comment]
The RCL is a spool.

**Comment by clusterfack** [comment]
Cables would be better as an autolathe item than as a cargo shuttle pack

**Comment by Probe1** [comment]
What Clusterfack said.  Make it cost a decent bit too.

I can't get over the "You can order cables from two different crates specifically designed for cables" aspect.

Autolathe it.

**Comment by SonixApache** [comment]
Maybe just put the box of cable coils in the code for now and autolathe coils as a seperate PR.
Do maint loot spawners spawn cable coils? If so, could we just add the box to those?

**Comment by Intigracy** [comment]
I haven't seen anything happening with this in four months, if you're still working on it let me know and I'll re-open it.

**Comment by Exxion** [comment]
Quads are cursed

**Comment by SonixApache** [comment]
I'd like to add this box for completion's sake, really. Just not the cargo crate.

**Pull request closed without merging**
