### PR TITLE
[MDB IGNORE] Liquid reagent puddle system

### PR DESCRIPTION
**Pull request by ghost**
[tweak][system]
image

:cl:
 * rscadd: Liquid reagents splashed on a turf now make more realistic "puddles" than can spread to other turfs when reaching a reagent limit and react on them.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Very nice. So is it going to replace the current lubing, bloodstains, and welder fuel on the floor?
I could see this eventually morphing into a volumetric liquid system so there could be tanks of liquids, or hallways filled knee-deep with blood.

Maybe you could have an opacity variable for reagents so things like spilt milk would be opaque but water would look more transparent.

**Comment by ghost** [comment]
> Very nice. So is it going to replace the current lubing, bloodstains, and welder fuel on the floor? I could see this eventually morphing into a volumetric liquid system so there could be tanks of liquids, or hallways filled knee-deep with blood.
> 
> Maybe you could have an opacity variable for reagents so things like spilt milk would be opaque but water would look more transparent.

That's the intention. The PR is part 1 of that.

**Comment by Eneocho** [comment]
Can't wait for the stealthy pacid puddles.

**Comment by ghost** [comment]
> Can't wait for the stealthy pacid puddles.

You just reminded me to add mob reactions for crossing them, done. (usual permeability rules apply)

**Comment by Hinaichigo** [comment]
If you lay down in a puddle does it coat the rest of the body as well? Like say you mixed space lube and pacid and then people would slip into the acid and melt all their clothes and skin off or something.

**Comment by WindowsErrors** [comment]
can you dump a bunch of seperate reagents on the ground so they mix in the puddle like napalm

**Comment by Cartlord** [comment]
we are moving closer to gooncode

**Comment by Eneocho** [comment]
Do puddles work as a "container" for fluids? As in, if I made a puddle of water and poured potassium on top, would it go BOOM in relation to how much of each were poured? How large is the container if there is one? Is there reagent effect stacking? Could I make a puddle with keloderm, bicarisol and peptodylo and place injured people on a ghetto medical puddle? Can they dry out eventually or do they need to be scrubbed/cleaned by a janitor? Do they interact with the Wet/Dry vacuum?
Will your puddle system consider that some reagents are powdered (like plasma powder or diamond dust) and make reagent heaps (different icon)?

**Comment by kilozombie** [comment]
This is fuckin awesome

**Comment by WindowsErrors** [comment]
that's what i just asked yonoko

**Comment by ghost** [comment]
> Do puddles work as a "container" for fluids? As in, if I made a puddle of water and poured potassium on top, would it go BOOM in relation to how much of each were poured?

Potassium is a solid so this won't work for now, until I code a good way for solids to interact with turfs spilled on.

> How large is the container if there is one?

50 units for a puddle to not spread out over time, 1000 in total for "part 2" of this PR.

> Is there reagent effect stacking? Could I make a puddle with keloderm, bicarisol and peptodylo and place injured people on a ghetto medical puddle?

I don't think on_mob_life and reaction_mob are the same proc, but there should be for things with it.

> Can they dry out eventually or do they need to be scrubbed/cleaned by a janitor?

They have an evaporation rate, will try to make mops soak them up.

> Do they interact with the Wet/Dry vacuum?

Will work on that.

> Will your puddle system consider that some reagents are powdered (like plasma powder or diamond dust) and make reagent heaps (different icon)?

They're REAGENT_STATE_SOLID, so the engine already has it covered, will do those and the icon in another PR, or this one if I can.

**Comment by ghost** [comment]
> can you dump a bunch of seperate reagents on the ground so they mix in the puddle like napalm

Tested this and it works.

**Comment by NiftyRyanyan** [comment]
Great pr, can’t wait to flood the station with corn oil.

**Comment by adacovsk** [comment]
> > can you dump a bunch of seperate reagents on the ground so they mix in the puddle like napalm
> 
> Tested this and it works.

can you thermite through the floor? Actually, any interaction with heat would be really cool

**Comment by Eneocho** [comment]
> > > can you dump a bunch of seperate reagents on the ground so they mix in the puddle like napalm
> > 
> > 
> > Tested this and it works.
> 
> can you thermite through the floor? Actually, any interaction with heat would be really cool

A way to remove floors that doesn't use RCDs or explosives sounds incredibly based. make it happen blease.

**Comment by ghost** [comment]
> > > > can you dump a bunch of seperate reagents on the ground so they mix in the puddle like napalm
> > > 
> > > 
> > > Tested this and it works.
> > 
> > 
> > can you thermite through the floor? Actually, any interaction with heat would be really cool
> 
> A way to remove floors that doesn't use RCDs or explosives sounds incredibly based. make it happen blease.

Outside the scope of this PR, sorry

**Comment by godietxt80** [comment]
looks great, hope ur able to finish it

**Comment by ManopolisJones** [comment]
I'm suure it'll be great mechanically, but from the image posted it looks atrocious.

**Comment by Eneocho** [comment]
> > > > > can you dump a bunch of seperate reagents on the ground so they mix in the puddle like napalm
> > > > 
> > > > 
> > > > Tested this and it works.
> > > 
> > > 
> > > can you thermite through the floor? Actually, any interaction with heat would be really cool
> > 
> > 
> > A way to remove floors that doesn't use RCDs or explosives sounds incredibly based. make it happen blease.
> 
> Outside the scope of this PR, sorry

Ok, but please consider it some time. Lighting thermite on the floor. 
Our thermite is kinda weird now that I think about it. Ain't thermite a powder? Why does it make a splash sound when poured on a wall? Why can we pour it on a wall in the first place?

**Comment by Hinaichigo** [comment]
Is there diffusion and mixing between puddles that touch one another and have different concentrations of reagents?

**Comment by ghost** [comment]
> Is there diffusion and mixing between puddles that touch one another and have different concentrations of reagents?

It's shown in the image above.

**Comment by Kammerjunk** [comment]
this was perhaps a strange call

**Comment by Eneocho** [comment]
Prepare for unforeseen consequences.

**Comment by Cartlord** [comment]
This should never have been fucking merged.

**Pull request merged**
