### PR TITLE
OOP Solar

### PR DESCRIPTION
**Pull request by eswordthecat**
Changed
/obj/machinery/power/solar -> /obj/machinery/power/solar/pane
/obj/machinery/power/tracker -> /obj/machinery/power/solar/tracker
/obj/machinery/power/solar_control -> /obj/machinery/power/solar/control

Now
 /obj/machinery/power/solar (just a parent type now)
 /obj/machinery/power/solar/pane
 /obj/machinery/power/solar/pane/fake
 /obj/machinery/power/solar/tracker
 /obj/machinery/power/solar/control

Add them to a seperate folder and files.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Descriptions please.

**Comment by eswordthecat** [comment]
ping

**Comment by ComicIronic** [comment]
Gonna get conflicts with #2567.

**Comment by eswordthecat** [comment]
gasp

**Comment by clusterfack** [comment]
Oh you dun it now

**Comment by clusterfack** [comment]
#raginghard

**Pull request merged**
