### PR TITLE
Gardener job title

### PR DESCRIPTION
**Pull request by DeityLink**
gardener

Since Hydroponics can now produce cosmetic potted plants, I thought those who want to focus on embellishing the station deserved a new job title.

also fixed a bug related to randomized plants.

### CODE REVIEW

**Comment by SkowronX** [comment]
Thanks doc

**Comment by FudgePucker** [comment]
@DeityLink Hey can I get your opinion on an idea I posted in the thread last night?

Why don't we just semi-port fertilizers from goon, and have different fertilizers that slowly improve traits of plants?

That way you can have a less RNG way of improving potency and other things, but with a few draw backs like reducing other traits.

Maybe have a fertilizer that improves potency but reduces plant lifespan. Maybe have a fertilizer that is ammonia+radium that improves bio-luminescence at the expense of randomly reducing other traits.

Trying to improve potency for some plants sucks, one of the few sure fire ways to improve potency is using mutagen, but it has a 1/6 chance to effect other traits, and then a 1/2 chance to reduce it, then you have to do that roll 10 times to get to high potency, don't even attempt it if the plant mutates into another species because it will mutate before you can get potency up.

Goons system is 10000 times more simpler and easy to do, just pour some fertilizer into the tray and keep tending to the plants while it slowly improves (they also have a way to inject it directly into seeds to improve the stats, but lets not go too overboard here, we already have our own xenoboatany system, no need to add even more fancy imitating machines in the back.). With our system it is like winning the lottery if you improve potency high enough, with goons it just takes time before you can get over 420 potency (SMOKE DAT DANK SHEIT.).

One guy in the thread said it sounded like a good idea, I just want to get some feed back before making a formal feature request, and well you are the guy currently working on botany right now.

Whats your oppinion on it?

PS:Sorry for derailing, nice job on the outfit.:+1:

**Comment by DeityLink** [comment]
@FudgePucker I like the idea. Code it.

**Comment by dylanstrategie** [comment]
We could always port Bay's latest iteration of Botany, which is where we ported from in the first place. Apparently their stuff works very well now

**Comment by FudgePucker** [comment]
@DeityLink 
I thought at first it would be something simple like if there is this type of chemical in the tray, have a random chance to change this stat, just add in some new chemicals, some new chemical recipes, and add in new effects when it is in the tray. But after digging though the hydro. module, oh god, there is only three factors that fertiliser has, plant endurence, plant yeald, and plant mutation. Plant mutation is a rand chance of 10 diffrent effects.

I have no idea how I would pull that off, most complex thing I have done is add boards for the tea, booze, and soda desps, this proposed change would require rewriting parts of the datum for plants.

I guess I will look at TG and Bay's hydro. code.

**Pull request merged**
