### PR TITLE
Orderable and buildable portable SMES

### PR DESCRIPTION
**Pull request by Zth--**
I think they're cool. Tested.

🆑 
- rscadd: Portable SMES are now orderable from cargo and buildable from science

### CODE REVIEW

**Comment by Kurfursten** [comment]
While you're on this, you should fix the description of the portable SMES. The third letter is capitalized erroneously.

**Comment by Zth--** [comment]
Done

**Comment by ComicIronic** [comment]
What, no, it wasn't erroneous - the model name was a pun on "ion" and "IO".

**Comment by Probe1** [comment]
Rip programming joke

**Pull request merged**
