### PR TITLE
Create "Religion" module, general changes to Chaplain

### PR DESCRIPTION
**Pull request by ghost**
Change list copied verbatum from the changelog :
- All Chaplain-related code has been moved to the Religion module. This module will handle everything Chaplain-related, including main items, the job datum and the Pray verb
- Added a handful of new religions and "religions". Assigned dieties to all of them (can still be changed in post, but suggested by default)
- Suiciding with a Bible will lead to serious consequences
- Trying to use a Bible as a Vampire or a Cultist will quickly backfire. Trying to use it as anyone else than the Chaplain will have you simply bash people's heads in
- Helmets, hardhats and fedoras now protect you from the Bible's effects completely (even if they would be beneficial or adverse to you)
- Pray verb now shows the round's deity to allow the admin to see how he should answer IC. Note that only the Chaplain will see what deity is answering by default
- Bible healing is now 5 brute and 5 burn with 50 % chance, and bible brain damage is now 20 % chance of 5 brain damage. Mobs with 60 brain damage and over cannot be affected further by bibles
- Holy Water has a 10 % chance of unculting per mob tick and always damages Vampires seriously per mob tick when swallowed. Consumed at 5 units per tick. Vampires react much more aversely to holy water being sprayed on them
- Null rods hit have a 25 % chance of unculting and Bibles have 20 % chance, but both have to be handled by Chaplains unlike holy water. Due to the serious damage caused by both, randumb hitting is not recommended
- General typos and visible_message passes

This PR was more ambitious when it started and planned to add both Chaplain status buffs when in holy areas and a follower system allowing Chaplains to "hire" disciples that would carry limited buffs, immunity to Cultist and Vampiric conversion and limited abilities with Chaplain gear, but I realized I was neither competent with Life code nor Mind datums, so I settled for that

Discussions go below. Since this is a rather broad PR, there might have been oversights. Please warn me if you see anything weird or controversial

### CODE REVIEW

**Comment by gbasood** [comment]
>allowing Chaplains to "hire" disciples that would carry limited buffs, immunity to Cultist and Vampiric conversion and limited abilities with Chaplain gear
This would never end well.

**Comment by dylanstrategie** [comment]
I was trying to figure out how that would work, but my complete incompetence with the handling of mind datums just made me discard the idea altogether. At absolute worst, the base is here

**Comment by dylanstrategie** [comment]
I'm aware that the way I moved those files is quite unclean (copy-paste, deleted old, modified and included new), but I'm not sure as to how I can ACTUALLY reference the old files without having to redo everything in an even more complicated manner

I could always reference the old files with a comment at the top of each .dm if it's REALLY important

**Comment by PJB3005** [comment]
Does this include religious extremism?

**Comment by dylanstrategie** [comment]
Well, religious extremism can be RPed or something, but technically this PR is way less ambitious than planned

Too bad I'm terrible at working with Life() code and Mind datums

**Pull request closed without merging**
