### PR TITLE
Roboticist's Tears, the best soup you'll eat.

### PR DESCRIPTION
**Pull request by Eneocho**
Why should the clown be the only one crying? Roboticists deserve some suffering too.
[sprites]
resized robo tears
NOW ANIMATED (see above).
:cl:
 * rscadd: Roboticist's tears, made with a phazon sheet, a robotic head and water. An incredibly nutritious dish, perfect to eat in front of the roboticist.
 * tweak: Clown's tears now needs a bananium sheet instead of a bananium ore.
 * bugfix: Fixed mommi spaghetti icon where it would have a phantom plate during the sparkly part of the animation.

### CODE REVIEW

**Comment by pedr69** [comment]
>oops 4
checks still fail

based?

**Comment by Eneocho** [comment]
I typed the lines instead of copying then editing. I hate this shit so much it's unreal.

**Comment by ghost** [comment]
id like if you allowed ores in the recipe aswell

**Comment by ghost** [comment]
id like if you allowed ores in the recipe aswell

**Comment by Eneocho** [comment]
> id like if you allowed ores in the recipe aswell

Not sure how I'd do that besides just making a duplicate recipe with ore instead.

**Comment by Eneocho** [comment]
> At some point there should be a -tears for every job.

The idea of a -tears food is that some rare and highly coveted (but not unique) whatever for said job gets wasted to make food. Gas masks and insulos are easily acquirable for a greyshit, same as gold, silver, diamond and uranium for a miner or tasers and batons for a seccie. 
A greyshirt tears would be far better if it used the spare as an ingredient, for example.

**Comment by luigil101** [comment]
using the spare in food is Everyone's tears

**Comment by Eneocho** [comment]
An idea for Doctor's tears could be 10u Rezadone, 10u Peridaxon and a giant syringe,

**Comment by tuypo1** [comment]
Best I can come up with is wardens tears that uses the battering ram

**Comment by Kurfursten** [comment]
Wiki

**Comment by Eneocho** [comment]
On it.

**Comment by Eneocho** [comment]
Updated.

**Pull request merged**
