### PR TITLE
vox tails, except no wag emote and no code supporting tailwags

### PR DESCRIPTION
**Pull request by nervere**
closes #36030
## What this does
[copying from original PR]
Previously, Vox tails didn't even exist, they were baked into the chest sprite
Now they are a separate thing
Tails will now show on character preview [only tested with Vox]
Vox tails will now show in the North direction, previously there wasnt even a sprite for the north dir it was just blank
general code cleanup

## Why it's good
Vox having actually functional tails instead of a half-baked sprite is good. Weirdo tail wagging stuff is not.

## Changelog

:cl:
 * rscadd: Vox tails now work in all directions.

### CODE REVIEW

**Comment by Eneocho** [comment]
I don't mind the tail wag, as an extension of having a tail is being able to move it, but I gotta say that he dropped the ball hard by adding tail and tail wagging without also adding full mechanical reasons/effects/consquences for said tail to exist.

**Comment by nervere** [comment]
Half of a PR is marketing, after all.
I'm neutral on the matter, but several vox players telling me that they don't like the wagging stuff is all I needed to hear.

**Comment by Kurfursten** [comment]
> I don't mind the tail wag, as an extension of having a tail is being able to move it

I disagree, I have always seen the Voxtail as a long feathered protrusion of tailfeathers that served a vestigal purpose in flight, signalling, etc..
skeleton
A_hand-book_to_the_game-birds_(1895)_(14753202604)
08d69f03016296d531d80001e58f648e


I know my viewpoint is far from widespread and many people seem to have adopted the view that the tail is almost reptilian or something, but that's just how I've always imagined the tail.

**Comment by Eneocho** [comment]
> Half of a PR is marketing, after all. I'm neutral on the matter, but several vox players telling me that they don't like the wagging stuff is all I needed to hear.

ok you convinced me, i'll vote for the wagging since v*x players hate it

**Comment by 13spacemen** [comment]
I literally did the Vox tail wag BECAUSE /vg/ Vox players asked me to

**Comment by BomberBro** [comment]
/vg/ vox players are mutants

**Comment by Eneocho** [comment]
> I literally did the Vox tail wag BECAUSE /vg/ Vox players asked me to

I guess I'm not voting for the tail wag because v*x players like it?

**Comment by angryturnip** [comment]
> I literally did the Vox tail wag BECAUSE /vg/ Vox players asked me to

Perfect reason to not add it

**Comment by Pastamadness** [comment]
Fetish content

**Comment by DeityLink** [comment]
> I literally did the Vox tail wag BECAUSE /vg/ Vox players asked me to

many such cases.

**Comment by KingofHONK** [comment]
Can they be severed? They need to be severed.

**Comment by Eneocho** [comment]
> Can they be severed? They need to be severed.

Should make it so doing the ass removal surgery removes the tail if done on a vox, and the vox cannot sit because it no longer has a behind.

**Comment by hacker-on-steroids** [comment]
comparison pics? is there even any difference in the non-south dirs? what the hell does this pr do???

**Pull request merged**
