### PR TITLE
Imidazoline is like eye drops now

### PR DESCRIPTION
**Pull request by 9percents**
Spraying imidazoline on people's eyes now heals them completely, except for blindness disability.

:cl:
 * rscadd: Imidazoline can be used as eye drops now.

### CODE REVIEW

**Comment by Zth--** [comment]
With this code you can splash someone with a beaker and if his/her eyes are not protected then it'll heal them. Is this intended?

**Comment by 9percents** [comment]
it's a feature, because it does get in the eyes :^)

**Comment by MadmanMartian** [comment]
But droppering imi into the eyes transfers it to them..

Also why the massive buff from it taking 1 point of damage away every tick, to instant cure?

**Comment by 9percents** [comment]
massive buff because it gets to eyes directly and more quickly

I mostly saw the difference between dexalin and dexalin plus, which both treat oxygen damage, but instead of different reagent I thought of different method of application

plus, imidazoline already treats eye damage very quickly and people have 2-15 damage on their eyes at most

**Comment by Tokanova** [comment]
very cool change. would be fun to give medbay a pepper spray thing and have them fill it with imidazoline

**Comment by 9percents** [comment]
they already have a dropper for it though

**Comment by Kurfursten** [comment]
If *somehow* this becomes outrageous we can always scale back its effectiveness. Hard to imagine people will complain about fast eye fixing though.

**Pull request merged**
