### PR TITLE
Medsci Story

### LINKED ISSUE #24345: Snowmap Signs are Shit (SSS)
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
eed2edfacf52a2caf6b0cacfdcbdd50763840250

# Description
The science and medbay signs on the glass grilles point down but those places are up.
# Steps to Reproduce
bitch look at it
# What you Expected
sign = up
# What Actually Happened
sign != up

### LINKED ISSUE #24430: Chemistry needs a bunsen burner
(WEB REPORT BY: blitzikaze REMOTE: 206.221.180.138:7777)
# Revision
55c04da5a9a6e99aaca74dabcf0bb5e834778da7

# Description
no bunsen burner in chemistry
# Steps to Reproduce

# What you Expected

# What Actually Happened
wanted to make special snowflake chems but could not

### LINKED ISSUE #24884: Snaxi: Can't Reach Barsign
I keep forgetting to report this. It's blocked by directional windows on all sides.

### LINKED ISSUE #24886: Snaxi: Solars Lighting
They should not have dynamic lighting disabled

(also reminder to self about the rogue carpets in the wood area on medsci)

### LINKED ISSUE #24887: Snaxi: Lighting
One good large light could do the trick, it's too dark

Also, the pit should be part of the frozen core area so it doesn't get weird lighting

Courtroom wants a light for the viewing area

Small light in librarian backroom

Virology living space

Slide those janny closet lights up 1 tile each

One light would help in the hall between botany and the HOPbridge

One light by the piano in the bar

A light in the middle of engineering storage

One lamp on the south side of the north solars control room would be nice

### LINKED ISSUE #24888: Snaxi: Dorms Top Exit Not In Dorm Area
The light won't turn on because the area doesn't properly overlap the door.

### LINKED ISSUE #24892: [SNAXI] Air tanks in atmos
(WEB REPORT BY: nakerbott REMOTE: 206.221.180.138:7777)
# Revision
ef468500b8e9bb4d4997a363a33b34eabec3b028

# Description
All output (the vents) for the air tanks in atmos are disconnected from their respective supply control console

# Steps to Reproduce
go to atmos and check the supply control consoles

# What you Expected
the vents being connected to the supply consoles

# What Actually Happened
the vents were not connect to the supply consoles

### LINKED ISSUE #24903: Snaxi: Borer Problems
extension of #24750

scrubbers ain't connected
pipe line out of xenobio is missing a pipe under the r-wall

### LINKED ISSUE #24904: Snaxi: Perma missing biogenerator
Exactly what it says

### LINKED ISSUE #24906: Snaxi: Add Conveyor In Disposals
There needs to be another under the disposal outlet so that it will get anything that gets stuck on the chute

### LINKED ISSUE #24985: Snaxi dorms pod
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
20c4596f2fe3d377d15a37182df65a44d30f5000

# Description
Snaxi dorms pod is behind a red external airlock, which you need special access to open, making it unreachable

# Steps to Reproduce
Touch the door. Do it now

# What you Expected
Safety

# What Actually Happened
*buzz

### PR DESCRIPTION
**Pull request by Kurfursten**
This is a complete revamp of snaxi medsci. It touches everything. Here's as brief as possible:
* Demainted as promised - this was well received on engcargo
* Morgue less cramped
* Chemist gets new mixing room and bunsen burner
* Paramedic has new snowmobile bay with carts for corpse hunting, plus saint corgi mascot
* Medbay storage now has a proper room, plus MULE point
* Medbay entrance has the desired 2-and-2 instead of singleton 3-wide
* Mechanics can access telecoms
* Mech bay now openable to public and 2 chargers
* Roboticist across the hall but with spacious new digs
* Scientist receives missing lockers and new MULE point
* RD receives missing Lamarr, computers, and science telescreen - important stuff! Server room also nicer.

Fixes a bunch of unreported bugs, but also
fixes #24906
fixes #24904
fixes #24888
fixes #24884
fixes #24430
fixes #24345
fixes #24886
fixes #24887
fixes #24892
fixes #24903
fixes #24985

Untitled

Special thanks to medical mains Basil, Tobias Kunst, and Irradiation for providing consultation on medbay improvements

🆑 
* tweak: Snaxi medsci has been completely overhauled
* tweak: Snaxi has had many minor mapping bug fixes and quality of life improvements
* tweak: The Snaxi trade shuttle now docks at a closer location. The Centcomm ferry now gets its prime dock spot.

### CODE REVIEW

**Comment by N3X15** [comment]
fixes
fixes
fixes
fixes
fixes

**Comment by ghost** [comment]
All good with me, but I will get those map valids on Snaxi anyways. There's always an issue, until I do my pass (hopefully)

**Comment by Kurfursten** [comment]
Here are some feedbacks clownlion gave me directly that I think are worth writing down:
* Swap chem master and dispenser positions so you can use cauldrons
* Move disposal to back room so you can have more table space by the dispensers
* Move closet to a corner to prevent pushing

These are all good ideas I think, so I plan to do at least one more commit. Here are some other things I've been kicking around
* Make sure medbay front doors are actually separated onto separate id_tags for buttons (I do not remember doing this so they probably aren't)
* Push R&D out one wider. This is mostly aesthetic for smoothing with the rest of the wall but it's also free real estate for scientists.
* Put the robotics conveyors on a lever just in case someone wants to stop them

**Comment by Durgen** [comment]
why is it being demainted?

**Comment by Kurfursten** [comment]
People liked the idea of demainting Snaxi since there are so many places to hide in the dark snow anyway - cabins in the woods, caves, glaciers, those little gas switching station huts, etc. The idea was received favorably on EngCargo. Moreover, the maints before (on all stations) were narrow and felt a bit forced. Maint normally serves as a shortcut or alternate route, but on a planet surface you have as many routes as you want between two places, and each of the three stations is too small to need shortcuts inside the station. In fact, removing maint has *improved* flow. Imagine before you have several bodies near the ice caves like in this pic
image
The new hallway at the top left actually makes it much easier to get those bodies back inside and to medbay than the old side maint access few people could get through both doors. Having real entrances on each side treats seriously that people could approach from any angle.

I ended up writing more than I wanted and now it's a paragraph. Basically, this is a surface map, it should *feel* different to play on in many ways than a space station. Buildings on planets don't usually have those big crawl spaces for engineers.

**Comment by Durgen** [comment]
I see. This would probably be a lot of work, but I think it would be cool to have a fourth cold derelict substation. Might be a way to make up for people losing maint.

**Comment by Kurfursten** [comment]
There is one of those, as a holdover from old Taxi long ago. It's on the MoMMI z-level.

I believe adding more structures (notable suggestion is an art cabin) and geography (still planning that geyser hotzone and a surface-mine but both need code support) to explore is definitely on the menu. I have one more station to overhaul first, and likely the outpost as well.

**Comment by Probe1** [comment]
image
image

Oopsie doodle waste line using air supply pipes then a unary vent connected to waste.

**Comment by Kurfursten** [comment]
Thanks for catching it, you can leave me a full list here or PR map changes to this and I'll check it out in the morning

**Pull request merged**
