### PR TITLE
Fixes #9574 #9592 #9586

### LINKED ISSUE #9574: Telekenisis Electrocution
(WEB REPORT BY: bittervanilla REMOTE: 172.93.109.202:7777)

> Revision 5d36ff7414a6c30203b2edbc89a6ee3f6d24b1cc
> 
> When using a conductive item on electrified grilles (In this case, a knife) with a telegrab, the shock still occurs in the user. Not sure if this is intentional or not
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by ghost**
Fixes #9574 #9592 #9586

### CODE REVIEW

**Comment by Exxion** [comment]
Well at least say "Fixes #9574" in the OP so it autocloses when this is merged

**Comment by PJB3005** [comment]
Sounds like a bit of a hacky fix, modifying `shock()` might be a better idea.

**Comment by ghost** [comment]
9600bauds: Hope I am not stepping on your toes, I was able to replicate, confirm your suspicion, and test the fix

**Comment by Exxion** [comment]
You have to put fixes (or one of a few other words) before each of the issue numbers to autoclose them

**Comment by Exxion** [comment]
Wait never mind you did that in the commit messages

**Comment by clusterfack** [comment]
I think shock() should additionally check for adjacency to user instead.

**Comment by clusterfack** [comment]
Otherwise looks good

**Comment by ghost** [comment]
Here is the issue with checking for adjacency. What if the user has a telegrabbed crowbar and it is right next to him as he uses it to smash down an electrified grille? Rather than doing a check if telegrabbed/adjacent then: etc, it makes more sense for this highly specific situation to behave in the manner outlined. The user is insulated from the shock by an air gap regardless of any other variable and this fix does exactly that. Just my 2 cents

**Comment by clusterfack** [comment]
I see your point, though it looks uglier I'm inclined to agree it covers more fringe cases

**Pull request merged**
