### PR TITLE
all maps now have same syndie shuttle

### PR DESCRIPTION
**Pull request by SonixApache**
shuttle

Unified the syndicate shuttle to be identical on all maps. yes, even Deff's edgy black colorscheme is gone, and as are Roid's bombs.
Major changes:
 - Added 5 crowbars to the gear room
 - Make it so you can just shove the nuke through the teleporter
 - Medical room now has space for all their tools + a organ freezer
 - Added an empty toolbox to the rocket crate

🆑 
 - tweak: All maps now have the exact same syndicate operative shuttle
 - rscadd: Added 5 crowbars, tele-nuking, and an organ freezer to all operative shuttles

### CODE REVIEW

**Comment by SonixApache** [comment]
wonder if i should toss in an autolathe

**Comment by PaulRitter** [comment]
whatever happened to the mapdiffbot?

**Comment by MadmanMartian** [comment]
Better way to do this
 - Remove the syndicate shuttles from all maps
 - Have the syndicate shuttle loaded whenever the nuclear operative ruleset fires

**Comment by SonixApache** [comment]
I agree. However, as-is, the syndie shuttle has a unique little base on every map, alongside being connected to a fake building set and the elite syndie shuttle.

Not sure if it'd work without losing some flair.

**Comment by tuypo1** [comment]
Why?

**Comment by Kurfursten** [comment]
@MadmanMartian A mapload of that size would cause a brief stutter that would give away nuke ops. For reference, loading the mecha graveyard is enough to cause this pause too and it is a very small vault.

**Comment by tuypo1** [comment]
You could just load it a few squares at a time over the span of a minute or so but I suppose it's not worth the hassle.

**Comment by SonixApache** [comment]
Why- because having different gear loadouts per map is silly
and because not being able to push the nuke through the porter is sad

**Comment by gbasood** [comment]
> You could just load it a few squares at a time over the span of a minute or so but I suppose it's not worth the hassle.

Tile atmos would probably break with that, also machinery and such

**Comment by Kurfursten** [comment]
In this case it might not since ops shuttle is 100% unsimmed

**Pull request merged**
