### PR TITLE
Bigger and More Immovable

### PR DESCRIPTION
**Pull request by Shadowmech88**
Code scavenged from #9960

Adds immovable pillars and immovable monoliths.
Immovable pillars do this:
image

Immovable monoliths do this:
image

Both have a different impact sound than the normal immovable rod.
The only time either of them will appear in-game is when an admin spawns them.
Also, the volume of an immovable rod's impact sound is now based on the hearer's proximity to the impact.

This does not change the functionality of normal immovable rods whatsoever.

:cl:
 * rscadd: Added two new more destructive variants of immovable rods, admin-spawn only, code courtesy of DeityLink.
 * tweak: The volume of an immovable rod's impact sound is now based on the hearer's proximity to the impact, code courtesy of DeityLink.

### CODE REVIEW

**Comment by 9600bauds** [comment]
:joy::gun:

**Comment by kilozombie** [comment]
Get Deadminned In Five Minutes With This One Weird Trick

**Comment by N3X15** [comment]
That doesn't look laggy whatsoever

**Comment by Aurx** [comment]
A: Please do not pollute our glorious old/tg/ memes, they are precious and beautiful.  
B: There's no particular reason for anything that just says "Fuck everything along this random line and everyone in an airgroup along it or connected to such an airgroup."  As a random event it'd be round-ending, as an admin button it'd be mostly untouchable.  
C: LAAAAAAAAAAAAA server has stopped responding

**Comment by Exxion** [comment]
I'm like 90% sure the original immovable rod did basically what the monolith here does

**Comment by AI-Is-Rogue** [comment]
What do the pillars and monoliths look like?

**Comment by Shadowmech88** [comment]
Pillar:
immovpillar

Monolith:
https://dl.dropboxusercontent.com/u/33846352/parallax/dreamseeker%202016-05-18%2002-18-27-31.webm

**Comment by Zth--** [comment]
Monoliths are scary

**Comment by Megamaw** [comment]
ah, nah. this kind of cheapens the original joke of the 'immovable rod'.

it's times like these i remember people who haven't played as long as me just know the immovable rod as a 'dude weed lmao' random joke instead of what the joke Actually Is

or at least, i dont think shadowmech/deitylink are aware

**Comment by Shadowmech88** [comment]
Are you referring to the idea that the rod is a static object instead of a projectile, and the damage it deals is due to the station colliding with it at a high relative speed?

That notion kind of went out the window when immovable rods were given an angle-based icon like all other projectiles instead of their former static icon.

**Comment by Megamaw** [comment]
no, i mean in the source material there is literally no such thing as an 'immovable pillar' or 'monolith'.

it just makes it an esoteric space thing instead of something actually funny-- ie, the presumed natural conclusion of the 'truly immovable rod' story it was based on

**Comment by Shadowmech88** [comment]
Are you thinking that there will be people who won't get the reference the original object is making, simply because altered versions of the object exist?

**Comment by Megamaw** [comment]
i don't know, do you?

again, either way, it cheapens the joke.

also while i appreciate the noise-distance thing i don't like adding more buttons for the sake of more buttons, and there is almost literally no reason for an admin to press a button that instantly fucks the station this hard

so like even if i didnt agree with the content of the pr (which, well, i like one HALF of it) this is still pretty fucking unatomic

**Comment by Probe1** [comment]
>and there is almost literally no reason for an admin to press a button that instantly fucks the station this hard

sadly as much as you and I wish differently, there are many reasons.

**Comment by 9600bauds** [comment]
Any of them good?

**Comment by Exxion** [comment]
Again
The original immovable rod did fuck the station this hard

**Comment by clusterfack** [comment]
I dislike how when you have something nice you have to make like 10 variants of it to cash in on it and dilute the thing that was nice about the original.

**Comment by Megamaw** [comment]
cluster that's a much better way of summing up my sentiment than what i said

**Comment by Megamaw** [comment]
>everyone says it's dumb
>it's merged anyways

Thanks

**Comment by Exxion** [comment]
>everyone

image

**Comment by Megamaw** [comment]
can we really count people who press the shiny button, instead of actively contributing to the discussion

**Comment by Exxion** [comment]
Yes

**Pull request merged**
