### PR TITLE
Adds Fidget Spinners that can be won from the arcade machine

### PR DESCRIPTION
**Pull request by RFultra**
Adds Fidget Spinners that can be won from the arcade machine

Sprites by happy cat face on discord

🆑

- rscadd: Added Fidget Spinners that can be won from the arcade machine

### CODE REVIEW

**Comment by ghost** [comment]
goofball no goofing

**Comment by SkowronX** [comment]
kys

**Comment by TheFriggenSawbones** [comment]
content

**Comment by Shadowmech88** [comment]
I think his meme density might actually be higher than Goofball's.
It's frightening.

**Comment by NigglyWiggly** [comment]
For fucks sake

**Comment by Kammerjunk** [comment]
Is this late-stage "when you code it"ism

**Comment by ghost** [comment]
You can't even spin it, it just always looks like it's already spinning

**Comment by ghost** [comment]
@Kammerjunk it's a late stage terminal disease

**Comment by RFultra** [comment]
space spinners man, the technology advanced to where they spin on there own

**Comment by troots** [comment]
@Unknown-as-Captain it's a fidget spinner not a fidget notspinner

**Comment by JustSumBody** [comment]
@Iamgoofball You forgot to take one with you

**Comment by carshalash** [comment]
🍆

**Comment by Exxion** [comment]
Judging by the inhands, that thing's like a foot across, or at least nearly

**Comment by Gunosaguki** [comment]
replace it with a butterfly knife for less meming

**Comment by AutismSpider** [comment]
time to stop

**Comment by SonixApache** [comment]
if i make a pr that's called 'repo bans emillia again' do you think they'll merge it
itstimetostop

**Comment by ghost** [comment]
cease it

**Comment by RFultra** [comment]
probably sonix

**Comment by Intigracy** [comment]
I miss goof honestly.

His memes were better than this.

**Comment by ghost** [comment]
keep flavour of the month bullshit outta the server

**Comment by gbasood** [comment]
Fuck you got to this before I did

**Comment by RFultra** [comment]
reopen this shit right now

**Comment by troots** [comment]
according to @Skullyton, if the fidget spinners meme survive this month then this gets added no questions asked

**Comment by ghost** [comment]
who the everloving heck even are you?

**Comment by sonime** [comment]
Re open this right the fuck now you meme hating fuckbells

**Comment by Exxion** [comment]
Better idea

**Comment by ghost** [comment]
>can't unlock

aw

**Comment by ghost** [comment]
RIOT

**Comment by RFultra** [comment]
Merge it!

**Comment by RFultra** [comment]
there

**Comment by salamandooo** [comment]
can we have a server poll please

**Comment by RFultra** [comment]
I agree

**Comment by PJB3005** [comment]
no

**Comment by d3athrow** [comment]
Ahahahaha

**Comment by troots** [comment]
👀

**Comment by clusterfack** [comment]
Why?

**Comment by Probe1** [comment]
>This wasn't merged
You're lucky I was gone!  All the posts about it make it even more hilarious than what would have been a half second eye roll thing to find in game.

**Pull request closed without merging**
