### PR TITLE
New Merch Computer Goods: Cheap Soap & Face Masks

### PR DESCRIPTION
**Pull request by DeityLink**
The Covid measures update!

face_masks
pull
masks

:cl:
* rscadd: New items added to the merch computer. Including a cheap soap guaranteed for 20 uses (and then has a progressively increasing chance of melting away), and Sterile Masks, that come in the usual medbay variety along with a more sober black variant, and a terribly clowny colorful variant.
* rscadd: Sterile Masks can now be moved away from your face like breath masks can. Doing so will null their sterility factor until you put it back on properly.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
20 still seems like a good amount of uses for something that cheap. Maybe 10? Maybe I'm just nitpicking but it seems fairly powercreepy

**Comment by DamianX** [comment]
Why should the merch computer provide soap?

**Comment by DeityLink** [comment]
@DamianX Here are my reasons:

* Most jobs don't have access to space cleaner
* There is often no janitor, or if there is they are dead, and if they're not they often don't respond, and even if they did you generally don't want some random working into your workplace if only because that means you need to open and close the door (and even then that's like 20% of the time, since the rest of the time there is no available janitor)
* The mining vendor at cargo sells infinite soap at $15. Cargo technicians can access it, and asking for a soap at cargo is often faster and less cumbersome than either calling the janitor or bothering chemistry (lol)
* The merch computer is basically a small convenience store, it'd make more sense to find soap there than inside the mining vendor of all places.
* Even then it's twice as expensive as the infinite soap from the mining vendor, and it can only clean a limited area, **it's intended for those specific cases where you spilled something in your workplace but don't want to call the janitor just to have a single tile cleaned up.**
* Lastly it will by no mean replace the need for janitors as not only are they required to clean the hallways and other large public areas that make up 75% of the station, but their tools are more efficient at cleaning.

People can still both the captain or cargo for some infinite soap if they want to, this option is a path of least resistance that will be preferable in very specific cases, but won't do if a clown's been spreading bloody footprints over your entire lobby.

**Comment by DeityLink** [comment]
I'll lower the amount of guaranteed uses to 10 if needed to support the intent.

**Comment by Kurfursten** [comment]
The real soap buff we need is for mappers to put the biogenerator at the front of botany in a generalfab-like setup.

**Comment by Dacendeth** [comment]
There is already a soap vending machine, it's even in cargo, is it so bad to talk to a cargo tech to get them to get you soap?

**Comment by DeityLink** [comment]
@Dacendeth please read the above comments.

**Comment by juanototo2** [comment]
Can you add a camo face mask?

**Comment by Eneocho** [comment]
> 
> 
> The real soap buff we need is for mappers to put the biogenerator at the front of botany in a generalfab-like setup.

Based.

**Comment by DeityLink** [comment]
> 
> 
> Can you add a camo face mask?

When you sprite it.

**Comment by Eneocho** [comment]
On my way to snort growth dishes and hug people.

**Comment by strawberrytan** [comment]
looks fine to me, I have two questions though

Does the soap slip on walkover?
Does being slipped on reduce the available uses left?

**Review by Kurfursten — APPROVED** [review]
Codewise this is fine.

I do like strawberry's idea of subtracting a use when used to slip though.

**Comment by DeityLink** [comment]
so do I

**Pull request merged**
