### PR TITLE
Europa Lights - test server PR

### PR DESCRIPTION
**Pull request by ShiftyRail**
<!--
Pull requests must be atomic. Change one set of related things at a time.
Test your changes. PRs that were not tested will not be accepted.

The idea behind this PR is that it can be merged - and reverted - to the test server.

### CODE REVIEW

**Comment by pedr69** [comment]
the testing server is broken, the rounds don't even start
when/if you get it working please also testmerge the landlines

**Comment by ShiftyRail** [comment]
@pedr69 Rounds not starting is weird. The git part I can fix relatively easily. At the worst case, we can do it live.

**Comment by brndd** [comment]
Is this purposedly reverting all these seemingly unrelated changes?

**Comment by pedr69** [comment]
i believe the six trillion commits are there because the test branch hasn't been updated in a year
image
this isn't going into the main branch

**Comment by brndd** [comment]
Ah, of course. I didn't notice it was into a different branch. Test server merges used to be done by the Discord bot I think.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
lets try it live its more fun that way
test server is kind of nebulous

**Comment by Inorien** [comment]
holy diffs batman

also hina is right this should go straight to live, we can blame any problems on pomf and the new server

**Comment by ShiftyRail** [comment]
Fixed conflicts/diff.

**Pull request merged**
