### PR TITLE
Emergency shuttle won't leave without engines

### PR DESCRIPTION
**Pull request by Zth--**
It needs a bit more of work, will finish if you guys think this is a good idea.
Also I can make it so pods can be sabotaged too (fuck you podbabies)

:cl:
 * tweak: Emergency shuttle won't leave without engines

### CODE REVIEW

**Comment by DamianX** [comment]
Does this make the round not end?

**Comment by ValkyrieSkies** [comment]
Cute idea, sounds shit in practice.

**Comment by SonixApache** [comment]
why would this ever be desired

**Comment by Zth--** [comment]
The round would end after the 2 minutes pass with or without shuttles.

It's just that I found engineless shuttles very dumb, and I liked the idea of sabotaging pods or the entire escape shuttle. But I'm not so sure of how that would play out

**Comment by Zth--** [comment]
To the bin

**Pull request closed without merging**
