### PR TITLE
Frying pans are craftable.

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
You can now make spare frying pans for 10 metal sheets, same cost as a baseball bat.
## Why it's good
Ghetto cooking on a burning barrel in the middle of maintenance can be a reality if there's a reasonable way to get more pans. 
:cl:
 * rscadd: You can make frying pans with 10 metal sheets.
 * rscadd: Frying pans can be recycled.

### CODE REVIEW

**Comment by jellyveggie2** [comment]
Don't forget to make it recyclable as well, all it needs is these two lines on pan.dm:
```
starting_materials = list(MAT_IRON = CC_PER_SHEET_METAL*10)
w_type = RECYK_METAL
```

**Comment by Eneocho** [comment]
Good catch yeah. On it.

**Comment by BomberBro** [comment]
These should really be autolathe-only imo. Most of the stuff metal makes very basic construction stuff and that's in there because otherwise building anything is absolute hell. It's already sort of dumb baseball bats can warp into existence without having to use something sharp on the wood, and here the spaceman is doing something even more absurd.

**Comment by ManopolisJones** [comment]
Wouldn't even say lathe only on the pan, I reckon it should be able to be forged at an anvil so people going native can have a chance to cook real food lacking proper tech.

**Comment by Kurfursten** [comment]
I think anvil recipe is a good compromise but I'm also not strongly against this PR. I think cooking with a frying pan is more complicated enough and getting access to a solder for a normal microwave is easy enough that there's not really a need to gate the pan.

I think Bomber's point about immersion is fair.

**Comment by Eneocho** [comment]
The anvil sounds good on paper but it's a whole can of worms to get forging equipment if you just want one or two extra pans, and making it latheable only goes against the idea of a greyshit cooking a cockroach in the middle of maintenance on top of a burning barrel, since they'd need access to a lathe.

**Comment by ManopolisJones** [comment]
> The anvil sounds good on paper but it's a whole can of worms to get forging equipment if you just want one or two extra pans, and making it latheable only goes against the idea of a greyshit cooking a cockroach in the middle of maintenance on top of a burning barrel, since they'd need access to a lathe.

The **clear** solution is to have a craftable ghetto anvil which is just a big metal cube costing like 30 metal. No hammer? Just use a toolbox, not like either of these tools are gonna make anything of quality anyway. I mean shit, the hardest get would be scrounging up enough grass for sand to make the forge, and at that point if you aint in it all the way, you may as well just go to cargo and ask them to print you out a frying pan for your ghetto cooking.

**Comment by ShiftyRail** [comment]
Makes this an autolathe thing. Or anvil.

**Comment by Eneocho** [comment]
>Makes this an autolathe thing. Or anvil.

Why? It's not that good a weapon as the baseball bats and they get the wooden plank craft treatment, this has some actual use for chefs and ghetto cooking since a ghetto chef would NOT have access to an autolathe and getting the entire forging equipment is a huge deal if you just want a pan or two (not to mention it would also go against the ghetto deal).
Clearly there are people that agree, the PR has 8 👍🏻 for a reason.

**Comment by svobodnik** [comment]
> Why?

powercreep

**Comment by Kurfursten** [comment]
It has the vote support

**Pull request merged**
