### PR TITLE
adds sweetrolls

### PR DESCRIPTION
**Pull request by robintime**
GGGGGGGGGG
high impact PR
a sweetroll can be made with flour, sugar, an egg, and butter
YES i will update the wiki

:cl:
 * rscadd: sweetrolls can now be made in the microwave

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
no lollygagging

**Comment by Kurfursten** [comment]
Sprite should be a bit flatter don't you think? Too tall

Let me guess, someone stretched out your sweetroll

Also: this is a lot of ingredients for a small dessert. Since butter already contains cream I think I'd drop the milk.

**Comment by robintime** [comment]
i thought they were kinda tall like that? why do i remember them being tall wtf wtf
also shit i was just going off what they're made out of In Da Lore but you're right
gimme a sec

**Comment by Blithering** [comment]
Skyrim sweetrolls are the tall ones, fallout ones are the flat ones.

**Pull request merged**
