### PR TITLE
lets syndicate space suits hold nitrogen tanks

### PR DESCRIPTION
**Pull request by gurfan**
:cl:
 * tweak: Syndicate space suits can now hold nitrogen tanks.

### CODE REVIEW

**Comment by ErrorsWindows** [comment]
I'm remembering the thing I saw for obj/clothing/suit where it could hold every type of gas tank _except_ for plasma tanks (it was made before plasmaman and would have no reason to make an exception for storing plasma tanks because they didn't exist yet)

... I wonder how long stuff like this has been grandfathered into old simple clothes like this without anybody knowing

**Comment by SECBATON-GRIFFON** [comment]
honestly i think these things should be discounted for vox or plasmamen too, since for them it's more style points than EVA necessity.

**Comment by pedr69** [comment]
>/obj/item/weapon/tank/jetpack,/obj/item/weapon/tank/jetpack/void,/obj/item/weapon/tank/jetpack/oxygen,/obj/item/weapon/tank/jetpack/nitrogen,/obj/item/weapon/tank/jetpack/carbondioxide

arent these redundant?
wouldn't the parent `tank/jetpack` include them all?

**Comment by SonixApache** [comment]
is there at this point any reason to not just condense it to `/obj/item/weapon/tank` ? It can hold basically every subtype but plasma tanks.

**Comment by gurfan** [comment]
Yeah I'll just do that

**Pull request merged**
