### PR TITLE
New Botanist Traitor Item: Briefcase Full of Bees

### PR DESCRIPTION
**Pull request by Shadowmech88**
Traitor botanists can now buy a briefcase containing a swarm of twenty angry bees for 4 TC. The bees are released when the briefcase's inventory is opened.

:cl:
 * rscadd: Traitor botanists can now buy a briefcase containing twenty angry bees for 4 TC.

### CODE REVIEW

**Comment by Lokiamis** [comment]
100 bees sounds like a lot to me, man.

**Comment by Shadowmech88** [comment]
The bees clump together into a single, slow-moving swarm. They're not that difficult to outrun or avoid.

**Comment by AutismSpider** [comment]
4tc for a item that can be counter by a  fire extinguisher

**Comment by yclatious** [comment]
I mean, its better than nothing and if you are sneaky about it, you could steal every hall extinguisher.

Eh, why not.

**Comment by SkowronX** [comment]
HWHAT'S THIS?

**Comment by AutismSpider** [comment]
https://www.youtube.com/watch?v=PYtXuBN1Hvc

**Comment by Zth--** [comment]
If these are the same bees from the bee gun, then you should buff them. I've used that machine a few times and it's pretty much shit. Bees are slow and disappear after 30 seconds or so

**Review by PJB3005 — APPROVED** [review]

**Comment by Shadowmech88** [comment]
It's actually the same bees that are spawned by the admin "Not the bees!" button, but they're still pretty terrible.

What if I increase the speed of these bees so that they can actually chase people?

**Comment by eplgr** [comment]
@Shadowmech88 So they don't have the same AI the normal bees have?
I mean, the normal bees are pretty awful and they probably need a revamp. If you hit them, they would only hurt YOU, just you, ignoring everybody else forever. I suspect they also stop working/doing stuff until you calm them down. But they will never hurt anyone else.

I hope these bees are not like that. 

(make bees fun again!)?

**Comment by calzilla1** [comment]
Buff it to like 1000 bees, let it recharge quickly, and can be used like a very slow bee minigun.

**Comment by Zth--** [comment]
And for god's sake they shouldn't diasappear magically after a minute, that's fucking stupid

**Comment by Shadowmech88** [comment]
@ShoMek 
They *do* have normal bee AI, they've just got their feral counter increased to make them angry.

**Comment by Probe1** [comment]
BEEEES

**Comment by Shadowmech88** [comment]
If the bees are terrible and not worth it, make sure to make an issue about it so they can be buffed.

**Pull request merged**
