### PR TITLE
literally replaces all solo antag objectives with "just bee yourself"

### PR DESCRIPTION
**Pull request by ghost**
Because people say we need this
:cl:
 * rscdel: replaced all solo antag objectives with "just bee yourself"

### CODE REVIEW

**Comment by kilozombie** [comment]
How about the slightly less memey "Make the shift interesting for yourself and/or others."

**Comment by small-boss** [comment]
i literally cant remember a round which ended up being good because the solo antag did his objectives. they are useless.
speed merge this

**Comment by jknpj** [comment]
A lot of effort for a meme pr.

**Comment by ghost** [comment]
I don't make joke PRs

**Comment by yclatious** [comment]
Madman.

**Comment by kilozombie** [comment]
WILD

**Comment by SonixApache** [comment]
what
the fuck

**Comment by Orangerush** [comment]
100% no joke good job man. Objectives dumb and there's no need for them. Nobody but probably 2 or 3 people follow them. Should remove "Just bee urself" part though and add something that just tells them to spice the round up

**Comment by Chazach** [comment]
wish this wasnt speedmerged because it doesnt deserved to get reverted and forgotten

**Comment by kilozombie** [comment]
Yeah honestly I'd be down for this being kept in permanently if it actually functions. Half the time I get antag shakes because I want to complete an objective, it's a very psychological thing.

**Comment by ShiftyRail** [comment]
Why did it have to be in a meme format ?
Remove the objectives and put a non-meme objective saying "Wreck havoc", or "You have carte blanche", please.

**Comment by bathosbathtime** [comment]
Apathetic to the PR itself but I hate speed merging.

**Comment by DeityLink** [comment]
While I agree that objectives need a thorough rework, this is not the answer it needs.
If anything, replace them with Guidelines, but here you're just essentially giving the antag version of writer's block. Some players need something to work with, even if they're gonna end up doing something completely different.

Telling people to just be themselves is just...

Well, let's say hello to a new era of tatorstended.

Here's a few ideas for guidelines:
* Steal high value items and ship them to the syndicate
* Cause destruction aboard the station

Also objectives that are easy to check such as shuttle hijack are fine.

**Comment by kilozombie** [comment]
@DeityLink Check out https://github.com/vgstation-coders/vgstation13/issues/19489, the discussion there is actually super neat so far
One point that's practically consensus right now is to just remove win/loss checks.

**Comment by DeityLink** [comment]
Eh, I think it could be worded differently but it could be mildly interesting to have some stats that pertain to the objectives (like whether the target is dead or alive).
This way, things like "minimize casualties" could have things like "X players died this round, make of that what you will"

**Comment by Allspice** [comment]
Only thing solo objectives (at least, in a state resembling the present) are good for is end of round laffs when people see the blams flooder had minimize casualties.

**Pull request merged**
