### PR TITLE
Removes telekinesis

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
The worst superpower of all that needed a lot of exceptions and such whenever telekinesis interactions were involved

Why:
- A ton of things have no sanity with TK

Direct consequences:
- You can no longer acquire the Losseta stone

Indirect consequences:
- A bug or two from such an extensive removal, I am eyeing the "buildmode" locked thing because I don't know what it does

In the future I might add it back, but possibly as an occasional ability that calls "attack_tk" or something, I don't know.

:cl:
 * rscdel: Telekinesis superpower is gone.

### CODE REVIEW

**Comment by DamianX** [comment]
Can you make a few examples of things that have no sanity with regard to TK?

**Comment by boy2mantwicethefam** [comment]
A few I can recount on the spot
You can remotely smash walls as a hulk using TK
Access-restricted still require your personal access even if there's no possible way to make contact with your ID and the access-restricted machinery
Changing laws of silicons show your identity even if you did it remotely, if changing silicon laws remotely isn't a lack of sanity by itself
A fixed one, but you used to be able to remotely crack safes as you could hear with a stethoscope in hand remotely
I can't remember which, but you can still take items out of things without being adjacent and plop them in your hand, I say I can't remember because I can't remember if you could with the antique gun, but I think you can do it with the ID console

**Comment by Lokiamis** [comment]
It's a cool, unique feature in the game that's fun to use with incredibly minor issues. Why the fuck would you delete it instead of fixing or ignoring the issues that nobody cares about?

**Comment by Tehsapper** [comment]
why not remove hulk, cold resistance and xray as well then if you only want memeshit powers to remain.

**Comment by Tehsapper** [comment]
oh LOL you actually want xray to be gone too
what the fuck man

**Comment by Kammerjunk** [comment]
so add the sanity

**Comment by Killette2** [comment]
Fuck no

**Pull request closed without merging**
