### PR TITLE
Condenses several items in sec related lockers to a single box of gear.

### PR DESCRIPTION
**Pull request by DrSnips**
[qol][bugfix]
The title sums things up a bit. The main reason for this is to cut down on the clutter inside of sec lockers and to prevent the issue of items overflowing from the locker and ending up outside. Almost all of the gear contained is overlap between all of the lockers.
Each sec gear box contains:
`sec belt, sec headset, SPS, flash, flashbang, knife holster, tactical light, sechud, black gloves, stun baton, taser, pepper spray, sec. ta:b:e, hailer`
While the detective's contains:
`sec headset, sec hud, black gloves, sps, 2x .38 ammoboxes, speedloader, evidence bag box, scanner, binoculars, and a hand TV set.`
A minor sprite to make it stand out.
boxes

**Possible things to REEE about.**
~~Officer lockers start with one pair of cuffs now. The other already had some to start.
Detectives now start with a roll of sec tape and a tactical flashlight.
Minor additions that were requested.
Detectives now start with sec gear.
This one is actually pretty big and I have a different plan for the detective's locker later even if this passes. I'm not so keen on this change but I thought I would at least run it by people. It's not like the detective can't get this stuff already since they can just open an actual officer locker for the gear.~~

:cl:
 * tweak: Common and standard sec gear and detective gear now comes in boxes to cut down on clutter. This affects officer, warden, detective, and HoS lockers.

### CODE REVIEW

**Comment by kilozombie** [comment]
Might be worth making a sprite for these
Box sprites are terribly simple, so even if it's codersprite it'd be fine.

**Comment by iFlashYou** [comment]
>security buffs

**Comment by DrSnips** [comment]
I don't really see the need for one since it's just for function but if someone else agrees sure.

**Comment by kilozombie** [comment]
The main issue would be clarity-- opening a sec locker as somebody that doesn't read Github and being confused as to why all the normal equipment is gone, or being a new Security player and not realizing all the valuable stuff is in a box.

**Comment by DrSnips** [comment]
I think a box named security essentials is pretty obvious. As I said if another person feels the same I would make one.

**Comment by SonixApache** [comment]
👍 on clutter removal
👎 on making detectives think that they're officers (just make a subtype)
👎 on no sprite
👎 on cuffs, fuck the whiners, stay atomic

**Comment by groosbstrd** [comment]
it makes it kinda easy for a greyshit to get in, grab a box of all the sec shit, and get out.

**Comment by FudgePucker** [comment]
Detectives should have security gear.
A) if security is understaffed they really need to help out.
B) they could use some of the tools to help out with their job, like police tape.
C) if the killer returns to the scene of the crime, and there isn't another officer, having the means to detain them would be nice, instead of murder/running away.
D) implying detectives actually do any detecting on our low rp server. What, are they some jack off with a gun and armor that is to spend the entire round in the bar?

**Comment by DrSnips** [comment]
@groosbstrd  I'm not too worried about that since you have to open a locker anyway to get it and you could just use an unlocked storage to drag all of it away already.

**Comment by SonixApache** [comment]
@FudgePucker 
A) If security is understaffed, they can get a job change to officer.
B) Agreed, tape would be good for them actually.
C) There are alternative ways of restraining them, but it's not their job
D) Our level of RP is only as low as *you* set the bar. Silly argument.

**Comment by Blithering** [comment]
The main thing I'm worried about is a box containing another container, in this case the secbelt.

**Comment by DrSnips** [comment]
For some reason you can't put some items back into the large box despite it being a large storage item namely the taser, baton, and belt. Surely this is intended but I don't know why. 
Also the box doesn't fit into most other storages since it's a large item so you have to carry it. It would be less convenient to carry the box with the belt in it if you wanted that to be your storage.

**Comment by Blithering** [comment]
Oh its the large box? That's a different story then. I was worried about abusing nesting to get all your sec equipment inside your internals box

**Comment by spoonylove** [comment]
Would like to see something like this for botany and xenoarch. Less clutter is always nice.

**Comment by DrSnips** [comment]
**CHANGES**
The detective no longer has the sec gear box and now have their own with only fitting items that being:
`sec headset, sec hud, black gloves, tactical flashlight, sps, sec tape, 2x .38 ammoboxes, speedloader, evidence bag box, scanner, binoculars, and a hand TV set.`
This technically adds a few minor items like ta:b:e to their locker but other than that it doesn't add anything major like how the sec gear would.

The boxes now have a slightly different sprite by request.
boxes

Added a comment in locker file about the contents of the boxes and where to find them.

**Comment by ghost** [comment]
Can't you just make it so the belts in the lockers are filled by default with the useful items?

**Comment by DrSnips** [comment]
I could but not all of the items fit on the belt like boot holsters and headsets. Also the amount of items exceeds the capacity of the belt.

**Comment by Blithering** [comment]
This does make me want a round setup option that replaces the box in every locker with one containing nothing but a badge and a gun.

**Comment by SonixApache** [comment]
*JUST* do the additions seperately. Atomicity. 
I think the box idea is great, but the "also gives detective some officer stuff" part isn't.
And fuck off with the cuffs. We don't need more cuffs. We already have a fuckload of cuffs fucking EVERYWHERE.

Good sprites 👍

**Comment by DrSnips** [comment]
I guess the cuffs can go but the detective getting tape and a flasblight seemed minor enough. But you're really hung up on it I guess it can go for now.

**Comment by KingofHONK** [comment]
Although outside of the PRs scope, clown can use a box like this badly. Their inventories start with every slot full.

**Pull request merged**
