### PR TITLE
Hazard vests can now hold trash bags, adds a hazard vest to janitor's locker

### PR DESCRIPTION
**Pull request by djkramer123**
What it says on the tin, the janibelt is supposed to hold the trashbag but can't because of size issues and changing the sizes had unintended consequences. On the bright-side, doing it this way makes it so the slowdown effect of having a full trash bag applies.
:cl:
 * rscadd: The hazard vest can now hold trashbags in its suit storage.
 * rscadd: A hazard vest has been added to the janitor's locker.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
thumbing up despite it not really making sense because i frequently play a character who must carry the trash bag in his hands while also wearing a hazard vest.

**Comment by adacovsk** [comment]
Should make the janicart hold items or have a separate item like in tg be able to hold more items.

**Comment by wotisjanitor** [comment]
> Should make the janicart hold items or have a separate item like in tg be able to hold more items.

downthumbed because i do not use the cart.

**Comment by ManopolisJones** [comment]
Why not make it so an empty trashbag can fit in your backpack (kind of like how an empty trashbag can be worn) instead?

**Comment by Exxion** [comment]
> Should make the janicart hold items or have a separate item like in tg be able to hold more items.

The janicart *can* hold the trash bag.

**Comment by pedr69** [comment]
time for two backpacks baybee

**Comment by Apogee-dev** [comment]
overalls can already hold trash bags (and most other janibelt items, see #29410) and are more thematic for janitor than a hazard vest imo, consider using those instead. you could edit the overalls to properly apply the full bag slowdown if necessary, i'm unsure if that actually works on them

**Comment by adacovsk** [comment]
> The janicart _can_ hold the trash bag.

that's one thing

**Comment by Exxion** [comment]
> that's one thing

Yes, the same one thing this PR is about

**Comment by adacovsk** [comment]
> > that's one thing
> 
> Yes, the same one thing this PR is about

haha oops, wrong PR

**Comment by Kurfursten** [comment]
Alternative won in popularity

**Comment by wotisjanitor** [comment]
> Alternative won in popularity

what? that wasnt an alternative. we want both

**Pull request closed without merging**
