### PR TITLE
I'm done with this codebase.

### PR DESCRIPTION
**Pull request by PJB3005**
Here's the secret repo, I don't care anymore. Shitloads of ruined dreams and counterfeit goon secret ripoffs in here.

### CODE REVIEW

**Comment by PJB3005** [comment]
image

Ok that worked.

**Comment by Aurx** [comment]
You're like, two and a half weeks early man.  
And at least pad out a bit, +1 -0 is too obvious.

**Comment by PJB3005** [comment]
@Aurx yeah I couldn't be bothered to go that far since I'm just debugging MoMMI.

**Comment by Aurx** [comment]
>he couldn't be assed to hold down the carriage return for thirty seconds and copy-paste the file a few times

As expected of a c*der.

**Comment by Kurfursten** [comment]
What really impresses me is that our whole secret repo is a diff of only +1.  Truly those Gooncoders know how to write compressed code in elegant ways we can only imagine.

**Comment by SysadminJeroen** [comment]
Open and close it a couple more times.

**Comment by DamianX** [comment]
We benchmarked it and BYOND runs the code faster when you compress it all down to one line.

**Pull request closed without merging**
