### PR TITLE
Shortens mining smelting line

### PR DESCRIPTION
**Pull request by Intigracy**
See images for details.

### CODE REVIEW

**Comment by clusterfack** [comment]
This wont help, what you need is to have conveyor belts move more than 10 objects per tick in their code.

**Comment by Iamgoofball** [comment]
https://github.com/tgstation/-tg-station/pull/10556/files

**Comment by ComicIronic** [comment]
It doesn't make outside loading any faster, and outside loading is more common.

**Comment by Intigracy** [comment]
Good idea Clusterfack, did so.

I'm not porting any of your code, goofball. Someone else can if they have the time.

**Comment by Probe1** [comment]
ehh.  remember when I said 6 is good, 17 is unacceptable?  14 isn't really terrific.  even 10 is pushing into the limits of bad mapping.  it's not a disposal system, it's just a smelter.  there's no need for it to be that big.

**Comment by Intigracy** [comment]
That's why I also bumped up the amount of minerals that move at a time.

It's a 150% increase.

**Comment by Probe1** [comment]
I'm not going to gripe too hard.  I want it to be faster.  I'll be happy if you accomplish it.

**Comment by Iamgoofball** [comment]
yeah, 25 is the sweet spot for "doesn't lag but moves a lot of materials".

**Comment by Intigracy** [comment]
Updated.

**Comment by Probe1** [comment]
@ComicIronic 

That's the first time I've heard anyone say that.

image

**Pull request merged**
