### PR TITLE
Round Over YEAHHHHHHHH

### PR DESCRIPTION
**Pull request by DeityLink**
adds https://www.youtube.com/watch?v=S15YYwLYCgw and https://www.youtube.com/watch?v=09s-c2JVI40 as round end soundfiles.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Why don't I see the Rock in the list of possible round end sounds?

**Comment by SkowronX** [comment]
While you're at it: 
https://www.youtube.com/watch?v=wEr09Vi_bw0
https://www.youtube.com/watch?v=RQhWROgMTeI
https://www.youtube.com/watch?v=K5alwU0yXhc

**Comment by DeityLink** [comment]
@Shadowmech88 SMELELLEE is the sound when you arrive at centcom. Those are the sound that play when the server restarts.

**Comment by DeityLink** [comment]
@SkowronX should I use the Playstation or the Saturn version of the Rayman jingle? The playstation version was technically older.

**Comment by MercuryDoll** [comment]
The SMW jingle is probably too long, quite frequently the roundend sounds are cut off from the game restarting. I would like it replace the Rock though.

**Comment by SkowronX** [comment]
@DeityLink either one is fine

**Comment by Konater** [comment]
Playstation version please
Also sonic CD EU/ 3&K / BTS jingles are better

**Comment by DeityLink** [comment]
Added a few more sounds. check the Files changed to listen to them.

**Comment by Konater** [comment]
Can we merge these with the rock so they actually get played? I think a lot of the server just silently restarts without putting a banging donk on it first

**Comment by DeityLink** [comment]
When/Who added smelelelee anyway?

Should we just swap the two sounds? so smelelelele happens when the server restarts?

**Comment by clusterfack** [comment]
Pomf added it when he added map voting

**Comment by Hoshi-chan** [comment]
https://www.youtube.com/watch?v=mpEeGPvZETA

Because the Japanese version of Castlevania 3 had way better sound.

Also, https://www.youtube.com/watch?v=leDVVhuubPI

**Comment by DeityLink** [comment]
I'd rather we only use "victory" musics.

**Comment by Imagebard** [comment]
>I'd rather we only use "victory" musics.

**GAME OVER YEAAAAAAAAAAAAAH**

**Comment by DeityLink** [comment]
C'mon, that one is jovial as fuck. When I say victory I mean at least upbeat.

**Comment by Imagebard** [comment]
Okay but ignoring that, the problem is that you're picking "victory" tunes in SS13.
Is it irony or something

**Comment by SkowronX** [comment]
It's pretty much on the same level as the metal slug mission complete jingle.

**Comment by DeityLink** [comment]
This.

I'm using the metal slug's jingle as the standard for what the sounds should be like.

ps: just realized that Hoshi replaced the game over sound with a victory sound. I'll use the All Clear one.

**Comment by Hoshi-chan** [comment]
Woo!

**Comment by 9600bauds** [comment]
If you touch SMELELEL I will end you

**Comment by NigglyWiggly** [comment]
> Added TF2 Victory sound

Why did you do that

Also they're all so fucking loud jesus

**Pull request merged**
