### PR TITLE
removes a sneakycoded change that forces all nuclear operatives to be human

### PR DESCRIPTION
**Pull request by gurfan**
#31874 at fault

:cl: 
 * bugfix: Operatives can now be nonhumans again.

### CODE REVIEW

**Comment by WindowsErrors** [comment]
huh

**Comment by boy2mantwicethefam** [comment]
It says it fixes it for nukeops too.
Also I am not sure syndie plasmamen and vox are supported properly.

**Comment by gurfan** [comment]
they are supported

**Comment by WindowsErrors** [comment]
they are

**Comment by Eneocho** [comment]
BRING BACK OPS AI

**Pull request merged**
