### PR TITLE
Ports DMItool from bay

### PR DESCRIPTION
**Pull request by ghost**
Coded by @GigaNinja32
He's a pretty cool dude and allowed me to blame the bugs in it on him
As far as I can tell there are none
How does it work? I don't know
I do know that it resolves DMI conflicts
if you ever have coded anything with a DMI you'll know that that is literally revolutionary
Why hasn't anyone ported this before it's not even dm code I literally just ctrl+v'd  the folder and slapped it in

### CODE REVIEW

**Comment by Exxion** [comment]
Are you sure you don't need to add it to .gitconfig?

**Comment by ghost** [comment]
@Exxion I just stole a port of this to a /vg/-branch codebase by @Zuhayr, didn't seem like he added it to the .gitconfig

**Comment by Exxion** [comment]
Well if you looked at the damn code you ported, it tells you to

**Comment by Intigracy** [comment]
You have to do that manually just like with the map merge driver, though this one has a .bat that does it for you when you use it.

There is no .git folder on the repo, only locally.

**Comment by Exxion** [comment]
There's no folder, but there is .gitconfig
Which I assume sets that up for newly-cloned repos? I don't know

**Comment by Intigracy** [comment]
Pretty sure it means to use .git/config, not .gitconfig, which are two different things.

**Comment by Exxion** [comment]
Yes, you're right. I have been lied to.
However, you DO still need to add it to .gitattributes

Also, the fact that the repo has no (accessible) .git folder is obnoxious because that means we can't make it use our custom merge drivers when merging things here. Only locally.

**Comment by Intigracy** [comment]
We can if we have pomf add it on the repo folder that updates on the server's machine, can't we?

**Comment by Exxion** [comment]
I don't think that would help
The repo is hosted by GitHub, so even if Pomf's server could merge things, this repo couldn't
Which, admittedly, is a reasonable advantage of GitLab

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Do the `.gitattributes` change.

**Comment by ghost** [comment]
done, please merge

**Comment by Exxion** [comment]
Read better

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Definitely blew it.

**Comment by PJB3005** [comment]
@DrCelt this still isn't ready to be merged.

**Comment by ghost** [comment]
DONE MERGE NOW

**Review by PJB3005 — APPROVED** [review]

**Comment by PJB3005** [comment]
When You Travis It:tm:

**Pull request merged**
