### PR TITLE
Reverts hypno change and gives vampires 10 starting blood

### PR DESCRIPTION
**Pull request by jknpj**
Because sood asked me to do it. Reverts #17067

http://ss13.moe/index.php/poll/147

:cl:
 * tweak: Hypnotise costs 10 blood again.
 * rscadd: Vampires now start with 10 blood.

### CODE REVIEW

**Comment by gbasood** [comment]
Like I've said in discord a bunch, I want to see how round boil down once players get a chance to get used to the previous change before merging this one.

The overall goal of the PR before this one as well the current PR is to make the early parts of a vampire round less frustrating for all players. Previously a vampire without access to chloral would likely not get anything done for a large portion of the round. This seems to me, from a player's perspective and from observing, to be the single most frustrating thing about participating in a round of vampire.

**Comment by ghost** [comment]
True that.

**Comment by ghost** [comment]
And for the record, I will say this here for the sake of clarity.  I never intended for the hypnosis change to instantly make vampire great.  It was intended to give vampire some actual progression.  The game-mode has its problems, and I will be the first to admit it.  The issue was that we were ignoring these problems for a long time by just making it impossible to progress the game-mode without chloral hydrate or taking on the station with the holy trinity of cheese (backpack full of guns/the spare/blowing the borgs).  Now that we can see some vampire round consistently progress, we can take a look at what the actual problems are and where frustrations are coming from.

I hope and believe that hypnosis and vampire as a whole are touched in the future due to such.  

What most people forget and do not realize, is that the original changes that added the hypnosis bloodcost were in response to an antagonist that was so broken, that its use of abilities didn't even actually consume blood.   When you were at full power and entered space, your passive regen would outheal the burn of space.

t5e4gt5esg


Literally made by someone who died in a vamp round, and was so reactionary and untested, that it didn't even work as intended for nearly four months.  Vampire was a steaming pile of shit, and the response wasn't to fix it, it was to lock it away and make progression near impossible.  They did that and called it a day.  I just wanted to draw this to light and attempt to actually do something with the game-mode.  I firmly believe that restricting antag progression doesn't fix any issues, it just let's you see the actual issues less and creates the illusion of the problem being gone.

**Comment by gbasood** [comment]
Pretty sure unid's commit title was a meme

**Comment by ghost** [comment]
@gbasood if only you knew how bad things really were....

[15:42:29]SAY: Unid/(Elise Baker) (@88,105,1) Ghost: can't you like yell ";VAMPIRE" when you get blinded

[15:42:49]SAY: Yred/(Bryan Murphy) (@88,105,1) Ghost: elise, only before you're hypnotized

A few snippets from deadchat that fateful day the PR was made and delivered 2 years of vampstended/chloral monsters onto us (to be fair, yeah, he wasn't the one that died in that particular situation).

**Comment by carshalash** [comment]
https://github.com/vgstation-coders/vgstation13/pull/17038 at least revert this as well.

**Comment by PJB3005** [comment]
Can we come to a conclusion on this.

**Comment by jknpj** [comment]
@PJB3005 i'm torn because role datums

**Pull request merged**
