### PR TITLE
Grues seeing mobs through walls

### PR DESCRIPTION
**Pull request by Hinaichigo**
[tweak]
Based on feedback, this gives grues the ability to see mobs through walls, like xenos can. Hopefully it should make grues feel a little more predatorial and give players more information. 

Please let me know if you think this is a good change or not. 

:cl:
 * rscadd: Grues can see mobs through walls.

### CODE REVIEW

**Comment by ghost** [comment]
dunno, theyre already kinda powerful as-is

**Comment by Eneocho** [comment]
Given that they get cucked by the first powergamer to place light tiles this seems like a decent compensation. I'd also make them spawn in numbers (2 grue instead of 1) so there's a chance to get the things rolling. Thus far I've only seen grues get going twice and both times the admeme intervened and spawned another one after the first one got turbofucked.

**Comment by Armadingus** [comment]
Starting to get a little too much like xenomorphs lite. What if people instead left invisible footprints that disappear on X amount of time that only the grue can see and track?

**Comment by ValkyrieSkies** [comment]
> Starting to get a little too much like xenomorphs lite. What if people instead left invisible footprints that disappear on X amount of time that only the grue can see and track?

This sounds a little contrived and possibly draining on server resources - why not something more thematic like they have wall hacks only if the person is standing in an area below a certain light level, essentially alerting the Grue that they've left the safety of the light and thus are likely to be eaten by a Grue.

**Comment by Armadingus** [comment]
Thought it would be realistic since we also have invisible pathogen clouds appear on players when they are diseased.

**Comment by Eneocho** [comment]
> Thought it would be realistic since we also have invisible pathogen clouds appear on players when they are diseased.

Something like the scent mechanic in CDDA? I like it.

**Comment by Hinaichigo** [comment]
One thing I think that could be interesting for the tension aspect of it is, players knowing grues can see through walls would give that uneasy feeling that there could be a grue watching them in the darkness on the other side of the wall. "I can't see them but maybe they can see me" type of tension. Gives an additional level of asymmetry to it aside from just being able to see in the dark.

Also it would let the grues position themselves better to be there lurking whenever a player ventures into the darkness without a light. And, combined with their faster movespeed, help them avoid being hunted down, letting them escape in the darkness more often. Along similar lines, I've been considering the ramifications of a "grue blink" type spell that would only work in darkness and would teleport them into another random, or maybe designated, dark tile within a certain radius, helping them vanish into the shadows more easily.  

If it seems like this, or the "grue blink", would make them too overpowered I think more positioning ability could be offset with nerfs in other areas. But from what I understand usually grues currently get hunted down and slain pretty fast as is.

Generally I think one direction to consider is to give the grues the upper hand in terms of situational awareness and positioning, making them seem more "omnipresent" and keeping their prey guessing where they might be, while still being unable to deal with bright areas.

**Comment by Cartlord** [comment]
The only problems with grues are their slow start and their weakness to light tiles, this fixes neither

**Comment by Eneocho** [comment]
If shit hits the fan with this we can just revert it, lets try it out.

**Comment by Cartlord** [comment]
But who will bother to revert it, instead of just bitching about it? I think you are overestimating the drive of our coders.

**Comment by Eneocho** [comment]
> But who will bother to revert it, instead of just bitching about it? I think you are overestimating the drive of our coders.

It's literally 3 clicks to get a revert PR going. Click on the merged PR, scroll to the bottom, click on the revert button then click on the pull request button.

**Comment by Blithering** [comment]
Thematically, I think grues shouldn't be tracking people wandering the lit halls. They're the scary thing in the dark, and being limited to the dark is important.

**Comment by Hinaichigo** [comment]
Maybe it's a bit controversial and there's decent counterpoints so let's hold off on this for now?
Please do let me know how you think grues can be improved at #31969.

**Pull request closed without merging**
