### PR TITLE
Gatling laser: Safe spawn

### PR DESCRIPTION
**Pull request by Securitymain**
[content]
## What this does

Adds the rusty gatling laser to the list of possible weapons in safes
This version can't  have its cell swapped and deals less damage (10 instead of 15)

## Why it's good

I think it fits well with the rest of the items in there

## Changelog

:cl:
 * rscadd: Add gatling laser to safes

### CODE REVIEW

**Comment by Blithering** [comment]
I'd say it might be a bit strong for a safe spawn, even the energy axe spawn in there had to be a nerfed subtype. Maybe have the safe one have the battery compartment jammed shut so it can't be reloaded?

**Comment by Securitymain** [comment]
The emojis have spoken, so it shall be

**Comment by Securitymain** [comment]
Damage from 15 to 10
Can't swap cell

**Comment by Kurfursten** [comment]
If you update this branch it will show the correct diff instead of 19 files

**Pull request merged**
