### PR TITLE
Buffs roentgen energy uranium content

### PR DESCRIPTION
**Pull request by ghost**
[tweak]
Mainly changing uranium content to 15u from 3.6, now beating the Discount Dan chcolate bars containing 8u.
:cl:
* tweak: Roentgen energy drinks are now much more worth a premium coin to drink.

### CODE REVIEW

**Comment by DamianX** [comment]
not great

**Comment by ghost** [comment]
> not great

You still need a coin to get it, just felt like giving it more of a reason.

**Comment by DamianX** [comment]
not terrible

**Comment by BomberBro** [comment]
dislike seeing the reference removed

**Comment by Dacendeth** [comment]
It's 3.6 for a reason.

**Comment by ghost** [comment]
> dislike seeing the reference removed

wait wha

**Comment by Eneocho** [comment]
> 
> 
> > dislike seeing the reference removed
> 
> wait wha

https://www.youtube.com/watch?v=Mg5HOnq7zD0

**Comment by Eneocho** [comment]
It should keep the 3.6u of Uranium but have another thing to make it worth buying.

**Comment by Eneocho** [comment]
Perhaps it has the potent serum from potent hams?

**Comment by ghost** [comment]
Added the reference back, sorta

**Comment by BomberBro** [comment]
dunno about radium, that stuff completely bricks your immune system and loads you with toxin damage. it'd make the drink a noob trap

**Comment by DeityLink** [comment]
Radium only bricks your immune system if you happen to have a disease at the same time.

**Comment by jwhitak** [comment]
Change the PR description, you're changing the 20u sport drink and adding a whole new radium ingredient for whatever reason?

**Comment by Eneocho** [comment]
Don't like the sports drink nerf. It's supposed to be an energy drink. Where's the electrolytes?

**Comment by Eneocho** [comment]
What if it had 36u of uranium? It'd keep the reference (sorta) and would kinda be worth the coin, since they're a rarity. (Besides, purchasing enough danchocos to get 36u uranium is cheaper than purchasing a coin for the roentgen, making it an alternative for ease of acquiring, at the cost of higher cost).

**Comment by Kurfursten** [comment]
Not enough support

**Pull request closed without merging**
