### PR TITLE
New drunkness camera effect

### PR DESCRIPTION
**Pull request by Zth--**
edit:done

special thanks to @Shadowmech88 and @Reviire who helped me dig through this thing

https://streamable.com/k4e4u

:cl:
 * tweak: New drunkness camera effect

### CODE REVIEW

**Comment by Kurfursten** [comment]
Nice. Always thought it was a little weird you'd go straight from "I feel nothing" to "Can't pronounce a sentence, dying of toxins"

**Comment by Zth--** [comment]
Spot a nasty bug, will fix tomorrow

**Comment by ihadtoregisterforthis** [comment]
I can already see security slurring and getting robotic livers to get those extra two tiles of vision

**Comment by ghost** [comment]
I think this is really cool, thanks.

**Comment by Chazach** [comment]
this is fucking ass to play with, makes it absolutely fucking impossible to do anything after like 5 sippies

**Comment by Zth--** [comment]
sippies of what?

**Comment by ghost** [comment]
This is fucking ass to play with
I love it

**Pull request merged**
