### PR TITLE
Civilian's Delight

### PR DESCRIPTION
**Pull request by Kurfursten**
- Fully tested
- Fully sprited (includes 14 new sprites for HE lighting)

---

Too long have we suffered under the lash of the Engineering and Science departments -- languishing as they get new features. Rise, Civilians!
- New High Efficiency bulbs (2 boxes) now spawn in the Janitor's closet (more can be ordered from cargo at 2x the price for 2/3 the boxes of normal lights). These bulbs use 1/4 the energy and can keep those high stress areas like main hallway and arrivals running much, much longer.
- Who needs science? The autolathe now produces all tier 1 components.
- The Bartender closet now contains a vial of 25u "Black Food Coloring". When placed in any drink container, ANY amount of this reagent will cause it to be impossible to examine for contents. Placing it in a drinking glass causes it to become an International Drink of Mystery. When transferred to a non-drink container (e.g.: bottle or beaker), it reveals its true nature. Still possible to scan with a reagent scanner.
- NT scientists have reduced the weight and broken access of coinboxes, they can now be properly held in one hand and opened.
- In a stunning double-breakthrough, NT researchers have developed a new "used recharge pack". Produced when you insert 4 sheets of cardboard to a vendor before disassembling, the used recharge pack contains all the remaining contents of the vendomat! Now you don't have to waste everything inside if you want to scan the circuitboard or switch out the vendor type.
- Shaft Miners and Cargo Technicians no longer have QM Office access.
- Nitrogen tank moved to the bottom of O2 lockers so that Oxygen tanks are easier to grab. Gas the Vox: race war now.

### CODE REVIEW

**Comment by SkowronX** [comment]
changelog!

**Comment by ComicIronic** [comment]
>When hacked, it also produces tank transfer valves (at an exorbitant 40,000 metal 20,000 glass)

ABSOLUTELY NO

**Comment by AutismSpider** [comment]
tank transfer valves

This better be emag thing only the 6 round start ones can rip the station in two and cost of 40k metal and glass is a fucking joke when you can ask engi borg to spit out free glass and metal

**Comment by ComicIronic** [comment]
>This better be emag thing only

This better be removed.
Even for antags, there should be NO WAY to get more transfer valves.

**Comment by Kurfursten** [comment]
@ComicIronic I don't like that we have magic items anywhere that can't be produced (other than antag uplink items for obvious reasons). That's why con/decon has been a major project of mine.

But I'd rather get the rest of the PR pushed through and argue about that later, so I'll revert it off of this PR.

**Comment by ComicIronic** [comment]
>I don't like that we have magic items anywhere that can't be produced

This is a case of too bad. Tank transfer valves are very deliberately unobtainable, which is why there's a server rule against doing things like spacing them or moving them to the RD office.

**Comment by 9600bauds** [comment]
That makes absolutely no sense and leads to powergaming, as evidenced by having to make server rules against moving them, or being immediately able to tell if the bombing was a Science antag or not depending on whether the TTVs are still there.
Magic unique items are bad. It's a goddamn valve, too, it's not like this is some magic bluespace crystal magic gas transfer wand.
Having TTVs be limited is, at best, an ugly and illogical bandaid fix to balance bombs.

**Comment by Kurfursten** [comment]
@9600bauds Listen -- I agree with you on everything you've said, but I just want to get this PR through. Please start a separate Issue (or if you want to make it a PR, I will GIVE you my code, it was a very small change). Discuss it there. Let's just discuss the remainder of this PR here.

**Comment by Probe1** [comment]
Well balance bombs then instead of making them worse.

**Comment by Kurfursten** [comment]
@d3athrow Read full commit list and IRC

**Comment by ririchiyo** [comment]
There will be no new additional tank valves that will be generated. The only other acceptable solution is to heavily nerf the bomb cap even more if you want to have more of them on the station. This is final.

**Comment by Kurfursten** [comment]
Closed, continue discussing bombs here if you want

**Comment by Iamgoofball** [comment]
>daring to go up against the chicken

**Pull request closed without merging**
