### PR TITLE
Inflatable Shelter

### PR DESCRIPTION
**Pull request by Kurfursten**
shelter

I actually had this sprite laying around since March but never got around to coding it.

Fludds are part of the game, but they're not very interactive and wipe out the crew who don't have suits. The inflatable shelter gives you a chance to survive -- in a crippled sense -- until rescue comes. Basically, this renders you a sitting duck. But a live duck.

**Pros**
* Contains its own air, allowing you to survive a catastrophic atmos incident
* Injects you with a small amount of medicine to stabilize
* Can be activated (click while inside) to package up all your contaminated clothes in wrapping paper so that you aren't poisoned by them
* Can drag around people inside

**Cons**
* Takes 10 seconds to get out (but can be popped with damage or deflated from the outside in about 1 second like any other inflatable)
* Also injects 3u Soporific, which will make you sleep for about 10 seconds
* Have to stagger your way to a fire alarm in a fludd

Bonus features
* The sprite updates if you opt to have your clothes packaged, show off your briefs
* Examine to see the name of who is inside

🆑 
* rscadd: Firealarms now contain inflatable shelters. Once inflated you can climb in to seek refuge from an atmos incident. Be wary that the anesthetic gas inside will both heal you and cause you to pass out briefly.

### CODE REVIEW

**Comment by tolan1** [comment]
Where should these spawn / be obtained from? Putting them in inflatables boxes would be redundant because the jobs who get those have ample protection. Maybe 1 in each o2 locker?

Also, perhaps they should somehow self-deploy upon detecting an uninhabitable atmosphere. Just keep one in your pocket if you hear the AI is rogue, that way you get at least some time. Of course, that should be a toggle so you don't get fucked over.

**Comment by DrSnips** [comment]
Actual fire lockers are kinda scarce since most of the firesuits in maint are laying on racks rather than lockers. Likely another item to go in o2 locker toolboxes with a decent chance like 30%. The current rng pool of items is 5% for an airbag that stop you from being zased once which is nice and 15% for a rad patch that tells you "your insides are now bacon" a little too late for it to matter much. I'd like to see all of these things used a bit more often but since they spawn so rarely most people forget they exist.

**Comment by Kitfox88** [comment]
Could always add them to people's standard survival panic kit you spawn with, if you'd like them to be used more often? Maybe have it be chance based like spawning in the lockers if having them all every time would be ~unbalancing~

**Comment by Inorien** [comment]
feels more like they'd belong in a defib-like cabinet in the hallways, which unlocks/autodeploys when a plasma alarm is tripped

**Comment by ShiftyRail** [comment]
>Also injects 3u Soporific, which will make you sleep for about 10 seconds

Why ?
I'm okay with the rest

**Comment by Kurfursten** [comment]
Lore explanation: to prevent victims from going into shock

>to_chat(user,"<span class='warning'>You feel calmed by the anesthetizing gasses inside the shelter.</span>")

Balance explanation: You get the free kelo and pepto every time you deploy it, so you could just use the shelter for a ghetto healer if there wasn't some drawback. To someone legitimately trapped in an emergency situation, the sleep toxin will be a slight annoyance but nothing more, but it would make it super annoying to repeatedly use the shelter without a break. Also just as a balance thing, so you don't hop into a shelter in the middle of combat in hopes of blocking a taser or something. Basically, I'm erring on the side of keeping shelters "balanced" enough that they aren't going to trivialize what is rightfully a dangerous situation.

**Comment by Blithering** [comment]
Maybe emergency toolboxes could contain this as a third option if they don't have rad patches or the emergency zas bubble

**Comment by strawberrytan** [comment]
What if it was an alternative to the O2 kits in the lockers

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Clearly what we should do is let you climb inside fire extinguisher cabinets for this effect

**Comment by SonixApache** [comment]
very cute

**Comment by Kurfursten** [comment]
In general O2 lockers seem like a fairly natural choice, but remember that a lot of departments don't have O2 lockers anywhere near them. Like sec, or the front of cargo.

I think I like the idea of having them dispensed from fire alarms. You know, those old machines that no one pays attention to except clowns ever since modern air alarms were added. Plus you could order extra from cargo (no one would do this of course, but the option would be there).

**Comment by Durgen** [comment]
can you use these in space?

**Comment by Pathid** [comment]
Seems so.

**Comment by Kurfursten** [comment]
I hadn't even thought of that. Yeah, I guess you could use it in space. Should I disable that?

**Comment by Kitfox88** [comment]
I like it, the idea of being stuck in a bubble floating through space hoping that telesci can drag your dumb ass back without the dying part. Also it makes me think of the ejector bubbles from the speed racer movie and those owned.

**Comment by Blithering** [comment]
if you have a gun on you, can you fire out of the shelter without popping it?

**Comment by Irradiation** [comment]
@Kurfursten Instead of soporific, you could always give them some Tramadol, which lets people recover from shock.

**Comment by Intigracy** [comment]
Having them grabbable from fire alarms is a neat idea if you make it one per and make it obvious when it's been taken.

**Comment by Kurfursten** [comment]
@Irradiation That wouldn't be a drawback though, would it? I mean, I could add tramadol to the chem mix. I guess I can get some opinions here, do people think the STOXIN is not necessary to discourage tent hopping?

@Blithering You cannot fire out of the shelter. You can fiddle with your equipment like you can while in a locker, but that's all. Tasers do not pop the shelter.

@Kitfox88 I don't think you could T-sci someone out without great coordinated timing from them to deflate because the structure is anchored. You *could* remote rescue someone with the subspace tunneler though. If there's enough support for it I could maybe change the structure to be moveable, though this would require some airflow overrides.

@Intigracy I'll throw together a fancy new sprite for them

**Comment by Irradiation** [comment]
Am I reading the code correctly in the sense that you only get one dose of pepto, kelotane & sleep toxin? If that's the case, then I don't really mind sleep toxin beign a drawback. But put some Tramadol into it, that's always good.

**Comment by Kurfursten** [comment]
That's correct. Only the person who inflates the shelter for self use gets the injection.

There has been some murmuring here and in the discord that it might be fun if you could cram other people into a shelter by climbing in once it's already deployed though, which I have given some thought. It wouldn't be terribly hard to code. Although unless someone wants to get really stylin with overlay offsets, it would still only show the first person in the shelter.

**Comment by Blithering** [comment]
On the subject of the chems, I would say leporazine is more useful than kelotane, fires tend to heat you up to the point where you take continuous damage minutes after leaving the area, so people would still be burning to death inside the shelter despite its heatproofing

**Comment by Kurfursten** [comment]
Wouldn't leporazine "lock in" your temperature as hot? I haven't read its code.

You do actually make me think of something though: I need to make sure the shelter *actually extinguishes you*, which seems important since you can't resist to stop/drop/roll inside.

**Comment by Blithering** [comment]
After testing, leporazine reset my temperature back to normal as soon as it was ingested, making it ideal for this situation.

**Comment by Ratvar** [comment]
Can I use it every time I get lasered/poisoned, when I am out of combat? Sounds like a free heal.
Maybe make it usable ONLY if there's atmos problem (and you are not in atmos protective thick gear), and remove sleepy part?
Or make them break after 1-3 uses?

**Comment by Kurfursten** [comment]
Basically yes. Currently it gives you 6u of each which heals 30 burn 30 toxin. Following @Blithering 's suggestion I am thinking of dialing it back to 4u each (20/20) and adding 1u leporazine.

I thought of making them one-use originally, but then I thought "well, then people will just grab another to use next time". I think the sleepyjuice is elegant as a solution because most of the time if you are actively being hunted after a laser fight, going to sleep in a big yellow obvious box is the last thing you want to do. If you're a vampire you probably want to jaunt to your maint coffin not this. If you're wizzyman you are probably being hunted with brute shotguns due to no EMP and bleed memes.

**Comment by Durgen** [comment]
@kurfursten regarding use in space

It would be funny if they weren’t anchored and started moving in a random direction when inflated so they could be used for super ghetto space exploration

**Comment by Kurfursten** [comment]
Hmm, the trouble with taking out anchoring is a tendency to slide around. Still, I can look into taking out anchoredness. It's a little bit more involved than usual because of special behaviors inflatables have.

Plans for next version
* ~~Remove anchoring~~
* ~~Change chemical composition (reduce medicine, add leporazine)~~
* ~~Dispense from fire alarm (limit one)~~
* ~~New fire alarm sprite (with and without shelter)~~
* ~~Allow more than one person to climb into the shelter~~
* ~~Allow dragging an unconscious victim inside~~
* ~~Expand top sprite slightly so face is visible~~
* ~~If human calls update_icon call the shelter's update as well (mostly for extinguishing or falling sideways)~~

**Comment by MusgardTiger** [comment]
i think you should make it a one use item and put it in every crewmembers survival box. fire alarm idea is cool but in a suprise blasma fire situation (which i think most fires are in this category) you have few seconds to react to either leave the area, climb in disposals bin or don your rig suit otherwise you'll die within seconds. i don't think people can survive the short trip to a fire alarm unless they are really close to it.

**Comment by DamianX** [comment]
> in every crewmembers survival box

we hugbox now

**Comment by MusgardTiger** [comment]
@DamianX another quality comment

**Comment by DamianX** [comment]
Allow me to elaborate.
Before (this means before a PR with your suggestion!): Plasma fire will kill you unless you have a hardsuit.
After (this means after a PR with your suggestion!): Everyone can survive any atmospheric condition by just unzipping this thing from their survival box.

This is so ridiculous that at first I thought you were memeing, and I'd be surprised if people are going to be okay with it given how much importance they seem to give to players' ability to effectively antagonize.

I'm totally okay with having these in fire closets/fire alarms but I think your idea is retarded.

**Comment by Blithering** [comment]
how about making it deploy directly from fire alarms, and then pack away back into it when deflated? Prevents people grabbing them for themselves round start and keeping them on their person

**Comment by Kurfursten** [comment]
I actually think that's an interesting idea.

**Comment by MusgardTiger** [comment]
hugbox implies that there is no conflict, there is no conflict with plasma fires. it is literally the most boring thing you can do to "effectively antagonize", it is a shuttle caller borefest where people in rig suits waiting in escape arm and ghosts waiting for shuttle to reach centcomm.

**Comment by Irradiation** [comment]
What Mustard said, except depending on the nature of the plasmaflood, only the guy in an Atmos suit will survive the station bacon caused by THE HUMANS ARE DEAD, THE HUMANS ARE DEAD. WE USED POISONOUS GASSES TO POISON THEIR ASSES.

**Comment by SonixApache** [comment]
i agree with damian and blithering here
mobile 'no-plasma' boxes will be pilfered by powergay

**Comment by MusgardTiger** [comment]
If the only source for these items are crew survival boxes and they are one use items I don't think they will be pilfered by powergay, at least not to any significant extent. I just worry that this is going to be a feature that won't see any use due to how much damage a sudden spike in heat, pressure and toxins do to you, people won't survive the trip to the hugbox. 

That and if I understand this right these will be anchored items so in order for them to pop out of fire alarms I think you'll have to do some extensive edits to maps whats with a lot of fire alarms being behind tables, machinery and shit.

**Comment by Intigracy** [comment]
The handheld item would be dropped from the alarm, you can deploy it anywhere.

**Comment by Intigracy** [comment]
wait nvm just read the comment that was in response to

**Comment by Blithering** [comment]
>you'll have to do some extensive edits to maps whats with a lot of fire alarms being behind tables, machinery and shit.

You could avoid that by having the shelter inflate on the tile of the person that pulled the alarm rather than the tile of the alarm itself

**Comment by Inorien** [comment]
I really dont like the idea of _everyone_ having a personal anti-blasmaflud/fire defense bubble on them. Plasma fires are meant to be dangerous, catasrophic situations - giving everyone a get-out-of-fire-free card is like giving everyone EVA access and endless hardsuits in case there's a breach, if not more lenient. If you were to give everyone some little something to protect against plasma floods, it should be a one-use spray bottle to clean the plasma off you so you don't need to go to the washers/showers. If it's a fire, then you're fucked - I just don't think such a situation is supposed to be survivable. It's true I'm generally of the opinion things should be harder for no reason (for instance I don't think the pinpointer should just instantly locate shunted APCs  on malf) but removing 99% of the danger of a plasma fire just seems daft and trivialises them.

**Comment by Kurfursten** [comment]
I don't think there's any danger that *this* PR will ever get to a state where it's inside your starting box. I really like the idea of having one per fire alarm because those are common but also underused and just getting to one of those in a room is not necessarily an easy proposition in a blasmafire. I'm also inclined to like the idea of them being static and deploy into/out of fire alarms so they can't just be trivially stolen for healing tents. Those are the two most likely propositions on the table.

This will update soonish, I'm finishing up the supermatter monitor then this will get the attention it needs.

**Comment by DrSnips** [comment]
I agree with the one per fire alarm but having to be at one to get it while the fire is going seems a bit odd. Since you can't use it until a fire happens to trigger the fire alarm that means you have to wade through a fire in order to prevent yourself from being in a fire. Seems a bit backwards in design. Maybe you could have them drop manually from a fire alarm by opening a fire alarm and applying a tool?

**Comment by Blithering** [comment]
>you can't use it until a fire happens

That would be the intended purpose, they're meant to be emergency shelters for people trapped in an area that's on fire to survive in until help comes. The chemicals administered and clothing packaging thing specifically help those who have already been exposed to the fire. At least with them being tied to the alarm you know for sure the shelter will be in the area it's needed rather than in the pocket of a guy who took it just in case

**Comment by DrSnips** [comment]
Well if the chem amounts get changed and are weaker then it's less helpful to those who need to run into the fire in order to use it. I'm still for it being in O2 toolboxes at 25%-15% or something like that if the chem part of it got lowered because they were more common.

**Comment by Blithering** [comment]
Why would someone who isn't in the fire need to run into it to get into the shelter in the first place?

**Comment by Hugh-G-Rection** [comment]
With anchoring removed this will be a fun way to safely get crewmembers to the shuttle in floods and singulooses, as right now only option is the handteleporter. Also it will be fun to bully bubbleboys.

Add some way for them to be taped/sealed shut so the person can be kicked around with no way out without popping it, will be fun for bullying or a way for changelings and vampires to save people as snacks, or at the very least a supertough antag version for a portable gaybabyjail.

**Comment by Kurfursten** [comment]
The much anticipated update is here.
* Chems lowered to 4/4 (heals only 20 each) but added small amount of tramadol and leporazine
* No longer immediately forces you in when you deploy it. Instead, you can climb in (2 seconds).
* You may also grab someone to load them in (2 seconds). This extends to all living things like Ian, too.
* Any number of people can hide inside. They are all listed when examined, but only the "top" person gets displayed.
* Can now be pushed and pulled about. **No longer deflates with ctrl click for this purpose**
* Will block airflow like an unanchored window can
* Available from fire alarms, can be reloaded by using the same UI or by attacking the fire alarm with the inflatable in hand
* Building a new fire alarm creates an "empty" air alarm instead of creating a free inflatable
* Increased the window size slightly so that you can see your face better. Also added new fire alarm sprites.

I do like @Hugh-G-Rection 's idea but maybe that's for a separate PR down the road. I could see that being a bonus use for glue though.

**Pull request merged**
