### PR TITLE
One way window fixes

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[bugfix]

## What this does
similar to #31415, makes the turfs obscured by one-way windows disallow right clicking to view contents beneath. does not affect turf one way window is on yet, sadly (and breaks with thermal mobs, but thankfully only on the turf viewed with them) (and also breaks with mesons)
also fixes the obscure overlays not going away when it gets deleted, and removes excess calls of view()  while replacing the rest with oview() to aid performance, along with code cleanup here and there.

## Why it's good
makes them a bit less janky, since they do show up on maps

## Changelog
:cl:
 * bugfix: Destroying a one-way window now makes its blocked line of sight go away more consistently.
 * bugfix: Players can no longer right-click to see what's behind one way windows.
 * bugfix: Thermals now allow mobs to be seen behind one way windows.
 * bugfix: Mesons now allow mobs to see the turf behind one way windows.
 * bugfix: Only one-way windows facing the viewing mob cut into the view block now.

### CODE REVIEW

**Comment by Exxion** [comment]
There are one-way windows on maps in actual use? They're supposed to be forbidden. I don't know why they're even still in the code.

EDIT: Island and Dorf have them, apparently.
To be clear, I wish they were a feature we could actually have, but it is completely impossible in BYOND to make them work properly, and the one awful hack we can do to make them *kind of* work is really slow

**Comment by SECBATON-GRIFFON** [comment]
> EDIT: Island and Dorf have them, apparently.


in much more places actually, lowfat bagel is another

> To be clear, I wish they were a feature we could actually have, but it is completely impossible in BYOND to make them work properly, and the one awful hack we can do to make them _kind of_ work is really slow

how slow exactly? i feel like excessive use of view() might be why, i'll work on improving it some time

**Comment by Exxion** [comment]
You're right, I missed Lowfat Bagel and Synergy. I also highly doubt there's a way to get them to work with less use of `view()`, because Lummox absolutely refuses to add a `can_see()` proc. Please don't mention the `can_see()` proc defined in our codebase and used in like one place. It doesn't actually work.

**Comment by SECBATON-GRIFFON** [comment]
> I also highly doubt there's a way to get them to work with less use of `view()`

well i just did in those last 2 commits, tested working and all

**Comment by SECBATON-GRIFFON** [comment]
nevermind i didnt see the ```break``` in that loop, so i only really removed one. still something

**Comment by SECBATON-GRIFFON** [comment]
aaand now ALL calls of view() are gone in the proc, testing working near almost the same

**Comment by Exxion** [comment]
I'd profile it to verify that it's actually faster without any usage of `view()`, since I'd expect `view()` to be faster than equivalent softcode

**Comment by SECBATON-GRIFFON** [comment]
> I'd profile it to verify that it's actually faster without any usage of `view()`, since I'd expect `view()` to be faster than equivalent softcode

will update the OP with screenshots of the profile when i can

**Comment by SECBATON-GRIFFON** [comment]
> I'd profile it to verify that it's actually faster without any usage of `view()`, since I'd expect `view()` to be faster than equivalent softcode

i think it was about the same, so i changed it back and decided to just keep the ones i could remove.

**Comment by Eneocho** [comment]
There's a weird window issue I've seen floating around recently, where the windows don't return to their regular disconnected icon after disconnecting it from a set of windows, like in pic related:
image
Not sure what causes it, but since you're fixing windows, could you check it out?

**Comment by SECBATON-GRIFFON** [comment]
> There's a weird window issue I've seen floating around recently, where the windows don't return to their regular disconnected icon after disconnecting it from a set of windows, like in pic related: image Not sure what causes it, but since you're fixing windows, could you check it out?

once again, unatomic

**Comment by Eneocho** [comment]
[bugfixes don't need to be atomic](https://ss13.moe/wiki/index.php/Getting_Your_Pull_Accepted#5._Pull_Requests_Must_Be_Atomic)

**Comment by Exxion** [comment]
It's still a completely unrelated fix. Why include it?

**Comment by Eneocho** [comment]
He was fixing one way windows, my issue is tangentially related, so I suggested it. If he doesn't want to he doesn't need to, I'm just clarifying that bugfixes don't need to be atomic.

**Comment by nervere** [comment]
Apparently SECBATON-GRIFFON is actually repo-banned (see image) so I'm gonna close this so it doesn't stay up forever.
If someone wants to bring this PR back from the dead, please do.

image

**Pull request closed without merging**
