### PR TITLE
fix baguloth and make it unescapable

### LINKED ISSUE #13961: Baguloth runtime
``` 

[21:18:59] Runtime in datumpool.dm, line 70: code/__HELPERS/datumpool.dm:70:Assertion Failed: D
proc name: returnToPool (/proc/returnToPool)
usr: Frank McRib (jameswbigmac) (/mob/living/carbon/human)
usr.loc: The floor (315, 249, 1) (/turf/simulated/shuttle/floor)
src: null
call stack:
returnToPool(null)
Bag of Holding (/obj/item/weapon/storage/backpack/holding): Destroy()
qdel(Bag of Holding (/obj/item/weapon/storage/backpack/holding), 0, 0)
Bag of Holding (/obj/item/weapon/storage/backpack/holding): singularity act(1, the gravitational singularity (/obj/machinery/singularity))
the gravitational singularity (/obj/machinery/singularity): consume(Bag of Holding (/obj/item/weapon/storage/backpack/holding))
the gravitational singularity (/obj/machinery/singularity): Crossed(Bag of Holding (/obj/item/weapon/storage/backpack/holding), 0)
Bag of Holding (/obj/item/weapon/storage/backpack/holding): forceMove(the floor (315,249,1) (/turf/simulated/shuttle/floor), 0, 0)
Frank McRib (/mob/living/carbon/human): u equip(Bag of Holding (/obj/item/weapon/storage/backpack/holding), 1, 1)
Frank McRib (/mob/living/carbon/human): drop from inventory(Bag of Holding (/obj/item/weapon/storage/backpack/holding))
Bag of Holding (/obj/item/weapon/storage/backpack/holding): Destroy()
Bag of Holding (/obj/item/weapon/storage/backpack/holding): Destroy()
qdel(Bag of Holding (/obj/item/weapon/storage/backpack/holding), 0, 0)
Bag of Holding (/obj/item/weapon/storage/backpack/holding): singulocreate(Bag of Holding (/obj/item/weapon/storage/backpack/holding), Frank McRib (/mob/living/carbon/human))
Bag of Holding (/obj/item/weapon/storage/backpack/holding): attackby(Bag of Holding (/obj/item/weapon/storage/backpack/holding), Frank McRib (/mob/living/carbon/human), "icon-x=20;icon-y=19;left=1;scr...")
Frank McRib (/mob/living/carbon/human): ClickOn(Bag of Holding (/obj/item/weapon/storage/backpack/holding), "icon-x=20;icon-y=19;left=1;scr...")
Bag of Holding (/obj/item/weapon/storage/backpack/holding): Click(null, "mapwindow.map", "icon-x=20;icon-y=19;left=1;scr...")

```

NO SINGULO OCCURED
WE DEMAND A REFUND

### PR DESCRIPTION
**Pull request by gbasood**
Fixes #13961
~~Also cleans up the baguloth check slightly~~ or not
For the record the bag was nullspacing itself 

Also:
🆑 
 - bugfix: Baguloth lives again.
 - bugfix: You can no longer escape Baguloth's wrath.

### CODE REVIEW

**Comment by 9600bauds** [comment]
While you're at this
Can you PLEASE remove the `Knockdown(10)` and nonfunctioning `user.throw_at(T, 10, 5)` and just call `T.Bumped(user)` or `T.consume(user)`

Right now people can baguloth and survive by being on creatine/getting someone else to drag them away

**Comment by gbasood** [comment]
I think you mean `singulo.Bumped(user)`?
T is turf so unless I misunderstand how singulos work then I'll do that

**Comment by 9600bauds** [comment]
whoops yeah for some stupid reason I got T confused for the singularity object

**Comment by 9600bauds** [comment]
thank

**Pull request merged**
