### PR TITLE
Changes sec glock sprites.

### PR DESCRIPTION
**Pull request by Intigracy**
| Old | <b>New</b> |
| --- | --- |
| old | glock |
| oldempty | glock_empty |
| oldfancy | fancy |
| oldfancyempty | fancyempty |
| old45 |  |
| old45white | 45p |
| old45blue | 45r |

Sprite base taken from #11487 and modified from there.

### CODE REVIEW

**Comment by SonixApache** [comment]
I'm okay with this.
Edit: Actually, change the description (and classname) for the wooden one.
Edit Edit: And change the barrel of the white one back to black, man, what the fuck. Slide is fine, barrel and chamber aren't.

**Review by SonixApache — APPROVED** [review]

**Comment by Exxion** [comment]
(The white one is based loosely on the HL2 pistol)

**Comment by SonixApache** [comment]
The HL2 pistol being a H&K USP Match, this resembles a normal USP pretty well.

**Review by PJB3005 — APPROVED** [review]

**Comment by Blithering** [comment]
Hooray!

**Pull request merged**
