### PR TITLE
change range to trange, because it only wants the turfs not all objects.

### PR DESCRIPTION
**Pull request by eswordthecat**

### CODE REVIEW

**Comment by PJB3005** [comment]
Er, `range()` (and `view()`) in that sort of situation only return turfs, I don't think this matters (though I don't even know what `trange()` is).

**Comment by eswordthecat** [comment]
Format: 
range(Dist,Center=usr) 
Returns: 
A list of objects within Dist tiles of Center. 


Format: 
view(Dist=5,Center=usr) 
Returns: 
A list of visible objects within Dist tiles of Center. 


Format: 
block(Start,End) 
Returns: 
The list of turfs in the 3D block defined by Start and End (inclusive). 

trange uses block to get the start and end arguments

**Comment by eswordthecat** [comment]
Also for with a type (turf) declared is fetching just the type (turf) but it doesn't mean view or range doesn't return other objects.

**Comment by PJB3005** [comment]
No, `range()` and `view()` in this situation actively only look for turfs, it's an optimizations within BYOND.

**Comment by eswordthecat** [comment]
https://raw.githubusercontent.com/rastaf0/-tg-station/faels/code/LIGHTING/performance_notes.txt

The more you know.

**Comment by clusterfack** [comment]
Those notes are sooo 'meh'

**Comment by PJB3005** [comment]
Yes I was looking for that to link it here.

Also IIRC `block()` is slow as balls so this might just make it slower, can you profile it?

**Comment by eswordthecat** [comment]
if block is so slow why not use range (because you said it will only return pure turfs) instead of trange at explosions

**Comment by PJB3005** [comment]
Hey I didn't make explosion code.

**Comment by eswordthecat** [comment]
I know but there's a reason why trange created instead of using range on it

**Comment by PJB3005** [comment]
Okay we can argue all day, but instead, could you profile it to see which is better?

**Comment by PJB3005** [comment]
Wait I just realised from that text file that `range()` doesn't have the optimization...

**Comment by eswordthecat** [comment]
Even lummox said to use define instead of function because it cannot be optimize completely.

**Comment by eswordthecat** [comment]
When applicable.

**Comment by PJB3005** [comment]
I'm doing some profiling, we'll see which is best.

**Comment by PJB3005** [comment]
Okay I did some profiles, and `trange()` is the winner, good to know.

**Pull request merged**
