### PR TITLE
Adds new cult mob sprites that nobody asked for.

### PR DESCRIPTION
**Pull request by GoodG1448**
Could be of use if someone decided to actually code the mobs.
pic

Github is being a cunt, the phenol-plastic commit shouldn't be here.

### CODE REVIEW

**Comment by SirSkeleto** [comment]
dont make two different changes on the same branch

**Comment by GoodG1448** [comment]
It would be easier if I could just upload the file and make the pull request from there. All the new branches I make have all the other old 6 commits and that shit is impossible to delete. Hell, I can't even choose which commits I want in this PR and which doesn't.

**Comment by SirSkeleto** [comment]
just delete your fork

**Comment by GoodG1448** [comment]
Closing until my other PR gets merged to delete my fork.

**Pull request closed without merging**
