### PR TITLE
remove 'Donald Trump' from AI name list

### PR DESCRIPTION
**Pull request by gurfan**

### CODE REVIEW

**Comment by BomberBro** [comment]
Surprisingly added in #555 before this was ever a very political name

**Comment by ShiftyRail** [comment]
2valids2many
We just can't let the AI get the nuclear codes

**Comment by Kurfursten** [comment]
We have some of the best AI names. Really great names. And they want to take them away. Me? I wouldn't get rid of your AI names. If anything, I would add more.

**Comment by gurfan** [comment]
We are up BIG, but metaclubbers are trying to STEAL the PR election. We will never let them do it.

**Comment by Kurfursten** [comment]
Stop the emojis

**Comment by Eneocho** [comment]
We're going to build a Bar and Cargo is going to pay for it.

**Comment by xeroxemnas** [comment]
My aunt's name is Donald Trump. This PR is offensive.

**Comment by gurfan** [comment]
We won. We won by a LOT.

**Pull request closed without merging**
