### PR TITLE
Teleporter UI.

### LINKED ISSUE #4997: Way to see where a teleporter is going
we need one, the one that's not a telescience teleporter, by the way

### PR DESCRIPTION
**Pull request by PJB3005**
Resolves #4997

### CODE REVIEW

**Comment by CptWad** [comment]
ok :+1:

**Comment by PsiOmegaDelta** [comment]
You want to sanitize() the names to avoid the umulat y.

**Comment by clusterfack** [comment]
Oh, is that why the air alarms have that issue somtimes when displaying vent names? I never knew.

**Comment by Ephx1** [comment]
Would it be possible to have a cancel button?

**Comment by clusterfack** [comment]
Er, how would that UI need a cancel button? You aren't actually locked into anything from the look of it.

**Comment by Ephx1** [comment]
Oh nevermind, this new UI clears up the problem I was thinking of anyways, excuse my stupidity.

**Comment by clusterfack** [comment]
Trust me I said the EXACT same thing before he started making this

**Comment by PJB3005** [comment]
^ he did

**Comment by ririchiyo** [comment]
Did you remove the message that notified people when the destination was changed?

**Comment by PJB3005** [comment]
Yeah, because I couldn't figure out how to do it properly, I'll look into it though.

**Pull request merged**
