### PR TITLE
Wizard Spell: Feint

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds a new spell which grants the user a magic sword, then causes them to vanish, before reappearing three seconds later behind the target that was closest when the spell was cast.

The vanishing animation is exactly the same as ethereal jaunt, the idea being that you can trick your opponents into thinking you're running away, before appearing behind them and counterattacking.
The sword is a reskinned katana, so it has 40 force. It disappears if you drop it or attempt to equip it.

The icon for the spell is just a katana, because I couldn't think of anything else to make it.

Credit to @Arthurdentist for the original idea.

:cl:
 * rscadd: Added a new wizard spell which causes the wizard to equip a magic sword, vanish for a few seconds, then appear behind the target who was closest when the spell was cast..

### CODE REVIEW

**Comment by DamianX** [comment]
it doesn't say "nothing personnel kid"? 👎

**Comment by Shadowmech88** [comment]
If your opponents could be certain that you were casting feint instead of jaunt, it would hurt its effectiveness.

**Comment by sonime** [comment]
👌

**Comment by Exxion** [comment]
Also, strictly speaking, those are two separate but similar memes that people just often confuse

**Comment by Arthurdentist** [comment]
@Shadowmech88 Literally stealing my idea after I told it to you

smh

**Comment by Shadowmech88** [comment]
It seems I did.
I didn't remember where I heard it because it was a month ago when you came up with it.

**Comment by Blithering** [comment]
40 brute sword and a teleport to boot? Swordwiz is gonna be strong. 
Also obligatory SUMMON SWORDS WHEN

**Comment by ghost** [comment]
HOLY fuck

**Comment by sonime** [comment]
The best part is that admins can give the spell to clowns

**Comment by DeityLink** [comment]
>The icon for the spell is just a katana

`icon_state = "cultblade"`

🤔

**Pull request merged**
