### PR TITLE
Smooth Dark Shuttle Walls

### PR DESCRIPTION
**Pull request by JMWTurner**
smooth

:cl:
* imageadd: "Added smoothed dark shuttle walls to shuttle.dmi. I'll let the mappers decide when to use them."

### CODE REVIEW

**Comment by Exxion** [comment]
These look WAY better than the last time someone tried them

**Comment by JMWTurner** [comment]
Someone tried them before? It's not complicated, I replaced the pixels so the difference between those and the white ones looks just like the difference between image and image

**Comment by Exxion** [comment]
image
#5001

**Comment by JMWTurner** [comment]
oh dear

**Comment by Exxion** [comment]
The weirdest thing is that Skowron made those, and he's usually a good spriter. Maybe he was rushed.

**Comment by JMWTurner** [comment]
I think he shouldn't have tried going with something so original. People like what they're used to.

**Comment by JMWTurner** [comment]
Well here's a preview of the salvage ship with those sprites instead

image

**Comment by SkowronX** [comment]
Me old ones are poopy. Use deity's instead.

**Comment by Intigracy** [comment]
All this does is add the sprites.

**Pull request merged**
