### PR TITLE
Added a useless roid with useless ores for no real reason

### PR DESCRIPTION
**Pull request by AlphaBuffalo**
This is also a test to make sure if my smartgit is working. But if you guys like the roid I'll test it to make it works and we can have it. Here is a picture

dreammaker_2017-09-24_20-09-21

### CODE REVIEW

**Comment by MadmanMartian** [comment]
could cut off a little of that empty space, seems like the roid itself is only taking up a quarter of the given map, and even then it's towards the bottom. Also you may want to give it the vault autoarea so it doesn't do weird stuff

**Comment by AlphaBuffalo** [comment]
Oh, I see what you mean... I'll add it

**Comment by ghost** [comment]
goofball

**Comment by SonixApache** [comment]
are those

goof ores?

**Comment by Durgen** [comment]
This dilutes useful vaults

**Comment by Exxion** [comment]
What's wrong with that? Not *every* hunk of space debris should have extreme powergaming equipment on it.

That said, ores that can't even be refined into something useless might be a bit much

**Comment by SonixApache** [comment]
i honestly think this is 100% perfect as-is

**Comment by Exxion** [comment]
It would be better if the mineral sheets for these materials were uncommented so you could show off the spoils, but as it says in the file, that would clutter the ore processor menu for no good reason

**Comment by DamianX** [comment]
the obvious solution is to rewrite the ore processor ui

**Comment by Exxion** [comment]
Yeah but someone has to actually do it

**Comment by icantthinkofanameritenow** [comment]
This is literally for someone's testing smartgit. Congratulations, it works. Now hurry up and make something interesting instead of an empty rock full of useless crap.

**Comment by Shadowmech88** [comment]
An empty rock full of these ores could be nice if the ores could actually be turned into anything. Not even something useful necessarily, just anything at all.

Otherwise why bother mining them?

**Comment by FudgePucker** [comment]
Goon ores were a mistake on goon and is still an unfinished mess.

**Comment by SonixApache** [comment]
its cute

**Comment by DrSnips** [comment]
Why not make them children of the normal ore types and just look different so they process into useful ores? On top of that, maybe they make more or less sheets when processed into the useful materials?

**Comment by clusterfack** [comment]
Thanks goofball!

**Comment by small-boss** [comment]
the vault is as useful as goofball

**Comment by PJB3005** [comment]
@icantthinkofanameritenow not every vault has to be useful.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
You need to add the vault to the code here: https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/randomMaps/vault_definitions.dm

**Comment by ghost** [comment]
@icantthinkofanameritenow Wasn't your first vault a featureless rectangle full of overpowered crap?

**Comment by ghost** [comment]
>not every vault has to be useful

we already have lame vaults though
biodome is just a big botany
hivebot crash is only good for people with pods
icetruck crash has temp guns, you can probably already print some out by the time you find it
the one with two xenos has some ore deposits like any other roid and a spacesuit
http://ss13.moe/wiki/index.php/Vault_(map_element)
most of the vaults have cool things and only like 5-6 have powerful loot
as soon as people see this vault they're just going to go away and look for another

**Comment by SonixApache** [comment]
I don't think we have a lot of 100% useless vaults, I still think having one would be cute. Good trap for newfags.

**Comment by MadmanMartian** [comment]
I think the sheets for these ores are in stacks/sheets/mineral.dm

**Comment by PJB3005** [comment]
Yes but you can't smelt them.

**Comment by PJB3005** [comment]
Stale. Comment if you want it reopened.

**Pull request closed without merging**
