### PR TITLE
bleach kipper PR v.2

### PR DESCRIPTION
**Pull request by Arthurdentist**
_**ur an idiot something something learn 2 git**_

Remake of that classic and incredibly popular PR to celebrate the arrival of our new baby blue peacekeeper borgs.

Lets hope I didn't get merge conflicted again.

#13912

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
No conflicts, only Travis.

**Comment by Arthurdentist** [comment]
its because I did a hack job because im a hackfraud

**Comment by unusualcrow** [comment]
shit I just made a PR for actual bleach

**Comment by Arthurdentist** [comment]
I thought you were shitting on me but you actually did it.

AAAAAH

**Comment by ghost** [comment]
ok our bleaches should be fine it's nothing like yours

**Comment by Arthurdentist** [comment]
you know I spent ages fixing this merge conflict for that sodding valentine's day bar and now it just gets removed and im merge conflicted again.

man I can't stand git.

**Comment by SysadminJeroen** [comment]
@Arthurdentist It wouldn't be better if you were using SVN or any other revision control system.
What could help is if many icon files were split up into multiple smaller files.

**Comment by FudgePucker** [comment]
Wow that has to suck hard, your PR gets fucked for a meme PR, then your next PR gets fucked by the same meme PR being removed.

Pour out a forty for this PR 🍺

**Comment by Arthurdentist** [comment]
to be fair this PR is also a meme PR @FudgePucker so I hardly have any right to complain, im just not smart enough for git.

**Comment by FudgePucker** [comment]
I think you are selling your PR a little short.
It even comes with a chemical that turns people blue!
The second I saw this PR I thought up a hundred clown pranks and puns.
Poke someone with an autoinjector with it, then ask them "Are you having a rough day? You look pretty blue to me" then hit them with my bike horn.

**Pull request merged**
