### PR TITLE
runtime sprite transformation fix

### LINKED ISSUE #34505: Runtime transformed into espeon before methylin was fully injected.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
0593a00132f3333fb530cdc471a43b237fe2eceb

# Description
Title.
# Steps to Reproduce
Get Runtime.
Get syringe with methylin (5u methylin and 5u fluorine in this case).
Inject Runtime with syringe.
# What you Expected
For the chems to be actually injected and THEN she transforms.
# What Actually Happened
She just smelled the methylin and became espeon.

### PR DESCRIPTION
**Pull request by nervere**
fixes #34505

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Maybe the transformation check should be moved to somewhere like `Life()` or `on_reagent_change()` or something like that.
That way if methylin enters her system via something other than the syringe (like cryo) it will still work.

**Comment by nervere** [comment]
> Maybe the transformation check should be moved to somewhere like `Life()` or `on_reagent_change()` or something like that. That way if methylin enters her system via something other than the syringe (like cryo) it will still work.

Very good idea. I will change it to this when I get some time. Marking as draft til then.

**Comment by nervere** [comment]
Fixed, and handled via `on_reagent_change()` instead of `attackby`. Thanks again Hinaichigo for the suggestion.

**Comment by Hinaichigo** [comment]
Might also wanna keep the icon check so that it doesn't keep occurring if you give subsequent doses of methylin.

**Review by Kurfursten — CHANGES_REQUESTED** [review]
Hinai is correct, make sure it stops sending the transform message after it transforms once

**Comment by nervere** [comment]
Good catch. I just rewrote how it works entirely so I forgot about that check. Fixed, thank you!

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
