### PR TITLE
turf/Entered speedup.

### PR DESCRIPTION
**Pull request by ComicIronic**
HasProximity now relies on a flag.
If the moving atom doesn't have the flag, it isn't called.
If the surrounding atom doesn't have the flag, it isn't called.

Doing some rudimentary profiling, this cut the Entered cost by an order of magnitude.

### CODE REVIEW

**Comment by clusterfack** [comment]
Did you make sure this maintains functionality?

**Comment by ComicIronic** [comment]
Well, I tested that it still calls the prox proc using portable flashers.

I could test all the cases I edited, but I can't see any reason why they would be different.

**Comment by clusterfack** [comment]
Well if it works it works, I'm the last person who'd complain about an optimization

**Comment by Midaychi** [comment]
You say it cuts the entered cost by a magnitude but do you have before and after profile stats?

**Comment by ComicIronic** [comment]
Sure.
This is the cost from when the issue was reported:
enteredold
And this is from some testing:
enterednew2
Done by running through this setup back and forth several times:
microwavecorridor
Which led this this intermediate data:
enterednew
Then emptying 3 spawned boxes of ore through Mining's conveyor.
miningconveyor

Considering I basically abused HasProximity with the flasher/detector combo, the stats come out pretty well:
Before, the cpc (as total/calls) was 1.080e-4.
After, it was 4.44e-5.
In a regular round, you could expect the cpc to be even lower, simply because nobody is going to continuously hit 14 prox systems in a row.

**Pull request merged**
