### PR TITLE
Allows bodies to be dragged out of airbags

### LINKED ISSUE #33880: getting sent to crit potentially entombs you in a personal airbag
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
934267d70190cc8ea53d63ad982fa98037140d3d

# Description
i get hurt by spider queen and i shoot the window to quickly suck them out of the room with zas and a bunch of stuff hits me on the way out, deploying my airbag and keeping me safe in the room as the spider flies out, but i go into crit because of le funny venom toxin as well as damage tick delay and then i die and i remain trapped in the cocoon until the end of the round
# Steps to Reproduce
get damaged by some kind of delayed damage, like poison or being on fire or something, and then activate your personal airbag by getting hit by a bunch of flying cargo crates or something
# Possible Solution
make some kind of way to break open a personal airbag from the outside like a knife or something, sort of like how cocoons work

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[tweak]

## What this does
Closes #33880.

## Why it's good
saves people in crit sometimes.

## Changelog
:cl:
 * rscadd: Bodies can now be dragged out of personal airbags.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This is a feature request, not a demand, but it would be cool if you could pop these with sharps like inflatables.

Actually... why isn't personal airbag just an inflatable child - like the shelter is?

**Comment by dinnerwoerror** [comment]
> why isn't personal airbag just an inflatable child - like the shelter is?

personal airbags are

- eight years old soul code
- added 2 years before inflatable doors and 4 years before inflatable shelters
- uncommon; only available to redpilled cargo clientele and the lucky 5% of red toolboxes that hold its treasure
- probably a forgotten invention of John Nanotrasen, telltale by its indefatigable aluminum casing designed to shoot outwards like a Takata airbag and puncture the bubbles of the subhumans who use piss baby inflatables

**Comment by SECBATON-GRIFFON** [comment]
> This is a feature request, not a demand, but it would be cool if you could pop these with sharps like inflatables.

click dragging destroys them here and can be done on the same tile anyways

> Actually... why isn't personal airbag just an inflatable child - like the shelter is?

i don't find them comparable

**Comment by dinnerwoerror** [comment]
also I think I learned something about personal airbags, I think you can only move out of them (and thus leave the airbag) by moving, which you can normally do after your ZAS stun wears off, but you can't move around if you're in crit and dead from spider toxin damage...

**Pull request merged**
