### PR TITLE
Better storage not full indicator

### LINKED ISSUE #29408: Weird inventory glitch with backpacks and any storage method.
(WEB REPORT BY: kirbythewizard101 REMOTE: 206.221.180.138:7777)
# Revision
4c09a724bde4dbd895b9468a1c8aa18c4f65c984

# Description
If you fill something up to it's full "line" i.e a row of items, it'll display the next roll instead of staying where it was, this is with toolboxes, toolbelts, backpacks, plastic bags, briefcases, etc.
If this is a feature where can I vote to revert it? I dont want my toolbelts looking ugly.
# Steps to Reproduce
Fill something up to a full row.
# What you Expected
For my shit not to look ugly
# What Actually Happened
It looked ugly.

### PR DESCRIPTION
**Pull request by help-maint**
Fixes #29408
Old:
114298662-e18b4880-9a8d-11eb-85cb-cdbc7ce9db0e
New:
dreamseeker_12_05_2021_00_56_56_27
Mousing over the triangle tells you exactly how much space remains. Clicking the triangle is the same as clicking an empty inventory space.

:cl:
 * tweak: Changed the "storage not full" indicator from a full empty inventory bar to a new, small, ugly triangle that tells you exactly how much space remains.

### CODE REVIEW

**Comment by BomberBro** [comment]
I really, really like this PR.

**Comment by Eneocho** [comment]
How does it tell you how much space remains? Does it give a numerical value? Does it give a list of storage sizes left (something like: The bag can still hold 1 large object, 2 medium ones or 6 small ones.)?

**Comment by DrSnips** [comment]
Where's the triangle?

**Comment by gurfan** [comment]
@DrSnips directly to the left of the big X, it took me a minute to find it too

**Comment by help-maint** [comment]
> How does it tell you how much space remains? Does it give a numerical value? Does it give a list of storage sizes left (something like: The bag can still hold 1 large object, 2 medium ones or 6 small ones.)?

It just says "6 volume remaining". What does it mean? I don't know, but it speaks volumes.

**Comment by DeityLink** [comment]
Took me a while to find the triangle, this thing needs a more visible sprite imo. At the very least a different color.

**Comment by help-maint** [comment]
Still picture doesn't do it justice, it becomes way more obvious when you're actually using a container and the button spontaneously appears/disappears as you store items. It's not supposed to be eye-catching either, the only thing it has to do is be there and you already know what spot you need to click. I promise it's a lot better in practice.

That said if anyone wants to try respriting it be my guest

**Comment by Eneocho** [comment]
> 
> 
> > How does it tell you how much space remains? Does it give a numerical value? Does it give a list of storage sizes left (something like: The bag can still hold 1 large object, 2 medium ones or 6 small ones.)?
> 
> It just says "6 volume remaining". What does it mean? I don't know, but it speaks volumes.

At least change it from volume to liters. 6 liters remaining.

**Comment by help-maint** [comment]
I don't want to get into "a coin is not 1 liter" territory

**Comment by DrSnips** [comment]
You could give a % (or a rounded and then sanitized version IE "about half, about 1/3, about 3/4 full") of fullness so people could evaluate for themselves. If my bag has 3 small items in it and it says it's half full people can evaluate for themselves it will hold 3 more small items.

**Comment by DrSnips** [comment]
My thoughts on the method:
- Feed the (current volume/max volume) to a rounding proc to round to the nearest quarter
- Have that go into a switch statement to select a portion of a phrase and store it as X.
- That phrase is put into "The bag looks X."

**Review by ShiftyRail — APPROVED** [review]

**Pull request merged**
