### PR TITLE
Medbay Construction Fixes

### PR DESCRIPTION
**Pull request by Kurfursten**
- Fixed a bug where the Body Scanner could not be deconstructed.
- Fixed a bug where the Sleeper could not be deconstructed.
- Fixed a bug where the Operating Table could not be deconstructed.
- Fixed a bug where the Morgue Tray could not be deconstructed.
- Fixed a bug where the Body Scanner could not be constructed.
- Fixed a bug where the Sleeper could not be constructed.
- Fixed a bug where the Operating Table could not be constructed.
- Fixed a bug where the Morgue Tray could not be constructed.
- Fixed a bug where the Body Scanner did not benefit from improved components.
- Fixed a bug where the Sleeper did not benefit from improved components.
- Fixed a bug where the Body Scanner did not properly generate its own console.
- Fixed a bug where the Sleeper did not properly generate its own console.
- Fixed a map issue where Body Scanner Consoles were placed on the map.
- Fixed a map issue where Sleeper Consoles were placed on the map.
- Fixed a bug where the Body Scanner could not be flipped in direction.
- Fixed a bug where the Sleeper could not be flipped in direction.
- Fixed a bug where the Morgue Tray could not be flipped in direction.
- Fixed a missing sprite issue for the Body Scanner's alternate direction.
- Fixed a missing sprite issue for the Morgue Tray's alternate direction.
- Fixed a bug where the circuitboard for Body Scanners did not exist.
- Fixed a bug where the circuitboard for Sleepers did not exist.
- Fixed a bug where the circuitboard for Body Scanners was not able to be printed at the Circuit Imprinter.
- Fixed a bug where the circuitboard for Sleepers was not able to be printed at the Circuit Imprinter.

This is definitely a bug fix and not new functionality.

### CODE REVIEW

**Comment by d3athrow** [comment]
top kek

**Comment by d3athrow** [comment]
Also learn how to use the map tools so you dont get 10k changes when you change one tile on the map.

**Comment by Kurfursten** [comment]
I swore I used map tools. I can just step back a stage and redo it.

**Comment by d3athrow** [comment]
prepare maps, make changes, save, clean maps

**Comment by Kurfursten** [comment]
Map cleaner is a buggy mess.

**Comment by d3athrow** [comment]
Just doing it wrong.

**Pull request closed without merging**
