### PR TITLE
Buffs cheat death by letting you keep at most 10 blood.

### PR DESCRIPTION
**Pull request by SirSkeleto**
[gameplay] [tweak]

Since vamp got a little reworked and nearly all of its powers are on a blood cost, I feel like it's appropriate to give you something to work with. As someone who plays vampire, I honestly feel like a vampire that cheats death in the current state of things is weaker than one who's just starting, because they lack any way to kill crewmen. Maybe this is intentional, and maybe you think the ability to try again AT ALL is good enough in and of itself, and I'd be happy to hear what you think. As it stands, I think a death cheating vamp find itself in interesting circumstances. If you're at the point where you can even cast this, chances are you're doing quite well already. Chances are, the crew has noticed that you're the vamp or at least that there is a vamp, and if you don't die, well, this change won't matter. However, in the event that you do die, it's probably because of a coordinated crew effort, and you're probably decapitated anyway, so it won't matter that way either. The cases in which this does matter is if you die to your own stupidity, or you were mistaken for a traitor by hiding the use of your spells, or the crew simply forgot to dispose of you properly. As it stands, the advantages a death cheater has over a roundstart vampire are x-ray vision and resistance to holy things. The advantage a roundstart vampire has over a death cheater is that nobody knows they're there in the first place, and they have enough blood to get going (which is easier when you're quiet than when you have some decent passives, in my opinion anyway). On another note, it also prevents the awful anticlimax of a vampire coming back from the dead and immediately getting destroyed as the crew remembers to kill you properly this time, because you have no way of securing more blood for yourself aside from someone leaving murder tools out in the open for you. Even then, since you lack enough blood for hypnotize, a crewmember could call you out and the crew that ganked you before is probably more than happy to gank you again now.

Whew!

Thoughts?

:cl:

 * rscadd: Vampires who die and cheat death will now respawn with 10 usable blood, or however much they had if they had less than that.

### CODE REVIEW

**Comment by gbasood** [comment]
>* rscadd: Vampires who die and cheat death will now respawn with 10 usable blood, or however much they had if they had less than that.

not what your changes do
your current changes remove between 0 blood or 10 minus what they had before
you need to do more than use `remove_blood` here to make sure they start with 10 if they had 0

**Comment by SirSkeleto** [comment]
They're not supposed to start with 10 if they had 0. That's the point. I call max() so that you don't just kill yourself to get free blood. You get your blood back if you had between 0 and 10, and you get 10 blood if you had more than 10. That's exactly what I intended for it to do.

**Comment by gbasood** [comment]
Oh, I think I understand the other part I misread. Your changelog note means to say that they use 10 blood to respawn, not that they respawn with a minimum of 10 blood available, correct?

**Comment by SirSkeleto** [comment]
No. As it currently is, vampires respawn with 0 usable blood. This change will make it so that they respawn with their current blood or 10, whichever is lower.

**Comment by gbasood** [comment]
~~Then you need to use something other than `remove_blood`, since it doesn't set their blood to that value, but removes it from their current blood.~~

~~you know what nevermind im dumb i think it's fine and i'm probably just too tired~~

```dm
/datum/role/vampire/proc/remove_blood(var/amount)
	blood_usable = max(0, blood_usable - amount)
	update_vamp_hud()
```
you don't need the `max` then I guess

**Comment by SirSkeleto** [comment]
done.

**Comment by Irradiation** [comment]
>the advantages a death cheater has over a roundstart vampire are x-ray vision and resistance to holy things.
>resistance to holy things

[X] doubt.

**Comment by SirSkeleto** [comment]
> > the advantages a death cheater has over a roundstart vampire are x-ray vision and resistance to holy things.
> > resistance to holy things
> 
> [X] doubt.

forgot about that change, yeah

even more reason to merge (PLEASE MERGE)

**Pull request merged**
