### PR TITLE
Tackling

### PR DESCRIPTION
**Pull request by GreatBigFailure**
This PR adds the ability for spessmen to tackle. The evolution of combat will revolutionize ~runescape~ spess as an e-sport.

To perform a tackle you just need to be on either grab or disarm intent, then throw with an empty hand. This will immediately knock you over and throw you forward. If you hit a living creature along the way it **may** be knocked over as well.

bettertackle

### How it Works

Different factors affect how strong your tackle, or ability to resist being tackled is:

- Several mutations affect it positively or negatively. 
- Species has an effect of varying significance
- Equipment helps. Riot gear for example.
- Being fat 

These factors are summed up for both the tackler and tackle-y then some RNG is applied. The tackler is always knocked down, but if the tackle-y wins the dice roll they aren't knocked down. The difference in the two numbers defines how long both people involved are knocked down. Due to rounding both parties will likely be knocked down for the same amount of time, but if one number is much higher this can change. 

### Why Though and/or Reee Free Stun!

The chef shouldn't feel obligated to carry a taser. Due to the limitations of our combat system and how, aside from very lucky disarm attempts, the only means of defense is based on equipment, the chef is probably a lot happier with a taser if he knows there's a cult around. 
The idea here is to give unarmed spessmen a sort of delay tactic when caught alone. Screaming for help while you desperately tackle a school shooter, both of you scrambling to pick up his gun first only to have the other immediately tackle you back will do a lot to improve that sort of encounter.

Additionally there's a lot to be said for what it can do for other aspects of the game:
-  Two man sec teams can RP a little better with minor criminals. Rather than taze cuffing immediately, they'll have the option of tackling and screaming HALT HALT while hoping the tackle was enough for their partner to cuff them. 
- Rage cages will be very dramatic
- A third thing probably!

Tackling generally favors the person on defense. This is by design as the intention isn't to give people an I-win button but instead a minor counter to the existing I-win buttons we already have.

I understand this will probably trigger a lot of twitch reflex reactions against it due to sounding like a free stun, but after testing it consistently for a few days I'm confident it won't function that way live. If I'm wrong I made sure to make it easy to tweak.
I'll include a more detailed list of how tackling is calculated in a comment below to avoid a wall of text here. 

:cl:
 * rscadd: Spessmen can now perform a tackle by being on a grab/disarm intent and throwing with an empty hand. Knocking themselves and maybe someone else to the ground.

### CODE REVIEW

**Comment by jwhitak** [comment]
Robust as hell. I never knew I wanted this.

**Comment by DeityLink** [comment]
Please update the changelog to tell people specifically how tackling can be done.

**Comment by DeityLink** [comment]
Also really good feature, good to see you come back in force.

**Comment by Armadingus** [comment]
Neat, but the instant motion of the tackle looks a little disorienting.

**Comment by SageOfLight** [comment]
https://www.youtube.com/watch?v=W2zAg39AXcs

Needs the "subaluwa" part of this clip to rarely play.

Also needs insectoid beetle wrestling buffs.

**Comment by ShiftyRail** [comment]
You can make the tackle non-instant by de-compositing in two `forceMove()` with a very low `glide_size_override`. It would also make more sense.

You should also make it so you can't tackle if you have been standing still for more than 2 seconds.
The best way around it would be to add a counter to `/client/proc/move_loop()` or to `/client/Move()` that get reset in the mob `Life()`. 

In order to avoid even more Life() spaghetti you best use an event to do this.

**Comment by drawsstuff** [comment]
What species if you don't mind telling? I'll make it easier to update the wiki if this is merged

**Comment by gurfan** [comment]
I agree with Armadingus and Shifty, it looks like you just teleport to the guy

**Comment by GreatBigFailure** [comment]
Regarding the instant movement, it's mostly just a bad gif. I was in a hurry to PR this this morning. Since the gif is a portion of the screen it looks off. I'll post better one when I'm able.

I'll post the details like species and mutations when I'm not on my phone.

**Comment by Kammerjunk** [comment]
does this apply `stunned`? hulks (among other things) can't get stunned, so the only thing that happens when they try to tackle is that they try to move to that position. they don't fall down, and they don't tackle.
guessing this happens because the human is stunned, THEN moved, which lets it occupy the same space as a standing human. hulks fail the first step and do not pass go or collect 500

**Comment by Kammerjunk** [comment]
for more info see:
https://files.catbox.moe/4aodqn.mp4
https://files.catbox.moe/1ez550.mp4

**Comment by Kammerjunk** [comment]
also,
>The chef shouldn't feel obligated to carry a taser.

this is not a problem you can even attempt to solve with any one PR

**Comment by BomberBro** [comment]
I really don't like this sort of change. It hinges on the idea that people have to carry powergame gear or die, which, while true in one respect, doesn't fix the issue because the antag will always have the element of surprise and you won't be able to tackle a cultist, for example, before they use their stun talisman with no in-hand on you and take you out of the picture for good. 

In gameplay terms, this gives ANYONE the ability to instantly stun somebody up to 2 tiles away while stunning themselves. In my view this will just turn the halls into John Madden's 2565 NoRP Simulator where two assistants can instantly stun anyone at a small range, loot their gear, then run. This is going to affect antags in exactly zero ways because antags with the exception of like, nukeops, either have the element of surprise or come in such numbers that wasting your life tackling one will just result in you getting brained. On the other hand, the honest, regular joes will suffer under the weight (literally) of everyone getting the ability to stun them at-will.

**Comment by zakanater19** [comment]
>In my view this will just turn the halls into John Madden's 2565 NoRP Simulator where two assistants can instantly stun anyone at a small range, loot their gear, then run. 

Sounds !fun!

**Comment by d3athrow** [comment]
do you just teleport to them

**Comment by Kammerjunk** [comment]
you get thrown, which just looks like teleporting at that short a distance
like throwing a beaker onto the chemistry table from the dispenser

**Comment by ShiftyRail** [comment]
Reposting from thread.

I think people are really overestimating the impact it may have when it's really comparable to a short-ranged disarm requiring better a reaction time AND where you stun yourself as well as your opponent. To talk in powergay terms, in a 1v1 situation it changes nothing. In a 2v1 situation the people with numerical advantage won before the fight even began in 90% of cases.

Really, the only difference with disarms is that a) it stuns you and b) your gear is more taken into account. (disarms do ignore armour, it's a bug that evolved into a feature after a few years).

**Comment by Optimism333** [comment]
I'm not sure if this is possible, but maybe tackling could have a brief windup when done from a stationary position, but have no windup if the spessman is already running (because running is the windup)?

Edit: Could also have it put a message in the chat like "X charges forwards!". Maybe not quite as obvious, but something so people know what's just happened.

Edit 2: I would also suggest limiting tackle to one intent if possible. Maybe just throw on grab intent. I could see myself accidentally forgetting to switch my intents after this change and intending to throw something, but accidentally trying to tackle a table.

**Comment by PavelCIA** [comment]
This will absolutely cuck sec officers when they get swarmed by a group of greyshits. A single greyshit just needs to tackle the officer while the others grab his taser.

Good PR  👍

**Comment by ShiftyRail** [comment]
Honestly I am not against greyshirts using this for their uprising if it teaches sec better manners and better tactics.

**Comment by gurfan** [comment]
Attempting to tackle and throwing yourself should stun you regardless of what you hit, I might be wrong but looking at the code it seems to only stun you if you impact a mob or something dense.

**Comment by ShiftyRail** [comment]
Unless you're a ninja in which you roll over or something.

**Comment by PrimeDSS13** [comment]
I agree with Gurfan, I think it would help balance it out a bit better and make it a higher risk manuever than disarm, which as is currently may just be a bit weaker in comparison.

I also think it could use a run-up for both clarity, balance, and general !fun!, but if the above idea is implemented it may not be needed

**Comment by gurfan** [comment]
> Unless you're a ninja in which you roll over or something.

speaking of ninjas this should trigger their projector if it doesn't already

**Comment by PavelCIA** [comment]
If you hit a wall while tackling you should get brain damage

**Comment by githubuser4141** [comment]
> Unless you're a ninja in which you roll over or something.

Tackling a ninja who's got their katana out should result in you impaling yourself for like 2x the damage. That'd be a cool feature.

**Comment by zakanater19** [comment]
> > Unless you're a ninja in which you roll over or something.
> 
> Tackling a ninja who's got their katana out should result in you impaling yourself for like 2x the damage. That'd be a cool feature.

maybe ninjas would be the only antag near immune to being tackled

**Comment by GreatBigFailure** [comment]
PRing this right before work was a mistake, I'll need to wall of text respond. Also better gif coming in a second. 

@Kammerjunk Thanks for noticing that. I knew hulks wouldn't get knocked over by it and was still deciding how to handle that. However when I last tested they did succeed at tackling others. Maybe I changed something that broke it without thinking. Two options I'm looking at are either overriding their knockdown immunity and knocking them down for a shorter duration, or giving them simply more cooldown on their tackle so it's less spammable. 

@BomberBro If this gets merged the first few rounds will 100% be people spamming it. That's going to happen for anything similar though. Recently we had multiple light themed rounds where everyone was throwing flashlights on conveyor belts and lighting every flare they could. Once people get used to it I think it'll be a commonly used but not necessarily spammed feature. 
As far as looting gear and such, this would only work if the person was currently holding something. The knockdown isn't nearly long enough to loot the person. It also doesn't stun, it knocks down. Those are different, you can crawl while knocked down meaning you can't be looted since you can just move away. I think you're at least partially, maybe even majority, right for most of this but I stand by that this has a lot of positive, and just fun, potential. Trying it live is the only way to know for sure.

@Optimism333 I considered a wind-up if you're standing still and I'm absolutely open to it but I think that should be added for balance once it's tested live. The intent thing is a good point, I partially left it that way intentionally for giggles though. Still, easy to change.

@gurfan It always does a minor knockdown to you, it does so before the throw. If you hit something it does a longer knockdown that replaces the initial one.

**Comment by GreatBigFailure** [comment]
Alright I posted a better gif. The animation is still pretty fast but in-game there's definitely a bit of inbetween time, though extremely brief. I think I'll lower it to minimum throwspeed, but it won't make too much of a difference. If it's still too fast I'll do with shifty recommended.

**Comment by GreatBigFailure** [comment]
Here's the battleship of text for specifics of how it's calculated as of the time of writing. Definitely subject to change:
"Power" is just a flat additive to the likelihood of knocking them down. The way it's decided is:
Offense = Random number between power/2 and power
Defense = Random number between power/2 and power
If offense is bigger than defense, the person is knocked over for the difference. **Notably: if the numbers are the same the defense wins**

I'm happy for any additional ideas for modifiers, and numeric tweaks are easy to make. There's some things like wrestling masks and football outfits that I still need to add bonuses to.

**Species**
Species decides range as well as a big portion of power. If a species isn't listed it uses human values.

Human: Power 5, range 2
Skeleton: Power 2, range 3
Grey: Power 2, range 2
Mutton: Power 9, range 2 (notably only really achievable through SoC)
Vox: Power 4, range 2
Diona: Power 7, range 1
Golem: Power 8, range 1
Slime: Power 4, range 2

As you can see most species are basically even with slight pros/cons, while some fridge cases, mostly mid-round species, have more major alterations.

**Mutations / Strength**

"Strength" which is currently used for certain things like moving anvils and punch damage provides 2 x strength to offense and 1 x strength to defense. Base strength is 1 and not much adds to it.

Hulk: +2 offense, but also adds a point of strength from above, so it totals to +4 offense and +1 defense.
Fat: +3 offense, +2 defense
Vegan: -1 offense, -1 defense
Clumsy: -2 defense
Dwarf: -2 offense, -2 defense
Horns: Adds 5 damage to tackles
Run: Increases tackle range by 1

**Gear / Other**

Ninjas have +1 range
A standing tackle (not moved within 1 second of tackling) gives a -1 to power, while a running tackle (moved within 1 second) gives a +1. So effectively a difference of 2.

Holding a shield offers +4 defense, this stacks if you have more than 1. 
Having active magboots gives +4 defense
Riot helmets offer +1 offense and defense, and riot armor offers +2 to both.
Any suit that slows your movement, like an engineering hardsuit, reduce your tackle range by 1. 
Luchador masks and football jerseys give +1 offense each

**Comment by Viciousaurus** [comment]
Sounds fun in theory but a headache in practice.

Edit: I give it some thought and I have this to suggest:
-make it so people can tackle only on disarm intent
-however, if the other person has grab intent, he catches you and nobody gets knocked down

**Comment by calzilla1** [comment]
>Clumsy: -2 defense
Clowns should basically be untackleable due to their natural slipperiness

**Comment by Viciousaurus** [comment]
> > Clumsy: -2 defense
> 
> Clowns should basically be untackleable due to their natural slipperiness

Counterpoint: tackling a clown should make a honk noise

**Comment by GreatBigFailure** [comment]
> Counterpoint: tackling a clown should make a honk noise

I was just in the middle of adding that

**Comment by Eneocho** [comment]
Petition for hulk tackling to sometimes make you say "I'm the Juggernaut, bitch!" or something alike.

**Comment by GreatBigFailure** [comment]
Some updates:

- Not having moved within 1 second of tackling reduces its chance to knockdown while the reverse increases it. 
- Hulks can now tackle properly and knock themselves down while they're at it. They are still however immune to the increased knockdown of a failed tackle.
- Reduced how much riot helmets, armor, and shields contribute by 1 each. When combined they'll still make you practically immune to tackles but they were too much individually before.
- If a suit reduces your movement speed it also reduces tackle range by 1. This applies to things like hardsuits.
- Clowns now honk when you tackle them
- Tackles are now only performed on grab and disarm intent
- Tackle "animation" is now very, very slightly slower
- Bug fixes

**Comment by APCUnlocked** [comment]
Interesting idea in theory and i'm always up for more unarmed combat shenanigangs. ~~However I do share Bomber's concern about the system, and the fact that this does make greyshits nigh unstoppable unless you're constantly wearing riot armour. Which might be the buff riot armour needs, actually. Hmm. Very interested to see how it actually plays out when people start using it to powergame (which they will) i.e drowning the guy with a gun in tackles and when he's down to a crawl just stunbatoning him.~~ 
Edit: after thinking about it, it actually sounds hilarious. Merge this immediately.

**Comment by SonixApache** [comment]
this is not the fishing content i expected but good stuff either way

**Comment by GreatBigFailure** [comment]
Updated again:
- Tackles now provide attack logs. Hoo boy that could have been bad!
- Luchador masks and football jerseys now give a small bonus to tackles
- The knockdown for a tackle now caps at the same duration as a taser. This duration won't happen unless you tackle a fat martian holding 8 riot shields, but better safe than sorry
- The dwarf mutation now reduces tackle offense and defense significantly
- Skeleton tackles are now even weaker
- Improves the spaghetti code slightly

**Comment by Eneocho** [comment]
If luchador masks give a buff to tackling then shorts should too, since most wrestlers only use shorts when fighting.

**Comment by Eneocho** [comment]
Also, requesting for El Santo's mask to be added as a premium mask.

**Comment by Kurfursten** [comment]
This is so complicated it sounds like it needs its own small wiki page. So do that, there should be somewhere people can go to read about how to improve their tackling. Make a table or something on https://ss13.moe/wiki/index.php/Guide_to_Combat

**Pull request merged**
