### PR TITLE
New wizards den (For Deff)

### PR DESCRIPTION
**Pull request by Konater**
I looked at tg's wizard den and thought it was great so I made my own, there are random teleport tiles surrounding the place so if the spell restriction on z2 gets removed they shouldn't be able to get to central command I hope
wizden2
Thanks to @MercuryDoll  for the beholder

If anyone has some better names/descriptions/ideas/would rather have the tg shuttle/would rather I delete this please share

### CODE REVIEW

**Comment by MercuryDoll** [comment]
The sprite you used was the one where i left the n/w/e-connecting wall in the background.
Here's a DMI without the wall, i can make a proper styled podest/socket for the orb if you want.
https://a.pomf.cat/cbuhjp.dmi

**Comment by Konater** [comment]
Whatever you think is best, but I like the wall version too

**Comment by MercuryDoll** [comment]
In that case, have a version with a non-connecting wall sprite.
https://a.pomf.cat/vibvmx.dmi
image

**Comment by CptWad** [comment]
shit dude replace all wizard dens with that. Thats good

**Comment by Shadowmech88** [comment]
Does the air not drain to space even with no walls?
If the wizard walks out into space would he still die?

**Comment by Konater** [comment]
Invisible forcewalls stop the wizard from running into space or breaking the windows to run into space, I was thinking of making a bullshit invisible wall maze but I couldn't think of a good prize at the end

**Comment by CptWad** [comment]
do forcewalls stop air

**Comment by Konater** [comment]
No but it's all unsimulated

**Comment by CptWad** [comment]
id guess that would work

**Comment by xpcybic** [comment]
Not bad
It's like something you'd see on the cover of a Rush album

**Comment by Intigracy** [comment]
Will walking on the lattices space you since it's on a hyperspace turf?

**Comment by Konater** [comment]
I should have posted this before sorry
wizden

**Comment by Imagebard** [comment]
Beholder?

**Comment by CptWad** [comment]
confrictu

**Comment by Konater** [comment]
oh god what have I done

**Comment by Imagebard** [comment]
RIP PR

**Comment by Konater** [comment]
kill me

**Comment by Shadowmech88** [comment]
> giving up

So sad.

**Comment by clusterfack** [comment]
Lol? Did you close it because of the extra commit? You know that doesn't matter anymore right?

**Comment by Konater** [comment]
Are you sure

**Comment by PJB3005** [comment]
No, it doesn't matter.

**Comment by clusterfack** [comment]
You still need to fix the conflicts though

**Comment by Konater** [comment]
Clicking random buttons isn't working I might need to close and start again

**Comment by CptWad** [comment]
r i p a g a i n

**Comment by Konater** [comment]
next time I need help I'll ask I swear

**Comment by MercuryDoll** [comment]
Get well soon!

**Comment by clusterfack** [comment]
Update your bleeding edge, and then tell it to rebase onto that branch

**Comment by Konater** [comment]
I was getting errors, this is fine though there's some more stuff I want to do to it before it gets considered for merging

**Pull request closed without merging**
