### PR TITLE
Fix Github issue template comment blocks

### PR DESCRIPTION
**Pull request by gbasood**
100% tested markdown guys

Also commented out the bit about "Check whatever applies" since it's not actually part of the issue report.

### CODE REVIEW

**Comment by gbasood** [comment]
#### Description of issue

#### Difference between expected and actual behavior

#### Steps to reproduce

#### Specific information for locating



#### Length of time in which bug has been known to occur



#### Server revision



#### Issue bingo




- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
Uh, what

**Comment by gbasood** [comment]
For some reason the issue template comments sometimes fuck up and sometimes don't
I really couldn't say why
But I know that this fixed it in one the issues where it DID fuck up.

**Comment by gbasood** [comment]
#### Description of issue



#### Difference between expected and actual behavior



#### Steps to reproduce 



#### Specific information for locating




#### Length of time in which bug has been known to occur




#### Server revision




#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.


- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
I don't know of anyone else who has had a problem with it

**Comment by Intigracy** [comment]
The comments appear and he's saying editing in the extra -'s is making them correctly be commented out

**Comment by gbasood** [comment]
#9312 looks like the template comments are still there but Github is displaying them wrong?
I edited one of them to use triple dashes instead of double which fixed that one

**Comment by clusterfack** [comment]
The fact you just copypasted shit in the middle of the end comment segment probably contributed to that

**Comment by gbasood** [comment]
Well then

**Comment by 9600bauds** [comment]
> *he

**Comment by clusterfack** [comment]
I originally put you

**Comment by clusterfack** [comment]
YOU'RE THE SAME PERSON !!!!!

**Comment by 9600bauds** [comment]
!!!!!!!

**Pull request closed without merging**
