### PR TITLE
Trade console concept

### PR DESCRIPTION
**Pull request by Krimsonkhan**
[content] [wip]

pr

This was more of a learning exercise for me but I figured I'd throw it up and see what people think of it as a content concept. The trade console concept is designed for vox traders. I always thought traders should have a passive source of income equivalent to the wages that the crew gets, otherwise their wealth is eclipsed by the crew's wealth as the round progresses, regardless of how many successful trades they've made. Giving traders this additional source of income should give them more capital to trade with, increasing player interaction. It serves to push them to buy objectives cheaply from the crew and profit by selling it via the console.

- At the same interval of 15 minutes that the crew gets paid wages, a new **Trade** will be generated from the list of existing datums, with weights for chance to occur
- **Trades** have item and/or reagent objectives and reward credits upon completion
- Completion of **Trades** is done through the UI of a **Trade Console** linked with a multitool to a **trade telepad**. The items and reagent containers containing the reagents must be placed inside a crate and onto the **trade telepad**.
- **Trades** have a one-time completion per instance generated.
,

### CODE REVIEW

**Comment by Kurfursten** [comment]
Neat idea, also causes traders to be interested in more things than just credits (exchange goods for things the crew has to fulfill pad requests), could have a roundend report saying how many trades the Traders fulfilled
👍 
That said, I think the example trades are too easy. Have stuff they need to get off station like cargo gear, etc.

**Comment by DamianX** [comment]
I can't believe Krimsonkhan is literally glasseclipse.

What this will do is incentivize the ability of traders to steal shit so that they can buy things from their vendor without talking to anyone.
Me no likey.

**Comment by Krimsonkhan** [comment]
> 
> 
> I can't believe Krimsonkhan is literally glasseclipse.
> 
> What this will do is incentivize the ability of traders to steal shit so that they can buy things from their vendor without talking to anyone.
> Me no likey.

From my understanding traders usually start stealing shit when nobody wants to interact with them and they don't have enough credits to buy anything else from the trade vendor to sell. Though, I'll concede that your perspective is probably closer to the actual reality with you being an admin and less of a newfag and all.

**Comment by Kharkov72** [comment]
we make much coin

**Comment by dunsel-hordon** [comment]
aw why was this closed? I have noticed better interactions with traders lately so maybe the whole stealing thing wouldn't be an issue and maybe make it part of vox trader code of conduct that stealing unless no trade is happening is against the rules.

**Comment by Krimsonkhan** [comment]
> 
> 
> aw why was this closed? I have noticed better interactions with traders lately so maybe the whole stealing thing wouldn't be an issue and maybe make it part of vox trader code of conduct that stealing unless no trade is happening is against the rules.

I'm thin-skinned and can't handle any criticism. The code is shit as it was a learning experience and it needs refactoring. I'm not sure I want to be responsible for any shitcode and I could see myself missing a lot of edge cases. The idea itself is controversial.

**Comment by Krimsonkhan** [comment]
> 
> 
> aw why was this closed? I have noticed better interactions with traders lately so maybe the whole stealing thing wouldn't be an issue and maybe make it part of vox trader code of conduct that stealing unless no trade is happening is against the rules.

It needs more work, I'll reopen it for further discussion in the future

**Pull request closed without merging**
