### PR TITLE
deletes secure gps

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
slimes pay up
removes secure gps from security loadout, slimes bouta pay me another dollar if i insert witty banter into the changelog
2mans big wish list of things to delete
- nothing, everythins ifen

# Translation

Removes secure GPS units from security loadouts (Namely the lockers)

This was done because of a bet between myself and DrSlimes (pictured above) who claimed that I would be unable to delete secure GPS' from the game.

:cl:
 * rscdel: Removes secure GPS units from security lockers shout-out to ShiftyRail for being the one who actually solved the mapping problems.

### CODE REVIEW

**Comment by aceedex** [comment]
Gay

**Comment by boy2mantwicethefam** [comment]
shoutout to horatio for having good tastes in endless space memes

**Comment by ghost** [comment]
\>make a sorely needed and overdue change
\>give it a meme description and changelog so people don't take it seriously

this is so sad can we get antag datums

**Comment by Accipitermaris** [comment]
im not against removing this aspect of sec powercreep but just change them so they cant beep so you can still physically coordinate with others (our movespeed is crazy high so being able to coordinate with the xyz positions of others is vital)

seriously though leave in the spses but make it so they never beep & ill upvote your meme pr

 (in an ideal world there would be multiple different "categories" of gps so for example cultists doing /spacebase/ shit who wanted to stay off the grid could set up their own category of gpses so they don't stick out like a sore thumb to anyone with a gps while also broadcasting to eachother. a bit like the pr that non broadcasting gpses don't show up on the list but more fleshed out.)

**Comment by Tokanova** [comment]
hell no

**Comment by Irradiation** [comment]
@DrSnips Next time, negotiate for a dollar if it gets MERGED.

**Comment by iFlashYou** [comment]
mad man

**Comment by MadmanMartian** [comment]
and there's the map errors

**Comment by ShiftyRail** [comment]
Meme PR

**Comment by ShiftyRail** [comment]
Meme PR

**Comment by boy2mantwicethefam** [comment]
boi im bouta do the map fixing tomorrow ffs spawning sps on maps not only lockers bouta nuke whomstever did that

**Comment by Kurfursten** [comment]
Accipt wanted me to post my thoughts on the matter from the discord so I'll just paste my post here:

>I played a lot back in the old days and I can tell you most shifts started with the vamp murdering the one loot pinata (officer) and then gunning down a crew of unarmed crewmen who are totally unawares. The power of the SPS isn't even what it does, but the power of what it suggests. The fact that it exists means that people tend to not try to remove sec officers first and the result of that is that once people start to die there are still people with tasers who can maybe save the day.

I have never been a dedicated sec player. I've played a few rounds but turning sprites sideways has never been my passion. But I think the game is more interesting from a design perspective when there is more risk to jumping an officer. In actual *use*, the SPS beeps get ignored all the time and rarely ping a premeditated murder (more often it's when a sec officer walks in on a crime unexpectedly and gets hurriedly executed). Just yesterday the HOS got dragged into space and killed by the plasmaminer and his body was never found.

I'm not sure I agree with the choice to put the SPS in the HOP and Captain lockers which was never the original design intent but I do think they are important to the security role.

**Comment by IzayaChan** [comment]
this is so sad can we ban coders that make bad prs

**Comment by Diavill** [comment]
this becomes a good PR if you also remove the entirety of science

**Comment by iFlashYou** [comment]
Server 

@Kurfursten Sec can't be every round the protagonist

**Comment by Inorien** [comment]
why not just delete security altogether

**Comment by Jubisloviu** [comment]
why not delete all departments so we only have enginnering and clown related roles in the station?
clearly we've filled this game already with a bunch of unnecessary garbage, we should turn ourselves to what actually trully matters
atmospheric simulations

**Comment by Kitfox88** [comment]
yo this sucks balls, much like myself

**Comment by Blithering** [comment]
This PR has already earned its creator a dollar, it doesn't need to be functional.

**Comment by DrSnips** [comment]
monopoly
Here you go buddy. One whole dollar.

**Comment by boy2mantwicethefam** [comment]
shout-out to madmanmartian for acting like a translator for the species that we collectively call humabs

**Comment by boy2mantwicethefam** [comment]
from bad to worse aaaaaaaa

**Comment by ShiftyRail** [comment]
14 commits later

**Comment by ShiftyRail** [comment]
📞 Close it

**Comment by DamianX** [comment]
☎️ say no more

This is clearly not going anywhere and it's already been shitposted to death. Interestingly, there have been a few people explaining why they think this is a bad change, yet no one explained why this is a good change.

For further discussion see: #18872

**Pull request closed without merging**
