### PR TITLE
Peacekeeper borgs.

### PR DESCRIPTION
**Pull request by PJB3005**
http://ss13.pomf.se/index.php/poll/27
#7944

:cl:
* tweak: Security borgs have been renamed to Peacekeeper borgs, and the sprite colour scheme is changed to baby blue.

### CODE REVIEW

**Comment by PJB3005** [comment]
I need the Kodiak sprite to be converted, @Dizor could you help out here? If not I'll do it myself but I'll probably butcher it.

**Comment by Shaska-** [comment]
Please tell me this isn't the baby-blue borgs.
I'm fine with the rename though.

**Comment by PJB3005** [comment]
It is.

**Comment by Riekland** [comment]
fuck OFF those colours are wank
Make them purple or something, anything but that shitty shade of blue

**Comment by yclatious** [comment]
Looks like shit, make them normal coloured.

**Comment by ThePlapatin** [comment]
>2015-04-06

**Comment by PJB3005** [comment]
N o p e.

**Comment by yclatious** [comment]
Y e s

**Comment by PJB3005** [comment]
Not up for debate, the chicken spoke.

**Comment by Allspice** [comment]
Who said what where

**Comment by Ephx1** [comment]
OH MY GOD IT'S HAPPENING AGAIN!
Though, don't we already have the big red text that tells secborgs to fuck off with acting like sec if it doesn't fit their laws?
I can't really tell if that has worked because I personally haven't directly interacted with a secborg in a very long time.

**Comment by RemieRichards** [comment]
you should port the real peacekeepers :^)

**Comment by ScrambledSteak** [comment]
BWEEP BWEEP

**HUMAN HARM**

BWEEP BWEEP

**Comment by SkowronX** [comment]
wee woo wee woo

**Comment by Probe1** [comment]
oh boy here we go

**Comment by AutismSpider** [comment]
looks like shit tools it has are shit and the vote was pass by people who got there shit push in by rouge sec borgs

**Comment by PJB3005** [comment]
I had to reread that comment 3 times before I understood it.

**Comment by Shadowmech88** [comment]
That server poll is nearly *two years* old.
It's highly likely that our playerbase has changed since then.
At the very least, I think a new poll is necessary.

**Comment by SageOfLight** [comment]
Just remember to update red/blue knight 2.0 to being "Sleek" like all the other Sleek borgs.  :^)

I had Duny originally help me apply those since I didn't understand github worth shit.

**Comment by DoctorMonkey** [comment]
Got excited when I saw this because i thought it was /tg/s hugborgs

**Comment by Blithering** [comment]
I prefer the spicy flavour borgs to the cool mint. Hugborgs as a new option would be nice though.

**Comment by PJB3005** [comment]
Ready for merge.

**Comment by Arthurdentist** [comment]
Give every assistant a roundstart potent ham instead

**Comment by gbasood** [comment]
add a changelog and it's good to go

**Comment by PJB3005** [comment]
Done.

**Comment by Shadowmech88** [comment]
Why did this get merged based on the outcome of a poll that's two years out of date?

**Comment by PJB3005** [comment]
Better late than never?

**Comment by Anglosphere** [comment]
A vote is a vote is a vote. Just because a vote was made two years ago, doesn't mean its any less valid today. Presidential Votes in most countries remain valid for 4+ years after the vote. We can pick borg changes, based on two year old plebiscites as well.

**Comment by Intigracy** [comment]
Because Pomf wanted it too when it was brought up before, it just didn't get done.

**Comment by Shadowmech88** [comment]
But the playerbase has almost certainly changed. A significant portion of the players who voted on the original poll likely aren't even here anymore, and we certainly have a large volume of players who arrived since then that may have a different opinion.

There should have been another poll to measure what people want *now*, we shouldn't make changes based on what people did want years in the past.

**Comment by Intigracy** [comment]
```
Jul 02 06:50:04 <D3athrow>  http://ss13.pomf.se/index.php/poll/27
Jul 02 06:50:09 <D3athrow>  get to it Intigracy
Jul 02 06:50:35 <Intigracy> So just rename the module?

Jul 02 06:57:48 <D3athrow>  Intigracy rename and make the secborg baby blue
Jul 02 06:57:55 <Intigracy> cool
```

From the oldest PR on the subject
https://github.com/d3athrow/vgstation13/pull/5223

**Comment by Shadowmech88** [comment]
That chatlog implies that he told you to make it as a result of the poll's outcome, given that he linked it first.

**Comment by Allspice** [comment]
Did the god damn poll even link to the PR with the sprites?

**Comment by Shadowmech88** [comment]
It did not.

**Comment by Riekland** [comment]
tbh I wouldn't trust the people that play here to make any choice about security matters
ALSO I TOLD YOU TO CHANGE THE COLOUR THE BLUE IS UGLY AS SIN

**Comment by Sarcalogo** [comment]
Baybies lol fucking knew it. What did you expect with the tyrant Mr. Pain at the helm? May as well remove stuns now lol

**Comment by Ephx1** [comment]
I suggest Hot Pink

**Comment by gbasood** [comment]
we'll do a new poll in a day or two

**Comment by mrpain666** [comment]
> Baybies lol fucking knew it. What did you expect with the tyrant Mr. Pain at the helm? May as well remove stuns now lol

Yep. And remove guns and weapons from the game. Wouldnt want anyone's feelings getting hurt.

**Comment by aceedex** [comment]
(((Test merge)))

**Comment by 9600bauds** [comment]
:tada::tada::tada::clap::clap::fire::robot::fire::clap::clap::tada::tada::tada:

**Comment by TheFriggenSawbones** [comment]
100% tested

**Comment by Probe1** [comment]
why did it break something?

**Comment by TheFriggenSawbones** [comment]
#13833

**Comment by ihadtoregisterforthis** [comment]
wut-faces

**Comment by NigglyWiggly** [comment]
>Servbots made grey

I am going to fucking hurt you.

**Comment by Probe1** [comment]
We really need to revert the color aspect it looks much worse.  And it just makes everyone dislike the name change.

**Comment by Intigracy** [comment]
I'll make it suck less this week.

**Comment by IratePirate** [comment]
Why would you do this?

**Pull request merged**
