### PR TITLE
T-Ray Scanners should see invisible objects

### LINKED ISSUE #23121: T-ray and P-ray scanners don't reveal invisible-sprayed people
It seemed to me like these were the tools for uncovering invisible people, but this doesn't seem to apply when invisible spray is involved.

If this is intentional, feel free to close.

### PR DESCRIPTION
**Pull request by adacovsk**
[bugfix][hotfix]

With my invisibility PR, I forgot about t-ray scanners

## What this does
This allows t-ray scanners to pick up more invisible objects by:
- changing how the scanner loops through objects and mobs
- adjusting some invisibility levels for various spells and objects
- fixes some invisibility bug

## Why it's good
They currently don't pick up cloaked or invisible sprayed objects
Closes #23121

:cl:
 * tweak: T- and P- ray scanners now should pick up more invisible objects

### CODE REVIEW

**Comment by Pastamadness** [comment]
Should it pick up invisible spraypaint?
It used not to before the refactor and in that case it's easily countered by fire extinguishers, plus only the clown and mime get access to the permanent version. I'd also like to add that when an invisisprayed PERSON (which I assume is the most critical thing here) is injured, their wounds are overlayed over the invisible sprite for everyone to see although I have not tested this since the refactor.
I beg of you to keep ray scanners from picking those up for hilarity's sake.

**Comment by adacovsk** [comment]
> Should it pick up invisible spraypaint? It used not to before the refactor and in that case it's easily countered by fire extinguishers, plus only the clown and mime get access to the permanent version. I'd also like to add that when an invisisprayed PERSON (which I assume is the most critical thing here) is injured, their wounds are overlayed over the invisible sprite for everyone to see although I have not tested this since the refactor. I beg of you to keep ray scanners from picking those up for hilarity's sake.

yeah the overlays still show, I'm not sure how to prevent this from happening

**Comment by Pastamadness** [comment]
> > Should it pick up invisible spraypaint? It used not to before the refactor and in that case it's easily countered by fire extinguishers, plus only the clown and mime get access to the permanent version. I'd also like to add that when an invisisprayed PERSON (which I assume is the most critical thing here) is injured, their wounds are overlayed over the invisible sprite for everyone to see although I have not tested this since the refactor. I beg of you to keep ray scanners from picking those up for hilarity's sake.
> 
> yeah the overlays still show, I'm not sure how to prevent this from happening

Why prevent it? By cartoon logic only the outside is invisible while any cuts or burns would show.

**Comment by adacovsk** [comment]
> Why prevent it? By cartoon logic only the outside is invisible while any cuts or burns would show.

good point

**Comment by angryturnip** [comment]
Like the other guy said, invisible spray already has enough downsides. This would make it useless I had a really fun round the other night where I was invisible and the crew were trying different things to get me. They were spraying extinguishers, set up turrets, and then finally one of them got me with a proximity water grenade at the comm console I was taunting people at. That wouldn't have happened if t-ray scanners could pick me up.

**Comment by adacovsk** [comment]
> Like the other guy said, invisible spray already has enough downsides. This would make it useless I had a really fun round the other night where I was invisible and the crew were trying different things to get me. They were spraying extinguishers, set up turrets, and then finally one of them got me with a proximity water grenade at the comm console I was taunting people at. That wouldn't have happened if t-ray scanners could pick me up.

If this PR isn't merged, I'll make the same PR without the invisible spray changes

**Comment by Eneocho** [comment]
Rip invisispray. You had a good run.

**Comment by Pastamadness** [comment]
Why

**Pull request merged**
