### PR TITLE
Box execution chamber take II

### PR DESCRIPTION
**Pull request by ShiftyRail**
Working version of #22997 
Hopefully

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Knew it

**Comment by ShiftyRail** [comment]
Conflicts solved & playtested

**Comment by SonixApache** [comment]
Mapdiff is dead, can you show the EVA section? In the broken edition, you cut EVA down to 2 tiles, which sucks.

**Comment by ShiftyRail** [comment]
image

**Comment by SonixApache** [comment]
👌 
inner walls are suddenly reinforced but i'm not sure anyone cares
image

**Comment by ShiftyRail** [comment]
I forgot the air alarm

**Comment by ShiftyRail** [comment]
Fixed & ready to merge

**Pull request merged**
