### PR TITLE
Examine, guns, and campfire typo fixes

### LINKED ISSUE #19203: Incorrect grammar for missing limbs on examine
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
a3ee0e3e79f7954bf39e607807eab2ee40dd541e

# Description

Examine someone with missing limbs :

>They is missing their left leg.
>They is missing their left foot.
>They is missing their right leg.
>They is missing their right foot.

### PR DESCRIPTION
**Pull request by Repth1**
[grammar][bugfix]

examine, guns, and campfire typo fixes

closes #19203

:cl:
 * bugfix: Fixed some examine and miscellaneous typos.

### CODE REVIEW

**Review by MadmanMartian — APPROVED** [review]

**Comment by MadmanMartian** [comment]
huh, does approving it too early cause travis to autocancel?

**Comment by Repth1** [comment]
i think it's because i pushed a commit while travis was still building something

**Comment by MadmanMartian** [comment]
no, that wouldn't do it, it'd just make a new build

**Comment by MadmanMartian** [comment]
well, it succeeded at https://travis-ci.org/vgstation-coders/vgstation13/builds/489704228

**Pull request merged**
