### PR TITLE
Ore Unloader Revamp

### LINKED ISSUE #29804: unloading machines not unloading boxes
(WEB REPORT BY: nottoomykins REMOTE: 206.221.180.138:7777)
# Revision
e624b2f422a981cd9aabce5367bc7e7ce048717f

# Description
unloading machines as seen on the roid no longer unload ore boxes, you have to unload the box and move it away from the machine for the ore to get picked up

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #29804

updated version: image

unloader
bonkplasma_moveoutpost

https://user-images.githubusercontent.com/7573912/122289197-b7715f00-cef2-11eb-9a29-68e85c8f0903.mp4

:cl:
* rscadd: The Ore Unloader has had both its appearance and mechanics slightly refreshed. It now plays an animation when it forces an ore box to dump its content and another one when grabbing items. The new sprite was designed to fit along nicely with conveyor belts, and kept the original machine's color scheme.
* bugfix: Fixed Ore Unloaders not emptying ore boxes.

### CODE REVIEW

**Comment by ghost** [comment]
you baleeted muh chaining gimmick, but VERY good work overall

**Comment by DeityLink** [comment]
> 
> 
> you baleeted muh chaining gimmick, but VERY good work overall

Code is only a mean for a purpose. In the case of Ore Unloaders chaining didn't really matter outside of what can arguably be called mapping errors. But even then the "new" unloaders still call conveyor_act should there be a compatible receptacle in front, so any setup that worked before should still work now, including chaining ore loaders since they drop the items on top of them and will grab items behind them. (reminder that unloaders can be used to safely move items one-way through a wall)

chain unloaders

**Comment by DeityLink** [comment]
tweaked the shading and outline 
image

**Comment by cadaverouscoyote** [comment]
i was just about to say it was really good aside from the outline

**Comment by ghost** [comment]
> > you baleeted muh chaining gimmick, but VERY good work overall
> 
> Code is only a mean for a purpose. In the case of Ore Unloaders chaining didn't really matter outside of what can arguably be called mapping errors. But even then the "new" unloaders still call conveyor_act should there be a compatible receptacle in front, so any setup that worked before should still work now, including chaining ore loaders since they drop the items on top of them and will grab items behind them. (reminder that unloaders can be used to safely move items one-way through a wall)
> 
> chain unloaders

Your way of doing this honestly seems nicer and more sane, instead of something that just transports everything along the line instantly and crashing MC if it gets in infinite loops, pre-checking.

**Pull request merged**
