### PR TITLE
Snaxi Cargo: Unpacked

### LINKED ISSUE #34549: Snaxi Cargo - Mapping Changes (Proposal)
#### Description of issue
Snaxi Cargo Remapping Request:

I'd like to see some changes made to Snaxi Cargo. It's awkward in design in pretty much every aspect and I'd like to see if changes can be made to straighten these kinks out. These changes do not need to take place until AFTER July as to not bring Snaxi down during Aussie Xmas. Please refer to attached pictures to show areas that I would like to see changed. Descriptions will be below here.

Picture 1 (Storage Room and Shipping Conveyor): This storage room is virtually useless in it's current size and configuration. It's far too tiny to house much and given the sheer size of Snaxi, an expansion would be nice to have. To accommodate this expansion, I propose the elimination of part of the shipping conveyor room by extending the south side wall of the storage room through where the table is. The table will need to move to the west next to the janitor's door. I have annotated sections that will need to be removed, any monitor panel (air/apc) can be moved to a different section. The APC behind the table and the air monitor on the corner section of storage can be moved to either side of the cargo maintenance door. 

Addendum - In the storage room, on top of removing that odd angular corner piece, remove a second section with the other air monitor next to the storage rack, expanding the shutter door by one and move both storage racks in the storage room to the back wall.

Storage and Conveyor Room

Picture 2 (Cargo Lobby): The lobby is far too small as is and with the consoles dominating most of the space, it makes it extremely awkward to maneuver crates around and out the door for waiting customers to pick up. My proposal for the changes here are as follows and are annotated in the the attached picture:

- Expanding the lobby entrance one row east, adding more entry space.
- Move the clothing vendors south to the numbered spots indicated in the picture, 3 chairs will need to be removed, the ATM moved to the indicated spot next to the coffee machine and suit storage and the fire extinguisher moved to mechanics window.
- Elimination of the decorative candy machine
- Table with toolbox and cleaner, move south to in front of the security checkpoint window.
- With these out of the way the cargo lobby can also be expanded southward approximately 2 rows to allow for easier maneuvering of crates large and small. No need to change positioning of Cargo side ordering console or window. Door will be moved southward to accommodate the expansion.

Cargo Lobby

I will happily meet with whoever takes this on to better discuss my proposed changes with live pointers if anything needs clarification. This, in the end, should help make Snaxi Cargo a ton easier to use in critical areas for us Cargo mains. Apologies if the tagging isn't correct, didn't see one specifically for the map. 

#### Server revision

Game: 2d347e669a713522a3ec644a4de3ecb07a6c5b69 
Patches: 45084ae38cc9f68891184351e906b395e62066f4

### PR DESCRIPTION
**Pull request by Kurfursten**
closes #34549

image

🆑 
* tweak: Snaxi Cargo is now MUCH larger, including the warehouse, main bay, and front office.

### CODE REVIEW

**Comment by angryturnip** [comment]
Downvoted for witty title

**Comment by PrimeDSS13** [comment]
upvoted for witty title

**Comment by west3436** [comment]
I like the snowmobile garage it currently has, any way that can be retained?

**Comment by ErrorsWindows** [comment]
yea i did like the snowmobile garage, the shutters didn't have a button on the inside so i would keep people imprisoned in there

also they do have a point, the mail room just kind of looks fucking goofy with that much free space, you'd be better off expanding the warehouse instead (which i suppose you half did with the plastic flaps)
and i'm not really losing that much sleep over the loss of the rainbow jumpsuit chamber, that thing was weird to begin with, more interested in where the candy dispenser and the table with the toolbox and free spray bottle went, i used that to slip into the red man zone just south and fill it with pepper spray

**Comment by Kurfursten** [comment]
The garage is still there its just out of frame. It wasn't edited.

All of the things you mentioned were moved slightly to the right. Candy dispenser is by the eva room, toolbox and spray by mini medbay

**Comment by Kurfursten** [comment]
Also: I noticed I actually left a floating light near the main bay conveyor belt. When I go back to fix this I am also going to move the rack blocking the top shutter from the right and add a sales machine.

I could also separate the mail room with a wall so that the warehouse is not connected to it. This isn't what @CorinJace requested in his issue but it seems like some people would prefer a small mail room? This would also keep the janny out of the warehouse. Better give input soon though since Snaxi mapping requests gotta go fast for 1 month limit.

**Comment by CorinJace** [comment]
Yeah. I honestly did think about adding a wall to separate the mailroom and warehouse but tossed it aside thinking it might overcomplicate things. But thinking about it again, not a bad idea.

**Comment by ErrorsWindows** [comment]
i mean the warehouse is already connected through the maintenance door so it's not like it's that secure anyways

**Comment by Kurfursten** [comment]
It looks like a maintenance door in color but it's a cargo door. Would you like me to swap it to cargo colors while I'm at it?

**Comment by ErrorsWindows** [comment]
i donno it just seems kinda weird, snaxi is the only map where the warehouse leads directly into the main hallway

**Comment by CorinJace** [comment]
> It looks like a maintenance door in color but it's a cargo door. Would you like me to swap it to cargo colors while I'm at it?

Yeah. That'd be good. Match the color for cargo. Probably eliminate the door leading out to the hallway too. Like Windows said, it's weird. Doesn't make sense.

**Comment by ErrorsWindows** [comment]
also probably the fact that it's the cargo/mining door i've seen hacked most often by people from the hallway, even the mail room exit doesn't hold a candle to that door, even if i have to tell people that the mail door is open-access from the inside like the medbay doors

**Pull request merged**
