### PR TITLE
Temperature Guns now also set the temperature of the reagents inside hit objects

### PR DESCRIPTION
**Pull request by DeityLink**
I can't believe this wasn't a thing

:cl:
* rscadd: Temperature Guns now can now also be used to instantly set the temperature of food, or the reagents contained in beakers and other containers.

### CODE REVIEW

**Comment by jwhitak** [comment]
An example of a good heating-based PR.

**Comment by DeityLink** [comment]
The next step is to have food / containers actually appear frozen/glowing when cooled down/heated up. Might not do it in this PR though. That was just an idea that came up before going to bed.

As a xenobio player a decade ago I'm glad this baby finally has a reason to come out of science.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
i like the glowing idea but autismally i feel like it has to follow the black body model
maybe nice steaming hot effects over food would make it look nice

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
another thing i was thinking is, if you pick up something hot enough to burn you (not just warm or cool) and all the glove checks etc are accounted for (as with examining it inhand currently), it could say "the blah feels searing hot"
i took a look at this in the past but there are some things about put_in_hand() that would have to be slightly reworked to fix some edge cases (removing from storage containers triggers put_in_hand() twice)

and since pain makes you drop things, i was thinking maybe picking up something that's extremely hot could actually burn your hand and make you drop it, mitigated by painkillers, gloves, etc.

**Pull request merged**
