### PR TITLE
This is apparently controversial.

### PR DESCRIPTION
**Pull request by PJB3005**
Reverts d3athrow/vgstation13#12992

Note: reverting this is stupid. Doing this so these morons calm the fuck down.

### CODE REVIEW

**Comment by 9600bauds** [comment]
muh

e m o j i c r a c y

**Comment by despotate** [comment]
Don't set the precedent for thread shitters that brigading a PR will get it reverted.

**Comment by ghost** [comment]
Did you really have to call the idea of reverting it fucking stupid? Couldn't just make it unbiased and let people fairly come to their own conclusions.

Why are you so angry at people discussing things PJB, it's childish. People are going to disagree with some things the coders do, in a game with hundreds of players this is obviously going to happen.

**Comment by Kuranon** [comment]
>Note: reverting this is stupid. Doing this so these morons calm the fuck down.

Are you sure you're not the one who needs to calm down? I think it was being discussed rather well until you guys started ranting about how wrong we were for not wanting this and how we shouldn't care about it

**Comment by Exxion** [comment]
>Tells someone not to express his opinion
>Proceeds to express a bunch of opinions

**Comment by 9600bauds** [comment]
Why are the people that want this not even giving it a thumbs up

**Comment by PJB3005** [comment]
@SolariousGabriella because you're the childish ones here. You idiots calling for revert because it negatively affects you and your ego is stupid.

I would agree with discussion, but not here. Consistency is good and this is no exception. The only argument against it is that "it's different".

Think of it like this, you have to learn the new hotkeys for maybe 30 minutes, meanwhile a theoretically infinite stream of new players will run across this unintuitive behaviour.

**Comment by Exxion** [comment]
oh no

**Comment by ghost** [comment]
"Consistency is good and this is no exception"
Despite the actual playerbase being against it, the people that want this are coders that don't play the game. The game should be built for the actual players right? Not the hypothetical new players that are coming, and if so many have learnt the hotkeys as they were why would it be so hard for new players to learn them the same?

Alt+Click is used for a lot, it's also used for mostly useless shit that you hardly if ever use. The PDA is used a ton and is probably one of the most used set of hotkeys after pulling and examining, why change something that is widely used to be more like things that are hardly if ever used.

**Comment by 9600bauds** [comment]
Because the PDA is literally the only thing in the entire game that uses ctrl+click for anything other than dragging, and eject ID is used much more often than eject pen.

Do you understand this concept?

**Comment by ghost** [comment]
Yes, I also understand that ctrl+click is easier on top of being what people remember

**Comment by despotate** [comment]
What's "easier" about ctrl+click?

**Comment by PJB3005** [comment]
> Despite the actual playerbase being against it

A playerbase that has been shown to time and time again be edgy shitlords with no concept of reason. Gotcha.

>  the people that want this are coders that don't play the game

I'm pretty sure @despotate does play the game.

> The game should be built for the actual players right?  Not the hypothetical new players that are coming

With this kind of attitude you're likely to fuck off within a year at best and then what?

> and if so many have learnt the hotkeys as they were why would it be so hard for new players to learn them the same?

Actively making it harder to learn the hotkeys is not a good thing.
Yes, people used to ride by horse, doesn't mean that driving by car isn't superior because you're used to going by horse.

> Alt+Click is used for a lot, it's also used for mostly useless shit that you hardly if ever use.

You're using Alt+Click wrong.

> The PDA is used a ton and is probably one of the most used set of hotkeys after pulling and examining, why change something that is widely used to be more like things that are hardly if ever used.

See above, you're wrong.

> Yes, I also understand that ctrl+click is easier on top of being what people remember

Good thing you're wrong.

**Comment by Exxion** [comment]
Christ

**Comment by despotate** [comment]
I just want to see how many more replies it'll take until he admits that his only reason is just "I don't like change".

**Comment by Exxion** [comment]
Quiet. Everyone here, on both sides, is being obnoxious. Myself probably included.

**Comment by 9600bauds** [comment]
I said before I'd fuck off and do something more productive but I'm doing it for real now.

**Comment by Iamgoofball** [comment]
Remember when someone starts speaking for all the players, they're an idiot

**Comment by PJB3005** [comment]
That's like the wisest thing goof has ever said.

**Comment by Kuranon** [comment]
>A playerbase that has been shown to time and time again be edgy shitlords with no concept of reason. Gotcha.
Not an argument
>I'm pretty sure @despotate does play the game.
He admitted he wasn't even the one who suggested the change
>Actively making it harder to learn the hotkeys is not a good thing.
This is not actively making anything harder, though. 

>You're wrong
>You're wrong
>You're wrong
I guess this has devolved into putting our fingers in our ears and crying that the other side is wrong

**Comment by PJB3005** [comment]
I hate to say it but sometimes, there is an objective correct.

This is one of those cases.

**Comment by Shadowmech88** [comment]
Alt+click is easier for me to access than Ctrl+click because I don't have to change my hand's position on the keyboard.

**Comment by Kuranon** [comment]
Funny, Ctrl click is easier for me for that exact reason

**Comment by PJB3005** [comment]
See ideally we'd have key rebinding but > BYOND.

**Comment by Exxion** [comment]
There are, and it isn't.
Also, this is fucking stupid. If anyone wants to continue this, do it in an open PR.

**Comment by despotate** [comment]
Do you people really not swap ctrl and caps lock in system settings? ~~What the fuck?~~ Alright I admit I'm just stirring up drama. I respect everyone's choices and I can empathize with not wanting to relearn hotkeys for an abstract far-off ideal. Please remember the human.

**Comment by ghost** [comment]
"What's "easier" about ctrl+click?"
Ctrl is an easier key to hit, it's the bottom left one. There's no chance of hitting the wrong key at all. It's like spacebar.
"A playerbase that has been shown to time and time again be edgy shitlords with no concept of reason. Gotcha."
And the coders are always right, can do no wrong and if anyone disagrees they're a edgy shitter that just hates change. Disagreeing with you does not make them edgy, it means they disagree with you, and if they try and explain why they disagree you shouldn't just say that you're objectively correct and they need to except being wrong.
"You're wrong"
N-no you're wrong!
"I hate to say it but sometimes, there is an objective correct."
I-in your opinion!
"Remember when someone starts speaking for all the players, they're an idiot"
Yclat and Kuranon disagreed in the PR too, people gave it a thumbs down. I'm giving my opinion and saying that others don't like the change.

**Comment by PJB3005** [comment]
This is getting nowhere.

If you honestly care enough about this to argue make a revert PR.

**Comment by Kuranon** [comment]
ok, how

**Comment by Exxion** [comment]
Man what did I JUST fucking say?
If you want it reverted, open a fucking revert PR. It's one goddamn button.

**Comment by despotate** [comment]
> It won't be reverted anyway, the holy coders have spoken and to speak out is heretical, their ivory tower hug box tells them they are right and any dissent is objectively wrong.

Nice way to poison the discussion in the last line of a rant. Please stop.

**Comment by yclatious** [comment]
Im going to be honest, whilst PJB is mad, he is actually right in this.

I admit, I was wrong, and in this case, even if for me, ctrl is much quicker and easier since Im not used to alt, it wouldnt hurt anyone at all to do it, at most I once or twice hit the windows key.

**Comment by despotate** [comment]
This IS the revert PR.

**Comment by Iamgoofball** [comment]
Yeah why don't you go eat a bag of dicks you retarded cocksucking piece of shit kindergarten dropout motherfucker forever-alone autistic son of a bitch @SolariousGabriella

**Comment by despotate** [comment]
goofball dropping the wisdom bombs in here

**Comment by Exxion** [comment]
This is a revert PR opened by someone who didn't want it reverted. And it's full of pointless bile.

**Comment by ghost** [comment]
@Iamgoofball nice way to poison the discussion

**Comment by PJB3005** [comment]
For me alt is actually easier to hit since I have my thumb on the very left on spacebar out of habit anyways.

**Comment by ghost** [comment]
this fabled revert button doesn't exist, I've searched far and wide

**Comment by Exxion** [comment]
Alright
Everyone shut up
Sadly I can't stop collabs from posting, but please just don't. I'll unlock it if a collab tries to get the last word in after I lock it.

The revert button: 
smartselectimage_2016-12-22-16-50-29

**Pull request closed without merging**
