### PR TITLE
Autolathe now spits out stuff on it's location instead of at your feet

### PR DESCRIPTION
**Pull request by Iamgoofball**
now 10 times less dumb to use

### CODE REVIEW

**Comment by Kurfursten** [comment]
:+1: 

Comic may not like it because he was supposedly working on an autolathe thing as per his response to #4603, but he has had a while to work; he can rebase.

**Comment by Zuhayr** [comment]
If he has to rebase to resolve a single-line conflict then something is very wrong.

**Comment by ComicIronic** [comment]
How else would you resolve a merge conflict

**Comment by Iamgoofball** [comment]
git pull
edit files
git resolve
git commit
git push

bam

**Comment by ComicIronic** [comment]
>making a new commit to resolve a one-line merge conflict

**Comment by Iamgoofball** [comment]
oh i forgot to mention squashing it

**Comment by ComicIronic** [comment]
That's just a rebase you goon

**Comment by 9600bauds** [comment]
Why not make it like fabricators, where you can use a multitool to set the location where it should spit things?
<s>fabricator autolathe when</s>

**Comment by ComicIronic** [comment]
Because that's exactly what I'm doing and if we keep adding fabricator code to the not-fabricator we might as well just make it a fabricator and I'm going that right NOW

**Comment by ComicIronic** [comment]
Confrictu.
Also now redundant, because default fabricator behaviour is to spawn on itself.

**Comment by 9600bauds** [comment]
this is what we call the collaborator stall

**Comment by ComicIronic** [comment]
Henk henk henk henk I'm going to close this.

**Comment by Iamgoofball** [comment]
i would of gotten away with it too if it wasn't for that damned ironic comic book

**Pull request closed without merging**
