### PR TITLE
Banana suit

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
This has been cooking for months
Huge thanks to @BurntDevil and @BomberBro  for the sprites!
side
front

Known issues:
- There is a disconnect between the clown mask's colored hair and the vertical and horizontal facings of the banana hat (passes through the hat when facing vertically, doesn't pass when facing horizontally

:cl:
 * rscadd: The banana set is now available in the AutoDrobe!

### CODE REVIEW

**Comment by PavelCIA** [comment]
pbj

**Comment by Eneocho** [comment]
nanner dance

**Comment by boy2mantwicethefam** [comment]
banana suits

**Comment by FlintBarrel** [comment]
god bless, but if you could make it more curved, I would give you my soul.

**Comment by Eneocho** [comment]
Now we only need a way to make actual bananaphones.
I suggest using a bananapeel on a station bounced radio.

**Comment by boy2mantwicethefam** [comment]
It's already a bit more curved, I'll post pics far later

**Comment by boy2mantwicethefam** [comment]
Changed the side pic to reflect sprite change

**Comment by Eneocho** [comment]
can i redeem half a pomfcoin for bananaphone station bounced radios?

**Review by Kurfursten — CHANGES_REQUESTED** [review]
Put it in a smartbox

**Comment by Kurfursten** [comment]
It's really easy, ask me on discord if you need instructions

**Comment by Theophrastus1** [comment]
quality content

**Comment by Eneocho** [comment]
no signs from b2mttf. no bananaphone, bros...

**Review by ShiftyRail — APPROVED** [review]

**Comment by ShiftyRail** [comment]
i forgot how to dismiss a review but it's fine now

**Pull request merged**
