### PR TITLE
Hotfix. Replaced/added reagent scanners in place of mass specs where appropriate.

### PR DESCRIPTION
**Pull request by DrSnips**
[hotfix] [balance]
If you don't like some of these just say. 
I personally don't like mass specs because they are crippled as fuck in what they can scan. I didn't touch any maps besides spawners.
:cl:
* rscadd: Reagent scanners are allowed in medical belts and replaced mass specs borg modules, spessmart, and a few map loot spawners now.

### CODE REVIEW

**Comment by DrSnips** [comment]
TLDR list. They are in allowed/replaced mass specs in belts, borg modules, spessmart, and a few map spawners now.

**Comment by SonixApache** [comment]
🆑

**Comment by SonixApache** [comment]
Don't think you did the 🆑 right.
```
:cl:
 - rscadd: Reagent scanners are allowed in medical belts and replaced mass specs borg modules, spessmart, and a few map loot spawners now.
```

**Comment by DrSnips** [comment]
It just needed a space between *  and rscadd.

**Pull request merged**
