### PR TITLE
Updates Black Site Prism

### PR DESCRIPTION
**Pull request by Kromkar**
<sprites> <vault> 
:cl:
Adds a new hostile simple mob, the Syndicate Executive, thanks to our resident Italian ment_gah. Three variants, Unarmed, Ranged, Ranged Space
65b33d4aec344faa978d33eaf110e765

 - tweak: Polished up the Black Prism vault. Loot and mobs have been rebalanced.

### CODE REVIEW

**Comment by SonixApache** [comment]
:cl: is incorrectly formatted, long-winded and vague. 
Remember that the :cl: is for the players, not for the devs. We can just look at your PR.
Here's an example that is concise and properly formatted.
```
:cl:
 - tweak: Polished up the Black Prism vault. Loot and mobs have been rebalanced.
 ```
 
 Also, conflicts.

**Comment by gurfan** [comment]
gonfligs!

**Comment by Irradiation** [comment]
The free ling vial at the end can go fuck itself, TBH. Free antag after you're done collecting a ton of guns/equipment (though odds are, if you find the vault and clear it, the shuttle probably got called).

**Comment by PrimeDSS13** [comment]
>keeps ling vial
>adds ANOTHER self-antag vial

why

>Adds Commandant Chuck Sneed, syndicate executive and commander of Black Site Prism

stop

**Comment by toomykins** [comment]
mommi milk was a joke PR, Commandant Chuck Sneed should be too.

**Comment by BomberBro** [comment]
>Kept the changeling vial in the Necromorph pen

>Adds Commandant Chuck Sneed, syndicate executive and commander of Black Site Prism

notlearn

**Comment by bathosbathtime** [comment]
Naming a vault NPC after your static is funny but changing the name to Chuck Sneed because people didn't like it comes off as you throwing a fit.
I don't need to tell you anything you don't already know about the vials. Remove them.

**Comment by Kromkar** [comment]
> Naming a vault NPC after your static is funny but changing the name to Chuck Sneed because people didn't like it comes off as you throwing a fit.
> I don't need to tell you anything you don't already know about the vials. Remove them.

I'll remove the vials if they're really an issue when there's already self-antag items obtainable through Xenoarch.

Regarding Commandant Chuck Sneed; just goes to show that no matter what you do some people won't be happy.

> 🆑 is incorrectly formatted, long-winded and vague.
> Remember that the 🆑 is for the players, not for the devs. We can just look at your PR.
> Here's an example that is concise and properly formatted.
> 
> ```
> :cl:
>  - tweak: Polished up the Black Prism vault. Loot and mobs have been rebalanced.
> ```
> 
> Also, conflicts.
I'll keep that in mind for future changelogs. How do I fix the conflicts?

**Comment by Exxion** [comment]
>Regarding Commandant Chuck Sneed; just goes to show that no matter what you do some people won't be happy.

You have done exactly two things with regards to this name and people have good reason to be unhappy about both of them

**Comment by Kromkar** [comment]
Alright, vials out

**Comment by Kromkar** [comment]
> > Regarding Commandant Chuck Sneed; just goes to show that no matter what you do some people won't be happy.
> 
> You have done exactly two things with regards to this name and people have good reason to be unhappy about both of them

There is a vault that is a reference to a leatherdaddy porno meme that was popular at the time. CMD Chuck Sneed is not a big deal.

**Comment by ghost** [comment]
> 
> 
> > > Regarding Commandant Chuck Sneed; just goes to show that no matter what you do some people won't be happy.
> > 
> > 
> > You have done exactly two things with regards to this name and people have good reason to be unhappy about both of them
> 
> There is a vault that is a reference to a leatherdaddy porno meme that was popular at the time. CMD Chuck Sneed is not a big deal.

Gachimuchi is a 10+ year old fixture of internet culture that has remained consistently popular and the vault was added more than 5 years after taking off. Sneed, in its current iteration, is a ~2 year old forced meme.

**Comment by kilozombie** [comment]
I don't want to be a snitch, because snitches get stitches, but if things haven't changed, Kromkar still hasn't tested any of this

**Comment by Kromkar** [comment]
Ment tested the sprites and they work fine.

I forgot to change the branch when I went to submit another PR so there's now another vault bundled into this one until I figure out how to undo that on GitHub.

**Comment by Blithering** [comment]
syndiexec
Fashion being the most important part of any PR, the syndi exec suit was designed to go well with the red sunglasses if you wanted to jazz the mob up a bit more.

**Comment by smalIboss** [comment]
syndicate executive guys, awesome. but that commander name is retarded fuck you. just call him commandant mike syndicate or something.
and the vials for are insane. them being available through xenoarch isn't a argument since 1. only the biggest autists go for xenoarching and 2. its rare as fuck.

**Comment by Exxion** [comment]
He really doesn't need a personal name at all. Most vault enemies don't have them. He can just be `Syndicate Commandant`.
Also, your changelog still isn't formatted properly. You put the `rscadd:`, etc. at the beginning of each entry. Also, you should clarify that you're talking about this vault.

**Comment by Kromkar** [comment]
> He really doesn't need a personal name at all. Most vault enemies don't have them. He can just be `Syndicate Commandant`.
> Also, your changelog still isn't formatted properly. You put the `rscadd:`, etc. at the beginning of each entry. Also, you should clarify that you're talking about this vault.

1: That's fine that most vaults don't, mine does.
2: That's because I haven't changed it yet.



> syndicate executive guys, awesome. but that commander name is retarded fuck you. just call him commandant mike syndicate or something.
> and the vials are insane, same for the xenovial. i would just get rid of them. them being available through xenoarch isn't a argument since 1. only the biggest autists go for xenoarching and 2. its rare as fuck.
> you underestimate how filled with loot this vault already is with all the operatives running around with c20s.

The vials were removed 5 hours before you made this comment you braindead Frenchman sorry

**Comment by smalIboss** [comment]
> The vials were removed 5 hours before you made this comment you braindead Frenchman sorry
> syndicate executive guys, awesome. but that commander name is retarded fuck you. just call him commandant mike syndicate or something.

fix this.

**Comment by DeityLink** [comment]
> 
> 
> > > Regarding Commandant Chuck Sneed; just goes to show that no matter what you do some people won't be happy.
> > 
> > 
> > You have done exactly two things with regards to this name and people have good reason to be unhappy about both of them
> 
> There is a vault that is a reference to a leatherdaddy porno meme that was popular at the time. CMD Chuck Sneed is not a big deal.

Are you really comparing Gachimuchi and the legacy of Billy Herrington to that flavor of the year meme that is sneed?

**Comment by DeityLink** [comment]
Also why aren't you adding the Wuhan vault in its own PR? You don't have to copy all my old mistakes.

**Comment by Kromkar** [comment]
I am going to close this PR, fix my conflict issues, and resubmit it.

**Pull request closed without merging**
