### PR TITLE
Readds some overwritten sprites

### LINKED ISSUE #11720: Blood red syndicate magboots are invisible
@kol1th WHAT DID YOU DO
The thing's not in shoes.dmi anymore

### PR DESCRIPTION
**Pull request by JustSumBody**
Harmonica mask sprite and syndie magboots were overwritten thanks @kol1th 
closes #11720
Geeze kids these days accidentally overwriting sprites who does that

### CODE REVIEW

**Comment by kol1th** [comment]
oops

**Comment by ComicIronic** [comment]
You can create custom git tools to do diffs of non-text files, and it just might be worth making one for DMIs that compares the icon_states to prevent stuff like this.

**Comment by ghost** [comment]
Wait hold on

**Comment by ghost** [comment]
Bay has conflict resolvers for sprites, should I port that?

**Comment by clusterfack** [comment]
Yeah probably

**Pull request merged**
