### PR TITLE
Targeting-based reagent mob reaction, attempt 2

### PR DESCRIPTION
**Pull request by ghost**
[system][tweak][tested]

Original CL text from #32214:

:cl:
 * tweak: Reagents splashed from containers, jars, glassings, water balloons, paint buckets, liquid beams, mops and general breakable items can now splash a specific targeted part of the body.
 * tweak: Mobs will now only ingest splashed reagents if aimed at the head or mouth.
 * tweak: The species based damage effects of water, plant-b-gone and insecticide and general ones of sulphuric and polytrinic acid now take into account coverage and targeting of all limbs, not just the headgear and mask. (This includes melting of any acidable clothing)
 * tweak: Blood now only infects the part of the body targeted with splashing.
 * tweak: Space cleaner can now clean specific parts of the body.
 * tweak: The eye damaging effects of bleach and condensed capsaicin now only apply if targeting the head or eyes with splashing.
 * tweak: Nanites and xenomicrobes only have a chance to ingest if splashed when aimed at the mouth or head.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
How does this work with smoke?

**Comment by Eneocho** [comment]
>tweak: Blood now only infects the part of the body targeted with splashing.

Does this mean that only the shoes (for example) get splashed with virus blood, but the other bloody clothes (if any) are not infected?

**Comment by ghost** [comment]
> How does this work with smoke?

It targets everything

**Comment by Optimism333** [comment]
Can you post some screenshots / clips of how this would work in practice with pacid? I'd like to see what the chat feedback looks like and how fast it melts everything, if this makes it melt clothes now too.

Addendum: For that matter, will a pacid grenade now melt a hardsuit off someone completely after this change?

**Comment by ghost** [comment]
> Can you post some screenshots / clips of how this would work in practice with pacid? I'd like to see what the chat feedback looks like and how fast it melts everything, if this makes it melt clothes now too.
> 
> Addendum: For that matter, will a pacid grenade now melt a hardsuit off someone completely after this change?

It will, but I need to find a way to make it not that isn't "unatomic"

**Comment by Eneocho** [comment]
> > Can you post some screenshots / clips of how this would work in practice with pacid? I'd like to see what the chat feedback looks like and how fast it melts everything, if this makes it melt clothes now too.
> > Addendum: For that matter, will a pacid grenade now melt a hardsuit off someone completely after this change?
> 
> It will, but I need to find a way to make it not that isn't "unatomic"

You could both add a module that makes hardsuits acidproof and have that module default enabled on some suits (like xenoarch and medical).

**Pull request merged**
