### PR TITLE
[WIP] Medical Research Vault

### PR DESCRIPTION
**Pull request by Arthurdentist**
Somewhere in the depths of space, a small research team on a secret nanotrasen research facility meet an untimely demise. Years later an intrepid space explorer (or an unfortunate spaced clown) finds the old facility. Will he find sweet loot or get killed in a horrible fashion?

vault

This is my second awful vault. Unlike the previous one this one is meant to be a far more serious vault with more thought put into its contents and layout. As it stands it doesn't have any really impressive loot aside from some medical bits and bobs and a couple of other things. If you have any ideas, suggestions or additions then please comment so that my awful vault can perhaps be not so awful.

### CODE REVIEW

**Comment by gbasood** [comment]
Not sure that all that plasmaglass is necessary

**Comment by Arthurdentist** [comment]
You mean the windows? Looking at it now I think normal rglass would look nicer.

**Comment by SonixApache** [comment]
Add some advanced medical kits if you haven't already.

**Comment by Probe1** [comment]
This was cool man.

**Pull request closed without merging**
