### PR TITLE
Hailer GUI button and Attachable Hailers

### PR DESCRIPTION
**Pull request by Apogee-dev**
Adds a GUI button for sec hailers which can also be activated via command bar or macro with the activate-hailer command, performing an untargeted hail.

TODO: Add targeted hail functionality on CtrlClick

PARTIAL: Hailers can be attached to uniforms and armors, but action button isn't working yet. Need icons.

:cl:
 * rscadd: Added a GUI button for sec hailers.

### CODE REVIEW

**Comment by BomberBro** [comment]
Can you add a way to disable this with alt click so it doesn't clutter the HUD?

**Comment by Apogee-dev** [comment]
> 
> 
> Can you add a way to disable this with alt click so it doesn't clutter the HUD?

I would, but to be honest I barely understand how gui code works. I'll get working on it, though.

**Comment by drawsstuff** [comment]
haha yes PLEASE

**Comment by PrimeDSS13** [comment]
what is sonix so confused about bros...?

**Comment by Blithering** [comment]
Gun attachable hailers when

**Comment by Kurfursten** [comment]
Reminder

**Comment by Apogee-dev** [comment]
> 
> 
> Reminder

Sorry, I haven't actually been able to put any serious time into coding over the past couple weeks due to other work eating up my time. I'll probably do a quick balance pass on orderly once I can get back to work and then focus on finishing this one

**Comment by SonixApache** [comment]
reminder

**Comment by Apogee-dev** [comment]
Closing this one. I'm stuck on it, and probably need to axe the action button idea entirely and just go for the ctrl+click idea at a later date. I'll open a new PR when I do. In the meantime there's a lot of other code I want to work on.

**Pull request closed without merging**
