### PR TITLE
Janitor gets a utility belt and bartender gets a dress and hairpin

### PR DESCRIPTION
**Pull request by Konater**
The janitor has a bunch of small items like the wet floor signs and cleaner grenades, a belt makes his life much easier. I noticed two things in the bartender closet that I liked that weren't spawning due to the lack of src so I added it while I was in the file.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Maybe if the janitor wants a belt he should get one from the biogenerator? I don't see the need to make everything convenient, it's leading to power creep.

**Comment by 9600bauds** [comment]
They'd sooner get it from Maint

**Comment by ComicIronic** [comment]
Or cargo.

**Comment by Exxion** [comment]
That's a different type of belt
This is the base belt, and most of the belts around the station are toolbelts, which can only hold tools
Whereas the base belt can hold any small item, but only up to 7 of them (while other belts can hold 14)

Or we could go steal TG's janibelt

**Comment by mph55** [comment]
Make a new belt which you can attach the trashbag to it

**Comment by Konater** [comment]
You can only make toolbelts in the biogenerator, there's only two basic belts in the nukeop ship and a ton of them in defficiency maintenance

**Comment by ComicIronic** [comment]
It would then be better if basic belts were more widely available through some system like the biogenerator or cargo crates.

**Comment by Konater** [comment]
That's a better idea

**Pull request closed without merging**
