### PR TITLE
renames and re-icons the knife parent

### PR DESCRIPTION
**Pull request by Intigracy**
icon
inhands

Sprites taken from #10510

Same thing as #10739 but with the icon.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Oh no, my bugfixvalids!

**Comment by Intigracy** [comment]
Mine has the icon I told you about!

**Comment by FudgePucker** [comment]
Whoh I have never seen that blender before.
Does it work? Can we give it to bartender

**Comment by ComicIronic** [comment]
Why not, looks good.

**Comment by Intigracy** [comment]
@FudgePucker blending and juicing used to be two different machines.

**Comment by FudgePucker** [comment]
What about making it into some ice grinder and have some fancy blended drinks for bartender?

> wyci

**Pull request merged**
