### PR TITLE
Revert "explosions inside bodies / open containers no longer remove all chems"

### PR DESCRIPTION
**Pull request by Kammerjunk**
Reverts vgstation-coders/vgstation13#18722

Polls at 50/50 are usually closed. See http://ss13.moe/index.php/poll/144 and http://ss13.moe/index.php/poll/139
Optionally see http://ss13.moe/index.php/poll/114 and http://ss13.moe/index.php/poll/108
"the bandaid needed to be yanked off sooner or later" is a bad excuse when it's only changes you like

🆑 
* rscadd: Reverts the water + potassium change, meaning that explosions again react inside closed containers (such as bodies were)

### CODE REVIEW

**Comment by Accipitermaris** [comment]
i'm looking at the poll and it doesn't look like it was rendered in favor of the initial change, a literal tie
if the poll didn't point to it in favor, it shouldn't be forcemerged
http://ss13.moe/index.php/poll/159

**Comment by GreenHairedAssistantRickysSmellyDick** [comment]
"I'm loyal to the Republic, to Democracy"  Obi Wan Kenobi

wise man

**Comment by bathosbathtime** [comment]
Not everyday you see a 50/50 split with 40+ people.  But moderation favors the status quo and the merge should not have gone through without majority support.  I've said all I want to about the change itself and while I would be willing to accept it if it had a majority vote.  I feel it should be reverted for now and attempted again in the future ad infinitum or until a majority is edged out in favor.

**Comment by SonixApache** [comment]
agree with revert, polls are polls

**Comment by PJB3005** [comment]
> polls are polls

Brexit was also a poll.

Just sayin'

**Comment by boy2mantwicethefam** [comment]
if this pr passes how is my borg pr supposed to pass?

**Pull request merged**
