### PR TITLE
roid: all porous rocks, more reinforced rocks, remove dock lights

### PR DESCRIPTION
**Pull request by SonixApache**
🆑 
 - tweak: Roidstation: All inner asteroid rocks should now be porous, ie. safely mineable
 - rscadd: Roidstation: Added some more reinforced rocks here and there to hopefully avoid people minecraft holocausting the entirety of maint
 - rscdel: Roidstation: Removed the legacy dock lights from when the shuttle had doors on two sides

### CODE REVIEW

**Comment by Kurfursten** [comment]
Oh how I miss mapdiffbot

**Comment by ComradeDispenser** [comment]
But where did you add the new r-rock? This is important

**Comment by SonixApache** [comment]
Various small maint areas. Abandoned diner is among one of them Don't really remember where else.
Wish mapdiffbot wasn't dead.

**Comment by SonixApache** [comment]
giving deity priority

**Pull request closed without merging**
