### PR TITLE
Beekeeping 3.6.1

### PR DESCRIPTION
**Pull request by DeityLink**
Fixed an issue that could cause bees to essentially go braindead if their state-machine was on "Build" and they don't have a building location for some reason. Such bees will now go back to being homeless.

Queens can also now keep attracting a few more volunteers after they've started building their hive (up to 20 total workers)

Added a bus-only hornet minigun, based on the already existing beegun. Only a madman would actually fire it considering those things' tendencies to immediately attack the person who fired it should it not hit any mob.

### CODE REVIEW

**Comment by gbasood** [comment]
does this or the previous PR address the problems with bees literally being server-killing?

**Comment by DeityLink** [comment]
lag-wise? Well I didn't notice much lag earlier.

**Comment by gbasood** [comment]
~~You said that when we first added bees though
The current problem is they literally stop the ticker because they reach a point where they consume so much CPU because of bee swarms just being collections of mobs~~
I may have been misinformed

**Comment by Exxion** [comment]
@gbasood No, that was fixed a fair while ago, and was due to some internal BYOND fuckery
I haven't checked this build of course, but last time I did, the normal, non-server-destroying bee lag was significant but had little if anything to do with pathfinding
Specifically, the swarms lagged due to splitting (and thus generating the MoMMI static overlays, which is a ridiculously expensive proc), and the apiaries lagged due to reagent transfers
Removing letter-style MoMMI static (which doesn't currently even work) would help with the former
I haven't looked into the latter but I strongly suspect it could be optimized somehow

**Comment by Riekland** [comment]
The minigun should just be a tommy gun that shoots hornets

**Comment by DeityLink** [comment]
Also gave hornet hives their own honeycomb base color (sprite was missing), and reagents. Mostly nutriments, since their hives are almost exclusively used to store larvae, and no honey.

**Comment by nuklearcellphoneg** [comment]
So when I harvest apiaries, I can more or less get down new ones so the homeless go back in afterwards, however I wind up getting hives being put down by the bees after awhile. Once it gets to that point there's no real way to get rid of the bees without burning them all to death,. There should be a heavier delay before the bees make a new home, so that there's extra time to put down the old ones, maybe even a couple minutes extra. It can get out of hand quick, and while you're destroying one hive and moving to another to destroy, they just lay down another.

**Comment by DeityLink** [comment]
If your have had multiple bees, there's a chance not all of them moved into the new hive. I'll consider adding a delay.

**Comment by Tokanova** [comment]
Can we get a way to spade and neuter bees so they can't become this massive death swarm? Like if you get a size you like, you should be able to stop their growth somehow beyond straight up murdering them by hand with a hatchet.

**Comment by DeityLink** [comment]
What are you on about? Bees will always swarm up on you if you piss them off, and are easy to calm down with an extinguisher. If you don't want too many bees, just don't build too many apiary trays. Why would you ever hatchet down your bees?

**Comment by nuklearcellphoneg** [comment]
Once you harvest the honey, they very quickly begin to build new hives faster than you can get rid of them, as well as apiaries. I took care to harvest all apiaries at once in order to ensure no new hives were made, but some of the remaining bees were still calm, so began to build hives while I laid down apiaries back where they were, I laid down the apiaries, calmed the bees, but still had a bunch of homeless who began to make hives, and when you destroy those...

It just seems like there's no way to maintain a population and it always seems to get to a point where if you want to have a reasonable number, you're just going to have to burn them all and start from scratch.

**Comment by DeityLink** [comment]
The queens that are expulsed when you deconstruct a hive aren't angry, so they'll usually try to find a new hive right away. I can think of a two-step way to fix that issue:

* Newly placed apiary trays can only be colonized by either homeless queens or queen packets for the first 20 seconds of their existence. So if you place a hive after deconstructing an apiary, you know it won't get stolen by a queen from another apiary.
* Homeless queens have to be in the wandering state for 20 seconds before they become able to build a wild hive. Which will prevent them from starting building them before you've placed the apiary trays back down.

Additionally I could restrict wild hive proliferation by forbidding hives from being built too close from one another.

**Pull request merged**
