### PR TITLE
Adds the interrogator armor and the crozius arcanum

### PR DESCRIPTION
**Pull request by DeityLink**
imageimage

Green and red versions of this armor and their matching helmet can be bought as premium from the PietyVend. Chaplains with the imperium religion will start with the green version of the armor already equipped (debatable?). Null rods can now be reskinned by chaplains into the Crozius Arcanum.

Commissioned by Ocean Mann, sprites by keek from mercdonalds.

:cl:
* rscadd: Added the interrogator armor and helmet to the PietyVend's premium picks. Chaplains of the imperium religion will immediately wear it.
* rscadd: Null Rods can now be reskinned into the Crozius Arcanum.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Needs 🆑 

Note that it appears the Imperium chappie gets it for free

**Comment by Dacendeth** [comment]
It be nice if there was a more special version of this that was spaceworthy, not in the vendor of course that be silly.

**Comment by OceanMonn** [comment]
> It be nice if there was a more special version of this that was spaceworthy, not in the vendor of course that be silly.

A grey knight hardsuit exists in the code already on the tg side

**Comment by spoonylove** [comment]
Fuck yea.

**Comment by d3athrow** [comment]
👍

**Comment by Durgen** [comment]
Great sprite

**Comment by Kurfursten** [comment]
Normally a content PR would probably be up longer but anything this minor that Pomf has personally approved is probably fine to just merge

**Comment by Keekenox** [comment]
Oh cool thanks for putting in my sprites.

**Pull request merged**
