### PR TITLE
Reverts the simple_animal movement bullshit

### PR DESCRIPTION
**Pull request by unid15**
Reverts #11166 (except for being able to use ranged attacks)

I went too deep and tried to fuck with the mob movement code

Fixes literally every issue caused by that

### CODE REVIEW

**Comment by ghost** [comment]
But why?

**Comment by unid15** [comment]
Ah, I shouldve explained more. You can't pass the same value to walk_to and the movement delayer and get the same movespeed - I've experimented with adding various multipliers and stuff, but it can't be done without rewriting a lot of badcode.

For example client/Move() screws with the mobs movement delay for some reason. Because it isn't called for NPCs, players will move slower.

**Comment by ghost** [comment]
Rewrite the bad code. Never give up.

**Comment by unid15** [comment]
Ain't nobody got time for that

**Comment by ComicIronic** [comment]
The code was put in client/Move on some oldcoder belief that mob/Move had really poor performance if you ever modified it.

**Comment by clusterfack** [comment]
Better than leaving it the way it is

**Pull request merged**
