### PR TITLE
Revert stock parts using plastic

### PR DESCRIPTION
**Pull request by clusterfack**
Makes it impossible for me to autism as a derelict mommi, bad change bundled with good changes 0/10.
Closes #9220

### CODE REVIEW

**Comment by 9600bauds** [comment]
I'm in favor of the plastic change because it lets mechanics actually mechanic early in the shift and without depending on two different departments actually doing their job. This is a great change because collaboration being too convoluted/unreliable is terrible for everyone involved.

Derelict MoMMIS are an afterthought and the obvious solution is to just give those plastic.

**Comment by Probe1** [comment]
Honestly it's not a bad change it's a bad material.  But it's something I think we can chip away at until it works better.  One of the things is addressing it on the map by adding plastic to the derelict and RnD.  Another is to normalize the cost of parts so you don't need a calculator to guess how many you can make.

**Comment by clusterfack** [comment]
It is a bad change because its a bad material. 

Its found roundstart by deconstructing objects. That is **literally** the definition of a bad material for a tier 3 part of a tiered system.

**Comment by Probe1** [comment]
I agree wholeheartedly but I'm not ready to totally give up on it.

**Comment by clusterfack** [comment]
That's the worst argument in favor of something I've ever heard.

**Comment by Probe1** [comment]
I like the idea of having tier 3 parts (the mechanics bread and butter) tied to something the mechanic has in very limited supply at round start.  By 12:10 or 12:15 they can get started on their job and if they're very lucky have a botanist grow them more.  if they're unlucky, scan the hydroponics machines and grow their own.  

Realistically right now I and everyone else just eats up any spare air flap that they can find.  We can work at it until doing it as intended is better than cannibalizing the station for parts.

**Comment by clusterfack** [comment]
Having anything which is created solely from salvaging parts of the station is **fucking retarded and should be removed**

**Comment by SonixApache** [comment]
Originally, some tier 3 parts required miners.
Now they require botanists.

**Comment by 9600bauds** [comment]
Could be a good opportunity to redo compressed material cartridges and tie them with this new system
For the time being though, plastic is much better for the tier three parts than the old system

**Comment by Probe1** [comment]
I agree but I think we should remove it by addressing the benefits of salvaging the stations air flap supply.  We can approach it from a lot of different ways and I"m willing to be the one to do it.

**Comment by clusterfack** [comment]
As long as plastic flaps exist and give plastic, having plastic be a component is 100% haram.

**Comment by dylanstrategie** [comment]
Needs a plastic sheet stack on Derelict, in R&D, in MoMMI Nest and in Mechanics

**Comment by clusterfack** [comment]
Even if you put a few plastic sheets on the derelict that doesn't really solve the problem at all, we put in a lot of effort to make them self sufficient with the clown roid and smelter. It's still a completely limited resource.

**Comment by Probe1** [comment]
Would you take a small hydroponic setup on the D?

**Comment by clusterfack** [comment]
Not only does that sound ridiculous, it sounds completely ridiculous.

**Comment by SonixApache** [comment]
Make a cluster of plasticide grow on the clown roid? Mommis can build the rest.

**Comment by Probe1** [comment]
@SonixApache the argument we're having is people (i.e. me and everyone else that are demanding mechanics) will burn through plastic like crazy and the best approach is to skip botanists until mid game and eat up as many plastic flaps as we can get away with for sweet, sweet instant plastic.

**Comment by clusterfack** [comment]
Also I should mention that the original change to plastic was created and merged within hours before anyone had a chance to see it or discuss it.

**Comment by Probe1** [comment]
That's a good point, let's get people in on this and have the discussion it should have had. And yes, the  original change wasn't really explicitly listed and went pretty unnoticed until it was in.

**Comment by SangriaMonkey** [comment]
I don't see how being able to scavenge for usable material when you don't have someone willing to cooperate with you is a bad thing.

**Comment by Skullyton** [comment]
Changing it to plastic unkilled mechanics a little, as they no longer had to compete with science for materials to upgrade machines, all they had to do was get a good botanist, or get the plastic themselves.

**Comment by Probe1** [comment]
Custom vote started by Probe1.
What materials should tier 3 parts use?
Type vote to place your votes.
You have 60 seconds to vote.

OOC: Smoky Progg: other: bananas

OOC: Verirrten: what even is this tier 3 parts thing about?

OOC: Mikecari: I hate plastic

OOC: Mikecari: shit tier material

OOC: Probe1: truly there are people worse than mimes

OOC: Mikecari: just make it minerals

OOC: TomatoLicense: nobody grows plastic because lolweed

OOC: Qbone: Grey colored shirts

OOC: Mikecari: ^^^^

OOC: Manaony: Plastic is pretty awful

OOC: Mikecari: fuck plastic

OOC: Blithering: nutriment

OOC: Probe1: >assistants as a source of currency

OOC: Probe1: The more assistants you kill the richer you are

Vote Result: Gold, Silver, and Uranium like before with 12 votes
	Plastic like now had 5 votes
	G, S, U with tweaks to cost/recipe had 0 votes
	I don't give a fuck about this nerd crap. had 3 votes
	Plastic with tweaks to cost/recipe had 1 vote
	Other (Specify in chat) had 3 votes

OOC: Oberoth: everything needed for plastic is accessible to mechanics

**Comment by CptWad** [comment]
shit guys
just have it so that you can also make stock parts if you scan them in the genfab
but instead of uranium/diamond/etc have it replaced by plastic
gen fab uses plastic metal and glass to make shit that rnd makes with protolathes and expensive materials
they just need to scan it
boom

**Comment by Tokanova** [comment]
flesh of assistants as a material?

**Comment by Probe1** [comment]
@CptWad I'm pretty sure the genfab is too shitty to work that well.

**Comment by ihadtoregisterforthis** [comment]
Rip mechanics you had a good run

**Comment by DrCelt** [comment]
@Probe1 
>like before
Here hold on don't rig polls you know what you did here

**Comment by CptWad** [comment]
@Probe1 well how about un fuckin it
I know nobody would want to but we cant just ignore it forever

**Comment by Probe1** [comment]
@DrCelt 

suqznw4

**Comment by Probe1** [comment]
@CptWad I agree but I'm not competent enough to code it.

Regardless, it's a 2:1 response in favor of the old way with gold, silver, and uranium.

**Comment by coldcola** [comment]
I imagine at least half the people who voted in that vote had never touched mechanics or science in their careers thus barely have any idea of the rarity of plastic, that said I can definitely see how plastic can be hard to come by, I very rarely see botanists make plastellium without science directly asking.

**Comment by Probe1** [comment]
The key isn't to ask them to grow it for you.  The key is to scan their shit and ask them for the spores.  I use about 80-100 sheets per shift if I'm going light on flatpacks.  They will never grow that much just for you.

**Comment by Tokanova** [comment]
@coldcola Should Probe ask mid-round directly to scientists and mechanics, whether they'd prefer minerals over plastic?
Is that what you're suggesting?

**Comment by 9600bauds** [comment]
My take on this:
Minerals are shit and don't work out, which kills mechanics
Plastic is shit and makes no sense and also is shit but it unkills mechanics
We need to come up with something better

**Comment by Skullyton** [comment]
Why not both?

2 recipes for the tier 3 parts, one costing plastic, one costing the rarer metals?

Everybody wins but the bloated recipe list

**Comment by clusterfack** [comment]
@Skullyton That doesn't really address half the issues being raised here

**Comment by Probe1** [comment]
@Skullyton I think that was @CptWad 's pretty excellent suggestion that you print the stuff once, then scan it and use plastic to print it from the general fab.  But the problem is who will code that not me that's for sure.

**Comment by 9600bauds** [comment]
but how will you scan them if you need not-plastic to make the first one to scan

**Comment by Probe1** [comment]
Same as we did before, beg miners for just one sheet man just one sheet.

If the miner is skilled then the materials will arrive in a 5 minute window slower than the mechanic would with plastic alone.  12:10-12:15 range, with plastic 12:10 firm if you're roundstart aiming to make T3 parts as soon as humanly possible like me.

**Comment by clusterfack** [comment]
I mean, pardon my bluntness and lack of tact, but let me cut straight to the crux of the argument that is really going down between the lines of what everyone is actually saying:

A. Having a tiered part system is shit and should be removed (by making highest tier parts accessible immediately but not actually functionally removing it for some reason)
B. Having a tiered part system should lock people out of specific tiers sequentially, and having plastic invalidates that thus we should go back to the old system which helped enforce the tiers.

**Comment by 9600bauds** [comment]
The tier 2 parts are completely unnecessary desu, we could get rid of them like we did with laser scalpels

**Comment by Probe1** [comment]
The tier 2 parts are there just because some fuckass made some really bad oldcode with mechas and telecomm parts at this point.

**Comment by clusterfack** [comment]
I think there is a primary problem that occurs when we remove tiers, it's removing two concepts that we want to always preserve above all else

1. Dynamism - different things occur differently between rounds
2. Choice - people make choices based on the dynamics of a particular round

When you remove 1 and 2 the game goes from having emergent gameplay, to being a chore simulator.

**Comment by Probe1** [comment]
The point I think bauds was making is tier 2 is NEVER the choice with the exception of telecomm machinery and mechs which are hardcoded to only accept those.

**Comment by 9600bauds** [comment]
Those concepts were never present in the first place with tier 2 parts, though.

**Comment by clusterfack** [comment]
I know, I'm not saying the old system was perfect. But I'm saying when we're changing the system we should be looking to how we can maximize those two things primarily.

**Comment by clusterfack** [comment]
If I were to redo the upgrade system I would try to do it like this

1. Upgrades are now branched between various disciplines/styles
2. Upgrading gives points towards upgrades that you allocate to create machines that help with particular purposes
3. Secret components (obtainable through the random loot mechanics in game) unlock secret functions within machines

**Comment by 9600bauds** [comment]
Sounds excellent, though we're kind of short of ideas already on what part upgrades should do

**Comment by Probe1** [comment]
And even drier on people willing to code it.

**Comment by Skullyton** [comment]
Ooh, I got an idea on something for upgrades for machines.

Machines that require material resources, such as the exofab, protolathe, autolathe, etc. can be linked so that they draw from a central reservoir of materials rather than their own internal storage. Explanation behind this? Bluespace

That way, Mechanics and Scientists no longer have to compete with each other for resources cross-department, and roboticists and R&D scientists don't need to compete for resources inter-department, and makes it so that miners only have to go to one place.

>build material storage
>apply the bluespace maggufin to a machine, maybe one of those parts used in telescience? They're used in a gun that steals things after all
>acquire the frequency that the material storage is working on
>Link the material storage frequency to the machine
>Open the machines UI
>'Switch from local storage to shared storage'
>If the machine has materials inside it already, 'Dump local storage to shared storage'

**Comment by NigglyWiggly** [comment]
Okay I'm just stopping by to say:
@DrCelt >Here hold on don't rig polls you know what you did here

**Comment by Tokanova** [comment]
@Skullyton It's a neat idea but you run into an issue with it, what if someone like say the Clown gets his hands on a protolathe and a computer, and just starts mass spamming shit to make, running out all your diamonds and phazon and so on

**Comment by Skullyton** [comment]
So you make sure the clown doesn't get dat fukken frequency/multitool link

**Comment by FudgePucker** [comment]
You know what, why even have fucking plastic or g/s/u requirements for tier three parts?

They required mats to prevent making them round start, now they require plastic so they can be made round start.

This is fucking stupid.
Just make them require metal and glass and call it a day.

**Comment by PJB3005** [comment]
I mean really R&D itself is pretty fucking terrible, so that's already something that can be improved.

**Comment by Probe1** [comment]
R&D is like kudzu.  It originally had a purpose but has grown wild and untamed and _nobody_ wants to be the guy to get rid of it and make a better system of research.

tg had a neat idea with that material deconstructor thingamabob but I don't think it was super popular.

**Comment by gbasood** [comment]
@Probe1 Yep

I, for one, think we should start R&D over from scratch but so many departments are dependent on R&D things that it's going to be a huge fucking mess to do so

**Comment by SonixApache** [comment]
@gbasood You could rip out R&D and make certain things like tech disks, drills and advanced medkits orderable by cargo for the time being.

**Comment by CptWad** [comment]
@SonixApache while a blunt way to do it it might be the best way till we figure it out
maybe we can have it be more like a minigame and less like a chore

**Comment by Probe1** [comment]
i'm pretty sure most players will be much more upset if we rip out a major system and leave an IOU while 'someone' makes a new one.

**Comment by clusterfack** [comment]
Which is why in the meantime we merged this because everyone voted for it

**Comment by 9600bauds** [comment]
You and I know that server votes are pretty bad for these kind of topics, Clusterfack

I don't see any short-term OR long-term improvement this change would bring other than "ha ha suck it now you can't use plastic", which is neither a short-term or long-term improvement either

**Comment by clusterfack** [comment]
Well I mean even between plastic only 1 single person wanted to change the current system if -any- change were to be made and given the pollster I can only wonder whose vote that was.

**Comment by PJB3005** [comment]
Reminder that #9278 exists

**Comment by Imagebard** [comment]
>Vote Result: Gold, Silver, and Uranium like before with 12 votes

Why the fuck is this not here yet.

**Comment by Probe1** [comment]
because we made 1 poll once.  i thought clusterfack would poll other times but I was mistaken.

**Comment by Imagebard** [comment]
That's just smooth.
I guess the poll was made too much time ago for it to count now, anyways.

Good luck, fated PR.

**Comment by Probe1** [comment]
its a controversial change don't be pessimistic about giving the playerbase a voice.

**Comment by Probe1** [comment]
polled now

Vote Result: Plastic with 6 votes
	G, S, U with tweaks to cost/recipe had 1 vote
	Gold, Silver, and Uranium like before had 3 votes
	Other (Specify in chat) had 0 votes
	Plastic with tweaks to cost/recipe had 1 vote
	I don't give a fuck about this nerd crap. had 3 votes

**Comment by FudgePucker** [comment]
No really, remove the requirements besides glass and metal.

Now mechanics don't have to depend on the charity of miners to upgrade machines, like the requirement of plastic did, but science doesn't have to loot every flap.

What fucking balance concern is there? They aren't guns, they aren't bags of holding, they are just tier three parts.

**Comment by Probe1** [comment]
Custom vote started by Probe1.
What materials should tier 3 parts use?
Type vote to place your votes.
You have 60 seconds to vote.

OOC: Isaac the Slaver: plastic needs to be orderable from cargonia

OOC: NigglyWiggly: Plastic

OOC: NigglyWiggly: : ^ ) 

OOC: Konater: not plastic

OOC: KingcrimsonIJW: bananium

OOC: Mikecari: probe we did a vote already you goy

OOC: Konater: it was fine before with them needing silver and shit

OOC: Mikecari: plastic is shit

OOC: Tokanova: Flesh of Assistants

OOC: Mikecari: it sucks

OOC: Isaac the Slaver: What about a tier 4 that uses diamond and uranium and shit

OOC: GarethGobblecoque: we've done several votes, he's just getting an accurate smaple you goy

OOC: Probe1: the votes have been indecisive

OOC: Tokanova: Flesh of Assistants would be an excellent replacement for Plastic

OOC: GarethGobblecoque: both ARE grey

OOC: Isaac the Slaver: i agree with tokanova

OOC: Mikecari: they were pretty fucking decisive

Vote Result: Plastic with tweaks to cost/recipe with 11 votes
	I don't give a fuck about this nerd crap had 0 votes
	Plastic like now had 0 votes
	Gold, Silver, and Uranium like before had 4 votes
	G, S, U with tweaks to cost/recipe had 2 votes
	Other (Specify in chat) had 1 vote

OOC: Konater: ban whoever is voting plastic please

**Comment by Imagebard** [comment]
>Plastic

The end is nigh
In other news this PR probably should be closed.

**Comment by Probe1** [comment]
there were three polls m80

Plastic 5 + 6 + 0 = 11
Plastic + Tweaks 1 + 1 + 11 = 13
**G, S, U 12 + 3 + 4 = 19**
G, S, U + Tweaks 0 + 1 + 2 = 3
Don't care 3 + 3 + 0 = 6
Other 3 + 0 + 1 = 4

**Comment by Boxe** [comment]
excuse me

**Comment by dylanstrategie** [comment]
Excuse you

**Comment by Senaat1** [comment]
Are you supposed to merge your own (controversial) thing, Cluster? This doesn't seem kosher.

**Comment by 9600bauds** [comment]
S E L F
M E R G E

**Comment by Probe1** [comment]
Thats it I'm getting what I really want and that is a way for admins to make server polls like pomf.  This is why we need this.  Using the forums invites bullshit fake account votes.

**Comment by NigglyWiggly** [comment]
Please do @Probe1 
Also add a fucking +VOTE flag so I can take Celt's away if he ever comes back to spessmen

**Pull request merged**
