### PR TITLE
VOX Wordlist Update for November 2019

### LINKED ISSUE #25098: VOX Wordlist Requests for 11/2019
This is an issue for requesting all the words you want in the next package of VOX words. You can also list pronunciation errors so I can (try to) fix them

Words with bad pronunciations I know about but can't fix due to bugs in the voices:
* bag
* go

## Rurus
Because they apparently need to be said, and because I don't want to host this shit on gitgud.  Their upload speeds are atrocious.

* No slurs
* No lewds
* No illegals in the US of Free Speech
* If it's a sound effect, link to the sound effect and what the `_id` should be.
  * If you want it cropped out of a larger video/sound, make clear which section should be extracted or do it yourself
  * Bear in mind that sound effects are put through a series of bandpass filters and echoes so it sounds like a PA.  This will make them sound shittier *by design*, and not all sounds can go through this process without being rejected for shitty outcome.

## Current sounds
* https://github.com/N3X15/ss13-vox/tree/master/wordlists

[sound][vox][discussion][sound]

### PR DESCRIPTION
**Pull request by N3X15**
Quick PR before I have to go over to the folks' for Thanksgiving/biannual computer maintenance tomorrow. Will be out of town until the 28th (later if weather strikes).

## Summary

Adds a bunch of words from #25098, plus a bunch of extras, mostly holiday-related.

Also adds:
* `sound/AI/connection_lost.ogg` - Requested replacement for bluespace connection loss announcement
* `sound/AI/connection_made.ogg` - Counterpart to connection_lost
* `sound/AI/singuloose.ogg` - In case we add an AI announcement for singuloose.

## Related

* Closes #25098

## Changelog

:cl:
- rscadd: Added a bunch of new words to VOX announcements, including holiday-specific words.

### CODE REVIEW

**Comment by DamianX** [comment]
this is not february

**Comment by N3X15** [comment]
s-shut up

**Comment by tuypo1** [comment]
saiyan = cyan
saiyans = cyans

Lmao, better then I could have ever imagined

**Comment by N3X15** [comment]
You should have seen all the fucking gymnastics I had to do to get it to pronounce cyborgs without sounding like a drunken irishman.

CYBARGS

**Pull request merged**
