### PR TITLE
fixes self surgery / surgery on flipped tables

### LINKED ISSUE #12397: Self Surgery
If you stand on the same tile a table is on you can do surgery on yourself.
Here's a webm: http://puu.sh/rZjmV.webm

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #12397
removes /datum/surgery_step/proc/can_operate() since it's unused and just returns 1

🆑 
- bugfix: You can no longer perform self surgery, nor can you perform surgery when the person being operated on is on a flipped table.

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
> Fixes self surgery

But what was broken about it

**Comment by The-Albinobigfoot** [comment]
Self-surgery is a staple, high quality meme - don't do this.

**Comment by ghost** [comment]
Just like my favourite meme of dionas being able to carry crates, inti fixes another good feature :(.
We should open a discussion on self-surgery.

**Comment by Intigracy** [comment]
You can push over a table, stand on its tile, and perform surgery on yourself right there with the same benefits as being on a table.

Whether or not people want self surgery to stay, that specific instance is clearly a bug.

**Comment by Shadowmech88** [comment]
I agree that we need _some_ method of self-surgery, but being able to perform surgery while standing up behind a flipped table is pretty hacky.

We should come up with a better way and add that properly.

**Comment by kol1th** [comment]
@whorena 

> good feature

this is a bug lad

**Comment by NigglyWiggly** [comment]
Kolith shitposting as usual

**Comment by coldcola** [comment]
I am torn, self-surgery in some cases should be possible but flipping a table and standing on it's tile seems a bit unintended

**Comment by Intigracy** [comment]
I'll add it depending on the results of the poll I just put up, which runs until friday.

**Comment by clusterfack** [comment]
I think self-surgery of a very limited variety might be okay. Like some kind of arm bone repair or leg bone repair. 

But only a few surgery types, not all of them because that's ridiculous, and especially not because of a bug.

**Comment by Shadowmech88** [comment]
Pain should factor into it in some way, so you'd need to be on painkillers in order to mess up the surgery less.

**Comment by clusterfack** [comment]
Well remember we have stuff like eye surgery or brain surgery. I cant imagine even under every painkiller in the book that someone could do that to themselves.

**Comment by Chronakai** [comment]
It would at least give some more reason for people to make stronger painkillers.
Maybe even add a longer progress bar for doing it to yourself?

I'd suggest bone fixing, bleeding, organ fixing, implant removal and limb replacement to be allowed to start. Maybe others, but I'm sure someone has a better idea on that.

**Comment by Intigracy** [comment]
[03:07:20]ATTACK: <font color='red'>Timothy Hagano (sordine) used the station bounced radio to successfully complete surgery type /datum/surgery_step/cavity/place_item on Timothy Hagano (sordine)</font>

**Comment by Exxion** [comment]
Personally, I'd say only hard-restrict brain and eye surgery. The rest should be limited only by pain.

**Comment by Shadowmech88** [comment]
Probably all head surgery should be restricted, since you couldn't possibly see what you're doing.

**Pull request merged**
