### PR TITLE
admin ranks respect grammar rules

### PR DESCRIPTION
**Pull request by Intigracy**

### CODE REVIEW

**Comment by ghost** [comment]
It's already tumbling right the fuck down

**Comment by sonime** [comment]
Don't self merge

**Comment by Intigracy** [comment]
I merged this at the same time I merged the other grammar PR.

Your argument would hold more weight if I'd merged something that actually had an effect on the game, but to date it's been a hotfix for people pointing, this, and the confirmation box.

**Comment by sonime** [comment]
Still not a good habit to get into

**Comment by Intigracy** [comment]
he takes celt's shitposting to heart

**Comment by sonime** [comment]
what constitutes shitposting tho

**Comment by Intigracy** [comment]
I sent that 4 days ago in response to Skullyton, when it didn't work I logged in on the site and said the other thing.

**Comment by sonime** [comment]
long as it makes sense to you

**Pull request merged**
