### PR TITLE
New "vault", really just an asteroid with sick references

### PR DESCRIPTION
**Pull request by Intigracy**
tommyboy
removed egg tho
noegg

It has little in the way of loot except for a few high chance bananium spawns, the rest of the asteroid is all high chance for minerals. Plus a bunch of gibtonite, because I like explosions. There's nothing else worth grabbing from this asteroid.

### CODE REVIEW

**Comment by Probe1** [comment]
Cool.  We got a lot of SICK LOOT HOUSE vaults and this is a good addition to balance it out.

**Comment by clusterfack** [comment]
You have to post the map without the area view enabled

**Comment by Intigracy** [comment]
i cri

**Comment by Intigracy** [comment]
Updated OP with image.

**Comment by gbasood** [comment]
All these useful vaults make me want to make a maze vault that contains only an IOU.

**Comment by Probe1** [comment]
do it.

**Comment by FudgePucker** [comment]
Who needs loot houses when you have an antag spawner right there?

Hell who wants some crappy loot when you can bring aliums to the station.

**Comment by Probe1** [comment]
its just two hunters, xenobio makes worse without much effort.

**Comment by Intigracy** [comment]
egg

**Comment by FudgePucker** [comment]
And a face hugger egg.

**Comment by gbasood** [comment]
AKA equivalent of a nuke

**Comment by Intigracy** [comment]
noegg

**Comment by gbasood** [comment]
MY EGG
How will I get my daily dose of joy if there's no facehuggers for people to complain about?

**Comment by FudgePucker** [comment]
Every round should be an alium round.

**Comment by Intigracy** [comment]
This is done.

OP images are up to date, nothing has changed minus the egg removal.

**Pull request merged**
