### PR TITLE
Adds sprites to Gray(y) uniforms

### PR DESCRIPTION
**Pull request by CptWad**
:alien: 
ayy

- [x] tested
- [x] compiles
- [x] goat sacrificed to github shrine

adds jumpsuit sprites for greys wearing many jumpsuits, enjoy that waistline :alien: :eyes: :ok_hand: :tired_face: :sweat_drops: :sweat_drops: :100:

### CODE REVIEW

**Comment by SangriaMonkey** [comment]
>chins are still obscured by their suit collars

**Comment by NigglyWiggly** [comment]
Chins my dude please

**Comment by CptWad** [comment]
chins fixed, will update image shortly

**Comment by CptWad** [comment]
ayylmao
I accidently a floortile, but the chins are fixed so

**Comment by CptWad** [comment]
NFD when

**Comment by NigglyWiggly** [comment]
Merge.

MERGE.

**Pull request merged**
