### PR TITLE
Forcesay for hotkey mode: episode 2

### PR DESCRIPTION
**Pull request by DamianX**
The issue with #20826 was that opening the say window required client<->server communication, which could lag resulting in infinite sadness. So now it's done client-side.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Don't forget the F3 button.

**Comment by ShiftyRail** [comment]
So the difference between this and previous iteration is now, rather than
`push => verb => winset`, it's 
`push => winset`, or is there something else to it ?

**Comment by DamianX** [comment]
yes, before it used to be two server-side winsets, now it's all handled by the client

**Comment by strawberrytan** [comment]
gobless i hope this works so we can have m-GLORF

**Comment by SonixApache** [comment]
;HELP SEC BUFFS ON G-HRNK

**Comment by Kurfursten** [comment]
Wait, I misread the intent of this originally

Looks good

**Pull request merged**
