### PR TITLE
Rolling 20 on a cursed dice now gives you EVERY superpower

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Rolling a 1 turns you into a gods-forsaken cluwne, the only thing I regret is how much of a mouthful this is, look at the goddamn code it's activating 25 goddamn superpowers why did I do this
:cl:
 * tweak: Rolling 20 on a cursed die is now more generous with superpowers.

### CODE REVIEW

**Comment by utilitas-** [comment]
ARGH

**Comment by Kurfursten** [comment]
I don't like it. I do think your heart is in a good place, you want there to be a bigger reward 5% of the time, and I can get behind that. But it seems weird that the reward for xenoarch+luck is "finish genetics". And in the most complete sense, too. It's not like you're finishing other jobs, e.g.:
* giving the player 1 of every slime core - they'd probably want to farm more anyway
* giving the player a perfect maxcap bomb - having one doesn't give you the perfect recipe, you can keep chasing that theoretical softcap
* cleaning the entire station of gunk and trash - more will come in time
* giving you a cache of amazing rare foods - after all, the crew will eat through it in time
* giving an amazing xenoarch find like heal+charge in oxygen - there are always more out there

See, every other job still has shit to do after they get a great accomplishment. Geneticist is just fucking off to the bar or go validhunt after every power is unlocked. If someone rolls a 20, it's just "welp let's scan him and my job is fucking done". There are other ways to reward people.

**Comment by Probe1** [comment]
little bit much there

**Comment by boy2mantwicethefam** [comment]
@Kurfursten Fair enough, but I'm not sure what better reward to come up with

**Comment by Kurfursten** [comment]
How about 5-6 "amazing" foods including stuff like potent ham, sweet sundae ramen, bleach kipper, dangerously cheesy poutine barrel, Higashikata special, sunday roast, vanilla popout cake, primordial soup, clown's tears, roburger, mommi spaghetti, super bite burger, bluespaceberry muffin, power crepe. Or one cauldron full of karmotrine. What about a solid gold space pod? Or, how about what I said above? Send a global message and wipe out all trash and gunk on the station Z-level. How better to celebrate your 20 than announcing to everyone you won in the name of Mr. Clean?

I realize these are not as exciting as instant valid power but they're fun.

**Comment by boy2mantwicethefam** [comment]
Sure

**Pull request closed without merging**
