### PR TITLE
Drowsy B Gone: auto380 and fortyfive || And glock pain train

### PR DESCRIPTION
**Pull request by Optimism333**
## Drowsy Bullets No More ##
- Long ago auto380 and fortyfive rounds (used by the glock and silenced pistol respectively), were changed to apply drowsiness on hit in 2017. I'm revisiting this today in 2022 because I don't think it's great mechanically. I think the idea of certain pistol rounds applying a brief slowdown is interesting, but unfortunately that's not all that drowsiness does.

image

- Thanks to this block of code in life.dm, every tick that your drowsiness is above zero, you have a 5% chance to keel over paralyzed and fall asleep. I think this is a silly effect for these pistol rounds to apply, so I've removed the drowsiness value from the two projectiles.

## A Glock Compromise ##
Some players have fairly noted that this is a significant nerf to glocks, so I've made a compromise.

- **Compromise:** Glocks now deal 15 agony damage, compared to the 1 agony they dealt previously. Targets that get hit by several rounds are liable to go into shock, or even become completely incapacitated by the pain.

[tweak] [balance]

:cl:
 * tweak: auto380 and fortyfive rounds no longer apply drowsiness on hit
 * tweak: Glock auto380 rounds apply significantly more pain on hit. agony: 1 ->15

### CODE REVIEW

**Comment by pedr69** [comment]
if glox no longer slowdown on hit they're absolutely fucking useless
why would officers ever use em instead of shotguns/lasers
even with the current slowdown they're never used

**Comment by Optimism333** [comment]
> if glox no longer slowdown on hit they're absolutely fucking useless why would officers ever use em instead of shotguns/lasers even with the current slowdown they're never used

Regardless, applying that slowdown with an effect that can randomly put you to sleep is very bad design, imo.

This is effectively a nerf to the regular glock rounds, but from what I've heard, people who use glocks for stuns/incapacitation use the rubber rounds anyways. Since they stun and have a much faster projectile speed than a taser bolt.

**Comment by WindowsErrors** [comment]
I think the reason why it exists is to convey a sense of "stopping power" with drowsiness being the best available method (at least for 2017) of simulating it

That being said, 
> if glox no longer slowdown on hit they're absolutely fucking useless
why would officers ever use em instead of shotguns/lasers 
even with the current slowdown they're never used

I was going to say it less bluntly, but sort of what you said, the .380auto bullet does _15 damage_ (for reference a full extended magazine would do 315 damage if you hit every single shot, not even enough to kill a Spider Queen at 500 health) and I think the quasi-stopping power mechanic is probably what's kept it remotely relevant all this time

**Comment by Optimism333** [comment]
I'm not an avid security player, but I don't see why the glocks would be completely unused after this change. Ballistics always have certain advantages over lasers: not requiring recharge, not vulnerable to EMPs. Glocks also can be dual-wielded to deal a slightly more respectable 30 damage per double shot. And it could certainly still be a viable pocket pistol for a random crewmember, who might not have access to all of sec's fancy gear. Any ranged weapon is better than none.

I don't think that a small ballistic sidearm has to be comparable to a shotgun or laser gun, regardless. It's a cheap sidearm. Why should it be used on a spider queen, except as a last resort? That's a very odd example.

**Comment by Optimism333** [comment]
If you really think this leaves the glocks in a real bad spot, maybe I could slot in an increase to their base magazine capacity: 

- From 10 rounds to 15

I'd prefer that to giving them a flat damage increase per bullet.

**Comment by Eneocho** [comment]
Their point is that for securing them balids you want the weapon to fill a niche. If it's sheer damage you can always use the combat shotguns with slugs or buckshot. If you want stuns you can also use the shotgun with benabags or a taser/egun. No real niche for glocks if the slowdown is removed (though I hate it with a burning passion and I'm glad to see it gone).

**Comment by Optimism333** [comment]
> Their point is that for securing them balids you want the weapon to fill a niche. If it's sheer damage you can always use the combat shotguns with slugs or buckshot. If you want stuns you can also use the shotgun with benabags or a taser/egun. No real niche for glocks if the slowdown is removed (though I hate it with a burning passion and I'm glad to see it gone).

Rubber bullets in the glock are still pretty good for stuns. Much faster than taser bolts, even if the stun is shorter. People just rarely use them.

But yeah, I'm not looking to make the glock a desirable component of the sec weaponry meta that stands up to shotguns or laser weapons. I'm removing what I see as a poorly implemented mechanic that has unintended consequences.

If a compromise has to be made for that to happen, hopefully it's something reasonable.

I'm willing to do the base magazine capacity increase, as stated above.

**Comment by Eneocho** [comment]
One issue I've found with the rubber bullets is that most players connect "bullets" with "lethals" regardless of the variant, so they go unused.
From the perspective of the one getting shot, the secoff skipped all escalation and jumped to lethals, despite the bullets being rubber (you don't know if the bullet is rubber or not until you get hit, and that's a huge gamble if the bullets turn out to be lethal).
Increased magazine carries its own set of balance issues, such as how many mags can you refill with the ammo box, but it is a good middle-ground.

**Comment by Optimism333** [comment]
> Increased magazine carries its own set of balance issues, such as how many mags can you refill with the ammo box, but it is a good middle-ground.

Fair enough. I'll wait a bit to see what more players think, but I'm fine with having that be the compromise.

If that's what I end up going with, I'll have a look at the ammo box too.

**Comment by WindowsErrors** [comment]
> One issue I've found with the rubber bullets is that most players connect "bullets" with "lethals" regardless of the variant, so they go unused

One of my favorite rubber bullet moments is when the detective insists that rubber bullets are nonlethal and then shoots someone to arrest them before I subsequently tell them that they need to take them to medbay because the rubber bullet caused a life threatening case of internal bleeding

**Comment by Optimism333** [comment]
> > One issue I've found with the rubber bullets is that most players connect "bullets" with "lethals" regardless of the variant, so they go unused
> 
> One of my favorite rubber bullet moments is when the detective insists that rubber bullets are nonlethal and then shoots someone to arrest them before I subsequently tell them that they need to take them to medbay because the rubber bullet caused a life threatening case of internal bleeding

**Something inside your chest HURTS.**

You are correct though, using rubber bullets as "nonlethal" is shitty sec behavior. They shouldn't come out unless lethals have already been authorized.

**Comment by jwhitak** [comment]
Nerfing an already poor performing weapon class... At least give it something to compensate. Pain? A slight +1 to damage (totally innocent, this won't add a chance to gib max damaged limbs....)?

The reason for the nerf is good, but it leaves glocks worse off.

**Comment by Eneocho** [comment]
> You are correct though, using rubber bullets as "nonlethal" is shitty sec behavior. They shouldn't come out unless lethals have already been authorized.

A solution for that would be to make rubber bullets actually non-lethal, not causing any internal or external bleeding and just some minor brute damage (bruises), but rather causing fatigue (like the holographic eswords that eventually cause you to fall over).

**Comment by Optimism333** [comment]
I've been negotiating with the glock lobby. I'll look at the code later for glock magazines and the ammo box.

It's not finalized, but I think the magazine capacity increase from 10 ->15 is a fair trade to leave the glock lovers less unhappy with the change.

**Comment by WindowsErrors** [comment]
To be fair at this rate I don't think too many people would complain if it was just cut or straight up replaced with something better, I think the original security pistol was supposed to be the NT USP which was fortyfive but I donno what happened to that since I wasn't around for when this stuff was being added

I understand that it's a ballistic and that makes it "special" but what does the NTGlock have going for it even pre-nerf? Concealability? Redshirts aren't exactly in the concealability market hence their name, the detective already has the revolver, and even as a cargo worker I prefer throwables like fuse bombs, flashbangs, tear gas, grenades, and bolas because they're straight up more reliable, and rubber bullets are also kind of a meme because they're supposed to be less lethal but as we said it's considered shitcurity if you use them as such

**Comment by ValkyrieSkies** [comment]
Why can't we just add a slowdown debuff and apply that to the bullets? Isn't that the simplest solution?

**Comment by pedr69** [comment]
yeah, why not use the holographic pain damage?
>you're too exhausted to keep going

why's the tazer electrode the only thing that has that, not stunbatons and rubber rounds

**Comment by Optimism333** [comment]
> yeah, why not use the ~holographic pain~ agony damage?
> 

Bullets do deal agony damage, just a very small amount. It increases with higher caliber bullets, generally.

Glocks deal the least, at a whopping 1 point of agony damage.

**Comment by pedr69** [comment]
so, to get a man agonised enough to walk slower after being shot with lethal glock bullets, you need to shoot him.... 30 times, and i think he's gonna have bigger problems than slight pain by then
why not bump the agony damage to ~15-30?
or a separate slowdown like shifty said

**Comment by Optimism333** [comment]
> so, to get a man agonised enough to walk slower after being shot with lethal glock bullets, you need to shoot him.... 30 times, and i think he's gonna have bigger problems than slight pain by then why not bump the agony damage to ~15-30? or a separate slowdown like shifty said

Okay. I'll do some tests with higher agony numbers, and see what a decent one is.

**Comment by Optimism333** [comment]
> Why can't we just add a slowdown debuff and apply that to the bullets? Isn't that the simplest solution?

For a better coder than me, probably. For me, that'd be more difficult. I haven't played around much at all with movement buffs or debuffs.

I'm going to try giving glock rounds a higher agony value and see if that works well enough.

**Comment by ghost** [comment]
the simplest solution is to have the bullets inflict an amount of pain high enough to cause slowdown, no special code is necessary

**Comment by PrimeDSS13** [comment]
Instead of removing the effect entirely because of a strange property, perhaps it's possible to just give it the effect of slowdown and blur? I like the effect, but I was unaware it was literally putting you to sleep. I feel like changing the damage or magsize is just a bit of a weird stopgap fix for what is already a weak weapon.
Alternative, Ancients idea.

**Comment by Eneocho** [comment]
Increase agony then make it so rubber bullets can't shrapnel nor IB.

**Comment by Optimism333** [comment]
Okay, so. Glocks have been beefed from 1 agony -> 15 agony per round. This has some fairly serious effects.

I wouldn't say this makes glocks better against soft targets, since it doesn't slow on hit and they'd likely fall into crit before the pain takes effect. However, hard targets (ones wearing armor), will find themselves dropping into paincrit after about 8 glock rounds are emptied into them. Even if they don't go into paincrit, it's likely they'll quickly go into shock unless they find some painkillers.

I think this is a reasonable compromise. Top post has been updated to reflect the new stats.

**Comment by Theophrastus1** [comment]
alright, remove the drowsiness but up the pain and embed chance

**Comment by SonixApache** [comment]
the real solution would be to add a new effect that only causes slowdown without the chance of dropping into paralysis
or just replace the glocks with pepperball guns that only do agony damage

**Comment by wotisjanitor** [comment]
go away sonix

**Comment by BurntDevil** [comment]
The agony change keeps glocks competitive. If you dont think glocks are currently, or wont still be after this change, you do not know the way of the glock. The slowdown was not the appeal of the glock.

**Pull request merged**
