### PR TITLE
Glock full-auto modkit, magwell expansion kit, minor unatomic changes

### PR DESCRIPTION
**Pull request by SonixApache**
+ Added a glock full-auto modification kit. When applied, forces the gun to empty the magazine in one burst. Has a small but multiplying chance to jam on every shot. Accuracy decreases for every shot fired. Removable by screwdriver. Currently unobtainable. Codersprite.
 + Added a universal magwell expansion kit. Works on any gun that has stuff in it's `mag_type_restricted`. Removable by screwdriver, single-use. Currently unobtainable. Codersprite.
 + The full-auto kit is powered by overlays. The code isn't great, but writing this gave me a good indication on how to make other gun attachments into overlays. I'll do a thing for the suppressor soon.
 + When inserting or removing a magazine, it now tells you the name of the magazine.
 + Fixed a grammar error with clearing jams.
 + Added a description to the silencers.
tinyattachmentmodkits_codersprite

🆑 
 - rscadd: Added a universal magwell expansion kit that removes magazine restrictions from guns, and a full-auto conversion kit for glocks. Both are unobtainable for now.
 - tweak: Loading and unloading magazines now tells you the name of the magazine. Silencers now have descriptions. Fixed a grammar issue with jammed guns.

### CODE REVIEW

**Comment by dunsel-hordon** [comment]
make it a tator item. Can you imagine you just sitting up there and tator just comes up and dumps an entire mag into your skull pointblank range.

**Comment by DrSnips** [comment]
If only click and hold did anything besides clickdrag. _I think adding a rubber band to the sprite might reflect the ability well._

**Comment by Kurfursten** [comment]
You don't need a :cl: for unobtainable items

**Comment by SonixApache** [comment]
No but I *want* it so the admemes might, by the grace of god, actually read the changelog and learn about my works.

**Pull request merged**
