### PR TITLE
If you die on a plasmafire, you become a plasmaman

### PR DESCRIPTION
**Pull request by Zth--**
Now if you die on a plasmafire, you become a plasmaman (you have to hit the threshold). And if you keep getting burns after husked, you become a skeleton.

The config was modified for this, so you'll have to update yours.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
So if you take enough burn damage to become a skeleton and then get cloned, will you come out of the cloner as a skeleton?

**Comment by Zth--** [comment]
Yes

**Comment by ComicIronic** [comment]
You still have to add the config code in, and you should give the option of setting these things to negative to disable this behaviour.

**Comment by Zth--** [comment]
Ok, will do later. I'm gonna tweak this numbers with the incinerator to make sure numbers are ok. Oh, and don't forget plasma fires will be a bit more deadlier.
Maybe you should turn into a plasmaman instead of skeleton? It's open to discussion

**Comment by ComicIronic** [comment]
I'd support it being a plasmaman, it makes more sense.

**Comment by Exxion** [comment]
Only if you died in a plasma fire

**Comment by Zth--** [comment]
@Exxion I don't think there's an easy way of doing it.
I'll leave it like this for now, tonight I'll do some more testing

**Comment by clusterfack** [comment]
Makes a lot less sense thematically than the dissolve power for skeletonis. It would make a lot more sense for plasmamen though.

**Comment by kol1th** [comment]
Isn't cloning skeletons fucked?

**Comment by Zth--** [comment]
Yeah, it makes sense for plasmamen. The thing is, since we don't have different types of burn damage, you could technically laser someone to plasmaman, which wouldn't have much sense.
The other issue with becoming plasmamen is that there's no way of obtaining hardsuits, but I can work on it.

@kol1th I have no idea

**Comment by Exxion** [comment]
You can order plasmaman suits from cargo

**Comment by clusterfack** [comment]
Yeah maybe if their clothes were contaminated or there was plasma in the air or in their blood when they were died/husked

**Comment by kol1th** [comment]
@Zth-- Well, last time I tried to clone a skeleton, they gibbed in the cloning pod. That was after putting their head on a monkey man body.

**Comment by Zth--** [comment]
@Exxion Oh, I didn't know. I just came back from a ss13 break so well, it's new for me.
@clusterfack I implemented the contaminated clothes thing. It's a bit hacky but it works
@kol1th Hm, I'll take a look at that after this PR

I removed the dust thing, and updated the description. I think nothing's missing, is it?

**Comment by Imagebard** [comment]
This is actually a nice way to nerf plasmafloods, if it also revives the targeted person in question.

**Comment by Imagebard** [comment]
Well if its a plasmaflood they would die again.
I don't really know now, whatever.

**Comment by Zth--** [comment]
No, they don't revive. (Why whould they?)

**Comment by SkowronX** [comment]
So uh, plain white plasmasuits for victims then?

**Comment by Imagebard** [comment]
Why would they be dead in first place, after being converted into plasmamen?

**Comment by Zth--** [comment]
I can't imagine humans being magically converted into plasmaman in a plasmafire right after dying. I imagine it like someone found those dead corpses and decided to revive them after having decided they would work for them.
Yeah I'm high as fuck and I'm enjoying this conversation. Sorry if I'm a bit unclear, english is not my first language

**Comment by Imagebard** [comment]
I don't know, the thought of people suddenly going

>OH GOD, THE DEAD PEOPLE ARE TWITCHING AND TURNING INTO PLASMAMEN

Is entertaining for me

**Comment by icantthinkofanameritenow** [comment]
I don't know about you, but something about this PR really doesn't seem right to me. It might be the forced race change part or the fact that all those new plasmamen are fucked if Cargo is either absent or a bunch of shitters, but I really get the feeling this needs a trial round or two on the test server to see how it'll work in practice first. 

Zth-- being high as a kite right now is not doing much to answer my concerns.

**Comment by Ephx1** [comment]
I lllllllllike it! 

But it should definitely only be a percentage chance to properly become a purple-shitter, it's very likely a "threshold", whatever it is, to be reached due to how zealous incredibly boring AI/Atmos techs get with their plasmaflood.

The requirement of a suit _is_ worrying, but I can't see it being too much of an issue, just order suits for the corpses piled up at the cloner.

**Comment by jknpj** [comment]
> Why would they be dead in first place, after being converted into plasmamen?

You need O2, plasma and a spark/fire to begin a plasmafire. Plasmamen ignite on O2 and they also breath plasma and exhale o2. They'll literally start a plasmafire and "die again" as soon as they turn into plasmamen. Unlike vox, plasmamen living without internals in plasma atmos is but a dream. And without plasma in the air you'll just burn and gasp to death.

But yeah, seems like they are "reborn" as plasmamen rather than keep living as one. That would explain why you're not going back to being a human, even after being cloned: "Many xenobiologists wonder if the unknown properties of plasma may actually have some life-giving properties, as evident by their mysterious clutches on a semblance of their previous life." t. muh lore.

**Comment by icantthinkofanameritenow** [comment]
@Ephx1

I can envision just many people insisting they be cloned again so they can come back as humans. Hasn't it occurred to you that if someone wanted to be a plasmaman they would be one at roundstart? 

This is basically the nonantag equivalent of emagging the cloner and turning every new clone into a catbeast, now that I think about it.

**Comment by jknpj** [comment]
Maybe we can keep plasmamen perma-friendly-like suits in every emergency locker, or at least at medbay and toxins.

@icantthinkofanameritenow You won't come back as human after being cloned.

**Comment by Ephx1** [comment]
@icantthinkofanameritenow 
Hasn't it occurred to you that if someone wanted to die they would just observe?

The idea is that it's an effect of plasmafires, we're not forcing it on them, in a way it is I suppose, but in the same way you force someone to be dead as the result of a plasmafire.
That's like saying "Hasn't it occurred to you that if someone wanted to be a Slime, they would just go to xenobio?", then a wizard pops up and oh... they're a slime now.

How the fuck is it the nonantag equivalent of anything, WHY THE FUCK WOULD YOU BE PUMPING PLASMA AS A NONANTAG?

**Comment by jknpj** [comment]
Forgot to ask, this change only applies to humans, right?

**Comment by icantthinkofanameritenow** [comment]
Well, my main objection.is that at least when someone dies, they can be generally assured that when they are cloned they will come back as the same race as they were pre-cloning. While jknpj's idea is reasonable enough to answer the issue of what happens if cargo isn't around, the fact that such a contingency needs to exist in the first place is somewhat troubling. 

Basically, my main objection is that this seems to serve no real purpose. The staff of transformation is suited to mass produce catbeasts and clomer emagging is meant primarily for identity theft, but this just seems to be here for...I don't know, to throw a bone to the lore that all of three people seem to give a shit about at any given time?  (Hell, even if you did care I would note that plasmamen were transformed while they were alive, not after they died - and skeletons were created by the Space Wizard Federation and have nothing to do with plasma at all.)

**Comment by Ephx1** [comment]
Half of the shit in the game serves no real purpose, merely for shit to occur and be interesting. It's a mechanic made to build on the """"""""Lore"""""""" and generally be fun. It also adds some goddamn flavor to the millions upon millions of plasmafloods that occur, something different to being burned into a searing blaze within five seconds, sure it's very minute but for the love of fuck it's SOMETHING.

**Comment by Zth--** [comment]
> (Hell, even if you did care I would note that plasmamen were transformed while they were alive, not after they died - and skeletons were created by the Space Wizard Federation and have nothing to do with plasma at all.)

Then why, if they transformed while they were alive, their hardsuits transformed too? Plasma transforms suits to your size too?

Didn't we have a problem with tons of non-ss13 references? Well, this is a mechanic that fits our lore.

@jknpj Humans and mutant humans

**Comment by jknpj** [comment]
@Zth--

> It was confirmed recently that Plasmamen are indeed the victims of station-engulfing plasma fires and were the poor souls who happened to reach EVA or medbay to don biosuits in order to keep themselves alive. As apparent of their husks condition, this no doubt proved fruitless.
> 
> Plasmamen are the husked, charred remains of previous Nanotrasen employees who were recovered in ERT missions in order to send the remains back to their families. ERT found many of their supposedly extinguished employees locked within biosuits with no previous memories and only a fragment of their personalities.

**Comment by icantthinkofanameritenow** [comment]
@Zth--

They weren't transformed with them, they were always meant as hazmat contaiment suits (which I only assume were better at keeping play in better than keeping it out). 

Anyway, if you must put this in there should be a way for people thus transformed to change back to humans if they so desire. Even if it's just a brain transplant or something . 

@Ephx1

All that aside, I don't see how this mechanic can be fun since you'll be burning to death in a plasma fire anyway- there's just a chance you'll come back wrong after you're cloned too is all. I know I at least wouldn't want to come back as a plasmaman after dying in a plasma fire if I had a choice, so surely it wouldn't be too much to ask if you made it based on a percentage as.well as a threshold? That way even being stuck in a plasma fire  for a short time.after dying in one isn't guaranteed to turn you into a burning purple skeleton afterwards.

**Comment by gbasood** [comment]
self-perpetuating fires in escape generated by the corpses of the dead
because that's a great idea
:eggplant:

**Comment by Zth--** [comment]
Lost interest in this one, feel free to pick up the code and modify it

**Pull request closed without merging**
