### PR TITLE
Skinning animals on meatspikes

### PR DESCRIPTION
**Pull request by RealestEstate**
Using a sharp object on a meatspiked creature will allow you to quickly skin it for its hide.
Using wirecutters will extract teeth (and claws from xenomorphs)

TODO before merge:
- [x] add teeth removal
- [x] Examine shows butchering products which remain.
[content]
[qol]
:cl:
 * rscadd: Meat-spiked creatures can be skinned with sharp objects and deteethed/declawed with wirecutters.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you still cut off the meat after skinning?

**Comment by RealestEstate** [comment]
you would normally use an open hand to remove meat. applying a sharp object once the skin is gone does nothing. You can continue to remove meat once the creature is skinned.

**Comment by Eneocho** [comment]
very nice
can you make it so using a wirecutter cuts off the teeth?

**Comment by RealestEstate** [comment]
ready for review

**Pull request merged**
