### PR TITLE
Adds a second pinpointer to the hos locker

### PR DESCRIPTION
**Pull request by tuypo1**
Adds a second pinpointer to the hos locker, It's too easy for the single pinpointer the station has to just go missing
Note that this is not a repeat of my previous PR why was an attempt to add a pinpointer pinpointer

🆑
Adds a second pinpointer to the head of securities locker

### CODE REVIEW

**Comment by bathosbathtime** [comment]
How does this interact with the "steal the captain's pinpointer" objective?

**Comment by tuypo1** [comment]
Actually that's a good question, I failed to consider that.
I assume both would count like the captains armor objective but maybe it could be tuned up to only work for the caps

**Comment by Blithering** [comment]
You could just change the text to "steal a pinpointer" but with solo objectives imminent removal, I wouldn't bother

**Comment by bathosbathtime** [comment]
It is a little thing so I wouldn't worry too much about it, but if you are going to do something I would also recommend just removing "the captain's" from the objective since I would almost call it harder to steal from the head of security.

**Comment by ShiftyRail** [comment]
What about a pinpointer pinpointer

**Comment by tuypo1** [comment]
>What about a pinpointer pinpointer

I made that PR a couple weeks ago and it was very controversial compared to the mostly positive reception this has received. Maybe if this gets merged and it goes well I will see if people are open to changing it a few months down the line.

**Comment by utilitas-** [comment]
\>pinpointer pinpointer
the most stupid fucking way this could be solved
just make the pinpointer a non-controversial item and therefore allow for multiples, or at least give it more functionality to make it actually worth carrying around even outside of nukeops.

**Comment by SonixApache** [comment]
there's too much shit in the locker already

**Comment by tuypo1** [comment]
I don't know how you could still think that after it was massively condensed a few months back.

**Comment by SonixApache** [comment]
still too much shit

**Comment by utilitas-** [comment]
then put it in the armory/warden's instead

**Comment by Blithering** [comment]
I'd say put it on the desk, but that's mapping rather than just locker list editing.

**Pull request merged**
