### PR TITLE
Replaces goon arcade floor sprite

### PR DESCRIPTION
**Pull request by Intigracy**
Because I remember someone complaining about it in IRC.

Skowron made this.

### CODE REVIEW

**Comment by PJB3005** [comment]
That is literally eye burning.

**Comment by Intigracy** [comment]
:^)

**Comment by Intigracy** [comment]
doot doot updoot

**Comment by SkowronX** [comment]
arcade

**Comment by Intigracy** [comment]
doot doot updoot

thanks skowron

**Comment by Zth--** [comment]
we're still missing the item though

**Comment by Intigracy** [comment]
What do you mean?

**Comment by PJB3005** [comment]
@Intigracy you can't currently place these carpets, there is no floor tile item for them.

**Pull request merged**
