### PR TITLE
Fabricator and Lathe upgrade buff 2.0

### PR DESCRIPTION
**Pull request by jakmak3**
Old Pr--->https://github.com/d3athrow/vgstation13/pull/12689

This PR changes the behaviour of micro lasers and micro manipulators, esentially swapping their effects on machines around.

As it currently stands, micro lasers makes machines save on materials,roughly 3-5% for T3 parts, while micro manipulators makes building things faster, T3 parts saving 1-2 seconds on manufacturing time
This, of course, is very weak and offeres no reason to upgrade fabricators and lathes.

This change swaps what manips and lasers do by having manips save reasources and lasers save time and vice versa, since all fabricators have manipulators, but only a few of those have lasers in them, while those said fabricators would also have some of the objects that take the longer to produce.

In this change upgrading both the manipulators on the protolathe to T3 pico manips can easily shave off 30% of reasources while the autolathe can save around 15 to 20 percent when upgraded to T3.

This change is also noticable on spacepod fabricators and exosuit fabricators as being 30-40% cost reduction depending on which machine.

For the lasers this is not applicable to auto and protolathes since they lack lasers but for all other fabricators this bonus is noticable.

For spacepod fabricators it reduces the time needed to construct a spacepod frame piece from 2 minutes and 30 seconds all the way down to 40 seconds per space pod frame part.
On the flatpacker this reduces construction time from 16-20 seconds per flatpack to 5 seconds per flatpack.

On exosuit fabricators for a robot endoskeleton it takes 20 seconds as appose to the 2 minutes needed on a upgraded exosuit fab.
This change is, of course, balanced out by the fact that in order for these changes to be seen, it requires scientists to make a RPED and upgrade machinery, which requires time; both to finish R&D and to wait for the miners to gather minerals.

Remade due to DMCA

:cl:
_*_ tweak: Rebalance fabricator and lathe part upgrade effects
_*_ tweak: Microlasers now increase production speed
_*_ tweak: Manipulators Now reduce item price
_*_ tweak: Pico manipulators now cost silver and uranium. Super matter bins unaffected

### CODE REVIEW

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/pull/12688
https://github.com/d3athrow/vgstation13/pull/12687

Additional old PRs including that this has been folded into, including a very controversial and unpopular one whos changes are now included.

**Comment by aceedex** [comment]
With how little things are upgraded it's good to see stuff like this. My own qualms is that most of the benefactors are people with direct access to upgrade mahcines, so aid definitely like to see bigger improvements on non-sci machinery. 

Still, baby steps are good

**Comment by aceedex** [comment]
Id also like to add that since this is a really strong change, then maybe the price of the RPED should go back to costing rare mata

**Comment by jakmak3** [comment]
i intend to attempt to make the chem machines, cloner, and cryo better soon

Like if the upgraded chem disp could vend plasma, minerals (in chem form), and pre made chems
And the chem master 3000 being able to make bigger pills
and the cryo if upgraded increase the amount of reagents thrown against the user
and the cloner if fully upgraded could do autoproccess

**Comment by kol1th** [comment]
>bigger pills

Never do this

**Comment by jakmak3** [comment]
why not kolith? Name any other worthwhile bonus upgrading the chem master 3000 can give that is not already currently in game

**Comment by kol1th** [comment]
We should remove mechanics instead

**Comment by aceedex** [comment]
I'll remove you
http://img.gawkerassets.com/img/17sg680qxi0pejpg/ku-xlarge.jpg

**Comment by 9600bauds** [comment]
Pico-manips requiring minerals had a very negative reception, just saying

**Comment by jakmak3** [comment]
what it initially was is that i botched the first few PR's and the price rise was there and the explanation for it was the next PR which thanks to git took a half hour to do. I still feel that for this level of upgrades all T3 parts excluding matter bins should cost minerals just because this would be way to OP to have with T3 pico manips just costing metal.

**Review by PJB3005 — APPROVED** [review]

**Comment by aceedex** [comment]
Now to figure out what item to decon to get materials 5

**Comment by jakmak3** [comment]
super matter bins yo

**Comment by Probe1** [comment]
@jakmak3 CL

**Pull request merged**
