### PR TITLE
Halves the cost for wizard cooldown upgrades

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Finally, no more spending extra 80 points just to reduce the cooldown from 40 seconds to 30 (Mutate does this with a reduction of 2.5 seconds per cooldown upgrade)
For what it does this was ridiculously easy to add, just 3 lines. This could've been two lines but I wanted to add a variable for people to be able to tweak the spell's cost.
This was also done at 4:45AM so forgive me if there's any oversight, I'll rectify it tomorrow but I did test it and it works fine
Blink and Summon Pitbulls are not affected by this change.

:cl:
 * tweak: Wizards now pay half the spell's cost when upgrading the spell's cooldown instead of the entire spell cost, except for Blink and Summon Pitbulls which had their cooldown reduction price intact.

### CODE REVIEW

**Comment by dunsel-hordon** [comment]
Certain spells should be excluded like blink or jaunt. Things that make the wizard to hard to catch

**Comment by boy2mantwicethefam** [comment]
Balancing might come tomorrow because it's 5AM and I really want to sleep

**Comment by gurfan** [comment]
finally

**Comment by GreatBigFailure** [comment]
I say omit blink and maybe pitbulls and it's a great change. Most upgrade costs, especially cooldown, are ridiculous.

**Comment by DamianX** [comment]
awful

**Comment by GreatBigFailure** [comment]
> awful

Why? Doing it on an individual basis would be better but blink and pitbulls are the only ones I can really think of being a problem out the gate. Might make some spells less awful too. Pacify for example might be usable.

**Comment by DrSnips** [comment]
Blink is extremely offensive even right now and if anything I think it should be doubled.
There is never not a conversation about wizards were blink come up as a concern for some reason

**Comment by Theophrastus1** [comment]
ah yes, i sure LOVE almost FREE blink

**Comment by gurfan** [comment]
> ah yes, i sure LOVE almost FREE blink

it says right above your comment that the blink price is unchanged

**Comment by Kurfursten** [comment]
does it warn the wizard somewhere in the spellbook that these 2 spells cost double for reducing cooldown?

**Comment by GreatBigFailure** [comment]
> does it warn the wizard somewhere in the spellbook that these 2 spells cost double for reducing cooldown?

I think if you click on the upgrade it tells you its cost. If we don't have some way of showing upgrade cost we really, really need to.

**Comment by boy2mantwicethefam** [comment]
Only if you buy it it shows the cost and stuff

**Pull request merged**
