### PR TITLE
[WIP] New icon for smart lasers

### PR DESCRIPTION
**Pull request by Blithering**
smartlaser
Makes smart lasers easier to identify at a glance, so you know whether the gun on the floor is free loot or an irate turret with nothing to lose.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Does it look any different when there's a pAI in it?

**Comment by Blithering** [comment]
Not currently, I'm a bit too shit at coding to know how to do that for now.

**Comment by Shadowmech88** [comment]
Make the sprite anyway and post it in an issue, maybe someone else will add it.

**Comment by Kurfursten** [comment]
for proc update_icon()

`icon_state = "laser_smart[integratedpai ? "1" : ""]"`

Then have laser_smart1 be the icon name of the one with the pai and call update_icon() from install_pai()

**Comment by Blithering** [comment]
Closing due to githubbery, will reopen when I figure out the update_icon stuff

**Pull request closed without merging**
