### PR TITLE
another try at d*b

### PR DESCRIPTION
**Pull request by SirSkeleto**
:cl:
 * tweak: reverses april fools requirement for a certain emote

### CODE REVIEW

**Comment by beesil** [comment]
put me in the screencap

**Comment by ShiftyRail** [comment]
Ebin

**Comment by Coxswain-Navigator** [comment]
The hero we need and deserve.

**Comment by Kurfursten** [comment]
Stop posting PRs without a description or changelog unless it's for April Fools.

**Comment by aceedex** [comment]
Technically dabbing now surpases the 1 year clause on addming memes to the game but I dont like it

**Comment by bathosbathtime** [comment]
Relevant poll: https://ss13.moe/index.php/poll/178

**Comment by MadmanMartian** [comment]
I've come back from the dead to tell you to stop.

**Comment by SirSkeleto** [comment]
"R0B0/Madman Martian has resigned as a collab and departed from our community."

Why are you still invested in how super serious our game is when people very clearly want this feature? @MadmanMartian

**Comment by Intigracy** [comment]
didn't pomf veto this the last time you did it

**Comment by DrSnips** [comment]
Local robo just won't let go. More at 7.

**Comment by SonixApache** [comment]
fuck off

**Pull request closed without merging**
