### PR TITLE
Makes warping claws harder to find

### PR DESCRIPTION
**Pull request by tayachiya**
Changed a "100" into "25" which in theory should make Warping Claws 4 times harder to find

:cl:
* tweak: All dug up! Warping claws are now much rarer in xenoarcheology.

### CODE REVIEW

**Comment by robintime** [comment]
thank you for your service

**Comment by BomberBro** [comment]
very cool changelog

**Comment by APCUnlocked** [comment]
God bless you for this, it's time for the x*noarch metaclub to pay for their crimes

**Comment by spacedgod1** [comment]
dumb grudgecoding. There are so many things like hand teleporters and subspace tunnellers that accomplish similar things to the claws and don't even require xenoarch. Also since when does reactionary coding get so many thumbs up?

**Comment by Spyroshark** [comment]
maybe because someone getting the claws every round and opening up a portal every 2 seconds in the halls is annoying as hell

**Comment by anunknownentity03** [comment]
thumbs up from me.

**Comment by spacedgod1** [comment]
Seems like this is a hot PR rn, but I think the server should have the final say on this. Why not put it to a vote instead of letting G*thub users decide unilaterally?

**Comment by anunknownentity03** [comment]
this pr doesn't change enough in order to warrant a server pol

**Comment by spacedgod1** [comment]
Since when do you get to decide that? Just going off the handful of comments so far, xenoarcheology is consistently causing major problems. It sounds like a major change to me. If people have such strong opinions on this issue, why shouldn't we take a larger sample and come to a real consensus?

**Comment by Dacendeth** [comment]
Next target, Roulette revolver.

**Comment by BomberBro** [comment]
In a case like this where you have a horribly buffed item that, realistically, completely trivializes most gamemodes (malf, cult for both sides, revs if an RD gets it, for example), it either shouldn't be common or be nerfed so that it's not the case. It's a lot easier to just make it harder to get, which is probably the worse of the two options and doesn't completely solve it, but the way to nerf it without completely gutting it would be a hard sell. If this continues to be a problem there should just be a cooldown on making portals OR remove the interaction with mesons.

**Comment by robintime** [comment]
> Why not put it to a vote instead of letting G*thub users decide unilaterally?

the github is linked in the thread and new PRs are posted instantaneously in both discords. literally anyone can register and cast a vote as soon as they're done making their account, so treating the git as a secret club instead of a reflection of the playerbase's opinions is kind of weird

**Comment by TGFH** [comment]
Change that 25 to a 2.5.

**Comment by anunknownentity03** [comment]
> Change that 25 to a 2.5.

this is also a valid chance change

**Comment by Eneocho** [comment]
> 
> 
>There are so many things like hand teleporters and subspace tunnellers that accomplish similar things to the claws and don't even require xenoarch.


The hand teles need beacons and to be synced, making them useful to return to previous locations but not very good as an infiltration tool.
Subspace tunnelers are throttled in that you are either cucked by the crystal shattering, the clunky way to teleport or the fact that you can't teleport to walls, unlike claws which teleport for free, can teleport you directly to a wall and make any attempt at secrecy be useless since the guy can literally teleport right through to anywhere and kill you, just to skidaddle away.

**Comment by APCUnlocked** [comment]
> dumb grudgecoding. There are so many things like hand teleporters and subspace tunnellers that accomplish similar things to the claws and don't even require xenoarch. Also since when does reactionary coding get so many thumbs up?

Neither of those things are nearly as egregious as the warping claws are.

**Comment by anunknownentity03** [comment]
the chicken has spoken

**Pull request merged**
