### PR TITLE
Fixes #7155, water can't put out campfires

### LINKED ISSUE #7155: Campfire can't be put out with water
Splashing water over it does not put it out. Not sure about fire extinguisher.

### PR DESCRIPTION
**Pull request by ghost**
Yes, this was tested and mobs still get extinguished from fire extinguishers

### CODE REVIEW

**Review by PJB3005 — DISMISSED** [review]
Make a proc that gets called on objects when reagents get sprayed on them instead of this hack.

**Comment by 9600bauds** [comment]
What, you mean like reaction_obj()?

**Comment by PJB3005** [comment]
Yes.

**Comment by 9600bauds** [comment]
https://github.com/DrCelt/bugfixandsnowstationrepo/blob/5cf8f7c07e53336773ed3216a527f04e49c8b5c5/code/modules/reagents/Chemistry-Reagents.dm#L82

**Comment by PJB3005** [comment]
I meant that the OBJECT gets a proc called on it with the reagent, then the campfire sees "oh its water, I need to get snuffed"

**Comment by 9600bauds** [comment]
I agree that that would be the best, but man, fuck no I'm not refactoring a huge chunk of chemistry code over campfires under the clause of "No Ririchiyo, I'm Not Rewriting Mechs Just Because I Touched One Line Of Mech Code"

**Comment by PJB3005** [comment]
Too bad you're dealing with me then.

**Comment by 9600bauds** [comment]
you mean we'll see what all the other collabs think about it :^)

**Comment by PJB3005** [comment]
Well cluster for one isn't gonna give a Shit about this PR spam of rushed fixes.

**Comment by ghost** [comment]
Hi I made this PR so that means if bauds merges it it's not self merging™

**Comment by Exxion** [comment]
Fuck off, PJB. It's a bugfix. Don't hold it up over an existing system sucking just because you're pissed Bauds helped Celt.

**Comment by PJB3005** [comment]
I would've made critique like this either way.

Code standards are still above bug fixes, and yes this code would be trivial to add.

**Comment by Exxion** [comment]
Trivial to add in this one case, but not trivial to change everything to

**Comment by PJB3005** [comment]
I never said he had to change everything to it.

**Comment by Exxion** [comment]
Alright, fair enough, I guess

I'll probably do that later anyway

**Pull request merged**
