### PR TITLE
log votes publicly

### PR DESCRIPTION
**Pull request by toomykins**
these 2 lines of code i github edited in should make all votes public in the logs. They were already available in the logs through calculating href options against results, but this makes it more easy. Hopefully this will encourage less shitty voting. Glasnost if you will.

:cl:
 * tweak: votes are now publicly logged.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Not a good idea to log voters for the purpose of log-diving and building a vote profile to shame them for it. If anything the methods of revealing voters in the log files should be patched by obscuring the vote number on the log-writing side, much like IP connections.

**Comment by Inorien** [comment]
>accept that grief voting happens
>this is when people vote for a shit map and then DC and not even play it
>the solution is to make everyone's votes public

I'd rather the relevant map(s) were simply less shit in general, I see this as something that should really be temporary at best

**Comment by jwhitak** [comment]
As an aside: everyone's votes are already public, and are actively scraped/graphed. For problems with maps, use the bug report button in game and give any real suggestions/improvements. Single issues like that are easy to knock out for would-be mappers.

**Comment by djkramer123** [comment]
people deserve to be bullied for their shitty voting choices

**Comment by Pastamadness** [comment]
I don't understand what purpose this serves other than profiling people. Literal grudge PR.
Why not attempt to improve or even remove maps that are being deemed genuinely bad by the current zeitgeist?

**Comment by CrazyAmphibian** [comment]
all this is going to do is lead to metagrudging in-game and in the community. because you're so immature that you can't handle someone voting for a map *you* personally don't like.

**Comment by ErrorsWindows** [comment]
> As an aside: everyone's votes are already public, and are actively scraped/graphed. For problems with maps, use the bug report button in game and give any real suggestions/improvements. Single issues like that are easy to knock out for would-be mappers.

yea but where

**Comment by Eneocho** [comment]
> I don't understand what purpose this serves other than profiling people. Literal grudge PR. Why not attempt to improve or even remove maps that are being deemed genuinely bad by the current zeitgeist?

the metaclub has lobbied the last 5 times someone dared look at snaxi with less than loving eyes

**Comment by jwhitak** [comment]
They're stored in the href log and are slightly difficult to pick out by hand since people can change their votes.

**Comment by Pastamadness** [comment]
February ended and Snaxi is no longer In rotation.
You can close this meme PR now.

**Comment by Kurfursten** [comment]
Coming from someone who overwhelmingly does not vote (verifiable) this is a bad idea because the only purpose it serves is to attack other community members. You do not need to know someone's map vote for a ban request.

**Comment by angryturnip** [comment]
I thought the point was for people to have some level of accountability so they didn't just vote an unpopular map and log off

**Comment by Kurfursten** [comment]
Until you get the headmins to make voting for an unpopular map and not playing it to be a bannable offense, there's no need for this to be logged.

**Pull request closed without merging**
