### PR TITLE
Removes job restriction from pickpocket gloves, Chef's Sauce, and proximity mines. Renames Chef Excellence's Special Sauce to Horatio Sauce

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
we did it patrick, we saved the server, this is not a joke pr you chucklefucks
:cl:
 * tweak: Pickpocket Gloves, Chef Excellence's Special Sauce, and proximity mines are no longer job-restricted.
 * tweak: Renamed Chef Excellence's Special Sauce to Horatio Sauce.

### CODE REVIEW

**Comment by DamianX** [comment]
image
lmao nerd fix your shit

**Comment by boy2mantwicethefam** [comment]
only solution is to nuke the entire fork and start from scratch but as long as there are 3 prs open i cant really do that i believe

**Comment by Arthurdentist** [comment]
Okay, this is epic

**Comment by jknpj** [comment]
>Emojing your own PRs

Why did mommi stop autoclosing

**Comment by boy2mantwicethefam** [comment]
this pr is perfect and people cant argue otherwise so they tryin to nitpick at perfection cuz they hate how good it is unironically but ironically

**Comment by strawberrytan** [comment]
I dislike taking out the name chef excellence

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Agree on the pickpocket gloves, disagree on the chef sauce

**Comment by Lunstra** [comment]
potent horatio sauce
Only if we can get a new sprite for the spider queen that's magical girl kumo too you 4xg loser

**Comment by Durgen** [comment]
\>Horatio Sauce
don't immortalize players in code unless they have truly earned it

**Comment by MadmanMartian** [comment]
>why did mommi stop autoclosing

Become the change you want to see in the world

**Pull request closed without merging**
