### PR TITLE
Rampant Brand Intelligence random event tweaks

### PR DESCRIPTION
**Pull request by DeityLink**
Hopefully that'll alleviate some of my frustrations with this event.

**Why it's good**: It raises the chances of players to even figure out what the event even is about, but I agree it's not good enough yet, the command alert should at least mention something about toggling the infected machine's speaker, and there should be another alert when the event ends.

It's 11 years old Cael code that has virtually never been touched ever since.

:cl:
* tweak: The following changes have been done to the Rampant Brand Intelligence event. The original infected vending machine is now guaranteed to emit one of its custom slogans when it infects another vending machine, making players more likely to find it (and to hear those slogans at all like jesus christ the odds were ridiculously low). When the event ends, ALL infected machines stop throwing items instead of only 90 percent, and their speakers now return to their previous value instead of always being deactivated.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
why its good:

**Comment by DeityLink** [comment]
Why it's good: It raises the chances of players to even figure out what the event is about, but I agree it's not good enough yet, the command alert should at least mention something about toggling the infected machine's speaker, and there should be another alert when the event ends.

It's 11 years old Cael code that has virtually never been touched ever since.

**Comment by wotisjanitor** [comment]
2 votes and up for 2 days why hasnt it been merged

**Comment by DeityLink** [comment]
Because like I said I clarified the command alert, and added another one when the event ends.

For literally over a decade I literally had no idea what the game meant by _"Rampant brand intelligence has been detected aboard [station_name()], please stand-by."_, let alone that I could do something about it, until I finally checked the code.

**Review by west3436 — APPROVED** [review]

**Pull request merged**
