### PR TITLE
Organ item update

### LINKED ISSUE #11000: Feet and hands still pop out when a whole limb is severed.
I actually haven't found an issue about this.
#### Description of issue

If you cut out (or lose) an arm or leg, your correspondent hand or foot flies off like you're made of glass.
#### Difference between expected and actual behavior

For the hand/foot to still remain attached to the limb. 

This issue has been going for so long we're pretty much accustomed to it, but I still think that changing the organ system so that organic limbs don't always split in two when removed would improve reattachment surgery without having to resort to mechanical limbs because they're much faster to use.

It also would make medbay frankenstein slightly more common, if you like that sort of thing.

### LINKED ISSUE #13265: You can surgically remove a limb, and reattach it, and the limb will have no associated damage
#### Description of issue

Because of https://github.com/d3athrow/vgstation13/pull/12803 you can now chop off a limb, say a broken hand with internal bleeding and max damage, and reattach the exact same hand, and it will have none of the associated damage

#### Difference between expected and actual behavior
Expected - The limb object transplanted to have the associated damage it had, such as bad veins, broken bones, burn and brute damage, etc.

Actual - It has no damage whatsoever

#### Steps to reproduce 
Have a guy come in with bad damage to a limb you can remove

Chop it off in some way

Reattach it through surgery

Marvel at the fact it has no damage

#### Specific information for locating

Surgery, limbs, https://github.com/d3athrow/vgstation13/pull/12803

#### Length of time in which bug has been known to occur

18 days as of this bug report

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### LINKED ISSUE #13558: Janitor QoL tweak: Make 'right arm', 'left foot', etc. Small
oh god, these are a pain in the ass to clean up because they're so common, because gibbing is common, but i can't pick them up with a trash bag. the only way to do this is by hoping there's disposals nearby, and walking them over one by one.

this is the worst, and i don't think useless hacked off limbs will become broken somehow by being made small instead of normal.

### LINKED ISSUE #14566: Removing legs and arms should keep feet and hands attached to them
Because right now it makes no sense. WYCI, I suppose.

### PR DESCRIPTION
**Pull request by unid15**
Fixes #13558
Fixes #13265
Fixes #14566
Fixes #11000

changes size of organs, making arms legs and heads small, and hands and feet tiny
Organs keep their wounds on amputation, including bleeding and broken bones
After amputating a limb, the generated organ item will have all child organs attached to it, instead of them tearing themselves off and flying at your face. You can separate the organs (e.g. cut a hand off an arm) with any sharp item

:cl:
 * tweak: Arm, leg and head organ items are now considered small. Hands and feet are tiny and fit in pockets
 * bugfix: Amputated limbs now keep their damage, and no longer heal when attached.
 * tweak: Hands and feet no longer go flying when the organ they're attached to is amputated, now they stay connected to it. Use any sharp item on a separated arm or a leg to cut its hand or foot off

### CODE REVIEW

**Comment by DamianX** [comment]
YES
THANK YOU
also close #14566

**Comment by Blithering** [comment]
Neat, would it be possible to make limbs remember the damage they had on them when they were removed? So people can't just immediately reattach it and magically heal all damage to the limb

**Comment by unid15** [comment]
Sure thing

**Comment by DamianX** [comment]
Is there any indication a severed limb is damaged? If not, some flavor text on examine would be nice.

**Comment by RealestEstate** [comment]
I agree with Damian. maybe some text like "the arm appears to have [some, several] [lacerations/burns/ blue blotches/ green blotches]", "the arm appears to be bleeding profusely", etc. based on the damage

**Pull request merged**
