### PR TITLE
bees no longer attack other bees, or mommis

### PR DESCRIPTION
**Pull request by MadmanMartian**
unless somebody has any better ideas

:cl:
* rscdel: Bees no longer attack other bees or mommis

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by AutismSpider** [comment]
What if the bees merge with the mommi to make a beemo or mobees

**Comment by SonixApache** [comment]
this kills the hive versus hive

What if you just give them all a faction number that defaults to 0 or something, so bees spawned through means that isn't a hive are always allied to eachother? Or, hell, make certain methods of spawning bees give them different factions.

**Comment by Hugh-G-Rection** [comment]
Hive versus hive seems to be an inherently broken feature, because a single hive is meant to spread out into multiple hives. Place a single hive with a single queen, bees will reproduce until enough royal jelly is built up enough to create a new queen, that queen will leave with a swarm of bees to find a new hive. Even though they've all come from the same original hive, they'll still end up fighting because now they're living in different hives, making the seemingly intended expansion either pointless or needlessly difficult to manage.

**Comment by DeityLink** [comment]
I think that high toxicity bees should still attack other bees. You can add a check for it and have bees not attack other bees should their toxicity be bellow the threshold.

**Comment by Shadowmech88** [comment]
>You can add a check for it and have bees not attack other bees should their toxicity be bellow the threshold.

Isn't that exactly what we already had, and wasn't working because bees were still attacking other bees regardless of toxicity?

**Comment by DeityLink** [comment]
Nah, that check was only allowing them to be angry or not.

**Comment by Shadowmech88** [comment]
```
var/list/nearbyMobs = list()
for(var/mob/living/G in view(src,7))
  	if (istype(G,/mob/living/simple_animal/bee) && (((current_poison_damage - bees.len)/bees.len*100) > 51))
  	  	var/mob/living/simple_animal/bee/B = G
  	  	//even then, they won't attack bees from their own hives.
  	  	if (B.home == home || (home && B.home && B.home.wild && home.wild))
 		  	continue
  	if (G.stat != DEAD)
	  	nearbyMobs += G
if (nearbyMobs.len > 0)
	target = pick(nearbyMobs)
  	if (target)
	  	src.visible_message("<span class='warning'>The bees swarm after [target]!</span>")
```
I don't know, to me this looks like "If the mob is a bee and the swarm's toxicity is high enough, and the mob's home is not the same as the swarm's home, attack the mob."

**Comment by PJB3005** [comment]
@DeityLink @Shadowmech88 can I merge this or do you want to fix it properly.

**Comment by DeityLink** [comment]
I don't have much time to do it better right now, and it's not that important of a feature that I'd hold back your PR.

**Comment by Shadowmech88** [comment]
@PJB3005 
I have no issues with the PR.

**Pull request merged**
