### PR TITLE
Fixes picking up and dragging items from z-levels below

### LINKED ISSUE #30899: You can drag things on floors below you [MULTI-Z]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
e69b2cecf42fbc56fa8e0374bbfa7c963745c8de

# Description
By alt clicking, and then dragging the object on the floor below you, you can drag objects around (and even up Z's)

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[bugfix][hotfix]

## What this does
Closes #30899.

## Changelog
:cl:
 * bugfix: Adjacency now only counts being on the same z-level as something, preventing dragging things up Z-levels or picking them up from above.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Are there times we want to be adjacent to things with a z = 0? For example, an object inside your backpack.

**Comment by adacovsk** [comment]
Does this account for dragging things up and down stairs? Also if it hasn'tbeen addresses, pushing things from a lower z level to higher z level up stairs

**Comment by DorainGrey** [comment]
Does this affect dragging bodies up Z-Levels?
That's very important for some away missions.

**Comment by SECBATON-GRIFFON** [comment]
> Are there times we want to be adjacent to things with a z = 0? For example, an object inside your backpack.

suprisingly that doesn't affect that

> Does this account for dragging things up and down stairs? Also if it hasn'tbeen addresses, pushing things from a lower z level to higher z level up stairs

this works too somehow, added a quickfix for adjacency handling with it though

> Does this affect dragging bodies up Z-Levels?
> That's very important for some away missions.

elaborate. like with stairs? i can't think of any away missions you mean

**Comment by DorainGrey** [comment]
>> elaborate. like with stairs? i can't think of any away missions you mean

The new Gray Mothership away mission for example is spread out over 3-4 Z-levels, so you need a way for normal crew to transport bodies & down ladders, back to the portal.

**Comment by Kurfursten** [comment]
Iirc you want to grab the body and use the grab on the ladder. But even if that wasn't the case, those ladders would just check for a drag present at the moment you click the ladder, this wouldn't prevent that.

**Comment by SECBATON-GRIFFON** [comment]
> > > elaborate. like with stairs? i can't think of any away missions you mean
> 
> The new Gray Mothership away mission for example is spread out over 3-4 Z-levels, so you need a way for normal crew to transport bodies & down ladders, back to the portal.

all of them except the starting one is loaded on z2 though....

**Pull request merged**
