### PR TITLE
Snowman Tweak

### PR DESCRIPTION
**Pull request by Kurfursten**
I think we're all sufficiently tired of the 50 snowman armies. Plus building living snow golems with your bare hands is immersion breaking.

I raised it from 30% chance for a single gift to six guaranteed gifts since it's much harder to find a magic hat.

:cl:
* tweak: When you build a snowman, it's just an inanimate structure (clearable with a single shovel). If you can give it a carrot nose and a magical hat, however, it will spring to life and give you gifts (gifts only first time that hat is used).

### CODE REVIEW

**Comment by Blithering** [comment]
Could you have actual magic hats (the kind usually found near the headless wizard corpses littered around the station) not drain when used?

**Comment by Kurfursten** [comment]
I'll work out something like that, sure, need to look into it

**Comment by PrimeDSS13** [comment]
my body feels a violent rejection to this PR
If you make it so it's a normal hat instead of a wizard hat (in addition to the carrot nose) I'm willing to like it because it's actually obtainable while still requiring a bit more effort but what this does currently is basically kill living snowmen forever

**Comment by Kurfursten** [comment]
Why does the pile of snow come to life when you put a normal hat on its head? It doesn't fit the reference and it doesn't make sense. This isn't xenobiology or a space ray or chemistry, it's slapping snow on the ground.

@Blithering I've looked into it and compromised on "it doesn't drain the magic from any hat, but any given hat will only give you gifts 1 time", commit to come later today

**Comment by jknpj** [comment]
I SAY!

**Comment by Kurfursten** [comment]
Not only did I make the changes I said, I added the useful feature that snowmen will try to equip a hat on their tile when the first come to life if they have none. Players can use this with a box of winter that spawns a hatless snowman, admins too. Mostly useful for mappers though.

**Comment by ghost** [comment]
What is the prevalence of magical hats that aren't forcibly liberated from formerly living wizards? Exactly how much harder is this going to make making snowmen?

**Comment by Kurfursten** [comment]
Making snowmen will remain easy
Making living snowmen will be rather hard the first time. 5% of tophats are magic, sith cowls, plus any obviously magic hat (e.g.: the gemsuit helmet, pharaoh mask that traders can sell you, celtic crown from vault, the elfhat that can spawn in the wizard wardrobe, etc). On the plus side, you can retrieve the hat and keep making them as much as you want if it dies.

The easiest wizardly hat to get is a butt, followed by the inquisitor wide-brim hat from the pietyvend.

**Comment by juanototo2** [comment]
Make two snowman types. One inanimate, one animate. Animate requires relatively easy to obtain paranormal resources. Inanimate works like this PR.

**Comment by Kurfursten** [comment]
That's what this PR does, did no one read it?

**Comment by juanototo2** [comment]
The difference is that the animate by default one would need something like holy water or blood candles and be far, far weaker, while inanimate by default are stronger.

**Comment by juanototo2** [comment]
But... Ah, fine, whatever, who cares. Upboating now.

**Pull request merged**
