### PR TITLE
Fixes clean_map_git trying to do vgstation.dmm

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by ghost** [comment]
Shouldn't it build Busstation instead of Taxi ? Or did we use the same namespace for the new map ?

**Comment by PJB3005** [comment]
Bus is in it though...

**Comment by ghost** [comment]
Then remove Taxi

**Comment by PJB3005** [comment]
No.

**Comment by ComicIronic** [comment]
Why? Someone might edit it in the future.

**Comment by PJB3005** [comment]
Because the file isn't in the maps folder anymore. I could make it just not so the map if the file doesn't exist I guess.

**Pull request merged**
