### PR TITLE
Makes pulse demons not affected by bee stings or thrown pies

### LINKED ISSUE #31684: Pulse Demon dies to Hornets.
#### Description of issues
~~While being a Pulse Demon, I lost and regained the ability to see wires seemingly at semi-random. I seemed to lose wire sight after entering an APC, then somehow got back later, then lost the ability to see them again. Power wasn't being supplied to the net (I think), so that may be related.~~
I also noticed that going through wires by hornets caused a 'Hornets stung the pulse demon', as well as getting the red edge around my screen, even though my health was stated to be 100%. I then entered the room FULL of hornets, and died instantly, unsurprisingly.

#### Difference between expected and actual behavior
~~Being able to always see wires so I can pathfind properly, and not being able to.~~
Being immune to hornets, as "Don't let your charge run out! If the powernet blacks out you'll start losing health and eventually die off! You are immune to all forms of damage and obstacles in the way of cables, but are also extremely weak to EMPs, so avoid those at all costs." Then I died to hornets. 

#### Steps to reproduce
~~Try going in and out of APCs, and seeing if you lose wire sight?~~
Go into room with hornets and get destroyed.

#### Length of time in which bug has been known to occur
First time being pulse demon, so I don't know

#### Server revision
Game: 348f29631d6ca0f258fdd67a9b4142589cfcc449 
Patches: d2d8284cefe331992a20db0f4fedb3e1b63c7713

### LINKED ISSUE #32032: Pies Blind Pulse Demons
(WEB REPORT BY: kneegear REMOTE: 206.221.180.138:7777)
# Revision
fdfb1508429b2447967053fe8d40b75e05cb6a47

# Description

Being hit by a pie from a vending machine blinds pulse demons.

# Steps to Reproduce
Hack a vending machine to fire out contents, get hit by one as pulse demon

# What you Expected
Nothing to happen or for temporary blindness

# What Actually Happened
Blinded permanently

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[bugfix]

## What this does
Closes #31684.
Closes #32032.
Re-defines the astral projection's tangibility verb down to living mobs for this to also stop it affecting them when intangible, possible bones of a system with that variable for future usage.

## Changelog
:cl:
 * bugfix: Pulse demons can no longer be hit by pies.
 * bugfix: Pulse demons are no longer stung by bees.
 * tweak: A message now indicates thrown items go through pulse demons instead of hitting them.

### CODE REVIEW

**Comment by jwhitak** [comment]
You're removing the clown's soul...

**Comment by SECBATON-GRIFFON** [comment]
> You're removing the clown's soul...

it permanently blinds them, as the issue says

**Comment by jwhitak** [comment]
Rip, didn't see that. I'd still like to keep pies on the pulse demons if only for funny though. But between that and permanent blindness the priority is clear.

**Comment by Kurfursten** [comment]
Confl

**Comment by SECBATON-GRIFFON** [comment]
> Confl

fixed em now

**Pull request merged**
