### PR TITLE
Adds more AI names.

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by ghost** [comment]
dumb frogs

**Comment by Kammerjunk** [comment]
what the fuck am I looking at
image

**Comment by PJB3005** [comment]
I'd rather not talk about it.

**Comment by DrSnips** [comment]
Basically an evil AI has robot monsters that fuck up THE INTERWEBZ and bad shit that happens on the interwebz is reflected in real life. A group of kids animated in an indian sweatshop have magic internet tubes that send them into the interwebz along with an 8 year old HACKERMAN which gives them super power so they can nothing personal the monster bots.

**Comment by Exxion** [comment]
Alright I remember XANA but what is VIKI?

**Comment by IzayaChan** [comment]
Code Lyoko is pure kino and only chad remembers. Speed merge this and make PJB godheadmin of pomgkind

**Comment by ShiftyRail** [comment]
Code Lyoko ? Count on me to speedmerge it

**Pull request merged**
