### PR TITLE
 General Security-related mapping improvements.

### PR DESCRIPTION
**Pull request by ShiftyRail**
## All maps
- Head of Security locker starts with an alternative armour skin (previously, this was hard-mapped on Deff only)
- Head of Security & Warden lockers start with more equipment (a flashbang, a taser, a pepperspray, security tape, and a hailer - basically everything normal security got but the big boys didn't)

## Defficiency
- Arrivals checkpoint : 
deff arrivals
Added a security locker, a windoor, put the items lying on the ground on the table. (I was always under the impression the checkpoint had been vandalised since there never was a locker + the flash was on the ground)

- Medbay checkpoint : 
deff checkpoint
Added a door from lobby, put a security cameras computer, put a radio that was on the ground on the table.

- Perma ;
permeme
Layered plasma windows + grilles **on top** of the existing rwalls, making the escape attempts a bit more time-consuming as well as making more noise.

- Misc : 
The internal morgue door (medbay => morgue) can be opened with security access like in Box and Bagel.
Added a second sec vend to brig.

## Packed
- Interrogation room : 
brig packed
Cleared up a bit of space by replacing windows with smartglass (courtesy of @SonixApache), currently trying to make it so they are toggelable by a hard-mapped button, but my unga bunga brian doesn't manage to do it. Help wanted
Also, fixed a few glass windoors when the rest was already plasma windows, and nudged the cuffs box away from the holobadge one.

- Misc : 
The internal morgue door (medbay => morgue) can be opened with security access like in Box and Bagel.

## Meta

- Misc : 
The internal morgue door (medbay => morgue) can be opened with security access like in Box and Bagel.

:cl:
- rscadd: Meta: Security has access to the internal morgue airlock, like in Box and Bagel.
- rscadd: Packed: Security has access to the internal morgue airlock, like in Box and Bagel.
- rscadd: Packed: Interrogation room designed to allow more space to manoeuvre prisoners, and privacy in the form of Smartglasses that can be toggled on or off.
- rscadd: Deff: Security checkpoint in medbay can be accessed via medical lobby, and now has a security cameras computer.
- rscadd: Deff: Perma is more secured, with a layer of grille + plasma window on top of the renforced wall outside. This means you can no longer sneak in with a false wall unnoticed.
- rscadd: Deff: Added a security locker to the arrivals checkpoint.
- rscadd: Deff: Added a second sec vend.
- rscadd: Deff: Security has access to the internal morgue airlock, like in Box and Bagel.
- rscadd: Warden and HoS lockers will now start with gear that was otherwise missing in them but found in security officer lockers, such as a hailer.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Oh come on
I'm retarded : `step_x => pixel_x`
Et ceatera

**Comment by MusgardTiger** [comment]
good changes 👏 

also finally somebody is adding a door to medbay checkpoint from lobby, now I don't need to beg to whomever is mixing up his cryo autism beaker to open the door

**Comment by DamianX** [comment]
\>Security has to the internal morgue airlock

**Comment by ShiftyRail** [comment]
@DamianX Good catch
I'm terrible at English

**Pull request merged**
