### PR TITLE
remove attack delay affecting picking up and storing/retrieving items

### PR DESCRIPTION
**Pull request by nervere**
## What this does
All attacks function on a 1 second cooldown. Due to the way the code works, clicking on just about anything with an item, including your inventory, counts as an attack. Picking stuff up also counts as an attack. I find this to be nonsensical, and it makes the game feel laggy/unresponsive when it is, in fact, not.

This PR makes high-octane combat feel better. It does this by no longer allowing picking up items, storing items, and retrieving items from inventories to be affected by an attack delay. So, if you'd like to, say, have an item interact with another item in the world, and then immediately store that item, you can now do so almost immediately. Everything is still affected by the global click cooldown (0.1s), but that's 10x faster than how things are currently.

It should be said that not everything triggers this attack cooldown, but if you're a high APM kind of gamer, you'll definitely notice these changes across many aspects of the game.

## Why it's good
- Game feels more responsive during those high-intensity situations.
- Active attack delays affecting picking up/storing items is not intuitive.

I think I made this code foolproof so it won't affect anything unintentional, but I'd appreciate a fresh pair of eyes checking my work. I've tested this myself and didn't find anything weird happening, but the effects are wide-ranging so I probably missed something.

[tweak][qol][experimental]
## Changelog

:cl:
 * experiment: Active attack delays will no longer prevent you from storing/retrieving items from inventories, or picking up new items.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Does this allow someone to pull out a gun in an instant and fire it at someone?

**Comment by nervere** [comment]
> Does this allow someone to pull out a gun in an instant and fire it at someone?

Yes, there is no delay on that. Not exactly an intended consequence, but...
If the general consensus is that this is lame, I can make it so that retrieving items from backpacks still triggers a cooldown.
I can see people going the other way, though, and thinking this adds to the paranoia aspect of the game.

Either way, I'll respect the community's opinion and make any changes if needed.

**Comment by GreatBigFailure** [comment]
> > Does this allow someone to pull out a gun in an instant and fire it at someone?
> 
> Yes, there is no delay on that. Not exactly an intended consequence, but... If the general consensus is that this is lame, I can make it so that retrieving items from backpacks still triggers a cooldown. I can see people going the other way, though, and thinking this adds to the paranoia aspect of the game.
> 
> Either way, I'll respect the community's opinion and make any changes if needed.

I think the best implementation would be to add a specific flag/check for it so it only effects certain items, and can be tinkered with on a case by case basis. A "quickdraw" gene that lets you bypass it for guns, or having ninja's katana do more damage if they un-sheath it and attack during the normal delay period.

**Comment by Kurfursten** [comment]
Think this is fine for experimenting in its current form

**Pull request merged**
