### PR TITLE
Don't log throw_impacts of mindless or dead mobs

### LINKED ISSUE #9616: Hide attack log for simple animals without minds being hit by thrown items from admin chat output
You can keep the part where it logs to mob attack logs, just keep it out of my chat window geez
This way dead mice being hit by garbage in the disposals chutes won't clutter my chat.

### PR DESCRIPTION
**Pull request by unid15**
Fixes #9616

### CODE REVIEW

**Comment by Probe1** [comment]
>gripe in modchat about getting 30+ adminlogs when disposals activates and dumps all the garbage, including a dead simple mob 
 >someone fixes it within 12 hours
N I C E

**Comment by gbasood** [comment]
Only problem with this is that attack logs won't be updated if a simple animal has no ckey, and that's still useful because we want to know who killed Ian.

Actually wouldn't you want to change living_defense line 135, not this?

**Comment by unid15** [comment]
Good catch @gbasood. Fixed

**Comment by gbasood** [comment]
Wellllllll
Minor thing: minds stay even if the person who owns the mob is ghosted
It's kinda useful, compared to checking ckey

**Pull request merged**
