### PR TITLE
Adding shutters and a flasher to Boxstation's HoP line.

### LINKED ISSUE #12646: Shutters on the HoP office windows on box. Good idea? Bad idea?
The box station HoP office windows have no shutters to close in emergencies, unlike the other parts of the bridge. It might be handy to add some, as I have found the ones on meta really useful for hiding behind.
Then again, it might be a bit too secure if they were put in place. Who knows?

### PR DESCRIPTION
**Pull request by SysadminJeroen**
Always got annoyed by greytides breaking down the HoP windows. I mean I can deal with them hacking the HoP's door but if they just go and be assholes and break windows while in the line.

This map change should deter them from being cunts, and also provides a bit more safety for the HoP.

Pic

[Outdated Pic](https://i.imgur.com/JrLSXSQ.png)

[Outdated Gif #1](https://i.imgur.com/ukPfwrD.gifv)

[Outdated Gif #2](https://i.imgur.com/8XeOpT9.gifv)

_[Outdated outdated Vidya](https://a.pomf.cat/amzoju.mp4)_

Closes #12646.

:cl:
 * rscadd: Added shutters and a flasher to Boxstation's HoP line.

### CODE REVIEW

**Comment by JustSumBody** [comment]
~~Can that be reached from the other side by chance?~~
Whoops I'm retarded and didn't see the full vidya

**Comment by SysadminJeroen** [comment]
@JustSumBody It can not, you can see in the webm that I approach the button from the line, but what you can not see is that I was frantically clicking the buttons.

The buttons are mapped on the Security computer, their offset makes it appear as if it is on the wall.

However, I will check more circumstances like standing on the table and fix the permissions, it is currently set that everyone who has access to the bridge can operate the buttons.

**Comment by 9600bauds** [comment]
Heck, not even Brig gets front door flashers.

**Comment by SysadminJeroen** [comment]
@9600bauds That can be fixed, all you have to do is give this comment a :+1:.

**Comment by Probe1** [comment]
The trap is a bit too much. Just on the HoP side. As well, I thought we were talking about shutters not blast doors.

**Comment by SysadminJeroen** [comment]
@Probe1 Aren't they running on the same code, but just a different skin and opening/closing animation?
I can change the blast doors to shutters instead if that is desired.

**Comment by Probe1** [comment]
Good grief it is the same code copied and pasted into two different files.  Did they not have subtypes in 2013?  Fucking CAAAAAAAAAAAAAARRRRRRRRRRN.

Yeah it's just a stylistic choice.  I prefer shutters but it's really a visual issue and I'm not going to say redo it.

**Comment by Intigracy** [comment]
Being able to be trapped so easily isn't fun though.

You should remove the four on the outer windows and leave the pathways blocked off, so people trapped in can still get out without needing to remove a wall.

**Comment by Blithering** [comment]
I Would personally change the outer shutters to the drop-down kind, and have them only on the entrance/exits, so a sufficiently desperate greytide can smash their way out of the queue before sec arrive.

**Comment by SysadminJeroen** [comment]
So the general consensus is to remove the blast doors on the outer windows, and change the outer blast doors to shutters.

I'll get to it.

**Comment by Probe1** [comment]
I'm still not a fan of the outer shutters at all and don't think that's what you set out to do.  You need to map  with everyone in mind.  This very strongly favors command.

**Comment by SysadminJeroen** [comment]
@Probe1 I understand that, it is why I am replacing the outer blast doors with shutters and removing the outer blast doors on the windows.

That way that if the shutters are down and the HoP is flashing people in line, someone on the outside can still break the glass and drag the person out.

It will be a deterrent for those who are in the line not to try to break the glass.

**Comment by SysadminJeroen** [comment]
After being a stupid fucktard for the last hour, I have decided that I am lacking too much sleep and that I'll take a quick nap.

I will continue this tomorrow.

**Comment by SysadminJeroen** [comment]
Updated the original post.

**Comment by Probe1** [comment]
Weird I definitely didn't touch the HoP office and I'm pretty sure my PR was the only one merged.  I thought this stuff auto-merged if we didn't meddle with the same tile.

Anyway I still feel the flasher and the trappy outer shutters are too much.  One or the other.  Both are pretty strong on their own.

**Comment by SysadminJeroen** [comment]
You touched the QM's office, I think that is sufficiently nearby.

**Comment by Probe1** [comment]
That is gay.

**Comment by Sprok0** [comment]
I'm pretty sure it isn't actually the same tile, it's the same row of tiles.

**Comment by Shadowmech88** [comment]
Up/down row or left/right row?

**Comment by Exxion** [comment]
Row, not column
So left-right

tgm when

(I know the answer is when it doesn't occasionally crash BYOND)

**Comment by PJB3005** [comment]
A row is always horizontally. A column is vertically.

And yes, @Sprok0 is correct.

Relying on git to automatically merge maps is  a mistake. You installed the merge driver right?

**Comment by Exxion** [comment]
Git is supposed to automatically use the merge driver anyway

**Comment by ComicIronic** [comment]
>tgm when

When it doesn't fail on maps greater than 255 because there's 100000 line breaks in a 1mb+ file that Byond shits itself on.

**Comment by Intigracy** [comment]
I don't remember hitting merge on this, what.

**Comment by Intigracy** [comment]
There's not even a revert button, something about me merging the other PR merged this one at the same time.

**Comment by Exxion** [comment]
Uh
What the fuck?

Check that commit. It's not this.

**Comment by Intigracy** [comment]
@Jeroen52 You messed something up somewhere, the things that magically merged themselves in this PR don't include your mapping change at all.

**Comment by Intigracy** [comment]
From the look of it I'd guess a rebasing problem.

**Comment by Exxion** [comment]
I'd guess more along the lines of the DMCA fucking with Git

**Comment by SysadminJeroen** [comment]
WTF

**Comment by SysadminJeroen** [comment]
But yeah, I was busy with rebasing.

**Comment by Exxion** [comment]
Ah
You don't need to push your changes until after you're done rebasing, you know

**Comment by SysadminJeroen** [comment]
Quick vote.
Shutters start pre-opened, vote :+1:
Shutters start closed, vote :-1:

**Comment by SysadminJeroen** [comment]
It'll be line shutters on the hallway side and blast doors between the HoP's office and the HoP's line.

**Comment by SysadminJeroen** [comment]
After thinking about it a bit, I came to realize how stupid it'd be to start it closed with the way I'm going to map it.

**Comment by Probe1** [comment]
I think we're already going too far with the whole dungeonmaster setup.  Having the HoP office shuttered at roundstarts pretty big diff.  Focus on how it will effect everyone not just command/sec.

**Comment by SysadminJeroen** [comment]
@Probe1 Having it shuttered at round start is only two extra rwindows to break through.

However I was already going with opened at start, so players can already queue up.


Besides, if you know the test wire breaking in the HoP's is very easy and way faster already.

**Comment by Probe1** [comment]
If you're robust yes.  If you're not McBannedsoon Esquire whos played 50 rounds this week doors in main hallways are intimidating and take ages to get through.

**Comment by SysadminJeroen** [comment]
New screenshot: bwtsgduwgqye_dreamseeker_2016-12-21_23-35-38

**Pull request merged**
