### PR TITLE
This twisted game needs to be reset

### PR DESCRIPTION
**Pull request by MadmanMartian**
:cl:
 * rscdel: The ability to dab has been removed

### CODE REVIEW

**Comment by Kammerjunk** [comment]
based and yeetpilled

**Comment by DrSnips** [comment]
How many times do we need to teach you a lesson old man?

**Comment by aceedex** [comment]
What have [feature loss]es ever given us?

**Comment by boy2mantwicethefam** [comment]
Time to metagrudge (you) and people who upvoted this change for being threats to the server culture

**Comment by bathosbathtime** [comment]
Finally, a *dab PR made by r0b0 that will not be merged by r0b0

**Comment by Kammerjunk** [comment]
tbf what would you know about server culture

**Comment by boy2mantwicethefam** [comment]
On the plus side I can complain about ssethtiders

**Comment by boy2mantwicethefam** [comment]
me irl

**Comment by DrSnips** [comment]
I'm legally obligated to downvote this PR. I'm also obligated to create something even worse to replace such a loss in """"culture""" if this happens.

**Comment by robosperg** [comment]
>kills a feature bit by bit until he can outright remove it

peak ivory tower

**Comment by Coxswain-Navigator** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO *sniff* *sniff* NOOOOOOOOOOOOOOOOOOOOOOOOOOOOO DON'T TAKE AWAY MY DAB NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO How else will i convince new players to kill themselves by *dab ing and have a stylish way to commit suicide without any tools or weapons?

**Comment by AI-Is-Rogue** [comment]
dabbers dabbed on 
*dab

**Comment by SonixApache** [comment]
itstime

**Comment by DeityLink** [comment]
And as we always say here on 4chan: "nothing of value was lost"

**Comment by ShiftyRail** [comment]
This actually just remove the ability to suicide by dabbing
`me "dabs."` is still a thing

**Comment by cowboybuttsdrivemenuts** [comment]
yes, and the ability to suicide by dabbing is hilarious

**Comment by Tokanova** [comment]
Care to explain why?

**Comment by utilitas-** [comment]
Now make it so me "dabs." autopermabans and we will be golden.

**Comment by Lokiamis** [comment]
It's dumb and not funny

**Comment by ghost** [comment]
If you remove dab suicide i will start dab bombing with macros instead.

**Comment by ArchSunder** [comment]
unbased

**Comment by AI-Is-Rogue** [comment]
I'd rather it not exist at all because it doesn't add anything except memes for the sake of memes, but if it's going to stay can it at least be moved into the suicide verb somehow so we don't have two commands that exist to commit suicide?

**Comment by Irradiation** [comment]
*Dab

**Comment by ghost** [comment]
This should require a server vote

**Comment by utilitas-** [comment]
fuck no, this requires a speed merge
democracy is a mistake

**Comment by Boxe** [comment]
fund it

**Comment by ArchSunder** [comment]
These boomers must be squashed
The future is now old man

**Comment by DeityLink** [comment]
That pic and post were never funny

**Comment by jknpj** [comment]
*dab

**Comment by ArchSunder** [comment]
um sweaty there's more downvotes than upvotes? wot the fuk r u doing?

**Comment by DrSnips** [comment]
By removing dab you have broken the seal and doomed everyone. Time to make something even worse than this.

**Comment by SonixApache** [comment]
m-muh emojicracy

**Comment by Kharkov72** [comment]
sneaky, oh so sneaky~

**Comment by bathosbathtime** [comment]
The branch name is underappreciated.

**Comment by ShiftyRail** [comment]
Stunning and brave

**Pull request merged**
