### PR TITLE
Box: Adds public autolathe to Auxiliary Tool Storage.

### PR DESCRIPTION
**Pull request by bthomas2**
:cl:
 * rscadd: Box: Added public autolathe to Aux. Tool Storage.

autolathe

### CODE REVIEW

**Comment by Irradiation** [comment]
zoom zoom

**Comment by Accipitermaris** [comment]
Is it really powercreep if it used to be a thing on ancient ass box station? These questions and more, will be resolved by our top philosophists. 

autolathe

**Comment by Intigracy** [comment]
Yes, because it was a big deal when it was removed from ancient ass box station.

**Comment by ghost** [comment]
if your're putting a public autolathe make it so only seasoned assistants can get it. Lock it behind a bolted vault door. Slap on some clown goblins and taser turrets in the room

**Comment by brndd** [comment]
\*cargo desk bell\* (x12)

Assistant McGreyshirt hits the reinforced window with the toolbox! (x3)

Assistant McGreyshirt hits the grille with the toolbox! (x3)

Assistant McGreyshirt hits the reinforced window with the toolbox! (x3)

The autolathe beeps: successfully completed the welding helmet.

[airlock sound]

Jack Slackjaw (Quartermaster): yo what the fuck

**Comment by Lokiamis** [comment]
Just make one

**Comment by bthomas2** [comment]
> 
> 
> Just make one

I did, in the mapper

**Comment by juanototo2** [comment]
I've been waiting a VERY LONG FUCKING TIME FOR THIS

**Comment by Intigracy** [comment]
You know what.

Make it an empty machine assembly, and throw an autolathe electronics in the same room.

That way they at least have to put in a modicum of effort to use their public lathe.

**Comment by bthomas2** [comment]
when you refer to "they" are you referring to assistants?

**Comment by bthomas2** [comment]
no

**Comment by Intigracy** [comment]
hey you answered your own PR 😂

**Comment by tuypo1** [comment]
>if your're putting a public autolathe make it so only seasoned assistants can get it. Lock it behind a bolted vault door. Slap on some clown goblins and taser turrets in the room

encouraging more assistant robustness seems like a bad idea

**Pull request closed without merging**
