### PR TITLE
Revsquad changes

### LINKED ISSUE #11614: Revsquad scoreboard shows scoreboard from normal rev AND scoreboard from revsquad
will fix later

### PR DESCRIPTION
**Pull request by gbasood**
The armor vest was almost always thrown away, so I've replaced it with a traitor freeform AI module.
Also the sawnoff shotgun spawned in with beanbags because I'm dumb, so now it uses buckshot.
This should be left open for awhile for suggestions.
Should fix #11614, if for some reason this PR doesn't go through I'll move it to a new PR. Don't want to hold bugfixes hostage.
🆑 
 * tweak: Revsquad's sawnoff shotgun now starts with buckshot instead of beanbag ammo. Whoops.
 * rscadd: Revsquad members will no longer get duplicate items.
 * rscadd: Revsquad IED replaced with plastique.
 * rscadd: Revsquad's random chance for an armor vest is now replaced with a random chance for syndi freeform AI module.
 * rscadd: Revsquad members get a link to the wiki article for the mode now.
 * tweak: Revsquad will no longer prevent shuttle calls.

### CODE REVIEW

**Comment by Blithering** [comment]
Maybe if you wanted to give them a useful set of armour, give them the syndicate space suit bundle.

**Comment by ComicIronic** [comment]
I feel like the power step up from armor to AI subversion is massive and difficult to predict.

**Comment by aceedex** [comment]
It's not like AI subversion is particularly difficult. This just cuts short the process of "law 2 open that windoor"

**Comment by gbasood** [comment]
@ComicIronic I'd like to see it play out over time, honestly. The armor was going to be removed anyways since it was never utilized in a round.
Also revsquad gets lots of complaints about being underprivileged, which is part of the point, but maybe they're too underpowered right now. A buff like this combined with actual round playthroughs will give me a better idea.

**Comment by gbasood** [comment]
@Blithering The idea is to keep them sort of "low-tech", and I'm not sure that would fit.

##### I realize a hacked AI upload module isn't low tech.

**Comment by Blithering** [comment]
Could be a modified ghetto hardsuit then? While an armour vest isn't terribly useful, a space suit opens up a lot of opportunity.

**Comment by jakmak** [comment]
Allow the shuttle to be called during revsquad
And give the revsquadders their own radio key that only they can use

**Comment by gbasood** [comment]
@jakmak Nah they're not getting their own radio channel
Communication is part of the challenge
If you really want private comms, you can manage it through means already in game.
The problem with shuttle call enabling is
>HELP THEY'RE KILLING US
>CALL IT
>ROUND OVER
Revsquad isn't nukeops, they aren't organized and well-equipped enough to deal with a shuttle call.
@Blithering ehhhhhhh
They don't really need to go fuck off into space
The other problem is that equipping them with any sort of suit on roundstart is hard since they dont fit in backpacks and are conspicuous as fuck

**Comment by gbasood** [comment]
IED is now a plastique explosive and revsquaddies won't get duplicate items, OP updated.

**Comment by Allspice** [comment]
Shuttle can be called during cult, traitor, ling, wiz, et cetera.

More saliently, it CAN NOT be called during: Malf; Blob; Rev. Blob's the only one that actually has a justification for it, since Cent wants shit locked down. The other two are more tenuous, but: Malf has an endgame that (USUALLY) comes about soonish; and rev is just a massive clusterfuck so it'll (USUALLY) end in 10 minutes or less. Rev squaddies are bitches 50%+ of the time so the shuttle ain't fucking coming, doubly so since nobody is going to know it's a squad even if they catch one of the people being meanieheads.

**Comment by Intigracy** [comment]
Since the silencer was removed, you could make a subtype of the gun(s?) with a % chance to spawn silenced instead.

**Comment by gbasood** [comment]
@Allspice I think you underestimate how readily people will hit the shuttle button
If a bomb goes off someone will think to call the shuttle _immediately_. Thankfully most of the ones who think that way don't play headroles but still.

I might code a timed fake recall thing for revsquad? But that seems like it'd get metagamey
I don't want to lock people into a round of nonactivity, I get that argument, I'm just not sure that allowing shuttle recalls will help

**Comment by gbasood** [comment]
Fuck it we'll try it and see if it has real downsides

**Comment by Allspice** [comment]
Why would they be slamming that fricking shuttle button if they do not even know it's revsquad? Seems like a good 2/3 of the time at least if not more that the round end comes out of the blue to all living players.

**Comment by gbasood** [comment]
we're trying it already
why argue the point

**Comment by icantthinkofanameritenow** [comment]
All of this is good, but I still can't see the AI module being used simply because anyone without access in the AI upload is guaranteed to set off alarm bells and that most AI players tend to announce the presence of anyone in their upload (and very few people are smart enough to tell them to shut up in advance). What they need is more along the lines of an ebow or an agent ID.  Better yet, let them spawn with an uplink with a more limited selection and fewer crystals instead of giving everyone random items to start with. There's a big difference between being underprivileged and being little more than a bad joke at the expense of the round. 

And that's not even taking the possibility of a revsquad game starting without any silicons at all. Personally, I'd prefer it if the mode only triggered during lowpop because otherwise it's borderline impossible for the revs to win and it turns into extended.

**Comment by gbasood** [comment]
@icantthinkofanameritenow wizard turns into extended when wiz dies
if you think it shouldn't and that revsquad shouldn't that's another problem entirely

**Comment by icantthinkofanameritenow** [comment]
@gbasood 
The difference is that the wizard usually ends up doing something before he dies, though. 

The point is, the revs are so underprivileged in most games that it takes a miracle for them to be successful. With neither the advantage of numbers or gear, it's pretty much hopeless for them, at least in my experience playing both as part of revsquad and as a bystander in it. The "dumbed down uplink" option really is the way to go, especially since you could otherwise end up with insulated gloves in a job which already has access to them, or a gun you might have no way of getting more ammo for if you run out.

**Comment by Allspice** [comment]
please remove autorecall

**Comment by gbasood** [comment]
@Allspice it is removed

**Pull request merged**
