### PR TITLE
New item icons for captain's antique laser

### PR DESCRIPTION
**Pull request by nervere**
Cool new HD item icon for the captain's antique laser. Held appearance of the gun remains unchanged.
All credit for the spritework goes to @Blithering
Sprites:
caplaser1
caplaser2
caplaser3
caplaser4
caplaser5

## Changelog

:cl:
 * imageadd: New HD item icons for the captain's antique laser added, all spritework done by Blithering.

### CODE REVIEW

**Comment by Exxion** [comment]
The old one has a couple issues, but I personally like it better.

**Comment by SonixApache** [comment]
too dark

**Comment by githubuser4141** [comment]
Could it be made a alt click reskin option like the Detective's revolver?

**Comment by Blithering** [comment]
image0
Since this looks to be contentious, what would need to be tweaked/preserved from the old version to appease the soul cabal?

**Comment by Hinaichigo** [comment]
The fact that it's an antique laser makes respriting it seem especially wrong.

**Comment by ErrorsWindows** [comment]
oh that's the comparison? bro asked the barber to just a bit off the top, finna switch thumbs now

**Comment by nervere** [comment]
> image0 Since this looks to be contentious, what would need to be tweaked/preserved from the old version to appease the soul cabal?

I think the biggest improvement that could be made here is increasing the size of the red laser charge indicator.
It's an iconic part of the gun and you kinda gotta squint to really see it with the re-design.

**Comment by SonixApache** [comment]
> image0 Since this looks to be contentious, what would need to be tweaked/preserved from the old version to appease the soul cabal?

new shading is too dark, looks off

Addendum: today i learned this is supposed to be the Apollo H-4 from system shock 2

**Comment by Blithering** [comment]
I think at this point making it closer to the system shock pistol would detract from it, it's got its own identity over the years.

**Comment by Exxion** [comment]
Which begs the question: Why change it?

**Comment by Hinaichigo** [comment]
Somehow it being an antique makes it seem more wrong to change it, maybe even especially in a somewhat subtle way like this.

**Comment by Blithering** [comment]
> Which begs the question: Why change it?

Mostly because the current one has like 120 colours and the handle/trigger area bugs me.
Performed an emergency sovl transplant taking the suggestions into account, lost some of the sleekness I was going for, but is now almost a match to the original. Better? Or worse?
image

**Comment by Exxion** [comment]
> Mostly because the current one has like 120 colours

Why is this a problem?

> and the handle/trigger area bugs me.

You're right, I hadn't noticed before, but the trigger is dogshit

**Comment by Blithering** [comment]
> > Mostly because the current one has like 120 colours
> 
> Why is this a problem?
1. More colours means more memory, can cram more icons into the dmi if they're smaller 
2. Less near identical colours is more coherent, makes for better palettes when making similar shit later on
3. I have sprite-based autism otherwise I wouldn't be making these changes

**Comment by Exxion** [comment]
> More colours means more memory, can cram more icons into the dmi if they're smaller

It's a PNG. More colors does not mean more size. Technically, a noisier icon means less effective compression, but it's absolutely completely insignificant.

EDIT: You're also leaving the original sprite in anyway, so it's necessarily larger *after* this PR

EDIT: I stand corrected on the first bit. Some PNG encodings do use a pallette, and thus colors do take up space in those encodings. It's still an irrelevant amount of space, though. Also, those encodings only work if the entire file has no more than 256 colors, which is implausible here

**Comment by nervere** [comment]
> EDIT: You're also leaving the original sprite in anyway, so it's necessarily larger after this PR

@Exxion This was a choice I made, I can delete it though.
@Blithering Send me the sprites either here or on Discord so I can update this PR to your new revision.

**Comment by Exxion** [comment]
> This was a choice I made, I can delete it though.

A few sprites makes no meaningful difference. My point was just that this doesn't reduce the size of the file.

**Comment by Blithering** [comment]
I'm still in two minds about it, might be better to make some way for the captain to choose between all in old and all in new that can be selected as was suggested, so everyone can be happy rather than a compromise that leaves everyone questioning why bother in the first place. Maybe through right click menu or captain stamp gun painting?

**Comment by nervere** [comment]
@Blithering How about alt-clicking the gun to swap between the skins? (one use only)

**Comment by Blithering** [comment]
> @Blithering How about alt-clicking the gun to swap between the skins? (one use only)

If that's possible, I'd say that might be the best option. It would also open the door to more choices in the future.

**Comment by SonixApache** [comment]
i think captain-stamping it is the smart option here, also easy to do (see shotgun clownification for details)

**Comment by nervere** [comment]
der iconconflicten... i will fix this soon (tm)

**Comment by Kurfursten** [comment]
Given split community opinion I am deferring to Exxion's judgment. Frankly I don't care either way but I agree the current one is more readable.

**Comment by Blithering** [comment]
The people have spoken. And the answer was a confused shrug.

**Pull request closed without merging**
