### PR TITLE
line bar can view space

### PR DESCRIPTION
**Pull request by adacovsk**
## What this does
image

## Why it's good
- you ask, you receive

## Changelog

:cl:
 * tweak: frankenline bar has a view again

### CODE REVIEW

**Comment by wotisjanitor** [comment]
Another attempt to readd line, i see

**Comment by angryturnip** [comment]
Let the bar patrons have a worse view for choosing to go to line

**Comment by Eneocho** [comment]
> Another attempt to readd line, i see

This is just a mapping change, the PR to readd line is further down.

>Let the bar patrons have a worse view for choosing to go to line

You could claim that letting the bar patrons have a high risk of death from a based retard or spacecarp breaking a window would fit with the troubled history of the map.

**Comment by angryturnip** [comment]
No, I want them to fluoride stare at a wall for picking line

**Comment by WindowsErrors** [comment]
what happened to pedr

https://github.com/vgstation-coders/vgstation13/pull/33430

the skin walkers got to pedr69

**Comment by Eneocho** [comment]
We really should jump ship to another git client. First the server gets flagged, then kanef's shit becomes inaccessible due to flagged serv+ghost account fuckery, now pedr gets fucking skinwalkered. It is only time before more fucked up shit happens and we lose everything.

**Pull request merged**
