### PR TITLE
New contraband crate drug: Skeet

### PR DESCRIPTION
**Pull request by ManopolisJones**
epic name, I know

## What this does
Adds a new pill bottle to the cargo contraband crate with a new concoction: Skeet, one part sleep toxin, one part hyperzine, three parts cryptobiolin, all parts fun.

[Warning, somehow even MORE low quality showcasing video]

[droggas.webm](https://user-images.githubusercontent.com/89323872/190092637-829b7cee-df17-4429-b49f-1e76a6299e0e.webm)

## Elaboration
Skeet is described as a raver party drug, with a visual effect of foggy vision from the sleep toxin, a high heartrate and speed from hyperzine, and sporadic movement from cryptobiolin, leave what I believe to be a fun and unique drug combination. 
This PR was spurred on from a past of toying with recreational drug combinations, and with my recent purchasings of contraband crates to take copious amounts of PCP and Space Drugs, I wished to throw my hat in the ring with a new drug combination for people to check out without needing me to make and distribute it.

If I can think up anymore good recreational drugs to add to the contraband crate, i'll certainly make up another PR, although the options are all very limited when you factor in things like redundancies and the injection of new ghetto chems out into the wild.

:cl:
 * rscadd: Adds a new pill concoction to the contraband crate: Skeet, Ravers drug of choice to become the life of any party.

### CODE REVIEW

**Comment by jwhitak** [comment]
Removing zoom pills bad. Adding these new pills to the rotation instead? Good. The contraband crate needs more new stuff, it doesn't have a lot of things to generate, IMO.

**Comment by jwhitak** [comment]
You can't find the pill bottle DM? It's ```/code/game/objects/items/contraband.dm```. Add a new entry in your current file for your cool new drugs instead of replacing zoom.

You can add the new pill bottle you make to ```code/datums/supplypacks.dm```

I can code it for you to keep both. Zoom pills have their current cargo use (don't remove my synap).

**Comment by Eneocho** [comment]
Add mescaline or space drugs to the mix as well for them colours.

**Comment by jwhitak** [comment]
~~Third comment, the pills as-is are extremely weak. The high lasts ten whole seconds, and then you get free hyperzine for nearly three minutes. You've turned these into free hyperzine pills, not cool party drug pills...~~

Mixed up hyperzine and crypto. The sleeptoxin blurriness lasts 20 seconds, high lasts about 30 seconds, the hyperzine, about a minute.

**Comment by ManopolisJones** [comment]
> You can't find the pill bottle DM? It's /code/game/objects/items/contraband.dm

holy fucking shit, because of course it wouldn't be in weapons/storage but instead objects fucking items.

> Mixed up hyperzine and crypto. The sleeptoxin blurriness lasts 20 seconds, high lasts about 30 seconds, the hyperzine, about a minute.

From testing, if you take one pill and let it ride out like in the webm, both the crypto and the hyperzine should wear off at the same time (done deliberately to avoid unwanted fast speech after the dizzyness effect wears off) however, if you take the pills as intended, which would be another pill every time the fog wears off, once the crypto wears, there will still be active hyperzine left in your system.

In regards to keeping both zoom and cryptosporidium pills in the contraband crate, I shall do as much if a couple more people object to the zoom pills flat out replacement (more so especially now since I know where the damn pill bottle location is).

**Comment by Optimism333** [comment]
> "Straight from the mothership drug labs"

How could you do this. Drugs are BAD. Broodmom said so.

On a more serious note, I would also suggest having this in addition to the zoom pills. Not removing them entirely.

> Add mescaline or space drugs to the mix as well for them colours.

Also consider this. What's a rave without bright colors? See if it pairs okay with the blurry vision.

One other thing, though it's just preference. Give the drug pills a fancy or fun name, preferably something short and easy to remember. Zoom rolls off the tongue real nice and easy, Cryptosporidium not so much.

**Some unoriginal ideas:**
Vim and Vigor (Extremely unoriginal. Don't use this one)
Gogo
Juju
Lolla Palooza
Glim Glam
Thrash Up
Shindy Bindy
Bop Hop
Razzle Dazzle (Suggested by Dilt)
Fucitol (Suggested by Dilt)
Sporispin (Play on the current name)
Cha Cha
Rejuv
Skut

**Comment by Eneocho** [comment]
>One other thing, though it's just preference. Give the drug pills a fancy or fun name, preferably something short and easy to remember. Zoom rolls off the tongue real nice and easy, Cryptosporidium not so much.

Just keep the name as is, people will shorten it to Crypto, which will give you a reason to claim crypto ruined your life.

**Comment by Optimism333** [comment]
> > One other thing, though it's just preference. Give the drug pills a fancy or fun name, preferably something short and easy to remember. Zoom rolls off the tongue real nice and easy, Cryptosporidium not so much.
> 
> Just keep the name as is, people will shorten it to Crypto, which will give you a reason to claim crypto ruined your life.

No, that's LAME. LAAAAAAAAAAAAME. We can do BETTER.

If it must be a play on the current name, it ought to at least be Sporispin, or something like that. Drug marketing is half the experience, having it be shortened to crypto is just confusing.

**Comment by ManopolisJones** [comment]
and here I thought the ayy player would be able to appreciate the duel destroy all humans reference AND the reference to the  parasite that causes gastrointestinal illness, to which said aliens name is too a reference. That being said, if I needed to choose an alternate name for the drug, it would probably be "Skeet". Anyway, when I wake up i'll probably update the pr to make the pill bottle a separate item and give it a new name and all that jazz. Please stand by.

**Comment by Optimism333** [comment]
> and here I thought the ayy player would be able to appreciate the duel destroy all humans reference AND the reference to the parasite that causes gastrointestinal illness, to which said aliens name is too a reference. That being said, if I needed to choose an alternate name for the drug, it would probably be "Skeet". Anyway, when I wake up i'll probably update the pr to make the pill bottle a separate item and give it a new name and all that jazz. Please stand by.

Honestly I only got one of those references. Alas...

Regardless, I still think changing the name for a fun, quippy one would be good. Whether it's "skeet", or any of the random other ones I threw out onto the list.

**Comment by WindowsErrors** [comment]
name it the zoomer pill and do random zoomer speak

i like bananas because they have no bones

**Comment by pedr69** [comment]
finna skeet all over the bridge fr no cap

**Comment by jwhitak** [comment]
I have been appeased, your thumbs down has been removed and changed to a thumbs up. Speesemen may now choose between ZOOM, HAPPY, and SKEET.

**Pull request merged**
