### PR TITLE
Fixes missing hat icons.

### LINKED ISSUE #33022: UN Helmets don't fucking work
The helmets introduced in #32742 as /obj/item/clothing/head/helmet/tactical/antichrist display without a sprite when spawned.

image

### PR DESCRIPTION
**Pull request by Eneocho**
Turns out the icons for the UN Helmet, laserproof mask and bulletproof mask were removed by accident.
[hotfix] Fixes #33022.
:cl:
 * bugfix: Restores the antichrist.

### CODE REVIEW

**Comment by pedr69** [comment]
did you do mob/head.dmi too? those seem missing as well

**Comment by Eneocho** [comment]
No but I'll do it now.

**Comment by Kurfursten** [comment]
conflicts, unfortunately

**Comment by Eneocho** [comment]
Still broken? I'll just remake it then.

**Pull request closed without merging**
