### PR TITLE
removed atom del profiler

### PR DESCRIPTION
**Pull request by DamianX**
This doesn't have to be final, I'm just interested in seeing how this affects performance during high pop because this looks pretty bad:
image

### CODE REVIEW

**Comment by Exxion** [comment]
That'll mostly just hide the issue, not change anything. It's the supercall that causes the big number. It's hard dels.

**Comment by DamianX** [comment]
Do you think this isn't worth testing at all, then?

**Comment by Exxion** [comment]
Wait, I just looked at the actual code changes, and this isn't the del profiler I thought it was. Go ahead and try it. It'll just move the big number in the profiler to `/atom/movable/Del()` as far as performance goes, but I don't really think this profiler serves much of a purpose anymore. Honestly I'm not even sure what it was ever for.

**Comment by Kurfursten** [comment]
Experimental it is, then

**Pull request merged**
