### PR TITLE
Fix a metaldetector issue

### PR DESCRIPTION
**Pull request by clusterfack**
Stupid whoever you were cloroxygen
Fixes whatever

### CODE REVIEW

**Comment by clusterfack** [comment]
While I was at it fixed a second issue that probably occurs where it keeps adding a specific overlay every single time you anchor/unanchor it.

**Comment by Intigracy** [comment]
What's the issue this fixes?

From the look of it it's always the same icon_state, and I don't see how your change changes that.

**Comment by clusterfack** [comment]
Thats because the icon state isn't the issue

**Comment by Intigracy** [comment]
Oh, I see.

mb

**Pull request merged**
