### PR TITLE
Librarians now start with a book bag

### PR DESCRIPTION
**Pull request by djkramer123**
Someone requested it, and I wanted to learn how to work this github doodad and code malarkey. I'm not sure how I would get it to autodump books into a shelf when clicked on it given the extent of my knowledge is copying and pasting with slight edits. But even if I can't, it still holds more books than say, a backpack, which is still helpful for stocking the shelves, I'll scratch my head some more and see if I can figure something out later. Github is also very confusing to my small brain so I hope I did this right, if I didn't feel free to yell at me.

It holds 25 books(vs the backpack's 12), including basic books, spellbooks, paper, nanopaper, barcode scanners, pens, and cult tomes. If there's some reason I overlooked that it shouldn't hold cult tomes yell at me for it and I'll fix it. I excluded bibles from it since you can store things inside of them.

new sprite given to me
239756ee4b73ab883f9fbf478c60e1d9

:cl:
 - rscadd: Librarians now spawn with a book bag that can carry books (duh)

### CODE REVIEW

**Comment by SonixApache** [comment]
incorrect :cl: syntax, replace with following
```
:cl:
 - rscadd: Librarians now spawn with a book bag that can carry books (duh)
 ```
 good content otherwise :+1:

**Comment by djkramer123** [comment]
> incorrect 🆑 syntax, replace with following
> 
> ```
> :cl:
>  - rscadd: Librarians now spawn with a book bag that can carry books (duh)
> ```
> 
> good content otherwise 👍

Should be fixed now, thanks

**Comment by Eneocho** [comment]
I was working on the same thing, stop reading my fucking mind I dont want to eat the corn syrup.
Here's my icon even:
book bag

**Comment by djkramer123** [comment]
Someone suggested adding paper to the things it can carry and I've done so.

**Comment by ManopolisJones** [comment]
hahaha holy shit that sprite, it looks like you grilled the gadget bag

**Comment by Kurfursten** [comment]
Add pens and folders. And the barcode scanner.

**Comment by WindowsErrors** [comment]
this took too long to add

**Comment by Eneocho** [comment]
I'd add some blue to the sprite and maybe make it not such a dark brown, but very nice, an improvement over the deepfried bag.

**Pull request merged**
