### PR TITLE
Gives exca. suits a make over and brings them into the hard suit age.

### PR DESCRIPTION
**Pull request by DrSnips**
[sprites] [content]

A long time ago in an research outpost far far away xenoarch suits were yellow for space and orange for anomaly. This time and place is now (kind of) coming back.
This PR makes excavation suits into archaeology hard suits which have the exact same stats as survivor hard suits you find on Roid station. This means they will no longer have radiation immunity but rather a spread of different armors. I'm open to changing this around to help keep survivor suits unique.
`list(melee = 40, bullet = 0, laser = 0,energy = 0, bomb = 65, bio = 100, rad = 50)`
And with their change comes a fresh look to better fit their title of a hard suit. Inspired by DS3 Archaeologist suits. They even call back to the older exca. suit days with a yellow body.
arch_suit 4x size
They have a green/blue light to them as per the source material. I'm considering going a bit more green however.
light
**The current exca. suit sprites are being moved to an anomaly suit and the current anomaly suit is becoming a legacy item you can find via xenoarch.**

Todo:
- [x] On mob sprites
- [x] Inhand sprites
- [x] Icon sprites.

:cl:
* tweak: Xenoarch excavation suits have been brought to the hard suit age and are named "archaeology hard suit" appropriately. They match the survivor suits stat wise but cannot use Goliath plates.
* imageadd: Xenoarch excavation suits have a new sprite to fit in with the other hard suits due to the above. The gen 2 sprite is now an anomaly suit which ARE NOT SPACE PROOF.
* rscadd: The older gen 1 xenoarch suits have been added to potassium "tech" dig sites.

### CODE REVIEW

**Comment by DrSnips** [comment]
For people who are worried that making them hard suits will be the end of the world. I have talked to the Roid map creator and headmin about his observations and thoughts on [survivor] hard suits and science.
Capture

**Comment by ghost** [comment]
If scientists want to powergame it only takes them 2 seconds to steal other departments' hardsuits anyways so balance is kind of irrelevant here.

**Comment by Blithering** [comment]
I've long been against giving science real hardsuits because it inevitably leads to them being taken by nerds who want to wear them "just in case" while they sit in R&D instead of nerds who want to get out on the roid and do xenoarcheology. The slowdown and lack of armour on the current anomaly suit seems to deter these people well enough, but I've seen survivor suits on station far more.

**Comment by SonixApache** [comment]
:-1: to free science hardsuits

the survivor hardsuits are the worst

**Comment by Allspice** [comment]
hardsuit is pushing it

**Comment by Probe1** [comment]
Honestly there is no need to change any stats. Players are not complaining.  I like the existing sprites too but having variety is good.

**Comment by DrSnips** [comment]
I just reused the RoR suit stats so I wouldn't have to deal with theory crafting about stats again. That said I'm still open to suggestions if people feel like they want the two suits to be different.

**Comment by Probe1** [comment]
Just don't touch it is my input.

**Comment by jknpj** [comment]
A hardsuit with the softsuit stats would be hands down the strongest suit in the station. No other suit has 100% rad proofness, not even the CE one.

**Comment by jknpj** [comment]
Why not keep the soft one too?

**Comment by DrSnips** [comment]
This is not related to this PR but I would like to make a rad absorbing module for rigs. It would absorb X amount of rads before the user feels them. There would be a basic and adv. version which has an increased size. The ideal use for it would be for dealing with shards when you absolutely have to in overheats and avoids shard spray in the hall memes. This is avoided by only allowing a few seconds of high rads. The other factor that limits it is that you need to clean the suit in an SSU to reset the suit rad collector so you can't just wait 10 seconds to continue shard memes.

**Comment by DrSnips** [comment]
The soft suits are going to be there. I haven't pushed that part yet but its in the OP at the end in bold. Both old anom and old space (rad 100) will be there. They will use the solid orange and yellow legacy sprites.

**Comment by DrSnips** [comment]
This PR is now finished.

**Comment by SonixApache** [comment]
big gay

**Comment by DrSnips** [comment]
4u

**Comment by Blithering** [comment]
Time to start a collage of sad xenoarchaologists unable to do their job because all the suits are being worn on station by powergamers

**Comment by DrSnips** [comment]
I'd be happy since I get to see people enjoying the sprite more.

**Pull request merged**
