### PR TITLE
Reworks "Create Trinket" Prestidigitation Spell + Adds "Color Change"

### PR DESCRIPTION
**Pull request by gurfan**
Opening this PR on behalf of @kilozombie! 

## What this does 

One of the main distinctive features of Prestidigitation, the ability to make any nonmagical trinket, is completely neutered in SS13. This gives that ability in FULL to the Wizard, allowing them to pick from a few categories of objects to create, including gadgets, baubles, bullets, grenades, coins, et cetera. They also gain the new and innovative ability to Color Change any object they see.

https://github.com/vgstation-coders/vgstation13/assets/51427771/a4e11f9a-28cd-4662-b26b-11d14385b175

## Changelog

:cl:
 * rscadd: Kilozombie: Expanded the list of trinkets that the "Create Trinket" spell can create.
 * rscadd: Kilozombie: Added the "Color Change" spell to the Prestidigitation bundle.

### CODE REVIEW

**Comment by Eneocho** [comment]
I'd like a very small chance for the "what if it was purple" spell to cause sudden vomiting on all onlookers.

**Comment by kilozombie** [comment]
Late, but here's a bigger writeup:

This was inspired by D&D's version of Prestidigiation, same as the spell. The spell gives you a variety of tricks up your sleeve and is, in SS13, really shitty. Not that it's not kinda fun but it's overall extremely limited in how much you can do, party tricks or not. However, D&D 5e has this written as a possible ability:

image

Rules as written, this is pretty innocuous. But a really lenient DM will let you make a lot of bullshit happen with this little trick. Make a bullet! Make a lockpick! Make a figurine of your enemy and throw it at the ground! Make a _grenade_, if your DM is really, really nice to you.

This implements that in a form, making it sort of like a gacha game for possible objects to create. Each category contains a number of things, some of them useless and some of them really neat. This should at least make Prestidigitation a somewhat fun pick for Wizard rather than a near-total waste of points.

The objects have a limited duration depending on the category, with grenades being really short.

Color change should probably be fine except that https://github.com/vgstation-coders/vgstation13/issues/34889 might cause it to be more annoying than necessary. In a perfect world, you would be able to use a second spell to pick any hexcode, and then paint some object (or person) that color, to help further validate this idea of a wizard using trickery and aesthetics.

**Comment by Exxion** [comment]
Man, that video really showcases how awful it looks when you apply a simple `color` to a non-grayscale sprite. I bet it could look a lot better with a color matrix.
Out of scope for this PR, of course. I might give it a try.

**Comment by kilozombie** [comment]
Yeah, `color` is really lacking. I would kill for a method when mapping/bussing that allows for more vibrant color changes that don't just darken.

**Comment by Exxion** [comment]
You can get a better effect than simple multiplication by first converting it to black and white, but it's still only going to darken.
image
(Left is just setting `color` to `#66aacc`, middle and right are using different matrices to convert to black and white first)
(Middle uses the luminance values Lummox gives in the DM Ref, right uses ones from Wikipedia)
(The numbers *seem* significantly different, but the results are nearly indistinguishable)

There's not really an unambiguous way to automatically allow setting a simple color to lighten sprites. You can do it in multiple ways with a color matrix, though. I... think you can give a map instance a color matrix? It's just a list. I have no idea if the map editor will actually show what it looks like, though.

EDIT: Oh, also, while researching this, I found out that Noir doesn't use proper relative luminance values for its filter. It just weights all the channels equally.

**Comment by Eneocho** [comment]
> Man, that video really showcases how awful it looks when you apply a simple `color` to a non-grayscale sprite. I bet it could look a lot better with a color matrix. Out of scope for this PR, of course. I might give it a try.

An even better reason to have that very slight (i'm talking 1% chance) to cause people to vomit if they see the colour changing spell. (or maybe tie it with it changing the overall colour to purple).

**Comment by Eneocho** [comment]
>Oh, also, while researching this, I found out that Noir doesn't use proper relative luminance values for its filter. It just weights all the channels equally.

Yeah that's always bothered me, I've wanted, and even tried to implement, noir but all reds (and only reds) are still highlighted, kinda like gruevision, but noircode works like you described, so you can't do that at all.

**Comment by kilozombie** [comment]
> You can get a better effect than simple multiplication by first converting it to black and white, but it's still only going to darken.

I see what you mean. That still looks pretty damn good in comparison.

**Comment by pedr69** [comment]
>card option can make ID cards

nice
now you just need to get the invocation text to say after the item gets created, as opposed to while you're picking

**Pull request merged**
