### PR TITLE
Return Of The Crossbow

### PR DESCRIPTION
**Pull request by Tokanova**
so uhhh someone removed the ghetto crossbow recipe from the game
me an some other fellows think that's a trash thing to do
so we're gonna BRING EM BACK!

:cl:
 * rscadd: Added Crossbows Back

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Based
Add proper changelog though

**Comment by Tokanova** [comment]
> Based
> Add proper changelog though

i tried
unless you want something more descriptive than 'adds crossbows back'?

**Comment by jknpj** [comment]
WELL, I THINK GHETTO CROSSBOWS SUCK

**Comment by DrSnips** [comment]
Just a refresher for those who don't recall why it was removed. People made a bunch of them and carried several of them to mitigate their low ammo issue with them allowing you to kill people really quick.
see #16222

**Comment by Irradiation** [comment]
You had 7 minutes left before I called you out as a gutless shitposter. Good on you.

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
It was removed for balance reasons (Being an easy-access one-shot weapon)

Fix this, or no deal.

**Comment by Tokanova** [comment]
> It was removed for balance reasons (Being an easy-access one-shot weapon)
> 
> Fix this, or no deal.

I'll try! I think seperating ghetto xbows from regular ones is where i'll start and see what changes can be made from there

In your opinion though, what would you consider 'balanced'? A 5 click kill? 10?

**Comment by kilozombie** [comment]
I think the thing that caught me off guard, at least, is that crossbows *appear* to be shitty until you realize you can put a battery in them and make them 1-shot-kills

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Maybe something like the blunderbuss where ghetto versions of crossbows have a chance to explode if you use 2much power in one shot?

**Comment by bathosbathtime** [comment]
Might be out of scope, but making the ghetto crossbow into its own item with less damage might be a good idea.

**Comment by MadmanMartian** [comment]
That'd be perfectly within scope

**Comment by Dacendeth** [comment]
The powered crossbow is basically a hitscan 75 force gun, is this really the best idea to bring back as something easily crafted?

**Comment by Accipitermaris** [comment]
>I think the thing that caught me off guard, at least, is that crossbows appear to be shitty until you realize you can put a battery in them and make them 1-shot-kills

this is where it got super stronk, yeah

(also correct me if i'm mistaken but the crossbow is still mapped in on the vox outpost for Deff, Bagel, and Roid)

**Comment by Intigracy** [comment]
Make them a two handed weapon to fire after loading it with whatever.

Dropping a loaded crossbow fires it.
Putting a loaded crossbow in your bag fires it.
Getting stunned while holding a loaded crossbow drops the crossbow, ergo firing it.

**Comment by jknpj** [comment]
Feel free to ask for this to be opened again when you start working on it :ok_hand:

**Pull request closed without merging**
