### PR TITLE
Adds Vectors to packed and box armory.

### PR DESCRIPTION
**Pull request by DrSnips**
[Mapping (Box :baby:)] [Mapping (Packed :package:)]
As the title says two Vectors can be found in the box and packed armory lockers.
Hopefully this time my map doesn't make mustard gas.
:cl:
* rscadd: Added two Vectors to Box and Packed armory lockers.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
remove step_x

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
What are the powercreep implications of this?
It would be good to re-state what the Vector does and how it could be used by sec or otherwise in a practical setting.

**Comment by DrSnips** [comment]
To compare vectors and dual wield glocks. (using 380auto ammo)
Vector
-Main feature: Can adapt to mag sizes and technically any ammo. Requires ammo to be in a mag so stuff like rockets and shotgun shells aren't compatible. To switch ammo types you need to take the gun apart via screwdriver, apply the mag to the receiver and stand still for 10 seconds, reapply the receiver.
-Holds 10 bullets.
-Fires two round bursts while in semiauto mode.
-Not a handgun.
2x Glocks
-Holds 10 bullets per gun so 20 shots total.
-Fires two rounds at once.
-Handgun(s).
I'd say they are pretty similar to the glocks in function when using the same ammo. They differ once you put different ammo in the vector at which point you're basically using a different gun so you can't compare it to glocks anymore since the damage depends on ammo rather than the gun itself.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Any outstanding ways people could abuse vectorammo besides goonecode+genfab?

**Comment by DrSnips** [comment]
Not really since the gooncode lacks mags. TBH I kinda hoped that would be the main use for the vector was so you could use that ammo since sec lacks the guns to properly use it.
I don't think you can really abuse it since you can't scan fuck all without a traitor scanner.

**Pull request merged**
