### PR TITLE
Adds mute as a roundstart defect

### PR DESCRIPTION
**Pull request by RFultra**
This PR adds mute as a roundstart defect

Thanks to jknpjr who helped me a shit tonne

### CODE REVIEW

**Comment by RFultra** [comment]
WAIT SHIT I'M NOT ACTUALLY TRYING TO MESS WITH FLOORLENGTH BRAIDS ANYMORE

**Comment by Probe1** [comment]
Cute

**Comment by RFultra** [comment]
pls halp probe

**Comment by Probe1** [comment]
You never EVER commit changes to Bleeding-Edge.  You always make a new branch and commit it to that.

**Comment by RFultra** [comment]
balls
want me to delete and remake?

**Comment by Probe1** [comment]
It will be easiest to do that.  

Here's what you're going to do.  Back up your changes.  Delete bleeding-edge.  Pull Bleeding-edge from this repositroy (d3athrow/vgstation).  **Make a new branch** and paste your changes into it.  Submit that **new branch** as a PR.

Only use bleeding-edge to update your local code to the latest.  If you commit changes to it then this happens.

**Pull request closed without merging**
