### PR TITLE
Human zombies can force open doors

### LINKED ISSUE #31504: Headcrab Zombie access woes
(WEB REPORT BY: thathazmatyoukilledinsof REMOTE: 206.221.180.138:7777)
# Revision
0200e71bccf0b59d387b13bce8c13893b7eb357e

# Description
Headcrab zombies do not retain the access of their hosts
# Steps to Reproduce
Get headcrab'd and attempt to go through a door you might normally have access to
# What you Expected
Busting through the front door of my cargo like I owned the place to eat alive all the co-workers
# What Actually Happened
Needing the smash the windows of my cargo and have my unwitting miner open a door for me to go and kill him

### PR DESCRIPTION
**Pull request by adacovsk**
So I made an attempt at using the host body's access req and spent too long trying to figure it out... The problem lies with `req_access`. Anyway, this overrides any access issues. Seems like a bandaid solution, but it works.

## What this does
- Adds the `OPEN_DOOR_WEAK` flag to human-controlled zombies
- Adds the `OPEN_DOOR_SMART` for less hungry zombies
- Closes #31504
- Removes paincrit halo on revive
- Fixes some grammar

## Why it's good
Easier than breaking through a wall of glass, especially when you already had access on your living/not undead body

:cl:
 * tweak: Human zombies can force open doors and modified some behavior with doors for other zombies

### CODE REVIEW

**Comment by DamianX** [comment]
You're taking `SMASH_LIGHT_STRUCTURES | SMASH_CONTAINERS` away from them, though.

**Review by DamianX — APPROVED** [review]

**Comment by Kurfursten** [comment]
Important: if you give them `OPEN_DOOR_WEAK` but not `OPEN_DOOR_SMART` they will attack ANY DOOR they see, like spiders.

If you give them the smart flag they will only force doors to chase enemies.

**Comment by adacovsk** [comment]
> Important: if you give them `OPEN_DOOR_WEAK` but not `OPEN_DOOR_SMART` they will attack ANY DOOR they see, like spiders.
> 
> If you give them the smart flag they will only force doors to chase enemies.

I'm going to assume that you want me to update the other zombies to `OPEN_DOOR_SMART`

**Comment by Kurfursten** [comment]
Just a matter of whether you want zombies to indiscriminately attack doors, I guess there is an argument for either

EDIT: Smart does nothing on its own, combine it with WEAK

**Comment by Eneocho** [comment]
Zombies forcing open all doors in the off-chance there's someone behind for muh zombie horror atmosphere is kino though.

**Comment by adacovsk** [comment]
> Zombies forcing open all doors in the off-chance there's someone behind for muh zombie horror atmosphere is kino though.

I changed it so that more zombies can open doors, but only the hungriest zombies (based on their description) open doors randomly

**Comment by Eneocho** [comment]
Can NPC zombies evolve? Player controlled ones can do it but I'm not sure if NPC zombies can. This does help the mobloose when the wizard gets the staff of necromancy or the miner gets the mob belt.
On a related topic, we really should add some UI to the zombies. The fact that zombies can "evolve" into more powerful forms (and the fact that the evolution depends on if you died more or fed more) is all but secret tech here.

**Comment by adacovsk** [comment]
> We really should add some UI to the zombies. The fact that zombies can "evolve" into more powerful forms (and the fact that the evolution depends on if you died more or fed more) is all but secret tech here.

Yeah Evolve and waking up from the dead should be separate functions

**Pull request merged**
