### PR TITLE
Ministation complete overhaul

### PR DESCRIPTION
**Pull request by PromethTK11**
Basically i just want to modernize and remake ministation so it's at least a decent station, full image soon
Now miners have a shuttle to the asteroid, and it's the research shuttle too, basically the asteroid shuttle stuff

***TO-DO:***

- [x] Finish the offices for heads

- [x] Medbay overhaul

- [x] Science overhaul

- [ ] Finish engineering

- [x] Domirtories and misc things (Like EVA, tech storage and that things)

- [ ] New jobs distribution

- [x] Pipes and powernet

- [x] Maintenance trash

- [x] Z levels overhaul

- [ ] It is done? (If its checked, then yes)

### CODE REVIEW

**Comment by Chazach** [comment]
Can the mini-armoury with the hardsuits be accessed by officers or only by armoury access?

**Comment by Exxion** [comment]
Why does it still have all those canisters if you removed the TEG?

**Comment by ComicIronic** [comment]
Also, why would you remove the TEG? One of the reasons Mini runs it in the first place is to not have a singuloose be super easy to perform, since it's a lot more destructive on the smaller station.

**Comment by Exxion** [comment]
Yeah honestly bring back the TEG

**Comment by PromethTK11** [comment]
The setup was fucked up actually, it didn't werk so for placeholding i put on the singulooose.

Aaaand the mini-armory can be accessed by the officers.

The canisters are there because i didn't finish the mini-atmos still

**Comment by Exxion** [comment]
Ah, so Singuloth is a placeholder? That's fine then

**Comment by Riekland** [comment]
how the hell did you take those images and why are they so small and blurry

aside from anything else the kitchen/bar/botany area looks like it needs a little more glass instead of walls

don't mix light grey/colour tiles with dark grey tiles, it looks really bad

**Comment by FudgePucker** [comment]
Why not just use an SME?
Piss easy to set up.
Not a genocide if it gets fucked up.
Enough power for box meta and deff put together.

**Comment by Exxion** [comment]
Because Mini has always had a TEG
It's its thing

And Mini doesn't need as much power as ONE of those stations, let alone all of them

**Comment by FudgePucker** [comment]
SMEs can be made super small.
You could power the station with a micro SME and use the room left over for an AME.

**Comment by Exxion** [comment]
Or you could not do that, and instead have the classic TEG that Mini's engineering was always built around.

**Comment by FudgePucker** [comment]
TEG is extremely hard to set up.
SME is 100 times easier to set up and have it run with zero problems and zero baby sitting for hours.
Also Prometh said he couldn't get it to work, and I shutter at the thought of having to make a round start TEG engine set up. It has to be between fully set up just needing fuel injected, and an empty room with a middle finger made with wire.

**Comment by Exxion** [comment]
Dude you wrench down three canisters and press a button
And Mini was *specifically intended* to use a TEG

**Comment by Riekland** [comment]
>TEG is extremely hard to set up.

3c0a67e779ef87e3ad103ae710835209c60e1b81

**Comment by FudgePucker** [comment]
It is compared to the SME.
All you gotta do is cool it, filter it, emitter it, and set up a radiation collector. The more complicated you make the main pipe network the worse the engine will run.
The TEG on the other hand is a cluster fuck. The input and outputs have to be different pressures, I failed my first few TEG builds because of this. All pipes follow the mantra of "flow doesn't exist" except for the TEG. Adding redundent pumps gets you mocked for being inefficient for everything, except for the TEG where its mandatory.

Also I learned atmospherics and how to autism back when the TEG was a huge pile of shit and the R-UST was legit broken and impossible to set up (had an admin manifest himself in and help try to set it up, abusing as many powers as it took, still failed), so the best way to get those sweet sweet high numbers was the SME. So I might just have more practice with the SME and have a prejudice.

**Comment by Exxion** [comment]
The SME is and probably always will be the best way to get big numbers. But big numbers aren't necessary. If you want to get big numbers on a small station, you can always just build the SME yourself

As for the TEG, I'll grant that the last time I used it was on tgcode and also more than 2 years ago, but it was never hard to set up then
Especially on Mini, which came with it basically already set up with a paper detailing how to finish it step-by-step
But apparently the starting Mini setup no longer works, so maybe it's much harder now

**Comment by PromethTK11** [comment]
Updating OP, new atmos

**Comment by FudgePucker** [comment]
That atmospherics looks like a pretty rad set up. I like how to make up for the lack of miners you added the large gas storage containers, and also how they will need to be used more often because recycling is important with no gas miners.

**Comment by PJB3005** [comment]
@FudgePucker you're 100% wrong and retarded.

Second of all, pumps are still a bottleneck with the TEG.

About how the SME is easier than the TEG: no. You're wrong.

To set up an SME you need to insert shard into chamber (newbie can fuck up and touch shard, need I mention airflow?), wrench some pipes (or don't and use the default set up to trigger people like fudge who are too autistic to see simplicity), turn on an emitter and set up collectors (do you realize how many times it's warned NOT TO OPEN THE FUCKING VALVE WITHOUT TANK) 

With the TEG you wrench some cans, turn on the pumps and hit the ignition. Now before you screech "too simple", reminder that you need to refuel it.

Also, an SME explosion on box is Meh and nothing serious. Meanwhile on mini the entirety of engineering would be fucking gone and it'd be a 100% guaranteed round ender.

**Comment by FudgePucker** [comment]
Oh yea sure I am a retard for thinking that the TEG is harder than the SME. There could be a an SME set up that is easier and faster than singularity. Just put the shard in (standard pressure so no ZAS before its turned on), wrench a canister or two of N2 to a connector, fill collectors, turn on an AAC with a premade script, and turn on an emitter. You know what would happen if someone made the SME that optized there would be cries of "muh power creep" and "let's just fucking add a free power button", TEG is easier to set up round start because its already done, there's a god damn premade script on the AAC. Would you rather make a TEG entirely from scratch or an SME? I know that I would prefer to make an SME.

**Comment by PJB3005** [comment]
@FudgePucker you know how hilariously sad that statement is? I'm pretty sure that sums up the default box SME if people could see past their autism.

**Comment by ghost** [comment]
You already can do that with the box sme fudge. Shove the shard in, shove in your nitrogen, an oxygen and get the freezers going. A little pickup with the emitters every hour or so and it runs the station forever.

**Comment by FudgePucker** [comment]
I understand that the default SME set up works fine, the only difficult part is getting the shard in because the vents and scrubbers cause ZAS to kick in, and you can't turn off the vents inside the chamber from the air alarm. Also with the round start setup the single canister connected to the scrubber will eventually clog up and start over pressurizing, the two vent cooling system can't handle large pressure amounts, causing the shard to start its downward slope to destruction.

The fact that prometh can't figure out what was wrong with ministation's TEG means it isn't as fucking simple as you say it is, or is everybody but you "100% wrong and retarded"?

**Comment by PJB3005** [comment]
> Also with the round start setup the single canister connected to the scrubber will eventually clog up and start over pressurizing

Wrong. Scrubbers have no pressure limit.

> The fact that prometh can't figure out what was wrong with ministation's TEG means it isn't as fucking simple as you say it is, or is everybody but you "100% wrong and retarded"?

I would highly doubt that prometh is an engineer. If I gave a crap I could probably design a set up.

**Comment by PromethTK11** [comment]
I can modify the TEG setup to make it work, the thing is that at first it didn't work, so placeholder engine meme that's the singulo

**Comment by FudgePucker** [comment]
If scrubbers have no limit then why do people optimize the waste loop with more vents and cooling?

**Comment by PJB3005** [comment]
@FudgePucker I want to say morals to not abuse bugs but we all know how that goes on here.

I can think of one though: connecting distro to waste would be fatal if it's superheated.

**Comment by ghost** [comment]
You can turn them off at the console they're linked to though.

**Comment by Exxion** [comment]
Scrubbers don't have a temp limit, but both types of pump are more effective (by moles pumped through) at low temperatures
I assume the same applies to the gas filters the waste loop goes through, though I'm not exactly sure how the multiple outputs affect that, so I'm not sure
And if you're just dumping to space, it'll dump more quickly at low temp

**Comment by PJB3005** [comment]
@Exxion actually IIRC the passive vents always move a hard amount of moles per tick so temperature is irrelevant.

Pumps are bottlenecks basically always too.

**Comment by Exxion** [comment]
Yeah but they're *less* of a bottleneck at low temperature, and passive cooling doesn't really take any effort to set up
Also that's wacky with the passive vents

**Comment by PromethTK11** [comment]
Got new cargo, yay

I'm gonna try to finish this before the next week, not entirelly but atleast the map.

Anyone has good ideas about what to do to the another departments? I have something on my head, but new ideas are well received, and feedback too

**Comment by SonixApache** [comment]
I enjoy that Prometh ignores the autistic rambling in this thread and just happily works on.

**Comment by FudgePucker** [comment]
95% of PRs that aren't a hotfix have autistic shit flinging IMO.

**Comment by ghost** [comment]
When this is done, edit the title to [needs review] Ministation complete overhaul

otherwise, keep up the good work

**Comment by Fidelius** [comment]
So nobody is saying anything about the autistic turn-around you have to make to get from arrivals to Sec or Bridge or Cargo because... The clown theater is the center of the station?

**Comment by FudgePucker** [comment]
Its a feature. Clown is the most important job on the station. The station itself revolves around the theater.

**Comment by PromethTK11** [comment]
Remaking this because new name

**Comment by ghost** [comment]
DDDDD:

**Pull request closed without merging**
