### PR TITLE
adds small display to heater/freezer to show dir

### PR DESCRIPTION
**Pull request by SonixApache**
Better displays for directionality on pipe heaters/freezers.
image
Icondiffbot doesn't show it perfectly, but it's a good indicator.
Requested by @PrimeDSS13. 

:cl:
 - imageadd: Changed the sprites for heaters and freezers to better indicate their direction.

### CODE REVIEW

**Comment by DrSnips** [comment]
Works for me

**Comment by PrimeDSS13** [comment]
very nice
not sure the point of keeping the almost identical old sprites, they really wont be used for anything ever I can guarantee it

**Comment by SonixApache** [comment]
I had an idea to make this better, visibility is still kind of ass with the current setup.
The old sprites are there mostly to keep the blinky light templates.

**Comment by SonixApache** [comment]
Little bit more effort, think it's much nicer now.
+ Added an arrow display instead of the D-pad.  It pulses when active.
+ Flipped the position of the activity indicator to better differentiate between heater / cooler
heater
freezer

**Comment by Exxion** [comment]
Oh wow, the screen changes shape with the direction of the machine! How advanced.

**Comment by SonixApache** [comment]
the display is connected to the part that magically rotates the pipe on the bottom without changing the rest of the machine

**Pull request merged**
