### PR TITLE
Sleeper Sanity HF

### PR DESCRIPTION
**Pull request by Kurfursten**
Encountered this on Packed with @Kammerjunk 

Shouldn't be able to sleeper inject yourself anymore, nor operate the sleeper by keeping the window open after you die or something (I only encountered the former).

:cl:
 * bugfix: Fixed a bug that let people interact with sleepers from the inside, and others.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Actually hold the door on this one, I'm gonna add sanity to the full body scanner and mancrowave while I'm at it

**Comment by DamianX** [comment]
This doesn't account for silicons, right?

**Comment by Kurfursten** [comment]
Silicons are allowed to use the interface (e.g.: AI, medborgs, etc.)

**Comment by DamianX** [comment]
Also, won't this just prevent opening the window, rather than clicking on an already open window? If that's the case, you need to place the sanity checks inside /Topic

**Comment by MadmanMartian** [comment]
From what I remember, there was some specific typechecks to make sure mobs such as mice couldn't fuck with sleepers and such. Has that functionality been preserved?

**Comment by Kurfursten** [comment]
Mice would fail dexterity_check

@DamianX  I see what you're saying now, we should have it check adjacent only if it's not a silicon. And yeah we can do an extra one in Topic. I'll come back and make changes after lunch.

**Comment by Kammerjunk** [comment]
Knew I shouldn't have told you 😠

**Comment by Kurfursten** [comment]
🤔

Why would you not want to report something that you immediately recognized as a bug?

**Comment by Kammerjunk** [comment]
A few reasons come to mind like forgetting to entirely and being really lazy but it was actually just a meme you dip

**Comment by Irradiation** [comment]
It's a feeeeaaaatuuure

**Pull request merged**
