### PR TITLE
Nuke Op spawn with a Ryetalyn pill if they have some active genes

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* rscadd: If a Nuclear Operative spawns with some active gene, such as near-sightedness or fatness because of character setup, they will now receive a ryetalyn pill in their pocket to offer them the ability to get rid of those defects by themselves.

### CODE REVIEW

**Comment by Eneocho** [comment]
Why not just force randombody on these kinds of antags?

**Comment by DeityLink** [comment]
> 
> 
> Why not just force randombody on these kinds of antags?

Honestly I thought they did, years ago I suggested having "special" character slots to let people set up their characters for Nuke Ops specifically, but people didn't like the idea because of the meta potential. But now it appears to just use the main prefs so whatever. I think people like it like that.

**Comment by Blithering** [comment]
Fair enough, you dont want your RPG guy fumbling with an inhaler in a tense situation or, heaven forbid, lisping.

**Comment by Eneocho** [comment]
Make the ryetalin pill also have 1u of lipozine in case the guy got fat from defects so they can actually wear a space suit.

**Review by ShiftyRail — CHANGES_REQUESTED** [review]
Nuke ops have an outfit datum loadout. Put that check here.

**Comment by DeityLink** [comment]
@ShiftyRail done

@Eneocho the Fat mutation actually already has some code in place that prevents it from ever being a problem (along with a custom message about Syndicate training putting you back into shape)

**Review by ShiftyRail — APPROVED** [review]

**Comment by Eneocho** [comment]
>
> 
> @Eneocho the Fat mutation actually already has some code in place that prevents it from ever being a problem (along with a custom message about Syndicate training putting you back into shape)

Then instead of the ryetalin pill why not just add the rest of the roundstart defects to the removal via syndicate assistance? I've had more than one flop round get tougher than it should due to my character spawning without glasses and being nearsighted.

**Comment by DeityLink** [comment]
Well you know that you have a slim chance to also getting a positive mutation right? I'd rather let the player decide whether to keep them or not.

**Comment by Eneocho** [comment]
>
>
>Well you know that you have a slim chance to also getting a positive mutation right? 

That's a thing? Or you mean the positive mutations from jobs (like sober from bartender)?

**Comment by DeityLink** [comment]
> 
> 
> > Well you know that you have a slim chance to also getting a positive mutation right?
> 
> That's a thing? Or you mean the positive mutations from jobs (like sober from bartender)?

It is very much a thing, in fact 20% of players supposedly spawn with a random bad mutation, and 10% of those have a good mutation on top 
image

I must have had a good mutation happen to me like twice in all my years of spess. It feels like the actual chance is much lower somehow seeing as nobody seems to really mind it. I used those numbers to determine the chance of roundstart diseases when I made nuviro but turns out that contagious diseases are a lot more noticeable than an isolated, often useless, genetic mutation. 

Once in a while in medbay I see players come asking for rye because they spawned blind. (bad mutations are also much quicker to fix than a disease I guess)

**Comment by ShiftyRail** [comment]
That chance is low because this mutation isn't coded to activate. Only when you get a random mutation on top of that (such as the bartender's sober, the detective's noir, or in some cases when your are not a human) does this mutation activates.

**Comment by DeityLink** [comment]
> 
> 
> That chance is low because this mutation isn't coded to activate. Only when you get a random mutation on top of that (such as the bartender's sober, the detective's noir, or in some cases when your are not a human) does this mutation activates.

Hm, isn't that an oversight though? (that explains why I get most of those random mutations when I actually play bartender)

Don't get me wrong I think 20% is way too high, but I didn't think only bartender and detective could have those.

**Comment by ShiftyRail** [comment]
It's definitively a bug

**Pull request merged**
