### PR TITLE
Snaxi Update

### LINKED ISSUE #30089: snaxi doesnt have nu tradervend
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
47c01796e762d2cc09d266df1f977d01cf206cd7

# Description
snaxi only has the old trading machine and not the nu wardrobe/extra id/etc one
# Steps to Reproduce
play snaxi
# What you Expected
gladness
# What Actually Happened
sadness

### PR DESCRIPTION
**Pull request by Kurfursten**
Some minor updates for Snaxi
fixes #30089
fixes a misdirected ore unloading machine (it wasn't updated when they were changed)

made atmosia feel less cramped
there are now external waste line ports for the scrubbers outside atmosia
added an extra southern external exit to atmosia
the supermatter computer now starts linked to the shard in the crate
image

moved atmos cans near the engines from atmosia to save space, slightly bigger secure storage
image

AME now near other engines, more intuitive location
image

moved the pipe dispensers from atmos to a new annex at the north exit of the core, nobody uses these so it's mostly for flavor to keep them
image

Shuffled some tables into atmosia so that the engineering equipment room feels more spacious
image

:cl:
* tweak: Snaxi atmosia is now less cramped - AME moved near TEG, and other minor mapping fixes.

### CODE REVIEW

**Comment by Servalfang** [comment]
fix trader vend problem you dweeb

**Comment by Kurfursten** [comment]
Read line 2 of the OP

**Comment by wotisjanitor** [comment]
minors rejoice

**Comment by Kurfursten** [comment]
I just noticed in the OP the atmos area is now slightly misaligned, causing 3 hallway tiles to technically be in atmos. In practice this won't affect anything because there are no lights there, but I do want to fix it before it gets merged.

**Comment by xeroxemnas** [comment]
Can you please replace the godawful huge air scrubbers (fugly oldcode) with portable ones in toxins please. 
ew

**Comment by Kurfursten** [comment]
Easy to do but why wouldn't you want the big ones? They eat plasma at 4x speed and it's tradition to have a couple near toxins.

**Comment by xeroxemnas** [comment]
They're incapable of draining individual tanks like the portable ones are. Important for bomb making.

**Comment by Kurfursten** [comment]
Okay, reasonable. I'll put the big ones in the storage room and add a portable one. I will also look into possibly making this room a little bigger (this could be hard due to position) because it is one of the most cramped workstations on Snaxi.

**Comment by xeroxemnas** [comment]
Thank you I appreciate it

**Comment by Kurfursten** [comment]
I am going to do this in about 12 hours. I've looked at the map and I think it may be best to hold off a major rework of the science department.  I will include the scrubber change out but look for another PR shortly after this one merges -- I'm going to hit all of south station science with a significant expansion.

Not that it matters -- Snaxi is offline for 3 months, but I want it to be ready for winter.

**Comment by Kurfursten** [comment]
Okay, it's ready. I talked to more engineers and moved the AME down near the other engines. Atmos is now yawning in size and you can fill up air cans from outside atmos at the pumps like on other maps. Engineering equipment room now has FAR less cluster and is easier to move around in. New pics in OP.

I also swapped out that scrubber as promised... South Science rework will be a big project and it needs to be its own PR.

**Pull request merged**
