### PR TITLE
fixes 7077

### LINKED ISSUE #7077: Stormtrooper hardsuit modification kit doesn't work on helmets
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> db7bb2614063c55865595853c3a42ea8d568e249 
> 
> General description of the issue
> Stormtrooper hardsuit modification kit doesn't work on helmets. You can use it, but no helmet actually pops out.
> 
> What you expected to happen
> Use kit on sec hardsuit helmet -> stormtrooper helmet pops out
> 
> What actually happened
> Use kit on sec hardsuit helmet -> nothing pops out
> 
> Steps to reproduce if possible
> Use modification kit on sec hardsuit helmet.

### LINKED ISSUE #7102: Stormtrooper Helmet Lacks Image
(WEB REPORT BY: rhimrifer REMOTE: 158.69.55.2:7777)
Revision: db7bb2614063c55865595853c3a42ea8d568e249

Stormtrooper helmet obtained from stormtrooper conversion kit on a security hardsuit helmet has no image so it results in a bald head.

To get a stormtrooper helmet with an image

I got a stormtrooper helmet without graphics

Use stormtrooper upgrade kit on security hardsuit helmet.

### PR DESCRIPTION
**Pull request by ghost**
fixes #7077
fixes #7102

### CODE REVIEW

**Comment by 9600bauds** [comment]
what does this fix?

**Comment by ghost** [comment]
I forget

**Comment by Imagebard** [comment]
Someone merge this shit already.

**Comment by 9600bauds** [comment]
Someone merge this shit already.

**Pull request merged**
