### PR TITLE
Vox creampie

### PR DESCRIPTION
**Pull request by Securitymain**
Splat!
grafik

## What this does

[sprites]
Adds race-specific creampie sprites for vox, greys and insectoids

## Why it's good

Using the human overlay for all races looks terrible. It's floating in the wrong place in the wrong shape.
Sprites provided by the one and only TinySaturn

grafik
grafik
grafik

## Changelog

:cl:
 * imageadd: Added race-specific creampie overlays for vox, greys and insectoids

### CODE REVIEW

**Comment by ErrorsWindows** [comment]
🧐

**Comment by RealestEstate** [comment]
awful PR name, phenomenal PR

**Comment by CrazyAmphibian** [comment]
>vox creampie

what did he mean by this?

**Comment by d3athrow** [comment]
fucked up that im subjected to this slop in my email

**Comment by DeityLink** [comment]
amazing bait & switch

**Pull request merged**
