### PR TITLE
Slow down grue proliferation a bit

### PR DESCRIPTION
**Pull request by Hinaichigo**
[tweak]
This increases the time it takes for a grue egg to become ready to hatch from 30-45 seconds, to 2.5-3 minutes. The reasons for this are to:
- Give humans more of a chance to go try and hunt down the eggs, adding another "phase" to the gameplay with humans potentially trying to find the eggs and grues trying to keep them hidden and defended, instead of quickly creating new grues shortly after someone gets eaten.
- Slowing down the numbers-based snowball a bit so rounds can continue to go on with grues lurking in the background but not necessarily becoming a huge threat as quickly.

It's one idea but I'm curious if people think this would be a positive or a negative change, so please let me know your thoughts on the matter. And we can bundle some other tweaks into this if people want. 
 
:cl:
 * tweak: Increased grue egg development time.

### CODE REVIEW

**Comment by Eneocho** [comment]
I feel the current rate is good enough.

**Comment by WindowsErrors** [comment]
usually what happens is that there's one alpha power grue that's got like 13 kills and the 8 or so other cannon fodder grues that get spawned in midround end up just getting clapped because the crew is all militarized and shit trying to fight off the beast of gévaudan

**Comment by adacovsk** [comment]
maybe just slow down full grue speed a lil

**Comment by WindowsErrors** [comment]
well i think since the main grue is less busy pumping out useless eggs they're gonna be spending more time engaging the crew which will probably equate to a lower survival time in the long term

**Comment by Hinaichigo** [comment]
Okay, so seems like things are generally fine with the egg laying aspect as-is.
Noted on the movespeed thing.
And is Drain Light currently working well in terms of the range, how long it lasts per person eaten, etc.?

**Comment by adacovsk** [comment]
> Okay, so seems like things are generally fine with the egg laying aspect as-is. Noted on the movespeed thing. And is Drain Light currently working well in terms of the range, how long it lasts per person eaten, etc.?

it's sometimes hard to gauge when you're going to die due to light exposure

**Comment by Hinaichigo** [comment]
How so do you mean?

**Comment by Eneocho** [comment]
It's hard to calculate how long can you survive exposure when you're, for example, eating someone who has a lantern in their pocket. I tried it a few days ago and died to the PDA light because I had 30% health which I assumed was enough to eat the guy. I died one tick before eating succeeded, so I never healed.

**Comment by Hinaichigo** [comment]
Ah I see. Would more frequent ticks of light damage help? Say every 1/3 of a second or so rather than the current every 2 seconds. Each tick being weaker of course.

**Comment by Eneocho** [comment]
It would. And some better healing for the cannon fodder grue (before becoming big boy monster).

**Pull request closed without merging**
