### PR TITLE
Removes raping officer from lobby

### PR DESCRIPTION
**Pull request by Zth--**
This is a personal opinion, It's a low quality lobby screen, with terrible font, terrible background, terrible movement. Basically everything in this lobby gif is terrible. Most of our splashworks are great, so we don't really need this one

_Link nsfw: [shitcurity](http://i.imgur.com/3hbPFKu.png)_

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by SonixApache** [comment]
it's a very /vg/ thing to have, though

**Comment by 9600bauds** [comment]
If we're removing any lobby splashes I kinda wish the one with the chef whipping the botanists would go
The animation is REALLY annoying, it's not funny or pretty, pretty much the opposite happens in the game

**Comment by Riekland** [comment]
no thanks doc

**Comment by Zth--** [comment]
_Let me be clear with this:_ I don't mind the ERP thing, I mind the fact this splashwork is really low quality shit

**Comment by jknpj** [comment]
It manages to be worser than cybort farts in the "muh fetish fuel" scale while being toeing-the-line NSFW.

**Comment by SonixApache** [comment]
we're a /vg/ server, not a christian server

**Comment by kol1th** [comment]
>removing thanks doc

One step closer to reddit.

**Comment by yclatious** [comment]
I hate reddit as much as the next guy, but thanks doc was never a good lobby screen anyways, if anyone wants to remake it and do it decently, im all up for it, otherwise, remove it.

**Comment by N3X15** [comment]
Even though I've had a few close calls with this when I was living with my folks, it's a part of the /vg/ culture now.

Also it's supposed to be shit, the original source material is shit.

**Comment by NigglyWiggly** [comment]
"No"

**Comment by Boxe** [comment]
🍆

**Comment by SangriaMonkey** [comment]
Safestation 13

**Comment by Kurfursten** [comment]
Personally, this loadscreen is the only reason I can't play SS13 in public - or at least not wait in the lobby

It's not an issue that comes up often but it is a little annoying

**Comment by CptWad** [comment]
how about a safemode preference so people can disable it at their own will
everyone is happy

**Comment by 9600bauds** [comment]
ain't nobody gonna go through the effort of that just to salvage the second crappiest lobby splash

I mean, we have 17 of these things now and more just keep on getting added, we can afford some quality control

**Comment by mrpain666** [comment]
IM LITERALLY SHAKING
IM SO TRIGGERED

**Comment by yclatious** [comment]
Id be down for a toggle button honestly, if anyone gave a rats ass and did it.

**Comment by SkowronX** [comment]
Just add a toggle button to every damn thing why don't we.

**Comment by Boxe** [comment]
thats it im toggling your sarcasm

**Comment by gbasood** [comment]
It may be  very 4chan and /vg/ but it's also very not safe for work, or you know not safe for leaving your basement or showing spess to a friend or etc
I tried to test a bugfix I was working on in public once and this came up
It was not nice

But why does this PR touch on like 3 other files dude

**Comment by Iamgoofball** [comment]
please add a toggle for players opinions

**Comment by mrpain666** [comment]
Let's add a toggle for TG coders who dont even play the game or set foot in /vg/station while we're at it.

**Comment by Iamgoofball** [comment]
Let's add a toggle for ad hominem arguments too

**Comment by clusterfack** [comment]
I always end up covering it with another window anyway so I don't have to look at it. We've added plenty of screens now, removing it should be fine.

**Comment by PJB3005** [comment]
Making a toggle is surprisingly difficult actually, because of BYOND.

**Comment by Probe1** [comment]
If this is an issue there are other servers you can try.

**Comment by PJB3005** [comment]
I disagree.

Entirely.

Give me a good low RP server that's still calm and has ZAS.

I'm not here from 4chan and I sure as hell don't want to be, but it's by far the best SS13 server. At least for my taste. I'm sure there's other people that feel the same way. 

Closing a PR because "muh 4chan culture" is stupid.

**Comment by Boxe** [comment]
🍕

**Comment by Riekland** [comment]
Is this satire

**Comment by mtpowell** [comment]
Should remain. It's a parody of an old /v/ meme, which /vg/ originates from. Removing it would remove some of the server identity.

**Comment by ThePlapatin** [comment]
P"Advertise on reddit"J"Hippie is welcome"B isn't from 4chan? color me surprised

**Comment by SonixApache** [comment]
hey look it's the guy with the boner for pjb again

**Comment by Killette2** [comment]
We can't be too SFW, or else we'd be remoing things like space asshole and beepsky's fuckyourshiteatingcunt and I don't want that.

**Comment by ThePlapatin** [comment]
@SonixApache I'll have a boner for you too if you want, meet me in deff's dorms in 3 minutes

**Comment by Gef21** [comment]
thanks, doc

**Comment by Zth--** [comment]
People have spoken

**Comment by Probe1** [comment]
@PJB3005 I know, but it's who we are.  You have to accept some identity and thanks doc is pretty much at its core level.

@Zth-- if you want a toggle, get me a toggle.

**Comment by Intigracy** [comment]
We could always remove it from the repo and add it to the secret repo.

It's not removed from the server but people locality hosting never have to see it

**Pull request closed without merging**
