### PR TITLE
Increases the price of summon guns/swords/magic

### PR DESCRIPTION
**Pull request by F-OS**
Increases the price of Summon Guns/swords/magic. Why yes I am salty about the past 3 rounds, why do you ask?
[<gameplay>]

:cl:
 * tweak: The price of summon guns/magic/swords has been increased.

### CODE REVIEW

**Comment by iFlashYou** [comment]
Reaction PR...

**Comment by Gringonius** [comment]
Reaction thumbs....

**Comment by ghost** [comment]
One person using their survivor free antag ticket to destroy a round isn't grounds to remove some of the most fun spells in the game.

**Comment by F-OS** [comment]
This PR doesn't remove the spells, it simply increases the price, this is to prevent wizards giving everybody 3 different guns and to make summon spells more balanced.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
One day we'll make it so that "survivors" can't just immediately baguloose

But not today

**Comment by Kurfursten** [comment]
Even though this appears to have overwhelming negative opinion it will get its week to try to find support.

**Comment by FudgePucker** [comment]
I think that two bags of holding shouldnt create a singularity.
Does science REALLY need another way to end a round? At least 6bomb lmao requires basic understanding of atmospherics and a little effort, at least releasing the singularity requires you to have access or hack though four doors.
I PUSHED TWO BUTTONS ON THE PROTOLATHE, ROUND OVER :DDDDDDDDDDD

**Comment by FudgePucker** [comment]
What's the point of a singularity beacon when you can just create a singularity at the location you want to fuck?

**Comment by F-OS** [comment]
I've pushed a slight decrease to the price, now, summon costs 25 points instead of the original 40, this is a middle ground between 20 points, allowing for 5 uses, and 40 points, allowing for 2 uses, 4 uses should slightly decrease the impact and cause the wizard to commit to going full summon while still allowing the spell to have a large effect.

**Comment by F-OS** [comment]
This doesn't have any popular support and i've fucked up git branches so I think it's best if I close it.

**Pull request closed without merging**
