### PR TITLE
Bounced shots can hit the shooter

### PR DESCRIPTION
**Pull request by Sprok0**
Projectiles that bounce off walls can now hit whoever fired them

### CODE REVIEW

**Comment by SonixApache** [comment]
Projectiles can bounce off walls?

**Comment by Shadowmech88** [comment]
Bouncing is governed by a projectile-level var. Not many projectiles have it toggled on.

The ricochet rifle projectiles and the Lawgiver's ricochet rounds do.

**Comment by Sprok0** [comment]
So do the OSIPR bullets and dark energy orbs.

**Comment by SonixApache** [comment]
I'm pretty sure I've hit myself with the ricochet gun before.

**Comment by Sprok0** [comment]
The ricochet rifle has it's own set of snowflake procs that let it do what it does, this is for normal bouncing bullets like the lawgiver.

**Pull request merged**
