### PR TITLE
less wizard

### PR DESCRIPTION
**Pull request by gurfan**
halves chances

:cl:
 * tweak: Halves wizard chances.

### CODE REVIEW

**Comment by SnakeEater14** [comment]
I’ve always felt wiz fires too often and is better treated as a chaotic detour from the round. Less wiz is good in book

I do know a lot of people love playing as wiz (if not fighting it) though, and may view this as grudge code

**Comment by calzilla1** [comment]
I turn 3/4 of the station into slimes and this PR is made, interesting...

**Comment by PrimeDSS13** [comment]
five wizards in a roll and this PR is made, interesting...

**Comment by gurfan** [comment]
> I turn 3/4 of the station into slimes and this PR is made, interesting...

yes

> five wizards in a roll and this PR is made, interesting...

yes

>I do know a lot of people love playing as wiz (if not fighting it) though, and may view this as grudge code

yes

**Comment by kilozombie** [comment]
If you can grudgecode I can grudgethumbsdown >:(

**Comment by SonixApache** [comment]
we just need more variety for Dynamic to throw around

**Comment by Dacendeth** [comment]
The round after this PR was also wizards...

**Comment by APCUnlocked** [comment]
Yes, wizards always invariably gunk up the round especially if they aren't braindead and just take that mfing blink like every other magicmaxxxer. No RP to be had, just run after funny magic man with shotgun.

**Comment by xeroxemnas** [comment]
Blink is OP and cringe. Based PR.

**Comment by ShiftyRail** [comment]
3 days rule + overwhelming support : the PR has enough support
Don't think this is the correct way to do it, though

**Comment by ShiftyRail** [comment]
https://docs.google.com/spreadsheets/d/1kbYWTjYOPS_FrG5fURSHF8e531r3fUQHcyNqfjUoH0k/edit#gid=0

Nevermind, according to my simulation this should do the trick.

**Pull request merged**
