### PR TITLE
Fixed cult runes not containing pathogen when drawn with pathogen-infected blood

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* bugfix: Fixed cult runes not containing pathogen when drawn with pathogen-infected blood.

### CODE REVIEW

**Comment by tuypo1** [comment]
On the one hand I feel like this may actually be TOO disruptive to the cult but on the other hand it might be good ammo to point at as a major weakness that already exists the next time some whiny fuck tries to nerf cult.
Is it still infectious when concealed?

**Comment by DeityLink** [comment]
Yes. Also it already works if you get the infected blood from a container first instead of your body.

**Comment by tuypo1** [comment]
Isn't that kind of lore breaking though, doesn't the conceal rune shift the runes out of our reality slightly.
Although I suppose it's only moving the rune, not any infected air

**Comment by FudgePucker** [comment]
Use science goggles to find concealed runes

**Pull request merged**
