### PR TITLE
Additional Maintenance Connecting Security to Ghetto Bar: Box

### PR DESCRIPTION
**Pull request by plosky1**
[box]
[controversial]

So this is a (relatively) big maint addition to box, stretching from ghetto bar to security. A number of rooms have been added, along with NW solars being stretched up. The idea behind this change is that box is severely lacking in maintenance areas for antags to do shit, and this also connects security to more of the station. I didn't want to move space pods because it's a cool little dragracing strip now and more realistic in that the spacepod is in a protected hangar instead of attached to the side of a station.

The specific changes are as follows:

An overall picture of changes:
heh14

EDIT: Glass and grilles changed to lattice.

lattice

Air storage room has been moved and a rage cage has been put in under ghetto bar.

Ghetto bar, stays the exact same except the backroom has been made two tiles smaller.

Cult room. Just flavor shit and a ritual knife.

Blocked off rooms containing trapped monkeys, a ghetto kitchen (by request of jknpjr), and a single bee. 

Ghetto bathrooms moved up.

Two maint rooms connected to sec side, one cursed. Airlocks leading to space.

:cl:
 * rscadd: New box maintenance by ghetto bar. Extensive additions.

### CODE REVIEW

**Comment by Kharkov72** [comment]
based bee

**Comment by Hoshi-chan** [comment]
Should channel your inner Duny and replace the bee with a viscerator.

**Comment by plosky1** [comment]
it was a zombie originally but made it a bee since box maint isnt supposed to be dangerous like deff maint, or so im told

**Comment by cadaverouscoyote** [comment]
wow disgusting

**Comment by Lunstra** [comment]
>moved solars but didn't move the other external airlock so now there's two external airlocks next to each other on the escape pod side and none on the tumor side

Sasuga mappers. Also you blocked off the broken window entryway into the ghetto bar with a table which is moderately annoying given there's now a big ol room in the way of you going around the bar.

**Comment by Exxion** [comment]
Long podbay is very fucking funny
Couldn't you think of *any* other solution?

**Comment by plosky1** [comment]
Well ya could move it, but pod racing tho. Also kept in double airlocks on solars because one requires engi access. There's airlocks on sec maint side but yes, none on the actual tumor.

**Comment by OriginalBorbsRA** [comment]
I like the detective's office having a little window out into space and putting the equivalent of a mass driver space there kindof ruins it.
Also copying maint secrets wholesale from other maps is kinda dumb. Can't say I'm a fan. Why do we need to make the ghetto bar smaller, and have a second rage cage when nobody ever even uses the first one? Or a ghetto kitchen that's almost fully stocked but has no access to ghetto botany shenanigans.

**Comment by Accipitermaris** [comment]
I think this is some pretty unnecessary deff-ification of box in service of an extra maintenance route that is pretty redundant.

Additional maint tumors are sufficient to expand maintenance itself, but not necessary. Another way to add more room to maintenance without tumor-izing the joint is to fill out concaves in the exterior silhouette of the station, and to clear out unuseable spaces. [See shitty mspaint reference image.] Because the added space roughly conforms to the silhouette of the station instead of "breaking it", they come across less like tumors while also preserving the maintenance paths themselves.

[White arrows are paths, white Xs are nixed areas. Solid red lines are proposed walls, dotted red lines are possible walls for additional expansion in the mapping.]

Box NWmaint 1 1

**Comment by boy2mantwicethefam** [comment]
Absolute madman and absolutely based, I like this change

**Comment by ValkyrieSkies** [comment]
Bring back the long pod launchways, they're **KINO**

**Comment by ShiftyRail** [comment]
I'm fine with it, but I like Accip idea more.

**Comment by plosky1** [comment]
Just made some minor changes. Ghetto bar backroom re-extended to 2x3. "Deff"-style maint blockage changed to wooden crosses found on box. Extra space access moved to arrivals. Rage cage kept in and expanded with proper glass around it and a windoor. Less blood in cult room.

hehfinal1

**Comment by SonixApache** [comment]
DEFFinitely dangerous, but pretty cool.
I'd swap the gay cult room with the old bathrooms, though.

**Comment by Gringonius** [comment]
Maps that's aren't deff shouldn't be a maint hellhole.

**Comment by plosky1** [comment]
To be honest I dont understand how this qualifies as ‘’a maint hellhole”. If the definition of that is that its simply a larger maint, then I question why that should be deff-specific as box is notorious for having a small maint that nearly every player has memorized. This is not seen as a good thing by the majority of the playerbase. It’s also why certain team antags very commonly build space bases because the maint is so bad on box.

**Comment by Blithering** [comment]
people need to stop pasting the fucked up deff floors onto other stations.

**Comment by plosky1** [comment]
The dirt? Or the burned/damaged tiles? Please be specific, all of this is subject to change.

**Comment by Blithering** [comment]
The pre-damaged but sometimes not actually damaged just an unremovable decal but you never know which tiles.

**Comment by plosky1** [comment]
Ah gotcha. I’ll update all the floor tiles to regular floor tiles.

**Comment by ValkyrieSkies** [comment]
Useless hidden rooms like the Cult room are out of place on maps like Box, on a properly functional station it should be something with actual purpose like an emergency shelter or some sort of redundant backup room.

**Comment by plosky1** [comment]
I'll change it to something useful then.

**Comment by plosky1** [comment]
Changed cult room to ghetto washer room, complete with mankini because no collabs will ever push this through 😏 

heh14

**Comment by bathosbathtime** [comment]
Please place lattice between the podbay flaps as a compromise.  This will surely solve everyone's issue with the change.

**Comment by plosky1** [comment]
lattice

I expect all downthumbs to upthumbs :^)

**Comment by Kurfursten** [comment]
A washroom would be welcome on the right side of the station, but so close to laundry? We're talking less than 20 tiles away.

I appreciate the idea of more practical maintenance rooms but this one's a miss for its location.

**Comment by plosky1** [comment]
doing big edits that honestly require a new PR. dont fuck me up

**Pull request closed without merging**
