### PR TITLE
Trio of Metaclub fixes.

### PR DESCRIPTION
**Pull request by Probe1**
- Fixes https://github.com/d3athrow/vgstation13/issues/6860 by adding a desk bell
- Fixes https://github.com/d3athrow/vgstation13/issues/6864 by shifting each field generator to the left/right respectively.  https://github.com/d3athrow/vgstation13/pull/6874#issuecomment-162186721
- Fixes https://github.com/d3athrow/vgstation13/issues/6866 by deleting the extra object.  Credit to @unid15 for finding the issue and reporting it in the bug report.
- Replaces the pod walls on the security pod to correct the same issue as d3athrow#6866
- Replaces invulnerable shuttle window on security pod with a full compliment of reinforced plasma windows.  The next step down from outright invincibility.  I think it fits right.   I asked in game and players/admins think it fits right.  Invulnerable walls don't really have a place except out of necessity and it is not necessary here.  https://github.com/d3athrow/vgstation13/pull/6874#issuecomment-162197023

### CODE REVIEW

**Comment by Probe1** [comment]
Singlo fieldgen shift.

image

**Comment by PJB3005** [comment]
Er, @Probe1 the field gens on the right and left side of the field are still on the same y coordinates, have you tested this (make sure to DELETE the singularity generator before testing)

**Comment by Probe1** [comment]
Updated

image
(its a sauwastika, not a swastika, but it can be if you want)
( had to google what a reverse swastika is called)

**Comment by IratePirate** [comment]
TRIGGERED.

**Comment by PJB3005** [comment]
Swastikas aren't bad anyways IMO, I think it's stupid people freak out about swastikas.

They used to be a perfectly good symbol of peace or something, then Hitler went "oh this looks neat" and now everybody hates the symbol.

**Comment by Probe1** [comment]
Shit I did just cause it'll make people react.

**Comment by Probe1** [comment]
tested.

orbital_crypt_fifteen_2015-12-05_09-10-44

**Comment by Probe1** [comment]
image

**Comment by Probe1** [comment]
gross now this is a balance PR and I need to amend the changelog.

**Comment by ihadtoregisterforthis** [comment]
@PJB3005  All the history I know says that the nazi swastika is the mirrored image of the "good swastika", called Sauwastika.

I didn't know field generators had such long range.

**Pull request merged**
