### PR TITLE
Soul Rambler music no longer makes you fat or vomit if vegan.

### PR DESCRIPTION
**Pull request by Eneocho**
### What this does
Shakashuri music no longer fills you with Chill Wax but rather Chill Essence, which has the same pacifying and druggy effect with none of the nutrition.
### Why it's good
You can enjoy peaceful frankenstein's monster music without vomiting or going obese (though those effects and similar could be added to a Pied Piper item).
:cl:
 * rscdel: Shakashuri music no longer makes you fat or vomit if you are vegan.

### CODE REVIEW

**Comment by jwhitak** [comment]
When Xavier shows up, you know that the show you're watching is very weird. In fact, you should add more random effects to the music. But only after watching the entire show.

**Comment by Dacendeth** [comment]
Wont this also remove the brute healing, since no nutriment factor?

**Comment by Eneocho** [comment]
> Wont this also remove the brute healing, since no nutriment factor?

I never even noticed the shakashuri wax healed brute that way. Though considering food is not really an issue most of the time I don't think it's that big a loss.

**Comment by Kromkar** [comment]
> > Wont this also remove the brute healing, since no nutriment factor?
> 
> I never even noticed the shakashuri wax healed brute that way. Though considering food is not really an issue most of the time I don't think it's that big a loss.

repoban he for this

**Pull request closed without merging**
