### PR TITLE
Don't 👏 claim 👏 you 👏 like 👏 rap 👏 if 👏 you 👏 don't 👏 know 👏 who 👏 this 👏 is 👏﻿

### PR DESCRIPTION
**Pull request by SysadminJeroen**
Adds THE Biggie Cheese

I hope it was done correctly.

:cl:
 * rscadd: Added a mouse called Biggie Cheese, it spawns in boxstation toxins testing area.

### CODE REVIEW

**Comment by kol1th** [comment]
ebin

**Comment by Probe1** [comment]
Why not.

**Comment by ComicIronic** [comment]
Oh look, a Facebook meme PR.

Bravo, will merge immediately.

**Comment by ghost** [comment]
mind if i hit that YEET?

**Comment by ComicIronic** [comment]
To clarify, I am actually closing this Facebook meme PR.

**Comment by SysadminJeroen** [comment]
@ComicIronic 
>implying i'd know it is a facebook meme

Do memes even propagate that fast over Facebook? I mean they have a shitload of old people on them.

**Comment by Intigracy** [comment]
He probably means the emoji every other word in the title.

**Comment by ihadtoregisterforthis** [comment]
Someone 👏 clearly 👏 doesn't 👏 like 👏 rap 👏

**Comment by SysadminJeroen** [comment]
@Intigracy The title really doesn't matter, I mean look at the branch name.

Someone :clap: clearly :clap: doesn't :clap: like :clap: rap :clap:

**Comment by ComicIronic** [comment]
Biggie Cheese started on Facebook. It's also less than 2 weeks old.

**Comment by SysadminJeroen** [comment]
@ComicIronic Just because the ERP happened on Facebook doesn't mean that the spread happened on Facebook.

**Comment by ComicIronic** [comment]
It has spread on Facebook, and, as a rule, anything intentionally funny on Facebook also spreads on Facebook.

**Comment by Intigracy** [comment]
Why does a male human have nipples tho

**Pull request closed without merging**
