### PR TITLE
Different Insectoid Flavors Now Available

### PR DESCRIPTION
**Pull request by GreatBigFailure**
There's been a few requests for multi-color bugs, so here they are.
You can now pick the color of your insectoid's carapace in character creation. Obviously this is going to cause a lot of knee jerk reactions because neon rainbow anime bugs should not exist, that's why there's been a lot of experimenting done to find a good limit. Instead of allowing the full spectrum of color **I've limited it to between values of 0-80 for red, 0-50 for green, and 0-35 for blue.**

**These are the most colorful they can get. Top is the darkest and lightest. The others are pure R/G/B or max mixes of the two (80/0/35, etc)**
shinyhead

I think these are fairly reasonable however if people prefer them more/less restricted then that is very easy to change, **these aren't the set in stone limits.**
This also makes bug "hair" match their skin. Using hair/skin dye dyes both.

If you think this needs tweaking please let me know. Again, it's very easy to change the limits until we find a good balance.
**Update:** I'm very tired of fucking with bug colours and don't want to for this PR any more. Still give me opinions for use with any later attempts if those are necessary.

:cl:
 * rscadd: Insectoids now come in a variety of colors

### CODE REVIEW

**Comment by gurfan** [comment]
I think most look alright but the pink/blue/teal ones are a little jarring, their colors just seem off

**Comment by GreatBigFailure** [comment]
Some of them definitely fit more than others. I can create color specific limits as well. Alternatively I can widen the limit but make it so the values can only be a certain amount apart. It'll take more experimenting but I wanted people's opinions on this version first.

**Comment by SageOfLight** [comment]
> I think most look alright but the pink/blue/teal ones are a little jarring, their colors just seem off

I think the issue comes down to not having appropriate greyscale sprites yet. The base sprite is the default brown you've seen so any color added on top of that may result in some unintended levels of red tinting that'll throw it off.

**Comment by PrimeDSS13** [comment]
mmmm fruity pebbles 🤤

**Comment by TGFH** [comment]
I like the brown/red variants but I don't think the lighter colors really fit. The purple, green, and pink are all very pastel looking and give me a Paradise vibe when I look at them.

**Comment by GreatBigFailure** [comment]
Like I said I can keep tinkering with the limits and as Sage mentioned we haven't actually tried greyscale yet. I'm not personally fond of the left column aside from the top one. I might lower the maximum on blue and green but reduce the minimum on all of them to 0. Red, for some reason, doesn't really cause any issues.

**Comment by GreatBigFailure** [comment]
Greyscale happened and we kept tinkering. Because the colours come out a lot less weird than when we were using the old sprite it's been requested to try a higher limit. The (current) new limit is 0-90. Meaning you can make any colour any value between 0 and 90. Here's the collage of min/maxes with this new value. Left side is 0/0/0 and 90 red, blue, green in that order. The right side has two colours maxed with 90/90/90 at the top. Bottom is 45/45/45. 

newbugz


As before this is not set in stone and I'd like your opinion on it. I have no eye for colour or that sort of thing so really I'm just going along with requests from people who do. 
I'm also going to make an issue so more eyes get a say for the sake of fairness.

**Comment by gurfan** [comment]
some of those look way too saturated imo, I support this change if I get to valid anyone who makes a neon pink bug

**Comment by SageOfLight** [comment]
> some of those look way too saturated imo, I support this change if I get to valid anyone who makes a neon pink bug

If they try to be an unfunny memester I'll join you. This collage doesn't show all the tints and shades you can ideally make with this range. Trying to drown out the colors has the negative effect of making a proper red unable to show up for example. It's the reality of the RGB system.

**Comment by SageOfLight** [comment]
After some personal experimentation with the colors I think the issue is the blue is too overpowering in most color options. 

Edit: I think I found the sweet spot, 80/35/35
image

**Comment by GreatBigFailure** [comment]
Changed the limits again to compromise between requests for more vibrant colours and more muted colours. The new possible colour values are:
**Red** 0 to 80
**Green** 0 to 50
**Blue** 0 to 35
Here's what the extremes look like
shinyhead

Top are black and white, left side are max red, green, blue with the other colours at 0. Right is max of 2 colours with the third at 0. Bottom is all values half their max (40/25/18).

**Pull request merged**
