### PR TITLE
Taxi Fix

### LINKED ISSUE #4714: [TAXI] Tcomms SMES isn't connected at all
Not even a terminal.

### LINKED ISSUE #4716: [Taxi] Literally no fire extinguishers
Each room needs a wall mounted fire extinguisher. The only extinguishers on map that I found were the small ones in the scarce o2 lockers and 1 or 2 in maint.

### LINKED ISSUE #4723: [Taxi] these fucking faggot ass airlocks holy shit
~~the thing that makes coins, unless the Chef's mint is also missing~~

additionally:
ss 2015-05-27 at 10 37 44
this thing is NOT a replacement for a cycling external airlock, it's always depressurized and always causes air alarms in Mining lobby even when you are extremely careful. Besides being ugly and blocky as sin it makes your life as Miner a ZAS kind of hell, and is a huge kick in the dick whenever you forget your magboots, because there's no way to open it without getting your shit pushed to the ground.

### LINKED ISSUE #4725: [Taxi] Botany oh fucking why
There are no xenobotany disks at botany.
There are no plantclippers in lockers.
There is only one shovel.
Backroom has no table for the non-existent disks and is too small.

Tray count is fine since you can just spam dirt trays by shoveling grass and planting in hallways.

### LINKED ISSUE #4726: [Taxi] Taxi cabs are silent killers
There should be a check whether all airlocks to taxi are closed before movment, including the red ones, to prevent people getting spaced because taxi teleported moment before they stepped on it.

### LINKED ISSUE #4730: (WEB REPORT BY: gravelordsmaug REMOTE: 198.245.63.50:7777) Stuck inside a wall
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Was crawling through the vents as an alien and got stuck in the wall behind botany on taxi station.

>What you expected to happen
I expected to get out of the fucking vent. I had an amazing run and it really pissed me off.

>What actually happened
Everybody ganged up on me while I couldn't move and killed me.

>Steps to reproduce if possible
Go be an alien and try to exit above botany on Taxi. Absolute bullshit.

### LINKED ISSUE #4735: [Taxi] How did this even happen?
image

### LINKED ISSUE #4748: (WEB REPORT BY: apeh REMOTE: 198.245.63.50:7777) No shells for shotguns (TAXI)
No shells for combat shotguns in armoury. Simple as that. Taxi station only.

### LINKED ISSUE #4764: (WEB REPORT BY: weinermaster69 REMOTE: 198.245.63.50:7777) Chefs on taxi need botany maint access
>Revision d82b2d5106339cbee0daf7f8fce62e1a2757ef82 

Chefs need botany maint on taxi. They have it on all other maps (to my knowledge) and not having it makes it a real pain in the ass for chefs with no botanists. It means they have to leave via the backroom of the bar, into that main corridor, into the boxing ring area, into botany and then back. Pls fix

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

### LINKED ISSUE #4772: [taxi] Vox outpost has shit mapping
* The windows above atmospherics have no glass, only griles
* Valve on the scrubbers loop is fucked
* No lights in atmos
* No air alarm in EVA
* magic floating double air alarm in atmos
* Better airlock needed between the O2 and N2 areas
* Scrubbers set to meatbag mode
* External cycling airlock has no controller
* ALL THE WINDOWS have no grilles
* No APC in the main hallway
* No youtool

### LINKED ISSUE #4773: [TAXI] Floating light in sec station solar control

### LINKED ISSUE #4817: (WEB REPORT BY: chickenzness REMOTE: 198.245.63.50:7777) Vox outpost is not safe for vox. (Taxi station)
>Revision: 9ab63cbd151069ddd9a1ee089a57a3519f583817 
>Vox outpost has oxygen in it.

>To be able to take off the internals as a vox.

>Recieved damage from toxins.

>Analyze air in the outpost on Taxi station.

### LINKED ISSUE #4861: (WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) [TAXI] Cargo has no filing cabinets
>Revision 

b1cf0b6c121dca8a3f65a272bd69bf19b8aff5f8

>General description of the issue

There's no filing cabinets.

>What you expected to happen

Me being able to do my paperwork.

>What actually happened

NO FILING CABINETS HOW COULD I PISS PEOPLE OFF WITH PAPERWORK LIKE THIS?!?!?

>Steps to reproduce if possible

Be beaurocratic QM
Realize you're on taxi
cry

### LINKED ISSUE #5005: (WEB REPORT BY: Anonymous REMOTE: ) Taxi Telecomms tech access issues
Telecomms tech's round start accesses are messed up. On taxistation he cannot get to his workplace without robotics and AI access.

### LINKED ISSUE #5009: (WEB REPORT BY: Anonymous REMOTE: ) No flour in taxi kitchen
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
There's no flour to be found in the kitchen at round start

>What you expected to happen
Flour

>What actually happened
No flour

>Steps to reproduce if possible
Play taxistation

### LINKED ISSUE #5010: Taxi Station: Medbay Needs Two Roundstart Cryoxadone Beakers
The other stations have it, and it's convenient not having to make cryox in addition to clonex. There is one beaker in the paramedic's area (despite the Taxi paramedic not having their own cryo tube) but there should be two regardless.

### LINKED ISSUE #5092: (WEB REPORT BY: Anonymous REMOTE: ) Few station intercomms on the Taxi station, there are none in chemistry.
There is a lack of station intercomms in several areas of Taxi stations departments. Chemistry is one such department.

### LINKED ISSUE #5109: (WEB REPORT BY: Anonymous REMOTE: ) Broken jukes at Taxistation
>Revision: 70a954d31ad5ca0aa1b5a41e116f29ffa4957a97
>General description of the issue
Jukeboxes don't work at Taxi for some reason.

>What you expected to happen
Judging by the fact that this is Taxi Station, I doubt it will be fixed.

>What actually happened

>Steps to reproduce if possible

### LINKED ISSUE #5110: (WEB REPORT BY: Anonymous REMOTE: ) Telesci shield gens don't have req_access set to 55 instead of 0
>Revision 70a954d31ad5ca0aa1b5a41e116f29ffa4957a97 
Can't unlock the telesci shield gens as a scientist on taxistation.

### LINKED ISSUE #5245: (WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) (Map Issue - Taxi) Bar Juke
Has blank playlists because a generic juke was used instead of a bar juke

### LINKED ISSUE #5257: Add RnD boards to Taxi Tech Storage
Tech Storage on Engineering Station lacks any kind of research boards.

### LINKED ISSUE #5310: (WEB REPORT BY: sentientcloud REMOTE: 198.245.63.50:7777) Kitchen starts without any flour or sugar on Taxi
>Revision ad66440799a8825cf29c5a89227f408488fba993

Seriously, what the hell?

### LINKED ISSUE #5323: "airtight" plastic flaps
the plastic flaps used in the routing areas on taxistation are "airtight", but for some reason they don't actually block air, so the areas vent at round start

### PR DESCRIPTION
**Pull request by Kurfursten**
- RD boards in tech storage fixes #5257
- Juke is now Bar Juke fixes #5245 fixes #5109
- Kitchen now has Kitchen Cabinet (flour/sugar) fixes #5310 fixes #5009
- Changed the front AI Upload/Telecommunications door to needing only ONE to access instead of BOTH fixes #5005
- Added a filing cabinet to Cargo Office fixes #4861
- Telescience shield gens given proper access fixes #5110
- Medbay now has roundstart Cryoxadone fixes #5010
- Floating light fixture moved to wall fixes #4773
- Botany maint requires only botany, not maint access fixes #4764
- Armory contains all four shotgun shell box types fixes #4748
- The door to the AME room is no longer considered to be in space fixes #4735
- Added a missing air distro pipe in Botany backroom fixes #4730
- Added lattice around the Taxi docks fixes #4726
- Botany contains the proper amount of spades, plant clippers, and has a flora disk box fixes #4725
- Added 34 fire extinguisher cabinets fixes #4716
- Telecommunications properly hooked to its own SMES fixes #4714
- Added Gashapon Machine (Niggly's request)
- Added more than 50 station intercoms fixes #5092
- Mining entrances now are unsimulated fixes #4723
- Replaced plastic flaps with air tight models fixes #5323
- Vox Post: Fixed windows, removed extra air alarm, added lights, added main hall APC, fixed waste loop, added YouTool, improved N2->O2 Airlock fixes #4772 fixes #4817

### CODE REVIEW

**Comment by Kurfursten** [comment]
I swore last time when the clean map tool didn't properly reduce my edit size that I would never edit maps again.

Clearly I broke my oath in vain.

**Comment by PJB3005** [comment]
Damn that's a lot of fixes, map merger fucked up or not :+1: :x: :100:

**Comment by NigglyWiggly** [comment]
I'd suggest replacing one of the existing vending machines with a getmore, because the only way to get non-poisonous vending machine food is to break into the bridge on the sec/science station.

**Comment by Kurfursten** [comment]
@NigglyWiggly I am pretty sure that was a deliberate design decision, to encourage Chefery or Cargo to order some Getmore packs.

**Comment by NigglyWiggly** [comment]
@Kurfursten Oh, my bad then

**Comment by Probe1** [comment]
I was going to make an issue about the singularity but my gut told me it was a design decision.

Should there be cameras and a viewing console on it so we can see it better?  Gut says no it's intentionally shitty.

**Comment by PJB3005** [comment]
Singularity is too shit already anyways, IMO it should have a camera to make it SLIGHTLY less shit

**Comment by ComicIronic** [comment]
Are you using the right airtight flaps? There's a version that starts anchored.

**Comment by ComicIronic** [comment]
>making air tiles unsimulated

NO
NONONONONO
I WILL NOT TOLERATE THIS MAPMAKER HANDHOLDING
It is a disgusting standard that has gone on too long in the old mapping.

**Comment by PJB3005** [comment]
CYCLING AIRLOCKS NOOOOOOOOW

**Comment by Kurfursten** [comment]
I'm just keeping consistency with box which uses the same system

If you want to change the standard that seems like it should be a separate discussion/pr

**Comment by PJB3005** [comment]
\>I'm just gonna keep consistency with box.

Might aswell keep consistency with relative pathing, colour macros, and colons.

**Comment by Kurfursten** [comment]
@PJB3005 We do keep consistency with relative pathing in some places. Moreover, false comparison. Using unsimulated tiles has balance/gameplay considerations that those other things don't. It should have a discussion and be changed everywhere at once if people want it changed.

**Comment by ComicIronic** [comment]
>I'm just keeping consistency with box which uses the same system

No, you're making changes to revert back to consistency with an outdated system.
The current tiles were left as they are for a reason. Change does not need to happen all at once in a case like this.

**Comment by Kurfursten** [comment]
@ComicIronic If Taxi were more up-to-date than Box, this PR would not be nearly as long. I find it difficult to believe that the most-played and most-updated map is unintentionally outdated. It seems to be a design decision to me.

**Comment by PJB3005** [comment]
More like nobody can be bothered to fix the airlocks because they're lazy

**Comment by ComicIronic** [comment]
It's a design decision I disagree with, because it's sloppy and encourages bad play.
That nobody has bothered to change Box is no reason to revert Taxi to Box's assbackwards design decisions, especially when we're progressing to getting rid of them.

**Comment by Probe1** [comment]
Please Kurfurst, listen to Comic.  Unsimulated tiles are my pet peeve.  They provide an inconsistent experience and are used way too often as a crutch.  Taxi fucks me up HARD because I'm so used to every single external airlock having some fucky varediting or unsimulated tiles instead of a real airlock.  Don't bring this from Box, it's not good.

**Comment by Exxion** [comment]
Just so you know, that line "failed to resolve #5323" still contains "resolve #5323" and thus will autoclose #5323 if this is merged

**Comment by Kurfursten** [comment]
@Probe1 @PJB3005 @ComicIronic If someone changes it on Box, I'll change it in this PR for Taxi. I'm not super attached to the idea of unsimmed airlock turf, but I do like consistency.

**Comment by ComicIronic** [comment]
Don't pile on more work for others.
We have no reason to keep consistency with a bad system, especially when this is mapping and not coding.

**Comment by Probe1** [comment]
that's exactly the problem.  the airlocks on box are what are inconsistent.  there are even airlocks that are properly simulated around security maint that shitty mappers missed.  they'll get me good when I forget and I get sucked out.

**Comment by Exxion** [comment]
Box Disposals airlock is also simulated
Unsimulated airlocks are bad and you should feel bad

**Comment by Kurfursten** [comment]
@Exxion Glad to hear you're volunteering to change all the others on Box, looking forward to your PR.

**Comment by Exxion** [comment]
Sure, whatever. It could be done in maybe two minutes with a text editor. It should wait until we have working cycling airlocks, though.
Or external airlocks could just be given a shorter closing delay, which is much more effective than you might think.

**Comment by PJB3005** [comment]
cycling airlocks already work...

**Comment by Exxion** [comment]
Occasionally

**Comment by Probe1** [comment]
They work, they work.  They just give extremely poor feedback.   Which convinces people they don't work.  https://github.com/d3athrow/vgstation13/issues/4943

**Comment by Exxion** [comment]
No, they legitimately sometimes fail to work, unless it's been fixed since I last checked (which is a distinct possibility)
Sometimes they get confused and simultaneously pump air both in and out, making the pressure fluctuate but not significantly change
Probably comes from hitting the button too quickly, but I'm not sure

**Comment by PJB3005** [comment]
@Exxion That makes no sense, that's not how vents work at all, unless airlocks actually us SUCH shit code they don't use signals that's possible but otherwise no.

**Comment by Exxion** [comment]
I've seen it happen multiple times, though it's been so long I don't remember *which* airlocks I saw it in
Defintely pod bay, but there was at least one other
You could sit there for minutes and watch as the pressure went down and back up and back down endlessly
Pressing the button again would fix it

**Comment by FudgePucker** [comment]
I am in support of mining entrances being unsimulated.
Mining involves a ton of going in and out of pressured areas and unpressured areas.
If you put one of those slow ass cycling air locks the windows are getting busted so they don't have to deal with that shit, because fuck it, everyone that is on mining base already has a hardsuit.

**Comment by ComicIronic** [comment]
Then the Miners can deal with underpressurised areas.
The game is not intended to give people everything they want at the cost of good design.

**Comment by Probe1** [comment]
somehow we've managed to survive on Defficiency and Meta mining outposts without the crutch of cheated air tiles.  

only box has this.

**Comment by Kurfursten** [comment]
Someone really should add map logging to round start information so we can tell if Meta or Defficiency has been picked at all this week.

**Comment by Exxion** [comment]
The only time I've played within the past month or two was a Meta round
It's picked reasonably frequently

**Comment by d3athrow** [comment]
@Kurfursten map votes are already logged

**Comment by d3athrow** [comment]
ok then ctrl+enter why'd you close the PR

**Pull request merged**
