### PR TITLE
Fixes really major bug that really should have been fixed a long time…

### LINKED ISSUE #31943: html is desanitized for traitors
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
b879dddba0f6a2afcf72a77f4696f3e9c031ecb5

!(https://files.catbox.moe/ocej7s.png)

### PR DESCRIPTION
**Pull request by Exxion**
… ago

Fixes #31943
Tested enough to know it does in fact fix that bug
Not tested enough to know for sure that it doesn't break with certain codewords but I'm pretty sure it's fine and I don't have BYOND set up properly on my new computer so testing is very very slow and I got tired of it

### CODE REVIEW

**Comment by Servalfang** [comment]
but what bug is fixed

**Comment by Servalfang** [comment]
i would be cheesed to see this reverted

**Comment by Exxion** [comment]
Yeah let me just send you malicious code through chat

**Comment by Eneocho** [comment]
> Yeah let me just send you malicious code through chat

Based. Please do.

**Pull request merged**
