### PR TITLE
[DNM] Box, Meta, and Taxi fixes.

### PR DESCRIPTION
**Pull request by Probe1**
- Closes https://github.com/d3athrow/vgstation13/issues/6851 Adds Disposals to the research outpost on metaclub https://github.com/d3athrow/vgstation13/pull/6905#issuecomment-162487700
- Closes https://github.com/d3athrow/vgstation13/issues/6898 Adds a hos jacket to the hop locker on metaclub just like it is on Box

### CODE REVIEW

**Comment by Probe1** [comment]
I had to reroute an existing disposal pipe used for .. fucking who knows?  Well it was there and I had to shift it a bit.  I added a new disposal line and 4 bins, as well as pushed the trash driver out a bit more to accommodate.

vgstation13_ mapsmetaclub dmm _-_dream_maker_2015-12-07_06-09-47

**Comment by clusterfack** [comment]
hos jacket to the hop locker? MADMAN

**Comment by Probe1** [comment]
its whats on box.  people think its the 'hop jacket'.  

look what I found right outside the theater back room.

vgstation13_ mapsmetaclub dmm _-_dream_maker_2015-12-07_06-26-38

**Comment by Probe1** [comment]
Disposal pipes man.  They belong in the trash.

**Comment by Probe1** [comment]
I'll deal with the sheer amount of stupid shit that just happened locally later.

**Comment by Probe1** [comment]
Also disposal pipes have retarded sprites.   Junctions that do opposite directions have identical sprites.

**Pull request closed without merging**
