### PR TITLE
Removes balloon bundle

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
JUST my shit up fam
:cl:
 * rscdel: Removed the balloon bundle

### CODE REVIEW

**Comment by Blithering** [comment]
but its the highest value bundle you can possibly roll

**Comment by boy2mantwicethefam** [comment]
Too overpowered
"yeah let's just give the player 8 uplinks worth of items"

**Comment by Exxion** [comment]
I don't like this PR but honestly it's probably a good idea

**Comment by Blithering** [comment]
What if some of the balloons were knockoffs with the letter printed on backwards? would that balance it?

**Comment by boy2mantwicethefam** [comment]
@Blithering It wouldn't balance it, on the contrary it would be even worse because then the uplink would give you worse-off items than what you can simply buy

**Comment by Kharkov72** [comment]
coward

**Comment by agentofzog2** [comment]
It's a better bundle than the one with DNA scramblers.

**Comment by ghost** [comment]
how about you remove the shitty stealth bundles

**Comment by PrimeDSS13** [comment]
I enjoy the gambling aspect of bundles. Bundles generally offer you more worth then what you could usually get by buying singular items. The "bad"/less efficient bundles are a useful way to balance out the pool, so theres a risk involved. Also, the balloon bundle is fun and encourages fun balloon gimmicks.

Basically, please delete this PR or I will cry.

**Comment by boy2mantwicethefam** [comment]
@PrimeDSS13 okay

**Pull request closed without merging**
