### PR TITLE
No more praying while wearing a fedora

### PR DESCRIPTION
**Pull request by RFultra**
This PR prevents you from praying if you are wearing a fedora and instead brings up the message "You are too euphoric to pray, you don't need any phony gods blessing, you are enlightened by your own inteligence."

### CODE REVIEW

**Comment by ghost** [comment]
Madman actually did it holy shit

**Comment by Fruktlimpa** [comment]
>Emojing your own post

Sickening.

**Comment by mtpowell** [comment]
>inteligence

**Comment by SonixApache** [comment]
memes

**Comment by Shadowmech88** [comment]
I believe the misspelling is intentional.

**Comment by gbasood** [comment]
Low quality dated meme in my opinion

**Comment by Durgen** [comment]
memebob
@gbasood

**Review by PJB3005 — APPROVED** [review]

**Comment by PJB3005** [comment]
[Quality control when]

**Comment by ghost** [comment]
this is goofball tier.

But fun goofball tier, not vaccination giving you 100 brain damage goofball tier

**Comment by Intigracy** [comment]
Hey man, that was fun goofball tier.

**Comment by SonixApache** [comment]
memes

as in

don't merge this ever

**Comment by ghost** [comment]
>doesn't want memes on a server with memes based off of a website filled with memes where people talk about memes

**Comment by ghost** [comment]
@Commandersand just because a toilet bowl is full of shit doesnt mean it's okay to fill it with more shit

**Comment by TheFriggenSawbones** [comment]
its a good pr

**Comment by Orangerush** [comment]
> "Thefr*ggensawbones: its a good pr" 

time to close it

**Comment by gbasood** [comment]
i didnt actually mean to do that

**Comment by ghost** [comment]
>no fun allowed

Were not bay ;_; !!!!!!

**Comment by gbasood** [comment]
Fun *is* allowed, just not in 9gag levels of quality.
We have a council of fun revisions to prevent anything of subpar to mediocre levels of fun.

**Comment by ghost** [comment]
>fedora memes are 9gag level quality

Shiet might as well remove the fedora from the atheist religion and replace it with a research disk

**Comment by gbasood** [comment]
You missed the joke.
Also if you want an actual argument against what you said look at what @adu6oo said

**Comment by ghost** [comment]
>closed

RIOT

**Comment by RFultra** [comment]
RIOT

**Comment by SonixApache** [comment]
👌  thank you sood

**Comment by Intigracy** [comment]
wtf i love sood now

**Pull request closed without merging**
