### PR TITLE
Segway for Sec

### PR DESCRIPTION
**Pull request by jewishneocon**
moon spess junk xi 2015-02-22 203505
moon spess junk xi 2015-02-22 203531
a cool segway for sec
included in my commit is: the segway and icon code (necessary)
2 segways included in sec (not too necessary but i hope you use it)

### CODE REVIEW

**Comment by ririchiyo** [comment]
turn off automatically set FILE_DIRT for sub-directories in Build -> Preferences

**Comment by jewishneocon** [comment]
where are map tools

**Comment by jewishneocon** [comment]
bruh thats a lot of work for java
If you wanna take on the map part thats fine but the segway code is there and done

**Comment by ririchiyo** [comment]
You'll need to fix your conflicts if you want it to be merged and deal with the .dme file.

**Pull request closed without merging**
