### PR TITLE
Remove the WIP folder

### PR DESCRIPTION
**Pull request by ShiftyRail**
Someone had to do it at some point
RIP Cael, no longer in the' file tree but forever in our hearts

### CODE REVIEW

**Comment by SonixApache** [comment]
a travesty to our forgotten efforts

**Comment by ShiftyRail** [comment]
All the code is here, it's just moved around in places where it makes more sense, for instance the RUST in `power` submodules instead of an orphan folder.

**Comment by GreatBigFailure** [comment]
Isn't the entirety of space pods in there?

**Comment by ShiftyRail** [comment]
It's been moved to `code/modules/spacepods`.

**Comment by ghost** [comment]
finally

**Pull request merged**
