### PR TITLE
Stops "You can't pick things up!" spam for holopeople

### PR DESCRIPTION
**Pull request by Pathid**
:cl:
* bugfix: Stopped holopeople getting spammed with "You can't pick things up!" when picking things up.

### CODE REVIEW

**Comment by DamianX** [comment]
I'm dumb and I don't get it: why do holomen need this snowflake check?

**Comment by Pathid** [comment]
@DamianX 
Because holomen are simple animals. And they're unique among simple animals in that they pick up items in the standard way. This is unlike parrots and spider-bots which use their own special verbs.

**Comment by DamianX** [comment]
I wonder if it would be better to have a mob-level proc to determine if one can pick things up. The way this is done is kind of backwards.

**Comment by DamianX** [comment]
maybe one day

**Pull request merged**
