### PR TITLE
Adds airlock bolts sounds

### PR DESCRIPTION
**Pull request by Goldsteel**
Doors will now make a clack sound on bolting and a ca-clunk sound when unbolting. This has been tested with hacking using a multitool and wirecutters as a human. Additionally, AIs and cyborgs works fine too. Flavour text adjusted slightly on door hacking from click to clunk.

Further testing: Random events fire like prison break and doors work as intended. Double airlocks at virology/xenobiology on box clunk and clack at the right time.
:cl:
 * rscadd: Airlocks will now clunk and clack when you bolt and unbolt them.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I'm not sure these sounds... fit right. I don't know, maybe I'm just not used to them. I'd like other people to listen.

**Comment by Goldsteel** [comment]
I clipped and edited these sounds because I liked them and that's how I imagined the bolt systems working, whereby the bolting is much faster under gravity assist and unbolting is the opposite and takes longer. We can always change them if anyone has anything better.

I honestly think they sound good in game, especially with xenobio/virology.

I should also add I was going for a metallic/industrial theme instead of a scifi style sound because whirring and pneumatics was very harsh to listen to.

**Comment by brndd** [comment]
To me it sounds like they're the wrong way around. Dropping the needlessly heavy-duty NanoTrasen bolts would make that heavy "ca-clunk" noise that's currently in the beginning of `door_unbolt.ogg`. When the bolts are raised, weak NanoTrasen electromagnets barely pull the bolts out of their slots, making a "clink" sound from `door_bolt.ogg` as the bolts hit the stoppers inside of the airlock.

I still think `door_unbolt.ogg` would be better without the heavy "ca-clunk" sound, though. It just doesn't sound like a sound airlocks would make when bolted. It sounds more like a heavy door violently slamming shut, but that's not something that happens when the bolts are dropped.

**Comment by Goldsteel** [comment]
Originally they were the other way around. I can just rename the files and the problem is solved.

**Comment by SonixApache** [comment]
Oh man, those are some chunky sounds.

**Comment by Goldsteel** [comment]
I'm glad someone else likes them. I really do. I can highly recommend getting used to the sound just playing around with the clunking as a borg. Maybe we could pop this in the test for a bit for demonstration purposes.

**Comment by Goldsteel** [comment]
I think I'll have the bolts as just the bolting sound, with different pitches to determine bolting and unbolting instead of the heavier noise. I think I might use the heavier noise for blast doors for some real beefy clunking. I'll update tomorrow.

**Comment by brndd** [comment]
The updated sounds are really good and fitting IMO. Using the old, "clunkier" sample for blast doors sounds like a good idea.

**Review by MadmanMartian — APPROVED** [review]
Still reckon you should make a ToggleLock function so as to have some file cleanup.

**Comment by Goldsteel** [comment]
Looks like I forgot a bunch of stuff. I think I fixed it, but we shall see.

**Comment by Goldsteel** [comment]
Hopefully this now integrates r0b0s NT EXTRA MEGA DELUXE wire package with +2 wire action

**Pull request merged**
