### PR TITLE
Removed maintenance access from IAA

### LINKED ISSUE #10291: IAA doesn't really need maint access
(WEB REPORT BY: durgen REMOTE: 172.93.109.202:7777)
now that IAA has bridge access, I think maint access could be taken away without causing too much of a headache.

It's pretty hard to blacktide without maint access, so it might lead to people playing IAA more seriously.

Maybe losing maint could be compensated by throwing IAA another bone, kind of like how it already has basic medbay access.
Basic science maybe? It would be useful for inspections

### PR DESCRIPTION
**Pull request by DamianX**
The only purpose of this PR is to gather ~~negative~~ positive feedback so that we can close #10291.

:cl:
 * tweak: Internal Affair Agents no longer have maintenance access.

### CODE REVIEW

**Comment by DamianX** [comment]
Oh, shit.

**Comment by PJB3005** [comment]
Wew I'm surprised that still works.

**Comment by Durgen** [comment]
\>negative feedback
Don’t count your chickens before they hatch

**Comment by DamianX** [comment]
shieeet, if you keep going I'll have to add a changelog and stuff

**Comment by Accipitermaris** [comment]
chadstation when
remove id access requirements on maintenance airlocks

**Comment by FudgePucker** [comment]
:+1: IAA is a fluff RP job.
Do the chef and Chaplin get gen. maintainance access?
If you want to graytide pick assistant.

**Comment by Pathid** [comment]
>Chaplin

As a matter of fact, they do.

**Comment by FudgePucker** [comment]
Oh really? I guess they do have their extra room above them in maintainance.

But still, IAA still has security access right? In all the time I played security, lawyers and IAAs have caused several headaches. If removing maintainance access causes only super autists who want to roleplay to pick those rolls then fucking do it. I know I would rather have that office collecting dust, than to deal with supershitters with security access.

**Comment by Pathid** [comment]
IAAs get access to the front brig doors, which isn't the same as being able to open the lockers. 

But, yeah. IAA is in a weird spot in regards to server culture. Ideally being a shitter IAA would be an invitation for Centcomm to mess with you in all kinds of ways and maybe fire you, but that would take involvement on the part of the admins.

**Comment by FudgePucker** [comment]
Front brig doors is all the access you need to make securities lives hell.

**Comment by Dacendeth** [comment]
I dont play IAA so i upvoted.

**Comment by SonixApache** [comment]
delete blacktide

**Comment by Aurx** [comment]
IAA needed access list:  
Law Office

Everywhere else, they should be asking to be let in or getting access themselves.

**Comment by Blithering** [comment]
IAA has some cargo access, but can only enter via maintenance (on box at least). if they're losing maints, could you let them access the front door?

**Comment by DamianX** [comment]
Sounds good to me but I'll make another PR for it

**Comment by Probe1** [comment]
Throwing up an update wiki since this doesn't look to be controversial.  Also don't touch IAA bridge access.

**Comment by DamianX** [comment]
I don't think the wiki ever mentions IA people having maintenance access?

**Pull request merged**
