### PR TITLE
Revert "New medbay machine: the patient processor (#25333)"

### PR DESCRIPTION
**Pull request by SonixApache**
This reverts commit 81374e7d2fbf21ccc73491bd02903a5932edca49.
image

image

### CODE REVIEW

**Comment by ghost** [comment]
Leave it as a bus thing. Effort was put into it, even if it was joke effort.

**Comment by Tokanova** [comment]
Who are you to deny all the thumbs up it got?

**Comment by MadmanMartian** [comment]
change the changelog to undid stuff

**Comment by ShiftyRail** [comment]
This device is fine as a bus thing

**Comment by SonixApache** [comment]
admemes can already do the exact same thing by hitting rejuv or injecting adminodrazine or whatever it's called

a collab merging something only because that very collab mistakenly put in the effort of actually reviewing the code of a complete meme PR
is bad

**Comment by MadmanMartian** [comment]
It's too late, I'm already making use of this

**Comment by brndd** [comment]
Hitting rejuv or injecting adminodrazine requires manual effort. This thing can just be plopped down in a dorf round or something where you want to keep people from permanently dying but don't want to give them complete immortality.

**Comment by Exxion** [comment]
Adminordrazine showers are funnier but this is less immersion-breaking

**Comment by SonixApache** [comment]
\>editing my OP to contain your explanation instead of just posting it seperately

kurf...

**Comment by ShiftyRail** [comment]
Put both images in the OP

**Comment by ghost** [comment]
I unironically would use this for some busses.
I don't care if it's meant as some meme shitpost about medbay, if it works then keep it in. Worst case is that it'll just end up forgotten in time, with all the other adminbus-only objects.

**Comment by Kurfursten** [comment]
@SonixApache The explanation belongs in the OP. You've actually gone to the trouble of cropping out the explanation to try to make people angry, which actually by definition makes this a shitpost PR (incidentally, this doesn't mean you're in trouble or that this PR will be closed... it just means you're identical to what you're complaining about)

**Comment by N3X15** [comment]
Can I edit OPs I don't like too

**Comment by tuypo1** [comment]
Imagine getting upset about a fun bus item because of stupid discord drama

**Comment by SonixApache** [comment]
the 'discord drama' was to illustrate that kurf was well aware that what he merged was trashy meme content

but whatever, mainting repo quality isn't my job

**Comment by Intigracy** [comment]
I still think we should merge everything that has a higher thumbs up than thumbs down, regardless of how stupid it is.

Give the people what they want.

**Comment by SonixApache** [comment]
people vote ironically, people vote for extremely stupid things
there are standards to be upheld

**Comment by Intigracy** [comment]
If they're going to vote ironically while also holding up emoji ratios as important when things they don't like get merged, they deserve what comes with it.

**Comment by Kurfursten** [comment]
For the record you could've kept this open 5 more days to raise vote support. You get a full week, same as everyone else. But now it's going to be used in the deathmatch thing and frankly I don't see any problem with it being used in that context.

Imagine if someone would just port TG's ability to buy different shuttles as an ironic maymay joke but then people liked it and voted for it. That would be a good thing.

**Comment by SonixApache** [comment]
"the players (that don't all vote) deserve what they get for voting for dumb things" is a horrible opinion to hold

and i'm not gonna raise any more support, what's done is done, i just really don't think stupid shit should be merged, ironic upboats or otherwise - i look up to the collabs to walk that fine line

**Pull request closed without merging**
