### PR TITLE
Knock tacklers away with baseball bats

### PR DESCRIPTION
**Pull request by DamianX**
I was very disappointed when I found out this wasn't already possible.

:cl:
 * rscadd: Do not tackle batters without wearing a safety helmet.

### CODE REVIEW

**Comment by Viciousaurus** [comment]
https://www.youtube.com/watch?v=6g7V5UQzjb4

**Comment by ghost** [comment]
good feature

**Comment by Kurfursten** [comment]
Update the tackle entry on the wiki or I will find you

**Comment by DamianX** [comment]
image

**Pull request merged**
