### PR TITLE
Hazard Vests can now hold RPDs and Socket Wrenches

### PR DESCRIPTION
**Pull request by Kharkov72**
probably an [oversight] really because it can hold a fucking RCD but not an RPD

:cl:
 * rscadd: Hazard Vests can hold RPDs and Socket Wrenches

### CODE REVIEW

**Comment by Kharkov72** [comment]
wait they already fit

**Comment by DamianX** [comment]
🤔

**Comment by Kharkov72** [comment]
you didn't see nothin' kid

**Comment by Kurfursten** [comment]
lol inheritance

**Pull request closed without merging**
