### PR TITLE
Spawned and roundstart slime people start with electric protection

### LINKED ISSUE #24009: Shocked to death as Slime-man.
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
c3702e1414f4cbe5872d591518b58e34fe2ca17a

# Description
got bussed in as a cultist-chaplain-slime due to the crew wanting one on cult. got shocked by the AI and it put me into crit instead of healing. how peculiar? Left security lobby door on box.
# Steps to Reproduce
be a slime lad and get shocked on a door. perhaps wear a cultist outfit? it might just be because it was bussed in
# What you Expected
getting healed by a shock
# What Actually Happened
getting crit'd by a shock

### PR DESCRIPTION
**Pull request by Zth--**
Closes #24009 

:cl:
 * bugfix: Roundstart and spawned slime people no longer get shocked

### CODE REVIEW

**Comment by DrSnips** [comment]
Don't do it like this. Change the ones spawned to evolved versions.
Reason being is because anything that would create an "Evolved Slime" would fuck up with this method. Just change the few spots in the code that spawn slime people to have "Evolved" before them.

**Comment by Zth--** [comment]
I don't see a valid reason for having "Evolved Slimes" as a different species

**Comment by DrSnips** [comment]
Wow congrats you did the exact opposite of what I told you to do and spent way more effort than you needed to. The reason they exist is for a potential round start race since the shock heal would be too strong for round start. The idea was that you "got an upgrade" by doing xenobio.

**Comment by Zth--** [comment]
I don't believe shock heal would be too strong for a round start race. Not to mention it wouldn't have any sense

**Comment by DrSnips** [comment]
Its literally free and unremovable glubs. It would become the ideal shitter race worse than dionas.

**Comment by SonixApache** [comment]
good thing they'll never be roundstart

**Comment by DrSnips** [comment]
Care to test that statement?

**Comment by Blithering** [comment]
So whats the point in having the two types if both have shockheal?

**Comment by DrSnips** [comment]
Something something roundstart option since shockheal is too good.

**Comment by Zth--** [comment]
Removing shockheal on roundstart would be the same as making a new species for roundstart dionaes but without lighthealing. Does it make sense? No. Is it proper balance? No. You don't simply remove its main feature and call it a day.

Also there's no fucking roundstart slime people and I highly doubt they will ever be.

**Comment by Killette2** [comment]
Do you still heal from the shocks you're immune from? This makes me think if you touch a shocked door nothing would happen rather than it healing you. Was that functionality tested?

**Comment by Kurfursten** [comment]
For now at least, this functionality is fine. Fortunately slime people are mapped nowhere so if someone wants to change it back later for RS slimes it will be trivial.

**Pull request merged**
