### PR TITLE
Material Value Balancing

### PR DESCRIPTION
**Pull request by DeityLink**
As many of you know, material values were nerfed to oblivion a bit over a year ago, which was really needed as Miners could make obscene amounts of money in an absurdly small amount of time (think hundreds of thousands of credits)

In my opinion however, that crash was a bit of an overkill. A full stack of 50 plasma nets a miner a mere 10$.

As I am working on a revamp of the Centcomm Order feature, with new fun and interesting orders for all departments (cept Sec, you do your job dammit), we quickly noticed that Cargo/Mining orders looked really lame in comparison, as you'd ship 9 bananium sheets to be rewarded...9 credits? While the xenoarchaeologist would net the Science department 900 credits for a fully completed alien skeleton.

So I've decided that the new material values are definitely too low, and could use some tweaking. So I generated the map several times with a proc that gave me the exact amount of every materials on box so I could get an idea of how much money could theoretically be made through mining. Here are my findings, and my tweakings:

**=Iron= (found in 22.27% of all mine turfs, 15.425 iron ore harvestable on box on average)**
Price Before: 	0.2$	(10$ for a full stack)
Price After: 	**unchanged**. Iron is cheap and plenty available everywhere.(3.085$ potential)

**=Plasma= (found in 11.88% of all mine turfs, 8.230 plasma ore harvestable on box on average)**
Price Before: 	0.2$	(10$ for a full stack)
Price After: 	**1$**	(50$ for a full stack)(8.230$ potential) Cargo can still ship it for more

**=Gold/Silver/Uranium= (each found in 0.75% of all mine turfs, 525 ore of each harvestable on box on average)**
Price Before: 	1$	(50$ for a full stack)
Price After: 	**6$**	(300$ for a full stack)(3.150$ potential per mat, 9.450$ for all three)

**=Diamond= (found in 0.15% of all mine turfs, 105 diamond ore harvestable on box on average)**
Price Before:	4$	(200$ for a full stack)
Price After:	**50$**	(2.500$ for a full stack)(5.250$ potential)

///////Those can only be reliably harvested on RoidStation/////////
**=Bananium= (200 bananium ore harvestable on roid on average)**
Price Before:	1$	(50$ for a full stack)
Price After:	**20$**	(1.000$ for a full stack)(4.000$ potential)

**=Phazaon= (115 phazon ore harvestable on roid on average)**
Price Before:	1$	(50$ for a full stack)
Price After:	**50$**	(2.500$ for a full stack)(5.750$ potential)

:cl:
* tweak: Tweaked the monetary value of a few materials, so they're a bit more profitable (still way less than they were over a year ago)

### CODE REVIEW

**Comment by DeityLink** [comment]
For the curious, the old values per materials per sheet before the nerf was:

iron = 1
gold = 20
silver = 20
uranium = 20
diamond = 40
plasma = 40 (wtf)
bananium = 100
phazon = 200

**Comment by boy2mantwicethefam** [comment]
commenting before comment section autistic arguing

**Comment by GreatBigFailure** [comment]
I think plasma and diamond are a bit high. There's plenty of plasma sheets around the station and it's almost as common as iron. Something like 0.6 would be more reasonable, 1 credit per will add up very fast.
Diamond is rare but it's also concentrated in specific-ish areas so it's not as hard to get as the numbers say. Though it does come in much smaller amounts it's certainly not worth the same as phazon.

This is assuming we work toward making credits at all useful, which would first involve balancing how many of them people get. If this is a pure points thing then only the diamond:phazon:bananium thing is relevant.

**Comment by DeityLink** [comment]
@GreatBigFailure There's not that much plasma around the station. I mean there's many sheets but they have very little amount (thinking of those in Chemistry and Xenobio in particular).
Only the one in engineering might be full, but that's still just 50$. I don't think you should get any less for a full stack.

**Comment by GreatBigFailure** [comment]
There's also 30 in the research station maintenance. 
You can get about 2 stacks of it without stealing from chemistry really easily. That's enough to use for R&D for the whole round. This is coming from the perspective of usability not rarity though.

**Comment by aceedex** [comment]
Sheets being able to be sold to centcomm isn't really something to consider imo. The funds go to the cargo account which miners don't have access to

**Comment by GreatBigFailure** [comment]
I don't mean in regard to selling, I mean as a resource. Like I'd hope you wouldn't be shipping diamonds, gold, and silver to central if medical is begging for better surgery tools.

**Comment by DeityLink** [comment]
@aceedex I'm completely overhauling shipping stuff to centcom in my upcoming big PR. The point of it IS to have your department earn money. Higher prices gives ever so more of an incentive for miners to ship their extra materials when a Centcom Request appears for 50 silver.

**Comment by DeityLink** [comment]
@GreatBigFailure For cargo it'll be more a resource sink when other departments have had their deliveries. They're kinda excluded from the competition due to them being needed to ship stuff for other departments.

**Comment by aceedex** [comment]
Ah I see

**Comment by Zth--** [comment]
I think you're basing your balance on the wrong things. It should be based on early/mid/late miner game.

With starting tools, how much money can you get in average in 15 minutes? (15 minutes because it's tied to the paycheck)
What about 15 minutes of diamond drill?
And then what about diamond drill + ripley?
(And what about mining bots?)

Then we can compare those results to other systems or to the mining vendor and see if values make sense or not

**Comment by 9percents** [comment]
what about mythril? will it be only effective for smithing?

**Comment by PrimeDSS13** [comment]
yeah this seems okay but what will we spend it on
bring back the expensive raisins, it's the only way...

**Comment by boy2mantwicethefam** [comment]
chefoids have no rights

**Comment by SonixApache** [comment]
i don't care about any of this but i do want to know if it meshes with @boy2mantwicethefam's material sheet cost thing rework

**Comment by DeityLink** [comment]
@SonixApache The value is dependant on the material's rarity, as in their sheets, not their CC_Per_Sheet (which was an unintuitive feature and that i won't miss personally) So his PR and mine don't really conflict with each other.

**Comment by Chucklemonger** [comment]
I've really never understood why the material values were nerfed in the first place when money's already not all that useful and 90% of it was just a dickwaving contest to get that round-end logo or for the cool mining toys. 

While I'm at it PKAs requiring you to go into a mining area to spawn them has seemed pretty bizarre too

**Pull request merged**
