### PR TITLE
Can now akimbo pistols to fire both at once

### PR DESCRIPTION
**Pull request by MadmanMartian**
max_payne

:cl:
* rscadd: Pistols now have an instruction guide on how to fire both at the same time. Simply slap one against the other, then start firing until one goes click.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Would it be better to fire them both at once, or fire them alternately at half the normal firing delay?

**Comment by MadmanMartian** [comment]
They do both fire at once

**Comment by Shadowmech88** [comment]
I know, I'm asking whether people think it would be better to instead fire twice as fast instead.
Personally, I think a doubled fire rate would feel better in combat than firing two projectiles at once.

**Comment by Irradiation** [comment]
I'd normally agree with @Shadowmech88's point, but due to the nature of lag and online fun stuff, a doubled fire rate wouldn't exactly do a difference for somebody who has a mediocre latency.

**Comment by SonixApache** [comment]
could you make one of the guns fire like 0.2 seconds after the other?

**Comment by MadmanMartian** [comment]
It does already, because single thread

**Comment by Dacendeth** [comment]
Dual wielding tasers, new meta incoming.

**Comment by SonixApache** [comment]
nah, dude, load one glock with rubbers and another with lethals

**Pull request merged**
