### PR TITLE
Make machinery subsystem a bit faster

### PR DESCRIPTION
**Pull request by xXxEMBERGHOSTSQUADDIExXx**
## What this does
The machinery subsystem is the most resource intensive contribution to idle CPU usage, using about 1/3 of the total idle load. this makes it use about 10% less CPU, so that means about a 3% reduction in total idle cpu usage.

## Why it's good
less idle CPU usage, more room for other stuff

### CODE REVIEW

**Comment by brndd** [comment]
Getting rid of the redundant if before `M.auto_use_power()` seems objectively faster (by like one cycle). As for the rest...

I must admit that I don't know the first thing about the internals of the Byond interpreter, but I have a very hard time believing this would make for a 10% performance improvement. In any sane language this would at best do nothing and at worst be marginally slower due to cache misses and losing out on potential compiler optimizations. Did you actually profile this in a controlled environment (so vault generation disabled etc.) and see a performance increase?

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
its mainly because global variables are always "ready at hand" and are supposedly as fast to access as local variables, but by using a global variable we save ourselves the step of allocating a new variable for every machine every tick
i didn't disable the vaults but i did test multiple times and though there was some variation, it seems to use consistently less CPU. i think there is also some transient variation relating to cell usage and other factors but seems to work.

since it's so variable ill do more extended time sampling

**Comment by Exxion** [comment]
In my testing, there is no significant difference. I would lean toward saying *this* is slower, but it's likely just noise.
However, using a global var like this would be considered a deadly sin in many places

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
so im curious, isn't a global variable supposed to be as fast as a local variable? so theoretically it would be faster because it doesn't have to be continually re-declared?

**Comment by Exxion** [comment]
By my understanding, yes, but by an extremely small margin. The global variable solution is less maintainable and more prone to bugs, even if it is marginally faster. Which I'm not entirely sure about, because all of this stuff is on a level so small it's difficult to measure.

**Comment by brndd** [comment]
Answering that goes further into DM implementation details than my brittle sanity can take, but if conventional wisdom holds, the local variable would live on the stack and as such allocating it is basically free. If you want an actual accurate answer, you will probably have to ask on some official Byond channel where the most depraved High Programmers lurk (and even on those you will have to be very careful about who you believe).

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
the machinery thing is like this giant tempting chunk sitting there..
it seems like somehow it shouldn't be using as much as it is. i guess it's just the sheer quantity of machines? its about 2500 but they aren't actually doing all that much but getting the area and going through a few switch and if statements

**Comment by brndd** [comment]
I doubt there's anything that can be done to optimize that unless you figure out some way to cache the area to avoid unnecessary calls to get_area (and even that might not save much perf if get_area happens to be very cheap).

**Pull request closed without merging**
