### PR TITLE
Fixes socket wrenches

### LINKED ISSUE #9038: Gas Mole Duping using Pipe Wrench
(WEB REPORT BY: mxr41 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
>  9c7dc21897493b5d1ba727421f08fab44d82fa95
> 
> General description of the issue
> Moles of gas can be duplicated using a pipe wrench.  Unwrench a pipe in a airtight room, the room will instantly take on the pressure of that pipe, reguardless of how many moles of gas were in the pipe.  This creates more moles of gas, which can be then sucked up using scrubbers to reach insane pressures quickly. 
> 
> What you expected to happen
> Very, very high pressures (obtained up to 10^20 kPa in one test, higher is easily possible.
> 
> What actually happened
> High pressures
> 
> Steps to reproduce if possible
> See above. Use a larger room to produce more gas (volume increases, generated moles of gas will increase)

### PR DESCRIPTION
**Pull request by clusterfack**
This should allow the socket wrench to not let an entire pipelines worth of air to escape
Fixes #9038

### CODE REVIEW

**Comment by FudgePucker** [comment]
So does this mean the socket wrench just doesn't shit out all the air onto the turf?
(Who thought that would be a good idea anyways with how the air system is set up on the station? Oh yea, lets just let you use this fancy wrench on any pipe on the station to DUMP THE ENTIRE CONTENTS OF DISTRO INTO ONE AREA)

**Comment by gbasood** [comment]
Not going to pretend I know a damn thing about atmos code so I'll leave this merge to someone who actually knows what the fuck is going on

**Comment by FudgePucker** [comment]
Wouldn't that mean that this is a catch 22 then?
The only collaborator who understands a damn thing about atmos code is cluster, and he can't merge his own PR, that means this can never be merged.

**Comment by gbasood** [comment]
Most of that was making a new air mix out of the removed air honestly
I'm looking it over and bugging him about the one thing so far I've found that I don't understand

**Comment by ihadtoregisterforthis** [comment]
>and he can't merge his own PR

Little you know

**Comment by gbasood** [comment]
Looks good
Once server re-builds I'll merge

**Comment by PJB3005** [comment]
This completely broke socket wrenches.

**Comment by clusterfack** [comment]
Well if its broken on the live server it would be the fault of the return at the end there, that would need to be removed

**Comment by PJB3005** [comment]
Yes they don't automatically begin unwrenching anymore like they used to.

**Pull request merged**
