### PR TITLE
Pax bans

### PR DESCRIPTION
**Pull request by ghost**
[content][administration][tested]
Forces players to be pacified for the duration of the ban, like under the effects of a pax implant.

### CODE REVIEW

**Comment by adacovsk** [comment]
What about: brain transplant, mindswap, monkeying and unmonkeying, and horrorforming? These all remove implants IIRC. Should somehow link it to the mind/or ckey rather than the implant itself

**Comment by DamianX** [comment]
Since you're not supposed to be able to remove these implants, it would be better to make the proc that checks whether someone is pacified check `paxban_isbanned` and not deal with the implant at all.
You can keep a regular pax implant in them if you really really want to but I wouldn't, and I would definitely not implement any of the special snowflake behavior, especially not in its current form.

**Comment by boy2mantwicethefam** [comment]
Alternatively you can make it so that if a pax implant is not detected in the user it automatically produces a new one.
I don't think implants work on non-humans though, would be better to just move it to the pacifism check like @DamianX said, since IIRC it's broad-spectrum and works on pretty much anything.

**Comment by ghost** [comment]
> Since you're not supposed to be able to remove these implants, it would be better to make the proc that checks whether someone is pacified check `paxban_isbanned` and not deal with the implant at all. You can keep a regular pax implant in them if you really really want to but I wouldn't, and I would definitely not implement any of the special snowflake behavior, especially not in its current form.

Made it this check instead, better idea.

**Comment by Kurfursten** [comment]
For the record, "Voluntary Pax Implant" could be a cool starting character option like disabilities on the list.

**Comment by Optimism333** [comment]
> For the record, "Voluntary Pax Implant" could be a cool starting character option like disabilities on the list.

Yes... YES.

**Comment by Eneocho** [comment]
Literal Jobbie ban. honked.

**Pull request merged**
