### PR TITLE
Investigation Glasses

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Attempt 2 of #33987. Adds a unique version of the Tracking Glasses to the Detective Gear box. This version combines the SecHUD with the tracking capabilities of the eye tracking glasses. Added a unique sprite and worn-sprite.

## Why it's good

Helps increase the detective's investigative abilities.

## Changelog

:cl:
 * rscadd: Investigation Glasses can now be found in the Detective Gear box, allowing detectives to track eye movements.

### CODE REVIEW

**Comment by west3436** [comment]
please no icon conflicts please no icon conflicts please no icon conflicts

**Comment by Eneocho** [comment]
For reference, the closed (due to merge issues) attempt 1 had a 13 likes to 1 like.

**Comment by Eneocho** [comment]
> why are the eye trackers a child of prescription glasses anyway

The glasses have a camera and sensors to track movement with high precision, they can clearly adapt to nearsightedness.

**Comment by Hinaichigo** [comment]
What about as a science item?

**Comment by Eneocho** [comment]
> What about as a science item?

They already are, this just implements it as fancy special glasses for the detective. See #32850.

**Comment by xeroxemnas** [comment]
What's so power creepy about this? Is it because the detective will see if you examine a gun in your backpack or something?

**Comment by Hinaichigo** [comment]
I always downvote sec roundstart creep because they already have a massive  arsenal in their lockers, and the lockers usually outnumber the sec staff as well. Plus the detective having this roundstart seems like it would sort of make the detective's job, to investigate, into less of a player-player communication thing and more of a mechanical thing. If it's in science it seems like it shouldn't also be roundstart.

**Comment by Eneocho** [comment]
I upvote it cause now I have a reason to stuncuff the detective and steal his glasses.

**Comment by pedr69** [comment]
these don't have the secHUDs' ability to set wanted status and view security records
so they aren't strictly powercreep, more like a sidegrade

**Comment by Eneocho** [comment]
It should have all the sechud abilities, that seems like a bug to me.

**Comment by angryturnip** [comment]
You didn't add sprites for Greys >:(

**Pull request merged**
