### PR TITLE
Revert "makes buttbots explode after a certain amount of butting"

### PR DESCRIPTION
**Pull request by sushi-vomit**
:cl:
 * tweak: lets buttbots butt as much as they want without exploding

### CODE REVIEW

**Comment by Theophrastus1** [comment]
you aight jewboy

**Comment by Eneocho** [comment]
The PR that saved /vg/. Speedmerge now.

**Comment by SonixApache** [comment]
#23576

**Comment by jwhitak** [comment]
bad grammar in the CL

**Comment by BomberBro** [comment]
Should be an emag only thing

**Comment by Eneocho** [comment]
> Should be an emag only thing

Let the robotics loner make his butt machines, man. The argument that buttbots can be used for chat spam or cause muh server lag is irrelevant since you can make an assembly loop/break into telecomms and upload a script that does the same in a fraction of the time and effort to make the buttbots in the first place (which require sourcing a large amount of butts and the surgery time to acquire them all), the latter even more easily cause you have the tcomms password available right on the RD office, and no-one will bat an eye if you break in to get that paper.

**Comment by DeityLink** [comment]
I for one do not miss the time when radio comms were spammed into un-usability by butt bots.

**Comment by sushi-vomit** [comment]
Better to have (slightly) more radio spam than to have buttbots nerfed so badly that nobody makes them anymore

**Comment by Theophrastus1** [comment]
buttbots were a grudge code and you motherfuckers know it. For once Eneocho has a point. Tcomms is just as easy to break into and paste a script that just completely GUNKS radio comms far worse than what buttbots do. At least with buttbots you know exactly who to kill, and or he's gonna need a stream of asses to make said bots.

**Comment by Hinaichigo** [comment]
Nice to give people the option to grief and troll IC rather than preventing it outright in the code.

**Comment by sushi-vomit** [comment]
Also want to point out that it takes about one minute to write a script that will mute buttbots on comms, if it gets excessive.
IC issue (:

**Comment by SonixApache** [comment]
> buttbots were a grudge code and you motherfuckers know it. For once Eneocho has a point. Tcomms is just as easy to break into and paste a script that just completely GUNKS radio comms far worse than what buttbots do. At least with buttbots you know exactly who to kill, and or he's gonna need a stream of asses to make said bots.

Yeah, you actually don't. Look at the post I linked. You can't even get fingerprints off destroyed buttbotts.

**Comment by Theophrastus1** [comment]
> > buttbots were a grudge code and you motherfuckers know it. For once Eneocho has a point. Tcomms is just as easy to break into and paste a script that just completely GUNKS radio comms far worse than what buttbots do. At least with buttbots you know exactly who to kill, and or he's gonna need a stream of asses to make said bots.
> 
> Yeah, you actually don't. Look at the post I linked. You can't even get fingerprints off destroyed buttbotts.

But you could get fingerprints off the machine in robotics to make the robotic arm, or the arm itself unless buttbot code is fucky in that it wipes the arm clean when destroyed. Buttbots can only come from one place en masse, and that is robotics. Obviously if you are having an issue with them they are coming from that location entirely. It's feasible to assume you'd ask the roboticist about it then. Muting the bots on tcomms is also an option as was mentioned.

Either way there's no reason to even have buttbots if they fucking explode after one use. It's similar in my mind to banning someone for reading WGW over the intercoms for ERP.

**Comment by Kurfursten** [comment]
Just to be clear because a lot of people in this PR seem to be confused, the password in the RD's office allows you access to the PDA monitor, not to telecoms. You need a telecoms access ID to work the traffic console, and the room is also protected by turrets. In addition, it's generally easy to figure out where to go to fix a telecoms issue as opposed to hiding 20 buttbots behind a falsewall in maintenance. I think the main frustration with something like buttbots is that there is no way to track them down to stop them. All you have to do is put up a fake wall in maint, make a space base, etc. and the crew will never reasonably find them.

If you made buttbots play the fart sound effect every time they speak, you could at least hear them through walls. It wouldn't fix the space base problem but I've never actually seen someone go that far**, unlike hiding them in maint which is almost every time.

**I am not counting hiding on the research outpost as a space base, even though I have seen this

**Comment by Eneocho** [comment]
Well, that leaves tators with emags, spare rushers, mechanics, RDs, CEs, HoPs, Captains and AIs able to do the tcomms route for comms gunk, and you can always just do it more analog and make some assemblies and drop 'em in a baby pod (nobody ever checks) with a handheld radio on mic only.
For what is worth, though, making them do an audible fart on butt-ing is just a plus here, I'm all for it if they do (and no longer explode).

**Comment by sushi-vomit** [comment]
> In addition, it's generally easy to figure out where to go to fix a telecoms issue as opposed to hiding 20 buttbots behind a falsewall in maintenance. 

I added to the wiki a very simple script that will mute Buttbots. You don't need to go find them if they can't speak on Telecomms.
http://ss13.moe/wiki/index.php/NTSL_Scripts#Mute_Buttbot

**Comment by Kurfursten** [comment]
I don't personally like this, but there is a reasonable margin and we can always continue flip flopping back and forth if people hate it again. Basically next time someone makes 4+ of these babies.

**Pull request merged**
