### PR TITLE
Plasmaman cultist armor

### LINKED ISSUE #10107: Plasmaman cult armour sprites
Because getting culted and having them laugh behind your back when you can't say Nar-Sie without hissing is bad enough. Now you can rock around in this armour\* when everyone else is stuck with robes!
owtheedge
download link for icons: http://s000.tinyupload.com/index.php?file_id=80225514181703090988
*icons subject to change, no constructs were harmed in the making of this gear

### PR DESCRIPTION
**Pull request by kol1th**
image

Sprites courtesy of Blithering. I figured someone might as well make these a reality.

Not sure how to have armor() replace the current worn suit+helmet and drop it on the floor. If someone knows, I'll gladly edit this.

Closes #10107

### CODE REVIEW

**Comment by Blithering** [comment]
Might want to add closes https://github.com/d3athrow/vgstation13/issues/10107 in the title. Also woo!

**Comment by kol1th** [comment]
Oh, right. That would make sense, wouldn't it?

**Comment by gbasood** [comment]
Did you fix this to have the new armor pieces equip properly?

**Comment by kol1th** [comment]
@gbasood As the description says, no, I didn't. I have no clue how.

**Comment by gbasood** [comment]
But in the code it looks like you fixed it so the plasman armor gets equipped before the human armor, which fixed hte problem
Meaning this is also CONTENT

**Comment by TheFriggenSawbones** [comment]
god bless

**Comment by kol1th** [comment]
@Blithering hey my man, in order to have this work you'll need to convert the sprites to 64x64.

**Comment by Blithering** [comment]
Well crap.

**Comment by Exxion** [comment]
There's a script somewhere around here to upscale sprites by nearest neighbor
But it's probably easier to just do that with an external program if you only have a few of them to upscale

**Comment by clusterfack** [comment]
@PJB3005 can supply anyone with current sprites a script to upscale them to 64x64

**Comment by Blithering** [comment]
That would be handy, as every issue I currently have open is now dead due to using 32x32. Still going to be a pain to go through every one of them and upscale them all.

**Comment by PJB3005** [comment]
Run the DMI through this: http://84.195.252.227/dmi

**Comment by Blithering** [comment]
http://s000.tinyupload.com/index.php?file_id=18668173341920893229 new huger icons, I also slowed down the fire's animation, it was looking a bit eclectic at the previous speed. Thanks @PJB3005

**Comment by PJB3005** [comment]
But why

**Comment by kol1th** [comment]
fucking dajsdhakjlshfukehkfhaewfjasdf

I needed to update the branch and I fucked it

**Comment by kol1th** [comment]
i think i can fix this anyway

**Comment by jakmak** [comment]
fucking sexy armor. +1

**Pull request merged**
