### PR TITLE
Vampire gamemode requires two vampires

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * tweak: The vampire gamemode requires two vampires to start

### CODE REVIEW

**Comment by Irradiation** [comment]
I was told do comment on this.

**Comment by Accipitermaris** [comment]
I think making vamps work better as a Solo-Antag gamemode is a better way to go, and I think the whole "Thrall" mechanic revolves around this. I also believe that Vampire and Changelings shouldn't become too similar in terms of Round Progression, otherwise one of them becomes redundant in nature. Someone else mentioned giving Vampire some starting blood to play around with, and I think that's a good idea. (It's possible for there to be more than one Vampire on 25+ Pop, but I write this with the context that Vampire rolls on 10-14 Pop like crazy.)

**Comment by Sooose** [comment]
I would have to agree they feel better as a solo antag, I don't think you should force two starting vampires. If #17067 does end up merging two vampires on 10 pop seems like overkill.

**Comment by Ratvar** [comment]
now give vamps objective to fight each other and have thrall-on-thrall brawls

**Comment by iFlashYou** [comment]
How about we make first that thralls see other thralls icon from the same vampire?

**Comment by MadmanMartian** [comment]
stop changing gamemode crap, we're coding the frikkin datums!

**Comment by DamianX** [comment]
it's a 1 character change to be honest

**Comment by StreptoMutans** [comment]
But why two Vampires?
If you have about 8 people on lowpop, do you really want two of them to be Vampires instead of one?

**Comment by Pathid** [comment]
@StreptoMutans Secret Vampire requires 10 people. But yeah, it would make more sense for the two vamp minimum to only kick in at a higher pop.

**Comment by DamianX** [comment]
people are voting for this thing as is, though. Not sure I want to commit anything else to this after people have voted

**Comment by Accipitermaris** [comment]
@Pathid There is a two Vampire minimum at higher pops, it's just that said pop is around 25+ ready. I've seen 4 of those rounds in total. Half of them have been absolute chaos with welderbombs and a singuloose, whereas the other half were standard fare Vampstended. I'm not sure if it's the Highpop or double vamp that does it, but it I suspect "Double Agents Syndrome" may apply to it on Lowpop.
vamplaugh

**Comment by DamianX** [comment]
I changed my mind.

**Pull request closed without merging**
