### PR TITLE
Box Changes (Tradepost, Satellite, misc)

### LINKED ISSUE #10992: Vox raider shuttle doesn't perfectly connect to the vox outpost.

### LINKED ISSUE #11380: (Box) Make Outpost Great Again
This has been brought up by a few other people. Each of the Vox outposts kind of has a gimmick - Meta has all that research equipment, good gear, chemistry, genetics, surgery, virology. Deff has mining, a single chemistry dispenser, and other nice perks (wizard cards, crossbow, drink dispensers). The big plus that Box used to have before @dylanstrategie updated it was that it had a staggering 22 trays, which is more than the main station even has. Now it has a much smaller number.

Since Botany is kind of the outpost's gimmick, it might be nice if the Box outpost started with more trays, some farmbots, maybe bees, and even xenobotany machines. Big bonus if whoever maps it adds trader access to the whole outpost so that minertide and scientisttide don't immediately raid it for jetpacks at roundstart. Especially since we've finally done away with traders having the option for no ID.

### LINKED ISSUE #11847: Vox doors lack trader access
(WEB REPORT BY: fantasticfwoosh REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

c2dd2915cf7e64e8a4fa1e9af209fb93a71cf607 

> General description of the issue
> Nearly all vox trading station doors on boxstation are open access to use by anybody and summarily require manual input to seal to stop intruders (via welding or bolt triggers)
> 
> What you expected to happen
> Doors to be secured with trader access as to maintain boundaries and secure the compound.
> 
> What actually happened
> Scientists and miners entering the compound and summarily helping themselves to the supplies there intended for local vox population because the doors are all access.

Resulting oxgen coming through unintentionally on the doors opening also triggers the localised fire locks in small quantities

> Steps to reproduce if possible
> Play as vox trader and take off your id to walk through the doors, additionally invite miners outside from the opposing doors in the oxygen filled foyer.

### LINKED ISSUE #12047: Goonecode Sat Russian Removal
[Discussion]
#11974 seems to have removed the Russians from the Goonecode satellite, and replaced them with cyber horrors.

However, I can't seem to find any mention whatsoever in the PR that it was going to do that. @CptWad listed #10454 as being "fixed" but didn't seem to actually tell people anywhere what changes were made to the Goonecode satellite, so people never had the opportunity to voice their opinion on the removal of the Russian mobs.

Do you guys like or dislike the removal of Russians from the Goonecode satellite? Should they be re-added?

### LINKED ISSUE #12509: Paramedic EVA locker bug.
(WEB REPORT BY: dil9 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

Revision: 6f35f0ab5242609a7a68b72ca6e8c6a159d206e4 

>General description of the issue

There's an item called "obj" in the paramedic EVA locker in boxstation. I don't think you can pick it up or do anything with it.

>What you expected to happen
The paramedic EVA locker not having an item called "obj" in it.

>What actually happened
The paramedic EVA locker had an item called "obj" in it.

>Steps to reproduce if possible
Open the paramedic EVA locker and right click to see the items in it.

### PR DESCRIPTION
**Pull request by Probe1**
I consider this PR complete and ready for review.

**Fixes**
Fixes Vox Raider ship not lining up with the dock https://github.com/d3athrow/vgstation13/pull/12623#issuecomment-263608774
Removes errant /obj/ from paramedic locker.

**Additions**
Increases trays in Trade Outpost to 22.  Adds xenobot machines and farmbot. https://github.com/d3athrow/vgstation13/pull/12623#issuecomment-263596296
Adds Trader Access requirement to specific Vox Tradepost doors.  The armory and vault areas as well as the external door facing the asteroid will require Vox Trader access.  The rest will have no requirements.  https://github.com/d3athrow/vgstation13/pull/12623#issuecomment-263633106 Compliments restricted doors with Rwalls https://github.com/d3athrow/vgstation13/pull/12623#issuecomment-263641032
Varies the syringes in Box Security Medbay from 3 inaprovaline to 1 charcoal, 1 anti tox, 1 inaprovaline, and throws in a bottle of happy pills (Space drugs + Sugar) for good measure https://github.com/d3athrow/vgstation13/issues/12002
Unifies Paramedic Morgue access

**Removals**
Removes Cyber Horrors from satellite, replaces with Russians https://github.com/d3athrow/vgstation13/pull/12623#issuecomment-263580165

Closes https://github.com/d3athrow/vgstation13/issues/12047
Closes https://github.com/d3athrow/vgstation13/issues/11847
Closes https://github.com/d3athrow/vgstation13/issues/11380
Closes https://github.com/d3athrow/vgstation13/issues/10992
Closes https://github.com/d3athrow/vgstation13/issues/12509

:cl:

 * rscadd: Box Vox Post now has more trays, a farmbot, xenobotany machines, and bees.  High value rooms have been given vox trader access requirements.  
 * tweak: Box brig medical now has anti toxin and charcoal syringes.
 * tweak: Box Paramedics can now enter the morgue from any door.
 * rscdel: Cyber horrors on Goonsat have been replaced with Russians
 * bugfix: Vox Raider ship aligns better with Vox Outpost.

### CODE REVIEW

**Comment by Probe1** [comment]
dreammaker_2016-11-29_09-12-41

**Comment by Probe1** [comment]
Custom vote started by Kavlax.
#11847 Should the Vox Outpost airlocks require Vox Trader access?
Type vote to place your votes.
You have 60 seconds to vote.

Vote Result: Yes with 7 votes
No had 3 votes

**Comment by yclatious** [comment]
Yes on the russians, no on the vox outpost.

Let people enter the place, have em be able to maybe talk to the vox inside the outpost propper a lil, loot if they were dicks, and generally don't restrict it to id. 

Plus, aint it just a passport, not even a real electromagnetic card? How does that even work?

**Comment by Probe1** [comment]
The same way it works for the trade shuttle.  It's an electromagnetic ID card.

**Comment by jakmak3** [comment]
ok for the trader access while it does make sense from a balance standpoint it makes no sense from a lore standpoint since the trader ID's are simply just passports to keep them from being lynched

As for russians i do support removing the cyberhorrors of doom but russians had the problem is being easy as hell to cheese. What if they had spacesuits on them OR what if instead of russians they are replaced with nazis with nazi hardsuits?

**Comment by yclatious** [comment]
May I make a suggestion?

Neo Russian armor wearing melee guys with a classic no armor Russian dude having the revolver. Make the melee guys have the blue beret from the Komrade vendor.

Stylish, makes them harder to kill, problem solved.

**Comment by Probe1** [comment]
If you code up that mob for me then yes, I will add it.

**Comment by Probe1** [comment]
image

Working out the rough shape for the reinvorgation of the Box Outpost  https://github.com/d3athrow/vgstation13/issues/11380

Too many trays right now.

**Comment by yclatious** [comment]
Really mate, do I look like a coder to you?

You can probly just copy paste the Russian mob code, alter it so they wear Neo Russian and the beret easily enough, and most likely with less mistakes than I would. If all else fails, ask the coder discord how, I'm mostly busy with university shit atm.

**Comment by Probe1** [comment]
Yes I could but I'm trying to focus on the existing issues that haven't been responded to and this is a detour.

It's not that I dislike the idea or think you're in the wrong.  It's that I have to manage my time or I won't be able to map the stuff you like too.

@jakmak3 That would result in the station getting a bunch of very high end hardsuits at will.  It's even better loot rather than an even better challenge.

**Comment by yclatious** [comment]
Hey, I gave you a good solution, least in my eyes, one that doesn't seen that hard or take that much time to execute and seems to deal with the issue at hand. I ain't asking for any mapping or even asking for you to do it if you don't want to, but time seems like a bad reasoning not to do what seems to be a perfectly good fix for your issue.

Neo Russian ain't even space proof or ridiculously protective, its perfectly fine for loot and armor wise is enough to make melee be actually dangerous.

**Comment by Probe1** [comment]
You're making a suggestion.  One I'm fine with but not one that was directly raised in an issue that I am seeking to close.  If we pursued that then mid-PR people would start debating whether or not we should have stronger Russians instead of the original agreed upon idea that cyber horrors were a bad fit and the _original_ mobs should return.  

Please note the first PR to address this months ago was closed due to this kind of mid development debate.

**Comment by yclatious** [comment]
Ah, didn't know that detail. Apologies then, didn't mean to remake the past.

**Comment by Probe1** [comment]
I'm all for it but we'll have to tackle one issue at a time.  And right now I want to tackle a bunch of issues!

**Comment by Probe1** [comment]
Old 

image


 New

image

**Comment by Shadowmech88** [comment]
The two trays aligned diagonally in the middle-west of the room look kind of out of place.

**Comment by Probe1** [comment]
Really?  I thought it gave the room a detailed aesthetic
dreamseeker_2016-11-29_10-19-08
.

**Comment by Probe1** [comment]
Oh yeah bees

**Comment by Shadowmech88** [comment]
It's just my opinion, but I think it'd look better if it was a square of four trays.

**Comment by kilozombie** [comment]
I think the interior doors should stay zero-access. After all, with such a huge botany, I'm gonna have to recruit people to help me out!

**Comment by jknpj** [comment]
@kilozombie
That sounds like a job for our native plant men!

**Comment by Probe1** [comment]
> Not a big fan. Maybe on the entrance doors, but once people are inside it should be free reign IMO.

How is this compromise on Trader door Access?

Only the set of doors that lead you into the station require access

**Comment by kilozombie** [comment]
Pretty good compromise! It makes sense that traders would have to let people in, unless they feel like breaking windows.

Also, 2 side things:
1. With the botany extension, the leftmost airlock is still just BARELY too far to the right to avoid the metal girders above, and therefore anything spaced will be caught by it. In some ways, this is a great thing, unless you have a lot of corpses for some reason.
2. That 36-tray botany is complete insanity. Bedlam. The power is nigh-incomprehensible.

**Comment by Probe1** [comment]
The submitted changes are 22 trays + bees, xenobotany, and a farmbot.  The 36 was getting carried away making something I enjoyed.

I will alter the lattice*.

**Comment by Probe1** [comment]
Custom vote started by Diethyl.
**Should the Vox Outpost airlocks require Vox Trader access?**
Type vote to place your votes.
You have 60 seconds to vote.

**Vote Result: No with 8 votes**
	Yes had 6 votes

**Comment by Probe1** [comment]
dreammaker_2016-11-29_10-51-14

**Comment by Probe1** [comment]
I know it's ugly but it's the best I can do.

**Comment by AI-Is-Rogue** [comment]
Won't it suck nitrogen out of the Skipjack and ZAS the raiders with their boots off?

**Comment by kilozombie** [comment]
I enjoy botany a bit too, and the 36 tray, while ridiculous, also looked pretty great, so commendations all around.
Also, the dock ALREADY does that. There's an empty space tile between the skipjack and the airlock, and anyone without their magboots on will take a mean blow to the face.

**Comment by AI-Is-Rogue** [comment]
I know there is a space tile there, but Probe put a catwalk in that spot and I think it should just be replaced with a regular floor to minimize nitrogen leaking and raiders getting thrown about.

**Comment by kilozombie** [comment]
Ah, alright.

**Comment by Probe1** [comment]
@AI-is-rogue get ready to have your socks blown off.  IT'S A CATWALK ON TOP OF NITROGEN PLATING.  

ZAS issue is resolved.  I can lose the catwalk if you don't like it.  I thought it looked better.

**Comment by AI-Is-Rogue** [comment]
I like how it looks, I just didn't notice the plating under it.

**Comment by Probe1** [comment]
Trade access revised.  All other doors do not require access. 


dreammaker_2016-11-29_12-06-15

**Comment by Probe1** [comment]
Oh and I'd like to give paramedics access to the morgue from all doors.  For some reason they only have access from within the paramedics office which is a little bizarre.   If anyone disagrees please say so.

**Comment by Probe1** [comment]
dreamseeker_2016-11-29_12-36-46

**Comment by 9600bauds** [comment]
Press F2 to get a fullsize screenshot when zoomed out

**Comment by Probe1** [comment]
Wheres that save to?

**Comment by 9600bauds** [comment]
%userprofile%/documents/BYOND/screenshots

**Comment by Probe1** [comment]
battle town fourteen 2016-11-29 123755

**Comment by Probe1** [comment]
Seems a little nicer.  Thanks @9600bauds

**Comment by ghost** [comment]
>Back to regular old russians

We need some different variants of russians

Maybe some with mosins, some with obrez, and maybe some bare-chested and bald ones with PK-MGs for extra 'difficulty'

**Comment by Probe1** [comment]
I said it a long time ago and its still relevant.  We need mobs to delete themselves on death.  Players will always git gud and be able to win.  The better we make the mobs, the more outrageous the reward for killing them becomes.

**Comment by Shadowmech88** [comment]
Why not just make the mobs not drop their weapons if it's a problem?
No reason for the entire mob to disappear when it dies.

**Comment by yclatious** [comment]
A death gauntlet with no rewards is a shitty death gauntlet, completely removing all loot is the worst and deleting the guns is a bit of a slap, especially when the revolver is better than the mateba anyways.

All you need is to balance it right. A mateba is fine enough as is.

**Comment by Sprok0** [comment]
I feel the cyber horrors are much better than the russians, at the very least the mobs need to be spaceproof or they're not even vaguely a threat. People would always just cheese them by opening a door/breaking a window while pushing a girder or something to block them.

Also, the mateba is identical to the traitor revolver, I don't know what you're talking about.

**Comment by Probe1** [comment]
The reward was the item they were guarding.  Now the rewards a mateba, a hardsuit, an egun, etc.  

The real reward is just killing the guys.  That really screws up the priority for designers.

**Comment by jknpj** [comment]
The real reward is the space adventure. Maybe make them yell and explode(not like the nuke ops, maybe something fluffy like the roid's locked crates) when they die for muh immulsions if they are going to disappear when dead.

**Comment by yclatious** [comment]
The only reason now the mateba is the real reward is because the dang gooncode is now worthless since by reports of players, its dang useless.

You make it worth getting again, and the problem is solved.

**Comment by Sprok0** [comment]
The goonecode was worthless _because the satellite was so easy to clear_, bringing the russians back just makes it even easier to cheese and devalues it further.

**Comment by Sprok0** [comment]
No, you just need a few sheets of metal to make dislodged girders/computer frames/any movable solid object to block the lasers, move past the two left turrets and disable the APC. The entire thing is a joke if you have even a fraction of a brain.

**Comment by yclatious** [comment]
Then I say someone who is so prepared they do all of that is well deserving of the reward, just as much if not more of someone who brute forced it.

**Comment by Sprok0** [comment]
A stack of metal and a toolbelt aren't what I'd call "so prepared", that's pretty basic stuff that anyone can get at roundstart. There is no challenge or difficulty in getting to the goonecode if you know how to do it, which is what makes it worthless.

**Comment by yclatious** [comment]
You sincerely think half of our captains are smart enough to do it? Cause I have seen HoSs that don't mate, ingenuity is fine, and if you sincerely think the APC dissabling is bad, why not make the area just have a magic SMES in the middle of it, no power cheesing that way.

**Comment by Sprok0** [comment]
Who's talking about captains? An assistant can do it after stealing a suit from EVA/making a ghetto rig

**Comment by yclatious** [comment]
I say captains because of everyone to put a standard of game knowledge, you figure you'd be talking about the guy trusted to run the station proper, not the greyshirt. Even the experienced caps don't do it, even the heads of security don't do it, hell, I'd bet you real dosh not even the native carbon autism lords would do it, but the shitter clothed player does.

I'm going on a tangent though, I still think relocating the power storage to the middle of the shitcode room is probly the best solution to your issue.

**Comment by Durgen** [comment]
once upon a time kurfurst made a pull for an outpost redesign that was well received
https://github.com/d3athrow/vgstation13/pull/11441
his included vox access on all the doors, (which wasn't deemed a problem at the time)
it also got rid of the very long and ugly hallway leading from the docks to the outpost proper

edit: we should have replaced the gooncode item with a pomfcoin months ago when the leak happened

**Comment by Intigracy** [comment]
If you think the way you handled the skipjack is ugly, take a look at the way one of the other maps do it.

It's the airlock moved down one tile.

**Comment by Intigracy** [comment]
actually your own image in your other PR shows how it's done:

d11ccc6a-b565-11e6-81aa-8efb249289ad

**Comment by Probe1** [comment]
Yeah but I view that solution as even worse @Intigracy

**Comment by jknpj** [comment]
Remember to add conveyors and air flaps if you're going to use cycling airlocks, because transporting things through cycling airlocks can be a real pain in the beak

**Comment by Probe1** [comment]
Then people will just use the conveyor to enter 🍆

**Comment by Blithering** [comment]
Can the goonecode be replaced with a pomfcoin to bring back it's value?

**Comment by Probe1** [comment]
That would not bring back its value.

Players ran it into the ground.  We are the monsters.

**Comment by Exxion** [comment]
Ostensibly, the reason it has no value is that the actual Gooncode was leaked

**Comment by Shadowmech88** [comment]
There was an idea to replace it with 2 Bitcoins in reference to the leaker's extortion of one of the Goon coders.

**Comment by Probe1** [comment]
I was referring to the ephemeral nature of the challenge.  After the first month, the sat is figured out and there's nothing particularly noteworthy or special about retrieving it so it's difficult to reward players with a grand wish when they were not challenged to earn it.

Also changing the sat every so often proved untenable since it was suggested and no one was willing to do that at all, let alone regularly.

**Comment by Shadowmech88** [comment]
It'd be less easy to game the sat if our mobs were more intelligent, making them harder to cheese in combat.
I took a whack at trying to refactor mob intelligence into mind datums instead of it all being tied to the mob's `Life()`, but I couldn't muster the drive to get very far.

**Comment by Probe1** [comment]
Thats the long and short of it alright.

Its a big ol pile of stuff to do with few takers.

**Review by PJB3005 — APPROVED** [review]

**Comment by Sprok0** [comment]
While you're touching the satellite, I'd make the double windows on the walkways into a single stronger window on the outside, the windows on the same tile as the floor block mobs and absorb the turret laser shots

**Comment by Kurfursten** [comment]
I think it's crazy to rework the Vox outpost but keep the giraffe hallway and the poisonous trading floor no one uses now that we have ships. On the other hand, you are making things marginally better in the mean time, and someone may come along later and fix the outpost once and for all - so it doesn't hurt to have a better outpost in the interim.

**Comment by Probe1** [comment]
I am a marginal kind of guy.  I like to see things merged instead of in "I'll finish this later" hell like my asteroid station.

I agree that it would be cool to have a new vox station, and I really liked yours, but I'm satisfied with what I've done.  

@Sprok0 I saw your post but I'm really dying to get this merged so I can move on from the changes already made.

**Comment by kilozombie** [comment]
Hurrah

**Pull request merged**
