### PR TITLE
Small Gremlin Update

### LINKED ISSUE #15958: Gremlins continue playing with things they find boring
I believe the original functionality was intended for them to build a list of types they can't manipulate and ignore those in the future. That doesn't seem to be working. One got trapped in the O2 miner tank and kept spamming the play with window message because it never 'lost interest'. Same with another we trapped next to a slot machine.

>The gremlin tries to think of some more ways to screw the window up, but fails miserably.
The gremlin plays around with the window, but finds it rather boring.
The gremlin decides to ignore the window, and starts looking for something more fun.
The gremlin tries to think of some more ways to screw the window up, but fails miserably.
The gremlin tries to think of some more ways to screw the window up, but fails miserably.
The gremlin plays around with the window, but finds it rather boring.

@unid15

### PR DESCRIPTION
**Pull request by unid15**
Fixes #15958

:cl:
* bugfix: Fixed gremlins spamming messages when locked in cages, or when near windows
* rscadd: Gremlins can now use operating tables to perform surgery (operating them in the same way as deepfryers - using nearby items). Given their tendency to run around, the surgery can fail if they aren't restrained.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Did #15958 ever get fixed?

**Comment by unid15** [comment]
This fixes it, forgot to include it

**Comment by Probe1** [comment]
compiling and testing just shows how much you trust your code.  it's a sign of weakness.

**Comment by Dacendeth** [comment]
do they work with limb pieces (flesh/metal/peg) and attempt to reattach if you somehow got to the state they could be applied?

**Comment by unid15** [comment]
They should be able to do that, but it will take a lot of time (or a lot of gremlins) to replace a leg with a robotic one, since the target organ is random every time.

**Pull request merged**
