### PR TITLE
Manual and digital valve bugfixes and code cleanup

### PR DESCRIPTION
**Pull request by brndd**
- Manual valves couldn't be used by borgs when clicked on, but *could* be used by borgs when alt-clicked on. ~~I assumed the intention was for them to be able to use them, so they can now use them by clicking them too. If they're supposed to be borg-proof, I can make it the other way around.~~ I checked the Git history and they were never supposed to be able to do this.
- Borgs could use manual valves from range by alt-clicking. Thankfully this wasn't the case for the AI.
- Both kinds of valves didn't play their on/off animation when alt-clicked.
- Valves didn't get fingerprints when alt-clicked.

:cl:
 * bugfix: valves now play their animation when alt-clicked, borgs can no longer use manual valves by alt-clicking them, valves now get fingerprints when alt-clicked.

### CODE REVIEW

**Comment by PJB3005** [comment]
> I assumed the intention was for them to be able to use them, so they can now use them by clicking them too. If they're supposed to be borg-proof, I can make it the other way around.

I assumed the intention was for them not to be able to use it but whoever coded the alt click behavior didn't account for it.
I'm fine with either way too though.

**Comment by Kammerjunk** [comment]
almost definitely as PJB said

**Comment by iFlashYou** [comment]
why even have manual valves when borgs can now use them?

**Comment by brndd** [comment]
The AI can't use them. I'll make them unusable by borgs if that's how they're supposed to be.

**Comment by Lunstra** [comment]
Possibly make an exception for crabs given they: a) have an actual hand instead of grippers b)have an inbuilt RPD and can replace them with something they can use in like 4 seconds flat anyway and c) are probably the only people on station who might remember those air tanks in maint hooked to distro exist but they have a manual valve between them and the pipes which would otherwise force them to use option b to give distro a little kick if it's low and there's atmos issues to fix. Saving 4 seconds of time is hardly MoMMIcreep given option b exists anyway and outside of those 5 or so mapped in valves no bugger uses them anyway.

**Comment by brndd** [comment]
I *think* MoMMIs already use attack_hand but I'll need to check.

**Comment by Lunstra** [comment]
I know they can't currently use them as far as I remember since there's been plenty of times I've tried to use those valves and had to just remove them and replace em with a pipe to get the gas to move.

**Comment by SonixApache** [comment]
borgs not being able to use them even when adjacent is silly as fuck tbh

**Comment by brndd** [comment]
Alright let's do an impromptu vote

updoot this if you think borgs should be able to use manual valves and downtoot this if you think they shouldn't

**Comment by Kammerjunk** [comment]
don't think it's a reasonable suggestion that that part is a bugfix, at any rate

**Comment by brndd** [comment]
Alright I went through the 90 seconds of trouble it took to check the Git history and it turns out borgs were never supposed to be able to use them, so I'm removing that. Keep voting though if it turns out to be a popular request to let them use these I can make a separate PR for that later.

**Comment by Kitfox88** [comment]
love to engiborg and have idiots scream that i'm rogue while i try to tell them they need to go into sec maint and turn the valve since i have no hands in order to re pressurize their shithole

**Comment by FudgePucker** [comment]
Yeah if you really were rogue they would be on fire :^)

On topic though, what about passive gates?

**Comment by brndd** [comment]
> On topic though, what about passive gates?

I touch them in another PR, #22879, turning them into one-way check valves rather than the gimped gas pumps that they currently are. Their behaviour doesn't change all that much, but the UI is simplified (ie. doesn't exist anymore) and they no longer have an upper pressure bound.

**Pull request merged**
