### PR TITLE
Boxes Station/Box 2

### PR DESCRIPTION
**Pull request by deadharold**
The long-awaited sequel to Box Station.
<box>
:cl:
 * rscadd: Adds Boxes Station

### CODE REVIEW

**Comment by SkowronX** [comment]
picture?

**Comment by Irradiation** [comment]
Where we're going, we don't need pictures to see.

**Comment by Kharkov72** [comment]
boboxx bababyby

**Comment by Kurfursten** [comment]
If box is so good, why isn't there a box 2??

**Comment by DamianX** [comment]
Hilarious. Is the CE's stuff supposed to be in the public hallway?

**Comment by deadharold** [comment]
> Hilarious. Is the CE's stuff supposed to be in the public hallway?

Yes.

**Comment by tuypo1** [comment]
Ok I have seen the picture you have my updoot now
Curious how this works with the cargo shuttles though

**Comment by drawsstuff** [comment]
I'm ready for this hell

**Comment by PrimeDSS13** [comment]
>making the PR a day before april 1st

wtf bro everyone is spoiled now

**Comment by deadharold** [comment]
> wtf bro everyone is spoiled now

There's no spoiler because there's no secret.  This map is my response to Lamprey.  It's my opportunity to show everyone that I have what it takes to be a real mapper, not just a meme mapper.  But I appreciate the concern

**Comment by kilozombie** [comment]
I don't know what "me" you're talking about. I'm the one who did all of this. I did Box 2 singlehandedly while you leeched off my glowing success. You're a real scumbag, DeadHarold, you're a real ponce. Do you know how many months I spent on this work? Can't wait for you to try to scam me out of the pomfcoins.

**Pull request merged**
