### PR TITLE
triples rng chance of tableclimbing

### PR DESCRIPTION
**Pull request by Intigracy**
:cl:
 * tweak: Tripled the RNG chance of climbing a table.

### CODE REVIEW

**Comment by Aurx** [comment]
This is a good change.

**Comment by PJB3005** [comment]
Wow I thought we already had this. With the previous code I'm wondering why we even bothered having it in the first place. Now it's 🎉 though.

**Comment by DamianX** [comment]
merge this

**Comment by small-boss** [comment]
the pr that saved the server

**Comment by ghost** [comment]
Is this really necessary? With this tripled chance you can reliably, for example, climb over the table in perma and back. Or just trespass into the kitchen without a lot of damage on average. Basically no downside, I've been doing it a lot so I should know. without oxigen blob dont ouvulate?

**Review by PJB3005 — APPROVED** [review]

**Comment by PJB3005** [comment]
I mean can anybody really argue against this?

**Comment by Cyadox** [comment]
Should have quadrupled it, greytiding is what keeps this this server alive

**Pull request merged**
