### PR TITLE
Significantly reduce the price of chairs

### PR DESCRIPTION
**Pull request by ghost**
Chairs currently cost a fucking ton of sheets to produce, and I do mean a TON. This struck me very quickly when I had the foolish idea of trying to make a wooden table surrounded by chairs. The table parts were fine, but the wooden chairs blew through my wood planks stack quicker than an Assistant through the AI Core walls
- All metal chairs, including comfy and office are now worth 1 metal sheet, both on construction and deconstruction, down from 5/2/1 (office, comfy, normal)
- Wooden chair is now worth 1 plank, down from 3
- Couches are now 2 metal sheets, down from 3
- All deconstruction costs have been updated properly

Changelog included

### CODE REVIEW

**Comment by ScrambledSteak** [comment]
RIP librarians getting 40 metal every round from their office chairs

**Comment by ultraplen** [comment]
Reduce the couches down to 1 or 2 aswell. Makes no sense to have them way out of line with the rest of the chairs. And no smoothing since I couldnt pull it off tbh for something that has directions, such as couches.

**Comment by ghost** [comment]
I'll reduce the couches to two then, although it makes sense for them to cost one more than all chairs since there's a lot more structure in there

**Comment by clusterfack** [comment]
These numbers should SERIOUSLY be defines, and someone should 100000% do that so people don't accidentally make duping every single time someone changes one of these values.

**Pull request merged**
