### PR TITLE
xeno disarms now take into account the targets armor

### PR DESCRIPTION
**Pull request by MadmanMartian**
Literally just more layers of RNG that the affected can deck up in their favour.

No longer is the HoS as bad off as a lowly greyshirt when it comes to being in a fist fight with a xenomorph.

:cl:
* tweak: Xenomorph disarms now take into account the targets armor.

### CODE REVIEW

**Comment by SonixApache** [comment]
xenos are *supposed* to be strong

**Comment by Pathid** [comment]
Maybe for the knockdown part, but why would armor keep them from dropping what's in their hand?

**Comment by Sooose** [comment]
I don't see why the HoS should be better off than a greyshirt in a fist fight with an xeno.

**Comment by MadmanMartian** [comment]
There is a distinct difference between a greyshirt and a greyshit

A greyshirt will likely be an entirely new person, or somebody playing assistant to relax and get away from having to do a job and would be unlikely to go out of their way to prepare themselves for the coming storm.

A greyshit will do everything they can to survive, including looting the Head of securities things, or punching goliaths in the face for their plates to reinforce a mining hardsuit

**Comment by Pathid** [comment]
Now that I'm thinking about this it would be more "realistic" to have all knockdown effects have a magboots check to do an RNG roll. Dunno about balance though.

**Comment by SonixApache** [comment]
knockdown + magboots should rip off feet

**Comment by Fruktlimpa** [comment]
What are the percentages now after this change?

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/49dda632bad4598400a051d77b12e1014fe3000e/code/modules/mob/living/living_defense.dm#L13-L36

Is this being applied correctly here? Doesn't seem like it. Returning zero means a sure hit.

**Comment by MadmanMartian** [comment]
You've got a good point there. Ill change it when I can

**Comment by Killette2** [comment]
How ridiculous would this make riot gear vs xenos?
Or reinforced mining hardsuits

**Comment by MadmanMartian** [comment]
not that ridiculous, from testing.

Test cases were a clown, a miner rig, a syndicate soldier (has the same armor as a sec officer) and a syndicate commando.

Clown was down to clown town all the time, as they would keep rolling 0s

Miner was rolling 1s about 40% of the time, 2s 20% of the time, and 0s the rest.

Syndicate Soldier was about the same as the miner

Syndicate commando was rolling 1s about 60% of the time, 2s 30% of the time, with a rare 0

**Comment by Killette2** [comment]
Doesn't riot gear have the most melee out of anything though? A syndie commando hardsuit would be more well rounded but I thought riot gear was a specialty armor

**Comment by Accipitermaris** [comment]
I've been thinking about this change after having an opportunity to play more xeno rounds and I think if we want to go this route, what you'll want to do with this change is give Hunters access to Neurotoxin Spit for hardsuit takedowns, otherwise I think everyone will just go sentinal so they don't have to deal with dicerolls when trying to shovespam someone long enough to strip their stuff and get a hugger on 'em.

**Comment by Pathid** [comment]
@Accipitermaris I was skeptical at first but upon testing against sec hardsuits and the like, it doesn't feel like that much of a difference. Not enough to alter the xeno meta at any rate. That and disarming when they're already downed apparently bypasses armor or something because it seems like the failure rate goes way down. I guess we'll see how it goes.

I should add that this was against dummy targets and doing it against moving and shooting players could have left me with a different impression.

**Comment by ghost** [comment]
Well I feel it's a little sill a little silly that a bigger and stronger xeno will have more trouble pushing someone other just because they have a little armor which doesn't make a lot of sense. 

Flare guns, flare throwing, vent/scrubber team, tables, flamethrowers, blast cannons, etc. should be used more though.

**Comment by DeityLink** [comment]
I think all xenos should have 64x64 sprites and the Empress sprite should be the Queen's default sprite. Like the ones they're using on the Colonial Marines server. This way people would be more ok with Xenos being OP.

Currently our Xenos look kinda like humans in costumes.

**Comment by Blithering** [comment]
I don't think hunters need neurotoxin spit added, they have the camouflage ability that makes it easier to approach undetected so for a decent number of encounters the first disarm is free. And that's discounting the times you can just mash a hugger in their face for an instant knockout

**Comment by Killette2** [comment]
If you don't see a camo'd hunter you're playing too drunk, high, or horny.

**Pull request merged**
