### PR TITLE
Disable travis-ci caching BYOND so builds stop failing

### PR DESCRIPTION
**Pull request by gbasood**

### CODE REVIEW

**Comment by gbasood** [comment]
I disabled caching and it did nothing
I tried to check if DreamMaker existed before building, and now it builds all the time because it isn't cached
IT STILL CANT FIND DREAMMAKER WHEN IT TRIES TO RUN IT IN DM.SH

**Comment by ihadtoregisterforthis** [comment]
Selfmerges void any kind of begging for regaining trust should the merge break something or everything, and lower the esteem towards the collaborator in public.

**Comment by 9600bauds** [comment]
I think this was kind of an emergency fix though

**Comment by PsiOmegaDelta** [comment]
Clearing the Travis cache has corrected the issue for Bay.
As a collaborator go to (and login at): https://travis-ci.org/d3athrow/vgstation13/builds/105333051
Settings > Caches > Delete all repository caches (or those you feel to be relevant)

**Comment by clusterfack** [comment]
I have done so, thanks POD

**Pull request merged**
