### PR TITLE
Delays roundstart blob

### PR DESCRIPTION
**Pull request by MadmanMartian**
Current delay is 5 minutes, can be upped if needs be.

:cl:
 * tweak: Roundstart blob is delayed by 5 minutes

### CODE REVIEW

**Comment by Irradiation** [comment]
GOB DLESS

**Comment by Kurfursten** [comment]
I do not believe any new rulesets should use delayed until it's fixed, considering it is extremely broken right now.

I'm also not sure what the aim of this is exactly. This isn't the way to go about it if you wanted to give the blob player more setup time before popping.

**Comment by SonixApache** [comment]
Is a random delay possible?

**Comment by ShiftyRail** [comment]
Do note that the blob player will still know that they're about to burst only one minute before the fact.

**Pull request closed without merging**
