### PR TITLE
Instruments can now be played (and note-recorded) with keyboard input on focused windows

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
adds a method for playing instruments live with a keyboard, while the input is focused in the window for it. can also record inputs to lines, but this is probably a janky feature only good for sketching out ideas to edit later.
help screen for it:
image

## Why it's good
live playing is now possible, albeit in an awkward yet familiar manner for anyone who's done this in a DAW like FL studio or reaper, also a debatably less awkward way to input songs.

## Changelog
:cl:
 * rscadd: Instruments now accept user keyboard input in their windows while focused for live playing, alongside a mode for recording lines to play back later.

### CODE REVIEW

**Comment by BurntDevil** [comment]
neato

**Comment by gurfan** [comment]
Does this replace the current instrument system.
Also show screenshots.

**Comment by SECBATON-GRIFFON** [comment]
> Does this replace the current instrument system. Also show screenshots.

not at all, also there's nothing to screenshot since it's an input system that doesn't change the UI

**Comment by gurfan** [comment]
I'm not sure how this works, then. When the instrument window is open users can press those keys to play different notes? How are they supposed to know which keys play which notes? On goon a little piano pops up showing which keys correspond to which notes. Why not have something like this? Either you're shit at writing descriptive PRs or this whole thing is very unintuitive.

Post a video of you playing a simple song too. I'd like to hear how this sounds in game.

**Comment by angryturnip** [comment]
Midi controller inputs next?

**Comment by SECBATON-GRIFFON** [comment]
> Midi controller inputs next?

if i knew how to even do that with javascript, sure

**Comment by SECBATON-GRIFFON** [comment]
> I'm not sure how this works, then. When the instrument window is open users can press those keys to play different notes? How are they supposed to know which keys play which notes? On goon a little piano pops up showing which keys correspond to which notes.

added instructions now with that

**Comment by Eneocho** [comment]
Interaction with midi keyboards when

**Comment by SECBATON-GRIFFON** [comment]
> Interaction with midi keyboards when

i also don't know if js even supports it, or if any other server does

**Comment by BurntDevil** [comment]
Does not seem to actually work. Couldnt get a menu to pop up with the instrument at all.

**Comment by Kurfursten** [comment]
piano works, handheld instruments dont

**Comment by ConfusedCactus** [comment]
> piano works, handheld instruments dont

can you revert this pr until it's fixed, not being able to play handheld instruments at all sucks ass

**Comment by Exxion** [comment]
Yeah sure

**Pull request merged**
