### PR TITLE
Crtl-clicking clothing with accessories now removes it

### PR DESCRIPTION
**Pull request by ghost**
Very complex change, took me 4 weeks with a full development team to figure this one out but I managed. 4 pomfcoins please, thank you.

:cl:
 * rscadd: Crtl-clicking clothing with accessories will remove a random accessory.

### CODE REVIEW

**Comment by DamianX** [comment]
That's great, I always wanted to remove accessories as a ghost!

**Comment by ghost** [comment]
It's a feature

**Comment by ShiftyRail** [comment]
Shouldn't be random, should be the accessory you can't access by normal clicking (ie if you have a holster + holobadge, the holobadge) and then the first of those 4 holobadges you put

**Comment by SonixApache** [comment]
\>Random accessory

Oh nononono nono. Either grab the top one or make it a list prompt. I'd heavily prefer a list prompt.
Or what Shifty said. Or a list prompt.

**Comment by ghost** [comment]
I'll do list prompt.

**Comment by ghost** [comment]
Actually, I'll do what shifty said. The point of this was to make accessories easier to take off, fuck menus.

**Comment by Kurfursten** [comment]
don't forget to do that

**Comment by SonixApache** [comment]
fix it

**Pull request closed without merging**
