### PR TITLE
EMP now randomizes suit sensors.

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
A fatal error occurred in Suit_Sensor.exe. Please restart.
:cl:
 * tweak: EMP now randomizes suit sensors.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Just set them off when you strip them

**Comment by boy2mantwicethefam** [comment]
What? No it just lacked an EMP action, I don't think I actually ever purchased the EMP flashlight if that's where you're getting at except once or twice at least a month ago

**Comment by bathosbathtime** [comment]
I thought this was already in the game.  Unless the suits are EMP resistant or EMP creep is getting out of hand, I don't see why this wouldn't be a good thing.

**Comment by SonixApache** [comment]
make it random
literally just `pick(0,1,2,3)`

On othercode™ serbs, ion storms also mess with suit sensors. If you set this up right, we could just make that event call `emp_act()` on uniforms or something.

**Comment by iFlashYou** [comment]
Ion storms should even mess with the sps :^)

**Pull request merged**
