### PR TITLE
Shuttle Seats

### PR DESCRIPTION
**Pull request by DeityLink**
image
image image
shuttle2
image

:cl:
* rscadd: Adds shuttle seats. Basically reinforced chairs with visible belt when buckling in. You upgrade a chair into a seat with 5 plasteel, or downgrade them back with a welding tool.
* rscadd: Shuttle seats added to most shuttles and pods in the game. For balance reasons, most seats in the escape shuttle are still regular chairs (this might or not be changed at a later date).

### CODE REVIEW

**Comment by ShiftyRail** [comment]
They kinda feel out of place. Although the fault is mostly on the old chairs rather than on the new design.
They look pretty good.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
What's the balance behind being able to get some plasteel 5 minutes before the round ends (but you can still get plasteel from the escape pods??)

And the ultrawide ones facing up at the top of the shuttle look so bad

**Comment by DeityLink** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE someone suggested we keep the "gamer" ones in as "captain" chairs. Those fat chairs aren't craftable. But they can rotate.

**Comment by ShiftyRail** [comment]
@DeityLink 
>be traitor
>hijack shuttle
>hide almost completly in the gamer chair
>valids denied

They completely hide your sprite when facing up. A too convenient camouflage tool.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Right
The gamer chairs look terrible, especially facing up

**Comment by DeityLink** [comment]
@ShiftyRail your feet are clearly visible though. But fine, I'll replace them with the regular blue ones.

I'd argue that the game is already full of hiding spots though, closets are much more reliable in that regard.

**Comment by Exxion** [comment]
Hm
The perspective is still a bit weird in that the "camera" is not only angled down, but also slightly towards the back of the chair
It makes the sideways-facing ones look like they're rotated towards the camera a bit
This is especially noticeable with the head part

**Comment by DeityLink** [comment]
@Exxion In that regard I tried to remain faithful to the perspective on regular chairs:
image

**Comment by Exxion** [comment]
I always just figured the backs of the regular chairs were somewhat thick
Notice how you can't see the north-facing legs

**Comment by DeityLink** [comment]
Yeah but how do you explain the diagonal stripes on the chair that look horizontal when viewed from the south?

Anyway, I pushed some box fixes (forgot a seat in space by the research shuttle, and replaced the gamer chairs in the shuttle)

**Comment by Exxion** [comment]
Yeah, upon closer inspection I can see that the old ones just suck
I still think the back side of the headrest looks weird, though
Maybe just shave off one pixel?

**Comment by Intigracy** [comment]
while you argue about the dumb chair

white
change file extension to dmi obviously

**Comment by DeityLink** [comment]
Added @Intigracy 's white seat along with an extra:

image

**Comment by Dacendeth** [comment]
the visible buckle might look weird when you buckle something like a mommi/borg/mouse/etc into it.

**Comment by DeityLink** [comment]
borg (default)
image

borg (bloodhound)
image

borg (surgeon)
image

It looks bad on some mobs with different proportions, namely due to borgs and mommi having a wide selection of available sprites, or Ian whose ass is visible, mouses cannot be buckled due to being too small however. But they look just as bad when buckled on a regular chair or sofa. There's no fixing that.

Not to mention only humans (and maybe some other carbon mobs) fall down when the shuttle moves so robots and simple animals shouldn't need to buckle in.

**Comment by DeityLink** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE oh and regarding plasteel, this was a request from Killette I think, that most shuttle seats remain normal so that antags can grief by wrenching them down without having to weld them first.

If you're prepared though, you'll have 5 plasteel in your pocket and will upgrade your own seat. Also having some seats "better" than others may lead to narratively interesting developments that I cannot wait to observe in game.

**Comment by SonixApache** [comment]
not being able to spin the chairs is a major detriment
half the pod chairs can't be deconstructed
chairspinning is magic and not being able to do it with these sucks
i need to melt my eyes to turn the shuttle brig into a fortress
its lame that you can't spin them
free plasteel without fucking up walls is kind of stupid
the lack of spinning is saddening
they look kinda meh

i'd say they're suited for 'captain's chair in a shuttle' or 'awaymissionorbus' and that's it

**Pull request merged**
