### PR TITLE
Adds the Super Shotgun

### PR DESCRIPTION
**Pull request by MadmanMartian**
Was playing through the blood moon, felt something was missing while going doomguy on unlimited skeletons.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
>BIN -716 Bytes (99%) icons/obj/gun.dmi

🤔

**Comment by MadmanMartian** [comment]
🤷‍♂️

**Comment by Exxion** [comment]
Nothing's missing
I guess compression?

**Comment by Shadowmech88** [comment]
Do you think you should add a `sleep(1)` or something between the parent calls so that the two separate shots are perceptible? I imagine it'll just sound like one, possibly louder than normal shot otherwise.

**Comment by MadmanMartian** [comment]
I was going for it firing both barrels at the same time

**Comment by jknpj** [comment]
I'm going to use it later on

**Pull request merged**
