### PR TITLE
Adds a new wizard spell: Punch

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Ever thought "Man, I want to punch people very hard and this Fist spell just doesn't cut it"? Ever wanted to just punch someone so hard that there was a badass explosion? Well this is it.
(It has sound)

[Opofw9XaYp.webm](https://user-images.githubusercontent.com/41342767/187591754-610653d5-8c63-4020-b8b8-1a4762cf8a02.webm)

### Features
The Punch spell is a new addition to the wizard's spellbook, with an initial cooldown of 9 seconds, a minimum cooldown of 3 seconds after 2 quickening upgrades and an empowerment, the wizard has to get close and personal, right in the danger zone, to deliver a meteoric punch that deals 5x the unarmed damage to the target and launches them across the screen in a rather dramatic fashion, causing an explosion wherever they land. The most severe impact of the explosion will happen at the point of landing and won't affect the target themselves, barring certain rare circumstances. The empowerment will increase the range of the explosion and add a little bit of oomph to the epicenter. The wizard also needs hands and to not be incapacitated or in cuffs, obviously.

The wizard is IMMUNE to the initial explosion, meaning that they have a chance to slam someone into a wall like this without immediately breaking a few of their own bones, but this does not make them immune to the consequences of an explosion such as shrapnel, depressurization, the ire of the crew and more.

If the wizard were to fight a Hulk, a Mecha or someone who just super-glued their ass on a chair, the resulting punch won't launch them far away, but will instead be empowered more than normal, causing a larger explosion right there on the spot.

Also buffed the Fist spell a little by making it take less spell upgrades to reach the minimum cooldown.

### Behind-the-scene changes
- Changed event-invoking for to_bump from carbon level to living level
- Added a new variable to the attack animation that replaces the attack icon with any other icon of your choice
- Elaborated description of to_bump to be from atom/target to atom/bumped
- Fixed throw_impact event invoking, it now properly records hit_atom and speed
- Added an explosion whitelist system, anything in the whitelist won't have ex_act applied to it

:cl:
 * rscadd: Added a new wizard spell: Punch.
 * rscadd: The Fist spell now requires less quickening upgrades to reach the minimum cooldown.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
Toasting in epic bread

**Comment by BomberBro** [comment]
How much brute damage total does this do to the average schlub in grey if he gets hit into a wall?

Also add that Fist edit part in the changelog

**Comment by boy2mantwicethefam** [comment]
To the average schlub in grey that would be ex_act(3) + the randomized unarmed melee damage value multiplied by 5 which is roughly in the 30-60 damage range.

**Comment by ExpulsionSnooper** [comment]
Can I use this for #33005 ? I was thinking about doing something like this if a multiplier of above 4 or so is hit, but if you've already/are made/making it...

**Comment by Eneocho** [comment]
So basically a magical nuclear powered fist?

**Comment by adacovsk** [comment]
does it work with arcane golem and doppelganger?

**Comment by pedr69** [comment]
does being on kick intent while casting make this much stronger? since kicks have higher basedamage than punches

**Comment by Eneocho** [comment]
> does being on kick intent while casting make this much stronger? since kicks have higher basedamage than punches

Requesting for the casting spell to be FARUKONKICKU instead of FARUKONPANCHI when kick-punching.

**Comment by boy2mantwicethefam** [comment]
@Eneocho You can finally go "BANZAI" and smash people, yes.
@adacovsk Will test.
@pedr69 @Eneocho  No, technically it's not a pure unarmed attack. Kicking sounds cool but making the PR work drained me because when I am actually dedicated to a PR I try to cover up any hole that props up, and it had a fair amount of them that were tedious to patch. If I actually make a super-kick spell it would have to be a roundhouse kick.

**Comment by calzilla1** [comment]
With all these martial spells, there should be some wrassle robes to go along like some star spangled shorts.

**Comment by luigil101** [comment]
would this stack with the items that boost punch damage?

**Comment by Theophrastus1** [comment]
Mister Lister the Sister Fister makes his return

**Comment by boy2mantwicethefam** [comment]
@adacovsk You can launch them, yes.
@luigil101 Yes.

**Pull request merged**
