### PR TITLE
Adds Mothman hologram for AI, fixes corgi hologram

### PR DESCRIPTION
**Pull request by SonixApache**
tested
corgi sprite was already coded in, but somehow the sprite went missing
frontback
rightleft

🆑 
 - imageadd: Added a mothman AI hologram
 - bugfix: The corgi AI hologram now actually works

### CODE REVIEW

**Comment by Kurfursten** [comment]
New spritework needs picture

**Comment by SonixApache** [comment]
good point

**Comment by ihadtoregisterforthis** [comment]
I don't get it

**Comment by N3X15** [comment]
It's from a game I guess, pairs with a core sprite.

If the corgi sprite is new, we need pics.

**Comment by Knightkiller11** [comment]
http://megamitensei.wikia.com/wiki/Mothman

It's from Shin Megami Tensei, though I'm not sure why it was added. Maybe a meme I missed.

**Comment by mtpowell** [comment]
Puck from Dota

**Comment by SonixApache** [comment]
it wasn't my idea, someone asked me to do it

**Comment by ghost** [comment]
I guess you get it merged by pairing it with a bugfix

**Comment by SonixApache** [comment]
a mothman core icon was added in the last change, might as well

**Pull request merged**
