### PR TITLE
uncomments sovietvend/nazivend/boda recharge packs from cargo console (requires emag anyway)

### PR DESCRIPTION
**Pull request by SirSkeleto**
downvote my pr
:cl:
 * rscadd: The nazi. soviet, and boda vending packs are now available from the cargo console again.

### CODE REVIEW

**Comment by bungofungo** [comment]
thanks

**Comment by SirSkeleto** [comment]
> thanks

yw

**Comment by SonixApache** [comment]
fix title
fix description
add 🆑 
fix commit names
delet this

**Comment by ShiftyRail** [comment]
I wish there was a :thinking: react

**Comment by Zth--** [comment]
we can do it the old way

**Comment by Zth--** [comment]
:thinking:

**Comment by SkowronX** [comment]
🤔

**Comment by SonixApache** [comment]
fix title to reflect all changes
fix description to reflect all changes
fix 🆑
fix commit names  to reflect all changes
delet this

**Comment by SirSkeleto** [comment]
> fix title to reflect all changes
> fix description to reflect all changes
> fix 
> fix commit names to reflect all changes
> delet this

no

**Comment by bathosbathtime** [comment]
> Nazi/Communist gimmicks back
> 
Oh god oh fukc

**Comment by Kurfursten** [comment]
Reminder, more importantly, that these contain GUNS

**Comment by ghost** [comment]
Cargo had problems getting guns without emags?

**Comment by SonixApache** [comment]
I think the free hardsuits are worse than the free guns tbh.
Laser AKs are already in the soviet surplus guns crate in the first place.
Big stinker is the plasma gun, but even then.

**Comment by ShiftyRail** [comment]
Nazis/commies gimmicks bring the lowest of the low in any player, encourage uncreative memesters and are generally in awful taste.
I don't believe it should be available in a normal round.

**Comment by Kitfox88** [comment]
next we'll have the super ebin le captain donald trump back to build a wall to keep the vox out

**Comment by Hoshi-chan** [comment]
> Nazis/commies gimmicks bring the lowest of the low in any player, encourage uncreative memesters and are generally in awful taste.
> I don't believe it should be available in a normal round.

The same could be said of a lot of shit. This is going to be popular the week it gets merged, then you'll see it maybe once a month. Quit being the dang fun police.

**Pull request merged**
