### PR TITLE
mirrors are still magic, aint gotta explain shit

### LINKED ISSUE #3282: Mirrors ruin muh immersion
right now you can be bald and magically grow a pink afro by using a magic mirror in bathroom 

i dont really think its that well known but if possible itd be cool to have a barbers razor in maint to cut hair kinda like goone

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #3282

### CODE REVIEW

**Comment by Imagebard** [comment]
Yet it still can't change hair colors.

**Comment by Shadowmech88** [comment]
Hair dyes when?

**Comment by clusterfack** [comment]
Barber job when

**Comment by Intigracy** [comment]
maybe someday

**Comment by icantthinkofanameritenow** [comment]
@Intigracy 
Oh, just steal the job from Goonstation, they don't want it anyway.

**Comment by Imagebard** [comment]
>2 days

So this is the pain of being a 1-line PR.

**Pull request merged**
