### PR TITLE
Adds the ability to delete viruses from the database

### PR DESCRIPTION
**Pull request by MadmanMartian**
Requested via a PM in the discord

:cl:
 * rscadd: Can now delete viruses from the database.

### CODE REVIEW

**Comment by DeityLink** [comment]
Huh, care to explain your reasoning? That's pretty huge for tator virologists.

t. currently-a-virologist-main

ps: On one hand, I can understand the utility of it, since when you perform virus mutations, the virus database is gonna get clogged with duplicate viruses with the exact same name, but I had an idea to deal with that. My opinion is that only traitors using an emag should be able to remove entries from the list, since it allows you to release unidentified viruses and pretend it wasn't you. Could the guy from discord come give his opinion here?

**Comment by ghost** [comment]
I requested that feature because viruses show up on medhuds making them instantly obvious if they're in the database.

**Comment by ghost** [comment]
How does this make it harder to cure?

To my knowledge, curing goes blood sample -> monkey -> radium pill -> antibodies. How does a database help here?

**Comment by MadmanMartian** [comment]
It would make them 'harder to cure' by the fact you can't instantly recognise that somebody's infected from a glance via the med HUD

**Comment by DeityLink** [comment]
@Kyunny Well yeah, that's the point, and that's a huge buff to traitor virologists like I said. But oh well 🤷‍♂️

**Comment by ghost** [comment]
Well, making a good virus takes up to half your shift depending on how badly symptom rng decides to screw you over, meanwhile curing it takes about 2 minutes if you have chem dispenser near you.

**Pull request merged**
