### PR TITLE
Braindamage causes "troubles with breathing" - Adds a brain damage line.

### PR DESCRIPTION
**Pull request by Eneocho**
Let us not forget our history, spacemen.
:cl:
 * rscadd: Adds a brain damage line.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
wasted quints

**Comment by PrimeDSS13** [comment]
so dumb
1 year rule barely even kicks in, this is like a few months fresh

**Comment by boy2mantwicethefam** [comment]
Quints have decided this must be merged.

**Comment by djkramer123** [comment]
unfunny

**Comment by gurfan** [comment]
one year rule

**Comment by pedr69** [comment]
checked

**Comment by jwhitak** [comment]
Conflicts

**Comment by calzilla1** [comment]
Merge

**Comment by tinysaturn** [comment]
>same people who downvoted this PR upvoted the flarg brain damage text

really makes you go hmmm 🤔

**Comment by ghost** [comment]
why

**Comment by WindowsErrors** [comment]
we live in a society run by kids from the drama class

**Comment by githubuser4141** [comment]
I don't think it's funny to have IRL quotes as BD lines, why would you laugh at someone who'as going through an awful experience? And you're expecting other people to laugh, too? like, the other lines are harmless media jokes, I genuinely got a laugh out of the 'Traitor who kills but I respawn' line, this isn't even consistent flavour wise?
Why, just why?
 downboated

**Comment by Eneocho** [comment]
>I don't think it's funny to have IRL quotes as BD lines, why would you laugh at someone who'as going through an awful experience? And you're expecting other people to laugh, too? like, the other lines are harmless media jokes, I genuinely got a laugh out of the 'Traitor who kills but I respawn' line, this isn't even consistent flavour wise?

This was inspired by Sterlok/Uncle Murdoch's incessant "I CAN'T BREET" spam whenever he got tased/stunned/bolas'd/etc. I know about the real event with George Floyd, but that's not what this PR is referencing.

**Comment by ghost** [comment]
> > I don't think it's funny to have IRL quotes as BD lines, why would you laugh at someone who'as going through an awful experience? And you're expecting other people to laugh, too? like, the other lines are harmless media jokes, I genuinely got a laugh out of the 'Traitor who kills but I respawn' line, this isn't even consistent flavour wise?
> 
> This was inspired by Sterlok/Uncle Murdoch's incessant "I CAN'T BREET" spam whenever he got tased/stunned/bolas'd/etc. I know about the real event with George Floyd, but that's not what this PR is referencing.

if you can't tell that it's an indirect reference I'm not sure what to say, but considering our repo is under scrutiny as is I'd rather not push our luck

**Comment by Eneocho** [comment]
I can tell, it's an obvious link, but inside jokes are inside jokes for a reason, they require insider context. This makes fun of Murdoch's retardation.

**Comment by Optimism333** [comment]
Not going to wax poetic about principles behind brain damage lines, but I don't find this one that funny.

I didn't hate Uncle Murdoch, but I never found his constant "I can't BREET" to be hilarious. Mildly amusing the first couple times, at best.

**Comment by githubuser4141** [comment]
> I can tell, it's an obvious link, but inside jokes are inside jokes for a reason, they require insider context. This makes fun of Murdoch's retardation.

Most people wouldn't know or care about 'muh secret club' lore and would see it as insensitive. If it's about making fun of permabanned users, it should be their original content similar to the others on the list (Singulo, Traitors respawn, Monkeys, etc.) those quotes directly reference the other player's silliness, and this is obvious even without inside context (It's all silly stuff kids say on video games). 'I can't breet' to most people sounds like it's directly mocking Floyd, not 'another player that mocked Floyd but we're mocking that player lmao'

**Comment by Eneocho** [comment]
Alright, fair. Would it be better if I also added "ON GOD" or something, to further reinforce the Murdoch theme?

**Comment by cloutcode** [comment]
close the PR instead

**Comment by Kurfursten** [comment]
I won't merge this. You can always appeal to Pomf to overrule me, but frankly he wasn't funny enough to immortalize like this.

This isn't making fun of Murdoch the player - he was using the Ruckus character to act poorly, intentionally wanting people to insult him. He holds up a straw man to be attacked because he wants to see this stereotype attacked. And now the one being puppeted is you - he's got his hand in your ass making you immortalize one of the most uncreative character ideas in all of Space history. You are not making fun of Murdoch, you are making fun of Ruckus, which is a parody of Floyd.

**Pull request closed without merging**
