### PR TITLE
Swap staff

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds the staff of swip-swap.

Fire the staff, and whomever the projectile collides with, you will swap places with them!

Two-hand it so that you can fire through windows!

Moves the staff of change to its own subtype, so you dont get the change state window when you attack_hand your staff.

Guns now do a supercall on attack_hand, rather than just 'oh ye we try to lower aim, shame about all that other functionality we are ignoring!'

NEEDS SPRITES

:cl:
* rscadd: Adds the swap staff for wizards. Shoot it at a mob, and you switch places. Wield it to be able to shoot it through windows.

### CODE REVIEW

**Comment by Killette2** [comment]
Only if you can add the ability to transform it on use item to staff of swap. When you shoot it at someone you swap what's in your hands (they get the staff even if you drop it or put it away), and you get their item.

**Comment by MadmanMartian** [comment]
That sounds brilliant, I will add that as the default effect

**Comment by MadmanMartian** [comment]
On second thoughts let's not

**Comment by Killette2** [comment]
Is it more difficult than it sounds to code? I was suggesting it to have both abilities on a toggle

**Comment by MadmanMartian** [comment]
It is certainly possible, but I feel it could be more bullshit on top of bullshit, considering this is already something that can be considered annoying

**Comment by Killette2** [comment]
Almost all the staves are bullshit, and arguably more so.
Staff of change will fuck anyones day
Staff of necromancy can either make you an asshole zombie that needs to be smacked with a bible, or is more likely butchered. Or it can make you a skeleton with no way possible to recover.
Staff of mental focus is the only reasonable one, but enjoy being hit with a shotgun that self recharges and knocks you back
Staff of animation makes a mob army, even more efficiently if you grab a bunch of rods and spam grilles

**Comment by Inorien** [comment]
I want to sprite this but I won't have time until tomorrow

Was going to use this for inspiration https://www.youtube.com/watch?v=B4Te2Lo56kc

**Comment by MadmanMartian** [comment]
Sprites courtesy of Blithering

**Comment by MadmanMartian** [comment]
I donut understand, the icondiff bot is lying about the removal of the phylactery sprites

**Comment by Exxion** [comment]
That's weird. It correctly does not display them as removed on the details page, though

**Pull request merged**
