### PR TITLE
Cleans up monkeyization and stuff

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
There should no longer be a period of time in which someone disappears into the void only to reappear as a human or monkey
Added arbitrary duration checks that SHOULD be as long as the animation lasts

:cl:
 * bugfix: Monkeyized and humanized people should no longer disappear for an invisible delay after the animation ends, and will be able to act as soon as the animation ends.

### CODE REVIEW

**Comment by DamianX** [comment]
```
code/modules/mob/transform_procs.dm, line 378, column 8:
warning: macro undefined while not defined: MONKEY_ANIM_TIME
```

**Comment by SonixApache** [comment]
did u test it

**Comment by Kurfursten** [comment]
Test this

**Comment by ShiftyRail** [comment]
Well ?

**Comment by DamianX** [comment]
Shout for it to be re-opened once it's tested.

**Pull request closed without merging**
