### PR TITLE
Makes Borer chat messages colored.

### PR DESCRIPTION
**Pull request by slightly-floating**
[](url)[qol]

The borer now speaks in purple. This allows the host to more easily see the messages the borer has sent. 

https://files.catbox.moe/ggaqrl.png

### CODE REVIEW

**Comment by ghost** [comment]
this is already used by cults, go with some other colour

**Comment by boy2mantwicethefam** [comment]
To embed an image type it like this
!
[random image name, can be anything here]
(insert image link here)
Combine all that in one line, no spaces

**Comment by BomberBro** [comment]
Maybe a dark green might work better if it needs to be differentiated from cult

**Comment by help-maint** [comment]
Have you tested this in darkmode? Dark purple looks really bad against a black background

**Comment by slightly-floating** [comment]
> Have you tested this in darkmode? Dark purple looks really bad against a black background

Have not tested in dark mode. Am going to have to change the color anyway. What would a good color be?

**Comment by help-maint** [comment]
I think most uses of dark purple just turn into light purple in darkmode. There's a different .css for darkmode so you can just define it twice

**Comment by PrimeDSS13** [comment]
make it slimey borer colored

**Comment by FlintBarrel** [comment]
now do this for telepathy

**Comment by Eneocho** [comment]
Does this also affect the borer to borer comms?

**Pull request merged**
