### PR TITLE
changes northern box maintenance

### PR DESCRIPTION
**Pull request by gurfan**
I tried to give box (bawks) some chemotherapy and slim the maintenance down a little, but I mostly ended up just reshuffling some things.

OLD:

northwestmaintold

NEW:

northwestmaint

OLD:

northeastmaintold

NEW:

northeastmaint

also readded the monkey cultrobes to the monkey maint cubby

[box]

:cl:
 * tweak: Box northern maintenance has been tweaked and slimmed down slightly.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
pretty good changes, I especially like the connection of the small sec maint which I always though was kind of odd to the northeastern section.

might wanna put a rack with some fireman stuff to counteract the loss of the two rooms
image

bring back the brass knuckles though, that was rad and allowed for some fun gimmicks

**Comment by DamianX** [comment]
The new tunnel connecting brig maint to the holodeck could use an airlock or two, otherwise a breach near the windows just outside  the chapel will depressurize all the way to brig maint.

**Comment by gurfan** [comment]
- added a door in the corridor above ghetto theatre
- added a rack of firefighting supplies below the lockers in the picture prime posted
- added brass knuckles to the trash cart right of tool storage
- moved carp spawns closer to compensate for the smaller maint
- added a few grilles and lattices right above the ghetto morgue, removed the ones that were stuck out there in the photo

**Comment by ghost** [comment]
The main problem i see with this change is that it has no roundstart walled off maint rooms in the north-east side of the station. These are generally required by cultists and vampires on high pop. Maybe consider adding one near the chapel.

**Comment by dunsel-hordon** [comment]
YOU DELETED THE SPIKED KNUCKLES aaaah REVERT!

**Comment by gurfan** [comment]
@dunsel-hordon 
the brass knuckles are in the trash cart next to tool storage, there were never any spiked knuckles on box

**Pull request merged**
