### PR TITLE
Kitchen Coliseum Vault

### PR DESCRIPTION
**Pull request by Kurfursten**
untitled

Notable loot:
* Taxi pod
* Pretty much everything that could possibly be used in a recipe, including snow, robot heads, an Asimov board, radium, fake mustache, etc.
* The "Iron Chef gauntlets" - they just look like powerfists. They're insulated glubbs.
* Two meat cleavers
* Destination disk

### CODE REVIEW

**Comment by chesse20** [comment]
░░░░░░░░░░░░▄▄                     
░░░░░░░░░░░█░░█                  
░░░░░░░░░░░█░░█                  
░░░░░░░░░░█░░░█                  
░░░░░░░░░█░░░░█                  
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░ /vg/,░░░░░░░█ 
 ▓▓▓▓▓▓█░░░░Add This░░░░█  
▓▓▓▓▓▓█░░░░Please!░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█   
██████▀░░░░▀▀██████▀

**Comment by FudgePucker** [comment]
WHOSE QUIZINE WILL REIGN SUPREME?

**Comment by gbasood** [comment]
cuisine ya fuck

**Comment by FudgePucker** [comment]
Shit I am a dumb ass

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
