### PR TITLE
Stoplag Update 2

### PR DESCRIPTION
**Pull request by adacovsk**
Based on my previous PR but without the licensing issues #32914

## What this does
- Replaces a `round` with `ceiling` in stoplag
- Switches some `sleep(world.tick_lag)` to `stoplag()`
- moved stoplag to `tick.dm` along with some tick-related defines
- adds a parameter to stoplag so that code that has a parameter for stoplag actually gets used... This is likely stuff ported from tg in times of yore

## Why it's good
- organization
- less invasive and copypasta than my other PR but should still have some benefit

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Meant nothing at all
Meant nothing at all, it meant nothing 🎵 

This works and will likely not break anything but you really want to focus more on the actual things causing lags rather than microoptimising stuff like that

**Comment by adacovsk** [comment]
> This works and will likely not break anything but you really want to focus more on the actual things causing lags rather than microoptimising stuff like that

can you detail to me how to focus on actual things causing lags so I can avoid dealing with stupid minor optimizations?

**Comment by ShiftyRail** [comment]
The profiler/hard del list are good places to start. I can give you fullmin on the test serb to help you look at stuff there if you want.

**Comment by adacovsk** [comment]
already am but it's not so obvious to me

**Comment by adacovsk** [comment]
and the test server is way out of date

**Pull request merged**
