### PR TITLE
Crumbs adjustments also THE SPOON UPDATE, I guess?

### LINKED ISSUE #30500: Soups leave crumbs when eating
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
3cd2eb209be77ae7b7d8c434cf98a629f6a3e45d

# Description
FUCKING CRUMBS HOW THE FUCK DOES LIQUID MAKE CRUMBS
# Steps to Reproduce
eat soup
make magical crumbs
# What you Expected
fucking anything but soup crumbs
# What Actually Happened
MY IMMULSIONS, ANNIHILATED

### LINKED ISSUE #30738: [Feature Request] Crumbs should only appear if people eat on harm intent.
Contrary to popular belief, most people can eat a donut or apple without mashing it into their face and getting half of it on the floor.

Pic related, least dirty floor at the kitchen counter.
crumbs1

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #30500
Fixes #30738

I planned to do those for a while.

image

imageimage
_After this pic I raised a bit the offset of the food overlay on forks_

* Crumbs now have a chance to spawn depending on the food type eaten. The default chance has been reduced from 35% to 10%. Burgers have 20% chance, while Chips and Donuts have 30% chance. Furthermore, the chance is increased if you eat the food at very high speed (less than a second between bites). The chance is also increased if you are on harm intent. Lastly, the chance is drastically reduced if you are eating food on a plate.
* If there are already 4 crumbs on the floor when a new one is created, the oldest one is deleted.
*  Unlike other cleanable gunk, crumbs now only persist for the next round, instead of the next 3 rounds.
* Added explicit filling color to a lot of snacks so their crumbs and custom sandwhich fillings are more accurately colored. Some foods can now also have several filling colors, randomized when created and when crumbs are spawned (currently only Clown Tears use those).
* When using a fork on a food item that's on a plate, the plate no longer appears on the fork's food overlay.
* Spoons can now be used just like forks to properly eat some food items (as long as they aren't bent). Most soups can only be eaten using a spoon, but some dishes can be eaten with either a spoon or a fork (such as Flans or Stews). If there's some dish doesn't support either when you feel it should, please make a bug report so we can tweak that. (Optimism)
* Added spoons and small knives to the Dinnerware. As with forks, you can now find 10 of each.
* Small knives (which were pretty rare to see at all in the game until now) have had their damage reduced from 10 to 5 and no longer have the SHARP_TIP flag.

:cl:
* tweak: Crumb-spawn chance is now overall lower, and dependent on food type, plates and intent.
* bugfix: Plates no longer appear on fork overlays.
* imageadd: Soups and most liquid snacks produce dribbles instead of crumbs. (eneocho)
* rscadd: Spoons are the new fork-equivalent for liquid foods (some foods accept either). Spoons and small knives now available at Dinnervend.
* balance: Small knives have had damage halved and lost SHARP_TIP.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you please add an exception to eating soups (both the use-food-in-bowl and the soup recipes)? How can you even make crumbs when drinking soup.

**Comment by DeityLink** [comment]
> 
> 
> Can you please add an exception to eating soups (both the use-food-in-bowl and the soup recipes)? How can you even make crumbs when drinking soup.

Those should spawn liquid splatters instead of crumbs. I'll add an alternate sprite.

**Comment by Eneocho** [comment]
>Those should spawn liquid splatters instead of crumbs. I'll add an alternate sprite.

How can you even drink soup so violently as to leave noticeable splatters on the floor...
I guess I'll take this as a small victory, still annoys me though.

**Comment by jwhitak** [comment]
This is still probably way too high of a rate. Cargo pizza, alone, leaves massive messes right now to the point where a quartering of the crumbs is still going to be pretty bad. The crumbs might not be too bad for a chef who has access to plates or forks and puts all their food on it, but poor cargo...

And right now the crumbs don't really add much to the game. They just punish the chef for not using plates and force them to clean messes/be a janitor. Especially round start, where the crumbs from last rounds persist. You can walk into a nasty crummy kitchen most rounds right now because nobody cleans.

Recommended alternatives: ditch crumbs entirely or only certain foods leave crumbs (mostly snacks).

**Comment by DeityLink** [comment]
@jwhitak Chefs spawn with a soap. As a chef player I love cleaning my workplace at the start of a round. Regardless believe me that 10% is almost negligible compared to before. Most snacks are eaten in 2-3 bites and won't leave any crumbs at all (also cargo can buy soaps from the merch computer and surely they don't lack the money for it)

**Comment by Eneocho** [comment]
You might love cleaning the area, but most chef players want to cook and RP, not clean the damned place every 5 minutes (which by the way would require you to go all the way around the kitchen to clean the crew-side crumbs, which wastes a lot of time if you're using soap).

And as for the cargo soap, those go out after 20 cleanings, and at current rates, a single pizza more than makes 20 cleaningsworth of crumbs. I doubt reducing it to 10% chance will be of much difference.

I'm with Jwhitak on this one, crumbs, while cool, don't add much to the game (can they even be vacuumed for nutriment?) while being very obnoxious. The two options are to throttle it to a 5% or less (10% is still too big of a chance) or to limit it to some common "crumb" making foods (how do you even make crumbs while eating steak?) like sometimes spilling some frosting that crumbles off a frosted donut.

**Comment by SonixApache** [comment]
:cl: is kinda big, average player's eyes might gloss over halfway through
:+1: otherwise

large amounts of crumbs on a single tile should do something, like causing rats or bugs or crumbmatter cascades

**Comment by jwhitak** [comment]
Despite my comments I actually see no reason to discourage this PR since it is a step in the correct direction. I just wish it went further. Some additional thoughts:

Chefs may start with soap (hidden in a crate in their backroom) but that will not stop the crumb black holes, especially in areas outside of their departments. This is a common sight for escape shuttles where food is brought aboard. This was a pizza and a half worth of slices.
image

The vending machine areas are starting to look equally as rough, especially on rounds unlucky enough to not have a janitor.

Our chef has to physically leave the kitchen to scrub the ground _constantly_ right now. One person ate a pancake on a plate, now I have to stop what I'm doing to clean up the piles of crumbs that were left behind from a plated(!) food or let the dining area look hideous. This gets real old real fast, and disrupts the workflow. And don't even think about suggesting that a chef can force people to use forks...
Average roundstart kitchen:
image

I want to like the idea of crumbs but this is ultimately just generating unsightly messes in an area that crewmen already have problems trusting to be safe and sanitary.

**Comment by BomberBro** [comment]
The chance should be 30% on harm intent and 0% for most other foods besides chips and easily crumby things. Then you can still eat like an animal or laugh as some dummy sticks on harm intent and absolutely manhandles a pizza, but it doesn't cause the crumb armageddon to happen

**Comment by DeityLink** [comment]
I'm adding a limit of 4 crumbs per tile following which the oldest ones are removed to prevent crumb black holes. I would argue that it's the janitor's role to clean the side of the counter in the hallway but last time I saw a janitor they were busy *roleplaying* washing already clean floors with water.

**Comment by DeityLink** [comment]
I'm also reducing the persistence of crumbs so they cannot persist for 4 rounds, they now only persist for the next round.

**Comment by DeityLink** [comment]
> I want to like the idea of crumbs but this is ultimately just generating unsightly messes in an area that crewmen already have problems trusting to be safe and sanitary.

@jwhitak I argue that soap and space cleaner should also be more easily obtainable, as far as I know there are no ways to craft additional space cleaner bottles. A long time ago I suggested that every department should have a tiny custodial closet since you really can't expect the Janitor to knock at Science's door to go clean inside.

As a Virologist I usually take it upon myself to clean all the blood and vomit in medbay.

**Comment by Killette2** [comment]
For soups would dribbles be preferable to splatters? Could have a few splatters in too of course but dribbles similar to drops of blood may seem less silly, and cause people to misinterpret it as blood possibly too for unique scenarios

**Comment by DeityLink** [comment]
> 
> 
> For soups would dribbles be preferable to splatters? Could have a few splatters in too of course but dribbles similar to drops of blood may seem less silly, and cause people to misinterpret it as blood possibly too for unique scenarios

I haven't made the change yet, guess I'll sprite some now

**Comment by Optimism333** [comment]
Please don't make soup leave dribbles unless there will also be a way to avoid said dribbles, such as by using a spoon.

**Comment by DeityLink** [comment]
> 
> 
> Please don't make soup leave dribbles unless there will also be a way to avoid said dribbles, such as by using a spoon.

Now that you mention it are spoons still non-functional?

**Comment by Optimism333** [comment]
> > Please don't make soup leave dribbles unless there will also be a way to avoid said dribbles, such as by using a spoon.
> 
> Now that you mention it are spoons still non-functional?

I'm not sure, actually. I do know that they're still in the contraband section of the dining vendor for some reason.

Edit: Yep, spoons do not work on soups. Very sad.

**Comment by jwhitak** [comment]
~~Small knife weapon damage tweak is inappropriate for the PR.~~ Then again, you're messing with the other utensils already... That's a hard nerf for a rare item that I liked to have in my pocket...

**Comment by DeityLink** [comment]
> 
> That's a hard nerf for a rare item that I liked to have in my pocket...

I think it should still be decent at causing bleeding, it still has the sharp edge flag. Now that it'll become more readily available we'll be able to get more feedback. In my mind though those were always meant to be one of those
image

**Comment by Blithering** [comment]
I always pictured more of a steak knife, sharp but not a big kitchen knife like the other one.

**Comment by Kurfursten** [comment]
I have undeitied your changelog

**Comment by DeityLink** [comment]
@Kurfursten You'll find out that "balance" isn't a proper changelog flag, use "tweak" instead next time.

**Pull request merged**
