### PR TITLE
Sleeper Plug-in System

### PR DESCRIPTION
**Pull request by jwhitak**
# Sleeper Plug-in System

## What this does
Adds in unique items, obtainable in various ss13 ways, that can be installed into a sleeper to grant additional features and chemicals.

An example would be:

Discount Dan's Discount Sustenance Injectors
* Adds Discount Sauce and Grape Juice to the chemical list.
* Adds Beff and Refried Beans to upgraded lists.
* Adds Cheesy Gloop on an emagged sleeper.
* Maybe even add Discount Dan themed voice lines on injection (on a cooldown of course).

To-do
- [x] Add the core system that accepts plug-in objects and handles them
- [x] Bugtesting/Mechanicproofing
- [ ] Add various plug-ins:
- [x] NT Basic from Cargo
- [ ] Overlay+Plugin Sprite
- [x] NT Advanced from Research
- [ ] Overlay+Plugin Sprite
- [x] Discount Dan themed one, available from Cargo
- [ ] Overlay+Plugin Sprite
- [ ] Ancient Civilization one, available from xenoarch
- [ ] Overlay+Plugin Sprite
- [x] Funny Clown from Deep Frying
- [ ] Overlay+Plugin Sprite
- [x] Gunked from Splashing with Toxic Waste
- [ ] Overlay+Plugin Sprite
- [x] Open to suggestions for more ideas
- [x] Sleeper Screwdriver Panel

PLEASE leave suggestions or warnings. This is very rough draft so cool ideas? Now's the time.

## Why it's good
More funny medical upgrades, available from different places! Guido can get his daily injections of sprinkles and gravy with the right connections.

Buffs anything with a sleeper who also uses crew interaction/vault diving/whatever. Medical power creep, but more interesting power creep.

## Changelog

:cl:
 * rscadd: Adds a plug-in system to sleepers which enhance their abilities.

[WIP]

### CODE REVIEW

**Comment by Eneocho** [comment]
Requesting a GUNK mode plugin that injects various toxic or nasty chemicals, like vomit, saltwater (so YOU vomit), chemical waste, cockroach shells, spiders (if emagged), etc.
And a HONK mode that injects honk serum on you.

**Comment by Eneocho** [comment]
A few ideas:

* Gunk mode plugin that injects various toxic or nasty chemicals, like vomit, saltwater (so YOU vomit), chemical waste, cockroach shells, spiders (if emagged), etc. Acquired by inserting some nasty ass stuff on the thing (like live cockroaches, trash, burned messes, etc).
* Honk mode that injects honk serum on you. Acquired by inserting bananium/a very large amount of bluespace bananas/high potency bananas.
* Silent mode that injects Silencer on you. Acquired by inserting the brain of a mime/the mime's mask and beret.
* Quick Blood mode that instantly injects all the blood you need to get to 100%. Acquired by inserting cult paraphernalia/a monkeyman every 800u.
* Locutogen mode. You pre-set a word with the machine. On injection it doses the user with 1u locutogen set with your specified phrase. Acquired by installing a locutogen beaker and speaker assembly.
* RAGE MODE. Gives you 14u PCP. Emag only.
* Holy Water mode. Acquired by using a priest rod/bible/holy implant on the sleeper.
* Cancer mode. Gives you 1u Danbacco. Acquired by using a dan's supply pack on an emagged sleeper.

If nothing else, please consider the honk, gunk and locutogen ones.

**Comment by jwhitak** [comment]
Currently considering limiting it to one plugin per sleeper, but allowing more powerful effects in exchange. Such as injecting critical/dead patients. Maybe having multiple isn't too bad? You do have to get them after all.

Making the plug-ins after the core system is in would be relatively simple. I'd be doing it as a type, so you can just fill in the lists. Admins could even bus a custom one with how I'm planning it.

**Comment by jwhitak** [comment]
Intent is that these are pieces of sophisticated (lol) technology. Putting a clown mask in a sleeper would do nothing directly. Gotta get the special high tech goods somehow. But I'm not against like... A HONK upgrade, for example, could be made by installing the clown mask into the Trader plugin.

**Comment by Eneocho** [comment]
Maybe plugins could have a "cost". Roundstart sleepers start with 1 capacity, which can be increased by upgrading the Scanning module (one per sleeper, can be upgraded to tier 4). A tier 3 sleeper would have 3 capacity. 
You can fill this capacity with either 3 low cost plugins (honk, silencer and locutogen), 1 medium cost and 1 low cost plugin (Holy water and Honk) or one high cost plugin (Quick blood). This'd let you gate more powerful plug-ins with higher cost instead of being hard to get. It would also encourage more proactive upgrading of medbay machinery, which is always a plus.

**Comment by jwhitak** [comment]
Part of the one upgrade idea is that each would have a unique sleeper sprite. Overlays are a thing though ...

**Comment by tinysaturn** [comment]
How about medical nanobots for the Ancient Aliens™ xenoarch module?

**Comment by jwhitak** [comment]
Current plan. Please, please, PLEASE make suggestions and review this list. The core functionality of the plugin system is just about done, minus bugtesting and mechanicproofing. These all need cool names and other such details. Plugins can stack, except for certain ones which take over the entire machine (see: alien tech).
```
SLEEPER PLUGINS
	NT Basic
		Obtainable by Cargo
		Side effect/meme chems that might make docs feel good
		T1
			Mannitol
			Piccolyn
			Sprinkes
		Very slight overlay, likely just a tiny box on the side.
	NT Advanced
		Obtainable by NT Experimental Tech Disk and high bio research
		T3
			Botany Chems?
		Highly technical overlay, add more NT tech-looking devices
	Trader
		Obtainable by Traders
		Uncopyable by Mechanics
		T1
			Nitrogen (Injectable on Crit, Inaprov for Vox basically)
			Gravy
		T3
			Maple Syrup
		Emag
			Chillwax
		Weird greenbrown color overlay
	Discount Dan
		"Discount Dan's Discount Nutrition Injectors"
		Obtainable by Cargo
		T1
			Sauce
			Grape Juice
		T2
			Refried Beans
		T3
			Beff
		Emag
			Cheesy Gloop
		Advertisements, spoken aloud on injection
		Red makes the sleeper print beff faster overlay
	Ancient Civilization
		Obtainable by Xenoarchery
		New Chems:
			Unknown Alpha, Gamma, Omega
			Use randomized_reagents datum for each
		Three other random chems with random names
		T1
			Unknown Alpha
			Random Chem
		T2
			Unknown Gamma
			Random Chem
		T3
			Unknown Omega
			Random Chem
		T4
			???
		Alien functions take over the sleeper, standard chems disabled
		Weird alien esque overlay
	HONK
		Unknown Obtainability
		T1
			Banana Juice
			Honk Serum
		Funny Honk noises on entry/exit
		Funny Colored Overlay
```

**Comment by jwhitak** [comment]
image
mmm... gravy...

**Comment by Eneocho** [comment]
> Current plan. Please, please, PLEASE make suggestions and review this list. The core functionality of the plugin system is just about done, minus bugtesting and mechanicproofing. These all need cool names and other such details. Plugins can stack, except for certain ones which take over the entire machine (see: alien tech).
> 
> ```
> SLEEPER PLUGINS
> 	NT Basic
> 		Obtainable by Cargo
> 		Side effect/meme chems that might make docs feel good
> 		T1
> 			Mannitol
> 			Piccolyn
> 			Sprinkes
> 		Very slight overlay, likely just a tiny box on the side.

Mannitol is literally just discount dan's and doesn't really fit there. Make it Tendies instead (jannie healing chem, for consistency with sprinkles). Could add PCP to the emag function.

> ```
> 	NT Advanced
> 		Obtainable by NT Experimental Tech Disk and high bio research
> 		T3
> 			Botany Chems?
> 		Highly technical overlay, add more NT tech-looking devices

High bio research is part of the standard checklist and most ((scientists)) buy the NT disk at roundstart, consider changing it to NT 2 (acquirable via xenoarch). 
Not sure stepping on botany's shoes with the botany chems is a good idea, but that might be the hundreds of hours of botany autismo talking.

> ```
> 	Trader
> 		Obtainable by Traders
> 		Uncopyable by Mechanics
> 		T1
> 			Nitrogen (Injectable on Crit, Inaprov for Vox basically)
> 			Gravy
> 		T3
> 			Maple Syrup
> 		Emag
> 			Chillwax
> 		Weird greenbrown color overlay

I really dislike stuff getting the free "uncopyable" treatment just 'cause it comes from traders. Make it only scannable with the hacked scanner instead. Otherwise good ideas here.

> ```
> 	Discount Dan
> 		"Discount Dan's Discount Nutrition Injectors"
> 		Obtainable by Cargo
> 		T1
> 			Sauce
> 			Grape Juice
> 		T2
> 			Refried Beans
> 		T3
> 			Beff
> 		Emag
> 			Cheesy Gloop
> 		Advertisements, spoken aloud on injection
> 		Red makes the sleeper print beff faster overlay

Cheesy Gloop might be a bit strong for an Emag effect considering you only need 5u to get the heart attack symptoms. Then again, you can easily make gloop in like 30 seconds by buying the hardcores and mixing with 'zine. Consider adding all the danchem subtypes to the list. An idea for the Emag chem could be moonrocks, since that causes brute damage while not being too powerful. Another idea could be Danbacco (which causes cancer) but isn't immediately deadly like gloop.

> ```
> 	Ancient Civilization
> 		Obtainable by Xenoarchery
> 		New Chems:
> 			Unknown Alpha, Gamma, Omega
> 			Use randomized_reagents datum for each
> 		Three other random chems with random names
> 		T1
> 			Unknown Alpha
> 			Random Chem
> 		T2
> 			Unknown Gamma
> 			Random Chem
> 		T3
> 			Unknown Omega
> 			Random Chem
> 		T4
> 			???
> 		Alien functions take over the sleeper, standard chems disabled
> 		Weird alien esque overlay

T4 could inject 1u adminordrazine then lock up for 300 seconds, essentially being a hail mary to save 1 guy but you lose total functionality for a good while. Another idea could be for a random Karm drink instead of Unknown Alpha. You can get lucky and get the free money drink or get SPIDERS and accidentally (on purpose) doom medical to skittering hell.

> ```
> 	HONK
> 		Unknown Obtainability
> 		T1
> 			Banana Juice
> 			Honk Serum
> 		Funny Honk noises on entry/exit
> 		Funny Colored Overlay
> ```

Slap some bananium sheets onto the Sleeper to enable HONK mode. Consider either adding "Silencer" and "Nothing" to the module or adding a "..." module for mime chems.

Could you try to make the Locutogen module idea work? I REALLY want to gaslight people when treating them for burns. And a gunk mode you enable by slapping some cockroaches onto the machinery ("You contaminate the chemical synthesizers with the cockroach!"), letting you inject gunk such as vomit, chemical waste, toxic waste, etc.

**Comment by west3436** [comment]
Might be a big ask, but for the Botany module what about keeping it at NT1 but making it so that you can only inject chems that have had their phytochem disk inserted into the sleeper first to "load" the chemical makeup?

**Comment by Eneocho** [comment]
> Might be a big ask, but for the Botany module what about keeping it at NT1 but making it so that you can only inject chems that have had their phytochem disk inserted into the sleeper first to "load" the chemical makeup?

Even then it's a big loss for botany. Just get a couple disks (no splicing required) to insert and now you can print diamonds for free forever, helpful medical splices become pointless, medical gets a literally infinite source of blood, access to giga poisons, etc.

**Comment by jwhitak** [comment]
I'm at work but gonna review the ideas and respond to what I can.

NT basic feedbacks:
This is meant to provide NT/Old Station-feely actual chems. I'd say maybe not emag PCP since it's the newest thing but Hyperzine? Sure. Maybe even true antitox?

Mannitol is here as an oldchem joke for doctors to laugh about. It doesn't actually heal but that's the joke at this point. The Sprinkles honestly only barely fit, but I've got good feedback from it. Thanks for reminding me of Tendies, that might actually work for Discount Dan...

NT Advanced:
When I say high, I mean they will have to go above what the wiki gives them on bio by default. My scaling is assuming the wiki list + plasma is done each round as "normal" research. High being "gotta go out your way to make a kamotrine drink" or other shenanigans. I'll need to check the files on my next day off to see how good of an idea this is, especially because generally 10 needs xenoarch. I'm wanting to avoid NT2 because xenoarch will be getting an alien plugin.

I'm also not against making new chems in this plugin. I'm already doing so for the Allen plugin. Tricord2 or some such, though probably something more interesting than just more healing that stacks. The botany chems are just a shot in the dark suggestion for extra healing that is *very rarely* seen in medbay that would use existing chems. I don't want to make botanists obsolete lmao.

Mednanos could fit but they have a very unique side effect of causing a cyberhorror apocalypse so I'm very hesitant.

Traders:
The Shoal has the best copy protection hands down. That is lorewise why mechanics can't usually copy the stuff. If you want more, you pay the price.

I was originally considering swapping inaprov with nitrogen at first with this mod, but currently it keeps both.

Dan:
Gloop actually was requested by two people separately, that's why I have it here. It's powerful. I might wind up implementing custom sleeper amounts for dangerous chems like Gloop and nanos.

I didn't want to flood the sleeper chem list with various danchems, so I kept the list kind of clean. There's no actual limit on what can be included. I could throw all of those emag suggestions in easily.

Aliens:
Shutting down the sleeper for the big heal choom is a cool effect idea. It won't be the admin chem - there's ways to get chems out of people. But maybe something similar.

I like the random kamo chem idea. It's a pretty powerful list of effects... Generally the random reagent effects are very plain unless you get a high roll, and I'm probably going to make a safer_effects list for Alpha on top of it. So kamo chems would make it funnier.

Other ideas:
The upgrade is stored (mostly) in the plugin. Throwing cockroaches in a sleeper won't upgrade it or make it corrupt. It'd need to be something that makes a new plugin object. Like putting any plugin in a deep fryer. That's one option. Or splashing any of them with Nothing for a mine module. Ideas like that would work. Splashing vomit on a Dan module for a gunk module would work.

Locutogen could fit in NT basic/advanced in an upgraded sleeper. I don't like having a specific module  needed just for the chem but it sounds like something a fully realized sleeper should have - messages for your patients that are just waking up. I gotta figure out where it should go. It would be injectable on crit on its own, like Inaprov.

**Comment by Eneocho** [comment]
> Mednanos could fit but they have a very unique side effect of causing a cyberhorror apocalypse so I'm very hesitant.

Could easily limit it to a 4u dose maximum.

>Gloop actually was requested by two people separately, that's why I have it here. It's powerful. I might wind up implementing custom sleeper amounts for dangerous chems like Gloop and nanos.

I insist, gloop has the particular mechanic that it DOESN'T metabolize, which ensures you die of heart attack-based suffocation in 1 minute, while danbacco gives you cancer, which can be treated with phalanximine (would give a use to it as well, since cancer is so rare ingame). There's a roundstart bag of phalanximine on ghetto surgery as well, so you COULD get away with it even if medical is rogue.

>My scaling is assuming the wiki list + plasma is done each round as "normal" research. High being "gotta go out your way to make a kamotrine drink" or other shenanigans.
>I'm wanting to avoid NT2 because xenoarch will be getting an alien plugin.

NT2 is only available via the Scientist Sapience karm drink (3rd stage to the scientist drink), and you can only up to Bio 6 with it, which you can already get to with the checklist.

>It won't be the admin chem - there's ways to get chems out of people. But maybe something similar.

That's why I suggested only 1u of the stuff, it is virtually impossible to get the 1u out before it metabolizes completely.

>Locutogen could fit in NT basic/advanced in an upgraded sleeper. I don't like having a specific module needed just for the chem but it sounds like something a fully realized sleeper should have - messages for your patients that are just waking up. I gotta figure out where it should go. 

I'd say either baseline sleeper at higher tiers or NT Basic would fit for Locutogen. You'd have to implement a method to pre-set the locutogen phrase however (a simple pop up screen would do).

>The upgrade is stored (mostly) in the plugin. Throwing cockroaches in a sleeper won't upgrade it or make it corrupt. It'd need to be something that makes a new plugin object. Like putting any plugin in a deep fryer. That's one option. Or splashing any of them with Nothing for a mine module. Ideas like that would work. Splashing vomit on a Dan module for a gunk module would work.

That works, as long as I can get the gunk plugin and inject 1000u vomit into people. Pour some honk serum on a blank circuitboard to turn it into a HONK plugin.

**Comment by jwhitak** [comment]
I'm still thinking deeply over this.

Mednanos are MedNoNos unless research is reworked to allow for a route to Bio7 or some other nutty thing happens. It's more likely that I'd implement a unique chemical that is way less powerful. Mednanos obsolete most other chems alongside surgery. It heals broken bones, internal bleeds, all forms of damage. Too good. What EFFECTS should the advanced sleeper plugin have?

Research, upon inspection, is actually pretty gunked for higher end study. While there are ways to go above and beyond, the checklist knocks out pretty much all of it. Research needs more exotic methods to get higher research levels tbh. And not ones that depend on Xenoarch. You can't get to 7 bio normally for example. There IS currently a route, requiring a Mahoguny, but not even the Karmotrine drink can get to 7 otherwise. And 6 you get from the basic checklist. No middle ground...

Gloop is arguably less dangerous than cancer - you can at least explode the gloop out of them! Both would typically result in cloning being required. And now I'm including neither because I've been convinced that emagging sleepers is for stealthy mechanics, and having a blatant this-was-emagged chem in there is bad. I'll leave the emag chem system in for future PRs but it'll not be used in this one I think.

Do not underestimate medmains, that is all I will say about the 1u admindrug amount not being too strong. 0.01u on the other hand...

NT Basic at T3 parts, or NT Advanced plugin will fit Sleeper Loctuogen. It'll be a derivative of the temp_hearer that doesn't require an open container to learn a phrase. Just inject, and the first thing that is heard will be remembered. (Warning: Do not inject using Discount Dan's injectors without injecting something else first, they will advertise and the patient will hear an ad in their brain when they wake up!)

At this point of the comment I stopped, sprited a screwdriver-panel for sleepers, and coded it to be used. Now to continue.
image

Gunk module funny inject vomit and toxic waste. I'm getting more and more allergic to the idea the more I think about it, but I think splashing any plugin with Toxic Waste will do the chore. Good news is that there's an official GUNKS list of chems: ```#define GUNKS list(CHEMICAL_WASTE, TOXICWASTE, VOMIT, TOXIN, SOLANINE, RADIUM, MUTAGEN, UNTABLE_MUTAGEN, SPIDERS)```

Probably will do this instead: ```	t1chems = list(TOXICWASTE = "Toxic Waste", CHEMICAL_WASTE = "Chemical Waste", BOOGER = "Boogers", VOMIT = "Vomit", BILK = "Bilk", SALTWATER = "Salt Water")```

**Comment by jwhitak** [comment]
Here's the current feature list.

```
SLEEPER PLUGINS
	NT Basic
		Obtainable by Cargo
		Side effect/meme chems that might make docs feel good
		T1
			Mannitol
			Piccolyn
			Sprinkes
		T2
			Dylovene
		T3
			Iron
			Locutogen
				Injectable on Crit, popup when you push the button to set the message
		Very small overlay, likely just a tiny box on the side.
	NT Advanced
		Obtainable by Science - NT 1, Engineering 5, Bio 7 (obtainable only by scanning a MAHOGUNY at Bio 6)
		This has powerful effects and so it's difficult to obtain.
		T1
			Mahkoexpitol (NEW CHEM)
				Purges chems instantly on injection, similar to water+potass/iron+uraniumm, but no explosion/emp. Needs to be injected, so doesn't circumvent BLOCKIZINE.
			Dexalin+
			Biofoam
		T2
			Lifeline
		T3
			Morathial (NEW CHEM)
				Bicard OD effect healing. Heals 0.2 per wound per tick, average 10 per wound per intended dose. Heals internal bleeds, brutes, and burns. OD threshold 10u, deals clone and heavy toxin damage on OD.
		Highly technical overlay, add more NT tech-looking devices
	Trader
		Obtainable by Traders
		Uncopyable by Mechanics
		T1
			Nitrogen
				Injectable on Crit, Inaprov for Vox basically
			Gravy
		T3
			Maple Syrup
			Chillwax
		Weird greenbrown color overlay
	Discount Dan
		Obtainable by Cargo
		T1
			Sauce
			Grape Juice
			Tendies
		T2
			Refried Beans
			Off Color Cheese
		T3
			Beff
		Advertisements
		Red makes the sleeper print beff faster overlay
	Ancient Civilization
		Obtainable by Xenoarchery
		Uncopyable by Mechanics
		New Chems:
			Unknown Alpha, Gamma, Omega
			Use randomized_reagents datum for each
		All chems have random symbols for names
		T1
			Unknown Alpha (NEW CHEM)
			Random Karmo Chem
		T2
			Unknown Gamma (NEW CHEM)
			Random Karmo Chem
		T3
			Unknown Omega (NEW CHEM)
			Random Karmo Chem
		T4
			???
		Alien functions take over the sleeper, standard chems disabled
		Weird alien esque overlay
	HONK
		Deep Fry a Dan Plugin
		T1
			Banana Juice
			Honk Serum
		T3
			Colorful Reagent
		Funny Colored Overlay
		Funny comic sans sleeper interface
		Funny Honk noises on entry/exit
	GUNK
		Spill toxic waste on any plugin
		T1
			Toxic Waste
			Chemical Waste
			Salt Water
		T2
			Boogers
			Vomit
			Bilk
		T3
			Chumpari (NEW CHEM)
				the literal worst substance that one of our headmins has ever imbiled in their life
		Gunk takes over the sleeper, other chems disabled.
		Gunked box plugged in to the side
```

**Comment by Eneocho** [comment]
Pretty good overall. A few changes I'd suggest would be:
* Making the HONK module by splashing banana juice/honk serum on any plugin instead of deep frying a dan's one (that fits better for a chef module).
* Adding Mucus (asthma chem) to the gunk list.
* Some fireball stickers to go along with the red recolouring for the dan sleeper (fire is fast!!).
* The new chems have a TG-esque feel to them. I'd rename them a bit.

Does the locutogen injecting thing use the nearest heard voice? Or can you pre-set it internally on the sleeper (this would be better in my opinion, since it'd let you give secret/funny messages without blatantly saying them first)?

**Comment by jwhitak** [comment]
Appreciate the feedback, even though I'm not using all of it or liking all of it. I'm taking all of it seriously after all. Tempers the ideas.

The deep frying is there to encourage crew interaction. The clown breaks into the kitchen to deep fry his cargo order. It may be silly but that's how clowns program high tech machines.

Mucus fits better than Booger. I put booger in because of the gross factor, but it's actually a "normal" bar drink. That gunk list is getting pretty big.

I play 40k Orks. I know the true powah of red paint jobs and fire... Just have to sprite.

The NT sleeper intentionally uses tg-themed names, because they're actually bay-themed names, because they're actually from Star Trek. Station-themed stuff.

Locutogen has a pop-up when you inject it. If the patient is conscious, the Loc whispers it to them on the next life() proc. Otherwise, it waits for them to wake up. There's a lot of problems with trying to speak it out loud, turns out, so instead of wrestling with it, I opted for the less cool but simpler solution.

**Comment by Eneocho** [comment]
>The deep frying is there to encourage crew interaction. The clown breaks into the kitchen to deep fry his cargo order. It may be silly but that's how clowns program high tech machines.

I still think that to make the clown module you should use something clown related, even tangentially. Deepfrying is not really a clown-related item, even if you can use oil as ghetto lube. Maybe some arcane ritual with clown apparel, bike horns, farts and banana peels.
You slather the circuitboard in banana peel fluids, honk once, put a mask on top, honk twice, shoes on bottom, honk 3 times, fart on the thing then honk 4 times. Now you have the honk module.

**Comment by Eneocho** [comment]
I would change Mahkoexpitol to Charcoal. No need for a new niche chem when charcoal can do the trick.

**Comment by Eneocho** [comment]
The description of the unknown chems is missing a period. 
Should be `
description = "A chemical of alien nature, made of theoretically impossible elements."`

**Comment by Eneocho** [comment]
Instead of the unknown chems being called "unknown alpha/delta/omega", why not randomize the name as well? Add a list of a couple hundred chem syllables and make the name randomly from all the samples. You could end up with names such as Kermavene+, Hyccodol, Connic Acidane, etc.

**Comment by jwhitak** [comment]
Charcoal is extremely garbage at handling chemicals and poisonings to the point that most skilled docs will just use water/potass to clear out bad poisons. Or 999u of trash. No other chem removes all other chems instantly, so this new chemical has its place.

I pushed an unfinished commit, this is obviously not the final result. I forgot that I pasted in a placeholder when pushing that commit a few days ago, oops! I've still got another big work shift, but after it's over, I should be able to properly clean up the code.

And the unknown alpha/delta/omega are names in the code. They are hardcoded because reagent names/IDs are hardcoded per #defines. And honestly, they're mainly placeholders unless I can't come up with a better system name for them. As a side note, here is an image from testing...
image

**Comment by jwhitak** [comment]
Currently abandoned with no plans to complete at this time

**Pull request closed without merging**
