### PR TITLE
re-adds nanotrasen HR autoreply

### LINKED ISSUE #27825: IAA HR papers no longer send automated replies
saw some PR pop up a while ago about how messages sent to HR are now redirected to admins too, but now the pieces of paper that the IAA gets at roundstart to demote/reward someone no longer work. no response, nada.

### PR DESCRIPTION
**Pull request by toomykins**
fixes #27825, my very very own complaint
Re-allows you to get that cool little star poster and that demotion key, and you can still fax via them too! admins will not get a notification for the automated faxes, but they will for all other ones.

:cl:
 * rscadd: Nanotrasen HR will automate any requests sent with the magnetic stamp again, and you can still fax any other paperwork to them too!

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
thank you comrade the IAA/lawyer/bridgeofficer association of space america is in your debt

**Comment by ShiftyRail** [comment]
I still don't like anything automated. But I guess that's what the people want.

**Review by jknpj — CHANGES_REQUESTED** [review]
Log this shit. You don't need to notify the mins, but at least log it.

**Comment by toomykins** [comment]
all faxes are already logged, you can read in the logs what was sent to Nanotrasen HR, and so discern whether they received an item or not, which are only gotten from papers stamped with the magnetic stamp. Unless you want me to log what items they got anyway.

**Review by ShiftyRail — APPROVED** [review]

**Pull request merged**
