### PR TITLE
Declunkified Mech Fab menu

### LINKED ISSUE #4791: Mech fabricators have their queue on top, which is weird and annoying
Let's say we want six borg left arms
http://puu.sh/i7uKF/a722dd9035.webm
needlessly tricky

### PR DESCRIPTION
**Pull request by 9600bauds**
ss 2015-06-05 at 01 56 42
look at the pulchritude

fixes  #4791

### CODE REVIEW

**Comment by 9600bauds** [comment]
>cp: cannot stat `baystation12.dme': No such file or directory

ss 2015-06-05 at 10 05 34

Travis being a shit as usual, this does compile

**Comment by Probe1** [comment]
We've finally changed from baystation12.dme to vgstation13.dme.

Mite need to rebase.

**Comment by clusterfack** [comment]
The problem is we need to change over travis' test method to check for vgstation13.dme

**Comment by 9600bauds** [comment]
I don't see why I'd need rebasing, since I didn't touch the .dme

**Comment by clusterfack** [comment]
Travis wouldn't have compiled no matter what yesterday, if you make any push it will now though

**Comment by 9600bauds** [comment]
If the Ripley rebalance gets merged before this I'll have to make a 1 line change about the jetpack's category anyways

**Pull request merged**
