### PR TITLE
Borg pressure / temperature sensor HUD

### PR DESCRIPTION
**Pull request by SonixApache**
Salvage of #15344, minus damage aspects.

example hudcool sprites

🆑 
 - rscadd: Borgs and MoMMIs now have temperature / pressure HUD indicators, based on human stats
 - imageadd: sprites by Bilgecrank / Kokuten
 - tweak: Borg fire indicator now actually works. Probably. Not sure if borgs can catch fire.

### CODE REVIEW

**Review by N3X15 — APPROVED** [review]

**Comment by ihadtoregisterforthis** [comment]
By "based on carbon stats" you mean humans only?

**Comment by SonixApache** [comment]
yes
changed it to 'humans'

**Comment by ghost** [comment]
Hot.

**Comment by jakmak6** [comment]
Even without it's original balance thing it's still a good addition

**Pull request merged**
