### PR TITLE
vox & greys in roles that get extended tanks now spawn with the correct equipment

### LINKED ISSUE #13116: Vox Engineers/Miners spawn with o2 in their survival box instead of n2
[species.dm]
[boxes.dm]

### LINKED ISSUE #15120: Atmos/Engineer Vox start with extended capacity oxygen tanks
(WEB REPORT BY: knightkiller REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
82637aa5c1d23846bc636a3806bd1855bbb4bfaf 
>General description of the issue
Rather than the vox default nitrogen tank in the survival equipment box, its an extended oxygen tank

>What you expected to happen
Have an emergency nitrogen tank (Or perhaps an extended variant)

>What actually happened
Had an extended emergency O2 tank

>Steps to reproduce if possible
Join as engineering vox

### LINKED ISSUE #23137: Cheif Enginner Vox Spawn with Extended Oxygen Tank
(WEB REPORT BY: laserdog REMOTE: 206.221.180.138:7777)
# Revision
fef580631c834e36afd6c75a9c0954e020c6050d

# Description
Cheif Enginner Vox spawns with a emergency extended-capacity oxygen tank instead of an emergency extended-capacity nitrogen tank
# Steps to Reproduce
Spawn as Chief Enginner as Vox
# What you Expected
Have a nitrogen tank in my emergency box
# What Actually Happened
Had a oxygen tank in my emergency box

### LINKED ISSUE #23149: vox mechanic spawns with wrong survival box
(WEB REPORT BY: suchai REMOTE: 206.221.180.138:7777)
# Revision
51ecab414b20d9cfce8a4c0198da691fb00cb173

# Description
at least on packed, vox mechanic spawns with survival equipment box that holds human breath mask and oxygen emergency tank.
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by robintime**
closes #23149, closes #15120, closes #23137, closes #13116

engineering members (and two other roles) get special survival boxes in their loadouts, but a vox equivalent wasn't added, meaning they too got the default yellow tank and mask. this earthshattering PR gives them breathable air and a mask that fits

it was also brought to my attention that greys dont get the yellow tank at all so i added that in too. if there's any other problem with loadout gear being wrong, let me know so i can commit a fix to this PR.

:cl:
* tweak: vox in roles that use the engineering survival box now get an extended nitrogen tank and a vox mask, instead of an oxygen tank and a regular mask
* tweak: greys in roles that use the engineering survival box now actually get the box

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Thanks, good way to go around it.

**Comment by Kurfursten** [comment]
Conflicts

**Comment by Kurfursten** [comment]
Still conflicting

**Comment by robintime** [comment]
oh shit the email i got from 6 days ago telling me to fix my conflicts got fucking buried my bad

**Pull request merged**
