### PR TITLE
New Vault: Pod Station

### PR DESCRIPTION
**Pull request by Optimism333**
## Repair, Refuel, Relax ##
podstation

This is my first attempt at mapping a vault. It's a pod station. Danger level is minor to medium and loot level isn't too extraordinary for the most part. More notable loot includes: a few pod parts, a decent supply of food in the freezer, and about 200 credits and two coins.

There's a lot of functionality, such as a rudimentary power and atmos system, buttons to control shutters and door bolts, camera network (may or may not work, testing inconclusive), and a docking point for the salvage shuttle.

Thanks to BurntDevil and others for help and mapping advice, it helped turn it from a pretty okay vault to what I'd like to think is a pretty good one.

I tested it pretty rigorously, but please give feedback if I forgot to code or add something. I've never done a pr for a map before.

[vault]  [tested]  [content]

:cl:
 * rscadd: Adds a new vault named "Pod Station".

### CODE REVIEW

**Comment by Eneocho** [comment]
Is the pod part good? I'm talkin advanced pod guns, the military pod body, etc.

**Comment by Optimism333** [comment]
> Is the pod part good? I'm talkin advanced pod guns, the military pod body, etc.

No, it's not a military pod depot. If I was to make something like that I'd have to bump up the difficulty. This is just a civilian pod station where you can find some spare civilian pod parts. Think of it as a local petrol/gas station.

**Comment by Kurfursten** [comment]
> Directional glass on the same side as the gas chamber

You have made a grave mistake

**Comment by Optimism333** [comment]
> > Directional glass on the same side as the gas chamber
> 
> You have made a grave mistake

You're not the first one to mention this, but I tested turning the miner on and nothing extraordinary seemed to happen. I suppose I could place the glass on the next tile, then?

**Comment by SonixApache** [comment]
yes - glass on a tile where there is very high pressure causes it to shatter, whereas glass against a tile that is very high pressure is perfectly fine

cute vault, :+1:

**Comment by SootyBear42** [comment]
Add a crypod spawner in it

**Comment by Kurfursten** [comment]
As Sonix said, it will take a while to build up pressure but then certainly shatter

**Comment by Eneocho** [comment]
I think it shattering would add a bit of that "derelict" feel to it.
Also, you can already get military pods without conflict. Pods can spawn next to the old gas mix vault, it's a one in four chance (I think?) of it being a military pod (it just has better armor).

**Comment by SonixApache** [comment]
some guy in the thread is screeching that you should replace the gas miner with a gas canister because they're too strong and shouldn't be more acessible than the ones in atmos

As such, I recommend adding an N2 miner and gas mixer setup to help with maintaining proper atmos.

**Comment by Optimism333** [comment]
> some guy in the thread is screeching that you should replace the gas miner with a gas canister because they're too strong and shouldn't be more acessible than the ones in atmos
> 
> As such, I recommend adding an N2 miner and gas mixer setup to help with maintaining proper atmos.

I can try my best, but I really don't know anything about atmos. Even this very simple setup I was only able to manage by looking at how the box mining outpost was set up and copying the concept.

Is there anything I can look at as a simple reference for how to lay it out? And also, can it fit in the current tiny tool storage area or will it need more space?

**Comment by SonixApache** [comment]
I was just joking, there's no actual need for N2 anywhere. That said, if you'd want to actually implement that, you'd need a bit more space. One room per miner and scrubber, then a mixer outside. Could be built in a 3x3 square.

**Comment by Optimism333** [comment]
Unless it becomes a serious issue that's make or break for the pr, I think I'll leave it as is. If the person is particularly upset over it I'd appreciate it if they'd discuss it with me and offer advice on how to make an alternative.

**Comment by Optimism333** [comment]
> I think it shattering would add a bit of that "derelict" feel to it. Also, you can already get military pods without conflict. Pods can spawn next to the old gas mix vault, it's a one in four chance (I think?) of it being a military pod (it just has better armor).

Fair, but I just don't think that military pod gear is something I want to add to this vault. It's a humble abandoned pod station that was intended for civilian craft. There's a fair bit of loot already, and the potential to use it as a comfy base location that you can travel to with the salvage shuttle. It just needs a little cleanup and care to get running again.

**Comment by Kurfursten** [comment]
I do think you should stick to the aesthetic, no reason someone can't make a more militaristic pod dock in the future

I would like to suggest you remove cockroaches from the main room of the diner however so that they do not use the food in there to multiply en masse and consume loads of cycles even when no one has found the vault; just keep them in the bathroom and a player can loose the horde if they want

**Comment by Exxion** [comment]
> yes - glass on a tile where there is very high pressure causes it to shatter, whereas glass against a tile that is very high pressure is perfectly fine
> 
> cute vault, 👍

Only fire damages windows, not pressure.

**Comment by Optimism333** [comment]
> I do think you should stick to the aesthetic, no reason someone can't make a more militaristic pod dock in the future
> 
> I would like to suggest you remove cockroaches from the main room of the diner however so that they do not use the food in there to multiply en masse and consume loads of cycles even when no one has found the vault; just keep them in the bathroom and a player can loose the horde if they want

Alright, I'll make a compromise on this one. I don't really want to relegate the roaches to just the bathroom, as I also consider them part of the aesthetic of the run down pod station. However, to keep them from multiplying out of control I'll remove most of the loose food on the ground and replace it with more trash or random items.

**Comment by Kurfursten** [comment]
You gotta get all the food or they will spend an hour using that one food piece to breed for no one to even see them

**Comment by Optimism333** [comment]
> You gotta get all the food or they will spend an hour using that one food piece to breed for no one to even see them

Alright, alright. All the floor food is gone. The remaining food is safely sealed away in the freezer.

**Comment by Eneocho** [comment]
On my way to get to the pod station with a bagful of potatoes and a handtele to breed the unholy army of roaches and bring forth massive gunk.

**Comment by Optimism333** [comment]
> On my way to get to the pod station with a bagful of potatoes and a handtele to breed the unholy army of roaches and bring forth massive gunk.

That would definitely be one of the more creative ways to sow chaos on the station.

**Comment by Eneocho** [comment]
Well, you can already do that sans teleportation easily in the station. Just grab Radical Steve, hack a few vendors to dispense food, wait a while and release. Bonus points if you sprayed the roaches with mutagen. Extra bonus points if you somehow managed to get a mutated queen.

**Comment by Kurfursten** [comment]
That's all fine because a player is actively choosing to do that instead of it happening passively on a z level no one is observing

**Comment by Eneocho** [comment]
I find it fascinating that the serb simulates events outside of the currently in-use Z-levels. It seems like a waste of processing power, considering just how old and clunky byond is. There's probably a completely reasonable explanation on how it is like that because it'd require buffering on Z-level changing or whatever, but still.

**Pull request merged**
