### PR TITLE
Adds beekeeping attire to hydroponics lockers

### PR DESCRIPTION
**Pull request by ValkyrieSkies**
Hydroponics lockers now have a chance of spawning the beekeeper's jumpsuit, and will always spawn with a beekeeping suit.

Inspired by watching a poor botanist who had no idea beekeeper suits existed die repeatedly to his bees.

[qol]
:cl:
 * rscadd: Hydroponics lockers now contain beekeeping gear

### CODE REVIEW

**Comment by DrSnips** [comment]
It seems like it's getting a bit full. I forget what the limit of lockers are, did you make sure everything fits?
Edit: I just realized they are pick lists. My mistake.

**Comment by WindowsErrors** [comment]
the limit to a closet is 30 items

**Comment by Killette3** [comment]
Honestly it feels a little silly having to buy one from cargo or steal/make a spacesuit every time. This feels like giving them a free bone but I think it's the best of all our options as I don't see how one would be craftable.

**Comment by Kurfursten** [comment]
I'm not necessarily opposed to this since bees can appear as a random event

**Comment by KingofHONK** [comment]
Ill thumbs it up if you can add a guaranteed coverall spawn in locker instead of random % chance

**Comment by WindowsErrors** [comment]
what if we just don't emoji the PR at all and leave it like this? what happens then? the collabs might not function without thumb emojis and they'll eventually fall into a recursive overflow after searching for the non-existent thumb emojis for long enough

**Comment by Kurfursten** [comment]
If not even one person on the server supports it that says something too

**Comment by jwhitak** [comment]
Thoughts: Bees are annoying to deal with from an outsider's standpoint. Requiring interdepartmental work to get the things going is usually good for the game, right? That's what I'm always told. But this is the bare minimum stuff to even consider getting started with the business of bees. I didn't react to this post because I didn't feel justified in commenting on something that I didn't use or interact with directly.

But you haven't gotten a SINGLE reaction to this despite the tons of comments thinking. So have my thumbs up. If the game is ruined because of this PR, there's always the revert button.

**Comment by ValkyrieSkies** [comment]
> Requiring interdepartmental work to get the things going is usually good for the game, right? That's what I'm always told. But this is the bare minimum stuff to even consider getting started with the business of bees.

This was my core line of thinking when making this PR - While it's good to promote interdepartmental interaction, I believe that any job available from roundstart should have its core tools available to it. If it was just Botanist and Hydroponicist then sure, let it be a weird expansion available via cargo, but if Beekeeper is going to be a core option then they should be able to do their job properly.

**Pull request merged**
