### PR TITLE
Changes the runechat font

### PR DESCRIPTION
**Pull request by ShiftyRail**
The goal was to get a less thick font for runechat that would still look somewhat ok at low resolutions. I think Calibri works better than BYOND's default.

New font:

Calibri

Old font:

88434472-854d9f00-ce00-11ea-91cf-ad620d2bd4d0

Emoji it as you want.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
The new font makes it seem kind of blurry, and with the blur seemingly affecting some letters more than others.

**Comment by ShiftyRail** [comment]
That's true, especially now that I compare the two.

**Comment by Zth--** [comment]
It doesn't look good

**Comment by tuypo1** [comment]
Unreadable garbage

**Pull request closed without merging**
