### PR TITLE
Wearable trash bags

### PR DESCRIPTION
**Pull request by Probe1**
Re-opens https://github.com/vgstation-coders/vgstation13/pull/17274 to fix the conflicts

### CODE REVIEW

**Comment by Probe1** [comment]
Why are icon conflicts so fucking autistic I used a copy of the dmi from bleeding edge and added the new sprite manually.  Even mapping conflicts feel less foul.

**Comment by Probe1** [comment]
Dude what

**Comment by MadmanMartian** [comment]
mob/head.dmi conflict, mob/suit.dmi conflict

**Comment by Probe1** [comment]
I fixed it by remaking the PR entirely and that was merged.

**Comment by MadmanMartian** [comment]
ah okay, blithering had told me otherwise

**Comment by Probe1** [comment]
For future reference this PR was the merged one. https://github.com/vgstation-coders/vgstation13/pull/17685

**Pull request closed without merging**
