### PR TITLE
Butterfly Knife Refactor + Effects

### LINKED ISSUE #20813: Butterfly Knife needs an Inhand/Danger Message/Effect
I see this mostly as a neutral third party admeme observer so it's not an "i ded pls nerf", this thing is seriously one of the nastier antag items and most people stand by completely oblivious to the person holding it.

It just needs to be more noticeable when it is deployed. People are not pinpointing the source and rarely know what's going on as waves of bugs roll over them.

### PR DESCRIPTION
**Pull request by Kurfursten**
Essentially rewrote butterfly knives to be more OOP

Now produce a unique effect when
* You regenerate or pick up a viscerator
* You release a viscerator (also plays a sound)

closes #20813

🆑 
* tweak: Butterfly knives now can only pick up a viscerator or crystal butterfly if they are open.
* tweak: Butterfly knives now display an effect and play a unique (spooky) sound when they deploy a viscerator or crystal butterfly.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
backstabbing when

**Comment by Probe1** [comment]
Well shit I did not look at the tags I just read the code and OP.  Sorry I would have waited the usual week for Balance.

**Comment by Kurfursten** [comment]
Probably not devisive, it was advertised in the thread twice and no real interest

**Comment by nuklearcellphoneg** [comment]
pls no my antag weapon

**Pull request merged**
