### PR TITLE
Proposal: Only one "Summon X" artifact may be used per spellbook.

### PR DESCRIPTION
**Pull request by DeityLink**
`[16:13:40]GAME: syruseeln/(I Gift The Crew Incredible Powers Then Suicide) <span title='wizard'>(A)</span> summoned magic!`

I don't like this gimmick. A single Summon artifact can already do enough gunk on its own. No need to spam 5 of those.

:cl:
* tweak: "Summon X" artifacts such as Summon Guns or Summon Swords are now single-use and mutually exclusive.

### CODE REVIEW

**Comment by Theophrastus1** [comment]
best part is he didnt suicide

he rushed the armory for guns and then hopped on a snowmobile

**Comment by jwhitak** [comment]
Mutually exclusive? Ehhhhhhhhhhh. I'm fine with one cast per book, but sometimes a mix of giving everyone a bit of magic and also giving them all cool melee weapons is ok?

**Comment by DeityLink** [comment]
> Mutually exclusive? Ehhhhhhhhhhh. I'm fine with one cast per book, but sometimes a mix of giving everyone a bit of magic and also giving them all cool melee weapons is ok?

I can make it so you can only use 2 of them (including only one of each). But I think allowing one of all 5 marginally changes the problem.

**Comment by jwhitak** [comment]
I accept this compromise. Alternative compromise would be unlimited casting, but only appearing in an area of effect around the wizard (as proposed before).

**Comment by DeityLink** [comment]
I'll wait a while for the discussion to proceed before applying changes to the PR.

> Alternative compromise would be unlimited casting, but only appearing in an area of effect around the wizard (as proposed before).

I like this, although this also changes quite a lot the way the spell work. It'd also require to re-think the way Survivors work if kept at all.

**Comment by Eneocho** [comment]
Awful proposal. The point of using the summon X spell is to empower the crew and cause chaos among them. Being able to do so multiple times balances the field from the guy that got a chaingun vs the guy that got a generic laser pistol, not to mention the combos that have their place in-game, like potionseller-survivor(guns).

**Comment by west3436** [comment]
> I accept this compromise. Alternative compromise would be unlimited casting, but only appearing in an area of effect around the wizard (as proposed before).

There's no reason to "compromise" on something nobody has really complained about before

**Comment by DorainGrey** [comment]
> I accept this compromise. Alternative compromise would be unlimited casting, but only appearing in an area of effect around the wizard (as proposed before).

This would be terrible, casting it around your meta buddies to give them all antag and weapons.

**Comment by Hinaichigo** [comment]
It's fun having the option.

**Comment by nervere** [comment]
Just make each summon spell one use each so people are less inclined to mash a button.

**Comment by SonixApache** [comment]
every 'summon x' spell should just give any person on the receiving end a 'summon x' spell of their own

**Comment by ShiftyRail** [comment]
Survivor is the purest form of antag, and made even purer if everyone is one.

**Comment by DeityLink** [comment]
> Survivor is the purest form of antag, and made even purer if everyone is one.

I totally agree with that. But I also think we should have it no longer have it be tied to Summon Guns, in my opinion (that's beside the scope of this PR regardless). 

> There's no reason to "compromise" on something nobody has really complained about before

No one has really complained about Summon Guns spam? That's just plain false. To me it's also the wizard's _"Well I'm too tired to pull off an interesting gimmick so here crew have guns and mess the station up in my place"_ card. Limiting the use of those artifacts would incite the Wizard to spend some points in other spells and stuff as well.

**Comment by DeityLink** [comment]
> Being able to do so multiple times balances the field from the guy that got a chaingun vs the guy that got a generic laser pistol

I'd say this imbalance is part of the fun of Summon Guns. You have to play with whatever hand you got dealt.

> not to mention the combos that have their place in-game, like potionseller-survivor(guns).

That's a fair point, hence the compromise we talked above.

I'll let people voice their opinions in here for a few days then see if we can hold a server poll so all players can vote whether they're fine with the artifacts as they are, or whether they'd like them changed one of several ways.

**Comment by Securitymain** [comment]
we are becoming VG

**Comment by SootyBear42** [comment]
Haven't really read anything but it just seems you got butt blasted over one round.

**Comment by Theophrastus1** [comment]
how about this. Summon x only gives the people it chooses as survivors/wizards guns/spells instead of just dumping it to a shitload of people.

**Comment by ShiftyRail** [comment]
@Theophrastus1 but then you got a free antag check. IIRC I did it before, didn't work.

**Comment by TGFH** [comment]
> @Theophrastus1 but then you got a free antag check. IIRC I did it before, didn't work.

A free antag check on people who are armed and have no reason to worry about escalation.

**Comment by Blithering** [comment]
I would say make it all or nothing. limit it to one cast per round, but add one that casts magic/guns/melee at random five times.

**Comment by kacurasuo** [comment]
just like the government, the coders should provide as many liberties to their citizens as can be reasonably given

**Comment by Securitymain** [comment]
What if you let them summon 5x but only the first time fires the survivor lottery?

**Comment by DorainGrey** [comment]
> What if you let them summon 5x but only the first time fires the survivor lottery?

This could be a compromise and actually play into the paranoia, as there's actually a chance someone isn't an antag.

**Comment by DeityLink** [comment]
I'll lay this proposal to rest now. People have made it clear they don't like this direction.

**Pull request closed without merging**
