### PR TITLE
MDF Heavy Armor Uplink Changes, MDF Gear Belt split into its own uplink entry

### PR DESCRIPTION
**Pull request by Optimism333**
## What the pr does and why ##
After a while thinking about a suggestion provided in #33133 , I decided to apply it. The MDF Heavy Armor and MDF Gear Belt are now separate purchases from the uplink, and the quality of gear in the belt has been buffed a bit to justify the extra TC spent.

ayyuplinkscreen

## MDF Heavy Armor Changes ##
- The MDF Heavy Armor kit no longer includes a gear belt, instead it comes with an ayy soldier's uniform and boots to complete the look.

mdfheavy_kit

- Pictured here with black gloves and a security backpack

mothershipheavy_gear

## MDF Gear Belt Changes ##
- The MDF gear belt is now its own separate entry under the Extraterrestrial Black Market. It currently costs 5 TC, 4 TC for ayys. It includes an ion pistol, binoculars, first aid autoinjector, two stacks of trauma kits (one for brute, one for burn), extended oxygen tank, and a few other misc items (gas mask, zam biscuit, red suit cigarettes and lighter). This makes it a more useful addition to any traitor's kit, without having to worry about buying a set of armor along with it that you might not be able to wear.

mdf_belt

- Looks very similar to a normal sec belt at a glance, so unlikely to attract unwanted attention on its own.

mdfbelt

## Closing Thoughts ##
Please do share thoughts and feedback. I did my best to balance the belt's TC price, but I might have under or overshot it.

:cl:
 * rscadd: MDF Heavy Armor purchased from an uplink no longer includes a gear belt, instead it comes with a uniform and boots
 * rscadd: The MDF Gear Belt has been moved into its own entry, contains better gear, and costs 5 TC undiscounted, 4 discounted

### CODE REVIEW

**Comment by luigil101** [comment]
5 tc for a pair of binoculars and a belt feels pretty gay
a single TC discount is similarly mediocre

**Comment by PrimeDSS13** [comment]
gear belt is too expensive for what amounts to all extremely easy to obtain items

**Comment by Optimism333** [comment]
@luigil101 @PrimeDSS13 Do you have any suggestions for what could be added to the belt to make it more worthwhile? Or alternatively, what would be a more reasonable price?

**Comment by Optimism333** [comment]
The MDF belt now comes with an ion pistol sidearm for disabling tech, to give a bit more value to the buyer in exchange for the 5 TC price.

Screenshots and descriptions have been updated.

**Pull request merged**
