### PR TITLE
Bruschetta fixes

### PR DESCRIPTION
**Pull request by TheFriggenSawbones**
Who the FUCK did this.

🆑 
* bugfix: Bruschetta is made with Tomatoes, not Grapes idiots.

### CODE REVIEW

**Comment by DamianX** [comment]
Can confirm, there's no grape whatsoever in bruschette.
Also, you fucked up the changelog.

**Comment by TheFriggenSawbones** [comment]
SORRY I FIXED IT

**Comment by MadmanMartian** [comment]
Updat wik

**Comment by TheFriggenSawbones** [comment]
i wil

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Obviously it's made with grape tomatoes

**Comment by TheFriggenSawbones** [comment]
i updated the wiki thank u

**Pull request merged**
