### PR TITLE
Stunglove changes

### LINKED ISSUE #9238: Stungloves are obscured by hardsuits, yet can be used while wearing one anyways
Not only do hardsuits hide the stunglove's sprite, they also hide them from examination and from the stripping menu. This is fairly shitty considering that they still work anyways, even with a hardsuit on.

Proposed solutions:
- Easy: Stungloves don't work while obscured
- Probably Impossible: Make the stungloves display over the hardsuit on icon and on examination
- Best: Your hardsuit conducts the stungloves' electricity and shocks you instead

Also, stungloves need a sound

### PR DESCRIPTION
**Pull request by Sprok0**
Recoloring stungloves with a washing machine doesn't revert the worn sprite.
Stungloves stun on any intent, you can't hug someone with electric hands.
Wearing other clothing that covers up your hands prevents the use of stungloves.

Fixes #9238

### CODE REVIEW

**Comment by Durgen** [comment]
perhaps stungloves shouldn't work while wearing a hardsuit

**Comment by Sprok0** [comment]
Hardsuits cover your hands

**Comment by Shadowmech88** [comment]
Would it be possible to check the `seimens_coefficient` of whatever is covering your hands and, if it's high enough, make the gloves shock you instead?

**Comment by Sprok0** [comment]
That seems a bit too mean-spirited

**Comment by TheFriggenSawbones** [comment]
P L A S M A M A N
                           E
                           R
                            F

**Comment by 9600bauds** [comment]
Fixes #9238

**Comment by SkowronX** [comment]
@TheFriggenSawbones
>perf

**Comment by Probe1** [comment]
I am probably the biggest proponent of stun gloves and have told people to fuck off from engineerings best self defense tool for going on 3 years, and even I think this is fine.

**Pull request merged**
