### PR TITLE
Bicaridine's and Inaprovaline's bleeding slowdown now stacks.

### PR DESCRIPTION
**Pull request by Eneocho**
Something I suggested in #32404 that I wanna see.
Consuming both Bicaridine and Inaprovaline now slows down bleeding by 60% (30%+30%) instead of only 30%.
[tweak]
:cl:
 * tweak: Bicaridine and Inaprovaline slower bleeding effect stack with each other.

### CODE REVIEW

**Comment by pedr69** [comment]
i'd make inaprov not shit instead
does bicard need to be even better?

**Comment by Eneocho** [comment]
Bicaridine and Inaprovaline call the same -30% bleeding currently, so you can't stack em. This is a strict Inaprovaline buff because it now stacks. Your turbo ready paramedic can tame that bleeder up to -60% with this.

**Comment by jwhitak** [comment]
This makes a resting (not strapped to bed, an actual resting action) speeseman with inaprov and bicaridine have only 10% normal blood loss. This is fair because throwing them in cryo completely halts the blood loss, and paramedics already have a chemical bleeding stopper.

**Comment by Kurfursten** [comment]
I think this is too far, but I guess we aren't the server we were back in the old days of harmdragging.

**Pull request merged**
