### PR TITLE
Adds (preloaded) boot knife holsters to Mining vending machines

### PR DESCRIPTION
**Pull request by 9600bauds**
This is probably going to be requested after #12728 goes live (miners can't butcher shit with their drills anymore). Do not merge until after #12728

:cl:
 * tweak: Mining vending machines now stock cheap boot knife holsters, to compensate for drills not being able to butcher asteroid mobs anymore.
 * imageadd: The Mining knife holsters come with a fucking sweet skinning knife, sprites courtesy of Blithering.

### CODE REVIEW

**Comment by Blithering** [comment]
Possible skinning knife icon.
knife
Download link: http://s000.tinyupload.com/index.php?file_id=17577891126206344953

**Comment by 9600bauds** [comment]
fukn sweeeet

**Comment by 9600bauds** [comment]
dreamseeker_2016-12-11_03-15-12
Even added inhands, you've outdone yourself @Blithering

**Comment by jakmak** [comment]
Is the machete the same sharpness and damage as the sec boot knife?

**Comment by Intigracy** [comment]
Yes.

Also why the hell are the tactical knife and machete in this file instead of with the other knives?

**Comment by 9600bauds** [comment]
shhh it's not a machete it's a "skinning knife"

**Comment by 9600bauds** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaa DMI conflicts

**Pull request merged**
