### PR TITLE
Adds Fire Extinguisher to Box Arrivals Shuttle

### PR DESCRIPTION
**Pull request by Kharkov72**
There is no way emergency way out of the shuttle in the shuttle if the power is out to the doors as there is nothing that can break windows.
This is to fix that because it annoys me.
Oh god I'm a m*per now.
[box] [first]

:cl:
 * rscadd: Adds Fire Extinguisher to box shuttle.

### CODE REVIEW

**Comment by robosperg** [comment]
emergency air tank, kicking shoes if you dont have a tank for whatever reason

**Comment by Kurfursten** [comment]
fix 🆑

**Comment by Kharkov72** [comment]
Fixed

**Comment by Kurfursten** [comment]
Conflicts

**Comment by Kharkov72** [comment]
I'm dumb and gay.

**Pull request closed without merging**
