### PR TITLE
Fixes Numpad numbers no longer working

### LINKED ISSUE #29678: Can't use the numpad for typing numbers after the kane-f targeting PR.
I can't write me numbers the way I'm used to. Was it worth it, Kane-f? Soul, ruined.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #29678

AZERTY bros rise up!

:cl:
* bugfix: Fixed the numpad no longer letting you type numbers.
* tweak: To change which zone you're targeting using the numpad, you now have to hold the ALT key down at the same time (except for hands and feet that still require you to hold down CTRL)

### CODE REVIEW

**Comment by Eneocho** [comment]
Would this fix the macros bound to numpad as well? If so, link #29466 too.

**Comment by calzilla1** [comment]
Honestly it just be best to completely revert #29447. Does anyone actually use the numpad targeting system? I think most spessmen are just accustomed to using the GUI and the newer ones probably don't even know about numpad targeting. Let me know if anyone here actually does use it though (other than you kanef)

**Comment by djkramer123** [comment]
> Let me know if anyone here actually does use it though (other than you kanef)

I like and use them

**Comment by DeityLink** [comment]
> 
> 
> Honestly it just be best to completely revert #29447. Does anyone actually use the numpad targeting system? I think most spessmen are just accustomed to using the GUI and the newer ones probably don't even know about numpad targeting. Let me know if anyone here actually does use it though (other than you kanef)

Honestly I didn't know about it until I came across #29678 but I think it's good QoL (so long as it doesn't lead to feature loss at the same time). I'll probably use it from now on.

> 
> 
> Would this fix the macros bound to numpad as well? If so, link #29466 too.

Can't say for sure since I do not use macros, let me know after this gets merged.

**Pull request merged**
