### PR TITLE
adds Sood to code credits

### PR DESCRIPTION
**Pull request by gbasood**

### CODE REVIEW

**Comment by Exxion** [comment]
Come on, put it in the right place alphabetically

**Comment by Intigracy** [comment]
eww you broke my alphabetization

**Comment by ghost** [comment]
Wait, you can do that, just add yourself to the credits?

**Comment by Exxion** [comment]
Yes, but this is only the third time I know of someone doing it

**Comment by gbasood** [comment]
@Skullyton I'm important :eggplant:

**Comment by Intigracy** [comment]
If you want yourself in the credits, add yourself to the credits.

Nobody minds.

Also sood I'm more important. #7179

**Comment by Intigracy** [comment]
Also this PR doesn't have any memes, please add a meme.

Under Thanks To:, add "And thank YOU, random citizen."

**Comment by Exxion** [comment]
#5027
Bonus: clusterfack#3

**Comment by gbasood** [comment]
@Intigracy My first PR was before yours
get on my level

**Comment by Exxion** [comment]
@gbasood You sure about that? Because it looks to me like his first was almost a year before yours

**Comment by SysadminJeroen** [comment]
So, when does a person qualify to be on this list?

**Comment by Exxion** [comment]
When a PR adding them to it gets merged

**Comment by gbasood** [comment]
Got the month wrong on when I first contributed nevermind

**Comment by mrpain666** [comment]
Why not?

**Comment by Zth--** [comment]
Why don't we move all those people who aren't around anymore to "special thanks" or something like it?

**Comment by Zth--** [comment]
Now that you're on it, can you fix my name? It's "Zth", not "Zth--"
:)

**Comment by Intigracy** [comment]
> Zth-- commented 10 hours ago

:)

**Comment by PJB3005** [comment]
Please the meme tag is [honk].

**Pull request merged**
