### PR TITLE
Held items no longer block while incapacitated

### PR DESCRIPTION
**Pull request by Sprok0**
Held shield items don't work to block things while the holder is stunned, unconscious, dead, etc.
This mostly applies to the changeling armblade, but also superglued items as well.

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
Why?

**Comment by Sprok0** [comment]
Because magically blocking incoming lasers or toolboxes while otherwise unable to act is dumb. How does having your arm being a sword/having a sword stuck to it negate half of everything directed at you in all circumstances?

**Comment by NigglyWiggly** [comment]
Wait, the arm blade can deflect fucking lasers?
Why is that a thing in the first place?

**Comment by Sprok0** [comment]
Every single item with isshield = 1 blocks any incoming attack (50 - (1/3 damage))% of the time, regardless of the source or what kind of attack it is. It isn't really an issue until you have stunned changelings blocking every single blow and projectile thrown at them with their unremovable esword

**Pull request merged**
