### PR TITLE
Oww, my shin!

### PR DESCRIPTION
**Pull request by SysadminJeroen**
:cl:
 * spellcheck: Oww, my shin!

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Are you certain this is a typo, and not intentional?
There was an infamous player in /vg/station's past called Shin.

**Comment by SysadminJeroen** [comment]
No clue, man.

**Comment by Exxion** [comment]
I'm pretty sure this was intentional

**Comment by Ephx1** [comment]
don't speak its name

**Comment by SysadminJeroen** [comment]
There is only one way to know, @ComicIronic?

**Comment by SonixApache** [comment]
definitely intended
might be time to lay him to rest though

**Comment by N3X15** [comment]
We leave this in as a warning so history is not repeated.

**Pull request closed without merging**
