### PR TITLE
Removes the toxin damage from the radgun but makes it cheaper

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
### Why?
The radgun is extremely powerful because it can kill very fast and most conventional protections do not work. However, by removing the toxin damage it is more manageable to deal with. To compensate however, its price was reduced from 18 to 12 (the radiation can kill over time in a shot or two depending on RNG) while the discounted price was reduced from 14 to 9 (are you a bad enough dude to dual-wield them at the cost of almost all your TC?)
:cl:
 * tweak: The radgun does not do any more initial damage anymore. To compensate, its price was reduced in the traitor uplink.

### CODE REVIEW

**Comment by SonixApache** [comment]
12 TC still seems like a lot, can you show what one and two shots actually do to someone now?

**Comment by boy2mantwicethefam** [comment]
50-250 radiation + randomly activating approx 2 genetic blocks, the radiation isn't immediately dangerous and it will take a while for it to kill

**Comment by SonixApache** [comment]
Show me numbers, Peter!
Show me vomiting neon waifu haired monkeymen with bodyscanner readouts at point-of-impact and 10 minutes after, for both single and double shots!

**Comment by boy2mantwicethefam** [comment]
Above 100 radiation will kill (arguably lower because toxin damage causes liver damage which then causes toxin damage until treated), but because the radiation is external it can get blocked by radiation-shielded suits.

altered = max(0, (effect/100)*(100-getarmor(null, "rad")))

The effects of radiation itself are found in human/life/handle_mutation_and_radiation.dm

**Comment by SonixApache** [comment]
post testing pictures you dweeb

**Comment by boy2mantwicethefam** [comment]
Testing pictures? What for more specifically?

**Comment by ShiftyRail** [comment]
Toxin damage isn't what makes the radgun such a pain in the arse, it's the radiation damage, the fact that it's self-recharging, & the stun built-in

**Comment by SonixApache** [comment]
like i said in the other post, i want pictures of bodyscans
one of hit once, seconds after impact
one of hit once, (ten) minutes after impact
one of hit twice, seconds after impacts
one of hit twice, (ten) minutes after impacts

**Comment by KingofHONK** [comment]
This is clearly a stealth genefag buff

**Comment by boy2mantwicethefam** [comment]
God I wish
@SonixApache I should get em in a bit

**Comment by ShiftyRail** [comment]
Nothing stealthy about it
The geneticist will now be able to buy 8 TCs worth of stuff whilst keeping what made his meme weapon deadly

**Comment by boy2mantwicethefam** [comment]
Initial impact
first
Two shots
third

Both died within minutes, but the one with worse radiation died faster while the one that was shot only once died about 2-3 minutes later. I've noticed that it can be best treated with medical intervention, with things such as arithrazine, before the radiation causes any more damage.
dead
dead but with more radiation

**Comment by boy2mantwicethefam** [comment]
I mean @KingofHONK I can increase the TC price to 10 or 11 if you think I am doing a stealth buff

**Comment by Kurfursten** [comment]
I didn't comment on this right away because I wasn't sure how to feel about it. I think your heart is in the right place but I *feel* like the most likely result of this change will be a lot of stalemates where both people die. You know, geneticist gets off two shots on the officer, officer stuns him and starts batoning him to death, then falls over dead from radiation.

It's a weird situation because you just *can't* go into an engagement relying on a gun that only has an impact 2 minutes later.

**Comment by jknpj** [comment]
I want my muderbone weapon with emag and chips.

**Comment by Dacendeth** [comment]
I think it just shouldnt self recharge

**Comment by boy2mantwicethefam** [comment]
Too many downvotes

**Comment by SonixApache** [comment]
coward
this only got downvoted because of your bad PR streak

**Pull request closed without merging**
