### PR TITLE
Finishes Previously Made Pull Request Based On Chemistry

### PR DESCRIPTION
**Pull request by bathosbathtime**
This explosive PR finally adds what should have been added a long time ago, with demands made in a previously made PR of mine.  The need for this has been a real purge on my system.

Caramel recipes and foods.

This PR adds the caramel recipe, caramel cake, caramel cookies, caramel burgers, and caramel pie.  It also adds caramel to flan and gigapuddi (Reagents in the final products not the recipe to make) to match their description.  Which is weird for flan since it doesn't seem to have sugar in the recipe but that is a problem for a different PR.  I will update the wiki to include these once they are added to the game to avoid confusion.
Compiled and tested locally.
FOOD_SWEET CL removed to avoid clogging CL
Caramel apples added

:cl:
 * rscadd: added caramel cake, caramel cookies, caramel burgers, caramel apples, and caramel pies.
 * rscadd: caramel, caramel cake, caramel cookies, caramel burgers, caramel apples, and caramel pies can now be made with a microwave.
 * rscadd: Flan and gigapuddi and flan now have caramel in them after baking

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Gave me false hopes/10

**Comment by Kurfursten** [comment]
>Caramel burger

Cmon at least make things that exist!

**Comment by DamianX** [comment]
Players don't know what a FOOD_SWEET flag is or why they care
In fact, neither do I

**Comment by Shadowmech88** [comment]
No caramel apples?

**Comment by bathosbathtime** [comment]
We already have candied apples; candied burgers was clearly a higher priority anyway.

**Comment by Kurfursten** [comment]
@DamianX It is my theory that whoever was making the vegan disability had plans somewhere down the line to make a diabetic or something

**Comment by Shadowmech88** [comment]
I'll have you know that candied apples are completely different from caramel apples.

**Comment by Gringonius** [comment]
Caramel 'cubes'? Wait what?

**Comment by bathosbathtime** [comment]
I have learned that candied apples and caramel apples ARE two different things, and I will be adding them soon.  Just have to test them to make sure they work/the sprite isn't an abomination before God.

@Gringonius Caramel cubes!  Cubes of caramel.  Easier to work with than sauce as you don't need to constantly heat them.

**Comment by bathosbathtime** [comment]
Here are the sprites if you don't want to see them from the Diffs check:
caramel
Left to right:
caramel condiment jar, caramel pie, caramel cake, caramel cake slice, caramel cookie(ugly), caramel burger, caramel apple(cyanide), and caramel apple(apple).

**Comment by SonixApache** [comment]
title of this PR is stupid
🆑 is stupid
good content 👌

**Comment by Shadowmech88** [comment]
The caramel being in a jar is a little weird, it looks like a honey jar to me.
The caramel apple's stick looks kind of strange. Also is that our current apple sprite?

**Comment by bathosbathtime** [comment]
The caramel jar is a recolored honey jar sprite and the caramel apples are a recolored candied apple sprite

**Review by MadmanMartian — COMMENTED** [review]
>says chemistry
>chemistry never used

**Comment by bathosbathtime** [comment]
#19084 is the previous PR based on chemistry that this PR finishes.
Further, the caramelization of sugar is still a chemical reaction even if it doesn't use the specifically designated chemistry toys.  That word actually means something outside of the game.

**Comment by bathosbathtime** [comment]
We'll, the sprites need work anyway and I can't shake these conflicts.  I'm going to close this and make a new PR in the future.

**Pull request closed without merging**
