### PR TITLE
Adds Add Reagent to SPAWN flag. Doesn't remove from DEBUG flag.

### PR DESCRIPTION
**Pull request by Intigracy**
```
4:46 PM - Intigracy: I want to make the right click > add reagant part of spawn
4:46 PM - Intigracy: instead of debug or whatever it's under
4:46 PM - Intigracy: whatchu think
4:47 PM - Probe1: yea sure
```

It's literally just inserting reagents into whatever you're right clicking, and fails on incorrect reagents.

### CODE REVIEW

**Comment by ghost** [comment]
Woah, way to code yourself more shitmin power

**Comment by Intigracy** [comment]
I asked first though.

**Comment by Intigracy** [comment]
Adjusted so it's not taking it away from DEBUG.

/client/proc/respawn_character is under both SPAWN and REJUV, but doesn't appear twice in the verbs list, if anyone is afraid of something similar happening here.

**Comment by Probe1** [comment]
yea whatever

it makes more sense under spawn than debug even though it was undoubtably added for debugging purposes

**Pull request merged**
