### PR TITLE
Voucher Description Tweaks

### PR DESCRIPTION
**Pull request by jwhitak**
image
image
image
*Picture: happy clown who knows how to use a voucher*
### Gently modifies some voucher descriptions
Ever get a voucher and not know how to use it? The descriptions should be a little more useful now. Here's an example of the free self-heating donk pocket voucher.

### Cleans up some code!
Exciting! It's easier to read now.
#### Before:
```
	freebies = list(/obj/item/weapon/reagent_containers/food/drinks/coffee, /obj/item/weapon/reagent_containers/food/drinks/tea, /obj/item/weapon/reagent_containers/food/drinks/h_chocolate)
```
#### After:
```
	freebies = list(
		/obj/item/weapon/reagent_containers/food/drinks/coffee,
		/obj/item/weapon/reagent_containers/food/drinks/tea,
		/obj/item/weapon/reagent_containers/food/drinks/h_chocolate
		)
```

## Why it's good
Less confusion on where to redeem some vouchers, easier to read lists for those trying to work with vouchers. Note that this doesn't provide any new sources of vouchers, just makes things a little more understandable for folks looking at these things and using them for the first time. Both players and coders.

## Changelog
[tested][tweak]
:cl:
 * tweak: Changed some free item voucher descriptions.

### CODE REVIEW

**Comment by BomberBro** [comment]
The glowing voucher should stay as-is, the description feels way too on the nose.

**Comment by jwhitak** [comment]
It is on the nose because I am an idiot. Early on in my playing history, I thought vendomats were any vending machine. Why I thought that? I'm not sure. I wish to help future idiots like myself from standing at a Getmore wondering why the glowing voucher doesn't work. It's a vendomat, right?? It made me think vouchers were broken for *years*.

**Comment by PrimeDSS13** [comment]
feels super out of place, theres gotta be a better way to go about this

**Comment by WindowsErrors** [comment]
United Kingdom in 1836
Shut down the only machine parts factory in the world

**Comment by BomberBro** [comment]
Somebody not understanding what a glowing voucher is and thus not being able to use it is perfectly lore-friendly though. It's already directly called "Vendomat", the joke item hopefully doesn't need THAT much instruction.

**Comment by jwhitak** [comment]
So be it, my two Lords Grape. I will leave in my change to capitalize the name of the machine but I will remove the second sentence. Fair?

**Comment by BomberBro** [comment]
Yeah the capitalization makes it more clear that it's referring to a specific thing without being too overt, looks good.

**Comment by jellyveggie2** [comment]
>I thought vendomats were any vending machine. Why I thought that? I'm not sure.

Blame the wiki for this one:
vendomat
http://ss13.moe/wiki/index.php/Guide_to_Advanced_Construction#Machines

**Comment by pedr69** [comment]
the circuit board is also called vendomat too, at least in the soldering menu when you're making them

**Comment by jwhitak** [comment]
I have grudged the wiki name. Later I may grudge the circuitboard name and soldering iron entry too.

**Comment by Kurfursten** [comment]
All of those entries are probably my fault, I think I always thought of all vendors as vendomats and I wrote the wiki page and I wrote the soldering iron. Just a symptom of being around a long time.

**Pull request merged**
