### PR TITLE
Hologram Projector hotfix

### LINKED ISSUE #33415: Hologram Projector interraction as a pAI is a complete mess
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
0a6bf586f84cca1b145e82451b6c808be61cedcb

# Description
Hologram projector when slotted in as a pAI has extremely buggy behavior and some other oddities
-Hologram doesn't inherit the pAI's name
-Upon reverting, the pAI player gets permanently placed into a copy of the pAI that's actually a simplemob(?) on the spot where they reverted instead of going back into the pAI device.
-pAI holograms get the hologram rules system message (don't harm humans without consent), they should really just follow their orders and directives instead.

### PR DESCRIPTION
**Pull request by adacovsk**
[hotfix]

## What this does
This might fix the issue where the pAi spawns two devices... I am not sure, unable to test it. It should take care the rest of the issues though.

## Why it's good
Closes #33415

## Changelog

:cl:
 * bugfix: Hopefully fix hologram projector issues

### CODE REVIEW

**Comment by Kurfursten** [comment]
This won't fix that problem. The problem is that the pAI itself is a mob inside the pAI item. After reverting to pAI form you need to put the pAI mob back into the pAI item.

**Comment by adacovsk** [comment]
> a mob inside the pAI item

```
/obj/item/device/hologram_projector/remove_pai()
	var/obj/item/device/paicard/P = integratedpai
	P.pai = holoperson
```
would this work? I can't test it

**Comment by Kurfursten** [comment]
I don't think that will do it, but maybe I just haven't looked closely at it enough. Either way, I would say don't worry about it - just wait until you can get to a place where you can test. In the grand scheme of things, if it's broken a couple more days it won't end the world. We have broken stuff all over.

**Comment by adacovsk** [comment]
>just wait until you can get to a place where you can test.

Problem is I can't log into a guest account and join my local server, not sure why. Just says connection failed when I try to join as a guest.

**Comment by Eneocho** [comment]
>Problem is I can't log into a guest account and join my local server, not sure why. Just says connection failed when I try to join as a guest.

You probably have Safe or Ultrasafe on the localhost security level.
I think you can test it without needing a second account. Turn yourself into a pAI via admeme powers then view the player info and humanize without deleting the previous mob.

**Comment by adacovsk** [comment]
>have Safe or Ultrasafe on the localhost security level.

nope, still does not work

**Comment by adacovsk** [comment]
okay, figured it out, now can test

**Comment by adacovsk** [comment]
Should be completely working for pAIs now

**Comment by Kurfursten** [comment]
Yes, just on the face of things, this code looks much more like it will work

**Pull request merged**
