### PR TITLE
Prevents Nuke Disk From Being Lost in Nullspace

### LINKED ISSUE #14033: You can use a Morph Mask to hide the Disk forever
A simple guide to fucking over the nuke cops
1. Inexplicably get hold of a morph mask whilst the nuke cops are busy masturbating and discussing strategy
2. Hold nuke disk in your hand
3. Wear mask

Disk gets sent to nullspace with your body and there is no way the cops can get a hold of it again. Even if they murder you they cannot force you back from being transmorgged. Its worse if the mask is cursed because now you can't even get the disk back. 

The disk should ideally prevent the mask from working or get spawned on the station somewhere and not sent to nullspace.

### PR DESCRIPTION
**Pull request by Shadowmech88**
The disk now checks whether it can get a turf under it, so if it ends up in nullspace without being deleted somehow, it'll respawn itself.
Fixes #14033

### CODE REVIEW

**Comment by Shadowmech88** [comment]
@N3X15 should I close this in favor of #14047?

**Comment by PJB3005** [comment]
It's a nice catch all because that's far from the first and far from the last bug that can cause disk bluespacing.

**Comment by Shadowmech88** [comment]
That's what I thought, but N3X15 said in the Discord that he'd prefer if we just figure out why the disk is being nullspaced and fix that on a per-case basis rather than use this.

**Comment by PJB3005** [comment]
This won't make disk nullspacing any less apparent and it basically even has an alarm bell.

**Comment by Exxion** [comment]
Should log it specifically though

**Comment by Shadowmech88** [comment]
How? I'm not familiar with logging.

**Comment by Exxion** [comment]
To be honest, I'm not particularly, either
In this case, I think just do `world.log << ` (some message about the nukedisk having gotten nullspaced)
We have so many different logs, though, I'm not even sure

**Comment by Shadowmech88** [comment]
Logging added.

**Comment by N3X15** [comment]
`message_admins()` would be a better bet, since it goes directly to admins and is also logged to file.

**Comment by Shadowmech88** [comment]
Done.

**Pull request merged**
