### PR TITLE
Adds trader vends to all maps

### PR DESCRIPTION
**Pull request by Probe1**
also renames it from _Jew Vend_ .

https://github.com/d3athrow/vgstation13/pull/13381

### CODE REVIEW

**Comment by Ephx1** [comment]
annudah shoah

**Comment by Intigracy** [comment]
But

The Jewvend

How could you

**Comment by Probe1** [comment]
I left in the none too subtle dialogue at least.

**Comment by gbasood** [comment]
Tongue in cheek is more fun than bludgeoning people with it imo

**Comment by Probe1** [comment]
Exactly.

**Comment by Durgen** [comment]
lame, change the name back

**Comment by SonixApache** [comment]
name it back to jewvend

**Comment by Shadowmech88** [comment]
>also renames it from Jew Vend .

*I wonder who could be behind this...*

**Comment by Intigracy** [comment]
The goyim know, shut it down.

**Pull request merged**
