### PR TITLE
Removes hardmapped lowered chances of medical and weapon safe spawners

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Did someone say safe powercreep?
:cl:
 * tweak: Medical and weapon spawners for the vault safe no longer have a lower chance of appearing.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
In favour of this if and only if it goes with an administrative crackdown on safe rushers

**Comment by SonixApache** [comment]
better solution; remove loot spawning from the station safe altogether, make it start open (or just put the stuff form the crates and fridge in there)

**Comment by Probe1** [comment]
@SonixApache I added stuff to safes because people bitched there was nothing worthwhile in safes.  You can't win either way.

**Comment by utilitas-** [comment]
wall-mounted secure safes and all the other safes already get zero (0) and I repeat zero (0) usage, why the fuck would this safe be any different? they absolutely should start with shit in them.

**Comment by Probe1** [comment]
Unrelated but you just gave me the perfect feedback for the rushing the spare PR.

**Comment by Probe1** [comment]
image
random feedback

**Comment by SonixApache** [comment]
Free guns for greyshirts and giving people incentive to break into the vault (while not giving sec incentive to stop them) is a really bad move.

**Comment by boy2mantwicethefam** [comment]
from my experience greyshirts breaking into the vault were always arrested if noticed tho

**Comment by Probe1** [comment]
Custom vote started by Probe1.
**Should the stations safe have an equal chance of spawning items from the weapon and medical loot table as the other categories or should it remain at a 50% chance?**
Click here or type 'vote' to place your votes.
You have 60 seconds to vote.

Vote Result: 
**Equal weight won with 7 votes.**
	Reduced Chance of Weapons and Medical supplies had 0 votes.

**Comment by boy2mantwicethefam** [comment]
Also as a note, several maps already do have guaranteed spawners (roid, bagel, snaxi for example) and the PR makes the spawner guaranteed for the other maps

**Comment by SonixApache** [comment]
\>even *more* free guns for assistants
great

**Comment by Probe1** [comment]
They aren't free, people pretty overwhelmingly approved of the idea, and lets be frank when I coded this I literally just made some random decisions based on my gut about the balance.  It's not like I agonized myself over it.

If this sucks then we can change it nothings final.

**Pull request merged**
