### PR TITLE
Remove a disgusting line

### PR DESCRIPTION
**Pull request by ShiftyRail**
I expect this to be tagged as file cleanup (& speedmerged)

:cl:
- rscdel: Removed a line when you tried to fart when you had no ass anymore

### CODE REVIEW

**Comment by ShiftyRail** [comment]
[why] Because this has absolutely no reason to be here

**Comment by Duny-** [comment]
Not gonna lie I am worried that you even considered this could be sexual in nature

**Comment by ShiftyRail** [comment]
I never considered this sexual, I considered it disgusting
The fact remains this was added as such : 
image

**Comment by Duny-** [comment]
>remove a fetish line

**Comment by MadmanMartian** [comment]
>Duny

**Comment by MadmanMartian** [comment]
I apologize for this, but this may need a changelog

**Comment by ShiftyRail** [comment]
The speedmerge thing was a joke actually
Let this wait a few days and we'll see, if it has too many downvotes I'll hide it

**Comment by MadmanMartian** [comment]
too late

**Pull request merged**
