### PR TITLE
Abandoned mining crates now have a dusty look

### LINKED ISSUE #23490: You can't emag open abandoned crates in the asteroid
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
106e9d17accd7614718b17a92a2df0e547522cab

# Description
I had a emag, found an abandoned crate while mining, couldn't emag it open.

# Steps to Reproduce
1- Find a abandoned crate while mining
2- Get an emag
3- Try the emag the crate
4- Fail

# What you Expected

Goodies

# What Actually Happened

Dissappointment

### PR DESCRIPTION
**Pull request by DeityLink**
image
I guess it's less rusty and more dusty

:cl:
* imageadd: Abandoned mining crates now have a dusty look.

### CODE REVIEW

**Comment by SonixApache** [comment]
those crates need some serious polishing, they don't even change icon states when unlocked and there's not much worthwhile in them

**Comment by ghost** [comment]
emags should just explode them immediately instead

**Comment by ghost** [comment]
> emags should just explode them immediately instead

maybe a 50/50 chance instead of the default 1/10

**Comment by DeityLink** [comment]
> those crates need some serious polishing, they don't even change icon states when unlocked and there's not much worthwhile in them

Neither do other crates. You're thinking of the green led maybe but in this case it's easy to assume that its battery ran out decades ago. What matters is that they change sprite when open. You can just click them anyway to see if they are unlocked.

> emags should just explode them immediately instead

a pair of shorts, a painting, etc. The best thing you can get is a stunbaton and you can get better tools more reliably as an antag anyway. Let them have their "treasure".

**Comment by BomberBro** [comment]
Emagcreep bad.

**Comment by DeityLink** [comment]
> 
> 
> Emagcreep bad.

it's a fockin secure crate, the only reason it doesn't work currently is that secure crates have a snowflakey emag check in their attackby() instead of a proper emag_act(). It's basically a bugfix with a sprite on top.

**Comment by DeityLink** [comment]
Ok my bad, turns out you can already emag them open lol, that issue was outdated. Guess it's just a spriting PR then.

**Comment by ghost** [comment]
Iron does not rust in space, muh autism.

**Comment by DeityLink** [comment]
> 
> 
> Iron does not rust in space, muh autism.

fixed

**Pull request merged**
