### PR TITLE
Defficiency update

### PR DESCRIPTION
**Pull request by Duny-**
- Added a metric fuckton of firelocks.
- Added missing wire to Toxins Testing Area.
- Added a unique area for the old medbay to match the other abandoned areas and avoid confusing alarms for the engineering crew.
- Fixed HoP's office's area.
- Added a medical laptop and folders to virology.
- Warehouse shutters in cargo should now close the right angle. Map now playable.
- Added a bunch of intercoms in frequented areas.
- Replaced the abandoned medbay chem master which had a broken icon with a machine frame. Thought I had already removed this long ago.
- Added a whole bunch of newscasters, mostly in hallways.
- Added giant warning signs at the entrance of the abandoned stuff to show that they are not shielded against radiations.
- Added a few console screens to Tech Storage. As suggested here https://github.com/d3athrow/vgstation13/issues/4434

Fixes https://github.com/d3athrow/vgstation13/issues/7843, fixes https://github.com/d3athrow/vgstation13/issues/7740, fixes https://github.com/d3athrow/vgstation13/issues/7571, fixes https://github.com/d3athrow/vgstation13/issues/7545, fixes https://github.com/d3athrow/vgstation13/issues/7674, fixes https://github.com/d3athrow/vgstation13/issues/7675, fixes https://github.com/d3athrow/vgstation13/issues/7712, fixes https://github.com/d3athrow/vgstation13/issues/7729, fixes https://github.com/d3athrow/vgstation13/issues/7405, ~~closes https://github.com/d3athrow/vgstation13/issues/7441~~

### CODE REVIEW

**Comment by CptWad** [comment]
:pray: thank you for fixing that wire :+1: :+1: :tada: :clap:

**Comment by 9600bauds** [comment]
appreciate

**Comment by DrCelt** [comment]
How does this close #7441

**Comment by Duny-** [comment]
Because otherwise it will never get closed, and everyone is done talking.

**Comment by DrCelt** [comment]
Wow
Tyrannical.

**Comment by Duny-** [comment]
I'm afraid I can't let you call me that Dave.

**Comment by DrCelt** [comment]
I'm going to remake that issue if you close it gayboy, what will you do then?

**Comment by Duny-** [comment]
Copy/paste my last post. Hopefully you pick a less childish title this time.

**Comment by Skullyton** [comment]
Where's the autolathe, duny?

#7535

**Comment by Kurfursten** [comment]
:+1: But would like pictures of the distribution of radiation signs in one area just so we know about how much frequency they have been placed with

**Comment by Duny-** [comment]
@Skullyton I-I didn't add an autolathe because you can build one with what's in the RnD room you lazy fag

@Kurfursten I added one big ass giant sign at every entrance and everywhere I thought someone could enter and think "oh this area might be shielded". The shielded parts are already designated clearly by the markers on the ground in maintenance so I don't think being super thorough is necessary. Plus I don't want to spam the sign everywhere.

**Comment by Skullyton** [comment]
Well guess what, Duny

All the other maps have autolathes in R&D at roundstart, Duny

Therefore it's an issue, DUNY

WHICH ARE THINGS WE'RE TRYING TO GET CLOSED AND SORTED, DUNY

**Comment by Duny-** [comment]
All other maps also have DIFFERENT SHAPES AND ITEMS everywhere, I think we should fix this by copy/pasting defficiency into all other maps fam tbh

**Comment by 9600bauds** [comment]
desu I think the roundstart chemmaster is pretty dumb too, why remove the autolathe just because fuck your roundstart machinery but also add an even more powerful roundstart machinery?

**Comment by Duny-** [comment]
An autolathe is easy to build and there is literally everything you need in RnD, not in chemistry. But fine, I'll add an autolathe and remove all that's needed to build one in RnD if it hurts your autism so much to have to take 30secs to build an autolathe so you can rush research the same exact boring way every round (which is somehow okay and not annoying at all to people).
Next update though, takes me 10 minutes to open the map, 10 minutes to compile on this fucking piece of shit of a computer. ;_;

**Comment by CptWad** [comment]
@Skullyton There are more than one autolathe boards in maint and it aint that hard to make.
Ill back duny up for once. RnD is overpowered anyway

**Comment by 9600bauds** [comment]
The thing is that the autolathe isn't even overpowered in and of itself
In fact it's pretty much completely harmless save for the circular saw, and we're removing it in favor of the chloral and mutagen dispenser

**Comment by DrCelt** [comment]
Isn't there an autolathe in cargo?

**Comment by 9600bauds** [comment]
Yes, but cargo is fucking braindead.

**Comment by CptWad** [comment]
Then break in. If theres no cargo then it wont be an issue
if they are dumb then ask to be let in to print what you need
If they are dicks about it, you always can offer them guns then forget to deliver

**Pull request merged**
