### PR TITLE
TG's dice

### PR DESCRIPTION
**Pull request by unid15**
dice bag spawns in the library

service borgs have all dice

also dice bag sprites

### CODE REVIEW

**Comment by Riukanojutsu** [comment]
I support this.

**Comment by Riukanojutsu** [comment]
Will the Rapid-Service-Fabricator be able to dispence the full thing too?

**Comment by Unfit** [comment]
Yes it spawns the dice pack with all the dice in it

**Comment by Riukanojutsu** [comment]
10/10 we real DnD now.
gotta write a new guide though

**Comment by ComicIronic** [comment]
Could you change it from a pill bottle as well?
You can ask for a dicebag sprite in the IRC (or make one yourself), but the fact that it's a pill bottle with the base sprite has always bugged me.

**Comment by Unfit** [comment]
yeah it's already got a dicebag sprite straight from tg
forgot to include that in description

**Pull request merged**
