### PR TITLE
Revert "Merge pull request #35421 from boy2mantwicethefam/no-plushie-paracetamol"

### PR DESCRIPTION
**Pull request by brndd**
#35421

This PR with exactly 50% votes (when discounting repobanned and permabanned voters) was merged after only two days of discussion after its creator pinged collabs on Discord asking for it to be merged. I believe this is bad practice, and this change's fate should not have been decided so soon.

:cl:

 * rscadd: Plushies will once again give paracetamol when "hugging" players.

### CODE REVIEW

**Comment by brndd** [comment]
I will post my thoughts on it in comments to not soapbox in the OP.

This PR was a grudge nerf to a feature that had existed on the server for less than two days when the PR was opened. Its core argument is that hypothetical powergamers could hypothetically abuse this feature. There was no evidence of this actually happening in practice. The PR was therefore either not made in good faith, or was fundamentally trying to solve an issue that does not exist.

It also invoked 44 comments worth of discussion which was not allowed to run its course before the PR was merged.

**Comment by Securitymain** [comment]
muh permabanned/repobanned players

Just because adacovsk is no longe rallowed to post PRs does not make him not be a member of the community
Just because I'm permabanned does not make  not someone who hasn't played thousands of rrounds and knowing what's good for the server

**Comment by wotisjanitor** [comment]
Yaaaaaaaaaaaaawwwwwnnnnnnn🥱🥱🥱🥱🥱🥱🥱🥱🥱🥱

**Comment by Pastamadness** [comment]
> muh permabanned/repobanned players
> 
> Just because adacovsk is no longe rallowed to post PRs does not make him not be a member of the community Just because I'm permabanned does not make not someone who hasn't played thousands of rrounds and knowing what's good for the server

That's right. You don't.

**Comment by wotisjanitor** [comment]
This wasn't even the core argument by the way, did you actually not read anything people were saying to you?

**Comment by d3athrow** [comment]
Toys shouldn't give painkiller from hugging it

**Comment by boy2mantwicethefam** [comment]
To note I didn't ask that it should be merged, I asked to either merge or close it at the collab's discretion because it was still a pretty 50/50 thing.
It's not a grudge nerf, I mentioned it is not a grudge nerf, I am ambivalent over plushies, I don't love 'em nor hate 'em. I just don't think paracetamol from plushies is a good idea in its implementation, the addition of it also had no sufficient reason to have it in the first place, most players weren't even aware it was a thing.
A big chunk of the comments were me defending the PR and arguing why it should be merged because I have a tendency to over-detail and respond to posts which I admit is not necessarily a good thing, but the argument has kinda run out of steam after that day, the last comments that were mentioned were already accounted for and addressed in earlier posts... at least most of them.

Come on man you're fixating too much over it, I know you have a personal stake in it because you made the plushie PR but you're arguing with zero unwillingness to consider other arguments, zero compromise, all "my way or the wrong way", this isn't a good way to approach pull requests and it will burn you out sooner or later when another PR rolls around messing with your stuff, I know I'm likely stubborn myself but I try to do stuff for the betterment of general gameplay (at least these days, I think in the past I was more concerned with "what was funny", and I'm going to admit that as much as I like taking jabs at how "collabs refused to save the station from the female captain menace" I might not want to do that PR these days), I genuinely recommend playing cool videogames or breathing some fresh outside air to cool, you're stressing out over it and I feel that, I did that too over some pull requests and it helped to detach a little from the web and play some cool games instead, I do not intend to do anything else with plushies, I just thought paracetamol from plushies was a bad idea for a bunch of reasons that I sum up to:
- You can apply the painkiller to yourself with no help, preparation or consumption indefinitely and if you strip out all the fluff you get an infinite painkiller item that's better than hugs (you can self-apply it and you don't have to shake people up to use it on them) that anyone can carry and it's widely distributed on the station for a small requirement (coins).
- - If it was a Science item called a "Pain Numbing Device" that had a 1:1 effect it would likely be downvoted for another bunch of different reasons and probably require other balance changes like "this has a cooldown of X seconds" despite a significant material cost, people would likely complain it gives less reason to visit Medbay, that people can powergame with it and that hugs can already do it.
- - It really does have a powergame-y potential (I have a tendency to notice that because I am gameplay-minded, I try not to neglect roleplay) but I tried to not focus on this aspect not just because it was requested not to but because multiple people made a good point about "who powergames this?"
- My personal belief that fluff stuff should remain fluff and people should do cute stuff with the cute toys because of their roleplay potential and not because of a mechanical reward, it's cooler that way.

I do not wish to make any further posts related to this. I am legitimately concerned about your feelings and I do not want to make you feel stressed out if I can help it, I know that feel. I do not intend to say this in a condescending way.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
there are a million ways to powergame
did anyone abuse this mechanic and dominate everyone else with it during the time it was live?

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
also to repeat from before:

> painkillers should be adjusted to have the amount of pain reduction depend on the amount of painkillers in the system (right now its binary if you have a given painkiller in your system you get the "full effect" for that chem and it only stacks across the variety of painkillers rather than volume of a given painkiller) (in other words 1u of tramadol and 1u of opium will kill more pain than 50u of opium)
> if you did that you could scale the amount of painkillers per hug based on the strength of the effect you want

That way they could give a little painkilling effect but not as much as making a bunch of tramadol at chem and swigging it down

**Comment by brndd** [comment]
> You can apply the painkiller to yourself with no help, preparation or consumption indefinitely and if you strip out all the fluff you get an infinite painkiller item that's better than hugs (you can self-apply it and you don't have to shake people up to use it on them) that anyone can carry and it's widely distributed on the station for a small requirement (coins).

> It really does have a powergame-y potential (I have a tendency to notice that because I am gameplay-minded, I try not to neglect roleplay) **but I tried to not focus on this aspect** not just because it was requested not to but because multiple people made a good point about "who powergames this?"

(emphasis mine)

This is a strange distinction to make. You say you're not focusing on its powergame potential, but these are the same argument though? The fact that it mechanically gives you 10 seconds of paracetamol every 10 seconds seems to me to be a powergame concern, because abusing features like this is powergaming and therefore only powergamers would do it.

That's not to say it isn't a valid concern, but like I said before, it's something that can easily be addressed if it actually proves to be a problem. Addressing it beforehand would be daft, and the same argument could be used to justify removing many other mechanics from the game.

-----

I also agree with squaddie above in that the way painkillers in general work right now is stupid and they should be made more nuanced, but that's a very tangential issue.

**Comment by Eneocho** [comment]
I insist. They should've been changed to dispense paracetamol only once a minute, all other hugs just being flavour, that way the funny "hah, he survived the nukies thanks to the fumo" situation is preserved, and the mechanic is not powergameable (it wasn't gonna be powergamed when better solutions are available, but I digress).

**Comment by Pastamadness** [comment]
> I insist. They should've been changed to dispense paracetamol only once a minute, all other hugs just being flavour, that way the funny "hah, he survived the nukies thanks to the fumo" situation is preserved, and the mechanic is not powergameable (it wasn't gonna be powergamed when better solutions are available, but I digress).

That's not really funny

**Comment by Eneocho** [comment]
I happen to disagree. The sheer concept of surviving a rocket to the ass cause you were hugging the clown plushie is funny.

**Comment by ShiftyRail** [comment]
fwiw, 3-4 of the downvotes on this PR are sockpuppet accounts.

**Comment by Blithering** [comment]
People getting really autistic about anime dolls? What is this, reality? 
My entirely not serious solution: select your favourite tohou in character setup, paracetamol only dispensed from matching fumo.

**Comment by SonixApache** [comment]
My entirely not serious solution: fumos only deliver paracetamol when used on others

**Comment by brndd** [comment]
> My entirely not serious solution: fumos only deliver paracetamol when used on others

The fact that the PR being reverted here removed that functionality too instead of just the self-hugging is part of why I believe it was grudgecode.

**Comment by wotisjanitor** [comment]
IT WAS GRUDGECODE THERES NO OTHER REASON

**Comment by SonixApache** [comment]
make a new PR that re-introduces the hugging-others paracetamol thing (limit it to 1u) and you will gain my immediate 👍

**Comment by brndd** [comment]
Why should it be limited to 1u when regular hugs aren't?

**Comment by SonixApache** [comment]
mostly to prevent paracetamol farming, but the limit probably doesn't matter. Forget the limit.

**Comment by OfficialGasnigAccount** [comment]
Idea to keep the functionality without it being stupid.
Add a new chemical called dopamine. Dopamine is only created inside spacemen and will replenish itself slowly. When a certain action is performed a small amount of dopamine is released and will have a mild healing and painkilling effect. You can get this dose of dopamine from getting hugged, hugging a plushie, eating food that's better the vending machine slop, getting a paycheck, drinking alcohol, smoking a cigarette. This way everyone can have their vice for what they go to for surviving a stressful situation. One player after an explosion will hug their plushie for comfort, another player will take out a cigarette and light one up. Everyone is happy.
You can't spam it because the storage is small and is replenished slowly, the positive effect of it so small that calling it powergaming is just silly. Instead it would give people a reason to care about all this barely used side-content like packs of smokes and eating well instead of slopping up raisins from a vending machine. There is also that Valentine's day chemical that makes you explode when hugged, you can make that more useful by having the trigger be dopamine which can be activated in many different ways instead of one that is rarely used.

**Comment by Eneocho** [comment]
If you're going through the once every 10 exact seconds hassle for the paracetamol farming, you can just meander to chemical and demand a pillbottle's worth of tramadol (or oxycodone if you're feeling fancy).

**Comment by kacurasuo** [comment]
my dude I don't even necessarily disagree with you but it was commented on and merged by the host
we do be pretending this is a democracy but it's more like a constitutional monarchy

**Comment by Killette2** [comment]
I like the idea of it being once every minute or more with the others being flavor
Another solution is to have a magic variant that is rarer and has the above stipulation or something similar, the magic one wouldn't be obtainable outside of vaults, admins, or xenoarch home digsites

A 3rd solution is to give it an alternative chemical entirely, where this chemical may have a similar effect and reduced strength or it might have a downside like if you use too much you turn into a weeb and fat wearing the schoolgirl clothes

**Comment by Volttekka** [comment]
As a fumo enjoyer, I'm perfectly fine with the plushies having no actual effect, especially since that also shuts up the people bitching about it giving a tangible benefit.
Fumos exist simply to give me, the player, and not my character, peace of mind during a round.

**Comment by Kurfursten** [comment]
I think the hug chem is pretty harmless, I also don't think it's at all something worth fighting for.

That said, Pomf made his opinion as server host clear.

**Pull request closed without merging**
