### PR TITLE
It's DEGREES Celcius

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by clusterfack** [comment]
Yeah someone's git program edited to this for some reason

**Comment by N3X15** [comment]
Yeah, I think that file was set to UTF-8 and someone opened it in DM and mojibaked it.  I had it correct originally.

ALT+0176 if someone has to rewrite that again.
(Don't do that in firefox or you'll die in real life)

**Comment by Probe1** [comment]
We did it boys

**Comment by Shadowmech88** [comment]
Don't the degree symbols on the solar controls also need to be fixed?

**Pull request merged**
