### PR TITLE
THANKS NOT DUNY

### LINKED ISSUE #8146: Defficiency's disposal mailing system
it's pretty broken. (NOTE: i tested this on the test server)

when using a destination tagger on a parcel, using the following tags:

**_come back to cargo:**_
engineering
CE office
RD office
library
theatre
telecomms
mechanics
telescience

**_wrong destination:**_
cargo bay: goes to mechanics
chemistry: goes to CE office

all the rest seems ok.

side note: can't understand why there is a "Disposal" tag.

### LINKED ISSUE #8405: Double windoor on an unused part of deff.
Left windoor of the brig kitchen is double.

### LINKED ISSUE #8406: Deff cryo is fucked.
THANKS DUNY.

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes #8146 - Moved default tagger locations to map datums and used this to make telecommunications and telescience not show up in the tagger, because they were too cramped.
FIxes #8406 
Fixes #8405

### CODE REVIEW

**Comment by ghost** [comment]
Shit, I was just about to do this after reading the thread

God knows how a double windoor got there, the only things I touched in the brig was the stools.

Heck, the mancrowave didn't even start with a console and the bloodbags were everywhere. Something's odd.

**Comment by ghost** [comment]
There's more things odd, the volume pump from cryo to waste is missing as well, at least on the version of the map I just pulled

**Comment by CptWad** [comment]
Sometimes dreammaker mapmaker does dumb bullshit and you gotta catch it early or else you will never catch it

**Comment by ghost** [comment]
There's more stuff missing than that.

> Window above cryo is missing
> Firelock is missing from surrounding cryo

**Comment by Duny-** [comment]
@Skullyton pls stop making things go missing from the map, do that to box instead so we can collect boxbaby tears

**Comment by PJB3005** [comment]
Alright @Skullyton I fixed those issues.

**Comment by PJB3005** [comment]
Alright once Travis finishes this should be ready to be merged.

**Comment by ghost** [comment]
@Duny- Please

**Comment by Duny-** [comment]
bluethumbsup

What Skullyton you don't like boxbaby tears?
Wait. You ARE a boxbaby aren't you? Disgusting.

**Comment by ghost** [comment]
@Duny- please, I'm more of a fan of meta and deff

I like my exploring

ˢᵒʳʳʸ ᵃᵇᵒᵘᵗ ᵐᵒᵈᶦᶠʸᶦᶰᵍ ʸᵒᵘʳ ᵐᵃᵖ, ᶦᵗ'ˢ ʲᵘˢᵗ ʸᵒᵘ ʷᵉʳᵉ ᵗᵃᵏᶦᶰᵍ ˢᵒ ᵈᵃᵐᶰ ᶫᵒᶰᵍ ᵃᶰᵈ ᴵ ʷᵃᶰᵗᵉᵈ ˢᵒᵐᵉ ᵖʳᵃᶜᵗᶦᶜᵉ

**Comment by Duny-** [comment]
It's okay I'm just going to change what I dislike when I get back like a good lil despot. I'm in a really tight spot IRL currently and all I have is my shitty laptop that takes 10 minutes just to open the map so I just stopped updating deff until it's sorted. At least vox raiders stopped breaking everything which is breeeetty nice.

**Comment by Duny-** [comment]
Also I might had more abandoned shit to explore :^)
Deff supremacy

**Comment by CptWad** [comment]
> >might

You WILL add more shit to explore
It will never end

**Pull request merged**
