### PR TITLE
Autodrobe vox 2

### PR DESCRIPTION
**Pull request by falcon2346**
## What this does
Makes more Autodrobe clothes fit vox. This PR covers the Megaman outfit, Clownpiece outfit, Jester shoes (Note that the uniform and hat existed, although the hat sprite was incorrectly named, which I have fixed so it displays properly), Maid outfit, and Patriot outfit. This also includes the suit and uniform for Bridge Officers as I was notified that they didn't fit and it was convenient to include it, as well as a fix for the HoS winter coat because apparently I just screwed it up when I made it.

Sprite Sheet

## Why it's good
More outfits fit vox. Most of these already fit bugs, might as well bring them to vox as well.

## How it was tested
The images of the sprites were taken in-game to verify that they worked.
[sprites]

## Changelog
:cl:
 * imageadd: Added new sprites.

### CODE REVIEW

**Comment by SonixApache** [comment]
start working on the fat vox sprites

**Comment by Eneocho** [comment]
Can vox wear thee banana and monkey suit?
On that note, we need a vox chicken and a space credit suit, for the vox equivalent of the monkey and banana suits.

**Comment by falcon2346** [comment]
> Can vox wear thee banana and monkey suit? On that note, we need a vox chicken and a space credit suit, for the vox equivalent of the monkey and banana suits.

I sprited the Monkey Suit in my previous PR for this, I have not gotten around to the banana yet. If I ever get done with all the autodrobe stuff I'll make a vox chicken and credit suit but it'll probably take me a hot minute.

**Review by west3436 — APPROVED** [review]

**Comment by Eneocho** [comment]
You could probably just recolor the regular/pomf chicken suit

**Pull request merged**
