### PR TITLE
Removes fun

### LINKED ISSUE #7970: MoMMIs can polyacid smoke from within vents
and the smoke spawns on the turf above the vent ;^)

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #7970

### CODE REVIEW

**Comment by gbasood** [comment]
#7970

**Comment by 9600bauds** [comment]
Thank you I was trying to find that

**Comment by AutismSpider** [comment]
long over do.

could do lot of dumb shit in the pipes form using the hand tele link to death trap to bombs.

**Comment by ComicIronic** [comment]
Some of these make sense, like the foaming ones, but why should an EMP pulse be blocked by pipes? 

Also,  I will have a bone to pick with the way you've done this, it would be better to implement a generic system for finding if a reaction is trapped because this will affect more than ventcrawling.

**Comment by MercuryDoll** [comment]
Metallic pipes make for pretty decent electromagnetic shields, they're not perfect but they drain a lot of juice out of the pulse.

**Comment by Shadowmech88** [comment]
> Metallic pipes make for pretty decent electromagnetic shields

I doubt they'd be better than one-meter-thick metal walls, which don't seem to block EMPs at all.

**Comment by 9600bauds** [comment]
> this will affect more than ventcrawling.

What will it affect besides ventcrawling

**Comment by MercuryDoll** [comment]
> one-meter-thick metal walls

Technically, one tile is considered to be 2m by 2m, but the perspective of sprites in SS13 is all over the place anyway so there's no way to know how thick the walls would actually be.

**Comment by Shadowmech88** [comment]
I would hope they're at least thicker than the walls of a pipe that's no larger than a spessman's arm.

**Comment by ComicIronic** [comment]
> What will it affect besides ventcrawling

For a start, mecha.
Picture this: you load a buddy's backpack with boxes of napalms, flashes, foams, etc, send him off in a Gygax with a closed air supply, and remote detonate the grenades when he sanics into range. This is currently totally doable.
Then we would have a similar issue for closets, cyborg rechargers, and so on and so on.

**Comment by 9600bauds** [comment]
Oh, I thought you meant the fix

**Comment by 9600bauds** [comment]
EMP in vents is kosher now, also fixed a potential server hang if someone called find_holder on a turf for some reason

**Comment by AutismSpider** [comment]
Flash bangs stun you as you vent.

**Comment by 9600bauds** [comment]
As you vent?

**Comment by AutismSpider** [comment]
i mean in the vent Flash bangs stun you like normal as mommi and as human base mob

**Comment by ComicIronic** [comment]
:100::100::100::100:
Perfect OOP implementation A+

**Comment by 9600bauds** [comment]
I have finally gitten gud
I can now start making increasingly controversial PRs until I meltdown

**Comment by ComicIronic** [comment]
No, I'm now going to start bugging you for systems reworks.
System to rework #1: inventory datums

**Comment by 9600bauds** [comment]
brb suicide

**Comment by AutismSpider** [comment]
@9600bauds Suicide after you fix this shit

**Comment by 9600bauds** [comment]
Yeah I had to fix a couple of things with flashbangs too

**Comment by Kurfursten** [comment]
> hotfix stays on NFD for three days

Isn't the whole point of having half of every coder be a contributor to avoid this?

**Pull request merged**
