### PR TITLE
New equation for threat

### PR DESCRIPTION
**Pull request by ShiftyRail**
[system]

See : https://docs.google.com/spreadsheets/d/1qnQm5hDdwZoyVmBCtf6-jwwHKEaCnYa3ljmYPs7gkSE/edit#gid=0

Don't hesitate to make a copy of the file and modify the parameters.
Essentially, a new equation for threat that uses a Cauchy distribution (https://en.wikipedia.org/wiki/Cauchy_distribution for those interested) rather than the old function of dynamic mode.

Cauchy law still allows for extremes to happen, although they'll be more less likey. Moreover, it is easier to tweak, and you could even implement something like players voting on the kind of shift they want.

image

For instance, if we want a peaceful shift, we can vote for "green" curve, whereas if we want a more rough shift, we can vote for the blue, in which high-threat scenarios will be more likely.

Share your thoughts and ideas

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I've been itching to do storytellers but it would be as easy as just making the threat values check for the round's storyteller
This PR is still a response to a very unlikely round that happened where 3 different round-ending antags spawned
Also not many of us are mathematicians and future coders will probably both be amazed and disgusted by the obtuse equation
+A for effort though, so I support it

**Comment by ghost** [comment]
Does not solve overlapping modes like blob / ops / cult / rev / malf. All this will do is introduce more quasi extended rounds while still allowing for turbo gunk from overlap.

**Comment by ShiftyRail** [comment]
That's untrue. Overlapping modes always require at least 60 threat. Which is much less likely to happen. 
In fact, 40-60 threat rounds will be a lot more more common, and this threat range only allows one round-ending faction.

On the other hand, rounds with <40 threat (ie, a single antag or so) will also be much less common. This means that "extended" will be rarer.

**Comment by ghost** [comment]
How is any of what I said not true when you just said it is?

**Comment by ShiftyRail** [comment]
Prior to that change : ~30% of the rounds _allow_ multiple antags to happen (not all of those will have it)
With that change : less than 10%, and can be further reduced to less than 5%

If what you request is that Cult + Ops should never be allowed to roll at the same time, then it's possible but it's not the way I want to do it.
Also "more quasi extended rounds" is incorrect, since 40-60 still allows for a single faction antag to appear or for a lot of traitors.

Also, for reference (not counting forced rulesets) : 

Cult + nuke ops happened 5 times
Cult + Malf AI happened 3 times
Cult + blob happened 9 times
Cult + rev never happened.

**Comment by ShiftyRail** [comment]
>future coders will probably both be amazed and disgusted by the obtuse equation

It's just a Lorentz distribution

**Pull request merged**
