### PR TITLE
mushroom local telepathy

### PR DESCRIPTION
**Pull request by toomykins**
This is code stolen from gheritt, against his will of course.
see #35148 for an explanation

:cl:
* rscadd: Mushroom men now have local telepathy (gheritt's code)

### CODE REVIEW

**Comment by d3athrow** [comment]
lol

**Comment by Kurfursten** [comment]
> people say words in library
> PR stolen

**Comment by brndd** [comment]
game_of_life

**Comment by CrazyAmphibian** [comment]
BUT WHAT ABOUT THE NAUGHTY BOOKS? HOW WILL I PLAY THIS 18+ SERVER WITH NAUGHTY THINGS IN IT?

**Comment by ShiftyRail** [comment]
Stolen valour. If you go ahead with this I expect you to be able to fix it

**Pull request merged**
