### PR TITLE
Make the posibrain directive more visible.

### PR DESCRIPTION
**Pull request by ShiftyRail**
This way, people will hopefully notice it.

:cl:

- tweak: The prime directive of posibrains is now more visible.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Mate you're better off just bugging Probe and hope he changes the silicon policy

**Comment by ShiftyRail** [comment]
When it's not broken, don't fix it.
The problem was apparently just visibility.

**Comment by SonixApache** [comment]
unnecessary
doesn't help secborgs anyway

**Comment by Probe1** [comment]
I'm not very sure what people want with the Silicon policy in this case.  It's clear what the rules are.  The player broke the rules.  We applied an appropriate silicon ban in response.

As far as this pull request goes it's just a formatting thing and as long as it is in line with other silicon notices I dont see any problems.

**Comment by FudgePucker** [comment]
They should be keeper, that way MoMMIs can make more MoMMIs

**Comment by DamianX** [comment]
If posibrains are to be considered as acting under silicon laws they should get the "show laws" and "state laws" verbs.
If you just send the one message, even if you make it `font-size: 300px ` it might just get lost in the void by BYOND.

**Comment by ShiftyRail** [comment]
This requires more effort, but alright

**Comment by DamianX** [comment]
It doesn't need to happen with this PR but I feel it's important to be consistent.

**Comment by Probe1** [comment]
@DamianX is absolutely correct.

**Comment by Kurfursten** [comment]
In any case, I see no harm in this as-is. Adding it to notes seems a wise step but could be separately added.

**Pull request merged**
