### PR TITLE
syndie laser gun + elitesyndie viscerator gun

### PR DESCRIPTION
**Pull request by SonixApache**
one viscerator gun spawns on one of the syndiesquad bomb spawners
nuke ops with the Energy loadout get the rifle
image

Additionally: renames chillbugs fired from a chillbuggun from hornet to chillbug

## Changelog
:cl:
 * rscadd: Nuclear operatives with the energy loadout now get a unique laser rifle
 * rscadd: Syndicate SpecOps now have access to a viscerator gun
 * imageadd: Laser rifle / viscerator gun sprites by Blithering!

### CODE REVIEW

**Comment by ManopolisJones** [comment]
>What's the uniqueness of the laser rifle, besides it's new sprite

Nevermind, after looking at the files change I see it's just a child of the laser rifle with a clever nod to both guns nu-com origins. 

If you'd forgive me for ideas guying you, I think if you wanted to do something unique for a syndicate laser rifle, you could make it so they can swap out the battery in the gun to reload it.

**Comment by Blithering** [comment]
On the subject of reloading, the energy loadout choice for nukies is woefully sparse, you get a laser (rifle now, vanilla gun currently), an ion carbine, and two don't fuck yourself over emp grenades. 
In comparison engineer loadout gets a combat shotty, a box of shells, mesons, welding goggles, toolbelt, three C4, an esword and advanced magboots.
I think to make it worth taking you could add two to three of the already existing energy magazines you randomly get from the patrolman's pedometer, which would allow for reloads in the field.

**Comment by Securitymain** [comment]
the field reload thing only adds TWO shots. Its kind of ass for how annoying they are to  get rn (and they arent even reusable)

**Comment by Dacendeth** [comment]
Does this just give every nuke ops team a viscerator gattling gun for free?

**Comment by Blithering** [comment]
> Does this just give every nuke ops team a viscerator gattling gun for free?

I would assume the mapped in one is in the syndie strike team (deathsquad) prep, rather than the nuke ops one.

**Comment by Kurfursten** [comment]
Yeah this is just the landmark called syndicate commando bomb, not the nuke ops bomb

**Pull request merged**
