### PR TITLE
You can now quick equip items like tools to plastic bag in belt slot

### PR DESCRIPTION
**Pull request by RFultra**
You can now quick equip items like tools to plastic bag in belt slot

### CODE REVIEW

**Comment by Riekland** [comment]
plastic bags can hold items like gloves, right?
If so, would it override the quick equip for equipping clothes?

**Comment by Intigracy** [comment]
See above question.

**Comment by RFultra** [comment]
Gloves still equip to hands first yes

**Comment by SonixApache** [comment]
@Intigracy you got your answer

**Pull request merged**
