### PR TITLE
Somewhat updates the contrib guidelines that no one reads

### PR DESCRIPTION
**Pull request by gbasood**
the most important update we will ever have

### CODE REVIEW

**Comment by Intigracy** [comment]
> - **Only submit PRs that are ready to be pulled.**  PRs that are not ready will be closed.

ha
haha
hahahahahahaha

**Comment by clusterfack** [comment]
Lol
>* Merging your own PRs is considered bad practice, as it generally means you bypass peer review, which is a core part of how we develop.

**Comment by gbasood** [comment]
@clusterfack Let me just self merge all my PRs then

**Comment by Imagebard** [comment]
I don't need to be a coder to see what's wrong with this.

**Comment by Probe1** [comment]
had to view the file to see where it even existed lol

**Comment by Probe1** [comment]
Duplicate it here if possible.

image

**Comment by gbasood** [comment]
what

**Comment by Probe1** [comment]
When we make an issue we're given that template we're supposed to fill out?

Do that for PRs.

**Comment by PJB3005** [comment]
We can't.

**Comment by gbasood** [comment]
@PJB3005 yes we can

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by PJB3005** [comment]
I stand corrected!

**Pull request merged**
