### PR TITLE
Malf fixes

### PR DESCRIPTION
**Pull request by MadmanMartian**
I noticed while testing that apparently malf are not supposed to be able to hack off-station APCs according to their introduction. This remedies that.

### CODE REVIEW

**Comment by SonixApache** [comment]
They *are* supposed to be able to hack them, but they don't count for the malf timer. It's probably better to just adjust the introduction.

**Comment by MadmanMartian** [comment]
Seems they do count to the malf timer on-station and off-station. I'll just rectify this.

**Comment by MadmanMartian** [comment]
So, every APC removal had a z level check, but not APC addition. This look better to you @SonixApache ?

**Comment by SonixApache** [comment]
Absolutely.

**Pull request merged**
