### PR TITLE
Fixes posibrains hearing deadchat

### LINKED ISSUE #11259: MMIs in mechs can see deadchat
#### Description of issue

MMIs inside mechs can see deadchat for some reason. They still communicate in exclusively IC.
mmi deadchat
This does not happen when the MMI or posibrain (I assume it'd work the same for both of them) is not in a mech.
mmi outside mech deadchat
#### Difference between expected and actual behavior

MMIs inside mechs become mediums between the realm of the living and the realm of the dead instead of just being regular shitters in mechs.
#### Steps to reproduce

Be an MMI
Get put into a mech
Have someone else talk in deadchat (while you're de-adminned)
#### Length of time in which bug has been known to occur

Not sure. I've seen it happen yesterday and the day before, possibly a couple of days before that.
#### Server revision

c246201cd4fa9c35fa42145a33488f45b49e72e6
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched for "mmi" "posi" "mech" and "dead"

### PR DESCRIPTION
**Pull request by Sprok0**
Why did no one fix this before, it was trivial

Fixes #11259

### CODE REVIEW

**Comment by Intigracy** [comment]
So putting it in the brain places the brain into the mech directly as opposed to the brain in the mmi in the mech?

Mech code sucks.

**Comment by Sprok0** [comment]
It puts both the MMI and the brain into the mech, but as separate objects, then shoves the brain back into the MMI when it's blown/ejected. I guess it's to allow the brain to relay moves to the mech or something,

**Comment by Intigracy** [comment]
I'll get in touch with you about your prize when I get home or tomorrow assuming you're not online when I finally get home

**Comment by clusterfack** [comment]
THIS is how it worked? No wonder it fucking broke. Your fix was pretty bad too, could just lead to the same problem somewhere else in the future. It should be checking something like stat instead.

**Comment by Intigracy** [comment]
Brains can be alive or dead though, and it's intended that "alive" brains
still be able to hear deadchat, just not when they're in mmis/posibrains.

**Comment by clusterfack** [comment]
No, that's fucking stupid

**Comment by Sprok0** [comment]
#10649 Here's where Celt introduced the bug, to allow decapitated heads/brains to hear deadchat

**Comment by Intigracy** [comment]
Thank mr celt of shitcode

**Comment by clusterfack** [comment]
Celts bugfixes causing more bugs, why am I not fucking surprised

**Pull request merged**
