### PR TITLE
Balloon Animals

### PR DESCRIPTION
**Pull request by Shadowmech88**
long_balloon
Adds long balloons.
Three boxes of long balloons can be obtained from a party crate.

ballanim
Adds balloon animals.
Long balloons can be tied into a variety of balloon shapes. So far the options are balloon dog, balloon giraffe, balloon stegosaurus, balloon bear, balloon sword, and balloon hat.
Attempting to create a balloon shape has a 25% chance of popping the balloon, and takes five seconds.
Clumsy people, such as clowns, can shape balloons in half the time and with no chance of failure.

Adds living balloon animals.
Living balloon animals appear identical to regular balloon animals, but when a balloon is popped in view of them, they come to life and attack anyone who isn't clumsy.
They behave like space carp in terms of speed, damage, and health, although any weapon with a sharp tip or hot edge will pop them instantly
A box of living balloons can be bought from traitor clown uplinks for 6 TC.

:cl:
 * rscadd: Added long balloons, which can be tied into various shapes.
 * rscadd: Added living long balloons to traitor clown uplinks, which can be tied into balloon animals capable of springing to life.

### CODE REVIEW

**Comment by JustSumBody** [comment]
>buffing clumsy

OY VEY IT'S LIKE ANUDDAH SERVER POLL

**Comment by AutismSpider** [comment]
Take ages for clown set that shit up any way

**Comment by SonixApache** [comment]
BALLOON ANIMALS
COMBAT BALLOONS

SHADOWMECH HAVE I TOLD YOU I LOVE YOU BEFORE BECAUSE HOLY SHIT

**Comment by Intigracy** [comment]
But where's the snake

**Comment by Shadowmech88** [comment]
The default balloon animal subtype is a snake, just in case someone manages to acquire one somehow.

I didn't add it to the available shapes list though, because I didn't see a point.

**Comment by Intigracy** [comment]
hqdefault

**Comment by Shadowmech88** [comment]
Oh, well in that case When You Sprite It.

**Comment by Probe1** [comment]
Sorry once you fix the conflicts I"ll merge this right away.

**Comment by Shadowmech88** [comment]
Conflicts fixed.

**Pull request merged**
