### PR TITLE
Trader PDAs

### PR DESCRIPTION
**Pull request by Kurfursten**
Sprite credit @Blithering 
Idea credit @despotate 

pda

🆑 
* Traders now can buy a PDA from their vendor for 100 credits. It's ugly, but it has a shuttle-call button.
* Trader vendor now stocks tons of gashapons! Jewing the vendor by using the 'throw stock' wire will now take much longer to get anything useful.

### CODE REVIEW

**Comment by Durgen** [comment]
miners get to jew their vend, but traders don't?

**Comment by Kurfursten** [comment]
I personally think that's dumb too

It's not a must-have, we can talk about it, but I would like to encourage traders to have a reason to acquire money. I know every round I play Trader I just pulse the throw wire instead of buying my trader coat because why not, there's a 60% chance you get the coat on the first throw.

Compare that to the chance of getting a canary or a chili or something.

**Comment by Probe1** [comment]
Why do traders get 1:1 parity with crew?

**Comment by Durgen** [comment]
that's rich coming from you probe. youre the bird lover who coded a whole new outpost for us

**Comment by Probe1** [comment]
>us

oy vey!

**Comment by Megamaw** [comment]
is a balance tweak + a feature even atomic? i'm still trying to figure this out. anyways, my thoughts--



if we fix the whole 'throw stock' thing though i imagine just making it break until the wire is fixed will work b/c 

1.  if the vox can't just take stuff from the vendor, they dont own it
2. if someone's marketing vending machines to vox, i'd imagine they know about vox culture
3. let's be real they know the birds are gonna hack the thing you think they didn't expect that??

miner vends should have a similar failsafe b/c they're very expensive to replace objects on an NT-owned station. this is the same station that has stuff like Groans Soda to cut costs, do you really think they're going to let the QM steal thousands of creds worth of expensive equipment

**Comment by despotate** [comment]
I foresee the problem of monkeys breaking in and buying Trader PDAs just to keep calling and recalling their shuttle over and over again.

**Comment by Kurfursten** [comment]
@Megamaw I don't think it's really necessary. Sure, it will be hacked either way, but there's a time/effort tradeoff. You can get the PDA instantly and enjoy it all shift if you just pay for it at the start. Otherwise you need to sit next to the machine or rig it up next to an animal like Colonel Gravy and even then wait a pretty long time. There's about a 1% chance you get a PDA on the first throw.

@despotate The PDA must have an ID with trader access in it to use the send shuttle app

@Probe1 Not sure what you're asking. They don't, crewmen don't need to buy their PDAs and it's much easier for them to abuse throw wires to get items. Also crewmen still get a station account/virtual wallet that Vox don't which is one of the main conveniences in using a vending machine.

**Comment by Probe1** [comment]
Don't they regularly start with over 100 credits though?

**Comment by Kurfursten** [comment]
The consistency is really bad, you have an equal chance of starting with 2000 credits as 1 credit. I'm happy to talk numbers with you though, find a good spot for things.

I thought 100 felt reasonable for these reasons
* It's the price of a PDA at the PDA terminal (but you get an ugly one and no chance at the clear special edition)
* 100 is the same price as the trader coat, which is similarly something that exists to make trading quality of life better

What are your thoughts?

**Comment by Blithering** [comment]
How about making it only have a single PDA in stock, so birds are forced to either work together like reasonable people, or fight for it.

**Comment by SonixApache** [comment]
The birdvend has a throw wire?
Vending machines were a mistake.

**Comment by Kurfursten** [comment]
All vendors have a throw wire, you can get guns and jetpacks out of the minevend the same way

**Comment by Exxion** [comment]
Yes, you have an equal chance of getting any two SPECIFIC numbers of credits, but the same does not necessarily apply for ranges.
Unless it has a weird distribution, if you can start with 1-2000 credits, over 100 is much more likely than under 100
But maybe it's a weird distribution and everything I just said is irrelevant

**Comment by despotate** [comment]
The process works by selecting pick(1, 10, 100, 1000) for your first credit and then rand(50) to pick(1, 10, 100, 1000) for your seconds credit if it exists. I think that adds up to a 62.5% chance of being able to buy a coat/PDA roundstart if you're a solo Trader. If you spawn with buddies, the chances of everyone being able to get a coat and PDA rises greatly because of the chance of rollling 1000s.

**Comment by Kurfursten** [comment]
Some wallet consistency PR would be nice but I am sure the Defficiency assistants would scream bloody murder, since everyone knows about those wallets in maint now

**Comment by yclatious** [comment]
Not me, the most youd get is a bunch of vox traders getting miffed that easy jewing doesnt work anymore.

**Comment by Kurfursten** [comment]
Arright, it has been eight days (a week without discussion) and I have nearly three times the positive redditvotes

@Probe1 @clusterfack @PJB3005 @Intigracy

**Comment by Probe1** [comment]
I'm not powercreeping Vox Traders.  I said that outright.  They don't need PDAs and if they want them they're welcome to go to the station and trade for one.  You know, that thing they're supposed to be doing.

**Comment by Kurfursten** [comment]
I don't think you **did** say that outright, or anything resembling that. You asked a question ("Why do they get parity with the crew") and I said "I don't believe they do for two reasons, please tell me more about your stance" to which you never replied. This behavior seems, from my perception, to be strangely standoffish. I've been nothing but open to discussion, asking for further input after giving my thoughts in every post.

Frankly, I think this is the opposite of powercreep: I included the gashapons with this PR because I felt, like you, that Traders shouldn't get free toys, which coats currently are effectively. So the addition of gashapons to make the vendor harder to cheat is a counterbalance to make the new content "even". I think it's clear that it wasn't a popular decision from some of the comments here, but I made that hard choice because I don't want to play favorites with anyone.

**Comment by Megamaw** [comment]
i really like the content this adds. i really do. but i'm giving it a thumbs down b/c adding content + a balance tweak in the same PR i think is pretty 'unatomic', and kind of a sleazy move. if we want the content, we have to accept your balance change, which is really fuckin' weird.

please add the gashapons in a separate PR so people can adequately discuss the actual balance issue. the thumbs up are almost invariably for the pda addition. if you want to change tweak balancing, do NOT do it in the same PR that adds content.

**Comment by Kurfursten** [comment]
Stonewall Probe will never accept new Trader content unless it comes with a drawback, you read it yourself. Meanwhile,  a couple people like you are upset because it has a drawback. It's a no-win.

In spite of all that, we've got double the 👍 so I see no reason not to go ahead and merge.

**Comment by Lokiamis** [comment]
@Probe1 
PDAs are powercreep but you merged the 14 storage slot trader coat without so much as a negative comment on the matter? Something's not right here. You're going to have to explain this before putting your foot down.

**Comment by PJB3005** [comment]
How about giving Vox traders PDA cartridges with the call button instead, but still make them buy a PDA.

**Comment by Kurfursten** [comment]
I'm fine with that, do you think it's too gamey to just check the ID inserted into the PDA for access? That's what the code currently does.

If you simply hack into the outpost and there are no traders, buying a PDA won't do anything for you (at least, not anything you couldn't accomplish at any PDA terminal on the station)

**Comment by FudgePucker** [comment]
New fun github drinking game, every time you see the word powercreep you take a shot.
I am not responsible for damage to your liver.

**Comment by FudgePucker** [comment]
Also how the hell is giving traders a way to buy PDAs "power creep"?
This PR does more to hinder traders by making it take 10 times longer to cheese the vending machine.
Science can print AI upload boards, print guns, print any machine boards, a teleporter that can pick up targets from 95% of space, slimes, and can make bombs. But fuck me if traders get PDAs. I think I am going to have a stroke. I don't even like traders and I don't see how the hell this is ""power creep"".

**Comment by Kurfursten** [comment]
Look, I'm willing to be flexible here - we can do the separate cartridges thing, or adjust the price, or take out the gashapons - whatever. I've never drawn a line in the sand on this PR. But every time I try to have a conversation, I ask a question and then it peters out.

What's the deal Probe? Are the gashapons not enough of a counterbalance in your mind? Are wallets core to the Trader experience and irreplaceable? Are PDAs truly too strong? These aren't rhetorical questions or attacks, I'm trying to see where you're coming from

PJB, what's the advantage in your mind of separating the cartridge to spawn with traders over the current system of checking ID access? If there's a good reason I don't mind changing the code, just tell me what it is - why should I bother switching back onto the branch and changing up the code? If I implement your change will I get a merge?

**Comment by SonixApache** [comment]
replace gashapons with glasses of water

**Comment by FudgePucker** [comment]
Seriously, I would understand all this bullshit if it was a feature request.
Kurf went ahead and coded this, the least you can do is give more solid critism than "PDAs are power creep".
It really truely isn't power creep. The trader occupation is new and things need to change as the it evolves.
There are ZERO down sides to letting traders get PDAs. Oh no traders can send and receive messages. This is a good thing, using messaging can help them trade, and anything that encourages trading as trader is good. More trading and less grayshittry.

You know what how about a compromise, the vox PDAs can be worse than normal station PDAs by not having a cart slot, if that wouldn't be too hard to change? If anybody objects to it then I don't know anymore.

**Comment by Kurfursten** [comment]
They effectively don't have a cart slot because if you take out the trader cart you can't call the shuttle anymore

**Comment by FudgePucker** [comment]
Maybe prevent the cart from being removed?
Like its just cheaply soldered onto the motherboard and the PDA doesn't have a slot.

**Comment by Probe1** [comment]
It was a role designed to be austere and now you want to remove the austere part.  Leaving exactly what left?  A snowflake job for furries?  

You have not grasped the core design of a trader despite being there when they were added.

**Comment by Kurfursten** [comment]
I think that aesthetic is paid significant tribute in the sprite. Don't get much more budget looking than that. It's not as though I'm insisting Traders get a box of crystal PDAs and a cartridge vendor.

Moreover, having traders visible via PDA is good for everyone. My #1 frustration when I want to get a hold of Vox trade shit is that I'm sitting there playing the guessing game all shift if a trader is even going to show up, then they don't even bring me vapor salts or whatever.

**Comment by Probe1** [comment]
Austerity is not aesthetics.  They start with less and have slowly been dialed up to have everything they need to do their job and left to trade for everything else.  

That is the core design.  They are _traders_.  This is an item that they can get via the station.  What happens if we continue to give them everything they want rather than need?  They stop trading.  Why would they?  They already have everything they could want.  So it becomes an isolated job that is removed from the rest of the players to play single player SS13 with.  

It is not very different from the discussion over floral disks.  Yes, it's annoying not to start with them but its also a golden opportunity for trade to occur.

**Comment by Lokiamis** [comment]
If they want a PDA from the station they either have to buy it from the machine instead of Kurf's thing or get one from the HoP, who has no reason not to give out a next to worthless PDA for free in the first place. Either way, I don't expect traders to have PDA's, so I'm never going to check for them in the messenger to see if they're interested in something I have. 

If I can't contact them in private to set up a meet or ask about stock, I'm not going to bother running all the way to arrivals praying they're idling in their 4x4 ship eagerly anticipating one of the 3-4 customers they get in a 2 hour shift. I'm going to keep my hand teleporter instead of trading it for a stun prod or whatever meager bullshit they have to offer. 

If you want traders to trade more, give more opportunities to the 30 crewmembers, not the 2 traders.

**Comment by Kurfursten** [comment]
I think the floral disk thing was a good choice for the record.

But like @Lokiamis said, PDAs promote trade. They facilitate communication. Think back to when you used to play Mechanic all the time. Even with that EXTREMELY prime real estate dead in the middle of the station, I bet you recall getting orders and requests via PDA all the time, right?

Traders have the opposite of that prime real estate. Not only is it so far out of the way you'd only pass by if you were headed to the salvage ship, if you visit and there's no trader in dock you've essentially wasted your fucking time walking over there. Your only time save is to ask the AI if they can see the edge of the ship out one of the cameras, or hope the trader is listening to the radio chatter (which will go totally missed if they happen to be in transit when you ask, with no feedback unlike the PDA's error message).

When I trade, I play it very proactive - walk door to door and hassle people to buy things, set up a sample stand in the main hallways. But that's not how most traders operate, and as a guy who just wants to get some gravy or maybe get a borer to hatch in the incinerator, it would be great if I could see Traders on PDA, essentially broadcasting "yes, I'm open for business and I spent money on the conscious choice that I want to make my services available to you"

**Comment by Probe1** [comment]
I completely disagree but I can see that I'm out-debated here and I'm not going to stand in the way.

**Comment by Kurfursten** [comment]
Man I can tell you are tired just from your words alone

I hope you feel better soon, sincerely. Even now I fondly look back on the Allen Baker days, hell, even the pre-mechanic days. Take a break if you have to, I know I did - and I felt a lot better afterward.

Let me know if I can help with your Deff Medbay rework somehow.

**Comment by Probe1** [comment]
That isn't exhaustion.  I don't agree with what you've done.  I still accept that you and @Lokiamis have made stronger points.  There will come times when I have to say flat out no and tell people we won't do something.  There are times like this where I will have to listen against my own judgement.  It is disappointing for both sides but without accepting it then you aren't collaborating to make something better as a team.

https://www.youtube.com/watch?v=7knIi3LGf4M

**Comment by SonixApache** [comment]
*why don't we just make life easier for the shitbirds PR # 637*

**Comment by Probe1** [comment]
Yes those are my summarized thoughts on the PR, however it was reasoned that this will facilitate trading and that is their overall goal.

**Comment by SonixApache** [comment]
I'm going to remove the N2 miners from the vox stations and replace them with a single air pump with 999kPa N2 in it.

N2 miners are expensive, go trade with the station for one.

**Pull request merged**
