### PR TITLE
slimmer armor

### PR DESCRIPTION
**Pull request by SonixApache**
Modifies armor vests. Mix between old and new. 
Takes general shape from the old style, with the concept of straps and less wideness from the new style.
Motivation: I hate the shoulder straps with a passion.
Clown vest is untouched old style as example.
image

🆑 
 - imageadd: Changed armor vest sprites up a bit. For those who prefer the fat straps, use an armor vest on a secvend.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
can I get uhhhhhhhhh an old vs new

**Comment by SonixApache** [comment]
current ("New style")
new

Old ("Old Style")
old

Comparison (new vs mixed vs old)
mix

**Comment by Buchse** [comment]
I just like the pads too much my man

**Comment by PlausibleDeniability** [comment]
Personally prefer the current style with the chad shoulder pads

**Comment by PrimeDSS13** [comment]
I am on team anti-pad. Too many games have massive shoulder pads and I will not STAND for it.

**Comment by beesil** [comment]
Straps on the new detective armor aren't even, otherwise I'm a solid ehhhh. The current sprites have nicer detailing on the front.

I think it's worth noting that the timing on this PR is immediately after the person who made the current sprites came back from a several month hiatus as well.

**Comment by Buchse** [comment]
i'm curious about that, since if you hated em so bad you could've made the PR any time in the past what, three months? So if you didn't hate them badly enough to change them before, what changed?

**Comment by PrimeDSS13** [comment]
I do agree they need a bit more texture yeah

**Comment by SonixApache** [comment]
i happened upon a small cache of codermana, this is the result

i see the rogue pixel on the detective thing and will fix it

**Comment by smalIboss** [comment]
the pads were too much. they looked silly.

**Comment by Blithering** [comment]
Maybe the pads can be readded as an accessory for those who are on an action packed trip to detroit?

**Comment by SonixApache** [comment]
We do have these silly armor parts that I've been wanting to add to the armories. Sprites could use some work, but they're pretty cool. Reinforced shoulder straps could be funny, I'll think about it.
armor_shard

**Comment by Blithering** [comment]
Those ones are designed to look good with the plate carrier vest, so they're gonna look wonky with others.

**Comment by SonixApache** [comment]
Me and Clock are experimenting with how to improve the armor pieces. Meanwhile, straps.
Slapping an armored vest on a security vending machine now gets you one set of reinforced straps.
There's only two per machine, and they offer one (1) point of armor.
dreamseeker_2021-01-30_22-34-05

**Comment by Blithering** [comment]
I have some unused sprites for armour vest and helmet upgrade accessories if you wanna take it a step further.

**Comment by SonixApache** [comment]
i'll look at it, send 'em over for the next go

**Comment by Kammerjunk** [comment]
minecraft chestplate

**Comment by Kurfursten** [comment]
Make sure you say when the sprites are their final version

**Comment by SonixApache** [comment]
they're in the final version

**Pull request merged**
