### PR TITLE
Beach Party Vault

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds the beach party vault, a beach-themed vault containing some basic beach items, a few crabs, a boombox, a squirt gun, and a super soaker.
image

:cl:
 * rscadd: Added a beach party vault.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Oh man, it says I made changes to Bagelstation.

**Comment by Riekland** [comment]
bit sexist
where's my shorts

**Comment by Aurx** [comment]
Needs a party button.

**Comment by SonixApache** [comment]
:+1: for squirt gun USP

**Comment by Shadowmech88** [comment]
* A pair of red shorts has been added to the beach party vault.

**Pull request merged**
