### PR TITLE
shocking now passes the siemens coefficient of whatever you're hitting the thing with.

### LINKED ISSUE #11051: glass shard doesn't protect from electricity
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

20e8385cf18921c12e1b48770f334422bc9ddc20 

> General description of the issue
> using a glass shard on a door will open it. using a glass on a shicked grille won't shock you, beacuse glass is an insulator. using a glass shard on a shocked door will shock you, and not open the door.
> 
> What you expected to happen
> use glass shard on shocked door, not get shocked
> 
> What actually happened
> get shocked
> 
> Steps to reproduce if possible
> find a functional shocked door, then slap it with a glass shard

### LINKED ISSUE #18007: Shocked airlocks appear not to check siemens_coefficient
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
Hit a spicy airlock with a glass shard: Zappy
Shard on shocked grille: No zap.
Battering Ram on airlock (think it is also nonconductive): Zappy
Ram on shocked grille: No zap.

### PR DESCRIPTION
**Pull request by MadmanMartian**
closes #18007
closes #11051

This also means we can now make insulated tools in the future, rather than the all-powerful yellaglubs

:cl:
* tweak: Things that shock you on contact (airlocks, grilles, etc.) when you're hitting them with something now take into account the items siemens_coefficient

### CODE REVIEW

**Comment by Probe1** [comment]
Boy this will be fun to test

**Comment by Mothblocks** [comment]
lotta `(I ? I.siemens_coefficient : 1)`, can't you write a function or a macro to do it just to clean stuff up?

**Comment by MadmanMartian** [comment]
That can be done

**Comment by Intigracy** [comment]
what if I'm wearing gloves and use something non-shockproof to touch something

**Comment by MadmanMartian** [comment]
It checks in the electrocution_act for gloves, which is called by shock()

**Comment by Aurx** [comment]
Balance.

**Comment by Probe1** [comment]
@Aurx I totally disagree because its fixing something that is horribly coded but intended.  But whatever.

**Comment by MadmanMartian** [comment]
Theres an is_conductive check used precisely once. Gonna convert to get_conductivity

**Pull request merged**
