### PR TITLE
Can now smelt mythril and telecrystal

### LINKED ISSUE #21271: putting telecrystals from Mining satchels into oreboxes deletes them
(WEB REPORT BY: manfreed REMOTE: 206.221.180.138:7777)
# Revision
5637481bd5911efa33d1ef13990491ab0750877c

# Description
What it says on the tin.
putting telecrystals (purple triangle things) from Mining satchels into oreboxes deletes them.

# Steps to Reproduce
Find and mine telecrystals
Put them in your satchel like anything else you mine
empty satchel into ore box
TC are gone

# What you Expected
to keep my precious loot

# What Actually Happened
Admin PM: i got no clue about what happened to em

### PR DESCRIPTION
**Pull request by MadmanMartian**
closes #21271
:cl:
 * Can now smelt mythril and telecrystals at the ore processing console

### CODE REVIEW

**Comment by Goldsteel** [comment]
Does that mean telecrystals will stack as sheets? How will that affect them being placed in the telescience teleporter?

**Comment by MadmanMartian** [comment]
No it won't. They just become bluespace crystals. they can be placed in the telescience teleporter already?

**Comment by Goldsteel** [comment]
I just wanted to double check they wouldn't stack like sheets.

**Comment by SGuivenne** [comment]
Wait.  Natural or artificial bluespace crystals?

**Comment by MadmanMartian** [comment]
Natural

**Pull request merged**
