### PR TITLE
renames security borgs to peacekeeper borgs

### PR DESCRIPTION
**Pull request by SonixApache**
This is essentially a revert of #14762 and a redo of my old PR, #14203
It also goes against the relevant poll from `2017-07-16`, http://ss13.moe/index.php/poll/120

I think security borgs should be renamed to peacekeeper borgs because;

- they're not security when on any lawset but robocop or law custom
- they don't help security when on any lawset but robocop or law custom
- people that play them see 'security' and think they're security even when they're not onrobocop or law custom

Discuss.

### CODE REVIEW

**Comment by aceedex** [comment]
Gay

**Comment by boy2mantwicethefam** [comment]
borgs on blue alert part 2: electric bogaloo when

**Comment by Kammerjunk** [comment]
wanna make it clear and pre-empt the "sneaky coders" stuff by saying that this didn't come out of the blue, but after some non-serious chatting in the admin channel.

personally I think my opinion isn't worth very much because I'm probably not going to see it in action anyway, but I can see why it's an appealing change. whenever I played secborg, I took great care to observe Asimov moreso than Space Law because that's how borgs have to act and an "impartial peacekeeper" was what I thought was more interesting.
then again, it beats me how many people are even still left to rebel against all things TG and how many people will rather associate the word "peacekeeper" with hugborgs instead of any other server

**Comment by DrSnips** [comment]
Can we not do this again. The last time didn't go as planned what makes you think it will work this time?

**Comment by ShiftyRail** [comment]
No half-measures

Code blue and keep them called secborgs or nothing

**Comment by SonixApache** [comment]
i would like to clarify that there is nothing blue related anywhere to this

it merely renames "SECURITY" to "PEACEKEEPER" and nothing more

**Comment by Diavill** [comment]
notto disu shittu agen

**Comment by SonixApache** [comment]
I'd also like to remind everyone that "But TG call their hugborgs peacekeepers!!" isn't really an argument that holds any weight.

**Comment by bathosbathtime** [comment]
I don't think the "you guys only hate it because it's TG" argument holds any weight itself when we've added peacekeepers before to a largely positive reception.
Granted, my own personal feelings on the matter start and end at "secborg is easier to say than peaceborg."

**Comment by Shaska-** [comment]
I still prefer "Guardian module" but w/e.
Is this really still an issue though? I remember a lot of people used to struggle with the concept of the sec module not actually being part of sec before, but it doesn't seem nearly as prevalent these days.
Besides, whenever you pick the sec module, you get a big fat red warning, reminding you that your laws take priority over everything else.
If that isn't enough for some, then I doubt anything short of a complete rebranding of the module would make any difference. 
As long as it doesn't include the ugly baby blue sprites though, I don't really have anything against this. I just don't think it'll really accomplish much.

**Comment by SonixApache** [comment]
I've had to explain to a man who had that big giant red text appear literal seconds before the incident
that he was to follow his LAWSET and not SPACE LAW
because he was ignoring orders from people because they were 'criminals'

it is still and always will be an issue

**Comment by Shaska-** [comment]
Some things never change I guess.

**Comment by DrSnips** [comment]
Sounds like you should be doing your job as an admin and silicon banning people. Failing to read or understand a role means you shouldn't be able to play the role.

**Comment by ShiftyRail** [comment]
On a more serious note, I don't have too much opinions about sec borgs (other than moving them to code blue), but I doubt this change will have much impact.

**Comment by Blithering** [comment]
Back to a not-serious note, can we rename service module holy water factory and paint it orange?

**Comment by SonixApache** [comment]
@DrSnips i do in fact do my job as admin and tell those 'security' borgs that they're not security and they're called security borgs because they have security tools but not because they belong to the security department and that they're supposed to provide security in the literal sense in conjunction with their normal asimov lawset and not be worried about criminals or anything in that sense because they're not security officers

but boy does it get a little tiring after a while
if only there were some sort of way to pre-emptively prevent those kinds of mindsets

**Comment by Tehsapper** [comment]
i like secborgs more
nothing stops a borg to care about criminals, as long as they follow their laws.

**Comment by jknpj** [comment]
> if only there were some sort of way to pre-emptively prevent those kinds of mindsets

The only ways to prevent that is to either remove them or make cyborg/security module a whitelisted job/module. Neither is going to happen.

Department laws/directives when?

**Comment by utilitas-** [comment]
hmm, it's almost like someone should make silicon laws into less of a confusing mess so people could better understand it instead of making rules lawyering an inherent part of playing silicon.

**Comment by Blithering** [comment]
Borgs getting custom lawsets based on their module sounds fun, and would probably be less of an administrative headache, but would take a lot of the fun out of setting silicon laws.

**Comment by SonixApache** [comment]
what's confusing about
DON'T HARM HUMANS
FOLLOW ORDERS FROM HUMANS
?

What is confusing about having to obey the man you're arresting for stealing a hamburger?

**Comment by tuypo1** [comment]
Well then maybe command should stop being lazy and stop leaving the ai on asimov, they can freely act as security on almost all other lawsets

**Pull request closed without merging**
