### PR TITLE
Changes gum grammar

### PR DESCRIPTION
**Pull request by Hinaichigo**
This makes it so chewing gum displays as:
`He has some chewing gum in his mouth.`
rather than
`He has a chewing gum on his face.`

This also adds an `uncountable` flag to items and adds it to chewing gum so that the examine text of chewing gum will say:
`That's some chewing gum. It is a tiny item.`
instead of
`That's some chewing gum. They are a tiny item.`

:cl:
 * tweak: Chewing gum now goes in one's mouth.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Is it possible to add new grammatical genders or is that hardcoded into BYOND? It might be nice to have an UNCOUNTABLE gender as well.

**Comment by Eneocho** [comment]
I'd say "That's chewing gum. It is a tiny item." would fit best, since it works when referring to the pack as a whole or a single one.

**Comment by Kurfursten** [comment]
2 good Eneocho posts in 1 day

**Comment by Eneocho** [comment]
> 2 good Eneocho posts in 1 day

https://youtu.be/91YS3fNegmE?t=21

**Comment by Hinaichigo** [comment]
> I'd say "That's chewing gum. It is a tiny item." would fit best, since it works when referring to the pack as a whole or a single one.

That'd be ideal. But since this uses the inbuilt BYOND grammatical gender macros, and I don't think there's a way to add another one simply, it might require another flag to indicate something is uncountable.

**Comment by wotisjanitor** [comment]
souless

**Comment by Kurfursten** [comment]
I believe you want to use \proper for this to get rid of any articles.

For example, "That's Ian, he is small" instead of "That's the Ian".

**Comment by Hinaichigo** [comment]
If I understand correctly, would that result in having to add a flag and a check to avoid stuff like:
`He has energy gun in his left hand.`
It also works in conjunction with the `uncountable` flag added by #33484.

**Comment by Kurfursten** [comment]
That grammar is fine in this case. "He has chewing gum in his left hand" makes sense to me.

**Comment by Hinaichigo** [comment]
I made this more atomic with regard to #33484 by putting the gum-related changes here.
So if there's three items, one singular (revolver), one countably plural (berries), and one uncountably plural (chewing gum), there's a few options it seems:

For the revolver, it seems that it should always be:
`He has a revolver in his left hand.`
`It is small.`

For the berries, it seems like it should either be:
`He has some berries in his left hand.`
`They are small.`
or like this:
`He has berries in his left hand.`
`They are small.`

For the chewing gum, it seems like it should either be:
`He has some chewing gum in his left hand.`
`It is small.`
or:
`He has chewing gum in his left hand.`
`It is small.`

**Comment by Kurfursten** [comment]
conflicts

**Pull request merged**
