### PR TITLE
Fixes a Few Uniforms for Greys, Insectoids and Vox

### LINKED ISSUE #28634: Vox Uniform Sprites Going Unused
#### Description of issue
I noticed that the mannequins wear uniforms better than me and got jealous.
Untitled
There are clearly vox specific uniform sprites for CE, scientist, geneticist and chemist, but they do not show up on normal vox. Instead you get the human sprite tacked on top on yourself.
It'd be nice to wear a suit that actually fits and not have your chicken legs sticking out and your beak tucked in your collar.

### PR DESCRIPTION
**Pull request by Armadingus**
Closes #28634

Babby's first PR, watch out. Makes it so that the chemist, CE, geneticist, scientist and virology uniforms show the correct non-human sprite for greys, insectoids and vox.

:cl:
 * bugfix: Some specific uniforms now show the correct sprite for greys, insectoids and vox

### CODE REVIEW

**Comment by beesil** [comment]
did you test to make sure this doesn't break human sprites? 
if you're feeling ambitious, I tested & made a list of sprited but not working vox uniforms the other night, it seems to correlate to `icon_state` not matching `_color`.
- chaplain
- ~~scientist~~
- ~~chief engineer~~
- ~~virologist~~
- ~~chemist~~
- ~~geneticist~~
- simon pants
- hos
- noir det

**Comment by Armadingus** [comment]
Both human and fat human sprites are intact on my end, the only problem I encountered was the object uniform sprites using a placeholder, which I fixed in the first commit. I will definitely look into those other clothes you listed, as soon as I figure out how to make multiple commits in one PR.

**Comment by kilozombie** [comment]
> Both human and fat human sprites are intact on my end, the only problem I encountered was the object uniform sprites using a placeholder, which I fixed in the first commit. I will definitely look into those other clothes you listed, as soon as I figure out how to make multiple commits in one PR.

To do multiple commits, you just replicate whatever you did for the first one, when you 'staged' changes and such. It should Just Work, god willing

**Comment by Armadingus** [comment]
I noticed that the noir suit is missing its fat human sprite. Not because of what I've done I believe, it's sharing filename with the normal fat detective sprite.

**Comment by ShiftyRail** [comment]
Congrats on your first PR!

**Pull request merged**
