### PR TITLE
Borg skins second go

### PR DESCRIPTION
**Pull request by Dizor**
kodiaksample2
Sure hope this works now
Trying to add in unfucked borgs

### CODE REVIEW

**Comment by Ephx1** [comment]
Something else I noticed. North/south sprites are consistent with one another, but they don't match up height wise for west/east for both Sec and Service.
Definitely more noticeable on the service one however.

**Comment by NigglyWiggly** [comment]
It looks like the feet aren't lined up on the sprites, so the east/west sprites are even taller than they appear at first

**Comment by Dizor** [comment]
Yeah, I can adjust it but I chose to make the borgs a bit taller east and west to keep detail from being lost. If its going to be a problem I'll change em

**Comment by NigglyWiggly** [comment]
Looks good, merge when?

Also holy shit your avatar reminds me that we NEED a junkbot skin for janitor.

**Comment by ihadtoregisterforthis** [comment]
Inconsistencies between north-south and east-west
- Different heights for service and security
- Different  arm position on service
- Different head position on all of them

**Comment by Dizor** [comment]
I'll fix the heights and probably change the service borg's south and north sprites to have the arm reflecting the east and west sprites. Mining is finished, engineering has a finalized design and will be finished soon.

**Comment by ghost** [comment]
RIP

**Comment by gbasood** [comment]
That spider chassis though
I want it so bad

**Comment by Ephx1** [comment]
WHEN, WHEEEEEEEEEEEEEEEN?

**Comment by PJB3005** [comment]
Comment if you want it reopened.

**Pull request closed without merging**
