### PR TITLE
Adds a new traitor bundle and adds/adjusts items in it.

### PR DESCRIPTION
**Pull request by Servalfang**
[sprites] [tested]
New syndicate bundle. Comes with three greytide implants, three pitchforks, three torches, and a crossbow. 50% as common as normal bundles.
Torches work like slightly brighter flashlights, but fire-colored, and they do a small amount of fire damage on hit.
Pitchforks can now be wielded, increasing their force from 8 to 14, and have received appropriate sprites.

Reports that the syndicate are planning to hand over their coveted codebreakers to elite teams are as of yet unverified.
:cl:
 * rscadd: A new Syndicate Bundle.
 * rscadd: Torches, currently found only in one of the new syndicate bundles
 * tweak: Pitchforks can now be two-handed, with sprites, increasing their force from 8 to 14. Their sharpness has been reduced from a whopping !!2!! to 1.4.

Also: Credit/thanks to Optimism, Djkramer, Apogee, and Shifty for how2code basics and general advice.

### CODE REVIEW

**Comment by ConfusedCactus** [comment]
>syndie bundle with a codebreaker in it

bro are you insane

**Comment by Servalfang** [comment]
> > syndie bundle with a codebreaker in it
> 
> bro are you insane

Emags are 6tc and end the round quicker and easier, on top of increased utility. Don't forget that this is a 28-tc "elite" bundle, which are already exceedingly rare to see.

**Comment by WindowsErrors** [comment]
elite syndicate bundles be like

security status: snipered
school status: shootered
scammer status: beheaded by a single security officer for getting a shitty ass kit that's worth less than the 28 TC they spent on it
station status: nukered

**Comment by Servalfang** [comment]
Don't forget, two pinpointers are part of the station default. They point to the disk at all times.

**Comment by west3436** [comment]
A codebreaker alone costs 100TC, making the second item a very OP bundle. The first bundle is hilarious and definitely should be separated from the nukie-lite bundle so it'll actually be merged

**Comment by Servalfang** [comment]
> A codebreaker alone costs 100TC, making the second item a very OP bundle. The first bundle is hilarious and definitely should be separated from the nukie-lite bundle so it'll actually be merged

Codebreakers COST 100tc. they aren't WORTH 100tc

**Comment by Apogee-dev** [comment]
the elite bundle seems _mostly_ fine to me. sure it has a codebreaker, but if you want the nuke to blow you still have to protect it until it goes off and the only combat item in the bundle is the beretta. if you want to weaken it a bit, remove the eimplants and the emag or replace it with an agent card or something to make breaking into & stealing shit more difficult. emag is a ridiculously high-value item for its given price anyway. 
hell, if you want to go all the way on it just make the bundle the codebreaker and nothing else, the rest is up to two traitors who gave up all of their traitor gear for a chance to nuke the station

**Comment by Optimism333** [comment]
I've been informed that sharpness works as a multiplier for weapon force damage. So I'd recommend lowering the pitchfork's value from 2 to 1.5 so it has a damage range of 12-21 instead of 16-28. Still pretty strong, but not too crazy.

I don't know much about bundles, but a peasant rabble-themed one sounds fun. A more classic viva experience.

**Comment by Servalfang** [comment]
Oh. Yikes. How do I revision this shit?

> I've been informed that sharpness works as a multiplier for weapon force damage. So I'd recommend lowering the pitchfork's value from 2 to 1.5 so it has a damage range of 12-21 instead of 16-28. Still pretty strong, but not too crazy.
> 
> I also don't know much about the bundles, but a peasant rabble-themed one sounds fun. A more classic viva experience.

**Comment by Optimism333** [comment]
> Oh. Yikes. How do I revision this shit?
> 
> > I've been informed that sharpness works as a multiplier for weapon force damage. So I'd recommend lowering the pitchfork's value from 2 to 1.5 so it has a damage range of 12-21 instead of 16-28. Still pretty strong, but not too crazy.
> > I also don't know much about the bundles, but a peasant rabble-themed one sounds fun. A more classic viva experience.

You'll want to change the code line, make sure you're using the same branch you used to make this pr. Then make a new commit and push it again. New commits should change this existing pr only, as long as you only edit the "nubundles" branch.

If you need more help I encourage asking another coder/collab, since I'm a bit busy right now. I'll be around later.

**Comment by Servalfang** [comment]
Removed Hacker's eimplant and emag, gave him a handheld TV with a single camera bug, a security cameras circuitboard, and gave both halves syndicate encryption keys. Also reduced pitchfork sharpness to 1.4. I thought 12-21 is still a little high for three dudes swarming one, so 1.4 should reign it in a hair.

**Comment by Eneocho** [comment]
I'll update the wiki as soon as it gets merged.

**Comment by Kurfursten** [comment]
I'm voting against this. I don't have strong opinions on it and I haven't even read the PR, but this guy was complaining against downvotes in #ick so I had to do my duty.

**Comment by Kromkar** [comment]
I think the latter two bundles lack cohesion and seem to be nothing more than a reason to add a codebreaker to the bundle thing. I don't disagree with it in principle, but the downsides mentioned and lack of sovl in my opinion outweighs the good of new bundles. Pr the pitchfork one separately tho

**Comment by angryturnip** [comment]
> I'm voting against this. I don't have strong opinions on it and I haven't even read the PR, but this guy was complaining against downvotes in #ick so I had to do my duty.

Me too

**Comment by Servalfang** [comment]
the current form of the hacker bundle is supposed to be an observer/guiding hand for the hunter who also makes the decision of what to do once they have dat disk (do we smack the button or do we try to ransom the station or something?)

**Comment by ghost** [comment]
remove the codebreaker and ill rescind my downboat

**Comment by Servalfang** [comment]
And leave the newcops bundle with what? tears?

**Comment by Servalfang** [comment]
I could actually change it to "Assassin and watchdog (no nukies gimmick)" but I think the idea that that two tots might actually pull something off with this bundle is interesting considering there's only one weapon in the entire thing and it eats up a lot of TC.
Or, I could make a new 60tc bundle containing stuff for "Hammer, Anvil, and Commander" which has slightly better gear for three in exchange for being over twice as expensive making it extremely rare

Current idea: Make it a 60tc always-purchasable thing. instead of 12 spare tc, the third bundle contains an esword and a radio key, to assist the "hunter." Otherwise largely unchanged.

**Comment by pedr69** [comment]
>if you use it on the nuke and sit still for 60 seconds

more like 5
i am in favor of people being encouraged to guard the fukken disk

**Comment by Dacendeth** [comment]
Just throw the station nuke into the singulo from now on.

**Comment by Eneocho** [comment]
> Just throw the station nuke into the singulo from now on.

`>throw the nuke at the singulo`
`>it was blob`

**Comment by Servalfang** [comment]
I'll bend the knee for now. You will see the codebreaker again soon.

**Comment by Eneocho** [comment]
> I'll bend the knee for now. You will see the codebreaker again soon.

DONT. DONT OBEY THE CODER CABAL. YOU ARE SELLING YOUR SOUL HERE.

**Comment by djkramer123** [comment]
coward

**Comment by Servalfang** [comment]
it'll return in due time. May as well get the uncontroversial part merged asap while new work begins

> coward

**Comment by Servalfang** [comment]
sorry about the name shenanigans

**Comment by NiftyRyanyan** [comment]
I don’t think we need this bundle, we already have a greytide implant gimmick bundle. On top of that this bundle is way less balanced giving you 3 greytide implants (32 tc) and free weapons for everyone.

**Comment by WindowsErrors** [comment]
you're acting like people just don't straight up ignore the presence of the nuke disk on the captain's desk when they go in to consoom the stick of all-access butter

**Comment by pedr69** [comment]
>different bundles not being equally strong and giving you more TC for your TC

STOP THE PRESSES

**Comment by xeroxemnas** [comment]
> > different bundles not being equally strong and giving you more TC for your TC
> 
> STOP THE PRESSES

This. We have borderline useless bundles already like the hotline miami one and yet people are bitching that not all bundles are created equal with this PR.

**Comment by Eneocho** [comment]
Bundles have always been worth more(or less in some cases) than their TC cost. Shit like hacker is not worth the 14tc, while shit like emags and glue give you WAAAY more bang for your buck. There's also the grand prize one, that one's just perfect. 
Stop crying about muh balance and that poopoofart item will be too strong. Bundles have never been balanced and that's intended.

**Comment by Servalfang** [comment]
the original bundle has an emag, a famously strong traitor item. This does not.
additionally, the pitchforks are only barely better then toolboxes when two-handed.

**Comment by Kurfursten** [comment]
Last night Joakim asked the cap if he secured the disk
Cap said "secured what?"

**Pull request merged**
