### PR TITLE
Black Site Prism Tweaks and Fixes

### PR DESCRIPTION
**Pull request by Optimism333**
## A bit of prism cleaning ##
I told the vault creator months ago that I'd make an attempt to fix some issues.

### Mainly: ###
- The turrets at the front were shooting the checkpoint guards because they didn't share the same faction (fixed)
- The vox in the enclosure weren't supposed to die when the vault spawned (fixed)
- The vampire mob's abilities weren't working and there was no way to resist out of their grapple (fixed)

blacksiteprism

### Content and Misc: ###
- I made the vault's ayy and vox prisoners a bit more dangerous and gave them some flavor dialogue, using some of the same coding concepts I applied in the mothership lab vault.
ayyprisoner
poxprisoner
- Since I was editing the page anyways, I also improved the old vox crossbow raiders by giving their crossbow a cooldown, as well as a message when they fire a quill for better feedback.
- Cleaned up the smash flags on the grey and vox mob pages. I gave them to inheritance mobs instead of having a separate entry for each individual mob.

### Bleh Bleh Bleh: ###
- Vampire mobs now use their glare and screech powers properly. Both were broken.
- Vampire latch mechanic has gotten some qol changes. Mainly, the transition looks better and now rather than have to kill the vampire to get free, a player can attempt to struggle out of their grip by moving in any direction. Success chance depends on strength level calculated from mutations and other sources.

[vault] [tweak] [content]

:cl:
 * rscadd: Blacksite Prism has new prisoner mobs in the grey and vox detention center, and they're more dangerous than before!
 * tweak: Vox crossbow sharpshooters have a ranged cooldown
 * bugfix: Fixed the hostile humanoid vampire mob abilities and made it possible to resist out of its latch attack

### CODE REVIEW

**Comment by ManopolisJones** [comment]
Always hated the black site, and I doubt this will change my mind any, but it's still a good update.

**Comment by Optimism333** [comment]
> Always hated the black site, and I doubt this will change my mind any, but it's still a good update.

Fair enough. I'm just doing my best to follow through on a promise I made the creator a couple months back.

Even if you don't like the vault overall, glad you think the change is for the better.

**Comment by Optimism333** [comment]
Thanks to some help from Kurf, vampire mob code seems functional. May have also quashed some bugs out of the scope of this pr in the process.

Should be ready for review now.

**Comment by Blithering** [comment]
Glad those vampires aren't a guaranteed death sentence anymore.

**Comment by Kromkar** [comment]
> Thanks to some help from Kurf, vampire mob code seems functional. May have also quashed some bugs out of the scope of this pr in the process.
> 
> Should be ready for review now.

Thank you brother much love from Kazakhstan

**Comment by angryturnip** [comment]
It's Bleh Bleh Bleh not Blah Blah Blah

**Pull request merged**
