### PR TITLE
Revert breakable objects for now.

### PR DESCRIPTION
**Pull request by ShiftyRail**
With apologies to Hinaichigo - this sort of things happen.
Too much game-breaking stuff, I've been told to make a revert.

### CODE REVIEW

**Comment by Eneocho** [comment]
Both the taserhell and the "kick anything to nullspace it" bugs are too gunky for keeping it. Kick a pAI, it gets deleted, kick a folder, paper bin, etc.

**Comment by pedr69** [comment]
SPEED MERGE FUCKING NOW

**Comment by ShiftyRail** [comment]
ideally this would have been a component.

**Comment by Hinaichigo** [comment]
I'll clean it up before resubmitting. Apologies for the bugs.

**Pull request merged**
