### PR TITLE
༼ つ ◕_◕ ༽つAMENO༼ つ ◕_◕ ༽つ

### PR DESCRIPTION
**Pull request by ghost**
April Fools all of ya

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
You're an awful person

**Comment by 9600bauds** [comment]
please merge whatever this is as fast as possible so we can remove skeletons

**Comment by PJB3005** [comment]
# IT'S HAPPENING

**Comment by NigglyWiggly** [comment]
YOU CAN DO THIS IC 
WHY

**Comment by PJB3005** [comment]
WHY DO YOU THINK.

# MEMES

**Comment by ihadtoregisterforthis** [comment]
kappapoly

**Pull request merged**
