### PR TITLE
Revert "Suit Slot Sprites"

### PR DESCRIPTION
**Pull request by aceedex**
Reverts d3athrow/vgstation13#11827
The emergency tank sprites are really ugly looking and add even more stuff to the visual clutter. The Large oxygen sprites also obscure the cool Dead Space spine health indicator things

### CODE REVIEW

**Comment by PJB3005** [comment]
The dead space thing doesn't even work anyways and you're using a backpack or such 99% of the time anyways so???

**Comment by SangriaMonkey** [comment]
The little oxygen tank stubs sticking out from under things are annoying though and I don't see the point.

**Comment by NigglyWiggly** [comment]
>Wearing a backpack

**Comment by aceedex** [comment]
Satchel>>>>backpack my dude
But really, my big issue is how awful the emergency oxygen tanks look. A fully decked out paramedic looks more like a clown than a paramedic because of how terribly cluttered it is

**Comment by SonixApache** [comment]
I like suit slot sprites, but the air tanks ones are fuckhuge.

**Comment by Exxion** [comment]
I rather like suit slot sprites *existing*, but I'm not a fan of them just being exactly the same as the back sprites
Not sure where else they would go though

**Comment by Shadowmech88** [comment]
On the side/hip? On the chest? On the pelvis, rotated 90 degrees?

**Comment by aceedex** [comment]
Personally they don't look good at all. It's literally a yellow/blue rectangle with a black pixel.

**Comment by Ephx1** [comment]
Why are suit slots visible on the person? It's a suit slot, something _inside_ the suit.

**Pull request merged**
