### PR TITLE
Added Vox Sprites for Det. Gear and Cigar

### PR DESCRIPTION
**Pull request by zxpr0jk**
vox_ducktective

Follow your nose.

Made the detective hat sit right, moved the cigar more toward the beak and less the cheek, and added an instance of the hard-worn suit to vox anatomy.

### CODE REVIEW

**Comment by 9600bauds** [comment]
oh god what happened to these diffs

**Comment by ghost** [comment]
Are you using Git for Windows ?

**Comment by zxpr0jk** [comment]
Yes?

Oh, I see. It's recording the entire file as changed instead of just the lines that changed.

All that's really changed in the dm's was adding the line:

species_fit = list(VOX_SHAPED) 

in like 4 places.

**Comment by ghost** [comment]
- Back your changes up
- Set up http://ss13.moe/wiki/index.php/Guide_to_Git_CLI
- Try again

**Comment by SangriaMonkey** [comment]
> greys will never get their clothes fixed

**Pull request closed without merging**
