### PR TITLE
Something stupid

### PR DESCRIPTION
**Pull request by 9600bauds**
https://dl.dropboxusercontent.com/s/b0rv0n8x6q46p1a/Desktop%2006.20.2015%20-%2001.20.08.03.DVR.webm?dl=0

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
I love you

**Comment by SangriaMonkey** [comment]
Sweet

**Comment by Boxe** [comment]
changelog

**Comment by 9600bauds** [comment]
no it's a sekrit

**Comment by CptWad** [comment]
agreed sekrit

**Comment by Iamgoofball** [comment]
oh my god

:+1:

**Comment by FudgePucker** [comment]
11/10 best idea ever.

**Comment by SkowronX** [comment]
tumblr_lljqonmhuh1qikogn

**Pull request merged**
