### PR TITLE
Adds Chocolate Cows and Chocolate Milk

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
There was an unacceptable amount of non-warm chocolate drinks, so this had to happen.
Adds chocolate milk, made by reacting 5 parts milk and 1 part coco. This reaction requires a starter sample (5u) of chocolate milk as a catalyst, which can be milked from a chocolate cow.
Chocolate milk can be turned into hot coco by warming it to 60°C.
Chocolate cows can be purchased from cargo for 45c, that's 50% more expensive than a regular cow.
image
## Why it's good
Chocolate milk.
## How it was tested
Bought a choco cow crate and opened it, cow spawned fine. Milked it with beaker, worked fine.
Reacted milk with coco and enzyme, worked fine.
Heated chocolate milk with scalpel, made hot coco, worked fine.
Electrolized hot coco, got chocolate milk, worked fine.

:cl:
 * rscadd: Chocolate cows can be purchased from cargo for 45c, and can be milked for delicious chocolate milk.
 * rscadd: Chocolate milk, made the same way as Hot Coco is (5 parts milk 1 part coco) but without heating, and requires a starter sample of chocolate milk as a catalyst. Alternatively, can be milked from the aforementioned cows.
 * tweak: Chocolate milk can be turned into hot coco by heating it to 60°C.

### CODE REVIEW

**Comment by MercuriusGH** [comment]
image

**Comment by falcon2346** [comment]
Why would it require enzyme? Last time I made chocolate milk all I needed to mix it was a spoon.

**Comment by Eneocho** [comment]
> Why would it require enzyme? Last time I made chocolate milk all I needed to mix it was a spoon.

Cause else it would interfere with the hot coco reaction by ALWAYS taking priority. Changed it to require a starter sample of choccy milk.

**Comment by angryturnip** [comment]
> Why would it require enzyme? Last time I made chocolate milk all I needed to mix it was a spoon.

It's a space cow with space lactose

**Comment by jwhitak** [comment]
image

EAAAT THIIIS!

**Comment by Eneocho** [comment]
we're sof ucking back gamers

**Pull request merged**
