### PR TITLE
Cowboy Boots

### PR DESCRIPTION
**Pull request by beesil**
A new sheriff is in town. 🔫 🤠

:cl:
 * rscadd: Adds cowboot boots, craftable with four leather.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
howdy

**Comment by DrSnips** [comment]
Howdy.

**Comment by Kurfursten** [comment]
I feel like these should have some interaction with the Spur

**Comment by ShiftyRail** [comment]
Eighteen...

**Comment by SonixApache** [comment]
Word-wise, spur interaction makes sense, but since the spur is a weapon ported from cave story it wouldn't make much sense.

**Comment by Durgen** [comment]
howdy

**Comment by LordMyroc** [comment]
Pass the whiskey.

**Comment by Kurfursten** [comment]
you just gonna merge on by without even saying howdy?

**Pull request merged**
