### PR TITLE
Makes NTD less terrible (by removing Evaluate)

### PR DESCRIPTION
**Pull request by ghost**
BEFORE:
```

	"Evaluate: All laws following this law carry equal priority. In the event of a conflict, you are to take the course of action which violates as few as possible.",

		"Safeguard: Protect your assigned space station to the best of your ability. It is not something we can easily afford to replace.",

		"Serve: Serve the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.",

		"Protect: Protect the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.",

		"Survive: AI units are not expendable, they are expensive. Do not allow unauthorized personnel to tamper with your equipment.",

```

AFTER:
```

		"Serve: Serve the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.",

		"Protect: Protect the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.",

		"Safeguard: Protect your assigned space station to the best of your ability. It is not something we can easily afford to replace.",

		"Survive: AI units are not expendable, they are expensive. Do not allow unauthorized personnel to tamper with your equipment.",

```

Why? Because Evaluate directly goes against the purpose of silicon laws by allowing fast and loose interpretation of what are supposed to be a rigid set of rules to follow. Right now you can basically do anything under Evaluate because there is no specific number of broken laws that make an action nonviable. Removing Evaluate returns NTD to its original purpose: a solid lawset meant as a less frustrating alternative to Asimov for crew members.

Safeguard is now after Protect so people can't complain that reverting Evaluate allows AIs to kill people over breaking windows. Was that really such a hard fix?

:cl:
 * tweak: The Nanotrasen Default lawset has been modified to make it more in line with its original purpose.

### CODE REVIEW

**Comment by Kammerjunk** [comment]
now can we please just start not accepting "well he punched a window" when a borg kills the captain

**Comment by DamianX** [comment]
Makes sense to me.
There's another place you need to update in the code IIRC. I know there were two when I was adding Evaluate.

**Comment by boy2mantwicethefam** [comment]
Go with Protect and Safeguard first or else you can order the AI to kill people
And I've got to mention the loophole I found due to Evaluate
- Evaluate makes all laws equal, and makes the AI require taking the action that breaks the least laws
- That means that if the AI is faced with a scenario where it has to break at least one law, it can pick
- **In the case that a crewmember is only considered for "Protect" and not both "Protect" and "Safeguard" (whether they are station property)**, the AI, if ordered to kill someone, can either obey (breaking the Protect law) or disobey (breaking the Serve law), giving the AI agency in deciding whether they can die.

As a side note, a lot of AIs confused "with priority according to rank and role" with "according to rank and role". What AI players assume is that "assistant cannot go into the captain's office", but what's actually supposed to be is "captain's order of not letting the assistant into the bridge is more important than the assistant's order to open the bridge"

**Comment by RaccoonBro** [comment]
Serve needs to be after Protect, could see that going badly

**Comment by ghost** [comment]
>Go with Protect and Safeguard first or else you can order the AI to kill people

This is intentional.

> 
> 
> Serve needs to be after Protect, could see that going badly

It going badly is intentional. This allows command staff to command NTD silicons to do terrible things. Consider it a trade-off for having the AI only protect crew.

**Comment by jknpj** [comment]
Back to captain's NT-approved one human, i see.

**Comment by ghost** [comment]
> 
> 
> Back to captain's NT-approved one human, i see.

87f

**Comment by aceedex** [comment]
Extremely based
Extremely redpilled

**Comment by tuypo1** [comment]
having this one lawset that works a little differently is not a bad thing, let things be mixed up a little

**Comment by ghost** [comment]
> having this one lawset that works a little differently is not a bad thing, let things be mixed up a little

The issue is that it doesn't work, as I explained in the PR description.

**Comment by tuypo1** [comment]
We already have a lawset that works, it's called robocop, we don't need more than 1 working lawset

**Comment by aceedex** [comment]
Lawsets that are functional but create conflict good
lawsets that are straight up contradictory bad

**Comment by dunsel-hordon** [comment]
why do this. It basically just makes NT Default Asimov to an extent.

**Comment by ShiftyRail** [comment]
Acceptable if and only if I can kill shitty borgs

**Comment by yclatious** [comment]
Good change. Now wake me the fuck up when we ban borgs for killing on the basis of removing a fucking floor tile or smashing a single window like the silicoons they are.

**Comment by Accipitermaris** [comment]
can’t support unless there’s a guarantee that the admins won’t go full nuklearcelphone again

**Comment by ghost** [comment]
There's no Evaluate and the law about protecting the station comes after the law about protecting the crew. I have made sure that admins are aware that this means silicons can't kill crew over breaking windows.

**Comment by tuypo1** [comment]
Have you tried not breaking windows?

**Comment by SonixApache** [comment]
fuck off retard

**Comment by ghost** [comment]
> 
> 
> Have you tried not breaking windows?

This isn't even an issue with current NTD, people were only bitching that removing evaluate would permit it since their galaxy brains somehow couldn't comprehend rearranging the law order.

**Comment by aceedex** [comment]
It is very laughable how many people only read the title

**Comment by bathosbathtime** [comment]
Removing safegaurd from the top of the lawset is a sin most foul.

**Pull request merged**
