### PR TITLE
Tweaks to protected roles in traitor, changeling and vampire

### PR DESCRIPTION
**Pull request by rmariani**
-Security officer and Detective moved out of "protected" for changeling
-Security officer and Detective moved out of "protected" for traitor
-Security officer and Detective moved out of "restricted" and into "protected" for vampire

This is a cleaning up of an older pr: https://github.com/d3athrow/vgstation13/pull/7756#issuecomment-173437002

People complained about moving sec officer/detective from restricted to unprotected, so I changed that. They will remain restricted, since they are loyalty implanted.

However, I removed Security Officer and Detective as protected jobs from changeling and traitor. 

The arguments for them not being completely unprotected for vampire vampire are good and the community wants that, so I merely moved detective and sec officer to protected status from restricted status. I think this is a healthy compromise. This goes in line with entire motivating principle of SS13: it isn't a completely balanced game, and players should always be paranoid. Not being able to rule more roles out as an antag while increase paranoia. (The "protected" designation greatly lowers the chance of a role being the antag in question, while "restricted" completely bars them.)

Much of he reasoning behind protecting or restricting jobs in these rounds is their armory access. Neither detectives nor security officers have armory access. Expanding possibilities for antagonists is a good thing in SS13 to keep the air of paranoia alive, so players can't just rule huge swaths of characters out. Similarly, detective and sec officers don't have power over departments like heads do for cult rounds. If it's safe for HoP, CE or QM to be cultists without a fear of imbalance, these roles will be safer yet, but the greatly lowered frequency creates a good balance between interests.

### CODE REVIEW

**Comment by Imagebard** [comment]
Nice conflicts you got there

Can you actually list what you changed again?
Form what I understand, Sec Officer and Detective is protected now. What else?

**Comment by rmariani** [comment]
They aren't restricted from vampire

**Comment by Imagebard** [comment]
Just
Just list what you changed again. Just a short list. Here's what I got so far.

Security Officer and Detective: Protected form everything but Changeling and Traitor

**Comment by rmariani** [comment]
Security officer and Detective moved out of "protected" for changeling
Security officer and Detective moved out of "protected" for traitor
Security officer and Detective moved out of "restricted" and into "protected" for vampire

**Comment by DeityLink** [comment]
> +1,339 -1,339

How the fuck? There's something really wrong here.

**Comment by LordMyroc** [comment]
I don't like it.

**Comment by rmariani** [comment]
Ok, that's not an argument though. There have been substantive arguments in previous PRs, and they were against inclusion into cult.

**Comment by DeityLink** [comment]
Seriously fix this PR, aside from vampire.dm I can't read your changes at all.

You should have 10 lines changed at most, not 1339!

What did you even change in cult.dm ?

**Comment by gbasood** [comment]
`?w=1` shows that all but 4 lines changed are whitespace changes
What.

**Comment by ghost** [comment]
Antag security is incredibly overpowered, terrible change.

They get armor, guns, bolas, flashbangs, flashes, stun batons and sec records access for free. Not to mention inherent trust enabling them to effortlessly kidnap anyone.

On meta detective gets even fucking thermals for free.

If you want people to get antag when choosing sec, make the job selector
1. PICK PLAYERS FOR ANTAG
2. PICK PLAYERS FOR JOBS BASED ON FIRST PICK.

Everyone would be able to play any job at all and get equal chances for all the antags.

**Comment by Boxe** [comment]
holy shit the non-antag sec train is still alive

**Comment by Intigracy** [comment]
tbh TermedClepe has a point.

**Comment by DeityLink** [comment]
There hasn't been any new commits to this PR in a month despite the issues we've pointed out (both balance issues and code issues).

Do you plan to address them? Or close this PR?

**Pull request closed without merging**
