### PR TITLE
full removal of islandstation from code

### LINKED ISSUE #31330: Island Station Research Station
(WEB REPORT BY: balabalalde REMOTE: 206.221.180.138:7777)
# Revision
6789b69609d1c7787640ef3d2e97e4b469abd6a8

# Description

When going to the research station as a scientist via shuttle, there are mining airlocks that science cannot open.
# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #31331: Island Station Archeology
(WEB REPORT BY: balabalalde REMOTE: 206.221.180.138:7777)
# Revision
6789b69609d1c7787640ef3d2e97e4b469abd6a8

# Description
Excavation suits in Xenoarcheology do not exist. The machines were mapped as empty.
# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #31335: Islandstation medbay issues
#### Description of issue
aux surgery table is far away from tools malding surgeons
puddle of water????? in patient room
CMO office missing many items like lights, fire alarm and cmo announcement console
Virology missing a log of shit, beakers, syringes gloves and the dishes and mutagen
cryo is not connected up properly
image

#### Server revision
Game: 6789b69609d1c7787640ef3d2e97e4b469abd6a8 
Patches: 11fb283d23ba8368ca55fda744adbc14e5a418bb 

[island]
[mapping]
[bugfix]

### LINKED ISSUE #31337: Island Station - Science shuttle docks to a miner airlock
(WEB REPORT BY: rattleseaserattles REMOTE: 206.221.180.138:7777)
# Revision
6789b69609d1c7787640ef3d2e97e4b469abd6a8

# Description
Exactly what it says on the tin, science shuttle to the outpost goes to a docking port that has a mining airlock which they dont have access too.
# Steps to Reproduce

# What you Expected
to do xenobio
# What Actually Happened
got attacked by wizards while trying to get access to do xenobio

### LINKED ISSUE #31340: Smelter in the bird trade station on island does not work
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
6789b69609d1c7787640ef3d2e97e4b469abd6a8

# Description
I tried to get processed plasma and the damn thing won't even take ores
# Steps to Reproduce
>Be shitbird
>do bird shit
>expect to be able to forge processed plasma when you drop it in front of the thing, like in all maps
>Thing not take ore and move it down belt
# What you Expected
>Basic shit to work
# What Actually Happened
>Bird cackling intensifies

### LINKED ISSUE #31341: Island: Brig review
Which is a nice way of saying "list of complaints"
the good:
 - cells are nice
 - warden's office is kinda nice, would swap the SAC and camera console
 
 
the maybe bad:
 - the security shuttle leads to an airlock that sec has no access to
 - label roll in evidence room, no labeller
 - two (2) telebeacons for exceptional access to getting telebombed
 - no secvend or table space in equipment room
 - rechargers are sparse and spaced out
 - smoke/coffevend is nice but space could be better used for other things (like a charger)
 - wind grenades in evidence, why
 - windowed brigbay feels very out of place
 - windowed brigbay made out of plasmaglass, plasmaglass should be rare
 - double-size entry doors are pretty but fucking slow
 - warden windoors are reversed, outer should be openable for non-wardens, inner should be reinforced
 
 the bad:
-  the wall lockers are a nice idea for saving space but they fucking suck for actual use
- - seriously, like, you can weld them shut and there's no sprite for it, get rid of them
- officers can't use the "courtroom transport system" windoor
- The shuttle brig external airlock is public-access.

Further review pending until a time where I can see the map without wizards immediately destroying everything.

### LINKED ISSUE #31342: Island Station Borg Chargers
There's a shocking lack of cyborg chargers for silicons to recharge with on this map, with the only ones I found during gameplay being the ones in the AI core and the ones in the MoMMI nest. If possible, it'd be good to see chargers added to;
• Engineering, near the lobby
• Somewhere on the medbay wing of the station
• Somewhere in the medical wing of the station
• Somewhere in the civilian wing of the station, maybe in a bathroom stall akin to Box

### LINKED ISSUE #31386: Island has no morgue holosign
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
1396851f9b52ee8ca6e5a6576df23dc040a044c6

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #31413: Captain's Log 165: The Longest Station
It is the indomitable spirit of Man that drives him to explore, to seek out the lands Providence has provided to us and take in their grave beauty, whether they be the hottest stars or the cold emptiness of the void. Though Mother Earth mourns the sons she may never see again we have not forgotten her, and many manmade lights dot the blackness as oases to mirror her splendor. It is one such oasis (though whether this name be apt remains entirely up to you, dear reader) that I have visited in my travels quite recently: **The Island Station.** 

The Island Station, named so for its many "islands", carries the simple naming scheme once common to sailors and reflected in many lands even today, from Long Island to Whoresfield, and is connected by many bridges.
capt7
The bridges span to and fro the entire complex, taking for themselves the lion's share of its size. The Lord above knows better than I that I have no evidence, but I'm rightly certain that the station I tread was nothing more than a scheme to create a new labyrinth, one to hold a thousand Asterions within its winding walls. There's no other explanation for the corners cut and the choices made, which I shall detail below:

**The Barren Brig**
capt9
There's often little incentive for a brig funding. The only people that'll ever see it are prisoners and, perhaps worse, the brigmen themselves. That said, there are quite a few corners cut that'd make this slice of hell more fit for a small station, certainly not one of this size. The rechargers are stacked to save space and the computers follow this grim trend. The cells are smaller than a freightship cabin and, in the builder's haste to finish the straw house, a floodlight in the south has been attached to a door. The vast, cavernous interior lobby is partitioned into offices fit only for dwarves, and this space-saving transitions on to the entire station.

**Built for Bacteria**
capt6
The entrance to the Virology is bleaker than most, a tiny room flanked by washing machines stacked atop eachother like a Haida totem pole. The only useful addition here is the ashtray, something that'll see quick use thanks to its proximity to the vendor as well as the tomblike interior of the vessel. Once past these doors a man is greeted to another tiny room the same size, but this time empty. A common legend says that at one time many washing machines lived amongst the entrance rooms, and it was only once the Virologists came bearing weapons of unfathomable fury that they were relegated to reservations, forced to live in miserable conditions on a single tile.
capt4
Here I stand with the ~~freak~~ man himself. His office, like many, isn't particularly notable, though he did find great trouble with finding his dishes, something only resolved when I opened his wall locker and they spilled onto the empty table. Why they aren't simply on the table to begin with, like every other port, is a matter of grave debate, though personally I feel that, in a moment of brief clarity, the architects personally hid the dishes after finally understanding the pointlessness of the craft.
capt3
The rest of medbay is rather unremarkable, though it seems that the builders forgot to bring in sinks at some point and and took to pouring water in a hole instead. 
capt17
And thus I leave Medbay, though while passing through I marveled at the power and influence of the Medical Reception Builder's Union, typically they only get one job per station.

**The Captain's Half Dollars**
capt2
My own office is vast, larger than a whale with only half the smell. Central Command deems fit to provide an unfinished sword in the cabinets, whether that be a symbol of the ever-unfinished work of a Captain or the laziness of the builders is up to the reader's interpretation. That isn't the end of it either, what follows is a large vault and a truly king-sized bathroom. While I'm loathe to give up the only bathroom I've ever embarked on that reflected my greatness, the vault's use is debatable on account of it's as barren as a hag and most captain's don't accumulate enough riches in the few hours we supervise to justify it. 

**The Scientist's Plight**
capt11
Over the course of my travels here I met a scientist who came to me, tears in those unfeeling scientist eyes, and cried about his unrequited love. He was wholly unable to visit the rocks he held with an almost religious reverence, and the conditions he faced in his daily work would make even a chimney sweep take off his dusty, child-sized hat in respect.
capt12
For a xenoarcheologist,  light is but a distant memory. No golden rays litter the halls like your typical department, instead the sheer darkness is meant to prepare the poor soul for what will become 40 years of their life digging for ancient spoons. The scientist, still sobbing, explained to me that the department didn't even have his tools. The 0.492126 foot pickaxe, which I am told is critical for taking useless garbage from the maw of the asteroid, was simply not provided.
capt13
He then took me to the door outside, before trying to fruitlessly open it. At this point the scientist kneeled down and tore at his garments like a biblical prophet, decrying the good name of the architects who forged this station and fate which had cruelly kept him away from his most beloved rocks. Though there were no doubt other entrances, and, as any Captain's Spare can attest, a locked door rarely keeps a scientist away, the xenoarcheologist could not find another exit. 

Now, dear reader, you may ask, "With so many corners cut, where did the funding go?". It has been made abundantly clear to me through my time aboard that the architects were less interested in making a station than making:

**The Hollow Hallways**
capt14
The bureaucrats call this land an island, though I would liken it more to a spider web. It's quite easy to be caught in the strands that line the entire station, little enclaves of emptiness to cut the departments and make any travel abroad into a week-long trek. They permeate throughout the structure, stemming from the bridge into the halls and deep into the darkest corners of maintenance that only the pipe goblins dare tread.
capt16
There lie about 16 in total and by and large serve little to no purpose that I can spy. Typically a hallway is meant to connect two rooms together, but, with a slice fit for a Gordian Knot, these areas could be cut with no grief to the crew or their fair station.

hallways

When combined with the sorry state of the brig one has to wonder at what cost the hallway budget was increased, why were these hallways, which only serve to separate the crew from their fellow man both physically and spiritually, necessary? It's clear now that this station is a mere setup to contain a greater monster, whether a half-bull minotaur or something much greater. The crew, if they can be called that, are simply set up as bait for whatever monstrosity is foolish enough to take it, only to be caught in the web woven by the grand architects of Nanotrasen. If any reader of mine dares to visit Spiderweb Station, I do ask that they carry a knife close and hold fast to their courage, for both will be necessary when the beast arrives.

### LINKED ISSUE #31436: Enginering flubs on island
(WEB REPORT BY: cptwad REMOTE: 206.221.180.138:7777)
Ce does not start with mensons (maybe this should just be added to his locker)
Secure storage starts unsecured
no welding tool closet
As the CE I cant access the windoor to the Shard chamber (secure windoor is set to security access instead of power)
No general station alerts computer readily available for the engineers

### LINKED ISSUE #31451: Island station general security feedback
Now that I played it, I can actually give it a review.

### Brig itself

- The double stacked chargers are an unnecessary innovation which looks out of pace and can make it hard to click the proper one. It also makes it difficult to use both chargers as two different officers.
- Wall lockers in armoury are counter-intuitive and don't really show what they contain. They are the same sprite as the perma ones, which again isn't optimal in term of intuition.
- The Security Cameras are the detman version because of space constraint. Yes, I don't like that innovation.
- The flow is strange, mostly because of space constraints. It almost feels like Packed level of crampyness except with less ways to customise the interior.
- As said by other people, the cells are too small and arranged weirdly.

I think it could use an overall to be more open and space-efficient without using dirty tricks like stacked chargers.

### PR DESCRIPTION
**Pull request by nervere**
This map hasn't been played in nearly two years since it got voted out. Now it's just clogging the code.
https://ss13.moe/index.php/poll/227

image

## Why it's good
No point in having an unused map in the code if no one's gonna make it a good/workable map.
I'm tired of maintaining it whenever I do a general map update, too.

Fixes #31330
Fixes #31331
Fixes #31335
Fixes #31337
Fixes #31340
Fixes #31341
Fixes #31342
Fixes #31386
Fixes #31413
Fixes #31436
Fixes #31451

## Changelog

:cl:
 * rscdel: IslandStation removed fully from code as per: https://ss13.moe/index.php/poll/227

### CODE REVIEW

**Comment by SonixApache** [comment]
o7

**Comment by Eneocho** [comment]
Only 2023 ancientplayers remember the gnome/scissor debates.

**Comment by ErrorsWindows** [comment]
😌

**Comment by nervere** [comment]
> Only 2023 ancientplayers remember the gnome/scissor debates.

Don't worry, gnomes are still in the code. The debate will rage on.

**Comment by wotisjanitor** [comment]
I like this map

**Comment by Hinaichigo** [comment]
Now that the dust has settled... is island /ourmap/?

**Comment by Kurfursten** [comment]
It can always be revived if someone wants to modernize it, you can just look back at older versions of the codebase

**Pull request merged**
