### PR TITLE
Catwalks now prevent space slipping

### PR DESCRIPTION
**Pull request by DeityLink**
Catwalks were added a decade ago by N3X15 who sampled them from Paradise. Then dylan turned them from a turf into an object. Today, they finally do what catwalks are supposed to do in real life: provide adequate footing.

:cl:
* tweak: You no longer have a chance to slip when walking on catwalks.

### CODE REVIEW

**Comment by kilozombie** [comment]
Transposing my idea from Discord: catwalks should have railings applied as an effect on top of them. Maybe even literally copying over the railing sprites/layer code, applied to every side of a catwalk which does not connect to a turf or another catwalk.

**Comment by DeityLink** [comment]
Aren't railings an actual thing in the code now? I figured I'd keep both separate.

**Comment by kilozombie** [comment]
Applying them as an effect would mean you don't have to do any mapping, and it would explain away why they actually work to stop you from slipping

**Comment by DeityLink** [comment]
I think them appearing like relatively flat surfaces compared to lattices already does that job. Anyhow this PR took me 2 minutes and I'm not planning to spend more efforts on it. Auto-railings can always be added by someone else in their own PR.

**Comment by ManopolisJones** [comment]
This doesn't really make sense, but neither does being able to walk on normal tiles without slipping out in space, so I guess this is alright.

_See:_ **Muh Immulsions**_, for more details._

**Comment by Blithering** [comment]
Clearly NT shoes have little hooks on the soles to latch onto the lattice with velcro style. Shoeless spessmen are trained to grip on with their toes.

**Pull request merged**
