### PR TITLE
adds civil protection uniform/helmet/armor to the secvend

### PR DESCRIPTION
**Pull request by gurfan**
all spritework credit goes to vonadi and buchse

The secvend has two of each clothing item in stock, under the contraband category.

metrocopalt
metrocolalt2

:cl:
 * rscadd: Added civil protection uniforms, helmets, and armors to the Secvend's contraband section.

### CODE REVIEW

**Comment by Irradiation** [comment]
Uniform is nice, but the helmet looks tooks too much like an oversized milky-white skull.

**Comment by gurfan** [comment]
> Uniform is nice, but the helmet looks tooks too much like an oversized milky-white skull.

metrocop_helmet

is an alternative

**Comment by Irradiation** [comment]
The alternative is definitely better, as you can actually see the details/curves of the mask. Looks way more like the CP is in Half-Life 2.

**Comment by gurfan** [comment]
updated with the new helmet

**Comment by Blithering** [comment]
civil protection
I've had these sitting around for a while, more alternates for the alternate pile

**Comment by Exxion** [comment]
Sides and back look fine but from the front it has a clown nose

**Comment by Gazathor** [comment]
pick up that clown, citizen.

**Pull request merged**
