### PR TITLE
Bomberman splashwork

### PR DESCRIPTION
**Pull request by DeityLink**
Behold my Gimp coderart (lol) skills
sans titre

### CODE REVIEW

**Comment by SkowronX** [comment]
not spessmen

**Comment by DeityLink** [comment]
is that a new epic maymay?

**Comment by AutismSpider** [comment]
I like it but needs to be more spessmen like

Add monkey or two and some cyborgs etc

**Comment by DeityLink** [comment]
I spent a while to make it look good like that, I can make it more spessmenlike but it'd take some time. (and I'm not doing it anytime soon either, so if it really is an issue just forget adding it for now)

**Comment by PJB3005** [comment]
Dude, this is amazing, it could maybe use some spessman elements to it, but otherwise :+1:

**Pull request merged**
