### PR TITLE
Remove scaling miner with power

### LINKED ISSUE #33717: Derelict Gas Miners are broken
(WEB REPORT BY: luzha REMOTE: 206.221.180.138:7777)
# Revision
7e36d84767d0cd0c3ab9df2d94b7751ca352e16a

# Description
C*ders fixing what wasn't broken: Gas Miners on Derelicts are not producing gas anymore.
# Steps to Reproduce
Play Derelict MoMMI and head straight to Derelict Atmos.
# What you Expected
Gas being produced.
# What Actually Happened
It wasn't, despite being functional and operating at rates higher than 0 kPa when examined.

### PR DESCRIPTION
**Pull request by adacovsk**
Couldn't get it to work the way I wanted it to work, so reverting to a state that keeps original gas miner functionality
- Closes #33717

:cl:
 * rscdel: No scaling miners with power. Returns miners to prior functionality

### CODE REVIEW

**Comment by Kurfursten** [comment]
This doesn't seem self explanatory from the code, changing the output and also no longer adding a connection?

**Comment by pedr69** [comment]
this indeed fixes the runtime, but the miners still don't even work
you _did_ test your code, right?

**Comment by adacovsk** [comment]
> this indeed fixes ~the runtime~ one of the runtimes, but the miners still don't even work you _did_ test your code, right?

I'll fix

**Comment by adacovsk** [comment]
image
I don't have the time to fix it properly, so it's best to just revert it to a usable, functional state that I have put in this PR

**Comment by Eneocho** [comment]
I think the issue is that derelict atmos (as far as I remember) doesn't have an APC, so the thing breaks because of that. Would be as simple as mapping an APC for a quick patch.

**Comment by d3athrow** [comment]
im going to fucking strangle you

**Pull request closed without merging**
