### PR TITLE
Uncucks Paramedic access

### PR DESCRIPTION
**Pull request by pwnzer185**
:cl:
 * rscadd: Paramedics don't need to ask mom to get into chemistry or surgery anymore

### CODE REVIEW

**Comment by Dacendeth** [comment]
As much as I liked playing paramedic I don't think they should have this by default, you have other useful access instead that doctors don't have do you really need to be better than a doctor in everyway?

**Comment by Tokanova** [comment]
i think paramedics are better than doctors.

**Comment by pwnzer185** [comment]
Parameds are just doctors that go out more often so I think they should have access to two of the most important parts of med bay

**Comment by Accipitermaris** [comment]
make it add just surgery so that paramedics can help save lives instead of helplessly staring at the man they injected biofoam into

(and so that paramedics don't become ubermench medical doctors)

**Comment by Dacendeth** [comment]
I could get behind giving them surgery, but chemistry is too much.

**Comment by ShiftyRail** [comment]
The unit test for slipping failed
Funny that

**Comment by boy2mantwicethefam** [comment]
Remove chemists

**Comment by tuypo1** [comment]
Just give parameds a my first chemistry dispenser that can produce exactly what is needed to mix the basic meds and nothing more

Also maybe give surgery some sort of patient delivery chute so people without surgery access can put patients on a stretcher and push them through the hole into surgery, you could even have the chute become lethal when emaged

**Comment by DrSnips** [comment]
Im for surgery but not so much on chem. Being able to at least treat critical conditions like internal bleeding rather than just put them on a hope and pray delay chem so that someone can open the door to surgery would be great.

**Comment by RealestEstate** [comment]
I have no dog in this fight, but a babbyproofed chem dispenser variant actually sounds kind of cool

**Comment by 9percents** [comment]
umm, explanation?

**Comment by pwnzer185** [comment]
ignore my tism I'm just getting my baring with doing stuff on github

**Comment by ArchSunder** [comment]
Yeah can we do surgery but not chem like others suggested

Aside from this just making parameds better than everyone bar CMO there's already enough crowding problems in medbay since chemist seems to be one of the getgo roles for refugees to pick and blankstare at the machines or make epic drugs

**Comment by strawberrytan** [comment]
isn't a babyproofed chem dispenser a sleeper?

**Comment by RealestEstate** [comment]
oh yeah I guess you’re right

**Comment by pwnzer185** [comment]
the issue is that pills are needed to go, oh and the pill bottles are baby caged in chem but I see the issues here.
Its similar to science however where ever job there should have access to the departments important rooms

**Comment by ThatRedPyro** [comment]
Adding regular pill bottles to NanoMeds on top of giving surgery access to parameds sound like the best compromise.

**Comment by Dacendeth** [comment]
Just put your pills in a bag of dice like a real doctor would.

**Comment by Killette2** [comment]
My tactic as a paramedic is grab slamming patients through the observation room to break the glass and get to the tools. It's just as efficient

**Comment by ghost** [comment]
Paramedic is a higher pop role intended to support a fully staffed medbay. If you want full medbay access, play MD or pharmacist. If you need maint access because there's no parameds, go to the HoP. Or play paramed and ask for full medbay access.

**Comment by Kurfursten** [comment]
You have been visited by the mistake of not making a new PR after significant changes
Phantom downvotes will stay with you regardless of if those people ever view this PR again

So we have no way of knowing how popular this is post-changes.

**Pull request closed without merging**
