### PR TITLE
fixes #7108

### LINKED ISSUE #7108: Girder sprite is on the layer under pipe sprite
isthataguuurderunderpoiips
lookathatguuurder
I don't know how many other items act like, but girders shouldn't look like they're under pipes.

### PR DESCRIPTION
**Pull request by ghost**
fixes #7108

### CODE REVIEW

**Comment by clusterfack** [comment]
Uh I think layer may be a bit more nuanced than that? I think there are a LOT of things between 2 and 3

**Comment by ghost** [comment]
layer 3 is the default layer for machines and such

**Comment by Exxion** [comment]
So maybe use the define
I'm like 80% sure there is one

**Comment by ghost** [comment]
fixed

**Comment by clusterfack** [comment]
100% tested? I hope so!

**Pull request merged**
