### PR TITLE
Deff Maintbear: Revengance

### PR DESCRIPTION
**Pull request by Kharkov72**
[deff]
Oh no, it looks like the last time the circus was in town, Kuma the bear slipped on a bluespace tomato and landed in maint, and has been living there ever since!
Untitled

FREE HIM.

fuck you duny

:cl:
 * rscadd: Kuma the bear is ready to hug you on deff!

### CODE REVIEW

**Comment by Lunstra** [comment]
Free my nigga the maint bear

**Comment by ShiftyRail** [comment]
Maybe add a paper saying "don't bear open inside" next to it.
It's not like anyone will notice or read it.

**Comment by Gazathor** [comment]
A great power shall finally be released from its prison

**Comment by Kharkov72** [comment]
Untitled
Slight update, adding a bit more blood, a painting, and a GLOWING voucher for the bear to be allowed back on station.

**Comment by SonixApache** [comment]
IT'S NOT MAINTENANCE

you should put that on the door's description

**Comment by Kharkov72** [comment]
I gave that to the bear.
If some oldfag remembers what he would ACTUALLY call it I'll put that on the door

**Comment by SonixApache** [comment]
derelict
all those parts of the station are 'derelict'

**Comment by Kurfursten** [comment]
Leather whip is very very strong as guaranteed maint loot and this bear is easy to cheese

**Comment by Exxion** [comment]
I like this because bears let you flex on people who don't know their obscure easter eggs

**Comment by jknpj** [comment]
missing a FUCK YOU DUNY decal

**Comment by ShiftyRail** [comment]
Plenty of support

**Pull request merged**
