### PR TITLE
[Mapping] Vox Seed Vendors

### PR DESCRIPTION
**Pull request by Kurfursten**
This is amazingly not the smallest map PR I've ever done.

Changes "hydro" to "vox" in four locations.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I thought about it and I decided there was a good reason to add a changelog.

**Comment by Imagebard** [comment]
What do Vox seed vendors have again? The vox fruits you've PR'd a little while ago and a few extra ones that are also default on the main station, right?

**Comment by Kurfursten** [comment]
No, nothing from that PR is currently obtainable

> Why vendors?

From the beginning the new plants were supposed to replace "normal" plants for Vox so their botany would feel more alien, and also encourage trade. For example, Vox can't cook their Flammkuchen without acquiring cheese from humans, and humans may want garlic or gravy in turn.

**Comment by ghost** [comment]
> From the beginning the new plants were supposed to replace "normal" plants for Vox so their botany would feel more alien, and also encourage trade. For example, Vox can't cook their Flammkuchen without acquiring cheese from humans, and humans may want garlic or gravy in turn.

This is pretty neat. :ok_hand:

**Comment by Kurfursten** [comment]
Whoops I misread that and can't edit from mobile. Sorry! You are correct, check the wiki Guide to Vox Hydroponics for a full list.

**Comment by Imagebard** [comment]
>Grand total of 4 seeds normally and 7 total, 1 being glowshrooms and the other being NOFRUITSEED

I think you should add some a normal seed in case nobody comes in to trade, likely wheat.
Other than that :+1:

**Comment by Kurfursten** [comment]
Wheat, sugar, and tower caps are covered by breadfruit and woodapple. I thought this one through.

Not suit can allow them to ' research'  new seeds
Glowshroom for Vox outposts without chemistry so they can do mutations

**Comment by Kurfursten** [comment]
Nofruit*\* can

**Comment by ScrambledSteak** [comment]
fun fact: vox raiders ship has the seed&feed

**Comment by Kurfursten** [comment]
No, that was @Praecordia being a funmin and spawning one for the Vox

**Comment by ScrambledSteak** [comment]
oh

**Comment by 9600bauds** [comment]
Oh look at this green label I'd better merge it I sure hope nothing conflicts

**Comment by ghost** [comment]
BAUDS WHY

#10502 IS UP YOU JUST CONFLICTED IT

**Comment by 9600bauds** [comment]
I was under the impression maptools would make it not-conflict

**Comment by Intigracy** [comment]
They edited the same tile.

**Comment by 9600bauds** [comment]
haha oops

**Pull request merged**
