### PR TITLE
Black Market Culling

### PR DESCRIPTION
**Pull request by bathosbathtime**
This pull request removes several items from the black market.  This includes the portal gun, emagged nikita, and the potions.  It also comments out the arcane and the technology sections as no items would use those categories.  They are left in to easily readd if a new item would fit in.

I believe these changes are for the best.  Adminbus items and wizard potions should not be readily available to the crew.  The black market itself has promise that is marred by a few items that bring it down.  I believe these items being removed will improve the image of the black market while also making room for a better selection of items.  This is PR two of four.
Compiled and tested locally.

:cl:
 * rscdel: Removes the portal gun, emagged nikita, levitation potion, and health/death potion from the black market

### CODE REVIEW

**Comment by ghost** [comment]
The black market update 2.0 removes all of these except loot box and emagged nikita. Cough, cough.
I would like to keep the emagged nikita, it has it's meme value, but I think making it a 10% or lower chance to spawn would be fine.

**Comment by utilitas-** [comment]
i thought this pr was about culling the black market, not slapping it on the wrists

**Comment by SonixApache** [comment]
\>this after #23698
🤔

**Comment by DrSnips** [comment]
:+1: for most things. :-1: for lootboxes being removed.

**Comment by bathosbathtime** [comment]
Well, I've readded the lootbox.  Please adjust your reactions.
Feels weird to have it and not the nikita but at least it doesn't leave a bunch of rockets laying around I suppose.

**Comment by SonixApache** [comment]
Please remove the lootboxes.

**Comment by DrSnips** [comment]
Some fun stuff should exist and it's the closest thing we have to illegal as a meta joke.

**Comment by bathosbathtime** [comment]
It is a good addition to the black market and I personally regret even thinking of back tracking on it.  It fits the market, in both as a joke about gambling and in that it kills the user.  It isn't as obnoxious or destructive as it Nikita counterpart as it only kills the user instead of causing a rocket sized explosion.
I genuinely believe that the lootbox is perfect in a limited, somewhat obscure supply.

**Comment by SonixApache** [comment]
literal joke items that kill you without explicitly stating that they kill you are trash
keeping it in will forever continue to mark the black market as a meme dumping grounds

**Comment by DrSnips** [comment]
t. mr. I need everything spoonfed to me.
Play the game or talk to others to learn for once. Space bears don't have anything that lists that they will hit you like a truck despite their cute appearance but you likely found out how they work after the first time or by word of mouth. 
Stop being a big box baby.

**Comment by bathosbathtime** [comment]
You're overstating the affect of a single joke item that will fool someone all of one time if they ignore the warning signs around it.  The market can survive such a blow.
While I'm hesitant to compare a box that kills you to a bear, anyone buying a strange box off an illegal market should be ready for bad things to happen.

**Comment by SonixApache** [comment]
Everything else you can buy off the thing isn't as dangerous (except the nikita but I like to pretend that doesn't exist). There's no clear indication that it'll kill you - it's just a purple toolbox with stickers on it. 
I don't know a lot of people that think hanging around bears is a smart idea, regardless of how cute or 2dimensional they are.

**Comment by bathosbathtime** [comment]
The potion of health has a 60% chance to outright kill you and the baby carp is a hostile mob.
There are dangerous items on the black market, and that's fine.  It is an illegal market, after all.

**Comment by SonixApache** [comment]
if it's illegal then why is it so easy to access?

**Comment by bathosbathtime** [comment]
I'm not sure why you're trying to say the 'black market' isn't an illegal market or why being easy to access would be a point against it.
wish dot com isn't hard to use and yet there are plenty of less than legal goods on it in our real life flesh space, so it isn't a realism argument you could use.
It alerts security on random chance during use for certain items, mechanically implying it is illegal as well.
"The black market isn't an illegal market" is a stupid point, is what I am saying.  I know you get confused a lot so I thought I would spell that out for you.

**Comment by SonixApache** [comment]
A 'black market uplink' literally spawns on the bridge. Nobody has ever been arrested for buying anything off the black market. Saying it is in any way illegal is an absolute joke.

My point still stands; retaining dumb items that literally only exist to kill people once before they figure out that it only exists to kill them once is bad.

**Pull request merged**
