### PR TITLE
Adds asleep screen alarm for humans

### PR DESCRIPTION
**Pull request by jknpj**
Here you go @SonixApache 

:cl:
 * rscadd: Adds sleeping screen alarm for humans

### CODE REVIEW

**Comment by Tokanova** [comment]
based

**Comment by DamianX** [comment]
can we get a sound played when the alarm clears so I know when to tab back in?

**Comment by jknpj** [comment]
get me a good sound and i'll do it

**Comment by Zth--** [comment]
https://www.youtube.com/watch?v=6Wq-ku3AwTA

**Comment by SonixApache** [comment]
https://www.youtube.com/watch?v=7vObEK3Lbp4

**Comment by DamianX** [comment]
here, sampled [wakeup.zip](https://github.com/vgstation-coders/vgstation13/files/3913783/wakeup.zip)

**Comment by jknpj** [comment]
i said a *good* sound

**Comment by Zth--** [comment]
>he doesn't want to add wakeup.zip

ok then

**Pull request merged**
