### PR TITLE
Hotfix for scientist biosuit overlay iconstate being wrong

### PR DESCRIPTION
**Pull request by gbasood**
Cause was an inconsistency between the item's icon state and the overlay's icon state. Changed the icon state in icons/human/suit.dmi to fix this

### CODE REVIEW

**Comment by ghost** [comment]
Pics? Explanation?

**Comment by Exxion** [comment]
Why is it that the better a coder is the less they write in explanation of what they do?

**Comment by gbasood** [comment]
@DrCelt 
 This is how they look now
 After PR

**Comment by gbasood** [comment]
Cause was an inconsistency between the item's icon state and the overlay's icon state. Changed the icon state in icons/human/suit.dmi to fix this

**Comment by gbasood** [comment]
Also since I ACTUALLY TESTED THIS AND ITS A HOTFIX
TIME
TO
SELF
MERGE

**Pull request merged**
