### PR TITLE
Adds silencer compatibility to the NT USP

### PR DESCRIPTION
**Pull request by SonixApache**
If you manage to get a silencer somewhere, you can stick it on your USP. 
Equipping it lowers the firing sound by about half, and removes 'x fires the NT USP' messages. Same as with other silenced guns.
hush

Sprites by @Blithering

🆑 
- tweak: You can now attach a silencer to the NT USP.

### CODE REVIEW

**Comment by ghost** [comment]
Maybe a limited supply of silencers should be added to the armory? Probably a bit too much for only one gun, but how else can you be tactical without having it spawned/wizard using summon guns

**Comment by SonixApache** [comment]
There's a silencer in the meta armory. I could add one to the secure lockers of deff and box, if needed.
Really don't want to have to touch the mapping tool unless I really have to, might be better to put it up as issue for a seperate PR.

**Comment by yclatious** [comment]
Wait, why would the police or security force on a research station need silencers roundstart? I mean, they look good and I don't hate them being a thing, and if sec rped it as only a armory thing for no earmuffs, sure, but that won't actually happen.

**Comment by SonixApache** [comment]
Well on meta the locker contains a bunch of other contraband shit. So it fits there.
On box it contains a laser rifle, and on Deff it contains a grenade launcher I think.
So, there's no real need.

**Comment by yclatious** [comment]
*shrug

**Comment by SangriaMonkey** [comment]
They're not a make-or-break thing to have.

**Comment by ScrambledSteak** [comment]
make it so if you shoot ballistic weapons enough it'll start to make you deaf unless you have a silencer or are wearing earmuffs.

**Comment by SonixApache** [comment]
no

**Comment by CptWad** [comment]
>silencer

>not suppressor

**Comment by SonixApache** [comment]
It's called a silencer in game, I dunno who made it in the first place but I honestly don't care enough to change it.

**Comment by Blithering** [comment]
Any other guns you reckon should be compatible with the silencer?

**Comment by Sprok0** [comment]
The SMG maybe?

**Comment by Riekland** [comment]
psst
add a .45 and a 9mm suppresor and make sure that they only work on the guns that take that specific round
don't make me ree at you

**Comment by Sprok0** [comment]
It's a space silencer, your gun autism doesn't need to apply

**Comment by Riekland** [comment]
WAIT NO
Add a suppresor attachment that you use on air tanks to turn them into a can suppressor
make it craftable and all but it has a chance to break/not suppress the sound

**Comment by SonixApache** [comment]
@Blithering Any non-shotgun projectile weapon could theoretically use it, but I honestly don't think they're used enough to warrant it.
@Riekland i don't know how to code or i would

**Comment by SonixApache** [comment]
gun.dmi is my mortal fucking enemy holy shit i'll fix this tomorrow

**Comment by SonixApache** [comment]
god bless the waffle

**Pull request merged**
