### PR TITLE
Revert "Slight decrease in initialization time."

### PR DESCRIPTION
**Pull request by Intigracy**
Reverts d3athrow/vgstation13#5744

Let's see if this might fix this issue: 
#5776

### CODE REVIEW

**Comment by Intigracy** [comment]
I can't think of anything else that would have caused it that was merged in the last 24h.

**Comment by clusterfack** [comment]
I can't see any reason why these would be related

**Comment by N3X15** [comment]
This will fix roundstart freezing (since it'll wait for it to finish before presenting roundstart screen) but will not fix round END.

**Comment by clusterfack** [comment]
So it fixes an issue that doesn't exist

**Comment by Probe1** [comment]
Reverting this did not help

**Pull request merged**
