### PR TITLE
Change flashlights to run on batteries

### PR DESCRIPTION
**Pull request by ghost**
This changes flashlights and all sub-types (except for flares, slime lamps and penlights for obvious reasons) to run on batteries. They start with a standard 1000 W battery and currently consume 2 W per tick (which lasts for roughly 16 minutes, assuming no lag, battery not changed and constant use, otherwise it naturally lasts much more)
- Updated blinding people with flashlights to actually use eyecheck()
- If you are blinded with eyewear that amplifies blinds (prescription or NVGs), you will be stunned for a short period of time (SHORT, 2.5 seconds for prescription and 5 for NVGs)
- Flashlights, lamps (both types) and lanterns now use batteries. They have sprites specific to it
- You can now open the cover of those three light appliances with a screwdriver, once the cover is open you can examine the light appliance to see the charge level. If the battery runs out the light shuts off. Naturally, high-caps can be put in batteries to have a flashlight that doesn't suck (even a 10 000 W will give a solid flashlight)
- When under a certain power threshold (40 % currently), appliances that run on batteries will start flickering. All flashlight sub-types except slime lamps and flares (due to particular coding) will flicker if a ghost spooks them
- Experimental rework on SetLuminosity code when flashlight sub-types are handled, it seems to work in general, although old problems might still persist (one about force-dropping items apparently)
- Flares start brighter (from 4 to 6) but dim rapidly (goes to 5 near instantly, then slowly degrades). This allows one to estimate how much fuel is left in flares and makes the area moodier as the flare burns out
- Give lanterns a in_hand sprite, and give all flashlight sub-types different in-hand sprites when lit or not (was not tested due to a .rsc file lockup, but it should work, SHOULD)
- Move flares from the generic left/right in_hand file directly to the flashlightsnlamps dmi
- Update descriptions to be less boring
- Flashlights from the autolathe start with no batteries. Apparently systems that use batteries will be included with ghettochem, and free public batteries are not an option, fine then

Discuss below

### CODE REVIEW

**Comment by Exxion** [comment]
The use of W as a unit of energy (rather than power) irks me, but I think it's also present in existing code for some reason

**Comment by dylanstrategie** [comment]
Well, technically discussing power as watt output is much easier than using volts and amperes. It's just power, our powernet barely simulates anything, so here's that

**Comment by Senaat1** [comment]
I don't see what the use in nerfing something that is underused and mostly harmless is. What does this add? And it makes no sense for a single battery to last as long as a flare does.

**Comment by 9600bauds** [comment]
You should make them use the 500 watt AA batteries we have in the code, and change the power consumption to be 1-2W at best.

**Comment by dylanstrategie** [comment]
This is impossible to go from an unending, magical light-source to a realistic power source running on batteries without a "nerf", but the nerf just means that if you turn a flashlight on and throw it someone as the beacon of hope for the next century, it'll quickly run out

Also the main problem here is scaling, as with most things. Making power consumption even lower would make any decent battery light the battery up forever, and picking a base battery that is too low gives no time to use whatsoever. 1000 W base with 5 W/2 sec seems like a decent balance between usability and needing to actually mind your flashlight usage

**Comment by Probe1** [comment]
*from irc*
><dylanstrategie> 5 W per 2 seconds means a standard cell should last, roughly 200 ticks or 400 seconds
<dylanstrategie> Aka 6 minutes and 40 seconds
><dylanstrategie> And of course if you cram a high cap in there, which is 10k W, you have a flashlight that lasts 4000 seconds or nearly 3 hours 

having batteries for flashlights is whatever, no one was asking for it or wants it but it won't break the game to have it.  having flashlights run out in 6 minutes is dumb.  halve it to 2.5 watts or 3.  or better yet, code a new flashlight that emits more light but requires batteries.

**Comment by Senaat1** [comment]
I get that you want to make it realistic, but is this a needed change? Flashlights are really niche as it is because PDA flashlights do something similar and don't take up an extra inventory space. And if you want it to be realistic, the flashlight would last for hours. Batteries don't run out in mere minutes in real life either, they can go for hours and hours.

**Comment by dylanstrategie** [comment]
PDA lights were already nerfed because your PDA is basically a free inventory slot (it fits on your ID, and no-one in their right mind would discard something that fits on their ID slot and fits their ID) and old PDA lights lit up things well enough to obsolete flashlights unless you wanted to be a beacon of light

Flashlights aren't really niche, if you want to see anything other than structure (mesons exist) then you pull up a flashlight and instantly uncloak most of the darkness around you. Also I'm currently working to strike a balance between batteries running out too soon or lasting too long. Batteries don't run out quickly in real life too, but even then rounds last 3 hours, not two months

**Comment by NigglyWiggly** [comment]
>code a new flashlight that emits more light but requires batteries.

Yes please.

**Comment by Senaat1** [comment]
Now that's a good idea, Niggly.

**Comment by dylanstrategie** [comment]
Not a single step between 1000 W batteries and 10000 W batteries. No 2500 W, no 5000 W, nothing. Why not I guess ?

I'll plop power usage to 3 W, this way the batteries last a whole 11 minutes and a scrap. That's almost double, for a shitty starting battery that is so shitty that the only power cells publicly available are 10k W

I guess somewhere in the distant future I could check battery charge, but I'd rather have flashlights with batteries now

**Comment by NigglyWiggly** [comment]
@Senaat1  Well @Probe1 did say it first.
I guess batteries in regular flashlights could work if they recharged automatically or something, make it dependent on how many steps you take or something so you can explain it off as one of those shake-recharge flashlights

**Comment by CptWad** [comment]
:-1: No regular flashlights are fine we dont need this tier of realism ever. The point of flashlights is to provide light. They were nerfed that now you can only rarely find them over flares in emergency toolboxes. Outside of that making them last a certain amount of time is not fun. I also speak for the thread in the dissagreement.
@NigglyWiggly That is a better solution. So long as flashlight lights are not still nerfed in the process.
@dylanstrategie No stop thinking what you would rather have and think what everyone would rather have

**Comment by dylanstrategie** [comment]
The chance of finding flashlights in emergency toolboxes should be even with other spawns (so it might be 1:3, because you have flares AND a flare box), furthermore, you ca

**Comment by Senaat1** [comment]
Oh, well, fuck Probe1 i guess, it's your idea now Niggly. And i agree with you, Wad.

**Comment by dylanstrategie** [comment]
The chance of finding flashlights should be 1:3. Besides, you can autolathe an infinite amount of flashlights for minimal mineral investment, whereas flares burn out fairly quickly and are finite

When a flare is burned out, it's done, down the disposal bin it goes, when a flashlight is drained, you screwdriver the cover and pop a new cell. Hell, you can just grab a high-capacity cell before heading out, they are publicly available, and have a flashlight using the old system, because the power drain is so uneven between battery tiers that a 10k W lasts 3333 seconds, that's a lot of seconds

The comparison you make is simply invalid, a flare is finite and one it burns out, it's done. Hell, this PR nerfs flares by having them get weaker and weaker as they burn out. Flashlights last as long as the battery lasts, and while there is flickering on low charges levels, this is a pretty gimmicky idea and I'll remove it if it proves to be too annoying

Also, stronger flashlights are useless. One upgraded PDA with a flashlight is 6 tiles of light coverage. The cap is at 8 tiles (your visibility range)

**Comment by CptWad** [comment]
Flares are supposed to be finite
Flashlights are not
This is videogames. We don't need the flashlights to be finite.
And really if I want to see in the dark I don't *need* light, just mensons.
An upgraded PDA is not something everyone gets. Thats its own economy issue but fuck man **The thread and I personally agree we dont want this.** 
You have a magic aura about you that makes you want to nerf things. One anon says that you deliberately have singled out engineering as where you nerf things.
pls stop dylan I think you are capable of more than pissing off people.

**Comment by dylanstrategie** [comment]
I know and have played a LOT of videogames where flashlights are finite, and I did my best to avoid shitty "ten-second flashlights" while giving people an incentive to turn off their flashlights once they're done patrolling in Maint

I didn't add batteries to flashlights because I hate Engineers, or because I have a fetish for nerfing shit, I added batteries to flashlights because it would fit that devices run on batteries. Currently flashlights just magically produce light and that's it, and many, many devices use batteries and no-one complains. Space heaters and freezers, energy weaponry, stun batons and such. You could say "no-one uses them for it to matter" or "it's important that you can't spam them", it's a case of glass half full or glass half empty, nothing more nothing less

People generally don't get upgraded PDA lights because they aren't needed, or for the same reason they don't set their suit sensors. You have to physically step up to an upgrade machine, slap your PDA in here and work through a menu just in the eventuality you are caught in a general black-out

The thing is, it's a change that can only happen through a nerf, but the goal isn't to nerf flashlights, it is to have flashlights use batteries, otherwise I would have called this PR the flashlight nerfing PR, and maybe reduced luminosity too or whatever. Making it so that flashlights are no longer infinite is obviously a nerf by any standards, but I'm trying to limit the impact to put the mechanic above the gameplay impact if there is

Eventually this opens up a lot of possibilities, EMPing or sabotaging flashlights by fucking with their power cells (rigged powercells don't seem to work from what I've seen, oddly enough), making darkness a tad more daunting (which was started by nerfing PDA lights, which, again, used to light up entire maintenance shafts without effort) and generally adding more flavor

**Comment by dylanstrategie** [comment]
Flashlights now consume 2 W per 2 seconds. At this point they last as much as the longest flares (flares have random amounts of fuel). The difference being that they don't significantly degrade when they run out, don't have annoying red color, can be turned off when needed, can be recharged, and can be upgraded to basically last forever if desired on publicly available cells (high caps that start in areas as public as the Tool Storage)

At this point it's all about making flashlights work on cells, any pretense of a nerf has basically been wiped off the board, which I guess is fine if we keep the system change

**Comment by d3athrow** [comment]
Is it impossible to assume that in the future they have the flashlights that you can keep charged up using a dynamo?

**Comment by Senaat1** [comment]
Ooh, a hand-cranked battery charger would be nice, like in Metro 2033.

**Comment by dylanstrategie** [comment]
Well, they could have it, but it's Nanotrasen we're talking about here. The same company that makes their state-of-the-art silicon units run on commercial-grade power cells

Though I wouldn't see any problem with a portable cell charger, dynamo-style, but then it'd take more time than walking up to a public cell charger and charging the cell, and still require taking out the cell

**Comment by d3athrow** [comment]
>commercial grade power cells

>capable of outputting up to 25,000 watts

Y'know what, go fix some bugs instead of being retarded dylan.

**Pull request closed without merging**
