### PR TITLE
Adds [youtube] option for bbcode

### PR DESCRIPTION
**Pull request by clusterfack**
Needs a bit more testing by our goonchatters so we can be sure that goonchat isn't killing people who gets link sent to them

### CODE REVIEW

**Comment by clusterfack** [comment]
Yes I can confirm having a link sent to your chat in this manner will fucking destroy you through goonchat, though god knows why

**Comment by Shadowmech88** [comment]
>having a link sent to your chat in this manner will fucking destroy you

Is it safe to merge, then? Could players crash other players just by saying [youtube]link[/youtube] in OOC?

**Comment by clusterfack** [comment]
Haha what, no this is for nanopaper. It actually kills admins since goonchat automatically takes a regular encoded link described here in the message admins proc and tries to play it. 

Which creates a million instances of goonchat and crashes your computer given enough time.

**Comment by clusterfack** [comment]
To be honest it should be surprising its even tbat contextually clever. But equally horrifying since it crashes your computer with NO SURVIVKRS.

**Comment by Faptastic** [comment]
Would this work for direct webm links with a slight modification?
I got webm working on nanopaper by simply modifying the type variable to use vlc. Problem with that is it needs vlc.

**Comment by SkowronX** [comment]
clusterfack is right. I think he was a victim of when I attempted to use narrate to post a video. Unless that issue is fixed with this pr, :-1:

**Comment by Iamgoofball** [comment]
just scrub for video embeds in the proc reporting this shit to admins

**Comment by Shadowmech88** [comment]
>Problem with that is it needs vlc

That's fine. Most people have VLC anyway in order for the jukebox to work.

**Comment by clusterfack** [comment]
@iamgoofball that is not the problem

**Comment by clusterfack** [comment]
We've found the problem in goonchat, it's separate from this, and this PR wont cause it.

**Pull request merged**
