### PR TITLE
Prevents Space Heaters and Cult Forges from heating up the non-existent atmosphere of a vacuum

### LINKED ISSUE #22706: Construct Health bug
(WEB REPORT BY: salmonistasty REMOTE: 206.221.180.138:7777)
# Revision
a7fe90035c38e7f62b461cf4cd2f175b504e25b4

# Description

HEalth constantly keeps decreasing, there is a fire icon 

# Steps to Reproduce

I have no idea, i was turned into artificer and the other guy was turned into wraith and both our health bars kep decreasing as if we were on fire

# What you Expected

not to die

# What Actually Happened

Health bars kept decreasing

### PR DESCRIPTION
**Pull request by DeityLink**
A more thorough fix would be to prevent heat transmission altogether in a vacuum but lots of shit relies on it and I don't want to break everything.

Fixes #22706

:cl:
* bugfix: Space Heaters and Cult Forges can no longer heat up a room that's in a vacuum, causing mobs to take damage even though there is no molecules with which to exchange temperature.

### CODE REVIEW

**Comment by gurfan** [comment]
huge buff to forges in space

**Comment by DeityLink** [comment]
> 
> 
> huge buff to forges in space

They still heat humans. Just not constructs.

**Comment by SonixApache** [comment]
>//[...] vaccum

**Comment by DeityLink** [comment]
@ShiftyRail Are you seriously downvoting a bugfix because it no longer causes constructs to randomly die in space bases?

**Comment by DeityLink** [comment]
> 
> 
> > //[...] vaccum

My computer disagrees 
image

**Comment by DeityLink** [comment]
oh wait the typo is on the comment

**Comment by Eneocho** [comment]
How will I heat up my vacuum now?

**Comment by DeityLink** [comment]
Just microwave it.

**Pull request merged**
