### PR TITLE
Fixes not being able to attack mime goblin with items

### LINKED ISSUE #25481: Mime Goblin and attacks
(WEB REPORT BY: kirbythewizard101 REMOTE: 206.221.180.138:7777)
# Revision
d714f40cad6e025306aefdd8bc7b079d84fd21bb

# Description

Can ONLY hit a mime goblin with fists or by throwing something at it

# Steps to Reproduce

Try to attack it with anything else duh

# What you Expected

To hit the mime goblin normally

# What Actually Happened

I couldn't hit it and felt like a catgirl with 200 brain damage

### PR DESCRIPTION
**Pull request by Zth--**
Closes #25481 

:cl:
 * bugfix: Fixed not being able to attack mime goblin with items

### CODE REVIEW

**Comment by jknpj** [comment]
pretty sure this is supposed to be a feature... but only to cluwnes.

**Comment by SonixApache** [comment]
attacking them just isn't supposed to do damage
cluwnes and their subtypes can only be defeated with forbidden knowledge

**Comment by Caboozles** [comment]
This nerfs mime goblins. I strongly disagree with this on a spiritual level.

**Comment by Zth--** [comment]
You can still kill them with punches. So what's the bug here? them being attackable?

**Comment by Zth--** [comment]
I couldn't care less about this

**Comment by MadmanMartian** [comment]
but, that was fixed for cluwnes...

**Pull request closed without merging**
