### PR TITLE
Re-adds forges

### LINKED ISSUE #21230: [Cult] Summon Forge not working
(WEB REPORT BY: tobiaskunst REMOTE: 206.221.180.138:7777)
# Revision
4844c533ed116308b5a4b00525eaa5c77277ad61

# Description
Cultists are unable to summon a forge with the "Raise structure" rune when reaching the second phase of the cult (ACT II: The Sacrifice). The bug remains throughout the other phases.

Being unable to summon a forge results in a round breaking bug, since the cultists need a cult blade which can only be obtained by a forge to progess into the next phase.
 

# Steps to Reproduce
Reach the second phase: (ACT II: The Sacrifice)

Trace a "Raise Structure" rune

Use "Raise Structure" rune

# What you Expected
Get a selection between summoning a altar,spire or forge.

# What Actually Happened
Get a seletion between summoning a altar or a spire.

### PR DESCRIPTION
**Pull request by ShiftyRail**
God dammit
Closes #21230

### CODE REVIEW

**Comment by Kammerjunk** [comment]
Wait so
without reading any of the cult code, why does this fix it

**Comment by ShiftyRail** [comment]
```dm
	if (veil_thickness == CULT_ACT_I)
		var/spawnchoice = alert(user,"As the veil is getting thinner, new possibilities arise.","[name]","Altar","Spire")
		if (spawnchoice == "Spire")
			spawntype = /obj/structure/cult/spire

	else if (veil_thickness >= CULT_ACT_II)
		var/spawnchoice = alert(user,"As the veil is getting thinner, new possibilities arise.","[name]","Altar","Forge","Spire")
		switch (spawnchoice)
			if ("Forge")
				spawntype = /obj/structure/cult/forge
			if ("Spire")
				spawntype = /obj/structure/cult/spire
```
If the first check is by `>=`, it catches cases that should be handled by the second check.

**Comment by iFlashYou** [comment]
speed merge

**Comment by bathosbathtime** [comment]
This feels like something that really should be speed merged.  Cult can't progress without the forge, correct?

**Comment by ShiftyRail** [comment]
@bathosbathtime They can't. In the meantime, admins should just spawn one on request.

**Pull request merged**
