### PR TITLE
You can pat/punch AIs

### LINKED ISSUE #18179: Can't punch AIs
#### Description of issue
It is impossible to punch AIs.

#### Steps to reproduce 
- Be spessman
- Click AI with nothing in hand
- Watch as nothing happens

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by DamianX**
Closes #18179
image

:cl:
 * rscadd: You can now pat/punch AIs.

### CODE REVIEW

**Comment by SageOfLight** [comment]
It'sa feature.

**Comment by SonixApache** [comment]
yes
*YES*

**Comment by jknpj** [comment]
This makes wizards able to safely punch AIs to death with the Fist spell.

**Comment by DamianX** [comment]
Did not think about it but I am okay with it. They would need vision with the scrying orb or similar, anyway, right?

**Comment by jknpj** [comment]
No because the spell is broken but no one cares i guess

**Pull request merged**
