### PR TITLE
should fix invisible coats again

### LINKED ISSUE #24229: Bartender Coat (And Probably Others) Still Broken
Icon state is invisible, it's a broken sprite. Its item state (on the wearer) is just a basic winter coat until you toggle the hood.

Hood up sprite is layered wrong, it covers the human's head even when facing down (so you have a black void face)

Apparently can't hold a shotgun, though it's supposed to

### PR DESCRIPTION
**Pull request by SonixApache**
fixes #24229 

doesn't fix all the issues (certain coats don't have proper obj icons for their hooded variants) but whatever

🆑 
 - bugfix: invisible paramedic / bartender / mechanic coats should be fixed

### CODE REVIEW

**Comment by Kurfursten** [comment]
does this fix them in their default state when you spawn them before you've done any hood toggling?

I have a suspicion that the item_state isn't set in the definition

**Comment by ComradeDispenser** [comment]
Can you make the bartender coat hold the regular pump shotgun for snowmap, since the bar has one of those instead of a double barrel? The regular armor the bartender spawns with can hold the pump shotgun already.

Speaking of which, does the bartender coat have armor value to it like the security coats do?

**Comment by robosperg** [comment]
bartender coat has no armor

**Comment by Probe1** [comment]
@SonixApache Answer Kurf pls also CONFLICTRU

**Comment by SonixApache** [comment]
effort

**Comment by DrSnips** [comment]
We did it boys we defeated winter coats.

**Pull request closed without merging**
