### PR TITLE
Anti roundstart-rule-dodging mechanism

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[gamemode]

## What this does
using syndicate traitors ruleset as an example, detects that if another traitor slot could've been available with one extra player in similar conditions, it auto assigns the next latejoiner to roll for traitor, with all conditions attached. (such as lowering chance of successful role if they join as sec, eliminating it if prefs are off, etc) 
## Why it's good
stops a way for players to ensure they avoid being antagonist without just turning the pref off.

## Changelog
:cl:
 * tweak: Players who join just after the start of a shift will no longer easily avoid the syndicate's recruitment.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
based

**Comment by gurfan** [comment]
Honorable mention for dumbest pr of the year, congratulations!

**Comment by jwhitak** [comment]
This guarantees an antag roll to the first person late joining in the rare circumstance that not all the tator slots were filled. It causes the actual opposite of the problem you describe.

People don't normally try to dodge round start antag by late joining, they dodge it by turning off their preferences. If this PR passes, sec should metagame the first latejoiner of the round, every single round. Just in case.

**Comment by SECBATON-GRIFFON** [comment]
> This guarantees an antag roll to the first person late joining in the rare circumstance that not all the tator slots were filled. It causes the actual opposite of the problem you describe.

i mean i hope that's not what happens. isn't there even a 50% chance they get the roll or not? admin logs seem to tell me that when testing latejoins. not to mention all the checks for their jobs, prefs, etc

**Comment by ValkyrieSkies** [comment]
what

literally what is the point

**Pull request closed without merging**
