### PR TITLE
Halved chance for catbeasts to carry deadly diseases (from 10% to 5%)

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* tweak: Loose Catbeasts are now half as likely to carry a deadly disease (from 10% to 5%). Depending on feedback the chance may be fully removed later.

### CODE REVIEW

**Comment by tuypo1** [comment]
There should be more incentive to hunt them, make them almost always diseased but make them take a long time to become contagious.

**Comment by DeityLink** [comment]
The entire point was to have the crew equip with sterile gear BEFORE hunting the catbeast but I guess I expected too much of our blood crazed validhunters.

**Comment by DeityLink** [comment]
Oh and also the real round ending diseases are fucking stage 4. It takes 20 MINUTES to reach that stage. It can't hurt you to slap your ass with an health analyser after killing one.

**Comment by Kharkov72** [comment]
>It's validhunting to want to kill a catbeast

😕

**Comment by DeityLink** [comment]
It's you hunting something that's valid, even if you're expected to. What's your point?

**Comment by Kharkov72** [comment]
the point is that I'm not sure why you expected everyone to gear up for cat aids, ESPECIALLY because you need to kill catbeasts asap because otherwise they jack up the threat and you get ops on your dick

**Comment by DeityLink** [comment]
Yeah that's a decent point and that's why I made this PR. And like I said if you can kill the catbeast chances are that medbay will have a cure ready in the next few minutes. If people bludgeon catbeasts to death and never bother to check whether they got infected or take the vaccine they shouldn't be surprised when it reaches stage 4 half an hour later.

**Comment by bathosbathtime** [comment]
A T O M I C

**Comment by DeityLink** [comment]
removed the disease dish changes

**Comment by ShiftyRail** [comment]
They should be fully removed and replaced with a chance to have "inconvenience" diseases only (Hindrance class)

**Comment by DeityLink** [comment]
I updated the command announcement to remind people that catbeasts are disease ridden and that they should get a check up afterward.

**Comment by DeityLink** [comment]
To those who want the deadly symptoms gone as I said in the OP there will be another PR later anyway. I just don't want to do it all at once because I think it's fine if they have a small chance to happen. Can you just take it?

Or are people downvoting this PR because they want even more dangerous diseases? I don't think so.

**Comment by ShiftyRail** [comment]
Let's see what it will do

**Comment by tuypo1** [comment]
Neither, I want the diseases the catbeasts carry to be incredibly deadly but they should only become contagious if allowed to live for too long.

**Comment by DeityLink** [comment]
In which case they might as well have no disease since they tend to die in minutes.

A better alternative would be for them to mutate new more dangerous diseases when they survive longer.

**Pull request merged**
