### PR TITLE
Just in case

### PR DESCRIPTION
**Pull request by ihadtoregisterforthis**
Revert "64x64 Sprites"

You never know :>)

### CODE REVIEW

**Comment by Megamaw** [comment]
push it without discussing it, PJB does it all the time(read: just now)!

**Comment by Exxion** [comment]
It was up for 5 days
And the issue about the matter was up for three before that

**Comment by clusterfack** [comment]
Don't do this

**Comment by ihadtoregisterforthis** [comment]
Do what?

**Comment by clusterfack** [comment]
In general: make pre-emptive revert PRs
For you: make revert PRs ever

**Pull request closed without merging**
