### PR TITLE
Adds minerals to the price of the pico manipulator

### PR DESCRIPTION
**Pull request by jakmak3**
Does what the title says. Adds a tiny amount of silver and uranium (similar amounts as other stock parts) to the pico manipulator in the protolathe. The super matter bin is still mineral free so r&d can be completed with ease as normal. This change is designed to work with my other PRs that will be pushed shortly

### CODE REVIEW

**Comment by Megamaw** [comment]
well i mean we're not getting the whole story here are we

what other prs?

**Comment by jakmak3** [comment]
one sec megamaw im trying to get the last PR up for some reason git is being fucky

**Comment by ghost** [comment]
no

**Comment by Megamaw** [comment]
so wait machines other than the exosuit fab use these parts

this is just an even heavier yet deterrent for replacing parts of other departments

no thanks

**Comment by jakmak3** [comment]
yeah this was intended to go along with a rebalance to what machine parts do but for some reason git hath fucked up

**Comment by Probe1** [comment]
Even removing goofball and morena who aren't currently players here, this is entirely, overwhelmingly, positively negative in community response.

**Pull request closed without merging**
