### PR TITLE
Remapped Taxi medbay, plus a few other fixes

### LINKED ISSUE #7280: Taxistation - Cthulhu Brain starts with dead mobs
The creature mobs(Huge blobs with huge mouths on them) are hostile to normal asteroid monsters, so they die off quickly during roundstart.

### LINKED ISSUE #7413: Taxi Medbay
Minimum 24 tiles between cloner and cryo behind two airlocks, which is too much.

MDs do not get access to a crew monitor computer.

You have to go through a wide loop and past two airlocks to get from med primary to chemistry.

The lobby is nonexistent; patients have to wait directly in front of the med airlocks or just dawdle about in the middle of medsilicon until they're received.

Telescience is on another station, so it's never fucking used.

### LINKED ISSUE #8035: [Taxi] Scrubber connected to the distro
Are you even trying ?!?!?
http://puu.sh/mTmlN/21a31f9e8e.png

### LINKED ISSUE #8129: Inconsistent paramedic access to morgue
While paramedics can't access the morgue by the main door, there's still a valid non-hacking way to access it in Boxstation.

In Boxstation, they can access via the door between paramedic's room and morgue. However, in Taxi there's only one door to morgue (the main one), and so there's no access to paramedics.

I can't remember if there's such door in Defficiency.

### LINKED ISSUE #8134: Taxi salvage shuttle can't dock onto the derelict
Docking port highlight

As the salvage shuttle does not have destroy_everything = 1, it can't dock at this docking port.

Seems whoever converted the taxis into the side-get-on forgot to take the salvage shuttle docking into account

On an unrelated note, this show-ship-highlight function is pretty neat

### PR DESCRIPTION
**Pull request by xpcybic**
There's a lot to this. I did some testing on it already (with help from bauds), but there may be problems with it that I missed. Any and all feedback on the layout is also appreciated.
- Redesigned almost all of medbay with the goal of reducing cramp and improving workflow between departments. Adds a lobby, moves sleepers/cryo to center, moves paramedic to left, moves patient rooms to upper-left, adds a medical storage room, enlarges genetics, virology, and CMO.
- Changed morgue airlock to require either morgue or paramedic access.
- Expanded the small room in medsci maint into an unfinished office.
- Fixed vent and scrubber piping in CE office.
- Added intercom to AI upload.
- Added missing NT Default and Robocop lawsets to AI upload.
- Refloored bridges to look more distinct.
- Added bucket to robotics.
- Added autolathe to R&D.
- Fixed mobs in asteroid "brain" being hostile toward each other.
- Fixed an incorrect airlock on the emergency shuttle.
- Fixed a severe lack of supplies on the syndicate shuttle.
- Fixed a docking port being too close to engi/cargo, preventing the syndicate shuttle from docking at it.
- Adjusted derelict arrivals so that the salvage shuttle can dock at it.

Fixes #7413, fixes #8035, fixes #8129, fixes #7280, fixes #8134

screenshot 2016-02-10 18 56 16
screenshot 2016-02-10 19 35 50

### CODE REVIEW

**Comment by Zth--** [comment]
:+1: medbay looks much better

**Comment by ihadtoregisterforthis** [comment]
Larger medbay is great but did it need to be _that_ big?

˃three tiles wide maint
Oh boy

**Comment by IratePirate** [comment]
Expand maint.

**Comment by ghost** [comment]
Nice, bioprinters being in surgery observation seems like it might be a pain, but medical overall's looking beautiful

**Comment by 9600bauds** [comment]
Nobody ever uses the bioprinters OR surgery observation anyways

**Comment by ghost** [comment]
Virology air distro and waste distro shouldn't be connected to rest of the station.

**Comment by CptWad** [comment]
What @TermedClepe said viro needs to not be connected to main station because 

1. Airborne viruses
2. Xenos
3. Slimes

**Comment by PJB3005** [comment]
Pretty sure airborne viruses don't travel like that @CptWad

**Comment by 9600bauds** [comment]
This game would be a slideshow if that's how airborne viruses worked

**Comment by clusterfack** [comment]
I think I could them work like that pretty easy desu

**Comment by Konater** [comment]
Minor but the table blocks the cloning DNA scanner

**Comment by ihadtoregisterforthis** [comment]
Needs cameras

**Comment by CptWad** [comment]
Muh immulsions. They are supposed to have cut off air supplies because thats how its done anywhere they store virus shit, even more so for virus research. CDC dont fuck around and neither should we. Even if it don't or won't travel through vents

**Comment by xpcybic** [comment]
Will separate viro's atmos, right now it's just a copypaste from the original with some stretching and this hadn't even occurred to me
@Konater I can move that table, but I didn't think it'd prevent you from putting bodies into the scanner?
@ihadtoregisterforthis (re: cameras) shit of course I'd forget one of the obvious things. (re: size) idk it's still fairly packed, I could shrink it vertically but not by much. I'll widen the vacant office to deal with the huge part of maint.

**Comment by d3athrow** [comment]
Maint almost never needs to be more than 2 tiles wide
I know you didn't do most of these pipes but if you're in the area please try to fix them up.
pipes under mother fucking walls
another pipes under mother fucking wall

**Comment by xpcybic** [comment]
screenshot 2016-02-13 14 27 07
??
(actually on second thought having that airlock leading INTO viro is a bad idea i took that out)

**Pull request merged**
