### PR TITLE
[Balance] Made the teleporter HUB on the Syndicate Mothership always accurate

### PR DESCRIPTION
**Pull request by DeityLink**
Basically it is now guaranteed to send you to destination, without a small chance of sending you somewhere in space. I think the Nuke Ops deserve at least that for their 10 TC investment.

technically map changes but it was all done with a text editor to prevent any possible conflict with other PRs.

### CODE REVIEW

**Comment by clusterfack** [comment]
Soon everyone will be mapping with the text editor only, we're going to full dorf fortress hardcores mode

**Comment by DeityLink** [comment]
I'm pretty certain that your prediction will end up true soon enough.

**Comment by Probe1** [comment]
this will effect the accuracy of bombings right..?

**Comment by clusterfack** [comment]
Also I would have preferred you made an accurate typepath instead of varediting on the map. And hell placed an accurate one on centcomm too.

**Comment by FudgePucker** [comment]
I said in the thread that merging using the text editor would possibly be a better solution.
Its just changing some aaaaaaaaaaaaaa's to aaaaabaaaaaaaa's.

**Comment by DeityLink** [comment]
@Probe1 it just prevents stuff from being sent into deep space

@clusterfack 
>Also I would have preferred you made an 'accurate' typepath 
Dude you know that this "accurate" var has existed for ages? And cannot be currently changed by non-admins ways? Making another typepath just so we can set a var to 1 seems like overkill to me.

@FudgePucker 
You don't have to edit rows of "a"s if all you're doing is some varediting.

**Comment by DeityLink** [comment]
@clusterfack 
>Consider even adding a machine/device that can be attached to make a teleporter perfectly accurate as well

I've thought about giving teleporters a way to become accurate for a long time, but that's slightly beyond this PR's scope.

**Comment by clusterfack** [comment]
Making a typepath instead of random varedits on the map is always preferable deity don't be silly. 

Varedits on the map should be reserved for thing like APCs, varediting map objects leads to stupid things like the supermatter chamber door issue that I'm not sure has even been fixed yet.

**Comment by DeityLink** [comment]
First time I ever hear that.

**Comment by clusterfack** [comment]
It's not something anyone tried to hide, I've said it numerous times. Varediting map objects often leads to legacy issues in maps.

**Comment by DeityLink** [comment]
Well you've got a point but I'm really not in the mood (nor have the energy) to code something that makes teleporter hubs accurate, can we accept this PR as a workaround until we get something more substantial?

**Comment by clusterfack** [comment]
To be fair its like 2 extra lines of code, /obj/machinery/teleport/hub/accurate, accurate = 1

**Comment by Iamgoofball** [comment]
Why you should do typepath for shit like this

Let's say we change the accurate var to doubedonkbouncyjellojumpinghumpingbigbootyberthaextreme

If we have this map edit in after the change, the map is gonna get corrupted because the var accurate doesn't exist, but the var doubedonkbouncyjellojumpinghumpingbigbootyberthaextreme will, and we'll need to manually edit the map, find the broken nonexistent var, remove it, and add a new var calleddoubedonkbouncyjellojumpinghumpingbigbootyberthaextreme to the teleporter.

If we do a typepath, changing the accurate var todoubedonkbouncyjellojumpinghumpingbigbootyberthaextreme won't break horribly, and instead will work properly.

**Comment by DeityLink** [comment]
Ah right, that too. I didn't add a new type path to limit to the maximum the possibilities of conflicts.

**Comment by clusterfack** [comment]
Or if we add a research object that you just stick in a teleporter to make it accurate, you could just add the object to the code of the accurate teleporter

**Comment by Iamgoofball** [comment]
Maybe in the future, for now a simple accurate type path works

**Comment by DeityLink** [comment]
Yes but if I'm really going to add such an item I'd like to make it properly, with an R&D tech level and a nice sprite, I'm not ready to rush one right now.

**Comment by clusterfack** [comment]
I'm not saying to do it right now just that you would be reducing the amount of work required at that point by this change

**Comment by DeityLink** [comment]
It's a work that I'll do myself eventually. No one else bothered with that until now after all.

**Comment by ComicIronic** [comment]
>Making a typepath instead of random varedits on the map is always preferable deity don't be silly. 

Oh god no.
Map variants should never appear in the code.

**Comment by dylanstrategie** [comment]
What Comic said

I already had lots of FUN fixing, re-fixing, triple fixing and then deleting map variants because of all the problems they cause, for instant with "broken tiles" and "broken grilles"

Please use code entities for new objects

**Comment by IratePirate** [comment]
Can you just do this for the regular teleporters? There is nothing funny or interesting about being randomly killed by a teleporter malfunction.

**Comment by DeityLink** [comment]
@IratePirate as I said I'll give a way for scientists to upgrade teleporters later on. I think it should still have that small risk by default.

**Comment by d3athrow** [comment]
nerf telebombs!

**Comment by Probe1** [comment]
telebombs make me die a little inside watching the station get unstoppably and irrevocably broken 

but I have no complaints with this PR

**Pull request merged**
