### PR TITLE
Fixes Avocado Duping

### LINKED ISSUE #15151: You can become jesus with those simple steps.
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
1.Cut Avocado in half
2.Cut the Half Avocado again
3.keep cutting your half avocados for infinite avocados

also on a side note, the seed you get from removing the avocado seed will not be a modified seed, so if you have a bajillion potency avocadoes with polacyd, zombiepowder and tonio you'll only get a normie seed.

### PR DESCRIPTION
**Pull request by Shadowmech88**
Fixes #15151

### CODE REVIEW

**Comment by Intigracy** [comment]
If you want to know how to save the plant's information to the dropped seed, look at how the seed extractor does it.

**Comment by Shadowmech88** [comment]
The seed extractor seems to do it based solely on the `plantname` var of the grown item, but I'm not sure how that works, it looks to me like all grown items of the same type have the same `plantname`.

**Comment by Exxion** [comment]
Question, unrelated to that:
It looks like slicing the avocado doesn't carry the reagents over. At all. Is that correct?

**Comment by Shadowmech88** [comment]
That's correct, I should fix that.

**Pull request merged**
