### PR TITLE
Adds luck to card drawing

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
adds a luck factor to normal playing card decks for times when texas holdem would be played with them. currently makes it easier to pairs, three of a kinds, four of a kinds, straights, flushes and full houses. uno and wizard cards do not factor into calculations.
also adds this for the wizard card decks, as a chance to draw legendary ones.
une card decks make it more likely to draw wild draw 4s, wilds, draw 2s, reverses and skips in that order.

## Why it's good
makes luck factor in another thing in the game that involves gambling.

## Changelog
:cl:
 * rscadd: Lucky players are now somewhat better at poker with cards.
 * rscadd: Lucky players can draw legendary wizard cards easier.
 * rscadd: Lucky players can now draw more valuable une cards, such as wild draw 4s, wilds, draw 2s, reverses and skips.

### CODE REVIEW

**Comment by jwhitak** [comment]
Gut reaction screams oh no not my balanced gameplay of games... in a game. I didn't like luck that much to begin with, and now it's creeping into things I really don't want to see luck in.

But this is a considerable refactor of card code too, not just luck-changes-cards-PR...

**Comment by Eneocho** [comment]
While good for poker it would absolutely ruin any other card game you could play, since you would get the "lucky" aces when you wanted a 6, for example.

**Comment by SECBATON-GRIFFON** [comment]
> While good for poker it would absolutely ruin any other card game you could play, since you would get the "lucky" aces when you wanted a 6, for example.

i was gonna try do a different algorithm for uno and also make this support blackjack, but yeah that seems to be the main problem with this

**Comment by Dacendeth** [comment]
This is just going to make me not want to play card games with botanist or anyone else cheating with lucky charms.
I would call this a pvp advantage which I think luck shouldnt be for.

**Comment by SECBATON-GRIFFON** [comment]
> This is just going to make me not want to play card games with botanist or anyone else cheating with lucky charms. I would call this a pvp advantage which I think luck shouldnt be for.

only in a fluff arrpee game sense really, not something like combat

**Comment by Hinaichigo** [comment]
I like the idea of a luck roided poker game with people cramming their pockets with clovers. Everyone getting flushes and great hands only to be outdone by the next person and such. There are some issues like the blackjack thing but still would be funny.

Maybe saying the name of the game or certain keywords would 'set' the game type in the deck. Like saying 'hit me' and such.

**Comment by Hinaichigo** [comment]
Kind of funny also to imagine a fancy casino party with clover based foods as the catering.

**Comment by west3436** [comment]
stealth blackjack nerf

**Comment by SECBATON-GRIFFON** [comment]
yeah the une and wizard ones seem fine to me but i don't think the playing cards can be done right. will close but may reuse code for something in the future

**Pull request closed without merging**
