### PR TITLE
New Engine Sprites

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds new shuttle engine sprites, taken from Eris Station and heavily altered.

Current:
propulsionold

New:
propulsionnew4

:cl:
 * imageadd: Shuttle engines now have a new sprite.

### CODE REVIEW

**Comment by PJB3005** [comment]
Looks weird.

**Comment by ultraplen** [comment]
They look better for sure, but a bit too detailed.

**Comment by Ephx1** [comment]
They look like they belong in a completely different game.

**Comment by yclatious** [comment]
Agreed with everyone else, it looks far too detailed to be in our server.

Good intention, but its just too weird to see, it just doesn't fit.

**Comment by Aurx** [comment]
The color depth difference makes them stand out way too much.

**Comment by Shadowmech88** [comment]
I tried tweaking the colors a bit to be closer to our current sprites. How does this look?
propulsionnew2

**Comment by Ephx1** [comment]
That's better, but I'm not sure about the thrusters themselves, they still seem too complex.

**Comment by yclatious** [comment]
Just make them look worse, they still look too good compared to everything else we have.

**Comment by Shadowmech88** [comment]
I'm not sure how to make them look worse.

**Comment by yclatious** [comment]
Like I said in the thread, just try to make it worse. Can't screw up making something worse, don't think that is possible, at most you fuck it up too much.

**Comment by PJB3005** [comment]
Honestly those colour tweaked one look amazing 👍

**Comment by Shadowmech88** [comment]
I tried to remove some detail, how do these look?
propulsionnew3

**Comment by yclatious** [comment]
Much better already mate, maybe make the H area slightly more bland and itd be great.

**Comment by Shadowmech88** [comment]
Like this?
propulsionnew4

**Comment by yclatious** [comment]
Exactly like that, now it fits a lot more than the original shaded one. I would have simplified a bit more, but hey, still great stuff.

**Comment by N3X15** [comment]
> Taken from Eris Station

Do we have permission?

**Comment by Shadowmech88** [comment]
I asked about license compatibility in the Discord last night and you said "the only people that care about license are goon and /tg/" so I didn't think it was necessary.

**Comment by SangriaMonkey** [comment]
:ok_hand:

**Comment by PJB3005** [comment]
The it's CC-BY-SA I believe, should be fine.

**Comment by gbasood** [comment]
as long as the guy who made the sprites doesn't start a DMCA "as a joke"
i doubt he will

**Comment by StarSmasher44** [comment]
I like them, too detailed doesn't matter since you'll always look at new sprites the first few times. After that you don't even see it :P

**Comment by yclatious** [comment]
Its not about it being too good themselves, its everything around them being so simple that it clashes a lot and is very noticeable, for the worse, because then we have a much higher detail in objects for one thing and evrything around them is basic and unshaded, making it look like one 3d model got all the attention and then the rest were done by a unpaid intern learning blender or something.

**Comment by StarSmasher44** [comment]
Then we also upgrade the shuttle sprites too and we'll have awesome shuttles and ships. People will possibly pick up from there.

**Comment by Shadowmech88** [comment]
I'll keep my eye out for nice shuttle wall sprites. Eris didn't have any that were usable since their shuttles seem to be built from static pieces rather than using a dynamic wall smoothing system.

**Comment by eplgr** [comment]
They look pretty good.
The old ones were shit and didn't look like engines at all. I bet half of the server didn't realize they were engines until the recent update that added fire to them.

**Comment by Exxion** [comment]
They're called "propulsion"
I'm pretty sure everyone knew what they were

**Comment by Iamgoofball** [comment]
>good sprites dont belong

i'm borrowing these sprites if you guys want to continue living in 1999

**Comment by Iamgoofball** [comment]
ps, good sprites :+1:

**Comment by Iamgoofball** [comment]
also the sprites are compatible license wise, eris is a bay base afaik

**Comment by Zth--** [comment]
Just improve those stupid blue tiles, they feel like 1995

**Comment by Probe1** [comment]
You know you people fucked up when @Iamgoofball is making more sense than you

 >it looks too good make it look worse

holy hell.

**Comment by StarSmasher44** [comment]
I wish we could get out of the awful 2-minute sprites and into the quality works like these. People get used to them and will like them, all we need now is more spriters and more sprites to get it all rolling

**Comment by PJB3005** [comment]
Yeah fuck the Shit sprites.

Though I agree the original version in this PR looked strange, the new one is absolutely amazing.

**Comment by Iamgoofball** [comment]
I'll PR the good versions

**Pull request merged**
