### PR TITLE
Wheelstation engines revamp

### PR DESCRIPTION
**Pull request by brndd**
I wanted to map in a different kind of supermatter engine because our supermatter engines are all boring, so I did it on Wheelstation.

It's a Baystation-style engine that generates power from the heat given off by the supermatter, rather than the radiation. It has an active cooling loop for the chamber, and a simple passive cold loop for the TEGs to get a thermal gradient. It's stable and generates more than enough power to run the station (the reference setup described below will generate about 400 kW; bigger numbers are possible if you know what you're doing).

Reasons it's better than the usual kind of SME we have:

- It's more complicated.
- You can change the engine's properties by running it with different coolant gases in the chamber/hot loop; every gas behaves differently, even though our systems in this regard aren't nearly as nuanced as Baycode's.
- You don't get big numbers for free (unless you take the easy way out and bolt down some radiation collectors, which will generate an order of magnitude more power than the TEGs while being braindead simple; you should feel bad if you do this)
- It's different than on the other maps.

There's also no more antimatter room because the AME is stupid and not every map needs every engine mapped in; SME, singulo, solars and naturally PACMANs should be more than enough.

## How to set it up

<details>
<summary>
Spoilers ahead, if you read these you're a fake engineer
</summary>

spoilers

1. Take a can of carbon dioxide and a can of plasma and wrench them into the hot loop and the cold loop respectively, marked 1. on the picture above. The CO2 goes in the top loop and the plasma goes in the bottom loop. Turn on and max out the pumps next to them. You can use a gas other than CO2 in the hot loop if you're adventurous; different gases generate different amounts of power and may or may not be stable with all 5 emitters.

2. Once both canisters are empty, unwrench them and wrench down a second set of canisters. Put at least two canisters worth of gas into both loops. The amount of gas in the loops affects stability and power production, and more gas in the hot loop gives the engine more "inertia". Two cans is stable and enough to power the station, but feel free to experiment.

3. Set the gas filters (marked 2. on the picture above) to filter whatever gas you put in the hot loop (Carbon Dioxide if you followed the instructions). Max their pressure and turn them on.

4. Turn on the 4 volume pumps next to the cold loop circulators, marked 3. on the picture above. They should already be at 200 l/s.

5. Go to the Atmospherics Automations Console in the control room and set:
    - The hot loop injector (id tag: `sme_in`) to on and 200 l/s.
    - The hot loop vent (id tag: `sme_out`) to on, pressure checks disabled, mode siphoning.
    - Don't forget to apply the settings by clicking on RUN ONCE.

6. Turn on all the emitters. Monitor the temperature of the chamber and the stability of the shard at the consoles in the control room.

7. Eventually the yellow canister that waste gases (plasma and oxygen primarily) are being filtered into will fill up. You'll want to replace it with an empty canister when this happens, or replace the connector port with a vent into space if you don't want to collect the gas.

</details>

<hr>

Still no changelog because the map is not in rotation.

### CODE REVIEW

**Comment by PJB3005** [comment]
Especially with this layout, if you swapped the SM and singulo, and then put all the singulo collectors on catwalks in space, the entire engineering department would look so much better.

**Comment by DrSnips** [comment]
Engines that shoot themselves in the foot: the station

**Comment by brndd** [comment]
Active cold-making? Choose of smell-air? Make lightning of hot-hot and not green-glow?

Grug no like this new lightning-maker... What happen to cold-cold purple-air in air-box to make big lightning? That Grug understand. That Grug like.

**Comment by Kurfursten** [comment]
Grug also like having chair in monitoring office for sit and watch in comfort

Where Grug local power monitoring computer for check total throughput of engines without leaving monitoring room? Why no window on lower side of monitoring room so Grug able to observe all engine performance bars simultaneously? Grug also want firelock on window separating engine room from observation room like on Grug favorite map Defficiency.

**Comment by brndd** [comment]
Good ideas from Mr. Holiday here. Except the emergency shutters in the windows, screw that noise.

**Comment by Blithering** [comment]
Now we need an engine that uses the singularity's gravitational pull to move a ball on a treadmill for power.

**Comment by tuypo1** [comment]
Yeah we need less firelocks not more

**Comment by bthomas2** [comment]
why not just make this a R-UST?

**Comment by brndd** [comment]
1) The R-UST is too powerful for a roundstart engine

2) I don't like the R-UST

**Comment by bthomas2** [comment]
I hope you let this thing run for an hour as a test

**Pull request merged**
