### PR TITLE
Box Trader Outpost infinite SMES replaced with standard SMES, given an eel engine.

### PR DESCRIPTION
**Pull request by kernikov**
image

Magic SMES bad.

I'll make a comment to emoji to keep/scratch the eel addition, if anyone cares.

:cl:
 * rscadd: Traders given a small EEL engine for power.
 * tweak: Trader SMES no longer has infinite charge.

### CODE REVIEW

**Comment by kernikov** [comment]
Emoji this comment if you care about the addition of EELs.

**Comment by Servalfang** [comment]
let the poor souls have the power they need. unnecessary change.

**Comment by kernikov** [comment]
> let the poor souls have the power they need. unnecessary change.

The first plan was to have a plasma miner and floor igniter immediately fry them when they spawn, be glad this was the alternative.
No one gets a magic SMES.

**Comment by Eneocho** [comment]
Finally, the death of the metaclub...

**Comment by gurfan** [comment]
Do they have the stock parts they need to make the fishtank?

**Comment by kernikov** [comment]
They have the required stock parts of "glass".

**Comment by agentofzog2** [comment]
Traders are usually afking on the shuttle waiting for someone to come by or looting the armory I mean space vaults, this doesn't leave a lot of time to feed the fishies.

**Comment by kernikov** [comment]
> Traders are usually afking on the shuttle waiting for someone to come by or looting the armory I mean space vaults, this doesn't leave a lot of time to feed the fishies.

Fish only consume food when producing eggs.
Each eel is 50 kW.
The max draw of the entire outpost is 13kW.
The small fish tank can hold 5 fish.

**Comment by Kurfursten** [comment]
I don't think he's objecting to the ability to make enough power to stay charged (trivial) but rather the idea that traders would need to babysit their power in addition to other tasks. I can't remember if filth can eventually kill your eels if you leave them alone a long time. Traders also already have a lot of roundstart setup shit they want to do rather than make engines. On the other hand, I am doubtful that it will be a problem. The human outpost has nothing but PACMAN generators and they never get used because the human outpost (which draws 4x as much power) never runs dry its SMES.

My only request is that you make the trader outpost smes start with the same amount of charge that the research and mining outposts start with. I think if you do that, no one will ever even notice the magic being removed.

**Comment by kernikov** [comment]
@Kurfursten done

**Pull request merged**
