### PR TITLE
Can now order Grass Tiles, Carpet Tiles and Bloodbags at Cargo

### PR DESCRIPTION
**Pull request by Arthurdentist**
Addresses #3090 although you still can't get the lamps.

### CODE REVIEW

**Comment by Probe1** [comment]
you could already get blood bags from plastic?

whatev

**Comment by ComicIronic** [comment]
Can't make full Blood Bags from plastic sheets.

**Comment by Probe1** [comment]
that's why IVs have a toggle button!  it'll be weird not bleeding myself for bags of O-, and blood is like the last refuge of difficulty in medbay, but hell merge it.  I'll enjoy having piles of bloodbags more than the memory of what a PITA it was to get the blood bank going in medbay.

**Comment by ComicIronic** [comment]
I think the Blood Bags is intended as an emergency crate. Stuck in cargo with low blood and xeno hoards roaming outside? Order a crate.

**Comment by Arthurdentist** [comment]
this benefits medbay but it also benefits the chaplain or the clown or anyone else who wants to do gimmicks with blood. I resisted the temptation to give you loads of O- Bloodbags as well, you get one bloodbag for each blood type per crate, so unless you order a lot of crates you wont be able to just slap everyone with an O- Bag and call it a day.

**Comment by Probe1** [comment]
I'm satisfied with this.

However, I do want to discuss something outside the scope of this PR that is essentially why O- is powerful and the first choice by many players.

**Comment by Arthurdentist** [comment]
O- Blood is the universal donor. Anybody can accept O- blood in a blood transfusion whereas AB is the universal receiver. Only ABs can accept AB blood but ABs can accept any other blood type. Its based in reality.

**Comment by Probe1** [comment]
I was gonna stealth edit the issue in but there you go [3346]

**Pull request merged**
