### PR TITLE
Ramen heating tweaks

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
Currently, self-heating ramen uses calcium oxide + water -> calcium hydroxide reaction to heat it up enough to cook the ramen (100 C).
This is one of three reactions in the game that affect the temperature of the reagents mixture, the other two being the decomposition of space lube into sludge at extreme temperatures, and water freezing. Those two remain unchanged here.
However this introduces a slightly different mechanism for heat-releasing (or heat-absorbing) reactions and changes calcium oxide to use it. Instead of increasing the temperature of the mixture by a fixed number of degrees (regardless of its specific heat capacity), the reaction will instead release a given amount of heat per volume of the products. Here I set to where filling the ramen in a sink with enough water to boil all the ramen will bring it to ~106 degrees which feels reasonable and cooks it nicely. This also lets us remove the "react discretely" flag from the calcium oxide reaction, which I think was probably added to try to approximate this behavior, but is ultimately somewhat unsuited to this situation.

Also this reduces the ramen cooking temperature from 100 C to 98 C (apparently that's the ideal temperature for cooking ramen). Hopefully that also anticipates any future issues that may arise with regard to water boiling.

## Why it's good
More intuitive behavior and avoid some aberrant edge cases with how it currently works.

## Changelog
:cl:
 * rscadd: Calcium oxide dissolving releases a definite quantity of energy rather than directly shifting temperature by a fixed amount.

### CODE REVIEW

**Comment by SonixApache** [comment]
please for the love of god just destroy calcium oxide and make the cup heat the water automagically instead

**Comment by Eneocho** [comment]
> please for the love of god just destroy calcium oxide and make the cup heat the water automagically instead

Make more stuff use thermal reactions. Cool(TM) oxide that cools down the cup when reacted with water, instead of heating up.

**Comment by SonixApache** [comment]
The issue with the oxide is that it broke the perfect ratio for adding water from a sink long ago when it got added in a hamfisted response to the fact that the ramen didn't get any hotter when you add the water. So now every time you fill the cup from a sink you get a delicious mix of ramen, calcium oxide and water instead of just 30u hot ramen. It **SUCKS**.

**Comment by pedr69** [comment]
ever wonder why the hydrated lime gets mixed into the finished ramen for spacemen to drink up?
it's basic so it would taste disgusting and fucking dissolve your mouth and innards

**Comment by Hinaichigo** [comment]
Maybe some kind of exothermic thing that would evaporate and bubble out of the ramen as a gas after it gets wet?

**Comment by SonixApache** [comment]
make the cup generate plasma gas when you add water for all i care, just kill the oxide

**Pull request closed without merging**
