### PR TITLE
Fixes SSU locks being able to be opened without access

### PR DESCRIPTION
**Pull request by ghost**
Emagging these units dumps all their contents and leaves them open and broken.
Can be repaired with a solder.
Units as they stand, generally speaking, start unlocked, so this has no effect on access until someone with valid ID locks them.

Remaking this PR due to negative reception being a communication error, thanks @BomberBro for the new PR title
:cl:
 * rscadd: Department suit storage units now require their access to lock/unlock suit storage units, must require a valid ID or emag to bypass

### CODE REVIEW

**Comment by help-maint** [comment]
What do you mean "fixed"
It's not like there were access requirements that didn't work due to a bug, you're adding access requirements where there previously were none 🤔

**Comment by DrSnips** [comment]
In some fairness it does say locked which implies access of some sort should be needed.

**Comment by ShiftyRail** [comment]
~~This is the exact same PR as before and the exact same argument apply.~~

Nevermind

**Comment by BomberBro** [comment]
SSUlock
I'm pretty sure this is a bug, because you can freely lock SSUs and the lock correctly prevents you from opening them if you press "Open Unit", but there's no access restriction for the actual "Unlock Unit". If this isn't a bug I'd like to hear what the point of the lock is, because it doesn't secure anything.

**Comment by help-maint** [comment]
Really proves that, in an emojicracy, what you change is less important than what you call it

**Comment by Eneocho** [comment]
The SSUs can be hacked to unlock the gamma ray-level decontamination which burns to a crisp. Can you add a way to hack the access on the SSUs also?

**Pull request merged**
