### PR TITLE
Player Shuttle Construction

### PR DESCRIPTION
**Pull request by MadmanMartian**
Ever wanted to just strap an engine to the back of a bath tub and jettison yourself into space? Now you can with the shuttle evaluation permit!

 - Checks if your shuttle can actually move under the weight of its engines
 - Checks if you're actually facing towards space so it can try and make a shuttle docking port there

And that's about it.

Also fixes the oversight where turf/set_area wouldn't add the turf to the new areas area turfs.

## Todo
 - [x] Add it so you can get the station-side docking ports as shuttle disks
 - [x] Ensure you can get the shuttle computer boards somewhere on station
 - [x] Engine balancing?
 - [x] testing

Book sprite courtesy of Frosty the wizard in the coder discord.

:cl:
 * rscadd: NT have sublet the ship construction process to the civilian sector. Pick up your ship construction license at cargo today.

### CODE REVIEW

**Comment by spoonylove** [comment]
How big can you make them? Will this fix that big white ship vault so it actually moves? Will derelict mommis be able to ditch their native land with this?

**Comment by MadmanMartian** [comment]
1. The upper limit is how many engines you can afford.
2. No.
3. The only way you can get the ship permit is through cargo, so no unless you give the MoMMIs the card.

**Comment by Reviire** [comment]
Lets revamp derelict mommis, so they're on a small derelict ship. It would be perfect.

**Comment by MadmanMartian** [comment]
turns out you can build shuttle consoles

**Comment by SonixApache** [comment]
whence

**Comment by miniusAreas** [comment]
yall are doing fucking gods work, good job.

**Comment by MadmanMartian** [comment]
What more needs doing for this?

I removed the WIP label 16 days ago

**Comment by Exxion** [comment]
Changelog
Also what were you talking about with being able to build shuttle consoles?

**Comment by SonixApache** [comment]
@MadmanMartian make the 🆑

**Comment by MadmanMartian** [comment]
CL maked

**Comment by SonixApache** [comment]
image

**Pull request merged**
