### PR TITLE
Removes bus

### LINKED ISSUE #10772: remove bus
it keeps breaking

it needs constant admin supervision

please kill it

### PR DESCRIPTION
**Pull request by PJB3005**
It's just so awful dear god.

No this isn't a meme PR I'm actually dead serious it's so bad.

Resolves #10772

I'm convinced @Kurfursten actually spent fuckall effort on it. The amount of disconnected wires & pipes and issues is so insane. Any room which isn't copy pasted from Taxi is ugly.

If @Kurfursten actually believes it's in a state which can be considered decent he's dead wrong.

Normally I'd be on the side of the new map when it gets shat on like this, but Bus doesn't deserve my support.

### CODE REVIEW

**Comment by Imagebard** [comment]
Okay fuck I give up. Enough with the "Boxbabbies" shit.

**Comment by PJB3005** [comment]
I think basically everyone can agree it's a bad map in its current state, not just people who are "box babies".



I did a vote about which is the worst map:

Deff had 1 vote.
Meta 0 votes.
Bus had like 11 or something votes.
Box had 6.

**Comment by ghost** [comment]
eggplant

**Comment by ComicIronic** [comment]
Don't take it out of the code entirely, just pull it from rotation, because this way it will never be fixed.

**Comment by Exxion** [comment]
> Completely removing it from the code

Why
Seriously, just remove it from rotation like we have done every other time a map was "removed"

**Comment by PJB3005** [comment]
Because I can't. Only pomf can take it out of the rotation.

**Comment by TheFriggenSawbones** [comment]
pomf please remove it from rotation I'd appreciate it

**Comment by Exxion** [comment]
Well maybe ask Pomf to do that instead

Also I call bullshit on your claim that every room not copied from Taxi is ugly, because Bus's Service division is the fucking best
I have pretty much never been to any other part of the map so I can't comment on the rest, though

**Comment by TheFriggenSawbones** [comment]
primary tool storage is ugly as hell

**Comment by Intigracy** [comment]
The butthurt is real

**Comment by Kurfursten** [comment]
Supporting a map solo with a fulltime job is a difficult proposition. And make no mistake - every fix to Bus, except one by Probe - has been by me. Fixing issues as they appear takes effort - deleting everything takes "fuckall effort". I'm a little disappointed in your unnecessary venom.

I'm not going to fight it though. I had a PR underway to fix the reported issues, but it's really not worth contesting if there really is overwhelming hostility. In fact, issues that you would normally expect to be reported right away slip by for weeks at a time because no one votes for it. Go ahead and merge the PR.

**Comment by PJB3005** [comment]
Yes, and normally I would share your opinion on the matter, but the map just stinks of lack of effort.

There are bugs which can be missed and bugs which are so glaringly obvious the creator obviously didn't even bother to test (in the case of maps just glancing over is even enough) or didn't care.

Bus is absolutely filled with the latter.



I can count 6 issues on this screenshot by just glancing over it.



4 walls with incorrect sprites, cockpit has no chairs.

Then there's shit like this. I know this is nitpicking but how the hell does shit like this go through:















**I don't hate the map because of its issues. I hate it because it obviously doesn't have decent effort put into it.**

**Comment by TheFriggenSawbones** [comment]
when are we going to page pomf and ask him to remove it from rotation so it can get some love before it comes bacfk

**Comment by Intigracy** [comment]
This PR completely removes it from the repo as opposed to just removing it from the rotation.

Big :-1:

**Comment by Imagebard** [comment]
@PJB3005 Do you realize I upvoted your PR

**Comment by PJB3005** [comment]
@Imagebard yes.

**Comment by kol1th** [comment]
Also there's NO service channel.

**Comment by Exxion** [comment]
But I've used the Service channel on Bus

**Comment by kol1th** [comment]
When I checked, there was no telecomms hub for it.

**Comment by AutismSpider** [comment]
@Kurfursten  you did piss poor job with pipe  and cable lay out on all parts of bus

1ST fucking thing i got do is hook mommis nest air and scrubber pipe lane to station on top of fixing cable near by this not counting all the shit thats wrong.

**Comment by AlphaBuffalo** [comment]
I move for removing from rotation as well, maybe it can be fixed and used later, or maybe someone can repurpose it

**Comment by PJB3005** [comment]
Hasn't it just been removed from the rotation?

**Comment by PJB3005** [comment]
Alright Bus has been removed from rotation it appears victory achieved.

**Comment by ghost** [comment]
And now we're back to the usual 3

inb4 the complaints of 'these maps are stale' that we got before taxi

**Pull request closed without merging**
