### PR TITLE
Orderly Limit 2 -> 1

### PR DESCRIPTION
**Pull request by gurfan**
Gee medbay, how come you get two security officers.

### CODE REVIEW

**Comment by Optimism333** [comment]
> Gee medbay, how come you get two security officers.

Can you provide a bit more explanation on why there you think there should only be one? I haven't been able to play much highpop spess lately, but have situations come up in-game where orderlies have been chronic shitters? Or having two was more of a detriment to medbay than helpful?

I'm curious about what made you make this pr.

**Comment by gurfan** [comment]
Because why does medbay need TWO meme roles that don't revolve around healing people?

**Comment by mrflarg** [comment]
> Because why does medbay need TWO meme roles that don't revolve around healing people?

two geneticist roles two viro roles two chemist roles

**Comment by Optimism333** [comment]
> Because why does medbay need TWO meme roles that don't revolve around healing people?

I don't think that's a great argument. The role has access to all of medbay's various healing machinery and items (chemistry and surgery). So they're capable of helping with the wild ride when things get tough or setting up medbay if they're the only person on staff. And if they're not the only person on staff their role is to clean medbay, update records, and help the doctors work uninterrupted by filtering out the riff raff. It's hardly a meme role.

Unless you have a specific example of two Orderly slots being negative (like a few rounds with two Orderlies on staff who refused to heal or help people), it seems like a kneejerk pr because you don't like the role. Which is fine, but I don't think it makes for great ideas.

**Comment by Kurfursten** [comment]
We're seriously going to lower orderly from 2->1 before we lower paramedic from 4->3?
Have you ever seen 4 paramedics in medbay?

**Comment by gurfan** [comment]
I don't see 4 paramedics often, but I sure do see 2 orderlies a lot.

**Comment by tinysaturn** [comment]
sounds like somebody got their ass thrown out

**Comment by BomberBro** [comment]
They hated Jesus because he told them the truth.

**Comment by Optimism333** [comment]
> They hated Jesus because he told them the truth.

Maybe it would be beneficial to open a Github discussion to gather opinions on the role after a full month has passed since it was merged? I'd be happy to contribute to that sort of thing. I have actually had a specific negative experience with the role, but I just don't think the specific change in this pr would prevent it from occurring again.

**Comment by Kurfursten** [comment]
Not enough support

**Pull request closed without merging**
