### PR TITLE
Adds honking for the honk serum, recipe included

### PR DESCRIPTION
**Pull request by Goldsteel**
I thought this would be funny.

You used to need to get clown burgers to make the honk serum by grinding them, but now you can make it with banana juice, ear medicine and brain medicine. It metabolises at 0.05 per cycle with a 5% chance of making the honk occur, so eating a clown burger makes you do it 1-3 times before it wears off (5.5 units). Bananas grind for 1 banana juice so there's quite a bit of effort required to make enough of the chem.

I made a webm of putting the probability to 30 and metabolism to 0.01 and jesus christ it was the honking apocalypse.

THIS COULDNT POSSIBLY GO WRONG COULD IT HAHA NO NEVER

-->
:cl:
 * rscadd: Honk serum now makes you audibly honk. Honk serum can also be made from 1 part banana juice, 1 part inacusiate and 1 part alkysine.

### CODE REVIEW

**Comment by Irradiation** [comment]
Ear medicine is Inacusiate you regiment whore.

**Comment by Goldsteel** [comment]
Oops, let me correct myself.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
>Bananas grind for 1 banana juice

Did you try juicing them?

**Comment by Goldsteel** [comment]
It turns out juicing bananas makes 5 juice. This is probably fine.

**Comment by kilozombie** [comment]
You can buff banana potency and it should yield even more juice

Botany has been able to mass-produce stuff for ages

**Pull request merged**
