### PR TITLE
Fixes gas and temperature defines order of operations

### PR DESCRIPTION
**Pull request by Pathid**
Based on https://github.com/tgstation/tgstation/pull/37116

Completely untested on my end! Bomb mixing and the like will probably have to be adjusted.

:cl:
* bugfix: Fixed a very longstanding math flub involving gas values and temperatures. Gas and heat will be working subtly differently now, and hopefully better.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
>parenthesis around defines

that actually makes a lot of sense

**Comment by MadmanMartian** [comment]
surely you'd need parenthesis around any define that uses a math operator in that case, to maintain order of function?

I see some that are using multiply, go for those too

**Comment by MadmanMartian** [comment]
Good stuff

**Comment by SonixApache** [comment]
(this kills the bomber)

**Pull request merged**
