### PR TITLE
remove grinch from possible roundstart rulesets

### PR DESCRIPTION
**Pull request by SonixApache**
🆑 
 - rscdel: christmas is ruined enough, the grinch will no longer show up among roundstart antagonists

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Grinch is shot on sight and has no real standards other than steal stuff

**Comment by ShiftyRail** [comment]
Hey at least wait for Orthodox Christmas

**Comment by jknpj** [comment]
This should really be handled by a holiday check

**Comment by ghost** [comment]
Grinch is a absolute shit mode and feels like a april fools joke that stayed in the game for far too long already.

**Comment by Kammerjunk** [comment]
speedmerge when
@jknpj tbh I don't think any holiday check can remove it before it gets old

**Comment by ShiftyRail** [comment]
>grinch is a shitmode 

Why ?

>This should really be handled by a holiday check
>tbh I don't think any holiday check can remove it before it gets old

Why ?

I'm asking in earnest, I did the Grinch antag mode as a request, it's not meant to be the centre of the round, just a minor annoyance you can interact with.
Sonix quite literally went AFK after a round of Grinch started, then reconnected and openly flirted with a gayboy who build up a ghetto bar. Perhaps the Grinch would be more to xer liking if it were to be kissable ?

**Comment by Kammerjunk** [comment]
>it's not meant to be the centre of the round, just a minor annoyance you can interact with.

because that isn't accurate to how it plays out
it's a simple animal (with all the benefits that that comes with) that can ventcrawl, has effective all-access, can fuck up every single airlock it passes by, can hold and shoot guns, can mess with a bunch of other machinery (including setting APCs to panic siphon), and it can fire on rounds so dead that there is not an earthly (or spessly) chance for the crew to react before the station is entirely fucked
the antag works entirely by will, which means you're relying on the player to not be a boring fuckwit. you call Sonix out specifically, but I've seen him in particular hold back on being a fag since the grinch has a HIGH CAPACITY for being a fag

every time I have played with the grinch gamemode, the round has ended very early as a direct result of the grinch having more power than ideas, so I'll just wait until it's gone

**Comment by ShiftyRail** [comment]
If it's about moderating the interactions with APCs & Air alarms, then sure, why not

**Comment by Kammerjunk** [comment]
it's about the mode being ass

**Comment by ShiftyRail** [comment]
The general idea of Grinch is "non-lethal spanner in the works". Is that such a flawed concept in & off itself

**Comment by Kammerjunk** [comment]
yes, actually

**Comment by ShiftyRail** [comment]
I'll make an antag that turns people horizontal next time then

**Comment by Kammerjunk** [comment]
you already did

**Comment by ShiftyRail** [comment]
I must protest that I didn't, because the grinch can't hold and shoot guns. It's clumsy. (#21219)

**Comment by Kammerjunk** [comment]
idk it was shooting taser bolts just yesterday

**Comment by ShiftyRail** [comment]
image

Must have been bad RNG whilst facing the Grinch, then.

**Comment by Kammerjunk** [comment]
doesn't really matter anyway
there's a lot to be said about how antags work and how players play but I really don't feel like reiterating all that again again (etc)
this mode plays out about as well as the initial version of catbeast

**Comment by ShiftyRail** [comment]
It's not that hard to admit you were completely wrong, even if it breaks character a bit
But fine, since so many people want it removed they must have a good reason after all.

**Comment by Kammerjunk** [comment]
you responded to one tiny portion as if it refuted everything I said
do you think that guns are the only way to kill people or are you intentionally acting like this?

**Comment by ShiftyRail** [comment]
Reasoning - which could be flawed - was that, yes, guns are the only way here to kill people en masse since shocking a door is random at best, siphoning air takes a long time & is preventable with firelocks, removing power doesn't kill people instantly. In that sense, I didn't make an antag that turns people horizontal, no sir.

Grinch can't baguloth (his bag is a special form of the bag of holding which prevents that), can't interact with canisters, can't singuloose, he cannot make too much breaches or he will perish himself. He can of course try to WHACK people with a toolbox or melee items but with his measy 125 HPs, no regeneration and a fucking target on his back I don't think most grinches would do that.

Sorry if you read this comment as hostility or playing dumb but that comparison to catbeasts - humanoids with the same capabilities as a traitor without an uplink - isn't really warranted in my book

Think it's best to enjoy our new roundstart grinch-free game & leave it at that :man_shrugging:

**Comment by SonixApache** [comment]
my issue with the grinch was that it spawned on 3pop roundstart
and went around venting the station, shocking doors and toolboxing people
and couldn't ventcrawl at roundstart because the pipes had no air in them

that's not fun for anyone

it's fine as a midround / latejoin ruleset, it's fine as a bus ruleset, just not as solo roundstart

**Comment by ShiftyRail** [comment]
>and couldn't ventcrawl at roundstart because the pipes had no air in them

That's very strange

**Pull request merged**
