### PR TITLE
Radiation collector tweak/experiment

### PR DESCRIPTION
**Pull request by gbasood**
The change to format_text.dm just fixes an infinite loop if the formatted value is negative.
# I updated this to reflect some misunderstandings on my part of what this would affect.

The rest of this PR changes radiation collectors.
Power output from radiation collectors now follows a combination of a logarithmic curve and the old linear equation. This means that you will get diminishing returns from radiation sources as pulse strength exceeds 2000, although the point at which those returns become unviable is probably much higher.

In other words, this nerfs energy collection from singulos and SMEs both when working very large bursts of radiation, but lower values get a significant bump.

So autists will have a harder time getting miniature suns worth of energy, and casual engineers will have a somewhat easier time of it. But it isn't a plateau like the logarithmic curve I was going to use. Good outputs will still output more than bad by a VERY large margin.

Red is the old method, green is the method I _was_ going to use initially, and purple is the new method (which was the sqrt of the product of both curves)
`p` is just the value of an tank's worth of uncooled plasma.
https://www.desmos.com/calculator/skca9ntrwj this is the graph so you  can mess with values if  you'd like.

For my own reference, the coefficient was 24.7487 before I messed with it.
Also big thanks to Rhaplanca for the math help.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by FudgePucker** [comment]
First off.
Don't put a bug fix in a balance change.
Secondly.
What the fuck?
Why would you nerf the autism engines, and make it easier on shitters?
Now its less rewarding to spend an hour setting up an engine cooling plasma and setting up emitters, and more rewarding to just go 'fuck it' and hastely set up the singlo with room temp plasma?
:-1: \* 1000

**Comment by gbasood** [comment]
The bug fix is fixing a possible bug, really. It shouldn't even be occuring and if necessary I'll separate it from the PR.

SME outputs are actually kind of ridiculous, both before and after this, but at normal game values you shouldn't see a huge difference in output. Especially since energy consumption will probably never exceed your SME's setup, maximum autism or no.

That said, if the coefficient needs to be tweaked so that the SME isn't completely screwed over, it will be.

**Comment by gbasood** [comment]
~~Actually I just realized, this probably nerfs max singulo too.~~
Yep, this nerfs all radiation collector output.
I might need to change this in light of that, but I'll wait for more people to look at this

**Comment by gbasood** [comment]
@FudgePucker I fucked up in my initial understanding of the impact of this and I've updated the OP respectively.

Again, you're always going to get better results from cooled plasma than uncooled. And it looks like the SME will always be better than the singulo, but I'd need to see the energy value of a good SME setup to be certain.

Either way, this is not a huge nerf or buff. You're more than welcome to plug some values into the equations yourself if you'd like.

**Comment by clusterfack** [comment]
I don't really see the point with the way it works now, or what this is addressing?

**Comment by PJB3005** [comment]
Mostly just nerf the SME and normalize output so that future balancings and game mechanics can be reliant on a need to up power production.

**Comment by clusterfack** [comment]
I don't really think this is a nerf to the SME. Since the SME power production is already heavily limited, since it reduces at I believe the cube root.

Either way this is a pretty weird way to indirectly nerf that.

**Comment by Kurfursten** [comment]
A more direct way to nerf the SME would to make it start with 6 rad collectors like the singulo. 16 collectors can make a big difference, if a linear one.

Not that this PR is meant for that, I'm just sayin' you could do it.

**Comment by gbasood** [comment]
@Kurfursten that just nerfs roundstart SME though
Not as if you couldnt just make more collectors

**Comment by Kurfursten** [comment]
Of course, but doubtless no new rad collectors are ordered in 99.9% of shifts.

**Comment by CptWad** [comment]
back when teg could be set up in 20 minutes so you had an hour to autism with another engine I used to realize the full power of the singlo
To get the singlo to SME levels you would need eight more collectors and all plasma supercooled
nerfing both the SME and the singlo is not the way to do it. 

if you want to nerf the sme just make it shit more gasses or make it so that people cant do the meme where they put the cooling loop inside the sme containment somehow

The singlo is a shit powersource, making it worse is no way to go

**Comment by BarneyGumball** [comment]
I'd like to see some examples of these changes in action.  IE. Power outputs of the round start singulo setup with room temp plasma before and after these changes.

The AME and the base Singularity setup as they are now are great learner engines.  They produce just enough power to power the station in most situations, but if you want to avoid having to maintain them, then you need to learn more engineering stuff (cooling plasma, SME, TEG running on gas miners, etc).

I feel like this would be taking away the incentive for new engineers to learn the more advanced engineering stuff and weaken the fun of established engineers trying to make crazy engines.

**Comment by gbasood** [comment]
@CptWad 
This isn't a direct nerf to the SME.
It actually still favors the SME.
It nerfs individual collectors at VERY HIGH LEVELS, like the kind of levels where you don't even care how much power you're outputting anymore.
Unless you're just fucking with the engines at that point to stroke your ego with numbers I guess

I'm not sure this addresses what I wanted it to anymore but I'll leave it up for a bit more since any discussion on engine balance is useful

**Comment by gbasood** [comment]
discussion is dead, ripo

**Pull request closed without merging**
