### PR TITLE
New cargo console entries

### LINKED ISSUE #31535: [Feature Request] Make BODA vendomat packs obtainable without e-magging
**BODA** Vendomats packs are currently only obtainable by virtue of either finding one placed by a mapper or e-magging a cargo console and ordering the dusty old crates pack that gives you both the nazi-vend and the commie-vend. This is quite frankly unacceptable as one, **BODA** is a third-wheel in with these two packs that are the only reason anyone that could order them in the first place would and two, **BODA** isn't even anything crazy or illegal, it's just russian soda water. 
It is due to these facts, I believe **BODA** should be given a separate cargo order that can be obtained by simply solder hacking the cargo console. I figure it makes sense given you can order normal russian shit like the outfit box that gives the ruskie DJ's transport disk or the neo-russian outfits, so why not the **BODA** vendomat packs to go with?

This Issue sponsored in part by the ASWDC (Ayy Soda Water Drinker Coalition).
[featurerequest]

### PR DESCRIPTION
**Pull request by ManopolisJones**
## Changes

- Adds office supply crate for 15 credits under the supply group; has folders, pens, paper and two office lamps (grey ones)
- Adds portable scrubber and air pump crate for 25 credits under the engineering group; has one each
- Adds space heater crate for 20 credits under supply group; has two heaters per crate
- Adds air conditioner crate for 20 credits under supply group; has two ac's per crate
- Adds package wrap crate for 10 credits under cargo group; has four rolls of package wrap which is roughly 94 uses
- Adds cargo poster crate for 50 credits under cargo group; has six posters which can either be a seal or flag
- Adds russian beverage stack of packs for 10 credits under vending machine group; has two recharge packs of soviet soda machines and can be purchased from a contraband hacked cargo console (soldering iron)
- Removes soviet soda recharge packs from old and forgotten stack of packs

## Elaboration
In the unlikely event some of these "irreplaceable items" were to go missing, or somehow get destroyed, there are now cargo entries to help you replace or get more of them. The paper in the office supply crate is specifically the paper pack with the red ribbon on it, originally I wanted to also add some nano-paper packs with it, but seeing the librarians nano-paper dispenser that couldn't even use the nano-paper packs to replenish it due to requiring plasteel to recharge it, I thought it best to just leave it out for the time being until someone changes it. Another thing to note in the office supply crate are the specifics of the goods, such as the red, blue, black and fountain pens, as well as the folders being red, blue, black, med white, and cargo orange. Soviet soda recharge packs were removed from the old and forgotten stack of packs due to getting their own entries and being frankly out of place with the commie and nazi vend.

## Changelog
closes #31535

:cl:
 * rscadd: Adds several new entries to the cargo console

### CODE REVIEW

**Comment by Eneocho** [comment]
Some thoughts:
* Considering you can recolour the paper bins with a crayon (or bleach in case of white), giving that many colour variants feels off to me.
* The arts and crafts crate already has wrapping paper (and 3x gift wrapping paper)
* I'd make the air pump crate separate from the scrubber and slightly more expensive.
* Same with the space heater and air conditioner. You sometimes want only the heater (for leather, to control atmos with a rogue atmosian, etc) or only the cooler.
* For what amounts to simple posters, 50 credits feel a bit much (considering you're selling heating machinery for 20).

**Comment by cloutcode** [comment]
add toner to the office supplies

**Comment by ManopolisJones** [comment]
> * Considering you can recolour the paper bins with a crayon (or bleach in case of white), giving that many colour variants feels off to me.

The office supply crate has folders, not paper bins, if folders can be recolored with crayons, then I ought to change it to something like three orange folders or something

> * The arts and crafts crate already has wrapping paper (and 3x gift wrapping paper)

It only has one roll of wrapping paper, the wrapping paper crate is mostly drawn from experience on playing packed, where I just wanted the paper and not the million other things in the box.

> * I'd make the air pump crate separate from the scrubber and slightly more expensive.
> * Same with the space heater and air conditioner. You sometimes want only the heater (for leather, to control atmos with a rogue atmosian, etc) or only the cooler.

I think i'll probably separate the space heater and AC units into two separate boxes with two each, but just keep the scrubbers and air pump in the same box. I've heard it said that pumps are more useful then scrubbers before, but I figured it was a safer bet to just keep them in the same crate since you always see them together on station.

> * For what amounts to simple posters, 50 credits feel a bit much (considering you're selling heating machinery for 20).

Cargonia seals and flags are more then just "simple posters", they are signs of cargo superiority, they are morale enhancement devices, and they are without a shadow of a doubt, finely crafted. If one is to order SIX of these fine Cargonia products, you bet your ass they should be expensive.

> add toner to the office supplies

The first entry in the supply group is for toners cartridges, which has six in a crate, so i'm not too sure that'll be necessary?

**Comment by xeroxemnas** [comment]
pinpointer crate when. Two isn't enough.

**Comment by Kurfursten** [comment]
All of those paper products aren't irreplaceable, they're supposed to be printed at the biogenerator; some stepping on botany toes

**Comment by Eneocho** [comment]
Biogenerators can't make folders nor pens. So in a sense they are irreplaceable (you can get extra pens if you buy a PDA)

**Comment by Kurfursten** [comment]
Should've added folders to the biogenerator list instead

Pens are fair though. It's hard to imagine running out of pens but you could easily throw a sixpack of pens into an art crate or create a collectable pens crate for the special pens.

**Comment by ManopolisJones** [comment]
Got around to looking into the biogen, and you're right about about some of the paper category items in there, like the clipboard and wrapping paper, which I totally neglected to remember when making both the office supply crate and wrapping paper crate. That being said, I still like the wrapping paper crate as a cargo category entry, and i'm thinking if the office supply crate could be better changed with something like those office lamps you'd see in the abandoned office on box. 

Also got me thinking about the paper category in the biogen, and how much I dislike how paperbins function. I think the paper packs with the red ribbon should be added to the bio gen in place of the bin full of paper, as well as a grey folder which is currently not present in the office supply crate. With that, I could justifiably remove the paper pack inside the office supply crate, but keep in the colored folders for people who might want them in specific. As for something like pens, a three pack would be pretty nifty to have in something like the merch computer, or art crate like you said, however I couldn't imagine a collectible pens crate at all. 

I think the best case scenario for if we were to keep the office supply crate would look like: Colored folders, office lamps, fountain pen, and either the pen three pack in the office crate, or in the arts and crafts crate. I still think the paper pack would fit well in the office crate, but if botany got it I can see why it would be justifiably left out.

**Pull request merged**
