### PR TITLE
Updates 3 Gun Sprites

### PR DESCRIPTION
**Pull request by drawsstuff**
<sprites>
Changes can be viewed here. 

updates

:cl:
 * rscadd: Nanotrasen has updated the appearance of their Ion Rifle and Lawgiver. The Syndicate has countered by updating the design of their flare gun.

### CODE REVIEW

**Comment by yclatious** [comment]
Based, the flaregun looks like such shit right now, same for the lawgiver, doing good work draw.

**Comment by SonixApache** [comment]
like the new shapes, despise the colors and shading

**Comment by gurfan** [comment]
I like the lawgiver and flare gun but why did you just tint the ion rifle blue

**Comment by RealestEstate** [comment]
personally not a fan of the flare gun but the rest look good

**Comment by GreatBigFailure** [comment]
Looks great. Current flare and lawgiver look like someone made them in mspaint. Ion was okay but I still think this is an improvement.

**Comment by RealestEstate** [comment]
oh could you preserve the old sprites in the codebase by adding a suffix to their sprite like "flaregun_OLD" or something

**Comment by BomberBro** [comment]
ion looks sorta weird, I like the change to the blue charge area but the body itself looks too blue

**Comment by DeityLink** [comment]
It's crazy how your resprite of the Ion Rifle looks exactly like how I remember it.

**Comment by Kharkov72** [comment]
B L U E
L W
U   H
E       Y

**Comment by djkramer123** [comment]
Dang, those all look really good.

Nice.

**Pull request merged**
