### PR TITLE
Protolathe Cleanup

### PR DESCRIPTION
**Pull request by iFlashYou**
Delets some redudant or useless/never used designs from the protolathe.

:cl:
 * rscdel: Deleted some redudant or useless/never used designs from the protolathe

### CODE REVIEW

**Comment by DrSnips** [comment]
I'd like to leave the basic components so you have the proto or auto to make them in case shit happens.

**Comment by iFlashYou** [comment]
If you did research then you can just use the T2 componets

**Comment by Pathid** [comment]
>removing bruise packs and ointment

Correct me if I'm wrong but doesn't this mean you can't get to biotech 2 without an autolathe or a exofab?

**Comment by aceedex** [comment]
Mining redundancy gone is good.
T1s and the med supplies should stay

**Comment by iFlashYou** [comment]
Readded the med ointment and bruise pack

**Comment by NigglyWiggly** [comment]
For what purpose

**Comment by Hoshi-chan** [comment]
Fucking why? How is anyone without a protolathe going to make their own machines?

**Comment by Hoshi-chan** [comment]
Fucking why?

**Comment by BarneyGumball** [comment]
Did you test autolathes?  It looks like you're making it so they can't build the basic components either.

**Comment by iFlashYou** [comment]
@BarneyGumball Yeah, they can still make the componets. They use their own design list in the autolathe code.

**Comment by iFlashYou** [comment]
Due to popular demand are now the T1 Stock Parts back

**Comment by ghost** [comment]
The pick still saves diamond if you care about that. I use the sonic a fair amount when we get fucked, I arrived late to fucked shit and I gotta print something to go mine myself, or the sci mafia blew all the diamond without making a synth like usual.

Did someone put something in the punch, why is there suddenly a flood of trimming?

**Comment by SarahJohnson489** [comment]
The pick still saves diamond if you care about that. I use the sonic a fair amount when we get fucked, I arrived late to fucked shit and I gotta print something to go mine myself, or the sci mafia blew all the diamond without making a synth like usual.

Did someone put something in the punch, why is there suddenly a flood of trimming?

**Comment by SarahJohnson489** [comment]
The pick still saves diamond if you care about that. I use the sonic a fair amount when we get fucked, I arrived late to fucked shit and I gotta print something to go mine myself, or the sci mafia blew all the diamond without making a synth like usual.

Did someone put something in the punch, why is there suddenly a flood of trimming?

**Comment by SarahJohnson489** [comment]
The pick still saves diamond if you care about that. I use the sonic a fair amount when we get fucked, I arrived late to fucked shit and I gotta print something to go mine myself, or the sci mafia blew all the diamond without making a synth like usual.

Did someone put something in the punch, why is there suddenly a flood of trimming?

**Comment by SarahJohnson489** [comment]
The pick still saves diamond if you care about that and people using diamond for so much else. I use the sonic a fair amount when we get fucked, I arrived late to fucked shit and I gotta print something to go mine myself, or the sci mafia blew all the diamond without making a synth like usual.

Did someone put something in the punch, why is there suddenly a flood of trimming?

**Comment by SonixApache** [comment]
@SarahJohnson489 
One deposit of plasma is enough for a sonic jackhammer, and a small stack of plasma is enough to just *buy* a diamond pick, though.

**Comment by ghost** [comment]
It's for when things break down and science has to work on it from the science side of things.

**Comment by DamianX** [comment]
👎 'd

**Pull request closed without merging**
