### PR TITLE
HOW DID THIS EVEN COMPILE?????

### PR DESCRIPTION
**Pull request by Exxion**
I thought the whole point of using defines was to prevent shit like this

Will this fix any visible bugs? I don't fucking know! Probably! This shouldn't have even compiled before! BYOND a shit!

### CODE REVIEW

**Comment by 9600bauds** [comment]
What was this even causing

**Comment by Exxion** [comment]
No idea! But it was an invalid define so I'm still lost on how it compiled

**Comment by 9600bauds** [comment]
How did you even FIND this

**Comment by Exxion** [comment]
I was talking to my friend about how building a spacepod actually spawns two of them so I decided to look at the history for spacepods\construction.dm to see if I could find the cause and I found this instead

**Comment by clusterfack** [comment]
It compiles because list()s are created at server start, not compile time. Also it's not like it's a var or anything that's an associated list.

**Comment by Exxion** [comment]
But it is a define
And I was told to use defines in associated lists for the _express reason_ that a typo in a define would fail to compile while a typo in a string would just cause runtimes
Which is apparently not true

**Comment by clusterfack** [comment]
You're talking about something else here, this list is explicitly defined as a static thing at roundstart. If you were creating this list through code it would fail to compile.

**Comment by Exxion** [comment]
Ah
Well that's that mystery settled
Now to find out WHY THE FUCK MAKING A SPACEPOD MAKES TWO

**Comment by Exxion** [comment]
It... doesn't?
At least not on local
Did this somehow fix it?

**Comment by clusterfack** [comment]
Pretty sure someone put in some shitty code so that it spawns a spacepod in case it fails to build or something

**Comment by Exxion** [comment]
Ah yes, I saw that while looking for the problem
If it tries to set its index to zero, a spacepod appears

**Pull request merged**
