### PR TITLE
Removes remote_view

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Why:
- Being able to remotely see anyone you've heard at some point who wasn't dead to track their activities is too powerful
- Paradoxically, very often whenever you had this ability everyone else had the psychic resistance gene, meaning this ability couldn't be used on them, but I do not consider this to balance out this gene.

If the change is liked enough and ready to be merged, don't merge anything else until DNA_SE_LENGTH is changed
:cl:
 * rscdel: The remote view genetic superpower is no more.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
I think this is one of the biggest offenders of genetics
It completely ruins a game about some sort of healthy paranoia and being on your guard/trying to find someone when you can just lock on to them at anytime.

If people are complaining about security getting a scrying orb after killing a wizard, then this is the same thing, but you get it by simply talking to the geneticist.

**Comment by utilitas-** [comment]
What if instead of being able to remotely view people you've heard talk, you instead are able to remote view simple critters you've heard/touched? Use Sasha as a scouting dog. Find out which motherfucker took Ian. Make Poly useful.

**Comment by Kurfursten** [comment]
I like the utilitas suggestion. People would be more amenable to the power existing in a different form than pure r-word (remove)

**Comment by Probe1** [comment]
uh like do a better job with this then it'll get merged.  the idea of it being like the ai camera is cool I guess.

**Comment by Blithering** [comment]
Tinfoil hats solve more problems than people know, but some message to the person being viewed to let them know they're being spied on would be good.

**Comment by Killette2** [comment]
Use astral wizards to cut their astral cord

**Comment by Kurfursten** [comment]
I don't think this is ever going to have support in its current form, which is a shame, because remote view actually is a problem, one of those old legacy problems. But it needs a better solution.

**Comment by Killette2** [comment]
If you get naked while being remote viewed it should give the viewer eye damage as long as they continue viewing. Perfect balance.

**Comment by utilitas-** [comment]
Or if you start singing with a rubber ducky in hand, any viewer gets more brain damage the longer they watch.

**Pull request closed without merging**
