### PR TITLE
Fixed chemmaster/condimaster menu

### LINKED ISSUE #6381: Chemmaster/Condimaster menu
(WEB REPORT BY: vonzippenstein REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
6c8fd2961c2c88f756e86028b79da4e0bcb935ae

>General description of the issue
ChemMaster 3000 menu turns to Condimaster menu when you open the SnackBar menu.

>What you expected to happen
ChemMaster menu to stay as the ChemMaster menu.

>What actually happened
It turned to the Condimaster menu.

>Steps to reproduce if possible
Open the ChemMaster menu then open the SnackBar Machine menu.

### PR DESCRIPTION
**Pull request by Faptastic**
- Fixes #6381 and also updates the UIs to use the browser datum, gotta make em all match.
  Tweaked machines: Condimaster, all-in-one grinder, chemmaster, snackbar machine.

I left all that I didn't entirely understand alone because theres some quirky stuff in there and I've managed to get it working as-is.

### CODE REVIEW

**Comment by Probe1** [comment]
Insert pill bottle?  




This is :+1:  :100: :+1: though so much better.

**Comment by Faptastic** [comment]
The pill bottle thing is what I was talking about, i legitimately had no idea if it was meant to be like that or not, I double checked the code and I'm fairly sure it was like that when i got there.
I know you can insert a pill bottle into the snackbar machine and lose it forever due to the complete failure of the warning message but otherwise it's all good.

What threw me off about the condi machine is the pill warning was for the condi machine but inside the snackbar code, which is another file altogether. It's a mess in there and I'm lucky to escape alive.

**Comment by Probe1** [comment]
Its definitely inheriting behavior from a parent right?

**Comment by Faptastic** [comment]
Is any of the 3 machines besides the chemmaster even supposed to accept pill bottles? because otherwise I'll just go ahead and put a stop to the pill business outright unless it's the chem version of the machine.

**Comment by Probe1** [comment]
nah only the chemmaster should produce pills and accept pill bottles.

**Comment by N3X15** [comment]
Is this good to go or does it need to sit in CONTROVERSIAL?

**Comment by Probe1** [comment]
its good to go :+1:

**Pull request merged**
