### PR TITLE
Better rag smothering and stuff

### LINKED ISSUE #14556: Smothering somebody with a rag also wipes them down
#### Description of issue
If you target the mouth and click somebody you begin to wipe them down with the rag as well as smother them

#### Difference between expected and actual behavior
Smothering only

#### Steps to reproduce 
Equip rag, apply chemicals, target mouth, click somebody adjacent

#### Length of time in which bug has been known to occur

Unknown

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### LINKED ISSUE #28890: Rag Smothering is broken
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
f9e70f0b79bed274003cae9dbbd2980ce20a47ca

# Description
Date rape is no more

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #14556
Fixes #28890

:cl:
* tweak: Reworked rag smothering to fix a few bugs. The new implementation requires you to target the rag at their mouth with a 1 second delay (a visible warning and SFX play as soon as an attempt is made). Species that do not breath cannot be smothered. People wearing smoke-blocking masks such as gas masks, internals, clown masks, surgical masks or cigarettes (if they're lit) cannot be smothered either. Upon success, all reagents inside the rag will be transferred inside the target (up to 5u).
* bugfix: You no longer try to wipe down people that you are currently smothering or bandaging with a rag.
* bugfix: You no longer try to wipe down the Sink when you fill up your rag.

### CODE REVIEW

**Comment by DamianX** [comment]
As far as I can tell `current_target` is only cleared at the beginning of `attack`, so if you attack a human once and then try to delete said human, said human would hard-delete because of the reference you keep in the rag.

**Comment by DeityLink** [comment]
> 
> 
> As far as I can tell `current_target` is only cleared at the beginning of `attack`, so if you attack a human once and then try to delete said human, said human would hard-delete because of the reference you keep in the rag.

Right, it is now null'd after being checked in afterattack()

**Comment by Dacendeth** [comment]
Why would you ever do this over injecting someone, the situation where you can get a good grab on someone and the time that takes seems like you could just syringe someone in that time/situation instead.

**Comment by DeityLink** [comment]
> Why would you ever do this over injecting someone, the situation where you can get a good grab on someone and the time that takes seems like you could just syringe someone in that time/situation instead.

Not quite. Syringe injections take 3 seconds. if you're efficient you can manage smothering in 2 seconds alone, and maybe even 1.5 if someone's grabbing them in your place.

It's not meant to be drastically better or worse than syringes, it's just an alternative.

**Comment by Irradiation** [comment]
I think @Dacendeth meant "Why would you do this over harmsyringing" (which is instant)?

Unless I'm horribly out of the loop, harmsyringing still works reasonably well.

**Comment by Eneocho** [comment]
>
>I think @Dacendeth meant "Why would you do this over harmsyringing" (which is instant)?
>
>Unless I'm horribly out of the loop, harmsyringing still works reasonably well.

Perhaps if there are no syringes available? But getting syringes is so easy I can't see the point either.

**Comment by help-maint** [comment]
For RP of course

**Comment by PrimeDSS13** [comment]
I think you're underestimating how terrible grab intent is Deity

**Comment by DeityLink** [comment]
Well I thought it might be a bit too strong otherwise but if you guys think it's fine I'll trust your judgement.

**Comment by BomberBro** [comment]
This isn't a MOBA, there's no problem if one option is faster. Rags being worse at injecting chems compared to a syringe makes sense, but it's still a nice option to have and provides an alternative to harmsyringing that you can both easily get and gives you an alibi on having it if you're say, a bartender (try that with a bent syringe). 

That said, I'd remove the grab thing anyway because grab intent then using an item is somewhat unwieldy, but it should probably have more time than one second if that's that's the case. Does this warn the victim beforehand that somebody is trying to rag them?

**Comment by DeityLink** [comment]
> Does this warn the victim beforehand that somebody is trying to rag them?

Yes it sends a warning visible message. I might add an SFX too.

**Comment by DeityLink** [comment]
There, it now plays thudswoosh.ogg (the grab sfx) when you start smothering someone.

**Comment by drawsstuff** [comment]
Diety Appreciation post. You actually listen to feedback instead of arguing your intent and continually make good changes in just about every PR I've seen from you. 👍

With that out of the way is it possible to keep `user.visible_message("<span class='warning'>\The [M] has been smothered with \the [src] by \the [user]!</span>", "<span class='warning'>You smother \the [M] with \the [src]!</span>", "You hear some struggling and muffled cries of surprise")` in any capacity? It's one of the cooler flavor texts.

**Comment by Blithering** [comment]
Would it be possible to change the flat delay into a gradual transfer of the reagents to simulate it being breathed in over the course of the smothering? Either way, so long as you can still go around asking people if they think the rag smells like chloral or not.

**Comment by drawsstuff** [comment]
> Would it be possible to change the flat delay into a gradual transfer of the reagents to simulate it being breathed in over the course of the smothering? Either way, so long as you can still go around asking people if they think the rag smells like chloral or not.

Unfortunately people are gonna run at the first sign of trouble. A harm syringe is useful because it leaves no room for reaction. You can of course still ask people before you smother them.

**Comment by DeityLink** [comment]
@drawsstuff the line is still in there, now improved with proper syntax when smothering yourself (not sure why would anyone do that but still) `user.visible_message("<span class='warning'>\The [M] has [self_smother ? "smothered themselves" : "been smothered by \the [user]"] with \the [src]!</span>", "<span class='warning'>You smother [self_smother ? "yourself" : "\the [M]"] with \the [src]!</span>", "You hear some struggling and muffled cries of surprise")`

> Would it be possible to change the flat delay into a gradual transfer of the reagents to simulate it being breathed in over the course of the smothering?

I'd argue that some reagents are dangerous even from the first unit so maybe not.

**Comment by strawberrytan** [comment]
Additionally, trickle of chems is why stomachs completely broke chemical mixtures because of minimum requirements to metabolise

**Pull request merged**
