### PR TITLE
Slime "hair" styles

### PR DESCRIPTION
**Pull request by ghost**
[sprites] [help]

slimehairs

This PR:

1. Enables the ability for the Evolved Slime/Slime Human race unlocked through Xenobiology to select and change their "hair" and facial "hair" styles.
2. Fixes an inconsistency where the Evolved Slime race was not listed in the whitelist for the "Bald" hair and "Shaved" facial styles unlike every other humanoid race.
3. Adds prompts on becoming an Evolved Slime to select your hair and facial hair styles.
4. Adds four initial slime "hair" styles to choose from.
5. Causes immense butthurt among a vocal minority of the playerbase who prefer their slime people to ONLY be dumpy bald humanoids.

Though there are only four styles to start with, that's still more than the existing zero. I plan to add on more as I draw them, and anyone else is welcome to contribute sprites. The rule of thumb was and is to create styles based around the nature of the race  so they should involve features like tentacles, spines, bubbles, etc.

Final notes: the "hairs" are slightly more opaque than slimepeople's bodies and inherit their colors from the slimeperson's multicolored_skin values. These colors are still random (I believe they're generated on the original mob's spawn), but a color selector could easily be added along with the style selection if people want it.

:cl:
 * rscadd: Slime Humans can now choose (facial) "hair" styles.
 * imageadd: Four unique "hair" styles for slime people.
 * tweak: "Evolved Slime" race added to whitelist for Bald and Shaved styles.
 * tweak: Fixed a few oddities with the body icons for slime humans.

### CODE REVIEW

**Comment by Blithering** [comment]
My only gripe is that it's not unlocked through a xenobiology slime hair tonic that also lets you change colours

**Comment by ghost** [comment]
> My only gripe is that it's not unlocked through a xenobiology slime hair tonic that also lets you change colours

I personally don't see a need to gate a simple cosmetic update behind progression. 

As for color, it's currently randomly but you can still change the hair color seperately with hair dyes.

Something I'd like to do in the future is make it so that slime humans can recolor themselves by eating existing color items/reagents like paint or crayons. My ideal option would be if one of those changed the base color, which would then slightly blend with the colors of whatever reagents are in the slime person's body container.

**Comment by Gringonius** [comment]
Needs the controversial tag. Slime people were designed to be just humanoid slimes instead of fetish material on purpose to prevent waifufaggotry. At the very least replace with blatant monstergirl quest reference with a different hair to make this less obvious.

**Comment by ghost** [comment]
We have a human hairstyle that references a a highly sexualized 500 year old vampire loli. Should we remove that? Should we remove all anime hairstyles? Should we remove feet from humanoid races because feet are a common fetish?

I just want the option to look aesthetically pleasing as a slime person. The original intent of the race is irrelevant because this server an unending project where people are constantly changing.

I just want the option to look aesthetically pleasing as a slime person. If people want to beat their meat to a 32x32 sprite of a dumpy semi-transparent spaceman then that's their problem. The original intent of the race is mostly irrelevant since this server is a constantly changing project, but I still left them genderless because they're still just humanoid slimes.

**Comment by Killette2** [comment]
I hate to make things awkward but I kind of have a human fetish myself.

**Comment by SonixApache** [comment]
I wish we could just have something like a `slimify()` proc for normal (human) hairstyles instead of snowflake stuff

**Comment by ShiftyRail** [comment]
Careful if it's a prompt, because it'll steal focus if you're SoC into a slime.

**Comment by ghost** [comment]
>I wish we could just have something like a slimify() proc for normal (human) hairstyles instead of snowflake stuff

Personally, I think giving them unique styles adds more character to the race. Just taking regular styles and making them semi-transparent feels kinda lazy and doesn't make much sense considering they're made of slime.


>Careful if it's a prompt, because it'll steal focus if you're SoC into a slime.

The prompt is tied to the reagent code, so I don't think it'll appear if you're transformed in any way except mutationtoxin.

**Comment by ghost** [comment]
review pls

**Pull request merged**
