### PR TITLE
Removes most Pulse Demon possession mechanics (because it is broken)

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
**This is a first PR towards a larger set of Pulse Demon PRs aimed at improving how it plays out.**

Anyone who has had experience with playing Pulse Demons and has dabbled into possessing objects can attest to how weirdly it plays out. Rather than try and put an extreme amount of effort into fixing every single edge case and possibly leave a lot of ridiculously specific code that whitelists Pulse Demons from most sane checks it might be better to trim it right now and then revisit it at a later point with a different approach. As awesome as it may be for the pulse demon to do this stuff, it's also broken in mechanical ways.

Removes possessing bots, cyborgs, batteries, guns and rechargers. Bots are in an awkward position and in fact I believe it is impossible for a pulse demon inside a bot to get out. We have poor support for handling multiple players in control of a single mob, thus cyborgs should be left alone for now. Batteries, guns and rechargers are not only far too gimmicky from a gameplay standpoint but also suffer from the same problem of being pretty broken.
Does NOT remove possessing holopads, cameras and intercoms. They will likely be addressed at a later point.

In any case I hope that with most of the possession out of the way it will be possible to handle affecting machinery in a different manner; currently Pulse Demons are still crippled by limited room vision (and moving towards cameras teleports them away from the APCs), they cannot interact with machinery they're right on top of (they need to be directly connected to the APC). They should still be able to heavily affect machinery but they should not be necessarily in direct control of it.

:cl:
 * rscdel: Pulse demons can no longer possess bots, cyborgs, batteries, guns and rechargers.

### CODE REVIEW

**Comment by pedr69** [comment]
you can actually get out
just need to return to the area you entered the bot and click the APC

**Comment by boy2mantwicethefam** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
better to include the replacement functionality alongside whats being removed imo

**Comment by boy2mantwicethefam** [comment]
One thing at a time

**Comment by Eneocho** [comment]
I liked that one round where the pulse demon got inside the capgun and was  chilling as a sentient giga gun.

**Comment by boy2mantwicethefam** [comment]
I'm hoping to let the bots be directly malfunctioned (they currently need to have their maintenance panels open to be emagged, even though the pulse demon can't open the maintenance panel), somehow allow cyborgs to get some messed up laws (could be ion, could be more aggressive pulse demon-induced ones such as replacing a random law with an "error" message, maybe rig the cyborg rechargers like time-limited time bombs to do that) and camera interaction to be replaced with just letting the pulse demon sort of turn into a sort of room-bound ghost. Hopefully. I'm still not sure how to approach that but I'll get to that. I also plan to look into the spells and how they scale, as well as revisit how the Pulse Demon gains max charge.
I learned from the vampire PR that these sort of changes should be granular, imagine if I spent a lot of time adding all that but the players downvoted the whole PR for the removal of most possession mechanics.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
the charge cap mechanics should be looked at yea
but what sometimes happens is someone proposes something like this as a first step in a series of changes then gets bored midway thru and the feature gets stuck in a broken ish state

**Comment by pedr69** [comment]
yeah
i did some tweaking and its better than it used to be but it's still shit
think the scaling maxpower upgrade boy2man added and i later reverted could be better, just need to raise the spellcast / upgrade costs a fuckton and basically completely rework all the numbers
and make ion rifle projectiles hit the demon

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
they were definitely more fun to play when they could increase maxcharge more easily

**Comment by boy2mantwicethefam** [comment]
I don't plan on not working on pulse demons, and the change can be reverted easily if it needs to be.
I plan on doing away with the "1.5x" and "1/3" upgrade modifiers because they feel off, and replace them with something saner and linear.

**Comment by boy2mantwicethefam** [comment]
Nvm I don't feel like working on it anymore

**Pull request closed without merging**
