### PR TITLE
Juggernaut Mantle

### PR DESCRIPTION
**Pull request by Kurfursten**
alternative to #28837

Currently you can just floortile a jugg to death. It's comical, but it's only one stack of tiles. This would prevent that, and add the interesting feature that you can gauge whether a Jugg is bloodied yet. In return, crewmembers now gain the ability for a desperate counterattack with whatever is laying around once it is "broken".

image
_Codersprite overlay is a WIP._

🆑 
* tweak: While above 150 (60%) health, Juggernauts are now immune to damage from thrown objects with throwforce under 11, including floortiles. Below 150 health, Juggernauts are no longer immune to damage to either thrown objects or <11 force melee weapons.
* rscadd: Juggernauts now have a red "mantle" overlay when above 60% health.

### CODE REVIEW

**Comment by Blithering** [comment]
Can you make the mantle only appear when blocking damage? seems distracting otherwise.

**Comment by Kurfursten** [comment]
Yes, or a less intrusive mantle could be designed... I like seeing it BEFORE you attack so you know whether to engage or run away

**Comment by Eneocho** [comment]
So basically, the new tactic against a Jugg is to shoot them from a distance then floortiling them?

**Comment by Kurfursten** [comment]
More or less, at which point he also knows he's weaker and it encourages Juggs to retreat and heal at cultbase. I think this natural breakpoint for retreat could encourage more cerebral Jugg play. I also realize that is very optimistic.

**Comment by Allspice** [comment]
@Eneocho insofar as the current strategy is to flick tiles at juggers, sure
you used to see that occasionally before the ```shitter shuriken``` nerf, but that fell off a bit when their damage was halved or so

**Pull request closed without merging**
