### PR TITLE
Revert multiz

### LINKED ISSUE #30422: Waystation Holodeck Broken
I got it to run the first try on basketball court but after that all subsequent buttons did nothing, couldn't even get the basketball court back - it deleted the goals.

### PR DESCRIPTION
**Pull request by DamianX**
It's simply not ready. Currently breaks too many things and just jizzes all over the codebase.

Closes #30422

### CODE REVIEW

**Comment by ShiftyRail** [comment]
It's sad that I spent hours battling with float planes and, with the help of Exxion, finding a work-around (which completely negates the point of multiZ) only for multiZ to get axed soon after.

**Comment by DeityLink** [comment]
I suggest for multi-Z to be kept on a separate Branch from Bleeding-Edge so @kane-f can keep doing changes and fixing it up.

**Comment by DamianX** [comment]
In a fit of nerd rage I opened this PR because I noticed the multi-z PR made floor turfs `update_icon(1)` after they get `ChangeTurf`'d, but that's only one of the reasons behind #30422.
What are the other outstanding issues, american lights notwithstanding? It might be fine to keep it for now.

**Comment by DeityLink** [comment]
> 
> 
> In a fit of nerd rage I opened this PR because I noticed the multi-z PR made floor turfs `update_icon(1)` after they get `ChangeTurf`'d, but that's only one of the reasons behind #30422.
> What are the other outstanding issues, american lights notwithstanding? It might be fine to keep it for now.

Well I opened #30404 to fix #30390 and there was also #30381 which fixed radial menus being unclickable and Photobooths having layering issues but those are just the ones we found. Potentially there are more plane/vis_content related broken features. Unfortunately we can probably only find those by having players run into the issues and patch them ourselves.

**Comment by ghost** [comment]
> I suggest for multi-Z to be kept on a separate Branch from Bleeding-Edge so @kane-f can keep doing changes and fixing it up.

this i could work with

**Comment by DamianX** [comment]
I guess it's fine

**Pull request closed without merging**
