### PR TITLE
Bible bugfix and replaces various chaplain checks with religious leader checks, as well as some code cleanup

### PR DESCRIPTION
**Pull request by SirSkeleto**
[unatomic]
:-1:
:cl:
 * tweak: mirrors nullrod bugfix for bible smiting

### CODE REVIEW

**Comment by Kurfursten** [comment]
I don't think we should keep the assigned_role check at all. I don't think you should be able to use the Chaplain tools if you are not a religious leader. The only case where this makes a difference is if you signed up as Chaplain and you fucked up so badly you got disowned by your own God

**Comment by SirSkeleto** [comment]
aight

**Comment by Kurfursten** [comment]
compile ur code and fix compile errors

also needs 🆑 for the bugfix

**Comment by SirSkeleto** [comment]
> compile ur code and fix compile errors
> 
> also needs  for the bugfix

working on it

**Comment by SirSkeleto** [comment]
times three cause i aint a fag

**Comment by SirSkeleto** [comment]
tested on local serb, everything seems to work

**Comment by SirSkeleto** [comment]
please merge

**Pull request merged**
