### PR TITLE
Bandolier holding more than shotgun shells

### LINKED ISSUE #10909: feature request: bandolier holding different types of ammo
I am making this to get an reaction before I code it, it would be a very simple addition to add.

Right now all it holds are shotgun shells, what if we allowed it to hold all shell types of other guns? So you can walk around like a cowboy with a big iron on your belt and wrapped around with .357 shells.

Much more balance breaking but would be more useful is allowing it to hold magazines, that way you can hold speed loaders, or go tacticool and have assault rifle magazines on you.

Or for a more funny (also balance changing) use, allow matter carts to be put on it. For when you really need to build things.

What are your thoughts? Too over powered?

### PR DESCRIPTION
**Pull request by FudgePucker**
Sometimes you want to just be covered with ammo, but don't want to use a shotgun.

Now if you can put it into any gun (That one pressure based cannon excluded), you can put it in your bandolier.

Also matter carts because why not.

Also totally going to make a cowboy traitor bundle with a revolver, a hat, a coat, and a bandolier filled with speed loaders once this gets merged (if it does).

Also don't know how to edit the change log, we will cross that hurdle sometime later... not right now though. :^)

Edit: Closes #10909

### CODE REVIEW

**Comment by Exxion** [comment]
Come on, #10909 is your own issue. You should know it's there to make it autoclose.

**Comment by 9600bauds** [comment]
http://ss13.moe/wiki/index.php/Guide_to_Changelogs

**Comment by FudgePucker** [comment]
@Exxion My bad, fixing in a second. Its just putting "Closes #10909" in the PR right?

@9600bauds I will try.

**Comment by 9600bauds** [comment]
Literally just copypaste vgstation13\html\changelogs\example.yml then change the name and message

**Comment by 9600bauds** [comment]
Nice
Literally as I hit submit

**Comment by FudgePucker** [comment]
HOLY SHIT I MADE A CHANGE LOG.
WOO.
YEA.

**Comment by Exxion** [comment]
Why can you put the actual bullet projectile in it?
There's not really any harm in allowing it, but it's not possible to get one to put in there

Well it is with timestop, but that's buggy and not recommended at the moment

**Comment by FudgePucker** [comment]
Some of the guns are loaded with objects from that tree.

**Comment by Shadowmech88** [comment]
Which guns can you actually manually put a projectile into, though?

**Comment by FudgePucker** [comment]
I don't remember, maybe I misread.
Oh well whats the worst that can happen anyways?

**Comment by FudgePucker** [comment]
Can I get a NFD or some commentary on what's wrong please?

**Comment by 9600bauds** [comment]
'scool

**Comment by FudgePucker** [comment]
Woo

**Pull request merged**
