### PR TITLE
Removes NRV Horizon from the codebase

### PR DESCRIPTION
**Pull request by ghost**
It's not even in the mapvote and apparently it's universally loathed.

Naturally, this will require accompanying secret repo and travis changes.

### CODE REVIEW

**Comment by SonixApache** [comment]
turn it into an away mission instead

**Comment by Eneocho** [comment]
> turn it into an away mission instead

not a bad idea

**Comment by adacovsk** [comment]
I plan to turn it into an away mission at some point, but I'm pretty busy with things right now. In any case, I'll download a copy before it's gone

**Comment by GreatBigFailure** [comment]
I still don't understand the hatred for it. I'm not broken up to see it go mind you, but it felt fine to me.

**Comment by Eneocho** [comment]
It was less hatred and more an intense disapproval.
I haven't played Horizon in ages, but I distinctly remember that medical was very sinuous and awkward, engineering was forced to do shard, since snowflake code meant no scrungulos would work inside the ship and command was considerably larger than it should be for such a cramped map. Similar issues with island.

**Comment by Viciousaurus** [comment]
> turn it into an away mission instead

This.
We need less maps and more away missions.

**Comment by RedrobotAnnie** [comment]
i miss it

**Pull request merged**
