### PR TITLE
Adds a brain damage line

### PR DESCRIPTION
**Pull request by 18NakedSecOffsInTheShowersAtBoxBrig**
[tweak]

> [00:39:16]OOC: JohnathanSanta/JohnathanSanta (@8,81,2): i am based
> [01:13:51]SAY: Miss Stockings/JohnathanSanta (@@219,248,1) As Galactic Common : i am based, any objections?
> [01:55:14]SAY: Miss Stockings/JohnathanSanta/(Miss Stockings) (@273,231,1) Deadsay: drones, "i am based"
> [01:56:28]SAY: SINA-983/johnathansanta (@@291,233,1) : I am based
> [01:56:34]SAY: SINA-983/johnathansanta (@@293,233,1) : I am based
> [01:58:30]SAY: SINA-983/johnathansanta (@@318,252,1) : I am based
> [02:18:51]SAY: Unknown/JohnathanSanta (@@181,189,1) As Galactic Common : I am based
> [02:22:55]SAY: Blinko/JohnathanSanta (@@229,221,1) As Galactic Common : I am based
> [02:41:46]SAY: Blinko/JohnathanSanta/(Blinko) (@178,216,1) Deadsay: stammers, "I am based"

### CODE REVIEW

**Comment by gurfan** [comment]
I declare this PR based

**Comment by cloutcode** [comment]
based pr, any objections?

**Comment by SonixApache** [comment]
????

based on what?

**Comment by Irradiation** [comment]
Based on this retard.

**Comment by ShiftyRail** [comment]
Basé

**Comment by SonixApache** [comment]
should remove the one at line 46 and replace it with this tbh

**Comment by tuypo1** [comment]
Cringe

**Pull request merged**
