### PR TITLE
Mice keep the number in their name in deadchat

### PR DESCRIPTION
**Pull request by DamianX**
anonymity was a mistake
I think it used to work like this before deity changed mice for virology

### CODE REVIEW

**Comment by Armadingus** [comment]
Mouse hivemind posting is the worst thing to occur in deadsay and it is the one thing that keeps ruining discussion in deadsay.

**Comment by DeityLink** [comment]
Seems like I moved it to the parent New() by accident.

**Comment by Eneocho** [comment]
Not content with nerfing mice to oblivion, the c*der metaclub now wants to deanonymize the hive.

**Comment by gurfan** [comment]
nah

**Comment by DamianX** [comment]
You're all wrong

**Comment by BomberBro** [comment]
I'm right.

**Comment by ghost** [comment]
mouse hivemind is funny but not knowing who you're talking to is annoying

**Comment by Servalfang** [comment]
ban damian

**Comment by SonixApache** [comment]
[oversight]

**Comment by Armadingus** [comment]
Literally can't keep track of what's being said to whoever goes into the mouse crowd and it bothers me when people falseflag to take the piss out of me.

**Comment by ManopolisJones** [comment]
The anti-ratters will go to any lengths to take what's rightfully ours. I believe wholeheartedly that we should unite as one against such a VILE PR that will no doubt send shock waves through the obsgang community, no matter what they might claim to have over us.

**Comment by Exxion** [comment]
ok

**Comment by Eneocho** [comment]
Didn't know we were on TG where controversial PRs are merged to spite people.

**Pull request merged**
