### PR TITLE
Fixes #6896

### LINKED ISSUE #6896: Long Island Iced Tea involves no ice
[Honk] [OH GOD IT'S LOOSE]

EDIT: I have been informed it does not usually involve tea
BUT ICE

### PR DESCRIPTION
**Pull request by Probe1**
Adds ice requirement for making a long island iced tea.

Fixes https://github.com/d3athrow/vgstation13/issues/6896

### CODE REVIEW

**Comment by Probe1** [comment]
compiled, tested, works.  I'll update the wiki after its merged.

**Comment by Kurfursten** [comment]
:-1: No more balance PRs, this completely destroys the delicate balance of meta between virologists and the warden

**Comment by Probe1** [comment]
and the wikis updated.

**Pull request merged**
