### PR TITLE
Doubles plant glow mutation related chances

### PR DESCRIPTION
**Pull request by ghost**
Doubles the chance of generated (strange/exotic) seeds spawning with glow attribute, from 5% to 10%.

Doubles the chance of manifesting glow mutations.

Does not affect chances of other mutations.

We glow.

### CODE REVIEW

**Comment by 9600bauds** [comment]
To be honest I think the glow mutation chance should be even higher. The chance to even roll for a glow mutation is one in 11, and the chance for that roll to pass is usually 4% and rarely 8%.
I am not exaggerating when I say that in all my time as botanist I have only seen this happen once.

**Comment by TermedClepe** [comment]
I have never seen it happen. I think the mutation chances are written terribly. Especially the double/triple rolls needed for some.

**Comment by 9600bauds** [comment]
Sadly I haven't been using mutagen a lot lately. Building potency on a plant is much, MUCH harder than before, I've dumped entire beakers of mutagen into a plant without being able to get it up a single point and the results are usually not worth it.
I do think it could use a small rework, but we'd have to make a new topic on that.

**Comment by Zuhayr** [comment]
I would v. much appreciate input on mutations, Bay is borderline useless for this kind of play information, the mutation code is basically made up at random at this point and balancing it to be fun and interesting is on my list. Could you link the thread here if it is made?

**Pull request merged**
