### PR TITLE
Adds Plasma cabbages to hydroponics

### PR DESCRIPTION
**Pull request by joaomarcosh**
I tried making a material (silver, gold, diamond, etc) garden once and noticed that I had no way to obtain plasma so I decided to make a way.

~~EDIT: The plasbages should now consume plasma gas from the atmosphere.~~
Ignore that, I'm leaving this change for another PR once i can get it working properly.

cp2

:cl:
 * rscadd: Adds a new plant to hydroponics: Plasbages!
 * imageadd: Adds the sprite for the Plasbage.

### CODE REVIEW

**Comment by jwhitak** [comment]
I liked the plasmacanes better.

**Comment by SonixApache** [comment]
i'm more of a plastato type of guy personally

**Comment by joaomarcosh** [comment]
I just chose a random one because there was no majority

**Comment by Eneocho** [comment]
There IS a way to get plasma from botany without a dedicated seed, you can get plasma on random strange seeds from the hydroponics seeds crate. Don't get me wrong, I like this a lot, but there was a way to get plasma even before this.
Consider removing the plasma from the strange seeds if you add the plasma cabbages.

**Comment by Eneocho** [comment]
Also, could you change the name so it goes along with the naming standard for material plants? We have Golden Apples, Silver Pears and Diamond Carrots on one side and Rocknuts and Glowberries on the other. 
A name appealing to one of those two standards would be better in my opinion.

**Comment by joaomarcosh** [comment]
Do you think that naming it "Plasma Cabbage" would be better?

**Comment by Eneocho** [comment]
> Do you think that naming it "Plasma Cabbage" would be better?

Kinda, yeah. Since it matches the naming standard.
Also, please remove the plasma from exotic seeds. No point in having plasma in there too if you can get it normally via plasma cabbage.
This line: https://github.com/vgstation-coders/vgstation13/blob/d44e644ea6d164c65b081bd0785eeecfd073077b/code/modules/hydroponics/seed_datums.dm#L198

**Comment by Eneocho** [comment]
I just noticed the "they consume plasma" thing now. I'd remove it. 
All seeds on the seed vendor and their mutations can survive in a regular atmosphere (101kpa 20%O2 and 80% N2). 
If they need plasma, either they won't be planted since they'll need the plasma (and you don't want to plasmaflood botany for the umpteenth time) or that part will be overwritten by splicing nutrition via xenobotany, making it pointless.

**Comment by joaomarcosh** [comment]
> > Do you think that naming it "Plasma Cabbage" would be better?
> 
> Kinda, yeah. Since it matches the naming standard. Also, please remove the plasma from exotic seeds. No point in having plasma in there too if you can get it normally via plasma cabbage. This line:
> 
> https://github.com/vgstation-coders/vgstation13/blob/d44e644ea6d164c65b081bd0785eeecfd073077b/code/modules/hydroponics/seed_datums.dm#L198

I dont think its necessary to remove it, that list has chemicals that can already be obtained through normal botany like blood, sugar and radium so i dont see the problem in leaving plasma there.

**Comment by Eneocho** [comment]
The only reason plasma was on that list was because it was otherwise inaccessible via botany, having it in both places is redundant. Blood, Sugar and Radium do have their place in botanywork and/or cooking. Plasma is an outlier.
Also, removing plasma would increase the odds for the other chems which I like since I've been cucked outta great splices too many times due to the perfect spliceplant having plasma as well.

**Comment by joaomarcosh** [comment]
> I just noticed the "they consume plasma" thing now. I'd remove it. All seeds on the seed vendor and their mutations can survive in a regular atmosphere (101kpa 20%O2 and 80% N2). If they need plasma, either they won't be planted since they'll need the plasma (and you don't want to plasmaflood botany for the umpteenth time) or that part will be overwritten by splicing nutrition via xenobotany, making it pointless.

Ahh thats my mistake, i thought that variable made it so they consumed the gas but it wasnt necessary for the plants survival.
im thinking about making it be able to consume plasma but not need it, but if it does consume plasma it increases the amount of plasma you get from grinding it

**Comment by Eneocho** [comment]
>im thinking about making it be able to consume plasma but not need it, but if it does consume plasma it increases the amount of plasma you get from grinding it

That sounds cool as hell but would probably require a whole restructuring of hydroponic code.

**Comment by joaomarcosh** [comment]
I've changed the name to Plasma Cabbage and removed the need for plasma in the atmosphere and removed plasma from the list of possible chemicals for random seeds.
For now I think this pull request is fine and will leave the plasma consuming change for another pr.

**Comment by Eneocho** [comment]
Very based. I will update the wiki when it gets merged.

**Comment by irish09slasher** [comment]
> I just noticed the "they consume plasma" thing now. I'd remove it. All seeds on the seed vendor and their mutations can survive in a regular atmosphere (101kpa 20%O2 and 80% N2). If they need plasma, either they won't be planted since they'll need the plasma (and you don't want to plasmaflood botany for the umpteenth time) or that part will be overwritten by splicing nutrition via xenobotany, making it pointless.

Are you sure this is the case? Going through other references to consume_gasses in the repo, as well as in-game knowledge, suggests to me that this only sets the plant to consume certain gasses while not actually needing them to live.

**Comment by joaomarcosh** [comment]
> > I just noticed the "they consume plasma" thing now. I'd remove it. All seeds on the seed vendor and their mutations can survive in a regular atmosphere (101kpa 20%O2 and 80% N2). If they need plasma, either they won't be planted since they'll need the plasma (and you don't want to plasmaflood botany for the umpteenth time) or that part will be overwritten by splicing nutrition via xenobotany, making it pointless.
> 
> Are you sure this is the case? Going through other references to consume_gasses in the repo, as well as in-game knowledge, suggests to me that this only sets the plant to consume certain gasses while not actually needing them to live.

line 134 specifically

https://github.com/vgstation-coders/vgstation13/blob/496b8cae926632865462434645ea304e95d5de12/code/modules/hydroponics/hydro_tray_process.dm#L123-L136

**Comment by irish09slasher** [comment]
> > > I just noticed the "they consume plasma" thing now. I'd remove it. All seeds on the seed vendor and their mutations can survive in a regular atmosphere (101kpa 20%O2 and 80% N2). If they need plasma, either they won't be planted since they'll need the plasma (and you don't want to plasmaflood botany for the umpteenth time) or that part will be overwritten by splicing nutrition via xenobotany, making it pointless.
> > 
> > 
> > Are you sure this is the case? Going through other references to consume_gasses in the repo, as well as in-game knowledge, suggests to me that this only sets the plant to consume certain gasses while not actually needing them to live.
> 
> line 134 specifically
> 
> https://github.com/vgstation-coders/vgstation13/blob/496b8cae926632865462434645ea304e95d5de12/code/modules/hydroponics/hydro_tray_process.dm#L123-L136

Wow, thanks for the response. Was not under the impression that it worked that way.

**Pull request merged**
