### PR TITLE
Audio Changes

### PR DESCRIPTION
**Pull request by kilkun**
Traitor.dm: Plays syndicate intro for traitors

Robot.dm: Informs cyborgs being emagged about their new priorities.

Narsie.dm: Spooky space wind when Nar-Sie is summoned

This time with 100% less mess per PR. Reversion free!

Adds in a new gun, the Single Action revolver. Requires user to pull back the hammer before firing. Uses .38 and .357.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Would stop people not noticing they are a traitor.

**Comment by ririchiyo** [comment]
Relative paths are a no-go.

**Comment by Duny-** [comment]
I dub you Kilnocompilekun, son of Heredth.

**Comment by kilkun** [comment]
Compiles fine for me, I don't know what the issue is.

**Comment by ComicIronic** [comment]
You haven't pushed the sounds, so the remote build is throwing a path error.

**Comment by kilkun** [comment]
They exist in the base branch, seems kind of silly to include them in the PR when it doesn't change anything.

**Comment by ComicIronic** [comment]
Then the issue is the leading slash on all of them.

**Comment by kilkun** [comment]
Nice.

**Comment by ComicIronic** [comment]
This PR will hang on the revolver, so you might want to remove it if you aren't going to code it soon.

**Comment by kilkun** [comment]
It's removed.

**Comment by ComicIronic** [comment]
Rename it, and you're golden.

**Comment by kilkun** [comment]
k

**Comment by d3athrow** [comment]
Next time, keep Pull Requests atomic, one feature set per PR.

**Pull request merged**
