### PR TITLE
buttbots fart when they parrot now

### PR DESCRIPTION
**Pull request by gbasood**
:cl:
 - tweak: Buttbots now actually make fart noises when they parrot someone they hear.

I guess before they only farted on click.

### CODE REVIEW

**Comment by AI-Is-Rogue** [comment]
Would this make finding the buttbots easier?

**Comment by Hugh-G-Rection** [comment]
Not all heroes wear butts.

**Comment by Megamaw** [comment]
@AI-is-rogue i think that's the idea, yeah.

**Comment by gbasood** [comment]
It's part of the idea, but I didn't try to make the area of their fart do anything special.
They make the same amount of noise as if you click on them. I didn't try to do anything like fart through walls, as was suggested by others.

**Comment by Ephx1** [comment]
I much prefer this to outright removing them or their ability to talk over the radio.

**Comment by ghost** [comment]
No, it wouldn't because it still only helps find the buttbots of the laziest shitters who don't even bother to spend any effort to hide them. They need to be logged so non-antags stop fucking griefing as well as have printable gps to find the fuckers.

**Comment by Mothblocks** [comment]
from very short testing while working on another buttbot change, i think you accidentally ended up killing the buttbot

no matter what i say next to it, it only says "butt" as if it were clicked.

**Pull request merged**
