### PR TITLE
Cryo improvements:

### LINKED ISSUE #25728: Make cryo tubes have a visual indicator that they're out of mix.
[featurerequest] [sprites]

I dunno, something like having the health bar flash yellow.

### PR DESCRIPTION
**Pull request by PJB3005**
Now shows occupant/cell temperatures in both celcius AND kelvin.
Previous cell was kelvin and occupant was celcius (???)

Has a yellow flashing overlay for when there's no cryo mix.

Fixes #25728

image

:cl:
 * rscadd: Cryo tubes now have a flashing yellow overlay if they're out of mix.
 * tweak: Cryo tubes now display all temperatures in both Celcius and Kelvin.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I think PR should wait to be merged until after the "revert nucryo" PR gets concluded otherwise they will conflict. In the mean time I like this PR

**Comment by Kammerjunk** [comment]
give me uhh player-configurable rules with zero to one rule per reagent in the mix
each rule controls how much to inject and at which threshold to inject it

consider this feature request your first and last warning

**Comment by PrimeDSS13** [comment]
What Barry said, neat PR though.

**Comment by PJB3005** [comment]
Yeah but if you merge this after the revert it might as well not matter because you'll never run out of mix

**Comment by nuklearcellphoneg** [comment]
where is Fahrenheit

**Comment by PJB3005** [comment]
Weird way to pronounce Rankine.

**Pull request merged**
