### PR TITLE
Baseball bat updates

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][tweak]

## What this does
- [x] allows baseball bats to hit away items in the other hand in throw mode
- [x] allows baseball bats to hit away items on the floor in throw mode
- [x] cricket bat variant (cosmetic)
- [x] hurley variant (allows balancing tiny items on it while running)
- [x] hockey stick variant (crafted with plastic instead, only hits items on the floor, with doubled throw speed on slippery floors)
- [x] spiked bats are no longer totally useless at hitting or blocking but their chance and ability is greatly reduced
- [x] wirecutters can now remove the nail from spiked bats

## Why it's good
more fun uses for this item

## Changelog
:cl:
 * rscadd: Baseball bats can now hit away items in the other user's hand or the ground.
 * rscadd: Baseball bats can now have their nail removed with wirecutters.
 * rscadd: Spiked bats now have a very small chance to hit anything instead of none, with limited effect.
 * rscadd: Adds craftable cricket bats, hurleys and hockey sticks. Cricket bats act the same, hurleys can balance an item on them and hockey sticks cannot be spiked, block items or hit items in hand but are more exceptional at hitting items on the floor, especially on slippery turfs.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
>allows baseball bats to hit away items in the other hand in throw mode

I always kind of thought this was already a feature but I just didn't know how to use it. Nice.
It might be cool if it could work with breakable items, so you could for example bat a beaker into the air and send shards flying at people. There's already a `throwparams` datum which is kind of like a proto-notion of impulse. It lets you shoot breakable objects apart and have the fragments also get propelled. Maybe something could work there.

Edit: although *not* doing this would allow for some stuff, like batting a beaker of pacid at someone and then having it shatter when it hits them and splatter them.

> hockey

Hoverskates on the holodeck ice rink, or physical skates on physically icy floors... hmm..

**Comment by SECBATON-GRIFFON** [comment]
> Hoverskates on the holodeck ice rink, or physical skates on physically icy floors... hmm..

for another PR maybe, my idea is that they only work on slippery floors (increasing speed a bit too) but on normal floors theyre clunky to use and you trip a lot with them.

**Comment by Eneocho** [comment]
>cricket balls aren't made of cricket

why

**Comment by NigglyWiggly** [comment]
Shouldn’t a crowbar also be able to remove nails from a nailbat?

**Comment by Eneocho** [comment]
> Shouldn’t a crowbar also be able to remove nails from a nailbat?

Consider the following: https://www.youtube.com/watch?v=CsuXeqHn_rk

**Comment by SECBATON-GRIFFON** [comment]
\>it's an icon conflict
JUST

**Comment by Hinaichigo** [comment]
Maybe it's best to wait for the final review before fixing icon conflicts, so that it doesn't have to keep being fixed hopefully. That's what I'm planning to do from now on.

**Comment by SECBATON-GRIFFON** [comment]
honestly i hate in-hand spriting so i'll just remake this PR with a more limited scope sometime

**Comment by Eneocho** [comment]
I still want the cricket bats to be craftable with crickets.

**Comment by SECBATON-GRIFFON** [comment]
eneocho that still doesn't make any sense and the entire idea is just unfunny

**Comment by Eneocho** [comment]
It doesn't have to make sense and it is funny.

**Pull request closed without merging**
