### PR TITLE
Nukedisk fixes

### LINKED ISSUE #1675: Firebird riders can leave station Z-level with nuke disc
Title says it all.

Reproducing
Acquire Firebird
Acquire Disk
Fuck off into space.

### LINKED ISSUE #2631: Nuke disk is able to be moved off of z1 via mining shuttle
happened during a nuke round

### PR DESCRIPTION
**Pull request by clusterfack**
Fixes #2631, the nuke disk can no longer be taken off by either shuttle to the asteroid
Fixes #1675, people riding vehicles can no longer take the nukedisc off the zlevel with them

### CODE REVIEW

**Comment by d3athrow** [comment]
Changelog

**Comment by clusterfack** [comment]
Done

**Comment by ComicIronic** [comment]
If you're going to update the mining computer, please bring it in line with the other machinery construction code.
Move the code called on being smacked by an emag into the machine's emag() proc, and remove the screwdriver code since it's handled already.
Then you can set the machine_flags to EMAGGABLE | SCREWTOGGLE.

**Comment by clusterfack** [comment]
Alright I'll make those changes

**Comment by clusterfack** [comment]
Alright all fixes have been made to both shuttle consoles

**Pull request merged**
