### PR TITLE
Map changes: Parameds given Mining Access, Hydroponics backroom expanded

### PR DESCRIPTION
**Pull request by Rei1226**
also what did i do to this changelog file help

### CODE REVIEW

**Comment by FudgePucker** [comment]
Oh boy I can't wait for more powergaming parameds to loot mining base.
Awesome.

**Comment by NigglyWiggly** [comment]
>Parameds given Mining Access

For what purpose

**Comment by Exxion** [comment]
Presumably so they can rescue the inevitably dead miners

**Comment by FudgePucker** [comment]
Yea the paramed is toataly going to go use his access to go rescue the miner, who died from A:vampire/ling or B: Horrible monsters, instead of looting everything not nailed down.

You know whats better than a hardsuit? TWO HARDSUITS, FIVE HARDSUITS, ALL THE HARDSUITS, IF I WASN'T TO TAKE ONE OF THEM, WHY DO I HAVE ACCESS?

**Comment by Rei1226** [comment]
What reason would a paramedic have to loot mining?

The fuck is even in mining that they would want to loot?

They already have a hardsuit in their office.

**Comment by Rei1226** [comment]
legit fuck github i have never had this many issues with a program ever in my entire life then I have with this shit.

i can't figure out why the fuck it keeps adding ten trillion deletions and additions, I cleaned and prepared map like 8 million times, reverted and did it all over, still keeps doing this shit.

**Comment by FudgePucker** [comment]
>What reason would a paramedic have to loot mining?

Parameds are almost as bad as assistants with their shittery and looting most of the time.

**Comment by Rei1226** [comment]
Said no one ever

**Comment by FudgePucker** [comment]
They loot IDs and corpses for yellow gloves, every single round.
I saw one of them on one occasion rush to aux charging station and shock himself on the crew monitor.
I lost as an antag because I was going to wait to get to morgue before looting a dead engineers ID, but the paramedic don't give a shit, just fucking nab that ID for yellow gloves.
Every single fucking time I have had to interact with a paramedic they are powergaming shitfaces.

**Comment by NigglyWiggly** [comment]
The crew monitoring computer now shows sensors on all Z-levels, right? 
That's fucking stupid, if it does.
Regardless of if they can see the miners on the computer, it's always been a sort of buddy system kind of deal, you check your GPS every once and a while, and if your fellow miner's been sitting in the same spot for the last 10 minutes, you haul ass over there and get him.

And yeah parameds will loot whatever they can find from mining.

**Comment by Probe1** [comment]
It does (and pomf was the one that changed it so.. ._.)

**Comment by ririchiyo** [comment]
Please rebase instead of merge. Make sure you prepare the map prior to making any changes as in make sure dream maker is closed and everything when you're trying to discard your changes or revert to an earlier stage.

**Comment by AutismSpider** [comment]
No they have one fucking job and its to look at the crew monitoring computer and they can't even do this.

**Comment by TermedClepe** [comment]
No screenshot of map changes?

Why are you clumping unrelated PRs together? Hydroponics has nothing to do with paramedics, separate them.

**Comment by Probe1** [comment]
well, they have one job and it is to find, secure, and transport wounded and sick.  oftentimes they instead find, secuire, and transport sick or dead peoples things but there are some very good paramedics.

honestly they don't need mining access in the least.  Allen . bestCMO.

**Comment by FudgePucker** [comment]
No really, parameds are ill equipped for rescuing shaft miners.
The only thing that a paramed can do in one case of a shaft miner dying is if the shaft miner is a newb and got killed by a gibbinite shard.
A paramed would have a very difficult time finding the body anyways because of how maze like the asteroid is.
A better solution would be just to tell science that the miner died and needed to be retrieved. Science has access though their outpost to go retrieve it and can arm themselves for mobs, or just use telescience if the miner had a GPS tagged and on him. Science would go out of the way to save a miner that brought them materiels, a paramed has no reason to.
And to restate my point of parameds looting everything not nailed down, everyone in this post has said it, not nobody ever.

**Comment by FudgePucker** [comment]
Also, giving mining access shouldnt  be a map change, you would just be changing id access.
Also how far into cargo should they get to get to mining area? Should they have cargo access or have to go though maintenance?

**Comment by ComicIronic** [comment]
RIP this PR

**Pull request closed without merging**
