### PR TITLE
removes ninja

### PR DESCRIPTION
**Pull request by CyberpunkBenShapiro**
ninja is not fun
https://www.youtube.com/watch?v=u9Pwlva8wUY
I will code a fun mid round antag to replace this
🆑
- rscdel: removes ninja

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Please back up your argument with facts and logic

**Comment by PaulRitter** [comment]
i dont really care about this, but if you want to remove it, at least make some arguments

**Comment by DDihanov** [comment]
Are you memeing dude?

**Comment by ghost** [comment]
It's almost as if making reactionary meme PRs encourages other people to make more reactionary meme PRs thinking they are welcomed.

This is what you're asking for each time you make a joke PR.

**Comment by brndd** [comment]
It doesn't matter if a PR is \~reactionary\~ or whatever meme bogeyman moniker you want to slap to it if it backs up its stance with actual arguments, which this PR doesn't.

**Comment by PaulRitter** [comment]
>It doesn't matter if a PR is \~reactionary\~ or whatever meme bogeyman moniker you want to slap to it if it backs up its stance with actual arguments, which this PR doesn't.

+1, close this

**Comment by SonixApache** [comment]
@codeungabunga stop being such a snide fuck

**Comment by iFlashYou** [comment]
First code and PR your !!FUN!! midround antag and then remove another one

**Comment by Arthurdentist** [comment]
Okay, this is epic

**Comment by Intigracy** [comment]
Bring back weeb ree

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
The last time we added a hastily thrown together !!FUN!! antag to replace a removal, we got ninja

**Comment by jknpj** [comment]
Time to bring ling back

**Comment by agentofzog2** [comment]
Problem with ninja, besides being hard countered by the janicart, is how Dynamic fucking loves to spawn ninja after ninja after ninja, of whom maybe one will live long enough to find a disguise after which we're treated to silent shuriken murderbone until they slip on a puddle.

If we had more antags (like LING) this wouldn't be such a problem.
Maybe one day I'll post ninjaideasguy.txt somewhere.

**Comment by ghost** [comment]
Ling was unironically a good gamemode that people disliked because it stole their statics.

**Comment by IAGFPRMF** [comment]
I wouldn't care if ninja got removed. It's probably the worst antag idea (technically a remaster of a broken antag) that spawned out of any server I've seen. The fun you get from just going ham and murdering everyone with machine gun shurikens (or being murdered by it) goes out the window very quickly.

**Comment by ShiftyRail** [comment]
Conflicts + doesn't seem to be happening in that fashion, as much as ninja sucks as a gamemode

**Pull request closed without merging**
