### PR TITLE
chuck

### PR DESCRIPTION
**Pull request by ShiftyRail**
chuck
(formerly sneed)

### CODE REVIEW

**Comment by DrSnips** [comment]
More like chucks (this into the trash)

**Comment by SonixApache** [comment]
where's the 12:05 pomf close speedrun

**Comment by DrSnips** [comment]
If only I was a collaborator. I'd compete for that speedrun. *Wink wink nudge nudge collabs*

**Comment by boy2mantwicethefam** [comment]
formerly chuck

**Comment by Kharkov72** [comment]
>no "unable to reproduce"

sneed confirmed chad

**Comment by ShiftyRail** [comment]
He receives no monetary compensation

**Pull request closed without merging**
