### PR TITLE
Reverts Box NuMechanics

### PR DESCRIPTION
**Pull request by jknpj**
http://ss13.moe/index.php/poll/173

:man_shrugging:

:cl:
 * rscdel: Box mechanics are back to their old location.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Needs pic

**Comment by jknpj** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE #20191 but backwards

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Whoah,.......

**Comment by SonixApache** [comment]
rip, i guess
parts of the experiment were well recieved (toxins move, toxins storage, sci break room, vacant office), some weren't
shame, i was pretty happy with my work

**Comment by Caboozles** [comment]
Can we take the time to remove the glubbs from Mechanics while we're doing this? Just place the locker within Tcomms storage, or set an extra locker into engineering, making them less capable of spare rushing.

**Pull request closed without merging**
