### PR TITLE
The plasma sting

### PR DESCRIPTION
**Pull request by iFlashYou**
Adds a new sting for the changelings that lets them deal with silicons. After they sting a silicon it will gib after some seconds. It gibs the body but the MMI will be dropped on the floor, so there is still a chance to get back into your metalbody.
Works on borgs, AIs and MoMMis but not on carbons.

Added this littel sting so changelings would actually have some tool to fight the silicons and that even a borg has to think 3 times before he goes to catch the ling valids.

:cl:
 * rscadd: Adds the plasma sting for changelings.

### CODE REVIEW

**Comment by DrSnips** [comment]
If cyanide sting was so great why isn't there cyanide sting 2: silicon boogaloo?

**Comment by DrSnips** [comment]
Jokes aside. This is silicon deathsting so bump it up to the same cost as deathsting.

**Comment by ShiftyRail** [comment]
Lings's memesting is very strong and this is just deathsting II: silicon edition
I think than silicons are, more or less, designed a counter to the lings for that reason.
I'd rather have it an EMP Sting (with a lower cost) so that you can evade borgos rather than just instant death.

It would also be good to give feedback to the cyborg. Carbons get the "Oh shit muh chest is tightening" and jitter a lot ; your PR as in would simply trigger a kill switch after a random duration.

A message like "RUNTIME ERROR: Major system overload in 0xFBA67, restart in --" and a few sparks would be cool as feedback.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Carbons also get fucking instasleep'd so I don't know what kinda feedback that is

**Comment by ShiftyRail** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE Feedback for outside observers

**Comment by SonixApache** [comment]
dude just make technological camouflage also work on borgs

**Comment by Kurfursten** [comment]
Hear me out, what if instead of giving the ling more uninteresting instant death powers, we just made silicons less obscenely strong in every game mode. Shift points out that borgos seem to be the counter to lings... but they also seem to be the counter to nearly every antag. They also get glare immunity, purely for example. If we had stats on how few wizards took EMP we could demonstrate that they are excellent wizzyman counters too.

Many rounds revolve around silicons because of their general powerlevel - high health and across the board immunities.

**Comment by DrSnips** [comment]
Silicon are a "you're either with them or you're against them" and you have the advantage if you're with them due to numbers and if there's an AI to provide info and as they say knowledge is power.
On a side note malf rounds seem to say otherwise about silicons being op with a win/loss rate of 16 wins to 36 loss based on the serb public stats.

**Comment by Chazach** [comment]
@Kurfursten after all this time coding people still dont get how the github works
an overall borg nerf wont be passed by a long shot
but this can scrape by with the "antags R supposed 2 be strong!!!" reasoning people use

**Comment by ShiftyRail** [comment]
@Chazach I don't see any recent serious nerf borgs proposal (aside maybe from the Code Blue PR).

**Comment by SonixApache** [comment]
Or how about this; instead of gibbing the borg, you just blow up its cell?

**Comment by ShiftyRail** [comment]
A rapid drain of the cell culminating in its explosion would be a good alternative.

**Comment by Blithering** [comment]
Or just rapid drain resulting in a borg that has to slowly and blindly head to a charger. Explosions are neat and all, but not very sneaky

**Comment by Caboozles** [comment]
If it costs as much as deathsting IE difficult to acquire both deathsting and this, then I’m loosely okay with it. I want the explosive side entirely because it ISN’T subtle. Stealth is the worst aspect of Ling for anyone not playing the ling.

**Comment by aceedex** [comment]
ei nath!

**Comment by jakmak6** [comment]
All six of me approve

**Comment by iFlashYou** [comment]
Plasma sting has now the same costs as the deathsting and added some metatext for the silicons

**Comment by SonixApache** [comment]
>It gibs the body but the MMI will be dropped on the floor, so there is still a chance to get back into your metalbody.

Yeah, because a ling would leave that MMI on the floor and not immediately destroy/space it.

>Works on borgs, AIs

w e w


Giving lings even MORE ways to permanently remove people from the round is a really bad approach towards fixing the issues with the antag.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Nice try, borgs are not people

**Comment by SonixApache** [comment]
silicon players are, contrary to popular belief, actually people

**Comment by ghost** [comment]
Adding more one-click player removal buttons to the server with a chronic issue with having the most boring/toxic combat due to everything being stun/kill based.  It amazes me how you seek out things that set /vg/ station lightyears behind almost every other server and you try to nurture that cancerous aspect.

Not ways to get more players involved with the round, not combat that is more involved and interesting.  No, you want other people playing in the round to die immediately and to stop playing.  That is the game you want.

**Comment by iFlashYou** [comment]
My intention with this pr was to put silicons on the same level as carbons when it comes to fight a late-game ling. Why should only carbons suffer the instant death while silicons get away with most of things and are immune to most antag tools. Afaik is ling the only antag that has no tools to let him quickly escape or deal directly with silicons.
Even if this pr would get merged it would probably change nothing, we would probably not even see this sting really used because it costs the same as the deathsting and that means a ling would had to get far ahead into the round without being caught and then even he could only use either the deathsting or plasma sting at the same time because of their high chem cost.

**Comment by ghost** [comment]
Have you considered that the issue in itself is that instant death isn't fun, and that rather than adding more of what makes the game unfun, death sting should be removed instead?

> Even if this pr would get merged it would probably change nothing, we would probably not even see this sting really used because it costs the same as the deathsting and that means a ling would had to get far ahead into the round without being caught and then even he could only use either the deathsting or plasma sting at the same time because of their high chem cost.

You admit here that it would do nothing.  Making broken antag abilities and just gating it behind goals that require you to take half the player pop out of the round, only to make yourself better at removing the remaining player pop, is the shittiest game design imaginable.

Do you know why vamp was (and still is) a shitshow for so many years?  /vg/ has the absolute shittiest coders that make reactionary balance PRs that are based on feelings as opposed to actually addressing the issue at hand.  Back then they saw vamp was broken and unfun so as opposed to actually fixing anything wrong with the gamemode, its progression was halted by adding a blood cost to hypno.  Nothing worked, abilities still didn't work as intended, nothing was tested (#7633 was the PR in question, and I shit you not, this PR was the result of dying in a vampire round the same day it was put up, logs don't lie).  They saw this broken-ass unfun lategame and said "wow, this stuff sucks!  Let's not actually address any of that and just make it shittier to start as a vamp!"

Now here you are on the other end of the coin, adding unfun, broken end-game with the reasoning that progression to that point is hard so it is ok.  This PR is a contribution to the same cycle of short-sighted, shitty game design.  Get the idea out of your broken brain that fun gameplay revolves around making as many people as possible unable to play the game.

And none of this is even touching how changeling doesn't even need this and it is already the single strongest antag type with a plethora of ways to deal with silicons and play around them.  That said, consider YOUR chloral-is-the-solution playstyle to be the issue and stop trying to remold the game to conform to one-click player removal being the solution to everything.

**Comment by ShiftyRail** [comment]
http://ss13.moe/index.php/poll/172

A poll for this (please ignore the other one. I blame myself)

**Comment by Boxe** [comment]
dumb

**Comment by Killette2** [comment]
This is stupid. Breaking a cyborgs components and massively fucking them up while disabling them for a good amount of time would be a better alternative than straight up exploding them

Say such a process would be shooting some ling goop inside which would later expand and break many things, like a human eating a monkey cube

**Comment by Reviire** [comment]
What if instead we just made ling a less shitty game mode? Why must they get Deathsting silicon edition? Deathsting is already anti-fun enough. Their entire design was just someone brainstorming the least fun thing possible for everyone involved, please don't add to it.

Ling needs to be reworked entirely tbh.

**Comment by Hoshi-chan** [comment]
What the FUCK?

**Comment by jknpj** [comment]
http://ss13.moe/index.php/poll/172 is over, guess we can just

**Pull request closed without merging**
