### PR TITLE
The RUST's EM Field is now anchored and not dense

### LINKED ISSUE #26978: Dragable Elektromagnetic fields
(WEB REPORT BY: davidblanc5 REMOTE: 206.221.180.138:7777)
# Revision
cbfe7e4e47fcbc5ba777dfdd7d0bc1d94ddeb64a

# Description
you can drag the EM field of the Rust
it does nothing expect you can drag the animation around and it will shrink and grow as the field increases
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #26978

:cl:
* bugfix: The RUST's EM Field is now anchored and no longer dense. (davidblanc5)

### CODE REVIEW

**Comment by gurfan** [comment]
The EM field used to be dense too, is that still an issue?

**Comment by DeityLink** [comment]
> 
> 
> The EM field used to be dense too, is that still an issue?

It most certainly was

**Comment by Eneocho** [comment]
Is this the beginning of the TLC that R-UST so desperately needs?

**Comment by strawberrytan** [comment]
Noooooooo I can't grab the EM field with telekinesis now!!!

**Pull request merged**
