### PR TITLE
add tech origin for goonecode

### PR DESCRIPTION
**Pull request by nervere**
## What this does
title

## Why it's good
cool reward for retrieving goonecode if no admins are online

## Changelog

:cl:
 * rscadd: Goonecode now has a tech origin and can be put in the destructive analyzer.

### CODE REVIEW

**Comment by Eneocho** [comment]
A bit underwhelming. Where is combat, engineering, electromagnetic, nanotrasen or anomaly?
Only bluespace = 5, not 10? Syndicate = 3, not 8? 
This is the goonecode, it should max literally all tech to the maximum possible level (that still has stuff).

**Comment by Kurfursten** [comment]
Add mech_scan_fail because this will allow mechanics to scan it, goonecode shouldn't be something you can fabricate

**Comment by Eneocho** [comment]
it already has mechscanfail
 `mech_flags = MECH_SCAN_FAIL //It's the holy grail!`

**Comment by RealestEstate** [comment]
It should give you a funny message about being closed source when the scanning fails.

**Comment by Kurfursten** [comment]
> A bit underwhelming. Where is combat, engineering, electromagnetic, nanotrasen or anomaly? Only bluespace = 5, not 10? Syndicate = 3, not 8? This is the goonecode, it should max literally all tech to the maximum possible level (that still has stuff).

Actually, I thought this over and I think goonecode should be a tech disk with a new tech level called Goone, like how the NT disk works. What should Goone tech unlock? No idea, but it should definitely require sheets of every goone ore we have in our code, thus making it nearly impossible to print anything.

**Comment by jwhitak** [comment]
I vaguely recall us removing the goone ores... did we?

EDIT: We didn't. You can have all the Erebite, Pharosium, and Syreline you like!

**Comment by Eneocho** [comment]
Goonetech just flatout gives you admin (except ban) flags. Ascend to godhood.

**Comment by DrSnips** [comment]
you can't use the meme sheets and it just gives you a mix of other existing materials iirc

**Comment by Exxion** [comment]
It should give negative levels in programming

**Comment by nervere** [comment]
> A bit underwhelming. Where is combat, engineering, electromagnetic, nanotrasen or anomaly? Only bluespace = 5, not 10? Syndicate = 3, not 8? This is the goonecode, it should max literally all tech to the maximum possible level (that still has stuff).

I disagree. The goonecode satellite spawn isn't uncommon and is pretty easy to cheese. I don't want that to become the meta. Materials 10 is incentive enough. I will up the rest of the techs slightly, though, and include Nanotrasen tech.

> It should give you a funny message about being closed source when the scanning fails.

I have added a special device analyser fail message for this.

> Actually, I thought this over and I think goonecode should be a tech disk with a new tech level called Goone, like how the NT disk works. What should Goone tech unlock? No idea, but it should definitely require sheets of every goone ore we have in our code, thus making it nearly impossible to print anything.

This wouldn't be hard to add but I don't want to go through the hassle without it having a purpose.

> It should give negative levels in programming

Done. It now has -10 programming tech origin. I added an exception to how tech updates to make it actually remove levels, and then removed it because I foresaw people being extremely cringe with that feature in the future. It's just fluff now.

**Pull request merged**
