### PR TITLE
Bagel Armory Shutters/Expansion

### PR DESCRIPTION
**Pull request by BurntDevil**
Thread request
This adds 2 sets of shutters to Bagel armory similar to Deff's. It also gives slight walking room inside the armory itself so officers arent stumbling into each other to suit up and to store the warden's toys.
Before
<a href="https://imgur.com/TEZdnrj"></a>
After
<a href="https://imgur.com/LMSJzRR"></a>

:cl:
 * tweak: Added deff style shutters the Bagel Armory. Expanded space enough to allow proper foot traffic.

### CODE REVIEW

**Comment by Riekland** [comment]
I'd say that the pure black tiles are a bit of an eyesore but I'm not about to complain over being able to actually move inside the armoury

**Comment by TurboGay** [comment]
I'd say the buttons should be moved to the interior as to still allow the armory to be locked down by Asimov silicons trying to prevent probable harm.

**Comment by Probe1** [comment]
@BurntDevil address or refute feedback

**Comment by BurntDevil** [comment]
I didnt see a need to change the paint scheme from what bagel brig already was.
I could move the buttons, if necessary, but Im not sure about the gameplay implications of the buttons being inaccessible from outside the door. If people want the buttons inside, its a simple task. I'd rather that decision not be mine.

**Comment by Probe1** [comment]
Dirty edit.

**Comment by Probe1** [comment]
Bad windows and bad firelock otherwise good for merge.  The entire fucking thing should be thrown in the garbage no offense to you.  What an unlovable brig.  It's too big where it doesn't need to be and too small where it needs to be bigger.  I feel like my heads going to explode looking at it.

dreamseeker_2018-04-11_22-57-03

**Pull request merged**
