### PR TITLE
Latejoin roles may now increase the threat.

### PR DESCRIPTION
**Pull request by ShiftyRail**
It's still not a tensioner but at least it's something.
Latejoining as a security role, or as a captain/HoP, _**that doesn't get autotraitored**_ now raises the max threat a little.
It's static and doesn't depends on the current threat. Could do something more context-sensitive if needed (doesn't high too much threat if there are many living antags, if the threat is already high enough...)

:cl:
- tweak: Latejoining as a captain or a security role will increase threat a little.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
'Captain [so and so] has arrived on the station.'

"Fuck. Call it!"

**Comment by ShiftyRail** [comment]
I don't understand
If there is low threat but a security force comes in, it's only natural that threat raises to give them some challenges
It's not like the effect will be instant, rulesets picking is independent from latejoining

**Comment by KingofHONK** [comment]
Make femsec worth double the normal threat increase.

**Comment by MadmanMartian** [comment]
I wasn't saying the method is bad, I was just taking the mickey.

Could increase the threat by minimal amounts from regular joes joining, as well.

Like, a random 1 to 3 increase in threat.

**Comment by Arthurdentist** [comment]
add "clown = 10" as well

**Review by MadmanMartian — APPROVED** [review]
If there isn't one, I'd say make a helper for modifying threat level

**Comment by DeityLink** [comment]
Wait shit, I liked the idea on paper but didn't take time to check the code.

@ShiftyRail you madman you're increasing the Threat AND the Threat Level!?

This is the reality we live in now:
image


Raising Threat alone was enough, it allows more antags to spawn overall, but raising Threat Level AS WELL is just raising the heat too much.

**Pull request merged**
