### PR TITLE
Nervestation

### PR DESCRIPTION
**Pull request by ghost**
[general][content]
image
Earliest concept art for this station I could find from November 26th, 2020, with work beginning the day after. So after almost 1 year in development, hopefully it will have been worth the weight.
image
A fairly average sized station, nerve station is centred around four of the main departments, security, medbay, engineering and research, centralised and surrounding the command one, with all heads of staff offices connecting directly to the bridge. Each department also connects to each other in ways that benefit them, such as a shared telesci between paramed and science, chemistry having a desk by R&D like on deff, mechanics having immediate telecomms room access from their office, the morgue being near the security stuff, botany opposite chemistry, and so on.
image
The research and mining outpost are also one in the same like on many maps to fit this theme, although there's not much else to say about it as it's fairly conventional.
image
Same with the trader outpost, but there's a restaurant with air flaps connected to the entrance lobby to be of note in design.

:cl:
 * rscadd: A desire for centralisation of departments, especially for command, has birthed a new station in rotation: Nerve Station.

### CODE REVIEW

**Comment by SonixApache** [comment]
mite b cool

**Comment by GreatBigFailure** [comment]
I like it. Given the concept I think more distinct aesthetic boundaries would be good though. Like a very obvious "my side of the apartment" tile colour. Though this is based on a phone sized glance at the map so use a grain of salt.
One immediate suggestion is to really look at what most research stations have and make sure this one is compatible. Off the bat I notice it's missing the spare metal/glass, the monkey cubes, and the stasis field generators. The research station is super useful as a source of resources when you're trying to do a gimmick and want to start things away from prying eyes.

**Comment by Kurfursten** [comment]
Resolution too low to really see details though

**Comment by calzilla1** [comment]
>warden has to leave the brig to access the armory
Kino station, speedmerge nao

**Comment by Eneocho** [comment]
Could you post a higher resolution full map picture? I can barely see shit.

**Comment by Eneocho** [comment]
Please move the doors to the miner chambers or the miners themselves to the center, else you have to actually enter the room and get crushed by the pressure.

**Comment by Eneocho** [comment]
> 
> 
> I like it. Given the concept I think more distinct aesthetic boundaries would be good though. Like a very obvious "my side of the apartment" tile colour. Though this is based on a phone sized glance at the map so use a grain of salt. One immediate suggestion is to really look at what most research stations have and make sure this one is compatible. Off the bat I notice it's missing the spare metal/glass, the monkey cubes, and the stasis field generators. The research station is super useful as a source of resources when you're trying to do a gimmick and want to start things away from prying eyes.

Could also use the carpboxes on xenobio as a test of just how bad/good they can be.

**Comment by Eneocho** [comment]
Alright. I loaded the map on StrongDMM. I can't take a high resolution screenshot for some reason, but here are my thoughts:

- The containment area/what I assume is the borer pen has no way to inject the gas nor a way for the borer to leave the chamber. Also, those dual glasslocks will flood if accidentally opened.
- Do the exofabs have their output set to south?
- Please move the xenobotany machines to the main botany room, trust me, it saves a TON of time on the back and forth.
- The civilian rage cage is a nice touch. It needs some windoors though.
- You could add a sepia camera to the chapel, like in deff.
- I'd swap one of the FEED signs on the traderdock with a SEED, so it says SEED FEED instead of FEED FEED or SEED SEED.
- There's no way to dispose of/syphon the contaminated air after you gas chamber someone in the execution chamber. You will either N2O/Plasma flood or get ZAS crushed by the 4500° CO2 after burning the guy alive.
- A plasmafire in the gas chamber would break those windows. Place them outside facing in.
- The treadmills on maint gym are not connected to a powernode.
- Why is the sec escape pod reinforced with plasmaglass, while all the other pods (and shuttles) only have regular reinforced glass?
- Most of the windows near perma lack the wall touching side window or have the inner windows on the wrong orientation.
- Why in the high fucks would you place a turret inside the vault? DELETE, REEEEEEEEE.
- Add more coloured tiles to differentiate departments.
- Having critical engineering stuff like the SMES units that far away from the engines proper is just cumbersome. It's faster to wire to grid.
- Move one of the tables or something on the Engineering Foyer so you can break into the CE room. Else you can't unlock Engi Storage without hacking doors.
- Place an airlock on the western side of the Scrungulo Radcollector area so you can get to space from there as well.
- The TCOMMS junction to junction is unnecesary, you can just continue the loop using regular HE pipes.
- There are no dedicated engi hardsuis on engineering, only those two on EVA, while atmospherics does have extra hardsuits. Please add a few hardsuits to engi as well.
- Add a few of the more exotic vending machines, like the Nuka Vendor, Offworld Off-License, Circus of Values, the ZAM one, etc.
- Add the barbervend and/or cosmetics vendor to the locker room.
MoMMI nest needs a Deconstructive Analyzer, else the MoMMI can't do research on its own. Could also use an autolathe.
- You need at least 2 Shield gens to create a wall shield, having them on the easternmost wall of telescience is pointless. Consider placing them on all 4 corners.
- Why are there 2 empty gas canisters inside telescience? You can't even use them to store scrubbed gases, why are they there?
- There's no way to dispose of the gas on any cryo loop. You need to in case someone or something maxes the tubes pressure. Just add a volume pump to the waste loop and keep it off.
- Could use a few more "raw" monkeys on genetics and virology.
- Due to being thrown out of a disposals loop, all the corpses you put inside the clonelab disposals chute will be also thrown inside the morgue's disposals chute, making any corpse sent this way end up in disposals/recycling.
- The morgue is a bit cumbersome to access as a medic.
- Place a microphone inside the holodeck so holomen can actually communicate with crew.
- Why are there 6 missing radcollectors on the shard room? You even wired them, why are they missing?
- The warden has to leave the brig to enter perma.

Probably more but my eyes hurt.

**Comment by ghost** [comment]
Uploaded a better quality image @Kurfursten @Eneocho

**Comment by ghost** [comment]
> * The containment area/what I assume is the borer pen has no way to inject the gas nor a way for the borer to leave the chamber. Also, those dual glasslocks will flood if accidentally opened.

Added this

> * Do the exofabs have their output set to south?

They do now

> * Please move the xenobotany machines to the main botany room, trust me, it saves a TON of time on the back and forth.

Not every map does this

> * The civilian rage cage is a nice touch. It needs some windoors though.

Done

> * You could add a sepia camera to the chapel, like in deff.

I dunno, maybe

> * I'd swap one of the FEED signs on the traderdock with a SEED, so it says SEED FEED instead of FEED FEED or SEED SEED.

Done

> * There's no way to dispose of/syphon the contaminated air after you gas chamber someone in the execution chamber. You will either N2O/Plasma flood or get ZAS crushed by the 4500° CO2 after burning the guy alive.

Fixed.

> * A plasmafire in the gas chamber would break those windows. Place them outside facing in.

Made them plasma instead.

> * The treadmills on maint gym are not connected to a powernode.

They're meant to be?

> * Why is the sec escape pod reinforced with plasmaglass, while all the other pods (and shuttles) only have regular reinforced glass?

Some other map does it.

> * Most of the windows near perma lack the wall touching side window or have the inner windows on the wrong orientation.

Was meant to fix this, thanks.

> * Why in the high fucks would you place a turret inside the vault? DELETE, REEEEEEEEE.

Never.

> * Add more coloured tiles to differentiate departments.

I could try make them stand out more.

> * Having critical engineering stuff like the SMES units that far away from the engines proper is just cumbersome. It's faster to wire to grid.

Fixed that by moving some closer to them.

> * Move one of the tables or something on the Engineering Foyer so you can break into the CE room. Else you can't unlock Engi Storage without hacking doors.

No.

> * Place an airlock on the western side of the Scrungulo Radcollector area so you can get to space from there as well.

Helps flow, is better, done.

> * The TCOMMS junction to junction is unnecesary, you can just continue the loop using regular HE pipes.
> * There are no dedicated engi hardsuis on engineering, only those two on EVA, while atmospherics does have extra hardsuits. Please add a few hardsuits to engi as well.

Added some.

> * Add a few of the more exotic vending machines, like the Nuka Vendor, Offworld Off-License, Circus of Values, the ZAM one, etc.

Added recharge packs for them at trader shop.

> * Add the barbervend and/or cosmetics vendor to the locker room.

If I find room.

> * MoMMI nest needs a Deconstructive Analyzer, else the MoMMI can't do research on its own. Could also use an autolathe.

Not many maps do this, why?

> * You need at least 2 Shield gens to create a wall shield, having them on the easternmost wall of telescience is pointless. Consider placing them on all 4 corners.

Thanks, fixed.

> * Why are there 2 empty gas canisters inside telescience? You can't even use them to store scrubbed gases, why are they there?

Other maps do it, dunno.

> * There's no way to dispose of the gas on any cryo loop. You need to in case someone or something maxes the tubes pressure. Just add a volume pump to the waste loop and keep it off.

Thanks, added this.

> * Could use a few more "raw" monkeys on genetics and virology.

Added one extra to each. That do?

> * Due to being thrown out of a disposals loop, all the corpses you put inside the clonelab disposals chute will be also thrown inside the morgue's disposals chute, making any corpse sent this way end up in disposals/recycling.

No they don't, tested this.

> * The morgue is a bit cumbersome to access as a medic.

Best I could do.

> * Place a microphone inside the holodeck so holomen can actually communicate with crew.
> * Why are there 6 missing radcollectors on the shard room? You even wired them, why are they missing?

Added them.

> * The warden has to leave the brig to enter perma.

As it should be.

**Comment by SonixApache** [comment]
>>The warden has to leave the brig to enter perma.

>As it should be.

????

**Comment by Kurfursten** [comment]
Bad brig

* Warden can't see even one prison cell
* Warden quite distant from perma
* Perma has FOUR entrances from maint and exists in a part of the station no sec off should be in regularly
* Entrance to brig has a 6x1 "kill zone" where you have to walk in a straight line for convenient execution on both sides
* Brig also has convenient entrances to the MAIN HALL conveniently located out of frame of anyone at the desk so you can free your friends without being seen
* Evidence room shares a wall with the ghetto bar

Please just delete all of perma, it would literally be better to have no perma than one this bad. I would never, ever store a prisoner here.

**Comment by Kurfursten** [comment]
Engineering

* Probably don't need those shutters on the left side of PA because they're redundant, no way in with all those r-walls - kind of awkward extra airlock walk before the external airlock when setting up singulo/rust
* No emitters for this singulo setup?
* Passive waste vent disconnected by gas mix tank?
* TEG feels like it would rather be flipped - put cold loop on top with easy north space access and put the burn chamber below
* SME room cramped, prefer 2-wide on all sides of engine for less clutter - just extend it out more and this will be solved
* Atmos suits 1 window from main hall, please NO - metaclub has a big problem with suit theft
* Where are the engineering hardsuits?
* Good engineering really needs 2 power monitors: one on engineering grid and one on main grid. Not clear which grid the one in eng lobby is on (clearly the one in the SME room is on the eng grid). Seems a little awkward to have the SMES so far from the engines but I see what you're going for and it's a gimmick so fine
* No silicate tanks?
* Most AMEs these days come with acoustic panels if they are near a major hallway
* Camera mounted directly onto shutters at secure storage?
* Secure storage seems awfully far from the CE office which makes backtracking a pain if you need into it
* Area between TEG and atmos seems awkwardly underutilized

**Comment by Eneocho** [comment]
>>Please move the xenobotany machines to the main botany room, trust me, it saves a TON of time on the back and forth.

>Not every map does this

But every map should. It is a godsend to have those machines in the main botany room, and with a game as fast as spess, any time save is welcome. You can't do any complex plant project if it takes you too long, because the round is over by then.

>>Having critical engineering stuff like the SMES units that far away from the engines proper is just cumbersome. It's faster to wire to grid.
>>Move one of the tables or something on the Engineering Foyer so you can break into the CE room. Else you can't unlock Engi Storage without hacking doors.

>No.

I can concede on the CE room thing, but the SMES units should be on Engineering proper. Specially since you'll have to go back and forth to tweak the thing if shit happens, which wastes time. 

>>Add a few of the more exotic vending machines, like the Nuka Vendor, Offworld Off-License, Circus of Values, the ZAM one, etc.

>Added recharge packs for them at trader shop.

Having the machines themselves mapped somewhere would be nicer. That whole ZAM thing is cool and I'd like to see it more often than the one or two rounds a cargo tech/assistant decides to build one.

>>Add the barbervend and/or cosmetics vendor to the locker room.
>>MoMMI nest needs a Deconstructive Analyzer, else the MoMMI can't do research on its own. Could also use an autolathe.

>Not many maps do this, why?

Barbervend/cosmetics vendor for muh RP purposes and the barber/hair dresser gimmick. Also works for pranks since you can dye/shave someone's hair.
MoMMIs sometimes need some researched stuff and using regular RnD if someone is already there is a big no-no. Not many maps do it, because the mappers forget to add it.

>>Why in the high fucks would you place a turret inside the vault? DELETE, REEEEEEEEE.

>Never.

REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.

>>The treadmills on maint gym are not connected to a powernode.

>They're meant to be?

Most maps have them wired to a node, since they also work as a power source.

>>A plasmafire in the gas chamber would break those windows. Place them outside facing in.

>Made them plasma instead.

As far as I know, they'll break still. Place them outside facing in. I've had plasmawindows shatter from a fire inside.

**Comment by Eneocho** [comment]
There's also a disappointing lack of weldertanks and maintloot. Where are the floorpill spawners? Where are the fireman suits? The mesons and gasmasks?

**Comment by Kurfursten** [comment]
Science
* 2 telesci shield gens seem pointless if there are 3 sides with windows

Civ
* No barstools at bar?
* Dorms don't lock
* Not a fan of a lack of a clear transition between bar and dorms with flooring
* That chapel launcher looks unfinished
* Morgue2 and chapel office look really really cramped
* Kitchen: better to have bin near edges since it's a pain to move if you want to customize your space; maybe swap with ice cream machine
* Cargo lobby maybe better flipped so you walk straight up to desk; desk also can oversee mail room better this way
* 

Silicon
* MoMMI nest has no pipes out, ree

Med
* All tools want to be within reach, swap sink and third table in overflow surg
* Did you test this sort junct? Not sure you can label human packages; default should be morgue2 not detective
* Chemfridge feels awfully far from the actual doctoring and the 2-wide bottleneck at the main (top) entrance reminds me strongly of original deff medbay and the unfortunate feelings of 2-wide medbay hall.
* Rethink paramedic office layout
* Overall feels like the prime real estate was given to things that can be more peripheral to medbay like paramedics and genetics

**Comment by ghost** [comment]
> Bad brig
> 
> * Warden can't see even one prison cell

Made him able to see at least one prison cell.
> * Warden quite distant from perma

Gave him a roundstart point in brig to help it a bit.
> * Perma has FOUR entrances from maint and exists in a part of the station no sec off should be in regularly

Gutted all of them.
> * Entrance to brig has a 6x1 "kill zone" where you have to walk in a straight line for convenient execution on both sides

Shrunk it a bit, will work on it.
> * Brig also has convenient entrances to the MAIN HALL conveniently located out of frame of anyone at the desk so you can free your friends without being seen

Gutted these too.
> * Evidence room shares a wall with the ghetto bar

Just a hall that looks like it.

**Comment by ghost** [comment]
> There's also a disappointing lack of weldertanks and maintloot. Where are the floorpill spawners? Where are the fireman suits? The mesons and gasmasks?

Adding them as we speak, this is a draft for a reason.

**Comment by ghost** [comment]
> Engineering
> 
> * Probably don't need those shutters on the left side of PA because they're redundant, no way in with all those r-walls - kind of awkward extra airlock walk before the external airlock when setting up singulo/rust

Removed em

> * No emitters for this singulo setup?

Added

> * Passive waste vent disconnected by gas mix tank?

Whoops, fixed.

> * TEG feels like it would rather be flipped - put cold loop on top with easy north space access and put the burn chamber below

Done.

> * SME room cramped, prefer 2-wide on all sides of engine for less clutter - just extend it out more and this will be solved

Done.

> * Atmos suits 1 window from main hall, please NO - metaclub has a big problem with suit theft

Good point, fixed.

> * Where are the engineering hardsuits?

Added them already.

> * No silicate tanks?

Added.

> * Most AMEs these days come with acoustic panels if they are near a major hallway

Added these.

> * Camera mounted directly onto shutters at secure storage?

Whoops.

**Comment by ghost** [comment]
> Science
> 
> * 2 telesci shield gens seem pointless if there are 3 sides with windows

Already fixed this.

> Civ
> 
> * No barstools at bar?

Whoops, fixed.

> * Dorms don't lock

Added locking doors now.

> * Not a fan of a lack of a clear transition between bar and dorms with flooring

Added carpet to help now.

> * That chapel launcher looks unfinished

Added the button.

> * Morgue2 and chapel office look really really cramped

Spaced them out.
> * Kitchen: better to have bin near edges since it's a pain to move if you want to customize your space; maybe swap with ice cream machine

Fixed.

> * Cargo lobby maybe better flipped so you walk straight up to desk; desk also can oversee mail room better this way

Fixed.

> Silicon
> 
> * MoMMI nest has no pipes out, ree

Added them, had no atmos at all wow.
> Med
> 
> * All tools want to be within reach, swap sink and third table in overflow surg

Done.
> * Did you test this sort junct? Not sure you can label human packages; default should be morgue2 not detective

Yeah it doesn't work, will undo it.
> * Chemfridge feels awfully far from the actual doctoring and the 2-wide bottleneck at the main (top) entrance reminds me strongly of original deff medbay and the unfortunate feelings of 2-wide medbay hall.
> * Rethink paramedic office layout

Done

**Comment by Viciousaurus** [comment]
This map is pretty dang big, which wouldn't necessarilly kill it except that the roundabout that makes the main hallway is Bagel-tier. 

I get the dea of the bridge being connected directly to the Heads' offices, and is even clever, but anyone else that wants to get to the bridge have to make the trip all around to arrivals and then walk up the Green Mile, not to ention is the _only_ point of access from the main hallways.

2 airlocks in less than 10 tiles separate the main hallway from the armory.

Chemistry is too far away from the reception desk.

Derelict bar behind the brig section with the evidence lockers is questionable.

Turrets in space over the AI core... Was this tested? Because last time I checked they don't work as they are bound to their respective areas and don't attack anything that's not stepping on it, even if it's right next to them.

Massive civilian space and the clown doesn't even get a stage shm.

**Comment by ghost** [comment]
> Turrets in space over the AI core... Was this tested? Because last time I checked they don't work as they are bound to their respective areas and don't attack anything that's not stepping on it, even if it's right next to them.

Yeah I changed this so they no longer need areas.

> Massive civilian space and the clown doesn't even get a stage shm.

They very clearly do at the bar.

**Comment by Eneocho** [comment]
Can you please move the xenobotany machines to the main botany room please?
Also the MoMMI nest needs that deconstructive analyzer.
If possible also some of those rarer vending machines in maint or somewhere instead of the packs on the trader room.

**Comment by ghost** [comment]
>Also the MoMMI nest needs that deconstructive analyzer.

Not every map does this.
>If possible also some of those rarer vending machines in maint or somewhere instead of the packs on the trader room.

Did this already.

**Comment by Kurfursten** [comment]
I should say that the creepgang trying to push special vendors on *every* map is making them less special

**Comment by Eneocho** [comment]
> > Also the MoMMI nest needs that deconstructive analyzer.
> 
> Not every map does this.

But again, they should. In the event a MoMMI wants to do RnD they are better off using the mommi nest instead of the RnD Labs since if there are people in RnD that's a big no-no with them keeper laws.

**Comment by Blithering** [comment]
I like the bridge being able to see little snippets of each department, captain seeing his highly trained scientists ignite and then vent the borer pen firsthand. Revs is going to be interesting too.

**Comment by adacovsk** [comment]
Just playtested a little, found some issues:

- server room 272,261,1 wall door, vent off
- 278, 365,1 wall door
- 268, 254 wall door
- beaccons
- morgue conveyor wrong way
- armoryshutter button
- all vents  off in brig
- two warden air alarms
- brig conveyor messed up
- brig disposals to recycling underneath window is missing, puts you in gas chamber
- disposals goes to delivery room rather than disposals conveyor and recycling conveyor doesn't work
- vent off in delivery room
-disposals conveyor doesn't work
- put a light between external airlocks
- visible pipes for borer hatchery
- SME and TEG  room unpowered
- (201,299,1) wall
- left exosuit fabricator conveyor broken
- (331,234,1) wall
- shutter button mech bay

Probably needs a lot more playtesting before merging, but seems like a nice map

**Comment by ghost** [comment]
> server room 272,261,1 wall door, vent off

Fixed

> 278, 365,1 wall door

Fixed (also it was 278, 265, 1)

> 268, 254 wall door

Fixed

> beaccons

Added these, and beepsky.

> morgue conveyor wrong way

Fixed

> armoryshutter button

Fixed

> all vents  off in brig

Fixed

> two warden air alarms

Fixed

> brig conveyor messed up

Fixed

> brig disposals to recycling underneath window is missing, puts you in gas chamber

Fixed

> disposals goes to delivery room rather than disposals conveyor and recycling conveyor doesn't work

Fixed

> vent off in delivery room

Fixed

> disposals conveyor doesn't work

Fixed

> put a light between external airlocks

Don't really notice them on some maps.

> visible pipes for borer hatchery

Most maps have this.

> SME and TEG  room unpowered

Fixed

> (201,299,1) wall

Fixed

> left exosuit fabricator conveyor broken

Fixed

> (331,234,1) wall

Fixed

> shutter button mech bay

Fixed

**Comment by SonixApache** [comment]
?

**Comment by ShiftyRail** [comment]
Terrible idea.

**Comment by Kammerjunk** [comment]
thus marking the 60th /vg/station map

**Pull request merged**
