### PR TITLE
Migrate Xenos to Midround

### PR DESCRIPTION
**Pull request by Kurfursten**
Not tested, I want shifty's blob thing to hit before this

Gets rid of the old xeno events and buttons, replaces them with a midround ruleset. Feel free to discuss threat cost/thresholds, I just pasted the one for blob.

🆑 
* rscadd: Xenos are now a midround ruleset.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Thank you Kurfursten, very cool!

**Comment by DrSnips** [comment]
I will admit my bias here that I dislike xenos as a whole due to everything involved with them. I'd rather not have xenos show up more often like antags because xenos are basicly a round ender when they show up and are considered big gay due to them aciding the comms console and making the round become xeno-stended if the crew didn't instantly call it once they show up.

**Comment by Kurfursten** [comment]
It's a bug if the shuttle isn't getting called when the last comms console on Z_STATION is destroyed

**Comment by DrSnips** [comment]
I think/heard there is some crazy requirements for it where all silicons must be dead, all comms console circuits are gone, all printer/research consoles are gone, and you have to have the planets line up while halley's comet is passing by. I can't find it myself so I'm trusting the words of other people and going off the fact that I've seen xenos melt all the comms consoles/circuits with no auto call.

**Comment by DeityLink** [comment]
About fucking time

**Comment by ShiftyRail** [comment]
It should require a much higher threat level and/or be unable to fire until a hefty amount of time
Xenos are a round-ender against which it is very hard to fight

As for the automatic comms call, it exists, but is usually only triggered by singularity, as the backup board in Tech storage will often prevent it from ticking.

**Comment by Kurfursten** [comment]
We could override acceptable to require station time to be after 60, 90, 120 minutes, whatever.

**Comment by DeityLink** [comment]
I think the threat requirements are fine. These things are easier to attune in hindsight either way.

**Pull request closed without merging**
