### PR TITLE
Shuttle Revolution: Part 1

### PR DESCRIPTION
**Pull request by ghost**
This still a WIP but I thought I'd give the collabs time to review what I've done so far. It involves mostly structural work.

- [ ] Refactor shuttle code and remove all the 3 line comments explaining a basic if statement
- [ ] Make each area have an indefinite cap of APC's and Air Alarms all synced to each other do that construction around the station isn't aids. Rework construction permit and CE blueprints UI, also maybe add construction permits to engi lockers since most people don't know they exist. Important to shuttles since every shuttle is based on its area.
- [ ] Improve hyperspace/transit (e.g. the 2 minute travel time on the emergency shuttle). Maybe improve the graphic with something more multidirectional (see how ugly the mecha graveyard can look), un hard-code the transit areas (currently you have to hard code the transit location of the emergency shuttle and escape pods), improve general functionality like replacing the space floor with hyperspace whenever a shuttle floor is broken. On a coding end, this would remove the concept of a "transit port" entirely, as transit is currently just a dock in hyperspace. Instead, it would teleport you to a random location in the large square of hyperspace. 
- [ ] Improve shuttle graphics. Also allow shuttle walls and floors to be constructed, deconstructed, and built on (escape shuttle will feature reinforced shuttle structures). In a future update shuttle structures will have a reason for being used in place of normal walls other than aesthetic. Maybe add reinforced plating (what you build tiles on).
- [ ] Improve functionality of custom shuttle engines and custom shuttle construction in general (they're a fair bit buggy and the process is poor).
- [ ] Remove the derelict and use it for hyperspace level instead (controversial)

:cl: 
* rscadd: (?)

### CODE REVIEW

**Comment by ghost** [comment]
I noticed I committed snaxi again. Will fix haha ha

**Comment by tuypo1** [comment]
I believe bay has shuttle stuff you may want to check out, I'm not sure of the extent of it though

**Comment by Blithering** [comment]
Don't we already have a transit space area on Z2? Why remove the derelict?

**Comment by Durgen** [comment]
Don’t touch the derelict

**Comment by utilitas-** [comment]
\>removing derelict
Nonatomic bullshit as always. When are we banning ass eclipse from the repo?

**Comment by Tehsapper** [comment]
>removing derelict

what the fuck

**Comment by ghost** [comment]
How about telecomms sat, then?

**Comment by tuypo1** [comment]
If you really need an entire empty z level to yourself couldn't you just add another one?

**Comment by RaccoonBro** [comment]
yeah, removing any current z-level seems like a terrible idea tf

**Comment by ghost** [comment]
Performance is a significant issue, and nobody really uses the telecomms sat anyway. Making a new z-level is an entire 250^2 tiles, and byond has a software limitation of 2GB ram. It would improve performance to replace the almost untouched telecomms with a 150^2 hyperspace z level.

**Comment by Blithering** [comment]
What purpose would the hyperspace serve that the current transit tiles don't that would require a whole zlevel being bulldozed?

**Comment by utilitas-** [comment]
How about you stop removing random shit and replacing it with completely pointless bullshit for absolutely no reason other than "software limitations" on which _an empty fucking z-level has basically zero impact_ (which might somehow be an even worse fucking reason than "stimulating the economy" by incentivizing niqqering half the station), you fucking hack?
I repeat, ass eclipse repobanned when?

**Comment by Durgen** [comment]
Most of z2 is empty, why would an entire new z level be needed

**Comment by unid15** [comment]
There's already a functionality to procedurally generate transit areas for any shuttles, they're almost identical to the current ones (the difference being that they just teleport you to deep space instantly if you jump off the shuttle, rather than throwing you around a bit beforehand). Use that instead of reserving an entire z-level

**Pull request closed without merging**
