### PR TITLE
Fixes broken bottles being either totally harmless or incredibly powerful

### LINKED ISSUE #7707: Broken bottles are broken
Broken bottles no longer do any damage.

### PR DESCRIPTION
**Pull request by Exxion**
What happened to the line endings, anyway? Both files I've edited in the past couple days say every line is changed and refuse to let me discard the changes. I had to manually select only this line to commit.

Fixes #7707

All broken bottles now have force 9, which is much more reasonable than either 0 (thrown bottles) or 15 (bottles smashed over someone's head).
(Smashing a bottle over someone's head is still force 15, just the broken bottle left after you do so isn't.)

### CODE REVIEW

**Comment by 9600bauds** [comment]
rip 15 force bottles
guess i'll be making a ghettolathe every round as assistant from now on :^)

**Comment by Exxion** [comment]
Or you could just take the tray in maint that nobody ever picks up, which deals 3 or 5 damage to whatever limb you target and has an extra-high chance of knockdown

**Comment by 9600bauds** [comment]
I think it's a trash/tray, not a weapon/tray

**Comment by Exxion** [comment]
Maybe
I don't know
Probably
boo

Anyway toolboxes are force 12, which isn't much less than 15

**Comment by 9600bauds** [comment]
>don't fit in your backpack
>force 12, which is less than 15
>don't decap

**Comment by Exxion** [comment]
Ah, but
Circular saw requires an autolathe and costs an absurd amount of metal to make

Also spears are force 18 when wielded and are much easier to acquire
And while spears don't fit in the backpack, both glass shards and wired rods do, so you can just keep one of each in your backpack for quick spearcrafting

**Comment by Exxion** [comment]
Closing this to redo it after #7733. It'll be easier to just redo this change than to try to fix the conflict.

**Comment by PJB3005** [comment]
Dude, fixing the conflict is easy as shit...

**Comment by Exxion** [comment]
Yes, but redoing the change is as easy as typing //
And I kind of want to be able to look at my other branches

**Pull request closed without merging**
