### PR TITLE
Grayy Rig Sprite Updates

### PR DESCRIPTION
**Pull request by Optimism333**
## Ayy Lmao ##
I did my best to make some edits to improve the overall appearance of the worker and leader rigsuits. I hope experienced spriters will forgive my amateur work. Thanks to Blithering for making the original sprites and therefore making this pr a possibility.

Babby's first pr. Please be patient and tell me in detail what I did wrong if I messed this all up somehow.

 * The worker rigsuit now has a hardhat to better differentiate it from the researcher rigsuit (old and new comparison below). I also improved the butt shading on the rear view sprite.
Screenshot (341)
Screenshot (347)

 * The Leader rigsuit has been redesigned with more uniform coloration, bigger shoulder pauldrons, and a bubble dome helmet instead of the previous partial dome. (old and new comparisons below) 
Screenshot (342)
Screenshot (344)
Screenshot (343)
Screenshot (345)

 * Sprites for the rig helmets in their item states and with flashlights on were also updated.

:cl:
 * The Grayy worker and leader rigsuits have had their appearances updated.

### CODE REVIEW

**Comment by SonixApache** [comment]
incorrect :cl: syntax - :cl: is just for the ingame viewers, should be kept concise, should not contain images
personally i like all the techno-bullshit on the old rigsuit better but i'm a neverplayer so pinch of salt

**Comment by Optimism333** [comment]
> incorrect 🆑 syntax - 🆑 is just for the ingame viewers, should be kept concise, should not contain images
> personally i like all the techno-bullshit on the old rigsuit better but i'm a neverplayer so pinch of salt

Thanks for the feedback. Fixed the syntax.

**Comment by Optimism333** [comment]
I accidentally added an unrelated change, then deleted the whole file when trying to remove the change, and had to reupload the file to my branch. Lesson learned... make sure to do new work on a separate branch. Coding at level zero is tough.

**Comment by Optimism333** [comment]
Going to redo this pull request and try not to be so clumsy next time.

**Pull request closed without merging**
