### PR TITLE
Adds some safety to OOC to prevent ick ock

### LINKED ISSUE #6935: Make OOC not accept messages starting with ;
Cut down accidental ick ock
Cut down "accidental" ick ock
Profit

### PR DESCRIPTION
**Pull request by JustSumBody**
image
I wonder how long I can go straight up copypasting stuff from /tg/
closes #6935

### CODE REVIEW

**Comment by ghost** [comment]
PLEASE
fake icks are dumb as hell. 
Also reminds of the round a paramedic ling accidentally common radio'd "G Paramedic here". That was funny.

**Comment by ghost** [comment]
Most important PR of our time.

**Comment by ihadtoregisterforthis** [comment]
#6935

**Comment by unid15** [comment]
> Your message ":^)" looks like it was meant for in game communication

evaluations = eroded

**Pull request merged**
