### PR TITLE
removes neon colored vox

### PR DESCRIPTION
**Pull request by Intigracy**
allvox

bad1
bad2

Might fit on paradise but here it's just gross.
Please note that while the last two might have tails in the top image, they don't have them ingame. Weren't even ported right smh.

:cl:
- imagedel: Removed Emerald and Azure Vox colors.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Would the neon vox look better if they were desaturated a bit?

**Comment by Intigracy** [comment]
I desaturated them :^)

good

**Comment by Shadowmech88** [comment]
Black vox doesn't look too bad.

**Comment by Exxion** [comment]
In a vacuum it doesn't, but it fits with the other colors even worse than these do

**Comment by SonixApache** [comment]
blax

**Comment by Intigracy** [comment]
I have (((plans))) for vox and I'll just replace these with two new ones when I get around to it.

**Pull request closed without merging**
