### PR TITLE
super duper shotgun

### PR DESCRIPTION
**Pull request by gurfan**
## What this does
adds super duper shotgun

no changelog, only for bussing

### CODE REVIEW

**Comment by SalmonIsTasty** [comment]
image

**Comment by assmops** [comment]
dont we already have the bulletstorm for that?

**Comment by SalmonIsTasty** [comment]
> dont we already have the bulletstorm for that?

The Super Duper Shotgun is a direct homage to the "too many super shotguns" Doom mod and has quite a few differences to the bulletstorm:

-comedic value (multiple barrels stacked on top of each other are funny)

-it doesnt have a single, special projectile inside it that mimics multiple bullets, it is in its core a regular shotgun, so you have to manually load all of the shells (also comedic)

So even though both of them convey similar theme, they are different to one another.

I might also ask gurfan to try making it so that if somebody shoots it without strong gene, gets their arms broken (if it's possible and not too time consuming to code, as he already did this pull request in my stead)

**Comment by Theophrastus1** [comment]
> > dont we already have the bulletstorm for that?
> 
> The Super Duper Shotgun is a direct homage to the "too many super shotguns" Doom mod and has quite a few differences to the bulletstorm:
> 
> -comedic value (multiple barrels stacked on top of each other are funny)
> 
> -it doesnt have a single, special projectile inside it that mimics multiple bullets, it is in its core a regular shotgun, so you have to manually load all of the shells (also comedic)
> 
> So even though both of them convey similar theme, they are different to one another.
> 
> I might also ask gurfan to try making it so that if somebody shoots it without strong gene, gets their arms broken (if it's possible and not too time consuming to code, as he already did this pull request in my stead)

it should just blow their fucking arms off if its squeezing several shells down range

**Comment by SalmonIsTasty** [comment]
Adding thresholds depending on the amount of shells loaded would make sense - from normal shot, to tripping you, stunning, arm breaking and finally blowing arms off. Yet again, it all depends on gurf if he'd like to do it.

**Pull request merged**
