### PR TITLE
Body scanners will now show the dangerosity of virus

### PR DESCRIPTION
**Pull request by ShiftyRail**
scan

The symptoms themselves are not described, but the quick diagnostic gives medbay an idea of the urgency of a virus.
An improved scanner shows more info - including precisely at which stage the virus gets harmful, and if there are beneficial symptoms, without showing what those symptoms are. (use the virologist's machines for that)

Had the idea while reading the thread. Access to this information helps medbay to chose if they prioritise the virus or the pile of bodies near the cloner.

:cl:
- tweak: The body scanner in medbay will now help you diagnose the lethality of a virus outbreak.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This gave me an idea for medhud

You know those throwaway <50 robustness viruses that people eat a spaceacillin and forget about? It would be nice if those just show up with a special "low danger virus" icon separate from the normal virus / beneficial virus icon

**Comment by Manleto** [comment]
This hurts antag virologists who want to deceptively create a virus with 3 begin symptoms and one deadly one. You need to give a way to fake it.

**Comment by Eneocho** [comment]
> 
> 
> This hurts antag virologists who want to deceptively create a virus with 3 begin symptoms and one deadly one. You need to give a way to fake it.

This. It's a good idea on paper, but cucks any attempt at a deceptive good virus that kills you in the end.
Make it so if it's logged in the system, it says the virus name, not the symptoms.

**Comment by ghost** [comment]
Ideally change it to a number representing the net danger of a disease, like centcomm requests use

**Comment by DeityLink** [comment]
> 
> 
> This gave me an idea for medhud
> 
> You know those throwaway <50 robustness viruses that people eat a spaceacillin and forget about? It would be nice if those just show up with a special "low danger virus" icon separate from the normal virus / beneficial virus icon

<50 strength, not robustness
Also technically there are already 3 different virus icons to choose from, all of which can be set up from a Medical Records computer.

**Comment by DeityLink** [comment]
Also regarding the possibility of it ruining the chances of a antag disease reaching stage 4, you can kinda counteract that by "incubating" the disease inside of a mouse/monkey, wait for it to reach stage 4, and THEN take blood from it. if it's a parasite people who ingest that blood will immediately be stage 4, if it's a Virus it'll be stage 3 which is already pretty nice.

**Comment by ShiftyRail** [comment]
I could give it a way to be slightly altered (and not showing the real lethality of the virus) by hacking of modifying the body scanners, if that's truly needed.

**Comment by PavelCIA** [comment]
just put a centrifuge in the medbay lobby so people don't have to rely on the lobotomized retards working at medbay to make a cure

**Comment by Manleto** [comment]
> Also regarding the possibility of it ruining the chances of a antag disease reaching stage 4, you can kinda counteract that by "incubating" the disease inside of a mouse/monkey, wait for it to reach stage 4, and THEN take blood from it. if it's a parasite people who ingest that blood will immediately be stage 4, if it's a Virus it'll be stage 3 which is already pretty nice.

What if you're making an airborne virus? 



> I could give it a way to be slightly altered (and not showing the real lethality of the virus) by hacking of modifying the body scanners, if that's truly needed.

I think a better way to do it is let the person set the lethality of the symptoms on a virology computer. Wouldn't affect it most of the time but would allow antag viros to deceive people

**Comment by Kurfursten** [comment]
Symptom danger as it exists currently is not something you would want players to adjust, because it affects what symptoms can appear in diseases.

**Comment by Manleto** [comment]
You're not actually affect the symptom danger itself rather what shows up on a scan.

**Comment by Eneocho** [comment]
As one anon said on the thread, allowing for database symptom danger changing would allow for some dank powergaming. Buy 5 boxes of random diseases, infect a monkeyman with all your dishes, set all the symptoms you don't want to harmless and the ones you want to deadly. Scan the monkey. You now know you have your target symptoms without scanning constantly.

**Comment by Manleto** [comment]
You could solve that by only saying the total number of deadly symptoms rather then which disease has which.

**Comment by ShiftyRail** [comment]
Need to do it in a better way for it to be mergeable.

**Pull request closed without merging**
