### PR TITLE
Fixes #11122

### LINKED ISSUE #11122: MoMMI's can't take Vtech or Jetpack upgrade
Why was this taken out?

They could use the board to get speed boost and for a jetpack

### PR DESCRIPTION
**Pull request by ghost**
Fixes #11122

### CODE REVIEW

**Comment by Shadowmech88** [comment]
So does this make it continue to not work for MoMMIs, and just display the message, or does it work for MoMMIs now?

**Comment by PJB3005** [comment]
Doesn't work as was intended.

**Comment by ghost** [comment]
@PJB3005 MoMMIs can now use those items

**Comment by PJB3005** [comment]
Oh, whatever the hell I misread then, still correct.

**Pull request merged**
