### PR TITLE
Increases gas consumption/waste production by x20.

### LINKED ISSUE #11653: Deus Ex gas consumption/waste production is way too low
Would take hours for a dude in a 1x1 box to suffocate due to lack of oxygen
20 mins and it produces like 0.02 moles or something ridiculously low I think
I need to change both of these by a factor of 20 and I think they're directly tied to one another so that works fine

### PR DESCRIPTION
**Pull request by gbasood**
Oxygen consumption and CO2 production increased by 20 times what it was (6/20 = 0.3)
De-magic numbered that denominator too
Resolves #11653 

Tested and appears NOT TO MESS WITH TANK AIR CONSUMPTION
Will update changelog

### CODE REVIEW

**Comment by gbasood** [comment]
Actually this probably breaks tanks entirely
I'll have to test it
If it does, then the only solution that allows me to keep this is to increase all tank capacities by the same factor

**Comment by ghost** [comment]
Upping capacity is gonna fug with bomb making a bit.  Mostly by making cold packing more successful since you'll be able to heat a given quantity of mols higher than previously before hitting leak pressure. 

Making snowflake breathing only tanks will be a snarl too unless you don't care if they're a third invisible category on tank dispensers. And in that case we'd still need a source of emergency and extended emergency tanks since you could do a lot of neat shit with them in atmos/toxins/misc sci./incinerator

Edit: Probably will up 2 dev one-tanks to ezmode if I'm reading this right and potentially make higher strength ones possible.

**Comment by gbasood** [comment]
Yeah, thanks for pointing that out. I won't be fucking with tank capacities
It seems like this doesn't affect tanks though. Because it goes off of how much oxygen you're being supplied as opposed to a flat 'we consume this much gas per tick' number.

So to lower the amount of CO2 the station emits you could just lower the oxygen they breathe for example

**Comment by gbasood** [comment]
After **TEN TO FIFTEEN WHOLE MINUTES** a human in a 1x1 enclosed space will produce around 0.8 moles of CO2 and have consumed the same amount of oxygen
So at that rate it'd still take about an hour for someone to suffocate in an enclosed space at normal station pressure.
@clusterfack @PJB3005

**Comment by Megamaw** [comment]
this is probably one of the worst ideas i've ever seen since 64x64 because it's liable to break so much

**Comment by JustSumBody** [comment]
What are you basing that off of?

**Comment by gbasood** [comment]
@Megamaw What's it going to break? It doesn't affect tank capacity, it doesn't affect the amount of gas that is used via internals. The only things it DOES change is that atmos is pulling in more CO2 and putting out more oxygen in standard circumstances, and unless you've got somewhere around 200 people in one room with only 1 vent you probably wont even notice.

The amount that this impacts is so incredibly small that I actually want to increase it, not decrease it.

**Comment by Megamaw** [comment]
@gbasood if there's basically no functional difference, why merge it? 

i'm just saying, until the impact of this is thoroughly tested, this is something that we probably should not merge.

**Comment by ghost** [comment]
:ok_hand: - people that disagree with this 10/10 change are either casuals or powergamers; both in the case of megamaw

**Comment by Intigracy** [comment]
0.03 when

**Comment by Megamaw** [comment]
man, i ain't no powergamer, i'm a hardcore casual, this just looks like some shit that'd potentially super affect a lot of things, so i'm just worried this is going to break something like bomb making like @SarahJohnson489 brought up, or something

messing with atmos stuff that's been this way for a long ass time is a major change b/c this has always been a static thing. again, all I'm asking is we rigorously test this so we don't break shit like we did with 64x64 because we didn't know how it'd actually work.

**Comment by Intigracy** [comment]
It is 100% impossible for this PR to break bomb making in its current form, because he's only editing the species air breathing proc.

```
 /datum/species/proc/receiveGas(var/gas_id, var/ratio, var/moles, var/mob/living/carbon/human/H)
```

**Comment by Megamaw** [comment]
well, i'm not a clever man, so if you say it's sound, i have no objections

**Comment by Shadowmech88** [comment]
What is the actual rate at which a human converts oxygen into carbon dioxide, at normal breathing speed?

**Comment by Intigracy** [comment]
The average person, through the natural process of breathing, produces approximately 2.3 pounds (1 kg) of carbon dioxide per day. The actual amount depends strongly on the person’s activity level.

https://web.archive.org/web/20110202140715/http://www.epa.gov/climatechange/fq/emissions.html#q6

**Comment by JMWTurner** [comment]
Does that mean that a few humans stuck in a room with no vents can actually pass out of oxygen loss in under 10 hours?

**Comment by PJB3005** [comment]
@JMWTurner yes.

**Comment by ghost** [comment]
If you want, you can pull his branch or just go to the branch at https://github.com/gbasood/vgstation13/tree/gas-consumption-ratio-tweak , download it as a zip and follow pomfs playing locally guide to see if it shook anything loose. Everybody would appreciate more passes to make sure it's all good.

ss13 single player pomf guide server test server

**Comment by BarneyGumball** [comment]
It's probably not an issue, but #11585 could potentially ruin atmospheres in smallish areas without atmos setups.

**Comment by Exxion** [comment]
That's not a bad point
Maybe we should fix that before merging this

**Comment by gbasood** [comment]
well I wish you luck debugging that because it shows up so rarely, at least as a visible problem

**Pull request merged**
