### PR TITLE
increases the range of blind talismans by 1

### LINKED ISSUE #13345: Blind talisman has range 2.
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
That is, one tile out of melee range. Dubiously useful when you can walk one tile and stun. To be useful outside of EXTREMELY NICHE CIRCUMSTANCES, range 3 would be better.

### PR DESCRIPTION
**Pull request by Gef21**
fixes https://github.com/d3athrow/vgstation13/issues/13345

There are two changes for some reason but it won't go away fuk u smartgit

🆑 
 * rscadd: Blind talisman range increased by 1

### CODE REVIEW

**Comment by Probe1** [comment]
You should ALWAYS rebase/get a fresh copy of the repo before you start a new project.

**Comment by Gef21** [comment]
but won't that break my open prs

**Comment by Exxion** [comment]
No

**Comment by Probe1** [comment]
1.  Have a local branch of Bleeding-Edge.
2.  Never ever add code to it.
3.  Make your active branch Bleeding-Edge
4.  Pull from upstream (this repository) so you're up to date.
5.  Make a new branch for your PR
6.  Code on it, commit it, push it to your repo, and open a PR.

Bleeding Edge is like the tree trunk and your branches are the branches.

**Comment by Gef21** [comment]
That's what I did but it's doing this anyway

**Comment by Intigracy** [comment]
5. Push to your repo so it's up to date (since it compares from there)
6. Probe's 5.
7. Probe's 6.

**Pull request merged**
