### PR TITLE
Puddle slipping tweaks

### PR DESCRIPTION
**Pull request by ghost**
[tweak]
Based on feedback I've heard about them.

:cl:
 * tweak: The time spent stunned on any slippery puddle or distance slid on a lube puddle is now tied to the amount of volume on the floor, with 50u representing roughly the old values. There is no effect below 10u on a floor.
 * tweak: Puddles now have a minimum size of 1/10th a turf.
 * tweak: Lube and cornoil puddles now evaporate again.

### CODE REVIEW

**Comment by calzilla1** [comment]
Whats the stun time from a puddle formed by a spray-bottle spritz?

**Comment by ghost** [comment]
> Whats the stun time from a puddle formed by a spray-bottle spritz?

You'd have to be more specific with the amount, but it caps at the old value regardless.

**Comment by calzilla1** [comment]
Sorry, I havent played since the puddle addition, but if you use a spray bottle filled with water and slip from the resulting water puddle, whats the slip duration?

**Comment by Cartlord** [comment]
The spray bottles the Jani has spray for either 5u or 10u at a time, depending on whether their pressure valve is enabled (toggled by using them in-hand).

**Pull request merged**
