### PR TITLE
Goodbye Sawbones AKA Defficiency Security Rework [finished?]

### LINKED ISSUE #8839: [Deff] Permabrig-esque area with Permabrig-esque botany and Permabrig-esque kitchen not actually Permabrig
I put an assistant in it, thinking it was Permabrig, and he just walked right out.
What the fuck @Duny-?
You mean you've made this system for Permabrig prisoners to actually do something with their time by serving other prisoners, and IT'S NOT FOR PRISONERS?

### PR DESCRIPTION
**Pull request by Konater**
Few areas I'm not totally happy with but at least I can change them later
If you have any idea how to make perma and armoury look less ass please share pictures, but I think this is ready for merge
deffsec6
Map Render - https://drive.google.com/open?id=0B_Bv_tVbIjxdRnBMZ3dVaVB1NlU
Fixes  #8839

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Someone with door hacking tools would be able to hack that maintenance door and then break into the permabrig/communal brig area by bashing through the two-tile window. It doesn't seem to have an N2O barrier like the larger window does.

I also dislike the fact that the warden can't see what's going on in the communal brig area without using the cameras.

I also suggest putting a few mounted flashers inside the communal brig area to allow the warden to flash _everyone_ inside with the push of a button. The communal brig is also the permabrig, so when you go to let a regular prisoner out, a perma prisoner is likely to attempt an escape. Much easier to flash everyone and then drag the prisoner out, and using mounted flashers saves flashbangs.

**Comment by Shadowmech88** [comment]
Also it looks like you didn't run the map cleaner, hence thousands of line changes.

**Comment by Konater** [comment]
The huge scrubbers are stationary, you can't wrench them loose. I will consider the flashers but with the pod locks and door controller it's going to be really hard for a prisoner to do anything.
Also I totally did run the cleaner

**Comment by Shadowmech88** [comment]
> The huge scrubbers are stationary, you can't wrench them loose

I have PERSONALLY unwrenched and moved the same huge scrubbers in Boxstation Toxins Storage.
They have to be on or off or you have to fiddle with the control console or something, but it IS possible to unwrench and move them.

**Comment by Imagebard** [comment]
>Goodbye Sawbones

Oh great another grudge PR. Downvoted.

**Comment by Konater** [comment]
Shadowmech there's a huge scrubber subtype that doesn't allow wrenching

**Comment by Shadowmech88** [comment]
Oh, that's fine then.

**Comment by TheFriggenSawbones** [comment]
holy shit the common jail room/whatever is actually usable

this is cool

**Comment by Kurfursten** [comment]
One way to compromise with angry wardens for putting perma directly next to public maint would be to put an X-ray camera up there. There's precedent for it, like in the AI core of Box and a few other rare places.

**Comment by Konater** [comment]
The two cameras in perma are already x-ray cameras, the bottom one can see all the cells which is why I wanted a wall in that sweet spot so badly

**Comment by Shadowmech88** [comment]
That's pretty kickass.

I wish it were possible for the Warden to work the shutter buttons without losing his camera view, though.

**Comment by ihadtoregisterforthis** [comment]
The hallway could look better on light grey.

**Comment by The-Albinobigfoot** [comment]
I really like the choice of title very nice quite good
:ok_hand: :100:

**Comment by Exxion** [comment]
What is going on with that filter and three-way digital valve in the N<sub>2</sub>O room?
You can opt to filter a gas out of the brig's air supply and into the rest of sec?

**Comment by Konater** [comment]
Oxygen filter in case of vox

**Comment by Megamaw** [comment]
how is this anti-sawbones, if i may ask?

**Comment by clusterfack** [comment]
Sawbones plays on defficiency that's how

**Comment by Konater** [comment]
GOODBYE SAWBONES

**Comment by TheFriggenSawbones** [comment]
@Megamaw 
Because i'm going to be spending all my time in jail beating inmates at hoops

**Comment by Imagebard** [comment]
@Megamaw

I really hate to explain the joke but,
The title is basically a joke on #10380 since the PR was rejected due to a side comment.

**Comment by 9600bauds** [comment]
Any objections to this?

**Comment by 9600bauds** [comment]
You can kind of get right into the armory from the HOS' office with just a wrench, and there are no shutters for that window

Make the execution bed into a chair for full electric chair

**Comment by Konater** [comment]
It's totally a feature
Actually there are shutters between the hos office and armoury/office all linked together but whatever

**Comment by 9600bauds** [comment]
i am dumb nevermind

**Comment by Konater** [comment]
You're right they're in their own room now similar to meta

**Comment by Shadowmech88** [comment]
I also don't see any shutters over the windows between the HoS office and the armory.

What am I missing? Are they underneath the window layer?

**Comment by Konater** [comment]
I promise you they're there and I don't think it's a big deal if they aren't

**Comment by Shadowmech88** [comment]
Considering how often traitors break into HoS offices via space just to take their locker, I think it's _kind of_ a big deal to make it so easy for them to break into the armory in the same trip.

If you don't want to put shutters, I think that window should at least be a reinforced plasma window or something.

**Comment by Konater** [comment]
But there are shutters there

**Comment by Shadowmech88** [comment]
That's fine then.

**Comment by Imagebard** [comment]
>that window should at least be a reinforced plasma window

Screwdriver Crowbar Screwdriver Crowbar

**Comment by Konater** [comment]
It doesn't leave you with a shard for cutting down the grille though
if it becomes an issue I'll be happy to wall it off

**Comment by 9600bauds** [comment]
I just had the brightest fucking idea
Tempered glass windows
https://youtu.be/haR_7K3BKEM?t=30s
Leaves no usable shards

**Comment by Shadowmech88** [comment]
Sounds great.

Who's going to code it?

**Comment by Konater** [comment]
If that was a thing then I wouldn't have to have used n2o

**Comment by Shadowmech88** [comment]
Merge when?

**Comment by Konater** [comment]
SOON

**Comment by 9600bauds** [comment]
Execution room needs a chair, do that in the next PR
No comments against this so woop woop

**Comment by Shadowmech88** [comment]
I think it's funny that no one mentioned the Lawgiver in the HoS's locker.

**Comment by Imagebard** [comment]
I think its funny you waited for the merge

**Comment by Shadowmech88** [comment]
I have no idea what you're implying, I _certainly_ didn't notice it until just after it got merged. Honest.

**Comment by Imagebard** [comment]
Wait is that your nerfed Lawgiver or the actual lawgiver

**Comment by 9600bauds** [comment]
whats-the-worst-that-could-happen-51ed5a34affa2

**Comment by Shadowmech88** [comment]
The standard one is the one that was nerfed.
The one that fires gyrojet rounds and laser cannon beams is now a special subtype called a demolition Lawgiver.

**Comment by Durgen** [comment]
> no cameras in the execution room

:s Don't worry AI we aren't going to harm greyshit mcmurderbone, we're just having a chat about... human stuff.

**Comment by Imagebard** [comment]
There NEVER are cameras in the execution room.

**Comment by Durgen** [comment]
Huh TIL

**Pull request merged**
