### PR TITLE
Fixes weird plasmaman suit speed

### LINKED ISSUE #8014: Some Plasmaman suits make you move slower
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d07d8b303c57f411d9eceea3f857507c89d5bc88 
> 
> General description of the issue
> im pretty sure the Librarian and some other plasmaman suits make you move slower, in comparison to the assistant suit
> 
> What you expected to happen
> going fast
> 
> What actually happened
> moving slow
> 
> Steps to reproduce if possible
> play plasmaguy
> pick librarian
> pick assistant
> notice the speed difference

### PR DESCRIPTION
**Pull request by TheFriggenSawbones**
Changes base slowdown of Plasmaman Parent suit thing to 1, changes
slowdown of Miner, Atmos, and Engineer suits to 2. Basically all just to
fix the IAA/Lawyer suit being so slow.
fixes #8014

### CODE REVIEW

**Comment by Exxion** [comment]
Two and a half hours from no Git client installed to your first PR
Not bad

**Comment by TheFriggenSawbones** [comment]
honestly i was playing video games in between and like making food

**Comment by TheFriggenSawbones** [comment]
theres still a lot im confused about and this will probably be my only pr thank you for listening

**Comment by 9600bauds** [comment]
It won't

**Comment by Exxion** [comment]
Extra not bad, then
Also :+1: for also removing the extraneous `slowdown = 1`s

**Comment by TheFriggenSawbones** [comment]
@9600bauds i'm calling you out i tested it and it worked

**Comment by Exxion** [comment]
I think he meant it wouldn't be your only PR

**Comment by TheFriggenSawbones** [comment]
im still  calling him out because im an idiot and ill end up merging something private to the repo and ill never show up again

**Comment by ghost** [comment]
Hey Sawbones, reference the issue you're fixing ( #8014 ) in the OP so it gets auto-closed, and so you're given the bugfix tag so you can get the PR merged faster

**Comment by 9600bauds** [comment]
Fucking phone

**Comment by TheFriggenSawbones** [comment]
don't you dare sabotage this i worked hard

**Comment by d3athrow** [comment]
This makes plasmaman suit have no slowdown at all but it gives full space protection still. Vox pressure suit does the same but has the slowdown still, so this is imbalanced.

**Comment by 9600bauds** [comment]
Apparently it's meant to have SOME slowdown, but slowdown = 1 seems to have no noticeable effect

**Comment by Exxion** [comment]
This actually only changes the speed of the base plasmaman suit (only ever seen on lawyers and IAAs) and the engineering plasmaman suit
All the others still have the same slowdown as before

**Comment by d3athrow** [comment]
i'm just telling you what i encountered in my test.

**Comment by Exxion** [comment]
Yes
But all the plasmamen suits except the orange one, the atmos one, and the mining one already had a slowdown of only 1

**Comment by TheFriggenSawbones** [comment]
as it stands the Default/IAA/Librarian suit is an anomaly as it provides no extra benefits at less speed. So I brought it and the engineering jumpsuit in line with the other variations.

The balance of the vox/plasmaman starting spacesuit is kinda a separate issue and i like to play by the rule of cool/fun and not worry too much about it

**Comment by ihadtoregisterforthis** [comment]
Besides vox don't need the suit on at all times to survive.

**Comment by Imagebard** [comment]
Why does the atmospheric suit have slowdown, again? If you're doing your job of stopping plasma fires you probably have less time to waste shuffling around, unlike engineers.

**Comment by clusterfack** [comment]
Because hardsuits aren't supposed to be a trade off and not the be all end all of equipment?

**Comment by ghost** [comment]
the atmos hardsuit should probably have a higher slowdown to be honest

**Comment by Imagebard** [comment]
>Hardsuits

We're talking about plasmamen suits. How the fuck can you have "trade offs" on the only clothing that you're supposed to wear? Why is that "trade off" designed to directly impact your job?

**Comment by 9600bauds** [comment]
Atmos suits would be an issue if other species could steal them and wear them, which they can't

**Comment by Exxion** [comment]
The atmos suit slowdown is not changed by this PR

**Comment by Imagebard** [comment]
@Exxion 



Excuse you

**Comment by TheFriggenSawbones** [comment]
yeah the atmos suit isn't changed.

it's at 2 currently, and in this PR it's 2.

Red/Librarian/IAA suit goes faster, Engineering suit goes slower. The only balance changes.

**Comment by Exxion** [comment]
@Imagebard You aren't a coder shut up

He added a line defining its slowdown as 2. Before, it _inherited_ a slowdown of 2. The code is changed, the effect is not. Its slowdown is unchanged.

**Comment by Imagebard** [comment]
>Yeah the atmos suit isn't changed
it's at 2 currently, and in this PR it's 2.


Are you talking about humanoid hardsuits or what? I'm pretty sure you are.
I downloaded the lastest code(Which still doesn't have this merged) and checked the files you're changing on github. You're DEFINITELY making the containment suits slower.

**Comment by Exxion** [comment]
The atmos tech plasmaman suits have no change in slowdown in this PR and I just explained why.

**Comment by PJB3005** [comment]
@imagebard you obviously don't know how inheritance works, the end result remains unchanged

**Comment by 9600bauds** [comment]
Check yourself

**Comment by Imagebard** [comment]
>Inheritance

Well, I didn't remember plasmaman suits having slowdown in first place
Good grief

**Comment by Exxion** [comment]
To be clear, the only plasmaman suits whose slowdowns are actually changed in this PR are the orange ones (technically the base one, generally seen on IAAs/lawyers/librarians) (sped up slightly) and the engineering ones (slowed down slightly)

**Comment by Exxion** [comment]
[NFD]

**Comment by TheFriggenSawbones** [comment]
i dont think this is a big change

**Comment by PJB3005** [comment]
:+1: to this personally.

**Comment by TheFriggenSawbones** [comment]
PLEASE GOD

**Comment by gbasood** [comment]
I'm sure nothing will go wrong with this, especially considering:

> This makes plasmaman suit have no slowdown at all but it gives full space protection still. Vox pressure suit does the same but has the slowdown still, so this is imbalanced.

But what the hell apparently we're good to go

**Comment by Probe1** [comment]
welcome to coding motherfucker.  it takes you 1% of the time to fix something and 99% of the time to try and get it to work.

**Comment by Exxion** [comment]
@gbasood 
1. They have 1 slowdown, not 2 slowdown
2. AS I HAVE SAID MULTIPLE TIMES, this ONLY CHANGES THE SPEED OF TWO TYPES OF PLASMAMAN SUIT AND THEY AREN'T THE COMMON ONES

**Comment by gbasood** [comment]
@Exxion By pomf said he tested it and saw what I quoted :V

**Comment by Exxion** [comment]
Look at the diff and what I just said is obviously the case

**Comment by TheFriggenSawbones** [comment]
@Probe1 what

@gbasood 

that's how it is now. I'm just fixing the Lawyer suit so it doesn't go slow as fuck, it's like an anomaly or whatever you coding dorks say.

**Pull request merged**
