### PR TITLE
vox farmbot on trader station with correct access added

### LINKED ISSUE #22745: vox can't alter farmbots
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
3a40e3639507f56e105c8d6b7521b0b9f3bcce8f

# Description
vox cannot alter farmbots that come with their station's permissions with their id.
# Steps to Reproduce
try using vox id on farmbot
# What you Expected
i would be able to unlock farmbot and alter it
# What Actually Happened
i was not able to

### PR DESCRIPTION
**Pull request by DDihanov**
[tested][box][snowmap][bufix]

Voxbros can now graden in peace on trader outpost with their new special vox farmbot which they can unlock with their ids. Also added on the snowmap and sec version of the maps. I also ran the maptools procedure, don't know why some of the files turned out this long after the clean.

closes #22745

:cl:
 * rscadd: Added vox farmbot on trader outpost which traders can now unlock with their id.

### CODE REVIEW

**Comment by jknpj** [comment]
>snowmap

**Comment by MadmanMartian** [comment]
This sorta shows a problem with bot access; sucks if a vox buys a roomba.

**Comment by beesil** [comment]
Replace the one on packed too for consistency, it has the same outpost as box.

**Comment by DDihanov** [comment]
Ask and ye shall receive!

**Comment by Kurfursten** [comment]
conflicts

**Comment by DDihanov** [comment]
Somebody made changes to packed. I need to rebase to that change, and it will show up as "bugged" again. I can't use the latest packed, because he added new changes in the code, and when I load it up dm asks me to remove the missing objects from the map - so if I compile it that way it will remove his floorpills.

**Comment by DDihanov** [comment]
Yeah this is beyond fucked. I need to make a new PR.

**Comment by brndd** [comment]
Use the map merger in the maptools folder. This is best done by setting up a merge driver for git. Read `maptools/install.txt` for instructions. This *should* allow you to just merge in the map file, because odds are your PR and the floorpills PR didn't touch the same tiles.

**Comment by DDihanov** [comment]
Yes I already did this and still there were conflicts for some reason. I will just make a fresh branch and go from there.

**Pull request closed without merging**
