### PR TITLE
No more snowcult

### LINKED ISSUE #24226: Cult really shouldn't be able to fire on snowmap
#### Description of issue

Snowmap has a TONS of places to hide, perhaps even more than roid and deff cult. The impossibility of raising an altar in the roid is null and void if you can just raise one in bumfuck nowhere in the woods

Relying on sufficient maint coverage is made impossible unless you have 5+ officers, given how far away everything is ; same for responding to calls or raiding departments

I don't even want to begin to imagine what would be bloodstone hunting on snowmap

### PR DESCRIPTION
**Pull request by ShiftyRail**
A blunt, but functioning workaround to #24226
I don't think metanarrative concerns are at play here, since changeling is already disabled on all maps but snow-taxi, blob is disabled on roid and snow-taxi as well, and people don't meta them.

Closes #24226 for the reasons listen within
Feel free to suggest any alternatives

:cl:
- tweak: Blood cult can no longer fire on Snow Taxi.

### CODE REVIEW

**Comment by DeityLink** [comment]
As far as I can tell those are the first two cult rounds on Snow station ever that just occured, also according to @MadmanMartian "this is the first time cult's rolled in quite a while" which means newblood might not be used to it yet. I think those are two good reasons to not grab so nerf hammer so soon.

It's true that the cult can technically build an altar anywhere on the Z level but the cultists still need to acquire spacesuits or warm clothing, also footprints would make a group of spessmen going somewhere in the snow much more easily noticeable, so it has its pros and cons, as opposed to building a space platform on any other map.

Lastly bloodstones cannot spawn on unsimulated turfs, so they cannot spawn on snow. If there are any simulated areas away from the station where they are spotted spawning, tell me and I'll add an exception to prevent it.

**Comment by iFlashYou** [comment]
No, dont take my chance to build a cult mansion

**Comment by ShiftyRail** [comment]
let's code a snowcult with forest witches that let you do that instead

**Comment by iFlashYou** [comment]
when you code it

**Comment by SonixApache** [comment]
yeah fuck spacebase: snow crash edition

**Comment by Kurfursten** [comment]
Permanently removing the mode after being played 2 times feels pretty REACTIONARY to me.

I think sec needs to patrol footprints more. Unlike on, say, Box where you can hide a cultbase behind a lot of access doors, no access restrictions on a spooky forest cottage.

**Comment by ShiftyRail** [comment]
Snowbases are one thing and not only the first thing that comes to my mind. 

That would rather be the impossibility of keeping track of who's alive and who's missing (something which is actually feasible in most other maps by checking in the departments) given how far away everything is, unless you spread out security (which is what snowmap encourages you to do), but this makes every officer an easy picking.

1 tile corridors everywhere in maint are just icing on the cake.

**Comment by boy2mantwicethefam** [comment]
_...metagrudge..._

**Comment by ShiftyRail** [comment]
Cult as a ms paint map

I could write a several pages essay with a thesis-antithesis-synthesis on why Cult has flaws and people wouldn't read it.

**Comment by utilitas-** [comment]
do it, I'd read it
but deity certainly wouldn't listen

**Comment by Kurfursten** [comment]
Wouldn't the bunker be somewhere else? Originally you were complaining they would bunker in the snow, now you're complaining they would bunker into one station with the last bloodstone.

They would be forced to do their ritual on at least one of the stations now that I think about it or get -1 bloodstone and have no control over the location of the rift bloodstone.

**Comment by ShiftyRail** [comment]
I never complained they would bunker in the snow. If anything I told that the snow gave them an all too easy way to escape and hide.

It's the bloodstone phase that makes snowmap absolutely awful for security, for reasons I tried to explain in this shitty map
Said map doesn't take into account the fact that some areas are extremely remote, yet ellibgible for bloodstone spawn (pod bay comes to mind), that maintenance (which you still be patrolling) is only over 1 tile wide, or that most security "offices" don't have rechargers, so you need to walk all the way to brig unless you've powergamed advanced energy guns.

**Comment by Kurfursten** [comment]
Now those are some actual good feedback ideas for snowmap in general

**Comment by plosky1** [comment]
As for more rechargers, that's already been fixed in my most current PR before this comment, although I definitely appreciate it. There's rechargers in each security checkpoint now.

I also agree with the problem of people hiding out in the trees. I almost want to make it so that jumpsuit tracking is turned on automatically for snowmap, but I know that will be hated to death. Tracking dead people (ignoring antags who are just hiding) is very difficult unless they prepare suit sensors / SPS before hand, which is unlikely.

**Comment by MadmanMartian** [comment]
I did see yesterday, somebody hiding a rune behind a tree

**Comment by DeityLink** [comment]
@ShiftyRail You know I'd read it. I love GDDs.

But let me argue that cult is more than Act 3+.

Most of the time last time I checked, Cult would lose before reaching the bloodstone phase at all. Now of course that doesn't mean we can just disregard it, but I think it'd be more interesting of giving players tools to deal with it instead of giving it the ling treatment.

An idea that'd be actually simple to implement that I've suggested a long time ago was giving the crew the location of the bloodstones a minute into Act 3. That gives the cult a bit of preparation time if they were still undetected while still giving the crew a slight edge to even the odds of winning during Act 3.

The easiest way to implement it would be to have it be a command announcement, or something printed at comms computer. Other mediums would be newscasters or Station Holomaps which could highlight the average area where stones are expected. This would of course be enabled on all maps.

**Comment by FudgePucker** [comment]
The stations being separated also boosts cult a lot. You know how entrenched the cult gets if they take over an entire department. How about an entire station.

**Comment by tuypo1** [comment]
Why do you people constantly have to ruin cults fun, who cares if they actually win on occasion

**Comment by tuypo1** [comment]
Also sure cult might have it easier in some ways since there are more places to hide but it seems to me like the lack of walls means it could also be easier to get caught by people wandering around
Can't exactly put up false walls in the middle of the snowfield either

**Comment by ShiftyRail** [comment]
I don't really care about cult winning. I care about having fun

As it stands, cult is tiring but manageable in most maps. Its flaws are multiplied by ten by the very nature of snowmap.

To clarify : cult winning or losing is not that important for me, what matters Is having a fun and balanced challenge
There is nothing fun about cult on snowmap from sec side

- Runes being hidden behind trees so I can walk over them and not see them
- altar and forges being in bumfuck nowhere, with a convenient exit/entrance path in the form of runes
- the map ENCOURAGES you to spread out and stay inside a deptartement rather than being in brig and responding to calls. Cult requires security to stay together and patrols in pairs. The map and the mode have completely different ways to play
- even if a cultist is dumb enough to not EMP my SPS before he converts me, it makes no difference because the map is so big and a bunker is so easy to defend.

In any other map I can make an effort to fight the cult before calling it. In snowmap, I have no choice but to smash that call shuttle button.

Every other course of action is an exercice in pointlessness

And this assumes that I can even see evidence of cult. Snowmap makes it very hard to keep track of who's missing, so a cult can fly under the radar for longer.

I don't mind a cult hidden inawoods (I love the concept) but the execution is just pain in the dick on every level

**Comment by incakola** [comment]
increase min sec for cult to fire on snowmap?

lower cult crew conversion threshold to trigger occult announcement?

**Comment by Blithering** [comment]
Not sure how feasible it would be, but you could give bloodstones a steadily widening cultify effect, so they give themselves away if people follow the cult tiles

**Comment by DeityLink** [comment]
@Blithering Hey that's actually a good and easily implementable idea. I'll do it tomorrow.

**Comment by tuypo1** [comment]
>spread out officers makes for easy pickings

How long does it take to convert through a loyalty implant again, just have officers report in at least that often if you suspect cult

And you can keep track of missing crew by actually enforcing suit sensors

You are right about the rechargers but that's a general mapping problem that can be easily fixed

**Comment by ShiftyRail** [comment]
not enough support for now

**Comment by SonixApache** [comment]
coward

**Pull request closed without merging**
