### PR TITLE
/me and /ooc in hotkey mode

### PR DESCRIPTION
**Pull request by Angelite191**
lets do it
Two birds, one stone.
Tested, and updated the hotkey help verb as well.
Mergey mergey asapy asapy.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Now can you figure out what's causing the lag in the hotkey switch?

**Comment by Angelite191** [comment]
Uuuh, no. I don't know anything about speed in this language.

**Comment by d3athrow** [comment]
@ComicIronic  its the azerty shit.

**Comment by Probe1** [comment]
cause people like me are too dumb d3athrow.  

thanks angelite this will be useful.  now if only we can get rid of that useless HOTKEY MODE ENABLED DISABLED ENABLED DISABLED message filling up logs..

**Comment by PJB3005** [comment]
you didn't AZERTY presets.

probe1; if the lag's that bad I can make snowflake exceptions if you want it, but it's snowflake and will be piss poor, also I can disable the feedback messages if you want

**Comment by Probe1** [comment]
@PJB3005 now I get why you brought it up in irc, I had almost forgotten about writing that.  

It annoys me to no end.  I don't need to be told I just pressed tab, it's over there in the corner and a clear decision.  Telling me is just useless information.

I didn't make an issue about it because it felt petty and unimportant. If I could snap my fingers I'd have a very to disable it or remove it outright.

**Pull request merged**
