### PR TITLE
adds holographic mimic animals for use in the holodeck

### LINKED ISSUE #14265: None of the animals in the Holodeck Zoo are holograms
I could look past the milking holocows
I could look past the farming eggs from holochickens
But corgi meat is literally an antag objective

### LINKED ISSUE #14688: Holodeck catbeasts can erase objects from existance
#### Description of issue
Anything you put on the holodeck catbeasts will be erased once you move them out of the holodeck.

#### Difference between expected and actual behavior
Stuff should not be erased, the catbeasts should keep the stuff you make them wear.

#### Steps to reproduce 
Load the holodeck zoo
Equip the catbeasts with stuff you want to erase. For example, put stuff in a backpack, put the backpack on them.
Drag the catbeasts out of the holodeck to make them despawn.
Reload the zoo, the catbeasts respawn but the stuff they were wearing is gone.
Reloading the zoo multiple times does not affect this, the stuff stays gone.

#### Length of time in which bug has been known to occur
First noticed yesterday

#### Server revision

Revision: 595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### LINKED ISSUE #14689: Holodeck animals can be transformed into "animal holder" by putting them in bolas or a cannon
#### Description of issue
The holodeck puppies and chickens transform into "animal holder" if you bring them outside inside another object. The one I noticed it with were the wheelchair cannon (load a puppy into it, fire it outside the holodeck) and the cable bolas (you can put the chickens in those).
Related: https://github.com/vgstation-coders/vgstation13/issues/14688

#### Difference between expected and actual behavior
The contents of the bolas / wheelchair cannon should be empty instead of "animal holder".

#### Steps to reproduce 
Make a wheelchair cannon
Load a corgi puppy from the holodeck into it
Fire the wheelchair cannon outside the holodeck
The cannon fires an "animal holder"

Make bolas
Insert chickens into bolas
Move bolas outside the holodeck
Examine will show the contents as: "A poorly made bolas, made out of a chicken and Pomf chicken, tied together with cable."
Cut the bolas with wirecutters: "You cut off the animal holder and the animal holder."
This results in "animal holder" objects on the floor that you can pick up

#### Specific information for locating

You cut off the animal holder and the animal holder.

#### Length of time in which bug has been known to occur

Noticed yesterday on the live server, tested today on test server

#### Server revision

Test server: Revision: d285a4411d86d707427ddbe1835ff4ae9ad5c086 
Live server: unknown, should be Revision: 595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #14689
Fixes #14265
Fixes #14688

Adds a holographic mimic mob, that you can pass a path to and it'll mimic the look of it like the holopads do with AI holograms

Can also play a little hide and seek if you possess a holographic mob, as you can click on things and assume their image

space town 37 2017-05-28 024412

:cl:
* rscadd: The holographic mobs in the holodeck are now actually holograms

### CODE REVIEW

**Comment by ghost** [comment]
Whoops wrong button, sorry probe

**Comment by ghost** [comment]
currently runtimes like a bitch when one of the animals is killed in the holodeck. DNM

**Comment by ghost** [comment]
Turns out the runtime just happens in regular game too

**Comment by Kurfursten** [comment]
Good use of gethologramicon 👍

**Comment by CptWad** [comment]
While you are at it give the sprites to the AI

**Comment by ghost** [comment]
this is using the same function that the AI uses to make its sprites.

Just the AIs sprites are limited to certain options

**Comment by Blithering** [comment]
This beats the hell out of manually adding holographic versions of everything

**Comment by Intigracy** [comment]
Any ideas on the runtime problem?

**Comment by ghost** [comment]
it just seems to be related to things associated with the holodeck that are living animals that then leave the holodeck.

Like, they're not being qdel'd properly

**Comment by Kurfursten** [comment]
Post the runtime logs

**Comment by ghost** [comment]
it's an event proc, lovely
`[21:03:06] Runtime in events.dm, line 37: Cannot read null.len
proc name: Invoke (/event/proc/Invoke)
src: /event (/event)
call stack:
/event (/event): Invoke(/list (/list))
INVOKE EVENT(/event (/event), /list (/list))
the corgi puppy (/mob/living/simple_animal/hologram/corgi_puppy): Move(the lush Grass (174,285,2) (/turf/simulated/floor/holofloor/grass), 0, 0, 0)
the corgi puppy (/mob/living/simple_animal/hologram/corgi_puppy): Move(the lush Grass (174,285,2) (/turf/simulated/floor/holofloor/grass), null)
the corgi puppy (/mob/living/simple_animal/hologram/corgi_puppy): wander move(the lush Grass (174,285,2) (/turf/simulated/floor/holofloor/grass))
the corgi puppy (/mob/living/simple_animal/hologram/corgi_puppy): Life()
Mob (/datum/subsystem/mob): fire(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing()`

and it just keeps happening

**Comment by Intigracy** [comment]
Is the thing that deletes objects that leave the holodeck an event?

**Comment by ghost** [comment]
no, it's called in process. HolodeckControl console loops through all objects affiliated with the current holodeck spawn in a list. If they're not in the holodeck they get 'derezzed' which basically just removes them from the holodeck item list and qdels them

That runtime's being called from the holodeck map that spawns as a dungeon by the now derezzed mob

**Comment by Intigracy** [comment]
I understood everything until the last paragraph.

**Comment by SonixApache** [comment]
Wait, so, does this have it's own sprites or does it just convert/overlay existing sprites?
Because if it's the latter, I'm definitely going to use it for that prismatic AI holopad idea.

**Comment by ghost** [comment]
it's the latter. Pretty fun system, but gets weird with some objects

**Comment by Lokiamis** [comment]
hi

**Comment by ghost** [comment]
hello, what brings you to this dead PR?

**Comment by SonixApache** [comment]
staffofnecromancy

**Comment by SonixApache** [comment]
I guess this isn't being merged because of the runtime that's present in Bleeding-Edge?

**Comment by Lokiamis** [comment]
I need this for an old project. It's super important.

untitled

**Comment by Kurfursten** [comment]
After the Battle of Boxstation, five catbeast soldiers are brutally impaled on spikes in a message of warning. (Nanotrasen Pictorial Corps, July 2525, Colorized)

**Comment by ihadtoregisterforthis** [comment]
When

**Pull request merged**
