### PR TITLE
Defficiency vox outpost change

### PR DESCRIPTION
**Pull request by Konater**
oh god

outpost

### CODE REVIEW

**Comment by Probe1** [comment]
WELCOME TO MAPPING ENJOY YOUR RIDE

**Comment by SysadminJeroen** [comment]
Is the entire station N2?

**Comment by Probe1** [comment]
Yeah I noticed that as well.. I don't see any new subtypes.  I have this sinking suspicion he used regular flooring everywhere.  I'm gonna try to help before he notices.

**Comment by Konater** [comment]
I swear it's nitrogen

**Comment by Probe1** [comment]
First glance in the editor its looking perfect.  I mean theres mismatching firelocks but its part of the whole "vox are run down and deff is run down so just fuck my shit up" appeal.

**Comment by Konater** [comment]
superior vox atmospherics at work

**Comment by Probe1** [comment]
Fully tested, no issues.  Ready 4 mergin.

:heart:

**Comment by xpcybic** [comment]
The weird firelocks are meant to act like doors and walls. Or you can use the fulltile ones when you're in a hurry and the onedir ones when you don't want to ZAS everyone to death.

**Pull request merged**
