### PR TITLE
Adds maximum player age to job options, assistants now have a maximum player age

### PR DESCRIPTION
**Pull request by MadmanMartian**
Something something [assistants will remember this]

:cl:
 * rscadd: Assistants now have a maximum player age.

### CODE REVIEW

**Comment by SonixApache** [comment]
testmerge it

**Comment by ComradeDispenser** [comment]
What is the maximum age?

**Comment by mentgah** [comment]
why

**Comment by bathosbathtime** [comment]
Interesting idea, but will interact strangely with the fact that we do allow alt accounts as long as they are cleared with the administration.

**Comment by Caboozles** [comment]
Isn’t this the definition of grudgecode?

**Comment by ComradeDispenser** [comment]
Time to see three roundstart mechanics every round I guess

**Comment by Shaska-** [comment]
Assistant is for beginners and people who have no intention of doing their job or living up to their responsibilities. 
If you take the assistant role away from the second group of people, aren't you just forcing them to take up positions where them slacking off and rejecting their responsibilities will negatively impact the round?

**Comment by SonixApache** [comment]
They negatively impact the round as-is anyway.
We could always just implement a Tourist job without maint access to compensate.

**Comment by aceedex** [comment]
isnt that at that point the same thing other servers do like recolor the grey jumpsuit?

**Comment by d3athrow** [comment]
bruh

**Comment by yclatious** [comment]
The assistant gang is not pleased Robo. Kindly become based again instead of onnions, you used to be cool bro.

**Comment by boy2mantwicethefam** [comment]
Greytide btfo

**Comment by FudgePucker** [comment]
Would make a good April fools joke

**Comment by Kurfursten** [comment]
Very interesting. Not sure it would actually fix anything, but interesting. I'd be game for experimental merge for a set time like week.

**Comment by vampirebat74** [comment]
Do not do this. I love greytiding. You cannot take this from me.

**Comment by Lokiamis** [comment]
Grow up

**Comment by ghost** [comment]
Make it so that there's a 50% chance it is blocked so that you have to play non assistant sometimes.

**Comment by mtpowell** [comment]
@aceedex This seems like a good idea, but what's stopping them from getting a different jumpsuit?

**Comment by cadaverouscoyote** [comment]
cool instead of shitter assistants being belligerent bums we can look forward to a bright new future of shitter mechanics, atmos techs, and scientists doing the exact same thing but with extra access and toys

**Comment by Exxion** [comment]
Incredibly good April Fools joke, but it's about five months late

**Comment by MaverickEsq** [comment]
FUCKING JOBBIES

### REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by SonixApache** [comment]
@cadaverouscoyote that's literally what those jobs already do anyway.

**Comment by ghost** [comment]
holy based

**Comment by mentgah** [comment]
time to tide as a doctor

**Comment by ShiftyRail** [comment]
is this a meme PR

**Comment by nuklearcellphoneg** [comment]
REV UP THEM JOBBANS

**Comment by AutismSpider** [comment]
> why is the server so ded
    > meanwhile...
    > we should start cracking down on assistants being shi-
    > WOW IF U BAN ASSISTANAXT IM GONA PLAY WORSE GET DABBED ON SEC GREYTIDE4LIFE THIS IS LOWRP SERB NOT MEDRP RP IS FOR GAY VOX ONLY DABS ON U AND POLYACIDS UR HED

**Comment by arc166** [comment]
> 
> 
> Make it so that there's a 50% chance it is blocked so that you have to play non assistant sometimes.

And watch as people just act like assistant on any job or kill themselves immediately. Then having to rely on admins to tell them off for daring to not play a job they never signed up for.

**Comment by DamianX** [comment]
amazing

**Comment by AutismSpider** [comment]
@arc166 nigga we have people who do that right now. 

IT TOOK TWO YEARS BAN A FAGGOT WHO WOULD PICK ONLY ATMOS AND HE WOULD LOG OUT IF HE DID NOT GET ANTAG.

**Comment by Shadowmech88** [comment]
I still played Assistant from time to time even years after I began playing.
If the problem is people who main Assistant forever and therefore "never contribute anything to the rounds" I'd rather see a maximum *frequency* rather than a maximum age.

**Comment by MadmanMartian** [comment]
Describe this maximum frequency idea.

You get x amount of assistant plays per day?

**Comment by Shadowmech88** [comment]
Either so many per day, or so many consecutively, or maybe there is a maximum number and rolling Assistant ticks it up, while rolling any other job ticks it down.

**Comment by dsfartgeg** [comment]
Should put the max freq stuff into its own issue so it doesn't get drowned out by the REEEing from this thread.

**Comment by Kammerjunk** [comment]
they say that if you can't beat something, you must join it
but I don't think they meant that since you can't remove player burnout entirely (since it's a natural part of what makes the game interesting for a lot of people), you should facilitate it

**Comment by ghost** [comment]
> 
> 
> Either so many per day, or so many consecutively, or maybe there is a maximum number and rolling Assistant ticks it up, while rolling any other job ticks it down.

I feel like this might actually have a beneficial effect on more experienced players in regards to how they approach the game, though it's hard to articulate exactly why I feel that way.

**Comment by Tehsapper** [comment]
this might be the worst PR ever
what if you /played for more than a day and still want to fuck around without any responsibilities.

**Comment by Kurfursten** [comment]
>"""worst""" PR
>not even 30 downvotes
>not even locked

sasuga #13645

Of course not my personal least favorite PR but this [manual screaming] is definitely up there for dumbest.

**Comment by kilozombie** [comment]
Clearly the solution is to make manually screaming make you into an Assistant

**Comment by anunknownentity03** [comment]
no thanks.

**Comment by SonixApache** [comment]
So where other servers get antag tokens, we get assistant tokens?

**Comment by ghost** [comment]
> 
> 
> So where other servers get antag tokens, we get assistant tokens?

It sounds more like a morality system on paper tbh

**Comment by tuypo1** [comment]
Sometimes I will want to play but think I might not be able to play for long, in such situations I don't want to take an important job slot that could go to somebody that is actually going to stick around

**Comment by Kurfursten** [comment]
Assistant replaced with terminal cancer patient slot confirmed

**Comment by tuypo1** [comment]
Actually that might be an interesting alternative to babies day out, show the terminal child a good time on the space station

**Comment by Lokiamis** [comment]
Take your kid to work day high rp when

**Comment by Probe1** [comment]
image

**Comment by Probe1** [comment]
image

**Comment by SonixApache** [comment]
coward

**Comment by Probe1** [comment]
Look at shadowmechs issue and use it as a touchstone on how to not antagonize the players with code.

**Pull request closed without merging**
