### PR TITLE
Fixes setting suit sensors through hardsuit

### LINKED ISSUE #10880: Suit sensors can be toggled through a hardsuit.
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 37bba96de73be3a926ac73422edc2186cb359141 
> 
> General description of the issue
> Other people can toggle your sensors through a hardsuit.
> 
> What you expected to happen
> To need to strip the suit first.
> 
> What actually happened
> Not needed.
> 
> Steps to reproduce if possible
> Bring up the strip menu on someone.

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes  #10880

### CODE REVIEW

**Comment by ComicIronic** [comment]
Shouldn't literally everything about the uniform be obscured by the hardsuit?

**Comment by 9600bauds** [comment]
It is, suit sensors weren't

**Comment by FudgePucker** [comment]
This just makes hardsuits EVEN better.
Power creep

**Comment by 9600bauds** [comment]
You used to not be able to strip set suit sensors at all

**Pull request merged**
