### PR TITLE
Adds Uzi & Micro-Uzi refactor/fix.

### PR DESCRIPTION
**Pull request by ghost**
[bugfix]
[sprites]
[tested]
[qol]

Added ``mini-uzi-ext-24`` to ``guns.dmi``
Added ``mini-uzi-ext-20`` to ``guns.dmi``
Added ``mini-uzi-ext-16`` to ``guns.dmi``
Added ``mini-uzi-ext-12`` to ``guns.dmi``
Added ``mini-uzi-ext-0`` to ``guns.dmi``
Added ``mini-uzi-ext-e`` to ``guns.dmi``

Added ``micro-uzi`` sprites to everything.
Resprited standard Uzi mags to display ammo count.
Fixed the microuzi code.

Refactors the names of ``mini-uzi-16`` sprites to ``mini-uzi-S-16`` in ``guns.dmi``.
Refactors the names of ``mini-uzi-16-e`` sprites to ``mini-uzi-S-e`` in ``guns.dmi``.

Thanks to @Kurfursten for pushing me to de-spaghettify my code.

:cl:
 * rscadd : Adds Uzi magazine ammo visualization.
 * rscadd : Added Micro Uzi, a more compact 9mm variant of the Mini Uzi. Barrel can be affixed with a silencer for stealthy drive-bys.
 * bugfix: Fixed Uzi turning "invisible" (missing sprites) when loaded with the extended mag.
 * bugfix: Fixed Mini-Uzi missing sprites.

### CODE REVIEW

**Comment by DDihanov** [comment]
Good shit. But I would suggest making the changelog more player friendly, since that's what they will see when they play. Just leave the rscadd and bugfix parts.

**Comment by ghost** [comment]
> 
> 
> Good shit. But I would suggest making the changelog more player friendly, since that's what they will see when they play. Just leave the rscadd and bugfix parts.

Ah, that's what I thought, thanks.

**Comment by Kurfursten** [comment]
There is a way you could do this slightly more elegantly where you just set MS to equal stored_magazine.max_ammo and change the order, then your state names become something like this:

```mini-uzi- (this is the magless state)
mini-uzi-0-16
mini-uzi-4-16
...
mini-uzi-20-24
mini-uzi-24-24
```

That being said, I think this is reasonably written enough

**Comment by ghost** [comment]
> 
> 
> There is a way you could do this slightly more elegantly where you just set MS to equal stored_magazine.max_ammo and change the order, then your state names become something like this:
> 
> ```
> mini-uzi-0-16
> mini-uzi-4-16
> ...
> mini-uzi-20-24
> mini-uzi-24-24
> ```
> 
> That being said, I think this is reasonably written enough

That's really good. I'll make a new PR as a low priority with those changes.

**Pull request merged**
