### PR TITLE
Adds knight armour

### PR DESCRIPTION
**Pull request by doobiedoo23**
Deus vult, purge the heretic!

Adds five sets of medieval armour. The templar armour has been added to the PietyVend, have fun starting a new crusade. In addition. this adds a crate to Cargo that includes the new armour, which costs just a bit more than a riot armor crate.

Sprite credit to Ausops and Dorisdwarfs at TG.
Templar armour sprites:
https://cloud.githubusercontent.com/assets/9773577/11448538/5580bb74-9528-11e5-89c9-05b4310944c8.png
Mob sprites for each set of armour:
http://puu.sh/lAZum/0784feb714.png

### CODE REVIEW

**Comment by Zth--** [comment]
God damn those sprites are a solid 10/10

**Comment by unid15** [comment]
:+1: :100:

**Comment by ghost** [comment]
:+1:

**Comment by sonime** [comment]
I do have an issue with riot armor being available at the PietyVend.

**Comment by Shadowmech88** [comment]
> color-coded armors

Knight team deathmatch mode when?

**Comment by AutismSpider** [comment]
@sonime And R&D can make armor that has 90% Melee res/ballistic people are fine with that

**Comment by Imagebard** [comment]
@AutismSpider 
Iamgoofball removed that, resists are down to 60% or less, a huge nerf.

**Comment by 9600bauds** [comment]
> those sprites

My gonads

**Comment by clusterfack** [comment]
Must everything be available in cargo

**Comment by doobiedoo23** [comment]
@sonime I can always just edit the damage resistance.
@clusterfack The knight armour is only obtainable through cargo. On the other hand, you can only get templar armour from the PietyVend.

**Comment by AutismSpider** [comment]
Cut the Damage resistance it has by half should be fine

**Comment by Arthurdentist** [comment]
if the armour is to be in the piety vend it should at least be premium content or hacked content.

**Comment by doobiedoo23** [comment]
for people who don't want to click the lil button beside the fixes commit

-Knight armour resistances are halved.
-Templar armour is now only available as a premium item from the PietyVend.

**Comment by sonime** [comment]
There, now this is something I can get behind.

**Comment by Imagebard** [comment]
Wait what
The damage resistance was already pretty small, but now its half? 20 melee resist?
Why is that?

**Comment by sonime** [comment]
@Imagebard Probably because it's now a child of standard armor instead of RIOT armor.

**Comment by Imagebard** [comment]
Nevermind, apparently the damage resistance nerf is only for helmets.
I still don't like it too much. since a lot of people aim for the head, and the armor looks really good. Is there nothing that can be done about it?

**Comment by icantthinkofanameritenow** [comment]
The problem is that WE ALREADY HAVE KNIGHT ARMOR WITH SPRITES, STATS, AND EVERYTHING, and in three different flavors no less. (And it's spaceworthy too, so it's objectively better than this new addition. Hell, the Solaire armor has higher laser resistance than the fucking Ablative Armor.)

God damn, you guys have to look at the resources already in the game before adding new ones, you'd be surprised how much unused crap there is in there. 

/obj/item/clothing/head/helmet/space/rig/knight
/obj/item/clothing/suit/space/rig/knight
/obj/item/clothing/head/helmet/space/rig/knight/black
/obj/item/clothing/suit/space/rig/knight/black
/obj/item/clothing/head/helmet/space/rig/knight/solaire
/obj/item/clothing/suit/space/rig/knight/solaire

**Comment by Imagebard** [comment]
Those knight armors are already in-game, though. Those are adminbus only.

**Comment by Imagebard** [comment]
>Controversial

What is it now

**Comment by N3X15** [comment]
nvm missed the comment where you fixed the pietyvend thing

**Comment by AutismSpider** [comment]
@icantthinkofanameritenow 

That is set of adminbus only armor made by niggly they act like space suits on top of having high res

**Pull request merged**
