### PR TITLE
Revert "Taser/Egun projectile nerf" as promised

### PR DESCRIPTION
**Pull request by Intigracy**
Reverts vgstation-coders/vgstation13#20392
as per what I wrote in its changelog

feel free to use this PR to ~~bitch~~ provide feedback about the change

Don't merge this until this countdown expires on Saturday Nov 3: https://www.timeanddate.com/countdown/generic?p0=137&iso=20181103T14&year=2018&month=11&day=3&hour=14&min=0&sec=0&msg=Revert%20Stun%20Change&csz=1

### CODE REVIEW

**Comment by Reviire** [comment]
The change really doesn't address any of the differences between tasers, lasers and projectiles. Think of it this way, a taser is functionally a 100 damage projectile that ignores all armor. The opposing player needs to land multiple hits on you to down you, while you only need one. 

Changing the stun to be a delay only shifts how long it takes to do this damage, which rather than giving them their own unique role in laser vs projectile vs taser, is just making them less viable against those weapons. Consider this, if you could down someone with a laser gun in the time it takes for the taser stun to apply, why would you ever use a taser? Of course there's armor to take into account, but then we're just back to tasers being the king of all weapons because they completely ignore armor. 

I think the best change here would be to just globally nerf all stuns, then add a new type of CC that fills the old role stuns had, one which won't see much use, except say, stun batons. Stuns need to have their own niche and utility that separates them from lethal weapons, rather than being another flavor of those weapons.

**Comment by SirSkeleto** [comment]
> The change really doesn't address any of the differences between tasers, lasers and projectiles. Think of it this way, a taser is functionally a 100 damage projectile that ignores all armor. The opposing player needs to land multiple hits on you to down you, while you only need one.
> 
> Changing the stun to be a delay only shifts how long it takes to do this damage, which rather than giving them their own unique role in laser vs projectile vs taser, is just making them less viable against those weapons. Consider this, if you could down someone with a laser gun in the time it takes for the taser stun to apply, why would you ever use a taser? Of course there's armor to take into account, but then we're just back to tasers being the king of all weapons because they completely ignore armor.
> 
> I think the best change here would be to just globally nerf all stuns, then add a new type of CC that fills the old role stuns had, one which won't see much use, except say, stun batons. Stuns need to have their own niche and utility that separates them from lethal weapons, rather than being another flavor of those weapons.

You don't even play the game lol

**Comment by Caboozles** [comment]
Nerfing all stuns sounds fun until you try and combat someone with an egun without armory access.

**Comment by Pathid** [comment]
My two cents on this is it's not a just a stuns problem, it's a stuns-and-lasers problem.

**Comment by SirSkeleto** [comment]
We could switch to the other servers option of it requiring multiple hits with a "stunning projectile" to actually cause knockdown. It's a decent solution IMO.

**Comment by Exxion** [comment]
To do that:
1. Improve pain to make it not suck
2. Make tasers just deal tons of pain

**Comment by ghost** [comment]
I experimented with pain, 100 agony isnt even enough to put someone in paincrit.

**Comment by Exxion** [comment]
Yeah that's why pain would have to be improved to not suck first

**Comment by Pathid** [comment]
Pain via agony/halloss just isn't implimented in a way that would work for this. But it could be.

**Comment by TheFriggenSawbones** [comment]
weaklings, all of you

**Comment by Blithering** [comment]
I don't like the idea of moving tasers over to pain, mostly because it ignores all the non-taser based stuns that are used. Nerfing specifically tasers puts all antagonists (besides revolutionaries I guess) at an extreme advantage

**Comment by DeityLink** [comment]
@Kyunny Wouldn't that be a bug?

**Comment by SonixApache** [comment]
i liked it
t. sec

**Pull request merged**
