### PR TITLE
Add Perma Wing Meteor Shielding

### LINKED ISSUE #5129: (WEB REPORT BY: Anonymous REMOTE: ) medbay door buttons
>Revision 271ee545e5885b206bd72b823a9a6cab3638b9f0

>General description of the issue
Medbat buttons are no longer in the right place.  I blame dylan.

>What you expected to happen
Mapping not to get fucked up

>What actually happened

Got fucked up
>Steps to reproduce if possible

Load box station

### LINKED ISSUE #5175: (WEB REPORT BY: Anonymous REMOTE: ) Toxins wiring
>Revision cf24a5bc1d4626513d98157fd6cbbe81d3b4d22f 

>General description of the issue

Looks as though the wiring to toxins is screwed up and the power is off

>What you expected to happen
Power to work properly

>What actually happened
Toxins is dark and without power and lighting

>Steps to reproduce if possible
Happens every single round so far as I have seen, just launch a round and it should be there

### LINKED ISSUE #5177: Info for Mappers
I assume this means something for mappers, information from box station map camera debugging

### LINKED ISSUE #5180: Box dorms wire missing.
A mapper in their infinite wisdom deleted a wire under a door to the dorms apc.  It isolates the dorms from the net.

ss 2015-06-28 at 10 04 58

### LINKED ISSUE #5196: (WEB REPORT BY: Anonymous REMOTE: ) Missing wires in Toxins mixing room
>Revision (Should be above if you're viewing this from ingame!)

Revision: 71b0b35fca55a99b25fd3a8858fe7af16b79fcbd 
>General description of the issue

http://puu.sh/iHJIj/7690154b5b.png

>What you expected to happen

A wire to spawn there

>What actually happened

NO WIRE!

>Steps to reproduce if possible

Just remove the tile and it's not there

### PR DESCRIPTION
**Pull request by ghost**
After seeing how efficient meteor shielding has been to prevent loose singularities and detonated supermatter shards, Security has put greyshits and permanent prisoners to work to create rudimentary meteor shielding to surround Perma

This shielding is composed of reinforced wall corners and grilles, and is supported by lattices. Some existing anchor points had to be moved to allow seamless building while shielding perma itself as much as possible from meteor blasts

The shield extends from Execution to the north of the Firing Range. Originally, it was supposed to surround all of Security, but the hired greyshits rioted and the project was cut short. In the meantime, it should prove useful to protect most of Perma from being blasted to bits by meteors

Screenshot : 

secshield

Other changes : 
- Fixed a broken lightbulb in Atmospheric's air tank
- Removed a light tube in the Mine area, replaced with lantern
- Cameras in Telescience are now tagged "Telescience". The Miscellaneous Lab has stopped existing for a long, long while in the mind of all players
- Fix two missing wires, caused by firelock retoolings

Fixes #5196
Fixes #5180 
Fixes #5177
Fixes #5175
Fixes #5129

### CODE REVIEW

**Comment by FudgePucker** [comment]
As someone who plays engineer this is a good update.
FUCK having to go fix up perma brig or execution chamber.
You have to go though like 6 airlocks you don't have access to, to fix up and repressure a room with just one vent, the atmos source for air is in maintenance on the other side and has a manual valve so the AI can't open it for you, and the rooms aren't even used.
Last time I tried to fix up execution chamber, the shuttle was called in the middle of it, and I just fucking gave up when the pressure in the airpump set up I had linked to brigs distro peaked at 12kpa and the shuttle was 3 mins from docking to station.

**Comment by IratePirate** [comment]
I remember a guy who added greeble all over the outside of the station and then lost it all in due to someone overwriting the entire map. We've come a long way since then..

**Comment by Intigracy** [comment]
fixes #5196

Can this be merged anytime soon to fix these power issues?

**Comment by FudgePucker** [comment]
This adds a very very very useful yet not OP addition to the map, and fixes about five bugs, merge when?

**Comment by dylanstrategie** [comment]
When Pomf gets down to it

**Pull request merged**
