### PR TITLE
removes about half of the random potted plant sprites

### PR DESCRIPTION
**Pull request by SirSkeleto**
[tweak]
they look really really ugly and not uniform and they take the magic out of xenoarch

### CODE REVIEW

**Comment by DrSnips** [comment]
I'd like to suggest a few things.
* Not outright removing the decommissioned sprites and slapping an "-unused" on the ones that apply.
* A quick image in the op showing which ones are staying and which ones are leaving.
* I'd personally like the flat dead one to stay in rotation. Maybe a different pot would help.
Other than those few things it's nice to see them have some consistency

**Comment by ghost** [comment]
I think they look fine, how are they taking out the magic out of xenoarch? They're clearly artificial and do not need any watering or care.

**Comment by Kurfursten** [comment]
Skeleto is somewhat confused here which is why he's saying they take the magic out of Xenoarch. We've always had those alien potted plant sprites, but about 3.5 years ago, Deity turned some of them into real plants you can find inside fossils on the roid in #5998 when he wanted to make normal plants pottable.

Anyway this is gonna be a 👎 from me because it removes my favorite potted plant, plant-14
plant-14

**Comment by Riekland** [comment]
unifying the pots would be appreciated but all those alien plants help make it feel like the year 2525 to me

**Comment by KingofHONK** [comment]
>making a thinly veiled clown nerf PR
Wtf i hate skeleto now
solidsnek

**Comment by Goldsteel** [comment]
Counterpoint: More plant sprites including things like yucca, flowering cactus, roses and colourful things.

**Comment by SirSkeleto** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Pull request closed without merging**
