### PR TITLE
Tinfoil hats prevent AI tracking

### LINKED ISSUE #27171: Tinfoil Hat should prevent AI tracking
It already blocks being seen on huds. It'd be nice if in `camera/tracking.dm` in `can_track_atom` at L169 it would also reject tracking if wearing a tinfoil hat (`/obj/item/clothing/head/tinfoil`).

### PR DESCRIPTION
**Pull request by gurfan**
Closes #27171 

There aren't any items that prevent tracking besides the ninja glove and a couple syndicate items. Since the tinfoil hat already blocks things like mindswap and HUDs, why not make it so it can be used to avoid the eye in the sky as well?

[tweak]

:cl:
 * tweak: Tinfoil hats will now prevent the AI from tracking you.

### CODE REVIEW

**Comment by twirling-jesters** [comment]
perfect

**Comment by boy2mantwicethefam** [comment]
Finally, now you can stop THEM from tracking you

**Comment by dunsel-hordon** [comment]
wearing a balaclava and no id should stop ai tracking. Is there no way to change how the ai's tracker works? Seems really dumb that it can go oh look unknown and i know who it is cause memes.

**Comment by TGFH** [comment]
Shittercreep.

**Pull request merged**
