### PR TITLE
Moves pill colors to main chemmaster menu via ugly CSS

### LINKED ISSUE #11088: ChemMaster 3000 Pill types
#### Description of issue

I believe color coding pills, at least for bicaridine, kelo/derma, antitoxin, and dex/dplus to be effective, but when I talked to others about it, they won't, literally because it takes two extra clicks.
#### Difference between expected and actual behavior

They seemed lazy but I expected logic to win through since it makes sense but
#### Steps to reproduce

Understand that color-coding pills is fairly simple when you think like, a bicaridine pill heals brute, brute is red colored text when you scan someone, so if someone puts all the different types in one bottle for their pocket, it's easy to differentiate between the pills. Once you understand this, explain it to a powergamer. They will freak out and call it retarded and slow because it takes two extra clicks per pill-type.
#### Specific information for locating

Reeeeeeeeeeeeee agents- wait, no, chemmasters.
#### Length of time in which bug has been known to occur

Time immemorial
#### Server revision

N-now.

---

Instead of a separate menu for pill types, can we just have all the different sprites listed across the interface like:

---

THIS IS UR BEAKER

THIS IS THE CHEMS IN THE MACHINE

[PILL] [PILL] [PILL] [PILL] [PILL] [PILL] [PILL]

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #11088 

At least 90% of the time spent on this PR was clumsily trying to piece together this ass-abomination CSS running on the abysmally old IE version BYOND works on and compiling inbetween every change
Also - rscadd: "ChemMasters will now remember the last amount of pills and bottles created, making that the default input."

### CODE REVIEW

**Comment by Fruktlimpa** [comment]
Wanna bet that lazy people will still not change the pill color? Despite it being one click now instead of two.

**Comment by clusterfack** [comment]
Does the chem master still lag from loading all the icons when you first open it? (And if so couldn't we convert all the pill icons to base 64 text and send them that way?)

**Comment by 9600bauds** [comment]
Same as before
I cannot answer the second half of that sentence

**Comment by clusterfack** [comment]
Bicon is an example of it,  you can convert the icon to a string and just send that instead of sending it as an icon

**Comment by PJB3005** [comment]
Yeah where you would insert the image tag just do `bicon()`, check `browserOutput.dm`

**Comment by clusterfack** [comment]
I don't know if it would REALLY be faster but would be cool if it was

**Comment by 9600bauds** [comment]
The problem here would be that the pill icons are not global
Unless we still want the icon to be generated once for every user we'd have to populate all the pill icons somewhere

**Comment by PJB3005** [comment]
Bicon caches the base64 strings so no that wouldn't be an issue.

**Comment by 9600bauds** [comment]
Yes but we need to generate the icons at SOME point

**Comment by 9600bauds** [comment]
Looking at html interfaces now, they seem to use register_asset() instead

**Comment by clusterfack** [comment]
Oh wow you did it you absolute madman, great job

**Pull request merged**
