### PR TITLE
Removes Undertale and Homestuck references.

### PR DESCRIPTION
**Pull request by NigglyWiggly**
We need a new meme PR.

### CODE REVIEW

**Comment by carshalash** [comment]
You forgot about the homestuck bible son. You fucked up niggly.

**Comment by NigglyWiggly** [comment]
Wait there's a fucking homestuck bible?
What is it called?

**Comment by Senaat1** [comment]
:-1: it's a meme pr why would you remove this

**Comment by ihadtoregisterforthis** [comment]
And the meteor gun from what I heard on the complaints of a _Celt bus_

**Comment by carshalash** [comment]
Meteor gun?

**Comment by 9600bauds** [comment]
This just makes it so that if the painting randomly rolls to be "flowey" it will be erroring instead

**Comment by NigglyWiggly** [comment]
Quiet you.

**Comment by 9600bauds** [comment]
you need to remove it from the list of available paintings u dolt

**Comment by Exxion** [comment]
The cueball hat and white suit are also Homestuck references
The SORD too
There are a lot

**Comment by Gringonius** [comment]
Can we remove all 2hu references too? Let's keep the witch-hunt going.

**Comment by carshalash** [comment]
Keep the white suit and remove the cueball hat, white suits are cool.

**Comment by TheEliminator16** [comment]
Let's remove references to anything that isn't science fiction related

**Comment by Boxe** [comment]
:eggplant:

**Comment by NigglyWiggly** [comment]
Oh yeah I forgot the cueball and suit and the fucking sord
Shit how many fucking homestuck references are there, god damn

**Comment by Imagebard** [comment]
The homestuck bible is the black one one with rainbow paint on it

**Comment by ihadtoregisterforthis** [comment]
:man_with_turban:　　| :man_with_turban: :cow2: 
:man_with_turban:  :toilet: | :busstop: :hankey:

**Comment by TheEliminator16** [comment]
GREAT JOB MORON YOU FUCKED IT ALL UP

**Comment by 9600bauds** [comment]
you didn't remove them from the vending machinesssss

**Comment by Imagebard** [comment]
DORK
Also did you remove the chance to get the candy corn horns genes too or just the images

**Comment by CptWad** [comment]
im ok with this
i sorta liked the cueball helmet thing even if I never watched to homosuck. Green glowy effect was always neat for me

**Comment by TheEliminator16** [comment]
Just resprite the horns to be black or grey

**Comment by NigglyWiggly** [comment]
> you didn't remove them from the vending machinesssss

Oh yeah fuck

> Also did you remove the chance to get the candy corn horns genes too or just the images
> Neither, I changed the horns to be all red like devil horns.

I could change em to be white like bone or something

**Comment by Imagebard** [comment]
Devil Horns is okay I guess

Also nice spacing

**Comment by Imagebard** [comment]
>Senaat1 reacted with the confused emoticon
But ALSO reacted with the thumbs up emoticon

Wew

**Comment by CptWad** [comment]
Red horns are fine.

**Comment by Boxe** [comment]
oh so those genetic horns are homestuck?

i thought they were supposed to be fucked up bike horns that sprout out of your head

**Comment by ihadtoregisterforthis** [comment]
Sprite another set of horns altogether

**Comment by Brolaire** [comment]
AYO HOL UP WE WUZ KIIIIIIING
N
🍆🍆🍆🍆

**Comment by 9600bauds** [comment]
niggly I advise you to try compiling before pushing your commits

**Comment by NigglyWiggly** [comment]
You are implying that this is a legitimate PR that I actually hope to get merged.

<sub>(It's not)

**Comment by Imagebard** [comment]
Are you implying that this is a illegitimate PR

**Comment by Boxe** [comment]
:egg: :seedling:

**Comment by Probe1** [comment]
```

loading vgstation13.dme
loading interface\skin.dmf
code\game\objects\items\weapons\gift_wrappaper.dm:104:error: /obj/item/weapon/sord: undefined type path
code\modules\maps\spawners\set_spawners.dm:72:error: /obj/item/clothing/under/scratch: undefined type path
code\modules\maps\spawners\set_spawners.dm:73:error: /obj/item/clothing/head/cueball: undefined type path


```

**Comment by NigglyWiggly** [comment]
> Are you implying that this is a illegitimate PR

That is exactly what I am implying.

**Comment by xpcybic** [comment]
dude
...
...
...
NICE

**Comment by ihadtoregisterforthis** [comment]
one day perhaps

**Comment by Imagebard** [comment]
NIGGLY STOP MEMEING
THIS PR IS HIGHLY ACCLAIMED
HALF OF THE COMMUNITY WANTS IT MERGED

>Feature Loss

Its commented out instead of being deleted, doesn't count

**Comment by Boxe** [comment]
:eggplant:

**Comment by Boxe** [comment]
:eggplant: :computer:

**Comment by Boxe** [comment]
:eggplant: :pill:

**Comment by Boxe** [comment]
:eggplant: :egg:

**Comment by Probe1** [comment]
:eggplant: :8ball: 

Your lucky message is:  Compile again later.

**Comment by 9600bauds** [comment]
ah yes the good ol' "[rush a PR that I don't want to see happen to use it as a bad precedent if anyone actually tries to do it seriously](https://github.com/d3athrow/vgstation13/pull/8493)" tactic

**Comment by Imagebard** [comment]
Merge this whenever possible

c1a11dc4419dc1ce1b0c186557e9154d414079cc

**Comment by gbasood** [comment]
> 31 minutes ago
> 
> 44 comments

this is what we have become
more interested in memes than video games

**Comment by 9600bauds** [comment]
> Its commented out instead of being deleted, doesn't count

This is just asinine

**Comment by Brolaire** [comment]
dude my current favorite meme is gondola, ever seen it? its a spurdo with only legs

**Comment by NigglyWiggly** [comment]
Can someone make a PR to comment out PJB

**Comment by PJB3005** [comment]
No.

**Comment by NigglyWiggly** [comment]
*/

**Comment by Brolaire** [comment]
lmao

**Comment by ghost** [comment]
RIP Cueball helmet, always thought it was a spaceballs reference

**Comment by kol1th** [comment]
upvoted

**Comment by PJB3005** [comment]
``` DM
#define NigglyWiggly PJB3005 //override NigglyWiggly
```

**Comment by Boxe** [comment]
*/ gay jail ends here

**Comment by PJB3005** [comment]
Nope you have no `/*`

**Comment by 9600bauds** [comment]
firefox_2016-04-22_20-55-28
So if we comment out niggly, it will comment you out two times?

**Comment by PJB3005** [comment]
Nope, you'll comment out my evil clone.

**Comment by Boxe** [comment]
if i comment you out, will you die?

**Comment by kol1th** [comment]
@Boxe it would be extremely painful

**Comment by Boxe** [comment]
you're a big line

**Comment by gobblecoque** [comment]
can we keep cueball

**Comment by PJB3005** [comment]
No, my implementation is private, can't comment that out.

**Comment by KingCrimsonIJW** [comment]
I have never seen an UT reference, only Flowey
I don't think UT is MLP tier, i get the hate to the fanbase, and how memey are some characters, but its not a horrible game
Just FUCKING DELETE DRESSES AND CROSSDRESS BAIT YOU FUCKING RETARDS

**Comment by carshalash** [comment]
If they did that how would we get crossdressing kingcrimson?

**Comment by d3athrow** [comment]
niggly i know you're gay but stop being such a fag

**Comment by NigglyWiggly** [comment]
I don't even hate UT.
In fact I really like UT.
I just feel like it stands on its own as a game, and certainly doesn't need, or warrant and appearance in spess.

> Just FUCKING DELETE DRESSES AND CROSSDRESS BAIT YOU FUCKING RETARDS

N o

**Comment by kol1th** [comment]
> Just FUCKING DELETE DRESSES AND CROSSDRESS BAIT YOU FUCKING RETARDS

N O

**Comment by Probe1** [comment]
OH SHIT

**Comment by Imagebard** [comment]
>Just FUCKING DELETE DRESSES AND CROSSDRESS BAIT YOU FUCKING RETARDS 

no bye

**Comment by KingCrimsonIJW** [comment]
THE DRESSES ARE ONLY CROSSDRESSING SHIT OR RETARDED LITERAL WHITE KNIGHTERY CARGONIA SHIT OR FUCKING WAIFUSHITTER SHIT THAT LOOKS RETARDED ANYWAYS
REMOVE REMOVE REMOVE

**Comment by KingCrimsonIJW** [comment]
I'M HAVING A FUCKING STROKE YOU NIGGERS

**Comment by ghost** [comment]
Calm down luv

**Comment by kol1th** [comment]
> THE DRESSES ARE ONLY CROSSDRESSING SHIT OR RETARDED LITERAL WHITE KNIGHTERY CARGONIA SHIT OR FUCKING WAIFUSHITTER SHIT THAT LOOKS RETARDED ANYWAYS
> REMOVE REMOVE REMOVE

i think u need to take a break family

if they're that big of a problem dont use them. when's the last time you saw someone order the feminine formalwear crate?

**Comment by NigglyWiggly** [comment]
You know what I should do to fix that Crimson.

Make skirts and dresses wearable only by male characters.

**Comment by Konater** [comment]
Better idea, add a way to get the hair flower pin and keyhole sweater

**Comment by 9600bauds** [comment]
I think we have conclusively proven all of today was just tribalism and double standards

**Comment by Arthurdentist** [comment]
This whole PR and comment chain really is something 
alright wow

**Comment by KingCrimsonIJW** [comment]
I was just joking
I haven't seen them in a while
But they are always horrible to see

**Comment by NigglyWiggly** [comment]
I'm going to go get dinner. There better be some fucking platinum memes here when I get back <sub> and close this PR.

**Comment by 9600bauds** [comment]
you close it

**Comment by kol1th** [comment]
> Better idea, add a way to get the hair flower pin and keyhole sweater

this

**Comment by NigglyWiggly** [comment]
That's what I was fucking saying you turbonerd, when I get back and then close this PR.

**Comment by clusterfack** [comment]
Oh a compiling PR that has ever so slightly more upvotes than downvotes? I guess I should just come in here and merge it without looking into any context.

**Comment by 9600bauds** [comment]
But was it 100% tested?

**Comment by clusterfack** [comment]
I'm sure it doesn't matter!

**Comment by Imagebard** [comment]
> I guess I should just come in here and merge it without looking into any context.

You say this like you're innocent

**Comment by Boxe** [comment]
>Oh a compiling PR that has ever so slightly more upvotes than downvotes? I guess I should just come in here and merge it without looking into any context.

https://github.com/d3athrow/vgstation13/pull/9033

**Comment by clusterfack** [comment]
Jokes on you because that had an even number of upvotes and downvotes

**Comment by Boxe** [comment]
>Jokes on you because that had an even number of upvotes and downvotes

:eggplant:

**Comment by Senaat1** [comment]
didn't everyone just vote both options? that's what i did

**Comment by clusterfack** [comment]
I also heavily commented on it to get code edits but your version of events is more humorous

**Comment by chatsonf** [comment]
Alright next on the list is removing xenos, aliens was a bad movie.
:trollface:

**Comment by clusterfack** [comment]
Get to it

**Comment by clusterfack** [comment]
Anything reference to material whose source you dislike is now fair game for immediate removal. The chicken has spoken.

**Comment by PJB3005** [comment]
I already got all removal covered.

**Comment by ihadtoregisterforthis** [comment]
<sub>:goof:</sub>　　|<sub>:goof:</sub> :tangerine:
<sub>:goof:</sub> :chicken: | :spaghetti: <sub>:goof:</sub>

**Comment by Probe1** [comment]
why is goofball having the miscarriage

**Comment by Senaat1** [comment]
goofball IS the miscarraige

**Comment by Probe1** [comment]
holy shit senaat 3 seconds after I post

**Comment by Senaat1** [comment]
so what

**Comment by Probe1** [comment]
too dank

**Comment by ihadtoregisterforthis** [comment]
For you

**Comment by Senaat1** [comment]
you're dank <3 c: :eggplant:

**Comment by NigglyWiggly** [comment]
Okay good job you had some nice memes now it's time to die.

**Comment by Senaat1** [comment]
boo

**Comment by Gringonius** [comment]
OPEN THIS

**Comment by NigglyWiggly** [comment]
Why did you do th

**Comment by Senaat1** [comment]
open it again uncle pjb

**Comment by NigglyWiggly** [comment]
oh what okay

**Comment by Exxion** [comment]
Your memes end here

**Comment by Probe1** [comment]
:eggplant:

**Comment by clusterfack** [comment]
We'll just have to open it and merge it at the same time

**Comment by kol1th** [comment]
DELETE THIS

**Comment by PJB3005** [comment]
Closest to deleting, sorry.

**Comment by clusterfack** [comment]
WOW THE METACLUB IS REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAL

**Comment by PJB3005** [comment]
Joke's on you I can always git fetch the PR and recreate it!

**Comment by 9600bauds** [comment]
the memes never die

**Comment by kol1th** [comment]
wow he deleted it what a fag

**Comment by NigglyWiggly** [comment]
Your memes end here

**Comment by Senaat1** [comment]
:(

**Comment by ihadtoregisterforthis** [comment]
dare you enter my magical pr
tongue_smile

**Comment by Exxion** [comment]
Did you just upload your own smiley?
What is this, 2006?

**Comment by ihadtoregisterforthis** [comment]
devil_smile

**Comment by SangriaMonkey** [comment]
:eggplant:

**Comment by Senaat1** [comment]
:eggplant:

**Comment by Probe1** [comment]
:eggplant:

**Comment by kol1th** [comment]
:eggplant:

**Comment by Iamgoofball** [comment]
> loss: goofball edition

:+1:

**Comment by ihadtoregisterforthis** [comment]
@Iamgoofball Save the icon if you want but it will need to be between `<sub> </sub>` to be inline with the others.

**Comment by Imagebard** [comment]
I don't like niggly anymore.

**Comment by Iamgoofball** [comment]
Thanks babe <3

**Comment by NigglyWiggly** [comment]
I love you, @Imagebard

**Comment by TheEliminator16** [comment]
Memes were a mistake.

**Comment by kol1th** [comment]
i am very disappointed in all of you.

**Comment by TheFriggenSawbones** [comment]
`[how the fuck do i insertr images]`

**Comment by Exxion** [comment]
Smash that motherfucking Markdown tutorial button below the comment box

**Pull request closed without merging**
