### PR TITLE
WHY

### PR DESCRIPTION
**Pull request by gbasood**
please work

### CODE REVIEW

**Comment by 9600bauds** [comment]
what is this witchery??

**Comment by gbasood** [comment]
I added a check to see if DreamMaker doesn't exist after building BYOND
If it fails I'll know sort of why travis is failing and from there I'll rework shit to make it work if I even can figure out HOW

**Comment by ghost** [comment]
What

**Comment by 9600bauds** [comment]
Leave the madman to his esoteric arts

**Comment by gbasood** [comment]
caching issues I guess
even though I disabled the cache and it was still failing
fuck it I tried

**Pull request closed without merging**
