### PR TITLE
Fax machines, wooden TVs, laptops, library computers can pass over tables

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * tweak: Fax machines, wooden TVs, laptops, library computers and boomboxes can pass over tables.

### CODE REVIEW

**Comment by ComradeDispenser** [comment]
Can you make grinders do it too? Most grinders start on tables anyway, having to build a table under your grinder is ass backwards.

**Comment by DamianX** [comment]
I don't know why you all think you can't do that
https://github.com/vgstation-coders/vgstation13/pull/23061#issuecomment-496370043

**Comment by tuypo1** [comment]
boomboxs please

**Comment by tuypo1** [comment]
Based and dare I say it, beatpilled

**Pull request merged**
