### PR TITLE
Removes camera in Box Ghetto Bar

### PR DESCRIPTION
**Pull request by Kharkov72**
>Be broken down, dilapidated bar
>Can't even get in without a crowbar
>Still have functional camera even without power
🤔 

I plan to go through all the maps with this but I'm testing the waters with just box. If this goes through, I'll do the same with the rest of the maps that have applicable ghetto bars in a separate PR.

Untitled

Update: Also adds a camera assembly to aux tool storage as per request for those who wish to add one to their bar.

[box] [controversial] [tested] [discussion]

:cl:
 * tweak: Box Ghetto Bar no longer has a camera.

### CODE REVIEW

**Comment by kilozombie** [comment]
That original title is pretty postmodern

**Comment by brndd** [comment]
Even hotter take: cameras don't work if the APC is unpowered (this would require relatively massive changes to do though, since there are some cameras on exterior walls and such that have no APC associated with them, so it's a terrible idea)

**Comment by Kitfox88** [comment]
please god no playing ai is already a living hell enough as it is

**Comment by brndd** [comment]
> please god no playing ai is already a living hell enough as it is

And AI players are known to be masochists. I say this as someone who plays a fair bit of AI.

**Comment by SonixApache** [comment]
AI here, not a masochist.

**Comment by iFlashYou** [comment]
>NOO DONT REMOVE MY VALID DETECTORS

t.all shitter AI's

**Comment by Kitfox88** [comment]
lern 2 cut cams loser

**Comment by FudgePucker** [comment]
"Just cut the cameras"
And then the AI notices a blind spot in its vision
":s Ghetto bar's cameras cut, go collect valids"
Or
Warden notices ghetto bar isn't in the list of cameras
":s Ghetto bar's cameras cut, go collect valids"

**Comment by Blithering** [comment]
Can you put a camera frame where it used to be, for those who are renovating the bar for less than shady purposes?

**Comment by Kharkov72** [comment]
@Blithering I'll put it in aux tool storage on the table with the circuits, I think it would just look weird lying on the floor.

**Comment by ShiftyRail** [comment]
Plenty of support + no other PR on Box seem to touch that line.

**Pull request merged**
