### PR TITLE
Adds flaming exhaust when shuttles launch

### PR DESCRIPTION
**Pull request by Sprok0**
Shuttle engines actually do something now, whenever a shuttle launches fire sprays out of them.

OUTDATED GIFS:
miningshuttle
syndieshuttle
escapeshuttle

### CODE REVIEW

**Comment by ghost** [comment]
While this is the most beautiful feature I've seen for a while, I can't help but feel that deficiency could become a bit more fun from this with that shuttle in the middle of a hallway

Also, if the pods launch while leaving somebody, they fry them to a crisp, so :+1:

EDIT Okay, defficiency'll fry robotics to a crisp judging by how the fire blast just goes through a window on the last gif/webm

**Comment by SysadminJeroen** [comment]
@Skullyton And it looks like antags now need to be careful where they park their ships.

**Comment by Sprok0** [comment]
The fire from the deff hallway shuttle doesn't go through the windows, I already checked.

**Comment by ghost** [comment]
Aww

**Comment by kol1th** [comment]
I don't like it too much. If the shuttles moved instead of disappearing, maybe.

**Comment by SysadminJeroen** [comment]
@kol1th Well, they do use Bluespace engines.

**Comment by SonixApache** [comment]
Fire effect is a little over the top, but I like it a lot.
Make it a little shorter maybe?

**Comment by Sprok0** [comment]
Shorter in which way?

**Comment by BarneyGumball** [comment]
Hahahahahaha. I don't even care if this doesn't make sci-fi sense, this is fucking great.

**Comment by ihadtoregisterforthis** [comment]
The fire should be a different color at least.

**Comment by Sprok0** [comment]
I am entirely worthless at spriting, but I made the fire blue.
bluefire

**Comment by gbasood** [comment]
> exhaust entering tiles surrounded by windows in third picture in OP

FIX
Also the exhaust travels REALLY FUCKING FAR and covers a lot of tiles. Maybe reduce that. But that's just my opinion, man

**Comment by Sprok0** [comment]
I'm pretty sure that the firebreath projectile going into windows like that is part of the big Bump() issue or similar. The projectile that spawns the fire has grillepass 100, and it seems to check if it can enter the tile only considering the grille and ignoring the outer window. This also seems to only effect roundstart windows, and not ones made later for mysterious reasons. Here are some gifs of testing this.
fire1
fire2
fire3
fire4
fire5
fire6

**Comment by Exxion** [comment]
That's almost certainly just due to poor coding, not the `Bump()` issue

**Comment by Shadowmech88** [comment]
The projectiles are made to have infinite penetration, and penetrate mobs, blobs, and objects. I did so to prevent a stream of fire from just stopping when it collides with a person or a machine, since it wouldn't really make sense for that to happen.
My guess would be that, due to windows being objects, the projectiles are penetrating them as well.

But according to the GIFs, it only penetrates roundstart windows, and only those that have grilles behind them.
So I don't really know what would cause that.

**Comment by Exxion** [comment]
My money's on it checking the turf for grilles then moving itself onto the turf if it finds one before an object it can't pass, like the Firebird used to do with airlocks
Whereas it should work by having the grille's `Cross()` return true for it

**Comment by Exxion** [comment]
OK no it looks like that's how it does work

Whatever the cause, it is probably buried deep within projectile code and probably applies to other projectiles and is just more obvious with this one

That or it's the `fire_blast` effect
I'm too tired to tell right now

**Comment by Shadowmech88** [comment]
Even if the `fire_blast` effect DID happen to spawn on the window's tile when the projectile died, that still wouldn't explain the complete stream of fire passing into the conference room through the window.

**Comment by Exxion** [comment]
You're right. It's definitely the projectile.

All evidence presented points to my first explanation, but I can't seem to find where that's happening in the code. But wherever it is, it's almost certainly not unique to this projectile.

**Comment by SonixApache** [comment]
Shorter as in not 30 tiles, but maybe 3 of solid stream and then some of that expandey shit.

**Comment by Sprok0** [comment]
The max range of the straight stream is 14, and I personally think that rocket exhaust should be pretty long

**Comment by ihadtoregisterforthis** [comment]
You could extend it to where the shuttle was

**Comment by Sprok0** [comment]
Current status:
morefire

**Comment by gbasood** [comment]
The problem with the length of rocket exhaust isn't a realism issue.
A player in space can be killed off by a stream of exhaust from a shuttle they can't even see and it can happen quickly enough that they won't be able to respond to it.
That's pretty dumb for something that's going to be happening so frequently.

Also, you **must** fix the issue with exhaust going through windows.

**Comment by SysadminJeroen** [comment]
I do agree with @gbasood that the exhaust is a bit too long.

I'd say that half of someone's line of sight is long enough.

**Comment by Sprok0** [comment]
I'll cut the length down, but it isn't like the exhaust is instant death or anything, standing in a flame for its full duration is about 40 burn to a naked human

The gif in the first post is with diona, for effect

**Comment by Sprok0** [comment]
Current fire length
lessfire

**Comment by SonixApache** [comment]
perfect

**Comment by Exxion** [comment]
Oh, that's where it was
Honestly, `projectile_check()` as a whole has no real reason to exist, but that's not what this PR is about

**Comment by unid15** [comment]
In the gif, the flames traveling north look a bit weird. Otherwise this is great!

**Comment by Sprok0** [comment]
I think they look fine, it's like a back to the future flaming tiretracks sort of thing

**Pull request merged**
