### PR TITLE
Adds a small addition to lazarus injectors desc

### PR DESCRIPTION
**Pull request by FudgePucker**
I have seen some new players show their pokemon to other people and have the poor creature be euthinized after it ripped off someones face.

This small addition should help prevent that from happening if they bother to read the discription.

### CODE REVIEW

**Comment by FudgePucker** [comment]
Also I know that there is a feature freeze and everything, but this is just a one line change and will prevent people from breaking the rules and getting people killed.

**Comment by Kurfursten** [comment]
If you're going to change it, you might as well just be explicit and make it say "it will remain hostile to anyone else".

Also, while you're at it, why not make a change to the lazarus capsules (mobcapsule) themselves to change its name and description based on what's contained inside? For example, when you capture something or when you rename it...
name = "[contained_mob]'s Capsule"
desc = "This is a lazarus capsule containing [contained_mob], which is a [initial(contained_mob.name)]."

And when deployed, just 
name = initial(name)
desc = initial(desc)

That way miners can show off by using Show Held Item instead of throwing out their Pokemon

**Comment by FudgePucker** [comment]
@Kurfursten 
It already is a very long description. Plus I think just mentioning its nature is the correct way because if you revive pun pun or ian they don't become hostile and have rabies.

Also that seems way out of the scope of this PR, a nice way of saying I don't trust my self to do anything involving anything beyond simple changes in fear of everything I touch shattering into dust.

**Comment by Kurfursten** [comment]
Yeah, it's out of scope

**Pull request merged**
