### PR TITLE
Revert "Weekend Primetime NO HOLDS BARRED"

### PR DESCRIPTION
**Pull request by d3athrow**
Reverts vgstation-coders/vgstation13#32966

Revert proposed due to short time frame of the server poll presented.

edit: Reversion poll submitted https://ss13.moe/index.php/poll/235

### CODE REVIEW

**Comment by Eneocho** [comment]
Bro it hasn't even been one weekend for this to be tested inserver.

**Comment by d3athrow** [comment]
> Bro it hasn't even been one weekend for this to be tested inserver.

Does it look like I care?

**Comment by PavelCIA** [comment]
This is a shit idea and democracy fucking sucks anyway

**Comment by ShiftyRail** [comment]
I don't like the fact that the PR poll gave away the title rather than simply linking to the PR for people to make their own idea. "Primetime" could mean anything.

**Comment by pedr69** [comment]
60% majority not enough, despite a 54% majority resulting in removing line?
odd

**Comment by WindowsErrors** [comment]
This is like, the one thing that would make me want to run for office, if you're in some kind of management role you can propose the Help the Small Babies pull request and the pull request just takes $20 from every paycheck so I can buy myself a house made out of supermatter shards, like just really egregiously blatant deception for the meme of "what's wrong with you, why won't you vote for the Save the Poor Children pull request"
There was a comic that had the Free Beer Act and it's like "ok when do I get a free beer" "what do you mean free beer? the Free Beer Act just raises your taxes by 2%"

**Comment by adacovsk** [comment]
Yeah, three days for three hours might be a bit much even for me, if it was just one night a week I think it'd be better

**Comment by John-VI** [comment]
The poll was bad and done wrong because it had a result I did not like. Revert nao

**Comment by ShiftyRail** [comment]
Castle wasn't meant to be available all the time. I don't think this "primetime" PR was a good idea from the start. There are already many ways to access Snaxi (4 months a year!), Line (1 month a year), and Castle. If this were to be enabled again then even stuff like Lamprey could be voted on on-demand. That's silly.

**Comment by adacovsk** [comment]
> Castle wasn't meant to be available all the time... If this were to be enabled again then even stuff like Lamprey could be voted on on-demand. That's silly.

"Admins will select for you the maps you love, these shouldn't be available to the plebes!" t. admin

Admins never change the maps...

**Comment by ShiftyRail** [comment]
>Admins never change the maps...

Admins aren't needed - there's a process for Castle, a process for Line (october) and a process for Snaxi even.

**Comment by Eneocho** [comment]
> > Admins never change the maps...
> 
> Admins aren't needed - there's a process for Castle, a process for Line (october) and a process for Snaxi even.

Sure you claim that but when I add a "process" for lamprey my PR gets suspiciously closed by one shifty rail despite the vote majority.

**Comment by ShiftyRail** [comment]
Lamprey is not meant to be played. It has no room for normal ss13 gameplay. Not in the same category.

**Comment by Eneocho** [comment]
Irrelevant to the point. You claim "processes" for non-standard maps to become available without an admin but attempts at re-adding a method to play them gets shut down despite majority. And in my time here I've only seen an admin bus lamprey once.

**Comment by SacredAtom** [comment]
> Lamprey is not meant to be played. It has no room for normal ss13 gameplay. Not in the same category.

Yeah maybe if you lack any creative juices and the ability to rp, which would be a classic combo for a french vox player.
God forbid people play a different map a few times on the weekend on something other then box station all week.

**Comment by pedr69** [comment]
>processes for non standard maps

we have a bagel process
maybe we should have processes for the more controversial non standard maps too, instead of locking them to one month/quarter of a year, which results in them being constantly voted in that time period
and people seem to hate line and snaxi, which could be because the maps are shit, or maybe it's because we play them for a month(or 4) straight

**Comment by Eneocho** [comment]
>we have a bagel process

In theory, but it is disabled. You can cook all the bagels you want but it won't let you vote for bagel proper.

**Comment by ShiftyRail** [comment]
Lamprey is not gonna be playable on demand. That's just how it is.

**Comment by pedr69** [comment]
FUCK, the vote is winning
i'll need to make some calls...

**Comment by ShiftyRail** [comment]
Maricopa county bros...

**Comment by wotisjanitor** [comment]
@Kurfursten merge this

**Comment by ShiftyRail** [comment]
~~A few more hours on the poll.~~
Oh no wait, it's 00:00 on the 10th.

It's unfortunate that there's no 50% majority for this, but it's clear that Primetime "no holds barred" isn't the way to go. Maybe there's another way to go about this map issue.

**Comment by adacovsk** [comment]
> ~A few more hours on the poll.~ Oh no wait, it's 00:00 on the 10th.
> 
> It's unfortunate that there's no 50% majority for this, but it's clear that Primetime "no holds barred" isn't the way to go. Maybe there's another way to go about this map issue.

yeah I was going to try to reduce the hours/days and change the vote method, but I'm not going to try it now

**Pull request merged**
