### PR TITLE
Makes bee buzzing messages less ambiguous looking

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[tweak][consistency]

## What this does
changes them to emotes like "**the swarm of bees** buzzzzz" and etc.
## Why it's good
less ambiguous onomatopoeia, more in line with other mobs.

## Changelog
:cl:
 * tweak: Bees now emote their buzzing instead of just making the user read "Bzzzzz" or "Hmmmm"

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you also fix the singular bee stinging message? See #31082.

**Comment by ManopolisJones** [comment]
I for one always liked the ambiguous buzzing, also I can't quite recall if the hornets also give the buzzing message, because if they don't they should.

**Comment by SECBATON-GRIFFON** [comment]
> Can you also fix the singular bee stinging message? See #31082.

2unatomic4me

**Comment by Servalfang** [comment]
This is perhaps the most retarded thing i want to stay

**Comment by incakola** [comment]
soulless

**Pull request closed without merging**
