### PR TITLE
Quick taxi fix for #6595

### PR DESCRIPTION
**Pull request by Probe1**
Removes one errant pipe that led nowhere in atmospherics adjacent to the air mix tank.
image

Removes one bent pipe that was obstructing the function of the air mix tank, rendering it inoperable.
image

image

Fixes https://github.com/d3athrow/vgstation13/issues/6595

### CODE REVIEW

**Comment by Probe1** [comment]
image


Dude weed lmao

**Comment by Probe1** [comment]
all done, merge when reviewed & you're ready.

**Comment by Kurfursten** [comment]
If you're editing anyway, might want to add a chair to the escape shuttle cockpit, and do the Cargo stuff I requested

**Comment by Probe1** [comment]
just pipe fixes pls.  I'll make a mapping PR in celebration of FF ending when it does and do all the things.

also now I'm positive it's done, there are no more pipes to conquer.

**Comment by FudgePucker** [comment]
>that scrubber connected to distro

Oh wow, its a mirical that no one plasma flooded by cutting open a hot mix canister in there

**Comment by Probe1** [comment]
@N3X15 quick fix.  two days later..

There are some serious issues this PR resolves (the scrubber hooked to distro and the bent pipe that neutralizes the main air mix chamber).  It's well documented and needs merged please.

**Pull request merged**
