### PR TITLE
Removed slowdown from plasmamen hardsuits

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * tweak: Plasmaman suits no longer slow you down, with the exception of engineering and atmos suits that have a slight slowdown (those have increased resistance to pressure/temperature).

### CODE REVIEW

**Comment by jknpj** [comment]
free suit and no slowdown? but why?

**Comment by yclatious** [comment]
The rotting half alive half dead plasma flesh zombies that are encumbered by highly specialized "dont fucking imolate yourself" hazard suits shal not have their slowdown removed.

**Comment by DamianX** [comment]
Plasmamen players complained about it. I think it makes sense because they need the suit to survive, unlike vox. I'm obviously open for discussion if you think this is retarded.

**Comment by ghost** [comment]
The only other spacesuits with NO_SLOWDOWN are ERT suits btw

**Comment by ValkyrieSkies** [comment]
Cease.

**Comment by jknpj** [comment]
How about giving non EVA jobs (engineer, atmos, CE, miner) a non-space worthy suit with no slowdown?

**Comment by Riekland** [comment]
They shouldn't have no slowdown because having the suit isn't meant to be a good thing
It's a bulky drawback that you accept so that you can play as a screaming purple skeleton

**Comment by yclatious** [comment]
Its a biohazard prevention suit, a expensive, likely budget cut piece of bulky equipment that has integrated extinguishers inside to keep plasmamen from ingiting in the air like the living bonfires of permanenly in pain plasma infused flesh they are, and I dont see plasmeme complaints being a valid reason to remove it, its a neat and interesting thing, fits with their situation and its a nice drawback so you can play as a constantly screaming and in pain half disolved man thats half plasma in the little flesh it has.

**Comment by Exxion** [comment]
Woop woop powercreep alert

**Comment by TheFriggenSawbones** [comment]
this is literally how it was since forever
it wasn't until his pr that the assistant suit and whatever got a slowdown

**Comment by TheFriggenSawbones** [comment]
Originally the only plasmaman suit with slowdown was, I think, engineering and for whatever reason the Librarian Lawyer suit. I made a pr to even things up and removed slowdown from those two suits but added it to Mining and Atmos and Engineering as they gave extra protections.

After talking to DamianX it sounds like it was unintentional, that in his resurrected slowdown refactor pr all plasmamen suits were given a sizable slowdown. As he believed that was the original intention when that wasn't exactly true.

I don't think you can call it powercreep as this pr returns them to how they originally were. and I honestly hope suits with added benefits, i.e Security, Engineering, ect, have some form of slowdown.

I understand the argument is that since we're given a free space suit there should be some downside but I believe that the suit itself is also the downside. Given the fact we have to wear it and the currently buggy nature of Plasmamen, they can be annoying to play. In comparison to Vox, they don't need their suit and could easily get some form of armor which would put them above Plasmamen's burn reduction, and way far ahead of the added brute damage they take.

I also don't think having a slowdown, especially with no great added benefits, is very fun nor a good decision from a gameplay perspective. Given that Diona have a slowdown because they're pretty much immune to brute damage and Vox are given the choice. Having to chug hyperzine, or be ineffective in any fight and other such situations, sucks a lot.

**Comment by ghost** [comment]
Before the slowdown refactor almost no suits had a slowdown at all. The PR that reduced the slowdown from the librarian suit etc. was simply bringing them in line with other hardsuits.

They are now still in line, which is, barely a 33% slowdown I believe.

**Comment by gbasood** [comment]
@TheFriggenSawbones 
\>Given the fact we have to wear it and the currently buggy nature of Plasmamen, they can be annoying to play.

just jumping in to say if there's a bug that makes them annoying to play the solution is to fix that, not to buff their suits, and trying to justify this PR by saying "but bugs unrelated to this" is more than a little irritating

**Comment by Exxion** [comment]
They *did* actually have a slowdown, but due to a bug it only applied when stacked with other things with slowdown
(Or when worn without shoes)

Also, brute damage armor is *way* more common than burn damage armor

**Comment by DrSnips** [comment]
Make them bio suits and have the slowdown removed on the new plasmamen suits so it avoids free space suit lmao people. Leave the ones that require spaceworthy suits like engineer, atmos, head roles, paramedic, etc.

**Comment by Pantrist** [comment]
it makes logical sense for plasmamen to be slow, they have a fat suit that is pretty much a biohazard suit.

the only way to say they should be faster is because of combat, and combat is not the focus of this game so why should the game be changed to be balanced? it is not a moba or fighting game, and if it was it would be a poor one because other races are simply not as good as some races. humans the most played race are by far the worst, they do not spawn with a free hardsuit, they need to carry internals with them at all times incase of n2o floods, they bleed and unlike the gays the can't call for help even when silenced. but humans are still the most popular race, because the big majority of people understand its not about playing the most overpowered race, but the one they find fun in this open world action rpg with platforming elements.

**Comment by TheFriggenSawbones** [comment]
@gbasood alas i've reported it and nothing was done, it's a well known bug

but regardless, I guess I should've left it out in my request to fix this oversight that totally 100% unintentionally added a further slowdown to plasmamen suits.

@Exxion yeah I know but they take two times brute damage so i think it more than accounts for the burn resist

@Pantrist humans are, by far, not the worst race. It's not even about power, it's about how it's not fun to play as plasmamen because of this UNINTENTIONAL OVERSIGHT.

**Comment by SonixApache** [comment]
delet

**Comment by dickmuncher** [comment]
Hey, like what if we also add plasmamen yelling as well? If sawbones cares SO MUCH about plasmamen surely this would be a bigger issue then "muh slowdown", surely people will remember the plasmamen threads that say, "What if we add people who are constantly burning to death and are screaming because they are always in pain". 

The fact that plasmamen have a little slowdown is less of a problem THEN WHAT THE FUCKING RACE WAS CREATED TO DO. It's like if you remove humans being covered under asimov, or vox talking like retards, or skeletons being unable to rattle their bones furiously, or greys being able to telepathically communicate with people.

Fix them not screaming constantly before you fix a little movement bug, sawbones doesnt know what hes talking about and isnt a true plasmaman poster if them screaming doesnt bother him.

**Comment by ghost** [comment]
@TheFriggenSawbones I don't think your claim that plasmaman hardsuit slowdown is an "unintended oversight" comes from valid logic, and even then, it wouldn't hold any weight. They could have HAD no slowdown like you wanted, but the votes here tell us people would be in almost unanimous favor of adding slowdown to them again.

**Comment by aceedex** [comment]
Remove slowdown on rig suits too then

**Comment by Blithering** [comment]
Slowdown seems ok if its in line with equivalent rigsuits. Maybe have a no slowdown, no space protection suit orderable from cargo for those who would rather risk dying from 1.5x pressure damage

**Comment by ShiftyRail** [comment]
F

**Pull request closed without merging**
