### PR TITLE
Showers are now ordered from cargo, not built using metal sheets.

### LINKED ISSUE #7573: I don't think players should be able to construct showers, or at least, not as easily as can be done right now
It allows you to completely clean yourself of blood anywhere at any time, provided you brought metal sheets (I personally never am without at least some metal sheets in my backpack)
It also has massive griff potential by letting you construct a shitton of slipathon machines everywhere and generally be A Huge Pain In The Ass
Lastly, it also lets you completely fucking calcinate Diona and Grey alike with jet streams of IMPOSSIBLY HOT AND ORDINARILY SLIPPERY WATER (WHY)

### PR DESCRIPTION
**Pull request by Intigracy**
They also have to be bolted to the floor to turn them on.

Fixes #7573

tested

### CODE REVIEW

**Comment by Probe1** [comment]
im ok with it but make sure the playerbase is.  a lot of people love making slip n slides.

**Comment by Boxe** [comment]
make them machines or something instead pls

useful for xenobio

**Comment by Intigracy** [comment]
They ARE machines.

**Comment by Boxe** [comment]
i mean like constructable via boards n shit from rnd/soldering irons

**Comment by Intigracy** [comment]
You don't even need more than one shower in an area, just steal one from the shower room or order a crate from cargo.

**Comment by Boxe** [comment]
ah fine

also how does this work with the wrench being used to change the temp

**Comment by Intigracy** [comment]
If the panel is open (it comes that way in cargo or you can screwdrive it to open it), using a wrench on it unbolts or bolts it to the floor.

If the panel is closed, using a wrench changes the temperature to VERY HOT, VERY COLD, or normal.

**Comment by Boxe** [comment]
oh good

**Pull request merged**
