### PR TITLE
More floorpill combinations

### PR DESCRIPTION
**Pull request by help-maint**
Many of the combinations that floor pills have are a little underwhelming (like just pure tricordrazine), so this adds a little extra to the more boring ones. Pills that would usually have no effect on healthy humans now also have a tiny bit of drugs or alcohol, and some chemicals are replaced by rarer versions of themselves (like bicaridine for opium). Very few changes overall.

:cl:
 * rscadd: Added a few more chemicals to floor pills, so even the more mundane combinations at least have a little bit of drugs.

### CODE REVIEW

**Comment by Eneocho** [comment]
I would restore Impedrezene. Half of the fun is in risking getting retardified.

**Comment by DrSnips** [comment]
Suggesting the name "Prototype d0"

**Comment by help-maint** [comment]
Impedrezene isn't gone, i just replaced it with the plant version of impedrezene

**Comment by Eneocho** [comment]
> 
> 
> Impedrezene isn't gone, i just replaced it with the plant version of impedrezene

I forgot that was a thing, with how rarely you get to make it.

**Pull request merged**
