### PR TITLE
Farting while in crit will now make you succumb

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Do not fart gently into the night.

:cl:
 * rscadd: Trying to fart while in critical condition will now actually make you fart, but at the cost of immediately making you succumb to your injuries.
 * rscadd: Farting while in critical condition with the super-fart gene active is not advised.

### CODE REVIEW

**Comment by pedr69** [comment]
but this is already a thing?
it gives the "name has left the building..." message when you do it

**Comment by WindowsErrors** [comment]
You know why I never liked executing people as the warden? It's because you shit yourself when you die

**Comment by pedr69** [comment]
oh, THAT'S why most of sec beheads and completely pulverizes the bodies
so they don't shit themselves

**Comment by Eneocho** [comment]
I feel this will somehow lead to farting while asleep instakilling you.

**Comment by boy2mantwicethefam** [comment]
It doesn't, I tested it.

**Comment by Eneocho** [comment]
> It doesn't, I tested it.

I almost wish you hadn't. Someone farting while chloral'd and dying to that would've been really funny.

**Comment by WindowsErrors** [comment]
does that mean you can super fart the warden while you're in crit, stunning the entire security the moment your explosive implant goes off

**Comment by Eneocho** [comment]
Line 204 says:
`if(M_SUPER_FART in H.mutations && H.stat == CONSCIOUS) //No super farting while unconscious`
So no.
Requesting for that to be removed so you CAN superfart while unconscious. Funny > Balance

**Comment by boy2mantwicethefam** [comment]
I'll do it but only if you agree that it should make the guy explode in the process.

**Comment by Eneocho** [comment]
Alright but the sleep superfart better be stronger than a regular superfart.

**Comment by calzilla1** [comment]
Superfarting while in crit should gib you

**Comment by adacovsk** [comment]
> Alright but the sleep superfart better be stronger than a regular superfart.

maybe not this, but shrapnel in the form of bodyparts

**Comment by Eneocho** [comment]
> > Alright but the sleep superfart better be stronger than a regular superfart.
> 
> maybe not this, but shrapnel in the form of bodyparts

This works too.

**Comment by Eneocho** [comment]
Superfarting while asleep just farts as normal, superfarting while in crit gibs you and shrapnels with limbs and bodyparts. Make it happen blease, @boy2mantwicethefam

**Comment by boy2mantwicethefam** [comment]
No shrapnel, I don't want the PR to raise any eyebrows

**Comment by Eneocho** [comment]
Aight but please make it so you can superfart while asleep, and superfarting while on crit gibs you.

**Comment by boy2mantwicethefam** [comment]
The superfart comes at a price, if I were to add that to regular unconsciousness people could easily superfart their assailants away while knocked out, such as vampires and cultists.

**Comment by Theophrastus1** [comment]
> I'll do it but only if you agree that it should make the guy explode in the process.

It should gib them and leave nothing but their ass and play that fart reverb sound effect we have while knocking everyone down around them.

**Comment by Eneocho** [comment]
> play that fart reverb sound effect we have while knocking everyone down around them.

That's what superfarting already does

**Comment by calzilla1** [comment]
https://youtu.be/gsXSozmWwiE?t=5

**Comment by Eneocho** [comment]
Can you fart/superfart while asleep but not crit?

**Comment by boy2mantwicethefam** [comment]
You can fart while asleep but not superfart from what I remember

**Comment by Eneocho** [comment]
Could you make it so you can, please? I find the idea of superfarting the gloralgoblins really funny. You could even superfart throw yourself into deep space after you fall asleep from hypothermia as well, blease make it so you can.

**Comment by boy2mantwicethefam** [comment]
Please I want to make funny fart PR not Super-Farting The Balance Nightmare even if that would be funny. Besides I already mentioned it before, power at a price, superfarting while in crit only and it gibs (on top of already being an empowered super-fart AKA throws somewhat farther and stuns for a little bit longer)

**Comment by Eneocho** [comment]
But why couldn't you fart while asleep though? You can while in crit but not while asleep? What's the reasoning, specially since you can regular fart while asleep as you said?
Also, superfart ain't that common a gene and is fairly useless in combat due to it's 3s delay until fart which stops if you move by any method and the obvious notification to anyone nearby, is it REALLY that big a balance threat to just enable superfarts while asleep?

**Comment by pedr69** [comment]
wyci, eneocho

**Comment by Eneocho** [comment]
It aint even a WYCI issue, he has the code for farting while asleep already, just with an exception on superfarts. Why that exception though? As previously mentioned, superfart is too cumbersome to be useable in combat so it's not a huge balance risk to enable it while asleep.

**Comment by Eneocho** [comment]
Add #24989 to the OP, since you said you can now regular fart while asleep.

**Pull request merged**
