### PR TITLE
[OBS-5/51] Brings back THE PAPER :tm:

### LINKED ISSUE #21217: Enemy Communications & NT Relation
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
000ab393137118df556fee4b4d5b045984bc5df7

# Description
Since codewords got added back, figured I'd report this. Ever since datums, there are no more reports of folks who have an opposed relation to NT. Traitors also no longer get a message saying that 'X may be willing to help' of someone who has a bad NT relation.
# Steps to Reproduce
Sit waiting for report
or be tator
# What you Expected
Report listing folks with a bad relation to NT
A crewmember that may be willing to help you
8 extra things to buy goodies if you're a tator and show up on the report
# What Actually Happened
No report pops out
Apparently none of the crew is willing to lend an ear to a syndie cause

### PR DESCRIPTION
**Pull request by ShiftyRail**
[bugfix] [role]
Closes #21217

This brings back the Paper :tm:, and changes it so that it gives a wild threat estimate rather than a list of "suspects" and extra TCs.

Outdated issue related to this : #13634

:cl:
- bugfix: Brings back the enemy communication paper from roundstart. It will give a wild estimate of the threat level.

### CODE REVIEW

**Comment by ghost** [comment]
I have a request/condition for this being brought back: Give it to everyone, and make the chances super, super lower. Skeptical, Opposed, even full on NT shills. The paper needs to have a VERY high accuracy miss % so it can become an RP item instead of a dumb "ur not even really allowed to read it cause then its metagming" thing.
Why do I say for everyone?
Because the Syndicate as bastards. 
If you're fully opposed to NT, there should be a message when rolling traitor that says "now's the time to prove yourself to The Syndicate, _____"
if youre skeptical, maybe they insensitive a rewards for completing the mission
but if you love NT? "We have something very important to you, if you don't do as we say you'll lose it and everything you ever loved"
We can even tailor it to midround tators vs roundstart, a sudden PDA message to deliver the news, or a voice in your ear as you arrive telling you what you have to do, and why

i'm mostly saying this because i think its bad design gimp people from antag things if they set a fluff thing in their character creator, and im trying to come up with creative ways to balance this lore and RP fluff

**Comment by SonixApache** [comment]
agree with the paragrapher

also maybe not put so much emphasis on the extraTC thing in the changelog
hidden knowledge, RP fluff instead of functional character options, etcetera

**Comment by Kurfursten** [comment]
I actually think we're going entirely the wrong way with this feature. As it exists right now, it's basically just a metatest for whether you are experienced or not. Are you knowledgeable enough about our codebase to set yourself to opposed? Have some extra TC. It's not documented on the wiki and there's no tradeoff that would ever make you want to not get the bonus TC since the paper is not supposed to be used anyway.

The paper could be used for something practical, like telling you how threatening the round was at start. Estimates like
>60+ threat: Enemy sector
>20-60 threat: Contested system
>20- threat: NT-controlled space

If people knew ahead of time there's not a lot of serious danger coming they might be more inclined to start renovation projects before the 2 hour mark. The really clever part about this is that by using the round starting threat instead of remaining threat is that you can't metagame how much of that has already been spent on antags. So the HOP might go around validhunting on 65 threat looking for a cult that doesn't exist because dynamic decided to only spend 30 threat on 3 traitors to begin with and save 35 threat for later.

**Comment by boy2mantwicethefam** [comment]
@Kurfursten real shit?

**Comment by ghost** [comment]
For this specific feature I actually think Kurfursten's idea is 200x better than mine.
completely removes the sort of weird meta thing of setting yourself to opposed for more TCs but still gives captains a roundstart report thing to read and think about

### from here is fanatical ranting ignore if you don't care
```
I'd like for this to become something people read at the round start and sort of... the Captains and the Heads and Security maybe "prepare" for within an RP guideline.
 If the threat is reported as low, reportedly in NT owned & dominated space, then Sec, Heads, etc, are expected to be casual, slow, operating as normal as possible. Security in minimal wear, Cap not running around strapped with eguns in his hardsuit, that kinda thing, unless a legitimate threat presents itself.
Perhaps the lower threat % could also mean the escape shuttle comes faster, at the expense of the supply shuttle being 30 seconds slower for some fluff reasons. 
For the medium tiers, in this "unowned/unoccupied" space, the same things apply but the heads/security should be understanding that NT involvement in things will be slow and they need be a bit more cautious. Perhaps brig timers for small offenses are allowed to be higher, blah blah, the supply shuttle & escape shuttle come at regular speeds.
now for the high threat, the 75%s and 90%s, where the station is occupying "enemy" territory, i think it should be fine for Captains to code blue as soon as they feel necessary, including right away. Everyone, including the crew should be more on edge at these times, its a stressful and tense time.
perhaps now, the supply shuttle comes faster because fluff, far enough away to use special drives blah blah, but the escape shuttle takes a bit longer  

all of this is pure RP trash that nobody would ever actually want on vg but i can dream and shitpost if i want
```

**Review by MadmanMartian — COMMENTED** [review]
In the area where it's seeing if they belong to a certain role and a probability to make them detected, have a function that's called where the role is 'detected', so you can have things like traitors gain extra TC, and potentially other things can happen in the future.

**Comment by ShiftyRail** [comment]
I took Kurf's suggestion but broadened it a bit ; the station can always be in "contested space", if the threat is < 50, it can be in "friendly territory", and if it's over 50, it can be in "uncharted space".

**Comment by Kurfursten** [comment]
You used threat instead of threat_level. Threat is how much there is left over to spend, threat_level is the max threat for the round. So for example, on a 60 threat_level shift it might spend 30 right away and leave you with 30 threat. This will almost always roll friendly/contested in its current form.

Maybe I'm a radical but I don't think it's particularly dangerous to the "meta" to know without randomness whether it's going to be a 1vampire extendorama or high threat ragin mages cult tot extravaganza. It lets bartenders get started on their work without fear early and it lets people know better than to fuck off to space if it's a shift where all hands are needed on deck. If we as a community are mature enough to handle advanced holopeople without the roundtype getting spoiled every round, I don't think having a general idea of the maximum threat will ruin things.

**Comment by ShiftyRail** [comment]
Right, thanks for the tip, I know what they are I just forgot

**Pull request merged**
