### PR TITLE
Flamethrowers can burn more things

### PR DESCRIPTION
**Pull request by abernd**
Flamethrowers are much more effective against a variety of organic threats. 

:cl:
- bugfix: Flamethrowers can damage facehuggers, xenomorph weeds, kudzu, and biomass.

### CODE REVIEW

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
Adding a long list of istype checks is really not object-oriented programming friendly.

Maybe make or find a flamethrower act proc that calls null on the base object, then override it for these objects (and if you're only just making this proc, add overrides for the other things fire blast damages)

Examples would be blob_act, bullet_act, cultify, those sorts of things

**Comment by abernd** [comment]
@MadmanMartian I'll see what I can do, thanks for the examples.

**Comment by Pathid** [comment]
Those things have `fire_act()` already. Maybe we should find out why it's not triggering and fix that.

**Comment by MadmanMartian** [comment]
fire act isn't being called on them by the fire stack

**Comment by ghost** [comment]
Fix not passing through nor burning webs? Always a bummer when an airy web stops a plume of fire.

**Comment by jknpj** [comment]
To the derelict you go.

**Pull request closed without merging**
