### PR TITLE
Sound play when you can ready up

### PR DESCRIPTION
**Pull request by gbasood**
Sound effect: [here](https://dl.dropboxusercontent.com/u/6581415/prefsready.wav)
🆑 
 - tweak: When you are able to ready up, you will hear a sound effect now.

### CODE REVIEW

**Comment by Fruktlimpa** [comment]
Is that from Starcraft 1? Kinda sounds like it.

**Comment by gbasood** [comment]
yep

**Comment by SonixApache** [comment]
posibrain activation sound when

**Comment by gbasood** [comment]
give me a sound

**Comment by SonixApache** [comment]
https://puu.sh/u7JSc/670d30c882.mp3

**Comment by SonixApache** [comment]
okay forget that, how about https://puu.sh/u9yQ6/b760628223.mp3

**Comment by aratherangryduck** [comment]
Not windows XP startup? Im disappointed sonix, I expected better.

**Comment by clusterfack** [comment]
Make ot check one of the sound toggles before playing

**Comment by Intigracy** [comment]
I think the TADA would be more noticeable for the lobby ready up

**Comment by Shadowmech88** [comment]
These changes appear to have already been committed directly in https://github.com/d3athrow/vgstation13/commit/bfac15d3267ece041c6651ea8c1a17746543941a.

**Comment by gbasood** [comment]
I have absolutely no idea how I managed to do that

**Pull request closed without merging**
