### PR TITLE
I am not done adding epik references

### PR DESCRIPTION
**Pull request by 9600bauds**
Makes it so that it spouts the lines in order, then it goes into "it's resting" mode, which is what I originally wanted to do but got lazy

### CODE REVIEW

**Comment by gbasood** [comment]
> courtain

Also, why does it go into the not dead lines at all when it's still dead

**Comment by 9600bauds** [comment]
fix'd

Because ees not ded, is just stunned :)

**Comment by gbasood** [comment]
Oh, wait they're all "look at this totally not dead thing" references, gotcha

**Comment by Exxion** [comment]
They're all Monty Python references
Specifically to the dead parrot sketch

**Comment by Arthurdentist** [comment]
https://www.youtube.com/watch?v=npjOSLCR2hE

**Pull request merged**
