### PR TITLE
Fixes Chef's Special Sauce metabolism rate to make it actually work.

### LINKED ISSUE #8692: Chef Excellence sauce not working propperly
(WEB REPORT BY: manfreed REMOTE: 84.163.145.21:54074)

> Revision (Should be above if you're viewing this from ingame!)
> -none-
> 
> General description of the issue
> Eating 40u of the Chef Excellence sauce doesn't kill. 100u works fine however.
> (tested on private server. May need additional testing)
> 
> What you expected to happen
> To be dead after a couple of minutes
> 
> What actually happened
> Nothing for 15 minutes
> 
> Steps to reproduce if possible
> Put 2 bottles (40u) of Chef Excellence sauce on a donut and eat it.
> Wait for 15 minutes.

### PR DESCRIPTION
**Pull request by coldcola**
as per advice, the metabolism rate has been fixed for the chef's special sauce, it should work now.

closes #8692

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
I suggest you test it if you haven't

**Comment by coldcola** [comment]
at 4+5 units death occurred in 5.5 minutes.

**Comment by gbasood** [comment]
How many units were left when you entered crit?

**Comment by coldcola** [comment]
I did not check actually, how do I do that exactly?
EDIT: Didn't go into crit actually, after 5.5 minutes I just seized up and died if that matters for anything.

**Comment by gbasood** [comment]
Actually looks like that's intended.
I'm not sure about the on_mob_life code, which you didn't touch, because triggering mob death after you're already dead might have unintended consequences

**Comment by coldcola** [comment]
dylan mentioned this would likely fix this issue that was occurring and that the metabolism was all that needed to be changed, I can try to take a look at how the on_mob_life code works and see if there might be any problems.

**Comment by gbasood** [comment]
@coldcola Nah, look at /mob/proc/death, /mob/living/death, /mob/living/carbon/death and /mob/living/carbon/human/death

See if anything would happen we wouldn't want from multiple calls to death for a human

**Comment by gbasood** [comment]
Actually
on_mob_life will only be called while they're alive
As long as the death() proc does what we think it should there should be no issues

**Comment by coldcola** [comment]
nice.

**Pull request merged**
