### PR TITLE
hallowiz robes

### PR DESCRIPTION
**Pull request by SonixApache**
halowiz
no way to acquire *yet*

### CODE REVIEW

**Comment by mattmatterson111** [comment]
That color scheme kinda hurts my eyes. It's a little too bright I think.

**Comment by Riekland** [comment]
it looks better away from gits pure wh*te background but the hat looks dumb with a purple outline

**Comment by mattmatterson111** [comment]
I'm using a dark theme on github. I haven't seen it with a pure white background.

**Comment by Durgen** [comment]
Aren’t outlines haram on sprites?

**Comment by SonixApache** [comment]
it's probably that the outlines are a different shade that makes them obvious, i'll swap them to some form of orange i guess

**Comment by SonixApache** [comment]
reduced hat outline on the top, to imply that there's a dark purple tone on the inside

**Comment by Riekland** [comment]
that works a lot better, but the green line on the hat looks a bit superimposed - a few darker pixels on the edges would help

**Pull request merged**
