### PR TITLE
Waterpotass

### PR DESCRIPTION
**Pull request by robosperg**
Days since stomach was reverted: 222

:cl:
 * rscadd: Waterpotass is back, deals minor burn damage now
 * rscadd: The same reagent clearing has been added back to nitroglycerin, as it was before

### CODE REVIEW

**Comment by Irradiation** [comment]
Based and waterpotass time pilled.

**Comment by robosperg** [comment]
Forgot nitro used to do clearing as well (why)

**Comment by bathosbathtime** [comment]
Relevant poll: https://ss13.moe/index.php/poll/159

**Comment by Kammerjunk** [comment]
also relevant is that the undecided outcome of the poll meant "don't merge" but then it got merged.
then it didn't get reverted because the headmin at the time said that it was fine if we instead got other ways to clear reagents, like stomachs
```Days since stomach was reverted: 222```

**Comment by Intigracy** [comment]
Make it deal damage to internal organs and I'll merge it.

**Comment by bathosbathtime** [comment]
If it helps, it now results in potassium hydroxide which deals (extremely weak) burn damage.

**Comment by robosperg** [comment]
fuck your balance/powercreep, players want waterpotass back to how it was before the coders of yesteryear had a meltdown about it, give them waterpotass back

**Comment by Intigracy** [comment]
Make it deal damage to internal organs and I'll merge it.

charcoal got a pretty substantial buff at one point, if you're going to go for the absolutely instant reagent clear there should be a downside over using charcoal

**Comment by bathosbathtime** [comment]
Water potassium reaction results in potassium hydroxide and hydrogen being created in the container.
While the resultant does piss poor damage, I have buffed it in #22423 (and removed the hydrogen) and can buff it further if needed for balance.

**Comment by robosperg** [comment]
>wanting organ damage this badly

its like you want people to just toolbox and clone anytime poison comes into play

**Comment by Kammerjunk** [comment]
stop being retarded, Inti

**Comment by Intigracy** [comment]
Fix conflicts and I'll merge it

**Comment by robosperg** [comment]
oh sweet fucking jesus what did I just do

**Comment by robosperg** [comment]
should be ready to merge now

**Comment by robosperg** [comment]
should be ready to merge now

**Comment by MadmanMartian** [comment]
Merged within a day, nice.

**Comment by bathosbathtime** [comment]
Yeah, you would know all speedmerging huh

**Pull request merged**
