### PR TITLE
revert stealthnerf to superior welding goggles

### PR DESCRIPTION
**Pull request by gurfan**
Read the tin.

Add your changes to the changelog, @pedr69 

:cl:
 * bugfix: Fixed a bug where superior welding goggles reduced your vision.

### CODE REVIEW

**Comment by pedr69** [comment]
completely forgot about this after the rig pr got closed
my bad

**Comment by pedr69** [comment]
also did you test this
because i'm 90% sure it will worsen the vision

**Comment by githubuser4141** [comment]
> also did you test this because i'm 90% sure it will keep the vision penalty and actually make them lower your vision MORE should you toggle them twice
> 
> set both vars to 0 instead of deleting the lines, otherwise it uses the parent non-advanced goggle modifier

!?
Is this a late april fool's I can't believe he did this
Imagine the uproar if someone "um removed an umentioned nerf" the detective's revolver bullets by repathing them to rubber rounds 😺 😅

**Comment by gurfan** [comment]
Fixed

**Comment by ErrorsWindows** [comment]
see, the detective's revolver bullets embedding in people and causing life-threatening internal bleeding is a part of the game now

this just doesn't really add anything

**Comment by githubuser4141** [comment]
> see, the detective's revolver bullets embedding in people and causing life-threatening internal bleeding is a part of the game now
> 
> this just doesn't really add anything

The det's .38 rounds should in fact, be lethal, it's hilarious why 'embed bullets' is a specific thing on /VG/ when like, isn't that how bullets are supposed to work IRL + sometimes they can fragment which is like embed +++? How even would a non-embedding bullet work 🤣 🤣 

Actually that'd be a good idea, fragmenting rounds, printable via science, 100% guaranteed to cause like, a dozen internal bleeds from one shot, deals 80+ brute damage and causes 'gaping wounds' which can't be bandaged, creates a ton of embeds, but these effects are blocked completely by armour. On a sec hardsuit, would deal about 5-8 damage. Would be fun for sec/sci to have a weapon that's basically a one-shot for any non-armoured person which is how bullets should work, anyway. And it'd encourage sec to enforce weapons control because of how annoying the revival/treatment process would be.

The joke being that stealth-nerfing the det's .38 to rubber bullets to somehow fix another issue would make a lot of sec mains salty, otoh nerfing a thing !!SCIENCE MAINS!! use? Meeeh

**Comment by pedr69** [comment]
why the fuck would a hollow point round need sc*ence to be made
the ammolathe is what prints the bullets, not r&d

also, we have this already - it's called a laser gun
sec armor has very good laser resistances

**Comment by Exxion** [comment]
> Would be fun for sec/sci to have a weapon that's basically a one-shot for any non-armoured person

Please explain how this would be fun

**Pull request merged**
