### PR TITLE
Signaler sanity

### PR DESCRIPTION
**Pull request by PaulRitter**
[powercreep] i guess

~raises the trigger chance for the threaten verb to 90% instead of 5%~
also adds some sanity to the verb so dead people cant trigger it

~my reasoning:
5% is fucking stupid for something like that, either remove it or buff it and i chose to do the second~

as barry pointed out correctly on discord, in [living_defense.dm#L72](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/living_defense.dm#L72) it triggers the signaler on getting shot with a 80% chance, this was just for dropping it. thonk

still gonna keep this up cause sanitycheck

:cl:
* bugfix: dead people can no longer use the threaten verb of the signaler

### CODE REVIEW

**Comment by Kitfox88** [comment]
Oh man, can you do suicide switches now and hold the station hostage with remote bombs that'll detonate if you die?

**Comment by Kurfursten** [comment]
🆑

**Comment by PaulRitter** [comment]
changelog for an added sanitycheck? wtf

**Comment by Exxion** [comment]
At the time it still said it changed the probability

**Comment by PaulRitter** [comment]
not when kurfursten commented anymore

**Comment by ShiftyRail** [comment]
I dislike that it's a processing object

**Comment by PaulRitter** [comment]
well its only a processing obj when someone presses the verb

**Comment by Exxion** [comment]
It has to be to give the periodic messages

**Pull request merged**
