### PR TITLE
Removed one useless line of code

### PR DESCRIPTION
**Pull request by DamianX**
As far as I can tell this does nothing but prevent me from adminbussing

### CODE REVIEW

**Comment by Eneocho** [comment]
Prepare for unforeseen consequences.

**Comment by Kurfursten** [comment]
Was it actually tested?

**Comment by DamianX** [comment]
I mean it works. The round starts correctly. I've looked into this *extensively*

**Comment by Kurfursten** [comment]
Gonna merge this now when pop is cooling off for the day in case something catastrophic happens

**Pull request merged**
