### PR TITLE
Adds a few more items to the knife holster's allowed list of items.

### PR DESCRIPTION
**Pull request by DrSnips**
Does what it says on the tin. Adds pens, withdrawn E swords, <s>syringes, auto injectors, </s> scalpels, minihoes, hatchets, and spades to the list of items you can holster. 
If anyone has anything else they would like to see on the allowed list just say so.

holstered
Sprites for some of the new holstered items. Any not pictured use the default handle in holster.
:cl: (as the emoji)
 * rscadd: You can now also holster pens, withdrawn eswords, scalpels, bananas, bike horns, minihoes, hatchets, and spades in knife holsters.

### CODE REVIEW

**Comment by Tornader** [comment]
this is also a botanist buff since they can just print those as much as they want

**Comment by DrSnips** [comment]
Good point. Want anything hydroponics related added?

**Comment by Blithering** [comment]
Minihoes maybe?

**Comment by DrSnips** [comment]
How about most botney tools? Spade, minihoe, etc?

**Comment by Tornader** [comment]
sounds good to me, hatchet, spades and minihoes

**Comment by DrSnips** [comment]
Hatchets, spades, and minihoes added. Clippers are children of wirecutters so they already fit. Removed the unathiknife since it's a child of hatchets.

**Comment by ghost** [comment]
Bootinjectors sounds lame AF but whatever.

Also these will all use the default knife sprite.

**Comment by ultraplen** [comment]
Boot injectors and syringes seem like a real menace. Also this is a surefire way to make sure that e-swords never end up in the evidence lockers.

At least throw together a generic item sprite for the holsters.

**Comment by DrSnips** [comment]
You say that like sec didnt "protect" the esword they took by carrying on thier body before this in place of the evidence room.
The knife handle is already a functional sprite and I don't think it needs to be changed. It just needs to indicate something is in it.

**Comment by ultraplen** [comment]
> You say that like sec didnt "protect" the esword they took by carrying on thier body before this in place of the evidence room.

"People already do this shitty thing, so lets further enable it by giving them this fun gimmick!"

Sec running around with traitor weaponry is minor shitcurity, but still shitcurity.

>The knife handle is already a functional sprite and I don't think it needs to be changed. It just needs to indicate something is in it.

Lazy, but a fair point.

**Comment by DrSnips** [comment]
Im just adding things that seemed like they would fit in holsters but for balance reasons I will remove the syringe and injector. As for sprites I will add esword, scalpel, and pens.

**Comment by jknpj** [comment]
I really dislike the notion of inventorycreeping autoinjectors and eswords when they're already pocketable

**Comment by DrSnips** [comment]
As I said, Im removing the injectors and adding sprites. Im just adding some things that seemed like they fit well. I think you can also see the icon of the holster when you examine someone so you might be worse off by holstering these items.

**Comment by ultraplen** [comment]
remove the sword and add in the kitchen knife, and the silverware

edit: and there is no way a hatchet would fit down a knife holster

**Comment by DrSnips** [comment]
They are more for !fun!. Silverware is already there.
I don't get why everyone is losing their heads over the esword, when widthdrawn, being able to fit.

**Comment by ghost** [comment]
maybe make it so that the item in the holster shows up when you examine someone

**Comment by Shadowmech88** [comment]
A hatchet might fit in a knife holster handle-first, with the head sticking out.

**Comment by Kurfursten** [comment]
>Handle first

Elaborate sec torture device? Any time the person wearing the hatchet shoes runs they get cut by the hatchet targeting the leg zone?

**Comment by DrSnips** [comment]
Im pretty sure you see the accessories icon when you examine the person already. So you can see what someone is carrying.
I will look into adding an examine addon for the holster if it doesnt show already. Just a simple "x has a knife holster with a Y in it."

**Comment by Durgen** [comment]
how about bananas and bike horns

**Comment by DrSnips** [comment]
That's OVER THE LINE. Will add.

**Comment by Shadowmech88** [comment]
The holster is on the outer side of the boot, not on the inner side between the legs, right? I don't think the hatchet blade would be much trouble on the outside of the leg.

**Comment by Hugh-G-Rection** [comment]
Emergency oxygen tanks?
One in both legs for ghetto jetpack?
ROCKETBOOTS!

**Comment by Kurfursten** [comment]
@Shadowmech88 The sprite implies outside

**Comment by DrSnips** [comment]
banana
When you examine someone this is what knife holsters look like. So you can see what's in a holster.

**Comment by DrSnips** [comment]
Also removed injectors and syringes.

**Comment by ghost** [comment]
Seems OK now

**Comment by ultraplen** [comment]
sneaky c*llaborator merges 2 day old PR with a negative like/dislike ratio 🤔🤔

But to be fair, most of the thumbs down rolled in whilst autoinjectors were still in the whitelist.

**Comment by DrSnips** [comment]
Would help if people removed their old votes too.

**Comment by DamianX** [comment]
\>assuming the votes don't apply even after the changes

**Pull request merged**
