### PR TITLE
Reverted GPS to nanoui

### PR DESCRIPTION
**Pull request by DamianX**
More than one person reported being unable to open the GPS a second time after closing the window once. It's not obvious why this happens so I'm reverting it to NanoUI for the time being.

:cl:
- rscdel: GPSs use NanoUI once again.

### CODE REVIEW

**Comment by SonixApache** [comment]
IMO: make a seperate tGUI GPS and put it in the protolathe locked behind NT tech.
Good for testing.

**Comment by DamianX** [comment]
maybe later

**Comment by SonixApache** [comment]
For the record; some players regret this revert as nanoUI almost never worked for them, and tGUI almost always did.

**Comment by DamianX** [comment]
As soon as someone comes along and figures out why sometimes you can't re-open the window and how to prevent it from happening I'll revert the revert. I spent a lot of time trying to figure this out with nano and my workaround doesn't work, so someone else will have to look into it.

**Pull request merged**
