### PR TITLE
Disables Thermal Entropy subsystems and adjusts freshly cooked/dispensed consumables' temperature to safe values.

### PR DESCRIPTION
**Pull request by ghost**
## What this does
Disables frustrating and anti-fun food/reagent containers "feature".
Does **not** touch the nu-fires.

## Why it's good
Let me quote my own wall of text I built past week:

> The fact that there have been over 9000 different tweaks and rebalances to this nu-fire-temperature subsystem and it still sucks ass is a definite proof it's shit and should be cut from the code entirely. Then, if someone actually capable and knowledgable about IRL fires makes it right we can judge if it would benefit the server in general or not.
> 
> I for one did not enjoy constantly trying and failing to extinguish cigarette butts and burnt messes on chef's counter that round when one careless grue melted the entire station by accident. It was kino, yes, but this one good round when that lone bag of sugar in the Kitchen actually turned into caramel for the first time ever since this subsystem was introduced was not worth all of the pure suffering players had to endure in all of the previous rounds.
> 
> Neither do I enjoy chemical pills being frozen in my personal medkit after I return from a space trip, nor do I like waiting for 10 seconds after microwaving my donk-pocket for it to be edible. I hate how often I get to see the hot/cold temperature indicator in the right corner of my game screen in your average round. It's frustrating and, most importantly, it's **NOT FUN.**
> 
> I know they fixed the cigarette butts, yet my point still stands. Yesterday it was cigarette butts, today apparently it's paper bins, tomorrow it will be some other annoying and frustrating shit. Just cut this shit entirely.

Cutting this feature along with every tweak made to it up to this day entirely proved to be a sisyphean feat, so simply disabling it will do.

## Changelog
:cl:
 * rscdel: Disabled Thermal Entropy.

### CODE REVIEW

**Comment by west3436** [comment]
There are many other options including #36024 and #36023 which can tone this system down but still retain some of its entertainment value. Removal should be the last step after we've attempted everything else.

**Comment by jwhitak** [comment]
Note: This does not affect temperature's effects on mobs. This only stops chemicals from trying to balance their temperature with their surroundings. This means microwave food will be permanently hot unless placed in a freezer/fridge, caramel similarly, stuff hit with a lighter a lot, etc.

**Comment by DrSnips** [comment]
Based

**Comment by KingofHONK** [comment]
Major skill issue also the alternatives are better.

**Comment by ghost** [comment]
> Note: This does not affect temperature's effects on mobs. This only stops chemicals from trying to balance their temperature with their surroundings. This means microwave food will be permanently hot unless placed in a freezer/fridge, caramel similarly, stuff hit with a lighter a lot, etc.

I forgot to test this with the microwaves, those still actually heat up the food. So do the coffee vendors. This still requires some code to be cut.

However food does not freeze in space or heat up inside of your backpack in a middle of a plasmafire anymore. This is a step in a right direction.
> There are many other options including #36024 and #36023 which can tone this system down but still retain some of its entertainment value. Removal should be the last step after we've attempted everything else.

Why keep it in the first place? It's frustrating, adds needless tedium (wait X seconds for Y to not harm you) and is absolutely in no way funny. It's lame and only exists to cause suffering.
> Major skill issue also the alternatives are better.

Wrong. Those are not alternatives, but half-measures. You will still suffer 2 minute slowdown because you ate something from your backpack after a trip to space or because you ordered some pizza from Cargo and confused the frozen Margherita for Blingpizza with the half-measures merged.

Let me make something clear: this system added literally nothing fun **in the first place.** No matter how much you keep tweaking this, you are not going to get anything funny out of it because this added 0 fun to begin with.

**Comment by hacker-on-steroids** [comment]
correct me if i'm wrong but doesn't deityheat just do the steam/ice overlay and minor temperature adjustments?
the burndamage is another thing #36023

**Comment by ghost** [comment]
> correct me if i'm wrong but doesn't deityheat just do the steam/ice overlay and minor temperature adjustments? the burndamage is another thing #36023

Not really. After disabling subsystems, you only need to revert some objects/items to their past behaviours for "deityheat" to stop having any effect on food.

**Comment by ghost** [comment]
done.

**Comment by jwhitak** [comment]
I intend to make a competing PR within a few days to simply remove chemical temperature affecting players. That way, only chemists have to care about temperature (for certain reactions), and we can keep the steaming/frozen food as fluff for the chef players.

Side note, this PR still doesn't remove any of that, and fridges will still cool stuff (though not to dangerous levels).

**Comment by SonixApache** [comment]
>the caramel complaints again

ah sweet, a schizo thread

**Comment by ghost** [comment]
> I intend to make a competing PR within a few days to simply remove chemical temperature affecting players. That way, only chemists have to care about temperature (for certain reactions), and we can keep the steaming/frozen food as fluff for the chef players.
> 
> Side note, this PR still doesn't remove any of that, and fridges will still cool stuff (though not to dangerous levels).

I mean, if you are going to do that you might as well disable the subsystems too since chemical temperature will no longer affect players, making all of the reagent containers' temperature changes a meaningless waste of CPU. But since your implementation will nullify all of the effects chemical temperature has on a player, please be my guest regardless.

Yes this PR does not remove steam/ice overlays, you can still heat/cool beakers on purpose as a chemist and have them visibly boil/freeze. I still need to do some additional testing with freezer lockers to see if they freeze the stuff inside though.

**Comment by DeityLink** [comment]
If your purpose really is to halt the impact of regular food and drinks on body temperature, then literally all you need to comment out is this proc. https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Holder.dm#L1047

Doing so would no longer cause eating frozen food to give hypothermia, while keep the visual stuff intact. **I've already suggested @jwhitak an alternative however, by having entropy proportional to atmospheric pressure when it dips below room pressure.** This would make food no longer instantly freeze while in space (we can snowflake it freezing anyway if it's on the turf directly, but this way it will no longer freeze in hands and backpacks which is what players _actually_ complain about)

**Comment by DeityLink** [comment]
Actually it's a 2 lines change so I did it myself: #36034

**Comment by ghost** [comment]
Like I said, yet another tweak. Only complete nullification/removal of all nu-temperature effects will make any difference.

**Comment by DeityLink** [comment]
any difference to what exactly?

**Comment by ghost** [comment]
ESL moment.

**Comment by DeityLink** [comment]
No no, please do elaborate for real. Your wall of text up in the OP is mostly about fire which is its own can of worms that this PR does nothing to address, and which is also only tangentially related to the entropy sybsystem.

> The fact that there have been over 9000 different tweaks and rebalances to this nu-fire-temperature subsystem and it still sucks ass is a definite proof it's shit and should be cut from the code entirely.

The entropy subsystem has had literally no tweaks whatsoever since its introduction. Wtf are you on about? #36034 is effectively its first tweak.

> Then, if someone actually capable and knowledgable about IRL fires makes it right we can judge if it would benefit the server in general or not.
> I for one did not enjoy constantly trying and failing to extinguish cigarette butts and burnt messes on chef's counter that round when one careless grue melted the entire station by accident.

If food auto-igniting is an issue, that can be disabled in one line change. Food auto-ignition was part of #35516, which as you might remember, was NOT the PR that added the entropy subsystem, the two were de-coupled. You could just revert those two lines in snacks.dm and food will no longer burn. Done.

image

> It was kino, yes, but this one good round when that lone bag of sugar in the Kitchen actually turned into caramel for the first time ever since this subsystem was introduced was not worth all of the pure suffering players had to endure in all of the previous rounds.

Entropy is about helping stuff reach room temperature you know? Sure that means if the room is an inferno stuff will warm up, but it mostly enables stuff to cool down rapidly. What "pure suffering" are you referring to? Because if it's about players taking burn damage when eating burning food and getting crit by it, that's from the pre-existing code by a certain Hinaichigo person. And I've got good news for you, because @Dacendeth 's PR (#36023) is removing that.

> Neither do I enjoy chemical pills being frozen in my personal medkit after I return from a space trip

Addressed in a 2 lines change by #36034 which again is **the first ever tweak to the entropy subsystem itself**.

> nor do I like waiting for 10 seconds after microwaving my donk-pocket for it to be edible.

Blow on it once or twice and it's safe to eat. Many other players like doing that (PrimeD and Blitzkaze come to mind),  Or if you don't want to use the shortcut, you could implement someone's suggestion (forgot whom) of making it so that trying to eat food at dangerous temperature automatically makes you blow on it unless you're on harm intent. There's always something to try.

> I hate how often I get to see the hot/cold temperature indicator in the right corner of my game screen in your average round. It's frustrating and, most importantly, it's NOT FUN.

ok

> I know they fixed the cigarette butts, yet my point still stands. Yesterday it was cigarette butts, today apparently it's paper bins, tomorrow it will be some other annoying and frustrating shit. Just cut this shit entirely.

Again this has nothing to do with the entropy subsystem, you're completely off the rails. And your only complaints on stuff actually related to the entropy subsystem are literally pic related: 
40bfb6a76627032773450ddee967be36

**Comment by ghost** [comment]
Sure.
> > I hate how often I get to see the hot/cold temperature indicator in the right corner of my game screen in your average round. It's frustrating and, most importantly, it's NOT FUN.
> 
> ok

Your entire argument collapses right here. You have never once elaborated on how this system is fun. I have elaborated on how this system is not fun several times.

The single mildly entertaining thing to have ever occured on the server involving this system was sugar bag turning into a caramel bag once during that round where one mature grue melted the whole station by accident. That's it. The amount of times this system caused pure frustration or tedium for the players? Countless - every single time somebody had to blow on food even though they've never had to previously, every single time somebody damaged themselves after nibbling on hot X, every single time somebody experienced a 2 minute slowdown after nibbling on cold Y, and so on and so forth. The ratio of funny to unfunny interactions is 1 to infinitely big number, which is an infinitely small number close to 0. 

Here's a simple chain of thoughts that every kindergartener can follow: this system is frustrating, it's not fun. We play videogames to have fun. No amount of tweaks and half-measures can somehow increase the fun value of something that wasn't fun to begin with. Therefore, this should be removed from the game. 

The nu-fires were at least hilarious on occasion and are still getting removed because it takes a few paper bins to make hallways uninhabitable and end the round for everybody. This though? This is dull, frustrating, unfunny shit that was never funny and as such should be removed from the game.

**Comment by jwhitak** [comment]
The system is fun because I can take frozen meat and cook it into a steaming hamburger.

**Comment by ghost** [comment]
That doesn't require an entire subsystem scalding players or giving them a frostbite, just the overlays. Simply make food that comes out of the freezers **look** frozen and food that comes out of the kitchen machinery **look** hot. Don't make it ACTUALLY cold or hot.

**Comment by DeityLink** [comment]
The system is fun because I can buy a cup of hot coffee and watch its steaming slow down over the course of a minute, making its heat feel tangible and the object in this video game ever so closer to an actual cup of coffee.

The system is fun because I can spot the meat that got thrown at the station by the last meat meteor shower on the other side of the window, see that it's frozen and be glad that I'm in a warm and pressurized environment.

The system is fun because I can put food in my pan over a fire and watch it steam up as it cooks.

The system is fun because food that just came out of the chef's microwave looks ever more delicious with that hot steamy look.

The system is fun because when I design a feature I actually try to put some thought into how players are gonna interact with it and discuss its mechanic both before, during, and after its implementation, and listen to the feedback that people ping me about. That's how I know that the main complaint about the system is the tangible case of trying to use pills, food or drinks while in space, and have now made a PR to remedy that.

The system is fun because players let me know that they like it and would rather see its flaws ironed out rather than it be removed altogether.

The system is fun because my PRs to improve it get thumbs up and yours to remove it get thumbs down.

**Comment by DeityLink** [comment]
> That doesn't require an entire subsystem scalding players or giving them a frostbite, just the overlays. Simply make food that comes out of the freezers **look** frozen and food that comes out of the kitchen machinery **look** hot. Don't make it ACTUALLY cold or hot.

And if you truly believed that then you would have enacted my suggestion up above of disabling the adjust_consumed_reagents_temp() which would have done exactly that, while preserving the visual aspects. Which you called "yet another tweak" and didn't elaborate.

**Comment by ghost** [comment]
> The system is fun because of a hypothetical scenario that never happened.
> 
> The system is fun because of an unfunny interaction that I claim to be funny.
> 
> The system is fun because ME ME ME ME ME!!! IT'S ALL ABOUT ME! HOW DARE ANYBODY INTERRUPT MY WORK?!

This is not your personal coding playground. This is a videogame inhabited by actual people, not by bots behaving how you like to imagine them behave. Get over your massive ego you lunatic. Try actually playing the game for once instead.

**Comment by jwhitak** [comment]
It isn't *your* playground either - it's everyone's. Feel free to fork and have your own world if you're not willing to have a discussion.

I can agree that the players are getting frustrated with chemical temperature stuff right now. I am too. Thus, tweaking the system and possibly straight killing temperature's effects on mobs. Complete disable is easy: dummy out one proc and kill two lines of code and all the effects on mobs vanish except for the hard coded effects like coffee. (Deity hates this solution but this lets us fix or ignore the broken chemistry heat system in peace without killing everyone with hot chips and cold coffee)

Also I like how the hot food cools down, how it can freeze in space or a cold room, etc. I feel the speed and effects need some tweaking but otherwise the system is workable.

**Comment by Kurfursten** [comment]
Forgot to close this when alternative PRs got merged

**Comment by ghost** [comment]
@Kurfursten Again, those weren't alternatives, those were half-measures. They didn't fix anything. For example, the food is still frozen in space, as a miner you still cannot make use of ambrosia you find on Asteroid in old crates or roundstart to the east of the mining outpost unless you go out of your way to waste 5 minutes you could've spent otherwise playing the actual game clicking away at a microwave trying to first heat the leaves up and then cool them down one by one (exactly what happened to me the other day).

Why do you keep entertaining this garbage? If people (and by people I mean a single quasi-collab I've never seen play chef and a petty script kiddie manchild responsible for this cancer) claim they like the steam/ice overlay so much then keep that overlay as a pure kitchen machinery/freezer locker sprite fluff. You don't need a whole subsystem that checks the temperature of every reagent container in the game and makes food/drinks dangerous to consume 4noraisin for that.

**Comment by DeityLink** [comment]
I read this and all I think is "hmm, what if miners could buy portable stoves from the miner vend?"

**Comment by Eneocho** [comment]
> I read this and all I think is "hmm, what if miners could buy portable stoves from the miner vend?"

That's exactly the space grill idea that kurf wanted to add to the lemuria crate. Would be good to have as a minervend item instead. It could heat food to room temperature and lock that temperature in for 2 minutes.

**Comment by Kurfursten** [comment]
> ... I've never seen play chef...

Who are you? I didn't know you played here github-user

**Comment by hacker-on-steroids** [comment]
2hotdogs

**Comment by ghost** [comment]
user1069
dffygrd
i hate neverplaying skids ruining the game for everybody else i hate neverplaying skids ruining the game for everybody else i hate neverplaying skids ruining the game for everybody else i hate neverplaying skids ruining the game for everybody else i hate neverplaying skids ruining the game for everybody else i hate neverplaying skids ruining the game for everybody else i hate neverplaying skids ruining the game for everybody else i hate neverplaying skids ruining the game for everybody else

**Comment by kilozombie** [comment]
Circle those icons in red a few more times, it will definitely make you look more level-headed

I can see your hand jittering and shaking on the mouse as you use Paint. Go outside

**Pull request closed without merging**
