### PR TITLE
MoMMIs can now remove cells from cell chargers.

### PR DESCRIPTION
**Pull request by Faptastic**
They can put cells in, but can't take them out.

### CODE REVIEW

**Comment by N3X15** [comment]
:+1:

**Comment by PJB3005** [comment]
Wait, could they not before, sure of it?

**Comment by Faptastic** [comment]
Absolutely sure, if it's hooked into the charger you can't do anything with it anymore until a human removes it for you, borgs can't of course since they lack hands.

Just wanted to start off the fork with a small fix that has been driving me insane everytime I play MoMMI.
I tested it ages ago, you can now rip them out and put them back in all day long.

**Comment by Probe1** [comment]
:+1:

**Pull request merged**
