### PR TITLE
Dorf map

### PR DESCRIPTION
**Pull request by PJB3005**
Adds a dorf map, it's all rock and unexplored mine (except for CC)

This is the stating base;

This should be a map of the dorf start base.

All other stuff should be procedurally generated, and isn't for this PR (that's why I made #3827)

### CODE REVIEW

**Comment by ComicIronic** [comment]
I question how big a roundstart this can support.

**Comment by CptWad** [comment]
what comic said
also it needs an accounts machine and AI core

**Comment by Midaychi** [comment]
Yeah this is more like a zlevel you can travel to rather than a full station.

**Comment by MercuryDoll** [comment]
I thought this was for dorfmode, which is basically extendedmode where players get to build a station from scratch and not a map for regular gameplay. I assume it would work with low to medium pop for timezones where nothing happens on the station.

Might need a account terminal and R&D parts, though.

**Comment by Kurfursten** [comment]
Firelocks should go below doors so you can click doors closed more easily

**Comment by PJB3005** [comment]
@MercuryDoll, that should be ordered from cargo, probably.

@ComicIronic @CptWad @Midaychi  It's supposed to be small, and an AI core would NOT be barebones, I can *maybe* add a recharger and a borg spawn, but that's pushing a 'barebones' theme.

**Comment by PJB3005** [comment]
Firelocks are now fixed, not gonna bother with a new image of the map since it's visible in the commit files anyways.

**Comment by CptWad** [comment]
You need the accounts database to use the vendor machines.
Also how do you deal with all the job types?
Do you just not allow an AI to play?

**Comment by PJB3005** [comment]
I'm not the guy that's coding this mode, gee, at any rate if the people want an AI they can make one later down the line

I made this map for pomf because he didn't want to do the mapping, pomf is coding this.

**Comment by d3athrow** [comment]
May want something a bit bigger. Imagine ministation that giacom made for tg but about half the size to start.
Accounts DB is required for money related things to work, cargo, ore redemption, vending machines, etc

**Comment by Kurfursten** [comment]
Another possibility is to leave the "main" station barebones, but have a "homebase" satellite for things like the AI core, the bar, the accounts database, etc. -- for logistics, and so people have somewhere to idle if there aren't enough hardsuits or something.

**Comment by RemieRichards** [comment]
@PJB3005 *loud whistle* https://github.com/tgstation/-tg-station/pull/9252

**Comment by ComicIronic** [comment]
Might as well have it, we can always make changes later if it turns out to be too small or something.

**Comment by PJB3005** [comment]
yeah, my issue with having a station that's maybe even bigger than tiny station (half the size of ministation) is that then you're running out of stuff to build, like, at that size you're gonna start needing atmos and shit

**Comment by FudgePucker** [comment]
It needs to have the external airlocks not lose air and be unstimulated, or it needs an atmos system.
A)Consider this, will gas miners be able to be ordered in dorf fort mode? They are not orderable in secret because, well, they can fuck over the station faster than you can say, OH FUCK ME THE KPA IS OVER NINETY THOUSAND.
B)If Miners can't be ordered, and the tiles are simulated, then you do need a full atmospherics.
C)If Miners can be ordered/tiles aren't simulated, then you can just have maybe a single canister and some vents/scrubbers/air alarms.
D)If there is no miners in cargo you still need a way to get gas miners for atmospherics. Maybe a locked crate that is locked by key code that has a random ass calculus/high level algebra question on it so that some chucklefuck who doesn't understand what they are doing doesn't open it in arrivals.

**Comment by PJB3005** [comment]
I'll switch the airlock to be cycling.

**Comment by Probe1** [comment]
math captchas?

**Comment by FudgePucker** [comment]
The problem with them just being orderable is that someone might order one with out fully understanding what they are ordering.
>Oh a gas miner? Does that mine things using tanks of gasses? That might be coo- OH GOD WHY IS THE PRESSURE OVER 90K?

People are stupid, and god might not always be there.
Having some type of quiz might be good, if they just look in the code for it, then they can't use the, Oh I didn't know what I was doing, when if they bothered to look in the code, THEY FULLY KNOW WHAT THE HELL KIND OF FORCE THEY ARE PLAYING WITH IF THEY OPEN THAT CRATE IN CARGO BAY.

Also giving antags gas miners in crates that can be emag'd won't end well.
Objective two is die?
Time to open a plasma miner in medbay after emaging open all the doors and welding open all the fire locks.

**Comment by PJB3005** [comment]
I updated the map, but now attempting to start a server with it doesn't work, the server hangs on startup forever

**Pull request closed without merging**
