### PR TITLE
actually limits borg names

### PR DESCRIPTION
**Pull request by MadmanMartian**
Previously you could have 'Validator 2: Validation Day: The Official Borg of the Movie - Validator 2: Validation Day: The Official Borg of the Movie' as a legitimate borg name.

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
What happened from then #15383 to now?

**Comment by MadmanMartian** [comment]
It never actually trimmed

**Comment by SonixApache** [comment]
What the fug?
`Reject_bad_name()` is actually a really shitty proc, and what my solution did was remove whitespace so you couldn't have " " or 
longname
 as a name.

**Comment by Probe1** [comment]
Ok

**Pull request merged**
