### PR TITLE
Revert "Revert "explosions inside bodies / open containers no longer remove all chems""

### PR DESCRIPTION
**Pull request by MadmanMartian**
**CHARCOAL IS ACTUALLY GOOD NOW YOU FUCKS**

Reverts vgstation-coders/vgstation13#18979

Wonder how long this revert chain will reach.

### CODE REVIEW

**Comment by aceedex** [comment]
We're reaching coder player liason levels of meme

**Comment by MusgardTiger** [comment]
Hopefully this is the last revert, communication problem which brought us here and it is solved. So we won't have to go through this sort of shit again. 

We will soon get a more sensible system of purging your system from chemicals instantly which isn't water + potassium so that feature is not going away. It is just gonna make more sense because safe 1u/1u reaction obliterating all chems in your system with no drawbacks doesn't make any gameplay or world sense.

**Comment by GreenHairedAssistantRickysSmellyDick** [comment]
@aceedex what ever did happen to the coder player liason

**Comment by MadmanMartian** [comment]
Who editted my PR to say 'CHARCOAL IS ACTUALLY GOOD NOW YOU FUCKS'?

**Comment by jknpj** [comment]
I mean you can see it next to 'edited by'

**Comment by MadmanMartian** [comment]
PJB Pls

**Comment by SonixApache** [comment]
*Szechuan Sauce*

\*edit*
oh shit this got merged and not closed, what the fug

**Comment by bathosbathtime** [comment]
What I valued in water potassium purge was that it used two different game systems, explosion code and reagent holding, to an effective degree in solving in game problems.  It was an undesigned solution to an in game problem that required knowledge of how the game functioned instead of reading design documents, PRs, or the like.  It was something born from the game that made it unique.  That there might be a special interaction that functionally servers the same purpose in the future does not make me feel better about this.  While there is merit in having special interactions, such a feature would be the opposite of what made water potassium interesting to me.
As far as I can tell, something neat was removed from the game and I still haven't seen a proper justification for why.  Charcoal IS better now, which means water potassium filled an even smaller niche.

**Pull request merged**
