### PR TITLE
Improve Box/Metaclub Roundstart SME Engine

### PR DESCRIPTION
**Pull request by gurfan**
StrongDMM_Wf9yzmCrM8

Notable changes:
- Reinforced floor in the chamber replaced with plating
- Cooling loop connected to the freezer loop (circled)
- Vents inside chamber replaced with HE junctions.

:cl:
 * tweak: The Box/Metaclub SME Room has been tweaked to remove some useless vents and connect the cooling loop.

### CODE REVIEW

**Comment by jwhitak** [comment]
Not cool. Literally.

~~Go playtest this and come back with a new PR after you realize how badly you've screwed up.~~

Ok, too harsh. But there's no functional cooling in that chamber. The default setup, while trashy, still technically works (lmao freezer cooling loop). Leave the vents in for those rookie engineers.

**Comment by DeityLink** [comment]
> 
> The default setup, while trashy, still technically works (lmao freezer cooling loop). Leave the vents in for those rookie engineers.

I agree, in my opinion the default setup should:

* not be optimal
* be relatively easy to replace
* still be functional

Those heat transfer pipes are here to "hint" at a better cooling system.

**Comment by Armadingus** [comment]
ugly

**Comment by BomberBro** [comment]
You WILL dismantle the same set of pipes every single round making the already-tedious engine process longer.
You WILL keep in completely obsolete and obtuse methods of SME use (How would a new player realistically ever figure out how to remove the vents, you can't unwrench them and they're not in the normal air alarm).

Keeping this is just silly. The default setup should not be some gygaxian nonsense that barely works because that's just confusing as hell for new players who think the engine is much more complicated than it normally is and tedious for older players who never use that setup anyway. If part of your basic engine setup is dismantling the mapped engine then there's a clear problem with the map, this sort of gatekeeping is stupid. If you don't think that it's a bad thing, well, take a look at the average crew manifest engineering list.

**Comment by jwhitak** [comment]
This is still gatekeeping because this is still not a functional engine. The standard setup literally works as follows:
1) put shard in chamber
2) turn on freezers
3) load up your rad collectors
4) turn on emitters

With this update, the engine requires wrenching pipes, requiring an RPD. It has only gotten more difficult to setup now...

**Comment by BomberBro** [comment]
According to my good friend pancakemines setting up the default shard setup on box causes it to delaminate in about 45 minutes. It's possible that this is wrong since it was relayed by somebody else, but currently I don't have any confidence in the normal setup.

**Comment by gurfan** [comment]
I'm going to put some HE junctions where the vents were, that way there should be at least some cooling.

**Comment by gurfan** [comment]
The HE pipes in the chamber will let the engine cool down without any setup, and they can be easily replaced without having to fiddle around with the atmospheric computer.

**Comment by kernikov** [comment]
100% yes to plating flooring

**Comment by ConfusedCactus** [comment]
As a regular engineer player, I agree with Bomber and Gurfan on this one. My least favorite part of engine-building is multi-step dismantling of worthless parts of prefab engines that suck like Box's SME. This seems like a good compromise where you can theoretically run the engine as is (at least temporarily, not sure how long a freezer-cooled setup will actually last) but it doesn't require as much annoying fiddling.

**Comment by jwhitak** [comment]
Fine, but color the connected pipenets the same color.

**Comment by Pancakemines** [comment]
I think if you're planning to do this you should change the nitrogen canister to a plasma one with no active vents it makes no sense to keep a passive coolant gas in the room. This would also help newer engineers as it would keep the engine running longer with absolutely no roundstart changes. You already have to drag the shard all the way over which is worse than most maps I don't see why you'd need to bang your head into a plasma canister the whole way too now.

**Comment by gurfan** [comment]
- Replaced the nitrogen canister in the room with a plasma canister.
- Colored the pipes around the freezers blue.

**Pull request merged**
