### PR TITLE
Adds 2 meats to the Trophy Meat crate

### LINKED ISSUE #13489: Can't get Crab Meat or Leafy Meat from Trophy Meats crate
This would be a really good intro to coding PR for someone new, all you have to do is add two lines to a list in supplypacks.dm

### PR DESCRIPTION
**Pull request by Shaska-**
Added Crab Meat and Leafy Meat to the Trophy Meat supply crate.
Fixes #13489

### CODE REVIEW

**Comment by Kurfursten** [comment]
That commit history is atrocious but I am very proud of you for learning git

**Comment by Shaska-** [comment]
Yeah, I know.
But I have no idea how to clean it up.

**Comment by Probe1** [comment]
Well there's two things you could have done.

1.  Made commits to your local copy of Bleeding Edge

2.  Made your commits tonight onto an old branch you had made a different PR with.

**Comment by Probe1** [comment]
@N3X15 was only interested in the fuckton of commit messages.  Since Github lets us squash them ourselves now that's not as big of a deal.  Ugly, and you should be careful in the future, but this times ok.

**Comment by Probe1** [comment]
codebaltfix

**Comment by Shaska-** [comment]
Alright, I'll see if I can't figure out how to make my next one cleaner.

**Comment by ComicIronic** [comment]
The two most important commands for keeping a clean history are:
 - `git rebase my-repo/Bleeding-Edge` - this is for updating your branch to my-repo's version of Bleeding-Edge without doing a merge to clutter history. Your commits will be put on top of the latest history, and you'll be asked to resolve any conflicts.
 - `git squash -i HEAD~n` - this lets you compress the last `n` commits. You then get a list of commits, with `pick` at the start of each line. If you change `pick` to `squash`, the commit and its changes are compressed into the commit above it e.g.

```
pick my first commit
squash my second commit
squash my third commit
pick my fourth commit
```

gives 

```
my first commit
my fourth commit
```

Where the first commit has changes for commits 1, 2, and 3.

**Pull request merged**
