### PR TITLE
Box tumor removal

### PR DESCRIPTION
**Pull request by SonixApache**
This removes the tumor from fore port (northwest) box maintenance.
The changes are straight-up lifted from #25060

here's a dmm overview, see the diff bot for more details(?)
notumorbox

[box]

🆑 
 - rscdel: Removed the tumor from box fore port (northwest) maintenance

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
pod bay back on its rightful turf, hoorah.

**Comment by SonixApache** [comment]
i looked at this and realized this is still a post-plosky version of maint, i'll update this later

**Comment by ghost** [comment]
cringe

**Comment by 9percents** [comment]
new good
old bad

**Pull request closed without merging**
