### PR TITLE
Clown Goblins

### PR DESCRIPTION
**Pull request by Shadowmech88**
Credit to Ch0c0latem00se for the sprites and the idea.

These were bussed in earlier this month, and I liked them so much I just had to make them a proper mob.
It's a child of cluwne, it moves faster and deals a tiny amount of brain damage with its honks. It can also slip people.
They have 100 health each. When killed, they drop a clown mask and clown shoes.

clowngoblins

Clown goblins can be created by combining a clown mask and clown shoes. This means that any killed clown goblin can be remade using the items it drops.
A clown goblin can be renamed by having a pen used on it.

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Does it have a movement sprite or you're just _**rotating** sprites_?

**Comment by Shadowmech88** [comment]
It has a movement sprite.

**Comment by S0yKaf** [comment]
:+1:

**Comment by ihadtoregisterforthis** [comment]
Why do they destroy tables though

**Comment by gbasood** [comment]
Also #9003

**Pull request merged**
