### PR TITLE
Lowers shuriken damage

### PR DESCRIPTION
**Pull request by Dacendeth**
I've had it up to here with these infinite ammo hitscan weebstars jobbieslayers. I make no attempts to hide that this is an ided pr but maybe you're sick of these things too.

:cl:
 * tweak: shurikens now do 20 damage when thrown instead of 30.

### CODE REVIEW

**Comment by Kromkar** [comment]
Absolutely antagonized

**Comment by SageOfLight** [comment]
Just remove ninjas if you're gonna go down this route.

**Comment by DamianX** [comment]
Can't believe you're removing ninjas. smh

**Comment by PrimeDSS13** [comment]
Currently, ninja stars will kill unarmored people in 2-4 hits. If they don't outright kill you, the internal bleeding probably will.
This change has been needed for absolute ages, because right now it's probably the strongest antag weapon in the game. There is no fun in dying the instant a ninja sees you with almost no time to react, and even with this nerf ninja stars will STILL be the most powerful item in the ninjas arsenal. That's just how strong they are currently.

**Comment by SageOfLight** [comment]
You're right. Replace them with floor tiles.

**Comment by BomberBro** [comment]
makes shurikens useless against armored targets, further cementing their role as the designated chemist-murderer

**Comment by Dacendeth** [comment]
> 
> 
> makes shurikens useless against armored targets, further cementing their role as the designated chemist-murderer

Hmm if only you had some other weapon that ignored armor.

**Comment by BomberBro** [comment]
Sec has two tasers and a flash, if you get close at best it'll cost you a projector. Ninja really is the jobbie murderer role and this doesn't fix that

**Comment by Eneocho** [comment]
Did the ninja on that rev round get you that bad?

**Comment by Optimism333** [comment]
Bomber has a point. A "I died plz nerf" pr won't fix ninja

**Comment by Eneocho** [comment]
One guy in the bread suggested to limit Ninja to rounds with active silicons so they do their original mission (to kill and shame all silicons).
However, the problem with this particular ninja round was not that the shurikens are overpowered, but rather that whomever was that ninja just hoarded the heads, slowly killing the round as nobody could be revived and thus could not fight the ninja. Remove the head storing from the ninjabelt or limit it to one or two heads for those two unlucky people you hate.

**Comment by PrimeDSS13** [comment]
Until someone is lined up to rework ninja (currently nobody), there's no reason we can't tweak what we currently have so it's less awful when it rolls.

**Comment by ShiftyRail** [comment]
image

"makes shurikens useless against armored targets, further cementing their role as the designated chemist-murderer"
"Ninja really is the jobbie murderer role and this doesn't fix that"

**Comment by SootyBear42** [comment]
Ninjas are glass cannons even if it's possible for someone to kill the entire station as one, they can always die easily they don't need to be nerfed, jobbie.

**Comment by SonixApache** [comment]
remove shuriken
replace with EMP kunai

**Comment by GreatBigFailure** [comment]
I do agree with this PR but the problems with ninja run deeper than shurikens. They're entirely designed around jumping out and surprise round removing people which is just awful. Without TC trades it's very difficult to do any gimmick that doesn't result in murder. You're either full on not an antag or you're a school shooter with ninja.

**Comment by Kurfursten** [comment]
Although Ninja as it exists now is purely a /vg/ creation, its design was strongly influenced by old-style antags that tended to be more clearly deadly threats. Nobody complains that you can't do gimmicks as blob. /vg/ HAS declined in this regards over the years but when you look back, that's how design used to be. That's why all the tot bundles are for mass murder and why Ei Nath existed. I personally think it's *fine* for ninja to remain as a killing-oriented antag just like rambler is the opposite, a non-killing-oriented antag. What I can say is that the cyber trophybelt originally did NOT hold human heads, someone PR'd that later.

You talk about lack of ninja play variety but the role has been begging for someone to make different schools of ninjitsu that specialize in different approaches for years. That's content though.

**Comment by Eneocho** [comment]
Someone on the bread suggested the following, which I find very cool:

A system to allow them to spend points to unlock ninja-themed items and abilities so they can decide their own playstyle and gimmicks. Beyond the tools they currently have, some items that could be added include;

• A variety of poisons with different effects, perhaps even throwing knives that could be coated with them if the ninja didn't want to poison food
• Caltrops, items which can be dropped to trip and bleed anyone running over them without ninja footwear
• That wooden bamboo thing, plays the YOOOOOOO sound effect, use it to dab on those you've defeated
• Ninja scroll, recruit another player as an apprentice, giving them a basic ninja outfit and a small pool of points to spend
• Specialized outfits, such as an Oni outfit designed for combat, a stealth outfit that grants invisibility in the dark, and so on

On top of that...

Mudra:
Mudra are the hand gestures that the people believed allowed the ninja to perform supernatural feats. I propose that they be added as essentially minor spells that require 2 open and intact hands to perform. Some examples would include:

• Invisibility, though the ninja must keep their hands empty to maintain it
• Log Substitution, the next time an attack would hit the ninja, they're instead teleported a short distance and leave a wooden mannequin in their place
• Instant Disguise, the ninja is immediately disguised as a (random?) member of the crew, but the disguise is ruined the moment someone attacks them
• The naruto run - lets you dash forward in a straight line very quickly, phasing through doors and mobs
• Lifesign detection, acts as thermal imaging until you move
• Wind Whisper, sends a message that can be heard by all ninjas and apprentices regardless of distance

**Comment by usnpeepoo** [comment]
just dodge lol

**Comment by WindowsErrors** [comment]
dread it, fear it, run from it, nerf it, they arrive all the same

the heavily motivated ghost player ninja WILL come and they WILL insta-kill you regardless of what you do as they macro 5 shurikens per second directly into your gluteus maximus, causing it to fly off in a graceful arc to the ground before exclaiming "Weakness." as they teleport up the hallways behind the next unwitting assistant, ready to do the same, all round every round, 24/7

**Review by Kurfursten — CHANGES_REQUESTED** [review]
@Dacendeth You want this merged, and I want to make a compromise that will please everyone. Here's my suggestion to make this palatable to all parties.

1. Keep the lowered throwforce, but have it do increased damage to silicons only, the way the hunting rifle works vs simple animals. This maintains the original feeling of anti-silicon play while making shurikens less punishing vs doctors in labcoats.
2. I will merge this PR to open up design space for new ninja content as has been discussed here. If no one makes a PR to add a new tool for ninjas in the next month after it gets merged, we can have a revert PR to vote on.

Hopefully this sounds fair to all parties.

**Comment by Dacendeth** [comment]
Damian is making something better.

**Pull request closed without merging**
