### PR TITLE
Fixes #6912

### LINKED ISSUE #6912: Come on now
image

> White
> Orange

Pick one

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
This crate's more trouble than it's worth.
Thanks @Exxion, though! I never actually made the dresses, they all were in the code.

### CODE REVIEW

**Comment by 9600bauds** [comment]
Jesus christ are you people STILL fixing the waifu crate

**Comment by ShiggyPiggy** [comment]
I've unleashed a demon.

**Comment by clusterfack** [comment]
I was serious last time

**Comment by ShiggyPiggy** [comment]
Technically, this isn't a crate problem, but an item problem.
As they say in Russia, я всех переиграл.

**Pull request merged**
