### PR TITLE
foam extinguishers now good

### PR DESCRIPTION
**Pull request by SonixApache**
more cool power for make room not plasmafire but not cool power for ice age

🆑 
 - tweak: Foam extinguishers are now once again effective at cooling reasonably sized rooms. They can't supercool things, and Very Large rooms will need actual solutions.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
foam

**Comment by PrimeDSS13** [comment]
foam

**Comment by beesil** [comment]
foam

**Comment by ghost** [comment]
foam

**Comment by Gazathor** [comment]
faom

**Comment by Irradiation** [comment]
foam

**Comment by cloutcode** [comment]
https://youtu.be/PLmD_69pXpk

**Comment by Kharkov72** [comment]
foam?

**Comment by drawsstuff** [comment]
foam

**Comment by strawberrytan** [comment]
foam

**Comment by jknpj** [comment]
Fix your CL/Title/desc

**Comment by SonixApache** [comment]
the :cl: is fine, you illiterate pasta

**Comment by Exxion** [comment]
What even happens if you have an invalid CL tag?

**Comment by Kurfursten** [comment]
You don't have to ping me twice, but during the ice age...!

**Pull request merged**
