### PR TITLE
The vending machines came out of the darkness.

### PR DESCRIPTION
**Pull request by DeityLink**
image

:cl:
* rscadd: Yet more machines have had moody lights implemented, with a focus on vending machines. All vending machines furthermore now emit a bit of light, helping them stand out much better in dark corners.
* rscadd: Added moody lights to the Vox Outpost's Trade Window
* tweak: Done some cleanup of smartfridge code, fixing some bugs, and removing some redundancy among other things.
* rscdel: Removed the redundant Seeds Smartfridge which was made obsolete by both the regular one, and the Seeds Extractor, on top of re-using the name and icon of the MegaSeed Servitor potentially leading to confusion.
* imageadd: Smart fridges also now all have unpowered and broken sprites.
* imageadd: Xenobiology's Slime Extract Storage now has its own sprite differentiating it from the other smart fridges.
* imageadd: The Secure Medical Storage smartfridge has a slightly different icon to help players differentiate it from the regular Smart Chemical Storage.
* soundadd: Added a sound for when you buy something from the Hot Drinks machine.

### CODE REVIEW

**Comment by Eneocho** [comment]
the beff glowing...
sovl...

**Comment by west3436** [comment]
Did you also implement this for the Lotto vendor in the bar?

**Comment by DeityLink** [comment]
image
yes, I did ALL the vending machines.

**Comment by DeityLink** [comment]
image

**Comment by DeityLink** [comment]
https://github.com/vgstation-coders/vgstation13/assets/7573912/316f6e2b-32fc-43ef-8553-ad42ce73b08a

**Comment by Eneocho** [comment]
> image

i feel they should emit a very faint light matching the average of the glowing bits instead of just having the oddly neon signs that don't make any light

**Comment by DeityLink** [comment]
1. they already emit a faint light
2. it looks better with a white light
3. in actual context the vending machines will rarely be in pitch darkness.

I might adjust the brightness of some of them depending on how large is their lit area. It'd make sense that the builder and zam vending machines would emit more light than the circus of value or barber vendor, while others like the vox seed vendor have a very weak light on purpose.

**Comment by GreatBigFailure** [comment]
The xenobiology smartfridge makes the extracts look delicious.

**Comment by Eneocho** [comment]
"DO NOT EAT THE SLIME EXTRACT" 
literally 1984

**Pull request merged**
