### PR TITLE
Changes minimum population requirement and removes maximum requirement for Synergy Station

### PR DESCRIPTION
**Pull request by wotisjanitor**
## Why it's good
I think Synergy does not fit very well in the lower pop maps. I think it fits much nicer in the medium pop to low-high pop category. I have noticed a decrease in pop and a lack of latejoiners whenever this map is being played during the mornings and late at night. Feedback is appreciated, as this is my first PR, thanks to @jwhitak for guiding me through the process. Also, I realize that this narrows when synergy could be played, and if people want it, I am open to increasing the maximum pop from 30 to infinity. 

## Changelog
🆑 
 * tweak: Synergy now requires 15 players online to be voteable.
 * tweak: Synergy now has no maximum player limit to be available for voting.

### CODE REVIEW

**Comment by nervere** [comment]
Might as well delete it if you're gonna set the population range from 20 minimum and 30 maximum.

**Comment by djkramer123** [comment]
If you're going to add a minimum, increasing to the maximum to 40 realistically is a must, because 20-30 is an lol

**Comment by jwhitak** [comment]
Remove the maximum. Do it. 70 pop Synergy. I'm ready.

**Comment by wotisjanitor** [comment]
I changed the maximum to 36. Is that enough, or should I just remove the limit?

**Comment by djkramer123** [comment]
I'd still say 40 is a fair range so the map still has a chance to get played occasionally. Also be sure to update the changelog

**Comment by DorainGrey** [comment]
I don't think there should be any limit, I want to see Uberhighpop synergy

**Comment by wotisjanitor** [comment]
> I don't think there should be any limit, I want to see Uberhighpop synergy

would you change your mind if I remove the limit?

**Comment by boy2mantwicethefam** [comment]
I like more opportunities for Box to roll

**Comment by gurfan** [comment]
15-No Max is what I would prefer

**Comment by wotisjanitor** [comment]
> 15-No Max is what I would prefer

By popular demand, there is now no maximum player count and the minimum is set to 15

**Comment by DorainGrey** [comment]
> > I don't think there should be any limit, I want to see Uberhighpop synergy
> 
> would you change your mind if I remove the limit?

It is done.

**Comment by pedr69** [comment]
wait, after this the 10-15pop maps are... only box and way?

**Comment by ShiftyRail** [comment]
I think this is way too restrictive and there's a clear debate on this (6/8). I'm not a fan of synergy but this is stealth-removal. It's not good for the game.

**Comment by wotisjanitor** [comment]
What are are you talking about? How is making it playable from 15 to infinity a stealth removal?

**Comment by wotisjanitor** [comment]
Also wow.... people don't agree on a PR? We gotta close it. Despite one of the votes being a permabanned shitter. 

edit: for historical purposes the vote was 8-6 when shifty left that comment

**Comment by Pastamadness** [comment]
I forgot to upvote it after the upper limit was removed.
Shifty is dumb.

**Comment by PrimeDSS13** [comment]
reopen the PR soy_rail

**Comment by Exxion** [comment]
Very strange closing

**Pull request merged**
