### PR TITLE
tgui security cameras, removed advanced security camera console

### PR DESCRIPTION
**Pull request by DamianX**
This also completely nukes the advanced security camera console because fuck that thing.
I've obtained permission to port this from @stylemistake, who made it for TG.

TODO:
~~- Lights don't work, everything is shown in full brightness. I tested this without southeast-asian lights and it worked the same, so it's not because of that. The original PR on TG also had this issue, funnily enough.~~
~~- Test adding new cameras, breaking existing ones, EMPs.~~

https://user-images.githubusercontent.com/6307265/132390182-0e2d8d05-4d95-4597-bb2c-3cc3b09efc6e.mp4

I'm opening this as a draft because I'd like someone to help with the TODOs

:cl:
 * tweak: Security camera consoles no longer take over the entire screen, showing the perspective of the selected camera inside a window, instead.

### CODE REVIEW

**Comment by BomberBro** [comment]
>This also completely nukes the advanced security camera console because fuck that thing.

You absolute buffoon, you fricken moron, you just made an unatomic PR

**Comment by ShiftyRail** [comment]
Can this be the advanced security camera and can we keep the old-style camera cycling? It's a lot better for taking pictures via cameras. Please.

**Comment by DamianX** [comment]
I think we might be able to arrange something for taking pictures. The simplest would be a button inside the tgui itself, but I think it might be possible to allow clicking on the viewport inside the gui to keep it just like it was before. TBD

**Comment by stylemistake** [comment]
@ShiftyRail have you tried making pictures with this new camera? Its viewport is clickable, and you can interact with things near you via this viewport.

**Comment by ghost** [comment]
wait, if we port this, does it mean we can also refactor bhangmeters away from the old minimaps and kill them for good? they take a minute or so out of server loading time just for 2 things, 1 being cut out now.

**Comment by DamianX** [comment]
Yeah, it's probably best to use deity's holominimap if we really want them anyway.

**Comment by ShiftyRail** [comment]
From my understanding, what you're doing is more or less creating an abstract object whose vis_contents are atoms in view of the camera.

Since light objects are drawn on a master_plane contained within the client, what you would probably need to do is to add the client's master_plane and dark_plane to the vis_content of the object, as they are not currently on the world's map, but rather contained in the client.

**Comment by stylemistake** [comment]
We fixed it on tgstation by simply changing the order of layers, and we also have [this bit](https://github.com/tgstation/tgstation/blob/3c4196e9600c625c1d5080e56365d5f19f61f21e/code/game/machinery/computer/camera.dm#L42-L48).

**Comment by DamianX** [comment]
Lights work
QJDKYQ1IF0

Photos work
LVcRo0rDBJ

Subspace tunneler works
https://user-images.githubusercontent.com/6307265/132736948-0d1b9369-b9bd-4423-9e41-d021f5ce282d.mp4

**Comment by Exxion** [comment]
Note that the removal of `VIS_INHERIT_ID` from more or less everything means that you can now click on objects visible on lower Z-levels. I do not know if this causes problems. Though honestly I didn't like that solution anyway and if it does cause problems we should figure out another way to fix them

**Comment by calzilla1** [comment]
Are pictures an internal thing or do you still need a physical camera to execute them

**Comment by DamianX** [comment]
Still need a camera

**Comment by Kurfursten** [comment]
confl

**Comment by DamianX** [comment]
gonfligds figsed :DDD

**Pull request merged**
