### PR TITLE
small rcd buff

### PR DESCRIPTION
**Pull request by unid15**
-you can choose the appearance of new airlocks via a verb(doesn't affect access
levels)

{{-RCD max matter is now 100}} //not anymore

### CODE REVIEW

**Comment by Probe1** [comment]
having limited capacity is a significant balance point.  the airlock seems interesting though.

**Comment by ComicIronic** [comment]
The RCD is meant to be useful in some way.
Its current drawback is being unusable by a dedicated construction engineer for having no storage.

**Comment by Probe1** [comment]
dunno as far as construction goes, the rcd is NOT the item you use for projects.  the rcd is the standby that you take and hope you don't need, when there's a breach and you need shit done immediately.  i feel the current capacity reflects that, and anyone that's going to build something is not interested in spending 300% more metal plus glass on building something a bit faster.

i've always felt it had plenty of storage for doing what it does best, plugging breaches where walls need to be put up 5 minutes ago and you don't have time.

**Comment by d3athrow** [comment]
Idea
Thing you wear on your back, when you click it or click the UI element it puts an RCD in your hand that is linked to the pack. Fill it with metal/glass/plasteel to fuel that RCD.

**Comment by Unfit** [comment]
i'll revert the max matter increase so that this PR only gives new airlocks with no other changes, and leave balancing for the future

**Comment by IratePirate** [comment]
I would allow RCDs to be put in pockets and on belts. That would serve as a decent buff I think.

**Comment by Probe1** [comment]
ooh throw in tile painters and RPDs too.  that's the one thing about rcd's that really makes me go "this is a pain in my fucking ass".  you've got your metal, rglass, rpd, rcd, internals box stuffed full of radios and extra wires and whatnot, and now you only have ONE free slot in your backpack.  being able to store rapid devices on belts would really help make them more enticing to people that wouldn't use them already.

**Pull request merged**
