### PR TITLE
surgeon switchtool now fits in medical belt

### LINKED ISSUE #7691: Surgeon's Switchtool doesn't fit in medical belt
Seems like an oversight

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #7691

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
I think someone said once this affects balance.

**Comment by 9600bauds** [comment]
We can safely disregard that someone

**Comment by clusterfack** [comment]
Well engineers get to carry literally everything in their toolbelt so sure

**Comment by Intigracy** [comment]
You can merge this bb.

**Comment by clusterfack** [comment]
The power creep is real

**Pull request merged**
