### PR TITLE
Cauldrons

### PR DESCRIPTION
**Pull request by MadmanMartian**
Thank you to @Blithering for the sprites

:cl:
 * rscadd: Adds Cauldrons. Made from 20 metal. They can hold 1000 units of reagents. Use help intent to add reagents, and anything but help intent to remove reagents.

### CODE REVIEW

**Comment by Irradiation** [comment]
I'm totally stealing this code for barrels now.

**Comment by AutismSpider** [comment]
can you dip stuff into it?

**Comment by Durgen** [comment]
someone should add them to wizard dens

**Comment by Blithering** [comment]
Any chance of a halloween only version that works like a poutine ocean, dip a container in to get a murky potion?

**Comment by MadmanMartian** [comment]
Yes

**Pull request merged**
