### PR TITLE
Revert cuck cube logging

### PR DESCRIPTION
**Pull request by DamianX**
The cube was uncucked in #17575

### CODE REVIEW

**Comment by jknpj** [comment]
But was it really uncucked? @Irradiation complained about it recently

**Comment by DamianX** [comment]
I don't see any report, do you?

**Comment by jknpj** [comment]
I do not.

**Comment by Probe1** [comment]
Not sure if the logging would detect the problem with that.

**Comment by jknpj** [comment]
the AI issue isn't related to this

**Pull request merged**
