### PR TITLE
Ventcrawling fixes

### PR DESCRIPTION
**Pull request by ComicIronic**
Ventcrawling now correctly starts from any pipe, not just vents and scrubbers.
This has allowed me to fix moving between pipelines : the images are now correctly updated when you change pipes.
Pipes now store their own images - this should help with processing cost, and lets them delete the image when they get deleted.
You can now see pipes in darkness.
Pipes are now readded when you log in as a ventcrawling mob.
Added a small sanity to remove_ventcrawl().
Also edited another thing that Pomf never got around to.
For a demo: http://puu.sh/hzTHa/d891c43328.webm

@RemieRichards

### CODE REVIEW

**Comment by clusterfack** [comment]
ANY pipe? So I can ventcrawl into a simple pipe?

**Comment by ComicIronic** [comment]
No, no.
You can't just start ventcrawling everywhere, but the ventcrawling backend no longer demands that you start at a vent or scrubber.

**Comment by clusterfack** [comment]
Alright, thanks that wasn't clear

**Comment by RemieRichards** [comment]
@ComicIronic cheers.

**Comment by ComicIronic** [comment]
Also made a change to let mobs see pipes in darkness. Having them see through dense walls doesn't seem possible immediately, though, because of how image locs work.

**Pull request merged**
