### PR TITLE
removed hard del from add_fingerprint

### PR DESCRIPTION
**Pull request by DamianX**
image

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Feels strange that lists can be hard-deleted like that.

**Comment by DamianX** [comment]
Why?

**Comment by ShiftyRail** [comment]
I would assume that `del(list())` just set it to `null`. I know BYOND's profiler is not a 100% reliable source, but I would expect something else than `/atom/Del()` to show up if a *list* was hard-deleted. :shrug: It doesn't look like it makes much difference in terms of results, so.

**Comment by DamianX** [comment]
The screenshot was meant to illustrate that `add_fingerprint` was expensive, not `atom/Del`, which is more expensive but also not the point of this.

**Comment by ShiftyRail** [comment]
Ah, sorry, misunderstood.

**Pull request merged**
