### PR TITLE
Adds Emergency Shuttle sounds

### PR DESCRIPTION
**Pull request by DeityLink**
Hyperspace begins (sound starts a few seconds before the shuttle takes off)
https://www.dropbox.com/s/ltb8t0hrr3rkzs9/hyperspace_begin.ogg?dl=0

Hyperspace progress (only plays to those who were on board when the shuttle took off)
https://www.dropbox.com/s/f898aezq2a0mj8z/hyperspace_progress.ogg?dl=0

Hyperspace end (plays right when the shuttle lands)
https://www.dropbox.com/s/hx1b1dauh6fbw93/hyperspace_end.ogg?dl=0

* soundadd: Added Emergency Shuttle sounds.

### CODE REVIEW

**Comment by SonixApache** [comment]
Hey while you're at it, how about sounds for the cargo shuttle?

**Comment by DeityLink** [comment]
Can be added later using those sounds.

**Comment by SonixApache** [comment]
👌 
That last link is the same as the middle link.

**Comment by small-boss** [comment]
you used the link for the hyperspace progress sound twice.
anyway, how does this sound while the jukebox music is playing on the shuttle?

**Comment by DeityLink** [comment]
@small-boss duh, fixed.

Also the progress sound doesn't loop, so as you can see it fades out after barely 19 seconds.

**Comment by DeityLink** [comment]
removed DNM label

**Comment by Kurfursten** [comment]
Significant buff to people who don't pay attention to the shuttle launch timer and forget to buckle in

**Pull request merged**
