### PR TITLE
fix rewriter typo

### LINKED ISSUE #8347: Rewriter drink description typo
Revision: 090bd47179bdfc32fc3c3e5cff3c6216138ee6f4 

The secert of the sanctuary of the Libarian...
Is this on purpose?

### PR DESCRIPTION
**Pull request by unid15**
Fixes #8347

### CODE REVIEW

**Comment by SonixApache** [comment]
that was quick :+1:

**Comment by unid15** [comment]
github's inbuilt file editor rocks

**Comment by 9600bauds** [comment]
This wasn't intentional, right?

**Comment by ghost** [comment]
It may have been but I disagree with it if it is

**Pull request merged**
