### PR TITLE
changes some threat costs and makes extended slightly more likely

### PR DESCRIPTION
**Pull request by Boolean-Buckeye**
changes some threat costs and makes extended slightly more likely. details in each commit. very simple self explanatory.

:cl:
 - tweak: roundstart traitors and wizards should be slightly less common
 - tweak: latejoin wizards and traitors should be slightly less common
 - tweak: midround wizards and blobs should be slightly less common
 - tweak: Extended and roundstart blob should be slightly more common

### CODE REVIEW

**Comment by Irradiation** [comment]
Put in a changelog you goof, otherwise people won't be able to tell what changed (assuming this gets merged).

**Comment by Kurfursten** [comment]
This won't even work, because the extended ruleset doesn't naturally roll, it's used for forcing a round type.

**Comment by boy2mantwicethefam** [comment]
extended ain't that likely to happen, due to shitcode extended only happens when the round's threat level is low enough

**Comment by SonixApache** [comment]
put this at the bottom of your OP

```
:cl:
 - tweak: roundstart traitors and wizards should be slightly less common
 - tweak: latejoin wizards and traitors should be slightly less common
 - tweak: midround wizards and blobs should be slightly less common
 - tweak: Extended and roundstart blob should be slightly more common
```

Personally,
:+1: on the extended threat change
:-1: on the rest of the changes

**Comment by Boolean-Buckeye** [comment]
> 
> 
> Put in a changelog you goof, otherwise people won't be able to tell what changed (assuming this gets merged).

literally just click the three little dots next to each commit there are only 4 commits and i put comments saying exactly what it does

**Comment by iFlashYou** [comment]
The changelog is for the bot to put it onto the serb so people can see what you changed

**Comment by Kurfursten** [comment]
Can I just say there is something absolutely humorous about someone from baystation rolling in to make balance changes to make extended more common and then getting annoyed when people tell him to follow basic repo standards for CL reporting that he would know about if he had opened *literally any PR* on our codebase to have a look?

**Comment by ghost** [comment]
>makes roundstart blob more common

what's the thinking behind this

**Comment by tuypo1** [comment]
Dynamic needs buffs not nerfs

**Comment by PrimeDSS13** [comment]
speedmerge it quick

**Comment by ShiftyRail** [comment]
This is one of the many PRs that try to toss numbers in the infernal machine that is dynamic
The problem is in the system, not the (barely readable, tbh) parameters

**Comment by Kurfursten** [comment]
Lacks support

**Comment by Boolean-Buckeye** [comment]
I'm not gonna lie, I don't even remember doing this, but 5 years younger me was pretty dumb. But it's also funny that somebody accused me of being from baystation for wanting more extended XD

**Comment by Kurfursten** [comment]
The comment wasn't because you wanted more extended, but rather based on the fact that your only past repo activity was, as of 2020, for Baystation. I will check in around May 2029 to see if you've replied to our ongoing conversation!

**Comment by Boolean-Buckeye** [comment]
It's really not necessary, I don't care about this anymore

**Pull request closed without merging**
