### PR TITLE
Mines.dm file cleanup

### PR DESCRIPTION
**Pull request by Probe1**
Adjusts stun time of effect/mine from 60 seconds to 20
Uses proper span classes instead of the font color shit from 2010
Updates procs to use current standard instead of vaporware

### CODE REVIEW

**Comment by Aurx** [comment]
Borrow TG's bomb disarming mechanics, those are fun.

**Comment by Aurx** [comment]
Oh, and the plasma mines work just fine as of a few weeks back.  
Some dude hit one, lit up the room, set off the welder tanks, vented the room.  Everything looked to be working A-OK.

**Comment by Probe1** [comment]
I just assumed because the N2O ones didn't work the plasma ones wouldn't work either.  That's good to hear.

**Comment by DamianX** [comment]
when

**Comment by Aurx** [comment]
When you steal his account and code it.

**Comment by Probe1** [comment]
I'll put off the vault and do it tomorrow it's been one thing after another that had higher priority.

**Comment by Aurx** [comment]
Is line 73 just a relic, or is that typecast without followup some bullshit needed to appease BYOND?

**Comment by Probe1** [comment]
Line 73 is why you shouldn't edit code in notepad++ while the same code is open in dreammaker.

**Pull request merged**
