### PR TITLE
Makes game work on 515, probably

### PR DESCRIPTION
**Pull request by Exxion**
Replaces the `.proc/` syntax with the new one and fixes TGUI. I don't think it breaks anything else but it's not extensively tested and also I was working on some other stuff in this branch which is not included here. Don't think there's any cross-contamination, but no promises.
DNM until the server is running 515. Don't update the server to 515 until 515 isn't fucked.

### CODE REVIEW

**Comment by Exxion** [comment]
SpacemanDMM doesn't support 515 yet, so the linters aren't going to pass. Perhaps that would be a good indication of when it's stable enough to use.

**Comment by adacovsk** [comment]
Just a note based on discussion: Exxion found out that `master_plane` does not work on 515.1596 which affects NVGs

**Comment by Exxion** [comment]
The bug he's referring to there is https://www.byond.com/forum/post/2837373, but there are several others not yet reported. The only other big blocker for us I'm aware of *right now* is that the skin's all fucked up in 1596. It's new to that build; skin is fine in earlier 515 builds. I'm sure more things will come up, though. Again, I wouldn't recommend updating *at least* until SpacemanDMM supports 515.
There's also a weird bug with our lighting system in `RenderIcon()`, but that's a new feature, so obviously we aren't using it yet.

**Comment by d3athrow** [comment]
haha time to merge

**Comment by pedr69** [comment]
JELP CANCT COMPILE
image

**Pull request merged**
