### PR TITLE
Winter scarves

### PR DESCRIPTION
**Pull request by ghost**
All the clothes added for festive stuff so far

As requested in the thread, 3 scarves, similarly coloured to the christmas jumpers, that can also hide your face when worn, fixed of missing icons and added to the "festive" crate.

Also act as internals because if a cigar can, why can't scarves?

### CODE REVIEW

**Comment by Kurfursten** [comment]
You should be able to stop the errors you're getting by finding the unchecked boxes next to cockroach.dm and whatever assembles are in and checking it.

Basically, you have the new files, but your local dreammaker doesn't know to include them

**Comment by ghost** [comment]
@Kurfursten I'm looking through, and it seems that cockroaches.dm and assemblies.dm doesn't exist

How the hell did I manage to screw a pull that bad?

**Comment by ghost** [comment]
@Skullyton discard all changes on your .dme file and rebase

**Comment by ghost** [comment]
Fixed it, image added

**Pull request merged**
