### PR TITLE
Adds an additional ability to the cult seer

### PR DESCRIPTION
**Pull request by MadmanMartian**
Now you can see a persons cult preferences

:cl:
 * rscadd: The cult seer talisman now reveals the cult preferences of a person, so you can choose your potential converts easier.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
No reason to make it restricted to the seer rune, it should be always on

**Comment by ShiftyRail** [comment]
It mixes IC and OOC

**Comment by boy2mantwicethefam** [comment]
Terrible reason to dislike qol

**Comment by SonixApache** [comment]
There's nothing ooc about seeing beforehand if someone's soul is resistant to conversion to the blood cult.

**Comment by Kurfursten** [comment]
I don't object to this but I do foresee a lot of people being annoyed because there are people who have cult as YES but choose to box if they're not in the mood to cult, or otherwise feeling angry/spiteful. Then again, that's the current state so I guess nothing changes.

**Comment by DeityLink** [comment]
I also used to think it was a bad idea since it threads the line of metagaming, but people already metagame who's a good potential cultist or not based on their static anyway and share lists, so this feature actually reduces the reliance on information from outside the game.

**Comment by Tehsapper** [comment]
there's nothing more frustrating for cult to waste time just to get boxed on.

**Comment by Chazach** [comment]
my question: if you can now just kill and shard people who have cult set to no, enslaving them in an even shittier role, whats the point of being able to set cult to no? aside from lucking out when a newbie converts you

**Comment by Ratvar** [comment]
Suggestion entirely unrelated to this feature: the boogalo: Make all cult conversions of banned automatically pull a ghost in.
I also would let cultists see preference at all times: everyone who complains about ic and ooc didn't even try to think around it with "This person *ingame* doesn't want to be converted on a spiritual level/ Narnar rejects their soul for eldritch reasons", why do they complain about that if they cannot explain stuff IC.

**Comment by ShiftyRail** [comment]
This toggle adds an element of impredicability to the convert
This change doesn't teach cultists to adapt to new situations and makes the most unfair of gamemodes even more trivial

It effectively tells the cultist to "shard this bastard" rather than attempting to convert, making the toggle essentially without object 

If this goes through, it's only logical to remove cult preferences alltogether

**Comment by MadmanMartian** [comment]
Same goes the other way with security HUDs. 

If you see a person you had previously given an implant and they're lacking one, you can kill them as you know they're cultist and have been converted (assumedly). If you see somebody who hasn't got an implant, you can test them with an implant. If you see somebody with an implant, you know they're not going to shoot you.

I was just coding this as some anons in the thread had said there should really be a way to know if somebody they've put in the effort to capture to convert isn't going to just become an integer increasing and a box of blood.

**Comment by ShiftyRail** [comment]
Tasing, processing, keeping tabs on someone and then happening on them again without the green square isn't comparable to knowing in advance if you have to use a soulstone or the rune, because one of those actually warns the cultist that he should avoid crossing paths with sec again.

**Comment by MadmanMartian** [comment]
You cross four of the five of your requirements off by having a shotgun instead of a taser, which is common practice due to there not being a method of deconversion.

**Comment by Allspice** [comment]
nice desu

**Comment by Blithering** [comment]
I like the idea of conversions pulling in a ghost if the current occupant denies conversion, easily explainable IC as demonic possession. Boxing should be reserved for when they really can't find someone to fill the role.

**Comment by MadmanMartian** [comment]
I really don't see this getting in even with positive votes

**Comment by SonixApache** [comment]
did you ask @Probe1 or any of the other collabs to make the call?

**Pull request closed without merging**
