### PR TITLE
Sanitize tcomms machine inputs

### PR DESCRIPTION
**Pull request by nervere**
lol

https://user-images.githubusercontent.com/26285377/206887728-6b316257-eb31-4e02-95ab-32ee3e0ac88e.mp4

### CODE REVIEW

**Comment by Exxion** [comment]
RIP U+202e fun
Unless `reject_bad_input()` doesn't sanitize that

**Comment by nervere** [comment]
Yeah, it rejects that with a whole range of other stuff.

**Comment by pedr69** [comment]
might also fix the one where nervegas characters were put into the server names and unable to be reset

**Comment by nervere** [comment]
> might also fix the one where nervegas characters were put into the server names and unable to be reset

Elaborate, please. I'm not sure what that means or how to replicate it.

**Comment by pedr69** [comment]
couple months back someone put 30 something characters of zalgo/emoji into the common frequency name(and all the other ones too)
the radio was fucking unusable because it was all just vomit

trying to multitool it back didn't work, neither did deconstructing the servers

**Comment by nervere** [comment]
> couple months back someone put 30 something characters of zalgo/emoji into the common frequency name(and all the other ones too) the radio was fucking unusable because it was all just vomit
> 
> trying to multitool it back didn't work, neither did deconstructing the servers

I'm able to replicate this but I'm not sure how to fix it. You'd think `reject_bad_text()` would stop zalgo characters, but no.
Should probably just ahelp it when that happens and an admin can fix it with a single varedit.

**Comment by Eneocho** [comment]
Don't take away the zalgoposting from me please... I've already lost so much, let me be the clown with the h̷̷̵̙̯̗̖̭̭̯̰͇̘͖̾ͪ̒̈̋ͩ̌̎̓ͨͧ̀͆́́͘o̶̘͙̩̝̘̩̘̟̓̀ͯ̿̌ͯ̏͛͑̐̂̈̀ͦ͡ṅ̷͉̙̻̖̫̞̋͛͑̑ͬ̅̑ͦ̊̄̿̄ͣ͂͞k̵̡̧̳̱̙̞͚̖͙̈́̈́͗͐̒̒ͪ̍̕͢ͅͅ job title.

**Comment by nervere** [comment]
> Don't take away the zalgoposting from me please... I've already lost so much, let me be the clown with the h̷̷̵̙̯̗̖̭̭̯̰͇̘͖̾ͪ̒̈̋ͩ̌̎̓ͨͧ̀͆́́͘o̶̘͙̩̝̘̩̘̟̓̀ͯ̿̌ͯ̏͛͑̐̂̈̀ͦ͡ṅ̷͉̙̻̖̫̞̋͛͑̑ͬ̅̑ͦ̊̄̿̄ͣ͂͞k̵̡̧̳̱̙̞͚̖͙̈́̈́͗͐̒̒ͪ̍̕͢ͅͅ job title.

I'm pretty sure the only thing that stops you from doing this is character limit on names (52), which isn't something this PR touches. I have no intention of trying to block zalgo text anyway, firstly because that's lame and secondly because that sounds annoying to do.

**Pull request merged**
