### PR TITLE
Fixes #12915

### LINKED ISSUE #12915: eclair sprites are fucking massive
#### Description of issue

They are larger than mobs

#### Difference between expected and actual behavior

To be regular sized

Its bigger than the nuclear bomb

#### Steps to reproduce 

spawn an eclair

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #12915
Adds giant eclair

### CODE REVIEW

**Comment by PJB3005** [comment]
How can you even call this a bug fix.

Now you're literally going "shit I ran out of low hanging fruit to fix."

**Comment by ghost** [comment]
It actually is a bug fix, let me tell you why

**Comment by ghost** [comment]
@Probe1 convinced me to fix this bug so I did 🤷🏻

**Comment by Probe1** [comment]
It was a bug.  People liked it but it was still a bug, so I asked Celt to take care of it so it freed up my time to do the taxi vault.  

Maintaining the functionality as a fun secret item was icing in the eclair, but fixing the GIGANTIC SPRITE was a bugfix.  A 2 in 1

**Comment by Exxion** [comment]
It was a sprite issue, not really a bug
But who gives a shit?

**Comment by Probe1** [comment]
I do when I'm trying to map and some goofball added shitty sprites.

AND IT NEVER GETS FIXED CAUSE LEL ITS FUNNY GUYS

**Comment by Exxion** [comment]
No, I meant who gives a shit whether or not it's actually a bug

**Comment by Probe1** [comment]
Oops.

**Pull request merged**
