### PR TITLE
Added 15 new hair options courtesy of Fury McFlurry

### PR DESCRIPTION
**Pull request by VelardAmakar**
http://ss13.pomf.se/forum/viewtopic.php?f=9&t=1834
img

the icons in that image are white but they have since been changed to conform with the existing system
Fury did a really great job on these

### CODE REVIEW

**Comment by ComicIronic** [comment]
That's a lot of animu.

**Comment by FuryMcFlurry** [comment]
Hehe, I would love to see them added. Also the bigger the hairstyles, to more chance you get clicked on. I would say these hairs are balanced gameplay wise

**Comment by d3athrow** [comment]
Great more floor length shit

**Comment by VelardAmakar** [comment]
makes you trip if you have it

**Comment by FuryMcFlurry** [comment]
you know, you could remove the shitty ones you don't like. I'd be cool with that.

**Comment by ZomgPonies** [comment]
https://github.com/ParadiseSS13/Paradise/pull/722

We personally removed 3 shitty ones and merged the rest.

**Comment by d3athrow** [comment]
Circled ones are the ones i'm personally against as it feeds the flashy, snowflake customization that plagues floor length hair braid with bubble gum pink hair fuck!

**Comment by FuryMcFlurry** [comment]
Back when I was spriting for hippiestation, those 2 were created to make the dev chat vomit @d3athrow. Maybe I went overboard with them. Ill ask velard to remove those 2.

**Comment by VelardAmakar** [comment]
removed the undesirable hairstyles

**Comment by MercuryDoll** [comment]
FUCK YOU I LIKE THE MEGADRILLS!

**Comment by FuryMcFlurry** [comment]
I would see that it somehow broke, http://i.imgur.com/yBrR2jq.png

**Comment by SangriaMonkey** [comment]
No keep the drills gone they're obnoxious.

**Pull request merged**
