### PR TITLE
Island Station Release Candidate

### PR DESCRIPTION
**Pull request by BurntDevil**
[<general>]

**Welcome to Island Station.**

Island station is a medium sized station. It is comprised of five sections, called islands, connected at the middle via an arrangement of bridges. On the exterior perimeter, secondary connecting junctions, called structs, also house secondary functions, such as recycling facilities or the new shuttle fabrication dock. Please familiarize yourself with the layout of your new station with the following schematic.

<a href="https://imgur.com/64IyWMw"></a>

Island Station has been inserted into orbit in support of a nearby shipyard tasked with the repair of the light exploration ship NTV Horizon, a smaller vessel named after the Horizon Class vessel you may have previously served on. Its undergoing repairs and refit, but will serve under your command as a base of operations for Research and Mining activities in your sector. Please familiarize yourself with the outpost and the vessel with the following schematic.

<a href="https://imgur.com/8eO2PCy"></a>

Reporting stations have detected a long range freighter flying under the flag of the Shoal, believed to be the Vox's means of operating in the area. We believe they are attempting claim of part of the asteroid field surrounding the shipyard. The Shoal's liaison for the sector states they are open to trade with the station and its outpost, and have been given docking clearance with the main station. Please treat the trade staff with all due respect one would give to the Vox by keeping them out of critical areas, especially the shipyard and the station vault. Please familiarize yourself with their vessel, the former freighter SS Turducken.  

<a href="https://imgur.com/pkYu1iL"></a>

Island Station is a new class of station with many experimental features. Shakedown cruises over the following shifts will help determine viability of this class of stations. Please direct all feedback through the due and proper channels so NT Stationworks can make adjustments and refits to future stations of this class.

Have a wonderful day at Nanotrasen, where the research doesnt matter and the credits are made up.

Jet Marson, NT Shipyard liaison, Central Command, Tau Ceti Sector 
NT-ID: 476913379000

:cl:
 * rscadd: A new class of station has been commissioned and ready for trials. Welcome to Island Station.

### CODE REVIEW

**Comment by SonixApache** [comment]
So what kind of experimental features are we talking?

**Comment by BurntDevil** [comment]
A number of new shuttles, a shuttle fab yard, some other oddball stuff to explore on your own.

**Comment by Eneocho** [comment]
Wasn't it actually called "NRV Horizon"? NRV instead of NTV.

**Comment by Viciousaurus** [comment]
Getting Wheel vibes from this, mainly that it looks huge and confusing to navigate. Both Wheel and Snaxi made evident separating the station in chunks is a risk because it makes vital interaction between departments a hassle.

On the other hand, that is the fanciest Trader Den I've seen. Could lead to some fun gimmicks inviting the crewmembers over.

**Comment by Eneocho** [comment]
I'm ok with this as long as it is a highpop only map. Lowfat was allegedly shrunken down and it feels massive and empty most of the time.

**Comment by BurntDevil** [comment]
For reference, LFBagel vs Island

<a href="https://imgur.com/Ayp0sah"></a>

**Comment by ghost** [comment]
I have my doubts that this map will play well, but I acknowledge all maps are products of immense effort and deserve a chance.

**Comment by SonixApache** [comment]
I am very interested in how this map will play, and I think the off-station maps are very nice.

**Comment by ghost** [comment]
remember to add the map to .github/workflows/ci.yml so it actually compiles in pr checks @BurntDevil

**Comment by Intigracy** [comment]
.github is ignored by default, your change (if you made one) didn't commit.

You could edit it via the web editor by opening this link and editing the file, then pull on your local copy of the branch.

**Comment by DeityLink** [comment]
Always glad to see new maps, however that's gotta be a top contender for the worst Virology lab. Here's some constructive criticism of my bones with it.
* No Viro-maint so you have to run all the way across medbay to get to safety in time from Rad Storms
* No back room either, even though it's not strictly necessary it gives some breathing space and also another exit to the lab when being chased.
* 4x5 of empty space while every furnitures/machines are lined up against the walls
* why the plasma glass windows/doors for the monkey pens but regular glass for the space window?
* those random double layers of r-walls and the overall very "square" shape of it
* no fire alarm/extinguisher cabinet, not very OSHA compliant
* fetching a monkey from the pen potentially exposes them to flying pathogen

Check Lowfat Bagel's viro for some ideas.

As for the rest of the station I guess I'll have more feedback once I've played on it.

**Comment by BurntDevil** [comment]
I'll remind you that this viro is the one you designed for my remap of horizon. Plus the patient rooms are rad proof. Ill add some fire equipment and a secondary window+shower for the pen.

**Comment by Kurfursten** [comment]
I tend to agree the walks are too long and too many airlocks to get anywhere, but it's in Pomf's hands now if he compiles the dmb

**Comment by WindowsErrors** [comment]
when i heard the name i thought this was gonna be like the map from GTA vice city but i guess everyone will have to settle for this

**Pull request merged**
