### PR TITLE
Lightbulb Removal Oversights

### PR DESCRIPTION
**Pull request by beesil**
[powercreep][immursions] 
Insulated gloves are now more insulated.

:cl:
 * tweak: Powered lightbulbs can now be removed by people wearing insulated gloves, or who's active hand is robotic.

### CODE REVIEW

**Comment by brndd** [comment]
The black gloves metaclub will remember this.

**Comment by SonixApache** [comment]
\>glovecreep
"no"

**Comment by SonixApache** [comment]
reasons to ever wear black gloves instead of insulated gloves:

**Comment by beesil** [comment]
@SonixApache its called fashion, look it up

**Comment by SonixApache** [comment]
just paint your yellow glubbs dude lmao

**Pull request merged**
