### PR TITLE
Centcom Officials such as ERT now have a custom icon on SecHUDs

### PR DESCRIPTION
**Pull request by DeityLink**
image

:cl:
* imageadd: Centcom Officials such as ERT now have a custom icon on SecHUDs, instead of appearing as unknown.

### CODE REVIEW

**Comment by tinysaturn** [comment]
N

**Comment by DeityLink** [comment]
You've got problems

**Comment by xeroxemnas** [comment]
I

**Comment by SootyBear42** [comment]
G

**Comment by pedr69** [comment]
G

**Comment by ErrorsWindows** [comment]
e

**Comment by Kurfursten** [comment]
Spam replies are /v/ culture

**Comment by Pastamadness** [comment]
I'm black

**Comment by nillkiggerstroonskilluselves** [comment]
N stands for nigger because he is a glow in the dark nigger haha
-this post has been approved by soy slurping github janny trannies-

**Pull request merged**
