### PR TITLE
Fix for artifact

### PR DESCRIPTION
**Pull request by clusterfack**
Fix new artifact issue with mobs without hands taking stones, fixes it not being wrenchable either.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Don't forget attack_paw.

**Comment by clusterfack** [comment]
Why would I want to block monkeys from taking one?

**Comment by ComicIronic** [comment]
You should include a check for aliens in attack_paw, since they aren't meant to have the dexterity for smaller items.

**Comment by clusterfack** [comment]
As far as I've seen aliens are already blocked from using any kind of machinery in attack_hand

**Pull request merged**
