### PR TITLE
Shutters are now layered below tables while open

### PR DESCRIPTION
**Pull request by DeityLink**
Before:
image

After:
image

:cl:
* tweak: Shutters are now layered below tables while open so they stop hiding display of items on counters.

### CODE REVIEW

**Comment by BomberBro** [comment]
Does this include closed shutters and would this allow you to teleport over shutters via grabbing somebody and putting them on the table?

**Comment by DeityLink** [comment]
> 
> 
> Does this include closed shutters and would this allow you to teleport over shutters via grabbing somebody and putting them on the table?

My man, I don't want to make you panic of anything but
itsalwaysbeenpossible

**Comment by BomberBro** [comment]
This also works for blast doors thanks to b*rrycode since you can put tables down by clicking next to you.

**Comment by DeityLink** [comment]
> 
> 
> This also works for blast doors thanks to b*rrycode since you can put tables down by clicking next to you.

:agony:

Well frankly I suggest you make an issue about it, but regardless it's ultimately unrelated to this PR.

**Pull request merged**
