### PR TITLE
Robotic limb unsucking

### PR DESCRIPTION
**Pull request by MadmanMartian**
- Adds an organ_malfunctioning flag
 - EMPs turn this flag on. If the limb is already malfunctioning, it gibs.
 - Non-organic limbs no longer feel pain.
 - Non-organic limbs no longer bleed.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
So EMPs, the main downside of robotic limbs, now only disable your limb for a total of 60 (sixty) seconds unless you get 2 EMPs in a row?

That'sa pretty big buff

**Comment by ddolll** [comment]
- nopain
- 2/3 base damage-able to be repaired virtually instantly, especially since >nopain means nothing is stopping you
- can only lose them from multishard blasts, really bad luck, the dumbest and most specific setups, or people with terrible choices in traitor items

Unless you're regularly rolling chememes or don't expect to have maintcrawler gear, is there any reason to avoid robolimbs with these buffs?

**Comment by MadmanMartian** [comment]
Trying to find a balance. Currently nobody takes robotic limbs BECAUSE of the EMP possibility of your arm just popping off.

Was thinking 'what if, like other electrical devices, it just stops working for a while then reboots itself.' and then realized that if that were the case, yeah there would be little to no reason to ever not have them, so thought if a person is purposely trying to disable a person, they shoot twice. So, the supermatter going critical isn't going to leave nuggets, but somebody with an EM rifle trying to disable roboticist-gone-terminator can still take them down.

Work with me here, what should I change? Can't work with just rampant 😕 emojis

**Comment by MadmanMartian** [comment]
Update:
 - Now your robolimb will explode if it's got a high amount of damage to it, or is malfunctioning, when EMPed

**Comment by ghost** [comment]
> Currently nobody takes robotic limbs BECAUSE of the EMP possibility of your arm just popping off.

They were added as a setup choice by Bay for the ARR-PEE choice, and I've seen plenty of people (myself included!) running around with them for just that reason. Otherwise, because they're playing a brute-vulnerable species and want to offset that somewhat. That, and they're easy to repair with basic tools.

~~I guess it's fine if you really want to change it, but I liked the annoyance of pain-malfunctioning causing you to drop things constantly.~~

**Comment by MadmanMartian** [comment]
The malfunctioning causing you to drop an item will still happen.

**Comment by ghost** [comment]
Oh, I only skimmed the file changes, now I see it. That's great, then.

Non-organic limbs paincritting you was only a thing with roundstart limbs before, wasn't it? If so, then that's just a bugfix, I guess. I think most of it's a good idea, but it could probably do with some extra weaknesses because, as the others said, it's a pretty big buff.

Sadly, I can't suggest anything at the moment - most of the ideas I've had in the past for robolimbs would be clunky to implement and likely more of a pain than it's worth.

**Comment by Dacendeth** [comment]
What if a single emp permanently disabled full limb use, but a "surgery" was able to fix it. Something simple that you have to get someone else to perform, multitooling it to reboot it manually perhaps. That way you keep the weakness of a single emp fucking you over, without it being as punishing as the limb gibbing right away that we currently have.

**Comment by MadmanMartian** [comment]
That is a good idea. I'll get to it

**Comment by DrSnips** [comment]
I like the multitool to reset them after emp idea. Legs getting emp'd will still floor you but with crawling I think being floored until someone helps you is fine. If you have all robolimbs, get emp'd, and can't crawl that's on the player who made that choice to be very weak to emps.
I wouldn't make it a surgery thing but rather a simple application of a multitool to the limb like bandaids.

**Comment by Blithering** [comment]
I like the idea of robolimbs needing recalibrating 'surgery' when heavily damaged or EMPed, preferably from robotics.

**Comment by MadmanMartian** [comment]
Update:
 - Robolimb damage no longer contributes to shock pain
 - Robolimbs malfunctioning from a direct EMP can now be recallibrated via a multitool

**Comment by MadmanMartian** [comment]
I may have misinterpretted the request. The user can reboot their own limbs.

This does mean that if BOTH of your arms malfunction, however, you're pretty screwballed

**Comment by Blithering** [comment]
Well I was kinda hoping it would require taking it in to the shop for repairs so to speak and give the roboticist something else to do other than plan their next mech rampage, multitool works too.

**Comment by ddolll** [comment]
You can just crawl to a chair if you lose both legs, all you need is one organic arm
They're still almost strictly superior outside of emps

**Comment by SonixApache** [comment]
this is a bit late but did you happen to fix / implement the emag thing where you can stealthily emag people's limbs to make them explode on damage?

also, @Intigracy,  how the fuck did you manage to merge this relatively major change to specific mechanics when there's no 🆑

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is even more OP than it was in the first commit

**Comment by SonixApache** [comment]
consider:
 - re-add pain; the limbs are part of your body, pain is normal (and useful) for bodyparts
 - make repairing take longer than 0 seconds
 - losing a robot limb should be very painful
 - something to offset the fact that you could hit a full robolimber in every limb with a laser and not crit them

**Comment by strawberrytan** [comment]
@sonixapache
I actually think it would be better if robolimbs didn't feel pain but also didn't give the "my arm hurts" occasional feedback when damaged, and the limb on the health doll muted like a severed limb

**Comment by bathosbathtime** [comment]
Wait, do robolimbs not have pain but have feedback for damage (read: pain)?

**Comment by strawberrytan** [comment]
I don't know if they still do but for the longest time this is how it worked: let's say you have a robot leg with 20 damage. 

Your screen edges won't change colour, but you will occasionally get a "my leg hurts" message in chat as well as the flashing injury indicator on the health doll until it's fixed.

**Pull request merged**
