### PR TITLE
deff cargo tuneup

### PR DESCRIPTION
**Pull request by bthomas2**
dcargo

:cl:
 * Deff: added firelocks and more conveyors to cargo, moved vent

### CODE REVIEW

**Comment by SonixApache** [comment]
image
mapdiffbot for clarity

While you're at it and if you're still up for it, can you add floor toles to the cargo vending machine? Currently the machine stands on bare plating.

Also I think your :cl: has to be at the end of the PR, with nothing after it - could be wrong but haven't been corrected on that one yet

**Comment by Dacendeth** [comment]
Yes fix the cargo floor thing, I think the cargo vending machine is ontop of bare floor on everymap though.

**Comment by tuypo1** [comment]
Fuck firelocks

**Comment by SonixApache** [comment]
:+1:

**Comment by Kurfursten** [comment]
conflicts; sorry, the scale of the wire change was so much larger and also had far more support

**Comment by Kurfursten** [comment]
brutal

**Pull request closed without merging**
