### PR TITLE
adds O as the ooc hotkey in hotkeymode

### PR DESCRIPTION
**Pull request by PaulRitter**
[qol]

adds "O" to be the ooc hotkey in hotkeymode

:cl:
 * rscadd: The O-key can now be used to bring up the ooc window in hotkeymode

### CODE REVIEW

**Comment by Blithering** [comment]
The circle is complete

**Comment by ShiftyRail** [comment]
It has been explictly removed
Edit your .dmf if you want it

**Comment by PaulRitter** [comment]
why was it explicitly removed?

**Comment by PaulRitter** [comment]
no

**Pull request closed without merging**
