### PR TITLE
Chapel Vendor

### PR DESCRIPTION
**Pull request by Arthurdentist**
Adds a vendor for the chaplain. Far from done but throwing this up now so I can get early feedback and to catch stupid mistakes faster. 

EDIT: Updated sprites courtesy of Skowron, cheers mate

chapelvend

chapel deny new

Sprites suck but will probably be changed before this is finished.

Things to do: 
- Ensure this is constructable.
- Ensure everything works.
- Add vendomat pack to Cargo as an order-able item. 
- Anything else I have forgotten.

### CODE REVIEW

**Comment by Probe1** [comment]
:+1:

**Comment by Skullyton** [comment]
:+1:

**Comment by Probe1** [comment]
travis failed to compile the maps you didn't edit.  interesting.

**Comment by Shadowmech88** [comment]
Seeing as all the special clothes are in the vendor, will they now be removed from the chaplain's locker?

**Comment by Arthurdentist** [comment]
the entire locker will be removed, that is the aim Shadowmech

**Comment by DeityLink** [comment]
I'm not fan of the sprite, think you could have it be darker like the clothing vendors in the locker room?

Other than that I'm happy we finally can remove those heaps of clothing from the chaplain's closet.
Now the ideal would be to have the content of the vendor depend on which religion the chaplain took.

**Comment by Arthurdentist** [comment]
Yeah I don't like the sprite either but I'm real busy at work so I'll update it at the weekend. If you have a better sprite I'd be happy to use it.

**Comment by FudgePucker** [comment]
A minor balance concern might be a somewhat constant source of holy water by making new vending machines if there isn't a chaplin. If a blood rune is found in maint or a corpse with no blood is found, you would be able to slowly produce holy water one bottle at a time.

**Comment by Shadowmech88** [comment]
Holy water can already be mass-produced from Groans Soda machines. One of the sodas contains holy water.

**Comment by FudgePucker** [comment]
Requires money and luck. Although I guess its fine for the vender to have holy water then.

Adding new clothing will be easier as well

**Comment by DeityLink** [comment]
I'm against it. Acquiring holy water shouldn't be so easy.

**Comment by SkowronX** [comment]
Hold that thought. I'll be right back.

**Comment by Arthurdentist** [comment]
this isn't a particularly easy way of acquiring it given that you require coins, something nobody ever mass produces. As an aside holy water does spawn in the office anyway, its just not something you can get more of without the chaplain about. 

Also cult rounds without a chaplain are a pain in the arse and lead to indiscriminate killing and permabrigging, maybe the addition of a somewhat convoluted way of acquiring more holy water would prevent that a tad.

**Comment by DeityLink** [comment]
Cult rounds where holy water is easily accessible also lead to cultists getting randomly slipped and forcefed/injected with it. I've seen it happen.

**Comment by FudgePucker** [comment]
This just means that cargo and maybe mechanics are a bigger threat to cult and should be a potental target rather than focusing on medbay or science.

Cargo has to be working with no fuck ups to make it. They need boards, order the shipments, and the miner has to make coins. Convert a single cargo tech and they can help fuck up that procedure.

Just admin help it if you see someone making 10 of these things round start with no sign of it being vampire or cult.

**Comment by Arthurdentist** [comment]
good thing this holy water isn't easily accessible then.

**Comment by SkowronX** [comment]
Apply bible to water tank. Instant 1000u of holy water. Wow.

**Comment by SkowronX** [comment]
☧

**Comment by Probe1** [comment]
Those sprites are great @SkowronX

**Comment by Arthurdentist** [comment]
I hadn't actually finished this

**Comment by FudgePucker** [comment]
If it hasn't been added to the map yet you can probably just make a new PR with fixes.

**Pull request merged**
