### PR TITLE
Removes the ancient, useless "bay overdoses"

### PR DESCRIPTION
**Pull request by help-maint**
### What are Bay ODs?
A long time ago, before we had code for proper overdoses, baycode had 4 "side effects" that worked as pseudo-ODs. 
I find that they are so useless that most people don't even know they exist.

They have a lot of problems:
- Their effects are just spamming you with emote text, over and over, and nothing else. If you've ever spent most of a round seeing "You feel an excruciating pain in your head!" even though there was nothing wrong with you, that's the Tricord OD.
Some of these are supposed to have an actually tangible effect, but it's ridiculously small, like dealing a total 1 brute damage that instantly heals itself.
- They are not revealed by any scan, and their causes/cures are not written down anywhere in-game. The only reason you'd know they exist is from one tiny excerpt very well hidden in an old wiki page. The most common OD also doesn't even have a cure message so you would have no idea that the cure worked.
- Their overdose limits are very very low. So low, in fact, that the pills that spawn in the roundstart first-aid kits cause you to overdose.
- The overdose duration is very very long. Minimum 20 minutes of emotespam, usually more because their duration is also bugged.
- They are very bugged. After you OD it may take up to 10 minutes for anything to start happening, and the OD strength goes up and down over time for no reason.

To reiterate: If you ever had 15u tricord inside you for even just a moment, you will get blared with "You feel an excruciating pain in your head!" for close to an hour. Doctors will say there's nothing wrong with you because every medical tool says you're at 100% health. The pain doesn't actually do anything, it's just big red text spamming your chatbox. ...Fun?

### Why do I want them removed?
They don't do anything. They just spam you with emotes for no seeming reason, and most people don't know what's going on because they are poorly implemented and unintuitive.
We now have a better OD system that has already been used to give ODs that *actually do something* to the offending chemicals, so this ancient system is redundant anyways.

:cl:
 * rscdel: Removed the ancient Bay overdoses, which really didn't do anything except spam emotes

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
Oh that's what did that? Good riddance

**Comment by Exxion** [comment]
Delete the file, don't just untick it.

**Comment by Armadingus** [comment]
I'd be sad to see this be removed. They might be wonky, but they are conditions that require both doctor and patient to communicate with each other to treat. It's not obvious that something is wrong, but the patient feels wrong, so the doctor has to ask how they exactly feel.
For me, this would be one less thing to have a patient slow down and roleplay with me about as a doctor.

**Comment by Eneocho** [comment]
> 
> 
>It's not obvious that something is wrong, but the patient feels wrong, so the doctor has to ask how they exactly feel.
> For me, this would be one less thing to have a patient slow down and roleplay with me about as a doctor.

While that makes sense in theory, the wild ride waits for no-one, so most doctors just speedrun the patients and don't really RP unless the round is unusually calm or lowpop.

**Comment by Armadingus** [comment]
> While that would work in theory, the wild ride waits for no-one, so most doctors just speedrun the patients and don't really RP unless the round is unusually calm or lowpop.
>
The effects are so minor, they can range from small red texts to bold red text that give you 1% brain damage. If there are bodies piling in, something that minor should not be your 1st priority.
They are for nice interactions during calm periods where you are usually bored out of your mind.

**Comment by Eneocho** [comment]
Instead of outright removing them, I would reuse them on symptoms for various ailments.
Toxin damage? You get cramps.
Burn damage? Your burnt area gets itchy.
Oxygen Damage? You get a headache (something something hypoxia).
Full of DanSauce? Stomachache.

**Comment by Eneocho** [comment]
> 
> 
> They are for nice interactions during calm periods where you are usually bored out of your mind.

I can't remember the last time medical was on a calm period. Besides, most doctor players (I've seen) lately are really of a "take this pill and GET OUT" attitude, so it still wouldn't really apply.

**Comment by TGFH** [comment]
So THAT'S what causes those headache messages. That always annoyed me and I just assumed it was some random event thing like random organ damage.

**Comment by ShiftyRail** [comment]
I would've liked them to be re-implemented as proper non-flavor text spam, but here we are.

**Pull request merged**
