### PR TITLE
Sanitised security essential box item holding

### PR DESCRIPTION
**Pull request by ghost**
[bugfix]
:cl:
 * bugfix: Medium-class weight items or items stored above the standard box storage limit taken out of security essentials boxes can now be fit back in again, and the box only allows items of types that it contained in the first place.
 * tweak: Security essentials boxes no longer fit in normal backpacks.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
This would probably turn a loadout-type box into something you can use for powergaming by treating it as a box that can hold a shit ton of security items.

**Comment by ghost** [comment]
> This would probably turn a loadout-type box into something you can use for powergaming by treating it as a box that can hold a shit ton of security items.

It only holds items of types that it originally contained, and to the exact w_class combination of them all.

**Comment by Eneocho** [comment]
I'd turn the sec essentials box into a one-use box, kinda like the autodrobe ones.

**Comment by BomberBro** [comment]
this wouldn't affect anything because people don't take everything out normally, and they doubly wouldn't if the box would die if they did. the box powergaming theorycrafting can come after there's evidence for it, there are already ways to hold multiple tasers in an object that fits in a backpack but I've never seen it powergamed.

**Pull request merged**
