### PR TITLE
Fixes several medhud oversights, removes redundant medhud code

### PR DESCRIPTION
**Pull request by gbasood**
This is what happens when you name your virus holders `viruses` and `virus2` and then also make them do two entirely different things

Removed lots of dead code for this one.

🆑 
 - bugfix: Fixes human medHUDs not being able to detect newstyle viruses (disease2) that pAIs used to be able to detect, seems to have been an oversight
 - bugfix: Fixes observers with the medHUD enabled being able to see if a person has old-style diseases (disease) instead of just new-style. I had no idea this even existed.

### CODE REVIEW

**Comment by SonixApache** [comment]
Isn't appendecitis still an old-style virus?
And wizarditis, and robot / mommi transformations, and...

**Comment by gbasood** [comment]
Yeah  there's a few old style viruses
That's why I haven't removed them

Sorry, let me be more specific:
Before, old-style viruses were the only ones detected.
NOW, it's old-style viruses and new ones, based on criteria previously used either in the central medhud proc that's used currently, or the pAI medhud proc that was still in code but not removed for some reason

**Comment by Durgen** [comment]
https://github.com/vgstation-coders/vgstation13/issues/14691

**Comment by gbasood** [comment]
Doesn't fix that at the moment

**Pull request merged**
