### PR TITLE
fix plasma mod oversight, overhaul to rigsuit mod functions

### PR DESCRIPTION
**Pull request by CrazyAmphibian**
[bugfix]

## What this does
FROG MAN DID CODE (see:  #33648)

## Why it's good
Fixes an oversight with the plasma seal mod which overwrites suits which are already plasma sealed
extends the functionality of rigsuit mod checks

## Changelog
:cl:
 * bugfix: Fixed the plasma suit mod being able to be applied to suits that are already sealed
 * rscadd: rigsuit mods can now use custom install conditions

### CODE REVIEW

**Comment by Hinaichigo** [comment]
I think you can leave the second changelog entry out as it's a backend thing.

**Comment by CrazyAmphibian** [comment]
> I think you can leave the second changelog entry out as it's a backend thing.

ah is the changelog what shows up verbatim on screen when you join the game?

i feel like it could still be good to let people know that there's a new back end feature, in case anybody wants to use it for something, as not everyone regularly checks the github to see what's going on code-wise

but i'll change up the wording to be a bit more approachable in the meantime to get some more opinions on it.

**Comment by Kurfursten** [comment]
He's right that coder stuff doesn't need to go in the CL, but I am proud of you for finally doing it

**Comment by CrazyAmphibian** [comment]
it would be pretty funny if it didn't get merged for another year

**Comment by CrazyAmphibian** [comment]
well, thus ends the bit.
was fun while it lasted.

**Pull request merged**
