### PR TITLE
Kick fixes

### LINKED ISSUE #8539: Infinite glass shards from kicking sunglasses over and over
http://i.imgur.com/qE296ej.png

### PR DESCRIPTION
**Pull request by unid15**
- Windows can't be kicked down anymore unless you have talons, heavy shoes or a lot of strength
- Fixes horrible sunglasses bug Fixes #8539

### CODE REVIEW

**Comment by ghost** [comment]
Why the removal of stomping sunglasses?

**Comment by 9600bauds** [comment]
http://i.imgur.com/qE296ej.png

**Comment by ghost** [comment]
Yeah, but in a previous commit he added the qdel that would've sorted it, now he's removed the feature entirely

**Comment by unid15** [comment]
It'd still be a bit buggy and produce two messages (X kicks the sunglasses, X stomps the sunglasses) and I don't feel like fixing that right now
will readd later

**Comment by ghost** [comment]
Fair enough

**Pull request merged**
