### PR TITLE
Smartfridges can now be wrenched and moved, fix walls under fridges

### PR DESCRIPTION
**Pull request by ghost**
Yes, I modified every single map, wasn't fun, but otherwise it would have been gay to unwrench and move a SmartFridge and not being able to put it back because wall lmao

:cl:
 * rscadd: Smartfridges can now be wrenched and unwrenched and moved. Removed walls under all SmartFridges on every full rotation map.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Nice

**Comment by robosperg** [comment]
Add firelocks

**Comment by ghost** [comment]
Airflow needs to be fixed, please send help @Exxion

**Comment by ShiftyRail** [comment]
I think I managed to do "something" that worked with big fish tanks

Makz `Crossed()` return `anchored`

**Comment by Exxion** [comment]
`Crossed()` has nothing to do with anything
Just replace `air_group` with `!istype(mover)`

**Comment by ghost** [comment]
Yo @Exxion it works perfectly now, thanks fam

Should be good to go too, dunno why map diff render keeps being gay

**Comment by ghost** [comment]
Aight, so, how are we on changes to make here ?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I wouldn't mind a longer unanchoring time since basically the only use this will get is grief and rarely B&E but if that's not easily doable then whatever

**Comment by ShiftyRail** [comment]
He forgot FIXED2WORK reeeeeee

**Pull request merged**
