### PR TITLE
Minor Autocloner update

### PR DESCRIPTION
**Pull request by TheEliminator16**
-tweak: Made autocloner spawn things faster in general
-tweak: Added skrite and necromorph as possibilities for autocloner
-Made autocloner animated like it always should have been

### CODE REVIEW

**Comment by AutismSpider** [comment]
How much faster?

**Comment by TheEliminator16** [comment]
On creation, the pod randomly picks how many ticks it needs to create a new creature.
Before this change, it was 60 to 360 ticks, which is slow as fuck
I changed it to be 45 to 180 ticks, still slow as fuck for balance purposes, but not "spawn one creature every 20 minutes" slow

**Comment by AutismSpider** [comment]
well slow tick may be call for with the shit that can pop out of it it can make spiders/spiderlings

all it takes is like three/four spider lings start a massive shit storm one or two of them will turn into queens etc

**Comment by TheEliminator16** [comment]
It can't spawn spiderlings, only nurse spiders, which are weak as fuck
You'd need to be severely incompetent to allow a nurse spider start shit

**Comment by AutismSpider** [comment]
You forget were you are we had med-bay staff have hard time with putting god damn gas mask on vox/plasma men

**Comment by TheEliminator16** [comment]
Incompetence deserves punishment

**Comment by 9600bauds** [comment]
Sounds like you're speaking out of one bad, isolated experience. Either that or you observed a round in the last couple of days where Plasmamen were fucked up.

**Comment by TheEliminator16** [comment]
merge when

**Pull request merged**
