### PR TITLE
sleeping people no longer considered dying on admin roundstart logout report

### PR DESCRIPTION
**Pull request by nervere**
[administration]

### CODE REVIEW

**Comment by Kharkov72** [comment]
i never noticed lmao

**Comment by bathosbathtime** [comment]
The logout report is not medically trained please do not shame it.

**Comment by nervere** [comment]
I'd like to think some centcom intern just looks on the cameras and gives a report based on what he visually sees.
Sleeping crewmember? Nah, more likely they just dropped dead or something.

**Comment by Theophrastus1** [comment]
image

**Pull request merged**
