### PR TITLE
Disabling the ID wire on a door will now allow the door to be accessed by anyone

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Thanks to @Kammerjunk and @MadmanMartian for literally doing this PR
Give the PR the OH GOD IT'S LOOSE tag
[gameplay] [tweak] [vote]
could possibly be a bug fix who knows

:cl:
 * tweak: Pulsing the ID scanner wire on an airlock allows anyone for 10 seconds to access it.
 * tweak: Cutting the ID scanner wire on an airlock has the same function; Not allowing anyone to use it.
 * rcadd: Added new messages when tampering with wires and when examining from a distance that show whether the ID scanner has been pulsed or cut.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
why not, in allowed(user), check if requiresID()?

**Comment by boy2mantwicethefam** [comment]
RequiresID is not what determines the user's access for the airlock, it is a value solely interacting with ID scanner and AI ID scanner.
RequiresID returns 1 if the ID scanner wire is not cut or the AI didn't disable the ID scanner, but if it is cut it returns 0, and if it's 0 it acts as if the user's access is null (no access to use the airlock)
@Kammerjunk made this solution instead, which in my opinion achieves the proper effect for the purpose of the PR

**Comment by MadmanMartian** [comment]
fair enough

**Comment by jknpj** [comment]
This makes silicons able to use doors with the ID wire cut, doesn't it?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is essentially sabotage and it's very hard to spot if done to your office. You'd have to take your ID off and facecheck your airlock regularly with zero indication to make you suspicious.

Door hacking is already pretty damn powerful with only marginal difficulty and I don't see the need to make it even easier. If you want to make it slightly less "destructive", make it so that you can hand-close airlocks that have their screwdriver panel open, because a lot of people don't realize that's how it works and their airlock needs only a screwdriver to be fully repaired

**Comment by boy2mantwicethefam** [comment]
@jknpj Haven't considered that, but how many people have done it as of lately anyway
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE I'm gonna add an examine then (no fun allowed)

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Same dealio, you'd have to examine your airlock a lot with no visual cue
A visible light turning on, like with disposals bins, would be better
And that's just usability, not even going into balance concerns. Why does door hacking need to be made even easier and more annoying to fix?

**Comment by boy2mantwicethefam** [comment]
How is it more annoying to fix?

**Comment by boy2mantwicethefam** [comment]
What?
Also now I'm planning on adding a multi-tool function for the ID scanner beside wirecutters

**Comment by Goldsteel** [comment]
My current opinion on this is that hacking doors is already easy enough.

I don't really like the idea of being able to remove access on doors very easily. You can already cut power to a room and crowbar the door open using an APC hack. If you want to deconstruct a door with an RCD and replace it with one with no access, you can do that. You can do it manually, too. There are so many options to getting around doors that this change renders them obsolete.

**Comment by boy2mantwicethefam** [comment]
I was thinking the change would be divisive, which is why I'm asking for a server poll

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Seems oddly deflective fam

**Comment by boy2mantwicethefam** [comment]
?

**Comment by KingofHONK** [comment]
would upboat if door bolt light showed yellow or something, as this would be neat for emergency situations where EVA should have its access revoked or if theres blob and armory doors could be opened without having to bolt em for crew

**Comment by ghost** [comment]
You know, I've always wanted this, but then I think about it and realize if it's just one wire you have to cut to bump open any door it's insanely broken.
A thing you can do already: Cut the wire in question and then pulse the open door wire (we have that right? I'm not just stuck in /tg/ still, I'm sure I did that gimmick on /vg/ multiple times). However in doing that you turn the door into a brick, unless you do your fancy-smancy way. And it kinda sucks, so now everyone knows that the door is broke because they can't open it suddenly. 
Maybe not ONE wire should be allowed to remove access, but a few different wires working together causes it to happen?
And as a thing, so you can check it's happened easily, make the airlock lights colour turn yellow or something.

**Comment by ShiftyRail** [comment]
I think that this should require more efforts to pull off. Rather than simply sniping a wire, make it a more fleshed out feature.
You could make it requires to bolt the airlock down, cut off AI wire (to represent the fact that it needs to be safely closed before changing access procedure, maybe) and then use a signaler sending frequencies equal to the desired access, and write down a dictionary of frequencies/access equivalencies somewhere

**Comment by boy2mantwicethefam** [comment]
here are the planned changes:
- Add a multi-tool interaction that temporarily removes access restrictions, y/n if people want wirecutter interaction to brick the airlock like current IDscan and like Razz's suggestion
- Lights show up when access is removed or airlock is bricked
- A separate atomic PR that allows closing screwdrivered airlocks as per suggestion

**Comment by jknpj** [comment]
Did you check the cyborg thing? Because this would remove a really good silicon counter.

**Comment by bathosbathtime** [comment]
I would love to have some ability to strip access from an airlock through hacking, but having it be snipping a wire seems far too easy.

**Comment by Ephx1** [comment]
I would much rather prefer if it required you to pull out the door board and fuck with access.

**Comment by bathosbathtime** [comment]
That feels closer to just doing engineering work than hacking to me

**Comment by SonixApache** [comment]
You can already close screwdrivered airlocks, just need to use anything that isn't your hand, your ID, or a screwdriver.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Fantastic, good to know
Makes requiring a wirecutter to fix your door even worse by comparison

**Comment by boy2mantwicethefam** [comment]
Changelog:
- Access revoking is now a multi-tool function; It disables the access requirement for about 10 seconds.
- Cutting the ID scan wire now has the current normal function AKA it bricks the airlock. (AI cannot toggle the access)
- Examining it now shows the current state of the airlock, whether it's hacked (ID card flashes yellow) or cut (ID card is off). Preferably I'd also get sprites to show it off, but I'm also anxious because the last time I made sprites another PR got merged and there were conflicts that I don't know how I fixed

**Comment by SonixApache** [comment]
good changes

**Comment by SonixApache** [comment]
@boy2mantwicethefam you should axe the mins for a vote

**Comment by MadmanMartian** [comment]
Admins were asked to make a vote, none responded. It's dead.

**Comment by SonixApache** [comment]
why didn't you just bug the mins to make a darn vote?

**Pull request closed without merging**
