### PR TITLE
Adds a new 'ninja' hardsuit

### PR DESCRIPTION
**Pull request by jknpj**
**This just adds the suit to the game, but does not makes it available**. Ninjas still need a few tweaks before they can enjoy using it. Statwise, it's just the ninja softsuit, but hardsuit, here's how it looks when worn by them:

This sundowner suit was made ages ago by @Blithering but the antagonist/bundle that it was supposed to be made into kinda never happened. If you want a cool project to work on, there's still a bunch of sundowner-related icons that still need to be coded, including his infamous shield rigging.

### CODE REVIEW

**Comment by SageOfLight** [comment]
RED SUN.

RED SUN OVER PARADISE.

**Comment by DeityLink** [comment]
Kinda wish we took the Warframe direction instead since it's closer to SS13's identity.

**Comment by Viciousaurus** [comment]
> Kinda wish we took the Warframe direction instead since it's closer to SS13's identity.

Give me 10 thumbs up and I'll sprite Excalibur

**Comment by SonixApache** [comment]
pretty sure we already have excalibur sprites laying around

cool hardsuit, ever stepping closer to adding the actual space ninja rather than sending in apprentices

**Comment by Blithering** [comment]
excalibarp
Thumbs are not needed.
lesspointy
Coders are though...

**Comment by jknpj** [comment]
I only didn't add the excalibur because it lacked separation/item sprites. Guess i didn't ask for them, though!

**Comment by Blithering** [comment]
Pretty sure those should be in the dmi, I'll double check.

**Comment by Kurfursten** [comment]
Guessing you plan to work on the hardsuit stuff in a separate PR, it's fine to add this for now though

**Pull request merged**
