### PR TITLE
Revert "beepsky now ignores invisible perps"

### PR DESCRIPTION
**Pull request by ShiftyRail**
Regardless of democracy being a mistake or not, you don't merge a PR that important or with that much controversy in four hours.

### CODE REVIEW

**Comment by aceedex** [comment]
The power of the bugfix tag is absolute. Ye olde collaborators of olde have set that precedent.

**Comment by boy2mantwicethefam** [comment]
Implying these people should have rights to democracy
That's right, it's time to dab on Beepsky defenders once more
"N-NO DONT FIX IT!!"
>Why?

"REEEEEEEEEEE"

>Merging it

"Y-YOU SHOULD HAVE WAITED FOR ARGUMENTS!!!"
And the responses to this comment will be tribal at best

**Comment by ShiftyRail** [comment]
From the man that brought you "t. sec main"

**Comment by boy2mantwicethefam** [comment]
t. sec main

**Comment by Kammerjunk** [comment]
imagine literally being Goof

**Comment by iFlashYou** [comment]
>AI cant see invisible people
>Borgs cant see invisible people
>People cant see invisible people

But some SECURITY bots should be able to see and arrest them?

**Comment by MadmanMartian** [comment]
This change doesn't even work anyway, as things like the cape of invisiblity change your invisibility level, not your alpha.

**Comment by MadmanMartian** [comment]
Seems I was mistaken, my apologies.

**Comment by ShiftyRail** [comment]
1000000% reviewed

@iFlashYou A player VS a non-player.

**Comment by boy2mantwicethefam** [comment]
Don't expect anything worthwhile to come out of Security players because they are almost never on the receiving end to care

**Comment by Intigracy** [comment]
I don't care about the change one way or another but please stop merging things that make people angry so quickly

This doesn't even address beepsky going after people with a high `invisibility` count

**Pull request merged**
