### PR TITLE
Fixes the incorrect ! statement for generating large artifacts, and a…

### PR DESCRIPTION
**Pull request by Cisrox**
Fixes the bug referenced by PJB in #23263, also changes the sites back to how they were pre #20762, with plant and animal sites returning to being the ones that don't generate larges. All other sites do, and here is my evidence as to why I changed this back; 

evidence 2

evidence one

:cl:
 * rscadd: Large artifacts now generate in house sites again, as intended. 
 * rscdel: Made large artifacts no longer generate in animal sites.

### CODE REVIEW

**Comment by Cisrox** [comment]
not sure why my push is by cisroxandkoilz, oh well

**Comment by ghost** [comment]
fucking finally

**Comment by Lunanite** [comment]
please do so my flavor text about being a xenoarch isn't incorrect

**Comment by Cisrox** [comment]
Just tested it, large artifacts don't spawn in any trace organic sites (Plant and animal), and also the number of them is normal. This is from an SDQL query on deff,
evidence PART 2

**Comment by Cisrox** [comment]
@Exxion merge this pls

**Pull request merged**
