### PR TITLE
makes charging apcs yellow

### PR DESCRIPTION
**Pull request by SirSkeleto**
not only is yellow the color in between green (charged) and red (uncharged), but this will remove confusion concerning what a blue apc means.

:cl:
 * tweak: charging apcs are yellow now

### CODE REVIEW

**Comment by Kurfursten** [comment]
It's too bright yellow for me I think

**Comment by ShiftyRail** [comment]
There was no real need for it imo

**Comment by bathosbathtime** [comment]
While I highly doubt it causes confusion, the red, yellow, green combination does make me feel good.

**Comment by press-mark** [comment]
as said earlier, I think the yellow is a bit too bright and jarring, could it be made a bit more pale?

**Comment by boy2mantwicethefam** [comment]
Remove the : before the tweak and you're golden

**Comment by SonixApache** [comment]
milf nerf

**Comment by Goldsteel** [comment]
I like it personally, but I think it should be a slightly darker yellow in my personal opinion. As a sidenote I think rechargers should charge as yellow and flash green when finished instead of the other way around.

**Comment by SNilWillIllShill** [comment]
Having the charging yellow APC be darker a la Engineering colors might not be so bad.
@Goldsteel >I think rechargers should charge as yellow and flash green when finished instead of the other way around.
Nope. The point is that yellow flashing makes them stand out to a cursory view of the screen and stuff on it. Green flashing might blend in a bit too much with the usual background colors, in my opinion.

**Comment by SirSkeleto** [comment]
i will make the yellow a darker yellow

**Comment by Intigracy** [comment]
neat

**Pull request merged**
