### PR TITLE
Vox and trader only co-operative cell item: Vox shoal raid pacts

### PR DESCRIPTION
**Pull request by ghost**
[content]

## What this does
Adds a vox and trader exclusive co-operative cell item to traitor uplinks, costing 60 TC but discounted to 40 TC for traders, activating it as a vox that can speak vox pidgin sets up a vox raider faction modified to use the trade outpost as a base, with the reward being points converted into shoal funds and some raider items being unlocked at trade windows. Also adds the charter as a very rare xenoarchaeology artifact, like the other antag items with the same chance.

## Why it's good
Adds more vox and trader specific items, and is thematic with them while opening up the trade window to some antag-exclusive items.

## Changelog
:cl:
 * rscadd: Trader and vox syndicate members can now purchase a charter declaring a shoal creed for a vox raid, the completion of which promises many coin for shoal funds at trader windows, and some new gifts.

### CODE REVIEW

**Comment by Kurfursten** [comment]
What do you actually get out of buying this? It seems that this gives you access to neither the raid shuttle, by extension no raider, gear, nor additional backup. Something I'm missing?

**Comment by juanototo2** [comment]
Remove it from xenoarch (waste, not all xenoarchs are birds) and I'm all for this.
Though make sure it also adds some advantage, such as for instance unlocking vox raider equipment on the trader vending machine.

**Comment by gurfan** [comment]
I don't really understand the point of this. It seems like it just gives turns you into a vox raider and gives you vox raider-like objectives. Raiders is a really janky and broken mode so copying it without any changes seems questionable. 
I don't really see the point of this either. You're spending 40 TC for... objectives? If this thing summoned a raiding crew to raid along side you or gave you some kind of raiding ship it would be a lot more worth it, but I don't really see the point.
Also being able to find this through xenoarcheology seems silly especially considering that only vox can use it. At least the other antag-making items barring the syndicate beacon have some reason to be buried in an ancient asteroid but I don't see why a contract from the shoal should be there.

**Comment by ghost** [comment]
> What do you actually get out of buying this? It seems that this gives you access to neither the raid shuttle, by extension no raider, gear, nor additional backup. Something I'm missing?

Added the reward of points being converted into shoal funds and raiding gear being made available at the trade window.

**Comment by NiftyRyanyan** [comment]
Who’s actually going to buy this, this is can only be used by vox and will require second traitor to you all their tc. Worst off most of the vox raider equipment can already be obtained without buying this so you are just paying 40 tc for a objective and a few goodies.

**Comment by Kurfursten** [comment]
> > What do you actually get out of buying this? It seems that this gives you access to neither the raid shuttle, by extension no raider, gear, nor additional backup. Something I'm missing?
> 
> Added the reward of points being converted into shoal funds and raiding gear being made available at the trade window.

Getting raiding gear is maybe cool but worth 40TC? Seems more like it should just be a one-time bundle that can roll based on your race.

Getting points turned into shoal funds doesn't seem much like a reward because the main point of shoal funds is to help you buy more things to trade. Who is going to want to buy from a publicly known raider?

**Comment by Eneocho** [comment]
If it were a vox-only syndicate bundle it'd be ok but as it is currently it just seems extremely wasteful and underpowered for the cost.

**Comment by xeroxemnas** [comment]
Raiders are still too fucking janky at the moment. Really needs to be ironed out first.

**Comment by WindowsErrors** [comment]
this is definitely a pull request submitted by kane-f

**Comment by Blithering** [comment]
Maybe a couple of grab bags of raider-like gear and an implant that marks you as friendly to raiders would make it more incentivised? Does this actively spawn a raider cell to visit the station or are the vox just awakening their inner magpies?

**Comment by Eneocho** [comment]
Buying the pact could send you a beacon that spawns a raidergear vendor. You can be unscrupulous and sell said gear to the same people you want to raid or use it to raid as intended.

**Comment by ghost** [comment]
Could not get to work, seems like vox raiders could use changes first.

**Pull request closed without merging**
