### PR TITLE
[Tweak, More of a Bugfix at that point] Making the Doors on the Mining Bridge accessible to players with Research Access

### PR DESCRIPTION
**Pull request by DeityLink**
raaaaaaaah

Using my newfound text-editor map-editing skills for the greater good. Let's be honest here, that one is looooong overdue.

### CODE REVIEW

**Comment by clusterfack** [comment]
I like this :+1:

**Comment by dylanstrategie** [comment]
I remember working on those doors, don't remember what's wrong with them. Maybe I accidentally gave it the wrong access requirement

**Comment by ComicIronic** [comment]
Did you check this on all maps?

**Comment by PJB3005** [comment]
Why is that bridge even there anyways? A catwalk is more than enough

**Comment by DeityLink** [comment]
@dylanstrategie they are only accessible to miners.
@PJB3005 I think it fits the style of the research outpost which is overly furnished for its purposes.
@ComicIronic Hm, Is there an exact same bridge on the other maps? I thought each map had a different asteroid.

**Comment by FudgePucker** [comment]
Does this even need anything besides all access? How the hell is someone with out access even going to get there? How are they not dead? Why can't they walk across it?

**Comment by DeityLink** [comment]
It was previously miner-only. Now scientists can use it. Xenoarchaeologists everywhere cheer in unison.

**Comment by FudgePucker** [comment]
What if someone goes on a space adventure and lands on the asteroid? Shouldn't they be able to use the pointless bridge instead of going around?

**Pull request merged**
