### PR TITLE
fixes baseball cap grammar

### LINKED ISSUE #15199: sec cap grammar
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
>Revision

91adeed8a916b660dbf081340607d6e91fa0131f 

>General description of the issue

thats not how grammar works

>What you expected to happen

That's a security cap. It is a normal-sized item.

It's a baseball hat in a tasteful red colour.

>What actually happened

That's a security cap. It is a normal-sized item.

It's baseball hat in tasteful red colour.
>Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by SonixApache**
unfucks cap grammar
resolves #15199

### CODE REVIEW

**Comment by Riekland** [comment]
I'd like to ask for this to be re-opened because I just now realise that not only did sonix Americanise the beautiful queen's but he also didn't fucking fix sec caps

```
 /obj/item/clothing/head/soft/sec
 	name = "security cap"
-	desc = "It's baseball hat in tasteful red colour."
+	desc = "It's baseball hat in a tasteful red color."
```

can you spot the fucking problem

**Comment by d3athrow** [comment]
Can't reopen a PR you'll have to make another @Riekland

**Comment by Riekland** [comment]
mudak

**Comment by d3athrow** [comment]
Mudak?

**Comment by Riekland** [comment]
It's a russian swear
I think it's just generic anger but I'm no slav

**Comment by SonixApache** [comment]
pfffff

**Pull request merged**
