### PR TITLE
New sprite for the Gallon of PCP

### PR DESCRIPTION
**Pull request by ManopolisJones**
## What this does
Changes the Gallon of PCP's sprite from the basic bleach bottle, to something more closely resembling the reference it's based off of.

liquid pcp 2

PCP slightly disconcerned

## Elaboration
At first I did an edit of the bleach bottle to have the same sort of color and PCP written in big black lettering, but then after making a half decent edit out of the liquid butter bottle, decided to go with that instead.

:cl:
 * rscadd: Adds new sprite for the gallon of pcp

### CODE REVIEW

**Comment by Theophrastus1** [comment]
i have one suggestion, invert the 4 pixels above the first P so that it looks like a frowny face instead of a smiley face

**Comment by ManopolisJones** [comment]
> i have one suggestion, invert the 4 pixels above the first P so that it looks like a frowny face instead of a smiley face

That was supposed to be like an indentation in the jug, but now I can't fucking unsee that as a little face on the bottle

**Comment by ManopolisJones** [comment]
QUICK, WHAT'S BETTER, THE O DENT OR THE SMILEY DENT?

OHNO

**Comment by NigglyWiggly** [comment]
Without the top two pixels it looks like the bottle is mildly concerned with your actions and I feel like that's reasonable

**Pull request merged**
