### PR TITLE
Santa Claus Kit for Wizards

### LINKED ISSUE #7272: Half of the stuff in #7260 didn't actually merge
thanks git #7260
@Skullyton
@clusterfack

### PR DESCRIPTION
**Pull request by ghost**
On christmas day only 
- summon gingerbread man
- makes the world snow
- summon snowmobile
- giftbag of infinite goodies that can't be removed
- santa suit that can't be removed
- no clothes

also fixes #7272 - as gingerbreadmen weren't checked in the default .dme

### CODE REVIEW

**Comment by 9600bauds** [comment]
ty eggman of coding

**Comment by ghost** [comment]
based eggman of coding

**Comment by ihadtoregisterforthis** [comment]
ty eggman of christmas

**Comment by FudgePucker** [comment]
How many Santa's got valid'd on chrismas

**Pull request merged**
