### PR TITLE
Plated Catwalks

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Adds Plated Catwalks. These can with metal sheets and installed like any other floor tile. Add two rods to the frame to build the wire hatch then use a screwdriver on the catwalk to remove or reinstall the hatch for easier access to cables or pipes beneath them. Big thanks to @DeityLink for providing me with good looking sprites!

## Why it's good

image
They look cool!

## How it was tested

Test cases:
- Installing and removing the tile successfully.
- Tiles do not install when applied to a turf that already has a tile.
- Toggling the grate.
   
## Changelog

:cl:
 * rscadd: Added Plated Catwalks which provide visibility and easy access to cables and pipes.

### CODE REVIEW

**Comment by CrazyAmphibian** [comment]
something about the look of them is... off?
it's hard to pinpoint exactly what it is.

**Comment by west3436** [comment]
> something about the look of them is... off? it's hard to pinpoint exactly what it is.

I am very much not a spriter - if you have better sprite ideas please send em over and I'll update!

**Comment by CrazyAmphibian** [comment]
i think it blends into the plating a bit too much, might need some more contrast.

**Comment by Eneocho** [comment]
Make it so you can shock these catwalk grilles, please.

**Comment by SECBATON-GRIFFON** [comment]
i don't get why you can't just make it so normal catwalks can be installed over plating too
maybe we could have both in some form

**Comment by RealestEstate** [comment]
I think these look very nice

**Pull request merged**
