### PR TITLE
Removes metaclub's eyepatch thermals that spawned in detective's office

### LINKED ISSUE #14198: Metaclub's detectives start with thermals
Other maps that are not box starting with cool stuff does not mean they should start with broken and completely OP stuff.

Detective's office (I guess?) starts with thermals. I just played a round as a mechanic where I was asked to masscopy them and give them to all officers.
And it was not the first time this happened. I didn't understand before how they got them, but now I do.

They are supposed to be an antag item, they are extremely good and expensive. Meanwhile, the detectives get it for FREE. Even though it spawns at their office, the HOS and many officers will rush to get (and probably masscopy) them.

I don't think they should have this. It's too much. It's too good.

### PR DESCRIPTION
**Pull request by eplgr**
Closes #14198, #7636

# Reasons
Read #14198, the `tl;dr` version is that thermals are too strong to be obtained at roundstard for free, and it's extremely easy to abuse it.

# In-game changelog
:cl:
 * rscdel: Metaclub: removed eyepatch thermals that spawned in detective's office

### CODE REVIEW

**Comment by ghost** [comment]
Yes.

**Comment by eplgr** [comment]
Top honk, I caused conflicts with #14337 .
Gonna fix it tomorrow.

**Comment by Kurfursten** [comment]
I enjoy it when a map has some things to make it different, but I admit it felt outright wrong when I played last on Meta and there were thermal eyepatches laying all around the halls because the mechanics printed 50 of them and everyone had one.

Trying to play an antagonist that shift would've been impossible so no surprise it turned into extended.

**Comment by Shadowmech88** [comment]
>there were thermal eyepatches laying all around the halls because the mechanics printed 50 of them and everyone had one

That problem specifically could be fixed by giving the detective's thermal eyepatch `mech_flags = MECH_SCAN_ILLEGAL`.

**Comment by salamandooo** [comment]
I love the thermal eyepatch though

**Comment by aceedex** [comment]
nah, unique things being in maps is fine. and there's nothing wrong with the mechanics making them. I liked that deff was played for it's brig until everything worth a damn in there got moved to box anyway. If you REALLY want to limit it, give the eyepatch  material costs but there's no reason to remove something nice because someone got fucked out of their antag roll

**Comment by PJB3005** [comment]
The ability to make more eye patches should be disabled as @Shadowmech88 said.

Though the uniqueness should definitely be kept. If you're worried about losing your antag round then just take out the detective.

**Comment by Blithering** [comment]
So long as it remains meta only, I don't think it warrants removal. Plus if it was removed we won't get the comedy of a detective walking into the brig and immediately having their eyeballs destroyed by thermal amplified stationary flashers.

**Comment by eplgr** [comment]
Giving security an antag item FOR FREE when antags have to pay 6-8TC for it is just awful and wrong.
Fun != giving thermals to the validhunter HoS/officer; detective is not a job that is played every round, odds are, someone else will take it.

That's why I don't think just disabling mechanics to scan them is enough.
Unique things added in other maps is fine, but this is broken and has nothing to do with that. Clearly you don't care about balance issues at all if your argument is "lol just kill the detective".

Stop giving the crew more easy tools to validhunt. This is not a pvp game. This literally serves no other purpose.

**Comment by TheFriggenSawbones** [comment]
please this is total bullshit.

Thermals were mostly removed for a reason, they were broken as shit. 

Without the cloaking device we really don't need them anywhere.

**Comment by SonixApache** [comment]
@Blithering is that even the case? I changed handheld flashes to actually affect people wearing thermals, but I dunno how the stationary ones work.

**Comment by SonixApache** [comment]
Can we merge this or close this so it doesn't hold the map PRs hostage

**Comment by RFultra** [comment]
I commented every emoji, can I get my metaclub token?

**Comment by yclatious** [comment]
I kind of have to agree with elpgr, it IS just a free antag item given to sec roundstart for no good reason but validhunting, it might be FUN for sec but are we sure that it actually allows FUN from the antagonists fucking shit up and are we sure it doesn't kill them making the situations of emergency we all love to try and survive through?

Extended is fine, and I never hated a round with no antags but sometimes too much extended can be boring for a spessman, if you roundstart discover a ling, roundstart discover the revs, roundstart discover every antag and then kill them all, where is the fun from the adversities they create, the antagonizing?

**Comment by PJB3005** [comment]
ALRIGHT.

I HAVE AN IDEA.

**Comment by eplgr** [comment]
Asking for blind votes when this requires a delicate balance discussion is not a good idea.

I know people who will literally vote against it just because they "like" the item, without having any deeper thoughts. How could such things be relevant and helpful?

I'm against this. I think I even prefer that you close this PR intead of doing a meme server vote. Obviously it'd be even better if you just merged it straight away.

**Comment by Lokiamis** [comment]
I'd personally be ashamed if I wasn't able to catch every antagonist on the station with thermals. Spawning your uplink items in a 1x1 bolted bathroom stall? Busted. Sucking the blood of somebody in a pitch black lair behind a hidden door? Busted. Thermals even work through cameras if I'm not mistaken.

**Comment by Exxion** [comment]
>Thermals even work through cameras if I'm not mistaken.

You know, knowing camera code, that's probably true.
It really, really shouldn't be. But it is. (Probably.)

**Comment by Yelier** [comment]
I don't know where to begin with this. First of all, the thermal goggle traitor item itself was made to help you find and kill people, and perhaps to avoid being caught doing sketchy things. It wasn't intended to catch other antags. Why would you even need to? You're a traitor yourself. 

However, it's really different on detective. Detective's job isn't to assassinate people, it's to find out who did a crime and to sic sec on them. Isn't it kind of silly that detective gets an item that completely renders their entire gimmick obsolete? You have no reason to scan crime scenes when you can just see people committing the crimes through walls.

Not to mention that mechanics can replicate them and hand them out to sec. HUDsunglasses are great, don't get me wrong, but thermals are MUCH better for their job in most situations.

**Comment by clusterfack** [comment]
Lets nerf thermals to show red blobs when people arent in your direct line of sight

**Comment by Lokiamis** [comment]
>First of all, the thermal goggle traitor item itself was made to help you find and kill people, and perhaps to avoid being caught doing sketchy things. It wasn't intended to catch other antags.

No, it was originally security equipment to find and kill antags using the cloaking device, another tool removed for having next to no counterplay.

**Comment by Bitod1** [comment]
>but thermals are MUCH better for their job in most situations.

That is assuming the detective is always within a screen wide radius of every crime, the thermals aren't perfect and the detective can't be everywhere at once. The detective's scanner still would be used for most crimes that the detective has to solve after they've happened like major thefts or murders.

**Comment by Yelier** [comment]
@Lokiamis I meant how it was currently implemented as a traitor item. My bad.

@Bitod That is true, but I'm talking from experience. When I play detective on Metaclub, all I usually need to do is lurk maint with the thermals on, and then I find the bad guys. It's harder on traitor than vamp and ling, but the fact that it makes two antag types just straight up trivial is kind of dumb.

**Comment by Blithering** [comment]
If this does get removed, I'd like to see something else take it's place to keep meta detective unique.

**Comment by Probe1** [comment]
It was floated in Discord that a syndicate camera bug pack would be an effective replacement.

As is, I'm not removing something that makes a map unique and we've managed to have for 2 years without it being a problem to the players.

I will consider swapping it to a different thing, like said camera bug, which would provide interesting gameplay for Security and motivate people to play Meta.

**Comment by SonixApache** [comment]
how about we just use the golden revolver icon we have laying around

or some other dumb cute little snowflake thing

instead of free syndicate items

**Comment by eplgr** [comment]
Yeah, I will see what we can replace it with.

Also it wasn't a problem for 2 years probably because it had the no-fruit effect. It was there since forever but no one really knew, until it went viral and it started being abused every single round.

**Comment by Intigracy** [comment]
Actually the camera bug is a really neat idea.

**Comment by N3X15** [comment]
Don't panic, reopening to try and fix merge status.

**Comment by Intigracy** [comment]
I can't re-open this and neither can N3X, the button is just gone.

Re-make this with a more reasonable approach with a replacement as opposed to just a removal.

**Comment by PJB3005** [comment]
I can't either.

**Comment by Exxion** [comment]
Greet

**Comment by N3X15** [comment]
firefox_2017-03-17_12-19-52
firefox_2017-03-17_12-34-15

**Comment by Blithering** [comment]
Idea for a replacement: disguise kit containing a pocket mirror, a false mustache and an ID with a ridiculous fake name like A. N. Other, Guy Incognito, Hugh Zasking, Ivan Gottasecret

**Comment by eplgr** [comment]
@Blithering I love the idea. And it's way more interesting than camera bugs.

**Comment by SonixApache** [comment]
@Blithering perfect

**Pull request closed without merging**
