### PR TITLE
Adds xenoarch digsite locators

### PR DESCRIPTION
**Pull request by MadmanMartian**
Basic version just shows hidden digsites that aren't showing on the rock

Advanced version shows the digsites as an overlay, with the colour of the overlay depending on the material associated with that find

currently uses the old forensic scanner sprites, so new sprites would be appreciated.

:cl:
 * rscadd: Adds xenoarch digsite locators. Similar in function to the mining scanners, they will reveal hidden or otherwise obscured digsites. The basic version just shows the digsites, the advanced version shows a coloured overlay whose colour is associated with the finds responsive material.

### CODE REVIEW

**Comment by DrSnips** [comment]
I always wanted something like this. I tried making one in the past and forgot about it when I put it to the side. The version I made was a pair of mesons that also gave the user the ability to do what the scanner does here but they are always visible.
I'd like to suggest making it either an upgrade to the depth scanner or making it another piece of gear that's a step up, like my mesons idea, because the xenoarch gear belt is quite full already if you plan to take enough for complete xenoarch work(not lmao-I-handpick-pick-handpick everything). Pickset/brush, pick, handpick, gps, core sampler, scanner, and tape measure.

**Comment by DrSnips** [comment]
I don't see the need for having two of them. I would just have the advanced one at anom. 2 research with the plasma cost.
I'm speaking from experience with reagent scanners and how many basic vs advanced versions were made. The basic one was never made, unless by accident, since it was "not useful enough" with just telling you the reagent names which was too little info. This is a pretty similar case since the basic level one gives you hardly any info about the sites them self.

**Comment by Probe1** [comment]
That's pretty powerful.  The last time this was added it remained admin spawn only after people recognized having shitloads of large artifacts on the station every round was not conducive to good rounds.

I wish I could remember the name of the one that already exists, I'd suggest using it sprite.

Found it 
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/research/xenoarchaeology/tools/tools_anoscanner.dm

**Comment by DrSnips** [comment]
You're thinking of something completely different called the anomaly scanner which locates larges. This isn't even close to that.

**Comment by Blithering** [comment]
Being able to see the edges of digsites seems handy to me.

**Pull request merged**
