### PR TITLE
Strong now activates on BAC

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I'm gonna buff strong later. Maybe.
You and I know about the specific genetics trick and now this won't shop up as 800-802 anymore
Genetics is all spaghetti code that can't be fixed yet
Please consider not torturing yourself by doing Genetics by hand
The wiki is outdated and shows minor powers as activating above 802. It's probably wrong. I'm pretty sure it's B-something. BAC I think, the major powers activate on DAC

:cl:
 * rscadd: Strong mutation for Genetics is now considered a beneficial mutation and will activate on BAC

### CODE REVIEW

**Comment by MadmanMartian** [comment]
So, why the change?

**Comment by boy2mantwicethefam** [comment]
It was not considered a beneficial mutation
Weirdly, toxic farts are considered good too but I'd say they're problematic because you get affected by the jenkem if you stand still after farting

**Comment by MadmanMartian** [comment]
I thought it was minor->major mutations, not negative->beneficial

**Comment by boy2mantwicethefam** [comment]
Minor mutations trigger at BAC and major ones trigger at DAC if I recall
Due to no "hard bounds" thing, the strong gene triggers at at least 800-802

**Pull request merged**
