### PR TITLE
Revert "literally replaces all solo antag objectives with "just bee yourself""

### PR DESCRIPTION
**Pull request by jknpj**
Reverts vgstation-coders/vgstation13#19485

You know the drill.

:cl:
 * rscdel: replaced "just bee yourself" with solo antag objectives.

### CODE REVIEW

**Comment by kilozombie** [comment]
Makes sense to speedmerge something you don't want in the game so it can be reverted immediately after.
That's what we're all about here at VG

**Comment by Orangerush** [comment]
*rubs hands* just as planned

**Comment by ProfanedBane** [comment]
literally update your home to the death barrier

**Comment by kilozombie** [comment]
The revert is warranted because speedmerging something controversial deserves a revert. But it shouldn't have been speedmerged at all, it should have been un-memefied, voted on, and maybe put in. Because it's something some players are actually clamoring for.

Also can we wait a minute before making this another big controversy, everything's gonna be fine boys

**Comment by Accipitermaris** [comment]
1. Guy makes complete goof PR that despite being a total goof, has something to it (Tetris Research)
2. Someone else speedmerges it
3. Gets reverted because it's a goof PR that got speedmerged
4. Goof PR gets banished to the shadow realm of our social consciousness because it was speedmerged 

When can we break the cycle?

**Pull request merged**
