### PR TITLE
PA interaction with SM

### PR DESCRIPTION
**Pull request by adacovsk**
:cl:
 * rscadd: PA now adds energy to supermatter power

### CODE REVIEW

**Comment by gurfan** [comment]
Does this consume the PA beam or does it pass through the supermatter, I think it should do the latter

**Comment by adacovsk** [comment]
> Does this consume the PA beam or does it pass through the supermatter, I think it should do the latter

Passes through, test it if you want. I want it to be more powerful than emitters but hard to determine because of different tick rates. Currently, I think it's only effective on level 3

**Comment by ConfusedCactus** [comment]
this has great meme engine potential

**Comment by GreatBigFailure** [comment]
Good change. PA needs more interactions.

**Comment by Eneocho** [comment]
Make it a lot stronger, it's enough to feed a singulo straight into hypermassive material-sucking weights, it should be a very powerful tool in an SME, at the cost of higher risk (and all the extra space used).

**Pull request merged**
