### PR TITLE
Trophy Meats crate buff.

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Adds cockroach, cricket, mutated cockroach, nymph, vox chicken and polyp meat to the trophy meat crates' randomized selection list.
## Why it's good
Easier access to rare meats for dishes is good.
:cl:
 * rscadd: Trophy meats crate can now have cockroach, mutated cockroach, cricket, nymph, vox chicken and polyp meat.
 * tweak: Renames the "Trophy meats" crate to "Assorted meats".

### CODE REVIEW

**Comment by BomberBro** [comment]
Cockroach doesn't seem like a trophy meat to be frank

**Comment by WindowsErrors** [comment]
> Cockroach doesn't seem like a trophy meat to be frank

you clearly aint ever been to a west coast coastal city

**Comment by Eneocho** [comment]
> Cockroach doesn't seem like a trophy meat to be frank

Considering the crate has generic synth meat and chicken meat too this doesn't seem too farfetched. Perhaps renaming it to "Assorted Meats" would work?

**Comment by BomberBro** [comment]
Yeah at this point that's probably a good idea

**Pull request merged**
