### PR TITLE
Makes Bolas Launcher work on more mechs not just Gygax.

### LINKED ISSUE #8997: Bolas Launcher not working on Phazon?
Tried to add a Bolas Launcher to a Phazon mech and it didn't work, the wiki doesn't say anything about mech exclusivity so feature?

### PR DESCRIPTION
**Pull request by coldcola**
Seems this was left in and no one took it out, tested and ready if this is a warranted fix.
closes #8997.

### CODE REVIEW

**Comment by Imagebard** [comment]
No changelog entry.

Actually you just deleted part of the code here.
I'm pretty sure this allows *every* exosuit to use them, actually. Isn't that a bad idea?

**Comment by gbasood** [comment]
Well, is there an exosuit you can think of that we wouldn't want using this?

**Comment by coldcola** [comment]
I tested it on a Ripley and it didn't work so I think it's still limited. 
How do I changelog, I just followed the guide on the wiki.

**Comment by Shadowmech88** [comment]
> I tested it on a Ripley and it didn't work so I think it's still limited. 

Limited to what, exactly?

**Comment by coldcola** [comment]
Combat Mechs I suppose? I only explicitly tested the Ripley because I knew that one might cause some controversy. 
As Sood asked though, is it a problem even if it did work on a Ripley?

**Comment by Shadowmech88** [comment]
Have you verified whether it works on other combat mechs? Durands, phazons, et cetera?

**Comment by coldcola** [comment]
The main intent was Phazon so it should work on Durand as well, I will check.

**Comment by PJB3005** [comment]
Due to the type it's now calling the parent's procs so yes this should be fine.

**Comment by coldcola** [comment]
Yes, it works as it did before on Gygax and now works on Durand.

**Comment by Imagebard** [comment]
If its just the Durand and the Gygax then its fine, I guess.
No comment on the Phazon exosuit.

Certainly not for the Mining Exosuit.

**Comment by coldcola** [comment]
Mind telling me how I do a changelog? Nothing on it on the wiki.

**Comment by Imagebard** [comment]
>All checks have failed

Fumble
Fumble

**Comment by coldcola** [comment]
I asked twice! Changelog is fucking me

**Comment by Imagebard** [comment]
I can only wish you best of luck, since, y'know, I'm not a coder.

**Comment by Shadowmech88** [comment]
@coldcola 

```
author: coldcola
delete-after: True
changes:
- tweak: Removes Gygax-only Bolas Launcher restriction.
```

**Comment by coldcola** [comment]
thanks a lot, much appreciated

**Comment by FudgePucker** [comment]
Bola launcher sucks
All nonleathal options for mechs suck.
Try to arrest some one using a combat mecha, you have to shoot them with the bolas then quickly load them in the portable brig.

Oh and THEY CAN RESIST OUT IN SECONDS OUT OF THE PORABRIG. YOU DONT HAVE ENOUGH TIME TO GET TO SECURITY TO PROCCESS THEM. THE ONLY TIME I TRIED I ENDED UP JUST PUNCHING THEM TO DEATH AFTER THEY RESISTED OUT.

THE ODY HOWEVER CAN SHOOT SLEEPY SYRINGES AND HOLD PEOPLE FOREVER.

**Comment by Imagebard** [comment]
Actually, lets make a issue about that.

**Comment by Imagebard** [comment]
Wait no I have never used a security hardsuit, all I know is that they use literally the same taser shot type as a normal taser.
FudgePucker you do it.

**Comment by coldcola** [comment]
my main intent here was to make them work in general, the wiki had no information as to why the bolas launcher was only working with the Gygax so after asking around I removed the restriction.

Make an issue if the launcher itself needs tweaking but at least now it works on other mechs.

**Comment by gbasood** [comment]
@FudgePucker Sounds like portabrig needs a buff
Do what @Imagebard said and make an issue out of it, mention that the ody is basically a better captive-taking mech than a portabrig mech

**Comment by FudgePucker** [comment]
Fun fact. There already might be an issue about it let me check

**Comment by coldcola** [comment]
@FudgePucker
I've tried resisting from inside the mounted jail to no success so I'm not seeing a problem there but it does seem like the default timer is pretty low before the auto-eject occurs.  Seems like a balance issue, is the mounted jail necessarily for holding prisoners indefinitely or more a means of transport?

**Comment by Shadowmech88** [comment]
I believe it's mainly for transport, but I don't think there should be a timer on it at all. I think it should hold prisoners indefinitely, but the prisoners should gain the ability to resist out of it. When they attempt resisting, give a prompt to the mech pilot in the chat window to allow the pilot to deliver a stun to the prisoner inside the cell. In this way, a prisoner can escape from the gygax if the mech is empty or the pilot is braindead, but will be unable to escape otherwise.

**Comment by coldcola** [comment]
any objection in removing the same restriction from the mounted jail to allow use on durand, phazon?

**Comment by Imagebard** [comment]
+ For Durand.
No comment on Phazon(Is it even supposed to be used for combat/security? I don't get it.)

**Comment by coldcola** [comment]
I always assumed it as such advanced tech that it could(or should) equip anything.

**Pull request merged**
