### PR TITLE
Some clarifications on the code of conduct

### PR DESCRIPTION
**Pull request by ShiftyRail**
Thank you Microsoft x2

### CODE REVIEW

**Comment by oversane** [comment]
epic fail on the jewish anon

**Comment by tuypo1** [comment]
You aren't gonna stop it, TG was done in over a wordfilter meant to keep the gamer word out. there is no reasoning with these people on any level

**Comment by ShiftyRail** [comment]
it's still the only thing I'm willing to do at this stage

**Comment by DamianX** [comment]
Travis failed and no code was changed.

**Comment by ShiftyRail** [comment]
I don't get it either. I assume it's from a forbidden character for the EOF.

**Comment by DamianX** [comment]
That test has been failing randomly for a while.

**Comment by ghost** [comment]
> 
> 
> You aren't gonna stop it, TG was done in over a wordfilter meant to keep the gamer word out. there is no reasoning with these people on any level

This is wrong. The wordfilter you've likely seen mentioned was the one for the Smile disability that replaces quite a few bad words, which we also have in our codebase. They weren't trying to "keep the gamer word out", though the nature of the filter is likely irrelevant for the sake of the takedown.

**Comment by tuypo1** [comment]
Oh I stand corrected
Still now that ss13 is under scrutiny I don't think there is much hope, especially once they realize we are a 4chan server

**Comment by Exxion** [comment]
This definitely wouldn't save us if they decided to care about us

**Comment by tuypo1** [comment]
Honestly I think the only slight bit of hope would be to not only clean up the code but implement an actual strict wordfilter as a sign of submission

**Comment by ShiftyRail** [comment]
do w/e you want

**Pull request merged**
