### PR TITLE
Tweaks pAI's software interface

### PR DESCRIPTION
**Pull request by jknpj**
Before (black title so you can actually see it exists):
ugly

After:
pai os new

Makes pAI OS dark gray and tweaks some minor stuff to make it look better also fixes both title/background being white. <s>Seems like pAI OS' green background image was broken since forever so that kinda explains why we had both white title AND background.</s>

### CODE REVIEW

**Comment by Probe1** [comment]
>Don't merge it until do something

**Comment by Probe1** [comment]
Please let us know when this is ready for review.

**Comment by ComicIronic** [comment]
I think that looks much better.

**Comment by jknpj** [comment]
@Probe1 it's ready.

**Pull request merged**
