### PR TITLE
dionas who evolve while held no longer delete worn objects

### LINKED ISSUE #8550: Diona Nymphs lose all equipped items if held when evolving
(WEB REPORT BY: mxr41 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> bef905aad65ed3da2ed3b0d1b185921b2013dd84
> 
> General description of the issue
> If diona evolve while being held by another person, they loose all equipped items. 
> 
> What you expected to happen
> Not losing bag (equipped as nymph)
> 
> What actually happened
> Lost bag (equipped)
> 
> Steps to reproduce if possible
> Be diona with backpack, be held, evolve.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #8550

I've tested that this compiles, I can assure you it does.

### CODE REVIEW

**Comment by Exxion** [comment]
Eeeeeeeh
`get_turf()` doesn't seem like a good way to do this in my opinion, but I can't think of a better way off the top of my head

**Comment by Intigracy** [comment]
How is get_turf() not the optimal solution?

The diona's loc is the diona holder. The diona's loc.loc is the person holding the diona holder. The diona's loc.loc.loc is the turf.

**Comment by Exxion** [comment]
Only if the person is standing directly on a turf and the diona isn't in a bag within a BoH
Say a diona evolves while someone is going on a disposal pipe ride. The diona's stuff (and probably actually the diona itself, too, which isn't your fault) will pop out on the floor above the pipe.

**Comment by Intigracy** [comment]
You can't bag diona, can you?

**Comment by Intigracy** [comment]
I could add a check to get_turf to see if the loc.howevermanylocs istype disposal pipe or pipe, but that could cause unforseen issues on things that rely on getturf to actually produce a turf.

**Comment by Exxion** [comment]
Yeah, you can stick diona nymphs in your bag, but they die after a while
Couldn't you just put the items the nymph was holding/wearing on the adult diona in the corresponding slots?

**Comment by gbasood** [comment]
You could potentialy overfill the storage of whatever the nymph was in so no that's a bad idea

**Comment by Exxion** [comment]
How, exactly?

**Comment by gbasood** [comment]
Oh, misread
You could do that as well, yes

**Pull request merged**
