### PR TITLE
Area portal turfs

### PR DESCRIPTION
**Pull request by ghost**
[content]
Should be able to make rooms that loop on itself much easier now.
:cl:
 * rscadd: Mappers can now place "area portals", which render a turf elsewhere and teleport all items to it immediately when on.

### CODE REVIEW

**Comment by DeityLink** [comment]
Not to be confused with https://developer.valvesoftware.com/wiki/Areaportal which is also something mappers can place in maps.

**Comment by ghost** [comment]
> Not to be confused with https://developer.valvesoftware.com/wiki/Areaportal

That's actually why I named them that

**Comment by DeityLink** [comment]
Their use in both instances are nothing alike though, I honestly don't know which one fits the name better.

**Comment by ghost** [comment]
> Their use in both instances are nothing alike though, I honestly don't know which one fits the name better.

Oh wait you're right, dunno what I was thinking of then.

**Pull request merged**
