### PR TITLE
Genetic power/disability "buffs"

### PR DESCRIPTION
**Pull request by ghost**
:cl:
 * rscadd: The strong genetic power now allows holding of twohand-only items in one hand.
 * rscadd: The heat resistance power now allows withstanding high pressures, to contrast with cold resistance withstanding low pressures.
 * tweak: Hallucination disability now makes players hallucinate 4 times more often. (from 1 in 100 per tick to 1 in 20)
 * tweak: Fat disability now remove fatness on deactivation if nutrition is below the threshold for fatness.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
So I can hold TWO carp?

**Comment by Eneocho** [comment]
Can the heat resistance power also affect internal heat? Because I had heat res and was at 1500 degrees on a recent round but still burned.

**Comment by Eneocho** [comment]
Also, I'd buff the Strong mutation to also allow resisting outta cuffs faster, say, 50% faster (takes 1 minute instead of 2).

**Comment by ghost** [comment]
> Also, I'd buff the Strong mutation to also allow resisting outta cuffs faster, say, 50% faster (takes 1 minute instead of 2).

The wiki says it can do that but you can't actually for some reason, I'll think about it.

**Comment by BomberBro** [comment]
I don't like the idea of a gene you can get infinitely being stronger at deflecting pressure damage than a Chief Engineer suit.

**Comment by kernikov** [comment]
> I don't like the idea of a gene you can get infinitely being stronger at deflecting pressure damage than a Chief Engineer suit.

simply built different

**Comment by GreatBigFailure** [comment]
> Also, I'd buff the Strong mutation to also allow resisting outta cuffs faster, say, 50% faster (takes 1 minute instead of 2).

If I remember right it already does. The strong mutation lends to strength which affects cuff resisting.

**Comment by Kurfursten** [comment]
I'm not sure about the 2handed buff, there might be things that start runtiming because they expect you to have an offhand. Did you investigate this thoroughly?

Also, strong does a lot of stuff because it increases strength - affects tackles, picking up anvils, cranking muskets, etc. - a bunch of things.

**Comment by Dacendeth** [comment]
The strong 1h thing might not play will with hunting rifles.

**Comment by ghost** [comment]
I would blacklist guns from the 2hand buff since that makes no sense. I think most other things should play well.

**Comment by ghost** [comment]
The 2hand buff only checks for items that force you into it like corgis, carp, gibtonite ore and etc @Kurfursten @ancientpower

**Pull request merged**
