### PR TITLE
Breakable Objects v2

### LINKED ISSUE #32126: Grue can't attack cameras!
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
c6e570daef731ad55560e565bfb38f107900ec15

# Description
A camera has a big bright light which can hurt a grue alot, you can't attack it at all though
# Steps to Reproduce
try to click the big bright camera
# What you Expected
Something to happen beyond nothing
# What Actually Happened
I got sizzled by the camera light

### LINKED ISSUE #32227: tasers crashing server
firing a taser through a window makes it bounce repeatedly forever

### LINKED ISSUE #32230: break toolboxes with one kick
you can break a toolbox with one kick and delete the toolbox with everything inside of it

### PR DESCRIPTION
**Pull request by Hinaichigo**
[system]
This is a reboot of the breakable objects framework proposal. I fixed the bugs that were reported and neatened a few things up and tested various cases and it seems to be working properly, so I'm opening this PR for now to get some feedback, help people who were concerned about the bugs to understand what this does, and hopefully get it considered again.

The idea is that any object can be selectively flagged as breakable in different situations, including being struck with a weapon, shot with a projectile, thrown against something, being hit by something thrown at it, struck by a simple mob, kicked, and bitten.
Essentially every interaction this adds is behind checks for breakable_flags, so it shouldn't impact anything unless it's specified to do so. The only exception to this is that shooting an object (even an unbreakable one) with a projectile that deals brute damage can propel it around, which I think is just nice to have as an option; you can shoot a fork off a table with a revolver, and things like that.

One benefit to doing this is that you don't need to add a specific interaction for every new type of object that's added. Instead of windows, cameras, lockers, grilles, etc. all having unique procs to specify their being damaged and breaking, they can all be funneled through one consistent framework, then changed in specific cases where necessary. Say a new thing like "acid ooze" was added that can go around dissolving objects in the station. Instead of having to define ooze_act() for every specific case (like blob_act() currently is in many cases), you can define a general ooze_act() for all objects and then flag various objects as breakable via ooze_act().

I would like to ask about doing this via components, which was suggested to use for this more than once. Is the idea that each breakable object would have a "breakability component" `add_component()`ed to it during `New()`? And all damaging and breaking would occur through that component rather than the base `obj` itself? What is the benefit of doing it that way? One concern I have is that there are various implementations of damageable objects throughout the code, and doing it the current inheritance-based way lets all these slowly fuse together into the new system, whereas to my understanding a component system would use different variables and not be as "backwards-compatible" if that makes sense.
ie. many objects already have:
`health`,
procs with similar functionality to `take_damage()`, `damaged_updates()`, `try_break()`,
etc.
Using the inheritance-based method these can be gradually integrated with the new system without altering any of their in-game behavior by default but allowing them to be more easily expanded on. I also think it would allow for objects to be made breakable rather simply, by setting the proper flags and filling in the relevant parameters. But is there a good way to do this type of thing with components as well? I'm taking a look at them to see if I can figure out how to implement it nicely that way. Maybe somebody can point me in the right direction in this regard.

Feedback would be greatly appreciated, thanks.

Tests:
- [x] Throwing-and-breaking breakable items.
- [x] Throwing-and-not-breaking non-breakable items.
- [x] Kicking-and-breaking breakable objects.
- [x] Kicking-and-not-breaking non-breakable objects.
- [x] Biting-and-breaking breakable objects.
- [x] Not-biting non-breakable objects.
- [x] Shooting-and-breaking breakable objects.
- [x] Shooting-and-not-breaking non-breakable objects.
- [x] Weapon-hitting-and-breaking breakable objects.
- [x] Not-weapon-hitting non-breakable objects.
- [x] Mob-hitting breakable objects.
- [x] Not-mob-hitting non-breakable objects.
- [x] Throw-hitting-and-breaking breakable objects.
- [x] Throw-hitting-and-not-breaking non-breakable objects.

Closes #32227
Closes #32230 
Closes #32126

:cl:
 * experimental: Some objects can be smashed and broken once again. Please use the bug report button to report undesired behavior.
 * rscadd: Breakable cameras, wall-mounted lanterns, flashlights, lamps, and beakers.
 * rscadd: Shooting an object can propel it around.
 * tweak: Small objects can be kicked around like tiny objects can.

### CODE REVIEW

**Comment by adacovsk** [comment]
does this fix projectiles yet?

**Comment by Hinaichigo** [comment]
> does this fix projectiles yet?

Yes. The issue was that obj/bullet_act() wasn't returning the proper value. I tested it and taser bolts impact windows properly now.

**Comment by adacovsk** [comment]
> Yes. The issue was that obj/bullet_act() wasn't returning the proper value. I tested it and taser bolts impact windows properly now.

check flareguns aimed at windows too

**Comment by Hinaichigo** [comment]
> > Yes. The issue was that obj/bullet_act() wasn't returning the proper value. I tested it and taser bolts impact windows properly now.
> 
> check flareguns aimed at windows too

Works fine too. Bullets break windows normally as well. The problem originally was that I used `..()` instead of `. = ..()`, so the proper value wasn't being returned to indicate that the taser bolt hit something. All of the (new) breaking-related functionality is behind a check for a flag that windows (and all objects currently) don't have set, so this doesn't change their response to projectiles, as intended.

**Comment by Eneocho** [comment]
Does this fix the "can't kick any medium sized object" issue? I tried kicking an emergency airtank but it just wouldn't budge.

**Comment by Hinaichigo** [comment]
> Does this fix the "can't kick any medium sized object" issue? I tried kicking an emergency airtank but it just wouldn't budge.

You can kick them but they won't budge. Being able to kick something doesn't necessarily mean you can kick it around. It was originally like this before I changed anything as well. Try kicking an emergency oxygen tank on the current live Bleeding-Edge; it doesn't move. Kicking something around originally requires `( kick power > 6 ) `.
and `kick_power = max((H.get_strength() * 10 - (w_class ** 2)), 1)`
So, sufficiently heavy items won't be propelled if a human kicks them.
The only thing I changed in this regard is changing `w_class` to a new proc `get_total_scaled_w_class()` which accounts for the `w_class` of the contents of an object as well. Since an emergency oxygen tank has no contents, it's functionally the same, I tested it to be sure it's the same in this case.

Are you sure you were able to kick emergency oxygen tanks around before?
Emergency oxygen tank has a `w_class` of `2` and `H.get_strength()` is `1`.
So `kick_power` is `6`, which isn't greater than `6`, and so it isn't thrown around.
This means that only `W_CLASS_TINY` objects can be kicked around by a standard human.
We could change it to `>= 6` instead so that `W_CLASS_SMALL`s can be thrown as well, but that's a different matter.

The original code for kicking items is in `code/game/objects/items.dm` in `obj/item/kick_act()`.

**Comment by Eneocho** [comment]
>Are you sure you were able to kick emergency oxygen tanks around before?

It is standard B&E when you don't have tools. You drop the o2 tank then kick it to break the window. I assume it broke when you got the breakable objects framework merged, I haven't been able to kick and have them move since.
Please fix it. I miss kicking objects and have them move. The change so small items can be kicked too would be nice.

**Comment by Hinaichigo** [comment]
> It is standard B&E when you don't have tools. You drop the o2 tank then kick it to break the window. I assume it broke when you got the breakable objects framework merged, I haven't been able to kick and have them move since. Please fix it. I miss kicking objects and have them move. The change so small items can be kicked too would be nice.

I double checked here and it seems like it was originally `if( kick_power > 6)`, before I changed anything anyway
https://github.com/vgstation-coders/vgstation13/pull/32007/files

I'll change it.

**Comment by Hinaichigo** [comment]
Every bug that was reported and I could find was fixed, and I tested through the various cases, so I'm going to open this again.

**Comment by adacovsk** [comment]
make sure to write Closes #32227 etc

**Comment by Eneocho** [comment]
Closes #32230 as well.

**Comment by godietxt80** [comment]
i'm down for it, let's see how it goes... again

**Comment by Cartlord** [comment]
What will this, meaningfully, add to the game? I want a real scenario where this will MATTER.

**Comment by Eneocho** [comment]
The light sources matter for grue purposes and the beaker stuff will enable some small gimmicks/gunk/antagonizing.

**Comment by Eneocho** [comment]
Is there a way to fix partially broken stuff? Say, a cracked beaker or a half broken flashlight.

**Comment by NiftyRyanyan** [comment]
> The light sources matter for grue purposes and the beaker stuff will enable some small gimmicks/gunk/antagonizing.
We really don’t need all of this just so grues can break a few lights and if the best reason you can think of for breakable beakers is gunk/gimmicks, it really shows how useless this is.

**Comment by Eneocho** [comment]
> We really don’t need all of this just so grues can break a few lights and if the best reason you can think of for breakable beakers is gunk/gimmicks, it really shows how useless this is.

I have to agree on that. The framework and mechanics weren't really necessary for grues, since a handful of checks on some light sources would've been the end of it, but I am hopeful good stuff will come out of having such a framework. The beaker part I dislike as well since I like my beakers non-shatterable, but it ain't that big a deal.

**Comment by Hinaichigo** [comment]
This system isn't just for grues. I could have copied the damage procs over from another breakable object, to flashlights, and called it a day, but that would just be perperpetuating the current paradigm of having snowflake code every time you want something to be made breakable, which would have to be  We could even just remove all specific breakable objects from this PR and then debate the specific items to actually make breakable in a serparate PR, if we feel it's too 'entangled' here. But I don't feel that 
A human throwing an item like a beaker doesn't do that much damage to it. And we can set the armor of a beaker to be just high enough that it doesn't do any damage if you are just throwing it on a

**Comment by Hinaichigo** [comment]
This system isn't just for grues. I could have copied the damage procs over from another breakable object, to flashlights and lamps, and called it a day, but that would just be perpetuating the current paradigm of having to add new snowflake code every time you want something to be made breakable, which potentially would have to be updated every time a new damage source is added. A current example of that is that while cameras can be attacked by human holding a weapon, there's no proc to deal with them being attacked by a simple mob. Instead of adding a new attack_mob() proc to cameras, we can now just add the BREAKABLE_UNARMED flag and a few parameters and it will function properly.
We could even just remove all specific breakable objects from this PR and then debate the specific items to actually make breakable in a separate PR, if we feel it's too 'entangled' here. But I feel that this is already pretty limited in scope in terms of the objects it makes breakable. And I want people to be able to mess around with it in game a bit. I figure beakers are a nice common item that makes sense for that.
A human throwing an item like a beaker doesn't do that much damage to it. And we can set the armor of a beaker to be just high enough that throwing it on a table doesn't harm it, but smashing it with a crowbar will.
And currently there is no way to repair damaged objects but it's on my list for expanding this once the foundation is relatively stablized.
See #32007 for a list of things I've been considering as areas for expansion.

**Comment by Eneocho** [comment]
You could use Silicate spray to fix glass-based objects such as beakers or screens, solders to fix damaged electronics like cameras and the like, wooden items fixed with glue, a regular welder to fix metal-based objects like broken forks or similar, etc. With combinations of these methods for more complex stuff.

**Comment by Hinaichigo** [comment]
> You could use Silicate spray to fix glass-based objects such as beakers or screens, solders to fix damaged electronics like cameras and the like and a regular welder to fix metal-based objects like broken forks or similar.

That's a good idea. But we have to add some notion of item materials first. I was thinking of doing that already so glass objects can shatter into shards by default, wood objects splinter into wood chips, etc. With the possibility of specified fragments like this current system of course.

**Comment by Hinaichigo** [comment]
With the current settings, beakers thrown down a hallway or onto a table don't take enough damage to get past their armor. Throwing a beaker at a wall or at someone, kicking it, or smashing it with a crowbar will cause it to take damage though. So chemists can still throw beakers onto the tables as part of their workflow if they're careful about it. And the same goes for desk lamps. This is because thrown objects hitting a floor take half damage relative to hitting anything else; it's a matter of "sliding to a halt" versus "colliding head-on".

**Comment by WindowsErrors** [comment]
if i throw something into a trash disposal and it breaks does the shattered stuff go into the disposal too

**Comment by Hinaichigo** [comment]
> if i throw something into a trash disposal and it breaks does the shattered stuff go into the disposal too

Currently, things don't take damage when they land in a disposal, or if someone catches them mid-flight, the former mainly being a side-effect of the latter. There's a check to make sure it's out in the open and not inside something in order to count as "impacting X" rather than "being caught by X". I've been thinking about the implications of having them break inside something, but then there are cases like, say you have a backpack with all inventory slots completely full of items, and then you break one of them (currently you can't attack items inside of a backpack, but assuming you could somehow get it to break - say if backpacks were given some notion of flexibly so that attacks to a backpack would transfer the impact to its contents). If that item breaks into more than one fragment, what happens to the excess fragments that can't fit into the inventory slots? It's not really relevant in the case of disposals but still something to think about.
Also, another thing to consider is, what should happen to reagents inside an item when it breaks inside an object like a disposal? When I test with a welder-fuel-filled beaker breaking inside of a disposal, the broken glass fragment appears inside the disposal properly, but the fuel spills all over the floor outside of it. We could store the reagents inside the disposal itself, or add a check to just not spill the reagents if it's inside something, but the latter essentially deletes those reagents. What would make the most sense to have happen would be for the reagents to go into the pipe and shoot out the other end... but a system like that's not in place yet. Maybe with puddles as a foundation we could then add boli of liquids moving through pipes and such.

**Comment by Hinaichigo** [comment]
@DamianX I've been wondering, if I was going to do this with components, what would be the best way to reference the parent's vars? Say I wanted a proc defined for a `datum/component/breakable` that referred to and operated on the vars of the parent `obj`.. what would be the nicest way to do that? Would I have to do something like:
`var/obj/O = parent as /obj`? 

Also, what's the benefit of doing it like that?
Thanks!

**Comment by DamianX** [comment]
You'd need something like `var/obj/thing/parent_thing = parent`. All procs that need to use those vars would need to declare a variable like that.

**Comment by Hinaichigo** [comment]
I see, thanks.

**Comment by Hinaichigo** [comment]
I see, thanks.
If you then modified the vars of `parent_thing`, would it then update them in the actual parent?

**Comment by DamianX** [comment]
Yes. `parent_thing` will be a reference to the same object as `parent`, but stored in a local var with a different type.

**Comment by Kurfursten** [comment]
Is this good to go? I was thinking we could merge this experimentally and let people test it again on live. I don't see it realistically getting enough testing to work out the bugs otherwise. It just touches too much stuff.

**Comment by Hinaichigo** [comment]
It functions properly and I fixed the known bugs from before.

**Comment by Eneocho** [comment]
Are the survival box oxygen tanks kickable again?

**Comment by Kurfursten** [comment]
I will try to remember to merge this during lowpop tomorrow.

**Pull request merged**
