### PR TITLE
Construction permits episode 69

### PR DESCRIPTION
**Pull request by jakmak6**
memez edition

What this change does is it adds in new mini blueprints called construction permits.

What these are are basically MOMMI prints accessible to all engineers/atmostechs/autists in the engi vend. They can create new rooms for use of APC's and air alarms and rename those rooms but CANNOT rename roundstart rooms (so engineers cant go around and rename every hallway to benis).

These permits DO NOT count towards the antag steal blueprints objective.(tested)

This would make it easier and encourage autism forts because previously you either had to be a MOMMI or steal the CE blueprints (or worse be the CE).

proof it works https://puu.sh/wCeKb/491c439848.webm

🆑 *rscadd: Added Construction permits to the engi-vend

remake of https://github.com/vgstation-coders/vgstation13/pull/15343 which is a remake of some other earlier version

### CODE REVIEW

**Comment by ghost** [comment]
I'm just gonna merge this before it gets broken again, as soon as travis wakes up

**Comment by SonixApache** [comment]
inb4 server explodes

**Comment by ghost** [comment]
wouldn't be the first time

**Comment by jakmak6** [comment]
FINALLY AFTER MONTHS THE COPY PASTED MOMMIBLUEPRINT CODE IS MERGED!

**Comment by SonixApache** [comment]
lucky seven

**Comment by gbasood** [comment]
one day jakmak might actually learn how to rebase by trying to use git outside of ss13 and actually gaining an understanding of what git even does

**Pull request merged**
