### PR TITLE
Redo Arrivals

### PR DESCRIPTION
**Pull request by ghost**
- Made hallways three tiles instead of two
- Added a bunch of stuff like more floor markings, more intercoms, some tables, a few extra vending machines
- Re-did the brand new extended Arrivals Dock to be less shit, gave tags to cameras, made it not bland as fuck, added air machinery, etc

new_arrivals

### CODE REVIEW

**Comment by clusterfack** [comment]
Someone should do something about the vacant office

**Comment by ghost** [comment]
I tried to expand the waiting area, but the Cargo Shuttle gets in the way, so it's REALLY hard to touch up the Disposals area

**Comment by CptWad** [comment]
@clusterfack just leave it there till we get a new job then we can slap them in there

**Comment by Kurfursten** [comment]
With the addition of a new ship dock, that hallway looks increasingly weird. Do you think it would look nicer if we just pushed out the other docks and made it a nice big waiting area? Or hell, you could even build out maintenance and put some great new content there, like a ghetto robotics room (like meta has) or a shopfront for the traders (like defficiency has), or an extra firecloset (since there is none on this side of the station), or some other good maintenance content.

untitled

**Comment by 9600bauds** [comment]
That's where shit docks

**Comment by Kurfursten** [comment]
You can move docking ports matey

**Comment by ghost** [comment]
I think it's better to clear up the hallways first before adding that much stuff

**Comment by Kurfursten** [comment]
Yeah, maybe long-term or something. I'm just saying the reverse-L seems really awkward and someone should do something about it eventually.

**Comment by Probe1** [comment]
> gave tags to cameras

some dirty collaborator told me they would generate tags and I've been doing it wrong all these years by setting them.

**Comment by Kurfursten** [comment]
@Probe1 The subtype camera/autoname will auto-generate tags.

**Comment by clusterfack** [comment]
All cameras will auto generate tags, c_tag is meant to be an override **only**

**Comment by CptWad** [comment]
wait really

**Comment by clusterfack** [comment]
Yes it will generate [area.name] 1, 2, 3, etc

**Comment by CptWad** [comment]
holy christ I put so much effort into my cameras for no good reason then jesus christ thats like one less thing to worry about

**Comment by clusterfack** [comment]
That's what you guys get for varediting everything, we can do so much with code.

**Comment by CptWad** [comment]
can you reorganize the under-floor robot pathing/mulebot delivery beacons?

**Pull request merged**
