### PR TITLE
If assistants don't get maintenance, then neither should security

### PR DESCRIPTION
**Pull request by Intigracy**
Addition to the dumbness that is #25113

merge it and revert it with that mess

:cl:
* tweak: the following jobs no longer have maintenance access: warden, security officer

### CODE REVIEW

**Comment by Irradiation** [comment]
So Head of Security still keeps maint access?

**Comment by Intigracy** [comment]
wait I'm stupid

**Comment by Intigracy** [comment]
And yeah, HoS and Detective still have maint.

**Comment by BomberBro** [comment]
When can we remove all accesses from maint and leave it as a sort of nature preserve, the maint mice and bears free to live without interference.

**Comment by ShiftyRail** [comment]
It's time to stop being retarded my lads

**Pull request merged**
