### PR TITLE
sec job priority rewards

### PR DESCRIPTION
**Pull request by SonixApache**
- HoS gets a holstered fancy glock, a can of coffee and a donut
- warden gets a holstered glock, a boot knife, a can of coffee and a box of donuts
- detective gets a boot knife and a flask of joe
- officers get a boot knife, a can of coffee and a donut
- also unatomically fixes off-center can sprite
 - can of coffee is #24640 

🆑 
 - rscadd: Added high job priority rewards to security! Boot knives, cans of coffee and donuts for everyone!

### CODE REVIEW

**Comment by utilitas-** [comment]
you forgot the elite skirt and stockings.

**Comment by IzayaChan** [comment]
Should be giving out free valids

**Comment by SonixApache** [comment]
@utilitas- I'll hard-code those to my characters in an upcoming no-PR commit, don't worry.
@IzayaChan what are donuts, if not valids?

**Comment by utilitas-** [comment]
the worst part is sonix isn't joking

**Comment by juanototo2** [comment]
@SonixApache then make sure to make a special version of them that doesn't have the added armor value and paracetamol :^)

**Pull request merged**
