### PR TITLE
Newchem(you probably shouldn't merge this just yet)

### PR DESCRIPTION
**Pull request by Iamgoofball**
> this actually merges
# wow #whoa

### CODE REVIEW

**Comment by Duny-** [comment]
#removegoofball

**Comment by Iamgoofball** [comment]
@Duny- i'm under orders from nexis to pr it to this branch so that we can use it on the test server instead of main

**Comment by N3X15** [comment]
The idea is to hammer out the broken shit before it hits main.

You know, what the test server is intended to do in the first fucking place.

**Comment by Duny-** [comment]
Doesn't mean you get to erase all of the comments by not linking to the old PR goofball
Also remove yoself

**Pull request merged**
