### PR TITLE
Allows clone backups from destroyed bodies (but for real)

### LINKED ISSUE #24015: Slime people and their brains are broken
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
c42aab6f351798161d7d6fdcdbbccc02de66987f

# Description
Can't put their shitty slime core brains in their dead puddless
# Steps to Reproduce
Get slime-man. Kill slimeman. Try to put their rainbow slime core into their puddle to clone or something.
# What you Expected
Expected the core to go in and them to get cloned
# What Actually Happened
Slime core (the brain) dropped at my feet

### LINKED ISSUE #34458: Can't clone from backup if you get SME'd
(WEB REPORT BY: inorien REMOTE: 206.221.180.138:7777)
# Revision
9bbc953ff111d2fa0e9929396fbe26be78fbb82f

# Description

See title

# Steps to Reproduce

get backed up in medbay
go touch a shard
be unclonable

# What you Expected

be clonable

# What Actually Happened

be unclonable

# Additional:

#34185

### LINKED ISSUE #34462: slimepeople that get gibbed/dusted/etc have weird slime puddles
slime people that get dusted/gibbed/etc. spawn a puddle with a null `slime_person` var
probably should just not spawn one at all

### PR DESCRIPTION
**Pull request by nervere**
#34185 doesn't work and, as far as I can tell, never did.
Fixes #34458
Fixes #34462
Fixes #24015
## What this does
This PR ensures that people who got scanned at genetics can still have their DNA record used for a clone, even if their body was gibbed/dusted/etc. after the scan happened.

## Why it's good
It doesn't make sense that your clone backup magically doesn't work because you ran into the SM shard.

[bugfix]
## Changelog

:cl:
 * bugfix: Non-existent bodies can once again be cloned, assuming you got yourself a DNA scan beforehand.
 * bugfix: Slimepeople that are dusted no longer generate slime puddles.
 * bugfix: Slimepeople that are gibbed are now cloneable, provided you have their slime puddle.

### CODE REVIEW

**Comment by nervere** [comment]
PR is now ready.

**Comment by nervere** [comment]
(And in case you're wondering why I chose to put the slime fixes in this PR, it's because it's required for them to be cloned at all when gibbed. See #34463 for related fixes to slimepeople.)

**Comment by ShiftyRail** [comment]
I kinda like the soul hypothesis, also this makes it so you can actually survive trying to mindproject into the singularity (lame)! But I guess the Kanefoïde version shouldn't have been merged

**Comment by Killette2** [comment]
Legendary fix, we've been suffering from this for what feels like a decade

**Pull request merged**
