### PR TITLE
Realistic Night Vision Goggles

### PR DESCRIPTION
**Pull request by DeityLink**
image

:cl:
* experiment: Night Vision Goggles have been reworked to display your surroundings like those do in real life. As such beside pitch black areas will appear adequately lit, while brightly lit areas will appear blinding, similarly to how Giant Spiders already see the world.
* bugfix: Fixed Giant Spiders being able to see lights through walls.

### CODE REVIEW

**Comment by beesil** [comment]
The idea is cool, but it looks super ugly

**Comment by SonixApache** [comment]
you can easily appease the "this looks ugly" crowd by adding scanlines

**Comment by Exxion** [comment]
Oh, right. There is one problem with that solution I forgot to mention, but it's an easy fix. That method to hide lights you can't see draws the entirety of plane 0 above lights, which currently includes some objects. Fixing that would just involve changing some of the plane defines so that no objects are on plane 0.

**Comment by DeityLink** [comment]
> 
> 
> Oh, right. There is one problem with that solution I forgot to mention, but it's an easy fix. That method to hide lights you can't see draws the entirety of plane 0 above lights, which currently includes some objects. Fixing that would just involve changing some of the plane defines so that no objects are on plane 0.

what objects are even included?

**Comment by DeityLink** [comment]
> 
> 
> The idea is cool, but it looks super ugly

Real life is ugly 😔

**Comment by beesil** [comment]
> Real life is ugly 😔

That doesn't mean spess has gotta be ugly too. In all seriousness I like this a lot but I don't think the effect meshes well with how the rest of the game looks.

**Comment by Exxion** [comment]
>what objects are even included?

If `planes_layers.dm` is to be believed, blood, decals, pipes and wires on floors (but not plating), and some others

**Comment by Eneocho** [comment]
An incentive to greytide the lights as a non-spider/grue, amazing.

**Comment by SonixApache** [comment]
make it more realistic-  crank up the bloom on actual lights by 10 and make them not work in actual pure darkness unless you have an IR light with you

**Comment by ShiftyRail** [comment]
@beesil There could be a lot of post-processing effects on this to make it less ugly but unfortunately post-processing effects are the devil.

**Comment by githubuser4141** [comment]
> make it more realistic- crank up the bloom on actual lights by 10 and make them not work in actual pure darkness unless you have an IR light with you

Isn't the idea of having it match today's NVs actually.. less realistic in a way? /VG/station is set 500 years in the future after all, where pockets-sized laser guns exist.. so it's actually unrealistic to assume NVGs haven't progressed from 2021- especially when you have RCDs that are capable of holding tons of steel and glass in a walky-talky sized device and *can assemble those materials in a functional electric motor door on the spot.*

I know the idea of this PR is that it's supposed to match today's NV tech but from what I Google'd a lot of NV devices come with integrated IR lights _today_ so I dunno why this'd be unusual in the year 2500.

**Comment by DeityLink** [comment]
> 
> 
> > make it more realistic- crank up the bloom on actual lights by 10 and make them not work in actual pure darkness unless you have an IR light with you
> 
> Isn't the idea of having it match today's NVs actually.. less realistic in a way? /VG/station is set 500 years in the future after all, where pockets-sized laser guns exist.. so it's actually unrealistic to assume NVGs haven't progressed from 2021- especially when you have RCDs that are capable of holding tons of steel and glass in a walky-talky sized device and _can assemble those materials in a functional electric motor door on the spot._
> 
> I know the idea of this PR is that it's supposed to match today's NV tech but from what I Google'd a lot of NV devices come with integrated IR lights _today_ so I dunno why this'd be unusual in the year 2500.

SS13 leans more toward retrofuturistism than sleek sci-fi. The game is filled to the brim with "old" items you wouldn't expect to find in the year 2500.

**Comment by DeityLink** [comment]
Now, an argument could be made about a having both versions as separate items, with the "advanced" version performing some sort of interpolation so that the lit areas appear normally lit and colored instead of blinding.

**Comment by SonixApache** [comment]
stalker did NV tiers perfectly

**Comment by DeityLink** [comment]
> 
> 
> stalker did NV tiers perfectly

Honestly not a fan 🤔 , or you'll have to specify with examples.
image

**Comment by SonixApache** [comment]
sadly my screenshots are gone so i will concede on this

I think that nightvision having minor downsides (not being able to see in well-lit areas) is fine. Gives thermals a reason to exist past seeing enemies through walls.

**Comment by DeityLink** [comment]
> 
> 
> sadly my screenshots are gone so i will concede on this
> 
> I think that nightvision having minor downsides (not being able to see in well-lit areas) is fine. Gives thermals a reason to exist past seeing enemies through walls.

Now wait until I make a Realistic Thermals PR and it makes everything look like 
image
(jk)

**Comment by Blithering** [comment]
I like the BLINDED BY THE LIGHT effect, in keeping with how wearing NVGs while welding or getting flashed is the best idea ever. Not as much of a fan of the hugely increased green-ness.

**Comment by Kurfursten** [comment]
@DeityLink STALKER interactive comparison of nightvision tiers here: http://cop.zsg.dk/NV_Scopes.php#Night_Vision

**Pull request merged**
