### PR TITLE
Adds the capillary laying operation tool. WIP

### PR DESCRIPTION
**Pull request by DrSnips**
<h1>WIP</h1>
This adds the <s>rapid vein layer</s> Capillary Laying Operation Tool (aka CLOT) and a special surgery step to go along with it.
The CLOT is intended to be used as an internal bleeding treatment tool for surgery. It acts like a faster fixovein as well as having a secondary function that allows it to inject biofoam to help stall the internal bleeding you're likely going to treat. 
The biofoam injection comes at a small cost. It eats rolls of gauze or trauma kits in order to make biofoam at a rate of 1 roll to 1u and 1 trauma kit to 5u. It has a 5u capacity limit. On top of the cost it can also only be used during surgery because <u>the way that it administers biofoam is by a surgery step</u> so you can't use it in the field very well. This step can be done at any time during the surgery.
In order to prevent an easy method to get biofoam out of the CLOT there technically isn't any reagents in the tool but rather just a value that it converts to reagents during the surgery step.

To do:
[ ]Give it a sprite.
[x]Determine the cost to make it.

:cl:
 * rscadd: Added the capillary laying operation tool (CLOT). An advanced version of the fixOvein. Using the CLOT in hand will toggle it to a secondary state where it can inject biofoam during, and only during, a surgery. You need to feed it rolls of gauze to fill it with biofoam at a rate of 1u per roll. Advanced trauma kits will make 5u per kit.
 *rscadd: A new tab in the protolathe has been added to house all surgery related designs to remove some clutter from the medical tab. The mobile operation table has also been moved to this tab.

### CODE REVIEW

**Comment by DrSnips** [comment]
<s>The planned sprite is going to look like a rapid cable layer but with two drums on it and looking a bit more medical.</s>
  Idea changed from the RVL to CLOT removing the reference to the sprite.

**Comment by strawberrytan** [comment]
I like the idea but not the name, but I also don't have any suggestions that aren't also lame

Maybe I'll throw some names here later

**Comment by DrSnips** [comment]
The idea is that it's taking the rapid cable layer design but laying vein in place of cable. I will work the secondary feature into the design somehow.
Each time I've asked in the past for a design and name I usually get a similar no idea reply.
Im not going to turn away any other ideas as long as they make a bit of sense.

**Comment by Blithering** [comment]
Capillary Laying Operation Tool or CLOT

**Comment by DrSnips** [comment]
CLOT is really good. Should I make it's reagent clotting agent rather than biofoam to match? They both do the same thing however biofoam is closer to the fuel source of the tool.

**Comment by Blithering** [comment]
I think clotting agent is for external bleeds, so it wouldn't be very useful in this instance. Biofoam seems fine

**Comment by DrSnips** [comment]
They have the same effect for internal and external they are just named differently because of context. Clotting agent comes from borers and a virus effect. Biofoam is just a renamed clotting agent.
I will likely leave it as biofoam since its a bit of a stretch with how the tool works eating trauma kits and the like.

**Comment by DrSnips** [comment]
With all of the tools for surgery I've added its starting to cause a bit of clutter in the medical tab. I've created a new tab in the protolathe to house all of the surgery medical designs as well as moving the mobile operation table to there as well. The exofab's M.O.T. design is still under misc.

**Comment by DrSnips** [comment]
I'm closing my PRs until I find some time to get back to them. I don't like them sitting around and looking abandoned.
The item sprite and inhand sprite all the only things left to do here but I don't like the abandoned look.

**Pull request closed without merging**
