### PR TITLE
Fixing Latejoining

### LINKED ISSUE #19928: Latejoin tator merchants dont get syndie menu
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
cdeb58b55178ad0ae228087a61bf4a4780d826e7

# Description
Latejoined as Merchant, got a message syndicate didn't have access to aradio even though I have spawned with one

# Steps to Reproduce
Latejoin as burd, pray for antag

# What you Expected
Emags and other things

# What Actually Happened
Cuck'd

### LINKED ISSUE #19939: Late-joins get double security (and medical?) records.
#### Description of issue

Roundstart people get one (1) security / medical record.
Late-joins get two (2).

#### Length of time in which bug has been known to occur
Recent. Probably role datums.

#### Server revision
29ac5a5bcda7bf03aa7f6900a68a8e08fde966d1

### PR DESCRIPTION
**Pull request by Kurfursten**
Looks like this was probably caused by improper merge conflict resolution based on the weirdly copied text.

Also removed an unnecessary New(). I tested this but I can easily imagine in cases like this there are weird cases that would be hard to think of in testing, as with all things that require multiple players present to test properly. Tried joining as a nonantag and antag.

fixes #19939 
fixes #19928 

🆑 
* bugfix: Fixed a typo in the trader latejoin PDA message
* bugfix:  You should no longer see twice the security records.
* bugfix: Latejoin traitors will now receive an uplink
* bugfix: If cyborg latejoin slots existed, they would work now.
* rscadd:  Ghosts should always hear the latejoin announcement even if they're not standing by a radio

### CODE REVIEW

**Comment by Kurfursten** [comment]
I have a fix for #19928 but testing has yielded some strange results. 
* Latejoin wizzyman not spawning inside Den, and getting datacore injected
* Can't seem to make traitor trader at all

Need to do some testing on live

* Tested on live, latejoin wizman works as proper and is getting his assigned_role set to MODE as proper, something I changed in the order must've messed with this

Unrelated: noticed aliens are getting their greet text twice (species being set twice?)

**Comment by SonixApache** [comment]
Please prioritize this, the two-records thing makes security gameplay pretty shit.

**Comment by Kurfursten** [comment]
I'll try to get to it tonight

**Comment by SonixApache** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Kurfursten** [comment]
done and tested

**Pull request merged**
