### PR TITLE
DAMNIT DUNY

### LINKED ISSUE #7947: GODDAMN IT DUNY
You fucked with the step_x step_y didn't you duny
oh god its like were back in 2004 what have you done to your map

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes #7947

### CODE REVIEW

**Comment by Duny-** [comment]
:(

**Comment by Exxion** [comment]
You were the one who diddly darn fucked it up

**Comment by Duny-** [comment]
So many pixel_x and pixel_y edits I had to fuck one up eventually
Fucking steps mang

**Comment by NigglyWiggly** [comment]
> PJB making a PR, tagging his PR, and then merging his PR

THE CODERBUS TYRANNY BEGINS

**Comment by PJB3005** [comment]
```
<PJB3005> hey D3athrow mind if I self merge the DEFF hotfix
<D3athrow> go for it
* vg-bot (~vg-bot@D3F905D9.DBFC011D.4F66FD71.IP) has joined
<vg-bot> [vgstation13] PJB3005 closed pull request #7948: DAMNIT DUNY (Bleeding-Edge...DAMNIT-DUNY) https://github.com/d3athrow/vgstation13/pull/7948
```

**Comment by 9600bauds** [comment]
It was an emagency

**Comment by Exxion** [comment]
> Implying Deff would have gotten voted in again before someone else merged it

**Comment by 9600bauds** [comment]
Next Map: Defficiency with 4% of winnings

**Pull request merged**
