### PR TITLE
Makes mugs fabricatable by the autolathe and the RSF.

### PR DESCRIPTION
**Pull request by Wizardcrying**
Replaces cardboard sheets with mugs on RSF.
Mugs are made with 750 iron instead of 750 glass in the autolathe.

Fullfills #6394.

### CODE REVIEW

**Comment by 9600bauds** [comment]
But... Why remove cardboard?

**Comment by Wizardcrying** [comment]
@9600bauds because then it would be like this
pls help

Edit: on second thought, I could add a lot more things to the RSF.

**Comment by Zth--** [comment]
Add more things to the RSF, don't remove cardboards

**Comment by Wizardcrying** [comment]
new thing

**Comment by Zth--** [comment]
:+1:

**Comment by ihadtoregisterforthis** [comment]
Crayons seem too much, given how much they cost on the biogenerator and merch console. Besides there's already many ways of getting them.
The camera doesn't fit with all the other "simple" items, but that's just like, my opinion man

**Comment by Wizardcrying** [comment]
What should replace the camera and crayon box? @ihadtoregisterforthis

**Comment by Zth--** [comment]
I'm okay with the camera. Is there any other way to build one? 
I agree with the other guy about crayons, there's already ways to obtain them

**Comment by Wizardcrying** [comment]
So, what should replace the crayons?

**Comment by Wizardcrying** [comment]
I'm not adding anything new here @PJB3005

**Comment by PJB3005** [comment]
Er you sort of are since you're adding stuff to the RSF? Fine I guess.

**Comment by unid15** [comment]
@Wizardcrying, maybe plastic knives

**Comment by Kurfursten** [comment]
Maybe wood? Cigars?

I do think it is content, though it doesn't really matter

**Comment by Wizardcrying** [comment]
aaaa I forgot to modify the rsf itseeeeelf

**Comment by Wizardcrying** [comment]
Ready for a merge unless anyone else has suggestions.

**Pull request merged**
