### PR TITLE
Re-adds obnoxiously long 2012 flashbang box description

### PR DESCRIPTION
**Pull request by ghost**
In all its shitty misspelled glory.
Some guy in the thread wanted this. I don't particularly care if it passes or not.

:cl:
 * rscadd: Re-added 2012 flashbang box description

### CODE REVIEW

**Comment by ghost** [comment]
I know you are @Exxion but what about the PR?

**Comment by Exxion** [comment]
Congratulations, that was the joke
Except it was towards you
Well played

**Comment by ghost** [comment]
adult

**Comment by Intigracy** [comment]
Hey, that's MY meme

**Comment by Exxion** [comment]
Sorry to break it to you, but I first made that joke a full seventeen days before you did, at least on the GitHub
Albeit more poorly

**Comment by Intigracy** [comment]
tbh op I'd merge this if you fixed the spelling

**Comment by FudgePucker** [comment]
Shit dude that really is a train wreck of a description.
:+1: I need memes to sustain me.

**Pull request merged**
