### PR TITLE
flash powder now works like a flashbang episode 2

### PR DESCRIPTION
**Pull request by SonixApache**
#22187 except the argument is flipped so it doesn't delete people on mixing
tested
~~in reality this probably needs some balance since you could make flashbangs with 1u of each reagent~~
now only for above 20u

- [x] **[UPDATE WIKI]**

🆑 
 - tweak: When mixed in quantities upwards of 20u, flash powder now functions exactly like flashbangs. Otherwise, it just flashes like normally.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I dislike this simply because it means I can't flash without banging anymore
I would be OK with it if the flash-without-bang happened at <20u instead of nothing, or if the bang was a different chemical reaction altogether

**Comment by SonixApache** [comment]
Give me good ideas for how one would mix flash and bang and I'll do it.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I elaborated two ideas here and in #22907

Maybe it flashflashes if under 20u and flashbangs if over 20u (by the way the OP changelog is misleading as it implies that's already what is happening when in reality aluminumpotassiumsulfur under 20u will just instantly vanish without a trace)

Maybe make bangbang aluminum potassium chlorine oxygen

**Comment by SonixApache** [comment]
done

**Pull request merged**
