### PR TITLE
Midround rulesets now have an initial delay of 30 minutes before they can fire

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Because apparently people don't like grues and pulse demons appearing 5 minutes into a round.
Mostly a requested PR.
Also contains code for delaying latejoin rulesets but is currently set to the normal delay.
Admins can toy with these variables. Negative numbers and 0 will cause the normal delay calculation to happen, while anything higher will set the starting cooldown to the new cooldown.

:cl:
 * tweak: Midround rulesets can no longer fire in the first 30 minutes of the game.

### CODE REVIEW

**Comment by toomykins** [comment]
MIDROUNDS WHEN
30 mins

**Comment by nervere** [comment]
Why not make it a different, configurable number per ruleset? If this is a grue / pulse demon problem, make it a 30 minute delay for them only.

**Comment by Servalfang** [comment]
30 minutes is far too much

**Comment by DamianX** [comment]
Hello @boy2mantwicethefam
Thank you for submitting your proposed changes to the vgstation13 project. It would appear that your pull request has bypassed some of the sections in our template, specifically the "Why it's good" part. This section is crucial for us to understand the impact and reasoning behind your changes. It helps maintainers and the community to quickly grasp the benefits and potential implications of the proposed modifications.

Could you please take a moment to update your pull request description to include this information? Providing a clear and detailed explanation will significantly aid in the review process, ensuring that everyone understands the value your changes bring to the project. Additionally, adhering to the template guidelines helps streamline the discussion and decision-making process for all contributors involved.

If you have any questions about how to fill out the template or why this information is necessary, feel free to ask. We're here to help guide you through the contribution process and make sure your efforts are recognized and understood by the community.

Looking forward to your update, and thank you for your contribution to vgstation13!

Best regards,

DamianX

**Comment by boy2mantwicethefam** [comment]
@nervere It's a general problem with midround antagonists on average, not just grues and pulse demons which were used as an example. A catbeast supposedly appeared within 5 or 6 minutes after the round started.
This does not affect latejoiner rulesets AKA the possibility of latejoiners becoming antagonists.
@Servalfang It was chosen under the idea of giving the crew a breather before Dynamic starts throwing more things at the station.

**Comment by SECBATON-GRIFFON** [comment]
this aint the way to do it
try tying the delay to the population

**Comment by Theophrastus1** [comment]
Just wanted to add that today we had a latejoin Grue that wiped the station at 12:07, and during a 3 traitor round later on, blob was called at 12:06. 30 minutes is a fine time.

**Comment by west3436** [comment]
Multiple traitor round followed by blob 5min later pushed this one over the edge. If you have a better solution, please PR it.

**Pull request merged**
