### PR TITLE
buff stoxin2 and make sleeper use it

### PR DESCRIPTION
**Pull request by 9percents**
why not
[tweak]

:cl:
 * tweak: Soporific Rejuvenant treats hallucinations now.
 * tweak: Sleeper now uses Soporific Rejuvenant instead of regular sleep toxin. It has same sedative function, but it also treats various disabilities, suffocation and hallucinations.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Forgot the buff in the changelog

**Comment by DamianX** [comment]
Kind of makes the upgrades to the sleeper a bit more useless (there are chemicals specifically to deal with deafness, dizziness and similar). Democracy was a mistake, I'm never merging this personally and leave it to someone else.

**Comment by 9percents** [comment]
stoxin2 doesn't really take over other chem's places, but okay, @DamianX 

P.S. Changelog was updated

**Comment by DamianX** [comment]
```
/datum/reagent/ethylredoxrazine/on_mob_life(var/mob/living/M)

	if(..())
		return 1

	M.dizziness = 0
	M.drowsyness = 0
	M.stuttering = 0
	M.confused = 0
```

**Comment by 9percents** [comment]
there is no ethylredoxrazine in the sleeper and stoxin2 comes with obligatory sleep to heal
same arguement can be said about regular chems(like bicard) inside that they devalue making chems for the fridge

**Comment by DamianX** [comment]
You are completely right and I was completely wrong.

**Pull request merged**
