### PR TITLE
Faster airlock prying and bolt cutting

### PR DESCRIPTION
**Pull request by CrazyAmphibian**
[tweak]
## What this does
POWERCREEP
* reduces the time it takes to chop airlock bolts from 30 (15) seconds to 20 (10) seconds
* reduces the time it takes to lift an airlock from its track from 10 (5) to 8 (4) seconds
* reduces the time it takes to pry an airlock from 10 (5) to 8 (4) seconds

for reference, deconstructing a basic wall takes around 14 seconds, and using thermite against a basic wall takes around 20 seconds between igniting and burning the wall, and a battering ram takes 6 seconds (25 if bolted) to open a door

## Why it's good
this allows the fire axe/halligan to be a viable means to open doors, and makes its time more in line with other forced entry methods

I timed it, and hacking a door open takes around 6 seconds for me (though this time could be lower if i practiced a bit beforehand). the additional time it takes, even if a few seconds can mean a huge difference when in-game. This change would keep the halligan as a worse alternative for opening doors, but less worse than before.

chopping door bolts takes a ridiculous amount of time for something that takes about a second of additional time to hack. forcing open a bolted door takes at minimum 50 seconds (in practice it's more around a minute), so this changes it to go down to 34 minimum.

## Changelog
:cl:
 * tweak: Chopping airlock bolts is now faster
 * tweak: prying open airlocks is now faster

### CODE REVIEW

**Comment by CrazyAmphibian** [comment]
man what the hell is with all of the previous commits, i'm on a different branch and discarded the commits

**Comment by SonixApache** [comment]
powercreep

**Comment by falcon2346** [comment]
> powercreep

It's powercreep of an item that is not printable, is not convenient to carry, is only available in atmos tech and the ce's locker, and is woefully outclassed at one of its two jobs by items atmos techs have easy access to. I'm pretty sure you could test every wire, get shocked, recover, then unbolt and open a door with a multitool in the 50 seconds it takes to do so with a fire axe and halligan. It probably takes less than 50 seconds to tear down an rwall.

This is the most unreasonably laughable claim of powecreep I've ever seen, especially since after the buff it's _still outclassed by every other option_ except maybe tearing down the neighboring reinforced wall by hand. Frankly if removing the wall is more viable than opening a door with a tool meant for that something has gone terribly wrong.

**Comment by CrazyAmphibian** [comment]
oh and by the way, cutting the door bolts doesn't prevent someone from re-enabling them right after (the feature is also just generally buggy and breaks if you wield the axe with both hands)
nor does prying a door open disable it from closing for any amount of time (and, in fact, it will auto-close after enough time)

**Pull request merged**
