### PR TITLE
Adds "minimum enemy requirement" option for rulesets and enables it for some rulesets.

### LINKED ISSUE #27630: threat issue
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
d6b20e81c042c99a38196b3c7d61206d420c609f

# Description
cult fired with no heads of staff, secuirty, or a chaplain
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by gurfan**
What it says on the tin. The rulesets changed by this PR are:

Cult: 2 enemies  (sec, captain)
Nukeops: 3 enemies  (sec, captain, silicons)

Partially fixes  #27630
0% tested
[tweak]

:cl:
 * tweak: Cult and Ops won't fire without any security anymore.

### CODE REVIEW

**Comment by DamianX** [comment]
Nuke ops without sec is pretty bad as well.

**Comment by gurfan** [comment]
> Nuke ops without sec is pretty bad as well.

Good point, I set required_enemies to 3 for nukeops.

**Comment by 9percents** [comment]
what about blob and civil war of casters?

**Comment by Kurfursten** [comment]
Truly we are going in circles. It has been 4 months since #26125

How many months 'til it gets removed again?

**Comment by gurfan** [comment]
I don't think blob is really a sec-reliant mode since everyone on the station has to get their shit together and fight it, and while wizwar is mess I don't think it's "as" undeniably focused on sec vs antags as the cult/ops. I wanted to touch as little modes as possible in this PR but if everyone wants enemy requirements on those then I can add them.

**Comment by 9percents** [comment]
we live in an endless loop

**Comment by gurfan** [comment]
It is sort of a partial revert of #26125, but only for two rulesets (currently).

**Comment by gurfan** [comment]
- Adjusted required_enemies to allow varying enemy requirements based on threat level (like originally). Required enemies remains the same for now.

**Comment by GreatBigFailure** [comment]
I don't like the nuke ops one. It's too meta. The only reason to even touch the disk is because of nuke ops so if there's no captain it'll just get left there. It'll make other head's job easier but maybe not in a good way. maybe make it cap, HoP, or HoS. That way it won't fire if the disk's only hope is a spare rusher but HoP/HoS won't ignore it if there's no cap.

**Pull request merged**
