### PR TITLE
MoMMIs can no longer be blobs

### PR DESCRIPTION
**Pull request by Kharkov72**
ebin
[hotfix]

:cl:
 * bugfix: MoMMIs can't be blobs anymore.

### CODE REVIEW

**Comment by tuypo1** [comment]
Momis as a source of blob sounds cool though

**Comment by Kharkov72** [comment]
if it was fleshed out like they had their own sprite sure, but Mommi Blobs don't actually pop so blob rounds which usually have two blobs have just one

**Comment by tuypo1** [comment]
Oh yeah blobs not popping when they should would be a problem

**Comment by utilitas-** [comment]
But they do have their own sprite. Silicon blob seeds should automatically pick the antimatter blob sprite when they pop. Fix them not popping properly and it'll be golden.

**Pull request merged**
