### PR TITLE
Sliding stun talismans into books to stun the next person who reads

### PR DESCRIPTION
**Pull request by RFultra**
:cl:
 * rscadd: Adds the ability to slide stun talismans into books which stun the next person who reads said book

### CODE REVIEW

**Comment by Knightkiller11** [comment]
While I like the idea of this, it does have a few issues so far:

1. This ignores one of the downsides of a talisman (and cult magic in general), namely that you have to shout an incantation to use it, like a spellcard from touhou, which makes it very obvious what just happened to nearby people. This makes it silent and sort of clashes with the established usage method.
2. How does the person reading it trigger the talisman? They can't actually use talismans if they find them, nor can they understand the runes on it to speak the incantation.
3. There appears to be no way to safely remove a talisman from a book after you've slid one in either.
4. There is no way to tell if a book has a talisman in it at all, until its read. Effectively giving a foolproof way to hide a talisman until its too late, maybe give some way to identify a trapped book.

Ideas:
- Perhaps make the person trapping the book incant the talisman, then place it between then page, essentially "priming" it and making it impossible to effectively remove without it discharging?
- Could other talismans have interactions like this? Perhaps have a teleportation talisman or a blood boil talisman could work with this method. As broken as that does potentially seem, I think if handled right it could add a fair bit more depth to talisman usage.
- Finally should this be able to affect someone with a null rod? Not sure if it protects from the effects of talismans and runes ordinarily and I don't see a check to test that either.

**Comment by Exxion** [comment]
Copypaste is bad
Either change `runestun()` so that it doesn't assume someone used the talisman on someone else, or move the actual stunning to a separate proc and make both `runestun()` and this call that

**Comment by strawberrytan** [comment]
Stun talismans don't work if you have a null rod in your inventory normally

What if holy water had an effect on cursed books?

**Comment by Knightkiller11** [comment]
I guess holy water would purify or burn any cursed books it would come into contact with, though the only real "cursed" books at the moment would be the Arcane Tome and probably Woody's got Wood.

Though I imagine it wouldn't do anything directly to talisman-trapped books themselves, as the book isn't cursed so much as the talisman itself is. And considering that holy water does absolutely nothing to either Talismans or Tomes at the moment I can't see why it would have any effect on books with talismans inside except make the pages soggy

**Comment by strawberrytan** [comment]
It's less about what makes sense physically and more about coming up with a noncultist method of handling known contraband

I am also okay with giving the chaplain a reason to do book burnings

**Comment by Ratvar** [comment]
Slide books into stun talismans to force people to read when you stun them

**Comment by N3X15** [comment]
Added [Balance] because this adds a new method of stunning.

**Comment by Shadowmech88** [comment]
In the same vein as this, I think it'd be neat to add new talismans which have effects specifically based around sticking the talisman to something and applying the effect to that object.
Like, you could make talismans that could bolt doors shut on application, or apply enchantments to objects for increased damage.

**Comment by DeityLink** [comment]
@Knightkiller11 's points are spot on.

That's why I also gave up "thrown talismans" after considering them for the ongoing cult rewrite. It's fun when you first get the idea, but it adds whole layers of balance issues.

I'm keeping the concept of remotely activated talismans in mind however. I think it should still require a cultist to trigger it with an incantation (unless they're a mime or have the discrete casting perk)

**Comment by DeityLink** [comment]
Wait what

**Pull request merged**
