### PR TITLE
Adds the icemachine to Packed's Kitchen

### LINKED ISSUE #17952: Packed Station doesn't have a cream machine
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
491b28e99152f490029981dd8936c2398e4834d7

# Description
packed station doesn't have a cream machine, the machine that makes ice cream. it should because every other station has it

### PR DESCRIPTION
**Pull request by MiniMeatwad**
before: dreammaker_2018-03-28_08-00-19
after: dreammaker_2018-03-28_09-23-43

first pull request, please lecture me if i did something wrong.

moves the light fixture floating in the freezer onto the wall.
moves the beer keg from the freezer to where pun pun was orginially.
moves pun pun to the left of the beer keg.
moves the fridge to where the beer keg was orginially.
adds the snack machine where the fridge was originally.
adds the cream master deluxe to the kitchen.

Closes #17952

🆑 

 * rsadd: Added SnackBar Machine and the Cream-Master Deluxe to the Packed Station kitchen.

### CODE REVIEW

**Comment by Irradiation** [comment]
Looks alright to me. Just remember to add at the bottom of your PR description so we can get a sweet changelog.
:CL:
 *rsadd: ADDED THINGYMAJIGS

**Comment by Aurx** [comment]
That changelog is needlessly descriptive and doesn't say what map it's for.

**Comment by Pathid** [comment]
Put Closes #17952 in the description so it auto-closes when this is merged.

**Comment by Probe1** [comment]
You wrote :CL: when it should be underscore.  You wrote *rscadd: instead of SPACE * SPACE rscadd: .  I tweaked it for you.

I'll look at the mapping changes.

**Comment by Probe1** [comment]
Make sure to include ALL the changes you make in your PR.  When I see "Adds ice cream maker" then find you moved the beer keg around it makes me ask "What else did he do without mentioning?".  Every change doesn't have to go into the changelog but it does have to be mentioned in the PR.

**Review by Probe1 — APPROVED** [review]

**Comment by MiniMeatwad** [comment]
i just did what people told me to do

**Pull request merged**
