### PR TITLE
Removes memes.

### PR DESCRIPTION
**Pull request by PJB3005**
This is the only way to guarantee  no memes.

### CODE REVIEW

**Comment by carshalash** [comment]
I created a monster yesterday. I looked into the abyss, and it looked back at me.

**Comment by 9600bauds** [comment]
Make it compile and I'll merge it

**Comment by Boxe** [comment]
merge when?

**Comment by kol1th** [comment]
free us from this nightmare

**Comment by Imagebard** [comment]
>1 dumbass could accidentally merge this and crash the server

A

**Comment by carshalash** [comment]
Baud don't you fucking dare.

**Comment by clusterfack** [comment]
Hope nobody's finger slips

**Comment by Shadowmech88** [comment]
Hey as long as it has more likes than dislikes, why should a collaborator look any deeper into the matter or consider the implications of merging it?

**Comment by clusterfack** [comment]
The man makes a solid point

**Comment by kol1th** [comment]
ill give u all my pomf coins if you merge it

**Comment by clusterfack** [comment]
WOW RIRICHIYO WAY TO FLAUNT THE PEOPLE'S VOTES

**Comment by xpcybic** [comment]
DO IT
JUST
DO IT

**Comment by PJB3005** [comment]
Muahhaa

**Comment by Shadowmech88** [comment]
MAKE
YOUR MEMES
COME TRUE

**Comment by kol1th** [comment]
M E R G E 
E
R
G
E

**Comment by Exxion** [comment]
Wait hold on
The diff is way too big to view
But what are the ten added lines?

**Comment by PJB3005** [comment]
@Exxion commenting out things in the Travis file and replacing the build script with `true`

**Comment by Imagebard** [comment]
>Conflicts

0 out of 10 meme points.

**Comment by Exxion** [comment]
This changes the entire codebase
It would be impossible for it not to conflict with any other change whatsoever

**Comment by PJB3005** [comment]
Removing memes is a very hard task.

**Comment by gbasood** [comment]
let the memes die

**Comment by PJB3005** [comment]
We should reopen this.

**Comment by SweptWasTaken** [comment]
Reopen this.

**Comment by PJB3005** [comment]
Shut the fuck up swept.

**Pull request closed without merging**
