### PR TITLE
addresses bagel engineering complaints

### PR DESCRIPTION
**Pull request by SonixApache**
This hopefully addresses most of the 'hour-of-power' people have with bagel.
Also powers the one grille in the SMES room that wasn't powered before, but I doubt anyone ever knew or cared.
Briefly tested.

🆑 
 - wip: These are all for Bagelstation.
 - tweak: Aux engineering now uses yellow cables
 - tweak: Aux engineering and engineering are now connected
 - tweak: Aux engineering porta-SMES power connectors are now wired to the grid
 - tweak: Aux engineering SMES now powers engineering, rather than the grid
 - tweak: Increased roundstart SMES charge from 40000 to 90000 per SMES (18%)

### CODE REVIEW

**Comment by Kurfursten** [comment]
Prepare to receive your map conflicts because #19359 is still unmerged

**Comment by SonixApache** [comment]
i'm going to explode

**Comment by SonixApache** [comment]
image
💣

**Comment by Inorien** [comment]
the PR that saved ~~/vg/~~ bagel

**Comment by Pathid** [comment]
Breaker boxes when?

**Pull request merged**
