### PR TITLE
Replaces a Barsign Sprite 

### PR DESCRIPTION
**Pull request by beesil**
[sprites] 

image

:cl:
 * imageadd: Replaces the Cindi Kate's barsign.

### CODE REVIEW

**Comment by jknpj** [comment]
why not both

**Comment by beesil** [comment]
@jknpj the old one is rather generic and I don't think I've ever seen it used. I could leave it in barsigns.dmi as cindikateold, if you'd like. 

image

**Comment by Intigracy** [comment]
idk what's up with the dwarf

**Comment by Exxion** [comment]
There are a bunch of bar signs with just the dwarf and text
It's basically the default design for when someone comes up with text but no image

**Comment by Intigracy** [comment]
Feel free to update even more of the generic sprites if you'd like.

**Comment by beesil** [comment]
That's the plan!

**Pull request merged**
