### PR TITLE
Fro-bot

### PR DESCRIPTION
**Pull request by gurfan**
Brobot's long lost cousin. 
frobot
Available to cyborgs using the service module.
[sprites]

:cl:
 * imageadd: Service cyborgs now have a groovy new design to choose.

### CODE REVIEW

**Comment by gurfan** [comment]
The left/right states are fucked and need some tweaking

**Comment by Eneocho** [comment]
Maybe they should come with the HUEY upgrade as well for that dank weed.

**Comment by SonixApache** [comment]
this is a port, right? you sure the licence allows it?

**Comment by ghost** [comment]
> 
> 
> this is a port, right? you sure the licence allows it?

Almost all spess sprites are CC-BY-NC as long as they're not a port from a closed-source repo. If it is a port then gurfan needs to credit the creator, or at least the codebase if the creator can't be pinpointed.

**Comment by Kurfursten** [comment]
>add sprites
>compression causes a negative icon file diff

Help me Lovecraft's cat I'm going INSANE

**Pull request merged**
