### PR TITLE
Deathsquad changes

### LINKED ISSUE #27000: Suggestion: Only deathsquad leader should have a mecha
There are never any old-fashioned deathsquads because all of them go into meme mechs with a gorillion health and damage, only the deathsquad leader should have a mecha because he is the leader

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
deathsquad zone
(this is the first time I mapped something this significant please tell me if something is bad)

- Locked mechas behind a blast door that is closed by default, except for the Seraph which is accessible to the Commander and available in the shuttle.

The deathsquad had a lot of personality and fun sucked out of it by the rampant use of mechas. With the locking of mechas behind a blast door that can only be opened by an admin (and a bunch of impenetrable windows) it should allow deathsquaddies to get up close and personal with their prey.

- Added 1 more Marauder, 4 Murderysseus and 4 Death Ripleys. For variety.
- Added a snazzy couch around the holomap, moved decal closer to deathsquad spawns.
- Stealthily replaced the breakable window grilles with invulnerable grilles. No you cannot use the portal gun on Z2.

So what does the deathsquad get to make up for the initial loss of the mechas?
- Deathsquad thermals now also confer x-ray vision, the ability to see in the dark to a degree and protect against flashes. They also cannot be EMP'd to blind the deathsquaddie, because this was a sort of glaring vulnerability that most people, not even the deathsquad, knew about.

And a few miscellaneous changes:
- Deathsquad members will automatically talk into the deathsquad frequency rather than Commons.
- Replaced the deathsquad SWAT masks with HECU masks that can be used indefinitely.
- Fixed a typo where Commando and Commander were swapped. Commander is the leader.
- Added a new possible leader name.

Closes #27000

:cl:
 * tweak: The Nanotrasen Deathsquad no longer has access to mechas by default, but the Commander still gets the Seraph which is now available in the shuttle.
 * rscadd: The Deathsquad mecha bay now has 8 more mecha with more variety.
 * tweak: Changed the Deathsquad lounge a little.
 * rscadd: The thermal glasses worn by the Deathsquad have been significantly improved, and provide protection against flashes, is immune to EMPs and can see through walls.
 * rscadd: Deathsquad commandos now spawn with improved HECU masks.
 * spellcheck: Fixed a typo where Death Commandos were called Death Commanders and vice versa.
 * rscadd: Added a new possible Deathsquad Leader name.
 * tweak: Deathsquad members will now automatically talk in their radio rather than the Common channel.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
The map changes are just the same area over the majority of the maps except dorfstation, all done via StrongDMM.

**Comment by gurfan** [comment]
>Deathsquad magboots are now lube-proof (this is not soulless!)

This is soulless!

**Comment by bathosbathtime** [comment]
Please do not make them lube immune.

**Comment by Eneocho** [comment]
Remove the lube immunity and we have a deal. That's a dealbreaker.

**Comment by jwhitak** [comment]
This is definitely a case of "put in a glaring flaw so that the manager can suggest their change and then be happy with it" with the deathsquid lube. Dear lord the soul it is leaving my body.

**Comment by pedr69** [comment]
disagree with the lube and EMP pulselasers

**Comment by dinnerwoerror** [comment]
can we just get all this stuff without any of the unbreakable walls

**Comment by tinysaturn** [comment]
I hate this whole idea of locking shit behind a blast door, if the players want to use a Marauder, let them. More choices is always better and leave it to the players to decide on what they want to do.
And more importantly, did you actually fix the fucking Death Ripley? That mech's gimmick module is completely broken and does nothing aside from pushing a mob one tile forward.

**Comment by boy2mantwicethefam** [comment]
- Removed immunity to lube
- Removed pulse laser EMP

**Comment by boy2mantwicethefam** [comment]
@tinysaturn Mechs removed a lot of the fun of actually fighting a deathsquad and they have the same lube immunity that people wanted removed from the magboots. That's why it should be up to the admin whether to allow the "fun allowed" deathsquad or the "no fun allowed" mechsquad.
I've looked at the KILL CLAMP and remembered something said about them years ago that they might be a joke mech. Damn. Not sure whether to replace the Death Ripleys and what with.

**Comment by SonixApache** [comment]
As far as I can remember, THE CLAMP has always been a joke or possibly an ancient WIP.

The blast door is a good idea; if there's admemes around to summon a squid, there's also admemes around to open the blast door.

**Comment by dinnerwoerror** [comment]
yea but when you give normal infantry squaddies this much improvement they're pretty much equivalent in power level to mech deathsquaddies so it'd be up to player choice anyways

**Comment by boy2mantwicethefam** [comment]
Mech deathsquaddies are outright immune to damage until the mech gets destroyed, unstunnable too, Marauders get access to rechargeable rockets that leave a big hole in the station that people can get sucked into without the use of magboots. Where's the fun in that?

**Comment by Eneocho** [comment]
Bro just circle around the mech and toolbox. I've seen weapon-less clownmasters outrobust full teams of squids. Having the blast door is a terrible idea.
You could let the squid choose the mech OR weaponry via a one use button that defaults on weapons, so you could go murdermachine but be a sitting duck when the mech dies or go murderhobo but don't have the guaranteed armor of the mech. Going both mech and hobo would require another squid not getting their weapons or mech. 
Something like this (with a dispensing machine to select mech type if you wanna be fancy, like the hardsuit dispensers for ERTs):

**Comment by tinysaturn** [comment]
Wait I just realised something
Why are you we talking about balancing a "go wild and destroy (what's left of) the round" admin button

**Comment by Eneocho** [comment]
> Wait I just realised something Why are you we talking about balancing a "go wild and destroy (what's left of) the round" admin button

Because barry is insisting on 'balancing' it.

**Comment by Eneocho** [comment]
Add some of the new squaddie goodies to the old vendortron.

**Comment by boy2mantwicethefam** [comment]
It's not about the balance, it's about making things more fun. Mechsquad is boring, deathsquad is exciting.

**Comment by Eneocho** [comment]
> It's not about the balance, it's about making things more fun. Mechsquad is boring, deathsquad is exciting.

Again, as simple as letting the squid choose between having the funny guns or the funny mech but not both like pic related:

**Comment by tinysaturn** [comment]
> It's not about the balance, it's about making things more fun. Mechsquad is boring, deathsquad is exciting.

You see, that's the problem here. I think smashing crew into fine paste in a combat mech to be very entertaining and funny, which is why I think you should just let people choose what they want to do. You know, kind of like how a nukie decides to go in with an esword and melee people to death instead of picking the superior ballistic gear

**Comment by boy2mantwicethefam** [comment]
@Eneocho But the funny meme guns are still available for free and don't really do anything bad. Plus mechs are available if the admin wants it.
@tinysaturn But it's not very fun for the crew to be smashed into a fine paste via something that's considered by most players to be extremely strong with almost no real way to fight back than EMPs (mechs), without that at least the crew has an opportunity to fight back, however small it may be, and that's overall more fun.

> You know, kind of like how a nukie decides to go in with an esword and melee people to death instead of picking the superior ballistic gear

How many times have you seen that?

**Comment by dinnerwoerror** [comment]
> > You know, kind of like how a nukie decides to go in with an esword and melee people to death instead of picking the superior ballistic gear
> 
> How many times have you seen that?

are you kidding me? there's ALWAYS that one melee/pistol/unconventional weapons guy on the airsoft team

image

**Comment by Eneocho** [comment]
> But the funny meme guns are still available for free and don't really do anything bad. Plus mechs are available if the admin wants it.

I put the meme gun boxes there for a visual representation. The idea i'm suggesting is to remove the guns from the deathsquaddie's spawn inventory and lock it behind a door. You have a single-use voucher that you can redeem on the mech door or the weapons door, so you can get the mech OR the guns, but not both.

**Comment by boy2mantwicethefam** [comment]
@dinnerwoerror Not when I play nukies, the gimmick always comes from a plan and everyone takes up guns.
@Eneocho But then deathsquaddies would just use it for the mech every time...

**Comment by Eneocho** [comment]
> @Eneocho But then nukies would just use it for the mech every time...

I wouldn't be so sure about that, since a mechless squid would be completely defenseless in this scenario. You're gambling your survival after the mech gets busted in exchange for superior firepower. 
Also >nukie

**Comment by boy2mantwicethefam** [comment]
Sorry, looked at the whole nukie thing earlier

**Comment by Hinaichigo** [comment]
I don't like the seeing through walls thing.

**Comment by Eneocho** [comment]
> I don't like the seeing through walls thing.

It makes sense in-universe as they've been sent to massacre everyone with no survivors. Not sure it makes sense gameplaywise. Kinda weird to limit the mechs cause they have the rocket launchers and stuff when the mechless squid pulse gun can also melt walls (and EMP if this gets merged) and they get xray glasses. Seems kinda illogical to block mechs on the "too easy to breach" point when the other non-blocked tools have similar capabilities (Just fire the destroy pulse in a straight line and you can breach as if a rod had passed through).

**Comment by dinnerwoerror** [comment]
do you just not like mechs barry

i also don't like mechs but that's no reason to take out your anger on the squiddies

**Comment by boy2mantwicethefam** [comment]
> and EMP if this gets merged

You should read the PR again because I updated it yesterday.
@Hinaichigo I felt that the deathsquad needed some better goodies to make them intimidating and fun, and giving what amounts to an elite black-ops squad meant to kill everyone the ability to track their targets better beyond mostly normal thermals (which they already have) would be an improvement.

@dinnerwoerror I don't like mecha deathsquads being the default, it sucked all the fun out of actual deathsquads fighting crew and what threat they have to face, there's no excitement in seeing a deathsquad roll over a station anymore. People were so quick to call the PR soulless and downvote it for giving the magboots immunity to lube that they did not think about how the mecha deathsquad is immune to it.

**Comment by pedr69** [comment]
now that i slept on it i'm wondering if removing the squaddies from the common channel is bad
since it results in almost guaranteed silent depopulation, instead of 3 minutes of OHSHITOHFUCK after you hear rescue leader creed on common(and then being killed in 2 shots)
and i'm also wondering why the station doesnt go delta once the station nuke is armed on blob rounds(or in general)

**Comment by boy2mantwicethefam** [comment]
I will change it back to Common default.

**Comment by boy2mantwicethefam** [comment]
Too divisive, serves me right for putting a good amount of effort into a PR.

**Comment by Eneocho** [comment]
Bro, just make the 'squid mechs require admin intervention' thing a separate PR and see how literally everyone agrees to the gameplay changes.

**Pull request closed without merging**
