### PR TITLE
Packed fixes

### LINKED ISSUE #17322: Packed botany windoors dont have access requirements.
#### Description of issue
Those windoors really should have access requirements, they do on all other maps.

#### Difference between expected and actual behavior
Walk to botany to wave at the beekeeper
Bump into the windoor instead releasing the bees.

### PR DESCRIPTION
**Pull request by Pathid**
Closes #17322

Split from #17350

:cl:
* bugfix: Packedstation hydroponics windoors require hydroponics access now instead of no access.
* bugfix: Packedstation service access requirements altered a bit to accommodate minimal access mode. (In case that's ever enabled.)
* rscadd: Divided Packed's Central Primary hall area a bit. There are now fore and aft primary hallway areas.
* rscadd: The Packed Engineering break room/lobby has been split off into its own area.
* rscadd: Added some air alarms and fire alarms to Packed.
* rscadd: Added a bag of sugar to the kitchen coldroom on Packed.

### CODE REVIEW

**Comment by Kurfursten** [comment]
If you are doing service this seems like a good time to add a kitchen area

#17219

**Comment by Dacendeth** [comment]
mechanics room doesn't have a light switch if you think that matters.

**Comment by Probe1** [comment]
I don't know packed from memory so I can't tell about the redesigns but I did test and confirm there's no problems.

**Comment by DamianX** [comment]
Waiting for a fix for an air alarm in the brig that was placed under a full window

**Comment by Kurfursten** [comment]
merge this

**Comment by Pathid** [comment]
Hold on, fixing now.

**Pull request merged**
