### PR TITLE
Snowmap (feat. Taxi)

### PR DESCRIPTION
**Pull request by plosky1**
SnowMap. The latest gimmick map is here.

This is the initial pull request. It'll likely need changes based on heavy play-testing.

Features: 
(Almost) completely enclosed snow asteroid.
Snow is breathable but cold so you'll need to use the winter jackets that are everywhere.
Uses Taxi as a base that's been modified by Celt, and then further by me.
Just look at the picture bro.

Thanks to: DrCelt, Burneddi, PJB, Veers, Kurfurst, Kharkov, and more I'm sure I'm forgetting about for helping me get this put together.

https://i.imgur.com/piMOqf2.jpg for up-to-date render. (not up-to-date)

ALSO BUNDLED:

Blizzard event by @GlassEclipse. Very nice, very atmospheric.

[snowmap]

:cl:
 * rscadd: Snowmap v0.1 is here to test and die on!

### CODE REVIEW

**Comment by Kurfursten** [comment]
>no taxis between snowbases

**Comment by plosky1** [comment]
This aint your mommas taxi. You gotta walk and brave the cold.

**Comment by Blithering** [comment]
Snowmobiles!

**Comment by plosky1** [comment]
Snowmobiles need their own PR to make it a child of janicarts instead of wizmobile, but once it's done I'll definitely add them in.

**Comment by Kurfursten** [comment]
In seriousness though, it seems a bit memey to put a Celtic Crown for free in snowmaint. Those wolves will all kill each other after the 10 minute mark and they start to starve, no deer around to support their hunger. Then you have 5 yetis pre-funneled for any deathtrap you set up, or just unloading an egun.

**Comment by plosky1** [comment]
Good call, I’ll rework that area real quick. Had no idea the wolves would eat each other.

**Comment by Blithering** [comment]
Deer or wolf migrations to replace the equivalent carp migration event would be neat, maybe snowstorms too.

**Comment by ShiftyRail** [comment]
Should add redundant power & atmos lines. Maybe also snow shelters/sheds in the forest in the event of a snow storm.

**Comment by SkowronX** [comment]
Needs wendigo

**Comment by plosky1** [comment]
Added redundant power & atmos line, and two snow shelters in the forested areas.

Also there are yeti wendigos 😏

**Comment by ComradeDispenser** [comment]
Make Snowmobiles so you can attach cargo carts to them for speedy delivery of crates and being able to transport wounded to medbay

**Comment by robosperg** [comment]
remove signs that say space for muh immulusions

**Comment by brndd** [comment]
I can't believe this is happening

**Comment by Blithering** [comment]
>wolves deprived of a food source will resort to cannibalism

Dare I say... wolf wendigoes?

**Comment by AI-Is-Rogue** [comment]
The time has come, this is the moment I've been waiting all these years for.

**Comment by SkowronX** [comment]
snowstation

Wish you were here.

**Comment by Lokiamis** [comment]
I've been waiting for this

**Comment by veles2001** [comment]
looks comfy as fuark, are the heaters in maint actually going to be useful now?

**Comment by jknpj** [comment]
if you don't make xmas lights actually make light i'll hunt you down

**Comment by plosky1** [comment]
> if you don't make xmas lights actually make light i'll hunt you down

This must be done by a sneaky c*der, my skillset is limited to only pushing out meme maps.

**Comment by Kurfursten** [comment]
* Why is there an atmos door that just leads straight out to space below toxins storage
* There is a tree blocking the entrance to the bottom left cabin
* Hatchets need to be more accessible I think, like winter coats.
* Random status display to left of AI core?
* Tell us more about all those shuttle destinations in the field of snow. I want to know what each is for.
* Did you remember to set base info for all pods and emergency shuttle dock too? Mining shuttle? Research shuttle? Trader shuttle?
* Where do traders dock? Where's the trader base? Taxi predates traders (though not by much)
* Syndicate mothership seems like it might dock too close to the solars.
* Since engineering storage has TEG parts, it should come with an ethanol tank in case anyone wants to lube the engine.
* You did away with mobile SMES, my favorite part of Taxi, and this makes me sad :(
* Cargo shuttle docks pretty dangerously close to path. Warning stripes? Docking lights? Something.
* Probably needs more access to heaters in general near airlocks, cold is gonna get in
* Chutes seem to have been made irrelevant in old disposals room (topleft) of MedSci station
* Floating air alarm in eng station "checkpoint" at base of MedSci
* Floating APC in medbay "checkpoint" on cargoeng
* Final disposals on cargoeng: putting disposal pipes LONGWAYS under r-walls is bad!
* A lot of your external airlocks have no catwalks outside of them, which means you should expect to get blown away constantly.
* You deleted EVA entirely in favor of a wintercoat room, but people might still need suits.
* It's not too late to give paramedics telescience like on roid and deff instead of leaving it directly next to the bomb room.
* One lesson we learned from Taxi is that the tiny xenobio chambers are suffering. Especially that 2x2 one where you can't access one tile at all due to the chute.
* AI APC too unsecure. You can walk in around back, deconstruct two walls, walk up to the APC (now safe from the blocked turrets) and casually kill the AI before turrets even open. Your choice of scooting in a welding tank or unlocking the APC. Hell, even just cutting every wire so that it shorts would be fine.

I feel like a lot of the magic and charm of Taxi (from an Engineer main's perspective) has been lost by mapping all of the piping and power systems together. No project to lay wires between the stations for bored engineers, no portable SMES shuffle, no added bonus of starting with 6 SMES for mega power storage, no comfy little miniAtmos to chill in on MedSci.

My thoughts, for now.

**Comment by plosky1** [comment]
The EVA room has space suits and typical EVA stuff in it, or ar least it should unless it did some weird rollback. As for the rest, I’ll fix it in a bit. I personally liked the multiple station SMES and missing piping/wiring but theres a lot of dissent regarding having the stations independent of each other.

Although its theoretically possible since each station has at least one solars connected to it.

**Comment by Blithering** [comment]
wave

**Comment by plosky1** [comment]
Added hatchet locker to each entrance.
Shuttle destinations in snow are for Vox, Salvage Shuttle, ERT, and nuke ops. They also have options in space.
Traders have their own docking port in the snow, and their base is on z-level 6.
Ethanol tank and TEG room added.
Mobile SMES re-added.
Heaters added near entrances.
Chutes in MedSci have been made irrelevant, but I left them there as part of the station history.
Catwalks added.
I re-checked EVA, and it has the suits and other EVA things I put in there earlier so it may be a map rendering issue if you're not seeing it.
I prefer science having teleporter over paramed, but I'm sure someone will change it down the line.
Fixed xenobio chambers.
Added more walls and open space for lasers to work on AI chamber. This will be particularly difficult to fix though considering it's all walkable snow around the outside and not space.

As for the piping and power systems interconnected, for now I'm going to leave it as I've done it, but depending on how our players do I may remove it in favor of disconnected power/piping.

**Comment by ComradeDispenser** [comment]
Do the Vox connect to the station in any way or are we free to build our own wooden trader hut out in the snow and have the shuttle dock directly with our comfy cabin?

**Comment by plosky1** [comment]
> Do the Vox connect to the station in any way or are we free to build our own wooden trader hut out in the snow and have the shuttle dock directly with our comfy cabin?

Based off current Vox shuttle landing spots on the snow itself, yes you can build a cabin. None are directly connected to the station.

**Comment by plosky1** [comment]
Vox unfortunately cannot land on station now due to snow tiles and destroy_everything being set to 0 for the Vox ship. I had to move several ship docking ports offstation because of this, and until I figure out how to set their destroy_everything var to 1 it will stay this way.

From my understanding of the code this var is set in the shuttle code itself and can't be changed on a map-to-map basis.

**Comment by Durgen** [comment]
this is an excuse for pomf to finally fix the test server

**Comment by Durgen** [comment]
also bring back ling and force it on this map every round

https://www.youtube.com/watch?v=oa3WTj_vuvc

**Comment by RaccoonBro** [comment]
The cargo shuttle spot could really use a border of some sort, seems like it'd be easy to accidentally walk into the path when it comes.

**Comment by plosky1** [comment]
That's already been fixed, the pic isn't up to date. Right now I'm doing one more minor fix, then I'm waiting on @GlassEclipse blizzard event, and it should be ready to merge for testing.

**Comment by Durgen** [comment]
It would be cool to have fourth substation that’s derelict, de-powered and cold, for intrepid assistants to venture into the snow and explore

If there is one thing wrong with taxi, it’s not enough maint

**Comment by ComradeDispenser** [comment]
How many final commits are you going to have, Plosk?

**Comment by plosky1** [comment]
Uhhhhhhh.

This should be it for realsies, I promise, until the blizzard PR is added and I need to fix the .dm.

**Comment by Durgen** [comment]
if only the test server was working

**Comment by Kammerjunk** [comment]
probably have to either commit something or reboot Travis
either way, 1be56df compiled without errors on my machine, where I pulled upstream/Bleeding-Edge, fetched plosky's snowtaxi branch, and merged FETCH_HEAD onto a new branch. tested it like that because the branch is 33 commits behind upstream/Bleeding-Edge
haven't tried the newer commits but I don't see any reason they should fail CI

**Comment by plosky1** [comment]
Ayy, ready for merge and testing.

**Pull request merged**
