### PR TITLE
[box] Expanded maint, new thing in space and goonecode containment

### PR DESCRIPTION
**Pull request by CptWad**
Lets see if I did this right

### CODE REVIEW

**Comment by gbasood** [comment]
pictures

**Comment by CptWad** [comment]
Okay this sends this straight to the main branch ok well shit

**Comment by CptWad** [comment]
roid
heres the thing in space, lemme figure the rest of it

**Comment by CptWad** [comment]
hold up its not done please ignore this

**Comment by DrCelt** [comment]
I imagine someone comfily sailing the stars

**Comment by CptWad** [comment]
I forgot to add areas for the maint shit hold on
Also none of this is tested give me like another hour

**Comment by 9600bauds** [comment]
???

**Pull request closed without merging**
