### PR TITLE
Tweaks luck-related values for slots and lotto tickets 

### LINKED ISSUE #32692: Clovers on lotto tickets got nerfed to the ground.
#### Description of issue
The effect of luck on lotto tickets got nerfed so hard that there's no point in farming clovers for luck. 
I tried scratching tickets with three seven leaf clovers and twenty-ish six leaf clovers, the most I won were 200 credits from a phazon ticket. The total winnings from the tickets were under 2500. About the same luck and profit margins of playing on supermatter tickets. There's no point in making the tickets affected by luck when having 50000 luckiness stat barely affect the tickets. 
I then tried the slot machines and got considerably more money, around 60K.
#### Difference between expected and actual behavior
Expected sizeable profits comparable to the effort of farming high level clover.
Got piss level profits.
#### Steps to reproduce
Get 5 seven leaf clovers (to equal the 3x10000 and 20x1000).
Scratch tickets. Get only 40-200 credits.

@Hinaichigo, you overcompensated.

### PR DESCRIPTION
**Pull request by Hinaichigo**
[tweak][bugfix]
After considering the feedback, I tweaked the influence of luck on slot machines and lotto tickets.
1. Slot machines are less influenced by luck; the expected number of wheel jostles per luck has more of a bias towards lower values.
2. Recalibrated scratchcard parameters so that the base impact of luck is somewhat higher, and raised the luck ceiling so that extremely lucky players won't hit as abrupt of a performance wall. I calibrated it as follows:
- The base "EV" of a Phazon Fortune is 45.5 credits. I don't think it exactly corresponds to the true "expected value" of a play (since once you win a given prize you don't keep rolling on the lower prizes), but it serves as a decent surrogate for our purposes.
- Originally, having a 7-leaf clover in your pocket would raise this to ~1.7 million credits, or essentially winning the jackpot every time.
- Post-nerf (currently), the EV with a 7-leaf is ~130 credits. However, due to the way it was nerfed, having 10 7-leaves only increases this further to ~136 credits, which is essentially the ceiling.
- This PR makes it so the EV with 1 7-leaf is ~230 credits (with getting the jackpot being around 5 or 6 times as likely as usual) and raises the luck ceiling such that the the jackpot probability plateaus at around 1/1000 beyond that.

I think it's nicer to have a wider range AKA having the luck ceiling higher, but not so high that it gives massive payouts too often.

Also fixes a bug where luck wasn't coming into play with Supermatter Surprise tickets. 

Fixes #32692

:cl:
 * tweak: Lowered influence of luck on slot machines.
 * tweak: Tweaked influence of luck on scratchcards to hopefully give more satisfying results.
 * bugfix: Luck influences Supermatter Surprise scratchcards properly.

### CODE REVIEW

**Comment by Eneocho** [comment]
I'd push the lotto EV a bit further up. Getting a single 7leaf is hard enough.

**Comment by Hinaichigo** [comment]
Done.

**Comment by Eneocho** [comment]
Is there a realistic chance to get the million credits when stacking luck? Because baseline odds are basically once in a million rounds.

**Comment by Hinaichigo** [comment]
Right now it's about 5 or 6 times more likely than baseline, if you're at the luck-ceiling. We could raise the cap without affecting the scaling much if people want.

**Comment by Eneocho** [comment]
I just want a decent chance to get the gorillions in a round without having to pray for a miracle (either adminbased or real life).

**Comment by Hinaichigo** [comment]
I see what you're saying. Now there's a roughly 1/1000 chance to get the jackpot if you're at the luck-ceiling (at around 10 seven-leafs, but I lowered the scaling just bit.
I don't want to make it too common, especially based on some of the feedback in that issue.

**Comment by Eneocho** [comment]
Trust me on this one. Getting the 7 leaf clovers takes work, not only you gotta know the splices, you gotta do them in a timely manner so you can start farming luck BEFORE the round syndie gunks the round beyond repair. Even with my autismo high yield splices it still takes like 40m (from roundstart) to get one (1) 7 leaf clover, not to mention 10.

**Comment by Hinaichigo** [comment]
Do the current values above seem like they're in a good range?

**Comment by Eneocho** [comment]
1/1000 chance with maxed luck sounds reasonable and plausible within a round.

**Pull request merged**
