### PR TITLE
Magbites

### PR DESCRIPTION
**Pull request by ghost**
Sprites and idea courtesy of @Blithering 

magbites are a premium item from getmore machines, they're little boot shaped cheese puffs that, when consumed, let you resist airflow at the cost of speed.

Should you try and circumvent the slowdown with hyperzine, the medium cores react with hyperzine to make cheesy gloop.

### CODE REVIEW

**Comment by Megamaw** [comment]
flavorful way of interacting with hyperzine, noted drawback

this is a good alternative to  the current busta nuts. instead of removing stuff, we give the user a replacement that's not as powerful, but still add content.

A++. love it. can we get a picture of the sprite?

**Comment by Blithering** [comment]
magbites
@Megamaw here's the sprite

**Review by PJB3005 — APPROVED** [review]

**Comment by ComicIronic** [comment]
Let's see how these go - there's an argument for not putting more ZAS stuff in food, but they seem OK for now.

**Comment by Kurfursten** [comment]
Update wiki

**Comment by Kurfursten** [comment]
Never updated wiki!

Also shouldn't legborers make this instead of hardcores now?

**Comment by Shadowmech88** [comment]
They should.

**Comment by Blithering** [comment]
Maybe a snowflake borer version that doesn't have the hyperzine interaction? I foresee a number of borers accidentally killing their hosts if it's given to them as-is

**Comment by Shadowmech88** [comment]
We could call them softcores.

**Comment by SonixApache** [comment]
@Skullyton aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by ghost** [comment]
dag gumnit

**Comment by Exxion** [comment]
What happened

**Comment by ghost** [comment]
After this was merged, #14840 removed the slowdown

**Comment by Exxion** [comment]
Hilarious

**Pull request merged**
