### PR TITLE
cheeki breeki cargo crate komrade

### PR DESCRIPTION
**Pull request by kol1th**
adds a russian armor/clothing whatever crate to cargo contraband, for 125 space creds

image

### CODE REVIEW

**Comment by Kurfursten** [comment]
I would lower it to 30 like the feminine formalware crate

**Comment by kol1th** [comment]
@Kurfursten I agree on lowering but not to 30, since the helmet and vest are not just cosmetic

**Comment by GenericGoose** [comment]
oooooooooooo cyka blyat time to occupy space krimea

**Comment by kol1th** [comment]
cheeeki breeeki iv damke

**Comment by ComicIronic** [comment]
The webbing, especially, is not purely visual, and it can and should push the price up to well above 150.

**Comment by kol1th** [comment]
that's what I'M SAYING i hate people

**Comment by Iamgoofball** [comment]
@generalgoose *liberate the Russian populace of space crimea

**Comment by Kurfursten** [comment]
@ComicIronic But the armor and helmet are just Armor crate items, which costs 15

Webbing is just a biogenerator item (free)

**Comment by kol1th** [comment]
@Kurfursten stop making me conflicted :frowning:

**Comment by Kurfursten** [comment]
I thought you had it in a pretty good place before.

Hacking the cargo computer is something that almost never happens

**Comment by SonixApache** [comment]
Yay, more cargo contraband crates!

**Comment by ComicIronic** [comment]
Nothing should cost 15 credits for armor, and prices should not be compared to inter-department availability, because we should try to encourage interaction.

**Comment by Kurfursten** [comment]
I get what you're saying. But 250 credits is a lot to value _just_ the webbing at.

As for the armor, if you want to raise the cost of the armor crate, that seems like it belongs in a separate PR.

**Comment by ComicIronic** [comment]
It's not just the webbing, it's everything in the crate. This PR also doesn't need to raise the cost of the armor crate, I just meant that it's a change we should make.

**Comment by kol1th** [comment]
conflicts..?
image

**Comment by clusterfack** [comment]
It probably did for a short time due to a changelog

**Pull request merged**
