### PR TITLE
Adds the R34-series to all basic cyborg types

### PR DESCRIPTION
**Pull request by jknpj**
All credits go to its spriter @Kokuten

squat_bots
combat_wip
engines_ready2
rollin_out
fieldsagrowinshieldsashowin

:cl:
 * tweak: Squadbot combat cyborg is now dubbed R34 - WAR8a 'Chesty'.
 * rsadd: R34 combat borg design improved by its creator, @Kokuten
 * rsadd: R34-series icon added for all basic cyborg types

### CODE REVIEW

**Comment by Bilgecrank** [comment]
Thank you again for posting this for me.

**Comment by SonixApache** [comment]
~~👍 sprites, fucking great
👎 namechange, i like 'squadbot' a lot
😕 faulty title, what the fuck am i reading jknpj~~

👍 👍 👍

**Comment by yclatious** [comment]
Yeah, the name is shit but everything else is 💯

**Comment by jknpj** [comment]
squat_bots

Something something name

**Comment by SonixApache** [comment]
How about R34 "Chesty" ?

**Comment by Bilgecrank** [comment]
I can just be 'Chesty' the, R34 - WAR8A part is just fluff. I called it Chesty to name it for Chesty Puller, one of the most decorated U.S. Marines in history.

**Comment by SonixApache** [comment]
If you ever add the other models, the prefix stuff will help the user figure out what sprite it is. Besides, fluff is cool.

**Comment by ghost** [comment]
What's R34 supposed to mean? Rule 34?

**Comment by SonixApache** [comment]
causes burns

**Comment by Bilgecrank** [comment]
The R34 series is ready for service.

**Comment by SonixApache** [comment]
I fucking love these sprites. Fantastic work, @Kokuten.

**Comment by ghost** [comment]
let's roll these bad boys out

**Pull request merged**
