### PR TITLE
new AI core look

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[sprites]

## What this does
cobson2

## Why it's good

a more sci fi thematic ai look, it's job from stephen king's the lawnmower man! i don't think this is used in any other context... right?

## Changelog
:cl:
 * imageadd: lawnmower man AI core

### CODE REVIEW

**Comment by Kromkar** [comment]
What is "context doe"

**Comment by SECBATON-GRIFFON** [comment]
> What is "context doe"

sorry, typo

**Comment by gurfan** [comment]
hwnbag

**Comment by Kromkar** [comment]
This sucks almost as much as you do at coding.

**Comment by wotisjanitor** [comment]
HWABAG

**Comment by tinysaturn** [comment]
HWABAG

**Comment by pedr69** [comment]
oh it's actually animated
image

**Comment by SECBATON-GRIFFON** [comment]
> oh it's actually animated image

yeah i'm trying to put that in the description, just need to upscale it

**Comment by githubuser4141** [comment]
Why does it have downvotes? It doesn't look memey it looks like something from Cybershock, Doom or any other classic pre-2000's game, so it should fit in. It actually looks good.

**Comment by Aloraydrel** [comment]
QA lost

**Comment by Eneocho** [comment]
> yeah i'm trying to put that in the description, just need to upscale it

Just use ezgif.com to rescale.

**Comment by xeroxemnas** [comment]
Kill jakkers
Behead jakkers

**Comment by SECBATON-GRIFFON** [comment]
> Kill jakkers Behead jakkers

what are you talking about, the feeling of jakking into a system and mainframe is a cool thing and thematic...

**Comment by SECBATON-GRIFFON** [comment]
> > yeah i'm trying to put that in the description, just need to upscale it
> 
> Just use ezgif.com to rescale.

did it with ffmpeg just now

**Comment by Hinaichigo** [comment]
I wonder how this would do in a server vote.

**Comment by Kurfursten** [comment]
I honestly couldn't care less about this, but it looks higher effort than the other one. I legitimately think no one will remember this vote a week from now.

I stand by my earlier statement that we should just use canvas code to let AIs draw their own sprite.

**Comment by pedr69** [comment]
>higher effort

this has 2 frames while mine had 12
which is SIX times more effort!

**Comment by gurfan** [comment]
COBSON WON

**Comment by Eneocho** [comment]
chudAI bros...

**Comment by anaxosa** [comment]
this one looks so much worse than the chud one. philistines.

**Comment by tinysaturn** [comment]
COOOOOOOB GAAAAAAAAAAAAAANG
NIGGAS COALY >THOUGH
COBSON'S GOT THE GEMMY >DOE

**Comment by xeroxemnas** [comment]
we are now soyjak.party station.

**Comment by SECBATON-GRIFFON** [comment]
the gemerald that saved veegee

**Comment by SECBATON-GRIFFON** [comment]
> I honestly couldn't care less about this, but it looks higher effort than the other one. I legitimately think no one will remember this vote a week from now.
> 
> I stand by my earlier statement that we should just use canvas code to let AIs draw their own sprite.

i'm actually going to code this very soon

**Comment by pedr69** [comment]
>very soon

any second now...

**Comment by SECBATON-GRIFFON** [comment]
oh my god the guys name was actually job and not jacobson, i actually made the meme too obvious

**Pull request merged**
