### PR TITLE
Aliens can only pick up whitelisted things

### LINKED ISSUE #16871: Aliens can use autoinjectors.
#### Description of issue

> "The alien hunter (441) injects the alien queen with the autoinjector." 

#### Difference between expected and actual behavior

They are aliens, they shouldn't be able/have the dexterity to do this.

#### Steps to reproduce 

Be alien, acquire autoinjector, be an asshole.
Update : here is how to acquire the autoinjector
https://streamable.com/0tbik
Basically Ayys can be given things. Which they shouldn't.

#### Length of time in which bug has been known to occur

Just last round.

#### Server revision

a2e83a82c01a6fdb8a92c2e2e689db8726421f14 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by MadmanMartian**
There were reports of aliens doing un-alien things, like robusting their young with an emergency toolbox, carrying handbags of facehuggers, and throwing flashbangs at security.

That shouldn't be the case anymore.

EDIT: Turns out this was intended from the start, but oldcoders were doing this on an object-by-object process in /attack_paw().

If an object overwrote attack_paw, it would skip the check, meaning xenos were never meant to pick up toolboxes and the like.

fixes #16871

:cl:
* tweak: Aliens can only pickup facehuggers now.

### CODE REVIEW

**Comment by Accipitermaris** [comment]
I'm only familiar with the trick wherein xenomorphs will place a large number of facehuggers inside toolboxes and carry the toolboxes with them in-hand for softball practice. I agree that I am not sad to see that go, however someone who's been in a lot of xenomorph rounds should mention if there are any fringe items that xenomorphs would be expected to pick up that should be covered by the whitelist. I can't think of any myself, but I've also been a xenomorph less than 10 times.

**Comment by small-boss** [comment]
aliens can also use flashbangs, which is pretty absurd.

**Comment by jknpj** [comment]
they can't use them without having them in their hands

**Comment by Sooose** [comment]
Goodbye briefcase xenos.

**Comment by Pathid** [comment]
Seems to work. There is something funky that happens when you try to grab items inside of boxes though. It leaves ghosts of them on the HUD.

macragge depot victor 2017-12-26 124612

**Comment by MadmanMartian** [comment]
Good spot. Seems that it isn't calling hide_from(user). How precisely did you end up in that situation?

**Comment by Pathid** [comment]
Step 1: Drag flashbang/injector/syringe/etc. box onto you.
Step 2: Try to grab something inside.

**Comment by Sooose** [comment]
If you remove the ability for xenos to hold autoinjectors, how will I disarm doctors and inject them with their own chloral?

**Comment by MadmanMartian** [comment]
So, turns out while digging I found that storage code was being inefficicent, calling things twice, that sorta thing.

~~This PR is no longer atomic, but it fixes the problem shown by Pathid, and should have also fixed the unreported bug of floating objects being left on your screen associated with storage.~~

It'll be done in another PR

**Pull request merged**
