### PR TITLE
Revert "Revert "Revert "adds Szechuan sauce"""

### PR DESCRIPTION
**Pull request by Intigracy**
Reverts vgstation-coders/vgstation13#14579

It tastes like shit.

### CODE REVIEW

**Comment by BobdaBiscuit** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by kol1th** [comment]
Revert my dick into your ass homo.

**Comment by SonixApache** [comment]
@R-UST markov(revert)

**Comment by Exxion** [comment]
This is getting excessive.

**Comment by Kurfursten** [comment]
Just so everyone's clear here, this one gets RID of the sauce

**Comment by Kammerjunk** [comment]
Thanks I'm lost in the revert reverbs

**Pull request merged**
