### PR TITLE
X-ray Beam Penetration

### LINKED ISSUE #13577: X-ray gun doesn't shoot through walls.
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
I've heard that it does from a number of sources; it doesn't. It's just a 30 burn laser that's green.

### PR DESCRIPTION
**Pull request by Shadowmech88**
X-ray beams now have infinite penetration.
Every time an X-ray beam passes through an object, its damage is reduced by 3.
The beam is deleted when its damage reaches 0.

Fixes #13577

:cl:
 * rscadd: X-ray beams now penetrate obstacles, decreasing in damage with each obstacle they penetrate.

### CODE REVIEW

**Comment by Aurx** [comment]
I think this is a fun idea, but [BALANCE]

**Comment by Probe1** [comment]
2 is pretty negligible and 15 walls passed through is pretty high.

**Comment by Lokiamis** [comment]
@Probe1 2 would be fine if it didn't start at 30. Lowering the starting value would stop it from being a direct upgrade to the laser. The real problem for me is the ability to snipe the AI from anywhere on the station as long as you have a recharger or spare gun. Maybe fuel tanks too.
edit: oh yeah, plasma canisters

**Comment by Probe1** [comment]
That is a problem as well.

**Comment by Ephx1** [comment]
Maybe reinforced walls could lower it more significantly, but I'm sort of OK with the idea of it being able to kill an AI, especially because one of their favorite tactics is to flood the core with doors. What research level is it at?

**Comment by Probe1** [comment]
That seems like a fair compromise.  Have it passing through rwalls drop it faster.

**Comment by Sprok0** [comment]
@Ephx1 It isn't a research item, the only source of the xray laser is as a random xenoarch weapon

**Comment by gbasood** [comment]
@Shadowmech88 does it only check if the obj is dense before reducing value?
Otherwise, too stronk

**Comment by ComicIronic** [comment]
This lets you shoot halfway across the station through several walls. Make the reduction much bigger, it should go through 3 or 4 at the very most.

**Comment by Ephx1** [comment]
If it's a xenoarch item I don't see the issue, but maybe an increase on beam reduction would be best.

**Comment by Shadowmech88** [comment]
* An X-ray beam's damage is now reduced by 5 for every obstacle it passes through.

**Comment by Aurx** [comment]
That still lets you effortlessly waste the AI from outside the bridge.

**Comment by Shadowmech88** [comment]
* An X-ray beam's damage is now reduced by 10 rather than 5 when it passes through an rwall.

**Review by PJB3005 — APPROVED** [review]

**Comment by Aurx** [comment]
Can STILL waste the AI on Box from a public hallway.  
If you stand due aft of the AI, you only have to shoot through two airlocks and a blast door.  

I'd personally say to make blast doors and rwalls stop xray lasers cold.  Otherwise you'll have space jackass who jetpacks past security and wastes them from outside and is gone before anybody can react.  Or maint jackass who just dumps into departments (and/or consoles).  Or even locked room jackass who stands in a rwall box with a charger in it and dumps his gun every which way just for that griff.

**Comment by Shadowmech88** [comment]
* An X-ray beam now dies when hitting an rwall or blast doors.
* Damage lost per Bump() lowered to 3.

**Comment by Probe1** [comment]
Okay I'm much happier about this now.  I'm not super happy that r walls will stop it but the more we think about it the more it upset the applecart big time

**Comment by 9600bauds** [comment]
Why do we need to gimp every neat thing as if it was a protolathe item smh

**Comment by Probe1** [comment]
Yes, lets trial killing the AI from the mechanics workshop or EVA :v)

**Comment by Lokiamis** [comment]
Now that we've nerfed the shit out of it, I wouldn't mind a syndicate bundle with the xray gun and a pair of thermals.

**Comment by Aurx** [comment]
No thank you.  Shooting blind through walls or shooting through obstacles is already amazingly powerful.  

Shooting through walls and knowing what you're targeting is just absurd.  Make them actually work for their bullshit.

**Pull request merged**
