### PR TITLE
Moves default admin verbs to +ADMIN

### PR DESCRIPTION
**Pull request by Goldsteel**
[administration][discussion][qol]

So, this is one that I was tossing around and one that was requested. You might recall that nuke was deadminned by probe because, while he had +SOUND and played some nice music for us, the default admin verbs also happened to give him msay and access to admin controls.

This didn't sit right with me, since EVERY admin and codermin also has +ADMIN, apart from our single cross server observer, who could just have an observer verb role assigned to him.

Anyway, this fixes that. A new DJ role can easily be made that gives +SOUND and lacks msay and vv and all the other stuff. Tested it locally, seems fine. This shouldnt affect anything if you're locally hosting as the highest rank of 'host'.

-->
:cl:
 * tweak: Default admin verbs no longer exist. They are now under +ADMIN.
 * bugfix: Moderators are now a supported admin rank for those without +ADMIN

### CODE REVIEW

**Comment by Goldsteel** [comment]
One slight problem is that while they can't see msay or hear ahelps, the game still reports them as being on the admin list.

image

image

It's not really an issue if we just make the meme role 'moderation' as they don't get admin flags and will show up as mods, not admin.

I think I will leave deadmin/readmin self in the default because without it, you can't hide the SOUND tab or anything else you had prior.

**Comment by Goldsteel** [comment]
When I try and readmin it's giving me legacy admin errors, I'm not sure if this is a problem on the actual server, though.

**Comment by Kammerjunk** [comment]
I'd say "make them moderators" but I dunno if that'll do something else bad
on a related note, this might fuck stuff up for cross-server observers, but we don't actually have any of those right now so whatever

**Comment by Goldsteel** [comment]
It turns out that pomf didn't realise we still had a cross server observer. I don't think it's been important forever since we have both the headmin discord and the cross server liason role.

I could make it so that people dont show up on the admin list if their permissions list lacks +ADMIN or +MODERATOR as an entry but i think it already does that.

**Comment by ShiftyRail** [comment]
One way to fix it would be to look at the verb/functionality causing trouble, look for a code block looking like that 
`if (client.holder)` or `if (check_rights(0))` and change it by `if (check_rights(R_ADMIN))`.

**Comment by Goldsteel** [comment]
I'll have a look at this now and see if I can fix it

**Comment by Goldsteel** [comment]
The culprit was that it checked the logical statement ADMIN or !MOD which, if you are not a mod, returns true, therefore people without permissions are admins too. I corrected this.

image

Here's me removing myself just to demonstrate that works fine too.

image

**Comment by Intigracy** [comment]
You can probably just remove the moderators portion of adminwho since it's never been used

**Comment by Goldsteel** [comment]
I wanted to keep it in because of the potential for roles who are NOT admins like observers and DJs and otherwise exists and I may rename them to non-administrative staff instead of moderation

**Pull request merged**
