### PR TITLE
Adds "Game Master" as an alternate title to librairian

### PR DESCRIPTION
**Pull request by Riukanojutsu**
Title says it all. This is my first PR so please tell me if I did something wrong.

### CODE REVIEW

**Comment by frangi** [comment]
Discard any changes made to baystation12.dme

**Comment by Riukanojutsu** [comment]
I dont even know why those are here, I didnt even touched the damn thing

**Comment by d3athrow** [comment]
remove automatically add file dirs in the prefs.

**Comment by DeityLink** [comment]
When you save a file in dream maker baystation12.dme will automatically be modified. Open it in notepad to remove the added file dirs.

**Comment by Riukanojutsu** [comment]
so I have to remove all the file dir except the "." one?

**Comment by ComicIronic** [comment]
http://puu.sh/fofdn/dfe73c67e3.png.
http://puu.sh/fofiZ/1930b90bf5.png. Make sure the box is unticked.
Recompile.
Push the new baystation12.dme.

**Comment by Riukanojutsu** [comment]
I did what you said, ticked the box, compiled and pushed
now what do I do to update this pr?

**Comment by ComicIronic** [comment]
Did you commit the files before pushing?
And if you pushed to the same branch, the PR will update automatically.

**Comment by Riukanojutsu** [comment]
Pretty sure I didnt commit it. I just pushed it on my fork.

**Comment by Riukanojutsu** [comment]
Woo I deed it

**Pull request merged**
