### PR TITLE
adds follow to the arrivals announcement computer

### PR DESCRIPTION
**Pull request by ghost**
adds follow to the arrivals announcement computer

### CODE REVIEW

**Comment by ghost** [comment]
not tested because 

> still compiling

**Comment by ghost** [comment]
tested

**Comment by clusterfack** [comment]
How ever did you think of such a good qol change

**Comment by ghost** [comment]
@clusterfack just came to me in a dream

**Comment by NigglyWiggly** [comment]
The fuck are you following though
The new arrival?
the shuttle?

**Comment by ComicIronic** [comment]
The new player.

**Comment by 9600bauds** [comment]
Niggly the shuttle doesn't even move

**Comment by NigglyWiggly** [comment]
That's why I wasn't sure who the hell it was supposed to be following

**Comment by Intigracy** [comment]
#11660

**Pull request merged**
