### PR TITLE
More ZAS updating

### PR DESCRIPTION
**Pull request by Exxion**
This rewrites a lot of ZAS code, especially `connection_edge`s and `gas_mixture`s. I tried to keep gameplay changes to a minimum, as usual, but I could only do so much this time.

The gameplay changes are extremely minimal, and it's unlikely anyone would notice them, but I'd like to list them anyway. Just skip the following list if you don't care about every exact detail of airflow.
* Zones connected directly to space will now zero out their gases when they get very close to empty, rather than exponentially approaching, but never reaching a completely empty state and thus processing forever.
  * A similar thing goes for zones connected directly to other zones, but not directly enough to merge. (For example, an open airlock between them. (Airlocks always prevent zones from merging.)) When their gases get very close to equal, they completely equalize with each other.
  * Note to self: Test if multiple zones connected in a loop trying to equalize with each other causes problems.
* Objects moved by airflow will move *slightly* slower. This would actually be easy to change back, but I think how it was before was a mistake.
* Airflow movement checks no longer incorrectly assume `W_CLASS_HUGE` is the highest `w_class`, and thus items above `W_CLASS_HUGE` are no longer blown around just as easily as items of `W_CLASS_TINY`. All other (integer) `w_class`es are unaffected.

~~There will assuredly be more later, as I plan to merge `AirflowCanPush()`/`AirflowCanMove()` (which refer to the same proc; the original XGM PR renamed it from the former to the latter) with `check_airflow_movable()`, since they fill exactly the same role. But one is used in some places and the other in others, and they don't return the same values 100% of the time.~~
That's done, and didn't actually require changing any gameplay. I think.

Oh, and I strongly recommend against looking at any of the commits here individually. Many of them are very small, and many of the rest make no fucking sense due to how I selectively committed changes with a diff viewer, and how shitty said diff viewer is.

### CODE REVIEW

**Comment by ghost** [comment]
Minimal or not, those changes are WONDERFUL (imo). God bless.

**Comment by ghost** [comment]
Does this mean you can no longer "almost vent" (vent, but it just stays at 0.00001 mols forever) a room and use H/E pipes in there as if they were in space?

**Comment by Exxion** [comment]
Presumably not
But... why do you need to do that?

**Comment by Exxion** [comment]
It now compiles.
It does not, however, work, because I made at least one extremely stupid mistake and probably made innumerable less stupid ones

**Comment by Exxion** [comment]
Remaining:
* Look over the code for anything this (especially the removal of `group_multiplier`) might break
* Tweak atmos analyzer displays so they work how they did before
* Fix airflow to space being ridiculously slow (actually an easy fix; I just forgot to do it with the last batch)
* A shit ton of testing

**Comment by Exxion** [comment]
Alright. Everything I remember having to do is done, aside from testing. Nothing obvious is broken.
I think I'll try testmerging it at some point and trying to convince people to test it on the PR test server, but last time nobody did

Wait actually there's one specific thing I still need to test

**Comment by Exxion** [comment]
>Note to self: Test if multiple zones connected in a loop trying to equalize with each other causes problems.

It does.
I have a *great* idea

**Comment by Exxion** [comment]
Alright my *great* idea wouldn't work (or would be more complex to get working than an actual solution), which is unfortunate, because it was really, really bad, but in a good way
Search algorithm it is

**Comment by Exxion** [comment]
Hey what the fuck I distinctly remember almost finishing the DFS but now it's gone
I mean it wasn't hard to do, but that's still obnoxious

**Comment by Exxion** [comment]
Alright. As far as I know, this is done. More testing couldn't hurt, but I've tested everything I could think of.
If anyone else wants to try, someone can load it up on the PR test server.

**Comment by ghost** [comment]
This is nice.

**Pull request merged**
