### PR TITLE
Removes SCP294 from Bagels Asteroid

### PR DESCRIPTION
**Pull request by Probe1**
By request from sneakycoders.  Also it's fucking insane why was this added.

🆑 

* rscdel: Removes SCP-294 (The coffee machine that creates any chem in the game freely) from Bagels Asteroid.  The sneaky coder cabal was here.

### CODE REVIEW

**Comment by Irradiation** [comment]
How else am I going to have 50u of Petricirin, Hypozine, Bicarodyne, mednanos and cyanide as Bagel Cargo now?

**Comment by CptWad** [comment]
wait when the hell did that get in?

**Comment by Probe1** [comment]
We need a sneaky mapper cabal where we sneaky add in SCPs

**Comment by Kurfursten** [comment]
Wad is the sneakiest mapper

**Comment by Kurfursten** [comment]
Gottem #15728

Snuck in when the diff was too big to view on github, you'd have to read the whole raw manually without change highlighting to catch this sneaky mapping

**Comment by Accipitermaris** [comment]
deal, but in return we revert the FREE POWAH removal PR from bagel

**Comment by CptWad** [comment]
I 100% did not know that was in there
fuck

**Comment by CptWad** [comment]
while you are in there can you make it a hot drinks vendor?

**Comment by Probe1** [comment]
The amount I like you slightly outweighed my urge to be a lazy piece of shit.

**Comment by SonixApache** [comment]
So you wanted to add a hidden coffee machine on the asteroid and accidentally added a hidden matter replicator?

**Comment by Dacendeth** [comment]
I'm surprised it took this long to be fixed.

**Comment by CptWad** [comment]
oh wait that machine
you must understand that I have a memory of a goldfish
I thought you were referring to a machine on the outpost proper and was really upset with myself that I let something like that slip

**Comment by Probe1** [comment]
Yeah sorry the one _in_ the asteroid.

**Pull request merged**
