### PR TITLE
Revert "Small Blob Attack Buff (mostly just reducing frustration)"

### PR DESCRIPTION
**Pull request by BomberBro**
Blob is just way too tough, and this killed off its only weakness by allowing the blob to make fortresses of solitude in the middle of space surrounded by strong blobs. I've seen multiple blob rounds where they just inhale any emitters in space by moving over to them (one where two men with eguns couldn't stop them), then turn their attention to the crew as a juggernaut.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Dual core blobs are also way too strong to take on in a reasonable fashion.

**Comment by SonixApache** [comment]
I spotted an emitter not doing anything until the beam was refreshed by something crossing through it. Maybe that's an issue?

**Comment by boy2mantwicethefam** [comment]
If the PR is so good then why are our cringest players supporting it?

**Comment by agentofzog2** [comment]
Yeah there's some layering bug or something that makes blob immune to emitters.

**Pull request merged**
