### PR TITLE
Holy water now explodes in contact with potassium, just like regular water.

### LINKED ISSUE #28886: Holy water is too holy to react with potassium
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
f9e70f0b79bed274003cae9dbbd2980ce20a47ca

# Description
holy water doesn't react with potassium
# Steps to Reproduce
mix holy water with potassium
# What you Expected
holy hand grenade
# What Actually Happened
potassium and holy water beaker

### PR DESCRIPTION
**Pull request by Eneocho**
Fixes #28886, now it explodes. And it explodes harder. Call it holy power. Much thanks to Kurfursten for the help.
[consistency] [tweak]
:cl:
 * rscadd: Holy water works the same as water when mixed with potassium.
 * rscadd: Holy water-potassium explosions play a HALLELUJAH sound effect.
 * rscadd: Holy water-Potassium explosions are slightly stronger than regular water-potassium explosions.

### CODE REVIEW

**Comment by Exxion** [comment]
Isn't there a way to make it so that one reaction can accept multiple possible input reagents instead of just copypasting the reaction?

**Comment by Eneocho** [comment]
> 
> 
> Isn't there a way to make it so that one reaction can accept multiple possible input reagents instead of just copypasting the reaction?

If there is, I am not aware. Lemme dive for a sec.

**Comment by Eneocho** [comment]
Checked, all recipes I saw had a copy for an exception or variant.

**Comment by Exxion** [comment]
There is, but the defines hide it. Things like `BICARIDINES`. That's actually a list of accepted reagents, not one specific one.
If memory serves, though, the reagents system doesn't like it very much if the first accepted reagent is a list. But that's pretty simple to "fix" by just swapping the order.

**Comment by Eneocho** [comment]
> 
> 
> There is, but the defines hide it. Things like `BICARIDINES`. That's actually a list of accepted reagents, not one specific one.
> If memory serves, though, the reagents system doesn't like it very much if the first accepted reagent is a list. But that's pretty simple to "fix" by just swapping the order.

Huh, I did not know that. Updating.

**Comment by Dacendeth** [comment]
Should tonic and soda water be added to this as well?

**Comment by Eneocho** [comment]
> 
> 
> Should tonic and soda water be added to this as well?

Not sure. Holy water is effectively just normal water with religious significance, while tonic and soda water aren't just water anymore, since they contain Quinine and CO2 respectively. You can't mass produce tonic and soda water the way you can mass produce holy water either.

**Comment by juanototo2** [comment]
Ask the c*ders on how to make it explode harder - recommend also making holywaterpotass do something special to vampires or gult caught in the explosion.

**Comment by gurfan** [comment]
it's too holy to explode dummy

**Comment by Kurfursten** [comment]
I always thought this was a feature, along with no slippy on holy water

**Comment by Blithering** [comment]
Make it play a hallelujah sound file when exploding.

**Comment by Eneocho** [comment]
> 
> 
> Make it play a hallelujah sound file when exploding.

I WISH I knew how. That was the first thing that came to mind. A holy hand grenade, like the ones on that monty python movie. I want it to play the worms armageddon Hallelujah sound.

**Comment by Kurfursten** [comment]
Just do a new explosion reaction that does a playsound

**Comment by Eneocho** [comment]
> 
> 
> Just do a new explosion reaction that does a playsound

Pray tell how.

**Comment by Kurfursten** [comment]
chemistry-recipes.dm
make a new reaction
call playsound() with appropriate file path, volume, etc. as args

**Comment by Eneocho** [comment]
>chemistry-recipes.dm
>make a new reaction
>call playsound() with appropriate file path, volume, etc. as args

Should it be like this?
>/datum/chemical_reaction/explosion_holy_potassium/on_reaction(var/datum/reagents/holder, var/created_volume)
>	var/datum/effect/effect/system/reagents_explosion/e = new()
>	e.set_up(min(round (created_volume/10, 1), 15), holder.my_atom, 0, 0)
>	e.holder_damage(holder.my_atom)
>	if(isliving(holder.my_atom))
>		e.amount *= 0.5
>		var/mob/living/L = holder.my_atom
>		if(L.stat != DEAD)
>			e.amount *= 0.5
>	e.start()
>	holder.clear_reagents()
>	holder.add_reagent(POTASSIUM_HYDROXIDE, created_volume)
>	playsound(sound\misc\adminspawn.ogg, 100,)

I literally have no idea what I'm doing, I know not the nuances of byondcode. I want to add the original Hallelujah sound from worms armageddon, since the adminspawn one has a teleporting-like effect to it.

**Comment by Kurfursten** [comment]
You can also just make a child of the existing explosion proc so it inherits all its behaviors, which is better.

```
/datum/chemical_reaction/explosion_potassium/holy
	id = "holy_explosion_potassium"
	required_reagents = list(POTASSIUM = 1, HOLYWATER = 1)

/datum/chemical_reaction/explosion_potassium/holy/on_reaction(var/datum/reagents/holder, var/created_volume)
	..()
	playsound('sound\misc\adminspawn.ogg', 100, 1)
```

If you want a new sound, just drop it into your code and make the path in playsound match it.

**Comment by Eneocho** [comment]
> 
> 
> You can also just make a child of the existing explosion proc so it inherits all its behaviors, which is better.
> 
> ```
> /datum/chemical_reaction/explosion_potassium/holy
> 	id = "holy_explosion_potassium"
> 	required_reagents = list(POTASSIUM = 1, HOLYWATER = 1)
> 
> /datum/chemical_reaction/explosion_potassium/holy/on_reaction(var/datum/reagents/holder, var/created_volume)
> 	..()
> 	playsound('sound\misc\adminspawn.ogg', 100, 1)
> ```
> 
> If you want a new sound, just drop it into your code and make the path in playsound match it.

Sounds good. Importing.

**Comment by Eneocho** [comment]
> 
> 
> You can also just make a child of the existing explosion proc so it inherits all its behaviors, which is better.
> 
> ```
> /datum/chemical_reaction/explosion_potassium/holy
> 	id = "holy_explosion_potassium"
> 	required_reagents = list(POTASSIUM = 1, HOLYWATER = 1)
> 
> /datum/chemical_reaction/explosion_potassium/holy/on_reaction(var/datum/reagents/holder, var/created_volume)
> 	..()
> 	playsound('sound\misc\adminspawn.ogg', 100, 1)
> ```
> 
> If you want a new sound, just drop it into your code and make the path in playsound match it.

Is there a way to make the explosions slightly stronger?

**Comment by Kurfursten** [comment]
You could add a var to the parent explosion reaction that's something like `var/bonus_range = 0` and then in the `set_up` code add it. Refer to the reagent explosion code for what the args are associated with. Explosions don't just simply do damage, they have 3 ranges (devastate, heavy, light) and everything within that range gets hit by that type of explosion.

**Comment by Eneocho** [comment]
> 
> 
> You could add a var to the parent explosion reaction that's something like `var/bonus_range = 0` and then in the `set_up` code add it. Refer to the reagent explosion code for what the args are associated with. Explosions don't just simply do damage, they have 3 ranges (devastate, heavy, light) and everything within that range gets hit by that type of explosion.

Thanks for all the help, but please, more simplified instructions. I literally am working with code I barely understand here.

**Comment by Kurfursten** [comment]
The easiest and simplest way to do it would be just to add this to the holy version below required_reagents
`result_amount = 2.2`

**Comment by Eneocho** [comment]
> 
> 
> The easiest and simplest way to do it would be just to add this to the holy version below required_reagents
> `result_amount = 2.2`

Appreciated. I went with 2.4 so they're decently stronger while not overpowered.

**Pull request merged**
