### PR TITLE
Fixes Endgame music

### LINKED ISSUE #30101: Christmas and Endgame Playlist are broken
(WEB REPORT BY: djkramer REMOTE: 206.221.180.138:7777)
# Revision
2faee0dc4dbc5dd71a2b69136f0a50b059c8dffb

# Description
Both the Christmas Jingles and Apocalypse vinyls are busted, this also means bloodstone music doesn't work
# Steps to Reproduce
1. Want to listen to christmas tunes or wallow in despair to the bloodstone music as cult takes overs the station
2. Silence.
# What you Expected
To feel the christmas spirit or soul sucking pain from cult winning 
# What Actually Happened
Left with uncomfortable silence

### LINKED ISSUE #30219: Endgame playlist is still broken
(WEB REPORT BY: djkramer REMOTE: 206.221.180.138:7777)
reeee

### LINKED ISSUE #36182: Revs music does not trigger when they go loud
(WEB REPORT BY: theophrastus REMOTE: 172.93.101.77:7777)
# Revision
0d7e1eccef1a3909779918b893ca04023b77b08b

# Description
Music that is supposed to start once the revs go loud does not start playing once the union message comes out.

# Steps to Reproduce
Go loud as revs

# What you Expected
Sick tunes and beats

# What Actually Happened
Dead silence

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #30219
Fixes #30101
Fixes #36182

top kek 
image

:cl:
* bugfix: Music should play again during thematic endgame events such as the Cult, Nuke Ops, or Supermatter Cascade.

### CODE REVIEW

**Comment by Theophrastus1** [comment]
fucking speedmerge this

**Comment by djkramer123** [comment]
bless you

**Comment by hacker-on-steroids** [comment]
what even broke this and when?

**Comment by DeityLink** [comment]
Hell if I know, all I know is that calling ticker.StartThematic("endgame") on the server last night did nothing and the jukebox was unpowered.

Doing the same after either moving it to a powered area or calling power_change() after setting its use_power to 0 turned it on and everybody heard the music. People were so unused to it that they thought it was admin music.

I don't know when it broke.

**Review by jwhitak — APPROVED** [review]

**Pull request merged**
