### PR TITLE
Fixes soil unwrenching business

### LINKED ISSUE #8093: Dirt trays can be dragged around
Put a pipe connector under dirt tray, wrench it, unwrench it, marvel as you can drag it around.

Brought to you by taxi station outpost, where advanced xenobotany is done in dirt piles with connectors!

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #8093

### CODE REVIEW

**Comment by clusterfack** [comment]
Why aren't you removing the WRENCHMOVE flag from soil?

**Comment by 9600bauds** [comment]
I am, I did, just that portable_atmospherics have a sooper snowflake wrenching/unwrenching to ports.

**Comment by clusterfack** [comment]
Why not have wrenching to ports check wrenchmove?

**Comment by clusterfack** [comment]
Or something

**Comment by 9600bauds** [comment]
Because that makes TOO MUCH SENSE.

**Comment by 9600bauds** [comment]
I'll do it later.

**Comment by 9600bauds** [comment]
It turns out that portable_atmospherics just don't have WRENCHMOVE in the first place, they're just not boltable to the floor, only to atmos connectors.
Which makes perfect sense because that's what atmospherics connectors are meant to do.
Now, hydroponics trays are a child of portable_atmospherics because ostensibly they're supposed to have atmos implementation that's extremely half-baked, half-broken and never used. Cool. Soil, however, is not. There's no reason for soil to be a subchild of portable_atmospherics. But, of course, you'd need to either copypaste every single proc from the regular tray over to the soil, or make the soil a neutered child of the hydroponics tray with all atmos features blocked away.
Which, really, is what was already had been done. With the exception of THIS detail.
So my options here are to add a CONNECTS_TO_CONNECTORS flag and give it to all portable_atmospherics except soil...
or just override this here.
Honestly, I don't think this soil business can get any better than the bastard child it is right now. I don't think there's a point to doing this another way.

**Pull request merged**
