### PR TITLE
makes mice just as hardcore as humans

### PR DESCRIPTION
**Pull request by SonixApache**
i.e. they no longer die if they're not fed unless hardcore mode is on
requested by @salamandooo

:cl:
 - tweak: Mice are now equally as hardcore as humans

### CODE REVIEW

**Comment by salamandooo** [comment]
You can't mess around as a mouse anymore because you always have to get food, and their tiny mouse paws cannot hold food to carry around. This is a good thing to fix!

**Comment by ghost** [comment]
That's precisely why it was there in a first place. You can't just sit in bumfuck nowhere and spam comms forever, mice gotta eat.

**Comment by salamandooo** [comment]
But that's no fun

**Comment by ghost** [comment]
It went from 

>I exist purely to exist, I griff verbally and that is all that I can do

To

>Gotta raid that fucking pantry if I wanna survive, oh fuck the chef has a cat

**Comment by abagone** [comment]
Personally I think starvation is generally a terrible mechanic. 

Give them the same downside when humans are hungry make them really slow

**Comment by abagone** [comment]
Also having the mice have a mind of its own and automatically move towards food is cancer.

It should only do that when you're really hungry it could actually be kind of useful not having to click a lot.

**Comment by SonixApache** [comment]
Right now they still move slower when they're hungry, but they only die of starvation when hardcore mode is enabled, which causes carbons to die of starvation as well.
I got a complaint about mice not being fun anymore because they just loldie, so I figured this'd be an elegant solution.

**Comment by abagone** [comment]
You know this makes me think how often is hardcore mode even turned on?

**Comment by ghost** [comment]
Rarely, if ever. People don't like the thought of having to eat to stay alive

**Comment by gbasood** [comment]
People like hardcore though?
Not everyone, obviously. I think most people like it on higher pops.

**Comment by Probe1** [comment]
@Skullyton you coded it.  Flesh out an argument on why it should not be changed.

**Comment by ghost** [comment]
Because the intention of the code was so that mice would have something to do, and have to do something, rather than just sit there and shitpost in chat all round and tell borgs/people with borers who killed them.

Gotta fight to survive, and chefs have to fight to protect their food. From observation it's certainly made the kitchen more lively, with the chef having to abduct the librarians cat to defend his food and dropping mousetraps here and there

**Comment by ghost** [comment]
After a fair few rounds of becoming a mouse tamer, I've found that mice needing to eat has led to some more interesting encounters.

I've found the chef having to barter (see: Steal from) the librarian, CMO, or paramedic for their mouse hunters, and ask the janitor for mousetraps as they have to defend their food from being eaten.

I've seen chef food fly off the tables not because people want to eat them, but so they can support their pet mouse.

There does need to be more feedback to people that a mouse may be starving to death, however (examine text doesn't carry over to the mouse held object, so it becomes interesting to note when your mouse friend may be starving or not unless it reacts itself), and maybe push the boundaries a little outwards (10 nutrition instead of 100 and below for the starving point, 500 and above for the too fat point, and maybe increase nutrition loss speed while fat)

Yet to see a single admin utilize plague rats or wire-nibbling rats however, maybe should add those to minor infestations.

**Comment by PJB3005** [comment]
From what I've seen the issue with starvation is how quickly you starve, not that it's a mechanic in the first place.

**Comment by Probe1** [comment]
That and player controlled mobs auto pathing to food.  Neither is appreciated by players.

**Comment by salamandooo** [comment]
Thing is, I don't think "something to do" is what someone plays as a mouse for. If I wanted to get back in the round full fledged, I'd go haunt a botanist or a robotics. When I, (and presumably others), play as mouse, it's because I wanna just chill out and watch, without having a scope of everything happening in the round, and additionally to have minimal interaction. Having the mouse food requirements turns what used to be a neat thing to do to chill out after you've died, into a semi-stressful food hunt which defeats the purpose of the role. I used to go mouse all the time, but there's no point if I have to focus so deeply on staying alive.

**Comment by Probe1** [comment]
Went with Dragonbros because I'm not giving mice cool abilities then removing the downsides.

**Comment by SonixApache** [comment]
This is unfair treatment of rodents. Why must the humanoids always be held in a better light? Why must lesser mobs suffer because humans and their alien brethren are too casual to eat? This is not the end, Probe, mark my words. I'm taking this to the highest possible authority. The rats will be free from oppression.

**Comment by Probe1** [comment]
LIBERTAS
LIBERTAS

**Comment by ghost** [comment]
Don't tempt me to make maintrats

**Comment by Probe1** [comment]
I've always wished cockroaches and mice could carry disease.

**Comment by ghost** [comment]
mice can already carry disease. That was in the last PR.

Yet to see a single admin use one

**Comment by Probe1** [comment]
I mean naturally.

**Comment by ghost** [comment]
Nexis poo-pood the idea

**Pull request closed without merging**
