### PR TITLE
Makes borgs vulnerable to fire

### LINKED ISSUE #15346: Borgs are supposed to be flammable but aren't for some reason
#### Description of issue

Borgs have code for catching/being on fire, but it doesn't seem to work.

#### Difference between expected and actual behavior

*Borg steps in burning inferno, comes out ablaze*
vs
*Borg steps in burning inferno, comes out just fine*

#### Specific information for locating
`code/modules/mob/living/silicon/robot/life.dm#L325`

#### Server revision
c8ab2aa22449e87b6463b560370143c893e0cf80

### LINKED ISSUE #17393: This is fine.
thisisfine

The current silicon fire immunity is actually an oversight. This issue is related to #15346.

Let's check their fire_act():
https://github.com/vgstation-coders/vgstation13/blob/25b228d3ecf180434125da9047275280ea2ce535/code/modules/mob/living/silicon/robot/life.dm#L335-L337
Ok so, they don't have fire_stacks, fine. IgniteMob() is called, but since cyborgs don't have their own IgniteMob()...

https://github.com/vgstation-coders/vgstation13/blob/70302175f29fe4915f40b2df8beb2f0b3efd1f41/code/modules/mob/living/living_defense.dm#L266-L274

They don't ignite at all. The best part is, they are supposed to take damage when on fire: 
https://github.com/vgstation-coders/vgstation13/blob/25b228d3ecf180434125da9047275280ea2ce535/code/modules/mob/living/silicon/robot/life.dm#L321-L326

### PR DESCRIPTION
**Pull request by Zth--**
edit: done and tested

Fixes #17393
Fixes #15346

:cl:
 * bugfix: Fixed borgs being immune to fire.
 * rscadd: Engiborgs and mommis have protection against it.

### CODE REVIEW

**Comment by jknpj** [comment]
Fixes #17393

**Comment by Zth--** [comment]
how didn't I see that issue before?

**Comment by AutismSpider** [comment]
Crabs and engiborgs shouldn't take fire and pressure damage other types should.

**Comment by Zth--** [comment]
ok, this is done and tested. I added a fire module to engiborgs and mommis. I also fixed a problem with the fire overlay.

**Comment by Aurx** [comment]
This is, in fact, not at all even remotely tested.  Fix your shit.

**Comment by Aurx** [comment]
I'm 99% sure this runtimes.  You sure you covered your test cases?

**Comment by Zth--** [comment]
you're right

**Comment by jknpj** [comment]
won't this make mommis unable to do anything inside a fire since they only have one hand?

**Comment by Zth--** [comment]
It's not a component you can pick and use, it's just there saying "you are immune to fire".

**Comment by SonixApache** [comment]
fixes #15346

**Comment by Probe1** [comment]
TEST MERGE if the players hate it the revert button will be visited

**Comment by jknpj** [comment]
Maybe a server poll after test merging it? I don't know we never do test merges anymore

**Comment by Probe1** [comment]
That was my thought.

**Comment by SonixApache** [comment]
what about the related issues?

**Comment by DamianX** [comment]
Updated the OP.

**Comment by Zth--** [comment]
We can test merge it, yes, I see no problem in that. Thank you Damian

**Comment by DamianX** [comment]
I'm not particularly for or against this, so I'm fine with test merging.

**Comment by jknpj** [comment]
Not really a fan of how the fire immunity is handled(visible useless module) but i guess i can simply change it when the silicon update gets merged.

**Comment by Zth--** [comment]
It felt better than hardcoding it, and that's the only solution I could find without writing a new system. Making it togglable would've been consistent but stupid as hell

**Comment by jknpj** [comment]
You could create a var at module level and check that if the silicon.module.fire_immunity is TRUE. That's what i'm doing for a lot of hardcoded shit.

Don't worry about it now since the big silicon update isn't in yet i guess.

**Pull request merged**
