### PR TITLE
Vox Winter Coat Sprites

### PR DESCRIPTION
**Pull request by falcon2346**
## What this does
This adds vox sprites for all job related winter coats, as well as the slime coat as part of an effort to eventually make all items available at the trade port fit them, provided they aren't a clothing item that their species is excluded from. Additionally, this adds a sprite for the Head of Personnel's dress jacket, as it was convenient to do while making the coats.

## Why it's good
More sprites that fit are always good.

## Changelog
:cl:
 * imageadd: Added new sprites for winter coats and the HoP's jacket.
All Coats

### CODE REVIEW

**Comment by Hinaichigo** [comment]
The slime coat kinda makes me think slimes and skeletons should be defined at a 'sub-species' level or something. So you could have slime vox and slime insectoids and stuff more easily.

**Comment by SageOfLight** [comment]
If you're cold, your chicken is cold.

Put a coat on your vox today.

image

**Comment by NigglyWiggly** [comment]
> The slime coat kinda makes me think slimes and skeletons should be defined at a 'sub-species' level or something. So you could have slime vox and slime insectoids and stuff more easily.

I'm pretty sure slime people used to be just your race colored bright cyan, with the extra weakness to cold and resistance to electricity tacked on

**Comment by Eneocho** [comment]
> > The slime coat kinda makes me think slimes and skeletons should be defined at a 'sub-species' level or something. So you could have slime vox and slime insectoids and stuff more easily.
> 
> I'm pretty sure slime people used to be just your race colored bright cyan, with the extra weakness to cold and resistance to electricity tacked on

Slimepeople as they are now are an independent race, a very broken (in the buggy and obscure sense) race, but an independent one. Like half the playerbase does not know how to revive a dead slimebro.

**Pull request merged**
