### PR TITLE
[Defficiency] A whole bunch of stuff

### PR DESCRIPTION
**Pull request by Duny-**
- The derelict is now identical to box's. (Closes https://github.com/d3athrow/vgstation13/issues/2227)
- Added canes in genetics, next to the glasses. (Closes https://github.com/d3athrow/vgstation13/issues/2422)
- Made yet another attempt at fixing brig timers. (d3athrow#2430)
- Added decals all over maintenance so that the less fortunate when it
comes to having a basic sense of direction don't get lost inside the
abandoned areas.
- Added recycling stuff and a camera to disposals. No incinerator, and
none planned.
ss 2015-01-04 at 05 19 41
- Added some wall-mounted fire and o2 closets, a fire closet, some
plasma, more solution trays and beakers and an additional dropper to the
research outpost. Fixed floating biohazard sign. The power now also runs
through the SMES. (https://github.com/Duny-/vgstation13/issues/22)
- Added surgery overflow.
ss 2015-01-04 at 05 18 37
- Probably fixed miners being thrown around when leaving the mining
station
- Added missing cameras in security. (Closes d3athrow#2430)
- All research outpost air alarms can now be unlocked with science
access. (https://github.com/Duny-/vgstation13/issues/22)

### CODE REVIEW

**Comment by Riukanojutsu** [comment]
Did you do something with the empty 2x2 room next to cryo (I think it was cryo, maybe it was paramedics?)?

**Comment by Duny-** [comment]
It's 1x2, and not yet.

**Comment by Riukanojutsu** [comment]
Any plans?

**Comment by Duny-** [comment]
Simply remove it :^)

**Pull request merged**
