### PR TITLE
Removes atmos related xenoarch large effects and triggers from natural gen

### PR DESCRIPTION
**Pull request by DrSnips**
## What this does

Exactly what it says on the tin.
It removes the atmos related triggers (temp, pressure, gas type) and the effects (heating, cooling, and gas synth) from the xenoarch large artifacts.
This doesn't remove them from the game entirely though. You can still admin spawn large artifacts with these triggers/effects and any other means of creation.

## Why it's good

I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST I HATE THE ATMOS-CHRIST

Jokes aside, atmos related stuff is by far the worst trigger/effect conditions when you ask most players familiar with the process, including myself. When considered together on each side of triggers/effects, they occupy a good chunk of each list as there is 3 in each which is roughly a 1 in 3 chance. There is still plenty of experimentation that doesn't require you to plasma flood the room or create skeleton crushing pressure rooms to get an artifact that charges batteries or harms you further.

## How it was tested

It isn't. If you want to spend the time hunting for a natural large artifact with another layer of RNG to get it to have atmos related effects then be my guest.
## Changelog

:cl:
 * rscdel: Large artifacts from xenoarch with the random effects/triggers no longer naturally appear with atmos related effects/triggers.

### CODE REVIEW

**Comment by angryturnip** [comment]
Hunting for larges and then examining them to find out what they do is literally the point of the job

**Comment by DrSnips** [comment]
I have great news, the pool is still bloated with a bunch of other dumb triggers and effects. You have plenty of "experimenting" (read: going on the wiki or through the code because I know sure as hell you don't know them) to be able to do.

**Comment by djkramer123** [comment]
The atmos triggers/effects are pretty lame/awful, good change

**Comment by DrSnips** [comment]
To gauge some intrest, while I think all the atmos stuff sucks would anyone want any particular triggers or effects to stay? I could make an arguement to keep the atmos synth effect or trigger on any % gas presence.

**Comment by boy2mantwicethefam** [comment]
I would support this if it was merely triggers

**Comment by west3436** [comment]
Not enough support for this one.

**Comment by bathosbathtime** [comment]
I don't mind this change. Do larges that react to vacuums still instantly activate when they spawn? In unaltered gameplay I mean.

**Comment by DrSnips** [comment]
This doesn't modify how any of the trigger/effects work, just that they no longer appear on natural exotic larges anymore.
So you can't even find a low pressure trigger exotic large naturally with the changes.

**Pull request closed without merging**
