### PR TITLE
Improves the phazon stock part functionality on certain machinery

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
It came to my attention that the special stock parts that can only be found via xenoarch had to go through 3 gates:
- The Xenoarch gate - The xenoarchaeologist not only brings them back to the station but also brings all 4 types of them.
- The Mechanics gate - Someone actually bothered to scan them using the Device Analyzer.
- The Phazon gate - Actually having the phazon required to print more of them.

It's for these reasons that I decided "it's fine for the components to do cool stuff, they're really rare and people are lazy at getting them". These machines now have additional functions when fully upgraded with phazon parts:
- Chemistry Dispenser: Unlocks quickly producing Plasma. More suggestions are welcome. No I don't think I can get away with nanobots.
- Booze Dispenser: Unlocks Karmotrine. The components did come from the same place that Karmotrine comes from. Mix those drinks up.
- Sleeper: Unlocks Doctor's Delight, Rezadone and Peridaxon, two more additions to the monstrous healing machine that is the Sleeper.

 Also made the Cloning Pod change its description to better highlight its special function with fully upgraded phazon parts.
:cl:
 * rscadd: The Chemistry Dispenser, Booze Dispenser and Sleeper now unlock extra chemicals when fully upgraded with phazon parts.
 * rscadd: The Cloning Pod will now change its name and description when fully upgraded with phazon parts. This is reversible in case it doesn't have phazon parts anymore.

### CODE REVIEW

**Comment by jwhitak** [comment]
There's also the Money gate alternative route. If your trader gets lucky, the super part injectors can have (non scannable by mechanics) tier 4s in them.

I was previously considering PRing having sleepers be voice operable at tier 4, but iirc they already can inject critical patients at that level.

Also, for the chem dispenser, please put the new chems at the end of the list so they don't make the chemists brains break (based on the screenshots you provided this isn't the case).

**Comment by Eneocho** [comment]
I'd rather have them be more common than do wacky powerful stuff, since heavily gated stuff seldom sees any use. But I guess this is fine.

**Comment by Eneocho** [comment]
Here's a couple of ideas for phazon part buffs:
* Instantaneous splicing/purging/gene sampling on xenobotany machines.
* Hyper efficient cooking (you get 2 of whatever you cooked instead of 1).
* Hydro-trays refill and clean themselves.
* Biogenerators can use any chem as nutriment for biomass calculations.
* Self-charging reagent dispensers (they use no power and recharge faster).
* Cryotubes no longer need cryogenic air.
* Body Scanners inject stabilizing chems onto the user if IB is detected (biofoam or preslomite).
* Genetics machines tell you which gene is on the unlocked blocks.
* Autolathes/Protolathes/Circuit Imprinters print instantaneously.
* Flatpack Fabricators/General Fabricators no longer need plastic.
* Condimaster can make _all_ reagents with condiment bottle designs.
* Ore Processing/Recycling machines get more material per unit (with some sanity), you feed 5 iron ore and get 10 metal instead of 5.
* Heaters can heat to 1000s of degrees.
* Coolers can cool down to 0.1K and do it fast.
* R-UST core EM field has more capacity (instead of capping at 1M particles it can hold 5M, for example).
* Gyrotrons can fire faster and harder.
* Chem Dispenser can make uranium, gold and plasma.
* Vending machines sell at a discount/spit out WAY more often.
* P.A.C.M.A.N. generators no longer consume the fuel/use it very slowly and can reach MW levels of power (an upgraded mrspacman can get to 480kw tops).
* Laser heaters and cryo coolers (to heat/cool beakers) instantly heat/cool to the target temperature.
* Smartfridges get linked with each other despite subtypes (so you can take food out via the medical smartfridge).

**Comment by poales** [comment]
I'd rather have the dispenser capable of dispensing plasma than dylo/inaprov

**Comment by boy2mantwicethefam** [comment]
@Eneocho I like some of those ideas. I've already got a fair amount of upvotes for the current PR so I don't think I can just change it out of the blue to include more things that people might have a chance to disagree with, but I noted some of those down for maybe a future PR.

**Comment by jwhitak** [comment]
Could kill the PR and make a new one.

**Comment by boy2mantwicethefam** [comment]
Nah it's in a good state.
Also the extra chems in the Chemistry Dispenser will now append to the list rather than intermingle with it AKA it no longer messes with muscle memory.

**Comment by Eneocho** [comment]
Make sure the chems don't interfere or interact weirdly with xenobio-upgraded chem dispensers (Delightful Syrup).

**Comment by boy2mantwicethefam** [comment]
It should be fine the way I implemented it, which is to remove the upgraded chems at the start and only re-add them if the machine is upgraded, and delightful syrup doesn't belong in that upgraded chems list.

**Comment by Eneocho** [comment]
Still, you oughta test it. We've had far too many unforeseen consequences `*cough* adacovsk *cough*` lately.

**Comment by tinysaturn** [comment]
I think the sleepers should also get Rezadone to complete the ghetto cryo identity they got with the soporific update

**Comment by boy2mantwicethefam** [comment]
@Eneocho Will test
@tinysaturn Sure

**Comment by boy2mantwicethefam** [comment]
Sleepers now contain Rezadone too when upgraded.
Also I tested delightful syrup and it works.

**Pull request merged**
