### PR TITLE
Makes Seeking Damage not AOE

### LINKED ISSUE #4360: Magic missiles still do unexplained tremendous damage to anyone touching them
Its strange but occasionally magic missiles do SHITLOADS of damage to people next to them. Ususally happens if you are next to the wizard when he casts the spell.
I think what tried to fix it was "The magic missile pops with a flash!" message but that did not fix the main issue as to where this damage was coming from.
Revival of #2996

### PR DESCRIPTION
**Pull request by clusterfack**
Fixes #4360 I think. A magic missile show would do AOE damage in 1 tile around it, with a few mobs around it this stacks up very very quickly.

### CODE REVIEW

**Comment by clusterfack** [comment]
It also fixes a thing where you could get hit by a spell hiding behind a door (which magic missile could totally due) due to merely checking range and not Adjacency.

**Comment by Probe1** [comment]
https://youtu.be/0qTfA2BDh1k?t=39

**Comment by CptWad** [comment]
praise jesus

**Comment by Intigracy** [comment]
Why does MM deal damage at all?

**Comment by Probe1** [comment]
Well its a missile, it's magic, and it deals damage by design.

**Pull request merged**
