### PR TITLE
Adds recipes for Hydroponics-related chemicals

### PR DESCRIPTION
**Pull request by ValkyrieSkies**
Adds recipes for creating the Hydroponics chemicals dispensed by the Nutrimax vendor.

E-Z-Nutrient
1 part Nitrogen, 1 part Phosphourous, 1 part Potassium

Robust Harvest
1 part E-Z-Nutrient, 1 part Formic Acid (Catalyst)

Left 4 Zed
1 part E-Z-Nutrient, 5 parts Radium (Catalyst)

chem

### CODE REVIEW

**Comment by kilozombie** [comment]
Hey cool but why exactly
I'm fairly sure you can make all 3 in the biogenerator for cheap.

**Comment by Riekland** [comment]
you're doing a great service to the proliferation of space weed soldier

**Comment by kilozombie** [comment]
I mean, you can make it from the biogenerator. But I guess this can be real handy for ghetto chem.

**Comment by ghost** [comment]
God bless potato batteries, gonna be a real crazy trip in a ghetto station gimmick map.

**Comment by ValkyrieSkies** [comment]
@kilozombie 
I think "But the Biogenerator can make it" is a really bad precedent to set for whether things should be added or not. There are other things the biogenerator can make that can be obtained by other means but that doesn't have us setting out to delete all alternative means to create those. Furthermore, being able to make EZ Nutrient in a large quantity without having to grow a crop to fill the biogenerator is pretty advantageous, I'd say.

**Comment by ValkyrieSkies** [comment]
Wiki info ready to go.

http://ss13.moe/wiki/index.php/User:ValkyrieSkies/Sandbox

**Pull request merged**
