### PR TITLE
Electric Boogaloo (Take Two)

### PR DESCRIPTION
**Pull request by gurfan**
Same as #31728, reopening to (maybe?) fix conflicts
From last PR:

[gamemode]
### Malfunctioning AI Overhaul

https://user-images.githubusercontent.com/51427771/147508302-e063cac9-158c-4be4-999b-be4799f2178c.mp4

https://user-images.githubusercontent.com/51427771/147508293-b5061985-2f81-4953-b316-8bfe009c6995.mp4

https://user-images.githubusercontent.com/51427771/147508275-e5638de2-6d84-4eb0-b6a1-864b849c787d.mp4

https://user-images.githubusercontent.com/51427771/147519622-f0694713-c79e-460d-b4be-1a62b3f798eb.mp4

Malfunctioning AI has been reworked to revolve around hacking machines and utilizing hidden abilities within those machines. 
Right Click to hack a machine. You can hack only hack one APC at a time, but for each APC hacked you can hack one more non-APC simultaneously. Hacking always takes 60 seconds.
Once a machine is hacked, right click it again to view a radial will all its abilities.
Hacked APCs will _very slowly_ generate processing power.

My hopes with this rework were to give malfunctioning AIs the ability to perform a lot more minor sabotage and deception, without immediately alerting the crew that there is a malfunctioning AI. (Though there are still plenty of abilities that will do that)
Since the malfunctioning AIs abilities are tied to the machines themselves, rather than magical spells, I also hope that this would make the gamemode a lot more dynamic. By destroying machines or moving them out of the AIs view, the crew can limit what the AI is capable of. 
I also hope that since AIs need to hack machines prior to using them, they would be forced to strategize and plan their approach to the round.
EMPs will also disrupt a malfunctioning AIs control over a machine for thirty seconds.

**The takeover process is still largely the same, but with a few changes:**
Right-Click your core to purchase core upgrades or start your takeover.
If the AI takes over the station, the round still ends, but the AI needs to interface with the nuclear fission device in order to blow up the station and get a major victory.

**For a full list of a abilities, see this document:**
https://docs.google.com/document/d/1_XUwdmdFh9eqGjFjmu9d4LnQ6FKCxdoyulhzAQQwvoA/edit?usp=sharing

:cl:
 * rscadd: The Malfunctioning AI Gamemode has been completely reworked:
 * rscadd: Malfunctioning AIs can now right click APCs and other machines to hack them and access various special abilities
 * rscadd:  They can also right click their core to purchase upgrades or start their takeover.
 * rscadd: Malfunctioning AIs generate power from hacked APCs, and use that power to activate special abilities on hacked machines.
 * rscadd: They can also control some devices normally uncontrollable by an AI, as long as they have hacked the device. This includes communication consoles and account databases. 
 * rscadd: Malfunctioning AIs can't activate any abilities on machines that are depowered, broken, or have recently been hit by an EMP.
 * tweak: Bypassing AI control on an airlock as a Malf AI has been moved to the new system.
 * rscadd: For a full list of abilities, see this document: https://docs.google.com/document/d/1_XUwdmdFh9eqGjFjmu9d4LnQ6FKCxdoyulhzAQQwvoA/edit?usp=sharing

### CODE REVIEW

**Comment by gurfan** [comment]
I have no idea if this is still conflicting with the secret repo or not

**Comment by Eneocho** [comment]
speedmerge it and lets see if it does

**Comment by SonixApache** [comment]
electric boogaloo 2: electric boogaloo

**Comment by Kurfursten** [comment]
conflicts

**Comment by gurfan** [comment]
@Kurfursten Fixed the regular conflicts. I don't know if its still conflicting with the secret repo.

**Pull request merged**
