### PR TITLE
No MDs? No problem!

### PR DESCRIPTION
**Pull request by jknpj**
This bad boy can fit so many fucking chems in it.

:cl:
 * rscadd: CMO's locker now starts with one advanced medibot cube

### CODE REVIEW

**Comment by MadmanMartian** [comment]
There's already 2 in medbay via the medvends, just get a coin

**Comment by SonixApache** [comment]
@MadmanMartian 
They're voucher-only, actually. You get the voucher from safe spawners.

**Comment by Tokanova** [comment]
never heard of an advanced medibot so it'd be nice to merge this and revert it if it sucks

**Comment by Kurfursten** [comment]
It's a medibot but it can inject Dex+, Bicaridine, Dermaline, and Antitox, which makes it dramatically stronger than the normal medibot. Just the Dex+ is quite good.

**Comment by crudequip** [comment]
also it looks cool

instead of this, consider making the voucher a high priority job reward, maybe?

**Comment by SonixApache** [comment]
CMO's spare spawns in the CMO's office when there's no CMO

**Comment by Tokanova** [comment]
can we make a voucher spawn in the CMO locker if there is no CMO? or similarly the CMO starts with a voucher?

**Pull request closed without merging**
