### PR TITLE
Adds a supply cyborg hookshot upgrade to the premium items in the dwaven vend.

### PR DESCRIPTION
**Pull request by jknpj**
The first non-generic supply upgrade, too.

:cl:
 * rscadd: Adds a supply cyborg hookshot upgrade to the dwaven vend's premium items for 3000 spessbucks.

### CODE REVIEW

**Comment by Ephx1** [comment]
Wouldn't this require a human to buy it for the cyborg? Silicons can't interact with machines that take cash.

**Comment by jknpj** [comment]
Yes, that's the idea. They can't even use the coin that's required to unlock the premium menu, after all.

**Comment by Ephx1** [comment]
Alright, it just seems like this won't see much use.

**Comment by AutismSpider** [comment]
does this work on mommis?

**Comment by jknpj** [comment]
@AutismSpider nope

**Comment by DrSnips** [comment]
Why is the upgrade locked behind a coin AND money while the normal one is only behind money?

**Comment by jknpj** [comment]
Because god willed it

**Comment by DeityLink** [comment]
I'm considering lowering the price of hookshots, now that they've been in the game for a while. Also since the price hike was a request from probe.

**Comment by jknpj** [comment]
They're kinda expensive but it's not like people actually buy them, they just use a multitool and a mice to get it for free.

**Pull request merged**
