### PR TITLE
Changing cell chargers

### PR DESCRIPTION
**Pull request by ghost**
You can't go wrong with electricity
- Add transfer_rate and tranfer_efficiency. Both of those can be tweaked for upgrades if ever implemented
- Span, typecasting
- Add emagging. An emagged charger will drain room power, and explode when someone realizes what's up and tries to remove the cell (with a very small window to get the fuck out of here)

Transfer_rate is now the same as it used to be. I honestly can't tell what kind of relativist system BYOND works under, but it makes it hard to figure out ideal charging times so don't change what isn't broken

### CODE REVIEW

**Comment by Probe1** [comment]
the emagging idea is top notch, but are cell chargers even buildable?  

the rest of it seems more useless than an asshole on an elbow.  "people rarely use them so lets nerf it"

**Comment by dylanstrategie** [comment]
Chargers aren't buildable currently, but you can move them

Also charging rates are pretty ridiculous. If people don't use cell chargers, it's because the power cell system isn't too demanding

**Comment by AutismSpider** [comment]
Can you add build able chargers then?

only 3 on box i think.

**Comment by dylanstrategie** [comment]
I'll give that a look once I have free time

**Comment by dylanstrategie** [comment]
I'll personally calculate charge times to see how long charging would take live, give me a little bit

**Comment by d3athrow** [comment]
No

**Comment by dylanstrategie** [comment]
The transfer rate was reverted back to default, and while at it I included an upgrade system since I had that on my mind

I missed the part where a "Do not merge" notice was actually needed, but normally this should fix all the complaints this PR has received thus far

**Comment by dylanstrategie** [comment]
Waiting for merge or additional feedback

**Pull request merged**
