### PR TITLE
Adds sprites for insectoid variant of basilisk reinforced mining suit

### PR DESCRIPTION
**Pull request by kestoloppu**
When the ability to reinforce suits with skins other than goliath was added it only included human versions of the sprites. 
Here are some sprites for bugs for basilisk skins.

## What this does
Adds sprites for insectoid variant of mining suit reinforced with basilisk skins
EDIT: now with image
image

## Why it's good
Human helmet sprite doesn't align to insectoids

## Changelog
:cl:
 * rscadd: Adds sprites for insectoid variant of mining suit reinforced with basilisk skins

### CODE REVIEW

**Comment by SonixApache** [comment]
gonfligds

**Comment by Kurfursten** [comment]
fix confl

**Comment by Kurfursten** [comment]
fix confl

**Comment by Kurfursten** [comment]
abandoned?

**Comment by ShiftyRail** [comment]
Gonflcits!!!!!!!!!!!

**Comment by Kurfursten** [comment]
Seems derelict, you can just ask us if you'd like this reopened

**Comment by nervere** [comment]
I spoke with kesto and he said he'd update this today.

**Comment by nervere** [comment]
PR author said they can't fix conflicts at the moment, so I will open a new PR with conflicts resolved.

**Pull request closed without merging**
