### PR TITLE
"Projectile" for shotgun blanks

### LINKED ISSUE #18069: Shotgun blanks are functionally no different from spent shells and can't be loaded
#### Description of issue
Shotgun blanks don't seem to have any function, even for making noise. They come out with the description, "this one is spent" and they cannot be loaded.

#### Expected behavior
Something like this I suppose.
https://youtu.be/t1on7ik5iZU

#### Steps to reproduce 
Make some blank shells at the autolathe and try to load them.

#### Thoughts
The current system requires a shell to contain a projectile to be usable. The easiest solution might be to put in an invisible one with a one-tile range. Possibly doing burn damage?

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Pathid**
Resolves #18069 

Made blanks work by giving them an invisible projectile with a range of one tile that does 10 burn. If anyone has opinions on how much damage this should do, or whether it should do any damage, feel free. Currently it's less than a welder does. Apparently the kill_count = 1 method doesn't let you shoot a diagonal tile either. Also the harm intent point blank shots don't work with shotguns right now it seems.

:cl:
* rscadd: Shotgun blanks work now, when previously they could not be loaded into anything. They may be for putting on a show, but they will do some moderate burn damage to someone up close.

### CODE REVIEW

**Comment by BurntDevil** [comment]
The concussive force of a blank would do more than just burn you. At that distance, I'd expect a bit of brute damage. Blanks are especially deadly at that range if directed at the head.

Food for thought.

**Comment by Chazach** [comment]
The concussive force of a shotgun shell to the head would kill anyone but you can slap a bandaid on and just walk out with a broken head in spess

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
May want to check if theres a way to disable its shrapnel

**Comment by Pathid** [comment]
I forgot to set embed to 0.

**Review by MadmanMartian — APPROVED** [review]

**Comment by SonixApache** [comment]
Blanks will very much still kill you at point blank, so maybe more'd be better...?
Getting your hands on  a shotgun is hard enough, so a higher number might not be too overpowered.
On the other hand, blanks are really cheap, so maybe upping their power wouldn't be a good idea?
I'd say toss it up to 20, maybe even 30.

**Comment by Pathid** [comment]
Something to keep in mind: Like I said, the point blank shooting feature guns have seems to be bugged for shotguns, making you melee instead. But if it were fixed it would let you turn 30 base damage into 39. Funny, I thought it was more than 30%.

**Comment by SonixApache** [comment]
It's making you melee again? I thought I fixed that.
*\*edit**
You have to be on harm intent to point-blank, by the by.

**Comment by Pathid** [comment]
I'm aware. Did not work when I tried it.
Edit:
Well, shit. It's working now. Nevermind then.

**Pull request merged**
