### PR TITLE
Guys I swear you, it's fixed for real this time. RIP Unsolvable Safe bug.

### LINKED ISSUE #29710: Yet another broken safe.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
bbba352827f0d8a6ffdc9b112ac5a3431fab7038

# Description
Plink on 140, plunk on 160. If I set the first tumbler, the second one unsets.
# Steps to Reproduce
Test with safes until you find another broken one.
# What you Expected
To be able to open the safe and get some goodies.
# What Actually Happened
PLUNK
CHINK
CLACK CLACK SCRAPE

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #29710

image

:cl:
* bugfix: Fixed a very rare bug (actually I've calculated that it had a 4.5 percent chance of occurring which isn't THAT rare) where the Safe's tumblers were set in a way that prevented players from ever cracking the Safe open. But this time for real. No really, I've tested it with extreme values and all that.

### CODE REVIEW

**Comment by DeityLink** [comment]
@boy2mantwicethefam ok so the tumblers having unlock position near 0 or 71 was irrelevant to the bug. The issue was the tumbler's unlock position being opposite or near-opposite of one another. The game now makes sure when randomizing tumblers to not let them be exactly 180° apart. Also them being 175° or 185° apart no longer causes an unsolvable safe either.

**Comment by ghost** [comment]
this is what, the seventh time now?

**Comment by ghost** [comment]
make a unit test

**Comment by DeityLink** [comment]
> 
> 
> this is what, the seventh time now?

until now it was only band-aids that we assumed might help. now I've done the _math_

**Comment by boy2mantwicethefam** [comment]
I hate coding

**Comment by help-maint** [comment]
7th

**Pull request merged**
