### PR TITLE
make snails less powerful

### PR DESCRIPTION
**Pull request by ShiftyRail**
You can walk through them

There's a hard headcount
A snail who mated can't mate again
There's a count on snail eggs

Frogs can now eat snail eggs

Sorry about that mess lads

### CODE REVIEW

**Comment by SageOfLight** [comment]
I feel preventing them from breeding again limits self-sustainability, I don't see why you'd prevent that if there's already a mob and egg limit?

**Comment by ShiftyRail** [comment]
fair point, goal was to make them rare

**Comment by boy2mantwicethefam** [comment]
Aren't they supposed to be global or something

**Comment by d3athrow** [comment]
snail station 13 when

**Pull request merged**
