### PR TITLE
Makes comm frequencies randomized at roundstart.

### PR DESCRIPTION
**Pull request by MadmanMartian**
still needs some TLC, ~~currently common tends to break~~ turns out a dumb freq_adder was being dropped, and that was expected to include common

 - [x] Librarian cheetsheet
 - [x] DJ cheetsheet
 - [x] AI notes

### CODE REVIEW

**Comment by plosky1** [comment]
Antags who sabotage telecomms rejoice.

**Comment by aceedex** [comment]
This kills the pAI

**Comment by boy2mantwicethefam** [comment]
Bruh

**Comment by RealestEstate** [comment]
good job on updating the librarian’s cheatsheet

**Comment by ghost** [comment]
Don't forget the DJ Station's cheatsheet, too, though.

**Comment by MadmanMartian** [comment]
And I've gotta remember to add the frequencies to the AIs notes, too

**Comment by Probe1** [comment]
Dope.

**Comment by tuypo1** [comment]
Yes please.

**Comment by calzilla1** [comment]
What does this do exactly?

**Comment by ComradeDispenser** [comment]
@calzilla1 Stops any moron with an SBR or access to an intercom from spying on security chatter from round start

**Comment by SonixApache** [comment]
and more importantly, fights the 'rainbow' chat spam that people like to do

@MadmanMartian no need to give the AI frequencies, they don't need then and they can just check telecomms anyway

**Comment by ArchSunder** [comment]
Poor detectives

**Comment by robosperg** [comment]
cheatsheet in telecoms control room as well

**Comment by MadmanMartian** [comment]
surprised and happy at the positive response so far

**Comment by ComradeDispenser** [comment]
Give the detective a cheatsheet too

**Comment by Durgen** [comment]
the assistant metaclub will remember this

**Comment by ShiftyRail** [comment]
I know that when I did this, I gave the dept. freq to the AI's mind and to the librarian's cheatsheet, as well as in the mind of the concerned departements.
Assistants will of course be able to PDA the AI in such a case.
Be extremely careful of frequency conflicts.

**Comment by MadmanMartian** [comment]
The only conflict I reckon may happen is traitor headset connections

**Comment by plosky1** [comment]
I'm not sure how AI radio works, does this work with it? You can toggle every department radio in your AI menu.

**Comment by jknpj** [comment]
soon

**Comment by MadmanMartian** [comment]
The AI one I'm still debating, as the way they get their frequencies is via the AI wiki page.

Why not have a borg read the paper, like with the telecomms access code?

**Pull request merged**
