### PR TITLE
snaxi: handful of pipe fixes

### PR DESCRIPTION
**Pull request by Inorien**
## What this does
- connects station waste loop to atmos waste handling

- adds missing waste pipe under morgue airlock to maint

- connects CMO office/breakroom/a hallway/mommi nest distro pipe to the rest of distro

## Why it's good
- station is able to remove waste gases

- a couple of rooms are connected to distro now, they weren't before

## Changelog

 * bugfix: Snaxi waste loop is now connected to atmos
 * bugfix: Snaxi missing waste pipe under morgue airlock fixed
 * bugfix: Snaxi medbay west distro is now connected to station distro

### CODE REVIEW

**Comment by Kurfursten** [comment]
Diffbot is showing a rollback of previous changes which is weird, since your actual diff isn't doing that

**Comment by Inorien** [comment]
> Diffbot is showing a rollback of previous changes which is weird, since your actual diff isn't doing that

That's very odd, I'll look at it a bit closer later today

**Comment by Kurfursten** [comment]
I do not think it's a problem on your end but it doesn't hurt to check

**Comment by Exxion** [comment]
It's probably because the branch this PR was made from is quite outdated.

**Comment by Inorien** [comment]
> It's probably because the branch this PR was made from is quite outdated.

yeah this is my theory, i guess its doing a shitty diff between my branch and target branch

**Comment by Exxion** [comment]
It's doing what is probably a correct diff between your branch and the target branch
Just do a rebase

**Comment by Inorien** [comment]
rebased and added a couple more missing pipes

there's some retardedness going on with the pipes in the middle of the place, i don't know what the rationale for this was but its very stupid - literally anyone can just turn off the pumps, same with a little room just to the south of this where anyone can just go in and start fucking with atmos stuff that should really be only in atmos
image
havent decided what to do with this yet but can be improved upon later imo

**Comment by DeityLink** [comment]
Beside making the doors require atmos tech access I think it's fine for there to be points of failure. Gives tators things to mess with.

**Comment by Inorien** [comment]
Agreed, I feel that goes beyond this cleanup PR so will see how much of an issue it is ingame before doing anything with it

**Comment by Exxion** [comment]
What's the purpose of that setup, anyway? You can either merge the pipelines or pump between them? Why?

**Comment by DeityLink** [comment]
Ok actually the more I look at it the less it makes sense. Who mapped that?

**Comment by Inorien** [comment]
> What's the purpose of that setup, anyway? You can either merge the pipelines or pump between them? Why?

its just strange
the person who reported that one (pancakemines) pointed out that literally all that does is hinder the other "stations" ability to remove waste gas, which is retarded, and the "workaround" for that must be the manual valve
it just doesnt make sense
what reason could there possibly be to introduce these, and why make them this accessible

i'm happy to call it what it is (retarded) and stop thinking about it until/if it becomes a real problem. there's talk (again) of impoving snaxi overall and i'm sure this will be early for the block

**Pull request merged**
