### PR TITLE
Insectoid Fashion Month 2 - Suits

### PR DESCRIPTION
**Pull request by PlausibleDeniability**
Part 2 of my insectoid spriting updates, the vast majority of easily accessable suits/coats now have a bug-specific sprite, be it adjusted to fit or remade from scratch, as there is 128 _(wew)_ sprites in this PR, I've just decided to take a screenshot of the DMI preview.  Happy to provide full previews of specific suits if people want.

Further, as I'm trying to be atomic, this is suits only, so there'll be some funny instances of the head counterparts to these suits looking off, but I'll be fixing all of these in the next PR which will be all hats.

dreammaker_4FHJfRF6XU

[sprites]
[qol]
[tested]

:cl:
 * rscadd: Created Insectoid sprites for the following suits: AutoDrobe, PietyVend, Winter Coats, Wizard Robes, common rigsuits
 * bugfix: There were a few insectoid sprites already in the DMI that didn't have its species_fit set, such as coatwarden, now working

### CODE REVIEW

**Comment by yclatious** [comment]
Get this man a fucking immediate merge, for we deserve not this level of dedication to spriting and content making. Absolute mad lad.

**Comment by Kharkov72** [comment]
how many sprites: yes

**Comment by SageOfLight** [comment]
Dressing my shrimp up for the grand ball.

**Comment by jknpj** [comment]
Ship it

**Pull request merged**
