### PR TITLE
Adds a radio transmitter room to deff.

### PR DESCRIPTION
**Pull request by Kharkov72**
Did you know that it didn't have one? Neither did I! I eventually noticed though and here we are.
[deff]
Untitled

:cl:
 * rscadd: Deff now has a room with a radio transmitter near the library.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I like the proximity to the library.

**Comment by PJB3005** [comment]
Maybe add a radiation warning sign?

**Comment by Kharkov72** [comment]
Untitled
I KNEW I missed something

**Comment by SonixApache** [comment]
also the reinforced floors

**Comment by SonixApache** [comment]
and a vault door with proper access reqs (just copypaste the tile from another map and check if the areas work)

**Comment by PJB3005** [comment]
I dunno man I like the idea of deff maint being a safety hazard and having the radio transmitter not properly secured.

There's a radiation warning, that's enough.

**Comment by SonixApache** [comment]
more of a style thing than a safety thing
could turn it into a broken vault door like all the broken airlocks in deff's not-maint, for flavor

**Comment by PJB3005** [comment]
Shit that might just make it more likely for people to be curious and get assblasted by radiation. Fund it.

**Comment by Kharkov72** [comment]
mmm, broken vault door
funding it
Untitled

**Comment by Kurfursten** [comment]
mapping conflicts

**Pull request merged**
