### PR TITLE
Fire_fuel sanity & other various ignition fixes

### PR DESCRIPTION
**Pull request by west3436**
## What this does

- Sets all obj fire_fuel vars to equal their w_class. 
- Things with no autoignition_temperature (fireproof) will no longer ignite. This prevents sparks from igniting things like mesons or bar stools.
- The nuclear authentication disk is no longer flammable.
- Storage items will now dump their contents on ignition to prevent nonflammable items from being deleted when the storage container burns up.

## Why it's good

Previous fire_fuel values were entirely subjective magic numbers assigned willy-nilly be each coder. Exceptions for things like sheets, items where fire_fuel = 0 on purpose, and structures & machinery were unaffected by the change. Using w_class provides consistency in that larger items result in longer burn times.

Additionally, the disk will no longer burn up or be deleted if the captain's backpack burns up.

## Changelog

:cl:
 * bugfix: Fixed things without autoignition values from spawning fires when hit by sparks.
 * tweak: Converted fire_fuel values for most items to their w_class.
 * tweak: Storage items will dump their contents on ignition.

### CODE REVIEW

**Comment by west3436** [comment]
Doesn't necessarily close #35874 but cut the fire_fuel value of all food items in half so it shouldn't get as hot.

**Comment by Eneocho** [comment]
guess that's a step in the right direction, thanks man

**Comment by west3436** [comment]
Need to test this more before I'm confident that it hasn't broken ignition

**Comment by ConfusedCactus** [comment]
> Doesn't necessarily close #35874 but cut the fire_fuel value of all food items in half so it shouldn't get as hot.

I don't understand how a pile of donuts catches fire from a flaregun being fired in the room. These things just shouldn't be so flammable.

**Comment by west3436** [comment]
> > Doesn't necessarily close #35874 but cut the fire_fuel value of all food items in half so it shouldn't get as hot.
> 
> I don't understand how a pile of donuts catches fire from a flaregun being fired in the room. These things just shouldn't be so flammable.

That is because the flaregun would ignite anything on the same tile as it which does not have an autoignition temperature. This PR fixes that.

**Pull request merged**
