### PR TITLE
xenoarch QoL

### PR DESCRIPTION
**Pull request by Intigracy**
You can no longer hit the energy field with things accidentally.

### CODE REVIEW

**Comment by gbasood** [comment]
not sure if needs changelog
is there a related issue?

**Comment by Intigracy** [comment]
No, I just experienced annoyance while doing xenoarch and have heard others
do so as well

**Comment by Midaychi** [comment]
I got around this issue by just not turning the field on until the last few steps, but sure I guess.

**Comment by PJB3005** [comment]
I got around this by not using the field at all.

**Comment by ghost** [comment]
Alt click the tiles for fun times of not accidentally clicking something on a higher layer or missing the object entirely.

Makes wiring solars a breeze

**Comment by ComicIronic** [comment]
If there turns out to be a reason you could click the field, this is getting reverted and you're getting repo-banned.

**Comment by Intigracy** [comment]
Well fuck you too buddy, thanks for mentioning a potential issue you had with it AFTER merging it.

**Comment by 9600bauds** [comment]
You could still altclick anyways :^)

**Pull request merged**
