### PR TITLE
Adds unique colors for dual eswords.

### PR DESCRIPTION
**Pull request by Cisrox**
All colors of e-swords (Red+red, blue+blue) etc. currently make a green dual e-sword. This change makes it so that, when you put a red and a blue e-sword together, you get a red/blue dual e-sword. It adds more logic and muh immershens to forming dual e-swords.

:cl:
 * rscadd: Adds unique color combinations for dual e-swords. The colors of the e-swords forming the dual e-sword determines this.
 * rscdel: Deleted dualesword1 sprite that was serving as a placeholder, it has been replaced by the new colors.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
Probably a long shot/impossible, but try using some color blending along with overlays so as to decrease icon bloat?

**Comment by Cisrox** [comment]
i'm new to this that sounds really difficult

**Comment by MadmanMartian** [comment]
Shouldn't be too hard in theory

- Make grayscale icons of the two energy blade segments (inhand and on-object)
- Get the color of the donor blades (let's store this as bladecolor)
- Make a new icon object (new/icon(icon file, icon_state) where it would point to the grayscale'd blade)
- use icon.Blend(bladecolor) (There's a few ways you can do bladecolor, best to have rgb(redvalue,greenvalue,bluevalue))
- add the overlay to the sword
- Repeat for second blade

**Comment by Cisrox** [comment]
the e-swords have animations though, are overlays possible with the animations?

**Comment by MadmanMartian** [comment]
Yes, grayscale gif

**Comment by aceedex** [comment]
Thanks doc

**Comment by RemieRichards** [comment]
Don't use ```/icon``` for greyscaling, just use a ```/image``` and set its ```.color``` var, this will colour the image based on the image's ```.blend_mode```

**Comment by DamianX** [comment]
Are you going to do the overlay thingy or is this good to go?

**Comment by Cisrox** [comment]
been busy this week, still don't really comprehend overlays

**Comment by Cisrox** [comment]
@DamianX i guess it's good to go, if I figure out blending I can make a second PR

**Pull request merged**
