### PR TITLE
have to be on a valid turf (Not space) to be able to crawl

### LINKED ISSUE #16925: Something Needs To Change: Box Perma or Crawling
Found this in the thread. Tagging @hugh-g-rection and @MadmanMartian for obvious reasons.

Now I personally don't have a dog in the fight of which one we change but this isn't acceptable.

### PR DESCRIPTION
**Pull request by MadmanMartian**
As suggested by @TurboGay, now you can't crawl space-to-turf, has to be turf-to-turf.

closes #16925

### CODE REVIEW

**Comment by ShiftyRail** [comment]
This is a much better solution to just reverting it.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
This would make it impossible to crawl on asteroid and centcomm tiles, which would definitely be wrong.

**Comment by MadmanMartian** [comment]
It already was impossible to crawl on asteroid and centcomm tiles, as the tile you're crawling to needs to be simulated as well.

I'll add an is_floor macro if needs be.

**Comment by MadmanMartian** [comment]
IconDiffBot being drunk again

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
