### PR TITLE
Economy Reform 2019

### LINKED ISSUE #19025: Cardboarding non-custom vending machines is super broken
You know when you deconstruct a vending machine and it just deletes all the snacks inside?
Did you know you can preserve the contents by slapping the vendor with 4 cardboard sheets before deconstruction?
I bet you didn't because why the fuck would you
Anyways this spawns a "partial" vendopacks that you can use to rebuild the machine. However a vending machine constructed from a "partial" vendopack is fully refilled by any other "partial" vendopack, so...

1. cardboard a nazivend or something valuable like that
2. deconstruct and reconstruct from the partial nazivend vendopack
3. buy the guns until out of stock
4. cardboard discount dan vending machine and deconstruct it for a partial discount dan vendopack
5. refill nazivend with partial discount dan vendopack

Oh, and you can't refill the reconstructed vending machine from its original vendopack anymore, but when has anyone ever refilled a vending machine

### PR DESCRIPTION
**Pull request by Kurfursten**
**TL;DNR**: If you were none of these this PR only affected you by making things cheaper: _miner, person who used cargo department card to set vendor prices to 0, person who duped items with partial vending packs, person who used department account money_
**Miners**: Your progression is identical but you earn labor points instead of credits to spend at the mining vendor. You still get the same number of points and same costs at smelter/vendor.
**Department Accounts**: Now not loadsamoney but still twice your starting dosh
**Bugs**: Fixed

Long ago in 2300, Nanotrasen bought out the UK, so now the Great Britain Pound is used as company scrip. As a cost cutting measure, NT now pays miners in GBP. Additionally, they're cutting the department allocated funds to less ridiculous levels, but making the most expensive items at cargo more reasonable.

* Shuttle License 3000->750
* DIY Engine Kit 650->250
* Radiation Suits 500->150
* Secway 500->150
* Suit Modification Station 400->200
* Blood Drive Crate 1000->50

Most significant bug fixes were removing duping using partial packs and removing the ability of cargo to get stuff for free with the cargo account card. To this very day I curse WhiteHusky for giving us such a broken accounts system I have had to fix like 8 times already.

fixes #19025

🆑 
* rscadd: IDs can now have Great Britain Pounds (can be examined on card if you have any at all) used to buy labor rewards from vending machines. So far the only way to acquire them is from the smelter and only use is the mining vendor.
* tweak: Vending machine throw wire changed to malfunction wire. Instead of a trickle of free goods you will damage the machine for a 2% chance of dumping several goodies.
* tweak: Changed malfunction rates somewhat. Additionally, hurt leg effect can only be caused by kicking the machine, not any other kind of malfunction.
* tweak: Department accounts lowered to 500 (750 for station account)
* rscdel: Some accounts can be hidden from accounts database (shoal, slot machines, vendors)
* tweak: Lowered the prices of the most expensive things in cargo that were balanced around department accounts
* bugfix: Fixed a bug where Cargo was the department attached to public vending machines instead of the (unused) vendor account. This means Cargo can't set prices or be 100% reimbursed for buying things anymore.
* bugfix: Improved error message for payment when your card does not have a linked bank account (mostly trader relevant)
* bugfix: Fixed a bug where partial packs could be used on anything
* bugfix: Fixed a bug where vending machines would not be turned off by their turnoff effect

### CODE REVIEW

**Comment by kilozombie** [comment]
HAPPENING!

Notably, this will help if Raiders ever gets off the ground and the shitbirds get monetary rewards for theft. It also will help the current trader meta even if I've rarely seen birds get money with the Ssethtide anyways.

**Comment by mtpowell** [comment]
Change GBP to Good Boy Points or leave it as credits

**Comment by SonixApache** [comment]
testmerge

**Comment by Intigracy** [comment]
how dare you use that nasty currency

**Comment by bathosbathtime** [comment]
rest in peace weaponized vending machines, you were pretty neat

**Comment by beesil** [comment]
hotwiring an ID to the slots machine account is a FEATURE

**Comment by Kurfursten** [comment]
@mtpowell They are listed as GBP on the ID and vending machine, you can choose to interpret it as Good Boy Points if so you choose

**Comment by Tokanova** [comment]
no reason to mine anymore if all you can spend your gbp is the useless trash in the vendors

**Comment by kilozombie** [comment]
> no reason to mine anymore if all you can spend your gbp is the useless trash in the vendors

This is what everyone was afraid of and why this change hasn't happened until now: the miner metaclub

Newsflash: it was broken from the start and remains broken that you can utterly annihilate any other method of making money by mining some plasma for 20 minutes. It invalidated everything to do with the internal economy of the game and is only realistically used to jerk off and buy cargo shit.

**Comment by nuklearcellphoneg** [comment]
Why use a defunct currency?

**Comment by Intigracy** [comment]
`bugfix: Fixed a bug where Cargo was the department attached to public vending machines instead of the (unused) vendor account. This means Cargo can't set prices or be 100% reimbursed for buying things anymore.`

Probably for another PR, but I think it'd be neat if all GBP spent on the station (except to other people) was eaten up and put in a hidden centcomm account (stats!) with a small tax going towards the station's account.

**Comment by Kurfursten** [comment]
@Intigracy Yes, also the "irresistible rise" stat for credits will need to be adapted for the lack of miners earning literally millions of credits

**Comment by Sooose** [comment]
Lower spessmart and mining vend prices.

**Comment by Kurfursten** [comment]
Mining vend prices are now entirely paid for in GBP which are still earned at the same rate. The mining progression experience will not change at all.

Adjusting other prices (crates, vending machines, spessmart) belongs in its own PR. The only reason I touched these was because they would be completely outrageous after removing sources of inflation. Things like the shuttle kit costing around 4k credits EXPECTED you to have a whole department account or mining bux.

**Comment by aceedex** [comment]
Lmao 2 currency!!!!!!
No really if the point is to kill miner money shenannigans why not just balance ore payout and minivend pricing?

**Comment by Tokanova** [comment]
> Lmao 2 currency!!!!!!
> No really if the point is to kill miner money shenannigans why not just balance ore payout and minivend pricing?

to remove miners from the economy because they aren't allowed to make money of course!
time to make a miner union and go on strike

**Comment by Kurfursten** [comment]
Miners will still receive their periodic paycheck

This system allows Miners to retain the dick waving privileges since they can hold up their card and show off their 1,000,000 points

**Comment by iFlashYou** [comment]
Like someone would care about some shitty points and
>Pounds

**Comment by aceedex** [comment]
I dunno kurf that just seems silly. No one cares about the ebin big number but rather because you can do something with cash maybe sometimes.
Thats a silly reason to have another currency system. If the idea is to just make mining monies no fun allowed just rebalance payouts.

**Comment by Intigracy** [comment]
it's not actually called pounds anywhere, that's just kurf memeing, it's referenced as GBP everywhere

just call it good boy points in your mind

**Comment by ghost** [comment]
I didn't actually read the code or tested this, but after reading the summary:

1. buy something from any vendor
2. check account transactions from ID you used
3. change your ID account number to the destination account number from your transaction
4. withdraw money you just paid as paper money / use your newly created vendor account ID forever

Regardless of whether the above works, adding a third currency type (credits, coins and now GBP) is just snowflaking the problem away instead of solving miner pay.

**Comment by Kurfursten** [comment]
That's a good point, has an easy fix though now that you bring it up. Thanks.

**Comment by Intigracy** [comment]
How's that adding a new currency? Current space dollars are being renamed to GBP, and miners are using GBP in their machine.

**Comment by Kurfursten** [comment]
No, there seems to be a misunderstanding. The only place GBP are earned is at the smelter and the only place they are spent is at the mining vendor (for now).

However, it's not snowflake in implementation. The GBP system is designed flexibly so that it could be used for any sort of labor reward vendors in the future. It stores on IDs and any vendor can have GBP items added to their item list with no extra coding, just put them under labor_rewards instead of products.

**Comment by aceedex** [comment]
but like, why not just use cash for any of that?

**Comment by Kurfursten** [comment]
I wanted to avoid a situation where it becomes very popular for assistants to hack into the mining dock to buy a (now very cheap) protokinetic accelerator and jetpack -- and simultaneously not interrupt the current natural miner progression too much. Remember, as it stands, protokinetic accelerators are something you can afford after mining 5 plasma ores. If we used credits instead of GBP, to avoid fucking up the miner progression where they can get a couple guns early to protect themselves on the roid, PKAs would end up costing like $5. Contrary to common belief, they're still reasonably robust weapons even in a fully pressurized room and even better if you welderbomb first or have a whole belt of em. This system preserves the old mining progression perfectly intact but the economy is no longer inflated by miners walking aboard with hundreds of thousands of credits.

**Comment by LordMyroc** [comment]
For the miners who still want to be able to earn lodsamone, perhaps a method of exchanging GBP for credits at a ridiculous exchange rate might work.

**Comment by aceedex** [comment]
I unno kurf it really seems like putting splints and gauze on a band aid fix. If PKAs are the problem we should move em to the mining station like deff has and maybe talk about pricing more. like if miner income was knocked about 70% and prices by the same ammount, the PKA would be 300 bux, more than what most people spawn with

**Comment by ShiftyRail** [comment]
I just upvoted this for the GBP joke because it's a friendly jab at our best players (the Anglos)
Features such as hotwiring accounts and spamming objects if you hack the vendor properly should be kept, it only for vendmachine jails

**Comment by Kurfursten** [comment]
@aceedex Ultimately, even if miner income was reduced 70% it would be too little of a bandaid to reduce inflation meaningfully. You have to remember here the goal is to make miner income semi-comparable to the income of other jobs which means they should be earning about $50/15 minutes. If you have looked at the income off of smelting ore you'd know that we're looking at an ore value reduction so significant that it may as well be converted to no monetary value anyway (something like a 99.9% reduction for plasma ore). What @LordMyroc says is more reasonable. We could very easily put up something like 50 credits for 40K GBP and let miners buy some additional income without interrupting the normal progression of buying PKAs early.

@ShiftyRail We discussed bringing back the throw wire, but only for free items (custom vendors and vendors like sec/medical). I have to wonder if we could improve it somehow, even. For example, I might be able to make it so you can pulse the wire to change the direction it fires in, so that you can more readily control which way items are thrown for that kind of setup.

**Comment by Hoshi-chan** [comment]
Change "Great Britain Pounds" to "Good Boy Points" and you've got my thumbs up.

That being said, I don't think this rework goes nearly far enough. You're ignoring outliers like slot machines that can generate an absurd amount of income, and many crates that you'll be able to order one or two of now, at best. This also nerfs the effectiveness of the "doesn't tip" traitor item, since you can no longer order forty pizza crates with ease. Oh, and many spessmart items are going to become borderline impossible to acquire, as if finding the vault wasn't difficult enough as it is, now that there's no reliable way to farm money. Blob is also going to become _even more_ difficult without unlimited laser rifles.

This is a hot mess that addresses key issues, but not all of them, just like every other "economy rework" in the past. Rebalance _everything_ or don't touch it. Most importantly though, if you're removing the ability for miners to generate a bunch of dosh, you need to add a new way to manually acquire money besides robbing people or waiting around and hoping the round doesn't end in thirty minutes.

**Comment by Kurfursten** [comment]
In game they appear only as GBP. It is never spelled out.

**Comment by SGuivenne** [comment]
>Newsflash: it was broken from the start and remains broken that you can utterly annihilate any other method of making money by mining some plasma for 20 minutes.

Isn't The Station supposed to be a Plasma Research and Harvesting Station explicitly supposed to be sending Plasma to NT?  Like at this point if you're going to punish this you may need to change this.

**Comment by Kurfursten** [comment]
Miners are not being punished, they still receive the same wages as everyone else. They do not receive any penalty for being miners.

**Comment by kilozombie** [comment]
Folks commenting that miners should be fairly compensated for the amount of work they do and not as a wage have never worked a soul-crushing job

- yours truly, somebody who has never worked a job

**Comment by SGuivenne** [comment]
The thing is, the wages don't actually encourage miners to mine.  The fact that you can go out mining and come back with a ton of money because you mined is what encourages miners to actually do their job, at least early in, so that they can fuck off into space as millionaires or go pokemon training or go raid vaults.  

If this occurs robotocists generally can straight up just build mining borgs at that point

**Comment by kilozombie** [comment]
GBP can already be used for the pokemon training aspect, but maybe it should be less of a miner-exclusive thing and more of a secondary currency for space expenditures?

Keep everything NT-endorsed paid for with credits (aside from the mining vendor), but have GBPs be usable in more alien contexts (vaults, especially Spessmart) and obtainable in vaults for the average spess explorer?

**Comment by Kurfursten** [comment]
I just don't get the "miners won't mine if they aren't being paid" argument. They can't get any of their normal guns/progression without doing mining or any of their toys like pokeballs, or any protolathe shit they gotta bring in minerals for.

Not to mention that no other job on the station is staffed exclusively by sociopaths who refuse to do the job they signed up for unless they're paid on an inflationary scale.

**Comment by kilozombie** [comment]
I only play chef if I'm paid exorbitant amounts of cash for every piece of pizza I create

**Comment by aceedex** [comment]
for me personally its "loadsemone is a fun part of the job, I dont like fun being taken away"
specially since dare I say, it doesnt break anything too hard, as the most common use for cash is ordering a pizza  when the chef dont wanna cook

**Comment by Kurfursten** [comment]
You can still have a really big number on your card, and even continue buying food with it like the peppers in your vendor.

**Comment by kilozombie** [comment]
>specially since dare I say, it doesnt break anything too hard

I don't know how you can enter a github thread and miss the point so hard.

The reason that loadsamone doesn't break much right now is because introducing anything economy-based would instantly break because miners shatter all the statistics

**Comment by jknpj** [comment]
It's simple: we remove miners and give their outposts to xenoarch

**Comment by AI-Is-Rogue** [comment]
This post was made by the Xenoarch gang

**Comment by Intigracy** [comment]
It is impossible to do anything economy related in this game because of the miner gang that always comes out and bitches incessantly about removing the ridiculous money injection they receive from mining things.

Everything about mining is the same after this PR except that they don't get money, they get GBP to spend at the mining vendor. Costs/income are exactly the same as before, you just can't mine for 20 minutes and start buying absolutely everything from cargo.

**Comment by Tokanova** [comment]
>you just can't mine for 20 minutes and start buying absolutely everything from cargo.

And what's wrong with that? Is a miner not owed the sweat of his brow?
Why should miners mine, if all they get is ridiculed with this 'good boy point' bullshit? The vendor stuff is nice but it's mostly trash that is invalidated  by just taking some diamonds to science and getting much better things there.
Miners mine for CASH, not for toys. We WANT to be the stations big spenders, tossing around our wallets to get what we want, it's part of the miner fantasy of spess. I want to be able to buy out the warden with a fat stack of ten thousand credits to get people I like out of jail, or to get some guns. Tossing cash at people to solve problems and such.

Miners like big numbers, but the numbers have to mean something, not just be a useless non-resource.

**Comment by jknpj** [comment]
>Is a miner not owed the sweat of his brow?

Saying that mining is a hard job to justify being entitled to low-effort economy-breaking amounts of money is bullshit. You can get your diamond drill and ore loader in less than 10 minutes, then strip the entire asteroid just my mashing your awsd keys(while ruining the xenoarch's job).

**Comment by LordMyroc** [comment]
>Why should miners mine, if all they get is ridiculed with this 'good boy point' bullshit?

This may come as a surprise but there's several dozen other jobs on the station that generally have no problem with doing their job despite not being paid a king's ransom for it.

**Comment by Kurfursten** [comment]
See child PRs, this has been broken into parts and some issues addressed

**Pull request closed without merging**
