### PR TITLE
Two new Costumes

### PR DESCRIPTION
**Pull request by Arthurdentist**
additional costumes
aviator finished

freedom2

### CODE REVIEW

**Comment by CptWad** [comment]
:+1: :us: :+1:

**Comment by Probe1** [comment]
http://www.youtubemultiplier.com/516cde3d4e79a-sweet-american-baby-jesus.php

U S A U S A U S A

**Comment by ComicIronic** [comment]
Conflicto.

**Comment by SkowronX** [comment]
Conflict with https://github.com/d3athrow/vgstation13/pull/3146/files
Update dem dmis

**Pull request closed without merging**
