### PR TITLE
Logs borer EMPs

### PR DESCRIPTION
**Pull request by Kammerjunk**
These are the arguments in the EMP proc: `proc/empulse(turf/epicenter, heavy_range, light_range, log=0)`
Borer EMPs were specifically set to _not_ be logged: `empulse(get_turf(src), 1, 2, 0)`
I can't think of one reason to do this. It now gets logged in the same way regular EMPs are logged.
image
The EMPs caused by hamserum are also logged now. It'll probably never be relevant given how rare potent ham is, but at least it's not 100% unlogged EMPs now

I couldn't find any existing issues about this, but GitHub's searching seems a bit clunky.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
I didn't specifically intend for them to be unlogged, I just took the empulse that hamserum used since initially their EMP ability *was* just injecting hamserum. I didn't realize that hamserum used an unlogged pulse.

**Comment by Kammerjunk** [comment]
Hamserum isn't logged either?

**Comment by Shadowmech88** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Reagents.dm#L5032

**Comment by Kammerjunk** [comment]
So it isn't. I dunno why it wouldn't be so I'll just add that until someone tells me I'm retarded 🤷‍

**Comment by Shadowmech88** [comment]
May want to change the title/description to reflect the additional changes.

**Pull request merged**
