### PR TITLE
Make Wizard not low-pop gamemode

### PR DESCRIPTION
**Pull request by MusgardTiger**
Wizards are way too destructive for low pop, with spells like blink, fireball, ethereal jaunt and pretty much anything else they can shit all over a low pop round and turn it into wiztended. Which isn't fun for anyone.

20 readyups will be better for everyone so when one or two players die the crew isn't suddenly left with 8 active crewmembers.

### CODE REVIEW

**Comment by SonixApache** [comment]
wiztended is gaystended
I think 20's a good number, especially since #15439 happened. 20 players is limit shared only with lings, far as I can tell.

**Comment by Kammerjunk** [comment]
Wiz dead = pseudoextended = extended but everyone is worried another wiz is gonna come
2 wiz = less risk of all wizzes dead = less risk of pseudoextended

**Comment by ihadtoregisterforthis** [comment]
How many gamemodes are left for under 15 lowpop deadpop?

**Comment by MusgardTiger** [comment]
Traitor (and double agents I think), vampire, cult.

**Comment by DamianX** [comment]
remember to update the wiki

**Comment by ghost** [comment]
Yeah, honestly, ever since wiz got multiwiz the mode was basically fucked since it's near guaranteed that one of the other wizards is a nigger so there's 0 chance of mid level antagonism as a result.

Maybe a solowiz spawn should be added to 3hr+ random event chances?

**Comment by SonixApache** [comment]
@SarahJohnson489 sure, just code antag datums real quick

**Comment by Killette2** [comment]
Yeah fuck wanting to be a fun wizard and then finding out the other fireballs himself in the bar, causing atmos breach and starting a witch hunt.

**Pull request merged**
