### PR TITLE
Zam Repackaging and Rebalance

### PR DESCRIPTION
**Pull request by Optimism333**
## Intro ##
**(Skip to THE MEAT if you just want to read the pr changes)**

When I initially added the Zam meals to the cargo merch computer in my first grayy food pr, I didn't give it as much thought as I should have. Upon further reflection since then, I think that while the meals themselves are not unbalanced as an article in the game as a whole, they're definitely unbalanced within the atomic environment of the merch computer, especially if you're playing a grey. 

There's little reason to pay 75 credits to get a Fast Food (XL) meal with 20 nutriment and condiments when a Zam Steak and Nettles only costs 70 credits but contains 21 nutriment and 5 doctor's delight. The fact that Zam meals need to be microwaved before eating isn't enough of an inconvenience to justify this. I've noticed lately that when I play a grayy, I never find myself hesitating over the choice of whether to buy Zam or fast food from the merch computer, because Zam is just the superior choice (both in style and substance).

With the above in mind, I've decided that the Zam foods on the merch computer need a nerf. Less substance and more style overall to make them a nice luxury to get for ayy roleplay, but not objectively better than the fast food that can also be bought from the merch computer.

## The Meat of the PR ##

The primary intent of this pr is to nerf the Zam meals that can be bought from the cargo merch computer so that they're not objectively better than the Nanotrasen fast food meals. The three meals have had their small amounts of medicine removed and their nutriment content slightly reduced (they don't make them like they used to). Regular Zam biscuits have also had their nutriment content slightly reduced, although they still contain a small amount of hyronalin. The prices haven't been changed.

### Zam Food Nerfs ###
Foods have been changed as follows:
* **Zam Steak and Nettles** --> 18 total nutriment when microwaved (instead of 21), No longer contains 5u Doctor's Delight
* **Zam Mothership Stew** --> 15 total nutriment when microwaved (instead of 18), No longer contains 5u Alkysine
* **Zam Spider Slider Delight** --> 12 total nutriment when microwaved (instead of 15), No longer contains 5u Dylovene
* **Zam Biscuits** --> Regular Zam biscuits now only contain 3 nutriment instead of 4 (same as a donut). They still contain 3u Hyronalin.

### More Style ###
Even though the nerfs above may seem a bit harsh, don't despair ayy players and grayy food enthusiasts. To compensate for the nerfs in nutriment numbers and useful chems, I've done something I probably should have done when I first added these.

Screenshot (739)
* All the Zam microwave meals now come in a food bag with a drink, an acid-resistant teflon fork, a packet of soy sauce (made from the freshest sulphuric acid), and a packet of malt vinegar (less acidic but probably still agreeable enough for a grey palate). Now you can eat your meal in style... right after you find a microwave to cook it in.
* Thanks to Deity for coding these nifty condiment packets in the first place.

## Closing Thoughts ##
- I'm sure the balance of these meals still isn't perfect, but hopefully it'll be in a more reasonable place after these changes.
- Please give feedback if you have some. I'm happy to read it and accommodate any reasonable requests if I can.

:cl:
 * rscadd: Zam microwave meals at the cargo merch computer now come with a drink, soy sauce packet, malt vinegar packet, and utensil. Microwave still not included.
 * rscdel: Zam microwave meals all contain slightly less nutriment and no longer contain medicine due to mothership lab cutbacks.
 * rscdel: Regular Zam biscuits contain one less nutriment.

### CODE REVIEW

**Comment by Kurfursten** [comment]
>microwaving a fork

It would also be cool if raising the temp of the meal cooked it as an alternate to the microwave, but I guess Grey food is the most retrofuture aesthetic so more than anything else it DOES make sense to rely on microwaves

**Comment by Optimism333** [comment]
> > microwaving a fork
> 
> It would also be cool if raising the temp of the meal cooked it as an alternate to the microwave, but I guess Grey food is the most retrofuture aesthetic so more than anything else it DOES make sense to rely on microwaves

Yeah... making the boxes a microwavable food item was the easiest shortcut for me when I originally coded them in because I was still very new to food coding (all coding, really). Maybe in the future I'll consider an alternative to microwaving, but it works well enough for now.

**Comment by Eneocho** [comment]
Pure Sulphuric acid does corrode stainless steel though. If nothing else it should be a Teflon fork (just rename a normal plastic fork).

**Comment by Optimism333** [comment]
> Pure Sulphuric acid does corrode stainless steel though. If nothing else it should be a Teflon fork (just rename a normal plastic fork).

Would a teflon fork not also be a different color than a normal plastic fork? Or should it just be the same aside from a different name?

Edit: Also, couldn't it be a renamed metal fork with a slightly different appearance and a description that's something like: "A metal fork with a teflon coating to resist corrosion from acids"

**Comment by Eneocho** [comment]
That's what I was thinking of, honestly. Just make a child of the plastic fork with a new description and name.

**Comment by Optimism333** [comment]
> That's what I was thinking of, honestly. Just make a child of the plastic fork with a new description and name.

Alright, done. The food bag now comes with a plastic fork with a darker sprite and unique description (also updated the screenshot).

**Comment by Optimism333** [comment]
Messed up my changelog... it was supposed to be rscdel, not rscadel. Oh well.

**Pull request merged**
