### PR TITLE
Allowed most living mobs to whisper

### PR DESCRIPTION
**Pull request by DamianX**
I excluded MoMMIs and borers, not sure if I'm forgetting anything else.

:cl:
 * rscadd: Most living creatures can now whisper, not just humans. This includes personal AIs, cyborgs, and Ian.

### CODE REVIEW

**Comment by Durgen** [comment]
Borg creep?

**Comment by spoonylove** [comment]
Should borgs and such have a special emote when doing so? Something like R.O.B.U.S.T adjusts it's volume"******"

**Comment by Dacendeth** [comment]
before nymphs could whisper with the whisper verb, but the :w shortcut didnt function, does this do anything for that?

**Comment by DamianX** [comment]
@Dacendeth can't reproduce, nymphs (tested at all growth stages) can't whisper at all, not with .w, not with the verb. With this PR they can whisper using either, although the default language is not respected.

I'm closing this because the allow-all-by-default approach is already proving to be a nightmare, there's a lot of copypaste, and there are bugs that I'd have to fix. Fuck it, I might come back to it at a later time.

**Pull request closed without merging**
