### PR TITLE
Trade Window

### PR DESCRIPTION
**Pull request by Kurfursten**
[There are a BUNCH of pictures in below comments, I encourage scrolling down]

image

What Traders should have had all along instead of a half-assed vending machine. The Trade Window is where you stock up on all merchandise (things like PDA and coat still come from the vendor). It's not hackable, it's not movable, it's not scannable. But it is a completely new way to acquire goods.

### Market Flux!
Traders operate on a complex system of fluctuating prices. Every 30 seconds there is a 3% chance that all prices will be shuffled from -20% to +20% from their base price. This encourages traders to buy low at ideal market conditions.

Operate on respect. Traders who form a business relationship with their supplier will get a better discount. -1% prices per 100 credits spent at the window, up to 10% at 1000 credits or greater.

Contribute to the Shoal. Traders who bring in nothing for the shoal are worthless. Every 250 credits in the Shoal account will give a discount of 1%, up to 20% at 5000 credits.

🆑 
rscadd: Traders now get goods from a trade window with fluctuating prices.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
A tentative thumbs up.
I like it more thematically and the extra discount mechanics are a fun idea. I also like that it will somewhat prevent traders from receiving constant unbwoinkable round removal in the form of vendor theft/destruction. 
I don't like that you can't bring it on your ship. Making shopping less convenient for people is going to reduce how often traders are used. I also don't like that it, assumedly, means limited items that were previously circumventable by mechanic scans will now be entirely limited. Finally, and this is minor, but if I have a traitor gimmick that requires a trader item without a trader existing I could, previously, buy an emag and get the items that way. This won't let me do that.

Two recommendations based on this:
- Add an in-game shopping catalogue. I never liked that we're mostly forced to just assume all traders have identical goods and know exactly what's in their vendor. Usually I make up some nonsense about receiving their catalogue in my mailbox every week. A real one would let you see what's discounted, order items from it, etc. So it would benefit RP but also mitigate the inconvenience factor. 
- Include a restock chance in the discount mechanic. Have it function similarly, based on the money the trader has and even on the same timer. So it's not a fully controllable restock like the mechanic scan, but it is a goal/option. That's also extra incentive to earn a profit which seems like a big focus of this PR.

**Comment by gurfan** [comment]
>nanoUI

get with the times

**Comment by Kurfursten** [comment]
You can make your own catalogs on a piece of paper, and I encourage you to -- there's even a stamp to stamp your work! As for your other complaint that people assume what traders have, that's only half true, it's a compromise. The variety packs like Alcatraz or Cloud IX ensure that there's some degree of randomness (e.g.: no, I don't have a HECU mask) but also ensure that you CAN eventually get the item you're looking for. I really like this system because variety packs encourage you to get a bunch of stuff at once and then market what you have without knowing what it will be -- this is totally different than getting a request for a specific flatpack and then just being the middleman. Market flux plays into this: buy crates when they're cheap and then market whatever you happen to end up with.

I do hear you on it being a pain to visit the outpost occasionally. I am not overmuch worried that this will decrease trader player count like you are - but I could see it being annoying. I am currently toying with a system where there's a bluespace chute in your ship and you can buy from the window remotely at a markup for convenience. It would also announce things like market fluctuations. This likely won't make it into 1.0, but I am committed to further developing the trade window idea. I have also discussed with BD about longterm even turning it into a proper NPC in a room -- but this is further down the line.

**Comment by Exxion** [comment]
So what happens if you bomb it?

**Comment by Kurfursten** [comment]
It would ruin immersions because it would blow away the turf under it. You pose a good point, I should just make the sprite take up a full tile and have it be a "booth".

**Comment by Exxion** [comment]
What would happen in *that* case if you bombed it?

**Comment by Kurfursten** [comment]
The window is now protected by a bunker-like safehouse so it's at the center of an explosion but unharmed.

I should say that because the trader within wants to see your face, it wouldn't be comfortable to continue doing trading until you restore air to the area (or at least some flooring). For more immersion, maybe I could get a "closed shop" sprite with shutters down until you restore at least a reasonable amount of atmos? That would be fantastic I think.

**Comment by Exxion** [comment]
Makes sense from a game design perspective. Irreplaceable object can't be destroyed, but it can be disabled such that it requires some effort to get working again.

**Comment by Kurfursten** [comment]
image
New improvements to the interface allow you to see what impact on price is coming from market forces and also from your past expenses.

image
Trade window will have fairly complex response logic, talking to you more like a proper NPC (name is generated) than just a vending machine. It won't be perfect, but it will add a little more depth with a variety of responses, which will get their whole own file. It even speaks in Vox (not necessary to understand Vox to trade though)

~~Speaking of which... should Mushtraders automatically gain Vox as a language?~~ All mushrooms know Vox by default, which is perfect.

**Comment by GreatBigFailure** [comment]
I agree with not letting it get easily destroyed, but if it somehow does then make it spawn gibs

**Comment by Blithering** [comment]
Or a live green chicken

**Comment by Kurfursten** [comment]
I will make it destructible in the future when I come up with a way to make it replaceable without admin intervention. Perhaps as part of a future patch like things I discussed above as long term ideas.

**Comment by githubuser4141** [comment]
> I will make it destructible in the future when I come up with a way to make it replaceable without admin intervention. Perhaps as part of a future patch like things I discussed above as long term ideas.

IIRC on Baystation there's a Merchant role that uses a computer with a teleport pad sitting next to it. Maybe this'd temporarily  work flavour/sprite-wise until a vox window can be sprited/coded properly?

**Comment by Kurfursten** [comment]
I actually already have an animated window sprite right now [pics in OP] that I'm pretty reasonably happy with (still needs some additional states like a flick for when you buy and a shop closed sprite though). Burnt was interested in an even more elaborate setup with an NPC on a full fledged shuttle that could happen someday - we'll see on that.

I should say that this sprite is a collaboration with the talented SageofLight. I provided a concept sprite and did touchups on the animation after Sage did detailing work.

**Comment by Viciousaurus** [comment]
Oy vey

**Comment by Kurfursten** [comment]
Today I added very complex greetings that recognize a wide variety of situations, including a range of initial greetings and midround greetings (no more than once per 30 sec).

Initial solo greeting examples
image
image

Solo greeting a latejoiner
image
Greeting a latejoiner who isn't the first there
image

Commenting on a trader who hasn't left but came back
image

Commenting on a trader who has been gone ages
image

You get the idea, it's modestly sophisticated

**Comment by Kurfursten** [comment]
New feature: sign up a new trader. They need a spare trader ID and to place it on the table. If accomplished, this will produce a trader application. This needs to be stamped and turned in by an existing trader. Done? That's all it takes -- you have been promoted from mushroom sprout to full trader!
image
image
image

**Comment by Kurfursten** [comment]
Conflicts fixed
Now closes when atmos conditions bad, opens when good (just needs pressure to be between 80 and 180)
Now flicks an icon when buying
Tested all these things

I'm going to call this 1.0-ready very soon, just needs mapping. For those of you sad about losing the borg modules in exchange for coins, that is coming back in the form of a new random modules box in a future PR. It won't be long.

Future plans include ways to influence market (coins?) and more intelligent responses beyond what it has now, but I am basically ready for this to go to live and we see how it works in the wild.

**Comment by Eneocho** [comment]
Vox with Wizard-style names? Surely you jest.

**Comment by SonixApache** [comment]
super cute

**Comment by Kurfursten** [comment]
> 
> 
> Vox with Wizard-style names? Surely you jest.

No, the adjectives used for these names come from an entirely different file.

**Pull request merged**
