### PR TITLE
Better, stronger than ever before! (New eswords)

### PR DESCRIPTION
**Pull request by kol1th**
# Scope of PR

Energy swords now use new, improved sprites that emphasize glowing rather than just pulsing blobs of color. 

**Yes, they're from TG. No, you cannot stop me.**

# For your Viewing Pleasure

image

image

image

image

# Changelog

🆑 
* tgs: Energy swords now have a new, improved sprite. Rejoice!

### CODE REVIEW

**Comment by Sprok0** [comment]
They look much shorter, like energy daggers or something

**Comment by kol1th** [comment]
Works on my eyes

**Comment by Lokiamis** [comment]
@Sprok0 
That is the original stance for energy swords. I made them criss-cross so they'd appear longer, but that was only ever on our server.

**Comment by kol1th** [comment]
Holding them away from you instead of in front of your face makes more sense to me, anyhow. Especially considering it's a *sword made out of literal hot light*.

**Comment by amikawaii** [comment]
it changes the toy sprites too right?

**Comment by kol1th** [comment]
It should yeah probably

**Comment by eplgr** [comment]
Any picture of someone holding the dual saber?
Also I'd suggest attaching a picture of the old e-sword for comparison. But yeah, the new ones do look...odd? Too short, maybe?

@kol1th They are made of plasma. Wait - can you actually call plasma "hot light"? I am not sure.

**Comment by kol1th** [comment]
I assumed they're just lightsabers

**Comment by eplgr** [comment]
Lightsabers ARE made of plasma. 

Also, plasma exists IRL.

**Comment by Exxion** [comment]
Plasma is an ionized gas, etc.

**Comment by ThePlapatin** [comment]
They look really short because they're pointed away which makes no sense as phoron energy swords don't emit heat except by contact, ugh read the lore?

**Comment by Exxion** [comment]
>phoron

\>>>/tg/

**Comment by 9600bauds** [comment]
The glowing is super sweet but damn they look shorter, I can't not see it now

**Comment by 9600bauds** [comment]
How would this look with the new item icons but the old inhands?

**Comment by Exxion** [comment]
Probably not good
But it's not like extending a straight line sprite is hard

**Comment by kol1th** [comment]
The old inhands are REALLY bad

**Comment by 9600bauds** [comment]
The current sprites go the other way, c
dreamseeker_2017-02-11_18-55-21
because logically if you point the sword away from you, it hits the 32x32 border and looks really short and you also won't block electrodes like that

**Comment by Exxion** [comment]
Yeah
You can just mirror and extend the new ones

**Comment by Lokiamis** [comment]
Mirroring and extending them is a time consuming bitch fyi

**Comment by Exxion** [comment]
Time consuming
But not hard

**Comment by kol1th** [comment]
I'll probably do it but definitely not right now.

**Comment by yclatious** [comment]
Make them criss cross, less clicking area and looks better.

**Comment by SonixApache** [comment]
misleading PR name
should be 'ports TG personal massagers'

**Comment by kol1th** [comment]
Quite a lot of spriting to do, i'll get to work on that

Also the dual energy swords were only ever green. 🤷‍♂️

**Comment by ThePlapatin** [comment]
Make them cross each other (but held behind yourself)

now that's cool and edgy, a true syndicate tool.

**Comment by SonixApache** [comment]
@ThePlapatin at least goof is funny when he shitposts

**Comment by Probe1** [comment]
aint nobody like it like that

**Comment by kol1th** [comment]
Maybe I'll fix this later who knows 🤷‍♂️

**Pull request closed without merging**
