### PR TITLE
Makes space not cold

### LINKED ISSUE #7890: Hypothermia was a mistake
Went out in the cold, got slow, passed out, eventually died. Then realized.

How is one supposed to space walk from perma to safety? It's impossible due to hypothermia.

### PR DESCRIPTION
**Pull request by clusterfack**
Thought I'd put it out there and see what people actually think about this.
Fixes #7890

Does not affect radiating from pipes (because it wouldn't in real life anyway come on people)

### CODE REVIEW

**Comment by DrCelt** [comment]
May want to add this only affects humans for the purpose of heat transfer and pipes are not affected.

**Comment by Shadowmech88** [comment]
:+1:

**Comment by DrCelt** [comment]
I'm sure there's a variable that affects pipes and stuff but I wouldn't mess with it.

**Comment by PJB3005** [comment]
Does this break H/E pipes on space though, if it does I say we need to make H/E pipes an exception.

**Comment by DrCelt** [comment]
@PJB3005 I told cluster he should add that to the OP

**Comment by 9600bauds** [comment]
Well I mean, it was the second comment, too

**Comment by PJB3005** [comment]
I'm an idiot!

**Comment by 9600bauds** [comment]
Happens to the best of us buddy

**Comment by NigglyWiggly** [comment]
Removing a major spess cliche from SS13 for the purposes of muh realism is silly and unnecessary
Regardless of the fact that space isn't cold, SS13 is built on movie and book cliches and shit, and having space be frigid is a major part of that

**Comment by AutismSpider** [comment]
Better sub in radiation for taking out the cold then.

if your going for this ebin realism shit

**Comment by dylanstrategie** [comment]
I'm fine with it, depressurization already kills well enough as it is, maybe a small buff, but nothing more

**Comment by 9600bauds** [comment]
And Diona everywhere rejoiced as they jumped out an airlock

**Comment by PJB3005** [comment]
:+1: to this for realism by the way.

**Comment by DrCelt** [comment]
It may be useful to note that if space isn't cold, local testing found that breaking out of perma and escaping to arrivals unassisted by chemicals was not difficult. I'd not go halfhearted on this, and make space more deadly in other more realistic angles. If that's what you're going for. Personally I think @NigglyWiggly may be right on this one though.

**Comment by clusterfack** [comment]
Space radiation

**Comment by DrCelt** [comment]
Code it

**Comment by DrCelt** [comment]
Oh yeah and you may want to make it actually hurt Diona. It doesn't, presently.

**Comment by PJB3005** [comment]
@clusterfack that's more an effect of low pressure isn't it?

**Comment by clusterfack** [comment]
That it is

**Comment by ihadtoregisterforthis** [comment]
As I suggested in the issue, make space not cold but make it increase dramatically the loss of heat because of science pomf explained in the hypothermia PR.

**Comment by Shadowmech88** [comment]
@ihadtoregisterforthis Mind copypasting it here? I don't want to wade through 420+ comments.

**Comment by ihadtoregisterforthis** [comment]
>you lose heat in space from rapid evaporation of surface moistures, when that's gone you'll slowly overheat as your body can't regulate temperature but you'l lbe dead before then.

**Comment by Shadowmech88** [comment]
From a gameplay perspective, would there be a significant difference between space being cold and space not being cold, but causing you to lose heat quickly?

**Comment by clusterfack** [comment]
No

**Comment by ihadtoregisterforthis** [comment]
It would mean cold space but from a different approach. Effects of cold space on the body in function of time instead of warm or 0k. It would keep danger as oposed to wearing the CE hardsuit helmet and spacestreaking.

**Comment by clusterfack** [comment]
In the game right now you can survive in space an exceptionally long time because the effects of pressure ingame are practically negiligible, whereas in real life they would be the strongest factor contributing to your inevitable demise.

Also the temperature of your body rising/lowering would be almost entirely dependent upon how close you are to a sun, and even far away the rate your body would be chilling is slow.

**Comment by gbasood** [comment]
since it's technically a balance thing right now, I think this is the sort of thing that should wait until after freeze????

**Comment by DrCelt** [comment]
Add a changelog, can't have a change like this without it. For what it's worth I'm erring on the side of caution and not super in favour of this PR.

**Comment by Exxion** [comment]
Why is this a define rather than a config option, anyway?

**Comment by clusterfack** [comment]
Celt couldn't into configs I guess

**Comment by DrCelt** [comment]
I have no clue what configs are or how to change them, so yeah, @clusterfack is right.

**Comment by DrCelt** [comment]
This needs to buff pressure damage before it's merged or you'll be able to walk in space for miles.

**Comment by 9600bauds** [comment]
Forever, in the case of Diona

**Comment by SonixApache** [comment]
space is not cold

**Comment by NigglyWiggly** [comment]
@SonixApache 
And Vampires, Wizards, Changelings, giant spiders, the cult of Nar-sie, space-carp, plant people, cat people, so on and so forth aren't real.

As I've said before, SS13 is practically built on science fiction cliches, and space being really cold is one of those very common cliches.
Regardless of if it isn't true, it's part of the general science fiction atmosphere that spess has going for it, and it adds to the gameplay by making space itself dangerous in more ways than one.

**Comment by Cutelilduck** [comment]
But space is cold senpai. You don't literally freeze before you die of decompression / oxygen, but spess IS cold. 

I just don't get it. Exposure is relatively balanced the way it is and its inconveniences has prompted us to fix breaches and stay in the station. Now when someone bombs the bridge you're telling me I can flop open the airlock, run through at full speed, and pop a Dexalin every now and then from the many emergency packs and not give a fuck? 

Freezing speeds is a severe annoying downside. It feels spacey. We don't have decompression sickness or severe pressurization penalties or radiation poisoning so we need something.

Removing such an integral part of the game without an equally balanced alternative is just dumb. Escaping through the airlock and running around the station is now a valid strategy. Perma is ded. The implications will never be the same.

**Comment by Shadowmech88** [comment]
Vacuums can't be hot or cold, since temperature is a property of matter and vacuums are devoid of matter.

**Comment by clusterfack** [comment]
This PR was made partly due to the fact perma is inescapable entirely due to hypothermia knocking you out almost instantly.

**Comment by DrCelt** [comment]
Perma was already inescapable partly due to cold. If this addition is added, perma will be escapable by anyone.

**Comment by clusterfack** [comment]
I'm saying the 'delicate balance' of space being cold was already *raped in the ass* by the hypothermia changes.

**Comment by 9600bauds** [comment]
p much

**Comment by gbasood** [comment]
Do we actually want this still

**Comment by clusterfack** [comment]
Of course

**Comment by Probe1** [comment]
wait what

you want to fix hypothermia being weird by FUCKING EVERYTHING ELSE UP?

did celt steal your account?

**Comment by 9600bauds** [comment]
Smells like baked potato

**Comment by gbasood** [comment]
@Probe1 I think the current plan is actually to make space's lack of pressure fuck you up as much but you'd have to bug @clusterfack about that

**Comment by Probe1** [comment]
:eggplant: all around.

**Comment by ComicIronic** [comment]
Close?

**Comment by dylanstrategie** [comment]
Don't see why, unless @clusterfack believes he doesn't and won't get support to merge it

**Comment by clusterfack** [comment]
I believe with the right changes this will satisfy a majority of people. People want a system that will still slowly incapacitate people in space. 

The only thing that hasn't been fully worked out is the ideal combination of detriments to being in space.

I think modifying pressure damage to do more types of damage to you would suffice.

**Comment by 9600bauds** [comment]
The first and foremost question here: Should space be deadlier than a breach?

**Comment by dylanstrategie** [comment]
It should be as deadly, pressure damage is the only factor here

**Comment by Shadowmech88** [comment]
We could add cosmic radiation as a detrimental effect to direct space exposure that makes sense.

**Comment by clusterfack** [comment]
What WOULD be the difference between space and a breach, space radiation aside.

**Comment by 9600bauds** [comment]
Don't think with your realisms, think with your gamesense
Space killing you too slow makes space exposure a joke
0kPa killing you too fast makes breached rooms retardedly deadly, especially combined with ZAS
If you make both the same thing, then either of them would be pretty shitty, or both of them would be shitty-ish.

**Comment by clusterfack** [comment]
BUT THAT'S WHAT SPACE IS YOU DOUBLE NIGGER

**Comment by clusterfack** [comment]
ITS NOT MAGIC

**Comment by Shadowmech88** [comment]
Aside from space radiation, there wouldn't be a difference between a breached room and open space.
Which is why I think space radiation should be a thing if we make space tiles not cold.

**Comment by AutismSpider** [comment]
Space radiation slowly take burn and toxin damage

**Comment by 9600bauds** [comment]
The sun burns your shit via UV light or whatever.
Bam, we went from space being brute+burn to space being brute+burn but not cold.

**Comment by Senaat1** [comment]
Wouldn't technically the position of the sun relative to the station matter a lot? No clue how hard/impossible this'd be to code but if you're in space and exposed to the sun you're going to heat up very, very quickly.

If you're in the station's shadow you'd be cooling down, thermal radiation still works in a hard vacuum.

Would it be possible to implement a system based around the realistic positioning and movement of the sun?

**Comment by Senaat1** [comment]
That'd also mean floor breaches would (possibly) cool down a room whereas breached windows would heat up a room if the sun is in the right position.

This sounds super lagtastic.

**Comment by dylanstrategie** [comment]
Right, if you are exposed to the sun a part of your body would heat up extremely quickly, which would be quite bad

**Comment by Senaat1** [comment]
I imagine a realistic system of a sun would be nearly impossible to pull off in SS13, considering you'd have to model the station's orbit around the...gas planet? it orbits and the station would spend a lot of time in the shadow of the planet. According to celt the current way the sun is handled (for solar tracking) is by just having it rotate around the station which is pretty fucking funny.

**Comment by 9600bauds** [comment]
Vampires already get burnt to a crisp by the sun if they step over any space tile, right?

**Comment by AutismSpider** [comment]
@9600bauds yup they burn to death if they step in space tile sunlight/starlight hurts them ton

**Comment by PJB3005** [comment]
So is this ever gonna happen?

**Comment by clusterfack** [comment]
I really just kept holding off on this because there is such a lack of concensus on how to make pressure deadly enough without being shit. I still think this is a very good idea though.

**Comment by Shadowmech88** [comment]
The problem with using pressure is that in order to mimic current balance, there needs to be a noticeable difference between space tiles and non-space tiles with no pressure.

If space isn't cold then, even IF we buffed pressure damage, there would still be no difference between standing on a space tile and standing in a breached room.

Which is why I now re-suggest my idea of some kind of cosmic background radiation. Only affects those on space tiles, and only harms the ones not wearing a hardsuit.

**Comment by SkowronX** [comment]
ded

**Comment by clusterfack** [comment]
I have no interest in solving everyone's concerns with this right now, perhaps some other time

**Comment by troots** [comment]
F

**Comment by gbasood** [comment]
space will never not be cold, rip

**Pull request closed without merging**
