### PR TITLE
skellington icon update, courtesy of niggly

### PR DESCRIPTION
**Pull request by ghost**
Ever, as a skellington, lose your head only for it to be thrown into the clean white floors of medical, and it become lost forevermore in that white void?

Worry no longer. Now there's some actual bloody detail to the sprite. Courtesy of @NigglyWiggly 

skellington_comparison

Old on left, New on right

### CODE REVIEW

**Comment by Bilgecrank** [comment]
I love the detail on that sprite.

**Comment by ihadtoregisterforthis** [comment]
It looks absolutely hideous. The color looks like a palette imported straight from another kind of game. Bones are naturally very pale, this is a fossilized skeleton from the moment the person melts. The current sprite is not the best but if you want to rework it actually rework it, don't recolor another race.

**Comment by ghost** [comment]
what took you so long?

**Comment by Zennyization** [comment]
I think the sprite is better but I dislike the colour change.

**Comment by ghost** [comment]
I guess the new one is a little dark

**Comment by Blithering** [comment]
Now all we need is liches

**Comment by Riekland** [comment]
I like that it's standardizing the skeleton to be the same general outline as a plasmaman but the colours are way too dark and shit
they really should be white and shit
maybe to help they could get a full body blood covering when they dissolve since it's literally flesh and shit sliding off them

**Comment by Megamaw** [comment]
i'd love this as an alternate option, like a skin color for skeletons

but i think that there needs to be a lighter 'skin' tone, too.

**Comment by NigglyWiggly** [comment]
>It looks absolutely hideous. The color looks like a palette imported straight from another kind of game. 

_That's exactly what it is_

Also the sprites are shamelessly taken from the original plasmamen sprites and recolored

**Comment by chatsonf** [comment]
Is this better
I fixed it

**Comment by Zennyization** [comment]
That's better in my opinion

**Comment by Megamaw** [comment]
hell y e a h

**Comment by Blithering** [comment]
Both palettes are good, first one would suit old bleached skeletons, while the second would be for the more recent skelebones

**Comment by NigglyWiggly** [comment]
I feel like that's the wrong way around, old ones are typically whiter because they get bleached by the sun or picked clean by animals and stuff.
That lighter palette looks great though, nice job Furbeh!

**Comment by ghost** [comment]
I've gotta bounce

**Comment by Shadowmech88** [comment]
Someone should remake this, it seemed like everyone liked the change.

**Pull request closed without merging**
