### PR TITLE
Reduced juggernaut dash max distance to 4

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * tweak: Reduced juggernaut dash maximum distance from 10 to 4.

### CODE REVIEW

**Comment by SonixApache** [comment]
i died pls nerf

**Comment by boy2mantwicethefam** [comment]
Yesn't.

**Comment by Accipitermaris** [comment]
i'm no code man but when i did a jugg dash in space i also flew indefinitely until i hit something, allowing for some truly impressive (and highly dangerous) moves. maybe it's different because it's not on turfs. pretty wild stuff regardless.
anyway, 10 tiles is more than a screen's length, yeah.

**Comment by DamianX** [comment]
yeah, that's a feature I guess

**Comment by iFlashYou** [comment]
make it 5 tiles

**Comment by plosky1** [comment]
If we're gonna argue about distance I'd say 5 or 6 instead of 4. As much as people like to argue Juggernaut is always used because OP, it's more like it's always used because the wraith just isn't good. Juggers die a lot even with the dash.

**Comment by DeityLink** [comment]
@Accipitermaris working as intended.

Either way make it 5 or 6. 4 is laughable. The point of this spell is to close the distance, especially since I've been coerced into nerfing the stun duration to barely a second.

**Comment by Caboozles** [comment]
I won't be satisfied until this rocket dash is removed. The last thing Juggernaut needs is more mobility. It's a fucking 250 HP tank with reflect that can create doors and punch walls down.

I have since cult 3.0's launch said it was stupid, and I will stand by it for as long as it exists.

**Comment by plosky1** [comment]
Juggernaut has the dash because it has no mobility. It's slow as fuck, the armor doesn't mean shit when you get lasered from down a hallway while you move slower than a snail, and more often than not your wall kills you rather than saves you. While a dash longer than your screen is too much, nerfing to 4 or even removing will absolutely gut the juggernaut. I still say nerf it to 6, see how it is and get feedback, then nerf more if needed. Also buff wraiths so that they dont suck, and you'll see less juggernauts.

**Comment by Caboozles** [comment]
Juggernaut has reflect, you need on average 2 or more eguns to take one down. You can't be stunned, can pop out of the jugg after dying and retreat (meaning they have to shoot you more), and most likely aren't the only jugg.
You also can heal up as long as you don't have a full ERT team shooting at you.

So unless we summon an ERT every time the bloodstones pop, you're going to have to accept that juggernauts aren't some flimsy poor machine. Juggernauts were extremely strong pre-cult 3.0 and that was never in contest. Nobody ever thought of ways to buff the Jugg.

**Comment by DeityLink** [comment]
They were strong at creating breaches and getting ignored yeah. I'd be more inclined to nerf their reflect/damage resist.

A 4 tile dash every 20 seconds is useless. This PR is basically removing the spell altogether.

**Comment by jknpj** [comment]
>eguns
>not using point-blank slugs to one shot them

smh

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
How is 4 tiles "basically removing the spell altogether", but 5 tiles is OK?
Instantly teleporting across 60% of the screen and knocking down on hit seems pretty good to me

**Comment by SonixApache** [comment]
Because you still have to slowly crawl to within half a screen's range of someone who is 3 times faster than you and can just kill you from range.
MUH EGUNS is a common sentiment but shotguns are widely used during cult and murderize the shit out of juggs.

**Comment by DeityLink** [comment]
This. Jugs also get owned by combat borgs and mechas. And the knockdown is shorter than slip on peel.

**Comment by SonixApache** [comment]
another victory for babbys

**Pull request merged**
