### PR TITLE
Fixes #6606

### LINKED ISSUE #6606: Cloning when ghosted
(WEB REPORT BY: tamassran REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
588c164d2c90c323deb3a7eb9df1b3e655beeddc

>General description of the issue
BWOINKED for cloner when I ghosted because like fuck am I gonna play a rev round

>What you expected to happen
Not get bwoinked when I was ghosted in a cloner and ineligable to resurrect/clone

>What actually happened
Got bwoinked yo

>Steps to reproduce if possible
Ghost -> Cloner -> Bwoink

### PR DESCRIPTION
**Pull request by 9600bauds**
tested&true

Fixes #6606

### CODE REVIEW

**Comment by PJB3005** [comment]
WCPGW

**Comment by RemieRichards** [comment]
@9600bauds 
Close your byond client fully.
Open the world via dream daemon, not dream seeker.
Join it, you'll be a guest
open your byond client
click the join button on dream daemon.
Bam 2 windows open for the same local server, with 2 clients.

**Comment by 9600bauds** [comment]
@RemieRichards I've been trying to do that for the better part of an hour, but every time I try to join as Guest, no matter from where, I always get "connection failed" or "connection died". I never got as far as the ban notice. If I can get it to work, that's a really neat tip though

**Comment by MrStonedOne** [comment]
uncomment your code for kicking guests

**Comment by 9600bauds** [comment]
@MrStonedOne that did it, I didn't even know we had such code since the connection failed screen was so vague.
Thanks people, I was finally able to test this PR and I can guarantee that it works. However, the ghost was still being bwoinked when put into the DNA scanner, and the defib would still revive the non-joinable corpse, which just goes to show how important testing your shit is

**Comment by RemieRichards** [comment]
our pleasure.

**Pull request merged**
