### PR TITLE
Balancing for borgs and EMPs. Made for @Isaac on Discord.

### PR DESCRIPTION
**Pull request by PJB3005**
I do not have any personal opinion on this, ask @​Isaac on discord for questions related to that. I just made this PR for him because he couldn't figure out git.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Should have escaped the @, now you've mentioned someone. Like we kept mentioning the wrong Skowron.

**Comment by PJB3005** [comment]
Ah fuck I screwed up, sorry whoever I pinged.

**Comment by PJB3005** [comment]
> Vim isn't accepting my ZWSPs

GODDAMNIT VIM.

**Comment by jakmak** [comment]
OK the intent of this change was to buff the effect ions had to cyborgs. Normally they do 20 organ damage and 5-10 seconds of stun if in the the center of the emp. If on the edge of the emp it would do 10 organ damage and 1-5 second of stun. This buffs the stun to 25-30 seconds if in the center of a emp blast and 15 to 20 if in the edge of a emp blast. As for damage it has been increased massively to make ions actual anti mechanic weapons. Center of the emp blast is from 50 to 90 organ damage and the edge of the blast is 25 to 45 organ damage to the cyborg.

**Comment by clusterfack** [comment]
Uh this is a pretty ridiculous stun

**Comment by AutismSpider** [comment]
30 sec stun lost your damn mind.

just up the damage keep it as 5 to 10 second stun.

**Comment by Exxion** [comment]
Keep in mind that an average everyday ion rifle can't hit a borg with a severity 1 EMP, if I'm not mistaken
You'll need an EMP grenade for that.

**Comment by AutismSpider** [comment]
@Exxion but it can if you do it up close means doing normal emp hit  or two then up close on the borg

Why this is retarded ion gun into laser gun and the borg done for this just makes so you only need two to three ion hits or flash bang into ion gun flash bangs stun borgs now and flash powder.

**Comment by Exxion** [comment]
There are
What
Three ion guns on the entire station roundstart?
And all of them are in the secure armory
Making them not actually 100% useless sounds like an improvement to me

That said, this might be a BIT excessive

**Comment by ihadtoregisterforthis** [comment]
Remember that the singularity also creates an EMP, and shards when they explode.

**Comment by AutismSpider** [comment]
@Exxion fine line form making them not use and to over power this does the later if people want make them not pain in the ass to use lower the size so they fit in bags.God damn E gun and Adv E gun look bigger then ion gun and both fit in bags when they should not

**Comment by SonixApache** [comment]
fuck on outta here

**Comment by ghost** [comment]
It's enough for even the light damage on the coinflip the emp system does at the border of hvy-light to break parts. Shard delaminations will have multiple chances to break a borgs actuator. Virtually instantly killing them for all intents and purposes.. There's a lot better ways to handle a problem borg even when you can't console lock or blow it. Mostly starting with ion repeatedly to disable to close in to  then flash and smash or remove cell and cut lockdown. or just alternate ion with a couple lasers/shotgun blasts until it's unsalvageable. Plus even flashbangs and flash powder work on borgs now cause of all the accumulated asshurt redtexts and deaf baddies downed by subverts. I feel it's a pretty harsh kneejerk over people who just can't handle borgs very well in the first place when you consider that the majority of robo's are incapable of reading the wiki so once you get broken parts that's it for you. In such a crisis that would result in getting broken components, many of the people who do know that you could ask for help are busy or dead. Borgs don't need more time repeatedly bouncing into the rack with the borg analyzer, spinning in place or being stuck and ignored wherever their actuator got wrecked.

Ion rifle doesn't need to be a pulse rifle to borgs and borgs don't need to turn into a towering inferno of helpless shattered parts when a wiz shows up or some joker chucks an ied at 2 shards.

**Comment by AutismSpider** [comment]
@PJB3005 you are retarded for thinking this was good in any way same goes for the dip shit that ask for this 

if you want better way to take ions with you what happen to the fucking PR for ion pistols some one was working on?

**Pull request closed without merging**
