### PR TITLE
Bluespace Bananas now Contain honk serum

### PR DESCRIPTION
**Pull request by KingofHONK**
Adds honk serum to bluespace bananas, replacing potassium bicarbonate. Mutated botany plants typically have alternative chems within them, and honk serum is a perfectly appropriate mutation reward (in addition to losing your shoes). Also I just want another thing to annoy the fuck out of everyone with.

:cl:
 * tweak : Adds honk serum to bluespace bananas, replacing potassium bicarbonate.

### CODE REVIEW

**Comment by drawsstuff** [comment]
This makes my life hell, I'm all for it.

**Comment by RealestEstate** [comment]
the mime-curse wizard metaclub will remember this

**Comment by Lunstra** [comment]
When I shilled botany to nipples I knew I would be creating a monster, but lords above forgive me I did a thousand times worse and created a c*der (botanycreep is pretty based though)

**Comment by SonixApache** [comment]
botanycreep
chemistry uselessifying

muh interactions

**Comment by RealestEstate** [comment]
merge when?

**Comment by ShiftyRail** [comment]
clown + botany powercreep

**Pull request merged**
