### PR TITLE
Первые потуги.

### PR DESCRIPTION
**Pull request by OdSt**
Перенес

### CODE REVIEW

**Comment by Intigracy** [comment]
cyka blyat

**Comment by Probe1** [comment]
Don't be rude to guests faglord.

**Comment by Intigracy** [comment]
cyka blyat

**Comment by OdSt** [comment]
Sorry for the mistake. This is our team decided to move [it](http://my-files.ru/cm4s5p) on your build.

**Comment by Kammerjunk** [comment]
khorosho

**Comment by Probe1** [comment]
It's quite alright @OdSt .  Best of luck with your project.  That's a great map name.

**Comment by OdSt** [comment]
Thank you. Very nice.

**Pull request closed without merging**
