### PR TITLE
PDA alt-click and ctrl-click swapped

### PR DESCRIPTION
**Pull request by despotate**
Far more people will be convenienced by this change than inconvenienced.

:cl:
 * tweak: "Alt-clicking and control-clicking a PDA have now been swapped. Alt-click to eject ID card and control-click to eject pen."

### CODE REVIEW

**Comment by 9600bauds** [comment]
I added this and I agree. The pen was just the first alt+click thing I tried as an experiment.

**Comment by 9600bauds** [comment]
https://github.com/despotate/vgstation13/blob/2ab9af641300f039a3ce327e812a84da9e3dab90/code/game/objects/items/devices/PDA/PDA.dm#L2087

Make ctrl+click eject the pen then, otherwise you have two shortcuts for ID ejection you silly

**Comment by despotate** [comment]
Oh, ctrl-click was the shortcut? never mind

**Comment by 9600bauds** [comment]
Ehhhh it's still not-ideal, alt+click is the one people will try first and ejecting ID is used more often than ejecting the pen. That was lack of foresight in my part.

You could swap around the two shortcuts and it'd be better off after people got used to it again.

**Comment by Probe1** [comment]
lol i didnt merge it dont yell at me

**Comment by Kuranon** [comment]
For what purpose?

**Comment by despotate** [comment]
I originally made the PR without knowing that ctrl-click was the shortcut (which is proof that the defaults aren't very good). Bauds informed me that it is a shortcut but told me to swap them instead. Cue outrage when it's merged.

**Comment by Intigracy** [comment]
Ignore the thread shitposting.

Though Kuranon makes a valid point below.

**Comment by Kuranon** [comment]
You didn't know about a shortcut so it's not good? I'd rather not have to relearn a button and go through the pain of pulling out my pen instead of my ID every time just because someone wasn't aware a shortcut existed

**Comment by despotate** [comment]
It's more about consistency. Alt-Click is the "primary" shortcut, it should handle the most important verbs. Like your ID. Ctrl-Click is much more rare and should be the "secondary" shortcut for useless shit like pens.

**Comment by ghost** [comment]
People have gotten used to it now though, it's been at least several months like this. There's no reason to change something just because you personally couldn't remember the correct shortcut. Now many people have to change because you couldn't be arsed to learn. bad form

**Comment by despotate** [comment]
Consistency and standardization of user interface ought to trample the feeble impulses and muscle memory of the unclean.

**Comment by ghost** [comment]
Are you going to switch dragging to alt as well? Gotta keep it consistent

**Comment by VirginiaXL** [comment]
I don't see why the need to change this

**Comment by despotate** [comment]
Fuck, downvotes are at critical mass and I'm out of excuses. Gotta dump the heaviest load - responsibility...

.... onto bauds who suggested the change. I closed this PR when I found out about Ctrl-Click, but he convinced me to reopen and commit to swapping them. Aim the pitchforks for him.

**Comment by ghost** [comment]
Please inform the uneducated masses how to make a revert request on this

**Comment by despotate** [comment]
Yell at probe until he does it for you

I AM the masses, look at my commit history, I've done jack shit

**Comment by yclatious** [comment]
PROBE, FIX THIS SHIT

**Comment by ghost** [comment]
@Probe1 revert this mr probe

**Comment by ghost** [comment]
It makes sense to me
@SolariousGabriella Why do you care?

**Comment by ghost** [comment]
@DrCelt Why do you care that I care?

**Comment by 9600bauds** [comment]
It's very simple, alt+click is the most common misc. shortcut. Ctrl+click is mostly for dragging, in fact machinery can't have Ctrl+click misc. shortcuts because it conflicts with dragging.

So alt+click is the most commonly used one. Ejecting ID is much more commonly used than eject pen. It makes all the sense in the world for it to work that way and not making it that way to begin with was lack of foresight in my part.

I occasionally altclicked by mistake only to get my pen instead of my ID, it made so little sense that not even muscle memory made me get it right. If you've already memorized the old shortcut, you'll be very shortly inconvenienced until you catch on to the new proper one, and everyone else in the future won't be inconvenienced by the previous dumb shortcut.

**Comment by 9600bauds** [comment]
And no it hasn't been "years" quit overreacting

**Comment by yclatious** [comment]
I remember only using alt click for sensors and absolutely nothing else in my gameplay, ctrl click for everything that usually matters and atleast for me, its a much more fluid than alt clicking due to it being a lot more used than anything else, alt is for my knowledge about machine activation like the microwaves, which makes no sense to make it, the less used key, to nab your id, the most important thing.

Changing it now to "standardise" would mean you also make alt click into draging, if you really want to start changing controls people are used to for no good reason but "standardization", go the full way then. Dogshit idea to begin with since ctrl is better, but if you really want to do so, atleast go for it fully.

**Comment by 9600bauds** [comment]
http://ss13.moe/wiki/index.php/Shortcuts

Like I said ctrl+click is for dragging mostly, and dragging has priority over everything else that isn't already inside your inventory. You couldn't ctrl+click a chemmaster to eject the beaker, or ctrl+click a portable pump to eject the tank, because dragging would have to take priority since it's more important.
That leaves alt+click for the "miscellaneous" shortcuts.

**Comment by ghost** [comment]
Well done, you changed a wiki. If only it could be changed back with ease..

**Comment by Kuranon** [comment]
You're not even removing the ctrl+click option so why does it matter which is which?

**Comment by yclatious** [comment]
Fine enough, fine enough, go change shit everyone is used to just to standardize it.

**Comment by 9600bauds** [comment]
The wiki link was to show that alt+click is the more diverse one. In fact, PDAs are the only thing that even use ctrl+click for anything besides dragging, it seems.

**Comment by Exxion** [comment]
Holy FUCK
Who fucking cares

**Comment by Probe1** [comment]
I merge like 30 PRs yesterday and I don't hear a word about.  PJB merges one and there's a riot.  I know which track the train is on.

multi_7a4fda_5461110

**Comment by ghost** [comment]
The game works fine without the change though, it's just enforcing shit on players to fufill your own autistic desires of keeping the code consistent. 

Funny isn't it that when it's posted to the thread there's an outrage, as if the actual playerbase doesn't want this and the only people that support it are coders that infrequently play the game anyway. I'm certain if the playerbase knew about this PR before it was merged the thumbs down would greatly outweigh thumbs up. It's a pointless change that annoys players and doesn't improve the game in any way, why keep something like that?

**Comment by despotate** [comment]
> fufill your own autistic desires of keeping the code consistent.

Have you ever coded before? Consistency isn't something you do just as an "autistic desire".

There are plenty of changes that are necessarily painful in the short term that lead to greater gains in the long run.

**Comment by ghost** [comment]
How would this improve the GAME that hundreds of people play. I understand it makes the code prettier and more standardized, but how does this change improve the game that the code affects? The game in my opinion should come before the consistency of the code.

**Comment by PJB3005** [comment]
I hope you all realize you guys are wrong.

Objectively.

Deal with it.

**Comment by 9600bauds** [comment]
>Funny isn't it that when it's posted to the thread there's an outrage, as if the actual playerbase doesn't want this

Actually that sounds to me more like it's the thread overreacting, if the playerbase didn't want it so bad they would have complained as soon as they saw the changelog

**Comment by 9600bauds** [comment]
Nobody ever said anything about consistency of the CODE. In fact this makes no difference to the CODE.

It's about making the existing shortcuts more intuitive.

**Comment by Kuranon** [comment]
What greater gain in the future will this give?

>Actually that sounds to me more like it's the thread overreacting, if the playerbase didn't want it so bad they would have complained as soon as they saw the changelog

This is exactly what I did

**Comment by PJB3005** [comment]
Good thing I merged this before these shitters got wind of it jesus, then I might've actually not merged it because of how controversial this change apparently is.

But anybody against this because change is bad is objectively wrong so deal with it.

**Comment by Exxion** [comment]
I'm pretty sure you've all spent more energy complaining about this than it would take to get used to it

**Comment by Probe1** [comment]
Make a revert PR and stop spending your time arguing in this merged issue which isn't going to get it reverted. 

You don't even have to code it you just press the revert button.

**Comment by 9600bauds** [comment]
yeah fuck this I'm supposed to be looking up antag datums, this is Parkinson's Law of Triviality at its finest.

**Comment by despotate** [comment]
Decisions are hard to make and consume willpower. Even something as small as having to decide whether to use ctrl-click or alt-click for your widget results in an opportunity cost of improving that widget further.

Standardizing to alt-click ends that debate and lets us work on future features with one less thing nagging at the back of our heads.

**Comment by uazuaz** [comment]
using ctrl is much easier, so in my opinion all the most used options should be used with ctrl+click instead of alt+click: PDA ejecting IDs, setting suit sensor, etc.

**Comment by PJB3005** [comment]
Issue is ctrl conflicts with pulling.

**Comment by Exxion** [comment]
I'm 90% sure neither PDA shortcut works if you aren't holding it

**Comment by Exxion** [comment]
Or I mean
If you don't have it on you

**Pull request merged**
