### PR TITLE
Fixes player age

### LINKED ISSUE #11142: Job Roles are no longer restricted behind an account's age
Panic but also despair
This was on a freshly made account.
Silicons, head roles, and I think sec should be showing number of days left until I can choose them. They are not locked however. The means someone can log in for the very first time and play as an AI or head and ruin everything.
Current theories:
Vox Trader update broke it
Moving preferences to the secret repo broke it
Byond is fucked

### PR DESCRIPTION
**Pull request by clusterfack**
Fixes #11142

If you log in the for the first time your player age will be "requires database". 

This causes problems because when you log in for the first time you can set job preferences to other values because your player age is "requires database" which means the game assumes you didn't set up a database and thus removes all job setting restrictions.

### CODE REVIEW

**Comment by Wizardcrying** [comment]
Oh, wow. I didn't know that it was actually broken.
That explains the severely inexperienced heads.

**Comment by PJB3005** [comment]
Fixes #11142

**Comment by MrStonedOne** [comment]
if you rebased to /tg/ you would have already had this fix......

**Comment by 9600bauds** [comment]
And if those Aussies nuked themselves, they'd have those damn emus in check.

**Comment by clusterfack** [comment]
And if you rebased onto us you would also have various fixes, your point?

**Comment by 9600bauds** [comment]
And it would be infinitely simpler to just fix those bugs again than rebase to a different codebase, without losing any features on the process either
Basically, we're stupid for responding to this seriously

**Comment by Iamgoofball** [comment]
should just rebase

**Comment by clusterfack** [comment]
Go back to your containment repo fags

**Comment by 9600bauds** [comment]
Shhhh, don't let Goofball goof on you

**Comment by Iamgoofball** [comment]
#goofd

**Comment by PJB3005** [comment]
The worst thing to happen to a man. 

Bring goofd.

**Pull request merged**
