### PR TITLE
You can now photocopy the blueprints

### LINKED ISSUE #8758: Allow the copying of the station blueprints.
It's no surprise that people like to hog their one of a kind items, here are some examples. Ask to borrow the captains laser, or his or the HoS's telebaton? Fat chance. Want a hand tele? Unless you're the clown you won't have much luck with that. Want the CMO's hypospray? Once you pry it off of his dead body. The RD's superior welding goggles? Just kidding you can make those in RnD now. But the station blueprints. This has to be one of the most harmless out of all the unique items, so why not let it be reproduced for building purposes?

Also on a side note, traitors can currently just take a picture of the station blueprints and succeed that objective anyways, leaving the original blueprints untouched. It's just a hastle to ask the CE to loan you the blueprints 50% of the time because they think you just want to steal them.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #8758

tested-stamp

### CODE REVIEW

**Comment by Imagebard** [comment]
>Copies count for the steal objective

Which means they are a high security item
Which means security officers can arrest you for it
Which means the CE can't give them away to lower mooks
WHICH MEANS THIS PR IS PRACTICALLY EVERYTHING WRONG IN THIS WORLD
The prosecution rests

**Comment by Intigracy** [comment]
suck it nerd

**Comment by ihadtoregisterforthis** [comment]
> fixes #8758 
> fixes a feature request

Is the copy the same as the original in all aspects? If it is I disagree with this solution.

**Comment by 9600bauds** [comment]
You can already photograph the CE's blueprints for your greentext u nerd

> Which means the CE can't give them away to lower mooks

Simple solution
>CE did you give this guy this photocopy
>yes
If people can get a gun permit you can get a fucking photocophy permit, stop blowing everything out of proportion

**Comment by Imagebard** [comment]
@ihadtoregisterforthis
Github checks for that line on the OP post. If you

>You can already photograph the CE's blueprints for your greentext u nerd

Which means security officers can arrest people for having a photograph of the CE's blueprints
Which means the CE can give away arrest-bait in the form of a photograph
WHICH IS BASICALLY EVERYTHING WRONG WITH THIS FUCKING SERVER

**Comment by Intigracy** [comment]
Even if you don't want to read the code, you can still read the changelog.

>+- rscadd: You can now photocopy the station blueprints to recieve a single use version of it. Copies count for the steal objective.
View

**Comment by Imagebard** [comment]
I fail to see your point?

**Comment by 9600bauds** [comment]
>EVERYTHING WRONG WITH THIS FUCKING SERVER is something that never happens, probably wouldn't happen even if you tried to make it happen, and you only just now even found out about

Phew! What a great server, then.

**Comment by Intigracy** [comment]
all this butthurt

**Comment by Probe1** [comment]
please no.

ask the damn CE.

**Comment by AutismSpider** [comment]
Ask the damn CE or Engi borg name the room for you and shit?

**Comment by 9600bauds** [comment]
> ask the damn CE.

Considering you're going to need the CE's blueprints to photocopy them in the first place...

**Comment by Zth--** [comment]
I'm ok with this. Photocopies are harmless, it means you already managed to get the real ones so... :+1:

**Comment by BestName** [comment]
@Imagebard 
ihadtoregisterforthis has a point. Intigracy should have used "closes" or "resolves" instead.

**Comment by 9600bauds** [comment]
literally who cares

**Comment by BestName** [comment]
:^)

**Comment by Probe1** [comment]
Because no ones going to tune up our pants on head retarded traitor objectives that ask syndicates to steal items made commonplace.

**Comment by Intigracy** [comment]
It's not commonplace considering you have to steal it to copy it in the first place.

Way to make mountains out of molehills.

**Comment by 9600bauds** [comment]
Since when do people give a shit about greentext anyways? Can't it still ask you to steal a tank of Plasma?

**Comment by Intigracy** [comment]
I've never seen someone arrest someone for having the blueprints if they were given to them unless they were being a prick about something. All it takes is asking the CE on the radio.

So much whining in a feature request PR.

Waah you used fixed to close the issue as a generic term instead of specializing to sate my autism ;_________;

Waah you can get greentext easy with this even though it's even easier to take a picture of the blueprints (NOT CONSIDERING YOU CAN COPY THE PICTURES AND THEY WORK CORRECTLY STILL) ;_________;

Waah I can't even read a changelog ;_________;

**Comment by 9600bauds** [comment]
jesus christ dude keep it civil

**Comment by NigglyWiggly** [comment]
Intigracy is a big bully, he doesn't know how to keep it civil

**Comment by Intigracy** [comment]
^

**Comment by Imagebard** [comment]
He's not a bully, just a sperg

>I'm putting huge emotes on my posts *IRONICALLY*

**Comment by Intigracy** [comment]
>le the playerbase is all shit meme
 >le walk me through what this pr does even though there's a changelog included meme

**Comment by 9600bauds** [comment]
Will Everyone Please Calm Down And Like Have A Bagel Together

**Comment by Intigracy** [comment]
Arguing this is pointless. I'm not going to change the code so this is just needs final decision at this point.

Reasons people have stated against this:

> Le playerbase will arrest you for having a copy or a photo because it's everything wrong with this server

Yeah buddy cause everyone is an asshole.

> This makes stealing the blueprints trivial.

You still have to steal the blueprints to copy them, and you can already take a picture of the blueprints and make copies of THAT to achieve the same effect.

And the completely unrelated crying about how I was using fixes to close a feature request.

**Comment by Imagebard** [comment]
Okay but can you photo the station's blueprints photocopy to complete the traitor objective?

**Comment by Intigracy** [comment]
Probably.

**Comment by Imagebard** [comment]
Okay but if you photocopy the blueprint's photocopy photo will that complete the traitor objective?

**Comment by Intigracy** [comment]
Yes, if you can photo the station's blue prints photocopy to complete the traitor objective, then making a photocopy of that photo will also complete the objective, because it just spawns another of the same photo.

Taking a photo of that photo will not work.

**Comment by Imagebard** [comment]
>Taking a photo of that photo will not work.

You think too far ahead.
There's no reason to not be able to take a photo of a photo of a photo of a photocopied photo of a photocopied station's blueprint and still get your greentext.

**Comment by 9600bauds** [comment]
the syndicate will finally see me for the elite stealth agent I am!

**Comment by clusterfack** [comment]
The cheap one is cool if its for regular paper. I don't know if the photocopier can take nanopaper, but it'd be cool that if it could it would make a mommi blueprints style blueprint.

**Comment by AutismSpider** [comment]
photocopier only takes paper

**Comment by clusterfack** [comment]
What happens when you photocopy nanopaper?

**Comment by Intigracy** [comment]
it makes a new nanopaper afaik

**Comment by clusterfack** [comment]
Wow fucking triggered

**Comment by Probe1** [comment]
@9600bauds 

> Since when do people give a shit about greentext anyways? Can't it still ask you to steal a tank of Plasma?

Really dude?  Fuck any kind of quality control because you don't care about greentext?

**Comment by Intigracy** [comment]
> m-muh greentext

I expected better of you Probe1.



You can steal the blueprints by going to the CE office, opening the locker, pulling out the blueprints, taking a picture of it, and putting it back like nothing happened. Your buddy needs the blueprints too? No problem, just copy the picture you just took.

In order to get greentext this way, you have to take the blueprints from the office, take them to a photocopier somewhere on the station, photocopy it, and then run back to put it back. Your buddy later reveals he needs them too? You have to go back to the locker, get the blueprints again, go back to the photocopier, copy them, then take them back again.

**Comment by Imagebard** [comment]
>I expected better of you Probe1.

The person I'm expecting more form is you, who just pretended he didn't say anything of importance. Holy fuck, are you that mad that people don't like your PR or what?

>You can steal the blueprints by going to the CE office, opening the locker, pulling out the blueprints, taking a picture of it, and putting it back like nothing happened.

Contrary to what will happen if this PR is merged, where you can just rush over to a Engineer and steal his blueprint copy, instead of having to break into the Chief Engineer office like you had to before.

**Comment by Intigracy** [comment]
First you say "Which means the CE can't give them away to lower mooks", now you're saying they're going to give them to every engineer every round.

Which is it?

**Comment by Imagebard** [comment]
First you deny that people will be arrested for it now you agree with me.

Which is it?

**Comment by Intigracy** [comment]
I never said they're going to be arrested for it, I'm pointing out your hypocrisy.

You however did say CE's can't give them away, now you're saying they will to every engineer.

**Comment by Imagebard** [comment]
So you mean to say that, either chief engineers will be giving out photocopies to engineers building new rooms, or they won't and photocopies will be useless.
Either possibility sucks pretty bad, don't you think? I think we should give up on this whole PR and think of something else.

**Comment by 9600bauds** [comment]
Just remove the blueprints being an antag objective holy shit
If any sort of compromise is completely impossible then it's just not worth keeping it as an objective

**Comment by Probe1** [comment]
Our codebase needs a head coder.

I spend all the babysitting time I have being an admin, I can't be here to explain why it's a bad idea to fuck up antag objectives to people that know better as well.  

If you're going to make a PR that trivializes attaining an antag theft item then address that too.  

Everybody stop with these damn PRs that open a huge can of worms and then does nothing to deal with the problem it creates.

**Comment by unid15** [comment]
Here's an idea

CE's original blueprints gain the ability to delete blueprint areas (the ability is in the code but commented out, would be easy to implement it). Blueprint copies can't delete blueprint areas. And make only the original blueprints count towards the objective

bam fixed

**Comment by Probe1** [comment]
@unid15 works for me.

**Comment by Intigracy** [comment]
WYCI

**Comment by unid15** [comment]
Cmon dog all you had to do was to uncomment line 93 at https://github.com/Intigracy/vgstation13/blob/f27b1cb55979267761862ea78bf8a2436dd0a841/code/game/objects/items/blueprints.dm

**Pull request closed without merging**
