### PR TITLE
[Meta] New Years map update

### PR DESCRIPTION
**Pull request by IratePirate**
Started a few weeks back and I fugged up map cleaning due to me switching between computers during the process. There were probably about 8000 changes anyway so oh well. General theme with these changes is both fixes, stuff that tries to make the map like overtly Box-like, ease of use for Security and Engineering and fluff changes. Probably lots of tiny little changes unmentioned.

-arrivals slightly changed to make it less overtly box-like
-added virology maintenance
-redone lighting in many parts of the station
-rewired much of the station - removed about 30% of the powernet because so much of it was unnecessary, now cutting wires might actually have an affect
-station cameras are now named differently, should be easier to navigate
-general fixes and changes especially with air vents
-made engineering foyer public access due to the ai minisat entrance, nothing important in the area anyway and should make getting to tcomms and the ai a tiny bit easier, atmos and engineering are secure enough anyway
-changes to atmos monitoring layout
-yet more changes to ai upload and fixed pipes running under walls
-changes to the asteroid, wizard station, nuke shuttle (made it a desert launchpad), satellite etc. mostly for the sake of flavour
-derelict should have air tanks
-incinerator made slightly larger
-changes to area around the showroom, new small maint added and space tiles removed
-fortified chemistry slightly more to stop griff
-minisat turrets rotated
-bar made larger and some decore changes, made less of a canteen
-brig infirmary and uniform area enlarged
-extensive layout changes to the prison wing and addition of solitary
-one upload turret removed, planning frame added, computers rotated so it might be harder to run up and use a module before getting hit
-removal of motion sensor cameras outside armory and inside AI upload, there is no need to help AIs with stuff like this when its already on a satellite
-moved gas sensors in atmos tanks
-moved test range a tiny bit closer to the station
-temporary workaround for minisat power, magic smes in ai core - might make bombing the AI a risky business we'll see
-fixed some motion cameras
-fixed a space hole in maint wall west of medbay
-prettied up some floors that needed it across the station
-fireaxe cabinets should be locked
-supermatter chamber filled with nitrogen to stop zas fuckery as per clusterfack's suggestion
-fixed placement of gear storage and added bandoliers
-fixed CE office power AGAIN
-added cameras to patient rooms
-shuttle layout changes, subject to change
-small changes to escape arm (formerly departure lounge)
-RD office layout changes so it isn't a straight copy of Box
-more firesuits added across the station
-dormitories area slightly changed
-added areas and apcs for break room and interrogation
-cards added to the map
-some more fluff added to maint and junk moved about
-mixing room made airless as per esword's fix

### CODE REVIEW

**Comment by d3athrow** [comment]
Generate and update the nanomap images for metaclub and add to your PR

**Comment by IratePirate** [comment]
Just found the guide, i'll make sure to do it.

**Comment by IratePirate** [comment]
Is that suitable?

**Comment by d3athrow** [comment]
start up a local server and in the special verbs tab use the generate all zlevels verb

**Comment by IratePirate** [comment]
Having trouble finding said tab, do I have to be an admin on my server to use it? There's generate nanoUI maps in another tab but no special verbs tab. I tried setting myself to admin using the config files but nothing seems to be working. Is it essential?

**Comment by d3athrow** [comment]
i guess i forgot which tab it was in but yeah its the map thats on the crew monitor and atmos control computers.

**Comment by Iamgoofball** [comment]
aaugh

use mapmerge

**Comment by IratePirate** [comment]
I always do, but I switched to a different computer and that somehow fucked with it.

There are many thousands of changes anyway so it's not as if I only changed a single vent in the corner of the map and overwrote absolutely everything.

Fucking github desktop app.

**Comment by ComicIronic** [comment]
Can you post images of the changes?

**Comment by IratePirate** [comment]
Some of these are WIP from two days ago.











Still having trouble generating NanoUI images. Editing admins txt doesn't seem to do anything.

**Comment by d3athrow** [comment]
waitin for nanomap1-7.png

**Comment by IratePirate** [comment]
aaaa

Edited the admins list in config-example. No admins list in the config folder itself. Where am I supposed to do this crap? Sorry if this is getting irritating but I have no idea how to make myself admin, instructions on some of the wikis seem out of date for /vg/.

I'll get to work on making door access more reasonable for our server also, Assistants currently can't go into maint for instance.

**Comment by Lokiamis** [comment]
Paste the file you edited into the real config folder

**Comment by IratePirate** [comment]
I just managed to find that on Bay's forums.

Kill me.

**Comment by Lokiamis** [comment]
At least you can skip the roundstart time now!

**Comment by IratePirate** [comment]
My powers are now limitless. Time to get this wrapped up.

**Comment by IratePirate** [comment]
Nanomaps added, thanks for the assistance. Should be ready to merge.

**Pull request merged**
