### PR TITLE
[Meta] Unimaginative Update Title

### PR DESCRIPTION
**Pull request by IratePirate**
-fixed up minisat power
-fixed the issues people raised
-made some job rooms like mechanics, chemistry and R&D a few tiles more
-layout changes to captains
-fixed up some piping in some places
-made paramedics and cryo slightly larger, layout changes in medbay
-changed execution access
-changed the grille defences for atmos in space
-added air alarms where it was needed
-added some job specific items that weren't on the map
-fixed disposals looping around after delivery
-removed the waste of space maintenance east of captains and EVA so the rooms wouldn't be so tiny
-made secure storage and engineering storage a wee bit larger
-xenobiology fixes
-lots of little things
-AI can no longer access the minisat turret control
-AI gets a pair of emitters to guard the main entrance of the core just because

### CODE REVIEW

**Comment by d3athrow** [comment]
Conflicts.

**Comment by IratePirate** [comment]
https://github.com/d3athrow/vgstation13/commit/7cb1db7bf729f78b232d91ea3490b72b9f8cc25e

Is it possible for you to revert these two fixes Pomf? They're included in this PR but the map is slightly different so I can't just manually merge them into mine.

**Comment by ComicIronic** [comment]
If you attempt to merge and resolve the conflict to your local version of the map file, it should be possible to add Pomf's changes, push, and have the conflicts be resolved.

**Comment by IratePirate** [comment]
Except for the fact that what Pomf changed no longer seems to be on the same tiles in my version of the map which means the whole thing conflicts.

**Comment by ComicIronic** [comment]
I meant forcing the merge to resolve to only your local version, which is a functionality that Git should provide.
You can then add the changes in on top.

**Comment by IratePirate** [comment]
You're a saint.

**Comment by IratePirate** [comment]
closes #2590
closes #2594
closes #2592
closes #2591
closes #2516

**Pull request merged**
