### PR TITLE
Adds new chemicals for emagged Sweets

### PR DESCRIPTION
**Pull request by Arthurdentistss13**
This PR expands the list of possible chemicals that you can get from sweets from emagged sweet machines.

The chemicals added are:

- Water
- Spiders
- Waifu
- Husbando
- Diabeetusol
- Sulphuric Acid
- Lithium
- Chillwax
- Oxycodone
- Vomit
- Bleach
- Heartbreaker Toxin
- Nanites
- Corn Oil
- Nova Flour
- 

:cl:
 * rscadd: Added new chemicals to the list of chemicals available from the emagged sweet machine

### CODE REVIEW

**Comment by Kurfursten** [comment]
👎 for spiders+waifu+husbando because this will allow people to electrolyze and get karmotrine without doing xenoarch

**Comment by boy2mantwicethefam** [comment]
electrolysis is a meme and so is karmotrine, let people have fun!

**Comment by dunsel-hordon** [comment]
wait spider? Will it turn people into spider?

**Comment by ghost** [comment]
>nanites
and let people make cyber horrors that easy?

**Comment by Arthurdentistss13** [comment]
There are far easier methods to get nanites then  using an emagged sweet machine; I.E. cooking a roboburger

**Comment by Blithering** [comment]
People can already RNG roll for karmotrine through floor pills, something locked behind both emags and a hefty coin supply isn't so bad.

**Comment by Kurfursten** [comment]
According to the odds based on all spawners and all outcomes, it's about once every 42-56 shifts you find 3-8u of non-replenishable karmotrine from floor pills on box. Not really comparable to a renewable source.

**Comment by Arthurdentistss13** [comment]
I really think you are overestimating how often people would use this as a method to get hold of karmotrine but I also can't be arsed argue about it so I'll remove it, some other nerd can always add it themselves if they want

**Comment by Arthurdentistss13** [comment]
replaced the karmotrine chems with liquid butter, colorful reagent and degenerate calcium

**Pull request merged**
