### PR TITLE
vines now have an icon for when they have fruit

### LINKED ISSUE #7258: Better sprite for when vines are harvestable
Right now the way vine sprites work is shitty. Could you put colored circles that somewhat resemble fruit on vines when they are ready to produce so you can easier see rather than it just being thick vines?

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #7258

### CODE REVIEW

**Comment by gbasood** [comment]
Holy shit what did we not have this before
How was anyone supposed to tell when their vines were anything but just vines @9600bauds

**Comment by Intigracy** [comment]
DNM for right now

**Comment by 9600bauds** [comment]
We did have it @gbasood, people just said it wasn't visible enough because it didn't have ketchup splattered on top

**Comment by gbasood** [comment]
Ketchup is important

**Comment by Intigracy** [comment]
You can remove the DNM now, I fixed the issue I had.

**Pull request merged**
