### PR TITLE
One-way window subtype

### PR DESCRIPTION
**Pull request by brndd**
title says it all

### CODE REVIEW

**Comment by ghost** [comment]
Constructable?

**Comment by brndd** [comment]
No, though there's an ideaguys idea. That would better be implemented as some new item you slap windows with that turns them into one-ways (the description says one-way windows have a plastic coating, so try something like that).

**Comment by Exxion** [comment]
Didn't we stop using these because they're buggy and slow?

**Comment by Shadowmech88** [comment]
>That would better be implemented as some new item you slap windows with that turns them into one-ways (the description says one-way windows have a plastic coating, so try something like that).

When I originally added one-way windows, they were constructable, and sheets of plastic was precisely how it was done.
However, because of the way BYOND's vision works, the only way for one-way windows to be possible is for the window to determine if there are any people in view of it, then determine if they're on the side that's blocked, then if so, briefly turn itself opaque, make a list of all the tiles in that viewer's vision that it would block, turn itself transparent again, and then manually block all of those tiles in that viewer's vision. For every viewer who is in range of the window, every time they move.

Now, even with all of that, one or a few windows in a room with a few people in it is not all that big a deal. However, we were running into issues where players would construct a shitload of one-way windows in highly-trafficked areas like Medbay, and the cumulative calculations were causing the server to noticeably lag. I left them in the code for mappers, since they could be placed in limited amounts for certain areas like Interrogation without too much trouble, but they just can't be optimized enough for players to not be capable of abusing their construction, intentionally or unintentionally.

**Comment by brndd** [comment]
Alright, that makes sense. This subtype is for mapping anyway; current maps suffer from varedited one-way windows, which resulted in lots of one-ways where they shouldn't be on eg. Roidstation. Subtyping it is the best solution because it makes it harder to accidentally place in the wrong kind of windows.

**Comment by Shadowmech88** [comment]
As discussed in Discord, there may be ways to optimize one-way windows so that they're performant enough to be allowed to be constructed, if anyone wants to take a crack at it.
Visual contents adds a lot of new and interesting things, though I don't know how it might be used specifically.
Each window could also cache all of the tiles it could possibly obscure from every angle within its view when it's built, and then use those while it exists, which would cut down quite a lot on `view()` calls, which are expensive.

**Pull request merged**
