### PR TITLE
Adds proper peglimb item, rewrote code to accomodate

### LINKED ISSUE #16097: Peg leg surgery consumes the entire stack of wood.
#### Description of issue
Peg legs only require one plank of wood to make, however the surgery step consumes the entire stack of wood.

#### Difference between expected and actual behavior
Expected the rest of the wood not to vanish into thin air.

#### Steps to reproduce 
Attempt peg leg surgery with a stack of more than one plank of wood in hand.

### PR DESCRIPTION
**Pull request by Cyadox**
Adds a proper generic peglimb to the plank crafting menu. Costs two planks, and replaces them in the process of putting peg limbs on someone - otherwise, it functions as planks did before.

peglimb
Also closes #16097 as wood is no longer used directly to make limbs.
:cl:
* rscadd: Adds peg limbs to wooden plank crafting menu. Credit to DrSnips for the sprite
* rscadd: Peg limbs are now used to give someone - you guessed it - peg limbs instead of planks
* rscdel: Removes the ability to use planks to give someone peg limbs

### CODE REVIEW

**Comment by SonixApache** [comment]
New sprite?

**Comment by Cyadox** [comment]
Yup, in weapons.dmi. I didn't see the read-only checked off so I thought it would be okay?

**Comment by N3X15** [comment]
Add the sprite to the OP (export as PNG, drag into OP description) so I can remove the more info tag.

**Comment by Cyadox** [comment]
Wiki is updated http://ss13.moe/wiki/index.php/Surgery#Limb_Replacement_Surgery
Sprite also now in the OP

**Pull request merged**
