### PR TITLE
Lightspeed Ship Vault is now pilotable (and other tweaks)

### PR DESCRIPTION
**Pull request by gurfan**
Ever find this thing in space and wonder why the FUCK you couldn't pilot it?

nu-lightship

Well now you can! This lightship vault now comes with a working shuttle computer, linked to several docking ports near the station (the ones used by nukeops). 

itsarrived

A couple parts of the ship have been tweaked

- Power room now has an SMES.
- Added a couple lines to the AME shielding code, so the mapped in AME won't broken anymore. Just refresh the parts and you'll find yourself with a fully functional, three-core AME, which is more than enough to power the ship.
- Shuffled spawners around a bit.
- Added entrances/exits to the port and starboard sides.
- Added a couple extra machines to some departments.
- Added an extra bear spawner.

[content]
[tweak]

:cl:
 * rscadd: The Lightspeed Ship found in the depths of space is now pilotable!

### CODE REVIEW

**Comment by toomykins** [comment]
>cooldown timer is 80 seconds

ngl i'd rather have it be 800 seconds.
Otherwise, very cool. hope this thing doesn't overlap with other existing docking ports.

**Comment by gurfan** [comment]
the ports gave me a bit of trouble, ~~Im going to make some unique docking ports and map them in.~~ If a docking port is already taken the shuttle can't move their, and in case somethings in the way of port the ship will refuse to move there

**Comment by SonixApache** [comment]
The Kestrel actually working is fucking rad. Great job. 👍👍👍 
Great job on the fixes too - the AME not working was a massive issue.

If you want to do some more FTL references, add a dead golem and dead bugman in there somewhere.

**Comment by mrflarg** [comment]
Paid for an account to upvote this. very cool!

**Comment by Chucklemonger** [comment]
absolutely radical

**Comment by cloutcode** [comment]
dangerously based

**Comment by Exxion** [comment]
>Paid for an account

Is this a joke? I don't get it

**Comment by Zth--** [comment]
It would be cool if you could lock/unlock the airlocks from the captain room using an airlock controller. Or maybe the security room? I don't remember which one was used in FTL

**Comment by Exxion** [comment]
There's a door room on this ship

**Comment by gurfan** [comment]
Updated:

- Side doors are now two tiles wide, so they can share some docks with the salvage shuttle (ex, DJ Station).
- Air room now has a connector to space and a connector to the air tanks.
- Door room is no longer full of airlock assemblies, instead has buttons for opening/closing exterior window shutters, bolting exterior airlocks, and turning off the lights in the ship.
- Kitchen: expanded by one row, shuffled it around, and added extra botany tray + seed extractor.

Updated screenshot above

**Comment by SootyBear42** [comment]
Actually a good idea

**Pull request merged**
