### PR TITLE
delay between surgery steps reduced by 90%

### PR DESCRIPTION
**Pull request by nervere**
## What this does
Surgery steps currently use the global attack delay of 1 second. This is very frustrating and, for experienced surgeons, is very noticeable. Oftentimes you find yourself spam-clicking to do the next surgery step, which sucks! ~~This PR lowers the delay to 0.2 seconds.~~ The delay is now 0.1s, the same as the global click delay.

## Why it's good
This change:
- Allows for a greater skill ceiling with surgery, allowing experienced surgeons to save their patients faster.
- Reduces frustration often felt even by newbie surgeons performing basic procedures.
- Makes it less dumb of an idea to perform surgery on a mildly injured corpse instead of lazily throwing them in the cloner.

Video of the new delays. Note that attack speed with surgical tools is not any different than before.
(Video depicts 0.2s delay - it has since been changed to 0.1s)
https://github.com/vgstation-coders/vgstation13/assets/26285377/e0351597-deed-4c6f-bacd-b97d87082299

[tweak][qol]
## Changelog

:cl:
 * tweak: The delay between all surgery steps is now 0.1 second, instead of 1 second.

### CODE REVIEW

**Comment by Eneocho** [comment]
might as well make it 0.1s to match the click delay

**Comment by nervere** [comment]
If no one thinks this is OP, I will do just that. I'll give some people time to voice their opinions first, however.

**Comment by KingofHONK** [comment]
Time for my new surgeon static: Robert Liston!

**Comment by Dacendeth** [comment]
Huge gremlin surgery buff.

**Comment by RealestEstate** [comment]
I would double ubvote this if I could.
0.1s gets my ubvote as well.

**Comment by nervere** [comment]
I'm gonna get this out of the way and change the delay to 0.1s since there doesn't seem to be any pushback so far.

**Pull request merged**
