### PR TITLE
Adds proper slime "meat" as gelatin for all slimes.

### PR DESCRIPTION
**Pull request by DrSnips**
[bugfix][consistency]
When slime people got added they were given a pseudo kind of "meat" as a place holder in the form of slime hearts which isn't a meat at all and no one came back to it. This adds a "meat" to them in the form of gelatin which contains 10u of slime jelly normally. I have also extended this "meat" to other slimes but I haven't changed if they can be butchered so they only give you meat via an emagged gibber or another method I'm not aware of.
Gelatin already exists in the code as a kind of food you can make but I didn't want to make their meat yet another non-meat product so this can go one of three ways. 
A) Both kinds exist at the same time but are reflected in use as it current is for the PR. 
B) The cooked version is changed to the new gelatin "meat".
C) The new version is removed and slime people are given yet another non-meat meat in the form of the existing gelatin. I have put these in order of my most to least desired solutions.
There's two recipes in this as well to make up for the overlap in gelatins.
This also fixes a bug related to not being able to butcher slime related things due to the lack of a proper meat type.

:cl:
 * rscadd: Slime related beings now have a proper type of meat in the form of gelatin [slabs]. You can use it as a meat or as a gelatin in cooking but be aware that it contains slime jelly. Throw your local xenobiologist into the gibber today!

### CODE REVIEW

**Comment by Kammerjunk** [comment]
fuck off slimefucker
edit: great moves keep it up

**Comment by DrSnips** [comment]
I should have posted the sprite in the OP but I'm tired now and will do it tomorrow. It's light blue as a reference to slime people 1.0. I could make it change color based on it's origin but I wanted to have a nod to 1.0 somewhere in 2.0 and making it consistent when transfering would be a headache but I'm willing to try.

**Comment by SGuivenne** [comment]
Oh fuck, as chef now I have incentive to raid genetics and forcefeed their humanized monkeys slime mutagen.

**Comment by MadmanMartian** [comment]
Fix the conflict!

**Pull request merged**
