### PR TITLE
Adding a Round End Information button to the right window that appears when the round ends

### PR DESCRIPTION
**Pull request by DeityLink**
explain

there

rei

### CODE REVIEW

**Comment by ComicIronic** [comment]
Looking pretty good. You might want to include an image of the button itself.

**Comment by DeityLink** [comment]
aye

**Comment by DeityLink** [comment]
And yes, just typing "RoundEndInformation" in the chat window will open it as well.

**Comment by clusterfack** [comment]
Make sure it removes the 'round end information' when a client reconnects automatically after the round restarts too

**Comment by DeityLink** [comment]
I'm not sure how to test that, but even if the button was still there it wouldn't do anything. The browse proc does nothing if its first argument is an empty string.

**Comment by d3athrow** [comment]
@DeityLink in Login()

**Comment by DeityLink** [comment]
Aight, that should do it.

**Comment by CptWad** [comment]
:pray: Thank you Allah.

**Pull request merged**
