### PR TITLE
Fixing an obscure holodeck runtime

### PR DESCRIPTION
**Pull request by DeityLink**
image

Unpatched, this runtime leaves the holodeck in a very buggy state. I haven't been able to reproduce it consistently.

image

:cl:
* bugfix: Fixed a rare holodeck bug where the area change wouldn't be fully executed and objects would remain forever.

### CODE REVIEW

**Comment by BomberBro** [comment]
THIS is what the emagged holodeck should've been.

**Comment by Exxion** [comment]
If this works at all, it masks the real issue. It should at least report some debug info.

**Comment by Exxion** [comment]
Oh wait, actually, I might know the root cause. A couple turf types don't `return ..()` in their `ChangeTurf()` overrides. These include unsimulated snow tiles, glass floors, and *regular fucking walls*. If the original turf is one of those, it would cause this. I guess it could also be something else, but that's a good place to look.

**Comment by DeityLink** [comment]
> 
> 
> Oh wait, actually, I might know the root cause. A couple turf types don't `return ..()` in their `ChangeTurf()` overrides. These include unsimulated snow tiles, glass floors, and _regular fucking walls_. If the original turf is one of those, it would cause this. I guess it could also be something else, but that's a good place to look.

Is there any reason for those to not return their parent?

**Comment by DamianX** [comment]
A bunch of `ChangeTurf`s were changed by *multi-z* and so they're broken. There's no reason for them to return null. Most (all?) callers of ChangeTurf expect it to always succeed

**Comment by Exxion** [comment]
The ones I mentioned predate multiZ, but multiZ did indeed add more cases. Though I don't believe any of them could be happening here.

**Comment by DamianX** [comment]
Additionally: in terms of API design, relying on the value returned by `ChangeTurf` just amplifies the damage a runtime error does for no gain. The reference of a `ChangeTurf`'d turf always stays the same, so you could just keep referencing the same one. If you do rely on the return value, do check for the null value.

**Comment by Exxion** [comment]
That's a good point. There's no real reason to use `ChangeTurf()`'s return value, or really even for it to return a value. That in mind, I'd say the fix to this bug would be to just replace all uses of `X` with `B`, since after the call `B` will refer to the new turf anyway.

**Comment by DeityLink** [comment]
ok then

**Comment by DamianX** [comment]
It really shouldn't be returning null, though. Is there another runtime that causes this one?

**Comment by Exxion** [comment]
If there were a runtime in `ChangeTurf()`, that would be the line this runtime came from. I guess a runtime could indirectly cause it, but I don't see how.

**Comment by DamianX** [comment]
I can't reproduce this bug at all. I went down the list of rooms top to bottom and then bottom to top. Everything just worked.

**Comment by DeityLink** [comment]
Chances are the players somehow built new turfs in the holodeck then tried to change the setting

**Pull request merged**
