### PR TITLE
Gives the Research Director a weapon permit.

### PR DESCRIPTION
**Pull request by SonixApache**
Since he's in charge of the department making guns, he might as well be allowed some ranged protection.

### CODE REVIEW

**Comment by AutismSpider** [comment]
Ahh yes a job no one picks now will only be pick for guns. What a good idea

**Comment by mrpain666** [comment]
Cant they just get one from the HoP anyways? As the situation warrants? Now we'll just see retards hogging the job for powergaming purposes.

**Comment by SonixApache** [comment]
Can't get one from the HoP / cap if they're not available at all (which is quite common in lowpop).
This was a common complaint in the lockbox PR.

And IMO, better a turboshitter RD than no RD. The latter is far more common.

**Comment by icantthinkofanameritenow** [comment]
A far cry from fixing the plethora of issues that the lockbox PR brought up, but better than nothing at all.

**Comment by jakmak** [comment]
Just revert the lockbox pr. This isn't a solution to the problems it has made.

**Comment by SonixApache** [comment]
The main issue with the lockbox PR is 'non-antag scientists no longer have easy access to guns'

i don't see how that's an issue

**Comment by Iamgoofball** [comment]
@SonixApache have they forgotten about the armory

or maybe that they don't NEED guns as a non antag and that there's shittons of improvised weapons they could be using like wavedash abuse to dodge bullets, pda slips, soap slips, microstuns from low potency banana peels, etc.?

**Comment by AutismSpider** [comment]
>need guns
>we have a dumb fucking blast cannon even mommis can use to crit people in one hit
>this shit has not been nerf yet with how easy it easy to make and use

fuck you Science babies aren't able to handle something more complicated than water potassing a lockbox and collecting valids.

**Comment by icantthinkofanameritenow** [comment]
@AutismSpider 
What, and waste a perfectly good TTV (of which you have exactly 6 and no way of making more)?

**Comment by AutismSpider** [comment]
other cannon you dumb shit

**Comment by icantthinkofanameritenow** [comment]
If you mean the pneumatic cannon, nobody uses it because it's too complicated for 95% of the server to figure out.

**Comment by AutismSpider** [comment]
its not though if you know how gas works and toss force of items

**Comment by icantthinkofanameritenow** [comment]
My point exactly, Autismspider. Or more precisely, those that do don't care enough to use it because it's still a lot of fiddling around that takes time that they may not always have.

**Comment by Iamgoofball** [comment]
So this is a case of git gud

**Comment by Intigracy** [comment]
fuck off goofball

**Comment by Iamgoofball** [comment]
fuck off Intigracy

**Comment by Shadowmech88** [comment]
Also the RD does have a unique personal weapon in the form of the hivehand.
Given that his job isn't directly combat-oriented, I don't feel like he needs a weapons permit any more than the CMO does.

**Comment by icantthinkofanameritenow** [comment]
The hivehand is also crap, and even if it wasn't the rest of the crew need to be armed for emergencies and breaking open boxes makes them crap too.

**Comment by Shadowmech88** [comment]
> and breaking open boxes makes them crap too

You yourself have a PR up to remove that, right? Shouldn't we wait and see how that goes before using it as a justification to give the RD a weapons permit?

**Comment by icantthinkofanameritenow** [comment]
Assuming it goes through you mean.

**Comment by gbasood** [comment]
ffffucking
why
If there's anything I hate more than pizzas being more expensive than a crate full of vests and/or guns it's R&D being gun printers and being the single force that can save or kill the station, save for singuloth
And no the fact that R&D's robustness is currently necessary due to the state of game balance is not an excuse to make them more robust

**Comment by kol1th** [comment]
what a disgusting PR. just stop

**Comment by SonixApache** [comment]
well since the lockbox thing is gone this is now irrelevant

**Pull request closed without merging**
