### PR TITLE
Dawson's Christian 4K HD

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[sound]

## What this does
same as #31694, but for this song too as it's also part of the higher quality upload of the album

## Why it's good
consistency

### CODE REVIEW

**Comment by Eneocho** [comment]
THERE ARE STORIES OF THE DUTCHMAN, THE CELESTE AND BARNHAM'S PRIDE
THERE ARE STORIES OF THE HORSEMAN AND THE LADY AT HIS SIDE
BUT THE TALE THAT CHILLS MY SPIRIT, MORE BECAUSE I KNOW IT'S TRUE
IS THE TALE OF JAYME DAWSON AND HIS CREW
YES THE TALE OF DAWSON'S CHRISTIAN AND HER CREW

**Comment by Eneocho** [comment]
Could you change this and carmen miranda's ghost on the filk playlist to the higher quality versions too?

**Comment by wotisjanitor** [comment]
make sure you keep the Harold Stein versions of the songs that we have as well. some people don't like the rocketman alternatives. Also, there's another version of Dawson's Christian sung by Vic Tyler on the "Free Fall and Other Delights" album which doesn't have the unfortunate sped-up high-pitched issues that the "Carmen Miranda's Ghost" version has on the rocketman archive as well.

**Comment by wotisjanitor** [comment]
> Could you change this and carmen miranda's ghost on the filk playlist to the higher quality versions too?

we should honestly just make a rocketman filk playlist and a harold stein playlist

**Comment by wotisjanitor** [comment]
Also a bit of filk trivia: 
Vic Tyler has absolutely no other music besides what you can find on Carmen Miranda's Ghost and Free Fall and Other Delights because he was not a singer. He was an employee at Off Centaur that they pulled into the recording booth to sing songs written by Duane Elms. Kristoph Klover still has contact with Vic, who now lives in the Bay Area and they discussed recording new music somewhat recently. However, that idea never went through

**Comment by Eneocho** [comment]
> > Could you change this and carmen miranda's ghost on the filk playlist to the higher quality versions too?
> 
> we should honestly just make a rocketman filk playlist and a harold stein playlist

This works too.

**Pull request merged**
