### PR TITLE
Unsnowflakes siding

### LINKED ISSUE #23686: Wood siding panels are unavailable outside of mapping(?)
#### Description of issue

You can find these on roid and some other rare places, it's the yellow/gold panel detailing on wooden underfloors.
image
Doesn't seem to be any way to construct them. I found only one related mention in the code, and that's stuck under a `isgrasstile()` check which is extremely weird.

#### Server revision
3d464aaf1e3345d2a8ee372e7d478af567ab0efb

### LINKED ISSUE #24018: Roid bar "wood" tiles and materials
image
The "wood" tiles here are covered by the gold outline. When attempting to screwdriver the wood it doesn't work, when crowbarring it pries off the outline. Now you cannot pry off the actual wood, and instead it functions as if it were plating. You can place any other tile on it but when prying off the new tile the plating still remains as wood. This is a crime to aesthetics.
Also the bar backroom on roid doesn't have a stack of metal and glass, it has exactly 1 (one) glass and metal sheet.

### PR DESCRIPTION
**Pull request by beesil**
[qol] Converts the gold siding used on Roidstation and Synergy into a decal (instead of a tile stacked on top of a tile). Adds it to the tile painter, along with a black variant that I found unused sprites for.

Closes #23686
Closes #24018

:cl:
 * bugfix: Converts golden siding used on Roidstation and Synergy into a decal.
 * rscadd: Adds two variations of siding to the tile painter.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Something is definitely wrong with these map diffs and I predict mapdiffbot man will come here and claim your skull for a trophy

**Comment by beesil** [comment]
I had to use the dreammaker map editor to remove the double tiles since sdmm can't handle them. Not sure how to fix the big diffs since we don't have maptools anymore.

**Comment by beesil** [comment]
also that's fine because i'll kick his ass in a fight

**Comment by beesil** [comment]
Saving the maps in sdmm after making the changes in dreammaker seems to have fixed it. It's still mad about shuttle walls but the files look fine.

**Comment by Eneocho** [comment]
Is it possible to also have the space-gold tiles? Those around the cyber mannequin on roid, right next to cargo.

**Comment by beesil** [comment]
@Eneocho You can make those now by using the tile painter decals on a glass floor, the mapped ones are still in (converted from tiles to decals).

**Comment by Eneocho** [comment]
based

**Pull request merged**
