### PR TITLE
Fixed invisible mysterious package

### LINKED ISSUE #17777: Shard delaminations can give you Mysterious Packages with no icon
#### Description of issue
After a shard delamination, I noticed that I now had in my hands a Mysterious Package with an odd icon. I couldn't open it, but I could drop it.

#### Difference between expected and actual behavior
Is this caused by hullucinations happening across the station or is it just a bug?

#### Steps to reproduce 
1 - Be on Boxstation
(Optional?) - Be a Changeling
2 - Have someone delaminate the supermatter shard.
3 - Enjoy your package.

#### Specific information for locating

capture

#### Length of time in which bug has been known to occur

Who knows

#### Server revision

Game: 1f76a015992ad17d7641e9c88b92262b9170a5cd 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [] Issue could be reproduced at least once
- [] Issue could be reproduced by different players
- [] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by DamianX**
Fixes #17777

### CODE REVIEW

**Comment by DamianX** [comment]
@ihadtoregisterforthis please elaborate

**Comment by SonixApache** [comment]
Are you removing C4 as a sprite option, or does that sprite not exist at all?

**Comment by DamianX** [comment]
image
`icons/obj/assemblies.dmi` contains a sprite with no assigned icon_state (Shown above). Such sprites are used by default when a non-existent or null icon_state is set.
`c4small_1` does not exist in `icons/obj/assemblies.dmi`, so the icon above is shown.
This is a bug.
`plastic-explosive0` is the sprite for c4, which works correctly.

**Comment by Pathid** [comment]
Suggest putting `plastic-explosive2` instead of taking it out, since that is the correct state for an armed c4.

**Comment by ihadtoregisterforthis** [comment]
Yes, blame shows that six years ago the icons got changed, but `c4small_1` wasn't. It's actually still there on `syndieweapons.dmi` as `OLDc4small_1`
oldc4small_1
Using the modern icon is probably for the best, and it's certainly more of a fix than removing the chance of getting a fake active c4.

**Pull request merged**
