### PR TITLE
Some character pref model changes

### LINKED ISSUE #9609: Sec. Role Character Setup Has Advanced Bomb Suit Helmet On
(WEB REPORT BY: kinggrimlock REMOTE: 172.93.109.202:7777)

> Revision 5478d4dc33ca2847caf1e298fa3a3e48a2a8e2a8
> 
> General description of the issue
> Security officer roles (Head of Security, Warden, and Security Officers) have an Advanced Bomb Suit helmet on their heads instead of what they would normally wear in the character setup screen.
> 
> What you expected to happen
> I expected my character to be wearing a HoS/Warden Cap or Sec. Helmet in the character setup screen when my preferred role was set to HoS, Warden, or Sec. Officer.
> 
> What actually happened
> My character was wearing an Advanced Bomb Suit helmet instead.
> 
> Steps to reproduce if possible
> 1. Enter Character Setup Screen.
> 2. Click on Occupation Preferences.
> 3. Set your preference for Head of Security, Warden, or Security Officer to High.
> 4. Save your changes, and exit back to the Character Setup screen. Your character will now be wearing an Advanced Bomb Suit helmet.

### PR DESCRIPTION
**Pull request by Konater**
Gives security real hats to wear, black gloves are now black and mechanic now has an outfit
Fixes #9609

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Why berets instead of the standard Security helmets?
Also shouldn't the warden be wearing a warden hat, and the HoS wearing the HoS hat?

**Comment by Konater** [comment]
Berets don't hide the hair, warden is wearing his warden hat though
Also berets>helmets

**Comment by Kurfursten** [comment]
I know it's not in scope but could you please play dressup with the Mechanic role too?

**Comment by Shadowmech88** [comment]
The warden is wearing his hat? "policehelm" doesn't sound like a hat.

Anyway, my point still stands about the HoS hat.

**Comment by Konater** [comment]
outfits
How's this for mechanic? Just glubs, toolbelt, jumpsuit and shoes. I noticed the gloves on security, I'll change all bgloves to black to fix it
If anyone has any more suggestions please go ahead

**Comment by Probe1** [comment]
:+1: :eggplant: :100:

**Comment by Konater** [comment]
If I could I would do one for traders too but job_misc_high is undefined and I don't want to mess with it
AI/robot icons are but a dream

**Pull request merged**
