### PR TITLE
Fixes the abominable snowflake code for nearsighted crewmembers, also health scanner glasses

### PR DESCRIPTION
**Pull request by DeityLink**
which didn't even work since the prescription var of glasses is set back by initial() as soon as you remove them.

glasses now have a "prescription_type" var which allows coders to indicate which glasses would be a prescription version of this one if there is one. And if there is, the game will equip that one instead to nearsighted players.

image
image

:cl:
* bugfix: Fixed an issue where nearsighted players would not have the correct prescription glasses equipped in most cases when their job outfit already includes some glasses, even if those had a prescription version.
* imageadd: Prescription Health Scanner HUDs have a new sprite and are now called Health Scanner Glasses. They can also now be printed at R&D, and both them and the regular Health Scanner HUDs can be found in medical lockers.

### CODE REVIEW

**Comment by pedr69** [comment]
there's a thing where you can put HUDS ontop of the normal prescription goggles but it doesn't seem to work
https://github.com/vgstation-coders/vgstation13/blob/0593a00132f3333fb530cdc471a43b237fe2eceb/code/modules/clothing/glasses/glasses.dm#L64

i could have sworn i tried removing this shit and letting you combine the 2 but apparently i didn't
must be the dementia again

**Comment by DeityLink** [comment]
That was some hacky workaround that never properly worked. Or maybe it did but then someone changed the way nearsightedness work which borked it.

**Comment by pedr69** [comment]
yeah that was me but i think it was broken beforehand too
#30769

**Comment by DeityLink** [comment]
yeah I meant beforehand as well, the "putting mesons over glasses" stuff never quite worked

**Pull request merged**
