### PR TITLE
THE ADMINBUS UPDATE

### PR DESCRIPTION
**Pull request by DeityLink**
adminbus

List of WEBMs, from the most recent to the oldest
- Final version with HUD (feat. working headlights) https://dl.dropboxusercontent.com/u/33846352/adminbus/Final%20version%2C%20featuring%20the%20HUD.webm
- Passenger List on the HUD https://dl.dropboxusercontent.com/u/33846352/adminbus/passengers%20list.webm
- Deployable mounted jukebox https://dl.dropboxusercontent.com/u/33846352/adminbus/mounted%20jukebox.webm
- Antag Madness https://dl.dropboxusercontent.com/u/33846352/adminbus/antag%20madness.webm
- Thunderdome split https://dl.dropboxusercontent.com/u/33846352/adminbus/thunderdome%20split%20and%20monkey%20suits.webm
- Teleportation https://dl.dropboxusercontent.com/u/33846352/adminbus/teleportation.webm
- Giving lasers and bombs to passengers https://dl.dropboxusercontent.com/u/33846352/adminbus/give%20lasers%20and%20bombs.webm
- Loads of Money and all access IDs https://dl.dropboxusercontent.com/u/33846352/adminbus/loadsofmone.webm
- Chained small Nar-Sie (you can chain the large one too) https://dl.dropboxusercontent.com/u/33846352/adminbus/narsie%20hook.webm
- Mass Rejuvinate https://dl.dropboxusercontent.com/u/33846352/adminbus/rejuvinate.webm
- testing the Singularity Hook https://dl.dropboxusercontent.com/u/33846352/adminbus/hookshots_for_players_might_be_fun_too.webm

adminbus

GENERAL STUFF:
-Added a new vehicle: the Adminbus. Enter as driver by drag-dropping yourself onto the bus. Exit by clicking on the bus. Can be spawned by admins with +FUN access from the Secret Menu.
-The Adminbus is indestructible.
-Players can also enter the bus as passenger by clicking on the bus, and exit the same way. Unless they are Test Dummies or Ian, the door needs to be openned by the driver.
-The bus can only carry up to 16 passengers.
-The Adminbus can move through any obstacle. Unlike the Firebird, the Adminbus doesn't have a cooldown after going through an obstacle. Exception: the Adminbus will go through teleporters.
-All mobs and bots inside the Adminbus are completely isolated from any form of damage (including singulo). They aren't targeted by hostile mobs either.
-While inside the Adminbus, Mobs can still use their hands, change their clothes, use and throw items out of the bus, etc...
-The driver of the Adminbus gets provided with a GUI to use the various abilities of the vehicle. The HUD disappears when the player leaves the bus.
-Passengers of the Adminbus get displayed on the top bar of the GUI.
-Admins who wish to delete an Adminbus are recommended to do so by using the Red button on the GUI, which will remove the Adminbus' associated entities as well.

ABILITIES:
-The Adminbus has three settings dictating his handling of rolling over mobs and bots: 1-Capture the mob; 2-Stun the mob and deal 5 brute damage; 3-Gib the mob
-The Adminbus can release all its passengers on the tile to its right. (They are all released in quick succession, not at once)
-The Adminbus can teleport its passengers to the tile where they were created (arrival shuttle for the latejoiners, genetics for the cloned, etc)
-The Adminbus can teleport itself to ANY area on the map.
-The Adminbus is equipped with a Singularity Hook: Fire at a Singularity (Or Nar-Sie/Mr.Clean) to capture them. Captured singularities cannot move by themselves anymore.
-Before it touches a Singularity, every part of the chain moves along with the bus. However once a singularity is anchored, the chain behaves in a more realistic way, each part following its parent when the latter moves away.
-The Hook cannot be used again until it has returned to the bus, so you cannot drag more than one singularity at once.
-The chain and the singularity will follow the bus even through Z-levels or through teleportations.
-The Adminbus is equipped with headlights. The light actually comes from an invisible structure 2 tiles in front of the bus. The headlights's luminosity can be set to either 0, 2, or 3.
-The hostile mobs spawned by the Adminbus won't attack each others, nor will they attack Test Dummies or Ian.
-Can spawn 5 clowns around itself, they will only attack if provoked.
-Can spawn 5 space carps around itself.
-Can spawn 5 space bears (10% chance of spawning a russian instead).
-Can spawn 5 pine trees.
-Can spawn 5 Red-Eyed spiders.
-Can spawn a large Alien Empress.
-Can Remove all the spawned mobs at once.
-The Adminbus can instantly rejuvinate all mobs at a range of 3 or less.
-The Adminbus can instantly repair all broken floors at a range of 3 or less. (as well as repair broken computers, wall girders, turn glass shards into glass sheets, and repair broken computers)
-The Adminbus can spawn LOADS OF MONEY (do not use when above space, bugged for some reason) and throw it around.
-The Adminbus can spawn Captain Spare IDs and throw them around.
-The Adminbus can distribute infinite laser guns and fuse bombs to its passengers (and delete them)
-The Adminbus can send all its passengers to the Thunderdome's Observation Lodge.
-The Adminbus can send all its passengers to the Thunderdome's Red or Green team. Passengers will be stripped of their belonging and equipped with Thunderdome gear. Their belongings will be stored in packages located in the Thunderdome's Admin lodge.
-The Adminbus can split its passengers between the two teams. If there is an odd number of passengers, the Red team will have one more fighter.
-The Adminbus has its own mounted jukebox, only usable by the driver. The bus needs to stand still to deploy the jukebox, and the latter will turn off as soon as the bus starts moving again. (because sound code, blablabla)
-Antag Madness, see bellow.
-Added animations for mobs/bus spawning/teleportation.
-Added animation for when admins/adminbus rejuvinate players.
-Added a bunch of sounds for some of the adminbus' abilities.

ANTAG MADNESS:
-Every player with a mind inside the bus becomes a random type of antag, picked among traitor, changeling, vampire, cultist, head revolutionnary, nuke ops, wizard, death squad ops, infected monkey.
-Can be either instant, or applied after a delay. Mobs get messaged when they are going to turn antag.
-Mobs get equipped with gear fitting their role, and get various overpowered advantages depending on their role (vampire have 500 usable blood, cultists start with all words, traitors have 30 telecrystals, etc...)
-Admins can right click mobs to apply antag madness direcly, and even choose a type of antag in particular.

Changes not directly adminbus-related:
-Admins now have the ability to instantly spawn themselves as a Test Dummy, equipped with basic clothes, and Admin ID.
-Admin ID: Basically Captain access+Centcomm access+Syndicate access+Pirate Ship access.
-Nuke Ops now spawn with /sunglasses/prescription, so players with bad eyesight aren't screwed anymore.
-Fixed the Syndicate Shuttle's console showing unpowered
-Added a new device: the Code Breaker. Used on a nuke, gives the nuke's code after 10-30 seconds of decrypting if you don't move. Given to players turned Nuke Ops by antag madness. (can also be deconstructed at R&D)
-Added a new device: Fuse Bombs. Press the bomb to lit the fuse, press it again to turn off the fuse. Starts with 5 seconds on its fuse. creates a (-1,1,3) explosion. Can be distributed to passengers of the Adminbus. (the adminbus can also revoke all of the distributed bombs)
-Added a new weapon: Infinite Laser Gun. Can be distributed to passengers of the adminbus. (the adminbus can also revoke all of the distributed guns)
-Added two new ID cards: Thunderdome Red & Green IDs. Given to the competitors of the thunderdome. No particular access. Might become an objective for thunderdome contestants to steal the IDs of their opponents.
-Added two new team-colored belts that can hold the Thunderdome IDs. Given to the competitors of the thunderdome.
-Added monkey-sized green and red jumpsuit. Given to monkeys sent to the thunderdome by the adminbus.
-Player controlled simple_animals can now unbuckle themselves.
-Improved the on-mob sprite of the death gas mask. Also gave the mask an alternate icon_state for when it is pulled back up.
-Sound systems (jukebox, wall-mounted speakers, boomboxes) now obey the "Last Arrived, First Served" rule. Which allows Jukeboxes to be placed in areas that already had a sound system in them (previously, there was no way to replace a room's sound system)
-Turning a sound system off and on will place it back on top.
-Added a new hair style: "Marisa", given by Antag Madness to female wizards.
-Hairstyle can now have overlays unaffected by colouration (ribbons and hairclips ahoy!)
-Updated the "Nitori" hairstyle to use the new system.
-Updated the sprite of small Nar-Sies, so they no longer show the large Nar-Sie's overlay, and so their sprite actually matches the area they destroy.

adminhud

### CODE REVIEW

**Comment by Senaat1** [comment]
:+1: merge this

**Comment by DeityLink** [comment]
never 4get

**Comment by mrflarg** [comment]
unmerge this

**Comment by d3athrow** [comment]
unmake flarg

**Pull request merged**
