### PR TITLE
Tweaks KEEPER because no one really minds MoMMIs talking on Binary

### PR DESCRIPTION
**Pull request by ValkyrieSkies**
As it says, just removes the restriction on MoMMIs talking in Binary chat because it's a generally accepted exception anyway. Still doesn't allow them to take orders from the silicons or to interact with the silicons, so more or less keeps things the way they are without the blatant rulebreaking no one cares about.

:cl:
 * rscadd: Minor tweak to MoMMI law to allow binary communication (but not action/orders)

### CODE REVIEW

**Comment by clusterfack** [comment]
Hilariously pointless and ugly change

**Comment by small-boss** [comment]
wouldn't this allow mommis to tell borgs about antags that they see?

**Comment by Duny-** [comment]
MoMMIs will always be breaking their laws all the time, it's pointless to try to fix that. And this could be used as an excuse to say shit like antag location to other silicons.

**Comment by ValkyrieSkies** [comment]
@clusterfack
It's a simple clarification of an accepted house rule that makes it easier for new players. Furthermore, how pretty it looks is irrelevant compared to how easily understood it is.

@Duny- @small-boss
Siccing an AI and their borgs on someone sounds like involvement beyond communication to me. I can see how this could be an issue in some regards however, could you suggest better wording?

**Comment by Pathid** [comment]
Tattling is arguably a form of communication.
I'll suggest adding instead:
"Communication is involvement when it helps or hinders a particular being in their goals.",
to the MoMMI intro text preferably.

**Comment by ValkyrieSkies** [comment]
A solid solution. I'll do that tomorrow, I've retired for the night.

**Comment by Aurx** [comment]
No lawset we actively use actually works exactly as written.  
Pathid's solution seems soundest here.

**Comment by PJB3005** [comment]
IMO, KEEPER is a lost cause. The best we can really do is keep it as is, and make it really explicit that it's for immersion and give a detailed explanation of how you should play MoMMI.

**Comment by Aurx** [comment]
Any MoMMI lawset would be a lost cause: You'd have to condense all of MoMMI policy without losing anything.

**Comment by ghost** [comment]
remove station mommis and give them a new lawset to let them kill anyone who dares step into their magical realm.

**Comment by Ratvar** [comment]
Who are those "no one" you are talking about, duh? I see at least eight people oppose.

**Comment by Fruktlimpa** [comment]
What is the point? 
MoMMI's are allowed to speak to silicons as long as it isn't relaying any round information. Small talk is allowed.

**Comment by jknpj** [comment]
`This law does not apply to communication within the Binary & Damage Control comm channels.`

Why not edit their spawning notes instead of this? No point in touching MoMMI's law 1 to clear something trivial and make the whole lawset more confusing because **YOU JUST FUCKING PURGED THEIR LAW ONE AND MADE 100% LEGAL TO INVOLVE THEMSELVES WITH THE MATTERS OF OTHER BEINGS AS LONG THEY DO IT OVER BINARY**

**Comment by DamianX** [comment]
Can I close this?

**Comment by ValkyrieSkies** [comment]
Heiki heicchara.

**Pull request closed without merging**
