### PR TITLE
Revert "Reagents added to a mob can heat up or cool down the mob"

### LINKED ISSUE #33812: Nutriment freezes the character.
(WEB REPORT BY: ezudiko REMOTE: 206.221.180.138:7777)
# Revision
c5d2df28ee81ca4c7d57f4a2a3dd548a7995c084

# Description
Eating food at chemtemp 293.15 will cause the character to be too cold. Binge eating will freeze and make you collapse.

# Steps to Reproduce
Spawn 4noraisins. Eat the whole packet. Get the "too cold" debuff and collapse.

# What you Expected
Not to die eating raisins.
# What Actually Happened
Getting hypothermia from raisins.

### LINKED ISSUE #33814: Medbay thermal regulators don't work
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
04be7d7ea701fb590d755623543e7ebba433a336

# Description
Thermal regulators don't heat up patients at all and sometimes only heat them up partially
# Steps to Reproduce
use heat regulator
# What you Expected
for patient to not be frozen from cryo and not start dying to frost burns

might be related to the bug that causes food to freeze you
# What Actually Happened
I'm glad he's frozen in there and we're out here

### PR DESCRIPTION
**Pull request by bathosbathtime**
Reverts vgstation-coders/vgstation13#33698
closes #33814
closes #33812
Going to need to take another swing at this one it seems.

### CODE REVIEW

**Comment by Exxion** [comment]
Normally I'd give some time to allow for a fix rather than a revert, but "eating a bag of raisins kills you" is pretty gamebreaking

**Comment by Eneocho** [comment]
I TOLD YOU HINAICHIGO THAT THE FOOD SPAWNED WITH LOW TEMPERATURE CHEMS. I TOLD YOU ABOUT STAIRS MAN

**Comment by Exxion** [comment]
This isn't really the right place to put this, but I just looked through some of the `specheatcap` values for various reagents and what the fuck were people smoking when they wrote these? Why does space cleaner have like 15 times the specific heat of water? That's far from the most absurd value (phalanximine has a specific heat more like 3000 times that of water), but it's just such a weird one. Maybe some of these should be rebalanced before the feature is re-added.

**Comment by Eneocho** [comment]
>Why does space cleaner have like 15 times the specific heat of water? 

Cause the guide at the top of the reagents page says to base it on real chemicals or to calculate it with that handy dandy formula they give you `SHC = (for(components of recipe) total_SHC *= component SHC)`. 
Space cleaner is just ammonium hydroxide, which has a specific heat of 80.8Jkg-1.

**Comment by Exxion** [comment]
> Cause the guide at the top of the reagents page says to base it on real chemicals or to calculate it with that handy dandy formula they give you SHC = (for(components of recipe) total_SHC *= component SHC).

OK but why that formula? That formula doesn't make any sense

> Space cleaner is just ammonium hydroxide, which has a specific heat of 80.8Jkg-1.

Pretty sure your number is incorrect, though I can't find a reliable actual value. First, the unit is [energy]/[mass][temperature], not just [energy]/[mass]. Second, values for J/kgK (as opposed to J/gK) would most likely be in the low thousands, such as water's 4184. However, the in-game number of 60170 for space cleaner is definitely also incorrect.
(It's defined in the code as 60.17 J/gK, which is 60170 J/kgK)

**Comment by Eneocho** [comment]
> OK but why that formula? That formula doesn't make any sense

It makes sense for chemicals you have no real life comparison to, like the midazoline. You add the specific heat of the components and multiply.
As for that number, it was a quick google search I didn't really check. A couple more sources state 4.420 J/g-°C or similar.

**Comment by Exxion** [comment]
> It makes sense for chemicals you have no real life comparison to, like the midazoline. You add the specific heat of the components and multiply.

No, I mean there's no reason at all that a compound's specific heat should be the product of the specific heats of its constituents. It makes no physical sense to use that formula. You get enormously vast numbers for anything besides the simplest precursors.

**Comment by Eneocho** [comment]
I think that was the intention.

**Comment by Exxion** [comment]
But why? It's not how it works IRL and I can't think of a good gameplay reason. It also means that any complex compounds that actually exist will have much lower specific heats than those that don't.

**Comment by Eneocho** [comment]
No idea, I wasn't the one who made that formula.

**Pull request merged**
