### PR TITLE
Adds blue helmets to the Security Vendor's premium section

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Now you can barge into R&D with style!

:cl:
 * rscadd: Added blue helmets to the Security Vendor's premium section, which can be accessed by using coins.

### CODE REVIEW

**Comment by Com1cThunder** [comment]
As long as wearing the blue helmets makes you valid then this will be an excellent addition

**Comment by BomberBro** [comment]
Let it be known on this day that at least one man tried to stop the inevitable "meme item that gets added because it's bus only" -> "meme item later gets added in fully with a minor change" pipeline.

**Comment by Kurfursten** [comment]
Seems more like vault loot to me - just a little touch for flavor

**Comment by Eneocho** [comment]
> Seems more like vault loot to me - just a little touch for flavor

Gating stuff means it'll never see any use. What's the point of adding the goddamned antichrist helmets if they can't antichrist with the boys (the other officers).

**Comment by boy2mantwicethefam** [comment]
@BomberBro This happened as a result of some discussion about the fact that bus items are never ever seen, admins literally forget about all the bus stuff and they never end up in a round for maybe years. Remember the Trauma Team PR (#29796)? Where is the Adminbus? The robot duck? What about #29994?
The blue helmets are normal enough that you can feasibly get away with them appearing in a round, since we already have the more "different" Half Life 2 metro-cop suits available under contraband.

**Comment by Eneocho** [comment]
Oh shit you reminded me of that. I'll try to map the carp boxes to xenobio again.

**Comment by WindowsErrors** [comment]
> bus items are never ever seen, admins literally forget about all the bus stuff and they never end up in a round for maybe years

the radio backpack? the emancipation gate? the pocket watch? the luna dial? armor shard accessories? the mind batterer? the debugger multitool? the stormtrooper kit? the glock modification parts? inflatable floors? reinforced strap voucher? fingerprint cards? goon ores?
Screenshot (1818)

I only got about halfway through before I lost patience, if it wasn't for vox creep we probably wouldn't even know about half the shit that goes unused

**Comment by Kurfursten** [comment]
Fingerprint cards, inflatable floors, stormtrooper kit, are all used
My PR to make goone ores useful got a mixed response #25660
Radio backpack was supposed to be for a special event that got cancelled

**Comment by Eneocho** [comment]
>My PR to make goone ores useful got a mixed response https://github.com/vgstation-coders/vgstation13/pull/25660

The thumbs were mostly positive however.

**Comment by BomberBro** [comment]
\>Remember the Trauma Team PR (#29796)? 
I mean, it's a video game reference to a specific video game. It's a shame that they haven't been used for a bus but it also doesn't give it carte blance to be in the game.
\>Where is the Adminbus? 
Talk to the admins, this is an item you and I would both agree should be bus (heh) only.
\>The robot duck? 
In the game and derails a round whenever the xenoarch gets his slimy paws on it.
\>What about #29994? 
What about it? It wasn't intended to be a bus item and the creator never figured out how to add it.
\>The blue helmets are normal enough that you can feasibly get away with them appearing in a round, since we already have the more "different" Half Life 2 metro-cop suits available under contraband.
Honestly they're not that bad, they just don't really fit the base game imo except for hyper specific bus. The secvend becoming Theatervend 2 is an issue in of itself

**Comment by Eneocho** [comment]
I for one want them added so I have an IC reason to schizo against the sectide.

**Comment by ShiftyRail** [comment]
I love the antichrist.

I am not sure about the change to be honest. To me this looks more like what Bomber says than genuine addition of content. There's certainly an argument for having those helmets in the game, but probably not directly in the sec vend.

**Comment by KingofHONK** [comment]
Downvoting because I hate sec

**Comment by Kurfursten** [comment]
I hate the antichrist meme

**Pull request merged**
