### PR TITLE
Pulling icon updates instantly (Fixes #7669)

### LINKED ISSUE #7669: Please update the drag/pull icon as soon as you start or stop drag/pulling, not in the next Life() tick
Going into throw intent updates the icon instantly, drag/pull should do it too

### PR DESCRIPTION
**Pull request by 9600bauds**
Oh look another gigantic pile of spaghetti that desperately needs a refactor!
I'd better not touch it ever

Fixes #7669

### CODE REVIEW

**Comment by ghost** [comment]
Unless I'm missing it, you can also have the macro instantly update the HUD

Should be CTRL+Click somewhere

**Comment by 9600bauds** [comment]
It's updated in the proc that is used for all the means of pulling

**Comment by 9600bauds** [comment]
For some ass-reason this is runtiming, give it time

**Comment by 9600bauds** [comment]
Oh nice, git somehow ate my last commit

**Pull request merged**
