### PR TITLE
Makes genetic powers have a guaranteed chance to manifest

### PR DESCRIPTION
**Pull request by Arzion5**
This is my first PR on vgstation, couldn't have made this PR without the aid of @unid15 . I am not actually sure if it works, but it's a few harmless numbers. I will test this locally as soon as possible.
The problem with genetics is that it's a very long task. There are 54 different blocks that you have to get to their respective thresholds to activate them. However, genetic powers have only a chance, on top of being lucky enough to reach the threshold, to manifest. The genetics machine is already unreliable because of the high chance of other blocks being affected aside from the one you've changed, and upgrading the components only causes injectors to recharge faster. This PR has been made with the purpose of making genetics less annoying on the long-term, and hopefully make it at least a bit faster as you won't waste too much time irradiating yourself with the injectors until the power actually manifests.

:cl:
 * rscadd: Genetic powers now always manifest, instead of having a random chance

### CODE REVIEW

**Comment by gbasood** [comment]
nope
nope
nope
nope
nope

this was always a thing because getting hulk reliably is stupid

**Comment by DamianX** [comment]
delet this

**Comment by ghost** [comment]
So basically you want to make genetics 2 times faster and 3 times more OP.
Nice.

**Comment by Arzion5** [comment]
@gbasood Hulk is still nerfed, hulk is still only an ability that knocks you down afterwards, and hulks are always still valid if they wreck the station, along with the risk of getting punished if they wreck the station too much. Really, all you have to do to defeat a hulk is to evade it but stick to it, until the duration expires and they are knocked out.
This PR aims to make Genetics gameplay at least a little bit faster and a little bit better. You will no longer have to constantly wait to make duplicate block injectors because the power did not activate.

**Review by PJB3005 — APPROVED** [review]

**Comment by gbasood** [comment]
Hulk is too good to give someone for simply getting the gene value above threshold

**Comment by PJB3005** [comment]
Getting a gene above DB really isn't that hard.

Making genetics even *more* easy is like the last thing it needs. It's already one of the least interesting jobs you can have.

**Comment by AI-Is-Rogue** [comment]
You don't need to inject the same block. Any injection has a chance to manifest each of your inactive powers.

**Comment by Aurx** [comment]
Genetics needs work, yes.  Genetics being RNG grinding central is a pile of shit, yes.  

But the solution isn't to remove part of the RNG and call it a day, since the RNG is a balancing factor on the stupid bullshit people have given to genetics.

**Comment by Arzion5** [comment]
@gbasood Hulk is a power that has an equal chance of manifestation as any other power except telekinesis. Hulk has been nerfed over the years, and the curent version on /vg/station is an ability that knocks you out when the duration expires. It is fairly easy to counter a hulk ; Evade the hulk but stick to it until it gets knocked out. If a hulk is already cuffed, just move them around. If enough people want, I will add a separate activation_prob to the hulk gene, that will be the current 45% chance of manifestation.

@PJB3005 Genetics is a dull job with great rewards. The machine is highly unreliable and the unreliability cannot be reduced by component upgrades. Getting a gene above DB requires luck due to the unpredictable nature of the mechanic, and it is detrimental to discover that you have wasted a potentially large amount of time trying to get a block above DB only to find out it was a disability, but this PR does not cover this issue. Additionaly, it is very unlikely that you can map out the entire genome by the time the round ends, because of the large amount of genetical modifications that have to be done and the luck required. In my opinion, requiring another check after reaching a threshold is detrimental and annoying, as you'll spend a considerably large amount of your time repeatedly injecting yourself with duplicate injectors to find out the power. This PR is a Quality-of-Life change for genetics so that when you inject yourself with a power, there is no further chance of the mutation not appearing. Injector A will give you Power A, with no strings attached and no obstacle. I can compare this random chance of manifestation after having already injected yourself with the power with the videogame term **"Artificial Difficulty"**.

@AI-is-rogue You are correct. But I would like to point out that jumping immediately to the next block can lead to labelling issues, as you will not likely know which block can do which. With disabilities, this is simple enough to fix, as a disability message will appear in red while a power message will appear in blue, but this can lead to a minor issue if you stumble upon another power block right after you have injected yourself with the previous power block. Again, you have a very good point, and I acknowledge it.

@Aurx Many "progression" departments and jobs exist with an end-game in mind. R&D can supply powerful upgrades and tools to the rest of the station, Xenobiology and Xenobotany allow for slimes and plants (respectively) to be created, with the former being harvested for miscellaneous items and effects and the latter that can be spread across the station or whose fruits can be given to the crew for other kinds of unique effects, Botany can grow and cultivate unique plants that they can give to the crew and to the chef, and in turn the chef can create very nutritious food. Virology is also included, as their end-game is getting lucky enough to harvest the right symptoms to spread across the station, which are not limited to : Occasionaly being pumped with tricordrazine, telepathy, being a glowing crewmember, and more. For the same purpose, Genetics' end-game is to fully explore the genome that features many powerful abilities, and share the power blocks with the crew. However, the problem with Genetics is that it is just simply too slow. It is perhaps THE slowest progressive department in the game, because it simply takes too much time and luck to map out the genome, and there is not enough time to map it by the time the shuttle arrives. This PR aims to hopefully make Genetics take less time in mapping out the genome, and give people Power A from Injector A with no further obstacles.

**Comment by DamianX** [comment]
People can complete genetics in under 30 minutes already.
You're welcome to rework genetics to not be "artificial difficulty", but this PR just trivializes the research to the point where you would see the full genome literally every game.

**Comment by Aurx** [comment]
Nice wall of text.  
Address the balance issues though.

**Comment by PJB3005** [comment]
As others have said people already finish everything in 30 minutes.

Even if they didn't, I just want to remind you that there's two geneticist
slots, and that just because you can map out everything does not mean it
should always be possible.

**Comment by Kammerjunk** [comment]
With a single console, I've gotten it all done in exactly 30 minutes twice or thrice over ~5-7 attempts (including interruptions). Due to only labeling them with a green colour if injection doesn't activate a defect and a red colour if it does (and no text), that'll mean rolling on multiple powers at the same time and most powers usually being activated when I'm done with the genome. 30 minutes is a pretty good time - intense and/or quick gamemodes like ops, blob, heist, revs, maybe malf if it rushes will be just about over, "regular speed" modes like tator, maybe cult, maybe malf should be just about getting into it, and ling and vamp are still a good two to three hours from getting started.

When I've gone through the genome, I usually hand off a box to sec and then leave another box in the bar. Say that's the norm: At best (genetics has had time to hand out enough power stabbers for everyone tenfold - ling, vamp), you're accomplishing almost nothing. At average (genetics has just put a box in the bar and one in sec), you're giving a bunch of crew people a guarantee of hulk, heatres, coldres(?), nobreathe, noprints, shock immunity, telekinesis, eat, xray, remote view, and telepathy. At worst, genetics can luck out and get the really powerful ones halfway through the genome and hand them out so people can kill the ops/blob/revs/heads/AI.
If only sec gets the powers, all of the above still apply but with a massive imbalance in favour of sec in the modes that don't involve outside antags.
If only the geneticist gets the powers, who really cares if a geneshitter doesn't get his free superman status? He's happy as long as he gets to super fart + toxic fart near people

In addition to all of the above, as @DamianX said, you're not removing the artificial difficulty in genetics, which mainly comes from block radiation being (almost) random.

**Comment by Arzion5** [comment]
I concede to your point. However, is Genetics fine as it currently is or should I try to decrease the power activation threshold instead?

**Comment by SonixApache** [comment]
alternative option: delete genetics
alternative alternative option: port goon (tg?) xenogenetics for maximum memes

**Comment by gbasood** [comment]
we could use different genetics work because I agree than an RNG roll is stupid
but just removing the RNG is bad and breaks balance horrendously
so until it is redesigned we can't just do what this PR sets out to do

**Comment by Aurx** [comment]
Genetics isn't really "fine".  It's a godawful chore to play.  The flip side is that's currently necessary for limiting it.  There's no easy and obvious "less RNG" fix that's balance-safe.  

If you really want to be the hero genetics deserves, you'd need to rework the system.  
I've always felt that Genetics should be a puzzle of mixing and ordering "base pairs" (characters) inside "chromosomes" (strings) to create "genes" (substrings, perhaps) to turn mutations on/off.  
That said, a really proper overhaul would need three primary things:  
A: Not plausible to write a program to handle better than a human can.  This would be easiest by making the underlying problem NP.  I haven't worked with much string analysis, so can't say for sure if such is plausible for my idea.  Though, I know Longest Common Substring is in P, so genes-as-substrings may be doomed to efficiency.  
B: Despite A, intuitively solvable by humans in a way that you can get better at over time.  IE, skill based.  
C: A newbie must be able to get some success in a round, and a master must not be able to five-minute run genetics.

**Comment by Hugh-G-Rection** [comment]
For what it's worth, while I agree with everyone that this upsets balance for those of us who are ~oldfag powergamers~ already fast with genetics, I'd like to say that your head is in the right place (mostly) and you shouldn't take this as a wholly negative experience. Do your local tests, get the code working as intended, and shelve it as a learning experience and move on to the next thing you'd like to fix/fuck up. 
Just know that most balance changes like this will likely be controversial in one way or another.

**Comment by gbasood** [comment]
Pretty much. I think most of us agree that you did find a problem with genetics that could be fixed, the problem is that it's not as simple as the solution this PR gives.

**Comment by Arzion5** [comment]
I am aware of this, do not worry. However, I still feel that there is a problem with Genetics. Reworking genetics as a whole is beyond my abilities, but the most I can do is make it a little bit better. I am planning on making a PR that will instead reduce the thresholds for all powers to activate, but I would like feedback if possible.

Edit : By the way, @Kammerjunk how do you actually manage to do genetics so fast?

**Comment by Hugh-G-Rection** [comment]
Blast a monkey with mutagen+radium spray/smoke to crank everything to DAB instantaneously

**Comment by PJB3005** [comment]
This seems pretty decisive and the discussion has been dead for two weeks.

**Comment by Aurx** [comment]
Of course the discussion is dead, the geneticist is too busy looking for powers to clone it!

**Pull request closed without merging**
