### PR TITLE
AStar subsystem for bots

### PR DESCRIPTION
**Pull request by ShiftyRail**
Continues @MadmanMartian's work on an AStar subsystem for bots.
Besides a good deal of code cleanup (botcode still has problems after that, but at least it's not longer a totally unreadable mess), this will also make bots lag less if many of them are pathing at the same time.

Most of the heavy lifting was already done by R0B0, now all we need to do is just to convert old code into new code. 

The code cleanup is now entirely done. wasn't easy.
:cl:
- experimental: The code which pilots bots (securitrons, medbots, mulebots...) went under a complete overhaul. Bots should be more aware of their surrondings and react faster, and having too much bots at the same time will no longer slow down the server. Please report any bugs or unexpected behaviours to the github.

### CODE REVIEW

**Comment by SonixApache** [comment]
this kills the shifty

**Comment by ShiftyRail** [comment]
Good news : mulebots work (and this wasn't as easy as it looks like)
Better news : I understand the feel of the code and that's a good thing
Bad news : some runtime is appearing and I don't know why

**Comment by ShiftyRail** [comment]
Only thing (that I saw) that remains to be fixed is that sec bots, and emagged dracula bots, are still slow as heck when arresting or chasing someone.

The variable which is supposed to increase their speed (`steps_per`) doesn't seem to work when they're not on patrol.

Beepsky might have a problem and could be overzealous and compute more paths than needed, but I'm not sure if it's just him.

That's all for today

**Comment by ShiftyRail** [comment]
I've finally done it. Bots should work completely fine now.

All that we have to do is to wrap it up in a subsystem to reduce lag, and write up some documentation on the new botcode.

**Comment by ShiftyRail** [comment]
Working as intended, most testing done, debug message removed and documentation added.

**Pull request merged**
