### PR TITLE
Fur coats and Bear pelts

### PR DESCRIPTION
**Pull request by giraffism**
This PR adds in the new ultra low quality sprite work of bear pelts for polar bears, brown bears, and a fake brownbear pelt
bear pelts 2
(from top to bottom: Original spacebear (unchanged), blackbear (unused for now), brown bear, faux brown bear, and polar bear)

A second item added is a fur coat, think one of those big vintage fur coats. protective against the cold and offers slight armors stats. The belt can be unbuckled via the right click toggle verb on the coat (just like the labcoat)
fur coats 2

Thanks to everyone who insulted my shit ass spritework in the discord

:cl:
 * rscadd: Adds pelts for polar bears and grizzly bears
 * rscdel: Adds a new fur coat from the premium section of the suitvendor

### CODE REVIEW

**Comment by giraffism** [comment]
why is the mapping bot angry

**Comment by giraffism** [comment]
was a clothing PR merged in the last few days?

**Comment by giraffism** [comment]
git refuses to see these files as not conflicting. I had downloaded the new files, inserted my new sprites into said files, and use the files to replace the old files in there respective folders to no success, it still conflicts

**Comment by SonixApache** [comment]
ask someone in the coder discord to fix it for you maybe

**Comment by Kurfursten** [comment]
Your problem isn't that the file doesn't include the latest sprites, it's that git doesn't KNOW it includes the latest sprites. The solution is quite similar to what you've already done.

STEP 1. Save your new sprites somewhere safe, like the desktop in a dmi
STEP 2. Rebase to the bleeding edge. This will get you the latest versions of the files.
STEP 3. Import your icons back into the respective files.

Rebasing is a headache to learn, I know, but it's not bad once you know how to do it. It's a couple of minutes and the same commands every time.

**Comment by giraffism** [comment]
my god, it actually worked

**Pull request merged**
