### PR TITLE
Can now add robotic heads to the body

### PR DESCRIPTION
**Pull request by MadmanMartian**
Now is the age of steel

### CODE REVIEW

**Comment by RealestEstate** [comment]
so does it hold an mmi or a brain?

**Comment by MadmanMartian** [comment]
Brain

**Comment by RealestEstate** [comment]
we ICP's now

**Comment by SonixApache** [comment]
habbening

IPCreep

**Comment by Blithering** [comment]
Now we just need the ability to attach synthetic organs to a cyborg chassis to make a robotic torso

**Comment by Pathid** [comment]
Is there a way to put a brain or eyes into one of those?
https://github.com/vgstation-coders/vgstation13/blob/d68a8fd4d54440258f76b1d7882d3f94ce932165/code/modules/surgery/generic.dm#L21-L22

**Comment by MadmanMartian** [comment]
Thanks Pathid

**Comment by Orangerush** [comment]
*rubs hands* one step closer to IPCs. Seriously though does this mean you can add robotic head to your character sheet thing like robo limbs? Or is it only through robotics

**Comment by NigglyWiggly** [comment]
Robo torsos when
WHEN

**Comment by MadmanMartian** [comment]
Had an idea on how to do that

**Pull request merged**
