### PR TITLE
Makes return to lobby message less vague

### PR DESCRIPTION
**Pull request by Intigracy**

### CODE REVIEW

**Comment by clusterfack** [comment]
But that's wrong

**Comment by clusterfack** [comment]
You are returned to the lobby because you had become assistant if jobs are filled, and sec officers are not numerous enough to allow you to become an assistant.

**Comment by Intigracy** [comment]
```
    if(player.client.prefs.alternate_option == RETURN_TO_LOBBY)
```

**Comment by Intigracy** [comment]
You're not getting a debug message when being sent to lobby with the be assistant pref. Look a few lines up, it sets your ready = 0 and everything else without spawning you in, but no message.

**Comment by clusterfack** [comment]
Whoops, add that message to the one above it then when players get unassigned because they have become assistant and blah blah like I said

**Comment by Intigracy** [comment]
thar u go fam

**Pull request merged**
