### PR TITLE
Nerf vox trader suits.

### PR DESCRIPTION
**Pull request by Allspice**
The free jetpacks still make me think a bit, but eh those can be managed later.

box
deff

### CODE REVIEW

**Comment by Kurfursten** [comment]
Post image of map editor so we can make sure you didn't mess up the pipes

No offense, just gotta be sure

**Comment by kilozombie** [comment]
Anything to make Traders act less like assistants and more like traders.
The jetpacks feel fair for that purpose, though.

**Comment by Allspice** [comment]
deff
box

**Comment by clusterfack** [comment]
Oh god the rainbows, you don't actually play like that do you? You know that's fixable right?

**Comment by TheFriggenSawbones** [comment]
@clusterfack he plays like that to powergame 100% serious

**Comment by clusterfack** [comment]
Really? Why would he play like that to powergame when he could simply turn off hardware rendering to disable all lights?

**Comment by TheFriggenSawbones** [comment]
just saying what he told me MAN

**Comment by FudgePucker** [comment]
That should be added as a space drug effect.
REALLY FUCK MY SHIT UP FAM

**Comment by Durgen** [comment]
brb, suiciding succumbing

**Pull request merged**
