### PR TITLE
The Honkgiver [Ready for Review]

### PR DESCRIPTION
**Pull request by RealestEstate**
The honkgiver is what happens when you clownify the lawgiver with the rainbow crayon.
Only the clumsy can fire it.(this includes clowns)

6 unique firing modes!:
-Bouncy ball: Bounces off most things. It knocks mobs back when it smacks them in the face.  And then it bounces some more.
-Scream shot: Forces the target to scream.... even silicon. Unlike a taser however, it will fill the target with a burst of energy and make them move faster.
-Rapid pie-er: fires pies in a burst. Great for pranking a crowd!
-High-velocity banana peel: fires a super fast peel that slides through mobs. It will slip whomever it hits as though they stepped on a banana peel.
-Water gun: Fires a stream of colorful water and a random, mostly harmless, reagent. If it hits a target it will splash them in the mouth, potentially transferring some fun chems.
-and last but not least, THE DOOMLAZOR 9000. The DOOMLAZOR is a powerful single shot energy beam which slowly recharges on its own. It's a high power beam that overstimulates the target's senses and reportedly burns off facial hair and eyebrows. Aside from that it's *usually* harmless\*

\**The honking guild is not responsible for any resulting vaporization, sudden ignition, or painful death.*

[honkgiver.webm](https://github.com/user-attachments/assets/1fa745ab-a4fd-480f-b61a-b51feaf9c7a7)

Made in collaboration with Razz, who helped test and provided the original idea, initial code, and sprites.

## What this does
Allows lawgiver to be clownified into the Honkgiver, which has its own set of unique features including: 6 custom shot types with unique keywords, extra ammo, unique sound effects, unique DNA check and a clownish "self-destruct". 
Allows for deconversion back into the lawgiver with bleach, same as previous clownified guns. Adds a ultimate variant for adminspawn only which has 9,999,999 bullets of each bullet type. Most bullet types have a unique suicide (shoot in mouth) effect.

## Why it's good
Its a funny gun conversion for clowns that shoots (mostly) harmless ammo types.

## How it was tested
Tested converting lawgiver and demolition lawgiver into honkgiver and vice-versa. Tested converting honkgiver mags and vice versa. Tested each firing mode on a player controlled mob. Tested recharging the magazine.

[gameplay]
[dnm]
:cl:
 * rscadd: Introduces a clownified variant of the lawgiver with action-packed bullets custom-made for our brave and stalwart defenders of humor. Apply rainbow crayon to lawgiver and enjoy the tears of HoS mains everywhere.

### CODE REVIEW

**Comment by angryturnip** [comment]
tfw never get mime crayon transformations

**Comment by Dacendeth** [comment]
Man this pr has been in the works for so long it's almost a AAA title. I started this back in 2018, lost the majority of the work in 2019, got picked back up in 2024 by RealestEstate and actually finished.

**Comment by hacker-on-steroids** [comment]
uhh why is the water yellow?

**Comment by MercuriusGH** [comment]
> uhh why is the water yellow?

looks like honk serum is mixed into it

**Comment by Eneocho** [comment]
> uhh why is the water yellow?

image

**Comment by RealestEstate** [comment]
guys I swear its not what you think!

**Comment by RealestEstate** [comment]
[content]

**Comment by RealestEstate** [comment]
This PR is now ready for review. The DNM label can be removed. Also I think the content label is probably more appropriate than gameplay so it'd be nice to swap those.

**Pull request merged**
