### PR TITLE
Fake telecrystal bombs uplink item

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][port]

## What this does
Ported from goonstation. Adds this to traitor uplinks for 8 TC, (can adjust on request) when inserted into an uplink, instead causes it to explode. Also has secret hidden functionality with FRAME cartridges when inserted into them, acting as a PDA bomb. (although it would be better to just use the detomatix carts for that...)

## Why it's good
good prank for traitors you don't wanna work with.

## How it was tested
inserting the TC into a PDA with an uplink, then sending it via the FRAME cart to a non uplink PDA.

## Changelog
:cl:
 * rscadd: Traitors can now purchase a fake telecrystal for 8 TC from uplinks, which can be set to a custom value when used. When inserted into another uplink, or sent to a PDA via the FRAME cartridges, will cause the target device to explode.

### CODE REVIEW

**Comment by mentgah** [comment]
>ported from goonstation
are you sure you can do that

**Comment by SECBATON-GRIFFON** [comment]
> > ported from goonstation
> > are you sure you can do that

no code is copied, i reimplemented the idea myself, plus we've taken sprites from them before for xenoarch stuff

**Comment by west3436** [comment]
>no code is copied, i reimplemented the idea myself

Still isn't allowed

>plus we've taken sprites from them before for xenoarch stuff

Assets are under a different license which is compatible with Goon's

**Comment by SECBATON-GRIFFON** [comment]
yea this item had a few more issues with it i foresaw anyways, like being too easy to spot as fakery

**Pull request closed without merging**
