### PR TITLE
Honk serum causes clumsiness

### PR DESCRIPTION
**Pull request by ghost**
[content][tweak]

:cl:
 * rscadd: Honk serum now causes people to act clumsier.

### CODE REVIEW

**Comment by Eneocho** [comment]
This would allow non-clowns to use the banannon and stuff, not sure if based.

**Comment by ghost** [comment]
> This would allow non-clowns to use the banannon and stuff, not sure if based.

Slippery incense already does.

**Comment by Eneocho** [comment]
> > This would allow non-clowns to use the banannon and stuff, not sure if based.
> 
> Slippery incense already does.

But the incense is both obvious and hard to mass produce. You can mass produce honk serum really fast with almost minimum effort.

**Comment by gurfan** [comment]
> This would allow non-clowns to use the banannon and stuff, not sure if based.

non-clowns can't even purchase those weapons; complete non-issue

**Comment by KingofHONK** [comment]
Dunno how to feel about this once since now ill have to be more careful when I shitmin 1000u honkserum into someone to bully them.

**Comment by Eneocho** [comment]
It would also enable non-clown advanced boots. I don't want a random grayshit stealing my goddamned earrape boots.

**Pull request merged**
