### PR TITLE
Santa's Fat Suit Addition

### PR DESCRIPTION
**Pull request by GermanSanta**
Growing out of santa's suit by being fat was always quite silly. When i went through the code it looked like it was originally made already so this wouldn't happen since it contained the onesizefitsall flag. However the sprite was never made so you would still grow out of it. Anyway, I did what I must adding this sprite for this season.

Added fat sprites to santa's suit

### CODE REVIEW

**Comment by brndd** [comment]
Does this really work with no code changes whatsoever?

**Comment by GermanSanta** [comment]
surprisingly it does due to the code already being onesizefitsall
download

**Comment by GermanSanta** [comment]
santa1
santa
download

**Comment by GermanSanta** [comment]
Santa's side sprite looked weird with that grey pixel there... well it's white now. All is good for the pr.

**Pull request merged**
