### PR TITLE
[Requires Review] Reworks box EVA

### LINKED ISSUE #13975: Box Radio Transmitter room is walled off
good work
@Lokiamis

### PR DESCRIPTION
**Pull request by ghost**
…rity has its own EVA gear and airlock

Box EVA now has 6 civilian suits so you can actually give a person EVA access to get a suit without also having to give them additional access to another department, the atmospheric and engineering suits are now all on one side.

spess depot delta 2017-02-12 212132

Security has its own airlock with 4 security hardsuits within

security_eva_v2

Medical has its own hardsuits in medical storage, locked down at roundstart unless a CMO allows it by pressing the new button in their office

spess depot delta 2017-02-12 212256

Current problems: 

- [x] Probably numerous other problems because of maptools going weird, it deleted defficiency and taxi.
- [x] An additional X for each time maptools did something wrong. X X X X

Fixes #13975

### CODE REVIEW

**Comment by Lokiamis** [comment]
The detective no longer has access to security hardsuits. Intentional?

**Comment by ghost** [comment]
He'll have to stay undercover and nab a civ hardsuit.

Never seen a detective grab those sec hardsuits anyway. Strangely enough, never seen a security officer with them either.

**Comment by Lokiamis** [comment]
You've never seen a security officer in a security hardsuit?

**Comment by ghost** [comment]
Fucking layers. Bet it's the blast doors, set those to layer 5 so they'd not be stuck under the windows and doors

**Comment by kernikov** [comment]
I think it's a little silly to have Security EVA be the only place that has layered vent/scrubbers on the same tile.

**Comment by ghost** [comment]
It's either that or put pipes through walls, which is a serious nono

**Comment by PJB3005** [comment]
Why can't you put the vent somewhere else in the room and only use layers to fit the pipes to the vents through the door?

**Comment by ghost** [comment]
That is a reasonable suggestion.

Weaver from the coderdiscord's just posted their approach to a reworked EVA. I kinda like it as it gives a new room to work with while also moving the gateway into somewhere a little more accessible, while also making the civ softsuit area more of a cloakroom/changing room

EVA by Weaver

**Comment by PJB3005** [comment]
I'm not keen on that image. At all.

**Comment by Ephx1** [comment]
I think this is the only time I'll ever say this here on github.
Fuck you for posting that picture, HOLY SHIT.

**Comment by ghost** [comment]
???

**Comment by Ephx1** [comment]
Pushing around a highly used room for a rarely used admin toy is _disgusting_.
Plus it's ugly

**Comment by Shadowmech88** [comment]
If the medical hardsuits are important enough for there to be *shutters* over the doors, shouldn't the room's walls also be rwalls?

**Comment by SonixApache** [comment]
I tried to do this once in #12029. Sec EVA doesn't work out.

Just fill some of the empty space in the EVA hallway with civilian suits and leave the rest as-is would be my take on it.

**Comment by 9600bauds** [comment]
Sec EVA works 👌  in Deff tho

Isn't that what this is anyways, trying to recreate Deff's EVA system into Box?

**Comment by SonixApache** [comment]
Sec EVA works in deff because the warden has direct visual on it. It's discussed in that other PR, I think.

**Comment by Kurfursten** [comment]
Yeah, this EVA only provides a much easier way to break prisoners out of perma
>Enter through back door no one patrols at
>Hack to perma
>Your buddy now even has a suit, and sec one less to chase him with!

**Comment by gbasood** [comment]
`The command "find maps/ -name '*.dmm' -exec cat {} \; | awk '/layer =/  { exit 1 }'" exited with 1.`

FIX
YOUR
SHIT

**Comment by CptWad** [comment]
>removing patient room 1

is the second room still name/area'd patient room 2?

Also removing a patient room is something I am against. Just add it south of the patient rooms and move viro out more
image

**Comment by Lokiamis** [comment]
Would you mind fixing my fuckup while you're doing this? It's just one piece of wall #13975

**Comment by SonixApache** [comment]
ATOMIC

**Comment by gbasood** [comment]
honestly fixing a wall is fine
Atoimc PRs are important but it's important because someone shouldn't mess with game ticker code AND map files in the same PR when those changes have nothing to do with eachother e.g. "Fix changeling regen and fixes access on escape airlocks"

**Comment by Lokiamis** [comment]
Pretty sure he was joking, but yeah I'm not going to hassle the guy with conflicts over a single tile

**Comment by ghost** [comment]
The conflicts are fixed, it's just I'm not sure on readding the patient room elsewhere

Fucking hell is box hodgepodged together

**Comment by ghost** [comment]
I have never seen patient room used for anything other than privacy for murder

**Comment by Probe1** [comment]
"I don't see it so no one must use it" says man who is about to make a silly statement about a room used every other round.

**Comment by Probe1** [comment]
@Skullyton make sure to scratch medical access to EVA while you're at it then.

**Comment by SonixApache** [comment]
i for one am disgusted

**Comment by ghost** [comment]
@Probe1 Eh?

**Comment by Aurx** [comment]
If you give sec an airlock, it should be placed next to the sec escape pod or somewhere similar where getting from the airlock to anywhere important takes you through the main area.  
Otherwise it's just a back entry that officers have to metagame and block off or the brig's already shakey security is gone.

**Comment by ghost** [comment]
That is a fair point, problem with that is then you've got two unsecured hardsuits in a way where even cargo can access.

And I've seen plenty people use that oxygen locker to catch the whole of security out, so it might not go down too nicely, but I'll see what I can do.

**Comment by Aurx** [comment]
If security of the hardsuits is a concern, they could be put in a more secure location than an airlock.

**Comment by ghost** [comment]
security_eva_v2
>In view of the head of security
>Makes it more of a prep room in case of space emergency

**Comment by Kurfursten** [comment]
Well, I definitely like it more than the get-out-of-perma-free version.

**Comment by ghost** [comment]
Oh for petes sake, mapcleaner didn't work

**Comment by ghost** [comment]
And now mapcleaner deleted the map.

Technical difficulties

**Comment by ghost** [comment]
Woo mapcleaner

**Comment by ghost** [comment]
Finally.

@Lokiamis I fixed the broken thing

**Comment by eplgr** [comment]
I do like the idea of giving more purpose to EVA, and I like the changes, but isn't it extremely big? Especially because it's not a place where you'd normally stay, you just pick up some things and go away. It feels like you are working on top of a previous mistake.

Either way, it looks cool.

**Comment by ghost** [comment]
>Map conflicts

Why must you hurt me in this way

**Pull request closed without merging**
