### PR TITLE
Unfuck the rest of the switched tiles on Box

### LINKED ISSUE #4422: (WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Telecom is fucked
>Revision (Should be above if you're viewing this from ingame!)
bfbf840dba607c1e8758e3542d58e134cbe2557f

>General description of the issue
Telecoms door sprite, wiring and goonecode room are fucked holy shit

>What you expected to happen
Having to shoot my way through shit

>What actually happened
Dead power, dead game, dead powerbase

>Steps to reproduce if possible
Go look at telecom sat right now

### PR DESCRIPTION
**Pull request by Exxion**
Git and the map cleaner apparently don't get along when reversions are performed after other map changes. As a result, 9c21244617fed55448b2fcc68170e18f205f65a0 caused certain tiles to switch with certain other tiles. In some areas (R&D server room, disposals, some stuff on the asteroid), this was minor or barely noticeable. Other areas (telecomms, atmos, the central room of the telecomms satellite, the TEG burn room) were completely disfigured. Pomf fixed telecomms, disposals, and atmos. This fixes the rest of them, at least on Box. I looked at each edit to the map in that commit and manually changed the map file if things were switched.

I'm going to fucking set myself on fire if I have to do that again.

Fixes #4422 and a substantial number of similar unreported issues.

### CODE REVIEW

**Comment by clusterfack** [comment]
There is also an issue with the igniter switch in box's toxins lab not starting a fire.

**Comment by Exxion** [comment]
That's a separate issue. This just fixes tiles that switched places with other tiles. A lot of them.

Also, just for kicks, try to break into the central room on the telecomms satellite before this is merged. You'll see why I recommend it if you do so. Or if you look at the map render or DM, but that's way more boring.

**Comment by clusterfack** [comment]
That's hilarious

**Comment by Exxion** [comment]
Highlight Reel (the worst-fucked paces this fixes):

Burn chamber:
image

And my favorite, the Goonecode room:
image

OK I wrote the first line of this post expecting to put three things here, but only those two were really impressive. Research outpost and vox trading post atmos areas were violently fucked, but not in a visually impressive way. Oh well.

**Comment by Exxion** [comment]
I took a quick look at the other map files. I didn't thoroughly scour them like I did for Box, but it looks like only Box and Meta got fucked by that reversion. I can fix Meta, but not right now and not in this PR.

**Comment by FudgePucker** [comment]
Oh god how did the goonecode room even?

**Comment by d3athrow** [comment]
Mapmerger shit itself.

**Pull request merged**
