### PR TITLE
Procedural Celestial Body Generation

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Procedural planet generation

## Why it's good

Will elaborate on this more later, but it is FUN!!

## How it was tested

0% tested

## Future
- Custom vaults/ruins
- "Boss" battles
- Procedurally generated loot
- Travelling to the planets via shuttles
- Multiple active planets
- Ghost roles for planetary colonists

## Changelog

:cl:
 * rscadd: Added procedural planet generation for away missions.

### CODE REVIEW

**Comment by west3436** [comment]
Opening this now as WIP in case anyone wants to add any suggestions on biome types (especially xeno planet biomes), loot and decoration tables, or provide sprites.

**Comment by wotisjanitor** [comment]
.>todo list

This is going to be closed in 6 months

**Comment by west3436** [comment]
> .>todo list
> 
> This is going to be closed in 6 months

What's your wager? 😉

**Comment by Eneocho** [comment]
wave function collapse bros??

**Comment by west3436** [comment]
> wave function collapse bros??

Voronoi is just for biome mapping - haven't decided on what I'll use for caves yet

**Comment by SECBATON-GRIFFON** [comment]
lavaland...

**Comment by MercuriusGH** [comment]
clown planet real?

**Comment by SECBATON-GRIFFON** [comment]
> .>todo list
> 
> This is going to be closed in 6 months

i for one, welcome our [derelict] overlords

**Comment by west3436** [comment]
I was putting the cart before the horse here, and now that we're AGPL I can just use existing systems. Going to close this and will be opening the following PRs to implement this:
- Map Zones and Virtual zLevels
- Moving zLevel 2 vaults to vLevels
- Porting a whole bunch of planetgen items like trees, turfs, etc from Shiptest
- Starting with procedural asteroid generation then will move onto moons and planets

**Comment by Eneocho** [comment]
ogre

**Comment by wotisjanitor** [comment]
kek

**Pull request closed without merging**
