### PR TITLE
CREED

### PR DESCRIPTION
**Pull request by JMWTurner**
I'm a hundred percent certain that Creed is his title, not his name.

### CODE REVIEW

**Comment by Intigracy** [comment]
You're certainly a hundred percent wrong then.

Creed is a reference to Creed from TG, it's a name.

**Comment by Intigracy** [comment]
The area he's in is called Creed's Office

**Comment by Kurfursten** [comment]
Only a tactical genius could infiltrate a Seraph to the station using scouting rules.

**Comment by JMWTurner** [comment]
Is there a backstory I can read on the guy somewhere? I'm closing in on finally doing this strike team revamp, those holochips were a huge stone I had to place first.

Is it related to https://1d4chan.org/wiki/Creed

edit: Jesus I'm in class right now, trying as hard as I can so the teacher doesn't notice my laughter, this makes me want to play warhammer so bad.

**Comment by JMWTurner** [comment]
@Kurfursten I'm definitely gonna give Seraph the ability to sneak around on the station. Right now I'm thinking of a Cloaking Device like the syndie one, or the ability to hide in closets.

**Pull request closed without merging**
