### PR TITLE
Streamlined xenoarchaeology depth analysis scanner

### PR DESCRIPTION
**Pull request by ghost**
image
[tweak][qol][tested]
Not sure why you could only view these as logs in a window, but this should bring it more in line with atmos analysers now.
:cl:
 * tweak: Xenoarchaeology depth scanners now output information directly to chat when scanned instead of just a separate window.

### CODE REVIEW

**Comment by Eneocho** [comment]
UI streamlines are nice, but `>xenoarchcreep`

**Comment by DeityLink** [comment]
Do we get to keep the separate window with the logs as well? Also please have the anomaly materials appear in bold, some colors are hard to read but that can help a bit.

**Comment by ghost** [comment]
> Do we get to keep the separate window with the logs as well? Also please have the anomaly materials appear in bold, some colors are hard to read but that can help a bit.

Yes and yes

**Comment by Kurfursten** [comment]
You said you would bold it

**Comment by ghost** [comment]
> You said you would bold it

Oh I did, just didn't update the image.

**Pull request merged**
