### PR TITLE
Introduce Mining Lantern Hook flickering

### LINKED ISSUE #5137: Hanging lanterns can only face south
Dylan what the fuck man
There doesn't even have to be a wall there it just appears to the south of you for no goddamn reason

### LINKED ISSUE #5179: (WEB REPORT BY: Anonymous REMOTE: ) Lantern hooks don't stick to the wall they're placed on.
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Once you create a hook, and place it on a wall, it doesn't go flush with the wall, and defaults to facing north.

>What you expected to happen
The hook to actually go on the wall

>What actually happened
It defaulted to facing north, see pic related http://i.imgur.com/9NTcblr.png

>Steps to reproduce if possible
Create a hook, place it on a wall, not sure if it matters if it's an Rwall or not.

### PR DESCRIPTION
**Pull request by ghost**
Requested, you can now spook mining lanterns to flicker them

Flickering mining lanterns is hit and miss (testing doesn't show it properly going on/off/on/off as expected), but it turns off when spooked and back on when done, so here's that

Fixes #5137
Fixes #5179

### CODE REVIEW

**Comment by PJB3005** [comment]
The way boo is turning out isn't very OOP, it should be some proc on the atom that's being boo!'d that's universal instead of this snowflaky shit

**Comment by clusterfack** [comment]
refactor when

**Comment by ComicIronic** [comment]
>all the :

REFACTOR NOW

**Comment by NigglyWiggly** [comment]
https://github.com/d3athrow/vgstation13/issues/5137
Cough cough fixit first faggot

**Comment by clusterfack** [comment]
inb4 pull closed

**Comment by NigglyWiggly** [comment]
I want to tenderly bully Dylan!

**Comment by dylanstrategie** [comment]
Normally I'm using the same proc that for all mountable frames for positioning mining lanterns, I don't see where in the code this isn't working

**Comment by ComicIronic** [comment]
Line 40.
It should be `get_turf(src), src.dir`

**Comment by dylanstrategie** [comment]
Will change asap

**Pull request merged**
