### PR TITLE
Bug fixes for Box

### LINKED ISSUE #20742: boxstation mommi nest still has improper firelocks
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)

triggers from the coldness of space

### LINKED ISSUE #21973: box genetics inflatable shelter blocks the room's scrubber
[box]
The inflatable shelter in the genetics room on boxstation inflates over the scrubber, preventing the room from being scrubbed unless someone goes in and moves it. Either moving the fire alarm or moving the scrubber would fix this.

### LINKED ISSUE #22020: No crowbars on arrivals shuttle
(WEB REPORT BY: autisticmouse REMOTE: 206.221.180.138:7777)
# Revision
e2adab7432543216b9babc334ff5d3440c4e306c

# Description

On box, there doesn't appear to be any crowbars on the arrival shuttle, so in terms of power failure you have to smash your way out.

# Steps to Reproduce

# What you Expected

Atleast one crowbar.

# What Actually Happened

0 crowbar.

### LINKED ISSUE #22549: Box Security is a mess
Unplayable

Untitled

[box] [easy] [first] [oversight]

### LINKED ISSUE #23646: Mini mining outpost pipe issue
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
5dee8676dac43ea4726ec8a8d2a005f77093dfdb

# Description
The mini mining outpost on box has an ore deposit which leads to a  Delivery chute that sends ore to the main mining outpost said chute does not work 
https://puu.sh/DVWq8/1fb160bb2d.jpg
# Steps to Reproduce
use the mini mining outpost
# What you Expected
ore to go into the chute and arrive at the main mining outpost
# What Actually Happened

### LINKED ISSUE #24104: BoxStation wood under gateway maint airlock
(WEB REPORT BY: incakola REMOTE: 206.221.180.138:7777)
# Revision
be7fa031c20379fc956a2792473b75be8d500465

### LINKED ISSUE #24338: Waste pipe under maint door below research on box instead of an air supply pipe.
image

### PR DESCRIPTION
**Pull request by Probe1**
Fixes the cosmetic waste pipe under the research maint door
Closes https://github.com/vgstation-coders/vgstation13/issues/24338

Adds a duplicate lever inside the west mining outpost to make it absolutely clear that you need to pull the lever to activate the conveyer and increases accessibility https://i.imgur.com/qFSsTMA.jpg 
Closes https://github.com/vgstation-coders/vgstation13/issues/23646

Fixes every single issue in this from duplicate wires to missing decals and unifying the table types to reinforced
Closes https://github.com/vgstation-coders/vgstation13/issues/22549

Adds one (1) crowbar to the arrivals shuttle in an o2 locker.  https://i.imgur.com/rpl73Vr.jpg
Closes https://github.com/vgstation-coders/vgstation13/issues/22020

Fixes the inflatable whatever from blocking the scrubber in genetics by moving the scrubber to the opposite side of the room https://i.imgur.com/0MRzQfH.jpg
Closes https://github.com/vgstation-coders/vgstation13/issues/21973

Tweaks the MoMMI airlock shit by deleting the outer one so it isn't always triggered because no other airlocks have a firelock and that's just fucking weird and unhelpful
Closes https://github.com/vgstation-coders/vgstation13/issues/20742

Oh and the wooden tile under the gateway room from its vestigial engineering office origins has finally been replaced.  
Closes https://github.com/vgstation-coders/vgstation13/issues/24104

:cl:
 * bugfix: Five bugfixes on Box.  Security decals and cosmetic consistency, No more space adjacent firelock for the MoMMI airlock to get triggered every round, adds an o2 locker to the arrivals shuttle so when powers out people can escape via crowbar or toolboxing their way out, adds an extra lever to the west mining post for people to ship ore high speed through disposals with, replaces a rogue scrubber pipe in the air supply network, and finally shifts Genetics scrubber to the opposite side of the room to avoid the fire alarm and scrubber sharing a tile and causing inflatable issues.

### CODE REVIEW

**Comment by Kharkov72** [comment]
🤔

**Comment by Probe1** [comment]
I'll do the rest of the Box issues another day I'd rather avoid a monolithic PR honestly.

**Comment by MadmanMartian** [comment]
You ran the pipe and wire checks?

**Comment by Kurfursten** [comment]
Please run cheques

**Comment by jknpj** [comment]
CONFLICTS AAAAAAAAAAAAA

**Comment by Probe1** [comment]
I deserve it all I had to do ONE thing Kurfurst told me and I did not.  I'll fix it quickly.

**Comment by Probe1** [comment]
I'll rebase and fix conflicts now that the other PRs are merged.  I got caught in a weird spot where I wasn't sure if Shiftys PR should really wait on mine and wanted to wait until it was clear.

**Comment by Probe1** [comment]
I DON'T REMEMBER HOW TO FIX MAP CONFLICTS

**Comment by Probe1** [comment]
Ok I do not remember how to fix map conflicts someone please ping me and help.

**Comment by MadmanMartian** [comment]
>go to working branch
>pull from bleeding-edge
>remake changes you wanted to push because mapping conflicts a dumb

**Comment by Probe1** [comment]
Damnit.  We used to have a trick for it.  I already tried using the map cleaner to merge a fresh version but as you can see it didnt work.

**Comment by Kurfursten** [comment]
Do it fresh and we won't merge any more box stuff before you

**Pull request closed without merging**
