### PR TITLE
Makes the supermatter crystal actually generate more power than shards

### PR DESCRIPTION
**Pull request by Jellyveggie**
### It's not really closed, it moved to https://github.com/vgstation-coders/vgstation13/pull/19480 after I fucked up

Used to be supermatter crystals heat up faster (and need less oxygen to get supercharged), but didn't really produce more power on identical setups, despite the usual assumption or the fact crystals are harder to control:

_From test server_

Now, by losing energy more slowly, crystals would be able to store more energy, thus producing more power (and thus heat, gas, radiation...) than shards:

_Tested locally_

As of right now the increase is by 20%. **Please suggest better values if you feel it's not enough/too much**.

### CODE REVIEW

**Comment by Jellyveggie** [comment]
I pulled the `power_loss_modifier` value for crystals out of my ass, so balancing should be discussed first. 
The figures on those comments come from `power_loss_modifier*(emitters*60)^(1/3) - emitters*60`. 
Radiator collectors, temperature and gas production percieve  `power_loss_modifier*(emitters*60)^(1/3)` instead, as their math happens before power is actually substracted.

**Comment by Substance455** [comment]
I like this. Make the crystals a little easier to find/get and it'll make engineering fun again.

**Comment by Jellyveggie** [comment]
Suggestions from the general:
* "I trust your judgement, shardanon"
* Make the ratio 1000, aka double than the shard. Might have been a joke, but considering gas efficiency is already the double on crystals it does makes sense in a way.
* Completely modify how crystals gain energy, by reversing the curve. [Pic related](https://user-images.githubusercontent.com/39123109/44599232-ed8b4480-a7d5-11e8-880a-5800165266ea.png), pending some actual thought on balance. I kinda like it, but should probably be a different PR.

**Comment by spoonylove** [comment]
What balance? crystals are random finds by xenoarch. Past a certain point power is meaningless, double its power why not? Engineers want big numbers and as rare and deadly as the things are they should be able to push ludicrously large numbers when they get the chance. Even double seems too little for a whole crystal.

**Comment by Caboozles** [comment]
Given that crystals always end in hellfire, there is no reason to me that they shouldn't produce even ten times as much power. They're basically something that WILL blow up, so let it just be something that generates so much power that anyone can do any sort of glove meme or maybe a railgun if they so choose.

**Comment by Jellyveggie** [comment]
oh god my messing around has done some weird commit spam
crap crap crap
I'll redo this pull give me amoment
sorry @Substance455 , @spoonylove, @Caboozles

**Comment by boy2mantwicethefam** [comment]
another PR has fallen to the metaclub, can it EVER be stopped?......

**Comment by Jellyveggie** [comment]
Move over to https://github.com/vgstation-coders/vgstation13/pull/19480

**Pull request closed without merging**
