### PR TITLE
You now get 40 bananium/phazon floortiles per sheet (up from 4), disables bananium/phazon scanning on cyborg matsynths

### PR DESCRIPTION
**Pull request by ghost**
Why?
It's not characteristic of an engineering cyborg to just be used to dupe exotic materials like a bitch. That's not engineering work.
As far as I'm aware, this duping is only used for 2 things:
1. Cheesing materials and making a shitton of phazon from just 1 slime split, then having an effectively unlimited amount of sheets to spam phazon mechs and phazon mutations
2. Meme floors (basically impossible without duping)

I preserved the second option and made you not need to dupe so badly to use it. MoMMis can also still do it, since dropping the sheets would be interference and mineral floortiles cannot be recycled back into sheets.
As for the first: You CAN still synthesize phazon, you'll just have to use the regular matsynth that uses solid ammo.
>A device capable of producing very little material with a great deal of investment. Use wisely.

:cl:
 * tweak: You now get 40 bananium/phazon floortiles per sheet, up from 4
 * rscdel: Cyborg material synthetizers cannot dupe bananium or phazon. You can still synthetize it by using solid matter cartridges.

### CODE REVIEW

**Comment by DrSnips** [comment]
Not entirely the same thing but its similar. #16014

**Comment by yclatious** [comment]
Yknow, I dont actually think there is anything inherently wrong with this change.

Fuck it, why not.

**Comment by aceedex** [comment]
Merriment forbidden

**Review by PJB3005 — APPROVED** [review]

**Comment by clusterfack** [comment]
This is a pretty good change to be honest

**Comment by iFlashYou** [comment]
How about adding a upgrade that allows it to scan phazon and bananium but it requires a fair ammout of both materials to make it?

EDIT: And was there not a poll about this and people wanted it to stay like it is?

**Comment by Reviire** [comment]
I don't see the point. If it's to "nerf" phazons, there's more than enough phazon on the roid to make several, you're not saving time by getting an engiborg to produce phazon. You're just creating more so you can make even more tiles.

Really, the only thing this change is going to do, is encourage people to hoard their phazon more and never let a phazon floor tile get made. Can't make your mechs, and then print more to cover the station in tiles. Instead, you get mechs and anyone who wants to make floortiles gets told to eat a dick. 

EDIT: Also, >coder isn't even in the ivory tower

**Comment by Killette2** [comment]
I like this

**Comment by ghost** [comment]
Upped to 40 after concerns that it still wouldn't be practical without duping

**Comment by Blithering** [comment]
You could make it so that Borgs can synthesise the tiles but not the sheets, not sure if turning tiles back into sheets works with other time types though

**Pull request merged**
