### PR TITLE
people can now bear arms on castle station

### PR DESCRIPTION
**Pull request by gurfan**
All crewmembers now have some sort of gun to start with on castle station to make up for the lack of security.

Departments have their own gun cabinet (access locked to their department) that starts with two taser guns and four department-specific guns. Department specific guns are as followed:

**Cargo:**
4 Vectors (Includes 6 extended .380 magazines and 6 rubber .380 magazines)
**Medbay:**
2 Decloners
2 Rapid Syringe guns (includes 3 boxes of syndicate syringes)
**Science**
2 Laser Pistols
2 Plasma Pistols
**Engineering**
3 Combat Shorties (includes 2 boxes of each shell type)
1 Pre-Charged Railgun

**Job-Specific Guns:**
IAAs: 2 uzis (with false-bottom briefcases)
Mechanics: 2 glocks
Librarian: 1 glock
Chaplain: Feldbischof Bible (Luger bible)
Clown: Bananon
Mime: Advanced Mime Gloves
Assistants: 4 blunderbusses
Chef: Lolly Lobber
Bartender: Extra box of slug shells
Botany: 3 mahogunys

Heads of staff also get a stun revolver in their respective lockers.

:cl:
 * rscadd: Castle Station: Departments now have their own gun cabinets, each containing two tasers and four department specific guns. Service and civilian crewmembers start with guns as well.
 * rscadd: Castle Station: Heads now get a stun revolver in their respective lockers.
 * tweak: Castle Station: Updated the bar and the science suit storage units in EVA.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
meme PR for a meme map, I like it

**Comment by Buchse** [comment]
Now boost the ops chance for castle massively

**Comment by DrSnips** [comment]
Dangerously based

**Comment by gurfan** [comment]
@Buchse ok
#28117

**Comment by TGFH** [comment]
>1 pre charged rail gun
Now people have a reason to play engineer

**Comment by SonixApache** [comment]
i concur with damian

**Comment by DeityLink** [comment]
I welcome the coming of Texas Station

**Comment by Dacendeth** [comment]
are those normal blunderbusses or flawless for assistants?

**Comment by Exxion** [comment]
Does everyone also get a gun permit or does building a securitron take down the entire station?

**Comment by gurfan** [comment]
@Dacendeth 
flawless
@Exxion 
beepsky will probably be a nightmare

**Comment by SonixApache** [comment]
beepsky probably shouldn't be present on castle

a subtype of beepsky that randomly stuns/cuffs people for fun might be more appropriate

**Comment by ghost** [comment]
accelerationism

**Comment by Blithering** [comment]
Replace beepsky with one of those robot ducks.

**Comment by PrimeDSS13** [comment]
actually I change my mind castlestation is comfy

**Comment by Kurfursten** [comment]
This has the better ratio

**Pull request merged**
