### PR TITLE
Censors Dusky

### LINKED ISSUE #31789: The borg in the bar vault shows up on the crew manifest
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
c4ac4c4c16159f046924f82b6a91e9c3146c09a9

# Description
Dusky the bartender borg shows up on the crew manifest

# Steps to Reproduce
load the bar vault

# What you Expected
immersions

# What Actually Happened
immulsion

### PR DESCRIPTION
**Pull request by gurfan**
Closes #31789
:cl:
 * bugfix: Dusky won't appear on the crew manifest or round-end scoreboard anymore.

### CODE REVIEW

**Comment by ghost** [comment]
Dunno about remaking it into a simplemob type, would ideally look for whatever function adds all mobs of type silicon to the manifest and find a way to exclude NPC types.

**Comment by gurfan** [comment]
> Dunno about remaking it into a simplemob type, would ideally look for whatever function adds all mobs of type silicon to the manifest and find a way to exclude NPC types.

Why shouldn't it be a simplemob? It doesn't do anything besides stand there and talk.

**Comment by Kurfursten** [comment]
Could you make it so he doesn't talk when no one's around?

**Comment by gurfan** [comment]
> Could you make it so he doesn't talk when no one's around?

#31507 already did that

**Comment by Exxion** [comment]
Why was it even a silicon to begin with?

**Pull request merged**
