### PR TITLE
the chud uprising 

### PR DESCRIPTION
**Pull request by Manleto**
## What this does
CHUDS the AI. 

## Changelog
:cl:
 * rscadd: Add chud
 * imageadd: Added chud (unless I fucked up)

### CODE REVIEW

**Comment by Manleto** [comment]
@gurfan you got something to say bitchboy?

**Comment by gurfan** [comment]
NAS

**Comment by pedr69** [comment]
>IconDiffBot2 Skipped — No icon changes

brother you didn't add the sprite

**Comment by Theophrastus1** [comment]
i knew that piece of shit AI core would cause this

**Comment by tinysaturn** [comment]
>upboating your own PR

**Comment by Eneocho** [comment]
`> upboating your own PR`
I kneel

**Comment by ErrorsWindows** [comment]
why would you not upvote your own posts? it's simply pragmatic to ensure your post is viewed as widely positive, like it should be

**Comment by Manleto** [comment]
> > IconDiffBot2 Skipped — No icon changes
> 
> brother you didn't add the sprite

Just upvote this one and I'll upload another PR adding  the sprite I'm a real coder

**Comment by d3athrow** [comment]
you didn't add the sprite my man

**Comment by pedr69** [comment]
what you do is navigate to the correct branch in your repo - click the manleto:patch11 at the top of the PR
then navigate to `icons/mob/AI.dmi`
and then upload the modified AI.dmi file with the chud sprite added
make sure you then commit to patch11 instead of creating a new branch

**Comment by Manleto** [comment]
I need to fix this

**Comment by Manleto** [comment]
@pedr69 how do I uh, upload that to it

**Comment by Eneocho** [comment]
You don't need to close the PR to do it. Go to icons/mob/AI.dmi and download the latest copy. Open that file on dream maker and add the chud image with the exact name on the ai.dm file. Save this updated version of the AI.dmi file somewhere on your PC.
Now go to your fork of the repo and select patch-11. That is the branch THIS specific PR uses. Navigate to icons/mob then click and drag your updated AI.dmi file to the folder to upload. Upload it to replace the previous copy (which is why you downloaded the latest). You now have an updated icon file. @Manleto 
If the PR was kept open the system would immediately detect a change to the PR and run the checks.

**Comment by SonixApache** [comment]
alternatively; don't

**Pull request closed without merging**
