### PR TITLE
Gives the homeless RAMsay shelter in Metaclub.

### PR DESCRIPTION
**Pull request by Gringonius**
On the tin, bagel was taken out of rotation by shitposting magic and RAMsay is now nowhere to be seen.
Since box is not allowed to have anything unique and Meta is somehow considered boring, I've put RAMsay in its kitchen.
At least until the fabled trimmed bagel shows up.
[meta]

:cl:
 * rscadd: RAMsay has found a new home in Metaclub.

### CODE REVIEW

**Comment by Lunstra** [comment]
> Meta is somehow considered boring

 probably because its basically just box but without half the QOL tweaks and updates box has had over the years. Anyway this is a good PR, anything that gives meta some more flavour is nice

**Comment by kilozombie** [comment]
Die

No, but really, RAMsay is funny, but don't put him in the kitchen. He insta-destroys the mint at every roundstart on Bagel because he's a meme and the kitchen already has enough things you have to wrench up and stuff into Maintenance please be more responsible

**Comment by Gringonius** [comment]
> 
> 
> Die
> 
> No, but really, RAMsay is funny, but don't put him in the kitchen. He insta-destroys the mint at every roundstart on Bagel because he's a meme and the kitchen already has enough things you have to wrench up and stuff into Maintenance please be more responsible

 #21514
remember to shill my other PR

**Comment by SonixApache** [comment]
ramsay already has his cute little cooking vault, does he really need to be in a kitchen

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This thing's sole purpose is to grief chefs isn't it?

**Comment by AI-Is-Rogue** [comment]
Ramsay cares about the quality of your food, he doesn't want you to poison the crew.

**Comment by jknpj** [comment]
Scream if you plan to work on this later on

**Pull request closed without merging**
