### PR TITLE
Ports the ability to have custom null rods

### LINKED ISSUE #9090: Null rod reskin for paladin chaplains
Since the crusader armour was introduced to the vendors, knight gimmicks have become commonplace. Usually this includes welding a bunch of knives together to make a suitable blade, and risk security confiscating it. 
I thought it might help to have chaplains who choose a suitably knightly deity have their null rod icon change to a holy avenger style sword, as they're known for kicking unholy arse. Other chaplains could have either a spell/ritual to alter their null rod, or otherwise be at the mercy of their god's good graces. 
avenger
The icon itself is a retool of the cult blade, with a more 'holy' look and glow.
Download link for icons: http://s000.tinyupload.com/index.php?file_id=05535435526954482657

### PR DESCRIPTION
**Pull request by jknpj**
null1
null2

Gives chaplain the ability to invoke the power os his god(s) to transform the null rod in other holy weapons. They are all reskinned childs of the null rod and are intended to help with gimmicks.

This doesn't port all those custom null rods from TEEGEE but adds a few ones:

* **The holy avenger**, a crusader blade (sprited by @Blithering )
* **The cult blade**(i wish i could give it a better name but MUH CULT GIMMICK), it looks just like the real thing!
* **The saint katana**, glorious holy nippon steel
* **The nullbox**, a toolbox-looking null rod
* **The divine brass spear**, based in the dead machinegod cult

Closes #9090

:cl:
 * rscadd: Ports the ability to transform your null rod in other holy weapons.
 * rscadd: Adds the holy avenger, cult blade, saint katana, nullbox and divine brass spear as holy weapons

### CODE REVIEW

**Comment by DeityLink** [comment]
>The cult blade(i wish i could give it a better name but MUH CULT GIMMICK), it looks just like the real thing!

...at least remove the red gem.

**Comment by SonixApache** [comment]
Needs *null-* skins. Love that sword, though.
Very much like the idea of custom nullrods to fit the religion, however dislike the idea of them having different stats from the nullrod.

**Comment by yclatious** [comment]
PR pics please.

**Comment by SonixApache** [comment]
sword
Sword.
spear1 spear2
Spear. Dunno why there's two sprites, but there is.
I'll leave the inhands to @jknpj.

**Comment by Exxion** [comment]
"Solves" doesn't work for autoclosing
Stick with "closes"

**Comment by jknpj** [comment]
>needs golden katana and golden toolbox skins

I agree

**Comment by SonixApache** [comment]
@Exxion @jknpj 
image

**Comment by N3X15** [comment]
Giving this [Balance] due to stat changes.

**Comment by DeityLink** [comment]
I'm against the stat changes. These skins should remain cosmetic. Especially considering Constructs taking extra damage from null rods was balanced around the base damage.

**Comment by ghost** [comment]
There should really be no stat changes.  just a reskinning.

**Comment by jknpj** [comment]
Well to be fair the only real status change is in the spear (16 force when wielded, the default null rod is 15), the katana is a straight nerf versus constructs (5 force, sharpness 2) and the swords just get sharpness flag because not having sharpness in a sword would be really silly.

**Comment by DeityLink** [comment]
>not having sharpness in a sword would be really silly.

ceremonial/parade swords generally have blunted edges.

**Comment by jknpj** [comment]
you do have a point

**Comment by N3X15** [comment]
Confirmed removal of statcreep. Removing [Balance].

**Pull request merged**
