### PR TITLE
Adds a 2-second cooldown to warping claws

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
These have no cooldown, you can spam portals endlessly
:cl:
 * tweak: Warping claws now have a 2-second cooldown. This change is brought to you by that wizard who used the warping claws.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
Maybe 3 seconds instead? 5 feels like too long with the fast-paced combat we have.

**Comment by boy2mantwicethefam** [comment]
it's a controlled hand-tele that can teleport into places you don't have vision to, come on

**Comment by jknpj** [comment]
It's also a large artifact that's quite rare to find.

**Comment by Caboozles** [comment]
Unless there’s some mystical way of acquiring them, their rarity is an absolute reason for them to stay as is. They’re ridiculously rare, and 99% of the time it’s just a non-antag xenoarch actually getting to have fun. 

There’s no reason to disable them. The same wizard could have just taken blink and be infinitely worse.
Actually, fuck off. Blink exists and it’s down to 0.5 seconds with almost the same effect.

**Comment by boy2mantwicethefam** [comment]
The claws aren't disabled, what do you mean

**Comment by DrSnips** [comment]
I don't get the comparison to blink since they aren't related. Wizards have their own balance.
I like the idea of a cooldown. I've seen people go full retard with them before and vent room after room as non antag. This might make people think a bit before just making air holes all over the station.

**Comment by ShiftyRail** [comment]
That's 99% of the fun of the item. If you truly want it """""""nerfed""""""", then make it work in short bursts and have a long cooldown if you open too many portals in a too short timeframe.

I really don't like the idea of gutting an item by making it slow and unresponsive.

**Comment by boy2mantwicethefam** [comment]
It's not slow nor unresponsive

**Comment by ShiftyRail** [comment]
>5 seconds cooldown between actions
>not slow

**Comment by boy2mantwicethefam** [comment]
22 damage punches that can teleport in any place in your screen without the limitations of a hand-tele is pretty strong and 5 seconds is still not slow given that you have the advantage of teleporting on the spot when you use it

**Comment by ShiftyRail** [comment]
I don't give a fuck about your balance bullshit
I want the item to feel fun

Jumping around is fun
Number-based tweaking isn't

I don't really want to argue about this on Christmas but please stop thinking in numbers. The teleport  spam *is* the entire point of the item !

**Comment by boy2mantwicethefam** [comment]
At least you're being honest, I like that. What cooldown do you suggest?

**Comment by ShiftyRail** [comment]
Over 10 portals in the span of 3 seconds means you can't use the item for 5 seconds

**Comment by boy2mantwicethefam** [comment]
Can you even make that many portals in 3 seconds?

**Comment by boy2mantwicethefam** [comment]
I could lower the cooldown to 2 seconds because that'll allow for a crazy amount of movement but I don't think giving it the crawl approach is great

**Comment by DrSnips** [comment]
Any cooldown at or above 2 would do wonders to help reduce the hole spam. *I'm not saying I've abused them using a means of rapid clicking but I've seen it happen on my screen by someone who likely used a rapid clicking method.*

**Comment by ShiftyRail** [comment]
This item's raison d'être is teleport spam

**Comment by DrSnips** [comment]
Then lets revert the atmos venting via portals to solve my issue with the portal spam. I already know that won't pass because muh interesting features. So addressing this it is.

**Comment by boy2mantwicethefam** [comment]
Warping claws now have a 2 second cooldown that can be var-edited

**Comment by Kammerjunk** [comment]
god I hate it when Shifty's right

**Comment by ghost** [comment]
God I hate it when a Frenchman uses French words at me like I know what they mean

**Comment by Desuiseiseki** [comment]
"please go inhabit somewhere else"

**Comment by boy2mantwicethefam** [comment]
no, also that wasn't me I'm range-banned

**Comment by Desuiseiseki** [comment]
still valid

**Comment by boy2mantwicethefam** [comment]
no

**Comment by boy2mantwicethefam** [comment]
People don't like this change

**Comment by ShiftyRail** [comment]
@Kammerjunk I'm never wrong

**Comment by xeroxemnas** [comment]
Make xenoarch less of a chore before you start nerfing it, please.

**Pull request closed without merging**
