### PR TITLE
Allows the GPS to be turned off by hand rather than just EMPs

### PR DESCRIPTION
**Pull request by ghost**
[tweak]
image
image
Also standardises non fancy UI to look more like the fancy one.
First attempt for me at TGUI code too.

:cl:
 * rscadd: GPS devices can now be turned off in their menus.

### CODE REVIEW

**Comment by WindowsErrors** [comment]
SPSs start falling off the listing

**Comment by Cartlord** [comment]
Maybe make the S.P.S. send a signal when disabled?

**Comment by WindowsErrors** [comment]
no

**Comment by Kurfursten** [comment]
I don't like this change. When you activate a GPS, you are committing to having it on. That means you can't just flip on a GPS for peeks at peoples' locations then flip it off again. Either you commit to being seen yourself, or you don't get to see who's on GPS.

**Comment by WindowsErrors** [comment]
a single airliner goes missing and people are still asking why the pilots have the ability to turn off the airplane transponder

**Comment by WindowsErrors** [comment]
where did all the downvoters come out of the woodworks from

**Comment by DamianX** [comment]
I paid them

**Pull request closed without merging**
