### PR TITLE
Adds shortcut for farting CTRL+F

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I liked this feature
Cycling left and cycling right shortcuts changed to CTRL+G and CTRL+H respectively
Also removes straining message to avoid spam
The most controversial feature PR yet
Only robust people like the clown can fart on people using this shortcut after knocking them down
:cl:
 * rscadd: You can now fart using CTRL+F. Cycling intent left and right have been changed to CTRL+G and CTRL+H respectively.
 * rscdel: Removes "user strains and nothing happens" message to prevent spam. Remember that the cooldown is 40 seconds.

### CODE REVIEW

**Comment by Sooose** [comment]
Literally just make a macro.

**Comment by yclatious** [comment]
Call me when you pr *dab, then we can talk.

**Comment by jknpj** [comment]
if only you know how bad things are

**Comment by MadmanMartian** [comment]
>Go to search for something in a block of text
>flatulence

**Comment by Exxion** [comment]
Dude you can just do this on your own skin file
Don't change everyone else's
Especially when you're changing existing hotkeys

**Comment by Kammerjunk** [comment]
macrobiotic breakfast
high-frequency farting can be yours in just 3 easy steps

**Comment by boy2mantwicethefam** [comment]
Dang u right

**Pull request closed without merging**
