### PR TITLE
Guns no longer damaged by breaking open lockboxes, take three

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
As the last two attempts, now with everything finally working. 

Reverts most of #11753

### CODE REVIEW

**Comment by jakmak** [comment]
Yes the lockbox buff was a mistake and should be undone. All it does is make antags even stronger by making their prey even weaker and trying to do it all in the name of "department interaction".

**Comment by icantthinkofanameritenow** [comment]
Also, reminder that Pomf himself said it should never have been merged at all.

**Comment by MechaMusume** [comment]
I hope this goes through quickly. Even Pomf thinks this change was stupid. 

Though maybe rework it to be a toggle for some kind of hardcore mode or something.

**Comment by jakmak** [comment]
Even the chicken god agrees that pr was a mistake. Deliver us from auitsm icant and bring us back our guns

**Comment by Shadowmech88** [comment]
I'm coming into this whole issue _very_ late, but I do have one question as to the matter of the original PR.

If people getting weapons illegitimately was a problem, then why not, instead of making illegitimately-obtained weaponry so broken that it's unusable, just make lockboxes themselves indestructible?

**Comment by jakmak** [comment]
@Shadowmech88 you see other servers do that and the end result is usually all the sci guns never get made and as a result only sec can defend themselves and other people. While sec being the sole defender isnt a bad thing for other places where antags are limited and sec has more authority instead here with server culture antags have free reign and a lot of tools at their disposal resulting in the servers culture encouraging being able to defend yourself from murderboners. Removing sci weapons from non sec would just make people easier targets for antags.

**Comment by icantthinkofanameritenow** [comment]
Not to mention the dozens of scenarios where Sec is unable or unwilling to open lockboxes. Which is very often given how few people play Security on this server.

**Comment by NigglyWiggly** [comment]
Why not just make it so blowing open a lockbox _can_ have some effect on your weapon.
Maybe it fires slightly to one side, maybe it's weaker, maybe it's falling apart.
Maybe it fires for twice the damage while burning through the cell twice as fast.
Like, don't make it all negative if you ever break one open, make it a gamble. You might get a normal weapon, you might get a fucked up one, or you might get a tradeoff or maybe even a stronger one.

**Comment by Hoshi-chan** [comment]
@NigglyWiggly Lockboxes changed into Lootboxes. Godly Ablative Vest of the Whale when?

**Comment by Kurfursten** [comment]
> Of the Whale
> Spirit gear

Reroll for Monkey @Hoshi-chan

**Comment by Hoshi-chan** [comment]
@Kurfursten Wow, thanks for making me feel fucking old for having to explain this, but the Godly Plate of the Whale was an extremely common hacked item that was prevalent in Diablo 1. It was a combination of a prefix and suffix that was unattainable by normal means and resulted in a piece of armor with extremely high AC and a huge bonus to HP.

**Comment by coldcola** [comment]
can I get a grandfather baton somehow??

**Comment by yclatious** [comment]
---- --- ---- --

**Comment by Allspice** [comment]
@Hoshi-chan Diablo was only released 20 years ago, not that long really

**Comment by Kurfursten** [comment]
@Hoshi-chan Blizzard likes their "of the [animal]" trend, so I figured you were talking about the "Of the Whale" item suffix for random greens back in Vanilla WoW. It fits the idea of randomly rolling boxes over and over again until you get the one you like better than a hacked item, imo.

**Comment by Hoshi-chan** [comment]
@Kurfursten It was a joke, but I do like Niggly's idea of RANDOMIZED ITEM PROPERTIES. Godly Plate of the Whale is just what I always think of when I think of randomized loot, because Diablo was my first experience with that type of thing, and that armor was fucking everywhere.

**Comment by d3athrow** [comment]
@NigglyWiggly maybe make it so you open up a shotgun that has a 10x scope that fires rockets instead of slugs.

**Comment by gbasood** [comment]
so wait
Why was the lockbox PR not just reverted if this wasnt wanted to begin with
why is this take 3 if it only needed a revert

**Comment by yclatious** [comment]
We made it clear we didnt want it, but we would be lying if it was complete shit, things like the actual access changes are fine, we want to keep those, just not the actual mod with the gun bullshit.

Plus, cluster merged a fix to the lockboxes before this, so I'm guessing personal bias towards this revert anyhow, even with pomfs direct order.

**Comment by NigglyWiggly** [comment]
Well I didn't actually mean to make the defect thing like a loot box, but I just meant give it something to make it so you aren't just guaranteed to get a shitty gun.
That said, we could totally add actual loot box style shit on the asteroid for miners

**Comment by Zennyization** [comment]
Not even kidding, I offered a solution that is a happy medium between the guns being broken if you illegally obtain them.

Why not just have science print out gun parts that can be used to repair the weapon if it is defective?

**Comment by icantthinkofanameritenow** [comment]
IIRC, that was dismissed of how it would defeat the purpose of the change or something. 

Better to just cut out the damage horseshit completely if you ask me, your way is just an unnecessary middleman.

**Comment by SonixApache** [comment]
so how many times has this change actually affected things apart from 'I wanted a gun but then I couldn't"

**Comment by coldcola** [comment]
last night as a scientist a cyberhorror I had imprisoned was loosed by someone and since we had no security or anybody willing to make a gun that they would kill themselves with it ended up causing some chaos.

**Comment by PJB3005** [comment]
Either intentional sabotage by an antag in which case 👍, or job ban worthy.

**Comment by SonixApache** [comment]
Sounds like a positive change to me.

**Comment by coldcola** [comment]
this makes me wonder how you think that this is an IC issue that would lead to a jobban for me for having brought something to the station that a non-antag loosed.

this would be similar to a non-antag loosing the singularity and blaming it on the engineer.

**Comment by SonixApache** [comment]
Teleporting a dangerous monster onto the station with no security onboard is a bad idea, one that might lead to a job ban if done repeatedly.
There's been people that got banned for teleporting a few dozen goats into places as non-antag.

**Comment by coldcola** [comment]
So basically, don't turn on the singularity if there's no science or else engineers could get a jobban because they won't have a bag of holding?
Or alternatively, bumrush the Captain's office so you can give yourself all access to cover those bases yourself?

There are many many times that there is either no security or command staff to allow access to guns/fight back against loosed hostile mobs - not just during lowpop either.

**Comment by SonixApache** [comment]
You're comparing the singulo, a highly dangerous destructive energy source that people tend to rather not get too close to, to a monster that gives you free super heals if you let it hit you once.

Stop being a fucking retard, don't teleport dangerous shit within reach of other retards, and loot the armory if you so desperately need guns to help everyone not die when you **do** fuck up.

**Comment by MechaMusume** [comment]
This still hasn't been merged? Whats the hold up, idiots like Sonix screaming this is good even with Pomf saying its bad?

**Comment by coldcola** [comment]
> loot the armory

right. so you're for some methods of gunshittery, but not others.  
really makes one think.
also

> You're comparing the singulo, a highly dangerous destructive energy source that people tend to rather not get too close to, to a monster that gives you free super heals if you let it hit you once.

so you agree, there are better ways of getting energy to the station and thus even starting up the singularity is worthy of a jobban on the potential for someone to loose it (under your logic of jobbans for all)

**Comment by icantthinkofanameritenow** [comment]
Sonix, you're missing the point. 

We have a random event that spawns various nasty things onto the station, including stuff like spider queens, sprites, and hivebot teleporter beacons. It happens even on extended, and our culture makes it rare that security is even fully staffed, let alone competent. How are you supposed to kill an unstunnable, robust mob that can spawn more mobs or put you to sleep with nothing more than a blunderbuss at best? 

This change might have been suitable on Bay, Polaris, or maybe even a medium-RP server like Paradise, but on /vg/ it simply does not work.

**Comment by icantthinkofanameritenow** [comment]
Sonix, you're missing the point (hypocrisy about looting the armory notwithstanding since in most circumstances that's something done most often by antags or shitters).

We have a random event that spawns various nasty things onto the station, including stuff like spider queens, sprites, and hivebot teleporter beacons. It happens even on extended, and our culture makes it rare that security is even fully staffed and able to open the armory without hacking, let alone competent. How are you supposed to kill an unstunnable, robust mob that can spawn more mobs or put you to sleep with nothing more than a blunderbuss at best?

This change might have been suitable on Bay, Polaris, or maybe even a medium-RP server like Paradise, but on /vg/ it simply does not work.

**Comment by SonixApache** [comment]
@coldcola memes really make me think

@icantthinkofanameritenow I know the event you speak of, but the usually a few hoppers or some other shit comes out.
The whole point of the armory is to arm the crew in case of an event where arms are needed, but to keep guns in a safe place when they're not.
Being able to print and pocket guns all the time is fucking retarded -- need guns? Armory.

And yes, sometimes sec is so incompetent that they can't even get the armory open, and even if they did they'd magdump all 6 lasers into a wall and get slaughtered, but so fucking what?

If there's no sec -- get into the armory and defend yourself.
If there IS sec -- work with them and improvise.
Consistent lack of security officers? Want to make sure the station is safe? Think you can do better than the bumbling redshirts? Maybe it'd be an idea to **play sec**, then, instead of being a paramilitary commando in a labcoat.

**Comment by aceedex** [comment]
> either play sec or let the antag/random event fuck you over
Nah. That's retarded
I hate this argument
but go back to bay

**Comment by SonixApache** [comment]
The "I cannot stand being antagonised by antagonists" argument is retarded as well. Want to be a vigilante? Use the tools at your disposal. Want the tools to keep everyone safe? Play sec -- it's their _job_.

**Comment by Shadowmech88** [comment]
> Use the tools at your disposal

The issue here is _what_ tools should be at a civilian's disposal.

Many think that R&D guns should fall into that category.

**Comment by icantthinkofanameritenow** [comment]
> play Sec

I've played it repeatedly, and I feel the need to remind you that your job is the most hated one on the station, and for good measure the admins watch you like a hawk looking for the slightest reason to verify the inevitable accusations of "shitcurity". 

 It isn't for nothing that barely anyone even considers playing Security since we make it so clear nobody wants them around. The lockbox shit does absolutely nothing to stop a server culture that has been actively hostile to security from almost the beginning; even a competent force does nothing to soothe all that latent hatred of redshirts. If you played Security for more than a single round you would already know that for a fact. 

But if you feel so strongly about keeping all guns in Security, how about you cut out all the weapons designs and make a special snowflake machine to produce them that only Security can access? That's way better than just punishing everyone for the douchebaggery of a few people who should have been banned anyway, and God knows that the protolathe is an endless source of feature creep that's been left unaddressed for ages. Seriously,  just look at all the shit added to it with no sign of stopping. 

> Break into the armory

Are you going full greytide now despite insisting this is needed to stop greytiding? The whole reason that lockboxes were even changed to make them openable with weapons permits was because armory access was so dangerous to have!  

And armory access will do a fat lot of good when a wizard has teleported in to steal it all, or a blob has eaten it, and let's not forget xenomorphs' acid can melt guns to destroy them entirely.

**Comment by icantthinkofanameritenow** [comment]
> Want the tools to keep everyone safe? Play sec -- it's their job.

Except for the fact they are constantly shat on for doing it even when they don't fuck up. Only an idealist, a masochist, or a power-hungry thug signs up for security now because the people who want to keep everyone safe would prefer they do that without being a target for every assblasted greyshit and clown on the station in the process. 

Given that nearly everyone despises Sec, it's inevitable they look to the vigilantes instead. Why would they not?

**Comment by SonixApache** [comment]
> If you played Security for more than a single round you would already know that for a fact. 

I'm getting real tired of this meme

> if you feel so strongly about keeping all guns in Security, how about you cut out all the weapons designs and make a special snowflake machine to produce them that only Security can access?

I've been thinking about it. Ideas of an ammolathe have been strewn around for years, it's not a bad idea. If I could code worth a damn, it'd probably already be done.
Protolathe is completely fucked, this is something most people can agree on.

If there's no sec, the armory's easy to waltz into - and a place where the crew can arm itself in case of an emergency. If there's sec - sec can up-arm themselves whenever needed.

Greytiding would be breaking into the armory to acquire guns when there's three officers trying to kill the wizard or whatever.

As for everyone hating sec; I play sec all the time. It's become my main job since I got the pistols in. Most people don't complain about me, some greyshirts do and that's resolved IC. I guess I'm an idealist.

**Comment by icantthinkofanameritenow** [comment]
I already agreed that splitting the protolathe into different machines was the best long term solution, but better to make another issue for that. This is simply to bring back a workable status quo long enough to buy time to tackle the real issue. 

> It's become my main job since I got the pistols in.

So you support Security getting more guns but take them away from everyone else? Kind of hypocritical, given that the pistols are an absolute joke even when compared to the armory's contents. 

> the armory's easy enough to waltz into
> Except that any security present will make sure that even if they can't get in, you sure won't. And practically every Asimov AI will refuse to let you in because "probable harm" (you aren't grabbing that shotgun just to kill a carp, anyone can see that). Even if you do get in, the "act like an antag, get treated like one" rule applies, and breaking into one of the most secure parts of the station is pretty damn antagonistic. And of course, all this still suggests that the armory itself hasn't already been looted or destroyed by whatever you need the guns for to start it. In that case, you're going to need to make new guns somehow.

**Comment by yclatious** [comment]
If you get real tired of people saying something they do bloody believe, prove em wrong like you do here. If PJB sincerely bloody showed us he played recently in any job but engie where he most likely isolates himself from literally everyone in autism engines, I wouldn't shit on him nearly as much as I do since he has very clearly given me the idea and image of someone who doesn't actually fucking play, alongside him saying ss13 is shit in every regard. And saying you aren't a idealist is a bold faced lie mate, course ya are.

You think breaking into a armory and letting it be acessible to the crew is a good idea instead of slowly making a reasonable ammount of weaponry to properly equip people for a threat, even if you are breaking lockboxes. Ignoring sec giving you atleast 15 minutes for that, you bloody bonkers, if a single security officer sees his precious armory looted he will go full on shitcurity, not to mention, like name said, it being antagonistic as fuck, alongside you not wanting people to just get used to raiding the armory, alongside stun revolvers being used with intent of plain non lethal defense most of the time. I don't care if "you" wont go shitcurity, everyone else will, even if its for a murderwiz, I don't trust sec and neither do most of the crew.

I say the status quo is good cause nothing else you folks suggest is actually better or aplicable to the current playerbase, if it doesn't just create bad habits like armory raiding. Gun making, gun busting, gun acquiring, its almost a cultural thing of ss13 in every server, and while I say that indeed you should punish the shitters who abuse the practical yet efficient system, you should not destroy the system itself or atleast butcher it, screwing everyone when they actually need to.

**Comment by Kammerjunk** [comment]
Breaking open lockboxes (including the temperature gun) is wrong, but breaking open cargo crates and the ("secure") armoury is not. I'm not sure I follow that logic.
If cargo orders guns out the rear, you kick down the door. If science makes guns, you should do the exact same.

**Comment by yclatious** [comment]
Yet not punish them my breaking the system, but punishing in a ic matter, and if it remains a issue with the player, its a ding dong.

Way its meant to be resolved.

**Comment by SonixApache** [comment]
somehow my arguments of 'when there **is** security do x, when there **isn't** security do y' is being completely ignored in favor of just yelling 'i plead the second' so whatever

**Comment by icantthinkofanameritenow** [comment]
Hasn't it occurred to you that it's because security being present is the exception and not the rule? Even when it is, just because you play good cop doesn't mean anyone else can be trusted to do the same. 

Plus, I find it hypicritical that breaking into the armory for a bunch of guns is okay in your books but breaking a lockbox for a single buffed taser is not. If gunsci is an issue, security ought to be dealing with it. They shouldn't need to beg the coderbus to save them from their own cowardice.

**Comment by yclatious** [comment]
He ain't wrong sonix, you know it.

**Comment by Shadowmech88** [comment]
Was the original PR fixing a problem that even existed?

Have antags been having a hard time dealing with the crew as a direct result of R&D weapons distribution?

**Comment by yclatious** [comment]
No, never was and never will,  same as retard cargo newbies get dunked real easy by sec, science is the same shit.

Course not, no scientist or variant just distributes in anything but nuke ops/blob, and even then, its 70% fluke with no chances or 30% win without the crew even being suspicious nuke ops ever even were a thing, same thing with blobs, either newbie ones or just plain experienced ones that will greentide better that dionae ever wish they could

**Comment by PJB3005** [comment]
Welp

**Comment by mrpain666** [comment]
IF IT AINT BROKEN, DONT FIX IT!

**Comment by Shadowmech88** [comment]
The problem is that everyone can't seem to agree on exactly what constitutes "broken."

**Pull request merged**
