### PR TITLE
Box Fixes/Changes

### PR DESCRIPTION
**Pull request by Probe1**
Removes blocks_air variable from several exterior door plating objects
Replaces Medical_Locker with Defib_Locker on Vox Outpost
Adds a folder to virology

Fixes https://github.com/d3athrow/vgstation13/issues/10471
Fixes https://github.com/d3athrow/vgstation13/issues/11863

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by Probe1** [comment]
Custom vote started by Kavlax.
https://github.com/d3athrow/vgstation13/issues/11847 Should the Vox Outpost airlocks require Vox Trader access?
Type vote to place your votes.
You have 60 seconds to vote.

Vote Result: Yes with 7 votes
	No had 3 votes

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/issues/12002

I added a folder to viro but it'll take time to question people and see if they want all this stuff.

**Comment by Shadowmech88** [comment]
While you're touching Box, could you make the external airlock directly East of Security open with just Security access, as well as the airlock that separates it from maintenance?
It's quite an inconvenience for officers to have to walk all the way to Arrivals for EVA.

**Comment by Probe1** [comment]
When this PR is closed I'll grab that along with making all the Vox Outpost doors require Vox Access and other misc changes people are petitioning for.  One of these bug fixes are 4 months old and I want to see them get pushed through.

I will remember it and do so.

**Comment by ComicIronic** [comment]
Honk.

**Pull request merged**
