### PR TITLE
Thermoelectric Coolers

### LINKED ISSUE #25818: Thermoelectric Cooler
I'm probably going to code this, but I'm making an issue here first for discussion and also in case I don't.

Currently, there's no legitimate way to get gases below 6.4K, and no way at all to get them below 1K. This is because we have no active means of heat transfer at all. In reality, active heat transfer is usually achieved through thermodynamic effects of compression heating/cooling and phase change. We don't have any of that, and it's not simple to implement.
What is (relatively) simple to implement is just a powered heat pump atmospherics component. My general plan goes like this:
* Pumps heat from one pipeline to another (like the heat exchanger but active)
* Has a maximum possible temperature difference between the cold side and the hot side
  * This temperature difference depends on the absolute temperature of the cold side, so the maximum difference is smaller the closer you get to absolute zero
* Consumes a constant amount of power and moves a variable amount of heat
  * Always less efficient than the TEG, so no infinite power memes
    * It could still be used to get big numbers on the TEG interface if that's what you want, but doing so would reduce the *net* production
  * Amount of heat moved per tick depends on the current temperature difference and the maximum temperature difference, so that in the absence of other effects it asymptotically approaches the maximum difference

Note that (if it's coded properly) you could get arbitrarily close to absolute zero with this device by building a multi-stage setup. Each stage would reduce the temperature by less than the last and do so more slowly, but there's no *hard* limit on how cold you can get. It asymptotically approaches absolute zero as the number of stages increases.

### PR DESCRIPTION
**Pull request by Exxion**
They work roughly as described in #25818, though simplified a bit. (There's no explicit math to figure out how much heat to transfer across it, and instead it just sets the temperatures of its internal reservoirs such that they differ by the appropriate number.) (Closes #25818.)
Currently they work pretty much how they will presumably finally work, except:
1. They lack radio control
2. The various numbers for them will be tweaked

Also they currently just have a shit placeholder sprite which doesn't even indicate whether they're on or off.

Their current numbers are:
* Consumes 1KW while on. (Comes from APCs, which might be a problem if you have a shit ton of them. Have to test that.)
* Maximum temperature difference is limited to 2500 degrees when the gases are hot.
* Cold side bottoms out at half the temperature of the hot side when the gases are cold.

All of these can and probably will be tweaked.

A quirk I'm not sure how to deal with is that they don't really just work when connected directly in a line. This is because there needs to be gas to move the heat from the hot side of one to the cold side of the other, and of course they start out empty. This makes sense if you think about it, but is kind of unintuitive if you don't really think about it.
You can make them work when directly connected by filling the open side of each with gas before you place the next, but this is kind of a pain. This isn't optimal anyway, though, since each stage should have more of them than the previous one due to the decreasing heat transferred per device as the temperature gets lower.

🆑 
* rscadd: Thermoelectric coolers can now be made with the RPD. They will help you reach low temperatures, but they consume power from the APC. They can be controlled with the AAC and interface with a multitool for configuration.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Needing an APC means they can't be set up in space, kind of a hassle eh?

**Comment by Exxion** [comment]
Yeah but setting up a billion wire knots seems like more of one

**Comment by tuypo1** [comment]
What if there was an item you could carry in your hand that acted as an APC to objects you are standing next to, or that you could set down on the ground and acts as an apc to anything adjacent

**Comment by ghost** [comment]
The APC power should not really be a problem if the system is directly connected to a high-power engine i think. I have only used the shield generator-capacitors with this type of high energy drain system and from my experience they will drain the APC for a second and then stabilize despite eating up a lot of power.

**Comment by Kurfursten** [comment]
The main difference here is that with shield gens you always want to be on the inside, and with pipe coolers you often want to be in space

**Comment by Exxion** [comment]
I think he was referring to what I said in the OP
As for these coolers, it doesn't really matter where they are because you can just run a line to some HE pipes out in space, but yeah, building them in space would be convenient because it could take up a fair bit of space if you want to get high throughput and very low temperature
But considering you can get a construction permit or something, APC seems like the lesser of the two evils
Either it uses APC power and just works inside but is a bit of a pain in the ass to set up in space, or it uses wire power and is a pain to set up in either case
Or it could not use power at all, but considering what you can do with these, I don't really like them just being *free*

**Comment by Kurfursten** [comment]
What if you have a controller computer which is where the power comes from (can be inside) and its power drain is based on whatever is linked to it via radio (multitool to link)?

**Comment by Exxion** [comment]
Honestly that kind of thing sounds more like a separate feature you'd want to be able to do with machinery in general

**Comment by Exxion** [comment]
* Now has radio control. I think. I have no idea what the fuck I'm doing with radiocode honestly
* Sprite is still a shitty placeholder but now actually indicates on/off. The difference is hard to see but it's there

Probably ready for testing on the test server to tweak its values

**Comment by Exxion** [comment]
Buffed `mtd_slope_at_zero` a bit from 1/2 to 2/3. Haven't really gotten a chance to test the impact this has yet, though.

I'm going to go ahead and testmerge this to the test server so other people can try it out. Leaving some tips here before I write a Wiki entry so that people don't just flounder:
* You need a fuckton of space cooling if you want to get any reasonable pressure of supercold gas just because of the sheer amount of gas you have to cool off.
* Since they instantly set the temperatures of their internal reservoirs, the rate of cooling depends on the ratio of the volume of their reservoirs to the total volume of the pipeline, not the absolute number of them you have. Manifold-stacking them isn't actually all that helpful unless you have a significant total volume of other pipes/devices in the same pipeline. (Note that passive gates have quite large volume on the input side, so even one of those in the pipeline might make stacking worthwhile.)
* Since they instantly set the temperatures of their internal reservoirs, they transfer more heat the more gas is in them, so it's beneficial to pump up the pressures between them, too.
* This is mentioned above but **just attaching them directly together in a line doesn't work unless you pump gas into the open end before you connect the next one**. If you *do* pump gas into the open end, though, this setup maximizes ratio of cooler volume to pipenet volume, so it's actually pretty good. Just make sure you get enough gas in there to move heat as quickly as you want.

You also might want to at least skim the comment at the top of the file for details on how they work.

**Comment by Exxion** [comment]
I don't think anyone else tried them, but after trying it out myself, I like 2/3 for `mtd_slope_at_zero`. It makes it so that in practical use, you can actually get the cold side to half the temp of the hot side.
I might increase power usage, but I'm not sure. Also I completely have no idea if `mtd_limit` should be changed. Honestly I doubt the latter will be very important, but maybe people will come up with other uses for these that make it matter.

Still needs sprites and I do need to fix one minor bug, but it should be ready other than that.

**Comment by Kurfursten** [comment]
I actually like your placeholder sprite

It's distinctive, simple, and easy to read

**Comment by Exxion** [comment]
The on/off state definitely isn't easy to read

**Comment by Kurfursten** [comment]
Make the middle bit spin while on like a turbine, the rest is great.

**Comment by Exxion** [comment]
* Added an improved on state courtesy of @Kurfursten 
* Made them actually work with the AAC
* Steeply increased power usage from 1KW to 5KW because you don't normally need to layer them. Frankly all engines except solars produce enough power to run plenty of them either way. Also the APC issues I was told about don't *seem* to be present anymore. They'll certainly drain an APC quickly if it's not charging, but even with dozens of them they don't seem to have issues related to the cell while it *is* charging.

Numbers still probably need tweaking but the best way to get people to test them is on live, so I'm calling this done unless bugs are spotted.
Still need to write up a Wiki entry, though.

**Comment by Kurfursten** [comment]
I didn't see anything obvious, let's move it forward for testing. I added a CL.

**Pull request merged**
