### PR TITLE
Fixed syndie shoes getting the ninja shoe message.

### PR DESCRIPTION
**Pull request by ghost**
Title says it all, since the addition of ninja space suit the New() for the ninja magboots would send a visible message after 130 seconds. I moved it to a new proc, activateMagnets, and added activateMagnets to the ninja spawn.

### CODE REVIEW

**Comment by SonixApache** [comment]
*Syndie* shoes were getting the ninja message? That's super weird.

**Comment by ghost** [comment]
Syndie shoes work by creating a new instance of every shoe in the game and then adding them to an internal list. Since the ninja shoes deactivated 130 seconds after being created, it would get this message. Thanks oldcoders.

**Comment by SonixApache** [comment]
jesus christ how horrifying

**Comment by DamianX** [comment]
Wow, that's bad. An alternative fix is to make the syndie shoes do what I did to the voice changer to avoid creating objects at all.

**Comment by Blithering** [comment]
Also the ninja gear should really only give the message to the wearer, its a bit weird walking through arrivals and suddenly being told that the ninja suit has lost its space protection

**Comment by SonixApache** [comment]
It's a visible message, though I guess reducing the range might not be a bad idea.

**Pull request merged**
