### PR TITLE
Can now make Ice from water

### PR DESCRIPTION
**Pull request by ghost**
Some simple fluff to give frost oil some reason for existing, considering we have no way to heat or cool the contents of beakers outside of atmos fuckery

Now ice is no longer in limited supply, bring out your frosted beers

:cl:

* rscadd: Can now make ice from water using frost oil

### CODE REVIEW

**Comment by ghost** [comment]
Ready on updating wiki

**Comment by ghost** [comment]
Wiki updated

**Review by PJB3005 — APPROVED** [review]

**Comment by Probe1** [comment]
you know shits fucked up with reagents handling when this PR gets made.

**Comment by ghost** [comment]
I hope for the day we can get heaters and freezers in use for chemistry

**Comment by Exxion** [comment]
First, we'd have to actually have reagent temperatures

**Comment by ComicIronic** [comment]
Reminder that goofchem had temperature.

**Comment by Exxion** [comment]
I thought about mentioning that and decided not to because I didn't want to summon him

**Pull request merged**
