### PR TITLE
Time Agent Rework

### PR DESCRIPTION
**Pull request by ghost**
Note: I haven't done anything yet, collecting feedback. Please leave any suggestions below!

Time agent is absolute garbage right now, essentially just a guy with an antag pass and some subpar wizard spells. Here's my rework:
- The good time agent and evil time agent now spawn at the same time.
- Both of them are given a singular, competing goal at random that gets resolved exactly 15 minutes after they spawn in. This goal is different and selected from a pool - for instance, this might be "ensure [person] is alive" for one agent and "ensure [person] is dead" for the other.
- 15 minutes after they spawn in, the crisis is resolved based on that criteria. Depending on who won, either a good event or bad event happens at random as the "timeline shifts", bringing everyone's consciousnesses to a better or worse timeline. An example of a good event would be replacing every window with reinforced plasma versions - anything that makes the station better. An example of a bad event would be randomly turning people into vox (lore-wise, switching over to a timeline where they were always vox). Or switching everyone's perspective so the station is upside down. Or scrambling the order of every reagent dispenser on station. Or replacing every airlock with a "Nanotrasen Toll Door" which charges you 10 credits every time you open it and denies you otherwise. Or replacing every O2 locker with really annoying advertisement Discount-Dan bots that constantly scream informercials and attack you if you try to shut them up.
 
Other notes:
- Rework their kits slightly so that if the time agents end up trying to murderbone each other it won't be a boring 5 second affair - maybe give them a one-time go-back-in-time savepoint that can be used even after death?
- Give them a less annoying way to escape maintenance.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
why not just make an issue

**Comment by west3436** [comment]
An easy and funny option for the altered timeline could be just to pick a random player and explain what happened to them after the round prior to showing the credits, be it good or bad:

https://youtu.be/u61F_qvdid0

**Comment by ghost** [comment]
Nobody replies to issues.

**Comment by Eneocho** [comment]
Would be cool to see. Requesting that you also add the missing time grenade to the time agent grenade belt.

**Comment by SECBATON-GRIFFON** [comment]
i reply to issues THOUGH

**Comment by BomberBro** [comment]
Their gun kind of sucks it should shoot energy shit and have its own sprite instead of being an infinite revolver

**Comment by SECBATON-GRIFFON** [comment]
> Their gun kind of sucks it should shoot energy shit and have its own sprite instead of being an infinite revolver

would definitely fix the shrapnel bug

**Comment by Dacendeth** [comment]
The evil twin should spawn with a goatee.

**Comment by Theophrastus1** [comment]
i like the idea of bettering or worsening the station. Shit like killing or protecting the HoP either drains everyone's bank account or gives them a huge bonus. Things alone those lines

**Comment by hacker-on-steroids** [comment]
might be hard to do but i think it would be cool if the event removed all of a certain item and prevented them from spawning again, say insulated gloves or mini health analyzers
"danitos cool ranch flavor? what the hell are you talking about?"

**Pull request closed without merging**
