### PR TITLE
Cuffs PR tweaked

### LINKED ISSUE #32030: You can mine out-of-range ore while spacewalking
(WEB REPORT BY: cartlord REMOTE: 206.221.180.138:7777)
# Revision
fdfb1508429b2447967053fe8d40b75e05cb6a47

# Description
While spacewalking on the asteroid Z-level, I noticed that I was able to hit a rock with a pickaxe, and then walk away - but the progress bar stayed on-screen, and the ore mined itself when it filled! Activating and deactivating magboots seemed to have no effect on reproducibility, nor did walking/running.
However, I did find that walking on asteroid sand while the progress bar ran down cancelled the mining. Walking on lattices and catwalks had no such effect.

# Steps to Reproduce
-Spacewalk
-Hit rock with pickaxe (works with standard, unsure of if it works with other picks or drills)
-Walk away

# What you Expected
The mining job should cancel, as I am no longer in range.

# What Actually Happened
The mining job continued, potentially allowing for a vast increase in asteroid mining speed!

### PR DESCRIPTION
**Pull request by adacovsk**
This PR cancels progress bar while changing direction. I should've included this in the cuffs PR I made. Otherwise, while doing atmos work on pipes or mining, you can't cancel your actions easily. Closes #32030

:cl:
 * tweak: can cancel progress bar actions in space again

### CODE REVIEW

**Comment by DamianX** [comment]
It still means you can keep moving indefinitely far away while you do a progress bar action as long as you don't change direction. Doesn't make any sense.

**Comment by adacovsk** [comment]
> It still means you can keep moving indefinitely far away while you do a progress bar action as long as you don't change direction. Doesn't make any sense.

I'll try to add an istype for cuffs

**Comment by DamianX** [comment]
Awful. You should try to find a way to determine if someone is moving due to inertia.

**Comment by adacovsk** [comment]
> Awful. You should try to find a way to determine if someone is moving due to inertia.

might be awful but it works properly... I'll try to find something.

I can't find anything that works, sadly. :(

**Comment by Kurfursten** [comment]
Some jobs care about whether or not you're adjacent to an outside object, others don't. Just make this a var. In order to slice open a wall or mine ore, you need to remain near that wall/ore. In order to weld knives or remove handcuffs, you just need to remain near that object. You could just change it to be an alternate form of do_after that cares about proximity to an item instead of a turf. That being said, that would allow for unlocking handcuffs while walking... not sure if people want that.

The way to do this would be to create a new var for mobs `progress_action_location` that tracks the turf they're supposed to be working on (this needs to be nulled in Destroy of course). The var gets set when you start a task that calls a progress bar and nulled if the job is completed or interrupted. It can be updated in process_spacemove() to move the location with the player. This could also theoretically allow for other actions while being moved. For example, if you wanted, you could make it so that a person who is cuffed to a wheelchair could work on breaking open the cuffs as they're being carted around.

**Comment by adacovsk** [comment]
>  a new var for mobs

this sounds really smart, I don't know if I'm capable of doing it. Well, if this is merged, it should revert the previous change I made. And I'll tinker and toil to get that to work, potentially in another PR.

**Pull request merged**
