### PR TITLE
Omnitool Cleanup

### LINKED ISSUE #29762: Omnitool ranged APC/Air Alarm interaction
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
16ebae11f40f3539400fd07f8cb13e4caaf428d5

# Description
stand 5 tiles or closer to APC (and Air alarms, too), click APC with omnitool = can't click buttons. Stand further than 5 tiles away - can click buttons
# Steps to Reproduce
buy/steal/make/procure omnitool, stand far away from APC, click it with omnitool in active hand
# What you Expected
can fiddle with APC at any range
# What Actually Happened
can only fiddle if I'm far enough away.
AND the interface windows still close, probably doesn't want to be fiddled with.

### PR DESCRIPTION
**Pull request by Kurfursten**
closes #29762

This is the triumphant return of the omnitool as more than a curiosity, but a great tool. Man this was a pain to get working.

🆑 
* tweak: The omnitool (from the cloud ix crate) now properly allows you to remote control any APC or air alarm as though you were a silicon, as long as you have the appropriate access. This means it will be "unlocked" even remotely when the omnitool is in your active hand.
* bugfix: Fixed the bugs with using the omnitool at range.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you remotely alt+click the APC/Air alarm to unlock them as well?

**Comment by Kurfursten** [comment]
No, it just behaves as though unlocked for you when you view it, like you're a silicon. So assistants can't "tailgate" your access to an APC. If you switch the omnitool to your inactive hand, you can't use it, either.

**Comment by Killette2** [comment]
If you access the APC then walk away but keep the menu open, can you still use it?

**Comment by Kurfursten** [comment]
The target needs to be within your client's view range, so you can use it from further away if you carry binoculars, but simply walking away won't let you keep using the menu.

**Pull request merged**
