### PR TITLE
Smooth movement for pushing things

### PR DESCRIPTION
**Pull request by DamianX**
https://user-images.githubusercontent.com/6307265/135584904-f16d76d4-24d5-45d0-8c8f-98e64be7870c.mp4

https://user-images.githubusercontent.com/6307265/135584888-2771e50e-5ca2-4fd5-a30b-c0c139b5023a.mp4

~~The changes look big but all I'm doing there is removing the `spawn(0)`s and de-denting everything that was under them. I don't know if that's even necessary. It'll probably cause some obscure problem but I guess we'll find out.~~

:cl:
 * tweak: Bumping into something to push it will now move both you and the thing smoothly, rather than taking turns stepping. It's also as fast as moving as if the object wasn't there.

### CODE REVIEW

**Comment by Exxion** [comment]
Not even going to slow down the movement when pushing?

**Comment by Eneocho** [comment]
This feels illegal. Keep going.

**Comment by BomberBro** [comment]
Needs to be slower when pushing to reflect how it used to be, but otherwise fantastic work.

**Comment by DamianX** [comment]
why?

**Comment by BomberBro** [comment]
Because currently it's slower? This more than doubles the speed you can push things, and if that's intended with the PR then that should be reflected in the changelog.

**Comment by DamianX** [comment]
1984

**Comment by DamianX** [comment]
I've restored the old ugly `spawn(0)`s to fix a bunch of bugs found by @Dacendeth and updated the changelog as per our tyrant

**Comment by Kurfursten** [comment]
Confl

**Comment by Exxion** [comment]
I'm still going to accuse the doubled speed of being powercreep

**Comment by DamianX** [comment]
I think this makes the server explode, hold on.

**Comment by Exxion** [comment]
Yeah, looks like it would

**Comment by Exxion** [comment]
`step()` itself also returns whether or not it succeeded

**Comment by DamianX** [comment]
The latest commit makes it not explode the server but I don't know why pushing multiple things is no longer smooth. I also don't feel like implementing a slow for it.
I think I'll just close this for now.

**Comment by Exxion** [comment]
space worms...

**Pull request closed without merging**
