### PR TITLE
Bagel vox ship

### PR DESCRIPTION
**Pull request by Probe1**
I noticed that Bagel had a copy/pasted ship from Box so here we are.  I'm not sold on having thrusters in every direction even if it sounded fun in my head.  If others think it's a silly idea I'll torpedo them.  The bit in the center is plasma glass flooring.

image

image

🆑 

* rscadd: Bagel now has a unique vox tradeship.

### CODE REVIEW

**Comment by Durgen** [comment]
the huge space inside is great, plenty of room for ancap healthcare facilities

**Comment by Probe1** [comment]
Don't violate the NAP

**Comment by Kurfursten** [comment]
Neat

>Drink dispensers

I know Bagel is the "give everyone toys" map but this might be a little far. The bartender doesn't even start with these.

**Comment by Probe1** [comment]
I was thinking about https://www.youtube.com/watch?v=UjLO_CrZRmM but with vox instead of Chinese Guy.  If it's too much I'll do something different but I'm not sure what.

**Comment by Kurfursten** [comment]
Maybe just empty out the Vox outpost kitchen and move some stuff over. Stools, those kitchen turfs, microwave and deep frier. Put some soy sauce on the tables.

I can help you with paper lantern sprites, and we've got Chinese signs in decals.dmi

**Comment by Probe1** [comment]
That'd be a real pain for the players to trek stuff from botany to the ship.  I'm not sure if that's the right direction.  And removing the drink machines seems superfluous when they already have them.

BUT

You did make me think how excellent it'd be to have a trade post on a ship.  Super basic, only whats needed.  Vagabond only no home final destination.  I don't see that fitting into any of our existing maps but it's an idea I'm going to hold on to.

**Pull request merged**
