### PR TITLE
ERT uniforms and holochips 

### PR DESCRIPTION
**Pull request by JMWTurner**
duplicate of #12676 that got fucked because github shat itself yesterday.

@ComicIronic @PJB3005 

86004900-baa1-11e6-8867-837d0be4c418
f9911c2e-bb22-11e6-8f5e-7ab86ed57cac
88b901c8-baa1-11e6-96fc-1de8fe02333c
9461e68e-bb23-11e6-9150-c3e001f15e7a

:cl:
* rscadd: ERT now spawn with brand new uniforms featuring holochips. The markers on their holomaps update depending on which helmets are the ERT wearing.
* rscadd: The deathsquad holomaps now track their marauders and seraph. The markers also update depending whether the squadies are piloting a marauder.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by NigglyWiggly** [comment]
>That dark black outline

**Comment by JMWTurner** [comment]
dark grey. Nice ain't it? It merges well with the jackboots and sec backpack.

**Comment by Probe1** [comment]
Alt-255 niggles. 

 >memes

------------------------

Don't remove the old sprites from the repo I quite like them and would enjoy seeing them reworked into something else, even if it's random space loot.

**Comment by JMWTurner** [comment]
@Probe1 What old sprites? That's the SWAT mask on the "before", I'm not removing it, sorry if this wasn't clear, I'm only making ERT not spawn with those anymore, and instead their internals box spawns with a gas mask that uses the old gas mask sprite.

**Pull request merged**
