### PR TITLE
Order Shuttles

### PR DESCRIPTION
**Pull request by Kurfursten**
This is very close to completion, I just have a few things to finish

* Finish mapping deluxe, old, and cargo shuttles.
* Find a better way to dispose of previous shuttle than qdel (leaves behind stuff like locker contents or coin boxes from nanomed)
* Find a better way to align shuttle spawning at centcomm. Currently it's off by 2x1 tiles which is... important. Hit me with suggestions.
* Prevent ordering shuttles after the shuttle has left (oversight)
* Test shuttles, so I notice things like the missing lights in deluxe shuttle

Optional: Add a button for admins to set the shuttle regardless of money in station account

General commentary:
* Does not appear to cause a lag spike when it loads because the maps are small enough
* You would need to custom-make shuttles for each map, but it's quite easy to do so one map or shuttle at a time, you don't need to make a new shuttle design for each map, so it's very easy to do one or two here or there and have unique shuttles for each map
* Shuttles are purchased from station account funds, price subject to change

Comms Console
image

Example shuttles pictured (all packed) (top to bottom: plasma response shuttle, armored shuttle, DIY shuttle)

Untitled

:cl:
* rscadd: On Packed Station, you can now order alternate emergency shuttles if there is enough money in the station account.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
This is a great idea with lots of potential. The DIY shuttle is going to get a lot of captain's lynched.

**Comment by PrimeDSS13** [comment]
When you buy a shuttle, does it arrive to the station looking differently or does it come immediately?
Alternatively, wouldn't the "DIY" shuttle be non-pressurized?

**Comment by Kurfursten** [comment]
1) It changes the shuttle at Central Command immediately. It doesn't change the time it docks.
2) Yes, it says in the description that the DIY shuttle has no air, which it does not.

**Comment by Kurfursten** [comment]
Over Discord, Prime suggested to me that maybe the DIY shuttle is just too over the line. I mean, you can't survive it at all without a suit or a shelter! I have decided that the DIY shuttle will probably need some kind of special access like Rainbow Alert or Emag.

Instead, here's another absolutely miserable shuttle to ride on that will provide a discount like the DIY shuttle, but it's just cramped and ugly, not impossible to breathe in.
image

Deluxe Shuttle up next.

**Comment by PrimeDSS13** [comment]
very nice

**Comment by SonixApache** [comment]
wouldn't those r-windows in the yellow shuttle medbay section explode due to thruster fire?

**Comment by Kurfursten** [comment]
I'm moderately confident that thrusters won't fire through glass but it will have to wait until testing to find out!

**Comment by tuypo1** [comment]
Would it be easier to simply adjust centcom itself when the shuttle is ordered rather than trying to adjust the landing point of the shuttle

Also I feel that having the surgery table makes the atmos shuttle TOO good, although I suppose in most situations where it would matter somebody will probably take a switchtool and table there anyway

**Comment by Kurfursten** [comment]
It does create the shuttle at Centcomm, the problem is that when it loads the mapfile currently it's off by a few tiles because it's trying to align based on what it thinks the bottom left tile of the emergency shuttle is. I need to look at shuttle code and figure out how to generate it based on the dock.

I'm not too worried about the optable because this requires (1) someone with captain access to think about it ahead of time and (2) spend the money from the station account. If they were going to do that, they could just go by an autolathe and grab a scanning module (to make the table) and print all the tools for the cost of like 2 metal and glass.

Also consider that all of these shuttles come at a cost of passenger space. Atmos shuttle may offer nice spacious rooms for medical treatment and cleaning, but it has barely any seats. People will be playing musical chairs if you call this shuttle with a lot of survivors.

**Comment by Kurfursten** [comment]
image

Who needs a command cockpit or mini medbay when you can have a smoking room, rumpus room, stargazing lounge, and wildlife preserve (brig)?

Notes
* Lasers are practice lasers
* Has no sound system for normal shuttle music, pick your own with the jukebox
* Stargazing lounge is plasmaglass floor
* The cage sits on a red brig floor for denying escape greentext (if it matters anymore)

Just one more (old shuttle) and I'm calling it done for the mapping portion

**Comment by SonixApache** [comment]
same thing for the gold one - pretty sure the fire will obliterate the r-windows, nuking the smoking lounge and all connected zones

**Comment by Kurfursten** [comment]
image
Testing on live seems to show that 1 window can stop all fire without risk of damage, unless emergency shuttle flames work differently.

**Comment by SonixApache** [comment]
i am confirmed to be a fool

**Comment by gurfan** [comment]
😔

**Comment by PrimeDSS13** [comment]
😔

**Comment by Eneocho** [comment]
Any news on this or will it forever remain on WIP?

**Comment by Kurfursten** [comment]
Not being developed right now but might in the future

**Comment by Eneocho** [comment]
Can you revive this? It was cool.

**Pull request closed without merging**
