### PR TITLE
europa lights

### PR DESCRIPTION
**Pull request by ghost**
for finishing what's been done on this branch so that larger/somewhat unrelated changes can be made separately
also updates from bleeding edge

### CODE REVIEW

**Comment by Intigracy** [comment]
I think something went wrong.

**Comment by jknpj** [comment]
those conficts tho

**Comment by ghost** [comment]
force pushing instead due to conflict issues

**Comment by Exxion** [comment]
This is why you rebase, folks

**Comment by ghost** [comment]
also keep in mind that this is for the separate europa lights branch, not bleeding-edge
proper PR will be made when it's ready

**Comment by mattroks101** [comment]
Are they still very laggy? 

_Sent from my ZTE B2017G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
