### PR TITLE
Merge pull request #1 from d3athrow/Bleeding-Edge

### PR DESCRIPTION
**Pull request by Sikras**

### CODE REVIEW

**Comment by clusterfack** [comment]
It's ok we luv you

**Comment by Sikras** [comment]
I am too dumb to figure out githubbbbb :(

**Comment by clusterfack** [comment]
Try sticking with a git client like smartgit, also git in itself is a challenge to use properly you can always come ask questions in irc

**Comment by IratePirate** [comment]
DELETE THIS

**Pull request closed without merging**
