### PR TITLE
Revert "Revert stock parts using plastic"

### PR DESCRIPTION
**Pull request by 9600bauds**
What the fuck, @clusterfack? #9226
Opens #9220

Seems like I can't actually push to this branch so I can't undo the changelog

### CODE REVIEW

**Comment by Probe1** [comment]
What a terrible night to have a curse.

**Comment by 9600bauds** [comment]
I'd assume his finger slipped or something if not for the changelog.

**Comment by Boxe** [comment]
:eggplant:

**Comment by clusterfack** [comment]
My version won the player votes

**Comment by Boxe** [comment]
>My version won the player votes

:eggplant:

**Comment by 9600bauds** [comment]
> Clusterfack: server votes are fucking stupid guys
> Clusterfack: except when I win them!

firefox_2016-04-24_22-19-39

**Comment by clusterfack** [comment]
Oh yeah I'm soooo biased
http://puu.sh/ouCQb/19da7156df.png

**Comment by Probe1** [comment]
G, S, U + Tweaks 0 + 1 + 2 = 3 which brings the GSU total to 22, and the plastic total to 24 which is fairly fucking narrow and why I stated that G S U had the higher total.  The split between G S U versus plastic was larger than the split between both options combined.

**Comment by 9600bauds** [comment]
When close to 50% of the server doesn't want a change it probably shouldn't be self-merged

**Comment by clusterfack** [comment]
As if the person who merges it changes whether or not people voted for it in any way

**Comment by 9600bauds** [comment]
I should add that the "server votes are fucking stupid" quote actually does come from you, by the way

**Comment by clusterfack** [comment]
I do think they are stupid, but that seems to be what convinces you people someone is right.

**Comment by Probe1** [comment]
They are but what we have little alternative.

Everyone just chill out and don't open/merge things for the night please I don't want to see mommy and daddy fighting.  Lets argue then resume the merge wars in the morning.

**Comment by 9600bauds** [comment]
oh look the votes are ever so slightly in favor of this PR
I'd better merge it now

**Comment by Probe1** [comment]
Please keep level headed in the face of what you rightfully view as bullshit.

**Comment by Iamgoofball** [comment]
@9600bauds but that also means close to 50% of the server wants the change

**Comment by Boxe** [comment]
@Iamgoofball

100% of your parents regret having you

**Comment by 9600bauds** [comment]
What I'm saying is that if the split is that close, you probably should reach a different compromise.
We're not forcibly choosing between two presidential candidates right now and without any third parties.

**Comment by 9600bauds** [comment]
[Feature Loss Loss]

**Comment by clusterfack** [comment]
Oh please I returned it to how it rightfully was before a change was made that was done immediately with no discussion.

**Comment by 9600bauds** [comment]
I see plenty of discussion against the revert, though.

**Comment by clusterfack** [comment]
And plenty for it

**Comment by Probe1** [comment]
I think bauds is right to be offended that it was a self merge.

But I also agree with the previous PR being merged.

**Comment by 9600bauds** [comment]
I believe the term for that is "not a consensus"
Which means maybe a better idea should be reached. And we did, since a better idea was laid down in the comments.
https://github.com/d3athrow/vgstation13/pull/9226#issuecomment-205070080
which maybe I've been in the process of roughly coding the basics for in the past week
hey, can I pull the riri card of "nobody touch anything even tangentially related to this thing I have no ETA on and might not even finish"?

**Comment by AutismSpider** [comment]
if not going revert add some fucking plastic on the derelict or give mommis the power copy wood and plastic getting real sick of praying for some plastic or asking the station mommi for mushroom seeds+tools

**Comment by pompossum** [comment]
Alright, as a guy who constantly plays science, this is an awful change that Clusterfack added and fully support reverting back to plastic. I ended up making an account just to comment on this issue, so hear me out for a bit. Research takes about 5-10 minutes tops for experienced players and it's boring as shit and nobody fucking likes it, but it's required for nearly all parts of the science wing, including the mechanic's office (and I guess the derelict but MoMMIs don't spawn with plastic OR whatever materials you changed, so it's kinda pointless except for basic research.) As a scientist doing research, you have to either hope and pray that a miner is actually competent enough to bring you minimal materials roundstart with this change in effect or go and get them yourself, and when you're the only scientist during the round that makes it harder to get anything done in science because you're fucking around on the roid for another 10 minutes. Making research longer and more tedious than it needs to be doesn't fix the damn problem. Now I either have three options for research at this point: 1) Use basic parts and stand there like an idiot waiting for a measly amount of sulfuric acid for another 15 minutes just so I can get two stupid circuit boards and then wait even more for the other three circuit boards I need, 2) Beg miners for 5 sheets of all materials immediately, wasting their time when they're trying to autism mining like I'm autisming sciece, or 3) Hope that there's an HoP or competent head so I don't have to steal the spare to give myself access to mining just so I can get more materials. Clusterfack please for the love of god revert this.

**Comment by Probe1** [comment]
Those miners need to git gud.  You should have no less than 30-40 of each plus 10 or more diamonds and be standing in front of RnD at 12:15.  I like the point you're making but its also a sign of what research is.  Just this burden that you take the quickest path possible to complete.

**Comment by FudgePucker** [comment]
JUST MAKE TIER THREE PARTS ONLY REQUIRE METAL AND GLASS. HOLY SHIT THIS IS GETTING RETARDED.

the tier three parts required USG because they didn't want them made round start.

They were changed to require plastic... So mechanics could make them round start.

THIS IS FUCKING RETARDED

TIER THREE PARTS ONLY REQUIRING METAL AND GLASS ISNT GOING TO DISTURB THE BALANCE OF THE DEPARTMENT THAT CSN MAKE GUNS BETTER THAN ANYTHING IN THE ARMORY AND AI UPLOADS.

FUCK IT.

**Comment by AutismSpider** [comment]
@FudgePucker a job we should not have and a charged that should have never happen for memey and useless job

**Comment by 9600bauds** [comment]
I have more faith in #9665 than in this, and stock part meta might change soon if I finish my machine upgrades overhaul so

**Pull request closed without merging**
