### PR TITLE
Get rid of clongspam

### PR DESCRIPTION
**Pull request by N3X15**
:cl:
 * tweak: Each mob will now see only one "Clong, CLONG!" per second.

/:cl:

### CODE REVIEW

**Comment by Probe1** [comment]
I will miss you clong spam.

Also theres something about pAIs that spam ATROCIOUSLY HARD either when they ping a pAI to let people know to turn it on or they wipe themselves and shut down. I need to find out which it is but hoooooly shit does it spam.

**Comment by 9600bauds** [comment]
Does this really warrant one whole variable per each mob in existence? I remember the shitshow we had in the wiz highlander PR over this.

Maybe you could just implement the "cooldown" as checking world.tick % 5 or something?

**Comment by N3X15** [comment]
@9600bauds This ensures that one, and only one clong can get through per tick.

**Comment by 9600bauds** [comment]
How about moving this cooldown variable to the hearer instead? We could even have an argument for visible_message() to implement other cooldowns more easily i.e. for the PAI

**Comment by N3X15** [comment]
@9600bauds It IS in the hearer.

**Comment by 9600bauds** [comment]
Hearer as in the virtualhearer, only mobs with clients in them get one

**Comment by N3X15** [comment]
@9600bauds If you feel that strongly about refactoring a complex system with tentacles in a lot of code, go for it.  I'm not going to put any additional effort into a simple spamcheck.

**Comment by SonixApache** [comment]
CLONG!! 
clong!!

Why even build hitlerloops if nobody gets clonged upon anymore?

**Comment by Probe1** [comment]
I know.  But they'll still be clonged. Just not as bad.

**Comment by Exxion** [comment]
OK I appear to be a minority here, but I *like* the clongspam

I mean
Up to a limit
If someone's just flying by in the tubes, I want to hear all the clongs so I can hear them approach and leave
But a loop in a hallway might be a bit excessive
But that would be hard to implement

**Comment by Probe1** [comment]
I feel like I'm saying this a lot but "I know." I totally feel the same way but I'm not gonna ask for an elegant solution to fix something thats funny but insignificant.

**Comment by Sprok0** [comment]
The clongspam has literally crashed my client before, probably because of goonchat, it needs to calm down

**Comment by Zth--** [comment]
Half a second and make it a deal

**Comment by Shadowmech88** [comment]
I also vote for the spamfix only applying after half a second or so, if possible.

**Comment by Kurfursten** [comment]
What if instead of spamming up chat, it played a sound, like an actual clong?

**Comment by Probe1** [comment]
But it does.  It does both.

**Comment by N3X15** [comment]
I did not limit the sound, just the chatspam.

**Comment by Probe1** [comment]
If you could pick an inelegant way to do it this would be it but it's the way it's going to be done unless someones got a better one.

Also @Zth-- pop up that PR making it half a second.

**Pull request merged**
