### PR TITLE
artifact analyzer ghosthands

### LINKED ISSUE #32770: Ghosts can bully xenoarchs
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
f09e2ee4925457339d9196fd826de7cf3203d23c

# Description
Ghosts can halt anomaly scanner scanning process (and launch it)
# Steps to Reproduce
be ghost, click anomaly scanner
# What you Expected
nothing
# What Actually Happened
I made a scientist believe his machines were only scanning when he wasn't looking. Quotes from xenoarch: "I hate living", "I'm gonna scream"

### PR DESCRIPTION
**Pull request by nervere**
Ghosts can endlessly troll xenoarchaeologists by cancelling the scan on their artifacts.
@dinnerwoerror I know it was you.
[bugfix]

Fixes #32770
## Changelog

:cl:
 * bugfix: Ghosts can no longer toggle scanning with the xenoarchaeology artifact scanner.

### CODE REVIEW

**Comment by adacovsk** [comment]
I don't think it needs `user.stat`, does it?

**Comment by nervere** [comment]
Probably not.

**Comment by wotisjanitor** [comment]
adacovsk thumbed it up, you know what to do discord dudes

**Comment by pedr69** [comment]
closes #32770

**Comment by dinnerwoerror** [comment]
get bullied tgmin

**Comment by Eneocho** [comment]
The end of an era.

**Pull request merged**
