### PR TITLE
Magivend smart boxes + two new costumes for clown/wizard

### PR DESCRIPTION
**Pull request by ghost**
* Wizard costumes in the magivend now come in smartboxes. Shoes can still be selected separately, same with other miscellaneous items that didn't belong to a specific costume.
 * Fixed a bug with the winter wizard coat to make sure that the hood counts as magic garb. 
 * Also added two new costumes: another cold resist wizard set, and a clown costume that also has a wizard variant. Sprites for the clown outfit are by Germansanta.

dreamseeker_649iRMGaXq

:cl:
 * tweak: Magivend now uses smartboxes for wizard costumes.
 * rscadd: Added one new outfit each for clown and wizard.

### CODE REVIEW

**Comment by BomberBro** [comment]
Could you post pictures of the the new clown and wiz outfits?

**Comment by ghost** [comment]
Literally taking screenshots RIGHT NOW

**Comment by Kurfursten** [comment]
Reminder that icondiffbot exists

EDIT: Well I shouldn't have expected anything less than a meme game reference from GermanSanta

**Comment by ghost** [comment]
> meme game

And to think I respected you....

**Comment by SonixApache** [comment]
delet meme game references

**Comment by utilitas-** [comment]
unatomic fuck off

**Comment by ghost** [comment]
> delet meme game references

ok, you first

**Comment by kilozombie** [comment]
>jevil costume doesn't make you able to do anything

Actually unbased, cringepilled game reference bad.

**Comment by ghost** [comment]
Didn't think people would feel so strongly about meme game references, so I won't try to force it.

**Comment by ghost** [comment]
image
weak

**Comment by SonixApache** [comment]
the boxes are good though

**Comment by kilozombie** [comment]
If I'm being honest the meme game references don't peeve me at all but I get people's grievances

Boxes are definitely good

**Comment by ghost** [comment]
#24914

**Pull request closed without merging**
