### PR TITLE
Cult Faction datum

### PR DESCRIPTION
**Pull request by DeityLink**
cult reporting in

### CODE REVIEW

**Comment by jakmak6** [comment]
have we started the fire

**Comment by yclatious** [comment]
Cult 3.0 soon spessmen

**Comment by DeityLink** [comment]
obviously there's nothing I can do about that failed travis check.

**Comment by Chazach** [comment]
Nar-Sie's ultimate goal is to tear open a breach through reality so he can pull the station into his realm and feast on the crew's blood and souls."

m-muh potent ham it's just a book you can't know that for sure

**Comment by MadmanMartian** [comment]
@gbasood This stuff's going into the role_datums section, so it is going to fail to compile as most of the role datum stuff isn't finished yet.

**Comment by gbasood** [comment]
yes
i am aware
that's why it's DNM

**Comment by Intigracy** [comment]
vgstation-coders:role_datums

**Comment by gbasood** [comment]
o

**Pull request merged**
