### PR TITLE
Most xenoarchaeology tools now make some sounds when being used

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* soundadd: Most xenoarchaeology tools now make some sounds when being used.
* bugfix: You now get visual and sound confirmation that you've hit a large artifact with an object.

### CODE REVIEW

**Review by jknpj — CHANGES_REQUESTED** [review]
use the toolsound var and playtoolsound proc instead.

**Comment by DeityLink** [comment]
@jknpj don't those only let you pick one sound?  the tools here often use two different sounds at least depending on the context (for example, the depth scanner has 3 different sounds, one when it scans, one if it finds anomalies, one if a boulder contains a large artifact)
(or the anomaly power utilizer whose sound differs whether you're inserting a battery or ejecting it)

**Comment by jknpj** [comment]
> @jknpj don't those only let you pick one sound?

No.

**Comment by DeityLink** [comment]
@jknpj read the rest of my comment. playtoolsound picks a random sound, that's not what I want here.

**Comment by jknpj** [comment]
But you're still not using multiple sounds in all tools, right?

**Comment by DeityLink** [comment]
Fine I've made the change for the digsite locator and the alden saraspova counter, the only ones that use only one sound.

Also I've fixed large artifacts not making any sound/visual message when you hit them with an item.

**Review by jknpj — APPROVED** [review]

**Pull request merged**
