### PR TITLE
VACCINES CAUSE AUTISM

### PR DESCRIPTION
**Pull request by Iamgoofball**
# see title

# USER WAS BANNED FOR THIS PR

### CODE REVIEW

**Comment by clusterfack** [comment]
Fuck off Jenny Mccarthy

**Comment by PJB3005** [comment]
Damnit I was really tempted to get the close valids myself but decided not to in case anybody wanted to meme.

**Comment by Iamgoofball** [comment]
^

**Comment by carshalash** [comment]
Hi Jim Carrey

**Comment by RoyalSev** [comment]
Healthy Spessman goes to Medbay, gets pumped with massive shot of many vaccines, doesn't feel good and changes - AUTISM. Many such cases!

**Comment by SysadminJeroen** [comment]
The joke is on all of you, many if not all spessmen already have autism.

**Comment by SonixApache** [comment]
needs [honk] tag

**Comment by SysadminJeroen** [comment]
Virologist antag vaccine that causes autism when?
```diff
diff --git a/code/modules/reagents/Chemistry-Reagents.dm b/code/modules/reagents/Chemistry-Reagents.dm
index 8cc68a2d7f..2bab492945 100644
--- a/code/modules/reagents/Chemistry-Reagents.dm
+++ b/code/modules/reagents/Chemistry-Reagents.dm
@@ -357,7 +357,7 @@
 				if(D.type == self.data)
 					D.cure()
 		if(prob(1))
-			M.adjustBrainLoss(100)
+			M.contract_disease(new /datum/disease/robotic_transformation/mommi)
 
 		M.resistances += self.data
 

```

**Comment by Intigracy** [comment]
Nothing wrong with this PR tbh.

**Comment by kol1th** [comment]
Free goofball

**Comment by gbasood** [comment]
@kol1th stop shitposting in the thread

**Comment by SysadminJeroen** [comment]
Free goofball

**Comment by kol1th** [comment]
@gbasood Free goofball

**Comment by PJB3005** [comment]
Never.

**Pull request closed without merging**
