### PR TITLE
Auto-clothing items

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
* adds the autoclother, an item that applies any clothing item stored inside it to anyone who passes through, emagging it will cause items to be stripped and swapped out if possible, and allow items to be inserted into storage. available from cargo under the automation machines supply pack.
* adds a version that builds the insides from outfit datums, including a prisoner one, found in the alcatraz security crates for traders.
* makes both of these inherit the wrapping machine, with a common path for each thing refactored into it all.

## Why it's good
QoL for medbay and permabrig.

## Changelog
:cl:
 * rscadd: Players can now purchase auto clothing devices from cargo and a prisoner variant from traders. Any items inserted into the former will be applied to the person passing through, where as prisoner ones cannot have items applied to them and regenerate their items with each use.
 * tweak: Auto processing items like the wrapping machine now have a smoother in/out animation.

### CODE REVIEW

**Comment by pedr69** [comment]
does it work with cursed/glued items?
and by work i mean does it do 50 brute damage and turn you into a skeleton

**Comment by Eneocho** [comment]
For the love of god please stop giving so much content to traders, they're almost never around. This would be great as an expensive cargo crate/RnD machine.

**Comment by SECBATON-GRIFFON** [comment]
> For the love of god please stop giving so much content to traders, they're almost never around. This would be great as an expensive cargo crate/RnD machine.

main autoclother is now cargo

**Comment by Hinaichigo** [comment]
On the other hand having more 'exotic' content that the station cannot manufacture isn't necessarily bad. And this seems fairly exotic. Makes going to the traders or spessmart interesting.

**Comment by Eneocho** [comment]
My main issue with traders isn't the massive content dedicated to a role that barely sees play. It's the fact that you CANNOT IN ANY WAY SHAPE OR FORM get the goodies if a trader isn't there. You can't do shit. Want to mess with bees and would like one of the fancy beehives? Shit outta luck, there was no trader this shift.
Spessmart is not much better (even though I love me some spessmart), since you've no way of knowing spessmart is there unless you explore a fuckton or do some metafaggy ghost teleport command to check before being revived.

**Review by ShiftyRail — APPROVED** [review]

**Comment by Eneocho** [comment]
Just noticed that this adds the prisoner autoclother to the Alcatraz crates but does not change the spawn mechanics for said crates. You can buy 4 crates, each pulling 6 items from the global list. This means all 24 items are eventually sold, if you buy all the crates. This adds one more item, meaning one random sec item will NOT be sold per shift. @SECBATON-GRIFFON

**Comment by west3436** [comment]
This broke the hell out of the wrapping machine. Did you test the impacts to the other machines you turned into autoprocessors or just the clothing machine?

**Pull request merged**
