### PR TITLE
Metaclub Fixes (no tacos)

### PR DESCRIPTION
**Pull request by Probe1**
### Fixes

**Fixes** SME chamber floors with 101 kPa nitrogen floors like I did for Box.
### Tweaks

**Redesign** on genetics to both make it much more open with less Rwalls and give them quick access to cloning to promote an overall feeling of being part of medbay.  https://github.com/d3athrow/vgstation13/pull/9222#issuecomment-205038869 https://github.com/d3athrow/vgstation13/pull/9222#issuecomment-205046563
**Replaces** the dirty plating in the permabrig with regular floor plus dirt on top in the same locations. https://github.com/d3athrow/vgstation13/pull/9222#issuecomment-205046613
**Replaces** the toilet at the research outpost with a washing machine.  Toilets are for assistants and rp.  Washing machines are for getting the workplace plasma out of your clothing before it kills you.
**Tweaks** the speaker in the cloner to be broadcasting and on medical frequency so the freshly cloned and dying that cannot stumble out can get in touch with doctors and give feedback on their state of care.
**Moves** the Engineering APC in the north part of engineering next to the SMES so it's neatly hooked up to the engineering grid.
**Moves** the donk pockets in the permabrig to be on top of the microwave (fuck convicts they can live like savages). https://github.com/d3athrow/vgstation13/pull/9222#issuecomment-205046613
**Removes** a trio of speakers in the Aft hallway that were all within 10 tiles of each other as well as a 2nd one inside cloning.
### Additions

**Adds** another potted plant in permabrig where the donk pocket corner was to fill in the space. https://github.com/d3athrow/vgstation13/pull/9222#issuecomment-205046613
**Adds** a plastic crate to medbay adjacent to the blood bag tile.  Stuffs the empty bloodbags and phalanx in it.  Autistically varedits all the blood bags to have different pixel offsets which may or may not even work right but if it does then A, B, and O blood will be sorted into the corners of the tables.  https://github.com/d3athrow/vgstation13/pull/9222#issuecomment-205046751
**Adds** A NEWSCASTER DIRECTLY INSIDE THE AI CORE FOR YOUR READING PLEASURE. The feature request asked for a lot more but I think it's just throwing duplicate machines at the problem that the Bridge already addresses. 
**Adds** a Merch console to Cargo Lobby.
**Adds** a service desk for genetics, complete with paper bin.
**Adds** a button to exit the cloning room for those naked souls who are trapped inside based on thread feedback.

Addresses https://github.com/d3athrow/vgstation13/issues/8638
Closes https://github.com/d3athrow/vgstation13/issues/8991
Closes https://github.com/d3athrow/vgstation13/issues/8500
Closes https://github.com/d3athrow/vgstation13/issues/7006
Closes https://github.com/d3athrow/vgstation13/issues/7374 
Fixes https://github.com/d3athrow/vgstation13/issues/8768
Fixes https://github.com/d3athrow/vgstation13/issues/2384

### CODE REVIEW

**Comment by Probe1** [comment]
old genetics
image

nu-genetics

image

**Comment by 9600bauds** [comment]
> Autistically varedits all the blood bags to have different pixel offsets 

Thank you

**Comment by Probe1** [comment]
don't get too excited it sometimes doesn't work right for no fuckin reason

**Comment by 9600bauds** [comment]
I also appreciate how the windows from maint to genetics are behind the machinery

**Comment by ihadtoregisterforthis** [comment]
Why were there so many intercoms?

**Comment by Probe1** [comment]
@9600bauds It was a happy coincidence that I could use.

@ihadtoregisterforthis I don't get it, did I screw something up?  Unless I made a mistake, I maintained the same amount. I moved the one inside genetics and cloning to allow for windows.

**Comment by Probe1** [comment]
Genetics

image

image

image

image

**Comment by Probe1** [comment]
Perma 

image

**Comment by Probe1** [comment]
Medbay

dreamseeker_2016-04-03_16-01-37

**Comment by ihadtoregisterforthis** [comment]
Well you removed one but they are very redundant.
Five of them on two rooms, and all clumped

**Comment by 9600bauds** [comment]
This is a fantastic change to Genetics and I love it

**Comment by Probe1** [comment]
I should probably remove the rtable I don't know how that got there or why it has plating under it.  I'll prune some speakers after checking other maps to see if it's inconsistent.

**Comment by 9600bauds** [comment]
~~Since you're already there, a paperbin in Genetics would be useful due to the nature of the job~~
My mistake, there's a folder

**Comment by Probe1** [comment]
If you say so I don't know nothin bout genetics.

@ihadtoregisterforthis here's Box.  Nearly every room minus surgery and the cloner room has a speaker.  I think it's for the AIs benefit more than the players so it can snoop but..

Anyway that reminds me to add a speaker to cloning on Box because standing there butt naked is no fun.

image

**Comment by 9600bauds** [comment]
I just noticed how hilarious it is that the ONLY rooms without an intercom are the cloner and surgery, e.g. the only two rooms where someone could get trapped inside without a headset and thus actually need an intercom :^)

**Comment by Probe1** [comment]
Proof of intelligent design

Atheists 0
Boxbabies 1

**Comment by ihadtoregisterforthis** [comment]
Yes, it's not a complaint, it's an observation.

**Comment by Probe1** [comment]
Oh well too bad I removed some excess this is totally not needed why speakers anyway

**Comment by Probe1** [comment]
Replaces the toilet at the Research Outpost with a washing machine.  Thread request

**Comment by Probe1** [comment]
Finished, tested each change, ready to merge.

**Pull request merged**
