### PR TITLE
External airlocks now spawn with their timers lowered

### LINKED ISSUE #5790: External airlocks should start with their timers lowered
Because it makes sense

### PR DESCRIPTION
**Pull request by Zth--**
# BECAUSE IT MAKES SENSE

Fixes #5790

### CODE REVIEW

**Comment by PJB3005** [comment]
:+1:

**Comment by dylanstrategie** [comment]
I would prefer just adding cycling airlocks. If this makes airlocks close instantly it'll just make them more annoying to work with

**Comment by PJB3005** [comment]
@dylanstrategie I would too but the players...

**Comment by Zth--** [comment]
The timing fits pretty well. Also there's no chance this way is more annoying that cycling airlocks.

**Comment by Probe1** [comment]
edit your changelog to describe what your PR does since I still have no idea what timer you're referring to

**Comment by Zth--** [comment]
Everybody should know what a timer is... anyways, changed.

**Comment by DeityLink** [comment]
It does make sense. Entering the shuttle is going to become a pain though.

**Pull request merged**
