### PR TITLE
Allows normal traitors to go loud for 7 extra TC

### PR DESCRIPTION
**Pull request by ghost**
[content][tested]
Should result in 27 TC at the maximum, just one short of any co-operative bundle. Based on an ancient pre-dynamic mode  system where traitors would get 8 extra if they showed up on the post-roundstart command report. (Reduced by 1 due to said bundles)

:cl:
 * rscadd: Syndicate traitors can now purchase a one-time assault package from their uplink, which provides them with seven extra telecrystals in spite of the communications being used to send them exposing operations to NT affiliated interceptors, effectively destroying their cover. Is not available to nuclear operatives or challengers.

### CODE REVIEW

**Comment by WindowsErrors** [comment]
can you tell us about the message that gets sent

is it gonna get bundled into the round start threat report that nobody reads? is it gonna be a critical priority message that gets forwarded to the security requests console with all the orange flashing lights and stuff? is it gonna be the station wide centcom update that blends in with the admin's 20 other update papers covering the comms console?

**Comment by DorainGrey** [comment]
Good idea but can't support it as currently implemented.

There's nothing stopping a traitor going silent, until they are discovered and then using this to get a free extra 7tc. Any murderboner, who gets called out on comms will just buy this bundle directly after.

There needs to be some sort of time limitation on purchasing this, to force traitors to choose. Something like it can only be brought before the first wage payment? Or 10 minutes after joining. Otherwise it's just free TC.

**Comment by NiftyRyanyan** [comment]
Bad idea, this is only going to empower the low pop silent shufflers. With the extra tc and everyone already knowing they are a traitor this is only ever going to result in murderboning.

**Comment by Servalfang** [comment]
nobody cares about your lowpip nigga people dont even play during it. even if it did matter, wah, i got silent shuffled and now the guy who did it is banned 5ever.

**Comment by WindowsErrors** [comment]
yea the time limit thing is a good idea

on bee they had the nuke ops leader spawn with the war declaration remote in their hands and they could openly declare war on the station in exchange for 75 extra TC in the uplink, but the thing was that it could only be done in the first 5 minutes of the round and the nuke ops shuttle could not come to the station for the next 20 minutes

I think it ended up getting removed or something because all the ops would end up brawling each other to get the war declaration remote from the leader to get the free TC before the 5 minutes ran out

**Comment by tuypo1** [comment]
This does put it as a centcom message everybody hears rather than in the communications report right? because those don't get read that often

maybe have it so you get the 7 for exposing yourself in a big flashy message and 2 for having it in the roundstart report

**Comment by ConfusedCactus** [comment]
I agree with other posters that adding a time limit is necessary for this idea to have legs. As long as it comes through as a centcomm announcement and must be done in the first ~15 minutes of a round, I actually think this isn't the worst idea and would like to see it in action.

**Comment by nervere** [comment]
This feels like a feature better suited to TTT than a roleplaying game.

**Comment by xeroxemnas** [comment]
oh boy more reasons to lowpop murderbone

**Comment by ghost** [comment]
Will revisit with a way that encourages less lowpop use

**Comment by WindowsErrors** [comment]
the time limit idea is a good start though

**Comment by Servalfang** [comment]
can you share with me the going loud files with me directly? I have a nuke-related idea.

**Pull request closed without merging**
