### PR TITLE
Revert "Sound added to airlock maintenance panel opening/closing."

### PR DESCRIPTION
**Pull request by Shadowmech88**
Last I checked, we had a rule against merging one's own PR.

### CODE REVIEW

**Comment by ghost** [comment]
Ten Jokes That Went Way Too Far

**Comment by DrSnips** [comment]
I don't really care if you revert it. Just add some kind of feedback to the person when you screwdriver the door since that was my intent with the sound before people lost their minds over balance.

I would like to know why people are against the sound though.

**Comment by ShiftyRail** [comment]
Thing is ShadowMech cannot merge it himself because that would be against the "rules".
>I would like to know why people are against the sound though.

I think they explained their reasons pretty well in the original PR

**Comment by Exxion** [comment]
There is no rule against self-merging. It's just frowned upon.

**Comment by Exxion** [comment]
Wait who gave that loser collab?

**Comment by Shadowmech88** [comment]
N3X15, I believe.

**Comment by Shadowmech88** [comment]
image
This is all it took.

**Comment by Exxion** [comment]
Nobody with org admin access is currently online, sadly, but I'll make sure this issue is resolved soon

Jesus fuck we have a *brain damage* line based on him
He's lucky he isn't repobanned

**Comment by DrSnips** [comment]
As they say ask and you shall receive.

**Comment by Shadowmech88** [comment]
I still think the PR should be reverted. I believe allowing it to remain would set a bad precedent as far as the acceptability of self-merging.
I actually don't have a problem with the content, but I think resubmitting the PR and having it merged in the proper way would be appreciated by the community.

**Comment by Exxion** [comment]
Yeah, if it had been demonstrated that people actually liked it, I'd disagree
But that is far from the case

**Comment by ultraplen** [comment]
unslipped

**Pull request merged**
