### PR TITLE
Batch of fixes and tweaks to the map

### PR DESCRIPTION
**Pull request by ghost**
- Remove random rwall poking out of Virology External
- Cut up areas a little to fix some weird area placement, include external vents in space to their corresponding areas
- Add a few plants around
- Make all of Security External into rwalls. Secure area means secure
- Increase size of window bay in the Firing Range
- Rework Supermatter Meteor Shield to be two tiles more distant and far more complex (including rwall corners and warning sighs)
- <s>Attempt to minimize ZAS fuckery when the Supermatter chamber is first opened by using a non-ZAS simulated airlock</s>
- Add another entrance to the Bar, leading west in front of the eastern Bridge Entrance, move a few items
- Add a desk lamp to one of the Bar tables to reduce size of "darkness spot", might be slightly out of place but should do
- Change Security Maintenance Atmos Room to run on air tanks instead of an air canister. Yes, this makes Security atmos sabotage harder, but seriously just hooking up a canister to a private maint maintenance room to make the most secure area on station a death zone might be a bit too easy
- Add one light and a firefighting closet to Bridge Maintenance
- Change Radio Room to have vacuum floors. You should take maximal precaution when entering it anyways
- Fill Engineering Storage more. There is now 8 shield gens and 4 meteor shields inside
- Give the Botanists a ChemMaster to make direct use of the reagents they obtain with their grinder. This will allow them to unlock the full potential of "chem crops" without a need to constantly get pissy with the Chemist

Those are mostly small things I wanted to fix here and there. Not very atomic, but this shouldn't act as a massive overall gameplay change

### CODE REVIEW

**Comment by Probe1** [comment]
Checked it out and it all looks good.  Engineering secure storage is packed now and players might have to do a little tetris to get what they want out in rare occasions but its a welcome change.  The chemmaster fits in and doesn't clog botany any more than it is.  Finally the SME chamber doesn't suck all the contents of the room towards the chamber when opened.  

Looks good from what I can see!

**Comment by d3athrow** [comment]
>Attempt to minimize ZAS fuckery when the Supermatter chamber is first opened by using a non-ZAS simulated airlock

What do you mean by this.

**Comment by Probe1** [comment]
I can't speak for him but the SME chamber has a nasty habit of sucking everything in the SME room into it when it is opened for the first time.  It's a minor but annoying problem.

**Comment by ComicIronic** [comment]
>unsimulated airlock

Absolutely no. Fill it with nitrogen or add a double airlock, but do not at any point break realism with a silly mechanic.

**Comment by dylanstrategie** [comment]
d3athrow, ComicIronic, by that I mean an airlock like the ones on the shuttles. They don't transfer air to avoid air fuckery. I know it's not realistic, but there just isn't place for a proper cycling chamber and the "sucking things into the chamber" part is extremely nasty

**Comment by ComicIronic** [comment]
Space for an airlock.
Seems to me that there's plenty of space.
It doesn't even have to be a cycling chamber. A double airlock is better than hacky solutions.

**Comment by dylanstrategie** [comment]
To be really honest, this'd be a massive problem, I'd have to delete two radiation collectors to make a cycling chamber, add in cycling apparatus to depressurize and repressurize the chamber correctly, move the pressure meter to be readable by humans and do all of that without filling the engine with crap

There's a reason why the Engine external airlocks are also ZAS unsimulated, even though there's a double set of them and there's NO Singularity machinery at this level

**Comment by dylanstrategie** [comment]
Also a double airlock IS a hacky solution. It would look awful and would be a pain in the ass to work with when pulling a shard you can't push or generally play Tetris with

**Comment by ComicIronic** [comment]
The reason the engine external airlocks are unsimulated are because there was a good period (and it might still be) of the Singularity EMPing them open and all the air rushing out. This is a different situation. A double airlock would be imperfect, but it wouldn't be unrealistic.

Also
>i'd have to remove two rad collectors

Boohoo, there's like 15 of them.
The engine can stand to lose a little power output for the sake of not having this level of ridiculousness in map design.

**Comment by Probe1** [comment]
this 'ridiculous' map design already exists in like half a dozen areas.  two at the mining outpost, two in engineering at the singlo, aaand I know there's one or two more but I can't think of them.

**Comment by AutismSpider** [comment]
Loss of two rad collectors is fine if it stop shit form flying in and out of the room that or add some fucking gas too it at round start.

**Comment by Probe1** [comment]
the alternative really is to just add 101.5 kPa of 80/20 and call it a day.  I mean we're going to filter the gas in the chamber at some point anyways.  Why not have the round start with normal gas mix in the chamber?

**Comment by dylanstrategie** [comment]
I'll just revert this change in particular. All the other fixes are more important to me, I simply did it as a last-minute quality of life thing

Ideally someone would rework the Supermatter Engine as a whole at some point, I might

**Pull request merged**
