### PR TITLE
Revert Biogenerator Biomolecules

### PR DESCRIPTION
**Pull request by gurfan**
Reverts vgstation-coders/vgstation13#34089 
Reverts #33985 

The plant biomolecules/biogenerator materials system had been added to the game under the pretence of there being a large follow-up update to the biogenerator. It has been 4 months since the materials system PR and there have not been any updates to the biogenerator. Currently the materials make using the biogenerator more tedious, annoying and slow than before, which is ironic considering the recent botany updates have made botany much faster.

### CODE REVIEW

**Comment by adacovsk** [comment]
This might have also messed up the chemicals outlined in a recent issue report

**Comment by Eneocho** [comment]
I was hoping for that biomolecules rework as well, sad that it never came to be.

**Comment by pedr69** [comment]
stock parts but instead of RND they're made of flesh when?

**Comment by Eneocho** [comment]
> stock parts but instead of RND they're made of flesh when?

That was actually an idea I had suggested at some point.

**Comment by Kurfursten** [comment]
I considered doing this one myself. It's not particularly hard to get the right biomolecules, but it is annoying especially since the biogenerator isn't used that much. The buff biogenerator needs is the suggestion I made like 6 years ago, move it to the front desk so that the public can use it (like the mechanics general fab)

**Pull request merged**
