### PR TITLE
mecha fixes

### PR DESCRIPTION
**Pull request by PaulRitter**
[tweak]
every now and then i would come across it and get mad so im fixing it now.

### CODE REVIEW

**Comment by PaulRitter** [comment]
also added a missing undef statement

**Comment by Exxion** [comment]
Terrible
Fuck `initial()`
More things should use the var method, not fewer

**Comment by PaulRitter** [comment]
whats so bad about `initial()`? redpill me

**Comment by Exxion** [comment]
1. Prohibits doing anything to the var in question in `New()`
2. Prohibits bussing
3. Doesn't work with non-primitive vars, though this one's not an issue in this particular case

**Comment by PaulRitter** [comment]
dont merge this im gonna do it the other way around

**Comment by PaulRitter** [comment]
alright so i inverted the whole thing and also removed that dumb reset_icon proc like jesus christ what the fuck

it literally sets the icon state and then returns it where the code uses it to set the icon state again

**Pull request merged**
