### PR TITLE
Wizard's Rune Scimitar

### PR DESCRIPTION
**Pull request by GermanSanta**
Adds a rune scimitar to every wizard's base
Except Wheelstation due to it still being in development

### CODE REVIEW

**Comment by Probe1** [comment]
Not a fan to be honest.  
1.  Its a good weapon.
2.  It's a flat out reference without subtlety.

Vault was the right way to add it.  Giving it to antags is silly.

**Comment by SkowronX** [comment]
If I were you, Id focus on a new project now. (unless you do a bugfix)

**Comment by GermanSanta** [comment]
True but for a wizard that's a lone with only a computer... one that already has spells riddled with references. The rune scimitar is the most fitting of weapons.

**Comment by GermanSanta** [comment]
True but for a wizard that's alone with only a computer... one that already has spells riddled with references. The rune scimitar is the most fitting of weapons.

**Comment by Kurfursten** [comment]
Lacking support at this time

**Pull request closed without merging**
