### PR TITLE
Biogenerators can make butter.

### PR DESCRIPTION
**Pull request by Eneocho**
### What this does
Lets biogenerators make butter for 150 biomass each, about 1.8x the cost needed to make the required milk (to then turn into cream).
### Why it's good
Gives more uses to the biogenerator and encourages the chef to ask the botanist for butter, which makes butter recipes more common.
:cl:
 * rscadd: Biogenerators can make butter for 150 biomass.

### CODE REVIEW

**Comment by jwhitak** [comment]
no... NO! QUALITY OF LIFE CREEP! MY BUTTER CAULDRONS ARE OUTDATED! NOOOOO!!

**Comment by Eneocho** [comment]
They'll still be the best way to get butter when there's no botanist playing, since getting enough biomass for mass butter production with regular crops will take way more time than you could ever save by biogenerating said butter.

**Comment by poales** [comment]
you've gone too far
cheese was already too far

**Comment by jwhitak** [comment]
No, this is superior in all aspects. All you need is to pump grass to high potency (afkable), merge it with some watermelons, and finally make sure the watermelons are multiharvesting. Then you're in the mass production business. This can be used in parallel with waiting for the dispensers energies to refill. And eventually, you'll run out of salt, making the biogenerator the longest lasting option.

**Comment by Eneocho** [comment]
That implies going into xenobotany. Most chefs I've seen just plant 4 or 5 plants of what they need for recipes and call it a day and for those chefs the cauldron is still the faster option.

**Comment by jwhitak** [comment]
The point I'm trying to make is that this isn't an either-or, it's a both. I can now make a dramatically higher amount of butter since I can do both methods at once. The consequences of this for the server are yet to be known.

**Comment by Eneocho** [comment]
I saw a clownchef slip the HoS that wanted his head with a couple butter sticks once, but overall I've only seen it used for cooking and even then it's rare.

**Comment by jwhitak** [comment]
image
\>barges into bar
\>unloads entire sacks of butter on table
\>refuses to elaborate further
\>leaves

**Comment by WindowsErrors** [comment]
i got the project zomboid gf by providing a dowry of 3 sticks of butter

**Comment by Kurfursten** [comment]
Isn't this reducing the actual cooking? I mean seriously - making the cheese and butter, that's part of chefery. I do not think I am being exaggeratory when it looks like next you might decide to add soy sauce, ketchup, hot sauce, etc. to the biogenerator at inefficient rates so there's no need to grow peppers or tomatos or get sacid or soy. At a certain point it just becomes the default to not act like a chef and instead dump watermelons and press button instead of having to think about the components for each recipe. It's not about adding any one thing to the biogenerator - in fact, that's why the cheese wheels were harmless. But there will come a point of critical mass when enough shit is in the biogenerator that it will become the default way to do things.

Butter won't tip the balance, I don't think. But it's one step closer.

**Comment by Eneocho** [comment]
I don't plan on adding more foodstuff to the biogenerator. I just wanted to make the biogenerator actually useful for chef-botanist collaboration, since just meat and milk are not really that useful considering the chef can get them faster than a botanist can prepare the biogenerator.
The biogenerator in general is very disappointing to me, it has tons of potential but most of the stuff it can make has either a very niche use or is already available to the crew so there's no real reason to ask for it.
The only things I've ever printed with regularity have been paper, soap, carpets, meat and the chems (every now and then). Everything else is just there for the very rare off-chance someone asks for it.

**Comment by ExpulsionSnooper** [comment]
qolcreep

**Comment by WindowsErrors** [comment]
> The biogenerator in general is very disappointing to me, it has tons of potential but most of the stuff it can make has either a very niche use or is already available to the crew so there's no real reason to ask for it.

is it sort of like how you can print a handful of leather things with the biogenerator but you can't print actual leather sheets

**Comment by Eneocho** [comment]
Yeah, that one is a huge issue for me, but I am sure the metaclub will say no because muh balance and the deprecation of the leather system.

**Comment by Kurfursten** [comment]
Realistically there are few things made from leather that people care about making: belts, suits and whips. Anything else is already makeable at the biogenerator (e.g.: wallet/satchels) or just cosmetic (e.g.: cowboy hat/boots -- weirdly you cannot make the leather apron from either leather or biogenerator). The reason people want belts, suits, and whips is because they are stat-boosting. Leather belts are that stupid meme item that actually increases your max health and punch damage - but probably not balance-upending. Leather suits are solid stats but nothing game changing. Whips are extremely robust though, like having a short range gun that never needs to be recharged. This has traditionally been balanced by the fact that few people want to fuck with the slow, lengthy process of leather refining.

If you make leather and whips available at the biogenerator, it will definitely be a real balance concern.

**Comment by Eneocho** [comment]
To some degree leather is already available, just print 5 monkeys, kill and skin then do the whole leather tango to get your funny monkeyleather whip, though I'd really like for actual leather to be available too. Making it turbo expensive has diminishing returns and is hard to explain diegetically (leather whatever costs 300 but raw leather costs 2000? kinda immulsions breaking).
We could try to add them however, botany already has access to arguably way more dangerous weaponry than a whip (though they're balanced by mechanical know-how, you gotta know your stuff to make the powerful plants) and le funny belt has no real effect on balance.

**Comment by Kurfursten** [comment]
Yes, that's exactly what I said, leather whips are balanced by the fact that few people know how to do the process and it's a pain to do it. Anyone can order a monkey cube box from cargo without complaints. And yes, botany does have access to arguably more dangerous weaponry - but not ranged weaponry. A deathnettle can kill in one or two hits on an unarmored target, but it still requires you to get close. Meanwhile whips don't even have an inhand sprite.

**Comment by jwhitak** [comment]
Because of the last two biogenerator PRs, I'm considering doing bigger changes to the machine. More than just adding butter, I'm thinking of throughly expanding the biogenerator (and what it takes to make the things inside). Throw thoughts into #32975 if you can. The note of not wanting to print raw leather, for example.

**Comment by Eneocho** [comment]
>by the fact that few people know how to do the process

The wiki has had a guide to process skins into leather for a more than a year now and still almost nobody uses the whips. It's not really a balance threat to have leather more easily available.

**Comment by Kurfursten** [comment]
No further biogenerator recipes emerged in 3 weeks so I guess this is cool

**Comment by Eneocho** [comment]
I told you, I had no plans to add more biogen recipes, just the butter as well. Perhaps in some distant future we can rework the machine.

**Pull request merged**
