### PR TITLE
literally replaces R&D with Tetris and clearing a line gives you a random research point

### LINKED ISSUE #9848: R&D system rework suggestion
Since noone likes the menial task that is stuffing a list of items into the destructive analyzer, here is an idea that i thought up that, with the right execution, should reward active research as well as help out if noone bothers to do research with an automation feature.
Borrowing from TBS and RTS games, research is now done with a "progress bar".

Items, or "Technologies", have a categorical (Research Level) requirement that is just like the current one and a Research Point (RP) requirement. Research Points are produced by CPUs.
A new machine, called the Processor Rack (similar to server racks) will hold up to 8 CPUs. There are different qualities of CPUs, each producing a different amount of RP per second. R&D starts out with two basic CPUs. Additional CPUs can be either bought via cargo or produced by R&D themselves, with higher quality CPUs available at specific Research Levels.

Research is done by activating a technology's research, CPUs are either automatically or manually assigned, so multiple things can be researched at once or scientists can focus on getting one specific technology faster. Additionally, there's an Auto-Mode which automatically starts research on the next new tech whose requirements are met.

Once research of a technology is completed, it can be produced instantly. Specific Technology Level points are also rewarded depending on the nature of the item. These TechPoints increase the Research Level (eg. Power). The Destructive Analyzer will function similar, but instead of directly upgrading the Research Level, it instead rewards a small amount of techpoints that could potentially upgrade Research Levels, as well as reduce the necessary RP to research the analyzed item by 90%, has it not been researched yet.

image

### PR DESCRIPTION
**Pull request by ghost**
pomfs boipussi
bomf

www.youtube.com/watch?v=4nDBCQWMQww

the tetris minigame is stolen from some 2004 website because I didn't want to port tetris to BYOND
it's in javascript so it's totally clientside, no input lag and anyone can hack it easily

fixes #9848

TODO:
this gives you ALL research including illegal and anomaly (feature?)
totally remove R&D right now i just deleted the roundstart destructive analyzer

:cl:
 * tweak: replaced R&D with Tetris and clearing a line gives you a random research point

### CODE REVIEW

**Comment by Chazach** [comment]
the pr that saved science

**Comment by Orangerush** [comment]
based

**Comment by jknpj** [comment]
the hero we need but don't deserve

**Comment by jknpj** [comment]
wait, is this only box?

**Comment by aceedex** [comment]
Wouldnt mind this going through at all. just need to keep current research available as well just in case we dont have a tetris grand master in RnD that day

**Comment by MusgardTiger** [comment]
Infinitely more engaging than our current system. (which says somethin tbh)

**Comment by DamianX** [comment]
image

**Comment by Durgen** [comment]
RnD values on items should be be given a random modifier each round

perhaps +1, +0, or -1 for each research category on each item

**Comment by aceedex** [comment]
real collab hours

**Comment by Durgen** [comment]
wait holy fuck this was merged lmao

**Comment by barbedwireqtip** [comment]
you suck at tetris lol

**Comment by Auris456852** [comment]
That's nice, I guess.
Now give us hold pieces, please.

**Comment by GriffinMan4455** [comment]
Motherfucker, if you do this I will be the GOD of science. I did nothing but play tetris in BOTH of my gov classes last year. BET.

**Comment by Ausops** [comment]
based tetris coder

**Comment by Screemonster** [comment]
Replace virology with Dr Mario

**Comment by Sharkmare** [comment]
https://github.com/jakesgordon/javascript-tetris

**Comment by ghost** [comment]
I think I actually tried that specific one. BYOND can't into HTML5, so I had to get an obscenely old Tetris clone.

**Comment by Shadowflame909** [comment]
Other servers need to steal this. T. guy who plays on other servers

**Comment by stylemistake** [comment]
You should keep scoring rules (ratios) as close to the classic NES version as possible.

1 line -> 40 * level
2 lines -> 100 * level
3 lines -> 300 * level
4 lines -> 1200 * level

Adjust research rate to e.g. 1 RP per 1000, and you're golden. World championship tier tetris, for science.

**Comment by stormcloud23** [comment]
bring it back

**Comment by aceedex** [comment]
Bring it back

**Pull request merged**
