### PR TITLE
[DO NOT MERGE NOT EVEN AT GUNPOINT] Processing subsystem

### PR DESCRIPTION
**Pull request by DamianX**
# DO NOT MERGE

Stolen from TG

Replaces the existing `processing_objects` with a number of subsystems: SSprocessing for datums, SSobj for obj/atoms, SSfastprocessing for SANIC

Replaces all the special `/proc/process()` definitions with a single `/datum/proc/process()` definition

Replaces addition and removal from the long gone `processing_objects` with helper macros.
Doing this I noticed that most objects remove themselves from the processing list in an overridden `Destroy()` BUT `/obj/Destroy()` already handles that. Should we remove one of those calls? If so, which?

# broken as fuck

Pipes don't work at all and I suspect other /datum/s don't work either. I need to see how the process() for those expects to be called and add it to a SS.

This is in preparation for further work.

# DO NOT MERGE

### CODE REVIEW

**Comment by PJB3005** [comment]
Brace yourselves.

The TG preprocessor macros are coming.

**Comment by Hugh-G-Rection** [comment]
My body is ready

**Comment by Shadowmech88** [comment]
What are the potential benefits of this?

**Comment by DamianX** [comment]
I looked at our wall smoothing code and skipped a heart beat. I decided to port TG's icon smoothing subsystem. We'll have a system that uses BYOND's mutable_appearance and queues to manage icon updates, that should help with performance for things like explosions and others. Such subsystems are children of this processing subsystem.

**Comment by Exxion** [comment]
Smoothwall code has negligible performance impact anyway, but reducing appearance churn can't hurt

**Comment by Shadowmech88** [comment]
RIP?

**Pull request closed without merging**
