### PR TITLE
Adds frogs

### PR DESCRIPTION
**Pull request by BomberBro**
Adds frogs to the game, one of which can be found inside every insect control crate. Frogs eat bugs, just like lizards, and you can hold them in-hand or wear them on your head. They're animated and jump when moving.
frogbase
froghead2

:cl:
 * rscadd: Adds frogs, contact your local cargo department for an insect control crate to get one.

### CODE REVIEW

**Comment by BomberBro** [comment]
I'm dumb and forgot to check out a new branch so those four first commits are from another PR, but that doesn't affect anything beyond beyond cluttering the log.

**Comment by SkowronX** [comment]
needs a ribbit sound to play

**Comment by ThatRedPyro** [comment]
Frenchmen? In _my_ spess?
It's more likely than you think.

**Comment by SageOfLight** [comment]
I'll take a dozen.

**Comment by TGFH** [comment]
I r8 this PR C&A/10.

**Comment by ShiftyRail** [comment]
our evil plan for station domination comes to fruition

**Pull request merged**
