### PR TITLE
Remove taxi and taxi accessories

### PR DESCRIPTION
**Pull request by DamianX**
The only remnant is a broken taxi call button on roidstation Z4

### CODE REVIEW

**Comment by SonixApache** [comment]
that and taxi's squidroid, which remains on roidstation

**Comment by Kurfursten** [comment]
Delete bus station too

Edit: Nevermind, it looks like you already did. I've not been watching github closely lately.

**Comment by DrSnips** [comment]
Will old maps be stored somewhere? Id like to have them around than not. It could be helpful for station skeletons in the future.

**Comment by DamianX** [comment]
they will forever live in your fork

**Comment by Durgen** [comment]
rip
taxi > meta

**Pull request merged**
