### PR TITLE
Xenoarch digsite scanner tweaks

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[tweak]

## What this does
 * moves the advanced one's extra description stuff to all of them since the color stuff applies to them all nowadays.
 * updates the item descriptions to match this and also describe what the advanced one does better. 
image
 * adds any finds hidden behind the main one as a smaller overlay with a luminosity inverted outline to distinguish it, half in size for the 2nd in a pair of two, and 2/3rds and 1/3rd in size for the respective last two in a pair of three. (dunno if i should lock this behind the advanced one at all)

## Why it's good
more visual cue that there's more than one find

## Changelog
:cl:
 * rscadd: Xenoarchaeology digsite locators now show all small finds on a mine turf.
 * tweak: Xenoarchaeology digsite locators no longer need to be advanced to show the color keys on examination.
 * tweak: The descriptions of both basic and advanced xenoarchaeology digsite locators have been updated to match their current usages.

### CODE REVIEW

**Comment by kernikov** [comment]
Can you label what's what in the image, it hurts my eyes and doesn't look too clear.
Not that I'm against it.

**Comment by SECBATON-GRIFFON** [comment]
> Can you label what's what in the image, it hurts my eyes and doesn't look too clear. Not that I'm against it.

the outlined lighter colored stuff over the ore is the highlighted finds

**Comment by pedr69** [comment]
>what's in this image

have you never played xenoarch?
it's extremely obvious

**Comment by Killette2** [comment]
Is this only for small finds? I am a bit rusty on what xenoarch has to find larges besides triangulation

**Comment by pedr69** [comment]
that's a good question, are the cult symbols for large artifacts downscaled 4 times into ~1 pixel?

**Comment by SECBATON-GRIFFON** [comment]
> Is this only for small finds? I am a bit rusty on what xenoarch has to find larges besides triangulation

only for small finds yeah

**Comment by kacurasuo** [comment]
what does it look like when there's a large? does it still overlay the smaller finds from on top of the large over it? (advanced finder ofc)

**Comment by SECBATON-GRIFFON** [comment]
> what does it look like when there's a large? does it still overlay the smaller finds from on top of the large over it? (advanced finder ofc)

that's unchanged so yeah

**Pull request merged**
