### PR TITLE
Warden uplink item: Remote explosive implants

### PR DESCRIPTION
**Pull request by ghost**
[content]

Superficially looks like a chemical implant until examined more, 18 TC for normal traitors, 12 TC discount for wardens and HoS. Spawns in a box with 5 like the one in the armory.
Does not use heard codephrases at all, instead must be activated from a prisoner management console.
Creates a smaller explosion than normal implants, but still breaches, comparable to syndicate cuffs.

:cl:
 * rscadd: Traitors with access to prisoner management consoles can now purchase a form of explosive implants that activate remotely

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
For the cost you should get way more than one.

**Comment by Eneocho** [comment]
Sounds like a normal e-implant with extra steps. Just implant the guy with the normal e-implant bomb and say the funny gamer word when you want him to explode.
Also, you can already chem-bomb implant your target. Just chemimplant with 50u water on one and 50u potassium on another. 
Either buff them so they're worth the cost or give more.

**Comment by juanototo2** [comment]
REMOVE THE FUCKING SECURITY LOCK YOU LOW GRADE IMBECILE.
IT'S A TRAITOR ITEM, YOU SHOULD NOT NEED TO HAVE EXTRA ACCESS TO USE IT.
THERE IS ALREADY A FUCKING COST -- TELECRYSTALS.
ARGHHHHHHHHHHHH.

**Comment by west3436** [comment]
> REMOVE THE FUCKING SECURITY LOCK YOU LOW GRADE IMBECILE.
> IT'S A TRAITOR ITEM, YOU SHOULD NOT NEED TO HAVE EXTRA ACCESS TO USE IT.
> THERE IS ALREADY A FUCKING COST -- TELECRYSTALS.
> ARGHHHHHHHHHHHH.

this or just make it a lockbox that can be opened by any access simply to appear like a chem implant

**Comment by ghost** [comment]
> this or just make it a lockbox that can be opened by any access simply to appear like a chem implant

Was just a placeholder until I figured out how to make it all access, should be fixed now

**Comment by calzilla1** [comment]
Imagine having to ask sec to open the box to your tator tools

**Comment by Eneocho** [comment]
> 
> 
> Imagine having to ask sec to open the box to your tator tools

It's not that good a tool, to be honest. You need access to the prisoner management console, meaning its hard limited to (((sec players))).

**Comment by ShiftyRail** [comment]
I am not merging this if you remove the security lock.

**Comment by Eneocho** [comment]
> 
> 
> I am not merging this if you remove the security lock.

Are you seriously vouching for having access locks on antag items?

**Comment by ShiftyRail** [comment]
(that's a joke)

**Pull request merged**
