### PR TITLE
MetaClub bar tweaks

### PR DESCRIPTION
**Pull request by brndd**
[meta]

Powercreep etc.

This is basically #22449 but for Meta. Meta already had the still in the back room and a wrench; Meta mappers clearly know what's up. It also has an... ice cream machine? Meta mappers *clearly know what's up*. Now it has booze, soda and coffee machines too.

The shutters button also had the wrong access, being positioned in the bar but requiring kitchen access. I changed that while I was in there.

After: 

Before:

:cl:
 * rscadd: MetaStation bar now has booze, soda and coffee dispensers.
 * bugfix: MetaStation bar shutters button now requires bar access instead of kitchen access.

### CODE REVIEW

**Comment by Exxion** [comment]
Probably should update the screenshot since you removed the extra coffee machine

**Comment by beesil** [comment]
Small request, could you add a tile painter in the backroom?

**Comment by brndd** [comment]
Done and done

**Comment by Exxion** [comment]
Can you reach the coffee machine?

**Comment by brndd** [comment]
yes

**Pull request merged**
