### PR TITLE
Mechanics tweaks - Box Station

### PR DESCRIPTION
**Pull request by eplgr**
_PSA: if you see any non functional work-environment in your department and you want it changed, you can post here or ping me at discord. I'll analyze it and try to improve it if it's needed._

# Github changelog
**Box station:**
- Mechanics: replaced reinforced walls that are facing maint with normal walls

# Reasons & personal thoughts
The main issue I want to adress: mechanics is too small. Whether that is a good thing or a bad thing, it leads to fun things like many mechanics wanting to expand/reform the place and its surroundings.
And then you hit a wall, literally. You realize reinforced walls are all around you. And a questions pops up in your head: WHY?
Reinforced walls are supposed to be used in _secure areas_. Mechanics is not the AI upload. It's not the brig. It's not Telecomms. Reinforced walls being used in mechanics, all it assures is mechanics being annoyed by them. They don't protect much. 
So that's why I replaced all r_walls with normal walls. To cut off the stuff that's not needed and improve mechanic's gameplay. No more wasting so much time unconstructing them or having to use thermite.

# In-game changelog
:cl:
 * tweak: Box's mechanics: replaced reinforced walls that are facing maint with normal walls

### CODE REVIEW

**Comment by Kurfursten** [comment]
It has reinforced walls for the same reason R&D does: guns can be printed there, it's a protolathe room.

@Probe1 Has probably played more mechanic than anyone on github though so we'll see what he says.

**Comment by DamianX** [comment]
I don't care about the rwalls vs walls but FUCK MECHANICS THAT BLOCK THAT MAINTENANCE ACCESS
FUCK YOU

**Comment by Probe1** [comment]
Just do the maint facing wall.  The rwalls are less to do with security and more to do with slowing the progression of explosions.

**Comment by eplgr** [comment]
@Probe1 Yeah, I thought of doing that. At the end, I decided to change all of them into normal walls because it felt more... right? The tools storage at the left has normal walls and is probably a way more dangerous place than the average mechanics room.

But yeah, maint walls work too. Gonna do that.

**Comment by PJB3005** [comment]
Discouraging shitters from blocking maintenance is good enough of a reason against this honestly.

👎

If you want mechanics to be larger, shrink tcomms so it isn't retardedly gigantic and move mechanics go the available space.

**Comment by eplgr** [comment]
Now only maint facing walls are normal walls. Also, updated the picture.

**Comment by eplgr** [comment]
@PJB3005 That's a whole another discussion. It may be a good idea, though. For the future.
For now, I still think this is a positive change.

**Comment by Probe1** [comment]
Mechanics are in a good place that helps people see them and acknowledge they exist.  Telecomms is pretty out of the way down the hall only engineers go down.  

It sounds like for that idea to work you'd have to shift a buncha stuff.

**Comment by PJB3005** [comment]
Moving tech storage down is doable I'd say.

**Comment by Probe1** [comment]
Lets say we found the space and it was all fine for the left side, and mechanics had all of tech storage to blob into.

What would go where mechanics are now?

**Comment by DamianX** [comment]
maint

**Comment by Lokiamis** [comment]
Zoo

Or move aux tool storage there and stock it with airlock controllers, high efficiency light bulbs light fixture frames and other good shit, while making the former aux tool storage into a a little store/bazaar thing like Deff has for people to mess with.

**Comment by eplgr** [comment]
Gonna come back soon with some drafts regarding my take on a mechanics expansion.

**Comment by DamianX** [comment]
While you're at it, fix #13683 for box too, I think it got closed by mistake.

**Comment by eplgr** [comment]
Well, I've been thinking, there are a couple of things that could be done.
1- Swap mechanics <--> tool storage
2- Make tcomms smaller-->move tool storage to the new space-->send mechanics to the old tool storage

1 is more than okay. 
2 means there's new space available where mechanics right now is.

I need some feedback. Can we repurpose the place where mechanics is? Would that actually be an improvement? What could go in there?

Maybe we don't really want tcomms to be smaller anyway.

**Comment by eplgr** [comment]
Gonna make a new PR with the changes.

**Pull request closed without merging**
