### PR TITLE
Fixes taxi_engineering_vault bugs

### LINKED ISSUE #13012: taxi_engineering.dmm has a singularity camera and it overrides the on station one
I will rename it and retain it as a cool easter egg.

### PR DESCRIPTION
**Pull request by Probe1**
...by renaming a camera and deleting all the air alarms/cameras.  What a bad fix but its technically yes, a fix.

Closes https://github.com/d3athrow/vgstation13/issues/13012

### CODE REVIEW

**Comment by kilozombie** [comment]
Might be better to have broken air alarm/camera sprites that don't do anything...?

**Comment by Probe1** [comment]
Tried it, didn't work real well.  It ended up sending an atmos alarm to the consoles then turning off.

**Comment by kilozombie** [comment]
Ah, that's annoying.

**Comment by ComicIronic** [comment]
It should be possible to edit the area to have no alerts.

**Comment by Probe1** [comment]
It was mapped so it could be rebuilt.  Adding no_alarm air alarms would have more severe repercussions than no_alarm apcs and adding a blanket var on the areas would equally prevent players from properly rebuilding it.  Worse, it would do so in a way that they could not figure out and would come back to us and say there's a bug in the game.

I weighed the three choices and tried the first choice of just having them in a state of disassembly and this is the one I am satisfied the most with.

**Pull request merged**
