### PR TITLE
Adds Diona meat icon and code

### PR DESCRIPTION
**Pull request by rawraxily**
Adds an icon and code for diona meat. Nothing points to it yet, but it's a start.

### CODE REVIEW

**Comment by clusterfack** [comment]
Conflicts

**Comment by rawraxily** [comment]
Which code is conflicting?

**Comment by ComicIronic** [comment]
If I had to take a guess, food.dmi from the Potent Ham PR.

**Comment by rawraxily** [comment]
Fffffffuck. I'll take a look then, I may just close this pr.

**Pull request closed without merging**
