### PR TITLE
Makes sandstone crafting faster

### LINKED ISSUE #24080: Making sand blocks is tedius
It used to be a streamlined process that turned all sand on the tile into blocks. For months this feature has suddenly stopped working. For this screenshot I used an autoclicker on sand because you have to do each block manually.

### PR DESCRIPTION
**Pull request by Shaska-**
Fixes #24080
:cl:
 * bugfix: Clicking a piece of sand now converts all the sand on the tile you're standing on to sandstone.

### CODE REVIEW

**Comment by Killette2** [comment]
While this stacks all sand you still have to make the bricks 1 at a time from a pile of handful sand.

**Comment by Shaska-** [comment]
I don't understand. 
You want to convert all the sand you're holding with a single click as well?

**Comment by Killette2** [comment]
Yes. Turning a pile of 50 sand into bricks was the tedious part of the original image. I like that the sand combines as well though, but I was originally referring how grass turns all the grass in on a tile to grass tiles when you use grass in hand.

**Comment by Shaska-** [comment]
That's exactly what this fix should do though, and what it did for me locally. 
It only turns the sand on the tile you're standing on into sandstone though, not the sand you're holding.

**Comment by Shaska-** [comment]
Just tested it on the server.
Took a piece of sand out from a stack of sand, dropped the stack of sand on the ground, then clicked on the piece of sand in my hand.
Turned all 50 pieces of sand into sandstone bricks with one click.
Should be working fine, unless I'm misunderstanding you.

**Comment by Killette2** [comment]
I'll test that out, if it works that way things should be fine then.

**Pull request merged**
