### PR TITLE
Switch Serve and Protect NT Default directives

### PR DESCRIPTION
**Pull request by ghost**
Note : As far as the code part goes, this is about as simple as it gets. What is more important is if it truly is a good idea or not
- NT Default Law 2 is now Protect
- NT Default Law 3 is now Serve
- Weed out snowflake commented Law 5 from the code

My personal reasoning for this change :
- NT Default currently acts as THE validhunter lawset by excellence, doubling as a Captain one-human law whenever needed. There's no reason to not switch to that lawset whenever available, unless the Captain is rogue (which usually only occurs if someone illegally instates himself as the Captain)
- The Captain (or failing that the highest-ranking official) can literally ask for the silicons to murder everyone but him and they have to comply. How NT would allow such a possibility is perplexing, at best
- Since the Captain cannot be a starting antagonist (at least currently), this GUARANTEES the AI only answers to non-antags. It is the only lawset that does so (outside of ridiculous "[antags] are not human" freeforms)
- The lawset generally puts ridiculously little value to human life. You'd think a lawset where a superior can have one of his department workers slain for his amusement would be considered a bit risque for a station full of psychopaths

Discussion goes below

### CODE REVIEW

**Comment by Shaska-** [comment]
Changes it from the go-to command lawset to something more akin to Asimov, while still keeping it different enough that it could be worth uploading instead of some other lawset, depending on the current situation.
:+1:

**Comment by 9600bauds** [comment]
There is nothing I dread more than being put into NT default as borg. You are no longer a do-no-harm piece of equipment, now you're the validhunter extraordinaire scout that has to prioritize asinine requests from the Captain and HoPtain.
A big part of the fun as Asimov Borg is playing dumb and being petty-crime accomplice to ensure the round flows smooth for everyone. That SE can have fun with the Cap's hand teleporter if he wants, the tater can get away with emagging a door if I wasn't law 2'd to stop him, haha no go fuck yourself HoS I'm not harming the janitor. In the end, the janitor had a pleasant round, that SE toyed around, and the round was entertaining to everyone because the tater got to actually do shit.
But in NT default, if someone breaks a window or hacks a door you HAVE to validhunt them even if they aren't even trespassing. If you suspect someone is a tater you can't just play dumb as long as they do no harm, you HAVE to make sure they don't try to tamper with you. If the HoS slightly suspects the janitor, you HAVE to hunt him down and space him. It's not just validhunting: the lawset, it's also police state: the lawset. In the end noone can do anything in my watch, the round was a snorefest because all the taters got executed 30 minutes in, and the HoS powertripped so hard he landed in the next dimension.

**Comment by Ephx1** [comment]
All fine here, works perfect with our follow-in-order rule for laws.
I'll miss it being essentially the "Who the fuck cares" lawset out of Serve being before Protect, but oh well.

**Comment by SangriaMonkey** [comment]
>this GUARANTEES the AI only answers to non-antags

Assuming there is in fact a captain at all and he is in fact not a corpse getting looted in maint.
The way I see it this lawset is still flawed and kind of shitty. Even with the swap you still have the "rank and role" stipulation which pretty much invalidates most of the crew in most situations. The AI isn't there to nanny everyone and help "important players" cover their asses. It's the station's computer system. And the fact that most if not all lawsets are geared around being a big wet electric blanket in some fashion shows a misunderstanding on someone's part.

**Comment by Shaska-** [comment]
NT Default will always be shit, no matter what we do with it.
We can at least try to make it a bit less shit though.

**Comment by clusterfack** [comment]
Whats funny is if the AI is quick it can become the kill everyone lawset as an assistant asking an AI to kill a captain is still valid under this lawset as serve > protect unless he asked to NOT be killed.

**Comment by d3athrow** [comment]
If you switch the two NT default just becomes a more boring version of Asimov, Fuck off dylan

**Comment by dylanstrategie** [comment]
Well, the alternative is what we have currently, with Captains just running up to the AI at roundstart to enable validhunter.exe

The worst thing is that it isn't even the silicons who are validhunting with their laws in this case, they are forced to follow orders from the Captain, even outright slaying people

**Comment by Probe1** [comment]
y you do this dylan.  you're a good coder but you always want to change up shit thats better left alone or at the most a discussion thread.  I like a man of action but not when it's charging head first into a pile of dumb.

**Comment by 9600bauds** [comment]
Well this kind of works as a discussion thread

**Comment by ririchiyo** [comment]
There's been a lot of discussion about AI Laws and stuff around it, #1442, #2278 .

**Comment by dylanstrategie** [comment]
The main intention of this PR was to act as kind of a more proactive discussion on NT Default by proposing a fix on recently-perceived shitty use of the lawset by the Captains, so I don't see the problem with having everyone's opinion on it before anything is done on it

It's just that usually law discussions on the thread or in OOC are borderline useless to get any tendency

**Comment by Aurx** [comment]
I'd rather see it just excised completely, it's an asimov variant that completely fails to function under law priority.

**Comment by Senaat1** [comment]
I think we should merge NT Default with the trash bin.

**Comment by nuklearcellphoneg** [comment]
REMOVE MOMMI SIGHT OF MOBS

REMOVE ALL LAW SETS

PRE MADE LAWSETS TAKE AWAY FROM THE CREATIVITY OF PLAYERS

**Comment by Uqualm** [comment]
to see the world
through the eyes of this man
must make the world
seem so hostile

**Comment by Senaat1** [comment]
shut up sarca

**Comment by dylanstrategie** [comment]
Meh

**Pull request closed without merging**
