### PR TITLE
fixes centcom stuff

### LINKED ISSUE #12024: Cyber horrors on gooncode satellite don't shut up
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0e07cd0217834583181458ec75010de45fe43077 
> 
> General description of the issue
> (Follow)  cyber horror  emits, "GHAA!@@#" 

(Follow)  cyber horror  groans, "H@!#$$P M@!$#" 

(Follow)  grey cyber horror  groans, "H@!#$$P M@!$#" 

(Follow)  vox cyber horror  groans, "KR@!!N" 

(Follow)  cyber horror  emits, "GHAA!@@#" 

(Follow)  cyber horror  emits, "GHAA!@@#" 

(Follow)  grey cyber horror  groans, "KR@!!N" 

(Follow)  grey cyber horror  groans, "K!@@##L!@@ %!@#E" 

(Follow)  cyber horror  emits, "K!@@##L!@@ %!@#E" 

> What you expected to happen
> NOT THAT
> 
> What actually happened
> THAT
> 
> Steps to reproduce if possible
> Observe on box

### LINKED ISSUE #12027: Meta supply shuttle destroys maint
#### Description of issue

When trying to the supply shuttle on Meta, you get this message:
`ADMIN LOG: WARNING: supply shuttle (/datum/shuttle/supply) attempted to destroy Port Maintenance (/area/maintenance/fpmaint2). If you want supply shuttle to be able to move freely and destroy areas, change its "destroy_everything" variable to 1.`
This is **not** the same message as (#12023), that's a different issue. If you force destroy_everything to 1, this is what happens:
destroys maint
It's too big to even fit in that hole and trying to force it results in torn walls.
#### Difference between expected and actual behavior

Meta's supply shuttle can't be moved because it breaks a wall into maint and depressurises the place.
#### Steps to reproduce

Load up maint
Send supply shuttle to station
#### Length of time in which bug has been known to occur

No ahelps or adminwarn messages about it for the entirety of yesterday, so I assume it's very recent.
#### Server revision

0e07cd0217834583181458ec75010de45fe43077
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched for: is:issue shuttle

### LINKED ISSUE #12030: Crew can't enjoy the Crew Area at CentComm because it's access-restricted
#### Description of issue

The Crew Area in the new CentComm area are access restricted to Mining. Their req_access var says 48, which is the same one using by the airlocks at the mining dock and if you take their board out, it also says Mining.
#### Difference between expected and actual behavior

Crew can't rush for the beach or bar machines or Russian revolver or whatever unless they're miners, cargo techs, HoP, or the captain.
#### Steps to reproduce

Take off admin ID
Try to open Crew Area airlocks
#### Length of time in which bug has been known to occur

Since #11974 was merged.
#### Server revision

0e07cd0217834583181458ec75010de45fe43077
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched all issues posted since #11974 was merged

### PR DESCRIPTION
**Pull request by CptWad**
fixes some shit
adds podlock buttons (still have to be an admin to use them tho) for ert stuff
fixes #12024
cyber horrors are quiet
fixes some autism with carpets
fixes some bullshit with a floorsafe

fixes #12027
fixes #12030

### CODE REVIEW

**Comment by TheFriggenSawbones** [comment]
bless you

**Comment by Shadowmech88** [comment]
Does this just make the goonesat cyber horrors in particular mute?

**Comment by coldcola** [comment]
So what's the rationale behind the poddoors to begin with?

**Comment by clusterfack** [comment]
Silent how

**Comment by SonixApache** [comment]
Does this remove the access requirements from the crew quarters (chill room)?

**Comment by CptWad** [comment]
cyber horrors are mute 
poddoors are to keep the ERT and deathsquad where they are
access requirement? You mean to the dorms area?

**Comment by CptWad** [comment]
oh I see the grassy area I made lemme fix that

**Comment by CptWad** [comment]
fixes #12027
fixes #12030
fixes a bug that will be noticeable with deff cargo shuttle

**Comment by coldcola** [comment]
>poddoors are to keep the ERT and deathsquad where they are
it also ruins end of round cheesing to get cool toys for 20 seconds of !FUN!, why?

**Comment by CptWad** [comment]
Because I dont need ERT to break into everything in centcomm and loot it. The ERT get their toys. 
Also the only "toys" are the AEGS to shoot people. theres three new explosives in the postround room that you can play with.

**Comment by coldcola** [comment]
b-but if you're putting in an ERT/Deathsquad how are you not monitoring them to make sure they don't fuck around?

explosives are not really as fun as half the shit you've filled your !FUN! room with that the average player will never see.

**Comment by Shadowmech88** [comment]
I believe ERTs are *supposed* to be able to be created without admin intervention.

**Comment by coldcola** [comment]
they are, but it is a pretty rare occurrence I believe.  I think it's an elevated code thing, not many people know that.

**Comment by CptWad** [comment]
Admins can spawn an ERT but if they need to make one they make a deathsquad instead

**Comment by coldcola** [comment]
How often are you playing wad? ERT must be called like, 80% of the time.

**Comment by CptWad** [comment]
yeah but thats by the crew

**Comment by Intigracy** [comment]
`>adds podlock buttons (still have to be an admin to use them tho) for ert stuff`

The entire problem with ERT is you can call one without admin intervention (code red) but they can't get to the station without admin intervention.

**Comment by Intigracy** [comment]
ERT basically never use the ERT shuttle because it's never accessible, they always end up using the regular shuttle.

**Comment by CptWad** [comment]
there is no podlock between the ERT and the shuttle. An admin still needs to use the shuttle but the ERT cannot leave the ERT area or enter the dress up rooms because those have podlocks

**Comment by coldcola** [comment]
So if an admin is needed to send the shuttle then my previous statement is correct, there is typically someone babysitting the ERT/Deathsquads as they need someone to send them to the station.

Wouldn't this remove the ability for the ERT to finagle their way through centcomm to get access/use the teleporter to get the the station when no admins are available?

**Comment by CptWad** [comment]
well if it helps I can just make it so anyone can move the shuttle, is that fine? I has NOTHING to do with my changes but christ ill do it if it resolves this no-admin issue.
Also a "lack of admins" cannot exist with the new mommi bot yelling at us

**Comment by coldcola** [comment]
Hmmm, but if anyone can move the shuttle won't you have crew stealing the ERT ship and heading to centcomm to fuck around?

**Comment by CptWad** [comment]
Yeah but poddoors
I think theres an ERT only access too so I can sort it out

**Comment by Intigracy** [comment]
I was talking about the shuttle in the top left, which many people have assumed to be the shuttle for the ERT.

By other shuttle I meant the one in your picture.

**Comment by CptWad** [comment]
>I was talking about the red shuttle to the left of that shuttle in your picture, which people (myself included) have assumed to be the shuttle for the ERT.

>By other shuttle I meant the one in your picture.

wat

**Comment by CptWad** [comment]
wait what I double checked what you said and **wat**
the red shuttle FOR THE DEATHSQUAD works fine I didn't fuck with it
the blue shuttle FOR THE ERT works fine too I haven't fucked with it either
shuttles in general are fucked because of the start area being in 1,1,2 now which screws with shuttle moving code

**Comment by clusterfack** [comment]
How exactly did you make them mute

**Comment by CptWad** [comment]
speak_chance = 0

**Pull request merged**
