### PR TITLE
PDA photo messaging and camera cartridge

### LINKED ISSUE #30302: [Feature Request] Photo Messaging
[featurerequest] Allow players to send photos through PDA messaging, maybe by inserting the photo into the PDA like you do with a newscaster. A massive boon for mimes that want to PDA someone without violating their oath or talking in emojis.

### PR DESCRIPTION
**Pull request by ghost**
[content]
image
image
image
image
image
image
Closes #30302
:cl:
 * rscadd: PDAs can now send photos with messages, with a photo inserted into the PDA. This also includes AIs and borgs, who can select a photo from their internal camera to send.
 * rscadd: A new cartridge with a built-in camera is available at merch computers! Includes the ability to view all photos and send one in a PDA message. No printer included, though.

### CODE REVIEW

**Comment by DeityLink** [comment]
Why is Ian hurt?

**Comment by ghost** [comment]
> Why is Ian hurt?

we may never know

**Comment by Eneocho** [comment]
Any chance this could be added to the librarian's cartridge alongside a newscaster for mobile journalism? See: #29824

**Comment by Eneocho** [comment]
> 
> 
> Why is Ian hurt?

He found Lisa with another dog.

**Pull request merged**
