### PR TITLE
Roid: Re-piped

### PR DESCRIPTION
**Pull request by kernikov**
## What this does
Re-works all problematic piping and atmos-related issues.

## Why it's good
May close this issue: #33293
Scrubbers will suck, vents will blow.
Removes loops.
Tries to match routing for both scrubber and distro where possible, runs piping into departments through central areas, tries to keep them seperate.

Corrects this "scrubber island".
image

## Progress (Areas touched)
- [x] Security / Brig
- [x] Science
- [x] Cargo
- [x] Arrivals
- [x] Engineering
- [x] Medical
- [x] Escape
- [x] Bridge
- [x] Hydroponics

## Changelog

:cl:
 * tweak: Roid Station completely re-piped.

### CODE REVIEW

**Comment by kernikov** [comment]
Roid SecurityBrig new
Brig/Security complete

**Comment by kernikov** [comment]
Roid Cargo new
Cargo/Mining complete
(possible duplicate APC in the mining lobby/minting area)

**Comment by kernikov** [comment]
Roid Science new
Science complete

**Comment by Theophrastus1** [comment]
how do you expect me to lay pipes when i dont have any hogs

**Comment by pedr69** [comment]
>cargo scrubbers weren't even on the pipenet

i am baffled

**Comment by kernikov** [comment]
image
Hydroponics backroom lightswitches moved to south wall, window added for piping.

**Comment by kernikov** [comment]
Bridge area complete, note new piping coming down next to the communications console.
Extra vents/scrubbers added to bridge, empty shop/nook had an air alarm and firelocks but no ventilation so it was added.
image

**Comment by kernikov** [comment]
Substation had an air alarm, so I added ventilation
image

**Comment by WindowsErrors** [comment]
> > cargo scrubbers weren't even on the pipenet
> 
> i am baffled

bro everybody forgets about cargo, even the plasmaflooders

**Comment by kernikov** [comment]
image

**Comment by kernikov** [comment]
image
Medical complete
The South/Main lobby front desk has it's own air alarm and venting. Didn't make sense to have the only one on the opposite wall outside Chemistry.
Access to medical atmos is available for MoMMIs and contortionists via the Public Surgery Observation area. Morgue distro and scrubber was previously provided by the Primary Hallway just to the west. 
Overall, cleaned up and bumped around.
image
Paramedics now have an emergency dump for their cryo, venting for the telepad with air alarm (it's not blocked), and supply to virology passes through. The lime green in the bottom right shows the old "double 90" that the cable and disposals did, I straightened this out when I added the piping to viro.
image
The lower virology room's scrubber and distro lines are now connected to virology, with a manual T-valve giving you the option of switching to the tank. I was initially going to have this connected to distro but I'm not 100% sure how `initalize_directions` works for T-valves, so call this emergent game design.

image
Oh, this maintenance airlock was bumped down one tile for the valve.

**Comment by kernikov** [comment]
Outside the scope of this, but still changed:
Removed these (stray floor and pipe)
image
Engineering nudged around, ~~nothing big changed.~~ See below.

**Comment by kernikov** [comment]
Escape vents moved around, another air alarm and fire alarm added to western wall, southern fire alarm centered.
Holopad and tracking beacon nudged to center.

**_Did You Know:_** The hallway just south of Escape had zero vents or scrubbers before?

image

**Comment by kernikov** [comment]
image
Arrow shows where the wall and rubble was pushed 1 tile east for piping.
Also, pipes moved around I guess. Ghetto bar makes more sense now, instead of one pipe coming through maintenance.

**Comment by pedr69** [comment]
did you test that the scrubbers work?
open a plasma can and see if any gas goes into the pipenet

**Comment by kernikov** [comment]
> 

no

**Comment by pedr69** [comment]
if it doesn't fix the scrubber net, then it doesn't really close #33293, does it?

**Comment by adacovsk** [comment]
wheres engineering

**Comment by kernikov** [comment]
> wheres engineering

No noteworthy changes, besides how it runs into the engineering bathroom.
https://github.com/vgstation-coders/vgstation13/pull/33426#issuecomment-1271293031

**Comment by kernikov** [comment]
> if it doesn't fix the scrubber net, then it doesn't really close #33293, does it?

I have re-worded it to not auto resolve the issue.
I may test this tonight, otherwise it would still be an improvement over the current situation if merged beforehand.

**Comment by adacovsk** [comment]
can you fix the distro room in engineering? the scrubber pipe goes under a wall and the pipes in that little room are not great, nor any of the distro, confusing and painful, all of them

**Comment by kernikov** [comment]
Atmospherics has been reworked.
More windows into the distro/waste valve area, Atmos Monitoring APC moved from the lockers to the actual monitoring area.
Digital valves added to all inputs from the gas miners, you can now change the gasmix piping inside atmos without flooding the place. (only oxygen and nitrogen are open during init).
image

**Comment by kernikov** [comment]
Here's the "Before" for the distro/waste valve room:
image

**Comment by kernikov** [comment]
image

**Pull request merged**
