### PR TITLE
Market Blackout

### PR DESCRIPTION
**Pull request by bathosbathtime**
This PR removes the black market as a mechanic from the game.
I don't want to put time and effort into something that the community does not want.  This PR is here to give home to discussion to the merits and downsides to outright removing the black market and to ensure that I am not wasting my time on something no one wants.
As there was a server poll to introduce the black market, I would also like a server poll be made IF this pull request gains a significant amount of positive feedback.  I would rather turn the black market into something we will be proud of, but I also want to give the community the option to choose its removal should they want to.  If only so that we can say we explored every feasible option.
This is the forth PR of four.

Compiled and lightly tested locally

:cl:
 * rscdel: Removed the black market

### CODE REVIEW

**Comment by DeityLink** [comment]
Are we replacing it with a proper player-to-player PDA-based market then as I've suggested for years?

**Comment by SonixApache** [comment]
\>this after #23698
🤔

**Comment by ghost** [comment]
The uplink has a P2P black market in my 2.0 version that's been under code review for 2 weeks.

**Comment by beesil** [comment]
@DeityLink SPACE CRAIGSLIST

**Comment by plosky1** [comment]
I hear complaints about how we're /years/ (although I don't agree) behind code-wise from other servers, then when we actually get content its reverted.

Has anyone seen any actual in-game negatives from the Black Market? I sure haven't when I've been adminning.

**Comment by ghost** [comment]
Screenshot 2019-08-15 16 46 17
This + shifty makes up the tranny metaclub, I believe

**Comment by SonixApache** [comment]
i upboated all four of the black market PRs

**Comment by beesil** [comment]
📞 He knows, take him out

**Comment by ShiftyRail** [comment]
One more day before we can merge this PR :relieved:

**Comment by FudgePucker** [comment]
We need more content and nobody actually has any real gameplay examples of why it is bad. Just shitposters and "coders" theory crafting when they haven't even logged on to play in weeks. Same deal with the emagged nikita launcher, people made it out to be the absolute worst thing possible, not made in good faith, and it actually had little to no impact, because surprise surprise, a welding torch and welding fuel tank is a cheaper meathod of blowing yourself up.

T. Shitposter who hasn't logged in to play in weeks

**Pull request closed without merging**
