### PR TITLE
Adds the Heavy Disintegrator to the Traitor Uplink

### PR DESCRIPTION
**Pull request by Optimism333**
## Syndicate Officials Have Signed A Trade Pact With Unknown Alien Forces... ##
Syndicate sleeper cell operators can now equip themselves with the heavy disintegrator laser weapon from a new section labeled "Extraterrestrial Black Market". Currently there are no discounts or restrictions applied on purchases. Good luck, operatives.

Screenshot (158)

## What the pr does and why ##
- The heavy disintegrator is now available to traitors at the price of 16 TC.
- The price might be a bit steep, I'm going by the high end of TC trades I did with admemes for the weapon. It is a pretty strong item, right between a laser rifle and laser cannon in terms of damage, not to mention having a useful and hilarious alt-mode stun.
- Some players suggested I apply a species discount for greys, and maybe I will in the future, I dunno. What I can guarantee is that this won't be the only item that gets added to this section of the uplink, assuming this pr passes.
- Why? Because it's a neat gun. While it is very capable of murder, the scrambler mode offers some fun saboteur/prankster utility that makes it somewhat unique. I've had a lot of fun with it via TC trades, and would like to make it a bit more available for traitor gimmicks.

## What is a heavy disintegrator? ##
- #31592

## Conclusion ##
Feel free to share thoughts and feedback. Is the price too high? Too low? Do you hate the pr in general? Do discuss, and thanks for your time.

:cl:
 * rscadd: Adds the heavy disintegrator to the traitor uplink for 16 TC

### CODE REVIEW

**Comment by Eneocho** [comment]
Make it have a discount for ayy lmaos.

**Comment by Optimism333** [comment]
> Make it have a discount for ayy lmaos.

later, unless you wanna do it first

**Comment by Eneocho** [comment]
I wanna but probably won't. And the price is a bit too high. 16 for a gun is too much, even if powerful, it just guarantees that whomever buys it will go for murderhobo, since you can't really hide it, unlike an ebow/esword. Make it 12tc(ish).

**Comment by Optimism333** [comment]
> I wanna but probably won't. And the price is a bit too high. 16 for a gun is too much, even if powerful, it just guarantees that whomever buys it will go for murderhobo.

Okay, I will make a makeshift poll on this.

HEAR YE, HEAR YE

### UPVOTE THIS POST IF YE THINK THE PRICE IS FINE ###

### DOWNVOTE IT IF YE THINK IT SHOULD BE CHEAPER ###

Edit: I'll wait a couple days so anyone interested in the price can have a say before I decide whether or not to make any changes

**Comment by angryturnip** [comment]
Make it appear above the co-op cell. Stuff over 20 tc should be the very last thing

**Comment by Optimism333** [comment]
> Make it appear above the co-op cell. Stuff over 20 tc should be the very last thing

Alright, sure. That's easy enough.

**Comment by Optimism333** [comment]
> I wanna but probably won't. 

Aw come on. Please?

**Comment by Eneocho** [comment]
Make sure it's also above the nuke ops specials.

**Comment by Optimism333** [comment]
> Make sure it's also above the nuke ops specials.

Nukeop specials are at the very top, unless I'm mistaken. And I don't think this would appear on one of their uplinks anyways, it's only adding it to the traitor uplink.

**Comment by Optimism333** [comment]
> Make it appear above the co-op cell. Stuff over 20 tc should be the very last thing

Alright, done. Will update the screenshot.

**Comment by Optimism333** [comment]
Decided to put the section above implants instead. It looks neater, imo

Screenshot updated

**Comment by calzilla1** [comment]
Considering the revolver is 13, which wrecks shit like nothing else, it should probably more comparable

**Comment by Optimism333** [comment]
Looks like the two sides are nearly neck to neck on the price issue. I'll give it two more days or so.

**Comment by Blithering** [comment]
Considering its high capacity, high damage and stun function, the cost is justified, I would say it's comparable to the radgun, which comes in at 18 before discounts. 16 with no discounts seems fair to me.

**Comment by xeroxemnas** [comment]
War of the Worlds style invasion with Tripods when?
At least we get the vaporizer guns to melt humies.

**Comment by Optimism333** [comment]
> Considering its high capacity, high damage and stun function, the cost is justified, I would say it's comparable to the radgun, which comes in at 18 before discounts. 16 with no discounts seems fair to me.

I'm inclined to agree with this, myself. It's a pretty powerful gun, and even if it doesn't have the stopping power of a revolver bullet it more than makes up for it with having a large number of shots per charge, an alternate stun mode, AND the capability to disintegrate deceased victims.

It's been nearly three days and since "it's fine as is" is holding on to a slim but steady majority, I'm not going to change the price in this pr.

**Comment by Eneocho** [comment]
Wiki updated

**Pull request merged**
