### PR TITLE
Removes white pixels from dead spider icons

### PR DESCRIPTION
**Pull request by Lokiamis**
Remember to double check the little gaps when you use the fill tool to delete the background, friends.

sss

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Or just use global select when deleting the background.

**Comment by Kitfox88** [comment]
IIRC there's a little white pixel floating at the edge of the 32x32 person sprite when facing left with the sawn-off shotgun as well, or at least there was a weekish ago?

**Comment by PJB3005** [comment]
If we're gonna point out white pixel issues:

How about literally every vending machine?

**Comment by Lokiamis** [comment]
@PJB3005 I looked at a bunch and didn't see what you're talking about. Can you point it out for me?

**Pull request merged**
