### PR TITLE
new virus effects: Calorie burn rate modifiers

### PR DESCRIPTION
**Pull request by MadmanMartian**
Just something for more things at level 2.

One makes you burn calories passively at a higher rate, other halves that.

:cl:
 * rscadd: Adds 2 new stage 2 symptom for pathogens. One makes you burn calories quicker, the other makes you burn them slower.

### CODE REVIEW

**Comment by SonixApache** [comment]
Wasn't @Arthurdentist talking about how viruses have some sort of modifier attached to them that almost nothing uses? Maybe you could use that as additional multiplier?

**Comment by MadmanMartian** [comment]
Changes:
Conflicts fixed, now using the multiplier

**Comment by SonixApache** [comment]
more conflicts

**Comment by SonixApache** [comment]
[update wiki]

**Comment by MadmanMartian** [comment]
Wiki's not a hard requirement for virology anymore as of #21959 but I'll try to get round to it

**Comment by SonixApache** [comment]
👍 didn't know about that, i'll make sure to redirect people to the virus description device next time they ask

**Pull request merged**
