### PR TITLE
Removing the Construction Area from the possible Infestation random event spawn places

### PR DESCRIPTION
**Pull request by DeityLink**
> Bioscans indicate that slimes have been breeding in the Construction Area.
> 
> Roger Wilco [common]:"Where the fuck is that "Construction Area"?"

Since there's no construction area on most maps...

### CODE REVIEW

**Comment by clusterfack** [comment]
But where the fuck IS the construction area, we may never know

**Comment by Probe1** [comment]
Deff has a great one.  Meta used to have a really cool one but it disappeared and I think the incinerator got put in its place.

I consider the small gas mixing area just above the southwest solars to be the construction area personally but I do not believe it is labeled that way.  

It's also a great place for antags to do antag stuff since no one goes there or remembers it exists but don't tell nobody.

**Comment by DeityLink** [comment]
Box's construction area used to be just in front of engineering, where tcomms is nowadays. Back then tcomms used to be on the old tcomms satellite (hence its name) where the goonecode is nowadays.

**Comment by Probe1** [comment]
Yup it confused the hell out of me when I was new and the existing maps were very old, and there was this construction area somewhere on the left but I kept running into doors I couldn't enter and didn't know what was on the other side.  

Halcyon days.

**Comment by AutismSpider** [comment]
construction area on box is the mommis nest when the spawn event happens

Don't fucking ask why.

**Pull request merged**
