### PR TITLE
Adds eyepatches to costume vend

### PR DESCRIPTION
**Pull request by carshalash**
Adds more roleplay options for people who want to do all sorts of things, pretend to be a pirate with the chill mime who always dresses up as one. Give one to rambling maniac when he comes back to make him look even more crippled and fucked, pretend to be a hard ass battle torn captain. It would probably make more sense for this to be added to the costume machine but whatever.

### CODE REVIEW

**Comment by ComicIronic** [comment]
>It would probably make more sense for this to be added to the costume machine

Yeah it would, you should do that. The eyepatch doesn't appear in the clown or mime starting items, and the crate you put it in makes no sense.

Also this weeb nonsense has earned you a repo ban.

**Comment by Exxion** [comment]
Just for shitposting in an OP? Harsh

**Comment by ComicIronic** [comment]
For shitposting so much I had to scroll to reach the comment section.

**Comment by Exxion** [comment]
zoom out lol

**Comment by DoctorMonkey** [comment]
Weeb lyric shitposting?

That's plapatin-level.

http://ss13.moe/forum/viewtopic.php?f=14&t=3726

**Comment by carshalash** [comment]
maan, how can I change it if repo ban?

**Comment by SonixApache** [comment]
why is the OP a paragraph of rambling nonsense

add changelog :cl:

**Pull request merged**
