### PR TITLE
Headcrab zombie sprite and fixes

### LINKED ISSUE #27867: Spessmart can spawn live headcrabs as hat clothing
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
9235a1c75374f52dea6a9a7da710d8b4170f9309

# Description
Because headcrabs are technically hats spessmart has a chance to spawn live headcrabs in its clothing department. This causes concern of spessmart becoming locked down by killing the headcrab or aggroing the headcrab into breaking stuff.

# Steps to Reproduce
Find spessmart and be very unlucky.

# What you Expected
Cool hats.

# What Actually Happened
Oof ouch my skull.

### LINKED ISSUE #28539: Amorphous Masks when turning the player into headcrab zombies make immortal zombies when killed and ghost the player, the immortal zombies create insane infinite lag
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
81b84a0e2ef9b7569516aa9ac5608e7eca107b5b

# Description
See title
# Steps to Reproduce
Get a transforming mask that turns you into a headcrab zombie
# What you Expected
To revive as a zombie or drop dead 
# What Actually Happened
the zombie lived and I was ghosted

### PR DESCRIPTION
**Pull request by DeityLink**
image

Fixed #28539
Fixed #27867

:cl:
* imageadd: Headcrab zombies have a new sprite looking more akin to their HL2 counterparts, including also a clothed version used when the zombie is spawned by other means than an actual headcrab, such as gold slimes or amorpheous masks.
* bugfix: Fixed multiple bugs linked to headcrab zombie death, including deadly lag occuring when an amorphous mask wearer transmogrified as one gets killed.
* rscdel: Facehuggers and Headcrabs no longer try to sneak themselves among other articles of clothing at Spessmart.
* rscadd: Bomberman Suit and Head now have a chance to be found at Spessmart (for purchase of course).

### CODE REVIEW

**Comment by Irradiation** [comment]
>rscdel: Facehuggers and Headcrabs no longer try to sneak themselves among other articles of clothing at Spessmart.

Deadmin/decollab he.

**Comment by DeityLink** [comment]
You'll never take me down !

source

The issue count must go down !

**Comment by gurfan** [comment]
facehuggers and spessmart is 100% a feature

**Comment by DeityLink** [comment]
It's only fun for observers

**Comment by Blithering** [comment]
Does the spessmart fix also count the mining toy version? I will admit to setting off the sensors not noticing one of those jump on my face as I made for the exit.

**Comment by DeityLink** [comment]
> 
> 
> Does the spessmart fix also count the mining toy version? I will admit to setting off the sensors not noticing one of those jump on my face as I made for the exit.

I will keep the toy version if you really care, but I'm keeping real ones and headcrabs away.

**Pull request merged**
