### PR TITLE
New Borg Sprites

### PR DESCRIPTION
**Pull request by Shadowmech88**
I took Dizor's kodiak borg sprites from #6364 and tweaked them a bit, they're ready to go now.

Standard:
kodiak_standard_off
kodiak_standard_on

Service:
kodiak_service_off
kodiak_service_on

Security:
kodiak_sec_off
kodiak_sec_on

Combat:
kodiak_combat_off
kodiak_combat_on

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Sprite valids secured

**Comment by kol1th** [comment]
> no medical

cmon dizor

**Comment by Ephx1** [comment]
noice
o
i
c
e

> No medical

why-foo bots go home

**Comment by Shadowmech88** [comment]
Dizor did actually have some frontal sprites for alternate medical marina borgs, but I couldn't find the other directions; he may not have made other directions at all.

**Comment by icantthinkofanameritenow** [comment]
The service one looks weird but the others seem alright to me.

**Comment by Brolaire** [comment]
I love the looks of the service one personally, I really dig the functionality-first design of borgs n shit

**Pull request merged**
