### PR TITLE
Adds a tiny (0.2 second) delay to cutting cables

### PR DESCRIPTION
**Pull request by brndd**
[tweak]

I've been told that things that are disproportionally easier to break than they are to fix are bad. One example of this that I could think of is running along maintenance spamclicking (or god forbid autoclicking) on wires, which can very quickly cut dozens or even hundreds of wires.

This adds a very quick `do_after()` to cutting wires. It's 0.2 seconds and basically has no effect when cutting them while standing still, but makes it impossible to cut wires while running.

Excuse my low-quality gif, but it hopefully gets the point across.

:cl:
 * tweak: Wires now take 0.2 seconds to cut. This has little effect in practice, but prevents you from cutting them wile running.

### CODE REVIEW

**Comment by Goldsteel** [comment]
I will be honest, I don't like having an action time bar appearing repeatedly. Otherwise, I don't have an issue with this.

**Comment by brndd** [comment]
Yeah I don't know if there's a good way to do this without the progress bar. It would probably be confusing if the bar was just hidden.

**Comment by ghost** [comment]
Use click delay.

**Comment by brndd** [comment]
Click delay probably would still allow you to cut wires while running, it just wouldn't cut quite as many of them. The intention is to force you to stop, even if for just an instant, in order to cut wires.

**Comment by ShiftyRail** [comment]
This makes solars/wire art gas

**Comment by brndd** [comment]
0.2 seconds is low enough that it will make no practical difference for most situations. How often do you cut wires while running when setting up the solars or making wire art?

**Comment by ShiftyRail** [comment]
0.2 seconds is the average reaction time
It's exactly enough to be noticeable (and hence frustrating)

I think the frustration felt will not because of the 0.2 seconds, but because of the existence of a delay in itself
If you see what I mean

**Comment by brndd** [comment]
I think you'll be too frustrated trying to click the 1-pixel wire sprite to be bothered by the delay. Unfortunately it can't be made any lower than this for technical reasons.

**Comment by Allspice** [comment]
isnt there an auto wiring device thing

**Comment by mtpowell** [comment]
>I've been told that things that are disproportionally easier to break than they are to fix are bad.

I was unaware there's a delay to placing wire.

**Comment by SonixApache** [comment]
seems like it would be really fucking annoying

@Allspice the rapid cable layer is a pain in the ass to use

**Comment by FudgePucker** [comment]
@mtpowell Have you ever tried laying down smooth wiring without the RCL?
It takes 100 times more effort and time than just cutting wires.

**Comment by Exxion** [comment]
It only takes like two times more effort and time if you lay knots in one direction then backtrack over them to finish

**Comment by brndd** [comment]
Yes all in all this probably isn't that good of a change. It fixes something that isn't a big problem to begin with and does so in a way that can easily be annoying. I'll just self-close this.

**Pull request closed without merging**
