### PR TITLE
No fun allowed

### LINKED ISSUE #26415: You can send people to nullspace by unwrenching the chair they sit in
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
3835445ab853608e701684ab9905915b875e5134

# Description

>be normal human being
>relax after a hard at work on my comfy chair
>mischevous mommi (probably from a birdbrain) unwrenches my chair
>get sent to cuckspace

# What you expected

Fall off my chair and unleash my anger on the mommer

# What actually happened

Sent to the shadow realm

### PR DESCRIPTION
**Pull request by ShiftyRail**
removes fun
Closes #26415

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
No changelog for an "I ded pls nerf" change?

**Comment by jknpj** [comment]
It might be my fault, haha

**Comment by Kurfursten** [comment]
More likely mine for adding new wrench behavior to chairs

**Comment by Exxion** [comment]
No it's mine for making `qdel()` use `forceMove()`
Just have to move the block that unlocks atoms up above the block where it moves it

**Comment by ShiftyRail** [comment]
Hasty fix, will do a proper one tommorow

**Pull request merged**
