### PR TITLE
Capitalizes Retract in " Someone is harvesting diona nodes. You have …

### PR DESCRIPTION
**Pull request by Probe1**
…been added to the list of potential ghosts. (Teleport | retract) "

0% tested 100% :eggplant:

### CODE REVIEW

**Comment by Kurfursten** [comment]
Our safe space has been violated by a phallic emote

**Comment by Konater** [comment]
:eggplant:

**Comment by ComicIronic** [comment]
Did you seriously make a change to a message that doesn't even appear in the game

**Comment by 9600bauds** [comment]
Comment tidiness is serious

**Comment by Probe1** [comment]
i didn't find ANY OTHER INSTANCES of the message in game and it looked identical to the grammatical messup in game.

**Comment by Kurfursten** [comment]
Not even on line 43 of seed_mobs.dm?

**Comment by Probe1** [comment]
THE OL SPICY SHITCODE

**Pull request merged**
