### PR TITLE
Fixes Vox Armalis breathing oxygen instead of nitrogen.

### LINKED ISSUE #17367: Vox Armalis need oxygen to live
#### Description of issue
A Vox Armalis, although being a sub-species of Vox, can't survive without oxygen.

#### Steps to reproduce 
Spawn an Armalis on the vox outpost and watch as it slowly dies.

#### Server revision
Game: f82455d2654e74f1a2877fe99384c9da40e5454a 
Patches: 78ac2f909b50159df885e55ab563750b9b00c5dd 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Mothblocks**
Copied over from /mob/living/simple_animal/hostile/humanoid/vox.
Fixes #17367

:cl:
 * tweak: Vox Armalis breathe nitrogen instead of oxygen, but unlike other Vox will not get oxygen poisoning.

### CODE REVIEW

**Comment by SonixApache** [comment]
description of changes in the title, please

**Comment by Mothblocks** [comment]
@SonixApache fixed

**Comment by ghost** [comment]
Been a long time since I looked at simple mobs, the max o2 1 will poison them right? Admins still use armalis occasionally so if it does poison them, please put in a warning prompt for when they try to spawn or tmog them cause they explode on death. explosion(gloc, -1, -1, 3, 5) On rng it can hit and break a hand.

Could also just leave the o2 toxicity off since they can't have a tank and mask equipped and toggled on spawn as-is.

**Comment by Pathid** [comment]
>Could also just leave the o2 toxicity off since they can't have a tank and mask equipped and toggled on spawn as-is.

In their original lore they have lot of cybernetic parts in them so it would make sense, at least as much sense as them exploding on death. Or at the very least the Armalis armour, if it gets put on them, should be changed to make them immune to most atmos stuff. Also they should be able to put the armour on themselves by clicking it, since right now they need a carbon mob with hands to put it on them and it's dumb.

**Comment by Mothblocks** [comment]
Made them immune to oxygen poisoning.

**Comment by jknpj** [comment]
>Made them immune to oxygen poisoning.

Please add it to the changelog too.

**Comment by Mothblocks** [comment]
@jknpj done

**Review by jknpj — APPROVED** [review]

**Pull request merged**
