### PR TITLE
Wild West away mission rebalancing attempts

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
Made changes to the mobs in Wild West Away Mission.

*Some of the Faithless in the maze are replaced with stronger versions that have 100 health and can inflict up to 20 damage (upper limit 20, lower limit 15).
*Modified some of the ranged syndicate mobs to use laser guns, recycling the version I used in my old vault.

### CODE REVIEW

**Comment by ComicIronic** [comment]
> 4 hits to crit instead of 7

Consider this affects cult rounds as well

**Comment by icantthinkofanameritenow** [comment]
@ComicIronic 
Well, when they start showing up in cult rounds then Nar-Sie has already risen so it makes no real difference.

**Comment by ComicIronic** [comment]
Post-Nar'Sie still has another 10 (ten) minutes of gameplay!

**Comment by icantthinkofanameritenow** [comment]
@ComicIronic True. But think of it this way, those ten minutes are already plenty lethal due to all the harvesters.

**Comment by Imagebard** [comment]
>+10 damage and +40 HP

Calm down your buff boner.

**Comment by icantthinkofanameritenow** [comment]
There, the buff is slightly weaker. Better?

**Comment by Imagebard** [comment]
k

**Comment by 9600bauds** [comment]
> Post-Nar'Sie still has another 10 (ten) minutes of gameplay!

This is an issue all in it's own honestly

**Comment by Imagebard** [comment]
Calls due to Nar'Sie should automatically become priority shuttles, like in red alert. That should halve the time people spend being idle.

**Comment by Ephx1** [comment]
> This is an issue all in it's own honestly

Whaaaaaaaaaat? No, that's for when cult has already won and they can gloat in a lag fest! This is a very vital feature and should not be altered.

**Comment by Probe1** [comment]
faithless come up in way more areas than just post round cult   6 hits to kill is alright, 4 is not.

**Comment by 9600bauds** [comment]
Give examples

**Comment by Probe1** [comment]
Pokeballs
Admins
Xenobiology

**Comment by Imagebard** [comment]
>Pokeballs

Takes actually catching

>Admins

You (should) know what you are doing.

>Xenobiology

Fair point, but still RNG and people would rather release slimes, and other gold slime mobs are just as dangerous.
I'm still uneasy by the damage buff, but at least it got reduced to 5 hits instead of 4.

**Comment by Probe1** [comment]
I was talking about the master trainer belt.  Antag item, comes with 6 random mobs incl this.

**Comment by 9600bauds** [comment]
Does that mean we can't balance ANYTHING because it affects master's belt balance?

**Comment by Probe1** [comment]
No it means cult mobs already have a heavy hitter (creature) and this is a little too far.  Increase the tanky-ness by hp or increase the damage.

**Comment by icantthinkofanameritenow** [comment]
@Probe1 
And have you forgotten cult mobs only show up when they've already won? Besides, this was specifically made with the Wild West away mission in mind since my decision to buff it was based off how easily they were slain by the crew that actually managed to make it to them.

**Comment by Konater** [comment]
> balancing for an awful one way trip away mission by forcing you to use an extra laser shot for 64 mobs

**Comment by Imagebard** [comment]
>this was specifically made with the Wild West away mission in mind

**Comment by Shadowmech88** [comment]
If you want to make that away mission more difficult, just make a new `/mob/living/simple_animal/hostile/faithless/strong` mob with buffed health and damage, and replace the current faithless in the away mission with the strong faithless.
All other normal faithless mobs will remain as they are.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88
Fair enough. I'll fix the commit soon.

**Comment by ComicIronic** [comment]
> 64 mobs

Is this real

**Comment by Konater** [comment]
> Finding /mob/living/simple_animal/hostile/faithless...
> Found 64 objects

yep

**Comment by icantthinkofanameritenow** [comment]
Alright, I had an idea. I've added the "strong" version of the faithless, and I figure it should be fine to replace only some of them with the new version. Does that work?

**Comment by ghost** [comment]
After seeing a man solo the wishgranter maze in the wild west away mission, I support a buff

**Comment by PJB3005** [comment]
How about we remove away missions and make them procedural?

**Comment by ghost** [comment]
Well that seems boring, means we can't make a story to an away mission, or objectives beyond 'get to the end'

**Comment by icantthinkofanameritenow** [comment]
And it would be a massive bitch to program too. How would you even ensure it could generate a mission properly without admin intervention?

**Comment by Kurfursten** [comment]
I just want to point out that saying the faithless were easily slain translates to

> After 20 or more crewmembers died, one guy got to the end, and all of them were heavily armed with the abundant C20-r SMGs and DD autoinjectors from that mission.

It was hardly an easy rout. The away team was wiped out alongside their NPC counterparts. I don't think they need a buff. If you want the maze to be harder, reduce the number of free weapons and healing items. And the maze wasn't "soloed" by anyone. Four people went in and two made it to the end, two died. Robot Man and the Vox made it, the HoS and bartender died in battle.

I don't know why it needs to be harder though. The guy who got the granter wished for minerals but by the time it took to complete the mission (at least an hour), none of those minerals were relevant anymore. Meanwhile the entire crew was wiped out.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten 
I've modified the mission somewhat, so while it's going to be harder I don't know if it'll be visibly more difficult. 

And as the bartender, everything was dead long before I got to the maze.

**Comment by ghost** [comment]
If we're 'fixing' the wild west mission, the mines don't do anything bar the radiation mines.

**Comment by icantthinkofanameritenow** [comment]
@Skullyton

I distinctly remember the plasma mines releasing plasma into the air when I stepped on one and making a huge fire. 

Also, what are your thoughts about replacing some of the revolvers with other stuff? I could use suggestions, because the map isn't exactly short on guns.

**Comment by clusterfack** [comment]
I fixed all the mines within the past month I think? Check again.

**Comment by unid15** [comment]
> not giving the stronger version a different name

I propose "Soulless"

**Comment by Kurfursten** [comment]
@Skullyton @icantthinkofanameritenow Yes I saw him step on that mine and it did almost kill us

Thanks for stepping on that I wasn't dying enough from the radiation already

**Comment by icantthinkofanameritenow** [comment]
I seem to have bungled this due to a mistake in committing with something else. Due to that and my own lack of interest, I'm closing this.

**Comment by Kurfursten** [comment]
You should still be able to recover your code by rebasing to the previous commit, check your reflog

It's good practice even if you don't want to keep working on this. Lord knows you're not obligated to work on something you're not interested in.

**Comment by icantthinkofanameritenow** [comment]
Too late, I already rebased my bleeding edge code to the current bleeding edge. Lesson learned at least- never commit directly to the bleeding edge.

**Pull request closed without merging**
