### PR TITLE
Revert "SAMMIs - Stationary Assembly MMIs"

### PR DESCRIPTION
**Pull request by gbasood**
Reverts d3athrow/vgstation13#9736

Too many fucking bugs

### CODE REVIEW

**Comment by gbasood** [comment]
@cloroxygen If you want them to be re-added, we need to run a round on a test server with them AFTER and ONLY AFTER you address all the issues related to SAMMIs that hav ebeen filed

**Comment by ghost** [comment]
Well, now we know what needs fixing

**Comment by icantthinkofanameritenow** [comment]
You mean "everything"?

I'm still not even sure why they even needed to exist.

**Comment by MercuryDoll** [comment]
So observers/ghosts whose body got destroyed have another way to bide their time until they can join the round properly again. It's great for people like me who sometimes can't dedicate a whole hour of spessmen. I often hit observe because i know "in 15 minutes i'll probably need to go afk for a few minutes" and this way i can dropin/dropout whenever and still enjoy spessmen.

**Comment by icantthinkofanameritenow** [comment]
@MercuryDoll 

> So observers/ghosts whose body got destroyed have another way to bide their time until they can join the round properly again. 

We have dionaea, posibrains, golems, mice, and derelict MoMMIs for that already. There's no shortage of ways of getting people back into the round as it is. Hell, most servers don't even have all of those.

**Comment by Shadowmech88** [comment]
> We have dionaea, posibrains, golems, mice, and derelict MoMMIs for that already.

All of these sever you from your previous body. If you die as a human and become a diona, you _never_ get to go back to your previous body.
SAMMIs allow ghosts to jump back into an active role in the round for 5-10 minutes while waiting for their body to be found, for example.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88

> All of these sever you from your previous body. If you die as a human and become a diona, you never get to go back to your previous body.

As it should be.
How is this so hard to understand? If you want an active role in the round but don't want to give up your old body, just spin a chair or fuck with the lights. You can't have it both ways.

**Comment by Shadowmech88** [comment]
> You can't have it both ways.

Says you. SAMMIs _do_ allow players to have it both ways.

**Comment by MercuryDoll** [comment]
Mice can do absolutely nothing, might as well stay ghost, which makes observing easier. 
Posibrains are never made due to the R&D requirements, not to mention that you'll mostlikely be stuffed into a cyborg and hence be under silicon laws (mostlikely for validhunting), which many players already dislike enough to not play them. 
Dionae are usually killed by crew before they can evolve, and even fully grown are mostly ID-less and, in best case, ignored. 
Golems are, like posibrains, rarely made and suffer from the same issue as dionae. 
Derelict MoMMIs were good to learn construction and atmos, but have otherwise no use outside of building an autismfort that noone's going to see unless you post it in the thread after the round ended because they're completely separated from the crew/station, might as well play on the test server or your own dorffort server.

SAMMIs have the advantage of being essentially drop-in/drop-out without wasting a jobslot by going braindead afk.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88
And I consider that a bad thing because it actually makes being dead have lasting consequences beyond "oh, I can just dick around as a robot arm a while before I get brought back to life".

Posibrains don't let people jump out, diona nymphs don't let people jump out, golems don't let people jump out- why should this be treated differently than anything else? Even MoMMIs don't act that way and their equivalents on TG do exactly that.  I know being a ghost is boring, but if anything that means that it's up to the people who can offer ways of bringing them back to create more opportunities to do so with what's already available. 

@MercuryDoll 
SAMMIS have laws too, you can't use that as a "positive" for them. And if anything they're even more oppressive than their crab counterparts since at least the crabs won't be bossed around endlessly. 

Besides, the drop-in/drop-out is by definition breaking those laws. You can't say that you're going to follow orders when you have no intention of even staying a SAMMI  for the rest of the round! The fact that this whole "job" is being viewed as simply something to pass the time before you can be revived properly should be a big warning as to how viable it really is as a job in its own right.

**Comment by ghost** [comment]
I just wanted to pop in and say I intend to fix up SAMMIs next free chance I get, I appreciate all the bug reports, that should make everything a lot easier.

**Pull request merged**
