### PR TITLE
Remakes our sheet system regarding fabricating stuff

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Instead of all the cm3 bullshit we'll use sheets directly, so for example instead of a component costing 70 cm3 metal it will cost 0.01 of a metal sheet. This way it drastically improves readability because a lot of materials also have their own cubic centimeters thing per sheet. Also the minimum cost will be 0.01 of a sheet.
This sort of thing is inspired by Eris-CV, where I've seen their fabricators and deem their sheet system superior to ours.
Since this change will go through over 100 files just to change a bunch of lines for every goddamn thing in the game, an issue or two would be inevitable.

- [X] Removed CC_PER_SHEET
- [x] Converted every CC_PER_SHEET reference into a straight sheet amount
- [x] Reticulated splines.
- [ ] Modified how fabrication of items works.
- [x] Address how many resources material bins can hold.
- [x] Contemplating dumpstering the entire change for making me suffer so much
- [x] Modifying the material synthesizer.
- [x] Modifying mecha fuel code.
- [x] Modifying ore redemption machine.
- [x] Actually making sure that whatever pumps out sheets does so out of the new material system.
- [ ] Modified R&D design prices
- [ ] Big ass testing

Current bugs and issues:
- Material Synthesizer does not work
- Autolathes and Fabricators should show sheets and not just "X iron"
- Fucked up prices in autolathes

:cl:
 * rscadd: The sheet system has been reworked. Sheets inside fabricators will now be straight values instead of cubic centimeters. Prices may have been changed due to the modified material price being considered in sheets instead of cubic centimeters. The minimum cost of an object is 0.01 of a sheet.
 * tweak: As a consequence, many things had their material prices readjusted.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
This is a good change, fuck how we currently do it. Whether or not I have enough to make something is total guess work.

**Comment by dunsel-hordon** [comment]
ya it is a pain in the ass to read current numbers. Took me a bit to remember the values of all the different sheets but damn was it autistic.

**Comment by Kammerjunk** [comment]
is the minimum cost of an object currently 70 cm3 (or 0.01 of a sheet)?

**Comment by boy2mantwicethefam** [comment]
the minimum cost will be 0.01 of a sheet

**Comment by Kammerjunk** [comment]
yeah but I mean currently - is the minimum cost without this PR 70 cm3, as it will be afterwards?
I don't think it's an issue if it is or anything, but it's relevant to know

**Comment by boy2mantwicethefam** [comment]
The minimum cost without this PR is 0.1x of the thing's cost if that's what you mean

**Comment by SonixApache** [comment]
would recommend using `experiment` or `wip` in the :cl: to signify nuclear changes

**Comment by Kammerjunk** [comment]
I mean that you say that a component which costs 70 cm3 will cost 0.01 sheets and that you say that the minimum will be 0.01 sheets. that means that anything that before cost less than 70 cm3 will now cost (the equivalent to) 70 cm3.
was there anything prior to this that cost 70 cm3? I don't think it's an issue if there was because it's such an insignificant amount, but it's relevant to know

**Comment by Kammerjunk** [comment]
either way, I can see a lot of probably-minor [balance] changes at a glance (e.g. 50 cm3 metal => 0.5 sheets instead of 0.01 or 20 cm3 glass => 0.5 sheets instead of 0.01)
edit: actually the extent of this is by no means minor

**Comment by ShiftyRail** [comment]
I find it immulsive to have the things being given in cm^3n but I have no strong stakes on the matter

**Comment by Kammerjunk** [comment]
so do I but god I have NO idea what it means when I'm actually looking at a lathe

**Comment by Zth--** [comment]
Seems like a good change.

Also I should mention that some costs are being heavily modified in this process.

**Comment by ShiftyRail** [comment]
That'd be very high effort for trivial gain, but a little "convert units" button on machines would be pretty good for this.

**Comment by TGFH** [comment]
I never knew that the numbers on the lathe were supposed to be cm3 in the first place. It always just seemed arbitrary so I would just guess how many sheets of whatever I needed.

**Comment by GreatBigFailure** [comment]
>edit: actually the extent of this is by no means minor

Can you explain more? Cubic CM system is visual noise to me so I just go "Number big, more sheets". How does this alter resource costs if it's just a direct conversion to less inflated numbers?

**Comment by Kammerjunk** [comment]
@GreatBigFailure cause it isn't just a direct conversion - a lot of things get changed changed from e.g. less than 0.01 of the amount you get from 1 sheet to e.g. 0.5 of a sheet

**Comment by boy2mantwicethefam** [comment]
Like Icarus, flying too close to the sun. This changes way too many things and it will look like shit in-game

**Pull request closed without merging**
