### PR TITLE
we /wwe/ here

### PR DESCRIPTION
**Pull request by SirSkeleto**
:cl:
 * :rscadd: folding chairs now hurt

### CODE REVIEW

**Comment by brndd** [comment]
While you're at it, make throwing/slamming people (using grab intent) into folding chairs or tables fold them if they're unfolded.

**Comment by SirSkeleto** [comment]
> While you're at it, make throwing/slamming people (using grab intent) into folding chairs or tables fold them if they're unfolded.

nah chief that's unatomic and i am not going to spend more than 5 secs on a pr rn 'cause finals

**Comment by SonixApache** [comment]
If it's /wwe/ shouldn't the folding chair *not* do any damage?

**Comment by Blithering** [comment]
Stepladder with no use besides putting the championship belt on top of when?

**Pull request merged**
