### PR TITLE
Mice are now attracted to supermatter.

### PR DESCRIPTION
**Pull request by gurfan**
What it says on the tin. Mice will walk towards supermatter similarly to how they walk towards food. Mice are already immune to supermatter, so they wont dust and be consumed by the shard. They'll die and leave a corpse behind once they try to take a bite out of it, though.

:cl:
 * tweak: Mice have started to confuse supermatter with cheese.

### CODE REVIEW

**Comment by bthomas2** [comment]
wtf

**Comment by N3X15** [comment]
mommi stab

**Comment by DeityLink** [comment]
but why

**Comment by SonixApache** [comment]
😕

**Comment by ghost** [comment]
> but why

because supermatter is made out of celestial cheese

**Comment by GreatBigFailure** [comment]
> but why

Someone wrote as a joke on the wiki that the platform the supermatter shard rests on is actually a pile of mice corpses. The mice think it's cheese, bite it, and die. Since they are the one thing immune to it they are the one thing that can be used as a platform for it. This is now the accepted truth.

**Comment by DeityLink** [comment]
I think this should remain in-lore drunkard rambling and conspiracy theory.

**Comment by gurfan** [comment]
twas not meant to be

**Pull request closed without merging**
