### PR TITLE
I fucking swear this better fix it

### PR DESCRIPTION
**Pull request by DeityLink**
Fuck BYOND's floating point numbers.

Oh and also discord's #server-status will now give the starting threat level, and specify the final threat level between parenthesis if it's different.

### CODE REVIEW

**Comment by Exxion** [comment]
I already said what happened. The math works fine. The threat increased during the round. It wasn't 66.6 at roundstart.

EDIT: OK I'm tired and somehow missed the first changes
But the part that changes the math is unnecessary

**Comment by Kurfursten** [comment]
Fix it

**Comment by DeityLink** [comment]
I'm keeping the math change because it let's us write "666" in the code instead of 66,6

**Comment by Exxion** [comment]
Alright, though you should know that if the Ref is to be believed, `round()` with one arg is floor rather than actual round, so it's not exactly the same
If you give it a second arg of 1 it should be though

**Pull request merged**
