### PR TITLE
New AI Action Icon Set

### PR DESCRIPTION
**Pull request by ghost**
New AI Action Icon set with consistent art style
aiicons

:cl:
 * rscadd: New icons for AI actions

### CODE REVIEW

**Comment by clusterfack** [comment]
Nice but it might need a bit more contrast? Blue on blue is a bit hard to distinguish.

**Comment by Ephx1** [comment]
I see absolutely nothing wrong with the current set of icons

**Comment by ihadtoregisterforthis** [comment]
Consistent with what?

**Comment by JustSumBody** [comment]
With TG

**Comment by kol1th** [comment]
Always liked this one more

**Comment by yclatious** [comment]
Ours looks better tbh. Why not make it a toggleable thing, to be able to choose our current one or go for the new?

**Comment by Allspice** [comment]
ai

Current interface. I think manifest shuttle and statelaws could stand to be more distinct.

**Comment by Ephx1** [comment]
Manifest is the ID computer, something that shows the crew manifest.
The call shuttle is a shuttle console.
State laws is the AI upload.

They're pretty distinct if you know a few jobs, _something I hope you do before choosing AI_

**Comment by kilozombie** [comment]
The tg icons are irritating, all look similar, and I've played with them before
Please do not merge

**Comment by SonixApache** [comment]
@Ephx1 shuttle and crew manifest are literally the same icon except with a slightly different tint

The TG way is not the way to go, but i do feel some changes could be good.

**Comment by BestName** [comment]
Are you high?
They are not literally the same icon with a slightly different tint.

**Comment by optimumtact** [comment]
fair warning, try not to expose too many things via toggles, it causes you all sorts of pain later and makes it harder to refactor systems

**Comment by ComicIronic** [comment]
Since this is a non-optional UI change without enough support : closing.

**Pull request closed without merging**
