### PR TITLE
Framework for new Holodeck

### PR DESCRIPTION
**Pull request by Lokiamis**
Preview: https://webmshare.com/WJEbK

Adds the framework for the new holodeck I'm working on to Boxstation, Deficciency, and Metastation. 
+Expanded to 11x10 (up from 5x10)
+All existing holodeck rooms are being expanded to match new dimensions. 
+Windows are tinted and doors have been switched to prevent most light from bleeding in and give the holodeck privacy. Very immersive if you keep your flashlights off. 
+/-8 new holodeck rooms have been designed. Lost them in a map error so they're being recreated now.
-Ghetto theater on Box had to be cut. What space was left has been reworked. Nothing major from other stations were lost.
-Haven't added the expanded rooms yet, so the holodeck will look goofy until that PR. It's not broken, they just don't fill the holodeck properly. Should be done by the time this is pushed to master.

ejwfwdenhsamambdgidskhtchibbe7ue6pd5u7-7z7zjmps5vpvcapzzfhm7nsojt2qbsltq7ue0rw7iqrkcd310aq0uidoukbip3vkaxbrdousjy8s0badic5lttzo_p7cdim8 1

hhmeta

deff

:cl: 
 * rscadd: Framework for new Holodeck added.

### CODE REVIEW

**Comment by PJB3005** [comment]
We could probably enable lighting on the holodeck come to think of it.

**Comment by Aurx** [comment]
>tinted windows

But how will people watch sports matches now?

**Comment by yclatious** [comment]
Could you show a picture the reworked ghetto theater in box?

**Comment by Lokiamis** [comment]
@Aurx seats in the holodeck
bball

@yclatious Nothing special, just typical maint stuff and a pretty ok place to hide a body. The dressing room was left alone. There's probably enough space to set up a new theater if need be, but keep in mind there's a theater setting in the holodeck which is pretty neato now.

thea

**Comment by Ephx1** [comment]
This makes me want Bay's AI ability to appear in the holodeck all the more.

**Comment by yclatious** [comment]
I actually like this area more now, good job.

Also, did you just add a pair of sunglasses to that one locker or am I just a bad greyshit for thinking only the southern maint bellow science had sunglasses spawned naturally in maint?

**Comment by JustSumBody** [comment]
Those sunglasses have always been there

**Comment by yclatious** [comment]
Every day, you learn something new about this game. Gotta love that.

**Comment by Sprok0** [comment]
All those pipes running under the walls will be hell to repair, can you fit them on floors somehow?

**Comment by Kurfursten** [comment]
Radio transmitter room needs wires.

It's not your fault, you didn't make the PR to make the transmitter require wires, but you're the one editing the room.

**Comment by Lokiamis** [comment]
@sprok0 the pipes were already under the walls.

**Comment by Probe1** [comment]
I will probably be done with Deff by Tuesday at the latest and if it goes well I assume merged by Wednesday.

If you want this merged before then you'll have to wait on the holodeck for that map.

**Comment by Lokiamis** [comment]
@kurfursten the radioactive death room? Just some wires and a knot under the machine?

**Comment by Kurfursten** [comment]
That's right, you can connect it to that nearby wire that runs to the solars.

**Comment by Lokiamis** [comment]
Alright. I'll clean this up tomorrow.

**Pull request closed without merging**
