### PR TITLE
HE'S GOING OVER THAT CLIFF

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
:cl:
 * rscadd: Added new possible male scream sound.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I don't know about this one, it's SO fuzzy I think it will stand out

**Comment by Kammerjunk** [comment]
I don't need to download this code to know exactly what this sound is

**Comment by boy2mantwicethefam** [comment]
@Kurfursten Don't really know how to clean the audio file

**Comment by Kammerjunk** [comment]
https://www.youtube.com/watch?v=IY9YNF5MMQo
this is the sound and it's a low IQ meme PR because the it's a low IQ meme author but the sound would be fine if it wasn't awful quality
https://www.youtube.com/watch?v=Cd_EnyaeO38

**Comment by DeityLink** [comment]
So I'm not the only one who has the Youtube algo recommend nothing but Speed Racer clips nowadays?

**Comment by boy2mantwicethefam** [comment]
too crusty, you can still hear the song in the background

**Pull request closed without merging**
