### PR TITLE
No-fruit juice and phazon salt random chemical reaction

### PR DESCRIPTION
**Pull request by ghost**
[content]
image
Was suggested this was a good idea to go through with due to effort in finding either.
Requires both 10u mutagen and 10u universal enzymes as a catalyst, and at least 10u of both to produce 1u of a random chemical, or a random chemical reaction with the minimum amounts of each.

:cl:
 * rscadd: Combining phazon salts and "nothing" (no-fruit juice) with mutagen and enzyme as catalysts can produce a small amount of (almost) any random chemical or chemical reaction.

### CODE REVIEW

**Comment by Eneocho** [comment]
pAIsmoke is accessible relatively easy without admin magic, remove it from the blacklist.

**Comment by Eneocho** [comment]
Also, WAY too expensive considering that phazon is literally 1u per sheet while nothing is like 15u per fruit. On average you'll mostly get 1u of bar drinks and wasted 10u phazon.

**Comment by djkramer123** [comment]
Once you get one sheet of phazon you have access to infinite amounts. The recipe is fine as is.

**Comment by Eneocho** [comment]
Fair, but 10u is still excessive considering that you'll most likely get either an alcohol or relatively common chem. As is, it will probably be used once or twice then forgotten about, simply because of how limited it is (Just how often do you get both "nothing" and phazon as bartender? Or as anyone for that matter).

**Comment by Kurfursten** [comment]
I think it's good as an easter egg more than a practical way to fish for rare reagents

**Comment by boy2mantwicethefam** [comment]
Remove adminodrazine from the blacklist it will be funnier this way

**Comment by Eneocho** [comment]
> I think it's good as an easter egg more than a practical way to fish for rare reagents

Still. At least buff it from 1u random reagent to 10u or something.

**Pull request merged**
