### PR TITLE
Machine-Man Interfaces

### PR DESCRIPTION
**Pull request by ComicIronic**
Act as a brain, let you make posibrains into humans (hopefully).

### CODE REVIEW

**Comment by Boxe** [comment]
here we go again

**Comment by Praecordia** [comment]
Yes. YES.
FINALLY
THE HOUR OF THE MaMI IS UPON US
THE HEAVENS WILL OPEN UP AND [spoiler]heredth will finally code those fucking pda chatrooms[/spoiler]

**Comment by Arthurdentist** [comment]
extreme grief potential. Expect lots of 'Positronic Brain not constrained by laws put into human body and murdering the tator tot who killed him in a past life'

Though I suppose its the same as Dionae so I doubt it would be that much of a problem, so long as admins stay on top of it.

**Comment by N3X15** [comment]
Should be malf-related upgrade for mediborg

**Comment by Ephx1** [comment]
Arthur, Positronic Brains have a lawset of "Do no Harm" and "Serve the crew", and according to the small text under that, they serve even other silicons themselves.
If we could get a text along the lines of "REMEMBER YOUR POSITRONIC DIRECTIVES: (Insert Here)" kind of like Secborg and Space Law, I'd be all for this.
Heck, I think Posimechs should get the same message, a majority of the time they ignore their directives too.

**Comment by ComicIronic** [comment]
>hey isnt that cheaper than a posibrain?

Considering it doesn't do diddlysquat without a posibrain in there, I think the cost is fine. Besides that, the design isn't in the game yet.

As for use, I was originally going to have these in either the Blade Runner gamemode or the malf MoMMI gamemode, but we'll have to see.

**Comment by Boxe** [comment]
oh OH

i thought it was seperate from posibrains

**Comment by d3athrow** [comment]
>Arthur, Positronic Brains have a lawset of "Do no Harm" and "Serve the crew", and according to the small text under that, they serve even other silicons themselves.
If we could get a text along the lines of "REMEMBER YOUR POSITRONIC DIRECTIVES: (Insert Here)" kind of like Secborg and Space Law, I'd be all for this.
Heck, I think Posimechs should get the same message, a majority of the time they ignore their directives too.

Add this and i'll pull

**Comment by ComicIronic** [comment]
Added.

**Pull request merged**
