### PR TITLE
Excavation Locker revamp

### PR DESCRIPTION
**Pull request by JMWTurner**
xeno
- Excavation Tools lockers are now secure, and have new sprites

### CODE REVIEW

**Comment by ghost** [comment]
> Adding wrenches and locking the tools away

Now this is starting to go from 'reworking a dead/untouched job' to giving free stuff for convenience

**Comment by JMWTurner** [comment]
> reworking a dead/untouched job

I take offense to that.

Furthermore, wrenches are the second most used tool by xenoarchaeologists right after pickaxes.

**Comment by ghost** [comment]
Hence there's a toolbox on box outpost and tools in the maintenance sections of most of the research outposts, and if those aren't available, use the autolathe in R&D to print off a wrench before you go. A little interaction usually hurts, but sure beats playing the game like it's single player and having everything in one place, limiting the potential for variance

And locking away the tools is coming across as wanting to limit xenoarchaeology specifically to xenoarchs only, especially considering you put the excavation gear orderable from cargo behind research access

**Comment by JMWTurner** [comment]
Point taken, I'm removing the wrench.

> And locking away the tools is coming across as wanting to limit xenoarchaeology specifically to xenoarchs only

Well disregarding that I'm only giving the locker the same access restriction as the door to the room that contains it, that's like saying that locking hatchets in hydroponics lockers limits beekeeping to botanists only. It doesn't. There are ways around it. You can politely ask, or you can break the locker open. Either way, I've seen miners break that window into the research outpost one too many times.

And one last thing. If you wanna do xenoarch, you can always go ask the HoP to make you a scientist.

**Comment by jknpj** [comment]
Aren't there 3 wrenchs literally outside of the locker room?

**Comment by JMWTurner** [comment]
Yeah that's also why I removed it from the locker last commit.

My judgement was based on the fact that mappers might forget to place wrenches near the lockers in future maps.

**Pull request merged**
