### PR TITLE
adds lemon juice to the booze dispenser

### PR DESCRIPTION
**Pull request by SonixApache**
I see no real reason not to have this in there. It's thematic, it's needed for a 7 drinks, lime juice is already in there. 
Inter-departmental necessities? Botanist union complaints? Bah.

Tested.

:cl:
 * rscadd: Booze dispensers now stock lemon juice.

### CODE REVIEW

**Comment by jwhitak** [comment]
Time to rememorize the gargle blaster recipe again!

**Comment by PrimeDSS13** [comment]
botanist nerf

**Comment by Exxion** [comment]
> Time to rememorize the gargle blaster recipe again!

There's no lemon juice in it

**Comment by Exxion** [comment]
Also, more bartender powercreep
Back in my day, we used the Booze-O-Mat, and we liked it

**Comment by falcon2346** [comment]
Perhaps it should require a higher tier of scanner than it starts with to produce lemon juice? That still encourages inter-department cooperation, but it means you can cooperate either with science or botany to get your lemons.

**Comment by SonixApache** [comment]
> Also, more bartender powercreep Back in my day, we used the Booze-O-Mat, and we liked it

There's no lemon juice in there either. I could add some, I guess.



> Perhaps it should require a higher tier of scanner than it starts with to produce lemon juice? That still encourages inter-department cooperation, but it means you can cooperate either with science or botany to get your lemons.

Code doesn't easily support adding chems for lesser upgrade levels, just t4 parts which is a little much for lemon juice. I could *add* that support, but this was intended as a quick and easy change.

**Comment by beesil** [comment]
Putting it in the booze-o-mat in limited quantity would be less powercreep, but I still don't like it.

**Comment by TrashFiend** [comment]
Could be worth balancing it out a bit by removing access to tomato juice. Only 4 drinks (and lasagna) use it, but it'd swap out a juice instead of adding one. It would make the Doctor's Delight harder to get unless the recipe is changed, but that may not be a bad thing.

**Comment by Hinaichigo** [comment]
In general the reagent dispenser system seems like it could be reconsidered. You can just bring 5u of enzyme in a glass to the dispenser and get enough cheese to feed the entire crew for the whole shift in 5 seconds. And same with chemistry; you have an unlimited supply of chemicals just standing in one place.

**Comment by SonixApache** [comment]
okay, suggestions for the downboaters, emoji this post
🎉 move lemon juice to T2 / T3 upgrades
🚀 move all the juices to T2 / T3 upgrades (including lemon juice)
😄 add 1 carton of lemon juice to booze-o-mat (combine with 🎉 or 🚀 )
❤️ remove from boozemachine, add 1 carton of lemon juice to booze-o-mat
👀 remove all the juices, add 1 carton of lemon juice to booze-o-mat

**Comment by kilozombie** [comment]
Milk should ABSOLUTELY not be available in the dispenser. It didn't used to be that way and it's shit for balance. Why spend time ranching cows or using the biogenerator when you can get infinite milk for free directly into a beaker? Awful, awful design.

**Comment by Exxion** [comment]
Adding the booze dispenser roundstart was the beginning of the descent. It turns bartender into Chemist 2. Bartending was originally distinct due to having to manipulate containers instead of just clicking buttons.
Milk isn't in the booze dispenser. It has always been in the coffee dispenser, but the coffee dispenser hasn't always been present at roundstart.
I always liked getting the dispensers as an upgrade every once in a while, but they should be upgrades, not available at roundstart.

**Comment by wotisjanitor** [comment]
I think the scope of the PR is rapidly changing. Booze Dispenser and Coffee Dispenser being available roundstart is really polluting this question. I'd like to see a PR to remove roundstart dispensers and instead have them available from science.

**Comment by wotisjanitor** [comment]
Oh and also, if they are only available from science, it may be more acceptable to have the juice in them. Also,,,,,, it has cometo my attention that the dispensers are available from cargo, and if people want these things removed roundstart, I feel like it follows they should be removed from cargo as well, otherwise instead of roundstart dispensers, its dispensers after 5 minutes of ordering them from cargo. Kinda just an annoyance

**Comment by beesil** [comment]
Locking the dispensers behind the department notorious for lack of cooperation is a stupid idea that's only going to frustrate players. Bartender is an rp job, and fine as is.

**Comment by DeityLink** [comment]
To me it being an RP job is all but justification for cutting extra potential interactions with another department.

Personally as a bartender, Booze-O-Mat is all I need. I only use the other dispensers to get drinks that you can get from vending machines that require money.

**Comment by beesil** [comment]
I'm ambivalent about removing the roundstart machines and having them be something you have to order from carog again, if we want more departmental interaction again (albiet shallow).

**Comment by bungofungo** [comment]
Fearing for my life as coders look towards my completely mundane roleplaying job and how to "balance it". 

Anyways lemon and berry juice are fine right now, being things that a bartender has to go through botany for. If they absolutely must be added to the bartenders arsenal, add them in limited number to the booze vend or lock them behind an upgrade of some kind. I don't see any point in buffing, or removing the existing roundstart dispensers unless something really cool took their place. I use them to rapidly make drinks for lots of people, and I use the booze vend for other things, bottles will see more use again if deity's bottle flipping PR goes through, simple as.

**Comment by Hinaichigo** [comment]
Every job is an RP job.

Having the drink ingredients require some sort of interaction beyond the bar gives the drinks, the act of making the drinks, and the act of serving the drinks more significance. The lemon juice gains something, the bartender can see the lemon tree in his mind, remember the smiling face of the botanist as she brought in the lemons. It makes his anger as the drunken patrons smash each other with the still-full glasses all the more deep.

**Comment by Exxion** [comment]
> I think the scope of the PR is rapidly changing. Booze Dispenser and Coffee Dispenser being available roundstart is really polluting this question.

I know. I just wanted to complain.

> I feel like it follows they should be removed from cargo as well, otherwise instead of roundstart dispensers, its dispensers after 5 minutes of ordering them from cargo. Kinda just an annoyance

Their *circuits* are available from cargo. You still need parts from science. It takes some nonzero effort to get them quickly.

> Fearing for my life as coders look towards my completely mundane roleplaying job and how to "balance it".

Bro I probably had the greatest number of bartender rounds of anyone before you started playing

**Comment by bungofungo** [comment]
> Bro I probably had the greatest number of bartender rounds of anyone before you started playing

Relax dog, I'm just poking fun at the github balance theorycrafting, wasn't an attack to discredit your hours as a fellow bartender or anything. 

Besides, I agree that adding new juices to the dispensers is a bit much, and currently the way milk functions in the brewery is questionable. I think it's worth looking into for some changes but I just don't agree with a complete removal of the machines, at best this is an issue left to some small adjustments for now.

**Comment by Blithering** [comment]
I don't see any reason why the cargo crates shouldn't have the required stock parts to make the dispenser, the incubator crate does. This tangent is getting even more tangential.

**Comment by SonixApache** [comment]
> Their _circuits_ are available from cargo. You still need parts from science. It takes some nonzero effort to get them quickly.

cargo brings you flatpacks that you can just unpack into the machines

**Comment by Exxion** [comment]
> cargo brings you flatpacks that you can just unpack into the machines

Oh, you're right. I guess it was changed at some point.

**Comment by Kurfursten** [comment]
Lack of support + I stand with botany

**Pull request closed without merging**
