### PR TITLE
Improves the spawn command

### PR DESCRIPTION
**Pull request by unid15**
Placing a period at the end of the path prevents subtypes from being listed

spawn "carbon/human" -> brings up a list with 9999 subtypes of /mob/living/carbon/human

spawn "carbon/human." -> spawns a human

fa

### CODE REVIEW

**Comment by Probe1** [comment]
I don't care if you put it here http://ss13.moe/wiki/index.php/Understanding_SS13_Code here http://ss13.moe/wiki/index.php/SS13_for_experienced_programmers or even here https://github.com/d3athrow/vgstation13/wiki but add it somewhere.

The best time for us to have started writing all this down in a place that can be found was 3 years 8 months and a few days ago.  The second best time is right now.

**Comment by Probe1** [comment]
Oh right I was totally gonna look at the spawn menu and increase its width since you can never see the full path of shit.  Do that if you feel especially motivated.

**Comment by PJB3005** [comment]
You can't.

The input window spawn uses is a native BYOND list input. There's nothing we can do other than making a HTML based version and using that, but that will choke on large lists because > IE. Same thing as the game panel being Shit.

There's no winning this.

**Comment by Probe1** [comment]
🔫

**Comment by ComicIronic** [comment]
Bravo quality.

**Comment by unid15** [comment]
@Probe1 didn't find anything about *spawn* on the wiki so I put it here http://ss13.moe/wiki/index.php/Starter_Guide_to_Admin_Tools#Important_verbs , and in the verb description

**Comment by Probe1** [comment]
Checkbox has been checked.

**Review by Probe1 — APPROVED** [review]

**Pull request merged**
