### PR TITLE
Fire axe sound plus deff airalarm

### PR DESCRIPTION
**Pull request by liltiptop**
Adds a fire axe hitsound and more firelocks along with another air alarm on deff's aft primary hallway.

### CODE REVIEW

**Comment by Exxion** [comment]
M A P   C L E A N E R

**Comment by liltiptop** [comment]
I did do the mapcleaner.
edit: kill me.

**Comment by liltiptop** [comment]
I'll be back. when I hopefully unfuck the map

**Comment by Probe1** [comment]
You'll get it.  We've all been here, we've all been frustrated and everyone you talk to in irc or here overcame it.

**Pull request closed without merging**
