### PR TITLE
You feel everything shaking around you!

### LINKED ISSUE #16732: You feel the stations structure shaking all around you on the asteroid
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
23b20ae8ccf3e904f0535f2452c4e02685801757

# Description

Explosions on the asteroid give you the "You feel the stations structure shaking all around you" even though you are on the mining asteroid and there is no station
# Steps to Reproduce

Set off explosion on the asteroid, get red text
# What you Expected

Not to be mining some sort of artificial station roid
# What Actually Happened

Immersion shattering text

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[grammar]

## What this does
changes this lines from explosions away from station structures when not on them
Closes #16732.

## Why it's good
they don't always happen on station

## Changelog
:cl:
 * spellcheck: The "you feel the station's structure shaking all around you" line has been changed to be more general when not actually on station, remaining the same while on it.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
would it be better to keep the line if you're actually on station?

**Comment by DamianX** [comment]
yeah sure

**Comment by githubuser4141** [comment]
Even if you're on the asteroid, isn't the asteroid directly connected to the station structure or, at least could be considered a small mining station? It's held together by metal truss and scaffolding.

**Comment by DamianX** [comment]
I think that's just your headcanon

**Comment by SECBATON-GRIFFON** [comment]
> yeah sure

done

**Comment by SECBATON-GRIFFON** [comment]
still seems to be a hated change

**Comment by DamianX** [comment]
I've seen no one say why it's a bad change, though!

**Comment by SECBATON-GRIFFON** [comment]
> I've seen no one say why it's a bad change, though!

something sovl or immulsions probably i dunno
and what githubuser said

**Pull request closed without merging**
