### PR TITLE
Fixing some typo's that Intigracy didn't notice.

### PR DESCRIPTION
**Pull request by SysadminJeroen**
_cough_ #9329 _cough_

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Who or what wrote this stuff on the first place?

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis Let me `git blame`.

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis I know who at least one person was.

```
fc6dfae6 (Dizor             2015-10-14 21:18:49 -0500 253)                      name = "\improper Nausiating Glow in the Dark Velvet Wizard Poster"
```

**Comment by 9600bauds** [comment]
> typo's

**Comment by SysadminJeroen** [comment]
@9600bauds GET IT?!

**Pull request merged**
