### PR TITLE
(Revival) Mini-station vault

### PR DESCRIPTION
**Pull request by ghost**
Revival of #20964, but with finished atmospherics and the job spawns replaced with space hobo ones.

image

Should further prove that I am somehow MadmanMartian all along.

## THINGS TO ADD FROM COMMENT:

- [x] Also botany needs a biogenerator and seed extractor and you might wanna consider a microwave and other kitchen tools such as a food processor and a condimaster.
- [x] Consider solars. PACMAN generators are limited in power production due to lack of plasma.
- [x] APC for every room/section. RCD might be wise. Maybe a nearby asteroid/pickaxe so engineering can do 'something' and have a way to expand the vault?
- [x] Consider a small shuttlepod/destination disc.
- [x] Consider gas miners of the oxygen and nitrogen varieties so the engineer can tinker with atmos and have gas to replace lost air in the event of breaches.
- [x] Consider a bar/bar machines.
- [x] Consider exterior scaffolding for navigation and aesthetic.
- [x] Firelocks.
- [x] Consider more exterior windows. Consider said windows with firelocks.
- [x] Consider a circuit imprinter circuit and old-R&D console circuit.

:cl: 
* rscadd: A new vault resembling a small station can be found in space. You may even find people on it occasionally.

### CODE REVIEW

**Comment by SootyBear42** [comment]
This is kinda what I wanted Space Hobos to be

**Comment by Optimism333** [comment]
> Revival of #20964, but with finished atmospherics and the job spawns replaced with space hobo ones.
> 
> 🆑
> 
> * rscadd: A new vault resembling a small station can be found in space. You may even find people on it occasionally.

Please do post a screenshot of the finished vault when you can.

**Comment by ghost** [comment]
> 
> Please do post a screenshot of the finished vault when you can.

Added one of it so far @Optimism333

**Comment by Eneocho** [comment]
Are those machine frames and circuits for RnD? If not, please add some RnD.

**Comment by ghost** [comment]
> Are those machine frames and circuits for RnD? If not, please add some RnD.

The todo list mentions those circuits being for RnD so yes.

**Comment by Kurfursten** [comment]
>Jukebox is area based
>This vault is composed of a ton of tiny areas so it won't be able to be heard more than a few tiles

**Comment by jwhitak** [comment]
Thumbs up. My thoughts about this PR:

* Hobos may get the roid bum treatment or they may get the premium space life squatting in a luxurious mini station. Playing luck when you push the hobo button now... I like this. If more hobo-allowed vaults are a thing, this could get real funny real fast.
* A dorms equivalent for the poor staff of this tiny hell hole would be nice. They've got all the departments covered except an actual place to sleep or use the restroom.
* Light switches?
* There are food vending machines but hobos do not have accounts or money to use with them. Guess they gotta grow their food! Or, hack the machines to shoot food, and then make monkeys out of monkey cubes from botany.
* There's a shuttle port so an admin allowing a bus to this station and back is fairly easy. You could do a destination disk as mentioned in comments so anyone who discovers this vault can go here with a shuttle.

**Comment by Viciousaurus** [comment]
Not mini enough

**Comment by Eneocho** [comment]
The picture shows 2 RnD circuits and 4 machine frames. You need at least 3 RnD Circuits (Destructive Analyzer, Circuit Imprinter, Protolathe), one RnD console circuit and at least 1 console frame, else the science part of the vault can't work (since you could not research anything).
Also, possibly a robotics machine to make your own vaultside borgs.

**Comment by Kurfursten** [comment]
Is there any good reason to have this as a bunch of tiny 25-tile areas instead of one to three larger areas?

**Comment by Eneocho** [comment]
> 
> 
> Is there any good reason to have this as a bunch of tiny 25-tile areas instead of one to three larger areas?

APC zone fuckery probably.

**Comment by SootyBear42** [comment]
Is there gonna be any lore for why there's a tiny station, like it's a back up or something?

**Comment by Eneocho** [comment]
> 
> 
> Is there gonna be any lore for why there's a tiny station, like it's a back up or something?

The Unofficial Lore(TM) is that the space hobos stole some RnD machinery and built everything in deep space.

**Pull request merged**
