### PR TITLE
Vending machine pixel fix

### PR DESCRIPTION
**Pull request by Lokiamis**
Once upon a time some asshole accidentally left two pixels the same color as DM's default mask color on a vending machine which caused every other asshole with a box select tool to confuckulate the problem. Did you know the chaplain's vending machine has 91 frames of animation?

Before/after
untitled

### CODE REVIEW

**Comment by Kurfursten** [comment]
Before/after in this case would make more sense if you actually had an in-game shot since we're dealing with transparency

I know that sucks to ask for but you already sat through 91 frames of pietyvend

**Comment by PJB3005** [comment]
Holy shit yes thank you so much.

As for pietyvend I'd have just used a python script.

**Comment by Lokiamis** [comment]
Jokes. Here's a real comparison.
untitled

**Comment by NigglyWiggly** [comment]
Next you're gonna say you're fixing the fact that the tea vending machine has a bunch of transparent pixels right in the center that look like they are just part of the design because the colors fit and no one else seems to notice it.

**Comment by Kurfursten** [comment]
Nice try sneaky elocutioners

**Pull request merged**
