### PR TITLE
Rags now work as bandages

### PR DESCRIPTION
**Pull request by SonixApache**
I tried to make it so they didn't actually heal, but it seems that as soon as a wound stops bleeding, it starts to heal.
Rags can't be used for repairing internal organs.

🆑 
 - tweak: Rags can now be used to stem bleeding.

### CODE REVIEW

**Comment by Hoshi-chan** [comment]
Out of curiosity, how are they made?

**Comment by Irradiation** [comment]
@Hoshi-chan Apply [knife] to bedsheet.

**Comment by SonixApache** [comment]
@Hoshi-chan @Irradiation Only with a scalpel, kitchen knife, butcher's knife, plastic knife or glass shard.
I'm fixing that now, and I intend (read: never gonna happen) to add 'cut-a-rag' functionality to jumpsuits.

**Comment by Hoshi-chan** [comment]
Should make it so you can do more stuff with them, too. 

Aim at hands or feet with harm intent to tie someone up (shoddy hand/leg cuffs), wear on the eyes for a blindfold, wear on the mask slot for a gag, nothing special required to remove them, just that your hands are free.

**Comment by Blithering** [comment]
I think bedsheets at least can already be used for tying people up, not sure about rags though. Does this mean you can accidentally bandage someone while trying to smother them with a rag?

**Comment by SonixApache** [comment]
Nah, smothering only works on the mouth, and bandaging only works on anything but the mouth.

**Pull request merged**
