### PR TITLE
Makes lasers have a travel time

### PR DESCRIPTION
**Pull request by Coxswain-Navigator**
Still faster than a bullet, but not instantaneous anymore.

:cl:
 * tweak: Lasers now have a travel time. They are still faster than a bullet, just not instant.

### CODE REVIEW

**Comment by SGuivenne** [comment]
Is this true with #20795 ?

**Comment by Accipitermaris** [comment]
https://youtu.be/b3ICv32DZSw?t=2m18s

**Comment by SonixApache** [comment]
why

**Comment by Tehsapper** [comment]
for what purpose

**Comment by Chazach** [comment]
PR that saved /vg/
point'n'click laser supremacy is shit and boring

**Comment by DeityLink** [comment]
It's fucking light.
If anything laser damage should be reduced to something like 20-25

**Comment by Accipitermaris** [comment]
If lasers shot by laser guns should have an instant travel time because of an accuracy clause then fired bullets would ought to have an instant travel time* under the same clause.
*This obviously isn't accurate but it would be more accurate for station engagements than really-really-fast-byond-projectiles

**Comment by ShiftyRail** [comment]
Why not have lasers being slightly deflected by windows as they actually do in real life

**Comment by Blithering** [comment]
I would say keep lasers instant travel time, but have a more extreme damage falloff on targets wearing armour, so lasers are almost guaranteed chip damage, but you need ballistics for cracking hard targets

**Comment by Killette2** [comment]
Either make bullets instant because being able to dodge a bullet should be impossible or pull the "instant" argument out of your ass and realize that non-instant lasers in the past were better and had none of the bullshit that makes them the prominent combat weapon they are now.

**Comment by Intigracy** [comment]
bullets are faster instead

**Pull request closed without merging**
