### PR TITLE
Sounds

### PR DESCRIPTION
**Pull request by IratePirate**
Energy sword now has a melee attack sound, same with toolbox and glass shard.

TOOLBOX DAMAGE INCREASED FROM 5 TO 8 (and syndi to 10). This thing has been piss weak for far too long, the reign of Bay ends now. You can't even put it in a backpack so why not buff it so it isn't weaker than a set of wirecutters (which does 7) ?

-energy sword hit sound
-toolbox hit sound
-toolbox made more robust
-glass shard has a hitsound
-welder hit sound fixed up

### CODE REVIEW

**Comment by ComicIronic** [comment]
You really shouldn't wrap content with balance changes, because it just delays both.

**Comment by PJB3005** [comment]
:+1: for the toolbox buff

**Comment by CptWad** [comment]
:+1: :+1: Yes

**Comment by A4Brogan** [comment]
This pleases me.

**Comment by FudgePucker** [comment]
|>tool box does 8 damage
|>not 50
Shit PR dnm

Jk good job, robust coffee will be more robust now.

**Pull request merged**
