### PR TITLE
Ian Behaviors Raised to Corgi Level

### PR DESCRIPTION
**Pull request by Kharkov72**
#22746 made Ian able to do a lot more stuff. However, there are two problems.
1. This meant other corgis couldn't do things as they were locked to ian, such as chasing and eating food (rip corgi engines)
2. A feature which was ripe for stupidity was locked to only a single mob, instead of all corgis.

Being able to point them to places, have a swarm of corgis power the station or eat the chef's cooking, and whatnot should be able to be done by ALL corgi and corgi subtypes, not just Ian.
At the very least I want to fix the bug that other corgis can't eat food though.
[bugfix] [oversight]
Also it works on my machine

:cl:
 * rscadd: Now EVERY corgi and corgi subtype is a very good boy.

### CODE REVIEW

**Comment by DamianX** [comment]
False advertisement, expected datums

**Comment by Exxion** [comment]
Actual real command datums would be cool but that's very much a WYCI matter

**Comment by ghost** [comment]
I feel like this makes Ian a little less special, though. But it does have some potential to it.

**Comment by Kharkov72** [comment]
ALL corgis are special

**Pull request merged**
