### PR TITLE
Medical Priority Rewards : take 3

### PR DESCRIPTION
**Pull request by ShiftyRail**
Revives #28501, doing the few changes Sonix didn't want to do and fixing a few conflicts.
Text pasted from the original PR.

Geneticist, Chemist, Virologist, CMO, MD, Paramedic
image

Mostly copied from #24633 as I believe @Kurfursten had good ideas as usual - but with some added flair from me.
lifeline can idea by toucan
Changes:
 - All medical staff now gets a can of Picomed Red, White or Cryo. The can is filled with Lifeline with a slight addition for taste. The cryo can has an overlay that changes depending on how much is left inside. Adorable sprites by @beesil.
 - Geneticist: remotesay injector
 - Chemist: box containing 1 electrolyzer, 1 high cap cell, and 2 flasks + can of Mann's Drink
 - Virologist: 1 random virus dish
 - CMO: a straightjacket
 - Paramedic: nothing !
 
 I was gonna do some other stuff but I mostly forgot and also ran out of codermana.

🆑 
 - rscadd: Medical staff now gets slightly better high-priority rewards.
 - imageadd: Picomed can sprites by Basil

### CODE REVIEW

**Comment by help-maint** [comment]
Latejoin chemists could really use 5u plasma in case of lateround gunk

**Comment by ghost** [comment]
I'm not sure if extra access is a good idea but the others are very needed

**Comment by beesil** [comment]
Medical priority awards are long needed & I'm glad to see the drink sprites being implemented. I'm a bit hesitant towards more paramed access-creep though and I don't think the straightjacket will be very useful to a CMO (the one in storage is rarely used).

**Comment by RaccoonBro** [comment]
Could make Paramedic access conditional maybe? If there's a virologist already, then no virology access for example

**Comment by PrimeDSS13** [comment]
I wouldn't do access. It's a bit of a stretch.

**Comment by ShiftyRail** [comment]
updated the paramedic rewards, will code it out too in a bit

**Comment by Eneocho** [comment]
I'd change the geneticist's free gene syringe with a randomized one that has some blacklists (no roundstart hulk or roundstart xray, for example) since remotesay is so rarely useful over a radio.
Like help-maint says, some plasma would be a godsend to latejoin chemists, perhaps a 20u plasma pill?
The virologist's random virus dish should either have some good (and hard to get) symptoms or have some rare antibodies (X and Z?) to make it good, else it's just another dish you can make in 20 seconds with some mutagen.
Same with the CMO's Straightjacket, you already have some at roundstart in medical storage, so it feels cheap, perhaps 5u of nanites instead?
The Paramed Access is cool and they deserve to have some, though I agree on that it should be conditional to whether or not the corresponding job is already filled.

Also, please tell me you can get the picomed drinks from the medvendor if you hack it/pay a coin.

**Comment by ShiftyRail** [comment]
@help-maint done.

@Eneocho True that a fixed power is kind of lame, that can be fixed.
>5u of nanites instead?

No way, those are way too strong.

Paramedic extra access feel redundant now that those big boys can access surgery for free.

**Comment by Eneocho** [comment]
> 
> 
> > 5u of nanites instead?
> 
> No way, those are way too strong.

They need something good to be worth the join though. 5u mednanos? (1u nanites turns into 5 mednanos, btw)

**Comment by help-maint** [comment]
No mednanos for the love of God

**Comment by ShiftyRail** [comment]
No mednanobots either, no.

**Comment by beesil** [comment]
Spitballing some alternate reward ideas that I think would be fun or useful:
- An advanced bruise/burn pack (Paramed/MD/CMO, too strong?)
- An advanced medkit (CMO)
- Extra biofoam injectors (Paramed/CMO, these don't usually run out, but very useful to have)
- Pill bottle of trailmix or time release capsules (CMO/MD/Chemist)
- Soap/cleaner spray (MD/CMO)
- Basic reagent scanner or chem PDA cartridge (MD/Paramed, CMO and Chemist already have one)
- Monkey cubes (Geneticist/Viro)
- Mouse cubes (Viro)
- Lollipop synthesizer (CMO/MD, maybe too snowflakey)
- Bag of lollipops (MD/CMO)

**Comment by Blithering** [comment]
Bag of lollipops sounds cute without being game breaking.

**Comment by APCUnlocked** [comment]
Give paramedics a normal reagent scanner or something, feels weird for everybody else to get toys but not them.

**Comment by help-maint** [comment]
Advanced medpack sounds better for paramed than CMO really

**Comment by Eneocho** [comment]
> 
> 
> Advanced medpack sounds better for paramed than CMO really

The problem is what can you give priority CMOs that they don't already have access to at roundstart? They can already get the biofoam injectors from paramed, chems from chemistry, virology stuffs from virology, etc. They even have access to the hypospray. What can you give them that doesn't feel cheap or overpowered?
Mednanos are overpowered, advanced medical kits feel cheap considering science can print them a dime a dozen with nominal research and materials. Time release capsules you can get for free if you nab the silver coins (or just pay 75 per choco coin). Etc.
An option would be rare medical chems like peridaxon or rezadone (but again, these are a tad overpowered). 
Alternatively, just abandon the idea of giving the CMO a medical related item and just give it a fluff item that has SOME use, like a lollipop synthetizer that can be filled with some chems which then dispenses chem-containing lollies.

**Comment by SonixApache** [comment]
thanks for picking it up, the sprites deserve it :+1:
i was working on adding a bag of medipops for CMOs but i lost steam halfway through refactoring lollipops to facilitate it

**Comment by beesil** [comment]
> The problem is what can you give priority CMOs that they don't already have access to at roundstart? 

The majority of priority rewards are items that the job can easily find around their workspace. It isn't meant for giving out otherwise unobtainable loot, but rather making it more convenient for them to gear up. Here are some of the priority rewards for other jobs as a point of reference:

- Engineer: Pre-equipped mesons and insulated glubbs.
- Roboticist: Extra synthetic flash.
- Warden: Coffee and a donut.

**Comment by Blithering** [comment]
Agreed, other than the little flavour items like badges and snacks, it's mostly stuff that's convenient to get you started quicker, rather than exclusive stuff they'd otherwise not be able to get.

**Comment by GreatBigFailure** [comment]
For geneticist I'd say replace the syringe with a crumpled note that says "random block good/bad" based on what it is. So it's just somewhere to start or skip and could be anything.

**Comment by Eneocho** [comment]
> 
> 
> For geneticist I'd say replace the syringe with a crumpled note that says "random block good/bad" based on what it is. So it's just somewhere to start or skip and could be anything.

Yeah, this sounds good. The paper could say something like "dont tell the cmo but block [number] is some of that good shit -a friend from centcomm". It'd be explained IC as a note slipped in there by a centcomm geneticist.

**Comment by DrSnips** [comment]
A M.O.T. and CLOT (the advanced surgery tool for biofoam) might be decent options for paramed.

**Comment by Eneocho** [comment]
> 
> 
> A M.O.T. and CLOT (the advanced surgery tool for biofoam) might be decent options for paramed.

This. Dear gods, this.

**Comment by ShiftyRail** [comment]
There, paramedic has a clot, geneticist has a random injector, and everyone get a lollipop.

**Comment by DrSnips** [comment]
A quick thing to note. The clot only really does something for them with a reliable surgery table. Hence why I suggest both.
Could they acquire one in the round? Yes, but it kind of makes their reward a bit useless at the start.

HOWEVER
I've been thinking over the idea of removing the surgery requirement and making it so you can use it anytime. Which also solves the last notion above.

**Comment by ShiftyRail** [comment]
A roller bed works as a makeshift surgery table.

**Comment by DrSnips** [comment]
There's a reason why two different versions exist. One works without question, the other only works a small chance of the time with no feedback that it failed because it was just by chance.
I'm probably going to go through with my revision of the CLOT's ability so no point in me arguing this.

**Pull request merged**
