### PR TITLE
Repeat wire for autolathes

### PR DESCRIPTION
**Pull request by unid15**
Adds a fourth wire to autolathes, the repeat wire
Using the repeat wire you can make an autolathe manufacture a design infinitely by itself, as long as it has enough materials.

If the repeat wire is cut, the manufacturing process can't be stopped manually - you will have to find a way to shut the autolathe down, like by cutting equipment power in the area.
If the repeat wire is pulsed, the manufacturing process can be stopped by interacting with the autolathe's interface again.

### CODE REVIEW

**Comment by ComicIronic** [comment]
I am in the middle of rewriting the autolathe completely, so you might want to wait.

**Comment by 9600bauds** [comment]
Damn, this is a really good idea and the code looks neat. Wish this had come earlier though, since the Autolathe is being worked on already.
Would be great to have this even after the Autolathe gets queueing capability, having the 'lathe keep making stuff until you come back sounds great.

**Comment by Shadowmech88** [comment]
This would be a neat feature for any production machine. Would make matter cartridge production via general fabricator a bit less tedious.

**Comment by ComicIronic** [comment]
RIP this PR?
It should be easy enough to add to the proper wiring system now.

**Comment by Unfit** [comment]
Well the main intention of this PR was to add a way to create a lot of stuff (like machine parts/beakers) without manually clicking a button every 10 seconds
Now that the autolathe has a queue, RIP I guess

**Pull request closed without merging**
