### PR TITLE
More Items can be held by Champion Belts

### PR DESCRIPTION
**Pull request by Kharkov72**
ATM it only holds lucha masks, but now, IF YOU WANT TO NUKE MY STATION, YOU'RE GONNA NEED TO BEAT ME IN THE RING
also now holds golden cups, so you can hold your champion cup in your champion belt while you take champion sips
[tweak]

:cl:
 * rscadd: Champion Belts can now hold the nuke disk and golden cups

### CODE REVIEW

**Comment by utilitas-** [comment]
While at it, make them hold the golden cup. It makes sense.

**Comment by utilitas-** [comment]
Shitty worn and item sprites for the belt with the nuke disk.

champ

**Comment by Kurfursten** [comment]
Are you going to change this to use the special sprites if the disk is loaded?

**Comment by Kharkov72** [comment]
I don't plan to myself, sprites are not my strong suit

**Comment by Kurfursten** [comment]
you would just make an update_icon() that checks contents and, if it contains the disk, sets the alternate icon_state and item_state

Still I won't force you to do something just because someone handed you a sprite. They can code it themselves.

**Pull request merged**
