### PR TITLE
Better Command Report

### PR DESCRIPTION
**Pull request by Kurfursten**
untitled

I told Shifty I think we're mature enough to handle a more accurate command report. Let's see if the emojiocracy agrees with me. There are 6 possible report descriptions. I'll save you the fluff and give you the mechanical meaning. In parenthesis, approximate rate of occurrence.

**Peaceful Waypoint**: <20 starting threat, no roundstart antags
**Core Territory**: <20 starting threat (6%)
**Anomalous Exogeology**: 20-39 starting threat (25%)
**Contested System**: 40-65 starting threat (43%)
**Uncharted Space**: 66-79 starting threat (18%)
**Black Orbit**: 80+ starting threat (8%)

I feel like this is happy medium between 'too much preparation' and 'so worthless you may as not even read it'. For reference to anyone not familiar, the old system works like this:

* If start threat<50, randomly choose Core Territory or Contested System (equal chance) 
* If start threat>50, randomly choose Contested System or Uncharted Space (equal chance)

The breakpoint of 50 is so vague as to be hardly worth knowing, and if you get the "middle" result the command report was entirely worthless. Contested could mean anything from 1 to 100

🆑 
* tweak: The command report at roundstart has received an aesthetic facelift and is now much more accurate in threat prediction.
* tweak: The command report is now received after 10-18 minutes.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
**BLACK ORBIT**

**Comment by ShiftyRail** [comment]
While the fancy HTML is nice and the words are much better, I would rather not have the "oh shit the paper says it's over 80 threat better rev up those robocop borgs and hide the disk in a disposal loop"

**Comment by Kurfursten** [comment]
Let's imagine every 8% of shifts that roll 80+ threat the captain starts cooking up hairbrained places to hide the disk like inside the clown's stomach in disposals below the shard in an active SME, and every single one of those 8% of rounds turns out to be ops (nigh impossible). Is that... such a bad thing? Sometimes ops will have to contend with a zany defense the crew threw together because they were on edge? And of course there will still be plenty of shifts where the crew *isn't* prepared because the report came back showing 30-40 threat, about 3x as often.

I think it's worth giving a shot.

**Comment by DeityLink** [comment]
Remember that Threat is balanced to generally hang around 50%. I think it's a bit weird that most stations that are about research would be in "contested territory".

Allow me to suggest a different distribution:

0 - 20 = **Peaceful Waypoint** (I think we shouldn't spoil whether there are antags at all)
20 - 40 = **Core Territory**
40 - 60 = **Anomalous Exogeology** (I think we shouldn't spoil whether we're straight above or bellow 50)
60 - 80 = **Uncharted Space**
80 - 100 = **Black Orbit**/**Contested Territory**

I like the idea overall though. I agree it's an obvious source of metagaming (as in, actual metagame) but I'd like to see if it helps increase the quality of the rounds.

A compromise would be to give the report a -20,+20 threat inaccuracy.

**Comment by DeityLink** [comment]
A good idea by @dylanstrategie is that the report should now be delayed by 10-20 minutes at least so antags have time to set up, and all players have time to get involved with the round.

**Comment by DrSnips** [comment]
I would pick and choose between the +/-20 or the delay to not make the report too watered down. While you could say both can cause meta gaming to whatever extent I'd rather have the delay so it's used to accurately act rather than incorrect mass lynching. It also would be a better reflection of the round due to the post round start rush of arrivals.

**Comment by Kurfursten** [comment]
I think the delay is not a bad idea, it gives command more reason to look in on the bridge. Maybe 18 minutes though, just to duck in right under the earliest midround injection.

For fluff reasons, maybe "Border System" makes more sense than "Contested System" with the description text

**Pull request merged**
