### PR TITLE
Yet another defficiency update I'm doing for free when I could have w…

### PR DESCRIPTION
**Pull request by Duny-**
…orked and gotten money instead

- Fixed disposaled items not landing on the mass driver, effectively preventing disposing of them due to the particular way deff's disposals work.
- Added a space cleaner bottle in chemistry and a bar of soap in surgery.
- Replaced the windows on the right side of the toxins launch room with walls, to avoid the windows breaking upon being hit by whatever the disposal outlet launches at them (usually corpses).
- Replaced the old firelocks on the research outpost with the new ones.
- Made the Nanotrasen-approved Maintenance Path Indicators unmovable.
- Added a cyborg recharging station in the bridge.
- Added three gadget bags and ten sheets of plastic to R&D.
- Removed all points of sale and EFTPOS scanners.
- Added a camera in the new science entrance.
- Removed the closet and moved the body bags in cloning to genetics to make cloning less cramped.
- Added two mining vending machines and an ATM to the mining outpost, repurposed the room in cargo to a delivery/storage room from which cargo techs can take the ores the miners bring from the asteroid to deliver to the rest of the station and store drills R&D made for the miners or whatever just be the usual goys and ignore it entirely then complain about it having no point or turn it into some dank disco break room for cargo. Your imagination is the limit.
- Removed the research shuttle entirely and replaced it with break room. The mining shuttle now covers both the mining and research outposts.
ss 2015-11-08 at 06 14 17

- Added two security suit storages units to the armory.
- Added a camera in space near the armory, and security airlocks now have randomized wires. Come at me greytide, I don't give a fuck.
- Added a cute little bathroom in security near interrogation.
ss 2015-11-08 at 06 15 21

- Fixed (maybe, who the fuck knows) getting thrown in illogical directions during pod/shuttle transit.
- Removed a metric fuckton of blind spots in the station's camera network.
- Updated the changelog and made several typos doing it.

Feedback always welcome.

Oh and:
Fixes https://github.com/d3athrow/vgstation13/issues/6459, fixes https://github.com/d3athrow/vgstation13/issues/6458, fixes https://github.com/d3athrow/vgstation13/issues/6423, fixes https://github.com/d3athrow/vgstation13/issues/6415, fixes https://github.com/d3athrow/vgstation13/issues/6354 (maybe), fixes https://github.com/d3athrow/vgstation13/issues/6351, fixes https://github.com/d3athrow/vgstation13/issues/6456, fixes https://github.com/d3athrow/vgstation13/issues/6457, fixes https://github.com/d3athrow/vgstation13/issues/6468.

### CODE REVIEW

**Comment by Probe1** [comment]
That is a cute bathroom.

**Comment by Duny-** [comment]
Nope, maybe in a future DLC.

**Comment by Probe1** [comment]
You are the meanest!

**Comment by Duny-** [comment]
Gotta make a living fam. Be happy I'm not setting up a Patreon and giving out the updates only for the donators and frenchies.

**Pull request merged**
