### PR TITLE
Spell HUD buttons

### PR DESCRIPTION
**Pull request by ComicIronic**
Sprites by Skowron, who is, as always, da best.

Added spell buttons for all spells. This is building on an idea originally put in by Deity, but which was done in a snowflake way and only for constructs.
These spell buttons are generated by handler procs for mobs.
Each spell button has a spell icon, changes with its percentage charge, and can be shown or hidden with the spell master.
The spell master itself can be moved around thanks to TG movable objects.
Constructs now inherit Life(), for sanity and goodcode.
Moved several Harvester procs to spells. (We can do this with ling and vamp too!)
Added Narsie listing so Harvesters don't loop through world.
Replaced a lot of strings in spellcode with defines.

How this looks:
(NEARLY) all the spells and genetic powers. Missing from this image are charge and remote view.
Mimespells
Notice the green backgrounds for the genetic powers. And yes, the faggot is Ei Nath.
For a harvester.
Reap
For a ghost.
Spook

More system changes included:
Turned several mob procs into actual spells.
Added a way for targeted spells to go through all the mobs in the world.

### CODE REVIEW

**Comment by CptWad** [comment]
:+1:

**Comment by Incoming5643** [comment]
Sexy, will probably at least attempt to port this back to /tg/ at some point :+1:

**Comment by RemieRichards** [comment]
Great use of my movable UI elements! :+1: @Incoming5643 you better, you're our wizard guy, spells are your thang.

**Comment by IratePirate** [comment]
God damn man.

**Comment by Probe1** [comment]
@ComicIronic genetic powers will have the same treatment?

**Comment by ComicIronic** [comment]
Yes, genetic powers will also get a button. When ling and vamp powers are ported to spell framework, they will have buttons as well.

**Comment by Probe1** [comment]
Will it be collapsible?

**Comment by RemieRichards** [comment]
@Probe1 looking at Comic's code, it's collapsible/toggle-able

**Comment by Probe1** [comment]
sounds like a good upgrade to me.

**Comment by ZomgPonies** [comment]
We've had action buttons for spells on Paradise for like...a year. Welcome to 2014.

Now properly port the system to support action buttons for ling and vampire abilities and then I'll be impressed.

**Pull request merged**
