### PR TITLE
Removes some awfulness from the code

### LINKED ISSUE #30810: ID card hashes aren't set automatically
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
b575a71b92add50e00eb6a85ae1b02d0ac9ed2e4

# Description
 That's Name's ID Card (Chief Engineer). It is a tiny item.

The card has a faint aroma of autism.

The current assignment on the card is Chief Engineer.

The blood type on the card is [UNSET].

The DNA hash on the card is [UNSET].

The fingerprint hash on the card is [UNSET].

### PR DESCRIPTION
**Pull request by DeityLink**
No memes here.

Fixes #30810 hopefully

Mostly changing proc names so they reflect what they actually do.

:cl:
* bugfix: Fixed DNA not being properly copied when getting cloned, resulting in altered hair styles and colors.

### CODE REVIEW

**Comment by ghost** [comment]
bring back wszhzhzh()

**Comment by DeityLink** [comment]
>proc is called fixblood()

>it doesn't actually fix blood

**Comment by DamianX** [comment]
looks like it makes the tests explode

**Comment by Eneocho** [comment]
I played a round an hour ago and the hairstyle changed after cloning, which this should've fixed. @DeityLink

**Comment by DeityLink** [comment]
perkele

**Pull request merged**
