### PR TITLE
Makes darkness clickable

### PR DESCRIPTION
**Pull request by clusterfack**
Fixes an already closed issue I think

Adapted from https://github.com/tgstation/-tg-station/commit/fea00718a0c889669e07d576cadcccd7fded90c2

### CODE REVIEW

**Comment by 9600bauds** [comment]
!!IT'S HAPPENING!!

**Comment by Exxion** [comment]
MANY THANKS

**Comment by DrCelt** [comment]
:+1:

**Comment by Jeroen52** [comment]
:+1:

**Comment by TermedClepe** [comment]
https://github.com/d3athrow/vgstation13/issues/6493
https://github.com/d3athrow/vgstation13/issues/6508
https://github.com/d3athrow/vgstation13/issues/6753

**Pull request merged**
