### PR TITLE
Diona hair

### PR DESCRIPTION
**Pull request by CodenameB**
This PR will add 8 new hair for Diona players. Some of the hair are static colors, and some allow you to pick the colors. 

All of them are based on the concept of diona growing flowers for hair. You can pick the styles at roundstart or by going to a mirror.

Due to their complexity, multiple colors, and multiple layers, the hairs appear messed up in the preview window, but they work fine in game.

Pickable color
"Big flower"
image image image
"Leafpile"
image image image
"Hanging Flowers"
image image image
"Rosebush"
image image image
"Small Mushroom"
image image image

Static color
"Bluebell"
image image image
"Flytraps"
image image image
"Alien Flower"
image image image

:cl: 
 * rscadd: 8 new hairstyles for diona

### CODE REVIEW

**Comment by jknpj** [comment]
I like the idea but these "hairstyles" are too crazy for me.

**Comment by Shadowmech88** [comment]
I don't think they look very good. A lot of them are just large masses of what seems to be nearly solid color.
Hanging flowers and rosebush look alright. The rest look jarring.

**Comment by Diavill** [comment]
flower creep

**Comment by Ephx1** [comment]
Gonna have to agree with the others, this just looks way too out of place.

**Comment by yclatious** [comment]
>attempting to make waifu hair for trees

Id puke, but im too busy laughing seeing as most of these are literally neon hair.

**Comment by ghost** [comment]
>neon hair

wow...it's almost as if....
image

anything that's not green and/or colorful won't fit on dionas

**Comment by CodenameB** [comment]
If you want fixes, you're going to need to be specific. "large masses of what seems to be nearly solid color" perfectly describe our current hair for humans (Literally, most hairstyles are just a single solid color)

"Crazy" and "out of place" are likewise completely unhelpful.

@yclatious Have you considered learning how to sprite? I'd love to see your solid black and brown flowers, now that would be a good laugh.

**Comment by yclatious** [comment]
Alright, lemme be a bit constructive since you lads always seem to get triggered at me shitting on your stuff even if I shit on almost anything for kicks.

Big flower, blue bell and alien flower just look both too "vibrant" and have colours that pop out too much, trash or tone it the fuck down. Even if we ignore the fact that the last thing dionaes were probably made for or had in consideration was uggu flower hair when someone sprited the brown lump of wood, you can make good hair for them, your hanging flowers and flytraps, maybe even rosebush look alright, but then you got small mushroom whose colour is just both too dead to be easthetic and the shape of it doesn't fit the general hairstyles, aka, small mostly minor shit with rarely ever sprouting out hair like pompadours have, I could say that about most of these but then again, constructiveness so do whatever.

Rosebush looks alright, but side view just kind of looks like a bunch of random green pink and yellow spots, id make some sort of more detailed flowers on it or something like that instead of a couple of pixels of each colour sprinkled in, leafpile front view covers the face a bit too much but whatever, back view looks alright but sideview just covers 70% of the face and I just think that's excessive, then again this is literally just waifu hair for sentient trees made for the bottom shelf players, so purposefully being shit and covering all the face probably the intention. Back on alien flower, I get what you tried to do, but you can barely see the face, a person isnt 60% made out of hair, it just doesn't look good to begin with and its abnormally big. 

Go check out other plant like haircuts from games like Starbound, you can use those are reference so you make half decent ones, only three here would be good to go as is in my opinion. Constructive enough mister I pretend to be a princess?

**Comment by Shadowmech88** [comment]
It's fine for human hair because actual human hair is homogenous. These are supposed to be individual flowers, right? Some of them aren't recognizable as individual flowers, like Big Flower, Small Mushroom, and Bluebell.
Flytrap doesn't really look hairlike, mostly because they appear to be attached to the diona's back and arm as well as its head.
Alien Flower looks like a hat or headdress.

The bright red flowers on top of the green in Leafpile make it look pretty busy. I think it'd look better if the flowers were reduced or removed. Leaf piles are homogenous, so I don't think it'd look bad for that style to be mostly or entirely green.

**Comment by ghost** [comment]
being able to feed dionas water to make them grow flowers when?

**Comment by CodenameB** [comment]
@yclatious 
I don't see why you are complaining about the color on the sprites that I very clearly said you can pick the color on (like Small Mushroom) You can change the colors on everything in the top half.

I actually did look at Starbound hairstyles, but they proved pretty much useless because the starbound Florian hair styles are larger than our entire body sprites. It's nearly impossible to do detail in a 5x5 area of pixels.

As for "Alien flower" yes, there are in fact plants that are 60% flower. This is an alien race after all.

@Shadowmech88 
No, they are not individual flowers for the most part. "big flower" is just petals, meant for people who just want a solid color hair like humans have. "Small mushroom" is just petals with a small red mushroom in the back. Bluebell is a ponytail made of bluebells. I guess "flytrap" rendered a bit weird, it has vines but because they are a single pixel wide, you can't see them well.

**Comment by yclatious** [comment]
"Some of the hair are static colors, and some allow you to pick the colors" just translated to "one or maybe two of these are static, the rest are just going to be neon haired on purpose", I misread it anyways and providing feedback on them all since I didn't know which were color locked or not due to migraines, lack of sleep and doing other shit while typing.

Pulled a PJB but eh, I can already tell these are maybe going to be used by 3 people, obviously with the neon cranked to cyberpunk levels so not like the criticism isn't valid for both the colors and the designs since shit like leafpile still needs to be cut down a bit so you can see the face instead of being 70% hair, rosebush still looks half pureed flowers in its side view and alien flower still looks like a flowery version of the womb in ME!ME!ME!.

**Comment by Ephx1** [comment]
OK, I don't know how "out of place" is not good feedback when that's incredibly simple. 

These look like wigs, they don't _fit_ with the diona, completely unnatural on them. Dionae already have head structures.

**Comment by ghost** [comment]
aegis hangar romeo 2017-06-04 215624

Dionae currently have a hairstyle

**Comment by ghost** [comment]
neon hair for vox when??? birds are like really colorful so it totally fits

**Comment by ghost** [comment]
Nah we need hair for skeletons

**Comment by Jubisloviu** [comment]
those airstyles should be avaible after splicing the dionae nodes with other plants
also where's the plump helmet dionae hair?

**Comment by SonixApache** [comment]
well, those are definitely hairstyles
seem kind of big and overly colorful, not sure

**Comment by Blithering** [comment]
They start huge and just get bigger, I'd prefer something small

**Comment by CptWad** [comment]
imo an alien plant person isnt going to have completely different flowers but the same flower in different arrangements, assortments and colors
like tulips
2-16-types-of-flowers-3-728
Same flower different features, like human hair.

**Comment by CptWad** [comment]
hair
this is sorta what I mean

**Comment by Blithering** [comment]
@CptWad I could see that being workable, take the headspikes that diona currently have and move that to the hair, then make different spike styles to choose from

**Comment by PromethTK11** [comment]
Diona looks more like dry leaves, so it's something odd seeing something so colorful in them, what about using the same color scheme of dry leaves/flowers/mushrooms instead of bright colors?

**Comment by Intigracy** [comment]
Or you can have the flowers but have everything else the same dry color.

Like the rosebush, try doing it with the roses as-is but with the main hair color as the dull body color

**Comment by Intigracy** [comment]
I'm gonna code it so you can grow a plant on a diona's head.

**Comment by SonixApache** [comment]
i think it's time for this one to start pushing up daisies
try again with less crazy stuff

I think Bluebell and Flytrap are cute and would work on their own.

**Comment by Exxion** [comment]
Yeah this doesn't look to be going anywhere
Feel free to open a new PR if you make some changes

**Comment by CodenameB** [comment]
That's fair.

**Pull request closed without merging**
