### PR TITLE
Bagelstation: replaced brig's valve with straight pipe

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * tweak: Bagelstation: The brig used to have a digital valve connecting it to distro, now it's a straight pipe instead.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Isn't this intended to allow you to cut off brig atmos from main distro if sabotage is underway? Even box separates brig atmos via a gas pump to delay any flood effects

**Comment by DamianX** [comment]
Box and deff do it, the other maps don't. Someone complained to me that the brig is cut off from the station by default. An alternative would have been to open the valve. I don't feel strongly about this one way or the other.

**Comment by Sooose** [comment]
I complained and asked Damian if he could change it since he was already working on bagel changes. Every time someone welder bombs the brig we end up with no air for the rest of the round in the brig unless someone brings a cannister. The reason being that this valve in the back of brig maint is off by default and no one even knows it exists, so brig distro never fills.

**Comment by Kurfursten** [comment]
Air pump like box then?

**Pull request merged**
