### PR TITLE
Allows AIs to enable a Medical and Security overlay

### PR DESCRIPTION
**Pull request by JustSumBody**
Ingame
Couldn't really think of a good place to put this, any suggestions are fine by me

### CODE REVIEW

**Comment by Ephx1** [comment]
In a similar fashion how visible actions no longer let you bullshit an AI, this in turn does the same thing with the MedHUD "Oh no worries AI, we're not beating the prisoner". Actually that makes me surprised the AI radio hasn't been removed. Would be REALLY handy, but I can see people getting up in arms over this.

Not sure how I feel about SecHUD, but if you're giving them MedHUD you might as well. The only difference from how it works now is just being able to click on Sec Records, look for the red, then track that name. So I suppose it isn't that much of a problem.

**Comment by JustSumBody** [comment]
You could argue seeing their health drop through the HUD is similar to seeing their health go down on the CMC, differences being the CMC requires suit sensors and having it open at all time, while the HUD only functions while you're actively looking at them. That seems pretty fair to me.
If you really need to get your valids on while there's an Asimov AI and for some reason you can't just change the laws, tinfoil hats block the HUDs.

**Comment by kol1th** [comment]
Sechud is fairly useless without being able to examine+set records.

**Comment by ghost** [comment]
Why are we giving AIs so much at roundstart?

Make it 'fun' for everyone, make it upgrade modules that science can make to improve the AI

**Comment by Ephx1** [comment]
Just make it a camera upgrade. Modules would require some sort of console or actually going up to the AI, which probably neither would ever occur.

**Comment by clusterfack** [comment]
I think @Skullyton is right.

Also I think in its current state, the AI's information gathering capabilities do not need to be buffed. If anything what AI's need buff is their interactibility with their environment (at a limited level of course).

**Comment by kol1th** [comment]
This would take the guessing game out of seeing if two people are being harmed, or if they were harmed.  Many times I've been just unable to tell if sec is beating someone to death in the security office, or solitary, or basically anywhere in security. Of course, that information would be available if I sent a borg, but nine times out of ten there is no borg. And then there's the CMC, which you have to shift your view from the area, click it, hope it loads right, and THEN move back to the guy you THINK is being harmed, at which point he's already dead and gone, but you can't just know that because you didn't see it.

It's information available to you, but instead of jumping through several, slow-paced hoops, you have it readily available. You can also see if there's a virus and work together with the medical team, borgs, etc. to get rid of it. 

I also believe this would make playing AI more user-friendly, and perhaps lead to more people playing AI better. There would be practically no change for experienced AI players.

**Comment by PsiOmegaDelta** [comment]
For a balance suggestion, Bay AI medHUD vision only offers as much information as the CMC does, meaning that if someone has sensors turned off the AI see nothing, binary the AI see the living/dead status, etc.

**Comment by Blithering** [comment]
I would agree that it would be best as an upgrade for the cameras, like x-ray and motion sensitive cameras currently. Having medscan cameras in medbay at round start wouldn't be a bad idea though.

**Comment by Durgen** [comment]
Could the type of Hud enabled be based on their current Lawset?

Robocop and NT could have secHud
Asimov and Paladin could have medHud
Corporate could have [spoiler]nvgHud[/spoiler]

**Comment by kol1th** [comment]
@Blithering Another camera upgrade that will never be used, just like the rest.

**Comment by ghost** [comment]
Maybe have it be something you slap in the upload console?

**Comment by ghost** [comment]
How about a new console entirely that's akin to a floppy disk drive, that has to be linked to the AI via multitool just for added complexity

We can finally emag the AI

**Comment by Ephx1** [comment]
Why emag the AI? It's a law two away from onehuman thanks to the freeform board.

**Comment by Allspice** [comment]
Kolith, you could just leave the CMC open in another window and bring it up as needed (if the monitor does not decide to shit the bed that day)

**Comment by JustSumBody** [comment]
also I fixed the conflicts pls remove label so this can never get merged

**Comment by Probe1** [comment]
@JustSumBody Reopen this PR please.

**Pull request closed without merging**
