### PR TITLE
Reduces a lot of stuns

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
It's one of those PRs
Argument: Stuns are a terrible thing for combat and nobody will miss longer stuns

Electrode from 20 to 10 seconds
E-bow from 20 to 10 seconds
Plasma guns **can no longer stun**, they are already broken enough
Weak bullets from things such as AC from 10 to 6 seconds
Shotgun taser shot from 20 to 10 seconds
Water slips from 10 to 6 seconds
Lube slips from 20 to 10 seconds
Clown PDA slip from 16 to 10 seconds
Stunpapers are coming soon when I am going to figure out the overlay thing so they aren't out of sync, that makes me better than the For Honor developers
CR-20 bullet stun removal is another PR
Batons are unchanged if you want to pacify people on the long term (if you use a stunbaton that it, prod is still 10 seconds as normal), bola is unchanged too

Q&A
Q: Because stuns are nerfed, doesn't that mean Security, a department relying on stuns, will have it much, much worse?
A: Cuffs take 3-4 seconds, gameplay is mostly unchanged but the main thing with stuns is that you can't just sit around for some time. There is also stun re-applying to take into account. Security will only have it worse if they don't cuff people and stuff
Q: Why are you making this PR?
A: Stuns are not cool, I mean it. They make the already-shoddy click-based combat of the game even worse. Maybe I can do more with the combat like the armor rework (instead of dice-based half or all damage absorbed current armor it will be percentage-based reduction) but until then have this (what I consider to be) genuine improvement
Q: Why did you not touch stun X?
A: Tell me and I'll change it, this is sort of an on-going PR, I looked over the list of bullets and most of them are alright, doesn't mean you can't tell me though.

:cl:
 * tweak: Several stuns have been reduced. Electrode, ebow, shotgun electrode bolt, lube, and clown PDA last 10 seconds, weapons that use "weak bullets" like the mech AC, certain shotguns, and water slips last 6 seconds. Plasma guns had their stun chance removed, and they can no longer stun.

### CODE REVIEW

**Comment by SirSkeleto** [comment]
stun meta is antifun

**Comment by aceedex** [comment]
"Plasma guns are already strong enough"
Those mother fuckers didnt even get the projectile speed buff. What brand of brain hurt juice you been sippin

**Comment by boy2mantwicethefam** [comment]
It contaminates clothes on hit and deal beefy damage, that's strong as hell man

**Comment by KingofHONK** [comment]
Less electrodes in firefight situations. Good thing.

**Comment by aceedex** [comment]
It is as easy to juke around as a taser. They never get made despite needing only plasma. The average scientists prefers to pilfer an egun from the armory and use a modkit on it.

As far as the rest of the changes go, I expect a lot of "there were two of em and I cant reliably keep an both down so I went to lethals"  it seems less genuine improvement and more a bandaid on an open heart surgery patient. 

This PR seems to follow the logic of "stun bad, so less stun good" without much more though as to how halving stun time changes the gameplay and why would such a change benefit. Personally I'd rather have something like stuns cant be reapplied if currently stunned if the goal is to increase the vulnerability time between applying a stun and doing whatever you want but again, I dont know exactly what you're looking to accomplish by halving stun times more or less across the board 

This also doesnt touch any of the ghetto stuns like prods and glubbs which should be top billing as far as such a change.

**Comment by GoodG1448** [comment]
What about vampire's glare and hypnotize?

**Comment by boy2mantwicethefam** [comment]
@aceedex That sounds like a Nirvana fallacy, just because the thing isn't perfect doesn't mean it should be disregarded. Nothing will get done this way. It is a band-aid to an open-heart surgery, but it's better than no band-aid on an open heart surgery.
The scenario you described is solved with cuffing one person at a time, what sort of officer would try to cuff people if they were valid enough that somehow not being able to be cuffed would mean field execution?
Not every solution has to be complicated, and I argue that a "window of vulnerability" would be problematic as you usually can't even tell when a person will get up. Stun stacking is a can of worms by itself
Melee stuns have not been changed, and I'm on my way (HANDLED IN DISCORD) to be convinced to not nerf any of the melee stuns
@GoodG1448 I'll see what I can do, but I recall the stun timer is fair enough, but hypnotise allows you to suck a person dry before they can even wake up

**Comment by SonixApache** [comment]
testmerge

**Comment by ghost** [comment]
Definitely worth a testmerge, because theorycrafting _(buzzword of the post!)_ only gets us so far. Presuming swift response and updates, it'd be fine if it were overbalanced a tad and then tweaked in post.

**Comment by plosky1** [comment]
Don't agree with ebow, it's already never used since it was changed to knockdown from sleep. Plasma guns are also never used and are "op" if you only consider long-term damage from radiated clothes, shouldn't be changed. Bullets should also be left alone, as while you have long-term damage from fragmentation the upfront damage isn't a lot unless you're filled with them.

Stunpapers from cult should ABSOLUTELY not be touched, if that's what you're referring to. Barely enough time to put down a conversion rune as it is.

Electrode, shotgun taser, and slips I agree with.

**Comment by aceedex** [comment]
And that sounds like a fallacy fallacy. You shouldn't make a sweeping change to a core game mechanic without at the very least trying to explain what it would accomplish. I only bring up the window of vulnerability because I still don't know what this is supposed to solve. What this reminds me of is the chemical sting change to changeling. "Doing it right is a Herculean task so let's half ass it and hope it does something"

As far as the hypothetical scenario, its a fairly common situation in cult/revs and I do fear it exacerbates it. 

Melee stuns IMO are the stuns that can most easily be turned against the user so they should be the first to bitethe dust. SPECIALLY glubbs since they can be hidden.

**Comment by MadmanMartian** [comment]
oof on that example

**Comment by aceedex** [comment]
Sorry robo. Nothing against you but I did dislike that change

**Comment by AI-Is-Rogue** [comment]
Wait. How can you hide stunglubbs?

**Comment by plosky1** [comment]
Stunglubbs have a specific sprite that is different when equipped, so maybe he means putting them on and off from a backpack?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I'm looking forward to seeing this as a testmerge and most of these honestly were unreasonably long no matter what. I hope this doesn't end up killing future stuns discussion however, there are good points to be made about cablecuffs for example.

**Comment by boy2mantwicethefam** [comment]
I have not intended to disregard your argument by claiming it's a fallacy though, the aim of the PR is self-evident as to just reduce overall stun duration, I think it's more of a one step towards a better direction when it comes to the game's shoddy combat, less bang for your buck for stuns and all that
It does not get rid of the problem, but it eases it
Cult and revs are pretty much fair game given the usual combat scenario, few revs bother with reviving dead fellow revs because revheads don't usually stay in medbay, but there's no reason to capture cultists if they cannot be deconverted
Melee stuns are a more "brave" approach to combat most of the time or to make a stun lengthier after applying a ranged one

**Comment by Sooose** [comment]
@AI-Is-Rogue @plosky1 You can always just hide your gloves sprite by putting on a firesuit/rig suit.

**Comment by plosky1** [comment]
@Sooose do stun gloves work with firesuits on? i know they dont with space suits on

**Comment by Sooose** [comment]
> @Sooose do stun gloves work with firesuits on? i know they dont with space suits on

Doesn't look like it, good catch.

**Comment by ShiftyRail** [comment]
Let's experiment it for a week to see that either nothing will change or it will be a complete disaster that nobody will attempt to do again.

Also

>30 seconds with a visual indicator is not enough for cultists to place down a convert rune or even to cablecuff

Says a lot more about cult players than anything else.

**Comment by plosky1** [comment]
The issue is that it takes 5-15 seconds to get converts into a room either in maint or one with no windows where you’ve broken cameras. Cablecuffing also involves carrying cablecuffs, using up 5 seconds to cablecuff, using up more time to remove headset, etc. Talismans are also one-time use and require two different runes to make. They’re fine as is.

**Comment by iFlashYou** [comment]
Just carry more than one stun talisman maybe?

**Comment by plosky1** [comment]
Obviously you do, but using more than 1 talisman on a convert should only be for if shit goes sideways and somebody catches you. The blood cost and time sink to make talismans is too high otherwise. Plus, having to use a second rune just increases your chances of being caught even more, and will make a cult that barely wins as it is even harder for anyone not expert-rated.

**Comment by spoonylove** [comment]
The only thing I care about is 20 second stuns being reduced such as lube. Good changes.

**Comment by TurboGay** [comment]
Changes are good but if you're dropping the paper stun duration there should be some compromise with increasing the mute time to avoid inexperienced cultists causing flukes too often.

**Comment by Blithering** [comment]
Nerf cuffs not stuns.

**Comment by SonixApache** [comment]
why not both

**Comment by groosbstrd** [comment]
What about flashes?

**Comment by ShiftyRail** [comment]
This will not achieve what it sets out to do (a 10 seconds or a 20 seconds stun is the exact same sentence in a 1v1 combat), while reducing the possibilities to win a 3 vs 1 fight if you're careful enough with your stun.

In other words, it will make de-esclation against multiple targets much harder while not addressing the core of the issue. Changing a few numbers here and there isn't how you fix stun-based combat. If you're going to be that ambitious, do more than lowering numbers.

**Comment by boy2mantwicethefam** [comment]
@groosbstrd Decided that melee stuns don't need a lowering in this PR, this includes flashes. If support to lower flash stun is high enough I'll make it in a separate PR

@ShiftyRail If you're worried about engaging multiple targets then tap them with the stunbaton, melee stuns aren't getting lowered, cuffing people one at a time also works because they can't open doors and have to stay still for two minutes to break out of cuffs

**Comment by DamianX** [comment]
As a sec person I welcome this change as it nerfs any counterplay an assistant could have against my taser (e.g. bait me into a water slip + cable cuffs, which is now closer to impossible with 6 seconds of stun).
Reddit gold from me

**Comment by calzilla1** [comment]
It would be cool if slip stuns were based of clothing and armor. Like a assistant slipping would give a much smaller amount of stun than a person in riot armor

**Comment by SonixApache** [comment]
encumbrance / weight system when

**Comment by tuypo1** [comment]
Stuns are mostly fine as is but I am all for a clown pda nerf.

**Comment by Accipitermaris** [comment]
cr20 stun removal pr got closed
that detail illustrates the difficulty in this pr as well (“if x, why not y”.)

**Comment by PaulRitter** [comment]
i agree with the testmerge, all this theorycrafting is getting us nowhere

**Comment by ghost** [comment]
Let's stop with the dumb "we can't have a partial nerf, it's my way or the HIGHWAY" rejection. Stuns as it stands are cancerous and are eating up our combat system. This problem has been identified for years back when the coderbus was an actual small IRC club

Let's lower the times NOW to take some pressure off, and let's try and brainstorm something to replace it on our own time. Preferably something that someone is actually going to fucking code this time, because last time fatigue was really talked up but never done

**Comment by ShiftyRail** [comment]
It's not really that it is complaining about a partial nerf, rather than it won't do what it wants to achieve (at all) in my humble opinion, all the while having unintended consequences (see Damian's comment about water slips).

**Comment by Gazathor** [comment]
Id say this would be interesting in terms of seeing how quickly the combat metas adapt to such a change

**Comment by JedediahSmith** [comment]
@plosky1 One advantage of multiple back-to-back cult rounds: in theory I hear you. In practice? People are having no problem stunning and converting with plenty of time to spare. Still, I don't think Talisman needs a Nerf, personally.

With regards to the PR: Stun meta, as it stands, is everything. Whether you succeed or fail has little to do with what object you are killing someone with. If any semi capable player lands a stun it's more than sufficient time to follow up.

I'm not certain halving the times will substantially change this meta, but it's worth a trial, IMHO

**Comment by IAGFPRMF** [comment]
The year is 2020, /vg/station
Stuns have been entirely removed, except for cultist stun papers which is now a ten minute stun. Cult still manages to fail every round, however. 
Tasers have been replaced with matebas and batons with energy swords 
Jail cells have became morgues
The hallways are filled with empty bullet casings  
The assistants who aren't bullet ridden are sobbing deeply in a dark corner muttering "f-fucking coders..." and "m-muh disarm... " nostalgically dreaming about the times where their shittery gave them a measly two minute sentence
Chaplain screams over the radio "GOD BLESS AMERICA" following by gun shots of his civilian mosin 

This is our future

**Comment by JedediahSmith** [comment]
@IAGFPRMF 

You forgot. Batons are still good. Sec officers now expected to carry 3-5 in order to toss them at fleeing criminals.

**Comment by Blithering** [comment]
batons were nerfed in the fallout of April fools day 2020, which saw the batling gun introduced to sec lockers.

**Comment by SonixApache** [comment]
\>batling gun
👀

**Comment by JedediahSmith** [comment]
@SonixApache Shoots bats.

**Comment by Blithering** [comment]
*harmbaton.ogg played over itself fifty times *
batling

**Comment by nuklearcellphoneg** [comment]
Okay but increase disarm stun duration by 1.5 seconds.

**Pull request merged**
