### PR TITLE
Overhauls Deffs Bar

### PR DESCRIPTION
**Pull request by Probe1**
It needed it, players asked for it, and I wanted a warm up before I gave Medbay a mean look.

- Bar counter and Kitchen have separate tables and face the bar.
- Added shutters to both the bar counter and kitchen counter.
- Useless ass ghetto dining room that no one ever uses is gone
- Botany got a little bigger of a back room for xenobot
- Maint shuffling
- Gambling Den has been moved to the bar and replaced with maint.

## Old:

image

## New:

https://a.pomf.cat/biawmt.webm

dreamseeker_2017-01-06_02-29-01

dreamseeker_2017-01-06_02-29-57

dreamseeker_2017-01-06_02-30-39

dreamseeker_2017-01-06_02-30-59

dreamseeker_2017-01-06_02-31-31

### CODE REVIEW

**Comment by Exxion** [comment]
Got a picture of the new?

**Comment by Probe1** [comment]
Yeah yeah its coming I forgot to redo the areas.

**Comment by Probe1** [comment]
Note the bruise pack is part of the maint random loot spawners and not something thats there every time or that I particularly picked out.

**Comment by Exxion** [comment]
Slick as fuck
Might actually make me enjoy Deff again

**Comment by Exxion** [comment]
I have one minor complaint: The juke isn't visible from most of the bar, meaning the bartender can't hear the name of the new song as it switches. Meta has that problem too, though.

**Comment by Probe1** [comment]
@Exxion 

I waffled between next to the slot machines and where it is but ultimately I think this gives the best coverage of the bar.

dreammaker_2017-01-06_02-44-38

**Comment by Exxion** [comment]
What the hell happened to that pipe?

**Comment by Probe1** [comment]
Circle it?

**Comment by Exxion** [comment]
Bottom left, on the table. Smoking pipe. Now it's a missing state sprite.

**Comment by Exxion** [comment]
Or that might just be the abysmal DM mapper

**Comment by Probe1** [comment]
Oh yeah the cigar has that same sprite in dreammaker.  I was thinking you were talking about atmospheric pipes.  And there's more!  Underneath the botany pest b gone bottles is.. Oops!

dreammaker_2017-01-06_03-04-59


It's all fine in game it's just bullshit we put up with.

**Comment by Probe1** [comment]
Boy there sure are a lot of things to forget.  With those speakers, request consoles, holopads, and camera/light tweaks I'm pretty sure I'm done.

**Comment by Sprok0** [comment]
Don't forget intercoms around places where people will cluster, so they can be spied upon by AIs

**Comment by Probe1** [comment]
I forgot that like 4 times in a row but I remembered it in the end

**Pull request merged**
