### PR TITLE
Another shot at fixing broken persistent broken growth dishes

### PR DESCRIPTION
**Pull request by DeityLink**
shazbot

### CODE REVIEW

**Comment by DamianX** [comment]
What is the issue?

**Comment by DeityLink** [comment]
@DamianX persistent broken growth dish that keep spawning with their icon-state set to "brokendish-outline", instead of "brokendish-persistent"

**Comment by DamianX** [comment]
Is it just the icon state that's wrong or is the type of the atom itself not the expected `/obj/effect/decal/cleanable/virusdish/persistent`?

**Comment by DeityLink** [comment]
persistent atom icon_states don't actually matter, since it gets replaced by the previous round's by mapsave2atom. you have to override it in post_mapsave2atom.

**Pull request merged**
