### PR TITLE
Snaxi Brig

### PR DESCRIPTION
**Pull request by Kurfursten**
I got tired of waiting for Kharkov to rework the brig and did it myself. Consulted with a bunch of sec mains including @KingofHONK Loppu dack_janiels @drawsstuff & vostroyan and also @BomberBro was consulted.

image

Major features
* New dorms / shower
* New solitary
* Wider cells
* Equipment room much less cramped and not a chokepoint
* Evidence room now adjacent to interrogation
* Interrogation room now large and central; has smartglass and curtains to go into private mode
* Can't get into armory by breaking 2 windows
* Wider hallways and reduced chokepoints all around
* Evidence lockers no longer have snowflake access

:cl:
* tweak: Snaxi brig has been overhauled. It's less chokepointy.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Like it a lot, except maybe the fact that the cells are hidden from public view (and therefore less effective), but you can't have it all I guess.
Good job.

**Comment by APCUnlocked** [comment]
Looks way better than the old snaxi brig. Digging the new interrogation room and *actual* solitary.

**Comment by cloutcode** [comment]
some comments
- the empty security office thing is empty and sad and weird to have as the connection to the courtroom
- also strange to have the security access to the armory go through the evidence room

that's all

**Comment by Kurfursten** [comment]
It feels more like an extension to the hallway in practice. I didn't want to put anything dense in there so that it still has a lot of maneuvering room. 1-wide spaces were a complaint on oldbrig.

Adding some more colored tiles might help though

**Comment by SonixApache** [comment]
Pretty decent job. It's still a bit claustrophobic in there, still reeks of lowpop map, but it's better than before for sure.
The double office and outside-connected dorm is a very strange choice and I feel like that space could be better used with more cells or locker room space.

**Comment by calzilla1** [comment]
I like it, but I wish there was more than 2 cells, as snaxi usually has a higher pop than other stations with even more cells in their brig. Maybe condense the sec room near the north and push it all to the right, and add another cell there. Also, add some shutters to the dorm's windows as their primary use afaik is to let officers go SSD without being stripped. Then, maybe add some more flashers as the brig has noticeably expanded and the warden's desk has moved away from the front desk.

**Comment by Kurfursten** [comment]
I'll see what I can do for an extra cell. Adding dorms shutters should be easy-peasy though.

**Comment by Kurfursten** [comment]
Based on feedback
image
+ bigger dorms with shutters
+ 1 more cell
+ Upper office area has a lot more stuff in it. Painted floors and nearly every tile of wall covered in wall machines

**Pull request merged**
