### PR TITLE
Sets suiciding to 0 upon calling rejuvenate/anything that uses it

### LINKED ISSUE #4978: Rejuv doesn't fix suicide.

### PR DESCRIPTION
**Pull request by Wizardcrying**
Fixes #4978, as well as an oversight that allows changelings that have committed suicide to regen themselves.

### CODE REVIEW

**Comment by d3athrow** [comment]
Is this a problem with ling regen and vampire revive?

**Comment by Wizardcrying** [comment]
There's other things like mass-revive, which is why I modified revive() itself. Should I specifically only set suiciding to 0 on admin procs?

**Comment by Fox-McCloud** [comment]
@d3athrow 

Well yes, but I'm pretty sure your'e NOT supposed to recover through those; suicide is kinda meant to be the quintessential "I'm taking myself out of the round permanently" thing--cloner and a few other thing specifically check for the suiciding var and return if that is the case.

It makes sense to change for rejuv though.

**Comment by Wizardcrying** [comment]
Alright, I'll look for admin procs which call revive().

**Comment by Wizardcrying** [comment]
Turns out that I misread the code; I was editing rejuvenate, but revive calls it anyway.

**Comment by Fox-McCloud** [comment]
Well, most things that revive specifically check for suiciding and fail if they they are...likewise examining someone who is dead and has suicided even has its own custom flavor message: "it appears they have committed suicide *_there is no hope of recovery_*".

Emphasis added by me.

**Comment by Wizardcrying** [comment]
In that case, time to do quite a bit more work.

**Comment by Fox-McCloud** [comment]
Please note there are definitely things that do NOT check for it which can and does result in weird situations--ie: lings who revive will just take oxy damage forever with no way to fix it (I think you use oldlings, right?)

**Comment by Wizardcrying** [comment]
We use oldlings, and there isn't a check for suiciding upon using Regenerative Stasis. You can still regenerate after committing suicide, but you will be in a constant state of oxyloss. Perhaps I should change things that call revive()/rejuvenate() to fix that.
However, there's already a problem I spotted with RS: changeling_returntolife is rejuvenate, just for changelings. It's copypasted, so I suppose I can replace its use with a single call of revive().

**Comment by Wizardcrying** [comment]
DNM yet, I have a bit more work to do.

**Comment by Wizardcrying** [comment]
I'll allow a merge in the current state of this PR, but I'd like to fix cult runes/vampire revivals too, possibly in a separate pull request.

**Pull request merged**
