### PR TITLE
Brute damage now only disfigures faces if the weapon used wasn't sharp.

### LINKED ISSUE #30931: Captain's Log 17: A Hairy Situation
A beard's to a sailor like barnacles to a ship, the more you have the more your experience reflects. Despite this, a man can't simply let his visage grow asunder with Spanish moss. Shaving's imperative for any respectable seafarer, but a good blade may sometimes be scarcer on the waves than a sharp wit. Of course, where there's a will there's a way, and lack of sword or dagger will not stop a clever jack from his mission. 

In the pirate capital of Nassau, where life's cheaper than rum, many of the men have figured a way to use plentiful bullets to trim their faces instead of a razor. I shall detail these steps below:
**Step 1: Get shot in the face**
beard1
It's not a clever art, hair's well-known to be scared of bullets just like any ordinary man, and it's commonly-held that gunshot victims are found hairless, the follicles simply hauling off like rats from a ship to find a better, safer life. Even if you get facial reconstruction surgery, as many a man does when confronted with grapeshot to the skull, the hair will remember the treacherous seas it once lurked and refuse to return. 

However, not all is lost for the sailor contemplating purchasing a beret, the cure is rather simple:
**Step 1: Get a new beard in the mirror**
beard2
Now, dear reader, you may be saying, "But that's not strange at all, mirrors can always create beards!", and I'll concede that fact. What I'll raise you, however, is that the original hair returns from the æther as soon as it spies a beard, instead of needing to tend to it separately. 

May you find use from these logs, I wish you all the best.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #30931

:cl:
* tweak: Brute damage can no longer disfigure people. Only burn damage and acid do. By decree of our headmin.
* bugfix: Your hair becomes visible right away after Facial Reconstruction Surgery as been completed now, instead of having to use a mirror. (Bomber Harris)

### CODE REVIEW

**Comment by DeityLink** [comment]
Changed after investigating the code and discussing with Bomber. Disfiguring can now longer occur from brute damage (since limbs cannot drop until they reach full damage so you're basically guaranteed to have your face disfigured by the time you're decapitated.

**Comment by DeityLink** [comment]
Ok changed again, now it's as before but only if the weapon isn't edged

**Comment by DeityLink** [comment]
aaaand changed again at Bomber's request, no more brute disfiguring.

**Comment by gurfan** [comment]
Why shouldn't brute damage disfigure you? If you were shot in the face I'm slightly sure that you would look a little different than before.

**Comment by DeityLink** [comment]
> 
> 
> Why shouldn't brute damage disfigure you? If you were shot in the face I'm slightly sure that you would look a little different than before.

I think so too but apparently becoming bald breaks some people's immersions so until we get custom disfigured hair sprites this was the option preferred by the person who raised the issue in the first place.

**Pull request merged**
