### PR TITLE
Revert "Puddle slipping tweaks"

### PR DESCRIPTION
**Pull request by Eneocho**
Reverts #32231.
Lube and water are now almost unusable. They evaporate way too quick. You can't even use the 5u sprays anymore since they can't make puddles at 5u. Clown Water Flowers can't make puddles (thus can't slip anyone) anymore since they spray 1u. Water is barely slippable. See #32243 for a list of issues with this "fix".

### CODE REVIEW

**Comment by Cartlord** [comment]
What if we just reverted fuckin' puddles?

**Comment by Hinaichigo** [comment]
Maybe even a single unit could form a puddle, with a minimum apparent size for visibility, with anything below eg. 10u looking the same as 10u, and evaporation times could go to their pre-puddle values and not depend on volume. Because they're flat along the ground, we could say a puddle's surface area (and thus evap rate) is linearly proportional with volume, so a small puddle would last as long as a large puddle, or something.

Also agree that slip time shouldn't be impacted by puddle volume, just the highest slipperyness of the reagents it contains.

That way all the previous functionality of lubed and watered floors are preserved as they were, within the puddle framework.

Down the line you could branch evaporation into two different things:
- drying up (like the previous system, the puddle disappears after a certain amount of time) Lube would simply dry up, not evaporate into lube vapor.
- true evaporation (the puddle loses volume via evaporation into the surrounding air, at a rate depending on the pressure and temperature of the surrounding air) That way you could get explosive fuel-air mixtures and stuff.

**Comment by WindowsErrors** [comment]
think the situations changed a bit

#32251

**Comment by Eneocho** [comment]
Well, that's something.

**Pull request closed without merging**
