### PR TITLE
Small Snaxi Fixes

### LINKED ISSUE #21158: Snowfort doesn't have mushroom suits.
(WEB REPORT BY: otatoh REMOTE: 206.221.180.138:7777)
# Revision
3ec6d4389835ec03acc98b6a14dc0168b7722560

# Description
Snowfort's trader outpost doesn't have mushroom suits in the lockers, I'm guessing because it still uses the wrong locker subtype.

### LINKED ISSUE #24361: Snaxi Vox lost the Housekey (Check under the welcome mat yaya)
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
f1da39ed6d91ae815f26df4596947f64367b65d7

# Description
Midround Vox Traders (and maybe roundstart too) wearing IDs or not can't press the buttons for the trader post airlock.
# Steps to Reproduce
>be vox trader
>flung to tradepost at high velocity
>standing in airlock
>repressurizer won't accept you
>enter anyway because the airlock recognizes you
>the entry supplies are sucked off the table
>say "*aflap"
# What you Expected
button work
# What Actually Happened
button no work

### LINKED ISSUE #24747: Sound Systems Snaxi
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
f100367cd935109fda15007550a2f94f53003b87

# Description
Missing Sound Systems most rooms and they won't work in a number of rooms / areas.
# Steps to Reproduce
Play Snaxi. Try and find Sound systems in rooms. Try and put sound systems in rooms / areas.
# What you Expected
To find a sound system and glorious music to play upon setting up a new one.
# What Actually Happened
Either no sound systems or upon setting up one on every available wall no music will play.

### LINKED ISSUE #24934: Snaxi vox station
(WEB REPORT BY: burneddi REMOTE: 206.221.180.138:7777)
Half the vent pumps are set to the wrong frequency and aren't controllable through the air alarms.

~~The NanoMed in the room to the east across the hallway from the botany trays has access restrictions and can't be used by the traders.~~

### LINKED ISSUE #25014: Playing bartender on Snaxi is like water torture
This issue dates back to long before it was Snaxi but somehow has never been reported, either by myself or by anyone else, as far as I can tell
If engineers build the AME in the normal place, you can hear it from behind the bar
The occasional but incessant bang noises WILL drive you insane IRL

### LINKED ISSUE #25015: [Snaxi]The coin press is not properly mapped
(WEB REPORT BY: probe1 REMOTE: 206.221.180.138:7777)
# Revision
f1900bf61d0e7ffaf25ff0e87d3b2e58a75cf0bc

# Description
https://i.imgur.com/TwiPG1f.jpg
# Steps to Reproduce

# What you Expected
coin food to go into machine
# What Actually Happened
coin food is not set up to go into machine

### LINKED ISSUE #25028: Bar has no compressed matter crartidges on snaxi
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
1de1fa637da060946eb9efa49885a7585f1d0e4b

# Description
the bar has no compressed matter cartridges on Snow Taxi
# Steps to Reproduce
Spawn and find no compressed matter cartridges
# What you Expected
there would be compressed matter cartridges
# What Actually Happened
there were no compressed matter cartridges

### LINKED ISSUE #25090: New snow SMES blocks flow of power to southern station on Snaxi
(WEB REPORT BY: caboozles REMOTE: 206.221.180.138:7777)
# Revision
18afa41ebae62f176ed095e979b19df58d63e6d8

# Description
Power will not flow from the engineering station into the Security/Bridge station in the south because the wire that connects goes through an SMES that starts on the off position. Due to this, you either have to manually enable the SMES or re-route it yourself.

# Steps to Reproduce
Set up an engine and enable the engineering SMES like normal.

# What you Expected
Power to return to the rest of the station

# What Actually Happened
South Station at 0 power, woops!

### LINKED ISSUE #25165: pipes missing in toxins, bar, mech bay
(WEB REPORT BY: crudequip REMOTE: 206.221.180.138:7777)
# Revision
dc4c5ff0152cf8778ee6714818dad1bb564bc051

# Description
snaxi pipes missing

# Steps to Reproduce
play snaxi

ventcrawl to bar 
there is a missing distro pipe underneath one of the doors

ventcrawl to toxins
missing waste pipe under r. plasma glass window

ventcrawl to mech bay
missing pipes under shutters

# What you Expected
:)

# What Actually Happened
>:(

### LINKED ISSUE #25167: Snaxi Paramedic carts
(WEB REPORT BY: tobiaskunst REMOTE: 206.221.180.138:7777)
# Revision
dc4c5ff0152cf8778ee6714818dad1bb564bc051

# Description
Snaxi paramedic carts are unable to load anything, unlike their cargo counterparts.

# Steps to Reproduce
1. Have cart + random object.
2. Drag random object on cart.

# What you Expected
Object moves on the cart and stays on it until unbuckled.

# What Actually Happened
Nothing. Nothing at all.

### PR DESCRIPTION
**Pull request by Kurfursten**
fixes #25028
fixes #25167
fixes #21158
fixes #24361
fixes #25165
fixes #25090 (output was already to ON, but if the SMES runs out of power before you get the main grid charging, it will turn OFF... I just added wiring across the grids, no other station separates them)
fixes #25015 (made it clear which side is input with decals)
fixes #25014 (made default control module tile further from bar, and added new acoustic tiles)
fixes #24747
fixes #24934
Fixed an unreported bug where there was a single tile of asteroid under a crate on the surface
Fixed an unreported bug where Vox atmos had no vent/scrubber

New tiles on display. Sound zone outlined in red.
Untitled

🆑 
* bugfix: Fixes some bugs on Snaxi. You'll find toboggans around for pulling people and cargo, and the bar should be less BANGIN' from the AME.
* rscadd: New acoustic tiles absorb 90% of sound. Players can't make them yet.
* tweak: The Vox trade shuttle is now closer to the living space (on the tradepost side).

### CODE REVIEW

**Comment by N3X15** [comment]
We are programmed to receive
You can check out any time you like,
but you can never leave

**Comment by Kurfursten** [comment]
I explicitly said I was not leaving for good

I'm also still on hiatus, I just was annoyed to hear that no one had added the toboggans after 2 weeks so I did it myself

**Comment by Kurfursten** [comment]
In this update:
* Confirmed the Vox cycler works
* Moved the Vox trade shuttle down to be closer to the living space (see below)
* Added sound systems to most rooms fixes #24747
* Fixed an unreported bug where Vox atmos had no vent/scrubber
* Fixed a bug where none of the air alarms in Vox trade post were linked fixes #24934
* Fixed an unreported bug where there was a single tile of asteroid under a crate on the surface

image

**Comment by Kurfursten** [comment]
Conflicts resolved

**Pull request merged**
