### PR TITLE
Eimplants didn't go off if you died without succumbing

### PR DESCRIPTION
**Pull request by ShiftyRail**
What I did test when I made the whisper thingy : 
- Whisper 
- Emoting *deathgasp

What I didn't : 
- Dying normally

:cl:
- bugfix: E-implants will explode again if you die without manually typing *deathgasp.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
This is going to break e-bows isn't it

**Comment by ShiftyRail** [comment]
No it won't
God dammit I hate myself enough already

**Comment by boy2mantwicethefam** [comment]
Don't hate yourself over open-source

**Comment by SonixApache** [comment]
🆑

**Pull request merged**
