### PR TITLE
Metaclub Trader Ship Overhaul

### PR DESCRIPTION
**Pull request by Kurfursten**
I think the big tradeship was a good idea. But after months of careful observation and feedback I have made a lot of changes that I think should make **everyone** -- both those who love and hate traders happy.

* Almost all r-walls replaced with normal walls or windows. This is especially noticeable on the casino outpost I found a better way of protecting the area from gibtonite explosions (which were a consistent problem even with r_walls), which was just to **buffer the area with non-mineral asteroid walls** so gibtonite won't spawn that close in the first place.
* Casino area much less fancy and no longer has security cameras. The point of the security cameras was really as an amenity for visiting humans so they could see what's happening on the station, but in practice I never really saw that happen.
* Fixed several pipes in the ship
* Ship no longer requires power as a gimmick, instead there is a port near where the Vox dock if they wish to sell power. I don't know if this will actually happen in practice, but it adds some variety.
* Fixed ship transit space so you can no longer get to Z-2
* Reworked ship for increased visibility and stable atmos (and less bloodboil)
* Gas exchange doors now require trader access as was requested
* Vox space lockers (with magboots) now spawn on the casino post instead
* The new desk and change in gas exchange position makes it easier to trade stuff without using the vendor
nushuttle
(Out of date picture doesn't show the footprints as green)

This new shuttle looks more properly rundown, has bigger open spaces for building whatever you feel like inside, and is much more visible for investigations so you don't get bloodboiled.

🆑 
* tweak: Once again, the Metaclub trade ship has been modified. It now has better visibility from a human perspective.
* rscadd: There's now a portable SMES port on metaclub for traders interested in selling power to the crew.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
fuck birdpoops but this is a nice change

**Comment by Jubisloviu** [comment]
honestly, i'm against the vox having a roundstart plasma beaker, that thing requires some research from the station and shit, a mortar and a plasma sheet would be enough.

**Comment by Diavill** [comment]
voxcreep

**Comment by Kurfursten** [comment]
I swear you people don't even read the PRs. This is in every way a substantial trader _nerf_. The plasma beaker is not new - it was added back when traders lost the advanced medkit, chem dispenser/chemmaster (previously had 2), full cryo/cloner setup, grinder, virology machines, and genetics machines.

What this PR does:
* Makes it harder for traders to do things hidden behind walls (especially bloodboil)
* Makes traders more vulnerable to people smashing in through windows
* Makes it easier for non-traders to steal from their lockers by putting them on the roid
* Makes their roid base much easier to drill/weld/otherwise damage by removing all the r_walls
* Removes the sec cameras and and the furnace from the roid base
* Makes the ship look much more run-down

The only things traders are "getting" are...
* A water tank
* Don't have to charge their own ship's power
* A port on the station they can plug their portable SMES into, which would give the humans their power (this doesn't work in the "opposite" direction to steal power, you would even have to weld down walls just to have space to add a terminal to steal power too).
* Some small quality of life (e.g.: doors require access so they don't have to be bolted)
* A table at the front

EDIT: And I will say that it's not even a principle of "Vox need to have a plasmabeaker" - I'd just as soon give them back the grinder/plasma bar because it's not actually a big deal, it's just annoying to be accused of creep during what's certainly a nerf. Seriously?

**Comment by Diavill** [comment]
Can you include a before and after comparison between the shuttles

**Comment by Kurfursten** [comment]
That's the full after shot in the OP -- the right hand side is the latest version nothing has been changed since it was captured, you can see the before version on the public render. It's also just the current version of the trade ship on metaclub, so it's probably just like the mental image you have of it. Even if you *never* play trader, you can picture that front room with zero visibility and not even a front table, just a vending machine.

**Comment by Kurfursten** [comment]
For two and a half years now, yes, since Spring 2016 when a trader post was added to metaclub. Where have you been? Back then they had 2 full chem setups. Have you... ever played Trader on metaclub? Ever interacted with traders on metaclub?

**Comment by Accipitermaris** [comment]
>Casino area much less fancy and no longer has security cameras. The point of the security cameras was really as an amenity for visiting humans so they could see what's happening on the station, but in practice I never really saw that happen.
it never showed up on the advanced camera console when looking at z5 so i had no idea it existed tbh

**Comment by Diavill** [comment]
I knew they had it at their base, but not on the shuttle
My only interactions with traders on metaclub was shooting them dead for being niggers, as on any other map

**Comment by Diavill** [comment]
https://github.com/vgstation-coders/vgstation13/pull/17669 
I missed this one, the one where _you_ added an entire chem lab even though they shouldnt have it

**Comment by Kurfursten** [comment]
Before that PR they had 2 chem dispensers, 2 chem masters, and 1 grinder. After that PR they had 1 chem dispenser, 1 chem master, and 0 grinders. In no world does this describe "adding". I'm not entertaining this profoundly stupid conversation further.

**Comment by Diavill** [comment]
if you make it 0 chem dispensers maybe it's actually a good idea since then the vagabond space jews arent as autonomous as the entirety of the fucking station

**Comment by Accipitermaris** [comment]
Not opposed to this PR, but I think Diavill has a point in that for every other department, the reasoning behind limiting their autonomy has been in the name of Interdepartmental Interaction, but where Traders are concerned this game design idea short circuits & seemingly isn't extended to them despite the fact that one would think it to be more relevant than ever due to the inherent qualities of a Trader occupation. (And if that Trader occupation is introduced under the premise that they are impoverished pariahs, a lack of the Interdepartmental Interaction idea extending to them is even more dissonant.)

**Comment by Kurfursten** [comment]
This is veering *way* off the course of the PR, but the paradox is twofold. People are strongly of the opinion that traders should have nothing worth having and simultaneously complain that traders steal things rather than trade things. Isn't that equally dissonant? Each of the outposts was supposed to have a different theme for sales (Metaclub being medbay tools) because that gives Traders something to do other than sell their one item from the vendor or hunt vaults. Frankly we should just change the trader race to Greys because there is way too much Vox hate for people to think rationally regarding the role.

But none of this really has to do with this PR, which is about making the trade ship way more visible **for the human crew.** It is truly, truly bizarre that I am having to fight this hard to nerf traders because "the nerfs don't go far enough" apparently.

**Comment by jknpj** [comment]
JUST

**Pull request merged**
