### PR TITLE
Improves the admin Antag HUD and enhances the Streamer logo

### PR DESCRIPTION
**Pull request by DeityLink**
also made an icon for when it appears on the antagHUD
image

logo
Much better than the boring balls.

not making a changelog since this only affects admins for the most part.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you make it a different icon than unironically the twitch logo? I don't like the idea of legitimizing twitch as an in-universe thing, even if the cult streaming spell and spess.tv exists.

**Comment by DeityLink** [comment]
Literally only admins can see this icon...

**Comment by Eneocho** [comment]
It's a matter of principle.

**Comment by DeityLink** [comment]
https://www.youtube.com/shorts/8m1RRbz1vD0

**Pull request merged**
