### PR TITLE
Adds the Christmas Vinyl

### PR DESCRIPTION
**Pull request by Kharkov72**
With shadow being busy with life and me not being the best at navigating the music repo, a christmas vinyl which we hoped to do was not thought to happen, but then hark! Some sick motherfuckers in the thread sent me a bunch of christmas shit already correctly metadata'd, and I thought "Fuck it"!
This is the result of that. Thank you, thread. [sound]

Also, remember, this is [dnm] to everyone but pomf and other people with the music repo access, sinde they kinda need merged at the same time.

:cl:
 * soundadd: Adds the christmas vinyl!

### CODE REVIEW

**Comment by Kharkov72** [comment]
Untitled
Current Songlist

**Comment by RaccoonBro** [comment]
[>missing the best christmas song](https://www.youtube.com/watch?v=t039p6xqutU)

**Comment by Kharkov72** [comment]
added https://www.youtube.com/watch?v=t039p6xqutU and 
https://www.youtube.com/watch?v=9AwWmgcxcX4&feature=emb_logo

**Comment by tuypo1** [comment]
>no ponyshit

It's like you DON'T want drama

**Pull request merged**
