### PR TITLE
Allows paramedics access to telescience in Box and Meta

### PR DESCRIPTION
**Pull request by aceedex**
changes door and windoor access so that paramedics can freely move through them so they can perform rescues.
Does not actually give paramedics science access, that'd be silly.

I do have the intent to do something similar to deff, but that requires a bit more mapping so I'm willing to see if this would fly before I start hitting my head against dreammaker some more

airlocks and windoors depicted in these images can be opened by paramedics
https://puu.sh/sYkgq/48aeaf29ef.png
https://puu.sh/sYkjU/346a8ebd07.png

### CODE REVIEW

**Comment by Probe1** [comment]
That's a pretty big change.

**Comment by kol1th** [comment]
This kinda makes the paramedic EVA redundant, don't you think? Why have roller beds and extended oxygen tanks and a special EVA suit and the likes if they can just go to telescience?

**Comment by aceedex** [comment]
well, ever since the change to ZAS bringing people in has been a hellish experience, so I want this because it helps a lot in that regard. But also taking a trip to Z level 5 to pick up a miner isn't exactly the easiest thing in the world. 

Not to mention, the station gets depressurized often enough for paramedic EVA to remain relevant even then

**Comment by 9600bauds** [comment]
Regardless of the balance aspect of this, hardmapping is a sin

**Comment by Probe1** [comment]
A little varediting never hurt anyone.  Ha Ha Ha.

As a side note and actually on topic why don't we just address ZAS ripping people out of each others tender arms.

**Comment by Probe1** [comment]
sorry @aceedex 

that's why I almost always make issues first before I change how the game works.

**Comment by aceedex** [comment]
Gonna wait until mapping madness and christmas is over to avoid more confrictus and maybe mull it over some more

**Pull request closed without merging**
