### PR TITLE
Dice Additions: Dice Cups, Fudge Dice, Bags of d6

### PR DESCRIPTION
**Pull request by jwhitak**
# Dice Cups and Fudge Dice
this one is a special request from beter
image

- [x] Core Dice Cup Functionality
- [x] Tallied Dice Rolls from Cup
- [x] Fudge Dice Code
- [x] Non-Coder Sprites

### Dice Cups
image
image
Adds Dice Cups, a type of dice bag that looks like a kinda big sake cup. If you drag the cup to a table, it tosses everything inside the cup out of it. If these items are dice, it rolls them automatically, and tallies up the results for you to see. It also does this if it's used as a weapon to attack someone, if you throw it at someone, or if it's otherwise launched and impacts something. This is very dangerous in the wrong circumstances.

image
image

### Fudge Dice
image
This also adds Fudge Dice, a d6 with two +s, two -s, and two blank sides, and a bag containing 7 of them. Admire the now slightly higher quality partially-coder sprites!

image
Flawlessly interacts with the dice cup.

### Bags of d6 and New d6 Sprites
image
Simple bags that have 7 standard dice, for games of chance that need just regular dice. They come in a small variety of colors, with a slight leaning to just be regular white dice. All of the dice in each bag will be the same color. Also, the d6 received updated sprites.

### Quick bugfix to dice bags
Dice bags no longer have the Change Color Label verb (which did nothing) when you right click them.

### Where to get these things?

image
These items are available in the library's fun and games vending machine.

## Why it's good
it's not

## Changelog
:cl:
 * rscadd: Added dice cups, fudge dice, and bags of regular dice.

[content][tested]

### CODE REVIEW

**Comment by Kurfursten** [comment]
Let down that you did not code the ability to fudge dice throws (with dice cups being the method of keeping people honest). Oh well.

**Comment by WindowsErrors** [comment]
we live in a time of games within games

next there will be a way to hold more than 10 une cards in your hand at a time

**Comment by PrimeDSS13** [comment]
are dice cups just sake glasses

**Comment by cloutcode** [comment]
we're hitting levels of codersprite not thought possible

**Comment by jwhitak** [comment]
accepting donations of better sprites because i too feel pain at my own creation

**Comment by SonixApache** [comment]
in awe of your codersprites

**Comment by jwhitak** [comment]
Drafting for now. Waiting for better sprites and I plan to implement a tallying feature for the dice cup.

**Comment by jwhitak** [comment]
Ok. I think we're good. Let's go.

**Pull request merged**
