### PR TITLE
Slays snowflake oldcode, tweaks to exotic seed reagents

### LINKED ISSUE #7020: PLEASE FOR THE LOVE OF ALL THAT IS OR COULD EVER BE CONSIDERED AT ALL HOLY, WHY, BAUDS, WHY???
Plants can now contain advanced mutation toxin, previously only available from end-tier slimes and only one unit at a time.
The chef cooked with some plants the botanist grew from his _early round_ exotic seeds and ended up making several foods _each_ containing **_TEN FUCKING UNITS_** of advanced mutation toxin
Several people took bites and were slimed

@9600bauds 
IT TURNS PEOPLE INTO SLIMES
Not slime people
_SLIMES_
Maybe _don't_ include it in seeds you can just buy from cargo

Yes, the botanist should have checked before growing the plants, but still
This would be WAY too powerful for an antag botanist
_ONE UNIT_ will turn someone into a slime

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #7020

### CODE REVIEW

**Comment by ghost** [comment]
> "amutationtoxin" = 1,

Come on man that's too low. Make it like 5 or 10.

**Comment by 9600bauds** [comment]
Ahaha shit I meant to remove that

**Comment by ghost** [comment]
Please don't. Nobody ever does slimes for it, then we'll never get to see sliming kudzu.

**Comment by 9600bauds** [comment]
> we'll never get to see sliming kudzu.

You're putting me on the brink of a tough decision

**Comment by FudgePucker** [comment]
Should be super rare or not in at all.
If we get any more 'mindbreaker in all food', 'everyone gets slimed by nonantag chef', or 'botany got a kudzu plant that produces heat and plasma, oh and the clown opened the window' rounds, cargos gonna start metagaming and not approve exotic seed crates.

**Comment by Imagebard** [comment]
If you plant exotic seeds(or use them for chef food) without scanning them then you deserve this.
Same thing as a engineer accidentally releasing the singularity, lets not remove the singulo just because of that stupid bullshit.

**Comment by FudgePucker** [comment]
The difference is that if an engineer fucks up the singularity he is warned then banned, in case they 'accidentally' let it loose.

So if I am a shitter chef, I can use exotic seed products in the recipes to 'toe the line' and cause madness. 'Oh my bad, I didn't see the question mark after it', he said as he made advance mutation toxin food that causes everyone to become a slime.

Holy shit fucking advance slime toxin, why would you want that to be mass produced from plants?

**Comment by Imagebard** [comment]
I want it to be mass produced from plants because that's fun.

Everything else you mentioned is an administration issue.

**Comment by ghost** [comment]
Lets remove gun printing from science because they can griff people. Also toxins.

I just named 2 things that are both easier to do without any interactions with the outside world and cause more potent ham than plants nearly every round.

On top of that, they can do the exact same thing but better than botany with their own outpost and round start chem dispenser, can print their own botany bot parts and a gazillion of other things.

Yet having some department other than science have something that only science 'should' do is crossing the line? This mentality is enabling the rampant power creep that science department has become. It's a joke at this point.

**Comment by 9600bauds** [comment]
I mean, I don't disagree with the beep beep science creep, but I don't think it's a relatable analogy since in the case of guns, they're knowingly printing guns, but for exotic seeds you're rolling for random chemicals and you don't know what you're gonna get and you can end up with slimetoxin even when you didn't mean to.

**Comment by FudgePucker** [comment]
I would normally agree with except on two things.
A: Toxins can be done 1000 times better in atmospherics, just a single door has to be opened to get the tank transfer valves.
B: Science printing guns can be punished by security, not growing exotic plants. IEDs shouldn't be able to open lockboxes. Also there are windows all around research so if you see a lockbox come out of the protolathe call sec, can't exactly see what chemicals are in exotic seeds unless you are in botany.
C: Black slimes are one of the hardest to get, OH BUT BOTANY CAN FUCKING GROW MASS QUANTITIES OF ADVANCE MUTATION TOXIN. So now the reasons to spend long times in xenobio are, I guess gold slime cores, thats pretty much it, because you know, OH HEY ADVANCE MUTATION TOXIN IS BEING PRODUCED BY THE BUCKET LOADS, ENJOY GETTING TEN UNITS AT A TIME FAGGOT.
D: A scientist spending time near the bar and kitchen area would raise suspicion, him using a syringe near it would cause him to get lynched, a chef can easily poison food.
E: Oh yea, toxins is totally easier than planting exotic seeds. Nice example.

Seriously, with all the shit you can get from exotic seeds like medicines that are unavailable, I don't think it would be the end of the world if you removed or had a super low chance for THE CHEMICAL THAT TURNS PEOPLE INTO SLIMES AND IS IRREVERSIBLE. Trying to balance advance slime toxin by allowing it to be reversible would just nerf xenobio.

**Comment by Imagebard** [comment]
>but for exotic seeds you're rolling for random chemicals

JUUUUUST scan it.

As for fudgepucker stop being bipolar and pick an side already.

**Comment by ghost** [comment]
Botanist and chef has access to plant scanners which in no way involve RNG and show precise amounts of chemicals in products. Using strange plants without scanning the products is solely the users responsibility, or the one that mixes it with other products in the fridge even if harmful.

**Comment by FudgePucker** [comment]
I'm not being bipolar, keep it as 1 in 100 chance or remove it.
It removes some of the exclusiveness of xenobio and is way too over powered to be in the exotic seeds.

**Comment by ghost** [comment]
This is not a "1 in 100 chance". This is a 1 in a 3651 chemical rolls.

Beyond absurd.

Removing science exclusiveness is a good thing, since science is removing exclusiveness from all other jobs.

**Comment by FudgePucker** [comment]
I am thinking of science as different slices of pie.
Research is fucking stupid how op it is.
Research botany gets a private plant lab of death, with access to atmospherics and a chem Despenser, meaning you have to like being a bitch to the chef and getting bombed to be a botanist.

But xenobio is only good due to its exclusiveness. This isn't 'spend a min on research and print 10 eguns' this is 'spend all round fighting RNG'
Yea if all you had to do was push a button to get adv slime toxin then I would agree with you, but xenobio isn't a fast job that prints rapid fire syringe guns so yea I think they deserve some exclusiveness.

**Comment by ghost** [comment]
Well that makes it clear you have no idea how much effort or luck it took to get amutation toxin in botany, which will just be multiplied by the weighed chem chances.

Go on and try it yourself before commenting about things you know nothing about. At least think back how often you even seen amutation toxin from botany as it is.

**Comment by 9600bauds** [comment]
To be frank it's the same chance as Peridaxon or Rezadone, both of which are expected out of a competent botanist. The only reason why we didn't see more amutation toxin is because it was literally broken up until a month and half ago.

**Comment by ghost** [comment]
What server are you playing on? Nobody ever asks or even expects botanists to do these things, botanists extremely rarely do these things, and when they do nobody cares to even utilize them.

I just checked logs for this entire month, looking in hrefs for "add=peridaxon", indicating the chem was actually filtered out of plants/used in pills.

In this entire month, it was used in 4 rounds. 2 of which it was thrown away as byproduct and 2 in which it was used as medicine.

Check your facts first, then make balance changes according to facts and not emotional outbursts of ignorant players.

**Comment by 9600bauds** [comment]
I'm talking about my own experience from playing botanist (which I haven't done in a few months, though the exotic seeds system hadn't changed since then). Finding a specific chemical is not hard at all if you get Cargo to actually mail you 5ish crates, and I did it quite a few times. Furthermore, just by asking a botanist to, they were able to get peridaxon for Medbay as well.

If you put a HUGE carrot at the end of a stick (amutation toxin, which wasn't even available before) then a lot more people are gonna climb that stick, and they're gonna find it wasn't even hard to. Kind of like brute-forcing the Polar Star once they realize how stupidly OP it is and how easily it can be obtained.

I'm not going on off the emotional outburst of ignorant players, I haven't even really spoken to a player about this, unless you mean the people who opened the issue about this and you're throwing them under the bus. I'm going on off my own intuition as a player and my common sense of what should and shouldn't be a thing. But hey, you have the facts.

**Comment by ghost** [comment]
Indeed, and the facts say that botanists making rare chems is rarer than a blob round.

I see absolutely no reason for any of the chems to have a lower chance than others, since even as it is they are extremely rare to make it into round. It's just so arbitrary, you even nerfed dexalin plus and even the harmless slime people chem.

> then a lot more people are gonna climb that stick

Evidence speaks to the contrary, even though amutation toxin was available for a long time. This doesn't even compare to the 'OP' things you can do in other departments in fraction of the time that actually do get abused regularly.

**Comment by FudgePucker** [comment]
I mean yea, you can buff the other chems, 40 seems way too low for "nothing" (being the mimes special bottle of booze, that is required in recipes and is unobtainable otherwise for some fucking stupid reason), but advance mutation toxin I have mixed feelings with, on onehand yea exotic seeds are fucking annoying and should be somewhat worth it (I tired planting exotic seeds last night and now I see termed, one of them had NO REGENTS AT ALL, the other had just nutrient, the other had blood and nutrient, one had anti radiation chemical that can be made from the dispenser, and the last one just had simple healing chemicals and also made you retarded, also most of them wanted to be in the dark or in the cold.), but on the other hand this is one of the higher tiers of objectives for xenobio to reach, and also its fucking super overpowered, being able to remove someone almost totally from the round as soon as it gets into their system.

**Comment by ghost** [comment]
I have never seen a single traitor botanist use amutation toxin. It's just not worth the amount of time you have to invest to create a bunch of slimes out to kill you, it's a nice fun thing botanists can look forward to during long rounds to offer to people.

The first thing xenobiologist does with it is inject himself because that's what he was aiming for. Check the logs yourself, there's a ton of slime transformations happening in science every month, there's nearly none outside of it. It's written as "x logged in as (grey baby slime 123)" with location included.

I would even say that it's faster, easier and more reliable to get it from xenobio, just not in such quantities once you do get it.

**Comment by Intigracy** [comment]
One time I got a seed packet with amutationtoxin (before the botany rewrite) and put a bunch of plants in the hallway outside botany and announced to the crew "Remember, do NOT eat the plants outside botany."

Clown was the first volunteer, then a bunch of people did even after I kept repeating the message.

10/10

As to this PR, can you lower the chance of cyanide while you're at it? It should be the same as carppheromones imo, it's extremely effective.

**Comment by 9600bauds** [comment]
Not like it really matters given that you can get cyanide extremely easily without exotic seeds

**Comment by ghost** [comment]
@Intigracy 
Why you shouldn't nerf anything : the post.

You yourself said you haven't played botany for months, and it's people like this that want nerfs. At least listen to the logs if nothing else.

**Comment by 9600bauds** [comment]
But if he hasn't played botany in months then how did he use amutationtoxin given that it's only been in botany for a month and half???????????????

**Comment by ghost** [comment]
Second paragraph was for you.

**Comment by Intigracy** [comment]
It was way too easy to transform a majority of the crew into slimes. It's even still possible to do so, you just have to get lucky with seed packets. It only takes one pack for the whole crew.

**Comment by ghost** [comment]
> way too easy

They did it as volunteers! That's like saying it's too easy to monkey everyone because genetics can print dna at roundstart.

**Comment by FudgePucker** [comment]
Monkeys can be made back into humans.
Slimes can't be made back to human

**Comment by ghost** [comment]
Way to miss the point on purpose.

**Comment by Intigracy** [comment]
It's just as easy to force everyone if you take 3 units of toxin to 12
units water and Kinect every piece of food on the station.

Or to shoot those syringes directly into people.

Waaaaaaaaaaaaaaaaaaaaaaah

**Comment by ghost** [comment]
@Intigracy 
Very good point with the diluting of amutation toxin. It makes the entire argument that plants produce "too much" irrelevant as a single unit can slime the whole station.

Since science does in fact produce it faster and more reliably than botany in however lesser ammounts, I can conclude that this entire PRs balance side is misguided and not based on reality but rather "hunches" and "intuition".

Frankly I'm tired arguing with people ignorant of the subject at hand, as it is amutation toxin might as well not exist and no noticeable change would come to pass, that's how rare and insignificant of a factor it is in rounds.

All I wanted was for you to realize that this is removing fun for sake of arbitrary sense of balance for which there is no need in the slightest. What should be done is adding a way for slimes to become human again and not nerfing an already insignificant department in ways that solve nothing at all.

I won't repeat myself further as I've made myself clear several times already, this change is bad and there's nothing but hard evidence that will convince me to the contrary.

**Comment by Intigracy** [comment]
Please merge this holy shit.

**Comment by Exxion** [comment]
Merge now.
I don't care that botanists _should_ scan plants or that the chef _shouldn't_ use exotic plants in cooking because botanists _don't_ scan and chefs _do_ use. I just saw _another_ mass sliming by a nonantag chef.

**Comment by 9600bauds** [comment]
Let's just start a vote in the server or something. Most of the playerbase doesn't come here.

**Comment by Intigracy** [comment]
tfw got traitor only to get griefed by nonantags sliming the crew

**Comment by Exxion** [comment]
image

What a fuck

This vote was to remove it, though. Maybe people would say yes to making it really rare?

**Comment by Intigracy** [comment]
THEY REMOVED BONES NOW THEY'RE COMING FOR OUR OTHER FEATURES

**Comment by Exxion** [comment]
^
(Actual thing that was basically said in chat after the vote)

**Comment by Intigracy** [comment]
Add mint toxin, remove advanced mutation toxin.

Fair.

**Comment by 9600bauds** [comment]
>In this entire month, it was used in 4 rounds.

>>yeah but people are gonna start doing it a ton more when they realize they can do it

>NO LOOK AT THE EVIDENCE

>>>(people realize they can do it and they start doing it)
fak u

**Comment by Exxion** [comment]
Four rounds is at least three too many

**Comment by Intigracy** [comment]
Here's a compromise:

remove adv mutation toxin
add mint toxin
add a new toxin that turns you into a plantperson

presto botany can still griff people but not by turning them into slimes

**Comment by 9600bauds** [comment]
When u code it

**Comment by Intigracy** [comment]
smd

**Comment by FudgePucker** [comment]
I love how most of those poisoned food chefs were non antag 
Seriously, why the fuck would you put adv mutation toxin 1000 feet within the chef?

**Comment by ghost** [comment]
@9600bauds

> In this entire month, it was used in 4 rounds.

I was talking about peridaxon. This is dishonest of you.

> (people realize they can do it and they start doing it)

Do you have any concept of scale? There's hundreds of rounds per month. Singulo wasn't removed because of non antags releasing it on purpose, neither were bombs or plasma or any other form of sabotage that I can think of.

What I don't understand is why people kept eating the food in the mentioned round since slimes can speak common.

> fak u

Please don't resort to imbecilic commentary.

**Comment by 9600bauds** [comment]
You've also said that your evidence spoke to you that people would NOT wisen up and start abusing amutation toxin, which was demonstrably proven wrong (and if you were speaking about peridaxon in the first place, doesn't that make your conclusion kind of dishonest as well?). And jesus H. christ someone can't take a joke.

I also made dex+ slightly rarer because normal dex is also available.

**Comment by ghost** [comment]
> which was demonstrably proven wrong

It was not.

> if you were speaking about peridaxon in the first place, doesn't that make your conclusion kind of dishonest as well?

It was a completely different response to your claims about peridaxon usage.

For my comment on amutation usage, see https://github.com/d3athrow/vgstation13/pull/7037#issuecomment-165555509

**Comment by 9600bauds** [comment]
There's been, to my knowledge, at least two mass slimings in the past two days, including one chef that was perma'd for it. It doesn't help that IT'S NOT HARD TO GET THE CHEMICAL.

**Comment by ghost** [comment]
Found only one in last 2 days, it took over 45 minutes for first slime to appear with round start botanists doing exotic seeds. I wouldn't call 45 minutes easy to get.

**Comment by Exxion** [comment]
45 minutes to get it and another 5 to slime half the station.

**Comment by ghost** [comment]
If you work 45 minutes to griff then you deserve it.

**Comment by Iamgoofball** [comment]
why don't you just make it pick a random chem ID with a blacklist to prevent broken reagents

**Comment by 9600bauds** [comment]
@iamgoofball: because then we're back to square one on whether amutation toxin should be blacklisted or not. Besides that sounds like an awful idea given the amount of chemicals there are, most of them lame. You'd get some variation of an alcoholic drink 60% of the time, some juice 20%, some inert reagent from the chemdispenser 10%, and the remaining 10 would be basically what it is now.

**Comment by Iamgoofball** [comment]
@9600bauds so instead add ethanol to the blacklist(this will block all other boozes), juices are fine, and the base dispenser reagents allow ghettochem.

Bam, problem solved. Deal with amatoxin blacklists on your own.

**Comment by 9600bauds** [comment]
Also what the hell are you doing that it takes you 45 mins to get a certain chemical? Back in my time I would get both peridaxon and rezadone easily, just order like six crates and splice products into chanterelle (nowadays I imagine ii  would be splice phytochemistry into eggplant or something similar). Let it grow and scan the 20 plants at once. Done, you have 80% of all obtainable exotic chemicals in one batch.

**Comment by Exxion** [comment]
The server voted against completely removing amutationtoxin from exotic seeds anyway. As much as I think that's stupid, I am outvoted. Most people don't want it removed.

Small sample size and close margins, but in that particular vote, at least

**Comment by 9600bauds** [comment]
And no, you don't "earn griff" otherwise you'd see non-antag Miners releasing 12 Goliaths into the library (hey it took me a while to get those!), or xenoarcheologists dragging DNA scramble artifacts into Medbay (hey I had to do a bunch of tedious shit to find it!) or all sorts of fucked up bullshit. No, just no

**Comment by ghost** [comment]
Bauds please don't think I'm retarded, I never said it shouldn't be punishable. I meant the power for time invested is deserved.

**Comment by 9600bauds** [comment]
So we've discussed a few hard facts on why I think this is a terrible idea.
- Removes exclusivity from Xenobio for no good reason
- Plants and botany in general have no relation to slimes whatsoever, so I really can't tell what the hell was the guy that added these in the first place going for
- Massassive griff since amutation toxin can't even be reversed
- Changing amutation toxin to be reversible would be double-dipping your turd in Xenobio's mouth by nerfing THEIR end-game research options
- People are ALREADY being banned for the massassive griff
- I still insist it's not hard to acquire the chemical itself at all. I mean fuck, I used to get rezadone and peridaxon nearly every round that I mucked with exotic seeds.

But:
- Vote was nearly 50/50
  till you're blue in the mouth

So it's 10 now
Frankly all I ask is that the vote is actually representative of what the playerbase wants. Trying to discuss this topic here was a goddamn childbirth.

**Comment by 9600bauds** [comment]
another vote is cast
fmatmy
i think 10 is rare enough and I only left it at 1 accidentally so whatever let's be done with this

**Comment by ihadtoregisterforthis** [comment]
That's only fourteen votes in total though. 
In any case seems like it's not rare enough. You could simply go the easy exit and make it antag only.

**Comment by ghost** [comment]
10 sounds fine.

**Comment by 9600bauds** [comment]
I believe the controversy has been slain

**Comment by Imagebard** [comment]
I do, too. 
It seems people have no problem with mutation toxin as long as its not every other round.

**Comment by Imagebard** [comment]
Damn it Clusterfack, I was still making my comment.

**Comment by 9600bauds** [comment]
ty schizo man of optimization

**Pull request merged**
