### PR TITLE
Adds blood red variety snowmobiles to snaxi and snowbox nukeops

### LINKED ISSUE #31607: Nuke Ops should get snowmobiles on Snow Station
(WEB REPORT BY: soyconsumer REMOTE: 206.221.180.138:7777)
Nuke Ops should get snowmobiles on Snaxi, bonus points if they're blood-red.

[featurerequest]

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][qol]

## What this does
Closes #31607.

## Why it's good
jetpacks ain't very snow themed.

## Changelog
:cl:
 * rscadd: Snaxi and snowbox nukeops now have thematic snowmobiles.

### CODE REVIEW

**Comment by shitmaper** [comment]
I made some sprites for nukie snowmobiles , but  gave up trying to add them because I cannot into code.
Feel free to use them if you want
snowmobiles
snowmobiles_off

**Comment by ErrorsWindows** [comment]
if it was up to me we'd have those kickass flying ski buggies [like in The World Is Not Enough](https://youtu.be/MQQLqRYm4vg) but I guess we'll have to just meet halfway and do black and red snowmobiles

**Comment by gurfan** [comment]
Use the sprite shitmaper posted.

**Comment by SECBATON-GRIFFON** [comment]
> Use the sprite shitmaper posted.

did just now

**Pull request merged**
