### PR TITLE
Bottle and overlay icons for chef's sauce.

### PR DESCRIPTION
**Pull request by Eneocho**
### What this does
Chef's sauce bottles now have a special shape and colour and pouring some on a meal will leave an overlay (this overlay can be hidden with other overlays, such as mayo, for example).
fish sauce
fish sauce
### Why it's good
How can it be a sauce if it doesn't even have an overlay?
:cl:
 * rscadd: Chef's sauce now has a special bottle and overlay.
 * tweak: Makes chef's sauce reagent colour more purple than red.
 * imageadd: Sprites for the aforementioned overlay and bottle.

### CODE REVIEW

**Comment by BomberBro** [comment]
Will the sec dorms get one?

**Comment by Eneocho** [comment]
I didn't even notice the phallic implication until you mentioned it lmao.

**Comment by jwhitak** [comment]
I like the notion that this condiment gets the treatment it deserves.

I don't like the sprite hooooly sheeeeeet

**Comment by Inorien** [comment]
what is that icon supposed to be

**Comment by djkramer123** [comment]
what the fuck

**Comment by Kurfursten** [comment]
What is the icon supposed to be? It looks like a poorly compressed pink anchor

**Comment by Hinaichigo** [comment]
Not sure about it having an overlay.

**Comment by Eneocho** [comment]
Guess I'll try again later

**Comment by jwhitak** [comment]
Try again later but with a less cursed sprite

**Comment by west3436** [comment]
Also no overlay since the secbirds will use it as a metacheck
Just say it's a clear condiment in the description

**Comment by Eneocho** [comment]
> Try again later but with a less cursed sprite

It was supposed to be a weird anchor shaped bottle for that muh exotic 1 gorillion dollars (5 dollars) sauce energy. I truly and unironically didn't even notice the phalic shape until it was pointed out. I'll remake it.

**Pull request closed without merging**
