### PR TITLE
New Stage 3 Disease Effect: Piratitis Syndrome, aka Tooth Decay

### LINKED ISSUE #10464: Two more virus ideas I'll never code but say I will
Tooth decay - Makes your teeth fall out.  Interesting exemption for mobs without teeth.  Hallways littered with TEEF.
~~Giggingtons - Makes you harmlessly giggle.  Tricks atmospheric technicians into thinking there is a N2O leak.  Weird out everyone else.~~ Added!

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #10464

:cl:
* rscadd: Added a new Danger 4 Stage 3 disease effect, Piratitis Syndrome. The infected will periodically lose some of their teeth and start talking like a pirate.

### CODE REVIEW

**Comment by Blithering** [comment]
Wouldn't scurvy be a more appropriate name?

**Review by Kurfursten — COMMENTED** [review]
Code doesn't seem to kidnap the princess of Canada at all

**Comment by DeityLink** [comment]
> 
> 
> Code doesn't seem to kidnap the princess of Canada at all

I didn't have that reference, but now I do and I have updated the code accordingly.

**Review by Kurfursten — APPROVED** [review]

**Comment by Eneocho** [comment]
> 
> 
> Wouldn't scurvy be a more appropriate name?

That would require bleeding gums and a way to stop the effect by drinking orange/lime/potato juice.

**Pull request merged**
