### PR TITLE
Restricts Vox from being wardens

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Please discuss.
Do NOT merge the PR unless the server vote concludes positively. Close the PR if it ends at 50/50 or a higher amount of downvotes.

:cl:
 * tweak: Vox can no longer be wardens.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
if you don't give a motive for your change it should be closable without giving a motive as well

please explain the motivation for this change in the body of the PR.

**Comment by tuypo1** [comment]
I am very much in support of human only heads and QM but warden I am not so sure about and I would rather reserve judgment until if we finally get rid of non human heads

**Comment by RealestEstate** [comment]
Warden is arguably a position of power despite not quite being a head of staff.

**Comment by cloutcode** [comment]
what is the issue with vox being in positions of power any other alien race can be in
i don't get it
both these dumb prs came on the heels of the first dumb pr, the bug job one, which also makes no sense because read above
dumb dumb dumb stupid

**Comment by boy2mantwicethefam** [comment]
This is far more divisive so I'm gonna close this

**Pull request closed without merging**
