### PR TITLE
Ice mining

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds ice crystals to the basic asteroid generation, they can be ground up for ice reagent.

 Additional QoL
 - Ores now stagger, rather than all being the same pixel_x and pixel_y
 - Rockernaut overlay, lacking a specific one, will default to the iron overlay when the mining scanner is used

Additional usage ideas requested
:cl:
* rscadd: Added ice crystals to the asteroid generation, they can be ground up for ice reagent.

### CODE REVIEW

**Comment by Irradiation** [comment]
Roid ice challenge when?

**Comment by brndd** [comment]
Can the ice be used as starbase fuel?

**Comment by MadmanMartian** [comment]
That's the intention behind plasma. What did you have in mind?

**Comment by DrSnips** [comment]
Applying an ice crystal should cool reagent containers similar to applying hot things for chem heating(cooling) stuff.

**Comment by DrSnips** [comment]
When ground it should make 20u of ice to be consistent with other stuff.

**Comment by MadmanMartian** [comment]
Okay, I'll up the amount it grinds into. Currently it grinds into 10.

The cooling seems like an interesting thing. When doing it, it consumes the crystal perhaps?

**Comment by SonixApache** [comment]
add them to the ice roid walls

ice swords when?

**Comment by DrSnips** [comment]
Id say no on the consume part. If I throw my drink on some ice the doesnt just vanish completely. Yes the ice "melts" somewhat but lets use some suspension of disbelief and say it stays around for QoL.

**Comment by Killette2** [comment]
Give us ice tiles for sliding puzzles

**Pull request merged**
