### PR TITLE
Reworking Boxstation Security

### PR DESCRIPTION
**Pull request by ghost**
So... I'm setting ahead to try and rework Boxstation Security. It's not the first time I change up the areas (expanded Brig and Sec Office area a little two years back). I will put the pic here immediately since it speaks a lot, but I'll put a detailed change list and my reasoning after that

Overview of Security after the changes :

overview

Changes reasoning:

**Boxstation Security has seen a major rework. Functionality shouldn't be too critically different, but the area has been expanded and tweaked as noted below.**

Yeah, Boxstation Security is pretty big now. I'm pretty sure it's anywhere from 50 % more to double vertically. Horizontally it only gained a few tiles near the top. I feel like this department needs to be large, especially the hallways since you're usually gonna be dragging a prisoner around. Armory especially forced me to implode the department outwards to get rid of the tiny, 1-tile corridor, super cramped Armory.

Oh and yeah, it's in black now. I think Security looks good in black, but it has that "high security" feeling to it. If it's too much, I can revert to white tiles. It'll be a lot of work, but it's not critical to my design. I was just tired of constantly switching between light and dark tiles, and found Deff's dark style Security pretty sexy.

**The Permabrig has been fairly expanded to make it easier to navigate in. There's now a small (3x3) Brig Office, perfect for riot emergencies. The Prisoner gear lockers are neater, there's two Isolation cells now and the vents within them were removed to justify them at all compared to normal Brig (most antags can ventcrawl). Execution and Permabrig now have a gap, so can't easily break from one into the other.**

Permabrig is larger now, though the horizontal size was mostly to make sure the layout is not -too- crazy compared to the rest of Security. The small office has a Permabrig shutdown button for emergencies. I doubled the Isolation cells and removed the vent to make it easier to justify putting prisoners in here.

The gap between Perma and Execution, and the removal of the soap, might be a bit controversial. One proposition would be to change the two r-walls at the entrance into windows to give a more straightforward escape route than just spacing yourself. I'm looking for feedback here, as this is a MASSIVE vulnerability to replace a pretty middling one (you can loot shit from Execution, but not enough to hack doors or anything new). As for the soap... I can add it back in honestly, or move it to somewhere easier to retrieve for Security, I just felt that it was busywork for Security Officers as letting Perma prisoners have soap was accident central, I personally always remove it when permaing prisoners.

Oh and yeah, the cutlery is plastic now. Turns out silverware is pretty lethal, who knew, huh ?

**Interrogation, Evidence Storage, Warden are all a bit bigger. Warden especially has more doors to make it way easier to slide into Interrogation or Security Office.**

Bigger is nice as it allows more people to fit in, and people to flow more naturally. Warden especially is a blessing for Wardens, since you no longer have to exit through the front door and run through the often clusterfuck-y main hallway to reach Interrogation or Security Office

**Armory has been massively reworked. It's now a fairly large room, with items inside Security-locked lockers (Sec, not Armory access). There is a shutter access opened a la Defficiency so Wardens can very easily let people in to grab stuff.**

**Boxstation's Armory riot gear is now more comprehensive. There is now more pistol ammo (2 mags per gun). There are now 4 space suits in suit storages.**

It is definitely a change that has to be seen. There is a bit more gear overall (weapon amount was kept though!). The shutter access should be a MASSIVE improvement over the old headache of having to run back and forth a one tile wide walking way to let people in, same with the shutter desk which is more accessible from both sides. The lockers are Security access, if you don't have it and need guns, you'll have to get it unlocked. I'm aware it might be a tiny bit controversial, but in my mind it's not a gigantic issue... maybe we'll want to add locker hacking without emags eventualy ? There's so much shit in lockers you can't get on deadpop no command

Also, yes, you cannot break into Armory from space anymore. This is probably the biggest balance change here, as it is, and intended from myself. I think Boxstation armory is too vulnerable, and I've personally broken into it... dozens of times ? It's trivial to get a full toolbelt and a space suit, and if there's no AI to check the atmos alarm you're fucked. Now you have to make an effort to either break from space into adjacent rooms and quickly breach the new wall (or just C4/thermite everything tbh) or try something more subterfugey. There is still a blindspot from Warden too, just less comprehensive

**Expanded Security Office area. HoS, Firing Range, Toilets and a brand new, small Sec Dormitories were attached to a hallway rolling around Armory. Sec Office itself was cleaned up massively and should be easier to use without being expanded too much.**

Again, has to be seen. HoS is a bit bigger, toilets are quite bigger but it's fluff honestly (and well, a bonus blindspot). Dorms are also a cam blindspot. Security Office has been massively simplified but still has every last piece of gear it had, and an extra gear locker (the food machines were moved up to the hallway)

Sec Dorms is mostly to give a safe place for officers to AFK if needed, especially with the personal lockers... and fluff. And illegal shit, since as stated above it's a camera blindspot, and unlike Execution it is close to the rest of Security staff rooms.

Firing Range is quite larger. Honestly it was an issue of the old layout being weird to me. I can try and circumsize it a little if that's an issue.

Oh and yeah, Security has shutters now! Cam blindspot too, and since it has no air alarms a weakness for space breaches (I'm sure someone will figure out something).

**Removed soap from Permabrig Showers. Removed the "experimental weapons" locker from Armory. Removed Permabrig into Execution breakout strategy as mentioned above. Culled Permabrig Bedroom camera as it allowed AI to spectate part of the Execution room (and adds a small blindspot in Perma that isn't toilets for crafty prisoners)**

Ditto above, the stuff that could be controversial. Soap gone from Permabrig, the experimental weapons were removed (I found they were just silly, but if it's too tough I can re-add it in). The shortcut. The Permabrig Bedroom so AI can't easily tell when Execution Room is being used (also gives a blindspot for both AI and Security, for mindplay and all)

Oh, and unlisted, but obviously the meteor shield was reconnected to account for the massive change in BULK for Security

Obviously I'm redoing an entire department so I'm conscious this is going to be on community decision. I'll keep tabs on the thread. I can address a lot of stuff more, honestly, as long as it's not "this is too big, trash everything". It took me a while to make everything fit together without really dumb double walls and weird alcoves and such.

:cl:
 * rscadd: Boxstation Security has seen a major rework. Functionality shouldn't be too critically different, but the area has been expanded and tweaked as noted below.
 * rscadd: The Permabrig has been fairly expanded to make it easier to navigate in. There's now a small (3x3) Brig Office, perfect for riot emergencies. The Prisoner gear lockers are neater, there's two Isolation cells now and the vents within them were removed to justify them at all compared to normal Brig (most antags can ventcrawl). Execution and Permabrig now have a gap, so can't easily break from one into the other.
 * rscadd: Interrogation, Evidence Storage, Warden are all a bit bigger. Warden especially has more doors to make it way easier to slide into Interrogation or Security Office.
 * rscadd: Armory has been massively reworked. It's now a fairly large room, with items inside Security-locked lockers (Sec, not Armory access). There is a shutter access opened a la Defficiency so Wardens can very easily let people in to grab stuff.
 * rscadd: Boxstation's Armory riot gear is now more comprehensive. There is now more pistol ammo (2 mags per gun). There are now 4 space suits in suit storages.
* rscadd: Expanded Security Office area. HoS, Firing Range, Toilets and a brand new, small Sec Dormitories were attached to a hallway rolling around Armory. Sec Office itself was cleaned up massively and should be easier to use without being expanded too much.
* rscdel: Removed soap from Permabrig Showers. Removed the "experimental weapons" locker from Armory. Removed Permabrig into Execution breakout strategy as mentioned above. Culled Permabrig Bedroom camera as it allowed AI to spectate part of the Execution room (and adds a small blindspot in Perma that isn't toilets for crafty prisoners)

### CODE REVIEW

**Comment by ghost** [comment]
Ah, the infamous step_... good thing we changed that. brb

**Comment by Chazach** [comment]
I just personally absolutely disagree with the design philosophy here. Black brig looks bad. 
Its now fucking massive for very little reason, especially since the only real content added is a microwave and some beds.
Making perma more escape proof, removing the soap and execution room link is something I disagree with.
Cutting the execution cam is something that you should have to do IC.
Removing the big boy locker is one thing, but you also prevent anyone from entering the armoury via space, tele'ing in, or subspacing shit and I dont feel like security honestly deserves that.
Brig office is just pure bloat without purpose, I cant even theorycraft it unless there are 15 sec and all of them want to watch cams at once.
Lining the sec office with windows is just carpbait, it was at least tolerable when they only could smash the HoS office.

**Comment by Irradiation** [comment]
Off the top of my head, here are a few criticism/stuff/things that come to mind:

-The experimental weapons locker is more a less a staple of every map's armory. It's more or less the extra unique flavor that each map gets that makes it a tiny bit more unique than the last (Deff gets a grenade launcher, packed gets a plasma pistol, box gets Laser Rifle + 2 Vectors, etc). By removing it from Box, you're also removed Vectors from the armory.

-I wholly disagree with locking every gun and armor inside a security-locked locker. On top of making the armory less breachable from space (Whereas every other map's armory can be breached from space, minus Bagel), you now have to go through a quite tanky locker to even loot the stuff. So long are the days of opening the armory to the crew/greytide/robbers/security, now you have to fiddle with lockers, which robbers might not necessarily have access to (and if they do, then lockers are a moot point).

-Armory not being exposed to spess anymore pretty much makes the Shaft Miner's toy moot.

-Armory being thiccer is nice for walking around. It sucks to keep bumping into people trying to walk around the armory and fiddling with windoors 24/7.

-Hurray for more Peestol ammo. RUBBER BOOLITS WHEN?

-Bomb Suit lockers are a purely RP meme that nobody ever puts on. You might as well add more Biosuits, since those are actually useful.

-RIP the extra recharger in the armory hallway thing.

Security dorms is nice, but a bit too big if you ask me.

-Holy fug this is a long walk to the firing range and back. I could probably get to the bar or bridge faster than the firing range if I start from the brig lobby.

-Security lobby/meeting room having big nice windows exposed to space is going to get that room depressurized pretty fast via Carps or anything else and you know it.

-Watch out, there's no toolbox, free crowbar, flash, gauze, radio and FREE DONUT BOX in the security lobby anymore. The security metaclub has been alerted of your actions.

-Evidence room didn't really need to get thiccer. Also why are there racks in the middle of the room? I thought the point of the lockers was to tell which locker's content belonged to X.

-I don't really see the point of an extra observation/camera room under the autopsy/torture/chemical execution room.

-Having an extra solitary confinement room is pretty okay.

**Comment by ghost** [comment]
I'll prepare a first revision for some of the points. Honestly, the one core part of the change is making Armory central. I know it's different from the other maps, but it's something I do want to try

It's insanely trivial to break in as long as you get a hardsuit (which honestly is not challenging, especially given how many jobs can get into EVA now, which reduces the gravity of hacking in). Thermite, welder tanks, or just tools and time can all punch through easily. I understand the concern, but at the same time having the armory emptied half the rounds gets old fast. Antags can easily bypass the lockers with emag/door spell/hulk-ish abilities/stealing access... or if Security leaves them unlocked

I'm split on the locker thing. I could make them all access if this is a serious sticking point

I'll re-add the missing items, I don't want to gimp gear

**Comment by ghost** [comment]
I like the expanded execution room, secondary solitary confinement, the little camera room, the barracks room, and the meeting room (with what looks like two seats at the head of the table for the Warden/HoS?) a lot. I would say something about double-walling the armoury, but seeing as it's a bit deeper in it should(?) be okay, and I guess the lockers fix that, if not in a way I like so much.

While not an issue I have with it, I think some people might dislike the size of it and the spaciousness in some parts.

EDIT: In addition, after thinking about it for a few minutes, the actual issue I have with this is 'why?'. Box's Brig just doesn't feel like it needs redesigning to begin with.

**Comment by SonixApache** [comment]
Holy shit, it's huge.
And yet there's still no security EVA.

Really like the expanded armory (though the supersecure lockers are big gay).

Space between the permabrig and execution chamber? Really?
Removed the soap? Really?
Come on, dude.

I really dislike the briefing/gear room. Bad design.
Armory should really be exposed to space!
And is that a special dorm just for sec? Really? I mean, it's cute, I guess, but kinda weird.
Also added a cola machine, but no smokes machine. Priorities, dude.

Maybe you should try doing what Meta does, with it's gulag and shuttle? Having a sec shuttle would be nice.

**Comment by Chazach** [comment]
@dylanstrategie the lockers have like 20,000 HP, the only thing thats opening em is stolen access or emags

**Comment by ghost** [comment]
Aight, fine, I'll make the lockers all access. This way we can have the style of armory lockers without the balance implications.

I'm noticing a lot of feedback for Perma breakouts, I'll try my idea then, hold on

**Comment by iFlashYou** [comment]
Just put the armor stuff on racks, there is no need to make everything baby proof. This is a research station, not some high-tech military station.

**Comment by ShiftyRail** [comment]
I don't like the design and the design philosophy at all.

Brig is way too big. This meeting room will have on average 2 or 3 officers, so it'll always feel empty.
The whole shooting range is a waste of space.
The corridor leading to the shooting range and the shooting range area are way too big to be used. I doubt you can even see the end of the corridor at the front. It'll just feel empty and soulless.

Armoury at the heart of brig is a design that doesn't fit the playstyle of /vg/station in my opinion.
Guns shouldn't be nested that deep. In the event of a cult, if someone wants to take up arms, they should be able to ; weapons in racks just look better in my opinion.

I liked the simplicity and clarity of old box brig. Some elements of this rework - the renewed lobby, more aesthetic, the secondary solitary, and the brig doors as well as the warden-interrogation link - are good, the rest is just unneeded or badly designed.

**Comment by ghost** [comment]
overview

- Re-added multiple items that were missing
- Re-added Box's super locker as is
- Armory lockers removed and replaced with racks
- Added a more standard breakout way for Permabrig... you'll have to bash through six different windows and go all the way down to hallway for it though
- Added pistol rubber bullets and rubber bullet box
- One more biosut locker, one less EOD locker
- Added two rechargers in the Secure Armory
- Racks changed into more lockers in Evidence Room

**Comment by ghost** [comment]
I'll redo it with the actual screenshot in a bit, fuck me

**Comment by Kurfursten** [comment]
I only trust like 3 other people besides myself to do working disposals, so I am going to need you to load up your game and test disposal deliveries to both the HOS and security office.

**Comment by ghost** [comment]
Fair enough, hold on, I have a screenshot to refresh

**Comment by ghost** [comment]
Well... they both go into Security Disposals... how do I fix that ?

**Comment by Kurfursten** [comment]
You need to set up sort junctions. They work like normal T junctions but when a package tagged with the matching ID tag hits it from the straight entry path, it takes the branch instead of continuing straight. For all items coming in from the branch side, it behaves like a normal disposal and goes with the arrow down the "main" route.

What you're going to need to do is set up 2 sort junctions, one to output into the security office and one into the HOS office. It's slightly complicated by the fact that security is special and we want it to further go through security disposals after hitting those two offices, but we don't want the rest of the trash loop to go there. The best way to learn this is by experience, so I recommend downloading and opening the old version of box and following the disposal loop to see how we did it before. Basically we set 2 sorters way down at the entrance to the brig to peel those packages off onto a separate loop.

**Comment by ghost** [comment]
I'm checking out the general design with another mapper. I think I saw the sort junctions, thankfully I have... tgstation_snow for easy reference

**Comment by Lunstra** [comment]
The deffpalette is nasty, the central armoury position is also nasty since it removes space break-ins and nuke ops being able to bomb it, the shooting range doesnt need to be that big, the meeting room feels too big but on closer inspection I think that's just cause it's had the line of tables next to the lockers it currently has nuked, and I honestly don't really see the point at all for sec to have their own private dorms room, that just feels like bloat for bloats sake. But the extra solitary room, the warden interrogation link and the actual design, just not placement, of the new armoury is good. I dunno, could use more work I guess.

**Comment by Kurfursten** [comment]
Everyone else has major concerns so let me raise a minor gripe.

I don't like the central evidence lockers. They are not anchored so they just get pushed out of place by imprecise walking.

**Comment by KingofHONK** [comment]
not to shit all over your work, but im just gunna be honest here
https://www.youtube.com/watch?v=umDr0mPuyQc

**Comment by ShiftyRail** [comment]
I think it would be better to partition the PR in smaller parts. Brig dorms and maybe the renewed central area ideas are popular, they could be salvaged.

**Comment by d3athrow** [comment]
in perma the AI has a blind spot where the beds are on the bottom most row.

**Comment by ghost** [comment]
I'm going to close this PR in favor of Osseus/Veer's PR since he salvaged most of what was important for me (minus non-spaced armory but I don't need to die on that hill) and this one has... very slim chances of passing anyways on its own

And yeah Pomf, that was sorta intended. Also a bit of an issue where having cameras in the Dorms bedrooms means the AI can see way into Execution

**Comment by SonixApache** [comment]
Your attempts were not in vain.

**Pull request closed without merging**
