### PR TITLE
Fixes #7807 and a bunch of Mixed Mode + Cult related issues

### LINKED ISSUE #7807: Mixed mode cult blood objective bugged
I covered 1/2 of the central hallway, all of the bar, all of dorms, all of the fitness room, some maint behind it and some of the hallway between bar and medbay
I only needed 160 tiles covered
The objective never completed and we culted the janitor before he was a problem
also I guess the shuttle was coated in blood too, but the objective never completed.

### PR DESCRIPTION
**Pull request by DeityLink**
Who the heck even added Cult to Mixed Mode anyway? I mean it's cool but there's a lot of things to check so you don't mess up objectives and stuff.

On that note, I added a new proc is_round_cult() that either returns ticker.mode if the round is cult, or the cult mode inside ticker.mode.modes if the round is mixed with cult, or null if the round has no cult going on at all. So from now on instead of doing

> if(ticker.mode.name == "cult")

you do

> var/datum/game_mode/cult/cult_round = is_round_cult()
> 
> if(cult_round)

etc

Also fixed a weird issue about blood cleanables and DNA.

Oh and lastly, /datum/admins/proc/check_antagonists() was taking half of player_panel.dm and I could never find it when I needed it so I moved it to its own new file. And fixed a typo in it.

### CODE REVIEW

**Comment by PJB3005** [comment]
Uhm, `is_round_cult()` seems like it'd return a boolean, not a reference to the gamemode.

``` DM
var/datum/game_mode/cult/cult_round = is_round_cult()

if(cult_round)
```

Seems weird, following might be better IMO:

``` DM
var/datum/game_mode/cult/cult_round = get_gamemode() // Does get_gamemode actually exist?

if(istype(cult_round))
```

**Or:**

``` DM
if(is_round_cult()) // Though in this case the is_round_cult() functionality wouldn't matter.
    var/datum/game_mode/cult/cult_round = get_gamemode() // Does get_gamemode actually exist?
```

**Comment by DeityLink** [comment]
@PJB3005 is_round_cult() is meant to be used mostly to check if the round is cult. I originally intended to have it return a boolean, until I realized that returning a reference not only gave the same result for the checks but allowed for a much broader use of the proc. So I'll stick to my guns here.

get_gamemode doesn't exist. In the future we could further improve is_round_cult() into something that returns any specified game mode, for example mode_exists("cult") (using the mode's config_tag string) But since only cult needs it for now I say we it's good enough for now. I do plan to expand upon Mixed mode so I'll definitely get back to it.

**Comment by gbasood** [comment]
When gamemodes get refactored into an event-based system it should be a lot easier to check if a specific event is active (i.e. cult) Pseudocode:

``` DM
if(/datum/event/cultists in list)
```

**Comment by d3athrow** [comment]
yeah with is_something_proc() you return 0 or 1, not a datum.

**Comment by gbasood** [comment]
ideally gamemode datums would have a check_mode proc, and mixed mode would have an overriden proc to check which modes it was running

**Comment by DeityLink** [comment]
There we go. Replaced the is_round_cult() proc with a find_active_mode(var/config_tag) proc.
So you can grab any specific mode. For instance in our case we'll do find_active_mode("cult") and grab the datum if it exists, but now it works for every mode type. I've added a list of all the used modes' config tags above the proc.

**Comment by DeityLink** [comment]
Also fixed cult objectives not appearing in the Check Antagonists panel during Mixed mode rounds.

**Pull request merged**
