### PR TITLE
[COLLABS] CHANGELOG MERGING HAS TO BE PUSHED MANUALLY

### PR DESCRIPTION
**Pull request by Intigracy**
At minimum it's going to be until early next month, might end up longer.

Either push the changelog after you merge something like a real bro, or just have it done once/a few times a day by someone.

### CODE REVIEW

**Comment by Intigracy** [comment]
@Clusterfack give me the meme tags.

**Comment by ghost** [comment]
Why

**Comment by Intigracy** [comment]
MYOB fam

**Comment by Intigracy** [comment]
Because eggman's bot isn't going to work until at least next month.

**Comment by Intigracy** [comment]
nooooo we woulda fixed every issue ever if you merged this

**Pull request closed without merging**
