### PR TITLE
Vox Sprite Update / Raider Resprite

### PR DESCRIPTION
**Pull request by drawsstuff**
For the past few months, I've been working on Clockworkdoorhinge's old abandoned vox raider resprites. In this time I've made significant progress and I'm nearing the halfway point with the project. Given that, now is the time to open a pull request on the matter to gauge public opinion on the matter. 

I've yet to decide if these new raider sprites should be universal for all vox, or apply only to raiders, and thus your feedback is welcome. The goal of this project if it should be a universal sprite change is to include all prior vox sprites, a few new sprites, and possibly the removal of starting departmental suits in favor of an alternative method of nitrogen tank storage. I will post all sprites to this pr in the comments as they are completed. 

CREDITS:
Clockworkdoorhinge: Armored Raider Suit and Original Rehaul Sprite
Drawsstuff: Absolutely everything else, clothing, hair, colors, ect.

### CODE REVIEW

**Comment by drawsstuff** [comment]
COLORS: 100%

Green
Emerald
Azure
Brown
Grey
Light Green

**Comment by gurfan** [comment]
what does it look like in game?

**Comment by drawsstuff** [comment]
HAIRS: 100%+
sq
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

NEW:
image
image
image
image

**Comment by drawsstuff** [comment]
EYES: 100%
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by drawsstuff** [comment]
MASKS: Incomplete
image
image
image
image
image
image
image
image
image
image
image

**Comment by drawsstuff** [comment]
GLOVES: Incomplete
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by drawsstuff** [comment]
SHOES: 100%
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by Exxion** [comment]
But why

**Comment by drawsstuff** [comment]
UNIFORM: Incomplete
image
image
image
image
image
image
image
image
image
image
red
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by gurfan** [comment]
these look like they will be twice the size of humans

**Comment by drawsstuff** [comment]
> these look like they will be twice the size of humans

I would include an image, but github is having issues processing them at the moment. They *are* larger, but not by two times the size.

EDIT:
image

**Comment by help-maint** [comment]
Maybe you can upload somewhere else e.g. discord and edit a link into the OP

**Comment by drawsstuff** [comment]
> Maybe you can upload somewhere else e.g. discord and edit a link into the OP

I'll give github a day to get its shit together

**Comment by GreatBigFailure** [comment]
I like them a lot but don't want them for all vox. Just raiders or special cases. Mainly because they'll look a bit too out of their element if they're too common in the station. A midround species would be good though.

One thing to note when you get them working in game: test attaching robotic limbs, including heads, to them. Current vox already look a bit "off" with them, let alone these.

**Comment by Exxion** [comment]
Hold on. The side sprites are way more than 32 pixels wide. How do you intend to actually put them in the game without making it look awful?

**Comment by drawsstuff** [comment]
> Hold on. The side sprites are way more than 32 pixels wide. How do you intend to actually put them in the game without making it look awful?

Same way the rest of the over 32 sprites are handled

**Comment by Exxion** [comment]
So making them wider than a tile? I said "without making it look awful"
So what, the tail would overhang the next tile?

**Comment by gurfan** [comment]
sprites larger than one tile cause lots of visual issues like clipping through walls

**Comment by Eneocho** [comment]
looks like a lizard and less like a bird, bad

**Comment by drawsstuff** [comment]
SUITS: Incomplete

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by drawsstuff** [comment]
HEAD: Incomplete
image
image
image
image
image
image
image
image
image
image
image
image
image

[Github crapped out again here, more updates later]

**Comment by KillFurries** [comment]
making vox look more like clockwork's rape furry porn when clockwork doesn't even play the game
are you really going to add all this just so drawsstuff can get off better and have more porn accurate furries to get kidnapped by? this goob tier, actually far worse
stop
advanced faggotry

**Comment by drawsstuff** [comment]
> making vox look more like clockwork's rape furry porn when clockwork doesn't even play the game
> are you really going to add all this just so drawsstuff can get off better and have more porn accurate furries to get kidnapped by? this goob tier, actually far worse
> stop
> advanced faggotry

KillFurries
Joined 27 minutes ago

If you're so scared of me that you need to make a sockpuppet account for the sole purpose of downvoting and posting clown memes, maybe this PR will be better suited for an ingame poll instead of a github PR.

**Comment by usnpeepoo** [comment]
yikes this is not wholesome

**Comment by djkramer123** [comment]
seems neat if it's for raiders, dunno about for all vox though

**Comment by KillFurries** [comment]
> If you're so scared of me that you need to make a sockpuppet account for the sole purpose of downvoting and posting clown memes, maybe this PR will be better suited for an ingame poll instead of a github PR.

didn't address anything I said or explain why the server catering to your furry fetishes is ok
it's not relevant, but this isn't a sockpuppet account
the PR is so bad that everyone who passively lets it go through should be ashamed, everyone should make an account and voice their opinion about having a race designed by a furry porn artist who doesn't play the game. An entire race styled around furry porn of dudes with blown out assholes being tied to toilets and getting raped, that's exactly what vox should be based on apparently

**Comment by drawsstuff** [comment]
> didn't address anything I said or explain why the server catering to your furry fetishes is ok
> it's not relevant, but this isn't a sockpuppet account
> the PR is so bad that everyone who passively lets it go through should be ashamed, everyone should make an account and voice their opinion about having a race designed by a furry porn artist who doesn't play the game. An entire race styled around furry porn of dudes with blown out assholes being tied to toilets and getting raped, that's exactly what vox should be based on apparently

If this is infact your first account I'm going to have to ask that if you want to discuss this PR that you should do so in a manner that actually gives me advice on how to improve upon them. Some limitations apply in the fact that the "Frame" needs to be the same to ensure that no sprites need to be remade.

**Comment by FlintBarrel** [comment]
Should be raiders and admin only, they kinda look more like lizardmen than the chickens vox are supposed to be, personally.

**Comment by KillFurries** [comment]
> If this is infact your first account I'm going to have to ask that if you want to discuss this PR that you should do so in a manner that actually gives me advice on how to improve upon them. Some limitations apply in the fact that the "Frame" needs to be the same to ensure that no sprites need to be remade.


I made my criticism perfectly clear
throw this PR in the trash and don't style vox after furry porn, drawn by the guy who draws awful furry porn, no one wants to look at your fetish shit in a space station simulator
didn't admins remove the furry porn of your character getting raped from the library? The one that was drawn by clockworkdoorhinge? Was that supposed to be a preview for this PR or something?

**Comment by drawsstuff** [comment]
> I made my criticism perfectly clear
> throw this PR in the trash and don't style vox after furry porn, drawn by the guy who draws awful furry porn, no one wants to look at your fetish shit in a space station simulator
> didn't admins remove the furry porn of your character getting raped from the library? The one that was drawn by clockworkdoorhinge? Was that supposed to be a preview for this PR or something?

I'm sorry, but these vox are not styled after furry porn. The earliest "clock style" vox dates back far before those images' creation, and if you would like proof, I am happy to provide. Said sprites were also created before the creation of said image, so you'll need a different leg to stand on. These sprites have nothing to do with pornography or anything erotic seeing as the server that runs this codebase does not allow for such things. If you would like to view furry pornography, I would advise you instead try another server such as Skyrat, Citadel, or Virgo. I have links to these codebases if you would like them.

**Comment by tinysaturn** [comment]
They look like retarded pickle lizards. 
Also if these become sprites for vox raiders, you can say good bye to pretending to be a trader, awful.

**Comment by Blithering** [comment]
I'd say make them either some buy-in loud raider option or admin only, making all raiders like this makes them unable to blend in with legit traders. 
Sprite wise, there's a couple of bits of inconsistency, such as the syndicate mask having separate eyeholes on the side view but a monovisor on the frontal, and the sleeve length being a bit fast and loose.

**Comment by PavelCIA** [comment]
idk seems a bit too special snowflake, like something you'd see on VORE

Edit: unironically

**Comment by ShiftyRail** [comment]
I really don't like it. Those voxes seem really tall and wide in an artsyle where humans are small and short compared to other sprites. 

I don't know how to rigorously explain it, but even if that new vox is only 20% taller, it feels like it is 3 meters tall. Much like the mice feel smaller than they are.

I believe it will look extremely silly when an east-facing vox raider has its tail clip with the wall, or when a north-facing one has its head constantly butts with the airlocks before opening them.

What of buckling ? How are you going to fix that ?
Why does the HoP's hat seem to gain so many pixels when a Vox raider tries it ?
Lorewise, what do the raiders eat that make them so buff ?

It just looks bad to me. The fact that they are drawn in a way that dwarves humans and carries the obvious connotation of a superior superhuman race doesn't help sell it either. It looks like one artist forcing his own vision of the race on the server, a vision which is far from unanimous.

**Comment by drawsstuff** [comment]
Discussions outside of this PR and the thread have led to a mostly unanimous conclusion on how these new sprites will be implemented. 

These will _not_ replace current vox sprites or current raider sprites, but rather be an option for vox raiders who wish to go for a smash and grab approach instead of a more stealthy one. If a raider does decide to forsake their stealth option, they will receive a few themed benefits such as prying open doors for compensation. Thank you to everyone who took this seriously and pitched in to the idea and theory-crafting behind this. You can expect a PR properly implementing these as a raider option in the near future.

**Comment by Senaat1** [comment]
Remove Vox. Death to furbait races.

**Comment by help-maint** [comment]
Next time please start by showing what they look like in-game and not against a blank grid that doesn't even match up to 32*32

**Comment by d3athrow** [comment]
@drawsstuff 
>Discussions outside of this PR and the thread have led to a mostly unanimous conclusion on how these new sprites will be implemented.

that's not how it works. also why do the reptilians have a crotch bulge.

**Comment by nuklearcellphoneg** [comment]
As we say in car soccer,

Savage!

**Comment by ghost** [comment]
>vox: erp metaclub edition resprite

tenor

**Comment by Olb43** [comment]
I dont like it. It looks like a lizard. Vox are birdmen space gypsies and that works. This doesnt.

**Comment by wotisjanitor** [comment]
looks like a completely different species. Doesn't look like how I've come to imagine vox, and I'd be very annoyed if it was only raiders as well. Part of the fun of vox raiders is that it's unclear at times who's just a vox crewman and who's a raider.

**Comment by ShiftyRail** [comment]
Necro

**Comment by drawsstuff** [comment]
> looks like a completely different species. Doesn't look like how I've come to imagine vox, and I'd be very annoyed if it was only raiders as well. Part of the fun of vox raiders is that it's unclear at times who's just a vox crewman and who's a raider.

I've got some other things on my plate at the moment but it's on the to do list still with a couple other raider related features.
300pert

**Pull request closed without merging**
