### PR TITLE
Removes action buttons. Ready for server side testing after successful test server testing.

### PR DESCRIPTION
**Pull request by ghost**
Removes action buttons. Ready for server side testing after successful test server testing.

:cl:
- experimental: (temporarily) removes action buttons. - some items will now have to be used in your hand to be toggled until this test is complete!! - please immediately ahelp WITH A SCREENSHOT if your screen is frozen and NOT fixed by relogging and/or waiting 30 seconds.

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
Looks good to me, let's merge this

**Comment by ghost** [comment]
boys I don't want to excite anyone but people who are getting the freeze fixes itself after a second now

**Comment by ghost** [comment]
Of all the words of tongue and pen the saddest are these: TG spreads again

**Comment by Aurx** [comment]
Back in my day we just had to input the verb for everything both ways uphill in the snowmap.  And we LIKED IT.  It built character.  You whippersnappers don't know how good you have it.

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
I made the PR prompt people to update to 512; and I think we should try some LIVE SERVER TESTING to see if the extremely positive results found on the test server are replicable in live with a far higher test group

**Comment by DamianX** [comment]
The guy that froze with #17855 also froze with this.

**Comment by jknpj** [comment]
Time to rebase to bay.

**Comment by ghost** [comment]
image

**Comment by ihadtoregisterforthis** [comment]
>Their version: 510.

But that's the version that never fails

**Comment by Shadowmech88** [comment]
>and I think we should try some LIVE SERVER TESTING

A larger test pool would certainly be good, however the removal of action buttons would be a major loss of functionality. On top of that, to my knowledge, not everyone even suffers from the screen freezing, and this would be negatively impacting them for no gain on their part.
Isn't there some way this could be made opt-in? Some sort of player option that adds the player's ckey to a global list which the action button code can check and then fail to execute for anyone on it?
It would allow the test subjects to be restricted first only to those who actually experience the freezing, and additionally only to the ones who are actually alright with having their game impacted in such a large way. If it works, it might even turn out to be a partial solution for the people who experience freezing regularly, which they can use while the cause is narrowed down further without it impacting those who don't want to lose their own action buttons.

**Comment by gbasood** [comment]
HAHA HEY GUYS
LETS HIT IT WITH A SLEDGEHAMMER UNTIL IT WORKS
BECAUSE WHY NOT
This won't get us any closer to finding the actual problem but I'm tired of hearing people whinge about how nothing's being done

**Pull request merged**
