### PR TITLE
Traitor PDA Pinpointer can now change targets more than once

### LINKED ISSUE #30674: [Feature Request] Buff the Syndicate item PDA Pinpointer
(WEB REPORT BY: dickwrath REMOTE: 206.221.180.138:7777)
# Revision
eeba1cc03122e57174ed878eb0ddbec482d3a446

# Current Issue
The PDA Pinpointer is a great item that will give you directions to anyone's PDA, pinpointer style. However it's currently only single use, limiting its utility.

# Suggested Change
Allow the PDA Pinpointer to swap targets on the fly. For the TC this item would be a lot more viable if it could be used as many times as you desired instead of just single use.

### PR DESCRIPTION
**Pull request by gurfan**
Closes #30674 

also lets you alt click the pda pinpointer to change targets (in addition to the usual right click menu method)
also also removes PDAs on centcomm from the list of selectable PDAs

:cl:
 * tweak: The Syndicate has modified their PDA Pinpointers to allow users to change the target every two minutes. Changing the target again requires having the same UE of the first person to set a target.

### CODE REVIEW

**Comment by BomberBro** [comment]
I for one look forward to sec finding one of these and using it to gestapo every single suspect they have, especially on cult (the incorrect solution to this problem would be to make it only usable by the buyer).

**Comment by gurfan** [comment]
> I for one look forward to sec finding one of these and using it to gestapo every single suspect they have, especially on cult (the incorrect solution to this problem would be to make it only usable by the buyer).

feature

**Comment by gurfan** [comment]
okay I'll make it only usable by the buyer

**Comment by BomberBro** [comment]
incorrect solution

**Comment by PavelCIA** [comment]
>I for one look forward to sec finding one of these and using it to gestapo every single suspect they have, especially on cult (the incorrect solution to this problem would be to make it only usable by the buyer).

Nice theorycrafting. Do you wanna know a secret? ERTs get advanced pinpointers that can literally track people's DNA instead of their PDA, but they never give them to security (or use them at all really). 
Even with the buff I don't see people buying this very often. If security manages to get one let them have it.

**Comment by gurfan** [comment]
The first person who set a target now owns the pinpointer, and only they can change the target afterwards.

> incorrect solution

shoo

**Comment by gurfan** [comment]
The first person to choose a target submits their DNA. Changing the target requires you to have that DNA. If security really wanted to abuse this pinpointer they would have to change their UIUE, which I think is a good punishment.

**Comment by BomberBro** [comment]
ERT are the designated blob and cult fumigators and cult only when the cult is already loud/obvious enough to be a problem. The pinpointers (and almost nobody knows about them) aren't useful in either of those cases unless command mashes the button as soon as they see fingerpainting.

**Comment by drawsstuff** [comment]
I'd suggest tweaking it to a limited number of changes. As in, you can only set who to track 3 times before it becomes "Stuck".

**Comment by SonixApache** [comment]
> 
> 
> > I for one look forward to sec finding one of these and using it to gestapo every single suspect they have, especially on cult (the incorrect solution to this problem would be to make it only usable by the buyer).
> 
> Nice theorycrafting. Do you wanna know a secret? ERTs get advanced pinpointers that can literally track people's DNA instead of their PDA, but they never give them to security (or use them at all really).
> Even with the buff I don't see people buying this very often. If security manages to get one let them have it.

Don't tell anyone, but those advanced pinpointers are broken as fuck.

**Comment by Kurfursten** [comment]
I feel like a limited number would be a better pressure valve

I'm a little nervous about HOW good a utility this is when completely unlimited. You can even just flip through security officer PDAs to make sure you know where the entire sec team is before killing jobbies. Lowpop? Check through the entire crew before hacking into a room. It's so versatile with no cap. 3 uses seems fair.

**Comment by Eneocho** [comment]
>You can even just flip through security officer PDAs to make sure you know where the entire sec team is before killing jobbies.

That would be an actual issue if our codebase didn't have everyone running like sanic on cocaine. By the time you finished checking, the patrolling seccies would have done yet another round.

And there's the advanced pinpointers thing that Bomber mentioned, they get stationside decently often, but I've never seen anyone use them to track anyone. Also, if sec/tator is going to town on the pda pinpointer, you can just drop your PDA on a locker and be a PDA-less person, it's not like there's no counter to PDA memery.

**Comment by SonixApache** [comment]
>I've never seen anyone use them to track anyone

I remember successfully using it but once, when we got sent in as ERT and had to track down the single survivor of a post-cult2 massacre. Was actually really cool.

**Comment by Kurfursten** [comment]
> By the time you finished checking, the patrolling seccies would have done yet another round.

I don't think this is the case, we're only talking about toggling between three players at most on an average round to check their locations, this makes breaking into the armory for example much less risky. You just have to make sure no one's in security at the moment. And if you get nervous you can swap back to the start again - toggling between them is easier than ever with alt click, so you can easily check on the whole sec team in six seconds I should think. Contrary to what you're saying, while players do move fast, they aren't constantly patrolling like robots. They move from one place to the next, stop to talk to people, or look in through windows.

Maybe I'm overblowing it but this is definitely a much bigger buff than people are treating it.

**Comment by gurfan** [comment]
I'll add a cooldown to it soon

**Comment by gurfan** [comment]
The pinpointer can change targets every 2 minutes. Examining it shows the remaining time.

**Pull request merged**
