### PR TITLE
Fixes #10664

### LINKED ISSUE #10465: 24 Bug Fix Challenge
I've been gone for a little while, and I caused two bugs that I left unresolved during my absence that I can find (if there are any bugs that are my fault that I haven't fixed, please report them, a preliminary search using "is:open celt" didn't yield anything)
As a way to pay for my sins, and show I'm genuinely sorry, I'll fix 24 bugs in 24 hours (well I'll try, anyway. Some bugs are harder to fix than others. - whichever comes first will be what I call a victory.) @ArthurDentist has convinced me to stream it, if I can, but I doubt I'll provide very interesting commentary
If anyone wants to match the amount of bug fixes (or beat it) and make the collaborator's jobs hell for that day, that'd be pretty cool too.

Please suggest bugs that I can fix. Haven't yet got around to setting a date, but expect it within the next week.

### LINKED ISSUE #10664: No progress bar for AI planning module
The planning module takes 5-10 seconds to upload into an AI or cyborg upload. However, it gives a starting message making you THINK it worked, but it won't work until you stay longer and another message pops up. This has lead to people thinking they have uploaded their laws but really they just purged an AI.

Simple addition, kinda a bug report since everything else has progress bars, and this is something that should have it since it involves you standing still to do something.

### LINKED ISSUE #10687: Progress bars appear under other things sometimes
Specifically, if you are doing something to a floor, they appear under everything except floors. Probably applies to other things under similar circumstances.

### PR DESCRIPTION
**Pull request by ghost**
fixes #10664 
fixes #10687 
fixes #10465

### CODE REVIEW

**Comment by ghost** [comment]
this is the 24th fix.
I am now free.

**Comment by Imagebard** [comment]
_Only if all the fixes work :^)_

**Comment by ghost** [comment]
@Imagebard feck off

**Comment by Imagebard** [comment]
NOT ONE OF THOSE FIXES IS FORM ONE OF MY REPORTED ISSUES DRCELT
WHAT GIVES DRCELT

**Comment by ghost** [comment]
@Imagebard uhh, which ones were they?

**Comment by clusterfack** [comment]
One of your fixes was already reverted for being a shit

**Comment by ghost** [comment]
@clusterfack and I coded a way to fix it again.

**Pull request merged**
