### PR TITLE
Automatic Fire Suppression

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Adds a Fire Suppression preset to air alarms which scrubs Oxygen and Plasma while replacing them with Nitrogen. This preset is triggered when a fire is detected in a room to help quickly suppress a fire without feeding it additional fuel or oxidizer. Automatic Fire Suppression is disabled on all air alarms at roundstart: Engineers and/or Atmos Techs must manually enable it in all rooms where they want this to trigger automatically.

image

## Why it's good

Gives Engineers & Atmos Techs more tasks to do outside of Engineering and helps fight fires.

## How it was tested

- Burned a room without the mode enabled and confirmed it did not automatically swap to the Fire Suppression preset.
- Burned a room with Automatic Fire Suppression enabled and confirmed Oxygen and Plasma were scrubbed and replaced with Nitrogen.

## Changelog

:cl:
 * rscadd: Added a Fire Suppression preset to Air Alarms which replaces Oxygen and Plasma with Nitrogen in its area.

### CODE REVIEW

**Comment by Eneocho** [comment]
can you set this mode remotely via the CAC or do you need to go to room and mess around with some wires first?

**Comment by west3436** [comment]
> can you set this mode remotely via the CAC or do you need to go to room and mess around with some wires first?

The mode can be set remotely like any other mode - the toggle (which I haven't added yet) just will be used to control whether or not a given alarm will autonomously switch to Deoxy mode when a fire is detected. I'll make the toggle available remotely as well so the AI can feel important and useful.

**Comment by Eneocho** [comment]
Update Wiki

**Comment by wotisjanitor** [comment]
sneakycoded vox shit

**Pull request merged**
