### PR TITLE
Prevents scrolls from being fabricated by the crew.

### LINKED ISSUE #8021: You can mass-produce teleportation scrolls through the general fabricator
Seems like an oversight.

More accurately, this was the Lesser Scroll of Teleportation (the ones apprentices get with only one use), not sure if it works for default teleport scrolls or not.

### PR DESCRIPTION
**Pull request by gbasood**
Fixes #8021

### CODE REVIEW

**Comment by SonixApache** [comment]
Magical origin tech when?
Magilathe when?

**Comment by gbasood** [comment]
WHEN
YOU
CODE
IT
And when you justify it's a good idea to give the crew even better shit to deal with ragin' mages.
Because that's really the only situation when they'll be able to get magical tech levels.

**Comment by ghost** [comment]
@SonixApache It's in the code, just commented out, and nothing was assigned to it in the research machines.

Cooould bring it back by making magical items (force staffs, scrying orbs, etc.) take mythril (also commented out in code, but the coins still show up in magic rooms, the ore and refined sprites still used by xenoarch, and the walls of the magic rooms should be mythril material walls but instead are plasma walls because placeholder)

**Comment by ghost** [comment]
:-1: magic tech when

**Comment by 9600bauds** [comment]
Don't remove the technology entirely, just give it mech_flags = MECH_SCAN_FAIL
If someone gets a scroll of teleport and wants to stick in the DA my god they should be able to

**Comment by Exxion** [comment]
Give it something ridiculous like bluespace 20 so that it is helpful to research but you can't get high enough tech levels to actually make it

In addition to what Bauds said I mean

**Comment by ghost** [comment]
@Exxion To be able to make it, it would need to be added to an R&D machines list of things that it can build. Giving it bluespace 20 in this case would just give robotics easy mecha teleporters

**Comment by Exxion** [comment]
Only if they got a bunch of them
If R&D works how I think it does (which is a big if; it's been a long time since I've done it and I don't even remember if it was on this codebase), all a high value like that would mean is that you'd be guaranteed one level up per scroll
If memory serves, you'd need at least two scrolls or one scroll and one phazon part to get the teleporter

**Comment by Skullyton** [comment]
Huh, the way I remember it is

>If the research level is considerably lower than what is being broken down, then the research level becomes 1 level less than that of the objects level
>If the research level isn't that much lower than what is being broken down, then the research level becomes equal with that of the objects level
>If the research level is equal to that of what is being broken down, then the research level will be 1 greater than that of the objects level
>If the research level is greater than that of what is being broken down, oh shit nigger what are you doing

**Comment by Exxion** [comment]
Oh, that might be it
In that case, definitely do not do what I said

**Comment by gbasood** [comment]
Did what @9600bauds recommended. Device analysers can't scan them now, but you can still deconstruct them for bluespace tech.

**Comment by aceedex** [comment]
I don't know, I think it's a neat enough feature that it shouldn't be removed. After all, the genfab isn't really worth anything other than mass producing maybe flashes and the odd hand tele if mechanics ever gets phazon.

It's not like it's a giant balance issue or anything, since you usually only get teleport scrolls usually when the wizard is killed or otherwise detained

**Comment by ghost** [comment]
Kill it

If you really want magic, then add magic to R&D

**Comment by gbasood** [comment]
@aceedex It is a balance issue. Ragin' Mages, specifically, becomes incredibly stupid. It removes the advantage of mobility for wizards because **the entire crew can just follow them around when they teleport away** after they get a scroll off the first dead wizard.

**Comment by aceedex** [comment]
@gbasood I don't think that's exactly a big issue when wizards (note that plural, because one wizard alone can become more than a hassle for an entire crew, having 5 of them doesn't exactly make things easier, specially if the first wizard of that wave puts in work) have a lot more mobility than what a scroll can offer. Specially since you need to activate the scroll in your hand, and then select an area. It's not like you're printing spell books.

**Comment by gbasood** [comment]
@aceedex Doesn't matter, if you have 40 crew members with scrolls eventually they'll out-maneuver you.

**Comment by aceedex** [comment]
@gbasood Is that really that big enough of an issue when mechanics is almost always empty, and when it's not rarely anyone even thinks of using the genfab, and even then to get that kind of setup going you'd not only need quite a bit of plastic, but to also have successfully killed a wizard AND have the scroll not be lost somewhere along the way?

**Comment by NigglyWiggly** [comment]
I still have some sprites and shit put aside from the Arcane Research thing I was spriting shit for months ago.
Someone should code that and make it a thing but that's a discussion for a different PR.

**Comment by gbasood** [comment]
@aceedex 

> but to also have successfully killed a wizard AND have the scroll not be lost somewhere along the way?

When one wizard dies, and there's 5 more coming, and the crew is handing out scrolls like candy to help hunt down wizards, it's a problem.

**Pull request merged**
