### PR TITLE
fixes emagging firelocks welding them shut

### PR DESCRIPTION
**Pull request by gurfan**
## Changelog

:cl:
 * bugfix: Fixed emags welding firelocks shut.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This is actually intended as of #13443 -- wow, 5 years go fast don't they?

I expressed at the time that I thought it was a bad idea, but it's technically not a bug

**Comment by pedr69** [comment]
current behavior seems more consistent?
emags will break open normal and minor alert firelocks, the ones you can just click to open
major alerts, when the firelock gets "bolted shut" and needs an ID/crowbar to open the emag welds instead

it's also funny seeing someone weld himself into a breached room by accident

**Comment by gurfan** [comment]
This is definitely not intended and was caused by #31892. Prior to that PR emagging a closed airlock opened it THEN welded it down. After #31892 emagging a closed airlock welded it without opening it.

**Comment by Kurfursten** [comment]
Interesting. Still not fully satisfied with how this works but this is less bad.

**Pull request merged**
