### PR TITLE
Secures unsecured watercooler on Waystation

### LINKED ISSUE #36774: Unsecured Water Cooler in Waystation
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
# Revision
e315245d7668ac829e1f8287dbc80e35f9f14383

# Description
the water cooler outside the court on waystation spawns unsecured so it immediately gets shoved all over the place when people run around
# Steps to Reproduce
poke it
# What you Expected
stubbed toe
# What Actually Happened
oh my god there's water drops everywhere

### PR DESCRIPTION
**Pull request by angryturnip**
## What this does
Closes #36774 by securing the unsecured watercooler with 4 additional turrets.
water cooler secured

## Why it's good
The water cooler is now secure

## How it was tested
It wasn't

## Changelog
:cl:
 * rscadd: Added new thing.
 * rscdel: Removed old thing.
 * bugfix: Fixed a bug that caused something bad to happen.
 * tweak: Changed a 5 to a 6.
 * imageadd: Added new sprites.
 * imagedel: Removed old sprites.
 * experiment: Added an experimental/work-in-progress something.
 * spellcheck: Fixed missing punctuation, typos or restructured a sentence.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
downvoting because it needs more turrets to secure it with, this won't do

**Comment by Eneocho** [comment]
THIS PR HAS BEEN VERIFIED BY REAL NANOTRASEN PATRIOTS

**Comment by toomykins** [comment]
```
maps/waystation.dmm:78498:error: undefined type: /obj/structure/falserwall
maps/waystation.dmm:78500:error: unknown type
```

**Comment by jwhitak** [comment]
#36777 ended the dream...

**Pull request closed without merging**
