### PR TITLE
Adds sanity for consumables with respect to mouth obstructions

### PR DESCRIPTION
**Pull request by ghost**
With this change, all oral consumables will require an unobstructed mouth for yourself or anyone you wish to assist.

:cl:
 * rscadd: Consumables require an unobstructed mouth.

### CODE REVIEW

**Comment by ghost** [comment]
@SonixApache @jknpj I got you fampai.

**Comment by jknpj** [comment]
Might as well add a mob or human level proc  and call it instead or copypasting the check everywhere. Sitll, good stuff.

**Comment by RFultra** [comment]
+1 upvote from me and +1 hooray as an upvote from kolith

**Comment by yclatious** [comment]
>removing eating while having a gas mask and so on

Its something a lot of people wanted and all, but fuck me, Im gonna miss not having to take out my shit to eat, I know, imulsions and all and I get it, but still gonna fucking miss it.

**Comment by Exxion** [comment]
It should be a proc rather than copypaste
Also, just for standards reasons, it should have a `\the` before the `[H.get_body_part_coverage(MOUTH)]`, even though it works exactly the same without it

**Comment by Exxion** [comment]
Oh yeah also RIP vox and plasmamen

**Comment by yclatious** [comment]
>vox and plasmamen

Honestly, having forgotten those dudes, itd be nice if they could have a free pass on this sort of change or just a free pass for stuff like normal gas masks but not for anything else to save the hassle of snowflaking it for those races and no, Im not just saying this so we can get a free pass on a mask or something, the ayys already have it rough on account of being ayys, screwing em or making life more inconvenient with changes like these is really uncalled for.

**Comment by Exxion** [comment]
Add straws to vox and plasmaman breath masks

**Comment by ghost** [comment]
They can grind their food and inject it with a syringe.  In all seriousness, considering options at the moment.  I believe that as a feature would be great, but I don't think it should stand in the way of sanity.

**Comment by yclatious** [comment]
>making vox and plasmemes grind food like skelememes to drink it by IV

Skelememes deserve it, not plasmemes and vox

**Comment by ghost** [comment]
Can't you like, push your breathing mask up?

**Comment by AI-Is-Rogue** [comment]
What about clowns and mimes? Their masks are children of mask/gas.

**Comment by ghost** [comment]
@Exxion Ok, I was able to ad the `\the ` as asked.  I am not exactly sure how to go about the proc, as I am pretty dumb.  If you told me how or could direct me to someone who could help, I would try.

**Comment by ghost** [comment]
Nevermind, I will figure it out.

**Comment by SonixApache** [comment]
How do vox and the like eat on other codebases?

**Comment by ghost** [comment]
Ok, I learned myself something new and did the thing.

**Comment by ghost** [comment]
How is this going to be anything but a monolithic ulcer for medbay, vox, and plasmamen and why couldn't it have simply remained abstracted when the delay already functioned as a compromise? At least update the strip menu with a toggle other's mask button that works from global so you can get at em without way too many delays working down to the mouth then putting it all back on or shit getting left all over.

**Comment by TheFriggenSawbones** [comment]
whats the point

**Comment by TheFriggenSawbones** [comment]
MECHANICS
OVER
FLUFF
bad mechanic kill

**Comment by ghost** [comment]
What's confusing about it? The delay already serves the purpose without having to play helmet and mask removal jenga when they're being inattentive or get critted. It creates a quality of life log jam in medbay on top of bag space/theft headaches. Why can't it remain abstracted in the action delay thing or at least get a toggle in the strip menu?

**Comment by Kurfursten** [comment]
I'm surprised this has so many "upvotes". There are two quality of life things I love on /vg/: quickswapping equipped items and not having to fuck with my mask when I go eat/remember to flip it back when I go back to space.

We still let people use cigars as an O2 mask, right?

**Comment by SonixApache** [comment]
~~if this is such a detriment to xenos maybe it's a good time to remove xenos~~
the obvious solution is to remove vox

**Comment by ghost** [comment]
They're more of infrequent collateral. Upending medbay, self-treatment in hazardous/space conditions and field triage when we already have the delay when you feed someone a pill/beaker/food/whatever sounds unnecessary. It's causing a huge QoL issue for a minor gain in fluff.

**Comment by ghost** [comment]
There, plasmamen and vox have adapted to a lifetime of wearing masks.  I cite the vampire standard of them being able to shift aside their mask to suck blood.

**Comment by ghost** [comment]
That should do it.  Clowns, mimes, vox, and plasmamen have adapted well to masked lives.  I  Included clowns and mimes due to clowns and mimes removing their masks being something that makes me and many others physically ill.

**Comment by SonixApache** [comment]
the passive aggressive tone in the updates makes this PR feel like a joke, even though i kinda like it

**Comment by ghost** [comment]
Thinking this a little better this is going to be a pure undiluted cancer for Medbay for no real purpose

**Comment by SonixApache** [comment]
immursions is a completely legit goal

**Comment by Fruktlimpa** [comment]
Unsure how I feel about this. On one hand it will be good for immulsion purposes but on the other hand it is going to add a bunch of tedious steps for medbay personnel because 90% of people already wear some form of mask.
Probably sounds worse than it will actually be but I don't know. 

Also, doesn't this kinda fuck up the Ops last stand pill? Sure, not like they ever use it but I don't think you would have time to take off your helmet, then your mask, to pop the pill to make a last stand.

**Comment by Shadowmech88** [comment]
What if taking a bite of something while wearing a mask yielded a "You pull your mask away and take a bite of \the [food], then move your mask back into place." message without actually altering functionality?

**Comment by jknpj** [comment]
Oh no, medbay can't heal things with a single click anymore, call the shuttle.

Also yeah the mask's action button push it out of the way for this exact feature but i don't think there's a way to push other people's mask out of the way

**Comment by SonixApache** [comment]
alternatively we could close this kneejerk pr and remove the sanity shit from the other one

**Comment by ghost** [comment]
No Sonix, immersions in the way this is applied is not a completely legit goal. The delay that already exists on feeding someone else can have its message refluffed so it's more explicitly hey in these couple seconds I/you are going to quickly tip your helmet and move your mask to the side then put them back without I dunno a minute and 40 seconds of strip menu jenga. I could see it if a push mask aside button with a shorter delay was added to the strip menu and worked globally so like toggle internals you can get at them but for the most part it's making a mountain of headaches for an insignificant flavor text message. It's a spot where simulation should give way to abstraction.

**Comment by Chazach** [comment]
this is fucking ghey and serves no purpose but to hinder gameplay
being able to quick equip an entire space suit or consume beakers, pills and food in a fraction of a second isnt particularly immersive but it exists because tedious tasks for no purpose but immulsions is straight up shit and over complicates gameplay for some nebulous goal that will never be reached

**Comment by SonixApache** [comment]
MY
IMMULSIONS

compromise: only apply this to non-humans.

**Comment by yclatious** [comment]
Better solution, we make it non humans only but a flavour text only about lifting the mask.

**Comment by ghost** [comment]
Compromise, we don't and leave it abstracted and reword the you feed messages with an obstructed check for a message referencing the helmet/mask being moved and put back during the action, or before this is accepted the strip menu gets a move mask aside with a reduced delay so it's not a gigantic ulcer. Does the obstruction check even care if the mask is pushed aside in the first place?

**Comment by jknpj** [comment]
i told you about backslash, bro

**Comment by jakmak6** [comment]
The only problem I have with this is if your in a vacuum and need food you can't take your mask off for even a second or else you get YOU FEEL A STABBING PAIN IN YOUR CHEST and unavoidable slow death unless you spend 15 minutes in medbay (which may not always be possible). Same thing with trying to bandage yourself in space. You need to take your hardsuit off and if you fumble your airtank then burst lungs

**Comment by SonixApache** [comment]
@jakmak6 that shit got refactored to be less of an issue a while ago

what if this only applied to helmets, and not masks?

**Comment by Megamaw** [comment]
well it's more consistent with needing to strip a guy's face to do CPR but like

we still do have the issue of some races basically dying when you take their masks off. if you can code exceptions, i'm all for it. otherwise, i'm gonna have to say no.

**Comment by ghost** [comment]
I think the issue here is forcing people to regularly go through the awkward strip menu and the fumbling of masks and helmets dropping to the ground. If you want to make a point about fluff you don't need any of the above, you can just add a small delay. Like how we already have a slightly longer delay for injecting people in a hardsuit.

**Comment by Arthurdentist** [comment]
this buffs horsemask, clown curse and french curse. 

Seems like everything is a wizard buff in disguise these days.

**Comment by RFultra** [comment]
so what I can gather is that vox and plasmamen dont have to deal with this because people will complain? but everyone else has to? doesn't seem fair, it should be all one way or all the other

**Comment by ghost** [comment]
It is actually consistency with the design of vampires biting of the neck.  Plasmamen and Vox don't require mask removal for such and it even says they effortlessly bypass it.

**Comment by RFultra** [comment]
What stops humans from lifting their mask up and doing the same, just seems iffy to have certain races not having to deal with mechanics, and I am also refering to the vamp mechanic here

**Comment by ghost** [comment]
I dunno, friend.  I just use the status quo as an acceptable standard if it is specifically coded a certain way.  Especially in the case of vamps.

**Comment by ghost** [comment]
I have no strong feelings towards this going through or getting declined.  It is not my place to have an opinion on it as I am presenting it.  I specifically made this PR to get community opinion on such, as we were discussing the sanity regarding such in my other PR #15619.  I would have been a lazy hypocrite if I did not put the effort into attempting to make this.

**Comment by FudgePucker** [comment]
:-1: I dislike this idea.
First, a knee jerk reaction to "being like other servers". Valids and autism, not imulsions and rp.
Second it seems extremely inconvenient for nothing in return.

**Comment by ghost** [comment]
Then add an obstructed check in the relevant action messages that plays an alternate message so the people who want more immersion can get that x goes to move the obstruction aside to give y the thing goodness. Add a toggle internals-esque move mask aside button to the strip menu that works globally. aka not blocked by helmets so people can get at crit nerds and people who dead fish in medbay. If there's both of those and if moving the mask aside actually does count as unobstructed then it's a net gain overall without an unreasonable burden. Otherwise, it's just shitting up quality of life for nothing else but pure undiluted autism the likes that would do away with quickswap so you actually have to take everything off to change jumpsuits instead of just being able to put it right on.

**Comment by N3X15** [comment]
* Added [Balance] due to numerous effects on medbay and traitors
* Added [Controversial] because drama and RP vs. Greyshittery arguments.

**Comment by ghost** [comment]
Who's ready for this to be left sitting stale for 2 more weeks then merged randomly?

**Comment by Orangerush** [comment]
Why do plasmamen need to eat anyway? They're just purple skeletons

**Comment by ghost** [comment]
WE BAY NOW BOYS
Being able to roll down jumpsuits when?

**Comment by Kammerjunk** [comment]
When I first started playing, I removed clothes as you'd expect clothes to be removed: First the exosuit, then the shoes, then the gloves, then maybe the belt, then potentially the hat, and finally the jumpsuit.
I was a real happy camper when I figured out that wasn't necessary

**Comment by yclatious** [comment]
My imulsions are already broken by stupid people yelling ayy le mao, people named Rambling Maniac and other stupid shit, I do not need them being broken more over my character being unable to automatically move his mask every time he wants to have a bit of food, that's a hassle for non immersions and like people have said before, its just a extra pain in the ass for doctors.

I get the intent but really, this isn't going to improve immersions, itl be a annoying addition, if you want to help my immersion not being busted, code a temp ban every time someone tries to put a adjective on a name field.

**Comment by ghost** [comment]
>immulsions
>In a light RP server

hahahaha

**Comment by Orangerush** [comment]
> Being able to roll down jumpsuits when?

SOON

**Comment by SysadminJeroen** [comment]
Can we get @Iamgoofball to comment on this?

**Comment by ghost** [comment]
Goofball's done enough damage, leave him out of this.

**Comment by Iamgoofball** [comment]
>server vote

>on whether you can put food in your mouth or not

ten outta ten vee gee
this is where democracy gets you

**Comment by Iamgoofball** [comment]
let me ask you:
how does this improve the game

**Comment by FudgePucker** [comment]
OH GOD THEY SUMMONED HIM.
WE ARE ALL GOING TO DIE!
@Iamgoofball seriously this
Fuck being like other servers.
This PR idea is horrible.

**Comment by Exxion** [comment]
Yeah
Much like Goofball, it doesn't really improve the game

**Comment by Intigracy** [comment]
At least when goof makes meme prs they get treated as memes instead of real features

**Comment by ghost** [comment]
So you consider it perfectly acceptable to be able eat an entire turkey dinner, have a space cola, and take a few hyperzine pills by "moving your mask out of the way" in the middle of deep space or in a plasmafire flood?

**Comment by Intigracy** [comment]
Yes I do, because there are game elements to this game.

**Comment by Exxion** [comment]
Realism is not the number one thing to strive for
Gameplay is
When they conflict, gameplay takes precedence

**Comment by PJB3005** [comment]
Jesus Christ realism is nice and all but this is nothing except a giant QoL decrease.

**Comment by ghost** [comment]
I think it will be interesting to see where people want the difficulty slider set for the server, if anything.  I'm glad I made this.  It's neat to get a feel for where the design direction is wanted to be set towards.

**Comment by Iamgoofball** [comment]
You could of asked in the coder chat instead of giving a platform to the retards.

**Comment by ghost** [comment]
That's not a healthy view to have of a game's playerbase as someone making changes to it.

**Comment by PJB3005** [comment]
@Iamgoofball not how this works.

@HarseTheef I don't think this adds to difficulty, at all. This just makes eating tedious. There's adding difficulty and then there's adding tedium.

**Comment by ghost** [comment]
yeah, it would be pretty tedious and make space exploration harder to power through.  I hope it doesn't go through.

**Comment by PJB3005** [comment]
Syringes still exist. You're just moving the meta.

**Comment by ghost** [comment]
Yup, I agree.  That's why i'm probably gonna vote no.

**Comment by Iamgoofball** [comment]
if you agree then why did you make the PR and why haven't you closed it

**Comment by ghost** [comment]
Because it is not Harse Station 13.  It is a sanity issue that had not been addressed and needed to at least be brought to the table.

**Comment by Iamgoofball** [comment]
This is your Pull Request, you can open it and close it whenever. Never feel obligated to keep a PR open.

**Comment by ghost** [comment]
Not addressing sanity or a bug, due to it personally benefiting me, is morally wrong and pretty fricked up in general.  That is why I suggested it be polled.

**Comment by PJB3005** [comment]
What if this was an intended feature all along?

**Comment by ghost** [comment]
Cmon, don't be a turkey sandwich.

**Comment by Iamgoofball** [comment]
This is neither sanity or a bug when it comes to code, it's design.

Sanity checking is making sure a correct value is inputted to prevent a bug or runtime from occuring, such as verifying that the human is indeed human and not a window.

This is a feature. I was there when "moving mask to eat stuff" was coded and added, it was added so that you could adjust your mask to eat because you could eat already with the mask on.

(that shouldnt of been added because it was dumb but eh whatever)

This is, most definitely, a feature, ESPECIALLY if there's already mechanics for eating food with a mask on(pushing the mask up)

**Comment by ghost** [comment]
So you are saying the intended functionality is to be unable to eat if your mouth is obstructed?

**Comment by nuklearcellphoneg** [comment]
Nah, moving the mask to eat was added for flavor(haha cuz you're eating).

**Comment by ghost** [comment]
The whole process is already abstracted into attack delay because, big surprise, it's a giant needless hassle for nothing the likes of which that'd justify the removal of quickswap cause of muh immulsions g-gotta *breath_in, *breathe_out or you suffocate. This is so goddamn fucking stupid and I'm so sick of it. Put in a check to play a special flavor message to make the hey bub open up for the anti-tox airplane attack delay and dump the rest if you're hellbent on muh flavor or at the least do what I told you over and over and make sure the toggle mask works and add it to the strip menu with a very short delay so the implementation is passable for both parties instead of causing a giant QoL of life pileup getting through on a "muh vote" "j-just revert it". Stop shitting things up in the worst way when it might actually happen it's been a bloody month already.

**Comment by RFultra** [comment]
wtf are you talking about sarah
what are you actually trying to say

**Comment by Zennyization** [comment]
I dont understand why people would be upset over having to do one extra thing to eat food. All you need to do is take off your helmet/mask??? What is the issue here.

**Comment by cappt** [comment]
@SarahJohnson489 markov

**Comment by ghost** [comment]
@Zennyization Because it's pills and container drinking too zenny. It's taking what was abstracted into attack delay and just clicking someone . It's going to create a gigantic shitfest in medbay. People aren't going to take their stuff off. They're going to react violently when you do because they don't understand what's going on and it'll get worse once it's off the top of the changelog. Stuff's going to get stolen. It risks issues with any interactions in space or any fire it's no longer as simple as just give the guy a pill, you can't take his shit off, there's no toggle mask strip menu verb, seeing as it's been a month since I asked there wont be so it's rolling the dice on them not being retarded or having not been retarded before crit. There aren't going to be 56 large beakers added to every medbay map for the new syringe meta which is bad in its own right for those that used pill bottles to compress storage space or just don't want to kill themselves from a half dozen unecessary clicks or trying to get guys that traditionally dead fish and alt-tab for their trip on the wild ride to eat.

And for what?
There aren't crashes or runtimes to justify it.
Most hostile actions are either blocked outright or handled under attack delay
If you're dying for muh imulsions, the better way is to go in and have attack delay play a different message if obstructed or add toggle mask to the strip menu with heavily reduced delay and not in red text so it's not an ulcer for everyone.
You do breathe through a toggled mask fine. If the new meta is toggle your mask at roundstart and forget about it, there's no point in shitting everything else up for a one-off. It's not a perfect world.
There's just no point for it.

People already can't handle suit sensors by and large and now it's layering an actually impactful headache on top of that.

**Comment by TheManNamedTom** [comment]
@SarahJohnson489 yeah uuuuhhhhhh ill take a double triple bossy deluxe on a raft, 4x4, animal-style, extra shingles with a shimmy and a squeeze, light axel grease, make it cry, burn it and make it swim

**Comment by Zennyization** [comment]
@SarahJohnson489 In my experience I've never encountered people getting angry for stripping them while helping them. I personally don't think that this is much of an issue, normally if I am trying to help people in space/fires I'd bring them somewhere safer first. I feel as if this only really affects people who walk around with hardsuits on all the time (which is not something that I really 'agree' with anyway.) 

If the crux of the issue is that 'people are unable to handle it' because as you say "People already can't handle suit sensors by and large." Then I think that is an issue with the playerbase and not the feature. 

In my opinion however, I think that this comes down to a general laziness with people not wanting to readjust their routine when playing the game. Basically - you want it easy.

**Comment by nuklearcellphoneg** [comment]
It adds tedium. It will always add tedium.

It also adds immersion. However, it will add less immersion every subsequent time you must do it.

Therefore, it will ultimately only add tedium and will become an extra step in a routine.

**Comment by ghost** [comment]
@Zennyization You've used an N2O tank for surgery enough for that sweet oh god what the fuck is wrong with you get away reeeeee and even the rare ahhh sec help surgeon is [antag]!!! reaction. After the first month a good chunk will be onboard but a lot will always not understand what's going on and take it as a hostile action and it'll never ever stop from people constantly coming back from a break, being new in general, or differences in server code. The only people alive or at least relevant in any way will be the ones in hardsuits when it goes to shit and you know that but whatever. I could understand if there was some worthwhile gain to this but there's not. I could understand if it was done unobtrusively through refluffing the attack delay message or others had a way to trivially toggle it though a toggle mask button on the strip menu at the global level but it's not.

No zenny, what I Fucking want is the interaction that at best is an additional and wholly unecessary speed bump and at worst a complete and entirely unnecessary headache to not go through, remain abstracted into attack delay which can be trivially refluffed with a better flavor message instead or at least added to the strip menu at the global level with a reduced delay so it's a smooth transition instead of telling people to get fucked and deal because of ACTUAL laziness. Shoving a syringe up people's asses with a half dozen plus clicks and accumulated additional delay instead of the former pill feed to achieve the same goddamn Fucking goal isn't wanting it easy. There's a lot of shit that needs to get Fucking done and trolling to increase the load doesn't help. The change is not readjusting a routine, it's dropping a gigantic fatberg of additional work that adds nothing when it removes what was formerly abstracted into an attack delay and returns it to a clunky unnecessary UI jenga when even IC it'd be handled smoothly instead of an ordeal. All before it even gets into the if everyone just toggles mask so it basically doesn't exist why the goddamn flying shitfuck should it go in when it in practice will solely exist to Fucking piss off an already overworked medbay. Would you remove quickswap cause of m-muh dress yourself "sanity"? "Immulsions"? You wouldn't because it's a simple action that in practice becomes unnecessarily lengthy and tedious for nothing worthwhile. After all these years you can't just drop the muh player base bomb like it'll go away when it hasn't. It's the reality we live in, it has to be accepted, and what doesn't comply with that should remain on the muh perfect design pipe dream pinboard where it doesn't hurt anyone else.

**Comment by Kammerjunk** [comment]
Haha remember that time someone killed a borg because he felt a little prick from it
I remember

**Comment by ghost** [comment]
@nuklearcellphoneg If that is the case, then would you like for me to remove the requirement to have an unobstructed mouth for CPR?

**Comment by Kammerjunk** [comment]
While you're at it, make CPR relevant

**Comment by FudgePucker** [comment]
This PR is the opposite of a QoL PR.
Say *inhale
Say *exhale

Why would anyone want this PR merged?

**Comment by ghost** [comment]
@HarseTheef ,

Pick one
1. Remove everything and just have attack delay spit out a different message if you're obstructed so they get the whole you move x's mask aside or use their hardsuits transfer port to feed them the thing
2. Add toggle mask to the strip menu at the global level, make and repeat for toggle helmet and give it a shortened delay so shitbay and everyone else fucked over by this have a more unobtrusive experience instead of theft, fights, useless dead fish, and way too much wasted time per round over what is a simple fix to at least smooth the bump
3. Stop the PR before people who still don't know it includes pills and beakers continue to vote yes with their dick or simply to troll so there doesn't have to be a big revert fight afterwards.

**Comment by ghost** [comment]
I had completely forgotten CPR was in the game

**Comment by ghost** [comment]
Well I don't blame you. It's pretty counterproductive. CPR to just counter the crit oxyloss is not gonna help unless someone has supplies so they're just racking up more blood/tox loss instead of dying so it stops progressing. The constant patient dragging doesn't help either. You'd think people'd have more kits and autoinjectors at the least if not a med crate reload with how easy it is to get but oh well.

**Comment by nuklearcellphoneg** [comment]
CPR is relevant.

CPR simply doesn't have a lot of situations where it is relevant and either way is going to be trumped 90% of the time with dexalin plus.

@HarseTheef I can put a pill under this mask.

I cannot do the same with my mouth, my lips are  not snakes.

41pxlktvxsl

**Comment by ghost** [comment]
Yeah, if you got supplies, don't have a defib, and it's actually relevant that they don't die, cpr is great. Happens a lot in sec situations. Even if it's just a burn kit/trauma kit and 4noraisins and cpr any bumblefuck assistant can bring a cop back up.

**Comment by nuklearcellphoneg** [comment]
Having to remove an unconscious person's mask also makes things tense(if you're having to perform CPR things are likely already tense, again the situations that require it are rarer). 

Removing the mask to shove a pill down someone's throat that will magically fix everything... not tense. Tedious. Further, 

'Take off your mask'
'Please take off your mask'
John starts removing Jane's mask
Jane disarms John!
Jane disarms John!
'I can take off my own mask'

**Comment by ghost** [comment]
While the poll has less than 24hrs left, the results are pretty clear cut, so I am gonna close this ahead of time.

**Pull request closed without merging**
