### PR TITLE
medsec headset

### PR DESCRIPTION
**Pull request by Apogee-dev**
Based on suggestions in the thread, adds a unique headset with access to the medical and security channels. At the moment, this won't spawn in game without admin intervention.

:cl:
 * rscadd: Added med/sec headset.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
paramedics don't do joint activities with security at all, and thus I don't see the need for them to have sec radio
the only time I see them go into security is to collect hidden security body lockers, or to do something in the brigbay (which is probably the real reason they have the access but that's just a guess).

**Comment by djkramer123** [comment]
I think this would make it easier and encourage parameds to do joint work with sec, that and it's fitting with their sec access, though if we're going to go this route they should start implanted as well.

**Comment by Apogee-dev** [comment]
> I think this would make it easier and encourage parameds to do joint work with sec, that and it's fitting with their sec access, though if we're going to go this route they should start implanted as well.

I considered giving parameds a loyalty implant, but that's a fairly significant gamechanger and one that would make parameds much more close to / part of sec than the miner-like degree of "belongs to one department but can talk to another" that this PR represents in its current state, so I'm testing the waters with just the headset first. I'll add that in a later commit or a followup PR if everyone thinks the headset itself is a good idea and there's enough demand.

**Comment by KillFurries** [comment]
I've never had problems with security when I go into the brig as a paramedic. If the paramedic headset had the sec channel I would turn it off, there's way too much chatter in the sec channel and it makes it impossible to pay attention to what is happening when sec never shut up.
Paramedic is fine the way it is, the problem is with people who don't know what paramedic has access to. There is no way to quickly check your own ID to see what access you have.

**Comment by Eneocho** [comment]
Do paramedics even have base sec access to enter the brigbay in the first place?

**Comment by Apogee-dev** [comment]
> Do paramedics even have base sec access to enter the brigbay in the first place?

They do. That's part of what inspired the creation of this PR to begin with, actually. Parameds have brig access, but no real way to work with sec. Theoretically, they have all of the necessary access and tools, but no means of communication.

**Comment by Eneocho** [comment]
I don't think implanting the paramed would make much sense since a paramedic would be a doctor for sec, not a gun wielding officer who could threaten NT's interests.

**Comment by APCUnlocked** [comment]
Either they get a loyalty implant to go along with their security headset or they don't get it at all imo, roundstart access to sec comms when you can pretty reliably roll rev/cultist/traitor is pretty powerful not to mention this doesn't change the paramedic's job at all basically. Either you grab the corpses using telesci or just walk there like a man, security is not needed at all for it.

**Comment by PavelCIA** [comment]
Why not make a Brig Medic alt title that spawns with this headset and a loyalty implant?

**Comment by KillFurries** [comment]
After thinking about this with the big boy brain this is going to be a downvote.
There's some confusion about what a paramedic is supposed to do. What a paramedic does is primarily recover bodies, that's why they have a free space suit, inflatables and magboots. They recover bodies from places regular doctors can't get to normally, that normally would be recovered only by engineers and powergamers who break into EVA every round to steal magboots. The secondary purpose of paramedics is to keep people alive long enough for them to be taken to medbay, that's why they have biofoam injectors, they roam the station and patch people up when someone is seriously injured. They have access to the brig because they may need to recover bodies from there or save a security officer from death.

Paramedic is not a combat medic. This PR came from people in the thread complaining that paramedics never tag along with security and it's hard for paramedics to coordinate with them. They're not supposed to do this. If you want healing just grab some for yourself and give some medicine to your partner. Trying to turn paramedics into combat medics who tag along during security raids goes against the purpose of paramedics. I wouldn't want to play a paramedic when there are sec players who expect me to go with them, boss me around and try to hand me guns. This is already the case with IAA sometimes and always the case with detectives.
People are already talking about how paramedics should be implanted which further solidifies this weird sec combat paramedic idea.

> Why not make a Brig Medic alt title that spawns with this headset and a loyalty implant?

This is a good idea though I'd like it to be it's own job and not take up the same job spot as a regular paramedic.

**Comment by drawsstuff** [comment]
The issue with this lies in loyalty implants, like people above had stated. Even the thread you were talking about couldn't really agree how best to implement this, with the debate being if it should be a part of paramedic's duties by default, a paramedic alt title, or a separate job. 
I agree that there's untapped potential in this area, but how to implement it is going to be a hot topic for debate. Personally, I think this might work best as an alternate title for the paramedic, where they spawn with this medsec headset but also receive a loyalty implant. It may also work well as a security officer alt title or its own job, but this runs a greater chance of them being issued weapons. I have a few unused shitty sprites in this area if you need them. Until this is more fleshed out I can't agree with adding this as is.

**Comment by BomberBro** [comment]
If a paramedic was given sec radio I think it'd be the only job in the game that gets a sec headset without getting a loyalty implant. If you're going to go about this you should think about giving it as an alt title instead. Either way I don't really agree with the expansion of security like that because they're already one of two job groups that get too much importance in the game right now.

**Comment by ShiftyRail** [comment]
It needs to be its own job, implanted, with clear expectations on what the job should do with matters related to :
- prisoners
- brig timers
- arrests
- self-defence rights and OOC expectations of competence/knowledge of space law
- access (right now, a paramed cannot chill with the officers in the brig office. A sec paramedic should be able to)

A regular paramedic doesn't want to deal with all that and shouldn't have to. I agree that a role centred about helping prisoners and keeping company to the Warden would be good (I remember it as one of my motivations to get into coding and fix outfit datums), but it needs to be a clear role with a proper sprite, locker, etc. Not just a headset slapped onto an already existing role with already existing expectations.

**Comment by Apogee-dev** [comment]
Some pretty good points further upstream. The only thing everybody seems to agree on is that the base paramedic role probably doesn't need the headset, so I'm going to remove it from paramed's roundstart gear and lockers for the time being. Unless/until brig medic becomes a thing you'll have to ask an admin for one. As far as the brig medic debate is concerned, I personally think it should be an alt title rather than a dedicated sec role, because sec itself really doesn't need even more expansion and it'd be way too easy to just turn them into another gun-toting secoff. That being said, if enough people can agree on something, I'll gladly code whichever.

**Comment by drawsstuff** [comment]
> Some pretty good points further upstream. The only thing everybody seems to agree on is that the base paramedic role probably doesn't need the headset, so I'm going to remove it from paramed's roundstart gear and lockers for the time being. Unless/until brig medic becomes a thing you'll have to ask an admin for one. As far as the brig medic debate is concerned, I personally think it should be an alt title rather than a dedicated sec role, because sec itself really doesn't need even more expansion and it'd be way too easy to just turn them into another gun-toting secoff. That being said, if enough people can agree on something, I'll gladly code whichever.

may want to update the op then, since this just adds the headset for now +1 from me

**Comment by Apogee-dev** [comment]
So I've been informed that this isn't strictly necessary if it isn't combined with a role that uses it, since you can still use common if you replace the standard headset key with a department one. (e.g. a paramedic that wants to play brig medic in the current version can just replace his headset's common key with a sec key for the same practical effect). In light of that, I'm closing this PR. If and when I write a brig medic PR, I'll wrap this code into it for parity with other multidepartment roles like mechanic and miner that use combination decryption keys.

**Pull request closed without merging**
