### PR TITLE
Strength of spears is affected by the force of the shard used in its creation

### PR DESCRIPTION
**Pull request by unid15**
bonus:

-There's now a delay for creating spears
-Sharpening a glass shard (20% chance each time it's thrown at a wall) now takes its initial force value and adds rand(1,7) to it. In the best case, this makes a glass shard have 12 force and a plasma glass shard 15.

examples:

Using a normal glass shard doesn't change anything (10 singlehanded, 18 twohanded force)
A plasma glass shard gives the spear 3 more force (13, 21 force)
A sharp glass shard - from (11,19) to (17,25)
A sharp plasma glass shard - from (14,22) to (21,28)

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Don't recommend the sharp glass shard thing; 28 force is basically an esword.

**Comment by ComicIronic** [comment]
But it's a non-concealable twohand weapon.

**Comment by Fox-McCloud** [comment]
which can easily be constructed right when you need it.

**Comment by ComicIronic** [comment]
It's still hardly esword-tier in terms of concealment.

**Comment by Fox-McCloud** [comment]
Definitely not, I agree with you there, but its strenght is worrying considering every crew member has access to it.

**Comment by Probe1** [comment]
that's pretty fucking op. 10+3+3 is still serious shit.

**Comment by Unfit** [comment]
How about increasing the attack delay of spears? Perhaps have a chance to have it stuck in the wound, increasing the delay even more, and making the attacker drop it if he moves away before pulling the spear out (which takes, say, a second)

**Comment by Probe1** [comment]
I'd rather it didn't do triple the damage of a stun baton on harm.  It's a nice idea but it's way too strong to have something that good be relatively feasible for manufacture by anyone.

**Comment by ComicIronic** [comment]
>A stun baton is extremely lethal at just 10

Because it stuns, in fairness.

**Comment by FudgePucker** [comment]
>A stun baton is extremely lethal at just 10.

That's because stuns are OP.
With that spear, a non concealable weapon that has to be two handed, in those two or three hits with it, you could be disarm pushed and then beaten to death.
With that stun prod that fits in a belt and backpacks you hit them once and then proceed to beat their face in they can't do shit about it.
The spear has to have the ability to kill extremely fast or there is 0 point to it.
One of the few vampire rounds I did, I went up on the CMO with a fire ax in maint during a radstorm, hit him twice in the face, he didn't go down, he disarm shoves me once, down to the fucking ground, beheaded. If I used a stun baton or scrub gloves instead he would have died.

**Comment by Probe1** [comment]
No, I mean without the stun.  There are 14 bans on the banpage right now listing improper usage of harmbatons.  They are extremely lethal.

Having a 2 hit kill spear is too much.

**Comment by ComicIronic** [comment]
The energy axe isn't two-handed and is w_class 3.

**Comment by clusterfack** [comment]
Check what happens after you attack self the energy axe probe

**Comment by Kurfursten** [comment]
Isn't 28 what the Fire Axe does? That controlled item there are only 2 of.

**Comment by clusterfack** [comment]
The wielded fireaxe has 40 force

**Comment by Probe1** [comment]
I still think its way2much but I've offered my opinion already.

**Comment by clusterfack** [comment]
Spears should be deadly, put a construction delay to make one if it is too easy to instantly transport the materials and make one.

**Comment by Unfit** [comment]
Alright

-There's now a delay for creating spears
-Sharpening a glass shard (20% chance each time it's thrown at a wall) now takes its initial force value and adds rand(1,7) to it. In the best case, this makes a glass shard have 12 force and a plasma glass shard 15.

**Comment by clusterfack** [comment]
Did you make sure that do_after is busy checked

**Comment by Probe1** [comment]
I am happy with the PR and think it will make a good addition at that value.  Thank you Unfit.

**Comment by clusterfack** [comment]
Alright since everyone seems to agree good to go

**Pull request closed without merging**
