### PR TITLE
Plank

### PR DESCRIPTION
**Pull request by ghost**
wood
Using a crayon on a wooden plank will allow you to draw a face on it, creating Plank. Has 1 more force than a regular board.

🆑 
* rscadd: Added the ability to create Plank by drawing on a wooden plank with a crayon.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Give it a `process()` with a probability to send `to_chat()` messages to everyone in range that's hallucinating, speaking to them.

**Comment by SkowronX** [comment]
👌

**Comment by Probe1** [comment]
👌

**Comment by kol1th** [comment]
👌

**Comment by Intigracy** [comment]
:ok_hand:
What next, Wilson?

**Comment by ghost** [comment]
Do you two thumbs down seriously not understand the reference?
DID YOU EVEN HAVE A CHILDHOOD?

**Comment by Lokiamis** [comment]
Just don't like references for the sake of references. I know it's from a children's cartoon.

**Comment by ghost** [comment]
Please no, we already have enough references.

**Comment by ghost** [comment]
you people are no fun

**Comment by Kurfursten** [comment]
There's actually a legitimate critique to this PR, which is that the clown can easily just ruin an entire stack of wood by drawing on every board. There's no way to get regular wood back out.

Similarly he can just deconstruct everything in the bar and convert it to planks

**Comment by Probe1** [comment]
The criticism is pretty legit and I'm thinking maybe we shouldn't be so meme-rific for once.

**Comment by Shadowmech88** [comment]
Using soap on Plank could turn it back into a wooden board.

**Comment by unusualcrow** [comment]
ffs dmi conflicts REEEEEE

**Comment by ghost** [comment]
ok how do i fix this shit

**Comment by ghost** [comment]
fuck it
apparently people don't like references anyway

**Comment by Shadowmech88** [comment]
>apparently people don't like references anyway

What are you talking about? So far the negative votes are a minor minority.

**Pull request closed without merging**
