### PR TITLE
Detective scanner now has an alt-click mode that forces it to scan only

### PR DESCRIPTION
**Pull request by SonixApache**
### What this does
1: ~~Changes scanning from `afterattack` to `preattack` so you can scan boxes before sticking your scanner in them rather than just sticking your scanner in them~~
2: Adds alt-click behavior to switch to 'scan-only' mode, which doesn't call `attack` or `afterattack`, so you don't stick the scanner in boxes
2.1: Note that in scan-only mode, you can't get fingerprint cards off people.
3: Adds little animations for successful and failed scans.
dreamseeker_n8drF1xSyn

### Why it's good
more scanny, details

### How it was tested
tested
with additional sanity testing by razz

### Changelog
:cl:
 * rscadd: Detective scanners can now be alt-clicked to switch to scan-only mode, which prevents it from being put into boxes/coats/etc. Do note that this also prevents the scanner from taking fingerprint cards.
 * imgadd: Detective scanners now have a little animation for good and bad scans.

### CODE REVIEW

**Comment by DrSnips** [comment]
One alternitive idea was a "switch off" for it so rather than worry about what the scanner is going to do, it completely does one thing or another. I think keeping it in preattack is correct too.
Maybe an attack self or altclick, flips a var for an if() thst handles the whole function. So if it's on you can basically never put it in something and if off it never scans something. A simple coder sprite of a green/red dot in yhe corner would surfice but Id imagine it would be quick to whip up for a spriter.

**Comment by SonixApache** [comment]
good job @DrSnips, you made me realize that the solution is so so much simpler than it has to be
alt-click the scanner to switch between normal interaction mode and scan-only mode
lemme see if i have the energy to get that done

**Comment by DrSnips** [comment]
The only thing is if it's an alt-click action make sure you do an in hand check for if it toggles the state.

**Comment by DrSnips** [comment]
Finally the forensic canner, a new way to store evidence

**Pull request merged**
