### PR TITLE
unique vox voices

### PR DESCRIPTION
**Pull request by robintime**
https://user-images.githubusercontent.com/81062934/124340126-edfcda00-db80-11eb-863e-d38351b52403.mp4

^ preview the sounds here! each file (there are five of them) is mixed from a clip of a palm cockatoo speaking.
instead of the charlie brown mumbling, vox will now have equally nondescript parrot mumbling 🦜🦜🦜
i'm open to feedback on these! i chose a palm cockatoo due to their (relatively) deeper sound, but i'm not married to it

:cl:
 * rscadd: vox now have their own special player sounds

### CODE REVIEW

**Comment by Eneocho** [comment]
The voice samples feel like voxes have a cold and speak with that voice when you can't breathe through your nose at all. Very cool, how will the vox metaclub ever cope?

**Comment by ghost** [comment]
I see that i've not been referenced in this PR for my extremely hard and difficult work of hitting two buttons.
Prepare to hear from my lawyer.

**Comment by drawsstuff** [comment]
> The voice samples feel like voxes have a cold and speak with that voice when you can't breathe through your nose at all. Very cool, how will the vox metaclub ever cope?

Eneocho moment
Charlie_Brown

**Comment by Eneocho** [comment]
> 
> 
> > The voice samples feel like voxes have a cold and speak with that voice when you can't breathe through your nose at all. Very cool, how will the vox metaclub ever cope?
> 
> Eneocho moment
> Charlie_Brown

I know it's based on the peanut voice style, but it still feels really nasal, which was my point.

**Comment by TGFH** [comment]
Speedmerge it.

**Pull request merged**
