### PR TITLE
Adds a test map

### PR DESCRIPTION
**Pull request by unid15**
200x200x1

 

Silky smooth (7 seconds to start dream daemon) 

Contains only a gateway, a mining asteroid simulatior, emergency + arrivals shuttles, some lights and a bunch of useless shit that I was forced to add

Perfect for testing away missions, new monsters, new items, basically anything that doesn't require you to load millions of crap

NOTE: some oldcode may runtime and sometimes asteroid vaults break the walls, but other than that there are no issues

### CODE REVIEW

**Comment by ghost** [comment]
But asteroids take longer than any other turf to initialise!

**Comment by clusterfack** [comment]
Yeah this is pretty much the inverse of a test map

**Comment by Exxion** [comment]
Some asteroid would be nice, but it doesn't need that much.

**Comment by 9600bauds** [comment]
REMOVE ASTEROID remove asteroid 

But seriously though this is great, thank you a million times

**Comment by clusterfack** [comment]
Like I'm not wrong here right? 

This includes everything you wouldn't need to test normally and lacks all the things you would.

**Comment by unid15** [comment]
so what should be added in place of the asteroid?

**Comment by unid15** [comment]
removed most of it

**Comment by clusterfack** [comment]
I would say a test map would have
- A separate smaller area that has simulated turfs and dynamic lighting
- The majority area withe everything in it has no lighting and unsimulated turfs 
- It has all the tools for each major department along with supplies for them in a closely set up space

**Comment by unid15** [comment]
> It has all the tools for each major department along with supplies for them in a closely set up space

But you can spawn everything you need

**Comment by clusterfack** [comment]
I hope you aren't being serious

**Comment by unid15** [comment]
I am

What kind of supplies do you mean, for example?

**Comment by ihadtoregisterforthis** [comment]
I'd say surgery, cryo, a chem dispenser with beakers, microwave, less than minimum botany, a room to spawn something alive without it killing itself, some guns, windows and walls to break.

**Comment by 9600bauds** [comment]
Loaded toolbelts are probably the item I spawn the most often when testing shit, engineering vending machines would be convenient
Some machinery requires setup that is a PITA even when spawning stuff, this includes R&D machinery, Cryo, Telepad, probably an at least barebones Atmos cycle
A stocked surgery table would be great too
I hate spawning every individual part of atmos hardsuits including mask and tank, Atmos inconveniences even godmode testing dummies

**Comment by 9600bauds** [comment]
If you want to be cheeky, a few spellbooks would be handy too, especially Jaunt

**Comment by ghost** [comment]
Important note : The floodlights run on battery and will shut off after a while

You might want to code in special floodlights with an infinite battery (the literal infinite battery item, not some variable hack job) for testing purposes

**Comment by unid15** [comment]
I'm not going to add atmos to this btw

**Comment by PJB3005** [comment]
Having to walk around this much...

**Comment by 9600bauds** [comment]
ohhh myyyy goooooddddddd this starts up so fast
merge it now we can make it good later

**Comment by 9600bauds** [comment]
I actually tried map editing for this thing and I can see people making modifications for their own purposes and PRing them later

**Comment by PJB3005** [comment]
Wasn't @probe1 making a test map too?

**Comment by Iamgoofball** [comment]
pfft

just make it a 20x20 mapfile, it'll load up super fuckin fast

**Comment by ghost** [comment]
Go home Goof.

**Comment by Exxion** [comment]
> 20x20

That's barely bigger than the screen. Not exactly a lot of room to test stuff.

**Comment by Probe1** [comment]
this is exactly what I said should be added.  add it.  I will finish up the test map I was asked to do if I get the sudden urge to deal with dreammaker.  

but honestly this is why I never finished it.

> I want to compile and see if something works 

Load up and spawn in on a minimal map with nothing there.

> I want to test it against realistic conditions

Then just load Box it has everything you need.  We don't need "Well it worked on the test map!" accidents.  If something needs real world testing conditions then a map that is in play should be used.  If something just needs to be tested real quick then loading an empty map and typing spawn " whatever is going to be faster than a half step between the two.

**Comment by Iamgoofball** [comment]
@Exxion exactly

you edit the file before hand in Dream Maker and throw down the machines/dildos/pornhub hotlinks you need to test, then join in and fuck with it

you dont need to load a 200x200 map just to test a dildo gun, you can just throw it on the map and not commit the map changes/spawn it in

**Comment by PJB3005** [comment]
That involves a recompile.

**Comment by 9600bauds** [comment]
merge now

**Comment by unid15** [comment]
This doesn't change the game at all and makes life so much easier

Merge cuando

**Comment by 9600bauds** [comment]
We'll fix it in post

**Pull request merged**
