### PR TITLE
Goone Ores to Composite Ores

### PR DESCRIPTION
**Pull request by Kurfursten**
Basically it's that idea I had a couple weeks ago except now in its own separate PR so people can vote if they like the idea.

Now all Goone ores are various ores of existing materials. For example, it might be a rich source of bonus iron or contain a bit of silver. In the case of some, they provide new sources for brass, replicant alloy, and plastic. It also makes a new coal mineral deposit that drops charcoal sheets, kinda like the ice 'mineral'.

This PR doesn't add any of these ores to the normal random mineral lists, but it does create some new random mine tiles that mappers could use if they wanted to have their map with different ore composition. For example, the fuel tile will spawn Char and Coal minerals, while the iron ores tile can spawn any ore that contains iron - Iron, Mauxite, Bohrum, Nanotrasite, Cobryl, and Uqill.

No CL because it doesn't change anything in game yet. None of these ores are currently used and this doesn't add them to any map.

### CODE REVIEW

**Comment by PJB3005** [comment]
Personally I'd rather these be rare rewards you could find on stuff like vaults, that could have unique stats for the metalworking or whatever.

Making them smelt down to "regular" ores just means they'll become nigh useless.

**Comment by Dacendeth** [comment]
I thought there was a vault that had goon ores on it?

**Comment by Kurfursten** [comment]
@PJB3005 We've been waiting 10 years for someone to code Goone-style metallurgy. I guess we'll wait 10 more and leave these ores sitting in the code doing nothing? Because that's literally useless. Using the sprites to have varied geological environments and differences in what you're going after on a map by map basis sounds like a meaningful and interesting change to me. And Mythril is still in if anyone ever fleshes out blacksmithing to care, though at least according to the wiki, you can't use mythril in blacksmithing.

@Dacendeth I'll look through a few suspects, if you remember which you think it is, let me know and I'll check it

**Comment by Dacendeth** [comment]
Clown base has cytine and ejected engine has cerenkite, I remember because when you pick up cerenkite it vanishes and just gives you lethal radiation. Clown one just turns into glowsticks when you try that but you have to mine it to get inside.

**Comment by Kurfursten** [comment]
Looking at the code, the ores have the *extremely weird* behavior of turning into rads/glowsticks immediately when you try to use your hand on them - but you can still bag them with orebags to refine. It doesn't even give a feedback message?

I'd like to add this behavior:
* You can safely pick up cerenkite by hand, but hitting it with any object (other than a bag) causes it to radiate. Also, let's dial back the radiation a little bit and include a message about it breaking apart and releasing gamma radiation.
* Glowsticks won't be made until you use the cytine inhand.

Sound good?

**Comment by ShiftyRail** [comment]
gonflicts D:

**Pull request closed without merging**
