### PR TITLE
MoMMIs can now scan wood, plastic and carpet

### PR DESCRIPTION
**Pull request by 9600bauds**
Sure why not

"Balance"

### CODE REVIEW

**Comment by AutismSpider** [comment]
>no plastic so i can make my autism walls 

Have the wood and carpet build in the scanner

**Comment by 9600bauds** [comment]
Ehhhh... Engieborgs can already create infinite plastic, right?
I mean, you can't law 2 a MoMMI into giving you some anyways

**Comment by AutismSpider** [comment]
yup engieborgs can copy any mat like the normal scanner so you could law two engi borg make endless gold etc

**Comment by SangriaMonkey** [comment]
I don't see why not. Any dickhead can just harm crowbar wood barriers down on the off chance someone emags you.

**Comment by 9600bauds** [comment]
Not too sure about giving these materials roundstart

**Comment by AutismSpider** [comment]
Scanning is fine by me

**Comment by Probe1** [comment]
no plastic

**Comment by 9600bauds** [comment]
it's not like it's used for anything now ;)

**Comment by Probe1** [comment]
its used for the things it was originally intended.  manufacture of machines and such.

**Comment by ghost** [comment]
It'll at least stop MoMMIs taking over muh botany with ALL plastellium trays

**Comment by gbasood** [comment]
@Skullyton Really if MoMMIs are doing that then they should set up their own botany trays

**Comment by Probe1** [comment]
:two_men_holding_hands:

**Comment by 9600bauds** [comment]
Are you hitting on me?

**Comment by Probe1** [comment]
:toilet:

**Comment by ComicIronic** [comment]
I thought borg matfabs had restricted scanning? What happened to that?

**Comment by AutismSpider** [comment]
only mommis  have restricted scanning.

borgs can scan any thing they want

**Comment by 9600bauds** [comment]
Even diamond

**Comment by AutismSpider** [comment]
@9600bauds Diamonds even the left over goon ores etc

**Comment by 9600bauds** [comment]
Leather too

**Comment by AutismSpider** [comment]
Wait can scan leather?

**Comment by Shadowmech88** [comment]
Wait, is leather even a stackable material? I've never seen it in-game.

**Comment by AutismSpider** [comment]
yeah you can stack monkey fur corgi fur and stuff can't build any thing with it

**Comment by clusterfack** [comment]
I agree with wood, maybe on plastic, but carpet is silly.

**Comment by 9600bauds** [comment]
It's the ultimate solution to MoMMI power creep
Distract them with inconsequential autism

**Comment by clusterfack** [comment]
There probably should be more ways to make carpets though, I think the only way is the biogenerator? But that's somewhat unrelated.

**Comment by 9600bauds** [comment]
Pretty sure you can order more from Cargo

**Comment by clusterfack** [comment]
It's very possible, I don't track the supply crate additions

**Comment by AutismSpider** [comment]
Bio gen and cargo for carpets.

**Comment by ComicIronic** [comment]
Silicon material fabricator was a mistake and I'm going to remove it soonish.
Borgs will get to keep theirs minus the scanning.

**Comment by clusterfack** [comment]
So you're really saying you're just removing it from mommi

**Comment by ComicIronic** [comment]
Plus borg scanning, yes.

**Comment by AutismSpider** [comment]
@clusterfack Eggman took out mommi scaning ages ago after me and two other mommis turning the station into clown land with it.

six honk mechs 70% of the station made out of Bananium.

**Comment by Shadowmech88** [comment]
What would prevent an engineering borg from using its matter synth to do essentially the same thing?

**Comment by ihadtoregisterforthis** [comment]
It happened before too, but borgs aren't usually so autism driven and ocassionally LAW 2 will break its concentration.

**Comment by AutismSpider** [comment]
@Shadowmech88 Lack of autism and law two buts it happen in the past

**Comment by kol1th** [comment]
> Silicon material fabricator was a mistake and I'm going to remove it soonish. 

How do you expect MoMMIs to build/improve/repair the station with a limited supply? Expect them to ask the miners nicely for materials? Might as well just remove MoMMIs tbh. Derelict mommis will be useless too, no materials to do anything at all with unless they get off the z-level somehow and rob the station/miners

**Comment by AutismSpider** [comment]
@kol1th it go back to old one were its build in and they get more sitting in recharging station.

**Comment by ComicIronic** [comment]
Who said they were going to end up with a limited supply? They're just going to lose the fabricator, don't shit your britches.

**Comment by kol1th** [comment]
@AutismSpider oh thats better than I thought I guess but still pretty gay

**Comment by AutismSpider** [comment]
is this going get in or not?

**Comment by Probe1** [comment]
no plastic.

**Comment by 9600bauds** [comment]
I'd like an explanation on why not, especially since this is only for MoMMIs

**Comment by Probe1** [comment]
Because it would greatly devalue plastic and it is considered an uncommon material on the level of gold/silver/uranium

**Comment by AutismSpider** [comment]
>uncommon

>engi borgs can copy it and shit it out like candy same go's for gold silver uranium and other rare mats

funny to me

**Comment by clusterfack** [comment]
I don't significantly either way, merge it if you feel its fine as is.

**Comment by Probe1** [comment]
thats engiborgs for you. mommis can't.

**Comment by 9600bauds** [comment]
Plastic is only used for two machines, one of which is unusably bad, the other of which is not necessary and unlikely to be used as a MoMMI
This is the reality post-GSU
Plastic is also everywhere, and a MoMMI will still have to decon plastic flaps to get the initial plastic to scan
This is also for MoMMIs, so humans won't be able to just tell them to make more
If this devalues anything, it's an already worthless material and only so for MoMMIs specifically, which have almost no use for it anyways
I see it more likely that 99% of the plastic made this way is only used for lego autism walls

**Comment by AutismSpider** [comment]
@Probe1 nothing stopping sci nerd or that useless as fuck job law two any cyborg to go engi/reset to engi to copy and crap out mats endless


Mommi will build autism lego walls and floors with this

**Comment by MercuryDoll** [comment]
Sounds fun, i support this.

**Comment by clusterfack** [comment]
I hope you are all ready for mommis to become op as fuck autismally then, you were warned!

**Comment by Probe1** [comment]
Don't be cheeky this has fuck all to do with their intended role and devalues materials.

**Comment by AutismSpider** [comment]
Any time you talk about materials i will point engi borg the engi borg can copy all material types devaluing them to nothing.

Come up with some thing better or fuck off

**Comment by 9600bauds** [comment]
Please save the fear of MoMMI creep for when actual power creep happens

**Pull request merged**
