### PR TITLE
Roidstation - Sparerushing Hotfix

### LINKED ISSUE #24436: Roid Warden Locker still has .45 ammo
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
c7a7a2a1f03c9d1d0fcc7715c9915e616b238af4

# Description
Some mapper goons took my beloved .45, my queen, and replaced her with a rancid NT Glock Custom. Though I have many issues with this, the main problem is a definitive lack of .380 ammo in the locker. Instead, the .45's ammo is still in there. This is cruel, and only reminds me of the loss of a loved one.
# Steps to Reproduce
Go to warden's locker and look at it
# What you Expected
To have an ammo that fits my new ""gun""
# What Actually Happened
I cried in the corner of the room, wishing I still had my .45 with me.

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[roid] [funpolice]

Closed the Captain's Office Shutter to alleviate the rampant sparerushing greyshittery I see every time I observe a round of Roid. Also since no fun is allowed I took the extra (useless) .45 ammo out of the Warden's Locker.

Closes #24436 

:cl:
 * tweak: Roid: The Captain has been advised to be more careful about locking up his office before the start of each new shift.

### CODE REVIEW

**Comment by Zth--** [comment]
>mapper replaces the .45 for a glock on a bugfixing PR without mentioning it, but he forgets to replace the ammo
>your local player angrily reports it
>the ammo gets deleted instead of being replaced

Guys...

**Comment by Irradiation** [comment]
>Hotfix

I've been telling you about this issue for months, Veers.

**Comment by ShiftyRail** [comment]
I once had a wonderful round on roid involving chasing one assistant for 30 minutes because he rushed the spare, and having said assistant break out of perma 2 times, so I cannot support this PR, even though I see the rationale behind it

**Comment by calzilla1** [comment]
Just give the warden back his .45

**Comment by calzilla1** [comment]
I want to be able to shoot cults with Colts again

**Pull request closed without merging**
