### PR TITLE
Vox trader can now visit mech graveyard

### PR DESCRIPTION
**Pull request by ondrej008**
:cl:
 * bugfix: Vox traders can now visit the mech graveyard by using the disk on their shuttle computer

### CODE REVIEW

**Comment by Eneocho** [comment]
I've literally never seen anyone use the coordinate disk to visit the mech graveyard, this change can't be that bad, despite being yet another vox powercreep.

**Review by Kurfursten — CHANGES_REQUESTED** [review]
You need to test **every** map's trader shuttle to make sure it will work. That dock is _small_ and it's not designed for the bulky trader shuttle blueprints. I don't know if it will even fit the basic Boxstation model much less the gamut of different shapes and sizes - especially the megashuttle on Meta.

What I would like is for you to post screenshots with it in dock on each map.

**Comment by PrimeDSS13** [comment]
how much creep do traders need

**Comment by Eneocho** [comment]
> how much creep do traders need

I honestly hate how much content is gated behind traders. If you could get it as a non-trader with some effort it'd be ok, but all the gates to avoid non-traders from accessing it are just dumbfounding. Oh, you want to do a cool project that requires tradergoods? Very good, keep fluorided. What's that, there are no traders? Fuck you.
The only way for a non-trader to get access to the trader system is to have a trader already, which defeats the point.

**Comment by Armadingus** [comment]
Restrictions like these are meant so that traders are encouraged to trade their goods rather than use them for themselves.

**Comment by Eneocho** [comment]
> Restrictions like these are meant so that traders are encouraged to trade their goods rather than use them for themselves.

Point to the contrary: The DSES. I insist that it should've been a podfab item so you could have the deep space sonar when using the DEDICATED ROLE FOR SPACE EXPLORING, but it got added to the traders. I have never once seen the DSES being used by a non-trader, meaning it never has been traded.

**Comment by Kurfursten** [comment]
I am noticing a theme in Eneocho posts where most of the time his comments are that he wants to change something entirely out of scope or barely tangentially related to the PR

Regardless, I don't see evidence this would work nor general support for this change

**Comment by Eneocho** [comment]
> I am noticing a theme in Eneocho posts where most of the time his comments are that he wants to change something entirely out of scope or barely tangentially related to the PR
> 
> Regardless, I don't see evidence this would work nor general support for this change

I didn't bring up the topic of tradercreep, I just expressed my issues with it. Though I see your point.

**Pull request closed without merging**
