### PR TITLE
Revert "Damage effects for items broken out of lockboxes"

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
Reverts d3athrow/vgstation13#11753

Quoth Pomf:

> This PR is fucking stupid and whoever merged it should feel bad, more RNG is not what the game needs. this is akin to adding fucking critical hits to attacks.

The chicken has spoken.

### CODE REVIEW

**Comment by yclatious** [comment]
All hail the chikun

**Comment by SonixApache** [comment]
RNG isn't an issue if non-antags don't illegally access weapons they shouldn't have.

**Comment by icantthinkofanameritenow** [comment]
If illegality is the problem, then perhaps that's a reason for Security to get its shit together. IC problems require IC solutions. We literally just went over this in discord four minutes ago.

**Comment by Kammerjunk** [comment]
I think I'm either too dumb to follow you or that needs some more detail.
People should not be "illegally" getting weapons without proper authorisation via ID changes, therefore the RNG aspect of illegally getting those weapons (read: making them useless via making them extremely inaccurate, do less damage, or straight up be a danger to yourself and/or those around you) isn't an issue?

**Comment by SonixApache** [comment]
The RNG aspect only applies if you break open a lockbox -- something you shouldn't be doing. 
If you're an antag, you could emag it, agent card to get access, kill someone for access, etcetera.
If you're not an antag, your only option is to get (someone with) proper access to open it.
Having a broken gun is a more logical solution than just having the contents removed altogether, which is a good thing.

**Comment by aceedex** [comment]
you know, I was JUST about to come here and do that myself. good on you.

And for good measure, just allow me to state:
What did this PR even fix? what was the issue?
-Antags have their own weapons/can emag open
-non-antags looking to defend themselves and crew are now fucked
What was the issue? valid hunting? because that's not a problem here
gunshittery? that's administrative. It's no different than someone going to town with a toolbox
science too strong? all of the good protolathe weapons were nerfed into uselessness. the most reliable weapon that they have is a laser rifle, strictly a no-stun weapon. (unfuck ARs when?) specially when cargo got a gun that 5 less brute damage, but only costs money. Not a giant pile of materials and silver for bullets that because of this PR, can be all drained in one shot with masssive friendly fire, but that's another issue.


So really, what IS the fucking point to that PR? what does it solve? what does it do?
the only decent change is the weapons permit thing, by itself.  Coupled with that PR it's like putting a bandaid on a hole in the side of your head

**Comment by icantthinkofanameritenow** [comment]
@Kammerjunk 
As was exhaustively explained, in lowpop there may not _be_ a legal way of getting those weapons due to the people possessing those permits being absent or dead. And whoever steals the spare will not be likely to sit around granting access upgrades after giving themselves all-access. 

@SonixApache 
Aren't you being a trifle naive about all this, assuming that only antags would want guns and that there will always be a way to have legit access in a round? Even your own PR doesn't guarantee it, seeing as there's no certainty a RD will appear either!

Unless you also want to have force rounds to have at least one security staff before it can begin (yeah, like that'll ever happen), it's a good idea on paper that simply will not work reliably in practice.

**Comment by SonixApache** [comment]
So what if R&D guns are locked out because there's no access? The same would apply to having no power due to no engineers, no food because there's no chef / hydrophonicist who cares, not getting cloned because there's no doctors, not beating up the clown because there's no sec and not being able to order pizzas because there's no cargo.

This basically just puts sci in line with the rest of the sectors, and does it in a way that isn't too invasive. And yes, everyone wants guns, because the station is a dangerous place and guns are pretty damn good weapons. It only sounds logical to me that guns would be harder to acquire than less effective makeshift weapons.

**Comment by aceedex** [comment]
@SonixApache singularity having 1% chance to go loose because a medical doctor had to hack in to set up power WHEN?

**Comment by PJB3005** [comment]
HERE WE GO AGAIN!

**Comment by SonixApache** [comment]
@aceedex okay, so the issue is RNG bullshit.
So just revert this and make lockbox contents disappear if blown open? Or make them invincible?
Oh, and 'guns are as critical to the crew as power is to the station'

**Comment by aceedex** [comment]
@SonixApache SME booping itself out of existence because the clown had to set up power WHEN?
cap's spare having a 50/50 chance to do a 1,1,1 explosion when used by non-captains WHEN?

**Comment by icantthinkofanameritenow** [comment]
@SonixApache 

> less effective

Another part of the problem. Those makeshift weapons aren't simply "less effective", they're borderline useless due to most of them being overly dependent on a gimmick of one kind or another. Would it really be that hard to make a two-shot ghetto taser? 

> So just revert this and make lockbox contents disappear if blown open? Or make them invincible?

Them being destructible in the first place was due to the very same reasons I already described.

**Comment by Allspice** [comment]
Lockbox nerf stays in but re-add ninja tiles too, good compromise where everyone's angry.

**Comment by SonixApache** [comment]
^ + buff toolboxes even more

**Comment by SonixApache** [comment]
@aceedex R&D is not the only source of guns, and definitely not the best or easiest -- R&D guns are not remotely as necessary to the crew as power is.

**Comment by Allspice** [comment]
were cargo crates even fuggered like lockboxes were
or lockers

**Comment by Kammerjunk** [comment]
@SonixApache 
No, the best and easiest would be cargo, but that'll be going next.
Good luck catching my sekrit crate opening techniques honed over years, buckos

**Comment by aceedex** [comment]
And engineering isn't the only source of power. Get an AME crate and get the pac-mans from the roid up there.

All those complaints have a parallel

**Comment by d3athrow** [comment]
IC issues should be resolved IC unless it becomes chronic or affects other players negatively (ie killing then they get bannu)

**Comment by icantthinkofanameritenow** [comment]
@d3athrow 

Exactly! If a shitter keeps doing gunsci, the problem isn't with RnD- it's with the shitter, who should be treated just as he deserves.

**Comment by yclatious** [comment]
Shame it took pomf to finally say what we were saying to begin with to be heard

**Comment by SonixApache** [comment]
@Kammerjunk my point exactly. The ancient art of ordering 30 shotgun crates and a goat,

**Comment by Kammerjunk** [comment]
@SonixApache fug

**Comment by yclatious** [comment]
Oh like if nobody knew it Kammer, the secret was out as soon as any admin gave a toss and watched cargo for half a second

**Comment by Kammerjunk** [comment]
@yclatious I'm kidding you dumbo

What even is the difference between nerfing illegally opening lockboxes and nerfing illegally opening cargo crates? It's the same thing you're doing, you're just doing less work for it at cargo (with greater reward)

**Comment by yclatious** [comment]
I don't even know, nerfing shit to begin with is dumb, guess they just didn't make it for crates aswell, because effort or something.

**Comment by Iamgoofball** [comment]
🈂️ 🏷 🌮

**Comment by PJB3005** [comment]
There I fixed conflicts for you.

**Comment by icantthinkofanameritenow** [comment]
@PJB3005 
I see, thanks.

**Comment by coldcola** [comment]
@yclatious 

> guess they just didn't make it for crates aswell, because effort or something.

Don't be silly you know it's because someone got their shit knocked in by a scientist with a gun.

I'm really surprised at people trying to divert from the fact that this is an IC issue, maybe security needs to start keeping an eye on science as much as they do with cargo and we wouldn't have this issue.

**Comment by SonixApache** [comment]
Isn't the biggest issue with this thing that there may not be sec (to open lockboxes)?

**Comment by icantthinkofanameritenow** [comment]
Yes. Or anyone capable of reassigning accesses either. Or most often, both of those at once. And that assumes they're always able to do so. In practice, salty ex-antags can get put in those positions and refuse to allow those access changes out of spite.

**Comment by aceedex** [comment]
The problem is simpler than that

There is simply no guarantee that players with the means to open those lockboxes legally will be able to do so. And because of that, absolutely everyone else that might need a gun to fight is getting fucked over

for what purpose?

**Comment by clusterfack** [comment]
@d3athrow we had a poll on this http://ss13.moe/index.php/poll/64

**Comment by AutismSpider** [comment]
@d3athrow 

>PR is up for weeks
>an entire server poll happens
>he doesn't say a thing about it until it's already merged


not even trying any more are?

**Comment by AutismSpider** [comment]
@coldcola people who play sci are massive faggot to point better to kill them on the spot

**Comment by icantthinkofanameritenow** [comment]
Nice meme tags, PJB. Care to explain why none of those were added to the original PR?

**Comment by SonixApache** [comment]
what the fuck PJB, this gets [honk] but my literal honk batons don't?

**Comment by BarneyGumball** [comment]
:-1: 
A server vote was held and the majority was for it.  It's been in for less than a day.  It's time to stop theory crafting and see what the actual effects are.

**Comment by FudgePucker** [comment]
Muh poll.
You mean the poll that had a three vote diffrence?

Here is my input on this situation. With a story about one of my rounds.
I am the CE, while patrolling maintenance see that we have a carp problem. I go ask warden for a laser gun. Apparently it would be too risky to hand me a laser gun (never mind the fact that with my access I could subvert the borgs, plasma flood, singloose, drag around the shard, or all of above, me having a laser gun would be too big of a risk), and that an officer could handle it. So I wait until later for the officer to patrol maintenance and do pest control to continue looking for problems. See another carp waiting outside a window to space, have to walk all the way back to security to ask for a gun again, denyed again.
In hindsight I could have just used my mechanics access to print a gun instead of asking nicely.

Fuck interaction. Why should I have to depend on captain condom and his sidekick head of shitbags to do something?

**Comment by SonixApache** [comment]
What are you, casul? Why didn't you just go at him with a welder?
Could've asked an officer directly. Was there a HoP? Captain? Any cargo whatsoever?

How is your story related to lockboxes? What I get from your story is that the playerbase still needs to adjust to this change, and maybe be less uptight about handing weapon permits to heads.

**Comment by icantthinkofanameritenow** [comment]
> fighting in melee with a carp
> which can attack much faster than you and break hands in mere seconds

You must really wanted him to kill himself and cause a breach in the process, didn't you? Also, note the refusal of the warden to give a weapon in light of a perfectly reasonable request from a head of staff for no reason other than to be a petty jackass. Even if that wasn't the case, the fact that no carp was killed in between those requests is a good reason why the redshirts alone can't be trusted to keep people safe- they're too busy lording their power over everyone else to do their jobs. 

Also why anything that requires interaction to work needs an alternative- even when interaction would clearly yield a better result, people will refuse to do so for trivial reasons such as not liking the person with whom they must interact.

**Comment by SonixApache** [comment]
Yes, some wardens are shit, and some are not.

A counter-anecdote, then; Day or two ago I was sec and there were carp, so I geared up in an EVA suit and asked the captain for a laser. Went around removing carp with my laser and welding tool, took me 3 recharges but I got it done. Went back to sec, tossed the laser in the back since I wasn't using it anymore and went to go take off my suit. Then, the entire security staff including a posibrain in a phason mech, the captain, and his up-accessed lackeys fucked off to do an away mission, leaving me as the only sec on the station. However, the carp came back in greater numbers, prompting me to have to rip open the armory for some more guns to remove them.

My reward for clearing the entire station space of carp twice? Almost dying in medbay during broken hand surgery, because my internals ran out and they couldn't figure out why I was choking.

Point being, some players are shit. Complain about it IC, figure out a solution and get on with your shit.

**Comment by icantthinkofanameritenow** [comment]
Counter-counterpoint: You were security, which by definition is already trusted to use those weapons correctly in the first place. They would never reject a request from one of their own to be armed in the face of a threat- the same one that Fudge faced, I might add. All I'm saying is that they should be reasonable, not act as if they must either never let a single bullet out of the armory or give it away to the first greyshit who asks. 

Same goes for weapons access and lockbox opening- when it needs to be changed in order to arm more people, the ones who have the ability to do so, either due to being too fixated on protocol or the aforementioned saltiness of a failed antag. If anyone had any faith in the legitimate process being viable, nobody would ever try to break one open unless they were an antagonist or a turboshitter.

**Comment by SonixApache** [comment]
I personally always busted open lockboxes because it's a hell of a lot faster than asking someone to open it. People might be willing, just takes ~10 seconds longer, and ain't nobody got time for that.
I've opened and asked people to open plenty of boxes before, though. (before I knew about the bucket trick, mostly.) Again; it's the players that need adjusting, and this lockbox thing is a good way to push them in the right direction.

**Comment by Exxion** [comment]
Simply removing lockboxes is better than reverting it
Prior to these changes, lockboxes served basically no purpose

**Comment by icantthinkofanameritenow** [comment]
There are better ways of adjusting player behavior than this, and that's assuming it's even something that needs adjustment. Tell me, before this thing happened did RnD go full cargonia on a regular basis? If so, it sure never happened any of the many times I played RnD. If anything, the adjustment should be on the heads and Security, for their part in almost always finding a reason to deny a perfectly logical request and so ensuring that people have no choice but to break them open. If they were actually willing, this would have never been an issue. Oh sure, you might be willing to do so but that's of no help unless you play HoP exclusively. 

Look, lockboxes were made destructible in the first place _because_ that 10 seconds can be the difference between life and death..._**if anyone alive in the round  is able to open them legitimately at all**_. I personally prefer to do it the legit way, but I've already listed all the cases where neither the time nor the ability to do so is present, and I'd rather break procedure than die.

**Comment by Blithering** [comment]
@icantthinkofanameritenow Recent changes to the lockbox requirements means any sec officer, or even the barman can open them. It now requires weapons permit rather than armoury

**Comment by icantthinkofanameritenow** [comment]
@Blithering
A step in the right direction that should have been implemented on its own, but right now that it is ultimately Irrelevant, given all of the many rounds where security is absent, dead, or incompetent. No permits, no legit opening, and no hope for dealing with murderboners. 

You can't even trust the bartender to show up if it's deadpop, for fuck's sake.

**Comment by Exxion** [comment]
At the VERY least, if people do want to revert it, rather than reverting the whole damn PR (which added some logging and a lot of other nice things), only remove weapons being damaged by breaking the lockboxes

**Comment by icantthinkofanameritenow** [comment]
I would have done that if he had only added them in independently. Instead it's an all or nothing deal, though I wouldn't be opposed to the good parts being added in on their own in separate PRs.

**Comment by Sprok0** [comment]
you can literally just remove the become_defective() proc from lockboxes.dm, that's what makes weapons become damaged when broken out. I coded it in a way that should be easy to add/remove from wherever

**Comment by icantthinkofanameritenow** [comment]
@Sprok0 
Fine, calm your tits. I'll remake this so it only removes the trash while keeping everything that isn't worthless.

**Comment by icantthinkofanameritenow** [comment]
Remade, use #12157 for further discussion.

**Pull request closed without merging**
