### PR TITLE
Mob shrinking standardisation

### PR DESCRIPTION
**Pull request by ghost**
[tweak][consistency]
DNA SMALLSIZE block is now in line with the MoMMI virus symptom.
Code has also been moved into update_transform(), allowing the changes to be animated.
:cl:
 * tweak: The small size DNA block now actually shrinks the users appearance.
 * rscadd: Shrinkings from small size DNA and MoMMI viruses are now animated.

### CODE REVIEW

**Comment by Viciousaurus** [comment]
Would like to see a picture of the pr in action

**Comment by Eneocho** [comment]
Now we can properly shame the manlets. bless

**Comment by Exxion** [comment]
Why not just `M.transform.Scale(whatever)`?
Also this will absolutely not cooperate with anything else that changes `transform` whatsoever

**Comment by ghost** [comment]
> Why not just `M.transform.Scale(whatever)`?
> Also this will absolutely not cooperate with anything else that changes `transform` whatsoever

Code is exactly like the MoMMI symptom, so problems with this apply there too.

**Comment by Exxion** [comment]
OK
They're still problems

**Comment by Killette2** [comment]
Will this stack with the mommi shrink?

**Comment by Eneocho** [comment]
>Will this stack with the mommi shrink?

Double manlets. Amazing.

**Comment by ghost** [comment]
Code is now ```M.transform.Scale(whatever)```

**Comment by Exxion** [comment]
I think `Scale()` is relative, so returning them to original size would require scaling them back up rather than simply scaling by 1. I'm not certain, though.

**Comment by Kurfursten** [comment]
I am also pretty confident that Scale is relative. You should test this.

**Comment by Blithering** [comment]
Important question, will this create dwarfs or hobbits?

**Comment by ghost** [comment]
> Why not just `M.transform.Scale(whatever)`?

Update: Doing this does not work at all, so it was reset to how the virus does it and it works the same @Exxion

**Comment by Exxion** [comment]
And again, that's not viable. This is not the only thing that modifies `transform`. Doing it this way will reset any other changes to `transform`.
What exactly doesn't work?

**Comment by ghost** [comment]
Managed to get it to work in one line with *=, also moved transform editing to update_transform() and added conditionals so it co-operates with the lying transform update @Exxion

**Comment by Exxion** [comment]
The scale factor should be a define or something, and the factor to scale back up should be in terms of that. `1 / that_define`
Also if you're using those conditional checks, just `transform.Scale()` should work? The matrix multiplication method I said was supposed to avoid the checks but if it still needs them then it didn't work.

**Comment by ghost** [comment]
Scale factor is now a define, and 1 / scale factor is now used in the inverse.

**Pull request merged**
