### PR TITLE
Clown Voice Changer

### PR DESCRIPTION
**Pull request by Arthurdentist**
Adds a clown voice changer for syndie clowns. Normal voice changer that looks like a clown mask instead of a gas mask.

### CODE REVIEW

**Comment by SkowronX** [comment]
I TALKED. JUST. LIKE. THIS.

**Comment by Arthurdentist** [comment]
w-was that supposed to mean something?

**Comment by SkowronX** [comment]
Watch the movie

**Comment by ComicIronic** [comment]
>he hasn't seen who framed roger rabbit

Demanding a cartoon-drawn esword immediately.

**Comment by SkowronX** [comment]
Also, no longer needed since the mask now acts like a chameleon mask.

**Comment by Arthurdentist** [comment]
fair enough then, I'll close this PR

**Pull request closed without merging**
