### PR TITLE
A dispassionate attempt at testing the game without (roundstart) AIs

### PR DESCRIPTION
**Pull request by ShiftyRail**
image

#21036 was attempted a little less than a year ago. It got closed. I want to bring this idea back.

I'll copypaste the argument I made at the time for the PR to be, at least, test-merged.

I think that AIs don't make a positive contribution on the vast majoriry of rounds.
AIs gimp round progression by being the invincible eye in the Sky which spies on every antag and every crewmember.

As a result, the #1 priority for an antagonist is to kill, or subvert, the AI. And for security, in the event of, say, Cult or Revs, their #1 priority is to get the AI off Asimov because it'll impede their ability to work properly.

This is not a problem with Asimov, as often said. Asimov is the only way to make AIs bearable on non-cult/non-revs, but it does not work anyways because of the extreme lust for valids an AI has.

The problem is that we have to do that almost every time. It's frustrating, it's bad for round variety and round progression. In short, AIs reduce the general fun of the game simply by existing and this, funnily, without even breaking their laws.

>I died

Not that it matters but I rarely if ever play antag ; I just had too many rounds where the AI just valided the antagonist 30 minutes in, without trying to engage in any sort of gimmick. And that's frustrating.

>Just kill the AI

Killing AIs is trivial. It's akin to a washing machine laundry program. It's not fun to do because they're griefing or have been subverted.

>Get it off Asimov

Same as above. Not to mention that silicons feel more free to grief people on other lawsets (not even getting banned for it because of some retarded logic that EVERYTHING a silicon does on non-Asimov is the fault of the uploader) and the laundry rountine of carding the AI is more present.

>It's a player problem, not a problem with the role

I disagree with this on the basis that an omniscient, quasi-omnipotent eye in the sky, even played PERFECTLY (as in, don't snitch on harmless antags, is not a cunt to people on purpose...) is still compelled by Asimov to hunt & kill that Vox trader or that vampire, and so on.
The traitor himself has no way to know if the AI will play nice or not and as such will be encouraged to take the AI out.
Finally, the AI remains due to its sheer power the number 1 priority on cult or revs. The flaw is within a role that is too powerful, rather than a player issue.

Those arguments, I think, still apply. I will admit that the frequency of me coming into conflicts with AIs as a player isn't the same, but again I played a tad more in 2018 than I do today.

I think it's telling that even with how highly different the playerbase is when compared to late 2018 (a certain youtuber made his mark on the game), most of the problems of the AI role are still here.

I also want to finish this by saying that I'm fully aware this is a "inflammatory" changes, and I might come across as trying to start shit and forcing views unto people. For this PR, I want to stress this isn't my intention.

I know there are good AI players & good silicons players. I just believe that, from a game standpoint, the constraints and negative of AI outweigh its presence. I don't feel as strong in that belief as I felt a year ago, though. If this PR gets too much controversy, I'll happily close it down.

### CODE REVIEW

**Comment by brndd** [comment]
I see you've gone to great lengths to avoid the R-word here, but all your euphenisms are in vain.

>compelled by Asimov to hunt & kill that Vox trader or that vampire, and so on.

This kind of interpretation of Asimov is a player problem, not a mechanical problem. Lawsets are all about interpretation. Take Asimov to its logical extreme and you should be bucklecuffing all crew members at roundstart to prevent the potent hams. Nobody does that because it's fucking stupid, but many of the shitty AI players still do less extreme but still fucking stupid interpretations of their laws, and what you described is an example of this.

**Comment by ghost** [comment]
I still firmly believe it's a policy issue

I've said dozens of times that allowing Captains to set it to NT Default roundstart to be Security's pet was a bad idea, no-one listened

I've said dozens of times that allowing AIs to directly impede non-violent antagonists with stuff like constantly being on Security channel or mass bolting was a dumb idea, no-one listened

I very clearly wrote in the AI's wiki page that they shouldn't be hunting for antags save for potential (now probable) harm, was never made server policy

Why are we handling this as a code issue and constantly trying to nerf the Silicons in the most roundabout ways possible ?

This issue existed all the way back in 2014. I asked for stricter RP rules for AIs, never happened. Some AIs play properly, it's the bad AIs every time. It's like MoMMIs pre-interference law rewrite

**Comment by utilitas-** [comment]
AIs are absolute shit because of administration, not because of code. It's because you fuckers completely forgot about the basic tenet of SS13: absolute chaos. By restricting AIs with thousands of unspoken rules, you shit not only on the AIs but also on the game itself. It's not just unspoken rules concerning AIs, but it's the most visible part because there has always been the rules you actually get versus the rules you should actually follow (as ASIMOV) and it's fucking stupid.

Remove all the rules, make the server great again. I know you won't.

**Comment by utilitas-** [comment]
also "depassionated" isn't a word you fucking hack
it's dispassionate

**Comment by utilitas-** [comment]
also "depassionated" isn't a fucking word you fucking frenchie
it's "dispassionate"

**Comment by ghost** [comment]
> By restricting AIs with thousands of unspoken rules, you shit not only on the AIs but also on the game itself.

if there's thousands of unspoken rules then you should easily be able to name 100, let's hear them

**Comment by utilitas-** [comment]
I'll get to you on that tomorrow mom

**Comment by dsfartgeg** [comment]
Weren't you going to make your own server or something that was totally better than vg

how'd that go

also aren't you banned from playing AI for being a shit

**Comment by ShiftyRail** [comment]
I'm not banned from AI and I never wanted to make another server.

**Comment by utilitas-** [comment]
he's offtopic posting about me you dum dum

**Comment by Caboozles** [comment]
>Not that it matters but I rarely if ever play antag ; I just had too many rounds where the AI just valided the antagonist 30 minutes in, without trying to engage in any sort of gimmick

On one hand, I’ve seen AI cry out for blood when they see something like an antag break into a door, but I’ve also seen antags (and sec) BITCH when an AI calls out blatant harm like someone getting beaten by an esword and alerting the entire staff. Sometimes antags do themselves no favor, and an AI is explicitly instructed to not just “roleplay” asking some silent shuffle cultist to not kill someone as they beat the chaplain to death. This is entirely a player or administrative issue.

And an AI asked to hunt a vox antag is not compelled to kill it. Just because an antag is caught does not mean their game is over.

**Comment by Caboozles** [comment]
>Not that it matters but I rarely if ever play antag ; I just had too many rounds where the AI just valided the antagonist 30 minutes in, without trying to engage in any sort of gimmick

On one hand, I’ve seen AI cry out for blood when they see something like an antag break into a door, but I’ve also seen antags (and sec) BITCH when an AI calls out blatant harm like someone getting beaten by an esword and alerting the entire staff. Sometimes antags do themselves no favor, and an AI is explicitly instructed to not just “roleplay” asking some silent shuffle cultist to not kill someone as they beat the chaplain to death. This is entirely a player or administrative issue.

And an AI asked to hunt a vox antag is not compelled to kill it. Just because an antag is caught does not mean their game is over.

**Comment by ghost** [comment]
If latejoin silicons are going to get a testmerge then this should too. Then players can vote on both to see if either of them are good ideas.

**Comment by jknpj** [comment]
How can you testmerge late-join as AI with AIs removed?

**Comment by ghost** [comment]
Testing them SEPARATELY was supposed to be implied.

**Comment by calzilla1** [comment]
AI's are just not fun to play around. 90% of the time when the laws are changed it's either "Kill all the crew" OneHuman or "Kill all the antags" Robocop. When I think of antag Gimmicks I don't think "Hmmm how will I pull this off with out the crew dunking me", it's instead "Hmmm how will I pull this off with out the AI bolting me into a cuckcage." Even when I'm not an antag, when I play warden I roll the dice whenever the officers bring in a new to-be prisoner whether I'm gong to play the law 2 tug-of-war. They're not fun, fuck the silicon meta-club, and the game would see a marked improvement if the AI was nerfed into pAI territory.

**Comment by brndd** [comment]
>90% of the time when the laws are changed it's either "Kill all the crew" OneHuman or "Kill all the antags" Robocop. 

Confirmation bias. Much of the time when the laws are changed you probably don't even realize it, but you *do* realize it every time when the AI gets subverted or put on the epic validhunting lawset.

>when I play warden I roll the dice whenever the officers bring in a new to-be prisoner whether I'm gong to play the law 2 tug-of-war. 

Crackpot idea: roundstart disable the AI control wire on cell and perma doors.

**Comment by Allspice** [comment]
one thing that would be nice is laws actually being sequential, instead of the law 4 onehuman retardation

**Comment by Kammerjunk** [comment]
gonna spare the wall of text addressing each and every thing you've said because this isn't debate club, but if the issue is "the extreme lust for valids an AI has," you have a problem with players, not roles

**Comment by DamianX** [comment]
Get someone to testmerge this, then immediately revert it yourself. That's the formula to get the policy change many desire.

**Comment by ShiftyRail** [comment]
I'll leave this open a day or two, if the votes are still this balanced I'll close the PR.

**Comment by Senaat1** [comment]
One thing that hasn't been mentioned is the role AIs actually play. Things like opening doors for security, bolting down criminals, opening EVA during emergencies, bolting off plasmafires, that kind of thing. The AI mainly has a managing and organizing function within the station and getting rid of that entirely without a viable alternative seems a bit harsh.

Ontop of that, it makes the life of antags significantly easier if there's no eye in the sky to play around. Currently, if someone yells out HELP the AI will jump to them and see what's going on and relay information to the rest of the station. With this change it'll be much, much easier for antags to dab on people safely.

**Comment by ShiftyRail** [comment]
I think this illustrates that the AI is a crutch for access as a whole, personally.
Also, while this might be pure wishful thinking, I think antags would feel freer and take more risks (ie, not permanently remove people, but rather hide bodies in place where they can be found), if the threat of being instantly shut down by the Eye In The Sky isn't as oppressive anymore.

**Comment by Senaat1** [comment]
The AI isn't a crutch but it's a safety valve. Access-restricted doors are good in theory but sometimes you need doors opened or bolted/unbolted in a hurry, and the AI works for that. The alternative is security having to hack their way into a department to stop an active shooter or the Captain/HoP having to accompany Security at all times.

And if anything, permanently removing people will become significantly easier. The most convenient ways of doing so, spacing and cremating, are in areas the AI can currently monitor. Hiding a corpse in maintenance is safer because there's no AI but the corpse can also be found quicker.

**Comment by ShiftyRail** [comment]
I have strong opinions on the topic of "permaroundremoval", and I found that one line said often by the said "round removers" (the term is imperfect, but it works) was, "well, I'm gonna get valided soon anyways, so might as well antagonise a few people to the max", since the moment the AI catches them, it becomes very hard to evade its eye.

Again, this could be wishful thinking, but if those antagonists didn't have as much pressure on them once their first crime was discovered, maybe they wouldn't be so inclined to "stun-locker-weld-space" the people they antagonise.

**Comment by utilitas-** [comment]
then how 'bout you just make round removal not a big fucking deal
enable respawning
put mommi spawners back on the station
if someone abuses it, ban them


oh wait that would require admins to not rely on the code every single time, nevermind

**Comment by Myrios** [comment]
I do rather think it is somewhat telling that instead of suggesting for alternatives that could perhaps make the AI less of a "omniscient, quasi-omnipotent eye in the sky" we get this.

Perhaps adding more traitor items or jury-rigged that are able to disable cameras remotely. (Though nobody uses the ones that exist.)

Perhaps a way to make it so that the AI can no longer jump to someone via their ID, somewhat like suit sensors can be turned off.

Maybe even adding in some particular things that could take the attention of an AI along the vein of the random Greytide Trojan event where an AI has to fix malware that has infiltrated systems. (This would be especially useful if they caused cameras in certain areas to malfunction and the AI had to do some manner of "minigame" as it were of bringing them back online that would consume some of it's time and attention.

Inversely an AI being able to do much of the same thing to increase the efficiency of departmental software, making machines run better via the same method would also give the AI a laundry-list of things to do to take distract it.

As it is the AI can sometimes be seen as a somewhat omnipresent annoyance at times due to it often having very little to do itself as an AI other than simply watch and react, giving it proactive tasks would give antags much more wiggle room and be a healthier if more time and resource answer to this rather than whatever this is supposed to achieve than controversy.

**Comment by Caboozles** [comment]
If you think antags wouldn't remove people because there's no AI, you must not play the same game that I do. We have plenty of rounds without sillycones where people still chop chop or murderbone.

**Comment by brndd** [comment]
I can't believe I'm agreeing with utilitas.

**Comment by dsfartgeg** [comment]
> 
> 
> I can't believe I'm agreeing with utilitas.

it's ok the drugs will wear off

**Comment by utilitas-** [comment]
I'll put in a greater dosage next time bby ;)

**Comment by dsfartgeg** [comment]
> If this PR gets too much controversy I'll happily close it down

yeah sure you will.  you make stupid suggestions like these every week and then utilitas magically appears out of the ether to shitpost in the thread for hours at a time and egg on people in the issue itself.

you know this is a stupid idea prima facie and has no chance, but you thrive on the attention and chaos. fuck off.

**Comment by ShiftyRail** [comment]
>you know this is a stupid idea prima facie and has no chance, but you thrive on the attention and chaos. fuck off.

This is not true, and I don't really understand how you could came to that conclusion.
Utilitas is a grown man and I'm not responsible for him nor I would I wish on anyone to be responsible for him.

**Comment by utilitas-** [comment]
how 'bout you quit trying to build up a cult of personality on this Server Ran For an Anonymous Imageboard and instead discuss the issue at hand, buddy ol' pal

**Comment by FudgePucker** [comment]
I dont know how effective it is but the camera jammer item is temporary but still useful. Next time I get traitor I am going to buy as many as possible and bully the AI.

**Comment by ghost** [comment]
Ahhem

Fuck silicoons

Also an idea would be to have the ability to mass-disable cameras. Cultists are able to do this with their confusion rune. Perhaps give the vampire glare the same ability and give the syndicate agents a device to overload cameras in the area silently.

**Comment by FudgePucker** [comment]
I'm pretty sure syndicate agents do have a device to (temporarily) disable cameras in an area, it also disables cameras else where randomly so that they cant use what cameras are disabled to valid you

**Comment by ShiftyRail** [comment]
There is a multitool that goes red if the AI is currently watching you with its cameras, yeah.

**Comment by brndd** [comment]
Add a feature where you can attach a photo of the room to a camera to make it show a static view.

**Comment by ShiftyRail** [comment]
>Add a feature where you can attach a photo of the room to a camera to make it show a static view.

This is a lot more complicated than it looks like. I thought about that, but the free movement AI Eyes have makes it difficult to implement. It is workable for the security computer cameras, but the AI would need a different system.

**Comment by ghost** [comment]
@Myrios has a really good point. AIs are pretty essential parts of a futuristic roleplay setting. So is hacking, yet the only kind of hacking we have involves lawsets and EMPs. An interesting alernative would be if there were more ways to disable cameras for a time, hack the AI specifically, generally make it harder to track people or even a way to generate ion laws without admin intervention.

**Comment by boy2mantwicethefam** [comment]
Get rid of AIs for a while to see how the game would shift as a result, expect more hacking to be done at least and more courageous antags

**Comment by FudgePucker** [comment]
Use goons camera mechanic instead of magic observer.
You use the movement keys to jump from camera to camera.
A system like this would open up other possibilities on nerfs.

**Comment by PJB3005** [comment]
Goon's camera mechanics are absolutely agonizing to play with. AI freelook actually makes the role playable.

**Comment by boy2mantwicethefam** [comment]
I agree, the Goon cameras are just pain and there's no visual indicator about what camera you can jump to

**Comment by utilitas-** [comment]
@FudgePucker 
Ligga that's exactly the reason why we upgraded away from the idiotic camera jumping system _like six years ago._

**Comment by FudgePucker** [comment]
>theres no visual indicator of what camera you can jump to

Huh, almost like you cant just quickly check for disabled cameras by looking for static to look for cult or revs.

It would make the AI less omnipresent and more like a brain stuck in a box.

**Comment by ShiftyRail** [comment]
Not enough support for this, but at least some food for thought.

**Comment by Kammerjunk** [comment]
no I hate leftovers

**Comment by utilitas-** [comment]
that's hard to fuckin' believe

**Comment by Kammerjunk** [comment]
no I really do

**Comment by utilitas-** [comment]
the wrapping paper doesn't count as leftovers

**Comment by DamianX** [comment]
This is a shitpost.

**Comment by plosky1** [comment]
> AIs are absolute shit because of administration, not because of code. It's because you fuckers completely forgot about the basic tenet of SS13: absolute chaos. By restricting AIs with thousands of unspoken rules, you shit not only on the AIs but also on the game itself. It's not just unspoken rules concerning AIs, but it's the most visible part because there has always been the rules you actually get versus the rules you should actually follow (as ASIMOV) and it's fucking stupid.
> 
> Remove all the rules, make the server great again. I know you won't.

I can't believe it, but I'm agreeing with Utilitas here.

**Comment by utilitas-** [comment]
fuck off plosky

**Pull request closed without merging**
