### PR TITLE
Adds /obj/mecha to quick create menu

### PR DESCRIPTION
**Pull request by Sprok0**
To spawn mechs for testing or something, you'd need to load all /obj which freezes the client for like a minute. This adds /obj/mecha to the quick create menu.

### CODE REVIEW

**Comment by clusterfack** [comment]
Oh no, you don't actually use this do you?

**Comment by Sprok0** [comment]
How else can you do dumb things like this
bagphazon

**Comment by Aurx** [comment]
Use the spawn verb with a partial typepath.  
spawn "obj/mecha/whatevershititisyouwantedman"
Then varedit it into the bodybag's contents.  Infinitely less hassle then waiting for the loading.

**Comment by Sprok0** [comment]
putting it in the quick create menu cuts out all the loading though

**Comment by Aurx** [comment]
Spawn verb has near zero loading though.  
I mean, it's a good thing to do, but you're going about spawning things ass-on-assistant'shead backwards.

**Comment by Exxion** [comment]
Yeah the spawn verb is just a better version of this

**Comment by clusterfack** [comment]
We need to look at changing this menu completely to be honest, I'm 90% sure it can be made to not lag at ALL.

**Pull request merged**
