### PR TITLE
Bar Sign - Paddy's Pub

### PR DESCRIPTION
**Pull request by PlausibleDeniability**
paddyspub

Preview, complete with ocular patdown
7w8lg56j7l

[sprites]
[tested]

:cl:
 * rscadd: An old earth bar sign has been found in storage - Paddy's Pub

### CODE REVIEW

**Comment by Eneocho** [comment]
EGG

**Comment by jknpj** [comment]
Daddy's

**Comment by Kharkov72** [comment]
Aseprite_baCq2skYLv

**Review by Kurfursten — CHANGES_REQUESTED** [review]
For reasons I can't explain, this PR isn't showing conflicts that it should detect.

What I need you to do is this
* Download our current icons/barsigns.dmi here: https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/icons/barsigns.dmi
* Copy over these 4 icons: limbo, theclownshead, thesaucyclown, thedamnwall
* Update the icons in your PR's dmi

Once you've done this I will merge it

**Comment by ShiftyRail** [comment]
```
0 icons/obj/barsigns.dmi
Viewed
Empty file.
```

Right now, the PR would just destroy the bar signs dmi.

**Comment by Kurfursten** [comment]
Doesn't look empty on my end

**Comment by ghost** [comment]
its smug aura mocks me

**Comment by Kurfursten** [comment]
It has been a month, let me know if you need help with what I asked

**Comment by Kurfursten** [comment]
Let us know if you ever decide to revisit this and it will be reopened

**Pull request closed without merging**
