### PR TITLE
Non-Cult + Wizard Constructs

### PR DESCRIPTION
**Pull request by gurfan**
Inspired by #26240

Constructs created by non-cultists, or shades created by wizards, will get a unique color and glow. These constructs will also not speak the cult language.

Skeleton Lab Phi 2020-08-07 214013
Skeleton Lab Phi 2020-08-07 214034

Let me know if you think the colors need tweaking.

Constructs created by wizards are purple. Constructs created by non-cultists are blue. If a wizard happens to be a cultist then the construct will be in the usual red color. 

This PR doesn't touch perfect-type constructs. If a soul gem (not a shard) is used to create a construct, they'll always have the red appearance and speak the cult language, regardless of whether or not the person creating them is a cultist.

While making this I found unused animations for the creation of perfect-type constructs (see below). When these constructs are created the animation will now play.

makeartificer
makejug
makewraith

[sprites]

:cl:
 * rscadd: Constructs created by non-cultists will now have a bluer appearance to them.
 * rscadd: Constructs created by wizards will now have a purple-r appearance to them.
 * tweak: Added an unused animation for when a construct is made using a soul gem.

### CODE REVIEW

**Comment by Viciousaurus** [comment]
> Inspired by #26420

Are you sure that's the right number?

**Comment by gurfan** [comment]
fixed, oops. Meant to be #26240

**Comment by SonixApache** [comment]
recommend using `imageadd` in the :cl: instead of `rscadd`.

**Comment by gurfan** [comment]
I have thought of a better way to implement this

**Comment by SonixApache** [comment]
Why not just do it on the same branch...?

**Pull request closed without merging**
