### PR TITLE
red suit and hat

### PR DESCRIPTION
**Pull request by RealestEstate**
-adds a red suit and wide-brimmed red feathered hat to autodrobe.

callthis#now

-also adds ponchos to the autodrobe, of which sprites have existed in the code but never had any code for it.
-also fixes paper bags on head being off by a pixel.
[sprites]

:cl:
 * rscadd: Autodrobe now dispenses a red suit and hat
 * rscadd: Autodrobe also now dispenses a poncho

### CODE REVIEW

**Comment by Irradiation** [comment]
oy vey, ids our suit but in red

**Comment by RealestEstate** [comment]
soot

**Comment by Irradiation** [comment]
DELET

**Comment by SirSkeleto** [comment]
we live in a society

**Comment by agentofzog2** [comment]
From what I remember the librarian has a "red suit" jumpsuit (not the red jumpsuit found in the suitlord)

Still I think this should be a contraband/premium item for the suitlord so you don't have to break into the clown's office for the epic nuke ops prank.

**Comment by RealestEstate** [comment]
@agentofzog2  suitlord premiums, 1 per each vending machine depending on type.

**Pull request merged**
