### PR TITLE
Orderable replacement spacesuits for vox, plasmamen, and greys

### PR DESCRIPTION
**Pull request by ghost**
Adds a spacesuit that should only be wearable by greys. (Sprites courtesy of Niggly)

Spacegrey

Also adds supply crates to cargo that provide internals and spare assistant space suits for Vox, Plasmamen, and Greys (Not that they need spare internals, but it's a way to get the grey spacesuit in)

I've put the cost at 100 credits in case of balance issues, unless there's enough of an argument as to why they should either be cheaper or more expensive.

Grey spacesuits can't use large oxygen tanks in the exosuit slot, only emergency-sized tanks and flashlights, so you'd have to sacrifice your backpack slot if you wanted to go spacewalking with a decent-sized tank, or just get a better spacesuit.

### CODE REVIEW

**Comment by CptWad** [comment]
:+1: 
better make sure that ordering the crates dont break the console and shuttle and shit though
how many suits per crate?

**Comment by ghost** [comment]
@CptWad They shouldn't break anything, I've tested them all thoroughly, and it's 1 suit set per crate, along with internals and mask.

**Comment by Ephx1** [comment]
I'm a bit curious as to why Greys need specific hardsuits if they can already wear any other.
Neat nonetheless though.

**Comment by ghost** [comment]
@Ephx1 I was just gonna do the plasmaman crate at first because some shitter sprayed down I think sawbones over some petty shit and he had to get adminbus to get him a new helmet, then remembered how much of a pain it was to get more N2 as a vox so added that in, then remembered Niggly's jetsons bus a while ago and asked them for some of the sprites to give greys something.

**Comment by Shadowmech88** [comment]
But why do greys NEED a specific thing? They can already wear normal hardsuits.
If you want to add the suit to Cargo then do so, but I don't think you need to make it grey-specific.

**Comment by CptWad** [comment]
Greys are incredibly boring. Giving them a funny spacesuit gives them purpose in their shitty existence.

**Comment by Kurfursten** [comment]
I still think humans should be able to wear plasmaman suits. I want to impersonate a plasmaman after killing him.

**Comment by Ephx1** [comment]
Logically they should, plasmamen are purple skeletons. Skeletons from humans.

**Comment by 9600bauds** [comment]
Obviously the inner plasmaman suit linings are skeleton-shaped.

**Comment by Ephx1** [comment]
Uh, what shape would a human be, other than skeleton shaped?

**Comment by CptWad** [comment]
though a suit should exist that has a 50-50 chance of turning you into a plasman if you die in a plasma fire in said suit

**Comment by 9600bauds** [comment]
Humans are skeleton and muscle shaped

**Comment by ghost** [comment]
Skeletons are notoriously skinnier than humans.

**Comment by Imagebard** [comment]
Just let the greys have their hardsuit, man.

**Comment by ghost** [comment]
There's a few reasons why it would be a bad idea to wear a plasmamans suit when not a plasmaman
1. It's built around and for a skeleton, not something with flesh on it, you'd have to lose a fair few pounds or be wearing the contortionists jumpsuit

2.The things laced with plasma and is basically a contained plasma environment to stop plasmamen from burning, not good for the skin of those who are "allergic" to plasma

**Comment by Kurfursten** [comment]
Those are just rationalizations for the status quo though. It's not really an immersion factor in either direction (for or against) - we don't really have any set space suit lore (or lore at all). Decide based on whether it would be fun to masquerade as a plasmaman.

**Comment by Shadowmech88** [comment]
> The things laced with plasma and is basically a contained plasma environment to stop plasmamen from burning, not good for the skin of those who are "allergic" to plasma

I'm pretty sure the suit is just airtight.
All that's necessary for a plasmaman to not burst into flames is for there to be no oxygen in its environment.

@Kurfursten 
One issue that we'd run into; if humans could wear plasmaman suits then you'd have humans murdering plasmamen just for the free space suit.

**Comment by ghost** [comment]
So, what needs sorting with this to get it merged?

**Comment by ghost** [comment]
@shadowmech88
Airtight with what gas inside of it?

**Comment by Shadowmech88** [comment]
@DrCelt 
My guess would be N2, since it's non-reactive.

**Comment by ghost** [comment]
Day 3 in no-merge.

Heck, might start adding stuff to the PR, there's a lot of sprites in this grey.dmi that Niggly passed me.

**Comment by SonixApache** [comment]
:+1:

**Comment by Imagebard** [comment]
:+1:

**Pull request merged**
