### PR TITLE
Revert "Round no longer ends on wizard death"

### PR DESCRIPTION
**Pull request by carshalash**
I've honestly yet to see a single person that has enjoyed this change.

### CODE REVIEW

**Comment by Wizbing** [comment]
If an admin isn't on, or just doesn't care a wizard dying it just turns the round type into extended.

Especially with shitty wizards, this blows.

**Comment by kol1th** [comment]
Memes aside, it's quite literally extended after a wizard dies unless they summon guns or magic.

**Comment by SonixApache** [comment]
just combine wiz with vampuling

**Comment by carshalash** [comment]
Im not even memeing for once, this original change was put in by someone who doesn't even play the game anymore. At least with extended you have the fun and fear of wondering who is going to be the first to backstab you and be the antag after all. This is just making it so that if wizzy goes and fireballs himself at escape that we have to wait until an admin buses something or not.

**Comment by Shadowmech88** [comment]
I don't mind extended in and of itself, but it only works if people don't _know_ it's extended. Otherwise half the crew immediately loses their will to live and the other half spend all round doing their own autism projects instead of interacting.

**Comment by Exxion** [comment]
Basically fuck the whole gamemode system and tensioner when

**Comment by Arthurdentist** [comment]
A better solution is to add more interesting and varied events.

Round ending on wizard death was always retarded and dumb and it very much lead too:
1. Oh shit its a wizard
2. Blow up the Wizard cuz round end :^) (Its okay if I blow a 9 Dev hole in the bridge because the round will end!)
3. Did the round end? (Y/N)

If (Y) well done Valids Secured
If (N) Oh shit its ragin' mages!!! Time to prepare for more valids

**Comment by Exxion** [comment]
Yes, that would be the tensioner
Or rather the tensioner would be an example of that

**Comment by Arthurdentist** [comment]
Then the tensioner is the solution, not a return to the system that was previously implemented.

**Comment by Exxion** [comment]
Everyone would love the tensioner
Problem is that someone has to actually finish antag datums first

**Comment by ghost** [comment]
@JustSumBody

**Comment by Shadowmech88** [comment]
> antag datums

image

**Comment by Megamaw** [comment]
as someone who actually plays the game?

reverting this punishes stealth wizards. validhunters know exactly when they've killed the wizard b/c the round ends then and there.

paranoia of 'did we kill the wizard or is he still around???' is fucking incredible as someone who loves playing as wizard and this change wouldnt be fun except for validhunters that want to antag reroll faster.

**Comment by PJB3005** [comment]
Yeah. I remember a wizard round that was a complete clusterfuck mind swap wise. Took forever for the wizard to be killed (if he even was killed and didn't just disguise)

**Comment by FudgePucker** [comment]
I would prefer extended over 'woops wizard fireballed himself, time to wait an eternity for the server to reset, also next round is also wizard :^)'.

WOW I CAN'T GET VALIDS OR GET ANOTHER ANTAG ROLL? FUCK THSI SHITY FUGIN GAMMODE CHANG.

A better solution is changing the round to auto traitor when the only wizard dies. An admin not being on is a server error not a coding error. Also if it is that low pop that an admin isn't on, then why the hell would you want anything but extended? Nothing is more fun than low pop murder boner when one guy goes around ebowing eswording all four players to death!

**Comment by Megamaw** [comment]
@PJB3005 the one where they 'cornered' the wizzy in robotics and he kept mindswapping everyone?

lmao, that was me. good times.

**Comment by kol1th** [comment]
@FudgePucker Yeah but that requires someone to _code_ it. Which will most likely not happen

**Comment by Exxion** [comment]
What he described wouldn't be THAT hard to code, really. Making specifically wizard revert to autotraitor once the wizard dies? That's doable.
But that's pretty much a really watered-down version of the tensioner, and, again, to make THAT requires that someone finish antag datums. Which isn't really HARD so much as it is very tedious. But that hasn't stopped it from not getting done.

**Comment by kol1th** [comment]
You're delusional if you think someone will do antag datums any time soon T B H

**Comment by Exxion** [comment]
Who said I thought they would?

**Comment by PJB3005** [comment]
@Megamaw it was.

@Exxion no it wouldn't really require the antag Datums, just quickly hack it in. Code can't get any worse than it is right now anyways.

**Comment by Exxion** [comment]
It would require antag datums to do it _properly_

> Code can't get any worse than it is right now anyways.

But it _has_ been worse

**Comment by Shadowmech88** [comment]
> just quickly hack it in. Code can't get any worse than it is right now anyways.

I'm sure this logic was used to justify quite a lot of what is now oldcode back when it was added.

**Comment by SonixApache** [comment]
just merge bay over vgstation, it'll be fine

**Comment by PJB3005** [comment]
Literally all of gamemode code needs to be rewritten from scratch. There's nothing that's lost by writing shitcode in it.

**Comment by Intigracy** [comment]
Doesn't even need to be autotraitor.

You could just have it run the proc that selects from the secret lineup and pick a new gamemode/run the gamemode's startup code.

**Comment by Arthurdentist** [comment]
The emojiocracy has spoken

**Comment by optimumtact** [comment]
ha ha ha tensioner ha ha ha

we tried that

**Comment by Exxion** [comment]
Leave this place, fruitfucker

**Comment by optimumtact** [comment]
What possibly leads you to the conclusion I fuck fruit

**Comment by ComicIronic** [comment]
People with anime girl pictures want to fuck anime girls => people with fruit pictures want to fuck fruit.

**Pull request closed without merging**
