### PR TITLE
Baseball bat updates, sans new types

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][tweak]

## What this does
redo of #33571 with lesser scope and just the improvements to baseball bats themselves.
- allows baseball bats to hit away items in the other hand in throw mode
- allows baseball bats to hit away items on the floor in throw mode
- spiked bats are no longer totally useless at hitting or blocking but their chance and ability is greatly reduced
- wirecutters can now remove the nail from spiked bats

## Why it's good
more fun uses for this item

## Changelog
:cl:
 * rscadd: Baseball bats can now hit away items in the other user's hand or the ground.
 * rscadd: Baseball bats can now have their nail removed with wirecutters.
 * rscadd: Spiked bats now have a very small chance to hit anything instead of none, with limited effect.

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
i remember tg/bee baseball bats, those things were the shit

**Comment by PrimeDSS13** [comment]
wouldn't a crowbar make more sense than a wirecutter

**Comment by dinnerwoerror** [comment]
yea but youre cutting out the nails, not taking them out and leaving a bunch of holes in the bat that would weaken the integrity

**Comment by PrimeDSS13** [comment]
I suppose but it feels less intuitive

**Pull request merged**
