### PR TITLE
Taxichanges

### LINKED ISSUE #7062: Typo on Taxi
(WEB REPORT BY: senaat1 REMOTE: 158.69.55.2:7777)
Revision: 644acd3fcda003588b11e434f2574f51644671f6 

When using the Security Cameras console thing, Chemistry is misspelled as Chemestry

### PR DESCRIPTION
**Pull request by xpcybic**
A slew of redesigns and fixes to Taxistation. Among the most notable:
-Made the taxi docks U-shaped, so that each has two entrances
-Expanded head and QM offices a small amount
-Enlarged engicargo station (cargo/bar/kitchen/hydro/dorms) and redesigned theater backroom
-Tweaked brig, flipped courtroom
-Enlarged toxins and xenobio, added borer egg setup
-Added overflow surgery
-Added actual xenobotany equipment to research station
This probably needs some playtesting, and maybe someone else to look over it because I'm shit.

Fixes #7062, #7063, #7400, #7393, #7105, #7399, #7414
Addresses #4645, #7375, #6845, #7388

edit: MOOOOOM GET THE CAMERAAAAA

screenshot 2016-01-03 12 18 41
screenshot 2016-01-03 12 18 51
screenshot 2016-01-03 12 19 05
screenshot 2016-01-03 12 25 08
screenshot 2016-01-03 12 25 29

### CODE REVIEW

**Comment by ghost** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by CptWad** [comment]
n o i c e

**Comment by ihadtoregisterforthis** [comment]
Pics or didn't happen

**Comment by Kurfursten** [comment]
Dire need of pictures, but good work, especially on the dock thing - it was something I planned to do myself

**Comment by Kurfursten** [comment]
I notice that it is now actually impossible to walk through maint without moving two reagent tanks near the theater. That seems problematic.

**Comment by ihadtoregisterforthis** [comment]
And in the same maint there's a floating light fixture.

I'm not too sure how badly is a surgery overflow needed.

**Comment by clusterfack** [comment]
*2016
people still play taxi*

**Comment by Kurfursten** [comment]
W H A T

@clusterfack How did this get merged?! Floating lights and maint blocked!

**Comment by clusterfack** [comment]
How? No indication in the PR of it not being ready and people bugging me in IRC to merge it

**Comment by Kurfursten** [comment]
What about the last two comments?

No one could see pictures before my comment about the reagent tanks. Of course he's not going to say "don't merge my half-assed map change PR" in the OP.

**Comment by Kurfursten** [comment]
Also FUCK, it completely breaks the mail! Sorting junctions are broken in four places. Near theater, near HOP, near atmos back entrance, and in front of botany.

**Comment by ihadtoregisterforthis** [comment]
The circuitboard secure storage looks awkward too

**Comment by Kurfursten** [comment]
Good catch. That's more than awkward, that's inaccessible.

Also there are no external airlocks on that taxi anymore except for the ones that are engineering or cargo restricted. At all. Someone who gets External Airlocks access from the HOP to explore space simply can't exit or enter space from this Taxi anymore.

**Comment by clusterfack** [comment]
Do you think I read every comment in every PR and then carefully check to see if its someone asking for a fix and seeing if someone fixed it? If someone tells me to merge something I'm going to assume they already did that.

**Comment by Zth--** [comment]
This map full of sand/snow when?

**Comment by Kurfursten** [comment]
@clusterfack But the person who told you to merge it wasn't even the guy who posted it. He wasn't ready for it to be merged upon questioning in IRC. The guy who asked you to merge it was Celt (and he's not getting off without being harangued either).

And yeah, I know it sucks as a job as a maintainer/collaborator to troll through comments, but that's really all you have to go on for a map PR: you don't have code to look at. You have a better track record than this, I know you used to be as zealous as Comic in reading the code of every PR. Reading down to the 5th comment on github isn't too much to ask when there's no code reading involved.

It's not all on you for blame, but a little scrutiny would be nice, especially on someone's first major PR.

**Comment by clusterfack** [comment]
Fuck off kurfurst

**Pull request merged**
