### PR TITLE
Vault: Mothership Lab Renovations

### PR DESCRIPTION
**Pull request by Optimism333**
## Regularly Scheduled Lab Maintenance ##
I figured that even though the Valkor away mission temporarily fell through, I could use some of the tiling, furniture, and other content to buff up the ayy aesthetic of the mothership lab vault.

I also updated the layout of a few rooms throughout the vault and added a new one to the entry level based on feedback.

## Main Changes ##

- ### Nu ayy themed lockers, crates, chairs, and beds ### 

ayy_closets_crates
ayy_furniture

- ### Nu ayy-themed floors and walls ### 
ayy_floor1
ayy_floor2
ayy_wallz

- ### Footstep sounds when a land-based mob moves across most turfs ### 
Added some footstep sounds from Xcom Ufo Defense, that have a 33% chance to play when a land-based mob moves over the vault's turfs. Hopefully makes things a bit more atmospheric! And a good way to tell if hostile mobs are nearby.

https://github.com/vgstation-coders/vgstation13/assets/81007356/c13f5deb-af6e-4426-aef1-fd06d6d33534

https://github.com/vgstation-coders/vgstation13/assets/81007356/ac910d4d-b82d-4b90-8575-a2b9556050a2

https://github.com/vgstation-coders/vgstation13/assets/81007356/ba9d5fca-8b41-422f-bd23-bbe5a8540b5f

- ### Resprited ayy-drones ### 
I'd wanted to have the sprites for these redone for a while. Old is on the left, new is on the right. (Video example included)
ayy_drone_resprite

https://github.com/vgstation-coders/vgstation13/assets/81007356/d9238e17-c842-43e3-90e1-f7ab494def28

- ### Resprited ayy-ids with more visible color and lil' ayy faces (Thanks Blithering!) ###
Old is on the left, new is on the right.
ayy_id_resprite

- ### Doors are color-coded to match their needed access. ###
Tourist ayy-id will open white and unmarked doors, red ayy-id will open red security doors, yellow will open yellow engineering doors, green ayy-id will open white and green doors, leader ayy-id will open everything including vault and command doors. Hopefully this makes it easier to navigate the vault's access restrictions. (One day I want to replace the placeholder doors with ayy-themed airlocks, but this should work well enough for now)

### Nu Entry Level ###

**Noteable Changes**
- New mining explosives shed close to the front door, lightly guarded
- Slightly rearranged control room entrance

### Nu Habitation Deck ###

**Noteable Changes**
- Lab xenoflora bay has been spruced up with new soil floor under the hydro trays
- Added a new storage room to the maint area
- Old lab maint has more tiling
- Raider tunnel now has footstep sounds

### Nu Research Deck ###

**Noteable Changes**
- Lab petting zoo has been spruced up with new soil floor and a little sizzling puddle for Phyl to get his hydration
- Slightly improved the layout of the MDF armory
- Laborer quarters has more tiling

### In-Game Preview Screenshots ###
Capture4
Capture5
Capture6
Capture7
Capture8
Capture9
Capture10

[content] [vault] [sprites]

:cl:
 * rscadd: mothership lab vault: New ayy-themed furniture and decor has been added
 * rscadd: mothership lab vault: New ayy-themed floors and walls have been added
 * rscadd: mothership lab vault: Some rooms have had their layouts improved or been better decorated
 * rscadd: mothership lab vault: New mining explosives shed added to the entry level
 * rscadd: mothership lab vault: hoverdisc drone and saucer drone sprites have been updated
 * rscadd: mothership lab vault: ayy ID sprites have been updated
 * rscadd: mothership lab vault: added footstep sounds for most turfs in the vault

### CODE REVIEW

**Comment by SonixApache** [comment]
recommend reformat :cl: as
+ rscadd: mothership lab vault: blablabla

to avoid confusion

great work :+1: :+1: :+1:

**Comment by Eneocho** [comment]
looking good

**Comment by Optimism333** [comment]
I added some footstep sounds from Xcom Ufo Defense, that have a 33% chance to play when a land-based mob moves over an alien alloy floor tile. Hopefully makes things a bit atmospheric! And a good way to tell if hostile mobs are nearby.

https://github.com/vgstation-coders/vgstation13/assets/81007356/03197a49-350f-4873-85db-bb01db08adb7

**Comment by Optimism333** [comment]
Added one more type of footstep sound to the ayy soil patches.

https://github.com/vgstation-coders/vgstation13/assets/81007356/0384c624-6a06-4c85-9404-386e25c4f8e7

**Comment by nervere** [comment]
Please save the maps you modified in TGM format and re-commit them. If you're using StrongDMM, it's File > Preferences > Save Format > Set to TGM.

**Comment by Optimism333** [comment]
> Please save the maps you modified in TGM format and re-commit them. If you're using StrongDMM, it's File > Preferences > Save Format > Set to TGM.

Thanks for checking. Did the thing.

**Comment by Optimism333** [comment]
Added footstep sounds to the raider tunnel on the habitation deck level, so players can hear the vox skulking about. Will probably leave it there for now.

Did some other misc improvements: 
- Added floor tiles under some doors that only had generic plating
- Anchored the raider stew cauldron on the campfire
- Rearranged the lab control room entrance and added two railings. Fancy!

**Comment by Optimism333** [comment]
Should be done with everything. Will wait for review.

Edit: The end is never

**Comment by agentofzog2** [comment]
Finally, someone else who thought it was cool how Alien Bases in X-Com included strange alien gardens.
I like the old cyberdisk design better though.
Also as someone who got far enough (on the third credit) I wish more stuff was secured in lockers in those areas with pacid grenadiers.

**Comment by Eneocho** [comment]
Could you add the ayy tiles to the tile painter? They look great!

**Comment by Optimism333** [comment]
> Also as someone who got far enough (on the third credit) I wish more stuff was secured in lockers in those areas with pacid grenadiers.

Could you point out on one of the map screenshots where you think more stuff should be secured? Maybe I can shift some items into storage.

> Could you add the ayy tiles to the tile painter? They look great!

I might consider putting that up in a pr after this one goes through, if it's something players want.

**Comment by Optimism333** [comment]
Decided I might as well update the hobo home as well. I liked the idea that it was an abandoned mining barracks that wasn't being used by the lab anymore, and they just moved in. Now it looks more the part.

image

image

Screenshots in the top post have also been updated.

**Comment by Eneocho** [comment]
Damn those look good, but the airlocks really clash with the aesthetic (and to a lesser extent, the rock walls too, could replace the generic red rocks with purple or blue ones)

**Comment by Optimism333** [comment]
> Damn those look good, but the airlocks really clash with the aesthetic

There's not much I can do about that for the time being unfortunately. If I had the assets, I'd use ayy-themed airlocks with color-coded stripes to indicate what security clearance is necessary. But I don't at the moment, so I'm doing the best I can with the following system:

White/Grey Unmarked Airlocks = Can be opened with tourist ID
Yellow Engineering = laborer ID
Red MDF = MDF ID
White and Green (Medical) = Research ID
Command/Vault = Leader ID

If I do get the assets in the future, whether from a helpful spriter or by making them myself, I will replace them.

Glad you at least like the look overall.

**Comment by Optimism333** [comment]
Slightly improved the layout of the Administrator's bedroom. Aimed to make it more of a cozy bedroom, a little less of a cramped closet.

image

Added a jukebox to the bar on the habitation deck, and changed the positions of the light tiles to be under the tables. I think that looks better.

image

**Comment by Optimism333** [comment]
Finally, finished adding footstep sounds to most of the remaining tiles.

https://github.com/vgstation-coders/vgstation13/assets/81007356/ba9d5fca-8b41-422f-bd23-bbe5a8540b5f

**Comment by agentofzog2** [comment]
> > Also as someone who got far enough (on the third credit) I wish more stuff was secured in lockers in those areas with pacid grenadiers.
> 
> Could you point out on one of the map screenshots where you think more stuff should be secured? Maybe I can shift some items into storage.

Been a while since I got that far but the RnD lab and the bridge with the final boss was where I remember noting the greatest number of piles of melted goo after I cleared them.

**Comment by Optimism333** [comment]
> > > Also as someone who got far enough (on the third credit) I wish more stuff was secured in lockers in those areas with pacid grenadiers.
> > 
> > 
> > Could you point out on one of the map screenshots where you think more stuff should be secured? Maybe I can shift some items into storage.
> 
> Been a while since I got that far but the RnD lab and the bridge with the final boss was where I remember noting the greatest number of piles of melted goo after I cleared them.

RnD lab should be resolved, since there's no grenadiers in that area and I've locked off the doors so the grenadier doesn't retreat back there.

The bridge might be a bit tougher to change, but I'll have a think and see what I can do.

**Comment by Optimism333** [comment]
> > > Also as someone who got far enough (on the third credit) I wish more stuff was secured in lockers in those areas with pacid grenadiers.
> > 
> > 
> > Could you point out on one of the map screenshots where you think more stuff should be secured? Maybe I can shift some items into storage.
> 
> Been a while since I got that far but the RnD lab and the bridge with the final boss was where I remember noting the greatest number of piles of melted goo after I cleared them.

Alright, I've shifted some of the more valuable items into storage areas with secure plasmaglass windoors. Hopefully that helps mitigate all the items in the control room getting melted.

image

**Comment by Eneocho** [comment]
Can you make a PR adding the ayy floors to the tile painter, please?

**Pull request merged**
