### PR TITLE
Changes save loading to stop at 5 tries instead of 100

### LINKED ISSUE #9796: Spam When Trying to Load a Character Save that Isn't There

### PR DESCRIPTION
**Pull request by Intigracy**
closes #9796

I still have no idea why he had preferences to load but no save slot.

### CODE REVIEW

**Comment by PJB3005** [comment]
[Band-aid] tag when?

**Comment by Intigracy** [comment]
IDK what's wrong with his local repo that that happened, but I literally just downloaded a zipped copy of the repo, compiled it, started it up, and it generated/saved me a character correctly.

The only way I could see this happening is if you're connecting to a server for the very first time and quit after it creates you preferences, then rejoin and suddenly it loads the prefs and has no save slot to load.

**Comment by Intigracy** [comment]
Not really a bandaid, it needs lowering since it's been established it loads after the first try or two. No reason to wait 100 seconds.

**Comment by Imagebard** [comment]
@PJB3005 That's more something you would add in the code as comments (//Band Aid fix), not a tag for Issues.

**Comment by ghost** [comment]
I had a very painful run of this on a local server this morning. 100 times this shit before I can load in, because I can't use Setup Character when it's going on either, is not really quality

**Pull request merged**
