### PR TITLE
"THE TRAITOR THEY KILL PEOPLE": New Brain Damage Line

### PR DESCRIPTION
**Pull request by Optimism333**
## BUT I RESPAWN ##
- This is a bite size pr I've wanted to throw out there for the git crowd for a while. Finally got around to it.
- Is this line up to snuff to be added to the server's brain damage lines? Please do discuss.

### "TEH TRAITOR THEY KILL PEEPLE BUT I RESPAWN!!!" ###

[content]

:cl:
 * rscadd: A new brain damage line has been added

### CODE REVIEW

**Comment by jwhitak** [comment]
Memes must survive a year before being merged, though that's basically old policy at this point. Still looking forward to brain damage causing difficulties BREETing...

Though it has technically been 8 months...

**Comment by smalIboss** [comment]
funny even without context

**Comment by nervere** [comment]
The difference between this brain damage line and the rest is that it's spelled correctly and coherently. In my opinion, you should distort the message somewhat to this effect so it seems more like genuine stupidity rather than a vomited out OOC joke.

**Comment by Optimism333** [comment]
> The difference between this brain damage line and the rest is that it's spelled correctly and coherently. In my opinion, you should distort the message somewhat to this effect so it seems more like genuine stupidity rather than a vomited out OOC joke.

Personally I'd rather keep the line as true to the original as possible, but I'll consider minor alterations. Could you give me an example of how you'd write it?

**Comment by nervere** [comment]
Honestly, it's hard to modify it much but this (in my personal opinion) is what I had in mind by my previous comment:
`TEH TRAITER TEHEY KILL PEOple BUT I RESPAWN!!!`

Same general idea, but the person getting forced to say this line sounds even more stupid and much less coherent.
The natural speech stuttering and yelling you get with brain damage will probably make either version sound fine tbh.

**Comment by Optimism333** [comment]
> Honestly, it's hard to modify it much but this (in my personal opinion) is what I had in mind by my previous comment: `TEH TRAITER TEHEY KILL PEOple BUT I RESPAWN!!!`
> 
> Same general idea, but the person getting forced to say this line sounds even more stupid and much less coherent. The natural speech stuttering and yelling you get with brain damage will probably make either version sound fine tbh.

I distorted it just a little bit, top post has been updated.

**Comment by nervere** [comment]
Perfect!

**Pull request merged**
