### PR TITLE
Transit tube updates

### PR DESCRIPTION
**Pull request by adacovsk**
[bugfix]

Working on some fixes for the transit tubes, building on what @kane-f has done, using some old tg code to fix the issues. Issues:
- transit_tube.dm is about 1000 lines long and can be split into multiple files to make it more manageable.
- tubes block your path
- annoying messages when interacting with the tubes
- Bumped just doesn't work for getting into tube
- slow at station or immovable pod

Fixes:
- Divided up the code into something more readable
- Removed messages when you move into or past the tubes
- Drag-click to enter tube pod for you or someone/something else
- Using reverse flag on stations instead of complicated "looking-ahead"
- Dump items from pods by clicking instead of freezing pod and station indefinitely
- fast at station

:cl:
 * bugfix: some transit tube fixes

### CODE REVIEW

**Comment by Eneocho** [comment]
The transit tube on line did not have a cap on the departures side so it went once and just popped out. 
Also, consider adding more pathways between the northern and southern sides of line's hallway, since a few are used by the tubes' loading ports.

**Comment by Eneocho** [comment]
The support beams stopping you from moving perpendicularly through tiles with tube pieces just rubs me wrong. Is it possible to remove that? There surely is enough space between the beams for a spessman to squeeze through.

**Comment by adacovsk** [comment]
I don't think caps exist, and yes, not moving perpendicular through the tube also bothers me

**Comment by Eneocho** [comment]
There are no caps apparently, but a window or something works as one, look at the scientist outpost on box, the tube does not loop, instead having a "station" in the corners with windows stopping the tube.

**Review by Kurfursten — CHANGES_REQUESTED** [review]
the diff on xoq means it didn't get cleaned right, do that one again

**Comment by adacovsk** [comment]
> the diff on xoq means it didn't get cleaned right, do that one again

xoq doesn't like when I sanitize the variables. Is this an issue?

**Comment by Kurfursten** [comment]
Looks better

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
