### PR TITLE
Adds a random cyborg upgrade to the jewvend's premium list.

### PR DESCRIPTION
**Pull request by jknpj**
The magnetic gripper is blacklisted for obvious reasons.

:cl:
 * rscadd: Added a chance to get a random cyborg upgrade(minus the magnetic gripper) as premium item in the Vox Supply.

### CODE REVIEW

**Comment by iFlashYou** [comment]
No magnetic gripper?
dropped

**Comment by Durgen** [comment]
this is the perfect sort of item for the tradervend

**Comment by Kurfursten** [comment]
I'm commenting on this so that I know when it goes through. I've got another item I'd like to PR onto the list, but I don't want to make you go out of scope/nonatomic.

**Comment by PJB3005** [comment]
@jknpj Conflicts.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
