### PR TITLE
New hologram for AI

### PR DESCRIPTION
**Pull request by Blithering**
Adds a hologram corgi option for AI. 
holocorgi
:cl: 
 * rscadd: AI can now have a corgi hologram

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by Riekland** [comment]
I feel like the colours are too bright but that might be me being retarded
Does this get a transluscent effect in game? If so that would probably explain why it's so bright to me

**Comment by Blithering** [comment]
It's using the same colour palette as the other holograms, so in game it should look the same, just corgi-shaped.

**Comment by NigglyWiggly** [comment]
BLITHERING YOU DORK.

YOU FORGOT TO MAKE IT TRANSPA

Oh wait that's weird, none of them are at all transparent. I guess it just turns up the Alpha on the icons when they appear ingame?

**Comment by Blithering** [comment]
Yeah, I thought that was weird when I was making it, but if the rest are made that way, who am I to argue?

**Pull request merged**
