### PR TITLE
Shower tweaks: Ghetto Cryo Edition

### PR DESCRIPTION
**Pull request by Kharkov72**
Changes:
Showers now change your temperature by 1 degree a second instead of .5 because that is fucking slow.
The minimum for cold showers is now -200 C because we are in fucking space and because ghetto cryo is fun.

Fixes:
When the shower panel was unscrewed, that was when you unanchored it.
When it was screwed, this is when you changed the temperature.
This felt fucking backwards so I flipped it.

Why?
Partially because it was a request, partially because I think putting someone under a shower for their cryo healing is exactly what medbay needs.
But this got removed before, you say? Well, before your temperature changed 50 degrees a second so I don't think that'll be too much of a fucking problem.
Why not buff the heat as well?
Well, it's space. Stuff gets cold easy, hot less easy.

:cl:
 * rscadd: The Showers, They Heal!

### CODE REVIEW

**Comment by DrSnips** [comment]
While this is a funny haha thing I'm not sure if I want to be frozen as soon as I get put under a shower.

**Comment by kernikov** [comment]
Then don't go under the shower.

**Comment by DrSnips** [comment]
I mean when the clown puts them in the hall and puts people under them.

**Comment by jknpj** [comment]
>The minimum for cold showers is now -200 C 

>liquid water
>-200 C

What?

**Comment by Kharkov72** [comment]
It's the same reason why we have no water lines yet when you bolt the shower it just works:
_Magic_

**Comment by ghost** [comment]
https://en.wikipedia.org/wiki/Supercooling
obviously when wrenching the shower head the pressure is changed allowing for the water to super cool

**Comment by Exxion** [comment]
I don't know a *ton* about phase stuff but I'm pretty sure the coldest you can get something even theoretically before it freezes is its glass transition temperature, which is -137C for water, but practically you can't really get it below -30C
But this would be *so* far from the least realistic thing in the game

**Comment by bathosbathtime** [comment]
The simple solution is that changing the temperature also changes the reagent that comes out.
Finally, greys can safely shower under liquid nitrogen.

**Pull request merged**
