### PR TITLE
Revert 'Nuke Ops Requesting Reinforcements'

### PR DESCRIPTION
**Pull request by ShiftyRail**
This PR reverts #34245.

The nuke ops PR was merged as a test merge and now we ask the question if it should stay in the game or not.

Made at the request of PrimeD.

🆑 
* rscdel: Nuclear operatives can no longer declare war for additional TC.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
ty my good friend shifty test reverts are just important as the test merges

**Comment by Eneocho** [comment]
I like the war thing, keep it.

**Comment by Theophrastus1** [comment]
havent seen it used once, pointless

**Comment by Securitymain** [comment]
maybe play the game dumbass

**Comment by DeityLink** [comment]
> havent seen it used once, pointless

Only round I've seen it used into was Antag Madness, the rest of the players were too busy being antag to care about the disk and the nuke op blew the station in like 10 minutes. Has it been actually used another time?

**Comment by Securitymain** [comment]
yes and it was horrible because it disallowed all shuttle calls

so miners couldnt get materials for guns
and cargo couldnt order extra guns
so all we had was the armory

but doriangay fixed that since then i think, so

**Comment by ErrorsWindows** [comment]
so does thumb up mean we shoot down the revert to keep it in the game or that we support the revert and want it out?

**Comment by ShiftyRail** [comment]
Thumbs up for the PR to be merged - so for a revert.
it's close enough that we might do it on a server poll.

**Pull request merged**
