### PR TITLE
Metaclub vox tradeship

### PR DESCRIPTION
**Pull request by Probe1**
**Adds** a vox tradeship to Metaclub

The tradeship has three presents, three spawners (maint, engineer materials, pill), a box of pill bottles and a pill dispenser.  In addition, it has two personal lockers, a chem fridge, ATMS, Intercomms, shutters with multiple control buttons, some chairs and some plants.

It docks at the metaclub vox research facility on z6 and transits to hyperspace then reaches the north side of arrivals.

Tested to the extent I can think of and it werks.

### CODE REVIEW

**Comment by Probe1** [comment]
Tradepost 

dreamseeker_2016-05-30_05-55-09

**Comment by Probe1** [comment]
Station

image

**Comment by 9600bauds** [comment]
cathe-jung
Other than that, it werks

**Comment by Ephx1** [comment]
What's the atmosphere situation like?
I'm guessing it must be all Oxygen.

Man it would be super cool if we could have little trade boxes to swap between two radically different atmospheres.

**Comment by Kurfursten** [comment]
@Ephx1 You can do that in a hacky way with flaps, we used to do that

No gas passes so you can just click the table through the flap to trade items

**Comment by Probe1** [comment]
@Ephx1 It's a regular atm.  

Since vox follow the just one drop rule with oxygen you'd need ship atmospherics going on to really keep it clean and man, fuck that.

**Comment by ihadtoregisterforthis** [comment]
Better have it be all oxygen_ated air_, plastic flaps are asking for trouble

**Comment by Shadowmech88** [comment]
Won't the oxygen from the ship's interior leak into the research facility when vox use the side door?

**Comment by Kurfursten** [comment]
Box dock has a very nice scrubber room that always kills the O2 leaks without fail

Could be easily replicated here

**Comment by Probe1** [comment]
>has a very nice scrubber room
heh (I made it look as shitty as possible as well as making it that long, tedious loop to be part of the vox aesthetic and in return for having a well functioning ship)

In testing oxygen contamination only occurred when I stood in the doorway letting it seep in.  Using the airlocks normally without obstructing them didn't result in it.

I could add o2 scrubbers but the area isn't a vox trading post.  It's an abandoned research lab with a section modified by Vox.  That's why I chose wood there.  It looks very hastily put together.

If people really want scrubbers there it can be done.

**Comment by Shadowmech88** [comment]
I guess the question is, is the vox research lab intended to be an area in which vox can survive without internals?
Because if so, _any_ oxygen contamination will hurt that intent.
Maybe just put a portable scrubber in there for them to use, if you think proper scrubbers are too high-tech for the area.

**Comment by FudgePucker** [comment]
Proper scrubbers aren't that high tec and can actually scrub o2.
Portable scrubbers can't be made, the RPD shits out ifinate unariy scrubbers.

**Pull request merged**
