### PR TITLE
changelings get the victims memories when absorbing people

### PR DESCRIPTION
**Pull request by gurfan**
what it says on the tin (tin referring to this PR)
[tweak]

:cl:
 * tweak: Changelings will gain their victims' memories when absorbing people

### CODE REVIEW

**Comment by Kurfursten** [comment]
kind of weird immershuns to only steal someone's memories of their bank account info and headset frequency

**Comment by gurfan** [comment]
it steals any notes they made and uplink codes too,  I guess you could steal any of their security/medical records but that seems a little unnecessary

**Comment by Dacendeth** [comment]
But muh antag checks.

**Comment by ShiftyRail** [comment]
On the one hand, the good old "Oh yeah? You're the HoS? Whats your bank account?" check was gay and obnoxious

On the other hand, it had its purpose and was basically the only way to safely out a ling, especially one in a position of power.

**Comment by boy2mantwicethefam** [comment]
I mean the point of a changeling is to infiltrate, they already have to deal with l*yalty implants

**Comment by xeroxemnas** [comment]
Good first step I think in reforming ling. Dumb shit like the ling who absorbed a guy not knowing the guy's bank info is dumb. But at the same time I think lings should let off an inhuman screech when you set them on fire. Obviously you cant go around setting random people on fire to check for lings without getting beaned so I think it's a decent enough tellsign of a ling.

**Pull request merged**
