### PR TITLE
Say vomit-stained, oil-stained, fuel-stained, etc. in item examine descriptions

### LINKED ISSUE #34779: Vomit-stained shoes are described as blood-stained
(WEB REPORT BY: hinaichigo REMOTE: 206.221.180.138:7777)
# Revision
8078c3eb86f3ead0ad27b4cf389352c38e991149

# Description
Stepping in a pool of vomit stains your shoes with vomit. However when you examine yourself the shoes are described as blood-stained.

# Steps to Reproduce
Step in vomit while wearing shoes so that the vomit stains your shoes.

# What you Expected
The shoes to be described as vomit-stained.

# What Actually Happened
The shoes were described as blood-stained.

### PR DESCRIPTION
**Pull request by Hinaichigo**
Currently, all non-blood stains on items, including oil, vomit, and fuel stains, are erroneously referred to as blood-stains in item examine descriptions. This makes it so that these stains will be referred to appropriately. Also this makes it so stain text is colored according to the stain color; the phrase "vomit-stained" will be vomit-colored. Kind of nice and reminds me of Caves of Qud. When you have more than one stain type on an item you can get things like "vomit-and-blood-stained workboots".

Fixes #34779

:cl:
 * rscadd: Blood and other stain text in item examine descriptions is color-coded.
 * bugfix: Vomit-stained, oil-stained, etc. items are no longer described as blood-stained.

### CODE REVIEW

**Comment by DamianX** [comment]
Do they look okay in dark mode?

**Comment by Hinaichigo** [comment]
Human blood, xeno blood, insectoid blood, vox blood, fuel, and vomit look fine on dark mode. Oil is dark but still readable. Grue blood is a bit close to the background color. Maybe there could be some sort of HSV brightness shift if it's within a certain amount of the background color? Or maybe a text outline of the same hue but different brightness if BYOND supports that.

**Comment by Hinaichigo** [comment]
Now it'll clamp the HSV V to a range that should be readable on both light mode and dark mode, which I set to [60, 200]. Oil text isn't pitch black but this seems to be a decent balance of all of the factors in consideration.

**Comment by Hinaichigo** [comment]
Fixed it so it can now say "that's an oil-stained scalpel".

**Comment by angryturnip** [comment]
sovl

**Pull request merged**
