### PR TITLE
I like tabs they make it all more readable.

### PR DESCRIPTION
**Pull request by SysadminJeroen**
Signed-off-by: Jeroen de Neef <jeroen52@gmail.com>

@PJB3005

### CODE REVIEW

**Comment by clusterfack** [comment]
What? That's stupid, don't go giving people the impression that's how the preprocessor works.

**Comment by SysadminJeroen** [comment]
What kind of preprocessor would shart itself at this type of style?

**Comment by clusterfack** [comment]
Things like this are going to give people the impression that the preprocessor cares at all about tabbing when it does not at all.

**Comment by SysadminJeroen** [comment]
@clusterfack I know it doesn't care, it just makes the code more readable.

**Comment by SysadminJeroen** [comment]
Let's just remove all possible tabs from the code, and change `if(value)` to `if(value == 1)`.

**Comment by ComicIronic** [comment]
>Let's just remove all possible tabs from the code

I mean, we basically already do this, unless you mean "compress stuff into single lines". Horizontal space is limited and you typically shouldn't indent what you shouldn't have to. I agree with Cluster, the preprocessor is not whitespace-sensitive and there's no reason to hint that it is.

**Pull request closed without merging**
