### PR TITLE
Update games vending machine sprite

### PR DESCRIPTION
**Pull request by brndd**
The sprite on this thing looked a bit strange in-game, since TG where it's lazily ported from uses a 3:4 perspective on their vending machines. Now it should have a more consistent perspective.

New:

Old:

:cl:
 * tweak: fixed the perspective on the Al's Fun and Games vending machine sprite

### CODE REVIEW

**Comment by Kurfursten** [comment]
I thought it looked off

**Comment by calzilla1** [comment]
Told ya

**Comment by RealestEstate** [comment]
well I don't see a difference, I think the old sprites look better even

**Comment by brndd** [comment]
The old sprite has an odd clash between 3:4 and our perspective. If you ignore the top and right sides of it it's just a 3:4 sprite. Hard to unsee when you see it.

**Pull request merged**
