### PR TITLE
vamps coffin healing

### LINKED ISSUE #8352: Vampires don't heal organs in coffins
Coffins heal vampires to 100% health but do not fix organ damage, meaning if you have ruptured lungs you have to suicide and cheat death to fix it.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #8352 

working as intended

### CODE REVIEW

**Comment by clusterfack** [comment]
Did you test it

**Comment by Intigracy** [comment]
n-no

**Comment by Intigracy** [comment]
Tested, it works.

**Comment by Intigracy** [comment]
working as intended

**Pull request merged**
