### PR TITLE
Changes regular window panes

### PR DESCRIPTION
**Pull request by Konater**
I wanted this for so long
windows

### CODE REVIEW

**Comment by clusterfack** [comment]
What?

**Comment by Probe1** [comment]
I had a similar reaction.  Get in irc so we can what at you more regularly.  Is the change removing reinforced windows cross thatching?

**Comment by Konater** [comment]
fug I'll do a comparison, but yeah pretty much

**Comment by PJB3005** [comment]
I can see the difference and holy shit yes. :+1:

**Comment by Probe1** [comment]
yeah ok thats much better.

**Comment by SkowronX** [comment]
QOL :+1:

**Comment by clusterfack** [comment]
I'm literally blind does it just make regular window panes look more like reinforced window panes?

**Comment by Probe1** [comment]
@clusterfack most objects in the game have subtle shading around their borders, usually with black.  It helps them stand out and avoid their edges blending in.  Sharper contrast between objects. You'll see if you look closely the panes on the right have white-ish borders now.  On the left, black. 

Plus the crosses at their ends which also looks nice.

If you're keen, spawn a nuka cola vend in game.  You'll quickly notice something is off about it.  It's the absence of a border.

**Comment by ihadtoregisterforthis** [comment]
**PILLOW SHADING**
And the "crosses" look out of place

**Comment by ComicIronic** [comment]
Drop a player vote on it or at least show some thread responses.

**Comment by Shadowmech88** [comment]
Pillow shading or not, the new windows at least look better than what we've got now.

**Comment by Probe1** [comment]
Custom vote started by Probe1.
**What looks better left windows or right windows**
Type vote to place your votes.
You have 60 seconds to vote.

OOC: Probe1: ye

OOC: Palamag: Current ones always looked weird to me

OOC: Probe1: yea I think thats a pretty universally held view

OOC: Probe1: but comic wants a vote so there will be DEMOCRACY

**Vote Result: Left with 8 votes** [ left is konaters diff ]
    Right had 1 vote [ right is current ]
    >windows had 5 votes [ install Gentoo ]

**Comment by Intigracy** [comment]
:+1:

**Comment by Konater** [comment]
If you want me to work on them more I will, I just used the ones from the goon rip and coloured it in with our existing windows

**Comment by Intigracy** [comment]
Looks fine to me.

**Pull request merged**
