### PR TITLE
CE's blueprints can edit/delete areas

### PR DESCRIPTION
**Pull request by unid15**
What it says on the tin. In addition, areas can't be deleted if they contain an APC or an air alarm, and turfs can't be removed from areas if there's an APC or an air alarm within 4 tiles around the turf.

Possible mischievous uses:

* Making areas un-telejammed by deleting them

* Deleting maintenance areas (obnoxious to fix, removes radiation shielding)

* Deleting important / big areas like hallways or medbay, leaving them unpowered

* Abusing the fact that space areas don't have lighting

This makes the station's blueprints even more of a high value item, since they can become pretty dangerous in the wrong hands. However, to delete an area you have to deconstruct both the area's APC and air alarm, so it takes a lot of effort to delete the entire station as a clown

:cl:
* tweak: Blueprints can no longer remove turfs from areas if there's an APC or an air alarm from the same area nearby.
* rscadd: Chief engineer's blueprints can edit and remove the station's areas.

### CODE REVIEW

**Comment by Intigracy** [comment]
With the first two in mind we should probably at some point come up with a way to replace those / add them to other areas of the station ICly.

**Comment by Kurfursten** [comment]
Instead of having telejamming be a property of an area, we should have a telejammer machinery.

**Comment by jakmak6** [comment]
Kurf on the wiki I swear on some poorly written thing about telesci they said you could build a portable teleportation jammer from protolathe. Now knowing it doesn't exist makes me wish I had it

**Comment by N3X15** [comment]
Was something I wanted to make in the original jamming PR, but never got around to

**Pull request merged**
