### PR TITLE
Defficiency Fixes 

### LINKED ISSUE #8995: Shitficciency auxillary storage room on research station Bug
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 861a5c96dce31ffa41e9b3dd913fac4b6a7e352a 
> 
> General description of the issue
> When you try to scan an artifact on the pad in that room, it scans the firelocker instead.
> 
> What you expected to happen
> Scan my artifact
> 
> What actually happened
> Scanned the firelocker
> 
> Steps to reproduce if possible
> Get large artifact
> Put on pad in that room on Deff
> Scan it
> Get a paper that reports about the locker

### LINKED ISSUE #9024: Nuke Ops ship crashes on part of Atmos on Deff
rogue fortress three 2016-03-24 203012

Let's think together why this can be an issue

### PR DESCRIPTION
**Pull request by Probe1**
## Reworks

**Partial rework** of engineering. Moves the AME away from telecomms and puts it where the escape pod was on the south side. **Adds a partially constructed R-UST** area where the AME was.  Moves the engineering escape pod to engineering storage where the particle accelerator is.  Redo the piping inside the SME area.  Adds more AME fuel jars and 3 more AME parts as well as expands the AME room so new players don't get cancer trying to set up the SME for the first time when power is running out.  Adds a "singularity footprint" outside the particle accelerator storage to give people an idea of what it should look like.  This may be a bad idea because I'm not sure if emitters can work in space and without a defined area it may cause more work than intended (building and defining rooms with blueprints).  Adds a new docking port for the centcomm shuttle that pods dock to.  The relocation of the engineering pod required some new stuff there to work.

I'm stopping here and will continue after this is merged because we're getting pretty long in the tooth.

**Remakes** the research outpost because of a fire closet interfering with machines.  https://github.com/d3athrow/vgstation13/pull/9248#issuecomment-205493835
## Tweaks

**Removes** a fucking scrubber attached to the supermatter engines cooling loop why https://github.com/d3athrow/vgstation13/pull/9248#issuecomment-205301832

**Adjusts** the nuke ops shuttle landmark by shifting it 10 tiles to the right so they don't fly into atmospherics. https://github.com/d3athrow/vgstation13/pull/9248#issuecomment-205301411

**Swaps** the grinder and shotgun in the bar back room by request.
## Additions

**Adds** a Crew Monitor Console to medbay lobby by request

**Adds** a wooden barricade next to the research outpost disposal mass driver so the trash doesn't just shoot over the mass driver and hit the wall further away.  I think that the current setup summarizes deff as a whole.

Fixes https://github.com/d3athrow/vgstation13/issues/9024
Fixes https://github.com/d3athrow/vgstation13/issues/8995
Fixes https://github.com/d3athrow/vgstation13/issues/8995

### CODE REVIEW

**Comment by Probe1** [comment]
Newk shuttle

image

**Comment by Probe1** [comment]
Location of scrubber.

image

**Comment by Probe1** [comment]
Old anomaly lab 

image

New anomaly lab, will probably revisit.

image

**Comment by ihadtoregisterforthis** [comment]
You left the manifold of the old scrubber.
Are there enough scrubbers left on the room?

**Comment by Probe1** [comment]
There aren't and I'm going to revisit the supermatter room, redoing the piping.

**Comment by PJB3005** [comment]
Can you make those windows at the expedition preparation room be like regular ones (grille, plating underneath...)?

Also while you're at it there's no fossil bags on the outpost.

**Comment by Probe1** [comment]
Yes I can.

**Comment by Probe1** [comment]
Under consideration.  Benefits from change:  It's a straight walk without twisty turny mazes from the shuttle to the roid.  The area is overall smaller.

chrome_2016-04-04_12-08-13

**Comment by Probe1** [comment]
I have no idea if people are gonna love it or hate it but based on feedback I'm going all in.
- Straight walk from the shuttle to the roid.
- Xenobotany expanded
- Anomaly lab consolidated into one room.

dreammaker_2016-04-04_13-28-49

**Comment by Probe1** [comment]
Taking a break for lunch.  I'm so excited with how this is turning out!

dreammaker_2016-04-04_13-54-47

**Comment by Probe1** [comment]
Outpost final.

image

**Comment by Probe1** [comment]
I'll try and tackle the SME and make it more agreeable without making it too casual tomorrow.  I will probably fail.

**Comment by Probe1** [comment]
First pass on deffiency engineering.
1.  Redid all the atmospheric piping inside the supermatter room and monitoring area to avoid running pipes under rwalls.  This was not pleasant but it's done.
2.  Made choice usage of manifolds for the SME cooling loop to make it very, very easy to hook up to an outside space cooling loop while still maintaining the freezer setup for new players.
3.  Added an RPD to the CEs office which was missing.

dreammaker_2016-04-05_10-21-39

**Comment by Probe1** [comment]
Finishing touches on shifting the AME from the north to the south.  Added some lattices so people know the footprint of a singlo.

dreammaker_2016-04-05_16-24-25

dreammaker_2016-04-05_16-10-02

**Comment by Probe1** [comment]
Stopping here for the day.  Feedback is always appreciated.

dreammaker_2016-04-05_19-08-32

**Comment by ihadtoregisterforthis** [comment]
Outpost looks noice

The singularity wireframe is unnecessary, almost restricting. Without any premade area planning is encouraged and even needed.
Also there's a docking arrow in the middle.

What's up with the escape pod?

**Comment by Probe1** [comment]
> Escape Pod

When redoing an area, I copy and paste everything in said area out in space so I know EXACTLY what the area needs/  Additionally, some things like security cameras have their own instance with their own network and ID.  If it were deleted from the map, the instance would either be deleted or lost in a list of 100s of security cameras all labeled identically as security camera.  This keeps everything 'on the map' so I can re-add it when ready.  The DNM tag is no joke!

> Singularity lattice

I've called it a footprint in my head.  The most time consuming part of setting up a singularity in my opinion is pulling up a map render of an existing singlo so you can count the tiles and make sure you got it right.  This takes that part out of the equation and gives players an optional starting point.  Some lattice and catwalks won't force them to only build it there, and easily be turned into plating or removed in the case of catwalks, or ignored entirely.  I think that this will encourage more singlo setups on Deff if people have a starting point.  The existing SME area has been used for a singularity but I think the walk is pretty tedious since you have to go up and around to get there.

When I asked in game, players were warm to the idea and I'll ask again.

> That docking port right in the dead center of the singlo footprint

I'm not leaving it there, it was just a little private joke like when I mapped Loss with lattices where the R-UST currently is.  I should have gone ahead and moved it before the screenshot.

Plus the area of a salvage shuttle/nuke ops shuttle/whatever requires some careful measurement and I don't want to either fling it out into deep space or leave it too close.  Finish the job, then move it in respect to the existing station instead of move it, oh wait I'm doing this here move it again and again and..

**Comment by Probe1** [comment]
That was a fine waste of time.  Never get up to get a drink before cleaning the map.  100% guaranteed you'll have forgotten and push uncleaned changes

**Comment by Probe1** [comment]
One last thing to do and that's check an iffy rtable in medbay thats just.. there.  In the hall.  WIth blood bags on the floor around it.

**Comment by Probe1** [comment]
Fuck that I'll get it in another PR in the future I just don't care anymore.

**Comment by Probe1** [comment]
I SAID MERGE IT IN A DAY AFTER PLAYER FEEDBACK YOU MADMAN

**Comment by clusterfack** [comment]
What you wrote

What I read

**Comment by Probe1** [comment]
# WE'LL DO IT LIVE

**Comment by Senaat1** [comment]
where are the cigars probe

**Comment by Probe1** [comment]
@Senaat1 I'm gonna do something special for the next PR.  I didn't say I'd do it but I didn't say I wouldn't either.

**Comment by Senaat1** [comment]
:eggplant:

**Pull request merged**
