### PR TITLE
Adds new Mommi Prime Alt Sprites

### PR DESCRIPTION
**Pull request by Cyadox**
Updates Prime Mommi sprite. Credit to @SkowronX 
prime
prime_emag
Also lowers the offset so the hats don't float on the new sprite
prime_hat
:cl:
* imageadd: Adds an alternative MoMMi Prime sprite, Credit to Skowron.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
This sprite is not just higher quality, but with a noticeably different shape.
That being the case, why remove the original? There may be players who still prefer the old Prime sprite.
There's no reason we can't have both.

**Comment by Cyadox** [comment]
@Shadowmech88 I'll be perfectly frank, it was easier to just replace the existing sprites than to make it yet another option. I could try, but I was assuming that not many people preferred the old Prime sprite because it's not that nice to look at.

**Comment by Intigracy** [comment]
Adding it as its own option is easy, and preferable to removing the current one.

You add it to the list() on https://github.com/vgstation-coders/vgstation13/blob/744949fc80c9f611df6b740d96ccf1fed00ac23e/code/modules/mob/living/silicon/mommi/mommi.dm#L97

You add an if to https://github.com/vgstation-coders/vgstation13/blob/744949fc80c9f611df6b740d96ccf1fed00ac23e/code/modules/mob/living/silicon/mommi/mommi.dm#L100

You add an if to https://github.com/vgstation-coders/vgstation13/blob/58def87fedc25b491eb63abd0a369a82b2c90558/code/modules/mob/living/silicon/mommi/update_icons.dm#L54

I personally prefer the other prime sprite, especially for the east/west.

**Comment by Cyadox** [comment]
@Intigracy Ah, alright then. I guess I'll call it Prime Alt, so people can still identify the original. Will update tonight.

**Pull request merged**
