### PR TITLE
Returns our precious super singularity

### PR DESCRIPTION
**Pull request by clusterfack**
The super singularity originally created by /vg/ and adopted by everyone has gone commented out for too long, too long I say!

A stage 5 singularity will expand into a super singularity (without ending the universe) when it eats a supermatter crystal, but the full crystal creates the super singularity along with the usual supermatter cascade.

### CODE REVIEW

**Comment by mrpain666** [comment]
FUND IT

F
U
N
D

I
T

**Comment by icantthinkofanameritenow** [comment]
DO IT FAGGOT

**Comment by ihadtoregisterforthis** [comment]
Keep in mind that the singulo eating the shard is very common

**Comment by Probe1** [comment]
taffy is looooose

**Comment by Skullyton** [comment]
So would somebody feeding say a stage 3 singlo a shard still be logged?

**Comment by liltiptop** [comment]
PRAY: I need about 9 super matter crystals pls. All near lord singuloth thanks.

**Comment by CptWad** [comment]
@Skullyton its logged alright. Though generally we can find out just about everything involving the singlo

**Comment by FudgePucker** [comment]
Make it the Gravitational MoMMially, so that when some asshole singlooses to get the shuttle called because 'objective complete time to call the shuttle for green text', and it eats my SME set up, it can wiggle all my despair and worries away.

"Shh shh, no tears now, only dancing"

**Pull request merged**
