### PR TITLE
VV and AtomProcCall quality of life changes

### PR DESCRIPTION
**Pull request by ShiftyRail**
**1.** _Can now put lists in atomProcCall._
You choose a list (not an empty list) as the type of argument, and you fill it as you go. Tested.

**2.** _Can now delete a value from a list by clicking a link._
As it says on tin. Not yet tested.

### CODE REVIEW

**Comment by ghost** [comment]
>VV et AtomProcCall 

ouais c'est un bon idée

**Comment by ShiftyRail** [comment]
It was 2am in my defence

**Comment by ghost** [comment]
c'est juste

**Comment by ShiftyRail** [comment]
Tested and fixed the issues. It works.

**Comment by ghost** [comment]
Bon travail!

**Pull request merged**
