### PR TITLE
Alternate Titles Plus - Useless Bloat Edition

### PR DESCRIPTION
**Pull request by ghost**
[wip]
[dnm]

Hello there.

This is a small PR that adds more alternate titles to some jobs. I'll probably add some special loadout stuff for the alt titles that it'd make sense for. The current list is:

- Atmos Tech - Firefighter and Life Support Specialist
- Mechanic - IT Professional and System Administrator
- Medical Doctor - Resident
- Geneticist - Cloning Technician
- Paramedic - Emergency Medical Technician
-  AI - Computer (hopefully works)
- Bartender - Barista, Barman, Barkeeper (probably should change it to Barkeep)
- Cargo Technician - Mailman, Mailwoman

Some alt titles I'd consider adding are:

- Chemist - Druggist (an actual name for chemists in some places)
- Internal Affairs Agent - Attorney

:cl:
 * rscadd: Added alternate titles to many jobs. Variety is the spice of life, some random idiot said.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Can I humbly request you to put this on hold for a while until I finish outfit datums ? It's a project that I've been working on, on and off, since a long time that tries to make adding special functionalities to alt-titles easier.
 
I should be done by them tomorrow so that your PR isn't delayed too much.
Thanks

**Comment by ghost** [comment]
> Can I humbly request you to put this on hold for a while until I finish outfit datums ? It's a project that I've been working on, on and off, since a long time that tries to make adding special functionalities to alt-titles easier.
> 
> I should be done by them tomorrow so that your PR isn't delayed too much.
> Thanks

No problem.

**Comment by Buchse** [comment]
I might suggest changing a couple titles to be a bit more formal sounding, like 'firefighter' to "Fire Control Specialist"/"Fire Suppression Crew", or the medical 'resident' title to "General Practitioner"

**Comment by ghost** [comment]
> I might suggest changing a couple titles to be a bit more formal sounding, like 'firefighter' to "Fire Control Specialist"/"Fire Suppression Crew", or the medical 'resident' title to "General Practitioner"

Resident title is used as the alert for "I am new to being a doctor". The term is used to describe doctors who are practically fresh out of medical school from what I have seen. As for Fire Control Specialist, I see no reason to oppose other than there already being a specialist. I'll go with crew.

**Comment by Kurfursten** [comment]
I'm not a fan of how long some of these titles are (e.g.: EMT), titles which are explicitly gendered (e.g.: mailwoman), and some of the titles in general just feel totally disconnected from the job. Mechanic as IT or a sysadmin? I also feel jobs should not confuse new players, you should immediately be able to tell what job an alt title is for. Nurse is a doctor, okay. Hydroponicist is a botanist, makes sense. Life support specialist sounds like someone who works on cryo.

I think alt titles can be great tools for creating a slightly different experience (beekeeper for botanist gives a bee packet, research botanist gives some botany stuff, gumshoe has mutation, all the trader titles have special stuff) but if it's just for a oneoff gimmick that's not very common (eg: playing firefighter as atmos tech) why not just as the HOP for a name change?

**Comment by ghost** [comment]
> I'm not a fan of how long some of these titles are (e.g.: EMT), titles which are explicitly gendered (e.g.: mailwoman), and some of the titles in general just feel totally disconnected from the job. Mechanic as IT or a sysadmin? I also feel jobs should not confuse new players, you should immediately be able to tell what job an alt title is for. Nurse is a doctor, okay. Hydroponicist is a botanist, makes sense. Life support specialist sounds like someone who works on cryo.
> 
> I think alt titles can be great tools for creating a slightly different experience (beekeeper for botanist gives a bee packet, research botanist gives some botany stuff, gumshoe has mutation, all the trader titles have special stuff) but if it's just for a oneoff gimmick that's not very common (eg: playing firefighter as atmos tech) why not just as the HOP for a name change?

I understand your point regarding new players. However, from my experience, which is rather little, some people will do a job for a specific aspect and want to be wholly associated with that aspect (e.g - Mechanic wanting to do _only_ NTSL and telecomms stuff).  It allows them to be a tad more specific. (In my opinion, telecomms tech would be a seperate job, but meh.)

But also, as long as the base names aren't different, new players shouldn't have _that much_ confusion with the naming. To quote the CL,

Variety is the spice of life, some idiot said.

**Comment by BomberBro** [comment]
Alt titles are pretty lame unless there's a viable difference (bridge officer vs IAA for example). I don't see the point in having different names with little attached to them as (as been said before) it confuses new players and it doesn't really make things clear for jobs (IT and sysadmin are just duplicates of tcomms tech, atmos techs have bizarre titles). If you're going to do this I'd rather have these be some sort of extra civilian jobs in place of assistants like having a mailman delivering actual letters or a barber minor job.

**Comment by SonixApache** [comment]
cute but bloat, exactly what it says on the tin

**Comment by cloutcode** [comment]
good ones: firefighter, barista, barkeep, mailman
rest: bloat, ____ technician (we have too many of those already), and cringe

**Comment by beesil** [comment]
I like the EMT, computer and bartender alt-titles, lukewarm on the others.

**Comment by DeityLink** [comment]
HoP nerf. Feels like I've been going to his desk less and less over the years.

**Comment by gurfan** [comment]
alt titles are cool and all but the lack thereof is another reason for the hop to exist, giving more alt titles without gameplay changes (ex. botanist to beekeeper) seems like bloat, though giving computer as an AI alt title would be fine.

also adding technician to the end of something doesn't make for a good alt title

**Comment by ghost** [comment]
Alright, the ones I am planning on keeping are:

- Computer (AI can't change his title)

- Barkeeper

- Resident (A good indicator that somebody is new to being a doctor)

- Druggist

**Comment by DamianX** [comment]
Druggist and Computer are really dumb, Resident and Barkeeper are okay though we already have a ton of useless alt titles for MDs in addition to Medical Intern which is supposedly the "new to being a doctor" title. I guess Barkeeper is the only noncontroversial one.

**Comment by ghost** [comment]
Gonna go ahead and close this.

**Pull request closed without merging**
