### PR TITLE
Some bloody doodle tweaks

### PR DESCRIPTION
**Pull request by DeityLink**
image

:cl:
* bugfix: You can no longer write in blood as a ghost if the source blood disappeared before you finished writing your message.
* bugfix: You can no longer write in blood if there is no blood left on your hands or glove by the time you finish writing your message.
* tweak: Ghosts can now only write in blood up to a certain amount of tiles from the original blood source (before they could daisy-chain messages ad nauseam). The max distance depends of the original source's amount of blood. A drip will only have a radius of 1. Splatters a radius of 2. Gibs a radius of 5. (Same distance as footprints)

### CODE REVIEW

**Comment by Eneocho** [comment]
Last few rounds I've had bloody insulos (from surgery on a vox and from injuring myself), but couldn't write with blood.

**Comment by DeityLink** [comment]
the blood disappears from the player sprite but not from the gloves icon when used. This is confusing so I'll have it properly disappear there as well. Do note @Eneocho that picking up items with bloody gloves also "transfers" blood to them, and thus consumes the blood you could have otherwise used to write stuff.

**Comment by Eneocho** [comment]
I took a scalpel, botch the initial slice, gloves bloody, can't write.

**Comment by DeityLink** [comment]
We'll see if it still occurs after this PR,haven't been able to reproduce it.

**Pull request merged**
