### PR TITLE
Adds clown curse empowerment

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
This empowerment will make the shoes the slippy ones that have a 10% chance of lubing the floor per step from pierrot.
You are blowing 40 points on one of the most antagonizing spells in the game
These shoes can be acidable unlike normal clown curse shoes
Watch your step!
:cl:
 * rscadd: Added a new wizard empowerment for clown curse!

### CODE REVIEW

**Comment by Caboozles** [comment]
Yeah. No. Uncurable curse+acid lube? Absolutely not.

**Comment by boy2mantwicethefam** [comment]
It's not acid lube

**Comment by Caboozles** [comment]
I admit I misread it.
I still don’t like it because getting to medbay will just be lube hell, but it’s better I guess.

**Comment by boy2mantwicethefam** [comment]
Poor reception

**Pull request closed without merging**
