### PR TITLE
Emag Chem Dispenser

### PR DESCRIPTION
**Pull request by Kurfursten**
image

Destroy muscle memory chemists with this one cool trick.

🆑 
* rscadd: You can now emag the chem dispenser to scramble it.

### CODE REVIEW

**Comment by jwhitak** [comment]
Pure evil, and even more emag buffs. Give this to the Pulse Demon instead.

**Comment by angryturnip** [comment]
The pulse demon has an emag ability so it would be able to do this

**Comment by Kurfursten** [comment]
It's way less evil than what the emag already does to the microwave, which is to ruin every meal with the only indication of what is wrong being a different cook sound

**Comment by jwhitak** [comment]
I am antagonized even outside of the game, that is why I have to thumbs down. That's how cruel this is.

**Comment by Kharkov72** [comment]
if you got such a problem with it just crowbar it out and reconstruct it smh

**Comment by Eneocho** [comment]
Criminally hilarious.

**Comment by smalIboss** [comment]
you fucking faggot

**Comment by Eneocho** [comment]
Based reagent list remembering chads, it's our time.

**Comment by SECBATON-GRIFFON** [comment]
its simple and stupid but i love it

**Comment by Killette2** [comment]
You could also make screwdrivering it splash out dangerous chemicals. Outfits can protect from this but it would make it a little more dangerous to instantly fix without taking precautions

**Comment by SonixApache** [comment]
absolute devil

**Comment by Eneocho** [comment]
Does this affect the booze dispenser, brewer, condimaster, etc?

**Comment by Kurfursten** [comment]
Yes because they are children

However, there are less options and people practice them less, so I expect less complaints

**Comment by Eneocho** [comment]
I just needed clarification for the wiki, thanks for the help.

**Pull request merged**
