### PR TITLE
raging mages now costs 25*

### PR DESCRIPTION
**Pull request by SonixApache**
crazy that ragin mages currently costs 5 points less than vox raiders even though it's a total round ender 90% of the time

:cl:
 - tweak: made raging mages midround cost 25 points instead of 20 points

### CODE REVIEW

**Comment by Irradiation** [comment]
If you're going to grudgecode, at least add a changelog

**Comment by Securitymain** [comment]
grudge PR, downbooted

**Comment by SonixApache** [comment]
@Irradiation the changelog hasn't updated in three months.

**Comment by Exxion** [comment]
Do it anyway.

**Comment by Eneocho** [comment]
Difference is that raging mages can be funny. Pox raiders can't be fun.

**Comment by pedr69** [comment]
raiders had the potential to be fun
when suddely the captured raider got deleted for some reason and then ragen spawned(with 4 apprentices)

**Comment by Pastamadness** [comment]
Repoban this man

**Comment by Theophrastus1** [comment]
welcome back sonix

now fuck off

**Comment by SonixApache** [comment]
good counter-arguments from the downvoters, fruitful discussion 
i'll wait for one of the collabs to stroll past, look at the :-1:s and press close

**Comment by Kurfursten** [comment]
I have done a lot of legwork on this over the last few days chasing down a bunch of people who voted on this in both directions, but mostly people who voted down. I'm amazed that this was such a voted-on PR since a tweak of 5 threat seems like a nothingburger. A lot of the people I spoke to didn't feel opposed to the change itself, but rather vote against what they felt was the spirit of this PR (being an "ided PR"). However, I think some people like Eneocho voiced completely valid opinions that they think Ragin Mages is simply more fun than Vox Raiders and I think it's valid to say that fun can be a component of threat cost.

At last night's meeting, Luzzy encouraged me to (1) consider emojis less (2) do test merges more and (3) be more willing to tweak dynamic weights, costs, etc. In the spirit of that, I'm going to merge this change today. However, if after 1 week people dislike the change (I am guessing no one will notice), you are more than welcome to PR a change to something else.

I still care about community votes in general, which is why I bothered to do so much work talking to people.

**Pull request merged**
