### PR TITLE
Allows picking up all tiny animals

### PR DESCRIPTION
**Pull request by unid15**
- Dragging an animal onto yourself while not on help intent will put it into your hand
- Hostile animals escape from your grasp UNLESS they consider you their friend (you have the same faction, OR they don't consider you a valid target to attack)
- (the animal must be smaller than you, animals with size SIZE_SMALL and bigger must be held with two hands)
- Alien larvae are tiny now (previously they were human-sized)
- Animal holders are pooled now
- Animal holders can be deep-fried now

### CODE REVIEW

**Comment by Konater** [comment]
Can we pick up Ian and Runtime with both hands?

**Comment by Unfit** [comment]
not really but it's possible

I'll be more than happy to implement that if somebody sprites in-hands for them!

**Comment by clusterfack** [comment]
Oh jeeze at least pool these

**Comment by Probe1** [comment]
Interesting.  I was going to make a feature request related to this.  .. does this mean that mouse traps can now kill xeno larva?  

I hope so.  That'd be fantastic.

**Comment by Unfit** [comment]
No, they're snowflaked to only kill mice

**Comment by Probe1** [comment]
GAY

**Comment by Unfit** [comment]
@N3X15 no compile failure here just travis being silly

**Comment by unid15** [comment]
Just tested it and everything works fine

**Comment by unid15** [comment]
And the mob holders work flawlessly with cooking machines now

**Pull request merged**
