### PR TITLE
removes relics of a bygone era

### PR DESCRIPTION
**Pull request by Intigracy**
removes vgstation.dmm since it's just an old old version of box and is unused anymore. it'll remain in github's memory 5ever tho

removed an admin message that has 0 use anymore due to the time that has passed since it was added

changed an immersion breaking message

### CODE REVIEW

**Comment by ghost** [comment]
A T O M I C

**Comment by Intigracy** [comment]
How about fixing your shit?

These are all ancient relics that I'm removing.

**Comment by CptWad** [comment]
oh thats not boxstation
but please remove it
please

**Comment by xpcybic** [comment]
As long as you don't touch heartstation
(I have PLANS)

**Pull request merged**
