### PR TITLE
revert 64x

### PR DESCRIPTION
**Pull request by PJB3005**
Checked out icons to pre-64x, downscaled maps and edited the world icon size.

This took 2 minutes to do.

### CODE REVIEW

**Comment by ghost** [comment]
Some things are too good to be true

Don't trust the Lummox

**Comment by unid15** [comment]
thank you

**Comment by kol1th** [comment]
What about the sprites and movement states that were deleted?

**Comment by unid15** [comment]
Did you revert maptext size of status displays and crayons too?

**Comment by d3athrow** [comment]
Need confirmation of what @kol1th and @unid15 asked.

**Comment by Exxion** [comment]
Sprites are fixed, but I don't believe maptext is yet

**Comment by ghost** [comment]
press F to pay respects

**Comment by ghost** [comment]
> ctrl+f ".dmm"
> no results

you sure you edited the maps?

**Comment by unid15** [comment]
Github isn't displaying all changes because there are 682 of them

**Comment by Exxion** [comment]
There are no `.dmm`s in the drop-down menu either
But what changes do the maps need?

**Comment by d3athrow** [comment]
to view the full changes just pull the commit locally 
git checkout -b PJB3005-revert-64 Bleeding-Edge
git pull https://github.com/PJB3005/vgstation13.git revert-64

**Comment by PJB3005** [comment]
@unid15 yeah indeed maptext wasn't fixed I don't think let me do that.

**Comment by clusterfack** [comment]
Here's a list of what needs to be fixed manually
-revert the contextual click changes
-revert the maptext font size changes
-change back the pixel_x and pixel_y of things on the map

**Comment by PJB3005** [comment]
Okay I forgot context click stuff, the rest should be done though.

**Comment by clusterfack** [comment]
Yeah just go through my last 4 commits and you'll see all the things I had to do manually, they're really short

**Comment by ghost** [comment]
So, what's the verdict, is 64x64 getting reverted for definite?

**Comment by clusterfack** [comment]
For the time being yes, for reintroduction when either Byond improves dream maker native behavior or when monster's open source mapping tool comes out.

**Comment by ComicIronic** [comment]
Let no-one claim defines aren't useful.

**Comment by gbasood** [comment]
I have a question regarding 64x by the way
I know there's a bug related to mob overlays and blood making people invisible
That's got to be our fault,right? It's too specific a case to BYOND's fault

**Comment by clusterfack** [comment]
Making people invisible? No, the only bug thats been reported similar to that is one that THOUGHT blood overlays were making inhands invisible, when in fact inhands were just broken recently by a PR. There's zero evidence of what you've said that I've seen/heard.

**Comment by gbasood** [comment]
Borg turned invisible while beating someone to death a round ago, which is entirely a new bug
I must've remembered the inhands thing though
It was probably rsc corruption or fucked up icon states or something

Actually probably rsc, only turned invis for some people nto all

**Comment by NigglyWiggly** [comment]
if they were combat borgs, that's because of the whole 'deleting icons' business

**Comment by clusterfack** [comment]
@PJB3005 Fix conflicts please

**Comment by 9600bauds** [comment]
self merge as soon as ready

**Comment by PJB3005** [comment]
Self merge is bad and you know it.

Shouls be ready though.

**Comment by clusterfack** [comment]
Lel I bet this causes more bugs than the original pr

**Comment by ScrambledSteak** [comment]
maxresdefault 3

**Pull request merged**
