### PR TITLE
More chat fixes.

### LINKED ISSUE #9125: AFK admins no longer display as AFK after the chat stuff was changed

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes adminwho AFK, Fixes #9125
Fixes human icons in chat.

### CODE REVIEW

**Comment by clusterfack** [comment]
Really, your solution is to create another whole tracking number?

**Comment by PJB3005** [comment]
@clusterfack do you have a better solution?

**Comment by clusterfack** [comment]
Spoken with pjb about a server side method to modify the pinger, we'll see what happens I guess

**Comment by gbasood** [comment]
I'm interested in hearing about what other solution for AFK tracking there would be, if one is found

**Comment by PJB3005** [comment]
Alright fixed.

**Comment by FireFlashie** [comment]
@PJB3005 Can you help with fixing "я" letter in new chat, please? Usually sanitize change working on IC, OOC and emote, but no with the new chat. Can i somehow fix all issues with it?

**Pull request merged**
