### PR TITLE
Create the Judge Strike team

### PR DESCRIPTION
**Pull request by DamianX**
Are you sick and tired of the fact that nine times out of 10 the only person to judge a court case is a biased captain? Well now (and this probably won't work) you can pick some poor shlub out of the void to judge for you!. 

:cl:
 * rscadd: Added a judge strike team for obs

### CODE REVIEW

**Comment by DeityLink** [comment]
obsgang's power grows

**Comment by juanototo2** [comment]
Spoilers: This does not actually deploy judges as in court case judges. It deploys judges as in Judge Dredd, with hilariously overpowered NT-12s.

**Comment by SonixApache** [comment]
throw a godslayer in there in case of cult

**Comment by wotisjanitor** [comment]
THANK YOU AAAA IVE WANTED THIS FOR SO LONG! Every time i try to sue a head or sec as a lawyer the captain always just says "no" because that = less valids secured.

**Comment by BomberBro** [comment]
github

**Comment by ShiftyRail** [comment]
That is a ruleset, not a strike team. People won't be able to call it down, although admins will.

**Pull request merged**
