### PR TITLE
makes polls less clumped together when on the list

### PR DESCRIPTION
**Pull request by Intigracy**
Note there's spacing before and after options, image only shows the before but I changed it after.

### CODE REVIEW

**Comment by Anton-Kr** [comment]
>adding quality tag to own pr

**Comment by Exxion** [comment]
For like the 35th fucking time, the [QUALITY] tag is the QoL tag
Not a tag used to say a PR is good

I'm going to remove the hearts so maybe people stop saying that

**Comment by Intigracy** [comment]
I changed it after reading your message, if you hadn't noticed yet.

**Comment by FudgePucker** [comment]
That feel when they weren't complementing you, just tagging as QoL.

**Comment by RFultra** [comment]
why not call the tag QoL instead 🤔

**Comment by Exxion** [comment]
This is what QoL stands for

**Comment by Intigracy** [comment]
This is ugly

**Pull request closed without merging**
