### PR TITLE
Adds a grace period after antag destruction

### PR DESCRIPTION
**Pull request by ShiftyRail**
So when you gib/cremate/etc the big bad boy, you've got some relief before another joins in.

:cl:
- tweak: Added a grace period of 15 minutes after an antag's destruction before their death is taken into account for the threat level.

### CODE REVIEW

**Comment by iFlashYou** [comment]
>15min

make it 10

**Comment by ShiftyRail** [comment]
"No"
Can be further tweaked of course, but I believe 15 is reasonable enough

**Comment by boy2mantwicethefam** [comment]
Reduce it to 5 minutes

**Comment by jknpj** [comment]
>yet another metatrick that you can use as secmain

.s call the shuttle and cremate the wizard

**Comment by Accipitermaris** [comment]
I think that applies more to antagonists refunding threat when gibbed than it does to the grace period proposed here

**Comment by Hoshi-chan** [comment]
No fixed time limit. Either make it refund threat over time, or refund it after a randomized amount of time.

**Comment by KingofHONK** [comment]
imagine wanting to play sec without an steady IV drip of fresh valids. Just because the french fly the white flag doesnt mean the boys in red have to too.

**Comment by SonixApache** [comment]
i'd say make it random between 8-14 minutes to counter the metagay
otherwise nice change, fuck chain ninjas

**Comment by Caboozles** [comment]
A variable amount of time sounds better.

**Comment by ShiftyRail** [comment]
Random period between 9 and 14 minutes.

**Comment by Kurfursten** [comment]
I feel like this PR is coming from an... extremely confused place. I'm actually surprised it's from Shifty because he should have access to the threat log to see what the numbers look like. The number one contributor to refunded threat is latejoining officers. Besides vampires, most of the time antag threat refunds never happen. People either perma, borgify, or just kill traitors, wizards, and ninjas, they rarely destroy the brain - which is what is necessary to refund threat. If this PR gets merged you will notice nothing different at all.

If your goal is to slow the rate at which midround antags arrive, you should be looking at the injection timers, not the antag destruction refund. I would actually go as far to say I believe *no ninja has ever refunded threat*, because I have never seen someone cremate the brain. I notice you red boys putting them up like trophies in your office while obliviously refunding threat yourself by bringing on new secboys throughout the shift through latejoins!

**Comment by ShiftyRail** [comment]
I know precisely what this does. This is less about ninjas and more about, say, vampires (who can very easily get cremated). Or a traitor that gibs themselves via e-implant, automatically refunding threat.

**Comment by Kurfursten** [comment]
What exactly is the end goal here then? I commented on ninjas because "chain ninjas" seems to be where the majority of your supporting votes are coming from. You certainly didn't correct them on the matter. Like I said, if your goal is "antags show up too soon", you should be targeting injection timers (as you have in a separate PR).

I think this is adding an unnecessary layer of disconnected moving parts, especially if you're planning to slow midround injections to once every 1 hour 40 minutes (!) with a high chance of failure to inject anything (!!), it's *really* unnecessary and unhealthy that a destroyed antagonist might get killed right before your 1 hour 40 minute tick goes by. Say they get smoked in the chapel at 1 hour 30 minutes, that causes the check to not have any threat available, now it's extended until 3 hours. Extra sleeps in general are to be avoided for this reason.

**Comment by ShiftyRail** [comment]
Conflicts fixed

**Comment by ShiftyRail** [comment]
Does not seem to be going anywhere, code is here if someone wants to do it.

**Pull request closed without merging**
