### PR TITLE
Adds blank toolboxes

### PR DESCRIPTION
**Pull request by SonixApache**
Added blank grey toolboxes that can be made at an autolathe
~~Added combat toolboxes that can be made at a protolathe (combat tech 2)~~
Re-organized toolbox in-hand sprites
Re-organized storage.dmi

toolboxes

🆑 
 - rscadd: You can now print empty toolboxes at an autolathe
 - imageadd: Sprites by DrSlimes

### CODE REVIEW

**Comment by FudgePucker** [comment]
I don't know about giving science printable toolboxes with same force as syndie toolbox.

**Comment by ghost** [comment]
Considering it takes 3 minutes if you know any science to just get a syndiebox or fireaxe it's kind of a moot point.

**Comment by ghost** [comment]
3 minutes is a significant amount of time

Think of how much shit you can do in 3 minutes

**Comment by Exxion** [comment]
So it's a worse but less suspicious syndiebox?

**Comment by SonixApache** [comment]
pretty much, yeah

**Comment by RealestEstate** [comment]
I like the idea of printing more toolboxes from an autolathe. I'm not so fond of the poorly reskinned not-a-syndicate toolbox that science can print. it looks bad (in my most humblest of opinions), and it doesn't fill a niche or role in the station that a regular reprintable toolbox wouldn't. science is already capable of making better melee weapons than this, and would just be another thing to scroll past on the RnD console on my way to click on the cool guns.

**Comment by RealestEstate** [comment]
also, the joke of the toolbox is that it's a seemingly mundane item that is very easy to attain, but it is effectively one of the best noncontraband weapons that isn't a flat out stun. making a combat toolbox a result of scientific combat testing would be overdoing the subtlety of the joke just a bit, I think

**Comment by SonixApache** [comment]
Alright, I'll scrap the combat toolbox.

**Comment by jakmak6** [comment]
Keep the Sprite though. It's a nice Sprite and I'm sure we can find use for it

**Comment by ghost** [comment]
ERToolboxes maybe?

**Comment by ghost** [comment]
Now, if I recall correctly, it would throw an error if you tried to spawn the regular toolbox on the main server. Is that still the case here?

**Comment by SonixApache** [comment]
@jakmak6  @Unknown-as-Captain 
Keeping the sprite in, unused for now.

@Skullyton 
No errors on my end.

**Comment by Intigracy** [comment]
It used to do a weird world to_chat when you tried to spawn the parent toolbox, someone fixed it at some point but I can't find the PR.

**Comment by DrSnips** [comment]
Could have the combat toolbox just called the NToolbox and make it just a normal toolbox that you can obtain from having NT exp. 1 research. Maybe have the buff to it, but would at least be something in the NTE branch that's actually NT themed.

**Comment by gbasood** [comment]
No combat toolbox it's a bad idea

**Comment by DrSnips** [comment]
Combat box is kinda odd, but having it as a normal toolbox that the proto can make would add something at least NT related to the NTE tech branch because currently there isnt anything NT related in it.

**Comment by gbasood** [comment]
I think that's a dumb way to justify adding a bad thing.
"Yeah it's dumb, but at least it's a feature for X neglected feature"
NT tech branch stuff would be nice but not a combat fucking toolbox

**Comment by DrSnips** [comment]
Im not saying it needs to should be the buffed combat toolbox, Im saying it should just be a normal toolbox for NTE research.
But to be fair, about half the things things from NTE branch are weapons already (gravity well gun, rico. gun, marauder circuts). Still shouldnt be a buffed toolbox though.

**Comment by SonixApache** [comment]
My plan is to just make a NT toolbox that doesn't do anything special, and add it to the ERT room in a later PR.

**Comment by gbasood** [comment]
That's fine

**Pull request merged**
