### PR TITLE
Allow player to control skeleton jack on spook

### PR DESCRIPTION
**Pull request by toomykins**
> [19:15:46]ADMIN: PM: Manylo/(The god of light switches)->Toomykins/(Gary Gutter): oh yea if you need a coding idea  
> [19:15:55]ADMIN: PM: Manylo/(The god of light switches)->Toomykins/(Gary Gutter): allow the candy_jack to be possed by ghosts instead of being turned on 
> [19:16:02]ADMIN: PM: Manylo/(The god of light switches)->Toomykins/(Gary Gutter): it's spooky / low impact 

>see jack-o-lantern candybucket
>spook it
>animates it
>prompt asks whether you wish to control it
>you get to control it
it's a simplemob 

:cl:
* rscadd: observers/ghosts are now able to possess the jack-o-lantern candy-buckets upon spooking

### CODE REVIEW

**Comment by pedr69** [comment]
>toolbox strength simplemobs

:/

**Comment by GreatBigFailure** [comment]
Neat

**Comment by Kurfursten** [comment]
Make this check for month =10 and you have a deal.

**Comment by toomykins** [comment]
> Make this check for month =10 and you have a deal.

...
it was already in the code before i even touched it
```
/obj/structure/candybucket/candy_jack/New()
	..()
	if(text2num(time2text(world.timeofday, "MM")) == 10)
		spooky = TRUE
```

**Pull request merged**
