### PR TITLE
Custom paintings

### PR DESCRIPTION
**Pull request by jellyveggie2**
Customized player made paintings, You might remember this from 2-4 months ago from positng on the thread.
You can now build a variety of blank canvases using a stack of wood: 
* Small: 2 stacks, as usual.
* Portrait: 3 stacks. Wide as a small painting, and about as tall as a wall
* Landscape: 3 stacks. Portrait but rotated 90 degrees.
* Large: 5 stacks: covers nearly the entire wall.

showcase
Untitled
New blank canvases side by side with some existing paintings for comparison.

Onto the painting UI:
* Pick a color to paint with from the little colored squares, the big colored square is your active color. 
* Modify opacity (0 to 1) for better control on how much paint is applied
* Colors mix using the RYB formula:  blue and yellow makes green and all that
* You can name, describe, and sign your paintings on the Info tab
* Like piano songs, painting templates can be imported and exported through the Import tab. A "Help" tooltip explains how the templates are structured.
* Once you've imported a template, you can use it on the Template tab. Click on a color region to paint the entire region with your desired color and opacity. You can move any regions you're done with off the list.
* Templates are merely that, properly matching the intended result is up to the player's ability and resources. It's also useful in that, say, if there's a series of arrow templates you can choose wether to paint the arrow green or blue instead of white.
* When done, press Save changes for your painting to be saved onto the canvas. Make sure to do this between paining tool changes (eg. press save before switching from the red crayon to the blue crayon).

crayon

Use a painting tool on a canvas to start drawing, colors and painting opacity available to you will depend on your tool of choice:
* Pens: you'll only have the one color of the pen available to you: Black, red, blue, whatever. Maximum opacity is reduced to 15%.
* Crayons: Crayons have two colors available to them and same max opacity as pens. Reminder that you can use rainbow crayons in hand to customize said colors
* Painting brush: New item, built using a stack of wood. Holds a single color, can use 100% opacity. Use on a reagent container to take on it's reagents' color when painting, basically a color picker. Use on a container with water, space cleaner, or paint cleaner to clean the brush.
* Palette: ~~Held in hand when painting with a brush, adds it's colors to those available while painting. Use a brush on it to mix your custom color palette into it~~ TODO.

Caveat: The whole thing works off the canvas API, unavailable to Internet Explorer 8 or older. Meaning, **you won't be able to paint if you're on Linux**. I think you can still paint through the Template tab, but I'm not entirely sure. 
Sorry.

**TODO**
Some notes on the current state of this PR: Halfway through I ran into some IRL stuff, and I've no idea when I'll be able to get back to this so here's a laundry list of unfinished stuff:

Painting editor:
- [ ] Buggy color mixing algorithm: Hue-wise, the RYB rules work fine, Red+Yellow results in Orange, Yellow+Blue in Green, Blue+Red in Purple. Issue is the result is somewhat desaturated, gray, so you just can't get a proper bright Orange color. No idea why, I was yet to look into it, players will have to paint with orange crayons or orange juice for now.
- [X] Alpha: Many reagents have an alpha component to them (aka: they're somewhat transparent), meaning if you pick their color with a brush you might not get what you were expecting. Giving the brush the right color would be easy, hard part is reworking painting code on the UI to support painting with alpha colors.
- [ ] Brush size: Add brush size support, for spray cans. Everything else is small enough (compared to a canvas) that 1 pixel is more than enough
- [X] Movement detection throttling: BYOND seems to detect cursor movement more often than actual IE  or Firefox do, end result is a 0.1 opacity turns out more opaque on BYOND than it should. Might be performance dependant, faster computer = stronger strokes.

Canvas UI:
- [ ] Paint import should bring up an error mesage if your template code is fucked, perhaps explaining where the issue is.
- [ ] It would be nice to be able to set an offset for templates, and  have them clip instead of get messed up if used on a canvas  that's not wide enough (or offset too close to a border). Right now using a 24x24 template (large paintigns) on a 14x14 or 14x24 canvas (small and portrait paintings) results in every  half row being assigned to the next row.
- [ ] Paint export is nearly useless for most paintings, specially those where you're limited in your maximum opacity, as it results in hundreds of single-pixel areas. A way to reduce the export's palette to a custom number of colors, and perhaps some ways to name and reorder color regions, would likely be welcome.
- [ ] Canvas size/zoom: might be useful to have a way to zoom into the canvas on the UI, specially for small paintings.
- [ ] Template area overlays: Some way to tell what exactly will you be painting over when filling in an area

Items and mechanics:
- [ ] Palette: Right now it's mostly just a comment on the code, on how to go with it, there's basically nothing done on it. Without these, brushes are nigh useless
- [ ] Brushes: Right now it's a simple color picker, and cleaning it does not consume cleaner nor leak paint into it, so cleaning is mostly for flavor. Mechanics will likely vary depending on how palettes are made.
- [ ] Easel: Not necessary, but it was a nice idea. Rough idea was a portable "wall" to hang paintings on, with perhaps some extra functionality added in: Folding, storing palettes...
- [ ] Paint mixing: Paints from cargo should probably mix using the same RYB rules as the UI (once the desaturated Orange issue is fixed).
- [ ] Spray cans: Make hair dye spray cans into painting tools
- [X] Cargo crate: Now includes a brush, two small canvas and one canvas each of portrait, landscape and large variants.
- [X] Painting protection: Place a glass pane on a canvas to prevent further painting, screwdriver to remove glass pane

:cl:
 * rscadd: Staff shortage has prompted Nanotrasen to broaden our horizons: Fine Arts graduates are now welcome! You may now be able to expect crewmates to know how to use a crayon on a canvas.
 * rscadd: Build a blank canvas using a wooden stack, current sizes are: Small, Landscape, Portrait, and Large.
 * rscadd: Use a painting tool on a canvas to start drawing: Pens, crayons and brushes work.
 * rscadd: Build a brush using a wood stack, and dip it on a reagent to take on it's color. Order some paint from cargo, or paint with blood and orange juice.
 * rscadd: Like piano songs, you can import and export painting templates for later use. However, actually managing to match the template's expected result is up to your ability and resources.

### CODE REVIEW

**Comment by jellyveggie2** [comment]
Painting templates for the first screencap (Clown, Lemmings, Quote, Curly, and an extra one, Niko): https://pastebin.com/LkKEiV1e

**Comment by jellyveggie2** [comment]
Huh, don't remember ever touching mirrors or combs, but there it is on icon diff details

**Comment by Kammerjunk** [comment]
holy shit

**Comment by DeityLink** [comment]
Is there a specific reason why the painting dimensions have to be those specifically?

**Comment by jellyveggie2** [comment]
> Is there a specific reason why the painting dimensions have to be those specifically?

No real reason iirc, 12x12 pixels for small just felt too constraining I guess.
Just have to make sure the dimensions on the paintings.dm match those of blank canvas icons. Oh right, and any existing templates would have to be adapted, that reminds me of something else that was on the TODO list.

**Comment by Eneocho** [comment]
Holy based. You actually fucking did it, you madman.

**Comment by Eneocho** [comment]
>Like piano songs, you can import and export painting templates for later use. However, actually managing to match the template's expected result is up to your ability and resources.

So, if I'm reading this correctly, I can't export a painting I did on one round to import on another and be done? I need to import then paint?

**Comment by DeityLink** [comment]
> No real reason iirc, 12x12 pixels for small just felt too constraining I guess.
> Just have to make sure the dimensions on the paintings.dm match those of blank canvas icons. Oh right, and any existing templates would have to be adapted, that reminds me of something else that was on the TODO list.

I mean that you could instead let the player set the dimensions themselves, and create a canvas icon dynamically instead of having presets in painting.dmi
As long as the html accepts any dimension that can be easily added later.

**Comment by jellyveggie2** [comment]
@Eneocho 
> So, if I'm reading this correctly, I can't export a painting I did on one round to import on another and be done? I need to import then paint?

That's correct. I think I did a video showing how that works once but couldn't find, I'll dig around for it or record a new one later.

@DeityLink 
Sounds quite doable. 
Painting data is datumized, you can set whatever size and offset you want on creation. Once a player's filled the bitmap through the UI, just call render_on() providing it a base icon and it'll return said icon with the bitmap layered on top.
You'd just pass it an empty icon, and either extend it render_on() or pass the icon through a different method that'd dynamically paint a frame or whatever around. 
Right now the canvas icons exist to provide said frame as well as providing players with a sense of size before they get to painting.

The html I think should be able to handle things, but is rather simplistic about it. [paintTool.js](https://github.com/vgstation-coders/vgstation13/pull/29839/files#diff-79993197a49626c06946903c19c37d566cd772e63402461923d683b8aaa5ca3dR109) takes whatever size it received and multiplies it by 20 for rendering and cursor location purposes, while [canvas.js](https://github.com/vgstation-coders/vgstation13/pull/29839/files#diff-10b273136ebe46e482c7439701133f8c0eac127e5484502a5cd5a0b7f2d306f4R211) takes that into account to adapt the canvas UI's .css.
A microscopic 1x1 painting will squash the palette on the UI I think, a humongous 64x64 painting will stretch out of the window and require a good deal of scrolling, it's all part of the "Canvas size/zoom" TODO task I suppose.

**Comment by jellyveggie2** [comment]
On the topic of loading an already done painting rather than a "paint-it-yourself" template, codewise it shouldn't be too hard, just replace a datum/custom_painting's var/list/bitmap and set the bitmap height and width it was intended for. Should be good for building a gallery a la the library's book database - Extract bitmap, bitmap width/height off a painting and store it on a DB (probably store author, title and description too), then later on spawn a canvas and slap that info onto it's custom_painting datum.

Issue is all the DB stuff, of which I don't know jack about.

**Comment by DrSnips** [comment]
A color source you could consider adding. There's the can of hair dye which is effectively spraypaint. It's got a color picker as a part of it which would be really nice here

**Comment by jellyveggie2** [comment]
Right, I should explain how adding painting tools works, It's fucky and probably needs a rework.

On custom_painting_datum.dm (alongside /datum/custom_painting) there exists the /datum/painting_utensil.
On [New()](https://github.com/vgstation-coders/vgstation13/pull/29839/files#diff-81254e3d7fd857cfe9223073092c4e1afd8869e9a827a5083826f7fb4fef0c1dR11) it has to be given a user and a held item (defaults to said user's active hand), and a series of ifs tries to recognize the item and decides how to deal with extracting color and min/max opacity off of it.
Adding spray cans would just be to add another if to the list, cast "held_item" to "spraycan", get it's color/s off of it to be added to the datum's palette, and set the datum's min/max opacity based on said held item.
Adding a bloodied hand or whatever would be something along the same lines too I guess, though involving user more heavily.

For wooden palettes (as in, the item) you'd have to have the "if" that detects the brush also check for wooden palette's on the user's other hand/s, and add their color list to the datum's palette.

This all reminds me, right now paintingTool.js is absolutely incapable of dealing with brush sizes, so you'd be painting one pixel at a time despite using a spray can. might be a TODO thing too.

**Comment by Eneocho** [comment]
This should probably be a draft for now.

**Comment by jellyveggie2** [comment]
Videos on how it works in-game as of right now, as promised:
https://streamable.com/b11ttj
https://streamable.com/y1oqrw

Also, a hopefully up to date HTML demo I used to use to mess around with code on the fly without having to compile or hotswap cache files while playing. Buttons look off wrong due to css hijinks (debug buttons don't have any css, those are fine). 
Download, extract, open canvas.html on a browser and click on any of the "init" buttons:
[canvas.zip](https://github.com/vgstation-coders/vgstation13/files/6682594/canvas.zip)

That's all from me for now.

**Comment by Eneocho** [comment]
Is there a way for there to be an overlay of which area are you painting a template? As in, you press a button and a blinking overlay shows you where are you painting, so you don't fuck up when painting over something you didn't want to paint.

**Comment by Eneocho** [comment]
Also, please add placing glass on top of the painting to stop anyone from painting further on it (unless they screw the glass pane off).

**Comment by Eneocho** [comment]
Possibly related: #18155

**Comment by Eneocho** [comment]
Once this is completed we'll need to revamp most of the non-medical reagent colours since most of em just use the default.

**Comment by Kurfursten** [comment]
Let us know if you come back and I will be more than happy to reopen this for you, just haven't heard any word in a while

**Pull request closed without merging**
