### PR TITLE
Adds lootboxes to the black market!

### PR DESCRIPTION
**Pull request by DrSnips**
[fun]
3gvkl0b

Sinister Loot Box
A Short Story
by Anonymous
Loot Box had always hated dirty Glasgow with its curly, chilly cliffs. It was a place where he felt surprised.
He was a sinister, popular, port drinker with chubby toenails and slimy thighs. His friends saw him as a melodic, mushy muppet. Once, he had even rescued a spotless toddler from a burning building. 

That's the sort of man he was.

Loot walked over to the window and reflected on his deserted surroundings. The sun shone like bouncing humming birds.

Then he saw something in the distance, or rather someone. It was the figure of Black Market. Black was a proud bear with squat toenails and curvaceous thighs.

Loot gulped. He was not prepared for Black.

As Loot stepped outside and Black came closer, he could see the abundant smile on her face.
"I am here because I want a pencil," Black bellowed, in a controlling tone. She slammed her fist against Loot's chest, with the force of 4890 kittens. "I frigging hate you, Loot Box."

Loot looked back, even more puzzled and still fingering the tiny piano. "Black, I just don't need you in my life any more," he replied.

They looked at each other with happy feelings, like two kindly, knobbly koalas boating at a very deranged wake, which had R & B music playing in the background and two thoughtful uncles jogging to the beat.

Suddenly, Black lunged forward and tried to punch Loot in the face. Quickly, Loot grabbed the tiny piano and brought it down on Black's skull.

Black's squat toenails trembled and her curvaceous thighs wobbled. She looked active, her body raw like a bad, better blade.

Then she let out an agonising groan and collapsed onto the ground. Moments later Black Market was dead.

Loot Box went back inside and made himself a nice glass of port.

THE END
Credit goes to https://www.plot-generator.org.uk/ for all of their help in this epic tale.
:cl:
 * experiment: Added Lootboxes to the black market.

### CODE REVIEW

**Comment by SonixApache** [comment]
on one hand it fits the black market for being rare and exclusive stuff
on the other hand it devaluates the black market as a whole, spreading the idea that it's just a dumping grounds for dumb shit and meme content

personally, i wish i had coded dumb shit so i could make meme PRs at every opportunity

**Comment by kilozombie** [comment]
Better have a 100% chance of dropping a weird purple item with particle effects (the particle effects are explosive projectiles)

**Comment by DrSnips** [comment]
You can start at any time.
I enjoy the concept of blackmarket but holy hell its background retarded. Why is the black market basically an authorized NT giftshop where command starts with one always?

**Comment by beesil** [comment]
Blackmarket gacha pulls whenst? I want my forbidden waifu

**Comment by SonixApache** [comment]
i agree that the command uplink is a very silly aspect of it
blackmarket has some definitely interesting avenues but the implementation isn't up to par yet

this isn't helping, though

**Comment by aceedex** [comment]
Fearful

**Comment by DrSnips** [comment]
Collabs continue to fear my code.

**Comment by tuypo1** [comment]
>collabs continue to fear my code

How about you fix the fucking dupe duck so they don't, I think it looked fun

**Pull request closed without merging**
