### PR TITLE
Role datums update to bleeding edge

### PR DESCRIPTION
**Pull request by MadmanMartian**
1052 commits difference, nice.

### CODE REVIEW

**Comment by ghost** [comment]
do it DO IT DO IT

**Comment by MadmanMartian** [comment]
H-h-here we go!

**Comment by PJB3005** [comment]
Why in the name of Linus Torvalds would you use a PR for this? Jesus man.

**Comment by SysadminJeroen** [comment]
@PJB3005 We must do it the Linus Torvalds way, email patches to a maintainer.

**Pull request merged**
