### PR TITLE
runtime hunting - Action.dm

### PR DESCRIPTION
**Pull request by ghost**
Any time you'd remove a mask, or anything that had an action button affiliated with it, it'd cause a runtime. Be it either it being force-unequipped or you just putting it down

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Review by PJB3005 — CHANGES_REQUESTED** [review]
No wait on second thought, shouldn't only things related to the button itself be behind the if? It should still remove itself even if it has no button.

**Comment by ghost** [comment]
Tried it, it ain't too nice, but if you're insisting

**Comment by PJB3005** [comment]
Slapping null checks around things is not always the solution. Just because it fixes the runtime doesn't mean the error is gone.

**Comment by clusterfack** [comment]
🤔 Why is this being called when something doesn't have a button?

**Comment by ComicIronic** [comment]
Only a few things I can think of - the action gets `Grant()`'d when it already has an owner, meaning it never makes a button, or it is somehow equipped without ever being `Grant()`'d, and the `Remove()` tries to access a button that wasn't created.

Or ref recycling.

**Comment by ComicIronic** [comment]
Actually, one thing could be that `equipped()` is never called for roundstart equipment, so it might be causing it.

**Comment by SonixApache** [comment]
are any of you going to resolve any of this

**Comment by Intigracy** [comment]
equip_to_slot_or_del() doesn't call equipped()?

**Comment by SonixApache** [comment]
are any of you going to resolve any of this

**Comment by chatsonf** [comment]
I don't think he's going to resolve any of this

**Comment by SonixApache** [comment]
it's over

**Comment by Intigracy** [comment]
Some action runtimes were fixed in a recent PR, and OP deleted his account, so.

**Pull request closed without merging**
