### PR TITLE
Parachad/Medivend changes

### PR DESCRIPTION
**Pull request by pwnzer185**
:cl:
 * rscadd: Paramedic gets surgery access out the gate
 * rscadd: NT updated their medivend with three (3) pill bottles each

### CODE REVIEW

**Comment by pwnzer185** [comment]
came later than expected, I was grabbing Mcdonalds for the last 2 days

**Comment by streaki** [comment]
we're slowly approaching the future where paramed is just a better MD/ MD flavor

**Comment by keonrastgoo** [comment]
Parameds are unable to fix internal damages without going to ghetto surgery. Theres an argument in that ghetto surgery is a necessary evil but I just dont see it that way.

**Comment by pwnzer185** [comment]
Parameds are the only med staff that cant fix internal damages, the only way for them is to either break into surgery, get the tools from cargo/science, or to do ghetto surgery. There might be an argument in doing those workarounds are a necessary evil but in my opinion they shouldn't be a hurdle

**Comment by ShiftyRail** [comment]
This is awfully powercrepe-y, and I say this as a paramedic player

**Comment by GreatBigFailure** [comment]
If we had more medical staff this wouldn't be necessary since paramedics are really just meant to get them to medical. But ya fuck give them access since it's not uncommon to only have paramedics not MDs

**Comment by Kurfursten** [comment]
I don't think there is enough public support for this right now, but I'm willing to move it to server poll.

**Comment by Kurfursten** [comment]
61-38 split in favor

**Pull request merged**
