### PR TITLE
Improved wizard cooldown logic

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
The cooldown formula is from TG, tested without problems.
:cl:
 * tweak: Wizard spell cooldown reduction logic has been improved, please report if there is anything wrong. Noticeably, blink will reach the minimum 0.5 seconds cooldown at the fourth cooldown upgrade, not at the third one.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Do not merge yet, some more testing with how spell cooldown shows up in the spellbook has to be done

**Comment by boy2mantwicethefam** [comment]
Everything's in order

**Comment by boy2mantwicethefam** [comment]
also do not merge this yet

**Comment by DamianX** [comment]
unatomic

**Comment by DamianX** [comment]
You say this is an improvement. The given example is blink having a higher cooldown on average? I don't hate it or love it, I just can't form an opinion on this if I don't know what this actually does and I think the onus is on you as the author to explain.

**Comment by boy2mantwicethefam** [comment]
@DamianX It's an improvement because the previous cooldown logic was flawed.
The important thing here is spell cooldown. By default there are four levels of spell cooldown and this is shared with Blink. The minimum cooldown is 0.5 seconds, which the cooldown reduction math is supposed to adjust for so that the fourth level would reach it. Due to the messy math that used to be in calculating the cooldown reduction blink would reach the minimum cooldown reduction at the 3rd cooldown upgrade out of 4, meaning that not only did it reach the minimum cooldown unintended but it also meant the 4th upgrade did nothing.
The ported TG formula is improved and fixes this.

**Comment by DamianX** [comment]
Sounds like this closes #17842, then.
I still don't know what the 3rd upgrade gives you in terms of CD reduction but I'm just going to assume it's something sane.
You should still split this PR into two, the file cleanup is not even related to cooldown.

**Comment by boy2mantwicethefam** [comment]
It doesn't fix #17842 because that's an issue stemming from something else. Namely that the spell goes on cooldown after casting mutate. There is already a fix for this I think, Deity incorporated it for cult wraiths where being jaunted doesn't start the spell cooldown.

**Comment by DamianX** [comment]
No idea what you're talking about but ok
split it

**Comment by boy2mantwicethefam** [comment]
Why?

**Comment by DamianX** [comment]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/CONTRIBUTING.md

**Comment by boy2mantwicethefam** [comment]
But I want to waste my time separating it into another PR for a reason that should prompt it, I've tested it and it's safe to say they don't break anything, except for the current spellbook which is going to be tested and I'm confident there was an issue when I last tested, which is why I asked for the do not merge tag.

**Comment by DamianX** [comment]
The spellbook code cleanup will have to get reverted together with this once we find out this breaks cooldown completely because of some condition you didn't factor in or couldn't test for (this is a hypothetical scenario).
This is the reason why unatomic PRs are bad.
That said, I have no interest in continuing this meaningless discussion. If another collaborator wants to merge this anyway they are free to do so, it's not a big deal, but you're still an asshole.

**Comment by boy2mantwicethefam** [comment]
I don't want to be an asshole, I'm just chronically lazy and it's an issue in my life

**Comment by boy2mantwicethefam** [comment]
I found some motivation and now I've separated the spell book clean-up from this PR, so now this PR is just the cooldown reduction. DNM can be removed because I wanted to test something related to spellbooks

**Pull request merged**
