### PR TITLE
Fixes Xenoarch artifacts anchoring forever

### LINKED ISSUE #7029: Large Artifacts become anchored
(WEB REPORT BY: alone REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 644acd3fcda003588b11e434f2574f51644671f6 
> 
> General description of the issue
> Large artifactss become unmoveable
> 
> What you expected to happen
> Artifacts are able to move
> 
> What actually happened
> Artifacts get anchored and unmoveable after a certain time
> 
> Steps to reproduce if possible
> Find a large artifact
> Leave it inside an area
> Don't touch or move it, leave it alone in a room for a while
> It becomes anchored and unable to move

### LINKED ISSUE #10149: Analyzing an artifact with an anomaly analyzer makes the last scanned artifact get anchored until admins fix it with VV.

### PR DESCRIPTION
**Pull request by 9600bauds**
I don't know what to write here
fuck

fuck

fuck

fuck

fuck

Fixes #7029
Fixes #10149

### CODE REVIEW

**Comment by 9600bauds** [comment]
Testing this was a pain in the ass because one artifact made N2O and I couldn't rejuv myself long enough to put on internals, the other one just fucking straight-up paralyzed me forever so I had to spawn myself as a test dummy

**Comment by clusterfack** [comment]
Wow you should learn to test things as a mommi its so much easier

**Comment by PJB3005** [comment]
Should've moved it to atom locking.

**Comment by 9600bauds** [comment]
I mean if I am going to refactor everything I touch it shouldn't lock at all

**Pull request merged**
