### PR TITLE
Cuts recurring pieces of maps down into fixed vault spawns

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[general]

## What this does
does this for stuff like the white ship, dj satellite, derelict teleporter, oldstation based derelicts, salvage shuttles, abandoned ai teleporter, and the deep space ruin with the hotline miami gear. none of these are set to rotate.
also converts all their windows to window grille spawners
makes non-overwriting map elements not change turf if the turf to change to is the same as the base turf (such as space, for vaults in space)

## Why it's good
easier on mappers trying to change stuff
the base turf check change should also boost startup times a bit with vault loading and make something like admin loading a space vault into the roid a lot easier and nicer looking

## How it was tested
roid station, checking the space gym and salvage shuttle
also the base turf change currently affects no random vaults

## Changelog
:cl:
 * tweak: Map elements loaded and not set to overwrite will now no longer overwrite turfs if the type loaded in is the base turf of the z-level
 * tweak: Many fixed location vaults in space such as the derelict are now loaded in during roundstart and can be turned off in the server config for faster startups.

### CODE REVIEW

**Comment by SonixApache** [comment]
hey you do know that certain maps have different stuff in those pre-spawned map elements right

**Comment by SECBATON-GRIFFON** [comment]
> hey you do know that certain maps have different stuff in those pre-spawned map elements right

been keeping my eye out for those, (which is why i made 3 different overlays on the salvage shuttle for different mob infestations, a version of the DJ sat without the lattice-grille tail and 2 different types of deep space ruin maps for the hotline miami and doomguy outfits) but i can double check. any specific ones you can think of? most other things i noticed were the locations of spacepod spawns changing slightly, and metaclubs abandoned ai teleporter looking different which made me leave it alone.

**Comment by west3436** [comment]
Agree that the same map-specific zlevels should remain but I'd encourage you to develop a system to pick a random version of each common map element per round in a separate PR.

**Review by west3436 — COMMENTED** [review]
Notes/questions:
- Do the DJ Satellite and Derelict still spawn in the same location in relation to each other?
- Medship is missing its starboard airlock

Please test a couple of things:
- DJ Sat spawns appropriately with the "tail" included
- misc_derelict_[east/west] spawns properly with both halves positioned correctly

**Comment by SECBATON-GRIFFON** [comment]
> Do the DJ Satellite and Derelict still spawn in the same location in relation to each other?

tested working

> Medship is missing its starboard airlock

only on the map renders, loads fine otherwise

> DJ Sat spawns appropriately with the "tail" included

tested working

> misc_derelict_[east/west] spawns properly with both halves positioned correctly

tested working

**Review by west3436 — APPROVED** [review]

**Comment by SECBATON-GRIFFON** [comment]
last 2 commits there touched the salvage shuttle, tested working

**Comment by SECBATON-GRIFFON** [comment]
changed it after the approved review again award agh sorry

**Comment by west3436** [comment]
Test merging this one for a week

**Pull request merged**
