### PR TITLE
Adds fat chemist jumpsuits

### PR DESCRIPTION
**Pull request by chatsonf**
"Fixes" #7116
Fat chemists now spawn in with a fat chemist jumpsuit ~~that currently has no texture~~.

~~If anyone has any issue with it having no texture please look at the top of #9139 for the other jobs that currently don't have fat jumpsuit textures.~~

<sub>also I didn't realise noir detective suits were a child of detective suits so I am also adding their texture to suit_fat.dmi</sub>

### CODE REVIEW

**Comment by carshalash** [comment]
You fucking cunt.

**Comment by chatsonf** [comment]
:grey_question: :grey_question: :grey_question:

**Comment by PJB3005** [comment]
This is better than no jumpsuit at all.

**Comment by gbasood** [comment]
> a fat chemist jumpsuit that currently has no texture.

Wait do you mean it wont have an icon on the body or what

**Comment by Shadowmech88** [comment]
I think he means that it'll have that "textureless" purple and black checkered icon, for jumpsuits that have the ONESIZEFITSALL flag, but don't actually have a sprite for their fat version.

**Comment by ghost** [comment]
I guess that's better than nothing, but could we really not draw them ?

I did two last time on request

**Comment by chatsonf** [comment]
I'd rather have fat chemists have a "textureless" purple and black checkered suit at round start than have them start out with nothing while we wait for someone to actually sprite it, especially since this bug has been around for half a year. 

If someone makes a sprite for the chemist jumpsuit I'll add it into this PR, but until then, this PR is what it is.

**Comment by chatsonf** [comment]
Alright thanks to Niggly (AND ONLY NIGGLY I WAS JUST GOING TO LET THIS SIT HERE FOR ETERNITY) you guys get what you want and get a fat chemist sprite to go with the ability for fat chemists to have clothing at the roundstart.

**Pull request merged**
