### PR TITLE
from input menu to radial menu, switchtool

### PR DESCRIPTION
**Pull request by jjpark-kb**
Note: A few things had this radial check that could have been shared, so that is also included in this PR due to this PR touching radials.
Link to when I posted pictures:
https://discordapp.com/channels/239820742823378944/239823463802470400/788947771246903317
:cl:
 * rscadd: Switchtools now use radial menus

### CODE REVIEW

**Comment by Dacendeth** [comment]
Does the old way still work?

**Comment by jjpark-kb** [comment]
> Does the old way still work?

no, entirely replaced.

**Comment by PrimeDSS13** [comment]
post pictures in the OP

**Comment by jwhitak** [comment]
This replaces the old menu, so anyone on hotkeys using "z, KEY, enter" to quickly swap between tools will no longer be able to do so. Also, with the advanced surgery tools in a switchtool, it won't be clear which function is engaged. (Ex: is the scalpel that's inserted on cautery or scalpel mode?)

I'm recommending not to merge. Sorry, jjpark-kb. It looks great, but it'll ultimately be inferior to current implementation, utility-wise.

**Comment by BomberBro** [comment]
I'd wager most doctors don't even know about that function, and I'd rather have the utility over losing it. Ideally you could press a key anyway to pick the radial and nothing changes as well, but this change makes mega shit switchtools like the joke of an engineering tool actually decent. Needs images too

**Comment by DamianX** [comment]
radial bad

**Comment by StreptoMutans** [comment]
If you have no idea what the individual advanced tools do and look like, the current menu at least gives you a hint what step the tools perform. 
How does the radial menu approach this issue?

**Comment by ghost** [comment]
please at least just make this an alt-click option

**Comment by Sooose** [comment]
Please no, radials may look nice but I'd rather not lose the old functionality for something that is in everyday use worse.

**Comment by PrimeDSS13** [comment]
put real pictures in the OP not a discord link

**Comment by Kammerjunk** [comment]
post actual images dumbo
image

**Comment by jjpark-kb** [comment]
Im going to close this for now.

The plan is to give the switchtools radials, but only on alt-click. This would preserve the original input menu as well as give an alternative radial menu to those who wish to decide between the two.

**Comment by DrSnips** [comment]
I honestly don't get what people's issue is with this. As the person who coded the holotool I think the list menu is utter dogshit. Also if you don't know what the advanced tools do, why are you getting the advanced tools and furthermore replacing them in the switch tool?

**Comment by DrSnips** [comment]
There's a whole lot of downvotes but not a whole lot of reasoning behind them.

**Comment by Sooose** [comment]
Because having to click a location is more annoying that knowing what keys to press to get the tool you want. Not to mention this is going to slow down surgery as you have to needlessly take your mouse off the body you're working on to select another tool. If you want to merge this and preserve the original functionality I would recommend making a toggleable mode for the switch tool that lets you change the default functionality of the use action to this instead.

**Comment by DrSnips** [comment]
The mouse movement is only ~1 tile away. I think it's pretty safe to say it's negligible.

**Pull request closed without merging**
