### PR TITLE
Adds hatchets to the autolathe.

### PR DESCRIPTION
**Pull request by Eneocho**
You can print hatchets with metal handles that are clearly inferior (identical statswise) to the wooden handle ones.
This does not affect game balance since you can buy hatchets from the merch vendor (they're inside the swiss army knife) and the two areas with autolathes have access to way stronger weapons.
### What this does
Adds hatchets to the autolathe.
### Why it's good
Gives you another way to get a hatchet, gated behind autolathe access. 
Will also help contain the occasional kudzu/powercreep/biomass since cargo/science can quickly print and distribute them.
[content]
:cl:
 * rscadd: Hatchets on the autolathe, complete with a metal handle icon that displays the inferiority of mass produced tools.
 * tweak: Swiss army knife hatchets use the metal handle variant now. No change statwise, only difference is the icon and description when taken out of the switchtool.

### CODE REVIEW

**Comment by Kharkov72** [comment]
also before anyone says AIIIIIE POWERCREEP they could already print knives

**Comment by Dacendeth** [comment]
Hatchets are better than knives though.

**Comment by jwhitak** [comment]
Just buy your switchtool from the merch computer already. We already power creeped far past this. That said, this gives access to chopping tower caps as a miner. Too bad tower caps aren't on the weeds list...

**Comment by jwhitak** [comment]
We've powercreeped far past this already - just buy your swtichtool at the merch computer and be done with it.

That said, this gives a source of cutting tower caps to the extremely rare space hobo botanist. Turns out there's not many things that can chop down tower caps. Then again, the lathe can already print circular saws, so actually this doesn't change much at all.

**Comment by Eneocho** [comment]
>Too bad tower caps aren't on the weeds list...

But they are.

**Comment by Killette2** [comment]
Ok but I'm still making the pipe tomahawk instead

**Pull request merged**
