### PR TITLE
Hardsuit port [DNM]

### PR DESCRIPTION
**Pull request by ririchiyo**
Porting the hardsuit changes/ninja refactor that bay did from: https://github.com/Baystation12/Baystation12/pull/7008

### CODE REVIEW

**Comment by SkowronX** [comment]
Happening

**Comment by kilkun** [comment]
So wait, the module hardsuits, recoded ninja and voidsuits are all getting ported? I can't wait to hear the vague complaints people will voice when it's finally ready to merge.

**Comment by AutismSpider** [comment]
This recodes and take lot of ninja suit stuff out making it useless.

Dear lord what is this chem shit with the suits.

This needs to be tested badly

**Comment by ririchiyo** [comment]
Maybe you should actually look at what it does, AutismSpider.

**Comment by IratePirate** [comment]
Make sure you test this in advance. We don't want another Saycode fuck up.

**Comment by Midaychi** [comment]
If this adds most of the RIG and Voidsuit changes from bay then it might be pretty cool. They basically renamed hardsuits to voidsuits and made them space-pajamas, then took the RIG suits and made them into mini-mechs.  You put them on and initialize, they have a battery power reserve and can mount modules ranging from a datajack to magboots to a grenade launcher, etc. They still have the whole rupture and burn system bay hardsuits have had forever, and they're weak to emps, but looks like neat fun (especially for nuke ops).  Seems a little overpowered though and might need some balancing.

**Comment by Midaychi** [comment]
Speaking of RIG suits basically being mini mechs, would it be far-fetched to port mechs to the RIG system?

Could call them Heavy Rigs, and port the mech equipment over to be heavy rig only. Robotics builds the frames and installs the equipment, and they'd basically be rigs but access to heavy rig modules and better armoured/slower.

Ripley goes from a vehicle to being a spacesuit upgrade.

**Comment by Exxion** [comment]
>Space suit helmets function as internals
Yes. That means that, among other things, the Deathsquad command beret or whatever it is could be used WITH a cigar for at least 100% more badassery.

**Comment by Zuhayr** [comment]
Hardsuits are still buggy as shit on Bay for the record. Might want to leave it a few weeks.

**Comment by SkowronX** [comment]
So how's the progress?

**Pull request closed without merging**
