### PR TITLE
Allows you to eject your PDA's pen by alt-clicking it while in your inventory

### PR DESCRIPTION
**Pull request by 9600bauds**
I don't know what's up with the pizza thing

### CODE REVIEW

**Comment by 9600bauds** [comment]
fast merges and "needs final decision" will come to you, but ONLY if you comment "ty eggman of coding"

**Comment by PJB3005** [comment]
Would be nice if we could get the same thing but for PDAs.

**Comment by 9600bauds** [comment]
???
But this already is for PDAs

**Comment by PJB3005** [comment]
Ah fuck I ment IDs.

**Comment by 9600bauds** [comment]
Maybe tomorrow

**Pull request merged**
