### PR TITLE
Creatine Last Stand pills for nuke ops

### PR DESCRIPTION
**Pull request by SonixApache**
30 creatine, 5 oxycodone, 5 dexalinplus, 5 hypozine, 0.4 mednanos and 4.6 combatnanos
For about a minute of extreme punching action
also 100 PRs milestone finally

🆑 
 - Tweak: The 50u Creatine pill usually supplied to syndicate nuclear operatives has been modified to also rejuvenate it's user a bit.

### CODE REVIEW

**Comment by Diavill** [comment]
not even the greatest elixir can stop your teammates from RPGing you

**Comment by SonixApache** [comment]
True, but if you get your dumb ass shot into crit by sec one of your buddies can (try to) give you one more chance to fuck some shit up.

**Comment by Shadowmech88** [comment]
If you tweak the amount of creatine a bit, you could get nearly 10 minutes of hulk instead of only one.

**Comment by SonixApache** [comment]
Yeah, but then the hypozine'd kill you after five. This is really just to get someone out of crit and give them one more chance to fuck shit up.

**Comment by carshalash** [comment]
Bretty good

**Pull request merged**
