### PR TITLE
Adds Maintenance Access to CMO

### PR DESCRIPTION
**Pull request by DorainGrey**
[tested] [gameplay]
## What this does
Adds maintenance access to the CMO role.

## Why it's good
Very useful for Solo or undermanned Medbay, Since it allows you to collect bodies without the need for a paramedic. 
It's also weird for the CMO not to have all the access of their subordinate roles.
Also encourages people playing Head, which is good for the server.

## Changelog
:cl:
 * rscadd: Adds maintenance access to the CMO role.

### CODE REVIEW

**Comment by Kurfursten** [comment]
👍 for head benefits

**Comment by bathosbathtime** [comment]
This makes RDs inconsistent as the only head without maintenance access despite also having a subordinate who does (mechanic) but I hate science so I am fine with that.

**Comment by BomberBro** [comment]
Collecting bodies should be something only a truly deadpop CMO should care about, and they'd have the spare by that point or access changes. The more time he spends in maint is more time he spends not doing anything in medbay so he can do a job any assistant can handle with similar access.

**Comment by PrimeDSS13** [comment]
Why do CMOs have to be crawling around in maintenance? Finding bodies has never been an issue with the combination of suit sensors, radio screaming, paramedics, and even just random maintdwellers: in the end this just feels like unneeded accesscreep and a further push to homogenize all the access in departments for some reason.

**Comment by PavelCIA** [comment]
Big Medbay lobbying for more powercreep. Disgusting.

**Comment by WindowsErrors** [comment]
space station 13 players will truly get controversial and tribalistic over the strangest things

**Comment by Hinaichigo** [comment]
I like the idea of it being beneath the CMO's paygrade to scoop gore out of the maintenance ducts.
RD and CMO not having maint access sort of suits their positions.
Then again it does makes some sense for them to have maint access if they're "officers" in a naval sense. 
That being said, as I consider them more as civilians, and also vibe wise, I prefer the former situation.

**Comment by PavelCIA** [comment]
We should've just went with the PR that removed maintenance access from everyone

**Comment by Exxion** [comment]
>We should've just went with the PR that removed maintenance access from everyone

It's funny because this is a config option and it's actually on by default

**Comment by Dacendeth** [comment]
>It's also weird for the CMO not to have all the access of their subordinate roles.

Then why arnt you giving them external airlock as well?

**Comment by wotisjanitor** [comment]
on that note, remove brig medic and orderly

**Comment by Kurfursten** [comment]
Orderlies are good, brig medics are the ones who are superfluous

**Comment by Theophrastus1** [comment]
remove brig medics, they should have never been a role and instead should have just remained a gimmick

**Comment by aceedex** [comment]
Isn't brig medic just a paramed alt job that doesn't do anything different?

**Comment by wotisjanitor** [comment]
> Isn't brig medic just a paramed alt job that doesn't do anything different?

It gets brig access and makes no sense as a job

**Comment by aceedex** [comment]
Parameds have had brig access forever U donut
neither do clowns

**Comment by Kurfursten** [comment]
> Isn't brig medic just a paramed alt job that doesn't do anything different?

They spawn with a loyalty implant + medsec headset + reduced chance for antag roles as sec, command, and merchants do. All paramedics have frontal brig access, not just brig medics.

**Comment by aceedex** [comment]
> They spawn with a loyalty implant + medsec headset + reduced chance for antag roles as sec, command, and merchants do

whack

**Comment by wotisjanitor** [comment]
Mr. Kurfurst, close this PR.

**Comment by tomacatx2** [comment]
i offer you an alternative : the CMO offers to pay an assistant or somesuch credits to retrieve bodies
this generates interaction (having to talk with the designated corpse monkey, haggle about price), fun times (the designated corpse monkey looting the body and getting into trouble) and maybe even paperwork if the corpse monkey wants to ratify their new payroll or if they want access changes to fit their new job

**Comment by Kurfursten** [comment]
The emojis have spoken on this one

**Pull request closed without merging**
