### PR TITLE
Clean up some old files

### PR DESCRIPTION
**Pull request by adacovsk**
Came across some old files that are rather obsolete. We have a cargo system that handles Centcomm requests now that provides payments, which should be separate from objectives. The chef's jecties seem like a good approach to do things if someone was willing

If anyone is aware of other files which seem unused, I can try to remove them too, compile, and test

## What this does
Removes these old files

## Why it's good
Remove clutter

### CODE REVIEW

**Comment by adacovsk** [comment]
wtf

**Comment by WindowsErrors** [comment]
keep it up, 3 kilobytes isn't going far enough

**Comment by adacovsk** [comment]
> keep it up, 3 kilobytes isn't going far enough

work in progress

**Comment by Eneocho** [comment]
https://www.youtube.com/watch?v=xtrqYdvZ29E&t=110s

**Pull request merged**
