### PR TITLE
Radio headset sounds

### PR DESCRIPTION
**Pull request by west3436**
Radio headsets will now make a radio chatter sound after a message is sent or received. Configurable to have all sounds, no sounds, or only a sound on transmission and not receipt of a message. Default setting is sounds on transmission only.

:cl:
 * rscadd: added a setting to enable radio chatter sounds at the end of transmissions or on receipt of a message.

### CODE REVIEW

**Comment by WindowsErrors** [comment]
reminds me of the days when beestation first added this but there wasn't an option to disable the noise that they had to hotfix in after 40 minutes because all the sound in the game was drowned out by the 85 primetime players all using the radio at the same time in a torrential downpour of **kssht kssht kssht ksshtkshht kssht kssht ksshtksshtkssht kssht kssht kssht ksshtkshht kssht kssht ksshtksshtkssht kssht kssht kssht ksshtkshht kssht kssht ksshtksshtkssht kssht kssht kssht ksshtkshht kssht kssht ksshtksshtkssht kssht kssht kssht ksshtkshht kssht kssht ksshtksshtkssht kssht kssht kssht ksshtkshht kssht kssht ksshtksshtkssht kssht**

**Comment by DamianX** [comment]
I like it but I don't think everything needs to have a toggle in the preferences. As long as the sound is not too annoying, I would prefer there wasn't an option to disable it.

**Comment by Exxion** [comment]
God no that sounds fucking awful please keep the preference

**Comment by Eneocho** [comment]
Sounds like shit and would drown the peanuts sounds when speaking.

**Comment by Hinaichigo** [comment]
Can you hear other people's radio headsets or just your own?

**Comment by west3436** [comment]
> Can you hear other people's radio headsets or just your own?

Only your own regardless of setting

**Comment by bathosbathtime** [comment]
do you have any idea how often radio messages are sent

**Comment by west3436** [comment]
> do you have any idea how often radio messages are sent

Yes and some branches have these sounds on every message by default. This only makes the sound when you send a message when using the default config.

**Comment by pedr69** [comment]
make it a thing for stationbounced radios only, during primetime it would just be KHRRKHRHKRRRHHRHKKRKH

**Comment by west3436** [comment]
> make it a thing for stationbounced radios only, during primetime it would just be KHRRKHRHKRRRHHRHKKRKH

Just toggle it off if it gets annoying. Once again, the default setting is only to make a sound when you transmit. Do people read these PRs beyond the title?

**Comment by pedr69** [comment]
yeah i misread it my bad

**Comment by west3436** [comment]
[donotmerge] until I get the sql stuff added properly

**Comment by Eneocho** [comment]
> [donotmerge] until I get the sql stuff added properly

You could press the convert to draft button.

**Comment by TGFH** [comment]
This is a good idea and anyone that says otherwise has never played on a server that already has this.
Unless the sound is really annoying or something it quickly just becomes background noise that you won't really notice. It's a toggle anyway so if it rubs your autism the wrong way you can simply turn it off.

**Comment by bathosbathtime** [comment]
So we should add this because we'll learn to ignore it? How is this in any way not just an annoyance added to make you dig into the settings to turn off IF you even know that is an option?

**Comment by west3436** [comment]
> So we should add this because we'll learn to ignore it? How is this in any way not just an annoyance added to make you dig into the settings to turn off IF you even know that is an option?

The votes would imply that people don't see this as an annoyance. You have to "dig into the settings" just to set job preferences. No need to make a mountain of a molehill.

**Comment by ValkyrieSkies** [comment]
So long as it's set to off by default, it could be neat. A neat idea for expansion could be to have different types of sound effect the player can toggle in the settings so they can choose between the likes of a "kshht" or a walkie-talkie bleep and the like.

**Comment by Exxion** [comment]
The votes don't say anything about whether or not people would think it was an annoyance. For example, even though I think it would be fucking awful, I didn't vote because you can turn it off.

**Comment by west3436** [comment]
Don't understand the SQL stuff at all and there isn't any way to test it since it's seemingly on the secret repo, so please review this for accuracy @DamianX

**Comment by BurntDevil** [comment]
The only way this works is if you shitcan common channel. Something we should have done anyway.

**Comment by Kurfursten** [comment]
@DamianX what do you think?

**Comment by DamianX** [comment]
I went ahead and begrudgingly fixed the database part for you.
@west3436 It will not work locally for you and only you, until you fix your database: migration 28 that you added didn't do the right thing, but it's now marked as executed, so my changes to it will not happen.
I suggest you just delete your local `players2.sqlite` file.

**Comment by west3436** [comment]
> I went ahead and begrudgingly fixed the database part for you. @west3436 It will not work locally for you and only you, until you fix your database: migration 28 that you added didn't do the right thing, but it's now marked as executed, so my changes to it will not happen. I suggest you just delete your local `players2.sqlite` file.

Awesome, much appreciated. So I need to delete that then push or just for when this is merged I'll have to delete it for it to work on my end?

**Comment by Kurfursten** [comment]
Thank you Damian

I for one welcome the chshsh for one week before everyone toggles it off

**Comment by DamianX** [comment]
> Awesome, much appreciated. So I need to delete that then push or just for when this is merged I'll have to delete it for it to work on my end?

The latter.

**Pull request merged**
