### PR TITLE
Prevents pulse demon from firing

### PR DESCRIPTION
**Pull request by Dacendeth**
## What this does

Basically prevents pulse demon from firing automatically.
## Why it's good

General complaints to remove this, a "minor" antag that has the power to end the round, the primary way to counter it just feels cheesy and boring and make rounds feel unfun to play on both sides (turning off power for 20 mins)
## Changelog

:cl:

 * rscdel: Prevents Pulse demon from randomly firing.

### CODE REVIEW

**Comment by kilozombie** [comment]
I don't like Pulse Demons at all and think they need to be put into a more fun state. Mostly right now they are an unseen and unknown annoyance that can end your round out of nowhere. The counters feel counter-intuitive, if you get my joke.

**Comment by djkramer123** [comment]
It'd be nice to see them given a bit of love, but they're pretty wack currently

**Comment by nervere** [comment]
Turning power off doesn't even work, by the time the pulse demon is found out they can cable hop or self-sustaining charge to somewhere that does have power, like an SMES. (all of them never get turned off)
Ion gunning them is very powerful and at high power levels, pulse demons are very easy to notice with a huge yellow glow.
Unironically crew just needs to adapt to the correct strategies to combat them, they're not well-designed but also not hard to kill.

**Comment by hacker-on-steroids** [comment]
they are very hard to kill if there isn't an AI

**Comment by Dacendeth** [comment]
Killing them with ions is very tough, you need to hit them 4 times and hope they don't zip away and fully regen after 10 seconds. Also hitting them with ions is tough as the projectile just flies over them so you need to land your shots at walls near them or click them directly which is impossible if they're under a floor.

**Comment by kilozombie** [comment]
Yeah I mean if the crew doesn't have ions what do they do

**Comment by angryturnip** [comment]
simply pick them up and put them in a mouse cage!

**Comment by SECBATON-GRIFFON** [comment]
suggesting balance changes here: #36585
PR that fixes issues here: #36587

**Comment by west3436** [comment]
Too close to call it one way over the other. #36587 has some balance improvements, so we'll let that cook for awhile before trying this again.

**Pull request closed without merging**
