### PR TITLE
box bridge disposals

### PR DESCRIPTION
**Pull request by brndd**
I don't know why this wasn't done. It was literally 4 pipes.

:cl:
 * rscadd: boxstation bridge now has disposals instead of a lame trash compactor

### CODE REVIEW

**Comment by kilozombie** [comment]
It used to be a disposals pipe, then it was made into a trash compactor so you can't be a greyshit and escape the bridge through disposals.

This was intended and a feature.

**Comment by brndd** [comment]
What a stupid feature. Literally every single other map has disposals on the bridge. If anything, being able to escape through it is a feature.

**Comment by ghost** [comment]
If we don't want people using Disposals to escape, then literally just re-add disposals travel damage

**Comment by robosperg** [comment]
it was added for secure trashing of things with the bridge rework PR

**Comment by brndd** [comment]
https://github.com/vgstation-coders/vgstation13/pull/19436

This is the bridge redesign PR and nowhere does it say it's a feature. At the time the person who did the redesign had a very kryptonite kind of relationship with disposals (the reason I got on board with mapping Roidstation was that the existing Roid mappers, who BurntDevil was half of, could not for the life of them figure out disposals and were contemplating just replacing them with trash compactors).

It's for that reason I'm inclined to believe it was put there out of (for lack of a better word) incompetence rather than as a deliberate design choice.

Though I suppose I could just ask him, whatever little the original reason for it being there counts for.

Edit:



Dare you go against the \~VISION OF THE CREATOR\~ ...?!

**Comment by BurntDevil** [comment]
Routing the disposals wasnt exactly hard for the bridge project, I opted not to do it. It is different on roid, there was alot of junction stuff I didnt fully understand at the time. For box bridge, I specifically put the compactor on there as:

1. secure disposal of items
2. prevent that use as an escape vector
3. provide an on station compactor for emagging as boxed lacks any of them

Its intentional. Do what you will with that in mind.

**Pull request merged**
