### PR TITLE
Removes minor and major crime fields from the security database, improves visibility of comments field.

### PR DESCRIPTION
**Pull request by despotate**
**Now: shift click, see wanted status. Click view records, see major/minor. Click view comments, see comments.**
**This PR: shift click, see wanted status. Click view records, see comments.**

See https://github.com/vgstation-coders/vgstation13/issues/14531

Simplifying security recordkeeping should improve the quality of the server's security players and their ability to communicate with each other and with criminals. Less shitcurity, less confusion.

Example secHUD usage:

> This is  Ricky Richards!
> He is wearing  a captain's jumpsuit. It has  a medal of captaincy.
> He is wearing  a captain's hat on his head.
> He has  a captain's backpack on his back.
> He is wearing  some brown shoes on his feet.
> He has  HUDSunglasses covering his eyes.
> He has  a captain's headset on his ears.
> He is wearing  Ricky Richards's ID Card (Captain).
> Criminal status: [None]
> Security records: [View] [Add comment]
> Has weapon permit.
> *---------*
> 
> Name: Ricky Richards Criminal Status: None
> 
> Notes: No notes.
> 
> Comments:
>
> Made by Ricky Richards (Captain) on Mon Apr 24 11:57:52, 2561
> ehs a pretty cool dude and doesn't afraid of anything
> 
> Made by Captain (Captain) on Mon Apr 24 11:58:43, 2561
> arrest this man at once
> 
> [Add comment]

Tested on secHUD and sec records computer. Also affects pAI secHUD and a few other bits and bobs, untested but the code changes are mostly the same for those.

:cl:
 - rscdel: Removed the minor and major crime fields from the security database.
 - tweak: Improved visibility of the comments field.

### CODE REVIEW

**Comment by despotate** [comment]
Also why does the add comments thing even display real world time in the comment instead of station time?

**Comment by Riekland** [comment]
I really really don't like this change but I can't articulate my issues at all so I guess I'll say go for it and just cry myself to sleep in a pile of paperwork

**Comment by Chazach** [comment]
So you can add comments straight from the secHUD?

**Comment by Theophrastus1** [comment]
stay the fug out of security nerd, i regularly use those and so do a lot of folks who play sec. It helps to determine whether someone is kill on sight or apprehend. Plus it's nice to list out all their crimes. Seems unnecessary as shit to remove the major/minor fields.

**Comment by bisousbisous** [comment]
Is this DCSS now where we unnecessarily remove """""""""""""bloat""""""""""""" under the guise of streamlining the game? There is no reason for this change and I have not heard anyone complain about this.

**Comment by despotate** [comment]
Yes, you add comments straight from the secHUD.

Think of this as having the existing, timestamped, named comments field (which already exists) replace the four different minor/major crime details fields which are subjective as fuck.

If someone's super valid an officer will add that in a comment in all caps. If someone has a list of crimes then you would prefer reading all of those chronologically with details as to who reported them etc instead of jumbled together with no context.

I complained about this in the https://github.com/vgstation-coders/vgstation13/issues/14531 issue with many reasons why. Some people agreed.

**Comment by Kammerjunk** [comment]
\*unzips change*

**Comment by Chazach** [comment]
@despotate Do any of the comments appear from purely inspecting someone or is it all behind the [View]? I think what @Theophrastus1 was raising an issue with is that with the old system you could set their crime to "MURDERER KILL ON SIGHT" and that would appear directly on shift-click allow for streamlined valids collection. Perhaps have the last comment appear directly upon inspection?

**Comment by despotate** [comment]
The last comment is going to be at the bottom of the chat window since, well, it's the last comment. So if you need to quickly validtest someone just have your eyes jump to the bottom of the chat window, which is actually more convenient than right now where you have to jump to about one third of the distance away from the bottom towards the top.

Let me clear up the difference between now and in the future:

Now: shift click, see wanted status. Click view records, see major/minor. Click view comments, see comments.
Future: shift click, see wanted status. Click view records, see comments.

In either case it's going to be 1 click for stuncuff valids and 2 clicks for laser valids.

**Comment by Theophrastus1** [comment]
@despotate Would you not just be able to make the Major/Minor lines appear when examined? Or better yet, keep the Minor/Major fields and add an additional field for the medium crimes list. The comments list shouldn't be for placing crimes, it should detail exactly that, comments on the arrest made. 
 For example:
Minor: Breaking and Entry, Possession of Contraband
Medium:
Major:
"Urist McGreyshit was breaking into engineering. Subject was apprehended and contraband found on his person." -Head of Security Phallus

Now, with _just_ comments it could get jumbled when you have several people editing them, as sometimes that happens, and it might end up looking like one big block of text instead of separate things. The average officer doesn't need to know exactly why he's wanted, he just needs to know the crimes and appropriate level of force to respond to it with. Removing those fields kind of also is detrimental to someone who might not have space law memorized, and doesn't know that he should watch out. Also, at the bare minimum i feel that having the fields separate from the comments will at least allow some players to put in the crimes at the very least, they don't have to be in the right field, but they are there to see. Most sec officers aren't the type to sit down and type out why urist mcgreyshit did what he did, usually it's for the Warden or HoS to handle.

I just fail to see why removing the current format for the sec records is needed, as opposed to improving the existing system.

**Comment by Riekland** [comment]
Oh I remembered my issue
You can set someone to arrest and add a crime and description of it as anyone with a valid sec ID on a console, but you don't get your name logged when doing so
If comments are the only thing that let you inform officers what some cunt did wrong, you can't misuse it as a clown or whatever to make people set to arrest with reasonable crimes so they're out of the road
This is important because there's no better way to fuck with sec than setting people to arrest AND actually giving a reason for the arrest in their records

**Comment by despotate** [comment]
Seven fields isn't worth it and I don't understand the advantage of of having m/m/m fields at all. In your example, this line

>  Minor: Breaking and Entry, Possession of Contraband

is actually unhelpful. Crimes themselves should only be decided when sentencing _after_ all the information is gathered once they're arrested: maybe someone used their ID, maybe they had permission for the contraband, maybe there's extenuating circumstances, maybe they trespassed instead of breaking in, etc., and writing down the crimes they committed after they're spotted and before they're arrested makes no sense to me.

In comments, this would be a clear-cut case:

> X was spotted doing Y
> X was brought in and charged with Z after we found out A from him and found B in his pockets

Reading these comments you immediately know that this guy has been arrested, released, and served his time fairly. I can't think of a situation where the m/m/m fields would be worth their weight in space that would make this _more_ clear, rather than _less_ clear.

> Now, with comments it could get jumbled when you have several people editing them, as sometimes that happens, and it might end up looking like one big block of text instead of separate things. 

You can't have multiple people edit the same comment. You might be confusing this for the "important notes" field which is just persistent flavor text (and I didn't remove it).

> The average officer doesn't need to know exactly why he's wanted, he just needs to know the crimes and appropriate level of force to respond to it with.

This is the meat of the utility of the m/m/m fields to me but this really more justifies a custom "level of response" or "threat level" field rather than the six fields you're suggesting. I'm fairly sure that at the moment SOP dictates that the response to seeing wanted people is to take into account the surroundings and what the wanted person looks like, rather than the severity of the crimes that you quickly shift-clicked and view recordsed. I can see the very mild advantage in reaction to wanted criminals offered by the current system but I don't view it worth all the huge amount of disadvantage that they give in return.

**Comment by despotate** [comment]
@Riekland, I see anonymous security records as an unintended oversight rather than something explicitly allowed for honking. Personally I think that getting or creating a sec ID is the proper gatekeeping required to honk with arrest records, which are a very high-value database and very, very important to the round.

**Comment by Riekland** [comment]
I think that having the ID name come up is a step too far. I'm on the opinion that the best way to find out who's been spoofing records is to either catch them in the act or have the detective scan the consoles. I just don't think making it easier for sec is a good idea, even though I like the concept of an easier life personally

**Comment by Theophrastus1** [comment]
> @Riekland, I see anonymous security records as an unintended oversight rather than something explicitly allowed for honking. Personally I think that getting or creating a sec ID is the proper gatekeeping required to honk with arrest records, which are a very high-value database and very, very important to the round.

Come on man, that's a little bit much. In reality, if you leave a terminal logged in under security credentials, and someone accesses it who doesn't have the proper access, then it's your fault entirely. Shouldn't make it have to be that much harder because you feel they're an "unintended oversight"

**Review by PJB3005 — APPROVED** [review]

**Comment by gbasood** [comment]
changelog then merge

**Comment by Intigracy** [comment]
changelog then merge

**Pull request merged**
