### PR TITLE
Ancient Astronauts

### PR DESCRIPTION
**Pull request by Arthurdentist**
space man

Adds this space suit to the game. It can be found through xenoarcheology. Nothing particularly fancy really.

### CODE REVIEW

**Comment by Arthurdentist** [comment]
wew conflicts

**Comment by ghost** [comment]
That is pretty cool.

**Comment by Arthurdentist** [comment]
feel free to use the icons if you want.

**Comment by Arthurdentist** [comment]
merge conflict should be fixed now

**Comment by gbasood** [comment]
:+1:

**Comment by Ephx1** [comment]
Does it make you slow as hell?

**Comment by Arthurdentist** [comment]
nah it doesn't. Its basically just a normal space suit like the ones you can get in telescience.

**Comment by Ephx1** [comment]
Oh well, neat nonetheless :+1:

**Comment by Arthurdentist** [comment]
this space suit now offers slightly better protection then the xenoarcheology space suits do. It isn't a great space suit still by any means but it is now marginally better then the starting Xenoarch's suit. This gives Xenoarchs a reason to wear it if they put in the effort of finding it. 

It gives very basic protection to each form of damage, 50 protection to bomb damage (useful on the asteroid) and bio and rad protection in line with the Xenoarch Suit. 

This should be ready to merge (if) it passes these checks.

**Pull request merged**
