### PR TITLE
Revert "Goonchat UTF-8 support and better string highlighting."

### PR DESCRIPTION
**Pull request by clusterfack**
Reverts d3athrow/vgstation13#11428

### CODE REVIEW

**Comment by clusterfack** [comment]
A few messages in it started spitting out black gibberish of everything connected by %20 and such. Relogging fixed it but this needs to be tested so it doesn't FLIP out randomly for people.

**Comment by DrCelt** [comment]
it didn't on my machine :tm:

**Comment by Iamgoofball** [comment]
cyka blyat

**Comment by PJB3005** [comment]
God I fucking hate internet explorer.

**Pull request merged**
