### PR TITLE
Monkey forms for skeletons, plasmamen and greys, vox monkey form improved

### LINKED ISSUE #6767: Vox Turned Into Chickens Cannot Be Put Back
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 1709a73bdc6abd9f34226e682770357271f0ae46 
> 
> General description of the issue
> Vox turned into a chicken cannot get turned back.
> 
> What you expected to happen
> I expected them to turn into a vox when injected with the right SE.
> 
> What actually happened
> The injector disappeared, and the vox remained a chicken.
> 
> Steps to reproduce if possible
> Turn vox into chicken.
> Get SE to turn it back into a vox.
> Click chicken with SE
> SE disappears, no message, vox is still chicken.

### LINKED ISSUE #8403: Greys don't have their own monkey form
Monkifying a grey just makes a regular monkey. Missed opportunity for little green men in my opinion. 

Possible sprites to use for little green men:  http://s000.tinyupload.com/?file_id=20439507724043695414
heylaughingmyarseoff
Now with less rage inducing off green outlines!

I also know Niggly has one that could be used instead.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #6767 fixes #8403

With sprites provided by Niggly and splicing existing sprites, 3 new monkey forms (Skeleton, Plasmaman, and Grey) are added.

Skeleton monkey forms are skulls that hop when they move 
skull

Plasmamen monkey forms are flaming hopping skulls
flaming_skull

Grey monkey forms are big-headed monkey things
grey

Also, fixes vox chickens a little

> Now only have 1 hand slot, their beak
> Methylin means something now, letting them pick things up
> There's a proper check for amount of eggs left, whereas previously there was not
> Vox chickens now lay eggs if they're idle or not

### CODE REVIEW

**Comment by ghost** [comment]
Current bugs

Greys and skulls wave their tails and such

**Comment by CptWad** [comment]
>Monkeying a skeleton kills the skull when it forms because brute multiplier

working as intended

**Comment by CptWad** [comment]
also SCREENCAPS OR GO

**Comment by Hoshi-chan** [comment]
Noticed during a badmin stirring up some monkey business earlier that vox chickens don't seem limited to only the birb squawking the way monkeys can only speak monkey. They can still speak gutter, tradeband, etc if they could before.

**Comment by SonixApache** [comment]
Lesser greys better be little green men.

**Comment by Shadowmech88** [comment]
At some point it'd probably be good to just make monkeys a human race rather than a weird snowflake mob.

**Comment by TheFriggenSawbones** [comment]
ayy  can you post pictures for the forms

**Comment by Intigracy** [comment]
need to put fixes in front of #8403 too

**Comment by ghost** [comment]
Pics added

**Comment by ghost** [comment]
Flaming skulls now glow with the same light as a firepit.

Reduced the damage multiplier to 2, what skeletons currently have.

**Comment by clusterfack** [comment]
Hmmm, does this all actually work? It seems like there's more effort necessary than this to make them work without bugs with languages and clothing placement and such.

**Comment by ghost** [comment]
The skulls have all clothing disabled that could be done (Can probably be force-worn a backpack and mask however)

The greys have glasses disabled, otherwise they're just monkeys with larger heads, so monkey clothing works for them, but helmets look a tad ridiculous

I am unable to reproduce the language bugs mentioned by Hoshi. Each monkey I was able to test with didn't have any abnormalities with available languages.

This all seems alright, what do you see that could be off?

**Comment by Durgen** [comment]
can the grey monkeys use project mind?

**Comment by ghost** [comment]
@Durgen I tried to set that up, but giving them the mutation was odd

**Comment by ihadtoregisterforthis** [comment]
There should be sprites for skeleton chickens on monkey.dmi too, if you dare.

**Comment by ghost** [comment]
I'll get onto that now then

**Pull request merged**
