### PR TITLE
Psycho Bundle

### PR DESCRIPTION
**Pull request by Arthurdentist**
adds a new syndicate uplink bundle. Psycho Bundle. Comes with Raincoat,
Agent ID, Emag, Voice Changer, Soap, Newspaper, Axe and Suit.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Well there isn't a copy of It's Hip To Be Square, but it's good.
:+1:

**Comment by Arthurdentist** [comment]
I was thinking about that. Originally I went with the emag because Agent ID, Emag, Voice Changer = 9 TC. The Raincoat itself is 1 TC as is the Soap. Soap and Axes aren't that hard to come across though, but I could change it if people feel it is too much.

**Comment by DrCelt** [comment]
Seems fairly balanced in my opinion, Arthur's reasoning makes sense on the price for 10TC, I would have given it more, honestly.

**Comment by ComicIronic** [comment]
While I would agree that the cost of the bundle isn't an issue, the combination of some of the most useful stealth items in the game (Emag, voicechanger, agent ID) along with the most powerful in-game obtainable weapon could prove far greater than the sum of its parts.

Anywho, I suppose the server experience will have to decide if it's too powerful.

**Comment by Shaska-** [comment]
No more powerful than the hacker bundle, which is emag, hacked upload and binary translator or the murder bundle which is emag, esword, noslip and thermals, so it should be fine. The bundles are meant to be more powerful than what you'd normally get for 10 TC anyway.

**Pull request merged**
