### PR TITLE
Dejunks the health analyzer display

### PR DESCRIPTION
**Pull request by MadmanMartian**
Removes un-necessary gunk, abbreviates a lot of the feedback text. Removes some limb itteration for minute performance increase

health_analyzer_before_after

### CODE REVIEW

**Comment by MadmanMartian** [comment]
I would prefer to reduce it further, so it's just relevant data, but that's as much as I think is healthy to reduce it to currently.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
"Advanced scan required for location" is important info I think

**Comment by ShiftyRail** [comment]
My immersions

**Comment by strawberrytan** [comment]
does it still give time of death on corpses?

**Comment by MadmanMartian** [comment]
yes

**Comment by Intigracy** [comment]
I think it would look even less messy if you add `message += "<br>"` right before the to_chat here https://github.com/vgstation-coders/vgstation13/pull/20497/files#diff-4478f63cdab8deed3664867567df22f6R245

**Pull request merged**
