### PR TITLE
Starscreen changes

### PR DESCRIPTION
**Pull request by SonixApache**
changes starscreens up a bit

Capacitors:
- Max charge rate for capacitors upped by 10x for starters
- Upgrading the capacitors in the capacitor now actually doubles / triples output
- Displayed power is all in kilowatts now, to save on zeroes
- Kicking it has a 50% chance to turn it off, in case it sucks APC dry and you can't open the interface to turn it off
 - Added [MIN] and [MAX] buttons, alongside marking the bigger buttons with double symbols ([--], [-])

Shield gens:
- Interface no longer multiplies the field size by 2 because that was stupid (and not to mention broken - the max size was 200, but it only reached up to 108)
- Bigger fields possible across the board
- Upgrading it makes it more energy-effective and lets you power the shield faster
- EMPs will now fuck with it better
 - Added [MIN] and [MAX] buttons, alongside marking the bigger buttons with double symbols ([--], [-])

What still needs changing:
 - Starscreens and capacitors work 100% off APCs, not off cables or powernet power
 - Capacitors rip their maximum amount of charge straight out of the ether, whether or not the APC actually has that kind of power
 - add [SET] buttons?
 - maybe allow for multiple capacitors per shield generator
 - add some sort of sprite or effect to show a capacitor and generator are linked (i think other codebases have this)
 - make explosions not just fucking pierce the shield, what the fuck
 - ??? i forgot

🆑 
 - tweak: Starscreens have been upgraded to store and use way more power, and now benefit from upgrades.

### CODE REVIEW

**Comment by DamianX** [comment]
\>Kicking it has a 50% chance to turn it off, in case it sucks APC dry and you can't open the interface to turn it off
shouldn't it just turn off then?

**Comment by SonixApache** [comment]
@DamianX You'd think so, but it uses magic power -- the capacitor and generator work as intended, but the interfaces lock up.

I haven't actually figured out and fixed how the damn thing consumes power yet.

**Comment by SonixApache** [comment]
fucking travis

**Comment by Kurfursten** [comment]
I thought explosion piercing was a FEATURE so they don't trivialize meteors entirely, just reduce the destruction dramatically

**Comment by SonixApache** [comment]
The description of renwicks makes me think otherwise. Also makes EX starscreens completely pointless, since heavy meteors will still just crack the hull open.

**Comment by ghost** [comment]
Pretty sure it just never addressed shields when explosion resistance was added to walls and shit.  Regardless of the intent, an improvement should still be made for the benefit of making the ex starscreen matter for anything since maint still gets breached from the hvy radius going right over the shield even without it being large meteors. It'd also help with medbay not bitching incessantly every time eng throws the shield up too if they could use the ex over the regular. Lord knows you're in the dog house if they have to see sparkles while operating.

If it's felt that it's gotten too trivialized, meteor amounts, size weighting, and clustering density can be tweaked or a more intense wave(s) added as a later round event(s).
Otherwise, someone capable of it could try modifying the ex to instead offset 1-2 tiles from the turfs it already uses to determine shield placement. Existing clusters could still punch while trading off for reducing lone meteor damage without blocking off internal passages.

**Pull request merged**
