### PR TITLE
Should fix most issues with bots.

### LINKED ISSUE #26579: mule bots don't work
(WEB REPORT BY: yocutzo REMOTE: 206.221.180.138:7777)
# Revision
89e16f62ba7eae1337840864044319467589aed3

# Description
they don't show up on the PDA app and the commands on the mule bots itself rarely work

# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #32995: ED-209 Not Patrolling
(WEB REPORT BY: knife28 REMOTE: 206.221.180.138:7777)
# Revision
f839452895187cdf64c2996df53002bbcb35f050

# Description
When setting autopatrol to on it toggles off after a second 
# Steps to Reproduce
Unlock ed-209, set autopatrol to on
# What you Expected
Autopatrol to stay on and ED-209 to patrol like beepsky
# What Actually Happened
Autopatrol toggles off automatically

### PR DESCRIPTION
**Pull request by ShiftyRail**
I can't be arsed to look at the issues it fixes, but this solves the patrol problems Beepsky sometimes encounters, this fixes the summon bot PDA commands, and fixes mulebots commands.

The laser pointer also works. In fact it was the the laser pointer that resulted in the bugs in the first place. 
Not everything is fixed, though, as the laser-pointed mules still do not unload/load as required.

Thank you very much for your patience.

Closes #32995
Closes #26579 (although this one was probably related to another, pre-existing bug)

### CODE REVIEW

**Comment by ShiftyRail** [comment]
>secret repo
Nani?!

**Comment by nervere** [comment]
Our hero.

**Comment by SECBATON-GRIFFON** [comment]
if this actually works then thank you eternally, i've been thinking of a way to optimise astar code to make it actually work in-game but got nowhere. a suggestion i have to add to this is the possibility of a debug option to "draw" the path in red on tiles, like the spiral block check. how does this sound?

**Comment by Eneocho** [comment]
>"draw" the path in red on tiles

`>be clown`
`>doodle around with the red crayon`
`>bot freezes`
hehe, nothin personnel kidd...

**Comment by SECBATON-GRIFFON** [comment]
> > "draw" the path in red on tiles
> 
> `>be clown` `>doodle around with the red crayon` `>bot freezes` hehe, nothin personnel kidd...

that isn't related at all, check spiral block is an admin command, this would be too

**Comment by Eneocho** [comment]
the joke -------->

(you)

**Comment by ShiftyRail** [comment]
@SECBATON-GRIFFON There's actually a debug flag to draw the patrol path used by bots but it's not working for mulebots at the minute. It's also only set at compile time.

**Pull request merged**
