### PR TITLE
Removes the most USELESS thing ever.

### PR DESCRIPTION
**Pull request by PJB3005**
Seriously N3X15 this was the defenition of useless

### CODE REVIEW

**Comment by ComicIronic** [comment]
But did you test it

**Comment by PJB3005** [comment]
If there's anything that doesn't need testing it's this, let's be honest.

**Comment by ComicIronic** [comment]
I wonder if Byond is good enough to store floats with no decimal as ints.

**Comment by PJB3005** [comment]
I think that's just N3X15 putting .0 after every int, I've seen it in places it doesn't make sense.

Also, floats make no sense in the context num2dir was used anyways

**Comment by optimumtact** [comment]
Oh I thought this was removing the adminbus

oh well

**Comment by Exxion** [comment]
>Adminbus
>Useless

**Comment by d3athrow** [comment]
>num2dir
>takes a number and returns the exact same number unless its not a direction

:I

**Pull request merged**
