### PR TITLE
Replaces money lotto event with an actual six number lotto

### PR DESCRIPTION
**Pull request by ghost**
[content][tested]
image
image
## What this does
Changes the "money lotto" event which randomly decides to give a player money to an actual six number lotto (using a 6/32 draw) broadcasted from central command, with 5 and a bonus number at the end.
Tickets for it can be bought at the lotto vending machines during the event, and wins redeemed there too. Matching the bonus number and at least 2 of the other 5 gives a cash prize of the following:
* Jackpot / 1000 for 3/6 total
* Jackpot / 100 for 4/6 total
* Jackpot / 10 for 5/6 total
* The full jackpot for matching all 6, which then gets reset after this and no more winnings can be claimed from the announced numbers. The winner also gets announced from central command.

Jackpots build up 10,000 times the price of anything bought from a lotto vendor up to a highest total of 200 million. Winnings (including scratch cards) subtract from this total. This is persisted across rounds, with a low floor of 1 million.

## Why it's good
Makes the event more obvious, plus gives another fun use for the vending machines.

## Changelog
:cl:
 * rscadd: Central Command have bought out Tau Ceti Daily's Grand Slam -Stellar- Lottery and refurbished it, with a 6 number matching system. (5 and a bonus at the end) Matching at least 3, bonus included rewards a cash prize.

### CODE REVIEW

**Comment by west3436** [comment]
I had thought about doing this but consider this - what if the jackpot started in the 100k range and built up over rounds to some sort of capped value so we don't hit a billion credits or something? That mirrors an actual lotto setup and would be pretty fun to see people scrambling to buy tickets for the 100,000,000 credit jackpot or something like that.

**Comment by ghost** [comment]
> I had thought about doing this but consider this - what if the jackpot started in the 100k range and built up over rounds to some sort of capped value so we don't hit a billion credits or something? That mirrors an actual lotto setup and would be pretty fun to see people scrambling to buy tickets for the 100,000,000 credit jackpot or something like that.

Will consider this

**Comment by adacovsk** [comment]
Might not be completely atomic, but would you consider putting the scratch lotto and slots jackpot winners on the news channel as well?

**Comment by ghost** [comment]
> Might not be completely atomic, but would you consider putting the scratch lotto and slots jackpot winners on the news channel as well?

It was before this so it wouldn't be too unatomic.

**Comment by pedr69** [comment]
aieeeee nooooo
no longer do i get a trillion creds for doing literally nothing

**Comment by jwhitak** [comment]
I wish we kept the random event this is replacing, if only because of the SOUL.

**Comment by Eneocho** [comment]
Does luck affect the chances to win the 6 numbers lotto? If not, please make it so it does affect the chances. We have the luck system, it's a waste to not use it.

**Comment by ghost** [comment]
> Does luck affect the chances to win the 6 numbers lotto? If not, please make it so it does affect the chances. We have the luck system, it's a waste to not use it.

Maybe not in this PR, I don't know how to do it without the worry of breaking it.

**Comment by Eneocho** [comment]
> I don't know how to do it without the worry of breaking it.

You could take a look at how the regular lotto calls for luck [here](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/games/cards/lotto.dm).
As I understand it, it checks the user's luck then uses the luck value and a skew value to determine just how much of an effect luck can have. 
Your best bet is asking @Hinaichigo for further details.

**Comment by ghost** [comment]
> > I don't know how to do it without the worry of breaking it.
> 
> You could take a look at how the regular lotto calls for luck [here](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/games/cards/lotto.dm). As I understand it, it checks the user's luck then uses the luck value and a skew value to determine just how much of an effect luck can have. Your best bet is asking @Hinaichigo for further details.

Attempted it

**Comment by Kurfursten** [comment]
I like this event idea a lot, but I feel like it works backwards. You need to buy tickets - ideally up to ten of them - and then hope that the event will fire at all, but there are long breaks between events and you may just get unlucky - maybe you get greytide and meatstorm instead even with plenty of players.

This would require a refactor, but I suggest instead structuring it like this, which I think would have a LOT more player involvement and less wasted cash.
* Lotto is announced. Players are given 5-10 minutes to buy tickets (say "The lotto will close at [station time of end]").
* You can only buy tickets during this time. If you try to buy lotto tickets when a lotto isn't active, it rejects the purchase. Or alternatively, the lotto tickets just aren't in the machine. Whatever is easiest to code. There are a couple ways to approach this, ask if you need ideas.
* Lotto closes at stated time, or perhaps the minute after the announced station time to give people some grace period on last minute purchases. After that, it runs as it exists here.

This would make the lotto more of an active participation event and hopefully make people swarm the bar buying tickets. I am imagining that episode of scrubs.
image

**Comment by ghost** [comment]
> * Lotto is announced. Players are given 5-10 minutes to buy tickets (say "The lotto will close at [station time of end]").
> * You can only buy tickets during this time. If you try to buy lotto tickets when a lotto isn't active, it rejects the purchase. Or alternatively, the lotto tickets just aren't in the machine. Whatever is easiest to code. There are a couple ways to approach this, ask if you need ideas.
> * Lotto closes at stated time, or perhaps the minute after the announced station time to give people some grace period on last minute purchases. After that, it runs as it exists here.

Currently changing it to this, decided to make the results "broadcasted" from entertainment monitors with delays between each number instead of a generic announcement for the closing time. (The monitor is right next to the lotto vendor on Box)

**Comment by Eneocho** [comment]
>Decided to make the results "broadcasted" from entertainment monitors with delays between each number

Soulful.

**Comment by ghost** [comment]
> > Decided to make the results "broadcasted" from entertainment monitors with delays between each number
> 
> Soulful.

That was the intent.

**Comment by Eneocho** [comment]
I'd change it to say:
"The numbers are:"
"2"
"5"
"12"
"25"
"11"
"And 12"
Instead of repeating "The xth number is".

**Comment by Kurfursten** [comment]
I would encourage you to say something more like "A new lottery has opened. Secure your tickets from the scratch-off vendor for a chance to win immediately! Tickets must be purchased before the prize broadcast at a local entertainment monitor to qualify. The announcement broadcast will take place in [x] minutes at [station time]."

This makes it clear that people that they should rush to the bar to buy. Also, having the station time of closing is good because say you spend 3-4 minutes trying to get over to the bar and you're not sure how long you have left because you weren't near an entertainment monitor to hear the reading. It would be pretty sad if you got there late, missed the announcement, and started buying tickets because the broadcast is not global.

**Comment by SonixApache** [comment]
from hell's heart, i lol at @adacovsk

**Comment by adacovsk** [comment]
> from hell's heart, i lol at @adacovsk

?

**Pull request merged**
