### PR TITLE
Removes some unused procs

### PR DESCRIPTION
**Pull request by Exxion**
Just noticed these while working on something else. They aren't used anywhere. 100% tested in that the code still compiles and there's not really anything else to test.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
This was a spectacularly bad way to go about this check

**Comment by Irradiation** [comment]
Prepare for unforeseen consequences. Probably.

**Comment by ShiftyRail** [comment]
Not at all, as this wasn't used anywhere and would be a terrible way to perform the check.

**Comment by Exxion** [comment]
Both were implemented very poorly but BYOND doesn't give a good method to test movement without actually moving, so I can see the appeal. I have no fucking clue what's going on with the slime one though.

**Pull request merged**
