### PR TITLE
Adds Avali as a playable race

### PR DESCRIPTION
**Pull request by ghost**
Finally adds the highly requested Avali race. There may be some hiccups as NT budget cuts have left them without proper environmental suits. Since this is an experimental PR, they are currently limited to Assistant.

Sprites are borrowed from Polaris, which are apparently in turn borrowed from Bay.

:cl:
 * rscadd: Added Avali as a roundstart race.

### CODE REVIEW

**Comment by RealestEstate** [comment]
legend

**Comment by SirSkeleto** [comment]
AHAHAHAA

**Comment by kilozombie** [comment]
dare i say it

**Comment by BomberBro** [comment]
Content...

**Comment by Zach720** [comment]
The fuck?

**Comment by RealestEstate** [comment]
the speedmerge that saved /vg/

**Comment by tuypo1** [comment]
Remove the assistant cap while they are around

**Comment by ghost** [comment]
> Remove the assistant cap while they are around

fun fact: there is no roundstart assistant cap

if nobody else does it and latejoins end up being a problem anyways I'll do it tomorrow

**Comment by SonixApache** [comment]
repoban when

**Comment by tuypo1** [comment]
If they are gonna be kept around for longer than a day they will need to be bared from being traitors, it's a waste of threat otherwise

**Comment by ghost** [comment]
> 
> 
> If they are gonna be kept around for longer than a day they will need to be bared from being traitors, it's a waste of threat otherwise

They're gone after today, tomorrow from the perspective of that comment was the 1st for me.

**Pull request merged**
