### PR TITLE
[WIP] Adds skulls and bones

### PR DESCRIPTION
**Pull request by unid15**
- Added /obj/item/stack/animal, and made teeth a subtype of that
- Added a "has_skeleton" var to living mobs
- Added bones. They drop from animals after butchering, and can be used to build bone furniture (WIP: NEED SPRITES!)
- Added skulls. They drop from animals after butchering, using a chisel on one makes a helmet (WIP: NEED BETTER SPRITES)
- Remains can be collected by clicking on them with an empty hand, yielding around 20 bones and a skull

### CODE REVIEW

**Comment by Shadowmech88** [comment]
It must be made possible to drink beverages from the skulls of one's enemies.

**Comment by N3X15** [comment]
Conflicts

**Comment by Zuhayr** [comment]
Would you mind if I steal this concept for Europa?

**Comment by Unfit** [comment]
@Zuhayr not at all

**Comment by Rei1226** [comment]
can we get human skulls as well and wear them on our heads or on some sort of trophy belt?

I also concur with the drinking from skulls idea

**Pull request closed without merging**
