### PR TITLE
Syndicate Clown Pods

### PR DESCRIPTION
**Pull request by GermanSanta**
* rscadd: Adds clownpod seeds to the syndicate uplink of Clowns and Botanists for 20TC.

### CODE REVIEW

**Comment by gurfan** [comment]
MADMAN

**Comment by DamianX** [comment]
xD

**Comment by GermanSanta** [comment]
Complete

**Comment by gurfan** [comment]
Would be better off just putting it under the clown planet category, having it's own snowflake category seems pointless

**Comment by GermanSanta** [comment]
However, its necessary. Only appears if one is a clown or botanist. Would be kinda lame if everyone had access to the item, making it a common occurrence.

**Comment by GermanSanta** [comment]
Yea, that was a stupid idea. Listed it back into the clown planet category.

**Comment by SonixApache** [comment]
clown pods destroy stations
:-1:, locked behind admemes for a reason

**Comment by GermanSanta** [comment]
As a non-antag, set off an EMP in medbay that blendered someone that was in the process of being cloned. Logged before questioning. by SonixApache (Blondiemin) on Tue, August 27th of 2019

**Comment by gurfan** [comment]
what

**Comment by GermanSanta** [comment]
So does singularities and polyacid kudzu but that's not nearly as entertaining. Can you explain farther sonix?

**Comment by SonixApache** [comment]
one clown pod packet generates a literal infinite amount of retaliation mobs

**Comment by GermanSanta** [comment]
confused. xenoarch does the same how would it destroy a station entirely?

**Comment by jknpj** [comment]
You underestimate the autism of hydroponics. Don't do this.

**Comment by GermanSanta** [comment]
iyW6LSiZR1GMigy8ftMeXQ
kFo0xH4rQ_Ke4fAzt0tIJQ

**Comment by Zth--** [comment]
Think of a better proposal

**Pull request closed without merging**
