### PR TITLE
Zam Tweaks and Two New Products

### PR DESCRIPTION
**Pull request by Optimism333**
## The Return of Zam ##

This is a quick Zam update mostly aimed at introducing two new products, with two small tweaks included.
* Minor Tweak: Reordered the name of Radical Zam Biscuit. It's now named Zam Radical Biscuit
* Minor Tweak: Removed the sweet flag from the Zam Radical Biscuit, since it has no sweet ingredients.

## New Products ##
Screenshot (724)
 * **Zam Buttery Biscuit:** A new premium biscuit synthesized with butter coating. Administrator Zam's favorite! (Price = A coin) (Reagents = Nutriment, Arithrazine, Alkycosine, Butter, Sulphuric Acid) (Number Stocked = 2)
 * **Zam Human Hydrator:** Zam labs have replaced the generic mineral water previously stocking the machine with a new and improved version. It contains five essential minerals for the ultimate human hydration! (Price = 40 credits) (Reagents = Water, Iron, Copper, Silver, Gold, Diamond) (Number Stocked = 6)

:cl:
 * rscadd: New premium Zam product, a biscuit with butter!
 * rscadd: New Zam beverage, Human Hydrator! A premium mineral water for nongreys.

### CODE REVIEW

**Comment by Servalfang** [comment]
Details on the exact reagent balance of the water?

**Comment by Optimism333** [comment]
> Details on the exact reagent balance of the water?

35u water, 1u iron, 1u copper, 1u silver, 1u gold, 1u diamond dust

**Comment by SonixApache** [comment]
I was initially slightly worried about people buying this just to solidify diamond out of it but the numbers make that fine.

**Comment by Eneocho** [comment]
> 
> 
> I was initially slightly worried about people buying this just to solidify diamond out of it but the numbers make that fine.

There are far better ways to solidify diamond, don't worry.

**Comment by Eneocho** [comment]
Can you bump up the chemicals inside the human hydrator a bit? 40 creds for what amounts to be basically just water still seems a lot since you can just use a sink for infinite water. I dunno, maybe 10u Gold and 10u Silver or something? Obviously not diamond, since that would be too powerful, but you can find gold and silver stationside at roundstart without going to mine (Gold on the Vault crate, Silver ore on the Miner shuttle port, which you can turn into silver bars using recycling), and you still need someone at cargo to actually make the Zam vendors, not to mention the whole acquiring Frost Oil and Silicate thing.

**Comment by Eneocho** [comment]
Also, diamond dust is highly damaging, it causes tons of brute damage (M.adjustBruteLoss(5 * REM)), so you might want to remove it or add it to another contraband drink (Polytrinic Palooza would be a good choice, since it's already a fuckyou drink). Imagine eating fibreglass. 
It also makes you scream in pain.

**Comment by Optimism333** [comment]
> Can you bump up the chemicals inside the human hydrator a bit? 40 creds for what amounts to be basically just water still seems a lot since you can just use a sink for infinite water. I dunno, maybe 10u Gold and 10u Silver or something? Obviously not diamond, since that would be too powerful, but you can find gold and silver stationside at roundstart without going to mine (Gold on the Vault crate, Silver ore on the Miner shuttle port, which you can turn into silver bars using recycling), and you still need someone at cargo to actually make the Zam vendors, not to mention the whole acquiring Frost Oil and Silicate thing.

## To Address Your Concerns ##

**40 creds for what amounts to be basically just water still seems a lot since you can just use a sink for infinite water.**

Price is whatever people are willing to pay for the product, regardless of how helpful or useless it really is. Enough people were buying 100 credit mineral water before this change that I imagine someone at Zam labs said, "Look at these silly humans. If they're willing to buy perfectly normal bottled water from us for a hundred credits, imagine how much more they would buy if we cut our price by 60% and added some REAL minerals to the drink. These are all essential minerals for humans, aren't they? Throw them in and see what happens." Anyways, the value of the drink is that it's a unique item and also the only drink in the machine that is MORE lethal to greys than humans. It's not supposed to be objectively better or equivalent to other drinks of comparable prices. 

**Can you bump up the chemicals inside the human hydrator a bit? I dunno, maybe 10u Gold and 10u Silver or something?**

I'm really hesitant to put too many units of valuable minerals in the drink. Mostly because as Sonix mentioned, I don't want people using it to solidify metals. I purposefully left the amounts low to avoid that. I would accept an idea to add an additional 5 units of a moderately useful chemical or something similar, but I really don't want to buff the amount of metals in the drink.

**Also, diamond dust is highly damaging, it also makes you scream in pain.**

Weird, I fed the whole drink to a human dummy in testing and they didn't scream in pain. It caused a noticeable but not significant 10 brute damage, which was easily healed over time.

**Polytrinic Palooza would be a good choice, since it's already a fuckyou drink**

You take that back, sir! How dare you! Seriously though, Polytrinic Palooza isn't a fuck you drink for the intended consumer (greys), it barely does any damage to them. Unless you meant its a fuck you drink to humans, in which case... I suppose so yeah. But that could also be said for all the drinks in the machine that contain harmful acid.

**Comment by Eneocho** [comment]
>I'm really hesitant to put too many units of valuable minerals in the drink. Mostly because as Sonix mentioned, I don't want people using it to solidify metals.

You can just grind 3 Danchocos, isolate the uranium salt and solidify it for an uranium sheet. Sonix's fears are mostly unfounded, since we already have solidification available at roundstart but nobody does it since there are far better ways to produce metals in quantity than vendor solidification (You can just pop to the roid for 10 minutes and go back with a few sheets of most metals, maybe even one or two sheets of diamond if you were lucky), not to mention that there's barely any use for the materials outside of RnD so the only ones who would do it are scientists, who prefer to wait for the miners while doing the barebones RnD or just go mine themselves.

I get your point though. Perhaps just make it rich in iron (it helps with blood loss and it ain't really worth it to solidify iron for a single sheet when you can buy 50 sheets at cargo, plus it works with the IC explanation of minerals humans use) and some random chem. A few suggestions for said chem could be: 1u Clotting Agent (exactly the same as biofoam), 5u Doctor's Delight, 5u Paracetamol (Tramadol-lite), 5u Carbon (for "carbonation"), some amount of nutrition chems like Corn Oil or Nutriment.

>Weird, I fed the whole drink to a human dummy in testing and they didn't scream in pain.

There's a 30% chance for screaming. You got (un)lucky.

**Comment by Optimism333** [comment]
> > I'm really hesitant to put too many units of valuable minerals in the drink. Mostly because as Sonix mentioned, I don't want people using it to solidify metals.
> 
> You can just grind 3 Danchocos, isolate the uranium salt and solidify it for an uranium sheet. Sonix's fears are mostly unfounded, since we already have solidification available at roundstart but nobody does it since there are far better ways to produce metals in quantity than vendor solidification (You can just pop to the roid for 10 minutes and go back with a few sheets of most metals, maybe even one or two sheets of diamond if you were lucky), not to mention that there's barely any use for the materials outside of RnD so the only ones who would do it are scientists, who prefer to wait for the miners while doing the barebones RnD or just go mine themselves.
> 
> I get your point though. Perhaps just make it rich in iron (it helps with blood loss and it ain't really worth it to solidify iron for a single sheet when you can buy 50 sheets at cargo, plus it works with the IC explanation of minerals humans use) and some random chem. A few suggestions for said chem could be: 1u Clotting Agent (exactly the same as biofoam), 5u Doctor's Delight, 5u Paracetamol (Tramadol-lite), 5u Carbon (for "carbonation"), some amount of nutrition chems like Corn Oil or Nutriment.
> 
> > Weird, I fed the whole drink to a human dummy in testing and they didn't scream in pain.
> 
> There's a 30% chance for screaming. You got (un)lucky.

Alright, I'll drop the diamond dust and rearrange the reagent recipe in a little bit. I'll post the new one when it's done.

**Comment by Optimism333** [comment]
I think I messed up my local branch. This is what I get for taking a month long hiatus from coding.

If I can't figure out how to fix it by tomorrow I'll make a new pr with the final changes.

**Comment by SonixApache** [comment]
diamond dust is fine

**Comment by Optimism333** [comment]
Closing this for now. I'll reopen a new pull when I've fixed my local branch.

**Pull request closed without merging**
