### PR TITLE
Adds Space Rangers 2 - Meteor Shower to the lobby song list

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I want at least one Space Rangers 2 song in the lobby list, preferably two. This is a good one IMO but feel free to give a listen to the OST by typing it on youtube or something and tell me if there's a better one
Space Rangers 2, Space Rangers 2: A War Apart as well as Space Rangers 2 - Meteor Shower OST belong to Elemental Games
https://www.youtube.com/watch?v=TO27HN58Tbc
:cl:
 * soundadd: Added Space Rangers 2 - Meteor Shower to lobby songs.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
@brndd Is this spacey enough?

**Comment by Caboozles** [comment]
Do we need to have 20+ songs in the lobby list? What we have is absolutely fine.

**Comment by boy2mantwicethefam** [comment]
Never hurts to have more as long as they are great

**Comment by DamianX** [comment]
add is good

**Comment by Irradiation** [comment]
new content is inherently good

**Comment by jknpj** [comment]
Too many songs is not a meme

**Comment by boy2mantwicethefam** [comment]
it is if there's no negative impact, I think the only negative impact is a few seconds longer initial downloading resources screen

**Pull request closed without merging**
