### PR TITLE
[Taxi] Remap AI core, improve sleeper layout - NEW AND IMPROVED(?)

### LINKED ISSUE #8679: Emitter in Taxi's Research Station Isn't Connected to a Wire
Seeing as insulated gloves are not standard-issue for xenoarchaeologists, this can prove to be a nuisance.

### PR DESCRIPTION
**Pull request by xpcybic**
Neither Git nor the map merger would cooperate, so I redid this manually. I probably did it correctly. **99.999991% TESTED**
- Redesigned the AI core to be more open and prevent turret shots from being blocked.
- AI core SMES is now in its own room south of AI upload and starts fully charged.
- Security camera in sec/sci bridge now appears first in the camera list, like the dock cameras. AIs can jump to this camera for easy access to consoles.
- Added security records and research shuttle consoles to bridge.
- Spread out the sleepers, body scanner, and mancrowave so that they can be walked between.
- Expanded the IAA office a little bit.
- Added a pAI to sec/sci rec room.
- Wired the emitter in research outpost.
- Fixed hydroponics APC not being wired to grid.

Fixes #8679

screenshot 2016-03-08 22 16 39
taxi-mar06-5
taxi-mar06-2

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Check every pipe and wire near your changes.
Maybe you'll want a camera in the IAA office.

**Comment by xpcybic** [comment]
Threw one in there and also in detective's office
And yes I did miss piping and wiring in one place

**Comment by 9600bauds** [comment]
Replace Mancrowave with body scanner

**Comment by xpcybic** [comment]
Nah

(if we're actually going to it should be for all maps at once)

**Comment by 9600bauds** [comment]
Deff is doing it in #8828 so it might be a good time to start

**Comment by xpcybic** [comment]
eh
alright

**Comment by 9600bauds** [comment]
tyty

**Pull request merged**
