### PR TITLE
Walking on the clown PDA slips you (not april fools)

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
You: Work on the armor rework already
Me:
:cl:
 * tweak: You can now slip on clown PDAs even when walking.

### CODE REVIEW

**Comment by ghost** [comment]
Does this ignore noslip shoes?

**Comment by boy2mantwicethefam** [comment]
It shouldn't, the proc for slipping has 5 variables
Stun amount
Weaken amount
Slip on walking over it (0 by default)
Overlay type
And slip with magboots active (0 by default)
I believe slipping with magboots active checks for the "NOSLIP" flag, which no-slip shoes have.
I have set the "slip on walking over it" to 1, so that walking over it can make you slip.

**Comment by Jubisloviu** [comment]
Is barry dare i say /ourguy/?

**Comment by Irradiation** [comment]
Walk to evade, just like every other tool in the clown's arsenal.

**Comment by ShiftyRail** [comment]
Walking is already crippling yourself enough and there should be ways to play around silly slip that stuns you for a solid 6 seconds.

**Comment by PaulRitter** [comment]
soooo, is this gonna be a thing or not?

**Review by ShiftyRail — APPROVED** [review]

**Pull request merged**
