### PR TITLE
added animated still and cereal maker on state

### PR DESCRIPTION
**Pull request by PaulRitter**
also added an istype check instead of it literally checking for "cereal" in the items name

(couldn't make it higher res sorry)
[the animated states](https://gyazo.com/efacf10d8c2dd400cbba165e54889940)

:cl:
 * rscadd: You can now see the still and the cereal maker working
 * rscdel: You can no longer create recursive cereals

### CODE REVIEW

**Comment by bathosbathtime** [comment]
Removing easily done recursive cereal is a good thing.
I would appreciate it if it was in the change log in some form.

**Comment by PaulRitter** [comment]
dmn, im adding some more fixes.

also this kinda resolves #22644

**Comment by PaulRitter** [comment]
alright fire away im done

**Comment by SonixApache** [comment]
add 🆑 for the cereal name check thing

also don't do the cereal name check thing, it was only there to prevent infinite length names

**Comment by DrSnips** [comment]
Unatomic

**Comment by PaulRitter** [comment]
added cl for the name thingy

i guess this is unatomic, but lets be real here, these are minor hotfixes, im not gonna make a whole other branch&pr for a one line change for the same obj

**Comment by SonixApache** [comment]
I for one 👎 the loss of recursive cereals

**Comment by kilozombie** [comment]
I understand you looked at the code while fixing something else and went "oh that's shit" but it's a FEEEEAAATUUUURRREEEE and it isn't like getting nutriment is difficult in any way, shape or form

**Comment by Exxion** [comment]
Recursive food is a classic

**Comment by Kurfursten** [comment]
The check as it was before is perhaps the most egregious goofcode in existence

**Comment by Exxion** [comment]
Which is funny because it allegedly wasn't even Goof who wrote that particular one

**Pull request merged**
