### PR TITLE
Fixes #10610

### LINKED ISSUE #10610: ass pie contains spirit brekaer
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if you cook and grind an ass pie you get spirit breaker
> 
> What you expected to happen
> not happen
> 
> What actually happened
> it happened
> 
> Steps to reproduce if possible
> cook ass pie
> eat it
> sprit breaker happens

### PR DESCRIPTION
**Pull request by ghost**
fixes #10610

### CODE REVIEW

**Comment by 9600bauds** [comment]
Not a bugfix

**Comment by ghost** [comment]
@9600bauds @Intigracy said it was a bugfix. Assburgers had their spirit breaker replaced, so should ass pies.

**Comment by 9600bauds** [comment]
Whatever this is it should get in anyways
Rev up that changelog

**Comment by clusterfack** [comment]
:^)

**Comment by ghost** [comment]
@9600bauds remove not a bug and I'll do it

**Comment by 9600bauds** [comment]
Ostensibly balance but who cares

**Pull request merged**
