### PR TITLE
[Box] Update Perma, other fixes

### LINKED ISSUE #2863: [Box] Permabotany map issue
Needs a chem master/condimaster to be able to separate out the sugar/jelly for making jelly sandwich/donut/jelly toast. And pref at least 3 large beakers/condibottles to support flour, sugar, jelly containers for cooking. I'd like a sink so prison farmbot can refill and you can make candied apple too but faggots will slipathon

Comic says: Updated the issue.

### LINKED ISSUE #5909: (WEB REPORT BY: probe1 REMOTE: 198.245.63.50:7777) incorrect camera name
>Revision (Should be above if you're viewing this from ingame!)
EVA East camera is in the bathrooms, next to the dorms.  NE corner next to urinals

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by ghost**
The feature freeze is over, time to map again

Fixes : 
- Dorms Bathroom camera renamed. Fixes #5909
- Perma Botany changes. Fixes #2863

Changes : 
- Made Perma bigger in general, it gained around two to three tiles outwards. Perma is however still one big area for now
- A room called Perma Laundry has been clearly delimited with window panes and a windoor. Added a sink
- Added a mirror to Perma Washroom
- Cleared up the Perma Cafetaria (central room) to allow easier navigation
- Perma Cafetaria room now has silverware instead of plasticware. This might end badly, but then the plasticware couldn't cut anything and still allowed prisoners to gut eachother properly
- Perma Bedroom has a new bed
- Added two new trays, more windows, a NutriMax and a MegaSeed Servitor to Perma Hydroponics. This should make it much easier to grow stuff
- Seed packets changed to seed pack spawners

### CODE REVIEW

**Comment by Probe1** [comment]
pictures dude.  

if you're going to redo it then just nix the knives entirely.

**Comment by dylanstrategie** [comment]
The problem is that knives are needed to slice items, which you can cook since you now have an actual Hydroponics room to use

Picture : 

perma

**Comment by Probe1** [comment]
looks good to me.  really though the only thing silverware is ever used for by prisoners is stabbing security, other prisoners, and themselves.  its hardly a loss if people that committed heinous crimes couldn't make 2bread.

**Comment by Probe1** [comment]
ya fucked up the PRs only been up for an hour and I'm the only one thats looked at it

**Comment by Kurfursten** [comment]
Is that a seed vendor with all seeds available?

**Comment by dylanstrategie** [comment]
That's a regular seed vendor. The problem with giving seeds you can't get elsewhere is Botanist meta

**Comment by SarahJohnson489** [comment]
But we just grab or get a multi printed, pulse arrivals then we can unlock our own in botany anyway?

**Comment by Kurfursten** [comment]
@dylanstrategie I meant it in the opposite way. I'm wondering if there's anything on the non-contraband list that would be dumb to let prisoners grow. Diona seems to be a stand-out option. Should we be letting perma prisoners grow their own army to take back security wing?

**Comment by dylanstrategie** [comment]
As far as I know, everything is fine. At worst the prisoner might grow poison, nettles or diona pods, but that won't deter Security's work too much

**Comment by SarahJohnson489** [comment]
And even if it wasn't in the vendor, letting weed invasions will get you nettles and other bits. Not that 1-2 guys couldn't push/table lock and punch to death a cop that's too dumb to not flashbang or pop some N2O into perma in the first place.

**Comment by Probe1** [comment]
The only thing I can really think of in the vend that would be problematic is wood and bananas.  And if a prisoner made obstructions with peels or barricades I'd just gas him with N2O and move him to solitary.

**Pull request merged**
