### PR TITLE
hivehand stingers deal 15 damage instead of 10

### PR DESCRIPTION
**Pull request by SirSkeleto**
i changed it from 5->10 earlier, it's still bad
lets see if this makes it any better

:cl:
 * tweak: Hivehand stingers from 10 -> 15 toxin damage

### CODE REVIEW

**Comment by Irradiation** [comment]
See you next month for 15>20

**Comment by jknpj** [comment]
When will people notice that the hivehand is also a melee weapon

**Comment by boy2mantwicethefam** [comment]
I'm a scientist metaclubber, and I approve of this PR

**Comment by Kharkov72** [comment]
On one hand 15 toxin a shot is pretty strong but on the other hand hivehand consumes an arm so 🤷‍♂

**Comment by SirSkeleto** [comment]
> On one hand 15 toxin a shot is pretty strong but on the other hand hivehand consumes an arm so
> On one hand

honk
> When will people notice that the hivehand is also a melee weapon

It's a bad melee weapon

**Comment by jknpj** [comment]
>It's a bad melee weapon
>20 force+sharpness is bad

(You)

**Comment by ShiftyRail** [comment]
Unlike brute or burn toxin does not heal naturally, that's relatively strong on its own

**Comment by SirSkeleto** [comment]
brute is much stronger on account of opening wounds and deleting blood, and most burn weapons are hitscan. toxin has very little going for it in that regard. also consider that most firefights are over before healing really plays a role at all. on top of this, some people chug hundreds of units of antitoxin, which is something you can't do with brute or burn meds without od'ing

**Comment by SonixApache** [comment]
->brute is much stronger on account of opening wounds and deleting blood,
still heals automagically and easily
-> and most burn weapons are hitscan.
lasers are hitscan
->toxin has very little going for it in that regard. 
Not being able to recover from it, having your internal organs melt, and having to vomit are three pretty strong factors
-> also consider that most firefights are over before healing really plays a role at all. on top of this, 
only if you're badly prepared
-> some people chug hundreds of units of antitoxin, 
powergamers are scum that must me hunted down
-> which is something you can't do with brute or burn meds without od'ing
doesn't really matter if you can just chug antitox to completely nullify the OD effects

weak arguments for bad powercreep

**Comment by ghost** [comment]
> brute is much stronger on account of opening wounds and deleting blood, and most burn weapons are hitscan. toxin has very little going for it in that regard. also consider that most firefights are over before healing really plays a role at all. on top of this, some people chug hundreds of units of antitoxin, which is something you can't do with brute or burn meds without od'ing

You can do it with burn meds, just not brute.  Not that I would know anything about that.  Its honestly disgusting and abhorrent that anyone would do such a thing with anti-toxin and/or keloderma.  So disgusting that I would ask you to delete your comment and any reference to such as it is causing me great distress.

**Comment by Killette2** [comment]
Make the hivehand deflect projectiles like energy swords and shields

**Comment by Blithering** [comment]
Using up a hand is something all weapons do, but nodrop can be seen as a blessing, as it means you can't be disarmed.

**Comment by Kurfursten** [comment]
This does not appear it will gain the traction it needs to pass.

**Comment by SirSkeleto** [comment]
i tried killing people with the hivehand recently and it was basically fucking useless
i tried using it to shoot people but it never did anything useful
what ended up happening is after i managed to kill a guy with an egun i'd tase someone and shank them with it
thing is, if i had to hit them 2 more times (circular saw, 7x15=105, hivehand 5x20=100), it would have been easy, because they were stunned either way. needless to say, a circular saw doesn't eat your hand, can be concealed, and is much easier to obtain.
melee brute damaging weapons in this game are not terribly useful when compared to the array of stun weaponry (both melee and at a range) that exists here as well.
it takes 10 hits with this to put someone in crit, and you have exactly that many before you have to wait for it to recharge.
not only are you never going to land all 10, it takes time to fire each one, time during which they can run away, call for help, or kill you.
the hivehand is a really really terrible weapon and you will never see it used because of that, which is why i think buffing it is good.
i honestly tried to use it as a test run a while ago and i can honestly say that it was a waste of time and I should have just gotten a stunprod or a circular saw.

**Comment by Killette2** [comment]
I agree that the hivehand has absolutely no niche, and no place in this game. What good is a rechargable unEMPable gun when you can have a backpack of better weapons? The only way to make hivehand useful is to give it a niche. Perhaps something involving more creatine?

**Comment by juanototo2** [comment]
Give it homing projectiles like hl1 hivehand and make it home on the closest target after a shorrt arming time of a few tiles of travel

**Comment by SirSkeleto** [comment]
\>sticking to the source material
if only we could have a non-bouncy osipr

**Comment by tuypo1** [comment]
> It's a bad melee weapon
its a great melee weapon

**Comment by Kurfursten** [comment]
Alright. But I better not see 15->20 next.

**Comment by Killette2** [comment]
feels underwhelming so far. How about 18?

**Pull request merged**
