### PR TITLE
Adds a shitty cape to the magivend

### PR DESCRIPTION
**Pull request by Konater**
buying yew longbows 600gp ea
Added to the premium section so you have to buy 99 magic

### CODE REVIEW

**Comment by Shadowmech88** [comment]
> code/game/machinery/vending.dm:1591:error: /obj/item/clothing/back/magiccape: undefined type path

Looks like something got messed up.

**Comment by Konater** [comment]
it worked when I compiled and tried it in game I dunno what's up

**Comment by gbasood** [comment]
@konater Did you forget to commit .dme changes or something

**Comment by Shadowmech88** [comment]
Have you updated your branch lately?

**Comment by Konater** [comment]
oops you have to submit that too?

**Comment by Probe1** [comment]
YOU HAD ONE JOB

**Comment by ComicIronic** [comment]
Playing more than 99 rounds in a job should give you <s>a skill cape</s> a ban

**Comment by ScrambledSteak** [comment]
It should be a suit item that works as a Wizard Robe tbh

**Comment by Konater** [comment]
The suit slot is for your ahrims though

**Comment by ScrambledSteak** [comment]
> ahrims
> not mystic/enchanted

It's like you never went wildy PKing

**Comment by Kurfursten** [comment]
I've been out of the game for a while so just fill me in - how exactly would a wizard end up with a coin before visiting the station?

**Comment by Konater** [comment]
Right now they can't

**Comment by Shadowmech88** [comment]
Spell that does nothing but give you a silver coin when?

**Comment by Probe1** [comment]
Wouldn't take much more than a minute to add.

**Comment by ghost** [comment]
this is literally the best PR ever

**Comment by gbasood** [comment]
I still don't get the reference

**Pull request merged**
