### PR TITLE
Makes opened crates non-dense

### PR DESCRIPTION
**Pull request by 9600bauds**
This is something that's been bothering me forever. You can walk through opened lockers, but not crates.
Besides making it a PAIN to tetris crates around for no real reason, you can also easily get stuck in small spaces (happened to me a couple times in the salvage ship). You logically would be able to tip-toe over a knee-high crate, right?

Crates still won't pass through crates.
Note that you still can't fit bodies in crates.

Also fixes a bug where roundstart open lockers would still be dense.

### CODE REVIEW

**Comment by clusterfack** [comment]
"Content"

**Comment by clusterfack** [comment]
Crate that holds more than lockers and holds bigger shit than lockers being nondense for... what reason. Why even have anything of these containers be dense in the first place.

**Comment by 9600bauds** [comment]
requesting honk

**Comment by clusterfack** [comment]
Crates are simply larger than lockers are

**Comment by 9600bauds** [comment]
Also, crates don't hold more items, both crates and lockers hold 30 items.

**Comment by clusterfack** [comment]
They hold bigger items

**Comment by 9600bauds** [comment]
Only cases I can think of about items that fit in crates but not lockers are certain small unwrenched machinery like weapon rechargers, which you are still able to fit regardless of whether the crate is dense or not.
I genuinely can't think of a way to abuse crates being non-dense.

**Comment by clusterfack** [comment]
It eliminates any dynamic of cargo managing storage as crates can simply all be piled onto the same tile while opened. In fact there would be nothing to prevent someone "unloading" a shuttle just by opening all the shuttles crates and dragging one of them over all the opened crates and picking up their shit with it.

**Comment by 9600bauds** [comment]
The limit of 30 items

**Comment by dylanstrategie** [comment]
And what happens if someone attempts to close a crate when someone is crossing ?

**Comment by 9600bauds** [comment]
Nothing, crates don't fit mobs inside.

**Comment by clusterfack** [comment]
At least it is more difficult than "I can simply walk on any part of the shuttle because I opened all the crates"

**Comment by 9600bauds** [comment]
Well, to be fair, Cargo does have locked crates, and if you're just going to open all non-locked crates and lump their items into one single crate... you can just weld the empty crates to save space. I've seen it done.
Not like the surplus crates are even used, because they're nothing special.

**Comment by ComicIronic** [comment]
One option is to prevent crates going over other crates, but keep this functionality.

**Comment by 9600bauds** [comment]
I'm looking into doing that right now.

**Comment by 9600bauds** [comment]
Crates weren't calling can_close() while closing
Picnic

**Pull request merged**
