### PR TITLE
More lighting shit.

### PR DESCRIPTION
**Pull request by PJB3005**
Removes high res lighting.

FASTER!!!

### CODE REVIEW

**Comment by FudgePucker** [comment]
I have a question, was there a PR that fixed the problem with the flashlights and helmet lights turning off when moving?
Because I think I know why.
On the test server a few nights back I was testing something, the power was off, so when I ran though the halls with a flashlight the light didn't become disconnected.
Maybe everysingle bug that only happens on the main server and not on say your own test server you run for bug testing is because of lag.
Maybe the position of the player changes before turfs can update because of lag.

**Comment by PJB3005** [comment]
It's very possible it's due to lag, because the scheck() calls in the process code cause the process to be delayed, which causes some issues because additions to the update lists don't get processed correctly.

**Comment by FudgePucker** [comment]
From my experience it has to be lag. Wearable lights are bugged when moving and most of the time I have to feel around in the darkness of maint. (Makes vampire rounds SO MUCH MORE FUN.)
Shit after spending a few mins on the test server I really liked how the lighting worked with no lag, it was really fucking smooth, rather than just having an orb of blocky lights following you around like before hand.

Would there be a way to force the flashlights to update correctly if it lags off? Like if you outrun the lighting update it just has a moment of darkness before catching up?

Kinda funny when you really think about it, because of blue space disturbances and a weird force called 'features', the crew members are able to outrun the speed of light.

**Comment by PJB3005** [comment]
@FudgePucker, I have no idea what you're trying to say but that's not how that works, the only way to really fix this is just to remove the scheck() calls from the lighting process, which would result in a ded serb

**Comment by FudgePucker** [comment]
@PJB3005 
So the only way to fix lighting breaking from lag is to create more lag?
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by clusterfack** [comment]
But really did anyone think multiple resolution lighting was ever going to work effectively

**Comment by d3athrow** [comment]
or you know go back to not super pretty but not laggy lighting

**Pull request merged**
