### PR TITLE
Adds one singular emote.

### PR DESCRIPTION
**Pull request by PrimeDSS13**
I thought that the current *scream emote is generally more for pain, so I thought I would add this emote for fear. Sadly *shriek and *scream are taken, so it's *fear. Mainly I'm just trying to figure out github.

:cl:
 - rscadd: Adds the *fear emote

### CODE REVIEW

**Comment by ghost** [comment]
your changelog formatting isn't right :) use the template you get when you make a new PR.
like this:
:cl:
 * rscadd: Did stuff!
 * rscdel: did other stuff!

**Comment by boy2mantwicethefam** [comment]
Merge it before anyone realizes

**Comment by PrimeDSS13** [comment]
is this acceptable now

**Comment by ghost** [comment]
> 
> 
> is this acceptable now

yes

**Pull request merged**
