### PR TITLE
Gives some of the weaker uplink bundles some more stuff

### PR DESCRIPTION
**Pull request by yackemflam**
people feel super disappointed when they get these bundles in general
This pr is to make it feel not as bad or to make them decent while still fitting their respective themes

Things added:
Bloodyspai: A viscerator butterfly knife
Freedom: Changed to implants, added explosive and compressed implants
Smoothoperator: two spare mags and syndigaloshes
psycho:Hyperzine Pills, cigar, and zippo lighter
ocelot: An extra speedloader (Why did it come with only one when you get 2 pistols?)

Feel free to add any suggestions in the comments

:cl:
tweak: The syndicate have updated some of their kits to help their agents who choose to let fate choose their fate for them,

### CODE REVIEW

**Comment by tuypo1** [comment]
I like it, probably should have mentioned that it changed the weight of the implants bundle though

**Comment by jknpj** [comment]
>people feel super disappointed when they get these bundles in general

I'm almost like it's gambling or something

**Comment by yackemflam** [comment]
Gambling yes but that doesn't mean you have to lose

**Comment by jknpj** [comment]
>but that doesn't mean you have to lose

:thinking: I don't think you quite understand what a gamble is

**Comment by boy2mantwicethefam** [comment]
Uh excuse me? Bundles are not gambling? It's a surprise mechanic

**Comment by ghost** [comment]
Can you maybe list the changes in the PR comment so people don't have to dig around in the changed files?

**Comment by SonixApache** [comment]
code a dead ringer instead
put in some effort

don't like people getting even more explosive implants but that aside decent ideas

**Comment by Accipitermaris** [comment]
if i’m reading this right this increases the odds that murder bundles (Patrick Bateman, Hotline Miami, Guns Bundle, etc.) roll which seems unnecessary given how many of the traitor bundles are murder bundles already

**Comment by yackemflam** [comment]
a dead ringer would be too gunky for all of the dead bodies it would leave

**Comment by ghost** [comment]
You could make the corpses cosmetic and vanish after a set time (30-60 seconds?).

**Comment by tuypo1** [comment]
>if i’m reading this right this increases the odds that murder bundles (Patrick Bateman, Hotline Miami, Guns Bundle, etc.) roll 

Doesn't it only change the weight of the escape bundle which is now implant bundle? I am not really clear on what the addition equations in that code are

**Comment by ghost** [comment]
It's only the freedom/implants bundle that has had its chance increased. The other numbers are the supposed cost in TCs of those items normally. Personally I think the emags and the balloons bundles need to be increased to 100.

**Comment by yackemflam** [comment]
@jackfailure That's not how it works, you had it backwards
The implant bundle had it's chance DECREASED, the lower the number the less chance you would get on getting the bundle

I'm not touching the emags and balloon bundle, feel free to make a pr

**Comment by yackemflam** [comment]
@Accipitermaris The bundle's aren't done by TC cost but by arbitrary weights given. So not much would change on the chances you would get these other than the implant bundle would have a lower chance to show up

**Comment by DamianX** [comment]
Powercreep bad

**Pull request closed without merging**
