### PR TITLE
Suiciding with a gun now plays a sad song in your immediate area

### PR DESCRIPTION
**Pull request by ghost**
Song selection:

1 Johnny Cash- Hurt
2 Simon & Garfunkel - Sound of Silence
3 The MMMM whatcha say from that SNL skit
4. Joan Baez - Here's to you,Nicola & Bart
5. Biggie Smalls - Suicidal Thoughts
6. Can't remember, some classical tune that @Probe1 told me might fit and it did

### CODE REVIEW

**Comment by 9600bauds** [comment]
How long are these? Some are over 1.5mb

**Comment by ghost** [comment]
30 seconds ish. I should probably compress them.

**Comment by ghost** [comment]
compressed

**Comment by Exxion** [comment]
30 seconds seems a bit long

**Comment by Kurfursten** [comment]
I agree, the music should definitely be no longer than the delay between starting the suicide and pulling the trigger.

**Comment by ghost** [comment]
Going to disagree on that. The song plays very quietly after the trigger is pulled.  30 seconds feels about right and allows a decent amount of song to play while maintaining brevity. The average round lasts an hour and a half, we must remember, so in reality this really isn't much

**Comment by CptWad** [comment]
:+1:

**Comment by Probe1** [comment]
he actually did it the madman

**Comment by ihadtoregisterforthis** [comment]
Suicide rates going explosively up with this, and then going back to normal.

Consider not having it on the changelog. It won't be a sekrit anyways.

**Comment by ghost** [comment]
@ihadtoregisterforthis b-but how can I take credit for it

**Comment by ihadtoregisterforthis** [comment]
Be the first to shill it
Comment it on the code
Add a known Irish sad song
Make it that suicide spawns potatos
Suicided corpses are ginger and wear green

https://www.youtube.com/watch?v=upkYQqbrjSc

**Comment by 9600bauds** [comment]
Add https://www.youtube.com/watch?v=4gO7uemm6Yo

**Pull request merged**
