### PR TITLE
Local Man Dabs on Box Firelocks

### PR DESCRIPTION
**Pull request by Kharkov72**
short version: FUCK firelocks
long version: ever since #21753 firelocks have paired with eachother which is GREAT but with how box's firelocks were positioned often this feature would piss and shit itself
NO MORE
this condenses all these dumb fucking double firelocks into a single tile under the door, like so:
Untitled
there's also a few misc. tweaks in here, such as removing a bit of the dirt in the ghetto bar maint (it was really too much), removing a gunk spawner on kamina's cape that wasn't meant for this map, and adding a missing connection port in box perma to gas the prisoners race war now
[box]

:cl:
 * rscadd: Box firelocks have been condensed!

### CODE REVIEW

**Comment by ghost** [comment]
Now make it so anyone can force them open without a crowbar and we're golden

**Comment by GeneralVeers25** [comment]
Why didn't you correct the doors in that photo so they weren't uneven.

My autism.

**Comment by Kharkov72** [comment]
it's a feature

**Comment by SonixApache** [comment]
🤔 
image

grab the ones leading to dorms as well if they're not already set up that way

**Comment by FudgePucker** [comment]
Now give brain damage to people that force open blinking red firelocks and we're golden.

**Comment by Kharkov72** [comment]
they are set up that way

**Comment by tuypo1** [comment]
Thank fucking god
They should just be outright removed but this is a massive fucking step in the right direction

**Pull request merged**
