### PR TITLE
Revert "Friendly Cultist Cyborgs"

### PR DESCRIPTION
**Pull request by bathosbathtime**
Reverts vgstation-coders/vgstation13#23320
They're just letting anyone merge PRs these days, aren't they
EDIT:
Forgot the justification; Did not pass code review.  Unlisted, unrelated, unatomic changes.  Using O+ blood instead of O- is an oversight?  Bad feature?  Such a strange PR merged in such a strange state.

:cl:
* rscdel: reverted "friendly Cultist Cyborgs"

### CODE REVIEW

**Comment by DamianX** [comment]
I'm sorry, sir, you seem to be removing content from /vg/station. Do you mind explaining?

**Comment by bathosbathtime** [comment]
Inexplicably changed how snacks get deleted, used the wrong blood type in the cookies, and is inconsistent with how other cyborg upgrade modules are acquired by the vox traders.

**Comment by tuypo1** [comment]
Most of the issues seem like easy fixs
It really should require an actual hug borg from xenoarch though.

**Comment by iFlashYou** [comment]
Why should traders be the only one to have special borg upgrades?

**Comment by tuypo1** [comment]
Just spit balling here, what if when a hug borg was dug up the ghost that possesses it got to choose between regular hug borg and cultist hugborg

**Comment by ghost** [comment]
As creator of the PR I codone this since it was merged when I had not finished it yet. I'll remake a PR for it soon(tm)

**Pull request merged**
