### PR TITLE
Another scream if deleted by an admin.

### PR DESCRIPTION
**Pull request by Eneocho**
### What this does
When an admin deletes someone they scream as their body disappears. This adds a 50% chance for [this](https://a.pomf.cat/wficoz.ogg) sound effect to be played instead of the current scream. This scream is about the same length (slightly shorter) than the [current one](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/sound/effects/deletescream.ogg?raw=true).
### Why it's good
funny leg scream
:cl:
 * rscadd: Another scream if deleted by an admin.

### CODE REVIEW

**Comment by gurfan** [comment]
too long, dumb meme

**Comment by Eneocho** [comment]
> too long, dumb meme

Literally a shorter scream than the current scream by 1 second.

**Comment by west3436** [comment]
make that just have a chance to play whenever a clown breaks a limb

**Comment by Eneocho** [comment]
I know your pain, barry. I understand.

**Comment by ExpulsionSnooper** [comment]
NOOOOOOOO

**Pull request closed without merging**
