### PR TITLE
Ullapool Caber, a new Syndicate weapon.

### PR DESCRIPTION
**Pull request by Eneocho**
# The Syndicate has been in talks with the DeGroot family...
After much negotiation, the DeGroot family has agreed to let the Syndicate scan and make replicas of the legendary 'Ullapool Caber', used by the famous (or infamous) Tavish 'Demoman' DeGroot of the Teufort Nine.
gibus demoman
### Syndicate operatives may purchase a replica Caber for 10TC.
caber uplink
# How To Use:
The Ullapool Caber has a safety grip that must be enabled in order for explosions to happen. Firmly grip the Caber and swing at your foe. The resulting explosion will maim him and hurt you as well. Using it will do 35 brute self damage, no way to negate it, with the victim receiving somewhere around 55 brute.
After 1 minute, the Caber's explosive yield is restored and can be used as an explosive weapon again. If the safety grip is disabled or the Caber exploded, the weapon has a 15 force damage, similar to a toolbox.
:cl:
 * rscadd: Syndicate Operatives can purchase a modern replica of the legendary 'Ullapool Caber' for 10TC. This handheld 'grenade' will only explode when swung against a target.
 * rscadd: Legends tell of the original Ullapool Caber being somewhere in the Gods' domain.

### CODE REVIEW

**Comment by Eneocho** [comment]
Not sure how to fix that compile issue, it worked fine on localhost with zero errors.

**Comment by boy2mantwicethefam** [comment]
Somehow already better than the actual Caber from Team Fortress 2.

**Comment by DrSnips** [comment]
KAAAABEWWWM

**Comment by BomberBro** [comment]
Infinite breaching explosive item that can be shrugged off with bicard and armor is not very fun to deal with. Should deal 30-35 damage regardless of armor so you can't just constantly use it as a 1 minute recharge Ei Nath spell.

**Comment by Eneocho** [comment]
It doesn't automatically breach, it's a roll with explosioncode. Medium damage has a chance to breach, just like it has a chance not to, and if it breaches you get all the effects of a breach, including the stun. You get the damage as a direct effect of the low explosion around the target, this averages around 20-35 but I had a couple tries where one caber hit caused around 47 brute self damage, not really sure how to make it do self damage without it. You also get bleeds from the explosion too.

**Comment by Dacendeth** [comment]
>1.8 sharpness

how the hell is a broken piece of metal sharper than an energy swords 1.5?

**Comment by pedr69** [comment]
>discounted for assistants(6TC)

make it do a skin tone check instead
and ditch the 1 minute resupply, 8tc for a reusable instakill is insane - parapen is 12TC and single-use

**Comment by Eneocho** [comment]
> > 1.8 sharpness
> 
> how the hell is a broken piece of metal sharper than an energy swords 1.5?

Shit, forgot to tweak it. I had it in 1.35 on my localhost but 1.8 on the "code.txt"

**Comment by Eneocho** [comment]
> > discounted for assistants(6TC)
> 
> make it do a skin tone check instead 

That was actually the original plan but couldn't figure out how to implement it properly.

>8tc for a reusable instakill is insane - parapen is 12TC and single-use

I find it balances itself with the self harm you inflict on each use. Even the luckiest syndicate couldn't use it more than 4 times in a row without going into crit himself. The parapen should be made cheaper. 8 or 9TC, 12 is too much for what is essentially a glorified chloral harmsyringe.

**Comment by BomberBro** [comment]
Why would you have to be lucky? If you want to weight the dice then all you'd need to do is take bicard and wear a hardsuit, or if you want to just be immune to it wear a bomb suit or an EOD suit (which you can get from science with NO access requirements). This item is ridiculously strong and shouldn't be 8 TC or 6 for an assistant. It doesn't even make sense for an assistant to get a discount if it's not welder-related. A skintone check would be a lot better there, and if you're not going to make this one-use it should be at least as much as the chef cleaver. 

How much damage does this do to the average unarmored person? Can you survive one hit?

**Comment by Dacendeth** [comment]
> How much damage does this do to the average unarmored person? Can you survive one hit?

@BomberBro I tested it a little, seems to do about 130-150 combined damage against an unarmored target, 110-130 to standard sec gear,  50-70 against sec hardsuit, and about 30 to yourself when you're unarmored and hit someone with it.

**Comment by BomberBro** [comment]
\>over 100 damage per hit on a reasonably fast recharging weapon that you can negate the self damage for
Nothing to say but lol at that point, this thing should be expensive as hell and always deal 30-40 brute to the wearer.

**Comment by pedr69** [comment]
could probably also override throw_impact instead of gluing it to your hand
i assume that was the intention, to prevent you from just throwing the thing

**Comment by Eneocho** [comment]
I'll change the costs and look into making a skin tone check.

> could probably also override throw_impact instead of gluing it to your hand i assume that was the intention, to prevent you from just throwing the thing

I honestly forgot throw_impact was a thing, could be implemented that way, though I like the gluing thing.

**Comment by Eneocho** [comment]
It now costs 10, no discount until I figure out how to make it check for skin tone or genetics and does 35 self brute.

**Comment by Eneocho** [comment]
Alright, these are the final numbers: The caber explosion now does 55 brute to an unarmored target, 35 self damage and can't breach.
The admin only caber keeps the old numbers, being able to breach.
@BomberBro, @Dacendeth, does this sound better?

**Comment by tinysaturn** [comment]
cringe
just remove the cooldown and keep the old high damage value
if you want a bunch of these you should have to print them at the mechanic's workshop

**Comment by NigglyWiggly** [comment]
I see you’re trying to lure Deity back
Looks nice though, it might be worth just testing the damage amounts live instead of just arguing it in here

**Comment by SECBATON-GRIFFON** [comment]
aren't damocles already like this sorta? also don't like this being such an overt tf2 reference for some reason

**Comment by nervere** [comment]
This really shouldn't be able to recharge. I agree with a higher damage value but the caber gets destroyed in the process.

**Comment by BomberBro** [comment]
@Eneocho Either that works or making it one-use only so you have to reprint them (which is doable for a traitor mechanic to buy both)

**Comment by Dacendeth** [comment]
I feel like if it was single use it could be it's previous powerlevel. Force after being consumed could be upped to 20 too without much issue, same as a syndie toolbox. 

Side note I noticed when meleeing with it after it was broken it didnt have any hit sounds.

**Comment by Eneocho** [comment]
> I feel like if it was single use it could be it's previous powerlevel. Force after being consumed could be upped to 20 too without much issue, same as a syndie toolbox.
> 
> Side note I noticed when meleeing with it after it was broken it didnt have any hit sounds.

You sure? It has the sounds properly on my end. It is the explosion sound leaving you deaf for a few moments. If you try again on godmode or after rejuvenating your character you'll hear the bonks after the explosion just fine.

**Comment by Theophrastus1** [comment]
I hate this being a heckin epic TF2 reference

**Comment by calzilla1** [comment]
It should be non-rechargeable, be slightly more powerful than a welderbomb, and gib you and your target. Make it like a last resort hailmary weapon

**Comment by Dacendeth** [comment]
Oh you know, it's likely I was deaf come to think of it.

**Comment by calzilla1** [comment]
Make it so that you can only hit people with it if you're severely intoxicated, otherwise you can only throw it

**Comment by Eneocho** [comment]
> Make it so that you can only hit people with it if you're severely intoxicated, otherwise you can only throw it

As it is currently you can throw it but it doesn't explode. It only explodes with the safety grip (which doesn't let you throw it).

**Comment by Kurfursten** [comment]
It looks like overwhelmingly people want it to have no recharge. If you meet this compromise I will merge it.

**Comment by Eneocho** [comment]
At that point it's no different than the damocles. If anything it's weaker but aight. Going to make it single use but stronger like nervere said.

**Comment by pedr69** [comment]
but.. the damocles is infinite use? making the caber recharge would make it basically damocles(but cheaper and also not crit people in 1 hit)

**Comment by Eneocho** [comment]
> but.. the damocles is infinite use? leaving the caber rechargeable would make it basically damocles(but cheaper and also not crit people in 1 hit)

Difference is that Damocles does zero self damage and can be thrown for a last ditch larger explosion. Caber self damages and cannot be thrown if you want an explosion.

**Comment by Eneocho** [comment]
@Kurfursten, done.

**Comment by pedr69** [comment]
bit late for it now but the changelog would make you think its nukeop only
should have probably written traitors instead of operatives

**Comment by Eneocho** [comment]
In hindsight yeah.

**Pull request merged**
