### PR TITLE
Robot components bugfixes

### PR DESCRIPTION
**Pull request by Zth--**
70% tested. I'll do a bit more testing tomorrow

:cl:
- bugfix: Robots components. When replacing a damaged component, the new one remembered the old damage values, so you had to apply nanopaste to fix it. Now you don't
- bugfix: This also fixes a bug where power cell damage can't be fixed (because of a stupid loop). You still have to place a new power cell though.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by Intigracy** [comment]
Put the changelog at the end, not the beginning.

**Comment by PJB3005** [comment]
It wouldn't get parsed anyways because my regex is pretty strict but yes it's not a good idea.

**Comment by clusterfack** [comment]
I don't want to be 'that guy' but it'd be nice if we add some attackby code so that people can repair the robot components when they are outside of the robot as well? I don't know seems like some people might expect it though.

**Comment by Zth--** [comment]
Yeah, I also thought of it. I'll make a PR after this one. I figured out I still have to change some power cell code. It'll be done tonight

**Pull request merged**
