### PR TITLE
New icons for IV drip

### PR DESCRIPTION
**Pull request by CodenameB**
This PR will change the sprites for the IV stands so that now you can tell at a glance if they are set to take blood, or to inject blood. 

Anyone who has played a lot of medbay knows how annoying it is to hook up an critical patient to an IV only to discover the IV bag is further draining his blood because the last doctor never reset it.

This has an added benefit of making the sprites slightly easier to click. Color scheme based on medibots.

image

Idea proposed by https://github.com/vgstation-coders/vgstation13/issues/11104

:cl: 
 * rscadd: IV drip stands now have an indicator light to tell you if they are currently in "injecting" mode or "taking blood" mode.

### CODE REVIEW

**Comment by SkowronX** [comment]
QOL 👍

**Comment by ghost** [comment]
also means more pixels to click on, rather than having to pixel-hunt to drag it onto a person in proximity

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
?!?!?!?!?

**Comment by CodenameB** [comment]
Whoops. Was trying to delete a different branch, and did this one by mistake. Should be okay?

**Pull request merged**
