### PR TITLE
Metaclub changes

### LINKED ISSUE #3502: [Meta] Condimaster layering issues
The renamed Condimasters in Meta's botany and kitchen seem to have some weird stuff going on with their layering.
Any items ejected from them are hidden under the machine, and if you walk away both start z-fighting.
Doesn't happen with Box's condimaster.
ss 2015-03-20 at 01 43 20

### LINKED ISSUE #5116: (WEB REPORT BY: Anonymous REMOTE: ) Metaclub cargo mail
>Revision (Should be above if you're viewing this from ingame!)
206d4433700d08cd52e6c4ac5b3cf2ff37b1f0cf 

>General description of the issue
Metaclub disposal pipes at brig make you stuck. Sent two crates and later myself to engineering

>What you expected to happen
Getting to engineering through cargo mail system

>What actually happened
Stuck in a two-tile loop

>Steps to reproduce if possible
Send yourself to engineering through cargo (and probably any other location, needs testing)

### LINKED ISSUE #5896: (WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Metaclub Medbay needs more lights
>Revision (Should be above if you're viewing this from ingame!)

cd6734ae955158b842b7be1fa48fbec890871007 
>General description of the issue

It's incredibly dark in a lot of areas of medbay, such as the paramedic's office, chemistry, supply area, etc.

### LINKED ISSUE #5981: Can't use the foyer turret control on Metastation as silicon
Just why? My only guess is because telecomms is beyond there, but I don't understand why telecomms has it in the first place, unless it's some balance for people walking in there.

### LINKED ISSUE #6002: METACLUB MEDBAY SUGGESTION
(WEB REPORT BY: gringonius REMOTE: 158.69.55.2:7777)

>f9ea79b5de6e347ab4de7f75d324eb02341b04af 

>MAKE THOSE PLASTIC FLAPS IN FRONT OF THE SURGERY ROOM THE AIR-TIGHT VARIETY, HOLY FUCK
>What you expected to happen

>What actually happened

>Steps to reproduce if possible

### LINKED ISSUE #6478: Metaclub cargo bay has no metal/glass for autolathe
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
37c0b9a61d5d67ffe4539401a346d0b6219915da

### LINKED ISSUE #6479: Security destination tagger just sends the parcel right back into cargo disposals on Metaclub
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
As said

### LINKED ISSUE #6730: METACLUB: Surgery Observation
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Innacessable to medbay and nonmedbay staff. Shouldn't be like this considering it is the Surgery Observation room, a room for anyone to observe a surgery.

### LINKED ISSUE #6731: MetaClub: Left-side vent pump in the SME chamber is bugged
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> http://puu.sh/lvSTD/c879e95513.png
> The vent settings cannot be changed by multitools. Confirmed with two people, not sure if it's always the case.
> 
> What you expected to happen
> A multitool to be able to edit the values of the pump
> 
> What actually happened
> Can open the multitool menu, but can't change any settings.
> 
> Steps to reproduce if possible
> (suit up,e tc)
> Go to the SME room on MetaClub, apply multitool, try to change settings.

### LINKED ISSUE #6732: Meta's cell lockers don't seem to link with the timer
unlocked
This could be with the other lockers or this is just an oversight.

### LINKED ISSUE #6815: Meta map issue
The library carpets are all carpet, until you get to the doors.
The floors directly under the doors are all fucking floor tiles that LOOK like carpet, and they don't even connect to the actual carpet.

### PR DESCRIPTION
**Pull request by Probe1**
### Fixes
- Fixes https://github.com/d3athrow/vgstation13/issues/6730 by removing the access requirement on surgery observation.  Based on additional feedback, removes the access to the recovery rooom door which is just southeast of the observation door.  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161535197
- Fixes https://github.com/d3athrow/vgstation13/issues/6479 by moving the sorting junction to the west so packages come out by the lockers where the Warden and Officers will actually see them.  The original design did not work to begin with and this one is better (and tested to work).  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161535387
- Fixes https://github.com/d3athrow/vgstation13/issues/5116 by removing an errant Engineering sorting junction in Security that was supposed to be a security sorting junction.  I tested it and it still delivers to Engineering just fine without it.  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161535387
- Fixes https://github.com/d3athrow/vgstation13/issues/3502 by removing the pixel_y offset which was causing z level fighting. https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161534010
- Fixes d3athrow#5569 and addresses feedback by putting the bar sign on a wall at the entrance of the bar for better visibility https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161866780
- Fixes https://github.com/d3athrow/vgstation13/issues/6732 .  There is a duplicate Cell Locker 3 which is the hard coded way of making cell lockers work in conjunction with cell timers.  The second one does not function correctly and was used on Metaclub.  Replaced with the first instance of Cell Locker 3, which works as expected.
- Fixes #6731 . Kurfurst came up with the fix. The vents tags were identical to a vent in xenobiology causing a big fuss. The tags in xenobiology were altered.
- Adds engineering access to these two engineering External doors which previously had no access, something restricted to only arrivals and escape doors.  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161539612
### Feature Requests/Improvements
- Overhauls EVA.  Puts engineering and atmospheric hardsuits in separate door locked rooms. Separates the jetpacks to have 1 per EVA subroom rather than 2 in Engineering. Brings the metal+glass in line with Box. Adds 3 space suits (gray, slow, general suits) in SSUs that only require EVA access to attain. Adds a cell charger, some welding helmets and toolbelts, tools, and most importantly station bounced radios.   https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161849407
- Overhauls Xenobotany to bring it in line with Box.  Adds Botany vends, xenobotany machines, sandstone for making new dirt trays, disks, a grinder, plant analzyers, 8 hydroponic trays to replace the 6 dirt trays, a seed extractor, biogenerator and smartfridge.  In addition, five connectors were placed to connect to 4 hydroponic trays plus a spare to connect a canister to for gas study.  Plus some windows.   https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161849634
- Resolves https://github.com/d3athrow/vgstation13/issues/6854 by adding 4/6 requests.  See same image for the majority of the work, the remainder is just adding gloves and such. https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161849634 
- Resolves #6002 by copying the design from medbay rather than adding airtight plastic flaps. This brings medbay in line with all other delivery points on Metaclub without giving them special flaps. https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161533775
- Resolves https://github.com/d3athrow/vgstation13/issues/5896 by adding a single light to paramedics area.  This issue was mostly covered at the time it was made by a previous PR and I went over the department again.  The only location that was still too dark was the one back corner of the paramedics room.  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161534728
- Resolves https://github.com/d3athrow/vgstation13/issues/5981 by removing the firewall on the turret control.  This was placed because it was a copy/paste job from Box.  There was a discussion, and the discussion favored removing the firewall rather than redesigning telecomms.  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161534233
- Resolves https://github.com/d3athrow/vgstation13/issues/6478 by adding 50 glass and 50 metal to an open crate in the center of the cargo bay. I think it feels natural this way and there isn't a lot of bare table room to work with in the Lobby.  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161535083
- Replaces the atmospherics reinforced table with atmos windoors like how it is on Box. This was supported during feature freeze by players and frankly atmos is just awful to navigate when you're in an emergency.  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161533902
- Adds a pair of lights to the maintenance tunnel between genetics, medbay, and the morgue based on player feedback.  It's not true maintenance, it's just a service tunnel that medbay personnel have access to (unlike true maintenance which medbay personnel do NOT have access to).  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161534728
- Moves Botany All-in-one Grinder to the NE corner next to the brewmaster, removes the funky double airlock business to Botany, shifts two water tanks to the now free place. https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161533970
- Redo on the flooring for the theater to make it more pleasant to look at.  https://github.com/d3athrow/vgstation13/issues/6845 .  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161535440   This addresses the Metaclub half of this issue but not the Taxi half.
-  Resolves #6815 by removing that fake carpet and adding real carpet. https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161534481
- Swaps the gibber, snackbar machine, and meat fridge locations to make space.  Also removes the second meat spike because I swear to god it is never needed and there's plenty of metal around to make more.  https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161859459

### CODE REVIEW

**Comment by ghost** [comment]
Move botany grinder closer to other machines.

Make bar / kitchen somehow more visible. There's no hallway table.

**Comment by Probe1** [comment]
@TermedClepe at this point should we just nix the whole double airlock entrance?  Does this room really have a reason to exist, and is there anything we can add back to fill it?

image

**Comment by Probe1** [comment]
Jolly map cleaning mistakes.

**Comment by ghost** [comment]
> sink behind airlock

Yes purge with extreme prejudice. I guess some decorative plant pot to fill the empty space, meta botany is pretty well stocked already.

**Comment by Probe1** [comment]
Okay here's the picture documentation for everyone.

New mule entrance.

new mule entrance

**Comment by Probe1** [comment]
Windoor for atmos so people can enter atmos during an emergency without taking the circuitous route.  This was asked for and honestly a good thing to copy from Box.

atmos windoooro

**Comment by Probe1** [comment]
Nixed the double airlock in botany and moved the grinder to be with the other machines.  

botany door removed and items shifted

**Comment by Probe1** [comment]
This was the condimaster in question that had z level fighting.

condimaster z fighting

**Comment by Probe1** [comment]
Removes firewall access here, based on feedback from the issue and pomf saying it was there because of copypaste rather than balance.

firewall

**Comment by Probe1** [comment]
100% more shag, 100% less tiles painted as carpet for the library.

library carpet

**Comment by Probe1** [comment]
Lights for medbay.

medbay light

medbay maint lights

**Comment by Probe1** [comment]
Metal/glass for cargo in the best place I could put it to make it feel like it was put there by a person.

metal and glass for cargo

**Comment by Probe1** [comment]
Removes the access on the two doors here.  Surgery observation and the "recovery area" door.

removes access too this dooro

**Comment by Probe1** [comment]
Fixes disposals by adding a sorting junction in the southwest of the screenshot and a normal 3 way pipe in the northeast.  Also fixes the engineering issue.

security disposals rework

**Comment by Probe1** [comment]
Adds carpet and wood flooring to the theater based on Socas feedback.

theatre carpet

**Comment by Probe1** [comment]
Adds engineering access to these two engineering External doors which previously had no access, something restricted to only arrivals and escape doors.

vgstation13_ mapsmetaclub dmm _-_dream_maker_2015-12-03_02-21-25

**Comment by Probe1** [comment]
Tentative EVA redo, needs feedback.

old

**Comment by Probe1** [comment]
Final version of EVA up for review.  I've received positive feedback in game and in the thread/steamchat.  If no one objects to it I'll commit it and finalize this PR.

image

**Comment by IratePirate** [comment]
Good on you mate. These are some good fixes and changes.

**Comment by Probe1** [comment]
GImme your opinion on EVA @IratePirate .  I need help on this one to decide whether or not to commit it.

**Comment by IratePirate** [comment]
I think it looks better, I tried with the original one but it was honestly just too cramped and artificial. Your version seems more like an actual chamber where you can grab stuff, plus it's a lot more symmetrical which is always nice. On the other hand I don't think anyone likes 1 tile wide areas to move around in so i'd think about the tables.

**Comment by Probe1** [comment]
I was thinking about that in my head and thought it was a nice way of drawing a line between the slow gray space suits on the left and the hardsuits on the right.

If it's a selling point I can lose at least 2 tables, maybe all four, and relocate/prune the items.  Wouldn't be the end of the world if there weren't flashlights.

**Comment by IratePirate** [comment]
Since there are two entrances/exits you could turn each of them from two doors into single doors, and then move the tables so they are up against the walls or something like that. They are only double doors now because when I was doing up the map before I had the "make it consistent with Box" mindset, which in hindsight wasn't a good idea.

By the way, what's the light blue tank? A foam tank? It's been a while since i've regularly played SS13 since i've been busy with studies.

**Comment by Probe1** [comment]
Silicate was re-added to the game last month so we can repair windows without disassembling them (silicate sprayer + silicate, which comes in tanks or is chemistry producible)

We had the same idea about tables against the walls but I don't think we'd have to narrow the doors.  This feels like the best alt design I could come up with in 5 minutes.  

image

**Comment by IratePirate** [comment]
Now that just looks straight up ugly. Though maybe floor tile changes with hazard strips or tileless floors under the spacesuit dispensers might help it.

**Comment by Probe1** [comment]
I was thinking the same thing.  SSUs in the middle of the room look weird.

**Comment by Probe1** [comment]
alt2: emptyspaceville

image

alt2 with filler
image

**Comment by IratePirate** [comment]
Honestly you might just want to go back to how it was two pictures ago and try to fit them onto 9 tables instead of 12 without a gap in the middle.

**Comment by Probe1** [comment]
As so?

image

alt 2
image

**Comment by IratePirate** [comment]
Yeah that could work, though it's up to your discretion.

**Comment by Probe1** [comment]
I think alt2 of that third set of images is the best 'room feel' to me.  I'll leave it up to you to decide, how it was originally https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161601914 or that final image above

**Comment by IratePirate** [comment]
You're making the changes, you can do what you want man. I have no real stake in the map.

I would probably do the final one because it mixes accessibility and not being empty. But emptiness can be alright so long as you break the emptiness up with floor tile designs or overlays.

**Comment by Probe1** [comment]
Yea but no ones spent more time than you on it so you rightfully will have the most experienced opinion on it.  I'll go with the final one and cut the fat, players won't _need_ flashlights and it has a nice illusion of fullness without actually being narrow like the original image.  I'll tune it up.

**Comment by IratePirate** [comment]
10/10 maintenance update. Maybe people will start playing the map more.

**Comment by ghost** [comment]
Speaking of z level fighting, I believe the machine in top right corner of botany is always drawn on top even when you eject beakers from it.

I'm also pretty sure kitchen doesn't have a snackbar machine on meta, but I could be mistaking this for something else.

**Comment by Probe1** [comment]
Alright EVAs done (hopefully)

vgstation13_ mapsmetaclub dmm _-_dream_maker_2015-12-03_08-29-05

I'll look at the brewmaster in Botany and let EVA sit for 12 hours before committing it to give the rest of the players a chance.

**Comment by Probe1** [comment]
@TermedClepe Yep, its the same as before.  The machine is offset to pixel_x = -4.  That's the same technique I used in the EVA images to separate the stacks of metal and radios (though I just copypasted the radios from the gateway).  It works really well with objects that aren't on top of containers but works very badly for machines.  Causes zlevel fighting.  

The same things occurs in Telecomms on Box with the oxygen tank dispenser.  I'll make this note of it and fix it before I remove the DMN title.
image

**Comment by FudgePucker** [comment]
Wait, quick question.
Wouldn't it be a bad idea to have it be just two window doors separating the main hallway from the second best rigsuit in the game?

Seriously, just take a tool box to it and then you are immune to atmospheric problems and have brute resist. EVA at least has shocked windows.

The dual windoors on box works because it just opens into atmospheric monitoring, then its two airlocks that need to be hacked to get to the atmospheric rigsuits. You smash the windoors on box you can still do damage to the station with the monitoring computers, but it takes more time to fuck with them than just putting on a rigsuit.

Make them start locked at least.

**Comment by PJB3005** [comment]
@FudgePucker shocked windows are a joke anyways, pick up the glass shard and destroy the grille with that (glass doesn't conduct electricity), proceed with toolbox.

**Comment by PJB3005** [comment]
:+1: :x: :100: 

Meta needs more love.

Also, while you're at it, could you fix the `pixel_y` on the north facing windows at meta's escape, it looks stupid.

**Comment by FudgePucker** [comment]
@PJB3005 You also forgot that EVA has motion detectors that alerts the AI as soon as someone enters it, and also it is in a major hallway, not in engineering hallway.

**Comment by PJB3005** [comment]
Er?

**Comment by FudgePucker** [comment]
Doesn't Metaclub have cameras that have the motion detection in EVA like box does?

**Comment by PJB3005** [comment]
Oh, right, nobody cares anyways.

**Comment by Probe1** [comment]
Yes, I diligently added a motion sensor camera to Meta EVA next to the hardsuits.

**Comment by FudgePucker** [comment]
Sooo you think no one is going to care that getting access to one of the few hardsuits that makes you immune to plasma is now easy to access, meaning that you can plasma flood without killing yourself.

Nothing bad will come of this.

I would agree with you if it was just the engineering rigsuit, but this is the ATMOSPHERIC rigsuit.
Those two measly windoors will be smashed every round.

**Comment by Probe1** [comment]
@FudgePucker  It's under more stringent protection than before (It's now locked behind atmos access so only the CE, Engineers, and Atmos techs can get them, rather than that + Mechanics) and has electrified grilles and rwindows.  The only change here for atmos suits is they're now in a separate room inside EVA rather than in the same room as the Engineering hardsuits.

This is the same level of protection as Box.

**Comment by FudgePucker** [comment]
Is there reinforced plasma glass windoors?
That would at least make it a little less easy to bust in for those three tasty atmospheric rigsuits.

**Comment by Probe1** [comment]
Those aren't atmos space suits, they're regular gray ones.  They protect against almost nothing, except space.
image

**Comment by FudgePucker** [comment]
Why are there normal gray space suits in atmospherics monitoring?
You do know what area I am talking about right?
EDIT: I am looking at the third image you posted

**Comment by Probe1** [comment]
@FudgePucker I don't follow.  Atmos monitoring has 3 atmos hardsuits.
ishimura_fortification_12_2015-12-03_20-48-06

**Comment by Probe1** [comment]
EVA Overhaul image for the OP

augmented_spess_waypoint_omicron_2015-12-03_20-53-51

**Comment by Probe1** [comment]
Xenobotany

augmented_spess_waypoint_omicron_2015-12-03_20-58-29

**Comment by FudgePucker** [comment]
Yea I know I fucked that up and thought I saw six, I really need to get my vision checked, but still, three atmospheric rigsuits that easy to get?

All you need is one traitor to grab one.

**Comment by Probe1** [comment]
Its ok.  I don't know if atmos hardsuits should be more protected or less, adding a windoor to the room does open a vulnerability.

**Comment by Wizardcrying** [comment]
Why is the gibber not one tile southeast?

**Comment by 9600bauds** [comment]
> axing the dubbleairlock on botany

I-I kinda liked it

**Comment by Probe1** [comment]
WELLTOOBAD

@Wizardcrying you meant southEAST right?

**Comment by Probe1** [comment]
Swaps the gibber, snackbar machine, and meat fridge locations to make space.  Also removes the second meat spike because I swear to god it is never needed and there's plenty of metal around to make more.

image

**Comment by FudgePucker** [comment]
@Probe1 
I guess I might just be over reacting about atmos hardsuits.
I think it is the second item on the list of getting the holy grail of powergaming, first being captains access, third being yellow gloves.

**Comment by 9600bauds** [comment]
I'd argue that glubbs easily take the second place

**Comment by FudgePucker** [comment]
Eh, they are both fighting for it, I think being totally immune to plasma flooding/space/high pressure and having the bonus brute resist and syringe gun resist is better than just hacking tools.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/pull/6847#issuecomment-161505949  I think this goes a long way.

vgstation13_ mapsmetaclub dmm _-_dream_maker_2015-12-03_23-05-24

**Comment by Probe1** [comment]
suck my dick travis

```
loading vgstation13.dme
loading interface\skin.dmf
loading metaclub.dmm
saving vgstation13.dmb (DEBUG mode)
vgstation13.dmb - 0 errors, 0 warnings (12/4/15 2:32 am)
```

**Comment by Faptastic** [comment]
Might want to throw in the cargo desk bell as well for good measure, now they have it on box they want it for them all. Fair enough really.

**Comment by Wizardcrying** [comment]
After these changes, I'd take Metaclub as a good alternative to Box.

**Comment by Arthurdentist** [comment]
shutter

Someone pointed out to me earlier that on meta the PA shutters don't actually cover one of the doors.

**Comment by PJB3005** [comment]
HABBENING

**Comment by Probe1** [comment]
>PR gets merged
 >People make more issues
you don't understand!  it was supposed to clear the page!

**Pull request merged**
