### PR TITLE
ied-beartrap overlay and reference bugfix

### PR DESCRIPTION
**Pull request by RealestEstate**
image

adds ied overlay on beartraps
also removes used up ieds from beartraps after they kaboom. Before this if an ied blew up you had to screwdriver the non-existing ied from the beartrap before you could put a new one in.

[bugfix]
[sprites]

:cl:
 * rscadd: Jury-rigged explosive beartraps now have an overlay
 * rscbug: Fixed an error with ied-beartraps that prevented you from rerigging them after the ied exploded.

### CODE REVIEW

**Comment by RealestEstate** [comment]
[bugfix]

**Comment by DrSnips** [comment]
The magic words are still there. Stuff from the DID dimension has appeared and disappeared.

**Comment by RealestEstate** [comment]
@DrSnips I don't understand.

**Comment by iFlashYou** [comment]
[Balance]

**Pull request merged**
