### PR TITLE
Tape recorder uses say(), so it can talk through intercomms

### PR DESCRIPTION
**Pull request by 9600bauds**
:cl:
 * tweak: Tape recorders can now speak into intercomms, radios, etc.

### CODE REVIEW

**Comment by optimumtact** [comment]
rude af

**Comment by Shadowmech88** [comment]
Tape recorders currently don't display the name of the person saying the message on playback, right?
Should they?

If you can recognize someone's voice via radio, why wouldn't you recognize their voice via tape recorder?

**Comment by 9600bauds** [comment]
They also act as universal translators currently

**Comment by Ephx1** [comment]
"State name" command when????

**Comment by SonixApache** [comment]
In a perfect world, tape recorders would record doors opening, footsteps, explosions and other sound effects. On top of being able to judge the distance between the recorder and sound source, and being able to tell if a sound is coming from a radio or not.

**Comment by ComicIronic** [comment]
Why on earth do we have two copies of the same style file in a cascading file format that is entirely intended to have inheritance?

**Comment by 9600bauds** [comment]
idunno lol but it wouldn't work otherwise

**Comment by Probe1** [comment]
What's the status of the PR?  Ready?  Tested?  Do you have a numberphile reaction image for it?

**Comment by 9600bauds** [comment]
firefox_2016-12-19_22-43-41

**Comment by Probe1** [comment]
Tape recorders need a lot of quality code.  The comments in this PR drive home how awful some of their aspects are and I'm willing to bet they're ancient.  

But that's not in the scope and not terribly fair to say you must fix everything wrong in the game if you want to add to it.

**Comment by 9600bauds** [comment]
In one hand, tape recorders could really use to log the identity of who spoke

On the other hand, "Male Speaker \#2" sounds so much more noire-ish

**Comment by Probe1** [comment]
Either way works as long as either way is done.

**Comment by Probe1** [comment]
STATE YOUR NAME

**Pull request merged**
