### PR TITLE
Construction in Progress

### PR DESCRIPTION
**Pull request by MadmanMartian**
image

### CODE REVIEW

**Comment by jknpj** [comment]
at least make it mobs that can break walls

**Comment by DrSnips** [comment]
They took our tabe but they will not take our steel beams.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Can we at least make this kind of shit not be instantaneous

**Comment by Irradiation** [comment]
>Clown goblin waltez up to medbay
>Instantly breaks every RTable on the front desk
>people make girders to block the goblin
>goblin instantly JUST's the girders

What a world we live in

**Comment by MadmanMartian** [comment]
why the fuck does a clown goblin have break_light_structure?

**Comment by Irradiation** [comment]
Because simplemobs are magical things.

**Comment by ShiftyRail** [comment]
I am vehemently against this change so long as a mob going even near you still results in bone breaking or internal bleeding.
I once was in full HoS gear and wielding a riot shield fighting zombies, and only one hit broke my foot and as a result slowed me down for the rest of the round.

**Comment by MadmanMartian** [comment]
Update:
Girders that are secured to the floor require the mob to have SMASH_WALLS
Girders that are not secured require the mob to have SMASH_LIGHT_STRUCTURES, and have a damage gate that the mob has to surpass. 30 is minimum, with a reinforced displaced girder requiring 50 damage.

Still working on the logic. Hang on.

**Comment by Irradiation** [comment]
You realize that most naughty mobs deal 15 damage or so per hit and they magically breach everything faster than players can, right? If you're still going to go on with this idea, then make it so it takes about as long for mobs to break a girder as it takes a player to wrench it down or something.

**Comment by MadmanMartian** [comment]
do_afters in simple animal code tend to cause serious issues.

**Comment by Irradiation** [comment]
It's simple. We remove simple mobs and replace them with decoy balloons that move around.

**Comment by d3athrow** [comment]
shitty compromise:
give structures health and make it high enough (based on type and material used and any reinforcements) that simple animals don't just blow through them in a single life tick.

If a structure is reinforced then the structure has stages of damage that somewhat correlates to the reverse construction. IE r-wall > plasteel reinforcement destroyed > reinforced girders exposed > reinforcement destroyed > girder dislodged or destroyed

**Comment by MadmanMartian** [comment]
Nuclear option it is, as decreed by head chicken

**Comment by d3athrow** [comment]
@MadmanMartian 
An opinion and proposal isn't a decree

**Comment by Exxion** [comment]
Well it's a good idea anyway
Honestly we should have added a simple health system to all `/atom`s (or at least `/atom/movable`s) long ago

**Comment by MadmanMartian** [comment]
image

**Comment by Exxion** [comment]
It doesn't have to be *used* on everything
But the fact the system is present higher on the tree would allow objects that should take damage do so without a ton of boilerplate

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Honestly make a new PR for the new thing

**Pull request closed without merging**
