### PR TITLE
Tradeship Turfs

### PR DESCRIPTION
**Pull request by Kurfursten**
Just to remove the tedium for some gimmicks. Previously, Metaclub and Waystation already had non-shuttle turfs for trader shuttles. This moves all other maps to that system. Easier to paint or replace with wood, easier to move machines in. Just better in general.

🆑 
* tweak: Trade ships are now made of normal turfs, which makes them easier to destroy but more machine and gimmick friendly.

### CODE REVIEW

**Comment by Servalfang** [comment]
speedmerge

**Comment by DamianX** [comment]
MapDiffBot makes sense for roid, but its output is puzzling for the other maps. Is it bugged or is there something wrong with the changes?

**Comment by Kurfursten** [comment]
> 
> 
> MapDiffBot makes sense for roid, but its output is puzzling for the other maps. Is it bugged or is there something wrong with the changes?

You've fallen for the classic blunder. Mapdiffbot is showing the location of the tradeship if you transplanted it from Z5 to Z1 but kept its x/y the same. Roid is the same because it's always on Z1.

**Comment by Kurfursten** [comment]
Damn you Synergy

**Pull request merged**
