### PR TITLE
Blood Cult Season 1

### PR DESCRIPTION
**Pull request by DamianX**
Have you ever wondered what civilians are supposed to do whenever a fight between security and the blood cult ensues?
Should they run and hide? Should they join security? Should they *join the cult*?
The answer is **YES** to all of the above, but first, a word from our sponsor:
 

> This year's Thunderdome takes place on **your** station, and it's sponsored by Spess.TV, the galaxy's only source of online video gaming streaming services!
> NanoTrasen also partnered with Donitos and Geometer for the event! Crew members who previously didn't know what to do when the Code Red alarm started going off can now kick back and relax, grab a bag of Donitos or cans of Geometer and watch a real-time feed of their favorite Team Security or Team Geometer streamer fight for what's right! (according to their respective moral/value system!).

# Introducing Blood Cult 3 Season 1!
The E-Sports Chaplain (also known as Donitos Pope) receives a stack of flatpacks containing:
- 2x Spess.TV entertainment monitors
- 1x Team Security merch vending machine
- 1x lockbox containing Team Security's tactical Spess.TV streaming cameras, to be distributed among Team Security members.
dreamseeker_PQYHnBqVk6

**As a security officer**, ask your local Donitos Pope for a tactical camera to begin streaming for your audience.
image

image

**As a blood cultist**, simply cast the sponsored Stream rune (other see self) to begin streaming for your audience.

dreamseeker_VPnWCLrpdT
dreamseeker_1yBdVELTJldreamseeker_aLPIIK8v6Y
Team Security's HUD keeps track of the number of successful hits. 
image
Whenever the officer hits a target, an audiovisual effect plays.

image

Team Geometer's HUD keeps track of the number of successful conversions.
dreamseeker_Dc7JYXHt6i
## Double XP weekends!
**Earn up to 2x** the amount of points for each successful hit or conversion during the weekend!
image
## Following and subscribing!
While all entertainment monitors are tuned to Spess.TV, only Certified Spess.TV CRT monitors and flatscreens have built-in integration with Spess.TV Live Services, allowing users to follow and subscribe to their favorite streamers.
Following is **FREE**! Show your favorite streamer that you care about them!
dreamseeker_Ivf4fJS5ta

Subscribing, instead, costs only 250 credits - it comes with rewards for both the fan and the streamer! Get your lootbox!
dreamseeker_2Mj4Roks2f
Don't forget to get your limited-time exclusive e-sports gear from the chaplain's merch vending machine!
Each and every piece of clothing is unique: get your numbered shirt today!

dreamseeker_aIsASrHaBT

:cl:
* rscadd: Added the E-Sports chaplain, Spess.TV, Team Security merchandise, Donitos, Geometer!
* rscadd: Added streaming, following, subscribing!
* rscadd: Added double XP weekends!
* imageadd: Awesome sprites by @otatoh, @RealestEstate and CEV-Eris, awful sprites by me

### CODE REVIEW

**Comment by SkowronX** [comment]
nigga did you seriously just

**Comment by DeityLink** [comment]
>speedmerge
🤦‍♂ 

Look shifty I want this in as much as the next guy but please respect due process.

**Comment by DeityLink** [comment]
case in point #25936

**Comment by ShiftyRail** [comment]
01/04

**Comment by DeityLink** [comment]
oh, well duh then

**Comment by beesil** [comment]
Merge speedrun any%

**Comment by ghost** [comment]
based

**Comment by djkramer123** [comment]
Reading this felt like a fever dream.

**Comment by Zach720** [comment]
finally, speedy merge, no waiting, no beating around the bush, and, its a change to cult, good fucking job

**Comment by SonixApache** [comment]
why wasn't this reverted yet?

**Pull request merged**
