### PR TITLE
64x64 Sprites

### PR DESCRIPTION
**Pull request by clusterfack**
A joint project between @PJB3005 and myself. 

It seems @tgstation will be attempting this venture as well:
https://github.com/tgstation/tgstation/pull/19566

**What is 64x64?**
At its core this means we are doubling the resolution of the ingame tile. This means that any sprite with double the resolution will take up the same number of tiles.

**How does 64x64 work?**
This PR does the following:

- Using a script, doubles the resolution of all 32x32 sprites in the game using nearest neighbor interpolation
- Using a script, doubles the pixel offset of all map based entities to account for the new tile size
- Using a define, doubles the pixel offset of all code based pixel offsets
- Using a define, doubles the pixel offset of all screen locs
- Doubles the values of contextual click parameters, without a define
- Increases the offset and width values of maptext
- Increases the font size of maptext

**Why 64x64? Why this PR?**
To be clear, in its current form the game looks **identical** to what we have right now, that is the exact goal of this PR specifically, to replicate the current game but with double the resolution.

64x64 will allow us to reach a new level of detail not seen before in the game, and some areas of the game sorely need it (human icons). But the new level of detail possible simply cannot be understated.

**Whats the long term goal of 64x64?**
The long term goal is to gradually update whole groups of sprites to give them a higher level of detail. These groups would look something like

- Turfs/walls
- Human mobs
- SImple animals
- Machines
- Computers

By updating them as a group I am confident we can minimize the effect of "mixels" on making the style consistent.

### CODE REVIEW

**Comment by 9600bauds** [comment]
Anyone test performance of icon procs yet?

**Comment by clusterfack** [comment]
I have not, though blend() is the only primary icon proc still being used and necessary. The only cases in which that should be really apparent are bicon, cameras, and blood update icon.

**Comment by 9600bauds** [comment]
Oh GOD
CAMERAS

**Comment by clusterfack** [comment]
Praying for http://www.byond.com/forum/?post=2039888

**Comment by GeneralGoose** [comment]
why not 2048x2048

**Comment by NigglyWiggly** [comment]
Can we please just not

**Comment by Aurantiaco** [comment]
please stop

**Comment by kol1th** [comment]
:frowning:

**Comment by Aurantiaco** [comment]
>some areas of the game sorely need it (human icons)

do NOT touch the fucking humans jesus h jimminy cricket what is wrong with you that shit is iconic

**Comment by SkowronX** [comment]
Not sure if want.

**Comment by AutismSpider** [comment]
just make 64x64 size mommis spiders and cyborgs and call it a day.

**Comment by clusterfack** [comment]
@GeneralGoose Because 64x64 is much much closer to the size of the typical monitor these days, anything above it for the next few years would be useless.

**Comment by kernikov** [comment]
I like how the excuse goof is using for TG is that they can just steal from us to make it easier,
and for us you're trying to sell it as a joint venture.

Where's the discussion tag, this is clearly a big meme.

**Comment by clusterfack** [comment]
Well considering I started this before them, I'm not trying to use them to do anything.

**Comment by DrCelt** [comment]
Sounds fun. Let's do it.

**Comment by NigglyWiggly** [comment]
Get started on spriting everything then, Celt.

**Comment by DrCelt** [comment]
@NigglyWiggly This PR doesn't even necessitate that, though.

**Comment by clusterfack** [comment]
I made it quite specifically in this manner so that it WOULDN'T require immediately respriting everything in the game at once.

**Comment by gbasood** [comment]
>do NOT touch the fucking humans jesus h jimminy cricket what is wrong with you that shit is iconic

time to go back to the old human sprites

**Comment by clusterfack** [comment]
With hardcoded clothing that doesn't use overlays, for funsies

**Comment by DrCelt** [comment]
The human sprite **should** be changed, but it should just be a higher resolution version of the sprite we have right now, shape and otherwise can remain the same, for two reasons: One, Who would want to resprite every single article of clothing, and two, it is iconic. 

But the idea it shouldn't be changed at all, even if just to make it higher resolution, is a rather luddite idea.

**Comment by Nienhaus** [comment]
As soon as a new human is sprited I will start spriting clothing.

**Comment by MrStonedOne** [comment]
***Minor*** thing to keep into account: http://www.byond.com/forum/?post=2125489

**Comment by clusterfack** [comment]
@9600bauds I tested blend() with maprendering test_box, it only increased the operational time from 2 minutes to 2 minutes 30 seconds. I think it's pretty fine. With that and with @PJB3005's lobby image fix and fixing conflicts I think this will be good to go now.

**Comment by Jeroen52** [comment]
What.

**Comment by PJB3005** [comment]
That

**Comment by 9600bauds** [comment]
In the butt

**Comment by Megamaw** [comment]
Uhh, wow, merged that game-changer kinda fast didn't ya

**Comment by optimumtact** [comment]
>To be clear, in its current form the game looks identical

**Comment by Blithering** [comment]
So long as noone minds if I keep spriting in 32x32

**Comment by DrCelt** [comment]
:100:

**Comment by NigglyWiggly** [comment]
Fucking excuse me

**Pull request merged**
