### PR TITLE
Fixes the decloner

### LINKED ISSUE #4916: (WEB REPORT BY: Anonymous REMOTE: ) Decloner does no clone damage
>Revision (Should be above if you're viewing this from ingame!)
a29d5035cc42ef51293392e5af017b0606bf1401

>General description of the issue
Decloner only irradiate, it does no clone damage

>What you expected to happen
That my test target get clone damage

>What actually happened
Radiation

>Steps to reproduce if possible
Use a decloner

### PR DESCRIPTION
**Pull request by Zth--**
Fixes #4916
It may need balance?

### CODE REVIEW

**Comment by AutismSpider** [comment]
>25 clone damage a hit

>even a little bit of clone damage makes you useless sac of meat that cant grab and can bearly call out for help or walk for that matter.

make it like 10 or 15

**Comment by Skullyton** [comment]
Clone damage is nasty, even at low amounts like 30 to 40.

With 2 shots putting you at 50, that's a death sentence.

**Comment by PJB3005** [comment]
Frankly 5 might be where you need to put it.

**Comment by Probe1** [comment]
@AutismSpider is right on this one.  The trade off is you aren't stunning people.  Granted you could stun them first and then stack clone damage on them.

But yeah, that's definitely a 1-2 shot weapon.  5 clone damage is far too low.  25 is far too high.  Bridge it and go 10-15.

**Comment by FudgePucker** [comment]
Clone damage might be a little too good for a protolathe weapon (if it is a genetisist traitor weapon they are already the faggiest traitors with out a op weapon)

Making it do radiation damage instead might be better. Chances of mutations, a death sentience if they don't make it to medbay, and can turn a cold into embolaids. However it is treatable outside of cryo and a rare xenobotany chem.

**Comment by Probe1** [comment]
There's already a rad gun.

**Comment by FudgePucker** [comment]
Oh yea that's right, but still, clone damage fucking sucks. There's a reason slimes are feared

**Comment by Zth--** [comment]
It requires combat 5. That doesnt happen that often. Also, dont forget that plasma cannons can be made on protos and are super deadly. 
12 sounds fair to me, I'll make a commit when I go home

**Comment by AutismSpider** [comment]
Combat five not that hard to get unless you happen to be brain damage and know nothing about R&D

**Comment by Zth--** [comment]
Most people just tend to forget about it

**Pull request merged**
