### PR TITLE
Box Ghetto Bar Maint Changes

### LINKED ISSUE #4654: Under JOBS_HAVE_MINIMAL_ACCESS config, Botanists don't have access to Hydroponics hallway airlocks
Minimal access too minimal
Happens in Box, untested in other maps

### LINKED ISSUE #14957: Possible HoP traitor issue?
http://i.imgur.com/CCQzM56.png
I escaped on pod as HoP traitor (very low roll rate by the way) and didn't get my greentext even though I survived.

### LINKED ISSUE #20420: Bring back the Excavation Hardsuit on Box
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
23d284d870c417754ce95bf1e927aad92ff47d91

# Description
As far as I was aware the survivor suit was meant explicitly for roidstation, it shouldnt be popping up on box should it?

### LINKED ISSUE #20721: BoxStation CMO's Privacy Shutters lack a control button
(WEB REPORT BY: archinist REMOTE: 172.93.109.202:7777)
# Revision
87d970ac96f38421a18b634ca7d4ea9a739095c4

# The privacy shutters on the CMO's office on Boxstation cannot be opened or closed normally, as they lack a shutter button

# Steps to Reproduce

Load up BoxStation, walk to CMO's office, look at shutters on windows, look for a button to raise/lower shutters, fail miserably

# What you Expected

I expected a control button to close and open the shutters

# What Actually Happened

There was no button to raise or lower the shutters, such a shame

### LINKED ISSUE #20742: boxstation mommi nest still has improper firelocks
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)

triggers from the coldness of space

### LINKED ISSUE #21973: box genetics inflatable shelter blocks the room's scrubber
[box]
The inflatable shelter in the genetics room on boxstation inflates over the scrubber, preventing the room from being scrubbed unless someone goes in and moves it. Either moving the fire alarm or moving the scrubber would fix this.

### LINKED ISSUE #22020: No crowbars on arrivals shuttle
(WEB REPORT BY: autisticmouse REMOTE: 206.221.180.138:7777)
# Revision
e2adab7432543216b9babc334ff5d3440c4e306c

# Description

On box, there doesn't appear to be any crowbars on the arrival shuttle, so in terms of power failure you have to smash your way out.

# Steps to Reproduce

# What you Expected

Atleast one crowbar.

# What Actually Happened

0 crowbar.

### LINKED ISSUE #22549: Box Security is a mess
Unplayable

Untitled

[box] [easy] [first] [oversight]

### LINKED ISSUE #22749: Box nu-bridge still has a trash compactor
Seems Lazy

### LINKED ISSUE #22822: Make Box Brig Gr8 Again
#### Description of issue
Over time the brig has become the sleazy Security powergamers plaything. The brig needs to be put back into the players' hands once again.

#### Difference between expected and actual behavior
You used to could have a good time in the brig, now you can only have a good time in the brig if you're a sec officer or someone with access.

I've included a picture with two simple changes which would greatly improve box brig.

image

### LINKED ISSUE #23202: Boxstation air injector in toxins is off by default, cannot be turned on directly
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 206.221.180.138:7777)
# Revision
efdc09934e060ed1aee967004ae59a22dd6019e0

# Description
See the title; due to lack of nearby atmos computers the injector cannot be activated normally. 
# Steps to Reproduce
Use toxins, making sure to follow the wiki's instructions about the pumps.
# What you Expected
Gas goes into burn chamber.
# What Actually Happened
Nothing, struggle to figure out what's going on until admin tells me that no gas was going in.

### LINKED ISSUE #24104: BoxStation wood under gateway maint airlock
(WEB REPORT BY: incakola REMOTE: 206.221.180.138:7777)
# Revision
be7fa031c20379fc956a2792473b75be8d500465

### LINKED ISSUE #25754: box tcomms isn't connected to the grid
[box] [why] [and how]
#### Description of issue
here I've drawn a stunning visualisation of how the wires on Box are set up near tcomms
image

#### Difference between expected and actual behavior
tcomms invariably loses power on Box instead of actually functioning

#### Length of time in which bug has been known to occur

honestly it's probably been this way since tcomms was reworked to how it is currently

#### Server revision

4d2a5ba161d36be983ea882a7ed73822a72206b7

### LINKED ISSUE #25799: Plating under the arcade in Box perma is vox shuttle plating
(WEB REPORT BY: lunstra REMOTE: 206.221.180.138:7777)
# Revision
9b2511f9c61d70d99053697419373810ee62d877

# Description
Exactly what it says on the tin
# Steps to Reproduce
Try and put floor tiles down or anchor shit and be amazed as you cant do jack
# What you Expected
Plating to work
# What Actually Happened
Plating was shuttle turfs?????

### PR DESCRIPTION
**Pull request by Kharkov72**
[box]
I wanted to clean and condense it a bit, quite simply. It's not supposed to be derilect, you know?
Some notable changes include:
-The removal of the grug room, with the monkey cult room being in its place
-Expanding the pod bay slightly
-Unblocading the gym and adding kamina's cape to it
-Moving kamina's glasses onto the greyshit because it looks cool
-Condensing the art room.
-Expanding the draped room slightly
east
west

Here is the before of the east:
current

This also:
Closes #22549
Closes #22822 (Worked on in another pr already merged, and also the ramblings of nuke)
Closes #23202 (Already Fixed)
Closes #22749 (Already Fixed)
Closes #22020 (Become more robust like I did when I learned you can just kick your shoes at the windows to break them)
Closes #21973
Closes #20742
Closes #20721
Closes #20420
Closes #14957 (Never got more info to investigate)
Closes #25754 (This fixes the one part of it actually not a feature, that being two pipes in one spot)
Closes #25799
Closes #24104
Closes #4654

:cl:
 * rscadd: Northwest Box Maint has been cleaned and tidied up a bit!

### CODE REVIEW

**Comment by SonixApache** [comment]
pod bay in incorrect place
:-1:

**Comment by Kharkov72** [comment]
I'm just cleaning it up a bit, not overhauling it

**Comment by Pancakemines** [comment]
As far as I can see this removed the oxygen canister that's currently in north west maint behind the the security checkpoint. This canister is really useful for coming onto a breached station (assuming you have maint access) or for a quick fill before taking a pod to space in a hurry. Maybe keep it and place it in the pod bay to the west of the welding helmet? Seems like a reasonable place for it to be.

**Comment by Kharkov72** [comment]
I will hide my mistake behind it being a feature and you "convincing" me to put them back

They're next to the external airlocks now

**Pull request merged**
