### PR TITLE
Some more fat states for suits

### LINKED ISSUE #20842: Obese+trash bag= free storage
(WEB REPORT BY: spoonylove REMOTE: 172.93.109.202:7777)
# Revision
1d45da69591f630f53c860dab4ed501db80bdd06

# Description
be obese, put on trash bag, game tells you you burst out, still have the bag equipped in body slot, proceed to put things in the bag, on self inspection the bag does not appear on your description. This could lead to people having a stash of items undetectable by sprites or inspection
# Steps to Reproduce
be fat, get trash bag, see how you can now store things in your fat folds.

# What you Expected
to be able to wear trash bags while obese since its just a big bag.

# What Actually Happened
free storage

### LINKED ISSUE #23225: invisible trashbag
(WEB REPORT BY: assburgeri REMOTE: 206.221.180.138:7777)
# Revision
a98fb9c26db97519a8f9643e2c79f0658a355420

# Description
Wearing a trashbag as a obese man will make the trashbag unremovable, invisible, lets you use its storage and if you happen to lose weight you can even wear a space suit on top of that.

# Steps to Reproduce
be fat, wear trashbag.

### LINKED ISSUE #36872: Fat people are unable to wear cassocks
(WEB REPORT BY: wotisjanitor REMOTE: 172.93.101.77:7777)
# Revision
0b6fb6e34800362a6b2ee71dbb014a80f269561b

# Byond Version
514.1589

# Description
unrealistic!
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by RealestEstate**
adds fat states for the following suits:
Clown-EVA
Overalls
Apron
Monkey suit
Chef's apron
Paramedic vest
Hazard vest
Trashbag
Hoodies
Scuba
HoP coat
Advanced EOD
all biosuits
Cap jacket
Cap tunic
HoS suit
Time suit
Dracula coat
Sundowner coat
Cassock (sprite was already in code but was missing flag)

also resolves #20842 and resolves #23225 on testing.
Resolves #36872

:cl:
 * imageadd: Obese crewmembers can now properly wear: biosuits, clown EVA, monkey suits, cassocks, overalls, certain aprons, certain vests, trashbags, hoodies, scuba suits, certain HoP, HoS, and Captain coats, timesuits, vampire coats, and advanced EOD suits
 * bugfix: Becoming fat while wearing the trashbag should no longer give you permanent chest storage.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
kind of wish we just did those displacement maps for the fat gene saving us from using new sprites for everything

**Comment by falcon2346** [comment]
> kind of wish we just did those displacement maps for the fat gene saving us from using new sprites for everything

Supposedly SS14 even has them for vox uniforms, it would be awfully convenient.

**Comment by wotisjanitor** [comment]
THANK YOU! I wanted to play a fat priest with the cassock and now I can

**Comment by Eneocho** [comment]
>Becoming fat while wearing the trashbag should no longer give you permanent chest storage.

it's so over janitorbros...

**Pull request merged**
