### PR TITLE
Removes sending the singulo to centcomm by mail (supply shuttle)

### LINKED ISSUE #8983: Singlo to centcomm via the cargo shuttle
Now, I initially believed this was always a thing you could do, but celt is saying bug report so here goes

> What happened

A traitor shaft miner sent a singularity to centcomm via the cargo shuttle

> What was expected

The singularity to not get to centcomm via the cargo shuttle?

> What happened

2 hours of the singularity rampaging across centcomm because all the admins on at the time were either AFK or didn't quite care

I've messaged said shaft miner to ask how he dunnit, but he is offline at the time of me writing this bug report, assumed he did it through simply a PA aimed at a singularity generator on the MoMMI-nest side of the cargo shuttle

### PR DESCRIPTION
**Pull request by Intigracy**
I learned long ago never to wrestle with a pig. You get dirty and the pig likes it.

closes #8983

### CODE REVIEW

**Comment by gbasood** [comment]
I don't see why anyone would oppose preventing this, honestly.
There is NO upside to allowing this. At all. Why would we EVER want this to occur in a round?

**Comment by Shadowmech88** [comment]
Because it's !!!FUN!!!

**Comment by gbasood** [comment]
It's not though.
No one benefits from it.

**Comment by ghost** [comment]
It's fun as long as it has some degree of control behind it

What happened that round was the admins were completely oblivious to it, either through not being active for the 2 hours it tore through the z level, or just saying 'eh, I don't want to put any effort into this'

**Comment by icantthinkofanameritenow** [comment]
What, someone actually managed to do this once?

**Comment by clusterfack** [comment]
Once? I've personally witnessed it occurring on at least 4 occasions.

**Comment by PJB3005** [comment]
Okay better idea: allow it, but only if there's active admins. And when it does happen bwoink the admins so they can react to it.

**Comment by aceedex** [comment]
Well, why does it even matter if the singulo eats centcom, other than I suppose a lack of emergency shuttle.

It's FUN!!!!

**Comment by gbasood** [comment]
@aceedex It's the same z-level where ERT, deathsquad, syndies, wizards, etc. spawn on.

**Comment by gbasood** [comment]
I can think of one instance where we'd want to allow this.
We have an admin who can bus. The admin sees that someone managed to send a singulo to centcomm. They bus the station for eradicating a Nanotrasen administrative facility (aside from the station)

So maybe @PJB3005's suggestion makes sense

**Pull request closed without merging**
