### PR TITLE
Makes False Walls Properly Block Gasses

### PR DESCRIPTION
**Pull request by mtpowell**
100% untested

:cl:
 * rscadd: False walls block gasses now.

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Don't do this. Use Cross to prevent airflow calculations like doors do.

**Comment by Exxion** [comment]
Better idea: Just don't do this, in general

**Comment by PJB3005** [comment]
Yep they're supposed to allow airflow to pass. They're poorly constructed
fake walls.

Being able to set up a false wall in escape and just go *fwoosh* to kill
everything is a BIIIIT OP.

On 16 Oct 2017 18:24, "Exxion" <notifications@github.com> wrote:

Better idea: Just don't do this, in general

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/vgstation-coders/vgstation13/pull/16259#issuecomment-336940932>,
or mute the thread

**Comment by Exxion** [comment]
You'd have to depressurize escape first to build it, but yeah, I guess you could repressurize it and do that
Mostly though it's just !!FUN!! that they don't block air
Great way to sow chaos that likely nobody without mesons will find

**Comment by PJB3005** [comment]
Place a window in front of the wall you're replacing to keep the air in while you build it. Problem solved.

**Comment by Exxion** [comment]
Beyond a certain maximum pressure differential between tiles, you can't build a falsewall
And falsewalls use their own pressure differential shitcode
And it doesn't look like it checks adjacency
So I don't think a window would help

**Comment by PJB3005** [comment]
3 windows for a localized pocket of vacuum on both sides.

**Comment by Exxion** [comment]
Alright, I think that one would work

**Comment by mtpowell** [comment]
I don't really want to do this anymore

**Pull request closed without merging**
