### PR TITLE
Adds missing items to botanist belt acceptance

### LINKED ISSUE #31871: Botony belts don'
(WEB REPORT BY: thathazmatyoukilledinsof REMOTE: 206.221.180.138:7777)
# Revision
b1a9cb3faca436a418a94d0f78851e8e9e3505e0

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #31879: Botany gear belt doesn't hold all my botany gear
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
c37974d3513af6cb1104ae047b93ada8fba7b076

# Description
Blasted thing doesn't accept plant-b-gone, spade, plant clippers.
# Steps to Reproduce
Pick botanist (don't, that's my role), try to put gear in special belt, realize that plastic bag remains undefeated.
# What you Expected
belt that's better than plastic bag
# What Actually Happened
belt that's worse than plastic bag

### LINKED ISSUE #31888: botany belt can't hold plant clippers OR spade
(WEB REPORT BY: jesture REMOTE: 206.221.180.138:7777)
why

### LINKED ISSUE #31895: plant clippers dont fit in botany belt
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
38e707268f1be176729740d149dab5582d517128

### LINKED ISSUE #31899: The botany belt can hold barely any equipment
(WEB REPORT BY: jognvi REMOTE: 206.221.180.138:7777)
# Revision
eb32f32495bed37027f5d56da1cbe58351fbb8c7

# Description
The belt can't even hold spades like the description says. It's really not useful.

# Steps to Reproduce
Put on a belt, try to put botany equipment in
# What you Expected
Something more akin to other job belts for holding equipment
# What Actually Happened
It can hold basically nothing

### PR DESCRIPTION
**Pull request by ghost**
[bugfix]
Closes #31871.
Closes #31879.
Closes #31888.
Closes #31895.
Closes #31899.

:cl:
 * bugfix: Botanist belts can now fit plant clippers, spades and spray bottles.

### CODE REVIEW

**Comment by Armadingus** [comment]
Putting a large scythe in your belt may be very overkill.

**Comment by Dacendeth** [comment]
I kind of agree about the scythe, but at the same time mining belts can fit like seven pickaxes if they wanted.

**Comment by Eneocho** [comment]
Closes #31879

**Comment by Eneocho** [comment]
Closes both  #31895 and #31899

**Pull request merged**
