### PR TITLE
Grue drain light tweaks

### PR DESCRIPTION
**Pull request by Hinaichigo**
This increases grue nutrienergy use rate for drain light from 1 per second to 2 per second, and also removes the hard cap on drain light intensity introduced in #34989 (but not range which it keeps limited as-is).

With this change, eating one creature provides enough nutritive energy to drain light for 50 seconds rather than 100 seconds.

I think this could be nice in that it makes the use of the drain light ability more tactical and the grue has to be more discerning about when and when not to use it rather than using it more flippantly, while also restoring the intensity scaling by removing the hard cap so it can counteract large amounts of massed lights and there's more that can happen in that regard.
:cl:
 * tweak: Grue drain light drains nutritive energy twice as fast.
 * tweak: Grue drain light intensity is no longer hard-capped after eating 3 sentients (range is still capped).

### CODE REVIEW

**Comment by DorainGrey** [comment]
Here's the thing, this makes no meaningful impact.

For feeding a Grue gets a total of 100 nutri-energy after digestion, so this means they can run around with drainlight on for 500 seconds before running out.

This is the only one of the Grue's abilities that costs nutri-energy.
Evolving is the only other activity that costs.
.Laying Eggs doesn't even cost anything.  So it's not like they are forced to make any decisions here, it's the only thing they can spend it on....
There's no tactics at all, literally no incentive to not run around with Drain light on constantly, which experience shows is exactly what happens.

In exchange, they get the busted negative light levels back which means a Grue with 5 bodies can tank 15 torches on a single tile..... Meanwhile the crew can do literally nothing, even Mesons only show a single tile around you.
Literally the Grue's only weakness is light and you are trying to buff it, so they don't even need to worry about that.

This PR might make sense, if Grue's were charged for using teleport or wall breaking powers but until then it's just an extremely stealth buff to Grue.

**Comment by Hinaichigo** [comment]
What drain rate would you think would be reasonable?

**Comment by Hinaichigo** [comment]
> 500 seconds

You mean 50 seconds right? That var corresponds to ticks which are 0.1 seconds.

**Comment by DorainGrey** [comment]
> > 500 seconds
> 
> You mean 50 seconds right? That var corresponds to ticks which are 0.1 seconds.

I tested this locally and this seems to be the case.

If you are going to allow unlimited ligth drain then perhaps 0.4 is more reasonable.
This allows for 25 seconds per a kill and is still  very generous but I feel with the Grue damage nerfs it's good.

**Comment by Hinaichigo** [comment]
Okay I'll wait a bit to see if anyone else gives some feedback and then maybe increase it a bit more to around there.

**Pull request closed without merging**
