### PR TITLE
Revert "Aaaaaaah"

### PR DESCRIPTION
**Pull request by Intigracy**
Reverts vgstation-coders/vgstation13#14486

### CODE REVIEW

**Comment by ghost** [comment]
NO

**Comment by SonixApache** [comment]
YES

**Comment by yclatious** [comment]
FUCK SCREAMING

**Comment by SonixApache** [comment]
how does a revert

what

**Comment by ghost** [comment]
because it has to be reverted on the secret repo too

**Comment by PJB3005** [comment]
Because the real April's fools prank here was that we made it only play the scream to yourself, on the secret repo.

**Pull request merged**
