### PR TITLE
Horizon Hotfixes

### LINKED ISSUE #25315: horizon: paramedics office cryo has no pipes to support it
what it says on the tin, the paramedics office cryo has no actual pipes to connect the freezer to the tube, or a tube to connect an oxygen canister to the cryo tube for that matter

### LINKED ISSUE #25348: Cargo bay shutters Horizon
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
e3d28a057f655d340c60f2e2da3f7bdc95e5f8d7

# Description
Buttons aren't set to shutters right one doesn't open any other opens all of same thing on the shuttle it's wired to the cargo bay shutters and not just the shuttle shutters
# Steps to Reproduce
press the buttons
# What you Expected
seperate shutting
# What Actually Happened
it all shut

### LINKED ISSUE #25351: Horizon Trader Shuttle Door
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
9eee1c8336291eb905cc57d3701961bf54e29238

# Description
There is a space tile underneath the door to the trader shuttle.
# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #25368: horizon: extra firelock under atmospherics airlock
image

### LINKED ISSUE #25369: horizon: robotics camera faces wrong direction
why are there 2 cameras in there anyway?

image

### PR DESCRIPTION
**Pull request by plosky1**
Fixes disposals, closes #25351, closes #25348, closes #25315 , closes #25368 , closes #25369  and some other minor problems.

[hotfix]

### CODE REVIEW

**Comment by Kurfursten** [comment]
Why is this a 10k diff for some pipes and shutters?

**Comment by plosky1** [comment]
Because I rebased and it changed everything for some reason. It works fine though.

**Comment by SonixApache** [comment]
hey if you got any more changes you'd like to make, the interrogation rooms in sec shouldn't be see-through and i did a walk through after a bombing and couldn't find any fire alarms so maybe check that as well

**Comment by plosky1** [comment]
> hey if you got any more changes you'd like to make, the interrogation rooms in sec shouldn't be see-through and i did a walk through after a bombing and couldn't find any fire alarms so maybe check that as well

will do, thanks!

**Comment by plosky1** [comment]
Ready for merge

**Comment by Zth--** [comment]
#25368
#25369

**Comment by Zth--** [comment]
Also could you remove the rigsuit helmet as per #25365? Thank you

**Comment by DamianX** [comment]
See https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords to properly auto-close issues

**Comment by plosky1** [comment]
Proper closes should be ready on main post, and rigsuit helmet removed along with the other two issues solved.

Ready for merge unless more issues come up.

**Pull request merged**
