### PR TITLE
Reverted rust-g

### PR DESCRIPTION
**Pull request by DamianX**
Admins can't login and shifty is asleep, temporarily reverting.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
the round didn't even restart for the fix to kick in, at least wait until next round

**Comment by ghost** [comment]
the fix won't fix this issue because it only changes the query for bans

**Comment by boy2mantwicethefam** [comment]
isn't that the point?
as for admin rights I think it'd be worth checking out where adminship is handled

**Comment by ghost** [comment]
thank you for the advice master detective barry

**Comment by boy2mantwicethefam** [comment]
surely actual experienced coders know how to fix this

**Comment by ShiftyRail** [comment]
The fix to this was revealed to me in dream.

**Pull request merged**
