### PR TITLE
Changes the Atmospheric Technician's messenger bag

### PR DESCRIPTION
**Pull request by ghost**
Fixes the Atmos Tech's messenger bag being of the ugly industrial type rather than the basic type, like the rest of their bags.

### CODE REVIEW

**Comment by SonixApache** [comment]
pics?

**Comment by DrSnips** [comment]
Shouldn't it be the other way around where the basic bags are replaced with engi bags?

**Comment by ghost** [comment]
@SonixApache 
It's just the normal, default messenger bags that jobs like assistant spawn with, nothing new.

@DrSnips 
Atmos Techs have always had the 'standard' bag types.  Don't ask me why, it's probably because they're not horrendously ugly like industrial bags are.  I guess when messengers were ported from Bay, they just put the engi one on Atmos Techs because they're in engineering.dm.

**Comment by DrSnips** [comment]
Would you like me to throw together a set of atmos tech bag sprites?

**Comment by ghost** [comment]
I prefer the standard grey look, personally.  Going with the bright yellow and blue look would probably be garish, and if it matched the hardsuit it'd be a bit ugly.

I'll be sure to pester you soon, though, I have !!PLANS!! for bags.

**Comment by DrSnips** [comment]
>the colors shouldnt match at all

And define plans. Because plans are usually things that dont ever get done.

**Comment by ghost** [comment]
Very basic things for another PR.

The default grey look is still the best IMO, it looks way better with Atmos equipment than the industrial bags do and anything with the Atmos colours would.  This is just bringing the messenger bag in line with how the bags have (maybe?) been since departmental bags were added.

Feel free to sprite some Atmos bags for a later PR, though, it might be nice to see how they look.

**Comment by DrSnips** [comment]
Likely going with the industrial look with some blue stripes for the bags. Like them or not the colors line up better. The other bags were likely just never changed over with them. Make this change now but I will likely be touching them in the future if you don't continue with your plans.

**Comment by ghost** [comment]
Sounds good.

**Comment by jknpj** [comment]
I'd scream "DON'T TOUCH JOB CODE" because i'm porting outfit datums but fuck it, go ahead. I don't have the time to work on it now anyways,

**Pull request merged**
