### PR TITLE
Adds QoL Ban panel functionality

### PR DESCRIPTION
**Pull request by Goldsteel**
[WiP][administration][discussion][qol][featurerequest]

The aim of this PR is to make it easier to ban people. I'm not able to addess the database, so we will likely need to test merge this PR to the test server for some testing.

Anyway, the goals:

1. To provide a means for admins to put in DD/HH/MM instead of just minutes like 1440 for a day to save them spending time calculating exactly what they want to put in.
2. To give more means of feedback to the admin and player, such as when they got banned, how long the ban is approximately in days/hours/minutes.
3. To make it easier to edit bans through the respective ban panels.

I'm currently having some issues getting the formatting right but currently it does assign the bans in minutes and performs the arithmetic just fine, but recalling those values and editting them seems to be playing up with me and I don't know why yet. Feedback appreciated.

:cl:
 * tweak: Admins banning in game can now select days/hours/minutes for the ban length.
 * bugfix: The ban panel in game is now slightly more informative than before.

### CODE REVIEW

**Comment by Goldsteel** [comment]
image

**Comment by Goldsteel** [comment]
It seems like the legacy system is having problems reading and editting bans. I'm not sure if I caused this or not.

EDIT: Legacy panel is indeed not working on bleeding edge. You can view old bans, but you can't actually edit them even though I've made it so you can.

**Comment by N3X15** [comment]
Should just add a regex to extract `(\d+)y`, `(\d+)mo`, `(\d+)d`, `(\d+)h`, `(\d+)min` or something so you don't have to crawl through 50 dialogs.

That way the admin could specify a 5.5-day ban as `5d12h`

**Comment by SonixApache** [comment]
5 million inputs are nice and all but a proper UI would be even better

**Comment by Goldsteel** [comment]
I'm still trying to figure out how to make UI

**Comment by Kurfursten** [comment]
What's the status on this? Something you need help with?

**Comment by Kurfursten** [comment]
Let any collab know to reopen this if you pick it up again

**Pull request closed without merging**
