### PR TITLE
Removed datum pooling

### LINKED ISSUE #19779: resetVariables() is broken
#### Description of issue
`/datum/proc/resetVariables()` expects its args to be strings containing names of vars to NOT reset.
https://github.com/vgstation-coders/vgstation13/blob/63f63add5f463df6e34fb721583e4ef53363a666/code/__HELPERS/datumpool.dm#L108-L126

Instead, most implementations pass parameters like this:
```
/mob/living/simple_animal/resetVariables()
	..("emote_hear", "emote_see", args)
/mob/living/simple_animal/bee/resetVariables()
	..("bees", "visited_plants", args)
```

which results in resetVariable's args being (JSON representation):
`["emote_hear","emote_see",["bees","visited_plants",[]]]`

instead of the expected:
`["bees","visited_plants","emote_hear","emote_see"]`

#### Length of time in which bug has been known to occur
The beginning of time?

#### Server revision
63f63add5f463df6e34fb721583e4ef53363a666

### PR DESCRIPTION
**Pull request by DamianX**
Things seem to be working fine.

### What
Pooling is a thing that makes it so instead of deleting datums you store them somewhere, reset its variables and reuse it later, allegedly for performance.
This PR makes everything that used to be pooled just delete instead.

### Why
The performance gains of using pooling are uncertain but the bugs caused by references that are not properly cleared are innumerable and by removing pooling they turn into hard-deletions immediately, which we can track and fix, instead of subtle bugs that only appear after 500 iterations of pooling.

Fixes #19779

### CODE REVIEW

**Comment by Exxion** [comment]
Fixes #19779

**Comment by ShiftyRail** [comment]
Without datum pooling, runechat messages would conistently show up at the top of profiler, in the sense that the GC subsystem would take a lot of CPU and even some overtime. Slowly making

There's many of them and they seem to hog an internal reference or something, because they wouldn't get instantly cleared. They wouldn't get hard-deleted either (because I don't believe the server could withstand thousands of hard-deletions in a single shift), but the cost of them being handled by the GC wasn't zero, at all.

**Comment by DamianX** [comment]
That wouldn't have anything to do with the fact that you were hard-deleting the images?

**Comment by ShiftyRail** [comment]
Let me pull that one and try.

**Comment by Exxion** [comment]
The GC would only show up at the top if they had leftover refs, not if you manually hard deleted them
The refs *could* be internal, but probably aren't and you just have to find them

**Comment by ShiftyRail** [comment]
It doesn't cause problems (on local)

**Review by ShiftyRail — APPROVED** [review]

**Pull request merged**
