### PR TITLE
Adds Clown Funerals

### PR DESCRIPTION
**Pull request by gurfan**
:cl:
 * rscadd: Causes clowns to play a trombone sound when they actually die

### CODE REVIEW

**Comment by Kurfursten** [comment]
Immersion breaking and prevents clowns from faking their death because it won't play a sound

Would be fine for April Fools

EDIT: He made it for April Fools so it's fine with me

**Comment by gurfan** [comment]
ok sure

**Comment by jwhitak** [comment]
Play the sound when they fake their deaths.

**Comment by Eneocho** [comment]
Play the sound when they fake death so it's a global clown thing instead of just 1 day a year.

**Comment by Theophrastus1** [comment]
Make a batch of them, sad trombone, TAPS, medieval fanfare, whatever really clown it up

**Comment by Eneocho** [comment]
> Make a batch of them, sad trombone, TAPS, medieval fanfare, whatever really clown it up

This but different sound effects depending on how they died. If they died from o2 it trombones, if they died from burns it HONKs, etc.

**Comment by pedr69** [comment]
>play the sound when fake death

i see potential for sound spam and do not like
you could also make it an implant which plays the sound on death
imagine the clown replacing all of the HOS' loyalty implant cases with trombones

**Comment by Eneocho** [comment]
>i see potential for sound spam and do not like

Bro literally just add a delay similar to farting delay (30s?) so you can fake death with the appropriate sound effect yet more deathgasps are silent until the timer has completed.

**Comment by KingofHONK** [comment]
>faking deaths
Pussies.

**Comment by KingofHONK** [comment]
Clowns and mimes need to accept their tragic end. It's part of the act. Don't lock it to April fools, this is the most immersive PR released ever.

**Comment by Blithering** [comment]
Could this be what happens when a clown dies with banana juice in their system? (Like the custom deathgasp for having hardcores)

**Comment by Eneocho** [comment]
> Could this be what happens when a clown dies with banana juice in their system? (Like the custom deathgasp for having hardcores)

Or if someone dies with honk serum in their system.
Imagine: Revs, they capture the HoS, feed him some Clown Chips as his last meal and kill him, only for a sad trombone to play.

**Comment by gurfan** [comment]
>immersion breaking

Immersions are important but out of all the dumb meme shit that gets added I really think this is the least egregious.
We already have reagents that play bikehorn sounds, ear-rape clown shoes, dabbing yourself to death, and a segment from the hit 60's song The Sound Of Silence by Simon and Garfunkel that plays when you shoot yourself. I think this is humorous and fitting enough (it's for clowns after all) to be added year round instead of just April fool's.

I might look at making it play on deathgasps but with a delay to make it not spammable.

**Comment by Kurfursten** [comment]
At the very least tie it to CLUMSY or wearing clown shoes instead of making it attached to something entirely OOC -- whether you signed up as clown before joining.

**Comment by Eneocho** [comment]
I'd tie it to both CLUMSY or having honk serum on your system.

**Comment by gurfan** [comment]
I'll tie it to CLUMSY

**Comment by Eneocho** [comment]
> I'll tie it to CLUMSY

Tie it to honk serum and banana incense as well, since those 2 chems make you clumsy while metabolizing (but don't give you the clumsy gene).

**Comment by pedr69** [comment]
but how does a clown pretending to die manage to play the trombone
it just doesn't make sense

**Comment by Eneocho** [comment]
they fart out a trombone sound of course
clowns have anatomically different bowels, ever noticed that the clownfarts sound not like a generic fart sfx but rather a honk or trumpet? same deal here

**Pull request merged**
