### PR TITLE
Shuttle resprite

### PR DESCRIPTION
**Pull request by optimumtact**
Only affects box because I ran out of ability to care.

### CODE REVIEW

**Comment by Riekland** [comment]
stop doing this
having the sprites do the merge thing is gay because now it looks like there should be another piece of wall instead of fucking nothing next to it
the floors are hideous, fucking blurry, too soft, colours are all fucking wrong and have no relation to the colours currently in game
how do i outline?????
PJB needs to be put down

**Comment by optimumtact** [comment]
Better to be a gay coder with bad sprites than a degenerate with an anime avatar frankly

**Comment by PJB3005** [comment]
> having the sprites do the merge thing is gay because now it looks like there should be another piece of wall instead of fucking nothing next to it

That's already a thing not my fault.

**Comment by Riekland** [comment]
Then fix it before you fucking do anything else retard, what's the point in fucking making shit that's gonna be broken as soon as it's in the fucking game

**Comment by PJB3005** [comment]
@Riekland I would need to resprite all the objects on that shuttle (then do it for on station too for consistency), recode smoothwalling frameworks and move us to single tile windows if you're gonna be so demanding.

Of course we all know how that'd turn out.

**Comment by Riekland** [comment]
so don't fucking update the sprites?

**Comment by Shadowmech88** [comment]
>having the sprites do the merge thing is gay because now it looks like there should be another piece of wall instead of fucking nothing next to it

Are you referring to the open-ended look of the walls that surround doors and windows?

**Comment by PJB3005** [comment]
> so don't fucking update the sprites?

Did you miss the part where this happens even with the white shuttles?

**Comment by Riekland** [comment]
>Are you referring to the open-ended look of the walls that surround doors and windows?

yes

>Did you miss the part where this happens even with the white shuttles?

yes
fuck
DISREGARD THAT I SUCK COCKS

**Comment by Shadowmech88** [comment]
From what I could tell, having viewed the shuttle in the map editor, shuttle walls don't actually use smoothing code. They're manually varedited to the correct state.
I believe it would be completely possible via mapping for the walls adjacent to structures like doors and windows to be made into end caps rather than connective pieces.

Even with the current white walls, that specific issue should be fixable.

**Comment by PJB3005** [comment]
@Shadowmech88 yes but it'd look even worse.

**Comment by ultraplen** [comment]
Horrid palette swap.

**Comment by JustSumBody** [comment]
We're going to need a "shuttle" label now

**Comment by salamandooo** [comment]
I don't think it looks very good. It's a civilian shuttle, the darkness makes it seem like we're either rundown or evil or something like that.

**Comment by cadaverouscoyote** [comment]
didn't get any better since yesterday

**Comment by Exxion** [comment]
After understanding what PJB meant the lighter parts to be, I rescind my statement that this looks good at all

**Comment by TheFriggenSawbones** [comment]
ban oranges for shitposting

**Comment by optimumtact** [comment]
Please don’t' derail my PR thanks

**Comment by Intigracy** [comment]
we already have shuttle windows, they can't be broken though iirc

**Comment by Zennyization** [comment]
I dont like the colour scheme for the shuttle.

**Pull request closed without merging**
