### PR TITLE
Time agent 2: The hunt for more features

### PR DESCRIPTION
**Pull request by MadmanMartian**
Continues adding the time agent, a timed antag.

You get

 - A time suit that lets you turn back time, go forward in time, and stop time
 - A chronocapture device (for objective stuff)
 - A rewind rifle (Rewinds itself back 10 seconds after it was first fired.)
 - A Jump charge. Used to send an object forward in time 10 seconds, or interact with time anomalies.

todo:
 - [x] Objectives
 - [x] Time travel TLC (Never thought I'd get to type that)
 - [x] Ruleset
 - - [ ] Add a timed ruleset that calls back after N minutes to remove the antag.

:cl:
 * rscadd: Adds the Time Agency.

### CODE REVIEW

**Comment by Probe1** [comment]
I approve of this PR title.

**Comment by Tokanova** [comment]
i look forward to this bugging out in exciting and new ways.

**Comment by Kitfox88** [comment]
so when the rifle rewinds does it pull back its ammo or does it jump to the position it was at 10 seconds ago

**Comment by MadmanMartian** [comment]
@Kitfox88 It gets rewound, but still remains in the hand of the agent

**Comment by bathosbathtime** [comment]
This is a really good idea that I think will be very interesting.  And if it bugs out, we can just call it time distortion.  Emergent gameplay!

**Comment by Blithering** [comment]
cropped-chronolegionnaire1
Never existed.

**Pull request closed without merging**
