### PR TITLE
Apply a little post-processing filter to neo-lights

### PR DESCRIPTION
**Pull request by ShiftyRail**
image

image

This is very minor, like all post-processing effects, but it does add a little bit of flair and makes some of the most angular shadows a bit softer.

After the debacle of the initial post-processing filter, I'd like this to be merged to test and have a few players try it.

:cl:
- tweak: An attempt at making the shadows generated from walls less sharp.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
you call it minor, I call it a world of difference

**Comment by DamianX** [comment]
I call it a "maybe test this one on the test server first". Need to come up with a catchier name

**Comment by ShiftyRail** [comment]
People have tested it and it looked right so far.

**Comment by Kurfursten** [comment]
Confl

**Comment by ShiftyRail** [comment]
This is conflicts fixed, field-tested. It looks pretty on my machine.

When field testing on Box it works nearly everywhere except one (uno) holomap not layering properly. Moving it around fixes it. Spawning a new source of light post map-gen fixes it too.

**Comment by DamianX** [comment]
we do a little post-processing

**Comment by ShiftyRail** [comment]
This is what causes people to lag and crash :(

**Pull request merged**
