### PR TITLE
Adds Space Chocolate, a substitute for real chocolate

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
4 units can be made with 1 unit of vomit and 1 unit of corn syrup.
Less nutriment than corn syrup but has only a 35% chance to add 0.1 toxin to the character compared to vomit.
If the character is obese it's perfectly safe to consume.

:cl:
 * rscadd: Added Space Chocolate, a not-quite-like-chocolate chocolate substitute that can be made by combining vomit and corn syrup. It is far less toxic than vomit.

### CODE REVIEW

**Comment by adacovsk** [comment]
why

**Comment by tinysaturn** [comment]
american PR

**Comment by Pastamadness** [comment]
Needs milk

**Comment by ghost** [comment]
what

**Comment by boy2mantwicethefam** [comment]
From a theoretical standpoint it's a means of using abundant amounts of vomit to make up for the lack of confectioneries. Now that I mention it I should raise the amount of units produced to 4 to lean on the "worse but overall more abundant" aspect of it, but raise the chance of poisoning per tick to 35%.
From a reasoning standpoint american chocolate sucks.
@Pastamadness I'd add milk but then no one would ever want to put in the effort of making it.

**Comment by adacovsk** [comment]
is this a political statement? also tell someone to merge #33751 so the tests stop failling

**Comment by Pastamadness** [comment]
@boy2mantwicethefam clearly we should replace milk with a milk substitute like filk (D. Dan's sauce)

**Comment by Exxion** [comment]
>also tell someone to merge https://github.com/vgstation-coders/vgstation13/pull/33751 so the tests stop failling

Done but tests will continue to fail at random on PRs opened before that was merged

**Comment by Eneocho** [comment]
>space chocolate is a reagent, not a dish

low effort
just make it "space chocolate mix" and have it cook into space(TM) chocolate, we could even add it to the wiki as the second pre-mixed recipe next to pancakes

**Comment by Kurfursten** [comment]
> From a theoretical standpoint it's a means of using abundant amounts of vomit

Vomit can already be used for recycled nutrition cubes, no one does this afaik

**Comment by SECBATON-GRIFFON** [comment]
the joke is that hersheys in burgerland has a "distinct vomit taste" left in due to popular demand, you're welcome

**Comment by Hinaichigo** [comment]
The recipe doesn't quite make sense.

**Comment by Exxion** [comment]
Leaving in bad things due to people hating change? Where have I heard that before?

**Comment by boy2mantwicethefam** [comment]
@Hinaichigo Patented Space American chemical.

**Comment by Eneocho** [comment]
> @Hinaichigo Patented Space American chemical.

Make it so you use this to make space chocolate for a cheaper and easier alternative to chocolate bars, with the caveat of these discount chocolate bars having a chance of being toxic. You could then make chocolate-based recipes and get some toxin inside the choco coin or whatever.

**Comment by Kurfursten** [comment]
Lack of support

**Pull request closed without merging**
