### PR TITLE
Makes Frankenline votable only during October.

### PR DESCRIPTION
**Pull request by west3436**
Frankenline Station was a meme map built around a meme premise and added to the voting list as a regular map. This PR (now 100% tested) makes the map only able to be voted on during the month of October, since it is a spooky Frankenstein abomination.

:cl:
- Removes the ability to vote on Frankenline Station outside of the month of October.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
[REPOST FROM LAST PR]
I agree, I've noticed that the map kills pop whenever it rolls. It's a novel idea, but it is an absolute meme. Fits as a bus map, though.

**Comment by TGFH** [comment]
This PR was created by the Sn*xi metaclub. They're trying to keep us down, Linelads. Fight back!

**Comment by djkramer123** [comment]
Meme maps shouldn't be in regular rotation, good pr.

**Comment by pedr69** [comment]
line is good, but if a lot of people disagree(they are wrong), perhaps make it roll if some stupid round condition happens, instead of straight up removal
for example have it roll if more than 3 people got gibbed by a railgun or somethin

**Comment by west3436** [comment]
> line is good and should be kept in, but if a lot of people disagree(they are wrong), perhaps make it roll if some stupid round condition happens, instead of straight up removal for example have it roll if more than 3 people got gibbed by a railgun or somethin

my man did you even read the PR? this makes it available during October and doesn't remove it altogether

**Comment by adacovsk** [comment]
> some stupid round condition happens, instead of straight up removal for example have it roll if more than 3 people got gibbed by a railgun or somethin

Maybe a mass driver killing someone... I'll take more ideas and try to implement if that's what the people want

**Comment by pedr69** [comment]
i have read the PR and making it october only feels too rare, i don't want to wait 9 months to play line
have it roll on fullmoons or other dumb round conditions, like massdriver or immovable rod kills or some dumb shit idk
but i trust linechads will not be beaten, the vote will not pass

**Comment by Eneocho** [comment]
You torture us with Snaxi, you get tortured with Line, simple as.

**Comment by west3436** [comment]
> You torture us with Snaxi, you get tortured with Line, simple as.

Snaxi is only votable for a portion of the year, which is in-line with the intent of this PR.

**Comment by adacovsk** [comment]
> > You torture us with Snaxi, you get tortured with Line, simple as.
> 
> Snaxi is only votable for a portion of the year, which is in-line with the intent of this PR.

well to be fair it's like 4 months vs the 1 month you're proposing with this PR

**Comment by west3436** [comment]
> > > You torture us with Snaxi, you get tortured with Line, simple as.
> > 
> > 
> > Snaxi is only votable for a portion of the year, which is in-line with the intent of this PR.
> 
> well to be fair it's like 4 months vs the 1 month you're proposing with this PR

You are welcome to provide a better alternative here. This map should never have gone into full rotation in the first place.

**Comment by Eneocho** [comment]
Limiting maps to a specific time only makes it so that map gets constantly voted during the allowed time. It's the reason snaxi gets so many fucking votes despite being a horrible meme map, because it's only available during cold season. 
Also, Snaxi is allowed for 4 months of the year, so you should by that logic also increase frankenline to 4 months.

**Comment by west3436** [comment]
> Limiting maps to a specific time only makes it so that map gets constantly voted during the allowed time. It's the reason snaxi gets so many fucking votes despite being a horrible meme map, because it's only available during cold season. Also, Snaxi is allowed for 4 months of the year, so you should by that logic also increase frankenline to 4 months.

This is a separate issue. If you feel so strongly about this, make a PR to remove Snaxi from a season-based rotation.

**Comment by Eneocho** [comment]
I'm just saying limiting frankenline to a certain timeframe will make frankenline a LOT more played during that timeframe, which goes against your point of limiting it.
The issue ain't even that it is a meme map, it's dynamic voting. People tend to leave when the map they voted doesn't get chosen despite having almost all the votes. It happens when roid gets voted, when snaxi gets voted, when deff, waystation, hell, even box.

**Comment by Eneocho** [comment]
Also, if you do end up limiting frankenline, consider making it a May, June, July and August map (so it's in the middle of the year, opposite to snaxi).
I'm still opposed to making Line a seasonal map, but at least make it a decent change if you do.

**Comment by SonixApache** [comment]
if a rod rolls a perfect horizontal angle on its throw, add 10 votes to line

**Comment by Eneocho** [comment]
> if a rod rolls a perfect horizontal angle on its throw, add 10 votes to line

I will metagame the roulette revolvers and fire until line has 100 votes.

**Comment by adacovsk** [comment]
In any case, if this doesn't get merged, I'll make a PR to raise the pop to 25 from 20.

**Comment by ShiftyRail** [comment]
This is conflicting anyways.

**Comment by west3436** [comment]
> This is conflicting anyways.

as of 9 minutes ago you bully
i will update

**Comment by west3436** [comment]
>no longer compiling
@ShiftyRail any input as to what could have caused this? i am very far from a GitHub pro

**Comment by adacovsk** [comment]
> > no longer compiling
> > @ShiftyRail any input as to what could have caused this? i am very far from a GitHub pro

change the min pop to 25

**Comment by ShiftyRail** [comment]
@west3436 not your fault, nerve has a bug.

**Comment by tomacatx2** [comment]
whats line?

**Comment by west3436** [comment]
the in-game poll is decisively in support of this PR:
http://ss13.moe/index.php/poll/230

**Comment by Eneocho** [comment]
Since this will probably get merged, at least wait a week after merging #31785. Give a chance for the update/changes Adacovsk made to be judged by the playerbase. With its own poll to merge this or not afterwards if possible.

**Comment by djkramer123** [comment]
lol

**Comment by west3436** [comment]
> Since this will probably get merged, at least wait a week after merging #31785. Give a chance for the update/changes Adacovsk made to be judged by the playerbase. With its own poll to merge this or not afterwards if possible.

"No!"

**Comment by AdrianoKing** [comment]
frankenline has the best maintenance of all maps so far!
only medbays and other jobs without maint access hate the map because of the huge line.
I reject the merge and so do true assistants!

**Comment by bathosbathtime** [comment]
The poll ended with:
31 voting yes (53% total, 54% without abstain votes)
26 voting no (45% total, 46% without abstain votes)
1 voting abstain (2% total) (percentages rounded)

The poll, as linked above: http://ss13.moe/index.php/poll/230

**Comment by west3436** [comment]
> The poll ended with: 31 voting yes (53% total, 54% without abstain votes) 26 voting no (45% total, 46% without abstain votes) 1 voting abstain (2% total) (percentages rounded)
> 
> The poll, as linked above: http://ss13.moe/index.php/poll/230

Right, this is a majority. What is the threshold for a "won" vote in your book?

**Comment by bathosbathtime** [comment]
Simply stating the facts, what that threshold is is up to the collab. I have in the past, however, called for a threshold higher than that on other PRs so I suppose it would be hypocritical for me to support in any way this PR getting merged. I would have to review what decisions were made in the past to give you a firm answer but ultimately it is not up to me nor do I have any more say in this matter than any other user of this codebase.

**Pull request merged**
