### PR TITLE
silicon unit link established notification

### PR DESCRIPTION
**Pull request by SonixApache**
AImsg

🆑 
 - rscadd: Silicons now get a notification when they gain an AI link. This goes both ways.

### CODE REVIEW

**Comment by west3436** [comment]
Isn't this just a giant red flag that one of your borgs has been emagged, or do they remain linked even after they're hacked?

**Comment by SonixApache** [comment]
AIs don't get a warning from emaggings.

**Comment by tuypo1** [comment]
Established seems fine but lost is way too big a nerf to non emag antags

**Comment by SonixApache** [comment]
i think the amount of times antags have cut the AI link manually in the past year is less than ten, i wouldn't worry about it too much

**Comment by SonixApache** [comment]
If I change this to remove the link loss notification, would that please the nayvoters?
I just want to know when I get a new borg, man.

**Comment by tuypo1** [comment]
Yes, I only downvoted because of the link lost, the link gained is a great idea

**Comment by SonixApache** [comment]
adjusted to only show link gained - link lost info code is still there, but is unused

**Pull request merged**
