### PR TITLE
Adds basilisk hide and hivelord cores as mining rig upgrades

### PR DESCRIPTION
**Pull request by adacovsk**
## What this does
- Basilisks drop diamond ore upon death instead of removing hide
- Removing hide drops an actual hide from basilisks
- basilisk hides and hivelord cores upgrade armor
- Basilisk upgrades armor for lasers
- Hivelord cores upgrade armor for bio and rads
- You can only choose one path for your helmet and body independently

a mining hardsuit has base resists of 40% melee, 20% laser and 10% rad, but can be improved with:
goliath - melee resist, 10% per hide, up to 90%
basilisk - laser resist, 5% per hide, up to 30%
hivelord - rad resist, 10% per hide, up to 50%(the hardsuits are bio resistant to begin with)

## Why it's good
image

Sprites will probably need some tweaking

## Changelog

:cl:
 * rscadd: Adds basilisk hide and hivelord cores as mining rig upgrades

### CODE REVIEW

**Comment by tomacatx2** [comment]
good PR pls merge do the needful

hello and love from pakistan

**Comment by jwhitak** [comment]
Dilt thoughts: This PR allows you to upgrade the mining rigsuits with hides besides the goliath. But you can only pick ONE route! Example, if you want the melee resistance, you give up the upgraded energy/rad options. The helmet and suit are separate, so you can upgrade each differently if you so choose.

Goliath is the same, upgrading melee resist only, +10% per hide, to the max of 90%.
The Bassy will upgrade the energy/laser resistance by +10% each upgrade, to a maximum of 90%.
The hivecores will upgrade the bio/rad resistance by +10%, up to 100%. Most mining suits are already 100% resistant to bio.

Your generic ass miner armor has ```armor = list(melee = 40, bullet = 5, laser = 20,energy = 5, bomb = 35, bio = 100, rad = 10)```, though variants will have different stats. Each piece (helmet, suit) requires a hide. So, basically, to fully upgrade energy resist, you'll need about 18 bassy skins for the helmet and exosuit. This is feasible if the miners start stripping the advanced laz injectors from mining vendors. Prepare to have blue miners come out from farming and be nearly immune to lasers.

Most suits already have 100% bio resist, so the hivecores are mainly for the rad resist. If they get 18 hive cores, they can happily drag around very deadly radiation sources. If they want to. Really situational. The green suit looks the coolest though!

**Comment by tomacatx2** [comment]
> Dilt thoughts: This PR allows you to upgrade the mining rigsuits with hides besides the goliath. But you can only pick ONE route! Example, if you want the melee resistance, you give up the upgraded energy/rad options. The helmet and suit are separate, so you can upgrade each differently if you so choose.
> 
> Goliath is the same, upgrading melee resist only, +10% per hide, to the max of 90%. The Bassy will upgrade the energy/laser resistance by +10% each upgrade, to a maximum of 90%. The hivecores will upgrade the bio/rad resistance by +10%, up to 100%. Most mining suits are already 100% resistant to bio.
> 
> Your generic ass miner armor has `armor = list(melee = 40, bullet = 5, laser = 20,energy = 5, bomb = 35, bio = 100, rad = 10)`, though variants will have different stats. Each piece (helmet, suit) requires a hide. So, basically, to fully upgrade energy resist, you'll need about 18 bassy skins for the helmet and exosuit. This is feasible if the miners start stripping the advanced laz injectors from mining vendors. Prepare to have blue miners come out from farming and be nearly immune to lasers.
> 
> Most suits already have 100% bio resist, so the hivecores are mainly for the rad resist. If they get 18 hive cores, they can happily drag around very deadly radiation sources. If they want to. Really situational. The green suit looks the coolest though!

as god intended

**Comment by Kurfursten** [comment]
Goliath hides actually deal with a major threat miners face in their job. I don't know any miners who have died to basilisks. And for the record, I don't even mind the rads/bio thing for hivelords (no one will use these upgrades, except maybe to decorate an alternate suit). I guess it does have the weird upside of giving miners a good way to shard drag for completely unexplained reasons - they have nothing in their job that calls for radiation resist.

Giving miners 90% laser resist is just comical though. Fortunately, energy doesn't seem to be associated with being tased anymore, so it's not like that aspect is so bad (I honestly could not tell you what energy protects from at the moment). I don't think there's any other job anywhere as entitled as miners. Imagine if security officers were asking for their starting vest to get upgraded to their choice of 90% melee or 90% laser resist over the course of a shift. This isn't a fashion PR, these are extremely substantial stats that people already do grind.

**Comment by Optimism333** [comment]
> Goliath hides actually deal with a major threat miners face in their job. I don't know any miners who have died to basilisks. And for the record, I don't even mind the rads/bio thing for hivelords (no one will use these upgrades, except maybe to decorate an alternate suit). I guess it does have the weird upside of giving miners a good way to shard drag for completely unexplained reasons - they have nothing in their job that calls for radiation resist.
> 
> Giving miners 90% laser resist is just comical though. Fortunately, energy doesn't seem to be associated with being tased anymore, so it's not like that aspect is so bad (I honestly could not tell you what energy protects from at the moment). I don't think there's any other job anywhere as entitled as miners. Imagine if security officers were asking for their starting vest to get upgraded to their choice of 90% melee or 90% laser resist over the course of a shift. This isn't a fashion PR, these are extremely substantial stats that people already do grind.

Energy protects from the e-bow, supposedly.

**Comment by adacovsk** [comment]
Give me some reasonable numbers. The ablative has 80 for lasers, is that reasonable?

**Comment by Optimism333** [comment]
Kind of find myself agreeing with Kurf that 90 laser is too high. Maybe have that stat max out at 60. That's still plenty strong. Most combat hardsuits only have 30.

**Comment by jwhitak** [comment]
Security can get 80% melee resist and 80% laser resist from cargo and science respectively, no effort or grinding needed.

**Comment by Kurfursten** [comment]
Ablative
> Not spaceproof
> No built in light and helmet
> Wearing it a beacon of attention for most people, as it is a theft objective and gets you labeled as an "alblino"
> No head protection, more limited suit storage options
> Offers 30% less melee, 100% less bio, 35% less bomb, and 5% less rad than a completely unupgraded mining suit

NuAblative
> None of those drawbacks
> Miners WILL be wearing it all the time even though it is clearly oriented toward antag hunting more than asteroid business
> Because miners are insatiable for additional bonuses, there will soon be a PR to increase the drop rate on basilisk hides

Why is this a thing that *should* exist? As an engineer main myself I've never asked that building a great engine should let me supercharge my engineering rig to give me bullet resist.

**Comment by jwhitak** [comment]
More unorganized thoughts: The bassys are 1 hide per kill, but you can just spam advanced lazes and get infinitely many depending on credit spending (you can order more mining vendors from cargo). 90% is pretty damn high, 50% is far more reasonable. You'd probably have lost it on the 90% melee resist from goliath hides, but they've been around forever.

You also may have never asked for power to turn into bullet resist, but I have. Imagine a super charged bullet blocking gizmo that you could just hold and deflect bullets with! Fun times. Can't gun down THAT CE! Gotta be a shitter in a new way to kill him. Same with the blue miners of immune to lasers. Gotta use regular ass bullets on them. Or lube. Or a taser. Can't just e-sword them.

I do want to underline that none of these give bullet resist or stun immunity. Some of the most common types of killing people methods on the server. There's ways around a new form of resistance.

I really don't think anyone cares about rad resist too much though. Maybe a rare antag willing to grind out hivecores?

Also, why can't Science Hardsuit makers get some hefty hardsuits going with some upgrades? I'm surprised nobody coded it yet.

**Comment by Kurfursten** [comment]
I don't think rad resist is really relevant. If it was just rads I wouldn't really care and I don't think most people would, I was just pointing out that it's weird to give as a bonus since hivelords are neither associated with rads, nor does mining really deal with rads (xenoarch does on occasion though so maybe players would lean into that). And that's all fine, I honestly doubt anyone would care if the rad/bio resist even went up to 100% (all spacesuits are already 100% bio as is AFAIK).

**Comment by Optimism333** [comment]
> You also may have never asked for power to turn into bullet resist, but I have. Imagine a super charged bullet blocking gizmo that you could just hold and deflect bullets with! Fun times. Can't gun down THAT CE! Gotta be a shitter in a new way to kill him. Same with the blue miners of immune to lasers. Gotta use regular ass bullets on them. Or lube. Or a taser. Can't just e-sword them.

A personal shield item that can absorb a certain number of projectiles at a high power cost would be really cool

**Comment by BomberBro** [comment]
These sprites are hideous and, frankly, it's way too easy to pad out that 50 laser resist on a hardsuit. This needs to not just be a fighting game recolor of the goliath armor and the basilisk hide sprite is atrocious.

edit: If the basilisk hardsuit is an ablative then lol

**Comment by PrimeDSS13** [comment]
While I like the idea, the execution has a [lot] to be desired.

Additionally, Can you please describe what the upgrades actually *do* in the PR body?
You shouldn't have to codedive to find out that one of these is a superablative and the other is a meme, the numbers and effects should be in the base PR.

**Comment by tomacatx2** [comment]
make it take up the belt or exosuit slot to make it an actual decision you gotta make as an engineer

as for the PR in question, laser resist that doesnt outpace the sec suit or like a bit more than half an ablative doesnt seem like an issue to me
for starters, over like 75% of my miner rounds ive seen that im the only one to actually put the time and effort into farming a buncha goliath plates with laz injectors, cause it takes effort when i could be interacting on the station or killing more simplemobs
now even if i was antag and i had reason to farm enough plates of any type and frozen hivecore fullheals to last me in this life and the next, all it takes is one slip or stun and its game over

as to an actual reason why the suits should have laser and energy resist? iirc bassy attacks are energy and space drones are laser, both can be found in space (where the miner lives and breathes), as long as the values themselves are shit compared to actual dedicated station gear, i dont mind

**Comment by Optimism333** [comment]
> as for the PR in question, laser resist that doesnt outpace the sec suit or like a bit more than half an ablative doesnt seem like an issue to me for starters

> as to an actual reason why the suits should have laser and energy resist? iirc bassy attacks are energy and space drones are laser, both can be found in space (where the miner lives and breathes), as long as the values themselves are shit compared to actual dedicated station gear, i dont mind

I don't wanna be that guy, but even 50 laser resistance with full coverage is well over average for most dedicated station rigs, including the security rigs (they have 30 laser resistance, as do most combat-oriented rigs). 

So this absolutely would give a mining suit a resistance ceiling that if reached, makes them better at resisting lasers than most comparable station gear. It's hardly a "shit" value

**Comment by tomacatx2** [comment]
> > as for the PR in question, laser resist that doesnt outpace the sec suit or like a bit more than half an ablative doesnt seem like an issue to me for starters
> 
> > as to an actual reason why the suits should have laser and energy resist? iirc bassy attacks are energy and space drones are laser, both can be found in space (where the miner lives and breathes), as long as the values themselves are shit compared to actual dedicated station gear, i dont mind
> 
> I don't wanna be that guy, but even 50 laser resistance with full coverage is well over average for most dedicated station rigs, including the security rigs (they have 30 laser resistance, as do most combat-oriented rigs).
> 
> So this absolutely would give a mining suit a resistance ceiling that if reached, makes them better at resisting lasers than most comparable station gear.

true, then the values should again be tweaked
damn its like the author (or whoever is holding him at gun point to make this PR) didnt plan this out correctly.

**Comment by gurfan** [comment]
I don't think mining suits shouldn't get any extra resistances besides melee _at all_. Their actual job (which to the surprise of many, isn't running around maintenance hunting antagonists with the spur) isn't improved or even affected by these changes at all. There should not be a jack-of-all-trades when it comes to suit resistances- people should be encouraged to equip themselves for a specific situation, rather than wear one almighty suit all the time. (Looking at you, advanced EOD)

**Comment by DrSnips** [comment]
I feel like there's other avenues that these suits could take and this whole PR is kind of half baked. The armor stats are lazy, the sprites are lazy, and the reasoning is lacking.
While I like the colors, the sprites being just being green apple and wild berry poptart flavors could use a bit more effort.

**Comment by djkramer123** [comment]
Obligatory reminder that energy armor has been broken for a while now #29069
if it ever gets fixed 50 would be insane I'd imagine

**Comment by Optimism333** [comment]
> Obligatory reminder that energy armor has been broken for a while now #29069 if it ever gets fixed 50 would be insane I'd imagine

Energy armor useful when...

**Comment by pedr69** [comment]
what do you mean energy armor useless
emitter beams are the only things that do energy damage?

**Comment by pedr69** [comment]
also, the PR body itself is very confusing
from what i understand of the code, you have 3 upgrade paths now, and can pick only one

a mining hardsuit has base resists of 40% melee, 20% laser and 10% rad, but can be improved with:
goliath - melee resist, 10% per hide, up to 90%
basilisk - laser resist, 5% per hide, up to 30%
hivelord - rad resist, 10% per hide, up to 50%(the hardsuits are bio resistant to begin with)

**Comment by Optimism333** [comment]
> also, the PR body itself is very confusing from what i understand of the code, you have 3 upgrade paths now, and can pick only one
> 
> a mining hardsuit has base resists of 40% melee, 20% laser and 10% rad, but can be improved with: goliath - melee resist, 10% per hide, up to 90% basilisk - laser resist, 5% per hide, up to 30% hivelord - rad resist, 10% per hide, up to 50%(the hardsuits are bio resistant to begin with)

Helpful summary

**Comment by Eneocho** [comment]
Instead of adding rad shielding on hivecore, it could modify the suit into a pseudo HEV suit, dosing you with 5u tricordrazine/doctor's delight every 3 minutes, with each extra core reducing the delay by 30 seconds, to a minimum of 30 seconds, so you sacrifice the melee or laser defense for semi-reliable healing.

**Comment by adacovsk** [comment]
> Instead of adding rad shielding on hivecore, it could modify the suit into a pseudo HEV suit, dosing you with 5u tricordrazine/doctor's delight every 3 minutes, with each extra core reducing the delay by 30 seconds, to a minimum of 30 seconds, so you sacrifice the melee or laser defense for semi-reliable healing.

I could do that, will need some time to figure that out

**Comment by Eneocho** [comment]
Check the [Elite Security Skirt](https://github.com/vgstation-coders/vgstation13/blob/61606420dbcefd31dd7602d42caad2d5d55a0616/code/game/objects/items/trader.dm#L511-L518). It gives you some paracetamol every now and then.
You could probably do something like:
```
delay = 180
lastdose = world.time
if lastdose > (world.time + delay)
 reagents.add_reagent(doctorsdelight, 5)
```
And an attackby with the hivecores like:
```
if delay = 30
   return
else
   delay = delay - 30
```

**Comment by adacovsk** [comment]
> Check the [Elite Security Skirt](https://github.com/vgstation-coders/vgstation13/blob/61606420dbcefd31dd7602d42caad2d5d55a0616/code/game/objects/items/trader.dm#L511-L518). It gives you some paracetamol every now and then. You could probably do something like:
> 
> ```
> delay = 180
> lastdose = world.time
> if lastdose > (world.time + delay)
>  reagents.add_reagent(doctorsdelight, 5)
> ```
> 
> And an attackby with the hivecores like:
> 
> ```
> if delay = 30
>    return
> else
>    delay = delay - 30
> ```

not so simple, can't implement it as such. Requires process() and since it applies to multiple different types of rig suits, it is not feasible; it'd probably take me another day to do

**Comment by SonixApache** [comment]
Encasing the joint servos with basilisk (eyes? crystals?) cools them, allowing for higher output, reducing slowdown by 0.05 per application. The downsides are that it raises battery usage and doesn't leave room for armor plates.
Hivelord bits could be used to inject tricord / DD on injure, or to recharge the battery or something.

**Comment by Eneocho** [comment]
>Encasing the joint servos with basilisk (eyes? crystals?) cools them, allowing for higher output, reducing slowdown by 0.05 per application. The downsides are that it raises battery usage and doesn't leave room for armor plates.

That's actually a good idea. Though them cooling would imply more efficiency, thus less power usage.
I like where this is going, you could specialize with melee defense, no slowdown/speed or healing.

**Comment by aceedex** [comment]
I like the RBG miner suits. Hides are a big uggo but that's codersprites for you

**Comment by luigil101** [comment]
what kind of sec officer uses a laser gun over the shotgun

**Comment by Kurfursten** [comment]
I was initially against this, but I think Adam has at least taken steps to compromise. I believe Gurfan makes a very valid point - and truly it is unnecessary for their job, but the votes are clear - possibly even deceptive because some people may not have altered votes after changes. 30 laser armor is not nearly as offensive as 90, either way.

Miner creep will probably still continue unabated. Maybe someone will take this as an opportunity to add new enemies for miners that shoot lasers and radiation though. Last time we saw a new mine mob was rockernauts (unless you count Snaxi special mine enemies).

**Comment by Eneocho** [comment]
And here I was expecting for adam to implement the chem dispensing thing instead of the out of place radiation shielding.

**Comment by aceedex** [comment]
I woulda liked that too, tomorrows more of a day I suppose
Also for whatever's worth mining drones shoot lasers so it helps against friendly fire 
I guess

**Comment by Kurfursten** [comment]
Rogue minerbot as random enemies
Free minerbot collective as roidvault

**Comment by tomacatx2** [comment]
i can get behind this, guess i know my next code bounty posting

**Pull request merged**
