### PR TITLE
makes buttbots explode after a certain amount of butting

### PR DESCRIPTION
**Pull request by MadmanMartian**
Requested by administration.

:cl:
 * balance: Buttbots explode eventually after enough quotes

### CODE REVIEW

**Comment by Kharkov72** [comment]
or they could just have a small cooldown to stop them from melting the server
or roganbot could be not shitcode
kinda a shitty way to go about it

**Comment by SkowronX** [comment]
butt a unique buttbot buttwhere that butts forever

**Comment by aceedex** [comment]
why not a check that prevents the bot from buttyfing a sentence if it already has butt in it to prevent recursion?
Dont like this particular nerf

**Comment by SonixApache** [comment]
Did you check if the prints / fibers get properly transferred?

**Comment by utilitas-** [comment]
@aceedex
That is literally what is already in the code. Try talking to a buttbot, but include "butt" somewhere.

Also, stupid change: It's unintuitive. They should explode only when they quote a certain amount of times in a certain period, like they've overheated. Like more than 60 times in a minute, or more than 6 times per three seconds. Otherwise mapped-in buttbots will just randomly explode for no real reason.

**Comment by DamianX** [comment]
Now do the same for speakers.

**Comment by MadmanMartian** [comment]
@utilitas- if they want a subtype that just sits in a corner of maint to endlessly buttbot, there's now an available subtype.

**Comment by utilitas-** [comment]
It still does not make any natural sense for it to just randomly explode after N time, **especially** if it explodes after butting once (because that's how random chance works at the best of times). Add a hint in description/sprite, or change it so it explodes after buttbotting way too fast in a time span.

**Comment by MadmanMartian** [comment]
Nah

**Comment by SonixApache** [comment]
Please answer my inquiry 🙁

**Comment by MadmanMartian** [comment]
It unfortunately does not transfer prints, nor does destroying any other bots, nor does creating the butt bot transfer the prints from the previous amalgamation

**Comment by SonixApache** [comment]
Ah, alright.

**Pull request merged**
