### PR TITLE
Dynamic mode NTAW4: lower costs for Plague Mice

### PR DESCRIPTION
**Pull request by ShiftyRail**
See #29388 for the explanation of those changes. This PR is for plague mice.
Plague mice are a somewhat rare antagonist despite being an unusual one to fight. I think the very high requirements are a relic of the times when neo-nu virology was in need of tweaking. Now that it is in a (somewhat.......) stable place, it could be fun to see this kind of threat more often.

### CODE REVIEW

**Comment by BomberBro** [comment]
callofdeity

**Comment by GreatBigFailure** [comment]
I was going to write a sarcastic thing about "imagine if we had an antag that only the librarian could fix" to mirror the virologist but then I realized chaplains and sec. Still don't like em.

**Comment by Eneocho** [comment]
> 
> 
> I was going to write a sarcastic thing about "imagine if we had an antag that only the librarian could fix" to mirror the virologist but then I realized chaplains and sec. Still don't like em.

That'd be a good adminbus meme. An antag that could only be stopped by the librarian reading smut or some dumb shit.

**Comment by TGFH** [comment]
Honestly plague mice are just a total waste of threat. They typically get stomped in 30 seconds or die in the pipes -- if anyone even bothers to sign up that is.

**Comment by Kurfursten** [comment]
Conflicts

**Comment by gurfan** [comment]
literally just the virus event with extra steps

**Pull request closed without merging**
