### PR TITLE
adds custom glock to HoS locker

### PR DESCRIPTION
**Pull request by SonixApache**
🆑 
 - tweak: Added a custom glock to every HoS locker, replacing a flash

### CODE REVIEW

**Comment by SonixApache** [comment]
removed the flash to compensate
there's 5 in every sectech vendor anyway

it may be time to split the locker in two, like with the HoP, but that won't be happening in this PR.

**Comment by DrSnips** [comment]
That or put the standard sec gear(baton, flash, cuffs, spray, hailer, etc) into a box and have those in sec/hos lockers to dramatically cut down on the number of individual items per locker.

**Comment by SonixApache** [comment]
pre-loaded secbelts would be pretty heretical

**Comment by DrSnips** [comment]
Did I say belts?

**Comment by Durgen** [comment]
pre loaded secbelts when

**Comment by Blithering** [comment]
Maybe shift the weaponry to a more secure gunlocker? would free up room, but require remapping

**Comment by MadmanMartian** [comment]
At this point it might be an idea for the warden to have a requisition terminal for sec fluff stuff.

**Comment by beesil** [comment]
the hos already has one meme gun, so here's my proposal: glock with flame decals

image

**Comment by Blithering** [comment]
will submit pink plastic egun with rainbow stickers for approval shortly then
egunruined
edit: why did I do this

**Comment by beesil** [comment]
> will submit pink plastic egun with rainbow stickers for approval shortly then

brilliant, collab this man

**Comment by MadmanMartian** [comment]
Put it somewhere else. The Head of security's locker shouldn't be more armed than the armory.

**Pull request closed without merging**
