### PR TITLE
Adds pocket sand

### LINKED ISSUE #1880: Thrown sand needs to temporarily blind people with no eye protection
I tried to make this but I am incompetent

### PR DESCRIPTION
**Pull request by 9600bauds**
A fun experiment: "Let's close the oldest issue we can!"

Fixes  #1880

### CODE REVIEW

**Comment by Exxion** [comment]
This would have been horrifying that round a couple days ago the shaft miners brought back so much sand the admins turned on hardcore mode and declared it a dustbowl

Also :+1:

**Comment by FudgePucker** [comment]
:+1:

**Comment by Kurfursten** [comment]
Buffs botanists :+1:

**Comment by PJB3005** [comment]
:+1:

**Comment by CptWad** [comment]
:+1:

**Comment by Ephx1** [comment]
Perfect. PERFECT!
pocket-sand

**Comment by ghost** [comment]
Bless your heart

**Comment by NigglyWiggly** [comment]
Oh my god I love you

**Comment by 9600bauds** [comment]
Thanks, I love me too

**Pull request merged**
