### PR TITLE
More holster sanity (hopefully)

### LINKED ISSUE #16329: Holster sanity is still kinda broken
#### Description of issue

Attempting to draw an item from a holster of any type (knife or handgun) via macro/verb while both hands are full will tell you you need an empty hand to draw it.  Despite this, the item drops onto the floor under you, and will keep 'teleporting' after you if you continue attempting to draw it with both hands full.

If someone picks the item up and you attempt to draw it again, it'll duplicate the item - whoever's holding it keeps theirs, but another spawns under you.  These duplicates are still the SAME item, though, and if dropped or taken will remove the others.

If you pick it up yourself and then attempt to holster it by clicking on your jumpsuit/boots, you'll be given an error message for the holster being occupied.  Attempting to empty the holster with your other hand will work, but the weapon you were already holding will still be visible on your sprite and still be usable, despite not being in your hand slot.

There's a lot of other confusing behaviour that you'll notice if you test this out and trying to make it consistently work is giving me a headache.

#### Difference between expected and actual behavior

Expected to either be unable to draw the item with both hands full, or for the item dropped on the floor to not bug out horrendously.

#### Steps to reproduce 

1. Place item in holster.
2. Have hands full.
3. Attempt to draw item from holster with the Holster-(Handgun) or Holster-(Knife) verb, via the object tab or macro.

#### Specific information for locating

Shoulder holsters, knife holsters, and the like.  First noticed with the Head of Security's Lawgiver and Tactical Knife, but seems to be the case for everything.

#### Length of time in which bug has been known to occur

It seems to be the same issue with iconstates from #15366, which was supposed to have been fixed in #15600.

#### Server revision

bafcd50bbda22c552032a84673f973280f6bff46

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by ShiftyRail**
Creates a new proc, `put_in_empty_hands`, which put things in your hands if there is room for it and does nothing otherwise.
The old `put_in_hands` is for all intents and purposes similar to the one in this PR.
Not sure if there is anything I can do about the double `if(!W)`.
Should fix #16329.

Tested with knife holster, working as intended (a proper message failure, and only that, when I try to holster my knife.)

:cl:
- bugfix: Fixes sanity issues with knife and gun holsters.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Why does the empty hand checking need to go in its own proc, instead of just being incorporated into `put_in_hands()`?

**Comment by ShiftyRail** [comment]
@Shadowmech88 Because `put_in_hands` does actually two things : it first checks if you have available hands, and if you don't, it puts the item on the ground.
It makes sense in a lot of other cases (notably, if you draw an item from a container), so I didn't want to remove this feature. However, it caused problems with holsters.

**Comment by DamianX** [comment]
Sounds to me like `put_in_hands` doesn't do what it says on the tin. Perhaps it should be changed instead.

**Comment by ShiftyRail** [comment]
I actually don't know. The original coder must have had reasons to put the item on the ground if it was impossible to put the item in a empty hand.
I'm afraid if we replace `put_in_hands` with my proc, it is going to break something.
But also, in the way I've coded it, there is no way for `put_in_hands` to ever return 1. Dammit

**Comment by ShiftyRail** [comment]
@Shadowmech88 suggested I do this differently. At least we're sure we're only touching at holsters that way.

**Pull request merged**
