### PR TITLE
Custom vending machines for cargo

### PR DESCRIPTION
**Pull request by SonixApache**
Adds custom vending machines to the cargo departments of all the major maps in rotation.

🆑 
 - rscadd: Cargo now gets a roundstart custom vending machine on all maps in rotation.

### CODE REVIEW

**Comment by Kurfursten** [comment]
When you update the wiki link to the custom vendor place because iirc it's buried somewhere esoteric

**Comment by SonixApache** [comment]
i've added links to the cargo tech and QM pages

**Comment by agentofzog2** [comment]
I'd prefer it if cargo could just buy blank vending machines instead of having to run all the way to science or steal that very important groans vend.

**Comment by ghost** [comment]
@agentofzog2

You can use soldering iron to make tons of circuit board types, including vending machines. To make acid for soldering iron, you only need basic ghetto chemistry knowledge.

Grind flare, electrolyze water, combine sulfur from flare with oxygen and water.
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Recipes.dm#L232

This is something assistants use to rush out an autolathe in arrivals in first few minutes of a round, surely cargo will not have problems with it.

**Comment by agentofzog2** [comment]
Cargo can also mine for metal and glass instead of mining it but it's still there.
The point of cargo is to order things instead of working for them.

**Comment by Kurfursten** [comment]
I don't think orderable empty vendors is a bad idea, I also don't think it's in-scope for this PR

When you code it make sure it's a vendor that starts unanchored so we don't have to unwrench the vendor from the shuttle floor.

**Comment by SonixApache** [comment]
mapdiff is stuck

**Comment by Kurfursten** [comment]
I have examined the diff manually

**Pull request merged**
