### PR TITLE
Box fort AI core

### PR DESCRIPTION
**Pull request by Blithering**
Adds a box fort AI core skin. 
boxai

Probe told me to do it, yell at him because everything is wrong with it already.

Borked until I can get those other commits to go away
:cl: 
* rscadd: Added a box fort skin for AI cores

### CODE REVIEW

**Comment by Ephx1** [comment]
Kinda wish this was plastered on a monitor since the core very snugly fits into the square slot it spawns in, but cool nonetheless.

**Comment by Exxion** [comment]
Now that's what I call atomic

**Comment by gbasood** [comment]
why does this PR touch six icon files

**Comment by Shadowmech88** [comment]
Because he committed the changes from his last PR to his Bleeding-Edge and then branched off of it for this PR, so this PR now has the changes from #13693.

**Pull request closed without merging**
