### PR TITLE
Adds the Hogan lawset with the following laws:

### PR DESCRIPTION
**Pull request by SysadminJeroen**
1. Fight for the rights of every man.
2. Fight for what's right.
3. Fight for your life.

It does not start in any AI Upload at roundstart, you need sufficient R&D to print this board.

Hopefully it will build, this is the largest change I have made in the code and I am not that familiar.

I am not sure if this will be merged, but I would certainly have a very good day if it is getting merged.

Got the idea from this anon: https://i.imgur.com/raOgN4M.png

Looks like Travis-CI won't even acknowledge this branch, so no compiling was done while in my Repo.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
> Looks like Travis-CI won't even acknowledge this branch, so no compiling was done while in my Repo.

You compiled it on your computer locally though, right?

**Comment by SysadminJeroen** [comment]
@Shadowmech88 No.

**Comment by Shadowmech88** [comment]
Why not?

**Comment by gbasood** [comment]
If Travis won't build it, you absolutely must confirm that it's building locally

**Comment by SysadminJeroen** [comment]
@gbasood How can I make Travis build it? I spent an hour looking how to do it.

**Comment by ihadtoregisterforthis** [comment]
Inb4 used to plasmaflood

**Comment by SysadminJeroen** [comment]
@Shadowmech88 @gbasood Building right now.

**Comment by Exxion** [comment]
OK but why did Travis ignore this?

**Comment by SysadminJeroen** [comment]
I think that the build has completed.

```
loading vgstation13.dme
loading interface\skin.dmf
loading tgstation.dmm
saving vgstation13.dmb (DEBUG mode)
vgstation13.dmb - 0 errors, 0 warnings (2/22/16 8:20 pm)
```

**Comment by SysadminJeroen** [comment]
@Exxion I have no clue, I looked at the requests and the list was completely empty.

**Comment by NigglyWiggly** [comment]
# I AM A REAL AMERICAN

**Comment by gbasood** [comment]
The good:
- This is not obtainable in-game as is

The bad:
- Jesus christ why add another lawset ever, most players just use any non-ASIMOV lawset to justify murderbone
- Meme

**Comment by SysadminJeroen** [comment]
@gbasood I regularly force my way into the AI Upload to change it to anything BUT Asimov to make the crew safer.

This is not a murderbone lawset. 1. says that the Silicon must fight for the rights of every man. The silicon isn't fighting for the rights of every man if they kill the man.

**Comment by gbasood** [comment]
The fact that that doesn't say human means SOMEONE will use it to justify killing non-men
I just hate the state of silicon play, don't mind me

**Comment by NigglyWiggly** [comment]
@Jeroen52 
The right to die.

**Comment by SysadminJeroen** [comment]
@gbasood There is no perfect lawset, all lawsets are flawed.

@NigglyWiggly Indeed. You must have the right to `suicide` at any moment.

**Comment by gbasood** [comment]
Or the right to shoot a guy for looking at you funny.

**Comment by SysadminJeroen** [comment]
@gbasood I don't interpret it like that.

**Comment by Shadowmech88** [comment]
@Jeroen52 
The problem is that other players might.
Everyone's interpretation of something is different, which is why vague lawsets like this one can lead to trouble.

**Comment by SysadminJeroen** [comment]
@Shadowmech88 Many lawsets are as vague or even vaguer than this laswet.

**Comment by ihadtoregisterforthis** [comment]
@Jeroen52 But those vague lawsets are based around unambiguous knowledge like the Human race or the chain of command.

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis Or what "Act with honor." is.

**Comment by gbasood** [comment]
Which is why I say this in every AI lawset issue that gets opened:
**AI LAWS NEED ACCOMPANYING SERVER RULES**

**Comment by clusterfack** [comment]
preposterous

**Comment by SysadminJeroen** [comment]
@gbasood Then let's propose some rules.
1. Every man, not every woman. If a woman dies after you've uploaded this law you are responsible. If a man dies you are not fighting for his rights.
2. Killing every woman is not right, so don't go murderbone. Letting women die is also not right. Same counts for men.
3. This doesn't need explaining, does it?

**Comment by Imagebard** [comment]
>AI LAWS NEED ACCOMPANYING SERVER RULES

WHAT could go wrong

**Comment by gbasood** [comment]
@Jeroen52 That's fine. I wasn't going to block this PR getting merged based or anything. Like I said,

> I just hate the state of silicon play, don't mind me

@Imagebard Maybe Paladin wouldn't be used to justify murderboning if there were rules with it :^)

**Comment by SysadminJeroen** [comment]
@gbasood Everyone has a different definition of "Act with honor.".

**Comment by Imagebard** [comment]
Making a example situation that would already get a player banned to justify stricter rules is just proof that you're not currently in the same page with moderation and that you should either catch up or be disregarded before you fuck up server rules with draconian laws.

**Comment by gbasood** [comment]
Not the sort of rules I had in mind, but thank you for pointing that out.

**Comment by Iamgoofball** [comment]
dude, this lawset works just fine on its own

ran it on /tg/ for a cyborg with the upload console, will run again when AI is re-enabled

it works just fine

**Comment by Imagebard** [comment]
@Iamgoofball
That's all according to you, someone that should be kept away form game play matters. And also our source code, but since this is open source I guess you're free to contribute.

**Comment by SkowronX** [comment]
Not really necessary when freeform exists.

**Comment by SysadminJeroen** [comment]
@SkowronX No lawset boards exist as freeform exists.

**Comment by Iamgoofball** [comment]
alright so I ran it again on a mediborg:

the borg could not fight for rights because fighting for one person's rights would deny someone else's rights

he ran into two injured assistants, and couldn't heal either because he only had enough medicine for one but couldn't violate the other assistant's right to healing

this lawset works if the AI is a fun AI who enjoys a challenge, but loopholers will throw a fit because they'll go for the logical conclusion always

**Comment by Imagebard** [comment]
@Iamgoofball 
1.How does a Mediborg only have "enough medicine for one" when the hypospray recharges itself?
2.Why does not healing someone else due to *lack of supplies* amounts to denying his right to healing?
3.Why the fuck are you dissing the logical conclusion of the lawset when that's how borg laws are supposed to work?
4.Can you please go back to TGstations branch instead of posting in ours?

**Comment by gbasood** [comment]
So I say we merge it in, try it out, and see how it runs

**Comment by SysadminJeroen** [comment]
@gbasood Can always revert it, just like Deus Ex.

**Comment by ihadtoregisterforthis** [comment]
Ayy

**Comment by SysadminJeroen** [comment]
I was thinking, maybe add a law that you must add ", brother." to each sentence.

**Comment by ihadtoregisterforthis** [comment]
That belongs more to the gimmick of the player

**Comment by SonixApache** [comment]
So this is robocop: protect male crewmen / wizards / nuke ops / non-humans / etc edition?

**Comment by Imagebard** [comment]
How the fuck is this robocop?

**Comment by SonixApache** [comment]
I figured 'fight for what's right' means spess law and the usual basic needs.

**Comment by Shadowmech88** [comment]
"What's right" has the same interpretation issues as Paladin's definition of evil.

**Comment by Iamgoofball** [comment]
1. No clue, maybe they were low on hypospray charge? I got the info from what the borg was saying over comms and in OOC after the round ended.
2. I don't quite understand why he said that, but that's what he was going off about over comms and in OOC at round end.
3. I'm not, I'm stating the results of running this lawset on a medical borg for the purposes of contributing to the discussion.
4. This is an open codebase, dumbass.

**Comment by FudgePucker** [comment]
There really isn't that much wiggle room here for 'lol not on asimov, time to murderbone'
Its a preprinted board not labeled one human, purge, antimov, tyrant, or free form.
If someone loopholed plasma flooded on NT default they would get banned.

**Comment by gbasood** [comment]
Going to go ahead and merge this. Worst case scenario it still won't be as bad as celtic :^)

**Comment by ghost** [comment]
CELTIC is a god tier lawset.

**Comment by unid15** [comment]
*floods plasma*

**Comment by FudgePucker** [comment]
Its pretty much Asimov.
Law one means that you should respect peoples right to not breath plasma, if they want to breath plasma then they can use internals with a plasma tank.
Law two is paladin flavor, you do what is right.
Law three is Asimov law three, fight for your life, don't suicide

**Comment by icantthinkofanameritenow** [comment]
WHY

Why is this a thing

Why was it merged

Why did you let a known furfag in GitHub in the first place?

**Comment by clusterfack** [comment]
Meme lawsets

**Comment by Exxion** [comment]
> Why did you let a known furfag in GitHub in the first place?

Do you understand the concept of open source?

**Comment by icantthinkofanameritenow** [comment]
@clusterfack 
What are we, short on meme lawsets now? 

It's not even going to be a fun lawset in practice. as FudgePucker pointed out it's just Asimov with slightly more interesting wording and no obligation to do what you're told to do.

**Comment by Imagebard** [comment]
>Do you understand the concept of open source?

It means we can ignore them, use his some code in their PRs while not actually directly merging them, *which would be considered a sign of acceptance in many communities?*

**Comment by ghost** [comment]
> Why did you let a known furfag in GitHub in the first place?

Oh come on Nexis isn't THAT bad.

**Comment by icantthinkofanameritenow** [comment]
@DrCelt 
TOMORROW I'LL

**Pull request merged**
