### PR TITLE
Adds a link to the shortcut page on the wiki when you click the hotkey help button

### PR DESCRIPTION
**Pull request by Probe1**
Closes https://github.com/d3athrow/vgstation13/issues/10271

### CODE REVIEW

**Comment by 9600bauds** [comment]
The text here is pretty pretty damn long, the wiki link gets pushed off-screen
Probably add it to the bottom

**Comment by Probe1** [comment]
It doesn't.

**Comment by Probe1** [comment]
dreamseeker_2016-05-28_18-33-40

**Comment by 9600bauds** [comment]
Does for me
dreamseeker_2016-05-28_20-05-00

**Comment by PJB3005** [comment]
Holy shit I'm not the only person who hides the butt in that lobby art with the new player dialog.

**Comment by 9600bauds** [comment]
I have an irrational hatred for the one where the botanists are picking cotton
It's so dumb and it flashes so often

**Comment by Probe1** [comment]
I misread your comment and believed you meant it was too far to the right.

**Comment by Probe1** [comment]
image

**Comment by 9600bauds** [comment]
:clap:

**Pull request merged**
