### PR TITLE
tajaran monkeys now speak mouse

### PR DESCRIPTION
**Pull request by Intigracy**
just like daddy catbeast

#11213

### CODE REVIEW

**Review by Probe1 — APPROVED** [review]
Ur a faget

**Comment by Intigracy** [comment]
Github lets you discard needs changes reviews but not approved reviews, wtf.

**Review by Probe1 — APPROVED** [review]
Out fucking skilled

**Review by Probe1 — DISMISSED** [review]

**Comment by Probe1** [comment]
But can you dismiss the ones above that you DID NOT request

**Comment by Intigracy** [comment]
Yes.

You can dismiss any review as a collab.

**Comment by Shadowmech88** [comment]
I thought tajarans had their own language.

**Comment by Intigracy** [comment]
They do.

They also speak mouse.

**Comment by Intigracy** [comment]
languagetoadd = LANGUAGE_CATBEAST

**Comment by Shadowmech88** [comment]
Shouldn't tajaran monkeys get LANGUAGE_CATBEAST as well, then?

**Comment by Intigracy** [comment]
That var is from the monkey definition, they already do.

**Pull request merged**
