### PR TITLE
Makes diona immune to hypothermia

### PR DESCRIPTION
**Pull request by arc166**
Always found it weird how they're supposed to be space plants and stated to be resistant to the cold yet go unconcious in the cold at exactly the same speed as every other race on top of being restricted in armor they can wear that resists cold.

🆑 
- rscadd: Diona immunized to hypothermia

### CODE REVIEW

**Comment by brndd** [comment]
>yet go unconcious in the cold at exactly the same speed as every other race

Have you tested this? Because I swear I've seen a Diona survive space for several minutes before finally collapsing due to the cold. Wouldn't this change mean that they can actually spacewalk for... well, a very long time without wearing any space gear?

**Comment by DrSnips** [comment]
If anything dionas should die faster due to how cold and plants work normally.

**Comment by brndd** [comment]
>due to how cold and plants work normally.

You know trees don't die during the winter, right?

**Comment by Dacendeth** [comment]
They're resistant to cold right now as in they pass out about the same rate as a human but it takes upwards to 30 minutes for them to actually die to it.

**Comment by DrSnips** [comment]
Is that an IS_TREE flag or an IS_PLANT flag? Checkmate retard.
Jokes aside most tree aren't any more alive in the winter and go dormant which is technically them doing hypothermia stuff.

**Comment by brndd** [comment]
What the hell, all the other powercreep races get free roundstart spacesuits anyway so might as well give dionae this.

**Comment by arc166** [comment]
> 
> 
> > yet go unconcious in the cold at exactly the same speed as every other race
> 
> Have you tested this? Because I swear I've seen a Diona survive space for several minutes before finally collapsing due to the cold. Wouldn't this change mean that they can actually spacewalk for... well, a very long time without wearing any space gear?

Yes.  
They fall unconcious at the same rate as is. Even in mechs, despite not breathing, they have to turn on the mechs internals to not fall unconcious if not in space worthy gear.

**Comment by DrSnips** [comment]
>every race needs to start spaceworthy

Le slip slope is actually real this time. Mechs don't change anything for anyone. You always need the internals on in them in the case of being in space.

**Comment by arc166** [comment]
Mechs are super gay then

**Comment by Intigracy** [comment]
Remove hypothermia

**Comment by jknpj** [comment]
mechs block light, people forget they need light to live

**Comment by Blithering** [comment]
>restricted in armor they can wear that resists cold.

Last time this was mentioned, I tested diona and couldn't find a single item of standard (i.e. not vox or plasmaman specific) clothing they couldn't wear, can you double check this.

**Comment by arc166** [comment]
Off the top of my head, excavation suit, for no apparent reason. I know there are one or two other examples but I can't remember them at the moment or see anything on excavation to explain why its unable to be used by diona specifically.  
Also ancient suit, although you only find that by space walking to begin with.
My guess this is because diona are perpetually fat
And while testing just now the 'time' suit, although I'd be lying if I had any idea what that is or know if its some weird antag only armor or such

**Comment by Dacendeth** [comment]
The only thing that diona cant wear that i know of is the basic space suit (ugly white one), and the excavation suit, all rigsuits fit them.

**Comment by jknpj** [comment]
maybe because the excavation suit IS a reskinned basic grey suit

**Comment by Blithering** [comment]
Will this make them immune to heat as well as cold? Also seems a bit weird they can wear hardsuits just fine but not softsuits if it's a fat problem

**Comment by arc166** [comment]
> 
> 
> Will this make them immune to heat as well as cold? Also seems a bit weird they can wear hardsuits just fine but not softsuits if it's a fat problem

Nah, the hypothermia flag only negates the cold effect, it does nothing to heat

**Comment by Blithering** [comment]
Well that's a relief I suppose.

**Pull request merged**
