### PR TITLE
Plasma glass tables

### PR DESCRIPTION
**Pull request by ShiftyRail**
Sprites courtesy of @otatoh 

plasma tables

:cl:
- rscadd: Added plasma glass tables!

### CODE REVIEW

**Comment by SonixApache** [comment]
table datums when

**Comment by Kitfox88** [comment]
being able to bodyslam people through tables off the top ropes when

**Comment by Lunstra** [comment]
I feel like they could be a bit more purple instead of pink tbh. But I like em

**Comment by ShiftyRail** [comment]
I'm no spriter, defer complaints to my partner in this PR otatoh

**Pull request merged**
