### PR TITLE
A new scream sound plays if an user in a vehicle collides with a fuel tank and detonates it

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Done by request.
It is JUST the scream from https://www.youtube.com/watch?v=IY9YNF5MMQo
How it sounds in-game: https://a.pomf.cat/bcygmn.webm
The audio is not properly clean but the song playing in the audio is unnoticeable compared to the very loud detonation of the fuel tank that is happening at the same time.
:cl:
 * rscadd: Firebird drivers will now properly panic if they collide into a welder fuel tank.

### CODE REVIEW

**Comment by SonixApache** [comment]
blessed barry PRs

**Comment by BomberBro** [comment]
Let the record show that this was downvoted 30 seconds after creation.

**Comment by boy2mantwicethefam** [comment]
Compiled on my end, will fix.

**Comment by Kurfursten** [comment]
it's too bizarre because as you say you won't hear the first part and it's like... a full five seconds post collision that you hear "he's going over that cliff", then the scream

if it was just the scream maybe no big deal

**Comment by boy2mantwicethefam** [comment]
It is JUST the scream. I should've been clearer.

**Comment by BomberBro** [comment]
Can you post a video of this happening with audio?

**Comment by boy2mantwicethefam** [comment]
Give me 10 minutes to set up a proper recording system via ShareX.

**Comment by boy2mantwicethefam** [comment]
Wow, it was a pain to get it set up.
https://a.pomf.cat/bcygmn.webm

**Comment by Kurfursten** [comment]
A lot less offensive than I thought, I took off my 👎

**Comment by BomberBro** [comment]
I think you should cut out that weird gasp at the end and then it becomes really, really funny

**Comment by ghost** [comment]
now we need a use of the MY LEG! sound somewhere

**Comment by DeityLink** [comment]
> 
> 
> now we need a use of the MY LEG! sound somewhere

Whenever someone gets thrown

**Comment by Viciousaurus** [comment]
> How it sounds in-game: https://a.pomf.cat/bcygmn.webm

Maybe I'm defficient but I don't hear anything outside of the deafening explosion

**Comment by DeityLink** [comment]
> 
> 
> > How it sounds in-game: https://a.pomf.cat/bcygmn.webm
> 
> Maybe I'm defficient but I don't hear anything outside of the deafening explosion

I can hear it, though it could be a bit louder I guess (the scream, not the explosion)

**Comment by WindowsErrors** [comment]
you know how they actually threw a snake at somebody in the studio to get that scream?

**Pull request merged**
