### PR TITLE
Marina Borgs

### PR DESCRIPTION
**Pull request by SkowronX**
Adds new borg designs based on the marina sprite for mediborg.
Quick reference to the designs: http://imgur.com/rXBhbNt

### CODE REVIEW

**Comment by SkowronX** [comment]
Of all things I regret about spess, this one is the worst.

**Comment by TheEliminator16** [comment]
Agreed, Marina a shit

**Comment by clusterfack** [comment]
BOOTY BORGS WHEN

**Comment by SkowronX** [comment]
still hate myself for this

**Pull request merged**
