### PR TITLE
Adds a few more fat uniform sprites

### PR DESCRIPTION
**Pull request by DelaminatingShard**
Some more fat uniforms.
Turns out I made these over a year ago and never pushed them out lol

Uniforms: Pharmacist, Orderly, Plasma Researcher, Mechatronic Engineer, Biomechanical Engineer, Deathsquad.

fatuniforms2big

:cl:
 * rscadd: Adds a few more fat uniform sprites

### CODE REVIEW

**Comment by MadmanMartian** [comment]
>deathsquad

looks invincible

**Comment by DeityLink** [comment]
>deathsquad

I like it, do the ERT's as well while you're at it: it's basically a recolor.

**Comment by DelaminatingShard** [comment]
I actually did have an unfinished ERT uniform. ert1 I'll finish it for sure, but it won't be for a while, got a lot of RL shit to do in the coming week.

**Comment by DeityLink** [comment]
I might take care of it when I get home tonight then

**Comment by DeityLink** [comment]
there 
image

[uniform_fat.zip](https://github.com/vgstation-coders/vgstation13/files/2792990/uniform_fat.zip)

**Comment by DeityLink** [comment]
[uniform_fat.zip](https://github.com/vgstation-coders/vgstation13/files/2792999/uniform_fat.zip)

There we go 
image

**Pull request merged**
