### PR TITLE
Adds a potassium gun

### PR DESCRIPTION
**Pull request by SonixApache**
As requested by Angry Duck on the discord.
honk
morehonk

:cl:
- rscadd: A plastic banana gun now exists. It doesn't do anything.

### CODE REVIEW

**Comment by SonixApache** [comment]
wait hold up that commit aint supposed to be there

**Comment by Shadowmech88** [comment]
So how does this work? Because I was thinking of making a single-shot pistol that appears to be a banana until fired, at which point it turns into a banana peel.

Is there room for two banana guns?

**Comment by Intigracy** [comment]
clumsy_check = 0

**Comment by SonixApache** [comment]
@Shadowmech88 
It doesn't do anything, it's an upside-down banana with a trigger on it. You aim it at people to scare them.
Your thing is probably nicer to have, feel free to overwrite mine if it gets merged.

@Intigracy for what purpose

**Comment by Intigracy** [comment]
So that clowns can shoot the banana, duh.

**Comment by Intigracy** [comment]
Otherwise it'll blow up in their face.

**Comment by SonixApache** [comment]
@Intigracy will it blow up even if there's no ammo in it?

**Comment by N3X15** [comment]
Add a changelog and some pics plx

**Comment by SonixApache** [comment]
done

**Comment by kol1th** [comment]
Get an inhand sprite boi

**Comment by SonixApache** [comment]
it uses the revolver inhand sprite deliberately

**Comment by FudgePucker** [comment]
This reminds me of an idea I had a while back before my break.
Give bananas the ability to aim at people.
Add a new clown traitor item that is a single shot revolver that does bonus damage if you force it to go off after being held hostage, it is also perfectly similar to a banana, and can only be reloaded with a screw driver. Using the banana on yourself doesn't clear the chamber, but rather kills the person, because they tried to eat a banana that really is a gun (like that one chapter in JoJo part five) (also it needs to be loaded to kill, otherwise it should do small brute damage and make a tooth fall out).
Pretty much the perfect clown traitor item. Is that clown pretending to hold you hostage if you don't open that airlock for him, or should you do it before you have a new hole to breathe though?

**Comment by SonixApache** [comment]
fuck you, gun.dmi

**Comment by SonixApache** [comment]
okay well git has decided that gun.dmi will conflict no matter what so i'll probably close this soon

**Comment by SonixApache** [comment]
yeah okay fuck this i'm out

**Pull request closed without merging**
