### PR TITLE
Adds ass removal button

### PR DESCRIPTION
**Pull request by ghost**
For when somebody's being an ass in prayers, but not bad enough to warrant blowing them up

### CODE REVIEW

**Review by Intigracy — CHANGES_REQUESTED** [review]
log_admin()
message_admins()

**Review by Intigracy — APPROVED** [review]

**Comment by Probe1** [comment]
should it really leave them with all that damage though?

**Comment by ghost** [comment]
It's literally the ass removal spell. Leaves them in a puddle of their own blood and embarrasment

**Comment by Probe1** [comment]
I might regret this.

**Pull request merged**
