### PR TITLE
Specific lawyer sounds for spoken phrases

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[sound]

## What this does
if player wearing a lawyer outfit yells "objection!", "hold it!" or "take that!", a special sound plays and they emote pointing dramatically, with separate sounds for male and female players. "take that!" also plays when the lawyer outfitted throw an evidence bag onto a table immediately nearby

## Why it's good
arrpee flavour

## Changelog
:cl:
 * rscadd: People in lawyer outfits that shout "Objection!", "Hold it!" or "Take that!" now have specific sounds for each gender when said, along with emoting dramatic pointing. "Take that!" also plays when they throw an evidence bag onto an immediately nearby table.

### CODE REVIEW

**Comment by d3athrow** [comment]
This goes against your parole

**Comment by SonixApache** [comment]
@boy2mantwicethefam revive this

**Comment by SECBATON-GRIFFON** [comment]
> This goes against your parole

sorry, didn't read it clear enough

> boy2mantwicethefam revive this

it is what it is

**Comment by Eneocho** [comment]
i'll remind you to retry this when your parole gets lifted

**Pull request closed without merging**
