### PR TITLE
adds red & security sunglasses

### PR DESCRIPTION
**Pull request by SonixApache**
redglasses image
as requested by some guy at some point
You can find them in the secvends (replacing normal sunglasses) and the random sunglasses crates
Now also includes red sunglasses by Blithering! Those can be found in sunglasses crates.

🆑 
 - rscadd: Added security sunglasses. Can be found in secvends and sunglasses crates.
 - imageadd: Added red sunglasses.  Sprites by Blithering! Can be found in sunglasses crates.

### CODE REVIEW

**Comment by Blithering** [comment]
So they're not sechuds but they look like them?

**Comment by SonixApache** [comment]
Exactly.

**Comment by Blithering** [comment]
syndiexec
What about actually red sunglasses?

**Comment by SonixApache** [comment]
I'm fulfilling a request with this one, but those look fantastic. ~~Shoot me the icons and I'll throw them in.~~ ~~Going to add them ASAP.~~

**Comment by Kurfursten** [comment]
I've always thought sec needed aviators to complete their Kaz cosplay, if you're in an adventurous mood Blithering

**Comment by Blithering** [comment]
I'll see what I can do
something like this?
aviators

**Comment by Kurfursten** [comment]
Nice

**Comment by jknpj** [comment]
>does not apply a red matrix on your screen

Why

**Comment by SonixApache** [comment]
same reason the purple one doesn't purple matrix

**Comment by Blithering** [comment]
Do you mind adding the aviators to the PR? If not I'll send you the sprites

**Pull request merged**
