### PR TITLE
Blueprint Rack

### PR DESCRIPTION
**Pull request by Kurfursten**
Can be unlocked with librarian or mechanic access.
Up to 16 blueprints may persist between rounds if stored here. What will the mechanics of the past send you? A chem dispenser perhaps? A hand tele?

IAA inspection of blueprint rack may need to be a new job duty. Or I can just prevent illegal blueprints from persisting if that's better.

Needs to be mapped. (I am crying)

Limitations:
* No illegal scans (NT burns these)
* It ONLY saves the type, not the full design. This means you can't persist a machine with tier 4 parts.
* It ONLY saves what's in the machine at the end of shift. Took out a blueprint without returning it? It's gone. Someone logged on next shift and confiscated it? It's gone.
* You have to actually build the thing! Sure you have a hand tele blueprint but do you have the 50 phazon to make it?

🆑 
* rscadd: There is a new library blueprint rack that stores up to 16 blueprints between rounds for mechanics.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
Even I think this is too powerful, but it will also be very fun. The fun gets my vote, the too powerful gets my rant.
 
It will need to be HEAVILY balanced if it's to be added. Especially considering a lot of syndicate stuff isn't even considered illegal. Not to mention much of it will just look like a normal item (parapens are just "pen", exploding cuffs are just "handcuff"). So just making it not carry illegal things over won't necessarily fix it. Though you should probably not have it carry illegal things over.

Spitballing some balance:

- Tech level of the item has to be met to allow the blueprint to be used
- Add significant material costs to (only) blueprint designs produced by this
- Have each blueprint take up a significant amount of time to process. You'd need to make the prints interact with the reverse engine rather than just be put in a fab for this, but I'm talking like 5 full minutes, each, of processing time sort of thing
- Have the blueprints cost credits or something? Like you need to buy the patent from NT

With that said, I think the best way to keep this from being broken is a white/blacklist, but that would also probably make it really lame.

**Comment by jwhitak** [comment]
Persistence that removes bad mechanics like hiding away in your office to do a standard 100+ step checklist that you repeat in an identical manner every round is good.

Persistence that removes good mechanics like leaving your office and interacting with crew is bad.

Undercooked idea.

**Comment by mentgah** [comment]
giving your future self items feels metagamey as hell

**Comment by Kurfursten** [comment]
I think that there is some confusion in that you aren't storing items, just blueprints. For example, the hand tele blueprint is useless without phazon.

Also you are only giving to yourself if you play lots of consecutive shifts (good thing)

**Comment by GreatBigFailure** [comment]
> I think that there is some confusion in that you aren't storing items, just blueprints. For example, the hand tele blueprint is useless without phazon.

This is true for a lot of items but there are some that are very low cost. 
With that said, if you want to set out to tinker with the production costs of items this would be a good way to make a proper list.

> Also you are only giving to yourself if you play lots of consecutive shifts (good thing)

Fair enough

**Comment by ErrorsWindows** [comment]
> So just making it not carry illegal things over won't necessarily fix it. Though you should probably not have it carry illegal things over.

i'm a bit reminded of the old smuggler satchel on /tg/station that would hide items under the floorboards and carry over between rounds which was nice until **somebody** started giving themselves traitor items and wizard spell books every other round

**Comment by Kurfursten** [comment]
I have agreed no NO ILLEGAL SCANS which should quash that
Also don't forget: you have to actually build the thing

**Comment by ghost** [comment]
Please be honest and add a powercreep tag to this.

Now mechanics (an already regularly misused to spare rush and tide job, mind you) don't actually have to interact with the rest of the crew anymore to produce funky toys if somebody just so happened to scan and store 16 most powergamey items last Thursday on a deadpop shift. What's next, Magical Chemisty Refrigerator that persists all of the chems stored in it this shift so the chemists don't have to work or talk with anyone the next and can go cook their drugs/acids to validhunt from the get-go? Magical Slime Extract Refrigerator? Magical Virus Persistance Machine Thing?

This is feature bloat. Research archive was a good addition because 
> Persistence that removes bad mechanics like hiding away in your office to do a standard 100+ step checklist that you repeat in an identical manner every round is good.

and besides, Scientists have other time-consuming but much more interesting gameplay like Telescience, Toxins, etc.
This will be a bad addition because the only **unique** gameplay Mechanics have is running around the station scanning items/machinery then returning to their office to make them, and now you want to rob them of both half of their job and the main reason to interact with others.
> Persistence that removes good mechanics like leaving your office and interacting with crew is bad.

**Comment by Kurfursten** [comment]
Even though this has a positive ratio currently, I think it's too spicy for the current era. There may come a day, but I don't feel like it's worth trying to ram this through.

I also _generally_ agree with the argument that mechanics visiting people for scans is a good thing, although I think playing with the amount of rackable scans would fix that complaint. For example, chem dispenser is a pretty easy scan to acquire, so if you were only allowed to store 4 scans, I don't think people would store this one. Consideration for the future, perhaps.

**Pull request closed without merging**
