### PR TITLE
Working on food code

### LINKED ISSUE #3507: Cooked food nutriment values are too low
Eating raw food / grinded food into nutriment bars is both faster and more efficient than spending time cooking food, makes chef an artist instead of a cook.

### PR DESCRIPTION
**Pull request by ghost**
I usually never work on anything even remotely Chemistry-related. Hopefully, this should be within my competence
- Generally span, newlines, typecasting, absolute pathing, formatting
- Bring about the commentenning on recipe.dm. This is more or less a giant readme for all of the food code (at least the part where you cook shit), so it should be fine. This also allows coders who had about as much code literacy as I had when I started out to understand what is going on in here
- Nutriments now transfer over from raw ingredients to cooked food, like all other reagents used to. There's no reason to nuke nutriments, ESPECIALLY with high potency crops where you are actively wasting nutriments, time and miscellaneous ingredients to lose nutriments, to boot
- Remove make() function (which, incidentally, was NEVER used in the code). make_food() is now completely identical due to nutriments now transfering over (the sanity check was kept)
- Double volume all snack items can contain from 50 to 100. This was done so that reagents aren't wasted on the volume cap. Since drinks and condiment bottles inherit food, it was done at food/snacks level
- Salt shakers and peppermills now contain and start with 50 units of their respective reagents for consistency with "custom" salt shakers and pepper mills produced by using the CondiMaster
- Limitation on "reconverting" salt shakers and pepper mills removed
- Remove health value from meat, I simply cannot fathom what this would be doing here
- You can now explicitly exclude reagents from transferring from raw items to cooked items with the reagents_forbidden list, if you want to exclude dangerous or borderline lethal reagents present in the raw items to simulate the effects of cooking. Note that this deletes all reagents of that type, even those added in afterwards, so be careful about what you add to the ignore list

Fixes #3507

### CODE REVIEW

**Comment by 9600bauds** [comment]
Would this result in stuff like Aesir Salad having synaptizine in it?
If so, some recipes would need a bit of snowflake code to filter out certain reagents.

**Comment by ComicIronic** [comment]
I would suggest having an inherit_reagents var for recipes.
Then you could disable it for certain things with dangerous ingredients.

**Comment by dylanstrategie** [comment]
I'll look into a way to filter chemicals

**Comment by Arthurdentist** [comment]
1 unit of Chef's special sauce is enough to kill anyone. Are you sure its a good idea to up the amount to 50?

**Comment by ComicIronic** [comment]
I wouldn't include a balance change in a system PR. It will block the merge while people discuss it.

**Comment by TermedClepe** [comment]
That chef sauce change is bad, everything else is awesome.

**Comment by dylanstrategie** [comment]
I'll lower the Chef's Special Sauce again then

**Comment by 9600bauds** [comment]
It's not like you can't just put 30 units of water in the Chef's special sauce bottle and it will work as if it effectively had 50 units...

**Comment by dylanstrategie** [comment]
Dilution is possible in any container, and hell, you could have 100 units of diluted Chef's Special Sauce if you could bother to get a large beaker

**Pull request merged**
