### PR TITLE
Meat Blob

### PR DESCRIPTION
**Pull request by DeityLink**
A creature I worked on back in June, and arguably the one that's closest from completion among the planned Cult 4 mobs. Close enough that I figured I might as well let the collabs review it now, and let admins have fun bus-spawning it. Hopefully that'll get me back in the mindset of pumping out cult updates.

To admins: the button that spawns it is just below the one that spawns custom turrets.

https://github.com/vgstation-coders/vgstation13/assets/7573912/50e188f6-8565-494d-b1b3-1bdccc49a427

(note: visuals aren't the most recent, I've since then fixed some of the visible bugs and altered its spreading patterns. It shouldn't expand and retract the same tile repeatedly anymore)

- This creature moves around by spreading around similarly to how a space blob would, but it has a maximal size and must retract parts of itself to keep moving around
- Each of its tiles can be damaged. The damage moves around along with the tiles as they retract/expand. Once destroyed, a meatblob tile leaves a butcherable "corpse"
- After each movement it recomputes which tiles is at its "center". If that tile gets destroyed, the rest of the blob immediately goes inert.
- Its default behaviour is to alternate between staying idle (which allows it to slowly heal damage) and moving to a nearby visible location.
- When it gets hurt, it enters a fleeing state where it tries to move away from the source of damage.
- If it keeps getting hurt, it'll become able to move faster and faster. After a while without getting hurt it slows down until it re-enters its idle state.

### CODE REVIEW

**Comment by jwhitak** [comment]
Someone please add the 'it's loose' tag. It's loose.

**Comment by Kurfursten** [comment]
Perhaps not a good fit for your basic meat blob, but player blobs have access to other things like factory blobs. I keep thinking that meat blob might benefit from special organ segments perhaps if it gets turned into a separate mini-antag, functioning like the old space worm.

**Comment by GreatBigFailure** [comment]
It's cute, I love it

**Comment by DeityLink** [comment]
@Kurfursten It's not meant as an antagonist, or even a threat. Nor is it intended to be player-controlled for now.

Basically there's a list of creatures I have to code to populate the upcoming cult blood realm which I ranked from deadly to mild inconveniences. The meat blob is second from the bottom. Its purpose is both as an obstacle should players run away from a more dangerous creature, a source of "safe" food for players who go in there, and mostly prey for the other more dangerous mobs.

It's basically inspired by DF's cave blobs: https://dwarffortresswiki.org/index.php/DF2014:Cave_blob

**Comment by west3436** [comment]
Leave it to Deity to code a penis monster (it even comes with a butthole)

I just think the sprites could use some work

**Comment by DeityLink** [comment]
yeah the "center" sprite is definitely a work in progress, it's not meant to be a butthole, though I guess that's extra gross points. I made it so that admins can easily replace it though.

https://github.com/vgstation-coders/vgstation13/assets/7573912/d92a2372-818a-481d-81fc-040fea767291

The creature overall will look better in its intended environment, and as for all the things that come from the bloodrealm, there's also a stylistic choice to have them look slightly "off" and otherwordly. The sprites are good enough for now anyway. I can't spend too much time on each creature if I want to finish cult in my lifetime (plus there are other planned creatures whose looks I'd rather spend more time on to polish)

**Comment by Blithering** [comment]
Code wise, sorcery as usual. Sprite wise it looks a little bland for a creature from the nightmare zone, but it's serviceable and hardly something that'd prevent implementation.

**Comment by Eneocho** [comment]
Agreeing with the sprite comments, it basically looks like a skin sheet spreading like the puddles from the puddle PRs.
Make it more fleshy, grotesque. Actual walls of pulsing meat a la terraria's wall of flesh. It looks too tame for a meat blob.

**Comment by GreatBigFailure** [comment]
Personally I like how simple it looks. I'd rather a giant re-forming flesh tumor than a bloody hunk of raw meat, especially considering it isn't hostile, I think the simplicity communicates the lack of threat.

**Comment by DeityLink** [comment]
Yeah don't worry if I want to make it actually threatening in the future I'll do a pass on its looks. During development I actually considered having it potentially move toward player to try and deal damage if it managed to surround them or squeeze them against obstacles, but that's in the "maybe one day" list for now. There are like at least 6 other planned creatures of widely varying degrees of complexity I want to add.

**Comment by Eneocho** [comment]
That's fine. Do try to keep it in mind, though, the sprite is too bland for an eldritch creation summoned from the realm of blood and flesh. Just adding some pulsing veins and hue shifting it slightly towards red would do to make it feel eldritch (albeit still tame).

**Comment by kilozombie** [comment]
The eldritch realms must also encompass the fearfully mundane. The horror comes from there being a gigantic mass of featureless meat, not from that mass looking spooky and scary. It's just *wrong* to look at, which I think makes it special.

**Comment by Blithering** [comment]
I will not fearRP the haggis.

**Comment by GreatBigFailure** [comment]
> The eldritch realms must also encompass the fearfully mundane. The horror comes from there being a gigantic mass of featureless meat, not from that mass looking spooky and scary. It's just _wrong_ to look at, which I think makes it special.

This is a good way to sum it up. 
I strongly prefer this "Giant lump of slightly discoloured skin" look to something full of bloody gashes and wounds. 
If you did want to make it look more intimidating I'd say keep the general theme but add growths: little fingers, a leg or two, maybe patches of hair.

**Comment by Eneocho** [comment]
That would work. My issue is that right now it looks like dough.

**Comment by Blithering** [comment]
I was thinking veins, tumours, half formed faces etc. Something that breaks up the sausage look

**Pull request merged**
