### PR TITLE
Better default ghost icon

### PR DESCRIPTION
**Pull request by unid15**
Bottom: how ghosts will actually look (with transparency)

Top: comparison between new and current sprite

### CODE REVIEW

**Comment by clusterfack** [comment]
Big breasted ghost in a hoodie/10

**Comment by SkowronX** [comment]
But why.

**Comment by ihadtoregisterforthis** [comment]
Do they have directions?

**Comment by unid15** [comment]
They don't @ihadtoregisterforthis

**Comment by ihadtoregisterforthis** [comment]
A ghost that stares is better than a ghost that shows you its back if you move up a bit.

**Comment by unid15** [comment]
@N3X15 nothing was changed in game. Is there something on the secret repo?

**Comment by clusterfack** [comment]
For ghosts? Yes

**Comment by DeityLink** [comment]
Wasn't that sprite already in the game though?

**Comment by PJB3005** [comment]
@DeityLink I think it based used for the Boo! power.

**Comment by DeityLink** [comment]
I'm not really a fan of that icon for the actual mobs honestly. Something like the narsie-ghosts that are animated and look blurry is more spooky. We could use a modified version of those that only face south as to keep the spooky eyes visible.

**Comment by Zth--** [comment]
I second Deity. Ghosts should be spooky, not some funny sprite from ghostbusters

**Pull request merged**
