### PR TITLE
Ammunition tweaks

### PR DESCRIPTION
**Pull request by brndd**
[balance][consistency]

Everything about our ammunition "ecosystem" was retarded.

- Ammunition required silver to print, which was a good way to ensure it was never fucking printed unless a secman robbed the vault.
- We have a machine whose one purpose in life is to print ammo, but it couldn't print the ammo for half the fucking guns in the armory.
- Ammo costs were all over the place.

This PR changes it so that the ammolathe prints *most* of the ammo used by the standard guns, and printing it no longer requires silver. It can now print 9mm and 12mm ammo and mags. It can now print all the shotgun ammo as boxes, most the single-print shotgun ammo was removed except for blanks which had no box. It can even print .357 ammo. Whatever was available in the autolathe is still in the autolathe too.

9mm and 12mm ammo has been removed from the protolathe. If ablinos want to print ammo for the guns that they can print, they're gonna have to ~~get that NT research and~~ build themselves an ammolathe.

I also changed some wording and grammar, mostly for tacticoolness factor.

:cl:
 * tweak: The ammolathe now prints more useful ammo. Printing ammo from the ammolathe no longer requires silver aside from a couple of special types.
 * tweak: The protolathe no longer prints 9mm or 12mm ammo, nor shotgun stun shells. These have all been moved into the ammolathe.
 * tweak: The ammolathe circuit board can now be constructed at the circuit imprinter, requiring 2 Programming (data theory?), 2 Engineering, 4 Combat. It comes in a locked box.

### CODE REVIEW

**Comment by juanototo2** [comment]
Unatomic. Keep 9mil and 12mil being removed from the proto out of this fucking PR.

**Comment by boy2mantwicethefam** [comment]
I use my authority as a certified occasional scientist main (TM) to greenlight the removal of bullets from the protolathe, it never really made any sense, besides can't they just print ammolathe boards now

**Comment by brndd** [comment]
>besides can't they just print ammolathe boards now

Yes, but the Ammolathe board requires NT research. Which I think is a good thing. Makes it more relevant.

**Comment by boy2mantwicethefam** [comment]
You can't get to Level 5 NT research

**Comment by boy2mantwicethefam** [comment]
In fact, you can't get to any NT research above 1. It's just the cargo disk has one level and there are no items with NT research to give, anything above 1 is basically adminbus territory

**Comment by brndd** [comment]
Aight, good point. I'll just switch the ammolathe to use NT research 1. It has a construction recipe, so I don't see why not. It's not exactly a powerful item. Or I guess it's kinda powerful since you can build a rocket launcher, hah hah oh well.

**Comment by ShiftyRail** [comment]
The ammolathe made a lot of noise for not much pratical change. There's more than enough ammo in stock for most rounds, and if you are running short on lead, lasguns and the lawgiver only need a recharger.

I don't understand why this is such a heated issue.

**Comment by brndd** [comment]
I'll see later today if I can make the ammolathe circuit start in a lockbox since it does let you print vectors and glocks and RPGs.

**Comment by brndd** [comment]
Well, that was easy.

I made producing the board require NT research 1, but looking at what else is unlocked at NT research 1 I think it's a little weird — all the other stuff is like experimental crap. I'm axing the NT research requirement from the ammolathe board, since it now comes in a locked box.

👎 this comment if you think this is a terrible idea, and I guess you can 👍 if you think it's alright too.

**Comment by brndd** [comment]
While I have the eyes of potential sec experts here, please give me your opinions on either making all the empty mags in this print out with ammunition included, or alternatively adding most of the ammo for them into the ammolathe one way or another; some into the standard selection, the rarer ones into the contraband list (because contraband on it is currently fucking awful).

After this PR I intend to do a further powercreep PR for this, so that ammunition like A762 can be acquired. I don't have great insight into gun balance because most of them I've never used.

**Comment by ghost** [comment]
I think forcing people to fill the magazines/clips themselves is a reasonable step, unless your aim is to reduce clutter, in which case I can see an argument for the former option.

**Comment by tuypo1** [comment]
sounds good but juanototo is right, unatomic

**Comment by tuypo1** [comment]
I think it's better to have the magazines printed empty, if only because it is funny to see newbies tripped up by it

**Comment by ghost** [comment]
Keep it as a separate PR then, but they should be removed.

**Comment by calzilla1** [comment]
As one of the only warden mains... hahahahahHAHAHAHAA

**Pull request merged**
