### PR TITLE
Adds Sol Common, a human-unique language, renames prev Sol Comm. to Galactic Common

### LINKED ISSUE #7670: Galactic Common is no longer a thing.
It used to be that Humans had Sol Common as their species language that they could insult the filthy xenos with, and that Galactic Common was what everyone spoke.

Now everyone across the galaxy ever speaks the Sol language, and humans cannot cry out GAS THE VOX SLAY THE AYY BURN THE TREES CRACK THE ACK in their own language ever.

### PR DESCRIPTION
**Pull request by gbasood**
Doesn't look a damn thing like actual Esperanto but it's distinguishable from the other languages.
Also made Gutter actually have different syllables from Tradeband.
Resolves #7670, #4501

### CODE REVIEW

**Comment by clusterfack** [comment]
*Literally calling it esperanto*

Have some tact, please

**Comment by gbasood** [comment]
Well I could re-name Sol Common to Galactic Common and call this language Sol Common.

**Comment by clusterfack** [comment]
Well yeah that's pretty much what everyone wanted

**Comment by CptWad** [comment]
But will vox raiders know galactic common?

**Comment by gbasood** [comment]
All instances of Sol Common before are now Galactic Common, so no.

**Comment by Imagebard** [comment]
Finally

@CptWad 
If you're going to play the lore game...
Heist Vox have no reason to know Galactic Common that the rest of the crewmembers know, they're all children that just left the isolated vox ship to raid for supplies.

**Comment by sonime** [comment]
Should keep current Sol Common as is, make it the snowflake language for the humies, and keep Esperanto as the language that everyone knows.

Sol Common is based off Mandarin, which related to a single country on Earth.
Esperanto was made as a worldwide language, and IMO, works better as "that language that everyone knows".

**Comment by gbasood** [comment]
On the other hand:
Esperanto is a formal diplomatic language at best, and no one uses it ever. Only a few humans would know it.
Sol Common is based off of languages that most humans use today, so most humans should know it.

It's semantics really.

**Comment by ihadtoregisterforthis** [comment]
Everyone is working on a humie station, and by the quality of the personnel I don't think the humies were worth enough to teach them space language. 

Also special snowflake language is more of a feature for special snowflake races.

**Comment by Imagebard** [comment]
@ihadtoregisterforthis 
You realize that if you're searching for a job in space you should know the current global space language, not the language of Earth, right?

**Comment by gbasood** [comment]
errybody gets a snowflake language

**Comment by Exxion** [comment]
I'm with @sonime in that I think the syllables should probably be changed for Galactic Common to make them not based on common HUMAN languages
But otherwise this seems fine

**Comment by gbasood** [comment]
Tradeband uses latin gibberish, which is human, though.

**Comment by Exxion** [comment]
Those syllables are most likely a placeholder anyway, considering they're lorem ipsum
I'm definitely not arguing against them being changed too

But both of those issues might be outside the scope of this PR anyway

**Comment by ghost** [comment]
I don't suppose you'd squeeze in a fix for diona nymphs knowing monkey language instead of root speak.

**Comment by 9600bauds** [comment]
I'll do that right now

**Pull request merged**
