### PR TITLE
Fix photos again

### LINKED ISSUE #33363: Clothing stays facing forward in booth photos
(WEB REPORT BY: confusedcactus REMOTE: 206.221.180.138:7777)
# Revision
206b1b3d19ee84d5c99ab03f52645a42ea561af4

# Description
The photo booth doesn't rotate clothes in the photos while the person rotates.
https://cdn.discordapp.com/attachments/1021568625951375413/1022979496791507015/unknown.png
# Steps to Reproduce
take a photo in the booth
# What you Expected
clothes to face the same direction as the person in the photo
# What Actually Happened
clothes still oriented directly forward

### PR DESCRIPTION
**Pull request by DeityLink**
Reverts the changes from #33309 and forces bees to face South after moving.

Fixes #33363

:cl:
* bugfix: Fixed newly arisen photography issues with objects not facing the right way.

### CODE REVIEW

**Comment by DeityLink** [comment]
I've properly tested it this time.

**Comment by Kurfursten** [comment]
I thought about what you said, and maybe we should make this a higher level characteristic? That is to say, maybe even as high as mob level we should have a flag or var for a "directionless" mob, one intended to only have one directional state

**Comment by Exxion** [comment]
Or we could just deal with this horseshit until 515 gives us a real way to render flat icons

**Comment by DeityLink** [comment]
Yeah, ultimately this is a crutch while waiting for DM to stop rendering blank image when using the icon proc with a non-south dir argument on an icon-state that only has 1 direction.

@Kurfursten this shouldn't be needed since bees are basically the only mob that I know of with a 1-Direction icon_state. Flat objects like buckets, flashes and whatnot are much more at risk, although thankfully my "base64 hack" can detect those in most cases.

**Comment by DeityLink** [comment]
actually maybe bats too? but in their case we could just turn their sprite into a 4-Directional one. I didn't want to do this with bees since they have lots of icon_states which would substantially increase the dmi file size.

**Pull request merged**
