### PR TITLE
beekeeping 4.1.18

### PR DESCRIPTION
**Pull request by Blithering**
Adds bees to places bees were previously not.
:cl:
 * rscadd: more options for beekeepers, introduces two new kinds of bees!

### CODE REVIEW

**Comment by MiniMeatwad** [comment]
sounds good for april fools

**Comment by Aurx** [comment]
Should bee fun.

**Comment by nuklearcellphoneg** [comment]
I dunno if you've seen this https://github.com/vgstation-coders/vgstation13/issues/17905 and if any changes deity intended to make might affect yours or vice versa

**Comment by Blithering** [comment]
@nuklearcellphoneg pretty sure the two are compatible

**Comment by DeityLink** [comment]
>+0 −0

image

**Comment by DeityLink** [comment]
@Blithering don't forget to add the hydroponics tray sprite underneath.

**Comment by Blithering** [comment]
>cannot revert automatically

Oh dear, the bees have taken over

**Pull request merged**
