### PR TITLE
Adds Magmaws

### PR DESCRIPTION
**Pull request by MadmanMartian**
An invasive species has been spotted infesting plasma-rich asteroids.

Magmaws are known for feasting on plasma deposits, which they use to stoke their internal furnaces to stay 'alive', letting off streams of fire in the process.

Sprites courtesy of @Blithering

### CODE REVIEW

**Comment by mtpowell** [comment]
The fuck do they look like?

**Comment by Intigracy** [comment]
Click the arrow in the bot's comment buddy.

**Comment by SonixApache** [comment]
Cute!
Magic numbers for the `add_thermal_energy` calls?

No real reward from killing them, apart from them no longer eating your plasma? 
Maybe thermal plates for reinforcing the mining suit, or just the ability to butcher them for pre-cooked meat or something. Or allow them to be tamed with plasma.

**Comment by jknpj** [comment]
@SonixApache they are the reward themselves, just toss them inside a burning chamber and feed them with plasma and they'll keep the heat raising until it reaches R-UST-tier

**Comment by Kurfursten** [comment]
Extremely rare mining engine

P.A.C.M.A.N. has a tiny magmaw inside

**Comment by Durgen** [comment]
more engine autism is always good

**Comment by Exxion** [comment]
Power the station with hivelord treadmills and a magmaw TEG

**Comment by Kurfursten** [comment]
What if you could use magmaw bodies as a one-use microwave, destroying the corpse exchange? That could open up all kinds of cool roid cooking ideas and save ambitious miners (or even more ambitious xenoarchs) on "come back for pizza" trips.

Remind me after this gets merged and I'll write it

**Pull request merged**
