### PR TITLE
Borg Smashing

### PR DESCRIPTION
**Pull request by Kurfursten**
Inspiration taken from both magboot stomping and limb gibbing. When you hit a dead borg with a weapon of 15 force or more, you have a chance to rip it apart after 3 seconds. This process can be interrupted.

The formula is max((force/7.5)^3,25), or put more legibly, here are some percentage chances:
16-21 force: 25%
22 force: 27%
30 force: 64%
35 force: 99%
This formula was based off of the formula for human limbgibbing. There is a 25% chance for each robolimb to drop with the gibs.

🆑 
* rscadd: You can now smash borgs to get out the MMI/posibrain and some limbs. It requires a weapon of >15 force.

### CODE REVIEW

**Comment by beesil** [comment]
based and antisilicongang pilled

**Comment by SonixApache** [comment]
kind of dumb that you can't just force-disassemble them
especially considering that the ID lock gets released upon their demise now

**Comment by SGuivenne** [comment]
This is going to make more idiots destroy borgs fully during the malf rounds not realizing they could totally use them as meat shields that will basically soak up lasers forever.

**Comment by Kurfursten** [comment]
This doesn't remove the old behavior, if you have a toolbelt on you and you want to disassemble them you still can

Much in the way that you can perform proper surgery to remove someone's brain, or choose to decapitate them and do the scalpel-circ saw method, or just gib it with a brute weapon or gun. This just adds options.

**Comment by SonixApache** [comment]
Neither are good additions.

**Comment by Kurfursten** [comment]
I don't get what you mean.

**Comment by SonixApache** [comment]
I think being able to rip someone's (mmi)brain out without too much hassle is a horrible feature. No easier way to permanently remove people than that.

**Comment by DamianX** [comment]
borgs are not people

**Comment by SonixApache** [comment]
Contrary to the way you play the game yourself, borgs are very much players. Just as much as chaplains, cargonians, heads, greyshirts and redshirts.

They're all equally shit.

**Comment by Kurfursten** [comment]
Okay, jokes aside though I am willing to respect your different worldview that no one - human or borg - should be debrained. However, it feels like most people here want parity to go in the other direction.

**Comment by Blithering** [comment]
I don't like the idea of toolboxes having a 1 in 4 chance of gibbing a dead borg mostly from the perspective of making it require completely rebuilding the borg at that point. Internals components breaking is pretty much limbs and organs getting gibbed already, and borgs fully capable of being gibbed by explosions same as real people

Just thought it also makes it really easy to dispose of evidence when killing a borg, whereas no matter how many limbs you gib on a person, there's still a mangled torso unless you have the traitor chef knife to butcher them with.

**Comment by Accipitermaris** [comment]
borgs gibbed by explosions (or shuttlecrush, etc.) tend to ALWAYS leave the mmi/posi behind for whatever reason

i've heard stuff like "well, they're in a thick metal chassis" but i doubt this is intended as the same is also true of highly squishy mommis

**Pull request merged**
