### PR TITLE
Is crismas

### PR DESCRIPTION
**Pull request by ghost**
Well, I did do the map tools stuff, straight from a fresh pull from the github, but it's still saying everything is broken

Props to @SkowronX for the sprite, and @Probe1 For asking me at 20 past midnight on christmas day to add this because he was suffering the same problem that I'm having anyway

### CODE REVIEW

**Comment by gbasood** [comment]
fffff
can a mapper check out why the map diffs are so huge
maybe both probe and dragonbro just dont know how to use maptools somehow but that seems crazy
all I can think of though is that maptools didnt do its job

**Comment by Probe1** [comment]
You're reading this PR and wondering what the fuck.  

Well, last night around this time I was messing with the maps in Notepad++ and didn't bother cleaning the maps.  When I committed it I saw a shitload of changes and immediately set my (local) Bleeding-Edge to target upstream/d3athrow, pulled, then _accidentally hit push_ before I retargeted at origin/Probe1.  

I was not aware that I could push directly to the upstream repository without a password.

I spent an hour today struggling to get the map cleaner to work but everything was giving me as many lines changed as Dragonbro has here.  I gave up.  12 hours later I asked Dragonbro to handle the PR listed above, assuming that I somehow someway fucked up my repository and didn't have the energy to deal with it on Christmas Eve.  But now, he has the exact same issue.

I panicked when he told me this and asked @gbasood what it meant. He assures me that the log would show a commit unless I somehow also squashed that commit.  Which isn't impossible but I'd remember doing if I had.

I'm fucking fresh out of ideas.  The only thing that makes sense is I somehow fucked up.

**Comment by gbasood** [comment]
if the files did fuck up
`git log -- filename` would show you the latest commits to that file
🤷‍♂️

**Comment by Probe1** [comment]
I pulled from upstream and I got nothing here.  Why did Dragonbro have the same problem in this PR?  Why did I spend all morning with this problem?  What in the fuck?!

image

**Comment by gbasood** [comment]
maptools didnt happen on these files
that's literally all

**Comment by Probe1** [comment]
?

**Comment by gbasood** [comment]
as in
the tool
didn't do shit

**Comment by SkowronX** [comment]
ded

**Comment by Probe1** [comment]
As punishment i've been varediting the sprite in every round.

**Comment by Probe1** [comment]
I'm going to test merge this today.

**Comment by ghost** [comment]
Is no longer crismas though

**Comment by Probe1** [comment]
PJB will look at whats happening today.

**Comment by SkowronX** [comment]
may as well just close this. thanks

**Comment by Probe1** [comment]
Its more about figuring out what the fuck just happened

**Comment by ghost** [comment]
Is no longer crismas

**Comment by SkowronX** [comment]
Christmas was yesterday. figure it out on your own time. 

Just more salt to add to my pile.

**Comment by Probe1** [comment]
I MANUALLY added it for 5 out of the 8 rounds that happened and I did it 4u @SkowronX

**Comment by Probe1** [comment]
dreamseeker_2016-12-25_18-20-46

(I changed the lights layer later)

**Comment by ghost** [comment]
The sprite is beautiful, skowron

**Pull request closed without merging**
