### PR TITLE
Allows Clowns, when antagonists, to toggle their clumsiness at will.

### PR DESCRIPTION
**Pull request by ShiftyRail**
Inspired by #17913, @carshalash may find it of interested
Don't merge it yet, I need an idea for the icon.

It's a bit snowflakey, but it does its job, I guess.

:cl:
- rsadd: Clowns, when antagonists, can toggle their clumsiness at all.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
It compiled on my machine

**Comment by Blithering** [comment]
banana peel might work for the icon

**Comment by mtpowell** [comment]
NYET, this makes playing the clown easy mode

**Comment by Aurx** [comment]
Neg, it makes it normal mode.  
And come on, add stat-tracking so if they did/didn't toggle it is reported at round-end.  Let the good clowns brag and the scrubs get shamed.

**Comment by Dacendeth** [comment]
You should only be able to turn it off and then it's off for good, sorta like breaking a vow of clumsy.

**Comment by imw-Oculus** [comment]
I like that we have roles that have specific boons or hindrances. Can I ask what the reasoning behind this PR?

**Comment by Pathid** [comment]
@imw-Oculus 
https://github.com/vgstation-coders/vgstation13/pull/17371#issuecomment-364022398
Seemed like a good idea in context since antag testing kept coming up.

**Comment by ghost** [comment]
Stat tracking so people know who bitched out when?

**Comment by Allspice** [comment]
The only roles that are probably actually worse off for antag clown clumsy are cult and (narnar forgive me) head rev, due to the costs to the team of a clown shitting the bed from their own incompetence. But just fiddling with clumsy for those two modes seems a bit like a needless inconsistency. Hm.

**Comment by Probe1** [comment]
Clowns should never lose clumsy.  They already have CLUMSY SPECIFIC duplicate items for unrobust fags that want to both be a clown and murderbone.  If you want to be robust, but you aren't robust enough for clown, don't play clown.  There's no two ways around it.

@SarahJohnson489 When you reach 3 bitchouts, Auto-clown-ban.  Like warnings for unrobust.

@Allspice Clown losing clumsy during rev is 100% pure and inexcusable cancer.  Here's a guy that there's an expectation of hijinks, fun, and mild griefing walking around with a fireaxe.  And he's now stun decapitated you because the game mode is rev.  It was pure AIDS when we they would lose clumsy in the past during rev.

**Comment by Allspice** [comment]
As a head rev probe, not a standard rev. Due to the flash thing. As much as I detest rev, it's more of a matter of the clown head rev fucking up its teammates more than the usual moron head rev.

**Comment by Probe1** [comment]
Ok I'll concede head rev.  But I swear to Allah giving antag clowns special exceptions was the biggest gay.

**Comment by Blithering** [comment]
clown head revs should convert on slip

**Comment by Ratvar** [comment]
Or you should add snowflake check for headrev clown flashing

**Comment by ShiftyRail** [comment]
This is controversial and way to hard to do properly with all the antags of the game.
Leaving that branch, in case someone wants to do it.
Also, this is something we should look at in datums™️

**Pull request closed without merging**
