### PR TITLE
Fix meteor spawning directions, add meteor subtypes

### PR DESCRIPTION
**Pull request by ghost**
Whereas a new era downs on space rocks

General technical changes : 
- Fixed meteor spawning directions. Meteors will no longer get caught in the transition zone (especially when spawning from the east), and will head to the opposite side 100 % of the time (I guess it was that hard to write x and y axis transitions properly ?)
- Meteors now have a functional delay for spawning, which means that meteors will spawn within 1 to 3 ticks of eachother. That might sound very short, but it's certainly much, much more sequenced than the "all 100 of them at once" technique that caused apocalyptic lag. Talking of which
- Lag has been massively reduced again, and since meteors don't strike all at once wave sizes no longer impact latency. Waves also last much longer, which means intelligent Engineers can go to the side the meteors aren't striking to repair shit
- Increased meteor wave sizes from (50, 100) to (60, 125) to adjust for the multiple changes in meteor destructiveness. Benchmarked to breach the AI Core at shuttle arrival and leave little standing if no repairs or fortification are attempted
- Used event weighted lists as a model to spawn weighted meteors. This makes everything more modular, and also means small meteor waves will now spawn 100 % of their meteors, and so will medium ones (instead of 40 % and 95 % respectively)

New meteor types, all meteors are weighted at 5 % chance of spawning (out of total of all meteors, same as big meteors previously) : 
- Small flash meteor, flashes everyone in view similar to a flashbang. Explodes like a small meteor
- Medium radioactive meteor, irradiates everyone in view for (5, 10). Explodes like a normal meteor
- Medium piercing meteor, devastates first tile in the way (allowing it to pass unless bomb-proof), then explodes like a normal meteor
- Big cluster meteor, devastates own tile on explosion and sends three medium meteors hurling in random directions
- All meteor types have blazing new sprites (a bit coder-y art, but distinct), even old ones (so the big meteor is now visually big, for the viewing pleasure of whoever is on the receiving end)

Changelog included. Discussion goes below

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
You could watch into the meteors alert messages. The meteor warning tells everything is a-ok again just as the last wave spawns, and so meteors hit the station when it should be all safe. Panic ensues briefly.

Also post pics of the meaty whores

**Comment by ghost** [comment]
The problem is that meteor events end too rapidly, that can easily be fixed by tweaking two values

Here's three random meteor icons : 

big
small_flash
medium_piercing

**Comment by CptWad** [comment]
This is ok
:+1:

**Comment by AutismSpider** [comment]
The radioactive meteor going have glow to it like green or pale yellow?

**Comment by icantthinkofanameritenow** [comment]
Jesus, Dylan, do you have some kind of meteor fetish? It's literally all you ever code.

**Comment by TheEliminator16** [comment]
Meteors a best, I hope that we can make it so that meteor rounds aren't reviled anymore, I personally love them.

**Comment by clusterfack** [comment]
ANTAG OBSERVERS WHEN

**Comment by Iamgoofball** [comment]
> no meator

**Comment by ghost** [comment]
> Meator hits the station
> Shoguns spiked meat chunks forward for 70 tiles in a 25 degree cone

Fund it

**Comment by ghost** [comment]
For the radioactive meteor, I went with a silver look because according to Wikipedia that's what unrefined, unoxyded uranium looks like, and I don't want to upset some people

I'm planning to add changes in waves. That PR fixes all the systems such that we can now enjoy non-shitty meteor spawning all the time and adds a few basic meteor types for demonstration

**Comment by N3X15** [comment]
Since I don't see any objections

**Pull request merged**
