### PR TITLE
Lowers Roulette Revolver odds

### PR DESCRIPTION
**Pull request by Dacendeth**
This thing is too powerful for how common it is, and it's kind of odd to me that a magical self recharging gun is twice as likely to spawn as a beartrap or handcuffs so I lowered the odds. 

:cl:
 * tweak: Lowered odds of finding roulette revolvers by 80%

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I accidentally meteor'd chemistry one round years ago while trying to use the roulette revolver to break through the windoor, killing me in the process

**Comment by anunknownentity03** [comment]
i had a duel with an xenoarch where we took turns shooting the roulette revolver at each other and by the time when it was his turn he shot out either an extreme yield rocket or an apocalyptic meteor which led to the destruction of the entire research wing on asteroid station.

**Comment by anunknownentity03** [comment]
> This thing is too powerful for how common it is, and it's kind of odd to me that a magical self recharging gun is twice as likely to spawn as a beartrap or handcuffs so I lowered the odds.
> 
> 🆑
> 
> * tweak: Lowered odds of finding roulette revolvers.

you might wanna include a comparison of the old vs new odds in the cl

**Comment by help-maint** [comment]
I don't think the chance is the problem in this one. The problem is the fact that the thing is unusable because it will shoot cluster meteors within a couple minutes of use. If not for the meteors there wouldn't be anything wrong with it.

**Comment by jknpj** [comment]
Remember when all you could get from xenoarch were spoon-shaped forks, reskinned boxes and the job wasn't a just a glorified validhunting tool looter-shooter?

**Comment by ghost** [comment]
roulettes should probably be a large like claws are

**Comment by Dacendeth** [comment]
> 
> 
> roulettes should probably be a large like claws are

I thought about that, but not every cool thing needs to be a large.

**Pull request merged**
