### PR TITLE
Multiple Borers in a Single Body

### PR DESCRIPTION
**Pull request by Shadowmech88**
This PR gives cortical borers the ability to inhabit a mob's chest, right arm, left arm, right leg, and left leg, in addition to their head. Borers have different chemical-production options, genetic modification options, and verb unlock options based on whether they are inhabiting a head, chest, arm, or leg.

A general change is the addition of "channeling" verbs for borers. While channeling, a borer ceases chemical production, is unable to perform any other actions, and its chemical supply is drained constantly. When the borer stops channeling, either by choice or by running out of chemicals, the borer becomes unconscious for a time dependent on how long it spent channeling.

Head borers are mostly unchanged, except they can now produce lipozine, and a bugfix regarding prerequisites means they can now unlock the X-ray vision gene after unlocking telephoto vision.

Chest borers, by default, have a more advanced health analysis verb, similar to the readout of the body scanners in Medbay. It provides less information on the host's overall damage levels, but more information on the damage to specific organs, and whether their host has a virus.
Chest borers can produce the following chems: kelotane, blood, imidazoline, inacusiate, lipozine, ethylredoxrazine, oxycodone, and radium. Chest borers can unlock nutriment, paismoke, arithrazine, capsaicin, frostoil, and a new reagent called "clotting agent" which stops the bleeding process while it's inside the body.
Chest borers can unlock the resist heat and resist cold genes for their host after learning how to produce frost oil and capsaicin, respectively.
Chest borers can unlock channeling verbs that increase their host's resistance to either brute or burn damage for a short time.

Leg borers produce hyperzine. They can unlock the ability to produce synaptizine and hardcores as well.
Leg borers can unlock the run and jump genes for their host.
Leg borers can unlock channeling verbs that allow them to increase their host's base movement speed for a short time, or give their host immunity to slipping for a short time. The slip immunity will penalize the host's speed while it is active, unless one borer in each leg is channeling it at the same time.

Arm borers can produce bicaridine and kelotane. <strike>They can, by default, unlock the ability to produce creatine.</strike>
Arm borers have three specialization trees, each with its own chem unlock, gene unlock, and verb unlocks. Which tree you lock into is dependent on which of the first three verb unlocks the borer chooses.

Offense-spec arm borers can unlock the ability to produce latte, as well as unlock the strong gene for their host. They can unlock a channeling verb to create a bone sword attached to their host's arm and, after that, a channeling verb to create a much heavier but less sharp bone hammer attached to their host's arm.

Defense-spec arm borers can unlock the ability to produce hamserum, as well as unlock the regeneration gene for their host. They can unlock a channeling verb to create a bone shield attached to their host's arm and, after that, a channeling verb to encase their host for a short time in a bone cocoon which, while protecting their host, will also render their host immobile and unable to perform actions.

Utility-spec arm borers can unlock the ability to produce iron, as well as unlock the shock immunity gene for their host. They can unlock a verb to repair the bones in the arm they are inhabiting and, after that, they can unlock the ability to act as a sort of organic hookshot for their host. They gain a modicum of control over the arm they inhabit, allowing the borer to pull items from a distance directly into their host's hand via the hook, or pick up an item near their host. The hookshot ability also grants the borer the ability to drag an unconscious host away from danger while inside the host's body. If the host is holding something in the hand which the borer inhabits, when its hook bumps into something, the item's attack() will be called on the thing that was bumped. For example, a host holding a flash in their right hand will allow a borer in their right arm to fire a hook at a nearby mob and, when the hook hits, use the flash on that mob.

Each limb can only have one borer inside it. A single human can have five active borers, but to be effective the six players that make up the entity will need to act in sync, which could prove something of a feat.

### CODE REVIEW

**Comment by Intigracy** [comment]
tbh I'd rather all this just be added to all borers and keep the 1 per mob limit.

**Comment by clusterfack** [comment]
Absolute mad man

**Comment by Praecordia** [comment]
we /parasyte/ now

**Comment by Shadowmech88** [comment]
@Intigracy 
I restricted certain abilities to certain limbs specifically to require cooperation between multiple different players within a single body in order to increase the body's capabilities.
I think that would be a neat path for borer gameplay to take.

**Comment by Probe1** [comment]
You had me until offensive spec and then you added a bunch of stuff that sounds really cool but doesn't have a damn thing to do with borers, and it's really a stretch to say these little chemical secreting brain pals can pull off.

I'd add that somewhere else in the game honestly.

And I agree borers should be limited.  I'm ok with two but the idea of a guy with 3 or 5 borers in him just spamming chems is meh.

**Comment by Shadowmech88** [comment]
@Probe1
I freely admit that I am altering the original "intent" of what borers are supposed to be.
They are no longer merely slugs that can secrete chemicals.

**Comment by Intigracy** [comment]
I still think that something that's as hard to come by as a borer shouldn't be able to be hogged in multiples by one person.

**Comment by AutismSpider** [comment]
can order borer eggs form cargo for 100$

**Comment by Intigracy** [comment]
And how do you hatch them if you're not a scientist/atmos tech?

**Comment by AutismSpider** [comment]
not smart man are you?

hell Cargo can start borer farm easy on box they can build a RPD and suck plasma out of the burn room south of cargo all they  got do is make a 3x3 size cage of glass/walls and put pipes and vents so they can vent out and shit

**Comment by Imagebard** [comment]
We'r gonna have to buff pAI's again once this is done with.

**Comment by Probe1** [comment]
I thought about it and I really don't like saying this because of all the effort you put in, but no.  It's hijacking something that works perfectly fine and adding in a bunch of stuff that doesn't fit with it at all.  It introduces a bunch of balance concerns and content that is weird and doesn't fit SS13 to begin with.  

I don't want to see it lost but I would rather see it in a different part of the game than borers.

**Comment by CptWad** [comment]
on one hand :+1: because hell yeah more borer features
The other is the multi borer features which I dont think is very great since there are usually 2-3 players who play borer often all week
This is a lot of change for borers so methinks this deserves at least a trial period to see if its going to no be incredibly broken

**Comment by NigglyWiggly** [comment]
The only way I could see this being okay is if you can have borers take control of every part of a corpse and then pilot it around like a fleshy Voltron.
That'd be neat.

**Comment by Imagebard** [comment]
@NigglyWiggly 
Okay but how the fuck would you control that?
If a group of players somehow reached cooperation, how would the VOLTRON work then? Would it  be immune to brute/burn/oxy/tox damage and only kill-able by cutting off body parts, since its a reanimated corpse instead of a living human?

I know its a joke request but I must ask.

**Comment by AutismSpider** [comment]
Way to much team work.

Blood hell people have hard time working as a team in cult and nuke ops.

**Comment by Kitfox88** [comment]
It could be a cool adminbus thing for now, at any rate. Reskin them so they aren't borers and let the bus go /parasyte/ on the station now and then with ghost players or w/e

**Comment by AutismSpider** [comment]
any thing about the armor one that shit is dumb with how awful the player base is.

**Comment by jknpj** [comment]
Make a "type" of borer for each body part, limiting the part they can infest. Maybe they can work like slimes, starting as the regular cordical borer and forcing them to reproduce to give birth to more "adapted" borer-types.

**Comment by Shadowmech88** [comment]
Not that I'm against that approach, but why would that be better than giving each borer/host the freedom to choose what limb to inhabit?

**Comment by jknpj** [comment]
To keep borers from being powergaming devices. Or maybe they can be like aliens, evolving to one "type" of borer and then no changing between parts.

**Comment by PJB3005** [comment]
Please no borer discrimination!

The concept of a guy having 6 borers in them and being literally unstoppable amuses me. Also borers are very rare so I doubt it's an issue.

**Comment by Imagebard** [comment]
With 11 :+1: 's and 9 :-1: 's, this is the best PR yet.

**Comment by PJB3005** [comment]
Make that 12 :+1:

**Comment by Shadowmech88** [comment]
It's certainly a polarizing one.
Hopefully the PR test server will be up soon and people can try out the new stuff for themselves.

**Comment by Intigracy** [comment]
Have any of you even read what this PR actually does?

Arm borers can:

```
Spawn a hammer or sword in their host's hand.
OR
Give infinite regeneration to their host AND have the ability to spawn their host a shield
OR
Fire hookshots from arms. If the host is holding something in that arm's hand, that item is also automatically used at the hookshot's end location.
```

AND

```
Arm borers can produce bicaridine and kelotane. They can, by default, unlock the ability to produce creatine.
```

Chest borers can:

```
Have advanced health analyzers by default
AND
Produce kelotane, blood, imadazoline, inacusiate, lipozine, ethylredoxrazine, oxycodone, radium by default
AND
Produce nutriment, smoke, arithrazine, capsaicin, frostoil, and clotting agent which completely stops bleeding while it's in the body
AND
Give their host heat/cold resist genes
AND
Increase their host's resistance to brute or burn
```

Leg borers can:

```
Produce Hyperzine, synaptizine, and hardcores
AND
Unlock the run and jump genes on their host
AND
Increase their host's movement speed
OR
Give them slip immunity
```

I can't put enough :-1:'s to show how I feel about this.

**Comment by AutismSpider** [comment]
i don't like the weapon stuff and the slip immunity unless the slip immunity slows the host down to hard suit level of speeds they can turn on and off like mag boots

**Comment by Probe1** [comment]
My opinion hasn't changed, I still don't like it one bit and really regret all the good work you put in going the wrong direction with borers.

**Comment by Shadowmech88** [comment]
@AutismSpider 
It does, unless you have a borer in each leg, both channeling that ability at the same time.

**Comment by 9600bauds** [comment]
I'm really conflicted here because you've put a lot of effort into this PR so I don't want to bash on it, but yes I think that this is going 100km/h in the opposite direction of where borers should be

**Comment by AutismSpider** [comment]
Work on the Arm borer all of that is silly as shit if any thing arm borer should be shield and not some thing for healing. 

Healing should be left to chest and head only as for chest the Increase their host's resistance to brute or burn should they can only pick one right?

**Comment by Shadowmech88** [comment]
@AutismSpider 
They can only use one at a time, and can't do anything else while channeling it, but they have the option of both.

By "healing," are you referring to their ability to produce bicaridine and kelotane, or the defensive borers' ability to unlock the regeneration gene?

**Comment by AutismSpider** [comment]
The Gene the chems are fine the creatine is over the top when you mix it with the weapons and on top of how hulk works over all. 

they can keep fighting even when in crit unless the head comes off.Gibed or the hulk/creatine runs out

**Comment by Shadowmech88** [comment]
You have a point there. I added the creatine before making all their other abilities.
I think I might axe it altogether.

**Comment by AutismSpider** [comment]
Lets be real if you want this to work one borer per host on top of that need look over some stuff some  this is just MADNESS.

**Comment by Blithering** [comment]
This stuff sounds cool, but I don't really think it works well as borer abilities. To me it sounds like it would work well as an antag ability, maybe some kind of ling that can amalgamate people they absorb into themselves.

**Comment by Probe1** [comment]
(playable necromorphs baby)

**Comment by Kurfursten** [comment]
You really went a bit overboard on the powers. Also on a more personal level I don't like borers creating effects (hamserum, paismoke). It doesn't feel borer-like to me. Not to mention paismoke is literally for pAIs.

**Comment by Shadowmech88** [comment]
Originally for pAIs, yes. But I didn't see any reason to create a new reagent for the borer upgrade just because paismoke is _for_ pAIs.

**Comment by Kurfursten** [comment]
I'm just saying it feels like including nutriment and smoke are a little in the pAI's area. But that's hardly the biggest complaint, those are just my personal feelings.

Intigracy hit the nail on the head with his summary.

**Comment by Probe1** [comment]
i still feel the same way as I did initially.

what you have here is a ton of cool shit that has a place, but not with borers (or any one thing for that matter)

**Comment by AutismSpider** [comment]
NO nope take that weapon shit out

**Comment by Intigracy** [comment]
Borers are already rare to get without being a scientist
Now it'll be even worse since the scientist took all the borer candidates

**Comment by Kurfursten** [comment]
@Intigracy I didn't even think of that.

> Hey science can I get a borer?

Sorry mate only three hatched and I need five

**Comment by Intigracy** [comment]
I mentioned it earlier just not in as specific wording.

**Comment by Probe1** [comment]
http://ss13.moe/index.php/poll/42

**Comment by PJB3005** [comment]
>No "Yes, but with some improvements"  option.

**Comment by Kurfursten** [comment]
@PJB3005 I hate those options, they're too vague. Two votes for that might mean taking the design in totally different directions.

**Comment by MercuryDoll** [comment]
> being able to create weaponized bones

We Prototype now? Really though, sounds a bit overpowered. I thought they're brainslugs with a built in apothecary. I love some of these features but they all seem to make them really powerful for no reason. If you want to buff borers, give them more chemicals they can unlock and produce (with a limit on how much they can pump into the host) and the ability to play with their hosts genes.

While i love boneblade arms and shit i don't think it should be the ability of a little slug nesting in your ear. Why not make these bone-things mutations? Similar to genetic powers, but permanently active. For example, if you have the boneblade mutation, one of your arms is permanently turned into a weapon and the corresponding hand is unable to hold items.

**Comment by Shadowmech88** [comment]
@MercuryDoll 

> I thought they're brainslugs with a built in apothecary

As I've said before, this PR is a complete _rework_ of borers. They're still parasites, but not specifically _brain_slugs anymore.

> While i love boneblade arms and shit i don't think it should be the ability of a little slug nesting in your ear

A borer can only access that ability if it has burrowed into your arm, not your ear.

**Comment by Probe1** [comment]
The whole bone magic is pretty retarded in borers and I really wish this wouldn't be merged.

Borers are fine.  Many, many other things need this kind of attention.  Most of this code would go great cut and paste elsewhere.

**Comment by Shadowmech88** [comment]
I'm not entirely unwilling to compromise.
But I'll give the server poll some time before I make any decisions.

**Comment by Probe1** [comment]
The server poll looks like its gonna win.  Then people will bitch.  Then I'll bitch at them and say they should have voted.  I won't bitch now cause that'd be outright dickish and unfair for an admin to lobby against a change.  But there will be bitching and I will be disappointed.

**Comment by Imagebard** [comment]
Send help

**Comment by ghost** [comment]
Isn't this just making it a potential option?

You'd have to co-ordinate with multiple people to get multiple borers working in tandem.

Also, does this check for if the limb they are going to infest is robotic or not? Wouldn't make sense for some strange biological baloney to be done to a robotic limb

**Comment by Shadowmech88** [comment]
> does this check for if the limb they are going to infest is robotic or not?

I don't believe it does, good catch. I'll fix that.

**Comment by clusterfack** [comment]
So ya gonna fix it up or what
http://ss13.moe/index.php/poll/42

**Comment by Intigracy** [comment]
rip

**Comment by Shadowmech88** [comment]
Yes, I'm going to fix it up.

**Comment by Hoshi-chan** [comment]
Why would you do this? Borers are already incredibly OP. Like, "keep someone alive and murdering people after repeated near-death injuries" OP. Did the borer wizman round teach people nothing? The one that lasted 2 hours with the wizard just tanking everything thrown at him thanks to his borer, and then jaunting away.

Why don't you redirect some of this stuff towards making changelings more capable of direct combat and non-monkey-succing approaches rather than giving abilities superior to most antags to the average crewmember who orders a bunch of borer crates from cargo?

Expanding the capabilities of borers sounds okay, but having a slew of borers all making you an unstoppable killing machine does not. Also, borer chat should REALLY be visible to ghosts, and borers should be able to name themselves (or receive actual randomized names besides a number) to cut down on confusion amongst multiple borers, regardless of how this proceeds.

**Comment by clusterfack** [comment]
The people voted for it, so we'll try it out and we'll see how it goes. 

If people dislike this new direction in the future we'll cross that bridge when we come to it.

**Comment by Ephx1** [comment]
I want to call you a faggot because this just made borers incredibly OP and incredibly retarded at the same time. Borers should remain in the head, we should not have a fucking party van for an invincible person to walk around as.

IF ANYTHING, THEY NEEDED THEIR CHEMS LIST REDUCED HOLY SHIT
and before you call me a faggot for not voting I haven't been playing recently

**Comment by ScrambledSteak** [comment]
i am all for becoming the slug man.

**Comment by AutismSpider** [comment]
Am i going have to beat dip shit with borers in them to death now? People being smart asses with them in unfunny ways.

**Pull request merged**
