### PR TITLE
Sanity for teeth removal

### LINKED ISSUE #13622: You can remove teeth from a headless body
(WEB REPORT BY: probe1 REMOTE: 172.93.109.202:7777)
See above

### PR DESCRIPTION
**Pull request by ghost**
Should fix #13622

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]
Should probably have teeth be stored on the head organ or whatever but this is a good band aid.

**Comment by gbasood** [comment]
`code/modules/mob/living/carbon/human/human_defense.dm:295:error: head.status: undefined var`

**Comment by ghost** [comment]
oh shit sorry

**Comment by gbasood** [comment]
sorry for what
our daddy taught us to be proud of our runtimes

**Comment by unid15** [comment]
Actually when head is removed from the body, the teeth get transfered to the head organ, so it's a mystery how that bug happened

https://github.com/unusualcrow/vg-coding-fork/blob/18a5329346c1da5c860a4b4655cbc25e93af34a0/code/modules/organs/organ_external.dm#L1245

**Comment by gbasood** [comment]
Bad code tbh
Why are teeth not contained in the head organ to begin with

**Pull request merged**
