### PR TITLE
Gives the ghosts of corpses enthralled by a vampire a notification

### LINKED ISSUE #28168: You can thrall corpses, and it doesn't warn the corpse when they get thralled
>get owned
>vampire thralls corpse
>chat doesn't say this
>no warning or message at all if you already ghosted by then
>re-enter corpse when being revived
>have a thrall symbol
>confusedly check notes

Based on a true story.

### PR DESCRIPTION
**Pull request by ghost**
Closes #28168 
Now ghosts will have a large notification when their dead body is enthralled, so they can avoid confusion upon returning to the living.
image
[qol]

:cl:
 * rscadd: Added a notification for ghosts who have their corpse enthralled by a vampire.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This doesn't say WHICH vampire enthralled them which raises problems if
>they are not watching their body
>they go afk after being killed and come back to this message

**Comment by TGFH** [comment]
Why can vampires thrall corpses at all? Weren't cult corpse conversions removed because everyone considered it bullshit?

**Comment by Dacendeth** [comment]
Who your vampire master is is in your notes isnt it? could just add a "check your notes" to that message.

**Comment by ghost** [comment]
I purposely left it as a general message due to the nature of vampires constantly changing their identity and thus preventing any goofiness with saying they belong to another.  Especially given that a lot could happen before they are revived.  Their hud and notes give them enough info from this point.

**Comment by ghost** [comment]
I added an additional little descriptor in parentheses to the end for how to find who their master's current identity is upon revival.

**Comment by PlausibleDeniability** [comment]
> 
> 
> Why can vampires thrall corpses at all? Weren't cult corpse conversions removed because everyone considered it bullshit?

This, why is this a thing?

**Comment by ghost** [comment]
If a balance issue wants to be made along with a vote, I have no issue with such, but this QoL/fix is completely independent of that discussion and wouldn't be effected by such a change code-wise.  For now, this is how things are and I am honestly just trying to close out as many issues as possible in our backlog here.

**Comment by Kurfursten** [comment]
Harse is right, if you want to disable thralling corpses entirely, you can PR that; it's out of scope here

**Pull request merged**
