### PR TITLE
adds two vocaloid outfits from TG

### PR DESCRIPTION
**Pull request by RFultra**
This PR adds two vocaloid outfits from TG (suit and shoes) and adds them to the autodrobe

### CODE REVIEW

**Comment by Exxion** [comment]
>Emoji-ing on your own post

Disgusting

**Comment by clusterfack** [comment]
Just for that you should ban him again

**Comment by ghost** [comment]
pictures, please

**Comment by Intigracy** [comment]
fyi you can do inline images in github
```
![](http://i.imgur.com/3ds4SdL.png)
```


```
![](http://i.imgur.com/2wJR1UH.png)
```

**Comment by yclatious** [comment]
>waifu adding in waifu dresses

Oh boy I cant wait for a cetain *someone* to go and start raiding the autodrobe *every single fucking shift*.

**Comment by SonixApache** [comment]
Are there images in the OP? I can't tell.

**Comment by RFultra** [comment]
there are now

**Comment by SonixApache** [comment]
make better pictures
64x64 front rear and sideview

**Comment by ghost** [comment]
People are gonna complain about MUH WAIFUUUUS REEE
better at the Len outfit if there is one :^)

**Comment by FudgePucker** [comment]
I endorse this PR :+1:

**Comment by Arthurdentist** [comment]
this PR will cause a binary merge conflict with this one: #14979

(so merge mine first, because its not anime shit)

**Comment by NigglyWiggly** [comment]
Fucking what the fuck man.
I'm a huge faggot that likes animu shit but fucking no way mang

**Comment by SkowronX** [comment]
Awesome more garbage to add to the autotrashcan

**Comment by ghost** [comment]
wait no

**Comment by FudgePucker** [comment]
Why not just put it in a vault instead of the clothing vender?

**Comment by Shadowmech88** [comment]
What about an AI hologram wearing them?

**Comment by FudgePucker** [comment]
I mean having people storm the costume vender round start is cancer, having it as vault loot means that it is rarer and can't as easily be obtained every round.

Or give it to vox traders.

**Comment by RFultra** [comment]
alright
lemme fix it soon

**Comment by SonixApache** [comment]
you may want to 
- remake the PR (close this one)
- don't include the term "TG" in the body or title of the remade PR to ward autism
- don't add them to the autodrobe (as discussed)
- make an actual vault that includes them and some leeks or something at some point

**Comment by RFultra** [comment]
Yeah alright I will start from scratch and wait for shit to calm down

**Pull request closed without merging**
