### PR TITLE
Revert "Fire heat2color"

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Reverts #35127 "Fire heat2color"

## Why it's good

Just don't like it

## How it was tested

TEG and burnt the bar

## Changelog

:cl:
 * rscdel: Removed fire changing colors with heat.

### CODE REVIEW

**Comment by Lumbermancer** [comment]
i like the weird blue fires

**Comment by MercuriusGH** [comment]
it sucks

**Comment by anonymoose-contributor** [comment]
It should stay simply because its a visual indicator of what rooms you should stay away from should you happen to press your face up against the window of a burning down department.

**Comment by CrazyAmphibian** [comment]
i like seeing my burn chambers get hotter via visual feedback that isn't just a number

**Comment by SonixApache** [comment]
### What this does
Reverts "west is on github"
### Why it's good
Just don't like him
### How it was tested
looked at his posts on git
### Changelog

🆑

    rscdel: Removed west from github

**Comment by west3436** [comment]
It's over.

**Pull request closed without merging**
