### PR TITLE
tgui power monitor

### PR DESCRIPTION
**Pull request by DamianX**
Admittedly the chart is somewhat pathetic but I'd take it for now.
Stolen from TG.

~~Marked as draft until I figure out who made this so I can ask them to relicense it.~~

liXlONpscl 2fMXfnTLUS

:cl:
 * tweak: Changed the user interface for the power monitor.

### CODE REVIEW

**Comment by DamianX** [comment]
stylemistake made it and gave me permission to use his interfaces, so we're good.

**Comment by Eneocho** [comment]
Is this one faster? My trashcan always lags the hell out when loading the power monitor screen (once it's properly open it works fine, but the opening lags horribly).

**Comment by DamianX** [comment]
Yeah it should be.

**Comment by Kurfursten** [comment]
How hard would it be to get a third number with supply and draw that indicates unmet demand?

**Comment by DamianX** [comment]
Is that how powernets work? I don't know how to get such value, if so. If it's possible to obtain such value it would be very easy to add it to the UI, though.

**Comment by Kurfursten** [comment]
Each machine and APC contributes to the powernet's `load`, but what displays at the console is the `viewload`. Viewload builds toward load every tick by averaging itself with load (80% weight to itself, 20% to load). `viewload` is what we used to call load on screen, and `load` is what we showed to players as demand. In other words, `viewload` (what we previously called "load") does nothing but make the computer history look smoother, whereas demand is what was actually being consumed each cycle.

But neither of these refers to unmet demand. Each tick, the powernet gets requests from everything connected in it (but mostly APCs). So long as it still has leftover power, that thing charges. Since this order is based surely on what order APCs are in processing_objects(), it is pretty much at the whims of initialization to decide which APCs get charging priority. You could still track this info with minimal changes though. (First suggestion)

Suggestions to improve this interface:
1. In APC.dm at line 1136, it gives the status for not enough power in network to charge. I suggest at this point you get the powernet and sent it unmet demand, namely `lastused_total`. Then in the powernet keep a running total of unmet demand from APCs. This is potentially about three lines of code but gives engineers much more insight into the powernet needs.
2. Have a toggle to include non-APCs on the powernet monitor. This would show draw by other machines (like emitters). Currently the total draw does not match the actual draw because you only see APCs. Unlike suggestion 1, this is asking a lot more of you because you would have to come up with display data for non-APCs that doesn't exist, so it's more intensive.
3. Even better, you could give engineers control over APC charging priority by allowing them to adjust APC order at the monitor. You could either allow them to adjust where the APC falls inside processing_objects or more simply just split into low and high priority queues. Or even remote disable of APC charging so more important ones get to draw (e.g.: disable vault and xenobio so brig and bridge can charge). This is a substantial ask though and firmly out of scope of a UI PR. It's just something that would be really nice.

**Comment by ConfusedCactus** [comment]
The only thing I dislike about TGUI stuff is how jarring of a difference it is compared to all the UIs that aren't.

**Comment by DamianX** [comment]
Kurf and I experimented a bit with showing the "unmet demand" but we don't understand powernet code well enough, it seems.
So I scrapped that but managed to get the chart to resemble something vaguely useful:
image

**Pull request merged**
