### PR TITLE
Nazicurity

### PR DESCRIPTION
**Pull request by ErrorsWindows**
[content]

## What this does
Adds some Nazi-themed equipment to security lockers including the wardrobe

## Why it's good
Bro, have you seen these fucking security players this year? There have probably been more uploads of NT Default and Robocop in the past two months than there were in the preceding two years...
They deserve the Nazi clothes roundstart in security with the way these wanna-be Gestapo nu-sec's act, they might as well start owning up to the reputation by now... in fact I'm thinking this addition might genuinely lead to interesting security roleplay at this rate (security roleplay, can you believe that?)

## Changelog
:cl:
 * rscadd: Adds basic Nazi clothes to the security wardrobe
 * rscadd: Adds Nazi soldier uniform, soldier coat, stalhelm, and Nazi knife to security officer lockers
 * rscadd: Adds Nazi soldier uniform, soldier coat, panzer cap, and Nazi knife to detective locker
 * rscadd: Adds Nazi officer uniform, officer coat, officer hat, and Nazi knife to warden locker
 * rscadd: Adds Nazi hardsuit, officer uniform, officer coat, officer hat, and Nazi knife to head of security locker

### CODE REVIEW

**Comment by Servalfang** [comment]
I'm downthumbing you for upthumbing your own pr

**Comment by wotisjanitor** [comment]
Lol good meme you even quoted me

**Comment by ErrorsWindows** [comment]
Security is a perfect world. Imperfections do not belong in this world. These degenerates... the anarchists in cargo, the backwards feudalistic command, those... scientists... have proven themselves to be deceitful buffoons bent on sabotage... and must be corrected. They have used their last chance and corrective action must be taken now... a powerful message to the rest of the fat pigs, I think, should they be inspired to assault the public safety of the crew once more.

**Comment by bathosbathtime** [comment]
Oh, God. There's a reason the nazivender is nearly admin bus exclusive. Security can, and will, get even worse.

**Comment by twirling-jesters** [comment]
no

**Comment by twirling-jesters** [comment]
also this isn't content

**Comment by pedr69** [comment]
if you can't beat 'em, join 'em.
_puts a 15000 capacity power cell into his stun baton_

**Comment by Kromkar** [comment]
Local manchild crying, mother ignoring him. More at 11

**Comment by ghost** [comment]
dont do that

**Comment by ErrorsWindows** [comment]
> Oh, God. There's a reason the nazivender is nearly admin bus exclusive. Security can, and will, get even worse.

yea, that's kind of what I was going for, it's accelerationism: if nobody wants to police security's behavior, not even the admins, the best option would be to enable it so that it reaches its natural end quicker and we can get this era of redshirts over with

**Comment by bathosbathtime** [comment]
The only thing that will result in is your own removal after the debacle is blammed on you.

**Comment by SECBATON-GRIFFON** [comment]
godwin's law

**Comment by ErrorsWindows** [comment]
> The only thing that will result in is your own removal after the debacle is blammed on you.

What "debacle"? The only debacle is the one going on right now with the redshirt players who are already wanna-be Nazis

In fact, I'm half thinking you're talking about yourself in the third person because I can't even remember the last time you were on outside of an event, I even went back into this month's logs, you only had like, 4 or 5 total connections and only 1 of those was you with more than 10 players and it was that one zombie round two and a half weeks ago on the 12th where you left after getting zombified and I peed in the pool at the end of the round, go waste someone else's few remaining brain cells literal neverplayer

**Pull request closed without merging**
