### PR TITLE
Fixes the sun

### PR DESCRIPTION
**Pull request by Zth--**
Just a mysterious sun runtime

### CODE REVIEW

**Comment by Exxion** [comment]
I'm not sure. This might be hiding the issue rather than fixing it, since we don't know why it's `null` in the first place
I'd rather add some debug output first

**Comment by Zth--** [comment]
Sure

**Comment by nuklearcellphoneg** [comment]
but does it kill vamps

**Comment by BomberBro** [comment]
sun

**Comment by Kurfursten** [comment]
Could you please test this? Just idle on a server for say 15 minutes and see if you get spammed.

I want to be careful because this loops through all the panels and each panel potentially 256 times, every 30 seconds. This has the potential to make the game unobservable for admins if it's a common occurrence. You could also alternatively send the warning message to world.log.

**Comment by Zth--** [comment]
warning() only logs on world.log

**Pull request merged**
