### PR TITLE
Heated plasma and AN/FO bombs

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
extends onto the heated fuel bombs with a similar reaction working on plasma and AN/FO mixes.
works the same as fuel bombs, but with slightly more powerful explosions (welderbomb sized breaches at 100-500 units and nitroglycerin sized ones at above 500, non breaching below 100)
adds ammonium nitrate/fuel oil, a mix of 8 parts ammonia 2 parts hydrogen 2 parts nitrogen 6 parts oxygen and 1 part fuel, which works the exact same with plasma bombs.
TODO: change the heat values (optional, might not)

## Why it's good
expands this system for anyone with access to plasma or a chem dispenser.

## Changelog
:cl:
 * rscadd: Liquid plasma now either catches fire (open container) or explodes (closed container) when exposed to temperatures of 288C
 * rscadd: Adds ammonium nitrate/fuel oil, a mix of 8 parts ammonia 2 parts hydrogen 2 parts nitrogen 6 parts oxygen and 1 part fuel, with similar properties to liquid plasma at the same heat.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Hmm... liquid plasma autoignites but gas plasma doesn't?

Also I think the ANFO ought to be implemented as two seperate reagents that react together to explode under certain conditions, rather than making the mixture itself be a single reagent, which would be more flexible and also more in line with the other reagents.

**Comment by SECBATON-GRIFFON** [comment]
> Hmm... liquid plasma autoignites but gas plasma doesn't?

i wish there was a separate way to make fire act on reagents rather than just heat, but it seems to hard to maintain so this will do. (fuel shouldn't autoignite either but this is how i approximated it)

> Also I think the ANFO ought to be implemented as two seperate reagents that react together to explode under certain conditions, rather than making the mixture itself be a single reagent, which would be more flexible and also more in line with the other reagents.

i was going to use fertilizer as it is in the game as part of the mix but the one in our game is diethylamine, i'm not sure about making an alternate fertilizer recipe just for this PR.

**Comment by Hinaichigo** [comment]
Could just be a reagent clone of diethylamine that also works with the explosion, so it could also be used as fertilizer.

And I'm not sure if I like the idea of plasma autoigniting, especially at such a quotidian temperature.

**Comment by SECBATON-GRIFFON** [comment]
> And I'm not sure if I like the idea of plasma autoigniting, especially at such a quotidian temperature.

make it higher or lower? honestly the main reason i did this is because it happens in cigars already.

**Comment by Hinaichigo** [comment]
I didn't see your response before I replied so I deleted it:
>Could just be a reagent clone of diethylamine that also works with the explosion, so it could also be used as fertilizer.
And I'm not sure if I like the idea of plasma autoigniting, especially at such a quotidian temperature.

If anything higher I was thinking but now that you mention the cigars.. does that still work in a vaccum/inert atmosphere? Gas plasma can't burn without an oxidizer so hmm..

**Comment by Eneocho** [comment]
Not liking the plasma autoignition thing, but the ANFO bomb sound fun.

**Comment by pedr69** [comment]
what if there was bomb that only had a light radius
so people got hurt, walls ungirdered, cables broken but no breach

fusebombs sorta do that currently but it's what? 2 tiles?

**Comment by DorainGrey** [comment]
What is slightly more powerful?
What's the theoretical max dev.

**Comment by SECBATON-GRIFFON** [comment]
> What is slightly more powerful? What's the theoretical max dev.

same as nitroglycerin

**Comment by Eneocho** [comment]
Can't update the guide to chem page with this right now. Will do as soon as I can.

**Pull request merged**
