### PR TITLE
Wizard's Arcane Tamper

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
## What this does
Gives wizards this targeted spell, worth 20 points and with a cooldown of 30-20 seconds (subject to change)
Starts with a range of 1 tile, can be upgraded to full view and then recursively cursing contents (including stuff on floors)
Allows giving items anomalous and sometimes hindering properties, currently implemented ones are: (checked if fully tested working)

 - [x] Doors will teleport the user to another door and open it if crossed when open
 - [x] Closets will suck the user inside, close and weld shut (or just the last two if the first isn't possible)
 - [x] Tables flip YOU, and also throw anyone that tries to climb on backwards
 - [x] Chairs buckle YOU (and cannot be taken off until blessed)
 - [x] Kickable dense, anchored items kick YOU
 - [x] Emags get a small chance to arcane tamper instead, and another to do both
 - [x] IDs will only work for a random access every 30 seconds
 - [x] Welding tools "welderbomb" anything they try to weld, with a less powerful and non-breaching explosion. If used on an item when off it will refill.
 - [x] Welding fuel tanks welderbomb regardless of on/off state of welder
 - [x] Food will cause the user's mouth to go through the item and bite their hand instead, at the same rate they would eat the food.
 - [x] Drinking glasses will [stick to the hand of whoever picked it up, cause pain, and be constantly refilled with their own blood](https://scp-wiki.wikidot.com/scp-198)
 - [x] Insulated gloves become budget insulated gloves in function
 - [x] Electrical toolboxes have their contents deleted and replaced with budget insulated gloves
 - [x] Toolboxes lose all their robusting power
 - [x] Envelopes gain 10 throwforce, and default throw speed and range
 - [x] Paper, comms consoles and requests consoles will distort or markov chain the text of anything written on it
 - [x] Pens will write on paper with the user's own blood supply
 - [x] All dices become unfair mysterious d20s, obviously capped lower if there's less dice sides
 - [x] Fabricators and vending machines will now only dispense rubber ducks or their stock also arcane tampered, with a half chance between each
 - [x] Slot and lotto machines will only dispense money as ducks (cube root for each)
 - [x] Bike horns will act like the syndicate one/honkerblast only on the spell being cast on it (this is supposed to hinder, not turn it into an OP item)
 - [x] Telepads and their computers will teleport bread of various kinds
 - [x] Rubber duckies become (toy) singulos
 - [x] Toy singulos pull people in like a level 1 singulo
 - [x] Shuttle computers will reset the shuttle time from anywhere between 10 seconds or 3 minutes at random, once off
 - [x] Safes reset their dials and tumblers as soon as they align
 - [x] Machine frames build into broken cooking machinery of various types
 - [x] Computer frames build into old useless ones as found on the arrivals shuttle
 - [x] Canisters will always dump their contents into the room and never the attached tank
 - [x] All hackable wires shock anyone trying to interact with them instead of doing anything if the tool is tampered
 - [x] Tampered keys inserted into vehicles act like screwdrivers (brain damage instead of starting them) and vice versa
 - [x] Potted plants and couches distribute the cached item to a random area tile without density, akin to dimensional push
 - [x] Random artifacts get their effects randomized again, with effects on by default
 - [x] Hydroponics trays block harvesting or removal of their plants, and instead sting and inject people with their chems. Their plants are also like this, with not even botany gloves blocking the effect. This carries over with all associated seeds and vines
 - [x] Microwaves spawn burned messes, muck and break if they get tampered or if any inserted food item is tampered
 - [x] Mirrors and pocket mirrors shift the user to a random species, hair and facial hair style
 - [x] Spacecash inserted into ATMs and PDAs will lose a random amount of value inserted (anywhere between 1-100%)
 - [x] Forks and spoon cause the user to eat them, causing brute damage to insides
 - [x] Wires shock you when placed even if disconnected to the grid
 - [x] Cannons have their damage formula reverted so a heavy item is better
 - [x] Supermatter explodes limited to up/down/left/right like a bomberman bomb, doesn't generate power and has its emergency warning thresholds reduced by 90% (but not explosion threshold)
 - [x] Singularities turn into the spinning toy replica if at stage one, otherwise invert to being a white hole if possible
 - [x] AMEs always looks like they're about to explode
 - [x] Conveyors move backwards relative to their animation (animation goes left, stuff gets pushed right)
 - [x] Cleaner grenades produce a random fluorosurfactant of flour, radium, blood, carbon, fuel, oil or lube
 - [x] Wind grenades produce an oxygenated plasmaflood
 - [x] Janicarts/mops dirty the tile instead
 - [x] Meat spikes and gibbers spit out tofu instead of meat, including if just the mob is tampered
 - [x] Pills replace the displayed name with floorpill ones
 - [x] Switchtools randomize the selected module's icons and names
 - [x] Banana peels slip the person that dropped them, does not slip when stepped on
 - [x] Stasis beakers lose their no-react
 - [x] Plasma beakers turn any reaction inside them into the smoke
 - [x] Bluespace beakers only hold 25 units, large ones only 10
 - [x] Supermatter beakers no longer heat
 - [x] Genetic syringes inject a random disability instead of powers
 - [x] Arcades play outbomb cuban pete instead (some other game idea some other time) but rewards a wizarditis culture bottle and wizard garb instead
 - [x] All items act as if held by someone with clumsiness
 - [x] Strange coffee machines [REDACTED] seeds floating in it
 - [x] Old vendotrons [DATA EXPUNGED]

All of these are heavily subject to change and curable by blessing the item with holy water or killing the wizard. Blessing the item also recursively removes arcane tampering from all items inside, so useful on floors too.

## Why it's good
Good varied usage spell for messing with station items, lot of experimentation potential.

## Changelog
:cl:
 * rscadd: Gives wizards a new spell: Arcane Tamper, allowing them to bestow anomalous properties on afflicted items

### CODE REVIEW

**Comment by gurfan** [comment]
How do you remove these properties

**Comment by SECBATON-GRIFFON** [comment]
> How do you remove these properties

splashing holy water on them, any other or better ideas?

**Comment by gurfan** [comment]
Sounds cool

**Comment by Eneocho** [comment]
> > How do you remove these properties
> 
> splashing holy water on them, any other or better ideas?

Killing the wizard neutering all the unholy effects as well would work.

**Comment by BomberBro** [comment]
Killing the wizard should remove it too simply because there's not always going to be a chaplain around for easy access to it and going through cargo is extremely tedious (and also not always an option)

\>Chairs buckle YOU (and cannot be taken off even if blessed, is a bug but will keep in if it's funny enough)
Can you at least unwrench them? Also, does targeting a person do anything?

\>Defibrilators revive dead people as zombies
I'd avoid this one, most players don't know how to revive zombies so it's effectively permadeath and it's way too easy to get accidentally griefed into being unrevivable this way.

**Comment by SECBATON-GRIFFON** [comment]
> >Chairs buckle YOU (and cannot be taken off even if blessed, is a bug but will keep in if it's funny enough) Can you at least unwrench them? Also, does targeting a person do anything?

i'd imagine you can since it just locks the atom, and no not yet, but i have ideas

>Defibrilators revive dead people as zombies
I'd avoid this one, most players don't know how to revive zombies so it's effectively permadeath and it's way too easy to get accidentally griefed into being unrevivable this way.

can remove it, its a machine one covered by emags anyways

**Comment by WindowsErrors** [comment]
> going through cargo is extremely tedious (and also not always an option)

design advice for future developers: cargo does not count as a reliable source of anything on any round

**Comment by SECBATON-GRIFFON** [comment]
> Killing the wizard neutering all the unholy effects as well would work.

added this now

**Comment by pedr69** [comment]
does the undead lich skeleton revive wizard dying and respawning clear all the tampered items?
i would only neuter everything if the wizard gets killed a specific way, guillotine maybe? once he's captured and put on top of a conduction plate?

although a wizard spell that doesn't keep the round gunked for an hour after he's killed might be fine too

**Comment by Hinaichigo** [comment]
I like it more without the reversing after the wizard's killed.
Could also try it at first without that and then if people find it too chaotic or overpowered in game, add the removal-on-death.

**Comment by gurfan** [comment]
Spitballing some ideas

Cursing food replaces the nutriment with lipozine.
Cursing vending machines makes them fall on top of people.
Cursing the destructive analyzer makes it kick people back.
Cursing masks makes them disfigure you.
Cursing any item makes it act like a boomerang when thrown.

**Comment by Blithering** [comment]
Would a faint sparkling effect on tampered objects be too lame?

**Comment by Blithering** [comment]
> > Defibrilators revive dead people as zombies
> > I'd avoid this one, most players don't know how to revive zombies so it's effectively permadeath and it's way too easy to get accidentally griefed into being unrevivable this way.
> 
> can remove it, its a machine one covered by emags anyways

Maybe give them the happy mask shading instead? Less chance of permakilling, but still an "oh fuck what?" moment.

**Comment by Blithering** [comment]
>Cursing masks makes them disfigure you.

Or makes them function like a random mysterious mask?

**Comment by SECBATON-GRIFFON** [comment]
> Would a faint sparkling effect on tampered objects be too lame?

gonna use some purply one for it, there's a reason this is draft as time of writing

**Comment by SECBATON-GRIFFON** [comment]
> I like it more without the reversing after the wizard's killed. Could also try it at first without that and then if people find it too chaotic or overpowered in game, add the removal-on-death.

yeah i'm actually more in favour of this now, since arcane tampered items will indirectly out a wizard as being alive like that

**Comment by Eneocho** [comment]
> > I like it more without the reversing after the wizard's killed. Could also try it at first without that and then if people find it too chaotic or overpowered in game, add the removal-on-death.
> 
> yeah i'm actually more in favour of this now, since arcane tampered items will indirectly out a wizard as being alive like that

What if the wizard's death slowly uncurses the items? Like, one every minute. So you don't really know if the wizard is dead or alive. You just know that this particular chair no longer buckles you in place, clearly someone blessed the curse away.

**Comment by ConfusedCactus** [comment]
I still think they need to go away when the wizard is dead. I don't think wizard should be irreversibly (holy water is very unreliable to obtain) cursing everything on station with an invis cape and having it persist through death.

**Comment by PavelCIA** [comment]
Make the spell robeless

**Comment by SonixApache** [comment]
upgrade to affect all things on a person

**Comment by SECBATON-GRIFFON** [comment]
> upgrade to affect all things on a person

if you get a hold of their backpack it recursively affects everything inside it, same with all storage stuff

**Comment by SECBATON-GRIFFON** [comment]
also do you guys think this should be limited range like buttblasting or not? i made it like that by accident at first then decided it was better not to

**Comment by Eneocho** [comment]
Tier one range limited. Tier 2 range unlimited, Tier 3 can curse backpacks without taking them out.

**Comment by Hinaichigo** [comment]
Having it as a projectile (that could ricochet off of walls and stuff) would be fun. If it hits a person it could tamper with the clothing covering the bodypart it hits.

**Comment by SECBATON-GRIFFON** [comment]
> Tier one range limited. Tier 2 range unlimited, Tier 3 can curse backpacks without taking them out.

i actually like this, implemented

**Comment by Eneocho** [comment]
> > Tier one range limited. Tier 2 range unlimited, Tier 3 can curse backpacks without taking them out.
> 
> i actually like this, implemented

Neat. Make sure it isn't too expensive to go tier 3, just expensive enough.

**Comment by SECBATON-GRIFFON** [comment]
> > > Tier one range limited. Tier 2 range unlimited, Tier 3 can curse backpacks without taking them out.
> > 
> > 
> > i actually like this, implemented
> 
> Neat. Make sure it isn't too expensive to go tier 3, just expensive enough.

it's about 80 in total. reduce?

**Comment by Eneocho** [comment]
>it's about 80 in total. reduce?

Yes. To somewhere around 60, since this spell by its very nature requires you to be mobile and getting only 20 points to get utility spells is kinda iffy. 60 to max the tamper spell, with 40 to go for utility/survival, that's a more balanced cost.

**Comment by SECBATON-GRIFFON** [comment]
> > it's about 80 in total. reduce?
> 
> Yes. To somewhere around 60, since this spell by its very nature requires you to be mobile and getting only 20 points to get utility spells is kinda iffy. 60 to max the tamper spell, with 40 to go for utility/survival, that's a more balanced cost.

done

**Comment by DorainGrey** [comment]
> > > > Tier one range limited. Tier 2 range unlimited, Tier 3 can curse backpacks without taking them out.
> > > 
> > > 
> > > i actually like this, implemented
> > 
> > 
> > Neat. Make sure it isn't too expensive to go tier 3, just expensive enough.
> 
> it's about 80 in total. reduce?

I liked this PR before this however being able to tamper with a backpack without the person even knowing and gunking everything in it, is a bit powergay and pretty sneakycode to do so after the PR has been voted on.

Especially for 60 points, you could just spam blink upgraded + tamper and indefinitely fuck with people. Most rounds aren't going to have a Chaplin to do the blessing to reverse it otherwise.

If an emag has a small chance to tamper, how will you know that it's happened?
Will the toy singlo's gib or just pull people?

**Comment by JonathanSpaceStation** [comment]
Suggestion: mirrors (wall and hand ones) shifting species / appearance when you try and use them

**Comment by Eneocho** [comment]
> Suggestion: mirrors (wall and hand ones) shifting species / appearance when you try and use them

This.

**Comment by SECBATON-GRIFFON** [comment]
> Suggestion: mirrors (wall and hand ones) shifting species / appearance when you try and use them

done

**Comment by Eneocho** [comment]
Does the welderbomb tamper send an appropriate admin log? It would be troublesome if an engineer tries refueling a welder, the tamper makes it explode and the admin only gets a log that the engi welderbombed with no context.

**Comment by Eneocho** [comment]
Some ideas for tampers:
* Cursed forks make you eat the fork, which shreds your insides (gives you 5u diamond dust for the scream+brute).
* Cuffs cuff you instead.
* Wires shock you when placed if disconnected to the grid, they are insulated if you are currently expanding a live wire.
* Cannons have their damage formula reverted so a heavy item is better.
* Siege cannons can only face ONE direction and can't be turned around.
* Cannonballs can teleport people on hit.
* Dispensers have a chance to dispense a random dispenser chemical instead of the pressed button (You press radium and get water instead), the buttons are still in their original place.
* Cryotubes need hot gas/high pressures.
* Microwaves spit out a random dish instead of the prepared one.
* Microwaves inject random chemicals onto food.
* Tampered nuke gives a false "imminent nuclear explosion" warning.
* Supermatter explodes 2x as large but limited to up/down/left/right like a bomberman bomb.
* AME makes MORE SOUNDS.
* Tampering with the singulo rolls a telekinesis check on the wizard (if you succeed you survive/get the lossetta stone, if you fail you gib).
* Flash turn into the amogus flash mob (poll a ghost to go inside?).
* Tampered ghost makes them visible. (only available if the wizard can see ghost somehow).
* Conveyors move backwards relative to their animation (animation goes left, stuff gets pushed right).
* Cleaner grenades produce a random smoke cloud of Flour, Radium, Blood, Carbon, Fuel, Oil or Lube.
* Janicart/mop dirty the tile instead.
* Eggs hatch into random non-hostile mobs. (Imagine hatching a chicken egg and you get a no-AI greyshirt mob).
* Beds flip you so you are resting when standing up and standing up when resting.
* Toilets swirlie the user instead of the victim/Toilets swirly the user.
* Toilet Centrifuges turn the centrifuged chems into a random chemical.
* Meat spikes and gibbers spit out random vegetables instead of meat.
* Tampered chemfridges replace the displayed name of the pills with floorpill ones. Does not change the pill names themselves, only the chemfridge-visible name. ("Ryetalyn (1 unit) pill" becomes "TAKE THIS TO INSTANTLY DIE PILL pill", but once dispensed the name still is "Ryetalyn (1 unit) pill").
* AI holograms become solid.
* Holodeck/holo projector holograms become non-solid and can't interact with stuff directly anymore.
* Library console dispenses random books/only dispenses books from the adult section.
* Bibles don't punish you/reward you for farting on them but only once.
* Knifes stab the user instead.
* Switchtools randomize the selected module's icons and names (You open the tool selection menu, select the "crowbar", the icon is set to the wire cutters but the actual module selected was the fork).
* Tampered banana peels slip the person that throws them, does not slip when stepped on.
* Bike horns do a random sound effect.
* Light bulbs change their colour upon turning off (so when they turn on again the light is now green, for example).
* Stasis beakers lose their no-react and turn any reaction inside them into the smoke (You mix tricord on the thing, you end up with tricord smoke).
* Vending machines vend stuff from other existing vendors instead (buy some danitos, get a stack of plates).
* Tampering 2 doors or airlocks in quick succession links them together such that going through one of them spits you out the other. (This could be its own spell).
* Tampered AI sees in negative or inverse colours.
* Tampered borg gets the cameras hexed and sees everyone as random mobs instead.
* Genetic syringes become nofail.
* Gacha toys turn into simplemobs.
* Pinpointer tracks the clown/random greyshit instead of the disk.
* Pintpointer (the drink) tracks the disk instead.
* Diona pods spit out a randomized monkey simplemob (skull, rock, monkey, diona, flaming skull, farwa, etc).
* IV bags suck blood while on inject mode and draw blood while on suck mode.

**Comment by SECBATON-GRIFFON** [comment]
> Some ideas for tampers:
> 
> * Cursed forks make you eat the fork, which shreds your insides (gives you 5u diamond dust for the scream+brute).

 good idea, no diamond stuff though, eneocho moment

> * Cuffs cuff you instead.

doesnt clumsiness cover this already?

> * Wires shock you when placed if disconnected to the grid, they are insulated if you are currently expanding a live wire.
> * Cannons have their damage formula reverted so a heavy item is better.

i like these

> * Siege cannons can only face ONE direction and can't be turned around.

meh

> * Cannonballs can teleport people on hit.

stupid, save it for making them out of phazon

> * Dispensers have a chance to dispense a random dispenser chemical instead of the pressed button (You press radium and get water instead), the buttons are still in their original place.

not sure about it

> * Cryotubes need hot gas/high pressures.

i like this

> * Microwaves spit out a random dish instead of the prepared one.

already made it do burned messes (even if just ingredients are tampered) and i prefer that

> * Microwaves inject random chemicals onto food.

dunno

> * Tampered nuke gives a false "imminent nuclear explosion" warning.

bit much

> * Supermatter explodes 2x as large but limited to up/down/left/right like a bomberman bomb.

i like this

> * AME makes MORE SOUNDS.

meh, maybe the sprite could change too?

> * Tampering with the singulo rolls a telekinesis check on the wizard (if you succeed you survive/get the lossetta stone, if you fail you gib).

i have an idea for it but not this

> * Flash turn into the amogus flash mob (poll a ghost to go inside?).

**no**

> * Tampered ghost makes them visible. (only available if the wizard can see ghost somehow).

cult can already do this, no

> * Conveyors move backwards relative to their animation (animation goes left, stuff gets pushed right).
> * Cleaner grenades produce a random smoke cloud of Flour, Radium, Blood, Carbon, Fuel, Oil or Lube.
> * Janicart/mop dirty the tile instead.

i like these

> * Eggs hatch into random non-hostile mobs. (Imagine hatching a chicken egg and you get a no-AI greyshirt mob).

ehhhh

> * Beds flip you so you are resting when standing up and standing up when resting.
> * Toilets swirlie the user instead of the victim/Toilets swirly the user.
> * Toilet Centrifuges turn the centrifuged chems into a random chemical.

what is it with you and this

> * Meat spikes and gibbers spit out random vegetables instead of meat.

vegan mode, i like it

> * Tampered chemfridges replace the displayed name of the pills with floorpill ones. Does not change the pill names themselves, only the chemfridge-visible name. ("Ryetalyn (1 unit) pill" becomes "TAKE THIS TO INSTANTLY DIE PILL pill", but once dispensed the name still is "Ryetalyn (1 unit) pill").

they should change the pill too imo

> * AI holograms become solid.

maybe, but i limit myself to no tech stuff

> * Holodeck/holo projector holograms become non-solid and can't interact with stuff directly anymore.

see above

> * Library console dispenses random books/only dispenses books from the adult section.
> * Bibles don't punish you/reward you for farting on them but only once.
> * Knifes stab the user instead.

see: clumsiness

> * Switchtools randomize the selected module's icons and names (You open the tool selection menu, select the "crowbar", the icon is set to the wire cutters but the actual module selected was the fork).

maybe if i get around to it

> * Tampered banana peels slip the person that throws them, does not slip when stepped on.

or dropped in general, sounds good

> * Bike horns do a random sound effect.

nah, already gave it something

> * Light bulbs change their colour upon turning off (so when they turn on again the light is now green, for example).

this might be funny and also a really good visible effect of this, but its also an electronics, save it for emag maybe

> * Stasis beakers lose their no-react and turn any reaction inside them into the smoke (You mix tricord on the thing, you end up with tricord smoke).

this one sounds great

> * Vending machines vend stuff from other existing vendors instead (buy some danitos, get a stack of plates).

maybe as a third thing

> * Tampering 2 doors or airlocks in quick succession links them together such that going through one of them spits you out the other. (This could be its own spell).

i already added this, see 1st thing

> * Tampered AI sees in negative or inverse colours.
> * Tampered borg gets the cameras hexed and sees everyone as random mobs instead.

why

> * Genetic syringes become nofail.

always fail would be better, or always giving disabilities

> * Gacha toys turn into simplemobs.

i thought about this but it seems hard to implement
~~insert WGW reference here~~

> * Pinpointer tracks the clown/random greyshit instead of the disk.

machine

> * Pintpointer (the drink) tracks the disk instead.

i like this

> * Diona pods spit out a randomized monkey simplemob (skull, rock, monkey, diona, flaming skull, farwa, etc).

ill think on this

> * IV bags suck blood while on inject mode and draw blood while on suck mode.

kind of boring

**Comment by Eneocho** [comment]
The clumsy check ones would still fit with arcane tampering: "The cuffs quickly flip and cuff you instead!".
The diamond dust suggestion is cause virology does the same, instead of implementing a whole system for space adaptation or speed it just gives you a dripfeed of chems. 
The gacha mobs could just use the staff of animation's effect with some tweaks to either make them hostile or not.
The door suggestion was for you to manually link 2 doors, such that you could link a door in the hallway with the door in the AI upload, not for the doors to be randomly selected, though that works too.

**Comment by Eneocho** [comment]
You should get the brute damage after eating the spoon too, you're eating a whole ass fucking spoon after all.
Also, you should NOT get the damage after eating the fork/spoon if you have the eat anything gene.

**Comment by Eneocho** [comment]
How are you supposed to bless the supermatter? Just touching would ash the bible/holy water flask.

**Comment by SECBATON-GRIFFON** [comment]
> How are you supposed to bless the supermatter? Just touching would ash the bible/holy water flask.

i dunno, you're the one who suggested i do something with it

**Comment by Eneocho** [comment]
> > How are you supposed to bless the supermatter? Just touching would ash the bible/holy water flask.
> 
> i dunno, you're the one who suggested i do something with it

I guess you can spray holy water with a spray bottle or extinguisher? Though not sure if that ashes too.

**Comment by Kurfursten** [comment]
82 files to review could take some time

**Comment by Eneocho** [comment]
wiki updated

**Comment by pedr69** [comment]
> curable by blessing the item with holy water or killing the wizard

neither of these work

**Pull request merged**
