### PR TITLE
Small box changes

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Nothing to see here
Small changes there and there
:cl:
 * tweak: Box was slightly changed, you might notice a difference.

### CODE REVIEW

**Comment by PaulRitter** [comment]
image

**Comment by aceedex** [comment]
Goofball no goofing

**Comment by ShiftyRail** [comment]
Had it been anyone but Barry I would have upvoted it

**Comment by boy2mantwicethefam** [comment]
Coward

**Comment by tuypo1** [comment]
Does this consider firelocks a security element? If so merge he

Looks like it doesn't, back to the drawing board.

**Comment by DamianX** [comment]
yep, that seems to be what it does.

**Comment by Kharkov72** [comment]
>he actually merged it

F

**Comment by tuypo1** [comment]
Why do I get the feeling this is going to be reverted before I get the chance to log on and expirence its beauty.

**Pull request merged**
