### PR TITLE
In hand sprites for Tank Transfer Valves

### LINKED ISSUE #15198: Tank Transfer Valves have no in-hand sprite
This is kind of an issue. Would be good if we could transform the sprite the TTV is using at the time, since there's a lotta custom sprites for them.
Me holding two TTVs surrounded by more TTVs

#### Server revision
91adeed8a916b660dbf081340607d6e91fa0131f

### PR DESCRIPTION
**Pull request by CodenameB**
Ports /tg/'s sprite for having a TTV in your hands. Should make it a bit more obvious when someone is about to explode the shuttle and what not.

Nothing much else to say really.

closes #15198

image image image image

:cl: 
 * rscadd: Added in hand sprite for Tank Transfer Valves

### CODE REVIEW

**Comment by Exxion** [comment]
Could we have a picture?

**Comment by CodenameB** [comment]
Picture added.

**Comment by SonixApache** [comment]
We have 2^8 possible sprites for TTVs, does this account for all those?
Me holding two TTVs surrounded by more TTVs

**Comment by Exxion** [comment]
who cares lol
The important thing is that you can see it. Doesn't *really* matter if it exactly matches the item appearance. And in our current system, it couldn't.

**Comment by SonixApache** [comment]
I care. It's a neat feature that we have, and it'd be a shame if it wasn't represented all the way through.
I guess it'll be a When I Code It until someone else decides to change the current system.

Good placeholder, I suppose. Would work fox the toxins clock anyway.

**Comment by CodenameB** [comment]
Feel free to make the sprites, I'll stick em in. I don't care to spend the time to make 648 sprites.

**Comment by Exxion** [comment]
Yeah, don't
To do it properly would require rewriting how inhands work
Which is definitely not a bad thing to do, but someone would have to *do* it

**Comment by Shadowmech88** [comment]
We could at least make it so that the `item_state` is null unless the valve has two tanks on it, so that you only see the in-hand if they're carrying what could possibly be a functional bomb.

**Comment by CodenameB** [comment]
I considered that, but then people will just built all of the bomb except the last tank, and store the tank in their backpack.

Then just pull the tank out of their backpack, attach, and bombs away.

**Comment by SonixApache** [comment]
That train of thought is why I made #15201.

**Comment by ghost** [comment]
Codename, they're still, at the bare minimum of a dedicated officer camping them, armed with a bomb and prox relay left in toxins, a voice bomb on themselves, and 4 in a locker. If you go nutballs and make teleports fail without a crystal in the pad, they can hack or thermite into genetics faster than most actual response teams making at best 3 bombs ripping a chasm in the station when it only takes 1 bomb to get people to fuck off. Every second they're scooting along the primary hallways to shove one in the gas mask crate above eng, the top hat locker in hop maint is just gravy.

Edit: In case it came off wrong, we definitely need the in-hands on the TTV. It's been long overdue.

**Comment by Supermichael777** [comment]
it could be done with a generate in-hand proc in attaching things and some overlays if you have 8 valid tank types you need 16 overlays in 4 directions. 64 (small) sprites plus 8 for every tank added in the future.

**Comment by Shadowmech88** [comment]
We actually already have an item-level var for overlays which need to be applied to in-hand sprites.  The chemical pack uses it to show its filling overlay while being held.

TTVs could be made to set up their in-hand that way.

**Comment by Exxion** [comment]
Do we?
Well I'll just go fuck myself then

**Comment by ihadtoregisterforthis** [comment]
Should this be added to the Toxins clock?

**Comment by Exxion** [comment]
Read the changes

**Comment by ihadtoregisterforthis** [comment]
Alright then

**Comment by SonixApache** [comment]
when

**Comment by SonixApache** [comment]
now

**Pull request merged**
