### PR TITLE
Adds roller beds to some other exosuits that were forgotten.

### PR DESCRIPTION
**Pull request by DrSnips**
After the PR closed someone pointed out that a lot of other exosuits like vox and plasmamen didn't get the change as well. I went and tried to find any other medical suits that should have the change as well. I gave all medical suits for aliens the ability to hold roller beds but I'm willing to limit it to paramedic and CMO. I have it this way since not all maps, or any maps likely, come with alien head of staff suits if someone got promoted to the role. Humans can swap to the CMO or paramedic vests but that's not the case for all races.
I will ask again. **If anyone can think of a suit that should be allowed to hold roller beds please bring it up.**

### CODE REVIEW

**Comment by coderbus13** [comment]
ert, or maybe only medical ert

**Comment by Dacendeth** [comment]
Captains armor is the only thing I can think of that you missed now, but i'm not entirely sure it makes sense to add it to that.

**Comment by DrSnips** [comment]
I got medical ERT suits. As for the captain armor, I don't think it should be able to.

**Comment by DrSnips** [comment]
Small fix to roller beds not showing up inhand for all of them since the icon name isn't always "folded" for all children of folded roller beds.

**Pull request merged**
