### PR TITLE
Gives Mass-Spectrometers the ability to take blood samples

### LINKED ISSUE #4246: Give Mass Spectrometers the Ability to Take Blood
I use advanced mass spectrometers frequently, and it's always a minor annoyance to have to get rid of the 10u of blood that's left over in the syringe. Blood samples can only be taken in 15u amounts, and the mass spectrometer can only hold 5u at a time. Which means to clean out your syringe you need to use the mass spec two more times, or inject it back into the patient, or into yourself, or a beaker and splash it on the floor, and it just irks me. I'd much rather mass spectrometers be able to take blood samples by themselves similar to those fancy diabetes monitors that flick the little pin out to take your blood. It removes a step which only serves as an annoyance and not even an obstacle (Who's going to have access to a mass spectrometer that's not also going to have access to a syringe?). You can even make it for advanced mass spectrometers only, that's the only kind anyone ever uses since the research for them isn't much farther than the research for regular mass spectrometers.

### PR DESCRIPTION
**Pull request by 9600bauds**
Tested extensively by trying to take the blood sample of Runtime, a monkey, an alien, a window, and a pair of brown shoes.
Fixes #4246

### CODE REVIEW

**Comment by FudgePucker** [comment]
What was causing the shoes to take constant toxin damage?
TELL ME, WE NEED TO SAVE THEM.

**Comment by 9600bauds** [comment]
Can't save 'em all, Fudge, they're in a better place now.

**Comment by Probe1** [comment]
It's a good, de-clunk-ifying idea.  I've always felt adv mass specs are too user unfriendly and this will help.

**Comment by ComicIronic** [comment]
Does take_blood account for human species with no blood?

**Pull request merged**
