### PR TITLE
posibrain/mmi handcuff fix

### LINKED ISSUE #6628: You can handcuff positronic brains
Well.

I really don't know what else to say.  They're cubes.  You can handcuff them.  There is no corresponding sprite for it and they have no mob inventory for players to open so the cuffs are lost.  Works with and without a player occupying it.

image

### PR DESCRIPTION
**Pull request by coldcola**
fixes #6628

### CODE REVIEW

**Comment by clusterfack** [comment]
Did you test this? I don't think it'll work and might cause a few bugs

**Comment by coldcola** [comment]
yes, didn't notice anything unusual occurring afterwards either.

**Comment by clusterfack** [comment]
Did you test it before to make sure you could reproduce it?

**Comment by gbasood** [comment]
removing return call is not the way to fix this
I know we talked about that already just making sure someone who wasnt in that convo doesnt hit the button

**Comment by coldcola** [comment]
will re-open

**Pull request closed without merging**
