### PR TITLE
Splits the mutate spell into hulk mode and laser eyes

### PR DESCRIPTION
**Pull request by MadmanMartian**
The mutate spell is now split into two different spells

 - The original spell now just gives you hulk, but doesn't require clothing to achieve.
 - The second spell gives you heat vision independent of hulk, but doesn't last quite as long (and doesn't need quite as long to recharge)

I found I could get off about 20 shots within the duration, so still effective.

### CODE REVIEW

**Comment by ghost** [comment]
Been a while but if people support it, the apprentice scroll with mutate needs adjustment yeah?

**Comment by SonixApache** [comment]
Though I lament the loss of one of our most capable x-men, this is probably for the best.
However! you should make them worthwhile instead of making them never-choose options.

how about:
 - hulk gives you hulk as a spell, but also the run fast, strong, etcetera gene blocks
 - laser eyes gives you flash protection and thermal vision (but not x-ray, you'll need a scrying for that one)

\*edit*
Actually how do you even acquire the laser one? Does datums magic automatically add them to the book?
Do you get both the spells from buying the spell?

**Comment by MadmanMartian** [comment]
Okay, I can do those.

As for the *edit*, turns out the spellbook autopopulates spells that have ``user_type = USER_TYPE_WIZARD``

**Comment by Shadowmech88** [comment]
@SonixApache 
I agree that hulk strength alone might not be worth the full spell cost, but laser eyes alone are still an infinite ammo laser weapon with decent damage that can't be taken from you. That's pretty good.

Also, as an alternative to adding more benefits to the hulk spell, its price could be decreased instead. Either way is good.

**Comment by MadmanMartian** [comment]
There, once levelled up, the hulk spell gives you jump and strong too. It currently doesn't require robes to cast.

The heatvision spell gives you immunity to flashbangs off the bat. I hate this spell.

**Comment by Intigracy** [comment]
conflicts

**Pull request closed without merging**
