### PR TITLE
Fire Smoke

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Fires burning solid fuels (wood tables, etc) will now emit smoke which will cause burn and oxygen damage. Crawling prevents the oxygen damage.

## Why it's good

Part 3 of fire rework. Smoke is the main killer in fires and creates a challenge in locating the seat of the fire, offering more of a challenge to those attempting to put it out.

## Changelog

:cl:
 * rscadd: Burning objects now emit smoke.

### CODE REVIEW

**Comment by Eneocho** [comment]
Do you still suffer the damaging effects of the smoke if you're wearing a gas mask?

**Comment by west3436** [comment]
> Do you still suffer the damaging effects of the smoke if you're wearing a gas mask?

As long as you're not on internals, yes

**Comment by PrimeDSS13** [comment]
Does the smoke have an appearance? If yes, please post a photo in the PR.
Additionally, how do you get rid of Smoke? How does it interact with atmos?

**Comment by Eneocho** [comment]
You shouldn't suffer the choking effects of the smoke if you're wearing a gas mask (not to be confused with the air masks in the emergency box) even if you're not on internals. It would fit with the "blocks dangerous gases" effect of the gas mask.

**Comment by boy2mantwicethefam** [comment]
I think fire smoke should look a lot more like ashes rather than the default vision-obscuring smoke effect.

**Comment by west3436** [comment]
> Does the smoke have an appearance? If yes, please post a photo in the PR. Additionally, how do you get rid of Smoke? How does it interact with atmos?

Yeah it's the normal smoke darkened by 50%. Will post a picture next time I'm able to.

**Comment by gurfan** [comment]
A baseline 10% chance to emit smoke seems a little wierd, though I haven't seen how this works in game yet. I feel like the amount of smoke should be proportional to the amount of fuel being burned.

**Comment by west3436** [comment]
> A baseline 10% chance to emit smoke seems a little wierd, though I haven't seen how this works in game yet. I feel like the amount of smoke should be proportional to the amount of fuel being burned.

Agreed that there could be a better method - this is more of a bandaid until Exxion completes his gas reactions PR, after which it will depend on the oxygen/fuel ratio.

**Comment by PrimeDSS13** [comment]
I think this sounds pretty interesting, but I am still curious on how it looks in game. 
Is there any chance we could get a video of the library burning or something similar/common?

**Comment by west3436** [comment]
> I think this sounds pretty interesting, but I am still curious on how it looks in game. Is there any chance we could get a video of the library burning or something similar/common?

Yes I will upload it when I am able to, either tomorrow or Sunday.

**Comment by adacovsk** [comment]
make black smoke toxic, regular smoke just suffocate

**Comment by BomberBro** [comment]
Does the nobreathe gene and being a race with it protect you from the inhalation damage?

**Comment by Hinaichigo** [comment]
It might be nice to make smoke (or soot/ash) into a gas that can be used by the atmos system.

It's not really a gas but it kinda behaves like one. Though it might be weird I guess to use an atmospheric analyzer and have it come up with "10 kPa soot"... so maybe not.

**Comment by west3436** [comment]
> It might be nice to make smoke (or soot/ash) into a gas that can be used by the atmos system.
> 
> It's not really a gas but it kinda behaves like one. Though it might be weird I guess to use an atmospheric analyzer and have it come up with "10 kPa soot"... so maybe not.

Exxion is working on a gas reactions PR which will essentially do this

**Comment by Hinaichigo** [comment]
Oh nice.

**Comment by west3436** [comment]
> Does the nobreathe gene and being a race with it protect you from the inhalation damage?

It inherits the behavior of normal smoke, so it won't affect anyone wearing a mask and internals. If we want to extend this to nobreathe and races that don't breathe, it should be a separate bugfix PR for atomicity's sake to modify smoke as a whole. Happy to do that once this one closes.

**Comment by Kurfursten** [comment]
confl

**Comment by Exxion** [comment]
I was going to point out that gas masks in particular also protect you from smoke even without internals on, but turns out that's not actually implemented. I wonder if it never was in the first place, or if it got removed at some point. Or perhaps it is implemented but somewhere really obscure that I didn't find. They were obviously intended to, given the unusually descriptive clothing flag they possess: `BLOCK_GAS_SMOKE_EFFECT`. All that flag seems to do right now is slightly increase the amount of plasma in the air before you start taking toxin damage from it.

**Comment by Cisrox** [comment]
can we get this next
image
fire color based on temperature of the fire?

**Comment by Exxion** [comment]
That one's almost trivial

**Comment by west3436** [comment]
Now in #33431 due to my lack of git expertise

**Pull request closed without merging**
