### PR TITLE
Reduces explosion throw damage

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Now that the dust has settled and that far more players have (likely) experienced being on the receiving end of shrapnel with 100x throwing force damage hopefully people will reconsider the idea of reducing the damage so that the shrapnel isn't infinitely worse than the explosion itself. Fireballing wizards should die because they cast the spell too close to the target like the fools they are rather than because the target just so happened to be next to a floor tile that got launched into the wizard.

Currently this changes it so that it does 1x damage at light range, 3x damage at heavy range and 5x damage at devastation range, which is the same as the [previous PR](https://github.com/vgstation-coders/vgstation13/pull/33041).

:cl:
 * tweak: Explosion shrapnel will no longer instantly kill players, but instead do damage based on which explosion severity the object has been in.

### CODE REVIEW

**Comment by jwhitak** [comment]
Current shrapnel damage is 500 ``throw_speed`` for all explosions. To find out how much something does, take the ``throwforce`` of an item and multiply it by ``(throw_speed / 5)``. Explosions force the ``throw_speed`` of shrapnel to 500 so quick math shows that objects will deal 100 times the ``throwforce`` of the object ignoring whatever ``throw_speed`` the object has.

This PR sets the throw speed to 1 for light, 3 for heavy, and 5 for dev explosions, ignoring the ``throw_speed`` of the default object. I feel that this effectively makes shrapnel irrelevant unless blasted out by the dev range, and even then, only in high numbers. 15 damage glass shard at best. Explosions SHOULD be dangerous, and shrapnel should involve things like metal pens blasting through people's bones.

Talking with some folks, got some better ideas for this implementation that can still nerf explosion shrapnel but in a less harsh way:
1. Double the damage straight up compared to current PR (double pushback number)
2. Scale the damage harder for dev explosions only, keep light explosions relatively harmless (if light, low ``throw_speed``. If heavy, moderate ``throw_speed``. If dev, behead them with 500). Standing next to a dev explosion and getting hit with a shard SHOULD be lethal, but a light explosion throwing a piece of paper through your skull makes little sense.
3. And my idea (and I'm wondering why I haven't implemented this myself yet): Scale the damage based on the Atom's existing ``throw_speed`` (if it exists), accomplished by checking to see if it exists and if so using something like ``A.throw_speed * pushback`` to give some proper shrapnel coverage while also letting people survive getting hit by flying paper. Otherwise if it doesn't exist, fall back to a safe number like pushback above, or assume ``throw_speed == 5``

**Comment by falcon2346** [comment]
I'm going to agree with jwhitak that this is way too much of a nerf, I'll advocate for doubling or tripling the numbers you have on the throw speed right now. A single piece of glass at 15 throwspeed would be very damaging, but not outright lethal if you got slapped by it down a hallway, but it would still be high enough to shred someone if they get hit by multiple items.

**Comment by Theophrastus1** [comment]
Finally, i will rise from the flames and cast fireball safely once more

**Comment by wotisjanitor** [comment]
Shrapnel damage is funny. One time i kidnapped an engineer and shot a rocket launcher at him and his mesons flew from his head to my skull and i instantly died

**Comment by Eneocho** [comment]
dont care shrapnel damage is fun 👎🏻

**Comment by boy2mantwicethefam** [comment]
Updated the explosion shrapnel speed at the original value of [this PR](https://github.com/vgstation-coders/vgstation13/pull/33041).
1x throw force at light range.
3x throw force at heavy range.
5x throw force at dev range.

**Comment by pedr69** [comment]
heavy/dev bombs breach to space and should absolutely throw shrapnel at gigafuck speeds
i guess you could set the light bombs throw force to like 10 instead of 1 which is just normal throw speed

an assistant throwing a pen at you isn't a big deal but an IED launching a pen at you should hurt you(but not kill you instantly)

**Comment by boy2mantwicethefam** [comment]
The gigafuck speeds are not fun...

**Comment by Eneocho** [comment]
> The gigafuck speeds are not fun...

Seeing the nukie kill himself with a candy wrapper after shooting an RPG is hilarious.

**Comment by NigglyWiggly** [comment]
Shrapnel damage is far funnier than dying in an explosion ever was

**Comment by Kurfursten** [comment]
I think it would be reasonable for a 15 throwforce item thrown from dev range to kill someone. Per the formula given by jwhit, this would mean a plasteel tile for example would only do its throwforce, 15. Following the logic I gave above, I suppose I'd be fine with 7x for dev range, which would be 35 speed.

So perhaps
light = 5
heavy = 20
dev = 35

This is just my opinion though, it's not binding

**Comment by boy2mantwicethefam** [comment]
That still leaves a big discrepancy between explosions and explosion-involved devices such as gun bullets, which are propelled by the detonation of gunpowder inside the bullet casing (which doesn't mean bullets should instantly kill people, I think most people would be opposed to headshots instantly killing people too, after all it's a videogame and that wouldn't be fun), as well as the explosion damage itself which is significantly weaker than the shrapnel (unless it has devastation range, reserved for rarer and bigger bombs). You don't see frag grenade pieces decapitate people despite propelling pieces outwards. From a "does this make sense" standpoint, explosion shrapnel is exaggerated and doesn't make a lot of sense, and from a fun standpoint it's majorly a "I'm glad I saw someone else get owned by this!" thing. No fun!

**Comment by githubuser4141** [comment]
> That still leaves a big discrepancy between explosions and explosion-involved devices such as gun bullets, which are propelled by the detonation of gunpowder inside the bullet casing (which doesn't mean bullets should instantly kill people, I think most people would be opposed to headshots instantly killing people too, after all it's a videogame and that wouldn't be fun), as well as the explosion damage itself which is significantly weaker than the shrapnel (unless it has devastation range, reserved for rarer and bigger bombs). You don't see frag grenade pieces decapitate people despite propelling pieces outwards. From a "does this make sense" standpoint, explosion shrapnel is exaggerated and doesn't make a lot of sense, and from a fun standpoint it's majorly a "I'm glad I saw someone else get owned by this!" thing. No fun!

Well yeah, people are pretty opposed to being instantly killed by a headshot irl too, possibly more so then in video games
Actually there's a lot of people who've decided not to instantly die from headshots irl, is that fail RP? :L

Aren't most of the bombs we're talking about here TTV+ yield? A frag grenade is relatively tiny, TTVs are enough to blow a football field sized city to smithereens.

**Comment by jwhitak** [comment]
I'm liking something that keeps big bombs scary, scales the throw speed based on the item's intended throw speed, and makes little bombs funny but not beheading funny. The following idea would make light explosion sharpenel weak, heavy explosion damage fairly dangerous but not necessarily lethal on its own, and keep the soul of dev explosion lethal paperwork. This is my suggestion, should we make a change:
```
Light = A.throw_speed
Heavy = A.throw_speed * 5
Dev = 500
```

Edit: that said, I'm not sure exactly how much shrapnel can survive the heavy/dev explosions. Testing is a necessity here...

**Comment by Kurfursten** [comment]
> That still leaves a big discrepancy between explosions and explosion-involved devices such as gun bullets, which are propelled by the detonation of gunpowder inside the bullet casing (which doesn't mean bullets should instantly kill people, I think most people would be opposed to headshots instantly killing people too, after all it's a videogame and that wouldn't be fun), as well as the explosion damage itself which is significantly weaker than the shrapnel (unless it has devastation range, reserved for rarer and bigger bombs). You don't see frag grenade pieces decapitate people despite propelling pieces outwards. From a "does this make sense" standpoint, explosion shrapnel is exaggerated and doesn't make a lot of sense, and from a fun standpoint it's majorly a "I'm glad I saw someone else get owned by this!" thing. No fun!

When you think about it, the throwforce on a bullet is low, so it's actually pretty in-line with what we've said. Imagine the dev explosion rate. If a bullet does weak 15 damage, 2 throwforce sounds about right for a bullet thrown by hand. 7x2 = 14. Totally reasonable.

Alternately, if you prefer to think of this in game design perspective rather than realism perspective: bombs are less common than guns and also shrapnel is harder to control in an intentional fashion than clicking someone with your gun. Both of these suggest shrapnel should be more dangerous than bullets from a gameplay perspective.

**Comment by boy2mantwicethefam** [comment]
@githubuser4141 There's plenty of non-TTV explosives affected: IEDs, explosive grenades, nuke op RPGs, fireballs, welding fuel tanks, machinery overloaded by a malfunctioning AI...
@jwhitak I'm not sure I like any possibility of relatively mundane shrapnel doing damage comparable to the original explosion, if not more, especially when it flies out of the explosion's danger zone. But scaling it based on the item's characteristics would be a good start. Not sure whether it would be in this PR (given the votes that users leave and never revisit, ever) or a separate one.
@Kurfursten Well with almost everything being on the floor an explosive shouldn't even effectively throw that far away.
But enough of that, the problem isn't as much the shrapnel itself as much as it is how much damage that shrapnel does, which the PR attempts to address by giving it reasonable damage multipliers rather than a straight 500x. Shrapnel can't be efficiently weaponized because it is very random, and the randomness adds more no-fun to it; players get destroyed by shrapnel just because a single item happened to be on the floor between them and the source of the explosion. Or multiple of them.

**Comment by wotisjanitor** [comment]
image

**Comment by falcon2346** [comment]
And I'd upvote it again.

**Comment by jwhitak** [comment]
I love the idea of shrapnel doing crazy damage equal to the original explosion. It's part of the inherent dangers of an explosion. It also makes for excellent SS13-style storytelling, where bad things can just Happen to you as part of the chaos. You don't need to be in the radius of a grenade to potentially get hurt or even killed from it.

I'm fine with the shrapnel being toned down some. Some baby 0,0,1 boom shouldn't be able to behead people with an ammo casing. But a 3,6,12, where the casing was close to the origin of the blast? That's where I stand.

**Comment by Eneocho** [comment]
First they killed bombdodging with the performance rework (and "proper" explosion direction").
Now they are trying to kill explosion shrapnel.
when will it end

**Comment by jwhitak** [comment]
You can still bomb dodge if you're fast enough. It's just harder because the bombs are faster and explode the correct direction now.

**Comment by Eneocho** [comment]
> You can still bomb dodge if you're fast enough. It's just harder because the bombs are faster and explode the correct direction now.

While technically true, the era of the clown surviving the point blank TTV is now over.

**Comment by Kurfursten** [comment]
Lack of support in its current form

**Pull request closed without merging**
