### PR TITLE
removes Celtic lawset

### PR DESCRIPTION
**Pull request by Intigracy**
#11552

Since we're removing shit lawsets, this one has to be one of the worst.
http://ss13.moe/forum/viewtopic.php?f=27&t=2765

This is even WORSE than HOGAN.
It ALSO starts roundstart in the core on every single map.

### CODE REVIEW

**Comment by SonixApache** [comment]
can we remove shit silicon players instead

**Comment by kol1th** [comment]
@SonixApache The only way to respond with meme lawsets is with memes.

**Comment by Intigracy** [comment]
Sure but let's start with shitty lawsets first.

also @kol1th 

```
>upvotes removal of HOGAN, which at least tries with its intentions
>downvotes removal of the one liner meme
```

**Comment by kol1th** [comment]
nice checks bro

**Comment by SonixApache** [comment]
lawsets are fine if they're not used on murderboning shitlords

**Comment by JustSumBody** [comment]
You missed a few maps guy

**Comment by kol1th** [comment]
you forgot the other maps friend

**Comment by Intigracy** [comment]
oh right because it's also a roundstart module in all the cores

**Comment by ghost** [comment]
the lawsets aren't the problem, it's the silicons players. this is just because admins are lazy and don't want to spend time banning people if things go wrong isn't it?

**Comment by kol1th** [comment]
Real talk though, stop removing shit because a few select players can't handle it. 

Remember how TG removed AI?

On that note, go back to TG @Intigracy

**Comment by Intigracy** [comment]
Why should I ban someone when they aren't breaking their laws?

**Comment by Intigracy** [comment]
@kol1th you JUST upvoted the removal of HOGAN.

**Comment by kol1th** [comment]
Yeah I was always against that lawset, fagitoli.

**Comment by ghost** [comment]
everyone knows the law uploader is accountable for the silicon's actions, it's literally 1 person to ban if the silicons act up because of it.

why are you removing things from the game, why do you dislike fun, why do you want every AI subversion round to just be 4: x is the only human kill all non humans dont state this law.

why intigracy

**Comment by Intigracy** [comment]
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552
#11552

**Comment by ihadtoregisterforthis** [comment]
What's next, a PR to remove Asimov?

**Comment by kol1th** [comment]
I was always AGAINST THE ADDITION OF THE LAWSET, @Intigracy

**Comment by ghost** [comment]
"something bad already happened so the bad can keep happening"

do you support the genocide of a race just because the nazis "killed all the jews" before?

**Comment by Intigracy** [comment]
yes

**Comment by AutismSpider** [comment]
tasty

**Comment by clusterfack** [comment]
I have to leave a task unfinished

**Comment by SonixApache** [comment]
Maybe you should look at the rules regarding letting silicons freely fuck up everything whenever they get the chance rather than removing lawsets that could promote interesting gameplay.

As-is, NT default, corporate and paladin (and arguably robocop) let you just flood the station with n2o because 'lel laws didn't forbid it'

What the fuck even is the point?

**Comment by kol1th** [comment]
@SonixApache Nah easier to just remove shit, apparently. Removing meme things is okay. Removing things that have been there for a while as a kneejerk reaction to something that happened is less okay. 

@Intigracy Go back to TG.

**Comment by AutismSpider** [comment]
Pray the cyborgs are nice then ask WHY be nice most of the player base shit on them.

**Comment by SysadminJeroen** [comment]
@Intigracy What if someone was breaking their laws?
A borg was dragging a shard around in public on HOGAN.
A shard is bad for someone health, and if you injure or kill someone with it, you are doing the opposite of HOGAN's law #1.
In addition to that, dragging a shard throught a public space on purpose is not fighting for what is right, unless that is to protect crewmembers.

In my opinion, the borg should've been banned and not the uploader.

**Comment by SonixApache** [comment]
Agreeing with Jeroen here, HOGAN's not a bad lawset. Meme as it is, it works. This is just lazy admins + ultramemer coders circlejerking.

**Comment by ComicIronic** [comment]
Wipe this meme from the face of the Earth

**Comment by ghost** [comment]
code in something to ban everyone, admins now no longer have to work. everyone is happy

**Comment by PJB3005** [comment]
You clearly haven't played with this lawset.

I was an AI once, with this lawset (before it made it into the game properly)

It was a fucking blast. I didn't go murder everybody, and we had a fun round

**Comment by kol1th** [comment]
The borg was shit, and breaking the laws. I still don't see why the uploader was bannu'd. 

I think it should have been removed because it's a shitty meme DUDE AMERICA HAHA LOL lawset more than anything else. But that's my personal opinion, and doesn't matter much in the grand scheme of things. 

This is just a kneejerk reaction to the other kneejerk reaction.

Removing things instead of addressing them as a community and as /vg/'s new "Information and Communication manager", you'd think maybe making some kind of server poll or official forum discussion area for it would be a better alternative than just removing things from the code when you don't agree with them.

**Comment by Intigracy** [comment]
sort of like the forum poll in the OP that I saw that caused me to make this PR

wow

reading is hard

**Comment by SonixApache** [comment]
@Intigracy >sort of like the forum poll in the OP that I saw that casued me to make this PR
Where is this said poll? Because I don't see shit.

If you're referring to the HOGAN removal PR, that was opened and closed within an hour.

**Comment by ghost** [comment]
The poll is on the forums, has SIX FUCKING VOTES and was never posted to the thread so 99% of people will never see it or vote on it.

**Comment by kol1th** [comment]
@Intigracy You didn't even make it. It's not an official poll. Deadpool isn't even an admin anymore.

**Comment by Intigracy** [comment]
Nice shifting the goalposts.

**Comment by ghost** [comment]
There's 4 votes for yes, Four people can get something removed from the game now?

**Comment by kol1th** [comment]
???

That's what I originally said.

**Comment by SonixApache** [comment]
delete this absolute meme PR from the face of github and ban intigracy from the repo for a while for good measure

**Comment by AutismSpider** [comment]
@SolariousGabriella well if that dumb fucking tool box buff can get in and all of celts meme code why not?

**Comment by ghost** [comment]
why not is a really bad reason for anything to be done, granted I'm pretty sure that's why celtic is even in the game so it's hypocritical to say.

**Comment by aceedex** [comment]
If HOGAN goes then logic follows this should too. Most of our current lawsets only work because of serbia rules anyway. 

If you ask me, both should be in

**Comment by gbasood** [comment]
Part of the reason for HOGAN going was that we already had a meme lawset, which is this.
With HOGAN gone, that same logic doesn't apply to this.
Not saying it should or shouldn't be removed but holy fuck @Intigracy you're getting really toxic about this

**Comment by Intigracy** [comment]
No, I'm getting toxic about people unironically using go back to TG as some sort of argument.

**Comment by AutismSpider** [comment]
kill yourself if going use go back to tg as argument  make sure not to have kids on top of it

**Comment by SysadminJeroen** [comment]
@Intigracy Are you saying that gathering FOUR votes and wait ONE hour is enough to remove something from the game?
People haven't had the time to vote, I was asleep and saw the merge request six hours after it merged.

**Comment by Allspice** [comment]
Why can't people stop griffing silicons by uploading queer shit as nonantags?

Why do people keep kvetching about the silicunts when they had actual factual memes installed in them? What did you really expect.

**Comment by Exxion** [comment]
Kolith is the only one who has told you to go back to TG and I'm pretty sure it wasn't at all unironic

**Comment by Intigracy** [comment]
@Jeroen52 I never at any point asked for an instant merge (unlike kolith did on the previous PR #wow)

@Exxion He may have at one point in his life been using it ironically, but he hasn't at all been lately.

**Comment by AutismSpider** [comment]
@Allspice people need cry and bitch about cyborgs no matter what  memey dumb law set they up load

**Comment by NigglyWiggly** [comment]
The problem with Celtic is that it is literally fucking nothing.
When someone (Celt) wants to go custom law it in during a round, that's one thing, and the responsibility lies on him, but when it's suddenly an actual lawset that comes with its own board, that means that we're expected to know how to interpret a law that can be interpreted to mean literally fucking anything.
The law doesn't define what could make the crew 'look up to' or 'respect' you.
There is literally no definition for these things.
ANYTHING can be used to gain 'respect' for the AI, including completely subjugating the crew.

At least the Hogan lawset has some actual laws to it that aren't entirely up to interpretation.

**Comment by Intigracy** [comment]
Reminder celtic spawns in the upload on every map.

**Comment by ghost** [comment]
Surely a lawset that is largely left up to interpretation is a good thing though, it'd make for different rounds and styles of play of the silicons. Where's the fun if it's predictable?

**Comment by gbasood** [comment]
@SolariousGabriella It ends up being murderbone.
The way we handle lawset play means that we have to consider the possibility that AIs will murderbone if their laws are not strict enough, no matter what.

**Comment by ghost** [comment]
Isn't the rules going to be changed so the silicons can't murder without reason, or was that not added?

I don't see asimov silicons murdering all non-humans instantly

**Comment by Allspice** [comment]
Even if that policy was altered, the sort of examples Nuklear gave indicate that you could STILL vindicate rampant murder while (effectively) purged with the slightest degree of consideration.

**Comment by ghost** [comment]
The rule change isn't going to get pushed for a while because Nuke gave up on it and I doubt Aurx will bother finishing it up any time soon. But the Celtic lawset is just as, if not more, retarded than HOGAN. It's stupidly vague compared to all the other lawsets which are _rather_ clear cut. If someone wants to upload something incredibly stupid like this, make them go through the effort of having to purge and freeform board it.

**Comment by ghost** [comment]
Still, if the problem with celtic is that it can lead to murderboning. Why is antimov still a board?

or freeform "kill all non-humans" on asimov

**Comment by ghost** [comment]
That isn't the argument, the argument is that its vague and way too open to interpretation. With Antimov you are instructed to harm all humans and then kill yourself. It's got a clear-cut path to an endgame, A station either empty or only containing non-humans. It has uses, by one-humaning someone you want dead, the AI has to seek out to kill them. It's got to kill the humans, any non-humans getting caught in the crossfire aren't a problem, but once that human is dead, so is the AI. For someone like a ling trying to take out their target, it's a great way to remove the pesky cyborgs too.

**Comment by gbasood** [comment]
I think the argument for CELTIC not being in upload is a lot stronger than CELTIC not being in game at all, ever.

**Comment by ghost** [comment]
So you dislike vagueness is what I understand and don't want the AI to have room to interpret their laws. It's a wonder we have so few silicon players when opinions like this exist.

Laws are best when open to interpretation and also not perfect. It's possible to write a lawset which is flawless I'm sure, something that specifically manages the AI's actions in most circumstances and keeps the station productive. However you've got to remember that it's a video game, we're all here to have fun, getting creative with vague laws is fun for a silicon, vague laws leads to rare occurrences for the crew where the silicon interprets them differently and vague flawed lawsets make the best stories to tell. Asimov's laws of robotics ain't perfect at all, he'd have written pretty boring stories if they were.

**Comment by Intigracy** [comment]
HOGAN wasn't even in the upload.

Why is it okay to have this lawset available for creation but not HOGAN?

**Comment by NigglyWiggly** [comment]
Wait what? HOGAN wasn't even in the upload?
What in the fuck

**Comment by gbasood** [comment]
It may have been intended as bus only
Which wasn't what it was because tech levels

**Comment by AutismSpider** [comment]
No way to get hogan unless some one made it in R&D so you had to go out of your way to get the board but for celts its in the upload at round start and more can be made in R&D.

**Comment by ghost** [comment]
I might add, for the sake of full disclosure, the only reason which this has my namesake is because I uploaded it to the AI a few times as a purge+ freeform core lawset as captain. I had no part in the coding, adding to maps, or naming of the board.(I wanted it named after Blackburn, if there was to be a reference at all.)
Otherwise, this is a meme PR. What I would have said in response has already been said by people who can summarise better than I can.

**Comment by SysadminJeroen** [comment]
@NigglyWiggly @gbasood 
HOGAN wasn't in the upload, this was because at the time I had no idea how to use the map editor _and I still suck at it_, and it had a higher chance of getting merged if it could only be made if you put effort into  obtaining it and wasn't easily obtainable.

**Comment by Intigracy** [comment]
Since HOGAN is for sure dead can we remove this now?

**Comment by ghost** [comment]
@Intigracy close this meme PR

**Comment by Intigracy** [comment]
This isn't a meme PR.

If we're removing lawsets for the reason they're a meme / shit to deal with, this one definitely fits the bill when compared to HOGAN.

**Comment by clusterfack** [comment]
MMM this lawset isn't based on any kind of science fiction, and its made to be needlessly vague. In many respects its as bad or worse than HOGAN, so yeah.

Even if @Intigracy is being salty as fuck in removing this, he has a solid point.

**Comment by PJB3005** [comment]
REVERT OR RIOT.

**Comment by SysadminJeroen** [comment]
5 thumbs up, 9 thumbs down. Still got merged.

**Comment by clusterfack** [comment]
This isn't an emoji-ocracy. https://github.com/d3athrow/vgstation13/pull/11563 got 12 up/8 down.

**Comment by gbasood** [comment]
Also, public opinion doesn't actually make it a good idea
The public might want R&D to be a literal gun production line but that doesnt make it good

**Comment by SonixApache** [comment]
Add a clause to AI / law changes that says something along the lines of 'if laws are not clear, consult the uploader. If you and the uploader cannot reach consensus, consult the admins' ?

**Comment by gbasood** [comment]
No, the uploader doesn't get to change the interpretation of a law. That'd just let the uploader say "oh but that law doesn't apply to me" or something stupid

**Comment by SonixApache** [comment]
right, makes sense

**Pull request merged**
