### PR TITLE
Butchering radial menu rework

### PR DESCRIPTION
**Pull request by ghost**
[qol][UI]
animated
:cl:
 * tweak: Butchering now brings up a much nicer radial menu.
 * rscadd: Humans and monkeys can now be alt clicked to butcher when dead.

### CODE REVIEW

**Comment by Eneocho** [comment]
You telling me I can no longer butcher 5 zombies simultaneously?

**Comment by GreatBigFailure** [comment]
Why just humans and monkeys? Do any mobs have some alt-click interaction when dead? Even then you could make it based on intent and/or if you have something you can butcher with in your hand. This is a good addition and I want it universal. Butchering as it is is a pain.

**Comment by ghost** [comment]
> Why just humans and monkeys? Do any mobs have some alt-click interaction when dead? Even then you could make it based on intent and/or if you have something you can butcher with in your hand. This is a good addition and I want it universal. Butchering as it is is a pain.

Because dead simple animals (ie everything else) already automatically bring up the butcher menu when you click on them with a sharp object on help intent.

**Comment by GreatBigFailure** [comment]
They do what now

**Pull request merged**
