### PR TITLE
fixes erroneous bug where people who don't play the game get to make changes to it

### PR DESCRIPTION
**Pull request by ghost**
yes, I don't play the game either

but I don't want to make changes to it, I'm just here to shitpost :^)

### CODE REVIEW

**Comment by ghost** [comment]
I expect this to be speedmerged

**Comment by aceedex** [comment]
🖒
Can't emojicracy on mobile, imagine that

**Comment by MadmanMartian** [comment]
While you're here, how the fuck does hypothermia work so I can fix martians?

**Comment by ShiftyRail** [comment]
>When your PR is so ill-advised it awakens the dead

**Comment by ghost** [comment]
@MadmanMartian who the fuck are you
hit me up on discord DrCelt#0944

**Comment by clusterfack** [comment]
Fix planes first

**Comment by ghost** [comment]
Instructions unclear, fell unconscious after 20 seconds in the cold while grepping merge rights through a backdoor. 0/5, ordered a refund but have received no reply.

**Comment by ghost** [comment]
@clusterfack fixed

**Comment by ghost** [comment]
@SarahJohnson489 no refunds

**Comment by ghost** [comment]
Fug.

**Comment by ghost** [comment]
@ShiftyRail people STILL message me every time coders fuck up as if it is my problem or ever was. tbh it'd be better to stay dead

**Comment by Cisrox** [comment]
hell yeah

**Pull request closed without merging**
