### PR TITLE
Cyborgs action buttons

### PR DESCRIPTION
**Pull request by jknpj**
https://webmshare.com/3w35r

Adds action buttons for cyborg's selected modules, such as flashlight and jetpack, fixes jetpacks not working due no action buttons and also fixes an oversight with stabilization toogle not working for cyborgs. The webm still have the the set internals button but i removed it from cyborgs by creating a child jetpack without the button.

:cl:
 * rscadd: Adds cyborg action buttons
 * bugfix: Fixes cyborg jetpack not working
 * tweak: You can now toogle jetpack stabilization on and off

### CODE REVIEW

**Comment by SonixApache** [comment]
~~~hey can you make it so combat borg shield modules work with action buttons (like the jetpack) kthnx~~~

>You have to have the jetpack active to use it

borgs were a mistake

**Comment by jknpj** [comment]
You don't need to have the jetpack as your active module, just as one of your 3 selected modules.

**Comment by FudgePucker** [comment]
This would help out MoMMIs as well, even more so because they get only one slot for equipment,  so you can have out your flashlight if you weren't planning on doing anything else. First thing I do as MoMMI is get a hardhat for the flashlight on it.

**Comment by jknpj** [comment]
Mommis already have action buttons

**Comment by clusterfack** [comment]
Why didn't you have it call equipped instead of spaghetti-ing

**Pull request merged**
