### PR TITLE
Replaces sorting junctions with subtypes

### PR DESCRIPTION
**Pull request by unid15**
Won't do taxi because my pet script can't fix it (its junctions use a different variable)

deff changes: http://puu.sh/lp5m5/b5ac9ae513.txt
meta changes: http://puu.sh/lp5qX/c9099c2bdb.txt
box changes: http://puu.sh/lp5nW/d60c71f001.txt

### CODE REVIEW

**Comment by Kurfursten** [comment]
Sort_tag was actually preferable because it was more legible than having to look up which each sorttype value is (e.g.: I'm probably the only one who knows that sorttype 2 is Cargo off the top of their head).

@PJB3005

**Comment by PJB3005** [comment]
I also made `sort_tag` because `sortType` was less modular.

**Comment by Probe1** [comment]
@unid15 @N3X15 Is there any holdup other than conflicts on this PR?  There are map fixes that need addressed.

**Comment by PJB3005** [comment]
IMO we need a subtype for the mirrored sorting junctions too.

**Comment by Kurfursten** [comment]
@unid15 @N3X15 Does this have map priority? I want to change the path for wrapping paper and that will involve map file editing.

**Comment by unid15** [comment]
Conflicts fixed

**Comment by Kurfursten** [comment]
@N3X15 I would appreciate a speedy decision on this one so that I can push out my wrapping paper refactor. It kills a lot of bad oldcode.

**Comment by Kurfursten** [comment]
@N3X15 @PJB3005 @clusterfack What's the holdup?

**Comment by PJB3005** [comment]
Hey @Kurfursten we all know I'm just tag man.

**Comment by Probe1** [comment]
goddamn

fine
i'll test it.

**Pull request merged**
