### PR TITLE
Roidstation Spiders Fix

### PR DESCRIPTION
**Pull request by GeneralVeers25**
Title.

As requested.

[roid]

:cl:
 * rscdel: Hopefully ends the Great Roid Spider Migrations by locking up the spiders on the Derelict Shuttle.

### CODE REVIEW

**Comment by Kurfursten** [comment]
The derelict ones are really a problem on all maps because of spider door usage

The engineering ones aren't so much of a big deal because you have to more or less opt into fighting them

**Comment by GeneralVeers25** [comment]
By all means, if the coders want to fix the mess they made with spider code, then I'll close this PR. 

Or would you rather I just take them out of the Derelict Checkpoint and leave the ones in Engineering? The Shuttle is already bolted down, so they shouldn't (tm) be able to escape from there.

**Comment by aceedex** [comment]
Let the crew sort em out

**Comment by Kurfursten** [comment]
Is it possible the derelict spiders are sneaking out through the cockpit?

**Comment by GeneralVeers25** [comment]
This is proving surprisingly unpopular, given how often I am yelled at for this.

I've put the Engineering spiders back. And I've closed the Bridge Blast Doors on the shuttle, so the spiders should be completely contained.

**Comment by SonixApache** [comment]
THIS IS NOT THE PROPER FIX TO THE SPIDER MIGRATION SEASON ISSUE

**Comment by SGuivenne** [comment]
> This is proving surprisingly unpopular, given how often I am yelled at for this.
> 
> I've put the Engineering spiders back. And I've closed the Bridge Blast Doors on the shuttle, so the spiders should be completely contained.

Youre mixing up the issue.  The engineering spiders are virtually never the spiders that cause problems, and when they do its generally autism.  The biggest problem with them, if anything, is them getting roasted by the magmaws through the wall.

**Comment by GeneralVeers25** [comment]
Okay, so I removed the Spiders in Derelict Arrivals and bolted the Arrivals shuttle. Think that will fix it?

**Comment by Kurfursten** [comment]
Bolting the arrivals shuttle to prevent escape is a start but could we perhaps add some spiders to it so all latejoins instantly get killed too?

**Comment by GeneralVeers25** [comment]
Erm, not the Arrivals shuttle. The Abandoned shuttle. My mistake.

**Comment by SonixApache** [comment]
no, what will fix it is making spiders not think opening doors is a valid reason to roam

**Comment by jknpj** [comment]
Ok so maybe spiders will get fixed one day, but that day isn't today.

**Pull request merged**
