### PR TITLE
buffs skeleton

### PR DESCRIPTION
**Pull request by ghost**
buffs skeleton

### CODE REVIEW

**Comment by TheFriggenSawbones** [comment]
BAN CELT FROM GITHUB HE CAN ONLY CODE MISTAKES

**Comment by Intigracy** [comment]
:+1:

**Comment by chatsonf** [comment]
I sense a 100+ comment discussion soon.
:eggplant:

**Comment by Kurfursten** [comment]
The number went up therefore it must be a buff.

**Comment by Intigracy** [comment]
Glad someone gets it.

**Comment by kol1th** [comment]
Good change.

**Comment by Megamaw** [comment]
Five times brute damage

whew

**Comment by ghost** [comment]
@gbasood this isn't a meme pr please remove honk I unironically believe this is a good change

**Comment by ScrambledSteak** [comment]
> hit skeleton once with a toolbox
> instacrit

ack

**Comment by 9600bauds** [comment]
> 12 \* 5 = beeg numberz

checks out

**Comment by AutismSpider** [comment]
cant you make it three or some thing??

**Comment by AI-Is-Rogue** [comment]
DRCELT IS THE HERO WE NEED :+1: x :100:

**Comment by Wizbing** [comment]
do it

**Comment by d3athrow** [comment]
cracked

**Comment by clusterfack** [comment]
A deals a deal celt :^)

**Comment by chatsonf** [comment]
> it actually got merged

Guys it stops being a joke once people actually act on it seriously
The joke's being ruined now, you are being as bad as sawbones and that's not a compliment

**Comment by ghost** [comment]
I unironically made this PR. Skeletons need to be put in their place

**Comment by chatsonf** [comment]
This is a hate crime
This is worse than the telepathy change you made by a hundredfold

**Comment by chatsonf** [comment]
I don't even play skeletons and I am disgusted by this change, like this is even worse than cluster's suggested toolbox buff

**Comment by ghost** [comment]
@Furbeh the telepathy change was a necessary evil.

**Comment by chatsonf** [comment]
This is actually worse than dylan's "inflict cancer" pr

**Comment by chatsonf** [comment]
This is worse than the 1 TC 100k credit PR that you supported

**Comment by chatsonf** [comment]
I won't go as far as to say it is worse than your hypothermia pr, but it is definitely close

**Comment by chatsonf** [comment]
This is as bad as the suggested plasmamen balance PR

**Comment by chatsonf** [comment]
Hell, this is almost as bad as the SaMMI PR

**Comment by chatsonf** [comment]
I am running out of PRs to compare this to but I hope you are getting the point that this is worse than a mistake

**Comment by chatsonf** [comment]
Oh how could I forget, this is as bad as the 500 MB runtimes caused by goonlights

**Comment by ghost** [comment]
> Throw whiskey bottle at skeleton
> He explodes

**Comment by chatsonf** [comment]
This will be archived as "a meme gone too far"

**Comment by ghost** [comment]
> Skeleton accidentally hits himself with a tile while reflooring
> He explodes

**Comment by Kurfursten** [comment]
The only meme gone too far is multiborers and that's still in game

**Comment by NigglyWiggly** [comment]
Celt are you a literal retard
The 2x brute is already a huge difference.
This makes them fucking impossible to play as

**Comment by Intigracy** [comment]
Did you hear about the skeleton that got in a fight?

He was destroyed.

**Comment by Kurfursten** [comment]
I saw a skeleton explode from using the suicide verb (because it dealt 1000 brute with the modifier), which actually made it all worthwhile.

**Comment by Intigracy** [comment]
Did you hear about the skeleton who suicided?

He was destroyed.

**Comment by kol1th** [comment]
@Intigracy What did he mean by this?

**Comment by Intigracy** [comment]
This is a great change.

**Pull request merged**
