### PR TITLE
Increased pinpointer update frequency 4x

### LINKED ISSUE #11735: Pinpointer disk-tracking is slow.
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 92b1e8a9020617483eb80518906782c1636721a0 
> 
> General description of the issue
> Title
> 
> What you expected to happen
> Pinpointer to snap to the disk's location inside of half-second or so
> 
> What actually happened
> it takes a good two seconds for the pin pointer to point to the disk pin direction thing.
> 
> Steps to reproduce if possible
> Take pinpointer, try tracking the disk.

### PR DESCRIPTION
**Pull request by DamianX**
Fixes #11735

https://webmshare.com/play/0BqLg

:cl:
 * tweak: All pinpointers now update four times more frequently than before.

### CODE REVIEW

**Comment by ghost** [comment]
Wouldn't it be way more cost efficient for the disk to tell the pinpointers when it moves rather than the pinpointer to check periodically when the disk moves?

**Comment by DamianX** [comment]
dunno

**Comment by ghost** [comment]
Pinpointers can track more than one thing can't they?

**Comment by Probe1** [comment]
Malf AI and disk as far as I know.  Of course there's more than one kind of pinpointer.

**Comment by Aurx** [comment]
The overhead of having to check "Am I pinpointed?" every time anything anywhere moves would surely overshadow any performance gains made by updating the pinpointer less frequently.

**Comment by ghost** [comment]
There's an advanced pinpointer that can track a shit ton of stuff but it's a pile of buggy hot garbage.
Also the alden-saraspova scanner tracks the nearest large artifact.

**Comment by Probe1** [comment]
Ok why not

**Pull request merged**
