### PR TITLE
.380AUTO Security pistols

### PR DESCRIPTION
**Pull request by SonixApache**
Replaces the .45 NT USP with a .380AUTO NT Glock. The change is mostly cosmetic.
Some people complained about how a .45 pistol did shit-for-all damage, so the obvious answer was to make it a 9mm pistol and make the actual .45 do a bunch more damage.
glocks
fancyglocks

The NT USP is still in the code, just not the security pistol anymore.
Cargo packs and map spawns were updated for the new ammo.
Ammo vouchers were updated.
~~The fancy variant of the pistol has been removed.~~
Intigracy provided sprites for the fancy variant.

Buffs the damage of the lethal pistol ammo up from *13* to **15**.
Buffs the magazine capacity from *8* to **10**.
NT USP *(and other .45 pistol)* lethal rounds now do **35** damage.
NT USP *(and other .45 pistol)* rounds are buffed across the board.

Tested

🆑 
 - imageadd: The .380AUTO NT Glock has replaced the  .45 NT USP as standard service pistol
 - tweak: The security pistol now has 2 more rounds per mag, and does slightly more damage
 - bugfix: The NT USP now drops casings when firing

### CODE REVIEW

**Comment by SonixApache** [comment]
I just found out the sprites are 35x32 for some weird reason, I'll have to fix that.

**Comment by SonixApache** [comment]
image
Suppressor's somewhat hard to notice, but it seems aight.

**Comment by JustSumBody** [comment]
powercreep

**Comment by Diavill** [comment]
THREE FREE DAMAGE

**Comment by SonixApache** [comment]
oh wait shit it's 13 right now so that's only 2 free damage

i turned it down from 15 to 13 a while ago in #13991, now's a good time to reverse it

**Comment by Riekland** [comment]
Those are the most hideous fucking things I've ever seen in my life
Why would you ever think that it would be okay to replace the nice, pretty sprites we have with that actual shite
Really those are fucking horrible kill yourself or remove the sprite change

**Comment by SonixApache** [comment]
You should see the guns we were checking out on the other codebases, you'd be surprised. Noted, however.
I think they look a little off as well, but I'm not sure what it is. Too big / 'detailed', maybe?
Here's a buncha guns for comparison
image

**Comment by Riekland** [comment]
first off they're xbox hueg
the suppressors are what four pixels long
the shading is nonexistant and it looks like it's out of some flash game
and the worst part is there's actual no reason to replace our current sprites like what the fuck
why are you doing this

**Comment by SonixApache** [comment]
Imma do another go on the sprites, both guns and magazines.
The reason for it is that they were .45 pistols but shit-for-all to hurt people.
So I figured lowering the caliber would be a good move. Different caliber, different gun, different sprite.

**Comment by Riekland** [comment]
blank_897402_5422949
st-stoppan powah
Very little of the damage in the game is consistent but I'm all for moving towards a more realistic damage spread

**Comment by Riekland** [comment]
what in the goddamn
half those guns look blurry as fuck did you do something to your byond
anyway yeah there's a lot of inconsistency in sizing and detail but GENERALLY there's more shading and shit than in your sprites
also holes in the magazine to help show the amount of ammo left at a glance is the shit

**Comment by SonixApache** [comment]
image
image
How's this look?

**Comment by Riekland** [comment]
it looks like our current usp's but worse
really I don't think you're going to get it looking better la

**Comment by SonixApache** [comment]
image
I think this looks better than the originals.

**Comment by Riekland** [comment]
The proportions are off
The front end should be a little bit longer
The magazines being like that is bad, the base should be straight no matter how angled the rest gets
I just think that the usp looks nicer in the end
glocks are kind of ugly anyway it takes a long barrel to make them paletable

**Comment by SonixApache** [comment]
Yeah, sticking with this. Seems good.
Found an issue too; neither this gun nor the USPs drop casings when firing.
image

**Comment by Exxion** [comment]
And yet revolvers do
Someday I want to completely restructure gun code

**Comment by SonixApache** [comment]
It's the EMPTYCASINGS flag. Don't think it'd be too hard to unfuck how revolvers handle casing ejection.
Still need to fix the ammo interchangeability backend thing as well.
And we gotta add sounds for all the interactions too.

**Comment by SonixApache** [comment]
Here's some gun sprites from other codebases, for your viewing pleasure.
image
Well, and Blithering's USP is in there. I really like the machine pistol variant of the Mk58. Y'know, the fifth one in the first row. Glad we have that laying around unused in our codebase.

**Comment by PromethTK11** [comment]
That laser rifle and laser pistol sprites are really good actually
About the sprite, the trigger-guard isn't too square-ish? looks a bit odd

**Comment by SonixApache** [comment]
I suppose a half pixel at the front wouldn't be bad, but I think this is as good as it gets. Here's the ref.
img_3549

**Comment by Riekland** [comment]
I've come to the realization that I'm retarded
The sprites look a lot better than the current black one although I kind of prefer the white slide version more than these glocks
I really would like it if they had longer barrels but they're actually pretty good now

**Comment by SonixApache** [comment]
If I didn't have to pipe through eight variants I'd make a titanium match slide version. Maybe a later addition, or once I figure out how overlays work.

**Comment by Blithering** [comment]
the machine pistol would make a neat addition for revsquad equipment, kinda fits the theme well

**Comment by IzayaChan** [comment]
Why not just get a picture of an actual gunand pixelize the shit out of it?

**Comment by Intigracy** [comment]
whitepower

https://cdn.discordapp.com/attachments/239836068491296788/324382706437849088/whitepower.dmi

**Comment by Riekland** [comment]
woah mama that's my jam
personally I'd prefer a more tan slide but it's looking good

**Comment by SonixApache** [comment]
~~~okay, that's... not good~~~
crisis averted

**Comment by ghost** [comment]
o no

**Comment by SonixApache** [comment]
nnnoooooooooooooooooooo

**Comment by SonixApache** [comment]
okay i got it

**Comment by Intigracy** [comment]
If you want the other sprite to be something other than a resized picture I can do that too

**Comment by SonixApache** [comment]
Not sure what you mean. If you want to re-do the glocks be my guest.

**Comment by Intigracy** [comment]
The other ones in that dmi?

**Comment by Intigracy** [comment]
Coulda swore I saw one somewhere that's just a resized gun

**Comment by SonixApache** [comment]
That's the old sprites I made, those evolved into the current ones. They're in the second comment.
All is well for now.

**Comment by Cisrox** [comment]
M E R G E

**Comment by Blithering** [comment]
Do you think it would be a good idea to move the USPs to the ERT equipment area? That way they have a ballistic option that's a midpoint between the standard sec glocks and the deathsquad matebas

**Comment by SonixApache** [comment]
Sounds like a plan. (For a next PR.)

**Comment by SonixApache** [comment]
@Intigracy when

**Comment by Intigracy** [comment]
Never

**Comment by SonixApache** [comment]
man hell sure is cold this time of year

**Pull request merged**
