### PR TITLE
Removing Random Lotto

### PR DESCRIPTION
**Pull request by adacovsk**
There's a random event called "money_lotto" which gives a random amount of credits to a random account, including department accounts. We now have two well-developed RNG systems and luck for loadsa money/dosh. Random lotto isn't influenced by luck, isn't fun, doesn't do anything besides make a big number, and decreases odds of fun events.

Edit: you're lucky to win this event once in 5 years

## What this does
- Removes random lotto

## Why it's good
- Decreases compile time and increases chances for a "fun" random event

:cl:
 * rscdel: Removes random lotto. Event enjoyers rejoice!

### CODE REVIEW

**Comment by angryturnip** [comment]
Let's go for a fourth

**Comment by TurboGay** [comment]
_not fun_

I dunno, it's pretty enjoyable to siphon a lottery winner's funds and watch them go apeshit searching for their winnings for the rest of the round.

voxcredits

**Comment by Eneocho** [comment]
> 
> voxcredits

Is that an actual thing that happens to traders?

**Comment by adacovsk** [comment]
> how would one go about coding a space pod full of cash hitting the lottery winner instead of just a bank transfer noone even knows the recipient to?

this seems like a very bad idea for an event

**Comment by Eneocho** [comment]
Bluespace briefcase full of cash. An unknown individual was sending money via bluespace teleportation but it malfunctioned and it hit [WINNER] on the head for 5s stun and 10 brute damage. Once they get up they get anywhere from 20K to 400K credits.

**Comment by d3athrow** [comment]
lol

**Comment by bathosbathtime** [comment]
As you have bomber blocked, and he was against the previous PR that did this exactly this for more reasons than just the title and presentation, should we assume one extra thumbs down than visible for the emojiocracy? Or should we wait for him to contact a third party to relay his feelings on the matter? I would ask @BomberBro for comment, but he can't exactly do that here either.

**Comment by adacovsk** [comment]
> As you have bomber blocked, and he was against the previous PR that did this exactly this for more reasons than just the title and presentation, should we assume one extra thumbs down than visible for the emojiocracy? Or should we wait for him to contact a third party to relay his feelings on the matter? I would ask @BomberBro for comment, but he can't exactly do that here either.

Maybe do a poll if you care about his opinion so much. I don't think he as any valuable input, which is why he's blocked. Alternatively, you can tell him to behave better, so that I can unblock him

**Comment by bathosbathtime** [comment]
I wasn't talking to you.

**Comment by Exxion** [comment]
>Maybe do a poll if you care about his opinion so much. I don't think he as any valuable input, which is why he's blocked. Alternatively, you can tell him to behave better, so that I can unblock him

What about his behavior was even bad?

**Comment by pedr69** [comment]
>blocking people makes them unable to vote on a PR

piss baby tier behavior

**Comment by Exxion** [comment]
Yeah GitHub's blocking system is just incredibly moronic

The PR author having the ability to exclude people from the discussion is entirely incompatible with the way we run this repo. Regardless of whether or not it is your intention, blocking people unfairly manipulates the discussion. As usual we didn't set any official policy, but after the discussions today, I think most of the collabs would agree that it's not appropriate for PR authors to block other repo users outside exceptional circumstances. It's unfortunate this is how GitHub blocks work, but we can't change them.
If you want something that works more like a traditional blocking system, where it only hides the blocked posts from your *own* view, it should be relatively simple to make a userscript for that. I'm absolutely not a web developer, but could probably throw something together, if it would help.

**Comment by adacovsk** [comment]
> Yeah GitHub's blocking system is just incredibly moronic

I think it's funny. I think this should include some etiquette for commeters and submitters:

http://ss13.moe/wiki/index.php/Getting_Your_Pull_Accepted

**Comment by Eneocho** [comment]
> I'm absolutely not a web developer, but could probably throw something together, if it would help.

There's probably a userscript somewhere already.

**Comment by Eneocho** [comment]
Yep. The Github-issue-comment script on [this repo](https://github.com/Mottie/GitHub-userscripts) can hide comments from certain people.
https://github.com/Mottie/GitHub-userscripts/blob/master/github-issue-comments.user.js

**Comment by ShiftyRail** [comment]
If we do include some pull etiquette, it would certainly have to include "don't block people who disagree with you" on it. I can't believe we've managed to out-TG TG. At least they just *hide* comments they don't like, they don't make them vanish out of existence.

**Comment by ShiftyRail** [comment]
Please refrain from blocking people commenting on your issue if you want a real shot at it being merged. This is an open forum. If someone is REALLY being an arse, tell collabs about it.

**Comment by Servalfang** [comment]
i'm unironically in favor of this but the behavior is unacceptable

**Comment by Eneocho** [comment]
I'll add a note to the wiki page warning against blocking someone and using a userscript instead.

**Pull request closed without merging**
