### PR TITLE
Telecomms vending machine.

### PR DESCRIPTION
**Pull request by BurntDevil**
on behalf of jakmak6, stone him when it breaks, not me

:cl:
 * rscadd: A crate of telecomms gear has been registered in cargo's catalog.  You can now order and build a telecomms supply vending machine.

### CODE REVIEW

**Comment by jakmak6** [comment]
This PR (made on my behalf because i cannot of into github) adds a new vendor in. The telecomms vendor. Similar idea to the generic vendomatt which vends stock parts (and some other assemblies stuff). This vendor is stocked with stock parts, telecomms specific stock parts (think hyperwave filters and subspace doohickies), telecomm machine boards, the boards to the consoles which monitor and analyze telecomms networks, and some minor stuff (gadget bags, solder irons)
Currently the pack can only be gotten ingame via cargo ordering the supply pack.

telecomms vendor
from left to right
Off state, On state, On with maintenance panel open, supply pack

**Comment by jakmak6** [comment]
Full list of its contents are as follows

micro-manipulator: 10 
micro-laser: 5
high-power micro-laser: 3 
subspace ansible: 2 
hyperwave filter: 6 
subspace amplifier: 2 
subspace treatment disk: 4 
subspace wavelength analyzer: 2 
ansible crystal: 2 
subspace transmitter: 4 
Circuit Board (telecommunications subspace receiver): 1 
Circuit Board (telecommunications bus): 1 
Circuit Board (telecommunications processor): 1 
Circuit Board (telecommunications subspace broadcaster): 1 
Circuit Board (telecommunications server): 3 
Circuit Board (telecommunications hub): 1 
Circuit Board (telecommunications relay): 2 
Circuit board (Telecommunications Monitor): 1 
Circuit board (Telecommunications Server Monitor): 1 
gadget bag: 2 

  contraband:
part exchange device: 1  (NOT the RPED)
soldering iron: 2 (pre filled)

  premium:
Circuit board (Message Monitor): 1 (used to read PDA message logs)
Circuitboard (Telecommunications Traffic Control): 1 (used to edit NTSL code)

The reason why so many parts are in the vendor is because telecomms machines need a lot of parts, be it normal manipulators or specialized telecomms parts. 1 supplypacks worth is enough to make a rudimentry telecomms network (assuming you have the metal and cables to build the machines). 
2 supply packs is enough to build a sophisticated telecomms network, complete with servers, a hub, and relays for off Z-level comms

**Comment by DeityLink** [comment]
Just asking, why not ask R&D for parts instead? This feels like power creep but I'm not sure what for.

**Comment by jakmak6** [comment]
deity. It takes the following parts to make a BASIC telecomms network that wont have stuttering or anything like that.

9 MICRO-MANIPULATORS, 4 HYPERWAVE FILTERS, 1 ANSIBLE CRYSTAL, 2 HIGH-POWER MICRO-LASER (T2), 1 MICRO-LASER (T1),
1 SUBSPACE ANSIBLE, 2 subspace treatment disk, 1 subspace (wavelength) analyzer, 1 subspace amplifier, and 4 boards

And that is for the absolute barebones network. No servers for NTSL and comms logging, no support for off Z level comms.
I want you to go to r&d (with the assumption that 1. r&d was done, 2. Minerals were delivered, and 3 there is a scientist on duty) and ask them to make that colossal list of extremely specific parts.
After you do that (usually they mess up a part or two in the protolathe que because can you blame someone for confusing the subspace ansible to the ansible crystal to the subspace refuckulator), you would also need to bring them a gallon of sulpheric acid to make those boards assuming they didnt build a chemistry dispenser.
All of this can mount to be an obscene task when instead this proposes an alternative. All those parts in a convenient vendor.
Also before you say telecomms parts storage, most maps dont have enough parts to build a barebones network. Instead of fixing that I was considering replacing the tcomms parts storage with this vendor but another PR for another day

That and lets be real. If there is someone out there who actually understands telecomms well enough to build a new network (or repair the old one), regardless of intent be it benign or antagonistic, they deserve to not have to jump through a thousand hoops just for their tism machinery

**Comment by DeityLink** [comment]
>Also before you say telecomms parts storage

I wasn't gonna-

>most maps dont have enough parts to build a barebones network.

Yeah that. maybe that's also an issue though, when was the last time the part in tcomms storage were used?

>Instead of fixing that I was considering replacing the tcomms parts storage with this vendor but another PR for another day

Oh ok then. I guess it's kinda in line with how other features like xenoarch are getting streamlined. But honestly if that means more players get to tinker with it I'm all for lowering the amount of hoops. Still feels though that Cargo gets more and more to be as useful as R&D for criminally less effort.

**Comment by jakmak6** [comment]
> Still feels though that Cargo gets more and more to be as useful as R&D for criminally less effort.

what if for this specific flatpack (and the generic vendomatt flatpack for that matter) r&d can make this flatpack. For some cardboard and a smattering of minerals (to equate to the amount needed to make those parts individually) you can have the packs to this machine.
Ofcourse just for the specific vendomatts like the aforementioned. Not for food or anything, that would be ridiculous

**Comment by DeityLink** [comment]
Since you're suggesting that R&D makes flatpacks, here's yet another idea how about merging Mechanics and R&D ? R&D was in charge of upgrading station machines originally and Mechanics were created because Scientists never did it, but nowadays Mechanics that never do their job are the problem, clearly Mechanics were not the right approach, and on the other hand R&D is mostly boring, let's merge the jobs once more and improve both of them at once.

**Comment by jakmak6** [comment]
SHIT just realized i wrote flatpack instead of supply pack. I mean vendor supply pack not flatpack
havent had my half gallon of coffee yet

**Comment by jakmak6** [comment]
is this good to go or does it need to be fixed/adjusted?

**Comment by BurntDevil** [comment]
doesnt seem like it needs anything

**Pull request merged**
