### PR TITLE
Chronic Lime Disease, a new Stage 2 Symptom

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Adds a stage 2 symptom that makes you vomit limes. (not to be confused with Chronic Lyme Disease)
## Why it's good
Funny less-than lethal symptom.

:cl:
 * rscadd: Spessmen might find themselves affected by Lime Disease, and are advised to procure some salt and tequila in that case.

### CODE REVIEW

**Comment by SonixApache** [comment]
though i like the idea - what makes this stage 3?

**Comment by Eneocho** [comment]
> though i like the idea - what makes this stage 3?

It's on stage 3 because chicken pox is on stage 3. I could move it down to stage 2 though.

**Comment by ConfusedCactus** [comment]
Funny, I like it. I'm generally a fan of disease symptoms that are more funny annoyance than major gameplay hindrance.

**Comment by DeityLink** [comment]
Should be Stage 2 to fill the spot left by Glasgow 😌

**Comment by Eneocho** [comment]
aight

**Comment by falcon2346** [comment]
If you have this and chicken pox you've got half the ingredients for lime cake.

**Comment by Eneocho** [comment]
> If you have this and chicken pox you've got half the ingredients for lime cake.

clearly we need a disease that makes you sneeze flour, and if you hold a reagent container, you sneeze it in, and one that makes you bleed milk

**Pull request merged**
