### PR TITLE
Add "Blow on" verb to foods

### PR DESCRIPTION
**Pull request by joaomarcosh**
## What this does
Add a "Blow on" verb to the right-click menu for food items.

## Why it's good
Because not everyone knows you can Alt+MiddleClick your food to cool it.

## Changelog
:cl:
 * rscadd: Add a "Blow on" verb to the right-click menu for food items.

### CODE REVIEW

**Comment by kilozombie** [comment]
This should absolutely be called "blow on" and not "blow" lmao

**Comment by SonixApache** [comment]
even more unnecessary verbs to clutter up the lists

**Comment by kilozombie** [comment]
> even more unnecessary verbs to clutter up the lists

Object verbs only appear at all once you're adjacent to something you can use it on. Rotate-chair as an example

**Comment by SECBATON-GRIFFON** [comment]
we sit down to eat, and the potato's a bit hot. so i only put a little bit on my fork and i blow. *puff-puff* 'til it's cool. just cool. then into the mouth. *hawlp* *click* noice.

**Comment by SonixApache** [comment]
ok i dislike verbs but not everyone has a middle mouse button so i think this a good addition 👍

**Review by west3436 — APPROVED** [review]

**Pull request merged**
