### PR TITLE
Speeds up lights on at roundstart

### LINKED ISSUE #25817: Using light switches restarts emagged jukebox's song
#### Steps to reproduce
- Be spessman
- Emag jukebox and start playing a song
- Flick the light switch
- The song just restarts??

#### Specific information for locating
why does this code exist
```
/obj/machinery/media/jukebox/power_change()
	..()
	if(emagged && !(stat & (NOPOWER|BROKEN)) && !any_power_cut())
		playing = 1
		if(current_song)
			update_music()
	update_icon()
```

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[performance][qol]

## What this does
shaves up to ~~1~~ ~~1.3~~ *1.5* seconds off that new slower roundstart (roundstart being the actual beginning of the round with job and antag assignment)
adds a server config option to have all lights on at the start of the round regardless of players, off by default
incidentally closes #25817.

## How it was tested
editing config file, starting the game, obsing as ghost

## Changelog
:cl:
 * rscadd: Server config now has an option to turn all lights on at roundstart, off by default
 * tweak: Total roundstart time and lights on time is now printed to admins in-game
 * bugfix: Lights now instantly turn on at roundstart, instead of after a delay
 * bugfix: Lightswitches now use moody lights, so their overlay no longer renders above everything
 * bugfix: Roundstart now has up to 1.5 seconds less lag.
 * bugfix: Admin flicking all lights on and off is also better performing now
 * bugfix: Jukeboxes no longer reset song on lightswitch flicking

### CODE REVIEW

**Comment by Theophrastus1** [comment]
the Return of Adam

**Comment by SECBATON-GRIFFON** [comment]
> the Return of Adam

more like undoing whatever happened that caused it

**Comment by angryturnip** [comment]
adam...

**Review by west3436 — APPROVED** [review]
Very nice change!

**Comment by west3436** [comment]
@SECBATON-GRIFFON fella if you're still changing your PR, bring it to draft so we don't need to waste my time reviewing it only for you to add ten new commits after it has been reviewed. This is not the first time you've done this and you're tiring dilt and I out!

**Comment by SECBATON-GRIFFON** [comment]
> @SECBATON-GRIFFON fella if you're still changing your PR, bring it to draft so we don't need to waste my time reviewing it only for you to add ten new commits after it has been reviewed. This is not the first time you've done this and you're tiring dilt and I out!

wasn't sure this was a problem but i'll note it

**Comment by SECBATON-GRIFFON** [comment]
fun fact: theres still about half a second of lighting lag left if there's at least 1 player on with all the lights flicking on set in the config but if theres 0 players its instant, however commenting out the lighting subsystem update makes it instant with the 1 player at the cost of lights being a lil slower to flick on. worth noting

**Comment by west3436** [comment]
@SECBATON-GRIFFON will merge after you fix conflicts

**Comment by SECBATON-GRIFFON** [comment]
> @SECBATON-GRIFFON will merge after you fix conflicts

@west3436 done

**Pull request merged**
