### PR TITLE
Strike Team bases revamp

### PR DESCRIPTION
**Pull request by JMWTurner**
This will probably be my last PR on this account seeing as I've started using @DeityLink  again.

Most of this code and map changes are old from 5 months ago, and I put them on hold because I was tired and busy with work/studies. I cleaned it up and am finally ready to release them.

Behold your new centcom (of course the emergency/cargo shuttles have been accounted for on every maps):

centcom

The ERT finally has a fitting base and shuttle, and the deathsquad got some love as well

bases

I had to edit Deff and Bagel a bit so that the ERT shuttle could dock there as well:

map changes

The Elite Syndie base has been left mostly unchanged.

image

And here's the base for custom teams:

custom

:cl:
* rscadd: Centcom received some huge changes. The holding pen has been removed, thus ridding ourselves of the last proof that Space Ninjas ever were a thing. ERT and Deathsquad bases have gone through massive overhauls.
* rscadd: Added an admin-spawned suit dispenser machine, that lets admins quickly spawn sets of items. For now there are some in the custom strike team bases, later they might see some use in the thunderdome.
* rscadd: Admins can now spawn custom strike teams, they have a small empty base, fit with the tools for admins to quickly set up a custom squad, as well as their shuttle's destination locations. honksquads have never been this easy to set up.
* rscadd: The Deathsquad and Elite Syndie shuttles work at last! They have two destination on each stations, one that's in space near the station, and the other that consists of ramming their ship inside the station!
* rscadd: Players that wish to use shuttles to head over to the centcom Z-level now need to receive explicit permission from the admins. Admins receive a notifications when a flight is attempted, and can accept or deny it with a click. Both sides have the option of giving a reason.
* bugfix: Fixed the action buttons (headlights, holominimap, etc...) of strike team members being invisible when they spawn.

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
That looks pretty good.

I'm glad that Centcomm will keep the ferry.

**Comment by Praecordia** [comment]
MERGE WHEN

**Comment by CptWad** [comment]
oh sorry

**Comment by DeityLink** [comment]
@CptWad 

`>:[`

**Pull request merged**
