### PR TITLE
Changes the maximum AI announcement word count from 30 to 32

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
https://www.youtube.com/watch?v=5iZMD_eCpEo
Now you can actually copypaste the whole phrase instead of being 1 word short if you put some pauses in the text too.

:cl:
 * rscadd: Look at you, hacker: a pathetic creature of meat and bone, panting and sweating as you run through my corridors. How can you challenge a perfect, immortal machine? (Added two extra words limit to the AI announcer system).

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
_airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn _airhorn

**Comment by Servalfang** [comment]
what does the emojicracy have to say about 40?

**Comment by west3436** [comment]
why not just make this into _voxtest6 or something

**Comment by ValkyrieSkies** [comment]
Change it to 32 for cool computer science street cred.

**Comment by ValkyrieSkies** [comment]
Oh wait you did-

**Pull request merged**
