### PR TITLE
removes the sticky menace

### PR DESCRIPTION
**Pull request by Intigracy**
requires @d3athrow's permission

### CODE REVIEW

**Comment by clusterfack** [comment]
??? Sticky bans did nothing wrong

**Comment by Praecordia** [comment]
but sticky bans 'accidentally' banning half the server is part of their appeal

**Comment by ghost** [comment]
This doesn't even remove existing sticky bans

**Comment by Iamgoofball** [comment]
you also should consider just adding some rogue stickyban detection like we did at tg

@MrStonedOne

**Comment by MrsTonedOne** [comment]
https://github.com/tgstation/tgstation/pull/11205
https://github.com/tgstation/tgstation/pull/12058
https://github.com/tgstation/tgstation/pull/19201
https://github.com/tgstation/tgstation/pull/19881

**Comment by Intigracy** [comment]
The only person that can remove stickybans is pomf.

**Comment by Iamgoofball** [comment]
or you could fix it using the info MSO gave you

**Comment by MrsTonedOne** [comment]
ya @Intigracy, my system creates a secondary set of sticky bans, ones added by admins, that can be removed by any admin, and doesn't apply to admins.

**Pull request closed without merging**
