### PR TITLE
Fulltile windows now have double + 5 the health of a directional window of the same type

### PR DESCRIPTION
**Pull request by Intigracy**
I'm sad we can't make tinted windows without being an admin, I'll probably insert plastic into this equation.

### CODE REVIEW

**Comment by PJB3005** [comment]
The thing about tinted windows is that they look like shit when not full tile, and when they're full tile they're just there to look cool instead of a wall.

**Comment by Intigracy** [comment]
For now.

**Comment by clusterfack** [comment]
Oh man this is just too much health, rplasma doors have just 400 health and already take *forever* to kill

**Comment by Intigracy** [comment]
Use something heavier, duh!

**Comment by PJB3005** [comment]
85 HP for the full reinforced window = 7 hits with an RPD.

I'd say it's not the end of the world.

**Comment by clusterfack** [comment]
That's just the reinforced window pjb, the reinforced plasma ones have 325 health AND stack on top of one directional windows.

**Comment by Probe1** [comment]
..i'm okay with buffing the hell out of plasma windows.  it's really hard to justify my effort of grabbing plasma from engineering/miners/research and making my own plasma glass, then using that instead.

a see through wall.  doesn't require a welder to disassemble.

**Comment by Intigracy** [comment]
You can't make a fulltile window on the same tile as one that already has a directional window, it doesn't let you.

The only way to achieve that affect is to be a shitmin or to map it in.

**Comment by clusterfack** [comment]
Well my complaint against it is that it outclasses the reinforced plasma windoor significantly quick requires five reinforced plasmaglass and two plasteel, which people already think is strong as fuck.

**Comment by Probe1** [comment]
wait what are we talking about again?  you can't make a full window?  But you can?

**Comment by Intigracy** [comment]
You can make fulltile windows using plasma glass/reinforced plasma glass sheets.
You cannot do so if the tile you are on already has a directional window on it.
You cannot (to my knowledge, haven't tested) push a fulltile window onto a tile that has a directional window on it.


Don't rplasma windoors have like 400 something health, with the added benefit that you can go through them? You can already achieve this health effect anyway using two directional plasma windows.

**Comment by clusterfack** [comment]
You definitely can build them on the same tile as a directional window. And this would be approximately the same health as two plasma windoors, while costing 6 less reinforced plasma glass, 2 less airlock electronics and 4 less plasteel.

**Comment by Probe1** [comment]
Idk whats on your end but you can.  I didn't do the final 4th window because I didn't put a grille down first, which you attach the last pane to once you leave the tile.

**Comment by Intigracy** [comment]
oh god that's terrible

**Comment by Intigracy** [comment]
Anyway I see your points, thanks for the feedback.

**Pull request closed without merging**
