### PR TITLE
Fixes a bug where someone can turn into a manifested ghost via the staff of change

### PR DESCRIPTION
**Pull request by JonathanSpaceStation**
## What this does
Should make it so that you can not turn into a manifested ghost via staff of change; this had previously been fixed a few years ago but has re-emerged at some point [bugfix]

## Why it's good

because it fixes an annoying bug 

## Changelog

:cl:
 * bugfix: staff of change should no longer be able to turn you into a manifested ghost

### CODE REVIEW

**Comment by adacovsk** [comment]
Why is this considered a bug? I've always recalled being able to turn into Manifested with SoC

**Comment by JonathanSpaceStation** [comment]
[23267]

**Comment by JonathanSpaceStation** [comment]
#23267

If you get turned into a manifested ghost you cannot be turned into anything else; and if you die you turn into an unrevivable pile of ash; when it happens to people they are usually confused as fuck about it because manifested ghosts are incredibly rare in all other circumstances; plus it was previously removed before and has snuck back into the code by accident

**Comment by adacovsk** [comment]
> #23267

Thought it was intentional to prevent SoC cheesing. Good to know.

On second thought, why does manifested even exist? It does nothing outside the SoC

**Comment by JonathanSpaceStation** [comment]
> > #23267
> 
> Thought it was intentional to prevent SoC cheesing. Good to know.
> 
> On second thought, why does manifested even exist? It does nothing outside the SoC

I think its superfluous and doesn't really exist anywhere else, so could probably be removed entirely unless someone has some idea or use for them in the future. Didn't want to do that in this PR though as only looking to fix a very specific issue and don't want to accidently break something I wasn't aware of or some use case I hadn't thought about

**Comment by DeityLink** [comment]
@adacovsk 

> Why is this considered a bug? I've always recalled being able to turn into Manifested with SoC

> Thought it was intentional to prevent SoC cheesing. Good to know.

Yeah that's a bug, I never intended for manifested ghosts to appear in the game outside of specific cult interactions (specifically the manifested ghost rune that I designed it for originally). So let's see what git blame tells us about it.

image

Well would you look at that, someone called adacovsk changed the line with the WHITELISTED flag last October, let's check out the concerned PR (#33424).

image

Hmm, that's quite an important change there, let's check that PR's changelog.

image

hmmmmmmm

image

**Comment by PrimeDSS13** [comment]
banish adacovsk to the wastelands

**Comment by adacovsk** [comment]
Even before the changes, I remember being able to change to a manifested ghost. I guess that was before 2019 when the fix was merged. My mistake, I hope no one's feelings were hurt in the process

Also, the whitelist stuff was supposed to keep the backend stuff consistent, SoC should probably use PLAYABLE list and not WHITELISTED perhaps instead

**Comment by Eneocho** [comment]
I for one am on the side of keeping the bug. Funny manifested staff fuckery is funny.

**Comment by Kromkar** [comment]
Adam should be sentenced to 20 years in the Isocubes

**Pull request merged**
