### PR TITLE
H/E Pipe Fixes

### LINKED ISSUE #14298: HE Pipes infinitely layerable
dreamseeker_2017-03-08_19-21-38

I can't pinpoint where this is happening, but the `/obj/item/pipe/onattack()` shit seems to be one likely culprit.  

/cc @ComicIronic since he's the layering guru

### PR DESCRIPTION
**Pull request by N3X15**
# Executive Summary
Fixes a few ancient bugs related to HE pipes, namely the ability to infinitely stack them and the fact that they exchange heat from 1/4 of the *entire fucking pipeline*.

# Testing Apparatus
Heavily modified SME.  Tested with shard and crystal.  In-game modifications to both normal pipes and HE pipes were required.

dreamseeker_2017-03-10_01-32-35

From before emitters were turned on: (O2 coolant)
dreamseeker_2017-03-10_01-08-22

# Changelog
it's right there in the fucking repo jesus christ

Fixes #14298, #14299, #5754

### CODE REVIEW

**Comment by Probe1** [comment]
Telecomms tested for overheating?

**Comment by N3X15** [comment]
I didn't notice it overheating, no.  I'll do a more thorough test, though.

**Comment by N3X15** [comment]
@Probe1 Yep, works fine, aghosted to the air alarm and air temperature was falling despite the changes.

**Comment by PJB3005** [comment]
You should keep in mind that telecomms only generates heat while there's actual traffic.

**Review by PJB3005 — APPROVED** [review]

**Comment by jknpj** [comment]
spawn 200 poly/buttbots and you'll get a nice traffic test

**Comment by CptWad** [comment]
or the screamer

**Comment by Probe1** [comment]
We can get the players to test it.

😈

**Comment by CptWad** [comment]
jesus christ probe

**Pull request merged**
