### PR TITLE
Finally gives flashes back their in-hand sprite

### PR DESCRIPTION
**Pull request by Sprok0**
I found the missing flash in-hand sprite in r4407, it's back
flashsprite

### CODE REVIEW

**Comment by clusterfack** [comment]
WOW YOU JUST NERFED REV

**Comment by Shadowmech88** [comment]
[Balance]
[Controversial]

**Comment by FudgePucker** [comment]
I thought one of the points of the flash is that it doesn't have a in hand sprite.
It doesn't work on anyone with a hard suit helmet, sunglasses, and even science goggles.
Also it is small enough that you could palm it in your hand and not have it be obvious.

**Comment by Exxion** [comment]
[Honk]

But seriously it is balance and is gearing up to be controversial

**Comment by jknpj** [comment]
Why not? If you can examine and see the flash i see no reason to not have an sprite.

**Comment by Exxion** [comment]
Having to shift+click someone and notice one line of text that looks the same as all the others is very different from seeing something on someone's sprite just by looking at them

**Comment by ghost** [comment]
Going to disagree on this being balance - all items should have an in hand sprite, the only reason they don't is laziness.I definitely strongly disagree on it being controversial though.

**Comment by Sprok0** [comment]
Flashes already had item_state = "flash", it's just that the icon vanished from the .dmi at some point. This is a bugfix more than anything else.

**Comment by FudgePucker** [comment]
@DrCelt 
It is balance.
Flashes suck dick compared to other forms of stunning.
Melee range only.
Doesn't work on engineers security and powergamers.
And it can even burn out and become worthless.
They are harder to get than stun prods and scrub glubs.
Having no in hand sprite is the only thing they have left.

If you remove flash then the only fucking use it will have at all over any other stun weapon is stunning borgs and rev.

**Comment by Exxion** [comment]
@DrCelt 

> I definitely strongly disagree on it being controversial though.

Are you sure you know what controversial means?

And yes, being able to just see it in someone's hand is a BIG balance change.

**Comment by Gef21** [comment]
Who cares about balance lmao this isn't hippie

**Comment by Shadowmech88** [comment]
I was under the impression that bugfixes were exempt from concerns about the balance changes that result from them.

Like when infinite monkey blood got fixed.

**Comment by Exxion** [comment]
They aren't supposed to be.

**Comment by clusterfack** [comment]
I was being mostly facetious, I don't think there's anything wrong with this

**Comment by sonime** [comment]
smol things like inhand sprites do affect balance

balance is a very tricky thing with videogames, moreso than a lot of ppl think

**Comment by Zth--** [comment]
This is the right way to go, every item should have its in-hand sprite. If it affects balance then it should be rebalanced somewhere else

**Comment by clusterfack** [comment]
Well theorycrafting at this point is really a waste of time, it'd be better to just see how it shakes out.

**Comment by Boxe** [comment]
iirc the flash lost its in hand due to too many sprites or some shit i forget

n3x is the one who knows

**Pull request merged**
