### PR TITLE
Stuff that protects you from airborne diseases also prevents you from sneezing out mucus or sputum

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* rscadd: Stuff that protects you from airborne diseases also prevents you from sneezing out mucus or sputum.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
This is used as an alternate method of infection. Maybe have it so that airborne pathogens don't roll anything that affects the airways? Otherwise they'll just be another buffer symptom for virogenning.

**Comment by Exxion** [comment]
Obviously this makes logical sense but reminder that internals still release the air you breathe *out* into the environment. They only affect *inhalation*
So it sort of makes sense either way

**Comment by bathosbathtime** [comment]
yeah lemme just sneeze into my mask

**Comment by tuypo1** [comment]
Only if the mask eventually fills up and causes problems

**Comment by DeityLink** [comment]
k

**Pull request closed without merging**
