### PR TITLE
Adds a religion for chaplains referencing Dune

### PR DESCRIPTION
**Pull request by Durgen**
This is babies first pull request. I hope my code is not shit.

:cl:
 - rscadd: Adds a religion for the Chaplain from Dune

### CODE REVIEW

**Comment by gbasood** [comment]
your changelog isn't right

**Comment by SonixApache** [comment]
format:
```
:cl:
 - rscadd: Adds a religion for the Chaplain from Dune
```

**Comment by Durgen** [comment]
thanks, fixed

**Comment by Duny-** [comment]
It's shai-hulud not shai-halud

**Comment by Durgen** [comment]
fug

**Pull request merged**
