### PR TITLE
Changes the sound for sending a message over the radio

### PR DESCRIPTION
**Pull request by ExpulsionSnooper**
[tweak]
Got it from here: https://freesound.org/people/3questionmarks/sounds/612722/
:cl:
 * soundadd: Sending a message over the radio now has a different sound compared to receiving one.

### CODE REVIEW

**Comment by WindowsErrors** [comment]
now instead of ksssht kssht kssht its kssht bowyeep ksst ksshy bowyyt

**Comment by Hinaichigo** [comment]
There's a somewhat more satisfying walkie talkie sound out there... less high pitched. You might know it. It's like three very quick ascending notes that blend into one another, combined with a click. I wonder where to find a good copy of that.

It kind of sounds like the second part of this one:
https://freesound.org/people/Kijadzel/sounds/170608/

Actually this is what I'm thinking of:
https://youtu.be/Y5oEGZnffRE?t=43

**Comment by ExpulsionSnooper** [comment]
If you can find me one that's better than the one I've got PLUS some sort of little radio static at the end, I will happily replace what I've added here.
edit: Ok I take it back, I like the one I've posted initially a little bit more

**Comment by Kharkov72** [comment]
this is ASS

**Pull request merged**
