### PR TITLE
Multiple Minor Meta Modifications

### LINKED ISSUE #6900: Hot Drinks machine in Perma Brig requires money
(WEB REPORT BY: orzorn REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

7eb3e8a91327faff1f3accde8fd89b9c9ce49404 

> General description of the issue

Hot Drinks machine in the perma brig requires you to use money, something that pretty much nobody in the permabrig will have on hand due to having no ID/PDA.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by xpcybic**
- Removed the hot drinks machine from permabrig.
- Added a newscaster to tcomms control room, for easy AI access.
- Fixed the bar window shutter control not working.
- Removed a set of plastic flaps at one end of recycling, and added an airlock at the other end.
- Replaced the windows between toxins lab and RD's office with plasma ones.
- Moved the launch room intercom closer to the bhangmeter.
- Removed the sleeper blocking the infirmary door on the escape pod docking shuttle.
- Rearranged the emergency shuttle infirmary to remove the console-less sleeper.
- Un-reinforced the tables in toxins.
- Widened xenobio.
- Added a couple of emergency closets in hallways and maint.
- Removed the crate and two grilles blocking passage through aft maint.
- Removed the human test dummies from the toxins test site.
- Added a cyborg analyzer to robotics.

Fixes #6900, #7224, #7226, #7375, #7384, #7386, #7427, #7435, #7449, #7732
Kind of addresses #7374? <sup>But I mean if you want consoles you could just jump to the bridge</sup>

screenshot 2016-01-22 17 27 47
screenshot 2016-01-22 17 29 03
screenshot 2016-01-22 17 35 29
screenshot 2016-01-22 17 47 25

### CODE REVIEW

**Comment by 9600bauds** [comment]
Picture of new Xenobio? Or more specifically, were the pens made to not be visible to eachother?

**Comment by xpcybic** [comment]
screenshot 2016-01-21 23 59 58
It's one tile wider, a slime in one pen can at most see the outer windoor of another pen. Not sure if this is enough but there's room on the left if it needs to be wider

**Comment by ihadtoregisterforthis** [comment]
Pics for everything that isn't obvious.
And generally, post pics for map fixes, unlike that last taxi PR.

**Comment by gbasood** [comment]
What about #7732 ?

**Comment by Ephx1** [comment]
> Removed the human test dummies from the toxins test site.

Yes, YES. NO MORE UNKNOWNS CLOGGING THE TRACKING LIST.

**Comment by Exxion** [comment]
Merge when?

**Comment by xpcybic** [comment]
Updated with screenshots for the ones that struck me as less "obvious"
The emergency closets are specifically at arrifvals (two) and showroom maint (one o2, one fire)
The rest seem kind of self-explanatory
@gbasood Did not get to that one. Actually give me a minute maybe I'll do it now

**Comment by IratePirate** [comment]
You're doing god's work.

**Comment by gbasood** [comment]
Restarted the travis build since travis now actually builds maps other than tgstation

**Comment by gbasood** [comment]
Make sure to add any issues that last commit fixed to the PR description so they get auto-closed (#7732)

Other than that, it passed travis build so I'd say it's ready to merge when you're ready for it to be merged

**Pull request merged**
