### PR TITLE
Fixes DNA Consoles Labeling DNA of Disfigured People "Unknown"

### LINKED ISSUE #4387: Transferring DNA from disfigured makes unknown
Transferring DNA from a disfigured / broken / unknown face corpse results in the DNA being attributed to unknown rather than who the DNA actually represents.

### PR DESCRIPTION
**Pull request by Shadowmech88**
DNA consoles now check the medical records for the subject's DNA first, and use the name associated with the DNA if found. Otherwise, the subject's display name is used.
Technically a balance change, I think, since you can now reveal anyone's true identity through use of a genetics console if they're in the medical records.
Fixes #4387.

:cl:
 * bugfix: The DNA of disfigured people will no longer be labeled "Unknown" by DNA consoles if the person is in the medical records.

### CODE REVIEW

**Comment by DamianX** [comment]
I'm not sure this should be a thing. `real_name` seems to be the name of the character as it was set at roundstart, the only way the machine should know it is by checking the records. Can we grab the name from the records by searching for the DNA?

**Comment by Shadowmech88** [comment]
How do I access the Security/Medical DNA records from the genetics modifier console?

**Comment by DamianX** [comment]
copypaste whatever the medhud or the records computer does?

**Comment by Shadowmech88** [comment]
DNA scanners now check the medical records, and use the name associated with the subject's DNA if found.

**Pull request merged**
