### PR TITLE
Blacksmithing is now relevant

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds blacksmithed sword icon states, courtesy of ReleastEstate

blacksmithing now tweaks some values of the forged item

:cl:
 * rscadd: Adds blacksmithed sprites for the gladius, shortsword, scimitar, sabre, and hammer, courtesy of RealestEstate
 * rscadd: Blacksmithing things to a high quality can yield better stats on the made item.

### CODE REVIEW

**Comment by anunknownentity03** [comment]
yes

**Comment by salamandooo** [comment]
You have pictures??

**Comment by RealestEstate** [comment]
credits to Sage of Light for the legendary gladius and rapier sprites.
@salamandooo you can select the check tab and then the icon diff bot to see the sprites

**Comment by yclatious** [comment]
Shit looks straight out of a fucking jrpg. God bless, merge this asap.

**Comment by SGuivenne** [comment]
can we get artifact text if we make a masterwork weapon?

**Comment by MadmanMartian** [comment]
Yes, that's already in

**Comment by ghost** [comment]
Do they have an on the belt or back sprite yet, or do they still use the basic sword one?

**Pull request merged**
