### PR TITLE
Meta atmos correction + minor issue fixes

### PR DESCRIPTION
**Pull request by kernikov**
metaatmos

## What this does
Fixes overlapped pipes.
Removes dorms atmos connection ports, if you want to fill/dump them go to engineering.
Removes random single tile pipes, connects isolated islands of piping (medical?)
Makes the courtroom atmos vents and scrubbers actually work, holy moly.

Changes SME scrubbers and Atmos Automation console to a unique frequency.
Minor re-work of dorms atmos, ex. more obvious feeds into rooms, and the SME lobby scrubber doesn't run past the holodeck lol.

## Why it's good
Because it works (tm)

## Changelog
 * bugfix: Metaclub atmos cleaned up, removing a LOT of nonsense, individual pipes, and open pipes to nothing.
 * tweak: Metaclub SME scrubbers no longer controlled by the area Air Alarm
 * bugfix: Metaclub Captain's office now has correct number of stamps
 * bugfix: Metaclub virology external airlock has a light

### CODE REVIEW

**Comment by kernikov** [comment]
dorms1
dorms2

**Comment by noirogen** [comment]
You can leave the pumps and scrubbers connected to waste/distro, the issue causing pressure changes is #37277, which is gonna get reverted in #37306. The pumps were just exacerbating the problem by updating the pipenet repeatedly

**Comment by hacker-on-steroids** [comment]
closes #36705

**Comment by kernikov** [comment]
closes #36204 (removed extra stamp)
closes #36115 (research archive was previously added)

**Comment by jwhitak** [comment]
Metamen, it's time...

**Pull request merged**
