### PR TITLE
Minor ZAS Optimizations

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Shaves some processing cost off the air subsystem with the following changes:

Reduces air subsystem cost by ~10-20%:
- Additional QUANITZE checks
- Replaced pressure/temperature/total_moles proc calls (expensive) with variable checks (cheap)
- Added return_readonly_air() which is used for checking but not modifying air and does not force a zone update when used.

Reduces datum/effect/system/smoke_spread/start() cost by 50%:
- Reduced fire smoke amount and life duration

## Why it's good

The air subsystem is one of the most expensive subsystems which can result in lag when multiple breaches or fires are present. This change doesn't have a major impact, but does improve performance slightly.

## How it was tested

Checked the MC after starting fires in multiple rooms while breaching Central Primary and looked for the maximum tick usage. Ran a profiler report to see the impact of the smoke spread changes.

No CL

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
wish there was a way to speed up subsystem init

**Comment by Eneocho** [comment]
‮?nehw ALLIM

**Comment by west3436** [comment]
> ‮?nehw ALLIM

Never. It's extremely hardcoded for Paradise and doesn't support XGM. Auxmos has built-in XGM support but is widely scorned by SS13 maintainers as unreliable and poorly-supported by the author. I'll still look into using Auxmos to power ZAS in the future after I try to just optimize ZAS as-is.

**Comment by Eneocho** [comment]
Sad.
I was looking forward to MILLA being ported properly like you had hinted at before.

**Comment by west3436** [comment]
> Sad. I was looking forward to MILLA being ported properly like you had hinted at before.

I started down the path of porting it but to make it work we'd essentially have to replace our entire atmos system and components to match Paradise's which I presume would be a hard sell to the playerbase. I'm working on getting Auxmos running with our zone-based atmos which will hopefully play much nicer with our existing features.

**Comment by Eneocho** [comment]
> > Sad. I was looking forward to MILLA being ported properly like you had hinted at before.
> 
> I started down the path of porting it but to make it work we'd essentially have to replace our entire atmos system and components to match Paradise's which I presume would be a hard sell to the playerbase. I'm working on getting Auxmos running with our zone-based atmos which will hopefully play much nicer with our existing features.

I wouldn't mind a whole new atmos system if it meant incredible performance. While I like the simple room-based atmos, it'd be really fucking cool if the thing was tile based instead.

**Pull request merged**
