### PR TITLE
Scientists (also Xenobio/arch) get Robotics access back. Roboticists get RnD access.

### LINKED ISSUE #30143: "Robotics for the Robos" was bad and we should revert it
I don't have pictures on hand but every round I've played as scientist ever since #29907 I just see the window (or sometimes door) between Robotics and the rest of Science consistently broken apart, or at best dismantled.

Having sub-departmental rooms locked to the rest of the department is only acceptable if the whole department is populated, which isn't always guaranteed, and is really just an eyesore at lowpop (especially when there's no HoP either). It's acceptable for Paramedics only due to every machine present in their station being also available elsewhere in medbay (on most maps at least).

When people knock at Science, at least 30% of the time they need a robot arm or to be borged/some criminal to be borged. (40% of the time it's Miners with mats, the last 30% are misc items needed from the protolathe/circuit printer), and as scientist you need Robotics either to help doing R&D, or to just keep yourself busy AFTER doing R&D since other science jobs are far away from the desk and have been split to their own jobs for a reason.

At the very least, "Scientists" should have Robotics access back. I don't mind too much if Xenoarch/Xenobio don't get it back *yet* (because even if they need to break in at some point, by that time there's good chance someone with access came, while Scientists need robotics access much earlier).

Anyway, discuss.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #30143

:cl:
* tweak: Scientists (as well as Xenobiologists and Xenoarchaeologists) now have Robotics access once again.
* tweak: Roboticists now have RnD access.

### CODE REVIEW

**Comment by gurfan** [comment]
Why was the removal of R&D access from robos sneaked into #30009 anyway?

**Comment by Eneocho** [comment]
> 
> 
> Why was the removal of R&D access from robos sneaked into #30009 anyway?

It wasn't. It was part of #29907.

**Comment by gurfan** [comment]
> > Why was the removal of R&D access from robos sneaked into #30009 anyway?
> 
> It wasn't. It was part of #29907.

why don't you read the changed files again

**Comment by DeityLink** [comment]
Both PRs were kind of a package, Apogee probably forgot to switch branch. It's no big deal.

**Comment by Eneocho** [comment]
> 
> why don't you read the changed files again

Welp, I didn't notice.

**Comment by Killette2** [comment]
Isn't this a buff on the science job slot making it the same access as the other two but better? I do not know if xenobio and xenoarch have any access that scientist does not

**Comment by DeityLink** [comment]
Science jobs are more an indication of commitment. I mean, if everyone's fine with Xenobio/arch having robotics access too I can toss it in.

**Comment by DeityLink** [comment]
alright then

**Pull request merged**
