### PR TITLE
fix #9018

### LINKED ISSUE #9018: How the fuck do you fail Chaplain Arrival messages?
>**Eli Wood and  deity, Pomf Chicken, have brought religion to the station!**

Grammatical error here, *can't seem to find it tough.*

### PR DESCRIPTION
**Pull request by Intigracy**
@Imagebard gobble some cock

### CODE REVIEW

**Comment by gbasood** [comment]
Really confusing that the text macro fails there but oh well

**Comment by Intigracy** [comment]
I think it's because of the [H.real_name] whereas most of the macros (if not all, haven't checked) have it as just [H].

**Comment by ihadtoregisterforthis** [comment]
So this goes untested?

**Comment by gbasood** [comment]
It's
Text

**Comment by ihadtoregisterforthis** [comment]
All code is text

**Comment by Intigracy** [comment]
@ihadtoregisterforthis fuck yourself

**Pull request merged**
