### PR TITLE
Buffs portable air scrubbers

### PR DESCRIPTION
**Pull request by brndd**
[featureloss] [tweak]

These things are very bad. They're about as effective as the regular scrubbers that passively scrub into the waste loop, which is IMO unacceptable for an active solution. In practice this translates to taking about 10-15 minutes, depending on room size, to clear a single plasma canister leak.

This PR makes these much faster. The details are a little complicated (keep reading if you're interested), but in practice it now takes about 3-5 minutes to clear a single plasma canister leak from a medium sized room. I also added the option to change which gases they scrub, which involved removing the speed setting to keep the UI from being cluttered (not a big loss, because there's never a reason to run these at anything but max power).

I also imposed a 50 ATM (5066.25 kPa) pressure limit on these and increased their tank volume to 2000 litres from 750 litres. In practice this means that they can hold about 40 tiles worth of standard pressure air.

## The details

These now take a 5000 litre sample of air from the room. From that sample, they remove up to 300 litres of the gases they're set to scrub, and return the rest back into the room. Before this PR they took a sample of 1013 litres and removed all contaminants from it.

In practice this means that compared to their current behaviour, the new behaviour is slower at gas concentrations of 30% or more, but faster at gas concentrations below that. When gas concentrations get very low, the new behaviour is substantially (up to about 5 times) faster.

The reason it works this way is that the scrubber can now be set to scrub anything, including oxygen and nitrogen, and without this limit it could be used to drain rooms of their air very rapidly.

The Clarke scrubber and the Huge Air Scrubber have a sample size of 20000 (this number is unchanged by me) and remove up to 1200 litres per tick. This may sound like a lot, but it's only 20% more than a single scrubber set to syphon.

:cl:
 * tweak: Portable air scrubbers now scrub up to 5 times faster than they used to and have a larger tank (2000 litres). They now have a pressure limit of 5066.25 kPa.
 * rscadd: Portable scrubbers now have a gas selection.
 * rscadd: The Clarke scrubber now has an accessible interface and can be connected to a connector port to drain its contents.

### CODE REVIEW

**Comment by brndd** [comment]
They now also have a gas selection so you can scrub oxygen out of the vox base (which starts with these iirc) or whatever it is you might want to do.

**Comment by brndd** [comment]
The Clarke scrubber can now also have its interface opened so that you can customize the scrubbed gases.

This thing is DANGEROUS. Set it to scrub Oxygen and Nitrogen and you can drain entire rooms in 10 seconds. However, it has limited (though very large, 50000 litres) capacity and now that I think of it there doesn't seem to be any way to empty it aside from like, deconstructing the mech or something ridicilous. I'll probably have to add a way to drain it.

**Comment by brndd** [comment]
Well, that was a pain, but you can now connect the Clarke's scrubber into a connector port to drain it too. It's done through the same HTML UI View Stats thingy that you access the scrubber interface from.

This combines pipecode and mechcode so it's extremely cursed. Prepare for bugs.

**Comment by abernd** [comment]
It's ridiculous to call this a buff when adding an arbitrary pressure cap. Considering that a plasma canister has an equivalent volume of 1000, and during a fire gas temperatures can easily increase by two orders of magnitude, the effective power of the scrubber would be very limited as it can only scrub a small amount of moles until it hits the pressure cap and stalls. In a best case scenario (i.e. the plasma does not ignite), one scrubber couldn't even scrub the amount of plasma contained in two roundstart plasma canisters before stalling. The only remedy would be to hook it to a connector wired into the waste loop, but then it isn't really portable.
 
Adding the ability to scrub other gases turns scrubbers into an upgraded air pump and ultimately a tool for destruction, as they can suck most of the air out of a room (at room temperature) very quickly. Especially considering Box starts with several scrubbers in a common area.  

For the Clarke, it makes no sense to increase the volume of the scrubber to 50000 as a single tile has a volume of 2500. Just increase the maximum pressure cap.

**Comment by bathosbathtime** [comment]
I find this to be a complete retooling of the purpose of the scrubbers than a buff.
Retooling them to be dust collectors as they'd be pretty awful with anything other than maybe yeeting all of the air out of the bar if no one is paying attention.

**Comment by FudgePucker** [comment]
What exactly would be the danger of having no pressure check on these?
You can't extract air from them other than a connector.

**Comment by Lunstra** [comment]
As has been said putting a pressure check on these absolutely annihilates their purpose and combined with the ability to select the gasses being scrubbed leaves them only really useful for yeeting all the breathable air out of a room. This PR may as well be named "changes portable scrubbers to be a niche antag item"

**Comment by brndd** [comment]
@abernd 

These aren't supposed to be miracle machines. No atmos machine is. If you have a plasma fire, cool it down first and then scrub it. If *two* canisters leak, bring two scrubbers.

I think the canister leak is a good target to aim for/balance around, because it's probably the most common cause of plasma leaks that only contaminate a single room, and a great example of the kind of a task where you would want to utilize something like this to clean it up faster (because floor scrubbers will often take a very long time to do so).

The purpose of these machines is not to clear station-wide plasma fires, or even just single-room plasma fires. They could never do it, and they never should be able to do it. No single solution should be able to clear such a catastrophic event by itself. Use foam extinguishers.

I did not touch the stats on the Clarke scrubber at all. It always was this good, with a capacity of 50k and a rate of 20k. However I *did* buff the stationary Huge Air Scrubbers, which you can find in eg. Deff permabrig, because frankly they were slow for something so specialized.

>Adding the ability to scrub other gases turns scrubbers into an upgraded air pump and ultimately a tool for destruction, as they can suck most of the air out of a room (at room temperature) very quickly. Especially considering Box starts with several scrubbers in a common area.

It will take a little while for these to suck all the air out of a room, and they will run out of capacity before they can completely drain all but the smallest rooms. The Clarke scrubber is incredibly robust, yes, but I don't think that's going to be an issue, and it's easy to nerf it if it proves problematic. It'll be pretty obvious to see what's going on if you see a Clarke roll by and all the air in the room is suddenly gone.

They won't encroach on portable air pumps too much because these completely lack the ability to pump anything out. Yes, they can drain rooms substantially faster than pumps set to pump inwards can, but I don't think that's a big problem. Draining gas is kind of the point of these things, and there's no simple way to maintain their efficiency at scrubbing without just making them able to move air really, really fast.

So TL;DR: the job of these things is to suck, while the job of portable air pumps is to blow, IMO.

&nbsp;

@bathosbathtime 

I... what? I'm curious what you think the purpose of these was before, and how what I did changes any of that. I haven't seen anyone use these things for the longest time because of how slow they are. The only thing I have seen them used for is separating gases in tanks. They will still perform that function as before, or in fact better than before.

They are now strictly better at removing gases from the environment, be that select gases or all gas. The only functionality they lost was the ability to set their speed, but I don't see why that should be kept in because there was never a reason to run the scrubber at anything but maximum power.

Or is this yet another pressure limit tantrum? All things considered there could be cause to increase the pressure limit of these to eg. 9000 kPa rather than the 50ATM it's at now. It leaves some room for abuse, but you can't stack these things in layers so I think it all balances out. I've increased the maximum pressure to 9000 kPa now.

**Comment by brndd** [comment]
In retrospect increasing the pressure limit may not a good idea. At 50 ATM the 1000 litre capacity of these can hold 20 tiles worth of air. This is important because it's what limits their ability to suck rooms dry of air. If I increase it to 9000, these will be able to hold about 36 tiles worth of air, which is a fairly substantial increase.

Anyway, I think I have an idea to limit the ability of these things to suck all air from a room. Basically, I'll make them process 5000 litres of gas every tick, but they'll at most remove, say, 200 litres from that. This means they won't be able to drain rooms rapidly, but will still be reasonably efficient at removing plasma leaks and such.

**Comment by FudgePucker** [comment]
>ThER ShOuLDnT bE a MaGiCAl AtMoS dEvIcE

Oh okay, I should use the foam extinguisher, that uses water, to cool down the toxins fire to ALMOST ABSOLUTE ZERO, then drag like ten fucking of these scrubbers down there.

Fuck realism dude. This change turns the tool used for treating plasma fires into only being useful for emptying tanks and very nitch uses. Oh yeah, with the changeable scrubbing it might have some use for the SME, but the pressure limit makes it WORTHLESS for fires.

**Comment by brndd** [comment]
Be honest with me, have you actually tried using these? Do you ever use these as they currently are? Because it sounds to me you don't, and I certainly practically never *see* anyone use them when playing. I've tested them out and they're AGONIZINGLY slow to the point of utter impracticality. The numbers are in the OP.

With the rate increase I've given them, even if they do have a pressure cap they're *still* faster than their current incarnation, even if you account for the time it takes for you to drag them back to Engineering and empty them when they fill up.

-----

Either way, being able to suck rooms clear of air is a valid concern. For that reason I've changed the functionality to be like I described in my previous comment. They now take a 5000 litre sample of air from the room and remove up to 300 litres of gas from that. Roughly speaking this means that compared to their current incarnation (static 1000 litres), they'll be slower at gas concentrations above 30%, and faster (substantially faster) at gas concentrations below 30%.

Comparing to the Boxstation Engineering Secure Storage test from above, it takes this version of the scrubber about 3 minutes 40 seconds to remove the snowflakes from the air after a canister is opened. On the other hand, it will never be able to drain rooms of their air any faster than a regular portable air pump can.

I also adjusted the Clarke and Huge Air Scrubber numbers. They now remove at most 1200 litres of air per tick, which is the same percentage (6%) of their "sample size" (20000). For comparison's sake, the Clarke can clear the snowflakes from same room as above in about 1 minute 30 seconds and will have ample capacity to spare.

**Comment by brndd** [comment]
I updated the OP to be more concise and describe the current nature of the PR better. Please re-read it to get up to speed with what's going on here.

**Comment by bathosbathtime** [comment]
Yes I have used these before.  While slow, they always managed to get the job done.  The change you are proposing will mean they can not do what they used to do anymore.  Please stop attacking the authenticity of the position of the people that disagree with your change.

**Comment by brndd** [comment]
Rather than set the pressure cap at 9000, I think I'm instead just going to increase their volume. It's now 2000 to match that of pumps. This means they have a higher effective capacity: 3692 moles for 1000 l / 9000 kPa vs. 4157 moles for 2000 l / 5066.25 kPa. This translates to 40 tiles of standard pressure air, or about 2.25 canisters filled to 4500 kPa.

I think this is the preferable solution because it keeps the pressure lower and makes it slightly easier to understand how much gas is in the thing in comparison to canisters.

I didn't increase the volume of the Clarke or the huge scrubbers because that's already extremely large.

**Comment by Kurfursten** [comment]
I carry a few of these babies with me in my Clarke, that's why the hydraulic camp is my favorite mecha equipment. Normally pack a couple overpressurized air cans too.

**Comment by brndd** [comment]
You really are better off carrying an RPD and a wrench in your backpack, and whenever you're about to put down a portable scrubber and leave it there you instead RPD down an extra regular scrubber (or five).

**Comment by FudgePucker** [comment]
Oh yeah, what about the hueg portable scrubbers in toxins storage? I think those need to be beefed up, considering they have to be wrenched down and controlled by a computer, they should have a fuck huge volume (blue space or some shit) and a high pressure cap.

**Comment by brndd** [comment]
They have 50k volume, suck in 20k air per tick and filter out up to 1200 from that. Same as the Clarke scrubber.

**Pull request merged**
