### PR TITLE
Europa Lights... out!

### PR DESCRIPTION
**Pull request by ShiftyRail**
As promised, this PR reverts all the Eurolights changes, using git revert (so it reverts no more, and no less). 

While the experiment was, in my opinion, not all bad (the feedback I get about the visuals is mostly positive now, as opposed to mixed last time), some clients have persistent lag issues and that's not something I want.

I've tried very hard to make it work, and it seems that it did improve quite a lot compared to last time, but - and that's a big but - there's still problems. Even for people who can manage just "fine", there are times when the lag is strong enough even as a regular player (ie, not a ghost, not an AI) to make the experience uncomfortable.

That's not really what I want which is why it might be better to shorten the experiment by a few days. Maybe worth still calling a vote on this - I will leave it to the headmins/Kurf to decide.

Overall, it's been fun. Now only BYOND is the obstacle. Lummox has hinted at improving the way BYOND talks to your GPUs sooner or later, so keep an eye out on this. I'm not giving it up.

We took, what, 3 years for antag datums and 1.5 years for the outfit ones ? We'll find a way. Probably.

https://www.youtube.com/watch?v=q-ODpnj6bvk

### CODE REVIEW

**Comment by ShiftyRail** [comment]
These last 3 commits are because i forgot to save my changes in VSCode before committing.

**Comment by MercuriusGH** [comment]
merge this asap

**Comment by ShiftyRail** [comment]
More like MercuriusGloryHole

**Comment by DeityLink** [comment]
Any chance we could somehow keep moody lights around if this gets merged? It feels like they should be able to work even without the rest of Europa Lights, and I kinda hoped we could expand them further.

**Comment by ShiftyRail** [comment]
Not exactly sure how since goonlights has no backdrop on which we can draw arbitrary shapes.

**Comment by Kurfursten** [comment]
We could probably still implement "glowing" overlay on morgue trays and APCs (in the same way do lightswitches already). Sparks might move slow enough that they could still have a glow on goonlights, though it might be too slow to pull off the nice flicker we get on Europa.

**Pull request merged**
