### PR TITLE
Probably fix the map vote having a huge delay.

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by clusterfack** [comment]
It seems to come from streaming assets to the client

**Comment by PJB3005** [comment]
It does, which is why it's less bad when the admins made meme votes during the round.

**Comment by clusterfack** [comment]
So tell the game to stream the assets when the emergency shuttle arrives at the station/launches

**Comment by PJB3005** [comment]
Good idea @clusterfack I implemented it.

**Pull request merged**
