### PR TITLE
Update an outdated value.

### PR DESCRIPTION
**Pull request by PJB3005**
How didn't we catch this sooner?

### CODE REVIEW

**Comment by ghost** [comment]
it should be 2016, this was referencing the [current year]

**Comment by JustSumBody** [comment]
Someone get this man a nobel prize

**Comment by Exxion** [comment]
@DrCelt No, we leave this PR as-is and just don't merge it for ten days.

**Comment by Aurx** [comment]
*crickets*

**Comment by Aurx** [comment]
>merging a DNM

Gasp!  Shock!  Horror!   
And then the fiend tried to cover up his wrongdoing by removing the DNM tag!

**Comment by Probe1** [comment]
BUSTED

GOTTEM

**Pull request merged**
