### PR TITLE
Fixes glass tile floor parallax and decals

### LINKED ISSUE #34913: glass floor doesnt parallax anymore??
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
9e32cd263de90541cf23651273be707f8492d280

# Description
i swear it used to be now the stars under glass floor are static
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[bugfix]

## What this does
image
Closes #34913.
also keeps decals and tile painting them intact this time

## Changelog
:cl:
 * bugfix: Parallax now works on space viewing glass tiles again.
 * bugfix: Decals now show up right on multi-z glass tiles.

### CODE REVIEW

**Comment by nervere** [comment]
This is reverting it to how it was. It's very easy to do this, but this isn't a "fix".
You can clearly see the decals are layering below the glass tile, which makes it look dumb.

**Comment by jwhitak** [comment]
While this fixes the parallax, this breaks decal layers. Here's an example, can you tell which one is before the fix and which one is after?

beforeafter

**Comment by SECBATON-GRIFFON** [comment]
tried fixing the decal layers too to no avail but i was hoping the compromise would be enough

**Comment by nervere** [comment]
If it's really impossible to have both without some convoluted solution, then this should probably be merged. People seem to like having the parallax a lot more than the correctly-layered decals anyway.

**Comment by SECBATON-GRIFFON** [comment]
> If it's really impossible to have both without some convoluted solution, then this should probably be merged. People seem to like having the parallax a lot more than the correctly-layered decals anyway.

fixed that now anyways, see updated image

**Pull request merged**
