### PR TITLE
ERTs cannot be called while the shuttle is enroute

### PR DESCRIPTION
**Pull request by F-OS**
[tweak] [balance]
This PR helps avoid the disappointing situation where an ERT is called with 3-5 minutes left on the shuttle clock. As an emergency response team, their goal should be to resolve the problems facing the station. While that may involve evacuation, the ERT should be involved in that decision and shouldn't just be forced to babysit the crew as they run onto the shuttle, as that's unfun for the ghosts who signed up. This doesn't prevent the ERT from calling the shuttle, or prevent admin-called ERTs from spawning while the shuttle is enroute, it just helps encourage stubbed-toe captains to stick it out.

Note: This was actually part of the code pre-2017 and got taken out by #14841 amid a few other changes.
:cl:
 * tweak: ERTs can no longer be called while the shuttle is enroute.

### CODE REVIEW

**Comment by Viciousaurus** [comment]
Only if they're requested  past the 5 minute emergency shuttle recall limit.

**Comment by DamianX** [comment]
I don't get it. As a ghost signing up for ERT you can see the time left for the shuttle to arrive. If, as the ghost, you think it's going to be boring because the shuttle is almost there, you can just...not sign up?

**Comment by F-OS** [comment]
@Viciousaurus I disagree. It takes about 5 minutes for ERT's to spawn, get prepped, and get on the station. Moving the limit to 5 minutes would basically make this PR moot.

@DamianX In my mind, it's more about encouraging people to use the ERT as a tool to fix stations that can be recovered. Think about it, why would you call a trained emergency response team if you're just going to abandon a station?

**Comment by BomberBro** [comment]
How would this work during blob or malf if the shuttle gets called and somebody wants to get an ERT? With blob especially you could softlock yourself out of an ERT if a blob comes before a shuttle arrives midround.

**Comment by F-OS** [comment]
this should prevent that situation @BomberBro

**Comment by SageOfLight** [comment]
I approve of this. Each time the ERT is called when the round is effectively swirling down the drain is nothing sort of stupid.

Also it lets us know if an ERT is now being forced by someone. The perfect canary for shitty adminbus.

**Comment by SonixApache** [comment]
Calling the ERT as a sort of back-up plan to help during evacuation (and possibly after the recall of the shuttle) can be a great boon during hard times.
I'd understand it if they couldn't be summoned after the shuttle point of no return, but not before that.

**Comment by F-OS** [comment]
> 
> 
> Calling the ERT as a sort of back-up plan to help during evacuation (and possibly after the recall of the shuttle) can be a great boon during hard times. I'd understand it if they couldn't be summoned after the shuttle point of no return, but not before that.

This PR doesn't prevent that, though. It just reverses the order. You'll need to call the ERT before you call the shuttle, or, alternatively, recall, call an ERT, and call.

**Comment by SonixApache** [comment]
yeah, that's fuckin' stupid

**Comment by F-OS** [comment]
Will make it so they can't be called after the point of no return for the shuttle.

**Comment by Kurfursten** [comment]
Lack of support, try again in another form if you desire

**Pull request closed without merging**
