### PR TITLE
Gives back the nuke ops last stand pill

### PR DESCRIPTION
**Pull request by ShiftyRail**
I had forgotten it
The file was written using spaces as indents, which all got converted to tabs

### CODE REVIEW

**Comment by BomberBro** [comment]
Does this given them their big tank, mask, and other pills as well?

**Comment by ShiftyRail** [comment]
No. Give me a second.

**Comment by ShiftyRail** [comment]
There, the full box is back. Vox operatives have a variant without Oxygen. Also fixed possible issues with ERT survival boxes.

**Comment by Eneocho** [comment]
On the topic of nukies, I thought you could purchase the codebreaker for 60TC (Instead of 100 as regular traitors) or any cooperative kit as nuke ops , but the option doesn't come up. The entire "Cooperative" section is unavailable.

**Comment by ShiftyRail** [comment]
That's on purpose, to prevent nuke ops from becoming vamp ops or cult ops.

**Comment by Eneocho** [comment]
> 
> 
> That's on purpose, to prevent nuke ops from becoming vamp ops or cult ops.

They should at least be able to get the codebreaker at a discount, since the plan is to nuke anyway.

**Comment by BomberBro** [comment]
What'd be the point? Nukeops start with their code for their nuke, the only uses I see are:
1. The ops plan to lose their nuke or ignore it entirely, which is dumb 
2. op leader has a nervous breakdown and refuses to give the code to anybody

**Pull request merged**
