### PR TITLE
Creates new type of asteroid boss

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
adds a larger variety of hivelord called Maria that's slower and slightly harder hitting than normal ones, with 4 times their health (300, one third of angie's) and spawns normal hivelords to attack instead of broods, with a maximum of 5 hivelords out at once to prevent spam. it's also less persistent than normal hivelords.
when dropped, instead of having a hivelord core to butcher, gives a hivelord heart, which when surgically replacing another person's heart, causes bone fractures and internal bleeding to heal over time, as well as making all forms of brute, burn and toxin healing be twice as effective. frost oil also instantly revives this kind of organ, in theme with hivelord cores themselves.

## Why it's good
adds more variety to asteroid bosses, and their loot.

## Changelog
:cl:
 * rscadd: Angie now shares her boss lair with a new arrival, Maria, replacing her on certain occasions. They have a special core which functions perfectly as a human heart...

### CODE REVIEW

**Comment by Eneocho** [comment]
Could be named "Hivelord Queen" since it spawns hivelords.
Or "María" if we go for actual names.

**Comment by Eneocho** [comment]
Make sure the hivelord heart doesn't die from being exposed to the elements (like normal organs do), or it will die and be untransplantable before the miner gets it to medical.

**Comment by SECBATON-GRIFFON** [comment]
> Could be named "Hivelord Queen" since it spawns hivelords.
> Or "María" if we go for actual names.

i'll go with the second for now until someone has a better idea.

> Make sure the hivelord heart doesn't die from being exposed to the elements (like normal organs do), or it will die and be untransplantable before the miner gets it to medical.

peridaxon actually revives dead organs, but yeah that's a good point. i'd prefer it still dying but making it possible to revive with frost oil (hivecore lore) too. sound good?

**Comment by Eneocho** [comment]
>peridaxon actually revives dead organs, but yeah that's a good point. i'd prefer it still dying but making it possible to revive with frost oil (hivecore lore) too. sound good?

Peridaxon is really hard to find, so balancing around it is not that good an idea. The frost oil doesn't save the hivecore. It stops the healing powers from decaying by freezing it. If the core died before yo injected frost oil it is dead for good. 
Not sure freezing a heart to preserve it works that well (and not many miners carry frost oil on them) either. I'd make it invulnerable to reinforce the idea that it is so strong healingwise that it can outheal the damage from being outside of a body. Frost oil reviving it kinda feels like busywork to me.

**Comment by Hinaichigo** [comment]
Nanomachines, son.

**Comment by jwhitak** [comment]
Adding more bosses? Not sure that we want to go down that road. Especially for a simple chance to replace Angie in the olde Angie lair. Make a new Vault, or rework Angie's entirely.

**Comment by Eneocho** [comment]
I'm inclined to agree with jwhitak, replacing angie in the same lair is not that good an idea. A new roid vault with fleshy outcroppings (could use the "The Hive" mission sprites) that has Maria would be better.

**Comment by pedr69** [comment]
updoot because it reduces chance for murderbone roiddrops

**Comment by Hinaichigo** [comment]
It'd be cool if the heart's sprite was bigger than other hearts and looked like this:
download (1)
b64501967b193944-600x338

**Comment by jwhitak** [comment]
The heart has a 10% to heal any broken bone per tick, and 10% to heal any internal bleed per tick. It also doubles any source of brute, burn, and toxin healing. It's pretty strong, assuming you can get the heart surgery to swap it out. I'm clearly in the minority about adding this boss in though. I just don't like the lazy chance-to-swap-out-Angie method of implementation.

**Comment by Hinaichigo** [comment]
I also agree with the 'adding alongside' rather than 'replacing' thing for a given round.

**Comment by Hinaichigo** [comment]
It might make sense to have the heart also allow healing of robotic limbs and organs.

**Comment by Blithering** [comment]
Just to doublecheck, the disease symptom that causes you to hork up organs won't start spewing these hearts now will it? Might be a bit too easy to obtain that way.

**Pull request merged**
