### PR TITLE
makes secbelt fit more small things

### PR DESCRIPTION
**Pull request by 9percents**
sec got more stuff to play with and I want belt to actually handle it all and not just pick favorites

:cl:
 * tweak: Security belt now holds more small stuff on it. Rejoice, donut munchers.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
Doubling it from 7 to 14 seems a tad much, innit?

**Comment by SonixApache** [comment]
On one hand i really want this so I can carry my entire gearset in just my belt
On the other hand, serious powercreep.

How much does this actually change? Can you show how much fits in the belt after this?
Do all the contents of the Sec Essentials box fit in it? How many tasers fit in it?

**Comment by twirling-jesters** [comment]
Bump it down to 10 and I'll give it a thumbs up.

**Comment by 9percents** [comment]
ugh, the sing and dance
anyway, the amount of tasers you can fit is the same as before

I only increased storage slots so you can only fit 7 normal-sized items like tasers, but it has place for smaller equipment such as hailers, tape, donuts, cigarette packs, pedometers, bolas, flashbangs, magazines. 7 slots feels too restrictive if you want to take more sec toys and not just tasers or glocks.

**Comment by SonixApache** [comment]
post pics of loadouts and answer all my questions please 🙂 
Also remember that, for whatever fucking reason, glocks are *small* items. So you could fit 14 glocks in your belt.

**Comment by 9percents** [comment]
you can do the same with boxes in backpacks and the amount of space inside is still finite, it's just that's going to be a belt while normal secoffs can't fit a new depocket wand or pedometer

pics, belts are stuffed to the limit
good_sec_belt
badsec_belt
glonksec_belt
also, glonks can fit into a pocket for a reason

**Comment by SonixApache** [comment]
Yeah, I ran the same tests. I think this'd be fine. Glocks just need to have their size raised. Maybe magazines as well.
And to answer my own question; the contents of the sec essentials box fit in there, along with the roundstart taser sec gets. Lacking one slot for the roundstart cuffs, but I think this is pretty decent without going overboard.
dreamseeker_2020-07-19_16-42-49
dreamseeker_2020-07-19_16-41-29
dreamseeker_2020-07-19_16-41-01
dreamseeker_2020-07-19_16-40-21
image

**Pull request merged**
