### PR TITLE
Adds common filter input function

### PR DESCRIPTION
**Pull request by ghost**
[qol]
Working example is done on the animalize() and select_loadout() procs, as well as trimming down lines on varediting, buildmode, datum creation and mass deleting in zone.
:cl:
 * tweak: Big long lists of types to choose from in animalization inputs can now instead be passed as a filter by text.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Conflicts

Please make sure this is tested too

**Comment by ghost** [comment]
Fixed conflicts

**Comment by Kurfursten** [comment]
Did you test it

**Comment by ghost** [comment]
Yep, everything works

**Pull request merged**
