### PR TITLE
One Way Access on Patient Rooms

### PR DESCRIPTION
**Pull request by falcon2346**
## What this does
Makes the patient room doors in medbay able to be opened from inside without special access in all maps aside from Synergy (as the "patient room" area is part of the hall leading to virology), Way, Packed, Deff (patients can leave these areas without access already), and the special Box variants.

## Why it's good
People don't have to break open a window if they went braindead in medbay and got shoved in a patient room now.

## How it was tested
Opened the door from outside of the patient room with access, opened it from inside without access, failed to open it from outside without access.

## Changelog
:cl:
 * tweak: Changed patient rooms to only require access from one side.

### CODE REVIEW

**Comment by MercuriusGH** [comment]
What if you need to lock up the mentally ill?

**Comment by falcon2346** [comment]
> What if you need to lock up the mentally ill?

Remove their legs.

**Comment by MercuriusGH** [comment]
what about adding door bolts buttons on the outside of patient rooms

**Comment by west3436** [comment]
DNM until #37090 is either merged or close for licensing consistency.

**Comment by west3436** [comment]
@falcon2346 weve switched to an AGPL license in a commit prior to this one - do you still wish to have this PR merged under the new license?

**Comment by falcon2346** [comment]
> @falcon2346 weve switched to an AGPL license in a commit prior to this one - do you still wish to have this PR merged under the new license?

Yeah that's fine, makes no difference to me

**Pull request merged**
