### PR TITLE
Scale oxy damage based on max health of mob

### PR DESCRIPTION
**Pull request by Hinaichigo**
This scales incoming oxy damage based on the max health of the mob. Humans, at 100 health, are unaffected by this change. A mouse on the other hand, has only 5 health; currently they almost immediately die if they climb into the wrong pipe. This scales down that damage accordingly, which seems to make more intuitive sense. Also this makes grues not get more tanky to oxy damage as they mature.
 
:cl:
 * rscadd: Oxygen deprivation damage now scales with maximum health.

### CODE REVIEW

**Comment by Irradiation** [comment]
Prepare for unforeseen consequences.

**Comment by Hinaichigo** [comment]
I'm making this as a draft while I doublecheck for the places where `oxyloss` is modified directly instead of using the proc.

**Comment by adacovsk** [comment]
> I'm making this as a draft while I doublecheck for the places where `oxyloss` is modified directly instead of using the proc.

I agree that maxHealth should be more OOP: just pass a value in `setMaxHealth()` and not worry about scaling it? Does this make sense or am I missing something. All you'd have to do is scale the modifier

**Comment by Hinaichigo** [comment]
That's what I'm thinking too. Seems to work for humans (though the UI health indicator assumes 100 maxHealth). But it seems like simple mobs might actually just funnel all damage types directly into health damage. So I might have to add some stuff there.

**Comment by WindowsErrors** [comment]
dang i was pretty reliant on this because whenever the sneedicate operatives would go shooting with one shot mouser pistols i'd just hop into the scrubbers vent (not the vent vent) and get killed within seconds before popping out onto the floor in the next room over while they still expect me to be a mouse

**Comment by Hinaichigo** [comment]
Have to debug this a little more.

**Comment by Hinaichigo** [comment]
I slightly refactored the simplemob health calculation to actually make use of `bruteloss`, `fireloss`, etc. And now simple mobs will heal oxy damage when they're back in breathable air.

**Comment by Hinaichigo** [comment]
Have to fix one bug with revive() not working.

**Comment by Hinaichigo** [comment]
This was turning too much into a refactor of simple mob health/damage code and going beyond the stated scope of this PR, so I'll revert those extra changes for this time.

**Comment by Kurfursten** [comment]
I foresee a lot of increased vault cheesing with tough bosses suffocated fast

**Pull request merged**
