### PR TITLE
puts teleport prefs under +FUN instead of +DEBUG

### PR DESCRIPTION
**Pull request by SonixApache**
i'm tired of having to VV it and this makes more sense maybe

### CODE REVIEW

**Comment by ghost** [comment]
>trial admin making a PR to elevate their power

**Comment by SonixApache** [comment]
I can literally already do everything that this verb allows, just that the prefs don't carry over to the next round.

**Comment by bathosbathtime** [comment]
The second most powerful flag has been brought down a chip.

**Comment by Exxion** [comment]
Why the fuck was it on +DEBUG in the first place?

**Pull request merged**
