### PR TITLE
Two New Guns and Buckshot

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds a couple of new guns for summon guns/adminbus/putting in vaults/et cetera.

The mahoguny, which fires a single slow-moving projectile that can bounce once and deals 30 damage, along with three fast-moving projectiles in a spread that deal 10 damage each. It can be loaded with wood planks, and holds 10 shots.

The siren, which fires globs of liquid that splash their contents onto what they hit as well as the turf of the thing they hit. The gun has two modes, it can either deal 30 damage per shot and deliver 10u of reagents to the target and its turf, or deal no damage but deliver 50u of reagents to the target and its turf. Its shots will adopt the color of the reagents they contain. Both the gun and its projectiles have the NOREACT flag, which allows for all kinds of on-hit chemical reactions. It can be loaded with any reagents, and holds 5 shots.

Also adds buckshot shells, a box of which can be ordered from Cargo in the shotgun shell crate. A single buckshot shell fires nine buckshot pellets in a small spread, each dealing 10 damage.
The shotgun shell crate itself now contains a box of each type of shell rather than 10 loose lethal shells.

Also adds a unique in-hand sprite for sawn-off shotguns, since until now they looked the same as regular shotguns when held.
Also makes the blunderbuss and railgun belt-equippable like I've been meaning to do.

The mahoguny and siren ideas and sprites are from Enter the Gungeon, not my own creation.

Addresses #8394.

### CODE REVIEW

**Comment by 9600bauds** [comment]
> It can be loaded with wood planks, and holds 10 shots.

Okay, that sounds a little gratuitous for a gun that seems like it's best use would be spamming into a room

**Comment by Shadowmech88** [comment]
What, like too many shots?
The projectiles are almost slow enough to outrun, so odds are good that you'll miss at least a couple of shots if the target's moving.

**Comment by 9600bauds** [comment]
Yeah, that's why it seems like the best use would be firing into a room/into a hallway to make it pinball around, and it might have a little too big of a magazine or too common of an ammo type which would lead into the aforementioned uses being spammable

**Comment by Shadowmech88** [comment]
> to make it pinball around

Each projectile only bounces once.

**Comment by Imagebard** [comment]
Note to self:
Close #8394 if Buckshot is merged.

**Comment by Shadowmech88** [comment]
@Imagebard 
No need, I've updated the OP to autoclose it when merged.

**Comment by NigglyWiggly** [comment]
> Gungeon guns

pls

**Comment by Exxion** [comment]
I don't think fulfills is a valid autoclose word

**Comment by Shadowmech88** [comment]
Is there a list of them somewhere?

**Comment by Exxion** [comment]
Yes, but I don't remember where
Unless it was changed or I remember incorrectly, it's most tenses of close, address, and fix

**Comment by Probe1** [comment]
research levels are too high.  balance them against something that exists so we don't have to at some future point.  otherwise I don't see anything too crazy, even if I'm not super keen on the idea.

**Comment by FudgePucker** [comment]
The siren sounds like a ton of fun, but also really broken (so I guess really really fun)

So its a gun that shoots polyacid smoke or napalm?
AWESOME.

**Comment by Probe1** [comment]
Yeah that was basically my thoughts but polyacid smoke being badly coded isn't the problem of this PR.

**Comment by FudgePucker** [comment]
Yea its not the fault of the gun.

Oh man napalm shooter would be a good replacement for old flamethrower.

**Comment by Shadowmech88** [comment]
@Probe1 
I don't think the tech levels are too high. Their combat tech level is only one point higher than that of a combat shotgun, and those can be ordered from Cargo.
Given the potential strength of these and their rarity, I don't think combat 6 is too much for them.

**Comment by Blithering** [comment]
90 brute damage from the buckshot shells point blank? Ouch.

**Comment by Probe1** [comment]
@Shadowmech88 I think that's more the case of combat shotguns being shitty pasted code from something else than thought out.  Weapon 6 is  end of the line weapon research.

**Comment by Shadowmech88** [comment]
The new guns now give combat tech 5 instead of combat tech 6.
Also this is now ready for merge as far as I'm concerned.

**Pull request merged**
