### PR TITLE
Some big Snaxi changes

### PR DESCRIPTION
**Pull request by adacovsk**
I think a common complaint about snaxi has been its size. Since Yvvel is gone, I've taken it upon myself to finish something he wanted to start

Current:
image

This PR:
image

## What this does
- Only one main entrance from each of the stations
- less meandering path between the stations
- Shorter paths to the solars
- Moves clothing vendors and closets to dorms

## Why it's good
- It's easier to know where you are going if you go out a door
- Less pathway means more interaction

## Changelog

:cl:
 * tweak: It should be easier to get around Snaxi now.

### CODE REVIEW

**Comment by gurfan** [comment]
I really hate the removal of the entrance near the paramedic station and the entrance near the mechanics workshop. Snaxi has a lot of problems but those entrances sure weren't one of them. The fact that you left the sec/med checkpoint on the northeast station after removing the entrance is also laughable.

**Comment by adacovsk** [comment]
> I really hate the removal of the entrance near the paramedic station and the entrance near the mechanics workshop. Snaxi has a lot of problems but those entrances sure weren't one of them. The fact that you left the sec/med checkpoint on the northeast station after removing the entrance is also laughable.

there are still entrances, but the idea is not to make it a main arterial path. Will move those checkpoints

**Comment by Kurfursten** [comment]
Looks crunched and ugly, and you didn't even make the ERT shuttles dock the right way. Maybe the point was to have the thrusters away from the path but that's something you can map on the shuttle itself without awkwardly landing them away from the road. The old main entrance of eng-cargo station now seems like a bizarre empty foyer off to the side because you have taken away the entrance from it, meanwhile the side entrance does not feel at all like a main entrance.

Also you left big soulless patches of no shrubs or trees

**Comment by adacovsk** [comment]
> Looks crunched and ugly, and you didn't even make the ERT shuttles dock the right way. Maybe the point was to have the thrusters away from the path but that's something you can map on the shuttle itself without awkwardly landing them away from the road. The old main entrance of eng-cargo station now seems like a bizarre empty foyer off to the side because you have taken away the entrance from it, meanwhile the side entrance does not feel at all like a main entrance.
> 
> Also you left big soulless patches of no shrubs or trees

Still a WIP, didn't want to get too far without feedback

**Comment by Kurfursten** [comment]
The biggest feedback is this: all main entrances have snow supplies and a medbay nearby. Now that you've made dorms the main entrance, the flow of people is nowhere near the medbay station or snow supplies.

**Comment by adacovsk** [comment]
> The biggest feedback is this: all main entrances have snow supplies and a medbay nearby. Now that you've made dorms the main entrance, the flow of people is nowhere near the medbay station or snow supplies.

you're right, I've updated it. IN the process of adding trees

**Comment by Kurfursten** [comment]
You left the snow supply room on the other side of the station by mechanics...

**Comment by adacovsk** [comment]
> You left the snow supply room on the other side of the station by mechanics...

I moved the coats to the dorms, but I'll move everything. I guess that would make sense

**Comment by Kurfursten** [comment]
image

**Comment by adacovsk** [comment]
Haven't updated the image, sorry Kurfurst. I can flip cargo around.

**Comment by wotisjanitor** [comment]
>tries to remove snaxi
>pr closed
>tries to ruin snaxi

**Comment by adacovsk** [comment]
I like snaxi? I just don't like getting lost

**Comment by wotisjanitor** [comment]
kek what a manlet b*tch....

**Pull request closed without merging**
