### PR TITLE
New VOX words and announcements

### PR DESCRIPTION
**Pull request by N3X15**
# Executive Summary
Added a shitload new words (see vox_sounds.dm for full list) and 6 new roundstart reminders.  This should make it easier on AIs when they try to make important announcements, and adds some newer creatures in as nouns.

Corresponds with [this](https://github.com/N3X15/ss13-vox/commit/695adb29d739c9c8c9368980599b4c1d652bb297#diff-57b2f808bc68e7c4177c337e6a5f0019R727) ss13-vox commit.

# Testing
Tested in 511.1358 on 6/23/2017 by starting as AI, then running the announcement "voxtest4 excellent".

### CODE REVIEW

**Comment by ghost** [comment]
> cracktheack.ogg

you have my vote

**Comment by kilozombie** [comment]
I probably sound like a moron, but what exactly do these do and where?

**Comment by N3X15** [comment]
AI announcement verb ("ass blast usa") and the startup reminder announcements.

**Comment by kilozombie** [comment]
Cool, thanks.
This looks really helpful. More words means more creative assblasting.

**Comment by ghost** [comment]
ready to rock?

**Comment by N3X15** [comment]
Trying to fix a pronunciation error with codeine, but I can slip that in directly later, once I get my VM to stop being a shit and freezing when I try to play sounds.

**Comment by N3X15** [comment]
Fixed codeine and did the beat I could on rogue.  Festival still has glitches sometimes, even when you explicitly tell it how to pronounce a word. 🤷‍

**Pull request merged**
