### PR TITLE
fixes #8622

### LINKED ISSUE #8622: Invisible grilles on shuttle
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 25e4b508298181d88282a40acf22e88f603125b5 
> 
> General description of the issue
> reconstructing girders on the escape shuttle makes them invisible
> 
> What you expected to happen
> deconstruct and reconstruct would give me visible girders
> 
> What actually happened
> invisible girders that are not shown when rightclicking the tile, however they still act as a wall and you cant walk through them
> 
> Steps to reproduce if possible
> smash cockpit window on escape shuttle
> wirecutter girders
> step inside
> press z with rods in hand

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #8622 

I tried to also fix issue #7023, but window code is terrible.

### CODE REVIEW

**Comment by clusterfack** [comment]
Fix this part too in rod code

```
    if(locate(/obj/structure/grille, user.loc))
        for(var/obj/structure/grille/G in user.loc)
            if(G.broken)
                G.health = initial(G.health)
                G.density = 1
                G.broken = 0
                G.icon_state = "[initial(G.icon_state)]"
                use(1)
            else
                return 1
```

**Comment by Intigracy** [comment]
k done

**Comment by Intigracy** [comment]
oh it didn't push wtf

**Comment by Intigracy** [comment]
k done

**Pull request merged**
