### PR TITLE
Adds a 90's IDM playlist.

### PR DESCRIPTION
**Pull request by slightly-floating**
Don't merge this yet as I have to add it to the media server. I already have everything tagged and downloaded. The playlist has 38 songs. The list is the following plus one song that was cut off.

Music

The song that was cut out was "Two Lone Swordsmen - As Worldly Pleasures Wave Goodbye" also, If you have a song idea you can post it below as well. Two slots left. I probably won't listen to you. Must be 90's. Must be IDM. Preferably an artist I left out that is not no name. 

:cl:
 * rscadd: There's a new juke playlist now: 90's IDM. Check it out.

### CODE REVIEW

**Comment by ghost** [comment]
GOD i wanted to do this
thank you

**Comment by slightly-floating** [comment]
> GOD i wanted to do this
> thank you

Thx.. tell me what you think of the song list. Still have room for 2 more. Preferably of artists I forgot.

**Comment by ghost** [comment]
> > GOD i wanted to do this
> > thank you
> 
> Thx.. tell me what you think of the song list. Still have room for 2 more. Preferably of artists I forgot.

pretty much nails all the big names and well known/liked stuff from back then. maybe its missing lfo or should have a lil more album variety... (swap coopers world w journey to reedham 7am mix, one of the amber ones with 444 from incunabula etc)

**Comment by slightly-floating** [comment]
> > > GOD i wanted to do this
> > > thank you
> > 
> > 
> > Thx.. tell me what you think of the song list. Still have room for 2 more. Preferably of artists I forgot.
> 
> pretty much nails all the big names and well known/liked stuff from back then. maybe its missing lfo or should have a lil more album variety... (swap coopers world w journey to reedham 7am mix, one of the amber ones with 444 from incunabula etc)

Okay. Will exchange "Slip" with "Bike". Also think I messed up with the Mu-zik track, think technically it released in 2000s. Will swap that one out too.

**Comment by Kurfursten** [comment]
Let me know when the media server is updated

**Review by Kurfursten — APPROVED** [review]

**Comment by slightly-floating** [comment]
I have posted the ZIP in the Discord and notified the relevant people. I do not know if it is in fact updated. If I could do it myself, I would.

**Comment by Kurfursten** [comment]
I followed up on this and no one ever used your 3 day expiring playlist link

**Pull request merged**
