### PR TITLE
Adds more biohazard shutters to science because only having like 3 locations with them is totally useless, like really you can just walk around it

### PR DESCRIPTION
**Pull request by SysadminJeroen**
I got annoyed at how the Biohazard Shutters in Science were inconsistent and easy to evade.
What I did was redesign some places in Science to accomodate for the Biohazard Shutters.
I think that it looks somewhat decent as some areas like Telesci and Mech Bay were challenging, criticism is welcome.
Xenobio is blocked off from Science and the rest of the station when doing the lockdown, but there are no safe way for Science to cross into the Science hallway without coming in contact with a maintenance tunnel. And Xenobio is pretty much the only Biohazard in Science, I'm wondering why their entire distro isn't separated from the outside world.

[Check the changelog for all changes in Science.](https://github.com/Jeroen52/vgstation13/blob/546af951e9711d3e14968a069811ee58a1702ae1/html/changelogs/jeroen52.yml)

Here is a screenshot of the changes, you can see shutters all over Science, as the previous ones were pretty much useless.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
There's no need to change the mech bay's entrance.
You could just put the shutters directly on top of the mech bay's airlock.

Same for Xenobiology maintenance.

**Comment by SysadminJeroen** [comment]
@Shadowmech88 I don't like how that looks. It must look consistent to what exists in Science.
I mean, I could move all existing shutters in Science on top of the doors.

**Comment by Shadowmech88** [comment]
That'd probably look better.

**Comment by SysadminJeroen** [comment]
@Shadowmech88 I'll probably start from the beginning in about an hour or so.
I will however re-add the button for the mechbay shutters and add a camera as we must always be ready to launch skynet.

**Comment by ComicIronic** [comment]
I like it.

**Comment by SysadminJeroen** [comment]
Hold on, I think that this could get a opinion.

Upvote if you want to get the shutters to be next to the airlocks.
Downvote if you want the shutters to be on top of the airlocks.

**Comment by ghost** [comment]
Thumbs down if you think using the term up vote is silly.

**Comment by ihadtoregisterforthis** [comment]
I don't think the mech bay shutters serve as biohazard block, but more like hangar doors.

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis I have found no reason why it wouldn't perform the same way as the biohazard shutters. Unless they don't block DESTROY rays.

**Comment by ihadtoregisterforthis** [comment]
They look more like flavor doors. Even more I believe they can be opened with a crowbar.

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis Under what condition do you think that they can be opened with crowbars?

**Comment by Intigracy** [comment]
When unpowered you can open them with crowbars, though you can do that with these ones too.

I don't like this because it makes it completely impossible to get in or out of science without breaking something / using disposals.

Everywhere else there's shutters used you can get around them in at least one point, engineering has maint, the bridge has the head meeting room and captain's office.

Impenetrable forts are not fun.

**Comment by SysadminJeroen** [comment]
@Intigracy I have been thinking about that when making the changes. Maybe keep the maint access in the Mech Bay without Biohazard Shutters, the Mech Bay is already a weakness anyways.

**Comment by SysadminJeroen** [comment]
Now re-doing the work to do it according to [this vote](https://github.com/d3athrow/vgstation13/pull/10400#issuecomment-223809051).

**Comment by SysadminJeroen** [comment]
Something is going wrong with GitHub and I can't upload images.
Here is an image of the shutters re-done.
Image #1

**Comment by 9600bauds** [comment]
Zoom out, press F2

**Comment by ihadtoregisterforthis** [comment]
Screenshots are dead

**Comment by PJB3005** [comment]
No they aren't. There was a bug on BYOND's side but that's been fixed.

**Comment by Probe1** [comment]
You need to leave at least one opening.  That is how all departments handle it.  Otherwise its pretty imbalanced.

**Comment by Intigracy** [comment]
Blocking xenobio maint seems excessive.

**Comment by SysadminJeroen** [comment]
@Probe1 There is a non-shutter door in Robotics.

**Comment by Probe1** [comment]
Alright that seems fine.

Drop the ginormous amount of ugly placement for shutters and just put em over the doors like everywhere else then 5/5 gud4merge

**Comment by SysadminJeroen** [comment]
@Intigracy That is where most of the trouble comes from.

@Probe1 [This is the latest revision](http://puu.sh/plMGS/0739a1a8b5.png), couldn't make a video out of it yet.

**Comment by Intigracy** [comment]
You should move the xenobio main entrance shutter up one airlock, to be at the one leading from maint.

Also you know you can embed images in github right.



```
![](http://puu.sh/plMGS/0739a1a8b5.png)
```

**Comment by SysadminJeroen** [comment]
@Intigracy I know that you can.

**Comment by Shadowmech88** [comment]
> You should move the xenobio main entrance shutter up one airlock, to be at the one leading from maint

But then Xenobio could be reached by breaking in from space.
I think the current placement of that shutter is best.

**Comment by ghost** [comment]
So, is it good for merge yet ?

I have a literal mapping fetish and this PR is cockblocking me

**Comment by SysadminJeroen** [comment]
@dylanstrategie, made the main post somewhat prettier.
Maybe it will be merged once it gets more thumbs up.

**Comment by clusterfack** [comment]
Ok, whatever. If people hate it they can change it back later.

**Comment by SysadminJeroen** [comment]
Yey.

**Pull request merged**
