### PR TITLE
Fixes transit tube entrapment

### PR DESCRIPTION
**Pull request by Exxion**
I barely have any idea what even caused it, but this should fix it.
It also makes transit tube pods dense again, but this has practically no effect on anything.

### CODE REVIEW

**Comment by Exxion** [comment]
>hotfix not merged or even commented on for two days

You forfeited any right to complain about this

**Comment by SonixApache** [comment]
oh no

**Comment by ghost** [comment]
wait, we can do that?

I've got hotfixes that have been left for a month or so, hang on

**Comment by Exxion** [comment]
Hotfixes should be merged ASAP
If you've had any open for that long you really should have complained about them sooner

**Comment by Exxion** [comment]
Wait the only open hotfix PR right now is from N3X15 and it's listed as also needing testing
You liar

**Comment by ghost** [comment]
gotcha. But still, could've at least hollered at us in code-talk or the tower

**Pull request merged**
