### PR TITLE
fixes a runtime with visible_message/on_see

### PR DESCRIPTION
**Pull request by JustSumBody**
Whoops

### CODE REVIEW

**Comment by ComicIronic** [comment]
I'm more worried that this is at all possible. When is this runtime happening?

**Comment by JustSumBody** [comment]
Noticed it when I was testing my mimegun PR, it was throwing an error trying to call null.on_see when I threw away my starting gloves to equip the new ones. On test_tiny if that helps any.
Going back to it now, I can't seem to recreate it or find any of the runtimes in the live server. Maybe it was just an issue with one of my earlier versions of the PR?

**Comment by unid15** [comment]
I see this runtime quite often when testing stuff on a local server

**Comment by clusterfack** [comment]
Better served by putting some debug stuff into virtual hearers, like having them record the typepath of their attached and then if something like this happens output that to world.log

**Comment by JustSumBody** [comment]
I don't follow, like a try-catch block?
Can you give me an example so I can shamelessly copy paste it?

**Comment by PJB3005** [comment]
What Cluster's trying to say is that this only silences the error, it doesn't actually fix it.

What you should do is put some logging in so we can debug what caused a virtualhearer to not have something attached but still be on the map.

**Pull request merged**
