### PR TITLE
Special tab QOL for admins

### PR DESCRIPTION
**Pull request by gbasood**
Outputs a message to msay window AKA special tab when an admin starts to reply to:
 - Centcomm messages
 - Syndicate messages
 - Prayers
 - Faxes

This does of course check the admin's prefs to see if they want that message in the special tab or in chat, but it doesn't implement a new pref, so it uses the catch-all pref for having the special tab enabled at all or not.

I removed the Subtle Message HREF from prayers in favor a RPLY link that is basically just the same thing but with the message to admins on starting a reply.
🆑 
 * tweak: Admins will now see when another admin starts to reply to a fax, prayer, centcomm or syndicate message, in order to hopefully avoid duplicate replies from separate admins.
 * tweak: Admins will also see replies to prayers/faxes/centcom or syndie messages, thanks to Intigracy

### CODE REVIEW

**Comment by ComicIronic** [comment]
Might be worth adding cancellation messages at the same time.

**Comment by gbasood** [comment]
I feel that'd get a bit spammy, but if admins want it I can add it.

**Comment by gbasood** [comment]
Don't merge until @Intigracy makes fax responses show as links instead of outputting hte entire fax's contents to msay

**Comment by Intigracy** [comment]
Well, that's done.

I'll do a quick test.

**Comment by Intigracy** [comment]
Adding some formatting.

**Comment by Intigracy** [comment]
I also tested it without the special tab and it works, but didn't feel like taking more screenshots because without the special tab chat is just a mess.

**Pull request merged**
