### PR TITLE
Buffs fireball

### PR DESCRIPTION
**Pull request by unid15**
https://dl.dropboxusercontent.com/u/24942522/fireball.ogg

100% tested

### CODE REVIEW

**Comment by 9600bauds** [comment]
[Memes]

**Comment by Konater** [comment]
god damn it

**Comment by ihadtoregisterforthis** [comment]
remove sound REMOVE SOUND

**Comment by Imagebard** [comment]
>Green and Purple

Perfect for this meme PR

**Comment by Probe1** [comment]
thanks doc

**Comment by unid15** [comment]
If this is too memey, here are some options:

1) Only play the sound if the wizard is hallucinating
2) Only play the sound if the wizard is wearing Pitbull outfit and hair
3) Remove the music
4) Only play the sound for level 5 fireballs, to reward wizards who put 5 skillpoints into that useless spell

**Comment by ComicIronic** [comment]
I'd do above 1 point for the sound.
That was it's an investment, but not too much of one.

**Comment by AutismSpider** [comment]
@ComicIronic even taking one point of this shit spell is an invetment

**Comment by ghost** [comment]
This won't get annoying fast

**Comment by clusterfack** [comment]
It's not even merged yet and I already find it annoying

**Comment by clusterfack** [comment]
I don't really know what way to restrict it but it definitely needs some way

**Comment by ComicIronic** [comment]
Sound play cooldown?

**Comment by Hoshi-chan** [comment]
Uh, isn't this kind of a really long sound to play for a spammable instant cast spell?

**Comment by 9600bauds** [comment]
Yes but it's a meme so that makes it OK

**Comment by Shadowmech88** [comment]
If spam is an issue, maybe make it so that each cast only has a certain % probability to play the sound.

**Comment by DeityLink** [comment]
"oh hey, maybe someone finally made fireballs act like fireballs instead of bombs"
*> open the PR
*> It's just memes
"I don't know what I expected"

**Comment by AutismSpider** [comment]
@DeityLink if you want fire ball to act like real one just port over TG one

Any thing it slams into starts a massive fire even on mobs

**Comment by DeityLink** [comment]
> @AutismSpider ...just port...

REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Or we could come up with our own ideas, our own sprites, our own way to code it.
I'm not even saying that the way their fireballs work isn't good, I'm saying that I'm a coder because I like to code, I don't like to copy and paste.

**Comment by ComicIronic** [comment]
http://www.joelonsoftware.com/articles/fog0000000069.html

**Comment by clusterfack** [comment]
The best coder is a good thief

**Comment by Intigracy** [comment]
But TG coders aren't the best coders CF.

**Comment by clusterfack** [comment]
But they steal from the best, which makes them the best by proxy

**Comment by Intigracy** [comment]
Can't believe you just said that.

**Comment by clusterfack** [comment]
Reinventing the wheel is for lunatics

**Comment by Intigracy** [comment]
Reinventing cars to be electric is for millionaires.

**Comment by SangriaMonkey** [comment]
:fire: :fire: :fire: 
:eggplant: :eggplant: :eggplant:

**Comment by ComicIronic** [comment]
No but really this needs a cooldown and a shorter sound clip.

**Pull request closed without merging**
