### PR TITLE
update turret targeting to be less expensive

### PR DESCRIPTION
**Pull request by nervere**
4 view(7) calls -> 1 view(7) call

## Why it's good
better server performance when ruins like this spawn:
image

[system][performance]

### CODE REVIEW

**Comment by Exxion** [comment]
Have you checked this with a profiler? There are some internal BYOND optimizations I believe you miss out on with this change. Those optimizations *probably* won't be enough to make the original code faster than the new code, but it's good to check.

**Comment by Securitymain** [comment]
But will this spawn the turrets naked?

**Comment by nervere** [comment]
Changed to `is_type_in_list()` per Exxion's suggestion for better performance. As for internal optimizations within, say, `view()`, I don't know of any. I read the documentation on the proc and all related procs and couldn't find anything relevant.

I still need to test this and actually profile it.

**Comment by Kurfursten** [comment]
Is this WIP? It looks fine, although I suppose the typecheck is implicit in check_target anyway

**Comment by Kurfursten** [comment]
?

**Comment by nervere** [comment]
@Kurfursten Sorry, I've neglected github for a while now. I didn't mean to keep you hanging.

I tested it now for 5 minutes per version of the code and it's only ~5% faster. Maybe it'd be better if I ran it for longer since the cache takes a while before you see notable performance improvements, but whatever. It's cleaner code in any case. Not WIP by any means so I'll remove that tag.

**Pull request merged**
