### PR TITLE
R-UST fuel injector overhaul

### PR DESCRIPTION
**Pull request by DamianX**
~~Needs changelog, wiki update, testing of the fuel port.~~
Tested.
Addresses some of #16190

it's mostly a UI/QoL + code style change, with the core functionality staying intact

image

:cl:
 * tweak: The R-UST fuel injector no longer requires cable coils in construction. It can now be deconstructed, and its circuit board is available from the circuit imprinter.
 * tweak: The R-UST fuel injector has a new UI.

### CODE REVIEW

**Comment by Kurfursten** [comment]
What do you know, there was a build recipe after all. It just wasn't in constructable_frame for reasons unknown.

For maintainability it might be best to kill Rust/circuits and move those to the rest of the designs

**Comment by Kurfursten** [comment]
As a reminder, under **boards/machine_engie.dm**, look up the  /datum/design/rust_injector

It builds the wrong board

**Comment by DamianX** [comment]
But this PR addresses that?

**Comment by Kurfursten** [comment]
I missed that file change. 👍

**Comment by ghost** [comment]
god bless, i remember the pain of convincing R&D i needed specific parts for the R-UST machines one round, it was faster to just order the things

the new UI is good too, the old one was a bit ech

**Pull request merged**
