### PR TITLE
castlestation: gives people the new, weak .22 gun instead of powerful real-guns

### PR DESCRIPTION
**Pull request by gurfan**
Toned-down alternative to #28116

Rather than give everyone their own unique (and strong) guns, gives everyone the brand new .22 pistol that does 10-15 damage per shot. (Science gets the laser version, because lasers are high-tech)

Departments still get their access-locked gun cabinet with 4 pistols. 10 magazines are on a nearby table.
Department-less jobs and service jobs don't get a cabinet but they still get 1 pistol+2 magazines for each job slot.
Assistants get nothing.
The clown gets a spray bottle instead any gun.
Heads of staff (including the QM) still get a stun revolver in their respective lockers.

:cl:
 * rscadd: Castlestation: All jobs (excluding assistant) have access to a weak pistol they can use for self defense.
 * rscadd: Castlestation: Heads of staff (including the Quartermaster) get a stun revolver in their locker for self defense.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
>assistants get nothing

**Comment by gurfan** [comment]
>implying they won't steal the guns from the other departments

**Comment by ghost** [comment]
slightly less highlander 2.0, I like it

**Comment by Blithering** [comment]
I'd say give everyone a second internals box with a .22, two spare mags and a note that they're on their own, rather than leaving it up to departmental lockers

**Comment by TGFH** [comment]
>QM
 >Head of staff
Bad meme.

**Comment by tayachiya** [comment]
Why not give the clown a water gun instead?

**Comment by Kurfursten** [comment]
I am going to give this until 7 days [4 more] to get a better radio than the original; if it doesn't, then we'll just go with it, since more people seem to prefer it

**Pull request closed without merging**
