### PR TITLE
Poop.

### PR DESCRIPTION
**Pull request by ComicIronic**
You now have a chance to poop when you fart.
You can throw poop around and make a mess!

### CODE REVIEW

**Comment by N3X15** [comment]
Please die.

**Comment by ririchiyo** [comment]
ripip comic 2015-2015.

**Comment by PJB3005** [comment]
this PR took more time to code than it was worth

**Comment by Probe1** [comment]
how can you say you love ss13 if you won't even poop

**Comment by PJB3005** [comment]
holy shit (see what I did there?) this was the 3000th PR

**Comment by Praecordia** [comment]
simply epic

**Comment by Iamgoofball** [comment]
:-1: @heredth did it better

**Pull request closed without merging**
