### PR TITLE
knifeboot

### PR DESCRIPTION
**Pull request by MadmanMartian**
It's some nice lace-up shoes, with a knife inside. Damage based on the stats of a scalpel.

Idea and sprite courtesy of @Blithering 

:cl:
* rscadd: Adds new traitor shoes with a toggleable knife, for the dapper IAA who wants to kick something

### CODE REVIEW

**Comment by Irradiation** [comment]
If it's just using scalpel damage, then I hope the TC cost isn't more than 5.

**Comment by MadmanMartian** [comment]
look for yourself, it's 4.

**Comment by ghost** [comment]
Doesn't kicking have a longer cooldown? For 10 force too, it could use to be a little better I think

**Comment by MadmanMartian** [comment]
That's on top of the regular kick damage.

I was able to crit a guy in 7 kicks

**Comment by AutismSpider** [comment]
wait does strong legs mut  up kick damage?

**Comment by Dacendeth** [comment]
Knife boot + hulk + gyro, murderous kicks.

**Comment by Probe1** [comment]
Gyro?

**Comment by MadmanMartian** [comment]
Drink that seems to make you spin

**Comment by Probe1** [comment]
I know about the gyro drink.  In the context it made it sound like it increased kick power and I was confused.

**Comment by Blithering** [comment]
@Probe1  I think it does, at least it changes the kick text to a roundhouse kick

**Comment by Probe1** [comment]
That's really cool.  I'd forgotten or didn't know.

**Pull request merged**
