### PR TITLE
changes to packedstation.dmm

### PR DESCRIPTION
**Pull request by bthomas2**
:cl: Packed: minor tweaks

packed3
packed1
packed2

### CODE REVIEW

**Comment by Irradiation** [comment]
Mind putting an a "before" image so we can see the difference?

**Comment by bthomas2** [comment]
all I did was add a floorpill spawner, painting, a glass ashtray, NT pen for cap, 2 zippos, 2 cigars, a gold coin, and moved a matchbox

**Comment by Exxion** [comment]
You can click the checks tab above and click mapdiffbot to see the diff

**Comment by bthomas2** [comment]
oops

**Pull request closed without merging**
