### PR TITLE
Remove Alllights global list

### LINKED ISSUE #33192: lights dont turn back on immediately when you replace a bulb
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
fd808d68d314904b39ca913c8f692e1c5eba8f72

### PR DESCRIPTION
**Pull request by adacovsk**
Stupid global list that is not necessary, replaced the single admin use with something just as good

## What this does
- Removes `alllights` global list and replaces functionality where used

## Why it's good
- Reduces init by a negligible amount
- gets rid of a useless global list
- Closes #33192

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
It's technically less optimized than just adding every new light to a global list and referring to that list because searching for things in the entire world is a drain. Compare "refer to a list of maybe a hundred or two hundred objects that are added and removed when they spawn and get destroyed respectively" to "search the entire world which contains thousands and thousands of different units minimum every time you want to do something with that".

**Comment by adacovsk** [comment]
> It's technically less optimized than just adding every new light to a global list and referring to that list because searching for things in the entire world is a drain. Compare "refer to a list of maybe a hundred or two hundred objects that are added and removed when they spawn and get destroyed respectively" to "search the entire world which contains thousands and thousands of different units minimum every time you want to do something with that".

it takes negligible time to run still with this change and it's almost never used anyway

**Comment by ghost** [comment]
it takes like 5 seconds to modify all light sources with sdql so there's no reason to maintain a global list which needs to constantly add and remove sources for something that happens maybe once every few rounds

**Comment by ShiftyRail** [comment]
This will amount to precisely nothing. A single list is not what causes overhead. Please use the profiler if you're looking for stuff to optimise rather than trying random things or copypasting TG ill-conceived microchanges.

**Comment by Kurfursten** [comment]
I'm going to close this just because I hate `in world`. Someone stop me I've gone mad with power.

**Pull request closed without merging**
