### PR TITLE
More OpenDream Lints

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Addresses more OD errors found while making #37149. OD HATES empty else statements!!

## Why it's good

Makes the linter stop yelling at me.

## How it was tested

0%

No changelog as this is literally just adding null to empty else branches

### CODE REVIEW

**Comment by ike709** [comment]
> OD HATES empty else statements!!

You... you realize you're the one setting it to an error, right?

> #pragma EmptyBlock error

in https://github.com/vgstation-coders/vgstation13/pull/37149/files

OpenDream doesn't even emit anything for empty blocks by default.

**Comment by ike709** [comment]
Also... Why don't you just remove the unnecessary `else` blocks entirely?

**Comment by west3436** [comment]
> > OD HATES empty else statements!!
> 
> You... you realize you're the one setting it to an error, right?
> 
> > #pragma EmptyBlock error
> 
> in https://github.com/vgstation-coders/vgstation13/pull/37149/files
> 
> OpenDream doesn't even emit anything for empty blocks by default.

Oh lmao



> Also... Why don't you just remove the unnecessary `else` blocks entirely?

Laziness 

Looks like this can be closed then with some tweaks thanks!

**Comment by west3436** [comment]
Not necessary

**Pull request closed without merging**
