### PR TITLE
Adds kicks and bites

### PR DESCRIPTION
**Pull request by unid15**
PROGRESS: [===========](100%) **Needs [NFD]**
- Humans now have a "attack_type" variable. It determines how they interact with the outside world while on harm intent
- Possible values: ATTACK_BITE, ATTACK_KICK, NORMAL_ATTACK
- It's possible to switch between the modes using these two new beautiful buttons on the HUD. Middle clicking them, or clicking them while holding alt/shift/ctrl will reset attack type to NORMAL_ATTACK. Clicking on the currently active button also does that
- Hotkey for kicking: **5** / **CTRL + 5**. Hotkey for biting: **6** / **CTRL + 6**

- TL;DR:
- Kicking does more damage, stuns less often, has 2x the attack delay. Damage doubled when attacking lying targets. New special magboot attack that takes 3 seconds to prepare and deals 40 damage.
- Biting does slightly more damage, doesn't stun at all, gets stopped by almost any armor.
- Vox have talons and beaks, so they're more effective with these attacks.
- Everything can be kicked

---
- **KICKING**
- Vending machine kicking now utilizes this (must have kicking enabled to kick it)
- You can kick almost everything on the station http://puu.sh/neKwP/4b50aa9cce.png . Only a few objects respond to kicks, currently. Kicking windows / foam / windoors / etc still damages them. Kicking an unanchored structure / machine (beepsky included :cop:) will send it back a few tiles (more with hulk and strength mutation) http://puu.sh/neS9g/9d34b74fe1.gif
- Kicking an item sends it flying
- Kicking a table flips it
- Kicking somebody does 0-7 damage (compared to punch's 0-5), but has 2x the delay and 1/2x the chance to stun (stuns last slightly longer, however)
- Kicking somebody while they're down turns the attack into a stomp, dealing double damage and halving their armor protection
- Kicking somebody while grabbing them sends them flying in the direction you're facing. Distance scales with strength
- Some shoes (SWAT shoes, combat boots, jackboots) slightly increase kick damage (by 3).
- While wearing activated magboots, a special finishing move can be done by standing on your victim and stomping on him. This finishing move takes **3** seconds to complete (during this delay your magboots are turned off), does ~40 damage IN TOTAL and creates a satisfying splat. Vox magboots aren't really magboots so they can't do that.
- Vox deal 1-6 more kick damage while not wearing shoes, on account of having talons. Hulks get 3 bonus damage and increased stun chance.
- Must have both of your feet to kick. **Can't kick while restrained** for gameplay purposes

---
- **BITING**
- Drinking blood as a vampire now utilizes this (must have biting enabled to drink)
- Biting a piece of food/a cockroach = eating it
- Biting somebody does 1-5 damage. Armor has 3000% bonus versus bites, so it's almost impossible to bite somebody in a hardsuit. Having a beak increases damage by a flat 4, and significantly lowers armor protection. http://puu.sh/neK8b/653954abfc.png shows armor's effect on bites
- Must have at least two teeth or a beak to bite. Can't bite with a mask on, unless you're a vampire. **Can't bite while restrained** for gameplay purposes

---

minor spoiler features not in the changelog
- [Hidden spoiler feature](It's impossible to bite silicons unless you're hallucinating. If you are hallucinating, you bite the silicon and then lose some of your teeth.)
- [Hidden spoiler feature](Kicking a non-emagged arcade has a chance of messing up the player's and the enemy's stats)
- [Hidden spoiler feature](Kicking while under effects of gyro tea turns the attack into a roundhouse kick, adding 0-4 bonus damage)

### CODE REVIEW

**Comment by SonixApache** [comment]
:+1: for magboot stomping

**Comment by ghost** [comment]
There needs to be a hotkey for something like this.

**Comment by ghost** [comment]
pun pun punting soon?

**Comment by Imagebard** [comment]
Remember that kicks with jackboots and combat boots need to TURN UP THE HEAT too.

**Comment by LordMyroc** [comment]
PUT THE BOOTS TO HIM, MEDIUM STYLE

How deadly is kicking and biting? Will certain races have deadlier kicks/bites than others?

**Comment by Exxion** [comment]
Make sure to make vox boot stomping less deadly than magboot stomping
Maybe just make it deal normal damage but with some sharpness

**Comment by gbasood** [comment]
> Middle clicking them, or clicking them while holding alt/shift/ctrl will reset attack type to NORMAL_ATTACK.

Why not just make it so clicking on the active attack type resets them to NORMAL_ATTACK? I feel like most players will have a hard time figuring out how to reset the attack type without reading the changelog, which in the long run is going to painful.

**Comment by PJB3005** [comment]
Holy shit yes :+1:

**Comment by PJB3005** [comment]
Needs to have the vamp change in the changelog though.

**Comment by Shadowmech88** [comment]
> or clicking them while holding alt/shift/ctrl will reset attack type to NORMAL_ATTACK

But alt+click is the hotkey for handing over an item, shift+click is the hotkey for examining, and ctrl+click is the hotkey for dragging. It doesn't make sense for these to reset something related to attacking.

**Comment by Imagebard** [comment]
Better idea: Those reset when you get out of harm intent, or when you simply click on the button to turn them on again.

**Comment by Exxion** [comment]
None of them do anything to UI elements, though

**Comment by PJB3005** [comment]
@Shadowmech88 alt is the general "special interaction" button, a lot of things have actions bound to alt.

**Comment by unid15** [comment]
@Shadowmech88 the point is that you hold down any of these (easily accessible and useful, chances are you're already hovering over them) keys and click on these buttons to reset.

@gbasood cool idea thank you!

Also preview of some of the features (16.5 MB image warning) http://puu.sh/ndZ3f/9b98a1fcfa.gif

**Comment by Exxion** [comment]
Two kicks to crit?

**Comment by unid15** [comment]
I edited my size to 100, forgot to mention that. Normal kicks deal 0-9 damage + shoes, stomps deal 2x that

**Comment by Exxion** [comment]
Vox dealing more kick damage without wearing shoes when?
(Talons)

**Comment by unid15** [comment]
now

**Comment by gbasood** [comment]
I think there's a better way to handle how you're handling attack type changes as it is, as well. Will comment on lines

**Comment by gbasood** [comment]
Wow github handled that poorly but okay

**Comment by ghost** [comment]
Can you kick/bite when cuffed? Are there checks for being muffled when biting, or legcuffed when kicking?

**Comment by unid15** [comment]
> kicking or biting when cuffed

That'd be kinda annoying for security guys

I'll add checks for the rest, good catch @DrCelt

**Comment by Imagebard** [comment]
>Arrest someone
They start kicking me while they're cuffed

This is just like Lifeweb.

**Comment by ghost** [comment]
@unid15 Security have stuns for a reason!

**Comment by AutismSpider** [comment]
no turns into sec stun batoning them into crit for kicking them

**Comment by ghost** [comment]
@AutismSpider muh realism

**Comment by unid15** [comment]
@DrCelt why don't we implement table climbing as well surely I'll be realistic

**Comment by ghost** [comment]
@unid15 But our tables are extra slippery, didn't you know?

**Comment by ghost** [comment]
> 2 mag boot stomps to crit

Now I'd argue for removing quickchokes because instant tabling with 2 magboot headstomps will murder anything.

In fact this will make magboots the strongest melee weapon readily available, provided you stun or push your opponent. Basically a hands free executioners sword with most likely less cooldown.

**Comment by Exxion** [comment]
Clusterfack tried to remove quickchokes but something fishy went on

**Comment by Exxion** [comment]
And @TermedClepe
Crit is 100 damage, so four magboot stomps

**Comment by Imagebard** [comment]
>Four magboot stomps

Still, holy fuck.
Also, jackboots are just a flat +3 to kick/stomp damage?

**Comment by ghost** [comment]
Curbstomping shouldn't do damage when someone's on a table

**Comment by Exxion** [comment]
Stomping _doesn't_ do damage when someone's on a table, but you can just table them and then pull them off

**Comment by ghost** [comment]
@Exxion

2 stomps, because one is 30 flat bonus from magboots + double normal stomp damage which I'm guessing is 10+, so nearly 50 in one stomp. Rest you'll bleed / suffocate in moments.

Also this isn't even addressing the fact that even if it was 'just' 30 damage, it would break bones and cause internal bleeding in single stomp.

**Comment by Exxion** [comment]
I'm pretty sure 30 damage is how much they deal on stomp in total
It's specially-coded

**Comment by unid15** [comment]
How about this
- The magboot stomp takes 4 seconds to complete, can't be performed on a table and must be done while standing on your victim
- During the magboot stomp, magboots are disabled
- Damage lowered to 20

@Exxion nah it's 30 damage on top of the normal stomping damage (2-18)

**Comment by Imagebard** [comment]
>4 seconds to complete

1 second is longer than you think, 1 minute is shorter than you think.

**Comment by Exxion** [comment]
Oh then yeah Termed is right that it's a bit ridiculous
But putting in a delay long enough that someone just pushed down can't be executed like that makes it much better

**Comment by ghost** [comment]
4 seconds is ridiculously long. I think even 2 seconds would be enough.

**Comment by ghost** [comment]
What if I turn magboots back on during stomp channeling?

**Comment by unid15** [comment]
Then you perform an ordinary stomp without the bonus damage

**Comment by Exxion** [comment]
Perhaps the text for the vox boots should be different because they don't actually involve any magnets or power

**Comment by Exxion** [comment]
That works too

**Comment by CptWad** [comment]
Punting certain machines/structures
>Punting a nuke off the station
>kicking a closet or crate down a hall
>Kicking portable atmospherics and canisters
>kicking a welded door and breaking your foot
>Kicking fuel tanks at people
>Make it so you have to have kick mode on to kick vending machines
>You can now kick borgs to send them back a few tiles
>Kicking tables will flip them
>You can now kick beepsky. He won't like it


For biting
>biting dead and small vermin causes you to devour them like the fucking monster you are
>You can bite cable coil to electrocute yourself horribly

thats all I got for right now
generally just add it so you can kick machinery/structures that can be pulled or pushed around

**Comment by Exxion** [comment]
You do have to be set to kick to kick machines now though

**Comment by CptWad** [comment]
Oh I missed that

**Comment by ghost** [comment]
Can you bite while restrained? As in security cuffs you and you start biting their legs off like the greyworm you are.

Same for kicking, since your legs are not restrained.

**Comment by Exxion** [comment]
Your legs aren't restrained while cuffed, but you apparently lose control of them because you cannot escape from being pulled
Also a shoeless vox on kick can deal up to 15 damage and a shoed anyone else up to 12 so maybe don't allow that
I don't see any problem with letting them bite while cuffed though

**Comment by unid15** [comment]
Do you guys really want handcuffed retards running around the brig and biting everybody? Or having to waste all of your stun baton's charge while carrying Griff McGray to security so that he can't bite your ass off?

**Comment by Exxion** [comment]
How much damage do bites do?

**Comment by Kitfox88** [comment]
@unid15 
This just means we add Silence of the Lambs style full body restraints and handcart systems and shit. :+1:

**Comment by ghost** [comment]
@unid15

Of course not, but having an excuse to harmbaton would be fun. Jokes aside, it's a bad idea to allow them to harm people while cuffed.

**Comment by AutismSpider** [comment]
@TermedClepe Good excuse harmbaton/kick all there teeth out if any thing per bite they do hell even let the clown join in on this

Clown kicking/biteing people makes a sound right?

**Comment by Shadowmech88** [comment]
@unid15 
Do you have it check for whether or not the person has any teeth left before letting them bite someone?

**Comment by FatBaldBastard** [comment]
Please remember to include that once you have no teeth you can't bite. Also can't bite if muzzled. Especially nice if you can't bite while cuffed.

**Comment by Zth--** [comment]
:+1: great feature
By the way make the bite less powerful for each tooth missing.

**Comment by ihadtoregisterforthis** [comment]
How does this affect other mobs and interaction with them?
Will it be possible to kill slimes, manifested ghosts, spiders, festivus poles and cockroaches by biting them? Will Monkey rounds include infection by stomping? How about biting through full head helmets or kicking without legs from a wheelchair?
Wouldn't all of that be a bit silly?

**Comment by Kitfox88** [comment]
start age reduces number of teeth when

**Comment by AutismSpider** [comment]
oh good if this gets in monkeys with hulk can kick walls down and shit pack of hulk out monkeys in grey suits and gas mask hulk kicking the shit out of people it will be greet.

need update horror mode ling stuff for this to being one by one makes you go flying into walls and shit adds more damage to its hits

**Comment by unid15** [comment]
@AutismSpider only humans can bite/kick right now. I'll refactor monkey unarmed combat later

**Comment by unid15** [comment]
@ihadtoregisterforthis yeah you can bite simple animals to death. Bites are stopped by practically any armor, and kicking requires you to have both of your feet.

@Exxion 1-7, compared to punches 0-9

**Comment by unid15** [comment]
Added hotkeys

Pretty much ready. Most of the bugs have been fixed, there's nothing gamebreaking left in

**Comment by IratePirate** [comment]
This sounds awesome.

**Comment by Imagebard** [comment]
Kicking should deal more damage than regular punching if it has double the delay. Just a thought.
Unless it deals extra stun chance already? I don't think I'm keeping track.

**Comment by unid15** [comment]
actually I had the punch damage wrong

It's actually 0-5, so I lowered kick damage to 0-7 and bite damage to 1-5.

The tradeoff for kicks is that they stun less often (punch = 1/12, kick = ~1/24) and have more delay, and bites don't stun at all + you can't bite while wearing a mask (unless you're a vampire)

**Comment by ghost** [comment]
Holy a million commits
Compress them nerd

**Comment by clusterfack** [comment]
Yes please squash

**Comment by gbasood** [comment]
Squash then we'll get a NFD label in

**Comment by unid15** [comment]
Alright squashed

**Comment by Exxion** [comment]
absolute madmin

**Pull request merged**
