### PR TITLE
fixes being unable to force meteor-mode mid-round

### PR DESCRIPTION
**Pull request by ghost**
Fucks sake dylan

### CODE REVIEW

**Comment by ghost** [comment]
took you a minute there, PJB bot

**Comment by Exxion** [comment]
There are no webhooks for when someone posts a reaction, so it just has to periodically check for them

**Comment by SonixApache** [comment]
👍 bugfix

👎 meteors

**Comment by ghost** [comment]
I don't believe this is intended functionality, the actual bug here is being able to force meteor-mode at all

**Comment by FudgePucker** [comment]
How do you even meme so hard you fuck up this badly?

**Comment by Exxion** [comment]
That's also just about the worst way to make a confirmation dialog

**Pull request merged**
