### PR TITLE
Shattered statues now gib instead of dust occupants

### PR DESCRIPTION
**Pull request by Intigracy**

### CODE REVIEW

**Comment by Imagebard** [comment]
Okay just one question, why would it gib instead of dusting?

**Comment by Intigracy** [comment]
Go find a statue and hit it with something hard. Chunks fall off, it doesn't turn to dust.

**Comment by Imagebard** [comment]
I mean, are they flesh gibs?

**Comment by Intigracy** [comment]
Yeah, after you shatter the statue it stops being a statue and just gives you the fleshy gibs.

It's like making the cooldown happen immediately, except you're dead!

**Comment by ihadtoregisterforthis** [comment]
But why?

**Comment by Intigracy** [comment]
So you're not screwed completely.

**Comment by Imagebard** [comment]
>Flesh to Stone
>Statues give flesh gibs

Really now?
Can't you wait till someone ~~sprites it~~ resprite the default gibs or is this change being made so you can retrieve the patients brain?

**Comment by Intigracy** [comment]
You do know that flesh to stone turns you to stone for a limited time, and then turns you back to flesh, right?

This just makes it so breaking the statue expedites the process. And you end up in pieces instead of alive.

**Comment by clusterfack** [comment]
It's just turning your flesh to stone not making you entirely to stone, I think

**Comment by FudgePucker** [comment]
Hell statue spell seems broken and seems like ei nath 2.0, now you have to bash it some edition.

At least this means you can fix Humpty Dumpty after he runs into a murderboner wizard and put him back together.

**Pull request merged**
