### PR TITLE
Vox specific Mask/Glasses shaped to Vox head

### PR DESCRIPTION
**Pull request by zxpr0jk**
wip_balaclava vox_ducktor vox_goggles vox_sterile

Changed four sprites to better fit Vox anatomy.
- Balaclava
- Plague Doctor
- Welding Goggles
- Sterile Mask

### CODE REVIEW

**Comment by ghost** [comment]
You did it!

Gonna need some pictures though

**Comment by zxpr0jk** [comment]
correction_east
correction_north
correction_south
correction_west

**Comment by clusterfack** [comment]
You may want to blow up those pictures

**Comment by 9600bauds** [comment]
you-did-it

**Comment by zxpr0jk** [comment]
wip_balaclava

I hate gimp

**Comment by Shadowmech88** [comment]
> not using Paint.NET

**Comment by zxpr0jk** [comment]
vox_ducktor vox_goggles vox_sterile wip_balaclava

**Comment by Shadowmech88** [comment]
If you've changed other masks, you should update the PR's title/description to reflect that.

**Comment by KasparoVy** [comment]
Hey man, looks like your east and west sprites for the plague doctor mask are facing the opposite directions in the file there.

Awesome work by the way, looks pretty dope.

**Pull request merged**
