### PR TITLE
Congratulations on making the switch to AGPLv3! Here's the required license notices.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Welcome to the future of open source! Make sure to read up on the license here:
https://www.gnu.org/licenses/agpl-3.0.en.html

### CODE REVIEW

**Comment by TheFriggenSawbones** [comment]
fuck you and die

**Comment by clusterfack** [comment]
You should read it yourself genius

>13. Remote Network Interaction; Use with the GNU General Public License.

Notwithstanding any other provision of this License, if you modify the Program, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software. This Corresponding Source shall include the Corresponding Source for any work covered by version 3 of the GNU General Public License that is incorporated pursuant to the following paragraph.

Notwithstanding any other provision of this License, you have permission to link or combine any covered work with a work licensed under version 3 of the GNU General Public License into a single combined work, and to convey the resulting work. The terms of this License will continue to apply to the part which is the covered work, but the work with which it is combined will remain governed by version 3 of the GNU General Public License.

**Comment by SysadminJeroen** [comment]
GPLv2 is much more suitable for /vg/station.

**Comment by ComicIronic** [comment]
GPLv3 only - tyrant devices go home.

**Comment by ComicIronic** [comment]
"This Corresponding Source shall include the Corresponding Source for any work covered by version 3 of the GNU General Public License that is incorporated pursuant to the following paragraph."

Means that any GPLv3 code that runs alongside the AGPLv3 component has to be released along with it when the user connects over a network.

**Comment by ComicIronic** [comment]
This is relatively easy to avoid - we have to take out a few procs that were added by Remie for TG (and then reimplement them ourselves), or just ask for a relicense.

**Comment by SysadminJeroen** [comment]
@ComicIronic That means RIP secret repo.

**Comment by ghost** [comment]
yeah literally just take it out of the goon leak, have that code done as cc-by-nc with sharealike and just shut this guy up already

**Comment by Intigracy** [comment]
@Iamgoofball fuck off

**Comment by Jalleo** [comment]
You have to force remove the history of this though. Otherwise it still technically exists. And that means a rebase.

**Comment by clusterfack** [comment]
I wont tolerate this bikeshedding. If we're going to be technical the code of EVERY current open source codebase should be CC BY SA just like Goon, since the original r4407 was illegally released as GPLv3, when Goon itself was CC BY SA.

**Comment by clusterfack** [comment]
Unless you guys plan to say that every code to every codebase is actually -what it really should be- CC BY SA just like Goon's license was when r4407 was released. Then this bullshit is going to stop.

**Comment by ghost** [comment]
Licences actually mean precisely nothing in SS13. You're literally arguing about nothing.

**Pull request closed without merging**
