### PR TITLE
Fixed parallax not looping more than once

### PR DESCRIPTION
**Pull request by JMWTurner**
Something I noticed yesterday while drifting aimlessly through space.
- [x] tested

### CODE REVIEW

**Comment by PJB3005** [comment]
@clusterfack you should review this since you wrote it.

**Comment by clusterfack** [comment]
You should change it before this loop then, in the parallax offset portion, so it isn't doing 4 while loops for each parallax object

**Comment by JMWTurner** [comment]
@clusterfack each accumulated_offset depends on that object's default offset and speed. If I change it before the for loop then all 18 objects will jump at once which kinda ruins the purpose of having 18 objects instead of 2. If I'm not seeing what you mean please explain.

**Comment by clusterfack** [comment]
Then the system should be changed so that it keeps track of two different parallax values separately from the start. I was thinking of such a change for a while since it has to use round and several multiplications when the ```round(offsety * bgobj.parallax_speed * C.prefs.parallax_speed)``` really doesn't need to be recalculated 9 times in the first place.

**Comment by JMWTurner** [comment]
I'll do that

**Comment by ComicIronic** [comment]
You could also have used a % operation instead of a while loop.

**Comment by clusterfack** [comment]
That's not really what I meant

**Comment by JMWTurner** [comment]
It prevents having to use a while loop, so it should be at worse as efficient as before, with the added advantage of fixing the bug.

**Comment by clusterfack** [comment]
No offense but I'll just fix this in my own branch and make this a bit faster than it is now

**Comment by JMWTurner** [comment]
sure

**Pull request closed without merging**
