### PR TITLE
[MDB IGNORE] [Revival] Engine Access Split: Major / Minor. + Mechanic Promotion without Pay Increase.

### PR DESCRIPTION
**Pull request by ghost**
Revival of #31936 that resolves conflicts.

# Original PR Text

Replaces the access level "engine equipment" with "minor engines" and turns normal engine access into "major engines". Then adjusts a bunch of access requirements accordingly.

## What

Effectively this splits engineering access into 2 tiers: minor and major. Minor access includes generally moving around engineering, rigsuits, and most importantly "minor engines". Major access is almost exclusively used for "major engines".
Minor here is for engines that don't generally end the round if they go sour/are seen as simple. So things like the AME.
Major is the opposite, so: supermatter, singulo, RUST.

This changes access requirements for both doors and cargo crates relevant to this. For example, minor access lets you get into the AME. It also lets you order/open the shielding equipment for a singulo but not the singulo generator/PA parts. You now no longer need major (previously just "engine") access for ordered AME parts however, just minor access.

## Why

Mechanics have been given minor engine access but not major engine access. This means it is now officially their job to set up the AME or solars, but not the shard or singulo. Retroactively makes all the wrong people right regarding engines being mechanic's job, and also makes all the right people still right regarding access = job, wow!

## Door stuck

This was done with a bit of haste. I did double check both the code and via mapping tools but it's likely I either missed something or mixed something up. A lot of airlocks aren't labeled well at all. Please report any issues with this.

:cl:
 * tweak: Engine access now split into minor and major
 * tweak: Mechanics have been given minor engine access, but not major

### CODE REVIEW

**Comment by Kurfursten** [comment]
Fix conflicts

**Comment by ghost** [comment]
> Fix conflicts

Fixed

**Comment by Kurfursten** [comment]
Wiki

**Comment by Eneocho** [comment]
The supply crates page is updated. Gotta update the jobs.

**Comment by Eneocho** [comment]
Engineer, Atmos tech, CE and Mechanic's wiki pages have the access changes.
Mechanic's page now states you gotta make the minor engines if no engineer available.

**Pull request merged**
