### PR TITLE
Disables grue antag from firing randomly.

### PR DESCRIPTION
**Pull request by Dacendeth**
## What this does

Basically prevents grue from automatically firing
## Why it's good

Grue is a poorly balanced gamebreaking antag focused around round removal and broken game mechanics and it shouldnt be playable in this condition
## Changelog

:cl:
 * rscdel: Grue ruleset can no longer randomly fire

### CODE REVIEW

**Comment by BomberBro** [comment]
Third antag nerf/removal PR I've spawned immediately after I played as them for a round B)

**Comment by Dacendeth** [comment]
Yes I thank you for showcasing how retarded this antag is.

**Comment by ErrorsWindows** [comment]
i thought grues were a mining mob

**Comment by 9percents** [comment]
whoever thought up grue should rethink it

**Comment by angryturnip** [comment]
Focused on round removal is a bit of a stretch to me considering they can lay an egg for every person they eat. Having them snowball very easily if there happens to be a lot of dead bodies already in the round is a bit annoying though

**Comment by Dacendeth** [comment]
If they stay someone needs to do something about their infinite stat scaling. being able to regen 200 hp in a matter of seconds after eating a dozen people and moving three times as fast as anyone else makes a very unfun problem with nothing you can do about it besides call the shuttle since every grue weakness has been coded out.

**Comment by Theophrastus1** [comment]
Grues ability to just ignore what was supposed to be their intended weakness basically creates fucking mustard gas

**Comment by west3436** [comment]
[i ded]

**Comment by djkramer123** [comment]
They need their speed cut down, especially given the fact they deal 50 damage all grown up, which is pretty wack even without turbo speed. Also they should either lose the jaunt when they evolve to adult size or the cooldown needs to be massively increased. The ability to counter their counter has always been an lol.

**Comment by boy2mantwicethefam** [comment]
Perhaps wearing riot armor now that they once again deal ~8 damage at full strength to people wearing riot armor would help deal with grues. Some of you voted for grues to have that weakness and then don't make use of that weakness.

**Comment by ErrorsWindows** [comment]
le darkness aura
It is perfectly well lit. You are likely to be eaten by a big black man grue tugging a 10 tile blob of shadows with him and permanently fucking up the lighting logic for the rest of the round.
the reality is that nothing with mobility as its main trait will ever really truly be "balanced" due to the ability to simply pick fights, in the same vein of how many other things like that are simply annoying - Blink, a jetpack space battle, xenomorph hunters, etc.

**Comment by hacker-on-steroids** [comment]
make them deal pain damage(plus like 1 brute) and skeletonize people they eat
that way the crew remains alive and there's also spare grue eggs to get deadchat back in the round

**Comment by Dacendeth** [comment]
You think skeletonizing would help until you realize that the grue can just hit the corpse a few times and gib the head to pop out a brain that'll become unusable eventually.

**Comment by djkramer123** [comment]
> Perhaps wearing riot armor now that they once again deal ~8 damage at full strength to people wearing riot armor would help deal with grues. Some of you voted for grues to have that weakness and then don't make use of that weakness.

"Just wear riot armor" he shouts, as the adult grue runs through medbay's walls at mach 10 absorbing light and owns every doctor and patient and blinks away as security shows up

**Comment by hacker-on-steroids** [comment]
>the grue can just hit the corpse a few times and gib the head

you need a 15 brute hit to pulverise limbs, so the small amount of brute(multiplied by 2 because skelington) wouldn't be enough to crush them into bonemeal
the small amount of brute would be there to make simplemobs killable, and also to give the hypothetical grues a way to fight back against the completely skeletonised station without retarded headremoval

**Comment by Dacendeth** [comment]
> > the grue can just hit the corpse a few times and gib the head
> 
> you need a 15 brute hit to pulverise limbs, so the small amount of brute(multiplied by 2 because skelington) wouldn't be 

You do realize a proper grue does 50 damage which would be 100 against a skeleton corpse?

**Comment by boy2mantwicethefam** [comment]
> "Just wear riot armor" he shouts, as the adult grue runs through medbay's walls at mach 10 absorbing light and owns every doctor and patient and blinks away as security shows up

I don't believe grues are good at opening sleepers but I am not sure. I don't believe they can deal with disposal bins either.

**Comment by djkramer123** [comment]
> I don't believe grues are good at opening sleepers but I am not sure. I don't believe they can deal with disposal bins either

lol

**Comment by Dacendeth** [comment]
Any player controlled mob even mice can eject people from sleepers.

**Comment by SonixApache** [comment]
i ded pls remove

**Comment by falcon2346** [comment]
Grues already have a frankly ridiculously long lasting light resistance that lets them sprint through floodlight radius lights without getting slowed or taking damage, they literally don't need darkness aura. The dumb aura removes their only counterplay that isn't wearing riot armor. The aura is the biggest clear and obvious problem with Grue because it means at some point there is nothing you can do to keep them at bay, I don't know why we keep dancing around this.

**Comment by ErrorsWindows** [comment]
> "Just wear riot armor" he shouts, as the adult grue runs through medbay's walls at mach 10 absorbing light and owns every doctor and patient and blinks away as security shows up

image

**Comment by anonymoose-contributor** [comment]
> Grues already have a frankly ridiculously long lasting light resistance that lets them sprint through floodlight radius lights without getting slowed or taking damage, they literally don't need darkness aura. The dumb aura removes their only counterplay that isn't wearing riot armor. The aura is the biggest clear and obvious problem with Grue because it means at some point there is nothing you can do to keep them at bay, I don't know why we keep dancing around this.

Strange that you seem to agree with this PR, but downvoted it.

> Focused on round removal is a bit of a stretch to me considering they can lay an egg for every person they eat. Having them snowball very easily if there happens to be a lot of dead bodies already in the round is a bit annoying though

It seems as we've tried to counter "round removal" antags like Changeling by giving observers/dead players a chance to cause chaos via a respawn from a split or in Grue's case an egg, but that hardly seems like a good reason to keep an antag in rotation when its core purpose is to just kill. Not every antag needs to be about killing or mass destruction.

**Comment by west3436** [comment]
I ded/the thumbs hated this

**Pull request closed without merging**
