### PR TITLE
LAMPREY 

### PR DESCRIPTION
**Pull request by deadharold**
**Lamprey Station.**

The vast majority of secrets and details contained in Lamprey are usually quickly erased by the destructive power of 50+ players, leading to an overly hellish survival experience in highpop.  The intended way to play Lamprey is alone or with a few friends.

Just don't dig into the .dmm or an overseas server will remotely trigger my pacemaker to malfunction and stop my heart.
### Gallery

holo
_unused holomap view_
bridgemaze
_bridge maze_
theater
_clipping out of reality_
weldingengine
_welding engine_

A joint effort by Kilozombie and myself.
[<bus>]
[<sanity>]
[<dnm>]
:cl:
 * rscadd: Adds/Demystifies Lamprey Station
 * rscadd: Clown mobs

### CODE REVIEW

**Comment by ghost** [comment]
just checked the dmm and mapped out the most optimal insulated glove rush route, thanks

**Comment by Exxion** [comment]
I think he wanted DNM but feel free to remove it if I'm mistaken

**Comment by kilozombie** [comment]
RECOVERY IMAGE 01405

**Comment by kilozombie** [comment]
Not meant to be viewed in a map editor.
Mappers will instantly die. Everything is instances. I'm sorry.

**Comment by MadmanMartian** [comment]
But why put it on the main repo?

**Comment by kilozombie** [comment]
It requires constant maintenance to keep the map updated and we've decided it's time

**Comment by deadharold** [comment]
> But why put it on the main repo?

So people can local host it and explore at their own pace.
I don't care too much if some people decide to spoil it for themselves by digging through the .dmm.  And to address the claim that releasing lamprey like this will "kill" the map, I'll counter by saying the amount of hidden and mob-gated content on the map is large/dense enough that people will be finding new things for a long time.

**Comment by calzilla1** [comment]
This map achieves the dread and terror feeling of hell much more effectively than /tg/'s lavaland can ever hope to accomplish

**Comment by brndd** [comment]
Can we make it so that Lamprey can only be voted with 5 or fewer players on the server?

**Comment by IzayaChan** [comment]
I would actually play lowpop

**Comment by PJB3005** [comment]
> Can we make it so that Lamprey can only be voted with 5 or fewer players on the server?

You'd have to ask pomf but I assume so.

**Comment by DamianX** [comment]
why is this DNM?

**Comment by Exxion** [comment]
Because the person who opened it asked for it to be
@deadharold Say whenever you want the label to be removed

**Comment by deadharold** [comment]
The DNM is a shitpost take it off whenever

**Comment by DamianX** [comment]
:|

**Comment by kilozombie** [comment]
I don't know how to make it votable at 5 players (even after decades of trying to figure it out) but if somebody does and wants to make it happen I have no qualms personally.

**Comment by DamianX** [comment]
I don't know why you would want that but it's something that pomf has to set, currently

**Pull request merged**
