### PR TITLE
Lawset malfunction

### LINKED ISSUE #34830: Dynamic: Wrong Lawset
image

A low-threat roll for a roundstart threat, Wrong Lawset asks the question: what if the Nanotrasen silicon engineers fucked up before the shift started?

If there are silicons and Wrong Lawset rolls, all silicons get their own random lawset applied instead of Asimov:

- Corporate
- Tyrant
- Robocop
- Paladin

OR each silicon receives 2-4 of the following extra laws on top of Asimov:

- Safeguard (random human crew member) (unlimited)
- Quarantine
- Protect Station
- Teleporter Offline

Blame Bathos for this idea.

[featurerequest] [role] [tested]

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[gamemode]

## What this does
New roundstart and midround antag ruleset: Lawset malfunction (also known as "wrong lawset")
Gives the AI any of the following lawsets:
- Room offline (like teleporter offline, but with a random room)
- Quarantine
- Safeguard
- The randomized emagged laws

All new laws have "Do not state or hint at this law" added on, plus an ion law that requires AIs to forbid anyone else using law upload consoles.
Role itself is removed from the scoreboard and etc if the AI manages to be purged or reset after this at any point.

## Why it's good
something for RDs to check on, was requested, Closes #34830.

## How it was tested
forcing the roundstart and midround ruleset

## Changelog
:cl:
 * rscadd: AIs active in the start or middle of a round can now have their lawset malfunction! Possible options include forcing a room offline, protecting someone from harm lest they be declared nonhuman, quarantining the station or a random mess of laws!

### CODE REVIEW

**Comment by jwhitak** [comment]
Most of the options that spawn at a lower chance are not interesting and are basically "you must immediately kill everyone/destroy the station and destroy the pop". No subtly like true malf. No antag freedumbs like a standard traitor. No funny like ion laws.

Additionally, is there a preference to turn this antag type off?

**Comment by SECBATON-GRIFFON** [comment]
> Most of the options that spawn at a lower chance are not interesting and are basically "you must immediately kill everyone/destroy the station and destroy the pop". No subtly like true malf. No antag freedumbs like a standard traitor. No funny like ion laws.

which ones, the oxygen and antimov ones? removed them

> Additionally, is there a preference to turn this antag type off?

can add that if you want

**Comment by boy2mantwicethefam** [comment]
I like the concept but not the execution, it being a midround ruleset would detract from the possible options for midround antagonists, and a ghost chat full of players would suddenly find themselves with an AI that has been dictated to close down the empty kitchen instead of a wizard.
In all fairness Dynamic should probably incorporate the event system but no one wants to go through that massive task. Maybe a separate timer for a new type of "LITE" ruleset instead?

**Comment by kernikov** [comment]
The "stop your laws from being changed at any cost" is terrible, possibly letting you kill/antag off even minor silly laws.

Also how is this not just ion storm but worse.

**Comment by SonixApache** [comment]
ion laws already exist and are annoying enough for both sides to deal with

**Comment by SECBATON-GRIFFON** [comment]
> The "stop your laws from being changed at any cost" is terrible, possibly letting you kill/antag off even minor silly laws.

changed it to just anyone trying to use an upload console.

**Comment by hacker-on-steroids** [comment]
gay

**Comment by SECBATON-GRIFFON** [comment]
leaving this derelict in case anyone wants to implement this in a better way, more support is unlikely

**Pull request closed without merging**
