### PR TITLE
Your character in the claw machine

### PR DESCRIPTION
**Pull request by MercuriusGH**
[sprites]
[needspritework]
## What this does
I think that /vg/station is nothing without its players and their characters and the claw machine creates a fun opportunity.

The goal of this PR is to fill the coin prize pool of the claw machine with dolls based on the various characters that populate the rounds, preferably 1 doll per player.
Please submit a (fumo) doll of your character in the comments if you'd like to be included.
Can't make the sprite yourself? Don't worry, me and @falcon2346  will try to help out, contact us on the pager or just post reference images of your characters in the comments and we'll do our best.
Any help is welcome of course.

- [ ] placeholder task
- [x] Pox
- [x] Kayi
- [x] Kiera
- [x] Yika
- [x] Kitachki

## Changelog

:cl:
 * rscadd: Various character based plush dolls

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I will ONLY support this if they act as voodoo dolls.

**Comment by ValkyrieSkies** [comment]
Unless this PR specifically does something such as generate them by creating a shrunken down version of every characters' starting sprite (probably via reading the body archive) I suspect this will be heavily opposed because the playerbase generally doesn't want specific references to players in the code.

**Comment by wotisjanitor** [comment]
YAAAAAASS QUEEN

**Comment by CorinJace** [comment]
Unlike Valk, who has a wrong opinion (it's ok to be wrong), I support this 100%. It's cool to have game cute added in. A new game for players to have fun with.

**Comment by ValkyrieSkies** [comment]
Not strictly just my opinion, but a statement based on the discussion surrounding the original claw machine PR and its original inclusion of statics as job plushes.

**Comment by SonixApache** [comment]
no

*no*

we do not make references to specific players here, bar the two that got snuck in over the past

either make the dynamic `fumoify()` method of doing this, or don't do it at all

**Comment by gurfan** [comment]
i think it'll be fine as long as character's names are not explicitly stated
making a fumoify() proc could work too, but they wouldn't look as good

**Comment by Eneocho** [comment]
Clearly the solution is making a couple dozen fumo hairstyles, fumo clothing and fumo eye/facewear then generate then dynamically.

**Comment by brndd** [comment]
If you want to sprite more plushies, filling out the job fumo roster might be a good place to start. I don't think the time is right for player character references (and I'm frankly not sure the time will ever be right for that, though the fumoify wizard spell idea is funny as heck).

The claw machine also isn't technically locked to plushies (just a couple of the messages refer to them and should probably be changed if non-plushie items are added), so if you want to sprite some gunpla or something, those might be an idea, though I feel like hard toys are more the gashapon machine's territory.

**Comment by Securitymain** [comment]
grafik

**Comment by JonathanSpaceStation** [comment]
when I read the title I assumed this was about your character somehow getting stuck inside the machine; you should code that instead.

**Comment by djkramer123** [comment]
downvoted for including a permabanned shitter

**Comment by wankov** [comment]
what are we even doing anymore

**Comment by ShiftyRail** [comment]
nah, we're not having random players in the voxmachines and we're even less having permabanned ones.

**Comment by GreatBigFailure** [comment]
I think it would work on two conditions:
1. It's only the crewmen in the round, or similar like played within 24 hours
2. Everyone has one

Honestly I think the idea is very cute, but a universal method that transforms the player's sprite probably is the best way to go about it. Otherwise getting everyone to have one seems like a big speed bump. 

> nah, we're not having random players in the voxmachines and we're even less having permabanned ones.

Wait wait 
option 3: We ONLY have permabanned players

**Comment by SonixApache** [comment]
>go to hell
>there's a plushie machine there
>it contains unique, dynamically generated fumos of permabanned shitter statics

**Comment by Eneocho** [comment]
> > go to hell
> > there's a plushie machine there
> > it contains unique, dynamically generated fumos of permabanned shitter statics

Someone code that shit and map it on lamprey

**Comment by d3athrow** [comment]
😑

**Comment by John-VI** [comment]
This is unfair to plasmaman players who all look the same. Close this PR immediately.

**Comment by Eneocho** [comment]
> This is unfair to plasmaman players who all look the same. Close this PR immediately.

On the other hand you could claim literally all plasmeme statics are included so it should be closed even harder.

**Comment by Volttekka** [comment]
How about we fucking don't

**Comment by Kurfursten** [comment]
I don't know why I didn't close this sooner. Even if player opinion wasn't against this, we aren't going to start including normal player references. I would not oppose a generalized proc that makes a plushie out of any player in the current round using a squishing script like what brnd did for inhands.

**Pull request closed without merging**
