### PR TITLE
New mining vault: The Hivelord Queen's Lair

### PR DESCRIPTION
**Pull request by Eneocho**
Instead of having María spawn on Angie's Lair, she'll now spawn on her very own lair, complete with hive guardians and riches.

### TO DO
- [x] Fix assorted spriting issues.
- [x] More living floors
- [x] Harder guardians?
- [x] Replace the telecrystal ore with telecrystal veins.
- [x] Balance vault better
- [x] Add thematically appropriate loot.

:cl:
 * rscadd: María's Lair, a mining vault where the dreaded Hivelord Queen spends her days surrounded by guards and riches.
 * rscadd: Hivelord Guardians will protect the Hivelord Queen. They're slightly larger than a regular hivelord and have 25 extra health. These will attack with Hivelord Guardian Broods, which are nominally stronger than a regular brood.
 * rscdel: María no longer spawns on Angie's Lair.

### CODE REVIEW

**Comment by Eneocho** [comment]
### The walls inside the hive are all random and can have different kinds of loot, this is how it can look:
Procreatory Center Phi 2022-11-28 084719

**Comment by Eneocho** [comment]
Guess it's ready for review. Not sure what else to add, if anything.

**Comment by Eneocho** [comment]
> hold up what this isn't merged
> i saw the giant hivelord ingame a couple days ago
> am i off my meds again

Currently you can fight María on Angie's nest, there's a 50% chance of Angie spawning and a 50% chance of María spawning.

**Comment by Kurfursten** [comment]
Reduce the number of clown mineral turfs. Angie's nest only has 6 clown mineral turfs -- this one contains 66. That's a comical order of magnitude difference. It guarantees a large supply of bananium and phazon. This lair is also much easier to spot for miners on mesons than Angie's.

**Review by Kurfursten — CHANGES_REQUESTED** [review]
Reduce clown mineral turfs by 91%

**Comment by pedr69** [comment]
>66 bananium


image
imagine the clown honkening every airlock and floortile on station

**Comment by Eneocho** [comment]
> Reduce the number of clown mineral turfs. Angie's nest only has 6 clown mineral turfs -- this one contains 66. That's a comical order of magnitude difference. It guarantees a large supply of bananium and gibtonite. This lair is also much easier to spot for miners on mesons than Angie's.

Wait what? 66? I swear there were like 15 or something. Fixing.

**Comment by Eneocho** [comment]
Just checked, it was 61, not 66. Reducing down to 10. I feel 10 is a good number here cause the vault is a lot more hectic and dangerous than Angie's, where it's just one rocketnaut you can reliably swerve around. Meanwhile this is a swarm that very aggressively expands and quickly consumes all your ammo to hold back.

**Comment by Eneocho** [comment]
@Kurfursten, done.

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
