### PR TITLE
This PR allows mushroom men to smoke

### PR DESCRIPTION
**Pull request by toomykins**
surely this wont have consequences

### CODE REVIEW

**Comment by falcon2346** [comment]
I saw a mushman with a cigar the last round that I played though, can't they already do that?

**Comment by toomykins** [comment]
> I saw a mushman with a cigar the last round that I played though, can't they already do that?

Yes, thats why i have two separate PR's about this. In most code situations negatives should be handled before positives, but that's not the case in the current code that handles this. as a result, mushroom men can equip cigarettes if they quick-switch it into the slot, as in, swap it with a gas mask or something, rather than putting it in an empty slot.

**Comment by SonixApache** [comment]
they don't have breathing holes, this makes no sense

**Comment by NigglyWiggly** [comment]
What's the point, them not being able to talk normally is at least a unique thing

**Comment by githubuser4141** [comment]
> they don't have breathing holes, this makes no sense

How? Ciggy chems shouldn't process in their blood because they're not absorbing it, but there's no reason they can't place it in their mouth, or under a skin flap, or whatever. If they don't have mouths they could hold it in the air, I guess, or poke a ciggy sized hole in their head to fit one?

**Comment by ghost** [comment]
Let them, it's cool.

**Comment by NigglyWiggly** [comment]
I completely misread the title and I have severe brain trouble please excuse me

**Pull request closed without merging**
