### PR TITLE
Adds more passive and hostile infestation mobs (with bonus relevant admin tool improvements)

### PR DESCRIPTION
**Pull request by ProfanedBane**
@GeneralVeers25 asked me to add goliaths and davids to the spawn list and things got out of hand.

Currently adds the following "vermin":
- Syphoners (latches to wires and charges cells)
- Gremtide (gremlins playing dress up as assistants)
- Crabs (says it on the tin)

And the following "hostiles":
- Goliaths
- Davids (babby goliaths)
- MEGAMADCRABS (HE'S ANGRY)
- Meatballers (giant spaghetti monster ready to call you a faggot)
- Mutated Roach
- Roach Queen

With a bonus of having the hostile infestation admin override act the same as the regular infestation (you can pick location and mob).

Anything and everything here is subject to change, if you have concerns or suggestions please fire them over here.

:cl:
 * rscadd: More mobs may appear during infestations now, be careful spessmen.
 * rscadd: (admin only) Hostile infestations can now have their location and mob specified when manually caused.

### CODE REVIEW

**Comment by Kurfursten** [comment]
So many unrobust spacemen are about to be killed by goliaths

**Comment by ProfanedBane** [comment]
We need to condition the next generation to be stronker.

**Comment by AutismSpider** [comment]
more likey to die to mega mad crab/crabs then the goliath.

The crab moves fast as fuck and has 300 hp

**Comment by Caboozles** [comment]
Why stop there? Let's add Russians so we can say we have an infestation of Russians in the bar.

**Comment by ProfanedBane** [comment]
That's why they're MEGA MAD crabs and not Mildly Miffed crabs.

Also I'm not against russians being in, that could be funny.

**Comment by bathosbathtime** [comment]
Adding in Russians would be a nightmare for Asimov silicon and anyone having to deal with said Asimov silicon.  Not that I'm against adding them in, I just feel that this is an important point to consider before we do so.

**Comment by ProfanedBane** [comment]
Yeah that might be enough to warrant not putting them in, unless someone really wants it to happen.

For the record for a hostile mob infestation to happen we need 2 or more sec officers in the round.

**Comment by ShiftyRail** [comment]
A sec off without access to the armoury for laser weaponery may has well just throw stones at the mobs

It's a cool thing but it will make me miss mobs tape

**Comment by SonixApache** [comment]
The secure armory is usually only 4 hackable doors away.

**Comment by ShiftyRail** [comment]
I know, but it assumes
a) you have tools
b) you know the test wire
c) you don't shy away from hacking

Which while trivial to obtain is not automatic

**Comment by Kurfursten** [comment]
For whatever reason the community frowns on yellowglove officers which seems super hypocritical to me.

**Comment by SonixApache** [comment]
24/7 Yellowglubbs on an officer are the telltale sign of a shitter. Glubbs in the box are fine, IMO.
But generally, if you just grab the test wire at some point you've got easy armory access whenever, except on Deff.

**Pull request merged**
