### PR TITLE
Added barber's uniform and barber vendor.

### PR DESCRIPTION
**Pull request by Arthurdentist**
This PR adds a Barber's uniform and a Barber Vendor. 

barber costume update
barber vendor

The Barber Vendor sprite is by @NigglyWiggly 

The vendors don't exist on any map yet but you can purchase two packs for 15 credits from cargo. 

Each vendor contains 4 of the following:
- Barber Uniform
- Barber Hat
- White Gloves
- Fake Mustaches
- White Shoes
- Hair Dye
- Pocket Mirrors
- Electric Razors

Also for contrabrand you can get 5 random lipsticks.

### CODE REVIEW

**Comment by ghost** [comment]
Nicu

**Comment by SonixApache** [comment]
cute as fuck

**Comment by Shadowmech88** [comment]
I believe that, technically, that is the uniform of a barbershop quartet member.
To my knowledge, actual barbers have historically worn simple white shirts or jackets while working.

**Comment by RFultra** [comment]
Why no cut throat razors?

**Comment by Arthurdentist** [comment]
@Shadowmech88 Yeah that is obvious and goes without saying, but where is the fun in not having such a uniform?

**Comment by Kurfursten** [comment]
Perhaps add the apron item to this vendor? Nothing says barbershop to me more than aprons.

A+ spritework

**Comment by Arthurdentist** [comment]
@Kurfursten might add a barber variant in a later update, I did consider it but I'd have to change the name and I'd probably want to change what items it can hold, so I will leave it for now.

**Pull request merged**
