### PR TITLE
Hostile mobs no longer destroy firelocks that are either open, or welded down

### PR DESCRIPTION
**Pull request by DeityLink**
It's annoying watching them spawn dismantled firelocks everywhere, so I gave them parity with regular airlocks.

:cl:
* tweak: Hostile mobs no longer destroy firelocks that are either open, or welded down.

### CODE REVIEW

**Comment by jknpj** [comment]
watching clowngoblins wreck them is painful

**Comment by Eneocho** [comment]
By welded down you mean open welded firelocks, right?

**Comment by Kurfursten** [comment]
No he means any welded firelocks, so you can weld them closed and mobs are now once again helplessly trapped behind them. Apparently if they get locked down by pressure differential or temperature differential they are also prevented from breaking them.

This goes too far imo. Of course we don't want them smashing firelocks that are open but they should be able to smash through those which are simply alarming. Welded might lower the smash chance or something but why not?

**Comment by DeityLink** [comment]
Alright, I removed the lockdown limitation so they basically can open firelocks as someone with a crowbar could.

**Review by Kurfursten — APPROVED** [review]
Code is fine

**Pull request merged**
