### PR TITLE
fix hostile mobs losing interest in people standing still 

### LINKED ISSUE #29765: Cyberhorrors are way too tame.
I've made a "Cyberhorror treatment center" on a few rounds. Quite literally a cyberhorror trapped inside a plastic flap cuck cube so if you're injured, you can crawl into the cuck cube and be forcefully injected mednanos. The idea was a high risk high reward kind of facility that could cause problems if not careful.
The problem is that the cyberhorrors are very tame, uncannily so. To the point you have to both hit them and move them around (either by swapping places or by dragging) for them to notice you and attack. They are supposed to be very dangerous and bloodthirsty simplemobs, but they barely do shit unless actively taunting them.
I think it's a side effect of the hostilemob AI change #29429, but I could be wrong.

### LINKED ISSUE #31533: Simple mobs attack in bursts of 2
(WEB REPORT BY: sacredatom REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
Stand still next to a hostile simple mob, the mob will usually attack twice, stop for 5 seconds, then attack again usually after moving another tile.

# Steps to Reproduce
Easiest way is spawn a carbon in dome, and a simple melee mob, and watch it happen real time.

# What you Expected
Mobs to constantly attack

# What Actually Happened
Mobs attack in bursts of two, which can be used to usually kill a mob in most cases head on much easier. Even more simple if a plantman.

### PR DESCRIPTION
**Pull request by gurfan**
Closes #31533
Closes #29765

### CODE REVIEW

**Comment by Eneocho** [comment]
Does this fix #29765 as well? They lost interest and didn't attack properly.

**Comment by Optimism333** [comment]
If this does indeed fix simplemobs, thank you sir. Vault difficulty will no longer be artificially nerfed.

**Comment by gurfan** [comment]
> Does this fix #29765 as well? They lost interest and didn't attack properly.

probably

**Comment by Eneocho** [comment]
>Vault difficulty will no longer be artificially nerfed.

Ranged simplemobs are artificially buffed since they don't get stunned, crit'd or otherwise impaired until the death point.

**Pull request merged**
