### PR TITLE
Allows the mosin to accept a telescopic sight

### PR DESCRIPTION
**Pull request by ErrorsWindows**
## What this does
title

## Why it's good
Why do I think it's good? Just seems kinda strange how the only thing the telescopic sight can fit on is the bird rifle... I'd just like it to fit on the mosin because it'd make sense, you know?

### Why I'd actually like it (pov: in my imagination as I am writing why it's good)
[relax Schlomo, I was aiming for the desk bell, I'm just trying to make a point](https://youtu.be/PFs7mxKNUO8)

Screenshot (1986)

## Changelog
:cl:
 * tweak: Allows the telescopic sight to be mounted on the mosin nagant, the second gun to allow this attachment

### CODE REVIEW

**Comment by pedr69** [comment]
do you not need to do an attackby() override to attach the scope
or does the SCOPED flag do that already

**Comment by Eneocho** [comment]
there was a classic rant with a russian guy complaining that americans wanted to scope everything even if it didn't need to, but now of all times I can't find it.

**Comment by Inorien** [comment]
image
when

**Comment by Eneocho** [comment]
> there was a classic rant with a russian guy complaining that americans wanted to scope everything even if it didn't need to, but now of all times I can't find it.

Found it:
image

**Comment by Playyne** [comment]
> there was a classic rant with a russian guy complaining that americans wanted to scope everything even if it didn't need to, but now of all times I can't find it.

_Ahem_

Sniper_Rifle_Mosin_1891_30-fr

**Comment by ErrorsWindows** [comment]
> do you not need to do an attackby() override to attach the scope or does the SCOPED flag do that already

[ya i think it should work like that](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/projectiles/guns/projectile.dm#L264), the scope was designed like any other gun part would even though the only gun the scope even fits on right now is the rubber rifle, nice thinking of the future kurf

> there was a classic rant with a russian guy complaining that americans wanted to scope everything even if it didn't need to, but now of all times I can't find it.

yea I was autisming about that when I was making the sprite, thinking I would have to do some kind of 1' eye relief deal where I put it forward of the bolt because 2nd world guns are fitted with a weird dovetail slide on the left side instead of the good old rail on the top
until I realized that this is space station 13 and the scope itself is 3D printed so it'll probably just fit whatever you put it on

**Comment by pedr69** [comment]
i was wondering why you copypasted the scopecode from the hunting rifle instead of inheriting it but then i looked at guncode in general, and oh man
oh man

**Comment by SonixApache** [comment]
For pretty points, add a mosin nagant scope adapter to the hacked autolathe and make it attach off that.

Did you test if the overlays function properly with adding / removing the scope? 
Your method of adding and manipulating the overlay isn't the same as mine, so I'm wondering if your method is better or if you're going to be running into the same problems I was. (I can't find the  `gun_overlay` var anywhere to figure out what's going on, github blacklisting our repo is annoying.)
_INSTANT EDIT:_ `gun_overlay` seems to be used only by the hunting rifle, in a different file.  Linter hasn't run yet which confused me.
Probably won't work the way you're doing it. Either add the var to the mosin or adapt your code to work with the universal attachment system. Preferably the latter. 
Shouldn't be hard, just add your `scope_overlay` to `gun_part_overlays` instead, see the code for silencers.

**Comment by ErrorsWindows** [comment]
ok gimme a bit for my brain cells to regenerate

**Comment by pedr69** [comment]
the lint doesnt run because you're on a new account
all new accounts need to get a collab to press the button before the stuff works i think

**Comment by ErrorsWindows** [comment]
ya i don't know what i'm doing

**Comment by Kurfursten** [comment]
please do not make commits with special characters in the name

this also doesn't even compile because you pasted code without understanding it!

**Comment by ErrorsWindows** [comment]
yea i have no idea what i'm doing

**Pull request closed without merging**
