### PR TITLE
Away mission fixes

### PR DESCRIPTION
**Pull request by Probe1**
Thank you to @cloroxygen for sorting out why the fuck loading away missions was so busted.
## General

**Moves** all updated away missions to a new folder 
## Academy

**Updates** paths
**Fixes** windoors with the wrong dir
**Fixes** a bad landmark spawn that left players trapped.
**Fixes** missing windows and lights.
**Adds** a wizard spawner
**Adds** Wizard and Spider spawns to SPICE IT UP.
## Beach

**Updates** paths
**Replaces** two of the three crabs with a kickstool (black) and snowy (white) variant.
**Adds** advanced bartending machines to the bar.
**Removes** the sounds that play at the beach.  This can be re-added later but it relies on archaic and non-working code.  I fucked with it for a while but I couldn't get it to work so it's going into the trash.
## Meat Packers

**Updates** paths
**Fixes** windoors with the wrong dir
**Tweaks** the roid to be a clown roid.
**Adds** lighting.
## Challenge (EMITTER HELL)

**Updates** paths
**Adds** additional syndicates because I remember there being more.
**Rebalances** weapon loot.
## Example

**Updates** paths.  Remember not to include this one this time around..
## Listening Outpost

**Updates** paths.  This one has always needed way more work and is very, very boring.
**Replaces** regular mining tiles with a mix of high yield and clown.  At least its something.
## Station Collision

**Updates** paths.
**Fixes** windoors with the wrong dir
What a fucking mess of a mission.  Fun though.  Super fun.
## Wild West

**Updates** paths.  https://www.youtube.com/watch?v=u6mYGcNgKn8
### Space Battle, Jungle, and ZResearchLabs

are totally fucked and I'll try to recover them but don't count on it.
# To do:
- [x] Fix and improve Academy
- [x] Fix and improve Beach
- [x] Fix and improve Meat Packers
- [x] Fix and improve Challenge
- [x] Fix Example
- [x] Fix and improve Listening Outpost
- [x] Fix Station Collision
- [x] Fix Wild West

Space Battle, Jungle, and Research Labs need major TLC and are out of scope.  I really want a working space battle but it's got a lot of issues, notably that dreammaker crashes when you try to load it after fixing the bad paths.

### CODE REVIEW

**Comment by kol1th** [comment]
what's the academy?

**Comment by clusterfack** [comment]
Wizard academy away mission

**Comment by ghost** [comment]
Kinda wanna redo the beach away mission into something akin to islands.

Space carp in the water, diona with spears on another island, et cetera.

**Comment by Probe1** [comment]
You are more than welcome to it, they are all very old and new ones would be wonderful.

**Comment by Brolaire** [comment]
ITS
FUCKING
HAPPENING

**Comment by Probe1** [comment]
Somebody show me how the map loader is supposed to work because it's undocumented and mimicing the changes in https://github.com/d3athrow/vgstation13/commit/062ddde715d81970cc9541601c963456530678f2 doesn't do SHIT.

@gbasood @PJB3005 @ririchiyo @clusterfack @9600bauds ANYONE.

**Comment by gbasood** [comment]
New label, might as well since if this matches what we saw with vaults we'll see a huge amount of shitty away missions made once it's proven they work.

**Comment by ghost** [comment]
wow rood

**Comment by gbasood** [comment]
@Skullyton well hopefully good ones too  geez

**Comment by PJB3005** [comment]
Away missions can't not be shit with this model though.

**Comment by Probe1** [comment]
Despite your dislike, players still LOVE away missions.  Either way I'm making a separate PR to enable them and in that PR making it an admin toggle for the gateway so it isn't every round.

Today, we fix up the away missions.
Tomorrow, mappers are inspired to make new ones.

**Comment by Probe1** [comment]
Merge it

**Comment by Probe1** [comment]
Ready for review.

**Comment by gbasood** [comment]
@Probe1 Pretty sure admins can already trigger away missions so I dont know why you need a new PR for that part

**Comment by Probe1** [comment]
..where?

**Comment by gbasood** [comment]
Don't know, but I've been told several times that they can

**Comment by Intigracy** [comment]
Editing the config probably.

**Pull request merged**
