### PR TITLE
RIP N3X15

### PR DESCRIPTION
**Pull request by Intigracy**
Upsides to this change:
Nobody will be scared by the changelog thinking bald Eggman of coding has returned to us any more.

Downsides to this change:
Nobody will be scared by the changelog thinking bald Eggman of coding has returned to us any more.

### CODE REVIEW

**Comment by Imagebard** [comment]
:+1:

**Comment by clusterfack** [comment]
Nexis has more changelog entries right now than I do

**Comment by Imagebard** [comment]
I will change my opinion on this PR but only if you add a changelog note credited to N3X15 saying "fixes other coders crediting me for new changes"

**Comment by Intigracy** [comment]
Good idea I'll do that tomorrow.

**Comment by ComicIronic** [comment]
He's literally slacking and also get off the meatclub.

**Comment by ghost** [comment]
ANTAG DATUMS WHEN

**Comment by Intigracy** [comment]
Nothing wrong with being a slacker and not fixing bugs, Celt did it for over half a year for shit _he_ broke.

Anyway added a meme changelog this is good to go :+1:

**Pull request merged**
