### PR TITLE
remove 22 extraneous pans from snaxi

### PR DESCRIPTION
**Pull request by nervere**
lol https://github.com/vgstation-coders/vgstation13/pull/33569/commits/ee14d76683b0b5dd6dce57ac126605c5d18a8ad2

image

### CODE REVIEW

**Comment by Exxion** [comment]
Soulless, etc.

**Comment by pedr69** [comment]
>lets make snaxi even more shit

for what purpose

**Comment by Exxion** [comment]
Yeah I'm not sure why I didn't merge this on sight

**Comment by Eneocho** [comment]
sovlless

**Pull request merged**
