### PR TITLE
Potassium Hydroxide and Bar Soap Production

### PR DESCRIPTION
**Pull request by bathosbathtime**
This pull request adds potassium hydroxide.
To be clear, this is being done explicitly to reintroduce water potassium purging chemicals from closed containers, but that will be in a separate PR.  While this PR could exist on its own, I want to make it clear what my motivation is.

Potassium hydroxide is a chemical resultant from combining water and potassium.  It is corrosive, doing slight burn damage while inside the body.  It has a custom metabolism of 0.1 and is removed at a rate of (2 * REM) by anti-toxin.  Damage and metabolism numbers can be adjusted as needed for balance.  It is used in the making of soap.  Combined with corn oil and heated in a Bunsen burner will result in a bar of soap.  In real life, it is used in making liquid soap, but I made it make bar soap instead as people often find bar soap difficult to get a hold of, requiring spawn locations, the biogenerator, or an uplink.
The description mentions batteries, but it is not currently used in making batteries in game nor do I plan on making it.  That is just intended to be fun trivia/flavor.

Compiled and tested locally.

:cl:
 * rscadd: Added potassium hydroxide
 * rscadd: Soap can now be made at a Bunsen burner using potassium hydroxide and nutriment

### CODE REVIEW

**Comment by ShiftyRail** [comment]
>To be clear, this is being done explicitly to reintroduce water potassium purging chemicals from closed containers, but that will be in a separate PR. 

The hero we need

**Comment by MadmanMartian** [comment]
>explosions from chemistry
"I'm making soap"

**Comment by Blithering** [comment]
>chemists will soon be able to make lube soap foam grenades

Has science gone too far?

**Comment by SGuivenne** [comment]
except how will you get corn oil for this when botany will just ask you why and then print out soap for you to metagame.

**Comment by bathosbathtime** [comment]
I believe that there should be multiple ways to do something, even if they are closely related.  While I am not married to using corn oil, I had issue finding a better reagent that would fit the ingredient of fat/oil while still being realistically available during a round.

**Comment by bathosbathtime** [comment]
The soap recipe now uses NUTRIMENT instead of CORNOIL.  I find this to be more boring, but far more feasible for realistic production of soap.

**Pull request merged**
