### PR TITLE
Raises the amount of roundstart cultists back to 4

### PR DESCRIPTION
**Pull request by ShiftyRail**
Essentially, reverts #25519 

## Why

- the PR was an attempt at raising the "quality" of cult by removing points of failure (now only two people can draw illegal Ws)
- the PR did not change the frequency of people drawing illegal Ws
- if someone is caught drawing an illegal W, that's already 50% of the cult gone

If we cannot remove cult, then at least let's make it something else than "catch a guy being a shitter and find a way to have the shuttle called" simulator

:cl:
- tweak: The amount of roundstart cultists has been raised back to 4

### CODE REVIEW

**Comment by Accipitermaris** [comment]
i'm amazed it took this long for 2cult to get reverted, but better late than never

**Comment by tuypo1** [comment]
Thank fuck, now some cults might actually get off the ground, especially important now that we get it so rarely

**Comment by agentofzog2** [comment]
I don't know what they expected with that change.

**Comment by ShiftyRail** [comment]
@agentofzog2 what was expected was "less chances for someone on the team to fuck up on prologue since we have only two retards and not four", ie removing points of failure
didn't hit its mark and ended up completely atrophying cult

& i say this as a staunch anti-cult supporter

**Pull request merged**
