### PR TITLE
Revert "Added mutual cuff functionality (#23079)"

### LINKED ISSUE #24545: Friend/buddy cuffing is absurdly broken shitcode
#### Description of issue
I don't even know where to begin on this there's so many problems with it but here I go.
You can cuff yourself to a monkey to get stuck into a meatrack
You can cuff yourself to someone to get stuck inside a sleeper/scanner/cyrotube
You can cuff yourself to put two people into a mech that neither can operate correctly
you can cuff a human to a nymph and have someone put that nymph in their backpack to hide in the backpack along with the nymph.
You can teleport the nuke disk by teleporting someone cuffed to someone holding it.
You can hide inside a washing machine by being cuffed to a monkey you put in there.
I have like 10 more examples I could give/find if I really need to go on about how broken this is.

#### Specific information for locating

https://github.com/vgstation-coders/vgstation13/pull/23079

### PR DESCRIPTION
**Pull request by SonixApache**
This reverts commit 1a69151b2656730255f9f2e698297492a929ffed from PR #23079.

Why? Because of how many absolutely retardedly broken interactions there are with it. Including, but not limited to;
 - Being able to teleport with the disk
 - Entering mechs, sleepers, gibbers together
 - going invisible by picking up a dionae you're cuffed to
 - putting people on your head by equipping the dionae they're cuffed to

closes #24545 which contains a bunch more of these insane interactions

:cl:
 - rscdel: removed the mutual cuff functionality

### CODE REVIEW

**Comment by Dacendeth** [comment]
do the changes made by https://github.com/vgstation-coders/vgstation13/pull/23514 need reverting too? I don't know how these things work i'm just a concerned citizen.

**Comment by SonixApache** [comment]
Should be included.

**Comment by DamianX** [comment]
wtf, fix it don't remove it
lazy coders
muh features
[other empty statements]

**Comment by SonixApache** [comment]
I'd fix it if I knew how but this seems too big to quickly repair without too much hassle.
Anyone in the future is, as always, welcome to revert the revert and unfuck it.

**Comment by ShiftyRail** [comment]
All of those can be solved. The key issue seems to be that the link isn't broken when one party is `forceMove`d somewhere.

**Comment by jknpj** [comment]
Can be fixed =/= Will be fixed. I'll give this a few more days to see if some madman wants to work on it.

**Comment by jknpj** [comment]
I am literally blind

**Pull request closed without merging**
