### PR TITLE
Roid Bugfixes

### PR DESCRIPTION
**Pull request by Kharkov72**
[roid]
mostly fixing some pipes, tinkering with some wires, making tiles in the ghetto sec actually represent what they are, making the DJ sat not gunk, and making tiles that are just chilling in space actually unsimmed
but here's the big shit
every single reinforced asteroid wall was the *wrong type*
they would turn into an unsimmed turf when mined
very epic

:cl:
 * bugfix: Various roid fixes, including fixing all the reinforced rockwalls to be the correct type, cleaning up some various piping and wiring to not go through walls, and having turfs that start in space start unsimmed.

### CODE REVIEW

**Comment by Kurfursten** [comment]
What about all those pipe and wire changes?

**Comment by Kharkov72** [comment]
mostly just cleaning up, fixing a fucked up scrubber in chemistry, making cargo wiring not lean on sci wiring, making some pipes not go through walls when there are perfectly fine paths through doors

**Comment by SonixApache** [comment]
\>every single reinforced asteroid wall was the wrong type
\>they would turn into an unsimmed turf when mined
Fun fact; this is exactly what I fixed and threw away when I had to make way for Deity and you.

Please add a slightly more descriptive 🆑

**Comment by Kharkov72** [comment]
Newer tweaks include making the little atmos potato thing its own area, some more turf fixes, an area fix in the deep roid, and changing the warden's personal pistol to a glock custom, as .45 is an ERT pistol.
Untitled

**Pull request merged**
