### PR TITLE
Buff Viscerators to not die to a single toolbox smack

### PR DESCRIPTION
**Pull request by yackemflam**
They're really fuckin weak for how much tc the grenade costs

:cl:
 tweak: The syndicate put slightly harder alloys on their viscerators to combat the toolbox threat

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Yea sure

**Comment by ghost** [comment]
This isn't necessary.

**Comment by tayachiya** [comment]
They're fast, tiny, hit hard and with the knife you can spam them as long as you're alive.

**Comment by boy2mantwicethefam** [comment]
The PR about to get slapped because yackem made it smh

**Comment by ghost** [comment]
It's just not needed for all the reasons tayachiya described.

**Comment by boy2mantwicethefam** [comment]
I looked at the code, butterfly knife viscerators already have 25 health. This change is more about viscerator grenades now I think

**Comment by boy2mantwicethefam** [comment]
The grenade is pretty useless, most consumable items are because they're consumable. It doesn't affect the viscerators from butterfly knives because the butterfly knife viscerators have 25 health. This change is about viscerator grenades. It's a pretty good buff to prevent the viscerators from being destroyed so easily. Normal viscerators deal 15 damage, as much as a toolbox. Is this enough to convince you?

**Comment by dunsel-hordon** [comment]
sounds like it would be a good idea to have a diffrent viscerator type for the knife and nade if it isn't already like that and only buff the nade ones with a bit more health so they can take at least one hit.

**Comment by SonixApache** [comment]
viscerators have chopped me too often for me to endorse this

**Comment by boy2mantwicethefam** [comment]
@dunsel-hordon it already is like that, this PR affects grenade viscerators only, knife viscerators are already there

**Comment by aceedex** [comment]
dude 5 TC item
two 15 health mobs
lmao

**Comment by Dacendeth** [comment]
The knife ones are better for some reason, why is the spammable infinite knife version a better version anyways?

**Comment by SonixApache** [comment]
did you test this

**Comment by yackemflam** [comment]
yes

**Comment by ghost** [comment]
They're insanely small and can be copied with a traitor mechanics device, meaning that any buff to them is a buff _with that item in mind._ That and I think they're exactly fine like this, they see more use and more devastating use than most of the items uplink.

**Comment by ghost** [comment]
should probably have specified in the original comment if this doesn't affect knife viscerators

**Comment by tuypo1** [comment]
If you think they are underpowered for cost I think it would be better to reduce cost instead of increase power

**Comment by Kurfursten** [comment]
lacks support

**Pull request closed without merging**
