### PR TITLE
Xenomorphs should no longer hulk-scream when trying to break out of restraints

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Lol
:cl:
 * bugfix: Xenomorphs will no longer scream like hulks when breaking out of restraints of any kind.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I looked at that file and it is terrible

**Comment by ArchSunder** [comment]
feature

**Comment by jknpj** [comment]
this is a terrible way of doing it but ok

**Comment by boy2mantwicethefam** [comment]
it's because I'm not sure if xenomorphs have hulk, I heard they do but I never bothered checking

**Comment by Kurfursten** [comment]
jkn is right that this is a terrible way of fixing it... but also the whole proc this is a part of is so mindblowingly awful and non-object oriented that you would basically have to start rewriting it all and we can't really make you do that

**Comment by ShiftyRail** [comment]
`resist()`, the write-only proc

**Pull request merged**
