### PR TITLE
Message upon offering to hand someone an item

### PR DESCRIPTION
**Pull request by Hinaichigo**
[qol]
This adds a message when you offer to hand someone an item, of the form:
> You offer the fountain pen to Johnson Lovelocker.

That way you can see that the offer actually went through, which I think is nice.

:cl:
 * rscadd: Added visible message upon offering to hand something to someone else.

### CODE REVIEW

**Comment by Exxion** [comment]
Not a comment on the changes, just a note in case you weren't aware: `\the` doesn't actually do anything in these cases. It's implicitly inserted before references of this type. It's basically just a matter of whether it looks better with or without it.
As far as I know, it only does something if the following embedded reference is a string rather than an object.

**Comment by Hinaichigo** [comment]
I see, thanks.

**Comment by Exxion** [comment]
I mean you can put them in if you want, you just don't *need* to

**Comment by Hinaichigo** [comment]
It's more for the visual aid of someone reading the code?

**Comment by Exxion** [comment]
Pretty much

**Pull request merged**
