### PR TITLE
re-adds the syndicate greytide implant

### PR DESCRIPTION
**Pull request by MadmanMartian**
Readds the greytide implants to the traitor uplinks

### CODE REVIEW

**Comment by ShiftyRail** [comment]
This should create a faction of the greytide + the other guy so that they can get HuD icons.

**Comment by MadmanMartian** [comment]
Does it not do that already?

**Comment by ShiftyRail** [comment]
Nah, it creates an orphaned role.
I don't think the role is even of the right type

**Comment by MadmanMartian** [comment]
@ShiftyRail it makes a role now, sets the user of the implant as the leader of the faction through HandleNewMind, then adds the implanted through HandleRecruitedMind, then sets a protect objective to protect the leader of the faction.

**Comment by ShiftyRail** [comment]
👌

**Pull request merged**
