### PR TITLE
The Life and Death of Warden and HoS Advanced Cameras

### PR DESCRIPTION
**Pull request by Jackreturnswithaveangenace**
hate
I cannot tell you how much I hate these things. The way it messes with my UI, the way it crashes and lags when I could be using a simple, honest camera console. This is grudgecode pure and simple, have no illusions about this. My StrongDMM crashed twice just trying to save these radical changes as if the very code itself resisted my vengeful hand.

Please discuss.

:cl:
 * tweak: Advanced Camera Consoles on all maps have been changed for regular Camera Consoles, with a board left behind in the warden's locker as an afterthought by the repo-man who downgraded them.

### CODE REVIEW

**Comment by Kharkov72** [comment]
I am going to throw in that on startup, there is a minimap startup that takes 1-2 minutes
the advanced sec console is literally the only thing that currently uses it.
CMC and other shit uses holomaps as of #22461 so basically either fucking make it consistent, remove the loadtime and maybe make it work for godssake or remove it, if you are a centrist and don't want either I will personally put you in the lobby cube until time ends

**Comment by Jackreturnswithaveangenace** [comment]
let it all out, let it all out

**Comment by BurntDevil** [comment]
DEATH TO ADVANCED CAMERAS

Useless broken shit, they wont be missed.

**Comment by APCUnlocked** [comment]
God bless you for this PR, advanced camera consoles are cancerous as fuck to use compared to the normal ones.

**Comment by PlausibleDeniability** [comment]
Man this is retarded - if you're grudgecoding, just do it properly and remove it entirely

It's buggy, but so is the regular camera console, it's so much more usable with the scaling icons PR - #28551 

> 
> 
> I am going to throw in that on startup, there is a minimap startup that takes 1-2 minutes
> the advanced sec console is literally the only thing that currently uses it.
> CMC and other shit uses holomaps as of #22461 so basically either fucking make it consistent, remove the loadtime and maybe make it work for godssake or remove it, if you are a centrist and don't want either I will personally put you in the lobby cube until time ends

Be sure to remove the minimap startup too so this PR actually gives the server an actual benefit outside of (waa I don't like it)

**Comment by Jackreturnswithaveangenace** [comment]
That might be unatomic, but if you would like me to remove that too then just direct me to the code and I will go ahead with it.

**Comment by PlausibleDeniability** [comment]
Fuck it, I'll just make a new PR to grudgecode the rest of it completely out of the game when this inevitably passes

**Comment by DamianX** [comment]
duhh buhh grubdge duhhh

**Comment by ShiftyRail** [comment]
I don't think I've ever used those extensively, but they always more or less worked on my machine :tm: and since the unzoom thing got merged, were a decent alternative when some greedy HoS (which I will not speak the name) took the regular security cameras.

In other words, they are an inferior, but not bad alternative to the regular cams.

**Comment by TGFH** [comment]
They have been working for me very consistently unless I'm buckled to a chair.

**Comment by KingofHONK** [comment]
God fucking damn it why dont you tell me you were going to do this before I go and fix them. Welcome to my metagrudge list.

Edit: Try to fix them*** theyre still fucked admittedly. Still hate you.

**Comment by Jackreturnswithaveangenace** [comment]
Sorry @KingofHONK meatgrudge me all you like, I give you permission. I didn't even think about you before I did this. You didn't exist. You were nothing. (I decided to do this since I wanted to practice mapping and using github by changing stuff around before working on bigger stuff, sorry champ)

**Comment by Kurfursten** [comment]
The votes are clear

**Pull request merged**
