### PR TITLE
Fixes glitch in the matrix

### PR DESCRIPTION
**Pull request by Eneocho**
No longer will we have the faker and impostor's name where our beloved John Nanotrasen's name should be.
Changed because almost all of the times people have referred to the CEO ingame they use John Nanotrasen, including adminbuses, which gives it some legitimacy over the otherwise unused event name Johnson Lovelocker.

-->
:cl:
 * tweak: Changed the impostor CEO's name on the PDA events to the real CEO: John Nanotrasen.
 * spellcheck: Fixed one typo.

### CODE REVIEW

**Comment by WindowsErrors** [comment]
where is John P. Nanotrasen?

**Comment by ghost** [comment]
eneocho tier PR

**Comment by Hinaichigo** [comment]
Maybe you could change

> celebrating his birthday will well

to

> celebrating his birthday **with** well

**Comment by ValkyrieSkies** [comment]
But the CEO of Nanotrasen is Ned Nanotrasen (Sr).

**Comment by Cartlord** [comment]
...Why? Is there any specific reason he needs a silly name as opposed to a name you could actually expect someone to have?

**Comment by Eneocho** [comment]
Because almost all of the times people have referred to the CEO ingame they use John P. Nanotrasen, including adminbuses, which gives it some legitimacy over the otherwise unused event name Johnson Lovelocker.

**Comment by Exxion** [comment]
This concept becomes funnier and less stupid if you imagine that he changed his name to that some time after founding the company

**Comment by ValkyrieSkies** [comment]
I've seen John Nanotrasen alright, but where does the P come from?

**Comment by Armadingus** [comment]
John P. Nanotrasen is not my real CEO, he is a space communist and likely Syndicate as well.

**Comment by Eneocho** [comment]
> John P. Nanotrasen is not my real CEO, he is a space communist and likely Syndicate as well.

Found the revolutionary spouting fake news. Go back to cargonia.

**Comment by DamianX** [comment]
Mr. NanoTrasen created it, Lovelocker is just the current CEO.

**Comment by Eneocho** [comment]
At least let the voting decide to close the PR, Damian. It wasn't even a negative reception, there's more people that did want this merged than not.

**Comment by DamianX** [comment]
whatever

**Comment by tomacatx2** [comment]
Everyone knows that NanoTrasen was founded by John Trasen and his twin brother Jeff Nano

**Comment by JonathanSpaceStation** [comment]
His name is actually Jonathan Centcomm

**Comment by Kurfursten** [comment]
Amazingly we don't actually have a Lore tag, probably because it doesn't matter.

**Comment by Exxion** [comment]
Does it *really* have to include the P.? It just makes it sound even more like a shitty meme than it otherwise would

**Comment by Eneocho** [comment]
> Does it _really_ have to include the P.? It just makes it sound even more like a shitty meme than it otherwise would

It is the used-in-game name, which includes the "P.". And the "P." part is most probably a reference to John D. Rockefeller.

**Comment by Exxion** [comment]
Used in-game where?

**Comment by Eneocho** [comment]
> Used in-game where?

You're telling me you've never seen the adminbuses with the CEO? When do you even play, man?

**Comment by Exxion** [comment]
Like 2016
However, I can look through the logs and see that you, Eneocho, author of this PR and not an admin, are the only person on the entire server to mention the P, at least this year

**Comment by Eneocho** [comment]
Check further, I have clear memories of the buses mentioning the guy, it's why I used the "P." on this PR, it's how I was introduced to the CEO. So I use the "P.".

**Comment by Exxion** [comment]
From last year, there are about 11000 occurrences of the phrase "John Nanotrasen" in the logs and about 200 occurrences of "John P. Nanotrasen" with or without the period. There appears to have been exactly one bus using the latter name, lasting about ten minutes.

**Comment by ValkyrieSkies** [comment]
I still prefer Ned because the John (videogame) meme has been done to death.

**Comment by Eneocho** [comment]
> From last year, there are about 11000 occurrences of the phrase "John Nanotrasen" in the logs and about 200 occurrences of "John P. Nanotrasen" with or without the period. There appears to have been exactly one bus using the latter name, lasting about ten minutes.

I must've fucking realityshifted or some mandela effect bullshit because I remember the "P." way more often than not. Guess I'm removing the "P.".

**Comment by Blithering** [comment]
Never heard of this John P. Nanotrasen guy. Now John F. Nanotrasen, there's a man you can set your watch by.

**Pull request merged**
