### PR TITLE
Added a single missing wire in the packedstation engineering foyer.

### LINKED ISSUE #25632: Packed Station Engineering Foyer APC disconnected from grid.
image

[packed]

### LINKED ISSUE #25712: Packed engineering foyer apc not connected
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
1631fe43d05f3329a571b7e2a25b757c7bb88356

# Description
on packed, the engineering foyer APC is not connected to the grid. The missing wire is under a table to the left. Also what happened to the engineering SMES?
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by vltevev**
[bugfix]
[packed] 
closes #25632 & closes #25712
:cl:
 * bugfix: Adds a single missing wire in the packedstation engineering foyer.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
You need to put "closes #xyz" and "closes #abc" in the body of your PR to actually close the issues.

**Comment by SonixApache** [comment]
Title: Added a single missing wire in the packedstation engineering foyer.

body:
```
closes #25632 & closes #25712
```
🆑  is good

**Comment by tuypo1** [comment]
I dunno I kind of like it the way it is as I enjoy the confusion it causes, and it is my understanding it only makes the PA fail, not containment and that by the time it makes containment fail the sing has already become small enough to be harmless

**Comment by SonixApache** [comment]
you almost did it right
when i said :cl: is good that ment "don't touch the :cl: "
put `Added a single missing wire in the packedstation engineering foyer.` and `closes #25632 & closes #25712` somewhere else in the body

edit:
you got it, good job bud

**Pull request merged**
