### PR TITLE
Supermatter Cascade Overhaul

### PR DESCRIPTION
**Pull request by N3X15**
# Executive Summary
Fixes a buttload of Supermatter Cascade bugs, and provides some cosmetic upgrades.

# TODO
 * [x] Whoever coded the lighting shit did it wrong and it takes place AFTER the galaxy-wide alert thing
 * [x] Lights are green. (?!)
 * [x] Slow damage to the station not occurring
 * [x] Supermatter sea has some graphical issues
 * [x] Supermatter sea looks like shit
 * [x] Bluespace rift hitbox is 3x3 when it should fit the size of the sprite.
 * [x] Does not fuck with parallax colors (Would be neat to get brand new parallax textures but probably won't happen)
 * [x] <s>People have shovelled awful music into the apocalypse playlist, needs a review.</s> (Outside of PR scope)

# Screenshots
dreamseeker_2017-01-29_18-50-15
dreamseeker_2017-01-29_19-06-22
Latest bluespace sprites without edges:
dreamseeker_2017-01-29_20-09-51

# Changelog
:cl:
 * bugfix: Bluespace rift works again.
 * tweak: Minor consistency issues with supermatter cascade announcements have been fixed.
 * rscadd: New supermatter sea textures, also glows blue.
 * rscadd: Supermatter cascade now affects parallax textures.
 * rscdel: Lighting no longer goes green during supermatter cascade.

### CODE REVIEW

**Comment by Zth--** [comment]
Now we're talking

**Comment by N3X15** [comment]
Fixed the sprites having edges.

dreamseeker_2017-01-29_20-09-51

**Comment by Exxion** [comment]
Looks kind of shit
But still better than the current one so :woman_shrugging:

**Comment by Aurx** [comment]
It looks kinda shit because there's not enough sprite diversity and so you get runs.  Could use another two or three possible icons.

**Comment by kilozombie** [comment]
Or just the solid blue texture. No memes, that was much scarier.
Some weird funky crystals approaching you = uh oh.
The universe literally collapsing and turning into a flat, solid infinite blue landscape of nothingness = oh FUCK

**Comment by Exxion** [comment]
That was also a nice reference to the bug from which the term "bluespace" came
But several people were very unhappy with the flat blue texture

**Comment by kilozombie** [comment]
Yeah, yeah, I get. Still, nice in theory.

**Comment by Exxion** [comment]
Oh I wasn't disagreeing
I liked the solid blue

**Comment by kilozombie** [comment]
What about a server poll?

**Review by PJB3005 — APPROVED** [review]

**Comment by clusterfack** [comment]
Now we're talking

Oh damnit Zth beat me to it

**Comment by N3X15** [comment]
I personally liked the flat bluespace, because it was pretty clear it meant business.
dreamseeker_2017-01-30_01-06-09
dreamseeker_2017-01-30_01-08-26
dreamseeker_2017-01-30_01-09-26

**Comment by BobdaBiscuit** [comment]
Flat bluespace should be the icon, much more opposing and spooky looking, especially with the blue lighting.

**Comment by Exxion** [comment]
A border would be nice so it's less blocky, but other than that I like the flat bluespace

**Comment by Aurx** [comment]
Flat bluespace is best bluespace

**Comment by BobdaBiscuit** [comment]
Also add https://www.youtube.com/watch?v=68ugkg9RePc to the cascade playlist since it is now relevant.

**Comment by kol1th** [comment]
The original one looks really, really good. Better than just a flat blue texture for reference's sake.

**Comment by Riekland** [comment]
The plain blue square is objectively better
Make a server poll so it can be proven :^)

**Comment by N3X15** [comment]
<s>Just a note, I'm going to be out of town and on my folks' shitty 768k connection from the 1st to the 3rd and will be unable to work on this.</s>

Rescheduled

**Comment by Blithering** [comment]
I like the flat blue, but crystals are fun too. Maybe have some edge effects that bleed into the adjacent tiles so the edges aren't so abrupt.

**Pull request merged**
