### PR TITLE
Fixes several botany chemical reactions

### LINKED ISSUE #21353: Plant-B-Gone not working off of solanine
(WEB REPORT BY: seymourbutts REMOTE: 206.221.180.138:7777)
# Revision
4492b9c4e355ca292343e337d366499b2fd4d569

# Description
Plant-B-Gone recipe not using Solanine
# Steps to Reproduce
Attempt to mix Plant B Gone
# What you Expected
4 parts water 1 part solanine = Plant B Gone
# What Actually Happened
Contents dont mix

### LINKED ISSUE #27530: Plant-B-Gone recipe not working with solanine
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
494869bf587638c3801c775802d6cbdf00187705

# Description
According to wiki, solanine + water = plant b gone
http://ss13.moe/wiki/index.php/Guide_to_Chemistry#Plant-B-Gone
# Steps to Reproduce
mix solanine and water
# What you Expected
plant-b-gone
# What Actually Happened
solanine + water in beaker

### LINKED ISSUE #32624: Solanine + water doesn't react to form Plant-B-Gone
#### Description of issue
According to the wiki, solanine can be used to produce Plant-B-Gone. However, this reaction doesn't seem to function.

#### Difference between expected and actual behavior
Expected 20 units of solanine + 80 units of water to produce 100 units of Plant-B-Gone.
In actuality, the solanine and water remained in the beaker, unreacted.

#### Steps to reproduce
Add 20 units of solanine and 80 units of water to a beaker.

[bugfix]

### PR DESCRIPTION
**Pull request by kacurasuo**
[bugfix] [tested]

## What this does
This PR fixes bugs related to botany chemicals. Botany chemicals are defined as part of a list of components that fulfill the same "role," i.e. ```#define CRYPTOBIOLINS list(CRYPTOBIOLIN, PHYSOSTIGMINE)```. The reaction code iterates through all the reaction datums and initializes them into a filtered list based on the first element of the list of reaction components. This allows us to make some shortcuts in handling reactions - we get all the components of the reaction_holder, look in the filtered list for which reactions originate from each of the elements of the holder, and test each of the recipes in those lists. It saves a lot of processing time compared to testing every single reaction.

The issue is in the generation of the filtered list. The filtered list is generated with only the very first element of the chemical reaction, but that means if the first reagent is a list, like CRYPTOBIOLINS above, it will only generate the filtered list recognizing the first element of that list. This leads to many bugs. Reactions with botany ingredients work, but only if the botany ingredient is not part of the first element of the reaction list. This is why reactions with botany ingredients like hyronalin work (ANTI-TOXINS is not in the first slot), but insecticide and plant-b-gone don't (TOXINS is listed first).

With this PR, instead the filtered reaction list is initialized with all the components of the first element of the reaction list. This fixes many issues with pharmacognosy, including the reactions for plant-b-gone, insecticide, spaceacilin, suxameth, polyacid, and more.

As a note, this does amplify the effect of another existing bug where two colliding chemical reactions will use reagents for both but only produce output for one. That issue is not addressed here.

Closes #32624
Closes #27530
Closes #21353

## Why it's good
Fixes many persistent issues with reactions involving botany chemicals.

## Changelog
:cl:
 * bugfix: Fixes issues with initializing reactions where defined lists are the first reacting component.

### CODE REVIEW

**Comment by kacurasuo** [comment]
I don't know how to make it recognize both reactions without triggering the collision check.

**Comment by kacurasuo** [comment]
I made the unit test recognize alias reactions - it already didn't recognize all alias collisions from before for the same reason why the reactions didn't work.

**Comment by Eneocho** [comment]
Does this fix for example the Insecticide reaction not recognizing Solanine?

**Comment by kacurasuo** [comment]
> Does this fix for example the Insecticide reaction not recognizing Solanine?

Yes, and plant-b-gone too.

**Comment by Hinaichigo** [comment]
Nice.

**Pull request merged**
