### PR TITLE
Prompt Ghosts clicking on a blob core before putting them in.

### PR DESCRIPTION
**Pull request by gurfan**
What it says on the tin.

### CODE REVIEW

**Comment by DamianX** [comment]
This will allow you to steal it from the current controller, add sanity checks

**Comment by gurfan** [comment]
> This will allow you to steal it from the current controller

doesnt line 131 prevent that...? I tested it in game and you can't take control if someones already an overmind.

**Comment by DamianX** [comment]
You can if you open the alert(), then someone gets the overmind, then you click yes

**Comment by gurfan** [comment]
I didn't think about that, fixed now.

**Review by DamianX — APPROVED** [review]

**Pull request merged**
