### PR TITLE
Adds warning cooldown to vehicles

### PR DESCRIPTION
**Pull request by ghost**
Seems that mounting a vehicle and going on its keys with server lag would cause some users to crash as it tried to print out 'You don't have the keys' about 10 times a second, so now there's a delay function for any use of to_chat in canmove

### CODE REVIEW

**Comment by ghost** [comment]
Might as well say it here, sometimes it lags when you go towards a door without the access needed, happens with clown car and phazon memes

**Comment by ghost** [comment]
Guess I should report it instead of talking about it in a vaguely related issue eh?

**Comment by ghost** [comment]
The more details the merrier. Sounds like a problem with mechs

**Comment by Exxion** [comment]
It is
Mechs have no cooldown at all on *trying* to move. Only successfully moving.
This means they can play the door buzzer sound very, very quickly.
Also, walking into gibtonite with a drill out spams you with messages about safety features preventing that.

**Comment by ghost** [comment]
I think you can spam the door buzzer at hyper speeds when you go fast after drinking phazon so I don't think it's just a mech/vehicle thing

**Comment by Exxion** [comment]
It's not
But mechs are far worse for it than anything else can be
*Zero* delay, aside from what's inherent to the move loop to prevent the server from locking up whenever someone presses a button, I assume

**Comment by SonixApache** [comment]
goonchat was a mistake

**Comment by Exxion** [comment]
This has less than nothing to do with Goonchat

**Comment by SonixApache** [comment]
Doesn't goonchat do IRQ-tier freezing every time it has to parse a message?

**Comment by Intigracy** [comment]
the amount of lag/crashing when spammed with messages wasn't as bad before goonchat

**Comment by Exxion** [comment]
Oh
OK it has marginally more than nothing to do with Goonchat

**Pull request merged**
