### PR TITLE
Admins can now easily reset mobs' bodies using the Body Archive

### LINKED ISSUE #31127: datum/body_archive runtime
@DeityLink 

```
[08:05:07] Runtime in body_archive.dm, line 17: Cannot read null.owner_dna
proc name: New (/datum/body_archive/New)
usr: Unknown (as Alex Jones) (jakedb) (/mob/living/carbon/human)
usr.loc: The floor (272, 220, 1) (/turf/simulated/floor)
src: /datum/body_archive (/datum/body_archive)
call stack:
/datum/body_archive (/datum/body_archive): New(Unknown (as Alex Jones) (/mob/living/carbon/human))
Unknown (as Alex Jones) (/mob/living/carbon/human): mind initialize()
Unknown (as Alex Jones) (/mob/living/carbon/human): mind initialize()
Unknown (as Alex Jones) (/mob/living/carbon/human): Login()
Unknown (as Alex Jones) (/mob/living/carbon/human): Login()
Unknown (as Alex Jones) (/mob/living/carbon/human): Login()
Alex Jones (/datum/mind): transfer to(Unknown (as Alex Jones) (/mob/living/carbon/human))
/datum/surgery_step/head/attac... (/datum/surgery_step/head/attach): end step(Jack Mason (/mob/living/carbon/human), Unknown (as Alex Jones) (/mob/living/carbon/human), "head", Alex Jones\'s head (/obj/item/organ/external/head))
do surgery(Unknown (as Alex Jones) (/mob/living/carbon/human), Jack Mason (/mob/living/carbon/human), Alex Jones\'s head (/obj/item/organ/external/head), 0)
Alex Jones\'s head (/obj/item/organ/external/head): handle attack(Alex Jones\'s head (/obj/item/organ/external/head), Unknown (as Alex Jones) (/mob/living/carbon/human), Jack Mason (/mob/living/carbon/human), null, null)
Alex Jones\'s head (/obj/item/organ/external/head): attack(Unknown (as Alex Jones) (/mob/living/carbon/human), Jack Mason (/mob/living/carbon/human), null, null)
Unknown (as Alex Jones) (/mob/living/carbon/human): attackby(Alex Jones\'s head (/obj/item/organ/external/head), Jack Mason (/mob/living/carbon/human), "icon-x=17;icon-y=18;vis-x=19;v...", null, null)
Jack Mason (/mob/living/carbon/human): ClickOn(Unknown (as Alex Jones) (/mob/living/carbon/human), "icon-x=17;icon-y=18;vis-x=19;v...")
Unknown (as Alex Jones) (/mob/living/carbon/human): Click(the floor (272,220,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=17;icon-y=18;vis-x=19;v...")
Unknown (as Alex Jones) (/mob/living/carbon/human): Click(the floor (272,220,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=17;icon-y=18;vis-x=19;v...")
```

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #31127

https://user-images.githubusercontent.com/7573912/138987325-9d87ccec-25dd-48a4-98a0-5237239b7672.mp4

https://user-images.githubusercontent.com/7573912/138987347-cd11e5d5-437f-49c8-80bd-58f7ac8823b7.mp4

Admins can now use a mob's View Variables drop down menu to give them back their original body (a feature created for Cult 4's new reincarnation rune). This works even on ghosts, the only requirement is that the mob has a mind, as the body is archived when the mind is initialized.

Note that this drops all of a mob's currently equipped clothes and belonging.

Also fixed a runtime I guess.

:cl:
* rscadd: Admins now have the power to give players back their original body, even if it gets destroyed or transformed.

### CODE REVIEW

**Comment by SonixApache** [comment]
very good idea, :+1:

**Comment by Kurfursten** [comment]
It could be useful if there was an option to get their body from the archive without putting their mind into it. For example

>Person gibbed in my bus explosion and I want to bring back their body for paramedics to rescue but I need to do stuff to it before I am ready for their mind, like kill it
or
>Create someone's evil twin for a bus, just add fake mustache and a bored ghost
or
>I want to bus someone back in somewhere but I want the body to be dressed first

**Comment by DeityLink** [comment]
I can do that. I'll add all the body archives to a global list and and a new admin panel will access it to let you spawn clones at will.

**Comment by DeityLink** [comment]
there

**Pull request merged**
