### PR TITLE
Revert "Limb Health"

### PR DESCRIPTION
**Pull request by Kurfursten**
Reverts #24133

Not necessarily permanently, but I think we have gathered sufficient testing over the last 4 days to implement this properly.

Madmanmartian bit:
 "Working on fixing the problems people have pointed out."
#24267 
#24265

🆑 
* experimental: The exploratory change where limbs did not contribute to overall health has been reverted until further improvements are made.

### CODE REVIEW

**Comment by SonixApache** [comment]
it was a good testmerge

**Comment by Irradiation** [comment]
How is health real if your limbs aren't real?

**Comment by juanototo2** [comment]
>miss with epic laser gun and hit non-target limb

>effectively 0 damage applied

>run out of ammo before he runs out of health

🤔

**Comment by Intigracy** [comment]
I think it'd be worth removing the RNG aspect of shooting/hitting people unless you're drunk.

**Comment by Intigracy** [comment]
also

Moving away from stuns based combat is a good thing.

This change was a good first move away from stuns based combat.

**Comment by MadmanMartian** [comment]
can't valid as fast with it, so people don't like it

**Comment by agentofzog2** [comment]
> 
> 
> also
> 
> Moving away from stuns based combat is a good thing.
> 
> This change was a good first move away from stuns based combat.

But.... it nerfed everything but stuns....

**Comment by Intigracy** [comment]
Which makes non-deadly combat without stuns feasible.

**Comment by agentofzog2** [comment]
> 
> 
> Which makes non-deadly combat outside of stuns feasible.

Literally how?

**Comment by kilozombie** [comment]
Optimally I'd be able to aim at a guy's legs and laser them to make him fall over. A very brutish and reckless way to stun someone, but less lethal than lasering them to death. Unfortunately, having 70 burn damage on your legs doesn't currently make you fall over, probably because with our current system that'd be a bit funky.

Maybe widely-available lasers should have less damage, but more pain damage?

**Comment by boy2mantwicethefam** [comment]
This thing can be fixed by making it so that enough damage to a limb destroys it. But then you'd probably have everyone aim for the legs for a ghetto crit, so legs should be made so that having a destroyed leg doesn't knock you down but only slows you down a lot

**Comment by agentofzog2** [comment]
I feel like instead of doing all this and having the only "positive" change be that you can use lasers as a violent sort of disabler, you could just port disablers. 


I could see this being implemented properly with a lot of work, but I don't see it actually  happening given how this shit was just merged and the (absolute) state of other large scale projects like the economy and the black market.

**Comment by utilitas-** [comment]
mmmm better revert everything and then forget about it instead of actually trying out any changes first

**Comment by FudgePucker** [comment]
No really how does this "move away from a stun based" meta? It fucking nerfs everything but stuns.
If you get into an unarmed fight you will still go with disarm intent for the push down or harm intent aim for the mouth/head.
Booze bottle harm intent to the head, now there isnt a reason before to target another part other than the head before, now there really isnt one.
A stealth buff to armor and helmets, the only reason to change target areas other than head or chest was to avoid the armor. Now? Forget about it.
Stuns are king for a reason.

This is yet another lofty goal set by coders theory crafting that breaks the game (wow over a gigawatt of power passes though your body, just rub some ointment on your arm, you will be fine.) (Welding fuel tank explodes right next to you, you are still green health.), just like the economy update, where you make a radical change to bring in new changes, but they never fucking come. STILL HASNT BEEN A REASON TO KNEECAP MINER INCOME IN MONTHS, BUT HEY, AT LEAST ITS "BALANCED" FOR WHEN MORE ECONOMY UPDATES HAPPEN (never)

**Comment by SonixApache** [comment]
I'm okay with reverting and re-trying with a better attempt later.
Or changes could be made on the fly.

Don't think this should just be dumped, though.

**Comment by utilitas-** [comment]
Then think of a solid way how to treat this
I believe each limb should contribute brute, but only very little, so that getting all of your limbs mangled still does not mean you'll die if your organs are perfectly intact, you have all your blood and your chest and head are spotless. Like, 10 brute health per limb contributed to the whole.
But I also believe very low (20% and less) amounts of blood shouldn't deal ridiculous amounts of tox damage, maybe just slow metabolization of all drugs until blood is regained.

**Comment by Intigracy** [comment]
Robo is actively tweaking this to address the major problems and get it functional. It's not like he made the PR and then left others to fix it for him.

I think we should give him at least through the weekend to address major concerns with this before looking at a revert.

>why are we stagnant
>change is BAD

**Comment by incakola** [comment]
if we are talking about hitting legs to knock people down, then when i get shot in the leg I should be able to fire back from the floor because my hands still work
otherwise it becomes another method to stun

**Comment by MadmanMartian** [comment]
what if tasing worked like it did in IRL life, where it makes the muscles spasm?

Shoot a guy in the leg, he's down or kicked himself into the ceiling. Shoot a guy in the arm, he's either dropping the gun or firing it wildly into the air

Shoot a guy in the torso, nothing else around's going to be working

**Comment by agentofzog2** [comment]
> 
> I think we should give him at least through the weekend to address major concerns with this before looking at a revert.
> 

How about let's not leave the game in a broken state.

>
>why are we stagnant
>change is BAD
>

Lets break everything for no reason and then never fix it!

**Comment by MadmanMartian** [comment]
I'm having trouble reproducing the "I aim center mass and hit a shoulder" bug people are experiencing.

**Comment by agentofzog2** [comment]
> 
> 
> I'm having trouble reproducing the "I aim center mass and hit a shoulder" bug people are experiencing.

I have it happen when I target the head with a melee attack quite often. Chest attacks are more accurate I guess.

**Comment by MadmanMartian** [comment]
Oh, I was using a gun, that would be why

**Comment by MadmanMartian** [comment]
So, I've found that a lot of the complaints are unfounded or can't be easily remedied without changing a lot about the game itself (You can't miss with a ranged weapon it seems so those complaints are bogus, explosions do need some TLC but there's no way of doing it without somebody being angry that they're now too powerful, and balancing burn damage so it does something is a pain because it is also the most readily available source of damage on the station) but the votes and harassment are clear.

**Comment by SonixApache** [comment]
what a waste

harassment? really?

**Comment by d3athrow** [comment]
@MadmanMartian It took an AI a good couple minutes of door crushing to finally kill a guy because of your change.

Good way to make limb damage useful since it wouldn't kill would be to increase pain's effectiveness when limb damage exceeds a certain amount.

**Pull request merged**
