### PR TITLE
The Syringe Update (!?)

### PR DESCRIPTION
**Pull request by DeityLink**
Behold everyone! My most useless feature to date!
QoL obviously

:cl:
* rscadd: you may now use a pen to write labels on syringes.
* rscadd: syringes fired from syringe guns get to keep their label. (Unknown is hit by the syringe (Healing)!)
* rscadd: if a syringe fired from a syringe gun decays from traveling over 6 tiles, a broken syringe spawns in its place.

### CODE REVIEW

**Comment by Irradiation** [comment]
WHERE'S MUH QOL TAG?

Also just to clarify, syringes that currently travel further than 6 tiles outright disappear, right?

**Comment by DeityLink** [comment]
yep, I just tested on the server.

**Comment by Goldsteel** [comment]
I can't wait to be hit by a syringe of "JUICE THAT MAKES YOU GAY AND DIE"

**Comment by Kitfox88** [comment]
time for bone hurting juice

**Pull request merged**
