### PR TITLE
RETURN OF THE CLUWNE BAN

### PR DESCRIPTION
**Pull request by N3X15**
# DONUT MERGE
This is currently under testing, and still needs VGWS integration.

# Executive Summary
Back on my server, there used to be a way to ban people so that they became cluwnes on roundstart.

This brings that back using the /event API, but should be more reliable.

# Important Distinctions
This ban operates a little differently than normal bans, as it uses the same ban type but uses the duration to determine permanence.

* duration == -1: Permanent Ban
* duration >= 0: Temporary Ban

# TODO
* [ ] VGWS Integration
* [ ] Catbeast bans?
* [ ] Appeal Bans
* [ ] Ban/admin edition of cluwne that cannot die and cannot attack at all
* [ ] Testing

### CODE REVIEW

**Comment by CptWad** [comment]
cool and good
only issue I see is that someone deliberately taking up important job slots (head of staff, chaplain, AI) then becoming cluwne so nobody claims said spot. Should probably also default to assistant job position to prevent people from outing important job roles

**Comment by N3X15** [comment]
Already done, all cluwnes are assigned assistant prior to job assignment.

https://github.com/vgstation-coders/vgstation13/pull/15645/files#diff-ad5730becbdced110e633cef24155bb5R23

**Comment by N3X15** [comment]
I should also mention that a Cluwneban automatically jobbans you from all positions *except* assistant, so AI, head, and antag roles will not try to force them into something.

https://github.com/vgstation-coders/vgstation13/pull/15645/files#diff-c9da95830324d9b24daebaf98f064f2bR21

**Comment by Shadowmech88** [comment]
Can cluwnes talk? Can they use items?
Is there any reason for someone who is cluwnebanned to actually play instead of just observing or waiting it out?

**Comment by Exxion** [comment]
Cluwnes can never use items by virtue of having no hands
Unless these specific cluwnes are different, they can talk, but with nearly every word replaced with a HONK, rendering it almost entirely incomprehensible

**Comment by Shadowmech88** [comment]
Why would anyone who is cluwnebanned choose to play, then?

**Comment by Exxion** [comment]
Because they are not rational people

**Comment by Aurx** [comment]
We have code for detecting AFK admins.  We can tell when somebody logs in or out.  
Couldn't we make it so that cluwnebans last for a specified number of rounds, and a round doesn't count if you don't participate for a significant fraction of it?

**Comment by Icychocobo** [comment]
Well, what would even count as "participation" in this case? Shuffling around for ten minutes while spouting various volumes and pitches of HONK?

I mean, I HONK what the change HONK getting at, but HONK seems HONK little HONK HONK HONK HONK HONK HONK.  HONK HONK HONK lawn gnomes HONK HONK HONK station  HONK HONK HONK nuke.

**Comment by Exxion** [comment]
@Aurx Yeah, we COULD do that, but really I think this kind of ban is more for the memes
Like if we unbanned but cluwnebanned 2hotdogs or Sarca, they'd *definitely* still play
It would be like unbanning Kingston but forcing him to be a tajaran with infinite braindamage, but less personalized

**Comment by N3X15** [comment]
We could, but I'm not fucking with the database schema to enable that.

**Pull request closed without merging**
