### PR TITLE
Plasma cabbages can absorb plasma gas from the atmosphere

### PR DESCRIPTION
**Pull request by joaomarcosh**
This idea was suggested as a way to make plasma cabbages stand out more and give another way for botanists to help around the station.
The plasma cabbages do NOT require plasma on the atmosphere to survive, however, if plasma is present they will absorb it and increase the amount of plasma inside the product.

[wip]
:cl:
 * tweak: Plasma cabbages can absorb plasma!

### CODE REVIEW

**Comment by Eneocho** [comment]
Is the potency bonus an internal thing or does it affect the potency value itself? As in, if I have a gas chamber for my plasma cabbages, does it get more potent like if it had robust harvest in?

**Comment by joaomarcosh** [comment]
It should be "working" right now in the sense that it can absorb plasma and increase production but i still need to find a way to separate the variables for the plant and the product so each can have its own absorbed_gas value and also set up different absorbing rates for each.
For now i was thinking about making the products absorb only 25% of the amount the plant absorbs but all values are not final and will have to be tweaked later on.
And i do not know why its showing all of those pasts commits.

**Comment by joaomarcosh** [comment]
> Is the potency bonus an internal thing or does it affect the potency value itself? As in, if I have a gas chamber for my plasma cabbages, does it get more potent like if it had robust harvest in?

yeah thats basically how it works, just an added potency bonus. It was the simplest way i found to do it but the idea is that the absorbed gas will increase potency much more than just robust harvest.

**Comment by Eneocho** [comment]
My question was more like: Can this be used as an alternate way to get real high potency for xenobotany?
Also, can this "consume plasma to get stronger" trait be spliced into another crop? If not, please add it, it should be a Metabolism thing.
Is this adaptable, as in you could eventually add a plant X consumes gas Y? Or is it hard limited to blasma?

**Comment by joaomarcosh** [comment]
Since it uses a different variable it shouldnt affected the "real" potency used for xenobotany.
I had forgot about the splicing, but i will look into adding it.
Maybe through mutation but i have to check the code.

**Comment by Eneocho** [comment]
>Since it uses a different variable it shouldnt affected the "real" potency used for xenobotany.

A shame. I was looking forward to the dangerously autistic setups for 500 potency memes.

**Comment by Eneocho** [comment]
Make sure it doesn't get damaged by non air gases or it'll get damaged as it goes more potent.

**Comment by irish09slasher** [comment]
> My question was more like: Can this be used as an alternate way to get real high potency for xenobotany? Also, can this "consume plasma to get stronger" trait be spliced into another crop? If not, please add it, it should be a Metabolism thing. Is this adaptable, as in you could eventually add a plant X consumes gas Y? Or is it hard limited to blasma?

`	new_seed.gas_benefits =         gas_benefits
	new_seed.potency_bonus =        potency_bonus
	new_seed.absorbed_gas =         absorbed_gas`

I'm not sure how it currently works, however, in theory this "gas_benefits" trait could make it so that any plant that consumes a certain gas from the environment could receive a potency bonus from it. It provides possibilities for antagonist and station-helping xenobotanists alike. Can make ZAS plants or scrubber plants, as well as your previously mentioned use case of super potent plants with a gas chamber setup.

**Comment by Eneocho** [comment]
What gene controls that trait? Is it Nutrition? It should probably be nutrition (nut controls the carnivorous, parasitic, hematophage and gas consumption traits).
I was going more for the buff potency with gas then take the potency out for splicing kinda idea. Making a whole ZAS setup to get fucktons of potency fast then splicing said buffed potency instead of dedicated chambers for plants.

**Comment by irish09slasher** [comment]
> What gene controls that trait? Is it Nutrition? It should probably be nutrition (nut controls the carnivorous, parasitic, hematophage and gas consumption traits). I was going more for the buff potency with gas then take the potency out for splicing kinda idea. Making a whole ZAS setup to get fucktons of potency fast then splicing said buffed potency instead of dedicated chambers for plants.

If I'm reading the file correctly, it's not currently an acquirable xenobotany trait. None of these appear under any of the gene lists.

**Comment by joaomarcosh** [comment]
So far its just a concept model, i just hardcoded a few things to see what it would look like, its very far from complete

**Comment by Eneocho** [comment]
Why was this closed?
Please add the potency buff to the plant base so you can splice the 200 potency. You so rarely get to see 120+ potency in a normal round.

**Pull request closed without merging**
