### PR TITLE
Nerfs external blood loss, slays relative pathing

### PR DESCRIPTION
**Pull request by 9600bauds**
External blood loss has been slowed by 25%, though you'll still lose roughly the same amount of blood.

Lying down will reduce the amount of blood you lose from external bleeding by 30% (This goes a longer way than it sounds). If you can't stop the bleeding, your best bet is to lie down and call for help or have someone drag you.

Tweaked low blood level warnings to give a little of a warning transition between "mostly fine" and "going into shock".

Slightly tweaked the effect of low blood levels, previously medium blood loss would be deadlier than heavy blood loss. It will still kill you pretty dead.

Github is shit at diffs, here are the 2 lines I changed in wounds.dm in a non-shit presentation: http://i.imgur.com/YCQ84tc.png http://i.imgur.com/qwCzHlQ.png

### CODE REVIEW

**Comment by Ephx1** [comment]
> Lying down will reduce the amount of blood you lose from external bleeding by 30%

That sounds pretty neat. :feelsgood:

**Comment by ghost** [comment]
Does being buckled to a bed/chair count as lying down? It should count for beds at least as it's essentially the same position, and portable beds are a thing.

**Comment by clusterfack** [comment]
But I like blood loss

**Comment by Exxion** [comment]
FUCKING
THANK
YOU
BLOOD LOSS IS SO FUCKING ABSURD
TAKE ONE UNLUCKY HIT AND DIE A MINUTE LATER BECAUSE OF BLOOD LOSS YOU CAN'T STOP OR EVEN SLOW WITHOUT A BANDAGE

These changes sound great. Blood loss was quite often a death sentence if you were not _actually in_ or at least very near a medbay when you took a hit. Now lying down at least gives you a _chance_.

Also fuck off Riri there was no controversy when you tagged it as controversial

**Comment by 9600bauds** [comment]
@TermedClepe It counts for beds, but not for chairs because well, you're not really lying down when you sit down on a chair.

@clusterfack I've come to appreciate blood loss a little better now that I know exactly how it works, yet at the same time, testing only confirmed my suspicions. The majority of people in the thread and in-game come to agree that it's kind of ridiculous how fast and how easy you lose blood with the current system. And I realize it was mostly because of the "something did brute to me, run for 30 seconds afuk i'm dead" syndrome that bleeding compounded to.

Rather than make bleeding not dangerous (it still is pretty fucking dangerous) I tried to make it less bullshit. Lying down is to give an option to the player so they don't feel like they're helpless because they didn't powergame gauze. And the warning/slight tweaking of medium blood loss is so that the shock that kills you doesn't come out of nowhere.

**Comment by icantthinkofanameritenow** [comment]
@9600bauds

But you can't even do anything else when lying down though, so you're also putting yourself at risk of dying if nobody helps you- or worse, you become vulnerable to someone who might want to finish you off.

You're still going to be screwed if you aren't close to medbay or if nobody feels like helping you, it'll just cause you to linger just a little bit longer. Instead, lighter external bleeding should simply go away on its own over time so you don't risk bleeding to death from a paper cut.

Plus, I don't see how it would be powergaming to ask for a bit of gauze from RnD or the mechanic. It doesn't even require much in the way of research, at that matter.

**Comment by Exxion** [comment]
Light external bleeding _does_ go away on its own

**Comment by 9600bauds** [comment]
All external bleeding goes away on it's own, in fact it goes away pretty fucking fast. That was the issue.

**Comment by Exxion** [comment]
Not all external bleeding goes away on its own because it often kills you before it would

**Comment by 9600bauds** [comment]
fair point

**Comment by 9600bauds** [comment]
I think Clusterfack fucked up my commits

**Comment by unid15** [comment]
Do 

```
git pull --rebase upstream Bleeding-Edge
```

to fix your commits

**Comment by 9600bauds** [comment]
Still, how'd this happen

**Comment by clusterfack** [comment]
I thought this was merged ages ago

**Pull request merged**
