### PR TITLE
Changes from O² to O₂. 

### LINKED ISSUE #9191: We have a serious scientific inaccuracy.
#### Description of issue

The "No oxygen" warning: 

Has the 2 above the O, instead of below it.
#### Difference between expected and actual behavior

2 would be below the O
#### Steps to reproduce

Jump into space.
#### Specific information for locating

`icons/mob/screen1_Midnight.dmi`
#### Length of time in which bug has been known to occur

For basically as long as we have this HUD, years.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by SysadminJeroen**
Changes from O² to O2 (smaller and lower 2).
Closes #9191.

### CODE REVIEW

**Comment by clusterfack** [comment]
pics

**Comment by SysadminJeroen** [comment]
alium suffix lima 2016-04-01 202421
alium suffix lima 2016-04-01 202416

**Comment by unid15** [comment]
Do the other GUI files not have the same error?

**Comment by SysadminJeroen** [comment]
@unid15 Many GUI files have the "O2" with a normal 2, but many of them are very difficult to edit without making it way less visible.

**Comment by ihadtoregisterforthis** [comment]
O<sub>2

`O<sub>2</sub>`

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis Thanks.

**Comment by PJB3005** [comment]
Unicode to the rescue!

**Comment by Imagebard** [comment]
How did we go so long without this important change?

**Comment by ghost** [comment]
Well, remember that the optional recipe for Water has been 2 Oxygen 1 Hydrogen for like as long as Chemistry existed, which is certainly almost half a decade

**Comment by PJB3005** [comment]
@dylanstrategie [false](https://github.com/d3athrow/vgstation13/commit/24f24aea545355cb8d657f6746494c5616bb976f)

**Comment by Exxion** [comment]
OK but why was it changed to that?

**Pull request merged**
