### PR TITLE
Wizard Spell: Dimensional Push

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds a new spell which allows the user to teleport whatever he touches to a random non-space location on the same Z-level.
The user cannot teleport himself.

It does not require robes, and has a 30 second cooldown by default. Its speed can be upgraded 4 times, to a maximum of once per second, at a cost of only 10 points per upgrade, despite the spell itself costing 20 points.

:cl:
 * rscadd: Added a new wizard spell which allows the wizard to teleport whatever he touches to a random non-space location on the same Z-level.

### CODE REVIEW

**Comment by Diavill** [comment]
Is this only for people or can you teleport objects on the ground as well?

**Comment by Shadowmech88** [comment]
All children of `/atom/movable`. This includes mobs and objects.

**Comment by Arthurdentist** [comment]
None of these new spell PRs include single use spellbooks and that triggers me greatly.

Please resolve this.

**Comment by Megamaw** [comment]
f u n d  i t

**Comment by Shadowmech88** [comment]
Conflicts fixed.

**Pull request merged**
