### PR TITLE
Add icon for AA power cells.

### PR DESCRIPTION
**Pull request by twirling-jesters**
## What this does
Adds an icon for AA power cells that's distinct from normal power cells.

## Why it's good
Allows users to differentiate between normal power cells and AA, AAA and D cells at a glance.

## Changelog

:cl:
 * rscadd: Added icon for AA batteries.

### CODE REVIEW

**Comment by pedr69** [comment]
are those even obtainable?
and whats up with that sprite resolution

**Comment by twirling-jesters** [comment]
> are those even obtainable? and whats up with that sprite resolution

At least one spawns on box (see attached). Also I'm not sure what you mean by the sprite resolution-- The new sprite is 32x32.
image

**Comment by Eneocho** [comment]
>Also I'm not sure what you mean by the sprite resolution-- The new sprite is 32x32.

He probably means that it's kinda out of place for the AA cell to be that large whilst regular cells with a LOT more capacity are just a itty bitty rectangle.

**Comment by Kurfursten** [comment]
Yes, for consistency I would recommend a sprite around the same size as normal cells

**Pull request merged**
