### PR TITLE
Neural remote control

### PR DESCRIPTION
**Pull request by ComicIronic**
### Neural linking

Added neural link posibrains, which act like MMIs that a remote user can connect to.
Neural link brains have to be connected to a controller pod before they can be used.
Entering the controller pod then gives the user control over the given brain, which lets then move it around.
Just using the pod on its own won't do much, though: unless the user is wearing goggles, they cannot follow the brain.
Unless they are wearing an earpiece, they cannot hear what the brain hears.
The highest level of control is a neural connection, which puts the user in full control of the brain at the cost of awareness of surroundings.
Neural links are the only way to do things like ventcrawl, use mech equipment, or use robot modules.
Silicons under neural control have purple eyes.
Moved relaymove from client Move into mob Move.
Fixed some cases of Move not having consistent arg names.
Consolidated robot move into one place.
### Bot control

You can now control bots by putting a brain in them. This includes MMIs, which can become THE LAW, pack mules, medibots, or pretty much anything except farmbots, which aren't updated yet.
Added a general way for a mob's loc to influence its click.
Moved EDs under secbots.
Clicking while neural-linked to a bot lets you do contextual stuff as the bot itself.

The one thing I cannot seem to fix because it appears to be a Byond thing is the snap-back from editing client.eye, which wants to reset to client.current.

### CODE REVIEW

**Comment by PJB3005** [comment]
:+1: HOLY SHIT MAN WE NEED THIS!

**Comment by Probe1** [comment]
toasting in an epic bread

also that sounds pretty fucking cool.

**Comment by Midaychi** [comment]
Hos remote controlling beepsky 2015

**Comment by PJB3005** [comment]
More like HoS controlling ED-209's 2015

**Comment by Exxion** [comment]
This may well be a stupid idea, but what if (some types of) controllers could be hacked or emagged or something to control a number of things at once? As in they all respond to the same inputs at the same time. This clearly wouldn't work with vision, but hearing could still work with this.
To prevent such a system from being ridiculously OP in combat, maybe only one of the controlled mobs, picked at random, should respond to mouse input or something similarly limiting. Limiting enough that doing it could be fun but wouldn't really be useful.

**Comment by FudgePucker** [comment]
Wait if you use a MoMMI/cyborg like this do you still have lawsets or are you pretty much purged while controlling them?
If there isn't a lawset robotics would be the best traitor method of getting green text.

**Comment by ComicIronic** [comment]
I'm going to take controlled silicons off lawsets, but as an exchange they're going to have an obvious tell - green eyes.

**Comment by Midaychi** [comment]
Green eyes, everywhere

**Comment by ComicIronic** [comment]
>also that sounds pretty fucking cool. do science goggles now have a use or are the ear piece and goggles something new?

They're both new items.
If you don't want to risk a neural link, the goggles let you visually track the controlled brain and the earpiece lets you hear what it hears <s>and speak through it</s> not yet.

**Comment by FudgePucker** [comment]
Wait, so if I understand this right, its a cyborg/MoMMI like normal, but you can control it at anytime at one of the machines?
What if there was a traitor item for robotists that is a cyborg analizer that when used on a unpowered possibrain that removes what little ego it has and lets you have total control over it. Have it come with an implant that lets you neural link from anywhere, also installs the neural link incase it requires trusting someone else to do surgury on you.
This might be over powered (LIKE SCI TRAITORS AREN'T ALREADY WITH RESEARCH, Robotists also have toxins access.), but it would let you keep a empty MoMMI/Cyborg that you can basicly go braindead and control. Meaning that if you are arrested, you can have a sec cyborg waiting in a recharger to go and free you.

**Comment by ComicIronic** [comment]
It's now purple eyes, not green eyes.
Too many borgs had green eyes, and purple is a more noticable "what" colour.

**Comment by RemieRichards** [comment]
@ComicIronic 
>Moved relaymove from client Move into mob Move.

Danger Will Robinson!
Overriding ```mob/Move()``` is horrendously inefficient in comparison to overriding ```client/Move()```

**Comment by ComicIronic** [comment]
It's a mob-level interaction.
Efficiency has nothing to do with it.
Of the few times that relaymove is ever used in-game, they should all be handled at a mob level.
It is inconceivable that mob code managed to make its way into a client proc.

**Comment by RemieRichards** [comment]
@ComicIronic You're aware of the massive inefficiency of overriding ```mob/Move()``` in the case of performance right? not just in developing? as that's the one I'm hinting at.

```mob/Move()``` is hitler, and is a perfectly acceptable reason for ```client/Move()``` to contain the code.

**Comment by ComicIronic** [comment]
What's the performance impact?

**Comment by RemieRichards** [comment]
@ComicIronic I can't actually get any reliable profiling results on 508 that prove me right.
Either they've fixed it, or it's not strictly profilelable

You'll have to believe me here it does, or DID have a noticable impact, client/Move() overrides in a lot of my own work and things I've heard from others have always been preferable over mob/Move() overrides 

Perhaps it was a spooky ghost story they tell to children.

**Comment by ComicIronic** [comment]
I think it's moronic how much mob-relevant code is shoved into client Move.

**Comment by Midaychi** [comment]
Any chance of getting an implantable version?
Something that would take a protolathe and some science levels to produce, but can be injected into carbons and simple mobs?

It wouldn't have an effect if the mob has a ghost in it, but if it was just a mindless simple mob or a monkey Tajaran it'd have potential use for remote operation of cheap clones for dangerous activities.

**Comment by Shadowmech88** [comment]
Well, you could place the remote brain into a MaMI and then put that into a monkeyman.
If MaMIs are ever completely implemented that is.

**Comment by ComicIronic** [comment]
Yeah, MaMIs would be part of my implementation for that.

**Comment by Midaychi** [comment]
So what's the plan for actually adding this into the game? Is it going to be something you print from the protolathe/exosuit fab and circuit imprinter or something you build from scratch? Or something there's only going to be one of on the map and you've just not made a map commit yet to cut down on merge conflicts?

Also re: the neural link and consciousness transfer after host death, would it be something like this?

Wear neural link helmet, dose up on a whole bunch of toxins, enter pod and neural link to mommi or cyborg, body dies, player gets message about it, pod ejects ghostless body on the floor nearby and ghost stays in last remoted bot unable to eject because they lose the verbs for it? 

I guess you could just keep their purple eyes to denote they're valid or something.

**Comment by ComicIronic** [comment]
>verbs

This doesn't use verbs.
Ejecting is done through a UI button.
As for death, I haven't fully decided. It could trap the user in the silicon body as a result, but that might be too harsh.

The pod will not be available through traditional construction - it's too easily abused, especially by "I print guns and make my own rules" RnD. I don't want it to be adminspawn only, so it might end up as spaceloot you can get in roid rooms.

The rest of the PR in terms of MMIs controlling bots will always be available, though.

**Comment by FudgePucker** [comment]
Aww man.
Will there at least be a way to use it as a traitor robotist?
At least I can tell the clown that I am going to put him into a H.O.N.K. but then really put him in a buttbot.

**Comment by Midaychi** [comment]
Lame

**Comment by Praecordia** [comment]
sounds pretty cool, merge when?
for death honestly just do what Midaychi said, if your carbon body gets whacked while you're busy pretending to be a borg then emergency safety features shunt your consciousness to the borg body, or if the remote controlled borg body dies then you wake up in the pod/wherever you put on the helmet stunned with ~20 brain damage from neural feedback

**Comment by clusterfack** [comment]
YOU DIE IN THE GAME YOU DIE IN REAL LIFE

**Comment by Shadowmech88** [comment]
In-game VR MMO when?

**Comment by Midaychi** [comment]
Actually this could probably be used for some antag stuff. Especially if you could hide the purple eyes thing and do some anti-meta stuff to the cyborg blowing console.

Vox Raider and Nuke Ops both could start with one of these devices and a remote brain printer, so they'd have a stealthy infiltration option. 
 
You could make a new antag too (or use abductors from tg) that focuses more on stealthy approaches and stealing people/stuff.

**Comment by IratePirate** [comment]
How will this interact with Malf mode and rogue silicons?

**Comment by clusterfack** [comment]
By ventcrawling your mommi to the AI and murdering the shit out of it of course

**Comment by Midaychi** [comment]
He means that he intends to make it rare enough that it probably won't effect malf balance, but its also not designed around balancing for malf.

I guess if he makes it asteroid room loot (and he should also totally make it a large artifact) then you have to assume either they're a miner or a scientist and got hilariously lucky or the malf round is dragging out really long.

Then you either have a miner with a piece of equipment they'll probably keep in mining or quartermasters and not know what to do with, or a scientist with maybe a piece of equipment they know what to do with.

If the second, then they might build a mommi or a cyborg if they're not murdered by one while trying to do so.

If successful, then they could probably impossible mission their way to the ai core and try to take it out before a cyborg responds and crushes them.

That's of course assuming comic doesn't add ID level changes. If Comic makes the remote borg inherit ID from what the person in the pod is wearing, that might become a little more difficult due to door access and stuff

Also I hope comic makes it so the pod itself is loot, and you can stuff metal and glass in to print as many remote brains and head equipment as you need. Otherwise it might get a little silly with the asteroid rooms or something. Either you'd be missing vital unobtainable equipment or a bunch of shit would spawn on a single tile during mapgen and you could only use it once.

**Comment by FudgePucker** [comment]
I still like my idea of a robotist traitor item that lets you synch with a posibrain anywhere by showing up as brain dead while you are inside.

**Comment by Midaychi** [comment]
From now on, punishments that would usually result in forced cyborging shall now instead be forced buttbot-ing, and the source of the butt shall be the offender's own body.

**Comment by ComicIronic** [comment]
I think sticking a man's head up his own ass counts as cruel and unusual punishment.

**Comment by Midaychi** [comment]
Implying it wasn't already there in the first place.

**Comment by Midaychi** [comment]
Alright I tested this a bit on my own local server. There was a lot of weird shit going on in the console with qdel, and some gradual super clientside laggyness, but I'm not entirely sure that was due to this pr.

Problems:
1. You don't inherit the name of the simple bot when neural linked, so it comes out as the name of the remote brain.

2. using the goggles/earpiece, you can only see through the eyes of the remote linked target when moving. When not moving, it returns to the pod.

3. Medbots for some reason have their power light linked to screwdrivering, and appear to be off when in use with neural link. Also you can't inject anyone unless they're actually injured. It'd be neat if the power button was purple rather than red.

4. You can open a bot's interface, then go into the pod and the interface stays up. The bot can still use the panel too. Not an issue currently because the bot 'doesn't have enough dexterity' to modify its own options.

5. Bots really need a flashlight or some optical mesons. Fucking dark-ass maint. And beepsky/ed need sechud overlays. And medbot needs medhud overlay.

6. If an admin is stupid enough to ckey themselves to another mob while neural linking, it can cause problems if they then take the brain out and link it to another pod or do silly things. In normal play, this stuff probably won't happen.

7. Remote linked mulebots move fuck-fast. Like, sanic speed janicart style. Even without their engine wire cut.

8. You can't rename your cyborg when remote braining. You're never given the option. 

9. Synthetics that would normally get laws still get the laws even when using remote linking. They're 100% susceptible to the robotics control console too. Not sure if intentional? I didn't get to test but they might also link to ais.

10 I was too dumb to figure out how to eject a mob from a pod, so idk if that works or not.

**Comment by ComicIronic** [comment]
>2 using the goggles/earpiece, you can only see through the eyes of the remote linked target when moving. When not moving, it returns to the pod.

This is either a Byond issue with the way the eye works, or something buried in life code that insists on resetting the mob's eye to its loc even when it's set to something else. I can't tell which, and either way it's not immediately fixable without codediving.

>Also you can't inject anyone unless they're actually injured.

This is deliberate. A medibot with a brain still using the medibot diagnosis tools: they can't force an injection.

>11

I have no idea. Probably a Byond seed thing.

>23

This is deliberate. It is the most useless part of the pod.

>19

That's just how the code works with mobs.

>9

Partially intentional, but the laws shouldn't show. The robotics control is there as a balance check.

All the naming things are intentional. You can rename a borg by pen if you want to, I believe, but I wanted to make it obvious where the bot was being controlled by a brain in it, which includes speaking.

**Comment by Midaychi** [comment]
If you could install encryption keys and glasses and a flashlight and an id card into radio enabled mmis then this would fix issue 5 17 and 27

**Comment by Midaychi** [comment]
rip

**Comment by Praecordia** [comment]
why does the cool stuff always get forgotten
rip in piss cool feature
we hardly knew ye

**Comment by clusterfack** [comment]
Feel free to adopt this anyone

**Comment by Midaychi** [comment]
deeed

**Comment by Midaychi** [comment]
When is updoot?

**Comment by Zth--** [comment]
when you fix it

**Comment by PJB3005** [comment]
Literally dead

**Comment by Shadowmech88** [comment]
RIP in peace.

**Comment by BobdaBiscuit** [comment]
Aight hold my beer I've got my necromancy hat on!

**Pull request closed without merging**
