### PR TITLE
Snowmap Changes

### PR DESCRIPTION
**Pull request by plosky1**
[snowmap]

Mechanics office has a disposals bin, kitchen/hydro opened up and expanded, fences around shuttle areas. Also new concrete paths.

I was gonna do a maprender, but it crashes my dreammaker because this map sucks, so whenever someone else feels arsed enough to do one, there'll be one. It's not mean to be secret.

Also someone pls change sekret repo min pop to 20 or something.

:cl:
 * rscadd: The snowmap engineers Nanotrasen sent have been hard at work, they've braved the icy snow and added concrete paths! Mechanics office has it's own disposals now, and we've updated all the firelocks. We also noticed a lot of you running into clearly marked shuttle areas. These areas now have fences.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Mapdiffbot broke, post pics

**Comment by plosky1** [comment]
Removed the tunnel, fixed the concrete path, made it so that it doesn't slow down even during blizzard. Do I still need a pic? I'd have to manually piece it together..

**Comment by Kurfursten** [comment]
Can you give us the before and after distances between stations if not a picture?

**Comment by SonixApache** [comment]
take some fully zoomed out ghost pics

**Comment by bathosbathtime** [comment]
Don't like the baby-proofing of the shuttles but otherwise seems fine.  Less tedium is always welcome.

**Comment by plosky1** [comment]
The fences can have holes cut through them for the enterprising traitor. As for pictures, I'll put some up when I get home.

**Comment by FudgePucker** [comment]
Maybe add the ability to climb a fence with no items in hand. Unless charged, then you aren't climbing that fence even with glubs

**Comment by plosky1** [comment]
movement

**Comment by SonixApache** [comment]
Better, I guess. Honestly makes me wonder why the doors aren't just on the sides with the paths.

**Comment by ComradeDispenser** [comment]
I don't think I like the idea of tiles that don't slow down movement. 

Being "snowed in" and not leaving the station you're in because of the blizzard and the distance between the sub-stations is part of the map's charm.

**Comment by ghost** [comment]
I coded in those asphalt paths, they're functionally identical to the other "permafrost that get snowed on but never builds up a snow bank" tiles that were there before.
Edit: I see plosky changed the turf_movement_speed to 0 but unfortunately the setup for blizzard sfx makes it so that it gets changed to blizzard speed anyway. I would recommend keeping them as is since asphalt tiles don't ever get slowdown from the built-up snowbank. A snow tile with 20 cm gets slowed down much more than one with 0 cm.

**Comment by plosky1** [comment]
I can confirm on local tests that blizzard slowdown speed does not affect the tile if you hardcode speed in. When I changed it I ran tests on my local build, and while regular snow tiles would slow down speed, those would not.

I'm also going to take sonix's suggestion and make it prettier.

**Comment by plosky1** [comment]
Alright well I've now removed the slowdown on the concrete tiles, but they're still the main path because it just looks better and I fixed them breaking.

Cleaned up the path, not quite what Sonix suggested, but definitely better than before. Also added rooms with tiling so you can see the disposals madness @Kharkov72 made. Probably should have done this anyways.

newmove

**Comment by plosky1** [comment]
If checks pass, should be merge ready.

**Comment by ComradeDispenser** [comment]
Wait so do you walk at normal speed on concrete and you aren't slowed down by blizzards? 
Doesn't that remove the point of blizzards if you can get through them with no slowdown?

**Comment by plosky1** [comment]
That's what it was before, but I reverted it so the concrete tiles slow you down the same as all the other tiles do.

**Comment by tuypo1** [comment]
That's way too close together, the current distance is perfect.

**Comment by Lokiamis** [comment]
I like them being further apart. Bringing them closer together makes people fear being caught in storms less, reduces opportunities for had guys to make use of the uniqueness of the map, and generally just makes it less special.

**Comment by plosky1** [comment]
Ok well since the distance change appears to be unpopular, here's what I'm gonna do. I'm gonna revert the distance back to how it was, possibly streamline the path a bit more, keep the new gravel tiles (which for now are just visual changes), and keep the other stuff I've changed that's not related to station distance.

**Comment by plosky1** [comment]
movementreverted

**Comment by plosky1** [comment]
Cleaned it up a bit, but distance is back to what it was before. Other changes mentioned in original post are still there.

**Comment by plosky1** [comment]
Forgot to remove the snow footstep sound for asphalt. As of now, there is no sound which is in line with the rest of the tiles ingame. If someone wants to add custom sound, they are free to do it.

No more changes anticipated, ready to merge if approved.

**Comment by Kurfursten** [comment]
Update OP

**Comment by plosky1** [comment]
Done.

**Comment by ComradeDispenser** [comment]
Since you moved the stations back to their original locations I now remove my thumbs down and give it a big thumbs up

**Pull request merged**
