### PR TITLE
AI integrity restorer no longer shows law 0

### PR DESCRIPTION
**Pull request by DamianX**
People in #13400 seemed to be in favor of this
Completely untested. Didn't even try to compile.
:cl:
 * rscdel: AI integrity restorer no longer shows law 0

### CODE REVIEW

**Comment by jknpj** [comment]
why?

**Comment by DamianX** [comment]
> In my view, there's two perspectives to it. From MUH LORE/RP/whataver, NT tech and policy is notoriously shoddy and half-assed in various respects. Law 0 and ion laws don't show on cards due to underflow errors or some such, come up with your own justification it does not matter much.

> For GAMEPLAY, it does little to nerf the balls-to-the-wall blasma murder rampage AIs that people get pissed experiencing, and instead undermines the AIs that attempt to take a more subtle approach to their antagonizing. If you believe that XYZ only has vaporous suspicions that you're doing funny things, then you can let them card you, observe no subversive laws, and persuade them to re-core you. And if they had more concrete evidence and they wipe you on the spot, then your gamble failed; it happens, oh well. But if they can just take you to the integ restorer to confirm that you're a tater shit and get you got thereby, then once someone starts knocking at your upload with a card, your only feasible option is to kill kill kill. Which I think people dislike more than sillycunt subtlety. Perhaps.

In short, for fun. If people can't know you're a tator by simply looking up law 0 in the integrity restorer you support more fun gimmicks other than IF THEY'RE BURNING IN PLASMA THEY CAN'T GET TO THE CONSOLE XD

**Comment by ghost** [comment]
Like when it came up months ago, it has the same issue as vampire/cult/rev in that because they have a way to test, if they know about it they will always go for it after the slightest suspicion and wont stop because it's easy to blow borgs and kill the turrets. If you were trying to just be malfunctioning instead of a murdercunt with your law 0, this response immediately shoves you into murdercunt land because you both know he wont stop until you're in a card in the restorer if he knows about it. Not having that can make them hesitate from knowing they own the consequences if they're wrong. Also goes the other way from since you can't know it's clean, all 11 people in the whole playerbase that actually know how to repair you wont because they can't be sure.

**Comment by CptWad** [comment]
Theres only two reason to card the AI: Its killing people or it asked to be
nobody cards the AI to "Check if its antag" even if they did thats real fuckin shitty
While this does prevent people from checking if the AI is antag, consider the gymnastics required to actually end up carding the AI instead of killing it beforehand.

**Review by PJB3005 — APPROVED** [review]

**Comment by SonixApache** [comment]
i was checked for antag by being carded by a captain just yesterday

**Pull request merged**
