### PR TITLE
Circuits 2.0

### PR DESCRIPTION
**Pull request by PaulRitter**

### CODE REVIEW

**Comment by dunsel-hordon** [comment]
Don't forget to include where you can throw your id or pda at an airlock and open it

**Comment by DeityLink** [comment]
>+16,872,418

**Comment by Exxion** [comment]
Last I checked the codebase had like 400000 lines. That was a long time ago, so it's probably more now. But if it's 500000 now, this multiplies it by over 34. I suspect something is fucked up.

**Comment by Exxion** [comment]
Apparently most of that probably comes from the map files and when they were converted to TGM, and will probably just disappear if you rebase

**Pull request closed without merging**
