### PR TITLE
Delete Lotto

### PR DESCRIPTION
**Pull request by adacovsk**
Seems pointless to me. With this event gone, better events can trigger

:cl:
 * rscdel: Removed random lotto

### CODE REVIEW

**Comment by Armadingus** [comment]
My **_money._**
But in seriousness, this event could be a lot better, like there's no way to know who has won the lottery without being the winner or checking a newscaster if the event triggered and then looking up at the accounts database to see which account got the money, even a department debit can win the money.

Like, I want to believe that this event can cause some money hungry antag to rob a guy but it just doesn't happen. It's a pretty poor event.

**Comment by adacovsk** [comment]
>It's a pretty poor event.

W2's lotto tickets are better than this, would be a good replacement

**Comment by SonixApache** [comment]
i will miss this holdover from ancient baycode

**Comment by WindowsErrors** [comment]
i don't think i've ever even seen this event what's it supposed to do

**Comment by adacovsk** [comment]
> i don't think i've ever even seen this event what's it supposed to do

it gives money to a random person or department, and tells you on the news feed, that's it

**Comment by DamianX** [comment]
I just downvoted your PR.

FAQ

Q: What does this mean?

A: The amount of thumbs down (emojis) on your Pull Request has increased by one.

Q: Why did you do this?

A: There are several reasons I may deem a Pull Request to be unworthy of positive or neutral emojis. These include, but are not limited to: Removing anything, fixing bugs I deem features, grudgecoding (yet to be defined).

Q: Am I banned from the GitHub?

A: No - not yet. But you should refrain from making Pull Requests like this in the future. Otherwise I will be forced to issue an additional thumbs down, which may put your Pull Requesting and posting privileges in jeopardy.

Q: I don't believe my Pull Request deserved a thumbs down. can you un-downvote it?

A: Sure, mistakes happen. But only in exceedingly rare circumstances will I undo a thumbs down. If you would like to issue an appeal, shoot me an e-mail message explaining what I got wrong. I tend to respond to e-mails within several minutes. Do note, however, that over 99.99% of downvote appeals are rejected, and yours is likely no exception.

Q: How can I prevent this from happening in the future?

A: Accept the downvote and move on. But learn from this mistake: your behavior will not be tolerated on GitHub. I will continue to issue downvotes until you improve your conduct. Remember: GitHub is a privilege, not a right.

**Comment by DamianX** [comment]
Should have asked W2 to do this in his PR. They would have never seen it coming.

**Pull request closed without merging**
