### PR TITLE
MedHUD Buffs

### PR DESCRIPTION
**Pull request by Kurfursten**
Fulfilling some thread requests
untitled

🆑 
* rscadd: Doctors, virologists, geneticists, paramedics, and CMOs now spawn with MedHUDs equipped.
* rscadd: Chemists now spawn wearing science goggles.
* rscadd: MedHUDs now display the current medical record status next to the health bar in five colors (Blue = Active, Yellow = Physically Unfit, Red = Disabled, Gray = SSD, Black = Dead)

### CODE REVIEW

**Comment by SonixApache** [comment]
Fix records so SSD is a thing you can set again

**Comment by Kurfursten** [comment]
As per my testing you could set SSD from the HUD itself

**Comment by SonixApache** [comment]
yeah, but not from the records machines

**Comment by jknpj** [comment]
I don't like how it uses the same spot that antag huds use

**Comment by Kurfursten** [comment]
Don't worry, I thought of that, it won't show record overlay when you are ghosting with medhud on, only when using the doctor's medhud

**Pull request merged**
