### PR TITLE
LOOC Toggle

### PR DESCRIPTION
**Pull request by stewartspicer**
:cl:
* rscadd: Added a verb for muting LOOC and makes the toggle OOC verb seperate from LOOC

### CODE REVIEW

**Comment by stewartspicer** [comment]
I'm not very familiar with git, but I think I finally got this figured out. If it still isn't right, please correct me

**Comment by stewartspicer** [comment]
Also didn't know how to select only the commits I wanted, but you can check the files changed and see that it worked out, even if the commits are a mess

**Comment by PJB3005** [comment]
Commits being a mess is not a problem because we squash merge them into a single commit.

**Review by PJB3005 — APPROVED** [review]

**Comment by Probe1** [comment]
I hate to say it but not only is this not in the style we accept.. it already exists.  Good work on coding it right though.

**Review by Probe1 — DISMISSED** [review]
It already exist.

**Comment by Intigracy** [comment]
this is an admin verb lmao

**Comment by MidnightGlow** [comment]
Not gonna lie, I'm not totally sure how to properly add a changelog for this

**Comment by PJB3005** [comment]
@MidnightGlow don't need to add your name to the end of the changelog entry, it uses your GitHub username already.

**Comment by stewartspicer** [comment]
Alright, then it should be ready to merge now

**Pull request merged**
