### PR TITLE
Bus Station

### PR DESCRIPTION
**Pull request by Kurfursten**
A little over a month ago when there was a fever pitch in the thread over frustrations with Taxi, I suggested an overhaul to the entire map. Probe liked the design, but it was too much to ask of him because it was such a big change. **Basically, the idea was to redesign Taxi from the ground up to place the Taxis as far apart as possible to make it harder to sabotage both at once and reduce bottlenecking.** This redesign follows that idea, along with including more maintenance and enlarged rooms. I can't take credit for many of the key ideas from this map, since inspiration was drawn from the thread and from the other maps we use. Here's a basic summary of what I consider to be the most important changes.
- Some of the rooms which needed space the most were enlarged. All xenobio cells sized up 2x2 -> 3x3, security cells increased from 2x2 -> 2x3, botany increased from 8 trays to 18, and many other offices enlarged (head offices, QM office, kitchen, IAA office, library, etc.)
- R&D + RD reunited with the rest of the science team on one station. IAA, Library, and Chapel also reunited with the rest of the civilians.
- Maintenance is now much larger and includes some of our 'greatest hits' of maintenance rooms (ghetto botany, ghetto bar, etc.)
- Medbay has been entirely restructured to promote better flow of patients
- Security quality of life (the familiar security atmos and security disposals from Box, patrol route for Beepsky, hardsuits moved out from the armory)
- Disposals space sorter is now a mini-station with safe atmosphere.
- Brought back missing (or halfway-done) rooms from Taxi: holodeck, teleporter, dorms, laundry room
- A number of small quality of life changes (e.g.: telecommunications is now properly turret-protected and has a gas sensor, bhangometer now within comm range, sound systems in almost every room, dedicated borer hatching chamber, etc.)
- Makes full use of layered pipes. Pipes never go under walls when they don't have to: scrubbers are fully layered with distro.
- _There are many more differences, but creating an exhaustive list in a complete remake seems fit for Sisyphus._

**Experimental/Gimmick**
Since this is still a prototype, there are a few things I've done that were a significant break from the original spirit of Taxi that I think are worth trying out, and are mostly sourced from suggestions in the thread. My hope is to be as upfront as possible with this stuff: I'm not trying to sneak it in under anyone's nose, and we can have a full discussion about the pros and cons.
- Every station is equipped with an EVA loaded with space pods and civilian space suits. This is to promote alternate means of transportation between stations, as well as survival in extreme situations such as bombings. Requires standard EVA access to enter.
- Telescience was moved to the Paramedic room as an experiment.  One of the biggest complaints about Taxi was that paramedics couldn't save victims in time due to Taxi congestion, and it's no secret on the repo that I've long thought that Tsci should be in the hands of paramedics. I think it's a gimmick worth testing out on one map.
- Engine switched to TEG and Toxins TTV count lowered to 2. Another major complaint that was any damage to Taxi spirals to to catastrophic levels very quickly. By moving away from the Singularity and reducing the TTV count, hopefully there will need to be more strategic decisions about how to end shifts as opposed to simply bombing all three.
- One sepia camera spawns in the chapel. Think of it like the detective's thermals on Meta, a little perk for the chaplain to make Bus a little different.
- Xenobiology starts with tier 1 colored slimes (and one gray) instead of all gray slimes. A trade-off for having less working chambers than other maps. By including two of the most basic colors (metal and purple), Xenobiology can start moving in their preferred direction just a little faster.

civeng
medsili
secsci

### CODE REVIEW

**Comment by ghost** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by IratePirate** [comment]
Neat as fuck.

**Comment by ghost** [comment]
Not a big fan of the 5 tile hallways though

**Comment by Kurfursten** [comment]
@DrCelt Yeah, that's definitely something I'm flexible on. I discuss it a little more here (#6869) at the very bottom of the issue discussion.

Reducing it to 3 is definitely doable.

**Comment by Arthurdentist** [comment]
Train station when

**Comment by CptWad** [comment]
Wow it's 10x better. :+1:

**Comment by Kurfursten** [comment]
@Arthurdentist Jokes aside if Velard ever finished his moddable space pods this map would be way cooler. It's still neat to hunt between the EVAs for the pod design you want, but this map is just begging for more customizeable pods.

**Comment by LordMyroc** [comment]
Two issues that I can think of:
- Sepia camera for the chaplain seems like a bad idea to have from the start on any map, it promotes metagaming much more than detective thermals do. Though maybe I'm just biased because I don't like the sepia camera in general.
- Robotics and RnD being separate from each other seems like a bad idea because a lot of Roboticists tend to work in RnD as well as the robotics lab, especially if there are no other scientists willing to do research. I'm okay with the robotics lab being on the medical/silicon station, but adding a mini-RnD office to the robotics lab would be nice so roboticists who want/need to staff RnD don't have to constantly switch stations.

Other than that holy shit my dick is diamonds.

**Comment by SysadminJeroen** [comment]
Looks neat, but how can we make sure that both taxi's won't get bombed?

**Comment by CptWad** [comment]
@LordMyroc I actually want to see the robotics-rnd split happen just to see how the dynamic changes. Its definitely something we can leave as is since it might be worth testing, to see if robotics NEEDS to be next to rnd or if it can live independently. Means making combat mechs is a bit more legwork.
As for the sepia camera, its one item, if its a problem it can be removed.
@Jeroen52 its the main problem with this idea of a map. though the potential of the map outweighs the bombing issue, its how taxi was allowed in the first place.

**Comment by SysadminJeroen** [comment]
@CptWad Since the Taxi stations are all on the same Z-Level, if this map is on the same Z-Level and there are civilian EVA suits is it possible to build an emergency catwalk to the other station or is that not realistic?

**Comment by CptWad** [comment]
thats entirely possible. Would cost a stack of metal or two.

**Comment by ihadtoregisterforthis** [comment]
> bus station
> doesn't have a bus system

**Comment by Zth--** [comment]
Jeroen52, that was already done at least once by a mommi. If you break a single window, you lose all the pressure tho

**Comment by Kurfursten** [comment]
@Zth-- Since he mentions suits I think he just means he wants to throw down some lattices so that people can safely spacewalk between stations

Definitely doable, and in fact a fun project if you want to wire all the stations together

**Comment by SysadminJeroen** [comment]
@Kurfursten Precisely what I mean, especially if the taxis get bombed.

**Comment by FudgePucker** [comment]
What about being able to fix the taxi call buttons on the derelict station?
That could solve some autism breathing room problems. Also taxi derelict is best derelict

**Comment by Cyadox** [comment]
@Zth-- I've done it once before as a MoMMI with a full engineering/borg compliment. We only got two stations connected but what you do is segment the walkway with several sets of doors and multiple air alarms. It's a headache but breaches were much easier to handle.

**Comment by FudgePucker** [comment]
Combining the stations would only be hard in three factors, lack of external airlocks and hull space outside maintenance, knowing positions of other stations to make the bridge not have a bunch of zigzags, and time. Time being the big factor because taxi rounds last less than thirty mins because SHUTTLE HAS BEEN CALLED:this isn't box

**Comment by ihadtoregisterforthis** [comment]
map render pls

And at risk of making you angry for mapping, copypasting the rooms that are just fine from taxi is really cheap. I can only hope it doesn't "burrow" taxi's derelict and asteroid.

**Comment by PJB3005** [comment]
Could you take a proper screenshot of engineering because it's not on the picture: I can't review the TEG correctly.

Also, pretty sure that using BYOND's built in screenshotting (F2) will capture a 1:1 scale image independant of view size.

**Comment by CptWad** [comment]
@ihadtoregisterforthis i liked taxi's derelict

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis I think you missed the point entirely of the project.

@PJB3005 It works fine, I've tested the output.

**Comment by ihadtoregisterforthis** [comment]
If the idea is to replace taxi with a map that does the same but better, redoing all departaments is a must. In this case the actual taxistation would still exist.
If what you want is disassemble the station and work with the existing parts then there is no reason to rename as new.

What is precisely the point of the project?

**Comment by Kurfursten** [comment]
The idea is to do what Defficiency did to Efficiency, Metaclub did to Metacide, etc. In the same way, "Bus" is a reference to Taxi. The asteroid has had a little bit of clean-up work to modernize it and make it work, but overwhelmingly it remains the same. Why scrap what Taxi does well? People like the asteroid from what I can tell (with the exception of it perhaps being a bit too large).

I assume you're just asking for some minor trivial changes? There are already a few such as the structure of the top of the outpost. Maybe more will be forthcoming if people point out some good worthwhile changes. The next commit I intend to update research botany on the asteroid, but admittedly it wasn't so much a concern as getting something up. Probe wanted me to make an early PR a week ago.

asteroids and derelicts

**Comment by ihadtoregisterforthis** [comment]
No, what I wanted is for the asteroid and derelict to stay exclusive, since they are unique and not the same as the other three maps as ilustrated in your post. Since it's an overhaul to taxi, then keeping it's other z-levels is okay. What I originally though was that this was a paralel map that would push taxi away, not an overwrite.

On the map on itself, not a lot can be said without better pics. Toxins seems very forced, and sec doesn't look very secure. In some parts looks like you achieved "too much space". I doubt the free spacepods. I understand why **bus**station as opossed to _taxi_station, but by the name sounds like a single big shuttle to travel between stops.

**Comment by Kurfursten** [comment]
Toxins is just the toxins from Taxi. Not sure what you think should be done to improve it. I asked in the thread and someone said it was their favorite Toxins department so I left it at that. Could you elaborate?

Security is more secure than it looks. Sec maintenance (right) requires brig access, same as on Box, so you still have to go through 3 doors + 1 windoor to get into a cell (same as Box), smash one window from the lobby to get into a cell, (same as Box), 4 doors to get into the armory (same as Box), 2 doors to get into the security office (same as Box). What do you consider to be its weak points in design? Maybe I could shore up some of the places you find weaker.

**Comment by CptWad** [comment]
This is important
Does this map have the portal to the beach?

**Comment by ihadtoregisterforthis** [comment]
On the toxins, it looks like you were forced to connect the room to everything else through a stretched out hall. If you swap it with the shuttle you can rework the space, make access easier to miners (unless they have a dedicated shuttle that I didn't see) and even go as far as adding a bomb test area now that teleporting the bombs is more difficult.

Security can have it hard with the cells and HoS and Warden offices open to the main hallway. Even more with two of the three cells out of the line of sight of the warden.

**Comment by Kurfursten** [comment]
@CptWad I'll need to check but I think the end of the world portal is on the code end. Regardless I haven't touched the outpost much.

@ihadtoregisterforthis I think the HoS office is actually much more secure. because it is visible from the hall instead of tucked away (like on Box, it is the easiest jumpsuit to steal, compared to HoP office where anyone can see you inside of it). Note that the windows have closeable blast doors.

Can you elaborate more on the warden issues? Right now on Taxi the warden has visibility to 0 cells and this setup increases his security from 1 window/windoor vs a much more fortified setup (pictured below). But I understand where you're coming from: would it be more amenable to you if the door to the warden's office in the security hallway was removed, thus meaning he has to swing through the evidence/armory access to get into his office? Then it would be much harder to penetrate, increasing number of doors required to 4.

untitled

On the note of being able to see into cells from the warden's office: on Metaclub you can see into one, and in Box you can't see into any from your own office. Defficiency is the only station where you can see into a "cell" from the warden's office, but that's just into perma. You can't see into any from Taxi (vision range caps at 7 in any direction). I'm not opposed to a restructuring but this doesn't seem like a high priority to me to give Bus an edge for wardens over all other maps.

As for the toxins thing, I'm not really sure what you mean by a stretched out all, as it is access by one of the shortest halls (near the RD), but swapping it does seem like it would be better for miners. The only apprehension I have is that by having Toxins so far away, it would be the most isolated Toxins department on any map which means it is easy for someone to cook up bombs without getting noticed. Compare that to the current very high visibility from the rest of the science department on all maps except Deff. It would also still leave the hall with the same shape(?) so I don't think it would help with the hall design. Are you talking about the way the hall extends down by 2? I could move up the wall and shuffle around the items inside the room.

@PJB3005 Here's your (late) image of the TEG
teg on bus

As of the latest revision, a hot-cold merge valve was added like Box has.

---

To conclude, I think what Bus needs most is some real testing. Now, there are two main criticisms at this point that I think have a fair amount of merit worth redesigning for (correct me if there are more):
- Thin out the hallways from 5x5 to something like 3x3.
- Possibly switch the locations of the research shuttle and toxins

I'd like to get some more opinions on the toxins lab location (for the abovementioned reason) before changing it, but the hallways I will shrink down to 3-wide today. After that commit hits, **I'd like to get testing done with actual players**: having people on in different roles will help catch minor things like missing items, awkward access requirements, or things of that nature.

**Comment by ihadtoregisterforthis** [comment]
@Kurfursten 

In bright yellow, the line of sight from the extreme of the warden office, marked with an X. It only reaches a single cell. In meta you can see two at a time, and the third can be seen from the other end of the office. Box has the overlook that reaches all of them. Current taxi brig doesn't have a clear shot but the prisoners won't escape using a pair of shoes. Deff has a neat camera feed.

In darker yellow is the long hall that could be managed better, and doors marked for reference
buststation

---

Yes, this will need playtest, but don't go for the secondary test server ending with 7770. Noone ever goes there.

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis I see what you mean with the hallway, but what I was saying is that swapping the position of the two rooms won't actually fix the uneven shape. There might be another good shape to work with but I'll have to do some prototyping and see if people prefer that. I'll definitely look into it though.

Following your suggestion, I've added a camera to each cell. From the middle camera he can see all cells at once and the tile which the mounted flash is on has been replaced with another reinforced window instead of reinforced walls, so that the warden can now see every tile of each cell from the camera.

**Comment by Kurfursten** [comment]
I thought it wasn't fair that I wasn't giving updates on progress: I have finished changing the halls to 3-wide, which took more effort than I expected, but I am currently working on redesigning the brig and science department following ihad's suggestions. The brig is more or less done: while the warden's office and cells themselves are mostly unchanged, the newly redesigned security lobby is split up to make the lockers and hardsuits more secure, as well as provide officers to sit in view of all the cells (much like the front desk on Box).

**Comment by IratePirate** [comment]
How's this progressing?

**Comment by Kurfursten** [comment]
I think everything is good to go except science. I'm still working on a design to improve on the layout.

After this goes into testing (e.g.: next commit), if someone else is interested in developing the map further, they're welcome to given that grad school really eats up my time.

**Comment by 9600bauds** [comment]
>those xenobotany machines out in the open without a table to put disks and seeds on or paper to write down or even a seat
This is not riveting and does not quench my autism

**Comment by Kurfursten** [comment]
A table I can agree to, but do the machines really need to be in the back room? Sure, it's standard, but think about it: why? You can't actually see what's going on in this botany unless you have access to the service department hallway, because it has no desk. Moreover, you can't really examine what's in the machine from a distance, nor get a visible angle on it unless you have botanical access anyway.

And on a personal note, as someone who has played their fair share of botanist: I usually want the chem master in the front room by the grinder. Personal preference, perhaps, but I find myself using it there most often.

**Comment by 9600bauds** [comment]
I didn't even say they needed to be in the backroom

**Comment by Kurfursten** [comment]
You mentioned it was out in the open!

**Comment by Probe1** [comment]
How we doin here?

**Comment by ihadtoregisterforthis** [comment]
Most likely on hold

**Comment by 9600bauds** [comment]
Dead

**Comment by CptWad** [comment]
arise from the grave

**Comment by Kurfursten** [comment]
If people are still interested in Bus Station, I figured out how to rearrange the science department to look nicer. I will return and finish it to playable condition in 11 days if people want it.

**Comment by Kurfursten** [comment]
So I'm ready to get this into working condition, but I'm getting a fuckton of new errors so I'm guessing updating byond to 5.10 messed stuff up and my branch isn't compatible. Since I've only got three files, I think it might be easier to just start a fresh branch and port over these changes.

**Comment by clusterfack** [comment]
What kind of errors?

**Comment by Kurfursten** [comment]
Regex and garbage I didn't touch

**Comment by clusterfack** [comment]
Rebase onto bleeding edge then

**Comment by Kurfursten** [comment]
> 4 months of conflict resolution

Also who touched docking ports while I was gone? We don't even use those anymore? Or path changed?

**Comment by Kurfursten** [comment]
Holy shit, for the first time in possibly the entire history of git, it was actually less hassle to rebase

Now to be mad at @Probe1 for changing the path of docking ports. Oh well.

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis Okay, here's a rough draft of what I think would be a good rebuild of the science department. There's a showroom to kill deadspace. I'm pretty happy with the place this is right now, so I hope other people think it passes too so I can go ahead and pipe it.

untitled

**Comment by ComicIronic** [comment]
Why have you moved Research away from. Robotics? The point of a decentralised science department is that the jobs that worked together were moved together.

Dead space is also terribad.

**Comment by Kurfursten** [comment]
Did you like the previous version (in the original post) with the long hallway more?

You know, with all this space, I actually could move robotics over with the rest of science and just leave the recharge bay over there with the silicon stuff. I can't think of any super important reason robotics NEEDS to be right next to the AI core/charge bay. Would people like that more?

**Comment by ComicIronic** [comment]
It stops sillycons using the Taxis at roundstart to go over to Robotics for the cell upgrade and then go back. That's not a super-important reason, but there isn't a really big reason for the science department to be in one place either. Science is better thought of as a bunch of smaller groups that aren't big enough to be their own departments.

It should also be noted that you should reconsider your Mechanics placement if you plan to put everything in one place - they have to be not out of the way for Miners, which means putting them on the same station as either Mining or Research/Robotics (which is, in your case, the same station).

**Comment by Kurfursten** [comment]
That's true, but mechanics were with Cargo/Engineering on Taxi and I think they've got a good spot. If you're going to put mechanics next door to R&D, what's the point of mechanics in the first place? (And I know many people have wondered just that) Of course it wouldn't be an issue if stock parts used plastic, since they're on the station with botany. I won't fight that battle anymore.

**Comment by ComicIronic** [comment]
> what's the point of mechanics in the first place? 

Because research is a job that nobody wants to spend more than the necessary time in.
The fact that people still go to Research instead of Mechanics to actually get stuff made is largely a result of old habits and poor positioning.

**Comment by Kurfursten** [comment]
Progress report: Science is all mapped out. I'd like people to test it, and if people feel like robotics needs to be moved over to the rest of science as Comic suggests, I think we have the room for it no problem. I could even make something new in the new open space on medical/silicon station.

Since Vox traders are also a thing now and the old Taxi Voxstation wasn't very impressive (it was just a smaller, more oppressive version of the Box outpost without a trade shuttle), I mapped a new Vox outpost from scratch on Z-level 1. So it's as easy as nabbing a pod or suit from one of those EVAs and you can fly over to visit the fleabags. Here's a pretty picture. I hope you like how it came out, I think it looks cozy. The silver airlocks require Vox access, which is why Vox spawn outside on the trade floor so they won't be trapped if they choose no ID. _Not pictured: added mortar to manufacturing lab, added gas link to cycling airlock, added a connector in atmospherics for filling your pump_
vox outpost

Unless there are any last minute things someone wants to hit me with, I can make the commit and we can do some live testing.

**Comment by CptWad** [comment]
n o i c e
what are those spawners of?

**Comment by Kurfursten** [comment]
The three in the lobby are for Traders (they have to spawn outside the secure areas in case Vox choose not to take IDs).

The two in the pod bay are pod spawners so the traders can visit the other stations to trade if no one comes to them.

**Comment by CptWad** [comment]
no no the three squares that spawn items(top left), what are they of

**Comment by Kurfursten** [comment]
Maintenance loot spawners. They  can be anything from trash or syndie items. As seen on defficiency.

**Comment by CptWad** [comment]
hue alright

**Comment by Kurfursten** [comment]
Last call for comments before I push an update and ask for merge / public testing

**Comment by CptWad** [comment]
im ready

**Pull request closed without merging**
