### PR TITLE
Yay, another pointless feature that will never get used!

### PR DESCRIPTION
**Pull request by 9600bauds**
Lets you hang papers on smartfridges. Works exactly like tables. When the local mime or retard brings you a doodle, you can now proudly hang it on the fridge and pat them on the back.
Demonstration: http://puu.sh/hR4QJ/0ed3a27a84.webm

### CODE REVIEW

**Comment by PJB3005** [comment]
Aw, I expected them to look like the notice board

**Comment by dylanstrategie** [comment]
They honestly should, but I don't know if it would work in a practical manner

**Comment by 9600bauds** [comment]
I didn't even KNOW we had noticeboards, I've never seen them used before

**Comment by DrCelt** [comment]
Yeah, can you code this to be like the noticeboard? Make an overlay and maybe allow them to be stuck to any object.

**Comment by 9600bauds** [comment]
How would that work? Just attack any object with a paper and have it become stuck?
How do you retrieve the paper? Click the overlay?

**Comment by Probe1** [comment]
It opens up a UI that has a list of all things attached to it.

**Comment by ComicIronic** [comment]
I wouldn't code this to be like the noticeboard.
It would be incredibly difficult to get to work consistently in some situations, and it would only work to the same effect, whereas this looks better.

**Comment by Probe1** [comment]
yeah @9600bauds I think it's literally perfect how it is.  it's a cute secret/easteregg.

**Pull request merged**
