### PR TITLE
Why Mice Why

### PR DESCRIPTION
**Pull request by clusterfack**
Mice triggering station destroying endgames by respawning every minute.
Thanks mice.

### CODE REVIEW

**Comment by 9600bauds** [comment]
Why not just make mice give 0 points on singularity_act

**Comment by clusterfack** [comment]
I did

**Comment by 9600bauds** [comment]
Nevermind I'm stupid

**Comment by Kurfursten** [comment]
The oversight fix is a good one, but this should really at least have a discussion about pushing the respawn time for mice up from 1 minute to 5 minutes, especially due to the lack of changelog.

**Comment by clusterfack** [comment]
Putting up a changelog on something that is still up for discussion, as PRs are for, is a somewhat hasty gesture in my opinion.

**Comment by d3athrow** [comment]
changelogit

**Comment by clusterfack** [comment]
Done

**Pull request merged**
