### PR TITLE
Logging for posibrain attack_ghost

### LINKED ISSUE #20031: Registration List format bug with Posi Brain
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
d9cb1d08d578e7d63f29e8d681386e438000faf0

# Description
"Removed from registration list.

Click again to unvolunteer."

This should say to click again to volunteer, and is currently mildly misleading in its current form as reclicking will volunteer you like normal

# Steps to Reproduce

Be ghost, click activated posibrain to unvolunteer
# What you Expected

Removed from registration list.

Click again to volunteer.
# What Actually Happened
Removed from registration list.

Click again to unvolunteer.

### PR DESCRIPTION
**Pull request by Pathid**
Also fixes #20031

### CODE REVIEW

**Comment by Pathid** [comment]
Does this work now?
[administration] [grammar]
edit: guess not

**Comment by Exxion** [comment]
Has to be in the OP

**Comment by Pathid** [comment]
I think I'll remove the sign-up logging part. Or rather I'd like to make signing up from the chat prompt to be logged too for consistency.

**Comment by DamianX** [comment]
Yes, logging both would be a good idea.

**Comment by Intigracy** [comment]
consistency please

**Comment by Intigracy** [comment]
when

**Pull request merged**
