### PR TITLE
Meteorlogical vault

### PR DESCRIPTION
**Pull request by Probe1**
## Ready for Review/Merge

Contains:
- 3  mid grade weapons
- 1 hardsuit set
- ore
- misc food/drinks
- toolboxes 
- paper hat

dreamseeker_2016-12-18_11-49-35

🆑 

 * rscadd: A new Meteor-logical Vault to quietly study meteors.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by NigglyWiggly** [comment]
I still can't tell if this is a play on words or if you meant meteorological, which would make even less sense in this context.

**Comment by Probe1** [comment]
It's a play on words.

**Comment by Gunosaguki** [comment]
always up for more vaults.

**Comment by Probe1** [comment]
@PJB3005 was gonna merge it but there were conflicts, which he fixed.  Self merge slippery slope downfall of /vg/ etc.

**Comment by PJB3005** [comment]
Correct.

I was waiting on Travis just in case and forgot about it.

**Comment by Kurfursten** [comment]
It was pretty meta to get this in without saying what the vault really is

Still a nice place though

**Comment by Probe1** [comment]
Surely you can figure out why I did not.  It was discussed privately with coders first.

**Comment by Exxion** [comment]
What are you two talking about?

**Pull request merged**
