### PR TITLE
Based on a recent finding, reverts diona hyperzine allergy to only toxloss

### PR DESCRIPTION
**Pull request by Pathid**
I didn't think it was fair to make #17820 without this as a companion PR. See that one for details.

See also since it's very much related: https://github.com/vgstation-coders/vgstation13/pull/17645#issuecomment-371760150

**TL;DR,** #14721 was done, at least in part, to balance against the impact of two bugs that are now being fixed by #17820 and #17822. This isn't intended to be merged before those two are merged.

:cl:
* tweak: Adjusted diona hyperzine allergy to affect just toxloss. Cocaine also now has the same effect as hyperzine.

### CODE REVIEW

**Comment by Sooose** [comment]
Considering it is trivial to grab a flashlight out of an o2 locker and pocket it for the rest of the round I'd say no. I don't see the point in removing the allergy they can avoid by just taking small doses of hyperzine frequently. Not to mention the ridiculous amount of pros they already have.

That said, if #17822 passes I'm indifferent.

**Comment by Blithering** [comment]
I think the allergy was to prevent them from being able to intentionally massively overdose themselves and ignore one of their racial differences all shift, I'm not sure regen accidentally functioning in darkness was even known at the time

**Comment by Pathid** [comment]
@Blithering 
The thing is it's not just about regen accidentally functioning in darkness. It's also about the regen in light being massively higher than it was supposed to be.

Have an illustration for what the difference is.
line

Plus, if #17822 passes, hyperzine won't give them human level speed anymore.

**Comment by Blithering** [comment]
Have you tested that diona with the fixed regen amounts can't outheal an overdose when in the light?

**Comment by Pathid** [comment]
@Blithering Was just doing that. Turns out they still just outpace it if they're in full illumination. Let me change this.

**Comment by Pathid** [comment]
Wonder whether I should add cocaine in there too, while I'm at it. Or maybe that's still a feaaaatuuuuureeee.

**Comment by Blithering** [comment]
Cocaine was an oversight, lots of botany chems didn't get tagged the same as their equivalents.

**Comment by Pathid** [comment]
Full disclosure: Turns out I misread what #17822 did and it _doesn't_ actually affect hyperzine's interaction with racial speed modifiers. 

Got kind of a dilemma here: I don't want dionaea to come out completely sucking from #17820, however it's apparent we don't want the basis of them _not_ sucking to revolve completely around hyperzine and/or cocaine.

**Comment by Pathid** [comment]
I'm thinking of closing this unless somebody clamors for me not to. The regen's still nothing to sneeze at.

**Comment by jknpj** [comment]
RIP

**Pull request closed without merging**
