### PR TITLE
Add Malf splash/title

### PR DESCRIPTION
**Pull request by Efruit**
ai

:cl:
 * imageadd: Added the Malf splash screen

### CODE REVIEW

**Comment by Probe1** [comment]
Try to work on the size.  It's twice as big as the largest splash screen.

**Comment by Efruit** [comment]
ai-raw

A compressed version, saving 3.1MB

**Comment by Efruit** [comment]
ai-splash-2

A slightly reworked version, saving 3.9MB

**Comment by Exxion** [comment]
Honestly I kind of like that one the best anyway, regardless of size

**Pull request merged**
