### PR TITLE
Self-recharging batteries now recharge 10x faster

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Alright, so the problem is that literally nobody who is a non-antag uses the self-recharging batteries because they irradiate everyone nearby, and you can't even place them inside borgs because that'd make the borgs harmful to the crew. The worst part is that it also recharged far too slowly, where it would take about 100 ticks, or about 200 seconds for the extremely small batteries (literally worse than almost every battery present roundstart on the station) to fully recharge by themselves. Now here's an incentive, **the recharge rate has been multiplied by 10,** so that means it would take 20 seconds for it to recharge. Doesn't suck so much anymore, right? It still irradiates you but at least you have a pretty reliable self-charging low-capacity battery.
They are still slower than just placing a battery on a battery recharger, even more so if it is upgraded.
:cl:
 * tweak: Self-recharging batteries (the RTG and phazon RTG) now generate 10x as much power.

### CODE REVIEW

**Comment by DrSnips** [comment]
In theory they can support silions outside of humans. So basically only dere mommis. I tried to think of other places you can use them like stun batons but then you run into the issue of coming down with cancer.

**Comment by boy2mantwicethefam** [comment]
I could try removing the radiation as an alternative and instead make the recharge more modest (3x-5x)

**Comment by MadmanMartian** [comment]
look at https://github.com/vgstation-coders/vgstation13/pull/22588/files

**Comment by DrSnips** [comment]
I really like them as a concept but the practice is unfortunate truth.

**Comment by dunsel-hordon** [comment]
if you put it in a mech does it still irradiate people? I don't think so but not sure on that

**Pull request merged**
