### PR TITLE
Prevents nuke disk carriers from trying to ride a gravpult

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* bugfix: Marauder or Seraph pilots carrying the Nuke Disk can no longer try to ride the Deathsquad Gravpults, which would cause them to bounce off the Mech Teleporters and become stranded. (SoyConsumer)

### CODE REVIEW

**Comment by SonixApache** [comment]
i feel like this is the bad way of fixing this behavior

**Comment by DeityLink** [comment]
It's one that is consistent with gameplay mechanics surrounding the Disk. Also the commander delegating the disk to another operative isn't necessarily a bad idea.

**Comment by SonixApache** [comment]
forcing one guy to be the disk bitch while everyone else gets to ride cool mechs is gay
i assume making an exception for the gravpult / centcomm would be too complicated?

**Comment by DeityLink** [comment]
You can ride the cool mech on the shuttle.

**Comment by SonixApache** [comment]
😔

**Pull request merged**
