### PR TITLE
Fixes roundstart players appearing naked on their medical and security records

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* bugfix: Fixes roundstart players appearing naked on their medical and security records

### CODE REVIEW

**Comment by jwhitak** [comment]
I thought the nudity was intended. It gave a dystopian scifi vibe...

**Comment by DeityLink** [comment]
it's a bug that appeared somewhere in the last 1-2 years yet. And didn't affect latejoin players anyway.

Personally I like Nanotrasen being not all black or white, but this here would be downright dark to me.

**Comment by Eneocho** [comment]
I like it cause it implies _extensive_ checking by NT to make sure the crew is not mutant/alien/cultists/whatever, but are incompetent so they still let vampires, lings, cultists, blob infected crew, etc in.

**Comment by DeityLink** [comment]
that's your headcanon

**Comment by SonixApache** [comment]
shame, it made sense for the medical records

**Comment by sushi-vomit** [comment]
Always thought it was intentional, it will be missed

**Comment by PrimeDSS13** [comment]
leave it for medical records but not for sec records >:)

**Comment by DeityLink** [comment]
wyci

**Pull request merged**
