### PR TITLE
Construction Permits episode 6

### PR DESCRIPTION
**Pull request by jakmak6**
What this change does is it adds in new mini blueprints called construction permits. 

What these are are basically MOMMI prints accessible to all engineers/atmostechs/autists in the engi vend. They can create new rooms for use of APC's and air alarms and rename those rooms but CANNOT rename roundstart rooms (so engineers cant go around and rename every hallway to benis). 

These permits DO NOT count towards the antag steal blueprints objective.(tested)

This would make it easier and encourage autism forts because previously you either had to be a MOMMI or steal the CE blueprints (or worse be the CE).

proof it works https://puu.sh/wCeKb/491c439848.webm

:cl: *rscadd: Added Construction permits to the engi-vend

### CODE REVIEW

**Comment by jakmak6** [comment]
i dont know why items.dmi is conflicting. I downloaded the file off the repo and added my change several times and it still errors out

**Comment by SonixApache** [comment]
use inline conflict solver
delete [their] block
check it before you hit RESOLVED

**Comment by DamianX** [comment]
>browse()

**Comment by SonixApache** [comment]
oh wait, it's a .dmi

good luck lmao
is items.dmi not one of the untouchable .dmis?

**Comment by jakmak6** [comment]
i have no idea what is causing it to chimp out like this

**Comment by SonixApache** [comment]
back up permit icon
use bleeding-edge .dmi
commit & push
see if there's no conflicts
import permit icon IN A DIFFERENT SPOT
commit & push

**Comment by SonixApache** [comment]
almost

**Comment by SonixApache** [comment]
*memes*
also your changelog in the OP is formatted wrong

**Comment by gbasood** [comment]
okay since I know you'll freak out about that conflict and make a whole new repo, don't
instead:
 - Make sure you have the changes you made to items.dmi saved somewhere outside of that file, so you can re-add them.
 - Update your Bleeding-Edge *that lives on your hard drive*
 - `git checkout Bleeding-Edge icons/obj/items.dmi` so you have the version with the changes made since you made your branch.
 - Not sure if you need this step but with your branch for this PR checked out, `git rebase Bleeding-Edge`
 - Add the changes you had in items.dmi back in.
 - Stage and commit.

bam no more conflict

**Comment by jakmak6** [comment]
First, rewinding head to replay your work on top of it...
Applying: DOITAGAIN
warning: Cannot merge binary files: icons/obj/items.dmi (HEAD vs. DOITAGAIN)
Using index info to reconstruct a base tree...
M       code/game/gamemodes/steal_items.dm
M       code/game/machinery/vending.dm
M       icons/obj/items.dmi
M       vgstation13.dme
Falling back to patching base and 3-way merge...
Auto-merging vgstation13.dme
Auto-merging icons/obj/items.dmi
CONFLICT (content): Merge conflict in icons/obj/items.dmi
Auto-merging code/game/machinery/vending.dm
Auto-merging code/game/gamemodes/steal_items.dm
Patch failed at 0001 DOITAGAIN
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

error: Failed to merge in the changes.

Jakmak@Jakmak-PC MINGW64 /vgstation13 (permitspart4|REBASE 1/8)
$ git status
rebase in progress; onto c8ab2aa224
You are currently rebasing branch 'permitspart4' on 'c8ab2aa224'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   code/game/gamemodes/steal_items.dm
        modified:   code/game/machinery/vending.dm
        new file:   code/game/objects/items/constructionpermit.dm
        modified:   vgstation13.dme

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   icons/obj/items.dmi


Jakmak@Jakmak-PC MINGW64 /vgstation13 (permitspart4|REBASE 1/8)
$ git add icons/obj/items.dmi

Jakmak@Jakmak-PC MINGW64 /vgstation13 (permitspart4|REBASE 1/8)
$ git commit -m kodmon
[detached HEAD 68f07d2332] kodmon
 5 files changed, 52 insertions(+)
 create mode 100644 code/game/objects/items/constructionpermit.dm

Jakmak@Jakmak-PC MINGW64 /vgstation13 (permitspart4|REBASE 1/8)
$ git push origin permitspart4
Username for 'https://github.com': jakmak6
Everything up-to-date

Jakmak@Jakmak-PC MINGW64 /vgstation13 (permitspart4|REBASE 1/8)
$ git status
rebase in progress; onto c8ab2aa224
You are currently rebasing branch 'permitspart4' on 'c8ab2aa224'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit, working tree clean



i have very very seriously pissed off git

**Comment by Arthurdentist** [comment]
>Its a Jakmak episode

**Comment by gbasood** [comment]
how did you end up with the same conflict

**Comment by jakmak6** [comment]
i dont know

**Comment by gbasood** [comment]
okay
as long as you have the changes you made to items.dmi somewhere else:
`git rebase Bleeding-Edge` (should stop on conflicts)
when it DOES stop on conflicts:
`git checkout Bleeding-Edge icons/obj/items.dmi`
`git add icons/obj/items.dmi`
`git rebase --continue`
that works *I think*
after that add the changes back to the dmi and commit and push

**Comment by SonixApache** [comment]
make a new PR that adds a different icon to items.dmi and then see if this one works again

**Comment by jakmak6** [comment]
remake here https://github.com/vgstation-coders/vgstation13/pull/15350

**Pull request closed without merging**
