### PR TITLE
Twinkling Tile Particles

### PR DESCRIPTION
**Pull request by RealestEstate**
Adds a twinkling particle effect to Silver, Gold, and Diamond based turfs+constructions:
This includes:
*Floors (while unbroken)
*Walls
*Doors (while closed)
*False Walls (while closed)

Not ready for merge yet, I wanna test out different particle looks before I settle on one.
[sprites]
[wip]

how it currently looks:

[bling3.webm](https://github.com/vgstation-coders/vgstation13/assets/25192877/c69e2549-9220-4527-9003-04ec4aff5ff3)

## Changelog

:cl:
 * imageadd: gold,silver, and diamond turfs and structures now twinkle.

### CODE REVIEW

**Comment by Eneocho** [comment]
i'd say it's twinkling too much, maybe 50% slower twinkle? For comparison, look at a lucky coin.

**Comment by angryturnip** [comment]
Make it so they don't twinkle anymore if there's no light

**Comment by RealestEstate** [comment]
that's hard!
I have no idea where to even begin with light code.

**Comment by GreatBigFailure** [comment]
They look nice but I'd like the option to have them not twinkle if needed. 
Maybe have it so you "polish" the tile when you use a rag on it, and that starts the twinkling? Or similar.

**Comment by west3436** [comment]
@RealestEstate is this dead or will you be returning to it soon?

**Comment by RealestEstate** [comment]
dead for now

**Comment by Eneocho** [comment]
it's so over bros

**Pull request closed without merging**
