### PR TITLE
Fixed wrenching computer frames

### PR DESCRIPTION
**Pull request by DamianX**
Due to FUCKING wrenchAnchor.

### CODE REVIEW

**Comment by PJB3005** [comment]
👏

**Comment by Shadowmech88** [comment]
These issues exist because wrenchAnchor has unintuitive return values, right?
Is there a reason we don't just change those instead of changing everything that uses wrenchAnchor to work with them?

**Comment by DamianX** [comment]
Yes, I'll be doing that in my next PR.

**Comment by N3X15** [comment]
Which of these do I merge first? Will they conflict?

**Comment by DamianX** [comment]
they will, the other refactoring will also take care of the issue, but if you want to merge this one first I can fix the conflicts, no problems there.

**Pull request closed without merging**
