### PR TITLE
allow resisting out of straight jackets (but you can break your arms doing it and broken arms let you do it faster)

### PR DESCRIPTION
**Pull request by DamianX**
#31189: deluxe edition

:cl:
 * tweak: It is now possible to "resist" out of straight jackets. It takes two minutes. It may break your arms. Each broken arm shaves 30 seconds off the time needed to escape.

### CODE REVIEW

**Comment by ValkyrieSkies** [comment]
Seems a bit short given that handcuffs are also 2 minutes and a straightjacket is supposed to be a bit more all encompassing.

**Comment by DamianX** [comment]
I have made it my personal mission to not force people to sit still for extended periods of time despite what the github intelligentsia says. Historians will look at this and describe it with words such as prescient, far-sighted and visionary

**Comment by Eneocho** [comment]
>I have made it my personal mission to not force people to sit still for extended periods of time

Impossibly based and criminally underappreciated.

**Comment by SonixApache** [comment]
if only you didn't go for the two minutes
you almost had it

**Comment by WindowsErrors** [comment]
did damian get straitjacketed and abandoned in the pbrig by security again today

**Comment by BomberBro** [comment]
Reminder if your initial PR fails, make a slightly different, funnier one with mostly the same effect and it'll pass as "The Great Compromise"

**Comment by Eneocho** [comment]
If anything, robotic arms should help better since they have mechanical muscles and something something stronger arms.
`>b-BUT THE POWERGAYYMERS`
You don't get straight jacketing THAT often, not like cuffing, which happens more than once every round. And robotic limbs are fucking awful in their own right. EMPs fuck you up, you need tools to fix them, etc.

**Comment by WindowsErrors** [comment]
ok, but in all seriousness, there are certain analogues to be made here with other servers

when I started playing in 2019 on beestation, I eventually found myself playing security (I don't as much anymore) and it being one of the largest hub servers in 2019, naturally there was a lot of idiots to encounter

all the other seccies told me pretty quickly that you could resist out of the jacket the same way as cuffs, but the two of them stacked together, so we found ourselves just doubling up on them all the time, using the jacket as cuffs+ to the point that if we left a prisoner alone in the brig medbay or the pbrig or whatever jacketed for more than a couple minutes because there was some other stupidity going on somewhere else in the brig, with full and honest intentions of coming back later, even me leaving them a radio headset so they could talk, I would more often than not return to find them out of the jacket autistically smashing windows and vandalizing the brig like the chimps that they are

because of that, here, I understand the severity and the importance of the jacket and why there are a limited number, and why more of them can't be produced, I think of it more like restraining bolts but instead of cyborgs its for people, you don't just bolt down the borgs without a good reason

I also understand that security is played by some pretty smoothbrained palookas who do not share the same enlightened ideals as me, just last night I watched two seccies gas themselves with the CO2 can in the execution room in an attempt to execute the traitor mime, who lived because they had left the air scrubbers on to filter out the gas, and then had to be helped out of the straitjacket by the wonderful squidmoko

take these opposing viewpoints as you will

**Comment by Kurfursten** [comment]
Given the high degree of interest in this PR, I would like to give it a full week for opinions to come in

**Comment by WindowsErrors** [comment]
also I don't think this is going to contribute or change anything at all but I just wanted to add that it's spelt straitjacket in one word like the Strait of Gibraltar, not straight jacket in two words like the Straight of Gibraltar

whoever created this item first (probably the Goons back in like, 2010 or something) obviously didn't have the refined and modern understanding of the English language that us enlightened beings do today

**Comment by Blithering** [comment]
Personally I'd give it 3 minutes, -30 sec per broken arm and -1min per dismembered arm, so if you're really dedicated you can pop off both your robolimbs and be free in 1 min flat, for all the good it would do now you're an armless wonder.

**Pull request merged**
