### PR TITLE
Fixes traitor emagged robots not being selfdestructproof

### LINKED ISSUE #23297: You can blow up emagged borgs, even though you should not
#### Description of issue

The code for blowing up an emagged borg is :

```dm
/mob/living/silicon/robot/proc/self_destruct()
	if(mind && mind.special_role && emagged)
		to_chat(src, "<span class='danger'>Termination signal detected. Scrambling security and identification codes.</span>")
		UnlinkSelf()
		return FALSE
	gib()
	return TRUE
```

However, `mind.special_role` isn't used anywhere after role datums.
So, this protection emagged/traitor borgs used to get from being blown up no longer exists.

### PR DESCRIPTION
**Pull request by jknpj**
Fixes #23297

:cl:
 * bugfix: Fixes traitor emagged robots not being selfdestructproof

### CODE REVIEW

**Comment by Killette2** [comment]
Can you still blow them up with the 60 second countdown that blows all borgs?

**Comment by Kurfursten** [comment]
It doesn't look like it, based on the code. It seems to just desync the borg when self_destruct is called

**Comment by Killette2** [comment]
What's that feature for then? RP?

**Comment by Kurfursten** [comment]
If they weren't listed at all you could just check at roundstart to see which borgs aren't listed on the computer.

**Pull request merged**
