### PR TITLE
R&D console menu overhaul

### PR DESCRIPTION
**Pull request by ghost**
[UI][tweak][qol]
image
:cl:
 * tweak: The R&D console now has a new menu UI that should be much easier to navigate.
 * tweak: Settings and device linkage of R&D console are now on the same page.
 * tweak: The materials and queue sections of protolathe and circuit imprinter menus of R&D consoles are now on the same page.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Looks nice. Maybe a search function like the syndicate PDA uplink could be convenient.

**Comment by ghost** [comment]
> Looks nice. Maybe a search function like the syndicate PDA uplink could be convenient.

I wrote this in nanoUI which I'm not sure supports it. Maybe I'll add one when converting it to TGUI if I ever decide to.

**Comment by Dacendeth** [comment]
I just ctrl f whatever I want and this doesnt look like I can do that anymore so I dont like it.

**Comment by Pancakemines** [comment]
I gotta agree with Dacendeth maybe if everything were ordered alphabetically in each catagory I could get my dumb monkey brain used to it but as it is now I can't imagine this ever making printing all the things I want easier especially if it follows the same rules as before so things are displayed in the order you research them because there's just no consistency for me to learn over multiple rounds.

**Comment by Eneocho** [comment]
Not sure I like it. The shitty current UI doesn't blank (thanks byond!) half the time like this kind of UI does.

**Comment by pedr69** [comment]
i don't know if it's from being localhosted or what but the UI responds way faster than i'm used to
protolathe tab is fine, since you can only see 1 category at a time you don't need to ctrlF your shit anymore
the circuit printer categories are a bit fucked, engi RUST and medbay sleepers are in misc instead of their proper sections, but that's been like that before this PR

only real issue i see is how it's no longer ID locked, you used to need an ID to sync devices and tech levels
maybe ask for a valid ID to press the topmost buttons, which still lets greyshits print some stuff if you leave it on the protolathe screen

**Comment by pedr69** [comment]
oh yeah, the queue
there's no x5 button, so making multiple of something sucks ass
there's no queue custom button so good fuckin luck printing 50 pico manipulators for an upgrade run
the screen also doesn't update after you "process queue", the parts get printed but stay in the queue unless you click on the computer again or try to process queue again, at which point they vanish
also miss the total materials required for the parts in the queue

also i can't close the window while standing next to the console, it reopens automatically forever!

**Comment by tuypo1** [comment]
I would still want control f or a search, even if it is broken up into categories easier now

**Comment by pedr69** [comment]
you still can ctrlF?

**Comment by west3436** [comment]
I like the idea but it desperately needs a custom/multi-queue feature. Also TGUI would be much better than n*noui

**Comment by ghost** [comment]
> also i can't close the window while standing next to the console, it reopens automatically forever!

Fixed that

**Comment by ghost** [comment]
> I like the idea but it desperately needs a custom/multi-queue feature. Also TGUI would be much better than n*noui

Added that back in. Also will convert to TGUI at some point, but for now sunk cost and all.

**Comment by pedr69** [comment]
apart from the queue missing a material total and the scrollbar breaking once you have more than 6 parts queued it seems okay

**Comment by xeroxemnas** [comment]
Without a search feature or ctrl + f this is objectively a downgrade in usability from the original

**Comment by ghost** [comment]
> Without a search feature or ctrl + f this is objectively a downgrade in usability from the original

Will probably try saving throw this with some better categorisation or sorting in a future PR

**Comment by Kurfursten** [comment]
Does Nanoui support a typable box? A filter option would address these complaints.

**Comment by ghost** [comment]
> Does Nanoui support a typable box? A filter option would address these complaints.

~~Never seen a nanoUI one in practice, no~~ Actually I could use an input text box to filter things like in the view vars menu, see how that works.

**Comment by zakanater19** [comment]
soulless

**Comment by Kammerjunk** [comment]
wh
what
why

why would you put MORE NanoUI into the world
this is cruel

**Comment by ghost** [comment]
Will probably redo as TGUI, current search attempt is not working for me with normal JS, may reopen if I make a PR making categories less painful so search isn't as necessary.

**Pull request closed without merging**
