### PR TITLE
Posibrain boot sound

### PR DESCRIPTION
**Pull request by SonixApache**
Now there's actually an audible sound.
https://puu.sh/u9yQ6/b760628223.mp3
~~now there's actually an audible chime
https://puu.sh/u9t29/45a7403028.ogg
sound stolen from bay~~
100% tested

:cl:
 - soundadd: Positronic brains now make a sound after booting up.

### CODE REVIEW

**Comment by clusterfack** [comment]
Whoa there cowboy, text descriptions of sounds not good enough for ya? Check your hearing privilege.

**Comment by SonixApache** [comment]
when you tab back into ss13 while observing and you find out you got selected as posibrain 30 minutes ago

**Comment by SonixApache** [comment]
if you have any better ideas for a sound let me know, so far i only have 'buzzbeep' https://puu.sh/u9yQ6/b760628223.mp3

**Comment by Ephx1** [comment]
That second one is better.
Isn't the first one their announcement sound? Odd you took that one.

**Comment by SonixApache** [comment]
We don't have it in our codebase, and it sounds like a quiet chime, so I felt it fits. Lean more towards the second one myself, but it's lacking something.

**Comment by Shadowmech88** [comment]
What about using the BYOND Feed update sound?

**Comment by SonixApache** [comment]
Don't want to use sounds we're already using, if possible.
Another alternate: 'boobeebeep'. https://puu.sh/u9yy9/89afaf9f23.mp3

**Review by PJB3005 — APPROVED** [review]

**Comment by kol1th** [comment]
Second one tbh.

**Comment by SkowronX** [comment]
http://www.hrwiki.org/w/images/6/69/Win95_ding.ogg
http://www.hrwiki.org/w/images/2/21/Compy386startup.ogg

**Comment by SonixApache** [comment]
Decided to go with buzzbeep. Changed the text to go along with it.

**Comment by SonixApache** [comment]
I would like to say that the two sound files I posted in this are from a really old british 3D RTS game called `Machines: Wired for War`.

**Comment by jknpj** [comment]
Autism

**Pull request merged**
