### PR TITLE
What could possibly go wrong???

### PR DESCRIPTION
**Pull request by Exxion**
0% tested. Merge at your own risk.

In all seriousness, the list of things that could possibly go wrong is fairly short but certainly not empty
I'll make sure it doesn't break anything tomorrow (probably)

### CODE REVIEW

**Comment by Kurfursten** [comment]
I am pretty sure we did this before with the exact same "what could go wrong" meme and shit started to break because we actually do use infinity for some things that require calculations. Purely for example here if you insert an infinite power cell into an APC it crashes because it has to divide by infinity to determine percent charge.

**Comment by Exxion** [comment]
1. Infinite power cells don't use this define
2. We never did have this define set like this on live. Sonix had it for one commit in a PR but reverted it before it got merged just in case
3. Dividing by infinity works just fine. The reason APCs broke when infinite power cells had infinite capacity is because the browser fails to display the number, not because the math breaks

**Comment by Kurfursten** [comment]
🤷‍♂️ I must have been recalling this https://github.com/vgstation-coders/vgstation13/pull/14621#issuecomment-293041431

**Comment by DamianX** [comment]
remember #15457
is there a reason to do this?

**Comment by Exxion** [comment]
1. Yes, I remember that. Again, infinite cells don't use this macro. Again, that was a problem specifically with showing it in a browser.
2. Mathematical correctness and an asston of possible (albeit unlikely) edge case bugs

**Comment by DamianX** [comment]
fine by me

**Comment by ghost** [comment]
amazing related story, it's seems they (Microsoft) named positive infinity `1.#INF` because it would otherwise fuck up Visual C runtime library's rounding algorithm. And there is funny corner case related to that. 
https://blogs.msdn.microsoft.com/oldnewthing/20130228-01/?p=5103

**Pull request merged**
