### PR TITLE
Revert "Freeform objectives, fifth time's the charm"

### PR DESCRIPTION
**Pull request by jknpj**
Reverts vgstation-coders/vgstation13#20494 one week from now.

:cl:
 * tweak: Replaces the marginally more immulsive freeform objectives with solo antag objectives.

### CODE REVIEW

**Comment by ghost** [comment]
I think this is a massive terrible change and I'm completely shocked anyone would think this has the ability to fix anything wrong with the server.
If someone could link me to where all the discussion about this change has taken place I'd like to read and see what kind of reasons people have for wanting this because I simply cannot wrap my head around what positive arguments someone could make for completely removing objectives.

**Comment by SonixApache** [comment]
@morenaaa 
search for "freeform objective" or any variation of "just b urself"

**Comment by ghost** [comment]
> 
> 
> @morenaaa
> search for "freeform objective" or any variation of "just b urself"

This took me nowhere but this and the PR which this reverts which has no discussion

**Comment by Pathid** [comment]
@morenaaa 
Allow me:
#19485
#19487
#19501

**Comment by SonixApache** [comment]
also #19489

**Comment by Pathid** [comment]
Yeah that's the big one, was about to add it.

**Comment by SGuivenne** [comment]
are these just a meme at this point or is there an actual serious effort here?

**Comment by Pathid** [comment]
@SGuivenne They're these verbatim: https://github.com/vgstation-coders/vgstation13/pull/19501#issuecomment-417187361

**Comment by ghost** [comment]
Starting to do some reading and once again my main man I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE talking the most sense and approaching things the most logically. Almost all his ideas are the ones I was going to suggest.
But you've completely ignored them, despite it having the most thumbs up in the discussion thread.
Nobody really ever made any concrete arguments as to **why** _all_ solo antag objectives should be removed, and actual suggestions to fix the actual issues with solo objectives were seemingly just passed over?

I'll say this quickly here but removing objectives hinders far more than it does help.
Anecdotal evidence doesn't count as anything real, but I personally use objectives to give myself kickstarter ideas on what to do. Without them I usually have zero ideas on what I could do, and 90% of the time that ends up with you killing people and people getting upset you just "murderboned." It happened when I came back from a leave, double-traitor round in Robotics, I was going to build a mech, mess up the Chapel where the Chaplain was doing things as he was my target, but suddenly he came up to me and said he's going braindead so just kill him. Well now the hour I've just spent starting things with him, talking to people to spread rumours and shittalk has gone to waste. I've got my mech ready to shoot stuff, so I did just that. And people complained, they whined in the thread I'm the most boring person ever because all I do is murderbone.
And that sentiment that murderbone is incredibly boring is carried by a large percentage of our playerbase. It's always looked down on. But you tell people to do whatever they want, no prompts, no ideas, nothing, and I bet my left foot that you'll see a rise of players who just murderbone. Some of us aren't very creative, and the common phenomenon of the "antag shakes" which is experienced by all ranges of players will definitely lead to people bricking all sorts of gimmicks and just going for the murderbone.
But from here I'm going to say that there's a mentality some people hold that this isn't a roleplaying game, and that they play to win. So what is winning? It's rolling antag, getting your greentext and then being satisfied with yourself that you were rewarded with that big green endscreen. On the flipside, it's playing normal crew and walking around looking for someone to valid and kill, to deny them their potential greentext. This is something I see almost every time I play, and it's the one thing we haven't even addressed with the change. Not only yesterday did we have someone complain that with the new change, that they got the shuttle called but still got redtext. And I'm sure everyone here can remember rounds where people frequently recalled the shuttle because they hadn't yet got their objective. 
This isn't something we can hard change, it's greatly player-to-player and probably a in-grained part of their self. But we can influence it by turning objectives from a command and into a suggestion. We can change green/red text into something neutral, more of an acknowledgment more than reinforcements.
Lost my train of thought over intensifying hungry but I can add anything else later but please, this change is very bad, not properly thought out and will not fix anything in the long run.

**Pull request merged**
