### PR TITLE
Update Alien Nest Mining Surprise

### PR DESCRIPTION
**Pull request by gurfan**
The alien nest mining surprise usually contains only a cluster of eggs in the asteroid. This PR swaps out the old alien nest mining surprise for this:
aliens2
It is difficult to see underneath the weeds in the screenshot, but the structure contains a gygax wreckage, some alien hides, alien eggs, and a couple facehuggers.

:cl:
 * rscadd: The alien nest mining surprise has a new look.

### CODE REVIEW

**Comment by Durgen** [comment]
so the eggs were removed?

**Comment by gurfan** [comment]
no they're still there, the weeds are just shown on top of them in the map editor

**Comment by gurfan** [comment]
aliens2

this is what it should look like in game

**Comment by Durgen** [comment]
looks cool

**Comment by Kurfursten** [comment]
For vaults like this I wish we had some variable turfs that randomly become a plating, plating+girder, wall, or reinforced wall, same for plating/damaged plating/tile/damaged tile.

**Comment by SonixApache** [comment]
>not a ripley wreck

😕

**Comment by gurfan** [comment]
good point, I'll change that

**Comment by Kurfursten** [comment]
Waiting on that change

**Pull request merged**
