### PR TITLE
Reduces Diona burn modifier from 2.5 to 2

### PR DESCRIPTION
**Pull request by Kharkov72**
A captain's laser does 100 damage to you, so the lightest tap will throw you into crit, and 2 shots are an instant husk
I think that's a bit much
[balance]

:cl:
 * rscadd: Diona Burn Damage modifier from 2.5 to 2.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Pretty cringe tbh

**Comment by MadmanMartian** [comment]
Remember to fix it for nymphs as well. They don't draw their multiplier from the species datum, but from a hardcode.

**Comment by Kharkov72** [comment]
I think nymphs are fine with the higher burnmod, them being smaller frailer diona after all.

**Comment by tuypo1** [comment]
Fuck giving people more reason to play special snowflake races

**Comment by DamianX** [comment]
the obvious solution is to nerf the captain's laser

**Comment by DrSnips** [comment]
>diona need to be even bulkier

No thanks

**Comment by Kharkov72** [comment]
>37.5 damage welders
>75 damage from eguns and lasers
>instant crit with a captains laser

>"They need to be even bulkier"

absolute brainlet

**Comment by Exxion** [comment]
For the record this doesn't change the number of shots it takes to crit them with a normal laser

**Comment by DrSnips** [comment]
How dare a race have a strong drawback that doesn't need air, absorbs rads, has no blood to lose, and has good health regen from a flashlight.

**Comment by Exxion** [comment]
Doesn't need air (but still gets hypothermia in space)
Absorbs rads (but still gets mutations from them)
The other two actually are good though

**Comment by Kharkov72** [comment]
oh I wasn't aware that making them a bit harder to instagib was completely removing their weakness

**Comment by Kharkov72** [comment]
It doesn't change most threshholds for the normal egun lasers, but it does change threshholds for things like welders and the captain's laser, taking 4 hits to kill with a welder instead of 3 and 2 shots to crit / 3 to husk from 1/2 for the laser.
It doesn't have to solve every problem because it's _still their weakness_ but some of the threshholds should be a bit less ridiculous

**Comment by Coxswain-Navigator** [comment]
Buff mushbois to compensate.

**Comment by Kharkov72** [comment]
mushmen are literally already better than diona in terms of the reverse stats, I believe it was by .7 along with not having the hyperzine thing
UPDATE: their numbers are:
tox_mod = 0.8
brute_mod = 1.8
burn_mod = 0.6

**Comment by SonixApache** [comment]
dumb powergaming race buff

**Comment by Blithering** [comment]
@Exxion While they still get hypothermia in space, the main upside to their not needing air and space resistance means they can wear stronger armour in breached areas, where other people will have to downgrade their protection in favour of a hardsuit.

**Comment by strawberrytan** [comment]
can diona even break bones?

**Comment by Kharkov72** [comment]
like, have their bones broken? yes

**Comment by strawberrytan** [comment]
i can't remember ever having to fix diona bones so the question is more "do they have bones to break"

**Comment by Blithering** [comment]
They have bones to break, yes. but their regen makes it not matter in about 30 seconds to a minute, they stop getting the negative effects like dropping held items.

**Comment by Exxion** [comment]
It's actually *better* than not mattering because once the bone is broken, it can't break again
So yes, they can break bones, but only once then in effect the bone heals itself forever
That should definitely be fixed

**Comment by Blithering** [comment]
Diona stronk
Also I'm not too good at the new armour resistance system, but with the armour vest (sec or barman kind) having 50 laser resist, does that mean it blocks 50% of the damage? Making a diona in a vest the same as baseline human?

**Comment by Kharkov72** [comment]
Fair points on both sides. I still think diona could use a touchup, but I don't believe this is the touchup they need.

**Pull request closed without merging**
