### PR TITLE
Revert "64x64 Sprites (#11214)"

### PR DESCRIPTION
**Pull request by PJB3005**
This reverts commit 6edf0208ac8e4bea5b596de53e674e0f84eaef6e.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Why?

**Comment by PJB3005** [comment]
Because it's clearly causing a lot of issues (especially making mapping impossible).

**Comment by clusterfack** [comment]
Let me see this mapping thing myself. It reminds me of a similar issue to when I first started working on 64x64 where if you set a normal world with world.icon_size of 32x32 to 64x64 everything would be invisible.

**Comment by Iamgoofball** [comment]
yeah, there's probably a fix for this shit

I've mapped in 64x64 no problems before so I wonder what's going on here

**Comment by TheFriggenSawbones** [comment]
PLEASE
IT WAS A MISTAKE FROM THE START

**Comment by unid15** [comment]
just do it please
- Compile times are crazy now

I booted up DM and opened test_tiny.dmm. It took 9 minutes 20 seconds to update all objects, and an additional minute to load the map. Compiling takes even longer
- Map editor is unusable now

See #11297 - and even if the bug with invisible objects is fixed, there will still be a lot of minor shit left. For example, icons breaking when changed, enormous instance icons, being unable to zoom out like you could before, etc.

Sure, having 64x64 humans is cool, but not if everything else is completely fucked.

**Comment by kol1th** [comment]
@unid15 Seems all byond related tools are fugged up. Compiling with ATOM is fine.

**Comment by clusterfack** [comment]
@unid15 It's all related just to the mapper. The mapper uses some built in assumptions about 32x32 that is causing both the longer compile times in dream maker as well as issues in mapping.

**Comment by unid15** [comment]
So let's wait until we get a proper map editor before converting to 64x64

**Comment by clusterfack** [comment]
You don't have to tell me that

**Comment by Iamgoofball** [comment]
or we just have lummox fix whatever bug it is

**Comment by 9600bauds** [comment]
> have lummox fix

Oh Goof, you card, you're a barrel of laughs!

**Comment by Iamgoofball** [comment]
He tends to fix bugs we bring up at the because we don't actively discourage donating.

**Comment by monster860** [comment]
image

I've been working on a new map editor, and it handles the 64x64 sprites just fine.

**Comment by Iamgoofball** [comment]
Inb4 it dies

You're open sourcing this right

**Comment by monster860** [comment]
I will open source this when it gets far enough.

**Comment by clusterfack** [comment]
<3

**Comment by ghost** [comment]
@monster860 thank you my friend :+1:

**Comment by Iamgoofball** [comment]
Open source it now. Don't ever wait.

**Comment by ghost** [comment]
@monster860 listening to goof is something you should never do. Open source it when you feel it is ready.

**Comment by Iamgoofball** [comment]
I'm gonna point and laugh when he disappears right before finishing it then

**Comment by Intigracy** [comment]
Closed source it just so goof can't have access.

**Comment by monster860** [comment]
He'd just decompile it... It's ridiculously easy to decompile shit nowadays.

**Comment by Iamgoofball** [comment]
And then when it breaks, it can't be fixed and I'll laugh at your petty attempt to fuck me over just because you're a piece of shit, Intigracy

**Comment by Intigracy** [comment]
He could always give source access to non-goofball.

**Comment by Iamgoofball** [comment]
That doesn't change the fact you're demanding closed source simply to fuck me over. Don't be a dick.

**Comment by 9600bauds** [comment]
i can't tell if this is the fabled double-inverse-goof maneuver or if it's just goof being goof

**Comment by 9600bauds** [comment]
is there a difference

**Comment by ScrambledSteak** [comment]
why did this nightmare happen in the first place
fuck you
screen-shot-2015-06-01-at-9 42 12-am

**Comment by SonixApache** [comment]
do it

**Comment by 9600bauds** [comment]
> All checks have failed
> 
> This branch has conflicts that must be resolved

**Comment by PJB3005** [comment]
If I'm gonna revert this I'll just check out all the old icons and reset the icon size.

**Comment by NigglyWiggly** [comment]
What about the fact that the 64x64 switch deleted a bunch of icons, though

**Comment by Exxion** [comment]
That would be fixed by checking out the old icons

**Comment by unid15** [comment]
So you're reverting this?

**Comment by Iamgoofball** [comment]
@NigglyWiggly stop making shit up

**Comment by NigglyWiggly** [comment]
The switch deleted multiple icons. The first one I noticed was a book from the library.dmi, the Segway sprites are entirely absent from the .dmi they are supposed to be in, and I'm sure there's plenty more examples people haven't found yet.

Quit making an ass of yourself, @Iamgoofball

**Comment by Iamgoofball** [comment]
can you provide some proof of your accusations

**Comment by NigglyWiggly** [comment]
You can literally look in the fucking library.dmi and the vehicles.dmi, but since that's apparently too difficult for you, here:





Notice anything?
Anything at all?
If two icons have the same name, one of them is deleted.
This probably applies to most things with animated movement, like two of the MoMMI skins, pudding, etc, but I'm not going to go check that for you too.

**Comment by Iamgoofball** [comment]
hey there you go you actually provided proof, examples, and a potential cause, i'll check it out and see if I can figure out why the converter is deleting icons

**Comment by Iamgoofball** [comment]
wait hold the fuck up why are you having icons with two names at the same time w h y

**Comment by NigglyWiggly** [comment]
I decided to check, and yes. This does break literally everything like that.
All of our mobs that animate like that.
All of our objects that animate like that.

**Comment by Iamgoofball** [comment]
jesus christ why do we do that for movement sprites there has to be a better not-shit way

**Comment by NigglyWiggly** [comment]
Also this is unrelated to that issue but the alphabetization of the .dmi's is gonna give me a fuckin stroke because I got super used to where everything was

**Comment by kol1th** [comment]
@Iamgoofball not that I know of

**Comment by unid15** [comment]
@PJB3005 you'll also have to edit all the maps to restore the original pixel_x/y values (some commits already touched them so checkout's not an option)

maybe just rollback to https://github.com/d3athrow/vgstation13/commit/66d143ca3dd6348b0333253658a360264f68ee30 and forget this whole thing like a bad dream

**Comment by PJB3005** [comment]
Nah reverting this shit is easy hang on.

**Pull request closed without merging**
