### PR TITLE
Adds Ablative Helmet to Box Map

### PR DESCRIPTION
**Pull request by GermanSanta**
🆑

rscadd: Adds Ablative Helmet ontop of Ablative Armor in the brig. 
Made Squatopia Barsign Sprite more accurate

Edit: The helmet is only laser proof it doesn't deflect shots.

### CODE REVIEW

**Comment by hacker-on-steroids** [comment]
>change 2 pixels of a random barsign as well

why?

**Comment by Eneocho** [comment]
I am become Ablino... The ruiner of fun...

**Comment by angryturnip** [comment]
non-atomic...

**Comment by Dacendeth** [comment]
You made this PR also do your sand thing.

**Comment by GermanSanta** [comment]
Fixed! Sorry about that.

**Comment by Eneocho** [comment]
https://github.com/vgstation-coders/vgstation13/blob/3dd52c94e508310598281ce3936f9f0e92325be5/code/modules/clothing/head/tactical.dm#L43-L53
Can confirm that the helmet is only laser resistant (80 laser armor), it does not bounce lasers, nor tasers (unlike the armor ablative)

**Review by west3436 — APPROVED** [review]
Sec power creep...

**Comment by west3436** [comment]
Also you might as well make the helmet printable at R&D while you're at it

**Comment by anonymoose-contributor** [comment]
This is awful and completely unneeded. Learn how to dodge and don't rely on the Ablative.

**Comment by west3436** [comment]
Don't think we need this

**Pull request closed without merging**
