### PR TITLE
INSTANT LIGHTING UPDATES

### PR DESCRIPTION
**Pull request by PJB3005**
This makes lighting instantly update.

Note: it may lag, I'm not gonna guarantee it won't lag.

This is mostly a test, if it DOES lag: RIP. If it doesn't lag: hooray.

### CODE REVIEW

**Comment by ghost** [comment]
Isn't this something to test locally ?

**Comment by Exxion** [comment]
:+1: :heavy_multiplication_x: :100: if it doesn't lag

**Comment by PJB3005** [comment]
> Isn't this something to test locally ?

I tested whether it works but I can't test performance on the scale of the live server.

**Comment by clusterfack** [comment]
How did you deal with explosions or mass deletes

**Comment by mph55** [comment]
Updates faster than the character movement.

**Comment by 9600bauds** [comment]
[cautiously hyped]

**Comment by ghost** [comment]
Can't wait.

**Comment by 9600bauds** [comment]
Oh yeah it'll lag.
But damn if it isn't sweet.

**Comment by PJB3005** [comment]
> How did you deal with explosions or mass deletes

Let's just hope not too badly.

**Comment by clusterfack** [comment]
Prayer was not the answer I was hoping for

**Comment by PJB3005** [comment]
Okay there's 1 more trick I have up my sleeve which might work.

Ill put a `sleep(-1)`in `effect_update` and give it waitfor, if it works as I hope it does it'll make sure corners and overlays aren't redundantly updated.

**Comment by clusterfack** [comment]
It would be nice if it could just redo lights after the explosion fully finishes

**Comment by PJB3005** [comment]
Should be feasible to code actually.

**Comment by jknpj** [comment]
[GHOSTLY FLICKING INTENSIFIES]

**Comment by ComicIronic** [comment]
Is this going to be updated?

**Comment by PJB3005** [comment]
Probably not.

**Comment by 9600bauds** [comment]
RIP hopes and dreams

**Comment by Shadowmech88** [comment]
It was too good to be true.

**Pull request closed without merging**
