### PR TITLE
Bagelstation episode two maybe?

### LINKED ISSUE #15136: Add basic shit to the Bagel Xenobio
(WEB REPORT BY: goodguy1448 REMOTE: 172.93.109.202:7777)
775c9e72c3a7b19cab2d4a63bdf521f5a7599d6f

The Xenobio at the bagel roid is missing basic shit like a regular fire ext. and a wall medkit (Or just add a white medkit to the sleeper room).

I got my chest ripped by an adult slime and ended up bleeding to death because i could't find a fucking gauze.

### PR DESCRIPTION
**Pull request by DamianX**
- Converted bagelstation.dmm to TGM
- Added it to the list of maps checked by travis
- Fixed a minor issue (Closes #15136)
- Deleted a rogue /mob/dead/observer that was mapped in for some reason

If people want bagel back, all that needs to be done after this PR is merged is to tell pomf to enable it.
I think a big part of the reason it was removed was its sheer size coupled with our low population, so a high population requirement would be in order.

### CODE REVIEW

**Comment by Gazathor** [comment]
BAGELBOYS ASSEMBLE

**Comment by RaccoonBro** [comment]
BAGELBOYS

**Comment by Kharkov72** [comment]
the pop wasn't the issue about bagel and you fucking know it

**Comment by RaccoonBro** [comment]
Just make Engineering not a nightmare and Bagel is perfect

**Comment by Kurfursten** [comment]
Add a cooking recipe for bagels

Require 200 bagels cooked to have bagel appear on the vote

**Comment by Kurfursten** [comment]
Congratulations... you conflicted yourself

**Comment by DamianX** [comment]
wtf how

**Comment by DamianX** [comment]
silicons did this

**Pull request merged**
