### PR TITLE
Changes Circus of Values vending machine description.

### PR DESCRIPTION
**Pull request by Hinaichigo**
This changes the Circus of Values vending machine description to:
`The Circus of Values offers a variety of toys and trinkets for sale. Would you kindly?`
from
`The Circus of Values Vending Machine offers a variety of items for sale. Most Vending Machines have items at the bottom that will only become available if you successfully hack the machine.`

The reason for this is that currently it seems very dry and "tooltippy" in contrast to other object descriptions. I think this change improves it in terms of immersion and also consistency with most other objects, which don't have anything like the current description, notable exception being the inflatable shelter "did you mean to resist free?" but that's more forgivable in my opinion.

:cl:
 * tweak: Changed Circus of Value vending machine description.

### CODE REVIEW

**Comment by Eneocho** [comment]
"offers a variety of toys and trinkets for sale." would fit.

**Comment by Kurfursten** [comment]
In this case it is actually **completely intentional**. This is a reference to the description text for the real Circus of Values from Bioshock. It's purely coincidental that we also hack machines to reveal new items at the bottom.

image

**Comment by Hinaichigo** [comment]
Hmmm.... I see. I've only played Bioshock 1, and it's been a while. Is that something that appears in-game written on the vending machine screen itself? Or like in a tooltip? Or some sort of hybrid where the vending machine screen displays additional tooltip-esque information that the player generally assumes isn't canonically on the screen from the character's point of view, but is akin to a tooltip?

**Comment by Hinaichigo** [comment]
I changed it to `The Circus of Values offers a variety of toys and trinkets for sale. Would you kindly?` Might be a nicer vibe this way and also be more consistent with the other vending machines.

**Comment by Hinaichigo** [comment]
Out of confused curiosity... to the downvoters, why is this controversial?

**Comment by Kurfursten** [comment]
For the record I also don't feel strongly about the description, I was just posting an explanation of why it is how it is. It doesn't bother me if you want to change it.

**Comment by Hinaichigo** [comment]
Okay last tweak and I'll leave it to the 'mojis.

**Comment by SECBATON-GRIFFON** [comment]
the existence of these vendors feel like a fever dream to me but i only say that because i first became aware of them on lamprey, if that helps

**Pull request closed without merging**
