### PR TITLE
(Bagel) Adds service desk to genetics lab.  Moves consoles closer together.

### LINKED ISSUE #17872: Bagel genetics improvements
Add a service desk so people can get curbside genetics and geneticists don't live in a cave.

Move the consoles one tile closer to each other so you can stand in between them like the autistic fuck you are and double fist the consoles.

### PR DESCRIPTION
**Pull request by Probe1**
Let me know how you guys feel about this one.  I played around on Bagel as a Geneticist and thought the room felt too closed in.  One of the design flaws with Genetics is on Box it's sequestered into a corner of Medbay where no one notices it exists until a person enters the cloner antechamber.  On Metaclub this issue is rectified and since the opportunity is there for Bagel I feel it should match it.  Here's the before/after pictures.  Changelog pending players signing off on the changes.
Closes https://github.com/vgstation-coders/vgstation13/issues/17872

Before
dreammaker_2018-03-19_17-13-15

After
image

🆑 

* tweak: Bagel Genetics now has a service desk and the consoles are closer together.

### CODE REVIEW

**Comment by Kammerjunk** [comment]
Finally, Bagel genetics get multi-console drifting

**Comment by Probe1** [comment]
It's funny I went into this PR thinking "Oh the consoles should be closer together for convenience."  Now I'm not sure.  Good mapping leaves things for players to improve.  A geneticist can get one simple wrench and move the consoles closer together to utilize both simultaneously.  Should that be left to the player?  Or will players not naturally appreciate having two consoles at once.  I don't want to take away from things players can do to optimize their jobs.  

Meanwhile the service desk was initially an afterthought once I took a harder look at the room and now I feel like it's the more important addition.  

Just map balance things.

**Comment by ghost** [comment]
Eh it's fine. The geneticist grabbing a toolbox doesn't really add anything. The improvement is in people getting a 3rd/4th setup and upgrading the components for faster injectors.

**Comment by Probe1** [comment]
Added a changelog.  I have some reservations but other people like the idea and either way there's not really a ton of strong feelings about it.

**Pull request merged**
