### PR TITLE
New suit and bugfix

### PR DESCRIPTION
**Pull request by NigglyWiggly**
Fixed a simple bug that I had missed the first time, decided that I'd add a bit more content so that the PR is slightly less embarrassing.

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
Well fuck, I don't know what could be causing it

**Comment by SkowronX** [comment]
outdated dmis

**Comment by NigglyWiggly** [comment]
fuck it, I'm just gonna re-do all the changes then

**Comment by clusterfack** [comment]
learn 2 rebase, it would fix all your problems instantly

**Comment by NigglyWiggly** [comment]
I redid all the changes with the latest .dmis even thought the only one with a conflict is suits.dmi and it's saying I haven't changed anything. I honestly don't see what the fuck could be wrong with it at this point

**Comment by clusterfack** [comment]
You cant have a commit in your pull that modifies a part of the repo that has also been changed on /vg/ the only way to resolve this is to start a git rebase with the most recent /vg/ commit. It will tell you what is conflicting and then you can choose to discard your changes or modify them to be compatible, then you add them and continue the rebase. Once it is done there are no more conflicts.

**Comment by NigglyWiggly** [comment]
That's what I did, though, and the conflict is still happening for some reason

**Comment by clusterfack** [comment]
Then you aren't rebasing to the most recent /vg/ commit, otherwise it would certainly be resolved. It could be one of two things.

1. You are keeping your current changes instead of the rebased version, in which case you should make sure to add the /vg/ version and see that it is using git status
2. You aren't using the most recent version, in which case you should fetch /vg/ again and then rebase directly from vg/Bleeding-Edge

**Pull request closed without merging**
