### PR TITLE
Adds "Pause after first step" functionality to integrated pAI bots and the AI Eye

### PR DESCRIPTION
**Pull request by BobdaBiscuit**
Basically https://github.com/d3athrow/vgstation13/pull/12846 https://github.com/d3athrow/vgstation13/pull/13200 to pAI bots.

Might have fucked up the ordering but it all works correctly.

:cl:
* rscadd: Added "Pause after first step" functionality to integrated pAI bots and the AI Eye.

### CODE REVIEW

**Comment by Zth--** [comment]
Oh yeah, I forgot to mention that your delays fixed my movement. Keep on track 👍

**Comment by Shadowmech88** [comment]
Instead of having to paste `user.last_movement=world.time` into every moving bot that pAIs get access to down the line, why not just put the code into `/obj/pAImove()`, since all the child procs call it anyway to check whether they can move?

**Comment by BobdaBiscuit** [comment]
Oh yeah that was kinda backwards, I think it works like that too for mobs etc.
edit: De-spaghetti'd it.

**Comment by ghost** [comment]
Any chance this can be added to AI camera mobs?

I try moving from hop to cargo, and end up in deep space

**Comment by BobdaBiscuit** [comment]
I'll see about that, I think it'll have the same issue as with when I tried with ghosties in that they don't actually have any delay system built in. I'll give it a whack some time tomorrow though.

**Comment by ghost** [comment]
Thank you

**Comment by Ephx1** [comment]
@Skullyton 
Toggle Camera acceleration speed

**Comment by ghost** [comment]
I do do that.

My screen freezes up and I end up spacebound if I just tap one of the directional keys

2fast2furious

**Comment by BobdaBiscuit** [comment]
@Skullyton 
Good news, got it working with the AIeye, will be adding it to this PR once I refine the timing a bit.

If this gets in and the timing is off feel free to give me a shout and I'll tweak it a bit.

**Review by PJB3005 — APPROVED** [review]

**Comment by ghost** [comment]
@bobda Thank you. Cant test it rn as Im on self imposed exile, but it is appreciated

**Pull request merged**
