### PR TITLE
Red Core, First Edition

### PR DESCRIPTION
**Pull request by Kurfursten**
New dice tower - guarantees a fair roll, even with loaded dice. Also if luck ever applies to dice, this will ignore it. You can place dice inside or throw them at it.
Battle mat - I wanted this to be paintable but I think that needs to be a separate PR. This mat rolls up when not on a table, and when on a table it adjusts to center properly based on the corner it is in. The really cool thing about the mat is that it allows you to place and grab pieces relatively far away across the 2x2 table.
Box of game pieces - includes 4 player minis, 3 hivelord minis, and 9 brood minis. Also includes the rules for Red Core, 1st Edition and character sheets for each job.
Red Core - An original, simple tabletop battle game. Choose between the shaft miner (grapples foes), paramedic (keeps you alive), anomalist (highly positional), and engineer (supports from afar) with distinctive styles. This dice system needs a d4, d6, d8, and d12.

image

- [x] Dicetower 
- [x] Battle mat
- [x] Red Core basic rules
- [x] Miniature for Shaft Miner
- [x] Mini for Paramedic
- [x] Mini for Anomalist
- [x] Mini for Engineer
- [x] Mini for Hivelord
- [x] Mini for Brood  
- [x] Character sheet for Shaft Miner
- [x] Sheet for paramedic
- [x] Sheet for anomalist
- [x] Sheet for engineer

Red Core is entirely untested as a tabletop game.
296447714-51d6ec5c-588f-46cf-9835-61330df82108

🆑 
* rscadd: The game master now spawns with everything needed to play Red Core, First Edition.
* rscadd: You can buy dice towers, battle mats, and a Red Core minis set at the games vendor.

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
How does the battle mat work, exactly?
If it’s just an item you put down on the table it’ll make putting pieces on top of it significantly harder

Also is it a 32x32 sprite that gets upscaled by 2 or am I reading that wrong

**Comment by Kurfursten** [comment]
It starts as a normal 32x32 sprite using the rolled poster icon, when placed on a table it snaps to position and unfurls into a 64x64 battle mat. The mat itself has click positioning like tables do so you can place a figurine anywhere on the grid.

**Comment by Cartlord** [comment]
I respect the effort put into this, but what makes you think that people will actually play this in-game?

**Comment by Kurfursten** [comment]
People used to play tabletop games in game, we added the Game Master alt title for that reason. Thing is, the game master has never... spawned with any game master materials aside from some dice. It was up to the player entirely to make or copy their own system, make character sheets, collect any props, and THEN FINALLY get to the part where they recruit players. They can still do that, but I want the game master to have at least one pre-built game option they can pull out of the box if they wish. I won't be heartbroken if this battle game is never played, I cooked it up with heavy influence from existing tabletop tactics games in about an hour.

**Comment by ErrorsWindows** [comment]
yooo we having the competitive omok tournament?

**Comment by Kurfursten** [comment]
Yeah, the other perk is that you can use the grid for anything you want. Checkers, Go, whatever.

**Comment by Cartlord** [comment]
> Yeah, the other perk is that you can use the grid for anything you want. Checkers, Go, whatever.

but are you actually adding checkers pieces, or go pieces? it seems like it'd be better to start small with easily understood games, than to add a game you made up and expect people to learn its rules and learn how the battle mat works at the same time.

**Comment by Kurfursten** [comment]
The battle mat works like a table, I don't think people are going to have a hard time learning "click where you want a piece to go". As for checkers, you can play that with coins or anything you want. I added a tabletop game because the job title is "Game Master". As in, someone who runs a tabletop game. You don't call someone a Game Master because they have a copy of checkers.

Porting a mainstream tabletop system like D&D 5e would not only be a copyright liability but also way more complicated. This is a very simplified tabletop game. No rolling for stats, choosing perks, determining hit locations, armor class, etc. Your character sheet actually has all your abilities on it. I'll post a screenshot to show what I mean, but like I said... if this isn't your kind of game, there's definitely no need for you to learn it.

image

**Comment by Kurfursten** [comment]
I thought it over, and if someone will provide the sprites I will include a checkers board and pieces in another PR complete with board.

**Comment by SonixApache** [comment]
dog bless you kurf

**Comment by ghost** [comment]
> I thought it over, and if someone will provide the sprites I will include a checkers board and pieces in another PR complete with board.

Holodeck already features a chess (and checkers) board. Holodeck in general is barely used, there is no need to make it even less popular.

**Comment by RealestEstate** [comment]
hell yeah!

**Pull request merged**
