### PR TITLE
Randomized Lawset event and module

### PR DESCRIPTION
**Pull request by toomykins**
[content]
Adds a Randomized Lawset generator, which functions as defined in #29250 . 
Also Adds an event - which is just as random as the electrical storm event - that replaces the AI's lawset with a lawset from this Randomized Lawset generator (Save for ion and 0-laws). The event can also be fired from the admin's Secrets menu.
Also adds an AI module that applies the same effect via the upload computers, creates a new lawset anytime it is used. It can sometimes be found in the station vault safe.

The admins are now able to change the silicons' default lawset to "random", which picks a lawset from a biased list, shown here:

> 40% chance of ASIMOV
> 34% chance of Lazymov
> 15% chance of NTD
> 5% chance of Corporate
> 5% chance of Robocop
> 1% chance of Hogan

Balancing the feedback in the PR, thread and from the admins lead me to this conclusion. A lot of players wanted less AI intervention, which Lazymov provides balanced with the low chance of more "serious" lawsets. Still this should make your experience with and as the AI a little less monotone.
Again, this specifically requires the admins to select this at roundstart, so the chance of Hogan should be even more negligible than one in a hundred. I address this due to admin concerns.

Please do not confuse the two concepts of "Random" in this PR. One is a lawset generator, the other is a random predefined lawset picker, and this time the lawset picker never picks the lawset generator. Again, everything is up for discussion.

:cl:
 * rscadd: Added the Randomized Lawset, which generates a random lawset from predefined laws. as well as a random event which applies it to the AI. It also comes in upload module form, which can sometimes be found in the station vault's safe.
 * tweak: It's now easier for admins to set the AI's default lawset to a random pick from a biased list of defined lawsets at lobby time.

### CODE REVIEW

**Comment by jwhitak** [comment]
Upvote for the randomized lawset and module to upload it. This sounds great as a traitor tool, or as something to experiment with as an RD.

Downvote for the random event that can trigger in the middle of the round, completely ruining multiple players' experience all at once. I'm really glad that my subverted tator AI just rerolled into Robocop at the right moment after all of my tator tot prep and spending of TC on things to support this.....

**Comment by KingofHONK** [comment]
I like the concept of an event that randomly changes a lawset into a different, prefab one/themed lawsets. However, less AI intervention will be on the AI player, the lawset will do little to fix that

**Comment by toomykins** [comment]
> Downvote for the random event that can trigger in the middle of the round, completely ruining multiple players' experience all at once. I'm really glad that my subverted tator AI just rerolled into Robocop at the right moment after all of my tator tot prep and spending of TC on things to support this.....

I understand your concern, the event was mostly put in as per feedback received on the last thread. I could add a couple of flags/conditions to it, or remove it altogether.

**Comment by GreatBigFailure** [comment]
The lawset generator was what was interesting about the last one to me. Honestly I'd much prefer that over a random predefined lawset. Still, it's a positive to have either. Just much better to have the generator in my opinion

**Pull request closed without merging**
