### PR TITLE
Re-enable round end report for team antags.

### PR DESCRIPTION
**Pull request by Allspice**
1E17% tested.

Seriously though I only checked blob and cult and it seemed alright for both of those.

### CODE REVIEW

**Comment by jakmak** [comment]
Would this also show round end for raiders or nah?

**Comment by Exxion** [comment]
I was going to ask whether that was 1E(17%) or (1E17)%
But both of them are more than 100%

**Comment by Allspice** [comment]
heist

**Comment by Exxion** [comment]
The worst that could possibly happen is it showing up twice for some gamemode so let's do it

**Pull request merged**
