### PR TITLE
Fucking Fix Vampire

### LINKED ISSUE #5089: Fucking fix vamp
The fact that they can get up after death in two secs in dumb fix the timing or take off that power

### PR DESCRIPTION
**Pull request by clusterfack**
Fucking fixes #5089

### CODE REVIEW

**Comment by clusterfack** [comment]
"Balance"

**Comment by ComicIronic** [comment]
>literally a balance change
>somehow not balance

**Comment by Probe1** [comment]
it's not a balance change. velard mistakenly wrote 2 seconds instead of 200.

**Comment by ComicIronic** [comment]
Something being a mistake doesn't change it being a balance change.
The mistake is still a balance mistake.

**Comment by Probe1** [comment]
well said.

**Comment by FudgePucker** [comment]
Eh it's not really a balance change.
For example, when spamming wire clippers when disassembling airlocks would give you more wires back, it was a bug, but fixing it wouldn't be a balance change, its just fixing a missing line.
This is fixing a mistyped line of code.

Plus adding the balance tag would slow down this getting merged.
Balance tag is used for changes for balance and not fixes. Giving the HoP a loyalty implant is an example, HoP not having one isn't a bug. This is vampires getting up after two seconds when they should get up in two minuets.
Although, wouldn't the right number be 120 instead 200? Or is the code ...xyz=...x:yz? Where yz are seconds and x being minutes?

**Comment by FudgePucker** [comment]
Shit why not add hotfix? This is just a minor fix to a major bug.

**Comment by FudgePucker** [comment]
Shit I am on my phone so I can't edit, just saw the hotfix tag.

**Comment by ComicIronic** [comment]
> For example, when spamming wire clippers when disassembling airlocks would give you more wires back, it was a bug, but fixing it wouldn't be a balance change, its just fixing a missing line.

That's because cutting wires out of airlocks isn't an antag ability that needs a cooldown.
The code is working as expected, the only issue is that the cooldown is too short. It's a balance change, and you can't cut it any other way. Even if it was intended to be different, it's not malfunctioning.

**Comment by 9600bauds** [comment]
It's not working as ~intended~. You can't handwave that part out.

**Comment by FudgePucker** [comment]
The difference between two seconds and two minuets is like having a donut hole and eating two dozen donuts.
It is too major to be a balance change. Balance for bugs is fine if the bug is minor and mostly unnoticeable. For example, using wrapping paper to fit bulky items to put in normal bags. Minor oversight that fixing would change balance. Vampires getting up in two seconds is way too broken.
Let's say there was a bug where using a screwdriver on a crowbar created a stage 5 singulo, and its also log less. Because antags could use it its a balance change. So instead of it being merged as soon as someone can, they have to consider balance, meanwhile every round someone creates a singulo in the middle of the station.
That's an extreme example, although vampires getting up in two seconds is almost as broken.
Disarm RNG pushes last for less time than it takes for a vampire to go from being dead to full health. Got ten brute damage? It would be faster to stab your eye with a screwdriver into crit, succumb, and regen then waiting for it to heal from nutrition.

Wowzers its a better option to suicide then to look for a first aid kit. Better add the balance tag.

**Comment by ComicIronic** [comment]
>Let's say there was a bug where using a screwdriver on a crowbar created a stage 5 singulo, and its also log less. Because antags could use it its a balance change.

Some things can also be both.
A good example is the change to airlock wires, which fixed a bug in behaviour but brought a balance change along with it because of it.

And this going back to how you define a bug: a bug is bad or failed behaviour. This is not a bug. Nothing in the code is going wrong. A runtime isn't firing. There isn't some result that isn't coming out of the big calculation machine.

It's a mistake, sure, but it isn't a bug, it's a balance fix to a very overpowered ability.

**Comment by FudgePucker** [comment]
Okay it is a balance change, but one that is simple to fix and should be fixed ASAP.
Like 7 hours ago ASAP.
At least add back in the hotfix tag, I don't think that anyone would want to debate vampires going from dead to full health in two seconds instead of the already over powered two minutes.
These comments shouldn't be us having a debate on if its a hotfix or balance change on a open PR, it should be us joking that velard is as good at shitcoding as he is at shitposting :^) on a merged PR.

**Comment by 9600bauds** [comment]
A bug, an oversight and a mistake are all similar in how they are fixed and identical in their need to be fixed.

**Comment by clusterfack** [comment]
The person who coded it himself said it was not intended to be that, if something isn't working as intended in the code it is a bug.

**Comment by AutismSpider** [comment]
its bug even the shit posting nergo said it was not intended.

should be hotfix can not kill a vamp unless you force feed them water+potas to gib them even then they get up by the time you feed them the 2nd pill

**Comment by Probe1** [comment]
you niggas talk to much and that comes from someone who talks way too damn much

**Pull request merged**
