### PR TITLE
Outfit datums - BE parity

### PR DESCRIPTION
**Pull request by ShiftyRail**
Yes, I still intend to work on it

I commend the codebase on adding 164 000 lines and removing 40 000 other lines in the span of two months

### CODE REVIEW

**Comment by Kurfursten** [comment]
Imagine being the collab who is going to have to pretend they read all of this to review it 😂

**Comment by Kharkov72** [comment]
good lord what is happening in here

**Comment by ghost** [comment]
what is this

**Comment by PrimeDSS13** [comment]
nice changelog bro

**Comment by ghost** [comment]
jesus christ how horrifying

**Comment by ShiftyRail** [comment]
Wait a sec this isn't supposed to be in a single commit
What happened

**Comment by Zth--** [comment]
put the merge from bleeding edge into one commit and your changes on another

**Comment by ShiftyRail** [comment]
>put the merge from bleeding edge into one commit

that's not really what I want, I want all commits from BE to be here
parity, same history AND same content, and all that

**Comment by ShiftyRail** [comment]
May the Git Police have mercy on my soul : #25833

**Pull request closed without merging**
