### PR TITLE
Changes security cyborgs back to what they once were

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
The survey pushing for the name change was 2 years old- odds are the people who wanted it have long since stopped playing, so it shouldn't be used as a justification for a change nobody wanted at the time it was actually merged- and secborg shitters haven't stopped just because the name changed. Besides, the baby blue color scheme looked hideous. 

And most importantly, it has not and never will stop the shitters who want to play as an unstunnable security officer. This is a policy issue, and one you can't just code out.

### CODE REVIEW

**Comment by N3X15** [comment]
Not taking sides on this one.  Had my double dose of drama for the week.

**Comment by Intigracy** [comment]
bubblegum pink when

**Comment by Kitfox88** [comment]
I demand the ability to look fab no matter what chassis I pick.

**Comment by Riekland** [comment]
I would say put up another server poll but since our admins are mouthbreathing tards it would just cause more of this shite

fucking why

ps fucking fix this you cockgobbling shitheads

**Comment by Probe1** [comment]
You can see the contrast from when I was the only one with +Poll, and from when Pain gave it to everyone.

**Comment by Probe1** [comment]
Also no to this PR I don't know why you think this will be merged.  It was something the players are fine with.  It's something that improves things from a player-admin side and results in less confusion and bans.  It _greatly upsets_ people who want to play as an  unstunnable sec officer.

Revert the baby blue shit sure they look much better in red but you're gonna have to find something useful to get really mad about.   This will not  be it.

**Comment by Ephx1** [comment]
I really don't care anymore but bay has the hard ass administration that beats you back into line, AND their standard lawset is NT Default.
So using "even bay has this" is a poor argument.

**Comment by JustSumBody** [comment]
@riekland
Poll making is actually just  straight fucked and not documented

Hitting "cancel" makes the poll regardless
Having the poll be too long makes the rest of it(including the options) just straight not appear
Polls can't be removed by anyone but pomf last o checked as well

**Comment by 9600bauds** [comment]
I think it's a little early to say if the sprites had an effect or not

**Comment by Intigracy** [comment]
Poll making hasn't been changed since I ported the shitcode monstrosity from TG.

I was trying to improve it but got confused so gave up.

In the meantime, try getting good.

**Comment by Shaska-** [comment]
Personally, I'd prefer to keep the new name, but change the sprites back, or at least to something that doesn't look shit.

**Comment by icantthinkofanameritenow** [comment]
@Probe1 
>it greatly upsets people who want to play as an unstunnable sec officer

A name change won't stop shitters from acting like shitters, this was an attempt to code away a problem that was always a matter of policy (i.e. being too soft on silicon bans). 

Have you noticed so far that the admins are currently the only people objecting to this? That should be a sign as to what people really want.

**Comment by SonixApache** [comment]
I enjoy calling my borgs peacekeepers.
I enjoy ordering them to 'keep the peace'.

It makes more sense than security.

I'm not 100% on the colors, but it does scream "you are not security" which might help new players.

**Comment by 9600bauds** [comment]
I'm not an admin :^)

**Comment by icantthinkofanameritenow** [comment]
@SonixApache From what I've seen, it doesn't really work because "peacekeepers" still ignore orders on Asimov and generally do everything that this change was supposed to prevent. That's my main gripe with all of this, the whole thing made next to no difference in what it was meant to do so it comes off as  arbitrary and generally pointless. 

The problem is with the players, not the name and colors. Hell, I'd be fine with the name if they were at least reverted to the old color scheme, but I wouldn't expect anyone to act differently just because they're not explicitly named "Security".

**Comment by ihadtoregisterforthis** [comment]
Peacekeepers need more work instead of ONLY a rename and recolor. A change in the modules, references to secborgs, and I think the *law emote that wasn't touched.

**Comment by icantthinkofanameritenow** [comment]
@ihadtoregisterforthis 
That could work. There's already a precedent in combat borgs being locked behind code red, so you could just make it so secborgs can only be made active on code blue or higher. And unlike code red, any head can call code blue so nobody would need to worry about a lack of heads/comdom.

Peacekeepers could then fill a niche as a combined paramedic/emergency backup security officer, focusing more on preserving lives rather than actively going after things causing harm. That way the people who want to play the goody-two-shoes harm alarm can go about their business without interfering with the fact secborgs are often the only security on the station.

**Comment by Riekland** [comment]
Or you could just enforce asimov by handing out day/weekbans on borgs
You know, like you're supposed to
:^)

**Comment by icantthinkofanameritenow** [comment]
Text reminding secborgs that they don't follow spacelaw has now also been enlarged. If anyone overlooks it now, they frankly deserve the silicon ban.

**Comment by icantthinkofanameritenow** [comment]
fuck it, this isn't going to be merged anyway

**Comment by Ephx1** [comment]
changed your mind in 3 minutes, wow!

**Comment by icantthinkofanameritenow** [comment]
I have nothing to lose by having this open. For the moment.

**Comment by SangriaMonkey** [comment]
I think it's the precedents that have been set for silicon behavior that cause the problems people have with borgs. You're not going to be able to change that with flavor text and resprites.

**Comment by SonixApache** [comment]
Maybe if we keep them as PEACEKEEPERS long enough they'll adapt?

**Comment by SangriaMonkey** [comment]
Doubt it. They're about one pull away from getting commented out unless something changes from a policy perspective.

**Comment by icantthinkofanameritenow** [comment]
My point precisely. There's no reason that breaking silicon laws should be a "grey area". If someone didn't know the rules about silicon laws and how they interact with space law, it's their own damn fault for not reading them.

**Comment by Shadowmech88** [comment]
If an Asimov engineering borg breaks its laws in the process of repairing the station, it gets banned.
If an Asimov janitor borg breaks its laws in the process of cleaning the station, it gets banned.
If an Asimov mining borg breaks its laws in the process of mining the asteroid, it gets banned.
If an Asimov security borg breaks its laws in the process of arresting someone, the entire borg subset gets renamed and recolored?

How does this make sense?

**Comment by ihadtoregisterforthis** [comment]
Because the last one happens very very often, even after healthy amount of bans and bwoinks. Making it violently clearer reduces the possibility of misunderstanding.

**Comment by Probe1** [comment]
What he said.  No, this will not stop die hard shitters from ignoring their laws and eventually getting ahelped and banned.

Yes, it will help clarify to newer players their role.  It is confusing to a new player that a _security_ borg isn't actually _security_.

A lot of this is theorycrafting.  I've been an admin for two years.  I'm empirically aware that newer players get confused by it and I also well remember how this change was going to be done but then it was shitposted into oblivion by a minority.

**Comment by SangriaMonkey** [comment]
I'm not convinced that new players, as in people who aren't just ban evading, are comfortable enough with the game to try any silicon role before they're aware of the role that security borgs play.

**Comment by Shadowmech88** [comment]
I think it's possible that the volume of people disobeying their laws as secborgs isn't because they misunderstand their role, but rather they're intentionally being shit and chose to be a secborg because it gets access to the best tools with which to be shit.

**Comment by SangriaMonkey** [comment]
That, plus their complete lack of accountability compared to actual security personnel is a huge issue.

**Comment by SonixApache** [comment]
Let's have another quick asimov discussion while we're at it.

If you detain a man for harming, and you let him go because he orders you, and then immediately harms again, can you detain him for longer wile ignoring orders for his release? If you comply, you'll have to babysit him or he'll probably harm again. If you comply and let him go, you'll likely cause harm by inaction. But if you don't comply, you violate law 2. What do you do?

Also what the fuck do you do as AI when borgs fail to comply with laws? Just tell them off? Lock them for a while? Blow them immediately?

**Comment by Shaska-** [comment]
@SangriaMonkey 
Most new players don't understand the role that sec borgs play before they've played them for a while.
It's quite natural for inexperienced players to think that a borg called "security", with the same color scheme as security officers, and the same weapons should be doing the same job that security officers are doing. 
A change of name and color goes a long way to getting them on the right track sooner.

**Comment by SonixApache** [comment]
This change is also perfect for having the silicons act as the UN in nations.

**Comment by Ephx1** [comment]
@SonixApache 
Lock that fucker second time around, once he begs endlessly enough to be let out do so, then when he harms again toss him in the permabrig and never look back.
If you're AI tell those borgs to fuck off, if they continue you lock them down.

Here's a real conundrum for you: If a catbeast is scum, but they were unwillingly changed into a catbeast, do you kill them on Paladin?

**Comment by SangriaMonkey** [comment]
I would think that someone who isn't experienced with the game or silicon roles wouldn't be that eager to try being one. If the thread is any indication, people seem to be terrified of trying new jobs.

**Comment by icantthinkofanameritenow** [comment]
@Shaska- 
Most of the time, new players aren't the ones causing the problems as secborgs. It's almost always people deliberately using "BUT I'M SUPPOSED TO BE SECURITY" as a smokescreen to get away with breaking the rules- it's not genuine ignorance, it's just bullshit meant to let them off easy. If they were really new, they wouldn't have picked a job locked to new players and explicitly described as being one of the most thankless, painful jobs to take. As SangriaMonkey mentioned, accountability is the problem since the message that sends is "if it doesn't get you banned, do what you want". 

@Ephx1 
Well, they do beg for death as part of being catbeasted, and it would be evil not to end their suffering...

@SangriaMonkey 
Even if that wasn't the case, the mandatory waiting period before the non-MoMMI silicon jobs are available to new players should ensure that inexperienced players wouldn't be made secborgs in the first place.

**Comment by aceedex** [comment]
We have a giant warning that tells you to follow your God damn laws. Why we even needed that chickenshit change is beyond me. Or do we just change things when someone'says feelings two years ago got hurt on a whim?

Fuck. Silicon ban for a week and move on if someone doesn't follow their laws. This isn't rocket surgery

**Comment by aceedex** [comment]
Also, make assistants spawn in with randomized color jumpsuits and call them happy helpers. I'm sure that'llegar ease the greytising

**Comment by Shadowfgt** [comment]
where is our server vote so we can get rid of this ugly shit.

**Comment by Ephx1** [comment]
lol

**Comment by Shadowmech88** [comment]
When are we going to hold a server vote on this?

**Comment by Probe1** [comment]
I completely forgot about it like everybody else when they found something new to cause drama over.

**Comment by optimumtact** [comment]
just remove it

**Comment by Sarcalogo** [comment]
WISH WE COULD TURN BACK TIME.
 TO THE GOOD OLD DAYS.

https://www.youtube.com/watch?v=EscvKMOK_5c

**Comment by gbasood** [comment]
rip this pr tbh
re-open when it has no conflicts or someone else make a PR if you still care

**Pull request closed without merging**
