### PR TITLE
Adds H/E Manifolds

### PR DESCRIPTION
**Pull request by mtpowell**
110% Tested

### CODE REVIEW

**Comment by Exxion** [comment]
Absolutely horrifying

**Comment by mtpowell** [comment]
Please be more specific

**Comment by Exxion** [comment]
I can't, because I'm not well-versed enough in atmospherics
But someone will do horrible things

**Comment by mtpowell** [comment]
..horribly fun things?

**Comment by Exxion** [comment]
In the Dwarf Fortress sense

**Comment by ghost** [comment]
GOD YES

I WILL LOVE YOU UNCONDITIONALLY IF THIS WORKS

**Comment by mtpowell** [comment]
It does work, I tested everything with it.

@Exxion 
The worst that's gonna happen is some crab will make an autism engine that will surpass metal gear

**Comment by SkowronX** [comment]
Good lord, H/E pipes in parallel? What's next, coding flow and its effects on H/E?

**Comment by AutismSpider** [comment]
if any thing just save bit of time on set ups.

@SkowronX working gas flow and pipe bursting thats not dumb.

**Comment by clusterfack** [comment]
You know people are just going to make giant grids of just manifolds right

**Comment by AutismSpider** [comment]
@clusterfack gives me some thing new to play with. like the time we got layers i and turn the serb into a chat room form massive 600 stack i did.

**Comment by PJB3005** [comment]
@AutismSpider I hope you realize I still want to disable having more than 4 devices on a tile with layers.

**Comment by Riekland** [comment]
@clusterfack are you saying that's an issue or

**Comment by Probe1** [comment]
Neat

**Comment by clusterfack** [comment]
Yes I am

**Comment by PJB3005** [comment]
To be honest I find that H/E pipes only being straight and bent is a nice unique feature of them and it makes them stand out.

Also logically the manifolds should have a lower heat transfer coefficient due to lower surface area.

**Comment by Shadowmech88** [comment]
If we decrease the heat transfer of the manifolds, will it make the possibility of manifold grids less of an issue?

**Comment by PJB3005** [comment]
Yes

**Comment by mtpowell** [comment]
@PJB3005 

I took off a fourth of the heat transfer, as it currently stands

Pipes = 32000
Plates = 30000
Manifolds = 24000

N3X amped pipes up from plates, which is backwards I think, there's no point in using plates. I think you should reverse them in your PR to force people to utilize them.

**Comment by SonixApache** [comment]
100% unnecessary

**Comment by mtpowell** [comment]
>Unnecessary

There are currently no other ways to merge H/E pipes without adding junctions. This also has a lower heat transfer than H/E pipes so tiling them wouldn't be as efficient as using pipes. 

Sounds pretty necessary to me.

**Comment by ihadtoregisterforthis** [comment]
If manifold fields are a definitive no, the three way manifolds can be enough most of the time

**Review by ComicIronic — APPROVED** [review]

**Comment by ComicIronic** [comment]
We should technically look at moving the way HE pipes work so that it can be plugged into any pipe, because this has a lot of duplication with existing manifold code (but do so other pipes, so it's not a massive issue).

**Comment by FudgePucker** [comment]
I have mixed feelings about this.
This would let you make neater cleaner pipe layouts, and with the thermal extange reduction on them makes it not game breaking (why would you make grids of four ways when you could just spaghetti together a set up that allows double the pipes on a turf using just straight and bent ones?)

This however would make thermal plates more worthless because it removes one of the few downsides to h/e pipes.

**Comment by PJB3005** [comment]
@FudgePucker you wouldn't want to use these in a cooling grid because of their lower stats.

**Comment by FudgePucker** [comment]
Exactly.
It would make it easier to crisscross straight pipes across each other. Use the manifolds on the outside and straight pipes on the inside.

**Comment by ComicIronic** [comment]
Let's see how strong the actual impact is - I predict day one Danny McAtmos makes a grid of these and calls them shit.

**Comment by Exxion** [comment]
Why the fuck would you make a grid of these? Make two perpendicular lines of them and then make a grid of *straight* HE pipes.
Twice as many pipes per tile, *each* of which has greater heat transfer.

**Comment by ComicIronic** [comment]
Because Danny McAtmos isn't actually good at his job.

**Pull request merged**
