### PR TITLE
The "Extended" dynamic ruleset will no longer fire at 20 in-game players and above

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Everyone who has played through multiple Extended rounds can attest to the loss of server population and general player interest after an Extended round, where the round right afterwards has way less players than the round before had but to a degree that is more severe than the usual loss of players between rounds. This causes the period of time where the server is more populated to lose steam, as players beget more players and Extended "exhausted" a number of players by itself, getting worse the longer the Extended round has been.

This PR lowers the threshold at which Extended is unable to roll from 45 (the "high-pop override" mechanic, set at 45 in-game players, disables Extended) to 20, leaving Extended to roll during the lowpop, more peaceful rounds but unable to cripple the pop at 20 or above in-game players. However, this deliberately does not prevent "pseudo-Extended" where the round simply doesn't have enough threat to fire any other gamemode, which makes the rare high-pop Extended round actually special and not a semi-regular occurrence.

:cl:
 * experiment: Dynamic will no longer fire the "Extended" ruleset at 20 or above in-game players.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
i think 25 is better

**Comment by boy2mantwicethefam** [comment]
I'm on the fence between 20 and 25 because it counts in-game players specifically and 25 is harder to achieve than 20, I've also taken into consideration the usual number of players that do not join at the start of the round (so you could end up with, say, 26 or 27 players yet only 20 or 21 in-game players), the change is more to hopefully encourage player retention in the early phases of "primetime" and thus reach higher player counts more easily. Personally I often don't see rounds with more than 25 roundstart readied players in most evenings, even when the player count is higher than that.

**Comment by ValkyrieSkies** [comment]
Extended isn't a low-pop game mode, it serves a pretty important purpose in that the fact that it exists means you can't just assume there are antagonists every single round and thus won't jump the gun at anyone acting slightly odd. If you make it so that Extended never happens above a certain population threshold then people can be certain antags exist in the round which will alter their behaviour.

**Comment by boy2mantwicethefam** [comment]
Fair enough

**Comment by boy2mantwicethefam** [comment]
Wait a minute, the threat report already mostly confirms whether it's Extended or not!

**Comment by wotisjanitor** [comment]
does anyone actually read that, i never have

**Comment by boy2mantwicethefam** [comment]
I do at least...

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
remove threat report

**Comment by SonixApache** [comment]
> Wait a minute, the threat report already mostly confirms whether it's Extended or not!

it should absolutely not do that

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
The first paragraph of the OP doesn't seem true to me

i think theres a bias where people claim various maps, game modes, antags, etc cause pop to decline but, actually since most people join during highpop and then observe the pop declining after the highpop rounds, they attribute the pop decline to whatever happened during the highpop rounds. And with extended rounds usually being longer than other rounds, it's more likely they'll segue directly into the post-highpop pop decline. So it might seem like extended caused it but moreso it's just the natural rhythm of more people tautologically playing the highpop rounds then going to bed irl

**Comment by boy2mantwicethefam** [comment]
Already considered that but it didn't add up because Extended rounds cause the pop to decline harder than usual, and on minimum have less additional players in the next round than usual, I'd say it's the equivalent of roughly 2 quick & hectic rounds in a row in terms of how it lowers the pop, for example nukies blowing up the station one round and then a wizard summoning guns 4 times the next round, that exhausts people.

**Comment by NigglyWiggly** [comment]
Absolutely devoid of any and all soul. Extended is the best gamemode.

**Comment by GreatBigFailure** [comment]
> does anyone actually read that, i never have

I try to remember to. It's good for knowing if you should commit to a gimmick or just hang out until everyone dies.

**Comment by boy2mantwicethefam** [comment]
Not enough support.
Another addition to my collection of "you could have stopped this" PRs that I will mention when another victim of Extended At Prime Time Syndrome complains in deadchat about it before logging off for the rest of prime time.

**Pull request closed without merging**
