### PR TITLE
Tiny tweaks to trashy taxi

### LINKED ISSUE #7942: Solar Array APCS
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> solar array apcs dont work this is on taxi station
> 
> What you expected to happen
> take out battery power goes out
> 
> What actually happened
> nothing power stayed on
> 
> Steps to reproduce if possible
> take out battery

### LINKED ISSUE #7962: [Taxi] Bar maint door is the worst fucking door ever fucking conceived
Who has access to the door: Everyone with maint access
Who doesn't have maint access: The bartender
This means that anyone on the station except scientists can just walk behind the bar and steal all the bartender's shit, while the door doesn't benefit the bartender in any way

### LINKED ISSUE #7965: Taxi Medical Dock APC unpowered
(WEB REPORT BY: codenameb REMOTE: 158.69.55.2:7777)

> Revision: 2ed979bd5ad42f9522243562bd1f1cded0f45329 
> 
> General description of the issue

Taxi Medical Dock APC has no wire connecting it to the grid!

> What you expected to happen

The APCs to be connected to the powergrid.

> What actually happened

Mapper fucked up.

> Steps to reproduce if possible

Go visit the APC in the taxi dock medical station.

### PR DESCRIPTION
**Pull request by xpcybic**
- Cameras at each taxi dock will now appear first in the security and AI camera list.
- Fixed access on bar maintenance. It should no longer be the worst door ever conceived.
- Fixed floating, broken APC in solars near cargo.
- Fixed emergency shuttle brig not counting against the "escape alive and free" objective.
- Fixed many, many cases of airless plating where there should be air - and some normal plating where there should be airless.
- Fixed barricade walls on derelict where there should be window barricades.
- Scientists now properly have access to xenoarch wing and research shuttle.
- Fixed cabling on antimatter engine SMES. _(screenshot below)_
- Fixed med/silicon dock APC not being wired to grid.

Fixes #7962, fixes #7942, fixes #7965

The first change is meant to be a minor quality-of-life improvement for AIs, since I've seen a few complaints about trying to navigate between stations as AI.

screenshot 2016-01-30 21 57 28

### CODE REVIEW

**Comment by Kurfursten** [comment]
I can't think of any reason you would want the SMES wiring set up this way instead of the previous way. Your SMES is going to feed off the main grid and your AME is wired directly into the main grid.

**Comment by xpcybic** [comment]
screenshot 2016-01-31 00 44 45
Better?

**Comment by Kurfursten** [comment]
Yes

**Comment by MusgardTiger** [comment]
Godbless you my good man.

**Comment by clusterfack** [comment]
Nobody cares about taxi anyway lmao

**Pull request merged**
