### PR TITLE
Horror form major buff update

### PR DESCRIPTION
**Pull request by kilkun**
Changes:
-Changed Horror form health to 800.
-Added BLOCKSHAIR flag so human horror forms no longer have floating
hair
-Added STOPSPRESSUREDAMAGE flag so it can space walk
-Added the Blair Thing's scream as greaterling.ogg
-Raised it's max hit damage from 20 to 30
-Added notification to the world whenever a ling evolves, so that it
can't use it's 3 hit crit to yakety sax through walls and go undetected.

The idea is to make the presence of a horror form a REALLY, REALLY good excuse to call the shuttle. It's not invincible, and a coordinated attack will put an end to it, but it can easily kill anything short of a Ninja in a one on one fight.

Now Horror Lings are worthy of the title "Horror"

### CODE REVIEW

**Comment by IratePirate** [comment]
Maybe now we won't have 4 hour rounds where the lings eat monkeys and autism in Virology for the rest of the shift.

**Comment by Boxe** [comment]
make it rename the horror ling to "Kilkun Is Gay"

then it'd represent how good of an idea this is

**Comment by ComicIronic** [comment]
Same as last buff: I'll leave it open for discussion, but no objections and it'll be flagged as ready.

**Comment by utilitas-** [comment]
Give it a much lower genomes requirement and we'll be gold. Even murderboning is better than the terrible changeling mode we have right now.

**Comment by ComicIronic** [comment]
Why does the Horror form only regen when activated?

**Comment by clusterfack** [comment]
>even murderboning is better
Dude... what

**Comment by kilkun** [comment]
It takes 1 egun to kill it from 500, so about one and a half to take it down from 800.

**Comment by kilkun** [comment]
Utilitas, the idea of the buff is to make it worth the 30 and be a shuttlecall tool for changelings. At it's current (really, REALLY) overpowered state 30 almost seems too little. I mean that's only 15 victims. 13 if you don't use any of your starting evo points.

**Comment by clusterfack** [comment]
To be honest I think the only thing that can save changeling as a gamemode would be to remove absorbing monkey humans (which is the reason changelings can play stealth ling all day) and give MUCH more genomes from absorbing human beings. Higher risk, higher reward.

Stealth ling play is the result of very low risk, low reward gameplay mechanics.

**Comment by kilkun** [comment]
I've been looking into that nerf since I started this PR. I might make it so that absorbing monkey humans subtracts evolution points, but still give genome score.

**Comment by AutismSpider** [comment]
health to high for how faggy people are here.

They just run off to space to heal up drop it to 400/500 or up how burn damage they take to.

That and monkey humans only counting for genome score sounds fine.

**Comment by kilkun** [comment]
It really isn't all that high. 2 or 3 people with eguns getting the drop on it and it's game over.

**Comment by AutismSpider** [comment]
You forgot this is VG rarely do you see team work unless its Ai+cyborgs or two or more rouge mommis butt fucking the station.

**Comment by IratePirate** [comment]
Then they should get fucking good. If a horror form is tearing it up the HoP, HoS and Captain should be seeking their valids competently enough to kill it.

**Comment by kilkun** [comment]
If the community refuses to work together and gets killed constantly as a result, then they have only themselves to blame.

**Comment by Duny-** [comment]
I agree with the two last comments. The game shouldn't be designed around the retards, the retards should git gud for the game.
I think we should give this a try and tweak it if it proves to be too powerful. It's not like changelings can get any worse anyway.

**Comment by clusterfack** [comment]
The problem with that duny is the 'git gud' attitude towards balance. Even if something is clearly too powerful to the point of ruining rounds, people will treat it as balanced and sensible mechanics (i.e. firebird and staff of change) and defend it to the death.

**Comment by Duny-** [comment]
Well then don't add anything to the game JUST IN CASE it proves to be imbalanced or impacts it in a negative way. Freeze the code entirely. Or grow some balls and tweak your shit before it becomes standard and lowers the overall quality of the game, without listening to the percentage of the playerbase who complains for the sake of complaining. (probably republicans)
Being too afraid of what retards think is of you is the kind of attitude that spawned mechanics, who still don't really have a purpose to this day and only do what other jobs could already do. Reminder that percentage of the playerbase complained when you couldn't copy/paste guns with them anymore.
There's an entire universe between ignoring idiots and becoming erro.

Just merge that shit and see what happens. Nobody likes changeling anyway, it can't become worse. And if it does Kilkun can tweak the shit. If it proves to be completely stupid it can be reverted rapidly.
Another way to nerf it would be to make changeling kills less piss easy so they don't obtain the form without risk and effort, which would make everyone happy. And maybe, one day, all the useless stings could be made more useful or less expensive.
That or just remove the gamemode, vampires are way better anyway. :^)

**Comment by SarahJohnson489** [comment]
Give it insulation so it isn't shocked by shit and allow it to attack lights. It's retarded to have all these handicaps and you can't even get rid of the lights easily. I don't even think you have a decent rate to smash it with a shard or planks.

**Comment by IratePirate** [comment]
I would just merge it, what's the worst that could happen? Better to have something going around killing everybody than having the ling spend the round going into the morgue or taking monkeys until 3 hours later when everyone wonders what the hell is going on.

**Comment by clusterfack** [comment]
Shit duny.  Sperg out much? Did I trigger you?

**Comment by Duny-** [comment]
I'm sorry I'm able to use more than two sentences in an answer and actually use arguments, I know it's not the standard you're used to.

**Comment by clusterfack** [comment]
Yes because that was a rational 'argument' and not just pointless text vomit.

**Comment by Duny-** [comment]
Sorry disagreeing with you makes you so mad to the point of insulting me man.

**Comment by IratePirate** [comment]
Is this going to get merged soon?

**Pull request merged**
