### PR TITLE
Shit or get off the pot: Re-adds lings OR DIE TRYING

### PR DESCRIPTION
**Pull request by KingofHONK**
uhhhh just give them guns or something and stuff

:cl:
Re-adds lings into the rotation.

### CODE REVIEW

**Comment by KingofHONK** [comment]
oh god oh fuck

**Comment by ShiftyRail** [comment]
This PR re-adds ling to the rotation. It also ups its cost a bit and make additional lings ramp up the cost, much like additional vampires and traitors.

I made this branch because there seemed to be a desire to add changeling to the rotation again. I had no desire to defend it, so I just posted the link to someone that could want changeling back.

I'm neutral to that change. See also #23014 for info.

**Comment by soyconsumer** [comment]
Based, now remove vamp

**Comment by utilitas-** [comment]
how bout we remove vamp instead

**Comment by KingofHONK** [comment]
deal but only if you remove blob too

**Comment by ghost** [comment]
real jetpack hours

**Comment by SonixApache** [comment]
Aggressively shitposting in the thread with your link so brainlets do your dirty work for you instead of just manning up to make the PR yourself, pretty rad tactic tbh.

**Comment by ShiftyRail** [comment]
I'd rather have an actual debate on whether or not changeling needs to be brought back rather than inertia

I don't like shitty antags (and I think ling is a shitty antag) but I hate inertia a lot more ; people were complaining that ling was removed and didn't seem to go past their gitphobia to bring it back.

I'd have hoped people that wanted ling back would actually defend their choice.

**Comment by brndd** [comment]
Ling is thematically way cooler and fitting for spess than vamp. Vamp should have been the one to get shafted and ling should have cannibalized the good parts of it, not the other way around.

**Comment by SonixApache** [comment]
i still prefer getting glare->hypno'd or meme-scream'd over suddenly falling over dead when someone passes within 3 tiles of me

**Comment by agentofzog2** [comment]
*sps pings*
Ah shit. Man, them pinche lings are at it again
I wonder who they fucked up today?
*Screeching Tires*
You, motherfucka!
*you feel a tiny prick*
"got em"

**Comment by Allspice** [comment]
interesting how several people voted both for the "vamp no longer deals declone on suck" and this "re-add the dude that husks other dudes" thing.

Anyway yeah, the entire "deading people for sneaky upgrade points" mechanic is fundamentally shit so vamp and ling are both fundamentally shit. I wouldn't care too much if vamp is removed for ling or the other way around, but having both would be just terrible. And the best option for now would probably just be to replace both mods with nothing or an increase in the traitor proportion.

**Comment by ghost** [comment]
That is, in fact, correct.  Removing people from the round to get increasingly better at removing people from the round, in a game that punishes the removed by not allowing them to play for hours at a time, is horrible antag design.  Ling always represented one of the absolute worst aspects of vg, and I say that as someone who was very proficient at it and loved it.

**Comment by agentofzog2** [comment]
Keeping working antags removed would be fine if we had better variety  and a third of them didn't range from completely broken (malf, revs) to often fucked (wiz with orb).
Also ling is way better than "Man with esword and gun" which is somehow worth keeping(as long as nobody steals their esword, oh no that's super bad).

About threat, Lings should spawn in groups because that's what lets them do more interesting gimmicks beyond the silent succ.

**Comment by Allspice** [comment]
Malf and rev are both "working antags" insofar as their mechanics work, give or take. Whether they're trash is another question (and that was a point you conveniently neglected (because ling is trash)). And in my experience, the main ling gimmick when they worked together were to the tune of "let's all suck officers so we can depop" or "wait I don't have my objectives recall the shittle".

**Comment by brndd** [comment]
@SonixApache 

>i still prefer getting glare->hypno'd or meme-scream'd over suddenly falling over dead when someone passes within 3 tiles of me

I'm not talking about mechanics here, I'm talking about the theme of the antag. Changeling fits better in the setting and the general fantasy around it is cooler. In theory the suspense of "YOUR COWORKER COULD BE A MURDEROUS XENO DOPPELGANGER" is cool.

Yes, the mechanical execution turns it into a silent murderbone antag, but that has nothing to do with its *theme*. You can fix mechanics, but you can't for example fix the theme of vampire to make it better suited for a spess setting without making it not-vampire.

**Comment by BurntDevil** [comment]
i would rather be forced to play with souhei, whitaker and leonid for the rest of time than deal with lings. they arent fun. please forget they ever existed.

**Comment by agentofzog2** [comment]
> 
> 
> Malf and rev are both "working antags" insofar as their mechanics work, give or take. 

Rev doesn't have a lose state and Malf can be defeated by a shuttle call in addition to not being able to hack borgs.

>
>
>And in my experience, the main ling gimmick when they worked together were to the tune of "let's all suck officers so we can depop" or "wait I don't have my objectives recall the shittle".

The point is you had greater range for gimmicks unlike vamp who needs to succ multiple people to get friends or MAN WITH SWORD AND GUN.

**Comment by DDihanov** [comment]
So just nerf ling or make him acquire points some other way.

**Comment by SonixApache** [comment]
I'm not talking about the theme of the antag because the theme never matters in practice.
In practice, it's, as agentofzog so eloquently describes, "man with sword and invisible syringe gun"

I removed ling from rotation (with success, somehow) not because I thought the 'theme' of ling was bad, but that the execution was bad. If the theme had been bad, I'd have attempted to remove it from the code entirely.

Ling needs work before being re-added.

**Comment by brndd** [comment]
>Ling needs work before being re-added.

There I agree with you. What better way to spur people to work on it than force them to either fix it or suffer through shitty ling rounds?

**Comment by Exxion** [comment]
Well, that didn't work before

**Comment by agentofzog2** [comment]
> 

> In practice, it's, as agentofzog so eloquently describes, "man with sword and invisible syringe gun"
> 

Wait what do you mean by "invisible syringe gun"?
Oh
Oh christ.
What the fuck.

**Comment by utilitas-** [comment]
@brndd
suffering through it for six years sure as shit hasn't made anyone improve it

**Comment by DDihanov** [comment]
> @brndd
> suffering through it for six years sure as shit hasn't made anyone improve it

So give some suggestions then. Make a list of improvements and post it as an issue and we can get things rolling my dude.

**Comment by Allspice** [comment]
Like I said before, the fundamentals of ling are shit, so "uhhh just get things rolling my man" is tantamount to passing the buck to other people for designing a brand new antag. But if you specifically are willing to put in the work, here's where I'd start:
1. Remove the suck.
2. Maybe add the handcrab/legworm/eyespider from goonling, those seemed neat. Since there's no suck now, that might need to draft from ghosts like how apprentices used to
3. Fuck it, just like maybe give them lingTC I guess

**Comment by brndd** [comment]
I don't really know how current ling could be improved without a rework. The idea I keep throwing around is reworking it into a prop hunt antag. Absolutely no idea how that would work in practice, but "turn yourself into a captain's spare and wait in maintenance for an assistant to pick you up, then turn yourself into a gun and shoot them" sounds fucking hilarious.

**Comment by KingofHONK** [comment]
give them a 15 minute timer to get so many genes from the moment they get their first succ, buff horror form to be really good, and make it where the succs buff their horror form to be actually really good (vs old horror form thats a meme).

**Comment by SonixApache** [comment]
- every part of the ling is the entire ling
- every absorbed mind is also the ling

**Comment by ShiftyRail** [comment]
Having reflected on it, I don't believe this should be merged because ping-pong reverts is how you get waterpotass gas and I don't want that

**Comment by KingofHONK** [comment]
I...i dont feel so good mr shifty....

**Pull request closed without merging**
