### PR TITLE
Adds Three New Items to the Traitor Uplink for Cooperative Traitors

### PR DESCRIPTION
**Pull request by ghost**
hgfdhgfhg

The idea behind this is the provide some unique items and opportunities for groups of three traitors or more who want to pool all of their telecrystals in order to change the narrative of a round, as well as some more high risk/high reward opportunities for Nuke Ops who cooperate with traitors (I pity the loon who would use the mask and try to fly to the station).

:cl:
 * rscadd: Adds the changeling vial, stone mask, and the cult pamphlet to the traitor uplink for traitors that want to work together.

### CODE REVIEW

**Comment by Kromkar** [comment]
I think this would be a good way to encourage cooperation and give some more leeway to antagonist players influencing the round.

**Comment by kilozombie** [comment]
I don't think they should be available to nukies.

**Comment by PavelCIA** [comment]
Wait you can start cult as traitor now? Based

**Comment by ghost** [comment]
Good call on the Nukies, they will need to cooperate too and find a freelance traitor on the station as their price will be 100.
image

**Comment by SootyBear42** [comment]
From the price alone they won't happen regularly but they will be nice surprises.

**Comment by xeroxemnas** [comment]
Fuck it, why not. Better than boring traitorstended 24/7.

**Comment by dunsel-hordon** [comment]
This has to be one of the better pr's i have seen in a while. Finally its not just hur dur traitorstended

**Comment by gurfan** [comment]
based

**Comment by gurfan** [comment]
About the nukeops prices, when they find a traitor to work with wouldn't they just extract the TC from the ops uplink and use the traitors uplink so the cost is only 60? You might have to prevent extracting TC from the ops uplink or something

**Comment by ghost** [comment]
They would be only to buy one either way, if you think about it.  So cooperation is still accomplished in a roundabout way.  And at that point, if an entire nuclear strike team and multiple traitors are able successfully identify each other and organize without any of them using a single TC and are looking to put them all towards something, then that round sounds like it is already at their whim and is a minute from the credits rolling.

**Comment by drawsstuff** [comment]
Traitors buying cult is twisting my stomach in knots, but I tend to roll traitor security at alarmingly high frequencies so lets just wait and see what happens.

It's not like it will be the most popular item to buy or anything on account of it being a conversion antag.

What could possibly go wrong?

**Comment by ghost** [comment]
Yeah, if we get the point where this is a problem due to three or more agents consistently saving tc and organizing with each other in order to form group gimmicks and plans, I will be more proud of this server than anything and like to see the category further expanded.  I feel like the bar is set just high enough that this will be a special treat to see people working with this level of coordination and essentially doing a mass TC trade to better control the narrative of the round.

**Comment by BomberBro** [comment]
Like the first two, but it's really bizarre that the syndicate are turning people into cultists. Seems a bit short-sighted of the syndicate to try to end the world instead of just their corporate rival

**Comment by xeroxemnas** [comment]
> Like the first two, but it's really bizarre that the syndicate are turning people into cultists. Seems a bit short-sighted of the syndicate to try to end the world instead of just their corporate rival

It truly is the **_nuclear_** option, huh.

**Comment by juanototo2** [comment]
Reduce the cost of the vamp mask to 21, the ling vial to 30 and keep the cult pamphlet the way it is.

**Comment by APCUnlocked** [comment]
So cult can now completely bypass any enemy requirements provided there's 3 traitors on the station? Let's hope the oocly cult hate will keep us free from such a menace.

**Comment by TheFriggenSawbones** [comment]
good pr

**Comment by DamianX** [comment]
surreal

**Comment by SonixApache** [comment]
This has to be one of the worse pr's i have seen in a while. Finally its not just hur dur vampstended

not to mention giving people the ability to become lings when ling is *still* untouched

**Comment by xeroxemnas** [comment]
Sonix you do realize this requires traitors to actually work together right. That alone takes a fucking miracle in itself.

**Comment by SonixApache** [comment]
```
Enjoy the game!
Grey McShit [Common]: Gin fizz.
``` 
finding and collaborating with other traitors is stupidly simple

**Comment by Kurfursten** [comment]
Personally I think this idea is narratively pretty bad and mechanically even worse, but it's also one of those things that I expect to never actually happen in practice, or maybe once every couple months

**Comment by calzilla1** [comment]
Wish it was actually unique, interesting items, not just "you get to be different antag". But if we're going with that, maybe add discount ops, where all they get is the nuke code and that's it.

**Comment by ShiftyRail** [comment]
Yeah, someone on the d*scord suggested to add "discount operatives" on the list and add a codebreaker (plus maybe a few other items to help the new cops). I think this would be much more interesting than just changing the gamemode.

**Comment by ghost** [comment]
I am all for the codebreaker, but I figured it would be wiser to be light-handed and just start with a few antag types so that the category could be added and then be expanded on with additional PRs.  I will throw up the codebreaker PR less than an hour after this gets merged but figured a round-ending item would be best suited for its own PR

**Comment by ShiftyRail** [comment]
Fine by me.

**Pull request merged**
