### PR TITLE
Head revs get a loyalty implant pinpointer

### PR DESCRIPTION
**Pull request by DamianX**
## Why
Heads hiding in closets is annoying for everyone.
## Concerns
Heads that lose their implant, for instance through cloning, will be immune to this. The obvious solution is to remove cloning.
Unlike a flash, it's a dead giveaway that one is undoubtedly a revolutionary, so it's one more thing to stash if getting caught is part of the plan.
Here is a picture of bane: 
image

:cl:
 * rscadd: Head revolutionaries now get a pinpointer that tracks the closest living creature with a loyalty implant.

### CODE REVIEW

**Comment by jknpj** [comment]
Why would i take a pintpointer?

**Comment by Kurfursten** [comment]
I think this is a good solution because if the crew is winning they will implant everyone (meaning the pointer becomes useless) and it becomes more accurate the fewer implanted crew are left

**Comment by calzilla1** [comment]
> The obvious solution is to remove cloning.
Are you trying to crash your PR with no survivors?
Meme's aside how does this work? Will it just point to the closest implanted guy? What if you're at an equal distance from both implantees?

**Comment by Kurfursten** [comment]
>will it just point to the closest implanted guy?

yes

>what if you're at an equal distance?

the earlier person by index in the list `living_mob_list` would be selected, which will tend to be someone who hasn't died at all and was present and readied up at roundstart (however, several random events will shuffle this list, at which point, all bets are off)

**Pull request merged**
