### PR TITLE
Weeb to Ninja

### PR DESCRIPTION
**Pull request by Kurfursten**
YOU ASKED FOR IT
YOU GOT IT

Functionally little has changed here, but this includes some logic improvements to Dakimakura (now Hologram Projector) shadowstepping. Now it won't try to step to a wall, and will prefer further steps. It also can't be pulled except by a ninja -- but you can still destroy it with a drill or polyacid.

Most of the weeb text on the katana hasn't been changed because I imagine the true Space Ninja rework will replace the katana with an esword of some kind. The space weeb versions still exist, and the spawn proc for it still exists. Wiki has been updated.

Stealth posters now display a random wall hanging (apc, extinguisher, oxygen closet, etc.) instead of anime posters.

🆑 
* tweak: The Crazed Weeaboo has been replaced with a Space Ninja. This is fluff only.
* tweak: The hologram projector/dakimakura now has better shadowstep logic.
* tweak: You can no longer pull a hologram/daki (but you can still destroy it!)

### CODE REVIEW

**Comment by Irradiation** [comment]
Weeb might have been a meme, but I still liked the roleplay/meme content we had for it as opposed to sticking to the past of muh Space Ninjas. This is now a post warning that Space Ninjas will act like regular traitors and roleplay even less than Weebs.

(Community poll/vote already passed, so this is just me being bitchy/leaving feedback on the whole thing after it happened).

**Comment by DrSnips** [comment]
I feel like the hologram (projectors) should be able to be pulled at the minimum. Not being able to pick them up is fine still.

**Comment by Hoshi-chan** [comment]
Do they get the airlock-slicing beam katana back?

**Comment by Hoshi-chan** [comment]
Space Weeb probably shouldn't become Ninja unless it's a more complete rework that brings back the unique aspects of Ninja, like the airlock-slicing beam katana, suit powers, and suit AI. Weeb has more flavor in its current state than a half-baked version of Space Ninja would.

Also, there's no reason the two antags have to be mutually exclusive. When Ninja is done, Weeb could just become a lower threat cost alternative that could roll occasionally; it also makes a little more sense for the two to be similar if weebs are wannabe space ninjas.

**Comment by Kurfursten** [comment]
Server already voted

**Comment by ghost** [comment]
Hopefully this will lead to less friendly antags.

**Comment by Intigracy** [comment]
Lame.

There's nothing wrong with friendly antags in a game that now features many types per round. It was more of an issue when it was the only one in the round and they didn't do anything to spice it up. I personally would make a ninja faction that weebs and ninjas belong to and leave it at that.

The poll also had no both option, it was mutually exclusive.

Just my opinion though.

**Comment by bathosbathtime** [comment]
Link to relevant poll:
http://ss13.moe/index.php/poll/179

Personally I would also like having them be two different things, but that could always be done later.

**Comment by SonixApache** [comment]
refluff to ninja, keep zero-effort weeaboo as weeaboo?

Wouldn't changing the prefs make database gas anyway?

**Comment by Kurfursten** [comment]
Nah we can remove and add prefs to the antag list as we like without worrying about database stuff.

But the results of the poll were very clear on this point, twice as many people wanted a serious ninja. Personally I have no strong preference but the server clearly does.

**Comment by SonixApache** [comment]
Yeah, you take the current weeaboo and re-fluff him as a serious ninja.
And then toss back in the old silly "literally just a guy with a sword glued to his hand" weeaboo.

**Comment by DeityLink** [comment]
Why can't we just have ninjas that talk like weebs?

**Pull request merged**
