### PR TITLE
Hydroponics Mutations Rework

### LINKED ISSUE #28624: Feature Request: A way to remove specific chems from a plant's phytochemistry via either a tool or xenobotany machine.
I play botany a lot, and it's always a kick in the nuts to see a great plant that I can't effectively mass use because it has a chem that doesn't help, like the solanine (toxin) in ambrosia vulgaris or the cyticine (synaptizine) in ambrosia deus, both of which make blunts pointless, since smoking a normal blunt makes you somewhat poisoned while a godblunt can kill you (1u cyticine equals about 60 toxdamage and since a godblunt, regardless of potency, has more than 1u, smoking a godblunt is a death sentence.)

Other times, when making materials-fruit (like glowberries for uranium) the presence of nutriment is a problem, since it always outnumbers the material, making any grinding woefully slow since you have to remove the nutriment every time to keep going.
Many times you find the ideal exotic seed, only to find out it not only makes the chems you wanted but also 3 different poisons.

You can ADD chems to a plant via splicing, but there's no way to remove specific chems from it.
Please add a way to remove specific chems from a plant's phytochemistry.
[featurerequest] [qol]

### PR DESCRIPTION
**Pull request by adacovsk**
[system]

The mutations code for hydroponics is awful to read and hopefully this brings about more possibilities. After talking with a couple veteran botanists, I noticed that they used splicing/purging to accomplish most of what they wanted to achieve, avoiding mutations, mainly because of the low odds of getting a mutation that they wanted.

I remade the PR because I messed up the commits, previously #32730

## What this does
- Refactor and redo the whole mutation system
- Rather than mutagen and radium causing all mutations, I broke it up such that:
   - Mutagen affects phytochemistry genes, put teleporting into xenophysiology
   - Radium affects morphology genes
   - Uranium affects bioluminescence genes
   - Bicardines affects ecology genes
   - Kelotanes affects ecophysiology genes
   - Hyperzines affects metabolism genes. Metabolism now contains `fluid_consumption`, `nutrient_consumption`, `voracious`, `hematophage`
   - Creatine affects development genes
   - Dexalins (Thymol) affects xenophysiology. It now contains: `teleporting` `alter_temp` `noreact` `exude_gasses` `consume_gasses`

- Removes `custom_plant_metabolism`, `severity`, `yield_mod` and `mutation_mod`: these made barely any impact when used, and were rarely used, and convoluted.
- Rebalanced some toxins in on_plant_life() for some chems
- `parasite` combined with `carnivorous` now known has `voracious` to reduce the number of traits... Level 1 voracious results in the plant eating both weeds and pests. Level 2 `voracious` is HCARN, but relabelled VORA and CARN respectively
- Left4Zed actually does something now (<1% chance to proc any mutation each tick currently)
- Metabolism no longer exude/consume gases
- Morphology mutations can affect appearance
- Modifies creatine recipe so untable mutagen can count as a reagent in recipe so botanists can produce it.
 - Creatine can now be made with Poppies, Ambrosia, glowshrooms, regular and death nettles
- Somotray can apply any type of gene mutation
- fixes a broken hematophage
 ## Why it's good
- This should allow botanists more possibilities with their plants, and hopefully more possibilities for coders in the future as a big limiting factor was usability of the old code
- Mutating phytochemistry has a chance to remove a chemical. Closes #28624. While it is a roundabout way to eliminate chemicals, I don't see an easier way to do it until I modify seed machines (which I'm not doing for this PR).
- Since `no_react` and `auto_harvest = 2` are unique to xeno plants, they are not included in mutations

## Changelog

:cl:
 * tweak: Reworked hydroponics mutations, see PR #32853 or the wiki

### CODE REVIEW

**Comment by adacovsk** [comment]
@Eneocho for some reason the test server isn't updating with the new commits, no idea why, but I've added your changes

**Comment by Eneocho** [comment]
>mutations on chance is how it works currently

As it is currently, every single dose of mutagen/radium causes a mutation (not the same mutation kind each time mind you, but each mutagen/radium dose gives that "plant droops slighly" notification).
Currently, it is better to dose 1u at a time, wait for it to be consumed then dose again for species changing, is this not the case anymore with this change? The plants tend to not react to mutagenics on their tray until the tray empties, which is why microdosing is preferred. 

>This is all flat out wrong... It does provide feedback when it transforms into another species, I didn't even touch that proc. It's just because you're trying to use 1u
>Just be aware that you can dump a whole bottle into a tray, and it'll slowly process it using 1u at a time

I explained wrong. You DO get that feedback on species change, but no indication that the plant consumed the mutagen/radium, so you just pour shit onto the plant, it mutates into its new species then, because you had dumped mutagenics onto the tray, it mutates again after the species change, which is not always desirable (for example, you want the banana-spliced tomatoes to look like tomatoes but the radium procs and changes the icon group to potatoes).

>but I've added your changes

Appreciated. Apologies if I got antsy, I want this to work too.

**Comment by adacovsk** [comment]
> > mutations on chance is how it works currently
> 
> As it is currently, every single dose of mutagen/radium causes a mutation (not the same mutation kind each time mind you, but each mutagen/radium dose gives that "plant droops slighly" notification). Currently, it is better to dose 1u at a time, wait for it to be consumed then dose again for species changing, is this not the case anymore with this change? The plants tend to not react to mutagenics on their tray until the tray empties, which is why microdosing is preferred.

I don't understand this "until the tray empties" mechanic, so I've done it so that you can dump in any amount and it should just work, that way you don't have to micromanage it, unless you're looking for something specific. The "droops idly" was from stunted growth... Right now I've set it up so that you only get stunted growth if there's 0 nutrition.

**Comment by Eneocho** [comment]
I just want the plant to do their emote (droops idly, shakes slightly, etc) when getting dosed so I can know if the mutagen/radium/whatever got consumed, since that's the current main use for those emotes (instead of indications of growth).

**Comment by Kurfursten** [comment]
Seems quite powerful, but I think it's fine as long as it doesn't let you manually mutate to get the special traits that you are supposed to splice from xenoplants, like selfharvest or the noreact fruits.

**Comment by adacovsk** [comment]
> Seems quite powerful, but I think it's fine as long as it doesn't let you manually mutate to get the special traits that you are supposed to splice from xenoplants, like selfharvest or the noreact fruits.

that's a good point, I currently have noreact locked behind thymol, which is a xenoplant chemical. Autoharvest was always available through mutations, but since mutations were so dysfunctional, you'd probably never get it. With my PR, you need to make creatine to get to autoharvest, which has increased difficulty

**Comment by Kurfursten** [comment]
I definitely don't like that you've completely rendered Gelthi completely pointless -- easily replaced with a chem dispenser. Yes, creatine is slightly more annoying to make than bicaridine which is a casual 3 clicks, but don't compare that to departmental interaction. Those effects were specifically added - by me no less - to make plant finds meaningful. Increased importance for Thymol is cool though.

**Comment by adacovsk** [comment]
> plant finds meaningful

Perhaps sports drink from vale would be more appropriate and move autoharvest to that

**Comment by Eneocho** [comment]
A simple solution would be to just keep xenoarch traits (self harvest, noreact, etc) locked to gene editing and not mutation, which would solve both the benoarch genes being too easy to get and the issue with xenophysiology needing a fuckrare chem to do mutations unlike all other plant genegroups.

**Comment by adacovsk** [comment]
> A simple solution would be to just keep xenoarch traits (self harvest, noreact, etc) locked to gene editing and not mutation, which would solve both the benoarch genes being too easy to get and the issue with xenophysiology needing a fuckrare chem to do mutations unlike all other plant genegroups.

good idea

**Comment by Kurfursten** [comment]
Okay, that sounds good to me. I've retracted my vote.

**Comment by Kurfursten** [comment]
It's very weird how little feedback this has, because this is one of the biggest changes to hydroponics in a long time. It's really big. You will definitely need to update the wiki.

**Comment by adacovsk** [comment]
> It's very weird how little feedback this has, because this is one of the biggest changes to hydroponics in a long time. It's really big. You will definitely need to update the wiki.

yes, I will update the wiki. Also, I remade the PR a couple times, so that's part of the reason why. I would have 2 upvotes. I think it's generally because not many people care about mutations and don't use them (which is why I made the PR)

**Comment by Eneocho** [comment]
If you give me detailed descriptions of everything I can update the wiki for you, though if you want you can still do it yourself.

**Comment by adacovsk** [comment]
> If you give me detailed descriptions of everything I can update the wiki for you, though if you want you can still do it yourself.

I'd appreciate it. I'll be more thorough with the PR. 


The Generally accepted roundstart method and any references to nutrition are obsolete. Instead, perhaps consider replacing with this:
```
- Plant grass and dump 2 bottles of robust harvest for 100+ potency gene, watch out for weeds/pests as robust harvest makes them rise quickly and you can lose the plant.
- Hack your seed vendor to get glowshrooms, they contain radium.
- Take a grass seed packet and SPLICE Chanterelle mushroom DEVELOPMENT gene onto it at least 5 times. Take out this modified gene packet and extract the DEVELOPMENT and METABOLISM genes from into onto disks. Take a glowshroom packet and extract the ECOPHYSIOLOGY gene onto a disk. You will be PURGEing these 3 disks onto every seed you plant from now on for easy mode farming.
- You should also extract ECOLOGY and METABOLISM from the grass packet if you're interested in taming exotic seeds - nutrition will stop specialized hematophages, and ECOLOGY will make them tolerate ship conditions.
- Modify a glowshroom seed with the above 3 disks and plant it.
- SLICE PHYTOCHEMISTRY into poppies, ambrosia, glowshrooms, nettles to unlock most mutations by grinding them to extract their chemicals.
- To get death nettles and glowberries, you can use the opium, tannic acid, radium from those plants to mutate the species.
- You can then use the nettles with the poppies, ambrosia, and glowshrooms to make untable mutagen and creatine
- Thymol from the Vale plant or dexalin can be used to unlock the last remaining mutations that are not exclusive to xenoarcheology.
- The mutation chemicals will be consumed over time when dumped into the tray, so wait patiently. Warning: do not leave plants affected by creatine or dexalins unattended.
- Hyperzine can make kudzu vines especially dangerous, be careful.
- If science is doing their jobs, grab a somatoray to avoid dealing with the chemicals
```

**Comment by Eneocho** [comment]
Noted. The first 4 steps (the most important stuff, everything else is dedicated autism) are the same so no big gameplay changes on that part, and regular ambrosia already has opium, so no need for poppies.
Could I get more detailed explanation on specifics on the rework? As in, value changes, potential tips and tricks, etc? The more detailed OP helps and I have a rework of the xenobotany wiki page started, but every bit helps.
A few questions, by the way:
* Does any (plant) mutagenic cause species change or only the 4 mentioned on your roundstart guide?
* Noreact was recently added as a rare strange seeds gene, is it still available there or did you gate it exclusively behind xenobotany?
* How does the morphology splices work spritewise? Do you get a banana that looks like a tomato but still behaves like a banana (even in recipes)? Or do you get both banana-looking bananas and tomato-looking tomatoes on the plant? The former is funny, but the latter is consistent. (Or you could just say fuck it and mix the sprites so you get banana looking bananas, banana looking tomatoes, tomato looking bananas and tomato looking tomatoes on the same harvest.)
* Is microdosing still the preferred method for species change mutating? Or do you just pour a dozen units of opium and pray for a species change?
* Is microdosing still viable? I like doing the 1u shuffle for mutations, can you still reliably do it with this new system?
* You currently get a message every time the plant mutates (for good or bad), and this message only procs when the plant runs out of chems on the tray. Is this implemented in some way, as in, a "the plant shudders" message every time the plant mutates, so you know when to check again?
* Would you consider adding a dedicated non-random method of removing chems from a plant, like an advanced buildable xenobotany machine that lets you remove specific chems from a splice? Because while the phytochemistry method is appreciated, you don't really know if the chems were removed or not until you harvest, and then it might be the wrong chem removed (also the fact that you sometimes wanna top off your 99potency plant to a comfy 100 and could accidentally remove the desired chemical).
* As it is currently on the PR, L4Z seems very underwhelming (which ironically fits with current L4Z). You could change L4Z to either proc all mutation types simultaneously or to proc them all at random like mutagen does currently, so we either get the DANGER CHAOSMODE experience or the current mutagenic system in a "legacy" way (so you could just dump and forget for random mutations/sabotage or go specific with dedicated mutagens for hihg intensity botany). Having both effects as independent chems would be great. A chem that goes fuck you and mutates all groups (perhaps sans xenophy) at the same time and one for the "legacy" mutation system for those too used/too obstinate to try the new one.

I know I asked a few of these already and you answered before, but you did change stuff in the meantime, so I'd appreciate some confirmation.

**Comment by adacovsk** [comment]
Somatoray is extremely useful for changing mutations. Ideally, nothing should change regarding the "hydroponics meta", but one difference that I think you've noted in the past is that you've used robust harvest to increase the yield to close to 200 after splicing, this is still the case, but you won't suffer any negative impacts from it.
Answers:
* While I've kept all the caps the same, the functions are different and there's rounding, the hard caps realistically might've changed. If you see any issues with the hardcaps when mutating, let me know and I can change the code. I'm using logarithms instead of a hard and soft linear function for diminishing returns.
* Any "plant mutagenic" chemical can cause changes. This is both the chemistry and botany chemicals.
* I didn't touch anything with no_react, other than moving it to xenophysiology. It should still be available there, but that might be good to remove from cargo? In any case, that would be another PR.
* I haven't touched the morphology slicing. As for the mutations, it's completely randomized. I haven't touched the seed machines other than reorganizing some traits. Any changes to them will have to go in another PR.
* For development, xenophysiology, and metabolism, and phytochemistry it would be useful to "microdose" then check to see if you have the mutation you wanted. Since the other genes just increase stats, you can just dump a whole beaker. You have options.
* You get feedback on every mutation. Some are more specific than others, but I think it covers the important ones. This hasn't changed. The only reason you were getting that before was because you were using 1u instead of the 5u. I've since lowered it to 1u for a mutation.
* I haven't touched the botany machines other than reorganizing some traits, that would be in another PR if I get to it. You can potentially remove chemicals from specific plants through mutations, but you have to pay close attention to the changes and have many plants available to do it. I imagine it might be pretty infeasible to do.
* With L4Z, you can just dump and forget for random mutations/sabotage. It has some benefits where you don't need to make creatine, or have thymol to get certain traits, but they are much harder to get those traits. I am not 100% it's balanced yet, I can always increase the proc rate. More feedback would be great on it so I can make a balance PR, especially L4Z. I don't expect everything to be perfect.
* Recreating the old system for one novelty chemical would not be easy

Not sure if it's worth mentioning, but instead of "xenobotany" it's more appropriately called "teratology" irl

**Comment by Eneocho** [comment]
>I didn't touch anything with no_react, other than moving it to xenophysiology. It should still be available there, but that might be good to remove from cargo? In any case, that would be another PR.

On the contrary, it's good that it's available via cargo, it's really hard to find but gives you a chance when there's no benoarch. And you don't get the smoke chem either so no smokesplices.
>Recreating the old system for one novelty chemical would not be easy

I meant it more like having L4Z on all the mutagen groups simultaneously with a randomizer condition so you can dump it and get the "old system experience" while still having the updated code. 
```
If chem 1 or l4z
      if l4z and prob 10
            mutate thing
     else
            mutate thing
```
Kinda like that 

>Not sure if it's worth mentioning, but instead of "xenobotany" it's more appropriately called "teratology" irl

The ingame and most commonly accepted term in the server is xenobotany, so that's the term I'll use.

**Comment by Kurfursten** [comment]
I have a very particular set of permissions
If you update the wiki now, that'll be the end of it
But if you don't, I will find you, and I will not merge you

**Comment by Eneocho** [comment]
I'll be updating the wiki. Small changes here and there for quick consistency with the current system. I'll make a more structured and readable version as well, but that'll take time.

**Comment by Eneocho** [comment]
Xenobotany page was updated with the quick and dirty changes. I'll be making the pretty and updated page now.

**Comment by Eneocho** [comment]
Updated the Guide to Hydroponics' GMO and xenobotany section as well.

**Comment by Eneocho** [comment]
Remade the xenobotany page @Kurfursten, @adacovsk

**Comment by DeityLink** [comment]
@Kurfursten so that was an undocumented change it seems. Altering bee stingers so they could deal more damage or no damage has been completely removed with this PR.
image

**Comment by DeityLink** [comment]
Killette came discussing bees on Discord and when looking things up I ran across that.

It's terrible because further down they kept the yield increase effect in afterattack, but simultaneously left the bullet_act of apiaries to always trigger a swarm.

I'd like to know if this was an oversight by @adacovsk or an intended change first.

**Comment by Kurfursten** [comment]
I am out while recovering from surgery, please ask Adacovsk about whether this was just an oversight

**Comment by DeityLink** [comment]
Oh, recover well then.

@adacovsk

**Comment by Eneocho** [comment]
> I am out while recovering from surgery, please ask Adacovsk about whether this was just an oversight

Get well soon, man.

**Comment by DeityLink** [comment]
Actually it's way worse than I thought, since you removed the projectile and use afterattack which is applied immediately to the clicked atom, there's no sanity whatsoever as to whether the atom is actually reachable, or even anywhere near you!

For starters my soulstone particles were designed to be used from a static source to something that can move, not the other way around, or you can get shit like this:

image

Second much more problematic case study, since you just need to click the atom to apply the beam, you can fire at people through walls with xray

image

And last and much worse than anything else, it works through cameras.

image

**and this PR grants emagged floral somatoray the ability to mutate and deal burn damage to non-dionas humans at will. (on top of perma-stunning dionas)**

How was all of this allowed through?

**Comment by DeityLink** [comment]
You can give people any random mutation through cameras with a chance of burn damage on top every second 
image

Anyway I thought I'd make it known. You guys have fun.

**Comment by Eneocho** [comment]
Based.

**Comment by adacovsk** [comment]
Woah that's interesting. Sorry for messing with bees, there was a lot of shit code in there. It was an oversight if bee stingers don't work. My understanding that yieldmod was specific to plants and not bees. Emagged somatoray probably needs a nerf @DeityLink

**Comment by DeityLink** [comment]
The problem is that you removed that bit of code and forgot to plug it back wherever else it needed to go. 
image

That and adding a sanity check to the Floral Somatoray if you were not gonna have it operate like a gun anymore.

**Pull request merged**
