### PR TITLE
Fixes #6564

### LINKED ISSUE #6564: Sprite bug
(WEB REPORT BY: clugehead REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
Sprite bug

>General description of the issue
Throwing things as xeno glitches your sprite to still have the item

>What you expected to happen
I expected to throw the toolbox

>What actually happened
I threw it but the toolbox sprite is in my hand

>Steps to reproduce if possible
Throw a toolbox as a xeno. It was blood-stained

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #6564

### CODE REVIEW

**Comment by clusterfack** [comment]
I dont think you went through the proper procedure on this one, did you reproduce the bug first? This file hasn't been modified in months so no change here caused the issue.

**Comment by DeityLink** [comment]
>did you reproduce the bug first?

Yes

I tested it with my change. It fixed it.

**Comment by clusterfack** [comment]
Still didn't really find out why this is happening when it hasn't happened before

**Comment by DeityLink** [comment]
Aliens don't often pick up items though (or they pick items like face huggers that don't have an in-hand sprite)

**Comment by clusterfack** [comment]
So you're telling me it has ALWAYS happened and that booting up an old as shit commit would have the same bug?

**Comment by DeityLink** [comment]
Wouldn't surprise me. We've got quite a few bugs that have been lingering for years because no one reported them (such as plants in hydroponic trays' sprites not changing as they grow up, until I fixed that one)

Out of curiosity, how can I test the oldest commit available?

**Comment by clusterfack** [comment]
I normally just go to around last year, 200 pages back in the commit logs
https://github.com/d3athrow/vgstation13/commits/Bleeding-Edge?page=200

You only have to fix one error where byond made throw a keyword by commenting it out of the code to use it

**Comment by DeityLink** [comment]
No need to throw, just dropping the item will proc the bug.

**Comment by clusterfack** [comment]
No I'm saying if you checkout that code, byond will error in 2 places of the code where the name throw is used

**Comment by Probe1** [comment]
I observed it first hand as it happened.

battle_observatory_18_2015-11-12_05-11-39

**Pull request merged**
