### PR TITLE
Randomizes all door wires.

### PR DESCRIPTION
**Pull request by brndd**
Press 👍 to dab on greyshirts and powergamers.

:cl:
 * tweak: Test light is green... or was it red? Blue!?

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
greyshirt here

**Comment by Irradiation** [comment]
Press downboat to dab on c*ders.

**Comment by ShiftyRail** [comment]
It's a bad idea for many practical purposes and will do a lot more harm than good.

**Comment by brndd** [comment]
On the other hand it's a good idea for the purposes of three readily available tools not being equivalent to an all-access ID.

**Comment by Kharkov72** [comment]
Not a good way to go about it, making every door a wire guessing minigame will just get annoying and old quickly. 
Really, the answer is to have SOME doors be randomized, all the others be standard along with newly-made doors being random to be played off as doors being replaced on the station.

**Comment by brndd** [comment]
>making every door a wire guessing minigame will just get annoying and old quickly.

That is quite literally the point of the hacking minigame. The wires being static is one of those things that is only acceptable because it's "always"(?) been this way. If the hacking feature was added today, all of you would be quick to point out the fundamental problem with the wires being static (which really doesn't need explaining, but: it makes ID requirements borderline pointless).

TG has had this feature enabled on all airlocks for many years and it works very well there for the purposes of reducing powergay.

**Comment by robosperg** [comment]
find a way to make this not fuck over engineers

**Comment by brndd** [comment]
>find a way to make this not fuck over engineers

glubs

The CE also has the station blueprints which show you which wire does what.

**Comment by MadmanMartian** [comment]
Assistants are more likely to have gloves than engineers, considering assistants can get them from youtools, cargo, and engineering, whereas engineers are usually limited to just engineering

**Comment by brndd** [comment]
By my count engineers on Box have 4 pairs in roundstart closets, a pair in CE closet, the ones in the YouTool (requires a coin), plus a pair nearby in Technical Storage which they can surely get before any assistant if they want to. Mechanics also have 2 pairs. Not to mention the fact that nobody in cargo will bat an eye when the engineering department orders extra electrical supplies crates.

>assistants can get them from [...] engineering

A problem this PR would make substantially less common. In case you were not aware, assistants do not in fact have engineering access and have to hack or B&E their way in, then emitter (or otherwise force open) the ID locked electrical supplies closets the gloves are actually in.

**Comment by SonixApache** [comment]
- keep wire colors the same
- change their positions per door

**Comment by Durgen** [comment]
>The assistant metaclub will remember this.

**Comment by ghost** [comment]
Just rework the wire minigame entirely. Test wires make no sense.

**Comment by Lokiamis** [comment]
I think it would be fun to have a random event that randomizes wires.

**Comment by Chazach** [comment]
I dont get the idea
This doesnt hurt powergamers, this just kills people who try not to powergame by finding the door wires using signallers or in the ghetto bar or something and promotes for everyone the race to acquire glubbs.

**Comment by brndd** [comment]
Finding door wires with signalers or in the ghetto bar won't do you any good when every door has different wires.

**Comment by Chazach** [comment]
thats the point
different approaches that arent "lmao rush glubbs and fuck every single wire on the door" are all snubbed in favour of "lmao rush glubbs and fuck every single wire on the door", which encourages the amount of powergay going around. the people affected most directly (apart from everyone because this is really inconvenient for all involved) arent the greyshits or powergamers, its the middle class who dont want to be the greyshits or powergamers.

**Comment by FudgePucker** [comment]
Yeah I have to say this sucks thirty dicks. Would be really inconvenient for projects involving airlocks if you have to find the door open wire and bolt wire every time. If you wanted to make a checkpoint in a hallway that's three doors each side, Six, SIX airlocks you have to find the wires for, and finding the wires for every individual door would take even longer than finding the wires normally just for one. Hit the test light? Guess you are just going to have to wait, VS just checking the wires in the bathroom, where if you find the test light, you can just swap your test air lock.

Not only that but it would make hacking to break in harder to fix. Right now all it is, alt click on your PDA to pull out pin, click pin on airlock to close it, screwdriver the cover closed. With this change I hope you powergamed for glubbs, because that power gaming dick fuck hit the shock wire going down the wire list looking for the test light, now you need to hack your own door for all the wires so that it stops door crushing and shocking people.

Also hurts sabotage, basically the issue above only in reverse. My favorite traitor gimmick is to cut the bolts, cut the lights, and cut the shock light. This is a somewhat quick process once you find the wires, can be done in medium traffic areas, would take way too fucking long after these changes.

I would be in support of randomized high security doors being randomized (bridge, head offices, armory, telecommuications). Begrudgingly accept low priority doors being the same (general maintanace, general access airlocks).

But fuck this shit. Would hurt normal player base more than "power gamers"

**Comment by Kammerjunk** [comment]
hmm yes I miss the days of Isaac the mechanic cutting every single wire from the top until he hits power so he can get into chemistry

**Comment by Caboozles** [comment]
Couldn’t you just randomize high security doors like Sec or the Armory if you want to prevent the worst of it?
Or do the random event?

I mean, this will make every door bzzt hell, and require engineers fix every fucking door without a clue what the wires are for said door.

**Comment by SonixApache** [comment]
Randomizing sec doors was actually a thing on one of the maps for a while, deff I think.
It was removed because it was infuriating *for sec and engineers trying to unfuck the doors* and them alone.

**Comment by brndd** [comment]
Sec doors on Defficiency are still randomized.

Also I think you're being more than a bit disingenuous if you claim that only people fixing the doors are inconvenienced by this, and not the people who now take on average 10 to 60 seconds to break into shit rather than 2 seconds. Because that's more inconvenient on pretty much any objective meter.

**Comment by tuypo1** [comment]
Or we could be better as players by encouraging security to arrest people who call out the wires on public coms

**Comment by Kharkov72** [comment]
is it controversial if everyone thinks it's a terrible idea 🤔

**Comment by Kammerjunk** [comment]
also 👎 to the follow-up PR that "just expands the secdoor randomization to all maps and also randomizes vault doors"

**Comment by mtpowell** [comment]
This is a terrible idea!11
Why?

    Because!
dur

Pros:
Limits power gaymers
Muh realism
Reduces greyshittery

Cons:
Limits power gaymers
???

**Comment by Lokiamis** [comment]
unironically using !11 and a brainlet image on github

**Comment by mtpowell** [comment]
There's no counter argument in this retarded thread other then it's that way because it is.

**Comment by ShiftyRail** [comment]
>limits powergaymers

If you read more than the first 3 replies, you'd see that it only harms, people who DON'T powergame and need to hack a door on-the-go (plenty of situations call for it ; getting the guns when there's a killer and you don't have access to the armoury, getting away from a malf AI...) . People who do powergame will just use their gloves to pulse all wires from the top on each door.

>Muh realism

I've worked in engineering and I can assure you that it's much more likely than wires colours would be standardised.

>Reduces greyshittery

False, see "limits powergaymers". It reduces greyshittery of greyshirts who don't take gloves. Solving a problem that doesn't really exists.

**Comment by Lokiamis** [comment]
>you'd see that it only harms, people who DON'T powergame and need to hack a door on-the-go.

No, it would definitely reduce hacking to some degree. It would take a few extra seconds to hack a door, which can be the difference between me risking it or not. You'd also be semi-required to have insulated gloves all of the time if you wanted to hack.

**Comment by bathosbathtime** [comment]
>Reduces greyshittery
>
I do have to agree with this, as it will take them more time per airlock.
It will also mean they'll pulse/cut every damn wire on the airlock from the top down, making dealing with hacked airlocks a headache more often than not.
You'd need gloves all the time not only to hack, but to _use any airlock that would get hacked_

**Comment by brndd** [comment]
Dealing with hacked airlocks is a much smaller headache than dealing with all-access greyshirts.

**Comment by Kurfursten** [comment]
It is hard to imagine this gaining the support it needs, but it will get its full 7 days.

**Comment by Kharkov72** [comment]
>Muh realism
>It isn't realistic that doors would have universal wires for easy repairs

🤔

**Comment by brndd** [comment]
@ShiftyRail 

>you'd see that it only harms, people who DON'T powergame and need to hack a door on-the-go (plenty of situations call for it ; getting the guns when there's a killer and you don't have access to the armoury, getting away from a malf AI...) .

These people are reasonably unlikely to know what the test light wire is, so this change would make no great difference for them. If you need to hack a single door in such an emergency situation and it's the first door you're hacking that round, it makes no difference if each door has random wires or not.

>False, see "limits powergaymers". It reduces greyshittery of greyshirts who don't take gloves. Solving a problem that doesn't really exists.

You don't just "take gloves" as an assistant. There's a limited amount of roundstart locations for them, and even fewer that you actually have access to. Therefore the argument "this does not stop greyshirts because they have glubbs" is fallacious, because they by and large do not have glubbs. Most of them just figure out the magic wire at roundstart and then use that knowledge to open every door they want to in 2 seconds with no risk, no gloves needed.

>Muh realism

This is very obviously a gameplay issue for both sides of the argument.

**Comment by bathosbathtime** [comment]
>Dealing with hacked airlocks is a much smaller headache than dealing with all-access greyshirts.
>
I think you're underselling the headache of dealing with bolted, shocked, disabled safeties, timing errors, and the like combined with upselling just how many assistants this will stop.
>You don't just "take gloves" as an assistant. There's a limited amount of roundstart locations for them, and even fewer that you actually have access to. Therefore the argument "this does not stop greyshirts because they have glubbs" is fallacious, because they by and large do not have glubbs. Most of them just figure out the magic wire at roundstart and then use that knowledge to open every door they want to in 2 seconds with no risk, no gloves needed.
>
The electrical crate is cheap, infinite, and requires no access once you get it from cargo.  Two gloves per crate not including rare electrical toolbox RNG.

**Comment by SonixApache** [comment]
\>Therefore the argument "this does not stop greyshirts because they have glubbs" is fallacious, because they by and large do not have glubbs. 
Are we playing the same game?

**Comment by Blithering** [comment]
Someone post the picture of the malf AI that filled its core with bolted doors.

**Comment by Caboozles** [comment]
Man. If only you knew how easy it was to just order glubbs. There’s no RP downside, cost is nothing, and nobody gives a shit. A lot of times cargo will do it for you and just leave a rack of glubbs out.

This proposed change makes fixing doors harder rather than hacking doors harder. Unless you give engineers some magical way of knowing all door wires this is going to create more issues than it solves. 

If you want a change that won’t be ass to fix (though whether it’ll help any is debatable), make it so hacking a door open isn’t instant and requires some time. Say, seven seconds to pop a door open.

**Comment by FudgePucker** [comment]
Oh yeah, super buff to RCD airlock spam. Malf AI wins by default.

**Comment by Killette2** [comment]
Gee I always wanted to get fucked with more tedium when building a space base as an engineer

**Comment by robosperg** [comment]
@SonixApache deff sec is still random on some doors

**Comment by Killette2** [comment]
On second thought this would make a great engineering traitor item. Spend a majority or all of your telecrystals for this to happen then wire the grid.

**Comment by incakola** [comment]
why not have every department have their own wires 
and some doors such as department heads are always totally random
eg: Engineering doors are all the same except for CE office/Telecomms/Secure Tech storage which are all different

**Comment by Tehsapper** [comment]
>doors having random wires instead of standartized wire colours

???
"No!"

**Comment by Kurfursten** [comment]
Never seen -39 before

**Pull request closed without merging**
