### PR TITLE
adds a hunting rifle to the game

### PR DESCRIPTION
**Pull request by 9percents**
Adds a hunting rifle to the game. Holds 6 bullets. It's bolt-action and uses .308(that this PR introduces too). It can be made with an ammolathe.
showcase_complete
Additionally, you can outfit it with a scope or an internal magazine extender. For reasons, you can only print an internal magazine extender.
stuffies
Since it's a **hunting** rifle, it deals more damage to mobs. :deer: 
Sprites are done by me.
shooties

:cl:
 * rscadd: Cargo can now order hunting rifles now. They take .308 ammo and are more effective against mobs. Snaxi starts with 2 in the armory.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
I like most of it, sprite could use a little more work though.

**Comment by boy2mantwicethefam** [comment]
Implying man isn't the most dangerous game

**Comment by BomberBro** [comment]
I like it, but as said before, the actual item sprite needs to be clearer, maybe a darker outline on the edges.

**Comment by Irradiation** [comment]
>.308 (40 brute)
>Weaker in damage than fucking .357 damage (60 brute)

You fucking what?

**Comment by 9percents** [comment]
revolver is a traitor weapon, irrad

**Comment by Kammerjunk** [comment]
what if you had a gun

**Comment by SonixApache** [comment]
for what possible reason

**Comment by Buchse** [comment]
I dunno, i've been starting to agree that guncreep is getting a little excessive. I like guns in spess, but I feel they should be scarcer overall.

**Comment by PrimeDSS13** [comment]
Maybe if it was a special armory gun on certain maps, and not something you could print in an ammolathe?

**Comment by Tokanova** [comment]
perhaps it could be a special armory gun + have a design disk you can order on red alert through cargo to add its production to an ammolathe?

**Comment by 9percents** [comment]
thanks for suggestions, everyone
I'll work on it tomorrow and bring some changes
(not sprite changes though) :^/

**Comment by ghost** [comment]
Does it knock you down after firing if you aren't wearing protection like the Hecate? Does the projectile penetrate walls?
Pretty cool weapon, not really a problem to have it on the ammolathe when you have things like the vector in the armory already

**Comment by 9percents** [comment]
it doesn't create as much sound as hecate so no, it doesn't knock you out and no projectiles don't penetrate walls, it can penetrate more windows than regular bullets though
it is grouped with hecate because it's a sniper rifle too(if you attach scope) and you need to wield it 2-handed

**Comment by SonixApache** [comment]
make it .22 and make it do 22 damage haha

**Comment by Kammerjunk** [comment]
make it always decapitate and only require metal (there's no glass in it after all) and then make all the guns from CS:GO and put them into the far future

**Comment by tuypo1** [comment]
If we are looking to limit hunting rifles by map I suppose snow taxi would make the most sense to have one

**Comment by yackemflam** [comment]
jesus fucking christ the gun powercreep keeps on giving

**Comment by ShiftyRail** [comment]
Really redundant with shotguns (for anti-personnel warfare) and lasguns (for general use)
Would be more interesting as a thematic weapon for snowmap and/or for cargo rather than something security can make

**Comment by 9percents** [comment]
updated
more damage, needs disk to be printed(ordered from cargo)

**Comment by yackemflam** [comment]
putting it in cargo wont do anything to make it less of a problem

Locking things behind cargo really is the 'Doesn't randomly crit' of spessmen isn't it?

**Comment by ArchSunder** [comment]
Amazing, this gun is creeping in its own PR

**Comment by ghost** [comment]
Fuck higher damage, i like Sonix's idea: Make it a .22 and make it do 22 damage.

This should be a rifle for people who want to go hunting on snaxi or do long-range gun memes. It should not be very dangerous thus the security should not feel threatened to hand it to some greyshirt that comes asking for it. 

A scoped gun dealing revolver-tier damage that can be printed is guncreep at its worst.

**Comment by aceedex** [comment]
I agree with Baron. While I enjoy the idea. The damage is nutty. Mind that I don't think it's any kind of powercreep, it's hard to beat eguns starting in the armory. However I do think it's for the best if this was a gun you didn't have to think too hard about if a greyshit came asking for it. 
My opinion without having looked at the numbers yet, would be to make it's damage low like sonix said but if you want add a ton to it's simple mob functionality. You could even snowflake lesser forms like monkeys in there too

**Comment by ghost** [comment]
> 
> 
> putting it in cargo wont do anything to make it less of a problem
> 
> Locking things behind cargo really is the 'Doesn't randomly crit' of spessmen isn't it?

I can't believe you managed to form a good take

**Comment by ShiftyRail** [comment]
I'm more concerned about which "gameplay niche" this is going to fill rather than its pure "damage"

**Comment by tuypo1** [comment]
Yeah, it's already got the increased damage to mobs so just make it weak against players

**Comment by Kammerjunk** [comment]
btw anyone with weapons access can open this

**Comment by tuypo1** [comment]
So is this gonna get fixed or not? it seems like people are generally in favor of it as long as it is piss weak against players and only good against mobs

**Comment by 9percents** [comment]
last iteration
damage is back to its initial amount, adds it to a thematic cargo crate with other things a hunter would appreciate, removes it from ammolathe(but you can still print ammo for rifle from it), there are 2 rifles in the armory closet on snaxi now(not removing/replacing nagant)

**Comment by 9percents** [comment]
last last iteration
I forgot to remove one sentence

**Comment by Kurfursten** [comment]
Tell you what, I am inclined to give this a chance. What if instead of 40 (x2 vs mobs) you lower it to 20 (x4 vs mobs), and I merge it experimentally?

**Comment by 9percents** [comment]
what if you had a gun?

that's a no from me, kurfurst

**Comment by boy2mantwicethefam** [comment]
Based

**Comment by Kurfursten** [comment]
Hey, that just makes things easier.

**Comment by SonixApache** [comment]
told you you shoulda just made it do 22 damage

**Comment by 9percents** [comment]
fuck off, sonix

**Comment by tuypo1** [comment]
Man you sound like you really hate guns, do you have stocks in some sort of laser weapons company

**Comment by Kammerjunk** [comment]
closing this PR is the best thing that's happened to it

**Pull request closed without merging**
