### PR TITLE
Civil war of casters faction conversion of crew

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
adds a wizard spell called "convert to faction" only found in spellbooks during civil war of casters, when casted on a human mob with an active mind not already in our faction, it converts them to being in our faction (but without any wizard stuff) with the implied goal of killing all the other members of the enemy faction. converted crew are turned either red or blue depending on the faction, and it cannot be changed back until they stop being part of it.
costs twice as much as a normal spell, requires robes, and all converted crew lose this role when the wizards in their faction die. blocked by loyalty implants by default, but can be upgraded to bypass this.

## Why it's good
more crew interaction in a civil war round, also gives each wizard team the opportunity to rapidly convert people back and forth between their factions. the colour change thing also makes it more conspicuous.

## Changelog
:cl:
 * rscadd: Wizards in civil wars can now convert members of the crew to their faction to do their bidding. Does not grant any spells or special gear.

### CODE REVIEW

**Comment by gurfan** [comment]
lol

**Comment by pedr69** [comment]
make it require a hat to work or something

**Comment by PrimeDSS13** [comment]
why do wizards need more of the worst part of wizards

**Comment by SECBATON-GRIFFON** [comment]
> make it require a hat to work or something

a hat? on the wiz or convert?

**Comment by pedr69** [comment]
the convert
and i think a loyalty implant check would be a good idea too

**Comment by SECBATON-GRIFFON** [comment]
> the convert and i think a loyalty implant check would be a good idea too

added this, but with an upgrade to bypass it (i think those are 20 points? need to check)

**Comment by djkramer123** [comment]
sounds pretty awful

**Comment by Eneocho** [comment]
Sounds funny. Faction wars with scuff autobalance sounds great.

**Comment by BomberBro** [comment]
Add an unremovable red or blue hat depending on the faction and it's perfect cringe kino. Maybe snowflake it for the purple ones.

**Comment by Eneocho** [comment]
> Add an unremovable red or blue hat depending on the faction and it's perfect cringe kino. Maybe snowflake it for the purple ones.

Would cause issues cause a single breach means all factionized crewmembers are fucked since they could not put on a space suit. Unremovable team coloured jumpsuit would be better. Optional inability to damage those of your faction for that TF2 experience.

**Comment by SonixApache** [comment]
don't just turn them team-colored, turn everything on their person to the color of their team as well

**Comment by SECBATON-GRIFFON** [comment]
> don't just turn them team-colored, turn everything on their person to the color of their team as well

it does it the same way phazon or colorful reagent does, which if i remember right does that.

**Comment by adacovsk** [comment]
There's that miscellaneous spell bundle that lets you summon a coin or whatever, maybe they can get that

**Comment by Kurfursten** [comment]
Contentious and personally I dislike it, but there is a very narrow majority so we can at least try it out. Revert PR if cancerous after 1 week.

**Comment by pedr69** [comment]
wait you werent supposed to merge this he hasnt coded the unremovable hat yet

**Comment by Kurfursten** [comment]
He had weeks

**Comment by SECBATON-GRIFFON** [comment]
> wait you werent supposed to merge this he hasnt coded the unremovable hat yet

i didn't like the idea

**Pull request merged**
