### PR TITLE
Buff condensedcapsaicin (pepperspray) and fix ghost peppers not being spicy at all.

### LINKED ISSUE #24495: Ghost Peppers are weaker than regular peppers
/datum/seed/chili/ghost
	name = "ghostpepper"
	seed_name = "ghostpepper"
	display_name = "ghost pepper plants"
	mutants = null
	products = list(/obj/item/weapon/reagent_containers/food/snacks/grown/ghostpepper)
	chems = list(CONDENSEDCAPSAICIN = list(3,4), CURARE = list(0,40))
	packet_icon = "seed-ghostpepper"
	plant_icon = "chilighost"

/datum/reagent/condensedcapsaicin/on_mob_life(var/mob/living/M)

	if(..())
		return 1

	if(prob(5))
		M.visible_message("<span class='warning'>[M] [pick("dry heaves!", "coughs!", "splutters!")]</span>")

-------

As you can see from the code, eating a ghost pepper is not hot at all. All it has in it is pepperspray, and in worse case scenario curare which will paralyze you for a bit. There however is no heat to ghost peppers unless you splice it in, which inherently makes them less harmful than regular peppers unless something outside of the pepper murders you while you're paralyzed.

### PR DESCRIPTION
**Pull request by ghost**
[tweak]

Fixes: https://github.com/vgstation-coders/vgstation13/issues/24495

This mirrors the ``on_mob_life`` behavior from ``capsaicin`` into ``condensedcapsaicin``, but makes it much worse. Lot's of vomit. This PR originally intended just to fix Ghost Peppers(they had basically 0 effect), but inadvertently buffed pepperspray. Some people say it is nearly useless and needs a buff anyway. 
:cl:
 * tweak: Pepperspray(condensedcapsaicin) now has a more brutal effect on its victims.
 * tweak: Ghost Peppers got buffed. You will vomit a few times if you eat 1 (One).

### CODE REVIEW

**Comment by spoonylove** [comment]
So this will make all hot stuff burn people then if the capsaicin is added?

**Comment by ghost** [comment]
> 
> 
> So this will make all hot stuff burn people then if the capsaicin is added?
 
Nah.This just makes the reagent ``condensedcapsaicin `` increase body temperature for a little and vomit after about a minute after consumption.

**Comment by MadmanMartian** [comment]
Deceptive security buff

**Comment by ghost** [comment]
> 
> 
> Deceptive security buff

Yeah, I didn't consider that. Hmm. What to do about this. It seems obvious that condensedcapsaicin  was pretty much only thought of as being used for pepperspray, and has been built around that idea. Could leave it for that and just make a new reagent. Would be nice if we could set the concentration of a reagent and then measure it in things like ``on_mob_life``. That way I could just use ``capsaicin`` for the ghostpepper and do stuff based on the concentration.

**Comment by brndd** [comment]
Considering pepper spray is useless to the point where you're better off dumping it on the ground and filling your pepper spray with water instead, I don't think buffing it would be too bad of an idea.

**Comment by SonixApache** [comment]
make capsaicin fuck you up royally
make condensed capsaicin fuck you up relatively badly
buffing pepperspray so people might actually use it isn't a bad thing

**Pull request merged**
