### PR TITLE
Remove manual updates to the chem dispenser ui and set it to auto.

### PR DESCRIPTION
**Pull request by eswordthecat**

### CODE REVIEW

**Comment by Probe1** [comment]
What difference does it practically make?  I tested it and it seemed about the same.

**Comment by eswordthecat** [comment]
It gives the updates to the nanoui process instead of the machine process / doing itself.

**Comment by PJB3005** [comment]
The chem dispenser UI shouldn't be updated every tick, it should be updated whenever something changes.

Really make it update when the amount gets used / reagents get dispensed, and when the amount of energy increases.

**Comment by eswordthecat** [comment]
It will be updated per nano process tick if someone has the ui open if it is not it will not. Suspecting this is the issue why sometimes nano won't open at all (not the one without buttons), because this and with dna console is the only one doing this updating style.

**Comment by eswordthecat** [comment]
Also the dna console has been updated to this style last merge, don't know if someone still experiencing the nano won't open at all since then.

**Comment by eswordthecat** [comment]
The old style was calling nanomanager even no one is using it (at the process). It has checks inside to check if someone though vs my change only updates when someone has only the update status (green / orange eye) from it.

**Comment by eswordthecat** [comment]
As far as I can see the good use of this update_uis proc is when the alarm updating the AAC computers or whatever it's called because the user use the AAC and not the alarm itself.

**Comment by PJB3005** [comment]
Except updating it when there's no changes is a complete waste of CPU, NanoUI already lags enough as is.

Not to mention that since it'll get updated every nanoUI tick, the UI will be incredibly unresponsive (I fucked up when I moved the portable pump to nanoUI, it only updates per nanoUI tick, and the UI is a complete piece of shit to use due to how unresponsive it is).

**Comment by eswordthecat** [comment]
It will not get updated if no one is using it.

**Comment by PJB3005** [comment]
Yes, and if somebody IS using it, it'll get updated every tick, even if there are no changes.

**Comment by eswordthecat** [comment]
There's changes, the machine updating its energy.

**Comment by PJB3005** [comment]
It doesn't update its energy every tick, especially if it's at max energy.

**Comment by eswordthecat** [comment]
If that's your reasoning then change the others using nanoui too.

**Comment by eswordthecat** [comment]
If it's really lagging to death like you said.

**Comment by eswordthecat** [comment]
let say you have 0 energy

NOT OPEN CALLED BY PROCESS REGENERATE | NEW MECHANICS
machine process called regen by 2 total 2 | nothing no one is using
machine process called regen by 2 total 4 | nothing no one is using
machine process called regen by 2 total 6 | nothing no one is using
machine process called regen by 2 total 8 | ui is open because someone is makeing / checking chems total 8
machine process called regen by 2 total 10 | ui is open because someone is makeing / checking  chems total 10
machine process called regen by 2 total 12 | ui is open because someone is makeing / checking chems total 12
machine process called regen by 2 total 14 | nothing no one is using
machine process called regen by 2 total 16 | nothing no one is using
machine process called regen by 2 total 18 | nothing no one is using

and so on..

**Comment by PJB3005** [comment]
It's still updating the UI when it's not charging, and you're making the UI less responsive.

**Pull request closed without merging**
