### PR TITLE
Lotto ticket minor updates

### LINKED ISSUE #33374: vending/lotto shoot piles of paper, without message, when shooting inventory
[bugfix]
vending/lotto shoot piles of paper, without message, when shooting inventory.
Appears to be about 11 pieces per volley, and I'd assume it's from the Grandslam Lotto event inventory.
image

### PR DESCRIPTION
**Pull request by west3436**
## What this does

- Adds a new Unprinted Lotto Ticket item so the hacked vendors will no longer shoot pieces of paper.
- Gives lotto tickets flammability stats identical to paper.
- Fixes the hacked lotto vendor logic to no longer throw stacks of items, instead throwing one at a time.

## Why it's good

Closes #33374.

## Changelog

:cl:
 * rscadd: Hacked lotto vendors will now throw unprinted tickets instead of paper.
 * bugfix: Hacked lotto vendors will no longer throw entire stacks of things when hacked.

### CODE REVIEW

**Comment by Eneocho** [comment]
>Hacked lotto vendors will no longer throw entire stacks of things when hacked.

There goes the ashing engine. RIP.

**Comment by west3436** [comment]
Just use more vendors

**Comment by Eneocho** [comment]
> Just use more vendors

Not the same. 10 vendors before this were shot 60-80 paper sheets per cycle. Now they'd shoot 10. The idea was to reduce the work making machinery. Now they're the same as an autolathe, so you might as well use an autolathe.

**Comment by west3436** [comment]
> > Just use more vendors
> 
> Not the same. 10 vendors before this were shot 60-80 paper sheets per cycle. Now they'd shoot 10. The idea was to reduce the work making machinery. Now they're the same as an autolathe, so you might as well use an autolathe.

It was a bug kek

**Comment by Eneocho** [comment]
> > > Just use more vendors
> > 
> > 
> > Not the same. 10 vendors before this were shot 60-80 paper sheets per cycle. Now they'd shoot 10. The idea was to reduce the work making machinery. Now they're the same as an autolathe, so you might as well use an autolathe.
> 
> It was a bug kek

A wonderful bug I'd like to see stay. Good for engines, good for gauging the gunk level of the round, good to see how many people hanged around in the bar.

**Comment by PrimeDSS13** [comment]
the ashing engine has been done multitudes of times before this
just use an autolathe

**Comment by Eneocho** [comment]
> the ashing engine has been done multitudes of times before this just use an autolathe

I have. I just like the paper spam better.

**Pull request merged**
