### PR TITLE
makes shuriken less fuckhueg

### PR DESCRIPTION
**Pull request by SirSkeleto**
[sprites]

please only merge after #22135, which makes shuriken autopickup so that the size of the sprite (and thus its ease of picking up) is no longer a problem to someone in full shakyhands panic mode

images:

### CODE REVIEW

**Comment by Kurfursten** [comment]
My only concern is that it's going to be harder to grab your stack from your pocket when the sprite is smaller.

**Comment by Sooose** [comment]
Kurf you never have to click the sprite if its in a container, just click the slot.

**Comment by Kurfursten** [comment]
I thought we only had that for storage items  (e.g.: bags, toolbelts) not pockets

**Comment by mtpowell** [comment]
Are shurikens actually thrown or are they instant? last few times I've been hit by them I don't see em flying at me

**Comment by Kurfursten** [comment]
They are thrown, they travel really fast to the point where they are functionally instant. If it was thrown out an airlock you would be able to see it moving, but over the short distance of 7 tiles it seems instant.

This means it has all the properties of being thrown (like bouncing back from walls sometimes, causing throw impacts with things like the supermatter shard, etc).

**Comment by SirSkeleto** [comment]
@Kurfursten 
shuriken qol pr got merged

**Comment by Kurfursten** [comment]
Did we determine if they have opacity in the pocket?

**Comment by SirSkeleto** [comment]
> Did we determine if they have opacity in the pocket?

you don't have to click on the sprite itself
this goes for all items

**Pull request merged**
