### PR TITLE
Lawgiver

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds the lawgiver pistol. It can fire taser bolts, laser cannon beams, assault rifle bursts, flares, and gyrojet rounds. Its magazine contains five of each, and is replenished in a recharger. Firing mode is changed by voice command. The gun cannot be fired unless it has a DNA sample registered to it. If someone attempts to fire it and their DNA does not match the lawgiver's record, it will explode. If the user is wearing an ID with security access it will not explode, but it still won't fire. The assault rifle bullets are modified versions that do ten damage each, for a total of 30 brute per full burst, which I think balances the fact that it doesn't need a cooldown that an assault rifle does. Furthermore, they don't knock people over. The flares that the lawgiver fires can set people on fire just like the syndicate flare gun can.

I've changed gyrojet rounds to explode on bump rather than on hit. This means that they no longer penetrate (which frankly their penetration was terrible anyway, I could only get them to go through some glass airlocks) but now they do explode when hitting things like girders, bookcases, and lockers instead of just vanishing when they them.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I don't think I like the nerf to girders.

**Comment by Shadowmech88** [comment]
It occurred to me when I was firing the gyrojet during testing, and a bare girder could tank five shots and be fine, but a completed reinforced wall would be gone after two.
Either rwalls were too weak or girders were too strong, but there was an incongruity there, don't you agree?

**Comment by Kurfursten** [comment]
It's a similar behavior to how they are treated by pulse destroyers, right? Girders are supposed to be very difficult to destroy. I think it's WAD.

In either case, if you think girders need to be nerfed, that's a valid balance opinion, but (1) it's not atomic to this PR (don't worry, I'm one of the worst offenders on this), and (2) I think we should balance ex_act around bombs/IEDs as opposed to gyrojets given that one of those is much more common.

**Comment by Shadowmech88** [comment]
You've got a point, especially about the atomicity of it. I'll leave it for another PR.

**Comment by clusterfack** [comment]
Girders are pretty annoying

**Pull request merged**
