### PR TITLE
Removed death sting

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * rscdel: Changelings can't use Death Sting anymore.

### CODE REVIEW

**Comment by Irradiation** [comment]
Can I geet a uuuuuuuh speedmerge?

**Comment by ghost** [comment]
Can't you just rebalance it instead of outright delete?

**Comment by ShiftyRail** [comment]
Stunning & brave

**Comment by soyconsumer** [comment]
Make deathsting inject poison but remove the mute and stun
Remove it once ling got reworked

**Comment by SonixApache** [comment]
👌

**Comment by Hoshi-chan** [comment]
Now THIS is a PR.

**Comment by aceedex** [comment]
I never like to see something straight up removed. Before it comes to this Id like to try those suggestions of removing the mute  stun, removing the alert text but also increase the cost so that lings cant memesting the entire station

**Comment by ghost** [comment]
why not instead of having it inject cyanide it injects whatever is in Destroying Angels.
They feel a prick, but nothing else. No symptoms or anything for a while and then eventually they just drop dead.
It means they can move around for a while before dying, and doesn't just give lings a big free succ.

**Comment by Irradiation** [comment]
There was a sort of attempt to "rework" memesting so it isn't an instant "haha you're stunned & dead" (See #19018) for all it's worth with emojicracy and no polls that I could find to back it up & it got closed 🤷‍♂️

**Comment by AutismSpider** [comment]
@aceedex so we revert death sting to what it was aka just ton of Lexorin jam into you

**Comment by iFlashYou** [comment]
I died to x antag ability, remove it

**Comment by SonixApache** [comment]
here's a meme for you
delayed death sting that makes people zombiepowder dead, and then force-regenerates them after a minute or two

**Comment by Irradiation** [comment]
Here's some spice for you: you can't succ dead people. JUST LIKE IN DA MOVIES

**Comment by Shadowmech88** [comment]
I don't really see a way to balance this in a way that makes it fun, since deathsting in essence is "no warning no counterplay kill."

**Comment by Pathid** [comment]
The counterplay is to validhunt the lings as hard as you can whenever there's a hint of lings. Which makes deathsting become practically mandatory. There's no "out" for either party in this cycle, just a race to see who can ruin the other's fun faster.
That said, we probably shouldn't expect a simple removal to fix lings instead of shunting them into a different variety of busted.

**Comment by Dacendeth** [comment]
Bring back that one PR that made it inject chef special sauce instead.

**Comment by Allspice** [comment]
Regarding the destroying angel suggestion, amanatin makes you druggy for 30? seconds.

**Pull request merged**
