### PR TITLE
Gives biosuits plasma resistance

### PR DESCRIPTION
**Pull request by Blithering**
Adds plasmaguard to biosuits, allowing those with access to them to brave plasma spills without their clothes being contaminated.
whoops
 
If that plasma becomes ignited or is at high pressure you're still screwed however.
:cl:
 * rscadd: Biosuits now prevent plasma clothing contamination, toxins can now clean up its own mistakes!

### CODE REVIEW

**Comment by FudgePucker** [comment]
:+1: this is great.
This would nerf lazy plasma floods, without fucking over atmospherics. Why isn't this already in the game?

**Comment by Shadowmech88** [comment]
Not that I'm against this, but isn't 5 hours a little bit fast to merge a balance change?

**Comment by FudgePucker** [comment]
It isn't that big of an impact.
Fires and ZAS still will kill you.
Only seven suits on station that provide plasma protection, as it stands you only have at most seven people to worry about after a plasma flood. With this change, lazy plasma flooding is punished.

Worse case, scientists dragging open plasma canisters while in biosuit. Hell this is still a stupid idea because if someone is smoking you fuck yourself over.

**Comment by Blithering** [comment]
That was rather fast I agree, but its literally a single word change, a revert won't break anything if it turns out to be needed.

**Comment by Exxion** [comment]
Yeah that was really fast
Cool those jets a bit

**Pull request merged**
