### PR TITLE
Adding a verb allowing admins to debug strike team datums

### PR DESCRIPTION
**Pull request by DeityLink**
might help me understand why sometimes ERT doesn't load up.

also might fix a bug that cause a strike team to have less people than it should sometimes.

and lastly added ERT preparation to the areas that appear on the ERT holominimaps, duh

### CODE REVIEW

**Comment by PJB3005** [comment]
> he doesn't just use SDQL SELECT.

**Comment by Exxion** [comment]
SDQL SELECT doesn't seem to work with datums
At least I've never gotten it to

**Comment by PJB3005** [comment]
It definitely does.

**Comment by Exxion** [comment]
By what witchcraft, then? Because `SELECT /datum/subsystem` doesn't.

**Comment by PJB3005** [comment]
You need to specify a list to pull from. BYOND doesn't allow iterating over
all datums (and thank God it doesn't).

SDQL has full global var access, so you want SELECT /datum/subsystem IN
Master.subsystems

**Comment by Exxion** [comment]
OK, that makes sense

**Pull request merged**
