### PR TITLE
Lube is no longer invisible, now has water wet floor overlay

### PR DESCRIPTION
**Pull request by 9600bauds**
Because invisible hazards is pretty shit
Also removes one unnecessary variable from all simulated turfs

### CODE REVIEW

**Comment by SonixApache** [comment]
heresy

**Comment by kol1th** [comment]
HE'S
BACK

**Comment by 9600bauds** [comment]
Probably not sorry

**Comment by Kurfursten** [comment]
This is the change I always wanted but never thought I'd be able to coderbus through.

**Comment by FudgePucker** [comment]
::+1: fuck space lube.

**Comment by Shadowmech88** [comment]
> never thought I'd be able to coderbus through

So far it seems like most of the community wants it as well.

**Review by PJB3005 — APPROVED** [review]

**Comment by clusterfack** [comment]
Alright sure I guess

**Comment by Kurfursten** [comment]
@clusterfack I thought the point of lube is that it slides more, it can terribly injure or kill people, you can't walk on it safely with galoshes or magboots or syndie shoes, and there's no way to get rid of it.

**Comment by Exxion** [comment]
I'm pretty sure cleaning the floor gets rid of lube, but yes to the rest

**Pull request merged**
