### PR TITLE
Eucharist Wafers

### PR DESCRIPTION
**Pull request by Arthurdentist**
This PR adds Eucharist Wafers to the game because it was bugging me that the Chaplain didn't have them.

5 Holy water and 5 flour in the microwave to create

three wafers also exist in the chapel vendor

wafer

This is without a doubt the greatest PR of all time as it contains relevant and useful content that everybody will appreciate.

### CODE REVIEW

**Comment by 9600bauds** [comment]
requires more starting wafers

**Comment by Arthurdentist** [comment]
each wafer has 5 holy water in it so I don't want to add too many.

**Comment by 9600bauds** [comment]
more wafers

**Comment by Arthurdentist** [comment]
how many

**Comment by 9600bauds** [comment]
how many would jesus add

**Comment by CptWad** [comment]
What is all of them, "Feature requests that never got any replies" for 400 please.

**Comment by Arthurdentist** [comment]
hope I've satisfied your wafer lust

The vendor now contains seven.

**Comment by 9600bauds** [comment]
Absolutely sacred

**Comment by Arthurdentist** [comment]
pope

**Comment by Kurfursten** [comment]
Needs [Holy] tag

**Comment by clusterfack** [comment]
in nomine christi, amen

**Comment by ghost** [comment]
:+1:

**Comment by gbasood** [comment]
:+1:

**Comment by Ephx1** [comment]
Make it turn to flesh with some neat ritual or other.

**Comment by Zth--** [comment]
Did you update the wiki? The cook guide

**Comment by Kurfursten** [comment]
Arthur never updates the wiki

**Comment by Arthurdentist** [comment]
thats actually a lie. Wasn't even aware this was merged.

**Pull request merged**
