### PR TITLE
MDF Grenadier Changes, plus nu Ayy Soldier Type

### PR DESCRIPTION
**Pull request by Optimism333**
nuayyenemies
## Danger Close ##
- The MDF Grenadier has been changed spritewise and codewise to be more appropriate to his namesake. He no longer has a disintegrator, he now has a grenade launcher. And instead of only having a chance to "throw" a grenade, they are now his primary ranged projectile, albeit with a long cooldown between shots (8 seconds). There's only four grenadiers in the mothership lab vault, but this does make them quite a bit more dangerous.

## Ayy EVA ##
- I added the code and a previously unused sprite for a spaceworthy ayy soldier. While it won't be added to the mothership lab vault, it can be used for buss. I also intend to use it for a bigger project of mine (coming soonish).

[content] [vault]

:cl:
 * tweak: The MDF Grenadier has a greater affinity for grenades, and has been trained to use a grenade launcher
 * rscadd: The code and sprite for an MDF Trooper (spaceworthy ayy soldier) has been added

### CODE REVIEW

**Comment by Kurfursten** [comment]
Do they do nothing but move around for the 10 seconds between shots?

**Comment by Optimism333** [comment]
> Do they do nothing but move around for the 10 seconds between shots?

For the time being, yes.

**Comment by Kurfursten** [comment]
That's a very long time to do nothing at all. Maybe you could set them up so their retreat distance increases while on cooldown so they'll at least fallback while reloading?

**Comment by Optimism333** [comment]
> That's a very long time to do nothing at all. Maybe you could set them up so their retreat distance increases while on cooldown so they'll at least fallback while reloading?

Alright, sure. I'll add that change.

**Comment by Optimism333** [comment]
> That's a very long time to do nothing at all. Maybe you could set them up so their retreat distance increases while on cooldown so they'll at least fallback while reloading?

I reduced the ranged cooldown a little bit: 10 -> 8 seconds

I also applied that change you requested. They'll now run off after launching a grenade, and run back when their ranged cooldown is nearly finished.

**Pull request merged**
