### PR TITLE
Fixes boxstation virology power cables, adds two lights

### LINKED ISSUE #31627: box virology isn't connected to power grid
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
2cd121808cffed99f71abb118d6b96594031b963

# Description
viro is missing 2 cables, it's not connected to the powergrid
# Steps to Reproduce
go to viro
# What you Expected
power
# What Actually Happened
no power

orange 2 cables in the pic were added by me
https://files.catbox.moe/e021g9.png

### LINKED ISSUE #31753: Box station virology power
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
2d33ca4fee531ddac25eb7de243ab0a887345fc8

# Description
Two wires leading from virology access to virology on box station seem to be missing. Virology isn't hooked up to the grid. Noticed this twice now, I thought the first time was a malicious act by someone.
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by nervere**
Boxstation's virology was missing two tiles worth of cable, meaning it got depowered every round due to not being on the grid.
This PR fixes that and adds two lights to a really dark area I saw in viro when making sure I did this right.
closes #31627
closes #31753
[bugfix][box]

Before/After, respectively
viro-fix

:cl:
 * bugfix: Nanotrasen's engineers have fixed power issues in Boxstation's virology lab.

### CODE REVIEW

**Comment by Theophrastus1** [comment]
I thought viro losing power repeatedly was kind of strange

**Comment by Eneocho** [comment]
That explains the viro gunk this week.

**Comment by WindowsErrors** [comment]
how long do you think virology was like this? if its been like this for a while then I feel like this is a pretty clown-tier mapping moment

**Comment by Eneocho** [comment]
I think it's been like this since CptWad's medical PR: #31467, since that's the last time that I can remember someone touched box medical.

**Pull request merged**
