### PR TITLE
gromit mug

### PR DESCRIPTION
**Pull request by press-mark**
Add's a Gromit Mug.
Credit to boxed in the discord for the sprite
gromitmug
https://discord.com/channels/245853136495968267/246096207523348481/822662933585592372
NEW SPRITE
image
gromitmug2

:cl:
 * rscadd: Gromit Mug.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you add a pic of the mug to the main post?

**Comment by press-mark** [comment]
done

**Comment by Eneocho** [comment]
> 
> 
> done

Looking good. Thats a reddit gold big chungus wholesome keanu reeves from me.

**Comment by BomberBro** [comment]
creator

**Comment by ghost** [comment]
I don't have an issue with the reference but I concur that this isn't really fit to be added. Try and get someone to make a better sprite if you strongly care about it.

**Comment by press-mark** [comment]
okay a better sprite was supplied once again by boxed
image

**Comment by SirSkeleto** [comment]
gromit mug

**Pull request merged**
