### PR TITLE
Fixes new_player hard del

### PR DESCRIPTION
**Pull request by Exxion**
The beast is slain.

### CODE REVIEW

**Comment by DamianX** [comment]
A moment of silence for all the time we've spent on this that we'll never get back.

**Comment by Zth--** [comment]
The real treasure was the friends we made along the way, damian

**Comment by clusterfack** [comment]
Bravo mate

**Comment by Exxion** [comment]
This indeed fixed the main cause, as they no longer *always* hard del, but it seems they still do sometimes. I can't get it to happen locally, though, so it's probably something weird.

**Pull request merged**
