### PR TITLE
Undoes some of the recent security sprite changes

### PR DESCRIPTION
**Pull request by SonixApache**
This PR undoes the sprite changes for the security armor vest and standard security uniform made in #27674.
Other changes, such as the helmet and belt changes and the addition of new items remain untouched.

My reasoning for this is that I don't like the "popped collar" effect the new sprites had. 
The new sprites felt out of place compared to all the other outfits.
This is the result:
dreamseeker_2020-09-13_21-08-42
Thank you to buche for leaving the old sprites in, it made the process a lot easier.

🆑 
 - imagedel: NT has rolled back their recent experimental alterations to security uniforms and vests.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
I have no issue with the uniform. I don't like the helmet, though.

**Comment by SonixApache** [comment]
I'm not so sure about the helmet yet myself. It looks strange to me, but I'm giving it the benefit of the doubt.
The vest and uniform popping out like it never did before bother me a lot, so that's why I made the revert.

**Comment by kilozombie** [comment]
Yeah I do miss the old helmet just from memory. The new one still looks good, but I do miss the dorkier look of the old one.

**Comment by ShiftyRail** [comment]
I just liked the patch of hair.

**Comment by PrimeDSS13** [comment]
I don't mind the new uniforms, but I don't like the new body armor. Just looks kind of weird, and it doesn't look good without the security belt on. Additionally, it makes the bartender look like he's serving citizens of Space Detroit, not a NanoTrasen station.

**Comment by calzilla1** [comment]
I don't really care, but I _really_ don't like the new det's hat. It just looks like a bowler hat, too fat!

**Comment by SonixApache** [comment]
Here's a simple comparison for the sake of better illustrating my point.
CLASSIC is how things will be after this PR is merged, NEW is how things are right now.
MIXED

**Comment by Blithering** [comment]
Wait, the gold arm band is buggered up on the new sprites? Seems to swap sides on the north/south states and appears on both the west and east facing ones.

**Comment by SonixApache** [comment]
so it seems

**Comment by Blithering** [comment]
Well that needs fixing then, along with a couple of other things. I'll take a look at them and see if I can get a happy midpoint between old and new that doesn't offend either party too much.

**Comment by SonixApache** [comment]
feel free to put `closes #27807` in the body if you PR it

**Comment by Blithering** [comment]
what do you think, left is current, right is old, centre is the amalgamation
seccomparison

**Comment by SonixApache** [comment]
The, uh, chest thingies in their ¬ shape look a bit out of place, especially at that color
i'd make them flat and brighter -that aside, good mix

**Comment by DamianX** [comment]
People hate this, you got conflicts. Close it?

**Comment by SonixApache** [comment]
i lack the people's promised :+1:s

**Comment by aceedex** [comment]
F

**Comment by Blithering** [comment]
The amalgamation one is on its way I swear, just a lot of icons to work through.

**Pull request closed without merging**
