### PR TITLE
Packedstation fixes

### LINKED ISSUE #15511: Packedstation has the same retarded ai windoor setup as deff.
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
The windoor is on the same tile as the AI, so the AI fully obscures it. People without access won't notice this unless they right-click or alt-click the tile which is nonobvious.

### LINKED ISSUE #15512: Packed Station - Borer Room misconfigured
(WEB REPORT BY: tigerbothesh REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
27515e0b8e6cacd87358a3345ac018f79270d1b2

>General description of the issue
Scrubber #5 at the Borer Development room in Research is set to scrub plasma at the start of the round

>What you expected to happen
Scrubbers to be disabled, or not scrub plasma at round start.

Alternatively have an Atmos Control computer and the canister be disconnected like on Box

>What actually happened
Plasma canister fills the room, then gets scrubbed out immediately

>Steps to reproduce if possible
Start a new round

### LINKED ISSUE #15513: Packed station- Portable air scrubber ports not connected
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: 27515e0b8e6cacd87358a3345ac018f79270d1b2

>General description of the issue
These things are not connected at all and they won't connected if you unwrench the pipes and ports and try to connect them. I think they were mapped ontop of each other fucking up the placement pipe attachments.

https://puu.sh/wT2No/5ee3d5aaf5.png

### LINKED ISSUE #15514: Packedstation- TEG Burn room scrubbers
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: 27515e0b8e6cacd87358a3345ac018f79270d1b2 
>General description of the issue
The pipes are not connected together and won't connect together since the h/e pipes is blocking the replacement of the pipe
Also it is not connected to the outside vent at all round start

### LINKED ISSUE #15515: Packedstation- MoMMi spawning locations- Trapped
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: 27515e0b8e6cacd87358a3345ac018f79270d1b2 
>General description of the issue

For some reason the spawning location's for MoMMis are like so 
https://puu.sh/wT3xS/38d0eab4d7.png
This means the bottom mommi is stuck in place until top mommi moves. What if top mommi is afk?

if it was just changed to side to side it would be better for everyone

### LINKED ISSUE #15516: packedstation- Scrubber piping above security in their maintance
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: 27515e0b8e6cacd87358a3345ac018f79270d1b2 
>General description of the issue
There is a good amount of missing piping in maintance above security. Is this intended?
https://puu.sh/wSZ1O/b4229b81b5.png

### LINKED ISSUE #15517: Packedstation- Unisex bathroom above library
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: 27515e0b8e6cacd87358a3345ac018f79270d1b2 
>General description of the issue
The bathroom button here locks, unlocks, and opens the door up here.
https://puu.sh/wT3QQ/c5ba65d995.png
There is a button in that room that does the same thing.
It does not lock the bathroom door you are in. Also it is missing a toilet. The names for the doors are also just called unit 1 and unit 2 if that is intended

### LINKED ISSUE #15518: Packedstation- Random airlock for security maintance
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: 27515e0b8e6cacd87358a3345ac018f79270d1b2 
>General description of the issue
This is just a random airlock for a door instead of just a normal door for maintance for security north side.
It does not lead to space.

https://puu.sh/wT0kg/587adccc05.png

### LINKED ISSUE #15519: Packstation Engineering Feedback
* Would like a singularity monitor telescreen
* An extra airpump inside atmos where the public can't steal it would be a big plus. If there's too little space, put it in the TEG room.

### LINKED ISSUE #15520: Packed Station Mommi Nest
(WEB REPORT BY: spooooon REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
27515e0b8e6cacd87358a3345ac018f79270d1b2 

>General description of the issue
2nd useless circuit imprinter in the nest, underneath the cyborg charger.  Blocks use of the charger unless you unbolt and move it.

>What you expected to happen
To.. use the charger?

>What actually happened
I bumped into it a few times like a retard until I unbolted, moved, and discovered the circuit imprinter under it.

>Steps to reproduce if possible
for fucks sake

### LINKED ISSUE #15522: Packedstation- Firelock in wall
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: 27515e0b8e6cacd87358a3345ac018f79270d1b2 
https://puu.sh/wT9Rf/563bd1139d.png

### LINKED ISSUE #15529: Wrong values on the gas things on atmos - Packedstation
The MSGS are set to 20% Nitrogen and 80% Oxygen, while the air on the station is 80% Nitrogen and 20% Oxygen.

### PR DESCRIPTION
**Pull request by PromethTK11**
fixes #15520 
fixes #15522 
fixes #15511 
fixes #15512 
fixes #15513 
fixes #15514 
fixes #15515 
fixes #15516 
fixes #15517 
fixes #15529
closes #15518 
closes #15519

### CODE REVIEW

**Comment by PromethTK11** [comment]
oh no travis i loved you until now

**Comment by Kurfursten** [comment]
Travis is failing because we have a special check in to fail if someone manually modifies layers

**Comment by PromethTK11** [comment]
It is broken? I did that to fix the layered scrubber pipe don't merging with portable scrubber connectors

**Comment by PJB3005** [comment]
The failing build is fixed with #15525

**Comment by N3X15** [comment]
Kicking travis, ignore close

**Pull request merged**
