### PR TITLE
Remove need for carrier fluid from Fourier and Hyperspectral

### PR DESCRIPTION
**Pull request by PJB3005**
AKA making Xenoarch slightly less newb trap.

:cl:

- tweak: Carrier fluids are no longer necessary for the xenoarchaeology Hyperspectral Imager and Fourier Transform spectroscope.

### CODE REVIEW

**Comment by ComradeDispenser** [comment]
I don't know what any of this means but if it makes xenoarch more accessible I'm all for it

**Comment by Probe1** [comment]
@ComradeDispenser Take a rock sample.  Grind it.  Add a SPECIAL MATCHING REAGENT to the beaker which probably means checking the wiki.  Do a fourier transform to get a print out of the distance from where you took a rock sample to the nearest artifact.  And I mean the raw distance.  Not 30 tiles south just a plain 30 tiles away.  Take some more rock samples to triangulate the location using based trigonometry that all of our players are comfortable using in a video game to find a large artifact every round.  

This PR removes the SPECIAL MATCHING REAGENT.

**Comment by PJB3005** [comment]
Actually the fourer literally did not use the carrier for result accuracy.

**Comment by Probe1** [comment]
Whoops.

**Pull request merged**
