### PR TITLE
Allows more decals to be painted with the tile painter

### PR DESCRIPTION
**Pull request by Pancakemines**
## What this does
Adds some decals to the tile painter so you can better show your projects.
dreamseeker_8JAvjMEU03

## Why it's good
Giving players more freedom to decorate or warn crew about whatever they're working on should help people be more involved or avoid dying more.

## Changelog

:cl:
 * rscadd: added radiation symbols to tile painter.
 * rscadd: added the ability to paint wall signs on the tile painter
 *  rscdel: Removed some tile painter buttons that had nothing in them.
 *  imageadd: Added one new crime pays sprite.

### CODE REVIEW

**Comment by angryturnip** [comment]
the one on the left looks more like the fallout shelter symbol, but it shouldn't have that black circle in the middle. If it's meant to be the radiation symbol the circle is supposed to be the same color as the outer blades

**Comment by SECBATON-GRIFFON** [comment]
i feel like a lot more things should be added to the tile painter, like department direction signs, firelock exit warnings, restricted area warnings etc if they arent already there

**Comment by Pancakemines** [comment]
> the one on the left looks more like the fallout shelter symbol, but it shouldn't have that black circle in the middle. If it's meant to be the radiation symbol the circle is supposed to be the same color as the outer blades

More like this then? I gotta be honest I just used the one that was already there and added it to the painter so im winging it from here on out.
dreamseeker_aqxLEW4kbd

**Comment by Pancakemines** [comment]
> i feel like a lot more things should be added to the tile painter, like department direction signs, firelock exit warnings, restricted area warnings etc if they arent already there

These ones? They're not in there at the moment I guess because they're supposed to only go on walls but I guess if people didn't hate how they looked on the floor I could add them and change the PR to just be about adding decals in general. The only real issue is they clutter the ui a little since its an extra fourty or so entries. (update I have evolved my abilites and found out how to just put all the department directions under their own button so it doesn't clog up decals with all of them)
dreamseeker_T7BdrePJUu

**Comment by angryturnip** [comment]
> More like this then? I gotta be honest I just used the one that was already there and added it to the painter so im winging it from here on out. dreamseeker_aqxLEW4kbd

That's better. I mean everyone will read it as radioactive. I'm just being an autist since it's an internationally recognized symbol

**Comment by SECBATON-GRIFFON** [comment]
> > i feel like a lot more things should be added to the tile painter, like department direction signs, firelock exit warnings, restricted area warnings etc if they arent already there
> 
> These ones? They're not in there at the moment I guess because they're supposed to only go on walls but I guess if people didn't hate how they looked on the floor I could add them and change the PR to just be about adding decals in general. The only real issue is they clutter the ui a little since its an extra fourty or so entries. (update I have evolved my abilites and found out how to just put all the department directions under their own button so it doesn't clog up decals with all of them) dreamseeker_T7BdrePJUu

make these ones wall only somehow if you can

**Comment by Pancakemines** [comment]
> make these ones wall only somehow if you can

Honestly way beyond my ability I'll mess around some but I promise nothing.

**Comment by hacker-on-steroids** [comment]
aren't all the ones on the right actual sign objects you have to screwdriver to attach/pickup?

**Comment by Pancakemines** [comment]
Yeah I figured I'd mention this now I actually got it working so as it stands I've made the "signs" only paintable on walls but as you said they are currently signs in game that as far as I can tell are not obtainable anywhere except exactly where they are currently mapped. So I'm leaving it as is but if it seems weird I could always make all the signs orderable from cargo instead it just seems like something no one would ever do anyway and outdated. I leave it up to the people and whomever merges or not I suppose. (worth noting I didn't actually know they were signs when I started, my bad)

**Comment by jwhitak** [comment]
Edit the CL to reflect your changes (Adding the ability to paint wall signs on the tile painter) and this looks good to merge.

**Review by jwhitak — CHANGES_REQUESTED** [review]
Edit the CL to reflect your changes (Adding the ability to paint wall signs on the tile painter) and this looks good to merge.

**Comment by Pancakemines** [comment]
> Edit the CL to reflect your changes (Adding the ability to paint wall signs on the tile painter) and this looks good to merge.

all done boss

**Pull request merged**
