### PR TITLE
Vacuum air alarm preset and subtype

### PR DESCRIPTION
**Pull request by brndd**
I wanted to map a MoMMI nest that starts with no pesky air in it, so the soap doesn't escape out of the airlock when you walk out. Adding a new vacuum air alarm preset seemed like the best way to do this.

This has the side effect of making said preset selectable on air alarms and the Central Atmospherics Computer, but that's not a big deal because the plasmaman preset already exists and is functionally very similar (sucks out all air).

:cl:
 * rscadd: Air alarms now have a vacuum preset.

### CODE REVIEW

**Comment by brndd** [comment]
Travis is failing due to some unit test shit. Don't know why, because I touched nothing related to what it seems to be failing on (lots of runtimes out of some slip test). I blame the tests.

**Comment by DamianX** [comment]
Maybe the tests were fixed in a later commit than the one you used, try rebasing?

**Comment by brndd** [comment]
Why on earth would my branch matter for that? I bet the unit tests will pass if someone just restarts them.

**Comment by brndd** [comment]
See I told you.

**Pull request merged**
