### PR TITLE
Kick act for chemistry dispensers and chem masters

### PR DESCRIPTION
**Pull request by Zth--**
Kicking chemdispensers and chemmasters now eject the beaker inside (if there's any). Reasons?

1. I think this is quality stuff
2. Sometimes you're in a hurry and all of sudden the machinery stops responding (someone ahelped this today), so instead of kicking your own computer while you reopen the game, you can now simply kick the stupid machinery not responding and get your shit done before the CMO demotes you.
3. I think this is fun

100% tested

:cl:
- rscadd: You can now kick chemistry dispensers and chem masters to eject the inserted container

### CODE REVIEW

**Comment by Fruktlimpa** [comment]
I can confirm that I have had the chem dispenser stop responding several times and being forced to reboot the client while "weed growing botanist #1321412" is waiting impatiently for his mutagen is pretty annoying.

**Comment by Shadowmech88** [comment]
>IC solutions for OOC problems

I love it.

**Comment by Kurfursten** [comment]
This is good, but I would like to remind you that the dispenser has an alt shortcut for this

**Review by PJB3005 — APPROVED** [review]

**Comment by Zth--** [comment]
Alt shortcut is the pacific non-aggressive solution

**Comment by Intigracy** [comment]
Does it shake like vending machines?

**Comment by Zth--** [comment]
Yes it does. Every kick act on machinery shakes it

**Comment by Intigracy** [comment]
Is it done?

**Comment by Sprok0** [comment]
kicking a chem dispenser should spray you with a random chemical it can make

**Comment by Zth--** [comment]
@Intigracy you mean this PR? Yes, and it's been tested.

@Sprok0 I don't think that's a good idea, people will simply alt-click instead.

**Comment by Blithering** [comment]
Could you make kicking consoles that you can put your ID in have a chance to eject the ID?

**Comment by PJB3005** [comment]
That would actually be useful in the case of a power outage. I like it!

**Pull request merged**
