### PR TITLE
Removes some useless vars

### PR DESCRIPTION
**Pull request by clusterfack**
Removes a bunch of vars, or demotes them to more specific typepaths than /atom when they are used just a few times or no times at all.

### CODE REVIEW

**Comment by clusterfack** [comment]
So far the list is
- level demoted to /atom/movable (used for layering, and only ever used on atom in FLOOR IS LAVA proc)
- timedestroyed removed, never used
- forceinvertredraw removed, never used
- tempoverlay, var used for timestop to store old appearances, converted to global list
- throwpass, demoted to /atom/movable, for obvious reasons, never used as such

**Comment by clusterfack** [comment]
I don't know why test_box is fucking up on travis, works fine on my server

**Comment by gbasood** [comment]
\>build failed due to travis cache
thanks travis

**Comment by clusterfack** [comment]
It compiles fine, I've done it manually numerous times. I don't know whats wrong with travis.

**Pull request merged**
