### PR TITLE
Spessmart destination disk now spawns in the black market uplink

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
The idea was pretty liked in https://github.com/vgstation-coders/vgstation13/pull/25299#issuecomment-561829427 so I'm doing this here.
Details:
- Spessmart disk appears in the utility section and only if there is a spessmart in the game
- It costs 600 credits (you should have money on you when you go to spessmart)
- It will teleport in your hand
- It will trigger every SPS alarm

No this is not actually related to the pyrite slimes believe it or not
No this won't make black market harder to remove if people want that, I'll just give it to the vox if it ends up removed so don't worry if you hate the black market
For the black market supporters this adds a finally useful item to the uplink because it's been barebones for the last months

:cl:
 * rscadd: If there is a spessmart in the game, a destination disk will appear on sale in the black market uplink. However, it has a guaranteed chance to trigger the SPS alarm!

### CODE REVIEW

**Comment by calzilla1** [comment]
Actually I think giving it to the vox trader would probably be for the better. It would give the vox something actually useful and valuable to trade or something to use their earnings on. Seeing sec curb stomb the birdie after they got themselve's some syndie items from the mart would be fun to see as well.

**Comment by Caboozles** [comment]
Please note that the downside of the vox getting it would be the immediate possible outing of nukies, as holochips can spawn.

I mean, I’m all for it, but maybe just make sure if the vox get it it requires a little time and not just some bad rng

**Comment by dunsel-hordon** [comment]
sounds like a pretty good idea. Giving it to the traders might be the best route to go though.

**Comment by PavelCIA** [comment]
I think spess mart should be rare and only be discovered by space exploring. This will just lead to powergaymers roundstart looting the vault fridge and flying to spessmart

**Comment by Kurfursten** [comment]
The voting support is here and frankly this is just what we need to have the momentum to remove black market for good

**Pull request merged**
