### PR TITLE
Your HUD no longer becomes black and white when you have noir vision.

### PR DESCRIPTION
**Pull request by Intigracy**
Known issue: I can't get the stupid action button overlays to respect the color changing. I'm not sure how at this point, I tried adding 
overlay.appearance_flags = RESET_COLOR 
all over in item_action/New() and it doesn't work.

### CODE REVIEW

**Comment by 9600bauds** [comment]
nooo muh immulsiuons!

**Comment by Intigracy** [comment]
The hud isn't even something you see, it's an entirely OOC feature dummy.

**Comment by ghost** [comment]
This sticks out like a sore thumb.

**Comment by Intigracy** [comment]
Too bad, it's extremely irritating not even being able to tell how healthy you are.

ESPECIALLY if you plan on adding it to Vox roundstart.

**Comment by 9600bauds** [comment]
he's not tho

**Comment by ghost** [comment]
Jesus christ do you have any idea what colourblindness is, @Intigracy ?

**Comment by Exxion** [comment]
Didn't like 80% of all vox players basically say "no fuck that" anyway?

**Comment by ghost** [comment]
@Exxion http://ss13.moe/index.php/poll/37

**Comment by ghost** [comment]
This will stick out like even more of a sore thumb when colourblindness is added. if you HAVE to have the health icon be colourful, fine, but the hud shouldn't be.

**Comment by Exxion** [comment]
I said like 80% of vox players, not 80% of players
For some reason, like everyone who plays vox hates it and everyone who doesn't loves it

**Comment by ghost** [comment]
@Exxion Some of the vox I talked to liked it a fair bit, and didn't mind it because of the idea that it'd be fine with assisted eyes. I'll have this discussion when 510 comes out and I play around with making vox colourblind then though, this PR has nothing to do with colourblindness or vox being it.

**Comment by clusterfack** [comment]
HUD shouldn't be involved in this sort of thing, colorblindness nor noir

**Comment by ihadtoregisterforthis** [comment]
Slots look bad with all the gray, including the toggle on the top.
However health, intent and throw are really hard to read without color.

**Comment by AutismSpider** [comment]
lets shit up the hud (the one thing that should not be fucking touch) for the colorbllndness meme and noir shit

**Comment by Intigracy** [comment]
@Clusterfack is this one of the files in the secret repo?

It's not working on server.

**Pull request merged**
