### PR TITLE
Add actual sentient mushmen to the black market, not simple mobs.

### PR DESCRIPTION
**Pull request by arc166**
Apparently I added the wrong kind of mushroom before, because we have two visually identical seeds that make walking mushrooms, but only one is the actual player race.
Also the price was way too high when you consider even heads get barely over 100 cash without going to an ATM and barel 300 with that
:cl:
 * rscadd: Add actual sentient mushmen to the black market, not simple mobs

### CODE REVIEW

**Comment by MadmanMartian** [comment]
So, judging by your OP post, you intend for this to be a way to get mushroom men at roundstart?

**Comment by arc166** [comment]
I mean if that's what I intended I'd not bother adding anything since you can already do that via vox traders who get these for free roundstart. They just never plant them.

**Comment by Kurfursten** [comment]
50-100 seemed fine to me. You only ever need to order it once, then you can reproduce seeds off that with clippers.

**Comment by arc166** [comment]
Changed back to that then.

**Pull request merged**
