### PR TITLE
Pulse demons are no longer able to recall the shuttle

### PR DESCRIPTION
**Pull request by ShiftyRail**
Inspired by real-life events.

## Why it's good for the game

Pulse demons fucking stink

### CODE REVIEW

**Comment by SonixApache** [comment]
grudgecode but good

**Comment by NigglyWiggly** [comment]
Cringe

**Comment by Hinaichigo** [comment]
They're so weak as is and they're meant to be mischevious.

**Comment by BomberBro** [comment]
Recall spam is OOC antagonism

**Comment by Pastamadness** [comment]
Grudge code is really big gay but pulse demons not being able to recall much like AIs makes some sense.

**Pull request merged**
