### PR TITLE
Makes all remaining new() calls of mutable_appearance into the constructor

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
## What this does
adds more parameters to this proc, such as for the mutable to copy, pixel_x, pixel_y, dir, color, etc

## Why it's good
code now compiles on my version (New() wasnt understood as a proc for this type)

## How it was tested
radial menu, captain's watch, PAI emotion updating, trophy mounts, AI shunt, clothes storage boxes, pAI setting emotion, equipping and unequipping the player and a mannequin

### CODE REVIEW

**Comment by 13spacemen** [comment]
Im not sure if this is worth doing now

https://github.com/tgstation/tgstation/issues/86462

problems with MA New() seem to be a byond bug in latest 515 which will get fixed

**Comment by west3436** [comment]
We'll give this a week or two and if it isn't patched out by then we'll use it

**Comment by hacker-on-steroids** [comment]
how is everyone else even compiling the code as of recently? we killed 514 sometime ago and 515 doesn't work now either, this PR makes it finally work
what the fuck am i supposed to use?

**Comment by SECBATON-GRIFFON** [comment]
honestly every single use of new() ignores the hack for MAs, ive noticed. the non constructor uses all pass an original object argument which bypasses the check as specified, and everything else just uses it which defaults to FLOAT_PLANE anyways

**Comment by west3436** [comment]
> how is everyone else even compiling the code as of recently? we killed 514 sometime ago and 515 doesn't work now either, this PR makes it finally work what the fuck am i supposed to use?

This is an issue with the latest version of Byond, not our codebase. You can either downgrade or wait for an update to fix the issue. If the update doesn't come within a week and a half, we'll just merge this change.

**Comment by hacker-on-steroids** [comment]
i fucking hate updooting

**Comment by west3436** [comment]
@SECBATON-GRIFFON @hacker-on-steroids this has been resolved in 515.1644 - please update your clients.

**Comment by LemonInTheDark** [comment]
> @SECBATON-GRIFFON @hacker-on-steroids this has been resolved in 515.1644 - please update your clients.

(this version has not been released yet)

**Comment by hacker-on-steroids** [comment]
so what he meant is "this will be fixed once 515.1644 gets released"?

**Pull request closed without merging**
