### PR TITLE
Spacesuit contamination adjustment

### LINKED ISSUE #8826: Spess suits and plasma
So this is a little topic I want to bring up. When there's a plasma flood, all hardsuits (and I think soft suits) get effected by plasma, while the CE's suit and Atmos tech suits do not. Should we have ALL space suits, hard and soft, be resistant against plasma?

### PR DESCRIPTION
**Pull request by Intigracy**
Every spacesuit except the santa spacesuit and pirate spacesuit (they're clothing, what do you expect) now protect you against plasma contamination.

fixes #8826

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
> a day ago
> he gave up

Not everyone is turbocoding all day

**Comment by Intigracy** [comment]
but why not

**Comment by gbasood** [comment]
He said in IRC he was going to fix it up but hey
I think I might prefer this solution

**Comment by Probe1** [comment]
Please don't remove thinking from the game.  If you want to work in a plasma field you go get a special suit.  

There is nothing wrong with as is.  There is a hell of a lot wrong with making things easier for the sake of making it easier.

**Comment by Exxion** [comment]
Except contamination as it is right now:
1. Is dumb
2. Is stupid
3. Adds difficulty, but not in a way that is remotely fun
4. Makes no sense
5. Is stupid and dumb

Difficulty just for the sake of difficulty is no better than making it easier just for the sake of making it easier.

**Comment by Imagebard** [comment]
@Probe1 
One, you're not :-1: 'ing a PR that removes plasma contamination, you're :-1: 'ing a PR that gives more hardsuits plasma resistance(Hypocritical, given you asked us not to "remove thinking from the game." when you can't think yourself)

Second, you're clearly lying about "nothing wrong with it as is" and also lying when you say we're removing it "to make things easier"
Please shut up.

**Comment by FudgePucker** [comment]
@Probe1 
Oh yea, no problems.
No one has been complaining about contamination.
There isn't 10 issues about how fucking stupid contamination is.

No issues at all.
At all.
At all.

**Comment by liltiptop** [comment]
tfw retarded coder
Thanks for finishing what I couldn't. I need to learn to into code better.

**Comment by Probe1** [comment]
what ten issues?  There is literally **one issue** and it was made by **the coder who opened a PR to fix his own issue**

**Comment by Imagebard** [comment]
Okay, either this Probe1 legitimately guy doesn't know much about all the talk about contamination, or he knows that he will lose plain and simple if people see that nobody liked contamination to start with.

**Comment by ihadtoregisterforthis** [comment]
I liked contamination to start with.
Maybe you are this Nobody guy you're talking about

**Comment by Imagebard** [comment]
Sounds like ihadtoreigsterforthis just got autotraitored.

**Comment by Exxion** [comment]
FUCK WHO SUMMONED RIRI?

**Comment by gbasood** [comment]
@Probe1 
The problem with contamination is that it is not a mechanic that actually adds depth to the game beyond "haha fuck you you were in plasma and now you'll stay dead forever because medbay doesn't want to/think to take your shoes off"

Plasmafloods should be less viable than they are now, and this is a step in that direction without removing the viability of a plasmaflood in the process

**Comment by ghost** [comment]
Shit's supposed to be nasty and the contamination adds an extra layer to the threat instead of not giving a shit while you shut off the vents and bolt the doors unless it gets lit remotely by shit like an overload/hack shock by "unknown"/signaller-igniter in the trash cause you powergamed one of like 40 suits 3 minutes in 4noraisins.

Evacuate to space with your space proof suit that protects you from space where there isn't plasma and get your jammies, gloves, and boots off until it's cleared or man up and take scrubbers/air condi's to medbay and down some pills to last before the sillycons or sgt shocker lights it up. Leave the plasma protection which would be expensive and unnecessary outside of a few specialized suits for the crew who are meant to come in and clean up the spills.

If you're buttflustered that shitbay was shit yet again work on educating them in OOC and in-thread. You can even update the frequently referenced wiki pages to make it more obvious to a newer player.  :-1:

**Comment by Blithering** [comment]
Do biosuits also prevent contamination? I remember that being the purpose behind the one in the RD's locker, but last time I took a stroll through the purple haze it still contaminated everything through it.

**Comment by Imagebard** [comment]
Holy fuck who also summoned SarahJohnson?

>Evacuate to space with your space proof suit that protects you from space where there isn't plasma and get your jammies, gloves, and boots off until it's cleared

I didn't know you supported retarded gameplay mechanics. Are you even reading what you write?

**Comment by Imagebard** [comment]
Okay, since it seems we have a sudden source of people supporting plasma contaminating clothes through airtight space suits, I would like to state the disadvantages of not giving all suits plasma protection:

It makes plasma the go-to to any malf AI or traitor. Even worse than bombs, around 0 to 4 people on the station(The Chief Engineer and his Atmospheric Technicians) will be able to "fight" the plasma flooder. Other people can join the, but they'll be without shoes and in hardsuits, therefore slow as fuck, and magboot-less. The magboots part will be important. Want to know why? Unless you can scrub the station's plasmaflood, you'll have to... Open the floor so people can use normal space suits. Which will cause all sorts of atmospherics fuckery and you might end up dying if you don't have magboots, *which are contaminated by plasma...*

**Comment by gbasood** [comment]
Looking at that meme emoji voting tally we've got thanks to GitHub, it looks like this PR still has more support than not.

I'll check back on this later (tomorrow?) and if people haven't magically changed their minds I'll merge

**Comment by Shadowmech88** [comment]
I feel like it might be a better solution to give all airtight suits the ability to protect jumpsuits, gloves, and shoes from contamination, but make the suits themselves vulnerable to being plasma-contaminated if they don't have PLASMAGUARD.

**Comment by Imagebard** [comment]
If a exterior hardsuit helmet/exosuit gets contaminated, do you suffer damage as if they were contaminated?
Only the outside of the suit would be contaminated, after all.

**Comment by ghost** [comment]
@gbasood I wouldn't use the emoji voting tally as a representation of the discussion here. It's controversial, you can't merge it that suddenly.

**Comment by Imagebard** [comment]
Five people support this, but three oppose it(And two chickened out instead of arguing with me, but still)

DrCelt, can you hold a vote on the main server, at least?

>Inb4 "**Should we make the game more casual by nerfing plasma floods?**"

**Comment by ihadtoregisterforthis** [comment]
I stand against contamination removal but I agree to the airtight suits being plasma proof, and contaminable in the future.

**Comment by Imagebard** [comment]
Okay, form a total of four to three people.
Back to four if we count clusterfack(???)

**Comment by clusterfack** [comment]
I like contamination I think its just poorly explained in terms of how you get it, what it does, and how to rid yourself of it.

**Comment by Intigracy** [comment]
If someone wants to seperate PLASMAGUARD into two flags, that's cool.

As it is, PLASMAGUARD prevents what the item and everything it covers from being contaminated.

**Comment by gbasood** [comment]
> Five people support this, but three oppose it

Six and four against actually if you count things other than :+1: and :-1: 
But yeah point well made, won't immediate merge

> If someone wants to seperate PLASMAGUARD into two flags, that's cool.

Seems like an unnecessary abstraction honestly, why should a single mechanic get two flags all to itself? I like @Shadowmech88's idea

**Comment by Intigracy** [comment]
Shadowmech88's idea would require seperating it into two flags, unless you have another way of doing it.

**Comment by gbasood** [comment]
@Intigracy We already HAVE airtight suits, though. We don't need to add an extra flag.

**Comment by Intigracy** [comment]
WYCI

**Pull request closed without merging**
