### PR TITLE
Fixes centcomm HR faxes going into the void

### LINKED ISSUE #16911: Fax machines don't actually send faxes physically
#### Description of issue
Fax machines send stuff to 'destinations', but even if there's a fax machine at that 'destination', the message sent only gets shown to admins, not physically printed at another fax machine. This hurts my immulsions and other things.

#### Difference between expected and actual behavior
Send fax to centcomm -> go to centcomm fax machine -> see copy of paper
vs
Send fax to centcomm -> go to centcomm fax machine -> nothing

#### Steps to reproduce 
Send a fax message somewhere.

#### Server revision
58b5dde165c7ef46ad84db3fc2920cccd63194b8

### LINKED ISSUE #22446: IAA Printer to NT HR not giving admin notice
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
66375b7324cf4834d8c73bd19982a379f5555d1c

# Description

Tested, its giving a message transmitted successfully on client side, but admins didnt see anything
# Steps to Reproduce

be IAA, actually do job
# What you Expected

Admins to see I sent shit
# What Actually Happened

Apperently nothing?

### PR DESCRIPTION
**Pull request by ShiftyRail**
As per Harris's request.
Closes #16911 by the way.
Closes #22446

As a fun bit of trivia, sending faxes to "HR" had no effect unless the words "demotion" or "commendation" were in the title, and in this case it would automatically shit out respectively a demotion chip or a poster, regardless of the actual content of the fax.

:cl:
- rscadd: NT has moved to a more humane management. Your faxes to HR now actually get read.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Wouldn't it take admin intervention to actually send demotion chips now?

**Comment by ShiftyRail** [comment]
Yes. Better than write "benis" on a paper with "demotion" on its title.

**Comment by tuypo1** [comment]
I think it probably should still have the automated demotion chip function

**Comment by ShiftyRail** [comment]
Don't think so. The coarse way it was checked wasn't encouraging people to make good & well-argued demotion reports, but rather to just spam "Demotion" sheets. Really sad effect of making a roleplay role rely on an arbitrary mechanic.

I don't like demotion chips as a concept, to be fair.

**Comment by PrimeDSS13** [comment]
Yeah, but if there are no admins online than demotion chips are impossible to get then.
Also if you send a benis message to HR, and nobody else sees it, is it truly bad RP?

**Comment by SGuivenne** [comment]
I'm 70% sure there are additional bug reports relevant to this, I'll go trawling.

**Comment by SGuivenne** [comment]
Edit: Found it.  Closes #22446 .

**Comment by SonixApache** [comment]
Does this *actually* make a piece of paper show up at the target fax machine? Does this *actually* close #16911?

**Comment by Kurfursten** [comment]
it does make a piece of paper show up at the centcomm fax machines definitely

as to whether it affects station ones...

**Pull request merged**
