### PR TITLE
Locutogen

### PR DESCRIPTION
**Pull request by help-maint**
:cl:
 * rscadd: Added Locutogen, a chemical made from Piccolyn, Inacusiate, and Sugar. Locutogen will remember the first sentence it hears, and then replay that sentence in the head of anyone that eats it.

### CODE REVIEW

**Comment by Irradiation** [comment]
"Rent free."

**Comment by Eneocho** [comment]
On my way to make locutomix with woody got wood and add 1u of WGW to all pills.

**Comment by Eneocho** [comment]
Is there a way to reset it if somebody says a word before I could?
Also, add a small note or reaction if it registers a phrase, like bubbling or something,"the beaker sizzles after hearing a phrase.".

**Comment by help-maint** [comment]
>Is there a way to reset it if somebody says a word before I could?

No, your fault if the clown cucks you by talking

**Comment by Kurfursten** [comment]
It would be fun if there was a chemical so fragile that talking around it has a chance to make it explode (higher when yelled)

Super nitroglycerin

**Comment by help-maint** [comment]
Sound-activated reagents are a little iffy because saycode really does not support virtualhearers for things that are not atoms (i.e. a reagent datum)
I'm pretty unhappy with the hackjob it took to get this to work already

**Comment by Eneocho** [comment]
> 
> No, your fault if the clown cucks you by talking

What if I make more of the locutogen in the same beaker? Say I have 10u linked with the word "tomato" and make 10 more locutogen in the same beaker. Do I end up with 20u locutogen with "tomato" as the linked word? Do I end up with 10u that has "Tomato" and 10u unlinked as separate reagents?

**Comment by help-maint** [comment]
When mixing 2 batches of locutogen, the "host" phrase always overwrites the "donor" phrase, so you end up with 20u tomatogen. Same as blood color when mixing bloods.

**Comment by Eneocho** [comment]
What's the listening area for the locutogen? Is it a normal screen size? Bigger? Smaller? I feel it should have a 3x3 area centered around the container that registers the phrases to avoid it becoming useless since you'd be within hearing/speaking range of anyone when making it.

**Comment by help-maint** [comment]
It's screen-wide, don't think it's possible to create a listener with a custom range

Having to get good to use this chemical sounds like a FEATURE anyways

**Comment by Kurfursten** [comment]
parent_heard() gets the speech datum, and that contains `speaker`, from which you could do a get_dist()

**Comment by DeityLink** [comment]
*Dental Plan*

*Lisa needs braces*

*Dental Plan*

*Lisa needs braces*

**Comment by Eneocho** [comment]
> 
> 
> _Dental Plan_
> 
> _Lisa needs braces_
> 
> _Dental Plan_
> 
> _Lisa needs braces_

Now we need a PR to drop a pen on a player's ass if they're facing away from you.

**Review by ShiftyRail — APPROVED** [review]
It's pretty hacky but I don't really know how you can do better without summarily executing hear/say code, and to have worked with hearing cameras (which were broken for years), I know better than to ask you to do that.

**Pull request merged**
