### PR TITLE
Jabroni outfit sprites

### PR DESCRIPTION
**Pull request by ManopolisJones**
Can't believe i'm gonna miss IS12 Reborn for this

## What this does
Adds new species specific sprites for the Darkholme, fixing the poorly aligned outfit for greys, and allowing vox to wear both the darkholme and the contortionists outfit. This PR also allows fattys to wear the Darkholme, it however does not allow them to wear the contortionist's jumpsuit (Won't be fitting in any pipes with that gut, pal).

greyholme
fatholme
nothingtocrowabout
lineup big
190438000-970b9e9f-8d53-4ac7-b589-1c749e4d30de

## Elaboration
 #33021 was brought to my attention after I posted the funny leatherman ayy in the leatherjackets PR, so I figured i'd get around to fixing it one of these days. Of course, one of these days ended up being a sleep deprived early morning a few months later but hey, better late then never as they say. I ended up giving the darkholme the full species treatment with fats support, since I figured doing one species why not do both, not that I really ever cared for the jabroni outfit, frankly it just seemed like the right thing to do. But uh yeah, I feel this turned out fairly well for my low level of spriting ability, but tell me what you think, something ought to be changed and what have you.

## Changelog

:cl:
 * tweak: Allows Vox to wear the Darkholme and Contortionists Jumpsuit
 * imageadd: Added new species and fat sprites to the darkholme

### CODE REVIEW

**Comment by gurfan** [comment]
YES

**Comment by Hinaichigo** [comment]
Looks good. One thing is that the coloring seems a little differrent for the insectoid; the black looks greyer.

**Comment by ManopolisJones** [comment]
> Looks good. One thing is that the coloring seems a little different for the insectoid; the black looks greyer.

Didn't mess with the insectoid sprites, just put them up for point of reference to the other ones.

**Comment by Theophrastus1** [comment]
fuck you

**Comment by SageOfLight** [comment]
fuck you leatherman, and leatherrock, and leathergray, and leatherbug, and leatherbird

**Comment by wotisjanitor** [comment]
Hey, i posted that issue. Thanks man!

**Comment by cloutcode** [comment]
I'm an artist
I'm a performance artist

**Comment by Theophrastus1** [comment]
The PR that saved /vg/ from the Adam menace

**Pull request merged**
