### PR TITLE
AIO Grinder alt-click quality

### PR DESCRIPTION
**Pull request by 9600bauds**
i'll write this later

### CODE REVIEW

**Comment by Intigracy** [comment]
+- rscadd: "All-in-One Grinders will now try to start grinding their ingredients when alt-clicked, and only eject their beaker if no ingredients are loaded (previously they would only eject their beaker)."

**Comment by 9600bauds** [comment]
thanks now I don't need to write it intigracy you're the best

**Comment by Intigracy** [comment]
np buddy

**Comment by Exxion** [comment]
While you're at it, could you make it not open up the window when it finishes grinding if you've closed it?
Or at least if you're not adjacent

**Comment by 9600bauds** [comment]
I'll look into that later, maybe tomorrow

**Comment by 9600bauds** [comment]
tested now

**Comment by Kurfursten** [comment]
Wouldn't it make more sense to have as a separate shortcut, like ctrl+click? Like how PDAs work.

After all, there may be some cases when you want to detach without grinding.

**Comment by 9600bauds** [comment]
I mean sure it could be done but... When are you going to load stuff into a grinder if not to grind it?

**Comment by Kurfursten** [comment]
When you dump the soy beans in the grinder and realize the beaker already has flour in it and you need to take it out or suffer a trip to the condimaster

Why has not even one map placed the condimaster next to the grinder in the kitchen? Not even I was smart enough to do this with Bus and I've played Chef a ton.

**Pull request merged**
