### PR TITLE
Attempts to make movement with high ping easier

### PR DESCRIPTION
**Pull request by BobdaBiscuit**
My patchwork attempt to help ease #12779 .
Basically adds a verb under the object tab that causes a mob to stop for a few ticks after moving 1 tile, before then running on normally, if there's already a delay on runspeed ie hunger it won't trigger.

Used simulated latency on localhost to test the actual issue and it seems to work, values might need tweaking on a per player basis though, if it arises I'll work on having it all configurable.
Tested basic cases such as being hungry, hurt etc.

:cl:
 * rscadd: Added a "Pause after first step" toggle in preferences that creates a small delay after a mob's first step, attempts to help high ping movement be more precise.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Don't know about this as a fix for high ping movement, but it should definitely be a player preference and not just a verb.

**Comment by BobdaBiscuit** [comment]
I was told it needs database fuckery so I just splashed a verb together for now, how would I go about making it a preference?

**Comment by clusterfack** [comment]
This should already be softcapped on the bottom side by the movement delays minimum delay

**Comment by ComicIronic** [comment]
Wouldn't raising the minimum delay slow down all players?

**Comment by BobdaBiscuit** [comment]
The idea is to only slow the second step, since with high ping movement is fine apart from when you have to move 1 tile at a time (ie space walks, pushing shit around etc).

**Comment by clusterfack** [comment]
Raising the minimum delay would not slow down all players. And it should solve the problem you are describing exactly.

**Comment by BobdaBiscuit** [comment]
I'll give it that a go tomorrow on a seperate pr then.

**Comment by BobdaBiscuit** [comment]
Unless I fucked it up it does slow down all players, and minor unnoticeable adjustments do not help the issue.

**Comment by BobdaBiscuit** [comment]
I can't replicate it perfectly with localhost latency/packet loss but the issue does seem to be primarily packet loss, which appears above 130~ms ping.

I don't see what other kind of solution could be done without ripping up all current movement code.

**Comment by BobdaBiscuit** [comment]
Moved it to preferences, had to include the 007 migration .dm at PJB's advice.
If I fucked anything up please let me know.

**Review by ComicIronic — APPROVED** [review]

**Comment by BobdaBiscuit** [comment]
https://webmshare.com/jQvKL - webm of memes in action, reeee.

**Comment by Probe1** [comment]
@BobdaBiscuit 404 on link

**Comment by Probe1** [comment]
I'll merge this in a few hours when Pomf will be awake in case anything goes seriously awry.

**Pull request merged**
