### PR TITLE
Wheelstation remastered

### PR DESCRIPTION
**Pull request by brndd**
[general]

## What this does

Updates Wheelstation to the current year, fixing whatever remaining unfixed issues remained on the tracker, and changing and adding a bunch of other stuff.

## Why it's good

I feel we could do with one more larger "highpop" map. Many people didn't particularly like Wheelstation when it first came out, but more than one person has told me that they thought it was alright, so I decided to update it and see how it's received. If it's bad I guess it'll just never get voted, right?

One of the main reasons Wheelstation was removed back in the day was, I believe, lack of maintenance. I ended up burning out on SS13 shortly after releasing the map, so beyond initial bugfixes I didn't end up giving the map the love and attention it needed and deserved. I have given it some of that attention now, and if it gets merged and activated again I pinkie promise to bugfix and improve it for the foreseeable future.

I have fixed some of the outright questionable design the station had at launch. The engine layout is reworked to fit in an antimatter engine and to make the singularity more conventional. The funny supermatter engine still exists, but I believe it can be converted into a different kind of engine (either a conventional SME or a TEG) easily enough and has enough educational value to warrant being there. Telescience is also properly functioning again, rather than starting out in disrepair.

Also, I removed some extraneous airlocks from the hallways so it should now be even quicker to get around on the station. Added signage too, and more maint clutter, and other similar smaller tweaks.

## What the fuck is Wheelstation?

In case you blinked and missed it or weren't around to see it, Wheelstation is a station I created in 2019. It was removed sometime in 2020. The basic idea was to have a station consisting of several different sections with space gaps in-between. This design was chosen for two reasons: I thought it would look cool to be able to see into space on a space station, and I wanted to try an atmospherics gimmick where the station has multiple atmospherics loops.

wheelscreen

*Note: this image is a screenshot from StrongDMM. Things will appear slightly different in-game.*

Quick rundown of the features:

### Atmos kraken

2023-10-23T08:00:48

The station has 5 separate atmospherics loops. This makes them more fault tolerant. It also allows you to do targeted plasmafloods should you want to. The pipes are layered so that distro and waste are on different layers, which makes them easier to work with at the cost of vents no longer being centered on the tile (a tragic loss).

For the remastered version I added several more "bypass valves" around the station that can be toggled to connect the pipenets together. Their real purpose, however, is to make ventcrawlers' lives easier, and they do this even when turned off. The pipenet should now be far more interconnected than before.

### Space

gap_moe

There are many little internal pockets of space that you can see into through windows. Some may call this wasted space, but I call it negative space and they don't understand art. Or something.

One day we'll get fancier space background graphics and Europa lights these will look really cool. I said that in 2019 and we still don't have those things, but just keep waiting...!

### Maint shortcuts

I wanted to design the map so that if you know your way around, you can get around faster by cutting through maintenance and avoid dangers by taking alternate routes. I think this worked out alright, but then I *am* tooting my own horn.

### The legacy engine

2023-10-23T08:32:00

The default supermatter engine on Wheelstation was constructed before radiation collector technology became widely available, and hasn't yet been retrofitted to use radiation collectors (the crates are in the storage, the engineers are just lazy). Instead it produces power by using the shard's heat to run TEGs. Believe it or not, this is more than enough to run the station!

That's the lore, anyway. Really I just wanted to map in something different to show people what can be done, and I've always liked Baycode SME setups (their primary power source is heat, and rad collectors are just a little extra on top if you want it). This engine is actually really simple to set up, and my hope is that it can help introduce new engineers to actively cooled shard setups. It should also be a decent template for building more powerful setups.

In addition to that, this remastered version includes the trusty old antimatter engine and singularity. There is no TEG burn chamber, but the SME can be converted into one if you want to (the TEGs are already there).

### Powerful chapel

2023-10-23T08:38:13

I thought about making this a little bit saner for the remaster, but it's not really hurting anyone being tucked away on the far edge of the station. At least the chaplain has a lot of room to build gimmicks, or just a really grand temple to pray in.

### Meatball roid

2023-10-23T08:40:14

The roid looks like a drooling meatball or something in the mapper. I added a small mining home-away-from-home similar to Box because the roid used to be a little barren. It has annoying cycling airlocks because I think those are cool.

## Changelog

:cl:
 * rscadd: Readded Wheelstation with some new changes and additions.

### CODE REVIEW

**Comment by Eneocho** [comment]
Powerful. Want.
>Powerful chapel

I had at one point tried to make Chapelstation, a map where the chapel was massive (and snowflaked for the chaplain to work as a head there), but never finished it. Could you give the chapel silver floor tiling somewhere? For that holy (and powerful) vibe.

**Comment by wotisjanitor** [comment]
there's still no maint

**Comment by BomberBro** [comment]
Wheel was one of the worst maps we've ever had. It was absolutely pointlessly fucking massive and with lower pop than then it'll be even worse.

**Comment by SonixApache** [comment]
merge it but add a 50% chance for it to load island instead

**Comment by pedr69** [comment]
no SPS computer
no bangmeter
no wall-mounted nanomeds in normal medbay
and depending on the access these engimaint doors there's either two stupid maint deadends or a huge security oversight
image

fund it

**Comment by Chazach** [comment]
I think wheelstation sucks!

**Comment by Eneocho** [comment]
> merge it but add a 50% chance for it to load island instead

Ok but voting for snow has a 50% chance to load Line.

**Comment by angryturnip** [comment]
Like pedr69 pointed out, this really isn't updated as much as it should be

**Comment by brndd** [comment]
@BomberBro
> It was absolutely pointlessly fucking massive and with lower pop than then it'll be even worse.

This is the criticism it often got at launch, and I still don't think it's valid or fair. Objectively it isn't much larger than the existing maps. Running from the left side to the right side (bridge to escape) takes the same amount of time as from arrivals to escape on Boxstation. Running from Medical to Engineering (top to bottom) is faster than Security to Engineering on Box. Running the entire wheel of the station, from Engineering to Security, takes a while longer, but if you cut through maintenance the distance once again becomes about the same as other stations.

It's not that the station is much larger than other stations, it just *feels* larger. I would argue that's a symptom of successful design in what is supposed to be a highpop station.

@pedr69 thanks for pointing these out, I'll get them fixed. Deity also pointed out a simiral slew of little missing things on Discord. I tried my best to address these before making the PR, but it's difficult to catch everything.

**Comment by BomberBro** [comment]
\>it just feels larger. I would argue that's a symptom of successful design
lifesupport

**Comment by brndd** [comment]
A highpop station feeling large seems about right to me. That's a nice picture of an orangutan. Orangutans are nice. I don't see what it has to do with the discussion, though; perhaps you could use words next time?

**Comment by CrazyAmphibian** [comment]
would be nice to have more map variety.
as an engineering main, the legacy SME setup looks interesting since nobody really does it anymore, and pushes the comfort zone enough to try new things. The separated atmos loops also looks really interesting, too, but i've a feeling that won't lend itself to the innovation you'd hope for.
given the issues fixed, i think this could be a breath of fresh air from the usual map lineup.

**Comment by wankov** [comment]
I'm wheely excited for this

**Comment by wotisjanitor** [comment]
image

REDDIT, ASSEMBLE!

**Comment by SonixApache** [comment]
i know you're an AImain but make sure to do a holopad pass some time

**Comment by brndd** [comment]
2023-10-24T22:04:31

I gave this sec checkpoint outside of the bar a proper cell with a timer, the idea being that small-time criminals can serve their penalty here instead of dragging them all the way to sec. Whether it ever gets used remains to be seen.

I also added in a couple of more holopads, though I feel the map already was doing pretty well on that front.

**Comment by wotisjanitor** [comment]
Oh I like that checkpoint cell. Hopefully its used more than the roid one

**Comment by Kurfursten** [comment]
In the spirit of giving things a try I want to give Wheel a test run of at least 2 weeks and we'll hold a vote after that to see if it stays in rotation. Do you think you will be fully ready with pre-release tweaks by November 6?

**Comment by brndd** [comment]
I've fixed all the bugs people brought up in this thread and on Discord, so as far as I'm concerned it's ready already. Of course maps are never truly finished, but I don't have anything left on my to-do list that wouldn't be a time investment far too large to take on at this point in time (i.e. a large rework of the basic structure).

**Comment by Blithering** [comment]
I missed out on wheel so I don't have an opinion on it, but maps being updated is good.

**Comment by brndd** [comment]
Now that the SME books were merged, I added a Wheel-specific book for getting the default SME running.

<details>
<summary>Contents of the book</summary>

2023-11-02T02:12:25


</details>

**Comment by falcon2346** [comment]
I looked at the pipes and now I'm excited

**Comment by Eneocho** [comment]
Could you add a mapped-in airshield on the shard door? Feel that this would be an appropriate map to have that on by default (instead of built in-round), due to the focus on heat (and thus gases) on this engine, rather than radiation.

**Comment by Eneocho** [comment]
Also, the shard-TEG room looks incredible for a retrofit into a nested R-UST. Can't wait.

**Comment by brndd** [comment]
> Could you add a mapped-in airshield on the shard door? Feel that this would be an appropriate map to have that on by default (instead of built in-round), due to the focus on heat (and thus gases) on this engine, rather than radiation.

I feel like airshields are too powerful to have on a station at roundstart, since they allow you to mostly circumvent one of the core mechanics of the game. Inflatable doors were a mistake too.

**Comment by pedr69** [comment]
>airshields are too powerful

if god had wanted cycling airlocks to be used more he should have made them less shit
i still don't know what the difference between the two cycle controller boards is

**Comment by brndd** [comment]
Cycling airlocks work fine if they're mapped in correctly. They really need an air tank and a gas recapture system to not suck. My biggest gripe with them is that they only check pressure, not temperature, so it's not possible to have a cycling airlock into a coldroom. One day I will fix this.

**Comment by Eneocho** [comment]
The reason I suggest an airshield for the shard room is that ALL the game shardrooms are mapped such that if you need to close the move the shard 'cause delamination imminent or whatever, you gotta do a whole bullshit with inflatables (or just let the room be flooded with blasma, which goes against all other "safeties" engineering has. The TEG room in most stations has an airlock cycle (that gets bypassed for inflatables cause cycling is slow as hell, especially for hot rooms), the AME is (usually) out of the way, the singulo has the containment fields and blast doors, the R-UST area is out of the way (on deff). Shard gets nothing like that by default. 
And having and airshield mapped in would be a more organic way to introduce them to players.
If worse comes to worst, you can always map it out on an update, I'm just asking that the idea is given a chance.

**Comment by wotisjanitor** [comment]
airshields should only be made by science :)

**Comment by CrazyAmphibian** [comment]
> airshields should only be made by science 

as of now, this is the only way to get them besides the vending machine.
i think it'd be good for engineering to have at least a couple of boards at roundstart (the 10 you get seems like a lot to be honest, but not having any would make life harder)
the issue is that you only ever \*need\* a couple, and the only time i ever see more is when there's a meme engine that requires more than 10 shields to begin with.

but the troubling thing is that airshields are good, not just because they negate zas, but for the ease of use and convenience, and the other alternatives are either too slow or too annoying to use
maybe as a balance, make the power use of the airshield increased, or based upon the difference in atmospheres between the areas it's blocking?
~~also allow them to be deconstructed, last i checked you're kinda stuck with them built~~

**Comment by Eneocho** [comment]
But they are able to be deconstructed. You get inside it, screwdriver then weld.

**Comment by Kurfursten** [comment]
> But they are able to be deconstructed. You get inside it, screwdriver then weld.

The reason he's confused is that there are 2 versions of the airshield, one is a structure and one is a machine. The structure is used in mapping like vaults and also the syndicate pocket satellite. It doesn't require power.

**Comment by CrazyAmphibian** [comment]
> there are 2 versions of the airshield

oh there are?
> You get inside it, screwdriver then weld.

this would explain my confusion, since every other machine i know of is screwdriver then crowbar to deconstruct

**Comment by Eneocho** [comment]
Yea that too. I'm asking for the machine airshield. The one that requires power and can be deconstructed. On that note, the structure one can also be deconstructed (get inside, screwdriver, wirecutter, welder), and it doesn't leave a machine frame behind.

**Comment by CrazyAmphibian** [comment]
is there a reason airshields are dissembled in a different manner to other machines?

**Comment by Eneocho** [comment]
I added the machinery airshields as a shitcoded thing that got properly fixed afterwards, ask @jwhitak why are they disassembled different. 
I'd say it's probably to keep them aligned to structure airshields. (structure ones need screwdriver, wirecutter, welder and don't leave shit behind, while machinery needs screwdriver, welder, then disassembly like a regular machine)

**Comment by SonixApache** [comment]
airshields have no right to exist
busta is turning in his grave

**Comment by brndd** [comment]
I feel like airshields would be more interesting if they stopped working when the pressure gradient across them gets too large. So they would work between like a regular room and a vacuum, but not between a 5 terapascal TEG burn chamber and a regular room.

Anyway, if the shard starts delaminating, "by the book" entering the chamber is supposed to be the last resort, done only after venting the chamber into space fails to work. I feel like an airshield would make a situation that's supposed to be difficult and risky too easy.

**Comment by CrazyAmphibian** [comment]
> only after venting the chamber into space fails to work.

The issue with this is that most maps don't have this feature (apart from venting the entire room by breaking the windows)

**Comment by brndd** [comment]
On Wheelstation there are shutters connecting the chamber into space. I debated adding in a mass driver to launch the shard away, but I feel like that would make things too easy -- both too easy to avoid a delamination and too easy to prank the engineers.

**Comment by CrazyAmphibian** [comment]
> On Wheelstation

well that's good for wheelstation, but what about the other map that people play on?

> I debated adding in a mass driver to launch the shard away

lmao do it

**Comment by brndd** [comment]
> well that's good for wheelstation, but what about the other map that people play on?

We were talking about adding an airshield on Wheelstation, not on other maps.

**Comment by CrazyAmphibian** [comment]
> We were talking about adding an airshield on Wheelstation, not on other maps.

i know, but then the balance of airshields got brought up generally, then the venting the shard thing was mentioned by you (i'm sure you meant on wheel specifically), but its inclusion into the balance discussion of airshields isn't great since it only applies to one map (if there's another map that does it tell me).

**Comment by Eneocho** [comment]
I'd say an airshield is even more pertinent if there's a button to instantly space the chamber.

**Comment by Blithering** [comment]
If we get a button to instantly mass driver the shard into space, please make it "accidentally" pointed directly at the singulo containment

**Comment by brndd** [comment]
Rearranged the escape shuttle a little, and while I was at it I realized I hadn't added in the (stupid and annoying) mid-flight pod crash docking ports, so I put those in too.

2023-11-03T15:20:53

**Comment by wotisjanitor** [comment]
Please sir... add another custodial closet with another janitor slot... like deff

**Comment by Kurfursten** [comment]
Let the experiment commence

**Pull request merged**
