### PR TITLE
New Thermos and Water Bottle sprites

### PR DESCRIPTION
**Pull request by JMWTurner**
before (and unused)
oldbot

after
newbot

bonobo

Vox traders already spawn with a thermos in their backpack but it was using the shaker sprite for some reason.

Water bottles might come handy in some situations (future dehydratation?) or for some decoration.

### CODE REVIEW

**Comment by CptWad** [comment]
T R A S H SPRITE FOR BOTTLES
I NEED TO MAKE RAFTS OF PLASTIC TO KILL THE HIPPIES

**Comment by JMWTurner** [comment]
wait what

**Comment by CptWad** [comment]
empty plastic bottles get special trash sprite, like chip bags and what not

**Comment by JMWTurner** [comment]
They're drinks, you can fill them back up. They don't proc the spawning of a trash item.

**Comment by Kurfursten** [comment]
You could add an attackself that checks if it's empty to crumple the bottle, rendering it unusable (delete and spawn a trash object)

This also means that people who spamclick their waterbottle would smash it though

**Comment by FantasticFwoosh** [comment]
Admins need somewhere to keep their hydrating player tears.

**Comment by Kurfursten** [comment]
Oh, why don't you put water bottles in the BODA machine? That seems much nicer than glasses of water.

**Comment by JMWTurner** [comment]
@Kurfursten Actually BODA machines glasses are filled with SODA water, not plain old water. It's got bubbles in it and all.

**Comment by Kurfursten** [comment]
Well, it only has one item, it could stand to have a second item.

**Comment by JMWTurner** [comment]
Maybe in another PR.

**Comment by FantasticFwoosh** [comment]
Soda water bottles are a thing, besides its easy to cheat free glass out of recycling the glasses the soda water comes in if you're running a hardmode manual repair (IC and non borg or MMoMI) of derelict.

**Comment by JMWTurner** [comment]
Actually soda waters come in cans usually.

**Comment by JMWTurner** [comment]
emptysodacola
boda

revision 1:
- BODA machines now sell large and small plastic bottles of water as well as plastic bottles of sodawater. As well as contraband plastic bottles of space cola for free.

**Comment by ihadtoregisterforthis** [comment]
Why capitalist coca cola on the workers' vending machine?

**Comment by Exxion** [comment]
It's space cola, not Coca Cola:tm:

Also maybe it's stolen

**Comment by JMWTurner** [comment]
@ihadtoregisterforthis that's why it's CONTRABAND. Also it's already in the game. Except currently it's in a glass instead of a plastic bottle.

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis It always had space cola as contraband

Fine work, I like it :+1:

**Pull request merged**
