### PR TITLE
Glass sharpness and leathermaking tweak

### LINKED ISSUE #35060: Can't de-hair skin for leathermaking
#### Description of issue
I'm not sure what causes it but sometimes? you can't do the de-hairing step of leathermaking. Using a sharp object like a shard on the skin doesn't de-hair the skin like it's supposed to. But recently I also got it to work so maybe it's something inconsistent.

#### Difference between expected and actual behavior
Expected being able to use sharp item on skin to remove hair.
Actually can't use sharp item on skin to remove hair.

#### Steps to reproduce
Skin a creature.
Obtain a shard.
Use the shard on the skin.

[bugfix]

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
This tweaks a few things relating to sharpness:

- makes the leatherworking step give a message when you're using something with the `SHARP_BLADE` flag but that's too dull to de-hair the skin  (closes #35060). The minimum sharpness for this is currently 1.2.
- increase the sharpness of glass shards, broken glass bottles, spears (made from shards), and broken thermometers from 0.8 to 2, as freshly broken glass is typically sharper than a metal blade.
- Increases obsidian-bladed cult weapon sharpness' from 1.35 to 3

The base `force` (melee damage) of a shard (9) remains unchanged by this.
Sharpness is distinct from force (force being the main contributor for melee damage), and doesn't affect damage directly; the main thing it affects in combat is limb severing chance. Sharpness also doesn't affect bleeding or armor penetration or anything like that. Other sharpnesses for comparison:
- kitchen knife: 1.5
- butcher's cleaver: 1.2
- scalpel: 1.5
- sword: 1.2
- hatchet: 1.2
- fireaxe: 1.2
- katana: 1.2

## Why it's good
Makes it more understandable why a given bladed item can't de-hair skin for leathermaking.
Makes things more intuitive as broken glass and obsidian are very sharp:

## Changelog
:cl:
 * rscadd: Added message for using a too-dull blade when trying to de-hair skin for leathermaking.
 * tweak: Increased sharpness of obsidian and broken glass. Glass shards can now de-hair skin for leathermaking.

### CODE REVIEW

**Comment by ValkyrieSkies** [comment]
>broken glass seems like it'd be sharper than most metal blades.

Does it???

**Comment by Hinaichigo** [comment]
I think so, it's much easier to accidentally get cut touching broken glass compared to a metal knife in my experience. Also obsidian is said to be super sharp, and obsidian's a form of glass.  Sometimes obsidian scalpels are used in surgery because of their extreme sharpness supposedly. 

I think when glass breaks it ends up with super thin more-than-razor-sharp edges. But glass edges are easier to wear down and dull versus metal so if the shard was tossed around a lot it might dull faster than if you tossed a kitchen knife around to the same degree.

It'd be cool if you could make ghetto macuahuitls out of shards:
macuahuitl

**Comment by DorainGrey** [comment]
Yes, this leaves out that glass breaks upon any basically any impact.
Something that doesn't happen in spess.

Hence why you only see obsidian knives are niche surgery tools.

Have you tested what damage these increases will do, I recall sharpness being pretty lethal.

**Comment by boy2mantwicethefam** [comment]
Prepare for unforeseen consequences.

**Comment by Eneocho** [comment]
>ghetto macuahuitls

that'd be awesome for aztec RP where you accidentally cut the head off the conquistador (HoS)'s horse (warden)

**Comment by Hinaichigo** [comment]
As far as sharpness goes in combat, from what I can see, it mainly impacts the ability/chance to sever limbs.
I can test it to make sure this doesn't make shards super OP in that regard.

**Comment by Dacendeth** [comment]
It only makes sense spears are given this sharpness too as they're made from shards.

**Comment by Hinaichigo** [comment]
> Does it???

I think the main reason is that when you sharpen metal you are grinding down something to try to get it finer and finer, or scraping or ripping little chunks off of it, which is limited by the fineness of the whetstone or whatever, and leads to burrs and irregularities. Whereas with broken glass or obsidian you are splitting the solid along weak points in the molecular arrangement, so you can get edges that are just a few atoms thick.

DS-BU34UQAA8aeG jpg-large

**Comment by Exxion** [comment]
Broken glass can indeed form an extremely sharp edge, but intentionally breaking a piece of glass to form a blade is not the same as kicking a window. Also, glass blades are extremely fragile.

> It'd be cool if you could make ghetto macuahuitls out of shards

#13811

**Comment by pedr69** [comment]
don't we have a thing where throwing glass shards at a wall can make them sharper or duller randomly
making them all 5 times as sharp is retarded though

**Comment by Hinaichigo** [comment]
Honestly don't understand the downvotes in this case.
Sharpness plays a relatively minor role in combat.
Are people confusing it with force?

**Comment by Hinaichigo** [comment]
Where do you see the 5x thing?
I don't quite understand the amount of downvotes in this case... I'll remake this with just the leathermaking thing if it seems like this will fail but.. are people confusing sharpness with a kind of damage multiplier or something like that?

**Comment by falcon2346** [comment]
> Where do you see the 5x thing? I don't quite understand the amount of downvotes in this case... I'll remake this with just the leathermaking thing if it seems like this will fail but.. are people confusing sharpness with a kind of damage multiplier or something like that?

From what I understand it's because sharpness 2 is a very important threshold that allows you to delimb people with below 100 damage on that particular limb. In other words, this could potentially let you decapitate people before they even reach crit with glass shards. I haven't actually looked myself though, that's based purely on what someone else said.

**Comment by Hinaichigo** [comment]
- heads have 130 max_damage
- arms and legs have 75 max_damage,
- and hands and feet have 40 max_damage

So with less-sharp weapons and armor you'd have to reach those to sever the limbs. So for knives, swords, etc, sharpnesses you need to be in crit to have a head severed but not an arm or hand.

But for something with sharpness 2, you'd have to do:

- 65 damage to sever the head
- 38 to sever an arm/leg
- 20 to sever a hand

to have a chance to sever the limbs. I don't think that's so unreasonable per se... especially as shards aren't very powerful in terms of force, so if you're doing the 7-8 damage each swing, and they're doing the 15 from a toolbox, it probably won't necessarily make the shard-user the clear victor. but we could reduce the values to below 2 if people would find that more reasonable? Maybe something like 1.7 for shards and 1.9 for the obsidian blades?

**Comment by ValkyrieSkies** [comment]
I'm not disputing that obdsidian is super sharp yeah, but I don't think regular old broken glass is sharper than a blade specifically made to be sharp.

**Comment by falcon2346** [comment]
> * heads have 130 max_damage
> * arms and legs have 75 max_damage,
> * and hands and feet have 40 max_damage
> 
> So with less-sharp weapons and armor you'd have to reach those to sever the limbs. So for knives, swords, etc, sharpnesses you need to be in crit to have a head severed but not an arm or hand.
> 
> But for something with sharpness 2, you'd have to do:
> 
> * 65 damage to sever the head
> * 38 to sever an arm/leg
> * 20 to sever a hand
> 
> to have a chance to sever the limbs. I don't think that's so unreasonable per se... especially as shards aren't very powerful in terms of force, so if you're doing the 7-8 damage each swing, and they're doing the 15 from a toolbox, it probably won't necessarily make the shard-user the clear victor. but we could reduce the values to below 2 if people would find that more reasonable? Maybe something like 1.7 for shards and 1.9 for the obsidian blades?

The real problem comes from spears, giving them a sharpness of 2 with their much more intimidating 18 force makes those beheadings a lot easier. I'd also like to point out that a high frequency machete has a sharpness of 1.7, and I would argue that a sci fi vibrating blade should probably be sharper than some broken glass that you got from smacking a lightbulb, even if it doesn't have too much gameplay effect.

**Comment by Hinaichigo** [comment]
Hmm good point. Probably the HF machete and HF katana should be higher too since they electrically vibrate the atomic bonds apart I think is the explanation.. I'll reduce these a bit either way.

**Comment by Exxion** [comment]
Spears can have up to 29 force by the way

**Comment by Hinaichigo** [comment]
Maybe changing the sharpness limb-severing calculations could be a good. Instead of having it double between 1.999... and 2.0...01, it could instead use a (`sharpness - 1`) type of thing so, sharpness of 2.01 only has a little bit lower of a severing threshold compared to 1.99. Then there'd be more breathing room.
Something similar to what's already used for the severing chance:
https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/code/modules/organs/organ_external.dm#L203
But also putting it here too:
https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/code/modules/organs/organ_external.dm#L202

**Comment by githubuser4141** [comment]
I like how there's all this in-depth discussion on why a random piece of broken window should be sharper then 25th century steels. But everyone's OK with like, Durands being destroyed by throwing metal stars at it. In fact no one's got an issue with metal disks (ninja) shurikens being obscenely deadly 3-shot weapons even though in real life they're mostly designed to distract the opponent and don't have the energy / don't apply it in a way that can easily cause a deadly wound or even penetrate armour. People go on about "um uh it might damage the SeNsOrS" with small arms vs tanks and such but here we've got thin metal disks destroying an entire fighting vehicle in like 10 hits. Gah!!

**Comment by Hinaichigo** [comment]
After thinking about it a bit more I don't necessarily think being able to kill someone in a few hits from a melee weapon is necessarily so bad, especially considering we have a lot of other essentially instant kill and stun weapons.
If you think about how something like a shard or spear being more effective at cutting someone's foot off, in the context of also having stun batons, stungloves, tasers, e-guns, flashes, banana peels, and how melee weapons are used in practice, and also how there's armor, miss chance, disarming and taking the weapon for onesself, melee body-part targeting accuracy, and things, it'd probably be fine to make glass things sharper.
With combat, sometimes potential weapon changes get considered in the context of a 1 on 1 thunderdome kind of situation where two people  wail on each other with the weapon until one wins, but usually as we know in practice its a lot more asymmetrical and varied.

**Pull request closed without merging**
