### PR TITLE
Bartender librarian and cargo tech no longer spawn with plastic bags in their hands

### PR DESCRIPTION
**Pull request by xXxEMBERGHOSTSQUADDIExXx**
## What this does
Makes it so bartender librarian and cargo tech no longer spawn with plastic bags in their hands
now only assistants start with it

## Why it's good
It feels like trashy to be holding a plastic bag like that as if its part of your job. a suave bartender or a well read librarian holding a crinkly plastic bag as like their uniform just feels unaesthetic and doesn't make sense
i usually throw these out at roundstart and they just feel like garbage and clutter

## Changelog
:cl:
 * tweak: Bartender, librarian, and cargo tech no longer spawn with plastic bags in their hands.

### CODE REVIEW

**Comment by jwhitak** [comment]
Better change would be to have a differently-sprited plastic bag, perhaps something like a mail carrier? Perfect for gathering up small items from tables, putting on your belt, holding a couple of tools... but also not stepping on the assistant plastic bag motif.

**Comment by Kurfursten** [comment]
Instead of a plastic bag, bartender should spawn with a sixpack of beers in hand. He comes to the party prepared.

**Comment by DeityLink** [comment]
don't we have an actual sixpack box item? I'm sure I saw the sprites for it.

**Comment by Kurfursten** [comment]
> don't we have an actual sixpack box item? I'm sure I saw the sprites for it.

Yes I was referring to /obj/item/weapon/storage/fancy/beer_box

**Comment by pedr69** [comment]
not sure about barman and library because i don't play those
but the cargo bag is very useful

**Comment by Eneocho** [comment]
Instead replace it with the sixpack for the bartender, a random library book inhand for the librarian (something to read on the shuttle trip over) and a reskinned bag for the cargo tech.

**Comment by DeityLink** [comment]
I always discard mine instantly when I play bartender (granted I haven't in a long time, but still that always felt like an oversight)

**Comment by NigglyWiggly** [comment]
I still miss the days when I could use the plastic bag to store all my tools as an invisible belt that didn't have another sprite on the icon

**Comment by ManopolisJones** [comment]
This shall make playing as a backpackless cargo tech much more difficult

**Comment by Eneocho** [comment]
First they came against security and I didn't speak cause I don't play security.
Then they came against shroom smoking and I didn't speak because I don't play shrooms.
Now they come for the cargo platic bags, and there's no one to left to speak for cargo.

**Comment by Kurfursten** [comment]
I can't believe we repobanned everyone who supported shroom smoking so they can't vote anymore... Brutal

**Comment by Kurfursten** [comment]
Never changed to give bartender his sixpack, heartbreaking.

**Comment by pedr69** [comment]
WHERE ARE THE CARGO BAGS NIGGERS

**Pull request merged**
