### PR TITLE
Gondolas having built-in radios is now a subtype

### PR DESCRIPTION
**Pull request by Kharkov72**
Rather than every gondola being a walking talking speaker now it's up to the admin's choice, for things such as movie night.

:cl:
 * tweak: gondolas with build in radios are now a subtype

### CODE REVIEW

**Comment by MadmanMartian** [comment]
The reason behind them being radio transmitters was a request. People wanted them to play music as they watched, like those gondola music webms. Probably for the best it's disabled as I'm not sure if it even works.

**Comment by Kharkov72** [comment]
Hmm, that's fair enough, but it interferes with things like movie night for gondolas.
I think I'll make radio gondolas a subtype instead.

**Comment by SonixApache** [comment]
I tried messing with them and I couldn't get them to work. I wish they came with instructions.

**Comment by Kurfursten** [comment]
Okay this is fine but you haven't made a non radio version

**Comment by Kharkov72** [comment]
it's the normal one.
normal one is radioless, gondola/radio has the radio

**Comment by Kurfursten** [comment]
Yeah, I see it now, it was defined again in the other file. Which is a BIG YIKES from me personally. (not your fault)

**Comment by Kharkov72** [comment]
want me to condense them? because I don't see any reason for them to be separate anyways

**Pull request merged**
