### PR TITLE
adds fannypack, 1-slot webbing

### PR DESCRIPTION
**Pull request by SonixApache**
featuring codersprite from the nexis may cry series
fannypack
Priority assistants come equipped with a fannypack that has an assistant card in it. 
The card functions like a holobadge, except for assistants. Idea by @9percents.
ascard
ascard
item sprite provided by @JTGSZ - if anyone wants to take another go at the rest be my guest

:cl:
  - rscadd: added fannypack accessories, available from biogenerators and for priority assistants

### CODE REVIEW

**Comment by beesil** [comment]
👍 to silly fanny pack, 👎 to junk card

**Comment by Kurfursten** [comment]
It seems like people were against the idea of priority joins actually getting useful items but then again no one ever prioritizes assistants so it's probably okay.

**Comment by SonixApache** [comment]
@beesil I have made it so you can recycle the junk card.

**Comment by Kurfursten** [comment]
Conflicts due to Christmas jingle bells PR

**Pull request merged**
