### PR TITLE
Adds a karmotrine drink reaction.

### PR DESCRIPTION
**Pull request by Eneocho**
Currently, if you have both Waifu and Husbando inside you'll burn through them simultaneously, turning back and forth until one of them runs out.
This adds a drink made when mixing Waifu and Husbando called Tomboy. This drink will turn you into a female like Waifu, but give you a butler suit like Husbando does.
Tomboy takes priority over Waifu and Husbando, so you won't turn back and forth if you're metabolizing one of them and Tomboy simultaneously.
tomboy resized

:cl:
 * rscadd: Tomboy, a Karm-based drink made by mixing both Waifu and Husbando.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
okay but what happens when it happens to females, guy but in dress?

**Comment by Eneocho** [comment]
> okay but what happens when it happens to females, guy but in dress?

No, just gives you a butler suit, though that's a decent idea.

**Comment by gurfan** [comment]
<Heavy's Voice>: NO!

**Comment by SonixApache** [comment]
mixing the two evils should leave you a naked neuter

**Comment by jwhitak** [comment]
What if they have this new chemical and an amount of husbando or waifu in them? Or a chemical that prevents reactions and you drink all 3 at once?

**Comment by Eneocho** [comment]
> What if they have this new chemical and an amount of husbando or waifu in them? Or a chemical that prevents reactions and you drink all 3 at once?

No reaction. Husbando and Waifu will do nothing if you have tomboy on you.

**Comment by Kurfursten** [comment]
The pink pixel at the top left of the iris is really bugging me

**Comment by Eneocho** [comment]
Waifu (Pink) has a blue pixel. Husbando (Blue) has a green pixel. It thus follows that Tomboy (Green) would have a pink pixel.

**Comment by Kurfursten** [comment]
You do realize that's an artifact from when I downscaled an anime eye I stole from the internet and then didn't notice the pixel because it was close to the outline of the iris, right?

**Comment by Eneocho** [comment]
I do, but I like the thematic consistency, though if you insist I can edit it out.

**Comment by Kurfursten** [comment]
I don't insist, but I do appreciate it

**Comment by Theophrastus1** [comment]
Dangerously close to femboys

**Comment by Killette2** [comment]
Can it make catbeast femboys instead to make them even more valid?

**Comment by SECBATON-GRIFFON** [comment]
> Dangerously close to femboys

that was my idea for what to call it if it did it to males but there's probably no way it'd pass

**Comment by WindowsErrors** [comment]
image

**Comment by Theophrastus1** [comment]
> > Dangerously close to femboys
> 
> that was my idea for what to call it if it did it to males but there's probably no way it'd pass

The correct term there would be tomgirl or something. Same thing.

**Comment by Theophrastus1** [comment]
https://www.youtube.com/watch?v=XdqCY_DBbs0

**Comment by ManopolisJones** [comment]
I might've called the mixing of two gender bending fluids "Troonshine" but I guess this works

**Comment by Kurfursten** [comment]
Conflicts

**Comment by Eneocho** [comment]
@Kurfursten not sure why is the thing still conflicting. I'll remake this.

**Pull request closed without merging**
