### PR TITLE
completely fucking BUTCHERs the ~L0re~

### PR DESCRIPTION
**Pull request by 9600bauds**
The game's events now take place in the year 2525.

### CODE REVIEW

**Comment by kol1th** [comment]
MY IMERSIONS

**Comment by Ephx1** [comment]
I WAS LOOKING FORWARD TO 2561 YOU DICK

**Comment by Exxion** [comment]
But why

**Comment by 9600bauds** [comment]
https://www.youtube.com/watch?v=WhNM2K8cmU8

**Comment by Exxion** [comment]
I mean OTHER than memes

**Comment by 9600bauds** [comment]
Why not

**Comment by Exxion** [comment]
It's fun to meme on people who think this is already the case

**Comment by AI-Is-Rogue** [comment]
I dislike this.

**Comment by ghost** [comment]
It'll just become 2526 in 18 days. Is it worth changing the date for 2 weeks worth of a meme?

**Comment by 9600bauds** [comment]
It's just a prank bro

@SolariousGabriella 
It gets set to perma2525

**Comment by Huuuuuuuuuuugo** [comment]
rrrrrrreeeeeeeeeeeeeeeeeeeeeeeEEEEEEEEEEEEEEEEEEEEEEEE**EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE**

**Comment by 9600bauds** [comment]
Changed to something everyone will find agreeable

**Comment by Kammerjunk** [comment]
HOW I WISH I WAS IN SHERBROOKE NOW

**Comment by Praecordia** [comment]
our team of certified loremasters work 23 HOURS A DAY on producing quality lore™ for our server, and _this_ is how you repay them?

**Comment by 9600bauds** [comment]
I can arrange the hours in a day too

**Comment by 9600bauds** [comment]
https://www.youtube.com/watch?v=ZVc15-01RvM

**Pull request closed without merging**
