### PR TITLE
gives glock a proper name in code

### PR DESCRIPTION
**Pull request by 9percents**
it just infuriates 
due to glocks already present on certain maps, it also updates maps
[consistency] [general]

ss+(2019-08-18+at+06 14 34)

### CODE REVIEW

**Comment by Kharkov72** [comment]
based and readable-code pilled

**Comment by Irradiation** [comment]
Nice changelog my dude

**Comment by DrSnips** [comment]
Based and did stuff and did other stuff pilled.

**Comment by Kurfursten** [comment]
This is getting a speedy merge for touching maps and also being a backend change

**Pull request merged**
