### PR TITLE
Xenoarch excavation drill split.

### PR DESCRIPTION
**Pull request by DrSnips**
The current state of the excavation drill you can make from the protolathe is a joke right now, it digs slower than the handpicks (diamond mining drill is instant), and provides no buff to your equipment despite it costing silver AND diamonds. I have split the excavation drill into two hand drills now, the basic and diamond excavation drill.
*Basic excavation drill:
metal exca drill
+Costs less, only metal and glass. (About the same cost as the basic mining drill)
+Lower research needed for it
-Same shit 1-30cm range
-Same slow speed
*Diamond excavation drill:
diamond exca drill
+Dig range is 1-100cm
+Faster (Slightly faster than hand picks, so mid digging speed)
-Cost is slightly higher than the old exca. drill (roughly 60% cost increase)
-Needs the higher research
:cl:
* tweak: Excavation drill replaced with two types of drills.
* rscadd: Diamond excavation drill, faster and longer than the basic version. Costs a bit more than the old one.
* rscadd: Basic excavation drill, costs a bit less but the same slow speed and low range as the old one.

### CODE REVIEW

**Comment by N3X15** [comment]
You did something to the DMIs, show your work.

**Comment by DrSnips** [comment]
Done in the op. It's grey for the inhands too, nothing special.

**Comment by DrSnips** [comment]
@N3X15 Mind removing the needs pics tag?

**Comment by N3X15** [comment]
Mind being patient while I do other things like sleep?

**Comment by DrSnips** [comment]
I only code at night and when sleep deprived. You saying that's not normal for coders?

**Pull request merged**
