### PR TITLE
Cleans up Ministation for server play

### LINKED ISSUE #9646: Add Ministation to map pool for lowpop
It still works and compiles (and if it doesn't it won't take too much work to fix) and I've seen a lot of support for it in the thread. At the very least it'll split the vote and lead to fewer rounds on taxi (which seems best played in moderation).
Based on remarks in #9640

### PR DESCRIPTION
**Pull request by xpcybic**
ministation2
(Click for full size)
[Older image](https://cloud.githubusercontent.com/assets/15971146/14875495/20b89eba-0cc0-11e6-9221-3c7d6189f33d.png)

Cleans up the already-present Ministation to make it suitable for adding to the map vote. A smaller, simplified station designed for lowpop, it features a two-man command structure, a reduced job selection with multiple-duty jobs, simpler areas and powernet, a Z-level 1 asteroid field, and two tons of CUTE.
- Ported Ministation configs from TG, with minor changes to fit the vg codebase.
  - These jobs are disabled, some of them having roles filled by other jobs: chef, botanist, QM, miner, mime, librarian, IAA (and lawyer), chaplain, CE, atmos tech, CMO, geneticist, virologist, RD, roboticist, HoS, warden, cyborg, paramedic, mechanic.
  - These jobs have their player caps reduced by one: MD, chemist, engineer, sec officer, scientist, MoMMI.
  - These traitor items are disabled or have an increased TC cost to discourage lowpop murderbone (can be added to/removed from as needed):
    - Fully Loaded Revolver: 7 -> 10
    - Energy Crossbow: 5 -> 8
    - Energy Sword: 4 -> 7
    - Paralysis Pen: disabled
    - No-Slip Syndicate Shoes: 2 -> 5
    - Composition C-4: disabled

Other changes:
- Medbay: added body scanner, bone setter, bone gel, Fix-O-Vein, defib, and crew monitor.
- Science: added an autolathe board to R&D, made the server room its own area to prevent atmos problems..
- Engineering: added two solar arrays. Tweaked the TEG room to get the burn chamber injectors to work (toggle them from the computer).
- Security: added two ion rifles to the armory.
- Service: added jukebox, plant bag, removed table between bar/botany.
- AI satellite: fixed telecomms, replaced cyborg spawns with a MoMMI spawn.
- Details: desk bells, Dan's and Groans, random vault spawn areas.
- Changed shuttles to use docking ports, added lights to shuttles.
- **Update:** additional maint, tweaked pipe network, virology, chapel, several minor tweaks based on feedback.
- **Update 2:** plants, more stuff in maint, bioprinter/prosthesisfab, moved barsign so it can be used

Known Issues:
- The default TEG setup (using the provided instructions) does not function. Pushing #8771 should fix it.
- Traitors can be given objectives to steal items which aren't on the map, such as the CMO's jumpsuit. I couldn't quite figure out how to disable them in the same way as the uplink items. This is minor since the objectives are guidelines anyway.
- To load the map in Dream Maker yourself, tick ministation.dm beforehand and Build -> Update. The telecomms objects are in with this .dm's include files so the map will not load otherwise.

Closes #9646

### CODE REVIEW

**Comment by Exxion** [comment]
Maint is powered? Interesting.

**Comment by 9600bauds** [comment]
>kitchen and botany

>chef and botanist are disabled

????

**Comment by Exxion** [comment]
Botany is there, just not botanists
The bartender handles the entirety of service
I look forward to the challenge

**Comment by Probe1** [comment]
Spot check the gas miners for me and make sure they're not miner/air instead of oxygen and nitrogen.

**Comment by 9600bauds** [comment]
Immediate concerns: ~~Armory doesn't have rwalls~~, in fact the usage of rwalls in general seems completely arbitrary

Maint seems to be directly clumped into the hallways with the actual departments on the outside. From the central hallway, it's featureless, doorless hallways in every single direction except the bar. But I realize this is more of a design concern 

~~There's a Chemmaster in surgery for some inexplicable reason~~

~~Cloner can be made smaller at no loss to alleviate boxiness~~

There doesn't seem to be nearly enough hardsuits and they're all in the same place, you can see where this goes also are the blueprints in EVA?

**Comment by Probe1** [comment]
image

random disposal pipe?

**Comment by Probe1** [comment]
image

Double check this is an always on injector at telecomms

**Comment by Probe1** [comment]
image

Marauder at telecomms

Remember when we fixed most of those?  they were EVERYWHERE.  God that was so long ago that we did that.

**Comment by Probe1** [comment]
Is there supposed to be a radio transmitter at southeast telecomms?

**Comment by 9600bauds** [comment]
~~Detective is literally unplayable without a hi-res scanner console, lacks a detective locker which also has essential shit for detective including the scanner~~

~~Unless that's the IAA's office~~

**Comment by Probe1** [comment]
Add 1 atmos and engineering SSU to engineering.

**Comment by 9600bauds** [comment]
~~Maybe a sleeper at Cryo~~

**Comment by 9600bauds** [comment]
What is that white vendor at the HOP?

**Comment by Probe1** [comment]
Its the old secvend that mini had.  

Drop the sleeper at cryo.  Add a mancrowave.

**Comment by Probe1** [comment]
:+1: really love the conveyors in toxins

**Comment by Probe1** [comment]
>Ore redemption machine outside science
Move that useless ass copy machine to maint or cargo bay and put it there.

**Comment by 9600bauds** [comment]
I'm not sure how no exosuit fab plays out for borgs needing boards but add a borg charger somewhere in science or confused borg players will hate you

Also where is the borg control console? For when a borg gets emagged and lowpop murderbones everything?

Unless borgs are disabled which would be fantastic

**Comment by Probe1** [comment]
image

What are these grilles hooked up to?

**Comment by Probe1** [comment]
@9600bauds I think sili's are disabled.

**Comment by Exxion** [comment]
Borgs are disabled

And @Probe1 what's the story with the Marauders?

**Comment by Probe1** [comment]
who fucking knows lol somehow porting replaced all obj/bed/chair/office/dark with dark marauders or gygax's or maulers or some shit.

**Comment by 9600bauds** [comment]
I foresee issues with people wanting to pay botanist/chef but not knowing barkeep is the unintuitive and less popular step-up, personally I would reenable chef

**Comment by xpcybic** [comment]
@Exxion not exactly, the APCs in maint are connected to the departments they are next to. Maint itself is mostly part of the hallway area.
@Probe1 miners are both correct. The injector seems to be off, I replaced it with a regular vent.
Funny, I looked right at that marauder like ten times without realizing that this happened before and it's not supposed to be there.
The radio is there because that's also the AI spawn. I might move it to the empty room where the TG gravity generator would be.

**Comment by 9600bauds** [comment]
Basketball in dorms is REALLY fucking OP, are you gonna give them a red phone next you madman?

**Comment by Probe1** [comment]
get your mitts off the bball bauds

CHAOS DUNK
CHAOS DUNK

**Comment by 9600bauds** [comment]
~~I don't see any starting metal/glass for cargolathe~~

**Comment by 9600bauds** [comment]
~~no oxygen canister in EVA REEEE~~

~~Actually, there are no oxygen tanks either~~

**Comment by xpcybic** [comment]
@9600bauds 
The lack of rwalls I think was probably because the map is small enough that it's easier to get caught breaking into places, but I can add them where they make sense if that isn't enough
The chemmaster is actually a PanD.E.M.I.C :question: 
Crammed in a scanner console, there's already a detective cabinet
Added sleeper to cryo
The white vendor is a PTech, for PDA cartridges
I attempted to make disabled jobs appear as unavailable like how trader does for non-vox but couldn't, then decided that it wasn't a huge concern and people would go to the HoP if they really wanted into an inactive job like chef/botanist
What about the basketball? :confused:
Added the cargo supplies and O<sub>2</sub>

**Comment by invoid9** [comment]
I think the medbay fridge is way too far from the entrance, it's also awkward to move from the cmc to the entrance to pick up patients. I think it'd be much better if that little room in lobby with the cmc swapped places with the entrance. That way, the entrance is close to the fridge, cryo, scanner instead of just close to the scanner and some random storage equipment. 

Surgery also seems too big. I don't like having doors going into cryo, and would rather it open, but it doesn't really matter. Is that a hypospray in the storage room (oh yeah, makes sense since no cmo, nevermind LMAO)? I don't see any bloodbags or iv drips, but that might just be a design choice? Paramedic doesn't seem to be disabled but also doesn't have a spawn/station?

Otherwise I really like it, thank you for your hard work as well!

**Comment by Exxion** [comment]
Also I have to disagree with Bauds on re-enabling chef, as there is no real kitchen, just a bar backroom with cooking equipment
But I see no problem with re-enabling botanist if people want it

**Comment by ghost** [comment]
Why would you disable chaplain? That's a kinda needed job against some antags (Vampire, cult)

**Comment by SysadminJeroen** [comment]
Could it be possible to disable certain types of antags on certain maps?
Like Vamp and cult on Mini.

2016-04-28 11:44 GMT+02:00 Skullyton notifications@github.com:

**Comment by Exxion** [comment]
Cult wouldn't happen on Mini anyway because Mini would be lowpop-only and Cult is mid-highpop-only
I'm not sure what the population limit is for vamps, though

**Comment by FudgePucker** [comment]
Deadpop rounds would be fixed by putting a marauder in every room :^)

What about the off station zlevels?

**Comment by ihadtoregisterforthis** [comment]
PIPE IN WALL

DESIGNATED LOWPOP STATION

**Comment by CptWad** [comment]
You are using the improper lamarr cage at the bridge
need the same one as the caplaser is in

**Comment by ihadtoregisterforthis** [comment]
- Rogue wire on detective's office
- No APC on detective's office
- Atmos waste on maint
- firelocks not on doors, which looks nicer

**Comment by Ephx1** [comment]
More firelocks.
Three broken windows means you can depressurize pretty much all hallways except for security, unless that's the point.

Also the firelocks just before the door and not on them is ugly for solitary firelocks, it works for the engineering hallway and EVA though.

**Comment by 9600bauds** [comment]
mspaint_2016-04-28_12-10-53
This big spot of uselessness bothers me, I think you could do away completely with most of the maint around EVA and sneak in a small chapel or something

**Comment by PJB3005** [comment]
Maint looks too clean.

**Comment by ihadtoregisterforthis** [comment]
On the map
- Rogue wire on detective's office
- No APC on detective's office
- Atmos waste on maint
- Firelocks not on doors, which looks nicer
- No firelocks on the halls
- A lot of pipes under a lot of walls
- A lot of vents and scrubbers under machinery and consoles
- Incomplete wire near the armory
- Ore redemption machine which I believe doesn't work
- No virology
- Zero maint on science+medbay

The bartender having to do all the work sounds like a bad idea. Give more variety to cargo, instead of all techs make it one tech, a miner and a QM, or something like that. No cyborgs and no mechs allowed sounds dull. Virology installations are needed to cure those random event viruses. Where does the AI go, if is there one? And what is that empty room on the satellite for?. No real reason to remove mime. Full dependency on a faulty soon-to-be-nerfed engine can be problematic; the solars only recieve power little more than half the time.

**Comment by Exxion** [comment]
If memory serves and it wasn't moved, the AI sits in a little corner in that ship in the bottom right

And the bartender could totally handle doing all of service during deadpop. ~~Not like anyone except me actually plays bartender during deadpop anyway~~
I wouldn't really be opposed to adding a botanist or two, but please no chef unless an actual kitchen is mapped in

**Comment by FudgePucker** [comment]
SME takes up less room than the TEG.

I can make a SME in a 4 by 4 area, before layered pipes. 

You can use the area saved for a larger atmospherics.

**Comment by PJB3005** [comment]
Also, needs a lot more maintenance.

There's a lot of places to put some, even if it's just meteor protection.

**Comment by 9600bauds** [comment]
The underlying problem with this maint is that for some reason there's big chunks of maint with no seeming purpose at the heart of the station, and all the departments are on the outer ring

**Comment by xpcybic** [comment]
Going to go ahead and add a small chapel somewhere since cult/vamp can still be bussed in. For similar malf-related reasons I'll add one borg spawn and find somewhere to put a small robotics workshop.
I'll also wrap some more maint around everything, a lot of rooms are breaking the unspoken "two ways in/out" rule
@ihadtoregisterforthis uuughhhhhh don't make me fix more pipes alright fine I'll fix more pipes

**Comment by 9600bauds** [comment]
No leave it without silicons
It's perfect

**Comment by carshalash** [comment]
Isn't the TEG still broken?

**Comment by Ephx1** [comment]
Going to have to agree with bauds here, silicons would be absolutely miserable on this map.
Not the silicons themselves, but anyone trying to have fun.

**Comment by xpcybic** [comment]
Very well I'll leave borgs out
@carshalash yes the TEG is still broken (but won't be forever), I added the solars to make up for it

**Comment by ihadtoregisterforthis** [comment]
Leave roundstart borgs out, but what about things like borging, robot limbs and high research?
A single robotics machine in a corner is enough.

**Comment by xpcybic** [comment]
Updated first post with a new render (based on most but not all feedback)

**Comment by 9600bauds** [comment]
When we said mini chapel, you really took it to heart

**Comment by xpcybic** [comment]
I think it's p kawaii tbh
It can go only slightly bigger than that

**Comment by 9600bauds** [comment]
The operation console needs to be right next to the operating table to work I think

**Comment by Exxion** [comment]
It's hilarious and I love it
Looks like the chaplain will have to be a street preacher though

**Comment by 9600bauds** [comment]
I just had the BEST IDEA

Mini-Holodeck

**Comment by 9600bauds** [comment]
Potted plants maybe?

**Comment by 9600bauds** [comment]
How much metal and glass is there at engineering? Also I'm not sure if RPDs spawn in the lockers or not

**Comment by xpcybic** [comment]
@9600bauds four stacks each, and I threw in an RPD/tile painter

**Comment by iwillkillmyself** [comment]
Neat, thanks for making lowpop great again

Also medbay lacking bioprinters
Also can't you decrease the required_players_secrets and required_enemies for cult nukeops and rev game modes like with the jobs?

**Comment by xpcybic** [comment]
Looks like I can but I'm not sure if they should go much lower. Rev might not work too well since only cap and HoP are enabled. Nukeops MIGHT work with 3 syndies but I'll save it for a later pr so I can spend some more time looking into it.

**Comment by xpcybic** [comment]
Updated again. Any other minor things I missed? If not then this is :star:ready2merge:star:

**Comment by ihadtoregisterforthis** [comment]
What do the other z-levels look like?

**Comment by xpcybic** [comment]
Four z-levels total. Station, centcomm which is just the lower half of box's, empty level with DJ sat and clown roid, and asteroid which is entirely plain and not worth a full size shot.
screenshot 2016-04-29 18 25 36
screenshot 2016-04-29 18 26 11

**Comment by FudgePucker** [comment]
Where do derelict mommis spawn?

**Comment by Ephx1** [comment]
They don't

**Comment by FudgePucker** [comment]
:/ Just add in the little half derelict from taxi then.
Sometimes you just wanna autism latejoin.

**Comment by Probe1** [comment]
you can't have a low pop map and also accommodate for everyones desires or else you wind up with taxi.

**Pull request merged**
