### PR TITLE
Disposal bin shortcuts

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
## What this does
alt click to toggle flush engage, click drag from to adjacent tile to eject contents to it

## Why it's good
[qol]

## How it was tested
alt clicking the disposal bins and click dragging from em, while inside the bin and into dense turfs, all done while adjacent to it

## Changelog
:cl:
 * rscadd: Alt clicking now toggles the engage on flushing for disposal bins, if the user is not inside the bin itself.
 * rscadd: Click dragging from a disposal bin to an adjacent, non dense turf now ejects the contents onto it.

### CODE REVIEW

**Comment by Eneocho** [comment]
huh?

**Comment by SECBATON-GRIFFON** [comment]
> huh?

still unsure if it has the ok or not, feature freezes in the past (from 2016 or so) did allow this though?

**Comment by west3436** [comment]
reopen it coward

**Comment by SonixApache** [comment]
this violates your parole

**Comment by Eneocho** [comment]
> this violates your parole

free this man already, he's been a goodboy(TM)

**Comment by SECBATON-GRIFFON** [comment]
parole's up, welcome back

**Pull request merged**
