### PR TITLE
Convert all maps to TGM format

### PR DESCRIPTION
**Pull request by DamianX**
TGM is a format that puts every single little thing on its own line so that we don't get mapping conflicts anymore unless the exact same object is edited by two PRs.

### CODE REVIEW

**Comment by Exxion** [comment]
I thought TGM shit the bed with large maps
Did that get fixed?

**Comment by DamianX** [comment]
Shit the bed in what way? I just converted box and it seems to work.

**Comment by Exxion** [comment]
I don't recall exactly. There was something that would crash sometimes.
If they're using it actively that was probably fixed

**Comment by Kurfursten** [comment]
New mapping priority
#27360
#27356
#27287
**THIS PR**

**Comment by Kurfursten** [comment]
Shifty yields priority to you

**Comment by DamianX** [comment]
The map and icon diff bots understandably don't bother to parse this diff, but travis succeeded.

**Pull request merged**
