### PR TITLE
Fixes #8111, PDA messaging server now restarts after regaining power …

### LINKED ISSUE #8111: When becoming unpowered (through event or otherwise) PDA messaging servers do not turn back on
How to test
1. Turn off power to the telecomms room
2. Turn it back on
3. Watch as the rest of telecomms returns to functionality while the PDA messaging server stays off waiting for a player to fix it

This is actually a really old bug I never arsed myself to call in till just now

### PR DESCRIPTION
**Pull request by ghost**
…(unless manually disabled)

### CODE REVIEW

**Review by PJB3005 — DISMISSED** [review]
Don't do this, make it maintain `active` even when losing power but simply make it not do anything when `NOPOWER`.

In fact make a proc for it.

**Comment by 9600bauds** [comment]
Screw that, I'd have to go through every instance of things that look through PDA messaging servers.

I even checked all the other telecomms machinery and they have a manuallydisabled var analogue, too.

**Comment by PJB3005** [comment]
"I'm lazy" is not a valid excuse.

Because other telecomms machinery is stupid doesn't mean your new code can be stupid.

**Comment by 9600bauds** [comment]
Just how is it stupid?

**Comment by PJB3005** [comment]
Because an extra var to track this kind of thing is redundant, as I've outlined with my solution?

**Comment by 9600bauds** [comment]
We're racking our brains over one variable in one machine of which there exists one in the station, the lack of which caused this problem in the first place, this is probably more inconsequential than TG's typeless loops meme

**Comment by PJB3005** [comment]
> the lack of which caused this problem in the first place

Wrong

And yes, upholding high quality ™️  standards at all times is a good thing.

**Comment by 9600bauds** [comment]
\>cheapening out in ONE VARIABLE for no reason other than to cheapen out in ONE VARIABLE

the

very

best

it's called "premature optimization" and it's an anti-standard, you know it, I know it

**Comment by PJB3005** [comment]
This isn't premature optimization though.

This isn't about performance, there's no need for this variable to exist other than shit code, and shit code isn't an excuse.

**Comment by 9600bauds** [comment]
No, "it uses one more variable than theoretically necessary" doesn't make code shit

once again you are overblowing something tremendously petty

is this even worth arguing about

**Comment by PJB3005** [comment]
> theoretically. 

I could agree here in some other situations but this one? Not really no. `active` should be a "is this damn thing enabled, ignoring power state", stat is for power state. By not fixing it you're now stuck with 3 values: is it on, is it on and is power on, is power on. It's redundant overlap.

But yes, I won't argue anymore.

**Comment by 9600bauds** [comment]
>BROKEN is coincidentally 1 it seems.

🎉

**Pull request merged**
