### PR TITLE
Snowmap Fixes 1: The Awakening

### PR DESCRIPTION
**Pull request by Kharkov72**
Oh boy here we go.
LOADS of fixes, everything outlined in this:
[snowmap shit - Copy.txt](https://github.com/vgstation-coders/vgstation13/files/3517190/snowmap.shit.-.Copy.txt)

However, here's some highlights:

Reworked AI upload so you do not need to go through telecomms, reducing some of the r-walling, and using fences instead of grills.
rework1

You can now enter the armory through some shutters.
rework2

Waste now actually vents to space, along for some more space-room for autism.
rework3

Cat.
rework4

[snowmap]

Other, more minor updates:
-Removes the mapped in goonsat as it's a vault now, should help with loadtime.
-Adds a refinery between the science outpost and the trader outpost
-Expands engineering storage slightly, adds some emitters to it

:cl:
 * rscadd: Oh the weather outside is frightful~

### CODE REVIEW

**Comment by Kharkov72** [comment]
Oh and uh
closes #23907 closes #23913

**Comment by Durgen** [comment]
Are those starscreens in the AI chamber or the other sort

**Comment by Kharkov72** [comment]
@Durgen starscreens

**Comment by SonixApache** [comment]
wow that armory is really wonky

**Pull request merged**
