### PR TITLE
Readds new nuke sprite

### PR DESCRIPTION
**Pull request by clusterfack**
Readds fancy nuke sprite by repth from #5931

Old on top new on bottom

### CODE REVIEW

**Comment by DrCelt** [comment]
AAAAAAAAAAAAAAAAAA

**Comment by CptWad** [comment]
I mean I hate change but :+1: since its acutally a quality sprite and the nuke sprite is a bit shit

**Comment by Exxion** [comment]
Something *really* bothers me about the shape of the nuke in the new sprite
It looks like a shape that would look right from the side but would look rectangular from the front

**Comment by clusterfack** [comment]
Someone should readd the old sprite as a poster, because thats what that one looks like.

**Comment by clusterfack** [comment]
Besides I held a lot of votes for this in the past and people overwhelmingly like it

**Comment by Exxion** [comment]
I don't mind changing it, but there's something not quite right with this particular sprite
I don't really care that much though so whatever

**Comment by Intigracy** [comment]
You can only add the new sprite if you revert hypothermia.

Sorry bud thems the rules.

**Comment by 9600bauds** [comment]
I don't like it

**Comment by PJB3005** [comment]
Yeah it looks oddly out of place, even though a lot of SS13's perspective is dimetric.

**Comment by Probe1** [comment]
@Exxion 

>I don't mind changing it, but there's something not quite right with this particular sprite
I don't really care that much though so whatever

It's the sprites perspective.  But when I said to yank these, it was to pull the medhud sprite change that only like 1:10 people liked.  No one was strongly opinionated about the nuke.

**Comment by Intigracy** [comment]
@Clusterfack add the image to the OP.

![ ] (http://i.imgur.com/gwdXDYo.png) with no spaces.

**Comment by gbasood** [comment]
I might be wrong, but isn't this the perspective that fuel tanks/water tanks have?

**Comment by ihadtoregisterforthis** [comment]
I think that it's too bright to represent the game-ending roller cart that it is.

**Comment by dylanstrategie** [comment]
Dump the outline completely, I for one don't want that dumb shit in the game

Also fix the rolling cart's color, too bright

**Comment by clusterfack** [comment]
Dylan you know I'm not going to do that, if you want to do that you should do that but I didn't even sprite it.

**Comment by ihadtoregisterforthis** [comment]
How is this not on the changelog

**Comment by clusterfack** [comment]
It is, months ago.

**Comment by ihadtoregisterforthis** [comment]
Except it's not

**Comment by clusterfack** [comment]
It was reverted merely because it was bundled with the hud change everyone hated

**Comment by Probe1** [comment]
image

**Comment by Intigracy** [comment]
Do you like it:
Yes  
Yes, but it could be tweaked (for those who don't like the outline when it's active)
No
I'm Indifferent

**Comment by NigglyWiggly** [comment]
I feel bad about it and all.
Like, I think the sprite looks great, but I feel like it looks really out of place and I can't quite put my finger on why.

**Comment by Intigracy** [comment]
#9136

**Comment by PJB3005** [comment]
@NigglyWiggly exactly my opinion, though I feel @Intigracy's change makes it way better.

**Pull request merged**
