### PR TITLE
Revert "Sundays in April are also April Fool's Day"

### PR DESCRIPTION
**Pull request by SonixApache**
Reverts vgstation-coders/vgstation13#36262
image

### CODE REVIEW

**Comment by kilozombie** [comment]
It seems like it was worth a try but April Fool's is too gunky
Sundays are highpop days, we shouldn't sabotage them

**Comment by Eneocho** [comment]
would moving it to mondays be better? cause mondays are not that highpop but it would still let the extra april fools day happen.

**Comment by gurfan** [comment]
Moving it to April 1st would be better, that seems like a good day for this sort of thing.

**Comment by Theophrastus1** [comment]
Yeah, I'm of the mind that I understand that you wanna see stuff that isnt usually seen used more often, but this just gunks everything too badly all together

**Comment by SonixApache** [comment]
> would moving it to mondays be better? cause mondays are not that highpop but it would still let the extra april fools day happen.

no days would be better
admins can just force april fools as a holiday if they want a zany round

**Comment by DrSnips** [comment]
It seems to me like players would just pick and choose when they want April Fools. A "grass is greener on the other side" type of deal.
I'd propose that it launches every other round on Sundays rather than at random. The fool rounds don't often last very long anyway.

**Pull request merged**
