### PR TITLE
Mothership Uniforms: Fixes Soldier Uniforms Not Coming In Shipments

### PR DESCRIPTION
**Pull request by Optimism333**
## Oops ##
- I knew that it felt like soldier uniforms were never actually coming. I missed a list addition so that the soldier uniforms would actually spawn. This fixes that.

[bugfix]

:cl:
 * bugfix: Soldier uniforms now actually come with mothership uniform shipments

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you fix #33014 as well?

**Comment by Optimism333** [comment]
> Can you fix #33014 as well?

I can try. Where do you figure I should be looking? I don't know where in the code or when crate forwarding was added.

**Comment by Eneocho** [comment]
> > Can you fix #33014 as well?
> 
> I can try. Where do you figure I should be looking? I don't know where in the code or when crate forwarding was added.

Crate forwarding was added in https://github.com/vgstation-coders/vgstation13/pull/31967. Not sure if it will help since I get an error 500 when looking at PRs made by kanef (account deleted). 
You can take a look at https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/cargo_forwarding.dm as well.

**Comment by Optimism333** [comment]
> > > Can you fix #33014 as well?
> > 
> > 
> > I can try. Where do you figure I should be looking? I don't know where in the code or when crate forwarding was added.
> 
> Crate forwarding was added in #31967. Not sure if it will help since I get an error 500 when looking at PRs made by kanef (account deleted). You can take a look at https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/cargo_forwarding.dm as well.

Okay, thanks. Not being able to actually look at the PRs is unfortunate, but I'll see what I can do.

It will probably be a separate fix, though.

**Comment by Eneocho** [comment]
I think the error 500 is due to us being a hidden (by github) repo, so the whole backend deal to store the PRs of deleted accounts broke. You can easily see the PRs made by old accounts that got deleted before we got hidden, but the ones made by accounts that got deleted after being hidden (such as kanef) are nowhere to be found.

**Pull request merged**
