### PR TITLE
Fixes mushroom suits not spawning in the right place

### PR DESCRIPTION
**Pull request by ShiftyRail**
Probably because the spawner can only handle what it's given directly.

### CODE REVIEW

**Comment by beesil** [comment]
Box and packed use `/obj/structure/closet/vox_raiders/` while every other map uses `/obj/structure/closet/vox_raiders/trader/`, so add it to both.

**Comment by ShiftyRail** [comment]
Curses

**Comment by SonixApache** [comment]
The better solution would be to just make box and packed use the right closet.

**Comment by ShiftyRail** [comment]
That would require me to use the map cleaner
I can't code tommorow and the next day so you'll have to wait until Tuesday

**Comment by SonixApache** [comment]
That's fine, we can wait, or you can just scream at the folks in the mapping channels. Do it the right way tbh.

**Comment by Exxion** [comment]
No it wouldn't
Just open the map in a text editor and change the paths

**Comment by ShiftyRail** [comment]
Did the needed changes in the brutal fashion as Github can snitch now

**Pull request merged**
