### PR TITLE
Water puddles now freeze into ice at 0C and below.

### PR DESCRIPTION
**Pull request by ghost**
I'll clean it up for non-simulated turfs later, just wanted to get this out here as a potential simple but controversial change. Yes, mops will create ice if you mop in a cold room. It's the same ice puddles that cryotheum produces.

:cl:
 * rscadd: Ice puddles now form whenever water puddles exist in a 0C or colder atmosphere.

### CODE REVIEW

**Comment by Eneocho** [comment]
frozen lube puddles incoming

**Comment by Eneocho** [comment]
How long do the ice puddles last? Indefinitely until heated or do they "vanish" eventually? Can they be dried with sodium poly?

**Comment by smashedandslammed** [comment]
God no, we have enough feature bloat with temperature code.

**Comment by ghost** [comment]
> How long do the ice puddles last? Indefinitely until heated or do they "vanish" eventually? Can they be dried with sodium poly?

It's the same as the cryotheum puddle - lasts forever until heated above freezing. I can add other features, but y'know, want to see whether people actually want this feature.

**Comment by anonymoose-contributor** [comment]
Seeing as the puddles we had a few years back were a giant mess of both optimization and gunk it seems unwise to add more possible puddle jank back onto the codebase.

**Comment by Dacendeth** [comment]
spilling the ice reagent doesnt even make puddles.

**Comment by Eneocho** [comment]
> spilling the ice reagent doesnt even make puddles.

bro how do you expect an ice cube to make a puddle, it's gotta melt first (thus turning into a water puddle)

**Review by west3436 — APPROVED** [review]

**Comment by ghost** [comment]
Funny idea but I dislike it too actually. I dunno why I added this.

**Pull request closed without merging**
