### PR TITLE
Ports a bunch of AI core sprites from Tee gee

### PR DESCRIPTION
**Pull request by JustSumBody**
What it says in the title, some of the sprites are dead versions of already existing cores rather than just using the default bluescreen. 
Also removes some weird ckey specific code that I was told isn't relevant anymore.
Some of them are neat, some of them maybe less so. Feel free to argue it.
Not sure the best way to show these because it's something like 20 .gifs hopefully this picture suffices
image
:cl: 
* tgs: Ports some AI core sprites from TG

### CODE REVIEW

**Comment by 9600bauds** [comment]
https://www.youtube.com/watch?v=2H1ltYUQO2I

**Comment by Ephx1** [comment]
I've been wanting that Database one for a while now, good stuff.

Just realized something though, there's one called "ai-wierd_dead" that doesn't seem to match up with any of the other sprites, does that mean there's an actual "ai-wierd" living sprite or is it used with something else?

**Comment by JustSumBody** [comment]
AI wierd is one that we have currently, using that core and dying will show the AI wierd dead one

**Comment by ComicIronic** [comment]
Did you rename the DMI states to use the crash suffix instead of the dead one?

**Comment by JustSumBody** [comment]
I did, I took the screenshot from tg's .dmi for some reason though.
Though now that you mention it, I can't remember if I renamed the Soviet dead one to redoctober dead or whatever we called. Let me double check that in a bit.

**Comment by Ephx1** [comment]
@JustSumBody 
You sure about the "wierd" one? What option chooses that one? None of the options are "weird"/"wierd", so is it under something else?

**Comment by JustSumBody** [comment]
```
if("Green")
			icon_state = "ai-wierd"
```

**Comment by Ephx1** [comment]
Ahhhh I see now, thank you, odd that it's called green instead of the other thing

**Comment by JustSumBody** [comment]
image
full .dmi if someone wants to double check I didn't misspell something. All named right from what I'm seeing

**Pull request merged**
