### PR TITLE
Removes SCP 294 from Snaxi

### PR DESCRIPTION
**Pull request by MadmanMartian**

### CODE REVIEW

**Comment by ghost** [comment]
Sad!

**Comment by SonixApache** [comment]
fucking mappers

**Comment by Irradiation** [comment]
Time to keep a running tally of each new map that has SCP-294 in it.

**Comment by kilozombie** [comment]
>Time to keep a running tally of each new map that has SCP-294 in it.

image

Hmm

(three of those are on z=2)

**Pull request merged**
