### PR TITLE
Zinc Saucier Crate

### PR DESCRIPTION
**Pull request by Kurfursten**
CONTENTS:
3x HydroHUD
3x Reaper Bag
2x Sea Devil (recently buffed)
2x Langstroth Hive
1x Echoes Vinyl
1x Vacuum Dishwasher
1x Sushi Mat
1x Cricket Farm
1x Ride Mower
1x Condiment Dispenser
1x Darts Kit (1 dartboard 6 darts)
1x Mantini Vessel

It's here at last, and now with images to prove it all works. Here it is in the trade window (base price 160)
image

No missing icons
image

Ride mower needed a special offset to stay in the middle aligned with the icon. It works on kudzu outbreaks and clearing weeds.
image

Sushi mat demonstration - create sushi without boiled rice.
image

Vessel before / after transformation. After becoming Mantini it fills other glasses.
image
image

Using HydroHUD to remotely inspect plants
image
image

Reaper bag harvests with no need for hatchet
image
image

Cricket farm successfully making meat and flour
image
Loose crickets!
image

Dirty and broken to stacked and clean
image
image

Langstroth hive allows harvest without dismantle
image
image
image

:cl:
* rscadd: Zinc Saucier service crates are now available at the trader.

### CODE REVIEW

**Comment by Eneocho** [comment]
No special icon for the reaper bag? I can see myself confusing it with my regular bags and giving it away by accident when delivering crops somewhere.

**Comment by Kurfursten** [comment]
I don't have any immediate ideas how to convey its special cutting teeth other than to just recolor the bag. If you want to make a sprite I'll use it.

**Comment by Eneocho** [comment]
How about this?
reaper bag

**Comment by Kurfursten** [comment]
Sure, seems fine.

**Comment by SECBATON-GRIFFON** [comment]
[desire to know more intensifies]

**Comment by Kurfursten** [comment]
The only good weed... is a dead weed!

ALSO: In testing I thought it was kind of annoying to have to go get bees too if you have the Langstroth. Maybe I should make it spawn with food + bees starter kit? This might just make traders start bee farming though. Thoughts?

**Comment by falcon2346** [comment]
> ALSO: In testing I thought it was kind of annoying to have to go get bees too if you have the Langstroth. Maybe I should make it spawn with food + bees starter kit? This might just make traders start bee farming though. Thoughts?

Bees require oxygen, so even with food and a starter kit I don't think it would be a problem unless they're willing to restructure their trade ship into a bee farm/hydroponics bay.

**Comment by Kurfursten** [comment]
That's what I expected, since there is enough room for it and I've seen people put hydro trays on the ship plenty of times before. It's easy now that they use non shuttle turfs.

**Comment by Eneocho** [comment]
You should probably change the reaper bag description to account for the icon.

**Pull request merged**
