### PR TITLE
RayCasting

### PR DESCRIPTION
**Pull request by PaulRitter**
[System]
Dunno if this needs a 🆑 so i left it out for know

This adds Unity-like (others prob. do it to, i know unity) **RayCasting**.
Also adds and uses 3-dimensional vectors, cause why not, may need it someday

Basically this means you can give the `/ray` a **starting point** and a **direction** and it can then either return you the **first turf** it hits or **all turfs** inside a specific distance (50 by default).

I plan to use this to **rework lasers**, since I took a stab at fixing reflections and the made the choice to rewrite it completely if anything.

Its nothing groundbreaking, if you have ideas on how to better implement this, please share. Especially in the case of the actual raycasting (`getFirstHit`, `getAllHits`). I'm not happy with the step-technique but oh well too lazy to make a proper algorithm.

heres an example of a result of a direction vector with (7,3,0)
grafik

### CODE REVIEW

**Comment by ShiftyRail** [comment]
I am 100% sure all the maths I've done related to vectors work if you give them a `z` component and implement the related additions, norms, etc, etc.

The algebra on R^2 is exactly the same as the algebra on R^3 with z = 0. Code-wise, I don't believe I did anything which implies we are 2-dimensional.

**Comment by Kharkov72** [comment]
will reworking lasers to use this cause a performance hit, you think?

**Comment by PaulRitter** [comment]
as far as I am aware this is actually quite easy on performance, especially considering lasers won't travel long distances.

if you have a way for me to test the performance impact, please do tell

**Comment by ShiftyRail** [comment]
A few comments :

- I don't see us using 3d vectors or any form of 3d geometry in a 2D game, ever, even something like multi-z does not have the 3rd dimension isomorphic to the first 2, so anything implementing 3d vectors would be largely oversized ;
- Byond **can** actually do operator overloading (even if Lummox didn't expect it to be used), so defining "minus" and "plus" for 3d vectors isn't needed, overload + and - instead
- are you sure you aren't just re-inventing `bresenham_step` ?

**Comment by PaulRitter** [comment]
>     I don't see us using 3d vectors or any form of 3d geometry in a 2D game, ever, even something like multi-z does not have the 3rd dimension isomorphic to the first 2, so anything implementing 3d vectors would be largely oversized ;

valid point, put i'm gonna rewrite to use 2d vectors

>     * Byond **can** actually do operator overloading (even if Lummox didn't expect it to be used), so defining "minus" and "plus" for 3d vectors isn't needed, overload + and - instead

tell me how, i wanna know how. the procs were literally killing me, i didn't know this

>     * are you sure you aren't just re-inventing `bresenham_step` ?
Yes, because bresenham_step would draw the laser piece by piece as far as i am aware.
I want to detect the object I am going to hit via rays, then draw a laser to it and apply damage. entirely different process.
In addition, this is a generic process, so other things can easily use it without the good old copy paste

**Comment by ShiftyRail** [comment]
http://www.byond.com/docs/ref/#/operator/overload for the operator overloading syntax.

I'm not really sure if there's a real advantage to do this. Bresenham's algorithm is *the* exact solution to the problem of tracing a segment on a discrete 2d grid. Your algorithm answers a larger problem of tracing a ray in a **continuous** n-dimensional system (the algebra you're using is independent of dimensions and you are using the Euclidean norm). 

It is also *iterative*, much like Bresenham's

One obvious optimization would be to **normalise your thing with Tchebyshev norm/infinite norm** (https://en.wikipedia.org/wiki/Chebyshev_distance) rather than Euclidian norm + flooring it, making use of the discrete geometry, but you would still answer the problem in `n` dimensions instead of just 2. Additionaly, the brensham_step also takes cares of timestopped projectiles and other things.

I don't really see the need for it, sorry. It's a bit oversized and what we have already is sufficient.

I'm not really surprised Unity does it. But unlike byond, unity isn't tile-based (as in, the discretisation of space is almost invisible to the player) and any code they do is supposed to work seamlessly from 2D to 3D, hence their reliance on vectors rather than geometrical median point (which only has a simple expression in 2D).

**Comment by PaulRitter** [comment]
rendering lasers step by step is kinda overcomplicating it imo. this would make lasers way easier to implement / doctor on, also stuff like reflections (which does not work to this day)

I don't understand what you mean by n dimensions, i am also moving in a 2 dimensions, not n?

**Comment by PaulRitter** [comment]
other than that, in my next commit I am adding some optimization, also the one you proposed

**Comment by ShiftyRail** [comment]
What I mean is that the algo you did uses vectors, and it's trivial to adjust it to be valid and trace something in any context, 3D, 4D, etc... since it's just linear algebra.

It's a good thing for unity, because if my memory serves correctly, the thing let you do 2D and 3D games, but in byond we'll never ever leave the plane.

This is just my intuition speaking, don't get me wrong, what you did is correct, but I think it's oversized compared to the existing algorithms.

If you want to test it, you could create a gun which simulates 1000 firings with one method, using `CHECK_TICK` to make it not crashing the sever, another which simulates the other method, and then compare in the profiler the  `REAL TIME` column of the procs, which would count how much those firings took.

**Comment by Exxion** [comment]
Ignore him about the column
Never, ever, ever, ever, ever, ever, ever pay attention to the real time column because it's completely useless
You'll want to look at self CPU, or possibly total CPU if the entire call structure is different between them

**Comment by ShiftyRail** [comment]
In this context I thought doing 1000 tries at once could crash his game, so I thought including CHECK TICK would be useful. If you do that, then it would make sense to compare how long fhe server slept in the two cases.

I do know that real time doesn't mean anything 99% of the time.

**Comment by Blithering** [comment]
How would emitters be affected by this change? They're pretty buggy right now, particularly noticeable in blob rounds.

**Comment by Exxion** [comment]
None

**Comment by ShiftyRail** [comment]
Emitters aren't really concerned by the change, and their shitcode is elsewhere

**Comment by Blithering** [comment]
Ah, that's a shame.  Thought they may have used the same code magic.

**Comment by PaulRitter** [comment]
ight im gonna rework this a bit and the branch of it to implement it for laser, so [dnm]. unless you want this for other things which I suggest but you do you

**Comment by PaulRitter** [comment]
Gonna pr this together with the laser pr which I will finish someday™️

**Pull request closed without merging**
