### PR TITLE
Syndicate Operative locker changes

### PR DESCRIPTION
**Pull request by SonixApache**
🆑 
- rscadd: Syndie lockers: Added ammo pouch, bandolier, tactical boot knife, handgun holster
- rscdel: Syndie lockers: removed multitool, crowbar

### CODE REVIEW

**Comment by DrSnips** [comment]
Have you tested it to make sure all of it's items fit on all maps? I don't think any maps have special hard mapped op gear but it wouldn't be a bad idea to make sure since they look a bit full.

**Comment by SonixApache** [comment]
this one is mostly intended to pair with #23559 to ensure it all fits and works

**Comment by ComradeDispenser** [comment]
Where do they get multitools now?

**Comment by Kurfursten** [comment]
Yes, where?

**Comment by SonixApache** [comment]
They're in the syndicate toolboxes, in the equipment room.
I wasn't aware that they needed them for anything.

**Pull request merged**
