### PR TITLE
Box tweaks

### PR DESCRIPTION
**Pull request by bthomas2**
Binoculars and gold coin in Captain's office, cigar replaced by superior version, matchbox replaced with zippo, charger moved, new chair. Arrivals ashtray, new Bar ashtray, Medbay ashtray, Dorms hair dye, Brig fire extinguisher locker, oxygen locker, and a lawbook on the table of both brig wings.

:cl:
 * rscadd: Added a gold coin to the Captain's Office, moved a table, changed the guest chair to wooden and moved the charger and chain of command. Glass ashtray, zippo(matchbox replacement), binoculars and premium havanian cigar(replaced old) in Captain's Quarters. Added ashtrays: glass to Medbay, new bronze to Bar, plastic  to Arrivals. Added can of hair dye to Dorms. Fire extinguisher wall locker, oxygen wall locker, and two new lawbooks in the Brig cell wings.

### CODE REVIEW

**Comment by bthomas2** [comment]
capoffice

**Comment by bthomas2** [comment]
brig

**Comment by Kurfursten** [comment]
Going to need you to get the diff on this down to a reasonable level, use the map cleaner if you are having trouble.

**Comment by Shadowmech88** [comment]
Please list the items you added to the captain's office in the PR description, as well.

**Comment by bthomas2** [comment]
all done

**Comment by Kurfursten** [comment]
Your diff is still +15,749

It should be something more in the ballpark of +18 to +65 based on the scale of these changes

**Comment by bthomas2** [comment]
look at the 2nd commit

**Comment by Kurfursten** [comment]
It has a diff of 110 from your base commit, so the diff for the PR as a whole is still huge

What we would like to see ideally is a PR with **only** that second commit. All the changes nicely compressed. This has a couple of benefits: reduces bloat, makes mapdiff bot work properly so everyone on github can actually review your changes, and it doesn't inflate change statistics.

**Comment by bthomas2** [comment]
> 
> 
> It has a diff of 110 from your base commit, so the diff for the PR as a whole is still huge
> 
> What we would like to see ideally is a PR with **only** that second commit. All the changes nicely compressed. This has a couple of benefits: reduces bloat, makes mapdiff bot work properly so everyone on github can actually review your changes, and it doesn't inflate change statistics.

hol up

**Comment by SonixApache** [comment]
what you do is just switch to bleeding-edge, run mapclean-prep, switch back to this branch, run mapclean, then commit

**Pull request closed without merging**
