### PR TITLE
Basic Human AI

### PR DESCRIPTION
**Pull request by Shadowmech88**
It turns out making AI is hard, and the scope for this quickly spiraled out of my control and working on it now distresses me, so I figured I'd just PR what I had.

There isn't a whole lot of documentation for the component system, so my understanding is tenuous at best. The code is probably of poor quality.

This PR adds a spawnable subtype of human, `/mob/living/carbon/human/NPC`, which makes use of the component system to give a human mob some sort of AI.
Currently it will equip clothes in view if it has none, and eat food in view if it is hungry. It attacks catbeasts, and will prioritize acquiring a weapon to do so if it sees a weapon nearby.

### CODE REVIEW

**Comment by Ephx1** [comment]
Cool, now you can play the game by yourself and never notice the difference

**Comment by DoctorMonkey** [comment]
Now we just need:

-Greyshit AI that hacks doors in range, picks up the spare ID if it's in viewrange, drags anyone who is knocked over to disposals and trashes them
-Catbeast AI that runs away from everyone and yiffs
-Hopcurity AI that gives itself an all-access ID and rushes the armory
-Chemist AI that creates lots of chloral, polyacid, space drugs and mindbreaker then injects people with it at random

**Comment by Blithering** [comment]
-Doctor AI that puts anyone injured in cryo, then ten minutes later puts their corpses on the floor outside genetics.

**Comment by Lokiamis** [comment]
Now if only we could have AI subtypes trigger on catatonic mobs when equipped with certain jumpsuits.

**Comment by ghost** [comment]
Oh god

Lobotomites soon, spessmen

**Comment by ghost** [comment]
Add some antag routines to it, and we can finally have competent antags

I wonder if those signals are hard to set up

**Comment by ghost** [comment]
confirm it works, and say when you're done

**Comment by ghost** [comment]
looks like you really fucked up component design

**Comment by Shadowmech88** [comment]
@Skullyton 
It usually works.
Sometimes the AI doesn't do what it's supposed to, and I don't know why.

I'm done as far as its features go.

**Comment by ghost** [comment]
gonna mess with it and see if I can make some of the humanoid mobs it

**Pull request merged**
