### PR TITLE
Allows rulesets to bypass enemy job requirements at 80+ threat level

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* rscadd: Dynamic Mode: At very high threat level (80+), rulesets will bypass enemy job requirements.

### CODE REVIEW

**Comment by DeityLink** [comment]
That just seemed logical to me, but feel free to discuss. The point of high threat level was to allow a chaotic round where any ruleset may happen, several even, but currently enemy job counts can still prevent those rulesets from firing.

This affects "Black Orbit" threat level only.

**Comment by ShiftyRail** [comment]
90 threat alone is more than enough threat on its own. This isn't needed.

**Comment by boy2mantwicethefam** [comment]
>2k19
>not compiling your code to see if it works

DEITY

**Comment by DeityLink** [comment]
@ShiftyRail says you. When you know how many rulesets don't proc because of the enemy job check combined with high level threat being orders of magnitude more rare given the new distribution, I think it's warranted. This won't bring back early Dynamic Mode level chaos.

**Comment by ComradeDispenser** [comment]
Can we remove Dynamic instead?

**Comment by DamianX** [comment]
I think we're much better off with exactly 0 >80 threat rounds with or without this change.
Cultblobnukes is retarded, cultblobnukes with no security doesn't really make any difference.
I abstain from protruding the thumb from my virtual hand

**Comment by DeityLink** [comment]
alright then

**Comment by SonixApache** [comment]
coward

**Comment by tuypo1** [comment]
Aww I was excited for this

**Comment by DeityLink** [comment]
Feel free to PR it yourself, it's a 2 line change. I won't be the one fighting for it.

**Pull request closed without merging**
