### PR TITLE
Gigadrill and carts

### PR DESCRIPTION
**Pull request by Zth--**
# _Gigadrill and carts_ **_(UPDATE 1)_**

### https://webmshare.com/play/vOQM0 **_(NEW)_**

- Gigadrill is now a vehicle that can mine.
- Added tractors (see second webm)
- Added carts that can be attached to vehicles (like janicarts), or another carts.
- ~~Working on mining carts, when attached to gigadrills they'll collect stuff from the floor.~~ _fuck them_
- I also moved janicarts to the vehicles folder.

I will actually need help from spriters to finish this PR, gigadrills don't have a south or north sprite, and I'm a shitty spriter (yes, I made those horrible mining carts).

Carts are self-contained so people can easily add new kind of carts (prisoner carts? foodtrucks?). Normal carts don't have any feature yet.

### CODE REVIEW

**Comment by aceedex** [comment]
looks nice. But my only qualm is that it further throws the ripley into the useless pile.

**Comment by Zth--** [comment]
@aceedex to be fair diamond drills are already 100 times better than any ripley. I was thinking of adding fuel if balance is a problem.

**Comment by aceedex** [comment]
its not really imbalanced against DDrills, I think it's fine on that end all depending on how its obtained. but I just wish there was an actual use for the ripley

**Comment by BobdaBiscuit** [comment]
There's also the fact the gigadrill will never see the light of day in 99% of rounds as it's a xenoarch large artifact. And now an actually semi decent one.

**Comment by Zth--** [comment]
@BobdaBiscuit I was thinking of making them constructable instead of having them as meme artifacts

**Comment by Exxion** [comment]
Ripleys are great
What are you all talking about

**Comment by Exxion** [comment]
Also, thank god
The giga drill is useless right now

**Comment by Probe1** [comment]
Ripleys are for big time mining.  Diamond drills are for precision mining.  Giga Drills are for xenoarch to find and ok if they upset the applecart because of their rarity.

**Comment by Zth--** [comment]
What I dislike from mechs is you have to wait like 2 hours for the battery to recharge.

Well, I can make the gigadrill:
A) Better than mechs (for mining)
B) A xenoarch tool good for finding artifacts.

It doesn't fit as an another diamond drill. Obviously if I do this they'll remain as a large artifact

**Comment by Exxion** [comment]
(Tesla relays work on the asteroid)

**Comment by ghost** [comment]
Tesla relays work in deep space last I found

**Comment by Exxion** [comment]
Alright that shouldn't work

**Comment by Intigracy** [comment]
Reminder that honk mechs do the job of a ripley better than a ripley.

You can attach drills and clamps to them, and they move MUCH faster.

**Comment by SkowronX** [comment]
[SPRITES]

**Comment by Kitfox88** [comment]
Ripley is the best mech because it looks swag as hell.

**Comment by Exxion** [comment]
Also, it was, until pretty recently, the only mech that could mount the clamp
Powercreep, etc.

**Comment by jknpj** [comment]
Why the fuck would combat mechs need drills and clamps

**Comment by Exxion** [comment]
Combat mechs have always been able to mount drills
Or at least for as long as I can remember
But the clamp was special

**Comment by Aurx** [comment]
>Also, it was, until pretty recently, the only mech that could mount the clamp

Which was because it was the only mech that actually had an internal bay.  
Which really makes no sense, how the hell are you cramming a dozen ore boxes into an exosuit without a BoH?

**Comment by Exxion** [comment]
The really impressive part is that all objects take up the same space in the cargo bay
So you can hold a pen, or (with singularity trickery) another whole mech, complete with its own cargo bay

**Comment by AutismSpider** [comment]
left out the part were the mech can pick up a super matter shard or crystal then later mech drill it to blow it up

**Comment by Exxion** [comment]
What do you think are the chances that two unanchored mechs can nullspace each other by picking each other up with clamps at exactly the same time?

**Comment by aceedex** [comment]
mechs can't clamp other mechs, even on harm intent. I assume because it ended up in subpsace tunneler shenannigans

**Comment by Exxion** [comment]
Yes they can. You just need to use the singularity to unanchor them first.

Though I did just remember that a PILOTED mech can't be picked up even if you do that, so sadly you still couldn't do what I suggested

**Comment by Anton-Kr** [comment]
Does this mean we can have Bay's cargo carts?

**Comment by Zth--** [comment]
@IsdatAfamas explain? I'm working on cargo carts but I'm not sure how bay's work

**Comment by PJB3005** [comment]
@Zth-- you have a cargo train you can hope onto and then have carts you can attach to it.

The carts can have stuff loaded onto it as if it's a MULE.

**Comment by Exxion** [comment]
So basically this plus a vehicle in cargo specifically for pulling the carts

**Comment by AutismSpider** [comment]
Can hook the carts to a mule right and mobs?

**Comment by Zth--** [comment]
Added the tractor and now cargo carts can loadstuff

https://webmshare.com/play/vOQM0

**Comment by Probe1** [comment]
Is this ready?

**Comment by Zth--** [comment]
I'm not working on it anymore, it may need a few tweaks to be 100% ready, but it's working so I guess the answer is yes

**Pull request merged**
