### PR TITLE
Allows combat borgs to use jetpack modules

### PR DESCRIPTION
**Pull request by SonixApache**
🆑 
 - tweak: Combat borgs can now be upgraded with jetpack modules.

### CODE REVIEW

**Comment by DamianX** [comment]
How this was not already a thing is beyond me.

**Comment by SonixApache** [comment]
Combat borgs aren't taken seriously by anyone. 😢

**Comment by jakmak** [comment]
Because they are (rightfully so) a huge production to build and inferior combat wise 95% of the time to the secborg

**Comment by Shadowmech88** [comment]
Combat borgs don't have stun weapons, right?
Why not?

They can only be built on code red, so what reason is there to not just make them "Sec borgs, but better"?

**Comment by FudgePucker** [comment]
I mean really, security borgs with illegal module are better than combat borgs 95% of the time.
Taser, laser, and handcuffs? What else would you need?

**Comment by SonixApache** [comment]
@jakmak @Shadowmech88 @FudgePucker make an discussion issue about it and we'll think of something. Having combat borgs as "No stuns, just sheer firepower" sounds great to me.

**Comment by CptWad** [comment]
Laser cannon does 40 burn my friend. Compared to 15 reg laser burn, almost triple damage

**Comment by jakmak** [comment]
Sonix I'm fine with combat borgs as being what they are as a pure killing machine with no way to take people down without ending their lives and used only for SHTF situations but as it stands now unless if you are fighting xeno/blob/simple mobs the secborg is superior in every other combat situation

**Comment by ghost** [comment]
combat borgs are for blob rounds and xeno infestations
if it's normal antags people just use regular sec borgs

**Comment by CptWad** [comment]
Combat borgs shit on vampires tbh

**Comment by CptWad** [comment]
And wizzies

**Pull request merged**
