### PR TITLE
[Role Datums] Scoreboard

### PR DESCRIPTION
**Pull request by DeityLink**
image

before the change to the new css (pic kept because more roles are featured):
image

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Yes

**Comment by DeityLink** [comment]
image
even better

**Comment by ShiftyRail** [comment]
Uuh
Can you make that a toggle ? I like Times

**Comment by DeityLink** [comment]
I probably can't ~~be arsed to do a toggle~~. it's time for people to give their opinions.

**Comment by d3athrow** [comment]
Times a shit and reminds me of typing reports in school.

**Pull request merged**
