### PR TITLE
Merges Containplasmaman flag into plasmaguard

### PR DESCRIPTION
**Pull request by Dacendeth**
## What this does

The flag on clothing items that prevent plasmamen from catching on fire is merged into plasmaguard, effectivly allowing any suit that prevents plasma from leaking in to also prevent plasma from leaking out. It should be noted that plasmamen cannot wear every suit with this completely safe as their ability to regulate their temperature is currently still tied to their plasmaman suits, I may or may not change this later.
## Why it's good

Allows for more deception, makes sense logically to me, as I see it the reason they catch on fire in normal hardsuits is plasma leaks out the same way it leaks in and thus shouldnt happen with plasmasealed suits.
## How it was tested

Wore an atmos suit, wore a security hardsuit with plasmaguard upgrade installed into it, caught on fire when I retracted the helmet.
## Changelog

:cl:
 * tweak: Suits with plasmaguard can now be worn by plasmamen without catching on fire.

### CODE REVIEW

**Comment by ErrorsWindows** [comment]
I played on beestation before this when I first played here in 2020 and I thought it was weird when I went to put on the mining hardsuit to go out into the asteroid to escape rogue AI and I still caught on fire
So I guess my old caveman logic will work now

**Comment by angryturnip** [comment]
Logic makes sense to me why they wouldn't catch on fire wearing those suits. Might change my upvote if any of the people downvoting give a compelling reason they're against this

**Comment by angryturnip** [comment]
From discussion outside of github, "suit's got delicate shit on the inside, not made to contain corrosive super shit." I actually agree with that logic that the corrosion protection on the outside wouldn't be present by default on the inside of human suits, so the downvotes have won me over.

**Comment by SonixApache** [comment]
I remain of the opinion that a plasma containment unit hardsuit module should be written instead.
Plasmaguard keeps the plasma *out*, hardsuits aren't built for keeping plasminated environments on the inside.

**Comment by west3436** [comment]
> I remain of the opinion that a plasma containment unit hardsuit module should be written instead. Plasmaguard keeps the plasma _out_, hardsuits aren't built for keeping plasminated environments on the inside.

yeah do this instead

**Pull request closed without merging**
