### PR TITLE
Less-than-lethal killing SPS

### PR DESCRIPTION
**Pull request by ghost**
We all knew it was too good to last.
557987d36da81116070e27e6

:cl:
 * tweak: Moved SPS from security boxes to sectechs, requiring a coin.

### CODE REVIEW

**Comment by ghost** [comment]
unexpectedly based

**Comment by GreatBigFailure** [comment]
If you're doing that then add the ability to hear head of staff SPS' going off to their PDA cartridge. It's still important sec is able to know the captain has been beheaded.

**Comment by PrimeDSS13** [comment]
quick speedmerge before the secmains see

**Comment by drawsstuff** [comment]
it's too late, we already see

now remove it all the way, no balls

**Comment by Gazathor** [comment]
ITS TIME TO CRASH SECS DOMINANCE OVER THE SPS
NO LONGER WILL THE COMMON MAN BE DENIED THE BEEPING TOY
NO LONGER WILL THE CLOWN BE WITHOUT HIS 30 REQUIRED FUNNY NOISEMAKERS
NO LONGER WITH THE TRAITOR BE WITHOUT AN EASY WAY TO TRACK SECURITY
THIS IS A NEW AGE OF PROSPERITY

**Comment by ComradeDispenser** [comment]
At least leave it in for the heads of staff and give the officers some way to tell when heads SPSs are going off.

**Comment by BomberBro** [comment]
As a force of entropy I support any and all change to the stagnation in sec society, but I like the idea of an SPS as a basic GPS for the warden/designated brig pig to autistically watch and help direct traffic without the rape alarm feature.

As a side note, this PR doesn't actually do what it says it does in the changelog though, you fools. Shame on all of you who blindly upemoji'd it without checking the files changed, it doesn't touch sectechs or their premium items at all.

**Comment by ghost** [comment]
I merged the sectech change to this patch, but it didn't carry over for some reason. One second.

**Comment by ShiftyRail** [comment]
Which problem is this even supposed to address
Upvoting anything because muh stagnation and muh status quo is a dumb move

The SPS itself exists to promote teamplay and encourage officers to look after one another.

**Comment by Kammerjunk** [comment]
if only teamplay was otherwise possible

**Comment by GreatBigFailure** [comment]
> Which problem is this even supposed to address
> Upvoting anything because muh stagnation and muh status quo is a dumb move
> 
> The SPS itself exists to promote teamplay and encourage officers to look after one another.

It also discourages murderboning and makes modes like cult/revs more tactical and sneaky, which despite all the memes, are the point of conversion rounds. 
If SPS are too strong or hard to get by then more sources of EMP or other ways to disable them temporarily is a better solution than this.
Keep in mind that if only 1-2 people have an SPS, like heads of staff, they're now GPS. SPS only report things to other people with SPS meaning if the captain is beheaded the only person who knows about it is the RD who EMP'd his own SPS opening lockboxes and forgot to turn it on again.

**Comment by SonixApache** [comment]
not the proper solution for the SPS problem

*edit*:
My idea remains adding a "Security alerts computer" that houses stuff like SPS screams, camera alarms, door alarms, lockbox breach alarms, fire alarms, etcetera.

*edit 2*: 
Furthermore, giving clowns and cargonians easy access to SPS spam with celt's shitty horrendous fuckawful stupid terrible HL2 sounds still in place makes my soul die inside

*edit 3*:
Thanks for the gold kind sir!

*edit 4*:
thanks for being a fag, chikun
yeah i know you can read this, you big gay homo, the fuck is up with you

**Comment by BomberBro** [comment]
I don't see the issue as long as we get to see the effects of the change, SPS removal has been talked about for ages as a way to improve sec and now it's time for the supporters to actually demonstrate that beyond hopeless theorycrafting. If it works, great, if it actively makes security even worse, then we can send it back. 
I'll be honest though, passing this on votes alone is a terrible metric, especially for major balance changes, since a lot of people vote on the epic title alone and don't bother with scrutiny. The PR had about 7 upemojis when I pointed out it didn't do what it was supposed to, for reference. Even now the PR only removes the SPS for detectives and security officers, heads still keep it, but you wouldn't know that from the title and changelog alone.

**Comment by tuypo1** [comment]
If you are that bothered by sps removing them sure as shit ain't the right solution, removing the alerts is

**Comment by ghost** [comment]
I'll just say, I'm not bothered by the SPS at all, though making it more limited (it can still very easily be obtained via this PR and duplicated for all officers) might make me a bit more cautious running through maint solo as Head of Security.

**Comment by Konater** [comment]
If I take that off will you die?

**Comment by ghost** [comment]
It would be extremely painful...

**Comment by Armadingus** [comment]
What's the problem with SPS, though? There's more reward in killing security, especially with the element of surprise that antags have, you get equipment and one less armed guy to fight. It's good that there is a consequence, which you can remedy with putting resources into EMPs.
Could you at least address Kurfusten's reason to adding the SPS before you limit it?
image

**Comment by ghost** [comment]
I don't see a good reason to address any singular argument for the SPS because every substantive argument made is from personal experience and often contradict what other people claim with authority, though since you asked nicely, I will tell you that chloral being nerfed and ling being removed, as well as people being banned for greytiding security officers, did far more to stop the lone security officer "issue" than the SPS ever did. Making the SPS harder to get would most impact cult more than any other game mode due to the combined impact of the SPS going off during a conversion and the loyalty implant giving a longer duration to conversion, resulting in the location of the beep usually being where the officer will be when security eventually respond.

Stripping SPSes are fun, though, because they do prompt security to go from 0 to 100 on the "oh fuck lets get our act together" meter without having to be immediately at risk of them finding you. I just want to shake up some people's dependency on them and see what falls out.

**Comment by ghost** [comment]
The SPS is a crutch that de-incentivizes team play and communication because you only have to listen for the rape whistle to know where your free valids are located.

I've supported removing it for a long time, but making it harder to get is good enough to test the waters. Ideally I think it should be replaced with normal GPSes and a CMC in the brig so the warden or a designated officer has to put some effort in if they want to track the rest of sec, but that can wait until we see how this is received.

edit: I just now saw sonix's PR which is basically exactly what I wish SPSes were.

**Comment by KingofHONK** [comment]
Finally playing sec will be the hardcore ironman run that it was always meant to be.

**Pull request closed without merging**
