### PR TITLE
Raises all bigstacks from 20 to 50 sheets.

### PR DESCRIPTION
**Pull request by Eneocho**
A stack of material is 50, makes sense that bigstacks should be 50 as well. [tweak]
:cl:
 * tweak: Bigstacks now have 50 sheets instead of 20.

### CODE REVIEW

**Comment by gurfan** [comment]
This will make places like robotics/engineering that start with 20 glass/plasteel whatever get 50 sheets, won't it? The changelog should be more descriptive of what this will actually do

**Comment by Kurfursten** [comment]
No, those are hardmapped. Only vaults map bigstacks. This mainly buffs the Habitat Depot vendor, which normally gives you 20 of any material for a cost. Since this isn't changing the cost, it's lowering the price per sheet.

The other thing this touches is the trader antique matter synth, since it prints bigstacks. Since this isn't changing the energy cost, it's lowering the energy cost per sheet.

EDIT: This also buffs Gold core Slime Animation which makes wood bigstacks when not injected into anything (combined with water), and blob engineering supply requests - which were only recently added.

Overall, I don't really understand what the point of this PR is. Which of these is the thing you were trying to hit with this buff? Please explain.

**Comment by Zth--** [comment]
Sneaky coder vibes

**Comment by Eneocho** [comment]
> Which of these is the thing you were trying to hit with this buff? Please explain.

Honestly I just wanted to streamline some testing autism so I don't have to varedit or spawn multiple bigstacks on localhost to get them 50 sheets.

**Comment by DeityLink** [comment]
Make a /biggerstack subtype then

**Comment by Kurfursten** [comment]
I'm gonna make a hard collab call on this and say that since there's literally no justification for this, just make a new PR where you make a new subtype for your testing needs

**Pull request closed without merging**
