### PR TITLE
New vault - house in space

### PR DESCRIPTION
**Pull request by unid15**
A board game gone wrong has resulted in a house being teleported into space. The vault has no hostile mobs. Loot: super soaker, joy mask
Being an obvious movie reference, this sound is played when you discover it: https://www.youtube.com/watch?v=lo693ySIXto

 (the regular floor tiles are no longer there, neither is the bullwhip)

:cl:
 * rscadd: Added a new vault

### CODE REVIEW

**Comment by calzilla1** [comment]
First- loot seems a bit OP for a mobless ruin
Second- what was the movies name? I remember it was lile jumanji in space

**Comment by Riekland** [comment]
this loot is way too good
the movie sucked shit

**Comment by AutismSpider** [comment]
take out the bullwhip way to strong for mobless ruin

**Comment by Shadowmech88** [comment]
@calzilla1 
It was called Zathura.

**Comment by MadmanMartian** [comment]
>not having a dungeon that has a recycling furnace, with a conveyor full of flammable objects, surrounded by hostile humanoid space lizards where the good loot can go

**Comment by Blithering** [comment]
I like the wild wasteland sound on discovery, that should be on some other reference or bizarre vaults out there

**Review by MadmanMartian — COMMENTED** [review]
>narrator variables for all areas

Could be juicy for extra fun stuff in the future

**Comment by ghost** [comment]
name it Sneed's Feed and Seed (Formerly Chuck's) or riot

**Pull request merged**
