### PR TITLE
Energy sword changes, a bugfix, and a new interaction

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
It took most of the day, have mercy
List of changes:
- Energy weapons now have 100% armor penetration, and some in their inactive states have 50%
- Armor penetration for melee weapons now actually works, previously it was projectile-only and there was no consideration for armor penetration when calculating melee damage received
- New sharpness flag added called CUT_WALL_AIRLOCK. It lets you cut walls, airlocks, and girders. Interactions with these things have been added accordingly. Wall-cutting depends on the hardness of the wall. It takes 20 seconds to cut through an airlock, and about 2 seconds through a girder. You need to have the weapon active and to have harm intent.
- A bit of code clean-up
- The bloodlust weapon now has a 1.5 second delay instead of 2.5, given that it's a bit terrible
- Added a new interaction for active energy weapons: Hand-cutting. Like that scene in Star Wars. You need to have disarm intent on and the weapon active, it has a 25% chance of cutting the person's hand right there and there. Disarming. Ha. Dual sabers don't have this (yet)

As usual, if the PR doesn't pass the bugfixes and other features will be made separate
Bugfixes and more testing tomorrow and changelog tomorrow

### CODE REVIEW

**Comment by bathosbathtime** [comment]
Please make it atomic even if it will pass, this makes the reversion process if needed make mustard gas.

**Comment by Irradiation** [comment]
>Hand-cutting
>Dis-arm-ing

:thinking:

**Comment by SonixApache** [comment]
jesus christ how unatomic and horrible
make the melee considers armor pen thing separate at the VERY least

**Comment by Irradiation** [comment]
Also like Bathos said, this be some unatomicity. 
>**PR title = energy sword changes, bugfix and new interactions**
>Bloodlust gets buffed
>Melee armor penetration gets changed/fixed
>Airlock fuggering up thrown in there for good measure

**Comment by Coxswain-Navigator** [comment]
YOU WERE THE CHOSEN ONE!
Probably best to make this atomic like everyone is screaming, and dis-arming should really just cut the whole arm. Given that energy weapons ignore armor, its likely that there's actually a better chance of cutting someone's arm off with harm intent while aiming at the arm. Test this and adjust the percentage accordingly.

**Review by jknpj — CHANGES_REQUESTED** [review]
Make a PR for each different change, this is BYOND unatomic.

**Comment by ShiftyRail** [comment]
Unatomic

**Comment by Sooose** [comment]
The changes sound really !FUN!, I'll emoji it if they are separated.

**Comment by Hoshi-chan** [comment]
I really like the wall/girder/airlock cutting thing. Soon, we'll have everything necessary to bring space ninjas back...

**Comment by Kurfursten** [comment]
Not a fan of cutting through rwalls without need for other tools or eye protection all packed into an already-robust projectile deflecting pocket-fitting class of weapons.

**Comment by boy2mantwicethefam** [comment]
Atomic explosion

**Pull request closed without merging**
