### PR TITLE
Fixes moles problems with animals, plus misc. other objects and effects

### LINKED ISSUE #16648: AC Units Too Powerful
I noticed this a while back when I accidentally briefly exposed a heat exchange pipe from a RUST to an engineering chamber and the room shot up to ungodly temperatures. It only took a couple minutes with an AC unit to cool off, didn't even need foam. I've even heard of people running tiny SMEs on nothing but an AC to cool them. Probably went haywire with the atmos changes.

In any case, this needs more testing and may have already been fixed since I haven't had a chance to test it again recently. I'm all for strong engineering tools but it really seemed to cool outrageously fast.

### LINKED ISSUE #16860: Something about CO2 calculations is very off for some mobs
#### Description of issue
Mice will drop dead at very small amounts of CO2, 0.02 moles or something. Monkeys will go into a near-death state at around 0.6 moles and never come out of it.

#### What you expected to happen
Mice should follow what the max_co2 for simple animals is, 5 (moles?)
Monkeys have a safe_co2_max of 10, which appears to be partial pressure.

#### Length of time in which bug has been known to occur
I am fairly sure this started when all the recent ZAS updating was done.

#### Server revision

Game: 224443bda633f1ca00b897f0f656076f25e95d92 
Patches: 9e34bcea4d28270b966365362177f6890fc3ca45 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Pathid**
Closes #16860
Fixes #16648 at least partially
Stops your pets from dying to tiny amounts of CO2 and plasma!

A bunch of things are currently getting all moles from the zone they're in without regard for the volume of the zone. These are the ones I'm aware of that are causing issues.

:cl:
* bugfix: A breathing bug for non-human mobs was fixed. Tiny concentrations of CO2 and plasma should no longer kill animals dead.
* bugfix: A similar bug was causing space heaters and AC units to be unduly effective.

### CODE REVIEW

**Comment by DamianX** [comment]
Are air conditioners still more powerful than before #15922?

**Comment by Pathid** [comment]
They might be. But that difference is small compared to before and after this change.

**Comment by Pathid** [comment]
It strikes me now that there's a much better way to do this.

**Comment by Pathid** [comment]
Okay, I lied. I don't know a better way to do this. Done some testing and it doesn't seem to break stuff

Things I haven't gotten to yet:
* Artifact effects
* Heat exchange pipes and plates
* Fire

Fire and HE pipes at least I'll want to do in separate PRs probably.

**Comment by Pathid** [comment]
@MadmanMartian @jknpj @DamianX 
This should be good to merge.

**Comment by MadmanMartian** [comment]
I'm not a merge-collab. Not allowed to merge stuff, promised the chicken

**Comment by Pathid** [comment]
@MadmanMartian 
That's fine. Just take the DNM label off please.

**Pull request merged**
