### PR TITLE
Fast food vault

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[vault]

## What this does
adds a fast food restaurant vault with a car park and drive thru
when moving up to the speaker, orders can be made and collected by paying the service bot at the delivery point below it
if attempting to enter the kitchen, shutters will close and the cookbots will attack
has some boarded off backrooms with hostile mobs and chef themed loot

image

## Why it's good
thematically similar to both the pod station and mining bar

## Changelog
:cl:
 * rscadd: A strange, abandoned fast food outlet can now be found in deep space, staffed by robots that take orders inside or at the drive thru.

### CODE REVIEW

**Comment by pedr69** [comment]
pics?

**Comment by SECBATON-GRIFFON** [comment]
> pics?

added it there

**Comment by jwhitak** [comment]
Low quality, basic mapping. There's not even a maint, power system, or atmos. Nothing interesting in this map and we already have a nice ugly diner vault.

**Comment by xeroxemnas** [comment]
Cringe, make a Pizza Tower themed vault and I'll approve.

**Comment by dinnerwoerror** [comment]
don't forget the manager desk that's somehow in the middle of the hall and still has boxes crammed under it

**Comment by tinysaturn** [comment]
this is really similar to the...other abandoned restaurant vault

**Comment by Eneocho** [comment]
>this is really similar to the...other abandoned restaurant vault

Something something the abandoned diner closed down cause it couldn't compete with automated chefs.
I like the auto bot cooker idea. If this doesn't pass you could add it to the other vault.

**Comment by SECBATON-GRIFFON** [comment]
> Low quality, basic mapping. There's not even a maint, power system, or atmos. Nothing interesting in this map and we already have a nice ugly diner vault.

wait we do? how would people feel if i just added that to it instead (what's the name of it anyways i don't even remember it)

**Comment by Optimism333** [comment]
> > Low quality, basic mapping. There's not even a maint, power system, or atmos. Nothing interesting in this map and we already have a nice ugly diner vault.
> 
> wait we do? how would people feel if i just added that to it instead (what's the name of it anyways i don't even remember it)

It's about a year old by now. The pod station vault.

#31272

Have fun adding stuff to it!

**Comment by SECBATON-GRIFFON** [comment]
> > > Low quality, basic mapping. There's not even a maint, power system, or atmos. Nothing interesting in this map and we already have a nice ugly diner vault.
> > 
> > 
> > wait we do? how would people feel if i just added that to it instead (what's the name of it anyways i don't even remember it)
> 
> It's about a year old by now. The pod station vault.
> 
> #31272
> 
> Have fun adding stuff to it!

oh i didn't think that was a diner, more of a service station. the simiarities here could be roads and carparks but beyond that i don't see it

**Comment by SECBATON-GRIFFON** [comment]
just removed all the excessive roads and added a proper power system now, with a small bit of maint

**Comment by pedr69** [comment]
there's all the vents but where's the air alarm?
or do they come pre-initialised

**Comment by SECBATON-GRIFFON** [comment]
> there's all the vents but where's the air alarm? or do they come pre-initialised

added them now

**Comment by Killette2** [comment]
Feels like a mix between the pod docking like others said, and a similar iron chef competition vault which has more food and its own botany. I don't mind this as much and I like the idea of a robot ran bar actually serving people, but I would like similar vaults categorized together when rolled for so we don't get 3 space cafeterias in the same round and so vault quality isn't always the main issue whether a vault gets approved or not

**Comment by SECBATON-GRIFFON** [comment]
> Feels like a mix between the pod docking like others said, and a similar iron chef competition vault which has more food and its own botany. I don't mind this as much and I like the idea of a robot ran bar actually serving people, but I would like similar vaults categorized together when rolled for so we don't get 3 space cafeterias in the same round and so vault quality isn't always the main issue whether a vault gets approved or not

i actually had the mining bar in mind this whole time as making it the space counterpart, but the iron chef thing was an inspiration for the loot.

**Comment by Eneocho** [comment]
Unless you varedit the hivelord cores they will die during ready up (they live 2m). Consider increasing their time to a couple hours or making a variant that doesn't process.

**Comment by SECBATON-GRIFFON** [comment]
> Unless you varedit the hivelord cores they will die during ready up (they live 2m). Consider increasing their time to a couple hours or making a variant that doesn't process.

i thought they didn't die in freezers

**Comment by ManopolisJones** [comment]
I just realized what I don't like about this vault, I feel like its really not interesting enough. We're talking an almost mashup vault of the pod pitstop and the roid bar, and while it has the cool feature of robots cooking grub for you, I think it'd be a much cooler idea to have something like some kind of bloodbath were the service bots went haywire and started hacking up all the customers. 
Hell, it'd even be more interesting if the main room is covered in blood, and the cooking bots aren't intially hostile to the people showing up, opting instead to sell you food made from humanoid meat, where if you order a set amount of food, they'd run out of cooking material and then begin to attack you. I reckon making the vault like this could also open you up to some of the loot from the customers dead in the back, or an item or two left at one of the abandoned tables from the initial attack.
Of course, you might do right to take it as a real ideas guy moment, there is no doubt some virtue in finding something as simple and almost humorous like this out in deep space.

**Comment by SECBATON-GRIFFON** [comment]
> I just realized what I don't like about this vault, I feel like its really not interesting enough. We're talking an almost mashup vault of the pod pitstop and the roid bar, and while it has the cool feature of robots cooking grub for you, I think it'd be a much cooler idea to have something like some kind of bloodbath were the service bots went haywire and started hacking up all the customers.

if you intrude into the kitchen area all the bots do that to you, including closing the shutters so you can't get back out without breaking windows

**Comment by Theophrastus1** [comment]
lemme get uhhhhhhhhhhhhhh

**Comment by SECBATON-GRIFFON** [comment]
by the way if anyone's looking over this there's no secret repo conflict, i just accidentally branched this off the one way window PR and reverted everything that flagged the tag. to my knowledge anyways.

**Comment by Exxion** [comment]
>orders taken and handed over through right window

EUROPEAN

**Comment by Exxion** [comment]
Also there are no arrows specifying direction through the drive through. You have to figure it out from the intercom and the window, which aren't necessarily simultaneously visible in-game

**Comment by SECBATON-GRIFFON** [comment]
> > orders taken and handed over through right window
> 
> EUROPEAN

this is actually something burgers do different?

**Comment by Exxion** [comment]
Yes, it is well known that the driver side of the car is on the left in the US

**Comment by Theophrastus1** [comment]
changed to downvote due to having to shout across the pod to order

**Comment by Eneocho** [comment]
`>they don't know it's a space europe fast food joint`

**Pull request merged**
