### PR TITLE
Vampire buffs 3: Reduced cooldowns for five abilities

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Why?
Cooldowns are too much, that's all.
The most this change will do is make vampires pounce on people a bit more often, for God's sake even the wizard's teleport spell has a shorter cooldown than these.
The more powerful spells like summon bats, mist form, and diseased touch haven't been reduced in cooldown
Glare: 180 -> 120 seconds
Screech: 300 -> 180 seconds
Rejuvenation 180 -> 60 seconds: It's a very good tool but three minutes is too much.
Enthrall: 180 -> 120 seconds
Hypnotise: 180 -> 120 seconds
Also they cost blood except for glare
:cl:
 * tweak: The following vampire spells had their cooldowns reduced: Glare, Chiropteran Screech, Rejuvenation, Enthrall, and Hypnotise.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Glare, and hypno, have very long cooldowns because they're a guarenteed succ.
Screech as a very long cooldown because it's an AoE stun and a free griff ability.
30 seconds on a rejuv is just insane and ensure you'll never get caught.

Make those cooldown reductions tied to wearing a vampire cap and don't put such a huge buff on Rejuv.

**Comment by boy2mantwicethefam** [comment]
You can re-apply stuns though
1. It's a one minute reduction to push it a bit closer to being used as a defensive tool
2. The blood cost is high though and five minutes is just too much for any spell
3. Vampires are already hard to catch, they still have mist form and shadowstep that they can use (which cost blood and can quickly go down the drain)

**Comment by Caboozles** [comment]
If they’re so hard to catch, why add a further spamable tool? Hard pass on the Glare, Rejuv and Hypno timers

**Comment by boy2mantwicethefam** [comment]
Rejuvenation only does two things, get rid of stuns and chems (after a small delay, technically dictated by the byond tick) and later on reduce damage by 10 over a period of 14 seconds (except for oxyloss, which is 25), the current 180 seconds cooldown is too much. And you can quite literally just re-apply a stun, because all it does is set all existing stuns to 0, but if you apply a stun again it will last for the stun duration

**Comment by SirSkeleto** [comment]
increase the blood cost for rejuvenate to 10 at least
t. pro vampire player

**Comment by Caboozles** [comment]
Rejuv being spammable means that Medbay has lost all forms of defense against a vampire unless you want more people to grab tasers for every department. 

Tie it to a cloak, at the very least.

**Comment by SGuivenne** [comment]
Cab, just shove them into cryo and swap poly acid or space lube into the container.

**Comment by Caboozles** [comment]
If a vampire lets you cryodunk them, I doubt they are intelligent enough to  get enough blood to even have rejuvination.

**Comment by boy2mantwicethefam** [comment]
Should I increase the rejuvenation cooldown to 60?

**Comment by Caboozles** [comment]
60 would be better.

**Comment by ShiftyRail** [comment]
I am applying the "require server vote" label as it sits as 8/9. I'll create a server poll shortly.
Unless of course you want to edit it before it's proposed to the community.

**Comment by Kurfursten** [comment]
This never received its vote

**Comment by boy2mantwicethefam** [comment]
The craze has died

**Pull request closed without merging**
