### PR TITLE
More in-hand icons, Cigs Edition

### LINKED ISSUE #26379: Missing Cigarette Icon State
Left inhand, lit, facing west

It just blinks out of existence in one frame

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #26379

cigs

:cl:
* imageadd: Added and polished in-hand icons for all cigarette-related items. Every lighters, match, box, cig, and even ashtrays are now visible in your hands.
* bugfix: You will no longer crush your pipe into an ashtray, unless on harm intent. On other intents you will simply empty its content and put it out.
* rscadd: Cigarettes and Pipes now warn you about 5 seconds prior that they're about to go out, letting you extinguish them of your own accord. Blunts specifically will burn your lips for 1 burn damage if you let them go out while still on your lips or hands.
* rscadd: You now get a message when trying to cut a pipe out of an ear of corn, telling you that you gotta eat it first.

### CODE REVIEW

**Comment by Kurfursten** [comment]
If you let a cigarette burn itself out while you are holding it inhand or in your mouth, it should deal 1 burn.

**Comment by DeityLink** [comment]
> 
> 
> If you let a cigarette burn itself out while you are holding it inhand or in your mouth, it should deal 1 burn.

I considered it but I'm only gonna have it for blunts. Industrial cig filters usually put them out.

**Comment by DeityLink** [comment]
There, it can be enabled for individual brands later on.

**Comment by DeityLink** [comment]
Alright, 100% tested

**Pull request merged**
