### PR TITLE
[DNM] Advanced Tools

### PR DESCRIPTION
**Pull request by Exxion**
This PR is mainly for the purpose of being pointed to as a reason for using construction datums, but I am actually working on things.
Sprite work will, at some point, be required, but not necessarily yet. If someone wants to, though, go ahead.
All changes to tool speeds or tools with speeds other than the default use the speed system from #4216, so they only work on constructon that uses construction datums. Currently, this is only mechas, spacepods (whose construction steps are all instant anyway), and flatpacks, as far as I know.
So please use construction datums if you add construction and/or deconstruction to something. Comic made a [super helpful guide](https://github.com/d3athrow/vgstation13/wiki/Construction-Datums:-%3F%3F%3F-and-a-How-To) on it.
I'll work on porting existing things to construction datums, too.

Current changes:
- The socket wrench is now twice as fast as the standard wrench so it's actually special other than for one single use.

Planned changes/additions:
- Advanced tools from R&D
  - Power screwdriver, wrench, crowbar (maybe), wirecutters (really maybe)
    - Require research, but not much
    - Pretty much like the standard versions except they require power cells and are much faster
  - Arc welder
    - Also requires a bit of research
    - Uses a power cell instead of welder fuel, but slightly slower than a standard welder
      - Power draw configured so the smallest power cells last around as long as a standard welder
    - Only blinds and uses power while in active use, not just while turned on
    - May also include an advanced variant which has much higher research requirements, but is faster than a standard welder
  - MIG welder
    - Uses a power cell plus wire instead of fuel
      - Similar power consumption to the arc welder
      - Holds 5 or 10 cable pieces, each lasting around as long as a standard welder (maybe a little shorter)
    - Vastly faster than a standard welder, but only for construction. Either incapable of deconstruction or much slower at it (haven't decided).

And I'm open to other suggestions, too.

### CODE REVIEW

**Comment by FudgePucker** [comment]
Maybe make a another use for toxins and have plasma arc welder, you put in a O2 tank and a Plasma tank with a toxins mixture and it mixes just a tiny bit of gas at one time to make a super welder.
You can also use it as a non traitor Esword and have a sick ass plasma sword.
If you set it to use too much gas it blows up in your face. (Just a small explosion, you don't want people to use these to non antag bomb the station and use the excuse that they are new to it.)
Charging at xenos with a makeshift plasma sword would be kick ass.

Also
>one single use

Yea, that single use, is the most powerful force on the entire station.
Overload distro, wrench three distro pipes in the room you want to strike, bam, everyone not in a atmos hardsuit just died.

**Comment by Exxion** [comment]
>Yea, that single use, is the most powerful force on the entire station.

Good point, but I still think that its description as "the wrenchiest" suggests that it would also be wrenchier in other ways.
But if people disagree, I can change it back or make it faster than default by less.
Also, plasma welder would be kickass. Maybe something along those lines should be a sort of decon counterpart to the MIG.

**Comment by Probe1** [comment]
i'm at a loss trying to decide when I need a screwdriver, crowbar or wirecutters to work faster.  99% of my uses are instantaneous already and the delay comes from clicking things out of my tool belt and clicking on stuff.  

>The socket wrench is now twice as fast as the standard wrench so it's actually special other than for one single use.

yeaaaa but its one use is dumping  tens to tens of thousands of kilopascals of pressure into a room.

**Comment by ComicIronic** [comment]
I think it looks pretty cool for a base system, and we'll really reap the rewards when construction datums become more widespread.

**Comment by Iamgoofball** [comment]
Arc welder better be usable to blind people around you. That shit's bright. Also it should blind you more if you use it w/o protection.

**Comment by Exxion** [comment]
@Probe1 Wrench and crowbar would probably be the most useful to speed up. The rest are mainly for completeness.
But the way I'm currently setting it up is by basing the power drain on the time taken to perform the action, so instant actions don't use any power.
Also, the powertools don't fit in a pocket, but they do fit in a toolbelt.

**Comment by ComicIronic** [comment]
>griff tools

Go home, Goofball.

**Comment by Iamgoofball** [comment]
You try staring at an arc welder without proper protection sometime and see how well that goes for you.

**Comment by Exxion** [comment]
Unless I'm mistaken, the current welding tool blinds people around you, too
Just only within one tile distance

**Comment by 9600bauds** [comment]
Why not swiss army tools?

**Comment by Exxion** [comment]
I'm pretty sure that already exists but is only admin-spawnable

**Comment by ComicIronic** [comment]
I'd suggest reopening this PR when you have something more to show.

**Comment by Exxion** [comment]
Yeah I was going to keep working on it
Then I didn't

**Pull request closed without merging**
