### PR TITLE
Fixes Eye Surgery

### LINKED ISSUE #23027: Eye Surgery
I was doing eye surgery the other round and I noticed a weird issue.
If you are using the advanced scalpel in the switch tool (dunno if this applies to it when not in a switchtool) it will always cauterize the incision even if you haven't used a scalpel.
Also, you can use surgery tools an infinite number of times at any point. It's kinda weird. Like: Scalpel->eyes 10000000x
Retractor->100000000x
>hemostat->100000000x
>cauterize->100000000x
When you do eye surgery
At first I thought it had to do with mechanical eyes but I had another patient with organic eyes and the same thing happened. I'm no coder so I don't know but I will try to recreate it on the test serb soon.

### PR DESCRIPTION
**Pull request by Cyadox**
[bugfix][oversight][tested]
Adds checks to see what stage of eye surgery you're in to prevent repeated steps. I can't believe this bug is over 6 years old, was relatively common knowledge, _and_ only got ONE issue report 2 years ago.
Fixes #23027

:cl:
 * bugfix: Eye surgery no longer lets you infinitely slice or cauterize your patient's eyes

### CODE REVIEW

**Comment by Dacendeth** [comment]
Oversight :smirk:

**Comment by adacovsk** [comment]
There might be a related issue: you can do surgery on eyes on headless bodies, might want to check that too. See #9528 and #9394

**Comment by Cyadox** [comment]
> There might be a related issue: you can do surgery on eyes on headless bodies, might want to check that too. See #9528 and #9394

I'll look into it but I think that's unrelated.

**Comment by Cyadox** [comment]
@adacovsk Just tested, it's an unrelated issue. I can see about fixing it, but I think that'd be best for a separate PR. The issues you linked are to do with how dismemberment works, not the surgery itself.

**Pull request merged**
