### PR TITLE
Humans With Empty Blood Vessels No Longer Make Blood Splatters

### PR DESCRIPTION
**Pull request by Shadowmech88**
It doesn't really make sense that they'd leave a blood splatter if they have literally no blood, as is the case for bloodless races.

:cl:
 * tweak: Humans with no blood will no longer make blood splatters.

### CODE REVIEW

**Comment by Exxion** [comment]
Bloodless races do leave blood splatters, though
Or at least dionae do
Not sure about skellingtons

This is still a good change though

**Comment by Shadowmech88** [comment]
> Bloodless races do leave blood splatters, though

I know, that's what this PR is attempting to correct.

The "as is the case for bloodless races" in the OP was referring to the state of "having literally no blood."

**Comment by Exxion** [comment]
Oh, I see
Sorry, misunderstood

**Comment by ghost** [comment]
I think things like the syndicate wheelchair of absolute bullshit, and delivery MULEs put into overdrive are a bit snowflake when it comes to blood, in that they just spawn blood splatters

**Comment by Shadowmech88** [comment]
The syndicate wheelchair doesn't have any blood-related code at all, and the MULEs only have code to make themselves bloody when they hit someone. Beyond that, it looks like the blood splatters are spawned as a result of the damage.

**Comment by Exxion** [comment]
No, MULEs do have snowflake code to make big blood splatters when they run over someone, unless that was changed recently

**Comment by Shadowmech88** [comment]
Feel free to look in mulebot.dm.

From what I can see, the only thing that `RunOverCreature()` seems to do related to blood is adjust the MULE's `bloodiness` var, and the only thing that the `bloodiness` var seems to govern is the MULE making bloody tracks, not blood splatters.

**Comment by Sprok0** [comment]
https://github.com/d3athrow/vgstation13/blob/401b7e0f353e7ae8ba219dc5df46f127366ad245/code/modules/mob/living/carbon/human/human.dm#L359

Mule/wheelchair blood spawning is here

**Comment by Shadowmech88** [comment]
I'll just change that proc to call `blood_splatter()` then.

**Comment by Intigracy** [comment]
Were you gonna do that in this PR?

**Comment by Shadowmech88** [comment]
I was, and forgot.
Still am going to, though.

**Comment by Shadowmech88** [comment]
Alright, done.

**Pull request merged**
