### PR TITLE
Bedsheet ghost costumes

### PR DESCRIPTION
**Pull request by jellyveggie2**
Picks up on one of the leftover ideas from #33610 and adds a bedsheet ghost costume to the halloween costume crate

## What this does

Makes all exosuits hood-capable, not just wintercoats (which carry the `obj/item/clothing/suit/storage` baggage), mostly by moving winter coat code up to the `obj/item/clothing/suit` level. 
Also, all you have to now do is set their `hood` var with the desired headwear, since a null `hood` makes it ignore hood functionality entirely. ...You might also need to change the `hood_suit_name` so things like robes aren't referred to as "coats" in a couple warning messages that can crop up while trying to toggle a hood on or off.

The following suits have been converted from two-piece sets to a single suit with a toggleable hood:
- Cult robes (current, old, legacy, snow)
- Chaplain hoodies
- Grim reaper robes
- Sith robes
- Hastur robes
- Necromancer robes (wizard and costume)

Crates, vendors and such will no longer come with a separate hood item for the listed garments.

Winter coats and by extension the hoodies that inherited from them have been converted to the new system, too. 
For suits that change appearance depending on whether the hood is up or not (eg: winter coats, which depend on this as their hood item has no sprite), `hood_up_icon_state` and `hood_down_icon_state` are available.

Adds a new `body_parts_covered` flag, `HIDEBACK`, for garments that should appear as though they're overlaid above the backpack and obscure it from examine.

Adds an `auto_hood` var for suits which automatically equips the hood when set to TRUE (thanks Deity). Applies to cult robes and necromancer robes.

Adds a `force_hood` var for garments where the "hood" is intrinsic to the suit and cannot be removed. Works like `auto_hood`, but in addition to that removes the ability to toggle the hood, and makes it so manually removing the hood removes the suit itself too.

All this just to add some dumb bedsheet ghost that won't look terrible while wearing a backpack or the huge afro hairdo.
Clothes code is cursed, and I fear I might have made it even more so.

Also, disclaimer: I know that being able to unequip the bedsheet by taking it off the head slot would make it feel natural to be able to do the reverse and equip the bedsheet by placing it on the head slot (which would internally equip it to the suit slot). But you can't, because I can't figure out how to make it do so. It's annoying, but I don't have it in me to keep messing around with clothes code for now.

[ghost in da 'hood.webm](https://github.com/vgstation-coders/vgstation13/assets/78439377/e14f506f-e6a6-4e65-922b-7229a59b752f)

Capture1

Updated bedsheet ghost suit sprite by Blithering. 
"Folded" bedsheet and hood are just edits off Blithering's sprite. Inhands are a recolored trader coat inhand.

## Why it's good

Someone (other than just me) wanted a bedsheet ghost costume on the halloween costumes crate.
Also hoodie QoL for a couple clothes.

## Changelog

:cl:
 * rscadd: Adds a ghost costume to the halloween costume crate.
 * rscadd: You may also craft your own ghost costume by cutting up a bed sheet while targeting the eyes.
 * tweak: A number of robes now have toggleable hoods, just like winter coats.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
Thanks for doing this. Super cool

**Comment by Eneocho** [comment]
Requesting that instead of saying Unknown, it says Bedsheet Ghost during april fools (or normally).

**Comment by Hinaichigo** [comment]
It should be craftable from a bedsheet.

**Comment by cloutcode** [comment]
closes [#31659](https://github.com/vgstation-coders/vgstation13/issues/31659)

**Comment by falcon2346** [comment]
Speedmerge this NOW we only have 6 days left!

**Comment by angryturnip** [comment]
But can I dip it in ectoplasm to be allowed into Port Phasmatys?

**Comment by jellyveggie2** [comment]
Halloween/April Fools description, same as examining an actual ghost.
Untitled

**Comment by Hinaichigo** [comment]
I like the way you implemented the crafting with the zone selection.

**Comment by DeityLink** [comment]
I've provided some extra polish since you've touched cult clothing.

jellyveggie2/vgstation13#1

**Comment by Blithering** [comment]
I look forward to roving bedsheet ghost gangs this halloween

**Comment by Eneocho** [comment]
speedmerge oh god oh fuc

**Comment by DeityLink** [comment]
We should keep doing halloween bus in November

**Pull request merged**
