### PR TITLE
Adds proc for filling an area with map elements, raised vault amount to 5-15

### PR DESCRIPTION
**Pull request by unid15**
#12908 but by me

* Added get_dimensions() proc to map elements, and get_map_dimensions(file) proc to maploader. Both of them return a list with the map file's width and height.

* Added populate_area_with_vaults() proc. It randomly fills an area with multiple vaults. The vaults will not overlap with each other. The area can either be an actual area object, or a list of turfs.

* Added datum/map_element/customizable/vault_spawner for testing the proc above. It fills a rectangle (from 4x4 to 400x400) with random vaults

* Made vault spawning use the proc above - a lot of bad code removed, now you can change amount of spawned vaults

* Incorporates #11994, raising amount of spawned vaults from 1-10 to 5-15.

### CODE REVIEW

**Comment by unid15** [comment]
Raised amount of vaults to 5-15. This also made generation slightly slower overall - 15 vaults will take about a minute to generate

also they sometimes won't respect each other's personal space anymore http://puu.sh/sUIGl/7e2fc33258.jpg

**Comment by Probe1** [comment]
These need to be reviewed but they're way over my head.

**Review by PJB3005 — APPROVED** [review]

**Comment by Intigracy** [comment]
tfw map changes + merged without maptools
tfw duplicate tile definitions

IT WAS YOUUUUUU

**Comment by Probe1** [comment]
SUCH A LUST FOR REVENGE

**Pull request merged**
