### PR TITLE
Drug Tolerance Updates

### PR DESCRIPTION
**Pull request by west3436**
Expands on the system created by @kane-f in the following ways:
- Overdose levels no longer are stationary and instead follow a parabolic increase as tolerance increases. These levels eventually match the tolerance itself, leading to a loss in effects of a certain drug. 
- Advanced Reagent Scanners now will show drug tolerance levels in terms of units. A tolerance of 5u means any consumption level equal to or less than 5u will not result in any effect but will increase your tolerance and satisfy addictions.
- Adds Naloxone which can be used to reduce drug tolerances. This is meant to be used with a doctor present, as it sedates the patient and causes continual toxin damage, requiring close monitoring and precise dosages.

Following this, I intend to create PRs to implement some drug-specific addictions.

:cl:
 * rscadd: Adds Naloxone, a sedative anti-addiction drug used to reduce drug tolerance at the expense of toxin damage.
 * rscadd: Advanced Reagent Scanners can now identify drug tolerance levels.
 * tweak: Overdose levels now increase with drug tolerance levels to a certain point before falling to the tolerance level.

### CODE REVIEW

**Comment by djkramer123** [comment]
what part of addiction or tolerance is actually fun for anyone involved

**Comment by Eneocho** [comment]
I'd say it is not fun for anybody, but I don't really remember how does the tolerance system works, as in, how much does it increase per dose and how does tolerance affect the reagents having an effect.
If this in any shape or form nerfs medicine or funchems like sports drink or honk serum then nobody will accept it, medical is already a wild ride without having to deal with yet another (unfun) thing or having to nanny someone who took naloxone, and nerfing the fun uses for non medical chems makes any chem experimenting a chore.

**Comment by west3436** [comment]
> what part of addiction or tolerance is actually fun for anyone involved

Smokers and oxycodone or hyperzine addict RPers

**Comment by west3436** [comment]
> I'd say it is not fun for anybody, but I don't really remember how does the tolerance system works, as in, how much does it increase per dose and how does tolerance affect the reagents having an effect. If this in any shape or form nerfs medicine or funchems like sports drink or honk serum then nobody will accept it, medical is already a wild ride without having to deal with yet another (unfun) thing or having to nanny someone who took naloxone, and nerfing the fun uses for non medical chems makes any chem experimenting a chore.

This doesn't add any tolerance gains associated with any chems like I said in the OP. If you're still confused about the base mechanics, see #31994.

**Comment by djkramer123** [comment]
> > what part of addiction or tolerance is actually fun for anyone involved
> 
> Smokers and oxycodone or hyperzine addict RPers

sounds like something that should be an RP thing and not a game mechanic then

**Comment by west3436** [comment]
> > > what part of addiction or tolerance is actually fun for anyone involved
> > 
> > 
> > Smokers and oxycodone or hyperzine addict RPers
> 
> sounds like something that should be an RP thing and not a game mechanic then

You are arguing against the tolerance mechanic in its entirety which is already merged. I'd suggest making an issue report to remove it if you feel inclined, but until then I'd rather not use this PR to redo the entire addiction/tolerance debate that was held when this was first made.

**Comment by djkramer123** [comment]
> > > > what part of addiction or tolerance is actually fun for anyone involved
> > > 
> > > 
> > > Smokers and oxycodone or hyperzine addict RPers
> > 
> > 
> > sounds like something that should be an RP thing and not a game mechanic then
> 
> You are arguing against the tolerance mechanic in its entirety which is already merged. I'd suggest making an issue report to remove it if you feel inclined, but until then I'd rather not use this PR to redo the entire addiction/tolerance debate that was held when this was first made.

If you're going to be contributing to it, don't be surprised if people are going to discuss the system as a whole, especially given the fact the original PR was a split vote.

**Comment by west3436** [comment]
> sounds like something that should be an RP thing and not a game mechanic then

This same argument could be used against roundstart lisp, blindness, deafness, and other disabilities.

> If you're going to be contributing to it, don't be surprised if people are going to discuss the system as a whole, especially given the fact the original PR was a split vote.

This is akin to screaming "REMOVE CULT" in any cult-related PR, but fine.

I want to reiterate two things:
1. This PR does NOT add any tolerances to any chemicals. This will have zero impact on anyone's gameplay until a PR to actually add tolerances is merged.
2. Tolerance levels are entirely configurable. I am not sure what @kane-f had imagined, but I see addictions and tolerances more as things which can be eventually set at roundstart rather than things that arise in a single round unless it's a heavy drug like oxycodone or cocaine. For example, in the disabilities screen for character selection, an option could exist to choose a nicotine addiction. For someone who is not addicted, tolerance could be set such that smoking an entire pack of cigarettes over an hour increases your tolerance such that it takes two cigarettes to get the same effect from nicotine than it took an hour ago.

**Comment by ghost** [comment]
well i like the idea of adding a chemical that actually treats addiction and tolerance, definitely eases the pain of anything having it

**Comment by luigil101** [comment]
yes, we get it, you're perpetually asshurt at the existence of hyperzine and want to punish people for using it

**Comment by west3436** [comment]
> yes, we get it, you're perpetually asshurt at the existence of hyperzine and want to punish people for using it

Great criticism retard

**Comment by Kammerjunk** [comment]
I have a sneaking suspicion that people just don't like the system altogether.

**Comment by xeroxemnas** [comment]
> > yes, we get it, you're perpetually asshurt at the existence of hyperzine and want to punish people for using it
> 
> Great criticism retard

t. grudgecoder

**Comment by west3436** [comment]
> > > yes, we get it, you're perpetually asshurt at the existence of hyperzine and want to punish people for using it
> > 
> > 
> > Great criticism retard
> 
> t. grudgecoder

I didn't even make the system dumbass I am just trying to improve on the already-merged system

**Comment by SacredAtom** [comment]
this dumb, kanef system dumb too and i wont elaborate why

**Comment by luigil101** [comment]
> 




> > > > yes, we get it, you're perpetually asshurt at the existence of hyperzine and want to punish people for using it
> > > 
> > > 
> > > Great criticism retard
> > 
> > 
> > t. grudgecoder
> 
> I didn't even make the system dumbass I am just trying to improve on the already-merged system

the improvement would be removing the system, not piling more petty passive aggressive shit on top of it

**Comment by west3436** [comment]
> not piling more petty passive aggressive shit on top of it

This is how I know you haven't even read my OP. This adds a way to read tolerances IC using the scanner, a drug to actually reduce tolerances instead of just waiting them out, and increases OD limits with tolerance instead of just keeping them flat. You are silly.

**Comment by d3athrow** [comment]
If you're going to implement a medication with a real world equivalent then make it work the same. naloxone isn't a sedative nor does it affect tolerance of anything. it's just an opioid receptor antagonist.

**Comment by west3436** [comment]
> If you're going to implement a medication with a real world equivalent then make it work the same. naloxone isn't a sedative nor does it affect tolerance of anything. it's just an opioid receptor antagonist.

I understand that it doesn't do the same thing irl - I had initially planned to name it something silly like NanoCan but wasn't sure if we were strict about realism here. Seeing as there's a lot of pushback on this and the system itself, I'm just going to close this.

**Comment by Eneocho** [comment]
Realism is kind of a mess. While we have realistic chems with realistic reactions (such as diethylamine), we also have some with unrealistic reactions, such as:
(Aluminium) Silicate being sprayable to instantly fix a window.
Citalopram curing hallucinations (real citalopram can actually CAUSE hallucinations in rare occasions).
Methylin (Ritalin) having no effect on humans despite being a very common ADHD medication.
Oxycodone needing plasma on the recipe.
Paroxetine being an anti-suicide chem despite being just an antidepressant.
Chloral causing nigh-instantaneous sleep.
Etc. 
If you want to add a chem with a real life name, try to make it behave very similar to said real chem.

**Pull request closed without merging**
