### PR TITLE
Add occupancy limit to inflatable shelters

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
This makes it there's a limit to the number of mobs that can an inflatable shelter at once. The occupancy limit is 25 units and each mob takes up space based on the square of the mob size as follows:
- tiny mobs (mice): 1
- small mobs (corgis): 4
- medium mobs (humans): 9
- large mobs: 16
- huge mobs: 25

So one shelter can can fit 2 humans, 1 corgi, and 3 mice. Or 6 corgis and 1 mouse. Or 25 mice.

## Why it's good
Adds a bit of sanity with regard to fitting into inflatable shelters, so the presence of one won't be able to save the whole crew from atmos mishaps. Also could add some stuff like situations where people are fighting over space and have to decide who gets to go into the shelter and who has to face the station atmos.

## Changelog
:cl:
 * rscadd: Inflatable shelters have a limit to how many mobs can fit into them at once; two humans, one corgi, and three mice are the most a single single shelter can hold.

### CODE REVIEW

**Comment by west3436** [comment]
Make fat humans count as a large mob

**Comment by SonixApache** [comment]
i don't see why you would make this inconsistent with lockers, crates, etcetera

**Comment by Securitymain** [comment]
I've just had too many kino situations where a brave individual drags half the station behind him. Don't take this from us. It's boring just dropping dead.

**Comment by Substance455** [comment]
they'll nerf the capacity of the shelter, but not implement any system where you can drag a specific individual out

this is just proof that c*ders are my worst enemy, my arch nemesis

they watch my gameplay and wonder "hmm, how can we mess with him?"

**Comment by Inorien** [comment]
thank you subs, very based

**Comment by ghost** [comment]
Dude you're fun to play with IC but the problem here is that you seem to not understand the one simple truth and nobody bothers to explain it to you.
**Do not fix what is not broken.**
Fires, plasma, shelters and, regarding your past PRs, temperature mechanics in general already work fine as is. Plasma gas and fires are very robust but so are the means of protecting yourself from them - atmos hardsuits and inflatable shelters/doors/walls. Gas/chemical temperature simulations are already complex enough to be fun to play around with, so there is no need to make them any more complex.
Remember: "best" is the main enemy of "good".

**Comment by Hinaichigo** [comment]
Lockers have some uses for transporting large amounts of mobs or corpses and I think people wouldn't like that if I added this onto here. They're used for different things primarily and I don't think there's a big problem in how they're used or that it'd be ideal to mix things up here.

>Do not fix what is not broken

It's arguable. To me it seems like just boring that I can escape into the shelter and sit there safely essentially without consequence. When I'm playing, and there's a big disaster, I want to struggle for survival and limp my way to the shuttle with plasma in my eyes and people dying around me, I want to sometimes collapse in the hallway to escape and not make it. I want that added drama and challenge that having atmos be dangerous poses. Same with other hazards, like the singulo, xenos, etc. It's fun to be challenged and adds to the drama of the story of the round.

**Comment by falcon2346** [comment]
Make it so you can kick people out of your shelter or pull people from it. Just having the limit doesn't add much drama unless you can desperately try to pull someone out in order to save your own skin.

**Comment by Hinaichigo** [comment]
Draft to try to add that.

**Comment by pedr69** [comment]
>I want to struggle for survival and limp my way to the shuttle with plasma in my eyes and people dying around me

noone's forcing you to enter the shelter bro, you can run into the plasma fire if you want
if you enter the shelter, you still need someone in a spacesuit to come and drag you around

**Comment by ghost** [comment]
> Draft to try to add that.

After having a discussion in the thread yeah I changed my mind and think you should do this.

**Comment by wotisjanitor** [comment]
Kek what a manlet b*tch

**Pull request closed without merging**
