### PR TITLE
changing-references-of-subversion-in-the-pai-software-downloader-to-cvs-because-nt-uses-outdated-technology

### PR DESCRIPTION
**Pull request by SysadminJeroen**
I hope that I got the terminology correct.
https://github.com/d3athrow/vgstation13/pull/8631#issuecomment-192399370
https://github.com/d3athrow/vgstation13/pull/8631#issuecomment-192400665

### CODE REVIEW

**Comment by clusterfack** [comment]
Why the fuck are you making a new PR for this

**Comment by SysadminJeroen** [comment]
@clusterfack It is a different thing, and you can only accept ONE.

**Comment by ghost** [comment]
:+1: :+1: :+1: :+1:

**Comment by ghost** [comment]
https://en.wikipedia.org/wiki/Revision_Control_System
WHEN

**Comment by 9600bauds** [comment]
this is kind of getting out of hand

**Comment by PJB3005** [comment]
No this https://en.wikipedia.org/wiki/Source_Code_Control_System

**Comment by 9600bauds** [comment]
Just name it "PAI Appstore" or someshit

**Comment by PJB3005** [comment]
pAI package manager

**Comment by ghost** [comment]
I prefer SCCS. Do it.

**Comment by clusterfack** [comment]
Make another PR and they'll ALL be denied

**Comment by SysadminJeroen** [comment]
@DrCelt & @PJB3005 As far as I know RCS and SCCS are local. So it would make pretty much no sense to use any source control management anymore but instead you should use a package manager.

**Comment by PJB3005** [comment]
No

Better idea.

NTSC (NanoTrasen Source Control)

**Comment by SysadminJeroen** [comment]
@PJB3005 Unless you write NanoTrasen Source Control fully every time, people might confuse it with National Television System Committee.

**Comment by clusterfack** [comment]
If we're going to call it NTSC may as well call it PAL because pais are my pals

**Comment by gbasood** [comment]
package control manager is better
also holy fuck in the future just make one PR and ask people what they think and change it if necessary

**Comment by SysadminJeroen** [comment]
@gbasood That is another way of doing things, might do that in the future.

**Comment by Intigracy** [comment]
christ just make one PR and decide what you want the choices to be in the OP, then just say it's ready to merge after you decide and change it

**Comment by Intigracy** [comment]
oh sood beat me to it

**Comment by 9600bauds** [comment]
Can we merge one of these already

**Comment by gbasood** [comment]
None of them say package control manager yet so no

**Comment by SysadminJeroen** [comment]
@gbasood I prefer not to make a fourth PR without @clusterfack's approval or he may fuck all the PRs in the ass.

**Comment by gbasood** [comment]
@Jeroen52 Why the fuck would you make a new PR
Just change this one

**Comment by clusterfack** [comment]
That would imply they use git, which they may not.

**Pull request merged**
