### PR TITLE
[box] Expanded maint and goonecode containment. Some bugfixes too

### LINKED ISSUE #2287: SM Shard for Derelict
Please add it.. for the love of the autism MoMMI's

### PR DESCRIPTION
**Pull request by CptWad**
gooone
skub
monkey trouble
Other notes
1. Toxins test site moved back per request
2. New toys scattered around the map, collect them all!
3. Thing in space was scrapped _for now_
4. Fixes #2287 #3420 #7745 #7853 #8124 #8174 and #8178
5. Monkey room was remade, check below
5. Supermatter now does not broadcast shit off z-level, thanks @PJB3005 
6. put in all of @NigglyWiggly 's pets, besides the spider. Thanks dylan
7. Moved atmos's lightswitch somewhere it can be reached
8. Increased the size of virology, added a newscaster.
9. Another pill collector and some antibody scanners

### CODE REVIEW

**Comment by PJB3005** [comment]
This time the PR is good :+1:

**Comment by 9600bauds** [comment]
\>inexplicable lush grass beach with palm trees and a monkey card game party
\>walled off in a corporate space station
\>except for auxiliary cyborg recharge station which has a window to it for some reason
Uhhh...

**Comment by CptWad** [comment]
Tinted window but yes.

**Comment by 9600bauds** [comment]
This is Holodeck reject tier to be completely blunt
I also have to say that if you're expanding Maint, this would be the perfect chance to work on some better random maint spawners.

**Comment by CptWad** [comment]
I dunno how to do that but ok

**Comment by DrCelt** [comment]
:+1:

**Comment by TermedClepe** [comment]
That grass area is terrible, completely out of place and feels like an oh-so-random thing.

**Comment by Zth--** [comment]
:+1:

**Comment by Skullyton** [comment]
:+1: The little peace garden looks like it'd make a nice maintenance hideaway, also liking the shop to the left of it

**Comment by gbasood** [comment]
I like the little garden but I feel like it doesn't belong at all on Box.

**Comment by CptWad** [comment]
How bout I nuke the trees? They are a tad out of place.

**Comment by gbasood** [comment]
It's more the whole idea of a little lush spot with monkeys in them in the middle of maintenance. Feels more like something you'd find on Deff

**Comment by CptWad** [comment]
Alright hmmm

**Comment by CptWad** [comment]
monkey
alright hows this?

**Comment by Ephx1** [comment]
I recommend, if you're trying to make the tcomsat a bit harder to navigate, either remove the cameras nearby, or make it so the AI can't interact with the APCs. Otherwise they can just flick each one off to help people snag the code better.

**Comment by SarahJohnson489** [comment]
cptwad, look at modules/maps/spawners/spawners.dm . You can see their placement in defficiency as well.

**Comment by SarahJohnson489** [comment]
Like Ephx said, try and crib the ai protection the boxstation telcomms turret controller has and also toggle the ai control wire on the apc's in the telcommsat control and smes room

**Comment by CptWad** [comment]
fug I forgot the cameras, I meant to delete those.
As for spawners I mean to mainly use the seed ones for the ghetto botony and the one extra loot spawner. 
I don't really want to fiddle with too much of the spawners lest you insist

**Comment by Ephx1** [comment]
I only ask that you keep the southern most x-ray camera on the outside that allows you to see the teleporter area.
Unless you feel that's a necessary nerf.

**Comment by CptWad** [comment]
There we are and that wasn't too bad either

**Comment by clusterfack** [comment]
It'll make blob a little more interesting on this map at least, but I feel like it'll become the 'go to' spawn point and everyone will end up checking there immediately after the meta adjusts.

**Comment by IratePirate** [comment]
10/10 expansion.

**Comment by CptWad** [comment]
Anyone mind if I also address
#3420
#7745
#7853
#8124
#8174
and #8178?

**Comment by Skullyton** [comment]
Go right ahead, you've got map authority over box ATM

**Comment by CptWad** [comment]
fug @9600bauds is this the vent?
dick

**Comment by 9600bauds** [comment]
It's the vent named Arrival Shuttle Hallway Vent Pump #2

**Comment by CptWad** [comment]
They are not named in the mapmaker, I identified it because its on var was 0 where all others were 1 so yeah thats fixed

**Comment by CptWad** [comment]
hos
smether
pipe
paperchem
phalanx
on

**Comment by 9600bauds** [comment]
What a weird rendition of Loss

**Comment by CptWad** [comment]
aaaaaAAAAAAA 
but yeah that fixes all of them. I also double checked my maint shit and theres nothing wrong about them atm. If you want more in game pics of maint or goonecode holler

**Comment by AutismSpider** [comment]
Got the lossssssssss wrong

**Comment by CptWad** [comment]
I just uploaded them all at once from my now crowded desktop which I might clean next week at this rate

**Comment by PJB3005** [comment]
Erm, just saying but if you're gonna add a supermatter shard to the map, you're really gonna need to add the code changes to `supermatter.dm` from #4222.

**Comment by CptWad** [comment]
Oh
well
ill do that later today then. The reason that never merged was because mapmerge fuckery right?

**Comment by PJB3005** [comment]
Nope it was EOLs screwing up for some strange reason but at the time I didn't know enough about git to do anything about it.

**Comment by CptWad** [comment]
Aight ill throw you in as the person who did it since ill be stealing your code

**Comment by NigglyWiggly** [comment]
Why are you trying to make Box maint look like Defficiency not-Maint
That's silly and unnecessary.

**Comment by CptWad** [comment]
The drip still exists its just not in the CMO office.
As for Deffs-Not-Maint these are actual maint shafts and are radiation proof and all that. Uses the proper areas and such

**Comment by NigglyWiggly** [comment]
Yes but they look like notMaint
As in they look like they're just there to be easter eggs and stuff
Box's maint has always been just actual maintenance tunnels with a few little closets and areas in it, not jut abandoned areas and stuff

**Comment by CptWad** [comment]
There used to be plenty of abandoned rooms in box before they were replaced with stuff. But I understand your dectraction

**Comment by NigglyWiggly** [comment]
This would also be a good time for me to shill that the pets I made for a bunch of people still aren't on most maps.


If you actually think it'd be a good idea:
Sasha-HoS
Corpus-CMO
Norris-Xenobio
Dessert-Chef
S̶a̶l̶k̶-̶V̶i̶r̶o̶l̶o̶g̶i̶s̶t̶  -(Will still evolve into fully grown giant spider, thanks Dylan)
Salem-Librarian

**Comment by CptWad** [comment]
Aight, ill put it on my todo list. 
also
>GEE CMO HOW COME NT LETS YOU HAVE _TWO_ PETS?

**Comment by NigglyWiggly** [comment]
Because the CMO having a cat is silly when a snake makes more sense

I wish you could have it randomly pick between one or the other, I might make more variant pets for different jobs if that was possible

**Comment by CptWad** [comment]
Would you be cool if I just renamed a cockroach Salk in place of your spider?

**Comment by NigglyWiggly** [comment]
Runtime going to parameds is cool
The reason I wanted Salk to be a spider is because of the spider virus mang, I suppose I could just make Salk a cockroach with the spider icon, but I don't know what cockroachs act like or anything

**Comment by CptWad** [comment]
Actually nah. Ill just wait for it to be fixed first. Theres a cockroach virus too which is why I suggested it.
Then again the difference between a spiderling and a cockroach is that cockroaches can be walked over to get killed so nah

**Comment by Shadowmech88** [comment]
@NigglyWiggly 
>I wish you could have it randomly pick between one or the other

Make a new animal called Runtime-Corpus. In its New() have it randomly spawn either Runtime or Corpus and then delete itself. Add Runtime-Corpus to the map.
If I'm correct, now at roundstart when the animal is created it should randomly create one of the two animals and then delete itself, effectively doing what you want.

**Comment by CptWad** [comment]
@PJB3005 OK I tried it and the code did not compile.
what do
>"code\modules\supermatter\supermatter.dm:208:error: missing left-hand argument to +."

**Comment by CptWad** [comment]
Okay [NFD] me I dont want to fuck this PR up while I am still ahead.

**Comment by Zth--** [comment]
Someone a while ago made a disposal's book with useful information for cargo. Is it possible by any chance to add it this PR?

**Comment by Zth--** [comment]
#6800

**Comment by CptWad** [comment]
oh lawd
how do I add books?

**Comment by Shadowmech88** [comment]
@CptWad 
Look at the code for the Space Law books.

**Comment by CptWad** [comment]
@Shadowmech88 & @Zth-- it needs to path to its own book image it seems, is one already in the game?

**Comment by Shadowmech88** [comment]
>it needs to path to its own book image

I'm not sure what you mean.
Like the book has to be in the library database already?

**Comment by CptWad** [comment]
It needs its own icon_state I guess

**Comment by Shadowmech88** [comment]
Just find where the book icons are in the code and give it literally any of those icons.

**Comment by CptWad** [comment]
Aaaaaah how about I add it later along with @Arthurdentist 's astronaut thing?
I can even add it to all maps next time

**Comment by Shadowmech88** [comment]
You could even give it exactly the same icon_state that the robotics manual has, no one's going to care what it looks like.

**Comment by 9600bauds** [comment]
Don't hardcode the book, make it into its own wiki page and make the book point to that page

**Comment by CptWad** [comment]
well yeah I can just make the wiki page, right now in fact but I keep changing the PR and the more I change it the more I feel like its going to sit here and I dunno, Ill make the wiki page now

**Comment by Shadowmech88** [comment]
@CptWad use the temporary wiki at game.ss13.moe.

**Comment by CptWad** [comment]
http://game.ss13.moe/wiki/index.php?title=Disposal_Mail

**Comment by CptWad** [comment]
Heres all the changes I had yet to post pictures of
viro
cmo
loss
Other thing is the toxins test site which I honestly cant tell the difference, just that its too big to take a picture of

**Comment by CptWad** [comment]
oh boy

**Comment by Skullyton** [comment]
GL HF

**Pull request merged**
