### PR TITLE
Fixes #13691

### LINKED ISSUE #13691: no skin for cargo IDs on the identification computer
#### Description of issue
in the "card skin" section of the identification computer there is no skin for cargo jobs IDs.
i haven't tried all the jobs so i don't know if something else is missing.

#### Difference between expected and actual behavior
expected having choice for all ID skins
some are missing

#### Specific information for locating

ID computer menu

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * bugfix: Cargo and trader ID skins are available at the Identification Computer.

### CODE REVIEW

**Comment by jakmak5** [comment]
+1 for cargo -1 for trader. Trader ID's are suppose to be essentially vox passports into human controlled space instead of being used in a human corporate setting

**Comment by DamianX** [comment]
I had doubts about that. I thought since we had the option to make syndie ones it wouldn't be such a big deal.

**Comment by jakmak5** [comment]
wait we can make syndi ID colours on standard ID consoles? Why is that a feature

**Comment by DamianX** [comment]
Yeah, the comment says // yes no?
I guess one one really cares. But I'll revert the trader one.

**Comment by Shadowmech88** [comment]
>Trader ID's are suppose to be essentially vox passports into human controlled space

The question is though, should HoPs be capable of issuing them?
Currently if a non-crewmember somehow makes its way onto the station, such as a grown diona, the HoP's only option for giving them an ID is to give them a proper crew ID.
The trader ID skin could be used to denote identification cards that aren't meant to make someone part of the crew.

**Comment by DamianX** [comment]
Or we could sprite a new ID for people that are not crew members nor traders but are allowed to be on the station and have some access. But that would be outside the scope of this PR.

**Comment by Exxion** [comment]
Update that changelog now that you can't use the trader skin

**Comment by Probe1** [comment]
image

This is how it currently looks.  Fix that formatting abomination.

**Comment by Probe1** [comment]
For bonus brownie points rename syndie to anything except syndie.

**Comment by Intigracy** [comment]
Honestly I'd prefer if HoP's can issue the trader skin but not the syndie one.

**Comment by DamianX** [comment]
Let's make a vote? Emojicracy? Something? wat do

**Comment by yclatious** [comment]
I kind of liked being able to issue syndie ids, always liked how silly it was to have the option and always did look nice. I say to let the fun stay.

**Comment by Probe1** [comment]
Post image

**Comment by DamianX** [comment]
image

**Comment by ComicIronic** [comment]
Let's not keep the man waiting.

**Pull request merged**
