### PR TITLE
Plant mutations are faster.

### PR DESCRIPTION
**Pull request by Eneocho**
It can take anywhere from 4 to 10 seconds for a mutation tick to happen. This doubles the chances of a mutation tick happening, effectively halving the time.
:cl:
 * tweak: Doubles the chances for a plant mutation tick, effectively halving the time required for a mutation to happen.

### CODE REVIEW

**Comment by adacovsk** [comment]
Why though, isn't it consistent with old rates?

**Comment by Eneocho** [comment]
It's kinda weird that water ticks every second but all mutagens take fucklong to tick. Making them tick each second would be unbalanced as shit, this is a decent middle ground.

**Comment by Hinaichigo** [comment]
It's already plenty fast I feel.

**Comment by Eneocho** [comment]
It's the delay itself which bothers me, not the mutation rate. I find myself scanning the plant 10 times and it has yet to consume 1u Mutagen. This is just a quick attempt at reducing said delay without going into a full mutation rework such that there's no artificial delay while keeping the same rate.
Half assed, honestly. I'll see if I can rework it a bit in a different way.

**Comment by Hinaichigo** [comment]
Something I found out recently is there's a 'fast objects' category that ticks every 0.5 seconds, faster than the normal 'processing objects'

**Pull request closed without merging**
