### PR TITLE
Bacteria, Virii, and Parasites

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds two new subtypes of disease, bacteria and parasite

 - Bacteria, advances quick, but only has 3 symptoms, resets infection stage upon new infection
 - Parasite, slow to advance, low infection rate, but preserves stage of infection
 - Virus, what we have currently, but when infected, only drops a single stage rather than full reset.

image

:cl:
 * rscadd: Adds two new subtypes of disease. Parasite and Bacteria.
 * rscadd: Parasites are slow to advance, low base infection rate, but preserves stage of infection once a new person is infected.
 * rscadd: Bacteria advances quickly, higher base infection rate, but only has 3 symptoms and resets infection stage upon new infection
 * tweak: Viruses, when a new person is infected, the new disease is dropped a stage in the new recipient.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
The true metaclub is the viro metaclub

**Comment by SonixApache** [comment]
[update WIKI]

**Comment by DrSnips** [comment]
I really like this a lot. My only concern is gibbingtons and parasites leading to meaty exploding syringes.

**Comment by Ephx1** [comment]
SHUT
DOWN 
_EVERYTHING_

**Comment by Arthurdentist** [comment]
merge when

**Pull request merged**
