### PR TITLE
Makes blob point collection lag immune

### PR DESCRIPTION
**Pull request by clusterfack**
Blob points are now changed to be distributed based on the time since the last life() tick instead of having a set amount per life() tick. This stops lag from lowering the number of points received from blob life() of cores, though lag will still affect things like pulse() which affect both resource/factory nodes. 

Incidentally this will about double the base generation rate of points for a single blob core, which seems needed both for beginning blobs as well as extra overminds that often barely get any points at all.

### CODE REVIEW

**Comment by clusterfack** [comment]
Running into a macro issue which I'll figure out in a min

**Comment by Probe1** [comment]
Doubling its points when blob has a fair chance at success seems a little insane.

I'm not opposed to like, a 25% increase at most but that's sledgehammer balance.

**Comment by clusterfack** [comment]
Its not doubling its points, its doubling the point generation of the core only.

**Comment by Probe1** [comment]
Alright the core only, my mistake.  That's much more moderate and I'm ok with this.

**Comment by DeityLink** [comment]
That gives naked cores a 1.5x buff or so. It's gonna be easier for blobs to get started now.

**Comment by clusterfack** [comment]
Just what they needed really

**Pull request merged**
