### PR TITLE
Grey jumpsuits dissolvable in water

### PR DESCRIPTION
**Pull request by adacovsk**
[hotfix]

Missed a few in the last PR. These are mothership jumpsuits, not regular jumpsuits

## What this does
- makes grey jumpsuits dissolvable

## Why it's good
- head canon

## Changelog

:cl:
 * tweak: Grey jumpsuits, while resistant to acid, dissolve in water!

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Assistantbros... not like this...

**Comment by Optimism333** [comment]
Thank you, kind sir

**Comment by WindowsErrors** [comment]
Thank you for the reddit silver, kind stranger!

**Comment by nervere** [comment]
Can they be cleaned off with acid? If not, they'll have no way of being washed (unless the washing machine somehow doesn't use water).

**Comment by Eneocho** [comment]
I will only accept this canon if we get a cotton-like ayyplant with fruit that melts in water.

**Comment by adacovsk** [comment]
> I will only accept this canon if we get an ayyplant with fruit that melts in water.

eventually

**Comment by Optimism333** [comment]
> I will only accept this canon if we get a cotton-like ayyplant with fruit that melts in water.

If you really want ayy botany, I encourage you to give making some seeds/plants a try, man. It IS on my list, but it's behind quite a few things that I want to do first.

Best I can say is that I might get to it by the start of next year, if making an ayy away mission and other new content goes really well.

**Comment by ShiftyRail** [comment]
Showers just got deadlier. I guess.

**Pull request merged**
