### PR TITLE
Husbando

### PR DESCRIPTION
**Pull request by SonixApache**
Adds Husbando, the male equivalent of Waifu.
Turns you male and equips you with the 'callum' suit which we had in the rsc.
Accompanied by a `X reveals his true outfit in a vortex of ripped clothes!` message.
Open to suggestions.

transformation: https://streamable.com/q4cxkj
suitdrink

- [ ] Update wiki

If you want to see more low-effort jokes like this please pay my salary
https://www.patreon.com/pomf

🆑 
 - rscadd: Added Husbando, made from manly dorf and karmotrine.

### CODE REVIEW

**Comment by Gazathor** [comment]
here at /vg/, we strive for true equality.

**Comment by Dacendeth** [comment]
What if both waifu and husbando are in your system, do you just constantly change genders and outfits?

**Comment by SonixApache** [comment]
Yeah, it swaps constantly. Not sure what determines which one you end up with, but it's pretty funny to watch. Bugs out the animation as well.

Someone suggested making Waifu and Husbando mix into Fujoshi or something. Needs more input.

**Comment by AI-Is-Rogue** [comment]
With the addition of this new sprite, you can now set up anime wire art with heterochromia anime eyes and tiny eyebrows.
Aside from that, I like the usage of the shirt-rip to reveal formal clothing trope.

**Comment by Eneocho** [comment]
As per discussed on the /vg/ thread (https://boards.4channel.org/vg/thread/297120261#p297262771), what would happen if you drank both Waifu and Husbando?
It should collide the effects of both, into a new drink: Tomboy, makes you a female with a randomized name but wearing suits and stuff.
MAKE IT HAPPEN SONIXAPACHE, PLEASE.

**Comment by Eneocho** [comment]
Anon said:
Waifu, Husbando, and Tomboy should all let you at least select your new first name (after first drinking, so you don't get spammed from 500u of it in your system). Make it prompt for renaming like borgs.
Will give the HoP something to do for a name change on your ID.
Awkward HoP visits are great.
"So, I got tomboy'ed...I hate the clown..."

Makes sense, please make it happen.

**Comment by ghost** [comment]
> 
> 
> Anon said:
> Waifu, Husbando, and Tomboy should all let you at least select your new first name (after first drinking, so you don't get spammed from 500u of it in your system). Make it prompt for renaming like borgs.
> Will give the HoP something to do for a name change on your ID.
> Awkward HoP visits are great.
> "So, I got tomboy'ed...I hate the clown..."
> 
> Makes sense, please make it happen.

sounds gay

**Comment by tuypo1** [comment]
A name change screen alarm sure
an instant prompt would be a bad idea, if you somehow get waifu or husbando in your system in the middle of a fight or some emergency situation that short moment where you are immobile could mean your death

**Comment by Dacendeth** [comment]
If you didnt want to do anything fancy you could make them cancel each other out, like antitoxin and toxin.

**Pull request merged**
