### PR TITLE
Removes Impedrezene from Parapens

### LINKED ISSUE #13284: Parapens contain impedrezine.
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
As things stand, the only not-awful use of the tricky dicky pen is to enable gimmicks and such where you need one or two captives. But this is nonviable when the pen gives the victim 200 brain damage. The brain damage used to be fun when you could buy them from cargo and poke everybody, but that has been removed so the imped should be removed too.

### PR DESCRIPTION
**Pull request by BobdaBiscuit**
Fixes #13284 I've removed Impedrezene from the traitor bought parapen, and updated the description to match it.

Visible changes are the victim no longer has their view blocked from passing out, no longer gets 200+ brain damage, no longer remains drowsy while walking around after the other drugs wear off.

Victim gets paralysed at the same time from being injected, and remain paralysed for the same time.

:cl:
 * tweak: Removed Impedrezene from traitor bought paralysis pen, your victim no longer ends up critically brain damaged.

### CODE REVIEW

**Comment by BobdaBiscuit** [comment]
V E R I F I E D

**Comment by ghost** [comment]
Why wouldn't their view be blocked if they're PASSED OUT

**Comment by ComicIronic** [comment]
Because they don't pass out any more, presumably.

**Comment by Intigracy** [comment]
Pufferfish venom makes you unable to move or speak but you still experience every pain inflicted upon your body and have full awareness.

In spess we use carpotoxin to make it and call it zombie powder.

**Comment by BobdaBiscuit** [comment]
Celt it's cause they don't pass out, it's a paralysis pen, not a sleepy pen silly.

**Comment by BobdaBiscuit** [comment]
For probe.
[on asking about the pr]
OOC: Repertor: will make parapens good for hostages
OOC: SonixApache: seems aight

**Comment by TheFriggenSawbones** [comment]
yeah it sounds good

one time I tried to parapen eimplant a clown as a cool prank but him being retarded forever after is rough

**Comment by mrpain666** [comment]
If you cant kill and behead your target by the time he wakes up you're unrobust and shouldnt be buying it anyways

**Comment by BobdaBiscuit** [comment]
A reminder that the reasoning for this from the issue is nerds want to use it so they can capture other nerds for gimmicks, and they cannot if their hostage is braindead.

**Comment by Probe1** [comment]
That isn't a bad reason since I've seen players do that lately.

**Comment by Intigracy** [comment]
Doot doot

**Pull request merged**
