### PR TITLE
Ports janibelts

### PR DESCRIPTION
**Pull request by ghost**
Tired of having wet floor signs take up space in your backpack so that you don't get lynched?
wondered if there was a final solution?
introducing Janibelts!
These fancy belts carry the janitorial supplies including wet floor signs! No more clunk and clatter in your backpack.
image
They spawn in custodial closets
:cl: 
 *rscadd: Added Janibelts that hold janitorial supplies and signs, they spawn in custodial lockers

### CODE REVIEW

**Comment by PJB3005** [comment]
> can't hold mop.

**Comment by ghost** [comment]
WELL it's mostly for floor signs
but if people want i guess i can make it hold mops

**Comment by PJB3005** [comment]
> can't hold trash bag.

**Comment by ghost** [comment]
janicart can already hold the trashbag my negro

**Comment by Blithering** [comment]
The only thing in that screenshot that can't fit in a slim-belt is the light replacer, might as well let it carry bags and the mop to give it more of a use.

**Comment by ghost** [comment]
alright i'll add the trash bags and mop

**Review by PJB3005 — APPROVED** [review]

**Comment by SonixApache** [comment]
holosigns when

**Pull request merged**
