### PR TITLE
Refactor Immovable Rod

### PR DESCRIPTION
**Pull request by clusterfack**
I'm going to fall asleep now but I've remade immovable rod. It's pretty neat now if you throw one at the station.

Things I want to fix before this gets merged.
- It needs a better method for choosing targets and the target should terminate at the end of the zlevel approximately
- Still has some stupid issue where the appearance is all fucked up when it's tearing through the station instead of being like a normal projectile

### CODE REVIEW

**Comment by AutismSpider** [comment]
So have it pick random mob on the station Z level and it makes B line to it?

**Comment by CptWad** [comment]
god I hope so

**Comment by FudgePucker** [comment]
Maybe have it also select a mob via admin intervention. For when cluwning someone isn't enough and need to rip a giant hole in the station.

**Comment by CptWad** [comment]
@FudgePucker sounds like a good way to break up some ERP

**Comment by mrpain666** [comment]
@FudgePucker I approve!

**Comment by clusterfack** [comment]
Technically finished in its current state.

Immovable rods are now projectiles,
also courtesy of pjb

**Comment by Exxion** [comment]
So since it only blows up dense objects, are you safe if you lie down?

**Comment by CptWad** [comment]
Yeah but would you be fast enough?

**Comment by clusterfack** [comment]
Yes, I was initially going to give it a chance to hit nondense mobs but then it kept hitting my ghost so I wasn't entirely convinced that was a good idea.

**Comment by Exxion** [comment]
@CptWad Just lie down as soon as you get the "What the fuck was that?" command report

**Comment by clusterfack** [comment]
I'm fairly sure the what the fuck was that command report comes after it actually hits?

**Comment by Exxion** [comment]
Oh
It probably does because the other ones do but I'm stupid and didn't think of that

**Pull request merged**
