### PR TITLE
pies now splash people

### LINKED ISSUE #10947: Throwing a cream pie at someone doesn't splash the contained reagents on them
Will fix tomorrow.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #10947

also the partial pathing is all removed

ACTUAL CHANGES:

```
 /obj/item/weapon/reagent_containers/food/snacks/pie/throw_impact(atom/hit_atom)
+   if(ismob(hit_atom))
+       var/mob/Igothit = hit_atom
+       src.reagents.reaction(hit_atom, TOUCH)
+       var/client/assailant = directory[ckey(src.fingerprintslast)]
+       if(assailant && assailant.mob && istype(assailant.mob,/mob))
+           var/mob/M = assailant.mob
+           msg_admin_attack("[M.name] ([M.ckey]) threw [src] at [Igothit.name] ([Igothit.key]). Reagents: [reagents.get_reagent_ids(1)] (<A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=[Igothit.x];Y=[Igothit.y];Z=[Igothit.z]'>JMP</a>)")
    ..()
    if(isturf(hit_atom))
        new/obj/effect/decal/cleanable/pie_smudge(src.loc)
-       if(trash) new trash(src.loc)
+       if(trash)
+           new trash(src.loc)
        qdel(src)
```

### CODE REVIEW

**Comment by 9600bauds** [comment]
t o m o r r o w

**Comment by ghost** [comment]
⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛⚛?

**Comment by Intigracy** [comment]
```
 /obj/item/weapon/reagent_containers/food/snacks/pie/throw_impact(atom/hit_atom)
+   if(ismob(hit_atom))
+       var/mob/Igothit = hit_atom
+       src.reagents.reaction(hit_atom, TOUCH)
+       var/client/assailant = directory[ckey(src.fingerprintslast)]
+       if(assailant && assailant.mob && istype(assailant.mob,/mob))
+           var/mob/M = assailant.mob
+           msg_admin_attack("[M.name] ([M.ckey]) threw [src] at [Igothit.name] ([Igothit.key]). Reagents: [reagents.get_reagent_ids(1)] (<A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=[Igothit.x];Y=[Igothit.y];Z=[Igothit.z]'>JMP</a>)")
    ..()
    if(isturf(hit_atom))
        new/obj/effect/decal/cleanable/pie_smudge(src.loc)
-       if(trash) new trash(src.loc)
+       if(trash)
+           new trash(src.loc)
        qdel(src)
```

**Comment by 9600bauds** [comment]
> 1,285 additions, 1,171 deletions not shown because the diff is too large

WHAT DID YOU DOOO

**Comment by FudgePucker** [comment]
Oh man polyacid mutagen pies as clown antag.

**Comment by Intigracy** [comment]
removed all the partial pathing

the above is the only actual change besides that, though you're free to compare if you don't believe me :)

**Comment by ghost** [comment]
But seriously, why would a pie transfer ALL the contents in it? A beaker makes sense. A pie? Some should be lost.

**Comment by 9600bauds** [comment]
Why shouldn't it

**Comment by ghost** [comment]
@9600bauds the reasons seem pretty obvious to me.
If a pie has 50 cm^3 of sulphuric acid in it, and it's splattered over you, it'd have a very different effect than 50cm^3 of sulphuric acid being poured on you from a beaker.

**Comment by 9600bauds** [comment]
So, muh realisms?

**Comment by ghost** [comment]
Of course.

**Comment by Intigracy** [comment]
Regardless of how much is in either you're still getting the same damage,
whether it's 1 unit or 100.

**Comment by ghost** [comment]
@Intigracy that's awful

**Comment by Intigracy** [comment]
Beakers are also re-usable, pies are one hit wonders.

**Comment by Kurfursten** [comment]
Just to be clear here, pies will no longer leave pie tins or smudge the ground if you hit a person with them?

I don't think I like that

**Comment by Intigracy** [comment]
Yes they will.

**Comment by Intigracy** [comment]
The proc I changed is called multiple times, once on a mob, the last time
always being a turf.

**Comment by Kurfursten** [comment]
Still not sure about this though. Basically turns every pie into a super-syringe gun

Like a syringe gun it's one shot, but unlike a syringe gun you get up to 50u instead of just 15u and don't need a protolathe

**Comment by 9600bauds** [comment]
syringe guns don't get stopped by masks

**Comment by Intigracy** [comment]
It's not ingested, it's splashed.

It's not a syringe gun or something magically powerful compared to
something that exists already.

**Comment by Rattlederp** [comment]
Don't the pie remains catch fire? Does this mean the people will catch fire too? New weapon confirmed

**Comment by Exxion** [comment]
That's not caused by a reagent, so no

**Comment by gbasood** [comment]
Maybe pies should have low max reagents I don't know
Also not sure what kind of crust or pie tin withstands polyacid

**Comment by ComicIronic** [comment]
On this week's episode of reviewing shit after a week of it being dead:

throw_impact has a user argument, do you don't need to use client voodoo to find the thrower. You may want to check that user isn't null, because throw_impact is also called by ZAS and the like.

**Comment by ComicIronic** [comment]
RIP this PR for now

**Pull request closed without merging**
