### PR TITLE
Stops lobby players seeing captain announcements

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[bugfix]

## Changelog
:cl:
 * bugfix: Lobby players can no longer read captain announcements.

### CODE REVIEW

**Comment by adacovsk** [comment]
wouldn't `(M.client && !istype(mob/new_player)` be slightly better?

**Comment by Eneocho** [comment]
Soulless

**Comment by PrimeDSS13** [comment]
sovlless

**Comment by west3436** [comment]
The definition of soulless

**Comment by pedr69** [comment]
make them able to see the heads offices RC announcements too

**Comment by jwhitak** [comment]
Didn't someone try this PR before?

**Comment by Eneocho** [comment]
> Didn't someone try this PR before?

Secbaton tried to make it so you couldn't hear announcements if there were no tcomm relays on the Z-level (see #33407).

**Comment by SECBATON-GRIFFON** [comment]
it is... le SOVLLESS. BECAUSE IT JUST IS OKAY!!!!

**Comment by bathosbathtime** [comment]
You offer no justification for your change yet complain about the lack of explanation for the push back.

**Comment by SECBATON-GRIFFON** [comment]
well it was pretty inconsistent with RCs and etc and i assumed it was a bug

**Pull request closed without merging**
