### PR TITLE
If no players, choose from all compiled maps at random

### PR DESCRIPTION
**Pull request by adacovsk**
[emojithis]

I'm thinking that if there are no players, it might encourage people to join if a rare map is loaded randomly once the round ends. Feel free to downvote into oblivion

### CODE REVIEW

**Comment by Eneocho** [comment]
Time to gunk the round so nobody joins to have a chance to roll lamprey.

**Comment by Armadingus** [comment]
It doesn't work.
t. forced meme maps on lowpop.

**Comment by jwhitak** [comment]
Ah yes, an incentive to not play! If it's dead pop now you shouldn't play and wait for the server to restart itself until you get rare maps.

Basically, this could actually reduce pop.

**Comment by djkramer123** [comment]
awful idea, are you this desperate to see line played

**Comment by adacovsk** [comment]
> It doesn't work. t. forced meme maps on lowpop.

be specific, what you do mean?

**Comment by Armadingus** [comment]
I mean that I've both forced maps like line, deff, lamprey, dorf. Sometimes a player had asked for me to do it, sometimes it was just because I felt like it. From my observations, it doesn't put the pop over double digits. Hell, I even had one player request a map and then observe the 0 pop round instead of playing it, the absolute state of obsgang.

**Comment by adacovsk** [comment]
>had one player request a map and then observe the 0 pop

lol

**Comment by WindowsErrors** [comment]
although dorf does sound like the meme map to be shoehorned into deadpop because of its dynamic of the two or three autistic cargo workers and shaft miners doing all the work while everybody else is busy throwing chemicals at each other and wondering where this ladder goes

**Pull request closed without merging**
