### PR TITLE
Using a remote signaler on wire-hackable stuff now brings up the wire-hack menu

### LINKED ISSUE #8569: Using a remote signaler on an airlock doesn't open the hacking dialogue
What this ends up on is that you need to use a multitool or wirecutter on the airlock, so that you can then put the remote signaler in. Which is really silly and mildly inconvenient

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #8569

### CODE REVIEW

**Comment by Probe1** [comment]
Thanks for sorting this out.  The issue arose when a user was able to electrify doors without it being logged which is sticky for admins.

**Comment by 9600bauds** [comment]
But this is not related to logging

**Comment by Probe1** [comment]
I was sure I posted inthe right pr

**Comment by ComicIronic** [comment]
Replace it with a macro to avoid these edits in the future. 

iswiretool (), possibly.

**Comment by 9600bauds** [comment]
Will do tomorrow

**Comment by Kurfursten** [comment]
no siretool allowed bauds

ERP is bannable

**Comment by ComicIronic** [comment]
:ok_hand:

**Comment by clusterfack** [comment]
I like macros especially when people use them in an inventive and useful way

**Pull request merged**
