### PR TITLE
Gallon of PCP

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
Adds this as a game item. Acts like hyperzine while also causing hallucinations and purging chillwax from the system, found in contraband crates.

## Why it's good
It provides a good conversation piece.
[https://www.youtube.com/watch?v=tFUvmZWf4hI](https://www.youtube.com/watch?v=tFUvmZWf4hI)

## Changelog
:cl:
 * rscadd: Gallons of PCP are now available as an item. You didn't even know they came in liquid form!

### CODE REVIEW

**Comment by Dacendeth** [comment]
This chem should be the anti-chillwax, removing if from your system like antitoxin removes toxin.

**Comment by ghost** [comment]
it was brought up recently that we have too much content that isn't actually accessible in the game so this should have some means of obtaining if it's to be merged

**Comment by west3436** [comment]
definitely make this a simple recipe like hyperzine + mindbreaker heated up to a certain point, it's by no means an OP chem that should be gated behind a bus

for the gallon thing you could make it come in the janny cargo crate when the emagged options are available (have it replace the normal bleach bottle)

**Comment by Eneocho** [comment]
I checked the bleach bottles a while back and they spawn with 30u bleach despite the 100u volume for some reason and I can't quite figure out how to fix it. You might want to check that if you plan on having the 100u of PCP bottles actually contain 100u.
Also, what west said, just add a recipe with mindbreaker and 'zine heated to say 200°C.

**Comment by Theophrastus1** [comment]
oh yeah just got my gallon of pcp

**Comment by djkramer123** [comment]
you're here forever

**Comment by ManopolisJones** [comment]
You could always give it a chance to appear in the contraband crate with the happy pills and the like.

**Comment by SECBATON-GRIFFON** [comment]
> You could always give it a chance to appear in the contraband crate with the happy pills and the like.

done

> This chem should be the anti-chillwax, removing if from your system like antitoxin removes toxin.

done

**Comment by Eneocho** [comment]
Can you use PCP to bypass the trader Pax implants (not to be confused with the paxbans, though it would be interesting if it also bypassed those)? As in, you CAN be hostile if implanted with the Pax, but only when metabolizing the PCP.

**Comment by Kurfursten** [comment]
No, it doesn't do that

**Comment by Eneocho** [comment]
Still think adding a recipe as well would've been appropriate.

**Pull request merged**
