### PR TITLE
Radsuit crate

### PR DESCRIPTION
**Pull request by jknpj**
Because someone in the thread requested. Comes with a four radsuits and geiger counters. No need for engineering access but as expensive as a fucking supermatter shard.

:cl:
 * rscadd: Adds a radiation suit crate to cargo for 500 wagebux, it comes with a four radsuits and geiger counters

### CODE REVIEW

**Comment by Pathid** [comment]
With drag-around-a-shard memes being so easy to pull off, radsuits should be looked at as WMDs. I'd say put it in a secure engineering crate if I thought it would really do anything, but of course our guy would already have a way to get the shard crate open.

**Comment by pantherpusher** [comment]
They contain lead, clearly they must be kept away from children and untrained personnel.

**Comment by jknpj** [comment]
Alright, it needs engineering access now.

**Comment by Pathid** [comment]
🤷‍♂️ 
Like I said, locking it will likely not do anything to slow down the lowpop shard massacre. Suppose the essence of the problem is more with the shards than the suits, but currently having to access engineering for a radsuit is a necessary piece of the puzzle. Now you'll be able to get everything from the cargo shuttle.

**Comment by FudgePucker** [comment]
Yea I have to agree. Rad suits are harder to get than hard suits. Letting cargo do shard memes without leaving cargo is a bad idea

**Comment by jknpj** [comment]
You need a foam extinguisher/mesons to do your memes you'll need to go to engineering to get that foam anyways.

I find really bad that something to counter radiation is used mainly to abuse radiation but that's an issue with the shard itself.

**Comment by ghost** [comment]
Shard memes need to be removed, not balanced around

**Comment by Pathid** [comment]
The foam is a decent point since that's an optimal way of shard-blasting people, but it's not necessary. Mesons you can get in maint.

**Comment by SonixApache** [comment]
make sure you use that cool nuclear crate sprite for it

**Comment by jknpj** [comment]
what cool nuclear crate?

**Comment by SonixApache** [comment]
radiation

**Comment by jknpj** [comment]
All right i tweaked it a little bit. You now get four suits/geigers for 500 credits and no engineering access. I hope this makes it more used on emergency situations and less with shard murderbone.

**Comment by SonixApache** [comment]
I'd still keep the engineering access honestly.

**Comment by Pathid** [comment]
The unique crate sprite is great, you know what's in there right away. It's better than a lock in some ways.

**Comment by jknpj** [comment]
I feel like they're more emergency-friendly without a secure lock, hell, even radiation closets don't have one.

**Pull request merged**
