### PR TITLE
Adds a bluespace beacon to Spessmart

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I like the place, it should be visited more often but it's in the literal nowhere of space if it even spawns in the first place. I also wanted to do this before I forgot. Miners don't even have an incentive to visit space much anymore, meaning only vox would probably get to it if they even got to it in the first place.

:cl:
 * rscadd: Spessmart now spawns with a bluespace beacon when it appears, meaning you can go there using a teleporter.

### CODE REVIEW

**Comment by jknpj** [comment]
You miss the point of it being a vault

**Comment by boy2mantwicethefam** [comment]
Travis is having a fart because I compiled it and worked on my end
@jknpj Russian satellite does this already

**Comment by jknpj** [comment]
Yeah but it also has russians, viscerators and turrets. On top of being easily cheeseable, spessmart also has the best loot of all vaults.

**Comment by SonixApache** [comment]
Just add the destination disk to the black market instead.

**Comment by boy2mantwicethefam** [comment]
it's not that hard to cheese and it's still kinda uncommon for it to spawn, plus it has teleblock and a bunch of checks for items to not be allowed to leave without triggering security
@SonixApache there's no way to check if certain vaults spawned, destination disk will do nothing if spessmart doesn't exist
also isn't black market slowly going to die out because nobody's adding stuff to it?

**Comment by SonixApache** [comment]
You could just make the spessmart vault add its destination disk to the black market when it spawns. 
Look at the code for the mecha graveyard disk.

**Comment by jknpj** [comment]
>ERROR: 'step_y' found on line 216. Remove it, please.
ERROR: 'step_x' found on line 216. Remove it, please.

I'm never trusting you over travis again @boy2mantwicethefam

**Comment by boy2mantwicethefam** [comment]
@SonixApache The mecha graveyard is guaranteed to spawn when the trader vendor spawns
@jknpj No idea my dude, lemme try again

**Comment by Kurfursten** [comment]
You can do this in the vault's preload(), this is where other vaults load dungeons (for example fishing vault loads the wine cellar)

**Comment by IzayaChan** [comment]
merge this and tell anybody who complains to fuck off to /tg/ station

**Comment by Kurfursten** [comment]
I actually don't care very strongly about this one way or the other, but uhh isn't ignoring the emojis something TG codebase is well known for?

Isn't TG also well known for making powerful space/lavaland loot easier to obtain?

**Comment by MadmanMartian** [comment]
@boy2mantwicethefam Only reason the russian sat has one already is keeping it 1:1 with the original version.

Don't use an edge case and claim it is the norm

**Comment by ghost** [comment]
If you want to even consider doing this you will have to completely gut the items you can buy there. Otherwise everyone will have extremely easy access to powerful weapons and equipment.
The greatness of spessmart is in it's rarity. It is unarguably the best vault based on loot, and making it accessible this easily to everyone is just silly.

**Comment by boy2mantwicethefam** [comment]
I guess I'mma do the uhhhh black market disk thing but if it ends up being merged and then black market gets removed I'm gonna give the disk to the v*x

**Comment by Kurfursten** [comment]
Just commenting to say, oof that branch name

oof that commit name too

**Comment by tuypo1** [comment]
You should have to search for it but it really should spawn every round, it must suck to spend ages looking for it only to eventually find it never spawned
Maybe instead of having to manually comb space there was some lengthy minigame you could use to find it, maybe steal the minigame goon has where you can unlock away missions

**Comment by Blithering** [comment]
I'd like the black market to have a random destination disk as one of its items

**Comment by Zth--** [comment]
Bang bang

**Pull request closed without merging**
