### PR TITLE
New alt title for janitors: Maid

### PR DESCRIPTION
**Pull request by CodenameB**
A very simple PR that allows janitors to select "maid" as an alternate job title at spawn. This will spawn them with maid clothing.

Men can also be maids if they so choose. I don't judge.

:cl:
 * rscadd: "Maid" added as an alternate job title for janitors.

### CODE REVIEW

**Comment by ghost** [comment]
anybody else having a hard time getting a good footing on this slope?

**Comment by yclatious** [comment]
I sure as fuck ain't, especially after telling everyone how it would happen, but no, its impossible that tilting to either polarity is bad, lets merge shit that changes the current balanced status quo, itl fix shit, letting a waifufag code bullshit.

**Comment by Arthurdentist** [comment]
absolutely not

**Comment by ghost** [comment]
slippery slopes DO make for fun water slides so i support this in the end

**Comment by FudgePucker** [comment]
I endorse this PR :+1:

**Comment by FudgePucker** [comment]
Hey maybe now more people will play janitor.

**Comment by ghost** [comment]
njet

**Comment by JustSumBody** [comment]
oy VEY

**Comment by CodenameB** [comment]
RIP.

**Comment by RFultra** [comment]
reo:b:en :b:r

**Comment by ghost** [comment]
this will make people take up the job slot just to be autistic tbh
i have an alternate solution to this

**Comment by RFultra** [comment]
New service job
"service" maids?

**Comment by Gringonius** [comment]
It's funny, because this is almost harmless compared to the cosmetics machine which did get merged.

**Comment by Exxion** [comment]
?????
This is vastly worse

**Comment by Gringonius** [comment]
@Exxion 
Please explain how as any janitor can easily go to the theater for the same effect. Not to mention that almost no HoP denies simple title changes.

**Comment by Exxion** [comment]
And when's the last time someone actually did it?

How is a vending machine harmful in any way?

**Comment by Gringonius** [comment]
It's been a long while since I've seen something like that happening, but it can be asked with the same logic when was the last time someone did play as a maid janitor and how is an alternative title different in any way.

The harm of the machine is more than obvious with the sort of people it attracts and panders to.

**Comment by ghost** [comment]
Delete this

**Comment by Exxion** [comment]
It really isn't, since I don't see it.
It has exactly zero effect on anyone who doesn't use it.
Alright, not EXACTLY zero, since other people get to see a few colored pixels on the faces of those who do, but how bothersome could that possibly be?

**Comment by Gringonius** [comment]
Exactly, how bothersome is it to have someone with an alternate job title?

**Comment by Exxion** [comment]
There's a connotation here
But you're right, "vastly" was probably too strong an adverb

**Comment by nuklearcellphoneg** [comment]
I love adverbs

**Pull request closed without merging**
