### PR TITLE
There is now a one in a million chance to set of the nuke when you kick it.

### PR DESCRIPTION
**Pull request by ExpulsionSnooper**
[gamemode]

SOMEBODY STOP ME!

:cl:
 * rscadd: There is now a one in a million chance to set off the nuke when you kick it. Wearing the RD's shoes nullifies your kick.

### CODE REVIEW

**Comment by Eneocho** [comment]
On my way to spend 40 rounds kicking the nuke on the offchance it goes kablooey.

**Comment by Kurfursten** [comment]
Dumb PR; ending the round should not be done as a joke effect

We cannot possibly justify extremely stupid PRs on the basis that they are very rare. For example, if tackling someone had a 1 in a trillion chance of daybanning them, we would not do it just because lol it's rare.

Kudos to the original 4 lads who managed to sneak in a react emoji before it closed though

**Comment by ExpulsionSnooper** [comment]
It was worth a shot.

**Comment by Eneocho** [comment]
We can't have nice things. Goddamnit kurf.

**Comment by pedr69** [comment]
i think it would be fine if instead of instantly detonating and ending the round, it would anchor itself, go delta and start a 3 minute timer
as is is now noone gives a shit about the nuke, except when it's blob, when sometimes people will remember it exists

**Pull request closed without merging**
