### PR TITLE
Z levels only process if there's a player on that zlevel

### PR DESCRIPTION
**Pull request by MadmanMartian**
Just a silly idea I had, when I heard that TG or somewhere had processing only happen when a player was on it.

Needs to be enabled in config, and when it is, creates a list in the map subsystem that holds however many zlevels there are amount of lists.

Each list holds a reference to a mind datum, which is moved around during z level transition.

Currently object, machinery, mob, and some atmospheric machine processing require there to be a mob on the zlevel, should the list of lists be initialized.

Also, moves the on_z_transition event to on_z_transition proc (atom level), which is called by a players move and forceMove, rather than everywhere.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Will this have any mysterious effects on the mining Z level? For example, the mining outpost gets breached, so miner fixes the window and decides to head back to main station while it refills... but then the level pauses since no scientists are in the outpost no traders in the traderpost?

**Comment by MadmanMartian** [comment]
Yes. One of the unforseen consequences I was worrying about

**Comment by Tehsapper** [comment]
i am sure there are ways to metagay abuse this.
it's worth it if it reduces the CPU lag significantly.

**Comment by Exxion** [comment]
I guess it's a good option to have, but our CPU usage is low enough right now that I think the drawbacks outweigh the benefits
Remember that TG's atmos processing is vastly more expensive than ours

**Comment by MadmanMartian** [comment]
Let's leave it for now then, should we ever need it we can just reopen the PR

**Pull request closed without merging**
