### PR TITLE
Probably fixes revs

### LINKED ISSUE #26250: Revs music will go on ENDLESSLY
I'm not sure what the conditions are for revs music, but they seem wrong. A round where 3 of the headrevs died and 1 headrev became a Robocop borg continued on, revstended, with the music blaring all the way through for two hours. There's no way to stop the music even if you change your settings mid-shift and it's pretty confusing even just as an observer

image

### PR DESCRIPTION
**Pull request by Zth--**
`Probably` because I didn't test it

Fixes #26250

:cl:
 * bugfix: Fixes revs not ending

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Wasn't the problem that one rev was borged? Just make it check if the rev is a silicon

**Comment by ShiftyRail** [comment]
There were runtimes as well.

**Comment by Zth--** [comment]
There was a runtime on that same line I fixed https://github.com/vgstation-coders/vgstation13/blob/8cfdc095d9b6a8d9d27f7f2ac0fcfd6803166bc4/code/datums/gamemode/factions/syndicate/rev.dm#L152

A runtime halts the current proc so it doesn't continue processing. In this case this proc was checking if the revs were defeated but it couldn't do it because some rev had no body and it was runtiming.

A borg rev would still have a body and access to `stat` but maybe borging doesn't pass the mob reference to the gamemode? I don't know, but it's possible.

Was any rev singulo'd or gibbed that shift?

**Comment by DamianX** [comment]
Yeah, the brains were eaten.
re: cyborg: I think borged revs would still pass this check. Cult snowflake coded this scenario, see `/datum/role/cultist/PostMindTransfer`

**Pull request merged**
