### PR TITLE
Bumping into someone won't interrupt their pulling

### PR DESCRIPTION
**Pull request by DamianX**
### **ATTENTION**
This is shitcode.
I'm not sure how to make it better, I need help.
It does work, though.

:cl:
 * tweak: Bumping into someone who is pulling something won't interrupt their pulling anymore.

### CODE REVIEW

**Comment by jknpj** [comment]
>have someone pull you
>bump them
SONIC 3 & KNUCKLES

#13403

**Comment by DamianX** [comment]
Maybe bumping into someone just shouldn't be calling `forceMove`. Ideas?

**Comment by Exxion** [comment]
No, it should call regular `Move()`, or one of the step procs
But that would still cause the above

Maybe make it so that if the person you're pulling bumps into you, it still interrupts

**Comment by SonixApache** [comment]
>he actually did it

you absolute madman

\*edit*
On the subject of not stopping pulling, #14671
prepare for unforeseen consequences.

**Comment by RealestEstate** [comment]
does this mean we get conga-lines?

**Comment by MusgardTiger** [comment]
Bumping into somebody is one of three ways that you can stop somebody from dragging shit. Other two methods are stunning and pushing, first is not always available and latter depends on your speed and rng. 

I don't know if I misunderstand the point of this change, why do you want to do it?

**Comment by DamianX** [comment]
Dragging anyone that isn't cuffed in crowded areas (medbay comes to mind) is a pain in the dick

**Comment by MusgardTiger** [comment]
Pulling stuff and people and stopping people from doing that is unironically a big part of the game. Intentionally bumping into people to stop them from dragging something is not easy but it is still the easiest choice out of all your options. Changing this to alleviate some annoyances in a workplace will cause more annoyances inside and outside of it.

^ This was just the player vs player perspective on it. There is a delicate balance in pulling stuff while you are on different intents, on help intent it is extremely useful to pull non collidable stuff like horizontal spacemen and items in a crowded workplace while using mouseclick move them to different tiles to avoid pushing people away from their workstations (which usually ends up with them pushing you back if you don't) is very important. Pulling stuff on intents other than help while you drag stuff like vertical spacemen, machinery and closets have its own very valuable use.

That being said I think the best way to avoid accidental help intent pushing would to be make it so that you can't be moved a tile away from the thing you are pulling. 

and that ^ being said it is very important that you should be able to move yourself or other spacemen by walking into them on help intent while dragging shit.

**Comment by MasterofNothing** [comment]
This is just an idea, but what about making an item like a grapple hook for security? You put the 'hook' or chain into one hand, use it on the cuffed person, and they're latched to you? You drag them with you, with the distance between the security officer and the prisoner being one tile? To release the hook, you could either use it on the prisoner again, or have it be a two-handed sprite where you can drop the sprite in the auxiliary hand.

I'd like that more than this change.

**Comment by DamianX** [comment]
Pushed for posterity a commit that begins to address the things that need to be done but I'm bored of this, so I'm closing it.

**Pull request closed without merging**
