### PR TITLE
trader cards now look a bit more shitty

### PR DESCRIPTION
**Pull request by Intigracy**
before/after
tradertradernew

inspired in part by the id in this image
b3917dfc-c911-11e6-9df8-a9fd2e904f37

### CODE REVIEW

**Comment by Probe1** [comment]
👌

**Comment by kilozombie** [comment]
I'm confused, what even is the melty part supposed to be?
They're NT-issued, not scavenged, so it's a little weird to me

**Comment by Ephx1** [comment]
You expect near braindead birds to keep something in good condition?

**Comment by kilozombie** [comment]
Keep in mind all their other gear is pristine, as is Box Station's outpost. I'm fine with some of their stuff (stuff that they don't technically own, like a license) looking fine.
This just feels slightly out of place to me.

**Comment by Probe1** [comment]
They're not NT issued.  

The description even says it looks shitty.

**Comment by kilozombie** [comment]
I read somewhere they were NT issued and that's why they're allowed to sell shit and exist in Nanotrasen space. If that's not the case, Carry On.

**Comment by Shadowmech88** [comment]
Where are those spritesheets from?

**Comment by Probe1** [comment]
An old bay file that was user specific items that required specific ckeys to use.

**Pull request merged**
