### PR TITLE
Brings back the diagonal movement (for real).

### PR DESCRIPTION
**Pull request by Eneocho**
I liked the april fools diagonal movement, it is ROBUST and fun to use.

Reverts vgstation-coders/vgstation13#32340

### CODE REVIEW

**Comment by Exxion** [comment]
This isn't *quite* the ideal way to do it, since if it's always enabled, there's no point to the code that previously switched it on and off. It's potentially useful to keep the var itself and the checks for it around, though.
Making that change (or, in fact, any change at all) would also have the benefit of making this PR have more than one commit and thus show up as its descriptive title instead of its less-descriptive single commit name in the commit history, if merged

**Comment by gurfan** [comment]
One day late

**Comment by tuypo1** [comment]
far too much of a combat balance impact

**Comment by Eneocho** [comment]
One day you "muh balance" people will understand that balance is second to fun.

**Comment by Exxion** [comment]
t. does not understand game design

That said, I don't think this particular change is non-viable or anything

EDIT: It has occurred to me that the first part of this post is going to sound profoundly stupid to people who don't know what I mean, but I'm just going to leave it unless someone replies

**Pull request closed without merging**
