### PR TITLE
Renamed 'Anti-Toxin (Dylovene)' to 'Dylovene'

### PR DESCRIPTION
**Pull request by DamianX**

### CODE REVIEW

**Comment by jknpj** [comment]
what about medibots and their "ANT TOXEEN ADMINISTURD"?

**Comment by ghost** [comment]
If you're gonna remove one of the two names why remove the less common one?

**Comment by Diavill** [comment]
>not custom naming pills

**Comment by DamianX** [comment]
If I have to rename it 'Anti-Toxin' I will turn Bicaridine into 'Anti-Brute' and kelotane and dermaline into 'Anti-Burn 1' and 'Anti-Burn 2'

**Comment by EdXbtkOEwGw** [comment]
Was renaming iron for no reason not enough for you monsters

**Comment by Pathid** [comment]
@jknpj Here's the kicker with that: if it isn't a green medibot then it's injecting tricordrazine.

**Comment by SonixApache** [comment]
8d979c39eecc13cefb776116f39ea202a0025ba7
  
how about not touching it

**Comment by ghost** [comment]
Pomf literally veto'd this last time, yeah

**Comment by DamianX** [comment]
wew, that's kind of silly, but okay

**Pull request closed without merging**
