### PR TITLE
Removes lowfat cult room

### PR DESCRIPTION
**Pull request by plosky1**
[bagel] [hotfix]

https://i.imgur.com/o9cUEO3.png

### CODE REVIEW

**Comment by Eneocho** [comment]
How will I scare the HoS into going full cultfucker during a non-cult round now.

**Comment by SonixApache** [comment]
Cute change, but why?
before after

**Comment by DeityLink** [comment]
> 
> 
> Cute change, but why?

At my request, following the conversations in #31077 and #31092

**Comment by DamianX** [comment]
\>there's still mapped-in blood
image

**Comment by Kurfursten** [comment]
Make it dried blood

**Comment by plosky1** [comment]
> Make it dried blood

Made it bones instead of blood. I'm not sure where dried blood is in the mappable items, I didn't see anything different from the blood I already had so 🤷

**Pull request merged**
