### PR TITLE
Allows admins to add songs to jukeboxes

### PR DESCRIPTION
**Pull request by unid15**
The songs have to be hosted online, and you have to manually specify their length in seconds. You can add songs in batches, so you can make your own playlists in notepad and then add them all at once.

:cl:
 * rscadd: Admins can now add custom songs to jukeboxes. Added songs don't transfer between rounds.

### CODE REVIEW

**Comment by Exxion** [comment]
Can it not get the length of the song from the file?

**Comment by unid15** [comment]
There *might* be a way, but it's hard

**Comment by Fruktlimpa** [comment]
Time to spawn invisible jukeboxes with the entire Neko sugar girls series and place them in departments.

**Comment by CptWad** [comment]
It would be easier just to set up the dj station then you just make more sound systems

**Comment by Riekland** [comment]
THE PIAAAAAAAAAAAAANO

**Comment by Aurx** [comment]
Needs to be logged.

**Comment by DrSnips** [comment]
On the topic of jukeboxes, how awful would it be to fix the bug where if you leave a room where the song was playing and then go back in it starts playing from the begining

**Comment by unid15** [comment]
Added logging

@DrSnips make a bug report, I haven't encountered that. Try switching to VLC.

**Comment by Exxion** [comment]
@DrSnips That's a WMP bug. Use VLC.
You *have* to use VLC 32-bit. 64-bit won't work.

**Comment by Riekland** [comment]
> 64-bit won't work.

thanks byond

**Comment by DrSnips** [comment]
Alright, I will try it. Thanks for the advice.

**Pull request merged**
