### PR TITLE
Adds generously tiny attack delay to cult runes to prevent massassive spam

### LINKED ISSUE #8386: There's no delay on cultists clicking on runes
Cultists can just keep clicking on a rune with 0 delay and spam the chat forever, there should really be a delay on this shit
image

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #8386
Delay is short enough that nobody could complain about it

### CODE REVIEW

**Comment by ComicIronic** [comment]
I'm complaining about this delay RIGHT NOW

**Comment by 9600bauds** [comment]
Delay is short enough that only a dork could complain about it

**Comment by kol1th** [comment]
> ComicIronic added Needs Final Decision Balance labels 12 minutes ago

Thanks doc

**Comment by Kurfursten** [comment]
I would prefer it raised to 10

This is a complaint

**Comment by 9600bauds** [comment]
I've never actually used runes expertly so I'm not sure if that would step over any legitimate balance concerns

**Pull request merged**
