### PR TITLE
Map Fixes

### PR DESCRIPTION
**Pull request by ghost**
- Remove a few duplicate APCs in Starboard Aft/Med-Sci Maintenance
  (THREE APCs), the Research Outpost Hallway, the Derelict Secondary
  Hallway
- Move an APC on the DJ Station to avoid mounted frame overlap
- Make sure that the remains on the Clown Asteroid spawn in an empty
  space (otherwise they spawn OVER an asteroid wall)
- Extend the Secondary Mining Outpost slightly and replace the canister
  atmos with an air tank
- Change the Mining bridges (the ones with windows) to be supported with
  catwalk instead of lattice

### CODE REVIEW

**Comment by ComicIronic** [comment]
Can we get an image of the mining outpost changes?

**Comment by dylanstrategie** [comment]
Coming up

**Comment by dylanstrategie** [comment]
new_secondary_outpost

**Comment by IratePirate** [comment]
Not sure if I like the catwalks. They're made for walking on. Lattices appear to be mostly just be for holding stuff together. Just a thought.

**Comment by dylanstrategie** [comment]
I prefer catwalks to convey the idea of the air bridges being really structurally sound, which should be the case given there's a double set of window panes and floor tiles

**Comment by IratePirate** [comment]
Fair enough. Just make sure they're on top of the space tile instead of replacing it. From the image it seems to be alright.

**Comment by ComicIronic** [comment]
Catwalks aren't a turf anymore.

**Pull request merged**
