### PR TITLE
Adds three circuits to the board printer

### PR DESCRIPTION
**Pull request by Zth--**
tested

:cl:
 * rscadd: Brewer, soda dispenser, and booze dispenser circuits can be printed at the circuit imprinter.

### CODE REVIEW

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
needs tech requirements, material requirements, and category.

**Review by MadmanMartian — APPROVED** [review]
disregard, I am dong

**Comment by SonixApache** [comment]
get them from cargo

**Comment by Zth--** [comment]
I don't see a valid reason for that though. Almost every single machine can be built from rnd with a few exceptions (telepad for example, which has a balance reason for that), why wouldn't these be available? It's inconsistent.

**Comment by Kurfursten** [comment]
You pose an interesting point. Maybe we should just get rid of the circuits altogether and let you order the machines fully built out of a crate from cargo.

Coffee machine is "too complex" to build on station or otherwise forbidden due to weird bureaucratic OSHA regulations that somehow ban coffee but not supermatter.

**Comment by SonixApache** [comment]
Not to mention that half the maps come with the coffee machine(s) mapped in.
Might as well replace the cargo circuits with flatpacks.

**Comment by ghost** [comment]
Nothing wrong with having multiple methods of making fun bars.

**Comment by SkowronX** [comment]
yesssss

**Pull request merged**
