### PR TITLE
Changes a Dynamic Variable Name For Clarity

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Changes one variable in dynamic to be more clear and reduce confusion between candidates and mode.candidates

### CODE REVIEW

**Comment by Kurfursten** [comment]
This does not change anything (see dynamic readme)

>**NOTE Roundstart deals with both candidates (trimmed list of valid players) and mode.candidates (everyone readied up). Don't confuse them!

**Comment by boy2mantwicethefam** [comment]
This sucks

**Comment by ShiftyRail** [comment]
This is spawning as many traitors and vampires as intended

**Comment by Kurfursten** [comment]
In seriousness, though, it's fine to change this var name for readability, but you need to fix the title and OP to reflect that it's just a backend clarity change.

Also no need for a 🆑 because this won't affect gameplay

**Pull request merged**
