### PR TITLE
Bagelstation: improved armory

### LINKED ISSUE #28160: [Feature Request?]Bagel Armory is Lacking.
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
e6be5cb8a76ddbf9bea88ab95423df06cfbe69bb

# Description
The Bagel Armory is lacking a lot of things, and is rather empty. There are no holsters, and there are a lot of empty racks. Additionally, I don't think there is a roundstart beepsky in it. It could really use some modern touches.

### PR DESCRIPTION
**Pull request by DamianX**
Closes #28160

armory_bagel

:cl:
 * tweak: Bagelstation: the armory has been improved. It's easier to navigate, and it's got more stuff in it such as an ammolathe, a beepsky and holsters. Added a security camera console to the security office.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
what a saint

**Comment by Kurfursten** [comment]
Gee Damian how come your armory has no windoors?

Not that they're strictly needed, just a surprise to see

**Comment by DamianX** [comment]
I tried making one that kept the windoors, it sucked a lot. That's everything that went into the decision of not having them.

**Comment by calzilla1** [comment]
Just make a small glass prison around the Ion, laser, glocks, and eguns

**Comment by DamianX** [comment]
image

**Pull request merged**
