### PR TITLE
Defficiency engineering overhaul

### PR DESCRIPTION
**Pull request by DamianX**
Once upon a time, the AME exploded. And it took all the SMES units with it. Engineers were not happy.
This PR does the following:
- Moves the three SMES away from the AME, just enough not to get shredded when it eventually blows up
- Removes the cabling and floor decals from the old SMES positions
- Moves the lockers and tables that were on the western wall to the opposite one, to make room for the SMES
- Wires the telecomms SMES to the grid (Who designed this?)
- Removes useless cabling from the telecomms room (Who the FUCK designed this?)

It's my first mapping PR so I probably botched this, but I'm feeling confident right now.

Before: 

dreammaker_2017-01-31_00-41-09

dreammaker_2017-01-31_00-42-42

After:

dreammaker_2017-01-31_00-43-38

dreammaker_2017-01-31_00-45-43

:cl:
 * tweak: Moved the defficiency SMES units away from the AME.
 * bugfix: Wired the defficiency telecomms SMES to the grid.
 * rscdel: Removed some useless cabling around defficiency telecomms and engineering.

### CODE REVIEW

**Review by N3X15 — APPROVED** [review]

**Comment by Kurfursten** [comment]
I think we get the point, but turning off turfs was a weird choice for screenshots

**Comment by DamianX** [comment]
It was not deliberate, if I show turfs I can't see the piping/wiring. B Y O N D
image

**Comment by Kurfursten** [comment]
untitled

like this

**Comment by DamianX** [comment]
I think it's a bug with my specific byond version. Or are there settings I need to play with?

**Pull request merged**
