### PR TITLE
fixes pizza rocket

### LINKED ISSUE #32463: Pizza RPGs are fucking SCAMS
so it spawns a bunch of pizza slices right
but look at this
`/obj/item/weapon/reagent_containers/food/snacks/sliceable/pizza
	slices_num = 6
	storage_slots = 4
	w_class = W_CLASS_MEDIUM
	base_crumb_chance = 20`

`/obj/item/weapon/reagent_containers/food/snacks/sliceable/pizza/margherita
	name = "Margherita"
	desc = "The most cheesy pizza in galaxy!"
	icon_state = "pizzamargherita"
	slice_path = /obj/item/weapon/reagent_containers/food/snacks/margheritaslice
	storage_slots = 4
	w_class = W_CLASS_MEDIUM
	food_flags = FOOD_ANIMAL | FOOD_LACTOSE //cheese`
	
	`/obj/item/weapon/reagent_containers/food/snacks/sliceable/pizza/margherita/New()
	..()
	reagents.add_reagent(NUTRIMENT, 40)
	reagents.add_reagent(TOMATOJUICE, 6)
	bitesize = 2`

`/obj/item/weapon/reagent_containers/food/snacks/margheritaslice
	name = "Margherita slice"
	desc = "A slice of the most cheesy pizza in galaxy."
	icon_state = "pizzamargheritaslice"
	bitesize = 2
	food_flags = FOOD_ANIMAL | FOOD_LACTOSE`

the slice doesn't actually start with shit, it comes down from the full pizza when sliced
probably want to make a special subtype that adds reagents in the new()
[bus] [bugfix] [easy] [oversight]

### PR DESCRIPTION
**Pull request by Eneocho**
They now fire nutritious slices.
Closes #32463.
:cl:
 * tweak: Pizza rockets now fire margherita slices filled with nutritious goodness.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
It might be nicer if they fired the slices so everyone can munch on pizza without having it cut it up first. And have more of a pizza explosion feeling.
If you make a new `margheritaslice/rocket` and add
```
..()
reagents.add_reagent(NUTRIMENT, 5)
reagents.add_reagent(TOMATOJUICE, 0.75)
bitesize = 2
```
to its `New()` then it should work I think (numbers assuming each pizza cuts up into 8 slices here).

**Comment by Eneocho** [comment]
I considered that but firing a whole ass pizza is just funnier to me (and you can eat pizza without cutting it). Also pizza cuts into 6 slices, not 8.

**Comment by Hinaichigo** [comment]
True but I like the idea of the rocket hitting something and pizza slices flying everywhere, like you "fired' a whole pizza but it exploded into pizza slice shrapnel upon impact.

**Comment by bathosbathtime** [comment]
I also support the pizza shrapnel.

**Comment by Kharkov72** [comment]
i support pizzacreeping full pizzas but pizza shrapnel would be preferred

**Comment by Kurfursten** [comment]
Do the shrapnel, ask for help if needed. You can see ied or crackerbox code for example. It's just throwing items in random directions.

**Comment by Eneocho** [comment]
The pizza rocket already fired shrapnel like an IED so no change required on that front, I just swapped it from empty slices to whole pizzas. There seems to be a consensus that slices would be better so changing that.

**Comment by Hinaichigo** [comment]
Since `margheritaslice/rocket` inherits from the parent `margheritaslice` you don't necessarily have to include all the vars like `name`, `icon_state` etc, since they'd be the same. The only thing you'd need to have there is the `desc` since it's different, and the `New()` behavior.

**Pull request merged**
