### PR TITLE
Allows AIs to examine things through cameras

### PR DESCRIPTION
**Pull request by JustSumBody**
AIs can examine things if they're in sight of a camera by shiftclicking it
Currently it works fine  ~~on examining objects but doesn't do anything on mobs or turfs for some reason.but now it lets you examine things under static so I'm going to look at that in a bit.~~

We'll use this as a discussion since I've seen arguments against it from a balance perspective. Should AIs be allowed to examine things through their cameras?

### CODE REVIEW

**Comment by ghost** [comment]
I think it's fine, the cameras should be good enough to make out stuff like this

The main problem is that you can examine people on the fly to see their hands and even their pockets (although I'm not certain about the later), so you can catch someone running around an empty room with a "pen" in his hands

**Comment by clusterfack** [comment]
Yeah I think it's a bad idea

**Comment by Allspice** [comment]
AT THE VERY LEAST I would like it if the AI could see actions through the AI eye; it is sort of shit to attempt to infer that this fellow is the cause of that other shmuck dripping red spots.

**Comment by Konater** [comment]
I sure wish this was a thing when I played AI

**Comment by ultraplen** [comment]
Why shouldnt they be able to examine things tbh

**Comment by Ephx1** [comment]
Actions displayed to the AI I'd lean more towards because you could argue even on shitty cameras that actions are very apparent, but then you wouldn't be able to bullshit the AI on what happened so eh?
EDIT: If this part does happen vampires will be forced to be even stealthier, and I'd argue that lings would too.

Examining things will let AI go FULL ON BIG BROTHER and I feel will just piss people off with there already being a stigma about AIs being antaghunters. I'd love a test-run of it though.

**Comment by IratePirate** [comment]
This is a good idea. But make it so that examining allows the person to know that they're being examined in some small way so that they know they might be rumbled.

e.g. a message saying _you hear the security camera lense whirr_

**Comment by 9600bauds** [comment]
What about only allowing the AI to examine things in sight of a holopad hologram?
This is already how it works with visible messages like seeing attack text
You'll know you're being examined because the AI hologram is right there with you

**Comment by IratePirate** [comment]
Well only a few rooms have holopads. I always thought it would be a better idea to have holopads built into the walls instead of the floor.

**Comment by kol1th** [comment]
There are some things that are iffy at best to determine as an AI. What people are holding (no in-hand sprites), If they're asleep/dead, or the extent of the injury. I think it's a good change and is more quality of life than balance. :+1:

**Comment by JustSumBody** [comment]
The inhand thing is what primarily prompted this as well, especially since you can hide a full fireaxe behind your character now (@DrCelt)
An alternative I've considered is having slightly different examine text when examining as AI. Instead of listing all the contents of a mob, it could give a general description based on their health(High toxin damage: "he appears sick," "he is missing [limb]," ,"Sleeping soundly" vs "he doesn't appear to be breathing", whether or not something is covered in blood, etc.) 
I stand by inhands should still be a part of that, but worst case scenario you can lock it behind the high-res malf module.

**Comment by JustSumBody** [comment]
whoops why is the close button right next to comment who does that
At any rate, it is all working in the way I originally intended now. Feel free to pick it apart now.

**Comment by gbasood** [comment]
I feel like examining is specifically not a thing at the moment because it allows the AI to pick out antags impersonating other people ridiculously easily, on top of everything else they have going for them in that regard.

Seeing action text while observing things would be fine though, in my opinion

but hey who am I to say

**Comment by clusterfack** [comment]
I think I agree with both bauds and sood on this

**Pull request closed without merging**
