### PR TITLE
More Renovations and Additions (Mothership Lab Vault)

### PR DESCRIPTION
**Pull request by Optimism333**
## More Lab Maintenance ##
I made a pass through the mothership lab to brush up some of the bosses and mobs. I also added some new items.

### Explorer Armor Vest and Helmet ###
image

image

image

image

Explorers now have their own armor vest and helmet for a unique look. The helmet and vest can fit humans as well. (Pictured above with the uniform) (Special thanks to Blithering for the original vest sprite!)

Stat-wise the vest and helmet have less laser protection compared to a regular vest, but more bullet and explosion protection.

Defense Stats: (melee = 50, bullet = 50, laser = 15, energy = 5, bomb = 30, bio = 0, rad = 0)

### GDR Half Mask ###
image

Adds an ayy gas mask that is resistant to acid but water soluble. Replaces regular gas masks in most areas of the vault.

Zorb carries an advanced version that is resistant to both acid and water.

### Changes to the Hoverdisc ### 
https://github.com/vgstation-coders/vgstation13/assets/81007356/bb3f3167-c97d-42fc-8485-317fca114cb7

- Borrowed the shield block effect that juggernauts have to use as an indicator when melee and ranged attacks aren't damaging the disk (thanks Deity). Bullets also have a ricochet sound when they fail to significantly damage the disk.

- Also gave it a spooky ufo sound that plays occasionally. 

- The hoverdisk can break walls with its melee attack or its upgraded immolation ray cannon.

- When a hoverdisc is reduced to less than half its health, it will become more aggressive.

### More Audio Feedback on Psi Attacks ### 
https://github.com/vgstation-coders/vgstation13/assets/81007356/2e55aa7a-badd-49d0-b6da-fdbf46e81964

- When a mothership surgeon or Zorb psi-attacks a player, they will hear a sound effect play (It's a bit quieter in-game, I swear).

### Changes to Zorb ### 
image

- When Zorb dies, he will make one last psi attack and voice his discontent with the new state of affairs.
- Zorb's pacification psi-attack lasts a bit longer.
- Zorb will get much more aggressive when he is near-death.
- Zorb's melee attack has a better sound effect.
- Zorb gibs on death, will still drop all his gear.

### Deadlier Grey Nurse ### 
image

- The grey nurse first stage has been changed. When it has a paralytic syringe ready to use, it will attempt to rush the player. When the syringe is on cooldown, it will stay a bit further away. Its icon will also update to show a syringe in hand if the ability is ready.

- The grey nurse first stage can knock living mobs away with its melee blows, and will spark when hit with EMP weaponry, further hinting that all is not as it seems.

- The grey nurse second stage has been made deadlier, it now has a short range charge attack that allows it to destroy most basic obstacles (walls, structures, machines) and briefly knock over players (that can be knocked over). Its knockdown melee attack has been removed, and instead its normal melee attack has a base chance to stun: 25%.

- The grey nurse second stage is more vulnerable to EMP damage.

- Both stages have 50 more health, since the Nurse is a solo enemy encounter.

### Deadlier Vox Raid Leader ###
image

- The vox raid leader actually has a name now, "Hakiyikachiyayi the Handchopper". He also has a new ability, definitely completely unrelated to the name.

### New Enemies ### 
image

- Adds an Explorer Guard. One is present in the explorer barracks (he got put on rear guard duty instead of going out with the ufo). Identical stat-wise to a baseline MDF Pacifier.

- Adds an MDF Commando, a spaceworthy ayy soldier equipped with dual disintegrators. Only one is present at the control room with Zorb. Very dangerous due to high damage output.

### Tweak to Vox Raiders ### 
- Vox raiders can now see a short distance in the dark, so they don't do nothing when a target is right next to them, even if there's no light nearby. The assassins, deadeye, and raid leader can see the furthest in the dark.

### Various Minor Mapping Changes ###
- Added GDR half-masks to all appropriate locations
- Added explorer armor to the explorer gear room
- Added a disintegrator to the explosives shed, as a reward for killing or getting past the soldier there
- Added some nanodictionaries to appropriate areas of the vault (greyling dormitory, research division, Zorb's bedroom)
- Added an xcom mysterious armor set to a hidden spot
- Changed Zorb's starting position in the control room. Replaced two MDF regulars with a Trooper and a Commando.

image

[content] [vault] [sprites]

:cl:
 * rscadd: mothership lab vault: Vox Raid Leader and Grey Nurse are more dangerous
 * rscadd: mothership lab vault: Hoverdisc now gives visual and sound feedback when melee attacks or projectiles aren't doing damage
 * rscadd: mothership lab vault: Replaced two MDF regulars in the control room with an MDF Trooper and a Commando
 * rscadd: mothership lab vault: Added some nanodictionaries to various areas of the lab
 * rscadd: mothership lab vault: Zorb will make one last psi attack when he dies
 * rscadd: mothership lab vault: Added sound effect when a surgeon or Zorb uses a psi attack
 * rscadd: mothership lab vault: Added an explorer armor vest and helmet, which have been added to the explorer gear room
 * rscadd: mothership lab vault: Added a GDR half-mask, which is resistant to acid but water soluble

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you add the fancy ayy tiles to the tile painter, please?

**Comment by Optimism333** [comment]
> Can you add the fancy ayy tiles to the tile painter, please?

Can you point me to the file or files, if it's more than one?

Edit: Honestly Prime has a point.

**Comment by PrimeDSS13** [comment]
I wouldn't, it would cheapen the vault.
What's the proper way to kill the disks, anyways?

**Comment by Optimism333** [comment]
> I wouldn't, it would cheapen the vault. What's the proper way to kill the disks, anyways?

EMP weaponry, which is present in the lower armory. Only one disk is encountered before getting access to it.

Three direct hits with an EMP rifle will destroy a disk, or four shots in close proximity.

**Comment by Eneocho** [comment]
> > Can you add the fancy ayy tiles to the tile painter, please?
> 
> Can you point me to the file or files, if it's more than one?
> 
> Edit: Honestly Prime has a point.

File should be this:
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/RCD/schematics/tile.dm

And it wouldn't cheapen the vault in my opinion, cause the vault has a LOT MORE than just the floor tiles, it is a whole adventure by itself, away mission-level, with soft-gated stuff via the ID cards, weapons access, etc. Having the floor tiles available stationside does not remove all the effort, goodies, aesthetics, etc, on the vault.
The tiles themselves would be welcome for bar building or overall decorating. I for one would love to see a bar renovated with the ayy look that only serves acid-themed drinks.

**Comment by Optimism333** [comment]
> > > Can you add the fancy ayy tiles to the tile painter, please?
> > 
> > 
> > Can you point me to the file or files, if it's more than one?
> > Edit: Honestly Prime has a point.
> 
> File should be this: https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/RCD/schematics/tile.dm
> 
> And it wouldn't cheapen the vault in my opinion, cause the vault has a LOT MORE than just the floor tiles, it is a whole adventure by itself, away mission-level, with soft-gated stuff via the ID cards, weapons access, etc. Having the floor tiles available stationside does not remove all the effort, goodies, aesthetics, etc, on the vault. The tiles themselves would be welcome for bar building or overall decorating. I for one would love to see a bar renovated with the ayy look that only serves acid-themed drinks.

Sorry, but I'm not going to add that to this pr. If you'd really like to see it, I'd encourage you to open an issue and ask for some conversation/input. That way I can gauge whether there is player interest in such a thing.

**Comment by Eneocho** [comment]
Fair enough.

**Pull request merged**
