### PR TITLE
Smoother roid floors

### PR DESCRIPTION
**Pull request by ghost**
[sprites]

Before:
image
After:
image

## What this does
See image.

## Why it's good
Less ugly and clashing straight edges with space.

## Changelog
:cl:
 * rscadd: Asteroid floors now fade more smoothly against space.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Aesthetic.

**Comment by WindowsErrors** [comment]
in a mathematical sense this is actually less smooth

**Comment by Eneocho** [comment]
SOVLLESS

**Comment by Kurfursten** [comment]
> in a mathematical sense this is actually less smooth

I think in all senses that is true. In fact, this PR would make more sense as "rougher roid floors" or "more natural roid floor borders"

It's probably a little weird at this point that we use the exact same overlay on every roid wall and roid floor, now in 2 different colors. We should probably alternate between, at least three different overlays.

**Comment by Eneocho** [comment]
the top right corner always going up looks very weird

**Comment by WindowsErrors** [comment]
> It's probably a little weird at this point that we use the exact same overlay on every roid wall and roid floor, now in 2 different colors. We should probably alternate between, at least three different overlays.

what if we preemptively secure technical debt by alternating between no overlays

**Comment by DamianX** [comment]
It might be better to make these overlays use `vis_contents` instead of creating one `/image` per tile.

**Comment by Kurfursten** [comment]
That's a good idea; I don't think it has impacted performance so far even though the roid is completely covered in mineral turfs that each have an overlay, but it does seem like an obvious area for improvement.

**Comment by ghost** [comment]
> It might be better to make these overlays use vis_contents instead of creating one /image per tile.

Would render_target/render_source work just as well?

**Comment by DamianX** [comment]
I've never used those successfully, I don't know.

**Pull request merged**
