### PR TITLE
Revert "Revert "Nofruit are completely random and have a static cycling animation.""

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts d3athrow/vgstation13#13834

Stop encouraging Kilo's autistic obsession. He needs to learn to deal with change like a big boy.

:cl:
* tweak: Produce from nofruit is no completely random and has no bearing from the icon on screen.
* sounddel: Nofruit no longer clicks.
* bugfix: Nofruit cycling animations no longer produce lag.

### CODE REVIEW

**Comment by kilozombie** [comment]
The problem is not that it was merged, it was that it was self-merged

I've said before that if it's merged and the coderbase wants it that way, I'll fuck off. But so long as people are still discussing it, why merge already?

**Comment by PJB3005** [comment]
You literally cannot fix no fruit. It's technologically impossible.

**Comment by Iamgoofball** [comment]
@kilozombie make like a tree and get out of here

**Comment by Megamaw** [comment]
@Iamgoofball can you fuck off to /tg/ again

**Comment by Iamgoofball** [comment]
@megamaw sorry i forgot to do a poll

here's your poll, I'll add a toggle to enable/disable the outcome of this poll too if the outcome triggers you
http://poal.me/702ol

**Comment by Megamaw** [comment]
@Probe1 what the fuck, the consensus was generally negative on this PR

**Pull request merged**
