### PR TITLE
deletes "minor role" preference from existence and splits it into catbeast/rambler/plaguemouse preferences

### PR DESCRIPTION
**Pull request by gurfan**
this took 5 minutes to do, I don't know why it wasn't like this to begin with

:cl:
 * tweak: Split the "Minor Role" preference into seperate Loose Catbeast + Plague Mouse + Rambler Preferences

### CODE REVIEW

**Comment by SonixApache** [comment]
are you sure this won't obliterate the database
you don't seem to even make any database-related changes so i can only assume this will just break those three roles

**Comment by juanototo2** [comment]
Better idea: Split "Minor Role" into "Nonantag Minor Roles" and "Antag Minor Roles"

**Comment by boy2mantwicethefam** [comment]
Having a fancy database was a mistake

**Comment by juanototo2** [comment]
This preference exists to avoid cluttering up the role selection screen with five quintillion different variables of the same "little antagonist" paradigm to add spice to a round that dynamic allows. Do you have any idea of a single person that wants to be soul rambler but doesn't want to be plague mouse or vice versa enough to give him objectively worse quality of life?

**Comment by Dacendeth** [comment]
I want to be a rambler but not the other things.

**Comment by PrimeDSS13** [comment]
I dont want to be a rambler but I wanna be the other two.

**Comment by SonixApache** [comment]
I wanna be a cat but not the other two.

**Comment by Kurfursten** [comment]
All minor roles are midround with signups so it's okay to mix them into one pref

**Comment by Jackreturnswithaveangenace** [comment]
Gotta agree with the boys on this one, none of the minor roles are roundstart and you have to sign up for them anyway, they're not automatic.

**Comment by toomykins** [comment]
instead of this i'd prefer the user gets a ping when theyre auto-signed up for something, like a bwoink.

**Comment by ShiftyRail** [comment]
Conflicts

**Comment by ShiftyRail** [comment]
@SonixApache & @boy2mantwicethefam : this will not cause any DB issues

**Comment by ShiftyRail** [comment]
Conflicts (rappel)

**Comment by gurfan** [comment]
closing this, prefs don't matter for these roles anyway because they're all signups

**Pull request closed without merging**
