### PR TITLE
Castle now has 2 exclusive themes

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
US and Soviet anthems (with english lyrics). That's it.

:cl:
 * soundadd: Castle now has 2 exclusive themes.

### CODE REVIEW

**Comment by SonixApache** [comment]
+5 MB for memes, very bloat

**Comment by Exxion** [comment]
To be fair Snowmap has over 50MB of music
But yeah, these can probably be compressed better

**Comment by boy2mantwicethefam** [comment]
Compressed from roughly 5MB to just 3MB.

**Comment by Eneocho** [comment]
no balls to use the soviet anthem with the original lyrics

**Comment by Kurfursten** [comment]
Fine, at least you compressed it to half size

**Pull request merged**
