### PR TITLE
Removesspacesfromspeechwhileonhyperzines

### PR DESCRIPTION
**Pull request by ghost**
Theunknown[tweak]sviolently.
:cl:
 * tweak: Hyperzineandrelatedchemicalsnowmakepeopletalklikemotormouths.

### CODE REVIEW

**Comment by Irradiation** [comment]
Does this properly work if you're on cocaine as well?

**Comment by ghost** [comment]
> Does this properly work if you're on cocaine as well?

It counts all hyperzines so yes

**Comment by ShiftyRail** [comment]
What a lame get

**Comment by xeroxemnas** [comment]
The entire science department is gonna sound like junkies for sure.

**Comment by Eneocho** [comment]
Sec McSeccie (Security Officer) [Security] says "HeywardencanIgetashotguntheshotgundon'tmiss"

**Comment by Eneocho** [comment]
Virology's hyperzine symptom would also be affected, would it be prudent to add an exception to that? (Since virus symptoms are their own thing, but call on reagents for easier coding).

**Comment by DeityLink** [comment]
I don't see the problem with this affecting the viro symptom, since it does just that, hyperzine synthesis.

**Comment by Killette2** [comment]
Will admins cause brain damage if people talk with dashes instead?

**Pull request merged**
