### PR TITLE
Change how action buttons move

### PR DESCRIPTION
**Pull request by Mothblocks**
Action buttons can no longer be freely dragged around, but instead can be dragged onto each other to swap places.

I know it's a bit hasty considering I gave only an hour after my [issue](https://github.com/vgstation-coders/vgstation13/issues/17543), I just wanted to get a PR going. 

Comment whether you give a fuck about being able to move action buttons around. I just find it annoying and I never intend to do it.

:cl:
 * tweak: Instead of being able to move freely, action buttons can now be dragged on top of each other to swap places.

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
i want this to work with spells too but spells are written a bit weirder

**Comment by DamianX** [comment]
The "arrow" action button that toggles visibility for the rest of the action buttons should always be the rightmost. Can you add a check for that?

**Comment by Mothblocks** [comment]
@DamianX It automagically worked like that without me having to do anything special.

**Comment by DamianX** [comment]
No wonder, it's runtiming :^)
`Runtime in action_button.dm, line 42: list index out of bounds`

**Comment by Mothblocks** [comment]
@DamianX But it werks! (fixing)

**Comment by Probe1** [comment]
That runtime was introduced when the fucking thing was introduced.  Not that I'm against forcing young master Jared to fix it 😄

**Comment by DamianX** [comment]
No, it wasn't. It was specifically introduced by this PR.

**Comment by Mothblocks** [comment]
Fixed the runtimes and also organized the proc a bit better.

**Review by DamianX — APPROVED** [review]

**Comment by Probe1** [comment]
I played earlier this evening.  I moved an action button because of the issue/PR.  It ended up doing all sorts of stupid shit including getting hidden behind new action buttons.

Lets just move on to a saner system right now.

**Comment by Mothblocks** [comment]
@Probe1 I didn't and am still not getting those issues myself, but the entire thing just sucks. What would you suggest instead?

**Comment by DamianX** [comment]
I think he was referring to the old behavior.

**Comment by Probe1** [comment]
Yeah I meant that any restraint and hesitation I had disappeared after trying to use the free place action buttons.  They were terrible.

**Pull request merged**
