### PR TITLE
double agents no longer target themselves

### LINKED ISSUE #6613: Should we fix the double agent getting themself as a target bug?
It's been left in because it's funny.  Should we fix it?  

As a side idea, should we add a heavyweight operative that gets 20 telecrystals in exchange for being the only syndicate on the station?  That is how double agents getting themselves as a target plays out now.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #6613

We have more feature requests than bugs.

### CODE REVIEW

**Comment by gbasood** [comment]
If only we could separate feature requests into a wishlist tracker instead of using the issue tracker

You might want to, instead, remove traitor from the list of targets, check if the list is empty, and deal with it in another way than just looping back through find_target, since you can end up with an infinite loop as-is

**Comment by Intigracy** [comment]
find_target is just picking a random crewmember rather than going back through the list of antags. If somehow there's no available targets, the DA just gets a free objective at that point. Completely impossible to infinite loop using that proc.

Currently the DA objective finding a target handles like this:

```
target_list[traitor] = traitors[i + 1]
//bunch of code in between
kill_objective.target = target_list[traitor]
```

This means for when you're pointing the objective target to the DA's spot on the list, you're really doing it to DA's spot + 1.
The only time this ever returns the DA himself is when he's the only person on the list, which is normally supposed to just give a random assassinate target, but it doesn't work without my addition to the proc.

**Comment by Probe1** [comment]
rip funnybug but your time is due.

**Comment by gbasood** [comment]
```DM
if(kill_objective.target && kill_objective.target != traitor)
  			kill_objective.explanation_text = "Assassinate [kill_objective.target.current.real_name], the [kill_objective.target.special_role]."
  		else //Something went wrong, so give them a random assasinate objective
  			kill_objective.find_target()
```
So if kill_objective.target is traitor, it goes into the else block, which is find_target, which is the same exact code.

That's an infinite loop

**Comment by Intigracy** [comment]
find_target is not the same exact code jesus fucking christ

```
 /datum/game_mode/traitor/double_agents/forge_traitor_objectives(var/datum/mind/traitor)

    if(target_list.len > 1)
        // Assassinate
        var/datum/objective/assassinate/kill_objective = new
        kill_objective.owner = traitor
        kill_objective.target = target_list[traitor]
        if(kill_objective.target && kill_objective.target != traitor)
            kill_objective.explanation_text = "Assassinate [kill_objective.target.current.real_name], the [kill_objective.target.special_role]."
        else //Something went wrong, so give them a random assasinate objective
            kill_objective.find_target()
        traitor.objectives += kill_objective


    // Escape
    if(prob(15))
        var/datum/objective/hijack/hijack_objective = new
        hijack_objective.owner = traitor
        traitor.objectives += hijack_objective
        /*var/datum/objective/die/die_objective = new //NO
        die_objective.owner = traitor
        traitor.objectives += die_objective*/
    else
        var/datum/objective/escape/escape_objective = new
        escape_objective.owner = traitor
        traitor.objectives += escape_objective
    return
```

```
/datum/objective/proc/find_target()
    var/list/possible_targets = list()
    for(var/datum/mind/possible_target in ticker.minds)
        if(possible_target != owner && ishuman(possible_target.current) && (possible_target.current.z != map.zCentcomm) && (possible_target.current.stat != DEAD) && !(possible_target.assigned_role in bad_targets))
            possible_targets += possible_target
    if(possible_targets.len > 0)
        target = pick(possible_targets)
```

**Comment by gbasood** [comment]
Ye I commented before I reviewed

**Pull request merged**
