### PR TITLE
maybe fixes #7871

### LINKED ISSUE #7871: Marble statue kill isnt actually a kill
(WEB REPORT BY: h0l3m4k3r REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Turn To Stone statue destruction doesnt count as kill in objective terms
> 
> What you expected to happen
> Gibbed marble statues counted as killed
> 
> Steps to reproduce if possible:
> Turn someone to stone (Kill objective)
> Gib it from marble form with any gun
> Get redtext, even if he is as dead as his head in your backpack

### PR DESCRIPTION
**Pull request by Intigracy**
maybe

### CODE REVIEW

**Comment by ghost** [comment]
how

**Comment by Intigracy** [comment]
idk lol

**Comment by ghost** [comment]
Test it

**Comment by Intigracy** [comment]
maybe tomorrow

**Comment by Intigracy** [comment]
tbh celt this PR is the most ground breaking innovation since the shovel

**Comment by clusterfack** [comment]
You guys gotta be kidding me, this wont do shit

**Comment by Intigracy** [comment]
well if this won't do shit, then this bug doesn't exist in the first place.



tested this PR with another player, shot'm with a laser gun, right in his face.

**Comment by Intigracy** [comment]
bug doth not exist

**Comment by clusterfack** [comment]
Must have killed the wrong person

**Pull request closed without merging**
