### PR TITLE
Upgrades the hoverpod large artifact

### PR DESCRIPTION
**Pull request by Sprok0**
The hoverpod mech, a fairly rare large xenoarch artifact, is no longer incredibly slow, can equip the hydraulic clamp/scythe, and can once again move freely through space.

### CODE REVIEW

**Comment by clusterfack** [comment]
I've always wanted this to be like a spacepod + a ripley

**Comment by Sprok0** [comment]
well it basically is now, it's got phazon speed

**Comment by AutismSpider** [comment]
should only get phazon speed when moving in/on space or zero kpa zones

**Comment by Sprok0** [comment]
Now it has ripley speed when in areas with greater than 50kPa, which is still more than twice as fast as it was before.

**Comment by clusterfack** [comment]
Alright, I have no problem with this

**Pull request merged**
