### PR TITLE
From Shuttles to Spaceships

### PR DESCRIPTION
**Pull request by ghost**
**This actually has no content**, but the general populace rarely ever replies to issues so I thought I'd make an attention grabbing PR and make a checklist of what I want to accomplish.
Essentially, after turning the bridge into a spaceship and crushing the vox shuttle with it, I want to make a developed system to build, operate, and explore space in a spaceship. And you might say: "Fuck off, it's space STATION thirteen, not space SHIP thirteen." But why not have both? And as black market is at a standstill, I am considering just reverting it and saving it for when we have a functional economy to justify an illegal end to the economy. Spaceships would be a good place to spend your money.
And these changes will take quite a while, as it is a much, much larger project than the black market or likewise. 
Here are all the changes I am considering making:

- [ ] Rename shuttles to spaceships (code-wise)
- [ ] Improve areas to be less annoying and fucky, make APC's and air alarms less annoying when it comes to merging and editing areas. Current shuttles use areas as their basis for what to move.
- [ ] Update shuttle console to nanoUI.
- [ ] Add engine control requirement to shuttles. Using the console, you would have to manage fuel and your engines and stuff. In addition, add more engine variety and features to make them more interactive.
- [ ] Add starmap requirement to shuttles. Starmap would replace the current system of random vaults on z-levels that aren't z-level 1. You would be able to fly over to a vault or uncharted space and hope you find something. You can also select which port to dock on here.
- [ ] Starship travel in bluespace would now take more time based on distance and have interdiction opportunities (e.g. travel to a distant pirate planet and during the ten minute travel time a pirate ship crashes into your hull).
- [ ] Shuttles now have size limits based on what kind of ports you want to fit into. Metric is pending, but it would be something like small-medium-large-capital class. You can build your own docks.
- [ ] Shipyard on all stations, containing small and medium docks. Cargo shuttle would get a dedicated spot here and now have fuel requirements. You could buy ships or just build your own. In addition, new arrivals would come in small centcomm transport pods, so arrivals would be transformed and expanded into the shipyard.
- [ ] Mounted weaponry. Due to obvious limitations this would just consist of a more developed turret system and weaponry in the form of a structure/machine.
- [ ] If you're feeling hostile, you can now select on the starmap (by using minimap similar to deathsquad mech launch) where to directly land and in what direction. Of course, this would demolish your ship if you were to crash into a station, so it would be much better used to park in a hostile spot against your enemy.
- [ ] A way to move ships without teleporting? Unsure how that would work.
- [ ] And finally, a lot of content in other existing features that integrate into starships. Like improved engines as a part of RnD, hostile cyber horror ships that security has to use their Autism Cruiser to prevent from crashing into the station, things like that.

### CODE REVIEW

**Comment by PaulRitter** [comment]
issues: am i a joke to you?

**Comment by PaulRitter** [comment]
draft: am i joke to you?

**Comment by Kammerjunk** [comment]
without commenting on ideas, reworking areas is a major PR on its own

**Comment by SonixApache** [comment]
at first glance, this sounds like a metric fuckton of work, with changes that would almost warrant forking off into a new codebase
all of it sounds 'fun' and 'good' which translates to 'requiring an infinite amount of work that will be way too much to accomplish for a single hobbyist programmer in any reasonable amount of time'
and yeah it'd change the game in its entirety, this is beyond gimmick map levels of rework, you'd probably want to split off and host a new serb at that point

making an empty PR that's not even a draft PR to discuss your idea instead of making an issue is dumb

**Comment by Kammerjunk** [comment]
something like that
most of this is isolated to shuttles, but the sheer amount of work required to add all this *properly* exceeds any one feature added to date, including group projects. this is a collection of ideas without any deeper analysis made to understand the exact scope of the changes.
certain parts of this won't ever be developed and certain other parts won't ever be developed in this context

**Comment by ghost** [comment]
I'm aware this is a large project, so it would be done in segments over year(s) and not all of it would be done. I want to at least add better shuttle functionality, though.

**Comment by Anton-Kr** [comment]
If you want a decent starting point, Bay has a pretty dope space travel system

**Comment by MadmanMartian** [comment]
spaceship implies it's a ship that only works in space

shuttle is for transporting people and goods around, and has no environmental concern in its name.

**Comment by ghost** [comment]
I suppose, it just sounds a little dull

**Comment by Exxion** [comment]
>Add starmap requirement to shuttles. Starmap would replace the current system of random vaults on z-levels that aren't z-level 1. You would be able to fly over to a vault or uncharted space and hope you find something. You can also select which port to dock on here.

Don't like this for a couple reasons. First, it makes shuttles mandatory for vault-hunting. Second, it either requires adding a bunch of Z-levels (which really is just not possible due to engine limitations) or partitioning Z-levels into sub-regions that act as independent Z-levels (which would be a good system to have, mostly for Z2 stuff, but makes the issue of trying to go back to where you were before only to find you got thrown into a random area of space even worse).

Also, a *lot* of these suggestions just sound like unnecessary complexity and serve no real purpose. The docking port sizes thing, for example.



>A way to move ships without teleporting? Unsure how that would work.

You're always going to have to teleport the ship internally. There's no way around that. You can move it to a holding area and use a separate object that moves around to represent the ship, and even draw its inside with `vis_contents` (though this is guaranteed to look terrible if the ship can rotate), but considering how limited space necessarily is, this really seems like more trouble than it's worth.

**Comment by ghost** [comment]
To start off, I'm just going to refactor shuttle code and condense it into a module folder. Also I'll make APC's and air alarms less annoying to work with when making areas. Then, I'll work on prototyping a moving shuttle that works on all z levels and works similar to a pod to see whether it's viable. Then, regardless of the previous result I'm going to improve shuttles with new features.

**Comment by Kammerjunk** [comment]
okay well don't do all of those things here

**Comment by MadmanMartian** [comment]
this should be fun to review

**Pull request closed without merging**
