### PR TITLE
Revert "Remove solo antag objectives part 55: electric boogaloo"

### PR DESCRIPTION
**Pull request by MadmanMartian**
Reverts vgstation-coders/vgstation13#23476

It's been a week, let's see what the consensus is.

:cl:
 * rscadd: The syndicate now wants you to do specific things on the station to aid them, they are called "objectives"

### CODE REVIEW

**Comment by ghost** [comment]
I don't see why people care one way or another. People will do what people will do.

**Comment by ShiftyRail** [comment]
lol

**Comment by bathosbathtime** [comment]
I personally find this unneeded given #24001
while I didn't understand it at first, I have warmed up to it.

**Comment by SonixApache** [comment]
i'd rather have the toggle tbh

**Comment by Tehsapper** [comment]
either this or let people have freeform jecties in personal prefs.

**Comment by Kammerjunk** [comment]
let's maybe see what people want before we merge anything
there's like half a dozen different ideas on objectives currently open as PRs

**Comment by Kharkov72** [comment]
just merge #24001

**Comment by utilitas-** [comment]
Because a week is the perfect trial period for anything related to this game.

**Comment by MadmanMartian** [comment]
Closing in favour of #24001

**Pull request closed without merging**
