### PR TITLE
Line updates

### LINKED ISSUE #31516: Rename Line Station to Rodstation
(WEB REPORT BY: meetmeindorms REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #31517: the cargo line isn't lined up
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description

cargo shuttle outlet conveyer line isn't lined up

# Steps to Reproduce

go to the cargo shuttle

# What you Expected

the line to line up

# What Actually Happened

it didn't

you had one job map maker

### LINKED ISSUE #31521: why is there a punching bag in space outside the bridge on line
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description

there's a punching bag IN SPACE

# Steps to Reproduce

go to the bridge and look out the west side

# What you Expected

to see space

# What Actually Happened

i saw a punching bag

### LINKED ISSUE #31522: linestation mechbay has a wall in the door
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
robotics mechbay door is wall
# Steps to Reproduce
go to mechbay and try to leave through south
# What you Expected
door open
# What Actually Happened
door wall
https://files.catbox.moe/tg6lsu.PNG

### LINKED ISSUE #31523: linestation engineering SMES
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
engineering only has 3 SMES, going from engi->station
most other maps have another, that both inputs and outputs to the engineering powergrid - without it you cant setup the singo/SM(without doing AME first) because no power for the emitters
# Steps to Reproduce
look for the SMES batteries
# What you Expected
4 SMES
# What Actually Happened
there are only 3

### LINKED ISSUE #31524: Linestation vents issues
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
Research Shuttle Bay Vent Pump #2 and abandoned library vents are not connected to anything
# Steps to Reproduce
line station
mice
try to ventcrawl on those pipes
# What you Expected
dying to low pressure
# What Actually Happened
couldn't crawl

### LINKED ISSUE #31525: linestation medchem pipes
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
disposal pipe is missing under the window and the air vent is rotated wrong
# Steps to Reproduce
enter chem
# What you Expected
breet
# What Actually Happened
I CANT BREET(because vent's wrong)
also the disposals keep shitting in the window
https://files.catbox.moe/ic6wdb.PNG

### LINKED ISSUE #31526: linestation surgery 2 not blueprinted
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
the second surgery room isn't entirely marked on the station blueprint
there's a wire connection for an APC which isn't there
there's also a nanomed frame in the door
# Steps to Reproduce
enter surgery backroom
# What you Expected
CIA nigger free tables
# What Actually Happened
the tables glow in the dark
https://files.catbox.moe/uxwj9s.PNG

### LINKED ISSUE #31527: linestation atmos cosmetic issues
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
under the airlocks isn't floortiled
one singular scrubbers pipe is put on top of the floortiles

i do like how there's a sulfuric acid tank in engi, good job linestation man
# Steps to Reproduce
enter atmos
# What you Expected
nothing, really
# What Actually Happened
AAAH THE FLOORTILES
https://files.catbox.moe/0u9wgg.PNG

### LINKED ISSUE #31530: the line cargo office has incomplete firelock coverage
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description

the sales machine lets air pass through but there's no firelock covering it despite the desk and the main door having them

# Steps to Reproduce

void the air from the area

# What you Expected

to not have the sudden rush of air knock me over

# What Actually Happened

the firelocks fell and the sudden rush of air knocks me over

### LINKED ISSUE #31531: yo how come on line in arrivals one of the arrivals doors has full tile shutters but the other door just has firelocks
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description

there's a giant full tile shutter on the north door and normal firelocks on the southern one

# Steps to Reproduce

go to arrivals

# What you Expected

normal firelocks

# What Actually Happened

giant firelocks

### LINKED ISSUE #31534: Line station engineering doors do not use engineering access
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
Line station engineering doors by the CE office do not use engineering access
# Steps to Reproduce
acquire ID with basic engineering access

attempt to open engineering lobby doors by CE office
# What you Expected

# What Actually Happened

### LINKED ISSUE #31537: The gas pumps in the Frankenline's incinerator room aren't connected to anything
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
What the title says

# Steps to Reproduce
No need

# What you Expected
Connected pipes

# What Actually Happened
Not that

### PR DESCRIPTION
**Pull request by adacovsk**
[general]

- no (Closes #31516)
- removed barrier from hos office
- cargo conveyor (Closes #31517)
- xray camera for AI for AI Upload
- switched out firelocks near arrivals
- removed punching bag next to bridge (formally was gnome, Closes #31521)
- overflow surgery fixed (Closes #31526)
- fixed morgue access
- fixed mech bay wall (Closes #31522)
- fixed chemistry vents and disposal (Closes #31525)
- fixed floating bulb in chapel
- fixed glass near MiniSat
- fixed genetics access from maintenance
- removed sulfuric acid tank near atmos (Closes #31527)
- Added SMES. (Closes #31523)
- fixed vents (Closes #31524)
- added cargo vendor firelock (Closes #31530)
- 4nr (Closes #31531)
- The doors have standard engineering access keys, 11;24... Don't think this is an issue (Closes #31534)
- Changed paramed station to have circuitboards rather than telesci already set up. Makes parameds put more effort into doing their job.
- Changed bar layout based on feedback
- fixed Vox outpost
- fixed pipes in incinerator room (Closes #31537)
- Added greyling neckbeard courtesy of Optimism

I still have no idea what I'm doing on github

:cl:
 * rscadd: Updated line from feedback and github issues

### CODE REVIEW

**Comment by adacovsk** [comment]
I'm trying to "hotfix" my map, but I have no idea what I'm doing and this probably isn't the way to do it.

**Comment by Eneocho** [comment]
Add "Closes #ISSUE NUMBER" to the OP as appropriate. Example: "Closes #31522". This will link the issues to this PR and close them if the PR gets merged.

**Comment by pedr69** [comment]
>smes working as intended
all the best maps(box,deff and roid) have an engi-engi SMES. not sure bout the other maps but i think only one map doesn't have it. if you want your map to be GOOD and EPIC put the battery

**Comment by adacovsk** [comment]
> > smes working as intended
> 
> all the best maps(box,deff and roid) have an engi-engi SMES. not sure bout the other maps but i think only one map doesn't have it. if you want your map to be GOOD and EPIC add the SMES also why did you remove the acid tank i need muh orange juice

There are PACMANs that are right in the SMES room that you can connect to power the emitters... I really don't think the extra SME is necessary. The vending machine in engineering has your OJ.

Edit: on further notice, if someone doesn't know how to set up SMES properly and the batteries drop to 0, you get a singuloose.  So to retard-proof it, I'll add one.

**Comment by ShiftyRail** [comment]
Your PR contains Line's original commits. I think it won't cause to much troubles to merge it, but this is really something you should avoid. You should pull from Pomf's Bleeding-Edge and develop on a new branch.

You really should not be committing o your own repo's Bleeding-Edge.

**Comment by adacovsk** [comment]
I'll do this for next time, I really do have no idea what I'm doing, it was much worse before

**Comment by Kurfursten** [comment]
What he said, we'll do this once but not a second time, learn smartgit or command line

**Pull request merged**
