### PR TITLE
dead goliaths have a new sprite

### LINKED ISSUE #7222: Goliaths lack a distinct dead sprite, can be hard to tell if they're dead or not sometimes
Especially given that their aggro is a little finnicky, the fact that you don't want to move while you're fighting them (you might think it's just a lagspike), and how slow they are

### PR DESCRIPTION
**Pull request by Intigracy**
It's the old sprite flipped on its side :^)

fixes #7222

### CODE REVIEW

**Comment by 9600bauds** [comment]
Holy christ dude did you blow off half their bodymass from one shot
How do you even skin that for it's hide

**Comment by Intigracy** [comment]
magic

**Comment by 9600bauds** [comment]
Just turn the sprite sideways or something

**Comment by Intigracy** [comment]
genius

**Comment by gbasood** [comment]
> not making it explode into a pile of confetti

**Pull request merged**
