### PR TITLE
Removes setLoc(), a retarded piece of code

### PR DESCRIPTION
**Pull request by PJB3005**
~~DNM still testing~~

it works

### CODE REVIEW

**Comment by ComicIronic** [comment]
700,000 lines added.

**Comment by PJB3005** [comment]
Well yeah but seriously dat code quality.

Never4get #4511 either

**Comment by ComicIronic** [comment]
Out of interest, does this let the AI eye crush glass underfoot?

**Comment by PJB3005** [comment]
hm, actually it might, let me check that

**Comment by PJB3005** [comment]
There, with forceEnter I can GUARANTEE it doesn't cause you to walk on shards and stuff

**Comment by clusterfack** [comment]
You only changed 1 of them to forceenter but there are several involving the eye obj

**Comment by PJB3005** [comment]
Er, it compiles doesn't it? I removed atom/movable/proc/setLoc() so if I left references it wouldn't compile

**Comment by clusterfack** [comment]
I mean from forcemove to forceenter, any of them that involve the AI eye should be forceenter

**Comment by PJB3005** [comment]
what? I changed the AI eye's forceMove() to use forceEnter() for the actual moving, so calling forceMove() on the AI eye wouldn't cause issues.

**Comment by clusterfack** [comment]
In that case it should be fine

**Pull request merged**
