### PR TITLE
Its got what plants crave.

### PR DESCRIPTION
**Pull request by FudgePucker**
Sports drinks help plants.
Its got electrolytes.
I didn't see any plants growing out of a toilet.

### CODE REVIEW

**Comment by Imagebard** [comment]
You mentioned this on 8866

>cause beneficial mutations

What kind of beneficial mutations does Brawndo cause, now? Did you code that in?

**Comment by NigglyWiggly** [comment]
<sub>I don't know much about Hydroponics code so I may be wrong, but I suggest you read what he changed

**Comment by FudgePucker** [comment]
Nope, that seemed like a lot of work for me to copy past-
I mean, it already is so great for plants that you wouldn't want the meta to revolve around it would you?
Besides, its not Brawndo brand sports drink, its some generic kind, the kind that doesn't cause beneficial mutations.

**Comment by ghost** [comment]
Probably should make trays unusable after a while though

**Comment by unid15** [comment]
What if, while having high brain damage, you couldn't put water into trays (but you could still pour Brawndo in)

**Comment by Intigracy** [comment]
put "fixes #8866" in your OP somewhere without quotes

I suggest you change it to this though:
adjust_nutrient(1)
adjust_water(-1)

**Comment by ihadtoregisterforthis** [comment]
Don't be an Intigracy and put `closes #8866`, not "fixes"

**Comment by Intigracy** [comment]
You want to be just like me, not less like me.

**Comment by FudgePucker** [comment]
So should I make it dehydrate the plant, or keep the joke of it being super good for plants?
~~i am suprised noone has pointed out I just copy pasted adminzines effects~~ I am a good coder who knows what they are doing.

**Comment by Imagebard** [comment]
The great debate.
Should Brawndo damage or heal plants?

**Comment by Intigracy** [comment]
It should give nutrient and dehydrate.

It's got what plants crave!

**Comment by FudgePucker** [comment]
Should it kill pests and weeds or boost them?

**Comment by Imagebard** [comment]
It should boost pests- *its got electrolytes!*

**Comment by AutismSpider** [comment]
boost pests and weeds to much and you end up with spiders coming out of it etc

**Comment by gbasood** [comment]
Considering you're covering your plants in sugar water _and electrolytes_ I'd figure it'd attract pests, not kill them.

**Comment by Intigracy** [comment]
increase nutrient by 2, decrease water by 1, increase pests by 1, increase weeds by 1 or 2

**Comment by clusterfack** [comment]
Have you guys decided yet? I await the final revision of this critical fix with baited breath.

**Comment by Intigracy** [comment]
idc that much

**Comment by Imagebard** [comment]
I don't know
I guess its fine as-is?

**Comment by 9600bauds** [comment]
Make it remove water and I'm sold.

**Comment by Shadowmech88** [comment]
Why make it remove water?

**Comment by Intigracy** [comment]
Because it's a movie reference, and a sugary ass drink is going to cause a plant to dehydrate, not gain water.

**Comment by Shadowmech88** [comment]
I'm aware of the reference, but I thought the plants were dying in the movie because they were being fed Brawndo _instead_ of water.

**Comment by 9600bauds** [comment]
Yes, exactly

**Comment by Shadowmech88** [comment]
Why would that mean Brawdo itself removes water?

**Comment by FudgePucker** [comment]
electrolytes are salts.

FUN SCIENCE FACT OF THE WEEK

**Comment by PJB3005** [comment]
@FudgePucker false, salts are electrolytes but not all electrolytes are salts.

It's like all squares being rectangles but not all rectangles being squares.

**Comment by Probe1** [comment]
why does it heal plants though.  it does the opposite in the movie.  its like a reddit level understanding of the joke.

**Comment by 9600bauds** [comment]
It's a joke you dip, more people remember that quote than the actual plot of the movie

> dropping the r word outta nowhere

?????????

**Comment by Probe1** [comment]
Its true though, its a dumb joke.  The joke is brawndo kills plants but instead the PR makes it do a really good job at healing them.  

Makes no sense.  Which is why reddit applies.  Its taking a joke we all recognize then changing its meaning and honestly if you're gonna add a joke item (or in this case a function to a joke item) at least add the joke and not a meta reverse cryptojew joke about the joke.

**Comment by gbasood** [comment]
@Probe1 So we should add a chem that exists only to make plants shit got it

**Comment by Probe1** [comment]
@gbasood we have at least 2 plantkiller chems for that purpose in the game already.

**Comment by Imagebard** [comment]
>Making this chem heal plants is reddit tier

>We already have 2 plantkiller chems why make this a plant killer?

This is exactly why we have to DEAL.

**Comment by Probe1** [comment]
You mean "why not" make it a plant killer.

**Comment by gbasood** [comment]
@Probe1 we really don't need yet another plantkiller chem and that wouldn't be much of a joke at that point

**Comment by NigglyWiggly** [comment]
Wait does this actually make Brawndo heal plants
Because that's stupid.

Brawndo should without a doubt kill plants, that is the entire fucking joke.
BUT
It shouldn't say that it does.

It's not 'adding another plantkiller chem' it's giving an existing chem another function.

**Comment by ihadtoregisterforthis** [comment]
Plants growing on toilets when then?

**Comment by Imagebard** [comment]
>Brawndo should without a doubt kill plants

I don't see any plants growing in toilets.

**Comment by Intigracy** [comment]
It should give nutrient and remove water as I said before.

Just like the movie. The land ended up fertile af which is why those plants grew so extremely fast once they got water.

**Comment by Shadowmech88** [comment]
Did the land end up fertile directly because of the Brawndo or because of all the decomposing dead plants that littered it?

**Comment by Intigracy** [comment]
Who cares?

Brawndo by itself killed plants.

**Comment by 9600bauds** [comment]
The obvious solution to all of this is give Brawndo some good qualities coupled with one fatal flaw (removing water) that would kill plants if they were given ONLY Brawndo
thus you have a funny joek, it's accurate to the movie, and it's actually something that has a use and not an extremely obscure equivalent of a "You suddenly feel like a retard".

**Comment by 9600bauds** [comment]
I mean really, what's funnier/adds more to the game
- A clever botanist spending his shift's allowance on Brawndo to use it as a plant-healing chem that's essentially not even that useful or necessary, then spewing ebin references at people when they ask him about it

or
- A botanist finding out that the extremely obscure and useless substance called "sports drink" exists in the game and somehow not finding out that it kills plants, then thinking "hmm I wonder if that could be a reference to this movie", splashing it on his plants, and thinking "oh goddammit it is" then forgetting about it entirely

**Comment by clusterfack** [comment]
Most controversial PR in history

**Comment by 9600bauds** [comment]
Nah that was removing ponies

**Comment by Imagebard** [comment]
Seven thumbs up, one thumbs down. Add one more thumbs down due to bauds aaaand...

Nope, still winning.
Merge when?

**Comment by Probe1** [comment]
If you're going by emojis I forgot to reverse mine when I realized it did the opposite of what brawndo is supposed to do.

**Comment by 9600bauds** [comment]
> Add one more thumbs down due to bauds aaaand...

I like this PR you nerd
Why do you have to jump at every chance to be as contrarian as possible

**Comment by Imagebard** [comment]
Why do you have to jump at every chance to be as upset as possible

**Comment by Kurfursten** [comment]
I think I have an idea that could make everyone happy.

While the tray contains Brawndo, it should turn off all warning lights (pests, unhealthy, weeds, water, nutrients). So if you didn't examine it, you would think the plant was doing fine. Meanwhile the Brawndo itself doesn't actually hurt plants, just makes you oblivious to the need to fix your plants. I think that matches the joke more closely and provides a cool new functionality. It's not hard to code either.

**Comment by Shadowmech88** [comment]
I like it, would also give the opportunity to use it as a tool to sabotage and/or prank botanists.

**Comment by ComicIronic** [comment]
Interestingeffectfor2roundsuntilsomeonecomplainsaboutgriff/10

**Comment by Kurfursten** [comment]
If you want to griff a botanist, you're better off using plant spray. It instantly kills ever since botany3. You can wipe out a botanist's entire stock in less than ten seconds. I've seen it done, and it's not pretty.

Hope they have extra seeds.

**Comment by DeityLink** [comment]
This shit is basically adminordrazine for plants. It also makes them never die of old age either.

**Comment by FudgePucker** [comment]
Its almost as if I just copy pasted adminordazine code and changed a line :^)
I will edit it some ~~sometime~~ tonight.

**Comment by 9600bauds** [comment]
> tonight

**Comment by FudgePucker** [comment]
Woops

**Comment by Kurfursten** [comment]
If you want to do it my way, here's the code I would use. First, give sportdrink a custom metabolism rate for plants so it's used up less quickly

`custom_plant_metabolism = HYDRO_SPEED_MULTIPLIER/5` //Default is 1, equals 0.2

Then under hydro_tray_process.dm, at line 322 add this:

`&& !reagents.has_reagent("sportdrink")`

This is really convenient because you don't need to remove them yourself, it automatically freshly draws overlays every process. So just don't tell it to draw them again.

**Comment by FudgePucker** [comment]
Oh god what went wrong?
Why didn't it compile?
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by FudgePucker** [comment]
Also if it is just travis fucking up this is NFD.

**Comment by Intigracy** [comment]
code/modules/hydroponics/hydroponics_reagents.dm:210:error: .5: undefined type path
vgstation13.mdme.dmb - 1 error, 0 warnings (7/15/16 4:17 am)
mv: cannot stat `vgstation13.mdme.dmb': No such file or directory

**Comment by FudgePucker** [comment]
Undefined type path?
How/where did I fuck up then?

**Comment by Intigracy** [comment]
the -.5 should be -0.5 or probably just -1

**Comment by FudgePucker** [comment]
And the changelog failed to compile because?

**Comment by FudgePucker** [comment]
Wait I might have figured it out.
Drum roll please.

**Comment by FudgePucker** [comment]
FUCK YEA
Thanks @Intigracy

**Comment by FudgePucker** [comment]
#11027 
...
DAMN IT.

**Pull request closed without merging**
