### PR TITLE
Remove obsolete code

### PR DESCRIPTION
**Pull request by adacovsk**
## What this does
- Removes some old, unused, obsolete, commented out code

## Why it's good
- Removes bloat

### CODE REVIEW

**Comment by jwhitak** [comment]
Don't we want to keep that warning for clients that are sharing an IP? It seems to have a DEVELOPER_MODE switch, why can't that be used in a test environment?

**Comment by adacovsk** [comment]
> Don't we want to keep that warning for clients that are sharing an IP? It seems to have a DEVELOPER_MODE switch, why can't that be used in a test environment?

It's never worked properly for me. Or maybe it does, then I forget to change DEVELOPER_MODE. Furthermore, you can't do anything about it on the test server

**Comment by west3436** [comment]
~~unatomic~~

**Comment by Kurfursten** [comment]
Now only removes comments so there's no reason to be concerned

**Pull request merged**
