### PR TITLE
snaxi library rework - doubles its size and adds all new library machines

### PR DESCRIPTION
**Pull request by nervere**
Before:
image

After:
image

## Why it's good
Firstly, this is kinda ugly but I think it's far better than it was. That said, I'm open to suggestions.
Anyway, the snaxi library was cramped and had just about nothing in it before. Now it's an actually lively room to be in.

## Notes
I had to shift around xenobio a bit to make this work and give space to everything, but it should look and feel identical. I essentially just shifted one of the containment pens two tiles forward and prettied it up afterwards.

Also, I didn't delete the potent ham easter egg, I moved it here because it was the closest spot I could hide it.
image

[snaxi]

## Changelog

:cl:
 * rscadd: Snaxi: Reworked the library to double its size and add all of the new library machines.

### CODE REVIEW

**Comment by nervere** [comment]
poor mapdiffbot

**Comment by Kurfursten** [comment]
General thoughts:
> I think overall this is a huge improvement already, so bear with me on the other comments
> I think the directional windows + easel combo is pretty ugly -- consider swapping the art database desk and pen desk so you can just push those easels back one tile
> I would use wood border decals on the edge between wood and shag carpet
> Need a third wall radio for backroom
> Light tube placement is very weird
> Why 2x scrubber/vent in the main area but none in the backroom?

Alternate more daring ideas to save space
> Put art storage across the hall by the meeting room
> Just say fuck it entirely and have library take over that corridor, you now have to walk through the library to get to the southeast wing

**Comment by PrimeDSS13** [comment]
I'd make the south facing door windows more standardized to the other windows of the station

**Comment by west3436** [comment]
I'd make the leftmost glass airlock just a windoor to keep it in line with the directional windows

**Comment by NigglyWiggly** [comment]
Generally I like this quite a bit and I think it looks good, but I’m not a huge fan of the amount of single windows separating areas, especially the entire left wall, I’d rather just have normal walls with full tile windows around the door or something.

The little office being just made of tinted windows feels barbaric and disturbing but there’s not much you can do without significantly bumping up the size of the area, though i feel you should move the door to face the front desk area, instead of having to walk out and through the library to get there, if you can figure out a way to finagle all of that.
Also, aren’t tinted windoors a thing? I assume it’s just a windoor behind the giant curtain.

**Comment by Kurfursten** [comment]
I think Niggly is right on this and quite a lot of his feedback is similar to mine. If you need to move art storage across the hall or even jump the whole library to give it the space it needs, do what you have to do. Just fix it fast, Snaxi is already half done for the year.

**Comment by Kurfursten** [comment]
Revisions look a lot better

**Comment by Kurfursten** [comment]
You never updated the OP, is this the final draft?

**Comment by Kurfursten** [comment]
There are less than 30 days left of Snaxi so some communication would be ideal

**Comment by nervere** [comment]
@Kurfursten its done

**Pull request merged**
