### PR TITLE
Compiled Map List

### PR DESCRIPTION
**Pull request by adacovsk**
[wip][bugfix]

Should work properly now... Also replaced `all_maps` to `compiled_maps` for clarity.

:cl:
 * bugfix: all compiled maps can be voted on with an admin toggle, which will not break the server

### CODE REVIEW

**Comment by DamianX** [comment]
So basically all this does is check `is_enabled` in addition to `is_compiled()`.
This seems to go against what this comment says `var/is_enabled = TRUE // If FALSE, it doesn't show up during the vote but can be rigged`.
Why are you doing this?

**Comment by adacovsk** [comment]
> So basically all this does is check `is_enabled` in addition to `is_compiled()`. This seems to go against what this comment says `var/is_enabled = TRUE // If FALSE, it doesn't show up during the vote but can be rigged`. Why are you doing this?

for reasons I don't understand, xoq showed up in the `all_map` list. This should prevent that

**Comment by DamianX** [comment]
That's intended. As long as a map is compiled it should show up in the list returned by `get_all_maps()`, and if an admin rigged it you should be able to vote for it, and it should then start correctly. If something went wrong, this wasn't the culprit.

**Comment by adacovsk** [comment]
> That's intended. As long as a map is compiled it should show up in the list returned by `get_all_maps()`, and if an admin rigged it you should be able to vote for it, and it should then start correctly. If something went wrong, this wasn't the culprit.

If you're not aware, xoq kept the server down for like 3h yesterday. I assume it was because it wasn't compiled or it was just broken. I don't know how to test anything further

**Comment by DamianX** [comment]
I really don't have much more to add.
*Something* must have existed at `maps/voting/xoq/vgstation13.dmb`. It's checked here:
https://github.com/vgstation-coders/vgstation13/blob/f801f7d0e8882ac5a1d4bc48a9245305ced4bd47/code/datums/next_map.dm#L9

I believe `get_all_maps()` is behaving as expected.

**Comment by Hinaichigo** [comment]
I've been wondering, can you load the contents of uncompiled maps from the .dmm files while the round is running? Like say you wanted a certain 10x10 room to be filled with the contents of a given .dmm at the push of a button. Can you load a new one each time the button is pushed or does it have to be preloaded on a separate z-level and then teleported in?

**Comment by adacovsk** [comment]
> I've been wondering, can you load the contents of uncompiled maps from the .dmm files while the round is running? Like say you wanted a certain 10x10 room to be filled with the contents of a given .dmm at the push of a button. Can you load a new one each time the button is pushed or does it have to be preloaded on a separate z-level and then teleported in?

kanef would know more about that and the answer is no (currently)

**Comment by adacovsk** [comment]
```
    if(config.map_voting)
        //testing("we have done a map vote")
        if(fexists(vote.chosen_map))
            //testing("[vote.chosen_map] exists")
            var/start = 1
            var/pos = findtext(vote.chosen_map, "/", start)
            var/lastpos = pos
            //testing("First slash [lastpos]")
            while(pos > 0)
                lastpos = pos
                pos = findtext(vote.chosen_map, "/", start)
                start = pos + 1
                //testing("Next slash [pos]")
            var/filename = copytext(vote.chosen_map, lastpos + 1, 0)
            //testing("Found [filename]")

            if(!fcopy(vote.chosen_map, filename))
                //testing("Fcopy failed, deleting and copying")
                fdel(filename)
                fcopy(vote.chosen_map, filename)
            sleep(60)
```
could've been the issue

There might've been a file that was in the folder that didn't actually have the map compiled

**Comment by Exxion** [comment]
>I've been wondering, can you load the contents of uncompiled maps from the .dmm files while the round is running? Like say you wanted a certain 10x10 room to be filled with the contents of a given .dmm at the push of a button. Can you load a new one each time the button is pushed or does it have to be preloaded on a separate z-level and then teleported in?

Yes. There's an admin button for this, I think.
BYOND does not provide this ability internally but we have a library that does it pretty well. This is how vaults and dungeons are loaded.

**Comment by Hinaichigo** [comment]
> > I've been wondering, can you load the contents of uncompiled maps from the .dmm files while the round is running? Like say you wanted a certain 10x10 room to be filled with the contents of a given .dmm at the push of a button. Can you load a new one each time the button is pushed or does it have to be preloaded on a separate z-level and then teleported in?
> 
> Yes. There's an admin button for this, I think. BYOND does not provide this ability internally but we have a library that does it pretty well. This is how vaults and dungeons are loaded.

Thanks.

**Pull request closed without merging**
