### PR TITLE
Adds an in-hand for snakes (and also picking them up)

### PR DESCRIPTION
**Pull request by beesil**
[sprites]

I thought you could pick up snakes before but apparently not, so that too.

image

:cl:
 * rscadd: You can now pick up snakes.
 * imageadd: Gives Corpus and other snakes an in-hand sprite.

### CODE REVIEW

**Comment by arc166** [comment]
Cute

**Comment by ComradeDispenser** [comment]
Finally I can take my boy to the escape shuttle safely without having to shove him in an emergency shelter

**Comment by ShiftyRail** [comment]
There is a snake in my boot!

**Comment by AI-Is-Rogue** [comment]
Should make it so you can wear it on your head like pillowbugs

**Pull request merged**
