### PR TITLE
OOC Color is lighter blue

### PR DESCRIPTION
**Pull request by adacovsk**
:cl:
 * tweak: OOC color is a little lighter for darkmode and normal mode

### CODE REVIEW

**Comment by godietxt80** [comment]
soulless

**Comment by Eneocho** [comment]
image
This is how it'd look colourwise.
Bring back yellow OOC or add a way to customize on the client side.

**Comment by adacovsk** [comment]
customizing on the client side seems like a good idea... I will try and work on it (maybe)

**Comment by DamianX** [comment]
It's better but not much better. Was it really yellow in the past? Why was it changed to blue?

**Comment by Eneocho** [comment]
> It's better but not much better. Was it really yellow in the past? Why was it changed to blue?

It was yellow, mustard-ish. It's blue on eyerape mode but yellow for dark mode, the latest darkmode fix broke it.

**Comment by adacovsk** [comment]
>broke it

Actually that was the fix

**Comment by Eneocho** [comment]
image

**Comment by Eneocho** [comment]
> Actually that was the fix

Absolutely heretical. I want my mustard yellow OOC back.

**Comment by adacovsk** [comment]
> Absolutely heretical. I want my mustard yellow OOC back.

you're welcome to make a PR that changes the colors back, but that will cause the issues that I fixed to happen again

**Comment by WindowsErrors** [comment]
i suppose the removal of the dark mode message was somewhat premature

**Pull request closed without merging**
