### PR TITLE
Adds a new animation for plasmaman monkeyisation

### LINKED ISSUE #19688: Monkey Transformation animation for Plasma Men is Jank
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
80f35b7d06c1dab7bb9ff18777c95874b968addd

# Description

Plasma men being monkeyed by the staff of change do the human monkeying animation, which means they go from a plasma man, to a naked human, then have there flesh fall off into a monkey, and then suddenly become a flaming skull.
# Steps to Reproduce

Be Plasmaman, be whacked by change staff
# What you Expected

Plasma memes
# What Actually Happened

Jank

### PR DESCRIPTION
**Pull request by ShiftyRail**
Contributed by an anon on the thread.
Also makes monkey syringes give the proper monkey primitive type. Why not?

Closes #19688

https://streamable.com/xrbhoo

:cl:
- rscadd: Monkey syringes will now transform humans to the correct primitive species.
- rscadd: New animation from plasmaman monkeyisation, contributed by anon.

### CODE REVIEW

**Comment by jknpj** [comment]
what's up with the vanishing mob?

**Comment by ShiftyRail** [comment]
Human code sleeping/spawning a bit during the creation of a new mob.

**Comment by boy2mantwicethefam** [comment]
Can you try making the animation attached to the player? It's possible to move around the invisible person while the transformation is ongoing

**Comment by ShiftyRail** [comment]
I think either the transformation is an overlay glued to the mob or the mob is anchored while it's playing.

In fact, it's the former. Or at least it should be, the way it is coded doesn't work. Will fix.

**Comment by boy2mantwicethefam** [comment]
ty

**Comment by ShiftyRail** [comment]
Done

**Pull request merged**
