### PR TITLE
STOP EATING PEOPLE'S HEADS

### PR DESCRIPTION
**Pull request by gbasood**
People were eating disembodied heads
They should really stop
Also this adds gamelog and adminlog output for matter eater actions

### CODE REVIEW

**Comment by CptWad** [comment]
:+1:

**Comment by Boxe** [comment]
sounds like someone's mad they're not getting any head ;)

**Comment by 9600bauds** [comment]
Is this making the notice for failing to eat a brain saying that it's non-existent ears tickle your throat?

**Comment by NigglyWiggly** [comment]
But why

**Comment by gbasood** [comment]
@9600bauds fuck

**Comment by ghost** [comment]
> balance change
> during a feature freeze

**Comment by ghost** [comment]
:-1:  for adding arbitrary restrictions to matter eater. If ears tickle a throat, how in hell's name can you eat a stool?

**Comment by gbasood** [comment]
@DrCelt also a hotfix
It's not intended for players to eat mob's heads, see:

```
if(istype(limb, /datum/organ/external/head))
            //Bullshit, but prevents being unable to clone someone.
            to_chat(user, "<span class='warning'>You try to put [the_item]'s [limb.display_name] in your mouth, but \his ears tickle your throat!</span>")
            return 0
```

Disembodied heads was a case that wasn't accounted for, and now it is. I didn't make up the ears thing, some other nerd did.

**Comment by ghost** [comment]
I can claim anything is a hotfix though, this doesn't even fix a bug. Disembodied heads is not something that should be prevented, and especially not disembodied brains

**Comment by NigglyWiggly** [comment]
Yeah, it's silly to have a restriction on this just because it might permanently remove someone from a round, we have tons of other things that remove people from the round and there's no real problem with those

**Comment by gbasood** [comment]
I'm all for spacing someone's disembodied head, but Matter Eater makes it ridiculously easy to prevent someone from ever being revived. That's my opinion.

Changed tags

**Comment by ghost** [comment]
You could add everything eaten to contents of the mob and then release it when gibbed.

**Comment by FudgePucker** [comment]
Fuck genetics
:+1:
Also can you add logs for people using telekinesis on machines? A fucking genesist water potassium'd chemistry. Twice. In the same room. I knew it was the asshole after seeing him hiding around the corner glowing like a faggot with chamilion and horns.

**Comment by PJB3005** [comment]
Eating somebody's head should cause (uncurable) Kuru.

**Comment by Exxion** [comment]
You can also polyacid heads to permanently remove someone from the round
If anything, polyacid is easier to come by than the matter eater power

**Comment by Kurfursten** [comment]
@TermedClepe Stomach organ would be pretty neat.

**Comment by Imagebard** [comment]
Matter Eater should be able to eat heads, sorry gbasood.

It should also ping the admins like you suggested.

**Comment by AutismSpider** [comment]
@Exxion any one with poly acid up to no good 100% of the time they want the body gone for good what we have most of the time in genetics people being massive dick heads with matter eater and other powers no logs are made when they are used.

**Comment by FudgePucker** [comment]
@AutismSpider exactly.
Fuck
Genetics

Everything these assholes do should be logged and limited.

**Comment by gbasood** [comment]
I think polyaciding heads is equal levels of bullshit, if not more bullshit, than this. Not sure what to do about that if anything.

**Comment by Kurfursten** [comment]
The most mysterious thing about polyaciding a head is that if you spray a person with polyacid targeting the head zone they don't immediately become headless, but if you polyacid a cut-off head it immediately disintegrates.

**Comment by gbasood** [comment]
Actually it might be worth opening a separate issue for discussing whether or not we SHOULD let players destroy disembodied heads in various ways.

**Comment by 9600bauds** [comment]
I mean, if you're not stupid you could just hide the heads in a way that's 99% guaranteed they will never get back into the round. Even putting them into a potted plant would already be pretty much GG.

**Comment by Zth--** [comment]
I think being able to eat heads is good. You have to do tons of research to get the fucking power. Doing it as a non antag should be bannable though

**Comment by AutismSpider** [comment]
@Kurfursten logs are made when some one slap with acid and poly acid though both do lot of damage when use on suit less people on top of making limbs and organs poof into goo

**Comment by Kurfursten** [comment]
@AutismSpider I wasn't saying protesting better logging by any means

**Comment by 9600bauds** [comment]
@AutismSpider suits don't protect against polyacid, only helmets and masks do, and only very briefly. Pacid smoke can't be protected against, practically.

**Comment by AutismSpider** [comment]
@9600bauds Greys were the only thing that had acid and poly acid res they don't have any more for god knows what.

**Comment by Imagebard** [comment]
@AutismSpider 
But wasn't that the whole point
Weren't greys supposed to be weak to water and immune to Acid and pAcid?

**Comment by AutismSpider** [comment]
@Imagebard Yes but they lost it some how on top of keeping massive water weakness does toxin burn and brute all the same time to them

**Comment by ghost** [comment]
It's sulphuric greys were meant to be resistant to, not polytrinic acid you nerds.

**Comment by gbasood** [comment]
This is now ONLY adminlogs since people want to destroy heads I guess

**Comment by NigglyWiggly** [comment]
> Merged by the creator of the PR
> DNM tag

HMMMMMMMMMMMMMMM

**Comment by Imagebard** [comment]
The DNM tag was also added by the creator of the PR.

**Comment by NigglyWiggly** [comment]
> Still merged 

**THE CODERBUS IS REAL**

**Comment by 9600bauds** [comment]
>This is now ONLY adminlogs 
>This is now ONLY adminlogs 
>This is now ONLY adminlogs 
>This is now ONLY adminlogs

**Comment by gbasood** [comment]
Yeah there's literally no gameplay changes anymore
Don't worry I wouldn't self-merge a gameplay change that I considered controversial

**Pull request merged**
