### PR TITLE
BoxStation bar tweaks

### PR DESCRIPTION
**Pull request by brndd**
[box]

Powercreep etc.

This is basically #22449 but for Box. The bartender now has a little workspace of sorts between the tables. Hopefully it doesn't make things feel too cramped. The vending machines in the back were deleted because there are already duplicates of them elsewhere in the bar, and they don't serve much purpose when the dispensers exist.

After:

Before:

:cl:
 * rscadd: Boxstation bar now has soda, coffee and booze dispensers. The furniture has been shifted to accommodate them. The still has been moved to the back room, the back room vending machines have been removed (they are available elsewhere in the bar should they be needed), and there's now a wrench in the back room on the table.

### CODE REVIEW

**Comment by Hoshi-chan** [comment]
I'd just remove the boozeomat, honestly. Three tables in a line with booze, soda, and coffee dispensers. Move the shaker to the back room, add a box of glasses and mugs, or more rapid service dispenser cartridges.

I can see those tables getting dismantled and the machines getting moved every round, with the boozeomat either winding up crammed into the backroom or shoved out into the hall.

**Comment by brndd** [comment]
I'd like to avoid altogether removing things. I feel like if there's anything the unwashed anonymous rabble holds more sacred about the bar than the still, it would be the booze-o-mat.

**Comment by Hoshi-chan** [comment]
Put it in the back room, then.

**Comment by Exxion** [comment]
Booze-O-Mat is pretty important even with the dispensers because it contains glasses
That's why the bartending crate comes with glasses

**Comment by Exxion** [comment]
By the way, can you actually reach the machines in the corners from the spawn location? It seems like the dense objects would prevent you from doing so.

**Comment by bungofungo** [comment]
Swap one of the backroom vending machines for the booze-o-mat, its not like the soda or coffee machine is used at all

**Comment by FudgePucker** [comment]
They should work because there's an open space via the table

**Comment by brndd** [comment]
@Exxion 
>By the way, can you actually reach the machines in the corners from the spawn location? It seems like the dense objects would prevent you from doing so.

They work now, yes. The initial PR had a mistake but I think you commented after I fixed it anyway.

@bungofungo 
>Swap one of the backroom vending machines for the booze-o-mat, its not like the soda or coffee machine is used at all

Going into the back room to get drinking glasses and ice cups and such would kinda blow.

**Comment by FudgePucker** [comment]
How would you feel about pushing the bartender work area out one tile to the left? It would still not be in the way of the hallway, and would make the bartending area feel less cramped.

**Comment by Hoshi-chan** [comment]
Whatever, you do, you have to do something about this: 
ss (2019-04-16 at 04 27 22)

This is a straight downgrade. I'd rather take the old bar's layout and throw the boozeomat out myself every round, even if it meant I had to order and build my own dispensers.

The workstations should not be two tiles deep, leaving you one tile of space to traverse your work area. This is why Deff used to suck so much, and why it's annoying to have healthy non-doctors in medbay. Someone unleashes monkeys, breaks the windoor, or whatever, and your workspace becomes shove city. That's why I suggested moving the boozeomat to the back. Moving the bar out one tile like @FudgePucker suggested would also be a potential solution, since it gives you more space to distribute the shit behind the bar, or you could possibly move the disposal to the back room and remove the table.

Nothing you do is going to be ideal though without actually changing the layout of the bar, I think.

**Comment by FudgePucker** [comment]
Honestly you need that table IMO. You need some table room for storage of things. I would move all the stuff on that table other than the shaker to the back room.

**Comment by FudgePucker** [comment]
Although table space is less necessary with the machines because you dont need to keep track of several different containers and can just use the machines

**Comment by brndd** [comment]
What do you think about moving the disposals chute into the back room?

edit: like this



Alternatively I could just take out one of the machines, such as the brewer.

edit: well, this is in now because I thought it was good. If you disagree comment below (and like and subscribe) and let me know.

**Comment by FudgePucker** [comment]
Move the fire alarm into a general access area instead of behind the bar. ~~So that its easier to hack to disable the fire locks~~ Because having wood floors and the fire alarm outside of reach is against the fire code.

**Comment by Exxion** [comment]
Fun fact about that: There's code for wood floors burning but it doesn't actually get executed because of how a loop works somewhere
I forget the specifics

**Comment by brndd** [comment]
There's already a fire alarm in the general area next to the cigarette machine.

**Comment by Hoshi-chan** [comment]
That revised layout is a lot better. Maybe put the sink in the back, too.

**Comment by brndd** [comment]
The sink is necessary for wetting your rag, and doesn't really cause any problems where it is.

**Comment by jknpj** [comment]
>wall-mounted machinery on top of desks



Just use the walls.

Edit: actually, they aren't wall-mounted and putting them in the walls would be bad so disregard this.

**Pull request merged**
