### PR TITLE
Dab fixes

### PR DESCRIPTION
**Pull request by MadmanMartian**
- Reduces the damage from 50 to 5
 - Has typecheck for if the user is actually human
 - Checks for restraint and stunned
 - misc tweaks

:cl:
 * tweak: Tweaks some features of *dab

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
DABCREEP

**Comment by DrSnips** [comment]
Dabbing in cuffs is intended and that's why I fixed the broken bones freeing you from cuffs. But I made many mistakes today so... whoops.

**Comment by bathosbathtime** [comment]
So if it isn't april fools you'll just slap yourself in the face now?

**Comment by ghost** [comment]
I approve of this nerf

**Comment by DrSnips** [comment]
At least leave it as dab and not just slapping yourself. The damage was the issue not the emote message.

**Comment by SonixApache** [comment]
@DrSnips if you're going to actually do something with this, make it the only possible solution. Suicide, or on april fools, arm breaking.

**Comment by DrSnips** [comment]
No I listened before and it lead to stupid wizard memes. I plan to gut the emote and make it non-harmful to avoid any more issues. It should have been like that from the start but I caved to people saying it should damage you even more.

**Pull request merged**
