### PR TITLE
Implements soft lighting & adds a minor optimization to light source code.

### LINKED ISSUE #6738: Combat borg "Light Amplification" viewmode does not work
> Revision (Should be above if you're viewing this from ingame!)
> 2f77597bd6fd4648d9df706bcfcc0367ad64f638 
> 
> General description of the issue
> Combat borgs have access to a "Light Amplification" viewmode, but it doesn't work.
> 
> What you expected to happen
> Switching to the right mode after selecting the mode.
> 
> What actually happened
> Nothing. Selecting the mode just closes the prompt.
> 
> Steps to reproduce if possible
> Become a combat borg, set sensor augmentation to Light Amplification.

### PR DESCRIPTION
**Pull request by PJB3005**
Alright this is good to go.

@Mloc

Fixes #6738

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
@PJB3005 

Wasn't @Mloc going to work on soft lighting? Apparently he got really busy.

Isn't soft lighting where darkness isn't absolute; ie, more of the grey darkness that people were used to back in the DAL days?

**Comment by PJB3005** [comment]
@Fox-McCloud yes, instead of pitch black, even in your `see_in_dark` range, soft lighting puts it at a very dim thing, it basically "caps" the darkness, but still disables luminosity on the overlay.

**Comment by PJB3005** [comment]
Okay so I'm having some issues with floating point issues causing artifacts in relation to multiple colours of lights hitting the same overlay at the same time, I assume it's because of the depth of the decimals used to light things.

selection_040
)

**Comment by PJB3005** [comment]
Alright this is good, instead of hunting after floating point issues (and causing worse performance) I just made it ignore reeaally small lumcounts like that.

**Comment by Probe1** [comment]
Sounds like it needs tested to me m8

Inconsistent lighting behavior is still a thorn in players sides to this day.

**Comment by PJB3005** [comment]
@Probe1 sure if you want I guess @N3X15 could put it on the testing server.

**Comment by Probe1** [comment]
Locally testing should be fine.  I'm worried more about inconsistency then performance.

**Comment by Fox-McCloud** [comment]
@PJB3005 

What kind of performance boost does this have, precisely?

**Comment by PJB3005** [comment]
@Fox-McCloud at one point, @Mloc moved the lighting strength lists `effect_r`, `effect_g`, `effect_b` to not be an assoc list of turf = amount to having the turfs in a seperate list and going by index, when I later moved all those to 1 list, `effect_str`, I didn't think about making it an assoc list again, now I finally did that.

**Comment by Probe1** [comment]
Pretty wonky.  

I don't like the change removing darkness and think it's a significant alteration of gameplay/balance and not a bug fix.  I'd like to know why you disagree since you tagged it has a hotfix.  

I asked in game and only 4 people cared, three in favor of this change and one against.

north_edition_ii_2015-11-27_21-19-31

**Comment by clusterfack** [comment]
It's moving back the functionality to where it was when DAL still existed. Byond would have a dark sight variable which would allow mobs to see a little bit around them in the darkness just a little bit with dimmed lighting.

While we preserved that functionality with the move to this current lighting system, the darkness was still set to pitch black, rendering people unable to see things in that range.

**Comment by clusterfack** [comment]
@Probe1 Also I believe the first gif you posted is directly caused by pixel offsets completely unrelated to this fix

**Comment by Probe1** [comment]
I think its gay but the players don't so if it looks good code wise, I did test it for unintended side effects and found none.  

I still like having black darkness more.

**Comment by clusterfack** [comment]
It makes it impossible to see in total darkness at any range for both players and ghosts, why would you even want that?

**Comment by Probe1** [comment]
>total darkness
 >can't see anything

I don't get your view cause that sounds correct to me.  I can't see shit when I turn off the lights in my house, I don't get cats eye vision.

**Comment by clusterfack** [comment]
Too bad that is the opposite of fun

**Comment by Probe1** [comment]
"Atmospheric" gameplay often is.  It adds atmosphere to the game and makes it more enjoyable but it is not "fun" to have to struggle and prepare beforehand (though we have PDA lights so this is minimal).

It's good to repeat that I'm a minority opinion here and the few people that replied in game liked the change.  But I think it's unnecessary and makes the game easier for no reason.

**Comment by N3X15** [comment]
This big change.
Big change need big review.

**Comment by PJB3005** [comment]
@Probe1 as clusterfack said, the first gif always happened, even with DAL, it could be fixed by removing the SEE_PIXELS flag.

**Comment by Probe1** [comment]
I wouldn't say it's controversial since I'm the only one that disagrees with it.

**Comment by clusterfack** [comment]
I don't see any problem with the code, the change is rather small

**Comment by Midaychi** [comment]
I like it, and this is also how goonstation's lighting works.

**Comment by Angelite191** [comment]
Wait, why the fuck didn't I see this in the thread? I absolutely HATE this change! It makes maint crawling way too easy and impossible to hide behind/around people. Can we get a poll for this or something?

**Comment by WeinerMaster69** [comment]
woah woah woah woah can you see other people's little light they make because if so 

A) That's unrealistic garbage
B) Breaks the whole game

THE WHOLE GAME

**Comment by Angelite191** [comment]
You can't see other people's light. only yours. But yeah, like probe said, people that don't like it may be a minority.

**Comment by PJB3005** [comment]
Ah, the good ol' complain after it's merged.

If you don't want shit like this to go through, looking at the PR list every day is more than enough to see non-bugfixes (non-bugfixes easily need a couple days before being merged.)

And for the record, it was like this before baylights.

**Comment by SangriaMonkey** [comment]
It beats a big black unclickable overlay any day.

**Comment by PJB3005** [comment]
Actually @SangriaMonkey, this doesn't technically make that issue any better (you always could "see" next to you, it's just that the lighting overlay never became transparent enough to see anything on the tile)

**Comment by Probe1** [comment]
In every poll I've made people have favored the lighting before this.  I plan on making more.

**Pull request merged**
