### PR TITLE
Fashion Report - Hoodies

### PR DESCRIPTION
**Pull request by PlausibleDeniability**
I've created several hoodies to create some variety for the crew.  These can all be found in the Suitlord 9000. Hoods can be toggled just like the winter coats.

hoodieVending hoodieToggle 

<hr>

dreamseeker_a6TsTgNuLe

<hr>

hoodieHuman hoodieBug hoodieVox

<hr>

hoodieInhands

[sprites]
[tested]
:cl:
 * rscadd: The Suitlord 9000 has recently received a shipment of colored hoodies, try them out!

### CODE REVIEW

**Comment by DeityLink** [comment]
+1 for in-hand icons

**Comment by PrimeDSS13** [comment]
speedmerge when

**Comment by ghost** [comment]
the insectoid sprites are adorable

**Comment by TGFH** [comment]
perfect

**Comment by Dacendeth** [comment]
what's with the white spots at the feet of the vox one when the hood is down in that preview gif?

**Comment by PlausibleDeniability** [comment]
> what's with the white spots at the feet of the vox one when the hood is down in that preview gif?

That's the boots sprite, unrelated

**Pull request merged**
