### PR TITLE
Chopping food into toppings to be placed onto other food (WIP)

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
This is a WIP for a concept I've been thinking about and talking about with others here and there. I'm posting it in a draft state so I can see if people would like it, and also get feedback and maybe some ideas about the direction to take it.
It's intended to be the beginning concept of a more modular and flexible way of handling cooking, where you prepare and combine ingredients in various ways. This would be something to add alongside the existing recipe system.
Right now I have it so you can:

- get a carrot
- slice it up into sliced carrot
- dice up the sliced carrot into diced carrot
- deep fry the diced carrot
- put the deep fried diced carrot as a topping onto a cheese cake slice

Additional stuff I've been considering is like mashing things up or making soup or sauce out of things. Specific ways to cook various ingredients like caramelizing, roasting, frying, searing, etc. Combining multiple ingredients into one. Being able to melt cheese and put it on top of things.

Todos:

- [ ] non-placeholder sprites
- [ ] bloodstains persisting on sliced ingredients
- [x] sanity/recursive food stuff
- [ ] ensure things work well with existing slicing system
- [ ] handle using something with ingredients in a recipe
- [ ] handle using an ingredient as part of a recipe
- [ ] ensure things work well with customizable food and plates
- [ ] consider also calling crossed, to_bump, etc. on the ingredients
- [ ] handle cutting or not being able to cut rocknuts and others
- [ ] handle consuming the reagents in the ingredients
- [ ] handle 'topping' soup
- [x] consider having stuff like `before_consume()` and `after_consume()` also work on the processed ingredients, both inside something and eating the bare ingredient
- [ ] other miscellaneous todos in the comments

Please let me know what you think and if you have ideas of what direction to proceed in.

## Why it's good
I think it could be fun to expand the flexibility of the cooking system.

## Changelog
:cl:
 * rscadd: Food can be chopped into ingredients that can be added to other food as toppings.

### CODE REVIEW

**Comment by west3436** [comment]
pizza topped with deep fried burger...

**Comment by Eneocho** [comment]
Make pizza
Deep fry
Slice into bits
Make pizza
Use pizza bits as toppings
Deep fry
Slice into bits
Make pizza
...

**Comment by CrazyAmphibian** [comment]
i'd love to see what horrifying creations the chef makes as a result from this

**Comment by Inorien** [comment]
image

**Comment by CrazyAmphibian** [comment]
WHAT IN THE NAME OF THAT WHICH IS ALL UNHOLY IS THAT

**Comment by Eneocho** [comment]
> WHAT IN THE NAME OF THAT WHICH IS ALL UNHOLY IS THAT

the inevitable future when this gets merged

**Comment by Hinaichigo** [comment]
What should the behavior be if say you have a whole cake, top it with minced butterfingers, then slice it, and step on a slice?
It should probably divide up the minced butterfingers equally onto all the slices (creating new toppings and then dividing the reagents and luckiness equally between them), but I'm also not sure about if you should to be able to slip on the minced butterfingers topping. And that would introduce some weird situations where you can "squish" a juicy-soft fruit topping that's already been minced by stepping on it, though custom behavior can be added for that. There also probably needs to be general handling for what happens if the ingredient somehow vanishes (as a result of something like `before_consume()` or in general).

**Comment by Eneocho** [comment]
I'd say just keep the chance to slip as is. Funnier that way.

**Comment by d3athrow** [comment]
woman moment

**Comment by Eneocho** [comment]
Please revive this one, I liked it.

**Pull request closed without merging**
