### PR TITLE
Slightly desouls the Atmos hardsuit sprite

### PR DESCRIPTION
**Pull request by Brotanics**
A small change to the atmos hardsuit sprite to give it better shading and whatnot.

New:
unknown

Old:
unknown

[Sprites]

:cl:
 * imageadd: Slightly tweaked atmos hardsuit sprites

### CODE REVIEW

**Comment by Eneocho** [comment]
SPRITERS REMOVING THE SOVL

**Comment by Brotanics** [comment]
With the helmet.
unknown.

**Comment by calzilla1** [comment]
Not a big fan of the harsh light turquoise, but big :+1: if the color changed depending on the health of the wearer.

**Comment by Brotanics** [comment]
> Not a big fan of the harsh light turquoise, but big 👍 if the color changed depending on the health of the wearer.

Sadly i'm no coder, nor do I know code wizardry. So that's out of scope unless someone does it.

**Comment by SonixApache** [comment]
disgusting

**Comment by ghost** [comment]
can you make the thing on the back less bright? i know the suit is a rip off of dead space or whatever but it just looks out of place.

**Pull request merged**
