### PR TITLE
Prevent hostile animals from attacking humans wearing druid robes.

### PR DESCRIPTION
**Pull request by twirling-jesters**
[tweak]

## What this does

Keeps hostile animals from attacking any humans wearing druid robes.

## Why it's good

Flavor, plus makes the druid syndie bundle a bit more synergistic.

## Changelog

:cl:
 * tweak: Hostile animals will no longer attack humans wearing druid robes.

### CODE REVIEW

**Comment by Kharkov72** [comment]
based and shamanpilled

**Comment by Kurfursten** [comment]
Allows you to cheese all space vaults and away missions. You put this at the simple animal level which includes Russians, Syndicate, bosses like Angie and Maria, skeletons, etc... Also a stealth buff to wizard because this is available at the Wizard clothing vendor for free. Also given to Druid chaplains for free.

Keep in mind that Druid chaplains already get leafy incense which calms down angry goats and causes friendly animals to follow you around.

**Comment by Exxion** [comment]
This might be OK if it affected specific mobs, but making you immune to all mobs ever is pretty excessive

**Comment by Hinaichigo** [comment]
Hmm yeah maybe if there was a nature faction or something.

**Comment by xeroxemnas** [comment]
MYSTERY OF THE DROODS

**Pull request closed without merging**
