### PR TITLE
Sound added to airlock maintenance panel opening/closing.

### PR DESCRIPTION
**Pull request by DrSnips**
Airlocks lacked a sound for when the maintenance panel was toggled on them with a screwdriver. Not sure why this hasn't been fixed for so long.
# **The greytiders wanted it to have only one tile of range so it's one tile of range. Stop asking.**
:cl: 
 * rscadd: Airlocks now make a small screwdriver sound when you screwdriver the panel on them.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This is actually a balance change because it significantly affects how sneaky you can be while hacking into a room you don't have access to. It's not suspicious to hear an airlock in the next room open, but it IS suspicious to hear the screwdriver sound then an airlock. Not to mention surprise entries without an emag are just a little less surprising since you don't have to notice the panel open with a tiny sprite change - you can just hear it.

Won't really negatively affect me since I have tatortot turned off but you gotta address it.

**Comment by Exxion** [comment]
Stealth carpentry when?

**Comment by DrSnips** [comment]
While stealth door hacking is a nice 'feature' it shouldn't have ever been a thing since nearly all tool interactions have a sound that plays when they are used. Why this has gone so long without being fixed in beyond me.

**Comment by eplgr** [comment]
"Fixed"? Well, I guess the title is not misleading, but for sure your posts are.
This is a balance change and not a bugfix at all.

And it's an awful idea, so :-1:

**Comment by Allspice** [comment]
Opening firelocks with a crowbar dun hev sound

**Comment by Kitfox88** [comment]
if you want stealthy doorhacks again just make the admins spam SCOOOOOTTTLAND until everyone mutes problem solved

**Comment by DrSnips** [comment]
Not sure how I can mislead you on this. Almost all tool interactions have a sound so why wouldn't the airlock? I can change it to addition rather than bugfix if that's what your panties are in a twist about.
@allspice
I can add one there too if people want.

**Comment by SonixApache** [comment]
make the range like one tile

**Comment by DrSnips** [comment]
I thought 100, 1 is already that. Normal sound volume and 1 tile range.

**Comment by Fruktlimpa** [comment]
I mean sure, if it is just 1 tile range then fine it wont really matter. But no matter how hard you spin this it is a balance issue.

**Comment by DrSnips** [comment]
I'm suprised how quickly people flocked here because they have been spoiled by minimal notice hacking.

**Comment by SonixApache** [comment]
maybe like half volume?
also you should add that range to the OP for sure.

**Comment by DrSnips** [comment]
You're right next to the door, don't see why it wouldn't be normal volume but I'm indifferent since I just want an indicator that you toggled the panel on an airlock when you can't see the panel.

**Comment by SonixApache** [comment]
because screwdriver.ogg is fucking loud

**Comment by ghost** [comment]
Are you sure this is only one tile range?

**Comment by DrSnips** [comment]
I'm not exactly positive since I can't test it locally easy but I think I found the proper way to do it.

**Comment by SonixApache** [comment]
launch serb, click yellow connection button on daemon to connect to it, shut down byond, click yellow button again (Gotta enable guests in your config but whatever)

just mute the window of the one doing the screwdriving

**Comment by Exxion** [comment]
Or just
Stand two tiles away and proccall `togglePanelOpen()`

**Comment by PJB3005** [comment]
If we can't have any range, at least make the sound play to *only* the guy using the screwdriver. The audio feedback is nice.

**Review by PJB3005 — APPROVED** [review]

**Comment by ultraplen** [comment]
How would a new player, or someone who doesn't stay updated with the git, immediately understand that only he could hear the sound? The compromise of only having the sound play to the hacker may seem obvious but it is at the cost of audio feedback consistency.

**Comment by SonixApache** [comment]
you make it quiet for starters
You bring up two good points, though;
 - changelog should say it's only got short range
- [update wiki]

**Comment by PJB3005** [comment]
@ultraplen hrm, you're right, though I don't think it's that significant.

**Comment by DrSnips** [comment]
I will add it to the log but where would that go on the wiki?

**Comment by DrSnips** [comment]
As for the sound it's already at 1/4 volume.

**Comment by ultraplen** [comment]
@PJB3005 It is not very significant but I wanted to point it out. A very tedious, but decent solution would be to make all "silent" action messages be in _italic_ or something.

**Comment by SonixApache** [comment]
@DrSnips the guide to hacking.

**Comment by ghost** [comment]
Please confirm if it's one tile or not

If it is, all the above is mostly null

**Comment by DrSnips** [comment]
Ok, after some testing it has a range of 2 tiles as of right now with the -5. I will bump that up to -6 and that should make it 1 tile of range.

**Comment by DrSnips** [comment]
There, should make the greytide happy now.

**Comment by DrSnips** [comment]
This seems done.

**Comment by Lokiamis** [comment]
I, too, get snippy with people who give me feedback and then selfmerge at 5:7

**Comment by yclatious** [comment]
Did you really self merge. 
Did you really break rule numero uno you daki owning nerd.
Did you really just break the only rule that matters.

**Comment by ultraplen** [comment]
5/7 self merge. Its like a thread meme but it actually happened.

**Comment by eplgr** [comment]
his collaborator status removed /when/

**Comment by ghost** [comment]
Literally the only thing he did as a collab so far is self-merge a controversial balance PR lmao

**Comment by Hugh-G-Rection** [comment]
I tend to go with the flow, so It doesn't super bother me what gets merged or by who, but is it necessary to be rude and name call people who disagree with you for valid reasons? It isn't even that controversial of a PR, not like say, removing multi-layered pipes or something.

**Comment by DrSnips** [comment]
Don't you worry your little heads. I'm just going to make /vg/ great again by adding 20 roundstart furry races, adding dakis, and to top it all off remove vox.

**Comment by ultraplen** [comment]
Owe up to your mistake and merge #16293, then remake this pr.

**Comment by SonixApache** [comment]
self 
MERGED

**Pull request merged**
