### PR TITLE
New Frozen Core + Fixed Pipes

### LINKED ISSUE #35941: Snaxi TEG piping trouble
#### Description of issue
Three issues. (1) The topmost scrubber in the TEG's burn chamber isn't hooked up to the exhaust piping. Instead of a manifold being to its left there's a straight pipe instead. (2) The airlock leading into the TEG's burn chamber hasn't got any sort of vent in it. Trying to cycle through with the airlock buttons means the person will get trapped and have to hack their way out of the 1x1 airlock chamber. (3) The exhaust vent for the gas chamber cannot be unwrenched even when the catwalk and lattice are removed.

#### Difference between expected and actual behavior
The top scrubber ought to be attached, the airlock ought to have a vent like the box TEG's burn chamber, and the exhaust vent on the ice ought to be removable.

#### Steps to reproduce
Play Snaxi

#### Length of time in which bug has been known to occur

At least a week.

### PR DESCRIPTION
**Pull request by Kurfursten**
This new core is completely fool-proof, the only place it touches a window is plasma-glass.
The atmospherics cave follows cave rules and won't have snowstorms

Fixes #35941

image

🆑 
* rscadd: The Snaxi Frozen Core is now less dangerous.

### CODE REVIEW

**Comment by Eneocho** [comment]
image
image0

**Comment by Kurfursten** [comment]
No one ever breaks that one, I think it's okay

**Comment by Eneocho** [comment]
By making it the only non-plasma window I'd say it encourages it being the one people break from now on.

**Comment by Kurfursten** [comment]
Actually I think I might just replace it with a door entirely for TEG maintenance and also they're safer because they include transitional unsimmed turfs.

Need to adjust the areas for the new core anyway.

**Pull request merged**
