### PR TITLE
Fixes Borers' Issues With Burning

### LINKED ISSUE #6729: Cortical Borers
(WEB REPORT BY: redun REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> When you enter a pipe or a host from an area of dangerous atmospherics, such as fire, you will continue to take damage from said source even if you are in a safe host/pipe and out of the area.
> 
> What you expected to happen
> Not to take damage when I make it to fucking safety.
> 
> What actually happened
> The negative effects follow you until you get out of your host/pipe in somewhere with regular atmos, even if the host is safe and the pipe is empty.
> 
> Steps to reproduce if possible
> Should be pretty obvious at this point.

### PR DESCRIPTION
**Pull request by Shadowmech88**
Fixes #6729.
Adds a heat and cold indicator for borers, so you can know when you're dying from being too hot or too cold. Currently I'm just using the regular human ones, but if anyone wants to sprite borer-styled ones I'll take them.
Reduces the heat damage per tick and cold damage per tick of borers to 1 each. Since they have such low health, this will give them a bit more time to potentially survive until their body temperature goes back into a survivable range.
`simple_animal`s can now gain heat from/lose heat to the environment while not on a turf, so borers who enter a pipe to escape a burning room won't continue to burn to death forever due to their body temperature never lowering. Unless, perhaps, the pipe is completely empty.
This last one does have the side effect of causing ventcrawling `simple_animals` such as borers to now *receive* damage when crawling through pipes filled with supercooled or superheated air, whereas they did not before. However, as such pipes are uncommon and there are messages to warn you of those circumstances when you enter a vent anyway, I think it's a worthy trade for being able to escape into pipes from burning rooms.
:cl:
 * rscadd: Borers now have a HUD icon for when their bodies are too hot or too cold.
 * tweak: Borers are now more resistant to damage from environment temperature, although their low health still makes it a large threat.
 * bugfix: Simple animals will now equalize their body heat with the air inside a pipe when they ventcrawl.

### CODE REVIEW

**Comment by brndd** [comment]
Ah, the cursed [Needs Spritework] tag of never getting merged...

**Comment by Shadowmech88** [comment]
It doesn't really *need* spritework, but we don't have a tag for "could use some sprites if anyone's feeling up to it, but it's no big deal."

**Comment by Kurfursten** [comment]
I got you

image

**Comment by jknpj** [comment]
tfw read that as Lust Night

**Pull request merged**
