### PR TITLE
Packed: outpost improvement

### LINKED ISSUE #28193: Packed Trader Outpost Scrubber
(WEB REPORT BY: beelzewax REMOTE: 206.221.180.138:7777)
# Revision
7689e1a9dcded68f57ca363191ece9f8b8f6f581

the portable scrubber in the packed trader outpost gives the message "WARNING: Unable to interface with the Portable Air Scrubber" when you try to interact with it, which appears to be from here: https://github.com/vgstation-coders/vgstation13/blob/0534fe5aa3788132a3bb83c8b9301f2b0eb2570c/code/game/machinery/machinery.dm#L399

other machinery on the outpost worked fine

### PR DESCRIPTION
**Pull request by vtlevev1**
[packed]

Third time's the charm, eh?

Closes #28193

green spaghetti

:cl:
 * rscadd: Packed: vox outpost has been rewired
 * rscadd: Packed: minor fixes on the vox outpost, such as missing sinks.

### CODE REVIEW

**Comment by gurfan** [comment]
god bless

**Comment by SonixApache** [comment]
*why*

**Comment by Kurfursten** [comment]
My thoughts on this are the same as the original attempt: the addition of wire states is sure to make using yellow wire more of a hassle when mapping.

**Comment by beesil** [comment]
Fantastic wiring. While you're doing outpost bugfixes: the porta-scrubber in the engineering section is the mech subtype scrubber and unusable. Changing it to be a normal porta-scrubber would resolve #28193

**Comment by west3436** [comment]
mama mia

**Comment by AI-Is-Rogue** [comment]
Jesus christ.

**Pull request merged**
