### PR TITLE
Make maps 500x500x6

### PR DESCRIPTION
**Pull request by d3athrow**
Allows working with the mclarge huge turfs list, 1.5e+006 turfs. Centers the maps to allow for even expansion of all directions.

### CODE REVIEW

**Comment by CptWad** [comment]
arise lord chicken
render thine maps so I may or may not build again

**Comment by ghost** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by Arthurdentist** [comment]
yes please

**Comment by ghost** [comment]
Commenting to keep track of it as it superseded my own 500x500 map PR

**Comment by clusterfack** [comment]
You are aware of the notifications button that lets you subscribe to anything for updates right?

**Comment by ghost** [comment]
Not really

Also add Map Priority tag until sorted, it modifies all four maps

**Comment by d3athrow** [comment]
no if there are other map PRs they should go first, all i literally did was drag n drop

**Comment by ihadtoregisterforthis** [comment]
Kilometer long ships when?

**Comment by Duny-** [comment]
wew lad time to add even more dead zones and trigger everyone by not calling it maintenance

**Comment by gbasood** [comment]
On the bright side, we can fit twice as many greytiders on a z-level now.

**Comment by 9600bauds** [comment]
Or off a z-level.

**Comment by gbasood** [comment]
Actually, now that I think about it, bigger z-levels means we can have more shit in space to explore without over-crowding it.

**Comment by CptWad** [comment]
That and more room to place those fuck awful shuttles

**Pull request merged**
