### PR TITLE
Combat rework 2021

### PR DESCRIPTION
**Pull request by ShiftyRail**
Are you tired of stun-based combat? Do you want a combat system that let you truly express your skill and rewards your position and consistency?

Then the **Combat Rework 2021** :tm: is just the thing for you! Experience the chaos of ss13 combat like never before in this revolutionary update to your favourite game. After 18 years of development, hopefully it will have been worth the wait.

## Damage ramp-up and falloff

Sometimes, you just feel like the shotgun does not enough. In this rework, not only does it not miss, but it has also a **damage rampup** of up to 20% if fired up close!
On the contrary, only cowards run away - which is why firing from afar induce a **damage falloff** for all weapons, capped at 50%. This damage falloff also applies to stun weapons and to rockets fired from a nuke ops RPG!

## Embrace the chaos

But sometimes, simply hitting targets is not enough. You want to rush head on, front toward enemies, and destroy them with a savage toolbox hit. Well, fear not, dear gamer - for **critical hits** are just the thing for you! Any and all weapons have a base *15%* chance of inducing triple damage on hit.

Ranged weapons are not forgotten - they have a 2% chance to deal thrice as many damage to your target, including stun duration and explosion radius for rockets. Critical projectiles are not affected by damage fall off and appear bigger on screen.

## More blood

When you get one critical hit, you just can't stop. To reward an aggressive playstyle, the more you have been in combat and dealt damage to enemy gamers, the *higher your critical hit chance*, with a cap at 45% for melee and 10% for ranged, obtained with 80 damage in the last 20 seconds.

## Image

crit distance

:cl:
- tweak: Updated localization files
- rscadd: Combat rework!

### CODE REVIEW

**Comment by agentofzog2** [comment]
pls buff the crit chance on rockets

**Comment by agentofzog2** [comment]
Actually, just increase the magazine size on the RPG so it's more competitive in this system.

**Comment by ghost** [comment]
random crits are "fair and balanced"

**Comment by DeityLink** [comment]
They definitely are. Fuck Uncle Dane.

**Pull request merged**
