### PR TITLE
(cult music stops)

### LINKED ISSUE #27136: Chameleon cultists that dance around the blood stone remain invisible despite "moving"
#### Description of issue
I'm still reeling from a cult round the other day. Highlights include a triple conversion, clutch sacrifice in the nick of time, and a skeleton cultist security officer carrying the cult to victory despite a complete lack of all blood. But what sticks with me the most was the dance around the anchor stone, which is where the fun begins. While dancing around the final stone, I wasn't sure if I was going to be able to pull it off on my own, with security bearing down with shotguns, I was sure my time was up. However, the officer (HoS? It doesnt matter) never noticed me because I had the chameleon mutation. Despite chameleon requiring you to stand still, I remained invisible while dancing around the stone, allowing me to summon Nar-Sie even with officers and most of the station bearing down and breathing down my back.

#### Steps to reproduce
1. Gain the chameleon mutation
2. Spread enough blood to enter the second to final chapter of cult.
3. Dance around the anchor stone

You should slowly fade into invisibility, despite being in motion.

#### Server revision

98eed8c1e3d6ad26df1a424f12de40d802c6fd95

### LINKED ISSUE #27557: Cultists can dance, move and spin while stunned
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
d5e7eddcca93d7611800267adbb8cf6a41cb8806

# Description
I was being sacrificed at altar. Fellow sec stunned a cultist. I thought I was saved. Cultist continued to spin and dance around altar and successfully sacrificed me, raising a blood stone.
# Steps to Reproduce
Stun a dancing cultist
# What you Expected
Stuns to be viable at stopping unholy rituals and to be saved from a terrible fate
# What Actually Happened
Cultist successfully sacrificed me by rolling around altar while screaming in pain and twitching on floor.

### PR DESCRIPTION
**Pull request by DeityLink**
cultdance

Fixes #27557
Fixes #27136

:cl:
* tweak: Cultists now stop dancing while incapacitated, or when muted by holy water. This includes constructs when they are purged by a null rod.
* bugfix: Cultists with the Chameleon gene no longer remain invisible while dancing.
* rscadd: Cultists can now DANCE wherever using say "*cultdance". They will dance around the tile in front of them, so for the best looks do it in an open area. If other cultists uses the emote while adjacent to the first cultist's "dance center", they will join up and dance in sync. Up to 4 cultists may dance together without bumping into each other (as unlike the sacrifice/bloodstone dance, this one doesn't use forceMove)

### CODE REVIEW

**Comment by DeityLink** [comment]
And yeah, astral projections can use it as well.

**Comment by drawsstuff** [comment]
https://github.com/vgstation-coders/vgstation13/issues/27136

might wanna look into this while you're at it

**Comment by DeityLink** [comment]
yeah I was actually specifically looking into fixing that one

**Comment by DeityLink** [comment]
Well that took much longer than anticipated

**Pull request merged**
