### PR TITLE
Rune Armor Set

### PR DESCRIPTION
**Pull request by GermanSanta**
Since this project grew quite a bit from just adding a rune scimitar. I'm opening a new pull request.
Sprites = Given Real RS colors
Scimitar = lower damage, less force, only 1 in vendor
Armor Set located in Cargo Knight Crate
Open for changes and possibility to becoming a vault item

### CODE REVIEW

**Comment by ghost** [comment]
this is cool! :) smile.

**Comment by brndd** [comment]
I'm updooting because the sprites look good and it's a fun idea, but I must say I don't think this stuff belongs in the vendor or cargo crates.

A little bit of mapping and a Runescape music vinyl and you'll have a 💯 asteroid vault IMO.

**Comment by brndd** [comment]
Also your diff is all fucked and I think it's reverting a bunch of newer PRs.

**Comment by Dacendeth** [comment]
Nice changes, 20 force and 1.0 sharpness is much more fair than you had it previously, it was dangerously close to an energy sword in your previous version.

**Comment by Tokanova** [comment]
so are you going to add sea shanty 2 to the jukebox too? because that would be cool

**Comment by SonixApache** [comment]
needless content
simple reskins of existing content only for epic references aren't worth being added

**Comment by Probe1** [comment]
Include pictures of the icons in the PR please.

**Comment by GermanSanta** [comment]
Vault Update: Added a vault map. Upped the stats of rune armor/scimitar.
Removed Armor from cargo crate
Remove Rune Scimitar from Al's fun and games (we tried)
download

**Comment by Kurfursten** [comment]
I'm not sure what to make of this new vault. It just seems so zany for a roid vault.

We go a little more out there with space vaults because they're less common - you won't see them often and it could be nearly anything floating in the void of space. Remember roid vaults are like Angie, miners will see them all the time, and this is really anti immersions to just be embedded in rock randomly.

**Comment by GermanSanta** [comment]
That's kind of the point. My idea behind this was having it be a space vault. A chunk of gielinor just floating there or for adminbuses. Hence the updated stats of the armor.

**Comment by brndd** [comment]
if it's a space vault you can get rid of the 1 tile of roid surrounding it

**Comment by Kurfursten** [comment]
What brndd said

**Comment by GermanSanta** [comment]
Tiles removed 
Removed some mobs
Updated all files due to recent vgstation additions
download

**Comment by ghost** [comment]
stronghold of player safety vault when

**Comment by Kurfursten** [comment]
>diff +57,067 −10,468

GERMAN SANTA BECOMING TOO POWERFUL

SOMEONE STOP HIM

**Comment by SonixApache** [comment]
remember, do a merge commit, not a rebase

**Pull request closed without merging**
