### PR TITLE
[Role datums] Combining current progress

### PR DESCRIPTION
**Pull request by MadmanMartian**
couldn't wait for #16234 to be merged so pulled it, merged it, fixed it, combined it.

gotta love merge commits

will try to fix further when I wake up

### CODE REVIEW

**Comment by MadmanMartian** [comment]
just check the 'combining the current progress' commit for my changes

**Comment by Exxion** [comment]
26000+ changed lines across 500+ files
Jesus fucking Christ

I hope you know that attempting to get a single PR this big all working at once is a task nobody here has ever succeeded at

**Comment by Intigracy** [comment]
This isn't all role datums.

A lot of it is entirely unrelated.

**Comment by Exxion** [comment]
To be clear, I *strongly* recommend you do the opposite of this: break big changes into smaller PRs. It's easier for everyone that way.

**Comment by MadmanMartian** [comment]
the only reason this is like this is because I started the branch on bleeding edge, and vgstation-coders/role datums is about a month behind bleeding edge.

**Comment by Exxion** [comment]
Oh, then carry on

**Pull request closed without merging**
