### PR TITLE
Hallucinations can change client.dir

### PR DESCRIPTION
**Pull request by unid15**
There are no bugs in this screenshot, only features

Effect lasts 10-40 seconds

### CODE REVIEW

**Comment by ghost** [comment]
This is not ready until #5001 has been merged due to stuff like hotkeys or otherwise

**Comment by unid15** [comment]
Well, since it's a mindbreaker effect, I don't think messed up hotkeys are that big of a deal. Call it a part of the experience

**Comment by 9600bauds** [comment]
The most literal case of I-IT'S A FEEEAATUUUREEE
:+1:

**Comment by Shadowmech88** [comment]
Jesus Christ how horrifying.
:+1:

**Comment by xpcybic** [comment]
dude like
when i turn around
the world turns the OTHER WAY around man

**Comment by 9600bauds** [comment]
Add a hallucination that makes it so that the world always turns with you, so that you're always facing away from the camera and trying to turn makes the world turn instead

**Comment by Shadowmech88** [comment]
We should also have a hallucination that mirrors the world for you.

**Comment by PJB3005** [comment]
@Shadowmech88 gonna be hard but it should be doable in 510.

**Comment by Probe1** [comment]
I fucking love this addition.

**Pull request merged**
