### PR TITLE
Vomit electrolysis

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
You can now electrolize vomit into equal parts sacid and nutriment.
Or turn sacid and nutriment into vomit (with 5u enzyme catalyst), if you need vomit for some reason.
Stomach acid is actually HCL, not sacid, but I ain't adding a whole new acid just for 1 or 2 uses when sacid works just fine. Spessmen use sacid for digestion, it's canon now.
## Why it's good
Gives you a way to manufacture vomit (if you need some for whatever reason [like gunk roleplay or making nutrition cubes]), and a way to acquire sacid, should you source enough vomit.
## How it was tested
Spawned beaker. 
Vomited.
Electrolysis.
:cl:
 * rscadd: Vomit can be electrolized into equal parts sacid and nutriment, or made with equal parts sacid and nutriment, plus 5u Enzyme.

### CODE REVIEW

**Comment by CrazyAmphibian** [comment]
make it HCL coward

**Comment by hacker-on-steroids** [comment]
M
U
R
I
ACID
T
I
C

**Review by west3436 — APPROVED** [review]

**Comment by west3436** [comment]
Absolutely repugnant
Will merge after you fix conflicts @Eneocho

**Comment by Eneocho** [comment]
@west3436 done

**Pull request merged**
