### PR TITLE
advanced lung toxin/sleep immunity

### LINKED ISSUE #35046: Advanced Lungs do not filter gasses
#### Description of issue
Advanced lungs don't properly filter 

#### Difference between expected and actual behavior
Advanced lungs do not filter gasses as intended, so you still take toxin damage even if the air contains enough breathable gasses to otherwise be fine. Example pictured below:
dreamseeker_uzON8AYrh6

#### Steps to reproduce
Get advanced lungs, walk into an area with toxic gasses, attempt to breathe.

#### Length of time in which bug has been known to occur
No idea, but a trialmin I spoke with knew the lungs didn't work properly. Quite a while, apparently.

### PR DESCRIPTION
**Pull request by ghost**
## What this does

This buffs advanced lungs to totally filter out toxins and sleep chems. It also makes it so that those with advanced lungs need less of whatever chemical they need to breathe, to not suffocate. Closes #35046.

image
image

## Why it's good

In #35046 consensus seemed to be that advanced lungs should be more powerful.

## Changelog

:cl:
 * tweak: Advanced lung buffs.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Advanced organs are underrated and nobody takes them, this should shake things up a little.

**Comment by SonixApache** [comment]
Just to check; this removes the sleepy/toxic effect from being in atmospheres with those gasses, and does nothing for survival in low-oxygen environments, right?

**Comment by ghost** [comment]
@SonixApache With the min_pp change, it actually buffs the ability to survive in low oxygen for humans/low nitrogen for vox/low plasma for plasmamen, without removing the requirement to breathe some. That was suggested here:

[_"Maybe they should pull more of the breathable gas out of the air, so you can tolerate lower oxygen environments as a human and lower nitrogen environments as a vox. So lowering the min_pp values a bit to 8 or something."_](https://github.com/vgstation-coders/vgstation13/issues/35046#issuecomment-1732394991)

**Comment by ghost** [comment]
It occurs to me that an additional test is probably necessary to confirm cold/hot gasses are handled as we'd want them to. Advanced lungs shouldn't let you breathe super hot plasma I don't think. 
https://github.com/vgstation-coders/vgstation13/blob/7029e794f088d6cb70699466442d7be0279ea0cb/code/modules/organs/internal/lungs/lung.dm#L55
The code with lung_gasses.dm, _gas_mixture.dm, lung.dm is new to me so I can't say for sure that will work right. I don't see where `breath.temperature` is getting set.

**Comment by ghost** [comment]
Through varediting an oxygen tank to fill it with hot plasma and and having a human with advanced lungs breathe through it I've confirmed that they don't take toxin damage but still take damage from the temperature, which is what we want. `breath.temperature` is properly set by the procs in [/mob/living/carbon/complex/proc/breathe()](https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/code/modules/mob/living/carbon/complex/life.dm#L52), and does not depend on the lung gasses list.

So, this is READY TO MERGE.

___

I discovered what might be a bug UNRELATED to the changes in this PR, for which I will open a new issue. The `H << "<span class='warning'>You feel your face burning and a searing heat in your lungs!</span>"` type lines don't appear to log correctly in our `/datum/organ/internal/lungs/proc/handle_breath(var/datum/gas_mixture/breath, var/mob/living/carbon/human/H)` proc in lung.dm. No output to `H` I have tried adding has actually been visible by me, the player on my local. I wonder if others would encounter this.

**Comment by pulserider** [comment]
this gives me more reasons to replace peoples organs in maintenence. hell yeah

**Pull request merged**
