### PR TITLE
Remove black outlines on all labcoats

### PR DESCRIPTION
**Pull request by ghost**
Because it looks terrible. Real-life labcoats don't have black outlines anywhere, they're nearly pearl white with barely grey "outlines"

Sample from new sprites : 

labcoat_front
labcoat_back
labcoat_side
labcoat_chem_item
labcoat_cmo_front
labcoat_cmo_back
labcoat_cmo_side

This might blend in slightly with white tiles (although honestly this should be expected), but this is at the flipside of looking plain better in every single other situation

Dressed-up example : 

Old : 

md

New : 

md_new

As you can see, I removed a really strange black outline on the sleeves, and the outline is still here, just blended in much better

### CODE REVIEW

**Comment by Probe1** [comment]
image

old way looks much better.  its an outline.  like how the nuka cola machine looks like ass.  vending machines don't have black outlines irl either.

**Comment by dylanstrategie** [comment]
The labcoat items looked about fine. The worn sprites really didn't

Also, I fixed the sprite offset while I was in here, and the really strange alignment problem with the color sigils

**Comment by d3athrow** [comment]
There's a reason why weve got outlines on things like this we're limited to detail in such a small image area.

**Comment by dylanstrategie** [comment]
The thing is, I didn't remove the outlines completely, they're just blent much more

If you look at the old worn sprite and carried item, there's a net difference even there. The labcoat arms had a normal grey outline in the item (which I used in this PR), whereas the worn sprite had a strange black outline

**Comment by dylanstrategie** [comment]
I'll post a dressed-up example then

Old : 

md

New : 

md_new

As you can see, I removed a really strange black outline on the sleeves, and the outline is still here, just blended in much better

**Comment by PJB3005** [comment]
:+1:

**Comment by N3X15** [comment]
@d3athrow Any comment on this?  Are you still of your earlier opinion?

**Comment by Probe1** [comment]
Merge it and let the players decide @d3athrow @N3X15

**Comment by clusterfack** [comment]
Shove it in

**Pull request merged**
