### PR TITLE
Added Emperor's new clothes

### PR DESCRIPTION
**Pull request by Kurfursten**
Contraband autodrobe item

Here's what it looks like when worn
untitled

🆑 
* rscadd: The Wonderful Wardrobe now may contain incredible, magical clothing from an ancient emperor.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Is the person who's wearing it able to tell that there's nothing there?

**Comment by boy2mantwicethefam** [comment]
Ni:b::b:a pls

**Comment by Kurfursten** [comment]
Yes, although you bring up an interesting point. With overlays we could actually make it appear that they are wearing clothing.

Real sprites instead of codersprites would be nice too

**Comment by DeityLink** [comment]
Those are some really nice clothes.

**Comment by bathosbathtime** [comment]
I would personally like it better if it didn't have any of the layer stuff as that takes away from the source material
Then again it looks like you can clip an ID to it so maybe I'll shut up

**Comment by Kurfursten** [comment]
Perhaps you're right, though.

**Comment by Kurfursten** [comment]
Donated spritework

**Comment by Shadowmech88** [comment]
Making it invisible to everyone would be truer to the source material, strictly speaking, but the fact that there's no con men and no con involving the clothes would mean that there wouldn't really be anything interesting about the clothes beyond the reference. It'd just be a way to use your ID slot and pockets while "naked."
I think it'd be funnier if it was a piece of clothing you could gift to unsuspecting crewmembers (who don't use Github) who would then believe that they're wearing clothes when they actually aren't.

**Comment by Kurfursten** [comment]
You inspired a genius change. It will be totally invisible as before, but it's going in the Wonderful Wardrobe so people can be conned into buying "magic clothing"

**Pull request merged**
