### PR TITLE
Adds 6 civilian softsuits to box EVA

### PR DESCRIPTION
**Pull request by SonixApache**
like #13973, but simpler
eva

### CODE REVIEW

**Comment by Probe1** [comment]
I'd rather see the medsuits get nixed and the space re-allocated than this full room syndrome.

**Comment by SonixApache** [comment]
*unused space*
I don't get why we have a huge EVA room that has more whitespace than EVA stuff.

**Comment by Probe1** [comment]
I'm going to quip Gary Provost. 

> “This sentence has five words. Here are five more words. Five-word sentences are fine. But several together become monotonous. Listen to what is happening. The writing is getting boring. The sound of it drones. It’s like a stuck record. The ear demands some variety. Now listen. I vary the sentence length, and I create music. Music. The writing sings. It has a pleasant rhythm, a lilt, a harmony. I use short sentences. And I use sentences of medium length. And sometimes, when I am certain the reader is rested, I will engage him with a sentence of considerable length, a sentence that burns with energy and builds with all the impetus of a crescendo, the roll of the drums, the crash of the cymbals–sounds that say listen to this, it is important.”

Variation is important both in room sizes and contents.  If you want a non style reason (though style is incredibly important when it comes to mapping) then it reduces the oversized room to a single tile wide corridor which is never something you want to do aside from rare exceptions.

As it relates to the quote above, EVA is important.  It's supposed to fill the player with interest and wonder, and prepare them to leave the station or survive whats left after disaster.  Having a dinky narrow room isn't any of those things.  It's more of a broom cupboard than the stations EVA.

**Comment by SonixApache** [comment]
i see your point

**Pull request closed without merging**
