### PR TITLE
Removes Xenoarchaeology excavation suit slowdown.

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by clusterfack** [comment]
Lame

**Comment by ghost** [comment]
Xenoarch suits were literally slower than mining hardsuits, hence breaking into Mining to steal one was usually worth your time

I blame Bay snowflakes

**Comment by 9600bauds** [comment]
Inaccurate title, as of now slowdown 1 means literally no slowdown

**Comment by Kurfursten** [comment]
Why break into mining when you have a private chem dispenser that will go otherwise completely unused? Hyperzine all shift.

Although since this PR might be a lead-in to removing the dispenser from the outpost and replacing it with a beaker full of analysis fluid, who knows?

**Comment by PJB3005** [comment]
I honestly never used hyperzine because I couldn't be bothered. One trip to the mining outpost and you're on your way to powergame with my super secret technique.

**Comment by FudgePucker** [comment]
I am pretty sure the xenoarch suit gives you full radiation protection. Making it a space proof radsuit.

**Comment by ComicIronic** [comment]
It does, you can see it right there in the code : `armor = list(melee = 0, bullet = 0, laser = 0,energy = 0, bomb = 0, bio = 100, rad = 100)`

**Pull request closed without merging**
