### PR TITLE
Bear traps kill bears

### LINKED ISSUE #5246: Bear Traps Are Ineffective Against Space Bears
For how rarely bear traps are used and how rarely space bears are encountered, I think it'd be nice for the bear traps to actually work on them.

### PR DESCRIPTION
**Pull request by Kurfursten**
fixes #5246

### CODE REVIEW

**Comment by Probe1** [comment]
this is outrageous

**Comment by ComicIronic** [comment]
2stronk

**Comment by Kurfursten** [comment]
Well, let's talk about it. I was going to suggest triple damage but it turns out that's also an instant kill.

Normal damage: 20
Bear health: 60

I guess I could increase speed** for trapped bears?

**For simple mobs, higher speed means slower movement

**Comment by Probe1** [comment]
its not really outrageous I was meming.

**Comment by Kurfursten** [comment]
1/3 damage is good enough for bears, this PR isn't necessary

**Pull request closed without merging**
