### PR TITLE
Geysers Improved

### PR DESCRIPTION
**Pull request by Kurfursten**
Holiday fix 2

🆑 
* bugfix:  Geysers now properly smoke (vents do not smoke) and heat you up based on your proximity to the geyser. Unstable geysers can burn you fairly easily, so be careful!
* rscadd: Geysers can now melt nearby snow in a circle. Unstable geysers do it the fastest - melted snow? take it slow!
* rscadd: You can shovel a geyser to fill it in and reduce the rate it puts out heat. Do it enough and you can seal it completely. Shovel a sealed geyser to completely remove it.
* rscadd: Geysers hit by explosions can get sealed, but unstable geysers could go critical and spew out extreme heat. Call a suited atmospheric technician to seal it if this happens. Do not be tempted to build a thermoelectric generator around the critical geyser.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
hooray

**Comment by gurfan** [comment]
>Do not be tempted to build a thermoelectric generator around the critical geyser.

I'll try it anyway

**Comment by dunsel-hordon** [comment]
Can you make ice fishing please? Seeing as you can bash holes into the ice.

**Comment by Kurfursten** [comment]
That's out of scope for this PR

I think @greatbigfailure is working on fishing systems

**Pull request merged**
