### PR TITLE
Prelim cloning

### PR DESCRIPTION
**Pull request by ririchiyo**
All this does is allow people to add the clone pod to the multitool buffer and connect it to the console if the distance is less than 7. So you can have the cloning pod further away from the console so you guys can actually make maps that take advantage of this with cycling gas in areas for cloning different types of species. So you don't have to rely on making any changes to how cloning behaves and this is just preliminary work on other things I intend to do to change to cloning based on another machine that is going to be utilized by the cloning console.

Edit: I also moved the cloning files from code\game to code\modules\medical because it makes more sense. Down with code\game.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Very informative.

**Comment by ComicIronic** [comment]
What does this change and why do we want it

**Comment by ririchiyo** [comment]
All this does is allow people to add the clone pod to the multitool buffer and connect it to the console if the distance is less than 7. So you can have the cloning pod further away from the console so you guys can actually make maps that take advantage of this with cycling gas in areas for cloning different types of species. So you don't have to rely on making any changes to how cloning behaves and this is just preliminary work on other things I intend to do to change to cloning based on another machine that is going to be utilized by the cloning console.

**Comment by 9600bauds** [comment]
Does the roundstart cloner spawn disconnected? If so, Medbay would need a multitool before they can clone anyone.

**Comment by Probe1** [comment]
I like the multitool aspect.  It'll encourage people to remember you can multitool a plethora of different things and link them together for interesting effects.  

I hope the roundstart cloner in medbay does not require linking.  If it does, I offer the criticism that it will just result in busywork/routine that everyone will always do at the start of every round and not generate any positive or meaningful difficulty that would dissuade players from using the cloner.

However I have always felt that cloners linking themselves automagically when built was not in line with other machines in game and inconsistency between machines is my pet peeve, so I think adding that is a good move.

**Comment by ririchiyo** [comment]
It is unlinked by default at round start. It's mostly to get people used to the multitool buffer and see that it exists. I'd like to add many more machines that take advantage of it because it's woefully lacking at the moment but one thing at a time.

**Comment by Probe1** [comment]
Right, I downloaded a copy and looked around.  I don't see a multitool in medbay anywhere.  Also only the cloning pod was unlinked.  The scanner was still linked just fine which I suppose is a strategy decision so you can scan someone important early knowing that you can hook the machine up later but you've got (the captains or whichever VIPs) scan ready.  

Overall, I think it doesn't add any challenge or positive work to a medbay shift, either with a multitool added or not.  It just makes it part of the routine of someone else (Mechanic, Engineers, Doctors visiting autolathe locations).  It keeps cloning out of the players hands as long as it takes a paramedic to walk to cargo, ask for the multitool laying on top of the metal and glass, and walk back.  

But it does fit in line with other actions in medbay (cryo having to be turned on).  So it's not a random balance change, it's logical and fits in with cryo.

Pros 
- adds another step players have to take before they can clone people
- forces player interaction since they need a multi tool or personnel that have one

Cons
- the substance it adds is insubstantive. it's mindless busywork you learn once and do every time without thinking
- it is out of character for medical personnel to have to link machines.  the freezer is basically a big thermostat with an on/off switch which doesn't require much suspension of disbelief that anyone would know how to operate it.  a multitool on the other hand, used to link machines together for proper operation, feels much more into the area of engineers and mechanics than doctors and medical personnel.  And I don't believe the engineer playerbase will be rushing to lend medbay a  roundstart hand every single round instead of setting up engines and working on projects.  So I think any change to the machinery being linked will be something that is handled internally by medbay players, not by other departments.

Overall I don't think it's a good idea to have them unlinked **but** I don't consider it a dealbreaker or a reason not to merge.  It doesn't create any positive work, challenge, or enjoyment and I think that the cloning nerf should be better than just making it harder to use.  I support the idea of adding organ and bone damage that surgery has to deal with over making it more tedious to use the cloner.

**Comment by ririchiyo** [comment]
I don't see using a multitool as something that belongs only towards the engineering staff. In the future I want to expand it to many other machines for people to utilize it with. I mostly just didn't want to setup a preset to handle the clone pod for it. And this seemed like a good way to get people familiar with knowing that the multitool is something that can be used on machines to link them and set frequencies for certain machines.

Ideally I would like to have had the cloner completely removed in the beginning but this isn't a controversial balance chance and I'd save that for another PR/discussion as the cloner shouldn't be involved in the round at the very start. The cloner as it is makes people shrug off death, have the station rely on the research department gives them accountability. The game is built around inter-departmental interactions.

Aside from that, it's mindless busywork there to keep and show people that it is a thing. It shouldn't be seen as out of character as this is supposed to be a research station after all as well. This is a very simple change to just make the stupid clone pods need a multitool to be linked instead of it automatically being handled or being forced to be built beside the machine. This allows you to connect it from a distance so people can access it and solves people wanting to make a cloning room for different species. It allows the separation of the console + cloning pod.

I also don't really care if you don't merge it or not or whatever. I don't plan to support this if it gets a ton of conflicts or people don't like it someone else can just expand on it and do the same for medical it doesn't matter to me.

**Comment by Probe1** [comment]
It would benefit you more to add a multitool to medbay in that case, along with the wrench and crowbar near cryo, so people understand how it's supposed to work.

**Comment by d3athrow** [comment]
Why not have it autolink with adjacent things but also have the multitool menu, because having it unlinked is just going to confuse the fuck out of people

**Pull request merged**
