### PR TITLE
Vaultifies the goone satellite

### PR DESCRIPTION
**Pull request by MadmanMartian**
Changes most of it to teleblocking

Removes it from maps that had it

:cl:
 * tweak: The goone satellite has drifted out of static orbit

### CODE REVIEW

**Comment by Kharkov72** [comment]
Normally I'd say this is a good change but deff and roid have unique goonsats, what about those

**Comment by MadmanMartian** [comment]
Deff one looked like shit, roid keeps it as it's not a goone satellite, but an asteroi

It doesn't even have a copy of the goone code in it

**Comment by DrSnips** [comment]
~~Ah great just what we need. Less stuff in space.~~
You already axed clown roid and now we are [re]moving goon sat. ~~Can we get some stuff to replace these technically removed locations.~~  I bet the DJ sat is up next.

**Comment by DrSnips** [comment]
Can we get some reasoning on why we should remove the goon sat being static?

**Comment by MadmanMartian** [comment]
Filling the void with random vault potential area

And the reasoning is namely telescience abuse of it.

The black present spawn has a chance of a cryptographic sequencer, so people tend to telescience that out, in addition, they also telescience the bluespace crystals that are off to the side, which were previously not within an untelesciable area. This let people unlock telescience's full potential at roundstart with 0 effort.

**Comment by DrSnips** [comment]
Thanks for the space fill stuff that makes this a bit better.

**Comment by FudgePucker** [comment]
Just fucking remove telescience then.

**Comment by FudgePucker** [comment]
Or better yet, just add jamming, isn't there a tracking beacon on the satellite?

**Comment by utilitas-** [comment]
The AI satellite is fucking huge. Don't. I'll bet that it adds multiple seconds to initialization whenever it spawns. Those stack up.

**Comment by tuypo1** [comment]
Sending the crew off to the goon sat is fun, don't take that away from us.

**Comment by SonixApache** [comment]
Yeah, how does this work with the tracking beacon? Does that just work?

**Comment by MadmanMartian** [comment]
It just works, same with it still having the old docking ports

**Comment by Blithering** [comment]
So you can still send shuttles to it and set it as a teleporter destination after vaultification? sounds like the only ones fucked over by this are telesci nerdlingers.

**Comment by tuypo1** [comment]
Oh well if you can still use the teleporter to get to it I am fine with making it a vault

**Comment by FudgePucker** [comment]
Also the fact that it would have a chance to not spawn.

**Comment by FudgePucker** [comment]
Just add teleport jamming

**Comment by Blithering** [comment]
But you can make vaults guaranteed spawns, I asked about this in the clown roid vaultification PR.

**Comment by DeityLink** [comment]
I think it's time we moved on honestly.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Still telesci-metagamable roundstart by law2ing the AI into turning on the station teleporter and then teleporting a posibrain over.
I would like the loot to be teleshielded on top of this.

**Comment by tuypo1** [comment]
What the hell is the point of having inactive posibrains show up on the cmc anyway, remove that feature and it becomes a non issue.

**Comment by DrSnips** [comment]
I'm pretty sure the op says that he added tele blocking.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
My mistake I saw https://github.com/vgstation-coders/vgstation13/pull/23716#issuecomment-516530747 and assumed that wasn't the case

**Comment by plosky1** [comment]
Teleblocking it is a good idea because of people teleporting the gift box out.

Outright making it not static is not a good idea, and I GUARANTEE you this will fail if a server vote is run.

If the problem is that it's too easy to get Matebas, why not just re-do the box version? Deff and Roid version is pretty difficult to get through.

**Pull request merged**
