### PR TITLE
Tilebound

### PR DESCRIPTION
**Pull request by clusterfack**
To fix the issue with things larger than 32x32 or transformed or what not being seen from further away than they should be, we are giving the tile bound flag to all movable atoms.

I have explicitly removed it from icons that are larger than 32x32 beacuse they should be visible either way.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Will this fix #10398

**Comment by clusterfack** [comment]
That is the plan

**Comment by ComicIronic** [comment]
Did you test NarSie with this

**Comment by clusterfack** [comment]
There's not much to test about it? This just removes the double narsie thing you see occasionally

**Comment by clusterfack** [comment]
Here's a description of the tile bound flag from the reference

TILE_BOUND

There are many ways an object may be shifted out of the normal bounds of the tile it's on: a large icon, pixel offsets, step offsets, and transform. Ordinarily it's desirable to be able to see the object if it touches any visible turf. However, in some cases it's more desirable to only show the object if its actual loc is in view. The TILE_BOUND flag will accomplish that. 

TILE_BOUND is inherited by images and overlays.

**Comment by ComicIronic** [comment]
I'm pretty sure the NarSie code is meant to let you see him even if all his turfs are hidden, so TILEBOUND won't preserve behaviour.

**Comment by ComicIronic** [comment]
Even if that part of the icon is hidden by a wall?

**Comment by clusterfack** [comment]
It pisses me off but I think you are correct

**Pull request merged**
