### PR TITLE
Adds Paints to Trade Outfitter

### PR DESCRIPTION
**Pull request by falcon2346**
[content]

## What this does

Adds a new toolbox to the trade outfitter containing each color of paint, available for purchase for 80 credits. This does not contain canvases, a paintbrush, or a palette, as traders can produce their own wood.

## Why it's good

Adds a new avenue for an artistically inclined trader without having to make a deal with their biggest competitor, cargo.

## Changelog
:cl:
* rscadd: Added painter's toolbox containing paints to the trade outfitter.
* imageadd: Added sprites for the painter's toolbox.

### CODE REVIEW

**Comment by falcon2346** [comment]
I've attached the sprites used for the painter's toolbox below:
dreammaker_Hdw20qCdBn
dreammaker_a8Xd80lzpl
dreammaker_nbB0CHWESa
dreammaker_a0RgTCUfYD
dreammaker_rDzOUV7GgK
dreammaker_QczSEUlUdP
dreammaker_ZSMH7pbDSs
dreammaker_kcF6TzoXYv
dreammaker_rQtqFVieR4

**Comment by PrimeDSS13** [comment]
80 is way too much, considering the art supply crate is only 10 credits and it has all the paints + art supplies.

**Comment by falcon2346** [comment]
The initial thought behind the high price was to make it undesirable to try and simply flip the paints instead of actually using them but I suppose for that it just needs to be above 10 by any amount. Dropped price to 40 to ensure that a trader with a poor starting roll can still purchase a junk crate as well.

Also changed the in-hand sprites border on the new toolbox to be the same color as the world sprite instead of a bright orange.

dreammaker_htlxWeAzxK
dreammaker_quMvZ0sF7W
dreammaker_VTncSAXNN3
dreammaker_MdsQOMXfEz

**Comment by WindowsErrors** [comment]
> 80 is way too much, considering the art supply crate is only 10 credits and it has all the paints + art supplies.

The rationalization for the cheap supply crate prices is that they're subsidized by the company so they can be purchased at nearly the price of production, sort of like how food banks have trade agreements with farms and food producers to get stuff at like, an 80-90% markdown compared to the grocery store shelf prices
~~That being said, I have not encountered a single trader doing a similar agreement of getting dirt cheap maintenance crates, medical crates, and that one crate with the fire axe in it, and then selling it back to the crew at a 5x markup~~

That being said, 40 does seem a bit more rational considering how it's just paint and crayons

**Pull request merged**
