### PR TITLE
Lube stuns you for 10 seconds instead of 20

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Makes it more bearable eh?
:cl:
 * tweak: Slipping on lube stuns you for half the time it used to.

### CODE REVIEW

**Comment by Kharkov72** [comment]
feels a bit much of a change but as long as I can still lube people into space which is the real funny part of lube

**Comment by GermanSanta** [comment]
Too much of a change. Think of the poor clumsy clown slipping the man with an esword for him to get up again!

**Comment by KingofHONK** [comment]
FUCK

**Comment by Killette2** [comment]
Does this make it not valid you then?

**Pull request merged**
