### PR TITLE
bottles n shit

### PR DESCRIPTION
**Pull request by jakmak3**

### CODE REVIEW

**Comment by Probe1** [comment]
god bless

**Comment by ComicIronic** [comment]
Does this work? You might have made `/obj/item/weapon/reagent_containers/glass/bottle/rezadone/obj/item/weapon/reagent_containers/glass/bottle/rezadone`

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/pull/13273

**Comment by ComicIronic** [comment]
Fucking jej

**Pull request merged**
