### PR TITLE
Bluespace matter bins

### PR DESCRIPTION
**Pull request by SonixApache**
- Holds more than super matter bins
 - Automatically grabs mats from any other ~~machine~~ FABRICATOR that has bluespace bins if needed
 - looks rad

~~also unatomically fixes descriptions of stock parts and the resource costs that people forgot to fix~~

🆑 
 - rscadd: Added bluespace matter bins. On top of being able to hold more materials, they also automagically grab materials from other fabricators equipped with them if needed.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Put the material costs in a different PR jesus

**Comment by SonixApache** [comment]
yeah fair point

**Comment by Kurfursten** [comment]
Please list all the changes to machine efficiency this will cause. I know for example fabricator children (e.g.: autolathe, exosuit fab) will just have their max materials increased by 187500. Egg incubator will go up to 4 eggs. Essentially just go through all the upgradeable machines that include matter bins and tell us what's new with tier 4 so we can consider that.

**Comment by SonixApache** [comment]
what you posted +

 - sorting machine sorts more at a time
 - ore processor smelts more sheets at a time
 - stacker stacks faster
 - pacmans hold more sheets
 - grinders hold more stuff

**Comment by Exxion** [comment]
Why does it say so many icons were modified? Also why is the file more than twice as big?

**Comment by SonixApache** [comment]
No idea. Palette stuff, maybe?

**Comment by strawberrytan** [comment]
Hold up a minute can you blue space materials from the stacker to r&D

**Comment by CptWad** [comment]
based on his description yes,
however this actually means that if the stacker detects 50 sheets it spits them out, so I would wonder if upgrading it would actually be more detrimental

**Comment by strawberrytan** [comment]
or maybe you could do some meme setup with a dummy protolathe at the miner's smelting area to instantly transit the materials

**Comment by SonixApache** [comment]
stackers aren't fabricators
people've brought up some valid points, like ~~having to z-level lock it so derelict crabs don't steal all your mats~~ but i feel like it's fine as-is.

**Comment by SonixApache** [comment]
this might cause some fuckery with the subspace tunneler, have yet to test it but there's a decent chance it'll be wonky
\*edit*
slimes has offered to update the tunneler for me, so that's all set

**Comment by strawberrytan** [comment]
bluespace stomachs to share meals when?

**Comment by MadmanMartian** [comment]
@SonixApache So is this good to go or is it waiting on the tunneler update?

**Comment by SonixApache** [comment]
Good to go, tunneler update is a @DrSnips thing which is independent, no idea when he's going to work on it

**Comment by DrSnips** [comment]
I will make it in another PR.

**Comment by MadmanMartian** [comment]
We can safely assume it's a definite possible maybe.

**Comment by MadmanMartian** [comment]
??

**Comment by DrSnips** [comment]
You died on discord.

**Comment by MadmanMartian** [comment]
Oh. I said I was going to take the week off as there's a lot of university stuff to get done. Consider this my cheat hour. Will be back on tuesday.

**Pull request merged**
