### PR TITLE
NRV Horizon

### PR DESCRIPTION
**Pull request by plosky1**
Attempt #2.

Changed the name to NRV Horizon because people said NTR jokes would be made, not that I care, but hey you gotta please the emojicracy.

Once again I made this map because fuck the threadposters who said I can't map.

output

[Horizon]
:cl:
 * rscadd: New map - Horizon.

### CODE REVIEW

**Comment by plosky1** [comment]
@jknpj idk what the Horizon tag is but I tried

**Comment by plosky1** [comment]
Added an IAA's office.

**Comment by Lunstra** [comment]
I am disappointed you didn't keep it NTR station. Embrace the memes.

**Comment by plosky1** [comment]
This (theoretically) should be the last change, added an IAA's room and @BurntDevil moved it to a nice location. Updated render on the original post.

**Comment by RaccoonBro** [comment]
R-walls for Chemistry and Genetics seems a bit excessive

**Comment by plosky1** [comment]
Remove the r-walls, stuck some chonker engines on (courtesy FTL13), and added some dock lights.

**Pull request merged**
