### PR TITLE
Cigar/cigarette chemical fluff, take two

### PR DESCRIPTION
**Pull request by ghost**
[content]
Redo of #31555
This PR makes tobacco actually have beneficial effects and refines the negatives a bit, this time without actually giving people cancer and balancing things a bit nicer.

- Nicotine now reduces jitter, drowsiness and confusion by 1 on each tick, making it a weaker ethylredoxrazine.
- Tobacco does the same, but with a 5% chance to cause coughing per tick after 60 ticks and lung damage after 180, in a time based overdose system.
- Unfiltered tobacco is a new reagent, that triples the effects of the nicotine inside with the cost of it 4 times more likely to do cough or cause lung damage on tick overdoses (5 > 20%) three times sooner

## Cigarette brand changes:

All of these are on top of containing 5 tobacco, unless noted:

- Shoalsticks/bidis now contain 5 units of gravy, to heal vox.
- Golden carps now contain 1 unit of gold powder, from their rolling paper.
- Starlights now contain 5 units of dexalin.
- Lucky strikes now contain purely unfiltered tobacco.
- Deluxe lucky strikes also contain 5 units of pure nicotine on top of this.
- Redsuits now contain the reagents required to make a small puff of smoke and also a small chance to contain camera bugs.
- NT standards now contain 5 units of sprinkles, to heal security and command.
- Spaceports have a small amount of their tobacco replaced with discount dan special sauce, for economy reasons.

And cigars too, why not.

- Cigars now contain double the tobacco of a cigarette.
- Cohiba robusto cigars contain 5 units of sportdrink, for extra robustness.
- Premium Havana cigars contain 5 units of pure nicotine.

Let me know if any of these need tweaking or balancing.

:cl:
 * rscadd: Cigarettes in vending machines now have some extra "medicinal" purposes to them, according to supposed research or ad campaigns.

### CODE REVIEW

**Comment by djkramer123** [comment]
>cigarettes that come with hyperzine
why are you like this

**Comment by djkramer123** [comment]
Why do cigarettes need to be anything more than fluff items?

**Comment by kane-f** [comment]
> Why do cigarettes need to be anything more than fluff items?

Removed it.

**Comment by tomacatx2** [comment]
good PR, hope to see it ingame, thank you for giving the smoker metaclub more representation

**Comment by gurfan** [comment]
fuck the lung damage shit

**Comment by Kurfursten** [comment]
Don't like the access to all these special chems for cigs, why is it that you now go to the cig vendor to buy a ghetto spacesuit?

**Comment by ghost** [comment]
> Don't like the access to all these special chems for cigs, why is it that you now go to the cig vendor to buy a ghetto spacesuit?

Starlights don't make you immune to pressure and don't really fully fix oxygen damage.

**Comment by Eneocho** [comment]
I asked on the previous PR, does this affect blunts? Because as far as I remember blunts spawn with 5u tobacco by default that overrides 5u of your blunt's ingredients. I don't want my megablunts to fuck people up when they're tailormade to heal shit.

**Comment by Kurfursten** [comment]
> > Don't like the access to all these special chems for cigs, why is it that you now go to the cig vendor to buy a ghetto spacesuit?
> 
> Starlights don't make you immune to pressure and don't really fully fix oxygen damage.

Neither of those is close to the reason we wear spacesuits, it's to avoid the ghost of Celt AKA hypothermia

Even then I don't understand why the change at all. Why make such a relatively rarely made chemistry chem widely available? Why make cig brand a matter of powergaming instead of roleplaying?

I guess I partially blame Gray Foods PRs for creeping in this vein too, but at least they're gated by rare vendor and sometimes race. I don't want to see a PR next year where Space Cola contains bicaridine, Orange Soda contains dermaline, and Lemon-Lime contains peptobismol.

**Comment by SonixApache** [comment]
there's nothing more fun in this game than lung damage, i absolutely adore dying 4noraisins

**Comment by Kammerjunk** [comment]
a good quick and dirty "oh god oh fuck" pill bottle includes leporazine because it nudges your body temperature towards 310 K (36.85 C) by 60 K (or C) every tick. it also includes dex+ cause dex is poopy
that is all I have to say

**Comment by Eneocho** [comment]
Good chemists will make lepo pills just because they had the 5u plasma on the beaker and felt like doing a bit more

**Comment by Kammerjunk** [comment]
well yes sure but that's not the point

**Comment by Eneocho** [comment]
While I do like the idea of cigarettes no longer being fluff only and having actual chems inside, I insist that the proper way to fluff the smokeables up is to add some bluegoo/locutogen kinda thing that gives you a line or two about being superior to those smoking lesser brands. 
Say you're smoking Lucky Strikes and walk near a guy smoking shoal sticks, you could get a message that says something like "You smile, knowing you have better taste in cigarettes/cigars than [shoal sticks guy]."
Powergamey chems in easy to acquire form is no good, sure, keep the 1u gold from the foil or the dansauce, but free smokescreens, vox specific antitox or literal spaceproofing chems are a real steep slippery slope.

**Comment by Eneocho** [comment]
Also the lung damage is dumb, nobody likes getting lung damage and having to go to medical to get it fixed, it will only be tedious. What kinda fucking tobacco are they using if you can get turbofucked in 2 hours of smoking.

**Comment by KillFurries** [comment]
This should be two PRs. One PR for nicotine to have effects that may be harmful. Second PR for the different brands to have different flavor fluff.

**Comment by adacovsk** [comment]
smokers are jokers

**Comment by ghost** [comment]
Replaced the leporazine with more dexalin.

**Comment by anunknownentity03** [comment]
port goon's smoking effects and you have me sold @kane-f

**Comment by ManopolisJones** [comment]
I still think it's a cool idea, I still think it's the redsuits that should have the sprinkles, not the NT standards.

**Comment by TGFH** [comment]
@ManopolisJones 
The redsuits are contraband. It's supposed to be a reference to Syndicate blood red hardsuits/red space suits.

**Comment by Eneocho** [comment]
@kane-f, you still haven't answered the ambrosia thing. Does it affect blunts? Because if so, please remove those 5u tobacco from the weed.

**Comment by wotisjanitor** [comment]
Just keep the reduced shakes please. Everything else is dumb.

**Comment by SonixApache** [comment]
i said this in discord but i'll say it again here
make tobacco only remove jitter slightly
the gold in the golden carps is fine and cute

ditch the rest

**Comment by Eneocho** [comment]
Reminder that Discount Dan's now has a nutrition value (it's 4), so you could literally feed/go overweight by smoking spaceports.

**Comment by Armadingus** [comment]
I'd rather see the tobacco activate the cough gene defect rather than lung damage, even if we already have average reagents like corn oil delete your heart, I would like to see less lethal reagents and more inconveniencing soft griff reagents.

**Comment by Kurfursten** [comment]
Lack of support

**Pull request closed without merging**
