### PR TITLE
Add two new names to the credits

### PR DESCRIPTION
**Pull request by ShiftyRail**
With 826 and 759 PRs respectively, it's time.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
@MadmanMartian @DamianX if you have any comments

**Comment by Eneocho** [comment]
If you're doing that you should add more than just those two. I nominate robintime purely because he fixed the darkmode colour problems.

**Comment by Kurfursten** [comment]
Robintime still hasn't finished his coding homework

**Comment by Exxion** [comment]
It used to be pretty easy to get your name in the credits, long ago. (I would know.)
But not *that* easy

**Comment by robintime** [comment]
> Robintime still hasn't finished his coding homework

FUCK YOU OLD MAN!!

**Comment by MadmanMartian** [comment]
yo what the frick

**Comment by Kurfursten** [comment]
There is no evidence that DamianQ, r0b0, unid15, wild-billy, cloroxygen, and N3X15 aren't the same person

**Pull request merged**
