### PR TITLE
nerfs the amount of rads you receive from a DNA injector

### PR DESCRIPTION
**Pull request by ghost**
For some strange reason I keep getting changes in the file that I did not even look at, courtesy of atom.

:cl:
* tweak: DNA injectors now give slightly less radiation damage to the injected

### CODE REVIEW

**Comment by carshalash** [comment]
There goes my ghetto krokodil.

**Comment by ghost** [comment]
I am giving this my personal seal of approval after getting 7 counts of internal bleeding from doing the first 10 blocks of genetics research.

**Comment by ghost** [comment]
@carshalash just inject more of them then

**Comment by ghost** [comment]
whoops

**Comment by ComicIronic** [comment]
Bravo autoformatting

**Comment by PJB3005** [comment]
To be honest this problem wouldn't exist if everybody used a sane editor.

**Comment by Gunosaguki** [comment]
Thanks. Genetics was hell the round I had to report this issue because i got wrecked by rads very quickly. Had the foresight to inform my medbay staff I was gonna die

**Comment by Exxion** [comment]
But you use Atom. Practice what you preach.

**Comment by ComicIronic** [comment]
Look on the bright side: with the new headless Chrome instances, Atom will perform better than ever.

**Comment by Exxion** [comment]
Oh wow maybe it'll take less than a goddamn year to open

**Pull request merged**
