### PR TITLE
obj/item/weapon -> obj/item

### PR DESCRIPTION
**Pull request by DamianX**
`/obj/item/weapon` is a useless type, a lot of things currently use it for no reason.
This PR removes it so that the type paths are shorter.

I generated a list of type paths with `icon = 'icons/obj/weapons.dmi'` with the following proc:
```
/proc/itemicons()
	for(var/t in subtypesof(/obj/item/weapon))
		var/obj/item/weapon/T = t
		if(initial(T.icon) == 'icons/obj/weapons.dmi')
			world.log << "[T]"
```

```
/obj/item/weapon/melee/legacy_cultblade/nocult
/obj/item/weapon/melee/legacy_cultblade
/obj/item/weapon/melee/energy/sword/ninja
/obj/item/weapon/melee/energy/sword/green
/obj/item/weapon/melee/energy/sword/red
/obj/item/weapon/melee/energy/sword/activated
/obj/item/weapon/melee/energy/sword/bsword
/obj/item/weapon/melee/energy/sword/pirate
/obj/item/weapon/melee/energy/sword/dualsaber/bananabunch
/obj/item/weapon/melee/energy/sword/dualsaber
/obj/item/weapon/melee/energy/sword
/obj/item/weapon/melee/energy/axe/rusty
/obj/item/weapon/melee/energy/axe
/obj/item/weapon/melee/energy/hfmachete/activated
/obj/item/weapon/melee/energy/hfmachete
/obj/item/weapon/melee/energy
/obj/item/weapon/melee/defibrillator
/obj/item/weapon/melee/lance/dire
/obj/item/weapon/melee/lance
/obj/item/weapon/melee/baton/loaded/borg
/obj/item/weapon/melee/baton/loaded
/obj/item/weapon/melee/baton/cattleprod
/obj/item/weapon/melee/baton/harm/loaded
/obj/item/weapon/melee/baton/harm
/obj/item/weapon/melee/baton
/obj/item/weapon/melee/classic_baton
/obj/item/weapon/melee/telebaton
/obj/item/weapon/melee/bone_sword
/obj/item/weapon/melee/training_sword
/obj/item/weapon/melee/bone_hammer
/obj/item/weapon/melee/chainofcommand
/obj/item/weapon/melee/morningstar/catechizer
/obj/item/weapon/melee/morningstar
/obj/item/weapon/melee
/obj/item/weapon/reagent_containers/spray/pepper
/obj/item/weapon/tome_legacy/imbued
/obj/item/weapon/tome_legacy
/obj/item/weapon/substitutionhologram/dakimakura
/obj/item/weapon/katana/hesfast
/obj/item/weapon/katana/hfrequency
/obj/item/weapon/katana/magic
/obj/item/weapon/katana
/obj/item/weapon/cane
/obj/item/weapon/dummy
/obj/item/weapon/legcuffs/bolas/mech
/obj/item/weapon/legcuffs/bolas/cable
/obj/item/weapon/legcuffs/bolas
/obj/item/weapon/batteringram
/obj/item/weapon/staff/stick
/obj/item/weapon/toy
/obj/item/weapon/holo/esword/green
/obj/item/weapon/holo/esword/red
/obj/item/weapon/holo/esword
/obj/item/weapon/holo
/obj/item/weapon/gun/hookshot/whip/liquorice
/obj/item/weapon/gun/hookshot/whip/vampkiller/true
/obj/item/weapon/gun/hookshot/whip/vampkiller
/obj/item/weapon/gun/hookshot/whip
/obj/item/weapon/depocket_wand
/obj/item/weapon/armblade
/obj/item/weapon/boomerang/toy
/obj/item/weapon/boomerang
/obj/item/weapon/bikehorn/baton
/obj/item/weapon/glowstick/red
/obj/item/weapon/glowstick/blue
/obj/item/weapon/glowstick/yellow
/obj/item/weapon/glowstick/magenta
/obj/item/weapon/glowstick
/obj/item/weapon/kitchen/utensil/knife/tactical
/obj/item/weapon/kitchen/utensil/knife/skinning
/obj/item/weapon/nullrod/sword/cult
/obj/item/weapon/nullrod/sword/katana
/obj/item/weapon/nullrod/sword/chaos
/obj/item/weapon/nullrod/sword
/obj/item/weapon/nullrod/crozius
/obj/item/weapon/nullrod/spear
/obj/item/weapon/nullrod/chain
/obj/item/weapon/nullrod/honk
/obj/item/weapon/nullrod/cane
/obj/item/weapon/nullrod/morningstar
/obj/item/weapon/nullrod/vampkiller
/obj/item/weapon/nullrod
/obj/item/weapon/peglimb
/obj/item/weapon/shield/riot/buckler
/obj/item/weapon/shield/riot/roman
/obj/item/weapon/shield/riot/proto
/obj/item/weapon/shield/riot/joe
/obj/item/weapon/shield/riot/bone
/obj/item/weapon/shield/riot/tower
/obj/item/weapon/shield/riot/rune
/obj/item/weapon/shield/riot
/obj/item/weapon/shield/energy
/obj/item/weapon/shield
/obj/item/weapon/revivalprod
/obj/item/weapon/rsscimmy
/obj/item/weapon/damocles
/obj/item/weapon/conversion_kit
/obj/item/weapon/fireaxe
/obj/item/weapon/spear/wooden
/obj/item/weapon/spear
/obj/item/weapon/bloodlust
/obj/item/weapon/sord
/obj/item/weapon/claymore
/obj/item/weapon/harpoon
/obj/item/weapon/wirerod
/obj/item/weapon/macuahuitl
/obj/item/weapon/pitchfork
/obj/item/weapon/implantcase
/obj/item/weapon/fishtools
/obj/item/weapon/minihoe
/obj/item/weapon/hatchet/unathiknife
/obj/item/weapon/hatchet/tomahawk/drilled
/obj/item/weapon/hatchet/tomahawk/metal/drilled
/obj/item/weapon/hatchet/tomahawk/metal
/obj/item/weapon/hatchet/tomahawk
/obj/item/weapon/hatchet
/obj/item/weapon/scythe
/obj/item/weapon/grab
/obj/item/weapon/holder/animal/mouse
/obj/item/weapon/holder/animal/corgi
/obj/item/weapon/holder/animal/carp
/obj/item/weapon/holder/animal/cow
/obj/item/weapon/holder/animal/cat
/obj/item/weapon/holder/animal/frog
/obj/item/weapon/holder/animal/snail
/obj/item/weapon/holder/animal/salem
/obj/item/weapon/holder/animal/snek
/obj/item/weapon/holder/animal/slime
/obj/item/weapon/holder/animal/pillow
/obj/item/weapon/holder/animal
/obj/item/weapon/holder
/obj/item/weapon/robot_module/mommi/nt
/obj/item/weapon/robot_module/mommi/soviet
/obj/item/weapon/robot_module/mommi/cogspider
/obj/item/weapon/robot_module/mommi
/obj/item/weapon/robot_module/standard
/obj/item/weapon/robot_module/medical
/obj/item/weapon/robot_module/engineering
/obj/item/weapon/robot_module/security
/obj/item/weapon/robot_module/janitor
/obj/item/weapon/robot_module/butler
/obj/item/weapon/robot_module/miner
/obj/item/weapon/robot_module/syndicate/blitzkrieg
/obj/item/weapon/robot_module/syndicate/crisis
/obj/item/weapon/robot_module/syndicate
/obj/item/weapon/robot_module/combat
/obj/item/weapon/robot_module/tg17355
/obj/item/weapon/robot_module/starman
/obj/item/weapon/robot_module
/obj/item/weapon/arrow/quill
/obj/item/weapon/arrow/rod
/obj/item/weapon/arrow
/obj/item/weapon/crossbow
/obj/item/weapon/groans
```

Then, I removed the icon definition from /obj/item/weapon and added it to all subtypes that needed it.
I then ran the proc again, and verified that the output stayed the same.

```
$ diff before after
44d43
< /obj/item/weapon/dummy
93d91
< /obj/item/weapon/fishtools
```
Those two are fine.

I then replaced all occurrences of `obj/item/weapon` with `obj/item`:
```
$ find . -type f -exec sed -i 's/obj\/item\/weapon/obj\/item/g' {} \;
```
which immediately destroyed all files containing that string in the .git directory, making the repo unusable. Don't do this at home.

I cloned the repo and started again from scratch and used VSCode's search and replace to do what I originally intended to do.
Subscribe to my patreon for more exciting adventures like this one.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Babe it's 4PM, time to review a >1000 changed files PR

**Comment by DamianX** [comment]
b4aa8c0 is the only unreviewable commit, but it only does the search&replace and nothing else. Definitely no backdoors.

**Comment by Dacendeth** [comment]
Wont this cause mr valid to go crazy for a lot more things? I thought that was the point of /weapon/

**Comment by jknpj** [comment]
just add a flag

**Comment by Exxion** [comment]
It's typechecked for in a large number of places which should probably be fixed individually before doing this

**Comment by DamianX** [comment]
image
Every single one of those is shitcode, and these changes make them better, not worse.

**Comment by DamianX** [comment]
If we intend to merge this, I should probably be told when that is going to happen, so that I can fix conflicts once instead of going insane.

**Comment by Exxion** [comment]
They are shitcode but they'll be much harder to find after this because we won't be able to search for them
That's why I was saying they should be fixed first

**Comment by GreatBigFailure** [comment]
I've been wondering why weapon existed, having a single proc tied to it and nothing else.
If and when this gets merged you should first try to clear the current PR list as much as possible to save people from conflicts. Good change but it's potential nightmare fuel.

**Comment by DamianX** [comment]
Fuck it. The instructions on how to do this are in the OP, if anyone wants to do this.

**Pull request closed without merging**
