### PR TITLE
Splits Potion of Invisibility Into Minor and Major Potions

### PR DESCRIPTION
**Pull request by Shadowmech88**
I didn't realize until after the PR was merged that the potion only making the user's body invisible severely limits its usefulness, especially since wizards can already buy cloaking cloaks which are capable of that.

This PR removes the potion of invisibility and adds the potion of minor invisibility and potion of major invisibility.
The potion of minor invisibility makes the user's body, and only their body, invisible for five minutes. It costs 2 spell points.
The potion of major invisibility makes the user's body and anything they're holding or wearing invisible for one minute. It costs 10 spell points.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
have two potions. One of minor invisibility that only makes you invisible (for those who want to get their naked zap on), one of major invisibility that makes everything you're wearing invisible

**Comment by Shadowmech88** [comment]
How much should the minor invisibility cost? 1, 2, or 5 points?
Keeping in mind that for 20 points you can get infinite complete invisibility with the only downsides of needing to move slowly and not use your hands.

**Comment by MadmanMartian** [comment]
5, considering major invisibility is 10

**Comment by Shadowmech88** [comment]
Right, but major invisibility is also much, much more useful than minor invisibility.
Not that I'm saying it *shouldn't* be 5 necessarily, but I don't think major invisibility being 10 points is a good reason for it to be. I don't think two minutes of body-only invisibility is anywhere near as valuable as one minute of complete invisibility.
Maybe minor invisibility should have an increased time limit, like five minutes instead of one.

**Comment by Durgen** [comment]
The clown/mime invisibility spray is crippled by the fact that you can be seen on med/sec huds and tracked by an AI.

Will this have the same issues?

**Comment by Shadowmech88** [comment]
Most likely. The reason you can be seen on HUDs is because your alpha actually gets set to 1 so that you can still be moused-over/clicked on. If it set it to 0 you'd be invincible.
Someone would need to change HUD code so that it specifically does not appear on mobs with `alpha <= 1`.

**Comment by Shadowmech88** [comment]
OP updated with changes.

**Comment by Hugh-G-Rection** [comment]
Wearing a tinfoil hat blocks HUDs, wearing a gas mask and spamming E with two fake IDs will help with camera tracking. Not much help to a robed wizard though, maybe we should allow tinfoil hats to be placed inside normal hats, or at least wizard hats?

**Comment by DrSnips** [comment]
What if wizard hats just gained the tin foil effect by default?

**Comment by MadmanMartian** [comment]
what if most helmets, like the security helmet, gave the tin foil effect?

Would make it a lot harder than just pick mindswap, steal captain, become sorcerer supreme of the station in secret

**Comment by small-boss** [comment]
> What if wizard hats just gained the tin foil effect by default?

but then beepsky would be useless against wizards

**Review by PJB3005 — APPROVED** [review]

**Comment by N3X15** [comment]
Update wiki pls

**Comment by Shadowmech88** [comment]
Wiki updated.

**Pull request merged**
