### PR TITLE
Adds the grease spell, spell aspect flags

### PR DESCRIPTION
**Pull request by MadmanMartian**
summoning forth grease (lube) either from your immediate location, or in an area in proximity to yourself

:cl:
* rscadd: Adds the grease spell, letting you create a lube-spill at will. Has congruency with fire spells, so having fireball will also make it spill welder fuel.

### CODE REVIEW

**Comment by SonixApache** [comment]
if it's not flammable, it's shit

**Comment by MadmanMartian** [comment]
That can be arranged

**Comment by MadmanMartian** [comment]
@SonixApache done. Now if you have a fire-based spell, grease causes a welder spill on top of a lube spill

**Comment by Exxion** [comment]
Congruency doesn't seem like the right word, but I'm not sure what the right word would be

**Comment by mtpowell** [comment]
Hell on earth? Couple this with a blink spell and watch the world burn

**Comment by Hugh-G-Rection** [comment]
I have been summoned 

Let the lube flow

**Comment by ShiftyRail** [comment]
You just need to combine "summon rope" for the crew to give them a quick and easy way to escape

**Comment by SonixApache** [comment]
Wouldn't it be better to split the unatomic parts of this off, for posterity?

**Comment by MadmanMartian** [comment]
Sure

**Comment by SonixApache** [comment]
>didn't split off the non-atomic parts

**Pull request merged**
