### PR TITLE
general minor improvements to castle, remove sec areas from castle departures + shuttles

### LINKED ISSUE #34627: Castle pods do not have computers
(WEB REPORT BY: luigil101 REMOTE: 206.221.180.138:7777)
# Revision
beef675b67b304c13828255def6318a93a40546c

# Description
The flight computer you emag on the pods is not present on Castle pods
# Steps to Reproduce
Play on castle, go to pods with emag in hand
# What you Expected
The ability to ensure pod babies could not escape their punishment
# What Actually Happened
Pod babies escaped alive

### PR DESCRIPTION
**Pull request by nervere**
## What this does
Fixes #34627

Fixed this:
A1bFJ1p9l7
Fixed this:
X3gkcXRREH
Fixed this:
LwJzVetT1D

Security departures area is now this (couldn't really think of what to do with it tbh, feel free to change this):
lOSDHLtGet

Security shuttle prisoner holding area is now this:
t8H9ETsExq

Pod shuttle sec area is now this (also added more instruments around the shuttle):
n0j6I1GYBk

[castle]

## Changelog

:cl:
 * bugfix: CASTLESTATION: Fixed windows, the beach, and shuttle corners.
 * bugfix: CASTLESTATION: Pods now have control computers.
 * bugfix: CASTLESTATION: Fixed the lawyer's office having the incorrect ammunition type.
 * rscadd: CASTLESTATION: Emergency shuttle brig holding area is now an ammo storage area.
 * rscadd: CASTLESTATION: Pod shuttle security area has been replaced with normal seating, vendors, amenities.
 * rscadd: CASTLESTATION: Departures prisoner holding area is now a mini-bar.

### CODE REVIEW

**Comment by nervere** [comment]
Apparently we have no Castle label.

**Comment by Blithering** [comment]
Two requests if you're editing castle:
1. the IAA office spawns with uzis, but the spare magazines are for the micro uzis, one or the other needs to change over to match up
2. as someone mentioned, the castle shuttle still has a sec section. I'd personally recommend a bar or ammunition depot to replace that

**Comment by nervere** [comment]
> Two requests if you're editing castle:
> 
> 1. the IAA office spawns with uzis, but the spare magazines are for the micro uzis, one or the other needs to change over to match up
> 2. as someone mentioned, the castle shuttle still has a sec section. I'd personally recommend a bar or ammunition depot to replace that

I have added all that you asked for and more. Check the new changelog and pictures.

**Comment by nervere** [comment]
Should be ready now, barring any further changes/fixes from others.

**Pull request merged**
