### PR TITLE
Mostly complete fixing of Advanced Camera Console

### PR DESCRIPTION
**Pull request by ghost**
Someone had to do it and all the more qualified people than me can't be bothered.

## ANALYSIS OF PROBLEMS IT HAD:
- Cameras only update when someone's watching the console. If nobody's watching, no updates are done.
- No sort of permanent camera list. When a single camera was updated it overwrote the previous list which resulted in a map with only one camera.
- The javascript had a missing parameter that resulted in literally random behavior depending on the camera's position on the map.
- The javascript, on the miracle chance that the camera's position caused it to execute the actual code it was supposed to execute, didn't fucking work.
- The javascript also produced malformed HTML.
## FIXES AND CONCERNS:
 - Fixed the javascript being stupid. No problem here.
 - Added some sanity. No problem here.
 - Fixed the zoom bar square. No problem here.
 - ~There is still no sort of permanent camera list. Updating the cameras only sends temporary updates to the people who are watching the console at the moment, but the console itself doesn't remember any of that. Because of this, I have to go through all 235 cameras and regenerate the map everytime the console is opened. I don't know HOW slow this is but it's probably slow, so I'll have to write the permanent memory system that should have been there from the start (how the fuck was this ever merged to begin with?)~
 - Fixes points 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, and 14 of #16080. Fixes like a fucking dozen random, untagged open issues about the cameras console that I won't bother looking up right now.
 - Surprisingly works with new cameras.

:cl:
 * bugfix: Fixed Advanced Cameras Console only updating cameras if someone was watching the console at the time.
 * bugfix: Fixed Advanced Cameras Console erasing all cameras on display if any of them were successfully updated thanks to someone watching the console.
 * bugfix: Fixed Advanced Cameras Console camera updating failing most of the time even with someone watching the console, which was actually good due to the bug above.
 * bugfix: Fixed Advanced Cameras Console camera updating working completely randomly based on camera position on the miracle chance that it did work AND had someone watching the console.
 * bugfix: Fixed Advanced Cameras Console camera updating giving javascript errors most of the time even if successfully updated, randomly used the right code thanks to good random position, AND had someone watching the console to enable updating in the first place.
 * bugfix: Fixed Advanced Cameras Console alarm lights being sometimes inverted even if it miraculously worked, randomly used the correct code, AND randomly didn't cause javascript errors, AND had someone watching the console.
 * bugfix: Fixed Advanced Cameras Console javascript causing malformed HTML.
 * bugfix: Fixed the zoom bar formatting in the Advanced Cameras Console and Crew Monitoring Console.
 * bugfix: Fixed wrong messages in the Advanced Cameras Console.
 * bugfix: Removed debug text in the Advanced Cameras Console.
 * bugfix: Fixed Advanced Cameras Console letting you view out of disabled cameras, mostly thanks to not updating.
 * bugfix: Fixed EMPs not disabling cameras in the Advanced Cameras Console.
 * experimental: The Advanced Cameras Console probably still has bugs left in it. Please report anything weird you see.

### CODE REVIEW

**Comment by ghost** [comment]
OK, I rewrote a good chunk of it. No lag except ~1 second totally clientside when opening the console for the first time and that's because it has to draw 280 icons.

If noone finds anything wrong here I'll continue in another PR.

**Comment by ghost** [comment]
Tested, good for review

**Comment by N3X15** [comment]
Well, it can't be any more fucked than it already is, right?

**Comment by ghost** [comment]
Thank mr eggman

**Comment by Intigracy** [comment]
:+1:

**Pull request merged**
