### PR TITLE
Faxing Tomes Fix

### PR DESCRIPTION
**Pull request by DeityLink**
Imagine being a bad enough dude to perform tweaks to spess using my work computer.

:cl:
 * tweak: You can now use the faxing function of Conjure Talisman runes to send talisman to tomes held in webbings or arcane dimensions.

### CODE REVIEW

**Comment by DamianX** [comment]
Looks like you're never removing anything from `arcane_pockets`, won't this prevent GC of the spell?

**Comment by DeityLink** [comment]
Should be fixed

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
Rather than attempting 3 times to try and find the holder, use get_holder_of_type(src, /mob)

**Comment by Blithering** [comment]
Ability to prevent shuttlecalls by faxing centcomm stun and EMP talismans when?

**Comment by DeityLink** [comment]
right

**Pull request merged**
