### PR TITLE
fixes the revsquad include so it will stop showing up in future commits as a file changed

### PR DESCRIPTION
**Pull request by Intigracy**
this file was changed automatically when I opened DM and is going to keep doing so until this is merged

### CODE REVIEW

**Comment by gbasood** [comment]
weird
any idea why it did this? I know I included it manually but fuck
Is it a line endings thing?

**Comment by Exxion** [comment]
DM sorts them alphabetically and it was in the wrong place.

**Comment by clusterfack** [comment]
Atom needs a scheme to include .dm files or not

**Comment by Intigracy** [comment]
Yeah it's just alphabetical sorting, no biggie.

**Pull request merged**
