### PR TITLE
Roidstation 2.0

### LINKED ISSUE #20709: Teleporter doesn't work
(WEB REPORT BY: somepersonsalias REMOTE: 172.93.109.202:7777)
# Revision
4eefdcef89c9f2db5d85ee83eabb9241ba5f6b74

# Description
The teleporter doesn't work, no matter the destination, setting and entering does nothing.

# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #20943: Roidstation escape external airlocks access is wrong
The easternmost airlock is supposed to have no access restriction but is restricted to security
The airlock in the middle is supposed to be restricted to security but has no restriction

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[roid]

At long last, the Roidstation 2.0 Release is here. There are a lot of changes here, but the big ones are listed below:

- Some of the less-used rooms have been hugely trimmed down. The massive, largely unused, fitness room is gone and has been merged with Dorms. The Library has been completely redone.

- The AI has relocated its Core and Upload from an off-station satellite and the Security lobby (respectively) to where the Dorms used to be. This has created a nice grotto where a host of crabs have gathered.

- The Internal Affairs Bureau has relocated its law office to the former AI Upload in the Security Lobby, to better chase ambulances as they leave Security with injured prisoners/officers.

- Auxiliary Engineering was expanded to make the Singularity a more viable option for the most daring of Engineers.

- The spiders that were wrecking up the place from their nest on the Abandoned Shuttle have been exterminated. It should be empty, but we have detected a faint 'HOO-HAH, HOO-AH' sound from the shuttle when it is approached. 

**Before:** 
http://game.ss13.moe/minimaps/images/maps/AsteroidStation/#l=150,150,1;z=0.2

Check the maprender.

**After:**

Arrivals: https://lambda.sx/PVh.PNG

Central Hall (with lunchroom, Dorms, and improvements to the Courtroom): https://lambda.sx/kROZ.PNG

Library: https://lambda.sx/ely.PNG

Security Lobby: https://lambda.sx/zxCP.PNG

AI Core, Upload, and Grotto: https://lambda.sx/3Lh.PNG

Grotto (with lighting): https://lambda.sx/tgV.PNG

Auxiliary Engineering: https://lambda.sx/zyk.PNG

Derelict AI Core: https://lambda.sx/3Bi.PNG

**Bugfixes**
Closes #20709 
Closes #20943 

:cl:
 * bugfix: All of the following changes apply to Roidstation:
 * rscadd: The AI has relocated its Core and Upload from an off-station satellite and the Security lobby (respectively) to where the Dorms used to be. This has created a nice grotto where a host of crabs have gathered.
 * rscadd: The Internal Affairs Bureau has relocated its law office to the former AI Upload in the Security Lobby, to better chase ambulances as they leave Security with injured prisoners/officers.
 * rscadd: The Dorms and Library have been relocated and renovated.
 * rscdel: The spiders that were wrecking up the place from their nest on the Abandoned Shuttle have been exterminated. It should be empty, but we have detected a faint 'HOO-HAH, HOO-AH' sound from the shuttle when it is approached. 
 * bugfix: Also a ton of broken things like mislabeled conveyor belts, doors that didn't open, and otherwise useless equipment has been replaced.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
>HOO-HAH, HOO-AH

Oh no

**Comment by Exxion** [comment]
>he doesn't know the bear strat

**Comment by SonixApache** [comment]
FUCK YOU DUNY

**Comment by Kurfursten** [comment]
Yikes.

**Comment by GeneralVeers25** [comment]
Gave the IAA some front facing windows and also fixed the Genetics APC that was sitting on the floor.

**Comment by SonixApache** [comment]
❌

**Comment by GeneralVeers25** [comment]
Found a host of missing firelocks and made the grotto all-access.

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
check the wires. There was way too many disconnected wires when I checked

**Comment by GeneralVeers25** [comment]
Reverted the change to the Vox Shuttle.

**Review by GeneralVeers25 — COMMENTED** [review]
I've ran the wire check and corrected all of the wires that are unintentionally left disconnected.

**Review by MadmanMartian — APPROVED** [review]

**Pull request merged**
