### PR TITLE
Monkey/Diona Nymphs can now use their own "blood" as cultists, and some Shade/Constructs buffs

### LINKED ISSUE #20811: Various Cult bugs as Diona Nymph, and with Soul Gems
(WEB REPORT BY: jackmassacre REMOTE: 172.93.109.202:7777)
# Revision
f410ab446bf2d295613bf4d99d4123834e1b7f0b

# Description

As Diona Nymph, cult converted me, succeeded, but did not receive cult spells, and was unable to use tome to do anything "you don't have the dexterity to do this" when clicking on a rune name. Could still activate existing runes on ground, though.

After realizing uselessness, asked to be killed and put into soul gem to create artificer. Once I was punched to crit as diona nymph, heard successful soul shard/gem sound, but did not actually get absorbed, then healed from crit and saw the cultist use the soul gem (filled with nothing) on a construct shell, creating a blank Artificer controlled by no one.

Tried a few more times with similar results, then finally succumbed while crit, and ghosting failed to prompt for turning into a shade like other cultists can. Additionally, ghosting made my corpse vanish, and re-entering corpse made it re-appear on the ground.

Admin had to force my soul into the brainless artificer, and then had to manually set me to cult faction due to the artificer having no faction.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #20811

monkey_cultalien_cult

This doesn't really count as part of Cult 4, and more as stuff from Cult 3 that I should have fixed years ago.

:cl:
* rscadd: Monkeys, Diona Nymphs, and other primitive carbons are now able to use their health as blood when performing cult rituals, without the need to acquire a syringe and a beaker. Each unit of blood taken translates to 1 oxy damage, which is negligible as long as small amounts are used, but can quickly kill you if if the ritual requires a lot of blood at once (such as resurrect).
* rscadd: Aliens can use their blood as cultists as well by popular request. They cannot hold tomes though so writing full runes require a bit of effort. They take brute damage instead of oxy when writing runes but it's not like it matters since they heal all damage types over time by just standing over weeds.
* rscadd: As a human cultist, you can now just grab a monkey just like you can grab a human to use their blood. Note that dead monkeys don't provide any more blood. Yes that means you can give them some Dexalin Plus to keep them as free blood dispensers, but then again so could you all this time when using a syringe and beaker.
* tweak: Also monkeys now stop wandering around when grabbed with Grab Intent, just like when they're being pulled.
* tweak: Constructs could already use runes that don't require a blood cost, however this limitation has been removed, giving constructs new purpose as a catalyst for low-cost rune rituals, as constructs can now pay the blood cost without having to actually produce any blood. Does this mean rune-drawing constructs down the line? I don't know. Not for now anyway (and not later without some limitations, Pale Bodies using stun runes is enough of a source of frustration already) We'll see how this goes first.
* tweak: Shades can also use runes from now on, but only ones that don't have a blood cost (unless they find a splatter or bleeding corpse). As a side effect, so can Cult Blades, that can now fly through Path Runes.

### CODE REVIEW

**Comment by juanototo2** [comment]
>xenomorph cultist
jesus christ how horrifying
Also, in the case of a conflict between Queen orders and cult orders, who wins? And if the Queen gets converted, does the
entire hive become gult for the purposes of team antag rules as well?

**Comment by DeityLink** [comment]
@juanototo2 
Xenomorphs technically aren't a faction code-wise, there are no messages that tell new alien players to obey their queen, so if a queen becomes cultist it's up to their brood to decide individually whether they want to be converted or not as normal.

Since they aren't a proper faction, xenomorphs can also attack each other without admin repercussions whether one of them is a cultist or none of them are.

A cultist xenomorph cannot attack other cultists however, which then includes other cultist xenomorphs.

There is no such thing as "cult orders" though. Each cultist decides individually how to best further the cult's agenda, as long as it doesn't prevent the rest of the cult from completing the cult's objectives.

**Comment by gurfan** [comment]
I don't think xenomorphs can attack eachother regardless, it won't do any damage

**Comment by DeityLink** [comment]
No, they can attack each others, they just gotta switch to harm intent first.

image

**Comment by Blithering** [comment]
With enough ingenuity, this means a cult can make a comeback from the dreaded "everyone's a shade or construct, no-one has hands" scenario.

**Comment by DeityLink** [comment]
if a construct or shade manages to stun and convert a human without killing them, they deserve their comeback.

**Comment by Blithering** [comment]
so long as the cultists left behind stun and conversion runes, anything is possible.

**Comment by jknpj** [comment]
you forgot martians

**Comment by DeityLink** [comment]
@jknpj Unlike monkeys you cannot draw blood from martians with a syringe (you get the "unable to locate any blood message") and unlike xenomorphs they don't have custom gibs/blood properly set up. (in fact they can only be gibbed by explosions, and produce red gibs, even though their blood seems to be green like xenomorphs in Metal Slug)

So I'll feel more inclined to let martians draw runes once they have proper species values set up and can bleed.

**Comment by Dacendeth** [comment]
Nymphs shouldn't have blood should they, since their adult form doesn't?

**Comment by DeityLink** [comment]
@Dacendeth they shouldn't but they've always had, and changing that is beyond the scope of this PR.

**Comment by jknpj** [comment]
I strongly feel the cultist bias behind that statement, but fair enough.

**Pull request merged**
