### PR TITLE
Unknown upload detected. 

### PR DESCRIPTION
**Pull request by AgentOrangeLaughingGas**
It was you who broke my mason plate.

images

:cl:
 * rscadd: Laugh and Grow Fat

### CODE REVIEW

**Comment by ghost** [comment]
what kind of memetic kill agent is the foundation trying to show me now

**Comment by WindowsErrors** [comment]
BerLine station

**Comment by Kurfursten** [comment]
Instant merge code 443 accepted
Resetting code

**Comment by adacovsk** [comment]
cursed

**Comment by Eneocho** [comment]
> BerLine station eneocho, I think Operation Spessmart Steal trained us for this one

It will be done.

**Comment by Eneocho** [comment]
Though I gotta say that cutting line vertically instead of the logical horizontal line was the biggest blunder of the century.

**Comment by WindowsErrors** [comment]
from what I've been told it was all going swimmingly until people realized that the East side held all the power (literally)

just like real life now that I think about it

**Comment by Eneocho** [comment]
I found at least 3 locations to bypass the walls.
I told ya, it should've been divided in north and south instead. North controls kitchen, hydroponics, medical, cargo and mechanics. South controls sec, science, command and engineering. Sure, the south might be more technologically advanced, but the north controls the main medical facilities and access to nigh-limitless resources via cargo. That would've been far better in my opinion.

**Comment by WindowsErrors** [comment]
I think the concept involved having as short a border as possible so that there would be as few entry points for the admins to bother keeping for border jumpers, which ended with this map cleaving the chapel in half and completely cutting off telecoms in the name of convenience

and lemme guess, your three were... 

took a trip to the roid and used the other side's shuttle
literally just used the teleporter that was in the middle of arrivals on the west side
just went through the bombed out checkpoint that the ~terrorist~ Freedom Fighter cargo workers/assistants cleared out

**Comment by Eneocho** [comment]
There were regular walls to space connecting the chapel to the unused shop, just unweld those walls, make a simple path and boom. 3 tiles to bypass the separation, and right under the checkpoint's noses.
Same deal but across former AI space, a bit longer and more dangerous route.
Just hack and bust open the sec checkpoint airlocks and rush through.
And another one I'm forgetting right now.

**Pull request merged**
