### PR TITLE
New Wizard Spell: Summon Snacks / Diabeetusol Rework

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Adds the summon snacks spell. A single target spell similar to shoe snatching charm. This one's my favorite.

### Summon Snacks

**Cost: 20, requires robes, 30 second cooldown**
Forces a snack and drink into the target's hands. The wizard can target himself. If the target is holding anything at the time they drop them to hold the delicious munchies. The munchies can't be dropped, they can only be eaten or fed to someone else.

**Upgrades:**

**Speed, 10 per level, max 3**
Minimum cooldown is 15 seconds

**Amount, 1 per level, max 5**
Reduces how much of the snack you can eat per bite by 1u of chem per level, effectively increases how long it takes you to eat the food without increasing how many chems are inside.

**Power, 25 per level, max 1**
Adds 1u of diabeetusol to both the snack and drink. See that section for why this costs so much and should cost more.

**Move, 0 per level, max 4 (sort of)**
Move changes what's on the menu. They each have different chems in them but are only mildly different. Levels 0-3 are menus, getting it to level 4 resets it to 0 so you can cycle through them. I like the Dan one.
89968749-aac11200-dc22-11ea-83f0-01f3f540861b

### Diabeetusol

I originally made this as a hasty finish to the gingerbread vault and always hated how it turned out. It was made to only match the weapons found in the vault.
Since it was the perfect thing to match the theme here I've reworked it to match the intended concept much better and be generally more fun/flexible.

Diabeetusol metabolizes very slowly, has an extremely high nutrition value, and functions differently depending on how much sugar you have in your system. If you have less sugar than diabeetusol then you'll become confused, dizzy, your vision will blur, and now and then you'll pass out for a second. If you have more sugar then you'll rapidly gain weight. Once you're past a certain amount of nutrition your heart explodes. Also it makes you play tuba sounds which makes me smile.

**If anyone has suggestions for more "menus" please throw them at me. They're really easy to slap in there and I think it's a fun mechanic.**

🆑

rscadd: New Wizard Spell: Summon Snacks
tweak: Diabeetusol V2: Full Fat

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
Took me longer to "fix" the conflicts than it did to actually make this.

I'm going to keep tinkering with diabeetusol while this is being reviewed. I plan on adding something related to it as a chef traitor item so I want it just right.

**Comment by GreatBigFailure** [comment]
**Added two new menus: patrol and spicy.** 
Patrol gives people a donut and coffee, perfect for the shotgun secoff you've been running from all shift. It'll heal them a bit and fatten then up a little faster too. Oh and it also has 2u of sugar per snack but who cares right? Not like that specific amount of sugar would interact with some kind of power upgrade. 
Spicy has a bit of a kick to it. 2u of capsaicin specifically. 

**lean diabeetusol tweak**
The sugar effect now scales with how much diabeetusol you have in you rather than just being a flat fatness increase.

**Menu chems**
Tinkered with them slightly. Evened out their usefulness and made "filling" not the obvious best option for causing obese hysteria.

**Comment by Theophrastus1** [comment]
DR'NKN D'WF should give you a beer and a kebab

**Comment by GreatBigFailure** [comment]
I was in the middle of adding that actually. I just can't figure out what chems to put in it since there's already the pub fare one.

**Comment by Theophrastus1** [comment]
Well in that quest from where it is taken, it's mentioned that you hallucinate pink elephants and are incredibly drunk so maybe a dense alcohol in the beer and mindbreaker in the kebab?

**Comment by GreatBigFailure** [comment]
Mind breaker is too powerful, they're meant to all be basically the same with very minor differences. Like level 0 "amount" the "filling" menu takes 1 more bite. The sec one is specifically good at getting sec fat and does synergize veeery slightly better with diabeetusol but only for a second. 
Gonna add space drugs though, was looking for a place to put those thanks.

**Comment by GreatBigFailure** [comment]
Drunk dwarf menu added. I decided on 8u beer 2u tricord. Mimics the Runescape equivalent and has a niche that's different from the pub one. It'll require the most bites to eat but doesn't give much nutrition, so it won't fill people up. It will however get them drunk. The wiz can also use it as a very, very shitty self heal at the cost of him getting drunk.

**Pull request merged**
