### PR TITLE
Revert "Fixes #10005 This time with a Vengeance" This time with a Vengeance

### LINKED ISSUE #10005: Project Mind can be used to metagame someone's real identity
If someone masks their identity by any means, such as using someone else's ID and a mask, an agent ID, whatever have you, things get tricky and meta-ey.
Their FAKE name is displayed in the list of people you can project mind to (i.e. "Don Newman"). Up until you send the message, they are always displayed using their FAKE name.
dreamseeker_2016-05-10_16-44-47

However, the chatbox message you get afterwards uses their REAL name.
dreamseeker_2016-05-10_16-45-34

Someone using a voice changer to impersonate someone else? Let me whip out my project mind real quick so I can instantly confirm there are 2 identical names on the list. Sure there are, let me call them a faggot real quick. Oh that's who they really are.

### PR DESCRIPTION
**Pull request by carshalash**
Give it some kind of benefit instead of just being literal fucking trash, PDA's at least let you know if the person you're trying to message is there or not. You went way too fucking hard on this, greys are already just kind of a meh race as compared to the others.

### CODE REVIEW

**Comment by chatsonf** [comment]
So what does this actually do with #10005? Just ignore the fact that it is a bug?

**Comment by carshalash** [comment]
I just want fucking angelites change because it was actually workable and still removed the bug instead of just fucking up a everything

**Comment by chatsonf** [comment]
Did you even code angelite's change? If you want angelite's change then actually code it.

**Comment by TheFriggenSawbones** [comment]
angelite coded it didn't they

I think zach has a point. Maybe even figure out a way to make nuke ops and wizards exempt from the list who knows

**Comment by ghost** [comment]
> PDA's at least let you know if the person you're trying to message is there or not.

They don't tell you if they're alive or not, though.

**Comment by chatsonf** [comment]
If she coded it then WHY ISN'T IT IN THE PR

At this current point all that is going to happen is that you are going to get laughed at for suggesting to "revert a bugfix" without having the alternative bugfix included in your code.

**Comment by carshalash** [comment]
Just reopen #10013 . As it is now the power is just a really worse version of a pda, at the very least PDA's let you hit up anyone instead of needing to play pokemon snap and shift click people and give you the whole "your message could not be sent" if someone is off z levels or their pda is fucked.

And the suggestion for that was giving them both the unable to be mindpowered trait. I don't get why the server is in a frenzy about fucking race balances, half of them are from people complaining about "x player is being mean to me with their benefit."

**Comment by ghost** [comment]
If you have a better fix, code it. Reverting a bugfix isn't likely to get merged.

**Comment by carshalash** [comment]
Just remove greys then if you're going to call you adding in a bunch of extra shit a bug fix.

**Comment by chatsonf** [comment]
Jesus christ carsh this is just sad. You put no effort demanding that things get reverted then cry when people tell you to put in effort. 

:sob::sob::sob::sob::sob::sob:

**Comment by TheFriggenSawbones** [comment]
planes and hypothermia fixed when

**Comment by ghost** [comment]
Planes tomorrow hypothermia when you bug report any issues with it.

**Comment by TheFriggenSawbones** [comment]
ok thank you celt

**Pull request closed without merging**
