### PR TITLE
Adds four new recipes

### PR DESCRIPTION
**Pull request by Arthurdentist**
Adds four curries,

Chicken Balti
chicken balti

Chicken Vindaloo
vindaloo

Lemon Curry
lemon curry

Xeno Curry
xeno curry

Might be more to come depending on people's thoughts. 

Also adds Pepper and Salt shakers to the kitchen vendors so its harder to run out.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Be sure to add these to the wiki when it's merged.

**Comment by d3athrow** [comment]
Curry head please leaf

**Comment by IratePirate** [comment]
No Tikka Masala?

**Comment by Arthurdentist** [comment]
Eventually Irate

**Pull request merged**
