### PR TITLE
Revert "Adds *scream and *vent to Cyborg's emotes"

### PR DESCRIPTION
**Pull request by 9600bauds**
Reverts  #13213
Goodness fuck, why was this merged? The vote against it won significantly.

What is being reverted here:
http://vocaroo.com/i/s0ay0SnY6oLR
firefox_2017-01-12_21-34-14
farting marina secborg which literally injects fart chemicals (this parody of itself is in the game right now)

:cl:
rscdel: Removed *scream and *vent from Cyborgs

### CODE REVIEW

**Comment by ghost** [comment]
i like *scream but *vent should go

**Comment by Probe1** [comment]
Sorry I misread the emojidemocracy and thought it was ahead.

**Comment by Probe1** [comment]
Also I had no idea people cared this much and I have no idea _why_ people care this much about farting.

**Comment by SkowronX** [comment]
gg

**Comment by 9600bauds** [comment]
pacman being eaten by ghosts

**Comment by Probe1** [comment]
TIME TO GET YELLED AT FOR REVERTING IT TOO

**Comment by SangriaMonkey** [comment]
Someone should make a better scream that doesn't last for twelve seconds or contain funny frog jokes.

**Pull request merged**
