### PR TITLE
Defficiency updates are back baby

### PR DESCRIPTION
**Pull request by Duny-**
- Added a borer egg and a plasma canister to xenobiology. Two portable air scrubbers have also been added in xenobiology maintenance.  (Closes https://github.com/d3athrow/vgstation13/issues/7177)
- Fixed glass doors on the derelict not being dense. (Closes https://github.com/d3athrow/vgstation13/issues/7349)
- Fixed solar APCs not charging. (Closes https://github.com/d3athrow/vgstation13/issues/7351)
- Added a coin press to the asteroid. (Closes https://github.com/d3athrow/vgstation13/issues/7361)
- Modified the morgue's layout, more trays and less empty space. (Closes https://github.com/d3athrow/vgstation13/issues/7380)
ss 2016-01-03 at 02 39 06
- Fixed up a bit the walls and rwalls around science to be more nanotrasen-approved. (same issue as above)
- Added a light switch to hydrophonics. (https://github.com/d3athrow/vgstation13/issues/7394 no longer concerns Deff)
- Fixed Mechanics Workshop vent not being connected to anything. (Closes https://github.com/d3athrow/vgstation13/issues/7404)
- Added a few additional lights in science to make the hallway less spooky when one breaks. (Closes https://github.com/d3athrow/vgstation13/issues/7424)
- Attached the floating camera in xenobio to the wall. (Closes https://github.com/d3athrow/vgstation13/issues/7426)
- Added two cyborg analyzers to robotics. (https://github.com/d3athrow/vgstation13/issues/7435 no longer concerns Deff)
- Added plant clippers in xenobotany. (https://github.com/d3athrow/vgstation13/issues/7243 no longer concerns Deff)
- Added compressed matter cartridges in the bar storage, and replaced the shotgun with a double-barreled model. (https://github.com/d3athrow/vgstation13/issues/7163 no longer concerns Deff)

- Tweaked the starting charge of the engineering SMES cells again. (https://github.com/d3athrow/vgstation13/issues/6562)

### CODE REVIEW

**Comment by PJB3005** [comment]
:+1:

**Comment by DrCelt** [comment]
does this fix #7441 ?

**Comment by Duny-** [comment]
Are paramedics deleted yet?

**Comment by DrCelt** [comment]
they should be

**Comment by IratePirate** [comment]
When my Tort exam is over on the 8th i'll get back to helping patch up Meta and maybe even playing SS13 if I feel I can stomach it. Good to see you back on Deff Duny.

**Comment by Arthurdentist** [comment]
Tort is fucking boring.

All the best to you

**Comment by 9600bauds** [comment]
Don't those morgue trays still block the door?

**Comment by Duny-** [comment]
Good luck @IratePirate 
@9600bauds I don't see anything blocking any door fam

**Comment by 9600bauds** [comment]
The morgue trays open outwards fam

**Comment by Duny-** [comment]
Right. Well. Just close it to go though if someone for some reason left it open.

**Comment by clusterfack** [comment]
FUCK YOU DUNY

**Pull request merged**
