### PR TITLE
Removes z7 from meta

### LINKED ISSUE #5553: (WEB REPORT BY: kammerjunk REMOTE: 198.245.63.50:7777) Meta Club z-level 7
>Revision (Should be above if you're viewing this from ingame!)
Meta Club z-level 7

>General description of the issue
z-level 7 inescapable without admin intervention.

>What you expected to happen
The ability to leave z-level 7

>What actually happened
Hit a black wall of nothing

>Steps to reproduce if possible
Go to z-level 7, fly to the edge.

### PR DESCRIPTION
**Pull request by Intigracy**
Code doesn't support 7 z levels
fixes #5553

### CODE REVIEW

**Comment by Unfit** [comment]
>+12,741 -13,003

**Comment by clusterfack** [comment]
We can fix it so it lets you have 7 zlevels pretty easily

**Comment by Intigracy** [comment]
But wouldn't that require every map to have 7?

Also the z level is legitimately just empty space, z6 serves the same purpose sans the spider shuttle.

**Comment by clusterfack** [comment]
No, the only thing broken is the turf/space/entered check which is hardcoded to 6

**Comment by ComicIronic** [comment]
> turf/space/entered check which is hardcoded to 6

TERRIBLE
Why?

**Comment by clusterfack** [comment]
Someone thought that should be the max zlevel length, FOREVER apparently

**Comment by ComicIronic** [comment]
Then it should just be possible to use current_map.zLevels.len, or whatever the var is called.

**Comment by clusterfack** [comment]
Yeah thats the one

**Comment by Intigracy** [comment]
idk, but meta is pretty unplayable for the people who get stuck currently.

**Comment by IratePirate** [comment]
I always thought that extra empty space z-level seemed a bit odd.

**Comment by Intigracy** [comment]
Pomf already did it.

**Pull request closed without merging**
