### PR TITLE
Refactors docking ports

### PR DESCRIPTION
**Pull request by Probe1**
> {Clusterfack} convert docking ports to /obj
> {Clusterfack} they have some fucked up code because they inherit from structures for no reason

Changes path from `/obj/structure/docking_port` to `/obj/docking_port` .

### CODE REVIEW

**Comment by Probe1** [comment]
Tested on Box:
- Salvage Shuttle against arrivals docking
- Skipjack against Vox Tradepost
- Skipjack against North east solars
- Nuke ship against south of the Communications Satelite
- Centcomm Ferry against station arrivals (docking port 1)

Dream Bae-mon didn't kick any runtimes.  Seems like an easy refactor.  Unless somewhere in those 400 uses there's a really, really special snowflake.

**Comment by PJB3005** [comment]
Doubt anything other than compile errors could result from this anyways.

**Comment by Probe1** [comment]
Tag it as mapping with every map label we got while you're here.  This diddles the whole repo.

**Comment by unid15** [comment]
What issues did they cause because of inheritance from /obj/structure? Just wondering

**Comment by Probe1** [comment]
`¯\_(ツ)_/¯` I think they could be eaten by Narsie?

**Comment by clusterfack** [comment]
A few procs that inherited about destroying docking ports by certain actions (such as blobs)

**Comment by FudgePucker** [comment]
Can you drag it?

**Pull request merged**
