### PR TITLE
Bring all square roots in the sqrtTable to one decimal place

### PR DESCRIPTION
**Pull request by ghost**
This is purely experimental, all square roots in the sqrtTable are now defined with one decimal (and rounded properly too). This will have a significant effect on any equation that uses square roots ingame, and should hopefully have minimal processing cost

There doesn't seem to be any serious problems when running with this code, but no benchmarks were done

Changelog included

### CODE REVIEW

**Comment by PJB3005** [comment]
>This will have a significant effect on any equation that uses square roots ingame

It's referenced twice: DAL.

Which i'm getting rid of.

Honk.

Anything else just uses sqrt().

**Comment by dylanstrategie** [comment]
Well then. This can still be used for speedy square root calculus, but if sqrt() works there's literally no reason

**Comment by ComicIronic** [comment]
I'm not feeling the need to merge this, since it's about to disappear from code usage (and was generally bad anyways)

**Comment by mwerezak** [comment]
Just hearsay but I remember someone mentioning in #codershuttle that Mloc found sqrt() was actually faster than the list lookup. Not 100% sure though.

**Comment by ComicIronic** [comment]
I want to call RIP on this PR and the table in general.

**Pull request closed without merging**
