### PR TITLE
Revert "Make the blast cannon a bit better"

### PR DESCRIPTION
**Pull request by Kurfursten**
Reverts vgstation-coders/vgstation13#25800

As I promised, this merge was experimental and we will now vote to see if it ruined everything.

🆑 
* rscdel: Reverted improvements to the blast cannon.

### CODE REVIEW

**Comment by Gazathor** [comment]
Obligatory first honk

**Comment by tuypo1** [comment]
Did anybody even use it for us to have data to work from?

**Comment by yackemflam** [comment]
nope

**Comment by 9percents** [comment]
it needs more time to be tested and used, give it a month

**Comment by Kammerjunk** [comment]
the original PR was never actually argued for
it was merged with 17 memes up and 18 memes down
after the PR had been up for about 3 weeks, it was changed from a 1.5x multiplier to a 2x multiplier (up from 1x)
it was merged 17 hours after that change
one of the downboats here is Yackem himself

**Comment by yackemflam** [comment]
no one has tested to see if it ruined everything in the server yet, that's why I'm downvoting

**Comment by ghost** [comment]
This is such a dumb change to get worked up over and I have a sneaking suspicion most of the controversey is people reactionary voting because of Yackem's dudebomb reputation.

The last minute buff being merged is kind of shit but otherwise who the fuck cares about the blast cannon being made better? Opening the TTV bomb necessary to use the cannon still does way more damage.

**Comment by yackemflam** [comment]
its really a shame that people judge a pr by who made it instead of its merit

**Comment by Kammerjunk** [comment]
if this was an attack on Yackem, I wouldn't at all have mentioned the merge speed

**Comment by yackemflam** [comment]
But you did mention that I downvoted

**Comment by Kammerjunk** [comment]
well yeah because it's about your PR

**Comment by yackemflam** [comment]
But this pr' isn't my PR, is it?

**Comment by Kammerjunk** [comment]
no but it's a "service PR" about your PR

**Comment by 9percents** [comment]
alright, I saw the blast cannon
it works like an explosive railgun, I dislike it, give me an explosive tube back

**Pull request merged**
