### PR TITLE
Box teleporter shutters

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds shutter doors to the doorway between the captains office and the teleporter on box station, requested by Bomber Harris#5927 on discord.
image

Imperial Factory Zeta 2019-09-19 020440

:cl:
 * tweak: Box station now has a set of shutter doors between the captains office and the teleporter room

### CODE REVIEW

**Comment by BomberBro** [comment]
Wanted this as an alternative to locking the spare away or enforcing captainship on somebody. This way heads of staff can get the spare in a reasonable amount of time without a mechanic sneaking through the teleporter and on dead pop hard-working, honest joe's can still walk into the cap's office and set up the engines for the next three hours of bar rp. It's still very possible to rush, this really only cucks mechanics, but if the roid spare remap is anything to go by forcing slightly more effort into it will stop most in their tracks.

**Comment by Lokiamis** [comment]
Wouldn't it make more sense to put the shutter at the entrance to the teleporter room so those with access can allow public teleportation? It's goofy to have a shutter for a maintenance tunnel.

**Comment by BomberBro** [comment]
It was supposed to be a blast door originally but putting shutters at the front of the teleporter would work too

**Comment by tuypo1** [comment]
I got excited when I saw this because I thought it was gonna be on the other door to allow access to the teleporter to be open
Spare rushing is an ic issue that can be solved by consistently executing for it

**Comment by incakola** [comment]
I have this comment also present in #24175 

Why not something more novel like #23903 to deter/slow thieves.
It's easy to hack a door and then very easy to hack the other doors once you know the wire.
If at least the 3 doors are randomized on Box (Teleporter, Teleporter-Maint, Captain'sQuarters-Maint), then it should take 3 times as long to hack in.
But then don't randomize all the doors on the station, just sensitive doors like command and armory.

**Comment by Intigracy** [comment]
because that PR got 40 downvotes so will never be attempted again

**Comment by Probe1** [comment]
I'm sorry to be firm about this but this is not a good solution.

image


Why are these three tiles soft?  They were made that way intentionally so people could rush the spare.  This is a gunky solution to a problem.  Spare rushing remains just as viable on other maps despite this change so we're looking at very narrow solution.

Consider alternatives like say, putting it in a secure container like the captains laser or something much more novel and improved.  As stands this is a very organic design for the map but a bandaid solution to the problem that will be overcome and leave us where we currently are.

**Comment by Probe1** [comment]
ALTERNATIVE SUGGESTION:  There is a wall mounted safe right there in the room already.  No one uses these things.  Put the spare in it so players have one more minor roadblock on the path to sweet momma access.

**Comment by MadmanMartian** [comment]
There is a PR up for just that, #24175

**Comment by tuypo1** [comment]
That pr makes the safe way harder to crack
Too hard even

**Comment by d3athrow** [comment]
now people will just use disposals to get into the captains room.

**Comment by Probe1** [comment]
I'd like to repeat that I find this solution extremely inelegant and reactionary.

**Pull request merged**
