### PR TITLE
Librarian Traitor Item: E20

### PR DESCRIPTION
**Pull request by clusterfack**
Adds the E20, a librarian traitor item

Stats
Cost: 3 TC (lowered from 5)
Looks: Like a standard D20 dice
Effect: Creates an explosion of range X, where X/4 is the explosion devastation, X/2 is the heavy radius, and X is the light radius. X is the number you roll on the dice.
5% chance to roll a 1 which gibs the player
5% chance to roll a 20 which upgrades the explosion somewhat and ignores the bombcap

### CODE REVIEW

**Comment by Riukanojutsu** [comment]
5 TC sounds like a lot

**Comment by Iamgoofball** [comment]
1 tc imo

**Comment by clusterfack** [comment]
Its open for discussion, its everybodies code after al

**Comment by NigglyWiggly** [comment]
Seems a bit expensive, considering the chance aspect of it, but seems really nice otherwise!
That said, does it create the explosion right away, or do you roll it to prime it, and then toss it somewhere like a grenade?

**Comment by clusterfack** [comment]
It explodes after what should be about 4 seconds, also it actives the same way you roll a normal dice. So either you roll it in your hand and throw it or just throw it.

**Comment by clusterfack** [comment]
Merge branch, git please

**Comment by Probe1** [comment]
that's a fucking fantastic idea.

**Comment by Arthurdentist** [comment]
Is this one use only, IE does the explosion gib the dice itself or can you pick it up and throw it again? If you can only use it once this should be cheaper.

**Comment by Shaska-** [comment]
For an item that has a 5% chance of gibbing you, I'd say make it no more than 2 TC. Alternatively, rather than gibbing them, make a critical failure blow off your hand instead.

**Comment by SarahJohnson489** [comment]
I like Shaska's idea of it blowing off a hand.

**Comment by Duny-** [comment]
Critical failure seems too harsh for the cost I agree, I like the item though.

**Pull request merged**
