### PR TITLE
Gendered pronouns will now affect emotes for non-human mobs too

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
## What this does
Allows the system to actually work for mobs that aren't human, meaning that gendered mobs such as monkeys will now show emotes such as "cracks his knuckles" or "cracks her knuckles" too.
## Why it's good
This also fixes a bug where surrendering monkeys would show with "they surrender%s!" at the end

## How it was tested
Emoted as a monkey.
## Changelog
:cl:
 * bugfix: Emotes that change their wording based on the user's gender will now properly affect non-humans such as monkeys.

### CODE REVIEW

**Comment by Eneocho** [comment]
does this also work with simplemobs such as ian (male), lisa (female), salem (male)? given that they're named i'm inclined to believe they'd use gendered pronouns rather than it/they, it's no longer a random dog, it's Ian
sasha, poly (it'd be a female name if named polly), and runtime are too ambiguous to tell
how about other simplemobs like chickens, cows or goats? them giving eggs/milk implies them being female (the polyp is ayylien enough to be ambiguous despite giving jelly)

**Comment by boy2mantwicethefam** [comment]
It should take their genders into account now, yes. It's no longer a human-only check, but a mob check.

**Comment by Eneocho** [comment]
I'm pretty sure that none of the aforementioned mobs have their gender defined, so it'd still say "they".

**Comment by west3436** [comment]
gonfligdd :DDDD

**Pull request merged**
