### PR TITLE
initiating a vote while in-game no longer uses your in character name to say who made the vote

### PR DESCRIPTION
**Pull request by nervere**
## Why it's good
You're calling the vote, not your character. You don't play a self-insert... right anon?

## Changelog

:cl:
 * bugfix: Initiating a vote while in-game no longer uses your in character name. Your ckey is used instead.

### CODE REVIEW

**Comment by Eneocho** [comment]
`*coughs in valerie/valkyrie skies*`

**Comment by Theophrastus1** [comment]
>grudgecoding cause i called you kiera gayze for initiating a vote

yeah i'm thinking owned

**Comment by anaxosa** [comment]
kiera gayze lol

**Comment by Inorien** [comment]
kiera gayze

**Comment by Eneocho** [comment]
lmao kiera gayze

**Pull request merged**
