### PR TITLE
Packedstation Roundup

### LINKED ISSUE #17722: Scrubbers and Vents are on Three Different Frequencies on the Vox Outpost
#### Description of issue
The Vox outpost has its scrubbers/vents on three different frequencies. Some are even on different frequencies inside of the same zone.

#### Difference between expected and actual behavior
I suppose this could be what the mappers intended, but I would assume they would all be on the same frequencie. 

#### Steps to reproduce 
Teleport to the Vox outpost
Examine the vars for the vents, or use a multi tool on them. 

#### Length of time in which bug has been known to occur
Unknown

#### Server revision
Current

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x
voxcpox
 ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### LINKED ISSUE #17908: Packed issues
1.  Not enough ATMs/poor distribution
2.  Maps in arrivals.
3.  Mining shuttle shit can be done better.
4.  Path to the secret powergamer high yield areas requires a lot of tedious mining
5.  No crates around the mining smelter.

### LINKED ISSUE #18133: There is no blue toolbox on Packed's bridge.
There is one in each and every bridge. Consistency.

### LINKED ISSUE #18308: Packed engineering access
(WEB REPORT BY: majesticmastodon REMOTE: 172.93.109.202:7777)
# Revision
bfdda846636eac7dba837336b393963cfdcc3940

# Description
Mechanic doesn't have engineering access on Packed

# Steps to Reproduce
Just be a mechanic on packed and go to engineering
# What you Expected
For the doors to open so I can take glubbs and singuloose
# What Actually Happened
The doors didn't open

### LINKED ISSUE #18490: Trader shuttle blocks the way for spacepod in Packedstation
Title, if the trader shuttle is docked at the station you can't get to space via space pods, but it may be a feature(?)

### LINKED ISSUE #18677: Packed Surgery Lights
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
4c173ecd5d224315d62e0a49024266c31ac7ae99

There's a switch for the holosign in packedstation's surgery, but no switch for the actual lights

The switch for the rest of medical doesn't turn surgery lights off either so you can't use that

### LINKED ISSUE #18678: Packed Virology Airlock
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
4c173ecd5d224315d62e0a49024266c31ac7ae99

The airlock area in packed station's virology has no vent nor scrubber, meaning it just slowly runs out of pressure and regularly gets locked down by the atmos thing

### LINKED ISSUE #18750: packed xenobotany underequipped
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
department starts without a hatchet(important) which I believe to be an oversight while mapping

### LINKED ISSUE #18828: Packed Station lacks a coin mint.
(WEB REPORT BY: smedley8 REMOTE: 172.93.109.202:7777)
# Revision
aa6ebdcaa9f0313e4de958207d401828cf540c5d

# Description

No coin mint on the packed station Asteroid.

# Steps to Reproduce

Dude just go to the asteroid on packed lmao.

# What you Expected

A coin mint.

# What Actually Happened

A compressed mining/research outpost that lacked a coin mint.

### LINKED ISSUE #18836: Packed: Most Rooms Have No Sound System
Only the dorms and possibly engineering equipment room have one

### LINKED ISSUE #18945: Packed firelock and/or vent placement
Basically a bunch of firelocks create sub areas in rooms that don't have vents or scrubbers, meaning they're more difficult to repressurize and cause extra fun for the single cell organisms posing as engineers

I drew little red squiggles over the areas I could find, but there might be more

In the first one you can't see the firelocks blocking the doors left and right of the PA because of the shutters but they're there and they're painful

scrnshot8

scrnshot1

scrnshot3

scrnshot4

scrnshot5

scrnshot6

scrnshot11

This medical one is obviously the most notable of them, honestly I'd just remove all the firelocks poking out right at the T junction. Also why is there a directional firelock on the outside of a single maint door???

scrnshot2

In other firelock related grievances, tool storage and tech storage (seen here in blue) both use full tile firelocks for some reason, and secure tech storage (in purple) has only an airlock with no firelock despite having its own pump and vent

scrnshot7

Finally there's like two full tile firelocks on the asteroid, one for the toxins room and one for xenobio, and the rest is all just bare airlocks with no firelocks at all

### LINKED ISSUE #19079: Packed outpost atmos air miner starts off
(WEB REPORT BY: meetmeindorms REMOTE: 172.93.109.202:7777)
# Revision
85f13d5104fc96d211be55e86ee347b682b276de

# Description
The packed outpost atmos air miner starts off.

# Steps to Reproduce
>play on packed
>go to outpost

# What you Expected
For it to be on.

# What Actually Happened
It was off.

### LINKED ISSUE #19086: Packed does not have nearly enough holopads.
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
b122addbc8ed9294c5e8c9b99b7d1e1bb2a774a8

# Description
They're missing in like, everywhere. Telescience, for one.

### PR DESCRIPTION
**Pull request by Kurfursten**
* Removed firelocks near HOP line, the bridge, science, arrivals, dorms, the brig entrance, singularity, engineering, mining dock, and many from medbay
* Improved the atmos lines so that you don't need to destroy distro to fill oxygen/nitrogen cans
* Added a vent to the mining dock and virology
* Added a coin mint line
* Added a hatchet to outpost botany
* Turned on the outpost air miner
* Added many holopads
* Added a lightswitch to surgery
* Added toolbox to bridge and boxes to cargo
* Engineering foyer now uses access 11 (engine_equip)
* Added crates near smelter at outpost
* Added a powergamer shortcut to the high yield minerals by skirting the north of the Voxpost
* Added many sound systems
* Moved final recycling down

closes #17722
closes #18490
closes #18836
closes #18828
closes #18750
closes #18678
closes #18945
closes #19079
closes #19086
closes #18677 
closes #17908
closes #18133
closes #18308

🆑 
* bugfix: Many longstanding Packstation bugs were fixed, most notably the deletion of many annoying firelocks and a slight relocation of disposals south (to accommodate the pod bay)

### CODE REVIEW

**Comment by SonixApache** [comment]
thank god

**Comment by ShiftyRail** [comment]
The firelock nation attacked
Thanks for the PR

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Thank you

**Comment by Riekland** [comment]
screenshot_2018-08-15 after png png image 4160 x 4480 pixels

:thinking:

**Comment by Kurfursten** [comment]
I'll get that one too in another PR. I need to do a big atmosia cleanup because right now it hurts to live, and conveniently that spot is right next door.

**Pull request merged**
