### PR TITLE
Medical HUD Record Display Updates

### PR DESCRIPTION
**Pull request by jwhitak**
# Medical HUD Record Display Updates
image

## What this does
This PR updates the Medical HUDs so that:
* they display both the physical and mental status of the patient (vs just physical)
* the examine proc shows the mental status immediately
* and relocates the mysterious blue square (physical status) to the outline of the health status.

Note that this doesn't add or change any of the existing physical/mental statuses, only updates their display on the HUD.

image

### Physical Statuses

- Active: Blue outline.
image
- Disabled: Red outline.
image
- Physically Unfit: Flashing yellow outline.
physunfit
- SSD: Grey outlne.
image
- Deceased: Black outline.
image

### Mental Statuses

- Stable: No change.
- Watch: Grey tab on top.
image
- Unstable: Flashing yellow tab on top.
unstable
- Insane: Flashing red tab on top.
insane

## Why it's good
Lets a medical doctor inform the rest of medbay that this particular dude is absolutely insane while also not having to set their physical status to physically unfit for the funny yellow square.

Additionally, moving the 'blue square' to the outline of the health status lets you see the status while also having the faction icon on the right side in case of antags. Now you will know if your rev buddy has been marked physically unfit without the rev icon covering it up.

That's not good enough? Uh um errr ahhh... eehhh............

## Changelog

:cl:
 * rscadd: Added mental health status to medhud overlays.
 * tweak: Moved the blue physical health square to an outline over the health status.
 
 [UI] [sprites] [tested]

### CODE REVIEW

**Comment by Eneocho** [comment]
Does this work with pAIs using the medical module (and on that topic, does the sechud work for pAIs with the sec module?

**Comment by jwhitak** [comment]
Yep, you can even try it out on live right now. Join as a pAI and observe - working HUDs! They use the new datums. They can still set to arrest, even (as was the case before the hud update).

**Comment by PrimeDSS13** [comment]
I like the PR, not sure if I like the status being such a small outline. I suppose it's not the most important thing, but I liked the visual clarity of the square.

**Comment by jwhitak** [comment]
Ironically, this change is because of visual clarity. Faction icons and (when using combined huds, loyalty implants) would cover up the blue square of physical activeness. The outline of the health indicator was free space that wasn't being utilized, so was a good alternative.

**Comment by Kurfursten** [comment]
Update wiki with pictures

**Pull request merged**
