### PR TITLE
Protolathe Filtering, Custom Protolate Queueing & Other Incredible CamelCase Tales

### LINKED ISSUE #3999: [Feature Request] Sorting for the protolathe
I've had this idea in the back of my head for the last month.  The protolathe menu has so many items and it's so unwieldy.  It's a game of memorizing key words so you can ctrl-f faster, like knowing that management only comes up once so you can quickly jump to incision management devices or precision for high-precision scalpels (and just why the hell do we need 3 super scalpels to begin with)

What would really be beneficial is to have a sorting button that hides the things you're not looking for.  Something like this image attached at the end.  That way if you just want tier 2 parts you don't have to tab past advanced mass spectrometers and three other things to get to advanced matter bins.  And so on.  Having some sorting options would be the bees fucking knees.

 
ss 2015-04-19 at 02 36 12

I considered the autolathe as well but since its a much shorter list its not as big of a problem.

### LINKED ISSUE #4296: Circuit imprinters don't show how much glass they contain
Materials menu of UI is always empty, Materials Amount on primary screen never displays anything except 0.

### PR DESCRIPTION
**Pull request by 9600bauds**
FIXES
- Fixes #3999
- Material counters in the Circuit Imprinter construction menu being always 0 (Fixes #4296)
- Circuit imprinters not allowing you to eject materials inserted into them
- Mech fabricator not updating the window sometimes
- Like a couple of typos
- Fixes a bug where protolathes would not get any benefit from upgrading their micro-manipulators

CONTROVERSIAL
- !!accidentally!! fixes a never-reported bug where ALL fabricators could hold INFINITE materials
- To compensate for this, the base amount of sheets each fabricator can hold was buffed to 120 (was 40 originally, what the shit oldcoders?), +30 per bin upgrade (+120 maxed).
- The cap is TOTAL amount of sheets, i.e. 60 metal&60glass or 100metal&20glass etc. The mech fab was given 180 sheets since it's more material intensive.

FEATURING
- Adds sorting and filtering to the Protolathe&Circuit Imprinter construction menus!
- Allows you to queue a custom amount of items for ease of use
- Adds an option to disable window refreshing when queueing item production, to stop the user from being sent to the top of the page every time they queue something (breaks queue number by design when active, can be turned on or off depending on user preference)

OTHER
- Removed the protolathe material display in the construction menu, as it was terribly uninformative and bugged
- Does not break mechfab
- Circuit board categories not guaranteed to be 100% correct

DEMONSTRATION: http://puu.sh/hQaVO/9c60621500.webm

### CODE REVIEW

**Comment by Probe1** [comment]
Well done.  Thank you.

**Comment by ComicIronic** [comment]
I notice the queue number isn't updating after you input a custom queue number. Could you fix that?

Otherwise, looks really good, nice work.

**Comment by 9600bauds** [comment]
That's by design, I added an option to turn off window refreshing, which stops the annoying "send you to top of page again" after every single click, at the cost of not refreshing the queue number.
You're right though, it oughta be off by default.

**Comment by Iamgoofball** [comment]
>MAXIMUM SCIENCE

what is this

**Comment by 9600bauds** [comment]
admin-only debug option for testing

**Comment by FudgePucker** [comment]
Aww man. I wanted to MAXIMUM SCIENCE.
At least make it print a sheet of paper to go to toxins or xenoarch as a joke.

**Comment by 9600bauds** [comment]
Behold, I have rebased

**Comment by Probe1** [comment]
Bugs 

- When you click on Material Storage for the Circuit Imprinter it does not open.  This causes the console to fail catastrophically.   You can still move around to other menus while you have the UI up but if you close the console UI you can never use it again.  HONK.

- Autorefresh does not work.

Features

- I recommend dropping the part modifying its capacity entirely, tabling the issue for now and coming back to it later.  Having a cumulative cap of resources instead of one tied to each specific resource is cumbersome and unfun.  I'm not playing to do inventory juggling.  Having a limited amount you can have in at once is excellent but when you can easily jam in too much then have to stand there and remove some  but how much?  Because it's not in sheets it's in cubic centimeters.  It's a pain in the ass.  The right way, in my opinion, is to only let it hold 50 iron, 50 glass, 50 gold, 50 silver [...] at round start instead of letting it only hold 50 materials total.  

While the latest push increased the cap to 120 so it could hold 60 metal and 60 glass or 20 metal 20 glass 20 gold 20 silver [...], this is still extremely unwieldy and a downgrade from how it currently is with infinite capacity.  I say that as the person who was loudest in encouraging you to fix it and give a limited amount instead of infinite.

**Comment by Probe1** [comment]
I just made some food and I think I can make a good analogy to why the materials limits rub me the wrong way.  

I made some bean burritos.  And they are gonna be fucking  great.  I used a little tarragon, a little bit of chives and oregano, some onions and a bit of garlic.  It's still a bean burrito though.  

Having machine parts, having resource limitations built into the protolathe, it's a spice.  It's the garlic.  It makes it more interesting and complex than just having it by itself.  Sure it's fine by itself but with that limitation comes complexity and interest.  

But what if I added too much spice?  Right now I'm looking at the protolathe and it's giving me a headache from the garlic vapors.  A little bit of garlic is good.  Even whole cloves if you cure them right (cargo techs are an example of masters of material movement).  But when it wasn't supposed to be the main focus of the meal it's overpowering and some people HATE garlic even if most people like a little.  

Having a very limited, cumulative material cost is like having too much garlic on my food.  It's distracting me from what I wanted to do.  It's not fun on its own.  I'm not here to shuffle materials.  I just wanted a little spice to make it more interesting.  I believe it should strictly be tied to each material and not a cumulative cap.

**Comment by ComicIronic** [comment]
I'd be happy with a cumulative cap - because I'd prefer to not have to refill on metal and glass when I only have 5 sheets of each rare material.

I would raise the base cap massively, though.
Each base bin should be 50 sheets, the upgrade should be 125, and the final should be 250.

**Comment by Probe1** [comment]
Thanks for pulling the NFD.  I really want that material storage bit looked at and this not getting merged and suddenly a big problem crops up where you have to rebuild a computer if you accidentally press a menu.

Here's my two cents on cumulative versus individual.  

When you make it a cumulative cap on resources then you have to make it much larger in total.  This reduces the early game impact a lot.  When you only have metal and glass then it doesn't matter that you can only fit 100 sheets because you're only working with two types of materials.  No big deal, I have 50 of each.  

But when you're working with 7 different types of materials then that's just 14 sheets of each, or 30 sheets of metal and glass and 8 sheets of the others, etc.  It almost requires you to upgrade the machines or else it's annoying as fuck to use them.  

On the other hand, individual caps instead of cumulative mean you can keep it low and limit the amount you can add during the early game without affecting the late game, and still encourage players to upgrade machines without it being an all out necessity to use it without wanting to tear your hair out.  I feel that this adds more interest to it without as much limitation.

**Comment by ComicIronic** [comment]
> It almost requires you to upgrade the machines or else it's annoying as fuck to use them. 

But I'd prefer that.
People don't feel the need to upgrade currently, even though they should because otherwise we can't design for round progress in terms of machine functionality.

**Comment by Probe1** [comment]
I agree with you.  But I also think it's more annoying to the point of "fuck this I didn't click join to juggle inventory" unless you make them fuckhuge and betray the original point of making them limited in capacity.

I don't want it that way but I think the playerbase will make the final judgement.  I say merge it and see what happens.

BUT I'd rather not do 120, I'd rather do 5's and 10's.  Make it 150 300 500?  Or 100 200 300?  Or somewhere in between, just not 120.  Make it easy to figure out in your head on the spot.

**Comment by 9600bauds** [comment]
I've got to give a big thanks to Probe1 for not only volunteering to test, but providing a very thoughtful review and list of bugs. You da real MVP
In the end I made fabricators hold 562500 units, which is 150 metal sheets or 280 plasma/uranium/whatever. Matter bin upgrades give +50 sheets, maximum 200 (since the Protolathe's speed boost actually works now, people might actually feel like upgrading it)
Hopefully this'll seem like a fair compromise for everyone. I might look into making sheet storage individual for every material but I'll see what kind of feedback this gets first.

**Comment by Probe1** [comment]
Personally checked, no bugs left.  Good for merge.

**Pull request merged**
