### PR TITLE
Nerfs weak .38 stun and knockdown duration from 5->1 

### PR DESCRIPTION
**Pull request by ghost**
Mainly nerfs detective revolver, but also glock. These things fire way too fast and penetrate glass and such.
:cl:
 * tweak: .38 weak bullet stun duration reduced to 1 second from 5.

### CODE REVIEW

**Comment by falcon2346** [comment]
Is 1 second enough time to even cuff someone? That's so short.

**Comment by MercuriusGH** [comment]
glock bullets are as fast as electrodes what the fuck are you doing
also i ded

**Comment by ghost** [comment]
Detectives should not be putting on cuffs, they're detectives. Also the bullets travel as fast as any other bullet, i.e. almost instant.

**Comment by falcon2346** [comment]
> Detectives should not be putting on cuffs, they're detectives. Also the bullets travel as fast as any other bullet, i.e. almost instant.

You might as well be saying that detectives should just executing any threats then, this just makes stun bullets effectively worthless. Plus, while detectives may not be cuffing people this doesn't _only_ effect their revolver. You can no longer use glocks to get your arrest either with this.

**Comment by Kromkar** [comment]
"i died pls nerf"

**Comment by ghost** [comment]
NT glocks are .380, not .38.

**Comment by Squird5** [comment]
Skill issue

**Comment by PrimeDSS13** [comment]
i died pls nerf

**Comment by falcon2346** [comment]
> Mainly nerfs detective revolver, but also glock.
> NT glocks are .380, not .38.

Literally what did he mean by this? It's still dumb, it turns the revolver into a ranged disarm when there are other guns that do that and also give you enough time to do whatever the hell you want with them. 1 second isn't enough time to do anything so you might as well start with lethals from the word go.

**Comment by boy2mantwicethefam** [comment]
The number and duration of stuns are awfully common compared to how strong they are. In the space of 10 seconds you can just toolbox someone to death if they are not wearing sufficient melee protection. Flashes are scattered around the station and they stun for a whole 20 seconds, not even weaken so that they could crawl around, just stun.
I support this change but it affects way more than just the detective's revolver and glocks; it also affects beanbag slugs (such as the bartender's), I recommend changing it so that the intended targeted weapons have modified gun code that causes the projectiles to have a drastically reduced stun value when fired, look at the Hunting Rifle for an implementation of this system, which removes the stun value against human targets, and it is also a .38 bullet type.
I also recommend raising the stun value to 2, otherwise a target could immediately get back up in less than a second due to the Life() timing.

**Comment by Squird5** [comment]
> > Mainly nerfs detective revolver, but also glock.
> > NT glocks are .380, not .38.
> 
> Literally what did he mean by this? It's still dumb, it turns the revolver into a ranged disarm when there are other guns that do that and also give you enough time to do whatever the hell you want with them. 1 second isn't enough time to do anything so you might as well start with lethals from the word go.

380vs38
.380 Auto vs .38 Special

**Comment by angryturnip** [comment]
I nominate this for grudgecode of the year

**Comment by falcon2346** [comment]
> The number and duration of stuns are awfully common compared to how strong they are. In the space of 10 seconds you can just toolbox someone to death if they are not wearing sufficient melee protection. Flashes are scattered around the station and they stun for a whole 20 seconds, not even weaken so that they could crawl around, just stun. I support this change but it affects way more than just the detective's revolver and glocks; it also affects beanbag slugs (such as the bartender's), I recommend changing it so that the intended targeted weapons have modified gun code that causes the projectiles to have a drastically reduced stun value when fired, look at the Hunting Rifle for an implementation of this system, which removes the stun value against human targets, and it is also a .38 bullet type. I also recommend raising the stun value to 2, otherwise a target could immediately get back up in less than a second due to the Life() timing.

If you want to do a big pr reworking most stuns to at least allow them to be crawled during be my guest, I'd probably support that one even. This is just blatant grudgecode for getting owned though.

**Comment by jwhitak** [comment]
10 thumbs down in 30 minutes, impressive

**Comment by angryturnip** [comment]
I see VG has bad opinions, so I will be closing this PR.

**Pull request closed without merging**
