### PR TITLE
Makes your action progress bars show up for targets too

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
the do_after bars now show up for anyone the action is being applied to

## Why it's good
gives them a visual reference of how long it takes someone to forcefeed you or etc

## How it was tested
calling attackby on the other mob with the player as an argument with things like cuffs and food
calling strip_item_from() on the players worn jumpsuit and the other mob, with pickpocketing on and off
## Changelog
:cl:
 * rscadd: Progress bars from actions are now visible to the targets of these actions, if enabled in prefs and not via pickpocketing or vampire silent bites.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
i gave it the wrong label pls fix

**Comment by SonixApache** [comment]
might be smart to allow overrides to hide for case-by-case specifics

**Comment by SECBATON-GRIFFON** [comment]
> might be smart to allow overrides to hide for case-by-case specifics

which ones in mind?

**Comment by SonixApache** [comment]
nothing comes up but i foresee consequences for stealthy things
like trying to steal things with the thief gloves for example

**Comment by SECBATON-GRIFFON** [comment]
> nothing comes up but i foresee consequences for stealthy things like trying to steal things with the thief gloves for example

good point, i'll see what i can cover

**Comment by angryturnip** [comment]
On the fence about this because stuff like stealth cuffing someone and hoping they are just looking at the game instead of the text at the side is a staple tactic. It would be nice if maybe like on harm intent the bar doesn't show up for others still or something like that to still have the option.

**Review by west3436 — APPROVED** [review]

**Pull request merged**
