### PR TITLE
You can now emag advanced clown shoes to choose a very special sound

### PR DESCRIPTION
**Pull request by Intigracy**
https://dl.dropboxusercontent.com/s/ahnnmk4xbcd3mwf/2017-01-24_12-11-08.mp4

:cl:
 * soundadd: "You can now emag advanced clown shoes to be able to play a very special sound."

### CODE REVIEW

**Comment by Exxion** [comment]
Absolutely horrifying

Also, ouch, my immulsions

**Comment by Aurx** [comment]
Adminhelp.ogg and other adminsounds should remain strictly OOC.

**Comment by Intigracy** [comment]
😢

**Comment by Probe1** [comment]
@Aurx it plays when someone is trying to clone you and you aren't in your body.

**Comment by PJB3005** [comment]
That's OOC.

**Comment by Probe1** [comment]
Yeah I can see what you mean after reflecting.  It still annoys the fuck out of me.

**Pull request closed without merging**
