### PR TITLE
Midround rulesets will now roll more often

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Dynamic
(We don't talk about midrounds for living players, just don't)

Midround rulesets will now roll as often as latejoin rulesets do, which is some fancy mathematical distribution that goes from 5 minutes to 30 minutes. Previously it was 15 minutes to 50 minutes.

One issue with midround rulesets is that latejoiners would appear more often and drain the amount of points that could be used for midround rulesets, causing bigger and cooler rulesets to be less likely to fire because they would be short a few points, which were just used to send a ninja or something. Latejoining rulesets are on average less threatening because it is individual antagonists that get sent, but the only rulesets that cost less than 20 points are the Traitor and Time Agents rulesets. Everything else takes a hefty bite out of the available pool, even ninjas.
This alleviates that issue by making midround rulesets as likely to roll as latejoin rulesets.

:cl:
 * tweak: Midround rulesets will now roll more often.

### CODE REVIEW

**Comment by SonixApache** [comment]
counter-PR: automatically 24-hour-ban the asshats that spam MIDROUNDS WHEN in dedchet

this issue would be better alleviated by having more midrounds to choose from, rather than this

**Comment by boy2mantwicethefam** [comment]
There are 18 midround rulesets.

**Comment by SonixApache** [comment]
ok i'm a buffoon then thank you

**Comment by hacker-on-steroids** [comment]
with how roundending grues/pulsedemons can be i have some doubts about spawning a fresh one in every five minutes
don't know much about dynamic and threat costs though

**Comment by boy2mantwicethefam** [comment]
Grues and pulse demons are more common as latejoins because there are fewer latejoin rulesets that can roll. Midrounds have more variety.

**Pull request merged**
