### PR TITLE
removes a pointless file

### LINKED ISSUE #10777: Hunt for Oldcode: Plasmoid disease does not exist
https://github.com/d3athrow/vgstation13/blob/629f35941fb0b109ab257139021734eb386001e4/code/datums/diseases/plasmatoid.dm
This disease exists only in the form of a non-functional disease, and an entry in the medical records claiming it makes humans and monkeys require toxin to breathe. We already have plasmamen, and this file was last updated 23 Aug, 2010. I say we remove it.

### PR DESCRIPTION
**Pull request by kol1th**
The world may never know.

Closes #10777

### CODE REVIEW

**Comment by kol1th** [comment]
hurr durr

**Comment by Shadowmech88** [comment]
Why close it?
The error was because you didn't commit the changes you made to vgstation13.dme by removing the file.

**Comment by gbasood** [comment]
@kol1th reeeee

**Comment by kol1th** [comment]
oopsie i forgot about it :^) i'll fix it sometime maybe

**Pull request closed without merging**
