### PR TITLE
fixes server crash

### PR DESCRIPTION
**Pull request by Intigracy**

### CODE REVIEW

**Comment by Shadowmech88** [comment]
<strike>Why was this causing a crash?</strike>
Nevermind, I misread the diff and thought that bit of code was being removed, not added.

**Comment by DamianX** [comment]
Is `locate` sufficient or do you need to search other nested containers as well?

**Comment by gbasood** [comment]
5 days and no response to that question

**Comment by PJB3005** [comment]
Somebody fill me in on what the problem and this PR fixes.

Is the SST doing an infinite loop if you select something containing the user? In that case, `locate` won't help you since it's not recursive.

**Comment by Exxion** [comment]
BYOND will not allow an object to contain itself anyway, directly or otherwise. Or at least I couldn't get it to do so.

**Comment by gbasood** [comment]
@Exxion we need a more verbose answer, because it isn't about recursive containment that we're worried, but whether or not a thing 3 levels down will still crash

**your pr fixes:**
turf > thing > shooter
**we're worried about:**
turf > thing > thing > shooter

**Comment by Exxion** [comment]
I don't think you understood what I was saying.
If `afterattack()` ever manages to get called with `user` somehow inside `src`, through any number of layers, something has already gone horribly wrong.

**Comment by Exxion** [comment]
Alright actually I either misread or misremembered something about this PR so disregard that last bit
But can you even attack something while not directly in a `turf`?

**Comment by gbasood** [comment]
With a gun? Not sure
But things like pAIs could do it i.e. interfacing with doors

**Comment by gbasood** [comment]
oh my god
@Exxion look at the remoteattack proc

```dm
 /obj/item/weapon/subspacetunneler/remote_attack(atom/target, mob/user, atom/movable/eye)
 	return afterattack(target, user) //Allow using the tunneler through cameras and remote view
```

**Comment by Exxion** [comment]
Yeah that's... not the best way to structure that
But I guess it could be a lot worse

That does show that `locate()` is inadequate, though

**Comment by Intigracy** [comment]
Is there even anything a user can be inside that could be inside something else while still allowing them to interact?

**Comment by PJB3005** [comment]
Is there any actual difference to the code causing the SST to trigger?
Being in a package wrapped crate'll do it.

**Comment by Exxion** [comment]
1. It doesn't matter if there is right now, because there *could* be
2. If nymphs can use it, then very very yes

**Comment by gbasood** [comment]
things that might break with just locate that I can think of off the top of my head
 - pAIs
 - carded AIs
 - aghosts
 - nymphs maybe? but I doubt it

**Comment by DamianX** [comment]
I _still_ don't know how to reproduce this server crash

**Comment by Intigracy** [comment]
hold subspace tunneler
get in locker
close locker
click your locker with subspace tunneler in hand

**Comment by DamianX** [comment]
You can't tell but I'm clicking

**Pull request closed without merging**
