### PR TITLE
Dangerous Poutine and Dangerously Cheesy Poutine

### PR DESCRIPTION
**Pull request by Plaguewalker**
Poutine Code
http://pastebin.com/FVSkYGvH

poutinedangerous
image

poutinebarrel
image

### CODE REVIEW

**Comment by PJB3005** [comment]
I think you messed up.

**Comment by Shadowmech88** [comment]
>`Plaguewalker  wants to merge 5 commits into testserver from Bleeding-Edge`

You bungled it.

**Comment by Plaguewalker** [comment]
Look it's my first time using github

**Comment by PJB3005** [comment]
What if we test merged this PR?

**Comment by Probe1** [comment]
things break and I go to bed?

**Comment by PJB3005** [comment]
Oh shit so that's what happens.

**Comment by Plaguewalker** [comment]
Well, I was told the code is slightly old.

**Comment by Shadowmech88** [comment]
You're going to have to make a new PR for it, can't reopen this one.

**Comment by ghost** [comment]
@Plaguewalker Let me explain a few things.
The pastebin whoever sent you is supposed to be pasted in the correct file by you. There's no files modified in this PR because you didn't do that, you just linked the code. 
Make a fork of the repo, make a new branch, push the changes to it, and then makes a PR merging your branch from your repo into Bleeding-Edge on this repo.
Whatever you did this is fucked

**Comment by kilozombie** [comment]
I sent him it on the thread thinking it was like Probe or Shadowmech offering
I'll probably just do smartgit and do it myself. It's just a minor bit of effort and I'm lazy.
edit: Not smartgit, probably CLI

**Pull request merged**
