### PR TITLE
gives HUDs a moment to catch up before action buttons are applied

### PR DESCRIPTION
**Pull request by ghost**
Whole lotta runtimes from when a mob is being created or otherwise possessed by a player

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by clusterfack** [comment]
\>using spawn() like this

Haha, what

**Comment by Intigracy** [comment]
well

it works

**Comment by clusterfack** [comment]
No, if a spawn(1) fixes it, that means the problem with this is the ordering of login code. This code is in the wrong place.

Imagine how many arbitrary spawns we would have if we used them to fix any problem with ordering.
spawn(1) -> this fixes runtime A
spawn(2) -> this fixes runtime B since A code needs to run first

It's a terrible practice

**Comment by SonixApache** [comment]
@Skullyton last updated two months ago

**Comment by Exxion** [comment]
Yeah, and I'm with Cluster here

**Pull request closed without merging**
