### PR TITLE
removes adv hotkey mode feedback

### PR DESCRIPTION
**Pull request by PJB3005**
<PJB3005> probe, is the feedback messages from the adv hotkey mode system REALLY that bad?
<probe1> yes.

### CODE REVIEW

**Comment by d3athrow** [comment]
Honestly I dont like adv hotkey mode at all, the input delay due to it being serverside makes it annoying as fug.

**Comment by Iamgoofball** [comment]
wait what

I can't wait for the ahelps of "i can't move all of the sudden what the hell happened"

why would you ever remove feedback telling you you switched your control scheme

are you high

:-1:

**Comment by PJB3005** [comment]
because probe1 found it annoying, just leaving it here

also D3athrow, I've found the lag minimal, I could make it more hardcoded & crappy if you want, so it's clientside again

**Comment by clusterfack** [comment]
I like the hotkey feedback, but I don't like how hotkey swapping takes literally 2 seconds to activate now.

**Comment by ririchiyo** [comment]
Make it clientside, end of discussion.

**Comment by PJB3005** [comment]
I have an idea on how to do this, and keep both the server side one (muh AZERTY) and the clientsided one

**Pull request closed without merging**
