### PR TITLE
[seven thousand percent tested] Fixes ethanol wiping clean papers

### PR DESCRIPTION
**Pull request by 9600bauds**
something something whitespace

### CODE REVIEW

**Comment by gbasood** [comment]
I'm really confused as to why this was actually a problem

**Comment by 9600bauds** [comment]
Annoying message spam since sprays work like three times on the same thing.
I didn't test it but presumably ethanol smoke would generate 50 message a second.

**Comment by clusterfack** [comment]
100% untested

**Comment by 9600bauds** [comment]
I did test the fix. I just didn't test if ethanol smoke also had this issue (which I can make an educated guess and say it did), but this bugfix does work as advertised, and if ethanol smoke did have this issue (which it surely did) then this also surely fixes it.

**Comment by ghost** [comment]
Test the ethanol smoke then :^)

**Comment by gbasood** [comment]
when you test it (tm)

**Comment by 9600bauds** [comment]
practical way to test changes: toggle your fix using ooc_allowed

```
if((paperaffected.info || paperaffected.stamps) || !ooc_allowed)
```

http://a.pomf.cat/klwbbs.webm

I really don't think this was necessary

**Comment by ghost** [comment]
Doesn't look 7000% tested in that it spams chat even with one piece of paper being cleaned. :-1:

**Comment by 9600bauds** [comment]
go away you are banned from this PR

**Comment by ghost** [comment]
;__;

**Pull request merged**
