### PR TITLE
Buffs portable air pumps

### PR DESCRIPTION
**Pull request by brndd**
[tweak] [powercreep]

These things are fucking terrible for actually repressurizing rooms. Fill them to 4500 kPa and they hold enough air to pressurize 18 turfs to 100 kPa, and will take literally 15 minutes to do so. Absolutely laughable.

I doubled their capacity (1000 litres -> 2000 litres, for comparison canisters are 1000) and made them pump much faster (300 litres per tick, injectors are 200). This does mean that they're basically canisters with more capacity and extra features now. I don't know if that's a bad thing, because they're less available than canisters. If you think it's bad, there are two options: not buffing the volume on these (remember, 18 turfs), or buffing the volume on canisters (objectively powercreep and bad).

I'll be taking a look at portable scrubbers next because those are also laughably bad for actually scrubbing anything.

:cl:
 * tweak: Portable air pumps now pump faster (300 litres per tick) and have twice the volume.

### CODE REVIEW

**Comment by brndd** [comment]
Oh wait looks like I put it at 300 litres per tick because I thought a big hunky pump whose only purpose in life is to pump should be a bit more powerful than the tiny inline pumps you can put on pipelines.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
The hero we needed

**Comment by FudgePucker** [comment]
Considering you cant use scrubbers to fill one with enough gas to create a star this is needed.

**Comment by brndd** [comment]
Even if you could use scrubbers these would be borderline worthless. I'm not exaggerating (much) when I say they take 15 minutes to refill a room. It literally took 13 minutes for a pump varedited to have practically infinite volume to pressurize the Box courtroom (99 tiles) from 0 kPa to 100 kPa. For comparison, a single vent fed from a 250 kPa distro line did the same in 8 minutes, and a single vent from a 4000 kPa distro line did the same in... 30 seconds.

After this change the number is much closer to 30 seconds to one minute, assuming you have enough gas in the pump. The gas contents will be the primary limiting factor now, rather than speed (or speed AND gas contents I should say).

**Pull request merged**
