### PR TITLE
Fixes Some New() Arguments

### PR DESCRIPTION
**Pull request by Shadowmech88**

### CODE REVIEW

**Comment by ComicIronic** [comment]
What's the point of this?

**Comment by Shadowmech88** [comment]
PJB said that the first argument passed to `New()` should always be an atom, not a turf. I didn't know that back when I wrote these, so I thought it best to correct them now.

**Comment by ComicIronic** [comment]
I guess it's good for readability, but be aware that this doesn't  actually affect any code apart from your get_turf change, thanks to Byond's woefully ineffective type system.

**Review by ComicIronic — APPROVED** [review]

**Comment by gbasood** [comment]
It prevents future fuckups that might *possibly* occur because someone tried
`var/obj/shitteritem = new(locker)`
But that probably wouldn't have happened ot begin wtih

**Pull request merged**
