### PR TITLE
Updates minebot icon

### PR DESCRIPTION
**Pull request by jknpj**
miningbots

Ports the new icon from tgstation/tgstation#36308 Sprite by Onule. The old icon is still in the .dmi if someone wants to use it.

:cl:
 * sprites: Minebots have been given a visual makeover by Onule

### CODE REVIEW

**Comment by ghost** [comment]
Of all the words of tongue and pen the saddest are these: TG spreads again

**Comment by MadmanMartian** [comment]
keep the old, have the new be a beefier version that's more expensive

**Comment by Blithering** [comment]
I NEED PICTURES, PICTURES OF MININGBOTMAN

**Comment by jknpj** [comment]
incondiffbot god

**Comment by Blithering** [comment]
My bad, didn't know the icondiffbot posts the sprites. Overall its an upgrade, but I'm not a fan of the new perspective.

**Comment by jknpj** [comment]
My bad for making that post sound rude i just had no time to make a spinning gif of them

**Comment by Blithering** [comment]
Didn't come off as rude at all. I like the idea of having an upgraded version (maybe with pAI control for mining buddy shenannigans?) but again, its a shame all the new perspective tg sprites have that blobbiness to them like they were made of duplo

**Comment by Probe1** [comment]
The sprites fines.  Everyone will get used to the new sprite and  yada yada.  Lets not do the dinosaur dance over a sprite for some shit that almost never gets used.

**Comment by Blithering** [comment]
I did already say the sprite is overall better than the current one, I do however reserve my right to do the dinosaur dance whenever the opportunity arises

**Comment by Riekland** [comment]
We already had this argument and it was decided that the top down perspective was gay and stupid and for homos on goone and tege only

**Comment by AutismSpider** [comment]
use the top down mine bot for as pai upgrade that cost 4000$ or some shit

**Pull request closed without merging**
