### PR TITLE
Added a few in-hand sprites for drinking glass & co

### PR DESCRIPTION
**Pull request by JMWTurner**
glass

added in-hand sprites for the above drink containers.

the framework allows people in the future to add in-hand version of every cocktail if they wish.

### CODE REVIEW

**Comment by JMWTurner** [comment]
revision 1
- copied a few sprites from items_lefthand.dmi and items_righthand.dmi to left/drinkingglass.dmi and right/drinkingglass.dmi, such as the beer bottle or the cola can.

**Comment by GenericGoose** [comment]
back sprites look wrong

**Comment by JMWTurner** [comment]
@GeneralGoose Often, knowing precisely which item a player is holding is more important than accurate perspective. I applied that logic here. Beer bottles, Cola cans and a few other similar items already appear the same way in-game.

**Comment by JMWTurner** [comment]
revision 2
- Fixed conflicts (caused by changelog file)

**Comment by NigglyWiggly** [comment]
> Those north facing sprites

Please no

**Comment by NigglyWiggly** [comment]
None of our other sprites follow that design philosophy, and it just looks sort of silly

**Comment by ghost** [comment]
I agree with Niggly

**Comment by Intigracy** [comment]
Yeah those north facing sprites are atriocious.

**Comment by GenericGoose** [comment]
@JMWTurner well thats just stupid honestly and people think the same
you can know what people hold by examining, can't you?

**Comment by Exxion** [comment]
That argument for the north sprite makes sense for weapons or things that are really important to see, but not really for drinks

**Comment by JMWTurner** [comment]
I hear you loud and clear

revision 3
- drinks are hidden by the body when facing north
  voila

**Pull request merged**
