### PR TITLE
Refactors the Cyborg/AI Uloads into a single Law Upload Console

### LINKED ISSUE #20370: Cyborg Upload when no Cyborg Bug
#### Description of issue

When attempting to upload a law to the cyborg upload with no cyborg online, you will get an error stating the cyborg you are attempting to update the laws of is too far away.  While I know time can technically be used as a unit of distance, I doubt that was what was intended here.   I suspect the game considers the nearest cyborg to be an infinite distance away as there is no cyborg in range and is thus giving this bug.

#### Difference between expected and actual behavior

Weird error message

#### Steps to reproduce
Upload law when no cyborgs are in the round

edit: Apparently we cant manually add the muh immulsions tag

### PR DESCRIPTION
**Pull request by jknpj**
Closes #20370

Still rough around the edges but better than what it was. It really makes easier to add law uploading to other silicons in the future.

The old cyborg upload got replaced by a second law upload console in all maps. This might need to be changed.

:cl:
 * tweak: The Cyborg/AI Upload Consoles are now a single Law Update Console.
 * bugfix: Fixes maps that didn't have a longrange law upload console
 * bugfix: Fixes centcomm not having a longrange law upload console

### CODE REVIEW

**Comment by brndd** [comment]
Why not just remove the other console from the maps rather than have a duplicate?

**Comment by jknpj** [comment]
@brndd i'll leave it to the mappers themselves, i-it's not like i'm refusing to touch DM Map Editor or something.

**Comment by brndd** [comment]
but you're literally editing the maps in this PR, all you would have to do is remove `/obj/machinery/computer/borgupload` from the line instead of replacing it with `/obj/machinery/computer/lawupload/longrange`

**Comment by jknpj** [comment]
I honestly don't care about this enough to handle the conflicts

**Pull request closed without merging**
