### PR TITLE
Added speed setting for spacepods

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * rscadd: Spacepod pilots can now choose if they want to go fast or slow.

### CODE REVIEW

**Comment by Kurfursten** [comment]
That slow is *really, really* slow. Could we get a middleground? What's the space drifting speed?

**Comment by DamianX** [comment]
I intentionally made it REALLY slow because my intended use-case was getting in/out of the fucking spacepod room's plastic flaps without going back and forth 100 times. More settings can easily be added.
Space drifting speed would be like `movement_delay = 5` unless I'm mistaken

**Comment by Kurfursten** [comment]
Alright, as long as it's faster than drifting

**Comment by SonixApache** [comment]
i'm happy with docking speed

**Comment by Dacendeth** [comment]
while you're adding speed changes any chance we could get a brake feature? Sometimes I want to sit still without getting out or taking the cell out.

**Comment by Exxion** [comment]
IIRC you can brake by tapping the movement key opposite the direction you're moving
You only actually start moving the other direction if you hold it

**Comment by Dacendeth** [comment]
As far as I can work out there's no way to stay still, tapping the direction in the spacepod changes your facing and you continue to drift in your new direction, like a jetpack without stabilization on.

**Comment by Exxion** [comment]
Works On My Machine, but the tap has to be *very* short

EDIT: Actually this might just be the bug where things stop drifting if they change direction with precise timing

**Comment by Dacendeth** [comment]
huh yeah okay I tried it again with the quickest tap i could muster and it actually worked, would have never figured that out on my own.

**Pull request merged**
