### PR TITLE
Update the readme a tad.

### PR DESCRIPTION
**Pull request by PJB3005**
Travis-CI and a Discord link.

### CODE REVIEW

**Comment by gbasood** [comment]
next up code coverage @PJB3005 :^)

**Comment by PJB3005** [comment]
> unit tests

> byond

**Comment by ComicIronic** [comment]
Actually, what would be doable for unit testing? Spinning up a specially-config'd world which runs a bunch of code in the tests module under test datums which isn't otherwise included?

**Comment by gbasood** [comment]
it'd be really hard for us to do proper unit testing
for simple things, maybe machines, you could feed them dummy data and see if they don't runtime and that's probably about it

wouldn't even need to spin up a full world

**Pull request merged**
