### PR TITLE
Fix/rework droppers

### LINKED ISSUE #28526: droppers are broken
(WEB REPORT BY: locese REMOTE: 206.221.180.138:7777)
# Revision
39aab4046ad46d1f33c14947853e71869bee37ce

# Description
droppers are broken, they don't relay reagents for humans
# Steps to Reproduce
take dropper, take some chems in it, use it
# What you Expected
to give someone 5 units of something or apply imidazoline on eyes for instant eye cure
# What Actually Happened
it gave around 0.83 units to the target, which were gone too quick to record with the reagent scanner

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #28526.

I thought this was a simple-enough bug to fix, but in fact, the proper way to do it was to code yet another method for reagent transfer specific to droppers.

Droppers now transfer all the volume of the reagent, except of course if the patient/victim is wearing eyewear. To make them different from harmsyringes or old-school injectors, you need to stand still 2 seconds - more than enough if you slipped the victim - for the squirting to work.

For a few things - nanites, xenomicrobes, and pepperspray -, I copypasted a stronger version of the `TOUCH` reaction.

### CODE REVIEW

**Comment by jknpj** [comment]
here let me squirt some cyanide on your eyes

**Comment by ShiftyRail** [comment]
@jknpj The guy needs to stand still 2 seconds.

**Comment by Kammerjunk** [comment]
I vaguely remember some complaining about droppers. is that what caused them to break/change to begin with? if so, was it actually a problem or was it one single person who did it once?

**Comment by ShiftyRail** [comment]
#27116 was the original change. Prior to that, droppers were unwieldy and not very intuitive. The PR fixed that, but used `TOUCH` which factored every single piece of clothing the mob would wear. This gave quickly diminishing returns (and didn't make much sense, why would your chest armour protect your eyes?). 

I coded a special proc for droppers that allow them to ignore permeability. In exchange, you need the patient/victim to stand still for 2 seconds to perform the operation.

**Comment by Kammerjunk** [comment]
huh. I'll admit, I don't think I've ever used droppers to get stuff into people's eyes cause you have to actually have to have a liquid for it.
good change either way, permeability is a fuck

**Pull request merged**
