### PR TITLE
Removes the stormtrooper kit from box armory.

### PR DESCRIPTION
**Pull request by Probe1**
https://github.com/d3athrow/vgstation13/issues/9234

I'm fine with references.  The whole game is a reference to something or other.  But when it's too obvious it lowers the quality of the game.

The discussion almost entirely agreed.  Put it in a vault or something, not in the damn armory where it's a default, vanilla, canon kind of item.

### CODE REVIEW

**Comment by SkowronX** [comment]
:+1:

**Comment by ghost** [comment]
Sure, let's get it over with

**Comment by Intigracy** [comment]
Especially since people break in just to steal those.

**Comment by KingCrimsonIJW** [comment]
Doesn't it also make your accuracy decrease by a fuck ton?
Also >no helmet light
I never liked it, but it was okay to have in the Force Awakens days

**Comment by gbasood** [comment]
Not sure why because stormtrooper blasters have a chance to become permanently useless laser tag guns.

@KingCrimsonIJW You have something like a coin flip's chance to make your blaster into a useless pile of junk that 'misses'

**Pull request merged**
