### PR TITLE
Slight changes dynamic roundstart

### PR DESCRIPTION
**Pull request by ShiftyRail**
While I hate malf and cult as much as the next guy, this might be the reason why they do not fire
Thanks to Deity for noticing it

[bugfix]

### CODE REVIEW

**Comment by DeityLink** [comment]
Don't forget to edit the simulate_roundstart() proc

**Comment by tuypo1** [comment]
Thank fuck, I haven't been culted once since the weight reduction.

**Comment by ShiftyRail** [comment]
The simulation proc works correctly, it's the logic for the actual roundstart that was faulty.
I'm going to assume I was very tired when I coded it

**Comment by DeityLink** [comment]
Oh there's another big issue, you used a return FALSE here
```
/datum/gamemode/dynamic/proc/picking_roundstart_rule(var/list/drafted_rules = list())
	var/datum/dynamic_ruleset/roundstart/starting_rule = pickweight(drafted_rules)

	if (starting_rule)
		message_admins("Picking a [istype(starting_rule, /datum/dynamic_ruleset/roundstart/delayed/) ? " delayed " : ""] ruleset...<font size='3'>[starting_rule.name]</font>!")
		log_admin("Picking a [istype(starting_rule, /datum/dynamic_ruleset/roundstart/delayed/) ? " delayed " : ""] ruleset...<font size='3'>[starting_rule.name]</font>!")

		roundstart_rules -= starting_rule
		drafted_rules -= starting_rule

		for (var/datum/dynamic_ruleset/roundstart/DR in executed_rules)
			if ((DR.flags & HIGHLANDER_RULESET) && (starting_rule.flags & HIGHLANDER_RULESET))
				message_admins("Ruleset refused as we already have a round-ending ruleset.")
				log_admin("Ruleset refused as we already have a round-ending ruleset.")
				return FALSE
```

which means it'll completely cancel the search for an additional ruleset. Do it this way rather:

```
/datum/gamemode/dynamic/proc/picking_roundstart_rule(var/list/drafted_rules = list())
	var/datum/dynamic_ruleset/roundstart/starting_rule = null
	while (drafted_rules.len > 0 && !starting_rule)
		starting_rule = pickweight(drafted_rules)
		for (var/datum/dynamic_ruleset/roundstart/DR in executed_rules)
			if ((DR.flags & HIGHLANDER_RULESET) && (starting_rule.flags & HIGHLANDER_RULESET))
				message_admins("Ruleset refused as we already have a round-ending ruleset.")
				log_admin("Ruleset refused as we already have a round-ending ruleset.")
				drafted_rules -= starting_rule
				starting_rule = null

	if (starting_rule)
		message_admins("Picking a [istype(starting_rule, /datum/dynamic_ruleset/roundstart/delayed/) ? " delayed " : ""] ruleset...<font size='3'>[starting_rule.name]</font>!")
		log_admin("Picking a [istype(starting_rule, /datum/dynamic_ruleset/roundstart/delayed/) ? " delayed " : ""] ruleset...<font size='3'>[starting_rule.name]</font>!")

		roundstart_rules -= starting_rule
		drafted_rules -= starting_rule
```

**Comment by ShiftyRail** [comment]
There

**Pull request merged**
