### PR TITLE
Adds the dramatic sound effect to a bunch of things

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Done on request
https://www.youtube.com/watch?v=SFtLvkqHIds

:cl:
 * soundadd: The Advanced Clown Shoes have a new sound effect. Better get ready to criticize people's cooking skills!
 * soundadd: The Sound Synthesizer also has a new sound effect, albeit a bit longer than the shoe variant. Better get your cooking-related insults ready!
 * soundadd: The emag can now be used on microwaves to cause them to produce burned messes regardless of whether you were cooking right, until the microwave is rebuilt. And yes, you guessed it, it comes with a sound effect. The sound effect also plays during April Fools whenever you make a burned mess.
 * bugfix: Fixed a possible oversight where the attack_by() of an emag upon a machine did not return a proper value to signify to children procs that their attack_by() shouldn't happen if it happened in the parent proc, more specifically in cases where attack_by() checks for a positive return in order to stop.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
the PR that saved clowns

**Comment by calzilla1** [comment]
The PR that killed my fucking ears aaaaa

**Comment by Kurfursten** [comment]
I think this is too long to be a good clownstep effect, it won't make any sense.

Would support for sound system but not for shoes

**Comment by kilozombie** [comment]
Make it so you can emag microwaves so they always burn food and play this sound every time

**Comment by Eneocho** [comment]
Does the Chef RAM-say mob make this sound? I can't remember. If it doesnt, add it to it.

**Comment by drawsstuff** [comment]
> Make it so you can emag microwaves so they always burn food and play this sound every time

seconding

**Comment by Eneocho** [comment]
I feel that it would work better for the clownshoes if the audio didn't have the "BWOOM" at the beginning of the sound effect, just the waterphone part itself. (Compare the OP's linked youtube video with the dramatic.ogg file).
Keep the current version for RAMsay bot, make a cropped one for the clownshoes.

**Comment by Viciousaurus** [comment]
> Make it so you can emag microwaves so they always burn food and play this sound every time

Now this is content I can get behind

**Comment by boy2mantwicethefam** [comment]
@Eneocho I'll crop the audio for the clown shoes and add the full audio to the sound synthesizer

**Comment by wotisjanitor** [comment]
> @Eneocho I'll crop the audio for the clown shoes and add the full audio to the sound synthesizer

did you do it yet? Or is something else preventing this getting merged

**Comment by Kurfursten** [comment]
Ideally there should probably be a way to repair the emagging but I guess you can always just deconstruct/reconstruct

Add that somewhere like the Chef page to the wiki so that people know how to fix it

**Pull request merged**
