### PR TITLE
Knight Armor Hardsuits

### PR DESCRIPTION
**Pull request by NigglyWiggly**
Let's try this one more time
Still no item icons, but I just want to be sure that I haven't fucked up everything again
ss 2015-02-20 at 10 08 18
Pic again for reference

I probably could have just edited the last one, but I couldn't figure out how, so whoops

### CODE REVIEW

**Comment by ComicIronic** [comment]
Ideally one should be a subtype of the other. They share a lot of vars.

**Comment by NigglyWiggly** [comment]
I'm not entirely sure what you mean by that, I'm pretty new to all of this. Something like making the black knight stuff /obj/item/clothing/suit/space/rig/knight/blackknight instead?

**Comment by SkowronX** [comment]
yep, that way you don't have to copy pasta code, and all you need to do is change the aesthetics.

**Comment by NigglyWiggly** [comment]
They have different armor stats and names and descriptions and stuff, though. How would that work if it's just an iconstate thing?

**Comment by ComicIronic** [comment]
You can still set the name, desc, and icon vars for knight/blackknight, but a lot of redundant stuff is inherited.

Plus it makes checking if someone is wearing an armor set easier.

**Comment by NigglyWiggly** [comment]
Alright, hopefully that subtype thing should be right.

**Comment by ComicIronic** [comment]
Yeah looks good.

**Pull request merged**
