### PR TITLE
Atmos hardsuits are now laserproof

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
ablative on suicide watch shouldnt affect energy weapons bruh still stunnin still truckin still fuckin  shoutout to shiftyrail for pulling the greatest anime betrayal of all time bruh how tf are lasers real just close byond hahaha fuck quantum mechanics bruh muh immersions bruh how tf are laserproof hardsuits a challenge bruh literally just shoot em slip em stun em they literally only against laser wepons bruh just use literally any other wepon u beby
:cl:
 * rscadd: The very physics of the universe have realized that lasers are like really hot lines so because the atmospheric hardsuit is temperature-proof it doesn't make sense for whoever's beneath to get third degree burns, so now atmospheric hardsuits are laser-proof.

### CODE REVIEW

**Comment by DamianX** [comment]
The trouble with most comedians who try to do satire is that they are essentially brash, noisy and indelicate people who have to use a sledge hammer to smash a butterfly.

**Comment by boy2mantwicethefam** [comment]
you calling me a comedian bruh?

**Comment by jknpj** [comment]
I dare you thumbs up your own PR if you think you aren't.

**Comment by boy2mantwicethefam** [comment]
i bouta thumbed up my own pr bruh

**Comment by DamianX** [comment]
April 1st is 257 days from now

**Pull request closed without merging**
