### PR TITLE
Fixes cargo paperwork for AI and adds basic sound emotes for AI

### PR DESCRIPTION
**Pull request by PublicEnemyMaiPai**
gives AI's the ability to do basic emotes of buzz, beep, law, ping, and halt while fixing the cargo no checking isAI on paperwork
https://github.com/vgstation-coders/vgstation13/issues/18168
https://github.com/vgstation-coders/vgstation13/issues/18180

### CODE REVIEW

**Comment by ShiftyRail** [comment]
1. Actually put "closes #n" in the body of your PR to automagically close the issues.
2. It's not atomic rééé

**Comment by PublicEnemyMaiPai** [comment]
i realized that when i went to pull but i dont know how to split it or undo the thing i did. also its merging a map thing? halp

**Comment by ShiftyRail** [comment]
For the "map" thing, you just need to tick "tgstation.dm" again and untick "test_tiny.dm"

**Comment by DamianX** [comment]
Yeah, no.

- Change `test_tiny.dm` back to `tgstation.dm`
- Use "closes ##18168" as explain [here](https://help.github.com/articles/closing-issues-using-keywords/)
- Add a changelog. see `.github\PULL_REQUEST_TEMPLATE.md` and `html/changelogs/example.yml`
- Split the cargo thingy into another PR. This means you'll have to revert the changes done to that file in this branch.

**Pull request closed without merging**
