### PR TITLE
Transfer eaten creature's stomach reagents to grue.

### PR DESCRIPTION
**Pull request by Hinaichigo**
This makes it so when a grue eats someone, the reagent contents of their stomach also get transferred to the grue. 

:cl:
 * rscadd: Grues also ingest the stomach contents of their victims.

### CODE REVIEW

**Comment by jwhitak** [comment]
If this gets merged, I can't wait to see the grue explode from a water/potass bomb.

**Comment by Hinaichigo** [comment]
> If this gets merged, I can't wait to see the grue explode from a water/potass bomb.

I tested that by eating two humans with stomachs full of potassium and water. It did react inside the grue's stomach ("explodes violently!") but it didn't explode the grue. Then to be sure I tested sipping water and potassium as a human and it also did the same thing, without harming the human. So maybe something isn't set up properly for that? Or its a matter of amounts?

**Comment by jwhitak** [comment]
The explosion scales on the amount, and I don't think the grue has more than a 1000u stomach. For maximum boom, you want 500u/500u water/potass. Will it gib the grue? Science demands answers...

**Comment by Hinaichigo** [comment]
> The explosion scales on the amount, and I don't think the grue has more than a 1000u stomach. For maximum boom, you want 500u/500u water/potass. Will it gib the grue? Science demands answers...

I see. I think the default simple mob stomach size is 100u so that's what grues currently have. When I added 500u of potassium and 500u of water to a human's stomach it did explode them.
I'll see if I can increase the reagent capacity.

**Comment by Hinaichigo** [comment]
I increased the stomach size to 500u for larvae, 1000u for juveniles, and 1500u for adults.
I got the gibbing thing to work a few times by eating humans with 500u bellyfulls of potassium and water, sometimes though it doesn't really explode and seems to mostly make a huge amount of potassium hydroxide that sits in the grue's body and slowly metabolizes. Not totally sure what the difference is.

**Comment by jwhitak** [comment]
Potassium Hydroxide is a byproduct of the explosion. If you mix 500u/500u water/potass, it'll make 1000u of the potass hydroxide... assuming the container that holds the fluid is still intact from the explosion.

Also I'm learning that there's a hard cap on the explosion power of water potass. 75u/75u hits this cap: dev 1 explosion.

This is actually reduced if the explosion happens in a stomach, and further reduced if the stomach's owner is alive. That said, in the water potass code, the holder will still take direct damage from the unnerfed explosion amount before the real (nerfed, assuming it happens in their belly) explosion occurs, which will also damage them.

I have learned much today.

**Comment by Eneocho** [comment]
Can't wait to bomb the grue with two nitrostomach monkeymen.

**Comment by jwhitak** [comment]
For the github dwellers who seek forbidden knowledge: 40u/40u of water/potass is the minimum necessary to gib the grue. Keep in mind that the chemicals metabolize in a living target, so use more.

**Pull request merged**
