### PR TITLE
Rebased, and re-did the Box HoP shutters and blast doors and flash.

### LINKED ISSUE #12646: Shutters on the HoP office windows on box. Good idea? Bad idea?
The box station HoP office windows have no shutters to close in emergencies, unlike the other parts of the bridge. It might be handy to add some, as I have found the ones on meta really useful for hiding behind.
Then again, it might be a bit too secure if they were put in place. Who knows?

### PR DESCRIPTION
**Pull request by SysadminJeroen**
Always got annoyed by greytides breaking down the HoP windows. I mean I can deal with them hacking the HoP's door but if they just go and be assholes and break windows while in the line.

This map change should deter them from being cunts, and also provides a bit more safety for the HoP.

Pic

[Outdated Pic](https://i.imgur.com/JrLSXSQ.png)

[Outdated Gif #1](https://i.imgur.com/ukPfwrD.gifv)

[Outdated Gif #2](https://i.imgur.com/8XeOpT9.gifv)

_[Outdated outdated Vidya](https://a.pomf.cat/amzoju.mp4)_

Closes #12646.

Re-did this, because #12699 got merged while I was busy rebasing and re-doing this.

:cl:
 * rscadd: Added shutters and a flasher to Boxstation's HoP line.

### CODE REVIEW

**Comment by PJB3005** [comment]
Don't do map changes during christmas, because we're gonna revert the maps as soon as the christmas event is over.

At least, I can't think of a good way to undo all the christmas changes otherwise.

**Comment by Probe1** [comment]
We're too fucked already PJB.  We've merged map changes from non christmas stuff and we've not done it in any kind of coherent order.  

I have resolved to personally undo everything we did for Christmas _manually_ if I have to.

**Comment by PJB3005** [comment]
Wait when did we merge non-christmas map changes?

**Comment by Exxion** [comment]
Do not
Ever
Under any circumstances
EVER
Revert map changes after other parts of the map have been changed (with the revert button; manual with DM is fine)
I once had to fix the errors that came up when someone did that
It was awful

**Comment by PJB3005** [comment]
Gas miners in the hallways!

**Comment by Probe1** [comment]
uh I think it was bauds genetics one. https://github.com/d3athrow/vgstation13/pull/12770

Look rather than hold the entire servers mapping PRs hostage for a week, I will do the needful and delete every last damn Christmas change afterwards on all 3 maps.

**Comment by PJB3005** [comment]
There is no damn way you're not at the very least going to miss something on deff.

**Comment by Probe1** [comment]
Players will catch what I fail to.  Anything else will be part of the legacy of /vg/.  It'll be fine (for you.  For me it's a lot of work I have resigned to do)

**Comment by SysadminJeroen** [comment]
Looks like there is a conflict, again.
I'll redo this after Christmas has passed.

**Comment by Probe1** [comment]
Yeah sorry @Jeroen52 I'll have this all sorted by tomorrow evening.

**Comment by SysadminJeroen** [comment]
@Probe1 I mean, it has conflicts that need to be resolved so I'll most possibly need to re-do it. I mean it was done on the xmas map.

**Comment by Probe1** [comment]
Yeah that's what I meant, I'll have all the Christmas stuff undone by tomorrow evening and mapping can resume without fear of Christmas.

**Comment by Shadowmech88** [comment]
Can't we leave the decorations up until New Year's?

**Comment by Probe1** [comment]
edd5e9d2-c5f4-11e6-9fa1-52f1151ca4ce

**Pull request closed without merging**
