### PR TITLE
adds support for mushman silicons

### LINKED ISSUE #30574: [Feature Request] Mushmen should be able to join the crew as mimes, or atleast sillycons like everyone else
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
sneed

### PR DESCRIPTION
**Pull request by SonixApache**
closes #30574

:cl:
 - rscadd: Mushroom men can now be roundstart silicons.

### CODE REVIEW

**Comment by Servalfang** [comment]
what do you think about the possibility of any or all of
-Bartenders
-Janitors
-Medbay Orderlies
-Assistants?

**Comment by SonixApache** [comment]
-Bartenders
Social role, would be awkward if they couldn't speak properly. I wouldn't do it until they get a better way to communicate.
-Janitors
Janitors being weird races isn't a standard here but I'd be all for it.
-Medbay Orderlies
no opinion
-Assistants?
no opinion

**Comment by Servalfang** [comment]
i think people would appreciate a mushtender myself

**Comment by BomberBro** [comment]
This is similar to how Vox began their first steps aboard the station from the depths. I don't mind the robots but otherwise they must be turned back at every corner to prevent their generification.

**Comment by Servalfang** [comment]
> This is similar to how Vox began their first steps aboard the station from the depths. I don't mind the robots but otherwise they must be turned back at every corner to prevent their generification.

gay and dumb

**Comment by SonixApache** [comment]
@BomberBro should i split off the mime change?

**Comment by Eneocho** [comment]
What happens if the mushmime breaks their oath of silence? Do they get their "voice" back or does the no-mouth override that?

**Comment by SonixApache** [comment]
split off to #30628

**Comment by Kurfursten** [comment]
Opinion on this is divided but I believe some of the votes are probably from its earlier incarnation. Give it a few more days then I'll make a call.

**Comment by SonixApache** [comment]
there is literally no reason not to do this, as it doesn't affect anything - it's not like it brings shrooms into the game somehow, just allows people who have shroom selected to sign up as silicon brains

**Comment by Eneocho** [comment]
You should close this PR and make it again, since you changed this one from mushmime+mushsilicon to just mush silicon. You have 👎🏻 that are from people rejecting the mime mush thing.

**Comment by SonixApache** [comment]
it's essentially an oversight fix and :-1:s should really not matter (in this particular case)

**Comment by Kurfursten** [comment]
I think maybe a couple might be "real", but I'll take responsibility for it.

**Pull request merged**
