### PR TITLE
Banic

### PR DESCRIPTION
**Pull request by gurfan**

### CODE REVIEW

**Comment by Exxion** [comment]
Bro just turn on the bunker

**Comment by gurfan** [comment]
What fucking bunker?

**Comment by Exxion** [comment]
The panic bunker. The panic bunker that does exactly this.

**Comment by gurfan** [comment]
The panic bunker doesn't exist. Not anymore at least.

**Comment by Exxion** [comment]
My man it was removed for like two months in 2016. It's a myth that it's gone.

**Comment by bathosbathtime** [comment]
What's the verb to use it again? panic and bunker don't autofill it for me. Don't see it anywhere in the menus either.

**Comment by gurfan** [comment]
> What's the verb to use it again? panic and bunker don't autofill it for me. Don't see it anywhere in the menus either.

the verb was inaccessible because of byond, you had to proc call it

**Comment by bathosbathtime** [comment]
That's pretty funny

**Comment by Exxion** [comment]
It's a change to how we add admin verbs, not a BYOND bug, but yeah, the verb is inaccessible but works with proc call

**Comment by Kammerjunk** [comment]
@Exxion it's surely understandable that people assumed it was gone when 1) the verb (i.e. the way admins have used it) is inaccessible and 2) the entire thing doesn't exist outside the secret repo

**Comment by Exxion** [comment]
I admittedly completely forgot that the verb was broken

**Pull request closed without merging**
