### PR TITLE
Allows anything of type /obj/structure to bump things away in front of them

### PR DESCRIPTION
**Pull request by ghost**
[content][tweak]
Anyone who has used wheelchairs on this server notices they push the ones in front of you when you push one next to you.
This PR now lets any non-anchored structure do this, with a boolean deciding if it has this behaviour or not. (Currently only disabled for sokoban crates, but recommend any other edge cases) This should make moving things like crates in cargo much easier now, so [qol] too.
:cl:
 * rscadd: All non-anchored structure objects (such as crates) can now push things in front of them when pushed, just like wheelchairs. An option is also made available to structures to toggle this behaviour on or off, with sokoban crates not inheriting this property.

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Doesn't this fuck up sokoban?

**Comment by kane-f** [comment]
> Doesn't this fuck up sokoban?

I could easily make a subtype of crate that ignores the to_bump stuff.

**Comment by ghost** [comment]
Not anymore, made this behaviour a boolean for allowing it or not and disabled it on sokoban crates @Apogee-dev

**Comment by Eneocho** [comment]
This has been needed for so long now, finally. Cargobros rise up.

**Comment by Eneocho** [comment]
You should probably blacklist shards too, so they ash items instead of pushing them.

**Comment by ghost** [comment]
> You should probably blacklist shards too, so they ash items instead of pushing them.

Shards are machinery, not structures @Eneocho

**Comment by Exxion** [comment]
I think this is a good system to have, but I'm less sure about making it default to on for all structures

**Comment by Armadingus** [comment]
Can you tell me how this interacts with conveyors? Because with how wheelchairs work now, this causes active conveyor corners to not have an effect.

**Comment by Kurfursten** [comment]
Please test with conveyors and report back

**Comment by ghost** [comment]
Conveyor corners still move crates properly when on but if the corner is off while the crates incoming on other conveyors are on, it pushes. That doesn't seem like as big of a deal though since conveyor corners clearly do have an effect @Kurfursten

**Comment by ghost** [comment]
> Can you tell me how this interacts with conveyors? Because with how wheelchairs work now, this causes active conveyor corners to not have an effect.

As said above, but now it seems wheelchairs are properly affected when I tested this.

**Comment by Kurfursten** [comment]
I will merge this experimentally and we will give it 2 weeks for opinions

Someone remind me of this on the 18th

**Comment by Eneocho** [comment]
Aight, I can remind you.

**Pull request merged**
