### PR TITLE
Adds and updates some fat uniform sprites, and updates the regular CMO uniform

### PR DESCRIPTION
**Pull request by DelaminatingShard**
Made new fat sprites for the following uniforms: Beekeeper, Botantist, Lawyer, CMO, Electrician, Engine Tech, Gardener, IAA, Maintenance Tech, Nurse Dress, Nurse Suit, Paramedic, QM, Librarian, Roboticist, and Virologist
Updated the following fat uniforms: Medical Doctor, Cargo Tech, and Warden
Also updated the west view for the regular CMO uniform (the cross was green instead of blue, only changed one pixel)
fatuniformsbig

:cl:
 * rscadd: Added new fat sprites for some uniforms
 * tweak: Updated some existing fat uniforms
 * tweak: Fixes the west view for the regular CMO uniform (blue instead of green cross)

### CODE REVIEW

**Comment by DelaminatingShard** [comment]
ew my preview image got messed up
fatuniformsbig

**Comment by Orangerush** [comment]
You actually did it you madman

**Comment by SkowronX** [comment]
Only issue I see is that cargo tech uniform needing shorts.

**Comment by DelaminatingShard** [comment]
They are shorts. Shorter, at the very least.

**Comment by ghost** [comment]
Down voted because some people have fat fetishes and they might fap to this nurses in dresses

**Comment by Orangerush** [comment]
The atmo tech one looks like one of the rugby shirts Chris chan used to wear

**Comment by small-boss** [comment]
there is not a big difference between atmos players and chris chan so it fits

**Comment by DelaminatingShard** [comment]
ackshully that's the maintenance tech's jumpsuit

**Pull request merged**
