### PR TITLE
Removed O hotkey

### LINKED ISSUE #18157: Remove the O hotkey
Think of all the ick ock that could be prevented.

### PR DESCRIPTION
**Pull request by DamianX**
Fixes #18157
I just followed the instructions in the linked issue and committed the result. There are many unrelated changes because DreamMaker decided this was going to happen.

:cl:
 * rscdel: The "O" key no longer opens the OOC chat window in hotkey mode.

### CODE REVIEW

**Comment by Accipitermaris** [comment]
wwawsdawsadawawsa

**Comment by ghost** [comment]
AAAAAAAAAAA

**Comment by Shadowmech88** [comment]
Is there no way to make this a thing players can toggle for themselves? I enjoyed being able to use the O key for OOC.

**Comment by DamianX** [comment]
Yes, just edit your local skin.dmf :)

**Comment by Shadowmech88** [comment]
Actually, I think it would be completely possible to make this a toggle. The O key calls the [OOC verb](https://github.com/vgstation-coders/vgstation13/blob/f72fecb701a91a944378edf4eb41dfdbe4a3934b/code/game/verbs/ooc.dm#L1). All you'd need to do is make a new verb which checks for the preference, and calls the OOC verb if the player has it set to allow the O hotkey. Then have the O key call that new verb instead.
That way it will do nothing for the players who have it turned of, it will work for the players who have it turned on, and both parties can still access the regular OOC verb anyway, same as always.

**Comment by Sooose** [comment]
Can't you just make a macro for ooc? I never understood why something so inherently dangerous was bound to the keyboard by default.

**Comment by praisenarsie** [comment]
just dont use hotkey mode

**Comment by PJB3005** [comment]
@Shadowmech88 that doesn't work, because you need the input box from the verb, so you can't have it toggle in code. The actual macro needs to be disabled.

**Comment by ShiftyRail** [comment]
Make it Alt+O or something instead of the dangerous O.

**Comment by Shadowmech88** [comment]
@PJB3005 
You mean you only get the message box if the verb is called directly by the hotkey, not if it's called by another verb? And even if the message were to be received by the new verb and then fed to the OOC verb as an argument, the box for the new verb would pop up before any checks could be made?

**Comment by nuklearcellphoneg** [comment]
qqqqqqzsdHello!

**Comment by PJB3005** [comment]
@Shadowmech88 exactly.

**Comment by Shadowmech88** [comment]
Would it be possible to have the hotkey call a new verb that takes no arguments, have that new verb call a proc that does the preference check and then gets the message via `input()`, then have the proc pass whatever's put into the `input()` as an argument to the OOC verb?
Or have the O key call such a proc directly instead of a verb?

**Comment by PJB3005** [comment]
`input()` has a bunch of problems such as *being input* so it blocks other input calls.

Seriously. The solution is to toggle the macro.

**Comment by chesse20** [comment]
no support

**Comment by Cyberboss** [comment]
on life support

**Pull request merged**
