### PR TITLE
Reverted the forcesay thing

### LINKED ISSUE #23218: DamianX fucked up hotkey "t" chat window. reee
(WEB REPORT BY: spcmn REMOTE: 206.221.180.138:7777)
# Revision
8f063522a32cf48e71908e333b16b4d5df91573e

# Description
Can't exit out of a window to delete chat. It re-adds the last typed up words to the new window. Cannot open multiple windows to type down diffrent things, because it remembers only the last things spoken, preventing multiple windows for chat. Using " more than 4 times breaks the type and makes it so you cannot use space afterwards
# Steps to Reproduce
Use the chat window

# What you Expected
"t" hotkey to work like it used too.# What Actually Happened
 It proceeds to don't work like it used to.

reee

### PR DESCRIPTION
**Pull request by DamianX**
reverts #23186
closes #23218

:cl:
* rscdel: Talking in hotkey mode is no longer terrible.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Do you know a way to fix the issue ? I assume you'd need to refresh the window

**Comment by DamianX** [comment]
Which issue? The linked thing has 3 of them

**Comment by ShiftyRail** [comment]
Was talking about the fact it keeps the words you typed when pressing T

**Comment by DamianX** [comment]
Yes, that's fixable as I've said in the issue. I'm not going to because of the other two issues.

**Pull request merged**
