### PR TITLE
Adds the sith bundle as a possible traitor bundle reward

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
[wip] [gameplay] [help] [needspritework] 

Adds the sith bundle. Not done yet, but it's here. Thanks @RealestEstate for making the sprites for the sith suit!
- Two energy swords that have to be combined into a double energy sword
- Palpatine clothes + sandals. Wear them all at once to be able to use the lightning spell. Plasmamen cannot wear them. Not yet.
- Binding spellbook to use on your double energy sword
- Lightning spellbook to demonstrate your infinite power. Deals half as much damage (25 burn damage) as the lightning spell. No different sound files yet.
- Telekinesis because you can use the Force too
- The jump mutation because Palpatine did a sick 720 degree spin in the air

Current iteration doesn't even work properly because the current torso clothing is a jumpsuit that does not count for wizard garb (and will be removed later)

- [x] Add proper clothes for Palpatine Junior;
- [x] Acquire sprites for proper clothes; Thanks @RealestEstate !
- [x] Fix double e-sword not activating;

:cl:
 * rscadd: Adds the Sith Bundle to the possible traitor bundle list! Contains two e-swords, unique clothing (thanks to RealestEstate), a bind spell, a lightning spell (deals 25 burn damage and requires you to wear the entire clothing set), a telekinesis injector, and a jump mutation injector. Shouldn't mean you should try your luck at it by playing roulette with the bundle though!

### CODE REVIEW

**Comment by Irradiation** [comment]
-If you can't make the double esword activate for whatever reason, just spawn 2 eswords and call it a day.

-There's a flag for clothing that decides if it's wizard clothes. You could make a child of the used jumpsuit that has the Wiznerd flag.

**Review by MadmanMartian — APPROVED** [review]
I'd say drop its roll chance by half, because this is real good

**Comment by boy2mantwicethefam** [comment]
People are definitely going to start buying bundles just for a chance at the sith bundle and probably end up getting poor things, so I say the current weight is fine, but it will be tweaked after people no longer wanna urgently give it a try AKA maybe a few days or a week if the PR gets merged. For a while I considered giving it a far larger weight for a few days but then I thought maybe people will get tired too soon of the sith bundle and there are people that wouldn't wanna necessarily have the sith bundle, instead they want another bundle

**Comment by ghost** [comment]
This is cool
can I add a random suggestion to do with bundles: 
I don't think they're picked very often, and one of the things is there's currently 16 things you're rolling for and that seems like a big game of chance.
What if instead of rolling on each and every bundle when you press the button, each round picks 4-6 of the bundles (maybe using some sort of TC worth weighting? I don't know) and then lists the ones available you can roll from on the [?] text of the bundle. This way it might prompt some people to give it a roll, if one of the fun ones is up, they can give it a shot to try it out. Might also make it so we can make some more bundles and stuff without "bloating" it.

**Comment by DrSnips** [comment]
I'm not sure if I like spell books in syndi boxes it just seems wrong. Power gloves would work to replace the one spell and the bind spell is kinda useless since throwing the esword would do nothing even if you threw it and it was active some how. TK is fine since it's not actual magic.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Basically the above, Siths TK yank their eswords back not teleport them

**Comment by Durgen** [comment]
has anyone ever rolled for a decent bundle in the history of bundles

**Comment by boy2mantwicethefam** [comment]
It's ready

**Comment by boy2mantwicethefam** [comment]
Nevermind do NOT merge yet, icons are accidentally overwritten and several icon changes from the repo have been deleted with this PR

**Comment by boy2mantwicethefam** [comment]
alright, NOW it's ready

**Comment by boy2mantwicethefam** [comment]
NOW NOW it's ready

**Comment by boy2mantwicethefam** [comment]
TRIPLE NOW it's ready

**Pull request merged**
