### PR TITLE
Railings

### PR DESCRIPTION
**Pull request by ghost**
[content][sprites]
image
image
image

## What this does
Adds railings, table-high structures that work like window border objects but without the ability to place objects on them.

## Why it's good
Decoration, plus a border object that can be passed like a table is nice.

## Changelog
:cl:
 * rscadd: Railings can now be constructed with 2 metal, plasteel or wooden sheets, for different varieties. Any item that can pass through tables can pass through these, and they also work as cover for bullet fire in a similar manner while lying down. Adding wires to them with a cable current passing underneath will cause anyone who bumps into them or tries to jump over them to be shocked. Adding glass to them can be done for extra decoration and reinforcement.

### CODE REVIEW

**Comment by Eneocho** [comment]
add a gate for muh rancher gimmick

**Comment by Kurfursten** [comment]
Very nice, I will want to rebase wild west to use those wooden ones

**Comment by Optimism333** [comment]
I like it a lot, hope to see more generalized structures/obstacles expanded on at some point.

**Comment by Hinaichigo** [comment]
Horseback-riding when.

**Comment by WindowsErrors** [comment]
is this gonna be like old minecraft where there were fences but there weren't fence gates yet so you had to put a normal oak door as the gate for a fenced area

**Comment by Eneocho** [comment]
And he didn't add a fucking gate. We ARE like old minecraft now. Wood fences but with airlocks.

**Comment by Kurfursten** [comment]
wyci

**Comment by Eneocho** [comment]
More like when you sprite it, you can just reuse metal doors code.

**Pull request merged**
