### PR TITLE
New combat borg sprite

### PR DESCRIPTION
**Pull request by Lokiamis**
The Bloodhound's edgier brother, the Rottweiler. It's a TG syndiborg sprite that I slapped a shield and movement state (which hasn't worked for at least 4 months but whatever) on. Let me know if it's _too_ black.

untitled

https://webmshare.com/LjVge

:cl: 
 * rscadd: Ported a combat borg sprite from TG

### CODE REVIEW

**Comment by Ephx1** [comment]
Is there a separate overlay for the eyes?

**Comment by Aurx** [comment]
Too much black in similar shades.  There's no detail to it, it's just a black blob with red eyes and some grey bits.

**Comment by Lokiamis** [comment]
@ephx1 Yes, although the movement module has them fixed on. 

@Aurx I thought so too, but I wanted to weasel out of doing extra work. Tomorrow I'll touch it up unless the emojicracy isn't crazy about it anyway.

**Comment by Lokiamis** [comment]
Or maybe I won't touch it up?

**Comment by Ephx1** [comment]
Yeah that was oddly quick for a merge

**Pull request merged**
