### PR TITLE
Fixes wolf grammar

### LINKED ISSUE #25222: Wolf Attack Logs Are Gunked
ADMIN LOG: NAME (CKEY) ordered **a wolf a wolf** to attack Unknown **with WOLFNAME** (INTENT: HELP). 

Instead it should say 
>ADMIN LOG: NAME (CKEY) ordered a wolf (WOLFNAME) to attack Unknown.

### PR DESCRIPTION
**Pull request by Goldsteel**
[grammar]

Title

Fixes: #25222 

:cl:
 * bugfix: Wolf attack logs are corrected from 'a wolf a wolf' to just one wolf.
 * bugfix: Attack logging for wolves should work now.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I see, due to how the attack logs are set up there's no easy way to change the 'with WOLFNAME' being at the end where it is somewhat confusing

At least the repetition is solved

**Comment by Goldsteel** [comment]
It seemed to work find when the wolf had a name at least.

**Comment by Kurfursten** [comment]
It's not that it doesn't work, it's just that it sounds somewhat unclear the way that it's phrased, e.g.:

>Goldsteel ordered a wolf to attack R0b0 with Frost

what is a Frost?? oh that's the name of the wolf appended at the end of the log for reasons

**Comment by Goldsteel** [comment]
I've started pulling this apart more to make it more coherent. Currently it just spams the admin logs with "[16:34:38]ADMIN: A wolf is attacking a target, *no key*/(Test Dummy), their alpha is: Goldsteel/(Grug Unga) @(152, 256, 1)" which is awful, because it's in the attack logs anyway. I think I fixed the grammar problem.

**Pull request merged**
