### PR TITLE
Waystation - rePacked Station

### PR DESCRIPTION
**Pull request by GeneralVeers25**
This is the first PR for the WIP "Terminal Twelve" map I am designing to replace Packed Station.  I hope to address the flaws of Packed that players highlighted in the recent survey while staying relatively compact for low-pop. The station is designed to emulate a spaceport, with seedy back alleys and a large central terminal served by the bar and kitchen for passengers waiting for the Escape Shuttle. Security, serving as customs and border inspectors, watches vigilantly over Cargo and those perfidious Vox Smugglers.

Renders below.

The Station:

terminaltwelvePRrender3

The Asteroid (yes, it is just the current Packed Roid, sue me): 

terminaltwelvetoproid
terminaltwelvebottomroid

[general] 

:cl:
 * rscadd: Adds a new map, Waystation, to fill the low-pop gap left by Packed Station.

### CODE REVIEW

**Comment by SonixApache** [comment]
mark as draft or tag as DNM if you don't want it merged

be sure to load it up on the test serb so we can get some fixing done

on a quick look-around i noticed; 
ghetto botany is across the station from the ghetto kitchen, missed opportunity
toy femsec space hole could be replaced with more secure armory space which would make everything less cluttered -- hell, could throw the suit storage units in there, and change the suit storage section into a laundry/break room
in primary tool storage the welding fuel tank isn't directly accessible, you have to swap around the silicate tank first - should fix that as it slows down antag assistant speedruns
red doors in the security lobby will make it weird to find cargo
transparent maint doors make me sick
wiring to the main AI sat through the MoMMI nest is a weird choice, would separate the connections personally

**Comment by ShiftyRail** [comment]
Is Sacha meant to be in the cell ?

**Comment by Eneocho** [comment]
By looking at the render, it still feels a bit on the larger side to be a good replacement for packed. Packed is very, very tight. This feels like a redesigned box (sizewise). Still, good shit. New maps are always welcome.

**Comment by Apogee-dev** [comment]
> toy femsec space hole could be replaced with more secure armory space which would make everything less cluttered -- hell, could throw the suit storage units in there, and change the suit storage section into a laundry/break room

I'm pretty sure the femsec space hole is for security, one r-wall is definitely not enough for secure armory without a space gap. Two might not be enough without space either honestly.

> transparent maint doors make me sick

Most of "maint" on this map is public access, they aren't maint doors because they don't actually have maint access

all of your other points are good and i agree with them but i actually like the back alleys idea, it's neat

**Comment by Eneocho** [comment]
A few thoughts: 
-For the love of all that is holy, please, PLEASE move the botany machines to hydroponics mainroom, to keep with packed and synergy's style. It helps a lot.
-I'd replace the bottom wall next to the QM's door with a window.
-Add some of them recently merged Sacid tanks. Even a lone maintenance tank would do, but one for engi and or science would be welcome too.
-Try placing some of the vending machines, the more exotic ones, like Nuka Cola, Offworld Off-License, Circus of Values or the Barbervend.
-The Theatre is too secluded, right at that corner by the dorms, consider moving it a bit closer to the core.
-Consider making the shard room smaller, core included, to encourage different shard setups instead of a standard one.
-Same with the TEG room.
-More floorpill spawners please.
-The windows and blast doors to protect the spacesuits in EVA feel a bit much
-Engineering storage feels really outta place in the seedy alleys instead of near engi.
-Having the AI core isolated by space really discourages Law interaction with the AI and borgs, both by normal crew and antagonists, consider making a direct connection too.
-Honest thanks for not falling for the layered vents meme.
-Please move the vault somewhere else or add an entrance from outside the bridge.
-The AI restoration console on the RD office is inaccessible due to the table.
-What's the reason for those tanks to space under sec?
-If you could somehow make the seedy back alleys' lights blink every now and then for that extra seedy feel, that would be great.

**Comment by Kurfursten** [comment]
>Try to add roundstart acid dispensers
>Fail
>"Okay, we'll just make them orderable from cargo in a locked crate"
>A MERE TWO DAYS LATER
>"We should make these available roundstart in maintenance, engineering, and science"

So this is how the creepclub operates

**Comment by Apogee-dev** [comment]
> add acid dispensers

please don't. the roundstart acid PR failed for a reason and that's because in retrospect it was a terrible idea. let people hike to cargo if they really need it.

i'll second the bit about the AI core though, Meta has an AI sat but it's accessible via shuttletubes. Consider either adding tubes here or making the walkway to the AI ship an enclosed walkway so you don't need to spacewalk just to get to upload or telecomms.

**Comment by BomberBro** [comment]
That perma is laughably easy to escape from. Shardkick the window behind the chair, shardkick the EVA window, grab suit+ tank and leave

**Comment by Optimism333** [comment]
> -Having the AI core isolated by space really discourages Law interaction with the AI and borgs, both by normal crew and antagonists, consider making a direct connection too.

I find myself agreeing with this too. Also, correct me if I'm wrong, but given the way the two secure airlocks are placed (in the upper center of the glass hallway), won't opening those doors depressurize the reinforced glass hallway and/or the cyborg recharge station?

Addendum: The same criticism seems to apply to the little room in the upper left corner (presumably for mommi use). It's odd to have a single airlock there that looks like it just exists to depressurize the interior if opened.

**Edit:** I do love the concept of the bar and kitchen being next to evac like a terminal. +1 for that idea

**Comment by SonixApache** [comment]
@Apogee-dev
> I'm pretty sure the femsec space hole is for security, one r-wall is definitely not enough for secure armory without a space gap. Two might not be enough without space either honestly.

I see your point and agree that double walls are good and that it looks nice, but I still think that filling in the void there to move the suits would be a better option. Could just go with double walls rather than space.

> Most of "maint" on this map is public access, they aren't maint doors because they don't actually have maint access
> all of your other points are good and i agree with them but i actually like the back alleys idea, it's neat

my issue with that is the schizophrenic way the 'back alleys' present themselves
image
I understand the "door into maint" part of the little shop, but why have glass-door maint corridors that are interconnected by opaque doors? Why connect it to departments with opaque doors as well? Why public maint in general, didn't we run those experiments already? It's a very weird concept to me.

@Optimism333
MoMMI nests are known to have single airlocks that ruin the atmosphere of everything inside. Nobody knows why there's air in those things in the first place, since humans aren't ever supposed to go in them anyway. Maybe one day someone'll fix that.
The sat in general depressurizing when you open the door isn't that big of an issue since you need a suit to get there in the first place. Note how there isn't a single air vent or scrubber on the sat - it's intentional.

**Comment by west3436** [comment]
>need to spacewalk to get to telecomms
>void suit is on the sat rather than on the station
what the fuck

**Comment by GeneralVeers25** [comment]
Thanks for the feedback everyone. I've made the following changes:

Perma has been strengthened and shouldn't be easily escapable now.
The particularly seedy/empty back alleys have been given more plating, some vending machines, and better lighting to distinguish them from the other maintenance tunnels. And yes, some of those lights flicker.
Missing lights/cameras/APCs have been corrected. A few firelocks have been added as I've seen them too, but that's by no means complete and I'm sure a few are still missing.
The AI Core has been connected to the station. The MoMMI nest was moved and replaced with the Cyborg Station, which serves as an anchor tying the AI/Telecomms to the rest of the station via an enclosed walkway. The AI areas are now pressurized as well.
Ghetto botany has been moved to be closer to the kitchen. 

An updated render is below.

terminaltwelvePRrender2

To address some of the other concerns:
All of the consoles in the RD office are functional, I just tested them.
I was already told to make the SME/TEG bigger, so there's no way I'm shrinking them for no reason. The station is smaller than Box and pretty comparable to Packed in size. Here's the holomaps for both stations as an example.

Packed:
packedholomap
rePack: 
holomap

I'm pretty happy with the Secure Armory and believe it would be far too vulnerable without the space cubby. 
I wasn't able to re-arrange Botany in a way I was happy with so I left the machines as-is but I'll keep thinking about it.

**Comment by Eneocho** [comment]
>I wasn't able to re-arrange Botany in a way I was happy with so I left the machines as-is but I'll keep thinking about it.

You could shrink the botany backroom by one tile so it's a 4x2 rectangle so you can place the machines right outside it, something like this:

image

Also, can you please paint the tiles in the green areas with dark?
These ones:
image

Finally, what's the purpose for these tanks outside sec?
image

**Comment by SonixApache** [comment]
render doesn't show the welding fuel tank being changed
security lobby doors still red, cargo still mad
perma is still stupidly easy to escape from
mommi nest should be elsewhere to deter carbons (box is as always the perfect example)

good tweaks for the rest

**Comment by GeneralVeers25** [comment]
That's not a bad idea for botany, I'll see what I can do. Easy to paint the tiles as well.

Those tanks are CO2 tanks. For flavor, since the station is a spaceport, they're named "Starship Fuel"

The fuel tank is changed, it's just not on the render. See the "nooo my heckin roundstart welderbomberinoooo" commit.

The Perma windows have reinforced girders under them. They're not easy to escape from.

I'll think about it but don't believe it'll be a problem.

**Comment by Eneocho** [comment]
>Those tanks are CO2 tanks. For flavor, since the station is a spaceport, they're named "Starship Fuel"

Guess they can also be used for surprise CO2 floods since it only takes 7 pipes to connect to distro (since most wouldn't have a socket wrench).

And thanks a lot for the botany stuff. It truly helps a lot.

**Comment by GeneralVeers25** [comment]
terminaltwelvePRrender3

Another updated render. As requested, Botany has been rearranged. We had a round of testing, and some missing/broken elements (like the research shuttle and unpowered mining outpost or backwards shutters) have been corrected. I have also gone through and checked for firelocks, and while I'm sure a few may have eluded me I believe I got most of them. The CO2 tanks have been replaced with empty pressurized tanks.

Xenobiology has also been expanded from the old Packed outpost:
xenobio

Edit: I should add that I'm settling on naming this spaceport-themed map "Waystation."

**Comment by Eneocho** [comment]
>The CO2 tanks have been replaced with empty pressurized tanks.

I actually kinda liked the possibility for a CO2 Flood as non-engineering staff. Bummer.

**Pull request merged**
