### PR TITLE
Push the Boxstation bombing range 30 tiles away from station

### PR DESCRIPTION
**Pull request by ghost**
Pretty explicit
- Added a bunch of extra repeating catwalk/lattice tiles leading to the bombing range, totaling at exactly 30 tiles in length from first to last catwalk
- Cleaned up a weird wall pattern near the middle of the catwalk

This should make sure that even a decent bomb like 7, 14, 28 doesn't damage the observation post anymore. Even larger bombs might fuck it up still, but only light instead of being able to demolish eastern R&D

### CODE REVIEW

**Comment by CptWad** [comment]
9 dev damages the station, 7dev never has
7dev is bombcap 
how many tiles did you add? I know its 20 total but what was it before

**Comment by ghost** [comment]
I'm pretty sure I added a large amount of tiles

To get 30 tiles of space between the first and last open tile, I had to add roughly ten to fifteen tiles

So it should be significant

Also yeah, my calculation is the opening message is wrong. It's actually half that value, so it would need something as huge as a 15, 30, 60 to start damaging the observation post

According to that too, old bomb damage range was 9, 18, 36. So it was 18 tiles before, I would have added 12 tiles

**Comment by CptWad** [comment]
Okay so theres 12 more tiles between the blast doors and the mass driver
did you reprogram the blast doors to stay open long enough for the bomb to get in?

**Comment by ghost** [comment]
Er

**Comment by PJB3005** [comment]
...

Did you test it at _all_?

**Comment by PJB3005** [comment]
ALSO FUCKING NON BOX MAPS GET SHAT ON AGAIN.

Fucking fix the other maps too.

**Comment by ghost** [comment]
Fun fact : The bomb range is at a respectable distance on all maps that aren't Box (Taxi flat out doesn't have one, go ask abumblingidiot)

I'll give it a test when I have spare time

**Comment by ghost** [comment]
I can confirm that a 7 dev bomb does in fact damage the observation post as it is. But it only breaks a single wall that doesn't cause a breach, so the distance to station is a non-issue on box at current bomb cap.

The real issue with the test range is the fact that it becomes unusable after a few tests due to bombs flying through it into space since there are no walls to block them. Also the cameras get destroyed after the first bomb.

**Comment by gbasood** [comment]
I'm not sure that we can resolve the test range becoming unusable. Could turn the windows on the east side into rwalls to make it more durable I guess?

**Comment by 9600bauds** [comment]
Obviously give it a fridge, NT construction standards would be as such

**Comment by gbasood** [comment]
Toxins test: Put a bomb in a fridge with Ian, see if he lives

**Comment by ghost** [comment]
Good idea with the fridge, if you'd put one in the middle of it where bombs stop, it would prevent bombs from leaving into space.

**Comment by PJB3005** [comment]
TG has an undestructible riveted wall on the bomb range.

**Comment by 9600bauds** [comment]
Obviously a fridge makes more sense

**Comment by clusterfack** [comment]
Whats the point of an indestructible bomb range?

**Comment by 9600bauds** [comment]
Not the whole range of course, just one doorstop to prevent the bomb from flying off the z-level.

**Comment by ghost** [comment]
@PJB3005

It makes for a great place for blobs to hide behind.

**Comment by LordMyroc** [comment]
Why not add a bhangometer to the science outpost so scientists can test their bombs there? Asteroid floors don't get destroyed by bombs if I remember correctly.

**Comment by ghost** [comment]
@LordMyroc But miners do

Which would be extra hilarious

**Comment by ghost** [comment]
Too lazy to fix, shiet

**Pull request closed without merging**
