### PR TITLE
containment fields no longer shock through windows/border objects

### LINKED ISSUE #6537: Glass doesn't protect from Containment Field
Made a singularity containment with a thin glass pane to avoid accidental cuddles with the field, but looks like it didn't work at all.

i m not misbehaving

Kinda counter intuitive for the field to affect through materials, unless that's how they work.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #6537

### CODE REVIEW

**Comment by CptWad** [comment]
I dunno this might have unintended consequences

**Comment by 9600bauds** [comment]
> this might have unintended consequences 

When you make a statement like this you really need to give an example at least

**Comment by Probe1** [comment]
Seems like a reasonable addition.

**Comment by clusterfack** [comment]
Seems fine to me

**Comment by Probe1** [comment]
WAIT THIS DIDN'T HAVE PNG OF 100% TESTED APPROVAL OH NO WE'RE DOOMED

**Pull request merged**
