### PR TITLE
Dorfstation Map Initial Commit

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[general] [qol]

As a general attempt to make Dorf rounds less painful, this map is equipped with a barebones station modeled on the Boxstation Mining Outpost. It should contain everything needed to get a fully functional station set up.

The crew spawns on Z-Level 2 at Central Command in a special shuttle with a one-way Gateway that will take them to the outpost on Z-level 1. The shuttle they spawn in on Z-Level 1 doubles as the Escape Shuttle for the end of the round. Both the teleporter and the shuttle have been tested and should work without issue.

Z-Level 3 is currently empty except for the DJ Satellite and Salvage Shuttle. It has been left blank for further modifications - such as a derelict station for the crew to loot - in later PRs. All three Z-levels are 300x300 instead of the usual 500x500.

The Outpost:
DorfFinal-2

The Roid:
Dorf

The Spawn:
DorfSpawn

Much of the credit for this map goes to the Anon in the thread who put together the Spawn and Roid. I am simply building on his work.

:cl:
 * rscadd: Nanotrasen's latest space station is under construction. Sign up now - STRIKE THE EARTH!

### CODE REVIEW

**Comment by DrSnips** [comment]
I'm not going to beat around the bush. The roid looks like testicles.

**Comment by FudgePucker** [comment]
@DrSnips it's a feature, you can build engineering away from the rest of the station by putting a long hallway right in the middle

**Comment by utilitas-** [comment]
I strongly object to giving players such a well-equipped starting station. Starting them off with nothing but literally the barest essentials may be going too far - but what you have given them is a fully fledged, fully functioning station. They have no need to expand if they already have everything they would ever need - and besides that, just _expanding_ rooms instead of outright building new ones is infamously difficult, so it would remain crowded for all time. I would suggest starting them off with one or two rooms, shuttle included, with plenty of supplies to get them started and only some basic machinery, as well as plenty of spots to expand. Giving them a pre-established station is going to result in that same station being only minorly improved again and again, which I find boring.

To expand on that, our current building tools are quite limited and clunky. Building is a chore, and building en masse is an even more time-consuming and unegaging chore. I would take inspiration from https://wiki.ss13.co/Construction_Game_Mode and its various tools, which include pre-planning and more advanced blueprints. Those could be expanded on with our RnD system by researching even more advanced tools that would, say, auto-construct set down blueprints without the player having to lift a single finger beyond filling the hopper with materials and minerals. But perhaps the greatest issue with building are areas, and how fiddly they are when you are trying to expand. While dispensing with areas completely would be the simplest solution, it would rob people of autisming over power - and who'd want that? - so I'd suggest improving on our current area designation system and adding colour-coded area visualisation, remotely defining areas by floors/walls without necessary air-tightness, defining areas by dragging out rectangles (kind of like the horribly broken beacon designator) and by overriding pre-existing areas without needing to endlessly fiddle with individual tiles.

I also believe there may be merit in splitting up people between different z-levels, or at least having various different variations of the dorf map so it isn't just the same permanent 'roid. Even twenty people in a cramped little station can get hectic, though less so with a bunch of random crap pulled from the station cluttering the way; the load would be lessened if you could split them among z-levels. But all that heavily depends on how many and what kind of people are going to play it and, most importantly, on which server it will be hosted. I believe that you shouldn't sike dorf mode on the main server simply because not everyone is going to be in for it. Dorf mode should be hosted on a second server, likely the test server (which is used for group testing only anyway) and hosted _long term_ instead of the three hours stints that dorf mode were so far. If it will be hosted on a secondary server, I would expect fairly low, but highly dedicated population (interspersed with the occasional griffon). On the main server, you cannot expect anything but 30+ swathes of highly unsuited and deathly bored people with the occasional man of the station who actually does something, and even there splitting people up may be too much.

I'd also suggest implementing per-map min/max vault variables. Currently the number is somewhere between 15 and 30, I believe, while this sort of map deserves a much greater amount of more varied vaults, ones that would also include plenty of diverse valuable vaults (some of which could even be potentially reclaimed) similar to the ones I've uploaded. The current repertoire of vaults is just plain shit. But that would require more per-map configuration. Making it 300x300 instead of 500x500 may change that, but not by much.

t. faggot who made the initial map

**Comment by DrSnips** [comment]
The hell are you talking about with "its a full station" its literally just a mix of some mining outposts with a RnD lab to the side for machines and tools. Medical is a sleeper and a MOT and doesnt even have tools for a good example. While building is the idea of dorf you have to give it some flavor above a metal cube so an outpost to start is good for the theme.
The rest of your post looked unrelated to mapping so tldr.
One issue I see is a lack of suits since theres no way to get more besides mechs technically.

**Comment by kilozombie** [comment]
Add some dangerous, lootable abandoned outposts for things like hardsuits. Mark them on an ingame map as a sort of diagetic way of indicating that there are resources there.

**Comment by utilitas-** [comment]
\>18 rooms including hallways
\>reliable power source and mineral processing
\>complete, fully fledged RnD
\>fully functional infinite O2 supply
\>a bar and dormitories
\>an EVA
\>cargo
Literally the only bit missing away from being a complete self-sufficient station is a hydroponics, and that is a few clicks and two minutes of cargo shuttle wait time away from being squared away. _Fuck off, Snips._

A few barren rooms with basic supplies would be good. Heck, a few unanchored/disassembled RnD machines. But this is too much. There is no need to expand and worse, nowhere to expand from organically without making the outpost look like shit by extension. Adversity drives innovation. Give them a reason to expand.

**Comment by Kurfursten** [comment]
>floating fire alarm in R&D
>only exactly one RC console, so it can't actually request from anyone

**Comment by N3X15** [comment]
We need an overhaul of the game itself before this becomes viable.  Lighting and parts of ZAS are tied to areas, and we start getting MASSIVE lag when areas are changed.

**Comment by FudgePucker** [comment]
Would breaking up the asteroid into multiple areas reduce lag?

If the reason lag is bad is that it is a huge area that has to update every time you change it, wouldn't breaking it up into smaller areas work? Or would the zas calculations make it worse off when the area isnt being changed by blue prints?

**Comment by DrSnips** [comment]
@utilitas- 
I can agree that RnD is a bit more stocked than it should like metal, glass, and misc parts to start.
Since you clearly just blew in from stupid town I'm going to go over your points.
-Saying you shouldn't have a pre stocked RnD and no mineral processor because without at least one of those being fully functional neither works.
-Power is only a single smes(starting charge not given) and won't last forever so you're wrong by calling it reliable.
-How else are you supposed to get O2 then? Gas miners can't be made nor can you just create O2 in large enough amounts to fill new rooms which is the whole point here.
-Well no shit there's an EVA where else would mining suits be held to get mats?
-While the dining room and dorms aren't necessary they had at least some character to it.
-If its not from RnD it has to come from somewhere. Cargo need to have admin intervention to set up afaik and if this is to be played reliably for extended periods of time admins can't be relied on 24/7.
Most of these things go against the whole idea of dorf and show you have no idea when it come to designing this. Now its your turn to fuck off.

**Comment by GeneralVeers25** [comment]
I've updated this to address some of the concerns here. R&D and the starting station in general is less well-stocked and I have reduced the power in the starting SMES to encourage people to get to work immediately.

The goal of this PR is just to get a Dorf map up and running. Outposts buried in the roid and other goodies can come later, as can adjustments to the starting equipment. I want to make this as flexible as possible so different admins can adjust the 'difficulty' as they see fit.

**Comment by utilitas-** [comment]
You know they won't. Why adjust anything when it's set out in front of you? Just like antag datums were heralded as the saviour of /vg/, when admins could finally easily assign antagonists without bias and giving out custom roles would be a breeze.
Nada. Just fucking dynamic.

**Comment by Kurfursten** [comment]
Dynamic does do those things though. It's not even a comparison, someone who isn't an admin can't understand. Before if we wanted to send a new antag we would have to effectively announce something was going on by saying AHELP FOR FUN. And then you almost have to get people to agree upfront to be bussed for anything - no way to view preferences (there was a highly arcane technique of VV into their player client then prefs and knowing the values of many flags but this was incredibly obscure and no one did this) to see what people WANT to be. So if you ahelped for fun but hate cult but the admin wants to bus cult, tough titties: you now KNOW that the admin is bussing cult so you can't back out or you have metaknowledge.

Also you misunderstand what Veers is saying: he's arguing "I just want to get a basic design down and I can PR changes to it later". That's not a very good argument though, we should just do it right the first time. There's no rush, we've been dorfing for years already with no dedicated map.

**Comment by GeneralVeers25** [comment]
I don't have enough personal experience with Dorf to adjust the map now without it seeing a few good stress tests.

So yeah, I agree we should try to get it right on the first try, but I want the sort of feedback that only comes from letting the map get trampled in a proper Dorf round.

**Comment by utilitas-** [comment]
Then why do we still get admins going "pray for fun" if it's so easy? Jeb turned me into el vampiro after I prayed one or two months back. I think I even had vampire set to never, but that's probably untrue.

There is no "getting it right" the first time because no-one knows how to do dorf "right". All I know is that the way it has been done so far is fundamentally wrong, and I'd lean more towards the _from nothing_ approach rather than _renovating what is already there_ approach.

**Comment by Kurfursten** [comment]
When admins say "pray for fun" it's because they want to bus something that isn't in your preferences. For example, if you wanted to send abductors or something, there's no preference to know who'd want to do that.

Anyway, on topic: I disagree. I think we have learned a lot about dorf over the years from doing it - particularly people like Dorms who have been its loudest supporters. And there are objectively wrong things in the screenshot, like what I already mentioned - the floating fire alarm, random RC console, and even the cash register. There are other things too, which I think are less objective: like, for example, there needs to be an external airlock leading to the north side too, and there should be a roundstart labor console. Those are less clear, though.

**Comment by utilitas-** [comment]
Has dorf been done in any other way than "get a bunch of shit from the main station, cart them to the mining outpost then build from there while the main station gets annihilated by meteors"? Because there are many other ways to do it, ones that do not involve any mining outpost whatsoever. Which is something I've tried to encapsulate in my prototype dorf map, with each z-level having a fundamentally different embark.
I've played on a /vg/code-based dorf-type server hosted by /egg/, and that started from a single (large) shuttle in the middle of space with supplies and a cargo shuttle. It was pretty successful until the singuloose.

**Comment by ComradeDispenser** [comment]
What it needs 
>cargo dock with console to order crates 
>mining processing facilities 
>basic R&D with stuff to make circuit boards so new machines can be made from scratch 
>maybe combine R&D and mechanics into one cramped workspace to encourage them to spread out 
>also put the only chem dispenser here
>bare bones medbay with little more than a scanner, cloner, a single cryotube and macrowave, a sleeper and an operating table with barely any room to walk around
>security checkpoint by entrance to function as an incredibly small micro-brig and also the HoP office because that's where the ID console should be
>large empty "warehouse" space so brainlets can start building without needing to mine and make all new rooms from scratch (so people like botanists and chefs and bartenders can get to work designing their workspace immediately and not need to either set up in hallways or shove into cramped preexisting rooms)
>could be powered by portable generators and rely on engineers to totally build their own engine room from scratch 
>basic and cramped, minimalist atmos workspace 
>a good supply of wire coils since I don't think miners can make those from raw materials?

Nothing should be ideal working conditions for anyone, and especially the bar and chapel should not exist at round start, giving the bartender and chaplain complete freedom to design their lair. 
Just my thoughts on what a dorf map should be like.

**Comment by DrSnips** [comment]
I'd have to disagree with a few if those items. Going top down.
* Im on the fence if cargo should exist or not. A lot of critical items to do stuff come from it and would be healthy since cash from mining turns into more station expansion stuff.
* RnD shouldn't have q whole machine but rather just have 100u s.acid (2x 50u beakers in case they spill the first sol if they spill the second) to work with and if they fuck that up then sol.
* Mechanic shouldnt exist at all because that can be made later via rnd and serves no use early on with no pre-existing machines.
* That's way too much for med. the stuff in the op looks fine.
* While I don't think there should be a starting brig an ID console is needed.
* Just no on a large existing empty box. The station should be the very bare min. to get moving and required stuff to expand with. Also secondary roles like bar, bot, and chef have to face the facts and sit to the side while actually required roles do their job first. The break room is more than enough if you as me for all 3 roles.
* that brings up a good point. If not via cargo how do engies get a real engine? A few PACMANs could handle a tiny station I guess.
* As long as a gas miner exists atmos should be built rather than already existing.
* Cable comes in eletrical maint crates which is one of the most bought things from cargo due to glubs. I wiuldn't be worried too much about cable.

**Comment by Probe1** [comment]
This is the initial commit. We can refine it for all time.

**Pull request merged**
