### PR TITLE
Stun papers can stun mechs.

### PR DESCRIPTION
**Pull request by ShiftyRail**
As requested by @iFlashYou 
I'm indifferent to the change itself, I just wanted to code something simple and to feel useful

:cl:
- tweak: You can now use a stun talisman on mechs, which stuns their occupant for a short duration.

### CODE REVIEW

**Comment by jknpj** [comment]
Memes are getting too far

**Comment by ghost** [comment]
There's already emp runes against mechs.

**Comment by iFlashYou** [comment]
>weak ass emp doing anything to mechs

lmao

@codeungabunga just tested it, you need 11 emp runes to kill a durand

**Comment by SirSkeleto** [comment]
i have tried using emps against mechs
it does not fucking work
i wrote 4 pulse runes on the floor and it didn't do shit
also, fun note, pulse runes do the exact same thing as talisman as on the floor.

**Comment by soyconsumer** [comment]
Based, fuck science

**Comment by Accipitermaris** [comment]
i think instead, emps (this being a separate issue from ion rifles which are their own deal) should be buffed to do ... something against mechs (i once lobbed a box of emp nades at a mech which is a heavy pulse and nothing seemed to happen. and that's a heavy emp pulse! i believe the cult ones are light emp pulses.)

that & remove phazon cheese in a way that doesnt muck up the derelict & stuff

**Comment by strawberrytan** [comment]
What if similar to robotic limbs having a chance to have their function shut off until a reboot, a mech has a chance to lose access to specific modules or movement until it's rebooted from maintenance mode?

**Comment by MercuryDoll** [comment]
> emps should be buffed

This. The only thing EMPs currently do is damage/blow off robotic limbs and disable APCs and open airlocks for a short while. People have been complaining about the EMP's effect on borgs being laughably short too. Unless specifically outfitted with special shielding, EMPs should be the go-to for disabling **any** electronic equipment, which includes computers and robots.

**Comment by DrSnips** [comment]
I think making the emp do more to mechs would be a better solution.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Although I can confidently say fuck mechs, it'd be more sensical to buff the EMP rune against mechs than to make stunpapers The Emag Of Cult and keep the EMP rune useless against mechs anyways

**Comment by ShiftyRail** [comment]
Buffing EMPs against mechs is also viable, although I'm not sure what numbers to use since I don't usually use EMPs against mechs (I run and hit them with lasers with backup or just use a flashbang)

**Comment by KingofHONK** [comment]
despite making up only 13% of the weapons on station, EMPs account for 0% of total silicon and mech deaths.

**Comment by SonixApache** [comment]
this is some silly shit

**Comment by Caboozles** [comment]
Just make the battery drain for EMPs much larger. 
And variable between the rune and paper form.

**Comment by GoodG1448** [comment]
What about instead of stunning the mech, make EMP talisman **_temporary_** blind the mech user while inside the mech (by shutting down the exosuit interface) and drain the current cell by 25%.

**Comment by ghost** [comment]
I don't see why you should be able to counter a mech that took half the shift to get with one click of literally the most basic cultist item.

**Comment by aceedex** [comment]
Bruh
EMP talisman bruh

**Comment by iFlashYou** [comment]
>when people that never played cult start to talk some shit about emp runes and how mechs should be immune to blood magic

Edit: New test, now it took 9 emp talismans to destroy a durand

**Comment by ghost** [comment]
@iFlashYou 

Then perhaps EMP should be buffed against mechs instead of trivializing cult vs mech engagements? You're also not accounting for the navigational difficulties that result from mech being hit by EMP, which require calibration.

**Comment by aceedex** [comment]
> when people who play a game mode powercreep the fuck out of it

**Comment by Caboozles** [comment]
I don’t know if the DAMAGE of an EMP should be buffed. Buff cell drain above all else. If it took only 4 runes to destroy a full durand then holy shit there would absolutley need to be some module that could counter that. Durands are slow, get their own unique form of damage from EMPs, etc. Cult should not get a totally unique way to scrap-heap a combat mech in less than 5 seconds.

**Comment by Blithering** [comment]
I would say buffing EMP _runes_ damage against silicons would be a good idea, but not all EMP sources. Make it into a proper anti-tech rune

**Comment by GoodG1448** [comment]
What about EMP talismans blinding the mech user for 4-5 seconds (user can still use modules) and EMP rune blinding the mech user for 8-10 seconds plus 25% cell drain? (mech modules can be used aswell).

**Comment by DrSnips** [comment]
Why exactly should mechs have a direct counter for cultists? They cost a lot, take prep, and are intentionally clunky. They should be a "queen" in most cases where if you have one you're most likely going to win that fight. Mechs shouldn't be just as weak as normal players where its "I hit you with a single paper therefore you die". Stun papers are almost as bad as cyanide sting imo.

**Comment by Blithering** [comment]
@DrSnips Because antags shouldn't end up in a position where they are no longer a reasonable threat, they exist solely to be a powerful entity that threatens the station. If you get the crew outstripping the antags in terms of power, they either get wiped out quickly or go into hiding, making for boring rounds in either case (see any round where vampires are caught and chapelbaked before getting into the swing of things). The phazon in particular can ruin any cult's day as they are reliant on static structures, and a phazon can just swooce straight through any walls or barriers and start debating the merits of their religion

**Comment by jknpj** [comment]
Maybe the issue is phazon, not mechs? I feel like @Kammerjunk now.

**Comment by DrSnips** [comment]
Don't pretend like they are in the hands of everyone so easy and don't have a cost associated with getting them. I could understand if they are readily accessible but they're not.
With the cost of them they should be something to be afraid of not just something you can tap your funny pages to and it completely removes it.
Also what happened to blind and confuse runes? Do those not affect the drivers?

**Comment by Kammerjunk** [comment]
didn't read any of this but I agree with @jknpj

**Comment by SirSkeleto** [comment]
How about giving this functionality (and perhaps the existing stun for borgs on the stunpaper) to the emp talisman? Use in hand to do the normal EMP but hit something with it to really fuck it up?

**Comment by iFlashYou** [comment]
@DrSnips The pilot is immune to confuse runes/talismans

**Comment by SonixApache** [comment]
I feel like making pilots vulnerable to blind/confuse talismans would be a way better solution.
And also maybe a slight buff to EMP talisman/runes.
But not this stun nonsense.

**Comment by Blithering** [comment]
How about having EMP runes steadily drain cells in APCs borgs and mechs after the initial EMP pulse so long as a  cultist remains channeling it?

**Comment by iFlashYou** [comment]
>when flashbangs can stun the pilot but against blood magic the mechs have to remain immune

**Comment by SonixApache** [comment]
Why the fuck do flashbangs stun mech pilots?

**Comment by iFlashYou** [comment]
You tell me sec main

**Comment by SonixApache** [comment]
upon reconsideration, it probably makes more sense if stun papers and runes stun mech pilots
flashbangs 100% shouldn't, though

**Comment by iFlashYou** [comment]
merge when?

**Comment by aceedex** [comment]
hopefully never. there's 0 reason why an item cult gets from the get go, can be easily mass produced, has no in hand sprite and can be used in conjunction with shit like not an esword TM and pale skin should beat out something that takes quite a lot of time and three departments cooperating to make in one hit

**Comment by iFlashYou** [comment]
>takes three departments cooperating 

It only takes one department to make a mech, the second one is just there so you do not have to go and mine. And I don't know which third department you need to build a mech.
And we have flashbangs, that are available roundstart, that can safely stun pilot from range while with a stunpaper you still need to run up to it to slap in, really dangerous if the mech pilot is competent and/or you fighting a phazon. (Good luck going melee against a phazon)

**Comment by DrSnips** [comment]
Yeah I'm not sure who the third department is either. I'd bet that stuff like flashbangs can be used on pilots due to shitcode where stuff like the confuse rune are too sane.
Also a melee fight where they instantly loose if you even run next to them isn't quite the same as a melee fight with them being able to fight back. Save the phazon it's pretty easy to rush down a mech and at most you're likely going to only eat one shot. Most combat mechs aren't fast excluding the phazon and gygax in speed mode but that one has it's own balance already. Phazons should be a big reward and as for it's "unfairness" it's mainly unfair to melee based strategies. Blame cult combat being mostly melee based while it's ranged options barely tickle. Making stun talismen affect them shift the balance completely to the other extreme while mechs still have their huge costs rather than a papery boi cult have 24/7.

**Comment by aceedex** [comment]
The 3rd department would be security. Even without the lockboxes you need some coordination to male sure you dont get the fuck blown up because theres unauthorized mechs around.

As for flashbangs thats a shitty argument. "But THEY get to stun mechs" 
Even still, Im 100% sure flashbangs stunning pilots is more a result of shitcode rather than it being a balance decision. And should it get removed I welcome it

**Comment by SonixApache** [comment]
Lower it to 2 seconds to appease the locals and simulate having to blood magic someone through a plasteel exoskeleton 🙂

**Comment by DrSnips** [comment]
As a part of local gang gang I wouldn't be appeased. But I'm not too happy about this whole PR. I'd rather see EMPs have a slightly wider use be it damage and or cell drain. I thought most people agree that stun-n-done combat is big gay so why are we just adding that problem here?

**Comment by DeityLink** [comment]
Hah, wow. Maybe not though. Mechas are currently the only "counter" to cult, that cult can still only overpower with good enough tactics rather than with a single rune/talisman.

I'd rather have it stay that way, gives a reason for cult to go all out on the damage dealing side (constructs and cult armor/blade).

Also if #22660 gets through the new meta will be to chain stuns on mechas until someone can pull the pilot out. Should require 6-7 talismans, but I think two naked cultists armed with nothing but paper shouldn't be able to take out a Marauder.

**Comment by ShiftyRail** [comment]
>Mechas are currently the only "counter" to cult, 

Screencapped for posterity
Also I wanted to make an alternative PR that buffs EMPs as requested, but this isn't very high on my list of priorities rigth now

**Comment by DeityLink** [comment]
can you cap the entire sentence please?

**Comment by ShiftyRail** [comment]
If #22767 is merged this has no real reason to exist.

**Comment by iFlashYou** [comment]
>mechas are the only counter to cult

What are guns/tasers or any other weapon?
And now anti-cult collabs are holding this PR in PR hell

**Comment by aceedex** [comment]
emp, fervor, pale skin, armor. rest of the sentence, etc

**Comment by jknpj** [comment]
EMP buff merged, time to drag this one to hell :fire:

**Pull request closed without merging**
