### PR TITLE
Fixes #10973

### LINKED ISSUE #10973: you float after being stunned on a vehicle
update_mob() doesn't get reset if you get stunned on it, only when you are unbuckled

### PR DESCRIPTION
**Pull request by ghost**
Fixes #10973
This is a bit of a hack but no moreso than the hack that was previously used - it would be difficult to not use this hack without rewriting both vehicle and atom locking code.

### CODE REVIEW

**Comment by PJB3005** [comment]
The correct way of fixing this is to use relative offsets everywhere in vehicle code, not this hack.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
See comment.

**Comment by ghost** [comment]
@PJB3005 what do you mean by relative offsets exactly?

**Comment by PJB3005** [comment]
Because of shit like this, you should always add and detract from pixel offsets, never absolutely set them.

Add and substract is the pattern we've been going for.

**Comment by 9600bauds** [comment]
@DrCelt

**Pull request closed without merging**
