### PR TITLE
DO NOT CLONE preference

### PR DESCRIPTION
**Pull request by SonixApache**
i hope i didn't fuck anything up
image
what it says on the tin - adds a pref that makes you unable to clone *in any body you inhabit*

TODO:
 - [ ] add NOCLONE to medical records
 - [ ] add medhud icon?

:cl:
 - rscadd: Added a DO NOT CLONE option to character preferences.

### CODE REVIEW

**Comment by chaklett** [comment]
permadeath mod

**Comment by bathosbathtime** [comment]
I like the idea, hope it works in practice.

**Comment by ShiftyRail** [comment]
The kill and clone lobby disliked that

**Comment by Dacendeth** [comment]
What happens if you get mindswapped?

**Comment by ghost** [comment]
> 
> 
> What happens if you get mindswapped?

It checks for the mob's connected client, not for anything attached to the body or mind. Mindswap victims could still have their brain swapped back even if the mindswapper has do-not-clone toggled on, it only takes effect as long as they're in control of the mob.

**Comment by SonixApache** [comment]
I could change it right here and now to be a 'revival options' pref instead of a straight up do-not-clone pref (ie permadeath - defib only - clone only - any) but i'm not so sure how to change database entries post-merge

**Comment by Kurfursten** [comment]
Should probably be some place you can check to see if someone has this pref (med records?)

**Comment by ghost** [comment]
make it show up on the medhud maybe

**Comment by tuypo1** [comment]
I see no reason not to have it but if anybody thinks I am going to give them triage priority for choosing to be special snowflakes they got another thing coming

**Comment by ghost** [comment]
Intentionally choosing not to revive people because they're against an ostensibly cheap mechanic is poor roleplay, metagaming, and arguably just being a dick in general.

**Comment by SonixApache** [comment]
he said priority, man

**Comment by triplehorse** [comment]
imagine being snowflake enough to demand extra special treatment from medbay

and then having the FUCKING audacity to claim it's "poor roleplay, metagaming, and arguably just being a dick in general" when they triage you?

**Comment by ghost** [comment]
I don't care if people clone me, and I main medbay. Also, your gay.

**Comment by Kharkov72** [comment]
if my toolbox cannot heal you you need to accept the consiquences

**Comment by SonixApache** [comment]
not enough codermana to implement requested features, will try again some other time

**Pull request closed without merging**
