### PR TITLE
revert stealth change that deleted alien has_fine_manpulation

### PR DESCRIPTION
**Pull request by gurfan**
hey @adacovsk  why don't you check what these variables do instead of blindly trusting comments you fucking retard

### CODE REVIEW

**Comment by Theophrastus1** [comment]
it just keeps happening my friends

**Comment by Eneocho** [comment]
The consequences were unforeseen.

**Comment by NigglyWiggly** [comment]
Fucking christ man.

**Comment by jwhitak** [comment]
To defend @adacovsk, this did not affect normal gameplay. This change only prevented admins from bussing in xenos that could pick things up that weren't facehuggers. But it still went as an undocumented change and I'm sure admins have secret bus notes that included this funny tidbit.

**Comment by adacovsk** [comment]
This is literally for bussing and that's it???

**Comment by Eneocho** [comment]
I've never seen a bussed beno that could actually hold stuff since I started playing. Sounds like a neat bus though.

**Comment by SacredAtom** [comment]
image

**Comment by kernikov** [comment]
> To defend @adacovsk, this did not affect normal gameplay. This change only prevented admins from bussing in xenos that could pick things up that weren't facehuggers. But it still went as an undocumented change and I'm sure admins have secret bus notes that included this funny tidbit.

>>thinking admins document anything

**Comment by Cisrox** [comment]
tbh the fact that it doesn’t have gameplay effects doesnt make it okay, at that point lets just secretly remove everything that is used for bussing because its “only for bussing”

**Comment by Eneocho** [comment]
> tbh the fact that it doesn’t have gameplay effects doesnt make it okay, at that point lets just secretly remove everything that is used for bussing because its “only for bussing”

That's the thing though, it was not a secret change. The PR (#33343) said that it removed uncompiled and unused code. The fine manipulation change had a comment that stated it was only used on an uncompiled mob (//Deprecated, only used by /mob/living/carbon/alien/humanoid/special which isn't compiled).

**Comment by NigglyWiggly** [comment]
I used to use this shit all the time
Also it's not exactly a secret or undocumented thing, but most of his PR's are just "removes bad stuff" and then 80 lines of code removed without explanation for what he specifically is removing or why.
In a lot of cases that's not an issue but it can be frustrating to try to find the source of a change and have to dig through the files changed on each PR

**Comment by Cisrox** [comment]
> That's the thing though, it was not a secret change. The PR (#33343) said that it removed uncompiled and unused code. The fine manipulation change had a comment that stated it was only used on an uncompiled mob (//Deprecated, only used by /mob/living/carbon/alien/humanoid/special which isn't compiled).

understandable, i was misled by the title

**Pull request merged**
