### PR TITLE
Arcane golem movespeed buff and melee attack

### PR DESCRIPTION
**Pull request by unid15**
* Changed typepath to /mob/living/simple_animal/hostile/arcane_golem (used to be /mob/living/simple_animal/arcane_golem) - this allows for more complex behavior

* Arcane golems now have a 15-25 melee attack that they will occasionally use on any enemy who comes close to them. They are still forced to follow their master, and they will never chase anybody. They will not punch their master, other golems or any other animals slaved to the master.

* Arcane golems now move as fast as basilisks (slightly faster than before)

* Arcane golems now spawn ectoplasm on death

new movespeed

3 golems hitting a cat
punches

### CODE REVIEW

**Comment by ghost** [comment]
> Arcane golems now move as fast as basilisks (slightly faster than before)

Weren't basilisks a closed project?

**Comment by Exxion** [comment]
Basilisks are an asteroid mob.
You're thinking of cockatrices, which would be synonymous in any other context.

**Comment by ihadtoregisterforthis** [comment]
The basilisk is the blue crystal frost sight thingy

**Comment by SkowronX** [comment]
Is no one going to make a replacement for that sprite?

**Comment by unid15** [comment]
if somebody makes a better sprite i'll include it in this pr

**Comment by ComicIronic** [comment]
What's wrong with it? What was wrong with purple crystal?

**Comment by Exxion** [comment]
Nothing
Skowron's just weird

I mean it's not the greatest most fantastic sprite EVER, but it's at least on par with anything else in the game

**Comment by PJB3005** [comment]
He just hasn't passed the 5 stages of loss yet.

I'm so sorry skowron I promise I'll make it great again one day.

One day.

**Comment by ComicIronic** [comment]
This is fine for code, left to a playing collab.

**Pull request merged**
