### PR TITLE
Fat Ninja Fix

### LINKED ISSUE #27550: Fat Jutsu
If you join as a fat ninja, `equip_ninja` uses equip or del so it deletes the suit, and since the sword goes in the suit storage, it deletes that too

### PR DESCRIPTION
**Pull request by Kurfursten**
fixes #27550

🆑 
* bugfix: Fat ninjas will no longer be unarmed and unarmored

### CODE REVIEW

**Comment by mrflarg** [comment]
bring back weaboo

**Comment by jknpj** [comment]
> bring back weaboo

BANZAI

**Comment by Kurfursten** [comment]
Weeb still exists in the code, admins can toggle any ninja to be a weeb instead with one button on the check antags page, just none do

**Comment by SonixApache** [comment]
why are fat ninjas even a thing

**Comment by DamianX** [comment]
ninja outfit datum when

**Pull request merged**
