### PR TITLE
Security RPGs

### PR DESCRIPTION
**Pull request by bathosbathtime**
This pull request adds the Nanotrasen RPG, the blank rocket, the stun rocket, the EMP rocket, and the low yield rocket.  All of these items can be made using a standard ammolathe.  The RPG requires metal, glass, and **gold** to build.  The blank and the low yield require metal only.  The EMP requires metal and uranium.  The stun rocket requires silver.  All of the values listed can be edited per request, I do have reasoning behind them but I also avoid in game combat so I am unfamilar with how any of this would shake out in normal gameplay.
EDIT: Oh also the point of this PR is to both give security some fun toys while also giving people "RPGs on training wheels" to help curb flukeops.

Tested and compiled locally.

* Low Yield: The "lethal" option, this rocket will damage a small area.  Will not breach normal metal floors.  Avoid shooting exterior walls and windows with it.  The damage has been brought up.
* Blank: The stun shell of the group.  Foam rockets have been renamed so that rockets that cause foam can be made in the future without causing confusion.
* EMP: It causes an EMP in a small area, useful against crew members with eguns or pacemakers and not much else.
* Stun: This bad boy is a rocket propelled banger.  The damage has been reduced significantly, but can still cause medical complications on soft targets.

:cl:
 * rscadd: Adds the Nanotrasen RPG, the blank rocket, the stun rocket, the EMP rocket, and the low yield rocket to the ammolathe.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Hold up so now sec can make all the RPGs and ammo they want?

**Comment by bathosbathtime** [comment]
Yes.  The materials requires and amount can be adjusted for each item if felt to be too low.  While I find these amounts to be acceptable, I would be more than willing to change them as needed.

**Comment by bathosbathtime** [comment]
damageTable
This PR has been changed significantly.  RPGs now require 3 gold sheets to build, the same amount that spawns in boxed vault.
The stun rocket is no longer a single target nuke.
The low-yield rocket hurts more to the direct hit target.  Example above.

**Comment by Diavill** [comment]
RPG firing squads for everyone downboating this pr NOW

**Comment by Kurfursten** [comment]
conflicts

**Comment by bathosbathtime** [comment]
>gun.dmi has a red number now
>
Please do not merge until I make sure I didn't fuck something up

**Comment by bathosbathtime** [comment]
Compiled, tested again, and ready to go.

**Comment by Kurfursten** [comment]
I swear on me mum if this causes a wave of admin issues

**Comment by Kharkov72** [comment]
BASED

**Comment by MadmanMartian** [comment]
>actually just added a printable rocket launcher to the game

Prepare for unforseen consequences.

**Pull request merged**
