### PR TITLE
Data HUD range increase

### PR DESCRIPTION
**Pull request by DeityLink**
datahudrange

:cl:
* tweak: Data HUD range now depends on the client's view plus an overhead of 7 tiles, instead of a fixed 7 tiles. This overhead gives the HUD icons time to appear before the mob comes into view, drastically reducing the situations where you have to wait a second or two for it to appear.

### CODE REVIEW

**Comment by PlausibleDeniability** [comment]
Fantastic PR

**Comment by drawsstuff** [comment]
My only (serious) note comes from one of these situations where my ability to survive hangs by the thread of whether or not the hud updates in time. I'm glad to see a fix.

**Comment by SonixApache** [comment]
Though this is definitely an improvement, is it not possible to just improve the code to make it render faster?

Also, does this work for all the HUDs, including antagHUDs?

**Comment by DeityLink** [comment]
>Also, does this work for all the HUDs, including antagHUDs?

@SonixApache You did well to remind me that observer-exclusive HUDs are handled elsewhere in the code. I also added the changes to the Seer rune's convertability HUD.

Antag factions icons however are handled completely differently, for better or for worse. Unlike HUD icons they are "always" part of the client's image list, even when the faction members aren't in view at all, which means they will always show up without any lag on their mob. However the procs that add and remove those are more expensive, which is made up for the facts that:

1. They are called much more rarely than the data HUDs
2. There usually aren't that many faction members, even the cult would have at most all of the crew, while data HUDs would also show data for mindless mobs.

dataHUD don't take "time" to render, it's just that the call to update them is done once per Life(). And depending on if the mob entered your range slightly before or slightly after the last Life() call, their icon will appear instantly, or with a 1-2 second delay respectively. My solution here reduces this maximum delay from the time it takes to run 7 tiles at full speed, and most of the time the icon should now render before it even gets into view. However this doesn't help with mobs teleporting into close range/changing Z-Level. A completely different system would have to be implemented.

**Comment by DamianX** [comment]
I wonder if multiplying by 2 instead of adding seven would make this more future-proof.

**Comment by DeityLink** [comment]
@DamianX That would actually be worse, it has to be a flat value or smaller client views will have much less overhead time.

**Comment by DamianX** [comment]
It's just that a 7 there feels a bit like a magic number.

**Comment by Kurfursten** [comment]
Could use a defines

@DeityLink is that such a bad thing though? they're already penalized by smaller view distance; I'd be more concerned about the opposite, where farsight or binocs cripple your client suddenly

**Comment by DeityLink** [comment]
@Kurfursten That's the thing, it wouldn't, it's an overhead of 7 tiles **on top of your current view distance**. so people with the +2 viewdistance genetic power will have their icons start rendering from 16 tiles away instead of 14. The constant here is that it always renders "7 tiles away from the edge of your vision".

I'll make it a define.

**Pull request merged**
