### PR TITLE
Changes switch statement to start at one for Mommi Transformation.

### PR DESCRIPTION
**Pull request by Probe1**
Note:  Transformation took less than 30 seconds.  Balance issue.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by Probe1** [comment]
For fucks sake it doesn't work on plasma men at all.

**Comment by Probe1** [comment]
You ever start to fix a bug and find about 10 more bugs related to it because something wasn't handled properly when it was originally implemented?

🔫

**Comment by Allspice** [comment]
does it happen in 30 seconds everytime or did you just luck out with virus1

**Comment by Probe1** [comment]
I just lucked out but it's still rather quick for what it is.  And last time I checked copper didn't work.

Anyway I'm pretty sure I'm not going to fuck with this.  As you explained in the issue.  Since I'm not super keen on rewriting viruses, bloodless characters, or undead characters, off we go.

**Pull request closed without merging**
