### PR TITLE
Fixes C20r not stunning.

### LINKED ISSUE #11713: Syndicate c20r doesn't knock down
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a11b14623ac8bfb6d9e930c9c74cb61044d4edd2 
> 
> General description of the issue
> Being shot by the nuke ops gun doesn't knock people down anymore
> 
> What you expected to happen
> Shoot someone and they fall over
> 
> What actually happened
> They keep coming
> 
> Steps to reproduce if possible
> Shoot someone with the ops gun

Probably because of the recent assault rifle nerf

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
The C20r SMG wasn't supposed to lose its ability to stun; I had overlooked the fact it and the AR used the same magazines. Fixed it by adding a new mag for the gun that uses the proper bullet type. 

Fixes #11713

### CODE REVIEW

**Comment by ghost** [comment]
How about the ammo in the crates and syndicate lockers?

**Comment by icantthinkofanameritenow** [comment]
Ooh, nearly forgot that. Hang on, I'll fix it.
Edit: Syndicate lockers should have the right ammo type now. Not sure which crates you're talking about, but I can fix that too if you tell me. The ones that start in the ops' inventory are the right ones if that's what you mean.

**Comment by ghost** [comment]
I've no idea either but I was sure there were some, somewhere. Maybe not.

**Comment by icantthinkofanameritenow** [comment]
Didn't see any, at least on the main three maps in rotation.

**Comment by icantthinkofanameritenow** [comment]
Should be ready for merging now.

**Pull request merged**
