### PR TITLE
Changes Wizard Name Generator to that of Wizard101

### PR DESCRIPTION
**Pull request by chesse20**
Added the name generator from wizard101. took me like 20 minutes
:cl:
 * rscadd: Added the name generator from wizard101 to the wizards
 * rscdel: Removed all the old wizard names

### CODE REVIEW

**Comment by Probe1** [comment]
👀

**Comment by jknpj** [comment]
>removing the older ones

worse than hitler

**Comment by NigglyWiggly** [comment]
>Removing old ones instead of just adding new ones

**Comment by Probe1** [comment]
>adding 7000 lines worth of strings

**Comment by Kurfursten** [comment]
I legitimately thought this was an April Fools PR

**Comment by Probe1** [comment]
So did I.  I'm not adding 7000 lines of mostly common names.

**Comment by Mothblocks** [comment]
@Kurfursten @Probe1 it is and he's waiting for you to close it

**Comment by Probe1** [comment]
is that a dare

**Comment by Mothblocks** [comment]
@Probe1 if i were to make a dare it would be to merge this for at least one wizard round, which i do

**Comment by Probe1** [comment]
I will never close this issue.  You can't beat me!

**Comment by Mothblocks** [comment]
you might not but someone else will

**Comment by chesse20** [comment]
@Probe1 merge it, coward.

**Comment by Probe1** [comment]
NEVER

**Comment by Intigracy** [comment]
This didn't get in before april fools.

**Comment by chaoko99** [comment]
your work is not wasted

**Pull request closed without merging**
