### PR TITLE
Loyalty implanted CE, CMO, RD

### PR DESCRIPTION
**Pull request by brndd**
[tweak][balance]

Since we're a democratic server and all that, let us listen to the thread.

Pros:

- The "minor heads" are now more trustworthy so the rest of the station (primarily sec) can trust their authority more

Cons:

- RD and CMO antag mains will be upset and will argue that this will make even fewer people play these roles

:cl:
 * tweak: The Chief Engineer, Chief Medical Officer and Research Director are now loyalty implanted. This means they have a lower chance to roll antagonist for roles that care about implants, and cannot roll roundstart cultist.

### CODE REVIEW

**Comment by brndd** [comment]
also unatomically fixes a relative pathed proc for the HoP's loadout

**Comment by MadmanMartian** [comment]
>That's how equiping an implant is done

yeesh

**Comment by DamianX** [comment]
Great but does this also affect their antag chance? It should.

**Comment by brndd** [comment]
> Great but does this also affect their antag chance? It should.

Yeah it should, I honestly thought that would be automatic with the implants but looking at how they're installed I'm sure it isn't. Which file are the chances defined in?

**Comment by boy2mantwicethefam** [comment]
Security won't be able to arrest me anymore if giving everyone a gun is better for NT

**Comment by ShiftyRail** [comment]
Outfit datums will handle the implant thing
Personally I don't think the serb is ready for such an avant-garde change

**Comment by boy2mantwicethefam** [comment]
The server's ready for anything, just make sure to notify people

**Comment by brndd** [comment]
@DamianX if I'm reading the code right, traitor, vamp etc. don't have lower chances to roll for heads of staff. Only cult and ling use the `protected_jobs` var in role datums. It's possible traitor/vamp etc. do their blacklisting somewhere else.

**Comment by DrSnips** [comment]
What's the point of giving them one? Autism that some do and other don't so we need to make them all the same? When has authority ever been dictated by implants.

**Comment by ShiftyRail** [comment]
All `protected_roles` have a reduced chance. No matter the role. It's handled in dynamic rulesets.

**Comment by brndd** [comment]
>What's the point of giving them one? Autism that some do and other don't so we need to make them all the same?

Allow me to refer you to the thread post linked:

>it shouldn't make sense that the CMO and RD are always antags and the CE is given shit by sec just for existing.

Or to put it differently, these departmental heads don't feel like real heads, they just feel like glorified jobbies that the Captain, the Captain (HoS), or the Captain (HoP) will occasionally boss around so they can swipe code red.

**Comment by ShiftyRail** [comment]
Personally it's one of those elements of conflicts that should not go away. I actually want to distrust the CE. I don't want to be buddy-buddy with them.

But this point of view is hard to defend.

**Comment by DrSnips** [comment]
This doesn't change anything related to that though just because you put a green dot next to them that only select people can see doesn't make them any more in control of their department. If you asked people who actually obey heads of staff I bet it's not because they have an implant. If you didn't include a changelog I doubt anyone would even know that they were implanted and therefore care.

**Comment by brndd** [comment]
> just because you put a green dot next to them that only select people can see doesn't make them any more in control of their department. 

The point isn't to make their subordinates obey them, the point is to make them more trustworthy as authority figures. These roles are expected to take on the mantle of acting captain in the absence of anyone higher up in the chain of command and have free reign to key areas of the station, yet their chances of rolling traitor/cultist/vamp/what have you are as high as those of any random jobbie or assistant.

This makes it difficult to trust control of the station to them, and means that these jobs have a disproportionately easy time when antagging, because their increased power (~~chloral~~ doctor's delight sprayer, AI upload access, bridge access with the ability to (re)call the shuttle etc.) and authority doesn't come at the cost of lower odds of rolling antag & being easily detectable by sec if they get converted.

**Comment by Accipitermaris** [comment]
This has been a bugbear of mine forever and I had honestly thought the server was too against it. If the people who play CE/CMO/RD a lot want it, go for it. That said, I cannot emphasize enough that this is not the sole major reason why the masses (read: not just sec) don't trust these heads of staff, for the reasons DrSnips mentioned. So buyer beware(!)

**Comment by ghost** [comment]
I'm fine with giving them loyalty implants, it's a distinction that never made too much sense to me. Their ass is on the line if it's Rev, and they can definitely be targetted by antags for their items

Antag rolls ? Don't touch 'em is my feel. Being able to roll antag is a perk of those roles, especially since CMO is particular is a bit of a meme for being the least powerful head on the ship. CMO has virtually no Bridge authority, no access to the AI, his uniform is ultra obvious so it's hard to get away with antagging and Medbay often gets mass griefed by antags

**Comment by ShiftyRail** [comment]
You cannot have the metaphorical cake and eat it. The additional metatrust (so-called meta milkies) that the implant gives - when a RD assumes captaincy, for instance - shouldn't have zero drawbacks.

**Comment by SonixApache** [comment]
:-1:
Don't really see why you'd do this.

*edit to argumentate*:
I mostly agree with Shifty on all this - the perks of those roles is that you get more access, toys, trustworthyness and responsibility, but with a decent chance at rolling antag. Removing that would remove even more incentives for people to play the roles.

**Comment by Kammerjunk** [comment]
### don't mistake this for an opinion on whether this should be a thing (because I don't have one which means you can't disagree with it gotcha)
but "this is so sec can trust them more" is grand gay and huge homo
- don't make decisions on the basis of "well you (the person that I know is controlling the abstraction of a person that my abstraction of a person is pretend-looking at) might be an antag (based on the fact that the code for the game that we are both playing favours people who spawn in the beginning of the round with a certain attribute *and based on nothing else*)" - especially not ones like "no you can't have the golden ticket *I* have the golden ticket"

"but it's because sec wouldn't trust people who aren't loyalty implanted"
- if you're sticking to the IC justification, sec are private security at best and mall cops at worst and they aren't hired to believe but they *are* (presumably) taught the chain of succession

frankly trusting your HoS because you know he's implanted is gay anyway, in the same way that going "well this guy has an emag so the current round can't be vampires" before auntie datums was gay

thank you for watching please subscribe for more video essays and remember to donate so I can buy more pictures of my furry avatar to put into the video and pretend it's me talking

**Comment by Caboozles** [comment]
I don’t see why people are up in arms acting like this’ll make security suddenly like these heads any more. 

It’s a placebo change that really just nerfs cult’s ability to get all access.
Good. Fuck cult. Do it.

**Comment by Caboozles** [comment]
I don’t see why people are up in arms acting like this’ll make security suddenly like these heads any more.

It’s a placebo change that really just nerfs cult’s ability to get all access.
Good. Fuck cult. Do it.


And because my phone can’t edit for some dumb reason I’ll just throw this on a second and delete my first post. This expands the sacrifice pool in a more interesting manner too.

**Review by DamianX — COMMENTED** [review]
I think you should:
- Add the three jobs to the protected_roles list for d*namic rulesets
- Prevent the three jobs from being round-start cultists

Because, respectively:
- The trust you gain from being loyalty implanted is related to the lower antag chance
- Because that's the reason why #23433 was made, a starting cultist shouldn't be a sacrifice target

Anything else seems dumb and inconsistent

**Comment by FudgePucker** [comment]
It's not like having an implant removes your chance to get antag.
I got captain traitor two times in a row before.

I support this because entire departments can be easily converted to cult without any real tells. The head of a department being missing or lacking an implant can clue security in on the situation inside a department.

**Comment by Intigracy** [comment]
good pr

**Review by Intigracy — APPROVED** [review]

**Comment by brndd** [comment]
@Kammerjunk 

Paraphrasing here, but am I correct when I assume that what you basically mean is 

>don't make IC decisions based on OOC knowledge

My rebuttal to that is that implants are an IC mechanic. From an IC point of view implanted people should be literally, or at least almost completely, unable to oppose NanoTrasen. There is an IC reason for implanted characters to be ICly more trustworthy, and an IC reason for non-implanted characters to be ICly untrustworthy.

@DamianX 

I agree, and agreed from the beginning, but wasn't sure how and where to implement it. I've now implemented it, though. Please take a look to make sure I did it correctly and for all the roles you wanted.

**Review by DamianX — APPROVED** [review]

**Comment by Kammerjunk** [comment]
@brndd partly, see "but it's because sec wouldn't trust people who aren't loyalty implanted"
in short, that sort of trust is in conflict with the chain of succession

**Comment by bathosbathtime** [comment]
Implanting them and not changing the antagonist chances would be the single dumbest possible move. You'd devalue the meaning of the implants overall, greatly reduce the trust you would get with them in this case rendering the arrangement near pointless, and make the game even more inconsistent by doing so.
I don't care about this pull request but a particular suggestion above was worth additional feedback.

**Comment by brndd** [comment]
They get reduced antag chances.

**Pull request merged**
