### PR TITLE
Roidstation 1.3

### PR DESCRIPTION
**Pull request by GeneralVeers25**
This rework is designed to address one of the biggest pieces of feedback I've gotten about Roidstation - that the long central hallway is just too damn long. Accordingly, it has been completely revamped, along with Cargo Bay, the Head of Personnel's Office, Medbay's Central Treatment Room, the Bar, and the Bridge.

I have also added @BurntDevil's excellent new Escape Shuttle, so we are no longer using the one from Bagel. CentComm has also been adjusted to fit the new Escape Shuttle.

The Bar:
https://lambda.sx/5ri.PNG

The Bridge: 
https://lambda.sx/Lqr.PNG

The Escape Shuttle:
https://lambda.sx/MfH.PNG

The Lobby:
https://lambda.sx/D9U.PNG

The Medbay:
https://lambda.sx/TkP.PNG

:cl:
 * experimental: the following changes all apply to Roidstation
 * tweak: The Bridge and Central Halls have been reworked to reduce the likelihood that one greyshit can vent the entire station.
 * tweak: The Bar now has tile floors instead of wooden ones.
 * rscadd: The central Lobby area outside Science has been reworked to give the station better flow and to shorten that incredibly long central hallway. The Cargo Bay, HoP Office, and Teleporter have been moved around.
 * rscadd: A new Escape shuttle has been provided for the station's benefit.
 * rscadd: Office O'Beepsky, The Pride of Security, now properly patrols the halls.
 * bugfix: Various bugfixes.

### CODE REVIEW

**Comment by CptWad** [comment]
\>bagel

**Comment by DamianX** [comment]
whoops

**Comment by Kurfursten** [comment]
Unless that shard monitor is set to autoconfigure itself, no one's gonna be taking a multitool all the way to the SME room, buffering it, and bringing it back to the bridge to link

I don't think I like the massive shuttle. It's just SO big.

This last opinion is extra spicy but I don't know if I like the eastern wing renovations either. You've ended up with two weird sort of tumor common areas to try to accommodate hop/cargo + r&d robotics, and it felt more natural to have the big mall like area serving all four in one place to me. It doesn't make the long hall less long by just reducing the trips people take to cargo or the HOP, which are usually once per shift for someone. Maybe this is just me being out of touch though.

**Comment by GeneralVeers25** [comment]
Is there a var I need to edit on the Shard Monitor to make it configure itself? If I recall correctly, one of the shards is already tagged as "SME 1" or something but I would need to double check.

That's a valid opinion. I already cut it down some. If it strikes too many people as just too big, I'll take the front wings out completely and move their components to the back sections, like on most shuttles.

I actually somewhat agree with you on the last point. I like how the new lobby came out, playing and observing the game really showed off just how terrible it was to cross the station, but the lobby as it existed before also wasn't really doing its job properly - it didn't service the HoP Desk, for one, and it was wasted on Science since most people who went there were trying to head into Science.

One of the ideas I have had to fix this is to replace the extant entrance to the Science Wing (where the glass doors are) with a large shared desk for Robotics+RnD so that the Scientists have an entrance to the mall. However, that's outside the scope of this PR because it would require me to completely rebuild Science and I'd like to see how players interact with the new lobby before making more drastic changes centered around it.

**Comment by Kurfursten** [comment]
Make its id tag match the id of a shard or the shard box mapping id. The shard is not a preset id afaik, I believe that idea was scrapped

**Comment by GeneralVeers25** [comment]
I'll make that modification when I'm home. That shouldn't hold up merging this PR though, I can just hotfix it in.

**Pull request merged**
