### PR TITLE
Revert "Insectoids (Roachmen) II: Electric bugaloo"

### PR DESCRIPTION
**Pull request by Buchse**
Reverts vgstation-coders/vgstation13#25757

I've gotten loads of complaints about how I've executed them, and the suggestions I've received I'm either not a competent enough coder to implement, or were stupid/shitposts. There are bugs with them I can't seem to find, and the concept is better left to someone who can more competently create and implement it. 

I no longer plan to work on more content for them or bugfixes at this point.

### CODE REVIEW

**Comment by SirSkeleto** [comment]
here's a bugfix

**Comment by PrimeDSS13** [comment]
>thumbs up on your own PR

bro...

**Comment by SageOfLight** [comment]
If anyone picks this back up and doesn't sodomize it with turk memes or making it an event race, I'll help with sprites.

Until then, fucking RIP.

**Comment by yclatious** [comment]
https://www.youtube.com/watch?v=lpZiPZwwXhM

**Comment by N3X15** [comment]
You can ask for help, you know.

**Comment by SonixApache** [comment]
this PR is the correct bugfix
it fixes the bugs
by squashing them

**Pull request closed without merging**
