### PR TITLE
Vesta Heaters

### LINKED ISSUE #25347: Snaxi: Medbay Desk
I'd like it enclosed in glass with windoors, like the sec desk. It'd be nicer.

### LINKED ISSUE #25364: Security escape pod on Snaxi
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
415f91fdf41f551a32c310a6b621931c38dc2139

# Description
Secescape pod on snaxi seems to be locked behind engi access. As HoS I was unable to open the firelock leading to it

# Steps to Reproduce
Touch the doors

# What you Expected
Freedom!

# What Actually Happened
Buzz

### LINKED ISSUE #25377: snaxi: southern station medbay area is named Medbay
which means you can't teleport to the actual medbay with the scroll of teleportation because this second area always overrides it
remove snowmap

### LINKED ISSUE #25455: Auto Bomber Arena Overlaps Snaxi Ops Base
Oof

### LINKED ISSUE #25475: Misplaced light switch
(WEB REPORT BY: dustyny REMOTE: 206.221.180.138:7777)
# Revision
2505603b5898ed9dea75cfc98d4f8d2c8b4cd514

# Description
On snaxi the light switch in the medbay's break room is on the arcade machine instead of the wall
# Steps to Reproduce
be forced to play the worst map
# What you Expected
light switch on wall
# What Actually Happened
light switch on arcade machine

### LINKED ISSUE #25480: Snowmap medbay
(WEB REPORT BY: robosperg REMOTE: 206.221.180.138:7777)
# Revision
d714f40cad6e025306aefdd8bc7b079d84fd21bb

# Description
Light switch is on the arcade machine in breakroom. Door from breakroom to main hall is missing a tile under it. Could not find a box of perscription glasses anywhere in medbay.

### PR DESCRIPTION
**Pull request by Kurfursten**
fixes #25455
fixes #25364
fixes #25480
fixes #25475
fixes #25377
fixes #25347 
fixes: geysers will no longer wrongly appear on asphalt

image

🆑 
* bugfix: Snaxi fixes
* rscadd: Each Snaxi station has three VESTA-class space heaters. These immobile heaters are much more powerful than a standard space heater and draw power from the APCs.

### CODE REVIEW

**Comment by N3X15** [comment]
The new heaters should probably be hardwired, if they're going to draw 10 times the wattage of a standard heater.

**Comment by Kurfursten** [comment]
They only draw 5x the power (but they intake 4x as much gas at a time), and automatically turn off if the room reaches 35C

Being hardwired wouldn't really make a difference since they are anchored and cannot be relocated at all.

**Comment by jknpj** [comment]
That won't stop me from using a subspace memegun to steal them for my TEG!

**Comment by FudgePucker** [comment]
Should allow hacking to remove the temperature check. Soldering iron is a good choice instead of the mememag. Balance wise make it melt down and break at a high temperature to prevent a space heater from warming up an area to star levels of heat

**Comment by Kurfursten** [comment]
Honestly I think Snaxi has enough ways to mess up its atmosphere already

**Comment by Exxion** [comment]
The amount of gas they take in doesn't really change anything except in weird edge cases anyway
I don't really remember why I left them doing that when I changed other things to just add thermal energy to the environment directly. Probably because of said edge cases.

**Comment by Kurfursten** [comment]
They heat the removed air group then remerges it

**Comment by Exxion** [comment]
Yes, and the amount removed has no effect on the amount of energy added to the environment except when the environment has very little gas in it

**Comment by Kurfursten** [comment]
So what you're saying is there's no reason for space heaters to remove a portion of air at all, it will have the same effect if we apply the heating to the whole air datum for the area?

**Comment by Exxion** [comment]
Yeah. Conservation of energy and all that.
You would have to do something to avoid the superheating issue mentioned in the comment, but that can be done in a much smarter way anyway

Don't worry about any of this for this PR though. It works fine as-is.

**Comment by Kurfursten** [comment]
To address your concerns I've
* Taken away the CL claim that it is 20x as powerful
* Doubled heating power
* Halved heating power cost per unit of heat (to keep the power cost the same as before)

**Pull request merged**
