### PR TITLE
Fixes #12985, Roman religion not working

### LINKED ISSUE #12985: Chaplain Religion "Roman" not working.
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
9807acba44ad6e88b0e2e28342b711f791e19032

>General description of the issue
One of the Chaplain religions isn't properly appearing in-game. It's listed on the github, however.

>What you expected to happen
Set religion to "Latin" (same should also apply to "Rome", "Roma", and "Roman") and get Legionary armor, etc.

>What actually happened
Default Religion (Space Jesus, Holy Book of etc.)

>Steps to reproduce if possible
Set Chaplain religion to "Latin", "Rome", etc.

### PR DESCRIPTION
**Pull request by Kammerjunk**
Fixes Roman religion not working. Religions have to be undercase.
Fixes #12985

### CODE REVIEW

**Comment by Imagebard** [comment]
FIRST

**Comment by PJB3005** [comment]
Sorry @imagebard I'm first.

**Comment by Probe1** [comment]
Oh shit nice GET

**Comment by PJB3005** [comment]
wew

**Pull request merged**
