### PR TITLE
Vox shuttle doors no longer all-access

### LINKED ISSUE #11948: All doors on the vox skipjack are all-access
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a0276aab47fd96958917ffcb01190cfbcf33ca6c 
> 
> General description of the issue
> Anyone can open all doors on the vox skipjacks
> 
> What you expected to happen
> The doors to require syndicate access, the vox already start with agent IDs to provide it
> 
> What actually happened
> Anyone can walk through the skipjack freely
> 
> Steps to reproduce if possible
> TP to skipjack, touch door

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
Fixes #11948

### CODE REVIEW

**Comment by kilozombie** [comment]
Why the fuck isn't this merged yet? Is it just because it conflicts? can't that be fixed

**Comment by clusterfack** [comment]
Not by us

**Comment by icantthinkofanameritenow** [comment]
Wait, since when did this have conflicts? It didn't have them last time I checked.

**Comment by clusterfack** [comment]
At LEAST 10 days, possibly longer

**Comment by icantthinkofanameritenow** [comment]
Well fuck. Time to go and rebase the PR then.

**Comment by liltiptop** [comment]
> wizard den

WHAT HAVE YOU DONE?!

**Comment by Exxion** [comment]
Map conflicts are hard
/tg/ map format when?

**Comment by clusterfack** [comment]
When it doesn't cause crashes and shit

**Pull request merged**
