### PR TITLE
Massive Bus Medbay Remap

### LINKED ISSUE #10247: Bus Station - Medbay Complaints
ok medbay pros lets unite here.

The placement of things is kinda fucked up. Cryo being so close to the entrance is bad, possibly switch it with where the sleepers are? I feel like it'd be better as sleepers can be used to solve problems quickly while cryo is usually a longer commitment. Also it'd be so easy to fuck up cryo as a traitor with it being right there.

No lobby area kinda sucks but I guess you can't really have it since it's a compact station.

Speaking of cryo, the tubes should be under the tiles probably.

Chemistry and Storage should switch - It sucks to have the chem freezer far away and behind a door. 

The morgue feels way too big, especially when you look at cloning and it's a small piece of shit.

Possibly reroute the way into the telepad room? Medbay having its own is cool (how the fuck does teleporting aliens work is that going to kill everyone) but being behind two doors kinda sucks and overall the room feels kinda overly big.

In the end I think medbay needs a ton of reshuffling as it's clunky as hell. A lot of bigger rooms need to be smaller, and smaller rooms bigger.

### LINKED ISSUE #10250: [Bus] Map issues with toxins and one research outpost.
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision baaa4e48682da18c80d2481b5ce7bfdfbe742951 
> Toxins only has 3 valves instead of 6 which is shit for adjusting mixes after a test

No portascrub at all to clear plasma tanks

No portapump at all when it needs 4 for clearing tanks and handling small quantities of gas/cold gas since canisters only fill to current pressure unlike portapumps

No heater

No regular pipe dispenser or a filter on the burn chamber outlet, a gas mixer hookup to minimize waste, a heat exchanger hookup to the pre-gas pump outlet so you can still heat plasma when you fucked up and got a ton of co2 you can't get rid of.

No toxins test site?

Research outpost has no portascrubs for helping clear gas gen large artifacts

### LINKED ISSUE #10272: Bus: Paramedic maint door doesn't have paramedic access
Just a reminder to myself

Also add an oxygen tank maybe?

### LINKED ISSUE #10317: No pepper spray refiller in the warden's office on bus station
im smh tbh fam bams. How can I enter my inner shitcurity if I cant refill my pepper spray? Fix this POST HASTE.

### LINKED ISSUE #10325: Xenobio
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
I don't think the connecter port is connected to the plasma room.

### LINKED ISSUE #10328: Librarian cannot open his own shutter in his Den on Bus Station
What happened: I was the Librarian and I tried to open the shutter in my library backroom on bus

What you expected to happen: The door to open

What actually happened: Sod all

### LINKED ISSUE #10335: add gps on the eva/pod hangar places on bus station
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the feature

add gps for spess exploring

> What you expect to happen

more spess exploring

### LINKED ISSUE #10338: Bus Station disposals
(WEB REPORT BY: rattletrap REMOTE: 172.93.109.202:7777)

> Revision 7eb4d7c97a0140b6dd70b9f5dcd9fdc109e15285 
> General description of the issue
> There is an Output chute where there should be a delivery chute on the Medical and silicon station in the disposals sorting room. 
> 
> What you expected to happen
> The destination sorting machine sends the appropriate crates to the next conveyor, which should lead to a delivery chute. This delivery chute puts the crates into the station's disposal system and crates are delivered.
> 
> What actually happened
> Destination sorting machine sends crate to next conveyor, but the conveyors lead to a disposal outlet rather than a delivery chute, so the crates just sit there.
> 
> Steps to reproduce if possible
> Spawn on bus station, go to medical and silicon station disposal sorting room near the MoMMI nest, find disposal outlet where there needs to be a delivery chute, in the top left corner of the room

### PR DESCRIPTION
**Pull request by Kurfursten**
untitled
- Completely restructured medbay
- Now vents and scrubbers unstacked
- More lights and colored tiles
- New lobby and patient room

fixes #10325 
fixes #10328 
fixes #10272 
fixes #10335 
fixes #10317 
fixes #10338 
fixes #10250
fixes #10247

### CODE REVIEW

**Comment by Imagebard** [comment]
What's with the barricaded door on the paramedic officer?

**Comment by Kurfursten** [comment]
If you could see maint next to the surgical theater it's actually kind of an awkward place for a maint door (there are some grilles and racks in the way). Also, it would make the closets really crowded in the surgical theater. Previously surgery had no maint access at all on Bus - but I thought it might be fun to have an "abandoned" maint access that players can open up if they want.

**Comment by Kurfursten** [comment]
I did some testing and discovered 1 floating camera, 1 floating RC, one AI blindspot, and also that the cryo tubes are facing the wrong direction (thus disconnected from the pipes).

I will soon push a new commit that fixes these bugs, and, assuming no one else has further comments - request a NFD. This has already been talked to death in the previous issue.

**Comment by ihadtoregisterforthis** [comment]
Firelocks?

**Comment by Probe1** [comment]
I'm very surprised at how well this came out.  You had a real sharp eye when redesigning this

**Comment by SysadminJeroen** [comment]
It looks good, it looks very spaceous and many times better than the previous revision.

**Pull request merged**
