### PR TITLE
CMO and RD start with their unique coats equipped again

### PR DESCRIPTION
**Pull request by SonixApache**
undoes part of #15886

🆑 
 - tweak: The CMO and RD now spawn with their own unique coats equipped

### CODE REVIEW

**Comment by DrSnips** [comment]
I'm not opposed to them getting thier coats round start, I just did it to be consistant with other heads of staff needing to visit their lockers for their real coats save for the hos armor.

**Comment by Kurfursten** [comment]
Since you aren't removing them from the locker, there are now two of each

**Comment by DrSnips** [comment]
Id say having 2 existing is fine, most heads of staff have 2 coats and hos even has 3 at a time.

**Comment by Intigracy** [comment]
The CMO had two of each already before the change anyway, it's not really THAT big of a deal.

**Comment by SonixApache** [comment]
the roundstart one gets one
if someone gets promoted to head they get one too

**Pull request merged**
