### PR TITLE
Rapid-Fire Creampie

### PR DESCRIPTION
**Pull request by 9600bauds**
It's a banana pie mortar for the H.O.N.K.
A little more options for lighthearted clowning rather than clowntide&griff.

For once I find a "this is just awful" comment that wasn't made by me

### CODE REVIEW

**Comment by FudgePucker** [comment]
I always found it funny how the H.O.N.K. causes the most pants shitting horror from the crew.
The deathsquad mechs would cause less of a reaction.
But the second a H.O.N.K. shows up everyone starts running away screaming.

**Comment by AutismSpider** [comment]
You emp the honk to drain its cell or get stun lock to death by the HONKERBLAST

Death-squad mechs have very little stun to them unless rocket/mechshotgun blast hits you

**Comment by FudgePucker** [comment]
Still seems pretty odd considering death squad mechs are described as the last thing you see before you die, and it turns out that they are worthless compair- HHHHHHHHHHHHHHOOOOOOOOOOOOOOOOOOOOOOOOOOOOONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

**Comment by 9600bauds** [comment]
If anyone has anything to say against the weaponizing of banana pies, speak now or forever hold your peace

**Comment by FudgePucker** [comment]
Its not like its going to be over powered.
Oh no someone might abuse creampies, when in the exosuit fab its right by the HONKERBLAST, the best mecha weapon for anti personnel in the game.

**Pull request merged**
