### PR TITLE
Fixes items removed by monkeys from their backpack having a full-tile hitbox

### LINKED ISSUE #11976: Certain objects (shaker, bike horn, deck of cards) have fuckhuge 'hitboxes'
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5e01bf34bdfef989ba31f27eed62029ec59e28c3
> 
> General description of the issue
> Certain objects, like a deck of cards, the shaker and the bike horn have fuckhuge hitboxes that usually take up an entire table. It's annoying as fuck.
> 
> What you expected to happen
> Pick up my drink off a table with a drink and a deck of cards on a corner.
> 
> What actually happened
> Drew a card.
> 
> Steps to reproduce if possible
> Place a shaker, bike horn, or deck of cards on a table.

Has been like this for a month or so at the very least.

### PR DESCRIPTION
**Pull request by DeityLink**
Items now call the same attack_hand proc used by humans, I've tested and it seems to work perfectly fine.

This will probably fix that issue
Fixes #11976

:cl:
* bugfix: Fixed items removed by monkeys from their backpack having a full-tile hitbox.

### CODE REVIEW

**Comment by Exxion** [comment]
I don't think it does fix that issue since that issue had nothing to do with monkeys

**Comment by DeityLink** [comment]
@Exxion I suggest we open a new issue if the problem arises again. The last update on the ticket was 3 years ago.

**Comment by Exxion** [comment]
Yes, I just confirmed that it still happens following exactly the reproduction instructions given in that issue.

**Comment by DeityLink** [comment]
Oh, given your comments in the issue I had assumed that you had since finished your refactor and the monkey method was a different one. I can check it out.

**Comment by Exxion** [comment]
I didn't because I was stupid and tried to change way too much stuff at once
I can probably just do it for storage items only and fix this, but I don't remember for sure if there were any additional complexities

**Pull request merged**
