### PR TITLE
new way to choose religion

### PR DESCRIPTION
**Pull request by DamianX**
I always thought feeding opaque keywords into a BYOND text input based on instructions on the wiki was a very lazy way of doing things, so I banged my fist on the keyboard and shouted "There must a better way!" and this came out.

I didn't show it in the video because I forgot, but you can type things in the search bar in the top left and it matches against the religion name, the keywords, and the deity names.

https://user-images.githubusercontent.com/6307265/137641847-160e3d41-0527-42c8-b1b3-d453fc2d320f.mp4

:cl:
 * tweak: Improved the way chaplains choose their religion.

### CODE REVIEW

**Comment by kilozombie** [comment]
Wow this looks fucking fantastic

**Comment by Eneocho** [comment]
Can you also add what kind of Incense does that religion get to the info screen, please?

**Comment by DamianX** [comment]
I did?

**Comment by ShiftyRail** [comment]
I knew converting all these to datums back in 2017 would pay off.
I mean, it already did, but I never expected someone to actually code the UI I was thinking of at the time.

God bless.

**Comment by Eneocho** [comment]
> 
> 
> I did?

I need to get some better glasses because I swear to God I didn't see it.

**Comment by ghost** [comment]
may conflict with #29991

**Comment by Eneocho** [comment]
Any chance you could capitalize the conversion ritual and preferred incense? They're lowercase on the normal info screens but capitalized on the "Make your religion" screen.

**Comment by SonixApache** [comment]
just make this kill #29991, the poor PR has suffered for long enough

**Comment by DamianX** [comment]
> 
> 
> Any chance you could capitalize the conversion ritual and preferred incense? They're lowercase on the normal info screens but capitalized on the "Make your religion" screen.

done

**Comment by ghost** [comment]
will keys even still have a use or do we gut those too?

**Comment by DamianX** [comment]
>I didn't show it in the video because I forgot, but you can type things in the search bar in the top left and it matches against the religion name, the keywords, and the deity names.

**Comment by Kurfursten** [comment]
I did look over this pretty thoroughly. The only thing I have to grouse about is that ugly associative list that would be better datumized but it's not necessary. There's also the fact that you only included UI notes for Space Christianity when it would be nice if you included the bonuses other religions get like special hats, etc. but I don't think that's necessary to hold it up over.

**Pull request merged**
