### PR TITLE
Revert "Wizard Mode can now have groups of Wizards"

### PR DESCRIPTION
**Pull request by jknpj**
I, for one, welcome our old wiztended overlords. Feel free to state your opinion.

:cl:
 * rsdel: Reverts 'Wizard mode spawns a number of wizards proportional to the number of players'.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
The change (Wizard Mode can now have groups of Wizards) was made for a reason.
I don't think this is a good idea.

**Comment by SysadminJeroen** [comment]
Poll as per request of @jknpj: http://ss13.moe/index.php/poll/141

**Comment by Dacendeth** [comment]
What if it was single wizard, but high pop gave you free non refundable apprentice scrolls?

**Comment by aceedex** [comment]
Yes please, merge this shit. Wiz is an antag type that can and has dealt with a crew in hipop numbers. Not every wiz round needs to be raging mages and aside from the ei nath days current wiz is probably the strongest wiz has ever been

**Comment by Blithering** [comment]
Raging mages is raging for a reason, if you're wiz#3, you know that the station is gonna be forewarned and probably armed and hunting you, so you gotta pack light on the goofy gimmicks. Wizard mode should have some more wiggle room, but multiwiz kinda screws with this, as one person will want to go for a stealthy wizard, one will want to put on the clown robe and challenge the clown to a shoe collection competition for the prize of the final spell in the spellbook, and then the third guy can hit the summon guns button and its all over but the crying. 
One solution to this could be either to have one wizard with scaling spell points, or to have free apprentice scrolls spawn dependant on the population so they can be a team. 
**also liches when**

**Comment by clusterfack** [comment]
Give wizards an extra 20-25% spell points for every 15 players above the starting 15

**Comment by SonixApache** [comment]
yeah woohoo i love playing extended except everyone is armed with shotguns because the antag is dead and there's no suspense because they know it's extended

reverting is a fucking stupid idea, it doesn't tackle the core issue that got it merged in the first place

**Comment by Diavill** [comment]
>suspense
yeah i love 3 wizards buttraping the station with fisting invisible MY ON CLONS and the third one's a retard """""friendly"""""" wizard
im totally fucking suspended

**Comment by SonixApache** [comment]
antags murderizing you > antags are dead, hooray for chaos extended

**Comment by jknpj** [comment]
It's like i'm really playing CM

**Comment by Accipitermaris** [comment]
Right now, we have two MultiWiz gamemodes:
>[04:15:13]ADMIN: Failed to start a round of Ragin' Mages. Only 3 players ready out of 15 needed.
>[04:15:13]ADMIN: Failed to start a round of wizard. Only 3 players ready out of 20 needed.

This double whammy combo of 15 and 20 really kills the roundtype variety of prime time EST pretty hard whenever there's 20-24 people ready in the lobby. I actually used to really hate SoloWiz, especially SoloGunWiz, but I think I would prefer it now to missing out on other gamemodes in the Highpop timeslot.

wombo combo

**Comment by CptWad** [comment]
just have old 1 wizard but with 2x the spells available
keep ragin as is

**Comment by ghost** [comment]
so sonix do you only play for getting killed by antags and hunting antags?

most people don't, there's nothing worse than getting home and having time to play a full round and then instead it's wizard/raging 3 times twice in a row and it's just a murderbrawl ending in 20 minutes. at least in my opinion that sucks.

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/62d27fba15772acd146f01987a6abbe76598d35e/code/game/gamemodes/wizard/wizard.dm#L12
https://github.com/vgstation-coders/vgstation13/blob/58def87fedc25b491eb63abd0a369a82b2c90558/code/game/gamemodes/wizard/raginmages.dm#L5
This is bad.

**Comment by ghost** [comment]
just remove raging mages or wizard.  That, or make it to where if pop it 20+, then regular wizard won't roll.

**Comment by ghost** [comment]
What cluster and wad said and maybe a message to advise them to use it for fun and not straight up balls to the wall deathmatching. With more points you can take more stuff so you can still get away while still being an obnoxious prankster without well there's my jaunt, there's my kill spell now I have 3 slots to try and make something that isn't boring or shitter but wont be insta-ganked. Free my nigga lighting'd glow orb stripping

If it's not too much trouble  jknpj, could you implement an admin toggle for it like tirumvirate?

**Comment by aceedex** [comment]
Or just take 5 mutate 5 jaunt 5 blink and bind a gun to you

**Comment by ghost** [comment]
Some day we'll get more of the old stylin' wiz rounds

**Comment by Blithering** [comment]
I think that multi wizard could be reworked into a high pop team mode, some kind of prank squad with more esoteric objectives like turning a percentage of the station into clowns or stealing the captains butt, but in the current 15-20 ready slot a single wizard at a time is enough

**Comment by Arthurdentist** [comment]
If you wanted a separate multi-wizard mode then I would suggest something like this. I've suggested it before but I still think its an alright/10 idea. 

## Wizzard Wars :tm:

The federation is running a test to determine which wizards are ready for advancement, and they've decided to use Space Station 13 as this year's proving grounds. 

You are one of the wizards looking for a promotion, and the rules are simple enough. You have to get onto the station, locate a magical hat (or some other mysical item) which has been teleported on the station, and escape with it. 

The catch? You aren't the only wizard looking for promotion. Its Wizard against Wizard, every man for himself, one objective and one winner. 

So in summary:
1.  A number of wizards spawn, and each wizard has the same objective. Only one of them can win.
2. The wizard who escapes the station with the objective secures the greentext, any other wizards are pathetic failures
3. The crew aren't necessarily the target, but they are caught up in the middle of the wizard war. The crew wins if all wizards are dead and / or the wizards fail to escape with the objective. 
4. The wizards can fuck with the crew just like in any other round, but their ultimate goal is to secure the greentext against the other wizards, so they are not just causing grief for the crew, but they are also trying to secure their prize and kill / defeat their competition. 

This would probably necessitate some 'mode specific balancing', in the same way that summon guns isn't available in raging mages, you might want to restrict access to certain items and spells here too, but with a lot of work I believe a mode like this could be a fine replacement for high-pop solo wizz. You could then revert normal wizzard back to being by himself for solo shenanigans.

**Comment by Arthurdentist** [comment]
Notwithstanding my dumb autistic ramblings about alternative wizard modes, I think that making the revert here is a good idea

**Comment by Hugh-G-Rection** [comment]
I've always felt that single wiz has the most potential for unique gimmicks, and without a doubt have consistently been the most fun I have as antag.  With the right spells and gameplan, you can become the rounds Dungeon Master, choosing the fate of all those onboard.

But with more than one wizard, the general idea seems to be "If I try to do a gimmick the other wizard's crazy antics are going to fuck me over. Oh well guess I better get CUHRAZEE"

**Comment by chesse20** [comment]
please add ragging mages so theres more wizards than not wizards at the end of the round i LOVE THE RAGING mages

**Comment by ghost** [comment]
@jknpj why did you close this when it had overwhelming support not only in the vote here but on the server?

**Comment by jknpj** [comment]
Role Datums

**Pull request merged**
