### PR TITLE
Revert "Make objects burn if they overheat past the autoignition point and there's oxygen"

### PR DESCRIPTION
**Pull request by SonixApache**
sparks from defibs / hacked vendors keep qdelling everything
make the system better before this gets merged and you can throw a `closes` in your PR body
@xXxEMBERGHOSTSQUADDIExXx

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Finally, a downside to defibbing; burning all the clothes

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
I added a non burning category or sparks in that pr and gave it to portals to prevent the wormhole event from destroying the station
I can make a pr adding that to other spark sources if you give me a list
I deliberately left telesci teleporting as is to make things more chaotic but thats another potential one

Also note that all of these could already and still can ignite plasma in the air

**Comment by Eneocho** [comment]
Definitely make the defib (at least the non-emagged one) spark safe.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
See here on how to do this
(Set surfaceburn=FALSE in the spark() proc argument)

https://github.com/vgstation-coders/vgstation13/blob/cf75ea1879ce02aed749fe95147434d1bd79109e/code/game/objects/effects/portals.dm#L133

**Comment by DorainGrey** [comment]
Question, what is it that has such a low autoignition temp that is igniting medbay @SonixApache

**Comment by GreatBigFailure** [comment]
It seems like sparks are the specific issue, the rest of it has been working pretty well from what I've seen.
Sparks are definitely very abusable right now. It's hilarious but probably should be fixed. I'd say just nerf sparks as a heat source over-all, there's been some really goofy things starting fires.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
One more thing that I need to look at and fix is wooden floors occasionally igniting but not going out

**Comment by brndd** [comment]
>hack into CE's room to open secure engineering
>the door sparks
>the sparks ignite the folder on the desk
>the ensuing fire kills Poly before I can find the test wire and open the door

**Comment by Exxion** [comment]
Sparks just have a crazy high temperature. Just reduce it from 1000K to 500K. That's lower than any of the autoignition defines.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
> > hack into CE's room to open secure engineering
> > the door sparks
> > the sparks ignite the folder on the desk
> > the ensuing fire kills Poly before I can find the test wire and open the door

lmao

**Comment by SonixApache** [comment]
i will defer to the other two open PRs that solve this issue peacefully

**Pull request closed without merging**
