### PR TITLE
Adds a new corgi-flavoured life creating chemical

### PR DESCRIPTION
**Pull request by ghost**
[content]

Recipe is 1 part aminomicin and 3 parts bone marrow (a corgi's treat)
When mixed with nutriment as usual, does the same process but creates corgi puppies

:cl:
 * rscadd: A new chemical recipe has been discovered allowing for the creation of a man's best friend, especially those who command personnel.

### CODE REVIEW

**Comment by Eneocho** [comment]
Does this mean I can release the dogtide, powered directly by Danitos?

**Comment by Eneocho** [comment]
The name feels too close to Aminomicin. Could be Aminomicorg.

**Comment by ghost** [comment]
> The name feels too close to Aminomicin. Could be Aminomicorg.

It's a pun on Ian, but aminomicorgian works too or something

**Comment by Eneocho** [comment]
Aminomicorgian sounds good.

**Pull request merged**
