### PR TITLE
[BOX] Ungas the vox

### LINKED ISSUE #3799: [Box, probably others] Vox storage room has non vox flooring, thus the atmos alarm at round start.

### PR DESCRIPTION
**Pull request by Exxion**
First, replaces the floor in the vox storage room with vox flooring. Second, adds an atmosphere alarm to the trading post hallway because there wasn't one.
Taxi's trading post is atrociously fucked, but, surprisingly, not in this way. Too much to fix right now. I'll work on it later if nobody else does first.

EDIT: I forgot
Fixes #3799.

### CODE REVIEW

**Comment by PJB3005** [comment]
:+1: 

UNGAS THE VOX

**Comment by Exxion** [comment]
@d3athrow is racist against vox and is delaying the merge of a 31-line-change pull just because it helps them
REVOLUTION

**Comment by Boxe** [comment]
but then the N2 will spread into the EVA general area and then the misproportion will trigger my super-autism and then everything is terribleee

**Comment by Exxion** [comment]
Not sure how the N2 from the trading post on an entirely separate Z-level from the station would make its way to the station

**Comment by Boxe** [comment]
>First, replaces the floor in the vox storage room with vox flooring.

i thought it was talking about that tiny spot in the station EVA

ok i'm fine

**Pull request merged**
