### PR TITLE
Magic is stored in the ass

### LINKED ISSUE #29280: [Feature Request] Magic is stored in the ass
#### Request
Fairly self explanatory, a request for magic to be stored in the ass so that you can disarm a wizard by removing their ass, thus being able to pacify wizards through other means than muzzling, implants, et al. I think anything that prevents straight round removal is a healthy thing for the game, especially for a mode like wizard.

Optionally, if you could receive a random spell they had upon wearing said magic ass on your head, with the ass being a condition for casting said spell, I think it'd be an interesting thing to add. Could also go the angle of magical ass burgers granting you the spell as well.

<featurerequest>

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Wizard spells are now stored in the ass. To remove a wizard's spells, simply remove its ass. Applying the magical ass to someone will give them the spells stored in the ass.

## Why it's good

Offers the crew a new way to eliminate the threat a wizard poses without having to kill the wizard.
Closes #29280.

## Changelog

:cl:
 * rscadd: Wizard spells are now stored in the ass - remove a wizard's ass to remove its magic.

### CODE REVIEW

**Comment by MercuriusGH** [comment]
I can already see more bloodshed being caused by people fighting over the magical butt than the wizard himself.

**Comment by wotisjanitor** [comment]
Does this prevent wizborgs from existing?

**Comment by west3436** [comment]
> Does this prevent wizborgs from existing?

It doesn't but it should; I will work on that

**Comment by boy2mantwicethefam** [comment]
Prepare for unforeseen consequences.

**Comment by Eneocho** [comment]
Could you make it so wearing the ass as a hat gives you access to 1 (only one) spell the wizard had, since you are channeling the ass but don't have it as /your/ ass?

**Comment by west3436** [comment]
> Could you make it so wearing the ass as a hat gives you access to 1 (only one) spell the wizard had, since you are channeling the ass but don't have it as /your/ ass?

No!

**Comment by angryturnip** [comment]
Could this be expanded upon in the future to let admins vv clothing items to give/remove spells based on if someone's wearing it or not?

**Comment by west3436** [comment]
> Could this be expanded upon in the future to let admins vv clothing items to give/remove spells based on if someone's wearing it or not?

No, it is not designed like that currently

**Comment by djkramer123** [comment]
Do ass removed wizards still provide power on conduction plates?

**Comment by west3436** [comment]
> Do ass removed wizards still provide power on conduction plates?

That feature is unchanged

**Comment by wotisjanitor** [comment]
This is super gay, this makes wizard borgs impossible, so there is no longer any danger in borging them. Total loss of soul

**Comment by SonixApache** [comment]
i think it's funny but i also think 'magic' should be stored in the appendix, with wizards getting a special magical appendix

**Comment by Kurfursten** [comment]
> > Do ass removed wizards still provide power on conduction plates?
> 
> That feature is unchanged

The previous implementation was to check if they have a wizard role, but if there's nothing special about being a wizard and you can get all the magic just by having their ass, you should update the plates so that it only checks if you have a magic ass.

What about other powers like genetic powers? Are they impacted?

**Comment by west3436** [comment]
> The previous implementation was to check if they have a wizard role, but if there's nothing special about being a wizard and you can get all the magic just by having their ass, you should update the plates so that it only checks if you have a magic ass.

Yeah alright, can do


> What about other powers like genetic powers? Are they impacted?

No - this specifically removes wizard powers only.

**Comment by ShiftyRail** [comment]
Bit silly tee bee heach, but it has support, seems to prevent wizborgs (which is kind of a good thing), allows for pacified wizards (why not?).
I liked magic being stored in the torso better, though.

**Comment by Kurfursten** [comment]
You merged it too soon, he didn't fix the engine

**Comment by west3436** [comment]
> You merged it too soon, he didn't fix the engine

Toss an issue report if you want I'll get a fix in next time I have a chance either tn or tomorrow

**Comment by ghost** [comment]
@Kurfursten @ShiftyRail this honestly should've been a subject for a server vote. The regular non-antag crew can now easily obtain OP antag powers they were never meant to have and use them to powergay/validhunt everyone else into oblivion. Imagine being able to gain vampire abilities via blood transfusion or something similarly silly.
This also:
1. Removes wizborgs, which is lame and is good how exactly?
2. This also makes Butt-Bot's Revenge literally the strongest spell and a must-have during CWC because a single assblast is enough to permanently neutralize any other wizard;
3. You can already pacify a wizard with a special trader item, which Shifty would have known about had he actually kept track of the codebase or actively played the game;
4. Has a 14:9 like/dislike ratio but looks like that only counts whenever collabs decide it should count so forget it.

**Comment by Kurfursten** [comment]
You are correct, emojis only count when collabs decide it should count. This is official policy since the July admin meeting. Emojiocracy is ended.

I'm not personally a fan of this PR (I actually share 2 of your views) but Shifty did nothing wrong here. Let it play for a week and you can open a revert request on 3/3. Maybe after seeing some assistant ring of fire the bar you will galvanize support for a revert.

**Comment by Eneocho** [comment]
Perhaps butt-bot's revenge should be blacklisted for CWC.

**Pull request merged**
