### PR TITLE
Adminspawn-only proc call gun

### PR DESCRIPTION
**Pull request by ghost**
[content][administration]
outpaet
Adminspawn only, requires DEBUG to change the proc call on the gun as an admin.

### CODE REVIEW

**Comment by gurfan** [comment]
INSTAGIB WHEN?

**Comment by Eneocho** [comment]
Is it possible for this gun to cause people to hear a BWOINK?

**Comment by ghost** [comment]
> Is it possible for this gun to cause people to hear a BWOINK?

Call playsound_local on the target fired at, so yea.

**Comment by Eneocho** [comment]
Incredibly based. I'll use the goonecode wish to get the  gun with the bwoink sound effect then.

**Comment by Eneocho** [comment]
Can it call more than one proc?

**Comment by ghost** [comment]
> Can it call more than one proc?

Don't like this idea.

**Comment by Eneocho** [comment]
> > Can it call more than one proc?
> 
> Don't like this idea.

There goes the BWOINK+cluwne gun.

**Pull request merged**
