### PR TITLE
ACTUALLY fixes #8017 this time, tested

### LINKED ISSUE #8017: PA console sprite issue
the Particle Accelerator Control Computer appears at the start of the shift with the wrong sprite (as active); if you wrench it, it will be shown with the right sprite (as inactive)

particle accelerator control computer

i saw it on boxstation, i can assume it's the same on all the stations.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #8017

The icon it's showing up as looks exactly like the powered icon except the wires are on the left instead of the right........

So I just removed that icon_state because fuck that.

### CODE REVIEW

**Comment by clusterfack** [comment]
Is the update icon in new actually necessary then

**Comment by Intigracy** [comment]
Yes.

**Comment by gbasood** [comment]
Because

**Comment by Intigracy** [comment]
The initial icon_state is the computer is working one, but it's used as
reference for changing all the other ones. Need to update on new() so it
has the correct one.

**Pull request merged**
