### PR TITLE
Moves from extools to auxtools

### PR DESCRIPTION
**Pull request by Exxion**
extools is no longer supported and doesn't work properly in the latest versions of 513 or any versions of 514. The new version is auxtools. The three things we used from extools were:
* Maptick. This has been replaced with the internal BYOND version introduced in 514. Obviously this PR thus requires 514 and should not be merged until we update.
* Debugger. auxtools has a debugger which is allegedly better than extools'. ~~It is, however, broken on the latest 514 build. I'll update this PR once a patched version is out.~~ Nope, it was something else, which is fixed now anyway.
* Reference tracking. Unfortunately, there's no replacement for this. It was buggy to the point of being almost unusable, but it was still nice to have around. Maybe auxtools will get it someday.

This won't compile until the CI is set to use 514, which shouldn't be done until the server is updated to 514. This'll probably be a while.

### CODE REVIEW

**Comment by sohpeach** [comment]
There are instructions on how to add the auxtools debug server to a codebase @ https://github.com/SpaceManiac/SpacemanDMM/wiki/Setting-up-Debugging. You've just done a couple of things differently:

1) You're missing `/proc/auxtools_stack_trace` which allows runtimes that happen inside auxtools to be shown in your dreamdaemon window or error log (it'd just crash without it.)
2) Instead of shipping the dll yourself you can use the AUXTOOLS_DEBUG_DLL env var, which allows for updates to the debug server to be shipped through SpacemanDMM.

**Comment by Exxion** [comment]
Oh, I was going by the guide in the original PR where it just used regular `stack_trace()`. Perhaps that's why it's been crashing constantly.
That's all you have to do to use the env var? It's set automatically?

Thanks for the help.

**Comment by sohpeach** [comment]
The env var is set by SpacemanDMM when it launches the game

**Comment by Exxion** [comment]
That was apparently not why it had been crashing constantly, but I'm sure it would have crashed later had it gotten there. Thanks again.

**Comment by sohpeach** [comment]
I don't actually know any instances where auxtools' debugs server would emit a runtime atm, so I'd suspect the crashes to be something else. Let me know if you can reproduce it.

**Comment by Exxion** [comment]
I can definitely reproduce it reliably, but I'm much less sure I could narrow it down to a particular cause or make a minimal reproduction project. It happens often (but not always) when hitting a breakpoint running this codebase on 514.1545. I imagine it would also happen on any other SS13 codebase, but I'm not sure. One reliable way to reproduce it is to put a breakpoint in `/atom/Click()` and join the game and click on something. (It doesn't happen if you click something in the lobby as a `new_player`, for some reason. You have to actually join the game.)

**Comment by sohpeach** [comment]
Doesn't seem to happen on 1543 (the only version I've tested auxtools against so far), I'll try 1545 tomorrow.

**Comment by Exxion** [comment]
I'm not sure if you ever got around to testing it, but it actually does not appear to be version-dependent. Crashes for me on 1543 as well.

**Comment by sohpeach** [comment]
I can't reproduce any crashes, but there certainly is a huge hang when the breakpoints are being hit (sometimes even up to 30 seconds.)

The hang only seems to happen when inside procs like `/atom/Click`, other places like `/datum/controller/master/proc/Loop`'s main loop work fine, so it's gonna be something weird. I'll look into it further this week 4 reals.

**Comment by Exxion** [comment]
Did you ever get around to looking into it?

**Comment by sohpeach** [comment]
I've got a new debug server release lined up which does include a crash fix, but I'm not really sure it's the one you encountered. I want to look into this properly before said release, but you can try it now locally by downloading the build artifact from https://github.com/willox/auxtools/runs/1996159343 and loading the included DLL directly instead of using the env var from SpacemanDMM.

**Comment by Exxion** [comment]
No, that does not appear to fix this particular crash. I'm guessing the crash I'm observing and the hang you're observing are the same issue, and just for some reason present differently on our machines.

**Comment by sohpeach** [comment]
I've just tried the build I linked on 1543 and 1548 but I can't reproduce this issue whatsoever ¯\\_(ツ)_/¯

**Comment by Exxion** [comment]
So that build fixed the hang you saw before? Guess the crash and hang weren't related, then. I'll see if I can get a debugger to tell me more about the crash later.

**Comment by Exxion** [comment]
I finally got around to looking into it with a debugger. It looks like, for some reason, an exception is being thrown in the `eprintln!()` in `Server::notify()` when a breakpoint is hit, but only in certain conditions. If you want more information, I need specific instructions; I'm not very experienced with this kind of debugging.
Did you try it specifically on /vg/station code, or just a different codebase?

**Comment by sohpeach** [comment]
I tried on this PR's branch. eprintln panicked? That's... odd. I'll go hit a few thousand breakpoints and see if it happens.

Edit: Nothing at all. I tried the atom/Click method again too. What makes you think eprintln was causing an issue? A stack trace?

**Comment by Exxion** [comment]
The stack view on the debugger when it paused due to the crash, yes. Print functions inside `Server::notify()` were the last ones before everything had panic in its name.

**Comment by Exxion** [comment]
Oh wait, you tried it on this branch? Did you set `DEVELOPER_MODE` in `compile_options.dm`? As it's set up here the debugger is disabled unless that define is true.

**Comment by sohpeach** [comment]
> Oh wait, you tried it on this branch? Did you set DEVELOPER_MODE in compile_options.dm? As it's set up here the debugger is disabled unless that define is true.

Yeah. The debugger wouldn't work otherwise.

**Comment by sohpeach** [comment]
Try again and show me the stack trace I guess. You can also save a dump of the process using Visual Studio and email me that if you want.

**Comment by Exxion** [comment]
Sent you the dump. Hopefully that will shed some light on the issue.
It's the latest release from the GitHub by the way.

**Comment by sohpeach** [comment]
Is it possible that your spacemandmm extension (the language server) is crashing for some reason just before this? If you're launching directly through the extension it, the extension itself is what owns the stdin and stderr streams so it might be that they are being closed by something like that.

**Comment by Exxion** [comment]
That's possible, but then what would cause that? It happens consistently, so there must be something specific causing it. Maybe the extension dies if it gets sent too large a call stack or something? But then why is it only happening for me?

**Comment by sohpeach** [comment]
Well, it won't be too hard to narrow down if we stop the debugger from crashing first. There's no need for the debugger to write to stdin or stdout so I'll remove that later today in a new release.

**Comment by Exxion** [comment]
I have noticed that whenever I join the game, this is printed to the debug console:
```
[05c35d1c] core libvlc debug: VLC media player - 2.2.4 Weatherwax
[launched stderr] stream did not contain valid UTF-8
```
And it is only after I join the game that hitting a breakpoint causes a crash. Perhaps something is breaking the stream somehow, and then the next time the debugger (or anything else) tries to print to it, it crashes.

**Comment by sohpeach** [comment]
Perhaps the langserver is closing the stream when it encounters this invalid utf-8. I'm undecided on whether to fix it on the spacemandmm side or to still gut the logs from the debug server, but will probably do both.

What's libvlc btw? Does it hook into all programs you run?

**Comment by Exxion** [comment]
No, it's the VLC media player used for streaming media on /vg/station. You can choose between WMP and VLC in options, and VLC works better, but it defaults to WMP because VLC needs to be downloaded.
Incidentally, while writing this comment, I tried using WMP instead and it does not crash upon hitting a breakpoint in that case. Sounds like the langserver doesn't like receiving invalid UTF-8, and the masterfully-made VLC breaks it.

**Comment by sohpeach** [comment]
Alright, I'll make the necessary changes to spacemandmm to not crash on this later.

**Comment by Exxion** [comment]
Many thanks.

**Comment by sohpeach** [comment]
That fix should have been live since last week

**Comment by Exxion** [comment]
Nice. Thanks again.
That makes this PR ready to merge whenever we update to 514.

**Comment by Kurfursten** [comment]
I think @ShiftyRail was talking about wanting to move to 514 soon

**Comment by gbasood** [comment]
please

**Comment by Eneocho** [comment]
Exactly 4 months. Good shit.

**Pull request merged**
