### PR TITLE
Removes oxagent and volatile fuel.

### PR DESCRIPTION
**Pull request by ghost**
Never heard of them? That's because they were essentially unused gases, save for the napalm reaction spawning some volatile fuel (which I'm not sure even worked since the gas would just dissipate across the room, now it spawns fuel puddles which probably fit a lot better).

### CODE REVIEW

**Comment by Eneocho** [comment]
i swear I remember seeing someone doing some fucky atmos/chem wizardry to get volatile fuel in a canister once

**Comment by west3436** [comment]
Volatile fuel has some very nice applications as "flammable gas that isn't plasma" that can be used in the future; I don't see any benefit in removing it.

**Comment by ghost** [comment]
Downside: clutter now that all gases are displayed on various atmos machinery. 
If someone needs non-plasma flammable gas in the future they can re-add it, plus it should probably be changed so flammable gases aren't hardcoded and have flags in XGM instead (or are otherwise dynamic).

**Comment by clownisrogue** [comment]
I use these

**Comment by SonixApache** [comment]
get exxion to finish XGM (or help him do so)

**Comment by ghost** [comment]
Wdym, I already added XGM support to all atmospheric devices in cryotheum. Which should be compiled on the server shortly.

**Comment by west3436** [comment]
The people long for their volatile fuels and oxagents

**Pull request closed without merging**
