### PR TITLE
Adds two more generalized sanity procs, fixes some improper sanity calls

### LINKED ISSUE #5254: (WEB REPORT BY: banditsuit REMOTE: 198.245.63.50:7777) Cannot view security terminals from a wheelchair, possibly others
Tried to access the advanced security cameras in sec on taxi and I can't use it

>What you expected to happen
For it to let me use the advanced security cameras

>What actually happened

>Steps to reproduce if possible

### LINKED ISSUE #5256: (WEB REPORT BY: banditsuit REMOTE: 198.245.63.50:7777) Cannot take items off of others from a wheelchair
>Revision (Should be above if you're viewing this from ingame!)
c8b370ba3ecb11bc2760ab27db3ad4e58be517c9

>General description of the issue
Inability to take items off of others from wheelchair

>What you expected to happen
Take items off of others from wheelchair

>What actually happened
The inability to do so

>Steps to reproduce if possible
Try to take items off of someone from a wheelchair

### LINKED ISSUE #7153: Rightclick>Pickup not working while on janicart
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Picking up items via RMB diesn't work while in the janicart. Same with pointing at things &maybe other stuff
> 
> What you expected to happen
> To be able ti pick stuff up via the RMB menue
> 
> What actually happened
> Nothing
> 
> Steps to reproduce if possible
> Sit on janicart try to pick something up or point at something via the right mouse button menue

### PR DESCRIPTION
**Pull request by 9600bauds**
isStunned(): Returns 1 if the user is unconscious, faking death, paralyzed, stunned, or weakened.
incapacitated(): Returns 1 if the user isStunned() or restrained.
Hopefully these can be used as a better standard than the current mumbo jumbo we have of everything checking paralysis || stunned || weakened and shit.
Basically, using canmove as sanity is TERRIBLE.

Fixes #7153
Fixes #5256
Fixes #5254
Better fix for #6378

### CODE REVIEW

**Comment by clusterfack** [comment]
Merge this when you feel it's ready

**Comment by 9600bauds** [comment]
Ready for now

**Comment by 9600bauds** [comment]
Or rather, I'm done with it if there aren't any issues with it

**Comment by gbasood** [comment]
Looks good to me for the most part, not sure about the consequences to simple animal movement check though.

**Comment by 9600bauds** [comment]
If resting or locked_to are true, then canmove is surely also true, thus "!resting && !locked_to && canmove" is unnecessary

**Pull request merged**
