### PR TITLE
Removes Meteor

### PR DESCRIPTION
**Pull request by TheFriggenSawbones**
fuck you dylan
#10132

### CODE REVIEW

**Comment by Praecordia** [comment]
the absolute _madman_

**Comment by Eldzen** [comment]
Sawbones did something right

**Comment by Probe1** [comment]
how the living fuck did you manage to get conflicts in 7 minutes

**Comment by SkowronX** [comment]
I'm curious to know what sort of outcome you expect.

**Comment by Praecordia** [comment]
it's a political statement
like tank man in china

**Comment by Konater** [comment]
Can you remove malfunction and raiders while you're at it?

**Comment by TheFriggenSawbones** [comment]
@Konater thats for another day

**Comment by SkowronX** [comment]
@Praecordia you mean the political statement that cost the lives of numerous protesters? Seems accurate.

**Comment by Orangerush** [comment]
Madman

**Comment by TheFriggenSawbones** [comment]
@SkowronX the only man dying today is dylan

**Comment by ScrambledSteak** [comment]
Do it
Fuck you Dylan you fridge hating shit

**Comment by kol1th** [comment]
CONFLICTS GO HOME

**Comment by 9600bauds** [comment]
Is this tested? I don't think this will actually work, at least not in a way that causes a shitton of errors

**Comment by TheFriggenSawbones** [comment]
I'm pretty sure it'll break everything - much like how Dylan's meteors breaks our will to continue playing

**Comment by kol1th** [comment]
merge it

**Comment by SangriaMonkey** [comment]
:ok_hand:

**Comment by Boxe** [comment]
:eggplant:

**Comment by Kurfursten** [comment]
I looked at the code and I can't understand how this compiles, because apparently it doesn't remove the normal meteor event but removes all the meteor types. Unless the meteor event uses spawn_meteor, but then why does THAT compile? Either case I don't want to lose the normal event.

Someone who knows meteorcode better should explain the implications.

**Comment by Praecordia** [comment]
@Boxe please don't use such phallic imagery in your comments, it's very triggering

**Comment by SplergeBucket** [comment]
my metaclub sources are telling me that mrpain is gunna permaban you if this pr goes through

**Comment by ghost** [comment]
Meteor code is pretty well self-contained, although the approach taken here is amateurish at best

It will most likely generate runtimes. I'm surprised it doesn't throw a compile error from the meteor event since it's supposed to use those methods, but I guess Dreammaker knows what it is doing, somehow

**Comment by cowboybuttsdrivemenuts** [comment]
merge when

**Comment by SplergeBucket** [comment]
go remov metoeryhs iurselg then
the CONFLICFTS ARE WORHT THIT

**Comment by TheFriggenSawbones** [comment]
@dylanstrategie obviously only an amateur would think this code is amateurish at best jesus fucking christ dylan learn the caveats and secret rituals of byond coding and maybe you'll be allowed to fuck with fridges without retaliation

**Comment by SplergeBucket** [comment]
a5f466075db692989ae9e3f3753929da
my pagan witch curse has taken place
this code will be accepted as acceptable after i kill this potato goat

**Comment by ghost** [comment]
@TheFriggenSawbones Just deleting three files is going to cause a bunch of issues, that code isn't 100 % modular. For that matter, even the modules aren't

**Comment by TheFriggenSawbones** [comment]
i have to salt the earth to get rid of your code, and by god it's worth it to bring fridges back to their correct level of robustitude i can't believe you were allowed to get away with it.

**Comment by PJB3005** [comment]
@Kurfurst it isn't compiling though, Travis doesn't run when there's conflict.

**Comment by Imagebard** [comment]
>Muh Fridges

Just admit it that fridge wouldn't have survived a 2nd blast.

**Comment by xpcybic** [comment]
Not nearly enough meme tags on this

**Comment by PJB3005** [comment]
Alright.

**Comment by 9600bauds** [comment]
But controversial is for PRs where there's controversy

**Comment by PJB3005** [comment]
#rekt

**Comment by ScrambledSteak** [comment]
please gib write access to sawbones he clearly knows what he's doing

**Comment by NigglyWiggly** [comment]
:grimacing: :ok_hand:

**Comment by ComicIronic** [comment]
Sawbones now owns the rights to the code and will be the only collab on the repo

**Comment by icantthinkofanameritenow** [comment]
I fail to see how this can end badly.

**Comment by Intigracy** [comment]
Remove the mode not the event.

Jesus.

**Comment by Imagebard** [comment]
This isn't a serious PR anyways
And who the fuck even likes the event

**Comment by MercuryDoll** [comment]
I like the event when i play engineer on extended.

**Comment by PJB3005** [comment]
More meme tags!

**Comment by 9600bauds** [comment]
I keep hitting the "Merge pull request" button but it's not working, should I make a bug report?

**Comment by PJB3005** [comment]
Okay we reset the master branch to wherever we need for this to stop conflicting, then merge ASAP.

**Comment by icantthinkofanameritenow** [comment]
I think we need more tags.

**Comment by Megamaw** [comment]
Wow, removing something!

At least this time, it's something no one likes, unlike skeletons.

**Comment by 9600bauds** [comment]
Give it a rest

**Comment by Megamaw** [comment]
Never!

**Comment by ComicIronic** [comment]
RIP meme PR

**Comment by ghost** [comment]
It was REALLY never meant to be

Meteors 1 - Sawbones 0

**Pull request closed without merging**
