### PR TITLE
Diona bugfix 2.0 : fix #6911

### LINKED ISSUE #6911: Diona nymph inhand inconsistency
The shoulder the nymph is sitting on changes depending on whether the holder is facing north/south or east/west.

image
image

Both were taken with the nymph in the left hand.

### PR DESCRIPTION
**Pull request by TheEliminator16**
- Fixes a sprite issue with diona nymphs riding on shoulders

### CODE REVIEW

**Comment by TheEliminator16** [comment]
Well that's certainly unexpected. Why am I too dumb to make a PR that works?

**Comment by clusterfack** [comment]
It's not you, travis is fucking up at the moment

**Comment by TheEliminator16** [comment]
Oh, so just give it a while?

**Comment by clusterfack** [comment]
It passed one of the four so it's fine

**Comment by TheEliminator16** [comment]
It can be merged even if travis fails?

**Comment by clusterfack** [comment]
Yes

**Pull request merged**
