### PR TITLE
Removing virus symptoms on request

### LINKED ISSUE #12861: Remove Hanging Man's syndrome from the list of disease effects
#### Description of issue

Hanging Man's syndrome essentially replaces all th_ v_w_ls _n ___r sp__ch w_th _nd_rsc_r_s. It's a bad symptom in many ways.

Comms are meant to be auditory. All the other comms-affecting diseases are auditory. Almost all the stage four syndromes make you sniffle or wheeze or some shit in a way that everyone around you _hears it_. Some of them capitalize your words because you're screaming loudly. Broken radio traffic scrambles letter casing and order to simulate static. But underscores don't _mean_ anything, they're just underscores. They break the fourth wall by forcing the player to acknowledge that they're reading underscores, and oh, how funny, hanging man's syndrome, get it, haha, instead of being immulsioned in the game.

They also encourage stupid workarounds after the initial five seconds of panic. In my experience when a virus with this syndrome ravaged the station, people just started "going with the flow" with the virus by using leetspeak to prevent writing things that won't transmit, which is even more cancerous. Another problem is that this symptom doesn't really show any mercy; most symptoms in stage 2 have a percent chance of activating per processing tick and add up their effects fairly incrementally. Hanging man's just kills your comms without any randomness or luck involved, until you get cured.

Essentially, the symptom is a gag, too blunt, pulls you out of the fourth wall, and drags down the standards for the rest of the viral symptoms. There's certainly space for joke symptoms, but most of what's gotten added recently is gags like being turned into an anime girl with a katana, or a roundhouse kick disease, etc., which makes people approach virology with the mindset of "what's the funniest, most pop-culture-referencing symptom I can make", instead of "what would be an interesting, terrifying, or _space-worthy_ symptom"?  This is srs bizness, after all. 

And finally, if you scream, you end up saying "____________________!" This alone is enough of a reason to can this shit effect.

To fix, just comment the virus out here: https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/virus2/effect.dm#L943

### PR DESCRIPTION
**Pull request by ghost**
Now that there's been some time for players to get used to the symptoms, seems they were ill received, so removing them on request after a hefty response of 'remove' via an issue report, and the thread (from which the ideas were conceived)

fixes #12861 

:cl:
 * rscdel: Hangmans Syndrome, Pro-tagonista, and Spyndrome have now been removed after request.

### CODE REVIEW

**Comment by Probe1** [comment]
I liked the gyro one.

**Comment by ghost** [comment]
Too similar to existing symptoms

Then the other were not similar enough to existing symptoms

**Comment by Shadowmech88** [comment]
>after a hefty response of 'remove' via an issue report

Four people is a hefty response?

**Comment by ghost** [comment]
Only took 1 to give the ideas

**Comment by kol1th** [comment]
What's wrong with them again? Did someone in deadchat complain about it?

**Comment by Arthurdentist** [comment]
why remove all of these because a guy complained about one of them specifically?

thats real daft

**Comment by 9600bauds** [comment]
I think Gyro-syndrome and CatbeastButWorse-syndrome are alright, but man, I kinda hate the hangman thing and didn't want to say anything before.

I don't mean any offense to you, I just think it's not a good concept.

**Comment by Intigracy** [comment]
Roundhouse kick is fine, the katana spawning one is the only one I have any real issue with personally.

Growing anime braid hair is fine though, since you trip on it.

I think hangman would work better if you replace it with absolutely nothing, as in the vowel is just removed.

**Comment by Shadowmech88** [comment]
>the katana spawning one

Does it not spawn a replica katana? If not, it should be made to.

**Comment by Intigracy** [comment]
Not at all my point.

**Comment by despotate** [comment]
I support closing this (even as the person who suggested removing hanging man's) because:

- It conflicts with my PR (https://github.com/d3athrow/vgstation13/pull/12863) (pls merge, we can't discuss symptoms until the symptom file becomes readable)
- There was a mixed response on my issue
- Removing this many symptoms is too much - I prefer to lead by example - my way of doing this would be to open two PRs every time I add a new symptom, one to add the symptom, one to remove the worst currently existing symptom

**Comment by ihadtoregisterforthis** [comment]
Hangman is one of the few innovative ones. It could instead it remove a single vowel by line.

**Comment by Shadowmech88** [comment]
Or a single vowel per word.

**Comment by ghost** [comment]
Alright, how about a re-approach?

The amount of vowels replaced is dependent on the virus multiplier, and rather than an underscore it just replaces it with a space?

**Comment by Probe1** [comment]
How about we remove the overt anime stuff from the anime virus and just have it change hairstyle/color.  That's neutral.  That's inoffensive.

And what you just said.

**Comment by ghost** [comment]
Alright, the overt anime stuff is only available if the virologist puts some work into it, was meant to be something more round-endy, as the multiplier is default 1 if the virus is randomly generated

**Pull request closed without merging**
