### PR TITLE
Fixes Une decks being unreachable if nested too deep.

### LINKED ISSUE #19698: Cant pickup deck of une cards after putting them in a box
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
d1706cc4db2f3dc555f8721032bdc9cbc3f896fe

# Description
stick em in a box, expect to be able to click-drag them out to pick up the full deck, but actually "You can't reach it from here.", forcing you to pull out all 108 cards individually

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #19698 

NB: Not sure if this is the smartest way around but it does check for something nested as deep as you want.

### CODE REVIEW

**Comment by Exxion** [comment]
No, it isn't
Also the maximum recursion distance is intentional
EDIT: Or rather there is an intentional maximum recursion distance

**Comment by ShiftyRail** [comment]
You need to take into account than a deck being nested at the 2nd level is basically impossible to reach and occupy a slot in your inventory.

**Comment by Exxion** [comment]
Yes, it should work deeper than it does now, but not infinitely so
(Though the max recursion depth is deep enough that it's unlikely anyone ever noticed it)
Still this should use a check in the different direction
`is_holder_of()`

**Comment by ShiftyRail** [comment]
Yeah `is_holder_of` is saner.

**Pull request merged**
