### PR TITLE
Making fabricator delay between items shorter: Revenge of the Scientist

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
This time it SHOULD WORK
What was done:
- Building items has a far shorter cooldown (10x less, from 2 seconds to 0.2 seconds) between items being built
- The cooldown is dictated by a fancy new variable called fabricator_cooldown
 - start_processing_queue now kicks off a loop called build_item_loop() which will keep building items until stopped or it can't do it anymore
 - The added advantage is that it no longer depends on Process() and it kicks off immediately after pressing a button to produce the items
 - Cleaned up every src in the file that was redundant

If you notice anything wrong tell me. It was tested as much as I could test it. Auto-producing items still depends on Process() to kick off
Previous PRs which tried to do the same thing but failed for one reason or another #25308 (hogged the process() resources)  #22640 (broke autolathes)
:cl:
 * tweak: Fabricators now have a shorter cooldown between producing items.
 * tweak: Fabricators now start immediately instead of after a slight random delay.

### CODE REVIEW

**Comment by Kammerjunk** [comment]
have a collab seriously read this through both for implementation and feature

**Comment by boy2mantwicethefam** [comment]
yea that's why I ask people to tell me if there's anything wrong, because so far it worked fine in testing

**Comment by SonixApache** [comment]
removing `src` makes your diffs a lot harder to read

**Comment by boy2mantwicethefam** [comment]
Yea I realized it was a mistake

**Review by DamianX — CHANGES_REQUESTED** [review]
Before: https://streamable.com/1nyd0
After: https://streamable.com/w5fq3
Patch: https://gist.github.com/DamianX/cdc6fe0e30f7a811cfd3b02b797001a6
Related reading: https://github.com/vgstation-coders/vgstation13/pull/25308#issuecomment-562799508

so fucking stupid

**Comment by SonixApache** [comment]
dog bless you damian

**Comment by Kammerjunk** [comment]
I hadn't seen that PR
that makes this one way more stupid
what the fuck Barry

**Comment by boy2mantwicethefam** [comment]
@DamianX Told you fast_process() isn't too useful for what I try to achieve, the current iteration has 0.2 seconds delay between items being produced instead of 1 second that fast_process uses, functionally identical but the added advantage is that the delay between items can be tweaked using a variable.

**Comment by DamianX** [comment]
It's 0.7 seconds, not 1. Regardless, the proper way to do it still to use a subsystem. If you really want to make the delay 0.2 you can make `SSreally_fast_machinery` just copypasting `SSfast_machinery` and changing the `wait`.

**Comment by jknpj** [comment]
Do the thing

**Comment by Exxion** [comment]
???
How on Earth is adding a new subsystem just to handle one single machine less dumb than having the machine handle itself?

**Comment by boy2mantwicethefam** [comment]
@DamianX I want to hesitate from adding a subsystem to presently handle a specific kind of machine, sorry that I couldn't reply earlier. What's the advantage of process() over the current iteration?

**Review by DamianX — APPROVED** [review]
You're right, I'm wrong, sorry.

**Comment by Zth--** [comment]
It's a tradeoff. Damian's fast_machinery solution does the job, it's probably bugless as it uses a known system, it's easy to maintain and it's easier to review. But with his solution you don't have any control over how fast you want it to print stuff (is it really needed?). Trying to address this issue by adding functionality to SS would benefit all other machines that use it

Your solution is harder to maintain over time and fixing its problems doesn't really benefit other machines

**Comment by Exxion** [comment]
You really couldn't feasibly make a subsystem that allows different delays for different machines, and you couldn't eliminate the inconsistencies in timing due to partial ticks
Specific details aside, this general implementation seems proper to me

**Comment by boy2mantwicethefam** [comment]
I mean, I don't know what other machinery to add to it. In case I'll get around to it I'll try to make the "subsystem" thing in a different PR if it ever comes the case for anything other than the fabricator needing to process really fast because undoing the changes means restoring stop_process, refitting process(), removing build_part_loop and restoring where stop_process used to be called so it shouldn't be hard to retrofit for the subsystem

**Comment by Kurfursten** [comment]
Damian approved

**Pull request merged**
