### PR TITLE
[DNM] Adds parallaxes, also new blasting space sprite

### PR DESCRIPTION
**Pull request by ghost**
**NOW IN HOT DEVELOPMENT TO MAKE BETTER, DON'T BE SURPRISED IF THIS DOESN'T COMPILE**

Added parallaxes : 
- Basically, we now have a static background (the stars, which are so far away they functionally don't move relative to our view). It's a xboxhueg NASA image cropped and squashed down to 480x480. Which sounds terrible, until you see the end result
- The background is static using a REVOLUTIONARY new technique, <s>stole</s> borrowed from Paradise hot code. Basically create a pure white screen overlay that draws on the plane under all objects, draw space tiles under that underlay, and then draw our parallax to blend into that white overlay, giving a beautiful unmoving background
- This is a pretty huge change, despite it being 100 % cosmetic. The REALISTIC background sticks very well with the game, the fact it's static helps reinforce that you're a station lost in the middle of space and not literally walking on space
- Okay, maybe a tiny gameplay effect. You can no longer tell if you are moving if you have no in-game objects to use as a reference within view. But unless you're using a jetpack without stabilizer or end up stuck in space due to a bug, it shouldn't be that terrible, right ? Just a bit disorienting
- Added a special end game and Nar'Sie sprite, all areas that don't use warp space switch to it when entering the new universal state. Basically the space behind you slowly strobing in and out
- Warp space (the area the shuttles enter when travelling) has a special sprite taken from Goon

Potential issues : 
- Changing your view range (admin and observers) doesn't scale the parallax properly. In other words, everything beyond the normal 7x7 view range is a white void. I don't know of any way of fixing this, so yeah
- Shuttle corners are looking a bit dorky, but the only way to fix this would be to rework shuttle turfs and update the map, which would be a BIT sucky

Again, I'm aware it might be a bit disorienting, but it's really a huge improvement to the game. Unless we expand this into a semi-dynamic parallax (aka objects moving in the background with different speeds, like a true parallax), it won't get any more IMMERSIVE than this. Kinda like going from 32x32 sprites to 64x64 in scale of art change

Weebum : https://a.pomf.cat/avqvbt.webm (OUTDATED)

Random selfie : 
scrnshot1

Obviously tested

### CODE REVIEW

**Comment by 9600bauds** [comment]
> Changing your view range (admin and observers) doesn't scale the parallax properly. In other words, everything beyond the normal 7x7 view range is a white void. I don't know of any way of fixing this, so yeah

Can you make the background at least 9x9 so it doesn't fuck up for people with the longview mutation?

**Comment by ghost** [comment]
That might be pretty fucky. I think it would be better to actively scale screen elements to fit with new view ranges

How do crit overlays do it anyways ? If they already do it properly, then it can surely be used

**Comment by carshalash** [comment]
Dylan, there was only one parallax. The other lantern entities had their own names. God

**Comment by Boxe** [comment]
this is uglier than the french

**Comment by NigglyWiggly** [comment]
The still image looks neat for a bus or something, but the webm just hurts my eyes and looks really out of place.
I mean maybe if it was a pixelated thing that matched the style it'd be alright, but as it is this just looks strange.

And it's gonna look real bad around corner shuttle tiles and the high-speed shuttle tile things

**Comment by Exxion** [comment]
@dylanstrategie 
Crit overlays don't do it properly
In fact, having longview fucks up pretty much everything except the standard inventory/health HUD

**Comment by ghost** [comment]
@NigglyWiggly It does look a bit odd, but it might just take time to get used to. I worked with it for a bit, and now the old thing looks about as weird

I'd say it's the same thing as using the new Goon walls or trying to use 64x64 sprites. There's a jump in quality, but the rest can look out of place in the meantime. Over time, with better spriting, it will blend it more and more

@Exxion Then that's settled ? I guess a general fix for screen objects should be deployed in that case. Transform should do it, but might be a bit much even for a PR that adds parallaxes

**Comment by NigglyWiggly** [comment]
Do we really WANT everything to blend in with an actual photo of space though?

**Comment by Boxe** [comment]
the only good thing about this PR is the fact that the creator is in Europe

soon™

**Comment by Senaat1** [comment]
I quite like this, actually.

**Comment by ghost** [comment]
Well, why not ? It's space. Space is nebulae, stars and other features. It looks more detailed than usual, but no tricks were used there. It's just more detailed than everything else because we've been using CODERART(TM) on a ton of things and never transitioned to 64x64 sprites like a lot of servers envisioned

**Comment by NigglyWiggly** [comment]
Why would we want to move to 64x64 sprites either, though?
I feel like part of the appeal of spess is the simplisitic look of it. I do like the stationary space, but I wish it actually fit in with everything else in the game, instead of deciding that everything else needs to change to fit in with it

**Comment by ghost** [comment]
Simplistic look is really only because of 32x32 limitations (at least as far as very recently) and because we don't have an art budget in the hundred of thousands of dollars. I always thought of SS13 as a game trying to be realistic and immersive while freely letting silliness get in the way

**Comment by TheEliminator16** [comment]
I like it. I like it a lot.

**Comment by DeityLink** [comment]
> added parallax to space

HOLY SHIT I TRIED THAT A YEAR AGO BUT COULDN'T GET ANYWH--

> check webm
> it's just a static space background

Oh. Nevermind then, this sucks. It's wrong for a lot of reasons but I'll name one: if you're away from anything you have no idea whether you are actually moving or just still. The "good" kind of parallax which is what I tried (in vain) to achieve would be to have multiple "layers" of stars in the background that move at different speed. That would be much more immersing. Also I still prefer the stars we have now to that space background, sorry.

**Comment by Shadowmech88** [comment]
I like how it looks next to the station, but I agree with Deity in that when you're out in space, you couldn't tell even how fast you were going.

Would it be possible to make space still move when you move, but at a slower rate than everything else moves?

**Comment by ghost** [comment]
It would be slightly possible, but a bit fucky

I'm considering another option with Deity right now

**Comment by Intigracy** [comment]
This looks absolutely terrible as-is.

**Comment by gbasood** [comment]
I said this in IRC earlier today, but I think the cost to benefit here is absolutely shit.
Also, you picked a pretty bad spess background for this. It clashes super hard. And it isn't actually parallaxing in that webm
Paradise's at least blends in.

**Comment by ghost** [comment]
I'm working on parallax overlays right now, let me see what I can put out

**Comment by ghost** [comment]
Made background much less bright : 
scrnshot1

Still going to work on actual moving bits

**Comment by ghost** [comment]
We can't have nice things

If you can do better than I have somehow, please, help yourself, the code's here

**Comment by Shadowmech88** [comment]
Is it just not feasible to make space move slower than everything else, from a coding standpoint?

**Comment by ghost** [comment]
You could do the exact thing I did, but make space move. That does however raise a host of problems

**Comment by NigglyWiggly** [comment]
@gbasood  That looks a lot better, and it's pretty much exactly what I was thinking of

**Comment by ghost** [comment]
I prefer dylan's to be honest.

**Comment by DeityLink** [comment]
@gbasood HOW DID PARADISE DO IT? TELL ME

**Comment by gbasood** [comment]
@DeityLink by making the space parallax move like @dylanstrategie described

Please don't make this a thing, it causes headaches for some people with such a low level of parallax detail (one-layer parallax is dumb) Specifically having the background move with no 'anchors' that do not seem to move because they are off in the distance is disorienting.

**Comment by unid15** [comment]
This is really cool. In the webm you can actually feel like you're floating in space

**Comment by DeityLink** [comment]
@gbasood I agree, I was thinking of 3-4 levels of parralax, but I never managed to code it. I can make the sprites for it no problem, I guess I'll look into that code later.

**Comment by PJB3005** [comment]
~~@gbasood you can turn it off.~~

Dylan went retard again and didn't port the turning it off.

**Comment by DeityLink** [comment]
I think I'll give it a shot after all.

**Comment by unid15** [comment]
Heck yeah

**Pull request closed without merging**
