### PR TITLE
fixes typo in shrapnel sprite

### PR DESCRIPTION
**Pull request by SonixApache**
shrapnesmall -> shrapnelsmall
shrapnelarge -> shrapnellarge
who the fuck named these sprites

🆑 
 - bugfix: Neither large nor small shrapnel is invisible anymore

### CODE REVIEW

**Comment by Intigracy** [comment]
Ping me on discord when Travis passes

**Comment by Exxion** [comment]
Hold on
Why are there *three* ls in shrapnelllarge?

**Comment by SonixApache** [comment]
because i put a typo in the description of the PR that fixes typos because my eyes are bad

i tested it and it worked so it's fine

**Comment by Exxion** [comment]
Oh OK carry on

**Pull request merged**
