### PR TITLE
All scientist titles now get science satchels.

### LINKED ISSUE #8316: satchels
scientists spawn with a regular gray satchel, but i saw that there are scientist satchels on metaclub; i don't know if this happens with other jobs, but if there are specific job satchels/backpacks people could spawn with them by default.

satchel

### PR DESCRIPTION
**Pull request by PJB3005**
Also makes scientist lockers have science lab coats instead of regular lab coats.

Fixes #8316

### CODE REVIEW

**Comment by ghost** [comment]
Fucking finally, I hate when assets are wasted like this

:+1:

**Comment by ihadtoregisterforthis** [comment]
satchel gang
Do all satchels from all jobs appear properly now?

**Comment by ghost** [comment]
If they don't, they should

The second to last one looks REALLY weird though, and eye burning

**Comment by PJB3005** [comment]
Yes I think they all get assigned properly.

**Pull request merged**
