### PR TITLE
Carmen miranda's Ghost 4K HD

### PR DESCRIPTION
**Pull request by ShiftyRail**
Lifted from https://archive.org/details/filk_carmen_mirandas_ghost/01+Carmen+Miranda's+Ghost.mp3 instead of a youtube DL which itself comes from some kind of casette recording idk

It's fucking 2021

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
can you add jamie dawsons christian or whatevr its called in hq too

**Comment by ShiftyRail** [comment]
yes

**Comment by Exxion** [comment]
Perhaps I'm doing something wrong but I'm not sure this is the file you meant to upload

**Comment by ShiftyRail** [comment]
I deleted it and added a new one. I reformatted it to OGG in case it's relevant, though the MP3 is like 10 times smaller.

**Comment by Exxion** [comment]
Well, when I listen to it, I do not hear music, but rather a TTS reading the donation banner from the top of archive.org

**Comment by ShiftyRail** [comment]
🤔

**Comment by SECBATON-GRIFFON** [comment]
> Well, when I listen to it, I do not hear music, but rather a TTS reading the donation banner from the top of archive.org

throw it in

**Comment by ShiftyRail** [comment]
@Exxion Got trolled by Archive.org

**Comment by Exxion** [comment]
Oh cool we get both now

**Review by Exxion — APPROVED** [review]

**Comment by wotisjanitor** [comment]
you're keeping both versions in, yeah? You can also find another version of Carmen Miranda on the album "Rebel Yells" which is also on rocketman's archive. It's much more of an impromptu jam session/concert than a recording

**Comment by RedrobotAnnie** [comment]
There's a charm to the tape recording, I hope you keep both.

**Comment by Exxion** [comment]
It's still from a tape, just a better recording of the tape

**Comment by Eneocho** [comment]
> Well, when I listen to it, I do not hear music, but rather a TTS reading the donation banner from the top of archive.org

Add this TTS to the emagged playlist.

**Comment by Eneocho** [comment]
Also, if you changed this one, consider changing the playlist one as well.

**Comment by Viciousaurus** [comment]
Soulless

**Comment by TGFH** [comment]
The bad tape recording is SOVLful.

**Comment by Eneocho** [comment]
I've listened to the bad tape recording one so much that the HD version feels wrong, the voices are pitched differently. I have to slow down the HD version by 8 or so percent for it to feel right again.

**Comment by SonixApache** [comment]
the tape compression actually fits the song really really well, i'd lament losing it entirely
using both (HD for the title screen?) is probably the best option

**Comment by godietxt80** [comment]
as someone who listens to both versions semi-frequently, the casette version is better and fits in with the game more.

**Comment by Exxion** [comment]
It is, again, still recorded from the casette, just with an actual digitizer instead of like a shitty microphone or something
The artifacts you're hearing are from the digitization, not the casette

**Comment by boy2mantwicethefam** [comment]
Soulless

**Comment by SonixApache** [comment]
i like the tape warping effect in the shitty version but the vocals are painful so i'd prefer this

**Comment by wotisjanitor** [comment]
> I've listened to the bad tape recording one so much that the HD version feels wrong, the voices are pitched differently. I have to slow down the HD version by 8 or so percent for it to feel right again.

Actually, that's true. The digitization of that tape is rocketman's worst and first work. All his albums after have been much better.

**Comment by Kromkar** [comment]
Don't change it, just add the new one if you really want. Don't remove our SOVL

**Pull request merged**
