### PR TITLE
Fix spacepod weapons

### LINKED ISSUE #3293: Spacepod weapons give bad scary runtimes
Neither tasers nor lasers work for spacepods. They can be installed properly, but clicking the "Fire Laser System" action gives the following runtime:

proc name: Fire Laser System (/obj/item/device/spacepod_equipment/weaponry/laser/proc/fire_weapon_system)
  source file: equipment.dm,113
runtime error: undefined proc or verb /obj/spacepod/civilian/fire weapons().

### PR DESCRIPTION
**Pull request by Exxion**
Fixes #3293, along with a few various issues with spacepod weapons.
First and most obviously, spacepod weapons... work.
Removing a weapon from a spacepod also now actually removes the fire verb.

The only change not directly related to spacepods is to the dumbfire proc of beam projectiles. For whatever reason, it had an argument for direction, but ignored it in favor of just finding src.dir and using that instead. Now it uses the dir argument if provided, but uses src.dir otherwise. (Spacepod lasers would fire from the right places but exclusively southward without this change due to ridiculous src fuckery. And yes, the spacepod would shoot itself if facing any other direction.)
I'm not sure if that affects anything other than spacepods anyway, but I might as well list it.

### CODE REVIEW

**Comment by Exxion** [comment]
Maybe don't merge just yet. You can and it'll work, but the firing proc code bothers me and I'd like to clean it up a bit first.

**Comment by d3athrow** [comment]
just started debugging this bout an hour ago. If you want to continue your work on it I suggest you get rid of my stupid verb adding system and make a fire weapon system verb on the actual spacepod since with how adding verbs works if you put in the child of the taser you wont get a verb.

**Comment by Exxion** [comment]
I was actually already working on unifying the verbs, but it's just occurred to me that the way I was doing so was stupid and unnecessary. Doing it the better way shouldn't take too long.

**Comment by Exxion** [comment]
Alright. That took way longer than it should have, but now all spacepod weapon types call the same proc to fire. The weapon types themselves now hold the name and description of their specific verb as verb_name and verb_desc, respectively. The verb is still added and removed, but it is done so in a different way by the spacepod itself.
This also means that adding new spacepod weapons is even simpler than before. Granted, only by a tiny amount, but that's something.
It also means that a determined admin could make a new spacepod weapon mid-round, if they really wanted. Just spawn an existing one and edit its name, verb_name, verb_desc, projectile_type, etc. and it should work just fine.

**Comment by Exxion** [comment]
@d3athrow Not to be impatient, but this has been ready for a few days. Tested and everything.
If you don't want to merge it as-is, I'd like to know why so I can fix it.

**Comment by d3athrow** [comment]
I didnt notice you were ready for it to be merged, thought you were still working on it.

**Pull request merged**
