### PR TITLE
Airlocks now make wirecutter sounds when cut, and beep sounds when pulsed

### PR DESCRIPTION
**Pull request by Kharkov72**
Beep
[sound]

:cl:
 * rscadd: Cutting or pulsing an airlocks wires now makes a sound

### CODE REVIEW

**Comment by kilozombie** [comment]
>can hear wires being snipped on the other side of an airlock

Make the sound come from the person cutting/pulsing and have a low radius, if that's at all possible.

Else this just seems nonsensical, and you're already able to tell that a door is being hacked by seeing the icon (which also doesn't really make sense)

**Comment by Kharkov72** [comment]
As is, I think this would be better as SINCE you can see it open it may as well have the sound too
However you did give me an idea to have the panel overlay be on the users tile so people on the other side of the door wouldn't see it 🤔 
I'd mess with that after this PR though, to be a t o m i c (and also because it sounds kinda hard)

Update: Holy fuck no

**Comment by Kurfursten** [comment]
Make it consistent with screwdriver sound distance

machinery/doors/airlock.dm L1141

**Comment by SonixApache** [comment]
now consistent with screwdrivers, :+1: from me

**Pull request merged**
