### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
The server must be stained with the blood of coders who don't compile first, they must be held in a darwinian crucible and those who crash the server are permbannd okay

**Comment by Kammerjunk** [comment]
thank you for your service

**Comment by DamianX** [comment]
Alternatively we could actually fix the warnings
inb4 wyci

**Comment by 9percents** [comment]
it's such a dirty fix

**Comment by ghost** [comment]
oh, oh, OHH
n-nnyaaa~ PJB-kun, fucking fix it instead of disabling the test checks

**Comment by PJB3005** [comment]
See I tried to fix it properly but the tests started failing in a bogus way and I literally had no idea why, and I'm way too busy right now, so...

**Pull request merged**
