### PR TITLE
New job: Space Hobo

### PR DESCRIPTION
**Pull request by ghost**
[general][needsspritework][content]
image
Map will spawn shacks for the job to start in (NOT the same as mining surprises or vaults) based on player count, with none below 10 and capping at 3 with 30, and on roundstart, players who select this job end up in them.
Latejoiners get thrown at them, much like Traders.
:cl:
 * rscadd: Introducing Space Hobos: A job with even less responsibility, access or power than Traders! Non-crew members of any race spawn in a shack in an asteroid free to explore as much as they want, or forge their own destinies with nearby stations...

### CODE REVIEW

**Comment by ghost** [comment]
I appreciate the effort but I think that this role will only have a negative effect on the server culture and roleplay standards. You have basically created assistants, but without the need to cause conflict with other players if they wanna fuck off to space.

Edit: If you add this as a midround thing that ONLY players who have died in the current round can sign up for then I'd support it. As roundstart it's no-go.

**Comment by BomberBro** [comment]
They made an assistant role for assistants.

**Comment by chaklett** [comment]
NO!!

**Comment by Eneocho** [comment]
>They made an assistant role for assistants.

I heard you liked assistants so I put an assistant on your assistant so you can assist while you assist.

**Comment by plosky1** [comment]
Isn't this why they removed that old Vox role that was essentially the same?

**Comment by GreatBigFailure** [comment]
I agree with Ancient. It's a fun concept but should be a mid-round thing to get people back in the game, not a round start one.

**Comment by KillFurries** [comment]
I think this should be more like a low threat minor antag comparable to the soul rambler or a prisoner, not a new job

**Comment by SonixApache** [comment]
add a minimum player amount requirement

**Comment by Apogee-dev** [comment]
doubling up on what ancient said. make it a midround thing,

**Comment by SootyBear42** [comment]
I don't see anything wrong with this really as the people who want to just explore space rather than be a member of the crew would no longer be using a job slot to solely do that.

**Comment by ghost** [comment]
> add a minimum player amount requirement

Doing this soon

**Comment by ghost** [comment]
> I don't see anything wrong with this really as the people who want to just explore space rather than be a member of the crew would no longer be using a job slot to solely do that.

This is a multiplayer game that thrives off of player interaction. Allowing people to pick a role that dodges all player interaction, responsibility, and conflict goes against both the purpose and spirit of the game. And that isn't even considering how anti-conducive fuckoff roles are to our current issue of consistent lowpop.

The reason I'm okay with it as a midround role for dead players (as in, not observers) is because we need more roles to get people back in the round when revival is unlikely. A minimum playercount sort of addresses the issues I have with the role but I'd prefer my former suggestion since that would give the role actual utility beyond being a shitter magnet.

**Comment by SnakeEater14** [comment]
Definitely see this as a sorta low threat mid round antag ghost role thingy

**Comment by TGFH** [comment]
I agree with everything Ancient said here. 
If this was to be redone as a midround type thing, could they be hideous chimeras like ramblers to further distinguish space hobos from regular people in the event that they find their way to the station? I am not sure if dynamic would allow it, but I think it would be best if they weren't actually antagonists.

**Comment by ghost** [comment]
Gonna rework this into a midround ghost thing

**Pull request closed without merging**
