### PR TITLE
More Snaxi Changes

### PR DESCRIPTION
**Pull request by plosky1**
[snowmap]

Did some minor fixes to Snaxi, mostly more new jackets. Also added a backroom to the bar, and changed the ghetto bar a bit.

Biggest change is that all the ice walls are now blue roid walls. The walls are still invulnerable. I cant figure out how to port the roid code for the overlay and nobody wants to help, so until that's done they'll look shitty.

:cl:
 * rscadd: Minor fixes to snow map, bar has a backroom, ghetto bar has been moved closer and changed.

### CODE REVIEW

**Comment by Irradiation** [comment]
rscadd: Did stuff!
rscdel: did other stuff!

**Comment by Kurfursten** [comment]
Look into these too please
#24242
#24211
#24098

**Comment by plosky1** [comment]
Fixed #24211 and #24098 

Left #24242 due to request

**Comment by plosky1** [comment]
Unless more requests come up, that should be it.

**Pull request merged**
