### PR TITLE
Hallucination removing chemicals, made from hallucination causing chemicals

### LINKED ISSUE #8720: We have leftover baystation chemicals(???)
Those being, Methylphenidate, Citalopram and Paroxetine

### LINKED ISSUE #9456: You can get traitor ambrosia/ambrosia c from no-fruits
Whack a no-fruit at the right time and get lucky. If you get an ambrosia leaf, scan it, because it might really be ambrosia c.

Free non-antag spirit breaker fun was had a round. And by that I mean, I consumed spirit breaker, and it kicked in before I could pass around spirit breaker bars to others.

### PR DESCRIPTION
**Pull request by Intigracy**
+- tweak: "Citalopram and Paroxetine are no longer useless fluff bay chemicals. They now remove hallucinations when they're in your system, with Parox being the stronger of the two. Overdosing (15 units) on either of these results in brain damage."
 +- tweak: "Citalopram removes 20 units of hallucination at a time, plus 5 units of mindbreaker, and is made from a unit of mindbreaker, a unit of oxygen, and a unit of inaprovaline (2 units as a result)."
 +- tweak: "Paroxetine removes 90 units of hallucination at a time, plus 10 units of mindbreaker and 5 units of spiritbreaker, and is made from a unit of citalopram and a unit of spiritbreaker (2 units as a result). It has a 10% chance per tick to instead deal 1 clone damage to you instead of removing hallucinations."

also adminordrazine now removes spiritbreaker along with everything else it does

tested

Will update wiki when merged.

closes #9456 since the issue there was how badly spiritbreaker fucks you up.
~~Since it's so easy to get spiritbreaker, it's also as a result that easy to fix it (since the awesome recipe requires spiritbreaker).~~
It's still easy to get spiritbreaker en masse if you're good at using the no-fruit, but otherwise I removed the assburger having spiritbreaker.

closes #8720

### CODE REVIEW

**Comment by 9600bauds** [comment]
~~>Since it's so easy to get spiritbreaker, it's also as a result that easy to fix it~~

~~I really, really, really don't agree with this logic
Spiritbreaker is supposed to be an antag item, the fact that asspie has it is an issue in itself~~

**Comment by 9600bauds** [comment]
Also spiritbreaker has a slower metabolism rate so even if you make the anti-spiritbreaker chem it wouldn't be enough to counteract the same dosage

**Comment by Intigracy** [comment]
It would, because it's removing 5 spiritbreaker units per tick as well as 90 (Spiritbreaker adds 100 hallu units per tick for comparison) hallu units. Its slow metabolism rate doesn't matter when it's being removed outright.

If you mean 5 units of Parox won't remove 5 units worth of Spiritbreaker, you're right, but it'll go a hell of a lot faster than it does currently. Especially if you combine with antitox, synaptizine, and/or peptobismol.

You can't combine these two chems unless you get rid of all the spiritbreaker in their system first, since it'll just keep making parox.

**Comment by 9600bauds** [comment]
I'm still not sold on nerfing a tator-only chemical, especially when it's specific to a job that could be making cyanide or chloral instead AND when everyone knows who's doing it

But I guess this is non-trivial chemistry so I foresee the average wild ride using the ole toolbox anyways

I don't know, it's a decent nerf to a thing that shouldn't be nerfed

**Comment by FudgePucker** [comment]
What about a cure for spiritbreaker that requires spiritbreaker?

You need the traitor chem to cure it, so after you bust the botanist and find his death plant you can treat everyone effected.

**Comment by Probe1** [comment]
Fudgepacker has the right idea.

**Comment by 9600bauds** [comment]
> Paroxetine removes 90 units of hallucination at a time [...] and is made [...] from Spiritbreaker

**Comment by Intigracy** [comment]
lmao actually reading what PR's do

**Comment by FudgePucker** [comment]
Woops

**Comment by Probe1** [comment]
its like 100% tested

**Comment by unid15** [comment]
@FudgePucker you don't need to get spirit breaker to cure it, just pump the patient up with citalopram and it'll react inside the patient, turning all sb into parox and fixing everything

**Comment by Intigracy** [comment]
And then it overdoses them when you add too much.

**Comment by clusterfack** [comment]
Conflicts mostly

**Pull request closed without merging**
