### PR TITLE
Other baked goods can now be dipped like other foods

### PR DESCRIPTION
**Pull request by MushroomMan01**
:cl:
* rscadd: Now all cookies/biscuits/muffins etc. along with breadslices can now be dipped in open containers, just like cookies and donuts

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you make seasonal cookies, bread and all the bread types dippable too? The seasonal cookies feel like an oversight (cause they be cookies), the breads cause bread can soak up liquid, like a donut.

**Comment by MushroomMan01** [comment]
> Can you make seasonal cookies, bread and all the bread types dippable too? The seasonal cookies feel like an oversight (cause they be cookies), the breads cause bread can soak up liquid, like a donut.

Adding breads would require more than just adding a flag to the food items, since you can do a lot with them. Same reason why I do not dare try to add pancakes.

For now, it's just some assorted pastries and such

**Comment by Eneocho** [comment]
The :cl: and rscadd thing should be the last thing on the PR, nothing below it.
And would it really be a complicated thing to add it to bread? It's only a flag that enables the dipping system deity added to the bread. Adding the flag to all the breadtypes would only make those breads dippable, not the stuff you can make with those breads (or the breadslices for that matter, as several of em are not children of their respective bread). 
Also, we got pancakes already, see #30359.

**Comment by Hinaichigo** [comment]
Why not unwarmed donk pockets too?

And also the 'custom foods' from the food press. You can make an alternative form of donk pockets, cookies, etc. there as well. But I guess the structure and composition of those are debatable; does the result of food pressing a pumpkin into a cookie have a porous texture suitable for dipping?

**Comment by MushroomMan01** [comment]
> Can you make seasonal cookies, bread and all the bread types dippable too? The seasonal cookies feel like an oversight (cause they be cookies), the breads cause bread can soak up liquid, like a donut.

Fixed the cookies along with some more foods. Only made bread slices dippable since you wouldn't dunk a whole loaf into liquid.

I am thinking about adding cake slices.

Also cleaned up the PR.

**Comment by Eneocho** [comment]
> since you wouldn't dunk a whole loaf into liquid

You can. It might be a weird thing to do but you can, especially since the breads in-game are based in the stereotypical american bread loaf, which is porous on the outside, thus it should be possible.

**Comment by Hinaichigo** [comment]
Are food press cookies and donk pockets porous or are those just smushed into those shapes without changing the overall consistency?

**Comment by Eneocho** [comment]
Since the food press tells you it's a topological issue if you try to re-press something pressed before, I'd say they are effectively 'real' cookies/donk pockets, since it implies it manipulated the source food into the target food topologically, so they'd behave the same, for the most part.

**Comment by Eneocho** [comment]
You didn't add iron donuts as dippable (they are listed so they don't inherit from donutcode), also the bluespace muffin.

**Pull request merged**
