### PR TITLE
Made blood type scanning not require upgrades on advanced medical scanners.

### PR DESCRIPTION
**Pull request by ghost**
This information can be accessed already, but in an incredibly unintuitive way (surgery console), that few people are aware of. This is a far more intuitive way to access this information.

:cl:
 * tweak: Made Blood type scanning not require upgrades on advanced medical scanners.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by SonixApache** [comment]
You could also just check someone's ID, or pull up their record in the medical computer. Or ask them if they're up.

A more interesting thing to think about is identifying what bloodtype a random container of blood (reagent) is.

**Comment by ghost** [comment]
@SonixApache That's true, but what inspired me to make this PR was a player ahelping where no method would work except the surgery computer- a real life case.  Certainly that's a very good idea though regarding random containers though.

**Comment by DamianX** [comment]
chemmasters can tell you which bloodtype it is

**Comment by Pathid** [comment]
@SonixApache 
Or use the health scanner HUD to check their record. Quickest way usually.

I'll add that you can also draw a little blood into an empty IV bag to check the type. Apparently they have very smart labels built into them.

**Comment by SonixApache** [comment]
@DamianX Huh. The more you know.
wutblood

**Pull request merged**
