### PR TITLE
Big Antimatter Jar

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Adds a large antimatter containment jar to cargo. 

The jar has 10x the fuel capacity of a normal AME jar (10,000 versus 1000) and costs 200 credits. The steep credit number is to make this intended for use with the engineering debit account when building a fuckhueg AME rather than just to make a normal AME even more braindead.
This also adds a jar with 30,000 capacity but it's admin spawn for now. I might add something to science that let's them be made if people use the 10,000 capacity one enough to warrant it. 

>Why

AME boring. Engines boring. Stand there and exchange jars all shift if you want to make a big AME. 10x less boring. 10x the [qol]

:cl:
 * rscadd: An antimatter containment jar with 10x the normal capacity is now available at cargo

### CODE REVIEW

**Comment by BomberBro** [comment]
Wouldn't this just encourage the use of the dullest engine in the history of station engines?

**Comment by GreatBigFailure** [comment]
I don't see why this would encourage people to use the singularity
Jokes aside the AME can be fun to build. It's very boring to use but it can be a fun goofy project. This just helps that project not result in an explosion or deactivated, unfueled AME. Adds more flexibility.

**Comment by DamianX** [comment]
You complain about boring things then introduce a bigger version of a boring thing that you obtain through the most boring way possible

**Comment by GreatBigFailure** [comment]
The method of obtaining it was mostly laziness on my part, but it also means it won't be the default jar for the AME. You'd need to specifically be going out of your way to build a silly AME project to want to buy it. That's less boring than what we have now.

**Comment by DamianX** [comment]
But you start the game with 300-400 credits. What are you talking about?

**Comment by ShiftyRail** [comment]
Could make it obtainable through some meme crafting method rather than being ordered. Like blacksmithing.

**Comment by GreatBigFailure** [comment]
> Could make it obtainable through some meme crafting method rather than being ordered. Like blacksmithing.

The cargo source is mostly out of laziness but also because I see nothing wrong with giving cargo more useful things, it's their whole job after all. Was thinking of giving science a "Antimatter Housing Unit" in engineering research, but for the 30,000 one. Admittedly that might be a bit much.
Way I see it is the 1000 fuel version takes ages to need replacing, this isn't much of a buff to non-huge AME. They will still provide only a decent amount of power until more engines are built or through low-pop rounds. Larger AMEs are unusable because of how quickly fuel drains, you essentially need to just stand beside them all shift. This will let them be used.

**Comment by Blithering** [comment]
I could see new AME sections being a way to make things more exciting, rather than just cores and the bit you stuff jars in you could have doodads that recycle some of the fuel, increase the power per unit of fuel or even bits that provide synergy with other engines like an output that stimulates supermatter better than emitters or uses antimatter reverse entropy bullshit science to heat burn chambers.

**Comment by GreatBigFailure** [comment]
That would definitely be a better addition but it would also be a lot more work to make and require more engineering knowledge from the person making it. This was intended as a quick way to open up a slightly less boring option.

**Comment by Eneocho** [comment]
An idea to stop the "boring" AMEs would be to add an automated AME tank replacement machine that needs some science to build.

You get the machine frames on both sides of the AME Control, put the corresponding circuits, parts, etc. You can place up to 10 normal AME tanks (3 big ones) on the inserter side. Once the fuel tank is empty, the collecting side automatically takes the empty tank. It'd be a way to automate larger AMEs that isn't braindead.

**Comment by Kurfursten** [comment]
I'm not too worried about the concerns about cost, because while others have pointed out, you probably could buy 1-2 of these as a normal engineer if you're lazy... I think that's fine. It's a steep cost, but not disproportionate.

**Pull request merged**
