### PR TITLE
Pigs

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds pigs.
display_large
They're children of box, so they inherit all the pig-like behaviors.

### CODE REVIEW

**Comment by Zennyization** [comment]
What a dodgy looking piggy.

**Comment by Hugh-G-Rection** [comment]
Pig cube boxes please
Bacon! Chops. Pickled feet. 
Lard to be used as ghetto lube.
If on grass will track mud everywhere forever, janitors new worst nightmare
Will bite anyone laying down and eat corpses completely.
Carrot + wired rod to guide them around
SADDLES TO RIDE THEM
CREATINE AND PHAZON TO MAKE TURBO MURDER-PIGS
**LETS GO HOG WILD**

**Comment by ghost** [comment]
If they're inheriting box behaviour, you might want to make them friendly to humans - box are friendly to vox, and I think hostile to everything else.
On the other hand, botanists getting chased by angry pigs sounds like a fun time.

**Comment by Kurfursten** [comment]
They're a retaliate mob so they will attack only things that first attack them, and never attack Vox.

I don't object to having pigs in the code in case someone wants to use them for stuff like vaults or away missions (or holodeck farm?), but making them easily available as Hugh suggests would make boxen basically irrelevant, I think. If station botanists want something to farm, we've got chickens. I know because I wrote both the egg incubator and boxen cloner.

**Comment by SonixApache** [comment]
*why*

**Comment by Shadowmech88** [comment]
I had the sprites already and I figured there's no reason for a box counterpart that can survive in oxygen to *not* exist, even if it's not usually obtainable.

**Review by PJB3005 — APPROVED** [review]

**Comment by mtpowell** [comment]
What the hell, his legs aren't attached

**Comment by Exxion** [comment]
Also the feet on the side sprites are all manner of fucked up

**Comment by Kurfursten** [comment]
@mtpowell What you're seeing there are tusks

**Comment by Intigracy** [comment]
Do we have bacon?

**Comment by Kurfursten** [comment]
Yes, it's just one box meat with nothing added. By extension, pig meat will also do the trick.

There a few other recipes which call for pork, you can see them on the wiki.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
