### PR TITLE
Hello it's us! Your old friends "Spacevine infestation" and "Biomass infestation", we've missed you, why didn't you call?

### PR DESCRIPTION
**Pull request by DeityLink**
fixed

image

also space vines and biomass are each their own event now.

:cl:
* bugfix: Fixed space vine and biomass random infestation being borked and never actually firing for A WHOLE FUCKING YEAR. I mean, did anyone actually notice? Like come on...
* rscadd: Space Vines spawned during infestations (or by admins) now have a random strength factor that substantially increases their chance to possess dangerous traits, such as carnivorous, hematophage, ligneous, etc...
* rscadd: Space Vines appear now blood red if they have the hematophage trait, and grey if they have the ligneous trait. They'll appear dark red if they have both.

### CODE REVIEW

**Comment by DrSnips** [comment]
No body wants to see them that's why no one has cared for that year. Take a hint.

**Comment by DrSnips** [comment]
Mean post aside. Thank you for making some kind of indication of how bad they might be visually.
They only bug I can think of is biomass is able to phase through glass somehow and sometimes vines too.

**Comment by DeityLink** [comment]
I've seen biomass do it but not vines so far. Biomass has a lower chance to appear though now. (also Biomass could use its own gimmick to further differentiate them from vines, it's pretty crazy that despite being originally a recolor they're completely different objects, so fixing bugs for one won't fix them for the other).

**Comment by GreatBigFailure** [comment]
If people are annoyed by it we can always tone it down later. I'm all for more events. It's always meteors, rad storm, or power outage in that order. More variety and more potentially impactful but not round ending events.

**Comment by dunsel-hordon** [comment]
The station cancer rises again.

**Comment by tuypo1** [comment]
Yeah more events back would be great

**Comment by cloutcode** [comment]
when you spend so much time trying to click on the sprite you only cut one vine by the time two have grown

**Comment by DeityLink** [comment]
That's why you use plant-b-gone, sickle, goats, and other safer ways of dealing with it

**Pull request merged**
