### PR TITLE
Readds controversy but with a different bluespace sprite

### PR DESCRIPTION
**Pull request by ghost**
bluespace

Tell me what you think. If this doesn't look good, there's also the baystation sprite.
Transitions from tile to tile seamlessly, no ugly edges. Created with Tilemancer.

EDIT: alternative from Baystation
wew

I don't have any other sprites, if there was something better I'd put it here.
If spriters could come up with something better than the current blocky crystal stuff it would be really appreciated, because it honestly just looks plain bad.

EDIT 3:
bluespace_moving
as suggested by Shadowmech

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Show a WebM of an actual cascade using this sprite.

**Comment by Probe1** [comment]
seems ok but its not something i care deeply about

**Comment by ghost** [comment]
@Shadowmech88

**Comment by aratherangryduck** [comment]
Gonna be honest, that makes me even dislike it more, sorry mate.

**Comment by ghost** [comment]
It's giving it too much structure, like rather than it being a dimension overtaking our own, it's just a big mass of something.

**Comment by ghost** [comment]
alternative (from bay)

**Comment by Probe1** [comment]
pick a PR for an issue and stick to it.

**Comment by Probe1** [comment]
AHHH I THOUGHT THIS WAS A NEW PR HOW COULD I HAVE MADE THIS MISTAKE

**Comment by aratherangryduck** [comment]
It looks too organic, almost like a blob mass, not like a incoming well structured mass of death and destruction, I liked the crystals because it always made sense to me for a Crystal delamination to spawn a expanding crystaline mass of destruction.

**Comment by ghost** [comment]
https://my.mixtape.moe/nqnajs.mp3

**Comment by SonixApache** [comment]
Bay one looks more like phazon somehow.

**Comment by ghost** [comment]
Also, I can always make minor changes in photoshop, slight color modification, brightness change, etc.

**Comment by ghost** [comment]
Here's my two cents - It needs some variety.

Right now all we've had is the same repeating texture.

Have a standard background, then a few sprites that have mutations or variations on this, like a glass-breaking effect phasing in and out, or others.

**Comment by ghost** [comment]
@Skullyton Can be a bit difficult to do that while still maintaining seamless transitioning as there should be for something this large scale.
If there's any spriters that know how to do this stuff then maybe they could help out, I don't know how to go about making something like this.

**Comment by Ephx1** [comment]
I dunno, I kinda like that first one, a repeating nothingness in an odd structure is creepy.
It's also just fun to stare at.

**Comment by Aurx** [comment]
Server poll or gtfo.

**Comment by Probe1** [comment]
#whenbikeshedsgotoofar

**Comment by Shadowmech88** [comment]
bike_shed
Let's use this for the bluespace sprite.

**Comment by ghost** [comment]
@Shadowmech88 terrible color tbh

**Comment by ghost** [comment]
But okay, I'll give it the benefit of the doubt.

**Comment by ghost** [comment]
This is turning into a meme PR and since nobody thinks either of these sprites are good alternatives I'm just gonna close this

**Pull request closed without merging**
