### PR TITLE
Shorten Frankenline and move kitchen/botany/bar

### PR DESCRIPTION
**Pull request by adacovsk**
- Line shortened about 25 tiles, removed zoo
- Kitchen, botany, and bar moved closer to center of map
- Rearranged cargo
- Moved teleporter to arrivals, and beacon at escape

:cl:
 * rscadd: Shortened line, moved kitchen, botany, bar, and teleporter

### CODE REVIEW

**Comment by Kurfursten** [comment]
Not sure I like this. I actually thought it was genius to put them at the end because it pulls traffic up and down the station so people see each other in the halls more.

I guess we should get more general opinions though since I've observed a hell of a lot more than I've played on it.

**Comment by adacovsk** [comment]
> Not sure I like this. I actually thought it was genius to put them at the end because it pulls traffic up and down the station so people see each other in the halls more.
> 
> I guess we should get more general opinions though since I've observed a hell of a lot more than I've played on it.

It's been said throughout its existence that the bar needed to be moved, and I kind of agree with it. As an idea it seems great to have the kitchen and on the end, but I haven't really seen it work much in action, the bar is rarely used. Plus, I didn't move it too far and it helps that cargo is on the end to shorten the length because of the shuttles.

**Comment by wotisjanitor** [comment]
> Not sure I like this. I actually thought it was genius to put them at the end because it pulls traffic up and down the station so people see each other in the halls more.

This is never the case. Nobody goes to the bar

**Comment by wotisjanitor** [comment]
This is a good change, because the first two rounds i played of Line, I was killed right above dorms and nobody saw my body after waiting an hour both times.

**Comment by Kurfursten** [comment]
Had an idea, you know how Snaxi has a permanent teleporter from the arrivals roid to escape on south station?

What if Line had a permanent teleporter between arrivals and escape. So that it's more of a loop than just a line with dead ends.

**Comment by adacovsk** [comment]
> Had an idea, you know how Snaxi has a permanent teleporter from the arrivals roid to escape on south station?
> 
> What if Line had a permanent teleporter between arrivals and escape. So that it's more of a loop than just a line with dead ends.

There's already two teleporters, a transit tube, and disposal tubes (arrivals to cargo delivery and back) that take you across nearly the whole station. So to facilitate what you recommended, I put the teleporter at arrivals, and a bluespace beacon at escape

**Comment by wotisjanitor** [comment]
don't think i've witnessed someone use the tube either

**Pull request merged**
