### PR TITLE
Revert "Pomf why did you merge that already."

### LINKED ISSUE #4883: (WEB REPORT BY: kirtasheks REMOTE: 198.245.63.50:7777) pitch black
>4e6d381df0ee0f356ce39a870fb7f679575d8cd0 

>General description of the issue
the new lighting system is bugging out, sometimes there are pich blaack spaces that cant be lit, this spaces become black(only see the floor) when wearing a meson scanner.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by clusterfack**
Reverts d3athrow/vgstation13#4875
Fix #4883

### CODE REVIEW

**Comment by Probe1** [comment]
i'm with clusterfack.  we gathered some good data but it isn't ready and it's also probably why the server is suddenly goon levels of laggy.

**Comment by Kurfursten** [comment]
I'm indifferent to the merge/revert effort but I think that guy (who had never submitted a bug report before) might have just not noticed the lights were smashed or something.

However the problem he describes is actually real even if his case wasn't. I've seen some permanently dark space tiles.

**Comment by PJB3005** [comment]
I think this might be caused because, with the optimizations, `apply_lum()` uses the turf ref instead of a cycle through contents, which is more efficient, but can probably fuck up if `changeTurf()` isn't used properly, causing the lighting overlay reference to be nulled.

Also, if anything's to be reverted it's #4880

**Comment by clusterfack** [comment]
Well if you can fix it PJB I would be happy to merge that instead

**Comment by Manaony** [comment]
Kurfust: I was there and I can assure you the light were fine when http://i.imgur.com/FbORC71.jpg was taken

**Comment by clusterfack** [comment]
I think I've spotted the issue in #4880

**Comment by clusterfack** [comment]
@Probe1

Also the lag wasn't REALLY lights, it was a combination of a bomb, ed-209s failing to path thanks to the bomb and resorting to astar (four of them) and admins spawning spiders in centcomm which bred up to like 200-300

**Comment by Kurfursten** [comment]
@Manaony Trippy, but thanks for following up on that

**Comment by Probe1** [comment]
I don't know what is what.  I know how it is though.  It's laggier after merge than it was before.  

Get it done boys.

**Pull request closed without merging**
