### PR TITLE
Adds more mining surprises

### PR DESCRIPTION
**Pull request by beesil**
Adds four new mining surprises to the asteroid: a crashed escape pod, a crashed trader shuttle, an abandoned digsite, and a geode. Added to the start of the file so this hopefully doesn't conflict with #29808. 

Also touches up the pre-existing abandoned forge surprise and makes it able to spawn.

:cl:
 * rscadd: Adds some new surprises to the asteroid. Become a shaft miner today!

### CODE REVIEW

**Comment by beesil** [comment]
### Pictures:
screencap2
screencap3
screencap4
screencap1
forge

**Comment by Eneocho** [comment]
Extra mining content is always welcome. I'd add some of the rarer minerals to the geode (like mythril, telecrystals or bananium).

**Comment by Jackreturnswithaveangenace** [comment]
POD BABY

**Comment by Jackreturnswithaveangenace** [comment]
Also the geode is really really cool as an idea in execution, love it.

**Comment by jwhitak** [comment]
I am a simple miner man. More cool roid loot means up vote. Give me more stuff to drag to the station and spread around.

**Comment by Kurfursten** [comment]
I can't remember, is there a way to turn all those TC in there into refined TC for an uplink?

Also make sure those underground roid tiles mine into the correct type.

**Comment by beesil** [comment]
> Extra mining content is always welcome. I'd add some of the rarer minerals to the geode (like mythril, telecrystals or bananium).

I'm hesitant to put bananium in for vaultcreep reasons, the rock surrounding the geode is high chance so there is reward to it (other than fancy crystals).


> I can't remember, is there a way to turn all those TC in there into refined TC for an uplink?
> Also make sure those underground roid tiles mine into the correct type.

Good catch! I'm not able to work on this until later tonight at which point I will check these & add more of the suggestions from the thread.

**Comment by GreatBigFailure** [comment]
> I can't remember, is there a way to turn all those TC in there into refined TC for an uplink?

I'm 90% sure unrefined TC refines into natural bluespace crystals for some reason.

**Comment by Eneocho** [comment]
> 
> 
> > I can't remember, is there a way to turn all those TC in there into refined TC for an uplink?
> 
> I'm 90% sure unrefined TC refines into natural bluespace crystals for some reason.

They do. Which makes them useful as a subspace tunneler tool but not much else.

**Comment by ghost** [comment]
why is the forge listed in the mining vault files but unused? you think you could add that back in too?

**Comment by mrflarg** [comment]
add a trader ID to the crashed ship so we can do away with vox traders

**Comment by beesil** [comment]
Converting this to a draft since I won't be able to work on it until tuesday.

> add a trader ID to the crashed ship so we can do away with vox traders

No

> why is the forge listed in the mining vault files but unused? you think you could add that back in too?

Yes! I can add this.

**Comment by beesil** [comment]
Touched up the forge, changed its filename to match the others & made it able to spawn. Changed the walls of the geode to make cave tiles rather than permafrost ones. Anchored the doors/machinery in the tradershuttle. I specifically used the vox corpses with no IDs because I don't want to enable miners raiding the tradepost.

**Pull request merged**
