### PR TITLE
Wet tiles stun you for 6 seconds instead of 10

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
As much as soap, and makes people wish death and eternal damnation to the janitor less often
:cl:
 * tweak: Slipping on wet floor stuns you for slightly more than half the time it used to.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
Honestly, the lube and water stuns should be defines considering how inconsistent the stun times are for them

**Comment by ShiftyRail** [comment]
That's barely enough time to walk up to someone and cuff them, and water is the first line of defence of 75% of the crew.

**Comment by boy2mantwicethefam** [comment]
The code is a confusing mess anyway, shout-out to visual code studio for making it all easy to navigate

**Comment by boy2mantwicethefam** [comment]
Shifty you say it as if cuffing is a necessity, if what concerns you is that people have less ways to defend themselves consider that 6 seconds are enough time to retaliate or run away and that whoever is chasing will have to slow themselves down to not slip again

**Comment by Exxion** [comment]
I don't really think 75% of the crew carries water and cuffs on them at all times

**Comment by ShiftyRail** [comment]
If an antag is confirmed and you have no other way to defend yourself, you might as well
Alternatively, if you want to de-escalate a situation
Or if you want to prank someone

My position is that it's not really needed to nerf water slips. I can see a point for lube (unescapable, and much more dangerous) or for other ranged combat stuns (even though this only make de-escalating the violence harder), but for water, I don't see a good reason.

**Comment by ghost** [comment]
make macros for stun times you fool

**Comment by Diavill** [comment]
@Exxion cuffs are trivial, during a slip you can simply make cable cuffs

**Comment by boy2mantwicethefam** [comment]
Exxion has a point, the average person doesn't just carry cable cuffs with them even if such a thing would be trivial

**Comment by Blithering** [comment]
Considering how cuffing someone with even a plate of spaghetti will make them completely unable to prevent you dragging them out to space and throwing you out the airlock, or any other kill method so long as you keep moving to interrupt the resist, maybe "long enough to get cuffs on" shouldn't be the default to balance around.

**Comment by Kurfursten** [comment]
Not enough public support at this time. Get a server poll or pomf or try again later.

**Pull request closed without merging**
