### PR TITLE
New vox suits for janitor, botanist and cargo. Fixes a small oversight.

### PR DESCRIPTION
**Pull request by Gringonius**
Taking some grey away.
voxbotanists2voxcargosvoxjanitors

I also commented out the lines that had vox mime and clowns spawn with the nitrogen tank on their hand, it would always fail to open the tank valve at round start and both jobs always spawn wearing an assistant suit with an empty suit storage slot anyway.

### CODE REVIEW

**Comment by kol1th** [comment]
a t o m i c

**Comment by Kurfursten** [comment]
Perhaps the most baffling assistant Vox suit is the mechanic. You might just add him to the Engineering suit on the switch.

**Comment by Gringonius** [comment]
Mechanic is an oddball job that belongs to both engineering and science. I'm not sure if either existing suit would be a good fit, or if they should get the free welding protection from an engineering suit.

**Comment by Exxion** [comment]
Mechanics spawn with welding goggles anyway

**Pull request merged**
