### PR TITLE
revert brig medic

### PR DESCRIPTION
**Pull request by toomykins**
## Why it's good
please contact Dilt for any information regarding this.

## How it was tested
i looked at the job menu.

:cl:
 * rscdel: nanotrasen has decided to destroy all brig medics.

### CODE REVIEW

**Comment by bathosbathtime** [comment]
I support this pull request.

**Comment by west3436** [comment]
Content removal is always lame and I really never see valid hunting brig medics. Why not approach this differently; coupled with your other PR you could instead give brig medics brig hallway and brigbay access but not medbay access to make this job feel more unique.

**Comment by bathosbathtime** [comment]
For flavor I humbly ask that the change log has "destroyed" switched out with "lay off."

**Comment by KingofHONK** [comment]
now add brig scientist.

**Comment by Kromkar** [comment]
Terrible pr

**Comment by SonixApache** [comment]
yes, but why?

**Comment by anonymoose-contributor** [comment]
> Content removal is always lame and I really never see valid hunting brig medics. Why not approach this differently; coupled with your other PR you could instead give brig medics brig hallway and brigbay access but not medbay access to make this job feel more unique.

Shut the fuck up.

**Comment by toomykins** [comment]
reopened because west3436 is alive

**Comment by toomykins** [comment]
reclosing
the west has fallen

**Comment by Eneocho** [comment]
what if I reopen it

**Comment by toomykins** [comment]
> what if I reopen it

do it
you wont

**Pull request closed without merging**
