### PR TITLE
Requested pulse demon tweaks

### LINKED ISSUE #31606: Pulse Demon issues
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
1. Your max charge doesn't increase if you are in APCs, only in SMES.
2. You cannot actually interact with any machinery within the area, most likely because the Pulse Demon is not considered a proper AI.
3. Glow is still visible while under a floor. Intentional?

### LINKED ISSUE #31678: Pulse Demon impressions
After playing Pulse Demon a whole round here is a list of things:
- Self-Sustaining Charge is incredibly powerful, it allows the pulse demon to move around with the only penalty being taking damage as if you aren't on a power net, and makes it nearly impossible to lock down a pulse demon within a certain area of the powernet.
- Engineers can shit on you from afar by disabling power output on the Engineering SMES for a few minutes, which forces you into areas with their own SMES to leech off, because sucking power out of machinery doesn't provide you with any health, only being in a powernet does. Additionally you can avoid losing health by just jumping into an APC and never coming out, which somehow doesn't count as a no-power powernet even if the APC is empty, countering the engineer strategy and causing them to cripple their own station with no power.
- Max charge is not a good system because it forces the pulse demon to suck as much power out of the network as it is being outputted, which means that not only are regular APCs useless (they have low-capacity batteries so they never raise the limit to anything above a few thousand W, which isn't enough to buy any upgrade), but it also forces you to find the nearest SMES to suck off, except that how much power you get out of one depends on its power output, which you can't manipulate if you aren't in an APC in the same room.
- Pulse demons seriously need a way to toggle whether you consume the power in a power system you entered or not, otherwise with high enough power-sucking rate you can't actually make use of any of the machinery within a room because you instantly drained the APC.
- You can't get out of an APC with no wires attached to it, even if you have Self-Sustaining Charge active.
- Upgrades have no descriptions or any indication of what they do outside of the wiki. Not even chat messages.

### LINKED ISSUE #31684: Pulse Demon dies to Hornets.
#### Description of issues
~~While being a Pulse Demon, I lost and regained the ability to see wires seemingly at semi-random. I seemed to lose wire sight after entering an APC, then somehow got back later, then lost the ability to see them again. Power wasn't being supplied to the net (I think), so that may be related.~~
I also noticed that going through wires by hornets caused a 'Hornets stung the pulse demon', as well as getting the red edge around my screen, even though my health was stated to be 100%. I then entered the room FULL of hornets, and died instantly, unsurprisingly.

#### Difference between expected and actual behavior
~~Being able to always see wires so I can pathfind properly, and not being able to.~~
Being immune to hornets, as "Don't let your charge run out! If the powernet blacks out you'll start losing health and eventually die off! You are immune to all forms of damage and obstacles in the way of cables, but are also extremely weak to EMPs, so avoid those at all costs." Then I died to hornets. 

#### Steps to reproduce
~~Try going in and out of APCs, and seeing if you lose wire sight?~~
Go into room with hornets and get destroyed.

#### Length of time in which bug has been known to occur
First time being pulse demon, so I don't know

#### Server revision
Game: 348f29631d6ca0f258fdd67a9b4142589cfcc449 
Patches: d2d8284cefe331992a20db0f4fedb3e1b63c7713

### PR DESCRIPTION
**Pull request by ghost**
Closes #31606.
Closes #31678.
Closes #31684.

:cl:
 * rscadd: Pulse demons now have a spell allowing them to toggle power draining.
 * tweak: The maximum pulse demon absorbed charge in an APC has been multiplied by ten, with a max of 400kW from the best normally available cells, and 30kW by default. (up from 3kW)
 * tweak: The purchase cost of the following pulse demon spells has been changed: Electromagnetic pulse: 50kW to 150kW, Electromagnetic tamper: 100kW to 200kW, Overload machinery: 200kW to 300kW, Self-sustaining charge: 100kW to 500kW.
 * tweak: The upgrade cost of the following pulse demon spells has been changed: Electromagnetic pulse: 20kW to 50kW, Self-sustaining charge: 20kW to 200kW.
 * tweak: The upgrade cost of each pulse demon spell increases with each purchase of one.
 * tweak: Pulse demons absorb charge 10 times faster in batteries, but not APCs.
 * tweak: Pulse demons can now be EMPed inside machinery that gets EMPed.
 * bugfix: Pulse demons can now leave APCs with self sustaining charge toggled on.
 * bugfix: The maximum pulse demon charge absorb from an APC or battery is now updated on each drain, instead of just when you move inside.
 * bugfix: Pulse demons will now properly drain their health on an empty powernet if inside a power source.
 * bugfix: Pulse demons no longer randomly lose cable view.
 * bugfix: Pulse demons are no longer tangible to melee weapons.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Is it possible to make the Pulse Demon passively suck power out of an APC while in a room akin to a machinery if there's no power in the powernet? It would help against the whole "engies cut the SMES wires, GG" thing

**Comment by Eneocho** [comment]
Could you buff the power drain speed or its upgrades a bit? The few rounds I've gotten Pulse Demon (and the times I've observed pulse demons as well) I've had to camp the SMES units for a good while to get any decent amount of power. Raising the skills cost would only mean more camping and having to wait for 5 minutes to buy a good skill is kinda boring.

**Comment by ghost** [comment]
> Could you buff the power drain speed or its upgrades a bit? The few rounds I've gotten Pulse Demon (and the times I've observed pulse demons as well) I've had to camp the SMES units for a good while to get any decent amount of power. Raising the skills cost would only mean more camping and having to wait for 5 minutes to buy a good skill is kinda boring.

Multiplied it by 10, but only for SMEs, not APCs

**Comment by Eneocho** [comment]
> > Could you buff the power drain speed or its upgrades a bit? The few rounds I've gotten Pulse Demon (and the times I've observed pulse demons as well) I've had to camp the SMES units for a good while to get any decent amount of power. Raising the skills cost would only mean more camping and having to wait for 5 minutes to buy a good skill is kinda boring.
> 
> Multiplied it by 10, but only for SMEs, not APCs

Guess that works, thanks.

**Comment by Hinaichigo** [comment]
One thing about having to be inside the APC to manipulate machinery is that oftentimes the machinery in question is out of visual/clickable range. Examples on box include medbay (hard to screw with cryo settings) and the huge atmos room. I wonder if there could be a way around that. Maybe, for example, if you've hacked the APC in a given room, you can manipulate any of the machinery in that room so long as you're in that room yourself, or something.

**Comment by Eneocho** [comment]
A good example of that is also the main engineering room in boxstation. The APC is close to the CE's office, but both the PA and SMES units are outside of viewrange, so you can't mess with them.

**Comment by ghost** [comment]
> One thing about having to be inside the APC to manipulate machinery is that oftentimes the machinery in question is out of visual/clickable range. Examples on box include medbay (hard to screw with cryo settings) and the huge atmos room. I wonder if there could be a way around that. Maybe, for example, if you've hacked the APC in a given room, you can manipulate any of the machinery in that room so long as you're in that room yourself, or something.

Yeah, you can click on cameras if in an APC to jump in them, and the APC again to return back. This has been a thing since I added the antags.

**Pull request merged**
