### PR TITLE
various way improvements

### LINKED ISSUE #32190: Exactly half of the solars at WayStation's Trader outpost aren't wired at roundstart
#### Description of issue
At the beginning of the round on WayStation, only have the solar panels have wire knots under them, meaning you need to crowbar up their tiles and add cabling.
[https://cdn.discordapp.com/attachments/532031427563356160/951810650747863150/Solars.png](url)
[way]

#### Difference between expected and actual behavior
I figured that, once I'd connected all the visible wires on the catwalks, the solars would be fine; I did not expect to have to crowbar up fifteen tiles and wire the floors under them.

#### Server revision
Game: 9cb902c4188a36706eb2a53364e083243ec4298a 
Patches: 609a806a066b5859e732b12938343551efcc77f7 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

### LINKED ISSUE #32324: Waystation - no Telecomms Access for Mechanics
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
you need to hack through FIVE doors to get to telecomms on this map holy shit

### LINKED ISSUE #33467: WAY: Genetics Cloner console blocks the windows
The cloner should be against the north wall, so you/horrible simple mobs can smash through the windows to escape.

### LINKED ISSUE #33766: Waystation has no kitchen light switch
Missing a way for ghost to haunt the chef easier

### LINKED ISSUE #34319: waystation disposals has no pumps/scrubbers
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
63c0c8795ae50de1aa71e32154e477709c819593

There's an air alarm, though!

### PR DESCRIPTION
**Pull request by nervere**
fixes #33766 
fixes #33467 
fixes #32190
fixes #34319
fixes #32324

not fixed because its gonna be annoying to do: #32913

## What this does
-fixes trader outpost solars
-adds a new fire extinguisher in the central hallway circuit
-add light switch to kitchen
-changes orientation of genetics to be more open, more or less rotated it (see image)
image

## Changelog

:cl:
 * tweak: WAY: Added lightswitch to kitchen.
 * tweak: WAY: Re-oriented genetics to make it easier to break out of if necessary.
 * tweak: WAY: Added new fire extinguisher to central hallway loop.
 * tweak: WAY: Fixed half of trader outpost's solar panels not having wire knots under them.
 * tweak: WAY: Fixed disposals not having a vent/scrubber.
 * tweak: WAY: Mechanics now have access to telecomms.

### CODE REVIEW

**Comment by SonixApache** [comment]
#34319 ?

**Comment by KingofHONK** [comment]
dont forget to add an updated map render!

**Comment by nervere** [comment]
> #34319 ?

I missed a few of these including this one because they weren't labeled. I'll fix your issue in a bit.

> dont forget to add an updated map render!

Unfortunately these have to be done in a manual way separate from what can be done on GitHub.

**Comment by nervere** [comment]
Not fixing the remaining two issues with Way (TEG setup + secbot configuration), PR is ready for merge.

**Pull request merged**
