### PR TITLE
Fixes xeno eggs not affected by explosions

### LINKED ISSUE #15767: Xenomorph Eggs are immune to explosions.
#### Description of issue

Xenomorph eggs are immune to explosions from some testing done with bombs on the asteroid on the live server, placed a maxcap a few tiles from an egg, eggs still remained after the explosion.

#### Difference between expected and actual behavior
Expected the egg to not exist anymore, but it was still intact.

#### Steps to reproduce 
Set off a large explosion equivalent to a maxcap near a xenomorph egg.

#### Length of time in which bug has been known to occur
Not sure how long it's been a thing, don't think bombing xeno nests or eggs is common.

#### Server revision
2fd16dbca189d9a299b79f6c04e539d9d9170110

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by DamianX**
Fixes #15767
:cl:
 * rscadd: Xenomorph eggs will now be damaged by explosions.

### CODE REVIEW

**Comment by PJB3005** [comment]
This isn't really a fix, is it? It's more adding a feature.

**Comment by DamianX** [comment]
Sure, in my mind it was fixing an oversight, but I see where you're coming from. Changed.

**Comment by N3X15** [comment]
[Balance] added because this affects combat with xenos.

**Review by N3X15 — APPROVED** [review]
Code looks good.

**Pull request merged**
