### PR TITLE
A crateful of dresses

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
Adds a new crate to the hospitality section for the special and unique
snowflake in you, as well as two random lipsticks.

### CODE REVIEW

**Comment by Arthurdentist** [comment]
Waifus and Waifu enablers should sod off

**Comment by FudgePucker** [comment]
I just want to be a pretty grill ;_;

**Comment by Zth--** [comment]
:-1: Please no. Remove this fucking meme

**Comment by FudgePucker** [comment]
Why not just include some suits and rename it 'outfit' crate to avoid the 'hur dur waifufags hur dur'

**Comment by ShiggyPiggy** [comment]
There's already a formalwear crate that has suits, and this is its female counterpart.

**Comment by FudgePucker** [comment]
:+1:
Forgot about that crate.
Merge when?

**Comment by Probe1** [comment]
Seems fine to me.

**Comment by ShiggyPiggy** [comment]
Aww, I didn't notice it.

**Comment by Probe1** [comment]
:+1:

**Pull request merged**
