### PR TITLE
Buffs regeneration superpower by removing hunger penalty and giving more blood by default

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Healing doesn't happen much anyway unless wounds are treated
I should change how it works at some point in the future, making it regenerate limbs and stuff and with drawbacks or something
On the plus side the chef no longer goes bankrupt from not being able to provide the crew with enough food
:cl:
 * tweak: Regeneration superpower no longer makes you hungry faster, and now it gives a bit more blood by default when you don't have enough. It also no longer consumes more iron and nutriment, meaning you get more bang for your buck. You also start regenerating at a higher threshold (50 damage).

### CODE REVIEW

**Comment by SonixApache** [comment]
👍  on blood regen
👎  on not needing more food to power yourself

**Comment by brndd** [comment]
Would it be complicated to make it so that it's always active, but only consumes extra nutrient when you actually heal damage?

**Comment by AI-Is-Rogue** [comment]
What about raising the cutoff for the auto-healing to be above 15 damage if you have regen? This way you'd be able to take more than a toolbox without losing your automatic healing.

**Comment by kilozombie** [comment]
What kind of chef struggles to not make enough food

**Comment by boy2mantwicethefam** [comment]
Possible to do it only when the need arises but it will be a bit iffy, pretty sure it depends on metabolism and stuff
I can raise the cutoff to about 50 health

**Pull request merged**
