### PR TITLE
Fixes Bombermen Not Being Able to Breathe in Space

### LINKED ISSUE #9922: Bomberman suits should come with oxygen tanks / allow oxygen tanks in suit storage / bombermen shouldn't need air
For obvious raisins

### PR DESCRIPTION
**Pull request by Shadowmech88**
The bomberman helmet now confers the no-breathe mutation when equipped.
Fixes #9922.

### CODE REVIEW

**Review by DamianX — COMMENTED** [review]
Should probably remove the mutation when it's unequipped?

**Comment by Shadowmech88** [comment]
Is that necessary? Bombermen don't ever need to wear anything else.

**Comment by DamianX** [comment]
You're assuming the helmet won't ever be spawned outside bomberman arenas

**Comment by DamianX** [comment]
Also you could just keep equipping it to fill your mutation list with M_NO_BREATHE which is probably bad

**Comment by Shadowmech88** [comment]
Bear in mind that if someone does get ahold of the helmet and happens to already have no-breathe, putting the helmet on and taking it off will break that. I suppose that's better than it just being a free no-breathe ticket to be passed around to everyone, though.

**Comment by DamianX** [comment]
Would it really? The mutation is added to the mutation list regardless of whether it's already present and `Remove` will only remove one of the mutations in that case.

**Comment by Shadowmech88** [comment]
Oh, do active mutations get re-added every `Life()` tick?
It'll be fine, in that case.

**Comment by Shadowmech88** [comment]
You're right, I didn't think about the fact that it'd add an additional instance of the mutation on equip.

**Comment by MadmanMartian** [comment]
why would they need to be able to breathe in space?

**Comment by ShiftyRail** [comment]
Because bomberman arenas are spawned in open space and the walls tend to be destroyed.

**Comment by Shadowmech88** [comment]
Also, during bomberman rounds I imagine the station gets chunks blown out of it.

**Pull request merged**
