### PR TITLE
Skree

### PR DESCRIPTION
**Pull request by Kevak**
Vox are now capable of skreeing. Their screams follow the same mechanics as normal screams. Additionally, screamcode in general has had its level of Snowflake reduced from 7 to 3.

[Sound]
:cl:
 * rscadd: Vox across the sector have recently partaken in voice training. They now skree like proper vox! Humans everywhere cover their ears in horror.

### CODE REVIEW

**Comment by Exxion** [comment]
I... don't think you pushed this properly

**Comment by Irradiation** [comment]
Post the sound file because the diff-bot is dead and your method of merging can't show the changed files easily.

**Comment by Kevak** [comment]
I probably botched the puush

**Comment by Kevak** [comment]
Lemme just. Close and reopen this.

**Comment by Exxion** [comment]
The diff bots are fine, but don't cover sound

**Pull request closed without merging**
