### PR TITLE
robots console self-destruct sequence access tweaks and more

### PR DESCRIPTION
**Pull request by gurfan**
The Self-Destruct sequence on the robotics console no longer requires robotics access.
The sequence takes 120 seconds to complete.
Starting the self destruct sequence will alert the AI and Cyborgs that it was started and tells the AI the name of the area where the sequence was started. 
The console get's a unique sprite when the sequence is active and beeps a message when it starts/stops/completes.
Depowering, unwrenching, or destroying the console won't stop the sequence.

alertbig

Things that were not changed:

Area Restrictions (The console can still be used in space or off the z-level)
Individual, Instant Lockdowns/Self-Destructs
Traitor Cyborgs still getting blown up if they weren't also emagged.
Emagging to remove access requirements.

[qol][tweak]

:cl:
 * tweaks: The emergency self-destruct sequence on the robotics console no longer requires robotics access but alerts silicons when it starts.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
I think having a secondary type would be better. So keep the normal robotics access one but add a no-access version with a much longer timer that sends some station-wide alert. I don't play AI so I can't comment on how reasonable the alert is, it does sound like it would just prevent borgs from ever getting blown during malf though.

**Comment by Irradiation** [comment]
What happens if the sequence is started and the console "mysteriously" get unbolted/dismantled by a COMPLETELY UNRELATED cyborg? Or what if a certain entity cuts off power to the room where the console is in? Does it keep going or does the timer conveniently reset?

**Comment by jknpj** [comment]
>baiting thumbs up with access 'QoL'
>but also doubles the timer and pinpoints the location of the console to the AI

sneakycoder

**Comment by PrimeDSS13** [comment]
>report location to AI and rogue silicons
>they just cancel it immediately

el silicreep...

**Comment by gurfan** [comment]
@jknpj @PrimeDSS13 @Rubylips 
Nobody uses the self destruct sequence in it's current state. If somebody has robotics access, they would blow 
the borgs instantly like they already do now. This PR lets people without robotics access blow the borgs. It's not as easy, obviously, but if someone doesn't have robotics access it shouldnt be. I don't see how this is silicon powerceep.

@Irradiation 
The timer stops if the console breaks or loses power.

**Comment by gurfan** [comment]
@Irradiation @PrimeDSS13 @jknpj @Rubylips 
I reworked it to be handled through the cyborg instead of the console itself. Here are the changes:

The self destruct countdown is handled in the cyborg, so the robotics console losing power/being broken will not stop the self destruct sequence. 
Only the AI is alerted to the location of the console when the sequence instead of both the AI and the cyborgs

**Comment by PrimeDSS13** [comment]
yeah okay I'm down with it now

**Comment by Dacendeth** [comment]
This option needed to be changed to something like this as there was basically no situation where you'd use this the slow timer to kill all the borgs over the other option of instantly just deleting all the borgs with a few clicks.

**Comment by DamianX** [comment]
fix conflicts

**Comment by DamianX** [comment]
good enough I guess

**Pull request merged**
