### PR TITLE
Simpolinol

### PR DESCRIPTION
**Pull request by Kurfursten**
I think Bomber Harris requested this
image

🆑 
* rscadd: New from NT labs, it's Simpolinol. Inject it into simple animals to heal them. Poisons more complex organisms. Great for miners, ranchers, or even just pet enthusiasts.
* rscadd: You can mix up your own, just mix methylin with some ground up silver. Bootleggers can duplicate the process by pouring vapor salts into any sort of aluminum can, like those used in soda...
* tweak: When using the health analyzer on simple mobs, it no longer shows all the damage types they don't have. Instead it just shows their current health.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Simp...

**Comment by Kurfursten** [comment]
It's okay to be a **S**avior **I**njecting **M**auled **P**ets

It poisons more complex life because you shouldn't be a Sucker Idolizing Monkeys and People

**Comment by tuypo1** [comment]
I was expecting this to be related to the new buzzword, I am pleasantly surprised

**Comment by Exxion** [comment]
I guess that means everyone has forgotten that "simple" is a word, then

**Pull request merged**
