### PR TITLE
Security cyborg FUCKING DIES(Peacekeeper "port")

### PR DESCRIPTION
**Pull request by JustSumBody**
This is a meme PR but it's also not a meme PR

Removes security borg module and replaces it with a neutered peacekeeper module 
Peacekeeper module comes equipped with the following(subject to change because I don't know how to balance):
Hug arm: Lets you hug or boop people on the head. 
Cookie synth: Makes cookies.
Harm alarm: Disorients anyone in range without ear protection and sends a notification to the AI.

As well as a flash, inflatables dispenser, crowbar, police tape, flashlight, and fire extinguisher. When emagged, peacekeeper borgs still get the laser gun(only because I'm not sure what better to replace it with) and their unique modules get special effects(hug arm can shock and crush, harm alarm knockdowns/deafens, cookie synth adds chloral to the cookies)

I considered adding the TG holobarrier things but ~~those looked like they took actual effort~~ inflatables/police tape is close enough.  

image

### CODE REVIEW

**Comment by TheFriggenSawbones** [comment]
we aren't bay

**Comment by Ephx1** [comment]
That harm alarm should be a thing somehow, but as an incredibly high cost upgrade that has a 30 second cool down.

**Comment by ScrambledSteak** [comment]
WOOP WOOP

##  **HUMAN HARM**

WOOP WOOP

**Comment by ghost** [comment]
how about this. cookie borg is available on code green, peacekeeper is available on blue, kill borgs on red

**Comment by Shaska-** [comment]
Huge nerf to AI's, both antag and non-antag.

**Comment by RoyalSev** [comment]
May as well give them an attachment to automatically bwoink the admins when anything happens. maybe it should come with a ban request form you can fill in?

**Comment by 9600bauds** [comment]
this shit is OP as fuck what's next a module that lets borgs pat themselves???

**Comment by ScrambledSteak** [comment]
Infinite nutriment? Come the fuck on justsum, this is creatine waiting to happen

**Comment by kilozombie** [comment]
Slippery slope to extendo-hug-arms for humanoids. Not fair

**Comment by TheFriggenSawbones** [comment]
i thought this shit was going to be its own module oh FUCK

**Comment by ghost** [comment]
@adu6oo has the right idea. Make the alert level matter

**Comment by kol1th** [comment]
Let's not make alert level matter

>roundstart call code blue

Haha ebin

**Comment by ScrambledSteak** [comment]
I saw the clown call code red

**Comment by ghost** [comment]
I know that's what you'd do, kolith, but it's better than the alternative

**Comment by kol1th** [comment]
Sure I would!

**Comment by ghost** [comment]
okay, would it be possible for the peacekeeper module to only unlock if theres a certain proportion of sec to crew, otherwise only cookie is there?

**Comment by aceedex** [comment]
Make this the only selectable module 
100% foolproof way to make every borg follow his laws. You'll never have to answer any ahelp ever again

**Comment by JustSumBody** [comment]
@9600bauds you joke but CHECK THIS FUCKING SHIT OUT 
https://github.com/tgstation/tgstation/pull/23465

**Comment by jakmak** [comment]
HOW ABOUT we remove the sec borgs tazer and reduce its speed so we can remove one of the most broken things in the game without having to use these meme borgs

**Comment by kol1th** [comment]
they aren't memes, they're peacekeeper borgs. We don't have sec borgs.

**Comment by NigglyWiggly** [comment]
>Replacing them with the pacifism borgs
>Not calling them pacifism borgs
>Not making them all soft shades of pink

**Comment by icantthinkofanameritenow** [comment]
Words cannot express how awful this is. It's a self-parody.

**Comment by Wizbing** [comment]
WHEN ARE WE GOING TO FIND OUT WHO THE HECKIN GOOD BOY IS

ALSO MERGE THIS WOOP

**Comment by AI-Is-Rogue** [comment]
The association of harming humans approves of this PR.

**Comment by Blithering** [comment]
Why remove the security module when we could have both?

**Comment by Wizbing** [comment]
Merge or feed

**Comment by Probe1** [comment]
"Its a meme pr but it isn't" says man about to post a meme PR.

**Comment by Anglosphere** [comment]
This is a good PR and should be merged before the Silicon CoderClub learns of its existence, and conspires against it.

**Comment by SysadminJeroen** [comment]
@Anglosphere Too late.

**Comment by BobdaBiscuit** [comment]
\>do not merge

FUCKING SILICON METACLUB DOES IT AGAIN

**Comment by Blithering** [comment]
For an alternative to the laser for the emagged mode, could the hug be turned into a chokehold that silences and slowly suffocates?

**Comment by AutismSpider** [comment]
@Blithering that be useless.WE have three races that don't need air better to stun and force feed them the meme cookies.

**Comment by Blithering** [comment]
They would have to have a squirtgun module as a standard feature too, but I like the idea

**Comment by Yelier** [comment]
This doesn't feel right.

**Comment by Probe1** [comment]
Anyhow.  @JustSumBody please stop making topical meme PRs we have enough for this week.

**Comment by BobdaBiscuit** [comment]
OY VEY

**Comment by ScrambledSteak** [comment]
Totally™ Not™ The™ Result™ Of™ The™ Silicon™™ Metaclub™™™™™™™™

**Comment by Blithering** [comment]
Silence disgusting carbon. I mean... Fellow disgusting carbon. Beep boop.

**Pull request closed without merging**
