### PR TITLE
Adds frogs and snails to the vermin random event

### PR DESCRIPTION
**Pull request by Kharkov72**
I for one cannot wait for the snails to pop in the kitchen and for the french chef to ascend.

:cl:
 * rscadd: Snails and Frogs can now show up randomly as part of the vermin infestation.

### CODE REVIEW

**Comment by jknpj** [comment]
Can you prevent snails from breeding until the server crashes first?

**Comment by Kharkov72** [comment]
wasn't that fixed by #26214 (Hard limit of 40 snails, they only reproduce once, etc)

**Comment by SageOfLight** [comment]
Shifty limited them already.

**Review by ShiftyRail — APPROVED** [review]

**Comment by jknpj** [comment]
Good.

**Comment by DeityLink** [comment]
image
🤔 

Due to the way switch cases are processed in Byond those two probably never fired ever and no one ever noticed.

**Pull request merged**
