### PR TITLE
Right-click to see invisible objects

### LINKED ISSUE #33482: clown invisispray shitcode
[bugfix]
making items sprayed on the ground(sharts) vanish from the right and alt click menu might be intentional
but this applies to normal items too, say you spray the captain's spare ID invisible
it will vanish from the rightclick and altclick menu, and you won't be able to pick it up
a T-ray scanner will make it briefly visible
>if you pick it up while the item is t-ray temporary visible, it will always remain visible
>if you right click while it's temporary visible, only to pick it up when it goes back to invisible, you'll have an item in your hand that you cannot right click, or remove from your pocket/backpack easily

### PR DESCRIPTION
**Pull request by adacovsk**
@pedr69 wants the ability to right-click to see objects and be able to pull invisible objects. *Emoji This *

## What this does
- Closes #33482

## Changelog

:cl:
 * tweak: You can right-click to see invisible objects again, sprayed with invisible spray

### CODE REVIEW

**Comment by angryturnip** [comment]
\>controversial
\>it's the way it worked before you changed it

wat

**Comment by adacovsk** [comment]
> >controversial >it's the way it worked before you changed it
> 
> wat

To be honest, I just wanted the Emoji This tag, but I don't know how to add it

**Comment by nervere** [comment]
Not all labels have an alias with the bot, it has to be manually assigned.
Regardless, this change probably came from you combining the multiple types of invisibility into one.
I don't think restoring this to its original behavior will be very controversial.

**Comment by DorainGrey** [comment]
> >controversial >it's the way it worked before you changed it
> 
> wat

Personally I think it's an improvement but that's just me. More fun to be truly invisible.

**Comment by Hinaichigo** [comment]
Maybe you should be able to pull them and pick them up, but not see them with right click.
And how does it currently work with the Pick up item verb?

**Comment by cloutcode** [comment]
>downvotes his own PR

**Comment by angryturnip** [comment]
> Maybe you should be able to pull them and pick them up, but not see them with right click. And how does it currently work with the Pick up item verb?

This would be better, but until someone adds it I'd rather have it the old way personally

**Comment by adacovsk** [comment]
> > downvotes his own PR

pedr69 and mangosteen were complaining about it, and since they are unfamiliar with the code, it was easier for me to make the PR, rather than them spend hours trying to figure it out

**Comment by pedr69** [comment]
will it really fix the main thing in that issue? things becoming visible forever if picked up during the t-ray visibleness tick?
i'm all for making invisisprayed items not show up in right click but i'd like it to be functional, too

**Comment by adacovsk** [comment]
> will it really fix the main thing in that issue? things becoming visible forever if picked up during the t-ray visibleness tick? i'm all for making invisisprayed items not show up in right click but i'd like it to be functional, too

t-rays were always broken and will remain that way, it's just the nature of how it works with `spawn` you're welcome to try and fix it, it's honestly not very good code at all

**Comment by SECBATON-GRIFFON** [comment]
this sucks stop upvoting it

**Comment by WindowsErrors** [comment]
hey remember how you couldn't touch anybody with a chameleon projector so it was simultaneously obvious and annoying when someone was using one

think of this like that

**Comment by Killette2** [comment]
Make it that you can right click but only when it's next to you
:^)

**Comment by Kurfursten** [comment]
Numbers and status quo on the side of merge

**Pull request merged**
