### PR TITLE
Adds plastic walls and floors

### LINKED ISSUE #3152: Suggestion/bug report - clear lockers/plastic walls
This is also a bug report, if you try to use plastic sheets on a girder as plastic registers as a mineral, it deletes the girder and uses the plastic rather than making a plastic wall. I think one would be neat.

I also think we should be able to have semi-see through plastic lockers. Thin lockers made of plastic that you can see through as to what's inside, as raincoats you can make with plastic are see through.

### PR DESCRIPTION
**Pull request by Intigracy**
closes #3152

Disregard the gray wall, I fixed it.

### CODE REVIEW

**Comment by 9600bauds** [comment]
> made of legos

:100: BRILLIANT

**Comment by PJB3005** [comment]
:+1:  :x:  :100:

**Comment by Praecordia** [comment]
n i c e

**Comment by Intigracy** [comment]
Images added to OP, all done.

**Comment by ihadtoregisterforthis** [comment]
This gives me an eerie windows 3.1 feel, but I don't know why.

PS: this must be why 
win3tetris

**Pull request merged**
