### PR TITLE
Adds Trader's Coat to Trader Supply

### PR DESCRIPTION
**Pull request by Shadowmech88**
:cl:
 * rscadd: Added three trader's coats to the Trader Supply vending machine, for 100 credits each.

### CODE REVIEW

**Comment by Zth--** [comment]
Actually it doesn't belong there. Why don't you put it in the non-premium list?

**Comment by Shadowmech88** [comment]
To the non-premium list of the Trader Supply?
How much should it cost?

**Comment by Durgen** [comment]
well traders don't have a bank account and vending machines don't take cash, so probably free

**Comment by Shadowmech88** [comment]
How many should there be?

**Comment by AI-Is-Rogue** [comment]
I'd say as many as the trader role slots. Or one less then that.

**Comment by Shadowmech88** [comment]
How many trader slots do we have?

**Comment by AI-Is-Rogue** [comment]
There are three trader slots.

**Comment by Intigracy** [comment]
Or make it cost money so they have something to work towards.

**Comment by Intigracy** [comment]
Also since when do vending machines not take cash?

**Comment by Shadowmech88** [comment]
Vending machines *do* take cash, but there's nothing in the payment window that suggests this, and clicking the "pay" button with the cash in hand doesn't work, you have to put it directly into the machine. It'd probably be good to make it more intuitive, but that's for another PR.

**Comment by Shadowmech88** [comment]
* The trader coats have been moved to the regular items section of the vending machine. Three coats can be bought for 100 credits each.

**Comment by AI-Is-Rogue** [comment]
Don't traders spawn with cash in a wallet still? Ranging from 10 to a thousand credits?

**Comment by Durgen** [comment]
the wallet spawns with either 1 or 2 credit chips in it. each chip is either 1, 10, 100, or 1000.
so traders anywhere from 1 single credit - 2,000 credits

**Pull request merged**
