### PR TITLE
Bus Hotfixes

### LINKED ISSUE #10241: Bus Station's Safe is shit
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!) baaa4e48682da18c80d2481b5ce7bfdfbe742951 

Bus' Vault Safe is really bad, a shitty bear pelt hat and a painting is a lot less than whats on box (painting, jumpsuit, key, replica katana)

### LINKED ISSUE #10252: Bus Station doesn't have any vault spawn locations

### LINKED ISSUE #10254: Bus Station AI Core Door is hidden under the AI sprite
(WEB REPORT BY: ghlor REMOTE: 172.93.109.202:7777)
Exactly what it says above.

Perhaps make the layer var 5 or something to ammend the issue.

### LINKED ISSUE #10256: [Bus] Science
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision baaa4e48682da18c80d2481b5ce7bfdfbe742951

RnD - No gadget bags, No hand labler and box of refills, Needs fire alarm, light switch. Duplicate newscaster

Toxins - wire and pipe break one tile above its entry airlock. 

Toxins storage - Needs an air alarm

RD - Air alarm, fire alarm, keycard auth, light switch, newscaster, intercomm, planning frame. firelock on the door

RD division - both areas, air alarm, fire alarm, light switch. Access needs a firelock. Move the sound system out from under the RD glass so we can use it.

Break room - firelock, fire alarm, air alarm, intercomm, light switch

Shuttle dock - Fire alarm, air alarm, intercomm, light switch

### LINKED ISSUE #10260: Plasma windows on Bus station TEG aren't connected properly.
(WEB REPORT BY: jeroen52 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c697cd94938cbb5314cdf83fe6b34201b643f6d5 
> 
> General description of the issue
> The windows are supposed to be connected properly.
> 
> What you expected to happen
> The windows are supposed to be connected properly.
> 
> What actually happened
> Not connected.
> 
> Steps to reproduce if possible
> Go to TEG.

### LINKED ISSUE #10261: Bus station brig
(WEB REPORT BY: mrslippy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

the pAI in the brig starting area, the with with the 2 chargers, stormtrooper hardsuit mod and SPS stack can not be picked up.

> General description of the issue

pAI module can't be picked up, it can be draged and pointed to.

> What you expected to happen

Be able to pick up and activate the pAI become i need a buddy ;_;

> What actually happened

Can't do shit but drag it off the table.

> Steps to reproduce if possible

Go to the brig and look for the pAI that world spawned at round start.

### LINKED ISSUE #10264: Bus is boring.
I don't know what it is, but it just feels empty and boring.

Probably lack of details and other fun things.

### PR DESCRIPTION
**Pull request by Kurfursten**
fixes #10256 
In general, cameras should be everywhere now. I went through as an AI to add them everywhere I could. I even added some to the sorter sat - hopefully will make it easier to jump between stations as AI with it to guide them.

fixes #10241 
Two exciting new safe rewards

fixes #10252 
Increased to 500x500 and added vaults

fixes #10254 
Moved four windoors up a few layers

fixes #10260 
Removed extra windows

fixes #10264 
This is a work in progress, but now every EVA is filled with all kinds of quirky rewards, ranging from toys, to first aid kits, to circuitboards.

fixes #10261
Ghost no more

### CODE REVIEW

**Comment by ComicIronic** [comment]
Need EVA images.

**Comment by Kurfursten** [comment]
untitled

merge pls

**Comment by ihadtoregisterforthis** [comment]
There is a debug option to check camera coverage

**Comment by Kurfursten** [comment]
Thanks for the tip

Knowing is half the battle

**Comment by Probe1** [comment]
@Kurfursten its terrible, it doesn't account for walls and shit.  Just host and pick AI its much easier.  You already have to join the game to use debug verbs -> mapping tab -> camera-coverage

**Pull request merged**
