### PR TITLE
Adds sprites for five cardboard box containers thanks to Blithering

### PR DESCRIPTION
**Pull request by Probe1**
/obj/item/weapon/storage/box/botanydisk
/obj/item/weapon/storage/box/holobadge
/obj/item/weapon/storage/box/mugs
/obj/item/weapon/storage/box/injectors
/obj/item/weapon/storage/box/spellbook (Switches between a sparkling wizard cardboard box and an upturned tophat)

and organizes these loose box paths into the master boxes.dm file.

image

### CODE REVIEW

**Comment by 9600bauds** [comment]
upturned tophat is GENIUS

**Comment by Probe1** [comment]
Shame you can't wear it but i'm not doing that.

**Comment by Aurx** [comment]
Make it so you get a tophat from unfolding it instead of cardboard sheets.  
OR BRING BACK HAT STORAGE.

**Comment by SonixApache** [comment]
>holobadge box

hey maybe some of those newshit sec officers will actually see and use them now

**Comment by Exxion** [comment]
Let's refactor storage clothes again to just use unremovable storage accessories so we can easily make storage clothes that aren't coats

**Comment by Probe1** [comment]
Merge it you n e r d.

**Comment by Probe1** [comment]
Desire to self merge increases

**Pull request merged**
