### PR TITLE
Fixes #9584

### LINKED ISSUE #9584: Items can no longer be hidden inside food
#### Description of issue

https://github.com/d3athrow/vgstation13/pull/9327 fugged it because they're all the same w_class

### PR DESCRIPTION
**Pull request by ghost**
Fixes #9584

### CODE REVIEW

**Comment by Intigracy** [comment]
Why isn't this just defined on the /sliceable level?

**Comment by Intigracy** [comment]
`<Comic>    Reminder that if you conform to bad code style you are the code equivalent of an Auschwitz guard and you deserve your own Nuremburg`

**Comment by Probe1** [comment]
wait what

you changed a single food item, pizza, and not cake or turkey or any of the other things?

**Comment by clusterfack** [comment]
Naw this is the second pr he fucked up the first

**Comment by Probe1** [comment]
Well I'm a dumb shit.

**Pull request merged**
