### PR TITLE
Packed station maint slimming

### PR DESCRIPTION
**Pull request by ghost**
[packed]
Was told this is the thing wanted most with packed, so worked on it.
Before:
image
After:
image
Tried to keep most of the old maint loot, but some is lost
:cl:
 * rscdel: Packed station maintenance has been greatly slimmed
 * rscadd: Packed station virology now has its own vent atmospherics

### CODE REVIEW

**Comment by Eneocho** [comment]
Yet another attempt at nerfing the maintcrawler.

**Comment by help-maint** [comment]
Seems to be pretty much the same as before except that viro juts off to the side instead of being donut'd in

**Comment by drawsstuff** [comment]
Don't like what's goin on with viro, do like the slimming of maint a little.

**Comment by KillFurries** [comment]
Like what's goin on with viro, don't like the slimming of maint a little.

**Comment by RaccoonBro** [comment]
Seems like about the same amount of space taken up. Maint in that area could be shrinked without moving viro pretty easily

**Comment by Rabbidx7** [comment]
Yeah I'm not a fan of fucking around with maint, but virology being located in meteor range? That's just fucking perfect. Good work. Next make packed slightly larger overall, and make the library and ghetto bar more than a tiny square.

**Comment by Theophrastus1** [comment]
how about you slim you up some bitches

its ok but viro is shit

**Comment by Armadingus** [comment]
I really like the cleared tunnel in front of the ghostly gym.
I hope you put a manual valve or similar on those air pressure tanks in the little viro maint, else all that air is going to waste once a breach hits. Also a pipe meter, that's standard.
Xenomorph rounds will be a lot like other maps, gives xenos more options. I got mixed feelings about that, being a xeno on a small station sucks, fighting xenos on lowpop is hard.

I like this overall.

**Comment by ghost** [comment]
> virology being located in meteor range?

Virology has now been meteor shielded like the rest of that side

**Comment by ghost** [comment]
> I hope you put a manual valve or similar on those air pressure tanks in the little viro maint, else all that air is going to waste once a breach hits. Also a pipe meter, that's standard.

Done

**Comment by Olb43** [comment]
Dont try to ((((fix)))) things thats not broken. Packed maint is fine

**Comment by ShiftyRail** [comment]
Doesn't seem to have enough support, unfortunately.

**Comment by ghost** [comment]
Fair

**Pull request closed without merging**
