### PR TITLE
Fix buttbots not working as intended after #17116

### PR DESCRIPTION
**Pull request by Mothblocks**
Don't merge yet, I'm still checking if this works.

### CODE REVIEW

**Comment by DamianX** [comment]
sneaky c*ders making buttbots unable to speak on the radio...

**Comment by Mothblocks** [comment]
I put the speak("butt") in the wrong place, whoops.

**Comment by gbasood** [comment]
are you 100% sure that `speak` does what you think it does
because I'm pretty sure I avoided it because it explicitly doesn't go over the radio

**Comment by Mothblocks** [comment]
@gbasood shit you're right, I'm not home right now but I'll take a look when I'm back if nobody else does in the meantime.

**Comment by Intigracy** [comment]
So it speaks "butt"/farts when it gets clicked, and speaks "butt"/farts right after it mimics someone with replaced butts.

I don't see the issue.

**Comment by gbasood** [comment]
`say` does saycode things
`speak` is a proc defined on buttbot that uses `visible_message` or similar
why radio shit would be broken for them I don't know

**Comment by Intigracy** [comment]
IS radio shit broken for them?

He doesn't actually say what the issue is.

**Comment by Mothblocks** [comment]
@Intigracy @gbasood When you talk near a buttbot, they only say "butt" and fart rather than replacing your messages.

**Comment by Mothblocks** [comment]
i'm going to close this and instead make an issue, and then make a pr when i can fix it.

**Pull request closed without merging**
