### PR TITLE
Adds food delivery bag.

### PR DESCRIPTION
**Pull request by Probe1**
Food delivery bags!  It was mentioned off hand to me and after asking in the thread people wanted it.  So now it's here.  Assuming it can pass review, which my PRs definitely need more than most since I'm extremely inexperienced.  Please look over it carefully, this is my first time doing any kind of spriting work.
- Holds 14 snacks items.  This includes cooked meals and raw plants.  Does not include seeds.
- Can scoop and dump all snacks items identical to a plant bag.
- Cannot hold food containers so no putting 5 stacked pizza boxes inside as one item.  It can hold a bowl of stew but could not hold that same bowl if it was empty.
- Fits in bags, belts and hands only.
- Snazzy sprite that changes between empty and full as well as in hand and in belt sprites.
- Dinnerware vend comes with 5.  There aren't any other ways of getting more.  Maybe I could add it to the biogenerator if that's a problem but I don't think it will be since they're just food bags.

ss 2015-05-26 at 04 08 23

Thank you to Anonymous in the thread who did the spriting.  Without you it would have looked terrible.

### CODE REVIEW

**Comment by 9600bauds** [comment]
Success

**Comment by CptWad** [comment]
:+1:

**Comment by Probe1** [comment]
I hope I did that changelog right.  I looked at two others and the example.html file.

**Comment by clusterfack** [comment]
Yeah its not as strict as it looks in the example file, you dont even neeed the two spaces before the plus

**Comment by NigglyWiggly** [comment]
Book bag like /tg/ has when?

Also congrats on the first two successful pulls!

**Comment by Probe1** [comment]
their sprite needs a little love but the code is identical to what I did here but for books obviously.  It'd be nice to have multiple sprites for fullness states.

image

**Comment by DeityLink** [comment]
>bag

Isn't that a lunchbox?

**Comment by Probe1** [comment]
It does look like a box, the branch name was just so I could keep track.

The sprites like 
image

**Comment by Probe1** [comment]
two PRs merged and I only inadvertently caused the server compile to fail once!

**Pull request merged**
