### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I was scrutinizing the syringe blocking aspect of the fix PR (it all works fine btw) and I found this oversight since the armor change (mob/living would have their immunity to a thing considered as if they'd have only 2 armor for the purpose of blocking effects)
Edit: Turns out one of the fixes also makes borgs immune to the taser slowdown so make of that as you will

:cl:
bugfix: Fixed a bug where silicons would be affected by the secondary effects of weapons, such as being slowed down by tasers.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I'm pretty sure there was a reason this is 2, I remember thinking the same thing when I was doing shields for ninja holograms.

**Comment by boy2mantwicethefam** [comment]
The parent proc checks for blocked >= 100, but I'll dig the code per your suggestions for more possible fixes

**Comment by Kurfursten** [comment]
I looked into it and it does seem that it SHOULD be 100...

That said I did send you a list of other places where you can change this to 100

**Comment by dunsel-hordon** [comment]
I like how it currently is with a stun slowing down a borg

**Comment by ShiftyRail** [comment]
Silicons being slowed by tasers is a feature, and the support for this isn't here

**Pull request closed without merging**
