### PR TITLE
Fix Sleeper Construction Typo

### LINKED ISSUE #6642: Sleeper upgrade requires 1 scanning module
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
2c376492abf6663ec0bc3fc0ccbf851bbcf5d744 

>General description of the issue
When you insert the circuit board to build a sleeper it says it requires two scanning modules but it is complete when only one is inserted.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by ghost**
- Sleeper takes one scanning module, not two
- Fixed another error I noticed right above it

Those descriptions should really be created dynamically when the frame is created, otherwise every time machine components are updated, this needs to be too. For further notice I guess

Fixes #6642

### CODE REVIEW

**Comment by N3X15** [comment]
Didn't we have an automatic thing that did this?

**Comment by PJB3005** [comment]
@N3X15 it's automatic whenever you change the components in the machine (add ones), but the initial description isn't.

**Comment by clusterfack** [comment]
Actually it's fully automated as long as you don't specify a description

**Comment by dylanstrategie** [comment]
I'll check if I can just completely can the starting descriptions then

**Pull request merged**
