### PR TITLE
fixes the wine > vinegar bug again

### LINKED ISSUE #18048: Wine and Vinegar conflict
Hey, its really minor, but its impossible to produce wine using the cooking recipe as any amount of wine will automatically change into vinegar due to how the recipes work.

>/datum/chemical_reaction/wine
	name = "Wine"
	id = WINE
	result = WINE
	required_reagents = list(BERRYJUICE = 10)
	required_catalysts = list(ENZYME = 5)
result_amount = 10
/datum/chemical_reaction/vinegar
	name = "Vinegar"
	id = VINEGAR
	result = VINEGAR
	required_reagents = list(WINE = 5)
	required_catalysts = list(ENZYME = 5)
result_amount = 5

Pulled up by a cult round of all things, thanks man.

But either the ratios need to change or Grapes need to be able to make grape juice and that needs to be the new wine formula.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

#11566
#11567

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #18048
by doing what #11567 was supposed to do

there's 2 vinegar recipes so I put them next to each other to stop confusion in the future

:cl:
* rscadd: Fixes turning water to wine via enzyme instantly turning it into vinegar.

### CODE REVIEW

**Comment by DamianX** [comment]
Does the first recipe even work? Is it not overridden by the latter?

**Comment by Intigracy** [comment]
Wine and ethanol are two different reagents.

**Comment by DamianX** [comment]
Okay but the paths of the two datums are the same?

**Comment by Intigracy** [comment]
nvm I'm dumb

**Pull request merged**
