### PR TITLE
middleclick now opens a radial interaction menu

### PR DESCRIPTION
**Pull request by PaulRitter**
[qol][featureloss]

This was made in an attempt to make radial menus more relevant since its a cool thingy
options can easily be added by overriding:
- (var) radial_menu, which holds all options
- (proc) doRadialChoice, which handles the logic

all atom/movable have these three options
image

all items got an additional pickup option
image

:cl:
 * rscadd: alt + middleclick now opens a radial interaction menu

### CODE REVIEW

**Comment by kilozombie** [comment]
Fun that I will now get an interaction menu when I try to middle click so I can swap hands

**Comment by brndd** [comment]
Middle click is for swapping hands, an extremely useful functionality when dealing with machines that steal focus from the main game window such as the identification computer. If something should default to radial menu it should be alt-click, or even something like alt-right click if right click functionality can be overridden.

**Comment by d3athrow** [comment]
Find another key combination to use instead of co-opting an existing one.

**Comment by kilozombie** [comment]
Also I can't possibly think of a situation in which I would want or need this.
There are already easier hotkeys for all of these options (pick up, pull, examine, point) which don't require the extra second and extra gunk of a radial menu.
(This is why I kinda really don't like the grinder radial menu after using it for long enough to realize I only really eject and activate grinders and the alt+click to eject was much more useful than the radial)

**Comment by SonixApache** [comment]
How about shift-rightclick, or some other rightclick combo?
Since you're essentially adding the rightclick options to this radial menu.

I relaly like the idea, just not the key for it.

**Comment by PaulRitter** [comment]
@SonixApache gave me an idea, i might just rework this to show the verbs of an obj on shift+rightclick

so i'll close and rework

**Comment by Exxion** [comment]
Sorry to be the bearer of bad news, but you can't override right click (even with modifier keys) without breaking the right-click menu for everything

**Comment by PaulRitter** [comment]
:(

**Comment by MadmanMartian** [comment]
alt middle click?

**Comment by PaulRitter** [comment]
alright i added alt middle click

**Comment by brndd** [comment]
Imagine if we could break the right-click menu for everything and replace it with something better... just imagine...

**Comment by Lunstra** [comment]
I fuckin hate those radial menus on the grinder and microwave reeee

**Comment by PaulRitter** [comment]
dunno how it goes about merging since the old one overrid middleclick hand swap and people got mad about it, this literally just adds on a new feature

c*llabs decide

**Comment by utilitas-** [comment]
It doesn't make sense for middle click to switch hands. Just press pageup, christ.
But neither does it make sense for it to open up a shitty menu that no-one will ever use. Radial menus are terrible and inferior in every way to a normal menu simply because you have to wait for two laggy clicks instead of just one, and because it closes once you move away.

I'd rather middleclick points/shows hand instead of having to do ctrl/alt+middleclick.

**Comment by Kurfursten** [comment]
Open a new PR if you want to try again so you can get a fresh start.

**Pull request closed without merging**
