### PR TITLE
two minor packed changes

### PR DESCRIPTION
**Pull request by SonixApache**
🆑 
- rscadd: packed now has a second microwave in the kitchen and a toys vending machine in the library

### CODE REVIEW

**Review by Kurfursten — APPROVED** [review]
Diff looks clean

**Comment by utilitas-** [comment]
how about instead of adding a useless microwave you add something the kitchen actually, seriously needs
(hint it's salt and pepper and a rolling pin)

**Comment by SonixApache** [comment]
@utilitas- ur a dumpass
image

**Comment by utilitas-** [comment]
`contraband = list(
		/obj/item/weapon/kitchen/utensil/spoon = 2,
		/obj/item/weapon/kitchen/utensil/knife = 2,
		/obj/item/weapon/kitchen/rollingpin = 2,
		/obj/item/weapon/kitchen/utensil/knife/large/butch = 2,
		)`
\>yes let's make the chef go get a toolbox and tediously hack his own machine in order to acquire an item that he should be getting from the start in the first place
I'm getting very worried for you, Sonix. You should take a break from all this.

**Comment by Kurfursten** [comment]
Vendor also has free salt and pepper which you also listed as unavailable. Ergo you both need to deescalate your egos. If this turns into toolboxing you're both in trouble.

**Comment by utilitas-** [comment]
since when does it have salt and pepper holy shit

**Pull request merged**
