### PR TITLE
You may NOT have my attention

### PR DESCRIPTION
**Pull request by ShiftyRail**
The "may I have your attention please" ambience file was a bit out of context and frankly annoying.
[sound]

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
duzvrr7ucaix8o0

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
your-attention-please-clipart-13

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
57d66e26fd94013766b4c447-5807cf0195cee4003cf1e25d

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
9781462722594_p0_v1_s600x595

**Comment by DeityLink** [comment]
I guess that sound wasn't playing before for a reason.

But still can we have shipambience.ogg play again? kthx

**Comment by Sooose** [comment]
This needs a speed merge.

**Pull request merged**
