### PR TITLE
Okay it's been literal months.

### PR DESCRIPTION
**Pull request by PJB3005**
We've been without sanitization for **REGULAR IC SPEECH** for **MONTHS.**
# MONTHS

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
MERGED OH GOD LAST GAME WHERE HTML TAGS IS POSSIBLE

**Comment by NigglyWiggly** [comment]
Was this even fucking tested man

**Comment by PJB3005** [comment]
This bug has existed for months, even before goon chat.

The issue just got bigger because assholes were uploading audio.

**Comment by NigglyWiggly** [comment]
The entire thing is awful though.
Like every thing about it is needlessly complex and allows a lot more room for bullshit

**Comment by clusterfack** [comment]
Allowing more room for shit, including the bull variety is entirely the point you retard @NigglyWiggly

**Pull request merged**
