### PR TITLE
Fixes #3898

### LINKED ISSUE #3898: (WEB REPORT BY: morriak REMOTE: 198.245.63.50:7777) Mech Bay Recharge Station parts vanished upon disassembly
>Revision (Should be above if you're viewing this from ingame!)
2f600cb374d7765a86aa1c20d83b02ab8f9cb915 

>General description of the issue
All the parts and circuit board disappeared a tenth of a second after prying the board out

>What you expected to happen
I would be able to check what board it used and upgrade parts

>What actually happened
Everything Vanished except the frame

>Steps to reproduce if possible
Disassemble a Mech recharge station

### PR DESCRIPTION
**Pull request by ghost**
For some reason, slapping RefreshParts() after the components were added like in most other machines fixed it. I only know that RefreshParts() is mandatory so that the machine registers new parts, for instance when you upgrade them. Maybe it's mandatory here too ?
- Fixes Mech Bay Recharge Stations not dropping their components when deconstructed
- Adds RefreshParts() to both machines. This is important, every other machine has it !

Note : This is a republish of #3933, I had serious repo problems, that is all

### CODE REVIEW

**Comment by dylanstrategie** [comment]
Okay, I'll do it another way altogether, shite

**Comment by dylanstrategie** [comment]
Ah fuck it, that'll do

**Comment by clusterfack** [comment]
Still does nothing though

**Comment by d3athrow** [comment]
department encryption keys part 2: holy fucking hell byondaloo

**Comment by clusterfack** [comment]
It's just an unreproduceable bug, this isn't even a fix

**Comment by dylanstrategie** [comment]
Well then

**Pull request closed without merging**
