### PR TITLE
removes ancient goon verb that's annoying with its own tab and shit

### PR DESCRIPTION
**Pull request by Intigracy**

### CODE REVIEW

**Comment by clusterfack** [comment]
Remove the html it points to as well

**Comment by Intigracy** [comment]
k

**Comment by clusterfack** [comment]
Thanks

**Comment by CptWad** [comment]
>Atmospheric Technician.... is probably the easiest job for a new player, so jump in as this and getting a feel for the station layout and the basic workings of the game before you try anything else.
>Security Officer: Open your locker, grab a stun baton and then patrol the station and hit people. That's it.
>Geneticist: This is pretty much the most complex job on the station. Don't touch this until you've played for a **while.**
>Chaplain: AARHGFHGHGH I FUCKING LOVE TO PRAY

beautiful

**Pull request merged**
