### PR TITLE
The Eggcellent Update

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Egg cartons now have a 1% chance per egg to have been mistakenly packaged with a non-chicken egg. This applies to both normal and vox cartons.
Currently this is **1 of 4 different egg types: parrot, cockroach, cockatrice, and chaos.** 
The latter two being the only real danger, and chaos only being dangerous based on RNG. After spawning 100 cartons I think 1% is the right number.

-->
:cl:
 * tweak: Egg cartons now have a small chance to come with a non-standard egg.

### CODE REVIEW

**Comment by jwhitak** [comment]
It's very easy to order a lot of egg cartons from cargo. This will be a reliable (though expensive) way to get chaos eggs and cockatrice eggs. There may be consequences for this PR and I do not want to see them.

**Comment by kilozombie** [comment]
>There may be consequences for this PR and I do not want to see them.

Why do people say stuff like this? Imagine, for a moment, that _one round_ out of hundreds is a little gunky because someone ordered a ton of eggs and did a gimmick with cockatrice eggs. It's not like that affects the round before or afterwards. It's very easy to hotfix if people take issue or start abusing it. And "not wanting to see it" is kind of confusing, because usually watching bullshit happen in spess is the funniest, most entertaining part of the game?

**Comment by AutismSpider** [comment]
just do xenoarc get ton of eggs if you find the right digsite.

**Comment by GreatBigFailure** [comment]
There's a lot of little things to consider with this regarding whether or not it's too easy to get dangerous stuff.
The best source of eggs is cargo, you can get a carton for 10 credits in the basic cooking supplies, or 30 credits will save you sorting through flour/milk if you buy the vox eggs. So each carton is a slot on the shuttle. I've never had cargo say no to a shuttle full of 20 crates the first time. I've had them say no plenty the second and third times.
So you have a 12% chance to get one per crate, then 1/4 of those times it's a cockatrice. So you have a 3% chance per crate. You also need to hatch it with the incubator. Then you have a single mob that dies in I believe one egun shot. 

This is mostly for the giggles, not the antag option. Though chaos eggs can definitely create fun times.

**Comment by KillFurries** [comment]
The combination of making something very rare, but also allowing people to roll the chance over and over until they force it is a bad one.
If there is a chance to get something, no matter how small, people will go for it. Your chance to get a specific egg you want is very small. There being a 0.25% chance to get a chaos egg doesn't mean you'll get one after checking 400 eggs. When an antag decides that they'll go for a gimmick that involves eggs they'll be sitting there gambling in cargo for a very long time. These are literal gacha eggs if you can order them from cargo. It should apply only to roundstart eggs.

Alternative suggestion - make the egg incubator emaggable. An emagged egg incubator can turn normal eggs into rare eggs. Better and more consistent than ordering a shitload of crates waiting for RNG.

**Comment by calzilla1** [comment]
Im annoyed that there arent any new egg-based recipies. Where the fuck is my tamago

**Comment by GreatBigFailure** [comment]
@KillFurries I can actually agree with that, if this is to be done as a gimmick it's a tough one to pull off. I might make a hacked (not emagged) cargo version of "Non-locally Sourced Eggs" that have a higher chance to be weird. Thing is, this isn't really meant to be an antag gimmick so much as something that might make itself available to a player who was already setting up to do ranching. 

I've been meaning to do some tweaks oriented around the egg incubator for a bit because I think it has good potential for fun. This was just a first step inspired by a recent bus that was subtle enough it had me wondering if a PR like this was already made. In the future I want to add a "fossilized nest" that contains several fossilized eggs. I was once given a good 50-100 fossilized eggs in a bus and even with that not much resulted from it, the things need to be easier to get to be at all used. 
I also want to add more egg types. They're very easy to add but we don't have many. Not having many to select from is why I decided against the hacked version of this.

**Comment by TGFH** [comment]
As @KillFurries it's way too easy to cheese. Why make this PR right after a round where a bussed cockatrice egg wiped out like half the crew? It just seems like a cheap way to griff or a noob trap that will just kill people who don't know any better.

**Comment by GreatBigFailure** [comment]
>Half

3, one of which was me. It would have been 2 but I bit the cockatrice for stoning my chickens, knowing doing so would stone me. 

>Why?

Round was fun

>Noob trap

Chaos eggs are glowing neon rainbow disco balls and cockatrice eggs are 3 times bigger than chicken eggs and shaped like a weird organ. Why is a new player ordering 30 crates of basic cooking supplies? If this were to somehow occur I think it would make for a fun story for that player and get them more into the game.

**Comment by Jackreturnswithaveangenace** [comment]
Implying I would use this to farm cockatrices and not PARROTS

**Pull request merged**
