### PR TITLE
Enhanced Lowfat Bagel's Nar-Sie altar

### PR DESCRIPTION
**Pull request by DeityLink**
image

* Replaced the bugged modified "blood" candles with actual cult 4 blood candles. Those spawn unlit, but magically lit up when someone comes adjacent.
* Removed the bugged invisible runes, instead added two "rune spawners" that spawn with a random rune (it's always an actual rune)
* Replaced the plating with cult floors
* Replaced the mysterious altar with an actual cult altar, which isn't a problem anymore now that altars aren't tied to cult progression

### CODE REVIEW

**Comment by Eneocho** [comment]
On my way to remove everything in that room but the runes to scream bloody cult in a non-cult round and have people freak out.

**Comment by BomberBro** [comment]
Bad idea to put mapped in evidence of an antagonist, my issue says more on that though.

**Comment by Exxion** [comment]
Yeah putting actual runes and cult items in a map at roundstart is not a good idea

**Comment by DeityLink** [comment]
I don't think is as bad of an idea as you make it out to be. More info in Bomber's issue.

**Comment by Kurfursten** [comment]
I believe this is going in the wrong direction. I think it looks cool and if you want to show this off you could make a really neat little spacevault for it, but we shouldn't put this on station. Or hell, keep the figurine and candles and picture but replace the altar with a legacy altar and delete the runes.

I would prefer you use this PR to delete the cultden.

**Comment by DamianX** [comment]
the candles were cool though

**Comment by DeityLink** [comment]
Get in touch with your friendly neighbourhood cultist for snazzy candles at half price!

**Pull request closed without merging**
