### PR TITLE
Wizard Spell: Fist

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds a new wizard spell, Fist. Casting it delivers a punch to everyone in view. It does not require robes to cast.
The punch will hit whatever zone you're currently targeting. Punches have the standard chance to miss on a per-punch and per-mob basis.
It costs 10 spell points, half as much as a standard spell.
By default its cooldown is 5 seconds, and its minimum cooldown is 1 second.

:cl:
 * rscadd: Added a new wizard spell, Fist. Casting it delivers a punch to everyone in view.

### CODE REVIEW

**Comment by ghost** [comment]
Unless I'm misinterpreting it, this is gonna go great with mutate.  I love it.

**Comment by SonixApache** [comment]
goddamnit

**Comment by ultraplen** [comment]
Mass disarm when? With a fair cooldown, of course.

**Comment by mtpowell** [comment]
Does this take into account armor?

nvm I looked it up :^)

**Comment by Ephx1** [comment]
No robes just got a whole lot better.

**Comment by SkowronX** [comment]
31bc036b6121a2c6339c7af7e31c282f

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
