### PR TITLE
More Blob stuff

### PR DESCRIPTION
**Pull request by DeityLink**
- Ghosts now appear above the blob layer.
- Blob Overminds now get notified when a new overmind appears in a blob core.
- Blob Overminds now have a "damage overlay" that updates as their core takes damage. Similar to the one humans have when they take damage (screen borders become dark/reddish).
- Most of the Blob Overmind notifications added in the last update now have a (JUMP) button, so for example you can immediately find which of your blob nodes just got destroyed.
- Blob Overminds have a new verb called "Call Overminds", which sends a notification to all the other overminds, along with a button allowing them to jump to you.
- Blob Overminds that spawn in a blob core created by an Overmind are now called Blob Cerebrate. So they can easily tell which one of them was the original one (and the only one who can place new cores)

bleabl

### CODE REVIEW

**Comment by Kurfursten** [comment]
> Cerebrates

"Awaken my child, and embrace the glory that is your birthright. Know that I am the Overmind; the eternal will of the Swarm, and that you have been created to serve me."

**Comment by gbasood** [comment]
yep
time to add that soundfile to blob cerebrate spawning

**Comment by ihadtoregisterforthis** [comment]
About the blob resource packs including spores and damage effects...
:wink: :wink:

> (and the only one who can place new cores)

Please explain

**Comment by gbasood** [comment]
@ihadtoregisterforthis apparently the original blob is the only one who could ever have spawned cores

**Comment by gbasood** [comment]
Looks good :+1: :+1: :100:

**Comment by DeityLink** [comment]
@ihadtoregisterforthis only the original blob has the power to create new blob cores. it costs 100 points and has to be placed at least 15 tiles away from other cores. Overminds created inside those new cores don't have that verb.

**Comment by ihadtoregisterforthis** [comment]
Looks like it wasn't mentioned anywhere else but this will help to clarify.

**Comment by Intigracy** [comment]
Is it intended that cerebrates are unable to expand the blob?

**Comment by Kurfursten** [comment]
AFAIK the only difference should be that they can't place new blob cores (new players)

**Comment by DeityLink** [comment]
What Kurf said. It's always been like that. I just gave them a different name so we can differentiate them (and so they can figure which one of them is the boss)

**Pull request merged**
