### PR TITLE
Security cameras can be hit with tools to destroy them

### PR DESCRIPTION
**Pull request by DamianX**
fuk sec
fuk the ai

:cl:
 * rscadd: Weapons and projectiles can now be used to damage security cameras.

### CODE REVIEW

**Comment by Reviire** [comment]
Lets balance it out by getting reinforced security cameras that are harder to deconstruct and can't be smashed.

**Comment by Tehsapper** [comment]
being able to smash compooters and other machinery when

**Comment by ShiftyRail** [comment]
More options are always good, I guess.

**Comment by SonixApache** [comment]
indestructable titan cameras

**Comment by Chazach** [comment]
mind making lasers being able to scunt em too, or would that be over the line?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Make sure the indestructible thunderdome cameras can't be destructed like this

**Comment by DrSnips** [comment]
I'm fine with the change but I think the camera alarm should go off if they start taking damage so it doesn't creep manually deconstructing them silently.

**Comment by DamianX** [comment]
good points

**Comment by Durgen** [comment]
Chance to leave DNA, effected by gloves?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Seems like projectiles don't trigger the alarm
Also the alarm probably should only sound for things over CAMERA_MIN_WEAPON_DAMAGE

**Comment by DamianX** [comment]
- Using weapons now leaves fingerprints and fibers, which are transferred to the camera assembly upon destruction
- No longer spawns a new assembly, reuses the one stored in the camera
- Projectiles (both bullets and lasers) can deal damage
- Dealing damage will trigger the alarm
- Unatomically fixed the camera assembly spawning with the wrong icon/anchored state
- Thunderdome cameras are still immune to damage

**Comment by DamianX** [comment]
Made it trigger the alarm right before it gets deactivated but I can change it back if it makes more sense

**Comment by DrSnips** [comment]
I feel like it kinda creeps on the balance between hacking the camera to deactivate it and just smashing it. Smashing it is crude so it should alarm at sone point during the attempt to since it doesn't really do anything for the cam viewer's side except tell them that it's gone which could be infered by the cam going missing anyway.
Smashing is crude and should raise the alarm like smashing a window.
Taking the time to carefully hack the cam so it's a quiet removal should be like unscrewing and removing the window quietly and carefully.
Maybe the alarm goes off at 75% or  50%?

**Pull request merged**
