### PR TITLE
Fixes #10005

### LINKED ISSUE #10005: Project Mind can be used to metagame someone's real identity
If someone masks their identity by any means, such as using someone else's ID and a mask, an agent ID, whatever have you, things get tricky and meta-ey.
Their FAKE name is displayed in the list of people you can project mind to (i.e. "Don Newman"). Up until you send the message, they are always displayed using their FAKE name.
dreamseeker_2016-05-10_16-44-47

However, the chatbox message you get afterwards uses their REAL name.
dreamseeker_2016-05-10_16-45-34

Someone using a voice changer to impersonate someone else? Let me whip out my project mind real quick so I can instantly confirm there are 2 identical names on the list. Sure there are, let me call them a faggot real quick. Oh that's who they really are.

### PR DESCRIPTION
**Pull request by ghost**
fixes #10005 by making you have to type out the real name of the target

### CODE REVIEW

**Comment by Shadowmech88** [comment]
For what its worth, simply populating the list with the real name of every target instead of the display name of every target would also fix this, and would not change functionality otherwise.

**Comment by ghost** [comment]
@Shadowmech88 Yeah but there are almost definitely people on that list of every real name you don't want there.

**Comment by Shadowmech88** [comment]
Like who?
I guess maybe nukeops since they all have the same last name, but anyone else?

**Comment by ghost** [comment]
@Shadowmech88 Nukeops, raiders, wizards if you compare names to manifest, people who used DNA scrambler, etc etc etc.

**Comment by ComicIronic** [comment]
Make it a spell flag instead.

**Comment by ghost** [comment]
@ComicIronic done

**Comment by clusterfack** [comment]
I thibk this is such a shit way to fox this

**Comment by 9600bauds** [comment]
C H A N G E L O G

**Comment by 9600bauds** [comment]
C H A N G E L O G

**Comment by ghost** [comment]
@clusterfack *shrug, I liked that suggestion, so I ran with it
@9600bauds ehhhhh

**Comment by 9600bauds** [comment]
"ehhhh I don't want to" or "ehhhh this doesn't need it"?
Because this needs it

**Comment by ghost** [comment]
@9600bauds both :^)

**Comment by Imagebard** [comment]
So you have to write the name of the person you want to use telepathy on?
Oh man. It'll feel a lot more personal now.

**Pull request merged**
