### PR TITLE
fixes ghetto spacesuit species tagging

### LINKED ISSUE #15180: Any real reason that Dionae can't wear ghetto space suits?
#### Description of issue
Dionae can't wear ghetto space suits

#### Difference between expected and actual behavior
I don't see why they can't. same head, dionae and humans can both wear nasa suits, voidsuits, hardsuits, but not this?

#### Steps to reproduce 
try to wear a ghetto space suit as a diona

### PR DESCRIPTION
**Pull request by toomykins**
[easy][bugfix]
Fixes #15180
dionae can now wear ghetto spacesuits.
~~shrooms and greys can now no longer wear ghetto spacesuits (kao dekai!)~~
Dionae AND greys can wear ghetto spacesuit, greys now have their own helm sprite because their face is big. 
I fixed the lamp on the ghetto spacesuit head somewhat

:cl:
 * rscadd: allow dionae to wear ghetto spacesuit
 * rscadd: greys now have a fitting ghetto spacesuit head sprite
 * rscadd: the light on the ghetto spacesuit head now somewhat works.

### CODE REVIEW

**Comment by Buchse** [comment]
why shouldn't greys be able to wear ghetto spacesuits?

**Comment by toomykins** [comment]
could theoretically wear the suit, but helmet would require spritework, face too big. made it so they couldnt wear the suit either because *shrug* coherence, didnt think it over.

**Comment by Buchse** [comment]
> could theoretically wear the suit, but helmet would require spritework, face too big. made it so they couldnt wear the suit either because shrug coherence, didnt think it over.

well... just do the sprites then? it's just the grey alt for the fire helmet slapped over a gas mask with minor editing.

**Comment by toomykins** [comment]
first time spriting anything in byond, let's hope i didn't fuck anything up.
also made the ghetto spacesuit head's lamp work, but since i suck at coding i basically just copied the hardhat code, which sucks since the sprite doesn't update that well ingame.

:cl:
 * rscadd: allow diona and greys to wear ghetto spacesuit
 * rscadd: greys now have a fitting ghetto spacesuit head sprite
 * rscadd: the light on the ghetto spacesuit head now works.

**Comment by Buchse** [comment]
good work lad

**Comment by ShiftyRail** [comment]
Make the changelog better. The one you posted in your 3rd post is formatted the right way, you need to copypaste it into the OP.

**Comment by toomykins** [comment]
done!

**Pull request merged**
