### PR TITLE
allow resisting out of straight jackets

### PR DESCRIPTION
**Pull request by DamianX**
If you think it should take more than two minutes you're wrong and I will not elaborate further.

:cl:
 * tweak: It is now possible to "resist" out of straight jackets. It takes two minutes.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
Straight Jackets right now are probably the least fun item in the game. If you need an item that is literally inescapable to the person wearing it, you might as well just kill them or throw them in perma. 
You can also throw cuffs on people with straight jackets, so they're still good for that kind of stuff.

**Comment by BomberBro** [comment]
Should be 4-5 minutes since it's rarer than handcuffs.

**Comment by djkramer123** [comment]
Should have a chance to break an arm

**Comment by DamianX** [comment]
> 
> 
> Should be 4-5 minutes since it's rarer than handcuffs.

Nah, that's just the ideaguy wannabe-game-designer part of your brain speaking. Nobody wants to stand still for 2 minutes, let alone 4.

**Comment by kilozombie** [comment]
> > Should be 4-5 minutes since it's rarer than handcuffs.
> 
> Nah, that's just the ideaguy wannabe-game-designer part of your brain speaking. Nobody wants to stand still for 2 minutes, let alone 4.

You are completely right

On the other hand, nobody wants to micromanage a prisoner every 2 minutes

I don't even really have a solid horse in this race but the reason people use straightjackets is because they want to fire and forget, to say nothing of their intent of doing that

**Comment by BomberBro** [comment]
> Nah, that's just the ideaguy wannabe-game-designer part of your brain speaking. Nobody wants to stand still for 2 minutes, let alone 4.

Nobody wants to stand around for **any** period of time, if we go by that logic you should just be able to drop a straitjacket immediately like a butterfly escaping its cocoon.

**Comment by SonixApache** [comment]
longer time and/or break arm or gain 1d8 👎

**Comment by Eneocho** [comment]
> 
> 
> longer time and/or break arm or gain 1d8 👎

The metaclub reveals their presence.

**Comment by Kurfursten** [comment]
This does not look like it will gain the necessary support but I want to give it a week given the interest in it

**Comment by GreatBigFailure** [comment]
>like a butterfly escaping its cocoon.

A clown or mime successfully escaping a straight jacket should evolve. I don't care how.

**Comment by Kurfursten** [comment]
Alas for the lack of iron maidens and sarcophagus.

**Comment by Eneocho** [comment]
> 
> 
> > like a butterfly escaping its cocoon.
> 
> A clown or mime successfully escaping a straight jacket should evolve. I don't care how.

The clown gets its icon updated to the gigachad clown icon and they get stun immunity.

**Comment by WindowsErrors** [comment]
whatever I said for the other PRs of this derivative 

https://github.com/vgstation-coders/vgstation13/pull/31195#issuecomment-960054614

**Comment by Blithering** [comment]
I support this pr but I support the breaky arm one more.

**Pull request closed without merging**
