### PR TITLE
WIP: Role datums roles

### PR DESCRIPTION
**Pull request by N3X15**
Working on role datums and making shit compile.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
Should be to the role datums branch, not bleeding-edge

**Comment by SysadminJeroen** [comment]
WHEN

**Comment by Hugh-G-Rection** [comment]
Clocks ticking 💰

**Comment by N3X15** [comment]
Didn't get anything done today since I moved the code to my laptop.  Will be driving all day tomorrow, may get some done in the afternoon.

And I don't give a fuck about the bounty.  Will let it lapse.

**Pull request merged**
