### PR TITLE
AME Polishing and QoL

### LINKED ISSUE #8510: AMEs still shit a brick sometimes when they're made
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/fFq3Ekq.png

Stupid cores not working.  It's been broken for like six months at this point!

### LINKED ISSUE #24190: what did you do to the AME
image

### LINKED ISSUE #26396: The Antimatter Engine sucks ass to set up and use
[ui] [bug]

There's two pretty annoying problems when trying to use the antimatter engine in a round:
1. The modular part of it just doesn't refresh the parts properly sometimes when you first set it up. You end up mashing the refresh parts button to try and get it to have the second core to show up.
2. Something is broken with its Nano UI panel where it won't refresh the page whatsoever. Closing the window and re-opening it will refresh it, but it gets annoying when you want to turn it on or adjust the injection rate. (related to #24190 I guess?)

### LINKED ISSUE #29679: AME's UI is painful. You need to manually refresh the window for it to update so you don't get feedback and can fuck up if you're new/not careful.
Apparently it's due to being one of the first UIs to use nanoUI. At least the other nanoUIs work "properly". Related to #26396 and #24190.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #8510
Fixes #24190
Fixes #26396
Fixes #29679

Also fixed the dmi having twice as many sprites as normal for no reason since core-adjacent parts look just the same.

And removed the old placeholder .dmi.

ame_tweak
image

https://user-images.githubusercontent.com/7573912/126250598-280bc2d0-466f-4139-9f96-52c65cbd4e33.mp4

:cl:
* rscadd: The AME has gotten a bit of TLC, featuring new sounds, animations, a properly scaled UI that updates when interacted with, and the packaged reactor sections have gotten a new sprite and more importantly update the surrounding shield parts immediately after being deployed. The cores also emit a tiny bit of light when the AME is active. Finally the jars themselves now have in-hand icons, and feature a gauge on their side that displays how much fuel they have.

### CODE REVIEW

**Comment by DrSnips** [comment]
While you are making sprite changes/visual QoL. Could I ask for a simple change as well?
AME jars having a visible "fullness" to them like them being more or less blue or a gauge on them to show their fullness and the main console having a blue jug thing slotting into one of the two bottom ports if it has the jug?

**Comment by Eneocho** [comment]
> 
> 
> While you are making sprite changes/visual QoL. Could I ask for a simple change as well?
> AME jars having a visible "fullness" to them like them being more or less blue or a gauge on them to show their fullness and the main console having a blue jug thing slotting into one of the two bottom ports if it has the jug?

Some sort of overlay like the one that med drink can has would be nice.

**Comment by Eneocho** [comment]
add #24190 too

**Comment by SonixApache** [comment]
fuggen cool, nice work

**Comment by DeityLink** [comment]
> 
> 
> add #24190 too

nah, the UI is still distorted and I'm not fucking touching nanoui

**Comment by Eneocho** [comment]
RIP the AME cubes. You had a good run.

**Comment by DeityLink** [comment]
> 
> 
> While you are making sprite changes/visual QoL. Could I ask for a simple change as well?
> AME jars having a visible "fullness" to them like them being more or less blue or a gauge on them to show their fullness and the main console having a blue jug thing slotting into one of the two bottom ports if it has the jug?

It is done. I even made different sprites for each jar type
image

Oh right, fullness, I'll do that too.

**Comment by DrSnips** [comment]
Cool stuff!

**Comment by DeityLink** [comment]
There, with some in-hands too 
image

**Comment by DeityLink** [comment]
So one line break was all it took 
image

**Comment by Eneocho** [comment]
> It is done. I even made different sprites for each jar type
> image

2 jars on the AME? Is it the age of multi tank drifting?

**Comment by DeityLink** [comment]
nah, it's the sprite for the huge tank variant.

**Pull request merged**
