### PR TITLE
Fixed num2hex not padding with the right number of zeros

### PR DESCRIPTION
**Pull request by DamianX**
This is a screenshot of the character preferences window.

I noticed the little square that should match the hair/facial hair color of the spessman was SOMETIMES pitch black, despite the selected color not being black.

image

So I looked at the HTML of the window, and noticed the value for this color was `background-color: #CC990;`.
That is produced by this piece of code:
`background-color: #[num2hex(r_hair, 2)][num2hex(g_hair, 2)][num2hex(b_hair, 2)];`
which looks fine, meaning the bug is in num2hex, specifically when the number is 0 it didn't append another.

So I pulled the num2hex implementations from bay, paradise and TG, wrote one in libvg, benchmarked them, found out TG's is the fastest, made it return uppercase letters (because our old one did and theirs didn't), made it even faster, wrote tests for it, and sure enough:

### CODE REVIEW

**Comment by Exxion** [comment]
dude bitwise operations lmao
Except bitwise operations are probably actually *slower* in BYOND than normal mathematical ones because it has to convert float to int and back

I haven't verified that though so don't quote me on it

**Comment by DamianX** [comment]
but I have!
```
proc/num2hex(num, padlength)
	var/global/list/hexdigits = list("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F")

	. = ""
	while(num > 0)
		var/hexdigit = hexdigits[(num & 0xF) + 1]
		. = "[hexdigit][.]"
		num >>= 4 //go to the next half-byte

	//pad with zeroes
	var/left = padlength - length(.)
	while (left-- > 0)
		. = "0[.]"
```
this one's consistently worse than the PR'd version. Still faster than our current one, though.

**Comment by Exxion** [comment]
In a sensible language, I suspect that would be the fastest possible implementation, excepting witchcraft of the fastinvsqrt variety
But this isn't

**Comment by ShiftyRail** [comment]
Maybe this fixes the bug in which cloned people get a different hair colour.

**Comment by SGuivenne** [comment]
THATS A BUG!?  I THOUGHT THAT WAS A FEATURE FOR YEARS

**Comment by Exxion** [comment]
Nope
#5054

**Pull request merged**
