### PR TITLE
Updated cyborg self diagnosis UI

### PR DESCRIPTION
**Pull request by DamianX**
Before:
image

After:
image

:cl:
 * tweak: Updated the cyborg self-diagnosis UI.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Maybe do colored text for powered and toggled?

**Comment by DamianX** [comment]
I have no style, I have no grace
I'm going to need #rgb values to put in

**Comment by Kurfursten** [comment]
Feels nice to be able to return some of the help you've given me. Our standard template colors are found under nano/css/shared.css, and here are the most common three (green, yellowish, red)

'good' #4f7529;

'average' #cd6500;

'bad' #ee0000;

**Comment by DamianX** [comment]
And I've been told they are ass by one of the few people that cared about these things
#17140

**Comment by Kurfursten** [comment]
Maybe we should locate a homosexual to find us attractive new RGB values for our templates, since we use those in all the nano UIs

**Comment by Probe1** [comment]
I messaged Celt but my god is that an open field and I don't know which coder I should message.

**Pull request merged**
