### PR TITLE
Removed doppeldanger spell

### PR DESCRIPTION
**Pull request by Kitfox88**
Every wizard round one's taken this spell has been gunked beyond belief.

[featureloss]

:cl:
 * rscdel: remove doppelganger because it's broken as fuck, fix it

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Bruh moment

**Comment by ghost** [comment]
Whoever wishes to have it removed should first make an attempt to balance it. Or at least suggest some changes.

My proposal:
* remove all ability to deal damage from the spell
* increase cooldown to 50/40/30
* make clones invulnerable
* make clones disappear after 1 minute flat

**Comment by Kitfox88** [comment]
Remove it and then let people argue over balancing, as it is right now it's completely broken and a single wizard with doppel and blink shits up rounds faster and more safely than any ling or cult could dream of.

**Comment by boy2mantwicethefam** [comment]
C*ders removed Changeling from rotation without a poll and then talked about balance but it's still not back, don't go their way

**Comment by Kitfox88** [comment]
It's a single spell that's being abused every other wizard round to make them completely unplayable, comparing that to removing an entire antag is fucking stupid even for you.

**Comment by Chazach** [comment]
absolutely based, this spell should never have been made

**Comment by DamianX** [comment]
Whoever wishes to have it added to the game should first make an attempt to balance it. Or at least discuss some ideas.

My proposal:

- Remove things that are not fun
- Provide an argument for why it's something worth keeping

**Comment by Kitfox88** [comment]
Yeah I mean why would you want to remove this perfectly balanced and fine spell from the game as it currently is.
totally balanced and in no need of immediate revision or removal to be merged within the hour

**Comment by boy2mantwicethefam** [comment]
mad cuz bad

**Comment by ghost** [comment]
Very easy fix would be to limit amount of clones to 1/2/3 based on level.

**Comment by Kitfox88** [comment]
Then fucking code and make THAT push and merge it.

**Comment by Chazach** [comment]
> mad cuz bad


rich coming from:
#22388, #22014, #18856

**Comment by ghost** [comment]
I'm not the one having problems with it.

**Comment by boy2mantwicethefam** [comment]
@Chazach Mad cuz bad

**Comment by ShiftyRail** [comment]
Here's an idea : if a clone dies the wizzie man gets hurts a bit
Alternatively, I introduced numbers in a PR that nerfed D*ppls long ago, maybe those numbers can be lowered again

#18353

For all that matters, I don't like the spell either, I just believe straight-up removing content isn't the way forwards in this context

**Comment by Kitfox88** [comment]
Having them hurt the wizard so they're not a 100% safe ez fuck station button would be solid.

**Comment by ghost** [comment]
This same post is gonna be mirrored in the other two PRs as well. Reactive, same day balance PRs are NOT ok and the server should not fall back into passing them due to a few bad rounds today.  All three PRs need to be closed and if the spell should be touched, there should be more of a discussion as to why along with a game plan.  This is not the way to manage the code-base.

**Comment by SirSkeleto** [comment]
tbh doppel should have been on the chopping block earlier. I've hated it since I first saw it, and every round that I've seen it used has been hell. This was not a unique incident, trust me.

**Comment by Chazach** [comment]
just because you sound like a cunt doesnt mean your opinion is right
if something is so horrible it has 4 nerf PRs up, why shouldnt it be trashed? there wasnt this much of a discussion when the spell was added, and since its a net negative to the game why should there be this much discussion now?

**Comment by ghost** [comment]
This is lynch mob balance and it is not the right way to go about things.  Yes it was a shitty round, yes the spell has issues, yes there needs to be a discussion.  Supporting this way of going about things is absolutely moronic and it is historically the reason so many mechanics and game-modes have been absolutely shit on the server.

**Comment by MechaMusume** [comment]
Literally "I DED PLZ NERF :_:"

**Pull request closed without merging**
