### PR TITLE
Adds flatpack stacking

### PR DESCRIPTION
**Pull request by ComicIronic**
You can now stack flatpacks to create flatpack stacks.
Flatpacks can't be placed on stacks when opened, or opened when in a stack.
Stacks can be separated contextually through clicking. You can break up one stack into multiple stacks if you click in the middle of the stack.
Some flatpacks now also have a departmental icon for easier identification.
Example : http://puu.sh/hAw2P/0bf3a303b2.webm
Stacking

### CODE REVIEW

**Comment by Probe1** [comment]
Addresses https://github.com/d3athrow/vgstation13/issues/4249

Nice work Comic, I like how they look especially.  I'll download it tomorrow if it isn't merged by then.  Thank you.

**Comment by FudgePucker** [comment]
Now all we need are forklifts to carry them around the station.
And also forklift joust.

**Comment by clusterfack** [comment]
Ripleys ARE forklifts. They just need a rework.

**Comment by FudgePucker** [comment]
They move too slowly, I want to joust not slowly bump into each other and punch.

**Comment by NigglyWiggly** [comment]
Forklift races around the station when

**Pull request merged**
