### PR TITLE
Adds boot knife holsters, biogenerators can make holsters

### PR DESCRIPTION
**Pull request by 9600bauds**
The tacticalness continues

Added knife holsters which can be attached to any pair of shoes. They can currently be found in Security lockers (and the HoS spawns with one already clipped to his boot). Security knife holsters already come preloaded with a 10 force tactical knife.

The Biogenerator can now make handgun holsters, as well as the new boot knife holster. Yes, this is a balance change too, but I feel like the biogenerator doesn't really see much use, hopefully this lets botanists feel appreciated.

Sprites courtesy of Blithering, knife sprite stolen from Bay:
untitled-1
untitled-2
untitled-3

### CODE REVIEW

**Comment by kol1th** [comment]
:+1:

**Comment by TheFriggenSawbones** [comment]
REFERENCE SPACE VIETNAM
E
F
E
R
E
N
C
E

S
P
A
C
E

V
I
E
T
N
A
M

**Comment by SkowronX** [comment]
> > Sprites needed!
> > literally 8 pixels max

BUT WHY. Saying you suck is no excuse.

**Comment by 9600bauds** [comment]
The 32x32 item sprite mostly
By asking for a spriter's help, everyone wins

**Comment by Shadowmech88** [comment]
Even the 32x32 sprite is still just a 6x6 square.

Also on a related note I think the full sprite should be a rectangle, not a square, unless it's a square because the straps to hold it to the boot are included in the shape.

**Comment by Blithering** [comment]
I'll give this a go later

**Comment by ComicIronic** [comment]
> Even the 32x32 sprite is still just a 6x6 square.

As a placeholder, not as the full sprite.

**Comment by 9600bauds** [comment]
U da bess blithernig

**Comment by Blithering** [comment]
There's gonna be a few shoes that the overlay for it being attached to the item isn't going to work for. Clown shoes, kneesocks, and vox magboots for example. The on-mob icons will still work.

**Comment by Blithering** [comment]
@9600bauds http://s000.tinyupload.com/index.php?file_id=04173310656683170905 
Think that's everything needed. Let me know if I missed something.

**Comment by 9600bauds** [comment]
This will be the first clothing accessory with an inhand sprite at all, magnificent

**Comment by 9600bauds** [comment]
Overview of the sprites, much love Blithering: 
https://a.uguu.se/0WB5h5mZw3Fj_Desktop07.04.2016-02.00.32.02.webm

**Comment by 9600bauds** [comment]
Only immediate concern is that magboots are kinda too fat but that's probably OK.
dreamseeker_2016-07-04_02-36-25

**Comment by icantthinkofanameritenow** [comment]
I do have one question about this: what would the average security officer even need a knife for anyway? The  stun baton does the same amount of damage on harm intent and has a greater number of applications; if it's about providing lethal weapons to security in case of emergency, then generally they'll want something a little more robust than an knife as well. 

> handgun holsters 
> You mean the shoulder holster, right? Well fuck, that means the general fabricator will be even more useless than usual. Seriously, I think the biogenerator would be used far more often if more chefs knew it can make meat and milk.

**Comment by 9600bauds** [comment]
Mostly to be cool, and a very last resort if you lose your baton somehow. I don't imagine a lot of people will try to steal your boots to steal your knife.

I agree it's not very useful but I think that's better than something OP or powercreepy. If we want to make it a little better it could be force 12, at which point it will still be worse than a welder. Fun fact: In Bay, this knife also works as a hatchet

**Comment by icantthinkofanameritenow** [comment]
> bay

REEEEEE GET OUT

In all seriousness, I guess this wouldn't be too terrible so long as nobody got the idea to start stabbing people with them, but having shoulder holsters and these being mass produced without at least the effort needed for a mechanic to scan them first is a bit much. 

That said, unlike batons these have no way of stunning, so I can't really see any legit uses for these save for an officer who has literally nothing else available to him. (And let's be honest, the most common reason for that is because the guy who stole his baton is now beating the officer to death with it. A knife won't be much good when you're being stunlocked.) Even in that scenario, it won't exactly be a lifesaver. Perhaps that old idea about officers being given a weak ballistic sidearm might be worth reviving for that purpose instead?

Perhaps a bit more relevantly to the admin end, I get a feeling there's going to be a lot more ahelps about shitcurity of this goes through, both from shitters who forced sec to stab them because they took all their stunning options away and from people who were the victims of overzealous security officers who couldn't resist the temptation of their new toys.

**Comment by 9600bauds** [comment]
I don't play on Bay, I just steal their features :^)

**Comment by Blithering** [comment]
The solution is staring us in the face. HAVE THE KNIFE MAKE YOU RUN FASTER!

**Comment by 9600bauds** [comment]
Maybe when movement speed gets unfucked and you can practically run faster than base speed

**Comment by Blithering** [comment]
I thought there was a recent change that made movement speed easy to change, and that allowed for the speed setting when observing. Still, I can see some times when having a tool with sharpness would be handy for sec. As it stands they are mostly helpless against vines.

**Comment by Shadowmech88** [comment]
@9600bauds 
You can modify a mob's `movement_speed_modifier` var to change the speed at which they move, even making them move faster than the current "cap."

**Comment by 9600bauds** [comment]
Ideally movement_delay() wouldn't still be ass so we could sensibly just use that instead

**Comment by 9600bauds** [comment]
I completely forgot I had made this thing

**Comment by Intigracy** [comment]
the biogen change is the best part

interdepartmental cooperation a best

**Comment by icantthinkofanameritenow** [comment]
But the holster thing was literally the only thing that made the general fabricator not shit. That's as harmful to cooperation as this is helpful to it. Plus, as I said it encourages Shitcurity to stab people because they can.

**Comment by 9600bauds** [comment]
Multiple sources of coop is not a bad thing, just like how you can get a large beaker from a couple places, and the biogenerator needed something 
About shitcurity we'll see how it goes I guess

**Comment by Blithering** [comment]
Idea that might make everyone a bit happier: Give the HoS a unique shock-knife thing, have it able to be genfabbed, but not able to be produced elsewhere. Gen fab gets something else worthwhile to make, bootknives become a reliable backup tool if the work and cooperation is put in, and people get electric knives thrown at them.

**Comment by icantthinkofanameritenow** [comment]
But isn't that just basically making another stun baton for the guy who already gets that and the telescopic  baton? It seems redundant at best if you ask me.

**Comment by icantthinkofanameritenow** [comment]
@9600bauds

It already had something - unlimited meat and milk. The only reason it's not used is because nobody remembers it. All that's needed is to draw attention to it, not give it something new at the expense of a job that's already considered to be "assistant with engineering access".

**Comment by ComicIronic** [comment]
The meat and milk are used for service, which is a very low-level interaction given the chef is right next to botany. Chemistry can already make meat for medbay, and Chemtism who use milk for cryo will have more than enough from the Bartender.

**Comment by 9600bauds** [comment]
> use milk for cryo

I will fucking find you

**Comment by Blithering** [comment]
Sprinkles are for the true madmen of cryo mixologists.

**Comment by icantthinkofanameritenow** [comment]
@ComicIronic
Interaction doesn't need to be high-level to be effective. Hell, with the server being what it is we have no choice but to start with the lowest levels.

**Comment by ComicIronic** [comment]
It's not a question of being effective, it's a question of there being enough reason to warrant any interaction in the first place. Meat and milk are already getting all the demand they can, which is a fat near-nothing because they have very few uses. They do not make the biogenerator a sufficient source of inter-departmental interaction on their own.

**Comment by icantthinkofanameritenow** [comment]
But why holsters? Why not something more useful to everyone, like blankets or even advanced toolbelts? Surely those would have way more use than the guns most crew members won't even be able to use in normal circumstances.

Plus, you know this is a server that believes "death before departmental interaction". If you want them.to interact, you will have to quite literally force it to happen.

**Pull request merged**
