### PR TITLE
Adds a new splash screen based on the supermatter cascade

### PR DESCRIPTION
**Pull request by DelaminatingShard**
cascadanimated2

:cl:
 * rscadd: Adds a splash screen based on the supermatter cascade

### CODE REVIEW

**Comment by Riekland** [comment]
it looks like utter shit

**Comment by Shadowmech88** [comment]
I think it looks acceptable enough except for the scientist.
The scientist's anatomy is really screwed up.

**Comment by CptWad** [comment]
I get that its a refrence to EVA but probably should not trace over that in mspaint

**Comment by DelaminatingShard** [comment]
Thanks for the feedback. I'm gonna work on a more refined version now, with 99% less paint-tracing

**Comment by DelaminatingShard** [comment]
cascade2animated

How does this look?

**Comment by Exxion** [comment]
*Way* better
Only complaints:
1. The water looks slightly weird, though I can't quite place how. Maybe an artist could.
2. The shadows are mixels, though I'm not sure how you would go about fixing that.
3. The picture of the clown near the bridge was taken in the map editor or something and lacks smoothwindows.

**Comment by DelaminatingShard** [comment]
@Exxion 
1. Do you mean the coastline or the ocean? The coastline icon I flipped upside-down if that's what you mean.
2. Yeah, I can spruce those up, make them more clean.
3. Ya caught me red-handed, but I can change that too.

Give me a little while though, I worked all morning on it.

**Comment by Intigracy** [comment]
It looks much better pixelized.

You probably think the water looks weird because when you look out at the ocean irl you can see the horizon more pronounced, but this is pixels.

**Comment by DelaminatingShard** [comment]
cascade2animated

Okay so I fixed up the shadows, mostly on Coffee and the beachball, and redid the clown scene with smooth windows and Beepsky.
I want to make sure this looks okay before I commit it.

**Comment by ghost** [comment]
Sorry but I absolutely fucking hate seizure-inducing flashing lobby screens. The most annoying thing you could possibly have taking up 75% of your screen for 5 minutes. We don't need another one.

**Comment by Intigracy** [comment]
This is far from seizure inducing.

**Comment by N3X15** [comment]
Epileptic here, this is not seizure inducing for most photoepileptics.

**Comment by DelaminatingShard** [comment]
Well that's good to hear.
Last thing I want is for someone to get a seizure.

So, is this version good enough to commit?

**Comment by N3X15** [comment]
Which one is in the PR right now?

**Comment by DelaminatingShard** [comment]
The one with 9 thumbs up.

**Comment by N3X15** [comment]
The third one has some color weirdness.  Like the sec's shoes shimmer during screen transitions.

**Comment by DelaminatingShard** [comment]
Yeah I may have deep-fried it a bit too much trying to fix the shadows.
The second one doesn't look too bad if you just want to keep that one.

**Pull request merged**
