### PR TITLE
mommi milk

### PR DESCRIPTION
**Pull request by toomykins**
april first is very soon
#28647

:cl:
 * rscadd: added mommi milkies

### CODE REVIEW

**Comment by RaccoonBro** [comment]
slurp

**Comment by jknpj** [comment]
Even if '''funny''', this is still going to make mommis break their laws,

**Review by Kurfursten — CHANGES_REQUESTED** [review]
Add a holiday check if you want this merged

**Comment by toomykins** [comment]
> You know, if you had opened this on April Fools it would have been speedmerged
> Gotta be patient to make meme PRs

-exxion

just revert it on april 2

**Comment by Kurfursten** [comment]
if you code it right we can have automatic mommi milk every year

**Comment by toomykins** [comment]
i'll consider it when i get home i guess, if i can get my VM to work

**Comment by Exxion** [comment]
I said if you had opened it *on* April Fools
Again, you gotta have patience

**Comment by boy2mantwicethefam** [comment]
BIG and JUICY MoMMI milkies

**Comment by toomykins** [comment]
> I said if you had opened it _on_ April Fools
> Again, you gotta have patience

then close this and reopen the other one on april fools

**Comment by Eneocho** [comment]
> 
> 
> Even if '''funny''', this is still going to make mommis break their laws,

It's an instant "milking" so they don't interact. Besides, meme PRs are meme for a reason.

**Comment by calzilla1** [comment]
If added, make it more toxic than cyanide

**Comment by Eneocho** [comment]
> 
> 
> If added, make it more toxic than cyanide

Or make it a gamble. It's either more toxic than cyanide or more powerful than doctor delight, you only know what you get after consuming.

**Comment by Kurfursten** [comment]
It should just be reskinned welding fuel. Milk mommi to refill your welder.

**Comment by toomykins** [comment]
added april fools day check ( i think it werks)
and cuz FUEL is hardcoded most everywhere and you can't have something be a subtype of two things, i decided to just make it milk that's as toxicto drink as fuel.

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
