### PR TITLE
Fix #6868

### LINKED ISSUE #6868: Attention New Command Report Created - FUCKING EAR BLASTING
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision dee5cb7b250b0f88e0fde862b2bb8472d38e485c 
> 
> General description of the issue
> The command report is
> Loud.
> As.
> Your.
> Mum.
> 
> What you expected to happen
> Reasonable volume command report
> 
> What actually happened
> My ears got fucking assblasted
> 
> Steps to reproduce if possible
> START ROUND
> GO DEAF

### PR DESCRIPTION
**Pull request by clusterfack**
Reduces the command report sound to 60% of its current full volume

### CODE REVIEW

**Comment by DrCelt** [comment]
The problem isn't that it's loud, though that's a byproduct of it; I'm almost certain I hear them stacking, as if several command reports were being created

**Comment by clusterfack** [comment]
Except they aren't, you can very clearly see that they aren't

**Comment by DrCelt** [comment]
Hmm, guess my ears were deceiving me then. Wouldn't be the first time.

**Comment by DrCelt** [comment]
```
	for (var/obj/machinery/computer/communications/comm in machines)
		if (!(comm.stat & (BROKEN | NOPOWER)) && comm.prints_intercept)
			var/obj/item/weapon/paper/intercept = new /obj/item/weapon/paper( comm.loc )
			intercept.name = "paper- '[command_name()] Status Summary'"
			intercept.info = intercepttext

			comm.messagetitle.Add("[command_name()] Status Summary")
			comm.messagetext.Add(intercepttext)
		world << sound('sound/AI/commandreport.ogg', volume = 60)

```

**Comment by DrCelt** [comment]
Looks to me like it is indeed actually playing more than once.

**Comment by clusterfack** [comment]
Apparently you never looked before now

**Comment by DrCelt** [comment]
Yeah I'm pretty lazy

**Pull request merged**
