### PR TITLE
Fixes blob spore pathfinding

### PR DESCRIPTION
**Pull request by Exxion**
garmble grumble

Projectiles still work and now aggroed spores don't get stuck.
This comes at the low, low cost of a bit of snowflake code. _Thanks, BYOND!_

### CODE REVIEW

**Comment by ComicIronic** [comment]
Shouldn't you just have given stuff PASS_BLOB

**Comment by clusterfack** [comment]
Byonds pathfinding only checks density

**Comment by Exxion** [comment]
Yeah, blob spores already have `PASS_BLOB`
But `walk_to()` just doesn't give a fuck

**Comment by ComicIronic** [comment]
byond a shit, where's our custom A\* implementation?

**Pull request merged**
