### PR TITLE
Friendly Cultist Cyborgs - Black Market Edition

### PR DESCRIPTION
**Pull request by ghost**
See the old PR, which got reverted because Kurfusten merged before it was ready.
Also, I heard there were some issues with being unable to cast your own drawn runes as a cyborg. On my test server it works perfectly, so let me know if that's still the case.

Current Black Market prices:
	
>stock_min = 1
	stock_max = 3
	cost_min = 400
	cost_max = 500
	display_chance = 95

:cl:
 * rscadd: Friendly Cultist Cyborg board added to the Black Market.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
>SERVICE BORG

BRUH LEAVE IT TO THE TGBORGS GOD DAMN MAN HOW HARD IS IT FUUUUUUUUUUUUUUUUUUCK

**Comment by ghost** [comment]
Why, though? Hugborgs are rare enough, and I think service borgs are quite underused.

**Comment by tuypo1** [comment]
I still say it should go on the hugborgs
If it's on service borgs it will be too common.

**Comment by juanototo2** [comment]
LET IT GO ON SERVICE BORG

**Comment by jknpj** [comment]
Why not both?

**Comment by ghost** [comment]
Their concern seems to be that it would be too common. How about I add it for hugborgs as well and lower the chance of it appearing?

**Comment by Blithering** [comment]
If this passes, I'll get spriting a cult borg. if it fails, I have a sprite for a stupid morale construct that could use the spells

**Comment by bathosbathtime** [comment]
There is absolutely nothing wrong with something being rarely used.
Helps keep it fresh, too.
EDIT2: Oh the rune description still says o+ even though they are o-

**Pull request closed without merging**
