### PR TITLE
Adds skellington petards

### PR DESCRIPTION
**Pull request by unid15**
straight from aoe2

The explosion is identical to the wizard's fireball in size

### CODE REVIEW

**Comment by FudgePucker** [comment]
Do they make a AAAAAAAAAAAAAAAAAAAAAAAAAAAA sound when charging at a target?

**Comment by ScrambledSteak** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Megamaw** [comment]
can you go into a little more detail explaining what's going on here? i'm not smart.

**Comment by Exxion** [comment]
They're suicide skeletons.

**Comment by AutismSpider** [comment]
Suicide bomber skeletons.

if its about the petards small bomb made of a metal or wooden box filled with powder, used to blast down a door or to make a hole in a wall.

**Comment by ghost** [comment]
Quick question, would a monkey mob come under humanoid, and can you use landmark corpse to spawn monkey corpses equipped with things?

**Comment by unid15** [comment]
@Skullyton in their current state the corpse landmarks can only spawn humans, but changing them to spawn monkeys wouldn't be too hard, I guess

**Comment by Durgen** [comment]
Make sure to fill the examine description with AOE2 references

**Comment by ihadtoregisterforthis** [comment]
They seem very weak and slow to be suicide units

**Comment by ghost** [comment]
I wonder how well they'll chain-reaction

**Comment by clusterfack** [comment]
Much simpler code than I was expecting to find good job

**Pull request merged**
