### PR TITLE
Lightspeedship.dmm vault fix

### LINKED ISSUE #13318: The three borgs on the Kestrel Vault show up on the cyborg control console
They're also for some reason live borgs in standby.
I think it would be better if they were just borg shells maybe, but eh.

### PR DESCRIPTION
**Pull request by Probe1**
Replaces /mob/living/silicon/robot with /robot_parts

Adds a dead engineer for an engineering ID to access other parts of the vault based on player feedback.

image

Closes https://github.com/d3athrow/vgstation13/issues/13318

### CODE REVIEW

**Comment by ComicIronic** [comment]
I think it should really be a fully assembled shell.

**Comment by Probe1** [comment]
I did that and it resulted in the issue reported.

**Comment by ComicIronic** [comment]
`/mob/living/silicon/robot` is the mob, I meant the shell which is fully assembled i.e. as if you'd done all the steps short of slapping a brain in it.

**Comment by Probe1** [comment]
The mapping sprite sent me totally off course and made me stupid.  Thank you @ComicIronic you are the best.

**Comment by JustSumBody** [comment]
Those posibrains will show up on the CMC
Can roundstart telesci to the shuttle with that

**Comment by Intigracy** [comment]
Posibrains that haven't been activated show up on the CMC?

**Comment by JustSumBody** [comment]
Yes, robotics posibrain always shows up on the CMC

**Comment by Probe1** [comment]
First/old image shouldn't even be there my bad.  There are no posi brains.

**Pull request merged**
