### PR TITLE
Change the lighting value of tungsten (incandescent) light bulbs

### PR DESCRIPTION
**Pull request by ghost**
Or how my recent work in the Source Hammer Map Editor has given me some ideas on how our lights should be set
- Small light bulbs are now considered tungsten lights. The light is a lot sharper, warmer (orange-ish) but still diluted enough to not look like it is fluorescent
- A few items should be using that new light value, notably the mining lantern, candles and cigarette-related items

In-game example : 

scrnshot1

### CODE REVIEW

**Comment by ComicIronic** [comment]
Need some images

**Comment by 9600bauds** [comment]
Definitely
If it makes everything look piss orange this is a big :-1: from me, lighting bulbs are already bad enough in this regard.

**Comment by AutismSpider** [comment]
make it so you can put dye in the lights or some shit not piss orange

**Comment by Exxion** [comment]
image

**Comment by dylanstrategie** [comment]
Here's an example of what it looks like in-game. By orange-ish, I do mean orange-ish. It also looks very visibly warmer than the current light-bulb tone without being obscenely bright or saturated

scrnshot1

**Comment by Exxion** [comment]
That actually looks even less bad than just the color out of context

**Comment by Kurfursten** [comment]
Should not recolor high efficiency bulbs, as they are fluorescent, not incandescent

**Comment by FudgePucker** [comment]
I like it now after seeing an image.

**Comment by Exxion** [comment]
HE bulbs don't inherit the color of other bulbs. They are explicitly defined as white.

**Comment by 9600bauds** [comment]
Looks much better

**Comment by Probe1** [comment]
It looks nice.

>EDIT: Actually, this PR doesn't seem to change the color of bulbs at all. Only roundstart fixtures.

Make it consistent and it's a solid change.

**Comment by dylanstrategie** [comment]
I don't see where it is inconsistent ?

**Comment by Exxion** [comment]
You changed the color of bulb *sockets*, but not the bulbs themselves, so only bulbs installed at roundstart will get the new color.
The bulbs didn't use LIGHT_COLOR_BULB for some reason. Same color, but without the define.

**Comment by dylanstrategie** [comment]
Shitnipples

**Pull request closed without merging**
