### PR TITLE
Basado en que?

### PR DESCRIPTION
**Pull request by F-OS**
https://www.youtube.com/watch?v=mp8nG6iWrnw
Zero percent tested
:cl:
 * rscadd: What the hell is based?

### CODE REVIEW

**Comment by SonixApache** [comment]
i'd say speedmerge but there are legit sentences that include this word 
make it fire when it's only the word

**Comment by ghost** [comment]
make saying "keyed" do twice the amount of brain damage and twice as often
image

**Comment by PrimeDSS13** [comment]
I'd drop the check down to 6-8 characters.
also make it happen like 40% of the time

**Comment by Eneocho** [comment]
Imagine explaining someone how is some in game mechanic based upon another and you get slapped with the brain damage.
`Engi McNewplayer asks: How does the TEG work?`
`Clowngineer says: Ah, it's a heat-differential based engine. Hotter is more power` 
`You suddenly feel dumber.`
Thank you coders very cool!

**Comment by Eneocho** [comment]
Also, this won't stop basedposting at all, you can just say any derivative of the word. It's not a thing to "remove" via coding.

**Comment by SonixApache** [comment]
`Clown: "Based!"`
`Non-clown: "Based?"`
`Non-clown: "Based on what?"`
In retrospect, maybe just don't, even though it's funny.

**Comment by ValkyrieSkies** [comment]
This joke was funny for one day.

**Comment by ShiftyRail** [comment]
@Eneocho Only sentences with less than 14 characters will trigger it.

**Comment by Dacendeth** [comment]
14 characters is too high.

**Comment by ShiftyRail** [comment]
Agreed.

**Comment by Exxion** [comment]
It's technically 14 bytes, not 14 letters, but not very many multi-byte characters are allowed in chat anyway so it doesn't make much difference. However, if you *could* say it, "ｂａｓｅｄ" is 15 bytes.
Also you can get by any limit by just adding punctuation until you hit it

**Comment by smalIboss** [comment]
how silly

**Comment by ghost** [comment]
I'd make it match exactly for case insensitive "Based", as well as strings ending in "based" since I can't think of any legitimate sentences that would end that way.

**Comment by Eneocho** [comment]
> 
> 
> I'd make it match exactly for case insensitive "Based", as well as strings ending in "based" since I can't think of any legitimate sentences that would end that way.

`The shard engine is radiation based` As in dependent on.
`Paladin, as a lawset, is spesslaw based` Ditto. 
`That's where the chemist is based.` As in residence.
Many such cases.

Also, you can always just add a word after "based" and it would be fine, since it would not end on "based", hell even a single character would do.
This is a pointless change, since if people wanna basedpost, they're gonna find a way to basedpost, you can't predict every single instance of basedposting. Hell, 4chan has that soy -> onions regex but people still find ways to soypost.

**Comment by F-OS** [comment]
> 
> 
> > I'd make it match exactly for case insensitive "Based", as well as strings ending in "based" since I can't think of any legitimate sentences that would end that way.
> 
> `The shard engine is radiation based` As in dependent on. `Paladin, as a lawset, is spesslaw based` Ditto. `That's where the chemist is based.` As in residence. Many such cases.
> 
> Also, you can always just add a word after "based" and it would be fine, since it would not end on "based", hell even a single character would do. This is a pointless change, since if people wanna basedpost, they're gonna find a way to basedpost, you can't predict every single instance of basedposting. Hell, 4chan has that soy -> onions regex but people still find ways to soypost.

I understand that. The goal of this PR isn't to stop people from basedposting, it's just to add some consequences to doing it with no effort and meme on the memelords a bit.

**Comment by Eneocho** [comment]
You overestimate the amount of memelords. There's maybe 5 or 6 players that occasionally say based, generally as an answer to an open ended question someone else did.
`Captain, the janitor killed the lube clown, what should we do?`
`Based.`
`Let him go.`

I get it if people constantly basedposted all the time always, but we rarely see based being used consistently in game. This also kills very fun gimmicks we've had previously, like that one clown named "Clown that kills people who say based". Captain said based in response to his name and was promptly chased and killed by the clown. The captain knew the consequences and chose to say it anyway, because it'd be fun. Braindamage and barely being able to play is not fun. 

 Braindamage is NOT the way to go. This should not be policed.

**Comment by SootyBear42** [comment]
> Braindamage is NOT the way to go. This should not be policed.
Yeah if people just constantly spout memes they usually aren't looked at too fondly.

**Comment by F-OS** [comment]
Ladies and gents, I have heard your feedback:

- The probability is now lower.
- No more brain damage.
- It only fires if you're just saying 'based.'

**Comment by ValkyrieSkies** [comment]
Good changes, good response to feedback.

Still a bad PR.

**Comment by F-OS** [comment]
Not enough support

https://user-images.githubusercontent.com/10489825/142288886-338195fe-3bb7-420d-96b6-ecbf468d7630.mp4

**Comment by Eneocho** [comment]
You could try again but with only the "you think to yourself: Based on what?" part. That'd probably get some support, but people don't want their basedposting removed.

**Pull request closed without merging**
