### PR TITLE
Bagelstation: nuclear edition

### PR DESCRIPTION
**Pull request by DamianX**
rust_bagel

This is more an experiment than anything else. I don't know if this setup will make it too easy to get gigawatts or too hard for newfriends to do anything at all, or even if the thumbs down tribe will not tolerate having to assemble the particle accelerator before singuloosing to end the round. 

Features a TEG, tokamak, and all the consoles and machines. It requires an amount of effort comparable to setting up the old singularity, if not less.
It's still a bagel, too!

:cl:
 * tweak: Bagelstation: replaced the singularity engine with the R-UST.

### CODE REVIEW

**Comment by beesil** [comment]
it's beautiful

**Comment by SonixApache** [comment]
i wanted to do this except with a map-specific unique engine, but this is the better option

**Comment by Gazathor** [comment]
IM NUCLEARRRRR

**Comment by anunknownentity03** [comment]
3.6 roentgens, not great not terrible

**Comment by DrSnips** [comment]
Is there any matter carts for the fuel rods?

**Comment by DamianX** [comment]
CE office has some as usual

**Comment by DrSnips** [comment]
Ok and while I understand that hacking into the CE office round start is more common that breathing I do think there should be A (one) matter cart out there if it's going to be THE engine.

**Comment by ShiftyRail** [comment]
📞 merge it

**Comment by DamianX** [comment]
We can talk about not requiring hacking into the CE office once the button to open secure storage is no longer in there

**Comment by PJB3005** [comment]
That setup is pretty broken, isn't it?

The volume pump you have cannot hope to do shit because the R-UST will instantly get the hot loop up to ridiculous pressure levels. At that point the only thing providing the necessary pressure difference to get circulation is the continuous pressure increase from the intake side heating up continuously, which will eventually slow down and stop, completely jamming your TEG when it does (though realistically that might not happen in a real round due to how long it takes?)

**Comment by DamianX** [comment]
The pumps do stall, but they should work for a little bit. It's not supposed to be a perfect setup, I'll see how it ends up working.

**Pull request merged**
