### PR TITLE
Ointment, Plastic Solidification, Recycled nutrition cube fixed to work with plantchems

### PR DESCRIPTION
**Pull request by ghost**
Plantchems didn't work in the recipes. They work now.

plant derma works now

phenol plasticide works now

reclaimed works

[bugfix]

:cl:
 * bugfix: Plastic Solidification, Ointment, and Recycled Nutrition Cube recipe's work with their plant chems.

### CODE REVIEW

**Comment by SonixApache** [comment]
[update wiki] ?

**Comment by ghost** [comment]
Waiting for merge in case it sits a while.

**Comment by ghost** [comment]
Would be nice if this was actually done when plantchems were made. We could completely fix this by just removing them because they are borderline useless anyway. Whatever the original idea for them was has never been realised and left in an unfinished mess for over a year.

**Comment by ghost** [comment]
Eh, while borderline irrelevant and never ever happens, chem stacking's a neat option if you're actually packing armor. Makes fighting simple mobs in subpar armor and buckler more bearable too not that you shouldn't go about it in a way that isn't pigheadedly stubborn.

Even if you don't want to stack, it's slowly getting more plant-chem specific recipes to combat the chem disp meta as time goes on. It'll get there if we have a little faith.

Edit: Yep, stacking and botany specific reagents and recipes was the idea.

**Comment by ghost** [comment]
Wiki's updated.

**Pull request merged**
