### PR TITLE
Box Bridge Expansion 

### PR DESCRIPTION
**Pull request by BurntDevil**
<a href="https://imgur.com/Ska28ec"></a>
This should bring Box's bridge up to a useful level, like the deff expansion. This should encourage command to make more use of the bridge instead of abandoning it until the shuttle is called. The footprint increase is barely larger than before but it gives alot more space to work with.

:cl:
 * tweak: Expanded Box bridge for additional equipment to make the bridge more useful in general.

### CODE REVIEW

**Comment by cadaverouscoyote** [comment]
am i not seeing this right or can it be broken straight into from the hallway?

**Comment by Accipitermaris** [comment]
good observation; north windows on current box bridge are entirely protected by rtables & consoles but this one has potted plant and kicktable dangerzones

**Comment by BurntDevil** [comment]
I could shore that window back up but at the same time I lean toward that if the bridge has more ability it should also have more risk.

**Comment by cadaverouscoyote** [comment]
i can imagine people breaking in for the multitool every other round and grabbing the flash on their way out. also those stairs don't make sense spatially

frankly it doesn't seem like a whole lot of thought was put into this

**Comment by BurntDevil** [comment]
People can do that as is though, if youre going to break into the bridge, pushing say, the current bridge's sec cams out of a way isnt much of a deterrent. Its possible, yes, but it isnt really seen that often. You still have the shocked grille and the most patrolled area of the station to do it in. I dont think its an issue personally.
The stairs are just an attempt at creating visual height, as if the bridge sat overlooking the main hall. Its not an easy effect to portray with the sprites we use but I dont personally find it jarring.
And as for thinking it out, Ive been filtering this through the thread and through private playtests with people for atleast a month, Ive thought about this or I wouldnt have submitted it.

**Comment by cadaverouscoyote** [comment]
moving a console requires the third rarest tool on the station, albeit still a common one. to break into this one all you'd need is a fire extinguisher off the nearest wall. the difference might be a minor thing from a technical perspective but in-game it's just much lower-hanging fruit. the difference isn't how a player's gonna get at it but how a player's gonna look at it, especially considering how empty even the most patrolled area of the station can be on middlin' pop.

and the height effect doesn't work without anything between the bridge and the hall. you'd need like a moat of space. stairs are usually only convincing on the very extremities of a station, like metaclub's escape.

**Comment by ShiftyRail** [comment]
Just replace the potted plants by reinforced tables, or wall up the parts there aren't covered by consoles or tables.
Other than that, it's a pretty good rework. I'm a bit skeptical or the stairs. I'd had a few more chairs in front of the consoles, I can't imagine the helmsmen manning them all day all night without sitting.

**Comment by BurntDevil** [comment]
Eh, I wanted some vulnerability but I went ahead and shitcanned the flower pots and readded rtables. I also knocked the stairs out, Ill experiment with visual depth another day.
    
-edit: save the file exactly the same way as the first time, get +15,644 −15,636. How annoying.

**Comment by BurntDevil** [comment]
Fuck it Im just going to hit this again when I figure out why my git is being bullshit.

**Comment by SonixApache** [comment]
don't forget to run mapcleaner...

**Pull request closed without merging**
