### PR TITLE
Powered Cargo Carts

### PR DESCRIPTION
**Pull request by gurfan**
Created to address #26735 and #26696

Cargo carts being able to move anchored machines with no cost was broken, albeit fun for many. This PR brings it back but with a few changes.

- Each individual cargo cart now has a slot for a power cell. The cell can be inserted/removed the usual way (screwdriver open, put in cell, or pry out cell with crowbar).
- If there is a power cell inserted into the cargo cart, the machine will be able to function while loaded on top of it. Power will be drawn from the power cell instead of the APC. If the power cell runs out of charge, the machine will shut down. If the machine does not require power then it will work regardless of whether or not the cart has a cell.
- Cargo carts now have a blacklist of certain machines that won't function on top of cargo carts, even with a cell. The only thing on this list currently is the atmospherics miners.

This PR also adds connected_cell and battery_dependent variables to the obj/machinery parent, in case battery-powered machines become a thing later on.

Anchored objects can't be loaded onto carts, you need to un-anchor it before loading it onto the cart.

:cl:
 * rscadd: Machines will now function on top of cargo-carts again, so long as the cart has a power cell installed.

### CODE REVIEW

**Comment by gurfan** [comment]
oops

**Comment by PrimeDSS13** [comment]
very nice very very nice very very nice nice nice very nice

**Comment by GreatBigFailure** [comment]
I like that this is also a buff to batteries. Those don't get enough attention as a resource.

**Comment by tuypo1** [comment]
What about mules? might give them some actual reason to exist

**Pull request merged**
