### PR TITLE
Macuahuitl

### PR DESCRIPTION
**Pull request by Shadowmech88**
macuahuitl
Adds the macuahuitl, a makeshift melee weapon which can be crafted from a wooden plank and glass shards.

The macahuitl can be loaded with glass shards, its damage scaling with the number of shards it holds, up to 20 force at 10 shards.
Each hit, every one of the macahuitl's blades has a 15% chance to break. If the blade is a plasma glass shard, that chance is lowered to 10%.

The blades are added to the icon via code, which means that both the shards' shape and color is preserved and visible when it is placed into the macuahuitl.

:cl:
 * rscadd: Added the macuahuitl, a new makeshift melee weapon which can be crafted from a wooden plank and glass shards.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This has a curious behavior: when you add the first shard to the wooden plank its force doesn't change, but the rest add 2 force each.  (e.g.: 0 = 2, 1 = 2, 2 = 4, so on)

**Comment by Shadowmech88** [comment]
The first shard causes it to become sharp.
With no shards at all, it's a two force blunt weapon.

I could make 10 shards sum to 22 force, but I felt like 20 force was a nice even number for the full weapon to have.

**Comment by Lokiamis** [comment]
If I'm remembering my numbers correctly, this is a weaker, flimsier, more labor intensive version of the spear, even when one handed. Does it do anything extra when shards break?

**Comment by Shadowmech88** [comment]
The spear has 10 force, 18 if you two-hand it. It's also substantially less sharp than the macuahuitl.

**Comment by Lokiamis** [comment]
I was thinking 18 one handed for some reason

**Comment by Blithering** [comment]
Teeth and xeno claw versions when?

**Comment by 9600bauds** [comment]
20 force one-handed is pretty good, and this doesn't need any rare materials, just 10 sheets of glass. Plus the shard breaking chance seems really easily manageable.
I'm not saying it should be nerfed right now but if it becomes the meta, we'll see how it goes I guess. Maybe do what spears do and have the force bonus depend on the quality of the shard, so you can get your 20 force onehand if you find plasma glass.

**Comment by yclatious** [comment]
Could we have it so the aquarium pr shark teeth could be compatible in the future?

**Comment by SonixApache** [comment]
[needs wiki]

**Pull request merged**
