### PR TITLE
Nuke Ops Requesting Reinforcements

### PR DESCRIPTION
**Pull request by DorainGrey**
## What this does
- Allows Nuke Op leader to request reinforcements, doing alter the station through the leaky transmission on the radio.
- After the reinforcement request is intercepted moving shuttle & Teleporter are disabled for 10 minutes. (Reinforcments cannot be requested  if they were used beforehand)
- Their syndicate benefactors will grant them 200 tc as a reward,
- Emergency shuttle calling/recalling will also be blocked for these 10 minutes.
I have tested this fairly thoroughly on local and think I have caught most of the edge cases but I'd appreciate any extra testing if people want to try it out.

## Why it's good
I feel rush ops, can often be quite boring for most people outside Sec. They usually end quickly either with a fluke or complete nukie victory before most people are even aware or ready to engage.
The idea of declaring war, is that it will allow players to arm up and get more involved and provide nukies with the TC to try a lot of equipment that rarely gets used. (Gattling gun anyone?)

## Changelog
:cl:
 * rscadd: Adds a radio for Nukies, where they can request reinforcement and get extra TC in exchange for waiting 10 minutes during the ensuing bluespace distortion.

### CODE REVIEW

**Comment by ErrorsWindows** [comment]
aren't you afraid that the crew will be able to quickly call the shuttle and bounce in 10 minutes
also https://github.com/tgstation/tgstation/pull/13640

**Comment by DorainGrey** [comment]
> aren't you afraid that the crew will be able to quickly call the shuttle and bounce in 10 minutes also [tgstation/tgstation#13640](https://github.com/tgstation/tgstation/pull/13640)

They are blocked from doing so.
In the situation, the shuttle is called already however it will continue arriving I think but yet to test that.

**Comment by gurfan** [comment]
>60 extra TC per a nuclear operative, on top of the base 80TC.

This seems like a ridiculous amount.

>I feel rush ops, can often be quite boring for most people outside Sec. They usually end quickly either with a fluke or complete nukie victory before most people are even aware or ready to engage.

This PR doesn't do anything to address that, though?

>lot of equipment that rarely gets used. (Gattling gun anyone?)

That's because it sucks. Like, really fucking sucks.

**Comment by Theophrastus1** [comment]
This sounds like it will never work unless it's designed to be forced to work

**Comment by DorainGrey** [comment]
> > 60 extra TC per a nuclear operative, on top of the base 80TC.
> 
> This seems like a ridiculous amount.

I really don't think so, 10 minutes is a huge amount of time for crew to prep. They can easily order Ions, fortify arm most of the crew. I think it's a fair balance of risk vs reward. I'm open to different values however.

> > I feel rush ops, can often be quite boring for most people outside Sec. They usually end quickly either with a fluke or complete nukie victory before most people are even aware or ready to engage.
> 
> This PR doesn't do anything to address that, though?

What do you mean, if there's 10 minutes for people to prepare, you can do all sorts of crazy strats as Nukies & Crew.
This doesn't force the nukies to take this route but it means when they do, it's a bit more involved than 2-3 sec officers vs rushing nukies.
> > lot of equipment that rarely gets used. (Gattling gun anyone?)
> 
> That's because it sucks. Like, really fucking sucks.

I know it's just an example of something you can meme with when having Extra TC.

**Comment by DorainGrey** [comment]
> This sounds like it will never work unless it's designed to be forced to work

What do you mean?
The code works, I assume you are referring to something else?

**Comment by gurfan** [comment]
> I really don't think so, 10 minutes is a huge amount of time for crew to prep. They can easily order Ions, fortify arm most of the crew. I think it's a fair balance of risk vs reward. I'm open to different values however.

I might be overestimating it. Time will tell, I suppose.

> What do you mean, if there's 10 minutes for people to prepare, you can do all sorts of crazy strats as Nukies & Crew. This doesn't force the nukies to take this route but it means when they do, it's a bit more involved than 2-3 sec officers vs rushing nukies.

I mean there's nothing in this PR preventing operatives from doing their usual silent rush strategy.

**Comment by DorainGrey** [comment]
> I might be overestimating it. Time will tell, I suppose.

Yeah it's hard to say, it's definitely something that may need to be balanced down, 10 minutes may be too long and equally 60 tc may be too much. The TTV's worry me a bit tbh, possible they'd need to be capped at 3 or something however I'd prefer to balance down than up.

> I mean there's nothing in this PR preventing operatives from doing their usual silent rush strategy.

Yeah, they don't have to use the item. If the team wants to stealth ops or silent rush, that's a valid if boring strategy. 
I'm just trying to give an incentive for more interesting strats, even if that is the station vs 3 mechs or mass viscerator grenades, nikita &  hectate etc
There's probably room for more exotic meme weapons that are currently unavailable in the Nukies Section of uplink too as well.

**Comment by gurfan** [comment]
> Yeah it's hard to say, it's definitely something that may need to be balanced down, 10 minutes may be too long and equally 60 tc may be too much. The TTV's worry me a bit tbh, possible they'd need to be capped at 3 or something however I'd prefer to balance down than up.

A nuke squad of three members can purchase *10* maxcap bombs. Four member squads can buy *12*, and five member squads can buy a whopping *15* maxcaps. Spend two of these bombs buying the teleporter board (or even just get it for free with the ship+cameras loadout) and you can remotely destroy the station without even leaving your ship. Who needs nukes?

**Comment by DorainGrey** [comment]
> A nuke squad of three members can purchase _10_ maxcap bombs. Four member squads can buy _12_, and five member squads can buy a whopping _15_ maxcaps. Spend two of these bombs buying the teleporter board (or even just get it for free with the ship+cameras loadout) and you can remotely destroy the station without even leaving your ship. Who needs nukes?

That's fair, I think the solution is a limit to bombs though something like 3. Even if we reduced it to 20tc which would not be worth it for nukies they could still buy 6 bombs.
I'll look into doing this now.

Edit Old Coders are smart, they already implemented a limit all I need to set is one variable.

**Comment by BomberBro** [comment]
""A syndicate fringe group has declared their intent to utterly destroy [station_name()] with a nuclear device, and dares the crew to try and stop them.""

This shit doesn't really make any sense from a lore perspective. The syndicate wants to blow up the station so warns the crew beforehand and.... rewards the ops for doing this?

To differentiate it from tg and make a little more sense, what if instead the OP leader had a "Request Reinforcement" button (with a big red warning saying the line is not secure and neighboring stations will hear) which then gets intercepted and sends a big message to the main station. You'd get the same effect but the """""lore""""" would make more sense.

**Comment by ErrorsWindows** [comment]
> This shit doesn't really make any sense from a lore perspective. The syndicate wants to blow up the station so warns the crew beforehand and.... rewards the ops for doing this?

bro this is a video game, it's funny to telegraph your intentions to the other side, just roll with it for a testmerge

Screenshot (2044)

**Comment by gurfan** [comment]
> > This shit doesn't really make any sense from a lore perspective. The syndicate wants to blow up the station so warns the crew beforehand and.... rewards the ops for doing this?
> 
> bro this is a video game, it's funny to telegraph your intentions to the other side, just roll with it for a testmerge

kindly fuck off

**Comment by SonixApache** [comment]
nothing like a 3 marauder ultradeathsquad to really liven up the rounds

**Comment by pedr69** [comment]
complaining about the maxcap teleporters is dumb
if the crew had 10 minutes to prepare and they didn't deconstruct the telebeacons they fuckin deserve a maxcap in the bridge

**Comment by ErrorsWindows** [comment]
it's the risky game changing pull requests that really bring out the best in people

**Comment by Eneocho** [comment]
>This shit doesn't really make any sense from a lore perspective. The syndicate wants to blow up the station so warns the crew beforehand and.... rewards the ops for doing this?

What if the Ops had a Reinforcements Supply Beacon that when enabled sends an automated request for extra resources? NT could then send a warning to the station like so: 
"We have detected a rogue beacon frequency nearby that we believe is linked to the 'Nuclear Operatives' division of the Syndicate. Bluespace jammer deployed, we expect it to stall the operatives for about 10 minutes, so prepare well, crew. As a side effect of the jamming process, emergency shuttles cannot be called nor recalled during its function."

**Comment by ErrorsWindows** [comment]
yea that would make sense, jammers work both ways, it's like the anti IED jammers in Iraq, your head needs to be on a swivel when you turn the jammer off to make a radio call to make sure nobody with a cell phone has any funny ideas

> A nuke squad of three members can purchase 10 maxcap bombs. Four member squads can buy 12, and five member squads can buy a whopping 15 maxcaps.

I'm reminded of that one beestation round where the clown ops declared war so we did everything, cargo got surplus crates and shotguns, weapons were distributed, I RCD'd the hallways (any red shirt who has accrued a particular ire knows how frustrating a walled-up hallway is), etc.

on tg and bee I think it's just hard coded that you can't call the shuttle in the first 20 minutes no matter what, but anyways, that's when the clown oops decided to get nothing but _twenty-three maxcap bombs_, they didn't even need emags after that because there weren't even any doors to hack, the entire station was swiss cheesed, the station was the holes and the space was the cheese, although they didn't even get the disk because after the third explosion the captain got wise and ran out to the solars and then we won the round anyways when the shuttle came

oh yea and that's not even considering the bundle that you can get for 14 that has two maxcap bombs except they made all the fun bundles rarer for some dumb shit reason so now I never see anybody getting them anymore

**Comment by pedr69** [comment]
what if the nukeops could hit the button anytime before the comms consoles printed the intercept
and if they did, the paper said something about nucular signals, instead of the worthless stuff it usually does
then idunno, 10 minutes later the nukies got more teleshekels/ghost spawns
would sorta encourage speedrun+reinforcement, for the free crystals/respawns - maybe automatically call code red once the reinforcements actually arrive?

always bothered me how the communications intercept is worthless, except when it says blackorbit or impending doom

**Comment by ghost** [comment]
How about a new antag type that's intended to be (and balanced around) an announced raid on the station instead of giving nukies more ways to fuck up if a newbie is selected as leader? Or making revops more common as rounds go on?

When I added the ability for ops to announce themselves I purposefully never revisited the idea to add an incentive because the incentive is the satisfaction you get if you manage to forego stealth and flex on the station. Also this PR is unatomic as HECK, don't pair minor tweaks with an addition that completely changes a ruleset.

**Comment by adacovsk** [comment]
Emergency shuttle not able to be called is reward enough. I always like going loud, but the problem is that you often trigger an immediate shuttle call and have to rush to do things, often making fluking in the process. I like the declaration and the delayed emergency shuttle. Just leave it at that

**Comment by Eneocho** [comment]
Unironically yeah, that would work. Could be displayed to the station as "We have received a formal declaration of war against your station by the 'Nuclear Operatives' division of the Syndicate and detected signals of shuttle jamming near your quadrant. Cargo shuttles are reinforced against jamming and are NOT affected by this, emergency shuttles, however, will be unable to be called and any incoming one will return to central command."

**Comment by adacovsk** [comment]
> Unironically yeah, that would work. Could be displayed to the station as "We have received a formal declaration of war against your station by the 'Nuclear Operatives' 

I'd avoid the whole formal declaration part, and just say "BLUE SPACE CONNEXTION has been lost. An EMP has been pinpointed from hostile territory". That's enough information. Also, all the code already exists for that. just append a message saying the latter part. Don't reinvent the wheel, @DorainGrey

**Comment by Eneocho** [comment]
Ye that works too, I was thinking it more like formal "HEY FUCKERS WE NUKING YOUR ASS" instead of "OH GOD OH FUCK WE ARE ALL GOING TO DIE THEY ARE COMING".

**Comment by agentofzog2** [comment]
Make a  button that crashes the shuttle into the middle of the station like in that one bus whatshisname likes to do/Colonial Marines

**Comment by DorainGrey** [comment]
> > Unironically yeah, that would work. Could be displayed to the station as "We have received a formal declaration of war against your station by the 'Nuclear Operatives'
> 
> I'd avoid the whole formal declaration part, and just say "BLUE SPACE CONNEXTION has been lost. An EMP has been pinpointed from hostile territory". That's enough information. Also, all the code already exists for that. just append a message saying the latter part. Don't reinvent the wheel, @DorainGrey

That's fair, I'm going to do this now while adding the limit to 3 ttvs.


> How about a new antag type that's intended to be (and balanced around) an announced raid on the station instead of giving nukies more ways to fuck up if a newbie is selected as leader? Or making revops more common as rounds go on?
> 
> When I added the ability for ops to announce themselves I purposefully never revisited the idea to add an incentive because the incentive is the satisfaction you get if you manage to forego stealth and flex on the station. Also this PR is unatomic as HECK, don't pair minor tweaks with an addition that completely changes a ruleset.

What the hell is revops?
I really don't think a new antag is fit for this, we have enough similar antags. It's designed to give nukies more options, than just stealth or rush. I really don't think adding buckshot is massively unatomic but I'll happily remove it, if people really concerned?
As for the newbie thing, the leader is the leader it's their decision. The thing gives plenty of warnings and opportunities to backout, if you are really concerned about it, then we should address the root issue of newbies being selected as leaders and make it a toggle itself or account aged based.

**Comment by DorainGrey** [comment]
Okay updated PR a bit and did a full re-test should be ready for merge. I'm pretty certain I covered every edge-case.
Following changes were implemented

Removed Buckshot as @ancientpower requested

Matched Lore to @BomberBro suggestion as it was better, there is now no custom declaration. They can just buy a megaphone with the TC anyway

Implemented cap of 3 TTV's

Used the normal bluespace distortion messages as requested by @adacovsk

**Comment by DorainGrey** [comment]
@Kurfursten Merge for primetime perhaps?

**Comment by ShiftyRail** [comment]
Over my dead body will the ops be able to do something as silly as "declare war". We are not TG.
The new description makes it slightly less dumb but I don't feel this is a good gameplay addition to nuke ops at all.

**Comment by DorainGrey** [comment]
> Over my dead body will the ops be able to do something as silly as "declare war". We are not TG. The new description makes it slightly less dumb but I don't feel this is a good gameplay addition to nuke ops at all.

Why though?
Nukies is a fun gamemode sure but only for Sec & bits of commands. To the average spessman it passes without them getting involved at all or having any interaction. Just an early shuttle call, this tries to address that by giving the crew a chance to fight and build autism forts etc.

**Comment by DorainGrey** [comment]
TC is now reduced to 200 TC total
@gurfan

**Comment by ShiftyRail** [comment]
Whilst I don't like it, it has support and we allow test merges now anyway. We'll evaluate this in a few days.

**Pull request merged**
