### PR TITLE
Updates fancy containers' icons after mice eat out of them

### LINKED ISSUE #16746: Mice eating out of donut boxes don't update the donuts on the box's icon
#### Steps to reproduce 
Be a mouse, mousedrag a nearby donut box onto you, eat some donuts, observe the phantom donuts on the box's icon.

#### Length of time in which bug has been known to occur
Not new at all, just happen to be reporting it now.

#### Likely related issue
https://github.com/vgstation-coders/vgstation13/issues/13752

#### Server revision
Game: e6a24663932a4a0fb9a573c6ea7e239ea34677d1 
Patches: 9e34bcea4d28270b966365362177f6890fc3ca45 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Pathid**
Closes #16746

### CODE REVIEW

**Comment by unid15** [comment]
Make /obj/item/weapon/storage/fancy/Exited() call update_icon() instead, this is dangerously hacky and non-oop

**Comment by Pathid** [comment]
@unid15 `Exited()` doesn't seem to work for this, unless I'm missing something.

**Comment by Pathid** [comment]
@unid15 How about
```
else if(istype(loc, /obj/item/weapon/storage))
    loc:remove_from_storage(src)
```
Still hacky?
```
else if(istype(loc, /obj/item/weapon/storage))
    var/obj/item/weapon/storage/container = loc    
    container.remove_from_storage(src)
```
This safer for some reason?

**Comment by Pathid** [comment]
`remove_from_storage()` is much better actually, since it reshuffles the UI donuts properly too.

**Pull request merged**
