### PR TITLE
port virgo ribbon sprite

### LINKED ISSUE #21536: Red Ribbons (as seen on stacks of paper) can be worn but have no sprites
#### Description of issue

The ribbon goes on your head but there's no sprite for it which is a shame and a waste.

#### Specific information for locating
`/obj/item/weapon/ribbon`

#### Server revision
9547c64b102a4f2bd208c9a7108ed2117e0d386c

[needspritework]

### PR DESCRIPTION
**Pull request by SonixApache**
adds a sprite to the ribbon we have in our code, closes #21536
sprite lifted from https://github.com/VOREStation/VOREStation/commit/1e3017365d61a1f319b4187997b140919e37df54 and adjusted to match color
porting under https://creativecommons.org/licenses/by-sa/3.0/
image

### CODE REVIEW

**Comment by yclatious** [comment]
Arie into vore confirmed, waifufags(male) btfo.

**Comment by DamianX** [comment]
image

**Comment by SonixApache** [comment]
@DamianX

**Comment by ShiftyRail** [comment]
Is it covered by helmets ?

**Comment by SonixApache** [comment]
it's a head slot item, so no

**Review by Kurfursten — CHANGES_REQUESTED** [review]
I don't see code for an item at all, or a way to get that item.

**Comment by Exxion** [comment]
The object already exists and is obtainable, but has no `item_state` as far as I can see

**Comment by Kurfursten** [comment]
So we just had a clothing item that was totally invisible but WITH a var pointing to an item state that didn't exist?

**Comment by Exxion** [comment]
No because it has no `item_state` var
I'm guessing that change got lost to Git when Sonix was trying to get the PR to work, since judging by the screenshot he had it working at one point

**Comment by SonixApache** [comment]
the item is defined at 
https://github.com/vgstation-coders/vgstation13/blob/d9e848094b6925abf2f76e05e25d483a69edf908/code/modules/paperwork/paper_pack.dm#L88-L98

believe it or not, an `item_state` isn't requires for this to work - i switched branches, changed the icon name that got fucked up during the merge commit back to `ribbon`, and this is what i got
image

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
