### PR TITLE
Buildable full-tile firedoors

### PR DESCRIPTION
**Pull request by DeityLink**
image

:cl:
* rscadd: Firedoor Frames now offer you to either build a directional firedoor, or a full-tile one.

### CODE REVIEW

**Comment by CrazyAmphibian** [comment]
/vg/ is SAVED

**Comment by kilozombie** [comment]
image
THE BOYS ARE BACK IN TOWN

**Comment by ErrorsWindows** [comment]
AINT NOBODY GETTIN THRU HERE
DOING GREAT GUYS KEEP IT UP!
WE'RE MAKING THE STATION A SAFER PLACE!
IM KEEPIN TWO PEOPLE SAFE IN HERE!
NOBODY PANIC WE GOT THIS
SURGEON AND PATIENT CONFIRMED SAFE
THEY STOPPED MOVING
THATS HOW YOU KNOW THEYRE SAFE!
HERE COME SOME MORE
QUICK TURN ON YOUR LIGHTS LOL!

**Comment by Inorien** [comment]
thats right windowserrors, thats what the image says

**Review by west3436 — APPROVED** [review]

**Pull request merged**
