### PR TITLE
Re-enables rotation/spin on shuttle chairs and couches.

### LINKED ISSUE #30979: You can no longer rotate gamer chairs on the shuttle
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
3668def331c952f4bac6738a4cea657d3f08700e

# Description
shuttle chairs can't spin or change direction anymore, not the normal metal ones they're fine

### PR DESCRIPTION
**Pull request by PrimeDSS13**
I'm hoping this is done correctly.
Fixes #30979

This reintroduces the ability to rotate shuttle chairs and couches, using the new system. My reasoning behind this PR is as follows:

Reinforced Shuttle Chairs: Sitting in a reinforced chair (often found on shuttles) is a lot more entertaining when you can rotate your chair. Without it, you often can only see the backs of people heads, nor can you face people when you're speaking. I don't see a reason from a gameplay perspective why it should be like this.

Couches: While couch rotation can look a bit weird, it's quite annoying to have to deconstruct the couch every time you place it at an angle (very easy with couches). This change is a bit more QOL, and if enough people would rather this part be left out of the PR I am willing to change it.

:cl:
 * tweak: You can once again spin reinforced chairs and couches.

### CODE REVIEW

**Comment by Dacendeth** [comment]
The couch thing removes the minor guesswork out of placing corner pieces, which is great.

**Comment by BomberBro** [comment]
PR fixes a self-reported "bug" that was an intentional change.

**Comment by DamianX** [comment]
and?

**Comment by Exxion** [comment]
Strictly speaking neither the issue nor the PR claims that it's a bug

**Comment by Anton-Kr** [comment]
Is there not a way to have couch pieces automagically connect anyway?

**Comment by Eneocho** [comment]
Chapel pew rotation too?

**Comment by PrimeDSS13** [comment]
I've received two requests to re-enable Pew Rotation, but I'm not certain I see the point.
If anyone else wants me to re-add pew rotation, let me know here and I'll throw it in this PR. Let me know if you don't want it, as well.



> 
> 
> PR fixes a self-reported "bug" that was an intentional change.

what did he mean by this

> 
> 
> Is there not a way to have couch pieces automagically connect anyway?

Nothing I'm familiar with.

**Comment by SonixApache** [comment]
couch, pew and other multi-part chairs should probably be handled in a different way than the rotate-chair verb

**Pull request merged**
