### PR TITLE
Unifying code blocks

### PR DESCRIPTION
**Pull request by Probe1**

### CODE REVIEW

**Comment by Intigracy** [comment]
Does this even work

**Comment by Intigracy** [comment]
"null" =/= null

**Comment by Probe1** [comment]
Check the above code block

```

for(var/turf in visRemoved)
		var/turf/t = turf
		if(obscuredTurfs[t])
			if(!t.obscured)
				var/image/obscured_static = image('icons/effects/cameravis.dmi', t, null, 15)
				obscured_static.plane = STATIC_PLANE
				t.obscured = obscured_static
			obscured += t.obscured
			for(var/eye in seenby)
				var/mob/camera/aiEye/m = eye
				if(!m || !m.ai)
					seenby -= m
					continue
				if(m.ai.client)
					m.ai.client.images += t.obscured

	changed = 0

```

and compare it to mine before your change

```

for(var/turf in obscuredTurfs)
  		var/turf/t = turf
  		if(!t.obscured)
 -			var/image/obscured_static = image('icons/effects/cameravis.dmi', t, "black", 15)
 +			var/image/obscured_static = image('icons/effects/cameravis.dmi', t, "null", 15)
  			obscured_static.plane = STATIC_PLANE
  			t.obscured = obscured_static
  		obscured += t.obscured

```

**Comment by Probe1** [comment]
Wait I'm a retard 

WELL I TESTED IT IN GAME  AND IT WORKED.  BECAUSE IT DID NOTHING.

**Comment by Intigracy** [comment]
If it references an icon_state that doesn't exist it uses the null sprite by default

The null sprite is always the one without a name in the dmi, if any. If none, it's nothing.

**Comment by Intigracy** [comment]
I just made it actually unified so someone doesn't look at it and think there's actuall an icon_state named null.

**Pull request merged**
