### PR TITLE
Emitter Re-Sprite

### PR DESCRIPTION
**Pull request by DeityLink**
emitterevenbetters
rollingemitterrrr
wrenchinweldin
image

:cl:
* imageadd: Re-sprited emitters, with some polishing by Megautham. Also gave them separate sprites for when they are wrenched, welded, or being moved. At last their beam now properly comes out from their lens.

### CODE REVIEW

**Comment by ghost** [comment]
someone said not to say that this looks too good for the rest of the server so I'm going to say that it is

**Comment by ghost** [comment]
Now make a cult version

**Comment by SageOfLight** [comment]
Regressive retards be damned. These look great.

**Comment by SonixApache** [comment]
looks really out of place compared to the artstyle of the rest of engineering stuff

if the sprite had a little less over the top shading i think it would fit just fine
it's just too dark and shiny

**Comment by ShiftyRail** [comment]
I highly preferred the sleek and thin design, especially considered it emits a one-pixel thin laser at the end.

**Comment by KingofHONK** [comment]
UUUGH THICCER

**Comment by jknpj** [comment]
@SonixApache @ShiftyRail 
image
image

**Comment by yclatious** [comment]
Don't you shittalk the laser stubber, that shit looks fucking rad you dork.

**Comment by triplehorse** [comment]
side view needs work

the orthogonal muzzle slits look thin in the front view but fuckhuge on the side view, probably because of the overuse of outlines that makes the gap look 3-tall. it's so thick it makes the rest of the muzzle look thin

the support legs also look like a stubby afterthought on the side view, they really highlight the wonky perspective going on. needs better shape

the welding detail looks more like a weird shadow than anything

**Comment by Konater** [comment]
Can you please implement a user toggle for the sprites?

**Comment by DeityLink** [comment]
@Konater I'll add an Antique subtype that could be placed in maps, such as at the Derelict.

updated sprites coming soon, once I'm done wrestling those infrared emitters.

**Comment by cloutcode** [comment]
ass

**Comment by Accipitermaris** [comment]
it would be a loss to change this iconic design

**Comment by triplehorse** [comment]
also you have 1 sprite of yellow cabling on the animation when facing north in the 2nd image

**Comment by bathosbathtime** [comment]
Animations are very nice but please make them lighter so they can be seen in-game against un-tiled floor plating.
Personally I prefer the design of the skinny emitters but if the beetle boys are made visible during normal gameplay you'll get no complaints from me.

**Comment by d3athrow** [comment]
bring the mechanical pig with you to shoot pork beams.

**Comment by DeityLink** [comment]
New pass on the sprite by Megautham while I was busy wrestling with Infrared Emitters, addressing some of the issues mentioned by @triplehorse .

bettermitters

The old emitters have earned their own "antique" variant, which will be found hidden on maps, such as on the Derelict or Deff maint.

image

**Comment by Kammerjunk** [comment]
looks like a very large power plug
you're gonna need a fat converter to get it down to whatever the interstellar spess standard is

**Comment by DeityLink** [comment]
emitterevenbetters

I think we're pretty good here.

**Comment by Kammerjunk** [comment]
I'm honestly shocked at how much more I like it with those colours. I hadn't expected that

**Comment by Chazach** [comment]
he cant keep getting away with this

**Comment by bathosbathtime** [comment]
I like these now.
Still going to call them beetle boys, though.

**Comment by cloutcode** [comment]
ok we're keeping the old ones i'm fine with this

**Pull request merged**
