### PR TITLE
killdozer v2 - ripleydozer with guns

### LINKED ISSUE #27615: Feature Request: Killdozer modkit
### What is it?
Killdozer modkit is an item that turns civilian mechs (Ripley, Firefighter Ripley, Odysseus, Clarke) into low cost and stealthy combat mechs
### How does it work?
Inserting a modkit into a mech under maintenance (like batteries or tracking beacons) enables it to use mounted weapons. Visually, the mech sprite is not changed, but if inspected, you can tell the mech has been tampered with (ie. "There are some odd pieces of equipment on this mech" after examining it). However, they also keep the same armor of the civilian models, and are easily taken down by proper combat mechs or weapons.
### Acquiring and using the modkit
Modkits can either be ordered via Syndicate PDA or manufactured after science has done some illegal research. Before using the modkit, it needs a weapons board, similar to how a plasma cutter needs a diamond mining drill (or is it kinetic accelerator) to be completed. Killdozer mechs allow a syndicate agent to make an inconspicuous combat mech that will not raise any eyebrows till its true purpose is revealed. They can also be used as extremely low cost combat mechs when shit hits the fan, like blob or xeno, to quickly get heavy support to the crew

### PR DESCRIPTION
**Pull request by hacker-on-steroids**
## What this does
new item you can attach to ripleys
makes it into a slow and extremely armored dozer and uses up a slot
also lets you add guns in the remaining 2 slots
closes #27615
image
adds the killdozer to the traitor uplink and r&d(illegal 2)

## Changelog

:cl:
 * rscadd: ripley killdozer kit - adds tons of armor and allows you to put guns onto the ripley
 * rscadd: add killdozer kit to uplink (10tc)
 * rscadd: add killdozer kit to r&d (illegal 2)

### CODE REVIEW

**Comment by githubuser4141** [comment]
you gave it 99.9% energy resist, doesn't that mean it takes essentially zero damage from ions too? sure, it depletes cell and has a chance to destroy the weapons, but still

also 99.9% resists on other things mean you literally CANNOT kill it with any non-bomb weapon or non-deletion method (singulo, SM etc)
bombs of a certain strength still have a RNG chance to instantly delete the mech because that's how explosions are handled in the mech thing, I think

I suppose the idea is that the IRL killdozer was almost invulnerable to a lot of firearms that are as powerful or more powerful as any station guns - let's just say it was proof up to .50 BMG

But this logic is a bit janky because the **real** killdozer weighed **61 tons**. A SS13 mechsuit is about the same size as a person, and the individual pieces can be picked up and moved by a human (Arms, legs, etc.) when in construction. The additonal parts (armor plates) can be picked up also, and a human can carry all the needed ingredients to manufacture a mech in his backpack.

A person can also carry this armor kit, so clearly there's nothing in a mech, even a Durand, that comes close to 60 tons. The IRL killdozer was also the size of a bulldozer (weird huh?) which in SS13 terms would probably be at least 12 entire tiles of space

So trying to make it's armour match the "IRL equivalent" when standard SS13 mechs, even so called "military grade" mechs like the Marauder which canonically is supposed to be used for  "front line assaults" is silly. If  you threw 1000 Marauder mechs into a real life battlefield like Gulf War Iraq or Ukraine, in a few weeks they would be all gone without much of a trace (well, actually they'd be abandoned - they only have a few kilometers of range), this kinda implies there's no way of fitting that much armour on a such a small size vehicle - otherwise it'd be already done. There is probably a reason why the Mauler/Seraph/Marauder don't have 99.9% proofness against attacks -- because it **can't be done.** Not on such a compact vehicle. Even if you remove the air tanks and pressurized canopy. Like, this is just a hand-sized DIY kit that you apply to a glorified forklift.

**Comment by githubuser4141** [comment]
image
Yeah, this means that a 2 size explosion has a 30% chance of instantly killing the mech, and a 1 size explosion will always 100% kill the mech, I think. Minus the chance of a deflect making it less severe.

**Comment by hacker-on-steroids** [comment]
ions do some damage but mostly empty the cell and cause shorts and navigation errors
the only real way to pop it open once it's immobile is an emitter though

good catch on the bomb resist, but what do you want me to do regarding the other armor?
it's already as slow as the durand but i guess i could also bump the move powercost way up?

**Comment by west3436** [comment]
Yeah to balance this I'd make it impossible to recharge its cell so it is rendered fully immobile once its cell dies.

**Review by west3436 — APPROVED** [review]

**Comment by MercuriusGH** [comment]
can you permanently weld yourself inside

**Comment by hacker-on-steroids** [comment]
cant believe how shit the github voters' opinions are
v1 and v3 are clearly leagues better, they should just be separate items

**Pull request merged**
