### PR TITLE
Adds see-through plastic walls and plastic flooring.

### LINKED ISSUE #3152: Suggestion/bug report - clear lockers/plastic walls
This is also a bug report, if you try to use plastic sheets on a girder as plastic registers as a mineral, it deletes the girder and uses the plastic rather than making a plastic wall. I think one would be neat.

I also think we should be able to have semi-see through plastic lockers. Thin lockers made of plastic that you can see through as to what's inside, as raincoats you can make with plastic are see through.

### LINKED ISSUE #4810: Plastic walls disappear upon construction
Build wall girder, add plastic, wall girder is gone.

### PR DESCRIPTION
**Pull request by Intigracy**
Fixes #4810
Fixes #3152

Left is plastic, right is silver for comparison. It's not obvious, but I'm ghosting in the second image.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Finally, we can have lino!

**Comment by FudgePucker** [comment]
>Cheap plastic

That plastic isn't cheap.
In someways its more valuable than diamonds.
Making diamond walls would be less expensive than making plastic walls.

**Comment by Intigracy** [comment]
I do think we should have more ways to make plastic than just botany, mind you.

**Comment by bustygoku** [comment]
But why can't you see the stars or plating underneath the plastic flooring

**Comment by d3athrow** [comment]
>But why can't you see the stars or plating underneath the plastic flooring

This

**Comment by Intigracy** [comment]
I'll change the sprite to make it look like you can see the plating through it, since I have to fix merge conflicts anyway.

Just adding transparency to the icon means it's going to be see-through to a fullblack square much like you see when there's 0 light in an area.

**Comment by bustygoku** [comment]
You can blend the icons underneath a tile and use the transparent flooring as an overlay on the existing tile

**Comment by d3athrow** [comment]
just add the old turf's iconstate to the underlays.

**Comment by FudgePucker** [comment]
Maybe be able to also add in plastic floor plating then add floor tiles so that you can see the latice with the stars under it.
I think it would look cool having a plastic structure supported by metal struts out in space.

**Comment by Probe1** [comment]
>Why can't you see the stars under the flooring?

It's not plating it's a floor tile (right?)

**Pull request closed without merging**
