### PR TITLE
Added a Judge role as an alternative job for the IAA

### PR DESCRIPTION
**Pull request by Manleto**
IAA is a heavy roleplaying job. You need to be able to be able to communicate effectively with the entire crew to do your job well. On that line of logic; why not have the job meant for dealing with the law deal with court cases as well? Seems only natural for the Judge to be an alt of the lawyer.  Force Seccies to get Warrants on code green! 

:cl:
 * rscadd: Added a Judge role as an alternative job for the IAA

### CODE REVIEW

**Comment by west3436** [comment]
How many rounds actually have trials? Seems like this would only be used once in a hundred rounds. If anything, why not give the Lawyer a spare "Judge" ID that he can use when appropriate?

**Comment by Manleto** [comment]
> How many rounds actually have trials? Seems like this would only be used once in a hundred rounds. If anything, why not give the Lawyer a spare "Judge" ID that he can use when appropriate?

Hopefully having a judge on station will increase the amount of trials.

**Comment by Optimism333** [comment]
Not a bad idea. I suggest giving the judge alt-title a different outfit to make it stand out from the baseline IAA appearance.

**Comment by Manleto** [comment]
> Not a bad idea. I suggest giving the judge alt-title a different outfit to make it stand out from the baseline IAA appearance.

I would but I don't know how to code well

**Comment by Optimism333** [comment]
> > Not a bad idea. I suggest giving the judge alt-title a different outfit to make it stand out from the baseline IAA appearance.
> 
> I would but I don't know how to code well

I'd recommend looking at the old pull below from 2017 that added the unique outfit for the Bridge Officer. It might help narrow down where you would need to change the code and what you need to do.

https://github.com/vgstation-coders/vgstation13/pull/16078

**Comment by PavelCIA** [comment]
wow I can't wait for the judge to bother security every round to have a trial for every assistant that broke a window

**Comment by slightly-floating** [comment]
There being a judge role implies that he has some authority that is higher than the Captain and Head of Security, the authority of determining guilt or innocence. If the judge's decisions are non-binding and unenforceable then the role has no point. If his authority is legitimate, then he does not have enough responsibility, as he is a lawyer re-skin with the power of the HoS.

I can also imagine people picking Judge and insisting on handing out nonguilty verdicts and other nonsense to criminals, angering the Captain and HoS, and pointlessly starting conflicts. Or just arbitrarily sentencing people to sentences that he has no way of actually enforcing.

"No I had a trial the judge said to let me go!!! HELP HoS ARRESTING ME!!!"
"NOOOOOOO I'm THE JUDGE you have to listen to my verdicts!!! MUTINY! MUTINY!!"
"hahahaha lol you get 10 years in perma for slipping someone"

That or everyone is just going to ignore the Judge 99.9999% of the time.

**Comment by jwhitak** [comment]
The crew... They are going to roll up as Judge, demand the HoS's gun, and start saying that they are the law. This is going to be funny.

**Comment by Optimism333** [comment]
> There being a judge role implies that he has some authority that is higher than the Captain and Head of Security, the authority of determining guilt or innocence. If the judge's decisions are non-binding and unenforceable then the role has no point. If his authority is legitimate, then he does not have enough responsibility, as he is a lawyer re-skin with the power of the HoS.
> 
> I can also imagine people picking Judge and insisting on handing out nonguilty verdicts and other nonsense to criminals, angering the Captain and HoS, and pointlessly starting conflicts. Or just arbitrarily sentencing people to sentences that he has no way of actually enforcing.
> 
> "No I had a trial the judge said to let me go!!! HELP HoS ARRESTING ME!!!"
> "NOOOOOOO I'm THE JUDGE you have to listen to my verdicts!!! MUTINY! MUTINY!!"
> "hahahaha lol you get 10 years in perma for slipping someone"
> 
> That or everyone is just going to ignore the Judge 99.9999% of the time.

The authority of the Judge presumably occupies that of a Central Command official authorized to preside over trials, but they still have to obey directives from the Captain if they don't contradict Space Law or orders from Centcomm. Basically the same as an IAA, except with an emphasis on trials and being an impartial arbiter in the court.

The SOP for trials does say that an authorized official from Centcomm can preside over a trial in addition to any relevant Heads of Staff. That doesn't necessarily give the Judge authority over any Heads of Staff or the Captain, just the authority to dispense justice in a courtroom.

I do think this is worth discussing, since if this pr is merged a summary of how to perform the role and how much authority it has should be added to the IAA wiki page under the Alt-Titles section.

I also want to point out that people ignoring the parent role's authority is something that happens a lot, but it's just part of the experience. As an IAA you only have as much authority as your faxes get you and other players are willing to go along with, but that's part of the fun. Like the pr author said, it's a roleplay job.

**Comment by PrimeDSS13** [comment]
This seems like a role that will have literally 0 use for 99.6% of the time. Even less useful than a lawyer, and fills no niches inbetween. I'm just not sure the point or what good gameplay will come of this.

**Comment by Manleto** [comment]
> This seems like a role that will have literally 0 use for 99.6% of the time. Even less useful than a lawyer, and fills no niches inbetween. I'm just not sure the point or what good gameplay will come of this.

Yes and?

**Comment by Eneocho** [comment]
> 
> 
> > This seems like a role that will have literally 0 use for 99.6% of the time. Even less useful than a lawyer, and fills no niches inbetween. I'm just not sure the point or what good gameplay will come of this.
> 
> Yes and?

Based RPer.

**Comment by Optimism333** [comment]
> This seems like a role that will have literally 0 use for 99.6% of the time. Even less useful than a lawyer, and fills no niches inbetween. I'm just not sure the point or what good gameplay will come of this.

I do see your point with the first criticism about the Judge rarely having a use, but I could see the same criticism being applied to the IAA job as a whole. You can't do anything another job can't except send two different fax templates that get automated responses. The draw of the job is an rp fluff role, and the Judge isn't any different.

As for the second thing, I don't agree. The job of a Judge in a trial is at least distinguishable from that of a Lawyer. The Lawyer can be prosecutor or defender, while the Judge presides over the trial, so it does actually fill a niche that previously didn't exist for the IAA alt-titles.

My only criticism is that the alt-title should at least spawn with a unique uniform so it's not mistaken on sight for a baseline IAA.

**Comment by PrimeDSS13** [comment]
> 
> 
> > > This seems like a role that will have literally 0 use for 99.6% of the time. Even less useful than a lawyer, and fills no niches inbetween. I'm just not sure the point or what good gameplay will come of this.
> > 
> > 
> > Yes and?
> 
> Based RPer.

I'm implying that roleplay falls under the "gameplay" flag as well. There is no use for a judge without an active trial, I'm not sure if any good RP will come out of this besides seeing a judge crying on their knees begging for trials even harder than a lawyer normally does.

**Comment by Optimism333** [comment]
> > > > This seems like a role that will have literally 0 use for 99.6% of the time. Even less useful than a lawyer, and fills no niches inbetween. I'm just not sure the point or what good gameplay will come of this.
> > > 
> > > 
> > > Yes and?
> > 
> > 
> > Based RPer.
> 
> I'm implying that roleplay falls under the "gameplay" flag as well. There is no use for a judge without an active trial, I'm not sure if any good RP will come out of this besides seeing a judge crying on their knees begging for trials even harder than a lawyer normally does.

Not necessarily true. One thing that was just brought up is that a Judge could be another role that can authorize or decline search warrants for security, along with creating relevant paperwork.

**Comment by Manleto** [comment]
> I'm implying that roleplay falls under the "gameplay" flag as well. There is no use for a judge without an active trial, I'm not sure if any good RP will come out of this besides seeing a judge crying on their knees begging for trials even harder than a lawyer normally does.

Got a warrant seccie

**Comment by Manleto** [comment]
> How many rounds actually have trials? Seems like this would only be used once in a hundred rounds. If anything, why not give the Lawyer a spare "Judge" ID that he can use when appropriate?

You can use a judge for more then just trials. For example, it might be smart to force sec to obtain warrants instead of breaking into places on code green.

**Comment by Blithering** [comment]
I prefer having the captain (or ranking head) be the judge. Making it a dedicated role seems far too niche, and muddies up the chain of command.

**Comment by Manleto** [comment]
> I prefer having the captain (or ranking head) be the judge. Making it a dedicated role seems far too niche, and muddies up the chain of command.

The judge is still overridden by caps orders. This just gives sec a bit more of a leash on code green and a more unbiased agent in trials.

**Comment by BurntDevil** [comment]
This is not how to "fix" security nor improve the IAA jobset.

**Pull request closed without merging**
