### PR TITLE
Resolves this problem in a way that everyone will be happy

### PR DESCRIPTION
**Pull request by ghost**
adds clearing reagents to everyone's favourite machine in medbay

### CODE REVIEW

**Comment by EdXbtkOEwGw** [comment]
you've gone too far

**Comment by ghost** [comment]
this probably won't even work lmao I forget what the name of the blood beaker stored in humans is called

**Comment by N3X15** [comment]
So from two-button cure-all caused by a bug to one-button cure-all

**Comment by ghost** [comment]
@N3X15

**Comment by N3X15** [comment]
@DrCelt

**Pull request closed without merging**
