### PR TITLE
Fossilized egg

### PR DESCRIPTION
**Pull request by MadmanMartian**
The idea that made me rework xenoarch to be more modular

 - It's an egg
 - Inject it with rezadone to make it alive
 - Could be a cockroach egg, could be a regular egg, could be a cockatrice egg, could be a borer egg, could be a parrot egg

### CODE REVIEW

**Comment by brndd** [comment]
why can't it be a xenomorph egg

**Comment by Arthurdentist** [comment]
Why not add vox eggs as a possibility too?

**Comment by DrSnips** [comment]
Would it be too much to ask for a new egg that hatches into a parrot for this?

**Comment by MadmanMartian** [comment]
@brndd xeno eggs are weird

**Comment by strawberrytan** [comment]
do wolves lay eggs? I like it

**Comment by MadmanMartian** [comment]
>do wolves lay eggs

whut

**Comment by MadmanMartian** [comment]
update:

Added a parrot egg.

Questioning about adding vox eggs to it, as they seem like they're not an old enough species to appear on an asteroid in the middle of nowhere.

**Comment by Killette2** [comment]
What about the various types of space bear eggs?

**Comment by MadmanMartian** [comment]
space bear eggs?

**Comment by MadmanMartian** [comment]
Right, chaos egg it is then.

**Pull request merged**
