### PR TITLE
A Grayy Foodery Update

### PR DESCRIPTION
**Pull request by Optimism333**
## Ali-yum! ##
Screenshot (396)

This pr is to add some unique Grayy foodery to the station. All sprites were made courtesy of the ever helpful Blithering. 

Some of the additions are new recipes for the microwave and some are prepackaged meals. New items are pictured in the screenshot above, and the list below goes through them in order.

 * **New Grayy microwave recipes:** Nymph's Peril (a diona nymph steamed in acid and served with fried rice), Stuffed Pitcher (a pitcher plant stuffed with cheese and beans), Grey Greens (a nettle branch and pitcher plant diced and seasoned with soy sauce)

 * **New Grayy prepared meals:** Zam Steak and Nettles, Zam Mothership Stew, Zam Spider Slider Delight, and Zam Biscuits. All of these can be accessed from a section in the cargo merch computer conspicuously labeled "ZAM!".

 * **A change to diona nymph kitchen spike harvesting:** Diona nymphs now drop a unique "nymph meat" item when harvested from a butcher spike. They also only drop two meat items instead of three like before. This nymph meat is the ingredient that is needed to make the Nymph's Peril dish. I also updated the veggie burger recipe to accept either diona meat or nymph meat.

That's about it. I tested the pr pretty extensively, and everything seems to work as intended. Let me know if something is ruined and I'll try to fix it if I can.

**Addendum:** All Grey microwave recipes and prepackaged meals contain acid in varying quantities, and I've provided as many warnings about this fact as I could without being ridiculously overt in item descriptions and product entries. Don't eat these if you're not a Grey!

**If you care to keep reading, here's some boring trivia about this pr:**
* I tried to add corn oil to the output of the Nymph's Peril dish, but had to remove it because sulphuric acid and corn oil react and make glycerol. Glad I caught that in testing.
* The Grayy prepackaged foods are fairly expensive and have less nutriment than comparable alternatives, but they all contain small amounts of helpful chems. Plus, cool factor and roleplay.
* The Zam boxed microwave meals can be eaten without cooking at the low cost of about two thirds of the nutriment content, any helpful chems, and your dignity. 

:cl:
 * Food items catered towards a Grayy palate have been added: a few microwave recipes, and some products that can be accessed at the cargo merch computer.
 * Diona nymphs now drop a unique meat type when harvested at a kitchen spike.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Neat stuff. Maybe at some point Grays will get their own plants for more exotic dishes.

**Comment by drawsstuff** [comment]
> Neat stuff. Maybe at some point Grays will get their own plants for more exotic dishes.

I have that planned, but dear god am I too bogged down with work to even play spess these days. Soon though.


> GREY CROPS:
> 
> Opok (Round Grapefruit)
> Blecher Berries (Tiny heart shaped green berries)
> Gingi Tree (You carve the bark off)
> Pelchin Bush (You take the leaves)
> Eymine (Flowers, the seeds are what is cooked)
> 
> INSECTIOD CROPS:
> 
> Zwixiti (Tiny Blueberry-like crops with brown leaves)
> Thuilliz (Brown-red fruiting fungus)
> Lilixitizi (Red fungus with black sap dots, dots are what is harvested)
> Kilkreth (Tiny yellow balls, fungi)
> 
> 
> GREY DISHES:
> -Opok Bilay (Opok cut open, filled with Gingi bread) - (1 gingi bread slice, 1 opok) - (5 nutriment)
> -Sillit (Pelchin leaves soaked in acid) - (10 units sulfiric acid, 1 pelchin leaf) - (10 units sillit)
> -Eymine Bilay (Eymine seeds coating a Gingi bread ball) - (1 eymine seed, gingi 1 bread slice) - (5 units nutriment)
> -Stuffed Opok (Opok cut open, filled with eymine seeds) - (1 eymine seed, 1 opok) - (6 units nutriment)
> -Sillit Soak (Gingi Bread with sillit spread and blecher berry topping) - (1 gingi bread slice, 2 blecher berry, 10 units sillit) - (12 units nutriment)
> -Gingi Bread (Sour Bread made with Gingi Shavings) - (1 gingi bark, 15 units flour) - (15 units nutriment)
> -Gingi Bread Slice (made from slicing Gingi Bread) - (4 units nutriment)
> -Blecher Soak (Blecher Berries soaked in sillit) - (5 units sillit, 1 unit blecher berry) - (4 units nutriment)
> -Eymine Bread (Bread with eymine seeds) - (1 eymine seed, 15 flour) - (15 units nutriment)
> -Eymine Bread Slice (made from slicing Eymine Bread) - (4 units nutriment)
> -Pelipeli Eybilay (Pelchin leaves soaked in sillit, flavored with gigi bark, covered a Eymine Bread ball) - (10 units nutriment)
> 
> INSECTIOD DISHES:
> -Kilkreeti (Kilkreth fungi coated with sugar) - (2 Kilkreth, 10 units sugar) - (10 units nutriment)
> -Kilxith (Kilreth fungi and Lilixitizi sweet sap, stirred into a jam like state) - (2 Kilkreth, 2 Lilixitzi, 5 units water) - (8 units nutriment)
> -Zwieethiz (Zwixiti berries and Lilixitizi sweet sap, stirred into a jam like state - (2 Zwixiti, 2 Lilixitzi, 5 units water) - (8 units nutriment)
> -Thumit (Made from grinding Thuilliz fungus) 
> -Kilxith Pie (Kilxith jam baked with Thumit fungus flour into an overwhelmingly sweet pie, traditionally served for celebrations and shared) - (1 Kilxith, 10 units Thumit) - (20 units nutriment)
> -Zwieethiz Pie (Zweieethiz jam baked with Thumit fungus flour into an overwhelmingly sweet pie, traditionally served for celebrations and shared) - (1 Zwieethiz, 10 units Thumit) - (20 units nutriment)
> -Xizzik (Giant Celebratory Insectoid dish, usually usually shared by the community. Overwhelmingly sweet sugary taste, 1 is enough to feed several people) - (2 Zwieethiz, 2 Kilxith, 10 units sugar, 20 units Thumit, 2 Lilixitizi, 1 Kilkreth, 1 Zwixiti) - (40 units nutriment, 10 units sugar) 


Ignoring that massive dump, it's good to see more alien foods. I'd say the reason vox have a more defined """metaculture""" is vox exclusive antags, suits, jobs, foods, ect.

**Comment by GreatBigFailure** [comment]
Very nice, the sprites look great and it finally makes grayy's sacid vs water thing relevant without being completely game changing.
Were you not able to butcher nymphs before though? I thought Diona, nymph and grown, both gave "leafy meat"?

**Comment by Optimism333** [comment]
> Very nice, the sprites look great and it finally makes grayy's sacid vs water thing relevant without being completely game changing.
> Were you not able to butcher nymphs before though? I thought Diona, nymph and grown, both gave "leafy meat"?

You could never directly butcher nymphs as far as I know. You could just put them on a kitchen spike to grab meat off them. 

The only difference after this pr will be that nymphs have their own unique meat sprite and type. This will allow dishes/recipes that use nymph meat specifically as a component.

Does that answer your question?

**Comment by Eneocho** [comment]
Adult dionae give leafy meat when butchered, is this the same meat you get when meatspiking a nymph?
Also, assuming they are different, do you also get the nymph meat when normal butchering or when using the gibber? 
Finally, are the zam microwave foods only available for grayys? Or can a human/plasmeme/vox/whatever purchase them too?

**Comment by Eneocho** [comment]
I could swear I've seen nymph dishes when code diving.

**Comment by Eneocho** [comment]
> 
> 
> I could swear I've seen nymph dishes when code diving.

Diona Roast

Yup, there's an icon for a Diona Roast (pic related), but no actual recipe nor food related to it.

**Comment by Kurfursten** [comment]
el conflicto del iconisimo

**Comment by Optimism333** [comment]
> el conflicto del iconisimo

Oh God why. POR QUE.

I'll see if I can manage to fix it without redoing the pr.

**Comment by Eneocho** [comment]
>
>Oh God why. POR QUE.

Post de "Preparate para consecuencias inesperadas" obligatorio.

**Comment by Optimism333** [comment]
> Adult dionae give leafy meat when butchered, is this the same meat you get when meatspiking a nymph?
> Also, assuming they are different, do you also get the nymph meat when normal butchering or when using the gibber?
> Finally, are the zam microwave foods only available for grayys? Or can a human/plasmeme/vox/whatever purchase them too?

## To answer your questions: ##

**Adult dionae give leafy meat when butchered, is this the same meat you get when meatspiking a nymph?**

After this pr, adults will still give leafy meat when butchered, but nymphs will give a unique meat type called "nymph meat" with a different appearance. The sprite is pictured in the screenshot above on the table next to the spiked nymph.

**Also, assuming they are different, do you also get the nymph meat when normal butchering or when using the gibber?**

Normal butchering doesn't work on a nymph, but the new nymph meat is obtained as a product when using either the kitchen meatspike or the gibber. I just tested it to be sure.

**Finally, are the zam microwave foods only available for grayys? Or can a human/plasmeme/vox/whatever purchase them too?**

There's no restriction, anyone can buy the meals. I considered restricting them, but decided not to.

**Comment by Optimism333** [comment]
@Kurfursten Conflicts fixed.

**Comment by Optimism333** [comment]
> > I could swear I've seen nymph dishes when code diving.
> 
> Diona Roast
> 
> Yup, there's an icon for a Diona Roast (pic related), but no actual recipe nor food related to it.

Indeed! I plan to add that dish as a recipe and food item in a pr following this one.

**Comment by Eneocho** [comment]
Jesus christ man, you even properly formatted the post answering the questions.
Are the dishes grindable for that sweet sacid?

**Comment by Optimism333** [comment]
> Jesus christ man, you even properly formatted the post answering the questions.
> Are the dishes grindable for that sweet sacid?

Yep, all the foodstuffs are grindable! Just note that for the best results extracting chems from the boxed tv dinners you'll want to microwave them first. Otherwise you'll get significantly less out of it.

**Pull request merged**
