### PR TITLE
Syringes won't slice bread

### LINKED ISSUE #7579: Using a syringe on bread slices the bread
(WEB REPORT BY: apelsinsaft REMOTE: 158.69.55.2:7777)

> Revision 33fccc16807af278cd9828b4ce9c072927976397
> 
> General description of the issue

Syringes set to inject don't inject bread, but rather slice it.

> What you expected to happen

I expected to be able to inject shit in the bread

> What actually happened

Bread got sliced

> Steps to reproduce if possible

Inject bread, receive slices

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #7579
Crude fix but whatever IT JUST WERKS

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by clusterfack** [comment]
W o w.

Honestly why not sharp a series of defines or something. Like SAW CUT STAB CHOPWOOD

**Comment by ghost** [comment]
That'd work too.

**Comment by 9600bauds** [comment]
Because sharpness is used for multiple things. Originally sharpness was implemented for the purpose of popping balloons.
Syringes are pretty sharp at their tip, that's the point. If anything this should be checking if the item is a bladed weapon but we don't have a var for that.

**Comment by ghost** [comment]
I think that's what cluster is wanting you to do.

**Comment by Shadowmech88** [comment]
Our current sharpness system is garbage.

**Comment by 9600bauds** [comment]
But that makes no sense, the current sharpness is a scale, not a define on what can each thing do.
Essentially we'd need an isbladed var or something.

**Comment by Shadowmech88** [comment]
@9600bauds 
I believe he's wanting you to keep the existing sharpness var, in order to determine degree/quality of sharpness, but ALSO add some flags/other vars for the type of sharpness, i.e. slicing/sawing/stabbing/chopping.
For example a well-made kitchen knife might have a higher sharpness than a poorly-made hatchet, but the hatchet would still be better at chopping wood because it's an axe rather than a knife.

**Comment by ghost** [comment]
Should probably be made a wee list like armour protection defines.

**Comment by 9600bauds** [comment]
That would kind of pull the rug out from under your weapons PR.

**Comment by Shadowmech88** [comment]
@9600bauds 
The only thing that might directly conflict is if you make a change to the code that governs limb severing, which I could fix.
As far as the other changes, I could simply add the appropriate sharpness type flags to my weapons after the flags get implemented.
I don't see how it would be a big problem for me.

**Comment by NigglyWiggly** [comment]
You can also cut bread and pizza and shit with screwdrivers.

**Comment by Exxion** [comment]
You can, if I'm not mistaken, butcher a xeno with a syringe _but not a fire axe_

**Comment by 9600bauds** [comment]
I see now, yeah, the proper way to handle this would be a sharpness_flags bitflag.
I might actually do it at some point but that's work for another day

**Comment by Kurfursten** [comment]
Make a proc that determines cutting power by factoring in sharpness and force. Doesn't that make the most sense? Syringes remain sharp for stuff like balloon popping while less-sharp-but-very-brutal fire axe can.

@Exxion 
can t break

**Comment by 9600bauds** [comment]
My plan is to eventually add a sharpness_flags bitflag with flags such as SHARP_POINT, BLADED_EDGE, CAN_CHOP etc.
thus, to butcher, you would need something that specifically has a bladed edge

**Comment by ghost** [comment]
Makes sense

**Comment by 9600bauds** [comment]
I'll do that in another PR though

**Comment by Exxion** [comment]
But whatever PR that one is will outmode this one

**Comment by gbasood** [comment]
Well hey that's why it's called a hotfix

**Comment by Exxion** [comment]
More like a bandaid

**Comment by 9600bauds** [comment]
I feel no shame whatsoever

**Comment by clusterfack** [comment]
PR a shit

**Comment by 9600bauds** [comment]
NO SHAME

**Comment by 9600bauds** [comment]
I eventually made this better

**Comment by ComicIronic** [comment]
You should have been shot.

**Pull request merged**
