### PR TITLE
Skellington icon update 2.0

### PR DESCRIPTION
**Pull request by chatsonf**
Update/Reopening of #15403, using lighter palette that seemed well received by people in the previous PR.

Old left, New right.
:cl:
 * imageadd: Updated skellington icons

### CODE REVIEW

**Comment by Blithering** [comment]
Because mentioning nerfing skellingtons will get this merged quicker: this new sprite has more pixels, so its easier to click on, definite combat nerf there.

**Comment by ihadtoregisterforthis** [comment]
This is still a recolor of another race. It visually takes away from skeletons as a proper race, and plasmamen as something other than purple skeletons.

**Comment by Blithering** [comment]
@ihadtoregisterforthis This is the old plasmaman sprite recoloured though, current ones look a lot fleshier, so they're still distinct.

**Comment by ihadtoregisterforthis** [comment]
They are still used as the deformed icon

**Comment by NigglyWiggly** [comment]
Plasmamen literally are just plasma-skeletons though, and you're not very likely to see them outside of a suit anyway

**Comment by Blithering** [comment]
True, no reason why human skeletons shouldn't look like grape flavour human skeletons

**Pull request merged**
