### PR TITLE
Artifical Limb Bugfixes (The First Mystery of Xivvis)

### LINKED ISSUE #24927: Peg Legs!
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
a38416ec0d6897dbedd9c567cd6150cd097db2c4

# Description
When taking a pegleg at character select you move much slower then you would if you were amputated and given a peg leg.
When you connect a peg leg the leg has a peg foot too, but on round join you are missing the invisible peg foot
# Steps to Reproduce
Join in with a peg leg, cut it off reattach it and move faster
# What you Expected
I am unsure, the speed with one peg leg is (I think) slower than a person with two legs even when it's attached
# What Actually Happened
I moved faster upon reattaching the pegleg and gaining and an invisible peg foot

### LINKED ISSUE #26257: Robohands somehow getting disconnected from arms?
Man gets EMP'd, fixes his robotic arm and hand. Somehow his hand no longer works!
Changing the limb did not fix it, only complete removal and reattatchment.
Game thinks his hand is a stump even though it's still on him as evidenced from his message being from
`//called when we try to click but have no hand
//good for general purposes
/atom/proc/attack_stump(mob/user as mob, params, var/proximity)
	if(!requires_dexterity(user))
		attack_hand(user, params, proximity) //if the object doesn't need dexterity, we can use our stump
	else
		to_chat(user, "Your [user.get_index_limb_name(user.active_hand)] is not fine enough for this action.")`
Possibility: Hand got delinked from parent arm, causing mustard gas? Not sure, more testing needed.
Told this happens a majority of the time when EMP'd, but not ALWAYS.

### LINKED ISSUE #27108: Broken Legs
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
a19aff7a75b3e73242a071f2ab68b14728a32ae8

I tried to cut off the legs of a man with a peg groin and the operation did not work. The text comes up:

"You are beginning to cut off Spray [name]'s leg with the saw.

You cut off [name]'s leg with the saw."

However the leg is not removed. I can keep performing the operation again and again without removing the leg. If I intentionally fail the operation it breaks the leg as it should.

### LINKED ISSUE #30065: somethings fucked with robot arms
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
0b935e3413c11d8b45274b8c65a1ae37298b7e13

# Description
robot arms broked but cannot be fixed and replacements are still broken for no
# Steps to Reproduce
get robo arms, emp them (try singu, that's what cucked mine), try to repair or replace
# What you Expected
arm fix
# What Actually Happened
why it no fix!!

### LINKED ISSUE #33006: Being full health with metal limbs doesn't remove the damaged limb overlay
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
82af9cd6b8845a16cc88cbb0304f9d1bec4081bd

# Description
See title. It's normally not an issue, but becomes one when you've invisible sprayed yourself.
# Steps to Reproduce
Take limb damage with a metal limb, heal to full health
# What you Expected
That the limb damage overlay would go away like it does for normal limbs
# What Actually Happened
Still there!

### PR DESCRIPTION
**Pull request by jwhitak**
The first of three medical mysteries presented to me by Dacendeth:
## Why do you get a pain overlay when your painless metal or peg limbs take damage? And why are peg legs slower if you start with them round start?
The first "mystery" was basically two mysteries put together.
1. If you got hurt on your robo limbs, even if you have 400 damage, you will not normally feel pain or die from this. However, your limbs will constantly ache in the sidebar and you will have a really hefty hurt overlay. This overlay does not go away if you repair the limbs.
2. If you started with a peg leg roundstart, you went about four times slower. If you ripped it off and reinstalled it, or otherwise got a new peg leg after round start, you went full speed.

## What this does
This is a larger PR that piles together a bunch of bugfixes for artifical limbs. The first two fixes:
1. Removes the pain overlay and messaging from peg and robotic limbs. There are checks in place to prevent inorganic limbs from causing pain, but a message and overlay were missed. It will still flash on your status hud, but you will not have to deal with a big red circle of pain the whole round since repairing the limbs wouldn't make the overlay go away.
2. Turns out, round start peg legs didn't come with a free invisible peg foot. So you suffered the ``ORGAN_DESTROYED`` slowdown. This PR adds in the option for peg feet, adds a sprite, makes the foot optional, and doesn't automatically give you one when you surgically add a new peg leg. You cannot go fast by removing and readding your peg leg anymore. Slowdown values have been tweaked to keep the same slowdown regardless of if you're on a peg leg with no foot or if you've got a peg foot with it.

While I was there, I found and fixed a few additional bugs.

3. You can no longer get invulnerable, irremovable peg body parts by having a higher level body part replaced. Most commonly seen with hands/feet, but with admeme antics it would happen with other body parts too.

image

4. You can now have your whole body peggified without blowing you apart. (Badmins: VV, use the proc peggify_all on the chest organ, then use update_body on the main person's vv)

[pegbeta04.webm](https://github.com/vgstation-coders/vgstation13/assets/69739118/102edc74-6fd4-4cf8-b7e5-0e589e8e2e16)

5. Peg body parts all now have sprites which: exist, do not stick out sides of clothing, and do not float off the side of your body. Albeit, REALLY BAD ONES. **Please, spriters, come fix my coder sprites.** (Can you tell what parts are peg and what parts are human?)

image

6. You have the option roundstart to start with a peg foot. If you would rather the classic pirate look, you can opt to have an amputated foot and still move just as fast.

image

7. If you remove a malfunctioning robotic limb, your organic and peg limbs no longer carry a malfunctioning curse onto your next robotic limb.
8. You can no longer suture peg limbs on corpses. An easy oversight, since ``is_robotic()`` doesn't check to see if it's a peg limb.

## Why it's good
Admins can now turn your entire body into a peg body. And having damaged robo arms doesn't curse your whole round with a bad pain overlay.
Fixes #24927, Fixes #26257, Fixes #27108, Fixes #30065

## Changelog

:cl:
 * rscadd: Wooden prosthesises for feet are now selectable round start, and can be added with standard surgery
 * bugfix: Attaching a peg leg no longer spawns an invisible peg foot
 * bugfix: Damaged robo/peg limbs no longer give you a pain overlay or keep it stuck on the screen
 * bugfix: Turning your entire body into a peg body no longer blows you apart
 * bugfix: You can now remove child organ peggified limbs
 * bugfix: Malfunctioning robolimbs no longer leave behind a permanent malfunctioning flag when removed
 * bugfix: You can no longer suture wounds on peg limbs.
 
[bugfix] [balance] [sprites]

### CODE REVIEW

**Comment by jwhitak** [comment]
Additional fix: You can no longer suture peg limbs.

**Comment by DeityLink** [comment]
I think peg foots should still be relatively invisible and not "foot shaped" if they are to emulate their inspiration. 
image

Rambling Maniac was such a funny static because of his looks, I think he'd have been less funny with proper looking feet.

**Comment by jwhitak** [comment]
Peg feet are optional! I get where you're coming from though. Edit: if I can muster up some time I could just change the feet into wooden 'caps' or something. Ideally, I'd like a real spriter to fly in and save the pegmen.

**Comment by wotisjanitor** [comment]
Amazing PR

**Comment by DeityLink** [comment]
But what happens then if a peg leg has its peg foot blown off/removed via surgery? do they spawn "broken peg legs" when removed? for that matter does removing a peg leg spawn a peg foot too? (ideally removing legs that have foot on them should leave the foot attached on them)

**Comment by jwhitak** [comment]
What happens when you saw off a fleshy arm with a robohand attached? I attached a robohand to find out.

```
You start attaching the robot left arm where Albert Harrison's left hand used to be.
You have attached the robot left arm where Albert Harrison's left hand used to be.
You cut off Albert Harrison's left arm with the surgeon's switchtool.
Albert Harrison's left arm flies off in an arc.
```
The hand vanishes. Same with peg hands.
image

There's a *lot* of problems with the external organ code (and with surgery for that matter). It needs a really hard look. I'll see if I can't throw some bandaids on this code but it'll be a while, probably longer than this PR will be up.

**Comment by Servalfang** [comment]
Joke about getting pegged.

**Pull request merged**
