### PR TITLE
removes doubled up New Player Options

### LINKED ISSUE #13144: New Player Options New Player Options
dreamseeker_2016-12-28_16-13-18

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #13144 

 (polls is missing in image)

### CODE REVIEW

**Comment by PJB3005** [comment]
It highly annoys me how the title is not centered.

**Comment by Intigracy** [comment]
How do I center the title then?

**Comment by Wizardcrying** [comment]
made a pr to do that @Intigracy

**Comment by Wizardcrying** [comment]
DOUBLE CONFLICTS

**Comment by 9600bauds** [comment]
None of the darkCSS titles are centered

**Comment by Wizardcrying** [comment]
That's why there's an exception.

**Comment by ghost** [comment]
Why have the white line divider if there's nothing for it to divide that isn't already divided

**Comment by PJB3005** [comment]
Oh yeah remove that too @Intigracy

**Comment by Wizardcrying** [comment]
I already removed that in the PR I made @DrCelt @PJB3005. Inti hasn't updated the screenshot yet. It also centered the title.

**Pull request merged**
