### PR TITLE
new grey sprites courtesy of kokuten

### PR DESCRIPTION
**Pull request by ghost**
New grey sprites! Now with slightly more difference between male and female greys. Courtesy of @kokuten

greys

Left is Male, right is Female

 - There is supposed to be a difference between the female and male grey eye sprites, but how eye icons are currently done, that will not be easy to implement. Leaving them in the DMI in the future.

### CODE REVIEW

**Comment by Bilgecrank** [comment]
I meant to have the eyes on the female to be narrower, but right now there will be only minor differences.

Like so

**Edit:** I don't really know how the code works, but the only solutions I can think of are either reducing the alpha shade of the eye overlay **or** switching the layering of the eyes to *below* the Grey sprite and have the eyes cut out on the body sprite to allow for the different eye shapes.

**Comment by yclatious** [comment]
>grey waifus

War has changed

**Comment by Kurfursten** [comment]
Thicc fans on suicide watch?

**Comment by Ephx1** [comment]
I honestly don't like the alternate eyes for female greys.

**Comment by Megamaw** [comment]
"last question, how do we let players know some greys are girls??"
"give them boobs."
"you're hired, welcome aboard"

**Comment by Bilgecrank** [comment]
Does it really look like boobs? The female human sprite's got big boobs, I thought I made them kind of subtle looking.

**Comment by Intigracy** [comment]
boobs
3 pixels
boobs

**Comment by Megamaw** [comment]
female human sprites look different now??

how long have i been out of the loop christ this shouldnt be too bad then

**Comment by Exxion** [comment]
They... always have? At least as far as I know
The silhouette and clothes aren't different like on TG but the sprite itself is

**Comment by Shadowmech88** [comment]
@Kokuten 
Races with differently-shaped eyes have the eyes placed in a specific .dmi file. I'm not sure if there are male and female versions of each like there are with body parts, but you could check.

**Comment by ghost** [comment]
I've gotta bounce

**Pull request closed without merging**
