### PR TITLE
Vox can now afford their own N2 closets

### LINKED ISSUE #13462: Easy Spritework: N2 Closet
For years, the Vox outpost has had alternate O2 lockers that instead contain only N2 tanks and Vox breath masks. If you're a new contributor looking to cut your teeth on something easy, this is about as simple as it gets -- recolor an existing locker and change O2 to N2.

You can find O2 lockers under utility_closets.dm, look for /obj/structure/closet/emcloset/vox and simply set the icon states for open and closed to the names you've given the new sprites in closets.dmi (this is the same icon file where the O2 locker sprite is used).

### PR DESCRIPTION
**Pull request by ghost**
Closes #13462

This adds custom sprites for the emergency lockers that the Trading Outpost uses. Changes two lines of code and adds two new sprites so I don't think this will fuck anything up.

emergencyvox
emergencyvoxopen

 * rscadd: The lockers in the Trading Outpost now have sprites that replace the normal emergency locker look.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Ask in the discord to learn about how to run a local test so you can see your code in action, and also about how to do a changelog. These are good practice for when you become a 1337 pro coder.

**Review by PJB3005 — APPROVED** [review]

**Comment by JustSumBody** [comment]
Put "closes #13462" in the description as well, that way the original issue gets closed when this gets merged

**Comment by Probe1** [comment]
That should really be a smooth ass ternary operator but whatev.

**Comment by Kurfursten** [comment]
@Probe1 You can't use operations in initial definitions AFAIK, but you'd be right if he was coding the update_icon() etc.

**Comment by Probe1** [comment]
Really?  I thought you could.  Okay I'm a dum.

**Pull request merged**
