### PR TITLE
Adds Test_empty

### PR DESCRIPTION
**Pull request by MadmanMartian**
It's literally just space, a landmark for the new_player, and a landmark for observer join.

### CODE REVIEW

**Comment by Intigracy** [comment]
but why

**Comment by ShiftyRail** [comment]
I assume this is for just a compile-time test.
However, the loading time of test_tiny is already very small, and compile times aren't really an issue anymore as of 1454.

**Comment by unid15** [comment]
less time and resources needed for compile testing = less energy is used for computing = delaying the heat death of the universe
I'm down

**Comment by MadmanMartian** [comment]
hang on, I can reduce it further

**Comment by MadmanMartian** [comment]
Can't make it much smaller than that

**Pull request merged**
