### PR TITLE
Moved the skipjack docks from the station back a little

### PR DESCRIPTION
**Pull request by JMWTurner**
inspired by #12642

before

before

after

after

:cl:
* tweak: moved the Vox Raider skipjack docks a bit away from the station so the crew won't stumble upon it while casually moving in space along the station's hull.

### CODE REVIEW

**Comment by jakmak3** [comment]
add in more docking locations for the skipjack. The raider party which is suppose to be highly mobile only having a total of 4 places to dock at (vox tradepost, 3 places near station) as oppose to the nukeops and salvage shuttle which not only have a huge amount of places to dock at near station but can also retreat to the middle of deep space (z3 z4 and z5) without ending the round so they can hide/regroup

**Comment by Probe1** [comment]
Sorry about the conflicts @JMWTurner

**Comment by JMWTurner** [comment]
@Probe1 fixed conflicts

**Comment by Probe1** [comment]
@JMWTurner 
output_15kai9

**Pull request merged**
