### PR TITLE
Charcoal buff

### PR DESCRIPTION
**Pull request by PJB3005**
:cl:
- tweak: "Charcoal works 5x faster now, remains in the body for much longer, doesn't delete itself on vomiting (but still causes vomiting) and it automatically deletes itself when all reagents are gone."

### CODE REVIEW

**Comment by kilozombie** [comment]
Overall a solid solution.

**Comment by Pathid** [comment]
Not objecting to this, but I will point out that this makes stacking charcoal with anti-tox for 2x speed toxin healing a lot less viable.

**Comment by ghost** [comment]
Pepto which is easy to mass produce by either moving or having someone move the vendors over, arith, phalanxamine, tricord, DD, then go hork down some lime juice, orange juice, and tea or hop in the meme heal tube in addition to benefitting from kudzu pods now having a different AT clone that will stack.

**Comment by SonixApache** [comment]
[needs changelog]

**Pull request merged**
