### PR TITLE
Better access to gas storage in lowfat atmos

### PR DESCRIPTION
**Pull request by nervere**
## Why it's good
You no longer have to go all the way around atmos to get to the gas storage chamber that you want.
Requested by Kurfurst and Inorien.

New are highlighted with red box:

image
## Changelog

:cl:
 * rscadd: LOWFATBAGEL: An additional exit to atmospherics has been added to make accessing gas storage easier.

### CODE REVIEW

**Comment by pedr69** [comment]
>non anchored lockers in an airlock
>a fucking table in an airlock

the only worse one is in box secmaint

**Comment by Inorien** [comment]
you should get slammed in to by a locker every time you walk in and out of an airlock

it is soul

**Comment by nervere** [comment]
External airlocks generally close fast enough where that isn't an issue. I actually looked at how other maps handle airlocks with lockers and none of them have them anchored. If you can point me to where another map does this, I will anchor them.

**Comment by Kurfursten** [comment]
You are correct they aren't anchored, he was moreso speaking from personal experience of getting lockerslammed. O2 locker here is probably a bit redundant since it's RIGHT by atmos, but fire closet is a good choice. Maybe a spare radiation safety locker for the other one? I don't rate this overall very important though, O2 locker is fine if you are love with it.

Personally I liked the window into the suit room more so you can see a bit more. It's not like there aren't windows straight to space on either side!

**Comment by nervere** [comment]
I will add the windows / maybe the blast doors back tomorrow and re-evaluate the lockers as well.

**Comment by SalmonIsTasty** [comment]
Wall pipes...

**Comment by ShiftyRail** [comment]
```
non anchored lockers in an airlock
a fucking table in an airlock
```
He's right, you know

**Pull request merged**
