### PR TITLE
revert "Revert "Revert "explosions inside bodies / open containers no longer …

### PR DESCRIPTION
**Pull request by SonixApache**
respect the polls

🆑 
- bugfix: reverted the revert of the revert of the potassium-water body clearing thing

### CODE REVIEW

**Comment by bathosbathtime** [comment]
We're going to mememode levels not before thought possible.  While I support this for reasons I've posted in the last revert I doubt this will be merged.  The WIP in the change log is interesting as well.

**Comment by SonixApache** [comment]
the WIP icon looks like this
hard-hat-exclamation
i'm not sure which one's the nuclear symbol, it might be `experiment` but at this point who cares

**Comment by Irradiation** [comment]
Sneaky c*llabs are at it again, slapping the evil tags on PRs.

**Comment by boy2mantwicethefam** [comment]
this but unironically

**Comment by SonixApache** [comment]
yeah whatever if someone cares feel free to shitpost here or elsewhere

**Comment by Exxion** [comment]
I don't really have a horse in the race of which way it ends up being, but if the current decision isn't final, get a final decision before opening another PR
Revert chains like this are only funny for a couple steps

**Comment by SonixApache** [comment]
branch is up, can always just re-open this whenever

**Pull request closed without merging**
