### PR TITLE
Removed areaMaster

### PR DESCRIPTION
**Pull request by DamianX**
Prepare for unforeseen consequences.

### CODE REVIEW

**Comment by Exxion** [comment]
>He actually did it

Wow how long did this take?

**Comment by DamianX** [comment]
I lose track of time.

**Comment by Exxion** [comment]
For those not paying attention to the Discord, in its current state, it lags
Judging from the profiler, it *appears* that it causes mobs to attempt to move about six times as often as they should, but we don't know why
Or, thanks to the nature of the source, if that's even for certain what's happening

**Comment by Exxion** [comment]
Hm. In *my* testing, this didn't happen. But 6.2 times as many calls per unit time is difficult to write off as a mapgen issue, unless there's a vault out there that contains a true fuckton of very fast mobs.

That said, `get_area()` is *by far* the most-called proc in both of our tests. Its CPU usage per call is very low, but it still hovers around the tenth-most-expensive proc by self CPU just due to the sheer number of calls.
I believe this is still a net reduction in overall CPU usage, but it would be better if it were a bigger reduction

**Comment by DamianX** [comment]
It was, in fact, a vault out there that contains a true fuckton of very fast mobs.

**Pull request merged**
