### PR TITLE
Smoothed windows

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[sprites]

## What this does
image
image

## Why it's good
looks nicer

## Changelog
:cl:
 * rscadd: Non-full windows now look smoother

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
huh neat

**Comment by angryturnip** [comment]
Can you add a pic without this PR to show the difference?

**Comment by SECBATON-GRIFFON** [comment]
> Can you add a pic without this PR to show the difference?

done

**Comment by DorainGrey** [comment]
How does this interact with the RPD?
Does it work.

**Comment by boy2mantwicethefam** [comment]
LUMMOX HIRE THIS MAN

**Comment by SECBATON-GRIFFON** [comment]
> How does this interact with the RPD? Does it work.

i think you mean the RCD, and very occasionally some windows don't smooth but if you place ones next to them that do it fixes it. unanchoring them and reanchoring also fixes it.

**Comment by Theophrastus1** [comment]
i am old and do not like change

**Comment by Hinaichigo** [comment]
Now that we have railings I think it could be possible to re-do windows in general as a transparent breakable railing, or three railings on the same tile (glass, grill, glass) Like don't have them take up the whole tile, instead be a plane with a given orientation. I wonder how that'd look.

**Comment by Exxion** [comment]
> Now that we have railings I think it could be possible to re-do windows in general as a transparent breakable railing, or three railings on the same tile (glass, grill, glass) Like don't have them take up the whole tile, instead be a plane with a given orientation. I wonder how that'd look.

How is this different from how they are now, exactly?

EDIT: Oh, do you mean having the grille and second window be border objects on the same side as the first? Why not just only use the one window?

**Comment by Hinaichigo** [comment]
Something like this:
nuwindow
or this:
nuwindow2
I was thinking the reason to not use one window would be to preserve the current mechanics of having "three lines of defense" before the window gets broken through. But I guess that could all be part of the general "window with grille" object too.

**Comment by SECBATON-GRIFFON** [comment]
> Something like this: nuwindow or this: nuwindow2 I was thinking the reason to not use one window would be to preserve the current mechanics of having "three lines of defense" before the window gets broken through. But I guess that could all be part of the general "window with grille" object too.

these look way too goonish for me sorry

**Comment by Exxion** [comment]
There is nothing stopping you from doing that (and there never has been; unsure what railings have to do with it), but there's also no obvious reason *to* do it

**Pull request merged**
