### PR TITLE
Adds a to_chat() macro, and refactors the entire chat to use it, to pave the way to a non shit chat.

### PR DESCRIPTION
**Pull request by PJB3005**
Yes all you nerds are gonna have to use this when this gets merged.

Python script I used to convert this:

``` Python
import sys
if len(sys.argv) < 2:
    print "Not enough argument supplied."
    quit()

import os
import re

weirdre = re.compile("^[0-9]")

def to_chat(string):
    tabs = string.count("\t")

    actuallytabs = ""

    while tabs > 0:
        actuallytabs += "\t"
        tabs -= 1

    ltpos = string.find("<<")
    if ltpos == -1:
        return string

    user = string[:ltpos]
    if user.find("diary") != -1 or user.find("world.log") != -1:
        return string

    if user.find("//") != -1:
        actuallytabs = "//" + actuallytabs
        user = user.replace("//", "")
    thingendpos = string[ltpos + 2:].find("//")
    if thingendpos == -1:
        thingendpos = len(string) - 1
    thing = string[ltpos + 2:][:thingendpos]
    thing = thing.strip()
    user = user.strip()
    if weirdre.search(thing) != None:
        return string

    comment = string[ltpos + 2:][thingendpos:]

    return actuallytabs + "to_chat(%s, %s)%s\r\n" % (user, thing, comment)

basicre  = re.compile("^[^<]*<<.*$")
outputre = re.compile("^[^<]*<<\s*(?:output|browse|browsersc).*$") 

print sys.argv[1]
for root, dirs, files in os.walk(sys.argv[1]):
    print root
    for filename in files:
        if filename[(len(filename) - 3):] != ".dm":
            continue

        absolute = os.path.join(root, filename)

        print absolute

        f = open(absolute, "r")
        lines = f.readlines()
        f.close()

        f = open(absolute, "w")

        for line in lines:
            if basicre.search(line) != None:
                #uh
                if outputre.search(line) == None:
                    line = to_chat(line)
            f.write(line)

        f.close()
```

Yes that's absolutely disgusting.
# I LOOKED THROUGH IT AND IT LOOKS ALRIGHT, SOME MORE REVIEW'D BE APPRECIATED.

### CODE REVIEW

**Comment by N3X15** [comment]
MAKE ME NERD

**Comment by PJB3005** [comment]
\>Feature request.

implying

**Comment by clusterfack** [comment]
If you want to use such a thing make a script to replace it everywhere

**Comment by PJB3005** [comment]
@clusterfack challenge accepted.

**Comment by clusterfack** [comment]
Wow he actually did it? What a nerd

**Comment by clusterfack** [comment]
This will never end up getting used :laughing:

**Pull request merged**
