### PR TITLE
Giving a shot at reworking vamp

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* experiment: RE:Vamp Update, Vampire has had some tweaks
* experiment: Total, and usable blood have been reworked, vampires now have "Soul", "Power", and "Blood", displayed on their HUD.
* experiment: "Blood" is finally the actual blood in their body, acquired when biting people as usual, whether they have a player's mind or not, though you get less blood from biting dead people.
* experiment: "Soul" is acquired alongside blood when biting living player-controlled humans, and allows vampires to acquire their new spells and powers. It caps at 666 and cannot go down.
* experiment: "Power" is alongside blood when biting people. It replaces "usable blood" in that it lets you cast your spells. It caps at 200 and goes down when either getting smitten, or low on blood. 
* experiment: Vampire hearts no longer replenish their vessels' blood, instead they passively lose it, and food and iron are less effective at replenishing. Eating food is still sufficient to stale the loss of blood.
* experiment: However you can now also drink actual blood directly, which will convert to blood for your vessels in your body at the same ratio to biting dead people. So vampires might now want to steal blood packs from medbay. A few bar drinks have a similar property.
* experiment: The less blood in their body, the more a vampire's vision will turn red, similar effect to inhaling Moonflower incense.
* experiment: Low blood levels no longer inflict oxygen damage to vampires, allowing them to survive longer, however at the lowest levels they also get clone damage.
* experiment: Objectives have been rewritten to account for those changes.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
1. Nice.
2. Making vampires lose real blood is bad due to blood mechanics fuckery, which means oxygen damage and all that, while at the same time putting too much pressure on vampires to succ
3. This isn't fair you cucked me of the rework that was going to happen soon(tm) (actually a few months later at best)

**Comment by Irradiation** [comment]
Make it so being on a holy tile drains their blood even more :^^^^^^^^)

On a more serious note, make it so when they go into badwrong smite territory (the one that's actively killing them), also drain their blood harder.

**Comment by Irradiation** [comment]
ALSO SPACE TILES ASSBLASTING VAMPIRES TO HELL AND BACK HARDCORE WHEN?

**Comment by ShiftyRail** [comment]
>vampire hearts no longer replenish blood, instead they passively lose blood, and food and iron are less effective at replenishing

Another exiciting antag check

**Comment by DeityLink** [comment]
@boy2mantwicethefam I'll make it so it won't fuck up their lungs because this makes no sense.
@Irradiation don't hijack my rework you dummy. I'm taking it one step at a time.
@ShiftyRail nutriments stale the drain, so that's a thing to know for vampires. Why do I feel like every time you say that it means you disagree?

Oh also vampires see their surroundings become more and more red as they become short on blood.

**Comment by Irradiation** [comment]
IN 1990, IN 1990, HIJACKING REWORK. IN 1990, IN 1990.

I'm not hijacking anything, I'm just proposing suggestions to your existing ideas.

**Comment by Goldsteel** [comment]
Okay, here are my thoughts. I think vampire should behave more like a series of acts like cult, only with picking 2-3 thralls and performing a blood ritual to awaken your vampire powers to permit your rampage. I don't think silent succ is good at all. We should encourage players to stay in the round somehow, maybe converted into bats or some other minion.

I do like vampire hunger mechanics, though. I like the idea of the pressure increasing as the vampire loses control of their humanity and things turn red and perhaps they mumble or twitch.

**Comment by ghost** [comment]
Blood decay should scale with blood reserve, having a point below which it would never decay. Decay should also have a maximum rate it could achieve. Getting blood from a player would delay this decay for a time, length depending on how much blood they got from said player.

This is both to make sure a vampire doesn't just become toothless due to the decay and to give incentive to be more active if they want to keep their new blood levels.

**Comment by DeityLink** [comment]
@codeungabunga the "decay" is from their "vessel blood", not their actually usable blood, because those two things are still different for some reason, but I didn't want to change to much at once.

**Comment by DeityLink** [comment]
I've properly redacted the changelog now. Next I'll make it so that
* bar drinks made from blood also convert to "blood" in your body
* getting a little bit of oxygen damage from blood loss will no longer puncture your lungs BECAUSE THAT MAKES NO FUCKING SENSE HOLY SHIT IT'S BEEN LIKE THAT SINCE I STARTED PLAYING SPACE 6 YEARS AGO SOON.

**Comment by Irradiation** [comment]
I have yet to get punctured lungs from bloodloss. I was under the impression that you gunk your lungs if you aren't breathing while in a low-pressure environment.

**Comment by Dacendeth** [comment]
heart doesn't replenish mundane blood? Does that mean plasmaman vampires will be stronger?

**Comment by Caboozles** [comment]
Can we get a vampire feud gamemode where the jectie is kill the other vamp AND escape alive? Like double agent with more blood and comedy.

**Comment by DeityLink** [comment]
@Dacendeth Well yeah I guess. Either that or plasmamen (and other NO_BLOOD species) could be prevented from rolling vampire at all. Which should it be?

**Comment by Exxion** [comment]
Yeah ruptured lungs is a pressure thing
It causes blood loss, not the other way around

**Comment by DeityLink** [comment]
huh weird then. I need to test more extensively.

**Comment by DamianX** [comment]
missed opportunity to call this a revamp

**Comment by DeityLink** [comment]
@DamianX It was done over a few hours at school with minimal forethought, I had a conversation on Discord that made me realize how dumb blood management is for vampires. Honestly the more I think about it, the more a full revamp imo should completely merge vessel blood and spell blood. Vampires should no longer suffer the same effects as normal humans do from blood loss.

**Comment by DamianX** [comment]
it was a pun

**Comment by DeityLink** [comment]
Team face value wins again!

**Comment by DeityLink** [comment]
This is on hold for now, I have a few un-pushed commits ready, but I'm waiting for #21766 to take a course of action.

**Comment by DeityLink** [comment]
~~I'll rework this with the unchanging state of blood taken into account.~~ nevermind I don't even like vampire, I'll let someone who actually wants to fix them to do it.

**Comment by Hoshi-chan** [comment]
I like Goldsteel's idea. Make it something that progresses, have ways to keep players in the round rather than stealth succ, which is boring as fuck, and something that leads to open conflict by the end.

Endgame vampires summoning a portal to a castle full of skeletons and wall turkeys that the crew has to get through to kill them when?

**Pull request closed without merging**
