### PR TITLE
Removes exotic larges from xenoarch sites

### PR DESCRIPTION
**Pull request by DrSnips**
## What this does

What it says on the tin.
## Why it's good

Removes exotic larges from xenoarch sites

## Changelog

:cl:
 * rscdel: Xenoarch no longer generates "exotic" large artifacts (random triggers/effects)

### CODE REVIEW

**Comment by DrSnips** [comment]
https://www.youtube.com/watch?v=R_TbF5m5KpU

**Comment by Eneocho** [comment]
based department
based gif
CEO_of_based-F4A98
you_are_based-81ED8
armstrong based department
basado
gigachad muscle man computer
gigachad Patrick Bateman
gigachad posting
gigachad stars

**Comment by djkramer123** [comment]
this is retarded

**Comment by west3436** [comment]
Hello @DrSnips 
Thank you for submitting your proposed changes to the vgstation13 project. It would appear that your pull request has bypassed some of the sections in our template, specifically the "Why it's good" part. This section is crucial for us to understand the impact and reasoning behind your changes. It helps maintainers and the community to quickly grasp the benefits and potential implications of the proposed modifications.

Could you please take a moment to update your pull request description to include this information? Providing a clear and detailed explanation will significantly aid in the review process, ensuring that everyone understands the value your changes bring to the project. Additionally, adhering to the template guidelines helps streamline the discussion and decision-making process for all contributors involved.

If you have any questions about how to fill out the template or why this information is necessary, feel free to ask. We're here to help guide you through the contribution process and make sure your efforts are recognized and understood by the community.

Looking forward to your update, and thank you for your contribution to vgstation13!

Best regards,

~~DamianX~~ west3436

**Comment by DrSnips** [comment]
> Hello @DrSnips Thank you for submitting your proposed changes to the vgstation13 project. It would appear that your pull request has bypassed some of the sections in our template, specifically the "Why it's good" part. This section is crucial for us to understand the impact and reasoning behind your changes. It helps maintainers and the community to quickly grasp the benefits and potential implications of the proposed modifications.
> 
> Could you please take a moment to update your pull request description to include this information? Providing a clear and detailed explanation will significantly aid in the review process, ensuring that everyone understands the value your changes bring to the project. Additionally, adhering to the template guidelines helps streamline the discussion and decision-making process for all contributors involved.
> 
> If you have any questions about how to fill out the template or why this information is necessary, feel free to ask. We're here to help guide you through the contribution process and make sure your efforts are recognized and understood by the community.
> 
> Looking forward to your update, and thank you for your contribution to vgstation13!
> 
> Best regards,
> 
> ~DamianX~ west3436

DEAR COLLABORATOR,
THIS IS A GOOD CHANGE BECAUSE XENOARCH F*CKIN SUCKS.
THIS REMOVES LE BAD THING, THEFORE IT'S A GOOD THING.
Sincerely, DrSnips

**Comment by Eneocho** [comment]
MERGE NOW FOR GORGEOUS LOOKS

**Comment by west3436** [comment]
pick("bad faith" ,"low effort" ,"I ded","grudgecode")

**Comment by Eneocho** [comment]
it was good while it lasted

**Comment by hacker-on-steroids** [comment]
something something leave PRs open for one week for all the votes to come in?

**Pull request closed without merging**
