### PR TITLE
Make bombsuits Vox-compatible

### PR DESCRIPTION
**Pull request by ghost**
Vox can wear bombsuits, but they don't fit. Now they do

Example of the bombsuit helm sprite, from the side : 

bombsuit_helm

The main parts of the sprites that were tweaked were the leggings (digitigrade) and the helm (beak and cranium shape)

### CODE REVIEW

**Comment by N3X15** [comment]
Please put the rest of the sprites in here so people can bitch about them.

**Comment by dylanstrategie** [comment]
In no particular order : 

bomb_suit_either
bomb_helm_f
bomb_helm_r

**Comment by Nienhaus** [comment]
*bitches*

**Comment by Probe1** [comment]
eh if you must.  I prefer to see chicken wings.

:+1:

**Pull request merged**
