### PR TITLE
ports chemical heating from tg

### PR DESCRIPTION
**Pull request by ghost**
Fuck UIs

:cl:
 * tgs: Ports chemical heating from TG, currently only used for Lithium Sodium Tungstate

### CODE REVIEW

**Comment by SonixApache** [comment]
Oh shit, now we can finally get ling tests.

**Comment by ghost** [comment]
no ling tests until ling gets fixes

**Comment by Shadowmech88** [comment]
No ling fixes until antag datums, unfortunately.

**Comment by jakmak3** [comment]
I like everything here since it can be used to make a much more fleshed out chem system except using the TEEGEE sprite. Instead keep all the code and replace the sprite with the bunsen burner because it looks cooler and feels a lot more like your doing mad science when there is a orange flame under your beaker heating your evil mixture instead of sticking it inside of a big oven with no kind of a special effect until the oven dings and its done and you have your boring chemicals

**Comment by Intigracy** [comment]
We do already have bunsen burners, I agree they should be used instead.

**Comment by jakmak3** [comment]
ye why not remove the TG sprite chem heater and replace it with the bunsen burner+animation we currently have. replace that bunsen burner object on the maps in xenoarch with one of these since he already made the xenoarch chem reaction work with these things

**Comment by ghost** [comment]
Because the bunsen burner doesn't give as much control

**Comment by jakmak3** [comment]
elaborate. Do you mean that you cant have the temp settings that the chem heater would give or in my immulsions the burner would not be as precise. What i meant in my posts was keep all the code you have, replace the box oven chemheater sprite with the bunsen burner we already have in our code and use that while also replacing the old bunsen burner in xenoarch with your new code chemical heater bunsen burner. For immhulsions look at it this way. We can summon several gallons of pure elements (oxygen, nitrogen, iron, mercury) in liquid form at room tempreture using just electricity and power the station using a black hole fed by a particle accelerator . Im sure we can make a bunsen burner capable of being extremely precise

**Comment by ghost** [comment]
I already changed the bunsen burner to apply heat to the beaker attached to it though

**Comment by jakmak** [comment]
Ye but why have 2 separate machines that do the same thing? Change the new chem heater Sprite to the Bunsen burner sprite and replace the old Bunsen burner in xenoarch with your new code thing and comment out the old code burner. The chem heater sprite tg uses sucks and the Bunsen burner just feels so much more lively than Sticking your beaker into a box and waiting for it to heat

**Comment by ghost** [comment]
but then how the fuck do you explain making a bunsen burner out of a circuitboard and machine parts?

**Comment by jakmak** [comment]
I always assumed for most of the oddball machines the circuit board is more than a circuit board and all the specialized parts that stock parts can't provide are attached to the board

**Comment by yclatious** [comment]
So, we have the ability to power a station by feeding a glorified black hole with a particle accelerator, we can power a station by stimulating a shard of ultra concentrated matter and we can have clown invasions but a bunsen burner cant have a circuit board attached to it to regulate the heating mechanism?

**Comment by SonixApache** [comment]
electric fire

**Comment by kilozombie** [comment]
a wizard did it

**Comment by SkowronX** [comment]
Wheres the bunsen burner sprite rainicorn made?

**Comment by SonixApache** [comment]
On hold till we get a 🅱️etter 🅱️unsen 🅱️urner?

**Comment by ghost** [comment]
:b:es

Am I :b:oing it right?

**Comment by SonixApache** [comment]
may🅱️e

**Comment by ghost** [comment]
_The bunsen burner's technically better at heating, but it's unique_

**Comment by N3X15** [comment]
This PR is bugged due to an old GitHub bug, please remake

**Comment by FantasticFwoosh** [comment]
Wait a second, as someone from TG can you please explain your 'ling test' in relevance to our system of heating reagents.

**Comment by Exxion** [comment]
There isn't one
Boiling blood is a proposed one because of the movie or something

**Comment by ghost** [comment]
new PR when

**Comment by SonixApache** [comment]
WYCI

**Comment by MadmanMartian** [comment]
this looks neat, I'll see what I can do with it

**Pull request closed without merging**
