### PR TITLE
Eye Tracking Glasses/Examine Messages

### PR DESCRIPTION
**Pull request by west3436**
## What this does

A second attempt at second-person examine messages as initially proposed in #32401. Adds new Eye Tracking Glasses which enable the wearer to see what other people are looking at. These can be printed at a Prolathe using glass, iron, and diamond once a material science level of 6 is obtained.

image

## Why it's good

Provides Science nerds with a new tool to improve their observational skills.

## Changelog

:cl:
 * rscadd: Added Eye Tracking Glasses, allowing you to see what other people are looking at.

### CODE REVIEW

**Comment by jwhitak** [comment]
While I don't like the ability to see what others are looking at being given to literally everyone, I do like it being on specific items. This is why I updoot. But. 

I'm not a fan of the Flawless Glasses' flavoring. I'd almost rather it be an electronic device, such as a smart-eye-tracking system goggles or similar. This just suggests that speesemen are all blind. I mean, they are, but >implying glasses would help them.

**Comment by pedr69** [comment]
i'd put the feature on either science goggles or diagnostic huds
a separate item works too

**Comment by Hinaichigo** [comment]
Though I don't really like the idea in general for the reasons discussed in the previous PR, if it had to be something, I think instead of glasses it might be nicer to have it as an effect of hyperzine or something, like hyper-focus due to it being a stimulant.

**Comment by west3436** [comment]
> for the reasons discussed in the previous PR,

You didn't provide any reasons lmao you just said you didn't like it


>I think instead of glasses it might be nicer to have it as an effect of hyperzine or something, like hyper-focus due to it being a stimulant.

This is a terrible suggestion, why would glasses do that?

**Comment by BomberBro** [comment]
Yeah why WOULD glasses do that??? Huh?? Anyway don't give the science googles even more features their joke was that they did nothing

**Comment by djkramer123** [comment]
Neat item that probably won't be used much, would be cool if the detective's huds had this effect.

**Comment by gurfan** [comment]
Should be part of the mind reading mutation instead of a whole new item.

**Comment by Eneocho** [comment]
Change the glasses' flavourtext to something along the lines of being a high definition motion sensor camera that tracks people.

**Comment by west3436** [comment]
Updated these to be "Eye Tracking Glasses" to imply use of fancy electronics to see what others are looking at.

**Comment by DorainGrey** [comment]
Can you use a sprite that's not the default glasses sprite?

There's plenty of under utilized sprites in the glasses.dmi such as the red sunglasses, the CMO hud glasses etc Which both look nice and give a visual indicator.
Or if you want I'll color one a specific one for you.

**Comment by TurboGay** [comment]
Yeah, I think this would honestly make more sense as a genetics addon to something existing like gurfan mentioned.

**Comment by west3436** [comment]
I am going to push back on the call for this to be tied for genetics. More people called for this in the form of glasses on the last PR. Changing this now to genes will lose even more support. The mind reading gene is already very powerful. I don't see the issue in making this an item. I intend to make this either a feature of the detective HUD or an attachment to his HUD in a later PR.

**Comment by jwhitak** [comment]
We could do both the genetics and the item, but we must keep in mind that the genetic version is a feature request vs what this PR does, and should be a new PR. If west doesn't wanna code it, then it's up to someone else who wants it. I personally feel both are fine, just so long as not everyone has the ability round start.

**Comment by TGFH** [comment]
Why not just make this a regular feature instead of requiring some special glasses?

**Comment by west3436** [comment]
> Why not just make this a regular feature instead of requiring some special glasses?

Look at the PR I referenced in the OP lad

**Comment by west3436** [comment]
Updated the sprite to something more unique

**Comment by Eneocho** [comment]
I want the eye tracking glasses icon to be animated like the scouters in dragon ball.
image

**Comment by west3436** [comment]
> I want the eye tracking glasses icon to be animated like the scouters in dragon ball. image

Provide the sprites

**Comment by Eneocho** [comment]
>Provide the sprites

i tried
https://files.catbox.moe/5pgkj4.dmi Use this one for the icon.

https://files.catbox.moe/vrzimu.dmi Use this one for the on-mob icon (eyes.dmi).

**Comment by west3436** [comment]
> > Provide the sprites
> 
> i tried [ i tried ](https://user-images.githubusercontent.com/67024428/176522164-f8527761-783f-4058-bab3-ae4f098829f4.gif) [ ](https://user-images.githubusercontent.com/67024428/176522164-f8527761-783f-4058-bab3-ae4f098829f4.gif) https://files.catbox.moe/2s6hfg.gif https://files.catbox.moe/vrzimu.dmi

Thanks, using this now

**Comment by Eneocho** [comment]
I changed the timing of the sprites and exported them as DMI, please check again. @west3436

**Pull request merged**
