### PR TITLE
Multi-Z cables

### PR DESCRIPTION
**Pull request by ghost**
[content][general][sprites]
awtput

:cl:
 * rscadd: Cables can now traverse height and floors on space stations, and can be thrown down open spaces.
 * rscadd: Snowbox has been revamped to include multi-floor cables.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I would like you to get the spriters to pump out *something* for Z-changing cables. It doesn't have to look good, anything is a step up from wire knots.

**Comment by ghost** [comment]
> I would like you to get the spriters to pump out _something_ for Z-changing cables. It doesn't have to look good, anything is a step up from wire knots.

This is part of why I put the PR off for so long, this is the best way I could visualise it.

**Comment by Kurfursten** [comment]
Oh, I see it now. I didn't notice the difference before since the gif is grainy. That's not terrible... I feel like we could do better, but at least it's something.

I will ask around for spriters to see if they have any ideas. Remind me tomorrow to merge this if no one does.

**Comment by WindowsErrors** [comment]
ok but how do i map this

**Comment by Kurfursten** [comment]
You need to set d1 or d2 (whichever your choice is) to UP or DOWN, which I believe are 16 and 32, you you should check. Snowbox has example cables.

**Comment by WindowsErrors** [comment]
ok thx be back next month

**Pull request merged**
