### PR TITLE
New Wizard Passive: No Gun Allowed

### PR DESCRIPTION
**Pull request by GreatBigFailure**
No Gun Allowed is a new passive you can buy from the spellbook. It prevents you from using guns. If you try to use one anyway your hand blows off like a ninja or highlander.
It costs -10 points, as in it rewards you 10 points. So the maximum points a wizard can have is now 110. 

Rather than prevent gunwiz entirely people seemed more interested in rewarding choosing not to be one.

:cl:
 * rscadd: New Wizard Passive: No Gun Allowed

### CODE REVIEW

**Comment by Chucklemonger** [comment]
honestly wouldn't mind it being higher even if just for shits and giggles
fun stuff

**Comment by PrimeDSS13** [comment]
10 seems like a good number, I ignore guns as wizard anyways. Might let me reduce the cooldown on a spell.

**Comment by GreatBigFailure** [comment]
Oh thank goodness staves don't trigger honor checks. I thought I had to do more than 5 minutes of code.
Edit: No I'm retarded and staves blew up your hand. Fixed it.

>honestly wouldn't mind it being higher even if just for shits and giggles

I think any higher just risks wizards essentially defaulting to 100 + this. Let's test this out and tinker with it if it's well accepted. I'd like to keep it below 20 regardless though.

**Comment by Zth--** [comment]
Sounds good. 

I was thinking about some other dumb shit like fat wizard giving you 5 points, but I'm not sure if going that way is a good idea

**Comment by GreatBigFailure** [comment]
> other dumb shit like fat wizard giving you 5 points, but I'm not sure if going that way is a good idea

I like the idea of tradeoffs for small amounts of points and I'd like to add a few more, but first points need to be rebalanced a bit and problem child spells need some work.

**Comment by Chucklemonger** [comment]
@Zth-- If we're just spitballing here, fat might need to be worth more than that since it'd prohibit you from using the gem hardsuit which is super popular

**Comment by Blithering** [comment]
How about Showman:
refunds some spell points in exchange for announcements going off revealing your location occasionally, preventing stealthwiz.
Something on the lines of "come one, come all to see the amazing [name], now performing in [location]"

**Comment by GreatBigFailure** [comment]
>Showman

That's a fun concept, I like it. I'd probably want to add in an announcement of what spells you've bought as well. Just full information on the wizard in exchange for the points.

**Comment by dunsel-hordon** [comment]
Ya Showman is a fun one. Also maybe make one where you get points for not using artifacts? So no staff of change or other goodies like that.

**Comment by Blithering** [comment]
Now we have spell schools, maybe a specialisation that makes spells in one school cheaper, but at the cost of more expensive spells outside of it? (mostly because lich king armour takes all but one of your spell slots at present leaving you useless)

**Pull request merged**
