### PR TITLE
Broken components can now be fixed with nanopaste

### PR DESCRIPTION
**Pull request by Zth--**
What the tin says.

This opens a new discussion, how should it be balanced? How many uses of nanopaste should it use?
The thing here is, since you can now fix the broken components, there's no real point on printing new ones

:cl:
- rscadd: Broken robot components can now be fixed with nanopaste

### CODE REVIEW

**Comment by clusterfack** [comment]
?????
You made it so you can turn broken components back into working ones, but never made it so you can repair damage to components using nanopaste? This seems flipped on its head.

**Comment by Zth--** [comment]
No one has ever (and will ever) pop out a working component and replace it with a newer one if you can just apply nanopaste on it (it works when its inside the robot).

**Comment by Zth--** [comment]
Not only it was bloat code, it didn't have sense. The only component a roboticist will pop out is a broken one. Thus this PR

**Comment by clusterfack** [comment]
If you're going to make it save component damage when popped out it makes zero gameplay sense that you can repair broken ones and not damaged ones.

**Comment by Zth--** [comment]
You can repair damaged ones. When they're inside the robot you can repair them with nanopaste. I explained it on the other comments. This PR makes it so you can now do something with broken ones

**Comment by clusterfack** [comment]
Why shouldn't you be able to repair damaged ones outside of the cyborg?

**Comment by Zth--** [comment]
I'm not saying they _shouldn't_ be able to. I'm saying it's snowflake code for a useless system that maybe it's only used once a YEAR.

No roboticist will _ever_ pop out a damaged component when they can just apply nanopaste/wires/welding tool which is waaaay more faster than printing a new component and replacing it.

**Comment by clusterfack** [comment]
Then why not add it, I don't really understand

**Pull request merged**
