### PR TITLE
- tweak: "You no longer overdose on Inaprovaline."

### PR DESCRIPTION
**Pull request by Intigracy**
"...This will make you come out of the cloner with less damage, too."

### CODE REVIEW

**Comment by PJB3005** [comment]
You should change that changelog entry to: "Unattended cloning patients won't die anymore, either."

**Comment by ihadtoregisterforthis** [comment]
What are the effects of being pumped with 1000 units of Inaprovaline?
_Without OD, that is_

**Comment by Kitfox88** [comment]
it should fatman mint you

**Comment by Intigracy** [comment]
No effect, register.

**Comment by Tokanova** [comment]
I didn't see much reason myself for Inaprov ODing you, so this is neat.

**Pull request merged**
