### PR TITLE
Holoanimals

### LINKED ISSUE #14265: None of the animals in the Holodeck Zoo are holograms
I could look past the milking holocows
I could look past the farming eggs from holochickens
But corgi meat is literally an antag objective

### PR DESCRIPTION
**Pull request by Lokiamis**
Fixes #14265 in an inefficient copy/pastey way instead of making a var because I don't know how. Also, is corgi meat really still an objective? Why.

### CODE REVIEW

**Comment by Exxion** [comment]
This doesn't actually fix it, because there are ways to butcher without using an item, and you don't need to hit chickens with anything to get eggs
And furthermore, this will have some weird effects, like making them completely invincible to melee attacks with weapons but not ranged or unarmed melee, and probably some other strange things I haven't thought of

**Comment by Kurfursten** [comment]
You need to hit a chicken with wheat to get eggs. You could set the meat type and teeth to null.

**Comment by Exxion** [comment]
Oh, do you? Huh. That's kind of weird.

Anyway yeah just do what Kurfurst said, with the addition of also making the egg type null (if there's a var for that)

**Comment by Kurfursten** [comment]
There is not, nor is there a proc for laying eggs you could just override.

Fortunately grown chickens start with eggs_left = 0 and the only way to raise it is to attack the chicken with wheat.

**Comment by Lokiamis** [comment]
this is a pretty shitty fix

**Pull request closed without merging**
