### PR TITLE
Ambrosia Changes

### PR DESCRIPTION
**Pull request by Eneocho**
[tweak]

:cl:
 * rscdel: Removed Solanine from Ambrosia Cruciatus
 * rscdel: Removed Solanine from Amborsia Vulgaris
 * rscdel: Removed Cytisine from Ambrosia Deus
 * rscadd: Added Phytocarisol and Kathalai to Ambrosia Deus
 * rscadd: Added Cytisine to Death Berries.

### CODE REVIEW

**Comment by SonixApache** [comment]
I'm not a plant man. What does this do?

**Comment by Eneocho** [comment]
> 
> 
> I'm not a plant man. What does this do?


Ambrosia Vulgaris loses the Solanine (Toxin).
Ambrosia Deus loses the Cytisine (Synaptizine) and gains Phytocarisol (Synthocarisol) and Kathalai (Dermaline).
Ambrosia Cruciatus (Syndie item) gains Cytisine,
  
Cytisine is incredibly toxic, to the point that 3u can kill you, so moved to cruciatus. Deus got enhanced to match with the "godlike" nature it has.

**Comment by DeityLink** [comment]
So you mean now we can smoke both blunts and godblunts without hilariously dying of toxic damage? upboated!

**Comment by gurfan** [comment]
If deus and vulgaris don't cause toxin damage, then neither should cruciatus. The point of cruciatus is to mimic vulgaris until your mind starts going nuts.

**Comment by Eneocho** [comment]
> 
> 
> If deus and vulgaris don't cause toxin damage, then neither should cruciatus. The point of cruciatus is to mimic vulgaris until your mind starts going nuts.

Good point, hadn't thought of that. Fixing.

**Comment by Eneocho** [comment]
Noticed I hadn't removed the solanine from Cruciatus. Removed as well so it mimicks vulgaris appropriately.

**Comment by juanototo2** [comment]
If this goes through, a non-antagonist Botanist will be unable to gain access to cytisine. Ergo, it will become effectively admin only in most rounds, as nobody will go through the trouble of getting it as a traitor when they could just go for ultrakilllkudzu instead. I am downvoting this for precisely this reason.

**Comment by ghost** [comment]
Not a fan of taking medical reagents that are normally locked to exotic roulette/xenoarch(?) and putting them on a plant you can easily obtain with modest cooperation from anyone with a chem dispenser.

**Pull request merged**
