### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by adacovsk**
New take on old maps featuring long hallway, loaded with familiar vaults, departments modified to fit more snugly together.

:cl:
 * rscadd: Did stuff!
 * rscdel: did other stuff!

### CODE REVIEW

**Comment by ghost** [comment]
what

**Comment by adacovsk** [comment]
One sec, working on it. I'm new to this

**Comment by ghost** [comment]
the pr that saved veegee station

**Comment by adacovsk** [comment]
kane-f please help, I have no idea what I'm doing. I have my .dmm file ready to go, but I'd like people to review it...

**Pull request closed without merging**
