### PR TITLE
Gourcockmongler

### PR DESCRIPTION
**Pull request by Jackreturnswithaveangenace**
brtyhthhjjfflppp

See #29820

:cl:
 * tweak: Gourmongers no longer phase through walls and objects like an overloaded pulse rifle to eat you. Also radiation effect on mobs (not harvestable radiation) is reduced from 5 tile radius to 2.

### CODE REVIEW

**Comment by chaklett** [comment]
cool bus shows up when you type 32758 into google images

**Comment by GreatBigFailure** [comment]
Remove singulo, shard, tazers, esword, chloral, etc first please. They also hurt me once.

**Comment by BomberBro** [comment]
This PR doesn't nerf the speed as far as I can tell but does nerf rad output, right?

**Comment by GreatBigFailure** [comment]
> This PR doesn't nerf the speed as far as I can tell but does nerf rad output, right?

It makes a sassy comment about their speed. It doesn't nerf the output, it nerfs the range from 5 tiles to 2 tiles.

**Comment by BomberBro** [comment]
>it nerfs the range from 5 tiles to 2 tiles. 

Should be reflected in the changelog then

**Comment by Jackreturnswithaveangenace** [comment]
> Remove singulo, shard, tazers, esword, chloral, etc first please. They also hurt me once.

Except all of those things were balanced over the years too, you cockmongler.

**Comment by chaklett** [comment]
xcg88 on google images give syou pictures of a cool machine

**Comment by Durgen** [comment]
> * tweak: Gourmongers no longer phase through walls and objects faster than an overloaded pulse rifle to eat you.

unclear what you mean. Are you saying they no longer phase through stuff, or no longer phase quickly.

**Comment by Jackreturnswithaveangenace** [comment]
No longer phase through at all, I'll amend it.

**Comment by Durgen** [comment]
This will make it very easy to create ridiculous amounts of power, but I suppose its an improvement over the status quo.

**Comment by GreatBigFailure** [comment]
> > * tweak: Gourmongers no longer phase through walls and objects faster than an overloaded pulse rifle to eat you.
> 
> unclear what you mean. Are you saying they no longer phase through stuff, or no longer phase quickly.

The word phase is incorrect. He removed their ability to move through things entirely.
They would no longer destroy walls. They wouldn't destroy computers or machines. The only thing they'd do is get stuck on things and if they run into a mob they'll knock it over. The phasing was a one line change but he removed essentially their entire hunting mechanic.

**Comment by GreatBigFailure** [comment]
Look, as salty as I am about my baby being bullied. I'm open to constructive suggestions on how to improve them as an engine. The loose isn't the issue. The issue is how easy it is to accidentally loose them. So what needs to change about them mechanically that will make them more usable and less easily loosed?
Is it a numbers issue? Slower nutrition loss? More nutrition from food? Less human-targeted rads (same/similar engine-targeted rads)
Is it more mechanical like changing how they split or how they eat or what?

**Comment by Apogee-dev** [comment]
> The word phase is incorrect. He removed their ability to move through things entirely.
> They would no longer destroy walls. They wouldn't destroy computers or machines. The only thing they'd do is get stuck on things and if they run into a mob they'll knock it over. The phasing was a one line change but he removed essentially their entire hunting mechanic.

gours need some serious tweaks but removing wall smashing makes dealing with them WAY more trivial than it should be for the amount of power they give out- it's a serious overcorrection. all they need is their ability to teleport through anything they can't smash removed and maybe their AI changed to give up the chase if another food source is closer.

**Comment by GreatBigFailure** [comment]
>gours need some serious tweaks but removing wall smashing makes dealing with them WAY more trivial than it should be for the amount of power they give out- it's a serious overcorrection. all they need is their ability to teleport through anything they can't smash removed and maybe their AI changed to give up the chase if another food source is closer.

This is why I've been so insistent on keeping the wall smash. It's like no one thought through what effect that would actually have. You'd just contain them indefinitely with half a sheet of metal and like 1 minute of work. How insanely boring, I'd rather see them fully removed. 
As far as the phasing through things they can't destroy, that was a big concession I made to time constraints and laziness. Because of how they move to targets it's too easy to get them stuck. Now that I've had some time away from the initial headache I can add more special cases and maybe get rid of the forceMove(). Originally the logic was they were climbing over things since that's what it looked like in testing. Machine frames, crushed vending machines, etc. Then I watched them tunnel through asteroid wall live and realized maybe I overlooked some things. 

Regarding the target change for food. I thought Kurf's mob AI change recently fixed that?

**Comment by bathosbathtime** [comment]
I would also like to see them fully removed.

**Comment by Durgen** [comment]
I think the ideal fix is to tie splitting to a specific diet. 

Like, they split when fed X, or fed food injected with X

**Comment by Optimism333** [comment]
> Look, as salty as I am about my baby being bullied. I'm open to constructive suggestions on how to improve them as an engine. The loose isn't the issue. The issue is how easy it is to accidentally loose them. So what needs to change about them mechanically that will make them more usable and less easily loosed?
> Is it a numbers issue? Slower nutrition loss? More nutrition from food? Less human-targeted rads (same/similar engine-targeted rads)
> Is it more mechanical like changing how they split or how they eat or what?

I'd really appreciate less human-targeted rads given how many a competent engineer can breed. Either that or slightly reducing the radius at which you absorb said rads so it's a little easier to combat them from a distance with ranged weapons when a traitor looses several of them.

**Comment by TGFH** [comment]
@GreatBigFailure I don't think it's reasonable to downvote/complain about a PR and say "Look I'll get around to fixing these problems eventually."

**Comment by SonixApache** [comment]
I feel like the removal of wallslapping and such turns them into a complete non-threat.
Better to make them less accessible and adjust lethality in small iterations.
Maybe a whitelist/blacklist for the phasing? Maybe try to unfuck the AI so it prefers things near it?

There's always the NT tech requirement to lock things away into the never-available zone.

**Comment by Jackreturnswithaveangenace** [comment]
Turns out people want it as is, and any fixes will need to involve a lot more effort than just the more broken aspects of it. It's not worth my time to spend more energy to do that so I leave resolving the issue to others.

**Comment by SonixApache** [comment]
i think the rads thing was a good change to make

**Comment by GreatBigFailure** [comment]
I know this is closed but I need to make fun of Jack because I just noticed the retard didn't actually remove the phasing part of their movement. He just removed the smashing part. So, if this was merged, instead of breaking things they'd literally ONLY phase through them.

**Pull request closed without merging**
