### PR TITLE
text_box

### PR DESCRIPTION
**Pull request by 9600bauds**
I said I would try this and well here goes my crude attempt at it.
This is literally just z-level 1 of Box copypasted into a 255x255 map, removing all the other z-levels to speed up loading times.
Same premise as #10688 but a compromise between loading times and full department functionality if you need to test something like Atmos.

How fast is it?

teststation:
~1:43 to compile, ~5 secs to start up, practically instantaneous post-joining
test_box:
~1:47 to compile, ~9 secs to start up, about 6 secs post-join before being able to spawn
box:
~1:51 to compile, ~1:05 to start up, about 28 secs post-join before being able to spawn

Not tested a lot but that's what the test station is for!

### CODE REVIEW

**Comment by 9600bauds** [comment]
Added a bunch of pre-spawned things for testing
dreamseeker_2016-07-16_06-52-38
Two Admin IDs
Two pre-loaded advanced toolbelts, which already come with a load of tools
dllhost_2016-07-16_06-53-21
One pre-loaded RPED, which already comes with tier 3 and tier 2 parts
explorer_2016-07-16_06-55-43
100 metal sheets and 100 glass sheets
Two mini-blackholes (which are just bags of holding but tiny)
Atmos SSU, Tank dispenser, two Oxygen jetpacks

50 silver, gold, diamond, plasma and phazon in R&D
One surgical incision manager and one surgeon's switchtool in Surgery

**Comment by 9600bauds** [comment]
I forgot uranium

**Comment by kol1th** [comment]
:ok_hand:

**Comment by 9600bauds** [comment]
Added a bunch more fun shit
dreamseeker_2016-07-16_19-46-59
I already forgot what most of it was so you all have the luck of finding out by yourselves!

**Comment by ghost** [comment]
You could have just moved the map a little left, or made a compromise for 260-ish tiles

Also won't be able to test asteroid and a lot of shuttles go there

**Comment by ComicIronic** [comment]
If you want to test everything, use a full map.

**Comment by 9600bauds** [comment]
I'd sooner remove the bomb testing range and make the map smaller
The whole station is your bomb testing range

**Comment by ComicIronic** [comment]
Replace the testing range with roid tiles.

**Comment by 9600bauds** [comment]
Any way to disable the map borders teleporting you?

**Comment by 9600bauds** [comment]
Honey, we've got neighbors

textbox small

https://dl.dropboxusercontent.com/u/29768571/Test_Box.png

This added 4-5 secs to startup time and the shuttles don't work at all so I'm not sure if it's worth it, but hey that's what the tiny testmap is for.

**Comment by Shadowmech88** [comment]
Wow, is that really how small the asteroid is compared to the station?

**Comment by 9600bauds** [comment]
No lol, I copied the research outpost and half the mining outpost and slapped those together

**Comment by 9600bauds** [comment]
I do have to say though, these asteroid tiles really do have a noticeable impact. I don't think it's worth keeping them around

**Comment by 9600bauds** [comment]
Reverted test_box back to just Box, moved it slightly left to fix the bomb testing range
Added test_asteroid, which is only the asteroid z-level of Box
Renamed test_map to test_tiny

**Comment by 9600bauds** [comment]
Please merge soon I already can't live without this and switching branches is a pain

**Pull request merged**
