### PR TITLE
Added separate attack verbs for lit and unlit states in matches, lighters, and cigarettes to fix issue #18572

### LINKED ISSUE #18572: you can singe people with unlit cigarettes
#### Description of issue
You can singe people with unlit cigarettes. No idea if it does damage.

#### Difference between expected and actual behavior
click diona repeatedly with unlit cigarette -> nothing happens
vs
click diona repeatedly with unlit cigarette -> diona kicks your ass for attempted murder
#### Steps to reproduce 
Click someone with an unlit cigarette.

#### Server revision
b4bc4ed40e2461a576e45a8cbe69f82d878d5e1c

### PR DESCRIPTION
**Pull request by veles2001**
Closes #18572

### CODE REVIEW

**Comment by ShiftyRail** [comment]
The syntax for automagically closing the issue is "closes #18572"

**Comment by SonixApache** [comment]
Am I reading this wrong or do they do no damage anyway?

**Comment by veles2001** [comment]
They don't do any damage. This pull request is just to fix the attack verbs.

**Comment by jknpj** [comment]
You don't quite need two vars for that, you can use initial() to reset it to the unlit verbs

**Comment by veles2001** [comment]
`initial(attack_verb)` seems to return `list("attacks")` even though I included `attack_verb = list("prods", "pokes")` in the object declaration.

**Comment by DamianX** [comment]
wait what? initial works with lists now???

**Comment by Exxion** [comment]
Fuck them this is the better solution
This or just have it swap the contents of two variables

**Pull request merged**
