### PR TITLE
Perma friendly Plasma Man suits.

### PR DESCRIPTION
**Pull request by The-Albinobigfoot**
plasmeme
- Adds Plasmaman suits for prisoner keeping purposes.
- These suits are un-spaceworthy, and can only hold tanks and their subtypes.
- Added one suit and one helmet to the perma jumpsuit locker's loot list. As well as an additional pair of shoes to match the set.

Sprites done by @Blithering with some minor edits done by me.

### CODE REVIEW

**Comment by Arthurdentist** [comment]
they look very similar to the default plasma nerd suit. Should be more distinct so you can tell easily who is and who isn't a filthy prisoner.

**Comment by ComicIronic** [comment]
I liked the idea of the transparent versions.

**Comment by jknpj** [comment]
Looking foward to see security rush the harmbatom and forceswitch of every plasmamen assistant default suit with these.

**Comment by Probe1** [comment]
I'm mildly surprised no one thought of this sooner.  It adequately solve all sides of the problem without creating downsides for either part of the equation.  Nice job.

**Comment by ghost** [comment]
Transparent would be neater, but as I'm not a spriter I can't really complain. Concept is :ok_hand:.

**Comment by Blithering** [comment]
Alternate helmet with a transparent faceplate has been added to the link on the issue, in case you want to look at all the sad skeletons' faces.

**Comment by 9600bauds** [comment]
Are you going to add the transparent version?

**Comment by The-Albinobigfoot** [comment]
I have A) The fully transparent suit with no color; and B) The prisoner helmet with a clear visor.

The two don't go together well, and I'm not a real spriter, so I'm limited to what others give me.

**Comment by ihadtoregisterforthis** [comment]
transparenthelmet

I lost the original transparency values

**Comment by The-Albinobigfoot** [comment]
I need an obj/clothing/hats sprite for the hood. I suppose I could try and make it myself, but I won't guarantee that it will resemble anything other than well-aged dogshit.

**Comment by Shadowmech88** [comment]
> The white speck appears with the suit facing north, and north only. Anyone know what causes it?

You mean south? Because it looks like the guy in your pic is facing south.
Most likely it's caused by the suit's south-facing sprite having a pixel there.

**Comment by The-Albinobigfoot** [comment]
DELETE THIS.

(It wasn't even the suit, it was the mask, turns out I accidentally put that there myself, wew.)

**Comment by The-Albinobigfoot** [comment]
travesty

Sprite now, or forever hold your peace.

**Pull request merged**
