### PR TITLE
Security sprites: the compromisening

### PR DESCRIPTION
**Pull request by Blithering**
Slightly alters the security and warden uniforms to provide a compromise between old and new styles, fixes a few errors the new style brought in. Detective uniform, coat and hat have also been compromised, bringing back the old colours, hat style and toning down the bulk of the coat. The noir version retains the current appearance, for those who prefer it.
For those who prefer pictures to ramblinf descriptions: o= original n= current GIANT = proposed
91618155-a2254700-e957-11ea-9381-7edf26807357
detnew
[sprites] [tweak] [consistency]
.
:cl:
 * bugfix:  Security uniform sprites no longer swap armband sides at random
 * bugfix: Detective's coat icon doesn't wildly vary between ground and worn states
 * imageadd: Security sprites have been slightly altered again, fashion is the true sec metagame
 * imageadd: Detective's suit has faded in the wash again

### CODE REVIEW

**Comment by Buchse** [comment]
I just don't like any of the det changes in general, I changed them for a reason. I'm ambivalent to the hat shape, but the hat and coat colors, and the skinnyness of the coat just doesn't make any sense. Trenchcoats aren't tailor-fit and slim like a suit coat is, they're baggy and when unbuttoned you generally can't see under the arms. 

You also shrank the collar, which i don't think anybody complained about at all. In short, "ree bad change"

**Comment by gurfan** [comment]
I'm pretty sure the new det coat was the one sprite that most people liked

**Comment by ghost** [comment]
Yeah, I like the hat a bit better, but I also feel like the det changes were the least controversial so I'm not sure why you went with those specifically

**Comment by PrimeDSS13** [comment]
while the "new" outfit was better than the "old" outfit the "new new" outfit is better than the "new" outfit, yah dig?

**Comment by cloutcode** [comment]
the hat was DUMB and the collar looked DUMB

**Comment by beesil** [comment]
I like the new hat but bring back the FAT coat

**Comment by aceedex** [comment]
Did the warden coat start slim fast too?

**Comment by Blithering** [comment]
AFAIK, warden coat was untouched by both this, and @Buchse 's PRs. only uniforms.
Those lamenting the loss of FAT coat, remember that the grey trench coat is remaining FAT, so all hope is not lost.

**Comment by ghost** [comment]
The cinch in the waist looks kind of weird to me, also if you're gonna post new sprites you might consider posting a version from in-game, it's hard to visualize what a 32x32 sprite over grey tiles will look like when it's at 10x size over alpha.

**Comment by SonixApache** [comment]
i'll take what i can get

**Comment by Blithering** [comment]
detmockup
Here's an image of it in it's natural habitat.

**Comment by SonixApache** [comment]
your :cl: isn't 100% consistent

**Pull request merged**
