### PR TITLE
Mr Clean no longer destroys mobs

### PR DESCRIPTION
**Pull request by brndd**
Alright maybe it's just me but I thought it was kinda dumb that Mr Clean fucking murderzones everyone rather than just, you know, cleaning.

This is something of a feedback/discussion PR because I implemented it the laziest way possible and just deleted the code that deletes mobs. If the reception is generally positive I'd like to make him clean the mobs instead (take all the blood off their clothes etc.).

:cl:
 * tweak: Mr Clean no longer gibs you

### CODE REVIEW

**Comment by DeityLink** [comment]
EH, not sure about that, I mean I get your point, but it feels like such an emblematic adminbus
I love being erased from existence and becoming a ghost so instantly that I take a good few seconds to realize it.

edit: alternatively, have him spare janitors alone.

**Comment by brndd** [comment]
The reason for this PR is that it ruined a viscera cleanup detail adminbus today. Perhaps a subtype of Mr. Clean that doesn't gib?

**Comment by DeityLink** [comment]
Well the admin could have varedited MrClean's "eating range" before sending him to the station I guess. This could have been prevented.

This being said, `who became admin and didn't know that MrClean "erases" people?`

**Comment by brndd** [comment]
Wouldn't varediting the eating range prevent him from eating dirt too?

**Comment by MadmanMartian** [comment]
We are all unclean in the eyes of he.

**Comment by DeityLink** [comment]
er actually yes. I liked the idea that MrClean sees living things as impure by default
kinda like 2hu lunarians.

**Comment by FudgePucker** [comment]
Make a non killing mr clean spawn if the station is 95% gunked.

**Comment by FudgePucker** [comment]
When I apply for admin I will make sure to mention that I know that Mr clean kills everything and calls the shuttle

**Comment by SonixApache** [comment]
humanity is filth
xenos even more so

**Comment by bathosbathtime** [comment]
It is part of the joke.

**Comment by brndd** [comment]
I guess. I'm too lazy to actually implement an alternate version of him who only cleans mobs, especially because it would probably have to be something that's not called Mr Clean to actually satisfy everyone, so I'll just close this.

**Pull request closed without merging**
