### PR TITLE
Fix roidstation's AI blast doors being part of the AI upload.

### PR DESCRIPTION
**Pull request by gurfan**
## What this does
Sets the area that the AI blast doors are in as the core instead of the upload.

## Why it's good
Brings it up to par with every other map.

## Changelog

:cl:
 * bugfix: The Roidstation AI blast doors are no longer part of the upload.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
feature

**Comment by ShiftyRail** [comment]
What does this change mechanically?

**Comment by pedr69** [comment]
>what does this change mechanically

being unable to get into the AI core in four seconds?
the roid AI core is laughably easy to get into, and this makes it a tiny bit harder

**Comment by ShiftyRail** [comment]
Ah, I see, I think I understand now.

**Pull request merged**
