### PR TITLE
Re-adds sprite for corn oil tank.

### PR DESCRIPTION
**Pull request by Probe1**
YOU FUKT UP @PJB3005 
https://github.com/d3athrow/vgstation13/commits/Bleeding-Edge/icons/obj/objects.dmi
https://github.com/d3athrow/vgstation13/commit/9d7ff729b6b89eee0b3d750327f9fbaff4aeb045
You moved the corn oil tank to the stools-chairs-beds.dmi along with other stuff.

To think, we've had invisible corn oil tanks for years.. and no one noticed.

Closes https://github.com/d3athrow/vgstation13/issues/13303

### CODE REVIEW

**Comment by SonixApache** [comment]
I noticed, actually.

**Comment by Probe1** [comment]
👏

**Comment by Kurfursten** [comment]
The only map that had one was Bus so it's not surprising it wasn't missed

**Comment by PJB3005** [comment]
Shit.

**Pull request merged**
