### PR TITLE
Randomize shrapnel damage

### PR DESCRIPTION
**Pull request by yackemflam**
Didn't really fall into the spirit of IED's
Randomized damage and range should make them more unreliable, or more reliable, who knows, they're improvized bombs.

This can let you do enough damage to crit someone in 2 shrapnel shards, or you can survive with 3+ shrapnel shards in you, for more !!FUN!!

Shrapnel: 45 -> 15 - 75 (+/-30)
Small shrapnel: 25 -> 5 - 45 (+/-20)
Plasma shrapnel: 35 -> 10 - 60 (+/-25)

:cl:
tweak: IED shrapnel does random damage now

### CODE REVIEW

**Comment by GoodG1448** [comment]
How does this behave with bullets and pellets/slugs from shotguns shells?

**Comment by yackemflam** [comment]
Doesn't change shit for bullets

**Comment by ShiftyRail** [comment]
i find it really strange that this has so many upvotes after a PR which entirely removed RNG from armours on the basis of reliability passed with flying colours

**Comment by yackemflam** [comment]
because people expect unreliability from makeshift weapons, thats why a blunderbuss can explode in your face if you fill it too far

**Review by ShiftyRail — APPROVED** [review]

**Pull request merged**
