### PR TITLE
Better Soup

### PR DESCRIPTION
**Pull request by Kurfursten**
Tomato soup you expect to cure weak diseases, but it only cures up to 10 robustness. Can you name a time you've EVER seen a virus with strength 10 or less? This PR buffs that.

🆑 
* tweak: Tomato soup now cures up to 35 robustness diseases, and also doesn't sit in your system for an hour.

### CODE REVIEW

**Comment by hacker-on-steroids** [comment]
perhaps common/maint disease strengths could also be lowered
figure 10-15 so they'd only affect half the crew or so since everyone's antibodies are randomised

i've gone onto a bus or a public space while i had a cold before and i'm pretty sure i didn't transmit the cold to literally everyone

**Comment by SonixApache** [comment]
i agree with the above
also if you're gonna touch the soup, fix the metabolism so it doesn't keep you fully fed for almost an hour

**Comment by Kurfursten** [comment]
Seems reasonable

**Comment by DeityLink** [comment]
how long does it sit in your system now? this actually governs how much antibody concentration can actually be gained from them.

**Comment by Kurfursten** [comment]
Typical can contains 30u, metabolism is 0.2 = 150 ticks

**Comment by DeityLink** [comment]
alright then, should be good enough for low strength diseases indeed (and mute the symptoms of mid strength/low robustness ones)

**Pull request merged**
