### PR TITLE
New SCP-294 wrenchable subtype

### PR DESCRIPTION
**Pull request by jknpj**
closes #24083

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Sneaky coder stop sneaky coding
"Adds new wrenchable subtype but forgets to mention new subtype can't be scanned"
Ask the mappers to remove the coffee machines or do it yourself

**Comment by boy2mantwicethefam** [comment]
This whole mess could've been avoided if you'd just made a map PR to remove the coffee machines and it would've had better reception

**Comment by jknpj** [comment]
The thing is never going to be scanable again anyways

**Comment by ShiftyRail** [comment]
I'm fine with it not being scannable, but I maintain that the ERT giving it to the station is an hilarious emergent gameplay element

**Comment by Durgen** [comment]
the original should never have been merged, the revert is still sitting positive

**Comment by SonixApache** [comment]
The revert is stupid. The ERT getting a free "literally any chem you want ever" adminbus-only item is stupid.
This is a decent compromise, even though it shouldn't ever be mapped in.

**Pull request merged**
