### PR TITLE
Frankenline Station Bug Fixes + Changes

### LINKED ISSUE #33040: LineStation's CE office has a regular RCD.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
4e29ac0ce6d6dcd1281a140a5fd593414cff5acf

# Description
Title.
# Steps to Reproduce
Linestation.
CE.
See RCD.
# What you Expected
The fancy ass RCD.
# What Actually Happened
Regular RCD.

### PR DESCRIPTION
**Pull request by DorainGrey**
## What this does
- Reorganizes Engineering Secure storage into a layout that makes sense, fixes some missing R-Walls in Engineering.
- Replaces the Security Hardsuits in EVA with Atmospheric Hardsuits, as is standard, also reinforces EVA's walls.
- Gives CE the advanced RCD and removes the excess stacks of RCD Ammo.
- Makes the Airlock Near Bridge smaller, by replacing O2 Locker with Wallmounted O2 Locker.
- Fixes some missing firedoors.
- Removes window and backdoor to teleporter room. Keeps shutter.
image

- Moves Atmos Tech Gear out of the hallway into a dedicated area beside atmos monitoring.

image

- Adds Airlock to shard chamber, so engineers don't need to leave Engineering to setup the shard. Also prelinks shard to computer.
image

- Rewires engineering a bit, to make more sense.
- Fixes Engineering External airlocks being Arrivals Airlocks.

## Why it's good
Fixes a lot of issues with Engineering on Line, it's definitely still cramped and some very odd placement but this is all I'm willing to do in 1 PR.
Willing to fix other issues people have identified with different departments, if they comment here to let me know.

Fixes: #33040

## Changelog
:cl:
* tweak: Reorganizes Engineering Secure storage into a layout that makes sense, fixes some missing R-Walls in Engineering.
* tweak: Replaces the Security Hardsuits in EVA with Atmospheric Hardsuits, as is standard, also reinforces EVA's walls.
* bugfix: Gives CE the advanced RCD and removes the excess stacks of RCD Ammo.
* bugfix: Fixes Engineering External airlocks being Arrivals Airlocks.
* tweak: Makes the Airlock Near Bridge smaller, by replacing O2 Locker with Wallmounted O2 Locker.
* tweak: Fixes some missing firedoors.
* tweak: Removes window and backdoor to teleporter room. Keeps shutter.
* tweak:Moves Atmos Tech Gear out of the hallway into a dedicated area beside atmos monitoring.
 * rscadd: Added new thing. Adds Airlock to shard chamber, so engineers don't need to leave Engineering to setup the shard.
* tweak: Rewires engineering a bit, to make more sense.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Please make the airlock to space part of the SM Room

**Comment by DorainGrey** [comment]
> Please make the airlock to space part of the SM Room

Done

**Comment by pedr69** [comment]
for future reference, you should probably make the changelogs a bit shorter, and include a frankenline somewhere

**Comment by adacovsk** [comment]
@DorainGrey did you close off the maint hallway? Also crayons in dorms and washer needed, and check disposals around the fitness room

**Comment by Kurfursten** [comment]
You forgot to uninclude line ree

**Pull request merged**
