### PR TITLE
Shuttle and ERT are now called if no players are alive

### LINKED ISSUE #29460: [Feature Request] Automatic Shuttle Call/ERT if nobody has been alive on Z1 for at least 5 minutes.
On the event of everyone dying in a round (something that, while uncommon, is a recurring affair on deadpop), you get an empty station with no way to end the round if there are no admins online. And methods to call it anyway (Derilect MoMMI making an AI and having it call the shuttle being the main one) are not done for fear of bwoink. 
Please add an automatic shuttle call or ERT if nobody's been alive on Z1 for at least 5 minutes. It could be IC'd as: "No life signatures have been detected on the station. An emergency shuttle has been sent in case our sensors are mistaken./An Emergency Response Team has been dispatched to inspect the situation." [discussion][featurerequest]

### PR DESCRIPTION
**Pull request by ghost**
Closes #29460 
Also updates shuttle_autocall() to accept a reason instead of a hardcoded one
:cl:
 * rscadd: The emergency shuttle and response team are now called to your station if there are no signs of sentient life.

### CODE REVIEW

**Comment by SGuivenne** [comment]
>     * rscadd: The emergency shuttle and response team are now called to your station if there are no signs of sentient life.

Wont that just call the emergency shuttle at round-start most of the time?

**Comment by KillFurries** [comment]
I assume this checks for everyone alive at the moment anywhere and not just people on the station, so it doesn't call the shuttle if everyone goes space exploring but what does it count as sentient life? If everyone on the station is dead but a mommi is working on something on derelict station, does the shuttle get called? Do borgs count as sentient life? What if several people are alive but they're brains stuck in MMIs?
In theory this had to have been implemented a long time ago but it's not clear if this will work as intended.

**Comment by gurfan** [comment]
this is a bad and pointless idea that will lead to unforeseen consequences

**Comment by ghost** [comment]
> Wont that just call the emergency shuttle at round-start most of the time?

I added a check to wait about 15 or so minutes in the world before doing this so that it doesn't

**Comment by ghost** [comment]
> Do borgs count as sentient life? What if several people are alive but they're brains stuck in MMIs?

I think it counts all non-ghost players that are living

**Comment by KillFurries** [comment]
> I think it counts all non-ghost players that are living


That's not great because these kinds of dead rounds tend to have people join as a mommi and fuck around on derelict, one player can keep the shuttle from being called without even realizing it. What about things like bomberman arena or holodeck? It would be silly if a round restart would be kept away by bored people playing bomberman to pass the time, or someone joining as a hologram to prevent the shuttle call.

**Comment by Eneocho** [comment]
Make it check for cyborgs, humanoid crew and traders but not MoMMIs, since a stationside mommi would have to break the rules and risk a bwoink to call it and a derilect mommi couldn't call it anyway.

**Comment by Theophrastus1** [comment]
> 
> 
> this is a bad and pointless idea that will lead to unforeseen consequences

a lot better than all of deadpop being dead for almost 3 hours with no round reset or admin intervention

**Comment by Blithering** [comment]
As I said in the suggestion, I think it would be better just to have it pop up with a wide shot of the station like when the nuke blows, as the lights slowly go out, then end the round immediately, saving ghosts 15 minutes waiting for the shuttle to arrive, load up noone and head back. Bonus points for https://www.youtube.com/watch?v=HsM_VmN6ytk playing.

**Comment by Olb43** [comment]
> 
> 
> As I said in the suggestion, I think it would be better just to have it pop up with a wide shot of the station like when the nuke blows, as the lights slowly go out, then end the round immediately, saving ghosts 15 minutes waiting for the shuttle to arrive, load up noone and head back. Bonus points for https://www.youtube.com/watch?v=HsM_VmN6ytk playing.

I like this more.

**Comment by Blithering** [comment]
Anonymous madlad in the thread took the time to animate the idea.

**Comment by Eneocho** [comment]
> 
> 
> 
> Anonymous madlad in the thread took the time to animate the idea.

I would speed up the animation since it feels a bit longer than it should.

**Comment by TGFH** [comment]
Do shades and constructs count as players? If they do, they shouldn't.

**Comment by Eneocho** [comment]
Thread anon delivered an updated version of the round end gif.
Sped up roundend

**Comment by Kurfursten** [comment]
Going to hold on this until it has been reimplemented in what appears to be the new intended form.

**Comment by xeroxemnas** [comment]
oof how depressing
omega bad end

**Comment by Kurfursten** [comment]
Today I will remind him

**Comment by ghost** [comment]
Might just make a whole new separate PR for it and close this one

**Comment by Eneocho** [comment]
@kane-f perhaps?

**Comment by Eneocho** [comment]
@kane-f Any chance you could do this one again?

**Pull request closed without merging**
