### PR TITLE
Revolutionary Announcement

### PR DESCRIPTION
**Pull request by Jackreturnswithaveangenace**
Revs get knocked out of their stupor by some loud and proud gamer music. I think it's time to remind people of their allegiances again.

Requested by @PrimeDSS13.
Reverts #27372

:cl:
 * rscadd: Revolutionaries can again trigger an announcement at a high enough conversion rate, leading to loud music to wake up the masses.

### CODE REVIEW

**Comment by Eneocho** [comment]
image

**Comment by BomberBro** [comment]
gamer

**Comment by Jackreturnswithaveangenace** [comment]
gamers rise up

**Comment by Jackreturnswithaveangenace** [comment]
For record keeping
the deal

**Comment by APCUnlocked** [comment]
long have us GAMERS been oppressed, but not anymore...

**Pull request merged**
