### PR TITLE
curator wood and beret fix

### LINKED ISSUE #31811: Curator does not spawn with a beret, regardless of race.
#### Description of issue
Joined as curator both as a grey and a human, did not get the beret.
#### Difference between expected and actual behavior
Expected beret. Got nothing.
#### Steps to reproduce
Join as curator.
[bugfix]

### PR DESCRIPTION
**Pull request by Eneocho**
You're supposed to get 2 wood bigstacks, you only get 1 and a bugged backpack. And berets did not spawn at all. 
Fixes #31811
[hotfix]
:cl:
 * bugfix: curators should get wood and berets properly now
 * tweak: curators now get 50 wood instead of 40

### CODE REVIEW

**Comment by SonixApache** [comment]
yell at collabs for merge
make sure you test it

**Comment by Kurfursten** [comment]
Raising the amount from 40 to 50 as part of a hotfix?

**Comment by Eneocho** [comment]
> Raising the amount from 40 to 50 as part of a hotfix?

Its supposed to be 40 though?

**Comment by Eneocho** [comment]
Ah shit it's 50.

**Comment by Eneocho** [comment]
I guess 50 aint that bad to be honest, the only reason it was 40 wood was because I didn't want to make another stack type for 50 wood so they got 20 twice. Feature now. Fixed CL.

**Comment by SonixApache** [comment]
no longer a hotfix and as such you have ruined your chances at FastMerge™
good job, buffoon

**Comment by Eneocho** [comment]
Since one of the painting PRs changed it from framed canvas to unframed canvas, you need some extra wood to frame your paintings as before (10 small frames at 4 wood each for 40 wood + 1 wood per frame for the extra 10). Call it a feature as well.

**Pull request merged**
