### PR TITLE
[DNM] Floor Plating Removal Steps

### PR DESCRIPTION
**Pull request by N3X15**
# Executive Summary

Allows players to remove plating from lattice.
Plating must be fully repaired first, if damaged.

# Recipes
Disassemble:
* Weld (4s)
* Crowbar (1s)

### CODE REVIEW

**Comment by SonixApache** [comment]
jesus christ how horrifying

**Comment by N3X15** [comment]
This is failing in testing, DNM.

**Comment by ghost** [comment]
Easier to make a breach than it is to weld a wall?

Hell yeah let's see where this goes

**Comment by yclatious** [comment]
Sounds like !FUN! to me, why not try it.

**Comment by SonixApache** [comment]
make it use like 70 fuel if anything
gives a purpose to the large-tank welders that don't fit in belts

**Comment by abagone** [comment]
What if one of the deconstruction requirements is that there was almost no air pressure? 
So you can't just deconstruct a floor in the hallway unless that hallway is already fucked.

**Comment by ghost** [comment]
You probably already had this planned but just in case, this really needs sprites for halfway-deconstructed floor

**Comment by CptWad** [comment]
though it makes sense that something like this should exist, its an incredibly griffy feature
I am up for something that makes it harder to do

**Comment by ghost** [comment]
This is going to be so robust.
For those of you who don't know, magboots + welder tank is an extremely good combo because the moment Sec runs into the room you shoot the weldertank and they are immediately ZAS'd for a free kill. Basically a screen-wide instant stun and you're probably the only one that was prepared for it.

If you weld a tile in preparation, you can have a 1sec cast time screen-wide stun. I can see people getting this to work and it will be amazing.

**Comment by Riekland** [comment]
have it be 1second for the crowbar if there's no pressure on the tile but make it like 10 or 20 seconds if there is pressure since you're fucking fighting against the force of livable atmosphere flying out and space flying in

**Comment by ghost** [comment]
>space flying in

**Comment by Riekland** [comment]
im not very clever

**Comment by abagone** [comment]
Oh another thing I think would be a good idea is since we have glass floors make it so that you can insert a piece of glass rather than using a crowbar to replace the floor with glass and a floor tile to turn them back to normal floors. 

It be nice to have since you wouldn't have to vacate the room of air in order to replace the floor.

**Comment by FudgePucker** [comment]
As it stands one of the few ways to remove a floor plating is the RCD.
This would let anybody with a toolbox remove plating.
Pros: not having to get RCD to do autism.
Cons: holy smokes you can space all the air out of a room with a toolbox.

I like the 'air pressure needs to be low' idea. Too high pressure and you can't break the seal with a crowbar.

**Pull request closed without merging**
