### PR TITLE
Snowmap Changes From Stress Test

### PR DESCRIPTION
**Pull request by plosky1**
Currently a draft because waiting on @GlassEclipse to fix the footsteps and lighting issue. 

Remapped security, added mining shuttle, mining roid on the comet has been changed to a regular mining roid since snow roid tiles are super gunked and idk how to fix them. Requires oxygen/mining suit as its depressurized now with no air. Remapped Vox outpost and gave them a shiny new shuttle. Remapped part of the TEG room and engineering. Plus random other small changes.

githubrender

[snowmap]
[bugfix]

:cl:
 * rscadd: Lots of changes for Snowmap. Important to note that miners now need air and suits for mining, and have their own shuttle.

### CODE REVIEW

**Comment by Blithering** [comment]
Will it ever be viable to remap it to be completely landlocked? would be neat to have shuttles arrive on landing pads rather than have part of the station sticking out into space for them

**Comment by plosky1** [comment]
Possibly, there's a lot of stuff I'd have to think up solutions for such as atmos/engineering cooling, how gas floods would work, etc.

Right now it's not possible because most shuttles can't land on snow due to their destroy_everything var being set to 0 instead of 1.

Also thank you @GlassEclipse for fixing lighting and snowsteps and some more stuff! We're ready to merge and go again.

**Comment by plosky1** [comment]
Ready for speedmerge....pls....

**Comment by Blithering** [comment]
Partly why I thought landing pads might be a good idea, they could be an unbuildable turf so you wouldn't have to worry about deleting anything but the odd deer or player standing in the way. Just an idea for the distant future though.

**Pull request merged**
