### PR TITLE
Box Maintenance - Minimalism

### PR DESCRIPTION
**Pull request by plosky1**
I have heard the feedback, weighed the pros and cons, and reverted everything I did before along with removing other parts of box maintenance.

Why? Minimalism is cool, and having connected maint is even cooler.

boxnew1

box2

boxnew2

[box]
[controversial]

:cl:
 * rscdel: Box maintenance has been slimmed down, specifically the NW, NE, and SW quadrants.

### CODE REVIEW

**Comment by brndd** [comment]
I liked that bit in the southeast. Aren't you removing ghetto botany along with this? That's been in for a long time.

I think it's really just the ghetto bar area that people had a problem with.

**Comment by plosky1** [comment]
This is removing ghetto botany. Slim maintenance means slim maintenance all around. Hence why I doubt it'll get merged, but hey, the [vocal minority] has called for it.

**Comment by Intigracy** [comment]
[people don't like change]
[undo change]
[also make changes in polar opposite direction]

🤔

**Comment by plosky1** [comment]
It's not really an "undo", but rather a culling of the most egregious blobby areas of maintenance.

**Comment by DrSnips** [comment]
I also enjoyed the south part so Im on the nay side here

**Comment by brndd** [comment]
I also liked that bit in the northeast around the chapel for what it's worth.

**Comment by Irradiation** [comment]
Bring back ghetto botany. It's the only area in Box Maint where you'll find botany machines and some nice seeds. Also it was there before you changed maint.

**Comment by bthomas2** [comment]
leave backup art storage, too

**Comment by ghost** [comment]
I really disagree with this. Maint is fine as is. If specific rooms need culling, we can easily do it

Or people can stop being lazy and create new stuff that needs rooms

**Comment by ShiftyRail** [comment]
Not against this per se, but please keep Ghetto Botany.

**Comment by IzayaChan** [comment]
Minimalism sucks

**Comment by SneakyCanuck** [comment]
KILL ALL CODERS

**Comment by ghost** [comment]
>ghetto theater stays
>ghetto botany is gone
what's wrong with the current maintenance space?

**Comment by SonixApache** [comment]
image
this right here means that if arrivals is firelocked new arrivals will still have a hard time going into maint unlike oldbox where you could just take the door up north
so it's bad

personally i'd just like to see the recently added maint tumor / boxing ring be gone 5ever while keeping the new connections since they're good

**Comment by iFlashYou** [comment]
Only thing that had to go was the boxing ring, everything else was fine.

**Comment by plosky1** [comment]
Bottom right cancer blob was restored to it's old state. Top right was not touched. Top left had a hallway added to the toilets in case of firewall.

dreammaker_DGdPn9cAKN

boxnew2

**Comment by AI-Is-Rogue** [comment]
Does trash really need to be mapped in when we have permagunk that does that?

**Comment by plosky1** [comment]
Any trash that's mapped in was done before this PR.

**Comment by AI-Is-Rogue** [comment]
The bee was already mapped in?

**Comment by plosky1** [comment]
Yes, it's currently on Box.

**Comment by AI-Is-Rogue** [comment]
Shit, my bad then, why's there just a random bee?

**Comment by Blithering** [comment]
I would prefer it being un-deff-ified rather than outright removing everything. Just because its in maints doesn't meant it has to be boarded up, smeared with shit and full of deadends

**Comment by brndd** [comment]
> Shit, my bad then, why's there just a random bee?

it was added there during the deffication

**Pull request closed without merging**
