### PR TITLE
Removes Line Station from the voting pool

### PR DESCRIPTION
**Pull request by BomberBro**
Remember #31770? Remember **http://ss13.moe/index.php/poll/230**, when we had an entire poll to lock it to October and it passed? I'm tired of seeing this dogshit map try to squeeze into the voting pool against PRs we've already made because its creator can't accept it's a bad map. 

There's already a poll for the map system reversion so I don't have any comment on that one.

### CODE REVIEW

**Comment by jwhitak** [comment]
~~Bad faith PR.~~ There are methods besides this to resolve the situation, usually involving going to the forums and requesting people get repobanned, or leaving feedback on collabs who don't check for this. In addition, the PR that allows line outside of October has a new poll going on it. Remember to log in the server and vote.

EDIT: PR is not bad faith. I made a comment in haste and said mean things. I am sorry.

**Comment by Theophrastus1** [comment]
Sure it is in bad faith, but fuck this dogshit map

**Comment by BomberBro** [comment]
This isn't in bad faith at all, I want this PR to pass and not in the accelerationist way. The map should've never even had a shot after we did that serverwide poll.

**Comment by boy2mantwicethefam** [comment]
I'm out of the loop because I don't involve myself in drama, but what's actually wrong with Line? Even the gnome fetish stuff was removed.

**Comment by BomberBro** [comment]
It's a bad map. It's just a bunch of maps fused together like an april fools joke, but the creator insists it's a real, genuine map. It's made weirder by the fact that, after it got wiped via multiple votes, the creator made 3-4 PRs that slowly brought it back in rotation without outright saying so.

**Comment by Theophrastus1** [comment]
> It's a bad map. It's just a bunch of maps fused together like an april fools joke, but the creator insists it's a real, genuine map. It's made weirder by the fact that, after it got wiped via multiple votes, the creator made 3-4 PRs that slowly brought it back in rotation without outright saying so.

"yeah it sucks that my idea didnt get merged, but this PR is just gonna install the framework for my idea that failed a server vote" type shit that kanef did a lot

**Comment by boy2mantwicethefam** [comment]
It's just a weird map, is all. It's no Metaclub.

**Comment by WindowsErrors** [comment]
You can't break a mapper the way you break a coder or a player. The harder you beat a mapper, the taller he stands. To break a mapper's will, to break his spirit, you have to break his map. Mappers have this idea that we can map with dignity, that there is a proper way to make a map. It's absurd. It's an aesthetic we needed to endure the bloody horror of murder. You must destroy that idea. Show them what a messy, terrible thing it is to make a map, and then show them that you relish in it. Make a skubby map, then remove the map. Ban them. Take their bugs and vulnerabilities. Destroy their preconceptions of what a map is, and you become their personal monster. When they fear you, you become stronger, you become better. But let's never forget: It's a display. It's a posture, like a lion's roar or a gorilla thumping at his chest. If you lose yourself in the display, if you succumb to the horror, then you become the monster. You become reduced. Not more than a mapper, but less, and it can be fatal.

**Comment by ghost** [comment]
i thought this was a joke map how did it even make it into the rotation lmao

**Comment by jwhitak** [comment]
Line was only reduced to being in rotation in October. It remained compiled. Then this PR came out and passed the server vote (which has a new vote if you want to revert it): #32966

This PR came immediately after a long Line round, and the admins rigging the vote against Castle for Box.

**Comment by BomberBro** [comment]
Which was also a garbage PR, but that one didn't mention Line at all so it's not like it's a good representation on that map specifically.

**Comment by Servalfang** [comment]
stupid maps have soul boxcucks

**Comment by jwhitak** [comment]
It was an example of the creep mentioned, that primetime PR was made by the creator of Linestation and the first comment called it out.

**Comment by adacovsk** [comment]
I'm surprised how frequently it's voted on, I'd at least would've expected snaxi by now. It's a victim of its own success

**Comment by djkramer123** [comment]
The same coder that made the map keeps trying to force his map into rotation after it gets banished to its own month, shocking.

**Comment by nervere** [comment]
> Bad faith PR. There are methods besides this to resolve the situation, usually involving going to the forums and requesting people get repobanned, or leaving feedback on collabs who don't check for this. In addition, the PR that allows line outside of October has a new poll going on it. Remember to log in the server and vote.

"Bad faith" would mean the PR is trying to be sneaky, or its purpose is other than what's stated.
I think this PR is clear and concise in what it wants and what it accomplishes.

**Comment by west3436** [comment]
> Bad faith PR. There are methods besides this to resolve the situation, usually involving going to the forums and requesting people get repobanned, or leaving feedback on collabs who don't check for this. In addition, the PR that allows line outside of October has a new poll going on it. Remember to log in the server and vote.

adacovsk makes a lot of good PRs, I don't want to request him to be repobanned just because of his Linestation memes

**Comment by nervere** [comment]
> > Bad faith PR. There are methods besides this to resolve the situation, usually involving going to the forums and requesting people get repobanned, or leaving feedback on collabs who don't check for this. In addition, the PR that allows line outside of October has a new poll going on it. Remember to log in the server and vote.
> 
> adacovsk makes a lot of good PRs, I don't want to request him to be repobanned just because of his Linestation memes

Ya exactly, so a revert is the ideal move. Adam has done a great deal of good work for the code and I appreciate him.

**Comment by Eneocho** [comment]
Linebros will never bend the knee.

**Comment by kernikov** [comment]
Reminder that the creator of line literally accused me of "grudging" his map by bussing on it, because it stopped people from "enjoying" it

**Comment by Eneocho** [comment]
I can't see this and the primetime revert PRs as nothing else but reactionary complaint PRs after a few rounds of line, same thing that happens after 3 rounds of snaxi and someone wants it removed or limited. 
Let us have the fucking line same way you have your fucking isolation gimmick map (snaxi), it is fair.

**Comment by Eneocho** [comment]
image

**Comment by ShiftyRail** [comment]
I don't like how a map meant obviously as a joke managed to be voteable and I don't like the fact there's been persistent, sort-of-stealthy attempts at creating a majority for it when there's not one in practice. Line should simply be a meme map in October in my opinion.

**Comment by Theophrastus1** [comment]
> I can't see this and the primetime revert PRs as nothing else but reactionary complaint PRs after a few rounds of line, same thing that happens after 3 rounds of snaxi and someone wants it removed or limited. Let us have the fucking line same way you have your fucking isolation gimmick map (snaxi), it is fair.

wasn't snaxi only able to be voted on after a certain temperature condition was met outside of bussing? linestation sucks chump get over it, it should be relegated to the month it was in the first place instead of this "hey i made this PR that lets you vote on ALL compiled maps, and also mine (tee hee)" funny business going on

**Comment by ShiftyRail** [comment]
@Theophrastus1 Snaxi is votable 4 months of the year : November, December, January and in July (Australian Christmas).
The temperature check would give us Snaxi as early as October sometimes and as late as March.

**Comment by nervere** [comment]
> wasn't snaxi only able to be voted on after a certain temperature condition was met outside of bussing?

You are thinking of IceBox which requires the average station temperature to be below 0 celsius.

**Comment by WindowsErrors** [comment]
> > I can't see this and the primetime revert PRs as nothing else but reactionary complaint PRs after a few rounds of line, same thing that happens after 3 rounds of snaxi and someone wants it removed or limited. Let us have the fucking line same way you have your fucking isolation gimmick map (snaxi), it is fair.
> 
> wasn't snaxi only able to be voted on after a certain temperature condition was met outside of bussing? linestation sucks chump get over it, it should be relegated to the month it was in the first place instead of this "hey i made this PR that lets you vote on ALL compiled maps, and also mine (tee hee)" funny business going on

AI, convert their entire argument to angry crying or ugly wojaks and reply

**Comment by pedr69** [comment]
how about a server vote where people can vote on which maps they like
bring an end to linechad-snaxitard war?

**Comment by WindowsErrors** [comment]
listen bro, we just like line station, is that too much to say?

**Comment by ShiftyRail** [comment]
Well for me Line being available in October and Snaxi in the Winter is more than enough.

**Comment by Theophrastus1** [comment]
because you're mine, i walk the line

**Pull request merged**
