### PR TITLE
Summon spells are now challengey spells

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
They no longer create antags and instead only arm the crew with whatever was summoned, but now they instead **give** spell-points when summoned.
All 3 are **one-time** use.
Summon Guns and Summon Spells will grant 20 points, while Summon Swords grants 10 points for a total of 50 extra points.
I made this partly because I like the concept of wizard challenges for extra points and partly because at least a few people don't like premature round ends caused by a survivor or two deciding to survive by killing everyone else.
Also added a spellbook thing where if the price is negative it will tell you that you can gain points instead of that it costs points

Q: Wouldn't that give the crew enough self-defense tools to defend themselves against antagonists, thus making any existing antagonists antagonized by the wizard and inactive?
A: The same thing happens if the round survives the survivors, the round's dynamics have already changed by summoning stuff.
Q: Is this a good change?
A: I dunno, I'm not a good judge of quality even if I like to shitpost about how much of a good judge of quality I am.
Q: What's with the Q&A?
A: Hoping that it might elaborate some things but honestly I can't think of many questions and answers

:cl:
 * rscadd: The roundstart wizard's summon spells no longer create any survivors, but instead give the wizard up to 50 extra spell-points if all 3 are summoned.

### CODE REVIEW

**Comment by d3athrow** [comment]
bruh

**Comment by salamandooo** [comment]
I like the idea of changing Summon Guns/Spells, but because those extra points are so alluring (for new gimmicks which require many spells), and also because people like a challenge, I fear that nearly every wizard round is going to result in guns/spells being summoned and gunking up the round.

**Comment by boy2mantwicethefam** [comment]
Yea honestly I don't have hopes for the change but it's an idea I am throwing

**Comment by ThatRedPyro** [comment]
Feels like every round would be a survivor round because why not get free points

**Comment by boy2mantwicethefam** [comment]
@salamandooo @ThatRedPyro good points, the initial reception is bad so I am going to use this as an excuse to close it

**Comment by ShiftyRail** [comment]
This completely removes survivor as a concept. I don't think this a good idea.
This makes other antags much weaker because everyone will have guns to stop them.  I don't think this a good idea.
This gives most wizards 150 free points in exchange of making the round a stalemate when they die. Same as above.

>Yea honestly I don't have hopes for the change but it's an idea I am throwing

Then why bother with a PR at all ? You can be open to criticism, but making a passive-aggresive comment like that is just... :thinking:

**Comment by boy2mantwicethefam** [comment]
It's not meant to be passive aggressive

**Comment by DamianX** [comment]
One of the dumbest things I've ever seen

**Comment by Exxion** [comment]
I don't hate the idea of challenges to get more points, but I don't think this is the place to put them
It would make more sense to handicap the wizard than to boost the crew

**Pull request closed without merging**
