### PR TITLE
Adds the door-hacking sounds to the jukebox

### PR DESCRIPTION
**Pull request by Kharkov72**
You know, cut wire on cutting a wire, the boop on a pulse.
This has brought up the fact that it sleeps when you pulse the radiation wire so no more booping until it wakes up, I probably won't touch that but I'm going to sleep on it.
[Sound]
This was a request I was happy to oblige

Update: I won't remove that sleep because I like it not reacting for a moment to pulsing giving you a sign that hey you just got FUCKED by rads.

:cl:
 * soundadd: Hacking the jukebox now makes sounds!

### CODE REVIEW

**Comment by Durgen** [comment]
If you are fucking with jukebox hacking, there is a notable bug worth mentioning.
You can’t bring up the wire menu by multiooling with an open panel. You can only pulse wires by bringing up the wires using wire cutters, then switching to a multitool.

**Comment by Kharkov72** [comment]
I believe that's a feature, so you can connect it to the sound systems.
Even if it isn't, I can't think of a better solution.

**Comment by Kurfursten** [comment]
Why not just do this in the parent and call ..() for all stuff with wires?

**Comment by Kharkov72** [comment]
sure hell with it I'm going balls deep
I'll make that another pr though for transparency

**Pull request closed without merging**
