### PR TITLE
Let MoMMIs use microwaves and bartending machines

### LINKED ISSUE #22642: MoMMI can't interact with bar dispensers
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
1f131da8bd4dfb55546a640abc52a4859cb79461

# Description
MommI are unable to interact with bar dispensers in any way and there is no module apparent to enable them to do so
# Steps to Reproduce
Use bar-placed dispenser as MoMMI with or without shaker
# What you Expected
Access to shaker
# What Actually Happened
"Your programming forbids interaction with this device." According to Otatoh, there isn't a way to enable interaction.

### PR DESCRIPTION
**Pull request by FudgePucker**
Why can't MoMMIs use microwaves?
Is it not improving the station to have something to eat other than stuff from a vending machine?

Edit: I removed the change log so it wouldn't duplicate 
Edit2: closes #22642 an issue made after I made this PR.

### CODE REVIEW

**Comment by brndd** [comment]
you're going to duplicate the changelog with this, you only need either the opening post :cl: stuff or the file-based changelog.

**Comment by RealestEstate** [comment]
great now I can make pots as a mommi again

**Comment by aceedex** [comment]
Really mommi, my burger?

**Comment by ShiftyRail** [comment]
#18503

MoMMis shouldn't be seen

**Comment by SonixApache** [comment]
mommicreep

**Comment by Zth--** [comment]
Yes please

**Comment by jknpj** [comment]
Why, yes, i always wanted to have yet another reason to not play service

**Comment by FudgePucker** [comment]
I am still nostalgic for when MoMMIs had the behavior of a cyborg shaker. You could mass produce drinks.

Nothing is stopping MoMMIs from bartending. They can still use the booze mat and mix drinks by hand. But the other round when I was fixing up and renovating the ghetto bar someone had already taken it. Cargo was abandoned and you cant accept orders or send/call the cargo shuttle. Mechanics were jerks so I couldn't just scan and print out a new booze mat. 
Oh well, at least I can use the protolathe to create the bartending dispensers, oh wait. Guess I'm serving nothing but beer.

**Comment by ShiftyRail** [comment]
Maybe something that can do everything a silicon or a carbon can do but better was a bad idea.

**Comment by brndd** [comment]
They can't talk and have next to no combat ability and aren't even allowed to do combat (except when emagged, I guess), so I don't think it's that big of an issue.

It would be good to uncuck service cyborgs though because they'll be even more useless after this.

**Comment by FudgePucker** [comment]
@ShiftyRail
They only get one hand, no storage slots, and have very low health.
They also don't get a power based RCD, and can't get upgraded. Only real thing a MoMMI has over a engineering cyborg is being able to load plasma tanks into radiation collectors, and vent crawling.

**Comment by kernikov** [comment]
@FudgePucker 
>Only real thing a MoMMI has over a engineering cyborg is being able to load plasma tanks into radiation collectors, and vent crawling.

...and free plasma r-glass, and the ability to go mine 1 of gold/silver/uranium/diamond to scan and synth to make El Dorado, and the ability to do research to get free gadgets, and the ability to do all steps to get themself an ultra cell and personal upgraded charger to take everywhere and the ability to do all steps to give themself VTEC, and the ability to make advanced machines, and the ability to ignore humans when they want to, and the ability to interact with humans when they want to...

Silicons are basically for SecBORG validhunting, minerborg domination, and maybe mediborg if you want to partake in the wildride.
Service is cucked.
Engy is worse in every way tbh.

MoMMIs OP.

**Comment by FudgePucker** [comment]
MoMMIs can only scan plastic and wood. Engiborgs can scan anything.

**Comment by FudgePucker** [comment]
Also an engiborg can just ask for an upgraded cell. And will get one if it does a little bit of material whoreing.

**Comment by Caboozles** [comment]
What? MoMMis can scan any material and can upgrade their own cell as they please. Just screwdriver a borg charger and plug that bad boy in.

I mean, I’m all for microwaves, but they really are superior.

**Comment by FudgePucker** [comment]
Wait, can they? I thought that ability was removed?

**Comment by AutismSpider** [comment]
nothing stopping  engi borg form scanning plasma glass windows at toxins or the gold in the vault  etc

**Comment by Kitfox88** [comment]
m*mmiclub at it again, powercreep, plz ban

**Comment by jknpj** [comment]
>MoMMIs can only scan plastic and wood. Engiborgs can scan anything.

>
	var/list/can_scan = list(/obj/item/stack/sheet/metal,
							/obj/item/stack/sheet/glass/,
							/obj/item/stack/sheet/wood,
							/obj/item/stack/sheet/plasteel,
							/obj/item/stack/sheet/mineral)

Both mommis and cyborgs can scan the same things. But they get different starting loadouts:

	materials_scanned = list("metal" = /obj/item/stack/sheet/metal,
							 "glass" = /obj/item/stack/sheet/glass/glass,
							 "reinforced glass" = /obj/item/stack/sheet/glass/rglass,
							 "floor tiles" = /obj/item/stack/tile/plasteel,
							 "metal rods" = /obj/item/stack/rods)

>
	materials_scanned = list("metal" = /obj/item/stack/sheet/metal,
							 "glass" = /obj/item/stack/sheet/glass/glass,
							 "reinforced glass" = /obj/item/stack/sheet/glass/rglass,
							 "plasteel" = /obj/item/stack/sheet/plasteel,
							 "plasma glass" = /obj/item/stack/sheet/glass/plasmaglass,
							 "reinforced plasma glass" = /obj/item/stack/sheet/glass/plasmarglass)


Plastic is a mineral sheet, reinforced plasma glass is still glass. the only REAL difference between both of them is that the engiborg version CAN'T scan these:

>
	cant_scan = list(/obj/item/stack/sheet/mineral/clown, /obj/item/stack/sheet/mineral/phazon)

**Comment by FudgePucker** [comment]
It's been over 72 hours and has more :+1:s than :-1:s so I think it's ready to merge.

**Comment by SonixApache** [comment]
based newfags upvoting changes that have been tried and shot down in the past

**Comment by FudgePucker** [comment]
Now it closes an issue as well

**Comment by SonixApache** [comment]
put `fixes #22642` or `closes #22642` or `resolves #22642` in the OP if you want the issue to actually auto-close when the PR is merged
maybe make your changelog slightly more verbose for the players

**Comment by FudgePucker** [comment]
Will do tonight.

**Comment by FudgePucker** [comment]
There I made a better change log.

**Comment by kernikov** [comment]
MoMMIs shouldn't be "bartending" or doing anything with food as silicons.

**Comment by FudgePucker** [comment]
That's your opinion man.
Sure, if a MoMMI barges into the kitchen or bar while there is already some one running it there's a problem. But that isn't a coding issue, it is an administrative issue.
Not only that, there are non food recipes in the microwave. Like @RealestEstate pointed out, you cant make pots as a MoMMI. You wanted to improve the station with some potted plants? Fuck you, the anti MoMMI meta club said no fun today.
MoMMIs not being able to use the bartending machines made sense... MADE. Sure, who would want to play as a bartender and need to depend on other people to get the cool dispensers, or just play MoMMI and get them EZ. But hey guess what? They are now round start in the bar. There is also a reason to pick bartender over MoMMI, when some assistant comes in and starts throwing all your drinks at you, when you are a MoMMI all you can do is *buzz, bartenders can shoot them, stab them to death with a broken bottle, and gib their corpse. Also talking back, I forgot about the power of speech outside of pinging beeping and buzzing.
>Wow I was having a fun round, up until I ran into a conveyor sushi restront made in the vacant office by a MoMMI, now my round, and day, is ruined.

**Comment by FudgePucker** [comment]
Do you want me to add a reminder to follow your laws to the change log? Would that satisfy you?

**Comment by jknpj** [comment]
If this is an administrative issue, i'll leave for the headmins to say if the admin team want to deal with bartending mommis or not.

**Comment by Kammerjunk** [comment]
@GeneralVeers25 apparate

**Comment by Kurfursten** [comment]
I talked to the headmins, Foster approves, Veers doesn't like it. Both make good points.

We'll just need to crack down harder on people who do interact but allow this to go through, I think.

**Pull request merged**
