### PR TITLE
IJzerkoekje

### PR DESCRIPTION
**Pull request by SysadminJeroen**
# IJzerkoekje

IJzerkoekjes (translated: Iron cookies) is a Vlaardingse cookie, it doesn't actually contain iron in real life.

This PR has been made because I'd like to see this food implemented as a reward for [donating blood at Dr. Acula](https://github.com/d3athrow/vgstation13/issues/10181).

Sprite: IJzerkoekje
IJzerkoekje
Thanks @DeityLink for the sprite!

[Wikipedia article](https://en.wikipedia.org/wiki/IJzerkoekje)
[Real IJzerkoekjes](https://upload.wikimedia.org/wikipedia/commons/3/3d/IJzerkoekjes.jpg)
## Recipe

_Produces 6 IJzerkoekjes_
IJzerkoekje 30 flour
IJzerkoekje 30 iron
## Nutritional value

_Per IJzerkoekje_
IJzerkoekje 5 nutriment
IJzerkoekje 5 iron
## Other

This code has been tested.
Big thanks to both @DeityLink for the sprite and @Kurfursten for showing how to spawn more than one item from the microwave.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Looks like a stroopwafel to me

**Comment by SysadminJeroen** [comment]
@ComicIronic Yeah, I am not good at spriting, could give it another attempt.

**Comment by Shadowmech88** [comment]
I think they just need to be made a little more pill-shaped and less circle-shaped. A bit thicker as well.

**Comment by SysadminJeroen** [comment]
@ComicIronic, @Shadowmech88: Is this better? ijzerkoekje

It is way better in my opinion, but not perfect.

**Comment by Shadowmech88** [comment]
It's definitely better.

**Comment by SysadminJeroen** [comment]
@Shadowmech88 
CC: @ComicIronic 

What about this one?
ijzerkoekje_v3

What I did is cut out an IJzerkoekje from a picture, rotated it and re-textured it.

**Comment by Shadowmech88** [comment]
That one looks better perspective-wise.
Could be better, but it's the best so far. Certainly acceptable by the standards of our food sprites, I think.

**Comment by DeityLink** [comment]
The size isn't the problem. There's no shading at all.

**Comment by DeityLink** [comment]
3 minutes in Gimp using your original sprite as reference:

ijzerkoekje

ijzerkoekje_bigger

**Comment by Shadowmech88** [comment]
Very nice.
Should be more elongated though, to match more closely to real ones.
image

**Comment by DeityLink** [comment]
Like this?

ijzerkoekje2
ijzerkoekje2_bigger

**Comment by SysadminJeroen** [comment]
@DeityLink: Thanks for the help, I am not that good with image editing.
The last one looks pretty good, can you send me the original file so I can overwrite the last one?

**Comment by DeityLink** [comment]
The small one in my previous post is the original file. It's a png with transparency.

**Comment by SysadminJeroen** [comment]
@DeityLink: Oh yeah, I see. Google Chrome Anti-Aliased the fuck out of the image.

**Comment by DeityLink** [comment]
And that's why I still use Firefox.

**Comment by SysadminJeroen** [comment]
I have done multiple attempts to spawn six IJzerkoekjes from the recipe, but I couldn't figure it out.
If anyone knows how to, let me know.

**Comment by Shadowmech88** [comment]
As far as I know, we don't have any recipes that spit out multiple items. It may not be possible with our current microwave code.
The closest thing to it is the slider recipes, which produces a single "box of sliders," containing seven sliders.

You'd probably have to do something like that.

**Comment by Kurfursten** [comment]
@Jeroen52 
http://hastebin.com/rugofuvuci.pl

**Comment by Iamgoofball** [comment]
@Jeroen52 
make it spawn a dummy item that when it spawns, spawns 6 cookies

**Comment by Kurfursten** [comment]
20 minutes late goof

**Comment by SysadminJeroen** [comment]
@Kurfursten: It doesn't seem to spawn any IJzerkoekjes, it does empty the microwave of all the ingredients.

**Comment by Kurfursten** [comment]
That hastebin has some typos, new() should be New() and for(1 to 6) should be for(var/i = 1 to 6) I have tested this to confirm it does work if you fix the typos.

This is why you shouldn't code right before sleeping

**Comment by SysadminJeroen** [comment]
@Kurfursten I have noticed that I shoud've changed `new()` to `New()`
I'll edit the for-loop once I arrive home.

**Comment by SysadminJeroen** [comment]
Alright, I got it working.
Thanks @Kurfursten.

Now the grand question is if I should give it 7.5u iron or keep it at 5u. If I change it from 5u to 7.5u I should also change the recipe.

**Comment by SysadminJeroen** [comment]
Shall I squash the commits or leave the history intact?

**Comment by Shadowmech88** [comment]
No need to squash, Github auto-squashes upon merge now.

**Comment by SysadminJeroen** [comment]
@Shadowmech88 Seems like Github has a reputation of rewriting history lately.

**Pull request merged**
