### PR TITLE
buying the wizard hardsuit gives you a gem-encrusted oxygen tank

### PR DESCRIPTION
**Pull request by Arthurdentist**
I made a comment about it but I think this is a more elegant solution to the problem bought up in #22160  compared with just giving wizards no breathing.

<sprites>
:cl:

 * rscadd: Wizards who purchase a gem-encrusted hardsuit will now get a gem-encrusted oxygen tank to go with it.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I like this variant but it will show up in-hand as a blue oxytank (and maybe the back too) because it only has a sprite on how it looks like

**Comment by Arthurdentist** [comment]
thats a good point, I'll sort that other sprite out later today @boy2mantwicethefam

**Comment by DrSnips** [comment]
I think the whole point of the no breathe PR was to free up the armor slot for staffs and such. Maybe making it a small item or whatever it takes to fit in a pocket would be good. Making it a child of the double yellow E-tanks would allow for that.

**Comment by Hoshi-chan** [comment]
Hey, Arthur, don't forget to give them a mask, too.

You know, to breathe the oxygen contained inside the tank.

**Comment by RealestEstate** [comment]
wizards get an internal box iirc which has the mask

**Comment by Kurfursten** [comment]
What about a Gem Encrusted Rebreather? Basically a gas mask that contains its own tank

+ No need for tank taking up slots like NOBREATHE thing
+ Can still be removed unlike the NOBREATHE power, which I think was the point of contention
+ Totally unique so it makes for cool wizard loot

**Comment by press-mark** [comment]
the only problem I see is that the suit storage slot will be taken up when in use, so the wizard can't put their staff there

**Comment by Kurfursten** [comment]
No I mean it literally contains its own air tank, not it creates an air tank in the suit storage slot. You only need your mask slot.

**Comment by Arthurdentist** [comment]
Alright, I changed the tank type to the double-emergency sort, gave it a new sprite to fit, and did the inhands. Haven't actually tested this to make sure it all works, but I'll do that in a second and it should be good to go

**Pull request merged**
