### PR TITLE
Loadouts

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds the `/obj/abstract/loadout` type, and removes the `/obj/item/complete` type in favor of it.
The `loadout` type will be abstract objects which serve to spawn a series of items in their loc, then delete themselves.
References to the loadout's spawned items can be obtained in the form of a list by calling `get_items()` on it within a second of its creation (at which point it spawns the items itself and is then deleted).
The `loadout` type can also be fed a mob argument in its `New()` to spawn and then automatically equip its items to that mob. 

This PR also adds an "Equip Loadout" admin button to admins' right-click window. It allows them to choose from a list of existing loadout types to equip to the selected mob.
Alternatively, the admin can choose to use the items on their current turf, which will make a list of all the items on the admin's turf (not including the contents of those items), spawn new copies of them all, and equip them to the selected mob as though they were a loadout. This should hopefully make it easier for admins to outfit custom teams without having to manually make six identical piles of items.

When equipping a loadout to a mob, all the mob's current items are unequipped and dropped on the ground below it before the loadout is equipped.

### CODE REVIEW

**Comment by SonixApache** [comment]
not the loadouts I was expecting, but still nice QoL shit

**Comment by Orangerush** [comment]
rused

**Comment by Intigracy** [comment]
`Alternatively, the admin can choose to use the items on their current turf, which will make a list of all the items on the admin's turf (not including the contents of those items) and equip them to the selected mob as though they were a loadout.`

Just to be sure, you mean you're making a list and then spawning a new copy of each item in the list to equip, right?

**Comment by Shadowmech88** [comment]
Correct.
I'll change the OP to make that more clear.

**Review by Intigracy — DISMISSED** [review]
I was going to merge this but then I remembered that select equipment also exists on right click for admins.

Merge the two please.

**Comment by Shadowmech88** [comment]
The functionality of the two is a bit different in that `Equip Loadout` attempts to dynamically equip the chosen items to appropriate inventory slots, while `Select Equipment` directly equips specific items to specific inventory slots. I don't see any way to combine this functionality.

I can still make the `Select Equipment` sets into loadouts and add an option to `Equip Loadout` for whether to strip the mob and/or delete its items before equipping, but is it acceptable that it won't be capable of equipping specific items to specific inventory slots?

**Comment by Intigracy** [comment]
Yes.

**Comment by Shadowmech88** [comment]
It seems many of the equipment sets in `Select Equipment` make use of the fact that the equipment is known at runtime by altering the spawned items on the fly, such as changing the name, adding reagents, deleting contents, et cetera. The loadout system can do none of this.

Should I proceed with combining them and simply ignore such instances?
Or must I add new child objects for each such instance, which have the altered properties by default, so that they may be spawned that way by the loadout system?

**Comment by Intigracy** [comment]
Children sounds like the best option.

Sorry for adding more work, but the two verbs are similar enough that it's pretty dumb to have both in right click

**Comment by Shadowmech88** [comment]
I just realized that I can access the spawned items at runtime by overriding the loadout datum's `equip_items()` proc, so it turns out we won't need children for *all* cases, like the bloody items equipment set.
I'll probably leave in most of the children I've made though, because why not?

**Comment by Shadowmech88** [comment]
This should be done now, I think.

**Pull request merged**
