### PR TITLE
NT Port can be closed to trade

### PR DESCRIPTION
**Pull request by Kurfursten**
untitled

Traders have gotten a lot of buffs lately. I think it's only fair that NT get some tools to fight back against nuisance traders. With this change, traders will need to at least behave themselves well enough that they don't get the BEGONE THOT treatment. If the trade shuttle is docked at NT station when the port is closed, it is automatically sent to a random port on its docking list (usually the outpost but can be either port on metaclub).

I plan to do a followup PR to give IAAs a little leverage over traders as well.

🆑 
* rscadd: The communications computer can now be used to close off the station dock from traders, requiring an ID with HoS access or head access during a red alert. The same access is required to re-open the port.
* rscadd: Admins can now use the communications computer and all its features.

### CODE REVIEW

**Comment by Durgen** [comment]
😱

**Comment by bathosbathtime** [comment]
This is a change that I like.  Is there anyway for admins to toggle the port while an aghost, or will it have to be done by spawning a test dummy at central command?

**Comment by TurboGay** [comment]
I'm of the opinion that the HoS access shouldn't be enough to trigger this lockdown for the sole reason that as soon as any sort of suspicious activity happens, regardless if traders are the source of it or not, trader ports will be locked down. Selling things during a crisis is a great part of the fun I have playing trader and it would be unfortunate if these situations would be less common as a result.

I would support this change greatly if it was only the head access during the red alert only that could trigger the lockdown as there would have to be some greater justification for moving the code to red and more cooperation by the head players involved to make the decision of whether to lock down the port or not since red alert requires multiple head level ids or players in order to activate.

I would much rather have meaningful set in stone policy regarding traders on the server, but this could do in the meantime.

**Comment by Kurfursten** [comment]
There is no averb for it but I could add one (or add it to the admin panel), not that I necessarily think this is something admins should need to do?

What kind of situation are you imagining where an admin needs to step in and directly close the port in which it's not better for the players to do it themselves? Maybe I'm overlooking something?

**Comment by Accipitermaris** [comment]
The other day I learned that you can't deconstruct the Vox Shuttle console unlike the Mining Shuttle, or the Research Shuttle, so there really is no way to discontinue your relationship with the Vox Traders without personally capturing or murderizing them all even if you capture a valid ID/their shuttle. So I'm definitely in support of this PR if we're not going to change that (or magic "Vox Trader" access that cannot be acquired on any ID Console. IIRC borgs can access it though, which is a laugh.)

**Comment by bathosbathtime** [comment]
While I don't think that there is any situation that an admin would need to close the port, I can see the possibility of an admin needing to open it.  A hos rushing the bridge and closing the port round start might be an issue.

**Comment by Kurfursten** [comment]
Ah, yes, that makes sense. Good thought.

I should add that the closing/opening port is both logged AND sends an admin warning, with the reason they provided.

**Comment by Durgen** [comment]
If merged this would need some server policy about when it is okay to use.
- Can you lockdown because a trader slips a clown?
- Can you lockdown if one trader is being shit, but two others are chill and trading from the shuttle?

There is also a lack of consistent server policy in general regarding the rights or lack thereof of traders which should be clarified.

**Comment by Accipitermaris** [comment]
@Durgen yeah for whichever reason we tend not to write any new rules down & just leave them as “House Rules” which not necessarily all admins are gonna know about
Related threads:
http://ss13.moe/forum/viewtopic.php?f=27&t=2518
http://ss13.moe/forum/viewtopic.php?f=4&t=2573

Shouldn’t be too bad here because it’ll be obvious when the Captain is being a jerk but the “What is the /actual/ policy regarding Traders and Space Law?” question is still valid

**Comment by Durgen** [comment]
@Accipitermaris I pinged Foster about this subject earlier today on discord. Perhaps I'll make a forum thread about it as well.

**Comment by ghost** [comment]
Admins should have a button to reenable it in situations of metagay and just people being assholes for no reason. Shouldn't be hard to add.

**Comment by Allspice** [comment]
There was some minor noise in the thread about blocking traders as a matter of course when code red hits, and that sentiment seems to be bubbling up here. Just as a reminder, here is what the wiki states as the code red SOP:

SOP

It seems well within the spirit of this, for sec to not want to bother babysitting some shitty gypsies. Note: Declaring code red for no particularly good reason is a separate issue from forbidding traders after code red, because one affects people who actually matter (the crew).

**Comment by Durgen** [comment]
@Allspice The IC justification makes sense, but it would suck for your round to be over just when things are getting FUN.

**Comment by Arthurdentist** [comment]
@Kurfursten I like the change but I feel that it is a power the HoP should have. I think they are more closely associated with 'supply' and organising departments / IDs so I think it would be a better fit for him. 

Almost might be cool to have a way for traitor vox to ignore this warning.

**Comment by ghost** [comment]
Make a teleporter with their shitty gypsy superbase?
They also have GPS and jetpacks so it's whatever.

**Comment by Kurfursten** [comment]
I could be wrong but I believe a traitor Vox could just emag the mining or research shuttle, a solution which is far more versatile because it leaves you with an emag you can use on all kinds of stuff.

**Comment by jknpj** [comment]
Antag traders were a mistake. Having a private rape dungeon with no cameras, exclusive access, blood, basic medication, plants, security tool, a personal way to move from the station to your rape dungeon at will AND antagonist target immunity?

I welcome this as a decent way for the station to halt of at least slow down them if they do become a treat. Just add captcha or something so silicons can't abuse it.

**Comment by Durgen** [comment]
@jknpj >AND antagonist target immunity?
Everyone agrees this is dumb, but no one has bothered to change the single line of code that would fix this.
It's code\game\gamemodes\objective.dm line 19

**Comment by ghost** [comment]
It's dumb but it doesn't have a good solution because the only alternative is mandatory pda pointer and jetpacking around space to find them which is still opposite of the antagonists role to create action in the round. But hey, say you found and killed him in space vault 6969, it's fucking nothing. A lot of people can handle recognizing that it's a stupid objective and go do anything else instead but many can't. If they want to antagonize the fuck out of the traders and a general race war, their antag ticket lets them do it, they don't need an objective to do so. It's just removing a needless negative from the worst of the playerbase for the betterment of everyone

**Comment by Kurfursten** [comment]
Assassinate objectives shouldn't even exist for reasons I'd be happy to elaborate on in a separate issue. I have some strong opinions about the matter and ideas how to improve the objective system overall - but this isn't the proper time or place.

**Comment by BurntDevil** [comment]
What about IAA/Bridge Officer access to this feature? Or is that something you plan with the IAA follow up?

**Comment by Kurfursten** [comment]
What's new?
* Admins can now interact with the communications console. Meaning they can conveniently change alert level, call/recall shuttle, and toggle port status all in one place without the hassle of digging through menus.

@BurntDevil I have something different in mind for IAAs, a carrot rather than a stick to encourage good behavior.

**Comment by Kurfursten** [comment]
As a general reminder this is good for review or merge. Perhaps best to wait for April 2 to avoid confusion though.

**Comment by Aurx** [comment]
Merge it now, revert it on the 2nd, merge it again after review.

**Pull request merged**
