### PR TITLE
Hopefully fixes Genfab and Reverse Engine

### LINKED ISSUE #7428: device analyzer / reverse engine issue
on the wiki, the [Guide to Mechanic](http://ss13.pomf.se/wiki/index.php/Guide_to_Mechanic) says that you can scan health analyzers, advanced trauma kits, advanced burn kits, emergency defibrillators and Health Scanner HUDs, if you try to scan any of these items it says

> You successfully scan [item's name]

but when you use the analyzer on the reverse engine it says

> Sucessfully transferred 0 designs.

therefore you're unable to obtain blueprints for such items. i don't know if there are other items with the same issue.

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #7428
Comic has a very interesting way of working on top of his own previous projects
Tested this with all fabricators and they seemed to work correctly.

### CODE REVIEW

**Comment by CptWad** [comment]
fuck yeah now I can scan shit

**Comment by 9600bauds** [comment]
To do in my Comic list:
- Make the genfab not awful
- Fix autolathe bullshit that presumably was never tested

**Comment by clusterfack** [comment]
Hopefully fix? That's my line!

**Comment by 9600bauds** [comment]
[VGTA]

**Pull request merged**
