### PR TITLE
Moving all in-hand space suits and space helmets icons to a single dmi per hand

### PR DESCRIPTION
**Pull request by DeityLink**
and add the missing helmet sprite for the default spacesuit helmet.

### CODE REVIEW

**Comment by DeityLink** [comment]
what the fuck Travis?

**Comment by ghost** [comment]
Shouldn't the exact opposite be done? Having large dmi files is what causes problems down the line, making them unchangeable in dreammaker.

I didn't actually check how large these are, just mentioning that it's already a problem for botany plants.

**Comment by DeityLink** [comment]
The problem was having ALL the sprites in a single dmi file. As long as you don't need to scroll to check a dmi it's fine.

**Comment by DeityLink** [comment]
@codeungabunga for instance on my resolution, hydroponics.dmi has 4 screen-fulls of icons, while all spacesuits take half a screen. The limit isn't that small, suit.dmi has 3 screen-fulls of 4-directional sprites.

Either way having a single dmi for TWO sprites is the other extreme.

**Pull request merged**
