### PR TITLE
[POMF PLS] Compile under 510 + overlays for 510 + use tick var instead of btime

### PR DESCRIPTION
**Pull request by gbasood**
in which I steal PJB's 510 work and tg's 510 work (tgstation/-tg-station#14981) and make it work

Also I stripped the debug ifdefs out of lifecode

Going to need a lot of review because it touches on SO MANY FILES but mostly for mob overlays since there's no more global hud and I had to change all of that

https://github.com/d3athrow/vgstation13/pull/8447/files?w=1 Most of this shit is whitespace.
### Performance report

http://a.pomf.cat/obyjnr.mp4
With 378 instances of roaches, CPU would spike to ~18 per roach tick.
http://a.pomf.cat/nbdbkb.mp4
Explosions seem to be faster, too, somehow. Hard dels are still really slow though, which I found out trying to hard del roaches
And while they ARE, probably, faster, they aren't magically fast like Goon claimed they were
http://a.pomf.cat/ahszlx.mp4

### CODE REVIEW

**Comment by gbasood** [comment]
I tested the overlays for humans and they all work as expected from what I could tell, but someone else should review those still

One small change in particular to telecomms code may or may not fuck everything up

**Comment by gbasood** [comment]
Also, startup times seem to be considerably faster under 510. Which is very interesting.

**Comment by gbasood** [comment]
Just noticed that I can't seem to use verbs on certain things via right-click, like blood. What the fuck

**Comment by AlphaBuffalo** [comment]
To be expected when fixing shit old code :/

**Comment by gbasood** [comment]
Can't reproduce the failure to build, builds fine locally.

I also don't see the line Travis is talking about
what

**Comment by clusterfack** [comment]
Replace all instances of list2text with the inbuilt Join() proc

**Comment by gbasood** [comment]
@clusterfack But the file it's erroring on doesnt' even HAVE a list2text call in it

**Comment by gbasood** [comment]
oh good it got even uglier with a merge rebase

**Comment by gbasood** [comment]
http://www.byond.com/forum/?post=2042462
ayyy

**Comment by gbasood** [comment]
now that the update for that issue finally went in,
BACK IN BUSINESS
Outstanding bug(s):
- [x] Flash ~~and nearsightedness~~ were absolutely non-functional due to how they worked before.

So the things that mostly need testing for this would be overlays in general. Make sure all fullscreen overlays display properly for all mob/living/carbon/humans

**Comment by ihadtoregisterforthis** [comment]
Test
Serb

**Comment by gbasood** [comment]
can't run a test serb through Pomf's stuff because it's 510 and the serb won't load that by default

**Comment by gbasood** [comment]
So far I've re-done eyeflash code for flashes, flashers and flashlights.
I still need to hunt down all instances of eye flash code that we have and replace them
Why the fuck was this spaghetti'd out so hard in the first place holy shit

**Comment by ninjacha** [comment]
AI is broken yo, i can only see my AI mob.

**Comment by gbasood** [comment]
As in camera viewing doesn't work?

**Comment by gbasood** [comment]
More bugs:
- [x] MoMMIs start blind.

**Comment by gbasood** [comment]
@ninjacha Can't reproduce, need more info.
- Did you manually download and test this PR specfiically?
- Were you using BYOND version 510.1329? (As opposed to 509 or an earlier revision of 510)
- What steps could I take to reproduce that?

Unless you mean non-AI silicons?

**Comment by ninjacha** [comment]
I downloaded this PR, joined as AI, and could not move my camera around.
Latest 510.

**Comment by ninjacha** [comment]
Basically the MoMMI bug.

**Comment by gbasood** [comment]
Well, still can't reproduce that, so neato

**Comment by gbasood** [comment]
Only like 3 conflicts when rebasing this time neat

**Comment by gbasood** [comment]
Maybe I won't have to rebase with that commit now

**Pull request merged**
