### PR TITLE
Reformatted special roles menu

### PR DESCRIPTION
**Pull request by ghost**
image
[ui][role][formatting]

## What this does
Replaces the radio checkboxes on the special roles menu with normal buttons, removes the submit button for them (save setup inherits this functionality now) and cuts down some code.

## Why it's good
Looks nicer, works better on WINE, plus now works with save setup instead of unique case with having to press submit. Can change things about the menu look if anyone wants.

## Changelog
:cl:
 * tweak: Changing player special role preferences can now be done by pressing save setup at the bottom of the menu, instead of the old "submit" button. The menu has also been reformatted.

### CODE REVIEW

**Comment by west3436** [comment]
>looks nicer

**Comment by adacovsk** [comment]
If it makes the game more playable for Linux users, I think it's good

**Comment by pedr69** [comment]
now add a button to disable auto signup from deadchat(or limit it to having pref set to always, not yes)
i wanna have pulsedemon/grue set to yes, but if it means i'll be auto signed up that's fucking gay and dumb

**Comment by PavelCIA** [comment]
It's probably outside the scope of this PR, but there should really be an explanation of the differences between "Never" & "No" and "Yes" & "Always"

**Comment by ghost** [comment]
> It's probably outside the scope of this PR, but there should really be an explanation of the differences between "Never" & "No" and "Yes" & "Always"

I kept that legend, just not in the screenshot

**Pull request merged**
