### PR TITLE
Doppelganger tweaks/nerfs

### PR DESCRIPTION
**Pull request by ShiftyRail**
**What :** Nerfs Doppelgangers by limiting the simultaneous amount of them a wizard can summon to 15, and making them disappear naturally after 8 minutes.

**Why :** Doppel aren't fun to play with mostly because they stay in place almost forever after their wizard has gone to parts unknown. This aims to make them a little less spammable and a little less persistant. You'll need to conjure them again if you still want to condemn a zone.

This shouldn't remove their ability to cause chaos - 15 doppels is a reasonable amount, and 8 minutes a reasonable time. The chaos they cause should simply be less permanent.
This doesn't change their combat robutness and ability to stun people.

It seems also intended that Doppels should dissappear on their conjurer's death, _but_ I've never witnessed such a behaviour. It should be something to check/correct if needed.

Open to criticism/suggestions etc

:cl:
- tweak: A single wizard can only summon 15 Doppelgängers at the time, and Doppelgängers now naturally dissappear after 8 minutes.

### CODE REVIEW

**Comment by Irradiation** [comment]
That's nice and all, but you should add an extra Power upgrade that spawns a station-bounced radio right next to the doppelganger everytime you spawn one :^)

**Comment by DamianX** [comment]
too gentle 👎

**Comment by ShiftyRail** [comment]
I tested it, working as intended.

**Comment by Pathid** [comment]
How do their magic missiles travel at mach speed though? Is it some weird property of simple animals to do that?

**Comment by Blithering** [comment]
I would say to make the dopplegangers more fragile, enough so their fake death teleport could be believable as a injured wizard teleporting away

**Comment by ShiftyRail** [comment]
@Blithering a simple shift+click allows you to tell the cheap imitation from the real thing.

**Comment by Blithering** [comment]
Could that be changed? turn doppleganger from spam the npc army button into making a genuinely believable copy to throw people off your trail?

**Pull request merged**
