### PR TITLE
MoMMIs get a silicate sprayer.

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by Fruktlimpa** [comment]
Now for a soldering iron and the MoMMI's will reign supreme :^)

**Comment by ShiftyRail** [comment]
MoMMers will take are jerbs

**Comment by Hugh-G-Rection** [comment]
You were right before. The more things a MoMMi can do, the more incentive people who want to autism have to play them, which means less people in the round to interact with. Which is kind of the entire purpose of playing a multiplayer game in the first place, right guys?

**Comment by Kurfursten** [comment]
There is already a lot of incentive to play MoMMIs, all access, a protolathe, and no responsibilities probably being most prominent.

That being said, this addition is so small compared to the mat synth creep MoMMIs got, it practically doesn't matter by comparison and in my mind isn't even worth arguing over. MoMMI static when?

**Comment by PJB3005** [comment]
Yeah. MoMMIs are god damn OP but the silicate sprayer is not gonna change a damn thing. The only thing thing it'd change is that we'd see less damaged windows.

**Comment by SonixApache** [comment]
mommicreep

**Comment by Exxion** [comment]
Honestly the silicate sprayer is a textbook example of a tool MoMMIs should have
It's for repair and only repair

**Pull request merged**
