### PR TITLE
adds black crayons

### PR DESCRIPTION
**Pull request by SonixApache**
Tested. Pictured: Captain's gloves, insulated gloves.
black_crayons

:cl:
- rscadd: Added black crayons.
- tweak: Crayon boxes can now hold 7 crayons and include a black crayon.

### CODE REVIEW

**Comment by Blithering** [comment]
Is making black caps and black bedsheets functional?

**Comment by SonixApache** [comment]
image
Nope. Didn't know that was functionality.

Needs spritework, since the black cap and black sheet don't exist.

**Comment by SkowronX** [comment]
Ay hol up

**Comment by SonixApache** [comment]
Maybe just add black caps and sheets in a seperate PR.

**Comment by Blithering** [comment]
do black jumpsuit and shoes work at least?

**Comment by SonixApache** [comment]
Black jumpsuit did, tested that. Black shoes probably work as well. It's all super modular as long as the target object exists.

**Comment by Blithering** [comment]
Righto, I'll get to spriting the hat and blanket then

**Pull request merged**
