### PR TITLE
Fixes virus stage and clicks being carried over to copied viruses

### LINKED ISSUE #14145: "Suicidal Syndrome" is retardedly busted.
(WEB REPORT BY: kernikov REMOTE: 172.93.109.202:7777)
>Revision 70406da520eea6d365ed3740322ff484df9ec7c2 
>General description of the issue
'/datum/disease2/effect/suicide/activate(var/mob/living/carbon/mob)
	mob.suiciding = 1
	//instead of killing them instantly, just put them at -175 health and let 'em gasp for a while
	to_chat(viewers(mob), "<span class='danger'>[mob.name] is holding \his breath. It looks like \he's trying to commit suicide.</span>")
	mob.adjustOxyLoss(175 - mob.getToxLoss() - mob.getFireLoss() - mob.getBruteLoss() - mob.getOxyLoss())
	mob.updatehealth()
	spawn(200) //in case they get revived by cryo chamber or something stupid like that, let them suicide again in 20 seconds
		mob.suiciding = 0'

>What you expected to happen
A death that wouldn't permanently remove me from the game.

>What actually happened
Instantly unconcious in Crit after being hypersprayed with 5u of diseased blood and unable to be cloned.

>Steps to reproduce if possible
Become infected with a disease with the suicidal syndrome and observe that you've been effectively gibbed with the bonus of still being abled to get succ'd.

### PR DESCRIPTION
**Pull request by despotate**
fixes #14145

### CODE REVIEW

**Comment by stewartspicer** [comment]
Was this behaviour a bug? I always thought it was intended to work this way

**Comment by kernikov** [comment]
God, it better not be.

**Comment by eplgr** [comment]
After reading the code, I think we can say it was intended.

I don't think this is the right approach. Having to wait 60 minutes to get to stage4 is awful. This literally makes virology useless.

**Comment by Probe1** [comment]
It's more like 6 minutes than 60.

Also regardless of intent, the people who have coded viruses _since_ this was coded did not realize it worked that way and we have stacked incredibly lethal viruses in stage 4 with the design that they would take time to reach.

**Comment by Exxion** [comment]
Killing someone unrevivably instantly with no way to fight back is pretty shit, no matter how hard it is to get the tool required

**Comment by Aurx** [comment]
>I think we can say it was intended.

It was very likely not.  Pomf added those lines as part of his commit series trying to make Diseased Touch actually work.  No commentary in the commit about making other viruses faster based on how long they'd been in somebody else, so I assume it was just a hotfix with issues.  
https://github.com/d3athrow/vgstation13/commit/224a204f5fdf3132971669be2cc91eb44c0fd93c

**Comment by Intigracy** [comment]
If virus progression does take as long as people claim it does (which I highly doubt) then I think it would serve to change [line 133](https://github.com/d3athrow/vgstation13/pull/14153/files#diff-9cda4cba58dd9b79665e328bfd7aa373R131) from `clicks = 0` to `clicks -= stage*100` and move the `stage++` and log after it, while leaving in the clicks transfer in this proc.

What this means is that "cooking" a virus before spreading it will make it progress through the stages faster than just releasing it at stage 1, but it's not going to instantly jump to stage 4 which is honestly just bullshit.

Or instead of handholding we could just make people start actually using virus food, it's why it exists.

**Comment by Intigracy** [comment]
Ignore the parts I had about initial(stage), it's already at the initial value.

**Comment by Killette2** [comment]
Duplicate response from the issue.

I do not enjoy the concept of having to ingest virus food. With this fix I doubt anyone would want to play virology at all unless the syndromes are also sped up on their own. I certainly won't be touching it.

**Comment by Kitfox88** [comment]
I didn't think anyone wanted to play virology anyway.

**Comment by Killette2** [comment]
Virology is one of the jobs that is already struggling though. Any changes that would take away from it would make it even further undesirable to play.

**Review by PJB3005 — APPROVED** [review]

**Comment by PJB3005** [comment]
Manually merged with a357ed3737a63af94f833447b62ef44266882e34 but GitHub broke so it didn't detect it.

**Pull request closed without merging**
