### PR TITLE
Gives the Snow Survival Guide its own icon

### PR DESCRIPTION
**Pull request by DeityLink**
image

:cl:
* imageadd: The Snow Survival Guide now has its own icon, instead of re-using one of the old xenoarch ones.

### CODE REVIEW

**Comment by Servalfang** [comment]
it probably shouldn't be white. It's supposed to stand out in the snow, no?

**Comment by DeityLink** [comment]
Well it's supposed to stand out in your pocket where it spawns and I think colour is rarely an issue there. Last round you'd see them mostly thrown on the floor inside the station. If you were to drop it outside it'd turn to ashes instantly due to its magnesium thingstuff (which it might only do if you actually use it on the ground)

**Comment by Eneocho** [comment]
I'm still disappointed the thing just makes some "heat" instead of starting a fire on its tile.
It would be better if it made a campfire right under you, and used itself as tinder. 
"You take the emergency campfire supplies from the survival guide and activate its magnesium strip, quickly starting a makeshift campfire. You feel warmer."

**Comment by DeityLink** [comment]
yeah I was kinda disappointed too when the manual told me it could be used on snow and then just turned into dust.

**Comment by Kurfursten** [comment]
Instantly heating you up is far more useful and practical than starting a fire, though. The intended use is to give you an emergency hypothermia recovery not to chain you to one specific spot like a campfire would. I don't think the idea is awful that it could be used as fuel on a campfire like wood, but making it spawn a campfire is just asking everyone to walk out and put campfires on the main road to set other people on fire. I also don't think it makes sense to dissolve if dropped without using it, either from a gameplay design or immersion perspective. It's an internal lighter strip, you have to hold the book open.

I think the new sprite is fine.

**Comment by Eneocho** [comment]
>Instantly heating you up is far more useful and practical than starting a fire, though. The intended use is to give you an emergency hypothermia recovery not to chain you to one specific spot like a campfire would. 

Just build the campfire AND do the instant hypothermia recovery.
>making it spawn a campfire is just asking everyone to walk out and put campfires on the main road to set other people on fire

You forget that snaxi has tons and tons of freely available wood; just cutting 2 or 3 trees is enough to build like 15 campfires on the main road. Balancing the guide around the possibility of people griefing with campfires is kinda pointless if you can do it anyways with the freely available wood.

**Comment by Kurfursten** [comment]
I believe there is a difference between trivial and doable; trivial is "I'm throwing away my book anyway so I'm going to make a fire because it's just 1 click while I'm walking" and doable is "I'm going out of my way to grab a hatchet at the vendor, go 20 tiles off into the snow, cutting down a tree 10 more seconds, cutting up logs, stacking the wood, bringing it back to the road, building campfires at 4 seconds each, then lighting them individually). That's the difference in effort that keeps the meeting room donuts safe (it's just one window or windoor or 2 airlock hacks) vs the kitchen (public table). Another way to put this is: anyone can go melt down all the flaps on the station to make plastic bags, but giving every assistant a plastic bag is what makes them pile up in arrivals.

Even just adding slightly more effort would alleviate my concerns. Like it makes a campfire if you use the guide on wood or a log instead of snow.

**Comment by Eneocho** [comment]
The difference is that the book would be single use. At most you only get to griff once. Getting the wood for campfires lets you build as many as wood you can find (a fuckton).

**Comment by DeityLink** [comment]
added a yellow/black stripe so it looks more like a survival guide I guess

**Pull request merged**
