### PR TITLE
Borer Tweaks

### PR DESCRIPTION
**Pull request by Shadowmech88**
In response to complaints of head borers being unreasonably capable relative to other types of borers:
Removes hyperzine, anti-toxin, charcoal, leporazine, inaprovaline, kelotane, dermaline unlock, liver function boost gene unlock, and X-ray vision gene unlock from head borers.

Adds night vision channeling ability unlock to head borers.
This ability requires unlocking telephoto vision at least once, and allows the borer to expend chemicals constantly in order to give both itself and its host night vision.

In response to complaints of chest borers being unreasonable weak relative to other types of borers:
Adds leporazine, charcoal, anti-toxin, inaprovaline, dermaline unlock, and liver function boost gene unlock to chest borers.

:cl:
 * tweak: Head borers can no longer secrete hyperzine, anti-toxin, charcoal, leporazine, inaprovaline, kelotane, or dermaline. Head borers can also no longer unlock the sober gene or X-ray gene for their host.
 * tweak: Head borers can now unlock a new ability that allows them to channel chemicals constantly in order to give themselves and their hosts night vision.
 * tweak: Chest borers can now secrete leporazine, charcoal, anti-toxin, inaprovaline, and dermaline. Additionally, chest borers can now unlock the sober gene for their host.

### CODE REVIEW

**Comment by CptWad** [comment]
are their groin borers
while the concept may seem wrong, we could move charcoal, liver boost and antitox to groin borers

**Comment by ScrambledSteak** [comment]
only if it also has extendo dick

**Comment by Shadowmech88** [comment]
The liver is inside the ribcage. I would think that'd make it chest territory.

**Comment by AutismSpider** [comment]
@Shadowmech88 can you take out bustanuts for hyperzine on leg borers? i think that chem is more fitting for that spot

**Comment by Shadowmech88** [comment]
Leg borers are already capable of producing hyperzine. Bustanuts are their unlockable chem.

**Comment by Probe1** [comment]
God bless it shadowmech one day you're gonna have to learn balancing.

Remove Xray.  Not re-add in another slot or tweak.

**Comment by Shadowmech88** [comment]
I don't think allowing head borers to expend a lot of chemicals constantly to grant themselves temporary X-ray vision is so bad, is it?

**Comment by CptWad** [comment]
xray vision for borers is still awful because you can yell to your borer friends that you see an antagonist succing someone in maint
xray existed only as a genetics power that was hard to find AND unlock for a reason

**Comment by AutismSpider** [comment]
@Shadowmech88 Take out x ray vision for night vision?

**Comment by Shadowmech88** [comment]
Night vision for the borer or the host?

**Comment by AutismSpider** [comment]
Eh why not both at the cost chemicals?

**Comment by N3X15** [comment]
The coders and I were discussing more comprehensive changes, just as a note.

**Comment by AutismSpider** [comment]
@N3X15 What did they have in mind?

**Comment by Killette2** [comment]
I think that borers are just a scapegoat for this change. The obvious problem is chemicals.

I say that if your body ever has over 4 chemicals in it, you auto gib. The RP logic will be it overloads your immune system and you cannot live in space conditions due to it.

**Comment by AutismSpider** [comment]
@Killette2 massive organ damage would be better starting with the liver kidneys  heart etc

**Comment by Killette2** [comment]
That's not as terrible as my idea actually. The only catch would be selecting which chemicals count so the billions of flavor chems won't kill you.

**Comment by AutismSpider** [comment]
The chemical thing is a problem you can have six or more chemicals in you with no down sides.

This should hurt you in some way  by slow organ damage if you have five or four more chemicals ticking inside of you or just you vomit up random chemicals in you.

**Comment by Shadowmech88** [comment]
* X-ray channeling has been replaced with night vision channeling, which grants both the borer and the host temporary night vision.

**Comment by ghost** [comment]
I would like to point out that a major complaint in the original issue report was incredibly dishonest.  It takes borer closer to 17 minutes to get x-ray as opposed to 10 minutes.  In addition, the effect is lost if the borer leaves the host.

I also propose that anti-tox is moved the the legs as opposed to the chest given that you are already giving a massive amount of control to chest borers in the burn department with this change (arguably way too much with the affects of the burn resist and derma compounded).  Legs already lack a massive amount of chem control compared to the other possible positions.  You are taking apart one monster (head borers) just to create another (the insanely powerful chest borers if this is passed)

**Comment by AI-Is-Rogue** [comment]
Give anti toxin to the Synaptizine producing borers? You madman.

**Comment by ghost** [comment]
If I recall correctly, chest borers produce radium, allowing a single slot make you virtually immune to energy based weapons and projectile based weapons in regards to combat, as well as cure viruses with no repercussions is a lot worse than letting you handle the tox damage from synapt.  Leg borers are also much, MUCH worse off than chest borers.  Leg borers are currently the only borer slot unable to produce any healing chems whatsoever.  Why not give them anti-tox?  The need the love way more than chest.

**Comment by AI-Is-Rogue** [comment]
Radium protects you from energy and ballistic weapons?

**Comment by FudgePucker** [comment]
@Killette2 
A syringe holds 15u, so your idea would have to be carefully balanced to prevent people from making "beneficial" syringes that are instant gib.

It would also nerf everything retaining to chemistry.
What would be the effects of this if you put someone into a cyrotube with a standard mix?
Is it only chems that are used for powergaming? Like hyperzine synaptizine and the nanobots? Or is it also going to include medical chems to prevent people from making themselves near immune to damage?

This would be a major change, people would find ways around it, people would find ways to abuse it to 'accidentally' gib people (see happiest mask to see what shit people will try to pull off and get away with), and people might actually accidentally gib people with it.

The player base is always going to find a way to powergame and be huge shitters, trying to code away their methods isn't going to exactly work. You either have to accept that there will be shitters on the server or start implementing bay rules, zero tolerance on bullshit. Just have admins start checking chemical amounts on players, if they have more meds in their body than blood, bwank them and ask them if they have a good reason, if they don't or they make up one, gib them and tell them if they do that shit again they will be permabanned.

**Comment by Killette2** [comment]
@FudgePucker I wasn't serious about the gibbing part. One post later I said I liked the organ damage and that my idea was terrible simultaneously, which should be a give away

**Pull request merged**
