### PR TITLE
Fixes #11661

### LINKED ISSUE #11661: motorized wheelchair planes are fucked
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> fix planes
> 
> What you expected to happen
> planes fixd
> 
> What actually happened
> it goes under conveyor belts and stuff
> 
> Steps to reproduce if possible
> go around with a wheelchair and see fucked planes

### PR DESCRIPTION
**Pull request by ghost**
Fixes #11661

### CODE REVIEW

**Comment by clusterfack** [comment]
Stop making a thousand prs you fucking faggot

**Comment by Intigracy** [comment]
Half of them are coded by bauds.

He couldn't even keep his promise.

**Comment by 9600bauds** [comment]
You kidding?
All of those were done in one day
This has already worked out an order of magnitude better than any feature freeze
Who cares about the original terms

clip 2014-01-23 at 05 02 32

**Comment by Intigracy** [comment]
Bauds is indeed an impressive coder.

DrCelt is not.

**Pull request merged**
