### PR TITLE
removes St. Space Asshole's Day

### PR DESCRIPTION
**Pull request by TheEaterOfBeans**
Fixing my past mistake.
-->
:cl:
 * rscdel: St. Space Asshole's Day is gone

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
why

**Comment by djkramer123** [comment]
citadel coder moment

**Comment by Eneocho** [comment]
why_4

**Comment by TheEaterOfBeans** [comment]
Because I made it and it was a stupid idea.

**Comment by TheEaterOfBeans** [comment]
> citadel coder moment

Yes.

**Comment by boy2mantwicethefam** [comment]
Nothing wrong with it, if anything what's wrong is that the date is off by 1 day (at least on my end). I'd rather that gets fixed instead of removing content

**Comment by Kurfursten** [comment]
This PR and the last one are so baffling that I don't know what to make of them. As far as I know, you came to /vg/ to make one (1) PR where you added this holiday with no features or support at all. No one cared about the PR where it was added and only one person voted on it. It fired a single time, last year, and now you're removing it. Both PRs are without really any explanation.

Is there something you're getting out of this that I don't see?

**Comment by TheEaterOfBeans** [comment]
> This PR and the last one are so baffling that I don't know what to make of them. As far as I know, you came to /vg/ to make one (1) PR where you added this holiday with no features or support at all. No one cared about the PR where it was added and only one person voted on it. It fired a single time, last year, and now you're removing it. Both PRs are without really any explanation.
> 
> Is there something you're getting out of this that I don't see?

I had a stupid idea, then regretted it later.
That is literally it.

**Comment by smalIboss** [comment]
i veto his right for removal of this feature
let his regret last forever

**Comment by TheEaterOfBeans** [comment]
> i veto his right for removal of this feature let his regret last forever

yeah ok
I don't play here anymore anyways

**Comment by smalIboss** [comment]
you will come back. they all come back.

**Comment by Kammerjunk** [comment]
I love this PR and the one before it.

**Comment by TheEaterOfBeans** [comment]
> I love this PR and the one before it.

existence is pain

**Comment by SonixApache** [comment]
???
why did you suddenly panic and [redact] everything as if your actions were the worst thing in the world? did someone tell you that the world asshole is verboten or something?

**Comment by Armadingus** [comment]
I like how there's a comment of top of holidays.dm to not add stupid stuff and here we are trying to keep bloatcode that literally only makes text pop up at the 25th of October.
Mental. Someone please remove orgasming day as well.

**Comment by tomacatx2** [comment]
the pull that saved /vg/

**Comment by Exxion** [comment]
society

**Pull request closed without merging**
