### PR TITLE
Map Fixes - Boxstation

### LINKED ISSUE #2381: [Box] Cargo storage camera missing

### LINKED ISSUE #2389: [Box] Misc Lab camera is in maintenance

### LINKED ISSUE #2818: [Box] Mine APC lasts for minutes and won't recharge
The lights go out in minutes and the mech recharger outside the research outpost is always off as a result too

### LINKED ISSUE #3416: [BOX] Borked disposals north of fitness

### LINKED ISSUE #3778: (WEB REPORT BY: iconleap REMOTE: 198.245.63.50:7777) Kitchen backroom, insufficient light
>Revision (Should be above if you're viewing this from ingame!)
3400f3967657bb4753aa33ba3c4eb2aa2fd200ba

>General description of the issue
The light bulb is small to light the whole room

>What you expected to happen
The room is lighted

>What actually happened
Just only a part of that room is lighted

>Steps to reproduce if possible
>Be assistant
>GREYTIDE NATIONWIDE!
>Today is I gib someone
>Be at kitchen
>It's dark
>I have a phobia of darkness
>Cry inside
>DIE because they robust me ;_;

### LINKED ISSUE #4816: TV monitor in engineering is rotated improperly.
should be twisted 90 degrees to the left, right?

ss 2015-06-02 at 06 20 42

### LINKED ISSUE #4996: [BOX] Double light switch in recycling

### LINKED ISSUE #5038: [box] useless vent in overflow surgery
there are two vents there, one is under a computer and isn't connected to anything

### PR DESCRIPTION
**Pull request by ghost**
Because you can't stop working on the map for more than one week without having issues everywhere
- Remove an unconnected vent in Surgery Overflow. Fixes #5038
- Remove a duplicate lightswitch in Recycling. Fixes #4996 
- Orient the telescreen in Engineering properly. Fixes #4816
- Rename a shitload of airlocks to be less shit. Areas names used in priority, otherwise basic logic such as "This is a storage area, this is inside the Brig, etc". Also stop calling airlocks "X Door", please

Main change in this PR : 
- Further the introduction of border firelocks. The useless "hazard door" sub-type was removed in favor of "Firelock [Direction]". Trying to make sure Firelock South is used instead of the default state. 
-  Many departments and rooms that were oddly ignored should now be covered with firelocks, notably includes Security and Engineering
- Fix a large amount of firelocks that were arranged oddly or even incorrectly (looking at you, Bar). The logic is now to have firelocks fire outwards of the rooms they protect, towards places that could obviously end up breached or otherwise in a bad atmospheric conditions (for example the Engine, Escape, Arrivals, Toxins), no firelocks on maintenance access if possible

Please report any firelocks that are above airlocks and blast doors, badly aligned, or any old firelocks that are still present

The following issues, after investigation, are no longer a problem and should be closed : 
- Fixes #3778. Freezer lighting is sufficient
- Fixes #3416. Fitness disposals functions correctly and there is no disposal pipe breach
- Fixes #2818. Should no longer be an issue after the addition of mining lantern hooks
- Fixes #2389. No cameras pointing to the Misc Lab (now Telescience) appear to be misplaced in Maintenance
- Fixes #2381. Deliberate design decision to prevent AIs from snooping on Cargo's orders too easily

### CODE REVIEW

**Comment by Probe1** [comment]
regarding [2818] does it remove the outside apc?  it's been a pita because it powers the whole asteroid.

**Comment by dylanstrategie** [comment]
No, the outside APC is still here for the time being, but the lighting budget has been cut down to about 300 W. There are a few errors with lantern placement and I will push a hotfix for that while I'm here

**Comment by Probe1** [comment]
gay.  thanks though, good pr.

**Comment by dylanstrategie** [comment]
The problem is that while I can remove all the lights and the mech charging machinery is in their station's areas, there still are doors and windoors in the area and I prefer to have an APC to avoid quirks

**Pull request merged**
