### PR TITLE
Now Look at This Jumpsuit, That I Just Found

### PR DESCRIPTION
**Pull request by Shadowmech88**
display
Adds rotten suit.
Adds rotten shoes.
Adds five rotten suits and five pairs of rotten shoes to the autodrobe.

:cl:
 * rscadd: Added the rotten suit and rotten shoes, obtainable from the autodrobe.

### CODE REVIEW

**Comment by Probe1** [comment]
sigh.  why not, it's not so obviously I'M A REFERENCE and players will enjoy it.

**Comment by Kurfursten** [comment]
Maybe include it at the Nazivend, so that Nook Ops can wear it?

**Comment by Shadowmech88** [comment]
Don't nuke ops get an autodrobe as well as a nazivend?

**Comment by Probe1** [comment]
>Five guys named [Generic] HORSECOCK wearing robbie rotten outfits

Also yes it has an autodrobe.

**Comment by Shadowmech88** [comment]
The autodrobe actually only has four outfits.
Should I bump it up to five for ops?

**Comment by Probe1** [comment]
Will these inherit in_hand sprites from something?  ```item_state```

**Comment by Shadowmech88** [comment]
What do you mean? Their `item_state` is set.

**Comment by Probe1** [comment]
Gotcha.  I wasn't aware of how clothing item_state was handled. That is nice.

**Comment by Shadowmech88** [comment]
Actually with a second look, I realize I forgot to make in-hand states for these. I'll do so now.

**Comment by Kitfox88** [comment]
>nook ops

at least now i'll have an excuse for being a bumbling fucko whenever i play one

**Comment by Intigracy** [comment]
Now nuke ops can finally look the part.

**Comment by 9600bauds** [comment]
be careful not to make a sound! _*deathgasp_

**Comment by Intigracy** [comment]
No, don't touch that!

**Comment by ComicIronic** [comment]
Did you seriously merge meme reference material?

**Comment by Shadowmech88** [comment]
It's no more referential than a lot of the other costumes in the autodrobe.

**Comment by SangriaMonkey** [comment]
:ok_hand:

**Comment by Intigracy** [comment]
A meme a day keeps the noose away

**Pull request merged**
