### PR TITLE
Fixes vine/biomass spreading as well as registered lazy events disappearing on ChangeTurf

### LINKED ISSUE #20161: Blue biomass vines seem to have no sanity to where they can grow.
As the title says blue biomass seems to grow through windows, airlocks, firelocks, and most other tiles next to it despite being blocked in some way or another that you couldn't move though normally or would expect to block it.

### LINKED ISSUE #29378: Vines stop spreading after they mature
imagen

It doesn't take long to mature so it's kind of lame. It also kills the autoharvesting.

Solutions?
Listen for turf events next to the plant and readd to processing objects or try to spread if there are valid neighbors.
Or maybe put them on a slower process().

idk

Related code:

https://github.com/vgstation-coders/vgstation13/blob/4c09a724bde4dbd895b9468a1c8aa18c4f65c984/code/modules/hydroponics/spreading/spreading_growth.dm#L121-L122

### LINKED ISSUE #29687: Kudzu doesn't spread into new places if it has reached maturity before new place became available
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
98ba5a13aaf2978cb6c65a1027bbdbcf945e6085

# Description
See picture.
https://i.imgur.com/yFhIaSP.png
New place opened up after kudzu fully matured, andwa it does not spread there.
# Steps to Reproduce
Unleash kudzu (please don't), wait for it to reach final stage of growth (several red fruits on vine), give it new place to grow into (like open an airlock that blocks it) - it doesn't grow there.
# What you Expected
Kudzu going into new place
# What Actually Happened
Kudzu just chilling.

### LINKED ISSUE #29688: Kudzu doesn't spread into new places if it has reached maturity before new place became available
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
98ba5a13aaf2978cb6c65a1027bbdbcf945e6085

# Description
See picture.
https://i.imgur.com/yFhIaSP.png
New place opened up after kudzu fully matured, andwa it does not spread there.
# Steps to Reproduce
Unleash kudzu (please don't), wait for it to reach final stage of growth (several red fruits on vine), give it new place to grow into (like open an airlock that blocks it) - it doesn't grow there.
# What you Expected
Kudzu going into new place
# What Actually Happened
Kudzu just chilling.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #20161
Fixes #29378
Fixes #29687
Fixes #29688
image

image

:cl:
* bugfix: Mature Space Vines (kudzu) will now properly spread when an adjacent door opens or an adjacent wall is dismantled.
* bugfix: Fixed Biomass spreading through one-directional windows and firelocks.

### CODE REVIEW

**Comment by Eneocho** [comment]
Does this mean biomass will finally stop spreading through windows? I'm tired of biomass spreading into a window then needing to break/disassemble it to get rid of the mass.

**Comment by Exxion** [comment]
It does explicitly say that it stops biomass from spreading through windows, yes

**Comment by Killette2** [comment]
I think this is unrelated but have any changes allowed vines to spread on unsimulated snow tiles like the ones in snaxi

**Comment by DeityLink** [comment]
> 
> 
> I think this is unrelated but have any changes allowed vines to spread on unsimulated snow tiles like the ones in snaxi

not mine, but this PR allows biomass to spread on any floor, including shuttle/unsimulated ones

**Pull request merged**
