### PR TITLE
Ports TG(?) flag underwears

### PR DESCRIPTION
**Pull request by ghost**
Show your american pride by wearing this nifty american underwear or if you like communism there's one for that too!
image
ports three underwears for male and female characters, here's one example of the underwears added
These are actual underwears and not clothing items
:cl: 
 *rscadd: Ported 3 flags underwears, UK, USA, and communist flags.

### CODE REVIEW

**Comment by ghost** [comment]
i stole the sprites from a server that uses TG code so i have no idea if TG actually has these

**Comment by jakmak6** [comment]
which server?

**Comment by ghost** [comment]
c i t a d e l

**Comment by mtpowell** [comment]
Now port the vore code

**Comment by ghost** [comment]
I didn't realize how badly we needed this until just now.

**Comment by HarseTheef** [comment]
Beautiful

**Comment by ghost** [comment]
they also have BOOZE goggles

**Comment by Praecordia** [comment]
god bless america

**Review by ComicIronic — APPROVED** [review]

**Comment by Supermichael777** [comment]
these are indeed tg originals. CC BA NC 3

**Comment by ComicIronic** [comment]
It's the Creative Commons license you confused chumps

 * CC - Creative Commons
 * BY - Author Credit
 * NC - Non-commercial
 * 3 - Version 3

**Pull request merged**
