### PR TITLE
Adds crawling

### PR DESCRIPTION
**Pull request by MadmanMartian**
Was looking through organ code, and found a check not used anywhere besides being able to scoot around on an office chair. I hope move doesn't ignore too much sanity.

**Problems**
 - ~~You can 'crawl' while buckled to a roller bed. It relaymoves and has no slowdown (Go as quick as you can click)~~
- ~~There's generally no slowdown for any of the crawling movement, really. Hyperzine doesn't help, but only having one arm doesn't hinder either.~~
- Diagonal crawling - Let's just call it a feature

:cl:
* rscadd: You can now crawl by clicking on a turf in proximity when on the ground but not unconscious or dead and have arms

### CODE REVIEW

**Comment by Shadowmech88** [comment]
>You can 'crawl' while buckled to a roller bed. It relaymoves[...]

Do roller beds need to relaymove? Would it be difficult to remove that?

**Comment by MadmanMartian** [comment]
I think it happens to anything you can buckle to that isn't 'anchored'. Was able to reproduce it with a resin bed and a regular bed by setting their anchored to 0

**Comment by Fruktlimpa** [comment]
How long is the cooldown per click?
It should also be impossible to crawl if someone is dragging you kinda like you are being restrained.

**Comment by MadmanMartian** [comment]
@Fruktlimpa It's odd. If you were just standing and try to crawl, you can go at really fast speeds, but if you were pushed over, or have been crawling for a while, you seem to glide rather slowly

**Comment by Exxion** [comment]
Same thing happens in space except it's only aesthetic in that case. Error in the move delayer. I knew what exactly it was at one point, but forgot

**Comment by Kurfursten** [comment]
I gotta admit when I saw the name I expected this to be a joke PR. Crawling has long been joked about being added.

I don't object by the way, I just thought it's funny, it's finally happening. Incoming 100 replies when Americans wake up?

**Comment by Ephx1** [comment]
It's Hyperzine and Magboots, not hyperzine and crawling, OK? God bless.

**Comment by DrSnips** [comment]
Unless I'm unaware I don't see a reason why a person can't crawl after being pushed or anything stun wise. This could lead to a lot of issues with stunning someone and them crawling away to get out of cuffing or similar things.

**Comment by MadmanMartian** [comment]
good point, I'll add a stun check and such

**Comment by Dacendeth** [comment]
What about things like tables, could you lay down to crawl over them by clicking the ground under it?

**Comment by MadmanMartian** [comment]
can't crawl through anything dense like tables, from what I can see.

**Comment by SonixApache** [comment]
Every missing limb should slow down crawling speed imo.

**Comment by MadmanMartian** [comment]
They do already. Missing your legs? You slow

**Comment by jknpj** [comment]
>diagonal crawling

you can use diagonal movement to get through glassdoors

**Comment by SonixApache** [comment]
yeah but i mean like additive
1 leg & 2 arms? crawl.
1 leg & 1 arm? crawl slower.
0 legs & 2 arms? crawl slower.
0 legs & 1 arm? crawl slowest.
maybe even check for feet and hands

**Comment by Kurfursten** [comment]
I assume movement delay is the proc used in New Movement that we got a month or two ago? So it would inherit all the normal slowing factors, like wearing a space blanket cape, active magboots, pain etc.

Interestingly you won't be able to turn off your magboots while crawling since, like all other things, that requires you to be standing.

**Comment by MadmanMartian** [comment]
@jknpj I've tested it, and it seems to take things into account in an L for diagonal movement

Something dense below you and to the right of you? No going south west

**Comment by FudgePucker** [comment]
Can you crawl over tables?

**Comment by MadmanMartian** [comment]
That has already been asked. No you can not.

**Comment by FudgePucker** [comment]
What about plastic flaps?
I know on goon they let you move while getting up from laying down, meaning you can rest get up and move under plastic flaps.

**Comment by Kurfursten** [comment]
Could this be the update that finally forces someone to remap those awful flaps by metaclub atmos hardsuits?

**Comment by MadmanMartian** [comment]
You can crawl through plastic flaps, as they ignore things that are lying down. To change that would affect things such as cargo.

**Comment by DamianX** [comment]
Spacing people by throwing them through plastic flaps is a feature I'd rather not lose. Do we need an atom-level proc to check if a mob can crawl through it?

**Comment by FudgePucker** [comment]
I mean, its not like winflaps are impenetrable obsticals. You just need a wrench to bypass them.

**Pull request merged**
