### PR TITLE
Snowmap pr 2

### PR DESCRIPTION
**Pull request by ghost**
quick check to see if the conflicts have gone away

### CODE REVIEW

**Comment by PJB3005** [comment]
You know GitHub lists whether the PR will have conflicts before making it, right?

**Comment by ghost** [comment]
doesn't tell me what travis'll say.

And travis says taxistation's old and needs some changes to some things

**Comment by ghost** [comment]
AHHHH

**Comment by yclatious** [comment]
When

**Comment by ghost** [comment]
>thumbs down by PJB

I knew it, dream's dead

**Comment by Blithering** [comment]
In the distant year of 20XX, we will enjoy clockcult rounds on snowmap with scootaloos.

**Comment by carshalash** [comment]
Ireland may never be free. But we gotta free snowmap for nigga celt.

**Comment by Durgen** [comment]
is there enough progress on this to grab some screenshots
i'd love to see the map behind the meme

**Comment by carshalash** [comment]
I know two people with working copies of it before the change was made that broke snowmaps.

One is of course celt, the other is kolith. Try hitting them up to get a look at it all.

**Comment by ghost** [comment]
this works too.

Kolith has just kept saying he has a working copy, but it's out of date.

This is a copy of celts, brought up to date

**Comment by PromethTK11** [comment]
What changes are need in taxistation?

**Comment by ghost** [comment]
taxistation was just a tad out of date and needed fixing

**Comment by PromethTK11** [comment]
I mean, guidelines about fixing that, because there's a lot of things in the map

**Comment by ghost** [comment]
@PromethTK11 iirc the most important thing that needed fixing was the disposals network

**Comment by Shadowmech88** [comment]
>All checks have passed
>This branch has no conflicts with the base branch

Is it happening?

**Comment by ghost** [comment]
It hasn't even begun

**Comment by SonixApache** [comment]
image

**Comment by ghost** [comment]
code priority never. Conflicts forever

**Comment by ghost** [comment]
F

**Comment by SysadminJeroen** [comment]
F

**Comment by ghost** [comment]
F

**Comment by RFultra** [comment]
F

**Comment by Blithering** [comment]
a7def8e3bb7922eaec235c800418e3fd

**Pull request closed without merging**
