### PR TITLE
Updates the list of chems that need logging procedurally

### PR DESCRIPTION
**Pull request by MadmanMartian**
You making a chem that can be used nefariously, like a poison? Give it the CHEMFLAG_BAD and it'll be added to the list of reagents to log at game start.

Shouldn't need a changelog, as it's logging side, not player side.

### CODE REVIEW

**Comment by beesil** [comment]
Mercury, radium, sulfuric acid, and welding fuel will result in a lot of spam to admins since they're used frequently in non-nefarious things. Otherwise :+1:.

**Comment by Irradiation** [comment]
Sulfuric acid will spam the fuck out of admins when Cargo/Science/Engineering make tons of it. Also radium leads to Hyronalin & Mutagen.

**Comment by MadmanMartian** [comment]
Sulfuric acid was already on the list.

Previous list was: FUEL, PLASMA, PACID, SACID, AMUTATIONTOXIN, MINDBREAKER, SPIRITBREAKER, CYANIDE, IMPEDREZENE, LUBE

**Comment by Irradiation** [comment]
I'd take off Sacid personally, but that's just me.

**Comment by 9percents** [comment]
is it possible to make flag trigger only when it metabolizes or on_touch?
that would make mercury and sacid less spammable

**Comment by MadmanMartian** [comment]
Sure, can be done

**Comment by Kurfursten** [comment]
Okay but it shouldn't trigger every time it metabolizes or mercury would become nightmarish for admins.

**Comment by MadmanMartian** [comment]
but, it triggers on transfer to an object, not on metabolizing. This system's to check for stuff like "oh, so-and-so put plasma in the mix" or "so-and-so put amutoxin in the chefs pizza, admins check this out."

**Comment by Kurfursten** [comment]
I'm talking about what 9percents said

**Comment by MadmanMartian** [comment]
Okay, I think I can get that done.

**Comment by Irradiation** [comment]
F

**Pull request closed without merging**
