### PR TITLE
Fixes #10532

### LINKED ISSUE #10532: Project Mind isn't logged
Or, at the very least, not always.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #10532
- [x] tested

### CODE REVIEW

**Comment by ghost** [comment]
turns out this is impossible to test because #11658

**Comment by SonixApache** [comment]
fix it

**Comment by clusterfack** [comment]
Test it

**Comment by clusterfack** [comment]
Test it

**Comment by clusterfack** [comment]
Test

**Comment by ComicIronic** [comment]
low test PR

**Comment by clusterfack** [comment]
Okay pretty sure he doesn't give a shit

**Comment by ghost** [comment]
I literally ticked the test box you eejit. Unclose and merge

**Comment by clusterfack** [comment]
Don't use tick boxes to convey information. Use comments, there's no ping when you check a box, there's no obvious new message.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
