### PR TITLE
Organ transplant combat update

### PR DESCRIPTION
**Pull request by unid15**
Organ transplants from different species now carry over unarmed combat damage, as well as mutations such as claws, talons and beaks

Changelings in horror form can punch so hard they throw folks away; that is handled by the arms. Punching damage, however, is determined by the active hand.
Claws and beaks can be used for butchering. To butcher with claws, you have to be switched to the hand that has them

Organs will also respect their species' burn and brute damage modifiers, as well as ability to bleed and some other parameters. This means that while a diona hand is better at punching, it will receive 2.5 times the burn damage.

:cl:
 * rscadd: Organ transplants now carry over mutations like claws, talons and beaks, as well as other combat capabilities. When punching, your active hand determines the damage done. There are legends of a species so powerful they can send people flying with their punches - the ability to do that is stored in their arms, rather than hands.
 * rscadd: Damage dealt to organs from different species will now receive correct multipliers - for example, a skellington head will always take more brute damage, while a ghoul one will take less. In addition, limbs from some species won't bleed.

### CODE REVIEW

**Comment by unid15** [comment]
This is the ideal human body. You may not like it, but this is what peak performance looks like.

**Comment by mtpowell** [comment]
I approve, but I don't approve being a birb. Please vacate yourself.

**Comment by Exxion** [comment]
Is even a single part of that human?

**Comment by unid15** [comment]
The legs are. Also the torso is dionae so technically it's not really a human body, but then again it's not very diona-looking either

Also I thought that damage modifiers already were applied to organs based on their species, but it seems like that wasn't the case, so I added that. Also made it so that skellington limbs won't bleed. There are still some properties (like diona light absorbtion) that can't be implemented, so get ready for diona powergaming human/vox limbs every shift to remove the burn multiplier with no drawback

**Comment by DeityLink** [comment]
@unid15 more like this is what **beak** performance looks like

**Comment by RealestEstate** [comment]
what happens if you try to remove the limbs off of a creatine hulk monkeyman and then reapply them to another human for permanent hulk gains?

**Comment by unid15** [comment]
Doesn't work, only claws, talons, beaks and stone skin mutation (lets you walk on glass shards) can be transferred. But if there was something that could temporarily grant any of these mutations, then you could theoretically do that to gain the mut permanently

**Comment by Shadowmech88** [comment]
Will transplanting the legs from a mob give you its species's `move_speed_multiplier`?

**Comment by unid15** [comment]
that'd make diona too OP

**Comment by Shadowmech88** [comment]
If you wanted to screw over dionae, you could just make their healing not work if they don't have 100% diona and/or prosthetic limbs.

And anyway the only species that have a higher `move_speed_multiplier` right now are skeletons and grues, both of which take heavily increased brute damage.

**Comment by Intigracy** [comment]
Or reduce the healing dramatically.

**Comment by unid15** [comment]
No conflicts

**Pull request merged**
