### PR TITLE
Removes the panic writer messages.

### PR DESCRIPTION
**Pull request by PJB3005**
#7 Minutes later I realised this is PR #6666

`Murder.py`:

``` Python
# Loops through all files in a tree with the .dm extension, then removes any lines that have the following string in them: '//writepanic("[__FILE__].[__LINE__]'

import sys

if len(sys.argv) < 2:
    print "Not enough argument supplied."
    quit()

import os
print sys.argv[1]
for root, dirs, files in os.walk(sys.argv[1]):
    print root
    for filename in files:
        if filename.find(".dm") == -1:
            continue

        absolute = os.path.join(root, filename)

        f = open(absolute, "r")
        lines = f.readlines()
        f.close()

        f = open(absolute, "w")

        for line in lines:
            if line.find("//writepanic(\"[__FILE__].[__LINE__]") == -1:
                f.write(line)

        f.close()
```

Can't say I didn't break anything, because I haven't tested (what do you even test for a PR like this)

### CODE REVIEW

**Comment by clusterfack** [comment]
Mark of satan

**Comment by PJB3005** [comment]
I'm removing the mark of Satan.

*Or am I?*

**Comment by RemieRichards** [comment]
Should have just opened the file with r+ instead of closing it and opening it again for each file :P

**Comment by PJB3005** [comment]
@RemieRichards eh that was approach was the top answer to a real quick Stackoverflow search and I couldn't be bothered to do it properly, even on this old PC the entire repo took 5 seconds to be cleaned.

**Comment by 9600bauds** [comment]
http://www.theallium.com/engineering/computer-programming-to-be-officially-renamed-googling-stackoverflow/

**Comment by RemieRichards** [comment]
yeah os walking stuff is p.fast and python's I/O is fairly decent, no surprise it didn't take long regardless.

**Comment by clusterfack** [comment]
I wonder how many conflicts this may make

**Comment by clusterfack** [comment]
Only one way to find out

**Pull request merged**
