### PR TITLE
Reshaping the new Bar organization

### PR DESCRIPTION
**Pull request by ghost**
- The holodeck no longer has an entire face crammed into a wall, instead the small space breather room between the south of the Holodeck and the nearby Maint is back
- Extended Fitness by one tile, shrunk nearby Maintenance tunnels a bit (it's a maintenance tunnel, not Holywood Boulevard)
- Re-added token Maint window near Bar
- Touched up exit from Bar to Fitness
- Fixed placements of lights to minimize useless duplicates, moved cameras around a bit and tagged them correctly
- Fixed vent and scrubber placements to remove pipes under walls, switched vents and scrubbers around in general to take advantage of existing pipe placements (hallway, maint, bathroom)
- Made Theater a bit wider
- Removed some of the weird alcoves in the Bar, some of which caused double wall layers
- Removed a redundant air alarm. This is the Bar, not Atmospherics Monitoring
- Removed a lone wire by Engineering

newnewbar

This should make the new Bar a lot more structurally sound and a bit less annoying to use

### CODE REVIEW

**Comment by Probe1** [comment]
did you post the right image

**Comment by dylanstrategie** [comment]
Yeah, why so ?

**Comment by Shaska-** [comment]
Looks good to me.
Disposal piping in the bar could use a loving hand while you're at it though.

**Comment by dylanstrategie** [comment]
To be honest, I prefer not touching disposal piping

As far as T-junctions go, there seems to be some arcane voodoo magic going on, and one single T-junction facing the wrong way will bury some random room in the station in burning junk and corspes

**Pull request merged**
