### PR TITLE
Beekeeping 3.6.4

### LINKED ISSUE #22514: Hornets
(WEB REPORT BY: ktvii REMOTE: 206.221.180.138:7777)
# Revision
c33fc00d728036cd3e9267ba3c3fbc47b5f57d9c

# Description
The hornets will just kill the traitor botanist who planted them as soon as they start coming out, which makes them very unreliable in the longer run, since there's nobody to defend them from any would-be killers. They should consider the botanist planting them as their ally and never attack them.
# Steps to Reproduce
Plant some fucking hornets and die.
# What you Expected
I expected the hornets to see the traitor botanist who planted them as a bro of theirs.
# What Actually Happened
They fucking killed him, bastards. Fix it.

### LINKED ISSUE #23011: Bees can attack through firelocks
(WEB REPORT BY: assfaget REMOTE: 206.221.180.138:7777)
# Revision
cbe73fb072aa57b0cff076be254f1df205258952

# Description
Angered bees can attack through firelocks.
# Steps to Reproduce
Stand in front of a closed firelock with angered bees on the other side of it.
# What you Expected
Not to receive damage.
# What Actually Happened
Received damage.

### LINKED ISSUE #29494: Bees sting through windoors
(WEB REPORT BY: kafovofa REMOTE: 206.221.180.138:7777)
# Revision
648176ce0040d63f21f845a43f922bfbca856fb3

# Description
An angry swarm of bees stung me from behind a windoor
# Steps to Reproduce
Anger bees, stand behind windoor, bees attack through the door
# What you Expected
Bees to be obstructed by glass
# What Actually Happened
Bees stung me through the windoor

### PR DESCRIPTION
**Pull request by DeityLink**
It's been over two years since my last update to Beekeeping. What started as a series of bugfixes also got its share of tweaks and new features that I think our botanist friends will enjoy. Especially the traitorous ones.

beenade 2 0
image

Most of this PR however is essentially a big cleanup of bee code. Renaming variables, adding better comments, splitting that enormous Life() proc into several others to reduce copypasta.

Fixes #22514
Fixes #23011
Fixes #29494

:cl:
* experiment: Added a new Traitor Botanist uplink item, the Bee-Nade, which has been reworked to in fact spawn hornets that will immediately seek a target when they spawn. They also ignore the one who primed the spawner grenade, just like viscerators do. Cost 16 (Discount 8)
* experiment: The Hornet Queen Packet traitor item has been replaced with a Deployable Wild Hornet Hive. Place it, throw it, drop it, but be careful as it cannot be picked up again once deployed. Those behave exactly like those from random events, except they spawn with less hornets inside, giving you a few seconds to get away before they start coming out. Cost 10 (Discount 5)
* experiment: The swarm coming out of a Bee Briefcase now performs an attack as soon as it comes out of the briefcase, greatly increasing its lethal power. The TC cost has been slightly adjusted to match its increased lethality. Cost 12 (Discout 6)
* experiment: Bees and the likes now attack AFTER moving instead of before. This effectively increases their attack range, and so their dangerousness.
* tweak: Bees that spawn from vermin infestations and hornets of all kind now immediately become angry again after their calmed status has expired instead of going back to their hive or to roaming.
* rscadd: Bee and Hornet gatling guns bullets no longer deal direct damage, instead they immediately cause the spawned bug to attack once on impact. Said attack is also guaranteed to pierce bio or impermeable armors.
* rscadd: Added a chillbug gatling gun. It doesn't deal damage of course but will inject 1u chillwax into players hit by the projectile.
* rscadd: Added both the hornetgun and chillgun to Summon Guns.
* bugfix: Bees and the likes can no longer attack through one-sided windows and windoors.
* bugfix: Fixed not being able to stomp snails when on harm intent.

### CODE REVIEW

**Comment by ghost** [comment]
whats this?
a station woefully underpopulated by BEEEEEEES?

**Comment by Rabbidx7** [comment]
Make this cost more TC to get, and keep hornets from apiaries you make dangerous to yourself,  but buff them to be similar to the ones from random events.  If you buff the hornets from the packets, make them cost more as well, they're a round ender. Ideally, if this is a beekeeping rework, make bees more fucking useful. Honey has so little use its insane. and don't give me the "m-medical item" shit. I want stuff like solidifying honey and making weird honey tiles and walls and shit. I want honey armor you can make with it, etc etc. I want bee RP, fix this PR now !!!!!!!

**Comment by DeityLink** [comment]
Honey is food you sick fuck, go make a tomato armor!

It's not a rework, just an update. But yeah I'll adjust the TC cost and might replace hornet queen packets with deployable wild hornet hives.

**Comment by Blithering** [comment]
07fsz14kq6101
>honey armour

**Comment by DeityLink** [comment]
I've gone past my quota of TF2 references in spess years ago but I approve.

**Comment by Eneocho** [comment]
> 
> 
> Make this cost more TC to get, and keep hornets from apiaries you make dangerous to yourself, but buff them to be similar to the ones from random events. If you buff the hornets from the packets, make them cost more as well, they're a round ender. 

Insecticide, which can quickly be made in medical (or acquired from insect control crates) easily takes care of hornets, so this is not as dangerous as you make it seem, since one spray or two can kill a buffed hornet swarm. Also the frogs and lizards, they can absolutely wreck the hornets and bees. The grenade is about as dangerous as the briefcase full of bees. Then again, by the time you acquire an insecticide spray, a good chunk of the crew would be stung to death.

**Comment by DeityLink** [comment]
More importantly fire extinguishers neuter them, and unlike viscerators a glass pane or a locker is enough to keep yourself safe.

**Comment by Eneocho** [comment]
How do the "Pheromones" work? If you hold the grenade before throwing, they are friendly to you? If a tatorbotanist throws a beenade towards me, and I manage to pick it up and throw it back, am I protected from the bees?
It could be a separate usable item, a pheromone spray with 2 uses, so you can protect yourself and a fellow tator.

**Comment by DeityLink** [comment]
> 
> 
> How do the "Pheromones" work? If you hold the grenade before throwing, they are friendly to you? If a tatorbotanist throws a beenade towards me, and I manage to pick it up and throw it back, am I protected from the bees?
> It could be a separate usable item, a pheromone spray with 2 uses, so you can protect yourself and a fellow tator.

It works just like a viscerator grenade. Whoever primes the grenade will have the hornets on their side.

The spray idea isn't bad but I'd keep it for another PR, there's other stuff I need to work on.

**Comment by Blithering** [comment]
Will viscerator grenades be getting an update? The hornet grenade would hugely outclass it, and they're kinda crap in general.

**Comment by DeityLink** [comment]
Alright changelog updated.

> 
> 
> Will viscerator grenades be getting an update? The hornet grenade would hugely outclass it, and they're kinda crap in general.

To be fair the viscerator nade's cost is only 6, and even a Discounted hornet nade is now 8. Viscerators need some changes yeah but that's a PR for another time.

**Comment by DeityLink** [comment]
heh, you can place them in disposals and they'll plant themselves when they get thrown out 
image

**Comment by Blithering** [comment]
>heh, you can place them in disposals and they'll plant themselves when they get thrown out

Now put one in a cannon.

**Comment by DeityLink** [comment]
> 
> 
> > heh, you can place them in disposals and they'll plant themselves when they get thrown out
> 
> Now put one in a cannon.


siegecanon

**Comment by SonixApache** [comment]
beenade should unleash bees
hornade should unleash hornets
otherwise good work :+1:

**Comment by DeityLink** [comment]
To be fair most people mean hornets or wasps IRL when they say bee.

**Comment by Eneocho** [comment]
>
> Now put one in a cannon.

image

**Comment by Killette3** [comment]
I'm a little confused about the hornet change. Does the wild nest act as a hive too or is its life limited now and can't be ez'd?

**Comment by DeityLink** [comment]
> 
> 
> I'm a little confused about the hornet change. Does the wild nest act as a hive too or is its life limited now and can't be ez'd?

It works just like the wild hives of random events once deployed. Those cheat to produce hornets without any consumption or production of food, and can have more bees outside the hive at a given point. Throw it and run away. You may also use the fact that it has density to block someone in Bomberman Style.

**Pull request merged**
