### PR TITLE
>you will never be anthony burch

### PR DESCRIPTION
**Pull request by Intigracy**
well, as long as you're not a randomnamer with shit luck

### CODE REVIEW

**Comment by optimumtact** [comment]
Cuck

**Comment by Kurfursten** [comment]
I should've known this was going to become a meme

**Comment by TheFriggenSawbones** [comment]
@optimumtact ur on the wrong github

**Comment by ghost** [comment]
Meme PR, close this

**Comment by Intigracy** [comment]
`>saying no to 4chan culture`
you're not a good person

**Comment by ghost** [comment]
meme PR, close this.

**Comment by kol1th** [comment]
@clusterfack weren't you going to close meme prs?

**Comment by sonime** [comment]
I see nothing wrong with adding this.

**Comment by SplergeBucket** [comment]
al checks have passed i think its tiem to merge this

**Comment by Intigracy** [comment]
> April 1 - For April fool's day, the theme of the site is changed to resemble Google's "material design" (A joke on moot's recent employment at Google, and the rumor he's been slated to do work on improving Google+). Image thumbnails are cropped to fit inside a circle like Android contact photos. Users are also given randomly generated names such as "Sergio Blackwell," Karla Goodwin" or "Alberto Barbossa" which override custom names or tripcodes, but do not remain consistent between posts. A website-wide hunt for board relevant names ensued, with /v/ practically ceasing to function for the whole day while users attempted to post as "Anthony Burch", an infamous video-game writer; however even after hours upon hours of combined shitposting, the website went back to normal and in the end no user managed to draw the lucky lot. Notable names pulled include Christopher Poole, Annie Frank, Christian Chan, Maggie and Homer Simpson, Sheldon Cooper, Ronald Macdonald, Jack Bauer, Nathan Drake, George Washington, Jennifer Lawrance and Michael Jordan.

Sorry for actually browsing the imageboard we hail from.

**Comment by coldcola** [comment]
what is your point? are you trawling through KYM or something??

**Comment by Intigracy** [comment]
no

that is why I made the PR in the first place, the post is just for those of you who don't use 4chan on a regular basis and are wondering where this is coming from

I actually intended to do this a while back, the other name changing PR reminded me

**Comment by coldcola** [comment]
ah I get it now, I should have looked at files changed when you didn't have a description.

**Comment by NigglyWiggly** [comment]
Wow a fucking 4Chan reference god why don't you just go back to /V/ where you came from, @Intigracy Why is Anthony Burch even a joke, is there something wrong with being a cuckold who loses his Wii U??

**Comment by optimumtact** [comment]
Tfw you can spawn as Matthew Ward on based tg, but vg can't even be Cuck Burch

**Comment by Intigracy** [comment]
The best part is that if I had made a PR just adding a bunch of last names without mentioning Burch specifically, nobody would care.

**Comment by NigglyWiggly** [comment]
Well yeah of course

**Review by PJB3005 — APPROVED** [review]

**Comment by clusterfack** [comment]
Code goes in, code goes out. You can't explain that.

**Pull request merged**
