### PR TITLE
Makes Blindness More Blinding

### PR DESCRIPTION
**Pull request by Shadowmech88**
The blindness (and unconscious, since they're apparently the same) overlay now shows only your tile instead of the eight tiles around you. You can still mouse over objects on these tiles and interact with them, but you can no longer see them. Additionally, the blindness overlay no longer shows a flash of vision every once in a while.
image
One of the ideas behind this is preventing, for example, an unconscious player being able to see someone holding an item while performing surgery on them and deducing that they've just had something implanted in them, all while they're supposed to be unconscious.

Initially I wanted to obscure *everything* except the player's body, but I couldn't figure out how to do that with BYOND's vision flags without preventing mouseover functionality.

:cl:
 * rscadd: The blindness/unconscious overlay now obscures everything except the tile you're on.

### CODE REVIEW

**Comment by SonixApache** [comment]
Check out the code for blindfolds and/or harm-labelled eyewear, I'm pretty sure one of those does exactly what you want.

**Comment by Riekland** [comment]
does this fix being able to see past blindness with far sight from borers and shit or is that still a meme

**Comment by Exxion** [comment]
Blindfolds and harm-labeled eyewear don't allow mousing over things.

**Comment by SonixApache** [comment]
Can you mouse over yourself?

**Comment by Exxion** [comment]
Yes, but nothing else.
They just add the BYOND sight flag `BLIND`

**Comment by Shadowmech88** [comment]
This doesn't touch the farsight issue.

**Comment by ElectroBlueGuy** [comment]
always wondered why i could see what people near me are holding while blind, good job

**Pull request merged**
