### PR TITLE
Adds a mime winter coat orderable from cargo.

### PR DESCRIPTION
**Pull request by Pancakemines**
Hopefully adds a mime winter coat comes in the misc coat crate from cargo.
I have very little idea what im doing but hopefully it works, tested and it was fine. I also fixed some coats that would show with their hoods up when worn with hood toggled. I'd add a picture but I'm too brainlet, sorry.
EDIT: I worked out how I'm only half as brainlet.
#23880 I was told to mention the original adding coats to supply to help keep track of things I think this is how you do that.
mimefront
mimeback

:cl:
 * rscadd: Added mime winter coat
 * bugfix: fixed incorrect winter coat hooded sprites

### CODE REVIEW

**Comment by Caboozles** [comment]
Got an image?

**Comment by Tokanova** [comment]
just scroll down and look at the details of 'Icon Diffs', usually always has the sprites in question added by any PR.

**Comment by brndd** [comment]
Your icondiffs say that you're modifying all the existing winter coats. Are you sure you did it right? Seems like it might be a regression.

EDIT: oh, it's deliberate. Maybe I should've read the PR body.

**Comment by SonixApache** [comment]
icondiffbot says you fucked up the hooded variants

**Comment by Pancakemines** [comment]
They're not fucked up they were broken a lot of the ones in suits.dmi had their hood toggled up which led to this.
bad hoods
comparison hoods
you can see in the second image the ones that had _t without toggle originally are the ones that didn't have that issue so I just fixed them all to work that way.
The issue is the hood showing twice not the colour its just the only image i have of it.

**Comment by SonixApache** [comment]
I think that was a feature, to indicate that your outfit's hood was up. Not sure, now.

**Pull request merged**
