### PR TITLE
Fixes missing novaflower dead icon.

### PR DESCRIPTION
**Pull request by ghost**
Novaflowers were missing their dead icon, now they use sunflower dead icon just like moonflowers do. I've moved novaflower icons into `hydroponics2.dmi` since `hydroponics.dmi` couldn't sustain a single extra icon for some reason.

[bugfix]
[sprites]

:cl:
 * rscadd: Fixes missing novaflower dead icon.

### CODE REVIEW

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
revert the changes on hydroponics.dmi as you've accidentally'd some icons

**Comment by ghost** [comment]
@MadmanMartian

Reread what I wrote in the PR. I have moved novaflower icons to `hydroponics2.dmi` which is why those icons are missing from `hydroponics.dmi`

**Comment by Exxion** [comment]
You also removed the synth-whatever sprites, probably due to sprite limit
But I'm pretty sure those are unused

**Comment by ghost** [comment]
I have not deleted those sprites, you can check for yourself by downloading the .dmi file and opening it in dreammaker, as I have just done.

**Comment by codeungabunga** [comment]
proofs

**Comment by ghost** [comment]
I have only now realized the bot lists the missing sprites, I will fix it.

**Comment by ghost** [comment]
I have reverted the offending .dmi changes.

However, I still do not see the sprites in the original .dmi when using dreammaker.

**Review by MadmanMartian — APPROVED** [review]

**Comment by MadmanMartian** [comment]
they may still disappear even now, because lmaodmicode

**Comment by Intigracy** [comment]
it's probably one of the files that got forcefully increased byond byond's sprite limit per dmi

every time you open it in dm it trims it to the sprite limit, like with the inhand files

**Pull request merged**
