### PR TITLE
Corgis in space!

### PR DESCRIPTION
**Pull request by NigglyWiggly**
Adds corgi hardsuit

Edit: FINE JEEZ
ss 2015-08-04 at 11 53 07

### CODE REVIEW

**Comment by Arthurdentist** [comment]
WHERE IS THE PICTURE NOGGLY?

WHY DIDN'T YOU POST A PICTURE TO SHOW US?

**Comment by Intigracy** [comment]
Too bad we're on gitlab now :^)

**Comment by PJB3005** [comment]
MIGRATE TO GITLAB WHEN.

**Comment by N3X15** [comment]
Confrictu

**Comment by NigglyWiggly** [comment]
There shouldn't actually be any conflicts with this, I fixed everything and it should definitely work.

**Comment by Intigracy** [comment]
It's probably items.dmi mate.

**Comment by NigglyWiggly** [comment]
It was, but I fixed it!

**Comment by Intigracy** [comment]
Wish it'd tell us what's conflicting.

**Comment by DeityLink** [comment]
Most likely items.dmi

What did you add in there?

**Comment by NigglyWiggly** [comment]
The suit and helmet, but I made sure I had the latest version and everything

**Comment by DeityLink** [comment]
Just rebase on Bleeding-Edge and see which files are conflicting. It's easy to do with SmartGit.

**Comment by SarahJohnson489** [comment]
Merged then add the ability to strap a tank transfer valve to its back and mass drive it for explosive delivery corgi's in space when?

**Comment by clusterfack** [comment]
Niggly fix this up for us yea?

**Pull request closed without merging**
