### PR TITLE
The Lost Crates of Lemuria

### PR DESCRIPTION
**Pull request by Kurfursten**
It can't be, can it? After a hundred years, has birdkind rediscovered the lost crates of Lemuria, ancient Cargo warehouse-world?

2x available at trade window (160 base price). Contains 6 items from this list:

3 of a kind
- [x] Cargo cache kit (the fake cargo posters that serve as hidey holes)

2 of a kind

- [x] Gibtonite satchel - transport gibtonite in style to more convenient locations for excavation. Must defuse first.
- [ ] Digsite depressor - automatically shoves digsites into the ground when you mine over them, making them possible for xenoarcheologists to recover the precious findings later

1 of a kind

- [x] Cosmic grill - uses space radiation to cook special monster meals right there on the roid - just add meat from local fauna like goliaths, magmaws, hivelords, basilisks, goldgrubs, etc.
- [x] Goliath lure - put it down and attract goliaths. Use meat on it to force goliaths to attack the bait first, buying you a precious opening to unload.
- [x] Quantum routing computer - use it on the cargo computer to make the cargo shuttle arrive faster
- [x] Mecha graveyard disk (I am interested in suggestions to make this place more interesting. I thought about putting a boss here with some loot.)
- [ ] MULE paint - paint your MULEs in a number of exciting paintjobs, including flames, Cargonia, and solid gold

🆑 
* rscadd: Traders have arrived with new miner/cargo themed goods from the lost world of Lemuria.

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
Doesn't allowing cargo to buy the cache kit kind of make the trader's ability to buy them totally useless?

**Comment by Kurfursten** [comment]
This is a crate for traders to sell to a cargo audience

**Comment by cloutcode** [comment]
lost in the devastating crash of the UES contact light

**Comment by NigglyWiggly** [comment]
Shame on you for expecting me to actually look at what the changes were

**Comment by Eneocho** [comment]
>Digsite depressor - automatically shoves digsites into the ground when you mine over them, making them possible for xenoarcheologists to recover the precious findings later

Bold of you to assume miners don't go out of their way to crush dig sites.

**Comment by Eneocho** [comment]
You could put a weaker mecha hitler or similarly VERY STRONG enemy on the graveyard. If you kill it you get access to a damaged (missing a few modules at random) Marauder or Mauler.

**Comment by Kurfursten** [comment]
I think giving miners a mauler is a bad idea, the real treasure should be the fun bossfight. Like nobody kills Angie for the gloves, it's for the glory.

**Comment by Eneocho** [comment]
>Like nobody kills Angie for the gloves, it's for the glory.

Not so sure about that. You fight Angie to loot the rare ores without risking a sudden charge and death.
What else would be worth the bossfight and thematically appropriate for a mecha graveyard? A Phazon ain't that good a reward for a boss fight, since robotics can shit them out by the dozen with like 15 minutes of xenobio powergayming, neither is a mining mech since they're slower than manual mining with a plasma cutter.

**Comment by Kurfursten** [comment]
Rare ores would be a good include too, sure

**Comment by Eneocho** [comment]
Maybe a sealed box containing a flawless telecrystal? Powerful but not by itself, the miner would need considerable help (or leeway) to use it properly.

**Comment by Kurfursten** [comment]
At a certain point I am wondering if it's too many hoops to jump through. First you have to buy the disk, then go there, then beat the boss, then open the sealed lootbox, then find something to do with the crystal (telegun is complicated to make requiring telecoms parts and mind machine requires a special disk from cargo).

Perhaps it would be better to not worry about buffing Mecha Graveyard in this PR and do it in a separate PR.

**Comment by Eneocho** [comment]
I was thinking more of a fluff sealed box, not an actual lockbox.
 "You pull on the rusted chains and they fall apart, unlocking the box..."
>telegun is complicated to make requiring telecoms parts and mind machine requires a special disk from cargo

You can get the required parts through a telecomms vendor (no RnD needed!). There's also the wormhole thing that was added a while ago. If memory serves me right, only natural (10%) or flawless (100%) crystals would link the singulos.
I imagine some ambitious cargoman building a singulo in cargo and one in the bar, linking them both then using it as transport. "Hey, wanna see my bar? *jumps into a singularity"

**Comment by Blithering** [comment]
> I think giving miners a mauler is a bad idea, the real treasure should be the fun bossfight. Like nobody kills Angie for the gloves, it's for the glory.

We have plenty of gundam mech sprites sitting around unused, could have a bossfight against one of those which drops a special mech painter on death?

**Comment by Kurfursten** [comment]
Could be neat. Although Eneo just finished complaining miners don't like to use mechs at all. I think I have an idea for something cool that isn't just a bigger murder machine but it will need to be a separate PR.

Perhaps a more productive discussion is whether or not the digsite depressor is a good idea. Maybe Eneo is right and miners would never buy this. Thoughts?

**Comment by Eneocho** [comment]
I've only seen miners use mechs around 20 times ever? And that's counting when the roboticist gave them a free one with no prompting required. It's less that it isn't useful and more that it is outclassed. If the Ripley moved at human speeds while in the roid it would immediately become a favourite.

**Comment by Eneocho** [comment]
The digsite depressor's main feature would work better as a secondary effect to an actual mining upgrade. Say, it mines in a + pattern (a weaker slime upgrade) and pushes digsites down. Or it drills 2 blocks ahead and pushes digsites down. It would be a good purchase for the miner and would have the (un)happy side effect of protecting the digsites for the benoarch.

**Comment by NigglyWiggly** [comment]
Diamond Drill sidegrade that mines slightly slower but instantly vaporizes artifacts in a radius around the drill

**Comment by Eneocho** [comment]
Absolutely NUCLEAR. I want it.
"Artifact Discombobulator, turns non-standard mining outputs into the selected material sample."
Essentially, you feed it a material (silver, for example), you dig around wrecking digsites. After a couple broken artifacts it spits out 5 sheets of refined silver. You could use it to semi-reliably farm phazon, at the expense of the xenoarch, and assuming you got some phazon to scan in the first place.

**Comment by Blithering** [comment]
I think the digsite depressor is a good idea, but not sure if it's something miners would care enough to buy themselves. I agree tying it into another item might help it's buy rate. A mech module that increased speed in zero atmosphere might make mech mining manageable? Perhaps that would be a non-murder part to be found in the graveyard?

**Comment by Kurfursten** [comment]
I have a couple of mech upgrades that will go in the second half of this crate, one of which speeds up the Ripley miner based on how low air pressure is. It's a good idea, but its coming in part 2.

**Comment by dinnerwoerror** [comment]
only 99 years and 9 months until the lost crates of lemuria will be discovered

**Comment by ErrorsWindows** [comment]
cargo's really gonna move on up in part 2

image

**Comment by SonixApache** [comment]
conflicts

**Comment by Eneocho** [comment]
I'd like to update my opinion on the miners and mechs. Now that ripleys move faster in vacuum, they are definitely worth using if possible, ideally with a mech diamond drill, so an upgrade that speeds them up even more so would be great. Or an upgrade that makes the drill zone wider (5x1 instead of the current 3x1).

**Comment by Kurfursten** [comment]
As you can see this is not derelict because I have made an update
- Resolved conflicts
- Coded cosmic grill
Remaining items (digsite depressor and mule paint) have been scrapped until next time, so instead each crate gives 5 items from the list instead of 6.

Just needs testing then it's ready

**Comment by SECBATON-GRIFFON** [comment]
tested a bunch of stuff, here's what i noted:

* the gibtonite satchel doesn't actually accept the gibtonite
* the cosmic grill with a preloaded pan doesn't actually render the pan when it spawns, and when update_icon() is called on it it goes blank. also i can't seem to take pans off of these but i don't know if i'm doing it wrong
* the goliath lure does spawn goliaths when placed down, but the bait seems to be not very functional nor does it actually lure goliaths in
* cargo rerouting computer works but has no icon

**Comment by Eneocho** [comment]
I've said it on other places, but the cosmic grill should probably be made into a regular cargo item, so miners can grill the frozen space monster meat so it's edible right then and there, maybe with a timer that freezes the cooked item's entropy for a minute or two so you can actually eat it without it immediately going -100°C

**Comment by Kurfursten** [comment]
I'll get around to fixing these some day

**Comment by Kurfursten** [comment]
This is so far from done (based on Kanef's research, which I appreciate) that I don't realistically think I can do this before summer if ever. It really shouldn't be kept open for years as a bad example.

**Comment by ErrorsWindows** [comment]
it's so over

**Pull request closed without merging**
