### PR TITLE
Changes the cost of picos to plasma.

### PR DESCRIPTION
**Pull request by DrSnips**
Changes the cost of pico manipulators to use plasma in place of the silver and uranium. Plasma is hardly used for anything in the protolathe and plasma isn't used in any other upgrade stock parts so this will finally give a use for the stack of 10,000 sheets of plasma miners hurl at mechanics and science.
:cl:
* tweak: Pico manipulators now use plasma in place of the old materials.

### CODE REVIEW

**Comment by ghost** [comment]
Sneaky sneaky

**Comment by SonixApache** [comment]
make a window plasmifyer that lets you use solid sheets of plasma on windows to turn them into plasma windows _and/or_ make plasma floors flammable

there, problem solved

**Comment by DrSnips** [comment]
I might make the plasmifyer also at some point, thats a neat idea. I will throw it on my wyci list. Im doing all ot these small PRs Ive had planned for small science improvements and crossing them off my list.

**Comment by FudgePucker** [comment]
How flameable would plasma floor tiles be anyways?
Casually burning like a camp fire, or would it release plasma into the air?
I find the thought of making a space station out of a violital fuel funny.

**Comment by SonixApache** [comment]
about as flammable as plasma doors and walls i'd say
burns away it's own tile, maybe damages the plating below (without melting it outright)

**Comment by ghost** [comment]
Plasma doors are their own unique kind of hell.

**Comment by DrSnips** [comment]
I don't like to let PRs to go into pr purgatory and the other PRs I've made got merged quite fast compaired to this one. I feel like it's the cost of them so Im likely going to double it.

**Comment by SonixApache** [comment]
This is not PR purgatory. Its been 5 days.

**Comment by DrSnips** [comment]
No, but I know when one is on the rode to it.

**Comment by SonixApache** [comment]
fix it up, make a poll, yell at collabs to merge it while pointing them towards the poll

**Comment by DrSnips** [comment]
Not really sure how to make a poll.

**Comment by SonixApache** [comment]
ask a min to make you a poll, i usually ask frukt

**Comment by Kammerjunk** [comment]
I made one and it'll last a week, but this isn't entirely a change we need an entire referendum on IMO

**Pull request merged**
