### PR TITLE
Face flag body part coverage changes.

### PR DESCRIPTION
**Pull request by ComicIronic**
Removed the HEADCOVERSEYES, MASKCOVERSEYES, GLASSESCOVERSEYES, HEADCOVERSMOUTH, and MASKCOVERSMOUTH flags.
Added the EYES, EARS, and MOUTH flags for body_parts_covered.
Added a proc for getting the item giving a flag, instead of just checking that it's there.
Made borers check for the EARS flag, instead of using HIDEEARS. More code now uses either get_body_part_coverage or check_body_part_coverage, instead of snowflaking.

Next on the chopping block are BLOCKHAIR and BLOCKHEADHAIR, which are going to be shoved into flags_inv.

### CODE REVIEW

**Comment by d3athrow** [comment]
Why would you add another proc for more overhead, whats wrong with checking a flag?

**Comment by ComicIronic** [comment]
The regular proc is just a binary return: is the body part covered by some item in the user's equip list?
The proc I added actually returns the first item found that gives the flag.

I also don't understand the second part of the question.

This does also remove a proc used only once in borer code, though. It about balances out.

**Comment by dylanstrategie** [comment]
If multiple items cover a bodypart, wouldn't it cause oddities when you return items. Does it even matter ?

**Comment by ComicIronic** [comment]
I could technically hardcode the proc into a tier system of it first returning the helmet, then the mask, then the eyes, or whatever.

I feel like that would be a hacky solution, though. Making a better version to take that sort of thing into account would require a bit more work than this PR.

**Comment by ComicIronic** [comment]
Damn you, conflcts.

**Pull request merged**
