### PR TITLE
Fix isvampire runtime

### LINKED ISSUE #16236: Null rod runtime on attack
[03:47:18] Runtime in null_rod.dm, line 47: Cannot read null.vampire
proc name: attack (/obj/item/weapon/nullrod/attack)
usr: Prospero Wang (kamen132) (/mob/living/carbon/human)
usr.loc: The floor (296, 254, 1) (/turf/simulated/floor)
src: the saint katana (/obj/item/weapon/nullrod/sword/katana)
src.loc: Prospero Wang (/mob/living/carbon/human)
call stack:
the saint katana (/obj/item/weapon/nullrod/sword/katana): attack(Unknown (/mob/living/carbon/human), Prospero Wang (/mob/living/carbon/human))
Unknown (/mob/living/carbon/human): attackby(the saint katana (/obj/item/weapon/nullrod/sword/katana), Prospero Wang (/mob/living/carbon/human), "left=1;screen-loc=7:15,7:11", null)
Prospero Wang (/mob/living/carbon/human): ClickOn(Unknown (/mob/living/carbon/human), "left=1;screen-loc=7:15,7:11")
Unknown (/mob/living/carbon/human): Click(the floor (295,253,1) (/turf/simulated/floor), "mapwindow.map", "left=1;screen-loc=7:15,7:11")
Unknown (/mob/living/carbon/human): Click(the floor (295,253,1) (/turf/simulated/floor), "mapwindow.map", "left=1;screen-loc=7:15,7:11")

### PR DESCRIPTION
**Pull request by WhiteHusky**
Fixes #16236
Also I'm pretty sure someone can test faster than I can right now because I was able to make this pull request on the web while I'm still downloading my fork.
Rural American internet is *graaaaand*.
:cl:
- bugfix: Using items that check if the mind is a vampire should no longer cause a runtime if the human had no mind.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
There is no need for / :cl: and for "CarlenWhite", AFAIK MoMMI knows how to read your name from the title of the PR

**Comment by SonixApache** [comment]
\*edited* format here is 
```
:cl:
- typeofchange: change text
```

**Comment by Exxion** [comment]
I'm not sure if it even knows *how* to parse the name after the :cl:

**Comment by WhiteHusky** [comment]
Yeah I wasn't sure what was the changelog format. I ended up using /TG/s guide since it said it was using the same guff /VG/ used.

**Comment by Exxion** [comment]
Oh, and @SonixApache got the changelog format a bit wrong
There should be a space between the hyphen and the `bugfix` so it makes a Markdown list
I'll just... fix it I guess

**Comment by WhiteHusky** [comment]
Managed to do a proper test this time. Took a human with no mind and whacked them with a rod pre-fix which caused a runtime error. Doing the fix and whacking them buldgens them propper.

**Pull request merged**
