### PR TITLE
Reduces cult endgame from 3 minutes and 20 seconds to 2 minutes

### PR DESCRIPTION
**Pull request by Zth--**
Our crew is getting bored

Did not test it

:cl:
 * tweak: Cult endgame now lasts 2 minutes instead of 3:20.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Next step: Having revolution not end after all the heads of staff are killed

**Comment by ArchSunder** [comment]
damn dudes can't you let the juggers have a few minutes to *spin and have flexing contests

**Comment by Kurfursten** [comment]
Shortening isn't a bad idea but 30 seconds seems extreme

Could we do it in such a way that it just makes Narnar float over onto the shuttle and immediately takes off when he arrives? That would feel more natural and give a nice variable but organic amount of time

**Comment by strawberrytan** [comment]
2 minutes like shuttle travel timer parity would be nice

**Comment by Zth--** [comment]
2 minutes it is.

@Kurfursten not a bad idea but I really don't want to spend time on this

**Comment by Zth--** [comment]
It was actually 200 seconds and not 5 minutes

**Pull request merged**
