### PR TITLE
Allows a bunch of symbols and accents in names.

### LINKED ISSUE #30604: Invalid name laxening
#### Description of issue

Character names currently can only contai the characters A-Z, a-z, -, ' and .

This is somewhat needlessly restrictive, especially when it comes to creating foreign characters. Here's a few examples of names that are completely valid but currently impossible to use (unless you're a silicon, which is somewhat hilarious)

Ċikka Farr
Fábián Benedek
Göktürk
Jérôme Mostinckx
Raperîn Nîwar

If a MoMMI can be literally named in Egyptian Hieroglyphics, I don't  think it's unreasonable to lax the filter just a little for people to allow for these completely realistic and plausible names.

#### Steps to reproduce
1. Create a new character
2. Enter a name with a non-english character based on the latin alphabet. (I'm sorry to anyone named 𓅱𓉔𓄿𓏏 𓏏𓉔𓇌 𓆑𓅱𓋴𓎡 𓂧𓇋𓂧  or 劉曉波 but your day to shine comes later. You may copy paste this character as an example : ú
3. Have name rejected

#### Specific information for locating

>Invalid name. Your name should be at least 2 and at most 52 characters long. It may only contain the characters A-Z, a-z, -, ' and .

#### Server revision

2d19efec36b8199ea67b75b2d5fa9b609a58a11c

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #30604. This PR keeps all of the functionality of previous name-checking (automatic whitespace trim, puting capitals after whitespace, etc.)

It currently allows for Latin-1 letters but the system is setup so that any special character can be added (as long as it has both a capital and a small letter). It also relies on the assumption that the letters are encoded with 2 bytes, which I /think/ is the majority of the extended latin table anyway (including slavic letters).

Tested to the best of my ability.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Ok, looks like I forgot a few cases.

**Comment by wotisjanitor** [comment]
I stand with the slavs. Add cyrillic support.

**Comment by Eneocho** [comment]
But does it fix the chat window/runechat scuff where all non strict ascii characters get turned into gibberish?

**Comment by ShiftyRail** [comment]
Goonchat should support Unicode. I will check runechat for that as well.

image

Yes, there's no reason runehcat shouldn't support it as well.

**Comment by Eneocho** [comment]
Many thanks. It's always an immulsion breaker when you upload a law to the AI that has " or ' and it turns into gibberish.

**Comment by ShiftyRail** [comment]
image

Again anything regarding goonchat is unicode and should support UTF-8.

**Comment by SECBATON-GRIFFON** [comment]
> I stand with the slavs. Add cyrillic support.

and ą and ć and ę and ł and ń and ó and ś and ź and ż

**Comment by SonixApache** [comment]
prepare for unforeseen consequences

**Comment by Eneocho** [comment]
I'd say they're totally foreseen now.

**Comment by Exxion** [comment]
See `sanitize_speech()` for the character ranges currently allowed in chat, if you want a reference for what to allow in names

**Comment by Exxion** [comment]
> But does it fix the chat window/runechat scuff where all non strict ascii characters get turned into gibberish?

Also this has been fixed for years

**Comment by pedr69** [comment]
while you're at it also fix `"` breaking the AI law stater

**Comment by ShiftyRail** [comment]
I will add some more symbols of the latin alphabet but I don't think there should be any Cyrillic support. 
People know how to read latin letters and can vaguely guess how the accented letters are pronounced. 

I don't think most people would know that "Дмитрий Медведев" is actually "Dmitry Medvedev" and not "Amntpnn Meabeaeb".

**Comment by Hinaichigo** [comment]
One thing is that most people won't have these keyboards installed so if someone has an accent in their name, it'll probably almost always get 'mistyped'
Like for example if their name is Ödie or something, people would just say 'hey Odie'.

**Comment by Eneocho** [comment]
> I will add some more symbols of the latin alphabet but I don't think there should be any Cyrillic support. People know how to read latin letters and can vaguely guess how the accented letters are pronounced.
> 
> I don't think most people would know that "Дмитрий Медведев" is actually "Dmitry Medvedev" and not "Amntpnn Meabeaeb".

That interaction sounds funny though. Could do for some lost in translation/transcription interactions: 
```
>oh hey amntpnn
"my name is not amntpnn, it's Dmitry"
>well, how was I supposed to know?
```

**Comment by ShiftyRail** [comment]
> Like for example if their name is Ödie or something, people would just say 'hey Odie'.

True, but that one is clear enough in context. I don't think it would be a big problem.
I'll add the ones ~~kanef~~ @SECBATON-GRIFFON suggested and then it should be good to go.

**Comment by Hinaichigo** [comment]
One potential issue though is Syndicate agents having people's names as codewords. If the name has accented characters, 'Odie' wont have the codeword red highlighting (and also wont trigger the non-scrambling in #34131). So if someone specifically pastes the accented 'Ödie', it could allow some form of metagaming as people would wonder why they went through the trouble of doing that.

Maybe converting accented characters to their non-accented versions for the purposes of those checks could help avoid that.

**Comment by ShiftyRail** [comment]
Good point. Can always adapt the syndie codeword detection.

**Pull request merged**
