### PR TITLE
Lowers the money in the vault freezer

### PR DESCRIPTION
**Pull request by Kharkov72**
With the economy rework this stash went from a lot of money to way too much money, so I'm gonna reign it in a bit.

:cl:
 * rscdel: Vault Freezer has less money

### CODE REVIEW

**Comment by DamianX** [comment]
downvoted because removal

**Comment by MadmanMartian** [comment]
upvoted because balance

**Comment by boy2mantwicethefam** [comment]
Confusion

**Comment by FudgePucker** [comment]
Awesome.
Cool.
Great.

**Comment by Kharkov72** [comment]
oy vey

**Comment by SonixApache** [comment]
why did you close this exactly

**Comment by MadmanMartian** [comment]
9 downvotes

**Comment by SonixApache** [comment]
emojicracy is a joke, 6700 credits that nobody cares if you steal is a very stupid thing to have after the economy changes

**Comment by FudgePucker** [comment]
>muh economy

**Comment by MadmanMartian** [comment]
don't act dumb

**Comment by FudgePucker** [comment]
>emojicracy is a joke

Didnt stop it from being the justification for a major knee capping of the miner income, MONTHS after the PR was created, WEEKS sense the last discussion on it.
Also
>Nobody cares if you steal

ALMOST LIKE NOBODY GIVES A SHIT ABOUT THE ECONOMY
ALMOST LIKE THE JUSTIFICATION FOR THESE CHANGES (the black market) HAS BEEN MEMED AND SHITTED ON

**Comment by agentofzog2** [comment]
just remove all the ways you can make money besides collecting your wages
this is economy
we are gud coders
yes we'll surely include a balanced way to make money by the year 2025

**Comment by SonixApache** [comment]
\>The economy doesn't matter because the economy doesn't matter!
\>Stop trying to fix the economy, don't you know that the economy doesn't matter?!

**Comment by agentofzog2** [comment]
Of course it doesn't matter retard, we don't have an economy, we just have everyone collecting their bi(or was it tri)hourly tugboat and then few ways to actually afford the expensive stuff. Oh and mining for two hours straight to get like a thousand bux. 

ahem
FUCK COMMUNISM

**Pull request closed without merging**
