### PR TITLE
vector does more damage

### PR DESCRIPTION
**Pull request by 9percents**
Vector does more damage with regular .380. That's all. Yes, I like it, the gun is cool but ammo issue for it has only become worse after removal of easy .357/shotgunshell alternative. A lot of people has expressed their discontent with it and it doesn't really see much use. Now along with being recoilless and better damage it will become a valid choice of a ballistic weapon.

[tweak]

:cl:
 * tweak: Vector now does more damage with regular .380 ammo.

### CODE REVIEW

**Comment by BomberBro** [comment]
speedclosed...

**Comment by 9percents** [comment]
coders are afraid of the big gun

**Comment by aceedex** [comment]
Bruh. Ita a 4 damage increase on a 15 damage gun.

**Comment by cowboybuttsdrivemenuts** [comment]
bruh

**Pull request closed without merging**
