### PR TITLE
Soda cans can be ground into aluminum

### LINKED ISSUE #12167: Grinding soda cans nets you NOTHING
#### Description of issue

You can grind soda cans in ghetto mortars, but they don't give you anything. You don't even get the contents of the can if it's not empty. Would be a good source of ghetto aluminum.
#### Difference between expected and actual behavior

Expected:
Grind empty soda can into dust -> receive aluminum and some tin
Actual:
Grind soda can into dust -> receive nothing
#### Specific information for locating

/obj/item/weapon/reagent_containers/food/drinks/soda_cans/cola
-> 
/obj/item/weapon/reagent_containers/glass/mortar
#### Length of time in which bug has been known to occur

Since ghetto chem.
#### Server revision

763239efe8644c09c5f7d3859852df5207adfa21
#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by SonixApache**
Seems like a useful step in buffing ghetto weaponry.
Mostly resolves #12167 because I'm a lazy cunt who can't code for shit.

### CODE REVIEW

**Comment by Exxion** [comment]
Make it so that you can do it with an actual grinder too

**Comment by SonixApache** [comment]
There's a buncha shit that can only be ground in a mortar, though.

**Comment by Exxion** [comment]
That's dumb as shit though

**Comment by SonixApache** [comment]
I mean, yeah, but if we change that the ghetto chemists might start complaining.

**Comment by Exxion** [comment]
Why would ghetto chemists complain about actual chemists being able to do more things?
They're ghetto for a reason

**Comment by SonixApache** [comment]
That was more or less a joke. Can you stick soda cans in a grinder in the first place? Because you can stick them in a mortar, that's why I made this.

**Comment by Exxion** [comment]
Hell if I know
Probably not
The grinder and mortar don't run on the same code
Or really even similar code

Who wants to abstract reagent grinding to a datum?

**Comment by SonixApache** [comment]
Not me, I just want to crush cans into aluminum.

**Comment by Exxion** [comment]
Yeah alright.

Add a changelog though

**Comment by SonixApache** [comment]
Changelogs are overrated for tiny shit like this -- gonna update the wiki, though.

**Comment by Shadowmech88** [comment]
How else are people to know that it's a thing you can do now, unless it's in the changelog?

**Comment by SonixApache** [comment]
I told them in OOC once and I updated the wiki.
BYOND that? trial and error + seeing someone else do it.
Took people a while to figure out that packagewrapping was fucked, and then took them a while again to figure out when it was unfucked.

**Pull request merged**
