### PR TITLE
Remove Doctor's Delight from possible code words

### LINKED ISSUE #24079: "doctor's delight" does not function properly as a code word
even when you copy and paste it from your notes, it does not show as red. thanks byond for handling apostrophes well

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #24079

:cl:
* bugfix: Removed Doctor's Delight from the possible syndicate code phrases due to Byond not liking the apostrophe.

### CODE REVIEW

**Comment by DeityLink** [comment]
It could probably be fixed by doing some regex fuckery to check the text without apostrophes but we could do that, or we could just remove the one possible code word that includes an apostrophe.

**Comment by DamianX** [comment]
What part of BYOND doesn't like it?

**Comment by DeityLink** [comment]
> 
> 
> What part of BYOND doesn't like it?

the part about apostrophes being used in strings apparently, not sure if it fails on the codeword part or the saycode part. Like I said you could use regex to remove apostrophes in a temp var to perform the actual check and that'd probably fix it, but whatever.

**Comment by DamianX** [comment]
If it's not displayed properly in chat or windows you need to `html_encode` it before displaying it. There's no reason why you shouldn't be allowed to have apostrophes in strings.

**Comment by DeityLink** [comment]
> 
> 
> If it's not displayed properly in chat or windows you need to `html_encode` it before displaying it. There's no reason why you shouldn't be allowed to have apostrophes in strings.

It's not a display issue, since you can use apostrophes just fine in chat. It's the code not realizing that what the player says IS a syndicate codeword.

**Comment by DeityLink** [comment]
welp

**Pull request closed without merging**
