### PR TITLE
Janitors get a sodium poly spray bottle.

### PR DESCRIPTION
**Pull request by Eneocho**
Desperate need for these, the lube puddles don't disappear and can't be cleaned normally.

:cl:
 * rscadd: Janitor closets have a sodium polyacrilate (anti lube) spray bottle, to assist the puddle cleaning efforts.

### CODE REVIEW

**Comment by Kurfursten** [comment]
If lube puddles *never* go away that seems like something that should be addressed directly instead of giving janny stuff he should go to chem for

Like how the response to puddle problems shouldn't be to give him a roundstart cleaning module for the janicart

**Comment by WindowsErrors** [comment]
is there any other way to clear puddles?

if not, then it's literally impossible for the janitor to perform a fundamental aspect of their role at round start

**Comment by Kurfursten** [comment]
Mops are supposed to kill puddles as long as you wet them with water (or if the puddle is very shallow it takes no water at all)

If lube puddles are somehow specially bugged (I believe it), we need to fix that instead

**Comment by Spaceman33333** [comment]
Revert the puddle abomination, no more problems and bloat necessary to deal with this shit

**Comment by Eneocho** [comment]
Closing this since kanef fixed the uncleanable lube. HE ALSO NUKED ALL LUBE PUDDLES, THE MONSTER.

**Comment by Eneocho** [comment]
Actually no. Fuck this. Rework the lube puddle fix to not nerf it to the ground.

**Comment by DamianX** [comment]
huh?

**Comment by Eneocho** [comment]
Forgot bout this one after that puddle unmerge. Closing because muh non-nu puddle lube.

**Pull request closed without merging**
