### PR TITLE
Dynamic mode lowpop ruleset: Roundstart Away Missions

### PR DESCRIPTION
**Pull request by ghost**
[content][gamemode]
Idea suggested by @BomberBro 
Rolls most frequently on 0-5 pop, then with 40 minimum threat on 5-10, 80 on 10-15 before slowly tending towards 100 near the end.
:cl:
 * rscadd: Away missions can sometimes be found at the start of dead shifts.

### CODE REVIEW

**Comment by BomberBro** [comment]
I was suggested this for lowpop but somebody else pointed out that these tend to depop the station, so I'm pretty ambivalent.

**Comment by PrimeDSS13** [comment]
away missions are not lowpop things

**Comment by gurfan** [comment]
this isn't the solution

**Comment by SonixApache** [comment]
lowpop is the opposite of when away missions should be fired

also we need more away missions to really do this

**Comment by ghost** [comment]
Bomber is against it now

**Pull request closed without merging**
