### PR TITLE
fixes #7723

### LINKED ISSUE #7723: Mimewall emote text was written by someone who doesn't actually speak English
image

### PR DESCRIPTION
**Pull request by Arthurdentist**
pomf told me to literally just change surfacing so I did edition. 

inb4 everyone jumps down my throat again because my (british) english dictionary disagrees with them. 

fixes #7723

### CODE REVIEW

**Comment by Kurfursten** [comment]
Dammit Arthur I keep telling you stop being lazy and use gendered pronouns. You are **going** to learn how to use \his

**Comment by Arthurdentist** [comment]
'pomf told me to literally just change surfacing so I did edition.'

**Comment by Kurfursten** [comment]
One of the two of you is getting deep fried tonight, this is your opportunity to make sure it isn't you

**Comment by Arthurdentist** [comment]
code\modules\spells\aoe_turf\conjure\forcewall.dm:20:error: "mimes placing \his hands on a flat surface, and pushing against it.": macro \his requires preceeding expression

wew lad

**Comment by PJB3005** [comment]
Damnit thanks BYOND, it's because of the way macros work.

That's probably why it's not `\his` in the first place.

**Comment by Kurfursten** [comment]
oh yeah, this is kind of a weird place to use \his because you aren't referencing anything, it's in the invocation

what @PJB3005 said, you get off this time

**Comment by Exxion** [comment]
It gets confusing if you use "their" like that constantly, but there really isn't a problem with using it that way occasionally.

**Comment by gbasood** [comment]
:+1:

**Pull request merged**
