### PR TITLE
Botany additions

### PR DESCRIPTION
**Pull request by ghost**
Adds another botany locker, adds a spade, plant clippers and a bucket to each botany locker.

Moves xenobotany machines one tile to the east, moves contents of one table into the botany hydroponics crate.

Should fix https://github.com/d3athrow/vgstation13/issues/3192 and https://github.com/d3athrow/vgstation13/issues/3166

### CODE REVIEW

**Comment by TermedClepe** [comment]
Please tell me this is the correct way to do it.

**Comment by SkowronX** [comment]
Redo the map changes.

**Comment by TermedClepe** [comment]
What do you mean?

**Comment by SkowronX** [comment]
Get the most recent version of tgstation.dmm and redo your changes.

**Pull request closed without merging**
