### PR TITLE
Re-adds the Autoborger Cooldown. (Reverts #26158)

### PR DESCRIPTION
**Pull request by PrimeDSS13**
Reverts #26158

Going from a 90 second autoborger to a 0 second autoborger was a huge mistake. Nobody likes speedrun rounds where the malf borgs 4 people rapidly, and then it spirals into an infinite cyborg army that is impossible to defeat where everyone has to wait 10 minutes for the timer to tick down because no APC's are hacked.

:cl:
 * tweak: autoborgers have a cooldown again

### CODE REVIEW

**Comment by ghost** [comment]
90 seconds is a lot, but I would rather have 90 second cooldowns than fifteen secborgs at 12:15

**Comment by Manleto** [comment]
I think this would be good if the tower defense mode was buffed to compensate. Maybe the turrets get increased range?

**Comment by ShiftyRail** [comment]
I predicted this

**Comment by N3X15** [comment]
I think we need to sit down and have a real discussion about how to balance this thing properly rather than throwing PRs at it and seeing what sticks.

**Comment by Zth--** [comment]
Okay but let's actually have the discussion.

I will merge this PR and move this discussion here -> #28161

**Pull request merged**
