### PR TITLE
MaMIs don't decay

### PR DESCRIPTION
**Pull request by Kurfursten**
As a child of brains (haha, brainchild) they decay. No more.

### CODE REVIEW

**Comment by ComicIronic** [comment]
If you're fixing MaMIs, can you add the check to MMIs to not accept MaMI brains?

**Comment by Kurfursten** [comment]
@ComicIronic Okay, I'll fix it when I fix my shitty code

**Comment by SkowronX** [comment]
Bodyscanner does not recognize a Mami. Also if I remember correctly, debraining a Mami human gets a regular brain.

**Comment by d3athrow** [comment]
buuugs

**Comment by Kurfursten** [comment]
This PR still doesn't fix MaMIs in surgery. Oh well, though. Maybe that's a bugfix for another day.

**Pull request merged**
