### PR TITLE
Adds a new hairstyle.

### PR DESCRIPTION
**Pull request by ghost**
Adds the Kanade Sakurai hairstyle.  Spriting courtesy of Dizor (you rock!)

## The Hairstyle
29gqfwr
fpgtxhx
p8whouj
mztir2x
lypmrj1

### CODE REVIEW

**Comment by Ephx1** [comment]
I'm sure this'll be put to _great_ use.

**Comment by 9600bauds** [comment]
Where's my eyeroll emoji

**Review by PJB3005 — APPROVED** [review]

**Comment by kol1th** [comment]
It looks better than I expected

**Comment by Lokiamis** [comment]
Fuck off

**Comment by JustSumBody** [comment]
do you feel it
another "CONTROVERSIAL" PR

**Comment by kol1th** [comment]
@Lokiamis Glad to see you making more quality contributions to the repo!

**Comment by AI-Is-Rogue** [comment]
Why fus.

**Comment by Zth--** [comment]
I think these kind of PRs encourage more waifu shittery and I'm against it

**Comment by Lokiamis** [comment]
@kol1th 
>As a romantic school comedy setting,[1] the story focuses on the budding romantic relationship between Kanade and Yukino Sakurai, twin sisters in their second year in a Tokyo high school, and the conflict provided by freshman Sakuya Kamiyama's feelings towards Kanade.[5]

Are you really going to hold a github grudge because I gave you a thumbs down, Kolith? Unique anime hairstyles belonging to 16 year old incest yuri schoolgirls should absolutely fuck off.

**Comment by FudgePucker** [comment]
:+1: Oh boy not only is it a well sprited new hair style, its from a yuri twincest VN? 10/10 PR of the month.
Also at least it isn't those horrid TG floor length hair styles.

**Comment by kol1th** [comment]
@Lokiamis You DO realize most of the hairstyles we have are from anime, right?

**Comment by Ephx1** [comment]
If you look at it from his pov that's a terrible argument.
To him that's like saying "You do know you have cancer right? What's wrong with a little more?"

**Comment by ThePlapatin** [comment]
two thumbs up for all my anime friends out there

**Comment by SkowronX** [comment]
pffff ahahahaha

**Comment by Probe1** [comment]
You people need to get a hobby that isn't getting mad about hair.

**Comment by SangriaMonkey** [comment]
:pizza:

**Comment by Probe1** [comment]
🍆

**Pull request merged**
