### PR TITLE
Hostile mobs smash objects towards their target, rather than everywhere

### PR DESCRIPTION
**Pull request by Sprok0**
Hostile mobs that can smash windows and such will now only smash things in the direction of their target, rather than in all directions at the same time.

Also moved some related procs out of the giant unsorted.dm

### CODE REVIEW

**Comment by clusterfack** [comment]
Can you make it work like this, then?
plsdothis

**Comment by Sprok0** [comment]
I'll try, but first I must sleep

**Comment by Sprok0** [comment]
I think I did it

**Comment by Intigracy** [comment]
Does it work?

**Comment by Sprok0** [comment]
carp2

**Comment by clusterfack** [comment]
Better than expected 👍

**Pull request merged**
