### PR TITLE
Monkey Business

### PR DESCRIPTION
**Pull request by JustSumBody**
~~punpun1 is an icon of him with the suit on but he doesn't spawn wearing one, so he's naked but not~~

**Intigracy edit:**
makes punpun subtype that spawns with pun pun's suit and name
puts new punpun subtype on maps
removes punpun1 icon_state so people don't use it again
makes the way monkeys generate random names more subtype friendly than having to manually map edit them in(set the real_name on the subtype if you don't want the random numbers added)

organizes the mess that was monkey.dm so it's monkey define, then new()/destroy(), then subtypes/subtypes new(), then the misc procs

fixes grey monkeys not turning into greys correctly (missing greaterform)

🆑 
* imageadd: "Pun Pun is now snazzily dressed on every map, and his suit is removable."

### CODE REVIEW

**Comment by ghost** [comment]
What's next, removing his underwear because you can't take that off too, you sick furry fuck

**Comment by Intigracy** [comment]
Have him spawn wearing a suit.

**Comment by SonixApache** [comment]
@Intigracy I wish github had a WYCI reaction option

**Comment by Exxion** [comment]
It's very unfortunate that GitHub doesn't accept emoji other than those six if you edit the page source, etc.

**Comment by Intigracy** [comment]
Custom emoji on github when

**Comment by ghost** [comment]
Is this some kind of parasitic PR?

**Comment by SonixApache** [comment]
he actually coded it the absolute madman

**Comment by NigglyWiggly** [comment]
monkey

Mega-Monkeys when

**Comment by Intigracy** [comment]
it's not a self merge guize it has justsumguy's name on it :^):^)

@NigglyWiggly if you actually want those added give me dmis with the suit sprites/object icons

**Comment by JustSumBody** [comment]
> niggly actually giving anyone his sprites

Good joke friend

**Pull request merged**
