### PR TITLE
changes the cost of revolver ammo from 4 tc to 1 tc

### PR DESCRIPTION
**Pull request by SirSkeleto**
[balance] [powercreep]
you can literally make this at any autolathe with just metal
why is it 4tc
also see #22630

:cl:
 * tweak:  lowers the cost of ".357 Ammo" from 4 -> 1 TC

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Real shit?

**Comment by aceedex** [comment]
Takes a while to print and marks a location where you need to be around, as opposed to spawning the item when needed

**Comment by SonixApache** [comment]
revolver murderbone is cheap and easy and overdone, no need to make it even cheaper

**Comment by Kharkov72** [comment]
as it stands, revolver is just worseradgun, so some touching up couldn't hurt

**Comment by SonixApache** [comment]
Radgun: 
- 1 shot is a probable kill due to rads and toxins unless treated soonish
- 2 shots is a definite kill unless target is protected against rads | unless treated immediately (But you're stuck vomiting anyway)

Revolver:
 - 1 shot is a possible kill due to internal bleeding unless treated soonish
 - 2 shots is a definite kill unless target is armored | unless treated immediately (But you're in crit anyway)

i dunno bro

**Comment by ShiftyRail** [comment]
Radgun self-recharges.

**Comment by Ratvar** [comment]
Revolver has infinite charges because you can store ammo

**Comment by Accipitermaris** [comment]
>Revolver has infinite charges because you can store ammo

One must print the ammo, either by buying it for 4 TCs or by printing more at a hacked autolathe. (Which begs the question: If you can print .357 at a hacked autolathe, why does .357 ammo cost 4 TCs? Hence the PR.)

**Comment by Ratvar** [comment]
Maybe problem is hacked autolathe and not the TK cost?

**Comment by Allspice** [comment]
Dunno if I'm just missing it every time, but I rarely see revolver murderbone. Just putting that out there.

**Comment by LordMyroc** [comment]
For comparison, 1 TC gets you a bar of soap or a toolbox, both of which you can find all over the station. TCs aren't worth THAT much. Just reducing it to 2 TCs per box would in itself be a major buff as it effectively triples the amount of ammo a tator can buy with the 7 TCs left after buying the revolver.

**Comment by Blithering** [comment]
Maybe if the syndicate order came in a speedloader instead of a box it would be worth the tc cost? 
Edit: wait no, I'm retarded, it does. instant reloads are nice though

**Comment by Kurfursten** [comment]
Ask again later
t. Magic Emoji Ball

**Pull request closed without merging**
