### PR TITLE
Revert "Air Tank Sprite Port"

### PR DESCRIPTION
**Pull request by Probe1**
Reverts d3athrow/vgstation13#13934

http://ss13.moe/index.php/poll/94
image

### CODE REVIEW

**Comment by yclatious** [comment]
Told you itd be reverted Probe.

**Comment by Blithering** [comment]
Democracy has proven once again that change is scary and bad.

**Comment by AutismSpider** [comment]
@Blithering Make the new sprites look less ass then. its why people want the old ones back

**Comment by eplgr** [comment]
The sprite was added 3 days ago, if you wanted to see what people'd say after a while, then not enough time has passed, and if you were waiting for the serbvote, then I don't get why you didn't do that before actually merging it.

Either way, this is not a democracy.

@AutismSpider No, no matter what they are changed to, people will **always** complain.

**Comment by yclatious** [comment]
Probe said he was going to revert it if after 3 days people clearly did not like it, if you think that one more week is somehow going to make people like it more, you are a idiot.

Claiming that we are no democracy when probe said that he was going to take votes into account makes no sense and is just you being salty and wanting it to stay in. Suck it the fuck up buttercup, people have clearly said no, they will say no in a week or a month, Ill suck it the fuck up when you fuckos try and force Attack animations in, so you suck it up too when you lose your precious little artyle breaking sprites.

**Comment by eplgr** [comment]
I am not salty and you didn't get the point, which was:
Many sprites are old and ugly, people are used to them, and when someone comes with a better one, even if it's infinitely better than the old one, people will complain about it.

I don't even care about this specific sprite. But I do care about the stupid arguments that were put against it.

Example that happens every single time: people totally believe some sprites do not fit our theme. It's wrong to talk about that because we don't have a fixed style in first place, we don't have a style at all, but what you can do is slowly and progressively add sprites that are better and *do* have a style.
Some people actually proposed that. The problem is, you can't expect it to happen all at once, and you don't even let these people *start*.

**Comment by yclatious** [comment]
There is starting to improve and there is letting a bunch of complete "stick in the mud" sprites be about when they look completely out of place and would look out of place for atleast a few months until new ones would come along and be added, if they would even be added.

These were shit. Brightly coloured, outlined sprited shit, you can call our basic sprites shit all you want and its within your right to think so, but few, if any of them have the same perspectives, extremely bright palette or blend in well with these. If you were to actually compromise between this bright bullshit and what we currently have, I would gladly accept it but no, it has to be this shit that was told by many would clash too hard, no, had to be this, you couldn't do it gradually like almost everyone would have liked it to be, just shellshock with shitty and shiny bright yellow plasma tanks and awful looking red ones, just hit me up with that awful color palette, yeah, that's a great start, making my eyes bleed when I find some shitty out of place air tank in maint or making me cringe at a completely out of place and bizarre perspective on the plasma ones when Im seeting a SME up.

You want change? You want a spriting change, a upgrade from what we currently have? You compromise between both styles instead of making a sudden shift when nothing else even remotely looks like it. Don't you bullshit me with "But we can do it progressively!" if you can't even recognize this isn't progressive, its a bunch of regularly used items that stick out like a white dude in the Congo, its shit, and if you want a actual sprite change, follow my damn advice instead of thinking like some butthurt little shit that thinks people hate any and all change instead of hating sudden, shocking, and to them, bad change. Get a grip and realize that if you want any kind of change that to some are radical, you have to compromise or get shot down by the people you are trying to place the change on.

**Comment by SonixApache** [comment]
Serb vote says they look like ass.
Most people agree that they look like ass.
This isn't "Serb is afraid of change!" -- this is "Serb thinks this looks like ass!"

My opinion on the matter is this;
They just don't fit with our style, they look jarring and weird. Colors are too bright, contrast is weird, perspective is weird. They look oddly high-tech/high-detail compared to everything else. If this was part of some sort of mass re-imaging scheme, I might be okay with it, but in it's current state it just doesn't fit.

**Comment by Lokiamis** [comment]
we don't have a style so I'm going to replace our syndicate mobs with this guy because the sprite's really good. 

metal_slug_tarma_roving_dispara

**Comment by eplgr** [comment]
@yclatious I love the fact that you went from
>Those sprites look damn good

to

>These sprites were shit

But it's okay, at least I got you to finally write a proper column of arguments.

**Comment by yclatious** [comment]
Seeing them at a standstill alongside other stuff that looks within the same artstyle makes it look good, whodafigured the oposite holds true.

**Comment by Intigracy** [comment]
The simple sprite is charming when viewed with other simple sprites.

The problem is when it's made more detailed and it stands out from everything. You can argue that the new sprite is 'better' (which is 100% opinions) but when compared to everything else it looks shitty.

**Comment by Kitfox88** [comment]
@Lokiamis not seeing a problem man

**Comment by kol1th** [comment]
I'd say it's about the same quality as airlocks.

Also, Probe (and most people on this Github) are pretty revert happy with anything, and I don't really care much. 🤷‍♂️

**Comment by gbasood** [comment]
I think we can get a simple looking sprite that still looks better than what we had.

**Comment by N3X15** [comment]
Oh esus christ shut the fuck up

**Comment by Probe1** [comment]
"Okay guys I know that the "No" side is winning but it's really close and I'm going to put it to the server for a vote"

"Well guys it looks like the server overwhelmingly doesn't want it"

"_fuckin shitlaborators reverting PRs_"

**Comment by kol1th** [comment]
Well no, I'm not referencing this specifically. Just the github and people's attitudes in general.

**Comment by Exxion** [comment]
OK, after seeing the sprites in-game, I agree they were really out of place

**Comment by Intigracy** [comment]
I'd rather have people call for revert too much than call for revert too little/never.

**Comment by ihadtoregisterforthis** [comment]
I'd rather have people reach an agreement before merge instead of a loud group rushing merges and a rival loud group demanding reverts

**Comment by gbasood** [comment]
@ihadtoregisterforthis consensus is basically non existant in ss13 dev

**Pull request merged**
