### PR TITLE
moves the polar star and gun parts to xenoarch

### LINKED ISSUE #6994: Spur and Polar Star can be bruteforced really fast
Surround yourself with rocks containing artifacts/dig sites, spam your excavation strength 1 duster on all surrounding rocks until you get spur/polar star.

It shouldn't be this easy to get an auto recharging combat shotgun.

### PR DESCRIPTION
**Pull request by MadmanMartian**
closes #6994

### CODE REVIEW

**Comment by DrSnips** [comment]
Inb4 miner assblasting

**Comment by yclatious** [comment]
Whats exactly the issue with miners getting polar stars and what not?

**Comment by DrSnips** [comment]
Read the issue it resolves first.

**Comment by yclatious** [comment]
I did read it, honestly I dont see any actual issue with miners getting polars and what not, I got them even when directly avoiding the digsites as to not get shot by xenoarchs and still got them, and truth be told, spurs were rare as shit when I mined and not much better than my current stuff as I always carried a couple protos to deal with mobs in the roid.

**Comment by ghost** [comment]
welfare gunz

**Comment by SkowronX** [comment]
polar star + upgrade is a pretty unreliable weapon as miner

**Comment by aceedex** [comment]
doesnt seem like anything but a "ha ha fuck you miner" PR
when is the last time a miner went on a rampage and killed the entire station with a polar star?

**Comment by Exxion** [comment]
Someone shooting up the station isn't the only reason to change how something works.

That said, if I'm reading this correctly, it looks like it makes the weapon *preposterously* rare, requiring an average of 200 gun artifacts to be dug up to get the Spur.
I believe this would be described as overcorrection.

**Comment by FudgePucker** [comment]
:-1: why not just make it where xenoarch actions don't have a chance to spawn it? Just make it drop when mining a new turf of asteroid. This PR is the oppisate of what it should be.

**Comment by Exxion** [comment]
That's how it currently is, Fudge.
Digsites have a doubled drop chance, but you're still more likely to get it from regular rock because there is *far* more than twice as much of it

**Comment by Exxion** [comment]
Or actually it's quintupled, I think
But there's still a lot more normal asteroid

**Comment by Hugh-G-Rection** [comment]
It was a dumb issue in the first place, I rarely ever see the weapon used, but if you're going to fix something about it the issue is that dusting has a chance to find it. Fudge's suggestion is the only solution that makes sense.

**Comment by ghost** [comment]
I think it's stupid that you just up and get a free supergun if you're the first person to go mining. Bad meme, bad feature.

**Comment by yclatious** [comment]
>First to go mining
>Free super gun

Alright, what is this meme, the majority of shifts I went miner I never even got a polar star, and the polar star already fucking blows massive dongs mkay, the few I got a polar I didnt get parts and the few I got parts and polar, I used it as a glorified proto kinetic as stuns still rule as king so its kinda useless for slaughtering as a miner sticks out like a sore thumb and ;MINER MC DORF IS KILLING ME would happen, we still stand by tase and lase, stun and done, if I wanted a super weapon id just get a plas cannon and nig some tasers with the drill I inevitably got.

Its a decent weapon thats balistic in nature, a laser gun is way better in terms of reliability as hitting a running away target is kind of a bitch, its 60 brute but only really used for roid murder, its great for instacritting people that think you arent going to kill them but honestly, with the rarity it generaly has, id argue nigging a plasma cannon would be just as great for equaling instadunking due to its relatively high fire rate and 50 fucking burn. Las cannon however would still be better for all around combat as you dont rely on balistic physics that can be juked rather than instant laser fire across a hall, alongside science being more perceptive to that and being easier than depending on RNG minan.

**Comment by SonixApache** [comment]
maybe not do this and just lower the drop chances instead

**Comment by DamianX** [comment]
Is this going anywhere?

**Comment by MadmanMartian** [comment]
Entirely up to the community

**Comment by DamianX** [comment]
http://ss13.moe/index.php/poll/136

**Comment by DamianX** [comment]
Closing as the vote didn't pass

**Pull request closed without merging**
