### PR TITLE
Ports TEEGEE

### PR DESCRIPTION
**Pull request by Mothblocks**
:cl:
* rscadd: Ported TG

### CODE REVIEW

**Comment by chesse20** [comment]
█▄░▄█░█▀▀░█▀▀▀░ █▀█  
█░█░█░█▀░░█░▀█░█▀▀█
▀░▀░▀░▀▀▀░▀▀▀▀░▀░░▀
█░░█░█░▀▀█▀▀░█▀█░ █▀█  
█░░█░█░░░█░░░█▀▄░█▀▀█
▀▀▀▀░▀▀▀░▀░░░▀░▀░▀░░▀
█▀▀░█▀█░█░█▀▀
█▀░░█▀▀░█░█     
▀▀▀░▀░░░▀░▀▀▀
░░░░░░░░░░░░▄▄                     
░░░░░░░░░░░█░░█                  
░░░░░░░░░░░█░░█                  
░░░░░░░░░░█░░░█                  
░░░░░░░░░█░░░░█                  
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░ /vg/, ░░░░░░█ 
 ▓▓▓▓▓▓█░░░░Add This░░░░█  
▓▓▓▓▓▓█░░░░Please!░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█   
██████▀░░░░▀▀██████▀

**Comment by ghost** [comment]
Does not conflict with secret repo :thinking:

**Comment by Probe1** [comment]
THE MADMAN

**Comment by MadmanMartian** [comment]
fix the conflicts

**Comment by Mothblocks** [comment]
@MadmanMartian alright but it'll probably take another hour to push that commit, once i actually figure out how to do it with this monstrous repo

**Comment by Mothblocks** [comment]
@MadmanMartian Done. This is now ready to speed merge with no thought.

**Comment by SonixApache** [comment]
goddamnit

**Comment by Mothblocks** [comment]
All tests passed! 😄

**Comment by SonixApache** [comment]
shouldn't the title be "port TG" ?

**Comment by Jalleo** [comment]
Good thing this is a joke. VG department budget stuff is a good mechanic.

**Comment by Jubisloviu** [comment]
\>VG
you have to go back

**Comment by Mothblocks** [comment]
I am extremely disappointed in the /vg/ coderbase for not merging my PR. You will feel my wrath soon enough. Until then, I will close this...

**Pull request closed without merging**
