### PR TITLE
Adds a toggle for cult word research

### PR DESCRIPTION
**Pull request by MadmanMartian**
The toggle function currently does not work and I'm too tired to try and find why, so will take a look at it when I get up later.

What this basically does is, should the toggle be true, then tomes words are already filled in. You still have to scribe a rune word for word, but now your words are translated.

### CODE REVIEW

**Comment by Irradiation** [comment]
I'm going to wager that even with cult research being free when an admin toggles that function, people will still spill the spaghetti early in the most classic of ways.

**Comment by Allspice** [comment]
Different phrasing for atomicity: "Removes research, adds toggle in case shitmins want to put it back in for some reason"
like the whole attack animations thing

**Comment by jknpj** [comment]
when

**Comment by jknpj** [comment]
It's been too long already so i'll just slap derelict on this. Ping us in the coder discord when you want it reopened.

**Pull request closed without merging**
