### PR TITLE
Explosive fuel + tank explosions with fuel in them

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
updates welderbombing to allow any is_hot() item to blow any reagent dispenser up that has fuel in it, except for cauldrons or any non-fueltank type tank without fuel. (arcane tamper effects are updated for this too)
allows them all to hold rig assemblies too.
makes fuel itself react as a reagent on high temperatures, (288C, fuel autoignite temperature) creating a fire in an open container and a weak explosion in closed ones. (with the same volume calculations as a fueltank, so a welderbomb size boom would need a reagent container holding at least 500 fuel to breach, weaker than potass+water) updates this to be the thing that makes fueltanks explode, (works the same) except for aforementioned empty fueltanks which behave as usual.
~~also this will make ANFO a feature in the future possibly~~

ideally one day i'd find a way to tweak fuels heat specs to make applying a welder insta heat it like as in a tank for consistency, but i'd need to run this through with people as an idea first probably.

## Why it's good
some consistency for fuel as a substance and its heating.

## Changelog
:cl:
 * rscadd: Fueltank explosions now extend to being causable by any hot item pressed up against them, and on tanks with any fuel in them. Also applies to water coolers and barrels. Empty tanks that aren't fueltank type are not affected by this.
 * rscadd: Welding tools can now be filled by any reagent dispenser with fuel in it.
 * rscadd: Lighters can now be filled by any reagent dispenser with fuel in it.
 * rscadd: Fuel now explodes if it reaches 288C in a closed container, or creates a small fire in an open one.
 * rscadd: All tanks can now have assembly rigs on them.
 * bugfix: Lighters no longer refuel from empty fueltanks.

### CODE REVIEW

**Comment by Theophrastus1** [comment]
Don't agree with fueltanks not blowing up while empty. It's been a tried and true reasoning that fueltanks would probably contain compressed fumes that would combust. P sure it doesn't even breach when its empty.

**Comment by SECBATON-GRIFFON** [comment]
> Don't agree with fueltanks not blowing up while empty. It's been a tried and true reasoning that fueltanks would probably contain compressed fumes that would combust. P sure it doesn't even breach when its empty.

added an exception to this solely for actual fueltanks itself

**Comment by Theophrastus1** [comment]
> > Don't agree with fueltanks not blowing up while empty. It's been a tried and true reasoning that fueltanks would probably contain compressed fumes that would combust. P sure it doesn't even breach when its empty.
> 
> i could add an exception to this solely for actual fueltanks itself, if you want

There have also been previous PRs in the past that have been closed involving that particular fix, plus I just don't wanna see something that makes tons of sense get removed because of absolute fringe cases of it occurring to people.

**Comment by pedr69** [comment]
if we're going for realism i think only empty tanks should explode violently
full ones should just spew flames everywhere

**Comment by Eneocho** [comment]
>if we're going for realism i think only empty tanks should explode violently
full ones should just spew flames everywhere

Realistic, yes, but lame and boring. Welderbombs are funny and tradition.
Something something Spess Welding Fuel is pyrophoric.

>but you can fuel the floor without fire happening

It's bluespace, I ain't gotta explain shit.

**Comment by SonixApache** [comment]
> if we're going for realism i think only empty tanks should explode violently full ones should just spew flames everywhere

i've always wanted full fueltanks to turn into makeshift rockets when pierced, rather than boring instant explosions

**Comment by Theophrastus1** [comment]
> if we're going for realism i think only empty tanks should explode violently full ones should just spew flames everywhere

i'm not saying go full realism and i'm sick of people just assuming that. This is just a quirk from whoever made weldertanks and i think it's a funny quirk and soulful and shouldn't be removed because someone accidentally caused a 1 tile breach (that will be patched instantly).

**Comment by SECBATON-GRIFFON** [comment]
> > if we're going for realism i think only empty tanks should explode violently full ones should just spew flames everywhere
> 
> i'm not saying go full realism and i'm sick of people just assuming that. This is just a quirk from whoever made weldertanks and i think it's a funny quirk and soulful and shouldn't be removed because someone accidentally caused a 1 tile breach (that will be patched instantly).

i already took out that change from fueltanks

**Pull request merged**
