### PR TITLE
Suicide_act() update

### LINKED ISSUE #29680: You don't get a special suicidemessage by suiciding with a flare.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
1628ee2cec2ee9302b3cbaa4fb55c4be96c3de0f

# Description
Title.
# Steps to Reproduce
Suicide with an active flare.
# What you Expected
Dunno. Swallowing the thing and burning?
# What Actually Happened
Lame breath holding suicide.

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][port][tested]
Closes #29680.
:cl:
 * rscadd: Suicides can now be done with any adjacent obj, no longer just held items.
 * rscadd: Various new suicide methods have been added, including: chem dispensers, processors, machinery, windows, computers, supermatter, flares, TTV bombs, reagent tanks, meat spikes, gibbers, RPDs
 * rscadd: Suicide acts have now been generalised down to object and item levels, depending on their qualities, removing various redundant ones in the process.
 * rscadd: Cable coil noose suicides have been ported from Hippie Station

### CODE REVIEW

**Comment by Eneocho** [comment]
Incredibly based. But do make sure that detailed or custom suicides don't fail because of this (like the BoH suicide eating your body or the paper sheet + pen suicide making you seppuku).
A few things: 
* Why remove the knife suicide? I liked it due to how unexpectedly gruesome it was.
* Can you add a suicide for flares (see #29680)?
* Would this enable some really convoluted and otherwise never happening again suicides (like touching the supermatter with a bike horn while on a tractor, while dressed as the captain but wearing the RD shoes, for example)?
* Please add a R-UST or SME related suicide that affects the output of the engine as a one time thing (SME pulses stronger as if stimmed with something, then goes back to normal output, R-UST Gyrotron pulses twice in a row for a few seconds then goes back to normal, etc.).

**Comment by SECBATON-GRIFFON** [comment]
> * Why remove the knife suicide? I liked it due to how unexpectedly gruesome it was.

redundant to supertypes one
> * Can you add a suicide for flares (see [You don't get a special suicidemessage by suiciding with a flare. #29680](https://github.com/vgstation-coders/vgstation13/issues/29680))?

absolutely
> * Would this enable some really convoluted and otherwise never happening again suicides (like touching the supermatter with a bike horn while on a tractor, while dressed as the captain but wearing the RD shoes, for example)?

of course
> * Please add a R-UST or SME related suicide that affects the output of the engine as a one time thing (SME pulses stronger as if stimmed with something, then goes back to normal output, R-UST Gyrotron pulses twice in a row for a few seconds then goes back to normal, etc.).

no

**Comment by Eneocho** [comment]
> redundant to supertypes one

Ok.
 
> absolutely

Based.

> of course

Impossibly based. On my way to come up with and code such ridiculous scenarios.

> no

At least make it so if you suicide next to the SM, you try to hug it or some shit then instead of calling a standard suicide (brute or burn), it calls SM ashing. Please.

**Comment by SECBATON-GRIFFON** [comment]
flare one added @eneocho

**Comment by Eneocho** [comment]
> 
> 
> flare one added @Eneocho

Based. Thanks.

**Comment by SECBATON-GRIFFON** [comment]
> At least make it so if you suicide next to the SM, you try to hug it or some shit then instead of calling a standard suicide (brute or burn), it calls SM ashing. Please.

okay, i did this one

**Comment by juanototo2** [comment]
Add the ability to manually edit the TTV suicide message via a right click effect of some description.

**Comment by Killette2** [comment]
Would it be possible to choose suicides? Say I don't want to beat myself with a crowbar. And when you suicide with nothing in hand it seems to pick from 1 of multiple, but what if you want a certain one?

**Comment by SECBATON-GRIFFON** [comment]
why isnt it compiling

**Comment by Eneocho** [comment]
The only thing the test mentions is: 
`UNIT TEST FAIL: /datum/unit_test/slipping 2.4s
	REASON 1: [20:37:35] Runtime in ,: bad arg name 'overlay_type'
	REASON 2: Slipping test failed at 1, step 1 ; expected 1, got 0`
And repeats the 1st runtime.

**Comment by SECBATON-GRIFFON** [comment]
yeah but it has nothing to do with this PR. and it often shows up in commits

**Comment by SECBATON-GRIFFON** [comment]
nevermind now it does

**Comment by SECBATON-GRIFFON** [comment]
> Add the ability to manually edit the TTV suicide message via a right click effect of some description.

done, also standardised it for all bomber related ones

**Comment by SECBATON-GRIFFON** [comment]
> Would it be possible to choose suicides? Say I don't want to beat myself with a crowbar. And when you suicide with nothing in hand it seems to pick from 1 of multiple, but what if you want a certain one?

remedied a bit by picking from something in front of you before other adjacency checks. also, active hand takes priority anwyays.

**Comment by Eneocho** [comment]
I forgot to ask before. Would this allow you to suicide while cuffed/buckled to a chair? See #29255.

**Comment by SECBATON-GRIFFON** [comment]
> I forgot to ask before. Would this allow you to suicide while cuffed/buckled to a chair? See #29255.

still no, seems like theyre against allowing it

**Comment by Kurfursten** [comment]
Did this ever stop being a WIP and ready for review?

**Comment by SECBATON-GRIFFON** [comment]
its not WIP anymore @Kurfursten

**Comment by Eneocho** [comment]
I was gonna request if you could add a suicide with an ass, but it's too late. 
I imagined some dumb shit like making the giga fart sound effect then gibbing you.

**Pull request merged**
