### PR TITLE
Combustion Cannon

### PR DESCRIPTION
**Pull request by Shadowmech88**
combustion_cannon_100
Adds the combustion cannon, a new beam weapon.
Its beam causes an explosion with a light damage radius of 5 tiles at the impact point. It deals roughly 25 brute damage to everyone caught in the explosion.
The combustion cannon regenerates its own power slowly, like the captain's laser does. It can only be fired on a full charge, about once every 40 seconds.
The combustion cannon has a w_class of 5, and cannot be stored in the inventory.

### CODE REVIEW

**Comment by ghost** [comment]
>cannot be dropped

For what purpose

**Comment by clusterfack** [comment]
>**combustion** cannon, a new **beam** weapon

wut

**Comment by Exxion** [comment]
This feels like a reference, but I have no idea to what

**Comment by Shadowmech88** [comment]
The name is a reference, though I didn't realize it until after I'd already chosen it. The appearance might be a reference to a different thing, but I'm not sure. I got the idea for the shape from an image I saw but I don't know anything else about it.

**Comment by Gunosaguki** [comment]
Wait why can't it be dropped once picked up?

**Comment by calzilla1** [comment]
Mega meme

**Comment by jknpj** [comment]
i think i get the reference

159bd88a91939415a8fe77561922a9d3

**Comment by clusterfack** [comment]
The weapon is named gravity something something in that movie though. Is it different in the original manga?

**Comment by clusterfack** [comment]
Also we need the 1 year meme rule. No adding memetic references into the game unless they still remain fresh a year after they become popular.

**Comment by Shadowmech88** [comment]
That's actually not it.

**Comment by Shadowmech88** [comment]
Also, I made it undroppable because I felt that the recharge time wouldn't be as much of a penalty if you could just stuff it in your backpack until it was ready to fire again.

**Comment by Exxion** [comment]
Could just give it a huge `w_class` then

**Comment by Shadowmech88** [comment]
* The combustion cannon can now be dropped. It cannot, however, be stored in the inventory.

**Comment by Shadowmech88** [comment]
Personally I would've rather increased its destructiveness to make the `cant_drop` worth it, but heavy explosions cause breaches and just making the light range larger would risk catching the shooter in it.

**Comment by Shadowmech88** [comment]
Is there anything else that needs to be done on this?

**Comment by unid15** [comment]
There are conflicts otherwise seems fine

Also I think you intended to add a cant_drop_msg for this but forgot

**Comment by Shadowmech88** [comment]
I originally did add a `cant_drop_msg`, but removed it because people wanted it to be droppable.
I left the var in, though, in case someone else wanted to add such a message to some other non-droppable item.

**Comment by Exxion** [comment]
By the way, this is surprisingly similar to something I was going to make over a year ago, but never got around to

**Comment by Shadowmech88** [comment]
Conflicts fixed.

**Pull request merged**
