### PR TITLE
Players now get feedback when shattering light tubes they are holding

### LINKED ISSUE #28418: light bulbs/tubes break when you click anywhere on the screen
#### Description of issue
bulb in hand
click screen
bulb explodes

also happens when you put them in disposal bins

#### Difference between expected and actual behavior
bulb not explode
vs
bulb explode

#### Steps to reproduce
take bulb / tube in hand
click screen

#### Specific information for locating
some sort of afterattack fuckup? not sure

#### Length of time in which bug has been known to occur
not long, maybe a few weeks

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #28418

:cl:
* bugfix: Players now get feedback when shattering light tubes they are holding. (sonixapache)

### CODE REVIEW

**Comment by SonixApache** [comment]
that's a good addition but my issue more specifically was 
when you can click anywhere on the screen with a light tube in hand while on harm intent, you break the tube
which is stupid

**Comment by DeityLink** [comment]
> 
> 
> that's a good addition but my issue more specifically was
> when you can click anywhere on the screen with a light tube in hand while on harm intent, you break the tube
> which is stupid

I thought it was hilarious, so you get a separate message depending on whether you smashed the bulb on an adjacent atom or crushed it in your hand.

**Comment by Eneocho** [comment]
You should get some amount of brute damage if you crushed the glass on your hand. Or a small bleeder.

**Comment by Kurfursten** [comment]
I think it makes more sense to shatter if you use it in hand

**Comment by DeityLink** [comment]
aight fair enough

**Pull request merged**
