### PR TITLE
I'm The Joker(tm) baby!

### PR DESCRIPTION
**Pull request by DrSnips**
[sprites]
Did you know we have references in some of the code for joker playing cards but no joker card sprites? Well now we do. ~~This doesn't add them to decks, but it would be easy to. I can add them upon request as it could mess with people's expectation on a 52 card deck. Discuss that below if that should be changed.~~ Added to the top of the deck.
Required for #32368
image

🥳Did you also know that this is my 100th PR? This is me going full joker mode. 🥳

### CODE REVIEW

**Comment by Intigracy** [comment]
add to decks coward

**Comment by DrSnips** [comment]
image
Here's the sprites themselves.

**Comment by Eneocho** [comment]
Add them to the decks but make it so the top two cards are the jokers, so people can play without em if they want.

**Comment by DrSnips** [comment]
Tested. They do come out on top.

**Comment by Eneocho** [comment]
speedmerge now

**Pull request merged**
