### PR TITLE
Adds AI newLife and Death sounds

### PR DESCRIPTION
**Pull request by MadmanMartian**
As suggested by Jubisloviu and likely countless previous others

:cl:
 * rscadd: The station AI no longer runs on Mac

### CODE REVIEW

**Comment by ShiftyRail** [comment]
I guess you can try to do the same variations the "I LIVE AGAIN" and the test dummy sounds have to avoid having the exact same round repeat over and over again over different rounds.

**Comment by MadmanMartian** [comment]
It's set to FALSE precisely to have it be the same. If people want variance, say so.

**Comment by SonixApache** [comment]
So these are SUPPOSED to be global sounds, right?

**Comment by MadmanMartian** [comment]
global?!

**Comment by SonixApache** [comment]
You can hear the XP startup sound in the lobby and everywhere in the map at roundstart.
Not sure about the shutdown sound.

Maybe because it plays the sound in the ~~cuck cube~~"dressing room" under the lobby splash?

**Pull request merged**
