### PR TITLE
/vg/UI

### PR DESCRIPTION
**Pull request by PJB3005**
Port of tgui.

INCREDIBLY WIP ONLY THE TANK UI WORKS.

NOTE: based on Sood's 510 work, so that has to be merged first.

@neersighted

### CODE REVIEW

**Comment by CptWad** [comment]
theres going to be a whole lot of angry people who hate change when this comes out
and the bugs
oh god the bugs
but I will support this
godspeed

**Comment by gbasood** [comment]
if this relies on that browserOutput bug you told me about in my 510 branch being fixed you'll want to rebase

**Comment by neersighted** [comment]
Coolio

**Comment by FudgePucker** [comment]
Pics?

**Comment by SysadminJeroen** [comment]
I believe that there will be many bugs, but I think that we have already decided to have bleeding-edge features by calling our main branch `Bleeding-Edge`.
Post pics please, I can't wait to see it.

**Comment by Probe1** [comment]
Ok i'll ask.

Why?  What are the benefits, other than incorporating a 4th or possibly 5th UI format.  NanoUI, HTML, TGUI, that really old one.. some others probably

**Comment by PJB3005** [comment]
@Probe1 this is a replacement of NanoUI, it looks better, performs better, is more powerful...

**Comment by clusterfack** [comment]
Well nano is already dead to us, it will never be used to make a new UI and we will try to replace it where we can.

HTML was okay but not many people had the knowledge/will to code for it and the base code for it was somewhat obtuse.

I cant speak to the advantages of the new system only PJB can do that well but both old systems had many disadvantages.

**Comment by PJB3005** [comment]
https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/04/2016-04-03_17-45-03.webm

**Comment by Probe1** [comment]
I saw the webm and thought it looked nice but I didn't see what benefits other than a nice animation it brought.

My chief concern is it will end up like all the other new UIs:  Half implemented across the game and undocumented so only a few coders can tackle it, leaving the job entirely up to them to incorporate it.  Which is a burden that I don't expect only PJB to do.

**Comment by 9600bauds** [comment]
Any way to get rid of the white flash before the UI displays? Does it get longer with features/latency?

**Comment by PJB3005** [comment]
@Probe1 the backend tgui uses is way better than NanoUI, it allows for much more powerful, easy to develop and good looking interfaces than NanoUI ever did.

Since this is a replacement for NanoUI you can bet your fucking ass I'm implementing this properly.

**Comment by Probe1** [comment]
It should be your priority to take that gusto and fix all these piling up chat issues first, then add more things that will need a ton of work.

**Comment by AutismSpider** [comment]
Will this make setting my tank pressure to 16 kpa even more unbearably slow ? Can't wait to be unable to open the UI for 5 seconds because NanoUI is a massive lagshite.

**Comment by optimumtact** [comment]
Oh I'm sorry this will probably be too laggy for your sub 40 player server

**Comment by 9600bauds** [comment]
I'm not really feeling the classic oranges banter in that one

**Comment by PKPenguin321** [comment]
pointless savagery oranges

**Comment by optimumtact** [comment]
@9600bauds that's probably because I meant it

**Comment by PJB3005** [comment]
Oranges being sarcastic about sarcasm is getting old.

**Comment by optimumtact** [comment]
You taking shots at us because of a massive inferiority complex is getting even older

**Comment by ihadtoregisterforthis** [comment]
TGtters get out of my repo
:fire::frog::fire:

**Comment by PJB3005** [comment]
Due to tgui's clientside performance being too poor, I've put this on a hold.

We've got 2 options: 
- Try to get IE to be able to load web 2.0 things quickly.
- Use tgui alonside other UI solutions, make older UI solutions used to handle huge UIs.

**Comment by Probe1** [comment]
Here's hoping they sort it out.

**Comment by PJB3005** [comment]
Doubt it.

Let's port paraUI instead.

**Comment by ComicIronic** [comment]
What's the difference between all these UIs

**Comment by PJB3005** [comment]
Paradise ported TG's nano before it became tgui and it wasn't shit back then.

tgui is overengineered and runs like absolute ass even in modern browsers.

**Comment by gbasood** [comment]
note for future: as of this time paradise's version of nano is the thing we'd want to port most
tgui is really hard on the client apparently acc to @PJB3005

**Comment by ghost** [comment]
RIP

**Pull request closed without merging**
