### PR TITLE
Fixes a redefine

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
It was redefined something black market related

### CODE REVIEW

**Comment by DamianX** [comment]
both sets of macros are intensely retarded because of the lack of prefixes which caused the issue in the first place

**Review by jknpj — CHANGES_REQUESTED** [review]
Add the BLACKMARKET_ prefix to all of them.

**Comment by jknpj** [comment]
Jesus christ, we might need to add BLACKSMITHING_ prefix to the others too

**Comment by boy2mantwicethefam** [comment]
sneaky coder don't push your changes as my responsibility wtf

**Review by jknpj — APPROVED** [review]

**Pull request merged**
