### PR TITLE
Pale being nerf

### PR DESCRIPTION
**Pull request by DeityLink**
The armor rng removal having made many high value armors reliably stronger, armored pale beings are being a bit more of an issue right now. I'll let whoever plans to do the full pass on tweaking all armor values tweak cult's robes and armor (since I believe all armors should be tweaked together following the same rules) but in the meantime I'll implement some slight nerfs I had in mind to help people deal with pale beings:

smoke

:cl:
* tweak: Pale beings in crit now have an overlay applied to them, indicating to everyone that they're in crit. As a reminder, even though they don't fall unconscious, they still take periodic oxygen damage.
* tweak: Pale beings in crit now take 1 brute damage per second. Unlike oxygen damage, they cannot just heal it through fervor by themselves.
* tweak: Pale beings now die at -50 hp instead of -100 hp. This means that a fully charged egun can take an armored pale body down if every shot connects, without having to rely on crit damage over time to finish the job.

### CODE REVIEW

**Comment by Kharkov72** [comment]
pálido siendo blanco...

**Comment by juanototo2** [comment]
It's pálido ser blanco, you fucking Amerimutt mongoloid

**Comment by boy2mantwicethefam** [comment]
Don't @ me about it but cultists should be able to be repaired to some extent by artificers

**Comment by ShiftyRail** [comment]
Not enough

**Comment by SonixApache** [comment]
travis

**Comment by DeityLink** [comment]
@ShiftyRail It'll never be enough for some.

**Comment by Blithering** [comment]
Artificers being able to repair pale beings and cult structures would be neat, support classes!

**Comment by FudgePucker** [comment]
There should be silver bullet magazines printed at an ammo lathe that deal boosted damage to cultists at stage three and vampires, and can be blessed by a chaplain to add 3u holy water on hit. A full fucking magdump of a egun to take out a single one? Holy shit, that's the same as a spider queen, and the spider queen doesnt have a ranged AoE stun or yakety sax ability.

**Comment by Blithering** [comment]
I think this might be too much of a step in the other direction, it's still just a hulked human at the end of the day, nothing a chemist cant replicate. If they just had a toned down version of the aura at all times, so people knew when there was a pale being coming at them so not to waste time with stun shots then there would be much less of a problem.

**Comment by SonixApache** [comment]
global 'HOLY' var for literally all objects and turfs when

a visual indicator around pale nerds or a special sound effect when you try to stun them might help alleviate the annoyances with them

**Pull request merged**
