### PR TITLE
Two small fixes

### PR DESCRIPTION
**Pull request by unid15**
Examining a body without a head no longer tells you about its missing
brain or brain damage
Cigarettes can be lit with candles

### CODE REVIEW

**Comment by Exxion** [comment]
Fixes #4158

**Comment by PJB3005** [comment]
Does this also get rid of the 'he has a stupid expression on his face' message, that can also appear on corpses without head?

**Comment by ComicIronic** [comment]
That is the brain damage message, so yes.

**Comment by PJB3005** [comment]
ooooooooh

**Pull request merged**
