### PR TITLE
Updates Several Mining Sprites

### PR DESCRIPTION
**Pull request by drawsstuff**
Updates Several mining tools, ore sprites, and flood lights

BEFORE
before drill
before ore

AFTER
after drill
after ore

On top of these, also updates floodlights with included directionals
Before Flood

Sprites provided by the Russian SS13 Community, notably Tau Ceti Station, and WalterJe

[<sprites>]

:cl:
 * rscadd: Updates several mining sprites

### CODE REVIEW

**Comment by Exxion** [comment]
I like the purple and green crystals and the floodlights, but prefer the current sprites for the rest

**Comment by Spyroshark** [comment]
I like the floodlights, especially since we didn't have directionals for them. The ores sprite are..... fine, i have mixed opinions on them but I would be fine with them being added. The new jackhammer sprite is just weird and clashing. This would probably be better as a couple different PRs.

**Comment by DrSnips** [comment]
My belief is that good sprites encourages more good sprites so I really appreciate your work.

I like all of them quality wise but I have some issues with a few of their executions. I do really like all the new metals ores, specially since iron is now actually natural iron color.
Bananium feels just a little too close to what I would perceive at first is gold.
Plasma feels like it should be "wavey" as an ore given it's product rather than rods/spikes.
Uranium is the only one I liked the current sprite more.

God bless with the flood light update. The old one looks like dogshit.

**Comment by Kromkar** [comment]
Good additions and changes

**Comment by boy2mantwicethefam** [comment]
Soul -> soulless

**Comment by SonixApache** [comment]
shading inconsistent with rest of codebase
:-1:

**Comment by calzilla1** [comment]
Don't know why every server needs to port Eris sprites like they're god's gift to sprite work, but I like the old, darker sprites. Plus the old ore has a lot more contrast between the actual ore and the residue rock.

**Comment by yclatious** [comment]
There's a halfway point between stuff out there and what we got, and this ain't it chief. Its clashing as fuck, and for as "good" as the drills may look, like fuck I wanna look at them and have it be that aberrant compared to the entirety of the roid and everything else. Also the obligatory "fuck blue retardism shit" comment I have to make as well because for some reason you love the most boring hue in the spectrum.

Floodlights are aight, crystal is fine, fuck the rest.

**Comment by beesil** [comment]
Floodlights and crystals look great. The others (especially the drills) are jarringly different artstyle. I think tweaking the colors of the drills, diamonds, plasma, and uranium would go a long way to making them stand out less among our codebase.

**Comment by GreatBigFailure** [comment]
I think they're an improvement over-all but I do have issue with some of the ore shapes. The old ones communicated which they were both with colour and shape, now it's mostly colour. Not a big deal once people get used to it though. Drill is a massive improvement. I'd like to see phazon get an update to match though since it's left out.

**Comment by APCUnlocked** [comment]
this ain't it chief

**Pull request closed without merging**
