### PR TITLE
Welding speed tweaks

### PR DESCRIPTION
**Pull request by MadmanMartian**
Requested by Coxswain#4638 in discord.

:cl:
 * tweak: The gatling welder now welds twice as fast as the regular welding tool.
 * tweak: The experimental welding tool now welds 1.25 times faster than a standard welding tool

### CODE REVIEW

**Comment by Kharkov72** [comment]
finally a reason to use it

**Comment by SonixApache** [comment]
You tested this, right? It's not gonna turn out to weld at half speed, right?

**Comment by boy2mantwicethefam** [comment]
fuck, I'm gonna make a proc called usetool that will take into account the tool speed instead of having do_delays fucking everywhere and their duration multiplied by the tool speed

**Comment by Intigracy** [comment]
```
	var/weld_speed = 1 //How much faster this welder is at welding. Higher number = faster
```
```
	return isOn() && do_after(user, thing, time/weld_speed) && isOn() //Checks if it's on, then does the do_after, then checks if it's still on after.
```
:joy: It's literally in the comment on the var that bigger numbers are faster

**Comment by MadmanMartian** [comment]
welp.

**Comment by ghost** [comment]
Our most brilliant mind

**Comment by MadmanMartian** [comment]
been dealing with coeffs all day, must've slipped my mind

**Comment by Probe1** [comment]
It warms my heart and disturbs me that joke items I added ages ago are getting a purpose.

**Pull request merged**
