### PR TITLE
Adds the "Impostor" character from the 2018 hit video game "Among Us"

### PR DESCRIPTION
**Pull request by PavelCIA**
low effort
amogus

:cl:
 * rscadd: Adds the "Impostor" character from the 2018 hit video game "Among Us"

### CODE REVIEW

**Comment by smalIboss** [comment]
no man

**Comment by PavelCIA** [comment]
when the antag is valid

**Comment by yclatious** [comment]
Amogus

**Comment by Blithering** [comment]
3dho1p

**Comment by ghost** [comment]
amogus

**Comment by ghost** [comment]
we did it reddit

**Comment by Eneocho** [comment]
> 
> 
> we did it reddit

have a gold

**Comment by ShiftyRail** [comment]
April is one month and 10 days away

**Comment by juanototo2** [comment]
Find a better normalcattle meme to push this time, retard.

**Comment by Chucklemonger** [comment]
when the tator is sus

**Comment by PrimeDSS13** [comment]
collabs hire this man

**Comment by Gazathor** [comment]
wtf this isnt a barry PR

**Comment by Kurfursten** [comment]
Well it has the votes and it's bus only, so I guess beg Veers to spawn this in

**Pull request merged**
