### PR TITLE
New research shuttle + maint

### PR DESCRIPTION
**Pull request by frangi**
Mostly a test - brainstorm on how to make this area better.

I always felt that the reserach shuttle area was too detached from actual science, and it encouraged people to break in and go annoy/loot the outpost.

### CODE REVIEW

**Comment by ComicIronic** [comment]
If you want to prevent breakins, the walls should be rwalls, or it's just easier to get to than when it was in space.

**Comment by frangi** [comment]
now with r-walls

**Comment by IratePirate** [comment]
I don't see the point in this. All it does is make it harder for antags to get to the research station and needlessly penalises them if they want to go out into space.

**Comment by ComicIronic** [comment]
It stops scientists from being so vulnerable to carp attacks.
Which is a really good thing, since the shuttle is one of the most exposed and extreme parts of the station, so any attack will be deadly and have a good chance of ending the round for the player, since their body might never be seen.

**Comment by d3athrow** [comment]
rWalls makes aliens who get to the statio nfrom research shuttle unable to really go anywhere.

**Comment by frangi** [comment]
doesn't acid melt r-walls?

**Comment by Konater** [comment]
No, they could melt the doors though

**Comment by SarahJohnson489** [comment]
That's still 600 plasma and like 8 minutes

**Comment by frangi** [comment]
what about this?

**Comment by Duny-** [comment]
I like it. I'd have done it more like that though because the way it looks annoys me:
ss 2015-02-10 at 03 56 45
Forgot to add the metal thingies in spess for which I forgot the name, whatevs.
I prefer it like that than the shuttle floating in the middle of space far from science currently.

**Comment by clusterfack** [comment]
Windows to look at walls?

Also I recently fixed a bug that was causing the mining/research shuttles to not check for access. Greyshits shouldn't be able to loot the outpost anymore.

**Comment by frangi** [comment]
Duny: shifting it 1 up isn't the solution: when the escape shuttle lands it'll be adjacent to the new maint's windows. The idea isn't bad tho, I'd have to look for a way to shift it one down without making maint look like shit.

clusterfack: really? well, my reason for doing this was mainly to avoid greyshirts having a merrygoround inside the outpost, and that fixes it. The only reason left for me now is to have it actually be inside the department then something far and not even pertaining RnD, and the carp attacks as mentioned earlier.

**Comment by frangi** [comment]
after duny's suggestion

**Comment by SarahJohnson489** [comment]
The shuttle consoles require access so your outpost is safe from the big grey boogeyman

**Comment by Duny-** [comment]
>also took the liberty to add magboots to outpost since it was requested while I was at it

Replace excavation suits with /obj/machinery/suit_storage_unit/excavation instead, they come with magboots.

**Pull request closed without merging**
