### PR TITLE
Makes LAssailant a weakref

### LINKED ISSUE #14592: LAssailant is garbage
It causes mobs to hard del because it keeps a ref to a mob forever unless the mob that was attacked is destroyed. That isn't conjecture, I checked.

We don't really use it, as far as I know, for anything but stat logs, and before that I don't know why it ever existed.
It isn't useful.
I'll probably remove it from the stats site at some point anyways.

We need to remove the LAssailant var. Why am I making this issue? Because I don't want to deal with it tonight and I don't want to forget how garbage it is. *And maybe someone else will do it for me*

### LINKED ISSUE #27571: LAssailant causes hard dels
It should be a weakref or something

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[performance]

## What this does
Closes #27571.
Closes #14592.
changes var name to lastassailant so it's clearer on what it is

### CODE REVIEW

**Comment by Eneocho** [comment]
`>43 modified files`
prepare for foreskinned consequences

**Comment by SECBATON-GRIFFON** [comment]
> `>43 modified files` prepare for foreskinned consequences

LAssailant, like mentioned, is only really used on slime feeding and the minimise casualties jectie, so more like two things affected

**Comment by SonixApache** [comment]
put a bookmark on this one for when a dozen extremely weird issues suddenly pop up

**Comment by SECBATON-GRIFFON** [comment]
> put a bookmark on this one for when a dozen extremely weird issues suddenly pop up

tested this PR pretty well, kills still show up in the player's mind, runescape icons work ok

**Pull request merged**
