### PR TITLE
Tool Sound/Speed

### PR DESCRIPTION
**Pull request by jknpj**
Time to remove all hardcoded playsound calls/unify speed modifiers used by tools. Yes, this is going to be a royal pain in the ass.

### CODE REVIEW

**Comment by Exxion** [comment]
This is already a large PR, so you might not want to, but feel free to eradicate the extremely shitty and completely unused (I think) tool speed system I added years ago

**Comment by jknpj** [comment]
@Exxion if it exists i might as well use it, unless you're opposed to the idea?

**Comment by Exxion** [comment]
Use it? God no. Just remove it in favor of what you're doing here, or leave it around and I'll remove it later unless I forget

**Comment by Kurfursten** [comment]
Just checking in, where does this stand?

**Comment by jknpj** [comment]
In a weird place, since i have no clue what to do with cable coils and circuits that have different sounds per-machine basis.

**Comment by Kurfursten** [comment]
Unify, with a new cabley sound if necessary

**Comment by Kurfursten** [comment]
Fix conflicts and I will merge this, even without the other tools

**Comment by jknpj** [comment]
alright

**Comment by jknpj** [comment]
only took me two weeks

**Pull request merged**
