### PR TITLE
Fixes mechanic doors being snowflake fucking hardmapping, renames mechanic access level

### LINKED ISSUE #4375: No mechanics airlock assembly

### PR DESCRIPTION
**Pull request by ghost**
fixes #4375

### CODE REVIEW

**Comment by PJB3005** [comment]
Wait.

Didnt they have a different sprite?

**Comment by Intigracy** [comment]
icon = 'icons/obj/doors/Doorsci.dmi'

Yes, they had the science sprite.
As the engineering subtype.

**Comment by PJB3005** [comment]
I'm 100% sure they're a different sprite than the regular science airlock though. Not sure how that works but this might have broken it.

**Comment by Intigracy** [comment]
Oh, you're right.

There's doorsci.dmi for mechanics and doorresearch.dmi for science.

@9600bauds fix eet

**Comment by Intigracy** [comment]
There's doorsci.dmi which is the mechanics airlock sprite, which is this subtype (airlock/science), and then there's doorresearch.dmi which is on airlock/research which is all over science the department.

**Comment by PJB3005** [comment]
Gotcha.

**Pull request merged**
