### PR TITLE
Adds the plastic crate to cargo

### PR DESCRIPTION
**Pull request by bathosbathtime**
[powercreep][updatewiki]
This change adds the plastic supply crate to cargo.  It is a 30 credit cost for a stack of 50 plastic sheets.  No longer will you need to harvest holographic curtains or department flaps to gain plastic sheets.  The botany option is also still there but fuk plants.  The cost and amount is subject to change per review needs.
Compiled and tested locally

:cl:
 * rscadd: Plastic supply crates can be ordered at cargo

### CODE REVIEW

**Comment by aceedex** [comment]
time to make mechanics use plastic again

**Comment by Kurfursten** [comment]
Why not just remove plastic from the mechanics machines instead? That seems to more efficiently address your objectives.

**Comment by SirSkeleto** [comment]
> Why not just remove plastic from the mechanics machines instead? That seems to more efficiently address your objectives.

this way when the aforementioned workarounds are removed plastic can be used for things other than the mechanics (e.g. curtains for a bar, traffic cone hats, etc.)

**Comment by ghost** [comment]
I think this shows how underwhelming plant plastic creation is, to the point where it's too annoying to bother with.

You get at most 30 plastic sheets from a full large beaker reaction. This needs precise dosing of 60 plasticide and 30 poly acid, which involves grinding, waiting and then many more clicks, not counting the plant and harvesting. You have to repeat this process for every 30 sheets. Compare this to getting metal/glass/plasteel, which is just dumping a ton of ore and smelting it automatically.

I think giving plastic creation the grass treatment would solve this, using plastic shrooms in hand would form them into plastic based on potency. It could be made less efficient per shroom/potency than chemical reaction but it would be much less annoying and accessible.

**Comment by Kurfursten** [comment]
Alternate idea: instead of requiring chemistry (relatively annoying) or use in hand (relatively dull and muh immersions), what about a middle option?

* Grind up plastelium to plasticide as before
* Put in smartfridge to chill
* Plastic pops out after it reaches target temperature

Requires no precision and still a little more technical than beating mushrooms into sheets. Plus chemheating!

**Comment by ghost** [comment]
The problem is in making large quantities needing a ton of clicking and annoying processing. Realistically you will never need more than a full stack of plastic for both mechanics and science combined for the entire shift. It only becomes an issue for regular crew and building fancy things.

I would argue the grinding part is the largest demotivator.

**Comment by bathosbathtime** [comment]
These are all nice ideas for cleaning up plastic production but I'm more focused on ordering plastic from cargo so we can more regularly get those sick plastic brick floors.  Depending on service to exist (or not exist so you can break in) and be cooperative sucks, cargo is at least used to taking orders.  Not in the command sense but in the mercantile sense.

**Comment by jknpj** [comment]
this is dirty cheap, but uuuh, i'm not going to pick that fight today

**Comment by Kurfursten** [comment]
I didn't like it either because I don't think it addresses either

1. Mechanics are too reliant on other jobs doing stuff before they can start
or
2. Botany plastic productions should become practical enough that they can do it (not begging chemistry for polyacid just to help someone else)

**Comment by bathosbathtime** [comment]
http://ss13.moe/wiki/index.php/Supply_Crates has been updated

**Pull request merged**
