### PR TITLE
tomato soup premium item for coffee machines

### PR DESCRIPTION
**Pull request by SonixApache**
[content] which isn't a tag for some reason
added another sprite, going to do r0b0's thing and make it an overlay instead in ~~the next~~ AN UPCOMING PR
image

:cl:
 * rscadd: Added tomato soup as premium item for coffee machines
 * tweak: tomato soup, the food, now contains tomato soup, rather than tomato juice.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I'm buying clothes

**Comment by SonixApache** [comment]
100% tested and good to go and all that jazz

**Comment by Irradiation** [comment]
Why not chicken noodle soup while you're at it? IT'S BETTER THAN TOMATO SOUP.

**Comment by SonixApache** [comment]
because dutch vending machines have TOMATO SOUP

**Comment by DrSnips** [comment]
Personally I don't see the point to having a separate tomato soup reagent. The effect doesn't set it apart from other body warming regents to warrant its existence.

**Comment by SonixApache** [comment]
nutriment, heat, it's not ramen, there's already a tomato soup food that doesn't do anything
kind of like the 50 different types of alcohol, coffee and tea reagents that don't do anything special

My justification is adding a type of drinkable food to the coffee machine, alongside more coin-op things.

**Comment by Goldsteel** [comment]
Sidenote: I think warm soup should give you a low chance to recover from disease that hasn't progressed past 2nd tier if wearing a space blanket or lying in a bed.

**Pull request merged**
