### PR TITLE
Grue shadow shunt

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
This gives juvenile and adult grues the ability to shadow shunt, which teleports them from a dark tile (won't work in dim or bright tiles), to another random dark tile up to 25 tiles away.  The random selection is biased towards tiles further away from the grue's current location, and with decent levels of oxygen (to avoid teleporting out onto the solar array). It has a cooldown of 45 seconds, and decreases by 2 seconds with every sentient being eaten, down to a minimum of 8 seconds.

## Why it's good
I think this could be a nice buff to grues without making them directly more powerful or tanky in combat, or making them more light resistant. It lets them flee from dangerous situations and be more mobile, increasing their survivability so they can't be as easily cornered and hunted down. It could make them into a more elusive yet ever-present threat lurking in maintenance.

There's some related discussion at #33860.

Any feedback or ideas would be appreciated.

## Changelog
:cl:
 * rscadd: Grues can Shadow Shunt, allowing them to warp their way through the darkness.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
@SECBATON-GRIFFON Right now this picks a turf based on 2D distance around the grue, but if it was a multi-z map it might be nice to have them able to shunt to turfs in other z-levels. Currently this uses `orange()`, but is there a good way to find turfs around the grue in 3D on multi-z maps?

**Comment by Exxion** [comment]
For the record, `orange()` is a square, not a circle

**Comment by Hinaichigo** [comment]
I thought it depends on the args:
`orange(5)` being a 5-radius circle,
and `orange("5x5")` being a 5x5 box.

Or is that because it measures distance by the max of the x,y,z coordinates so it ends up as a square?

**Comment by Exxion** [comment]
It's everything within a range of 5. In BYOND, diagonal moves are the same distance as horizontal/vertical, so this forms a square.

**Comment by Hinaichigo** [comment]
Oh I see.

**Comment by Eneocho** [comment]
> It's everything within a range of 5. In BYOND, diagonal moves are the same distance as horizontal/vertical, so this forms a square.

T-Thanks byond.

**Comment by PrimeDSS13** [comment]
Truthfully, I think making antags able to teleport has never worked out.
When I think of all our most annoying antags and what makes them annoying, it always seems to come back to teleporting.

Wizard: Blink makes them unkillable and less fun
Vampire: Everyone kills them when they can because they can teleport away
Pulse Demon: Is really annoying to kill because it can teleport to other power sources
Cultists: Tied to chairs and beheaded as quickly as possible since they can be teleported out

Especially for a side antag like this, it still just seems like a tacked on teleport buff that so many antags get to increase survivability in a not-so-fun way. I'm not sure I want the duplicating murderbone gibbing maint antag to also be extremely annoying to fight.

**Comment by Hinaichigo** [comment]
Carrying a light could help prevent them from shunting away. If the grue is fleeing through dim or dark areas, their movement speed will likely be faster than a humans, but they will possibly have to pause to open doors, allowing the pursuer to catch up and keep them in bright-or-dimness, somewhat slowing them and also blocking them from shunting. There're also flareguns and stuff which could help with this as well. Maybe after seeing how this works out in practice, we can then consider corresponding movement speed scaling tweaks to make the crew-hunting-down-the-grue still fun and not ultra hard. Also to that end we could tweak the cooldown for the shunt itself.

It's possible the shunt could also use a different variable than a simple timer cooldown, something like the accumulative light exposure modifier that's currently used to make light and more damaging with increased recent exposure. So you'd have to be in the dark for a little bit to be able to shunt away, or something like that.

Or, this ability could be given a 0.5s casting time or something like that that gets interrupted by light exposure.

**Pull request merged**
