### PR TITLE
Makes Mushrooms feel no pain

### PR DESCRIPTION
**Pull request by MercuriusGH**
[balance]

## What this does
Makes mushrooms feel no pain
## Why it's good
it just makes sense
## How it was tested
cut my arm off on the test server felt fine afterwards

## Changelog

:cl:
 * tweak: Gives mushrooms the no_pain flag

### CODE REVIEW

**Comment by Dacendeth** [comment]
Doesn't make sense to me, pain is a response to something getting an injury that makes us check it so we can avoid dying to bloodloss, and since mushrooms can bleed out it seems like something they would have naturally have. Now having said that though I think it's dumb they have blood but as long as they have that pain also makes sense.

**Comment by SECBATON-GRIFFON** [comment]
downboating unless i can get proof that tasers actually work on them after this
still seems dumb in general thoughever

**Comment by angryturnip** [comment]
> it just makes sense

why?

**Comment by SonixApache** [comment]
shitposter PR

**Comment by githubuser4141** [comment]
> > it just makes sense
> 
> why?

because they're mushrooms, when you eat a mushroom it doesn't screem and writhe about?
Its a bio engineered race not designed by evolution, what that means is that basic "drives" and instincts might be missing, like a pain response, at least I think that's true? Could easily be changed in the lore doc anyway. Bio-engineered, missing some evolutionary traits, aka "badly designed".

**Comment by angryturnip** [comment]
Ignoring the fact that the mushrooms we eat are no longer alive at all, I would imagine a sentient fungus race would still have some sort of pain receptors despite our non-sentient earth fungus having none

**Comment by githubuser4141** [comment]
> Ignoring the fact that the mushrooms we eat are no longer alive at all, I would imagine a sentient fungus race would still have some sort of pain receptors despite our non-sentient earth fungus having none

If they are created from scratch in a lab they have exactly what they were given. If the designer who is not applying evolutionary pressure did not give them pain receptors they will not have them. It's like writing bad code that where the writer 'forgets' all the intercepts and interactions and stuff because it didn't arise from natural selection

The mushrooms we eat don't have any noticeable reaction to coming out of the ground and being killed. They might have some internal reaction but at the very least the mushroom people should have a muted reaction so no screaming or motion

**Comment by anonymoose-contributor** [comment]
This is objectively awful.

**Comment by MercuriusGH** [comment]
> Ignoring the fact that the mushrooms we eat are no longer alive at all, I would imagine a sentient fungus race would still have some sort of pain receptors despite our non-sentient earth fungus having none

Diona and mushrooms both have the IS_PLANT flag and Dionae don't feel pain, it makes sense to me for shrooms to not feel pain either

**Comment by angryturnip** [comment]
> Diona and mushrooms both have the IS_PLANT flag and Dionae don't feel pain, it makes sense to me for shrooms to not feel pain either

Arguably a fungus species shouldn't have the IS_PLANT flag, but with that information I'm more in favor of it. I wasn't aware Diona had it already.

**Comment by MercuriusGH** [comment]
> downboating unless i can get proof that tasers actually work on them after this still seems dumb in general thoughever

[dreamseeker_Z3v1IPlI41.webm](https://github.com/user-attachments/assets/25c93cdd-6926-4d81-96ed-37a12ffa46b6)

**Comment by west3436** [comment]
\>Why It's Good
\>It just makes sense.

"it came to me in a dream"

**Pull request closed without merging**
