### PR TITLE
Assistant Alt Job Uniforms

### PR DESCRIPTION
**Pull request by GreatBigFailure**
113083919-ff76c480-91d4-11eb-82ad-36ea7f703fcb

[Sprites] (all the work) by Blithering. I just copy pasted some things.

Updates the current assistant alt job jumpsuits from a single colour to a more fashionable and detailed grey combo.

From left to right: Security Cadet, Medical Intern, Technical Assistant, Research Assistant.

-->
:cl:
 * tweak: Assistant alt title jumpsuits are now more fashionable and grey.

### CODE REVIEW

**Comment by ghost** [comment]
sorry, i can barely tell these apart, probably went too far in that direction

**Comment by Dacendeth** [comment]
I assume there's no non human sprites for these?

**Comment by GreatBigFailure** [comment]
>sorry, i can barely tell these apart, probably went too far in that direction

I think it's an issue with poor lighting where I took the screenshot, but I was unfortunately in a hurry. I can get better lit screenshots when I'm able.

> I assume there's no non human sprites for these?

The vox and plasmaman ones just used the same coloured sprite so I assumed they fit them fine. Yes they work for non-humans.

**Comment by BomberBro** [comment]
What do the side views look like?

**Comment by juanototo2** [comment]
looks to me like it needs a little thickening. It's pretty hard to identify, and with any armor or hazard vests on, you wouldn't be able to know if they're a alt assistant without shift clicking.

**Comment by Dacendeth** [comment]
image
yeah no the vox ones look weird as expected.

**Comment by SootyBear42** [comment]
Good idea but needs to be tweaked a bit first

**Comment by Blithering** [comment]
I'll see what I can do about making the departmental colours stand out a bit more, stay tuned.

**Comment by SootyBear42** [comment]
> I'll see what I can do about making the departmental colours stand out a bit more, stay tuned.

Looking forward to it mate

**Comment by TGFH** [comment]
Yeah I think they're a bit too bland at the moment. The engineering one is especially difficult to see in that screenshot.

**Comment by Blithering** [comment]
assist
Did a few different designs, trying to make the department assigned more prominent. Which ones do people like?

**Comment by beesil** [comment]
The science and engineering suits look great, medical reads as closer to white than grey for me. Altogether :+1:

**Comment by Eneocho** [comment]
I would give the med one some green/cyan but overall they look great. The sec one looks a bit overboard though, you can barely recognize it being an assistant jumpsuit.

**Comment by BomberBro** [comment]
Science looks a bit like the janitor outfit

**Comment by SootyBear42** [comment]
> assist
> Did a few different designs, trying to make the department assigned more prominent. Which ones do people like?

All of them look great, though the medical jumpsuit could look more grey

**Comment by Blithering** [comment]
I'll try and get a balance between the engineering and science designs then, seeing as they seem to be the popular ones.

**Comment by SootyBear42** [comment]
> I'll try and get a balance between the engineering and science designs then, seeing as they seem to be the popular ones.

Alright, hopefully this gets merged

**Comment by Kammerjunk** [comment]
sci one looks like janitor but idc tbh

**Comment by Blithering** [comment]
assist
New attempt, added some more white to the science one to differentiate from janny suits, redid the medical and sec ones to better match the theme.

**Comment by SootyBear42** [comment]
> assist
> New attempt, added some more white to the science one to differentiate from janny suits, redid the medical and sec ones to better match the theme.

Definite improvement

**Comment by Kurfursten** [comment]
Waiting for commit

**Comment by GreatBigFailure** [comment]
Alright new versions finalized and added.

**Comment by Kurfursten** [comment]
Change icon in OP image

**Pull request merged**
