### PR TITLE
A Very Diona Roast

### PR DESCRIPTION
**Pull request by Optimism333**
## Are nymphs food or friends? ##
dionaroast

Hot on the heels of my previous food pr comes this one. Now that nymph meat is a usable ingredient in the game, this pr turns the unused diona roast sprite into an actual recipe that can be made in the microwave. I tested the pr in-game, and it seems to work fine.

**The recipe is as follows:**
* One piece of nymph meat (can be harvested from a meat spiked nymph or obtained by putting a nymph in the gibber)
* One normal apple
* One unit of salt
* One unit of pepper
* One unit of corn oil

Then turn on the microwave to get delicious! (With a hint of cruelty)

:cl:
 * Adds a new recipe: Diona Roast (Made with nymph meat)

### CODE REVIEW

**Comment by Optimism333** [comment]
If this passes, naturally I will update the wiki.

**Comment by Eneocho** [comment]
On my way to "accidentally" make some diona roasts to give to the local dionae as non antag.

**Comment by Eneocho** [comment]
I tried meatspiking a diona on a round today but it wouldn't budge. I had to gibber it.

**Comment by Optimism333** [comment]
> I tried meatspiking a diona on a round today but it wouldn't budge. I had to gibber it.

That's odd. I just tested it, and aggressive grabbing the nymph then clicking on a meat spike worked fine. I couldn't reproduce the problem. 

If it persists, consider opening an issue and I'll check it out more thoroughly.

**Pull request merged**
