### PR TITLE
Roidstation Hotfixes: SCP Edition Two: Gonfligs Boogaloo

### LINKED ISSUE #22684: RoidStation cargo lobby ATM puts money inside of the window
(WEB REPORT BY: burneddi REMOTE: 206.221.180.138:7777)
# Revision
7a9df6c928d601bdeea7299a7e6ee84a3fef8697

# Description

The ATM next to the cargo desk on roid deposits money inside of the window to its north when used.

# Steps to Reproduce

Try to withdraw money from the ATM.
# What you Expected

Money on the floor.

# What Actually Happened

Money in the window.

### LINKED ISSUE #23330: Syndicate Nuke Op Shuttle is way too close to the station on roidstation
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
2d0ef0b05ab2e3db3208de34cf2c01764ca647b6

# Description
The syndicate shuttle that nuclear operatives use is way too close to the station in the southern dock, making it pretty much a loot pinata for anyone who takes a walk through space

https://puu.sh/DJU7W/f67d56486c.png
https://puu.sh/DJU7C/6a00727409.png

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[roid]

Lots of QoL fixes in this patch.

The Captain's Spare is now harder to rush, more areas have sound systems, Security now has a small dormitory, the Ghetto Bar is more accessible, the SCP has been removed, the Lich King's Tomb should no longer implode into civil war on roundstart, and the Nuke Ops shuttle has been moved further away from the station. Maybe some other stuff I've forgotten too.

Closes #23330 
Closes #22684 

:cl:
 * rscadd: Roidstation: Did stuff!
 * rscdel: Roidstation: did other stuff!

### CODE REVIEW

**Comment by juanototo2** [comment]
>The Captain's Spare is now harder to rush
Instantly downboated

**Comment by ghost** [comment]
Muh atomicity
Don't remove the SCP, just make it harder to get.

**Comment by ShiftyRail** [comment]
As funny as the gunked spare-rushing was, all good things must come to an end

**Comment by boy2mantwicethefam** [comment]
Give pictures dammit

**Comment by SonixApache** [comment]
\>that changelog

**Comment by Diavill** [comment]
post pic of new spare placement so I can start theorycrafting my speedruns

**Comment by ShiftyRail** [comment]
I think he just added some shutters to the bedroom.
Pro start is to grab a blue toolbox, break windows to get into the cap office, and hack from here.

**Comment by SonixApache** [comment]
\>merged with *that* changelog

**Comment by FudgePucker** [comment]
Hey, he did add some stuff and deleted some other stuff.

**Pull request merged**
