### PR TITLE
Fixes Chameleon Projector

### PR DESCRIPTION
**Pull request by Kharkov72**
caused by [30138]

:cl:
 * bugfix: Fixed not being able to click on chameleon projectored people

### CODE REVIEW

**Comment by pedr69** [comment]
thanks kanef

**Comment by boy2mantwicethefam** [comment]
Use #(PR number) for links

**Comment by Kharkov72** [comment]
> Use #(PR number) for links

its BEEN A HWILE OK

**Comment by pedr69** [comment]
now that i think about it, this is a nerf, right?
even when the projectors made you pretty much invulnerable, people didn't use em

**Pull request merged**
