### PR TITLE
Some Balance to Dynamic Mode

### PR DESCRIPTION
**Pull request by DeityLink**
Proposed roundstart weights:

* traitors - 5 (up from 3)
* vampire - 2
* wizard - 3
* cult - 3
* nuke ops - 3 (down from 5)
* malf - 2 (down from 3)
* blob - 3
* rev - 2

Proposed roundstart costs (higher means there's less chance that many of those would proc at once):
* traitors - 10
* vampire - 25
* wizard - 30
* cult - 30 (up from 25)
* nuke ops - 40 (up from 30)
* malf - 40 (up from 35)
* blob - 45 (up from 30)
* rev - 35 (down from 45)

:cl:
* tweak: Roundstart ruleset weights have been adjusted. Overall there will be more traitors, less nuke ops and malf.
* tweak: High danger (potentially round ending) roles have had their ruleset costs increased, which lowers the chance of them happening at the same time.
* bugfix: Fixed a bug that caused two roundstart rulesets to proc at population levels that should never allow it.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
nice get

**Comment by ShiftyRail** [comment]
This will make "station-wide" antags less likely (making more rounds feel like traitor-vamp hellscape) while not addressing the issue of the occassional MALF-OPS-CULT-VAMP.

The real answer would be that a "station-wide" antag like Blob and Malf drastically reduces the chances of another one happening. Here is my modest suggestion : 
```
Drafting first ruleset.
Is it station-wide antagonist ? Then, either we allow for another station-wide antag to be drafted (25%) or we only allow for a "small" antag (like weeb, traitor, and debatably single vampire) to be drafted.
Continuing as decided.
```

This would solve the issue of BLOB-OPS-MALF, while still keeping it as a (rare) possibility, and would still allow traitors and the like to throw a wrench into the works during a malf or a similar station-wide antag.

**Comment by Kurfursten** [comment]
Rev needs a weight upgrade due to requiring 3 heads

**Comment by DeityLink** [comment]
Seriously why the fuck were the costs so low?

I've reduced the cost for rev, which was surprisingly the highest, and increased the costs for cult, nuke, malf, and espcially blob. We're now unlikely to see 3 of those at the same time, and less likely to see 2.

**Comment by SonixApache** [comment]
thank god
speedmerge whenever, shit's getting pretty ridiculous

**Comment by ShiftyRail** [comment]
This isn't the issue, the issue is that a "high level" antag shouldn't be allowed to coexist without another "high level" antag most of the time. Unless the first antag has already been neutralised.

**Comment by DeityLink** [comment]
@ShiftyRail I agree and that's exactly what my last commit addresses. High Level antags having higher costs doesn't make them less likely to occur, just less likely to coexist with other high level antags.

**Comment by ShiftyRail** [comment]
This could be done in a more explicit fashion than just choosing the threat requirements so that they add up to 100.

**Comment by DeityLink** [comment]
are you confusing weights and costs and requirements? Because I'm not sure what you're talking about.

**Comment by ShiftyRail** [comment]
I don't think so
You upped the costs in that last commit, right ? It's a way to prevent BLOB-OPS, if Blob =, say, 45 and OPS =, say, 45, BLOB-OPS requires >90 threat

I would do it in more explicit way, if I roll Blob (or Ops), then I `can't` roll Blob or Ops unless I pass a prob roll or something like that

**Comment by DeityLink** [comment]
Oh, you misunderstand, my intention is not to "absolutely" prevent blob-ops, just reduce the odds to something VERY exceptional, instead of something that may happen every other round. (or two rounds in a row like it just did)

**Comment by ShiftyRail** [comment]
That's also what I want, but rather than making it requires >90, I want it to pass a special, different, check.

**Comment by DeityLink** [comment]
Eh, that's down to implementation preferences then. I personally think we've got enough variables as it is to tweak with.

**Comment by Kurfursten** [comment]
I think I prefer deity's solution to something hardcoded. And I think we should tune the starting threat formula more.

**Pull request merged**
