### PR TITLE
simplifies colt

### LINKED ISSUE #26640: Colt single action army can't be reloaded
another fucking problem from #26608 
it requires the empty bullet casings be removed before it can be reloaded, but using its attack_self merely spins it because its super cool
`works with the colt` huh, you think someone would do that? just lie in a pr?

### PR DESCRIPTION
**Pull request by 9percents**
makes colt easier to use
all these times alt-click could've been used, but no one knew
I guess you can still lose your spaghetti if you accidently unload it, but that's on you
[tweak]
closes #26640 

:cl:
 * tweak: Makes colt single action army easier to use. Use in hand to cock and if it's cocked, unload. Press alt-click to spin it.

### CODE REVIEW

**Comment by Kurfursten** [comment]
It would be nice if you would add something like this

```
.../examine(mob/user)
  ..()
  to_chat(user,"<span class='info'>Alt click to spin the cylinder.</span>")
```

**Comment by 9percents** [comment]
you don't spin cylinder, you spin gun, bad Kur
but ye, I'll do it

**Comment by Kurfursten** [comment]
Right, I forgot it was a MGS reference instead of a western reference

Spinning the cylinder when??

**Comment by 9percents** [comment]
never, that would be too cool
also, not in this PR

**Pull request merged**
