### PR TITLE
adds 3 new toys

### PR DESCRIPTION
**Pull request by SonixApache**
- Added a bangerboi toy
- Added a femsec toy
- Added a hoptard toy
- Mapped them in to box

[sprites]

:cl:
 * rscadd: Added 3 new toys, sprites courtesy of otatoh

### CODE REVIEW

**Comment by Kurfursten** [comment]
pics

**Comment by SonixApache** [comment]
icondiffbot but
image

**Comment by beesil** [comment]
@Kurfursten 
image

**Comment by Kurfursten** [comment]
To avoid mapping conflicts we can fast track this assuming no major outcry in the next day

**Comment by boy2mantwicethefam** [comment]
Examining the bangerboy should stun and deafen you. I think I'll add that as a traitor item

**Pull request merged**
