### PR TITLE
Ectoplasm tweak

### PR DESCRIPTION
**Pull request by Eneocho**
If you consumed one unit of ectoplasm and ten units of degencalcium, you'd spawn a hostile skeleton and break a bone. However, if you consumed 10 units of ectoplasn and a hundred units of degencalcium you'd turn into a skeleman or skelevox. The problem was that you turned, yes, but you also spawned 10 skelemen that were hostile and would kill you, thus making the reaction not only dangerous to you, but the crew as well.
[oversight][bugfix]
:cl:
 * tweak: Consuming 10u Ectoplasm and 100u Degenerate Calcium simultaneously no longer spawns 10 hostile skeletons and transforms you (which ensured you died thanks to the brute damage and vulnerability). Instead it now only transforms you. If you react anything below those two values simultaneously, the skeletons will still be spawned.

### CODE REVIEW

**Comment by BomberBro** [comment]
The fact that this is such a huge method of destruction and nobody knew about it is a brutal commentary on how often this reagent is used.

**Comment by Eneocho** [comment]
It's more because of how finnicky it is to make. If you add the bone marrow too fast, you end up making aminomician instead of aminomicin. Which doesn't work with this.
Also the fact that you need degencalcium which needs both bar access and chem access, not to mention the fact that degencalcium is obscenely slow to heat without RnD, which further slows down the thing.
And finally the fact that you have to consume 110u for the reaction to turn you. Extra Ectoplasm fucks you up, extra degencalcium breaks all your bones.
I feel that if you do manage to get beyond all those hurdles, you deserve your skeleton gimmick.

**Comment by Eneocho** [comment]
Also the fact that bone marrow is fucking painful to acquire in volume, since you can only grind bones for it to get in large quantities and bones ain't a normally available item stationside.
Yes, you can get some marrow from discount dan's, but to get any sizeable amounts, you'd need either cargo help for extra discount dan's or a mechanics' help, for extra machines.

**Comment by GreatBigFailure** [comment]
This is actually intended but it probably is better gone, especially since it's such a rare use of it.
Also bone marrow is actually easy after the first 1u ecto is made since you can butcher skeletons for 3 bones which is 60u marrow

**Comment by GreatBigFailure** [comment]
Wait when did you remove the bone marrow requirement? Boo

**Comment by Eneocho** [comment]
To be honest I didn't even notice that there was no bone marrow requirement. I just changed the aminomician to aminomicin.

**Comment by Eneocho** [comment]
Checked, the bone marrow requirement was removed here: #29191
The aminomician uses 3 bone marrows and one aminomicin, which replaced the 3 marrows and 1 aminomicin on the recipe. I get it now. Reverting.

**Pull request merged**
