### PR TITLE
(cult) Summon Robes can be used on people other than yourself

### PR DESCRIPTION
**Pull request by gurfan**
https://user-images.githubusercontent.com/51427771/145334055-f37e3082-b734-4408-af71-98844cfb5ce9.mp4

Dress up your friends and/or enemies in valid-salad clothing.

:cl:
 * tweak: The summon robes rune now works on people other than yourself.

### CODE REVIEW

**Comment by chaklett** [comment]
dslkrk,1234edaaeae Good looks funny, Will love to see poeple who idnt see this pr update valid randomites!!!!!

**Comment by Kurfursten** [comment]
Thought this was going to be wizard summon robes

**Comment by PrimeDSS13** [comment]
If you're already wearing a backpack when you open somebody elses clothes box, does your old backpack vanish, or the new one? Does it just drop to the ground?

**Comment by gurfan** [comment]
The empty backpack that was in the box drops to the ground, as you can see in the video

**Pull request merged**
