### PR TITLE
More Trader Stuff

### PR DESCRIPTION
**Pull request by Kurfursten**
People have told me that traders don't have anything worth buying so here's some more miscellaneous stuff I think people might find cool.

**Ancient Flask** - contains 15u Karmotrine. Not scannable. It's not enough to make unlimited cool bar drinks like recovering the xenoarch plant so it doesn't obsolete that. It's just a one time flask so the barman can make cool stuff more often.

**Generous Crank** - A hand crank charger that can donate power to non-guns. Just hit it with the crank charger, no need to pop out the cell. You can't replace the cell in it, and its internal cell loses power over time when it isn't being cranked. Contains an unremovable high cap cell. Starts losing power after 2 ticks/4 seconds, 1 crank per tick.

**Supermatter Beaker** - Heats up the contents within, but it's probably best to set it down. While you carry it in your hands or pockets, it will irradiate you. If you were to get it implanted into your body it would be a permanent source of radiation. To avoid bloat, it along with the bluespace beaker (rarely ever purchased) and a comically large erlenmeyer have been placed into the chemist's pallet. The rads/tick has been upped to 3.

🆑 
* rscadd: Traders now sell an ancient flask with a small amount of karmotrine, a self-heating beaker, and a more user-friendly crank charger. The beaker is part of the newly improved chemist's pallet.

### CODE REVIEW

**Comment by tuypo1** [comment]
Does the supermatter beaker interact with the singularity at all?

**Comment by Kurfursten** [comment]
Not presently

**Comment by jknpj** [comment]
The crank is broken as fuck

**Comment by DamianX** [comment]
The beaker is the only passable one. I think Karmotrine should remain a xenoarcheology exclusive, special borers break emulsions, the crank seems too powerful.

**Comment by Kurfursten** [comment]
I can make the crank limited to non-weapons. What specifically are you worried about? Eguns?

FWIW I checked to make sure, batons and energy weapons don't let you fire unless you have the minimum shot cost (you can't just charge to 1 and fire) - I don't necessarily think it's even that strong. Is it better than having AEGs that just autocharge for you while you have a different gun out without having to frantically pump? The bison already does pump weapon. In terms of batons, you could already just pop out the cell and crank it, so this only saves you a handful of seconds.

I'm trying to figure out which item is spooking the pair of you.

**Comment by jknpj** [comment]
> I'm trying to figure out which item is spooking the pair of you.

It's **FREE** power with this simple macro:tm: for anything without the only downside that cranks have(needing you to manually replace the target's cell ).

**Comment by Kurfursten** [comment]
Presumably it's not **FREE**, the whole point of traders is that they are supposed to charge for goods.

Even if you are macroing (which I don't think is necessary compared to just pressing pgdown repeatedly), in what context other than a firefight is that a bad thing? Your active hand is a  slave to the crank vs just sticking cells into a cell charger, which is why almost no one uses that FREE POWER in the first place. They have other things they can be doing while it charges up. The other reason they don't get used is because most jobbies who would want to use a crank charger don't have the access to replace an APC cell which is the main thing they'd want to charge.

**Comment by jknpj** [comment]
>don't have the access to

Exactly the point of it being piss easy source of power. They need you to have access to the cell AND go through the process of swapping the cell(that is usually a reason to avoid replacing it instead of just using a charger). This crank has none of that and unlike the TG version, this one makes the power out of thin air.

I'd totally not use that to charge my Phazon mech on the go or material printer slave cyborg btw.
.t Not even your usual alblino

**Comment by Kurfursten** [comment]
Why not just do what actual ablinos do and put a couple supercells in your backpack? You can casually swap those out in seconds on your borg or phazon and be at full, no cranking necessary and much faster. Then when you are in the neighborhood, drop them off by the cell chargers because you don't need to babysit them.

But even if that was all the case, why is that a problem? What makes that unbalanced or broken exactly? It doesn't crank any faster than the cranks that already exist, you can totally crankcharge your phazon on the go right now if you'd rather do that than use supercell hotswapping. Nobody does.

I think you're overvaluing crankcharging in a world where unlimited power from engineering is the norm. It's okay for a product to be good and desirable! That's kind of the point.

**Comment by bathosbathtime** [comment]
Instead of having it majic the energy from the crank to the cell, have it be able to plug into an APC directly.
I really liked the wetvac because it was an incredibly mundane item that is also useful. The crank doesn't need to the product of miraculous reverse engineering done by the vox of all people on experimental ninja technology, it can just be a normal hand crank with a plug-in to contrast the makeshift version available to the crew.

**Comment by Kurfursten** [comment]
If the only concern was with the description I'd just change the desc back to my original one `Not to be confused with Scrooge at the end of A Christmas Carol.`

I don't think fluff is what jkn is complaining about though.

**Comment by bathosbathtime** [comment]
Making it plug into APCs wouldn't just be fluff since it would presumably only work for APCs instead of on mechs, cyborgs, and so on. I mean, it could also just be fluff if you wanted it to, and doing so would at least make me happier with it, but that will be if you so choose to do so.

**Comment by Kurfursten** [comment]
I think I made a realization as to what jkn was worried about in terms of balance, I wish he had made it more clear before but I think I understand now and have a compromise that I think will please everyone. Basically he was concerned about using the battery as an instant refill in your back pocket like a supercell without the hotswapping. Here's my proposed compromise that I think will please everyone:

* You cannot remove the cell from this crank, meaning you can't upgrade it to hold a supercell or whatever
* The cell in the crank passively loses power over time when not being used. This means that you can't just store up power for an instant recharge. You actually have to sit there and crank **right** when you want to charge.

Is this agreeable?

**Comment by DamianX** [comment]
OK, what about the other two?
Things that exist in the game don't necessarily need to be made more common as time goes on. Karmotrine being locked behind xenoarcheology instead of 50 space bucks makes it interesting.

The meme borer is supposed to be a rare meme, it's only acceptable to have it in the game because of how astronomically rare it is. I would hate to use a slippery slope argument but I don't want the average round to start including elements reminiscing of that that famous TG stickman screenshot.

**Comment by Kurfursten** [comment]
I'm not super attached to the borer idea. I figured it would be "opt in" since you'd know what you're getting into if you buy it, but frankly, if it will bring peace I'll axe it. Just for you Damian.

I don't think the flask encroaches on xenoarch. And I would know, the karmotrine stuff was all from me - special thanks Yred for finishing it later on. Bringing back the plant for karmotrine lets you mix up an unlimited number of drinks and go crazy - which matters since most of the karmotrine drinks have special metabolism where they consume extra reagents (notably suicide, waifu, and spiders all do this) to do their effect. I'm not worried about this making people not want to bring back fossilized plants anymore or something like that - it's more like a sampler you get at the store.

If you aren't convinced by the concessions I've made at this point in hopes of compromise, nothing is going to convert your vote, I suspect, so I'll just leave it there.

**Comment by ArchSunder** [comment]
Is that enough karmotrine for scientists serendipity?

**Comment by Kurfursten** [comment]
It is. Moonrocks not included, of course.

EDIT: After some testing I think I'm going to raise the price on the flask to $250 and lower the amount given to 20. This is for two reasons. One is at least a nod to Damian's argument about specialness, but mostly because this makes buying the karmotrine to make rags-to-riches not worth the tedium.

**Comment by agentofzog2** [comment]
MALF was the antag most cucked by dynamic since you're fucked if the captain stubs his toe.
With this milfs are only cucked by the camera and robot control consoles.

**Comment by Kurfursten** [comment]
I think you intended that message for the delta recall PR

**Comment by Kurfursten** [comment]
After testing and soul searching, I settled on $175 for 15u in the flask, and raised the radiation on the supermatter to 3/tick. I've moved the supermatter beaker and bluespace beaker into the chemist's pallet. Crank decay is a full crank per tick, starting 4 seconds after the last crank.

All worked in testing.

**Pull request merged**
