### PR TITLE
2

### LINKED ISSUE #7460: 3
Sometimes while dead or ghosted you will hear "3".
Literally just "3" pops up in your chatbox.
I have no idea what causes it. I have no idea what could it mean. It only happens while ghosted or dead.
Just... "3".

### PR DESCRIPTION
**Pull request by 9600bauds**
I had my fun.
Fixes #7460 

HOW DID THIS HAPPEN?
Way, way back then, there was no visible_message(), only show_message(). show_message() takes a second argument in the form of a number: 2 will only show this message to blind people, 1 will only show it to people who aren't blind .
This is how deaf messages were handled before. When visible_message() was implemented, this functionality was combined into making the first argument of visible_message() the non-blind message, and the second argument came to be the blind message.
I.E.: Before:

```
for(var/mob/O in viewers(src, null))
    O.show_message("[src] pings and flashes green!", 1)
    O.show_message("You hear a faint ping.", 2)
```

After:

```
visible_message("[src] pings and flashes green!", "You hear a faint ping.")
```

At some point in time, two things happened:
- Before the visible_message implementation, someone accidentally made the second argument of show_message() a 3. 3 does nothing, so the message showed just fine. Through some means, the 3 spread, I assume that it happened due to copypaste (oh, what's this 3 doing here? well I'd better leave it in, just in case it's important!). In this way, there were quite a few lines with this superfluous 3, which at the time did nothing.
- After the visible_message implementation, many show_message() calls were hastily modified to use visible_message() instead. In doing so, the second argument (be it 1, 2, or the improper 3) would have to be removed. I assume what happened here is that some sort of script was used, and it did not account for 3. This resulted in 3 being left in as the second argument, which as you remember, is the blind message.

As a result, most medical machines plus a few odds and ends ended up having 3 as their blind message. Since people are rarely blind (more commonly dead, as I believed at first), this was very subtle, and finding the cause was also rather difficult. I don't think I would have found it if not for to_chat. What's really incredible is the chain of events that allowed for this to come to happen.

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
:-1:
 :-1:  :-1: 
:-1:  :-1:  :-1:

**Comment by 9600bauds** [comment]
blame Clusterfack

**Comment by Ephx1** [comment]
Mystery solved!

**Comment by PJB3005** [comment]
:-1:
**<sup><sup>SPAM THE MEME TAGS</sup></sup>**

**Comment by Imagebard** [comment]
There is no need to fix it

>Balance

This isn't a balance fix, either.
Leave it be.

**Comment by 9600bauds** [comment]
At which point do we turn it into 1

**Comment by clusterfack** [comment]
>There is no need to fix it


When can we start banning people for saying this

**Comment by Imagebard** [comment]
There is no need to fix it

**Comment by 9600bauds** [comment]
There is no real need to fix it besides progress for the milestone which won't be completed anyways

**Comment by Imagebard** [comment]
The efforts of putting it on the milestone and putting the "Balance" label on this PR is obviously an attempt to force it to be merged when there is no need to.

**Comment by PJB3005** [comment]
@Imagebard I was spamming meme tags

**Comment by Imagebard** [comment]
CONTROVERSIAL ISN'T A MEME YOU FOOL
IF YOU LEAVE THAT TAG OFF ANYONE CAN COME OVER HERE AND THINK "WOW I SHOULD MERGE THIS"

PUT IT BACK

**Comment by clusterfack** [comment]
Wow I should merge this

**Comment by 9600bauds** [comment]
joke's on you it was 100% untested ;^)

**Comment by clusterfack** [comment]
PANIC

**Comment by Imagebard** [comment]
>1 check was pending

**Comment by 9600bauds** [comment]
By slaying the 3 I have become a collaborator
This will soon prove a huge mistake

**Comment by Exxion** [comment]
Hey wait you get collaborator status for removing 3 but I get nothing for fixing pulling windows being hellish
I want a medal

**Comment by 9600bauds** [comment]
I was also appointed to this position partly due to my DE-LICIOUS rice and tuna recipe
img_20151109_230833201

**Comment by Ephx1** [comment]
What the fuck

**Comment by 9600bauds** [comment]
You've never had rice and tuna?

**Comment by ghost** [comment]
:-1:

**Comment by Exxion** [comment]
What have I done

**Comment by clusterfack** [comment]
Why are you posting cat food

**Comment by 9600bauds** [comment]
Ask wwjnc

**Comment by Zth--** [comment]
Disgusting

**Pull request merged**
