### PR TITLE
remove glasscode episode 1: remove starman

### PR DESCRIPTION
**Pull request by SonixApache**
it's been used about 3 times since it was added, and as such it is needless bloat
i will remove relevant files from the `.dmi`s some time soon

### CODE REVIEW

**Comment by Eneocho** [comment]
Rather than removing it, I'd make it into a mid-round antag.

**Comment by Kromkar** [comment]
That is not a good changelog I wouldn't care except you got onto my ass about it before.

**Comment by Kammerjunk** [comment]
entries of confusion

**Comment by SonixApache** [comment]
\>`maps/LampreyStation.dmm:189584:error: undefined type: /obj/item/weapon/gun/energy/starman_beam`
fucking HAROLD

**Comment by Eneocho** [comment]
The starman gun is the best energy gun in the game, if only because of the 8 bit energy gun noise.

**Comment by ShiftyRail** [comment]
But why? If you really want to shave off unused things in the repo there are far worse offenders. I'm not sure if the 3 MBs of oggs matter this much since it's `only` 28 files. BYOND's weakness in packaging assets, not sending them

I'm really confused as to why you spent some time doing this.

**Comment by SonixApache** [comment]
\>why would you remove bloat, and not other bloat?
Gotta start somewhere. Bloat is bloat. I suddenly remembered this and figured I'd shave it off.

**Comment by ShiftyRail** [comment]
According to Kammerjunk, this PR removes exactly 300KB worth of data in the rsc.

**Comment by SonixApache** [comment]
that's more than 0

**Comment by Kammerjunk** [comment]
that was a bit of a shitpost
it's more like 1 MB, but that still assumes it scales exactly
the point is that it's literally fuckall

**Comment by Eneocho** [comment]
> 
> 
> According to Kammerjunk, this PR removes exactly 300KB worth of data in the rsc.

such bloat
much wow

**Comment by jknpj** [comment]
Don't tell them about the machete's 20 different sounds

**Comment by PlausibleDeniability** [comment]
In today's episode of bored c*ders

**Comment by boy2mantwicethefam** [comment]
Delete the unused alien races instead except the skrell because apparently Clock wants to rework them

**Comment by DrSnips** [comment]
I'm actually in support of this because nobody has mentioned this in the last half a year to my knowledge. What are the reasons for keeping it? Do people really feel that strong about it, I have my doubts since it's been a really long time since anyone touched it.

**Comment by Eneocho** [comment]
> 
> 
> Delete the unused alien races instead except the skrell because apparently Clock wants to rework them

Skrell are the frog people right? I want me frog people.

**Comment by DamianX** [comment]
No. /vg/station is append-only.

**Comment by Eneocho** [comment]
> 
> 
> I'm actually in support of this because nobody has mentioned this in the last half a year to my knowledge. What are the reasons for keeping it? Do people really feel that strong about it, I have my doubts since it's been a really long time since anyone touched it.

I got a cool starman sound effect "spell" as a MoMMI on one round around early december. It was fun seeing everyone comment on the "juke being broken" when it was the spell.

**Comment by KingofHONK** [comment]
Its great for EORG.

**Comment by Blithering** [comment]
Against this because I got given the soundtrack spell when I was playing disco wizard gimmick.

**Comment by SonixApache** [comment]
i can only assume that nobody actually cares about keeping this unused content, but that people just go rabid at the thought of things being removed alongside my name carrying eternal stigma

**Comment by anunknownentity03** [comment]
😕

**Pull request closed without merging**
