### PR TITLE
Defib tweak

### PR DESCRIPTION
**Pull request by adacovsk**
[tweak]

With this PR, and although it's amusing, you can no longer defib husks

:cl:
 * tweak: No more walking, living, breathing husks

### CODE REVIEW

**Comment by strawberrytan** [comment]
this is a travesty

**Comment by pedr69** [comment]
make the message text clearer the body can still be cloned, as it is now you would think the body is unrevivable

**Comment by ManopolisJones** [comment]
Facial reconstruction surgery for husks, when?

**Comment by djkramer123** [comment]
what's the point of doing this

**Comment by Eneocho** [comment]
Looking for a spot on the fun removing coder cabal I see.

**Comment by adacovsk** [comment]
> what's the point of doing this

husks aren't identifiable

**Comment by angryturnip** [comment]
Soulless

**Pull request closed without merging**
