### PR TITLE
Spessmart Inventory Tweaks

### PR DESCRIPTION
**Pull request by Kharkov72**
There's a few price changes in there, such as: 
-lowering pill prices overall (They're one use, they aren't worth THAT much) 
-soap (it's soap)

but this is mostly adding new items, including: 
the clone balloon
some water guns
various new pills
an esword (why did it have a double esword but not a single?) 
a glowing voucher for a VERY large sum of money
and a silencer
also I replaced the broken component with a breathalyzer because come on
[general]

:cl:
 * rscadd: Spessmart has some new inventory!

### CODE REVIEW

**Comment by MadmanMartian** [comment]
why are you making these changes?

**Comment by Kharkov72** [comment]
Because I felt that while the spessmart inventory is good, it could use some polishing up with fresh / newer items.
And because I felt prices required a bit of additional tweaking.

**Comment by utilitas-** [comment]
Why in all fuck would the glowing voucher be so expensive? If they found the space mart, it could have easily been a phazon asteroid instead. Make it cost fifty buckaroos.

**Comment by MadmanMartian** [comment]
It's an inside joke. A player was banned by Mr Pain and was told "unless you have a GLOWING voucher from another server, you're not being let back in"

So, now the glowing voucher is coveted.

**Comment by utilitas-** [comment]
Ah yes, an inside joke that makes absolutely no sense and isn't referenced by the item itself. Not confusing _in the slightest._

**Comment by MadmanMartian** [comment]
guess you're not a cool kid then

**Comment by jknpj** [comment]
Do references have to explain themselves

**Comment by Kharkov72** [comment]
fair points, I'll lower the price somewhat, but I do want the inside joke to be somewhat preserved.
I'll make it 150

**Comment by MadmanMartian** [comment]
Why? It's a coveted item similar to the goonecode

**Comment by Kharkov72** [comment]
good idea obtained, I'll make it the same price as the gooncode (400)

**Comment by beesil** [comment]
:+1: for waterguns

**Pull request merged**
