### PR TITLE
NRV Horizon: Electric Boogaloo

### PR DESCRIPTION
**Pull request by DorainGrey**
## What this does
Adds Horizon back to the map rotation.
Credit to @BurntDevil for doing a lot of the work remapping. I just reworked all the broken bits and updated to latest standard. Open to suggestions on what the pop restrictions should be, at the moment I'm going with a 25 player max and 5 player minimum.

## Why it's good
I think we are missing good medium pop maps and I think Horizon can fit the bill here, it's a good alternative to synergy.
Most of the complaints about this map have been addressed with this remap and I don't think it will be hated this time round.

## Changelog
:cl:
 * rscadd: Re-adds a new remapped version of the NRV Horizon as a medium pop station,

### CODE REVIEW

**Comment by tinysaturn** [comment]
based....so fvcking zased....

**Comment by Kurfursten** [comment]
> Ultimate comfy square bar replaced with this hallway bar

I told him this was a mistake.

**Comment by DorainGrey** [comment]
Update: Shuttle isn't working, please don't merge until I've fixed.

**Comment by ErrorsWindows** [comment]
you can turn it into a draft to signify that it's going to be worked on for two weeks and then forgotten entirely

**Comment by calzilla1** [comment]
Before merging, we need a gnome sweep

**Comment by adacovsk** [comment]
Make sure disposals work, because they didn't before

**Comment by Kurfursten** [comment]
Found your problem, it was just a minor issue of:

iaa no delivery sorter + can't reach
reversed pipe outside recycl
no trashcan in some likes e.g.: jani
wtf in meeting room manifold+abs no reason to go so far
(same on right)
more weirdness on the linkup near CMO to recycling (cannot reach)
court nosort double unreachable
near medbay side exit multiple destinations on single sorter + manifold in from recycl??
manifold inside medbay: will send trash from lobby to storage
all of chem, kitchen, bar, botany on a single sort and also linked into weird return to bridge

**Comment by Eneocho** [comment]
Actually looks pretty good.

**Comment by Eneocho** [comment]
Interesting that this uses the regular o2, plasma and n2 miners instead of the combo miner it used on the last iteration (it was a space gas collector, which harvested gas at decent rates by moving at lightspeed via bluespace).
Why no N2O or CO2 miners?

**Comment by calzilla1** [comment]
If this gets merged, it would be nice for some updates later down the line to give some unique events or mechanics due to the "station" actually being a space ship.
Planet exploration, different cargo merchants, space battles, etc
Also add a blank machine frame to RnD plz and tnx u :)

**Comment by adacovsk** [comment]
> If this gets merged, it would be nice for some updates later down the line to give some unique events or mechanics due to the "station" actually being a space ship.

Maybe annoying screenshake for "turbulence" when entering atmosphere

**Comment by Eneocho** [comment]
The event being landing on snaxi and it was a covert snaxi round all along.

**Comment by ErrorsWindows** [comment]
The event being landing on Island but it's on the mining asteroid and all the atmospherics on the ship are being vented with nitrogen for some reason

**Comment by pedr69** [comment]
> instead of the combo miner

i removed the combo miner because it didn't work at all #33723
there's supposed to be a `new gas_giant` made in the sun subsystem init but couldn't access it at all

**Comment by Kurfursten** [comment]
The nonfunctional gas miner was the gas giant one, we never used that code; the "graviton" combo miner worked (I even saw it in action many times on horizon). However, most engineers were too stupid to set up their own filtering so if we go back to the graviton gas sink I suggest having filter lines already built for them.

Given the code cleanup it would be pretty easy to re-implement if you did want to include it, since now it's just a single list to generate a mix of gasses.

**Comment by SECBATON-GRIFFON** [comment]
the command section still feels a bit cramped, i'd look into that
also make the mine look a bit less like parts are copypasted together by just smoothing them out, and remove the wizard den and beach since they're autogenerated now

**Comment by jwhitak** [comment]
Add directional arrows to the cargo belts if you could!

Also, this is a good chance to make a new derelict instead of a standard copy pasted box. Let the little robots make their RUST. Give them the supplies. Do it.

**Comment by SonixApache** [comment]
i'll re-iterate that having a ship map without accompanying features will be just as disappointing as the last time we had it
though i cannot remember the reasoning behind my suggestion of just turning horizon into an away mission

also,
\>burnedevil
\>mapping
howmanytimesoldman.jpg

**Comment by BurntDevil** [comment]
Dont forget to get rid of my glass shielding shit thats still on the side of the ship. I did that tinkering with concepts for roid protection. Either toss it, or figure out how to make it look right.

**Review by Kurfursten — CHANGES_REQUESTED** [review]
Fix the terrible disposals

**Comment by KingofHONK** [comment]
Dont forget to add an updated map render for the website!

**Comment by ValkyrieSkies** [comment]
Get back to work.

**Comment by DorainGrey** [comment]
@Kurfursten I've fixed all the issues here, only one or two parts of the destination tagging aren't working janitors office, rest is fine. I may just remove this, if I can't work it out.
I think it's pretty much ready to merge.

**Comment by BurntDevil** [comment]
Post an updated render, eh?

**Comment by Kurfursten** [comment]
Post the new render and I will look it over

**Comment by DorainGrey** [comment]
@Kurfursten @BurntDevil Updated.

**Comment by DorainGrey** [comment]
Made all requested changes from feedback in discord.
Ready to merge @Kurfursten

**Review by Kurfursten — APPROVED** [review]
Fix conflicts

**Comment by DorainGrey** [comment]
Conflict resolved @Kurfursten

**Comment by Kurfursten** [comment]
This will not be live until Pomf compiles it

**Comment by Eneocho** [comment]
wtf compilebros we got too cocky...

**Pull request merged**
