### PR TITLE
Gives water flower the OPENCONTAINER flag

### PR DESCRIPTION
**Pull request by BarneyGumball**
`shittermcckey/(Epic Funny Clown!!!!!!!!) has splashed 50u of lube from a beaker [0x420aaay] onto Water Flower.`

### CODE REVIEW

**Comment by gbasood** [comment]
This flag doesn't affect any other behavior. Right?

**Comment by Kurfursten** [comment]
The main notable other behavior is that it allows you to examine the reagents contained in the item.

**Comment by BarneyGumball** [comment]
`OPENCONTAINER` is just a flag to see if an object has its lid closed.  It only effects whether you can pour a reagent into the thing (and out of in some cases) and the examine behaviour that Kurf mentioned.

**Comment by Exxion** [comment]
What could possibly go wrong

**Pull request merged**
