### PR TITLE
Fixes atmospherics.Destroy() runtime if client is null

### PR DESCRIPTION
**Pull request by gbasood**
When this runtimed, you were left with a non-functioning pipe that could not be replaced or removed in any way.

### CODE REVIEW

**Comment by gbasood** [comment]
```
16:48:55 Runtime detected
Cannot read null.images at atmospherics.dm:57
 proc name: Destroy (/obj/machinery/atmospherics/Destroy)
  source file: atmospherics.dm,57
  usr: Circe the Conquerer (as Rayner... (/mob/living/carbon/human)
  src: Air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden)
  call stack:
Air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden): Destroy()
Air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden): Destroy()
Air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden): Destroy()
qdel(Air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden), 0, 0)
Air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden): ex act(3)
explosion(the floor (76,146,1) (/turf/simulated/floor), -1, 1, 2, 5, 1, 0, 1)
```

**Comment by clusterfack** [comment]
I'm pretty sure that nothing in player list should have a null client at any point. And that if that is occurring there is a larger problem at hand than this.

**Comment by gbasood** [comment]
@clusterfack I could include an ASSERT on mind/New to tell us what minds are ending up with null keys?

**Comment by gbasood** [comment]
Well, #7061 there's this theory

**Comment by d3athrow** [comment]
Likely cause is it was processing the players list and somebody logged out before it got to them and while I dont know the code it likely uses for(x in list) which makes a temporary copy of the list.

> look at changes
> for(x in list) is right there

so yeah sanity is the only way to fix this without using a more expensive loop.

**Comment by gbasood** [comment]
If someone logs out, Logout() processes their removal from the players list.
If a mob is destroyed, or the client value of a mob is changed, Logout() is called.

It should ALWAYS remove from player list unless the mob does not inherit mob/Logout()

The code that threw this runtime prevented pipe destruction for the entire round, so it wasn't just that it missed a mob once. That mob was in the players list for the rest of the round.

**Comment by clusterfack** [comment]
The **only** benefit that player_list provides is that it has a client. This just swept a major issue under the rug for no reason.

**Comment by gbasood** [comment]
@clusterfack It's still better than looping through all mobs, at least

**Comment by clusterfack** [comment]
No, not really. Because if we need to apply this fix we need to apply it to EVERY loop through player list, and if we need to do that then **WHAT IS THE FUCKING POINT OF PLAYER LIST**

**Comment by gbasood** [comment]
You're welcome to figure out what went wrong here but my bet's on #7061

**Comment by clusterfack** [comment]
Byond is single threaded. What you described there and d3athrow described here is both impossible. It wont del() the client in this case until something sleeps or finishes and the game has time to do so.

**Pull request merged**
