### PR TITLE
Adds "recall" artifact effect.

### PR DESCRIPTION
**Pull request by PJB3005**
When activated, the positions of all elegible objects (basically unanchored) objects around it are recorded. When the artifact deactivates after a charge time, all the recorded objects are teleported *back* to their position at the time of activation.

Objects are only sent back if the container they're in actually supports it. So no breaking the game sorry.

Also added a weakref type since I need that for this to avoid causing hard dels.

:cl:
 * rscadd: Adds a new "recall" artifact effect. No, it does not recall the shuttle.

[content]

https://user-images.githubusercontent.com/8107459/103779679-62244e00-5034-11eb-9ba1-58f001ac978a.mp4

https://user-images.githubusercontent.com/8107459/103779573-3ef99e80-5034-11eb-9dd0-32ade7d698d0.mp4

### CODE REVIEW

**Comment by DrSnips** [comment]
While I think this is really cool I anticipate a lot of game breaking stuff happening. I have mixed feelings.

**Comment by PJB3005** [comment]
> While I think this is really cool I anticipate a lot of game breaking stuff happening. I have mixed feelings.

Oh, I agree.

**Comment by ShiftyRail** [comment]
Don't we already have a weakref type

**Comment by PJB3005** [comment]
> Don't we already have a weakref type

image

**Pull request merged**
