### PR TITLE
HoS hat is visible on greyliens now

### LINKED ISSUE #13363: The Head of Security hat sprite doesn't appear on Greys
(WEB REPORT BY: digitalis REMOTE: 172.93.109.202:7777)
>Revision ec9c007416dd01bc8f7ddead3278586572afdd03 

>General description of the issue

Title
>What you expected to happen

>What actually happened

>Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by Gef21**
fixes https://github.com/d3athrow/vgstation13/issues/13363

🆑 
 * rscadd: HoS hat is now visible on greys

### CODE REVIEW

**Comment by kol1th** [comment]
Wait that actually works?

**Comment by gbasood** [comment]
I thought we needed a sprite for it

**Comment by Gef21** [comment]
yeah I even tested it

**Comment by kol1th** [comment]
holy SHIT i didn't do this for the other ones, I just re-added the same sprite to the grey DMI. Just fuck my shit up.

**Comment by Gef21** [comment]
http://i.imgur.com/r03DViX.png lmao

**Comment by Probe1** [comment]
why do we have species fit but it doesn't prevent the user from equipping it if the race isn't listed

**Comment by Intigracy** [comment]
species_fit means it's searching in that species' dmi for the icon instead of the regular one (for each species listed)
species_restricted can either restrict it to the listed species OR restrict the listed species from wearing it

**Pull request merged**
