### PR TITLE
PERMISSIONS admins can now make server polls

### LINKED ISSUE #9638: I want server polls for admins.  We need it.
https://github.com/tgstation/-tg-station/pull/11919

This.   I want this.   The plastic versus gold/silver/uranium is the latest reason why.  Asking people to register on forums and expecting no one to register twice to get two votes, and expecting admins to carefully check registrations for that, it's crazy.  

We need this.

### PR DESCRIPTION
**Pull request by Intigracy**
@D3athrow (or someone more intelligent than I in the workings of sql) I'm gonna need you to look this over for me to tell me whether or not I fucked anything up / forgot something.

closes #9638

### CODE REVIEW

**Comment by Probe1** [comment]
```

code/modules/admin/create_poll.dm:20:error: SQLtime: undefined proc
code/modules/admin/create_poll.dm:21:error: SQLtime: undefined proc
code/modules/admin/create_poll.dm:58:error: format_table_name: undefined proc
code/modules/admin/create_poll.dm:64:error: format_table_name: undefined proc
code/modules/admin/create_poll.dm:111:error: format_table_name: undefined proc

```

**Comment by Intigracy** [comment]
I knooooooooooooooow

**Comment by Intigracy** [comment]
Hoping nothing breaks from this.

**Comment by 9600bauds** [comment]
naaaah

**Pull request merged**
