### PR TITLE
Adds disposals to Packed

### PR DESCRIPTION
**Pull request by brndd**
## What this does

Maps in a disposals system to PackedStation.

## Why it's good

Rumour has it the only reason PackedStation doesn't have a disposals system is because the mapper who originally made the station couldn't figure out how disposals works. I don't know if the rumour is true, but lack of disposals always bothered me and I've wanted to map them in for years.

I had to change the layout of cargo a bit and grow it into the small maintenance next to it, and also move the gateway a little:

2023-10-19T22:24:35

Otherwise the only changes are replacing trash compactors with disposals units, as well as adding disposal units to a couple of rooms that did not have a trash compactor before (e.g. kitchen, mechanics, IAA, janitor).

I also added a new maint connection near dorms (the airlock near the center of the picture, next to the ATM):

2023-10-19T22:24:56

## Changelog

:cl:
 * rscadd: PackedStation now has a pneumatic disposals system.

### CODE REVIEW

**Comment by kilozombie** [comment]
end of an era

**Comment by angryturnip** [comment]
I like turning people into human cubes with the compactors as an antag

**Comment by brndd** [comment]
There are still compactors in permabrig and virology, so not all is lost.

**Comment by djkramer123** [comment]
You can also order compactors from cargo

**Comment by Kurfursten** [comment]
He has the support and frankly I don't see jannies using the compactors much (I coded them so I have no grudge against em)

**Pull request merged**
