### PR TITLE
Revert "attack animations"

### PR DESCRIPTION
**Pull request by PJB3005**
Reverts d3athrow/vgstation13#12678

I'm in different to the change itself but holy Shit man.

### CODE REVIEW

**Comment by ghost** [comment]
self-merge this when

**Comment by Kammerjunk** [comment]
I don't get it. I'm way opposed to the attack animations but if you're indifferent, is this like for discussion or something?

**Comment by Zennyization** [comment]
Self merging is basically slapping people in the face with a big fuck you tbh.

**Comment by SysadminJeroen** [comment]
What is wrong with it? Asking it because I haven't joined the server yet since it got merged.

**Comment by PJB3005** [comment]
Self merging is the issue, not the PR itself.

This kind of controversial Shit needs proper discussion not hasted self merging.

**Comment by aceedex** [comment]
No no its okay, he's just test self merging it and come back at a later date!
😂

**Comment by PJB3005** [comment]
Even if he does it still doesn't warrant such poor discussion.

**Comment by Intigracy** [comment]
Ah yes, 100+ comments, 2/3 people voting in favor on the PR itself, plus the over 50% who did on the poll.

Instead let's just let it sit for a month throwing the same arguments back and forth.

**Comment by kilozombie** [comment]
>Let's not self merge.

>But it's okay if it's me, I'm special!
>So long as I think I'm right, I'm allowed to do whatever I want! Proper github etiquitte doesn't matter!

- Intigracy

**Comment by Probe1** [comment]
We've been having the discussion for the last 2 years while every other server passed us and old players who don't want change stymied it with non arguments.

👎

**Comment by aceedex** [comment]
Just because other servers do it doesn't mean we should probe

**Comment by Zennyization** [comment]
Server that have attack animations just come off tacky to me.

**Comment by Intigracy** [comment]
@kilozombie cite your sources

**Comment by kilozombie** [comment]
Principles are important. Self-merging is counter-productive. I don't care if you're impatient. You'll be mad about the same shit the MOMENT you're on the other side of the fence, Probe, I promise.

@Intigracy 
lol idk bee urself

**Comment by Probe1** [comment]
@aceedex _every_ other server?

It hurts me to read this because I thought progress bars were horrible, got overruled, and accepted it.  This isn't Probestation.  I accept that I don't get everything I want.  

This is basic bitch quality of life shit that doesn't need arguments.  But we refuse to update to 2015, even a year later when it's obviously improved the server for every other codebase.  But not us.  

This is what I'm spending my time arguing about instead of adding features that have been requested.  An issue that has been voted on several times and the playerbase wants.

**Comment by kilozombie** [comment]
>that doesn't need arguments

OK, I'll repost my actual, legitimate argument, that you can make of what you will.

Attack anims will encourage new players to more rarely check the chat box during frantic moments. They'll come to expect everything important to be in the graphics portion, and might just flat-out ignore the chat-box for a while. This means that they'll ignore people saying things, whether pleading as they're being toolboxed or screaming over radio.

I don't mind it being merged. I'll certainly have anims turned on. But don't discard shit just because some of the people arguing for it are fucking awful at arguing. There are legitimate reasons not to merge the change, and willfully ignoring them instead of providing counter-arguments is frustrating to me.

**Comment by Probe1** [comment]
That is absolutely bogus and an argument that has only appeared with this PR.  You have never made the same argument for ... ! ? boxes appearing above players when they enter something to chat.

It cannot be applied one way.  Either _the current system_ which acts exactly how attack animations will creates a huge issue, one that no one including yourself has ever raised, or it's trying to find a flaw that does not exist.

**Comment by kilozombie** [comment]
With this PR? No. I made this argument in the last PR multiple times and so did yclat, once you move past his yelling, and so did Pomf. Again, willfully deafening yourself from legitimate arguments?

There is a flaw. That's my argument. Attack anims being on by default will teach new players that they don't need to check the chatbox during combat.

**Comment by kol1th** [comment]
That's like saying the speech bubbles popping up will teach new players to not look at the chat box. Jesus fucking Christ how is this even that much of an issue? It's not even a large change. There aren't even any real arguments against it, just people bitching and moaning about MUH CHANGE. I've seen a lot of self merges in the past and this definitely wasn't the worst one

**Comment by kilozombie** [comment]
Doesn't matter if it's a 'bad' self merge or not. It means that things can be self-merged if the merger thinks it's "obvious", which is the slipperiest damn slope in the universe.

**Comment by aceedex** [comment]
Here's my argument:
It looks like shit

**Comment by kilozombie** [comment]
@Probe1 

Probe1 commented 18 hours ago
Because 30% dont want it and thats fair to say when 30% are quite a few people.

This is only accurate for the github PR, which I would argue is less valid than the server poll. The split on that poll is actually 45-55%, which is a much, MUCH narrower margin.

**Comment by ghost** [comment]
"Attack Animations make it easier to see who is hitting who"

Except that you'd still need to examine both people to attach the name to the character to know who was who. If it's two random name random bodies fighting you won't recognize their sprites instantly so you'd have to hover over them to figure out who was who.

Under attack animations you see which sprite hits who.
Currently you see which name hits who.

I'm not sure how attack animations will make it easier for new players, if anything it's going to make it harder for them. Attack animations don't give as much information as the chat box, but it's visual so they'll be drawn to that instead rather than reading the very helpful attack text. Not to mention it's incredibly easy to just move your mouse over somebody and shift click, there shouldn't be any trouble here.

**Comment by Exxion** [comment]
You know that the text will still be there too, right?

**Comment by kilozombie** [comment]
>but it's visual so they'll be drawn to that instead rather than reading the very helpful attack text.

Yes, Solarious knows the text will still be there.

**Comment by Exxion** [comment]
In my defense, it was 4 AM

You know you can still look at the text box even after seeing the animation, right?

**Comment by kilozombie** [comment]
I think that's what will happen with most players, personally.
But it might be more helpful if they learn with the text-box only, as it teaches them to check that box for other important information, even during a frantic situation.

**Pull request merged**
