### PR TITLE
Fix queens ventcrawling

### PR DESCRIPTION
**Pull request by clusterfack**
Nobody thought this was worth reporting as a bug though it totally was.

### CODE REVIEW

**Comment by Konater** [comment]
rip

**Comment by d3athrow** [comment]
this isn't oop
override queen's altclickon to not do shit to vents/scrubbers

**Comment by clusterfack** [comment]
This does that, but still leaves the functionality of calling the parent for normal altclickon

**Comment by d3athrow** [comment]
You're still handling something in the parent when it should be handled in the child, involving an unnecessary proc call

**Comment by ComicIronic** [comment]
Yeah, the real thing is that queens shouldn't be able to ventcrawl full-stop. This isn't the way to go about it.

**Comment by Exxion** [comment]
Maybe I'm just being an idiot, but I don't see a way to handle it in the child without also breaking alt+click inspect tile, etc. for alien queens.

**Comment by ComicIronic** [comment]
The way is to override the queen's ventcrawl verb.

**Comment by clusterfack** [comment]
That would work, but pomf removed the portion where I had ventcrawling directed towards their own ventcrawling verb and replaced it with a direct line to handle ventcrawl.

**Comment by d3athrow** [comment]
whatever

**Pull request merged**
