### PR TITLE
Species-restricted jobs and vox traders 2

### PR DESCRIPTION
**Pull request by unid15**
Same as #9073 , with some extra changes:
- Traders now spawn with a station-bounced radio on their belt (if they become traitors, the radio is used as an uplink)
- Traders now spawn with an empty wallet and some provision: a box of donk-pockets and a thermos with a random amount of one of the following drinks: coffee, hot cocoa, ice coffee, tea, ice tea, water, ice, iced beer.
- Removed the SQL stuff and made Traders a "civilian" job. No changes gameplay-wise, but this won't break saved characters anymore

### CODE REVIEW

**Comment by Brolaire** [comment]
sick

**Comment by SysadminJeroen** [comment]
Merge when?

**Comment by Shadowmech88** [comment]
> made Traders a "civilian" job

Will they appear on the manifest?

**Comment by unid15** [comment]
Nope, as I said this changes nothing except for not breaking saved characters anymore

**Comment by ririchiyo** [comment]
make the jobs handled with the map datums

**Comment by ghost** [comment]
Uh oh

**Comment by icantthinkofanameritenow** [comment]
RIP Vox Traders.

They died how they lived: completely hated.

**Comment by 9600bauds** [comment]
'...by me and thus everyone!'

**Comment by icantthinkofanameritenow** [comment]
@9600bauds 
Riri slapped the DNM label on it, that by definition means it'll never see the light of day. 

But seriously, what the hell does this job offer that being a Vox Assistant doesn't? Is it really that hard to ask a miner or the AI to let you onto the trading post now?

**Comment by 9600bauds** [comment]
> Riri slapped the DNM label on it, that by definition means it'll never see the light of day. 

What fucking precedent are you going by?

**Comment by icantthinkofanameritenow** [comment]
@9600bauds 
The one I've seen happening here all the time, why?

And I'm still waiting to hear how this is different from being an assistant minus the access.

**Comment by Shadowmech88** [comment]
> The one I've seen happening here all the time

Can you cite some specific PRs?

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88

None of the top of my head, but I heard it was a common enough thing in the IRC once. 

But in all seriousness, my main concern is with the job's apparent lack of purpose. If you just want to have a "space explorer" job, why limit it by race anyway? 

Even then, the actual exploring is nigh-impossible without a spacepod now. If the one round I saw them present is an indication, they'll be little more than botanists with hardsuirs. 

That, and I thought that the "immigrants" meme was awful from the beginning, and that you should feel bad for indulging it.

**Comment by 9600bauds** [comment]
I know a few people that would disagree with you in your alleged precedent.

**Comment by icantthinkofanameritenow** [comment]
Forget the precedent, just tell me this: if the job is for people who just want to fuck off into space and not do anything useful for the round, why not just make it a subtype of assistant and call it "explorer" or something? Right now it just feels wasteful and self-indulgent to Vox, who quite frankly don't even deserve it. They already have an entire game mode specific to them, why should they get species-locked jobs just for them too?

**Comment by Shadowmech88** [comment]
Why not?

**Comment by ghost** [comment]
@icantthinkofanameritenow it is (or was) framework for species-specific jobs, including a whitelist and blacklist, so yes it would come off as a bit 'self indulgent' when it does actually make use of a whitelist. 

Vox trader is an example of such so somebody else who would want to make a species-specific job has some form of example to go off of, and it makes use of a currently existing structure on most maps that otherwise would go unused except during Vox raiders.

**Comment by unid15** [comment]
The one round that vox traders were available, the players enjoyed it. The job opens up some roleplay and bus opportunities as well.

@ririchiyo done

**Comment by Brolaire** [comment]
tbh i disliked the idea of ever playing Vox until I saw the trader PR

**Comment by SysadminJeroen** [comment]
I also didn't like the idea of ever playing Vox like @Brolaire until I saw the Vox Trader pull request.

**Comment by icantthinkofanameritenow** [comment]
Fine, I get that. It just seems like a job bereft of any actual purpose. And if one of them is a traitor, they're boned; not only are they not on the manifest and therefore suspicious enough as it is, their ability to actually get into the station proper is limited at best.

And what would you propose as other species limited jobs, might I ask? I for one would start by making all heads of Staff human only, lest some jackass decide to go "Law 2, kill the captain" before NT Default or some other law addressing that can be uploaded.

**Comment by Probe1** [comment]
@icantthinkofanameritenow Coincidentally both rounds they were in live there was as antag chosen from one of the three traders.  The first round was restarted immediately as we scrambled to try and fix  the bad database tables but in the second round, the vox trader antagonist faced no insurmountable difficulty.  It grabbed a jetpack, went to the station, emagged in and stole to its hearts content.

I think you do raise good points here but we rarely get new jobs and finding a place for a new and unique job is difficult.  We've managed to find that here and it's a good enough idea (and implementation) that it can be improved by future coders like any other job.

**Comment by icantthinkofanameritenow** [comment]
@Probe1 
True. I guess I just operate on the mindset that any job added should have some way of making a direct and constant contribution to the station, if only a subtle one. Clowns and mimes I can understand since they're ostensibly around for keeping morale up and entertaining the crew, and assistants do in fact assist people occasionally. Hell, even the IAA can sometimes be important when an admin decides that they want to use faxes for something. The trader though just feels...detached from the rest of the station. Over on the trading post, they're completely safe and secure from any sort of havoc that might be going on in the station proper and so are in no real danger from most of the hazards that can affect the crew (e.g. bombings, rogue AIs, antags looking to murderbone, etc.) They practically have to go out of their way to get themselves killed barring adminbus or the unlikely event of an antag among them deciding to turn on his own kind.

Plus, I don't see a reason why this kind of job should be species limited. If it's just to appease people who want the Vox gone outright, it's not going to have that effect, and it won't encourage that many people to play a different race since the novelty will end up wearing off eventually. Ultimately, the only difference between traders and assistants is where they spawn and what access they have.  And with no way of actually getting worth trading, they don't really have a reason to exist- how do you propose they raid vaults for their loot when said vaults are so far away their internals will run dry long before even getting close to one?

**Comment by Brolaire** [comment]
Other species limited jobs? Greys could get something related to understanding the anatomy ofother species as good as possible or alternatively trying to fix a crashed UFO. Dionae could get the objective to grow a super special plant that needs radiation and plasma and such. Humies could be EXOTIC GAME HUNTERS or zookeepers. These probably suck but I'm just saying there's ways of making every species unique.

**Comment by icantthinkofanameritenow** [comment]
@Brolaire 
The idea with greys could work, but there's not really anything that requires knowledge of anatomy at all in the game beyond which area to target for surgery. But I suppose it could be repurposed for a mode or event akin to the Abductors from TG. 

As for humans, I'll repeat my idea of limiting all Head positions to humans,  which would also avert the risk of them not being covered by Asimov laws at roundstart. The zookeeper idea in particular seems doomed to fail since the closest thing to a zoo on the station is the toxins testing range.

**Comment by Brolaire** [comment]
it would be a freerange zoo on the asteroid, clearly!

**Comment by icantthinkofanameritenow** [comment]
@Brolaire 
What, with no air? Or animals? Seriously, it would have to be a pretty small zoo. And again I can point out that I don't see the logic in arbitrarily restricting jobs to certain species. Why would only humans be able to have that job?

For heads being human-only, the argument is simple. Nanotrasen is (at least as far as we know) staffed by humans at its highest ranks, and they would prefer that any heads appointed would be of their own species as opposed to one of the other, less trustworthy species. Even now I still cannot understand why the crew doesn't valid a "trader" on sight; even if they demonstrate the ability to speak Galactic Common the fact that they aren't on the manifest is still going to create a massive cloud of suspicion over everything they do, no matter how trivial.

**Comment by ghost** [comment]
> He hasn't been on a safari ride through the brain of the taxiroid

**Comment by icantthinkofanameritenow** [comment]
@Skullyton 
Even the mobs on the roid aren't quite varied enough for a zoo. But if you want to add in a whole bunch of zoo animals, be my guest. I might do it, but my spriting ability can best be described as the stuff of nightmares.

**Comment by ihadtoregisterforthis** [comment]
Cows
Goats
Crabs
3 colors of bears
Corgis
Cats
Space carps
Xenomorphs 
2 varieties of chickens
4 kinds of monkeys
4 types of asteroid monsters
Mice
Cockroaches
BEES
Spiders
Bats
Borers
Skrites
And all the other stuff from xenobiology.

**Comment by Brolaire** [comment]
I thought alternatively besides that, hunters or zookeepers could also hunt more intelligent lifeforms, such as vox or greys or even humans.

**Comment by icantthinkofanameritenow** [comment]
All very good points, but it misses the most important one of all:

Why can only humans do it? At least the Vox had their paltry excuse of being a race of traders and so on.

**Comment by Intigracy** [comment]
Please remove traders from antagonist assassinate targets.

**Comment by Shadowmech88** [comment]
I agree, especially since they don't spawn with PDAs to pinpoint.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88
And since they don't show up on the manifest, they can't be tracked by suit sensors either. It's nigh-impossible to find them if they don't want to show up on the station proper.

**Pull request merged**
