### PR TITLE
Vox Raiders now start at the "Shoal" + Tiny Raiders QoL tweaks/fixes

### PR DESCRIPTION
**Pull request by gurfan**
Have you ever felt that the raider starting area was a bit bland? I did too.

## What this does

- Vox Raiders now have a home base similar to the way Nuclear Operatives have one.
- Fixed the skipjack being unable to dock at the trading port.
- Added a confirmation prompt when trying to send the skipjack back to home base (since doing so ends the raid and deletes all raiders from the mortal plane)

The shoal area is mapped into all main maps for now, but mappers can remap it any way they like. If the shoal area is missing from the main, the game will load in the old raider starting area.

https://user-images.githubusercontent.com/51427771/208565637-36bf4445-f0d4-479b-9c40-6ba6b303290d.mp4

## Why it's good
Fixes a bug, adds a helpful prompt, adds some FLAVOR to a very lackluster antagonist.

## Changelog

:cl:
 * rscadd: Added a starting area for Vox Raiders.
 * tweak: Added a confirmation prompt when trying to send the Vox Skipjack back to home base.
 * bugfix: Fixed the Vox Skipjack being unable to dock at the trading outpost. (Boxstation)

### CODE REVIEW

**Comment by gurfan** [comment]
dreamseeker_P7qs0O0Tu7

tweaked this part to look more like a real catwalk

**Comment by SECBATON-GRIFFON** [comment]
>multi z raider base on a non multi z map

oh god how will this work
looks awesome either way, railings were a really good addition

**Comment by gurfan** [comment]
This doesn't make use of real multi-z. The multi-z look was achieved by using effects that darken everything on the tile. All the greyed out areas are inaccessible.

**Comment by SECBATON-GRIFFON** [comment]
> This doesn't make use of real multi-z. The multi-z look was achieved by using effects that darken everything on the tile. All the greyed out areas are inaccessible.

you know you can hurdle rails right

**Comment by dinnerwoerror** [comment]
bro you weren't supposed to tell them that

**Comment by SECBATON-GRIFFON** [comment]
> bro you weren't supposed to tell them that

shame, they look nice. maybe put invisible walls on the fake multi z tiles next to them? density on that tile blocks doing it

**Comment by gurfan** [comment]
All the "multi-z" tiles are dense already.

**Comment by SECBATON-GRIFFON** [comment]
are the window grilles invulnerable too?

**Comment by Kurfursten** [comment]
Map confl

**Comment by gurfan** [comment]
I'm going to revisit this later as part of a larger and more polished PR. One day.

**Comment by SECBATON-GRIFFON** [comment]
i don't see why this was being premapped into maps instead of a map element

**Pull request closed without merging**
