### PR TITLE
Adds a Frankenstein Monster option to the staff of change

### PR DESCRIPTION
**Pull request by Arthurdentist**
https://www.youtube.com/watch?v=Np7CXhzVz70

I made a video to save writing a description.

### CODE REVIEW

**Comment by Imagebard** [comment]
Voxes have a different jumpsuit sprite. What happens if I have a Vox body but human arms/legs? I imagine the sprite will look awkward.

**Comment by Shadowmech88** [comment]
I don't think it's a big concern, considering it's a frankenstein monster.

**Comment by Arthurdentist** [comment]
you could test that out right now imagebard, you can make these abominations ingame already.

**Comment by Imagebard** [comment]
>you can make these abominations ingame already.

I'm going to guess that I'm supposed to go to your repo, download it, and adminspawn myself those.

**Comment by ComicIronic** [comment]
No, since #9669 you can do it on BE.

**Comment by Imagebard** [comment]
Oh so, tl;dr: if there is a problem with Vox sprites then its already in the server
In which case.

**Comment by ghost** [comment]
Imagebard if you're hit by a staff of change, you drop everything anyway.

**Pull request merged**
