### PR TITLE
Keycard gated loot vault

### PR DESCRIPTION
**Pull request by ghost**
[vault]
Another idea I've had for a while.
Comes in three difficulties: easy, normal and hard. Easy spawns 14x14 keycard locations and leads to a 3x3 loot vault, normal spawns 7x7s and leads to a 5x5, and hard spawns 1x1s and leads to a 7x7.
First worked in-game example of the portal turf.
## Entering a vault:
ooatpaaat
## Easy find:
image
## Easy vault interior:
image
## Normal find:
image
## Normal vault interior:
image
## Hard find:
image
## Hard vault interior:
image

:cl:
 * rscadd: A mysterious small room guarded by a door with keycard slots can now be found in space, with the keycards to gain entry scattered in other parts of space. They say it's bigger on the inside, and has a lot of valuable items...

### CODE REVIEW

**Comment by Optimism333** [comment]
Share screenshots of the maps, please

**Comment by xeroxemnas** [comment]
Was this inspired by Rust or something.

**Comment by ghost** [comment]
> Share screenshots of the maps, please

Done.

**Comment by Dacendeth** [comment]
Why does this add a dna box to traders?

**Comment by ghost** [comment]
> Why does this add a dna box to traders?

I can probably just varedit it into being a custom item on that vault

**Comment by Kurfursten** [comment]
You know I originally made an extremely sarcastic post, but the more I thought on it the more I thought that's not really the example I want to put out.

I don't think floating through space in a pod most of the round scouring for a card should warrant such overkill item rewards. Multiple wizard items, a deathsquad gun, 5 more guns for good measure, and a bunch of special TC-locked or otherwise super-rare items, really? This is the most loot pinata vault I've ever seen and it requires nothing but tedious floating. We have to stop the lavaland habit of making vaults only attractive for the purpose of acquiring guns to come back and validate the antag. This just happens to be the most egregious example I've ever seen.

**Comment by ghost** [comment]
> I don't think floating through space in a pod most of the round scouring for a card should warrant such overkill item rewards. Multiple wizard items, a deathsquad gun, 5 more guns for good measure, and a bunch of special TC-locked or otherwise super-rare items, really? This is the most loot pinata vault I've ever seen and it requires nothing but tedious floating. We have to stop the lavaland habit of making vaults only attractive for the purpose of acquiring guns to come back and validate the antag. This just happens to be the most egregious example I've ever seen.

Updated the description with images of the example vault find sizes. If those still aren't enough I can consider making keycards spawn other vaults themselves too.

**Comment by Kurfursten** [comment]
That does help in imagining how challenging finding keys would be, but I've yet to see a justification for why even finding 3 of the easiest should deserve a captain's laser. In terms of locating phazon and bananium, is it more interesting to locate the clown roid (another vault) and mine it out yourself before taking it home to refine... or to find whole sheets of it completely effortlessly in a medium keycard vault, plus some traitor gear to boot?

And hard is indeed hard, but why do we want to reward people who can find 3 lattices in space with a deathsquad pulse rifle as the cherry on top of a list of murder gear so egregiously long that if I were to list it out in every post, you'd probably think it was outright annoying.

* An infinite power cell
* A medical safe spawner (abstract type that doesn't work)
* One random upgrade for borgs (trader)
* Staff of Change (round gunking wizard gear)
* A medal
* A full flamethrower (gun)
* Cloaking cloak (wizard gear)
* Clothing spawner (includes HoS dermal patch, traitor chameleon outfit, laserproof armor, webbing, e-shield, emitter glasses, etc.)
* A double energy sword (16TC)
* Mateba (gun 2)
* Infinite cursed d20
* 10 phazon
* Random circuits (trader)
* A complete soul gem (cult)
* 5 random genetic powers (compare: rattlemebones vault gives 1)
* A deagle (gun 3)
* Pulse destroyer (gun 4, deathsquad)
* Random friendly mobs (trader)
* Random chems (trader)
* Safe spawner (includes anything on safe loot lists, so could be nanobots, creatine, portal gun, HoS patch, laserproof armor, a captain's spare, more guns, more genetic powers, etc.)
* Box of special beakers (trader)
* Vault food spawner
* Glue (traitor, 6TC)
* Vault weapon spawner (gun 5, could include combat shotgun, another deagle, saw, uzi, laser canon, etc.)
* Permanent invis spray  (traitor, 4TC)
* Emitter glasses (limited to safe loot/vendotron/spessmart)
* A pre-assembled nuke ops bomb (why?)
* 10 bananium
* Random materials (trader)
* An emag (traitor, 6TC)
* A crossbow (gun 6)
* A random mob in a cage

Bear in mind this isn't an OR list, it's an everything list. There's no theme here. You just drizzled in all the guns and bombs and trader and cult and wizard and traitor gear you could think of. There's no story being told by this vault, it's just a valid pinata.

**Comment by ConfusedCactus** [comment]
Have to say I agree with Kurf here. Way too much overpowered, round-gunking, or outright stupid loot. Needs to be dialed back about ten notches.

**Comment by gurfan** [comment]
this vault is hilarious for all the wrong reasons

**Comment by ghost** [comment]
> Have to say I agree with Kurf here. Way too much overpowered, round-gunking, or outright stupid loot. Needs to be dialed back about ten notches.

That I'd be willing to do, since I'm not very imaginative with it and left it to last for that reason.

**Comment by WindowsErrors** [comment]
gotta say, this is definitely a pull request submitted by kane-f

**Comment by ManopolisJones** [comment]
a doom style vault with keycards like this would be aces high, this however is not.

**Comment by Optimism333** [comment]
I think kurf makes a good point. The keycard concept and mechanic is neat in my opinion, but it'd be better with an actual setting built around it where you have to acquire the cards by completing different puzzles, or at least killing a few mobs.

**Comment by Kurfursten** [comment]
If it were me, I would probably try to make the vaults feel like something you find in space more than pinata rewards. Manopolis doesn't have a bad suggestion, you know a whole doom-themed area, but then again, maybe that's better suited to a small away mission?

Since you asked for suggestions, here's what I would probably do:

> Easy Vault Card Zone

Replace tiles with flashing docking lights, yellow stripes/concrete like the pod diner vault, and maybe a couple of mechanic-y things like a toolbox, hand crank charger, spare metal and rods, some empty powercells that have been discarded

> Easy Vault Reward Zone

A cramped space full of piled up pod parts and maintenance gear - pod cores, socket wrench, welding fuel tank, rods, pod armors, maybe even a podfab. The real prize is buried under all the junk - an infinite power cell. This is a great reward for the pod-themed difficulty because it means you can fly forever without cranking to recharge and it fits the theme.

> Medium Vault Card Zone

Replace all the lattices and such with those blue reflective turfs we put under solar panels. Make the whole thing look like a big radar dish/radar array. You could use some other things here like acoustic tiles for texture. You could make a "faraday cage" in the middle out of grilles. You can also add some nods to radar history with some scattered popcorn.

> Medium Vault Reward Zone

This is the space-radar operator's lair. Throw in some headset earmuffs, binoculars, security cameras (bonus if you make a special cameranet connected to the 3 card locations). The big reward is a custom computer that lists all of the vaults that were generated at roundstart + the Z-level they are on (no other coords). This is huge for a vault explorer, to know exactly which vaults to be on the lookout for and how many vaults they can find.

> Hard Vault Card Zone

Keep as-is

> Hard Vault Reward Zone

The final reward for trekking through space is a new home. It's a private bar with a 2-way portal you can open up leading to the main station. Make it comfy - don't skimp on the detailing. Behind the counter is an SCP-294 and a Superjuke. Any chem you want on demand is a fantastic reward. Take a nice sip of nanobots to relax from your space journey. Insist on having a gun? Instead of a deathsquad gun, how about a wacky 12-barrel shotgun to go with the bar theme, hanging over the counter on a wall mount? And of course any voyage through space gets lonely. Perhaps the bar comes with 2-3 adamantine slime cores so you can spawn yourself some golem customers/waiters.

**Comment by ghost** [comment]
Will take rework into suggestion in a new PR using code from this, thanks.

**Pull request closed without merging**
