### PR TITLE
Adds More Job Slots to Roidstation

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[roid]

Title.

Adds a ton more job slots to Roid. Assistants across the station, Engineers in Engineering, etc. Most of the specialized jobs now have a few different locations where they could spawn as well, mostly in their backroom/bedroom if they have one.

There is a spawn for the Detective in the bar.

:cl:
 * rscadd: Roidstation has been allotted a larger crew component and more job openings have allowed extra Assistants, Engineers, Scientists, and Security Officers to sign up.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Sure, but you need to exit the Roid DM file. Look at Deff's to see how it does it with 2 janitors

**Comment by Sooose** [comment]
Add more AI spawns please, can't triple AI currently.

**Comment by jknpj** [comment]
pls

**Comment by GeneralVeers25** [comment]
Fuck silicons

**Pull request closed without merging**
