### PR TITLE
Revert "Possible workaround for scrollbar bug that only randomly affects admins"

### PR DESCRIPTION
**Pull request by DamianX**
It doesn't work.

Reverts vgstation-coders/vgstation13#23400

### CODE REVIEW

**Comment by PJB3005** [comment]
Just replace stat panels with browsers. It'd probably fix it and will undo the massive performance issues too.

**Comment by DamianX** [comment]
I'm starting to think it's not that stat panel but the sheer amount of verbs being sent

**Comment by PJB3005** [comment]
Move all the admin verbs nobody ever uses into a separate panel then. It'll reduce right click lag for regular players too.

**Comment by Exxion** [comment]
The bug is definitely with the statpanel
It's not that it fails to create a scrollbar, it's that for some reason it thinks the displayed area is way longer than it actually is and it doesn't think it needs one
But if you get a very long statpanel when you have this bug, you will find that you have part of a scrollbar

EDIT: By the way I don't think it's specific to admins as I've had it on Alt+click menus, but since I am an admin it still might be

**Comment by PJB3005** [comment]
@Kurfursten you didn't merge #23400 into the secret repo so the code hasn't been compiling since that was merged, so DNM this because we haven't even tested that yet.

**Comment by DamianX** [comment]
Actually doesn't work.

**Comment by DamianX** [comment]
bump

**Comment by DamianX** [comment]
one day while andy was

**Comment by Probe1** [comment]
?

**Comment by DamianX** [comment]
just merge this already it's been 4 years

**Pull request merged**
