### PR TITLE
Removes darkmode message

### LINKED ISSUE #30877: [FEATURE QUEST][OVERSIGHT] Allow Admin Colors + "Set OOC Player Color" to be visible in dark mode
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
ad72739dcd508cdfa410fbfa724371f841a0e828

# Description
this seems like an oversight

### PR DESCRIPTION
**Pull request by adacovsk**
Removes darkmode message telling you to go to Github if you have an issue. I've been using darkmode for like two years without any issues.

Closes #30877

1. If you don't report the issue when it says to report the issue, what's the point?
2. If there is an issue, you can still report the issue without the message
3. Nothing else has a message saying "report the issue"

### CODE REVIEW

**Comment by Eneocho** [comment]
The issues are mainly colour problems, like how both gutter and insectoid are a dark brown in chat, which is hard to read on darkmode.

**Comment by adacovsk** [comment]
yeah but do we really need a message for that?

**Comment by godietxt80** [comment]
> yeah but do we really need a message for that? I don't see that as an issue, perfectly readable to me

works on my biological light receptacles
pointless dumb change for the sake of change

**Comment by wotisjanitor** [comment]
once every 5 times i play i have to restart because darkmode is broken

**Comment by adacovsk** [comment]
> once every 5 times i play i have to restart because darkmode is broken

did you ever report the issue? if not, the message doesn't work

**Comment by DamianX** [comment]
I will merge this if #30877, the only open issue about dark mode I could find, is fixed

**Pull request merged**
