### PR TITLE
Fixes the asset cache.

### LINKED ISSUE #5843: (WEB REPORT BY: xevonix REMOTE: 198.245.63.50:7777) Tile Painter Issue
http://puu.sh/knPFy/1333f218a7.jpg
I am unable to see any of the options on Tile Painters, unsure if it is just fucked this round or only for me. Figured I'd make an issue.

### PR DESCRIPTION
**Pull request by PJB3005**
This is how I'm gonna fix the asset cache issues.

Fixes #5843, and fixes most of #5853 (don't close that one yet I need to fix other stuff)

### CODE REVIEW

**Comment by clusterfack** [comment]
More like the runtime cache lmao

**Comment by PJB3005** [comment]
Did it ever runtime?

**Comment by clusterfack** [comment]
*Did it ever runtime*

Did it ever NOT runtime

**Comment by PJB3005** [comment]
I don't know if it did then tell me and I'll fix the runtimes.

**Comment by PJB3005** [comment]
Oh I found it, it's @N3X15' fault, the pipe layer adapter in the RPD is causing it.

**Pull request merged**
