### PR TITLE
Suit Slot Sprites

### PR DESCRIPTION
**Pull request by JMWTurner**
cultswords
- added sprites for cult blades stored in your suit slot.

engiback
- oxygen tanks (emergency ones too) now appear on your character when stored in your suit

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
> Suit Slots not holding the items _inside_ of your suit

:eggplant:

**Comment by JMWTurner** [comment]
Actually suit slot means the suit itself holds it, not necessarily inside. In fact the icon for the suit slot is a belt, and the dmi that contains the icons is belt_mirror.dmi

A few items are already visible when inside the suit slot, namely handcuffs.

**Comment by ghost** [comment]
They hold them outside the suit; if they held them inside the suit you wouldn't be able to take them out.

**Comment by NigglyWiggly** [comment]
No Celt, I didn't mean you held them inside the suit itself.
I mean the suit _slot_

Making oxygen tanks and stuff appear over the rigs also defeats the whole "Dead Space style health display" on the back. It looks silly and removes the sleek look of it

**Comment by JMWTurner** [comment]
Then just wear a jetpack on your back and breath your oxygen from it. But you still won't see the "Dead Space style health display". Nor will you when you're wearing a backpack.

I'm not changing the hardsuit sprite you know.

Should I have used the captain's armor to make my point?

**Comment by NigglyWiggly** [comment]
Wearing a jetpack would do fuckall, what are you even talking about?

I never said you were changing any of the sprites, but making the suit slot hold items on you like the back slot does is stupid.

**Comment by NigglyWiggly** [comment]
But why

**Comment by chaoko99** [comment]
Hrm. I like these... Might port these elsewhere.

**Pull request merged**
