### PR TITLE
SPS Alerts+Noise Tweaks

### PR DESCRIPTION
**Pull request by gurfan**
Adresses #28494 

SPS Alerts have been tweaked, here are the changes:

- The Security Alerts computer no longer states the triggered SPS out loud (though it still makes a boop noise), so putting a radio next to it won't be helpful anymore.
- SPS Units will now beep and show a small message in chat when an SPS is triggered, but there won't be any additional information shown to the user.
- SPS's now make combine sounds again.

The goal of this PR was to bring back the old panic from hearing the SPS go off that people talked about in #28494, but without completely reverting to the old SPS.

:cl:
 * tweak: The Security Alerts Computer no longer announces when an SPS is triggered
 * tweak: Individual SPS units will again play a noise to the wearer when an SPS is triggered, but there won't be any additional information.
 * tweak: SPS units use the old combine sounds again.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
Instead of it having no chat message and just making a boop, perhaps it *could* have a chat message? Just have it say something about an SPS going off, just not who.

**Comment by gurfan** [comment]
There is a chat message, I forgot to mention that. There is a "[sps] beeps loudly!" in bold red text.

**Comment by SonixApache** [comment]
:+1: to making the SAC not speak anymore. HOWEVER, you should make the [new alert] sprite a lot more visible.
:-1: to making the SPS beep other SPSes again. One of the primary purposes of the SAC was to avoid that.
:-1: to the curse of celt bringing back the loud and out-of-place combine noises

See also: #26555, #26677

**Comment by toomykins** [comment]
shoulda divided the computer thing into a different PR, imo.

**Comment by ghost** [comment]
>tweak: Individual SPS units will again play a noise to the wearer when an SPS is triggered, but there won't be any additional information.

This is awful and antithetical to the purpose of the SAC. I would recommend making it a separate PR as it seems to have very different reception from the other two changes.

**Comment by gurfan** [comment]
splitting into seperate PRs

**Pull request closed without merging**
