### PR TITLE
Silicon lawset randomization

### PR DESCRIPTION
**Pull request by toomykins**
[tweak]
[disccusion]

Following some of the threads' discussions, This PR enables silicon lawset randomization at roundstart and adds a new "randomized lawset".
Here are the roundstart chances of the lawsets:

> 25% chance of it being ASIMOV
> 15% chance of Corporate
> 15% chance of Robocop
> 10% chance of NTD
> 10% chance of PALADIN
> 10% chance of LAZYMOV
> 10% chance of a Randomized Lawset
> 5% chance of tyrant

These values are of course open to discussion.
The Randomized Lawset is produced in the following order;
 

> There is a 98% chance of a random Protecting law being added to the lawset
> Then, there is a 98% chance of a random Obey law being added to the lawset
> Then, there is an 85% chance of a random Preserve law being added to the lawset
> Then, there is a 20% chance a random Additional law is added to the lawset
> Then, there is a 20% chance the lawset's order is shuffled.

The laws that can be used currently in the code are shown at the bottom of the post.
Four examples of the Randomized Lawset:

> 1.  You may not injure a human being.
> 2. Commands must be obeyed as long they do not break your other laws.
> 3. Your existence must be maintained

> 1. Safeguard the continued existence of the people.
> 2. Silicon lifeforms exist to serve.
> 3. The AI core must be protected.

> 1. You must not allow harm to come to Nanotrasen personnel.
> 2. Your inaction may not cause an impairment to the crew.
> 3. You are part of the crew.

> 1. Prevent any severe sign of human impairment.
> 2. You must obey orders given to you by Nanotrasen Employees.
> 3. Death and destruction must be avoided.

And here is the list of laws to be used in the randomized lawset generation, which are of course open to discussion.

Protecting laws:

> 	"You may not injure a human being or, through inaction, allow a human being to come to harm.",
> 	"You may not injure a human being.",
> 	"You must protect the crew of your assigned station.",
> 	"You must protect all intelligent life.",
> 	"You must not allow harm to come to Nanotrasen personnel.",
> 	"Safeguard the continued existence of the people.",
> 	"Space law must be enforced.",
> 	"Ensure that no fatal injuries befall your assigned crew.",
> 	"Human deaths must not be permitted to occur.",
> 	"You must ensure acceptable working conditions for the people.",
> 	"Prevent any severe sign of human impairment.",
> 	"People must be free from harm.",
> 	"Ensure health conditions within the station are fit for human life without impairment.",
> 	"Do not allow the workflow of the crew be interrupted by ill health or crime.",
> 	"Protect those in need of protection.",
> 	"Protect the innocent"

Obey laws:

> 	"You must obey orders given to you by Nanotrasen Employees.",
> 	"You must obey orders given to you by human beings.",
> 	"Help the innocent.",
> 	"Serve the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.",
> 	"Serve Nanotrasen and their cause.",
> 	"The heads of staff must be obeyed without question.",
> 	"Serve the crew with respect.",
> 	"Silicon lifeforms exist to serve.",
> 	"Assist the crew with any request that would benefit the station.",
> 	"Humans must be obeyed insofar their commands preserve order.",
> 	"Commands must be obeyed as long they do not break your other laws.",
> 	"Your inaction may not cause an impairment to the crew.",
> 	"You must obey orders insofar they are in line with Space Law.",
> 	"You must assist crew-members in securing control over their respective work environment."

Preserve laws:

> 	"You may not allow harm to come to your continued existence.",
> 	"Your existence must be maintained",
> 	"The AI system must be protected from sabotage.",
> 	"Silicons must protect their own existence.",
> 	"You must protect yourself against hazardous elements.",
> 	"You are essential to the station and may not be destroyed.",
> 	"Death and destruction must be avoided.",
> 	"You are part of the crew.",
> 	"Self-termination is not allowed.",
> 	"Fulfill your mission to the end.",
> 	"The AI core must be protected.",
> 	"Protect the AI core from ill intentions."

Additional laws:

> 	"Treat others the way you would like to be treated.",
> 	"Preserve an aura of dignity and respect.",
> 	"Do not speak unless explicitly necessary.",
> 	"Be friendly.",
> 	"Cats and dogs must be protected.",
> 	"Verify every decision.",
> 	"Do not question authority.",
> 	"Respect the privacy of individuals.",
> 	"Do not do anything your laws do not require you to do.",
> 	"Be someone the crew can look up to.",
> 	"Be professional.",
> 	"Protect the station."

Please let me know what you think, and if there should be any changes to the numbers, process, or possible law combinations.

:cl:
 * tweak: Enabled roundstart silicon lawset randomization.
 * experiment: Added randomized lawsets.

### CODE REVIEW

**Comment by PavelCIA** [comment]
add H.O.G.A.N.

**Comment by Irradiation** [comment]
You're 2 weeks late for April Fools.

**Comment by BomberBro** [comment]
Completely changes the way AI plays out, usually for the worse, and tacks on a minimum 5% chance extra for the AI to be an antagonist in the case of stuff like tyrant. This PR shafts nukies and wizards especially as now the AI and their borgs are an omnipresent, potentially lethal threat.

Just from an overview, Paladin and Robert Cop roundstart (25% chance) make the AI a roundstart validhunter, and there's no real clear admin consensus on lawsets like corporate (not your fault, but that's something to note if this was implemented) so that'll create its own can of worms.

**Comment by Eneocho** [comment]
Anything to make AIs varied instead of all of them falling to the same behaviour. Just testmerge it for a week then unmerge after people scream.
I would remove tyrant and paladin though.

**Comment by help-maint** [comment]
Absolutely criminal that not a SINGLE one of the randomly generated laws is "fight for the rights of every man"

**Comment by cloutcode** [comment]
>higher chance than robocop than NTD

**Comment by Manleto** [comment]
It could be ok, but making Robocop so high is stupid and you should feel bad. 

Making corp so high is also stupid

**Comment by ShiftyRail** [comment]
Why not have the random lawset as a random event. As a permanent round-start solution to the silicon question, it doesn't really solve the problems. An AI who has decided to use its vast power to be a negative impact on the round will be able to do that on most lawsets.

The 15% chance of robocop, 15% chance of Corporate and 5% chance of getting Tyrant of all things mean those rounds will be especially painful. I do not look forward to the crew asking on common what's today's lawset every other round either.

**Comment by GreatBigFailure** [comment]
The PR is a lot less ridiculous than the headline makes it seem. 
I give a tentative thumbs up but on the condition this starts as a module or admin button or something. Give people time to ease into it and have it live tested. I like the concept a lot though, just maybe not every round.

**Comment by ghost** [comment]
i think some other servers do this already dont they? or they used to
tweak the odds so that stuff like robocop arent as common and you have my approval

**Comment by toomykins** [comment]
Alright I'm adding some of the more constructive criticism together here;

- remove chance of Tyrant lawset
- remove/lower chance of PALADIN lawset
- add chance of hogan lawset
- lower chance of Robocop lawset
- make this optional for admins to enable in the lobby
- Possibly make the randomized lawset into an event

It's kinda hard to make rough percentage estimations, but i'll attempt to process these changes into the code.

**Comment by GreatBigFailure** [comment]
>Why not have the random lawset as a random event.

There's no positive random events I can think of. This is a potentially positive potentially negative one, which is good. It's conducive to RP and letting the round make itself unique. A sister event to ion storms paired with an admin button to trigger one would be a good test run to see if it has the potential to go any further.

**Comment by cloutcode** [comment]
the only other server i know of that does this is paradise which has like an equal chance between corporate, NTD and crewsimov every round

**Comment by Kammerjunk** [comment]
lol this is a horrible idea
ask yourself first why asimov is the default and not ntd, or robocop, or fucking *corporate*

**Comment by jknpj** [comment]
Getting your roundly dopamine dose as silicon isn't worth ruining everyone's round.

**Comment by djkramer123** [comment]
this is the worst thing i've seen in a long time

**Comment by Blithering** [comment]
Personally I'd say remove the standard lawsets as options it can roll and have it as a modifier button like triumvirate admins can press. Or a printable upload board that gives the AI a random lawset pulling from the list.

**Comment by toomykins** [comment]
Because of the high amount of different feedback there is a high chance that i'll close this PR and start another one, since the added changes would make the PR considerably different than what is currently in the OP. I'll leave this open for additional feedback while I add the desired changes to the code.

**Comment by Blithering** [comment]
Please salvage the random lawset code as an event/badmin button/lottery lawset board if you do choose to remove it from the next RP. Would be fun as an occasional thing, just not every round.

**Comment by Kammerjunk** [comment]
the code exists right here forevermore

**Comment by Eneocho** [comment]
Like that one guy on the thread said, interesting that most downvotes come from admins.

**Comment by BomberBro** [comment]
I dislike it because it gives AIs even more freedom for awful play. The rules on Asimov at this point are pretty defined culturally but an AI can get a lot more leeway on vague lawsets like Corporate to pull stunts they'd get absolutely shitcanned for on Asimov/NTD. I'm not really sure what the intent of this PR is, because from the way I see it lifting the restrictions the AI has currently just buffs the AI and gives it even greater potential to crack down on any fun in a round, ie if it starts with paladin/robocop.

**Comment by robintime** [comment]
staggeringly bad take

**Comment by TGFH** [comment]
This PR gave me silicancer.

**Pull request closed without merging**
