### PR TITLE
Removes posibrain law/rule

### PR DESCRIPTION
**Pull request by MadmanMartian**
Addressed #20637 #11896
The boring way of approaching this
This removes the law/rule they have

### CODE REVIEW

**Comment by aceedex** [comment]
Dont do this
I assume the other PR doesnt adress things like a posibrain mech opening a blasma airlock

**Comment by MadmanMartian** [comment]
The other PR would require yet more mecha reworks

**Comment by SGuivenne** [comment]
Its a simple and elegant solution.  What more do you people want?

**Comment by strawberrytan** [comment]
I don't want posibrain mechs hunting crew down, they are not part of the crew (and in my opinion shouldn't even care about valids) and they can provide plenty of utility without being a new valid hunter

**Comment by Pathid** [comment]
Yeah that must be what it comes down to, and what the original reason for the directive was. It's the possibility that a non-antag could raise an army of unsubvertable non-antag posimechs that hunt the antags that may have killed the players in the posis in the first place. It's a quasi manifest ghost for the crew. Ever thought about why adamantine golems can't use guns? Or why diona adults are so slow and flammable? Or why methylin doesn't work on diona nymphs?

**Pull request closed without merging**
