### PR TITLE
Adds a very topical and surely funny reference aka meme

### PR DESCRIPTION
**Pull request by 9600bauds**
Casimir Skeletor cries, "why would I take a pin pointer?"

### CODE REVIEW

**Comment by Intigracy** [comment]
could you misspell something so it fits the recurring theme of actual retardation

as-is it could be confused for a legitimate statement

**Comment by kol1th** [comment]
I love you

**Comment by 9600bauds** [comment]
Some of the brain damage messages are grammatically correct too, such as "Don't tell Chase" and "not so tough now huh"

I'm torn between trying to decide what would be funnier, make it retarded or keep it true to the original quote (which is hilariously retarded on its own)

**Comment by kol1th** [comment]
The original quote was
>why would i take a pin pointer??

**Comment by Intigracy** [comment]
Nice.

**Pull request merged**
