### PR TITLE
Adds Buckle In & Buckle Out verbs for beds, chairs and vehicles

### PR DESCRIPTION
**Pull request by ghost**
[qol] [tested]
Mostly intended for buckling out of shuttle's chair with your hands full without robusting yourself.
Tested with beds, rollerbeds, chairs and snowmobiles.
Vehicle verbs work by removing bed's verbs, looks wonky to me, do tell if there's a better way around that.
:cl:
 * rscadd: Added "Buckle In" & "Buckle Out" verbs for beds, chairs and vehicles.

### CODE REVIEW

**Comment by Exxion** [comment]
You can click the screen alarm to unbuckle

**Comment by aceedex** [comment]
I'm very wary about the eternal v*rb but that's more up to the maintainers

**Comment by ghost** [comment]
> 
> 
> You can click the screen alarm to unbuckle

Shuttle chairs have special behavior that when clicked they instead hit who's hitting. Including the alarm.
But really I wanted to do this 'cause some anon asked like a month ago and I wanted to do something.


> 
> 
> I'm very wary about the eternal v*rb but that's more up to the maintainers

Are verbs bad?

**Comment by Exxion** [comment]
>Shuttle chairs have to look *cool* so they put a massive fucking buckle over your sprite
>This keeps you from being able to easily click someone in one
>So they pass clicks on to the mob in them

I still don't understand what was wrong with the normal chairs and why we had to make these atrocities instead

**Comment by SonixApache** [comment]
@Exxion it was content and therefor inherently good

**Comment by aceedex** [comment]
My memory is hazy but if I recall there was a verb purge a few years back to reduce on the lag. Again if the maintainers have an issue with it they should says so, so don't mind me

**Comment by Exxion** [comment]
*Hiding* verbs causes lag for some unknowable reason, so adminverbs are the ones with that problem
Other verbs are just frowned upon because the verb system itself is shit

**Comment by RealestEstate** [comment]
verbs are nice in that they can be macro'd

**Comment by ghost** [comment]
if the issue is snowflake chairs why not just remove the snowflake shit

**Comment by Dacendeth** [comment]
Did you test being handcuffed to a chair and using these verbs?

**Comment by tuypo1** [comment]
You can also press the resist button to unbuckle

**Comment by ShiftyRail** [comment]
Don't like verbs

**Comment by aceedex** [comment]
not verbist just dont 'ike em

**Review by ShiftyRail — COMMENTED** [review]
Sorry for the late review.
I'm not sure if you really need to add and abstract to the `verbs` list, since your procs already use the `verb` keyword.

**Comment by Exxion** [comment]
You definitely have to if you don't want them to always be there.

**Comment by ShiftyRail** [comment]
Fine then

**Pull request merged**
