### PR TITLE
You no longer have to wait for a door to be completely open to go through it

### PR DESCRIPTION
**Pull request by MadmanMartian**
:cl:
 * tweak: After a review of the company guidelines. NT personnel no longer have to patiently wait for a door to be fully open to begin going through it.

### CODE REVIEW

**Comment by SonixApache** [comment]
How fast can you go through? the moment you touch it?

**Comment by MadmanMartian** [comment]
Yes

**Comment by MadmanMartian** [comment]
There is still a small pause that can't be avoided (As it checks internal things such as use_power()) but it's as soon as the animation of the door opening starts playing

**Comment by Exxion** [comment]
But what about the firebird?

**Comment by MadmanMartian** [comment]
good question. What about the firebird?

(What the fuck is a firebird?)

**Comment by Shadowmech88** [comment]
Does this let you go through the door immediately, as soon as you bump into it? I feel like that would look strange.
A shorter wait time, sure, but I don't think letting people just phase through doors is a good solution.

**Comment by SonixApache** [comment]
Bit over the top to basically make people phase through airlocks. How about just dividing the animation delay by 2, so you can go through it when it's (theoretically) half-open?

Firebird is the wizard car that passes through airlocks without delay.

**Comment by MadmanMartian** [comment]
so it seems that the wizmobile does its own thing, where it just phases through the door and plays the door animation, but never sets some things properly so it may potentially brick in the future. I'll try the half sleep now

**Comment by gbasood** [comment]
What about:
 - opacity of doors before they're fully opened
 - airlock airflow before they're fully opened

**Comment by Exxion** [comment]
This is a pretty major buff to people being chased, since they had to wait for the door to open but the one chasing them didn't

**Comment by MadmanMartian** [comment]
@gbasood 
- the opacity was already being set before they were fully opened anyway, and oddly enough set AGAIN after they were fully opened, a seemingly useless call.
- airlock airflow is marked for update after the sleep in the update_nearby_tiles call

**Comment by Riekland** [comment]
but faceplanting into a door and getting shot while it slowly opens after you've already touched it is the funniest thing

if I could suggest just making doors without access open instantly to simulate them opening before you touch them since you don't have to scan an id or something for them

**Comment by ghost** [comment]
Not immediately after you touch them, but once they're half open would be good.
Alternatively add another airlock type that starts opening once you're 2 tiles away from it and put them on the corridors.

**Comment by Shadowmech88** [comment]
>open instantly to simulate them opening before you touch them

It would actually be possible to have them automatically open whenever someone came within two tiles of them.

**Comment by Hoshi-chan** [comment]
Is it April 1st already??

**Comment by SonixApache** [comment]
post webm

**Comment by Reviire** [comment]
This is pretty bad, I think. Not only would it look absolutely stupid, it's a pretty big gameplay change, especially with how much running away people do. Airlocks cease being a concern in where you run. It's probably a nerf to AI gameplay since you don't have the small delay to get ready to crush, and for opaque airlocks people are just going to run through, with no warning to the person on the other side.

**Comment by DamianX** [comment]
ITT: no one saw it in action

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
TG does it, that's where I've seen it in action

**Comment by Intigracy** [comment]
In case you missed it, it was changed to the suggested halving of the animation speed.

**Comment by Shadowmech88** [comment]
I think a WebM would still be nice.

**Comment by Fruktlimpa** [comment]
@DamianX "ITT: No one saw it in action"
No shit, there is no webm or anything displaying how it looks.

**Comment by Accipitermaris** [comment]
When people criticize our movement system they usually say something like “make airlocks open faster, but slow down run speed” (although it might be just me who thinks that)
I kinda wanna see this in action because of that as it does half of that

Edit: what if you could dive through glass airlocks but not opaque ones

**Comment by SonixApache** [comment]
my compromise joke when I was thinking about doing this was "make it so you can go through instantly, but at half speed, so it would take you just as long to go through the door as if you were waiting for it to completely open"

still waiting for that .webm

**Comment by DamianX** [comment]
I don't see this going anywhere, partly because of the retarded emojicracy that gives us no way to know if people actually dislike it with the second commit.
As someone who would like to see (something like) this merged, I think it would be best to open a new PR, possibly with an attached video.

**Pull request closed without merging**
