### PR TITLE
renames box to bawks

### PR DESCRIPTION
**Pull request by beesil**
:cl:
 * tweak: box station is now for chicken

### CODE REVIEW

**Comment by gurfan** [comment]
yeah sure

**Comment by ghost** [comment]
you are out of your mind
we cannot do this

**Comment by ShiftyRail** [comment]
No...

**Comment by toomykins** [comment]
\>chicken downboated this

**Comment by gurfan** [comment]
it's over...

**Comment by toomykins** [comment]
it's only just begun

**Comment by Stressedphysicist** [comment]
its happening

**Pull request merged**
