### PR TITLE
Tweaks to the map

### LINKED ISSUE #3540: There is no lightswitch for the kitchen.
The one in the bar only controls the bar's lights.

### LINKED ISSUE #3640: Bartender Lost his Sink [Box Station]
The new bartender backroom doesn't have a sink. Can't remember if he even had one before but he certainly needs one.

### PR DESCRIPTION
**Pull request by ghost**
- Add a lightswitch to the Kitchen
- Move the Bartender's lightswitch to his backroom
- Add a kitchen sink in the Bar counter area
- Modified Mech Bay area. It's now comprised of an big shutter "door" with a small one-tile electrified window on both sides. This makes it more of a "secure area for mechs to be stationed and maintained" area and less of a "muh clay" area. There's currently no outside access, you need to pass through R&D and Robotics to get in here (unless the shutters are open). Maintenance works, too

Fixes #3640
Fixes #3540

Screenshot of new Mech Bay area : 

new_mechbay

### CODE REVIEW

**Comment by ComicIronic** [comment]
I do not like that new mech bay.

**Comment by dylanstrategie** [comment]
The main idea is to have something that is more open and looks more like somewhere to store Mechs in, without removing the secure aspect of it nor impeding the Roboticist too much

In case you want to go through here, literally nothing forbids you from opening the Mech Bay shutters and keeping them open, and Cyborgs can access it freely by simply hitting the button, as they can see it through the window

**Comment by dylanstrategie** [comment]
Then again, if the no outside access thing is a doorstopper, I can simply add one on the outside, though if I do so it'll obviously need Robotics access to be used (unlike the one on the inside)

**Comment by PJB3005** [comment]
the issue being that electrified grills don't stop anybody who's semi robust, so then can get into science really easily now

**Comment by SarahJohnson489** [comment]
Mech bay was fine as is. Unless there's a hard check like dna locks you accomplish fuckall thanks to the countless alternatives. People are still going to get in. But even if they do get in it doesn't matter because only a moron doesn't dna lock the mechs then 10-beacon any before he unlocks and hands it off to someone that can be trusted to not grief. If your goal is a more secure mech bay it fails as there's still numerous ways in that a vast majority of the crew will have and without adding an external button it has to be left open. If there is one it still necessitates the pilot getting access then getting out, open, in, out, close then back in to wait while it charge then repeat again on the way out. Guess what wont happen. So the security minded will just make sure they have main and go through the maint airlock and the lazy will leave the shutters open. Accomplishing no benefit.

This comes across as a senseless change for the sake of change rather than a solid benefit

From a personal point of view, I don't like windows allowing anyone to see inside whenever they want when they pass by. At least as-is I can keep the shutters closed without 15 assfaggots wandering up and crawling all over thinking they can just get in then go off to griff

**Comment by dylanstrategie** [comment]
I will be adding an external access button with an access lock

**Comment by SarahJohnson489** [comment]
I am totally cool with people not being tempted to break through the glass to try and get in the mechs.

**Comment by dylanstrategie** [comment]
Newest layout : 
new_mechbay

- Added outside access, restricted to Robotics unlike inside access (so that in the unlikely event where someone without access has the shutters closed on them, they can get out)
- Tweaked Maintenance on the left of the Mech Bay to have functional access for Roboticist (with the door into Mech Bay exclusive to them). For those who REALLY don't want to be tailgated

**Comment by DrCelt** [comment]
>these floating buttons
thanks but no thanks

**Comment by d3athrow** [comment]
:-1:

**Comment by dylanstrategie** [comment]
Floating buttons ? Floating buttons getting moved to the walls, then

**Comment by d3athrow** [comment]
Solution that wouldn't make getting into robotics a pain in the ass and also make 'mech bay more prettyful'
multi tile airlocks instead of just shutters.
Reasoning: you cant open shutters from a mecha but can bump open airlocks.

**Comment by Senaat1** [comment]
I don't get why this is a positive change, all it does is remove a door and add some windows.

Why? Whyyyyyy?

**Comment by NigglyWiggly** [comment]
Yeah, really not a fan of the window buttons

**Comment by Senaat1** [comment]
Pomf, as far as i know the entire reasoning behind there being shutters and a regular door is so that Roboticists can open the shutters to let everyone in to recharge mechs, while the doors are so Roboticsts can enter with mechs without having to get out and open the shutters.

Your idea would mean only Roboticists could enter (unless they can drop/raise bolts from inside or something, in which case you might as well just use shutters) and in Dylan's situation either everyone can enter or Roboticists have to take a big detour through science and robotics to charge mechs.

**Comment by dylanstrategie** [comment]
The window buttons are being moved, I have a PR underway

The button system works this way, external button is restricted to Roboticist access, internal button is free to everyone

The Maintenance access can be used if you really want to get in and out without taking a finger out of your mech, it's been changed to allow Robotics access

**Comment by 9600bauds** [comment]
So to use the garage with a mech you have to go around maint now?...

**Comment by Senaat1** [comment]
Okay Dylan, but why not leave it as it is? Please, tell me what actually makes this a worthwhile change? It's easier to break in now because you can smash through two windows and an electrified grille with just an extinguisher whereas doors require actual tools, Roboticists have to go through fucking maint to get into the garage now (?????) and you made a door bigger even though even two tiles is more than you'd ever need.

**Comment by dylanstrategie** [comment]
This does not make the Mech Bay any less secure than it is now. Electrified grilles take time to get through and the determined attacker can just break in via the Robotics Desk

Roboticists only have to go through Maint if they don't want to dismount to open the shutters, this is used for people who want to get in fast and easily. If you want to enter through the front, take the time to get out and press the button

We all know Mechs only need one tile to transit, but if we debated on just having what is needed for everything we'd be playing Ministation right now

**Comment by Senaat1** [comment]
None of what you just said actually answered my question, it's just excuses why it doesn't change anything except make it so that Roboticists need to go out of their way to enter their own domain in a mech.

And even then, breaking in through the Robotics Desk still requires actual tools or a second person instead of just blunt weaponry.

**Comment by dylanstrategie** [comment]
- Moved the buttons from the window to the walls because floating in the air
- Add potted plants, everyone loves potted plants

**Comment by Boxe** [comment]
i dont like this

**Comment by dylanstrategie** [comment]
- You can now activate buttons in view (as long as you face them, for some reason, but it works) when inside a mechatronic
- It WILL check for proper access (yours) when doing so. The access denied message doesn't seem to show at range, but I don't know what's up with that

Literally open and close the Mech Bay without stepping out of your mech, living the thug life

**Comment by 9600bauds** [comment]
I've said it already, I'll say it again. I don't agree with this PR.
In effect, it just removes the front airlock from Robotics, and adds worse functionality (button-controlled shutter, a maint access) to try to replace it. Why?
Not only was the previous entrance of an airlock+shutters perfectly fine, it in fact worked better. Nobody would rather have to press one button to come in and one button to close the door, rather than just use an airlock that can easily be bumped into.
Worse still is that this is of no benefit to anybody, there was no need for the shutters to be three tiles wide, and there was no reason to remove the much more convenient airlock.
The maint access is also a terrible workaround. I'm again sorry to say, because I don't mean to just dismiss the effort you put into this PR, but it all makes as much sense as giving horse reins to your car.

**Comment by Probe1** [comment]
[17:54:36] <probe1> I think its a downgrade.  What I mentioned with unauthorized players can leave and close the door behind them thanks to button placement is now gone.  But that ties into roboticists too.  If they want to leave the most direct route they now have to leave their gate open for anyone to walk into.  With a door it will close.  With shutters it will not.

**Comment by CptWad** [comment]
:-1: 
Nobody benefits.
Having to get out of your mech to open the doors is a pain in the ass.
Current map if someone wants to break into robotics they do it at the window. Nobody breaks into mech bay. Unless they are already inside and want to break into robotics.
Electrified grilles on the windows is no necessary due to above reasons.
Two separate shutters are not necessary as they look atrocious.
If there are issues of people stealing mechs then either keep the shutters down (easy) or just keep the mech in robotics and ask the owner to pick it up (even easier). This method just encourages people to break in through the windows to get in there. The more difficult to get in the more likely greyshirts want in.

I can say more if anyone besides dylan wants this.

**Comment by Shaska-** [comment]
Not a huge fan of this, but with a button to open it up from the outside, I guess it would be okay.
Buttons on windows are terrible though. You should change the left window to an Rwall instead.

**Comment by SkowronX** [comment]
Robotics not broken in the first place. Don't change. :-1:

**Comment by saronsen** [comment]
FOR WHAT PURPOSE?

**Comment by dylanstrategie** [comment]
Here's the last iteration of the Mech Bay, because I didn't get around to updating it

wmmbebn

Mechas having to dismount has been completely solved, they literally don't have to anymore, so that's that

**Comment by VelardAmakar** [comment]
3-wide is a bad idea
if you're gonna do anything at all:

replace the center tile with a refwall and put 4 buttons on it

**Comment by dylanstrategie** [comment]
Then I'll put this up to consideration : Should I keep the three-wide shutter entrance, or should I splice it in the middle with a rwall ?

I would rather have one set of buttons in the middle for both shutters, unless it's important both doors are be opened separately

**Comment by CptWad** [comment]
Someone pointed out that that map is missing the body bags for robotics.

**Comment by ComicIronic** [comment]
That someone was also wrong.
The bodybags are just under the table. The issue was closed.

**Comment by dylanstrategie** [comment]
I might look into it real quick

**Comment by dylanstrategie** [comment]
For some really good reason, I suppose, the Roboticist's body bags had a layer of 2. This meant not only that they spawned under the table, but that they would always be under tables or really anything when laid down

I have fixed that, and gave the Roboticist space cleaner since Surgery is messy

**Comment by dylanstrategie** [comment]
Need a check on the Do Not Merge tag, at least

**Pull request closed without merging**
