### PR TITLE
adds an attack delay to blobs.

### LINKED ISSUE #21336: blob appears to have absolutely no attack cooldown
(WEB REPORT BY: whoru REMOTE: 206.221.180.138:7777)
it can just autoclick and make a borg instantly go from 300 health to gibbed
it also has no expansion cooldown so it can expand-sprint in a straight line across a room in 1 second

### PR DESCRIPTION
**Pull request by MadmanMartian**
Seemed odd that there was one lacking. Current delay is half a second.

closes #21336

### CODE REVIEW

**Comment by Kurfursten** [comment]
Please move the attackdelay below all the other return checks (e.g.: you won't get delayed half a second if you jump the gun right before your resources come in)

Partial solve of linked issue

**Comment by Sooose** [comment]
Honestly I think an attack delay is completely unnecessary and even harmful to the game mode. Blob already has to spend a lot of points to even attempt an attack in the first place and you're generally given very few opportunities to take advantage of it.

**Comment by Exxion** [comment]
Blob always used to have an attack delay (in effect) before newblob, and it was a lot better to fight back then
That said, I haven't tried fighting it since the costs were rebalanced, so if it's not as awful as it was before that then take this with a grain of salt

That said, a half second might be a *bit* long

**Comment by Kurfursten** [comment]
I do *feel* like Blob is in a pretty good spot (when it doesn't land on Roid's roid which is unfun for everyone involved). On the other hand see 21872 (linked above). There is a small cheese tactic where it actually is possible to place new blobs faster than emitters can destroy them which feels really bad when a blob is expanding *through* emitter fire which should never happen.

It needs a cooldown. Is 0.5 sec too much? Possibly. But it does need something, even if that's 0.1 sec.

**Comment by MadmanMartian** [comment]
@Kurfursten I'll put it below all but the buycost, so you don't waste resources if you didn't have the points

**Comment by Kurfursten** [comment]
Yeah, that's where I meant. 👌

**Comment by Killette2** [comment]
How do you even attack properly with blob? I thought no attack delay was to make up for expanding being unreliable. I've tried different hotkeys and it feels like you only expand when the game feels like it and you have to brute force it with groups

**Comment by Kurfursten** [comment]
ctrl click with 15 resources to expand

fails 75% of the time if expanding to space, otherwise never fails

**Comment by Killette2** [comment]
15 not 5? Did blob get nerfed?

**Comment by Kurfursten** [comment]
You should probably go read the full redesign

**Pull request merged**
