### PR TITLE
Academy hotfix

### PR DESCRIPTION
**Pull request by unid15**
Fixes *some* typepaths in Academy.dmm

### CODE REVIEW

**Comment by ghost** [comment]
will academy be given some unid funtimes?

**Comment by Probe1** [comment]
I meant to do this months ago but realized I didn't give a shit about it anymore because its so freaking old.  

Thanks Unid.

**Comment by unid15** [comment]
no actually this only fixes the screwup caused by #14522 (I skipped this file when replacing paths)

other typepaths are still broken :L^)

**Comment by ComicIronic** [comment]
>this history

**Comment by ghost** [comment]
???????

**Comment by ghost** [comment]
Oh, oh lawd

**Pull request closed without merging**
