### PR TITLE
Revert "Speak finnish randomly when brain damaged"

### PR DESCRIPTION
**Pull request by clusterfack**
Since removing memes is the word of the day obviously this should be removed

### CODE REVIEW

**Comment by kol1th** [comment]
my aunt is finnish you can't remove this

**Comment by Imagebard** [comment]
I once got turned into a statue, muted form IC, set on fire and turned into a tajaran for writing say ":DDDDD" since it was ruining other's people immersions

Clearly the administrative team has no problem with this. Might as well count in the number of admins we have as :+1: this.

**Comment by Probe1** [comment]
7am0bfa

**Comment by Intigracy** [comment]
I think just the one with emoticon :DDDD should be removed.

**Comment by SplergeBucket** [comment]
sparde

spurdo sparde

**Comment by Brolaire** [comment]
GONDOLA
W H E N
H
E
N

**Comment by clusterfack** [comment]
ITS GONE MATE

**Comment by PJB3005** [comment]
WOW SELF MERGE

**Comment by Intigracy** [comment]
But my aunt is finnish.

**Comment by Probe1** [comment]
:eggplant: :eggplant: :eggplant: :eggplant: :eggplant: Hold up :eggplant: :eggplant: :eggplant:  :eggplant:  :eggplant: 
:eggplant: :eggplant: :eggplant: No memes past this line :eggplant: :eggplant: :eggplant: 

When you get into the territory of trying to play games with PRs and in this case, add and remove memes as you see fit because you like or dislike them personally, everyone sees what you are doing and eventually (in this case instantly) people start playing games with you right back.

So cut the bullshit out.  If you want something added or removed ask people first, make an issue, talk to them in game, unless its wholly positive and is a no brainer to add then ask first.

**Comment by NigglyWiggly** [comment]
>Self Merged this
>Closed the other attempt to change it

REMOVE CLUSTER WHEN?

**Comment by clusterfack** [comment]
Don't make me merge your pr as well niggly

**Comment by clusterfack** [comment]
Because I will, I'm a madman

**Comment by Imagebard** [comment]
I see no problem
Screaming :DDDDD in say like you were typing in a electronic interface is something the moderation team legitimately doesn't like.

>Don't make me merge your pr as well niggly

Why don't you do it anyways?

**Pull request merged**
