### PR TITLE
Egg Station WIP DNM

### PR DESCRIPTION
**Pull request by AlphaBuffalo**
I think I figured out how to do PR properly. Thanks Ririchiyo for telling me GitHub for windows is a piece of crap and to use smart git

### CODE REVIEW

**Comment by Zth--** [comment]
Keep posting images!

**Comment by AlphaBuffalo** [comment]
I didnt really do much work today. I was trying to find out how to into github and pulling. Also baby sitting.

**Comment by AlphaBuffalo** [comment]
Also, for Autism Spider's comment about making the station run on a TEG R-ust combo, or a SMR

Im going to just do a simple TEG that should generate enough power to run the station, There is a shard room, and an AME. I will include a particle accelerator, but I will also include gyrotrons, and a fuel injector for the R-ust, the rest will be up to you guys.

**Comment by AlphaBuffalo** [comment]
station

1000 + hours in MS paint

**Comment by Zth--** [comment]
all those windows on the hallways...................... this cannot end well

**Comment by AlphaBuffalo** [comment]
Non-sense, if people know how to into shield generators, they should be able to protect from roids.

Carps on the other hand... idk I forgot they existed when I was planning the map out

**Comment by Zth--** [comment]
It's still too early to discuss something, but seems good :+1:

**Comment by AlphaBuffalo** [comment]
I I still got to add solar panels and stuff

**Comment by AlphaBuffalo** [comment]
station 11-20

**Comment by PJB3005** [comment]
Please avoid pipes that go through walls.

**Comment by FudgePucker** [comment]
I think that the windows surrounding the station is a great idea. All departments are connected by maint or the central hallway, meaning that firelocks would be enough, just add instructions to the heads desks about how to enable emergency maintanace access. It would mean that there is area to build in space new rooms that are general access that aren't excape airlocks or arrivals airlocks.

Not every good map needs to be box

**Comment by AlphaBuffalo** [comment]
@PJB3005 I won't allow any pipes to go through walls, including power cables, Im also making vent crawling better by not putting vents at the end of long pipe sections, at least in the main hallways

**Comment by clusterfack** [comment]
>Im also making vent crawling better by not putting vents at the end of long pipe sections


Speaking of that, where's my total rework of all the pipes @probe1

**Comment by AlphaBuffalo** [comment]
medbay 11-21-15

I need to learn how to change access to doors with the edit feature

**Comment by PJB3005** [comment]
That's quite a big medbay, sure all that space is needed?

**Comment by IratePirate** [comment]
>I need to learn how to change access to doors with the edit feature

Just look at the other maps. There should be a txt file with the various accesses noted down somewhere.

**Comment by PJB3005** [comment]
You're looking for [`access.dm`](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/jobs/access.dm).

**Comment by AlphaBuffalo** [comment]
I can fill that medbay with junk, its viro break room that's too big

**Comment by Exxion** [comment]
I have to salute the fuck out of you for working on such a big map so quickly
I tried to make a map once, but I gave up after ~3/4 of one room because Dream Maker is so obtuse

**Comment by AlphaBuffalo** [comment]
station 11-24-15

**Comment by IratePirate** [comment]
Why was this closed?

**Comment by PJB3005** [comment]
Inactive for too long I guess, tell me if you want it reopened.

**Pull request closed without merging**
