### PR TITLE
Box Trade Outpost Overhaul by Kurfurst

### PR DESCRIPTION
**Pull request by Probe1**
6515db96-6b79-11e6-8dde-7dc731a5477f

People liked this very much and the thread asked me to re-open it when I floated the idea of updating the tradepost.

I'm opening a PR now for feedback.  I plan on making additional commits tomorrow.  Notably, I believe it needs cycling airlocks like other stations.  As well, I'd like to give a good hard look at it and see if I can improve it in any small way.  I think the overall design is solid.

Link to original PR https://github.com/d3athrow/vgstation13/pull/11441

### CODE REVIEW

**Comment by Shadowmech88** [comment]
It looks awfully dark.

**Comment by despotate** [comment]
There do seem to be some floodlights in the storage room that can remedy the darkness.

I personally like the gloomy glowshroom aesthetic, not everything has to have 5 lights and cameras per square foot.

**Comment by Probe1** [comment]
Ya its pretty dark I'm gonna shift the glow shrooms so there's no dead spots.  I'm willing to give the low light thing a go.

I think the players will dislike it but I'm willing to try it.

**Comment by Lokiamis** [comment]
Darkness isn't a problem when everybody, especially folks on the asteroid, are running around with their flashlight(s) on at all times. Looks cool.

**Comment by jakmak5** [comment]
the white airlocks look kinda ugly. Other than that good change

**Comment by Blithering** [comment]
I like the glowshroom lighting, adds a low-budget vibe that fits vox rather well. Only problem I can forsee with it is the botany room might not have enough light to grow. Maybe replacing the white airlocks with glass ones would look better too. Also I'd like there to be a pacman generator or something to provide power, I know the asteroid is fuelled by magic space dust but there should be a theoretical source for the power.

**Comment by Shadowmech88** [comment]
The botany room could have lanterns hanging on the wall to provide extra light.

**Comment by Probe1** [comment]
I tried that and it makes it super bright.

**Comment by Kurfursten** [comment]
We talked about axing the oxygen trade floor and possibly adding an oxygen room for livestock/guests, but that may be more than you want to do right now.

It's probably worth mentioning that it's not quite as dark as that picture, I know I added at least one cluster of glowshrooms to the stock room. And of course, since the whole station is powered and you start with a box of lights, getting some brightness going isn't hard at all.

**Comment by Durgen** [comment]
I'm not a fan of the dirt floors or the lighting, but overall a vast improvement.

edit: maybe the safe can have extra Trader coins in it, now that those are a thing?

**Comment by Probe1** [comment]
It's a thing balanced around traders having one coin and I'm in no rush to mess with that WHILE trying to figure out what the vend should even have.

**Comment by Probe1** [comment]
FUCK I DELETED THE BRANCH WHILE CLEANING EVERYTHING OUT.

@9600bauds WAS RIGHT

NEVER DELETE YOUR BRANCHES

**Comment by 9600bauds** [comment]
use this system

**Comment by Kurfursten** [comment]
Are you going to need the dropbox link again or do you still have it?

**Comment by Probe1** [comment]
Oh I just restored the branch.

**Comment by Kurfursten** [comment]
>No opposition

Quick, someone merge this before it gets deleted again

**Comment by N3X15** [comment]
TIME TO DO SOMETHING WILDLY UNPOPULAR

**Comment by 9600bauds** [comment]
C H A N G E L O G

**Comment by Probe1** [comment]
It came true within 10 minutes!

**Pull request merged**
