### PR TITLE
adds radio usage to logs

### PR DESCRIPTION
**Pull request by SonixApache**
kammer asked me to do this 4 years ago

image
```
[01:39:50]SAY: Sonix Apache/SonixApache (@100,101,1) As Galactic Common :  : Lalala I'm speaking in person lalala.
[01:39:57]SAY: Sonix Apache/SonixApache (@100,101,1) As Galactic Common : (headset) : Everyone, listen to me speak! Listen to my words!
[01:40:07]SAY: Sonix Apache/SonixApache (@100,101,1) As Galactic Common : (Security) :  Security, even though I don't have a security radio, I'm yelling at you anyway!
[01:40:12]SAY: Sonix Apache/SonixApache (@97,105,1) As Galactic Common : (Command) :  AI, call it!
```

### CODE REVIEW

**Comment by SonixApache** [comment]
People are worried that this might spam the logs if used in conjunction with active-mic multi-channel SBRs, but rest assured: it only grabs the intended channel from the message, so only stuff like ; and :C gets caught.

**Comment by ghost** [comment]
this is honestly something we have needed for a long time and it's crazy it's only happening now. dogbless you for doing it and let's hope there's no way to abuse and flood the logs. 
Is there a way to make it clear if the message was actually broadcast over the radio or not?

**Comment by Kammerjunk** [comment]
this made me dig up my GitHub login again just to say based

**Comment by SonixApache** [comment]
@morenaaa no, radio stuff isn't logged, and there's a few situations where a message could be properly broadcasted over the radio while still not arriving at people. I could make something to log those too but that'll be in a separate PR.

**Pull request merged**
