### PR TITLE
Adds a delay before headbanging on a table

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Only 1% chance on April Fools to actually ever manage to climb a table, which still very likely results in broken skulls and permanent brain damage until you actually do it.

:cl:
 * rscadd: There is now a delay before banging your head on a table.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
repoban fucking when

**Comment by boy2mantwicethefam** [comment]
Sorry, I have made a mistake, let me fix it but I assure you that I tested it

**Comment by boy2mantwicethefam** [comment]
I have fixed it

**Comment by DrSnips** [comment]
Im pretty sure this a bugfix since we already had "table climbing".

**Comment by Kammerjunk** [comment]
it isn't

**Comment by DamianX** [comment]
We already have table climbing.

**Comment by boy2mantwicethefam** [comment]
Call it redundant code

**Comment by boy2mantwicethefam** [comment]
The PR turned into a feature PR and has been updated accordingly, please re-read

**Comment by boy2mantwicethefam** [comment]
Well it turns out keeping up with the joke has made people believe it adds table climbing properly

**Comment by boy2mantwicethefam** [comment]
I don't think this will gain enough upvotes

**Pull request closed without merging**
