### PR TITLE
Revert "Prevents godmode allowing organ and bone damage"

### PR DESCRIPTION
**Pull request by ShiftyRail**
Reverts vgstation-coders/vgstation13#32719

Soulless :(

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
god should fear leaving his throne
as shadow headmin I support this PR

**Comment by Exxion** [comment]
Damaging admins on the server is funny, but it's bad both for adminning and for debugging to have no option whatsoever to actually be invincible
If you really want hard-but-not-impossible-to-damage back, make another flag

**Comment by kilozombie** [comment]
There's something very cathartic about spawning in as a test dummy and watching all your bones shatter and face melt off while you walk around like nothing's happening

**Comment by Exxion** [comment]
You don't walk around like nothing's happening, though. You're frequently blinded and sometimes killed by whatever you were trying to investigate.

**Comment by Eneocho** [comment]
>You're frequently blinded and sometimes killed by whatever you were trying to investigate.

Good. Let them fear joining the mortals.

**Comment by kilozombie** [comment]
It's definitely bad for adminning but since I don't admin I can say whatever I want and face no consequences

**Comment by luigil101** [comment]
an ID plucked from an admin's corpse is the ultimate trophy
a shame they're so rare

**Comment by Eneocho** [comment]
> It's definitely bad for adminning but since I don't admin I can say whatever I want and face no consequences

If the admin manifested himself as a testdummy on the actual station during a regular round, thus fucking with said round's progression then he deserves getting oneshot by the CE's fuckyou railgun.

**Comment by Exxion** [comment]
>Good. Let them fear joining the mortals.

I didn't say anything about mortals. Have you heard of debugging?

**Comment by Eneocho** [comment]
> >Good. Let them fear joining the mortals.
> 
> I didn't say anything about mortals. Have you heard of debugging?

I have, to better debug you gotta experience shit like a regular player, so go blind and break the bones like a mortal spessman would.

**Comment by ShiftyRail** [comment]
Buddha mode it is

**Comment by Exxion** [comment]
>I have, to better debug you gotta experience shit like a regular player, so go blind and break the bones like a mortal spessman would.

Not that it matters at this point but I legitimately cannot tell if you're being serious here

**Comment by Eneocho** [comment]
> > I have, to better debug you gotta experience shit like a regular player, so go blind and break the bones like a mortal spessman would.
> 
> Not that it matters at this point but I legitimately cannot tell if you're being serious here

image

**Pull request closed without merging**
