### PR TITLE
SCP-294 tweaks and improvements

### PR DESCRIPTION
**Pull request by ghost**
[tweak][content]
Makes looking up names of chemicals to spawn not case sensitive anymore in checks, plus truncates spaces and/or converts them to underscores and also checks actual reagent names along with their ID.
As a bonus, these now support entering a mob's name to grab some reagents and blood out of them to make them more faithful to the original, as well as spawning a paper cup for the reagents if none is entered. (and allowing input with none inside to follow on this)

:cl:
 * rscadd: Strange coffee machines have improved their chemical seeking capabilities, being able to retrieve them from mobs and being less specific with names.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I will weaponize this

**Comment by Eneocho** [comment]
I will spend an entire round asking for cups of murderboner antag to remotely and stealthily kill 'em.

**Comment by Eneocho** [comment]
Cup of appropriate medical knowledge to link you to the surgery wiki when.

**Comment by calzilla1** [comment]
Does this mean you've given all ERT squads a slow acting Death Note?

**Comment by Kurfursten** [comment]
I support this so that accelerationism will finally give us the emojis we need to remove SCP from ERTs.

**Pull request merged**
