### PR TITLE
Replace buzzer sound coming from a door blocked from closing

### PR DESCRIPTION
**Pull request by ScrewdriverSurvivor**
Intention of this PR is to replace that distinct double buzzer sound that's most often heard while standing in a doorway and blocking a door from closing, among other things. **Read carefully: this won't change the access denied sound.**

This new sound retains the contextual idea of it's predecessor (two short buzzes), but it's shorter, a bit quieter, more pleasant to the ear.

The sound file was taken from [here](https://freesound.org/people/Jacco18/sounds/419023/). It's released into public domain under the terms of CC0, so no credit is required.

[sound][tweak]

:cl:
 * soundadd: Replaced double buzz sound with an alternative.

### CODE REVIEW

**Comment by brndd** [comment]
A recording of what this sounds like when someone's constantly buzzing a door in-game would probably be pertinent.

**Comment by ghost** [comment]
Can we please also generally make it so it can only trigger every few seconds on a specific door or such ? That would immensely help with the issue

**Comment by ScrewdriverSurvivor** [comment]
>A recording of what this sounds like when someone's constantly buzzing a door in-game would probably be pertinent.

> Can we please also generally make it so it can only trigger every few seconds on a specific door or such ? That would immensely help with the issue

I'm not sure I understand. This won't change the access denied buzzer that triggers while unable to open a closed door. This changes the loud buzzer that triggers when door can't close because someone's standing in the way. It doesn't play more often than a few seconds anyway.

**Comment by ghost** [comment]
Oh, fair

**Comment by brndd** [comment]
The old one has two tones, being a sort of a beep-boop sound, right? I'm not sure if this really conveys the same message. This really sounds like the door bumping one, being one tone played twice quickly.

**Comment by ghost** [comment]
What he said above. I'm a bit dumb but when I heard it my first thought was "ah, less grating than the current sound for someone constantly running into a door with wrong access, why not"

**Comment by ScrewdriverSurvivor** [comment]
Thanks for considering my PR. I'm closing it for now though. I see there's not enough popular demand for it and I don't see a reason for it to litter the PR list.

Maybe I'll revisit it in the future, with more suitable sound and proper examples with sound webms so people can better understand the idea behind it.

**Pull request closed without merging**
