### PR TITLE
Yet even more in-hand drink sprites

### PR DESCRIPTION
**Pull request by JMWTurner**
The crusade continues.

Cheers to all bartender players.

drink1
drink2

### CODE REVIEW

**Comment by SkowronX** [comment]
on a roll

**Comment by ScrambledSteak** [comment]
They look good fam, nice job

**Comment by clusterfack** [comment]
W e w

**Comment by NigglyWiggly** [comment]
> French people hold bottles by the bottom instead of the neck

_Interesting._

**Comment by JMWTurner** [comment]
Why french?

wineservice-2
server_wine

**Comment by NigglyWiggly** [comment]
Typically you don't casually hold a bottle by the bottom, at least not from what I've seen.
At least not on this side of the ocean :^)

**Comment by JMWTurner** [comment]
I guess we didn't have the same upbringing.

**Pull request merged**
