### PR TITLE
New xcom laser icons

### PR DESCRIPTION
**Pull request by Blithering**
Okay, take 2 at this and hopefully I'm not a years commits behind this time
New icons for the xcom laser rifle and pistol, printable from research
newguns

:cl:
 * rscadd: Changed the research printable laser rifle and laser pistol icons

### CODE REVIEW

**Comment by SonixApache** [comment]
icondiffbot says there's a rogue white pixel on the top left of the fully charged lasers, is this the case?

**Comment by Blithering** [comment]
I can't see it in the dmi, but I see what you mean, its posted in gif form in the spriting channel of the coder discord and doesn't show the pixel there either.

**Comment by agentofzog2** [comment]
Remove xcom sprite
replace with x-com sprite

**Comment by Blithering** [comment]
@agentofzog2 I have an idea for a way to add the x-com (or UFO: enemy unknown in bongistan) sprite, but it will be a separate PR to this one if I can get it working.

**Pull request merged**
