### PR TITLE
can repair grilles using rods, or whatever material the grille uses

### PR DESCRIPTION
**Pull request by nervere**
## What this does
You can now use rods on broken grilles to repair them.

## Why it's good
Having to break a grille first to repair it is tedious and nonsensical.

## Changelog

:cl:
 * rscadd: You can now repair broken grilles using rods, and clockwork grilles using replicant alloy.

### CODE REVIEW

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
So repairing them would consume more rods total than breaking and rebuilding?

**Comment by nervere** [comment]
No. When a grille is broken, it drops a rod. It takes one (1) rod to repair the grille. It is both faster and equally material efficient to repair instead of destroy and replace.

**Comment by falcon2346** [comment]
> No. When a grille is broken, it drops a rod. It takes one (1) rod to repair the grille. It is both faster and equally material efficient to repair instead of destroy and replace.

This isn't actually true. When you break a grille it leaves behind one rod and a broken grille. You can repair the broken grill using a single rod, or destroy the broken grille to get the second rod back. Using a rod to repair a grille before it gets broken (if I'm understanding this pr correctly) will give you a net negative of one rod, while destroying it is rod neutral. I would instead suggest having a tool be used to repair it.

https://github.com/vgstation-coders/vgstation13/assets/111808553/53340493-cbae-4caa-95ec-5d4a94d32380

**Comment by falcon2346** [comment]
Can't you already do this just by standing on the space of the grill and using it in hand?

**Comment by nervere** [comment]
> Can't you already do this just by standing on the space of the grill and using it in hand?

It would seem so! While I didn't know about this, it seems this feature is a flawed as it doesn't properly re-smooth the grilles once it's created, (see image). Due to changes I've made in this PR, this quirk will be fixed and it will properly re-smooth now.
Further, I think it's valuable to be able to click a grille to repair it rather than having to walk onto the tile and double click rods in hand.
image

**Pull request merged**
