### PR TITLE
Reagent lists

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds reagent ID list defines. Rather than duping recipes for the botany-alternative chems, just use one of the lists instead.

Covered chemistry-recipes and microwave recipes.

:cl:
 * tweak: Certain recipes can now use both the chemistry made reagent, or the botany acquired reagent versions

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
What happens if you electrolyze stuff?

**Comment by DamianX** [comment]
Runtimes would be my guess https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/reagents/machinery/electrolyzer.dm#L99

**Comment by MadmanMartian** [comment]
not anymore.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
So I guess this means you can make something with allicin and then electrolyze the result to transmute it into antitox

But let's be real:
Nobody will fucking care, ever

**Comment by MadmanMartian** [comment]
only if it can take both anti toxin or allicin.

Lore perspective: The electrolysis denatures the reagent, making it similar to the synthetic version

**Comment by jknpj** [comment]
missing a list with shitterjuice and beer2

**Comment by MadmanMartian** [comment]
??

**Comment by MadmanMartian** [comment]
oh, chloralhydrate and beer2.

I'd rather not make a list of those, as that would make a meta test for beer2.

**Pull request merged**
