### PR TITLE
Adds space_music to the lobby song list

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
https://opengameart.org/content/space-music-2
A bit large, compression would help. I'd ask R0B0 how but he's not here anymore 😢 
Thanks @PJB3005 for compressed audio file!

:cl:
 * soundadd: Added a new lobby song to the lobby.

### CODE REVIEW

**Comment by ghost** [comment]
Why is the file 3mb when the link you posted has a 1.7mb ogg download?

**Comment by boy2mantwicethefam** [comment]
I just don't know
I think it's because I took it straight from the audio folder

**Comment by boy2mantwicethefam** [comment]
Thanks @PJB3005 for compressed audio file!

**Comment by Kharkov72** [comment]
it'd make for some good variety for space ambience but not a lobby song

**Comment by boy2mantwicethefam** [comment]
I argue it's energetic enough to be a lobby song

**Comment by SonixApache** [comment]
how many times do we have to teach you this lesson old man

**Comment by boy2mantwicethefam** [comment]
Not enough support.

**Pull request closed without merging**
