### PR TITLE
Raincoat

### PR DESCRIPTION
**Pull request by Arthurdentist**
Adds a Raincoat you can buy for 1 TC from the syndicate uplink. 
hip to be square

Its Hip to be Square!

### CODE REVIEW

**Comment by DeityLink** [comment]
wrong pic?

**Comment by Probe1** [comment]
no, right picture.  it's a translucent raincoat to stop blood from getting on his clothing ala American Psycho.

**Comment by Arthurdentist** [comment]
Its in the category 'pointless badassary' for a reason. You can carry the fire axe in its suit storage, but that is all it does. The point being there isn't one, outside of looking hip.

**Comment by ComicIronic** [comment]
Fantastic, A+, :100:/:100:, :+1:.

**Comment by utilitas-** [comment]
How about a special traitor bundle that contains the raincoat, a business suit, a pill bottle with painkillers and a fire axe? A full Bateman kit.

**Comment by IratePirate** [comment]
Hey Paul!

**Comment by Senaat1** [comment]
We need more dumb stuff that doesn't serve any purpose but is fun anyway.

**Comment by IratePirate** [comment]
Make it so you can put it in your pocket after you've killed someone and got it covered in blood.

**Comment by d3athrow** [comment]
:+1: but make a Space American Psycho bundle.

**Pull request merged**
