### PR TITLE
Spell prices update

### PR DESCRIPTION
**Pull request by unid15**
I made a mistake when I made spells cost 5 points, because 5 is a huge number that is also a prime, so you can't make a spell with 50% of normal cost

* Changed base spell price to ~~2~~ 20 points. Purely visual change (spellbooks have 100 spell points, noclothes cost 40, etc)

* The following spells now cost 1 point (50% of normal spell price) to buy and upgrade: blind, forcewall, knock

:cl:
 * tweak: Changed base spell price once again, this time from 5 points to 20 points. This change is purely visual and doesn't affect number of spells that the wizard can purchase (the spellbook has 100 points, allowing you to buy 5 spells)
 * tweak: Forcewall minimum cooldown increased to 2 seconds (used to be 0)
 * experiment: The following spells now cost 10 points (50% of normal spell price) to both buy and upgrade: blind, forcewall, knock

### CODE REVIEW

**Comment by yclatious** [comment]
What could possibly go wrong?

**Comment by ghost** [comment]
>can get forcewall x5 and still have room for three more spells
Yes please

**Comment by Durgen** [comment]
why not set the default to 4 points
then there could be 3 point spells and 5 point spells

**Comment by Exxion** [comment]
Reducing it this low is just asking for it to be increased again later

**Comment by JustSumBody** [comment]
Make it 100 but every spell costs 20, or 50 but 10 in that case. Divisible by 4 is best since then you can have half and quarter cost spells IN MY OPINION, but until someone actually needs that quarter point or whatever 10 works.

**Comment by Exxion** [comment]
Let's make it so you get ONE spell point and all spells cost a fraction
That way we can have arbitrary precision
(I mean as arbitrary as the floating point format allows, which is pretty arbitrary that close to 0)

**Comment by unid15** [comment]
360 would rock because of its large amount of divisors, but I feel like some ~~casu~~people wouldn't be very fond of that, so I'll go with 100 which sounds pretty good

**Comment by ghost** [comment]
Nice . Forcewall's high cd, knocks high cd to door open ratio, and blind losing list target really left them in the dumps compared to other options

**Comment by TheFriggenSawbones** [comment]
THE WALL BECOMES STRONGER

**Comment by TheFriggenSawbones** [comment]
wait THE WALL BECOMES WEAKER OH NO

**Pull request merged**
