### PR TITLE
Atmos Traitor Item Tweaks

### PR DESCRIPTION
**Pull request by Kurfursten**
- Following feedback from community, lowered Contortionist's Jumpsuit from 7TC to 4
- Modified Flare Gun is now pickable by the CE as well

### CODE REVIEW

**Comment by Probe1** [comment]
~~the jumpsuit supposedly does not work.~~

**Comment by clusterfack** [comment]
What makes you say that

**Comment by Probe1** [comment]
Trusting shitty feedback in the thread without testing it myself.  It works fine.
 >items description isn't "The boss of this gym"

You're such a leatherhead Kurfurst

**Comment by clusterfack** [comment]
*trusting the thread*

**Comment by Kurfursten** [comment]
Yeah, I had heard some poster saying it didn't work, but I did testing to ensure it does.

**Comment by clusterfack** [comment]
I even made it so they have an object verb to crawl through vents so anyone would know how to use them

**Comment by FudgePucker** [comment]
What the hell is the point of the syndicate flare gun?
A: its just a desgised single shotgun. Woopie fuckin doo.
B: why the hell would an atmostech need a god damn flare gun? Its a giant fucking red flag saying "HEY EVERYBODY, I AM VALID, PLEASE FUCK MY FACE IN" yea, they need to have a flaregun to fight fires. Going into dark areas with an atmos tech id and atmos hardsuit is a great way to get spaced and have plasma flooded.

No one wanted my idea of camo pipes were they can look like one pipe but be another. Maybe be able to use a multitool to bring up a special menu to change settings and people who click on it just sees a false menu. Have a reversed pipe from waste to distro that looks like a deactivated distro to waste. Would be more relevant to the job than a single shot shotgun desgized as something that is never used.

**Comment by Kurfursten** [comment]
This is just a balance PR

**Comment by FudgePucker** [comment]
Maybe add some fake bean bag flares that light them on fire and also stuns longer than normal bean bags. As it stands a bartender with a saw can get a better weapon than the atmos techs job specific traitor item, and even then can get away with the didndunuthin excuse because they do it as non antag when compared to the flare gun that has 0 use.

**Comment by clusterfack** [comment]
Give flaregun foam flares

**Comment by clusterfack** [comment]
But yes, totally unrelated to this PR

**Comment by clusterfack** [comment]
Anyway if no one has objections to this to speak up with, it'll get merged soon

**Comment by Kurfursten** [comment]
@clusterfack I actually like that idea. Or maybe some flare ammo that you can fill like tanks, which rewards atmos techs who build heat chambers / space coolers. Outside of scope, but a neat idea to add to my list.

**Comment by FudgePucker** [comment]
@clusterfack 

> Foam flares

OH GOD YOU ARE EVIL
@Kurfursten

> shootable air tanks

 OH GOD YOU ARE DOUBLE EVIL

**Comment by Probe1** [comment]
:+1:

**Comment by Kurfursten** [comment]
@clusterfack

**Pull request merged**
