### PR TITLE
RIP Syndicate Wheelchair

### PR DESCRIPTION
**Pull request by Kurfursten**
- Syndie wheelchair now has an obvious name, description, and bright red coat of paint
- Wheelchair now cannot damage someone more than once per second.

untitled

### CODE REVIEW

**Comment by jknpj** [comment]
It's still pretty strong now that is has no slowdown, but  as i said, not being stealth is the biggest nerf. I like it.

**Comment by SkowronX** [comment]
I hope this isnt going to be too big a nerf.

**Comment by 9600bauds** [comment]
I didn't really notice it had a slowdown to be honest

**Comment by ScrambledSteak** [comment]
g o d f u c k i n g b l e s s

**Comment by 9600bauds** [comment]
Making it stop moving is awful to be quite frank
Make it skid for one second or something
Also right now you can bypass the "chair stun" by dragging it behind yourself

**Comment by Kurfursten** [comment]
@9600bauds That's an easy fix, just anchor it

**Comment by jknpj** [comment]
If you get run over, can you get up in that one second? If you can't i don't see how it is awful. Sure, you can't faceroll escape/shuttle anymore but then again, it is still a strong 1v1 weapon.

**Comment by 9600bauds** [comment]
You're not guaranteed to be stunned when ran over I believe

**Comment by Kurfursten** [comment]
~~You will be knocked down guaranteed~~ real testing shows I am wrong, this isn't true anymore since the last nerf round, but yeah same as any other weapon if you get knocked down once, 1v1 you're dead.

Still, this will make killing slow enough that people can easily warn the rest of the crew unlike an esword, and with a 50% higher cost than an esword + unconcealable + useless once the AI starts to bolt doors, this one will just be for style kills from here on out.

**Comment by ihadtoregisterforthis** [comment]
What about a delay for running over a same mob again, with longer time?

**Comment by Kurfursten** [comment]
I don't really like the inconsistency of psychic chair that knows who you last ran over to give bonus time for. What people were really upset was the ability to run over 3 sec officers who fumble their tasers in rapid succession. This nerf will completely prevent that and make it impossible to use the chair against more than one person unless you've got a gun or something.

**Comment by 9600bauds** [comment]
Make it skiiiiid

**Comment by AutismSpider** [comment]
>some one on the memewheels

>tasers mean any thing half the time they have shield to block it or hulk out making the taser fucking useless

no safe way take some off it unless you shotgun them in the face three times or you get cyborg stop them

**Comment by Sprok0** [comment]
Cyborgs can't even stop it effectively, it drives right over them

**Comment by Kurfursten** [comment]
If you only had a taser versus a hulk, you were going to die whether they had an ~~egun~~, a wheelchair, an esword, a fireaxe, or even a hatchet.

Same as trying to take down a Gygax with a taser.

**Comment by Allspice** [comment]
Just a reminder, you can't into egun while hulked. Or taser, or caplaser, et cetera.

**Comment by Blithering** [comment]
The instant brake on hit seems a little much, making it obvious that whoever is barrelling down the corridor at you has murder on the brain is a big enough hint  in my opinion. Maybe instead give it the stun when colliding with solid (i.e. non-roadkillable) objects that the secway has?

**Comment by SonixApache** [comment]
Drop everything but the recolor, see if that does the trick.
Shit like this always reminds me of those gamedev quotes from hideki kamiya / the borderlands devs.

**Comment by FudgePucker** [comment]
Put some streamers onto the handle bars.
It will make it go faster.

**Comment by Kurfursten** [comment]
I suppose I can take off the 1-second stun and we can always nerf it more later.

But I'll add an emp_act too

**Comment by Sprok0** [comment]
Rather than make it stop moving entirely, maybe make it so it can't crush again for a second or two

**Comment by Kurfursten** [comment]
Okay. I  have followed that suggestion because it seems reasonable. So to clarify, the current revision is:
- Slowdown re-added to chair
- Still highly obvious paint job, name, description
- Now can't damage more than once per second, but does not stop the chair from moving

Please update your Redditvotes

**Comment by AutismSpider** [comment]
put the emp stunning it back on you fag some thing that should have been on it form the start should have never been taken off.

**Comment by SonixApache** [comment]
merge it

**Comment by Kurfursten** [comment]
There was never any EMP stunning

**Comment by ghost** [comment]
It should have had one like there is on the janicart and the clown cart. How'd it not have one from the start?

**Comment by ComicIronic** [comment]
Probably because the default wheelchair doesn't have one and nobody thought to add it.

**Comment by ComicIronic** [comment]
We're going to trial this for balance.

**Comment by kol1th** [comment]
:frowning:

**Pull request merged**
