### PR TITLE
beepsky no longer arrests people that are invisible via alpha var

### LINKED ISSUE #15870: Beepsky can see and arrest jaunting wizards
#### Description of issue

I tried to jaunt from the AI core in Bagel to the escape pod below bridge. Officer Beepsky noticed me while I was invisible and incorporeal, stunprodded me, and I was downed as my jaunt expired in the hallway, leaving me vulnerable to the detective that heard the noise.

#### Difference between expected and actual behavior

If I can't be attacked by humans in this state I assume I shouldn't be attacked by a stunprod bot.

#### Steps to reproduce 

1. Be a target within Beepsky's parameters for arrest
2. Start a jaunt from outside his range so he doesn't start aggroed on you
3. Move into his range
4. Get stunned

#### Length of time in which bug has been known to occur

I'm not sure when this bug became a thing. The first time it's happened is today.

#### Server revision

Game: af25d80b871d85f1da391adf266a1812c5c85722 
Patches: cce7d45130404579663c09010c5d0aebe829e6d6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #15870

Previous reading:
#22400
#22405

I still have no strong opinions for or against this pull request, but it does have things that need to be changed like also not trying to arrest things with a high enough invisibility var

todo:
- [ ] fix the existing is_visible() proc to not be retarded (seperate PR)
- [ ] use is_visible() proc in this PR
- [ ] make secbots have an upgrade to go after invisible people

:cl:
 * tweak: Beepsky no longer arrests people that are invisible via alpha var

### CODE REVIEW

**Comment by bathosbathtime** [comment]
I like my idea of moving invisible arresting ability to an upgrade involving t-ray scanners but I don't know if anyone else does.
In justification of invisible arresting other than "its fun," it is also something that keeps invisible wizards/traitors from being god like.  Other counters include the t-ray/p-ray scanner lines, water, thermals(?), mouse-over text, blind firing in the halls, and possibly HuDs such as sec and med if that hasn't been fixed yet.

**Comment by FudgePucker** [comment]
HE'S A LOOSE CANNON, BUT HE IS STILL THE BEST OFFICER ON THIS GOD FORSAKEN STATION.

I would be in support of being able to add a t-ray scanner upgrade to let beepsky keep his ability to show JUSTICE to invisible perps.

**Comment by boy2mantwicethefam** [comment]
Beepsky tug of war where sneaky coders pull out the most insidious tactics

**Comment by FudgePucker** [comment]
Also there isn't much of counter play to invisible antagonists.

Getting close enough to a wizard with a cloak to see them with a t-ray scanner is a death sentence. And the CE isn't going to receive a weapon to help hunt until it's too late. Seriously, even though I am a head, it's like pulling teeth to get a laser gun for carp.

**Comment by Durgen** [comment]
anyone who down thumbs this PR is a mime main

**Comment by jknpj** [comment]
Can't be a main something when you don't play. Checkmate, vox metaclub leader.

**Comment by ShiftyRail** [comment]
Invisible hazards/threats are dumb and there need to be a way to deal with them
Beepsky was reasonable enough

**Comment by Intigracy** [comment]
I'll need to fix is_visible before anything else

**Pull request closed without merging**
