### PR TITLE
Biting and kicking while handcuffed.

### LINKED ISSUE #32206: You can't bite without arms
(WEB REPORT BY: cartlord REMOTE: 206.221.180.138:7777)
# Revision
640def376fa86972a10781008b1229fbd59a5072

# Description
Lost both arms, tried to bite, no dice

# Steps to Reproduce
-Lose arms
-Enable bite
-Click thing

# What you Expected
-Cronch

# What Actually Happened
-Jack shit

### PR DESCRIPTION
**Pull request by Hinaichigo**
[bugfix]
This makes it so you can still bite and kick while handcuffed. I tested with a muzzle and biting and it behaved properly - and with legcuffs and kicking and it behaved properly. Also works with the various permutations of amputation and restraint.

This doesn't affect the current behavior where a human can't kick while prone, and can't bite when they have something covering their mouth, not limited to muzzles.

Closes #32206

:cl:
 * bugfix: Handcuffed individuals can still bite and kick. Security beware!

### CODE REVIEW

**Comment by adacovsk** [comment]
Those jokes...

**Comment by angryturnip** [comment]
This just overly complicates kidnapping people and makes it so sec has to muzzle people they're transporting which removes any RP. It makes sense from a realism perspective but is awful from a gameplay perspective.

**Comment by adacovsk** [comment]
> This just overly complicates kidnapping people and makes it so sec has to muzzle people they're transporting which removes any RP. It makes sense from a realism perspective but is awful from a gameplay perspective.

The RP is beating the prisoner to death if they bite

**Comment by Hinaichigo** [comment]
If a captive bites a captor while restrained, they can simply be stunned or beaten into submission.

**Comment by angryturnip** [comment]
At least add a ghetto way to muzzle people with rags or something

**Comment by angryturnip** [comment]
Also, I realize this does technically fix the bug you posted, but this is a huge gameplay change to the way restraining people works.

**Comment by Hinaichigo** [comment]
It's true, it does change things a bit, but I have seen this requested here and there, so let's see how people feel.

We could have it so handcuffed people can't bite or kick, but armless people still can, or something.

Also I'll work on making rags work as ghetto muzzles in another PR.

**Comment by WindowsErrors** [comment]
I said this before but for the record, this PR in combination with [this PR](https://github.com/vgstation-coders/vgstation13/pull/31913) gives you even less of a reason to _not_ just behead the vampire on the spot

**Comment by Hinaichigo** [comment]
I'll see if I can make muzzles not slip-out-of-the-way able in the ghetto muzzle PR.

**Comment by bathosbathtime** [comment]
If this passes I'll make it official policy for security to just kill prisoners that bite and/or kick them.

**Comment by adacovsk** [comment]
> gives you even less of a reason to _not_ just behead the vampire on the spot

It's interrupted if you move. Also nerfing biting wouldn't hurt anyone. For example, we can change the damage from 2 to 1 so it's blocked by all armor.

I think including kicking while handcuffed is a bad idea though

**Comment by WindowsErrors** [comment]
> If this passes I'll make it official policy for security to just kill prisoners that bite and/or kick them.

you will?

**Comment by Hinaichigo** [comment]
If someone has no arms, should they be able to bite and kick?

If so we could close this and open one where handcuffs prevent biting and kicking but armless people won't be harmless.

**Comment by xeroxemnas** [comment]
more reasons to just kill people rather than kidnap them.

**Comment by angryturnip** [comment]
> If someone has no arms, should they be able to bite and kick?
> 
> If so we could close this and open one where handcuffs prevent biting and kicking but armless people won't be harmless.

I really don't understand why this wasn't the initial PR considering the bug you're referencing is talking about exactly that. I would upvote that.

**Comment by Hinaichigo** [comment]
One thing to note is that muzzles aren't the only thing that prevents biting. Anything that covers the mouth normally prevents biting.

**Comment by Hinaichigo** [comment]
Looking at the other PR #23255  relating to this that was rejected for technical reasons, though contrastingly had unanimous support, I think this might be able to be implemented in a better way. Also it only had kicking and biting when not actively pulled. So I'll mark this as a draft and work on it if this seems like it has enough support, or possibly redo it along the lines of that PR. 

Please let me know what you think of kicking and biting while restrained only when not being grabbed or pulled.

**Comment by Hinaichigo** [comment]
Going to take another look at this according to the previous comment.

**Comment by Hinaichigo** [comment]
I'll do it again more nicely, possibly with a config option for being able to attack while simultaneously restrained and pulled/grabbed.

**Comment by pedr69** [comment]
give pain damage to stunbatons or a way to break bones without making the guy bleed to death
at last the spiked syndishoes will have a purpose

**Pull request closed without merging**
