### PR TITLE
Soap should no longer attack people

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I'm gonna look at the code later
:cl:
 * bugfix: Soaps will no longer attack targets you clean.

### CODE REVIEW

**Comment by jknpj** [comment]
why not port the NOBLUDGEON flag from bay?

**Comment by boy2mantwicethefam** [comment]
1. im lazy
2. didnt know it existed

**Comment by jknpj** [comment]
>didnt know it existed

Now you do, get to work

**Comment by boy2mantwicethefam** [comment]
no

**Comment by jknpj** [comment]
Then die for your sins :gun:

**Pull request closed without merging**
