### PR TITLE
Add back the changeling

### PR DESCRIPTION
**Pull request by Manleto**
In the few times I've seen the changeling bused it's been a whole lot of fun to play against.   I understand that a lot of people are not a fan of the ling,  however I think the need for more antag types (we have a variety issue) warrants it's readdition. 

I think a compromise is warranted. The compromise comes in line with the the other change I'm proposing, which  is to vastly reduce the chances of getting changeling in dynamic.   If it turns out that changelings are terrible no matter what,  it won't affect too many rounds before removal. If it turns out that server culture has changed enough for ling to be fun, then we can up the dynamic rate.  If changeling is fun as a once in a while treat then we can keep it rare.

:cl:
 * rscadd: Just added ling back
 * rscdel: did other stuff!

### CODE REVIEW

**Comment by Buchse** [comment]
Ling as it is really is just no fun to play against, especially since people only use it as traitor+.  Someone mentioned they were trying to put together a ling rework along the lines of what i'd mentioned a while back.

**Comment by Manleto** [comment]
> Ling as it is really is just no fun to play against, especially since people only use it as traitor+. Someone mentioned they were trying to put together a ling rework along the lines of what i'd mentioned a while back.

This would be temporary until that rework happened. We're at an antag shortage and variety is the spice of life.

**Comment by ghost** [comment]
The issue with ling isn't it being frequent. The issue with ling is that it's a gamemode/role which encourages the player to silently and permanently remove as many people from the round as possible. No other role is like this. One could argue vamp is similar but that's not true. Vamps aren't required or even encouraged to permanently remove their victims, thralling gives them a reason NOT to remove them. Maybe they'll do 1-2 permanent removals early on if they're playing it safe, but even then they could gamble that their victims will be good sports about roleplaying and spare them.

Nobody wants to fix ling because there's no easy way to do it. I'd suggest making them a solo role instead of spawning 2-3+. Maybe even take the thralling idea to the extreme and make it a conversion gamemode with no win condition, your objective becomes to assimilate as many players into the hivemind as possible and you can spawn them back in as new changelings once you get enough Ling Points(tm).

Calling it a temporary change is a very strange thing to say, the gamemode is almost unanimously agreed upon to be unfun for the victims and methodical for the antag. If you want it back in then you should go all the way or don't bother at all.

**Comment by boy2mantwicethefam** [comment]
inb4
image

**Comment by Manleto** [comment]
If no one adds a ling rework this would be permanent unless removed yes, I was more just saying that I didn't intend this to be a ling rework.  Part of this is simply a test, if people don't like it we can remove it.   Ideally I would also have it such that only one would spawn, but I have no idea how to code. 

I don't think this is necessarily true anymore.  There have been multiple cases of it being bussed in to great affect, even with the permanent removal factor have lead to interesting and fun rounds.  Permanent removal increases the tension. which can in turn increase the fun.

**Comment by Manleto** [comment]
One of the other changes I'm thinking about is making horror form less costly.  

Maybe buff it's stats a little

**Comment by BomberBro** [comment]
Do the changes, then add the gamemode back in. We already got so sick of this shitty iteration of ling that we removed it from snaxi, there's no need to have it again so we can reach the same conclusion.

**Comment by ShiftyRail** [comment]
https://www.youtube.com/watch?v=mLFvthzy294

:notes: *It's the circle of liiiife...* :musical_note:

**Comment by SonixApache** [comment]
fix ling *then* add ling

**Comment by BanEvader43** [comment]
jobbies go home

**Comment by ghost** [comment]
Changeling was changed to encourage permanent removal. Can't eat monkeys, can't eat monkeymen. Trying to eat a dead body of a player, sorry dude this one doesn't count. They changed it so that you have to kill a player and eat them right then and there, so you have to remove active players from the game permanently. You can't just loot the morgue or steal monkeymen, then have to explain to security why you were stealing bodies and turning them into husks. You can't just play a cargo changeling who has to explain why he was ordering 10 crates of monkey cubes and dragging them into a dark room where he disabled all the cameras. Your only options as a changeling is silent removal and stealing fresh cloneable bodies.
You people changed the changeling to encourage permanent removal of players and then someone went ''wtf I don't like permanent removal,'' and now changeling has to be disabled because you optimized all the fun out of the changeling. Like hitting your own fingers with a hammer and then cutting off your own arm because your fingers now hurt.

**Comment by BanEvader43** [comment]
readd monke succs

**Comment by KingofHONK** [comment]
Force horror form if the ling lasts 45 mins on the station and has 15 dna to spare. If it doesn't it dies. This would be a bandaid to prevent the dreaded lingstended from happening. The problem of ling is lack of interesting, varied options and the lack of urgency. Can't fix the first one without code, but can bandaid the second one.

**Comment by BurntDevil** [comment]
turning on ling in the state it is in will be absolutely stupid. its not fucking fun. 
nothing about the current ling is fun. or the old ling. ling isnt fun any of the ways we have tried it. it needs to be rebuilt from the ground up with fun in mind. perma removals from the round in a sneaky manner arent fun, and other servers have methods of integrating the victim into the ling so they can still enjoy the round, and mechanics like that need to be brought here. until these revamps are done, dont fucking make us suffer a shitty antag

**Comment by Allspice** [comment]
Unfuck ling before bothering to re-add it.
(ps unfucking it involves removing sucks altogether)

**Comment by Eneocho** [comment]
How about this:
Ling can't depop-suck individuals, but rather, a-la John Carpenter's Thing, it assimilates them. Assimilated individuals can either fight for control or stay as secondary to the ling.

Rather than getting DNA from sucking individuals, it gets DNA from assimilated bodies, the more assimilated individuals, the quicker the DNA storage fills, akin to a mana bar in a game. Objectives would go from "get x amount of dna" to "hold x amount of bodies when leaving".

If fighting for control, you start corrupting the main body, process accelerated if you deploy certain chems, slowed if said chems aren't present or if the main body or secondaries are fighting against you. If you reach 100% corruption, you seize control, if not, you blackout for a minute or so and must obey the main body after "waking up". The main body gets an alert as to whether an assimilee is trying to seize control and can do actions accordingly. It can ask the other asimilated individuals to counter deploy or outright remove you at some considerable hp and DNA cost.
On the other hand, when staying as secondary, you become a mix of arm and torso/head borer, you get some attack capabilities and can deploy some chems, but in exchange, you're exclusively dependant on the main body and can't leave, unlike a borer.

If the main gets killed but not destroyed, an assimilated can seize control of the body, with the corruption being much, much faster since the original is gone, regenerate it and become next ling.

This'd give ling a dual nature, for it will get stronger the more individuals it has assimilated, it also gets more unstable, possibly losing control. It'd make for some good gameplay, since even when assimilated, you can "fight" the main body, whilst simultaneously making it much more dangerous and unpredictable than just "haha silent depop goes brrr".

**Comment by DamianX** [comment]
image

> Do the changes, then add the gamemode back in. We already got so sick of this shitty iteration of ling that we removed it from snaxi, there's no need to have it again so we can reach the same conclusion.

**Comment by TrojanWhite** [comment]
> image
> 
> > Do the changes, then add the gamemode back in. We already got so sick of this shitty iteration of ling that we removed it from snaxi, there's no need to have it again so we can reach the same conclusion.

Fucking faggot admin

**Comment by TrojanWhite** [comment]
Why the fuck was this closed

**Comment by TrojanWhite** [comment]
And the prick even voted down so bias is clear

**Comment by DamianX** [comment]
Sure, keep this open, I guess. I just don't see the point since it's so controversial you're certain you're pissing off 50% of the population whatever you do (and we've historically closed such PRs, with many examples to back this up).

**Comment by boy2mantwicethefam** [comment]
*and we've historically closed such PRs when we the collabs didn't like them but if we liked them we merged them
FTFY

**Comment by Kurfursten** [comment]
That's true and not a bad thing. When the will of the people is clear, 98% of the time, the collabs follow the emojis. When things are close, it can go one way or another, someone has to make a tiebreaking call. This is not a particularly popular task - I've done my share of it and caught a lot of flak for it because half of the people are always upset. I can speak as someone who hasn't voted on this PR and doesn't feel strongly about it - I'm glad a decision was made one way or the other.

Someone has to make a call on these things at the end of the day, and when the vote ratio is so close (7:6) I am glad it is being moderated by someone who I at least know is highly invested in our server specifically*.

*According to rapsheet, Damian has over 10k connections [about 8.3 barries, or nearly one decabarry] and last connected 3 hours ago.

**Comment by boy2mantwicethefam** [comment]
Your honor, I will reject this ownage unless the non-observer connection rate of Damian is >3 barries

**Comment by ghost** [comment]
Apparently this PR is a ling too, because it's alive again.

**Comment by drawsstuff** [comment]
Wait until someone reworks it, there's a lot of people trying to do just that at the moment.

**Comment by PrimeDSS13** [comment]
The downvotes are now greater than the upvotes, meeting trojanwhites critera. Close the PR again!

**Comment by ghost** [comment]
Don't forget to behead/cremate this time.

**Comment by BurntDevil** [comment]
The only acceptable PR for Lings is to remove it entirely from the code.

**Comment by SonixApache** [comment]
ok can we close it now

**Comment by optimumtact** [comment]
Keep ling alive it's soul of vg

**Comment by drawsstuff** [comment]
fuck off oranges

**Comment by Kurfursten** [comment]
Try again after revisions hit

**Pull request closed without merging**
