### PR TITLE
Weighted Voting Clarification

### LINKED ISSUE #7582: possible weighted vote issue
**NOTE: this just happened on the testing server, so i don't know if it affects the regular server too**

i was on the testing server, then i called the shuttle to restart it; when tha map vote popped up i choose boxstation.
i was alone on the server, so this means that 100% of votes gone to box, but it was chosen metaclub instead. additionally, defficiency appeared two times (one with a typo)

vote

### LINKED ISSUE #7634: Wording of weighted random map selection causes rampant misunderstandings
Rather than saying "Weighted vote result," say something like "Weighted random selection." People in the thread seem to constantly think it means something it doesn't.

### PR DESCRIPTION
**Pull request by clusterfack**
Weighted vote -> Random Weighted vote
% chances added to the end of the options
fix #7582
fix #7634

### CODE REVIEW

**Comment by clusterfack** [comment]
Does this code work? The world may never know

**Comment by DrCelt** [comment]
this should fix #7582 & #7634 right?

**Comment by clusterfack** [comment]
Yeah I guess, I didn't want to bother looking for complainer issues

**Comment by DrCelt** [comment]
lazy hallion

**Comment by Exxion** [comment]
Wait
You opened this PR in response to #7634 
And initially forgot to include that it fixes #7634?

**Pull request merged**
