### PR TITLE
Fixes

### LINKED ISSUE #5920: (WEB REPORT BY: anonymousrex REMOTE: 198.245.63.50:7777) Automatic Robotic Factory 5000 bypasses Silicon Job Bans
>Revision 

7a0aa2617dc18c4bb52a11381f57acdc4423d5d6 
>General description of the issue

Was jobbanned for 3 days starting yesterday (ban still in place) and was successfully converted into a functional cyborg.

>What you expected to happen

That the job ban would've prevented the automatic borging, I guess?

>What actually happened

The machine bypassed the ban.

>Steps to reproduce if possible

Get jobbanned from silicons, fight a cyborg with a sonic jackhammer and lose, then get forcibly borged by the Automatic Robotic Factory 5000 (or you can just skip most of that, apply a job ban to a test subject and feed them in).

### PR DESCRIPTION
**Pull request by Repth1**
- Fixes  #5920: Automatic Robotic Factory 5000 bypasses Silicon Job Bans #5920

### CODE REVIEW

**Comment by Probe1** [comment]
>The [src.name] throws an exception

I laughed.  

:+1: 4 more fixes after this!

**Comment by PJB3005** [comment]
You should completely delete their corpse though, the malf AI can't know whether somebody's job banned, and this can give them precious seconds to scream before being killed by the AI/borgs.

**Comment by Repth1** [comment]
@PJB3005 While true, the same thing happens if you try to put a jobbaned MMI into anything, that can potentially screw up a traitor roboticist.

Also I have no idea how to get rid of them cleanly.

**Comment by PJB3005** [comment]
@Repth1 yeah but the MMI doesn't have a radio most of the time, and you can easily silence it (take the brain out)

**Comment by Repth1** [comment]
@PJB3005 Yeah but you could also argue, that if someone is on the borger, they've either been knocked out or have been able to yell the entire time. The only way this would be a negative, would be that in between the time they're on the conveyor belt, and the time they go through when the machine says it doesn't work, they regain consciousness or manage to talk again, cause after that they can just be killed.

**Comment by PJB3005** [comment]
@Repth1 You obviously haven't been killed by being received by telescience with a borger next to the pad, have you?

**Comment by Repth1** [comment]
@PJB3005 The telescience machine can't teleport into or out of the AI core or upload without a bluepsace crystal which are rare and require humans or MoMMIs to manually insert one into the telepad.

So no, not that I can remember.

**Comment by Zth--** [comment]
Just turn them into spider-bots or something useless like that

**Pull request merged**
