### PR TITLE
Revert "morgue light for "dead and potentially revivable""

### PR DESCRIPTION
**Pull request by Inorien**
Reverts vgstation-coders/vgstation13#34952

>try to clone
>MIF
>go to morgue
>red red green
>?????
>try to clone again
>scan successful

image

I agree with Gallywix from the original PR and this change just doesn't really do anything useful imo

### CODE REVIEW

**Comment by Kurfursten** [comment]
I'm confused by what you're trying to convey in your story. Didn't the lights make you try a second time, thus causing him to get revived? Anyway: I don't have a dog in this fight in terms of whether this PR gets merged, but you have to update the wiki this time if it does, or else
image

**Comment by SonixApache** [comment]
so you're saying that a guy died and disconnected or crashed, you put him in the morgue, the lights that tell you that the guy isn't necessarily completely gone confused you into thinking that the guy was in his body, and in the moment it took him to click the GIANT TEXT THAT SAYS CLICK HERE TO RE-ENTER YOUR BODY you managed to throw him in the cloner and it happened to work?

why is this a bad thing again?

**Comment by Kurfursten** [comment]
Not one emoji thought it was worth explaining their position other than sonix, and his opinion seems reasonable, so here's your proof that comments matter more than emojis.

**Comment by pedr69** [comment]
image

**Comment by Kurfursten** [comment]
image

**Comment by Inorien** [comment]
oh i completely forgot about this, lmao

only point i would have made is that before the change, seeing all red lights -> dont bother, seeing all green lights -> the guy is in there and 99% wants to come back

after the change its red red green -> they are ghosted and still connected, but maybe dont want to come back, maybe they do, maybe they dont know their body was found, its extra work as a doctor to check everyone every time you see a red-red-green. i still think this is extremely dumb, but i'll just quietly seethe about it and ignore people who aren't in their bodies in morgue

DJ put it the best way though, if you want medbay to notice you quickly, just be in your body.

**Comment by SonixApache** [comment]
>its extra work as a doctor to check everyone every time you see a red-red-green.

the mixed sign is just an indicator that maybe those bodies shouldn't be handed to the chef for insta-gibbing

**Pull request closed without merging**
