### PR TITLE
Grenade PR

### PR DESCRIPTION
**Pull request by BurntDevil**
Laundered PR for jakmak6. He will provide description.

* rscadd: Adds premade timer grenades to the autolathe under the contraband section, these grenades have an easy to use timer that can be adjusted during and after grenade assembly
* rscadd: adds an adjust timer setting to pre-made chemical grenades like the weed killer and metal foam grenade

### CODE REVIEW

**Comment by jakmak6** [comment]
The purpose of this PR is to make grenade mass production easier, since most grenades would use a timer/igniter assembly as its detonator, ive added a grenade casing with one already inserted. Originally I was going to have 2 options for grenades, one with a long timer, one with a short timer. When I was dissecting the holder file I found code for an adjustable timer, I simply adapted it and made it more accessible via a right click on the finished grenade/grenade casing. (instead of hidden in the objects tab) 
The grenade casing can be made from the autolathe in the assemblies tab, its price is the same as 1 grenade casing and an igniter+timer

**Comment by BomberBro** [comment]
zoom zoom

bundling both powercreep grenades with being able to tweak existing grenade timers is pretty lame

**Comment by PrimeDSS13** [comment]
why would autolathes print pre-made grenades that makes zero sense
additionally why would you make grenades easier they are already just a few steps and there's no reason to make it even easier
also bomber makes a good point about atomic PRs

**Comment by jakmak6** [comment]
@BomberBro if its so desired I could strip out the adjust timer verb section of this PR and open a second. And tell me, how is being able to easily adjust a chem grenades timer a bad feature?

@PrimeDSS13 Ever try to produce several grenades? The amount of adjustment needed to make the detonators is a long, tedious, and annoying process. A process which can easily be shortened by cutting out the middle man.
As for having it in the autolathe, where else would I have it? Ammolathe? Congratulations, the only people who will see it is the powergaming scientist who built every fab and lathe that exists. protolathe? Another item only to be seen and used by science. 

All this does is simply a tedious process. For detonators that use any other kind of trigger (proxy sensor, voice activator, signalers) the nature of those require tailor made configurations. Timer grenades could easily function with a cookie cutter timer that can be adjusted without painstaking hassle.

**Comment by ghost** [comment]
if you want to use grenades a minimal amount of effort isn't really so much to ask of you

**Comment by BomberBro** [comment]
I don't, I think adjusting default grenades is a fine feature, but I don't think it belongs with something else that I dislike such as free grenades from autolathes. timer grenades are pretty uncreative and mostly used for bombs or pacid, I don't get your argument that only scientists will use it if it was in the ammolathe (it shouldn't be regardless) when with the current PR scientists are STILL going to be the only ones to use it because they're the only ones with an autolathe AND a chem dispenser roundstart

**Comment by SonixApache** [comment]
assembly-based timers are extremely fucking annoying to work with and i would much prefer this system

**Comment by jakmak6** [comment]
moved the grenade casing (with preinstalled timer) to the contraband tab on the autolathe

**Comment by jakmak6** [comment]
what is up with travis, its been running for over 2 days now and it isnt giving any errors or clue why its taking so long

**Comment by SonixApache** [comment]
he's getting old

**Comment by agentofzog2** [comment]
Every time I try fucking around with grenades it feels like it would be more efficient to just stick with the quick and easy TTVs instead, so I'm all for this.

**Comment by Spyroshark** [comment]
Making a grenade that has the timer set properly is not a hard process at all. I think mass producing bombs should be a bit of a tedious process, since, you know, you're mass producing bombs that will probably be used to bomb the station

**Comment by SonixApache** [comment]
It's not so much difficult as tedious. Grenades *can* be used for good instead of evil, but rarely are. Is the reason for this that grenades are tedious to make? Maybe.

For bombing the station, canister bombs, one-tank bombs and TTVs are way easier and more effective. Waterpotass grenades are garbage outside of targetting specific people, and nitro grenades take a while to make. Polymutasmoke grenades are pretty lethal... if you can catch someone off guard. They're really not all that effective compared to the 'real' bombs. EX Multi-slime grenades are probably the scariest thing you can make with grenades, and even then... low impact.

And then on the light side, you've got metal foam grenades, air grenades, 'good' slime grenades, cleaner grenades, meme grenades... They're fun to use, but very tedious to make.

**Comment by gurfan** [comment]
working with assemblies is fucking annoying and I would much prefer this

**Comment by Jackreturnswithaveangenace** [comment]
good players on the right, bad players on the left

**Comment by BurntDevil** [comment]
Going with a server vote. To be continued.

**Comment by SonixApache** [comment]
what a shame

**Pull request closed without merging**
