### PR TITLE
Fixes lone lattice icon

### PR DESCRIPTION
**Pull request by ghost**
[sprites]
Before:
image
After:
image

:cl:
 * tweak: Lone pieces of lattice not connected to anything now look it.

### CODE REVIEW

**Comment by Servalfang** [comment]
this is bigger then the grille fix of '99

**Comment by SonixApache** [comment]
new look bad, old look good

**Comment by Kurfursten** [comment]
I like the old one more

**Comment by cadaverouscoyote** [comment]
if i didn't know better i'd take that for an item at first glance. old sprite communicates what it is much better

**Comment by ShiftyRail** [comment]
I like it and I'm going to be the tie breaker

**Pull request merged**
