### PR TITLE
Taxi Fix 2: The Movie

### LINKED ISSUE #4629: [Taxi] Map issues
-taxi caller buttons being reliant on APC power seems like it could be open to abuses
-HoP sunglasses and armoured suit at the bottom of locker
-doors are below firelocks all over the place
-accounts database cannot be reached due to dense objects (damn it Deity), room generally needs to be made bigger
-recharger should be on the wall if there's no room for it on the table
-shutters in bar area on top of the tables look silly
-disposals is fucked south of disposals on Engi-Cargo station, holes where there should be pipes
-gas sensors above vents in mini-atmos'
-virology access button underneath a newscaster
-light switch in surgery on the table
-sink above window just north west of medbay entrance
-no intercom in genetics
-maintenance east of chemistry randomly has a shit load of first aid kits in it
-missing wall in virology north east of the disposals
-incorrectly placed cobweb in Medbay station disposals
-too many poorly placed windows all over the place, shit looks structurally unsound
-no bells
-medical break room door called Surgery
-botany backroom vent is visible
-intercom on top of APC in science entrance
-pipe under rwall in east genetics
-pipe under rwall north of mini atmos room
-ugly windows in server room
-custodial closet is incredibly small and in maintenance
-ugly window east of custodial closet
-visible vents all over engineering
-atmos has non-visible vents while every other pipe is visible
-toxins lab floor under central door is not white like it should be
-telescience igniter switch on the table
-wiring under windows generally is fucked up, needs to be like it is on the other stations
-three doors at medbay entrance looks hideously ugly, needs the central one replaced with a wall or window, plus the windows to the east and west look ugly
-medbay entrance APC is cramped onto the wall alongside the door button
-captain's office door has incorrect floor under it
-double layered bridge windows - what
-sec entrance poster is on the floor and not on the wall

### LINKED ISSUE #4646: (WEB REPORT BY: exxion REMOTE: 198.245.63.50:7777) [TAXI] Maintenance Access
>Revision (Should be above if you're viewing this from ingame!)

096a8f877f64bd4c41a705c8963302995fdc614b
>General description of the issue

Every single maint door on taxistation is named "Maintenance Access," as far as I can tell
>What you expected to happen

Have maint doors with special access requirements be named "[Department] Maintenance" or whatever it is, like on all other statins
>What actually happened

Not that
>Steps to reproduce if possible

1. Load taxistation
2. Move cursor to a location where a department maintenance door is
3. Read bottom of screen

### LINKED ISSUE #4661: [Taxi] Brig issues
-The cells are 2x2 which makes putting people into them, buckling them to the bed and uncuffing them while flashed rather difficult.
-Middle brig timer can only be accessed from the tile to its immediate left
-Right brig timer cannot be accessed from in the room, is visible from the courtroom and can only be accessed from the courtroom. Brig timers generally have awful code so all this is unsurprising, Defficiency and Meta both had major issues with them.
-Armory is tiny, contains no shotguns, barriers, flashes and Mr VALIDs might need another storeroom somewhere perhaps

### LINKED ISSUE #4685: [Taxi] No ATMs
there are no ATMs on taxi

### LINKED ISSUE #4689: [TAXI] No AAC at round start.
I wanna make mah autism SM at round start!

### LINKED ISSUE #4690: [TAXI] Security Bell inaccessible, rendering it useless & No ERT/adminbus port
What's the point of a bell you can ring to attract security's attention if it requires security access to open the windoor to get to it? 
Also add ERT functionality, please.

### LINKED ISSUE #4695: (WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Taxi robotic material
>Revision (Should be above if you're viewing this from ingame!)
a3da7b07bffbdbadf47ea8fb130e892fc4537ba7

>General description of the issue
Robotic doesn't have enough metal at roundstart

>What you expected to happen
Being able to build at least one cyborg

>What actually happened
Can't even build one without ugrade and tech sync

### LINKED ISSUE #4696: (WEB REPORT BY: eldzen REMOTE: 198.245.63.50:7777) Taxi Virology
In Virology you are unable to reach the table in the top right cornet because of machine placement.
http://puu.sh/i1M73/a0111e8fbb.png

### LINKED ISSUE #4697: [Taxi] Janitor Closet
I'd love to be more specific in the title, but it would be too long

- Janitor gets two trash bags and no soap (the closet contains a trash bag plus there's one on the table)
- No water tank in the room (though there is a sink outside, so this is excusable)
- Neither table in the room is accessible without moving something/opening lockers
- Room is piss-tiny, with a grand total of two tiles not containing dense objects at roundstart, making the previous issue all the more irritating
- This one is only a minor complaint, but there are only two cleaner grenades in the room on Taxi compared to three on... I think all the others

### LINKED ISSUE #4713: [TAXI] Emitters in secure storage are welded to the floor.

### PR DESCRIPTION
**Pull request by Kurfursten**
- bugfix: Emitters are no longer wrenched/welded in secure storage fixes #4713
- bugfix: Robotics starts a shift with 100 sheets of metal fixes #4695
- bugfix: Machines in virology rearranged fixes #4696
- bugfix: Atmosia now has an AAC and Central Atmos Comp fixes #4689
- bugfix: Warden's office rearranged fixes #4690
- bugfix: Cells and armory now have some breathing room fixes #4661
- bugfix: Added ATMs to every taxi dock and also cargo fixes #4685
- bugfix: Fixes #4629 with ...
- bugfix: Fixed camera and lightswitch in surgery
- bugfix: Fixed igniter button in telescience
- bugfix: Adjusted a maintenance window near Custodial Closet
- bugfix: Fixed tile coloring in toxins lab
- bugfix: Custodial closet made bigger, added cleaner grenade, given soap, removed extra trash bag fixes #4697
- bugfix: 16 maintenance doors renamed to be more specific fixes #4646

### CODE REVIEW

**Comment by ComicIronic** [comment]
The rearrangements need images.

**Comment by Kurfursten** [comment]
@ComicIronic 
taxi

**Comment by ComicIronic** [comment]
The proper number of flashes for Taxi is smaller, because security itself is smaller and therefore easier to cover.
That armory is also way too big. If you want to make it larger, at least use the space efficiently.

**Comment by Kurfursten** [comment]
I dunno, I think 2 flashes is reasonable for Taxi. 

Also, the armory looks big because it's on Taxi, but it's still smaller than Box (83% the size of Box Armory)

**Comment by ComicIronic** [comment]
It looks larger because it has a lot of needless and empty space.

**Comment by Kurfursten** [comment]
The space makes it easy to move and take out barriers

**Comment by ComicIronic** [comment]
Only because the armory isn't structured to take full advantage of the space.

**Pull request merged**
