### PR TITLE
changelog 2 electric boogaloo

### PR DESCRIPTION
**Pull request by CrazyAmphibian**
edited the yml so it won't break hopefully

### CODE REVIEW

**Comment by Eneocho** [comment]
I TOLD YOU ABOUT STAIRS BRO

**Comment by Eneocho** [comment]
If this one breaks too you'll need to make a dummy PR with all the CLs on the description, which sounds scuffed as hell.

**Comment by CrazyAmphibian** [comment]
> If this one breaks too you'll need to make a dummy PR with all the CLs on the description, which sounds scuffed as hell.

that wouldn't work since it'd drop the author's name from the CL

**Comment by Eneocho** [comment]
> > If this one breaks too you'll need to make a dummy PR with all the CLs on the description, which sounds scuffed as hell.
> 
> that wouldn't work since it'd drop the author's name from the CL

Still, better than no changelog, and you can always format it like this:

:cl:
* rscadd: SpessmcSpessman: Fixed a thing

**Comment by toomykins** [comment]
> > > If this one breaks too you'll need to make a dummy PR with all the CLs on the description, which sounds scuffed as hell.
> > 
> > 
> > that wouldn't work since it'd drop the author's name from the CL
> 
> Still, better than no changelog, and you can always format it like this:
> 
> 🆑
> 
> * rscadd: SpessmcSpessman: Fixed a thing

pretty sure this changelog syntax (having double colons) was the exact fucking reason the last try at this was doomed

**Comment by Eneocho** [comment]
Then do:

:cl:
* rscadd: SpessMcSpessman - Fixed a thing.

**Pull request merged**
