### PR TITLE
Clown Language. Honking as means of communication.

### PR DESCRIPTION
**Pull request by Eneocho**
Added a clown language to the game. It's a native language to clowns, the same way Janitors spawn with mouse or Librarians spawn with some X language.
Since clowns have their own planet and religion, it makes sense for them to have their own language.

:cl:
 * rscadd: Added a clown language.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
make the language color pink and the font comic sans

**Comment by jwhitak** [comment]
Please do as above comment suggested. Emoting my favor in advance. Honk.

*_Honk_*.

**Comment by Eneocho** [comment]
> 
> 
> make the language color pink and the font comic sans

Pray tell how, friend. I jury rigged this the best I could. I've no idea where I could fix that, though pink comic sans sounds very thematically appropiate.

**Comment by Eneocho** [comment]
Would yellow comic sans be more appropiate?

**Comment by ShiftyRail** [comment]
Pretty good, but I don't think it should be a roundstart thing. Make the honker WORK for it.

**Comment by Eneocho** [comment]
Figured it out. Made it banana yellow with comic sans. This is how it would look on white background. (Does anyone still use bright mode?)
Clown language visual style on white background

**Comment by ShiftyRail** [comment]
>Does anyone still use bright mode?

Yes.

**Comment by gurfan** [comment]
yellow will be unreadable, make it pink

**Comment by Eneocho** [comment]
> 
> 
> yellow will be unreadable, make it pink

That's the point. But lets compare.
style comparison

**Comment by Eneocho** [comment]
I actually quite like how the pink shade looks (it's  #ff9fef, by the way). But I'd much rather have the yellow for how annoying and hard to read it is.

**Comment by xeroxemnas** [comment]
Ok now we need a mime exclusive "language" that is just hand movements that only other mimes can understand and it's complete.

**Comment by Dacendeth** [comment]
Could make mimes understand the clown language since it's reasonable they learned the language of their enemy from the great mime clown war.

**Comment by Eneocho** [comment]
> 
> 
> Ok now we need a mime exclusive "language" that is just hand movements that only other mimes can understand and it's complete.

Can't.
What I did is adding a Say "language. You need to speak it using the say/whisper commands. 
Also, No way in hell I could mess with the mime's spellcode to make it work with the no speaking effect. It took me long enough to make this.

**Comment by gurfan** [comment]
wait, what?

**Comment by APCUnlocked** [comment]
time to decapitate clowns for talking near me since that font and colour is absolute eyerape

**Pull request merged**
