### PR TITLE
Revert "makes buttbots explode after a certain amount of butting"

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Now that the dust has settled, can we agree that this was a really bad idea?

:cl:
* tweak: Buttbots will now butt on forever once more

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
yeah new buttbot explodes way too fast you barely get any butt mileage out of it

**Comment by Babaganosh** [comment]
> Now that the dust has settled, can we agree that this was a really bad idea?
> 
> 🆑
> 
> * tweak: Buttbots will now butt on forever once more

let them butt on once more

**Comment by Exxion** [comment]
Pretend I just made a PR titled "Alternative to #27894" that just completely removes buttbots
Too much effort to actually do it

**Comment by DrSnips** [comment]
Yeah, no thanks.

**Comment by DeityLink** [comment]
the best jokes are the shortest-lived ones.

**Comment by boy2mantwicethefam** [comment]
Buttbots farting have been around for years, this joke of them self-destructing has outlived its funny value

**Comment by ShiftyRail** [comment]
Now that the butt has settled, can we butt that this was a really butt butt?

**Comment by KingofHONK** [comment]
If this shit doesn't butt through at least make it where if you emag em they are back to normal.

**Comment by SageOfLight** [comment]
The change was fucking stupid and reductive to the zaniness that ss13 was fostering. Also buttbots are a lynching excuse anyway. It all resolved ingame.

**Comment by ShiftyRail** [comment]
>It all resolved ingame.

*hides a buttbot in a random corner of the asteroid with 7 SBRs tuned to different departments*

**Comment by ghost** [comment]
Locking it behind an emag or something is the only way I'd want to see it back in full form, since, while entertaining, they will shut down comms for the rest of the round if someone feels like it. I'd be happy to see a compromise of extending the life of the current ones, but as it stands they might as well not exist because they don't last long enough to even get a chuckle out of.

**Comment by DeityLink** [comment]
Infinite butt bot spawner as a traitor item, an indirect way to ruin comms.

**Comment by SageOfLight** [comment]
I'd rather see them brought back as traitor tools than be removed forever because you guys don't want a pinpointer that can be set to "Butt".

**Comment by SonixApache** [comment]
butt, just butt raise the buttage you butt out of one buttbot.

**Comment by DamianX** [comment]
butt butt

**Comment by Kammerjunk** [comment]
just add a new pinpointer for literally everything in the game
i am a professional game design

**Pull request closed without merging**
