### PR TITLE
Expanded botany backroom, moved bar piano

### PR DESCRIPTION
**Pull request by Rei1226**

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
Pics where

**Comment by Rei1226** [comment]
420blazeit

**Comment by Probe1** [comment]
works for me.

**Comment by TermedClepe** [comment]
>moved bar piano

Screenshot?

**Comment by Rei1226** [comment]
Everything on tables were moved to the two tables to the left
The lights are there, for some reason they're now reskinned to those fuzzy shaded things you can see over the wooden table and the locker. I don't understand who changed them or why, but yeah.

Bar piano was moved to the bottom right of the bar. Don't really think it's such a huge change it needs a screenshot.

**Comment by DeityLink** [comment]
>Bar piano was moved to the bottom right of the bar.
But why?

**Comment by Probe1** [comment]
@DeityLink Everyone complained about its current placement being awkward from the proximity to the cig machine.  I don't care but that's the issue raised by others.

**Comment by 9600bauds** [comment]
This when

**Comment by DeityLink** [comment]
muh piano

**Comment by ComicIronic** [comment]
RIP this PR as well.

**Pull request closed without merging**
