### PR TITLE
Illegal research item: Mini Chameleon Projector

### PR DESCRIPTION
**Pull request by ghost**
[content]
This is something I've had in my branch backlog for ages, basically like normal chameleon projectors except only works when placed on an item, disguising it. Fun for doing stuff like disguising forks as power cells and tricking people into putting them in APCs, etc.
:cl:
 * rscadd: Illegal tech research on protolathes can now create mini chameleon projectors, items that disguise any item as something else scanned, even when moved around and picked up. Can only be removed by examining.

### CODE REVIEW

**Comment by Eneocho** [comment]
I feel this should also be available to traitors at a cheap price, or to come included with the normal chameleon projector purchase.

**Comment by Blithering** [comment]
I don't doubt this will lead to a lot of TTVs and laser cannons disguised as cigarette butts. I'd say its more suited for a traitor item than science printable.

**Comment by Eneocho** [comment]
I was actually thinking more along the lines of disguising a shard as Ian so people "Pet" it.

**Comment by Dacendeth** [comment]
Chameleon projectors dont work on shards it ashes them when you try.

**Comment by Eneocho** [comment]
Figured as much. Then chameleon projecting the (unlocked) crate disguising it as a stolen locker. They click twice, get ashed.

**Comment by Eneocho** [comment]
Just make it a combo item that comes WITH the regular projector.

**Comment by TGFH** [comment]
Spacemen must band together to fight science creep at every turn.

**Comment by BomberBro** [comment]
Would be more interesting if illegal tech wasn't guaranteed and easy to get for science every round.

**Comment by ghost** [comment]
Just tested it and it doesn't work at all, gonna close it until I give it a complete overhaul.

**Pull request closed without merging**
