### PR TITLE
Fixes Syndie Reinforcements bugs & reduces reward to 120TC

### LINKED ISSUE #34493: WAR OPS disables Cargo Shuttle
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
0593a00132f3333fb530cdc471a43b237fe2eceb

# Description
When Ops declares a war and gets reinforcements, this fully disables Cargo's shuttle, preventing the crew from preparing or mining from getting supplies to the station. Arguably, the station is WEAKER when the Ops declare War as a result.

### LINKED ISSUE #34494: War Ops cannot make announcements due to Bluespace Blocking
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
0593a00132f3333fb530cdc471a43b237fe2eceb

# Description
Due to blocking the shuttle/bluespace, War Ops cannot send taunting messages to the Station as they get scrambled by the mentioned blocking.

### PR DESCRIPTION
**Pull request by DorainGrey**
## What this does
Fixes: #34494 
Fixes: #34493 

Reduces reward to 120TC for calling reinforcements.

## Why it's good
It's hard to base stuff on first playtest, since Nukies got an extra 300TC bussed in due to them apparently not receiving TC. (They did, just did not realize it)

However I think even 3 Maulers is too hard for crew to deal with. I kinda anticipated Sec being responsive, handing out guns, barricading etc but it didn't work out so well. So I think reducing it to 120TC where they can at best get 2 Maulers is a reasonable compromise for the added preparation of crew.
Noted, the cargo shuttle will also work again which will allow the crew to order more & better weapons and armour to fight.

## Changelog

:cl:
 * bugfix: Fixed Cargo Shuttle not being callable during Nukie Reinforcements
 * bugfix: Fixed Nukies not being able to taunt the crew during bluespace distortions.
 * tweak: Reduced reward for Nukies calling reinforcements to 120TC down from 200

### CODE REVIEW

**Comment by SonixApache** [comment]
>However I think even 3 Maulers is too hard for crew to deal with. So I think reducing it to 120TC where they can at best get 2 Maulers is a reasonable compromise for the added preparation of crew.

those were the concerns i voiced in the original PR

**Comment by Eneocho** [comment]
I'd put the reward reduction as a separate PR from the bugfixes (cause it is bound to be controversial), but I'm neutral here.

**Comment by nervere** [comment]
`code\game\objects\items\devices\nuclear_challenge.dm:38:warning (unused_var): nuke_op: variable defined but not used`
Please delete this variable so I stop seeing this when I compile.

**Comment by Kurfursten** [comment]
Eneocho is correct that more atomicity is better, but I'll waive it this time since after 5 days there is no dissent

Fix conflicts

**Pull request merged**
