### PR TITLE
no meme issues

### PR DESCRIPTION
**Pull request by Intigracy**
no meme issues

Related:
#9029
#9030
#9106
#9107
#9108
#9109
#9110
#9111

### CODE REVIEW

**Comment by gbasood** [comment]
do  you really think anyone who wants to make a meme issue is going to give a shit about the template

**Comment by Intigracy** [comment]
Nuke wanted us to put it in the issue reporter template so that anyone who does get banned for it can't say there was no rule anywhere for it.

**Comment by gbasood** [comment]
@clusterfack @PJB3005

**Comment by clusterfack** [comment]
I wouldn't explicitly use the word meme

**Comment by ghost** [comment]
Usage of the word meme is a meme.

**Comment by Intigracy** [comment]
no more memes

**Pull request merged**
