### PR TITLE
Fixes opening crates with shuttles

### PR DESCRIPTION
**Pull request by unid15**
It was far too easy to get guns this way

### CODE REVIEW

**Comment by Exxion** [comment]
That's no fun. Now I can't use a locker to get into secure parts of the emergency shuttle.
But it's also totally fair because I shouldn't be able to do that

**Comment by AutismSpider** [comment]
Back to jacking emitters form engi/ied opening shit then.

lets hope this gets in fast

**Comment by ghost** [comment]
Great, now we need to fix opening crates with goats, something I actually witnessed happening and that is used by Cargo specifically

**Comment by AutismSpider** [comment]
oh that was not fix yet?

**Comment by AutismSpider** [comment]
Goats and other host mobs can be use to bust open crates

**Comment by SysadminJeroen** [comment]
And an emitter.

**Comment by clusterfack** [comment]
Bless you sweet coder

**Comment by AutismSpider** [comment]
Faster to get roid mob as the QM any way

**Pull request merged**
