### PR TITLE
"[MDB Ignore] Christmas Lights ! (DO NOT SQUASH THE COMMITS)" (v2)

### PR DESCRIPTION
**Pull request by ShiftyRail**
see title

### CODE REVIEW

**Comment by Kurfursten** [comment]
What's the status on this?

**Comment by ghost** [comment]
europa light when

**Comment by Eneocho** [comment]
> europa light when

never it seems

**Comment by ShiftyRail** [comment]
https://www.youtube.com/watch?v=2I9KXRr3VhI

I'm a bit burnt out on, well, everything. I'm still looking at ways to improve this but BYOND unfortunately is (still) not in 515.

**Comment by Eneocho** [comment]
RIP fancylights

**Pull request closed without merging**
