### PR TITLE
Removes xray

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
A power being removed from a balance point
Why:
- Seeing through walls is extremely powerful as it lets you see any activity within range and shut down any sort of stealth that doesn't involve containers, especially bad for the "cult" group antag that relies on stealth to advance.
- When combined with night vision or mesons, you can see everything within view without any darkness concealing the view, I'm responsible for this because I fixed this.

Direct consequences:
- Scrying orb no longer provides x-ray
- Likewise, the two x-ray wizard potions are gone

If you ever need to add x-ray in some form, you can manually change the user's view_flags to "see_turfs | see_mobs | see_obsj" or something like that. I think I also removed some rudimentary code this way.

:cl:
 * rscdel: The x-rays superpower doesn't exist anymore.
 * rscdel: The scrying orb no longer provides x-ray.

### CODE REVIEW

**Comment by DrSnips** [comment]
I could see from genetics but why wizards?

**Comment by boy2mantwicethefam** [comment]
Because scrying orb activates x-ray, and x-ray can't be in the code without making it available to activate through genetics

**Comment by DrSnips** [comment]
Or you could just code a blacklist of effects genetics cant unlock.

**Comment by boy2mantwicethefam** [comment]
Genetics work by assigning superpowers to blocks, IIRC a superpower can't exist outside of a block, and leaving "dead-end" blocks in genetics wouldn't be fine either, there's also the matter of how to deactivate the powers that can't normally be acquired

**Comment by DrSnips** [comment]
Shit tier idea. A hidden genetics power pool is made along side genetics prime to house hidden powers.
Ok tier idea. Make them spells or something that just gives the user a flag in their traits.
Better tier idea. Genetics only checks for effects in a white/blacklist and then creates visible blocks/list from that.

**Comment by FudgePucker** [comment]
I remember one cult round I was in medbay, both me and the geneticist were in genetics and the captain (sacrifice objective target) comes in and demands xray. Both of us plays dumb. I fill a syringe with sleepy juice, and harm syringe him with it. He was so obsessed with getting his valid seeking powers he didnt even notice. So I went and filled an auto injector with sleepy juice (back when you could do this) and poked him with it.

This shit is cancer. It reduces the value of thermals. It is cancer when an antag gets it, and turbo cancer when the crew gets it.

**Comment by iFlashYou** [comment]
Better idea, leave x-ray for wizman and vamp but replace genetics x-ray with thermals

**Comment by Tehsapper** [comment]
yes lets remove all positive powers from genetics so that you can only use it to gain those cool powers like noir or swedish accent ;)

**Comment by luigil101** [comment]
how bout we just remove this fag boy instead
genetics powers are more valuable than he is

**Comment by DrSnips** [comment]
That's not a bad suggestion

**Comment by Killette2** [comment]
He's right that the crew having x-ray ruins it for a lot of antags, because only the top 10% could pull off being stealthy with that condition. I think there's no reason to take it from wizards, unless you feel like cheaping the scrying orb alongside it.

**Pull request closed without merging**
