### PR TITLE
Revert "clowns are clumsy even when antagonist"

### PR DESCRIPTION
**Pull request by PJB3005**
Reverts d3athrow/vgstation13#12594

This PR and everybody who supported it was retarded let's be honest.

### CODE REVIEW

**Comment by Probe1** [comment]
It hasn't even been a week and the PR was merged because players wanted it calm your tits and revisit this once the reactionary response has settled and we know what people actually think.

but fix clusmy for clown only antag items.

**Comment by Intigracy** [comment]
https://dl.dropboxusercontent.com/s/f2d7752iu61j4fk/2017-01-01_12-35-23.mp4

**Comment by TheFriggenSawbones** [comment]
clowns are still fucked in every team antag mode

game design hard though

**Comment by JustSumBody** [comment]
I'm pretty sure someone else said it, but being gimped during a team antag because the other head rev physically can't flash or one of your starting cultists can't cuff people is pretty fucked
It's one thing to punish clowns or whatever, not stable fair to punish the rest of their team for something they had no choice in

**Comment by carshalash** [comment]
I know you haven't played the game in a long time intigracy, but there is a little thing called the banana bunch now. 

Most of the players who voted for this are kinda dumb and just thought "Oh dude, they can't shoot guns anymore if I vote for this!"

**Comment by Intigracy** [comment]
Literally nowhere until that comment did you mention it was the banana bunch.

**Comment by ghost** [comment]
The simple solution is to prevent clown being drafted for team antagonist roles at the start

**Comment by carshalash** [comment]
I just think rebalancing a role entirely over someone getting mad a clown shot them with the caps gun when they were an antag to be absolutely retarded.

**Comment by Megamaw** [comment]
i think clown should still get clumsy

but a less severe version of clumsy. so still some downsides. keep the more visible and comical things.

so you know, they don't lynch the clown every time they see he's not clumsy

**Comment by TheFriggenSawbones** [comment]
or for the sake of fun we revert it

**Comment by SangriaMonkey** [comment]
I don't get how clumsy is supposed to be funny or some kind of stand-in mechanic for a funny clown player. You can barely even notice it unless you're the clown in question. Just seems like contentious politically-charged shit to me.

**Comment by Probe1** [comment]
Clown apartheid

**Comment by ComicIronic** [comment]
>I'm smarter and better than everyone else on the server and votes are dumb

scope these hot opinions

**Comment by gbasood** [comment]
Hold a post-change vote maybe to justify this
otherwise what the fuck

**Comment by murnandreams** [comment]
Why is everyone for clown antags being crippled?

**Comment by Probe1** [comment]
Oh I don't know because they're **clowns** and this isn't about winning or losing it's about having a good time.

**Comment by murnandreams** [comment]
I'd argue that it greatly reduces the good time if the clown has the odds stacked against them on their antag rolls.

**Comment by Shadowmech88** [comment]
Or it encourages clown antags to do something more unusual and creative than shooting everyone until they stop moving.

**Comment by murnandreams** [comment]
Why is that burden on the clown? And it does more than just effect guns. Hell, if clumsiness only applied to guns, there'd be no issue.

**Comment by 9600bauds** [comment]
bcuz muh metagay

**Comment by gbasood** [comment]
@LemonTheFruit because they picked clown
that is the burden of the clown
that is how it has always been until antag clowns got special treatment
I think that team antags would be especially fucked over by this though

**Comment by ComicIronic** [comment]
>that is how it has always been until antag clowns got special treatment

Which you would likely not remember, because it predates this codebase.

**Comment by ComicIronic** [comment]
Since the original PR was merged on a server vote, I'm not seeing a compelling reason to revert it unless we wait a bit and produce a new server vote which shows a change of opinion.

**Comment by Blithering** [comment]
Solution: have the clown's crayon contain ryetalin when eaten. They can be a useful member of the crew at the cost of removing a little bit of fun from the station.

**Comment by murnandreams** [comment]
Rye doesn't even work on clowns, son.

**Comment by clusterfack** [comment]
The original PR shouldn't have been put up to a vote in the first place. People enjoy voting to fuck over things they don't play and the playerbase's opinion as a whole towards a very specific role shouldn't be taken into account. This goes for mommi, vox, etc.

**Comment by Intigracy** [comment]
`>Rye doesn't even work on clowns, son`

Incorrect.

**Comment by carshalash** [comment]
Normally I love to shit on cluster as much as the next guy with the aunt scootaloo memes but even he can see the very obvious mindset of votes and the playerbase.

And intigracy, do you genuinely have brain damage?  Would you like a prescription for actual alkysine in real life so you can be less brain dead? Your lack of understanding about nearly everything to do with this PR is honestly embarrassing and has reached dylan tier stupidity. You first started posting that webm of the clown with the banana sword without even realizing that the banana bunch was a thing in the game, you just kept smuggly posting the same webm over and over again of the banana sword with your shitty holier than thou attitude.

You know that fucking french idiot whos lack of understanding of the game caused him to kill the serb by injecting a million vapor salts into someone? Your lack of understanding on the playerbase and code is on the same level as his, you stupid fuck.

God damn you're dumb.

**Comment by Intigracy** [comment]
Ah yes forgetting about something is the end of the world.

Thanks for disproving my point about rye though you manchild.

**Comment by Probe1** [comment]
He's just digging his grave for when he wants to appeal his ban.

Also I plan on opening a poll on the one-month anniversary so we can see what players think.

**Comment by N3X15** [comment]
Conflicts, cannot merge until fixed.

**Comment by Probe1** [comment]
http://ss13.moe/index.php/poll/84

The poll will expire on February 4th.

**Comment by murnandreams** [comment]
The poll was the problem, probe.

**Comment by Exxion** [comment]
>If you think so many people want it, do a server poll!
>No, server polls are bad and meaningless!

I know the people saying those two things are generally not the same people, but it still makes it nigh fucking impossible to make people happy
Going with the poll is the way to make sure that the *majority* of the players are made happy

**Comment by clusterfack** [comment]
That is fallacious, unless you assume all the people voting have played clown/intend to play clown after the change. 

If a majority of players are happy at making a minority of players very unhappy, is that something we should allow?

**Comment by Exxion** [comment]
Didn't say it was a perfect system
But until you come up with a way to measure *how much* people on either side care or something along those lines, we don't have a better one

**Comment by clusterfack** [comment]
Applying changes that hurt a group of players based on such a flawed system in the first place was a horrible idea. And the mistake was actually making the change in the first place based on it.

**Comment by PJB3005** [comment]
Yeah the poll is stupid here.

That's like going up to a bunch of drug dealers and asking whether marijuana should be made legal.

**Comment by Blithering** [comment]
Wouldn't dealers hate legalisation? They'd come up against a ton more competition

**Comment by murnandreams** [comment]
The point is that the group would be biased, nerd.

**Comment by Probe1** [comment]
The group is voting for what people have been asked for.  For Group-Antag clowns to not be punished.

Simmer that fire down.

_In fact_, as of right now, revert is wholly winning.  But you're right.  Polls are stupid!

**Comment by clusterfack** [comment]
It doesnt matter which side is winning in whether or not the poll should be regarded.

**Comment by murnandreams** [comment]
Probe, we are saying that the poll was the initial problem, as clown job that the majority dislikes.

**Comment by Probe1** [comment]
Can you show that the majority dislike Clowns?  Cause after 3 years of playing on this server that sounds like a massive ass pull and mistaking IC for OOC.

Clowns are disliked in game but that's a side effect of their job.

**Comment by gbasood** [comment]
Vote over, been over for almost a week actually
http://ss13.moe/index.php/poll/84

**Comment by murnandreams** [comment]
So is it going to be reverted in some way? More people voted for some sort of change, than for the clumsy to stay while antag.

**Comment by Probe1** [comment]
Sure.  No ones opposed to group antag roles losing clumsy.  But at the same time no ones jumping to code it.

**Comment by Intigracy** [comment]
I'll do it tomorrow

**Pull request closed without merging**
