### PR TITLE
Fixes virologist not having access to secure vial container.

### LINKED ISSUE #12554: Secure Vial Storage
(WEB REPORT BY: pinkacolada REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
A virologist does not have the access to open the Secure Vial Storage box in Viro

>What you expected to happen
It to open

>What actually happened
It didn't open

>Steps to reproduce if possible
Get a Secure Vial Storage box and swipe a Virologist ID on it

### PR DESCRIPTION
**Pull request by Probe1**
Fixes https://github.com/d3athrow/vgstation13/issues/12554

### CODE REVIEW

**Comment by Probe1** [comment]
I'd like to point out how efficiently I fixed this and I want @clusterfack to tell me I did a good job.

**Comment by ComicIronic** [comment]
brabo

**Comment by Probe1** [comment]
I SAID CLUSTERFACK YOU'RE NOT MY CODING SENPAI

**Comment by Intigracy** [comment]
I will admit:

Your mother did a good job having you.

**Comment by Probe1** [comment]
I WANT CLUSTERFACK

**Comment by ComicIronic** [comment]
clustercuck'd more like

**Pull request merged**
