### PR TITLE
Maybe fix the volume setting for VLC

### PR DESCRIPTION
**Pull request by DamianX**
Completely untested so it might just make it not work at all, but it seems to me this should take values in the range of 0-200 (like the comment says) rather than 0-20000.

### CODE REVIEW

**Comment by DDihanov** [comment]
I got you buddy:

https://www.techjunkie.com/normalize-volume-vlc/

**Comment by SonixApache** [comment]
Considering that `0 * 100` is still `0`, this probably doesn't solve it. But good catch regardless.

**Comment by StreptoMutans** [comment]
Consistent play only works if the sound is on the exact same value in the rooms you walk through.
Can this fix it?

**Comment by DamianX** [comment]
You mean if two rooms with sound systems have different volume settings, then the sound gets interrupted?
This should be handled here and should be unrelated to this change:
https://github.com/vgstation-coders/vgstation13/blob/6ee990d58db0b9f3162940367caaecd0f22fef2a/code/modules/media/mediamanager.dm#L185

**Comment by DamianX** [comment]
Tested on the test server, seems to work fine.

**Pull request merged**
