### PR TITLE
Processing someone disguised as a chicken has a 20% chance of making vox nuggets instead.

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Sticking someone with a chicken suit on a food processor has a 20% chance of making vox nuggets instead of regular nuggets.
## Why it's good
Fluff
:cl:
 * rscadd: Food processing someone wearing a full chicken suit has a 20% chance of making vox nuggets instead.

### CODE REVIEW

**Comment by BomberBro** [comment]
why?

**Comment by tinysaturn** [comment]
I don't get it
Why not make it do this when it's a vox in a chicken costume?

**Comment by bathosbathtime** [comment]
You are killing the verisimilitude. Stop that, please.

**Comment by Eneocho** [comment]
>Why not make it do this when it's a vox in a chicken costume?

I hadn't thought of that.

**Pull request closed without merging**
