### PR TITLE
Bag of holding singularity on the shuttle take two

### PR DESCRIPTION
**Pull request by Dacendeth**
Remake of #29271 because I dont know how to use github correctly and remaking is easier
bags of holding now make a singularity if you're on z2 and on the escape shuttle, otherwise they explode on z2

Tested shuttle in transit, shuttle docked, tested at vaults that exist on z2, everything either exploded or singulo as it should have.

:cl:
 * tweak: Bags of holding create singularitys on the escape shuttle again.

### CODE REVIEW

**Comment by Eneocho** [comment]
Do you still explode when baguloosing on centcomm?

**Comment by Eneocho** [comment]
Of note is that the original PR had a 12-2 ratio.

**Comment by Dacendeth** [comment]
if you walk off the shuttle at centcom it explodes if you do it.

**Comment by Eneocho** [comment]
> 
> 
> if you walk off the shuttle at centcom it explodes if you do it.

So on shuttle proper at centcomm still bagulooses, but outside it explodes? I'd make it not explode either on the centcomm-stationed shuttle since it makes for better post rock cooking memes.
Also, what If you start baguloosing the tick you change tiles, does a singulo spawn on centcomm proper or does it still explode?

**Pull request merged**
