### PR TITLE
You can now get arcade and carpet tiles from the biogen for 10 points each

### PR DESCRIPTION
**Pull request by Intigracy**
Did it this way because I expect 5768 to be merged anyway, but someone might have an issue with costs or something on this PR.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
honestly this should be a grass mutation

it'd be more interesting

or do both

**Comment by Intigracy** [comment]
go away turdgator-

**Comment by Zth--** [comment]
Plants that grow carpets? It's a good idea but...... weird

**Comment by N3X15** [comment]
1 day for discussion

**Comment by Probe1** [comment]
:+1: biogen needs more purpose

**Comment by Zth--** [comment]
I say yes

**Pull request merged**
