### PR TITLE
Nuke Ops no longer end the round

### PR DESCRIPTION
**Pull request by adacovsk**
[role]
Love me, hate me, I don't care. Rounds no longer end when nuke ops blow up the station. Everyone doesn't instantly die. Everything continues as normal but is in shambles. Nuke still ends the round with blob. Emoji this!

Rationale: we're vg with dynamic, not paradise where the round ends when the antag dies!

:cl:
 * rscadd: Nuke ops no longer end after the nuke goes off

### CODE REVIEW

**Comment by jwhitak** [comment]
"With this ~~character's death~~nuclear explosion, the  thread of prophecy is severed. Restore a saved game to restore the weave of fate, or persist in the doomed world you have created."

I'll choose the doomed world, thanks.

**Comment by Eneocho** [comment]
On the one hand it'd finally give a use to the turbo metalfoam grenades, since 4 or 5 of em could tile the entire station. On the other hand, nobody wants to wait 15 minutes for the round to restart once the entire station infrastructure was destroyed and shit's too fucked to repair in a decent amount of time.

**Comment by djkramer123** [comment]
this is dumb

**Comment by boy2mantwicethefam** [comment]
WE BUILD

**Comment by Optimism333** [comment]
Why, though

**Comment by robintime** [comment]
as github will not let me thumbs down this, i am forced to voice my displeasure in a comment

**Comment by ExpulsionSnooper** [comment]
if this gets merged, d-does that mean my kick PR will be reopened?

**Comment by d3athrow** [comment]
haha, no

**Comment by jknpj** [comment]
We don't need more dorf rounds

**Comment by ExpulsionSnooper** [comment]
> haha, no

:(

**Comment by xeroxemnas** [comment]
lazy admins just dont want to bus in cool fallout stuff after the nuke goes off.

**Comment by Armadingus** [comment]
Won't anyone think of the poor latejoiners dying immediately because they spawn in a crater?

**Pull request closed without merging**
