### PR TITLE
More Bus Minor Fixes

### LINKED ISSUE #10392: Bus - CMO office's APC is not on a wall tile.
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 4cee6922d52fb0f439fd92ab3c9574ec4ca4a836
> 
> General description of the issue
> Title
> 
> What you expected to happen
> APC to be on a wall
> 
> What actually happened
> It was one tile lower on a floor tile.
> 
> Steps to reproduce if possible
> Go to Bus

### LINKED ISSUE #10393: Bus - No defibrillator rechargers anywhere
#### Description of issue

Self-descriptive, Bus Station medbay doesn't seem to have a single recharger for defibrillators despite having two of them.
#### Server revision

5efc3dfb9f6a3d497d4485150db0160a2e6063bd

### LINKED ISSUE #10520: bus station nuke ops shuttle
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

the medical crates are empty

> What you expected to happen

have stuff

> What actually happened
> they are empty
> 
> Steps to reproduce if possible
> be nuke op on bus

### PR DESCRIPTION
**Pull request by Kurfursten**
secremap
- Slightly remapped security to have a sleeper, moved water cooler down
- HoS office now has its own shutters on a button which default to closed at shift start. Keep the rabble out.
- Warden office has reinforced tables to make it somewhat more secure in riot conditions.
- Armory now uses armory lockers instead of crates, because crates could not be relocked. The original rationale for using crates was because Bus is low-pop and much less secure by its small nature and abundance of space suits.
- Security now has unstacked vents and scrubbers as per #10265 - two departments down!
- fixes #10392 
- fixes unreported issue with lacking vent and scrubber in CMO office
- fixes #10393 
- fixes #10520 - Bus nook ops now get everything that Box nook ops get, but because it's a small map, they trade their rocket launchers and bombs for insulated gloves and super glue. This means that Bus ops now have access to medical records, security camera, and a well-stocked ship medbay.

### CODE REVIEW

**Comment by Imagebard** [comment]
>because it's a small map, they trade their rocket launchers and bombs for insulated gloves and super glue

Are you sure this is 100% legal

**Comment by Kurfursten** [comment]
If people think super glue is too powerful they should speak up and shoot the idea down.

But Bus (and its predecessor Taxi) both lacked launchers and bombs for that reason (and the insulated gloves were also already there), so that's definitely staying. I am of course open to including a different free item in compensation or not adding anything extra at all (since of course Bus and Taxi never had them in the first place)

**Comment by Sprok0** [comment]
The combat gloves ops spawn with are already insulated, why did they have yellow gloves on the ship at all

**Comment by Kurfursten** [comment]
Stealth gimmicks

**Comment by Imagebard** [comment]
P8 shit reason.
can you add something for loud attacks then? Maybe a brute and a burn medpack? I don't know.

**Comment by Kurfursten** [comment]
Hell I'd throw in deity's medgun if it was merged

The idea with the glue was you could prevent disarms

**Comment by Imagebard** [comment]
I was thinking of the medigun but I thought it was too OP.

Then again, losing a RPG due to map size isn't that excellent. Add that medigun shit in Y/N?

**Comment by Konater** [comment]
Do it, add an uber heart for the guy carrying the minigun too

**Comment by Kurfursten** [comment]
Fluke ops does surgery to add uber heart
Removing heart causes instant death
Chain explosion

**Comment by Kurfursten** [comment]
@ComicIronic Since the medigun was cancelled, let's go ahead and merge this. I want to revamp Engineering but that's a much larger scale project so it should be a separate PR.

**Pull request merged**
