### PR TITLE
New biogenerator products, foldable crayon&candle boxes.

### PR DESCRIPTION
**Pull request by 9600bauds**
In response to #3170
New biogenerator products:
- Box of crayons, creates the full box with all six colors.
- Bar of soap, important to have when your dumbass botany partner uses said crayons to draw runes all over (plus as mentioned in the feature request, if botany wants to slip people they have banana peels)
- Candles, for when your dumbass botany partner slips you with said soap, steals your ID and turns botany into a cult recreation.
- Bins of paper, you can make the empty bins and mass-produce the paper sheets, all this does is keep you from having to stuff all 30 sheets into it individually.
- Clipboards, leather briefcases, wrapping paper and package wrapper.
- Mining satchels and gadget bags, you can make more plant bags so it makes sense to make these as well.

New cardboard options:
- Lets you make crayon and candle boxes from cardboard sheets, as well as unfold said boxes for re-purposing. Why not.

Changes to existing biogenerator products:
- Cardboard cost lowered from 200 to 100. Cardboard boxes do have a use by being able to store small items, but a cost of 200 points is very prohibitive for kitchen uses like pizzaboxes and donut boxes. People throw boxes on the floor all the time anyways, so there's not an awful shortage of them that would warrant such a high cost.
- Paper sheets cost lowered from 75 to 15. Paper has absolutely no business costing so much given that it has no important practical uses and there are dozens of full paperbins around the station.

Additional info:
The biogenerator code is so fucking good, the UI is so neat and tidy, I wish autolathes and protolathe construction menus were like this.

### CODE REVIEW

**Comment by Midaychi** [comment]
Any chance of adding it so you can output fertilizer to a connected container instead of to individual 10 unit containers? So you can fill a bucket with robust harvest? (There's reasons you'd want to do something like this in xenobotany, I assure you.)

If you want to copy someone, https://github.com/ParadiseSS13/Paradise has done it already.

**Comment by TermedClepe** [comment]
Awesome, good job man.

**Comment by 9600bauds** [comment]
Changed product fertilizers to go into the loaded container since it was silly that it was only used for milk - I fucking love the biogenerator code. I didn't need to copy anything, just slightly change the recipe,
Only thing I couldn't fix is beezeez, for whatever god-forsaken reason it's not actually a reagent, the bottle IS the beezeez, It's not even actually a container, you just insert the "beezeez bottle" item into the apiary and it works. I don't think anyone will ever be bothered by this since the dispenser starts with a ridiculous amount of beezeez and you rarely need more than two in the entire shift anyways.

**Comment by Probe1** [comment]
i've never actually noticed an apiary require a second bottle.  the bees are happy with one, or maybe even none i've never questioned this.

**Pull request merged**
