### PR TITLE
Adjusts the shuttle sounds to be 25% quieter

### PR DESCRIPTION
**Pull request by ghost**
Probe is right (#17557).  At their loudest, these sounds are intolerable.  This change should cut down their volume by the requested 25% at their loudest possible occurrence.  I included all of them, because they are all just too loud.

:cl:
 * tweak: Makes the shuttle-related sounds 25% quieter.

### CODE REVIEW

**Comment by ghost** [comment]
@Probe1

**Comment by Probe1** [comment]
That'll do it.  Thanks @HarseTheef for enabling my laziness 😄

**Comment by ghost** [comment]
I didn't think about it until you made the issue, but I actually have a keyboard macro for muting my sound at round end because of this combined with everything else.  I guess it had just become second nature.

**Comment by DeityLink** [comment]
imo the departure and transit sounds were fine :/

**Comment by Probe1** [comment]
It's still going to be louder than everything else in the game.

**Pull request merged**
