### PR TITLE
200 point secway crate

### PR DESCRIPTION
**Pull request by Intigracy**
yep

### CODE REVIEW

**Comment by ghost** [comment]
way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way way 
too cheap

**Comment by clusterfack** [comment]
Can you make it so it requires a key and a set of keys spawn in a lockbox in wardens office

**Comment by kol1th** [comment]
image

**Comment by kol1th** [comment]
make it 500 so your average greyshirt can't order it roundstart. same with cargotide

**Comment by ghost** [comment]
:100:  tested

**Comment by Intigracy** [comment]
worksonmymachine

```
+/datum/supply_packs/secway
 +  name = "Secway crate"
 +  contains = list(/obj/structure/bed/chair/vehicle/secway,
 +                  /obj/item/key/security)
 +  cost = 200
 +  containertype = /obj/structure/closet/crate/secure
 +  containername = "Secway crate"
 +  access = access_security
 +  group = "Security"
```

**Comment by Intigracy** [comment]
`>give sec the keys to a vehicle they don't even have in their office`

`>make it so expensive that the only people who ever WILL use it are miners/cargo`

Yeah fuck it I give up on this.

**Comment by SonixApache** [comment]
Is there no security account that comes with 5000 credits like every other department?

**Comment by ComicIronic** [comment]
Or maybe the higher price will incentivise sec to make money, thus pushing the economy that we've been working for?

**Comment by ihadtoregisterforthis** [comment]
I see no problem on giving sec exclusive and roundstart access to the keys. It doesn't change anything if they don't order secways and is better than teleporting the keys or _lockboxes_

**Comment by Exxion** [comment]
You can't do that
An individual key is bound to an individual vehicle

**Comment by Intigracy** [comment]
Not that I'm aware.

**Comment by Exxion** [comment]
That wasn't a question
It is a fact
Spawn two janicarts and try to use the key from one of them on the other

**Comment by ihadtoregisterforthis** [comment]
Well that changes things

**Comment by PJB3005** [comment]
Then code changes to it?

**Pull request closed without merging**
