### PR TITLE
Adds pistols to armory, and holobadges to sec

### LINKED ISSUE #12010: Box (map) doesn't have holobadges
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 6141d3384cb484a04884512410d9c1b82b1dad83
> 
> General description of the issue
> Unlike Deff (and Meta?) Box doesn't come with a box of holobadges. This is a great problem for Security.
> 
> What you expected to happen
> Wave my blue badge at people to indicate I AM THE LAW
> 
> What actually happened
> Have to baton people to death to indicate I AM THE LAW

### PR DESCRIPTION
**Pull request by SonixApache**
- rscadd: Added .45 pistols to secure armories of all maps, each with one extra magazine. The weapons in their place were moved to the secure lockers.
- rscadd: "Box: Added some .45 practice ammo to the firing range."
- rscadd: "Box and Meta: Added 2 boxes of holobadges to the briefing room"
- tweak: "Box: Security officers can now use the external airlocks in maint just outside security."

Resolves #12010

Box Armory

### CODE REVIEW

**Comment by Kurfursten** [comment]
A new, unmonitored space door loaded up with space suits and jetpacks right next to the prison wing? Perma breakouts just got a lot easier.

**Comment by ghost** [comment]
> unmonitored

There's a point, where's the cameras?

Nevermind, am dumb

**Comment by SonixApache** [comment]
Copied it straight from Deff's brig, guess that's a problem on their end as well. Noted.
Why's Travis telling me to go fuck myself?

**Comment by ghost** [comment]
`"ajX" = (/obj/machinery/portable_atmospherics/canister/air,/obj/machinery/atmospherics/unary/portables_connector,/obj/machinery/airlock_sensor{dir = 2; frequency = 1331; id_tag = "sec_eva_int_airlock_sensor"; master_tag = "sec_eva_airlock_control"; pixel_x = -24; req_access = null; req_access_txt = "0"; step_y = 0},/turf/simulated/floor{icon_state = "dark"},/area/security/range{name = "\improper Security E.V.A"})`

Travis doesn't like step_y or step_x equalling anything, causes weirdness with movement as it's a global variable

**Comment by SonixApache** [comment]
There's a camera across from the connector port, I didn't even notice that myself. 
Camera view:
SecEVACamera

**Comment by jakmak** [comment]
What if you swapped the position of sec EVA with the shooting range as so prisoners dont get a easy space suit and way out and sec might be more inclined to do firing squad executions.

**Comment by SonixApache** [comment]
Noted, but I don't think escaping perma convicts are a concern in this. Firing range is a nice idea, but south-to-north executions look nicer anyway.

**Comment by SonixApache** [comment]
Turns out the airlock buttons don't have access requirements, I'll have to fix that.

**Comment by SysadminJeroen** [comment]
As I can see, the security distro loop is used as backup to the air canister, right?

**Comment by Konater** [comment]
Airlock access buttons cannot be access restricted.
The valve is set to like 300kpa or something, so if someone pisses away all of the air distro will fill it up again.

**Comment by Kurfursten** [comment]
@Skullyton @SonixApache That's not exactly my point. On Deff, to get to that airlock you have to pass through the warden's vision. He can see the door to the sec EVA from his chair. You can't get from any cell, perma or otherwise, to the EVA without walking right past his checkpoint. Moreover, if you hack the door open, even if the warden is busy watching cameras, he can hear the airlock sound.

This is tucked out of the way, up above the sec medbay in an area that is not regularly patrolled and has no one sitting in vision/noise range by default. This is a pretty big deal.

**Comment by Hoshi-chan** [comment]
Who the hickity heck is Travis?

**Comment by Kurfursten** [comment]
@Hoshi-chan Is this a new meme or are you seriously asking?

**Comment by FudgePucker** [comment]
Crazy idea, replace those windows with plastic walls.
That way you need a welder and a wrench to break out instead of that glass shard you nabbed.

**Comment by Shadowmech88** [comment]
I don't think the issue is prisoners breaking out, but others breaking _in._

An external airlock leading directly into the Security wing, with a complimentary heavily-armored hardsuit on the way in, would make it much easier to take Security by surprise. Or to get into the brig and hide without any evidence of you being there, whereas now someone would have to at least break a window to get into the brig from space.

**Comment by FudgePucker** [comment]
The cycling airlocks are harder to hack because you also need to know the bolt wire.

**Comment by SonixApache** [comment]
@Kurfursten @Shadowmech88 you make a fair point. I'll ditch this plan and swap some lockers around instead.

**Comment by Shadowmech88** [comment]
@SonixApache 
An alternative solution could be placing blast doors on the exterior airlock that can only be opened by a button in the warden's office, as well as removing the windows from the Sec EVA room entirely.

**Comment by SonixApache** [comment]
Decided to do it as such:
NewArmory

While I'm at it I might as well add guns to all the maps.

**Comment by Shadowmech88** [comment]
Also while you're touching Box Security, could you make the exterior airlock south of the HoS office and Sec escape pod accept Security access?

If I remember correctly, currently when an officer wants to EVA, they have to walk to Arrivals or Escape.

**Comment by SonixApache** [comment]
@Shadowmech88 done.
I think everything's actually working as intended now.

**Review by PJB3005 — APPROVED** [review]

**Comment by icantthinkofanameritenow** [comment]
You know, I don't entirely understand the point of this. If things are bad enough to justify opening the armory, Sec is going to want something much better than a few pistols. I'd suggest instead lowering the price on the pistol crates instead; there is no reason why they should cost 10 fucking times as much as the basic weapons crate despite being significantly weaker.

**Comment by SonixApache** [comment]
They're in the armory because they're lethal guns. Handing each officer a gun if there's more than three on the force is difficult without ordering new stuff from cargo, hence some roundstart pistols.
The pistols also have more capacity than the roundstart shotguns; more chances to hit.

The price is to try to prevent every officer and their mother having a gun. Of course that doesn't work since they can just ask the HoS, QM, miners, HoP or silicons for it, but it's a deterrent, sort of.

**Pull request merged**
