### PR TITLE
BusStation: First Revision

### LINKED ISSUE #10182: "Useless" book on Bus Station's hydroponics
#### Description of issue

The book "The human harvest" is blank upon reading, making it an useless addition to Bus Station's hydroponics.

Should either remove it or give it some actual content to the book.
#### Server revision

d285a4411d86d707427ddbe1835ff4ae9ad5c086

### LINKED ISSUE #10183: "Useless" door on Bus Station's Hydroponics
#### Description of issue

There's a maintenance door blocked by a wall on Bus station's hydroponics' left
#### Server revision

d285a4411d86d707427ddbe1835ff4ae9ad5c086

### PR DESCRIPTION
**Pull request by Kurfursten**
Wherein I realize that Bus is not included in the map merge tool.
- Some brig areas were not properly defined (as it was rebuilt following suggestions from the previous PR)
- Two doors near the rebuilt brig didn't have tiles under them
- One botany door to maint had a wall under it
- Added some lights
- Added a hoe to Vox outpost
- Defined the space sorter as an area. I don't know why this was necessary - I don't think Taxi did it, and I think it worked previously in testing, but clearly something about autoconveyors has changed because it won't run outside a defined area now.
- Fixed a missing cable to the podbay on eng/cargo
- Adjusted Civ/Eng bridge
- Fixed a missing cable to Xenobio maint
- Fixed Virology airlock buttons being hidden under a poster
- Door under airlock to mining half of research station
- Fixed airlock access to courtroom
- Completely reworked Toxins and the maint outside of it
- Added a lot of detail work to Perma
- Made the needlessly-small chpel office a bit larger
- Fixed the Vox SMES being infinite (oops)
- Science maintenance is now much bigger, boasting two medium-sized rooms.
- AI core upload made more spacious, hopefully without losing security
- Added Lamarr to RD office
- Added extra airlock to mining entrance to research shuttle
- Detailing work to space around the stations: added a mini roid, a smashed satellite, a wrecked room, and a singularity construction area. These are all part of an effort to make flying around the stations more interesting.

closes #10183 
closes #10182 

**Major revision: Toxins**
No longer need to walk through the break room to get in. Now has a nice space view window. This revision was made based on feedback with the community players on the test server. The freezer has also been moved from the storage room to the mixing room.
busrev1

**Major revision: Brig**
This is not all from the latest PR, but there hasn't been a picture of the brig in a long time. Note how the new structure promotes sec officers meeting right above the cells so they can watch anyone imprisoned while also being served coffee from the brig cafe. Perma has had windows added in the latest revision. I originally did not want to have windows in perma because this map has so many space suits and pods, but we'll give it a try with heavy guard. These are plasma windows with reinforced girders under. While I wanted to avoid the temptation of replicating "perma botany" which is on every other map, there is a hidden soil patch now with no seeds - but if you're lucky, it might grow some random weed mushrooms.
busrev2

### CODE REVIEW

**Comment by ComicIronic** [comment]
You should include Busstation in the map merge tool.

**Comment by Kurfursten** [comment]
Gave my best, it corrupted the map file. Maybe someone else could do that and I'll use the tool in the future after it has been changed.

I can rebase to the version with the maptool. I'm just afraid of losing my progress because it has already corrupted twice in attempts to edit maptools.

**Comment by PJB3005** [comment]
Why are you closing this?

**Comment by Kurfursten** [comment]
I'll reopen it after someone updates maptools, and also I don't want someone to merge it because I think somehow in my original attempt (before first commit pushed) to use the maptool, somehow the map in this commit has no changes (it's identical to the test serb version).

Fortunately I made a backup before anything else because I have bad past experiences with map tools, so the changes are safe.

**Comment by Kurfursten** [comment]
New pictures

**Comment by Hoshi-chan** [comment]
That shuttle that leads directly to the asteroid is going to lead to a lot of cold, depressurized research shuttles. That exit needs a double airlock or to not exist.

**Comment by Kurfursten** [comment]
Testing reveals that the external airlock timings are shorter than ZAS needs to move, so there is no leakage unless you stand in the doorway.

But it's a valid point. Maybe I can push back the asteroid a bit more. The wall is a little close for my tastes, it would be really annoying if gibtonite spawned there on the edge.

**Comment by PJB3005** [comment]
> Testing reveals that the external airlock timings are shorter than ZAS needs to move

Not how ZAS works, you're just lucky.

**Comment by Kurfursten** [comment]
This list is getting exhaustive. I guess I should get around to trying to get the maptool to work.

**Comment by Kurfursten** [comment]
This is rebased to the latest, reduced with the maptool, and has all those changes from above. It's ready to go live.

**Pull request merged**
