### PR TITLE
(more) snaxi changes

### LINKED ISSUE #24251: Snaxi southwest security solar APC is offset the wrong direction
#### Description of issue

image

pretty sure you did x = -20 instead of 20
@plosky1

### PR DESCRIPTION
**Pull request by plosky1**
[snowmap]

Some minor changes that were requested. Vox shuttle shutters can be closed from the inside and outside now. Armory expanded a little bit, more shotgun shells added, one of the regular shotguns removed, and two secways added. Replaced xenobotany dirt piles with trays. Jailcell lockers linked to timers. Fixed #24251 

🆑 
rscadd: Snowmap: Armory has had a Nanotrasen officer go through it and add and remove unnecessary items. He's also fixed some of the jailcells. The workout room has had workout machines added to get SICK GAINS.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Does every map really need a room where we spam exercise machines now?

image

**Comment by plosky1** [comment]
Yes, how else do I get epic gains?

**Comment by ShiftyRail** [comment]
Did you add rechargers to security stations ?

**Comment by plosky1** [comment]
@ShiftyRail Already added in last update.

**Comment by tuypo1** [comment]
Why would you ever want LESS shotguns

**Pull request merged**
