### PR TITLE
Cargo computer UIs overhauled

### PR DESCRIPTION
**Pull request by BarneyGumball**
Porting (and improving) an old PR of mine that brings nanoui to the cargo computers.

Features include:
- Everything on a single screen now.  No obnoxious backwards and forwards nonsense.
- You can now order up to 20 of a crate type with a single click
- You can also cancel your own orders from the Ordering computer now
- If you can't afford the amount of crates you're asking for, you will be notified of how many you can actually afford

Cargo

### CODE REVIEW

**Comment by mrpain666** [comment]
Thank fuck. The old UI was such a clunky mess.

**Comment by Kurfursten** [comment]
Gee Bill, how come your mom lets you have that many separate accounts?

Great work though, I hate working with interfaces and you're blowing through them - this looks exactly how I imagined it  :+1: 

IIRC the supply computer and supply requests computer (the one out in front for the public) use a lot of pastecode, are you condensing them to one computer?

**Comment by SonixApache** [comment]
'ACCEPT / DENY ALL' BUTTONS AND/OR CHECKMARKS ELSE THIS IS JUST AS SHITTY IF NOT SHITTER THAN THE OLD ONE

**Comment by Kurfursten** [comment]
@SonixApache If it doesn't go to a separate "thanks for confirming" screen then it's a huge step up from the old one. You just click confirm over and over without having to hit back.

**Comment by SonixApache** [comment]
That much is true.

Does it list approved requests?

**Comment by BarneyGumball** [comment]
@SonixApache I avoided that option just so cargo is still required to at least glimpse at what people are ordering instead of just accepting everything every time.  You can still mash the "APPROVE" button to quickly churn through orders.

And yeah the approved requests are under the current requests.

@Kurfursten I don't think there's any reasonable way to merge the two computers.  The public cargo computer isn't supposed to ever be able to order contraband/hacked items, which I believe is why there's 2 different circuits for the computers.

**Pull request merged**
