### PR TITLE
Removed round-start AI job slot

### PR DESCRIPTION
**Pull request by DamianX**
These changes will do nothing as they are. They will have to be accompanied by a secret repo PR to take effect on the server.

:cl:
 * rscdel: Removed round-start AI.

### CODE REVIEW

**Comment by Chazach** [comment]
absolutely dangerous levels of based

**Comment by nuklearcellphoneg** [comment]
Neato

**Comment by DrSnips** [comment]
I shiggy diggy.

**Comment by TheFriggenSawbones** [comment]
why though

**Comment by Orangerush** [comment]
brainlet

**Comment by Irradiation** [comment]
Is this the means that we must take to prevent the fashy future?

**Comment by carshalash** [comment]
A bit early for an april fools pr mate.

**Comment by Exxion** [comment]
Have Coders Gone Too Far?

**Comment by Spooooon7830** [comment]
I don't see the logic behind this at all.  If this is being done because you want to rework it fine, but removing shit just to remove it is bonkers.

**Comment by carshalash** [comment]
I ded remove job role the pr.

**Comment by plapatin** [comment]
what the fuck

**Comment by nuklearcellphoneg** [comment]
Science can always make one. :^)

**Comment by carshalash** [comment]
If only they could make alkysine for you.

**Comment by tayachiya** [comment]
Just wanna point out, guy that wants AI removed just got perma'd from AI
Excruciating toe line shift of AI and logged out at 45 minutes. Admitted to playing a caricacture just to make a point. Logged out promptly 42 minutes into the shift. Appeal this when you can play the role seriously.

**Comment by carshalash** [comment]
image

**Comment by Exxion** [comment]
Yeah considering that I'm going to say that yes, Coders Have Gone Too Far

Merits a poll anyway
But I've never failed to fuck up a poll so someone else should make it

**Comment by Inorien** [comment]
Damian go to bed and come back tomorrow and look at how daft you're being

**Comment by ghost** [comment]
What the fuck even???
No reasoning behind this, nothing logical and makes no sense.
-1

**Comment by Hoshi-chan** [comment]
"If I can't be AI, then no one can!"

**Comment by Exxion** [comment]
It was the other way around
He got banned for intentionally playing badly to make a point about removing it

**Comment by Hoshi-chan** [comment]
That's even more retarded.

**Comment by optimumtact** [comment]
that explains the playercount

**Comment by Durgen** [comment]
I admire the audacity of this pr

**Comment by lolman360** [comment]
what next, remove security? remove science? remove cargo?

**Comment by SonixApache** [comment]
Okay, sure, but why?

**Comment by ShiftyRail** [comment]
Because I share the general idea of this PR I'll defend it.

I think that AIs don't make a positive contribution on the vast majoriry of rounds.
AIs gimp round progression by being the invincible eye in the Sky which spies on every antag and every crewmember.

As a result, the #1 priority for an antagonist is to kill, or subvert, the AI. And for security, in the event of, say, Cult or Revs, their #1 priority is to get the AI off Asimov because it'll impede their ability to work properly.

This is not a problem with Asimov, as often said. Asimov is the only way to make AIs bearable on non-cult/non-revs, but it does not work anyways because of the extreme lust for valids an AI has.

The problem is that we have to do that almost every time. It's frustrating, it's bad for round variety and round progression. In short, AIs reduce the general fun of the game simply by existing and this, funnily, without even breaking their laws.

>I died

Not that it matters but I rarely if ever play antag ; I just had too many rounds where the AI just valided the antagonist 30 minutes in, without trying to engage in any sort of gimmick. And that's frustrating.

> Just kill the AI

Killing AIs is litteraly trivial. It's akin to a washing machine laundry program. It's not fun to do because they're griefing or have been subverted.

> Get it off Asimov

Same as above. Not to mention that silicons feel much more free to grief people on other lawsets (not even getting banned for it because of some retarded logic that EVERYTHING a silicon does on non-Asimov is the fault of the uploader) and the laundry rountine of carding the AI is more present.

> It's a player problem, not a problem with the role

I disagree with this on the basis that an omniscient, quasi-omnipotent eye in the sky, even played PERFECTLY (as in, don't snitch on harmless antags, is not a cunt to people on purpose...) is still compelled by Asimov to hunt & kill that Vox trader or that vampire, and so on.
The traitor himself has no way to know if the AI will play nice or not and as such will be encouraged to take the AI out.
Finally, the AI remains due to its sheer power the number 1 priority on cult or revs. The flaw is within a role that is too powerful, rather than a player issue.

But because we can't have anything, here is 20 downvotes. Reminds me of that PR long ago to remove traitor AI.

**Comment by jknpj** [comment]
Not like this changes much, it just adds a middleman and removes malf as gamemode.

**Comment by ShiftyRail** [comment]
If milfies valids are an issue, they could be made as a mid-round ruleset.

**Comment by SonixApache** [comment]
make it a toggle

**Comment by Intigracy** [comment]
There's already a config option that does this.

EDIT: I'm retarded and didn't look at what was actually changed.

Funfact, even if merged this does nothing to the server, you have to convince Pomf (not collabs) they're worth removing.

**Comment by Exxion** [comment]
Yes, the OP says that it also requires a secret repo change
And collabs work too for that particular file

**Comment by Intigracy** [comment]
Config isn't on the SR that I see.

**Comment by Exxion** [comment]
It's `config.txt` in the directory `config`
Are you on the right branch?

**Pull request closed without merging**
