### PR TITLE
Fixes drowsyness.

### LINKED ISSUE #10102: Decimal drowsiness causes you to be drowsy... forever.
Because oldcoders are just using a `--` to decrease it AND they check `if(drowsyness)`, so if it goes into negatives IT KEEPS GOING DOWN.

And the fun thing is a xenoarch artifact can cause this.

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes #10102 

~~Note: untested.~~

### CODE REVIEW

**Comment by ComicIronic** [comment]
> untested

NO MERGE

**Comment by PJB3005** [comment]
I wasn't intending it to be merged yet.

**Comment by ComicIronic** [comment]
Is this actually ready

**Comment by PJB3005** [comment]
Oh shit right I should test this.

**Comment by PJB3005** [comment]
Alright test it.

**Pull request merged**
