### PR TITLE
Stamped Cargo Manifest Reward Increase

### PR DESCRIPTION
**Pull request by jwhitak**
Stamping papers all day and getting only two credits per stamp? No. We need to reward the paperwork-obeying QMs. This PR will buff the stamped manifests reward to 5 credits (up from 2 credits). In effect, this will make returning a crate with a stamped manifest reward 10 credits (up from 7 credits).

This increase is relatively minor but rewards cargo folks who stamp and take care of their manifests instead of just burning them like savages looking for a little fire in their cave. It will urge them to carry their stamp on them, increasing the urge to want to use it for other things. Like paperwork.

[balance]
[gameplay]
[tweak]

:cl:
 * tweak: Stamped Cargo Manifests give 5 credits each (improved from 2 credits each)

### CODE REVIEW

**Comment by Kurfursten** [comment]
I don't see it. For most QMs, you will never run out of credits, I don't think 3 more credits will make the difference in increasing average QM paperwork.

However, what this DOES do is mean that you get paid more for returning the crate and paperwork than you pay for some items in cargo. For example, if you order a fuel tank and return the crate+manifest, you've just **made 2 credits** on top of the fuel tank. What this actually incentivizes is ordering an infinite amount of fuel tanks every shift.

**Comment by DeityLink** [comment]
Wait are fuel tanks really that cheap? There being cargo orders cheaper than crate+stamped manifest sounds like an issue in itself to me.

**Comment by Kurfursten** [comment]
Currently crate+stamped rewards 7, whereas reagent tanks (all of them) cost 8

**Comment by DeityLink** [comment]
Well I don't think people would complain much if their price went up by 2 credits. Even though imo it could go even higher. Regardless if they increase it to 10 capitalism will be safe.

**Comment by Eneocho** [comment]
If we're talking about making tons of credits as cargo there are far easier and faster ways than the stamped manifest+crate being returned, so this will have a very minor, possibly negligible effect.
Grinding for some extra 2 credits with the fueltanks as Kurfursten fears ain't really gonna happen, mainly because there are faster ways to make credits, the simplest being just making metal crates. Besides, you can already purchase fucktons of fueltanks (at a low low cost of 1 credit once you return the crate+manifest), so raising the manifest reward by two credits won't affect much, if at all.

**Comment by Kurfursten** [comment]
It's not about the fact that you can make money this way -- you can make money a LOT more efficiently by ordering a metal crate and crafting crates for a tidy profit. That's not the concern.

The concern is that this strongly encourages the mass fueltank gimmick which if anything should be an expense like buying multiple shards, not encouraged.

**Comment by jwhitak** [comment]
Fuel tanks should have their prices increased. That'll have to be a separate PR, it's outside of the scope of this one. (Seriously, 8 credits for a breaching explosive? There's gotta be shipping costs and overhead for that kind of thing...)

**Comment by Eneocho** [comment]
> The concern is that this strongly encourages the mass fueltank gimmick

Does it though? I've been playing cargo and observing cargo a lot lately and I haven't seen any attempt at a fueltank gimmick. I've only seen like 6 fueltank memeries the last 15 months, and 2 or 3 of em were made by antags that got the idea from an emagged silicon, the others were made by non-antag clowns/mimes/assistants that couldn't access that QM cash anyway.

**Comment by Eneocho** [comment]
As I mentioned on Kurf's PR:
Reagent tanks come in wooden crates. You can't send those boxes back since you turn em into wooden planks when opening the box meaning you don't ever get the reimburse thus no negative price.

**Pull request merged**
