### PR TITLE
Fixes #4195 (Adds flaps to podbay)

### LINKED ISSUE #4195: [Box] Pod bay could seriously use plastic flaps
~~Two-fold issue:
A) Spacepod fabrication used to need plasteel, but was changed to not need it. The stack of plasteel in the pod bay remains, and if it doesn't go unused the whole shift, it's snagged by Robotics. 
If you want to actually build a spacepod, though, you'll find that it requires about 8-12 sheets of glass, which is not available at podbay and not really readily available to civilians. So it ends up with arrivals windows being welded down into sheets.~~

B) Box uses a system of 2-wide airlocks for pod launching. This causes a few problems: Number one, you can only reach the "cycle to exterior" button from inside, which means you'd need someone ELSE to start the cycle for you. Number two, even with two large vent pumps, the depressurization cycle needed for the outer airlocks to open takes FOREVER. Both of these compounded end up in just "FORCE EXTERIOR DOOR" and since you can only do that from inside it ends up in the podbay being depressurized to launch the pod, 100% of the time. Come think of it I don't even think it's possible to dock with a pod while the exterior doors are open, since you can't reach the controls.
Meta solved both of these wonderfully well and in a wonderfully simple way.
ss 2015-04-29 at 11 35 41
Yes, it works. Yes, it's instant. Yes, we NEED this.

### PR DESCRIPTION
**Pull request by Intigracy**
Removes a stray wire in engineering while I'm at it.

Fixes #4195

### CODE REVIEW

**Comment by PJB3005** [comment]
:+1:

**Comment by Ephx1** [comment]
Podbay depressurizes arrivals every time because people are impatient as fuck. This is one of my favorite changes. Thank you so goddamn much.

**Comment by PJB3005** [comment]
You can probably remote the pipe meters in the podbay now too

**Comment by Intigracy** [comment]
merged on gitlab

**Pull request closed without merging**
