### PR TITLE
NEAR-INSTANT LIGHTING UPDATES.

### PR DESCRIPTION
**Pull request by PJB3005**
I just set the process interval way higher.

### CODE REVIEW

**Comment by ghost** [comment]
It's better than lights lagging behind people, for sure

We're going to need profiling done on this though

**Comment by 9600bauds** [comment]
Needs profiling I guess
Test merge it sometime

**Comment by clusterfack** [comment]
It's a bad idea

**Comment by PJB3005** [comment]
@clusterfack have you tried it?

**Comment by clusterfack** [comment]
No but I have profiled the current one on the server I know the cost wont be fully five times higher but if it was it would be way too high.

**Comment by PJB3005** [comment]
F

**Comment by ComicIronic** [comment]
F
We need an event-based lighting system for instant transmission.

**Comment by PJB3005** [comment]
What do you mean with event based?

I don't see how event based would make a difference. There's an instant updating system implemented (add a compile directive to one of the define files) and it works but the concern is things like explosions causing redundant updates and lagging.

**Pull request closed without merging**
