### PR TITLE
Readds two old hoodie colors

### PR DESCRIPTION
**Pull request by RealestEstate**
some people voiced that they wanted some of the old hoodie colors back.
re-adds the dark purple and dark green hoodies to suitvend.
[sprites]
:cl:
 * imageadd: The once available dark purple and dark green hoodies are back in stock again

### CODE REVIEW

**Comment by Dacendeth** [comment]
Yesss the dark purple was so nice.

**Comment by PrimeDSS13** [comment]
honestly I think most of the old colors were better 
who wants to wear eye flashingly brightly saturated clothing, it doesn't match anything

**Comment by gurfan** [comment]
> honestly I think most of the old colors were better who wants to wear eye flashingly brightly saturated clothing, it doesn't match anything

EKyef3DXkAgAPlf

**Comment by RealestEstate** [comment]
Well, there's no reason we can't have both. If there's an old color you want back in let me know and I'll add it to the PR.

**Pull request merged**
