### PR TITLE
Cricket Behind Fridge

### PR DESCRIPTION
**Pull request by Kurfursten**
🆑 
* rscadd: Sometimes crickets will appear behind refrigerators. Where's that noise coming from?

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I'm not sure it should be an event, especially since it's a silent one and it could take up other noticeable events.
Maybe a really, really rare chance?

**Comment by Eneocho** [comment]
Is there a way to breed crickets or are 4 crickets all you get?

**Comment by Kurfursten** [comment]
@Eneocho Crickets don't breed outside of the cricket farm, so it doesn't infringe on the trader but it's also a fun little crimket event. I also think it's pretty ambient to just hear an annoying cricket sometimes and have to hunt for it. Think of it more as atmosphere than an intended roach alternative for gunkburgering.

@boy2mantwicethefam That's a fair opinion to have. Personally I think events are remarkably all over the place. It doesn't interact with dynamic and there is no weighting to whether you get a rod, carps, a xenoqueen in the library, a vendor, wallrot, PDA spam, or vending machines throwing food. Some events just aren't impactful at all and the system is agnostic to that, only banning some events if you lack staffers (e.g.: meteors for engineers). I personally feel your complaint could be better addressed by improving the logic of the event system overall.

**Comment by Eneocho** [comment]
>Crickets don't breed outside of the cricket farm, so it doesn't infringe on the trader but it's also a fun little crimket event.

They totally could though, the farm is extremely convenient. Not only does it breed the crickets but it kills them without needing insecticide, butchers them immediately and can process them to get flour instead. Not to mention the speeds at which it refills itself with more crickets.
For comparison, breeding cockroaches is a slow process, after waiting to get some population going, you gotta kill the bugs with insecticide else they turn into splatters on the ground, once dead, you gotta manually butcher every single cockroach, which quickly becomes extremely time consuming (especially after the radial menu for butchering got merged, since you can't speedbutcher as fast anymore).
In the time it took you to get 30 slabs of cockroach meat, the cricket farm made 200+ slabs of cricket meat. Letting them breed outside the farm would let you have slow cricket meat production in case there are no traders (common on lowpop) and wouldn't really infringe on the trader, since the farm is orders of magnitude faster, such that you'd want it instead of ranching on your own.

**Comment by Hinaichigo** [comment]
Maybe events should be diversified into "major" and "minor" events or something and have separate calls on them. So there could be a lot of fun things like this that wouldn't necessarily use up potential for meteors or something to proc.

**Comment by Eneocho** [comment]
> Maybe events should be diversified into "major" and "minor" events or something and have separate calls on them. So there could be a lot of fun things like this that wouldn't necessarily use up potential for meteors or something to proc.

I'm liking this idea. It could segue into more "hey that's cool" events, instead of "GOD IS DEAD WE LIVE IN HELL" events.
For example: 
* A centcomm cargonian gets sent on the shuttle by accident, and since safeties prohibit the shuttle from taking living beings he's stuck as a station cargo tech until round end (maybe his id has extra centcomm access for post round fun).
* A research disk that was stuck on the RnD console falls off, you can clean this disk with soap then stick it in for anomaly research (or some other research level the station doesn't have yet).
* Samples from an experimental reanimating virus were accidentally sent to the station. One random dead and sentient guy revives as if nothing happened, but with a disease that will eventually turn him (and any other infected) into zombies (symptoms should be tame or even beneficial, but the last stage should start a timer that clearly implies you going feral).
* Engineering finds a supermatter splinter hidden somewhere on poly's nest (spawns a sm splinter under poly).
* Botany finds a few randomly spliced seeds under the Bioballistic Delivery System (completely randomized genes and traits, think exotic seeds but with no safeguards or weights).
* Clown finds a bananium coin stuck under his shoe! It was stuck with years old clown-grade chewing gum, so you'll need to melt the shoe. Maybe make a metallic sound instead of clown squeaks every second step.
* The latest cigarette delivery was tampered, all cigarettes bought from currently existing cigarette machines are dosed with 5u welder fuel (small, mostly harmless explosion).
* NT's contract with Discount Dan was kept off the books. To keep the auditors from finding out about this extra money, all Discount Dan and Groans Soda vendors will not vend until further notice (they can still throw stuff).
* A subspace tunneler appears in the telescience pad with random machines and items inside its matter bin. You could get a bag of holding just as much as you could get an active syndie grenade. Do you feel lucky?
* A massive psionic wave of unknown origin affects the crew for a few minutes. For this period, the entire station is mirrored (mirror the viewport).
* A blood tear mob (that one that just drips blood everywhere) leaps out of a sudden rift in spacetime somewhere in the halls.
* A vial with 10u peridaxon was jammed on one of the medbay scrubbers. This singular scrubber is not working (use the red sprite). If someone disassembles the thing they'll find the peridaxon vial.

**Comment by Exxion** [comment]
Small, silent events like this one could be super common without being disruptive if there were enough of them to keep them from getting old
So basically we should make more of them instead of specifically avoiding making them
And also make some change to the event logic, but I'm not sure just the two categories of major and minor would be descriptive enough

**Pull request merged**
