### PR TITLE
Fixes MaMi Sprite when posibrain slotted in

### PR DESCRIPTION
**Pull request by DeityLink**
Ever heard of perspective?
image

### CODE REVIEW

**Comment by SonixApache** [comment]
as a reminder, these were made publically  and easily available on Feb 23, 2017
it took at least two years and 5 months for someone to realize that the sprite was fugged

**Comment by DeityLink** [comment]
>easily available

well I guess most people gave up when they realized that
image

**Comment by ghost** [comment]
I think the joke is that nobody has ever actually used a MMANI in over 3 years of it being a thing

**Comment by DeityLink** [comment]
That is most likely the case. I found this bug by accident when opening its .dmi

**Pull request merged**
