### PR TITLE
Fixes 'global' windows xp startup

### LINKED ISSUE #20739: AI startup sound plays globally
#### Description of issue

[bugfix]
You can hear it in the lobby and as any role afaik
don't think this is intended

#### Difference between expected and actual behavior
screw in AI, room hears startup noise, rest doesn't
vs
screw in AI, entire universe hears startup noise

#### Steps to reproduce

Start as any role, have another client start as AI.

#### Length of time in which bug has been known to occur
since #19733

#### Server revision
869e7cbf5253c2d517f20239fe14b2c3008412a9

### PR DESCRIPTION
**Pull request by MadmanMartian**
At least, I think it should. Hard to tell during solo test

closes #20739

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Why ? It's a good way to tell if there is an AI on board.

**Comment by Exxion** [comment]
If you want that feature, it should actually be coded as a feature rather than as an inscrutable timing issue, for maintainability reasons

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
When are we gonna make silicons show up in the crew manifest already

**Comment by jknpj** [comment]
But they already appear in the PDA list

**Comment by bathosbathtime** [comment]
They can disable that and you can't check that in the lobby

**Pull request merged**
