### PR TITLE
VOX Update for October 8th, 2019

### LINKED ISSUE #24387: Requests for Next Batch of VOX Words and Announcements
Request VOX words and announcements here. These will be included in the next batch of VOX words/announcements, delivered on a (hopefully) regular basis.

**Current lists:** [announcements](https://github.com/N3X15/ss13-vox/blob/master/announcements.txt), [words](https://github.com/N3X15/ss13-vox/blob/master/voxwords.txt)

**Mispronunciations:** Lots, please fire me a note if you find one.

**Features**: Introduction of male voice and *possibly* a separate voice for automated announcements.

### PR DESCRIPTION
**Pull request by N3X15**
Closes #24387.

Includes:
* A bunch of new sounds
* A new masculine voice
* A browser dialogue for entering words, with word suggestions and idiot checks.
    
Tested locally on my Linux laptop.

# Screenshots

# Changelog
:cl:
* soundadd: Added more sounds to VOX, including a new masculine voicepack.
* rsc-add: Added a new word-entry dialogue with word suggestions, word count, and pre-validation.
* bugfix: Fixed sound effects being distorted.

[sound][content][qol]

### CODE REVIEW

**Comment by Kharkov72** [comment]
the absolute fucking madman

**Comment by ghost** [comment]
Finally, won't have to search up ultra contrived terms to make a coherent announcement as an AI

**Comment by N3X15** [comment]
There.  Rebased.  Still have some words to add from the requests issue.

**Comment by strawberrytan** [comment]
you absolute madman I've always wanted a way to search or filter the available terms

**Comment by SonixApache** [comment]
holy shit you absolute legend
this totally means we could add HL1vox as well

**Comment by ComradeDispenser** [comment]
Is the masculine voice the Half Life 1 vox or something else?

**Comment by N3X15** [comment]
We could, but the HL1 voiceset is extremely limited, which is why I came up with the festival-based system.

**Comment by N3X15** [comment]
The masculine voice is from festival, using the `rms` voice from NITECH ARCTIC.   It sounds like [this](https://www.nexisonline.net/downloads/vox_login-rms-processed.ogg), basically as close as I could get to HL1 VOX without devoting my life to it.

**Comment by Probe1** [comment]
Ready to merge?

**Comment by N3X15** [comment]
Yep.

**Comment by utilitas-** [comment]
Tested this any? Because in the last few rounds as AI, it played all the sounds in alphabetical order instead of the order typed.

**Comment by N3X15** [comment]
I typed in ass blast usa a few times and it worked fine.  It also did not change how the words are played, just added an extra dimension to the list.

**Comment by utilitas-** [comment]
A comes before B comes before U.
Now type usa blast ass.

**Comment by Probe1** [comment]
TEST MERGE!

**Comment by N3X15** [comment]
AI last round successfully announced "jesus christ is black", and local testing of the same word succeeded.  QED checkmate

**Pull request merged**
