### PR TITLE
Updates RD Console UI

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Replaces the RD Console's old UI to match most other UIs. Users can still search the window to quickly locate any items.
goodmat
badmat
blue
filtered

## Why it's good

Consistency, visual improvement

[ui]

## Changelog

:cl:
 * tweak: Modernized the RD Console UI.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
honestly it should have the black and green hackerman ui that mechs have

**Comment by Securitymain** [comment]
I was like "wow, how the hell did he port it to nanoUI/TGUI with 1 changed file?" Then I realized you only changed the inline css to change the colors to the ones of TGUI. You didnt replace any HTML, you only changed numbers around... so your description is wrong? Not like it matters. Looks good to me

**Comment by Eneocho** [comment]
Change the colours of the "required materials" text to green or something, that dark blue is hard to read against the grey background.

**Comment by west3436** [comment]
> I was like "wow, how the hell did he port it to nanoUI/TGUI with 1 changed file?" Then I realized you only changed the inline css to change the colors to the ones of TGUI. You didnt replace any HTML, you only changed numbers around... so your description is wrong? Not like it matters. Looks good to me

Yeah it's just the updated html template not nano or TGUI


> Change the colours of the "required materials" text to green or something, that dark blue is hard to read against the grey background.

The blue text only is used when bluespace matter bins are installed and it's really not that bad

**Comment by Eneocho** [comment]
it is really bad my guy, it's hard to read, at least make it a lighter blue, cyan perhaps

**Comment by Securitymain** [comment]
Seconding that it's really bad. I can't read it unless I move closer to the screen

**Comment by west3436** [comment]
blue
Updated the blue coloring, also in the OP

**Comment by Kurfursten** [comment]
I personally think this is ugly but maybe we should give it a trial run. If someone hates it they can click the revert button.

**Pull request merged**
