### PR TITLE
Adds two new recipes for whitebeets

### PR DESCRIPTION
**Pull request by KNB4002**
## What this does
Adds two new beet-related recipes: **pickled beets** and **rosolli** (a Finnish salad of root vegetables):

pickledbeets

Pickled beets is made with 5u of vinegar and 2 beets.

rosolli

Rosolli is made with 1 potato, 1 carrot, and 1 beet.

## Why it's good
Other than sugar, borscht and a salad there are not many recipes that include beets. This would give chefs slightly more of a reason to grow them. Also new food!

:cl:
 * rscadd: Added two new recipes that use whitebeets.
 * imageadd: Added sprites for those new recipes.

### CODE REVIEW

**Comment by BomberBro** [comment]
I like the sprites

**Comment by gurfan** [comment]
love it

**Comment by Eneocho** [comment]
I really like how the pickled beets look.

**Comment by Eneocho** [comment]
The pickled beets icon on your food.dmi file has no name.
image

**Comment by Hinaichigo** [comment]
> I really like how the pickled beets look.

I was about to comment this as well.. look so tasty lol.

**Comment by KNB4002** [comment]
> The pickled beets icon on your food.dmi file has no name.

Hopefully I fixed it.

**Comment by SECBATON-GRIFFON** [comment]
sburdo sbarde ebin sprololo perkele :DDDD

**Comment by Kurfursten** [comment]
icon conflicts (you may ping me if you want help on this)

**Comment by Kurfursten** [comment]
I told you how to fix it!

**Comment by Kurfursten** [comment]
FIX IT

**Comment by Eneocho** [comment]
I can take over and fix it for him, @Kurfursten, if you don't mind.

**Comment by Kurfursten** [comment]
Go ahead

**Comment by Eneocho** [comment]
Aight.

**Comment by Eneocho** [comment]
@Kurfursten Done.

**Pull request closed without merging**
