### PR TITLE
Gas maths stripping

### PR DESCRIPTION
**Pull request by ComicIronic**
Let's streamline this shit.

### CODE REVIEW

**Comment by clusterfack** [comment]
Issues with the present build
1. Zones are starting out freeeezing. Also they are leaking air somewhere somehow.
2. Adjust_gas wasn't accounting for temperature, bay uses adjust_gas_temp for this specific scenario. A good example would be the gas miners which output T20C gas.
3. Total moles is being added in set_gas, and everything is using set_gas directly or indirectly. The goal is to calculate total_moles only once. So if a single gas is manually being added it is done in set_gas, and if gas datums are being merged/removed the total moles of the datum is subtracted/added just once there.

**Comment by clusterfack** [comment]
I have found the initial issue with zones starting out freezing. None of the gases are calculating heat_capacity, since every heat capacity is 0 the initial zone temperature of 2.73K is the final value.

**Comment by ComicIronic** [comment]
I had it set the list instead of adding to it for heat capacity.  Try pushing a fix.

**Comment by ComicIronic** [comment]
> 2. Adjust_gas wasn't accounting for temperature, bay uses adjust_gas_temp for this specific scenario. A good example would be the gas miners which output T20C gas.

This is hardly an issue. adjust_gas is meant to account for modifying the gas numbers in a mixture, it doesn't actually deal with gas transfers from one mixture to another. If a machine wants to output gas at a specific temperature, it should be using mixtures and merging them.

**Comment by ComicIronic** [comment]
>Division by zero runtimes might also be the cause of the zone's gas "disappearance" if it is runtiming in the middle of procs with atmos machinery due to division by zero.

It does seem to be, because I made an oversight in not ensuring heat_capacity was always non-zero.

**Comment by clusterfack** [comment]
Making a new gas datum is 10 times as expensive per call as using set_gas one time

**Comment by clusterfack** [comment]
@ComicIronic It was from division by zero runtimes, I fixed the heat capacity issue and the gas disappearance issue went away. Also the temperatures are all fixed now.

**Comment by clusterfack** [comment]
Here is the final profile

**Pull request merged**
