### PR TITLE
Renamed whiskey

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
This time without being a fuckup

### CODE REVIEW

**Comment by Intigracy** [comment]
:+1:

You should really start using branches though.

Inb4 the autists that don't even play here.

**Comment by Arthurdentist** [comment]
I don't like the name and I actually play here.

**Comment by Intigracy** [comment]
I didn't mean you.

**Comment by Arthurdentist** [comment]
just re-iterating the fact

**Comment by Intigracy** [comment]
Though this honestly would be better if it were added to milk / milk's desc instead.

You know, since it has calcium.

**Comment by ShiggyPiggy** [comment]
Maybe I could change the description not to reference calcium.
My point was renaming whiskey, and also making it skele-themed.

**Comment by Iamgoofball** [comment]
seriously this should be milk

and why does whiskey need renamed, it's just gonna confuse bartenders

**Comment by Zth--** [comment]
I don't see the relation?
I like milk more

**Comment by IratePirate** [comment]
Pathetic.

**Comment by ConkerDev** [comment]
I :+1: because Im a huge faggot and I hate bartenders.
Also, because the original description is really baylike. Ew.

**Comment by Rei1226** [comment]
Yes. Ack Daniels is a way better name. Forget the autists whining about how it'll confuse people. If they're confused over what "Ack Daniels" is referencing they're probably not old enough to play on the server in the first place

**Comment by Iamgoofball** [comment]
motherfucker I get it's a play on Jack Daniels but the description makes it sound like its some kind of milk shit.

**Comment by AutismSpider** [comment]
Description makes it sound like milk drink make a better one.

**Comment by Rei1226** [comment]
Seems good now, merge when?

**Comment by Shadowmech88** [comment]
When the feature freeze is over.

**Comment by Rei1226** [comment]
wen

**Comment by Arthurdentist** [comment]
Never with any luck

**Comment by ShiggyPiggy** [comment]
Oh boy, I didn't know two lines of code could cause such controversy.

**Comment by Arthurdentist** [comment]
Such is life in spess

**Comment by clusterfack** [comment]
Don't really see why there cant be both drinks, just make a subtype with the different name/description?

**Comment by DeityLink** [comment]
I liked Uncle Git, until the idiot whose name was used actually came in the thread and turned out to be a retard. Ack Daniels is a fitting substitute.

**Comment by Shadowmech88** [comment]
Was Uncle Git really a reference to Dakka Git? I thought it was just coincidence.

**Comment by ShiggyPiggy** [comment]
I'm pretty sure it was, he's claimed it to be so in his unban thread.

**Comment by Shadowmech88** [comment]
How old is the player then? I don't remember seeing him on /vg/station until this year, but we've had Uncle Git's for the past couple of years, if memory serves.
What did he even do that was notable enough to have a reference to him?

**Comment by ShiggyPiggy** [comment]
He comes from TG, and I assume that is also where the name comes from.
Or...the notable event or whatever.

**Pull request closed without merging**
