### PR TITLE
makes apocalyptic meteors apocalyptic

### PR DESCRIPTION
**Pull request by SonixApache**
afaik these are only occasionally spawned by roulette revolvers - if this isn't the case, please say so, because then this probably shouldn't be merged ever
but yeah it makes them big and slow and makes whatever they hit disappear

### CODE REVIEW

**Comment by BomberBro** [comment]
I don't like the idea of a gun shooting maxcaps even if it's a low chance

**Comment by tuypo1** [comment]
I disagree and think it sounds like a great idea

**Comment by strawberrytan** [comment]
all meteor types can be spawned during forced meteor mode, if that's still a thing

**Comment by anunknownentity03** [comment]
so what its like a high yield rocket in the terms of damage or worse?

**Comment by SGuivenne** [comment]
I will say, Cluster Meteors already exist in the roulette gun and can fuck the station up royally, and precedent says firing a roulette gun makes you liable for whatever comes out the other end as you should know better.  Generally I've seen the big rule with the Roulette gun is unless whatever happens is either hilarious or inevitable you're getting dinged for it.

**Comment by Kharkov72** [comment]
yeah roulette revolvers can already shoot cluster meteors and fucking RODS I think we'll survive

**Comment by KingofHONK** [comment]
Horrible idea. Merge asap

**Pull request merged**
