### PR TITLE
berline event map

### PR DESCRIPTION
**Pull request by adacovsk**
Let me know what other features would be good for berline @KingofHONK 

image

## What this does
- admin wall through the station
- syndicate executives along the wall in space along with centcomm turrets
- arrivals is the only entry/exit, with HoP and sec stationed inside. Turret control and lockdown to surpress rioting
- red and blue onesies to determine side
- many exterior windows replaced with reinforced walls to avoid aggro of syndicate

## Why it's good
- event map

### CODE REVIEW

**Comment by Kromkar** [comment]
How many times do we need to teach you this lesson old man

**Comment by Theophrastus1** [comment]
image

**Comment by tinysaturn** [comment]
disconnect engineering and make it neutral Switzerland, let cargo and science figure out power for their sides.

**Comment by adacovsk** [comment]
> disconnect engineering and make it neutral Switzerland, let cargo and science figure out power for their sides.

I'd rather just remove the SME/AME/Singulo rooms

**Comment by DorainGrey** [comment]
> > disconnect engineering and make it neutral Switzerland, let cargo and science figure out power for their sides.
> 
> I'd rather just remove the SME/AME/Singulo rooms

What would be the point of even playing Engineering then?

**Comment by ConfusedCactus** [comment]
Downvoted because you are going to make a pr in 6 months that attempts to add this to rotation just like you did with line in the primetime pr.

**Comment by tinysaturn** [comment]
> > disconnect engineering and make it neutral Switzerland, let cargo and science figure out power for their sides.
> 
> I'd rather just remove the SME/AME/Singulo rooms

boring
imagine if this map had something interesting going on

**Comment by Kurfursten** [comment]
I'll say it: I don't think Nations gimmicks work in the first place. The station is supposed to work together. Each department gives its part. Engineering vs Medbay doesn't make any _sense_. They exchange services.

If someone really, really wants to make a nations map, they should make two small stations that have every department. Maybe they are asymmetric like one side has different engines than the other. Or one side has only individual prisoner cells whereas the other has only a perma/communal confinement. One side has sophisticated chems and surgery but no cloning, the other has only TUBES, cloner, and a lifetime supply of clonexadone. One side gets AI and the other gets unslaved borgs. It is completely possible to randomly assign a person to one station or the other during join logic. Or make them arrive in neutral zone and have competing HOPs advertise for job openings (perhaps this map has 2 HOP slots and no Captain).

**Comment by adacovsk** [comment]
> I'll say it: I don't think Nations gimmicks work in the first place.

this isn't nations, this is BERLIN i.e. a WALL. It's a little different. I thought it was fun when I played it last and people in the thread have brought it up

**Comment by adacovsk** [comment]
> boring imagine if this map had something interesting going on

>interesting

isolating engineering is interesting? I'm open to other recommendations. I'm gonna read more about East and West Germany to see what other neat features I can add

**Comment by Theophrastus1** [comment]
> > I'll say it: I don't think Nations gimmicks work in the first place.
> 
> this isn't nations, this is BERLIN i.e. a WALL. It's a little different. I thought it was fun when I played it last and people in the thread have brought it up

shut the hell up idiot

**Comment by SonixApache** [comment]
@Theophrastus1 this one is better
sotn

**Comment by KingofHONK** [comment]
> I'll say it: I don't think Nations gimmicks work in the first place. The station is supposed to work together. Each department gives its part. Engineering vs Medbay doesn't make any _sense_. They exchange services.
> 
> If someone really, really wants to make a nations map, they should make two small stations that have every department. Maybe they are asymmetric like one side has different engines than the other. Or one side has only individual prisoner cells whereas the other has only a perma/communal confinement. One side has sophisticated chems and surgery but no cloning, the other has only TUBES, cloner, and a lifetime supply of clonexadone. One side gets AI and the other gets unslaved borgs. It is completely possible to randomly assign a person to one station or the other during join logic. Or make them arrive in neutral zone and have competing HOPs advertise for job openings (perhaps this map has 2 HOP slots and no Captain).

I think that although this *might* be useful for a one time event meme, this suggestion (which likely falls WAY out of your scope im sure) is the best idea here. Id run the shit out of this.

**Comment by Theophrastus1** [comment]
> 

This is a much much better option than once again forcing your dogshit map down our throats in the guise of it being for the funny events

**Comment by Kurfursten** [comment]
@KingofHONK Should I merge this? Are you going to use it?

**Comment by Kurfursten** [comment]
Luzzy told me he would not use this on Discord

**Pull request closed without merging**
