### PR TITLE
Fixed syringe injections not checking for NO_INJECT

### LINKED ISSUE #16022: NO_INJECT Flag is Broken
It appears both golems and skeletons can be injected with syringes despite having this flag.

### PR DESCRIPTION
**Pull request by DamianX**
Fixes #16022

image

### CODE REVIEW

**Comment by SonixApache** [comment]
Aren't skeletons supposed to be able to be injected?
Doesn't the flag exist to prevent you from drawing blood from them?

**Comment by Exxion** [comment]
It's called `NO_INJECT`, not `NO_DRAW`

**Comment by Exxion** [comment]
Also they have `NO_BLOOD` or whatever for that

**Comment by Kurfursten** [comment]
I've been noticing a lot of good work in your PR history. Bugfixing is often thankless work and it doesn't get the big upvotes or recognition, but it is important. And people do care.

Thank you for your contributions to our codebase. 💯

**Pull request merged**
