### PR TITLE
Personal Airbags

### PR DESCRIPTION
**Pull request by Shadowmech88**
airbag_deflated airbag
Adds personal airbags. When carried in a player's belt slot or pockets, a personal airbag will deploy when the player is slammed against a dense object by ZAS, absorbing the damage as well as protecting the player from further damage for five seconds, at which point it will deflate and be deleted.

WebM of it in action: http://puu.sh/tKkpw/2aae9d6cf1.webm

:cl:
 * rscadd: Added personal airbags, single-use items which, when stored in one's pockets or belt slot, will deploy to protect you from being slammed into objects by ZAS. Personal airbags can occasionally be found in emergency toolboxes, or may be ordered from Cargo.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
I need ideas for where these should go. Cargo crate?

**Comment by SysadminJeroen** [comment]
Pretty cool, but perhaps the airbag should also give the player some hardcores when deleted so the player has 1 or 2 seconds to be able to interact with stuff.

**Comment by gbasood** [comment]
new meta

**Comment by kilozombie** [comment]
Add a chance for them to be in emergency lockers/toolboxes?

**Comment by eplgr** [comment]
AMAZING!
Idea: be able to attach them to your jumpsuit like you can with holomaps?
Something similar.

But should them be easily obtained? That's the real question.

**Comment by Shadowmech88** [comment]
If they were made jumpsuit accessories, there would be literally no downside to them.
I feel like you should at least have to sacrifice a pocket or belt slot in order to get one free pass on the ZAS slam jam.

**Comment by Kurfursten** [comment]
I think we have an "O2 emergency" crate that could use some more love, these could go in there.

Another random type of emcloset wouldn't hurt either

**Review by N3X15 — CHANGES_REQUESTED** [review]
Looks good codewise, but needs some text-based feedback.  Something like, 
```
to_chat(mob, "<span class='notice'>Your [src] deploys!</span>")
```

**Comment by gbasood** [comment]
`Your [src] deploys!`
lewd

**Comment by Shadowmech88** [comment]
Done.

**Review by N3X15 — APPROVED** [review]

**Review by PJB3005 — APPROVED** [review]

**Comment by Probe1** [comment]
Just toss em in a cargo crate for now if you can't decide where to put them.  If you do an emergency locker make it a low ass chance.

**Comment by Shadowmech88** [comment]
* Emergency toolboxes now have a 5% chance of containing a personal airbag.
* A crate of five personal airbags can now be ordered from Cargo for 25 credits.

**Pull request merged**
