### PR TITLE
Ports Messenger Bags from Bay

### PR DESCRIPTION
**Pull request by jknpj**
They look cool.

Normal: https://webmshare.com/7QJ6y
Security: https://webmshare.com/zWLqb
Engineering: https://webmshare.com/NdN41
Hydroponics: https://webmshare.com/0rnVd
Medical: https://webmshare.com/GZJRw
Science: https://webmshare.com/OV4jn
Captain: https://webmshare.com/Je48e

There are more but i don't feel like making more webms/gifs so just have a DMI preview:

msb1
msb2

:cl:
 * rscadd: Ports messenger bags from Bay

### CODE REVIEW

**Comment by Ephx1** [comment]
Those engineering and botany bags gave me cancer. Practically no shading.

**Comment by SkowronX** [comment]
They all look like trash. :-1: until proper resprite.

**Comment by yclatious** [comment]
Only the greyshit one looks good, all the others range from mediocre to shit, who the fuck sprited engie and botany bags, they look fucking awful, medical doesn't look too bad, but sec and the rest are just a big whopping no.

**Comment by Kitfox88** [comment]
I like em.

**Comment by Exxion** [comment]
The botany item sprite is just awful
The engineering one isn't good, but is leagues better than the botany one
The command one is pretty good
The rest are all pretty mediocre

The worn sprites are all fine except engineering

**Comment by SonixApache** [comment]
More bags, neat.

**Comment by Probe1** [comment]
@SkowronX get me better sprites

**Pull request merged**
