### PR TITLE
fuck window code, fixes #7023

### LINKED ISSUE #7023: Grills shocking even when covered with a window
(WEB REPORT BY: golfer45 REMOTE: 158.69.55.2:7777)
To reporduce this, break one of the grills above the bridge on box, walk to where the grill used to be. Now walk into the grills next to it, it will shock you even while covered in glass

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #7023 

I tried using a non hacky fix via putting a bunch of different procs here/in shock(), tried changing adjacent(), window code just sucks.

### CODE REVIEW

**Comment by clusterfack** [comment]
Use a variable that gets set when full tile windows get anchored on top of grilles

**Comment by Intigracy** [comment]
Wouldn't I also have to loop for it in New() for ones that spawn on the map?

**Comment by clusterfack** [comment]
Yes, but that isn't bloating move() code

**Comment by Intigracy** [comment]
Should I put it in fulltile window code, grille code, or both?

**Comment by clusterfack** [comment]
It'll likely have to be in both the new() of full tile windows and grilles, but only in the construction/deconstruction (anchoring) of full tile windows.

**Comment by clusterfack** [comment]
Personally though I was thinking of a completely different solution than yours that might work, giving it flags of ON_BORDER and then setting its dir to 15

**Comment by clusterfack** [comment]
Shame it probably uses dir for smoothing however

**Comment by Intigracy** [comment]
it does

**Comment by clusterfack** [comment]
Try it out with ON_BORDER though, I think thats a solid way to solve the problem since border objects are resolved before dense ones.

**Comment by Intigracy** [comment]
Full windows or grilles?

**Comment by Intigracy** [comment]
Also, won't giving fulltile windows ON_BORDER break shit like taser projectiles (which normally fizzle against windows) passing through them if coming from a different dir?

**Comment by Intigracy** [comment]
a real life grille!

**Comment by clusterfack** [comment]
Nah its dense so it'd probably be fine

**Comment by gbasood** [comment]
> Use a variable that gets set when full tile windows get anchored on top of grilles

Would you want to update this when a grille STOPPED being under a window?

**Comment by Intigracy** [comment]
I did every one I could think of.

qdeling a full window makes it turf check for a grille and update it accordingly, unanchoring/anchoring a window does the same, somehow unanchoring a grille that's under a window does (except by varediting shitmins).

The only one I could think of that would give this issue is pulling via singularity, but if it's been pulled you can still attack it with tools to destroy it, not like bump matters since it's extremely unlikely it's under a powered wire at that point.

**Comment by gbasood** [comment]
WHAT COULD GO WROOOOOONG

**Comment by gbasood** [comment]
actually @clusterfack thinks he knows of a better solution
Someone should probably try it
And then we can revert this hacky method afterwards

**Comment by Intigracy** [comment]
bandaid fix is better than no fix at all tbh fam, I don't mind this getting reverted if someone codes a better solution.

**Comment by gbasood** [comment]
Kill it with fire

**Comment by Intigracy** [comment]
sorry bb

**Pull request merged**
