### PR TITLE
Adds tobacco to cigarettes and similar items.

### PR DESCRIPTION
**Pull request by DrSnips**
Cigarettes and other items you can smoke currently come empty and that seems a bit silly. Tobacco has been added to them to give them a bit of flavor.
:cl:
 * rscadd: Cigarettes now come with tobacco in them for a true smoking experience.

### CODE REVIEW

**Comment by imw-Oculus** [comment]
So is cancer back in use? If not, I suggest just damaging the lungs on a prob(1). Some other small buff like reducing drowsiness would be nice as well. I also suggest not just adding Discount Dan tobacco as a meme.  Maybe with a prob(5) instead of the prob(1) for non-discount cigarettes.

My concern is that people will just stop using the item, because it's mechanically only a negative.

**Comment by DrSnips** [comment]
Cancer has always been around it's just unused because it's a death sentence. I will likely remove the normal type causing cancer however

**Comment by SonixApache** [comment]
phalanximine, ho!

\*edit*
as fun (and probably actually good, if you include some sort of positive effect to tobacco) as this is, it **does** limit the amount of chems you can put in cigarettes.

**Comment by Probe1** [comment]
Thats fine cigarettes are dumb as fuck.  They're just smokable reagent holders as is.

**Comment by FudgePucker** [comment]
Make it so tobacco breaks down into nicotine then I would agree with this change.

**Comment by FudgePucker** [comment]
One concern, nicotine is a rename of that one chem that reduces stuns and treats holusinations, it also deals a lot of toxins damage even at low doseges.
Dionia are going to roll spliffs to smoke, but will a single cigarette kill your kidneys without constant antitoxin doses?

**Comment by DrSnips** [comment]
Well I intended this to be with the april fools PRs but that's come and gone now. Tobacco will just be a flavor chem with no actual effect Im thinking.

**Comment by Probe1** [comment]
Some fucker forgot to tag it as honk.  I'm sorry.

**Comment by Probe1** [comment]
WIP or ready for review?

**Comment by DrSnips** [comment]
Ready to review. Tobacco is just a flavor chem now. Maybe someone can add some desired flavor text later or give it an effect but cigarettes are currently flavor only so I'm going to leave their contents as flavor only.

**Pull request merged**
