### PR TITLE
Box fixes

### LINKED ISSUE #7747: [Box] This one single conveyor belt switch is multidirectional, needs to be /onedir
Related to #6923 
space_station_13_2016-01-17_19-39-06
What's happening there is that when the lever is first touched, it will cause the conveyor to send the ores AWAY from where they're supposed to go.
This switch needs to have convdir set to -1

### LINKED ISSUE #8230: [box] Science outpost dorm 1 button
On box, the button to bolt airlock in science outpost dorm 1 doesn't bolt the airlock.

Possibly affects meta.

### LINKED ISSUE #8861: [Box] Needs to be a vent/scrubber on this side of recycling, or plastic flaps that let air through
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
See the problem?

The vent and scrubber only reach 1 side of the glass.  http://i.imgur.com/GluvfGX.png

### LINKED ISSUE #8941: Missing sound system
On Boxstation, you can hear jukebox music in all other hallways, but the Port Primary Hallway zone (near the primary tool storage) misses a sound system.

### LINKED ISSUE #9190: CargoBay fire alarm hard to reach
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 6479e75b23d28ac1d05fbca0ea463a367759ea6c
> 
> General description of the issue
> https://i.gyazo.com/ad250cb224e2c9fd1aa7debfdbc3d96f.png
> Fire alarm can only be reached by standing on the delivery chute tile
> What you expected to happen
> Fire alarm easy to reach in case of false alert
> 
> What actually happened
> You need to open a windoor, climb into a chute and then climb out of it to turn it off

Personally I think locating it on the same wall but facing East would be a lot better.

> Steps to reproduce if possible

### LINKED ISSUE #9272: Unreachable extinguisher cabinet
#### Description of issue

inside boxstation's medbay there is an unreachable extinguisher cabinet
#### Difference between expected and actual behavior

that i could take the extinguisher, but i couldn't, because you need to stand in an adjacent tile to take it
#### Specific information for locating

west of the body scanners, near the medical records computer

extinguisher cabinet
#### Length of time in which bug has been known to occur

i saw it today, tested again in the testing server
#### Server revision

d7d60e9f5ecb176cc98335588f3f39a78a3d41d4
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Probe1**
### Bug Fixes

**Adds** scrubbers and vents in recycling to get full room coverage
**Fixes** dorm button in the research outpost.
**Fixes** mining outside conveyor using bauds recommended fix.  See image for complex solution https://github.com/d3athrow/vgstation13/pull/9217#issuecomment-204957999
**Fixes**   Fixes a fire extinguisher in medbay that was inaccessible behind a table. I placed it on the same tile as the table and varedited x_pixel to -32. Interestingly none of the medbay fire extinguishers had this offset pixel treatment. Most wall objects do, it's very odd that fire extinguishers did not.
### Tweaks

**Tweaks** a fire alarm in cargo to be accessible
**Tweaks** floor_types.dm to remove the temperature definition of nitrogen floors as part of the resolution of [2384]
**Tweaks** floor tiles in the supermatter room to nitrogen flooring.  They will now have 103kpa 20 C pressure/temperature at round start so opening the airlock will no longer blow everything the fuck around
**Replaces** the courtroom window door with IAA/Lawyer access in addition to brig access so lawyers can enter the court on their own.  Based on thread feedback.  https://github.com/d3athrow/vgstation13/pull/9217#issuecomment-204978565
**Replaces** the rwindows that faced maintenance in the RDs office with the rwalls that were there originally.
**Replaces** the research outpost toilet with a washing machine.  Toilets are for assistants and rp.  Washing machines are for scrubbing the plasma out of your clothing before you die.
**Moves** the genetics request console to be adjacent to the genetics consoles so geneticists will actually see it.
### Additions

**Adds** sound system to Port Hallway
**Adds** a camera outside the library based on thread feedback https://github.com/d3athrow/vgstation13/pull/9217#issuecomment-204958670
**Adds** two additional cameras outside the solar access doors in the fore of the station.  They are named Fore Port Solar Access and Fore Starboard Solar Access.  This mirrors the Aft half of the stations already existing camera coverage.
**Adds** a speaker tuned to medical frequency and turned on to the cloning room so neglected clonee players can cry about the doctors before they pass out.

Fixes https://github.com/d3athrow/vgstation13/issues/9272
Fixes https://github.com/d3athrow/vgstation13/issues/8861
Fixes https://github.com/d3athrow/vgstation13/issues/9190
Fixes https://github.com/d3athrow/vgstation13/issues/8230
Fixes https://github.com/d3athrow/vgstation13/issues/7747
Resolves https://github.com/d3athrow/vgstation13/issues/8941
Half-Addresses https://github.com/d3athrow/vgstation13/issues/2384 Meta will still need touched up.

### CODE REVIEW

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/issues/7747 's recommended fix causes a new issue.  The lever only works one direction so your ore box gets trapped underneath the plastic flaps and you have to turn it off, ctrl click, pull the box out.  100% clunk.  I decided the best course of action is to incorporate the fix but redesign the input area.

old
04a9d63e-bd52-11e5-8668-9365f23ec71a

new
image

**Comment by Probe1** [comment]
Adds a camera here to fix missing camera coverage for the AI.  "Starboard Primary Hallway Library".  Also changes the name of Starboard Primary Hallway 4 to "" Hallway Robotics to follow the existing naming convention

image

**Comment by Probe1** [comment]
Courtroom windoor is now IAA accessible so they can enter.  The windoor for the accused remains as it was so they can't sneak away with their clients.

image

**Comment by Probe1** [comment]
Commits are squished, PR is tested, if anyone has any additions let me know.  These are the ones I feel I can cover for Box and I"m shifting my attention to metaclub.

**Comment by PJB3005** [comment]
@Probe1 you don't have to squash commits yourself anymore, GitHub does it for us now.

**Comment by Probe1** [comment]
REALLY now that is useful.

**Comment by CptWad** [comment]
off the top of my head

- Could you remove the RD's windows to maint and replace them with rwalls?
- A camera is missing at the northeast solars. There needs to be one in maint

**Comment by Probe1** [comment]
@CptWad Did you place those windows?  WHO DID?  I was gonna poll the server about that before making the change myself.

**Comment by CptWad** [comment]
yeah no its not supposed to be there, it was either me or dylan but I will say me because I changed shit first.
If anything I put it there accidently when doing shit which is weird because I never worked around the RD office so its a mystery :ghost:

**Comment by Probe1** [comment]
Alright I'll switch it back.  I never knew why it was changed but it was a dumb change.  I didn't want to start balancing shit on my own without asking first.

**Comment by CptWad** [comment]
there is absolutely no reason for it to be there so yeah change it thanks

**Comment by Probe1** [comment]
Polled in game, almost unanimous support for rwalls so I feel safe assuming that further polls with have similar majority results against it.  Plus neither Dylan or CptWad can remember changing it so it's a fucking mystery that we're gonna bury as soon as I go back inside.

**Comment by Probe1** [comment]
```
Replaces the toilet at the Research Outpost with a washing machine.  Thread request
```

**Comment by Probe1** [comment]
I suppose I need to test this again since it's been 5 commits since.  If no one has any objections by tomorrow afternoon please merge.  I'll test it again in the morning.

At this point I'm just grabbing up new issues as they're made and adding them in.

**Comment by Probe1** [comment]
Finished, tested each change, ready to merge.

**Pull request merged**
