### PR TITLE
Replaces tank dispenser UI with radial menu

### PR DESCRIPTION
**Pull request by ghost**
[qol][ui][sprites]
animated2
Also makes it easier to set custom angle offsets in menu rotation during creation.
:cl:
 * tweak: Tank dispensers now use radial menus for taking tanks.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
what does it look like

**Comment by ghost** [comment]
> what does it look like

Updated it with gif example

**Comment by Eneocho** [comment]
Very nice.

**Comment by Kurfursten** [comment]
I'm surprised this is received so poorly. Anyone want to elaborate on why they voted down?

I don't feel strongly either way but I am curious.

**Comment by Pancakemines** [comment]
I can't speak for them but if I were to downvote it'd probably be because the current UI shows available tanks so you're losing that functionality and have to eyeball the sprite which the menu blocks when it's open which is a little annoying. Radial menus also in my experience don't function well with either my inputs not going through or them being tempermental and closing when I don't want them to or opening when I don't want them to, but in this case at least that's a tradeoff for when the uis never load.

**Comment by Eneocho** [comment]
Rewatch the gif on the OP and you'll see that the radial UI has a number to mention how many tanks are currently on.

**Comment by ghost** [comment]
Updated OP with much clearer GIF showing numbers

**Comment by SonixApache** [comment]
this is nice but what if ctrl/alt+click shortcuts

**Comment by Eneocho** [comment]
That reminds me, the alt+click shortcut for APCs and Air Alarms is also the shortcut to check everything on the tile, thus changing your tab from whatever to the floor tab.

**Comment by Kurfursten** [comment]
Personally I think it's fine but the votes are against you

**Pull request closed without merging**
