### PR TITLE
Diseases now don't autocure over time.

### LINKED ISSUE #14300: Viruses cure themselves after extended periods of time
This is dumb, especially if you make a beneficial virus that nobody wants cured.
It's even worse since you have to wait a long time until stage 4. We could introduce some better QoL changes to virology before we're forced to do an overhaul or ignore it forever.

### LINKED ISSUE #15307: Virus is broken completely now
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
When you contract a virus your body develops the antigens instantly which makes it useless. You don't even need radium or a doctor. It just autocures itself at stage one.

pls fix

### LINKED ISSUE #20147: Natural antibodies
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
They're the most broken part of virus feature and it basically makes beneficial viruses pointless. This is already besides the fact that malignant viruses are weak as shit compared to the effort it takes to get rid of them even without the natural antibodies.

### PR DESCRIPTION
**Pull request by MadmanMartian**
closes #14300
closes #20147
closes #15307
you want cure? Go to chemist. Drink radioactive waste.

:cl:
 * tweak: An impurity in the cloning process of personnel has led to a weakened immune system. This means diseases now no longer cure themselves, so they require medical expertise to cure.

### CODE REVIEW

**Comment by SonixApache** [comment]
- [x] 🆑

**Comment by SGuivenne** [comment]
I've got no complaints, if its a hostile disease it'll kill/incapacitate you/turn you into a furry long before it self cures, at which point the self curage is irrelevant.   This only makes beneficial diseases viable.

That said, we may need a patch note about how all spacemen are now immuno-deficient.

**Comment by ghost** [comment]
The PR that saved viro.

**Comment by Shadowmech88** [comment]
Immuno-deficient or not, no human immune system is going to completely clear out a virus in just a few hours.

**Pull request merged**
