### PR TITLE
Fix Grinch

### LINKED ISSUE #21176: Two grinch bugs
oh god when you put a law in the planning frame it fucks you up. it fucks you up bad. No more vent crawling for you mr

ID in hand? that shit don't work. don't open doors or lockers. didn't test buying anything

### LINKED ISSUE #21194: More Grinch bugs
- Midround ghost polling Grinch doesn't seem to spawn with a backpack.

- Grinch can't even drop items. Have fun finding a rack or something and not being able to ventcrawl.

- Grinch polling for ghosts has a wonky sentence that goes sort of like this: "Apply for datums/gamemode/role/grinch".

### LINKED ISSUE #21196: Grinch can't put things down
(WEB REPORT BY: kharkov72 REMOTE: 206.221.180.138:7777)
# Revision
32be4e48eaea414d879badb2cb6583d08b8abea5

# Description
While using hotkeys, I tried to drop some things in order to stash them away, and all I got was
This mob type cannot drop items.
You can still throw things to put them down though, but this just feels like an odd oversight.
ESPECIALLY because the actual button for dropping things on the UI (Next to throw) works, but using the hotkey for it doesn't.

#Steps to reproduce
Just turn into a grinch, turn on hotkeys and try to drop something (Like a radio) with the bound hotkey

### LINKED ISSUE #21257: Becoming the grinch: nullspace no-control edition
#### Description of issue
was a autotraitored posibrain
got put in a borg shell
died
ghosted
got polled for grinch, poll immediately closed when i applied
didn't actually get pulled as grinch
found an AI grinch feeling up walls
grinch got robusted
tried to re-enter corpse, ended up in dead grinch
went back to where I died to look at my old body but it was gone
kurfursten did a lookup and found my borg body in nullspace
[bugfix]

#### Server revision
69b5c5b6808562168fbd1494efcc5bd70865f458

### LINKED ISSUE #25285: Admin spawning a grinch midround causes mustard gas
>Try to midround spawn a grinch
>Pulls the guy but shoves him in a naked dude instead

```
proc name: OnPostSetup (/datum/role/grinch/OnPostSetup)
usr: Kolton Hunt (kharkov72) (/mob/dead/observer)
usr.loc: The wall (345, 256, 1) (/turf/simulated/wall)
src: The Grinch (/datum/role/grinch)
call stack:
The Grinch (/datum/role/grinch): OnPostSetup()
The Grinch (/datum/dynamic_ruleset/midround/from_ghosts/grinch): setup role(The Grinch (/datum/role/grinch))
The Grinch (/datum/dynamic_ruleset/midround/from_ghosts/grinch): finish setup(Jaylen Mccullough (/mob/living/carbon/human), 1)
The Grinch (/datum/dynamic_ruleset/midround/from_ghosts/grinch): review applications()
The Grinch (/datum/dynamic_ruleset/midround/from_ghosts/grinch): send applications(/list (/list))
```

### LINKED ISSUE #28326: The Grinch Stole My Soul
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
9c11db3ad5517d57df1c857ab5486f04c18f7e12

# Description

Applied to be Grinch, it runtimed repeatedly, Chaz decided to triple down. When selected my Character name changed, and I went from a ghost to a naked ghost, instead of becoming the Grinch.
# Steps to Reproduce

Sign up for Grinch, be selected for grinch, cease to be you and be someone elses naked ghost
# What you Expected

To be grinch
# What Actually Happened

I'm now a ghost, but a different one, and not even the ghost of Christmas Past, Present, or Future.

### LINKED ISSUE #31671: Grinch
The mode is looking for volunteers to become The Grinch. (Apply now!)
Added to the The Grinch registration list.
Applications for The Grinch are now closed.
>Grinch standing around hitting walls at the spawn location

#### Description of issue
Expected to be a grinch, but instead a AI mob was spawned. Died as a catbeast, then tried to be a midround grinch

Endgame credits (for troubleshooting):
was Nyanners (died as grinch)
Objective 1: Stay alive on the station for five minutes. Success!
Objective 2: Defile 30 rooms by entering them. Success!
The loose catbeast was successful!The catbeast survived on station for 1474 seconds, defiled 40 rooms, and generated 44 threat!
 was Nyanners (died as grinch)
Objective 1: Tis the season. And you are here to ruin it. Disrupt Christmas and steal the crew's valuables. 
The Grinch managed to steal $0 worth of items!

#### Steps to reproduce
Dynamic gamemode rolling Grinch

#### Length of time in which bug has been known to occur
See #31548 and #31590

#### Server revision
Game: 552d870af550fda58189a4cc0a136b70e0361e5d 
Patches: d2d8284cefe331992a20db0f4fedb3e1b63c7713

### LINKED ISSUE #31726: Grinch AI
(WEB REPORT BY: uchla REMOTE: 206.221.180.138:7777)
# Revision
aa9a3b8c030e2bf4906724cf3f183bf7ab0c7089

# Description
I signed up to be Grinch and it made an AI Grinch and said I was the Grinch after the round ended
# Steps to Reproduce
sign up as grinch, maybe also be on the asteroid
# What you Expected
to play as ther Grinch
# What Actually Happened
I was still a ghost and an AI was the grinch and did nothing

### LINKED ISSUE #33852: Grinch is borked
(WEB REPORT BY: korthe REMOTE: 206.221.180.138:7777)
# Revision
47f3f79da37e614437b1d77e133aa21348bcaa67

# Description
Not only do grinches not spawn in the player they selected, they cannot pick shit up and have no bag to put the things you can't pick up in.
# Steps to Reproduce
insert yourself into a grinch
# What you Expected
to have a jolly fun time picking things up and putting them in a bag
# What Actually Happened
I could just fuck with electronics and ventcrawl, I could not to anything else

### PR DESCRIPTION
**Pull request by gurfan**
Closes #33852
Closes #31726
Closes #31671
Closes #28326
Closes #25285
Closes #21257
Closes #21196
Closes #21194
Closes #21176 (maybe?)

## What this does
fixes grinch not spawning correctly and being unable to pick anything up
and also being unable to drop things using Q

## Why it's good
Because people want to play grinch

## Changelog

:cl:
 * bugfix: Fixed the grinch ruleset.

### CODE REVIEW

**Comment by gurfan** [comment]
Lot more broken than I thought

**Comment by nervere** [comment]
Closes #33852

**Comment by boy2mantwicethefam** [comment]
You have to add the "closes (PR)" in the PR itself

**Comment by adacovsk** [comment]
> Closes #33852

there's a bunch of other grinch issues open too

**Comment by Killette2** [comment]
Give grinch health regen, a cap only has to hit a few lasers during the entire round. They also have sucky pressure resist when their main method of transportation is vents, which also stacks on the no health regen problem

**Comment by gurfan** [comment]
> Give grinch health regen, a cap only has to hit a few lasers during the entire round. They also have sucky pressure resist when their main method of transportation is vents, which also stacks on the no health regen problem

I'm just handling the most basic of fixes in this PR, for atomicity.

**Pull request merged**
