### PR TITLE
Reworked money bags

### LINKED ISSUE #7668: Coin bags, an ode to terrible code
These bags are the result of another piece of bad and hard code machinery named "coin press".
- Money bags are accessed to take coins by clicking on them, and can be picked up by dragging the sprite onto oneself.
- Once on-hand, clicking on it with one's free hand will allow the person owning that hand to enter the menu, but nothing if one uses the same hand that holds the bag.

Now this is when it gets tricky
To change the bag from one hand to another, one can
- Drop it and get it with the other hand
- _If and only If it_ is on the **Left hand**, the bag can be dragged into the character's sprite
  - If it is on **the Right** hand the bag will simply drop to the floor

Not so bad huh?
- After dragging the bag onto self from any hand slot, _the bag stays on the original hand, and wherever the bag is, if the user uses the drop command on a hand, the bag **teleports back to the character**_
  - Passing the bag from Left to Right and dropping it _still leaves the bag in the Left hand, being able to recall it at any time with drop_
  - If the bag falls to the floor after dragging it from the Right hand, one can _drop from this hand to phase it into self, and **repeat it with the left hand afterwards.**_
### And the player can't interact with anything as long as the invisible bag stays on the hand

death via moneybags

Also they don't have a sprite on hand so I can't look like a cartoon bank robber or Doctor Octopus on Spiderman 2

### PR DESCRIPTION
**Pull request by Zth--**
They're now a subtype of /storage/bags instead of some hardcoded shit.
Also I added them to the biogenerator, they cost 300.
fixes #7668

### CODE REVIEW

**Comment by Exxion** [comment]
Aw, no more teleporting bag magic shows
However, also no more stealing of your bag from your hands

**Comment by 9600bauds** [comment]
>can hold heads
?????

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
Why can it hold heads and ore?

**Comment by Zth--** [comment]
Ore because of gold, diamond, etc
Heads because I thought it was hilarious, I'm ok with removing it though

**Comment by FudgePucker** [comment]
:+1:

**Comment by gbasood** [comment]
I'd love a bag designed specifically for head-holding but probably not a money bag

**Comment by ghost** [comment]
I want a moneybag full of heads.

**Comment by Zth--** [comment]
Removed heads. This is ready to go

**Comment by clusterfack** [comment]
Oh, I forgot about this

**Pull request merged**
