### PR TITLE
More Packedstation fixes

### LINKED ISSUE #16908: Packed - Can't reach HoP chest drawer
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
58b5dde165c7ef46ad84db3fc2920cccd63194b8

# Description
There's a chest drawer in the HoP office, but to reach it you have to jump on the copying machine.
# Steps to Reproduce
Step into Packed's HoP office, attempt to put a piece of paper into the chest drawer
# What you Expected
Easy access to my paperwork.
# What Actually Happened
Jumping on office equipment.

### LINKED ISSUE #16909: Packed - Can't reach the paper table in the mechanics office
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
58b5dde165c7ef46ad84db3fc2920cccd63194b8

# Description
On packed, you cannot reach the table with the paper dispensers without opening the locker next to it.
# Steps to Reproduce
Step into the mechanics office, attempt to grab some paper.
# What you Expected
Paper in my hand, on demand.
# What Actually Happened
Required locker wizardry.

### LINKED ISSUE #16969: Lots of atmos/piping/vent mistakes and omissions in packedstation map.
Both sets of scrubbers in the captain's office and captain's quarters face south when they should face west, and thus start disconnected from their respective piping. Beneath the cigarette machine and beneath the rack.

The captain's office and quarters scrubbers also start out scrubbing plasma and oxygen, instead of plasma and CO2.

The unary vent that is supposed to serve as vent pump for the four tiles between the two sets of double-airlocks at the brig entrance begins the round turned off.

There is no air alarm in the brig proper to control the vents and scrubbers.

There is no air alarm in the detective's office.

The unary vent pump hidden beneath the equipment rack in the mining dock room in cargo is facing south when it should be facing north, and thus does not connect to air supply piping.

There is a stray "port maintenance" air alarm in the maintenance tunnel directly south of the pod bay. It does not control any vents or scrubbers. The existence of another maintenance air alarm in the central eastern part of the station that IS connected to a nearby vent and scrubber within maint tunnel probably suggests the stray one was intended to have its own vent and scrubber.

There is a redundant "Research Division Air Alarm" in the borer development room (as the airlocks name the small room), which controls the same vents and scrubber that are already controlled by the air alarm in the main research division hallway, on the outer wall of the RD's office.

The borer development room also lacks its own working scrubber connected to the waste piping, and instead has a scrubber connected to the isolated orange piping that borers are intended to crawl out of, except this scrubber is on by default and scrubbing the small room's atmos into its isolated piping, by mistake. It's also noteworthy that this little room is not properly designated as a separate area from "research division", for blueprint purposes, and lacks its own APC to power its equipment as well.

The center-most unary vent pump in the AI Upload Access room starts out facing west when it should face east, and thus isn't connected to any piping. Also there are two sets of vent pumps and two sets of scrubbers in the AI Upload Access room, for no discernable reason. It's quite a small room.

The courtroom vent pumps both start out turned off instead of on. The westernmost courtroom scrubber starts scrubbing only CO2, but not plasma, while the other correctly starts out scrubbing both.

The Quartermaster's office does not have its own vent pump or scrubber, and in fact the air and waste piping doesn't even come near the office. There is a redundant "Cargo Bay Air Alarm" inside this office which controls the same vents and scrubbers as the air alarm right outside in the main cargo bay area. The QM office does not seem to have its own blueprint area designation, nor APC or unique air alarm.

The scrubber in the Paramedic Station room near medbay begins the round scrubbing only CO2, but not plasma.

The Gateway room does not have its own air alarm.

### PR DESCRIPTION
**Pull request by PromethTK11**
Now with a new render:

Fixes #16969 
Closes #16909
Fixes #16908 

:cl:
 * bugfix: Packed: Fixed a lot of air alarms/vent/scrubbers issues on Packed, you can breath now.
 * tweak: Packed: You shouldn't be able to crowbar the AI core blast-door now.
 * rscadd: Packed: Added an evidence locker to brig for all your noir needs.
 * bugfix: Packed: The flash of the brig cells now should work properly.
 * rscadd: And various Packedstation misc fixes!

### CODE REVIEW

**Comment by Pathid** [comment]
About half of the main hallways still lack air alarms.

>Failure to have an Air Alarm in an area enclosed by firelocks will cause the firelocks to behave incorrectly, causing them to raise when there might still be hazards in the area.

**Comment by SonixApache** [comment]
What if you swap out the clothing locker and the copying machine in the HoP office?
Just kind of removing it, however unused and useless it may be, is pretty lame.

**Comment by Kurfursten** [comment]
1. Packstation needs a temperature monitor in tcoms
2. The MSGS units need to default to ON instead of OFF

I have skimmed the diff and can find no undeclared wadisms, so that's good

**Comment by DamianX** [comment]
Are you going to address the issues listed here?

**Comment by PromethTK11** [comment]
Yes, i'm on it

**Comment by PromethTK11** [comment]
Done

**Comment by Pathid** [comment]
Something I forgot to mention earlier: the kitchen is zoned as part of the bar, so there's no defined kitchen. So the vermin event for the kitchen (maybe the incinerator too, I don't see one) still fires and gives the message, but it can't find anywhere to spawn the mobs.
https://github.com/vgstation-coders/vgstation13/blob/949c674551ba85719a6e1019203ad9dbf6c68d04/code/modules/events/infestation.dm#L14
There's probably a way to fix it without affecting the actual map areas though.

**Comment by DamianX** [comment]
Are you going to fix that too? Why have we decided to report issues in a pull request anyway?

**Comment by PromethTK11** [comment]
I didn't knew that isses, wew.

Probably that one is out the scope of this PR, isn't?

Anyway for now i won't fix that but gonna make the issue :stuck_out_tongue:

**Pull request merged**
