### PR TITLE
Fixes ID cards in hands not being detected by vending machines

### LINKED ISSUE #17363: The "Pay" hotlink on vending machines no longer works with ID in hands.
#### Description of issue
IDnowork
Clicking the *Pay* link with your ID in either of your hands should process payment.
However, right now, clicking *Pay* without an ID in your ID slot doesn't do anything at all.

On a related note, you can no longer pay by clicking your ID on the machine itself, but that's more related to #17102.

#### Difference between expected and actual behavior
Hold ID in hand, click *Pay*, funds get deducted, I get coffee.
vs
Hold ID in hand, click *Pay*, nothing happens, machine waits for further input.

#### Steps to reproduce 
Attempt to acquire a product from a paid vending machine, try to pay by using your card.

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/machinery/vending.dm#L737

#### Length of time in which bug has been known to occur
Probably since the custom vending machine system (#15339), and it's probably related to #17102 and the ID card issues surrounding vending machines.

#### Server revision
0715cffed91239d5997051c7cc2ad3abc70de0a9

### PR DESCRIPTION
**Pull request by SonixApache**
~~get_all_slots() now also checks held_items on humans, this fixed the issue. This might fuck up something that used that proc, but I didn't see anything in testing.~~
Now checks hands in the `get_id_card()` proc. This has as consequence that you can open airlocks with an ID in your off-hand, but that's all.
Also made attacking the vending machine with an ID while it's waiting for payment pay for the item rather than try to set the linked account number.
Lastly, added a little message when hitting 'pay' without an ID.

Fixes #17363

:cl:
 - bugfix: Slapping vending machines with an ID to pay for a product now works again. That includes the 'Pay' button and touching your ID to the physical machine.

### CODE REVIEW

**Comment by gbasood** [comment]
~~Did you check if anything using get_all_slots is affected by this change?~~

I'm really good at reading comprehension today I guess

**Comment by gbasood** [comment]
Yeah you got some problems

```cs
//everything on the mob that is not in its pockets, hands and belt.
/mob/living/carbon/human/get_clothing_items(var/list/filter)
	if(!filter || !istype(filter))
		filter = get_all_slots()
	filter -= list(back,
				handcuffed,
				legcuffed,
				belt,
				wear_id,
				l_store,
				r_store,
				s_store)
	return filter
```

```dm
/mob/living/carbon/proc/internals_candidates() //These are checked IN ORDER.
	return get_all_slots() + held_items

/mob/living/carbon/human/internals_candidates() //Humans have a lot of slots, so let's give priority to some of them
	var/list/priority = list(s_store, back, belt, l_store, r_store)
	return priority | get_all_slots() | held_items //| operator ensures there are no duplicates
```

Finally, specifically, horror form transformation will now drop held items, although I'm not sure that was ever not the case
```dm
	for(var/obj/item/slot in H.get_all_slots())
		u_equip(slot, 1)
```

**Review by gbasood — CHANGES_REQUESTED** [review]
You need to actually check for things that'll break, since I've found at least one case that will

**Comment by gbasood** [comment]
Also while you're at it:
```dm
//everything on the mob that it isn't holding
/mob/proc/get_equipped_items()
    var/list/equipped = get_all_slots()
    equipped -= list(get_active_hand(), get_inactive_hand())
    return equipped

//everything on the mob that is not in its pockets, hands and belt.
/mob/proc/get_clothing_items()
    var/list/equipped = get_all_slots()
    equipped -= list(get_active_hand(), get_inactive_hand())
    return equipped
```
You could change these to just, you know, use `get_held_items` instead of individual hands

**Comment by SonixApache** [comment]
Okay, plan B, edits incoming.

**Comment by SonixApache** [comment]
Now checks hands in the `get_id_card()` proc. This has as consequence that you can open airlocks with an ID in your off-hand, but that's all.

Also @gbasood those two procs check in a specific sequence whereas `held_items` gives you right hand + left hand every time.

**Review by gbasood — APPROVED** [review]

**Pull request merged**
