### PR TITLE
silicate citrus fix

### PR DESCRIPTION
**Pull request by Eneocho**
I forgot the harvest_repeat line when making it.

[consistency][oversight]

:cl:
 * bugfix: Silicate Citrus is now reharvestable as intended.

### CODE REVIEW

**Comment by adacovsk** [comment]
why does this need to be reharvestable?

**Comment by Eneocho** [comment]
Because it is a tree. Trees are reharvestable (both IRL and in game). All 3 plants that can mutate into silicate citrus are reharvestable and we have consistency on mutated crops to still behave somewhat like their parent crops:
Golden and Cyanide apples are reharvestable because regular apples also are are. Diamond carrots are not reharvestable because regular carrots are not. It thus follows that since Lime, Lemons and Oranges are all reharvestable, their mutation should be as well. 
I had actually meant for them to be reharvestable but I forgot that one line.

**Comment by WindowsErrors** [comment]
they're reharvestable because they just are

**Comment by adacovsk** [comment]
> Because it is a tree. Trees are reharvestable (both IRL and in game). All 3 plants that can mutate into silicate citrus are reharvestable and we have consistency on mutated crops to still behave somewhat like their parent crops: Golden and Cyanide apples are reharvestable because regular apples also are are. Diamond carrots are not reharvestable because regular carrots are not. It thus follows that since Lime, Lemons and Oranges are all reharvestable, their mutation should be as well. I had actually meant for them to be reharvestable but I forgot that one line.

wouldn't it be overpowered though? maybe it should be a citrus shrubbery

**Comment by west3436** [comment]
> wouldn't it be overpowered though? maybe it should be a citrus shrubbery

can we please not be anal about balance regarding a fuckin silicate-producing tree that requires a mutation to get?

**Comment by WindowsErrors** [comment]
bro it's SILICATE, you spray it on the windows after people chimp out and smash them when they get stuck in the cargo disposals sorting room, what is "overpowered" about it?

**Comment by Eneocho** [comment]
Bro, you literally can buy tanks with 1000u silicate for like 15 credits. What's there to balance here? This is for consistency.

**Comment by adacovsk** [comment]
I guess I was just confused with the infinite plasma thing

**Comment by Eneocho** [comment]
That was a long and tedious splice I had made using the silicate citrus plant as host (I could've just as easily used peanuts or whatever).

**Pull request merged**
