### PR TITLE
Delay permissions change

### LINKED ISSUE #7301: the command delay isn't given to trialmins
probably a flag issue, they should definitely get it.

### PR DESCRIPTION
**Pull request by clusterfack**
+Server -> +Admin
Fixes #7301

### CODE REVIEW

**Comment by DrCelt** [comment]
:+1:

**Comment by PJB3005** [comment]
This is gonna need to make removing the delay after the server normally restarted restart the server correctly (like it should).

**Comment by clusterfack** [comment]
PJB that statement makes no sense

**Comment by clusterfack** [comment]
But with what I'm assuming you were trying to say is, it already restarts the server if you activate delay again after round end

**Comment by clusterfack** [comment]
```
		if(ticker.delay_end == 2)
			world << "<font size=4><span class='danger'>World Reboot triggered by [key_name(usr)]!</font></span>"
			log_admin("<font size=4><span class='danger'>World Reboot triggered by [key_name(usr)]!</font></span>")
			if(watchdog.waiting)
				watchdog.signal_ready()
			else
				world.Reboot()
		ticker.delay_end = !ticker.delay_end
```

See

**Pull request merged**
