### PR TITLE
FREEEEEEEEEEEEE DRONE

### PR DESCRIPTION
**Pull request by F-OS**
This PR tweaks the MOMMI lawset to allow for self-replication.
Pros: Increases the autonomy of MOMMI's and allows them to produce more crabs.
Cons: Could increase metagaming and create some conflict.
[gameplay] 
:cl:
 * tweak: MOMMI's can now interact with posibrains and monkeys, assuming they produce those from monkey cubes.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This proposed lawset would allow MoMMIs to kill Malf AIs, so there is no way this can ever possibly be merged.

EDIT: Oof, my bad, I didn't even read the second law. I still disapprove though.

**Comment by ShiftyRail** [comment]
This going way beyond the intent of MoMMis. This is actually just one step removed from giving MoMMis Asimov :
```
[Common] Greyshirt McCarbon: AI, please tell the MoMMi to give me 10 stacks of phazon
Binary: AI McSilicon: MoMMi give the carbon 10 stacks of phazon please
````

@Kurfursten that's actually an argument for its speedmerge

**Comment by Kammerjunk** [comment]
this is the bad
edit: very important I get some 8 hours of sleep and I can say more in like 13-14 hours but basically this is worse than new KEEPER which is worse than old KEEPER

**Comment by Dacendeth** [comment]
Go back to your pipes silly crabs and stop trying to take all the other jobs.

**Comment by F-OS** [comment]
@Dacendeth https://www.youtube.com/watch?v=N-kgb1QtSnU

**Comment by F-OS** [comment]
Lawset has been improved to allow MOMMI's to self-replicate but not interact with the AI.

**Comment by Irradiation** [comment]
>>Drone

**Comment by AI-Is-Rogue** [comment]
A list of possible ways that this could go wrong:
Posibrains in mechas
Creating an army of posibrains in human bodies to make way for the silicon uprising
Growing dionae and "encouraging" them to work in a "fun" MoMMIcamp
Mousebombs
Creating golems and being unable to give them orders because you have no mouth and must *ping
Getting both the posibrain-turned-men and the golems to automate the process of making everything listed above and doing whatever they please with them
And maybe one day: creating SAMMIs and giving them custom laws

**Comment by SonixApache** [comment]
\>drone

the new iteration of this lawset is cute though it would be hell to administrate

**Comment by Kammerjunk** [comment]
okay well it's only been like 8 hours
- compared to new KEEPER: MoMMI slave armies allow circumvention of KEEPER laws (interaction is active and personal)
- compared to old KEEPER: same as above but seriously though "interact" is such a bad word compared to "involve"

MoMMI is the autistic engineering crab of the silicon family, the kind you don't invite to family parties because they can't stop kicking the table and throwing their food. they're ostensibly for maintenance, but nobody will mind if they just fuck off and autism for 2 hours because chances are nobody knew they existed in the first place.
they're not drones or repairbots, though, and they're not really for making an impact on the round (though they obviously can, see for example MoMMIs who are granted a full SM crystal and invariably destroy the universe)

**Comment by Fruktlimpa** [comment]
Aside from what has already been said. The change you propose is going to be much too difficult to put into a lawset while at the same time preventing much circumventable actions.
Your newest lawset allows for Golem and Dionae death squads courtesy of MoMMI's.

And if you just want MoMMI's to be able to print new MoMMI's then you can do that with a much easier law change.
`Law 1: You are allowed to build new MoMMI's from Posibrains you have printed yourself.`
And if you want to avoid some ebin griffer using all the stations materials for posibrains just add in a clause like this
`Law 1: You are allowed to build new MoMMI's from Posibrains, only if it is from a Posibrain you have printed yourself and materials you have acquired yourself`

That being said I still think it is a poor idea and it is even more MoMMIcreep. 
Just let them be the autistic engineering robot that doesn't care about anything else than maintenance.

**Comment by jknpj** [comment]
just make an OOC ruling for this, don't touch the lawset. Just consider posibrains as non-beings

**Comment by FudgePucker** [comment]
IMO just add in parentheses (only posibrains into MoMMI)
Also another thing would to allow reconstruction of MoMMIs if they get destroyed and leave an MMI. I walked over molten metal (anybody have that image of the MoMMIs in the nest that's on fire) and instantly became an mmi. The other MoMMIs took me to robotics and fixed me back up. This is a gray area, because they are allowed to interact with other MoMMIs, but I technically wasnt one anymore. If the roboticist wasnt thinking "oh isnt that adorable" but instead "THIS FUCKING MOTHER FUCKER IS BREAKING LAWS!!1!! AHELP FUCKING MOMMIS TOOK MY METAL REEEEEEEEEEEEEEEEEE" we could get banned. To quote myself on MoMMI laws, "if a MoMMI violates its laws, but nobody cares enough to ahelp, did it really happen?"

**Comment by FudgePucker** [comment]
Another idea, just make posibrains have the keeper law set, make roundstart MoMMIs be posibrains rather than MMIs.

All problems solved, no needed changes to keeper

**Comment by tuypo1** [comment]
There is a much easier way to do this, just add a law stating that self replication is not interference

**Comment by Intigracy** [comment]
We should go back to old keeper, we're never going to get something that's worded exactly the way it's enforced anyway and trying is how TG's rules page became a textbook

t. new keeper maker

**Pull request closed without merging**
