### PR TITLE
Melee energy weapons can now "disarm"

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Does not work for the dual-wielded melee energy weapons
60% to lop off someone's arm on the spot depending on which one you target. You need to have the weapon active and to have disarm intent on while targeting an arm.
:cl:
 * rscadd: Added "disarming" interaction with melee energy weapons! You must have disarm intent, have the energy weapon active, and to target an arm to have a 60% chance of cutting it off on the spot!

### CODE REVIEW

**Comment by SirSkeleto** [comment]
doesn't melee weapon sharpness already accomplish this?

**Comment by SonixApache** [comment]
I thought you ment that attempting to disarm someone that was wielding an energy sword would result in you literally disarming yourself.
This is kind of silly, and the sharpness flags already let you do this, albeit slower.

**Comment by boy2mantwicethefam** [comment]
It's funny, also useful in a pinch
I still don't know where sharpness plays in limb tearing though

**Comment by Kevak** [comment]
~~I am _very_ leery about making energy weapons more damaging.  Energy weapons have always been designed around 'easy damage (burn), easy fix (kelotane)' where ballistics have always been designed around 'Less effective aiming (non-hitscan), hard to fix (internal bleeding, broken bones, gored limbs). I'm rather against giving eguns of any sort access to the 'hard to fix' category of damage. That just doesn't seem wise from a design standpoint. And a 60% chance no less! That's pretty absurd for a 20burn, nosharp gun.~~

Oh. I just realized. It's talking about eswords n shit. Belay that! Still a bit excessive when they already have sharp.

**Comment by Exxion** [comment]
Higher sharpness is higher chance to delimb, and lower minimum damage to do so
Sharpness 100 means instant and always, I think
It's also extremely rare for obvious reasons

**Comment by LordMyroc** [comment]
Why do we need a special snowflake function for this? Just target a limb and hack away.

**Comment by Exxion** [comment]
I also don't get the desire to take an already very powerful weapon and then buff it to the fucking moon

**Comment by Kurfursten** [comment]
This does not appear to have enough support to pass.

**Pull request closed without merging**
