### PR TITLE
Vampire Shapeshifting changes + Screech breaks light bulbs

### PR DESCRIPTION
**Pull request by adacovsk**
Right now I think changeling and vampire are a little too similar, so here's a start of something that differentiates them at least a little more

## What this does
- Instead of shapeshifting being similar to changeling's transform, I've made it so you turn into a vampire in your true form (which I took from umbra, which was formally grue)
- being a true vampire will hide your former jobbie identity and you can rapidly change when necessary
- hides you from cameras and easy identification although it's visually obvious what you are
- nerfed the former umbra (now vampire) and replaced old code
- make vampire vision work in the dark (it currently doesn't)
- the former umbra, former grue code is all still being used. The drainlight is used by grue, and I combined the break lights into the vampire screech

## Why it's good
- Hopefully one small step in the right direction with vampires
- fixes vision issues
- uses sprites that aren't currently being used
-  differentiates vampire from changeling a little

## Changelog

:cl:
 * rscadd: Reworked vampire's shapeshifting. When using Shapeshift, the vampire transforms into a "true vampire" that has vision in the dark. hides you from cameras, and hides your jobbie name.
 * rscadd: Vampire's Screech now breaks lights in a radius around the vampire.

### CODE REVIEW

**Comment by jwhitak** [comment]
Goodbye, Umbra, and 131 lines of code... including comments on the tiers of vampire spells?

**Comment by Hinaichigo** [comment]
Nice to diverge vamps from changelings a bit.

**Comment by Hinaichigo** [comment]
Oh yeah the umbras were a valid bodytype for the amalgamations/soul ramblers to pick body parts from, so maybe they could be removed from that list.. unless keeping them could be fun.

And also what do you think about giving them hair/beards?

**Comment by adacovsk** [comment]
> And also what do you think about giving them hair/beards?

Well, if you code dived a little, I am calling the vamps "Nosferatu" because they look like those guys and it also helps to differentiate them from normal people

**Comment by Blithering** [comment]
Widow's peak only.

**Comment by Hinaichigo** [comment]
White/grey hair only might be cool and still make them unique looking.

**Comment by Kurfursten** [comment]
Code end looks fine, kind of a shame to see Swallow Light go as it's a fun little gimmick spell. I guess it's trivial to bring it back if wanted.

**Pull request merged**
