### PR TITLE
double click to ventcrawl

### LINKED ISSUE #22900: [Feature Loss] Diona lacks dexterity to vent crawl?
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
43d8c3d3c30457234b5a8209203659655bf62150

# Description
Doubleclicking on airvents dont work anymore.
# Steps to Reproduce

Be diona, Doubleclick on air vent
# What you Expected

To begin entering the vent
# What Actually Happened

You don't have the dexterity to do this

### PR DESCRIPTION
**Pull request by DDihanov**
[qol]

Easiest update of my life. Closes #22900

:cl:
 * rscadd: Can now vent crawl with double click as well as alt click

### CODE REVIEW

**Comment by DamianX** [comment]
~~Does this need to check for incapacitation?~~
It doesn't.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Shouldn't this be an atmosobject-level proc?

**Comment by DDihanov** [comment]
> Shouldn't this be an atmosobject-level proc?

Yeah no, the vent-crawling logic has nothing to do with `attack_hand` like you would think, sadly. Whoever wrote it made it so user clicks on turf -> searches for vent on the turf -> if vent found then all is good

**Comment by jknpj** [comment]
Yeah but when they wrote that they didn't have layered vents

**Pull request merged**
