### PR TITLE
Nerfs fire

### LINKED ISSUE #33507: Fire is a bit strong.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
54def9f0766fe2cd8079a19fe067073509372aaf

# Description
Set myself on fire, died like 3 seconds after.
# Steps to Reproduce
Set yeself on fire
# What you Expected
to live for longer than 3 seconds
# What Actually Happened
*deathgasp

### LINKED ISSUE #33511: being on fire causes agony/pain even when in a hardsuit
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
d470ad71272d70468ddffbcb9b5cbd0e3e5521ef

title

### PR DESCRIPTION
**Pull request by west3436**
## What this does

- Removes agony from fire damage since severe burn damage already causes agony (closes #33511).
- Slightly reduces the damage rate for burning (closes #33507).
- Removes coughing while on fire (lol) and checks for protection before making you scream.

## Why it's good

I ran a series of tests to see the Time To Crit for the configuration before fire caused burn damage (historical), the currently-merged configuration (current), and the outcome of this PR (proposed). Tests were conducted as a standard-issue clown. Being set on fire but not in a fire tile was done by walking through a campfire, while staying in a fire tile was completed using Molotov's in the library.

Notes:
- Tested hardsuits to ensure no damage or other side effects of fire happen while you're in the suit on internals.
- Tested plasmamen taking their suits off (they can survive for about 2 minutes without their suit on so it's a non-issue).
image

## Changelog

:cl:
 * tweak: Removed agony damage from fire.
 * tweak: Slightly reduced damage caused from burning.
 * bugfix: You will no longer cough or get confused while burning in a hardsuit with adequate heat protection.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
I think burning damage is still pretty low as-is. I've been able to put myself out with stopdropandroll without much issue recently. I don't think it needs a nerf in terms of raw damage, but the pain damage and hardsuit changes are nice. Not sure about coughing, since wouldn't you still cough as long as there was smoke?

**Comment by PrimeDSS13** [comment]
good call it's a bit crazy right now , especially with how agony interacts with it
plus since you're the guy spearheading the changes I'll go with what you think is best for now

**Comment by west3436** [comment]
> I think burning damage is still pretty low as-is. I've been able to put myself out with stopdropandroll without much issue recently. I don't think it needs a nerf in terms of raw damage, but the pain damage and hardsuit changes are nice. Not sure about coughing, since wouldn't you still cough as long as there was smoke?

Just removing the agony actually didn't slow down time to crit at all, so it wasn't really doing anything. This nerf is pretty minor, just gives people a few more seconds to get extinguished since being on a fire tile is still very deadly. Correct, you'll already cough if you're in smoke.

**Comment by wotisjanitor** [comment]
I would say make a seperate PR for the hardsuit fixes, that seems like its own bugfix that should be handled seperately while people vote on this PR.

**Comment by Hinaichigo** [comment]
17 seconds is still pretty long in terms of a live round. Like in testing it might feel longer, but since you can get brained in 2 seconds with a revolver, stunned or disarmed and then killed in like 4 seconds, insta-ashed by the shard or insta-gibbed by the singularity, etc., I'd say 17 seconds is more than fine. I like the idea of it being really dangerous.

**Comment by Kurfursten** [comment]
Don't forget that it's 17 seconds of slow movement due to agony, possibly with collapsing.

**Comment by pedr69** [comment]
add soot onto the rig babies' hardsuit helmets while in a smoke cloud

**Comment by west3436** [comment]
> add soot onto the rig babies' hardsuit helmets while in a smoke cloud

sounds cool give overlay sprites

**Pull request merged**
