### PR TITLE
Adds a new chemical, Midazoline

### PR DESCRIPTION
**Pull request by help-maint**
## What is it?
A new chemical that someone posted the half-finished code for in the thread (it didn't work) so I went ahead and finished it.
Midazoline has no effect, except that it converts ALL chemicals it touches into more Midazoline.

## How does it work?
Slip 1u Midazoline into a soda can of 30u cola, you get 31u Midazoline. Slip 1u Midazoline into a welding tank of 900u fuel, you get 901u Midazoline. Even complex mixes of chemicals all become Midazoline when mixed.
The only exception is Mercury: Mercury instead turns Midazoline into more Mercury. So if you want to get rid of 999u Midazoline in somebody's metabolism... charcoal won't work, waterpotassium won't work, only 1u Mercury will. And then you have 1000u Mercury to dispose of.

## How do you make it?
It uses a new "item-in-jar" method of catalyst, inspired by some kinda philosopher's stone type of deal.
Mix 1u Clonexadone, 1u Sulfuric Acid, and 1u Gold Powder in a JAR/LARGE ERLENMEYER that also contains a bar of SOLID plasma.
You have to mind the order of ingredients, or be fast, because the sulfuric acid will slowly melt the plasma if you take too long.

## What does it do if you eat it?
Nothing. Thematically it should turn people into gold statues, but that's lame and something that fits the cockatrice vault better. I don't really want this to be Yet Another Chemical That You Have To Be An Antag To Use.

## What's it for?
I don't know. It's meant to be a novelty/curiosity/gimmick. I coded this just to see what uses people come up with.
You CAN use it to dupe gold via electrolysis, but you also need the means to solidify it, and Botany has been able to do that for ages with nobody ever bothering, so...
In the future, if somebody bothers to code it, I imagine it'd be neat if you could use it in a sprayer to turn iron coins into gold coins, or iron pickaxes/chainmail into gold pickaxes/chainmail etc.

:cl:
 * rscadd: Added Midazoline, a chemical created with clonexadone, sulfuric acid, and gold powder, mixed in a jar that also contains 1 solid bar of plasma. Midazoline converts ALL chemicals it touches into more Midazoline. The exception is Mercury, which turns Midazoline into more Mercury.

### CODE REVIEW

**Comment by Eneocho** [comment]
Criminally based.

**Comment by Eneocho** [comment]
Does the plasmasheet remain after you make the first unit of midazoline?

**Comment by strawberrytan** [comment]
I like it, I think the metabolism rate should be halved so it hangs around for a while

**Comment by help-maint** [comment]
Yes, the plasmasheet remains

As for metabolism, just like chug water

**Comment by Eneocho** [comment]
What if I feed someone a mercury-ice-potassium pill, do they get the mercurification and explosion or does the midazolining take priority and only mercurification?

**Comment by help-maint** [comment]
Seems like ice+potassium works if it's all in 1 pill, doesn't work if it's spread between 2 pills though

**Comment by help-maint** [comment]
Also, if you throw up, your vomit on the floor turns into more midazoline which I find hilarious

**Comment by Eneocho** [comment]
Does Midazoline have its own sprite for being sprayed on the floor?, like uranium, radium, carbon, etc.?

Also, does it require strictly sacid? Or does formic acid work as well?

**Comment by GreatBigFailure** [comment]
Sounds like a lot of fun. I like the theme a lot. The fact that it inherently limits its potential uses is unfortunate but oh well. Could definitely use some touch reactions in the future.

**Comment by Blithering** [comment]
Maybe have the gold statue effect occur if you have a huge amount of it in your system?

**Comment by calzilla1** [comment]
Sounds like a good poison neutralization drug. Get hit with a meme syringe? Pop one of these and that mix of chloral, cyanide, and waifu becomes 15u of Midazoline

**Comment by Blithering** [comment]
chloral, cyanide, waifu and 0.1u mercury will be the new meme

**Comment by help-maint** [comment]
No sprite for being thrown on the floor because I'm lazy

Formic acid now works, so I guess Botany could make this chem with a little help

There are already easier ways to counter common poisons, but yeah I guess this makes you waifu-proof. It also makes you bicaridine-proof, and kelotane-proof, and nutriment-proof.

One thing I realized is that I guess midazoline smoke grenades should work very well, since 0.1 units getting inside your target is all you need

**Comment by Eneocho** [comment]
on my way to add 1u midazoline to all the chemfridge's pills

**Comment by Eneocho** [comment]
>
>
> One thing I realized is that I guess midazoline smoke grenades should work very well, since 0.1 units getting inside your target is all you need

Can you even make midazoline smoke grenades? Does the midazoline react with the smoke reagents before mixing? You'd need either an EX grenade (one beaker for the midazoline, one beaker for the sugar and phosphorus and one for the potassium) or a stasis beaker that holds the smoke reagents.

**Comment by ghost** [comment]
Hmm today I will counter hyperzine abusers

**Comment by Eneocho** [comment]
Updating the wiki.

**Pull request merged**
