### PR TITLE
Adds more glass to Metaclub and BoxStation Robotics labs.

### PR DESCRIPTION
**Pull request by sonime**
My autism flared up and so I decided that Robotics needs more glass. Thankfully, Duny already realized this and has a stack of 50 sheets in Defficency. Thanks Duny. ~~fuck you~~

I changed the stack of glass in Box Robotics to be 50 instead of 20, and Metaclub Robotics now has a stack of 50 instead of two stacks of 20.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Can't say I agree, roboticist glass numbers are meant to keep a handle on the number of immediate Ripleys and Exosuit Modules you can build until you interact with some other part of the crew to get more, or at least walk over to Cargo to order some.

**Comment by ghost** [comment]
No.
There is a lot of glass that spawns on Box that is very reachable. 100 spawns in the Spacepod bay, I think 100 in EVA and 50 in the tool shed. All of these are pretty easy to get into as a Roboticist, and it's not like you don't have time to run around while your borgs take 5 minutes to print all the parts. 
Plus, R&D doesn't really need all the glass it starts with. You can get through all of R&D and have half the stack left. 
And then just yell at your miners or buy it from cargo, it's so cheap and it's not hard to get.

**Comment by Kurfursten** [comment]
Cargo metal and glass next level cheap, and when the minerals come in you're likely to pick up some more stacks there.

**Comment by JustSumBody** [comment]
Also not counting the free 50 glass on the research outpost, 50 in tech storage when you're getting your yellows.
Don't really need more roundstat

**Comment by sonime** [comment]
Literally nothing but negative feedback on this, so rip.

**Comment by Probe1** [comment]
If its any consolation I've been playing again and I can say with experience as the best damn virologist autism worker that cargo is on point.  The "new" (new to me) cargo ordering system makes bulk orders really easy.  

It's rare that I get totally shafted by cargo and I can ask and receive lots of materials reliably every shift.

**Comment by sonime** [comment]
>someone else actually buys virus crates
I'm surprised nobody else picks up on that meta. I usually can get access from the HoP to open them, and then I just analyze them all and go to town in viro. You can get all the antibodies in 30 minutes and immunize the entire crew from anything.

**Comment by Probe1** [comment]
>antibodies

Fuck them I'm making super beneficial viruses in 30 minutes or your money back.  And I'm releasing it and walking around and there is no stopping the tricord/dd/telepathy/hyperzine rape train from stopping in your station.

But I do have antibodies if it bothers you.

**Pull request closed without merging**
