### PR TITLE
reduce admin discord ping spam

### PR DESCRIPTION
**Pull request by nervere**
pov killette just logged on
image

## What this does
Disables a ping for one specific admin message that has been spamming the admin channels, specifically the one notifying admins of a player with the same IP/CID as another.
[administration]

### CODE REVIEW

**Comment by djkramer123** [comment]
suffer

**Comment by anaxosa** [comment]
PR to give nervere more notifications

**Comment by Pastamadness** [comment]
lol

**Comment by Theophrastus1** [comment]
Guess we should disable @Actually Plays The Game too, because there's days I end up with 30+ pings from that role since I couldn't play.

Maybe just right click clear them and move on?

**Comment by nervere** [comment]
audibly yawns in the downthumbers' faces and metaphysically throws their opinions in the trash

**Comment by Inorien** [comment]
will this lead to admins missing important messages like ahelps? if so i'm highly against it, if not then i'm neutral
e: sorry i'm retarded, i didn't read the code and relied on the description alone
this is logging duplicate IPs, is it not important info? i don't have any alt accounts and have no idea how prevalent it is

**Comment by nervere** [comment]
> will this lead to admins missing important messages like ahelps? if so i'm highly against it, if not then i'm neutral

The ping is for a single notification. The notification I'm doing this for is the one that alerts admins that someone has the same IP and CID.

**Comment by Inorien** [comment]
> > will this lead to admins missing important messages like ahelps? if so i'm highly against it, if not then i'm neutral
> 
> The ping is for a single notification. The notification I'm doing this for is the one that alerts admins that someone has the same IP and CID.

yeah, the description says it disables a ping so i got concerned

**Comment by nervere** [comment]
I will fix the description in light of this.

**Comment by ErrorsWindows** [comment]
> The ping is for a single notification. The notification I'm doing this for is the one that alerts admins that someone has the same IP and CID

Screenshot (2053)

**Comment by Exxion** [comment]
Bro just break his kneecaps

**Comment by pedr69** [comment]
>multiple mice

i thought multikeying was haram?
if all the accounts were in the lobby/observing i guess you could explain it as not actually multikeying but uhhhhh

**Comment by Killette2** [comment]
Honk

**Pull request merged**
