### PR TITLE
Fixed Immunity Scanner display

### PR DESCRIPTION
**Pull request by DeityLink**
I noticed it when I played a round months ago and I see it's still there! WYCI remains forever true.

Immunity Scanner display now only displays antibody concentration and gauges of antibodies that matter. This allows for more antigens to be added to the game without clogging the Immunity Scanner screen (or spoiling their existence).

Here's how it looks: https://imgur.com/a/VX76Del

:cl:
* bugfix: Fixed the Immunity Scanner graph's bars not matching the letters and concentrations written below.
* tweak: The Immunity Scanner no longer mentions antibodies that have 0% concentration in the body, unless said body is affected by a disease that has those specific antigens (and has been analyzed).

### CODE REVIEW

**Comment by Eneocho** [comment]
The antibody bars are kinda misaligned, does this fix that too?

**Comment by DeityLink** [comment]
That's the main purpose of this PR yes, just click the imgur link.

**Comment by Eneocho** [comment]
I mean, the imgur pic is also kinda misalligned, that's why I asked.

**Comment by DeityLink** [comment]
It's an album, there are several pics, the first pic is how it was "Before" as explained just below the pic:

image

**Comment by Eneocho** [comment]
Ah, it only loaded the first for me, I get it now. Nevermind.

**Pull request merged**
