### PR TITLE
Replaced the bloody writing font

### PR DESCRIPTION
**Pull request by DeityLink**
image

:cl:
* bugfix: New font for blood-writing, aptly titled Bloody. Doesn't support smallcaps, but fits its purpose better.

### CODE REVIEW

**Comment by DamianX** [comment]
but you're not sending this asset. Is this font even referenced by the HTML?

**Comment by DeityLink** [comment]
> 
> 
> but you're not sending this asset. Is this font even referenced by the HTML?

How'bout now?

**Comment by DamianX** [comment]
Is this font even referenced by the HTML?

**Comment by DeityLink** [comment]
> 
> 
> Is this font even referenced by the HTML?

Does that count as referenced? I mean otherwise how would it even work for me and some other players?
image

**Comment by DamianX** [comment]
Yes, it does. That's not a font that's installed by default on any OS, right?

**Comment by DeityLink** [comment]
> 
> 
> Yes, it does. That's not a font that's installed by default on any OS, right?

Wrong, it's one of the new fonts added in Windows 10. This was all a plan to identify people still on Windows 7.

https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list

**Comment by Eneocho** [comment]
> 
> Wrong, it's one of the new fonts added in Windows 10. This was all a plan to identify people still on Windows 7.

What if you were on Windows 8?

**Comment by SGuivenne** [comment]
> > Wrong, it's one of the new fonts added in Windows 10. This was all a plan to identify people still on Windows 7.
> 
> What if you were on Windows 8?

Then you deserve whatever bugs you are experiencing you sick fuck.

**Pull request merged**
