### PR TITLE
Burn damage can cause ashing in high amounts

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds a (currently disabled) config option for, should a human take enough instant burn damage, they just dust.

Adds an argument for human dust for it to drop everything that the person has equipped

:cl:
 * rscadd: If enabled by the host. If somebody takes enough instantaneous burn damage, they will turn to dust, leaving their belongings behind.

### CODE REVIEW

**Comment by spoonylove** [comment]
botany bout to go ham with these novaflowers

**Comment by Hoshi-chan** [comment]
It leaves a pile of bones, right?

terminator

**Comment by MadmanMartian** [comment]
If botany can deal 500 damage in a single shot, they deserve it.

**Comment by MadmanMartian** [comment]
Yes, it does leave a pile of bones

**Comment by spoonylove** [comment]
Wont this make atmos burn chamber breaches nuclear holocausts for the station? Sun canisters more deadly than the nuke?

**Comment by Hoshi-chan** [comment]
But that's fun.

Also, it's a config option, it doesn't turn it on, that's up to Pomf.

**Comment by MadmanMartian** [comment]
The burn would be over time, not instantaneous

For this, the only feasible method I can think of for ashing a person instantly would be the grid being excessive, or being a diona

**Comment by Goldsteel** [comment]
I don't know how I feel about this. Out of curiosity, how much power needs to be in the grid to induce 500 burn damage?

**Comment by Kitfox88** [comment]
i like the idea

**Comment by MadmanMartian** [comment]
The function for electrocution damage, from the powernet, is avail^(1/3) * rand(1,1.25) effectively,

So, anywhere from 64000000W to 125000000W

**Comment by Caboozles** [comment]
It’d take grid efforr, but it’s very doable.

As long as this doesn’t end up with bans for overwatting the grid, I think this is fine.

**Comment by SGuivenne** [comment]
> As long as this doesn’t end up with bans for overwatting the grid, I think this is fine.

Only way I can see bans like that happening would require shittery thats already bannable, such as intentionally shocking doors as a nonantag or intentionally placing electrified grilles in dumb spots.

This will make rage cages exciting though.

**Comment by Blithering** [comment]
Bone piles being revivable as skeletons when?

**Pull request merged**
