### PR TITLE
Air Tank Sprite Port

### PR DESCRIPTION
**Pull request by kol1th**
# Scope of PR

This PR replaces the current tank sprites with new, and improved ones. I made the small red one myself as it didn't exist.

https://github.com/tgstation/tgstation/pull/23861

# Screenshots

image

image

## UPDATED
image

# Changelog

🆑 
* tgs: Air tanks now have new sprites! They're from TGstation.

### CODE REVIEW

**Comment by Lokiamis** [comment]
Wouldn't mind seeing them without the black outline

**Comment by ghost** [comment]
its time to steal all the code and sprites
(guardian port when)

**Comment by CptWad** [comment]
im up for porting sprites, a lot of ours are just prehistoric

**Comment by N3X15** [comment]
WE HAVE A VOLUNTEER

**Comment by kol1th** [comment]
I'm actually the volunteer. But I'm not respriting anything :^)

**Comment by CptWad** [comment]
dont forget 
https://github.com/tgstation/tgstation/pull/23934

**Comment by Sprok0** [comment]
I, don't think these look good. What's wrong with the old ones?
And what is that angle on the plasma tank, how is it sitting on the ground like that. How does the one-tank bomb equipment overlay work on it?
How do these look attached to a TTV?

**Comment by kol1th** [comment]
TTVs are not changed by this PR.

**Comment by SangriaMonkey** [comment]
Gross.

**Comment by ChangelingRain** [comment]
UNFUCK YOUR TINY RED TANK COLORS http://puu.sh/tXOZT/710956dc3d.dmi
Like holy shit how did you fuck up the colors on that these sprites are literally using a palette where you can swap out colors at will

**Comment by 9600bauds** [comment]
Lacks the plasmeme super snowflake internals plasmatank

**Comment by kol1th** [comment]
@9600bauds i can do recolors thats about it

**Comment by kilozombie** [comment]
Post the versions without outlines?

**Comment by 9600bauds** [comment]
How does the one-tank bomb overlay look on these Korean MMO things

**Comment by Riekland** [comment]
These look good but they look like nothing else in the fucking game
Either resprite LITERALLY EVERYTHING ELSE or don't port these since they stand out so much

**Comment by PJB3005** [comment]
Yeah they look really weird, probably because of a combination of the outline and the diagonals.

**Comment by yclatious** [comment]
Those sprites look damn good, but everything else doesn't kolith. Its a good intention and if everything else wasn't ugly as shit in comparison, Id love it, but it clashes way too much.

**Comment by kilozombie** [comment]
Yeah that's really fair.
Cohesion is more important, even if the sprites do look good.
Ditching the outlines would be a start

**Comment by Kurfursten** [comment]
untitled

This is a quick demo of what it looks like with no outline

**Comment by Riekland** [comment]
remove the big black outline on the white band too you utter mongoloid

**Comment by Lokiamis** [comment]
Don't worry, when we switch to 64x64 we can upgrade all existing sprites to match these tanks no problem.

**Comment by Exxion** [comment]
These look good, but they kind of... stand out
We already don't have any kind of consistent artstyle, but this isn't consistent with any of them

That said, I also don't really care

**Comment by Probe1** [comment]
What's with minor PRs attracting controversy in the last month while big PRs get a pass.

**Comment by Lokiamis** [comment]
Most people know better than to oppose the coderclub

**Comment by Anglosphere** [comment]
Minor PR's are being pushed to distract voters. Certain Waifu Hair PR's were only submitted to run as a screen for larger PR's. This likely is running as a screen for a much larger, and more sinister PR.

**Comment by JustSumBody** [comment]
>What's with minor PRs attracting controversy in the last month while big PRs get a pass.

BIKE
SHED

**Comment by Probe1** [comment]
I cannot believe we had a [Controversy] over the color and texture of bluespace my fucking god people take a step back.

**Comment by ThePlapatin** [comment]
They look too nice that they stand out a lot, weird complaint but it doesn't fit

**Comment by despotate** [comment]
We merged the improved shuttle sprites, too late to do anything these PRs now

**Comment by ThePlapatin** [comment]
two wrongs do not make a right, three lefts do

**Comment by Lokiamis** [comment]
I like the new sprites, but the harsh outline that doesn't blend looks bad to me.

It's not really black, but you can see that nothing else on the mob here has that outline. The edges are softer.
687474703a2f2f7075752e73682f74597942772f376165316536346462652e706e67
old/new
tank

**Comment by IzayaChan** [comment]
It scuks

**Comment by PJB3005** [comment]
I'm gonna be honest our previous ones look so much better.

**Comment by Chucklemonger** [comment]
That style fits with just about nothing else in the game. Plus it kinda looks like shit even independent of what it would be replacing.

**Comment by Frutzl** [comment]
risk of rain style sprites? hnnng

**Comment by Yelier** [comment]
Nice sprites, but they don't fit at all.

**Comment by kol1th** [comment]
What does fit, then? The old mess of pillow shaded pixels?

**Comment by Lokiamis** [comment]
Well, yeah. It's SS13.

**Comment by kol1th** [comment]
So let's leave everything shit because "That's how ss13 should be!"

**Comment by Frutzl** [comment]
don't get me wrong but if you're saying that ss13 has a consistent art style, you're talking out of your ass
i mean come on, these look GOOD, ss13 has no artstyle

**Comment by kol1th** [comment]
It doesn't. That's the point.

**Comment by 9600bauds** [comment]
Compare those mob overlays with anything else in the game and tell me again there's no consistency 

Nothing you can possibly put on your back gives you a weird big bright blob with very visible black outlines

**Comment by Frutzl** [comment]
exactly, kolith. if people think these shouldnt be merged because "ss13 artstyle", thats the worst argument ive ever heard

**Comment by kol1th** [comment]
I'm working to improve the overall quality of our sprites. Give me things you thing aren't good, or are in need of a re-sprite, and I'll see to it.

**Comment by PJB3005** [comment]
Alright here's the deal.

These sprites do look good, I'm not gonna disagree with you.

But they look extremely cartoony and almost as if they came out a **GBA Pokémon game.**

SS13 has no consistent art style no, but these just stand out too damn much. The regular tanks can probably be fixed by changing the palette, making the contrast lower and making it more dark in general, but that plasma jerrycan is just *no*.

**Comment by PJB3005** [comment]
@Frutzl 

> exactly, kolith. if people think these shouldnt be merged because "ss13 artstyle", thats the worst argument ive ever heard

Ah yes, the good old "we're literally swimming in shit let's just flat double the amount of shit, not a problem."

**Comment by PJB3005** [comment]
Also the jerrycan doesn't even have the damn Pl letters on it. Boo.

**Comment by Frutzl** [comment]
you see PJB, the thing is, if someone makes things that actually look better than the way they do now, they should at least be considered to be put in the game. they could be improved on, sure, but the point is, improving garbage sprites from 2006, even if one by one, is a big step up. just my two cents, anyway.

**Comment by PJB3005** [comment]
See, as I said they do look better...

if you're comparing them objectively without context.

If you gave the sprites for comparison to somebody who's never even heard about SS13 and asked them which is better they'll say these new ones guaranteed.

But in the context of SS13 they look like actual horse shit when placed next to every other sprite.

**Comment by kol1th** [comment]
You're not wrong. But I plan on making a lot of the sprites we have now better. 

🤷‍♂️ 

I'm not exactly partial to the plasma tank either. I don't even know why it's included. Chances are I'll remove it soon, don't like it too much compared to the others.

**Comment by 9600bauds** [comment]
>they should at least be considered to be put in the game

Are we not considering it?
"It should be considered" does not mean "it should be done"

**Comment by Exxion** [comment]
Just like
Kill the outlines and lighten up on the shading a bit

**Comment by kilozombie** [comment]
@Probe1 The reason is because people choose what battles they want to fight. When the argument is just about the aesthetics of something, absolutely everyone can have a stake in it for free.

**Comment by kol1th** [comment]
I'm coding bike sheds next.

**Comment by Intigracy** [comment]
They're fine sans the outline

**Comment by Exxion** [comment]
@kol1th So let me get this straight
You ported something with no bearing on gameplay and how it looks is the ONLY thing that matters about it
And people complaining about how it looks is bikeshedding?
?????

**Comment by SangriaMonkey** [comment]
If it's not no-fruit it's silly and trivial.

**Comment by Kurfursten** [comment]
@Riekland Calm down my man, you need Space Jesus

**Comment by ThePlapatin** [comment]
>carshalash voted on this despite being permabanned

?

**Comment by TheFriggenSawbones** [comment]
> solarious posts on github despite being perma'd

?

**Comment by kilozombie** [comment]
>votes mattering

**Comment by ThePlapatin** [comment]
the emoji vote is sacred ok

**Comment by Riekland** [comment]
WAIT HOLD ON
We had belt icons for small tanks before and everyone hated them because it ruins the aesthetic of many costumes
fucking remove small tank on mob sprites or I'll dos you fegt

**Comment by Exxion** [comment]
I'm about 95% sure they already show upon the belt.
I think you're thinking of suit storage.

**Comment by Riekland** [comment]
Oh no shit wait I remember, it was the white air tube going from the tanks that caused the issues
maybe make them transparent or something I dunno

**Comment by Probe1** [comment]
>counting votes over discussion

Many people made fine points over the shading and outlines not matching the rest of the game and I'm ok with holding on till that's addressed.  

The amount of _upvotes_ a PR has is real fuckin low on my list of worries.  They are a casual way of showing approval.  If they aren't backed up with your input I give them a glance then move on to the meat and potatoes:  What the PR is and whether anyone has brought up good points on why it should not be merged.

**Comment by Shadowmech88** [comment]
It's a lot easier to go into depth about why you dislike something than why you like it. I'm pretty sure there are more negative posts than positive posts on *any* PR with roughly equal upvotes/downvotes.

**Comment by Probe1** [comment]
And likewise, a person who likes something will not really be motivated to write at length as to why they like it.  That is a very valid point and one that I'm mindful of.  

I was just explaining why again we're seemingly at the whims of emojiocracy and why sometimes I don't listen to it like it's the holy word.

**Comment by kilozombie** [comment]
I respect that completely. It's good for a first-glance look at how the community might view it, but that's not a perfect view of the community and also isn't the greatest metric to see if something should be merged or not.

What's really important is that legitimate points aren't ignored or glossed over.

edit: I will say that my personal use of the emojicracy is... I use it on most PRs. If there's a PR I'm too stupid to really discuss, but I understand the general gist, I throw a vote in, knowing it's not so important.

**Comment by SangriaMonkey** [comment]
:hotsprings:  hot opinion :hotsprings:  
I think that emoji voting is a shitty corporate design committee feature that kills actual discussion.
You just get your thumbies and go unless someone raises hell about it. Makes gauging general reactions a little easier but ultimately less actual feedback is being given, which kind of undermines the purpose of the whole peer review thing.

**Comment by SonixApache** [comment]
needs better outlines, style is pretty cool
little over-techy (too detailed?) compared to most of the other shit like canisters and gas masks

**Comment by optimumtact** [comment]
dont' worry if you force this through and stifle dissent the complaining goes away after a few days

**Comment by Probe1** [comment]
We save that for good PRs @optimumtact 

@kol1th is this ready to go?

**Comment by Riekland** [comment]
PROBE NO

**Comment by cadaverouscoyote** [comment]
> But I plan on making a lot of the sprites we have now better.

then do it and get back to us, so we can be sure we won't be stuck with a just a couple of slick, flashy, new sprites that are glaringly out of place. i wouldn't consider these outside of a larger pr and even then i don't particularly like them.

**Comment by Probe1** [comment]
"We shouldn't improve anything because everything is old and we should just stay like that forever" is by far the worst argument you can possibly come up with about anything.

**Comment by ghost** [comment]
Probe1 is now my favorite.

**Comment by Riekland** [comment]
Probe we covered this fucking arguement already
Not only does it not look better, improving things piecemeal by several different people results in the mess of artstyles we have today
If you want the game to look like those sprites that's great but fucking change everything, just adding more out of place sprites will NOT HELP
I ALREADY FUCKING SAID ALL THIS REEEEEEEEEE

**Comment by cadaverouscoyote** [comment]
"strawman" is by far the worst argument you can possibly come up with about anything

**Comment by jknpj** [comment]
"We already talked about this" is by far the worst argument you can possibly come up with about anything

**Comment by aratherangryduck** [comment]
Ignoring all previous valid complaints about stylistic clashes is by far one of the worst ideas you can possibly make.

If this was a complete overhaul of wall sprites and the like, Id maybe give it a shot, but I know itl be weeks or hell, the other sprite replacement prs might not even come at all after this is merged, and what then, we are stuck with some obviously standing out tank sprites while everything else stays the same? Its a decently high probability Probe, so why risk it.

**Comment by kilozombie** [comment]
@Probe1 "We shouldn't improve anything because everything is old and we should just stay like that forever" isn't the argument being made here.

One of the arguments being made here is "it clashes with our current artstyle". One of the _reasons_ it clashes with our current artstyle is because we have an older style.

Please don't ignore legitimate criticism by passing it off as something else.

**Comment by Kurfursten** [comment]
I honestly think the sprites look much more reasonable without the black outlines.

I think you should at least mock up some outline-less versions so people can compare. I did a really simple mockup myself earlier. The outlines are pretty standout though.

**Comment by jknpj** [comment]
@kol1th  are the images in your OP updated? Didn't @NigglyWiggly help you remove the black outline-

tankshit

Yep, update OP.

**Comment by Intigracy** [comment]
still the same m8

**Comment by jknpj** [comment]
Did he just remove them from item_state?

**Comment by kilozombie** [comment]
I really don't mind the ones with the improved outlines at all.

**Comment by kol1th** [comment]
OP has been updated.

**Comment by Blithering** [comment]
The outlines are an improvement, but with no new jetpack or plasma tank sprites they're still gonna cause some icons to stick out like a sore thumb. I'd prefer to keep a cohesive set.

**Comment by kol1th** [comment]
Yeah, if someone is up to sprite it go for it. I'll try something in a bit. I'm not fond of the in-hand for the emergency tanks, either. I'll try to make something for those as well.

**Comment by eplgr** [comment]
Merge /when/?

**Comment by PJB3005** [comment]
Never.

**Comment by kol1th** [comment]
It's ready to go. /shrug

**Comment by Riekland** [comment]
It won't be ready until you remove the outlines from the on mob sprites and in hands, you shitlord

**Comment by kol1th** [comment]
But I DID

**Comment by PJB3005** [comment]
Screenshots where?

**Comment by kol1th** [comment]
Check the OP nerdboy

**Comment by Exxion** [comment]
You know, I was thinking the shading would need to be lightened up, but actually those look fine with just the softened outlines

**Comment by PJB3005** [comment]
Nah they still look pretty bad.

**Comment by Probe1** [comment]
anyhow time to send it to the server and see what people say.  see you back in 3 days with a revert PR pending the poll.

**Comment by murnandreams** [comment]
Out of place, looks shit.

**Comment by ihadtoregisterforthis** [comment]
"Test merging because I like it" is by far the worst argument you can possibly come up with about anything

**Comment by Probe1** [comment]
Who said I liked it?

**Comment by kilozombie** [comment]
The argument begins and ends at "this doesn't fit" vs "it is okay". If we want to further this argument in an actually productive way, test merging isn't a bad way of doing it.
Gather opinions after it's been out a bit to see if it's actually as bad as people are saying here, or if it's even a slight bit over-exaggerated.

**Comment by murnandreams** [comment]
With the emergency airtanks, how do I adjust their air consumption? I can't do it by using them anymore.

**Comment by Chazach** [comment]
these look like ass please stop

**Comment by Probe1** [comment]
@LemonTheFruit 

That has nothing to do with this PR.

Double click it while it is in your hand, or press Z.

**Comment by murnandreams** [comment]
Just something fucky was going on that round I suppose.

**Comment by Megamaw** [comment]
these look nice

but next to the rest of the game, it looks jarring as fuck.

**Comment by Tehsapper** [comment]
tbh they look out of place and the outline is still shit. the diagonal placement does not help.

**Comment by kilozombie** [comment]
Played with them one round, the worn sprite is not to my taste at all.

**Pull request merged**
