### PR TITLE
Removes laser eyes from wizard's hulk out spell

### PR DESCRIPTION
**Pull request by gbasood**
<gameplay>
Created following a discussion suggesting changes to wizard to make them less one player murder fantasy, fun for the player who gets wizard and no one else, and more antagonistic

:cl:
 * tweak: Wizard's mutate spell no longer grants laser eyes.

### CODE REVIEW

**Comment by Manleto** [comment]
Mutate isn't worth the cost without lasers eyes. reduce it

**Comment by gbasood** [comment]
I'm not sure it isn't worth its cost without laser eyes, honestly. Laser eyes AND hulk at 20 cost makes it an automatic buy for anyone looking to murderbone. It's still all but necessary just so you can withstand a lot of things that would otherwise incapacitate you.

**Comment by GreatBigFailure** [comment]
Make it no robes.
Mags aren't a buff to hulks. All it would do is allow silly costumes and some kind of wrestle man wiz. Good change either way

**Comment by PrimeDSS13** [comment]
making it no-robes is a good idea if it's just hulk actually

**Comment by Eneocho** [comment]
If hulk out loses the laser eyes, we need a separate spell that consists of only laser eyes.

**Comment by Dacendeth** [comment]
Could re-purpose laser eyes to a potion as well, not just a spell.

**Comment by Blithering** [comment]
I'd rather the cost was adjusted to account for the power, rather than a nerf. Laser eyes are cool, and there's far more egregious kill the whole station spells out there.

**Comment by gbasood** [comment]
Given the amount of support the PR has currently I'm hesitant to modify the spell's price. However a subsequent PR could easily change the price

Making it no robes would be good but I didn't see a clean way to do that with how norobes spells currently work (inheritance and typechecking). I didn't want to change much so I left mutate as is.

**Comment by DeityLink** [comment]
This cannot come any sooner

**Pull request merged**
