### PR TITLE
Security cyborg H.O.S. upgrade, W.A.T.C.H. upgrade tweak and more.

### PR DESCRIPTION
**Pull request by jknpj**
* Upgrades can now require other upgrades to be installed in the cyborg
* Upgrades will not add something that is already present in the cyborgs modules
* Adds two new quirks, MODULE_HAS_FLASH_RES and MODULE_IS_FLASHPROOF.
* MODULE_HAS_FLASH_RES reduces the duration of flashes by half.
* MODULE_IS_FLASHPROOF makes the silicon ignore flashes, totally balanced i swear to god guys. (They still get hit by the flashbang's sound stun)
* Cyborgs with the W.A.T.C.H. upgrade have MODULE_HAS_FLASH_RES now.
* Cyborgs with the W.A.T.C.H. upgrade now adds cyborg cuffs to hugborgs.
* Fixes a runtime with object code trying to check the reagents of cyborgs every time they fired a fucking gun

I really hope we can make a flash_act or something because flashbangs, flashers and flashs having their own snowflake code is pants on head.

The Head of Silicons upgrade contains:

* MODULE_IS_FLASHPROOF Quirk
* MODULE_IS_DEFINITIVE Quirk
* Removes the taser, revolver, speedloader and gives them a Lawgiver(Also DNA so they can use it)
* Grenade Launcher
* Upgrades the worn-out gripper to be able to hold lawgiver magazines, grenades and donuts
* Custom look for Hugborgs (Icon made by TG's RemieRichards)

:cl:
 * rscadd: Adds the security cyborg H.O.S. upgrade to the tradervend. A powerful upgrade that requires the target cyborg to already have both N.O.I.R. and W.A.T.C.H. installed first... Good luck trying to get all of them in a single round!
 * tweak: Cyborgs with the W.A.T.C.H. upgrade now recover from flashes faster than normal silicons.
 * tweak: Cyborgs with the H.O.N.K. upgrade may now blow their own guns if they try to use any.(Can only happens to Hugborgs)

### CODE REVIEW

**Comment by ShiftyRail** [comment]
>flashproof borgs

**Comment by aceedex** [comment]
Powerful
This is the day the silicon metaclub takes back their rightful soil

**Comment by Kurfursten** [comment]
Apx 0.087% odds of all three being available in the same shift.

No data on odds of secborg/trader exists or trader to borg sales

**Comment by ShiftyRail** [comment]
How is the silicon-in-chief Lawgiver recharged ?

**Comment by jknpj** [comment]
* Equip both lawgiver and gripper
* Activate lawgiver
* Click on it to remove the magazine, magazine will automatically drop on the Gripper
* Tap the nearest gun recharger with It
* Wait until the recharger is blinking green
* Grab magazine with gripper
* Slap It back inside the lawgiver

**Comment by ghost** [comment]
What's the point of features that have practically no chance of being seen in a round?

**Comment by Durgen** [comment]
bus

**Comment by Sooose** [comment]
So some badmin can bus it in not realizing how busted it is and then get shit for it later.

**Comment by jknpj** [comment]
You can say that about all adminbus items, so yes.

**Comment by Sooose** [comment]
That's true, the even more unstunnable nature of it combined with the ranged stuns of it's own gives me pause. My earlier post was mostly a shitpost so don't take it seriously for the PR's sake.

**Pull request merged**
