### PR TITLE
Adds a video game playlist.

### PR DESCRIPTION
**Pull request by slightly-floating**
I didn't make the playlist, just helping. The tracks are not subject to change, do not complain to me. Those are the rules.

Music

Music

### CODE REVIEW

**Comment by Kharkov72** [comment]
gamer

**Comment by mrflarg** [comment]
>no baba yetu 
>no https://www.youtube.com/watch?v=ckZlj2p8W9M

cringe

**Comment by ShiftyRail** [comment]
Extremely disproportionate amount of gay weeb shit.

https://youtu.be/OXajx7l4VxE
https://youtu.be/-mzfnUIdzq4
https://youtu.be/Q2evIg-aYw8
https://youtu.be/Uxg5W5wKvLE
https://youtu.be/cfOaV9QEk4I

And Half-Life (+2), Portal (+2), the TF2 menu themes........ Supergiant Games soundtracks.. Mirror's Edge...... Zoomers these days.......

I think you could add some variety by limiting it to one track PER GAME and try to include more than just RPGs in it.

**Comment by Eneocho** [comment]
> 
> 
> > no baba yetu
> > no https://www.youtube.com/watch?v=ckZlj2p8W9M
> 
> cringe

Baba yetu, yetu uliye

**Comment by Eneocho** [comment]
>no earthbound 
>no chrono trigger
>no hl2 
>no diablo 1 and diablo 2 
>no uplink 
>no doom 
>no stalker bandit radio
>no zero escape 
>no terraria 
>no hotline miami
>no vtmb 
>no fallout 1 
>no binding of isaac 
>no necrodancer A1M2 Shopkeeper 
>no tf2
>no transistor
>no bastion
>no spelunky
>no link to the past lost woods
>no deus ex 

What even is this playlist.

**Comment by Kurfursten** [comment]
My instinct is that a video game playlist may be a bad idea because there's just so much out there that has left an impression on people and it will just make people upset they can't find any of their favorite music.

I think instead of just going with "vidya music I like" you should go for a stronger theme, like "Space Game Music" or "Retro Game Music".

**Comment by xeroxemnas** [comment]
Don't we already have a bunch of vidya music? I coulda sworn I've heard the death egg theme from Sonic 3 before.

**Comment by slightly-floating** [comment]
The contents of this PR will be the same regardless of whether the tracks you want are in or not. If new tracks are really a precondition to this being merged, please speak to Dickwrath. They are the creator of this playlist and handling the media server side of things.

**Comment by Dickwrath** [comment]
Hi yes, to address some concerns and to expand upon the intentions of this playlist I'll go ahead and clear a few things up.

For starters, the intention of this playlist is not to be this catch all general playlist with one song from every franchise known to man, but a curated collection of community suggested tracks. I added suggestions, limiting songs to three per franchise so not a single series would be over-represented. I then excluded songs that were too heavy or were sonically at odds with other songs on the playlist, the idea being it can be a more energetic, dancey selection with some calmer songs dotted in to break it up a bit. Which is why you wont be seeing Shadow of the Colossus or Bloodborne music, as amazing as they are they don't fit a bar environment. Same with series like Zero Escape (though I have included some of the more mellow VLR tracks). 

Lastly, I had a strict limit of 70-80 songs with this playlist. It currently sits at 73, and it's entirely comprised of music from a variety of series, from many generations and publishers. I did not want to exceed this limit as it is already one of the largest playlists to be suggested. Even still, I managed to justify such a size by also having a strict limit on song length, with most songs being in the 2-3 minute range, and very few being any longer than 5, keeping the folder (after conversion) to a respectable size. 

What I'm offering is almost entirely community chosen, with some auditing for cohesion. I did not want to call it 'chill vidya' or 'club vidya' because I think there's a large enough variety of songs to not pin it down to a single theme. So I decided on 'Vidya' as a double meaning. To mean songs from video games, but also songs from the vg community that they wanted to see in. 

If you feel there is a song or two that absolutely needs adding, I'm open to extending the PR to accommodate. What I will not do is keep it open forever while an endless amount of songs pour in, because let's face it, there's a lot of video games that are cherished and loved out there and it would be impossible to represent them all. But if I can represent a sample size that people are satisfied with, then I feel this makes it a worthy addition. 

For suggestions, feel free to contact my Discord. Otherwise I'm happy to deliberate here. I hope I've cleared a few things up!

**Pull request merged**
