### PR TITLE
Snowmap salvage: Wintercoats and boots

### PR DESCRIPTION
**Pull request by JustSumBody**
Can't let these /vg/ original sprites go to waste
image
Adds wintercoats and winterboots, they keep you warm and look cool as HECK
no way to obtain outside of admin spawn

WE'RE BRINGING
SNOWMAP
BACK

### CODE REVIEW

**Comment by RFultra** [comment]
any chance the jobless coat can be added to the clown outfit vend?
Seems like a waste having them admin because 90% of admins wont spawn them for people and the 10% that will will only spawn them for their metafriends

**Comment by kol1th** [comment]
What are you even talking about buddy

**Comment by RFultra** [comment]
the metaclub, duh

**Comment by ghost** [comment]
could always stuff them in a cargo crate

**Comment by gbasood** [comment]
honestly it'll probably be less of a clusterfuck if we add parts of the snowmap PR piecemeal
less conflicts to manage

**Comment by ghost** [comment]
A cold weather cargo crate sounds nice.

**Comment by Shadowmech88** [comment]
Such a crate could be another source of space blankets, as well.

**Comment by kol1th** [comment]
They don't come in cargo crates in snowmap, there are closets around the station that you can get a regular coat + boots from.

**Comment by Blithering** [comment]
Snowstation is happening a chunk at a time!

**Pull request merged**
