### PR TITLE
can now scan heads with health analyzers

### PR DESCRIPTION
**Pull request by MadmanMartian**
razz_request

With this, you can now scan a head with a health analyzer. If there's no brain, it will tell you as such. If there's a brain with a mind where the mob has not ghosted, the head will twitch in some way. If there's a brain with a mind, but the mob has ghosted, there will be little to no reaction, but a reaction nonetheless. Otherwise, no reaction will occur.

 **todo**
- [x] Add aesthetic (Sounds, effects)

:cl:
* rscadd: You can now scan a severed head with a health analyzer to see if it still has a mind

### CODE REVIEW

**Comment by Kammerjunk** [comment]
Please yes
Save time not fixing up goners, more time for helping other people

**Comment by Dacendeth** [comment]
That was impressively fast.

**Comment by ghost** [comment]
Give a message to the ghost if they ghosted, like the cloner does

**Comment by MadmanMartian** [comment]
@Unknown-as-Captain good idea

**Comment by MadmanMartian** [comment]
that took much too long, I'm sorry.

**Comment by ghost** [comment]
Thank you, this is great

**Comment by ghost** [comment]
God bless your work.

**Comment by nuklearcellphoneg** [comment]
I'm giving this person all flags.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
