### PR TITLE
[Meta] Bugfixes

### LINKED ISSUE #2940: [Metaclub] Add additional IVs
Add 2-3 more IVs to storage.  Metaclub Medbay It only has the one near surgery and that's a bit unreasonable to ask medbay to go get metal to make basic supplies.  3-4 covers almost all regular possibilities and more can be made if needed.  

image

Unrelated but I'd remove the advanced trauma/burn kits.  We have to annoy RnD for something!

Also unrelated but I'd remove a few of the O- bloodbags.  Seems a bit too generous to have that many.  I'd replace them with empty blood bags.

@IratePirate

### LINKED ISSUE #3041: [Meta] Officer beepsky gets stuck in the escape hallway
There are also two beepskys. so they play in escape all day until a traitor comes to collect his free stun batons

### LINKED ISSUE #3234: Meta the map got no nullrod
Ruh-roh

### LINKED ISSUE #3237: [META] No Atmos Automations PC in atmos.

### LINKED ISSUE #3238: [META] Derelict alarms showing up in MoMMi's "Show Alert" page
also a complete different set of alerts shows up in the actual alert pc on station:

### PR DESCRIPTION
**Pull request by IratePirate**
fixes #3041
fixes #3237
fixes #2940
fixes #3234
fixes #3238

### CODE REVIEW

**Comment by ComicIronic** [comment]
What's fixed?
Could you look for any tvalves on the map and check they're pointing the right way?

**Comment by IratePirate** [comment]
Sure i'll check them out now. And just some of the issues, plus fixed some floor tiles, fixed some privacy shutters, added Pod Bay RD console and added some fire locks to eastern brig.

**Comment by clusterfack** [comment]
How did you fix #3238 ?

**Comment by IratePirate** [comment]
t-thanks

I replaced the APCs.

**Comment by d3athrow** [comment]
Were major map changes made that would need a nanoui map regen?

**Comment by IratePirate** [comment]
Nope. For once this is just little things. I managed to restrain myself.

**Pull request merged**
