### PR TITLE
Fixes #5222, air alarms not having n2o thresholds

### LINKED ISSUE #5222: Air alarms do not have an N2O threshold
As the title says, you cannot configure the threshold so the air alarm stops kicking up alerts and dropping firelocks because of N2O. Ultra-annoying to a malf trying to not plasmaflood.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by PJB3005** [comment]
Wrong.

N2o is not the only trace gas.

**Comment by PJB3005** [comment]
If you're gonna spam fixes at least put in the effort to do it properly.

**Comment by 9600bauds** [comment]
What other trace gases are there?
I only ever see trace gases being used to refer to N2O.
Please be a little more constructive.

**Comment by PJB3005** [comment]
Oxygen agent B and Volatile fuel.

Yes, I can't think of a way to make either of those too, but naively throwing all gases under N2O is wrong and you know it.

**Comment by 9600bauds** [comment]
I have never, ever heard of those and I'm not convinced they are actually in the game, I actually thought N2O was the only trace gas (which is believable due to shitcode).
But here, let me fix it!

**Comment by Exxion** [comment]
Yes, I remember seeing a system specifically for trace gasses. I have no idea if any other than N<sub>2</sub>O are used, but they exist.

**Comment by 9600bauds** [comment]
Well this PR actually got fucked because it was closed when I pushed the fix, thanks a lot @PJB3005 for your quickdraw skillz

**Comment by Exxion** [comment]
Huh.
Since when does that break things?

**Comment by 9600bauds** [comment]
No clue, let's try not to close shit willy-nilly so it doesn't happen again

**Comment by PJB3005** [comment]
I wouldn't have closed this if YOU made the PR yourself, but considering celt has 4 days left to fix 100 bugs AND get the fixes merged or his headmin rights are at stake I have all reason to assume he's shoveling out untested and broken bug fixes.

**Comment by ghost** [comment]
@PJB3005 my headmin rights? N-nani? But I'm stepping down in January anyway and that wasn't part of the deal

**Comment by 9600bauds** [comment]
\>I wouldn't have closed this if not for \~DRAMA UNRELATED TO COLLABORATOR STANDARDS\~

**Comment by TheFriggenSawbones** [comment]
@PJB3005 god bless the coders

**Comment by PJB3005** [comment]
@9600bauds it literally IS collaborator standards though.

Showing that throwing out shovelware fixes without thought is unacceptable is a good thing.

**Comment by 9600bauds** [comment]
PJB, it was just human error because I thought N2O was the only trace gas, which is an acceptable error to make when the other trace gases don't even exist in-game as far as I know.

Instead of using the review function, which you know how to use, you flip and close the entire PR. That's not okay. And I even remade the PR properly already, you need to calm down.

**Comment by PJB3005** [comment]
> you need to calm down

What am I not calm?

> Instead of using the review function, which you know how to use, you flip and close the entire PR. That's not okay.

If you have more than enough reason to assume malice, it is.

**Comment by Exxion** [comment]
PJB, what the fuck are you talking about?

**Pull request closed without merging**
