### PR TITLE
maybe prevent clown cannonballs from going bananas

### PR DESCRIPTION
**Pull request by d3athrow**
[bugfix]

### CODE REVIEW

**Comment by d3athrow** [comment]
#29543

**Comment by GreatBigFailure** [comment]
I don't know if this will fix it because stopBouncing() is only called when you try to arrest it to make it stop. The crash this caused had nothing to do with that as far as I saw. This is an oversight either way and I think probably fixes another bug I've noticed with them but couldn't pinpoint where in they just lose their bouncy properties forever

**Comment by adacovsk** [comment]
I would like to think shooting or arresting the ball being the only ways to stop it are intentional. Crashes might be related to the breakable  items PR

**Comment by Eneocho** [comment]
>I would like to think shooting or arresting the ball being the only ways to stop it are intentional. 

It IS intentional, it's a clown(ball).

**Comment by GreatBigFailure** [comment]
> I would like to think shooting or arresting the ball being the only ways to stop it are intentional. Crashes might be related to the breakable items PR

It is intentional, I made it. I meant that I didn't think this specific oversight caused the crashing. Good call on the breakable items though, that's possible since I know this was fixed ages ago.

**Pull request merged**
