### PR TITLE
Janitor's New Gloves, Derelict RnD

### PR DESCRIPTION
**Pull request by bthomas2**
:cl: 
* rscadd: Metaclub: added new RnD server and console to Derelict.
* tweak: replaced Janitor's orange gloves with black ones.

### CODE REVIEW

**Comment by bthomas2** [comment]
oh fuck not again

**Comment by brndd** [comment]
but why

**Comment by bthomas2** [comment]
burnt hands

**Comment by Intigracy** [comment]
I thought janitors were given purple gloves that had stats of black ones.

Weird.

**Comment by SonixApache** [comment]
🆑 is not formatted correctly
pretty sure janitors get their own gloves don't they?

**Comment by bthomas2** [comment]
always good to have a spare

**Comment by Intigracy** [comment]
🆑 is not formatted correctly

**Comment by bthomas2** [comment]
fixed

**Comment by Durgen** [comment]
unatomic

**Comment by bthomas2** [comment]
fine

**Pull request closed without merging**
