### PR TITLE
Removes fuck-up boots from spellbook

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
JUST

:cl:
 * rscdel: Fuck-up boots can no longer be purchased

### CODE REVIEW

**Comment by BomberBro** [comment]
Normally I'd like to see these reworked, perhaps upping the speed a bit and removing the breaches in favor of ripping up tiles and wires more and keeping the wall breaking, but currently these are basically free shuttle calls so good riddance.

**Comment by SonixApache** [comment]
remove from available list, keep in for dumb bus

**Comment by aceedex** [comment]
I don't like the R word but I think it's been enough fuck ups without anyone talking about fixing them

**Comment by DrSnips** [comment]
2nding them just being removed from the list of options.

**Comment by DamianX** [comment]
Hey, can you not?

This seems all kind of reactionary and deliberately taking away options rather than adding them.
No real reason is provided even.

**Comment by TGFH** [comment]
@DamianX
Witnessing a round where a w*zard with blink and fuckup boots vents the entire station is all I need to vote for this.
3rding Sonix's suggesting to just remove them from the list though.

**Comment by ghost** [comment]
Hello this is the second removal PR and thus second time I will say I only support removing them from the spellbook

**Comment by tuypo1** [comment]
I maintain they don't need to be removed, it just needs to be impossible to take both fuckup boots and blink at the same time

**Comment by ShiftyRail** [comment]
Would rather have them only work after taking a long strike (4~5 footsteps) with the count being reset after blinking

**Comment by SonixApache** [comment]
wyci

this PR is now 👍 and 👌

**Comment by ShiftyRail** [comment]
Higher effort PR linked

**Comment by ShiftyRail** [comment]
Damian you god damn extremist

**Comment by DamianX** [comment]
Your PR can still be merged, I do not care one way or the other.

**Pull request merged**
