### PR TITLE
fixes the tgs part of the changelog being pretty much unimplemented

### PR DESCRIPTION
**Pull request by Intigracy**
which is why it doesn't actually show any icon on the changelog for it

### CODE REVIEW

**Comment by PJB3005** [comment]
Uh, we don't use this C# program though?

**Comment by Intigracy** [comment]
Not at home to check rn, does the py reference it well enough?

Currently the tgs icon shows as nothing on the changelog in-game.

**Comment by Probe1** [comment]
what does this mean

does this work

will i using questionable judgement hit merge?

tune in next week!

Bonus spoiler:  Hitting revert on the previous PR!

**Comment by gbasood** [comment]
@Probe1 merging this would do nothing afaik
the C# code isnt ever used

**Comment by PJB3005** [comment]
Why is this C# code here.

What does it do.

Mysteries!

**Comment by Probe1** [comment]
It's been two weeks.

**Pull request closed without merging**
