### PR TITLE
Clowns honk faster

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Honk.

:cl:
 * rscadd: Clowns will now honk bike horns and other horn-derived objects 4 times faster AKA twice per second.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
This does not affect the syndicate bike horn. Yet.

**Comment by OfficialGasnigAccount** [comment]
Cringe. Nothing wrong with the current honking speed. Give them 4 times the honking speed when they drink coffee, cocaine or any other stimulant. Make clown powergaming powerhonking a reality.

**Comment by boy2mantwicethefam** [comment]
That's what the clown cart is for but on bananium, a far more potent clown stimulant.

**Comment by GreatBigFailure** [comment]
Okay okay hear me out
Bike horn in each hand? Let them honk them both like dual wielding handguns

**Comment by Eneocho** [comment]
> Okay okay hear me out Bike horn in each hand? Let them honk them both like dual wielding handguns

"I am the Clown of my Station.
Banana is my Body and Honk is my Blood.
I have slipped over a Thousand Captains.
Unknown to Perma,
Nor known to the Syndicate.
Have eaten banana to slip many officers.
Yet those peels will never slip enough.
So, as I Pray--
Unlimited HONK Works"

**Comment by Dacendeth** [comment]
Okay sure, but im killing the clown after an admin var edits his bikehorn to play an annoying soundclip and he spam clicks it.

**Comment by nervere** [comment]
Please gate this behind something, *anything*.

**Comment by boy2mantwicethefam** [comment]
I think it needs to be mentioned the general overestimation of how spammy this is actually going to be. The cooldown of a bike horn is TWO SECONDS. This allows clowns to honk twice per second at most.

**Comment by Eneocho** [comment]
Requesting for the bike horns to have exactly ZERO honk delay during april fools for that machinegun honking.

**Comment by GreatBigFailure** [comment]
> Requesting for the bike horns to have exactly ZERO honk delay during april fools for that machinegun honking.

Requesting attaching a traitor horn to a baton gatling to machine gun fire honk batons

**Comment by Eneocho** [comment]
> Requesting attaching a traitor horn to a baton gatling to machine gun fire honk batons

Unironically a good idea, make it happen.

**Pull request merged**
