### PR TITLE
Chem puddles

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds chemical puddles (SERIOUSLY NEED A SPRITER FOR THIS ONE)

You splash something on the floor? It doesn't just magically disappear, it leaves a mess that needs to be cleaned up.

### CODE REVIEW

**Comment by Pathid** [comment]
Thought I should mention that certain reagents like radium and welder fuel already leave visible puddles of a sort and having this overlaid on that might look funky.

**Comment by Ephx1** [comment]
Couldn't you just use the already existing "green slime" you get when tossing chems on the floor occasionally and tweak the color as necessary?

**Comment by Kurfursten** [comment]
Why not just use a gray version of the radium spill and color it based on reagents like we do with beakers?

**Comment by Blithering** [comment]
would this make lubing more apparent? or would it keep the current occasional wet floor sheen?

**Comment by MadmanMartian** [comment]
That's a good point

**Comment by praisenarsie** [comment]
was this inspired by hippie's chempiles :thinking:

**Comment by DamianX** [comment]
Feel free to reopen it whenever you want.

**Pull request closed without merging**
