### PR TITLE
Hotfix for revsquad being picked by mixed causing bugs

### LINKED ISSUE #11677: Revsquad appears in mixed mode
So I set up mixed to pick 3 modes at random
it picked revsquad
revs did not show up in tator menu
shuttle could not be called
r i p

### PR DESCRIPTION
**Pull request by gbasood**
Resolves #11677

Since I dont want to add support for revsquad in mixed because mixed is a nightmare

### CODE REVIEW

**Comment by clusterfack** [comment]
Doesn't mixed have some sort of exception list or something

**Comment by gbasood** [comment]
@clusterfack doesn't work when mixed is manually set

**Comment by ghost** [comment]
Mixed can manually be set with revsquad; this is a bad fix if this just means that it doesn't occur

**Comment by gbasood** [comment]
@DrCelt Actually revsquad doesn't show up in the manual configuration for mixed, or it shouldn't according to code

**Comment by gbasood** [comment]
Better idea

**Pull request closed without merging**
