### PR TITLE
Removes mindswap apprentice

### PR DESCRIPTION
**Pull request by Dacendeth**
Mindswap apprentices are something i've heard complaints about and I dont like myself. I had planned to replace it with something but i was afraid that wasnt atomic, so I think i'll add more apprentice types after this PR goes through or gets thumbs down to death.

:cl:
 * rscdel: Wizards have stopped training apprentices in mindswapping.

### CODE REVIEW

**Comment by Buchse** [comment]
Fuck apprentices. All my homies hate apprentices.

**Comment by GreatBigFailure** [comment]
Usually I'm against content removal but mindswap apprentices is pretty universally hated. Not only that but because of the current mindswap glitch it's also unplayable and kicks people out of the game. 
Just gotta replace it with something interesting like you said.

**Comment by Viciousaurus** [comment]
Remove mindswap apprentices
Add grease apprentices

**Comment by AutismSpider** [comment]
grease and wall of fire apprentice

**Comment by juanototo2** [comment]
Add cleric apprentices with heal other and or robeless.

**Comment by SonixApache** [comment]
mindswap apprentices are among the best ways to leave a lingering effect on the crew

**Comment by Kurfursten** [comment]
R word...

**Pull request merged**
