### PR TITLE
Magboots on the supply system.

### PR DESCRIPTION
**Pull request by Eneocho**
Magboots on the cargo request system, under clothing at 100 credits per crate. 
:cl:
 * rscadd: A new cargo crate, available under Clothing for 100c, which contains 1 (one) pair of magboots.

### CODE REVIEW

**Comment by BomberBro** [comment]
spacesuitcrate
I'm not sure if I agree that adding magboots makes it worth 75 credits less

**Comment by Eneocho** [comment]
> 
> 
> spacesuitcrate
> I'm not sure if I agree that adding magboots makes it worth 75 credits less

Oh shite, didn't remember that one was a thing, I rarely check the clothing screen on the cargo requests. How about magboots on a separate crate, worth 100?

**Comment by BomberBro** [comment]
That's for the proles to decide, I personally think that magboots should be timegated to like an hour into the round for cargo if they were added at all so you could buy them after the usual round attrition while negating the most powergamey elements. Then again, magboots aren't exactly rare and many jobs have access to them, so who knows.

**Comment by Dacendeth** [comment]
magboots should be their own box if anything.

**Comment by Eneocho** [comment]
> 
> 
> magboots should be their own box if anything.

Done.

**Comment by Blithering** [comment]
I think the price needs to go up, for reference the ghetto magboot food costs 110

**Comment by Eneocho** [comment]
> 
> 
> I think the price needs to go up, for reference the ghetto magboot food costs 110

The magbites are expensive because they're a powerful item as the prime source of cheesy gloop, the same way the choco coins are worth 75 despite having shitty nutriment, because they can be used as proper coins.

**Comment by juanototo2** [comment]
Finally. Glad to see the death of non-command exclusive irreplaceables is at hand.

**Comment by MadmanMartian** [comment]
Magbites were not intended to be "the prime source of cheesy gloop", they were a meme chemical to avoid putting magboots in the cargo shuttle

**Comment by Eneocho** [comment]
> 
> 
> Magbites were not intended to be "the prime source of cheesy gloop", they were a meme chemical to avoid putting magboots in the cargo shuttle

I meant that now it's main purpose is for cheesy gloop, not the magbooting, since anyone can break into EVA and steal some boots. This just aims to add a source of boots. I think that 100 credits is a fair price (considering the whole spacesuit being worth 200), though if that's problematic, I can raise it t 150.

**Comment by Blithering** [comment]
Honestly, magboots are worth more than a cheapass grey space suit, I'd up them to 200 at least.

**Comment by Eneocho** [comment]
> 
> 
> Honestly, magboots are worth more than a cheapass grey space suit, I'd up them to 200 at least.

Fair point, if we take that into consideration it'd be better to reduce the spacesuit's price to 100 and up the boots to 200, since you can already make ghetto spacesuits, but lets see what everyone else thinks.

**Comment by KingofHONK** [comment]
Zas should remain a life threatening mechanic. This PR cheapens that.

**Comment by Kurfursten** [comment]
Sometimes we just need to make a call on these things when it's close. I'm going to uphold the status quo this time.

**Comment by Eneocho** [comment]
> 
> 
> Sometimes we just need to make a call on these things when it's close. I'm going to uphold the status quo this time.

I was thinking of closing it and making a new PR with updated prices (200c for the magboots, 150 for the suit).

**Pull request closed without merging**
