### PR TITLE
Gives the paramedic science access (for telescience)

### PR DESCRIPTION
**Pull request by TGFH**
Am I doing this right? I have no idea because I'm not used to this github witchcraft.
This PR is intended to give Paramedics access to telescience, but that's just generic science access so that's what I've done. 
Our most popular map, Box, has no telescience setup in medbay (unlike its cooler brother, Roid). This is a quick way to remedy that issue.

Pros: Increases your chances of being recovered if you get killed or injured  
This will probably make science mains angry

Cons: None

Requested by PrimeD

https://cdn.discordapp.com/attachments/245856976217702400/846601757798957076/unknown.png

### CODE REVIEW

**Comment by jwhitak** [comment]
Can this access be given to just regular paramedics? Brig medics don't need this. 😏

**Comment by BomberBro** [comment]
The solution to this "problem" would be to give the maint door to telescience paramedic access, not giving them full science. I think either way is completely unnecessary though.

**Comment by west3436** [comment]
remove the paramedic hardsuit and boots then since they'll just play the bluespace claw game from now on

**Comment by gurfan** [comment]
mister harris is right on both counts

**Comment by KillFurries** [comment]
Telescience is stupid and takes all the fun out of the game. If you give a paramedic access to telescience it means people expect them to do the fucking awful boring telescience shit and the paramedic can no longer use the excuse that he doesn't have science access. This is optimizing the fun out of the game. Instead of going to recover bodies you want the paramedic to sit in front of a console and do this shitty minigame. You might as well be giving miners a little cuck console that they sit in front of and teleport the ore from the roid into cargo without ever setting foot on the roid, this isn't fun at all.
A paramedic has a spacesuit, an SPS and he can get his hands on a jetpack on most maps. Go out there and recover the body yourself you lazy shit.

**Comment by Eneocho** [comment]
I've just noticed that all of Science (perhaps not robotics) are shitty soulless minigames. Xenoarch is some gay speedrun powergaming and you have your meme tools, RnD is following a literal checklist, telesci is claw game powergaming, xenobio is a soul sucking drag'n'drop.

**Comment by Dacendeth** [comment]
The real answer is to just move telescience to paramedics on every map.

**Comment by DamianX** [comment]
remove telescience

**Comment by PrimeDSS13** [comment]
at this point we might as well give paramedics all access

**Comment by ghost** [comment]
just change the req_access on tscience doors facing maint to allow paramed access too, its better that way

**Comment by Theophrastus1** [comment]
Realistically Telescience should be operated by a science team member in cooperation with the paramedic. Have to remember we're a space station that is often probably working together. Nobody's stopping the paramed from getting a toolbelt and tools to hack the door, law 2'ing into telesci, or getting access from someone with HoP access. Needing the access automatically is for losers.

**Pull request closed without merging**
