### PR TITLE
Buffs air conditioning & bugfixes it

### PR DESCRIPTION
**Pull request by brndd**
These used to have a temperature adjustment rate of 500 joules/second. 1 joule is 0.000947817 BTU, the unit commonly used on air conditioners in the real world. 500 joules/second is therefore about 1706 BTU/hour. If you're familiar with air conditioning units, you'll know even the cheap window units are usually at least 12000 BTU/h. In other words, spess air conditioning is really bad.

This increases the cooling rate to 5000 joules/second, which is about 17000 BTU/h. That's what you'd find on a reasonably powerful window AC unit.

Also fixes a bug where these would never heat rooms up. What kind of a dummy confuses kelvin with celsius haha?? (it was probably me)

:cl:
 * rscadd: Air alarms are now equipped with a 17000 BTU/h air conditioner instead of a 1700 BTU/h one. This cooling now uses power too.
 * bugfix: Air alarms can now actually heat rooms above 90 K (their range is -40 to 90 °C).

### CODE REVIEW

**Comment by brndd** [comment]
Also for comparison the separate draggable space heaters and air conditioners seem to be about 4 times as powerful (20000 joules/second or some 68000 BTU/h).

**Comment by MadmanMartian** [comment]
dang it, I'd balanced powercreep ambient temperature draw over that amount.

**Comment by brndd** [comment]
if you want to rebalance it for this new amount make a PR on this PR's branch and I'll include it

**Comment by MadmanMartian** [comment]
alright. Of note, I don't think the air alarm actually tries to draw the power from APCs that it adds to the environment, so you just get free energy.

Can you remedy this while I work on powercreep?

**Comment by MadmanMartian** [comment]
Also, space coolers being able to output that much can cool a supermatter shard. That's crazy. Does it even draw that much from its internal cell?

**Comment by brndd** [comment]
Alright, they use power now. I gave them a 300% efficiency rate which is in the ballpark of what you'd find on heat pumps in the real world, ie. they drain 1/3rd the power from the grid as they put out into the atmosphere in joules.

This does leave some room for abuse because these aren't *real* heatpumps, so you could still generate power off of this heating (but then again you might be able to do that anyway because I'm pretty sure the TEG has a >100% efficiency now too thanks to brainless buffs)... but if you really want to make an engine out of air alarms, be my guest.

**Comment by brndd** [comment]
Fixed another bug while I was at it where setting a target temperature higher than the maximum safe temperature currently defined would cause the air alarm to not do anything. Now it heats up to the maximum safe temperature and stops. Or cools down to the minimum, it goes both ways.

**Comment by Exxion** [comment]
But of course they're weaker than window units
Violating physical laws is hard

**Comment by brndd** [comment]
They just transfer the heat into space or something. And when they heat the room they transfer it from the hell dimension (to be implemented)

**Comment by MadmanMartian** [comment]
hell dimension's semi implemented, look at the description for some of the prestidigitation bundle spells

**Comment by Kurfursten** [comment]
Had to restart travis

**Pull request merged**
