### PR TITLE
aaaaaaaaaaaa Also adds mind inheritance aaaaaaaa

### PR DESCRIPTION
**Pull request by ghost**
Apparently spider queens were recursively evolving and deleting themselves, causing the server to slow waythefuck down

### CODE REVIEW

**Comment by Probe1** [comment]
image

Do this, but quickly.

**Comment by Aurx** [comment]
>null
>effectively the same as zero

[TRIGGERED]

**Comment by clusterfack** [comment]
Yeah, in an if check it is. Learn to code.

**Comment by Aurx** [comment]
I considered adding a line explaining that yes, it's equivalent inside an if() and that I'm making fun of splitting hairs.  But I figured nobody would be so spergtacular as to not get the joke.  Guess I've been proven wrong.

**Pull request merged**
