### PR TITLE
Taxistation power changes

### PR DESCRIPTION
**Pull request by ComicIronic**
Added portable batteries to all three Taxistation stations. The non-engineering batteries start with 2e6 charge.
Added charging ports to engineering.
Made rad collectors start anchored.
Edited SMES code to use a general system for starting with a terminal.
Reduced portable battery max capacity to 3e6 from 5e6. This is to stop them outclassing SMESs.
Engi station
battery_engicharge
Medsci station
battery_medstation
Secstation
battery_secstation

### CODE REVIEW

**Comment by PJB3005** [comment]
:+1:

**Comment by FudgePucker** [comment]
Does this mean that taxi station might be ready to be put into map rotation?
Or is there still somethings broken?

**Comment by ComicIronic** [comment]
There's nothing now broken to my knowledge, but only really playtesting will tell.

**Comment by Exxion** [comment]
I've always thought Taxistation looked interesting
I'd love to actually get to play it

**Pull request merged**
