### PR TITLE
Firebirds can no longer be rotated by ghosts

### LINKED ISSUE #8218: Ghosts Can Rotate Firebirds
Since vehicles are children of `/obj/structure/bed/chair/` this probably applies to all vehicles.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #8218

### CODE REVIEW

**Comment by Skullyton** [comment]
:+1: For using a variable check rather than some snowflake nonsense

**Comment by Exxion** [comment]
They can't be rotated by ghosts... or anyone else, including the rider (other than by moving)

**Comment by CptWad** [comment]
Does this extend to janicarts?

**Comment by Exxion** [comment]
No, just the firebird

**Comment by 9600bauds** [comment]
If you're just going to remove rotation altogether, seems like you could do "src.verbs -= rotate()" in New().
Right now you're still leaving in the rotate verb in right-click, just that it does nothing.

**Comment by Exxion** [comment]
Actually I'm an idiot and you should ignore what this comment originally said because I'm an idiot who forgot how my own damn code worked

**Comment by Exxion** [comment]
Are you still working on this or should I do it?

**Comment by ghost** [comment]
Go ahead and do it @Exxion you've probably got a better idea.

**Pull request closed without merging**
