### PR TITLE
Box fixes 12/6/16

### LINKED ISSUE #12668: ATM in Cargo office spawning withdrawn cash wrong
(WEB REPORT BY: qbone REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 19128f20e69e267d413ddaf91722b1146516a4c9 

>General description of the issue
ATM in Cargo spawns withdrawn cash in grille between Warehouse and Cargo office instead of at the ATM, or in front of it. 

>What you expected to happen
I expected the Withdrawn Cash to appear where the ATM is.

>What actually happened
It spawned in the grille to the left and behind the ATM, I had to break through the glass and grille to get it.

>Steps to reproduce if possible
Withdraw cash from the ATM in Cargo Office

### LINKED ISSUE #12671: Disposals Access
At some point, on Box, someone decided to restrict just the right-hand door to final disposals. I'm not sure who has access to it now (Janitor?) - but the QM and Cargo Techs can't get in anymore from that side, but they can waltz in the other entrance.

Please give cargo back access, sometimes a crate gets sent to disposals by mistake.

### PR DESCRIPTION
**Pull request by Probe1**
(Box) Replaces double sided windows at tcomm sat with single sided plasma windows. https://github.com/d3athrow/vgstation13/pull/12695#issuecomment-265267027
(Box) Fixes Quartermaster ATM
(Box) Fixes Disposal Access for Cargo
(Box) Renames locker bathroom doors from "Unit 1" to "Stall 1"

Closes https://github.com/d3athrow/vgstation13/issues/12668
Closes https://github.com/d3athrow/vgstation13/issues/12671
Also addresses a comment in a previous PR https://github.com/d3athrow/vgstation13/pull/12623#issuecomment-264594190

🆑 

* bugfix: Cargo personnel once again have access to disposals on Box.

### CODE REVIEW

**Comment by Probe1** [comment]
If I see conflict I'm going to rage quit my life.

**Comment by Probe1** [comment]
dreamseeker_2016-12-06_15-44-49

**Comment by Durgen** [comment]
Can the Gooncode replaced with a pomfcoin? There was some discussion of that in #12623

**Comment by Probe1** [comment]
@Durgen make a separate issue and see if anyone has any strong feelings about it.  I don't really wanna get yelled at cause the decision to replace it was buried in PRs not about the topic.

BUT I do agree it should happen.

**Comment by Probe1** [comment]
The trap is a bit too much.  Just on the HoP side.  As well, I thought we were talking about shutters not blast doors.

**Pull request merged**
