### PR TITLE
Tweaks to restricted/protected roles stealth modes

### PR DESCRIPTION
**Pull request by rmariani**
I removed Security Officer and Detective as protected jobs from changeling and traitor.

The arguments for them not being equal cult and vampire are good and the community wants that, so I merely moved detective and sec officer to protected status from restricted status. This goes in line with entire motivating principle of SS13: it isn't a completely balanced game, and players should always be paranoid. Not being able to rule more roles out as an antag while increase paranoia. (The "protected" designation greatly lowers the chance of a role being the antag in question, while "restricted" completely bars them.)

Much of he reasoning behind protecting or restricting jobs in these rounds is their armory access. Neither detectives nor security officers have armory access. Expanding possibilities for antagonists is a good thing in SS13 to keep the air of paranoia alive, so players can't just rule huge swaths of characters out. Similarly, detective and sec officers don't have power over departments like heads do for cult rounds. If it's safe for HoP, CE or QM to be cultists without a fear of imbalance, these roles will be safer yet, but the greatly lowered frequency creates a good balance between interests.

### CODE REVIEW

**Comment by CptWad** [comment]
So this has a chance of being pulled sooner, due to feature freeze, he originally posted this here #7710 and redid it.
Id be okay with how it is now. If any horrible shittery happens because of the change its not like we cant fix it quickly.
It was pretty well discussed already so I don't think a [Discussion] is necessary but if people have gripes then I guess its warranted.
IMO this will probably lead to more people playing sec roles. I can also live out my fetish of being a charles bronson detective with a real revolver. 
:+1:

**Comment by ghost** [comment]
Hold votes on the server. Antags getting free tazer, baton and security record access etc. in addition to their TC is incredibly overpowered.

Remove TC for antag sec and it would be fine.

Thankfully this wont get merged any time soon thanks to feature freeze, plenty of time to realize how much of a bad idea this is.

**Comment by Kurfursten** [comment]
:-1: I will always be against roundstart loyalty implanted cultists. I don't agree with it on a fundamental level.

> Much of he reasoning behind protecting or restricting jobs in these rounds is their armory access.

Why do you keep saying this? Has anyone said this but you? I know you're not getting that from the code comments which say that NT has better background checks for important jobs. You aren't getting it from the last PR where no one said that.

> If the QM and CE can be cultists, why not security?

Because they're not implanted. It has nothing to do with department leadership. I can't see how a CE or QM has any advantage over a Cargo Tech or Engineer in terms of converting people, but a security officer has a massive advantage in that he can fool people with his loyalty implant (not to mention the already listed advantages of taser, cuffs, etc.). People will be sure he's already safe because they can see the implant on SecHUD.

> "The community wants that"

I saw that poll, and it was 66% for "implanted roles should not be roundstart sec", not "should rarely be roundstart sec".

**Comment by rmariani** [comment]
You "always being against it" isn't an argument. This is about the issues for improving the game, not how much a change upsets you.
Because being able to rule out entire swaths of the station in a game mode because a guy "is always against it" on github isn't fun. This game is about fun, it's about paranoia, and it's not about esports-like balance.

Protected status is a compromise between some roles being overpowered for some game modes (which will _always_ happen for this kind of game) and the game just not being fun if you try to strangulate it with draconian, metagame restrictions

Anyway, come to think of it, IAA should be moved from restricted in protected for cult as well.

TermedClepe: HoP can already be every one of these roles, and not even protected. He effectively has all access (including armory) and starts with an e-gun.

**Comment by Imagebard** [comment]
>Loyalty Implanted personnel being cultists

Bug Report: Useless implants nicknamed "Loyalty" appears on Warden Office at roundstart.

**Comment by Kurfursten** [comment]
Expressing my opinion is not an "argument" but is certainly a valid statement. I notice you did not chastise the person who gave you a +1, perhaps because you only dislike opinions when they disagree with you? But more to the point: your own first paragraph doesn't have an argument in it either. A "guy on Github" (you) thinks it's fun when cultists can be loyalty implanted at round start. That's an opinion too. You see how this gets us nowhere? You haven't produced _anything_ but opinions on what makes the game more fun. Of course the opinions of everyone involved matters - yours, mine, and the playerbase (which I assume you are a part of but you've rather violently opposed identifying yourself, so in truth we don't really know if you play here).

So let's talk facts. You just told TermedClepe that the Head of Personnel can be a cultist, which tells me you haven't even read the full line of code that you're changing. That's a fact. You've said the polls show that people want implanted changed to protected rather than kept on restricted, but that's incorrect. The fact is that the votes pointed toward loyalty implanted characters remaining restricted from cultist at shift start. So there are your facts without opinions.

**Comment by rmariani** [comment]
I am not talking about HoP cultist, I am talking about HoP being an unprotected antag in general.

**Comment by ghost** [comment]
HoP being able to be antag is also bad and should be removed.

Proper solution to antag rolls is to have the game mode 

FIRST PICK PEOPLE FOR ANTAGS
THEN PICK PEOPLE FOR JOBS BASED ON FIRST PICK

This way everyone can play any job they want and still get equal chance of rolling any antag they want regardless of job protections.

**Comment by rmariani** [comment]
Lol, players having various advantages based on their roles is a feature of the game. HoP is at a disadvantage for being so high profile and being expected to be in his office. Assistants have no "technical" advantages but can run around doing nonsense and nobody bats an eye. When I play engineer and get antag, I can get I can get cable cuffs and a stun prod within two minutes. This isn't an issue, it's just part of the game where players can draw the gameplay experience from a really dynamic and malleable world. 

Fun > balance, at least in SS13.

**Comment by Kurfursten** [comment]
Access to stuns is hardly the issue at hand: it's the ability to be trusted that a security officer has. People get batoned in a public place and scream for help and no one bats an eye, but if an engineer kidnaps someone all the validhunters come running.

But to address your central point (which consists of 'the game will be more fun this way'): fun is subjective and a larger number of people have said the game is more fun for them when implanted roles do not start as cultists. So who are you to tell them how to have fun?

**Comment by rmariani** [comment]
Then player behavior needs to change; we can’t develop a game around a playerbase’s naivety. Nobody should be able to -rule out- security being actual bad actors, rather than just (meta) shit sec. Players screaming “SEC TRAITOR” or “SEC CULT” while being dragged away shouldn’t be able to just be dismissed on a metagame level by any non-new players. So the very point you raised is a testament to the atmosphere of the game being degraded by schoolmarmish changes being made to game mechanics under the auspices of making the game “fair.”
The idea that everyone needs a guarantee that sec should be good guys in every single round is preposterous. I am just erring on the side of fun in the fun-vs-balance debate in a game which I think is completely underpinned by erring on the size of unpredictable, paranoid, dynamic fun at the expense of balance. I think it's by pretty reasonable compromise to just shift the lowest-threat restricted roles to protected.

**Comment by Arthurdentist** [comment]
Security officers and detectives shouldn't be able to be roundstart cultists because of their security implants, I think its honestly as simple as that. I note you didn't make it possible for Internal Affairs Agents to be cultists either, which strikes me as being really inconsistent. 

I don't mind them being vampires because I don't believe vampires are really bothered by Loyalty implants in any way.

**Comment by rmariani** [comment]
The IAA thing was an oversight. They should be moved to protected, or, in my opinion, completely unrestricted, being one of the most useless roles in the game. What do others think?

I get the in-game explanation, but in the end gameplay > lore for design.

**Comment by LordMyroc** [comment]
> players should always be paranoid

Why?

**Comment by Kurfursten** [comment]
How can you seriously in the same post say that you are on the side of fun and also say that we shouldn't design the game for our players?

I get that sometimes unpopular decisions have to be made, don't get me wrong - but antag balance isn't the place to force change.

**Comment by rmariani** [comment]
LordMyroc - are we really having the discussion of why paranoia is important in the game of Space Station 13? I mean, do you not know why almost every round mode is "secret" and players don't get a message telling them exactly who the antags are?

**Comment by gbasood** [comment]
> The IAA thing was an oversight. They should be moved to protected, or, in my opinion, completely unrestricted, being one of the most useless roles in the game. What do others think?

They're loyalty implanted at start, and they're intended to be one of the few roles on the station that will NEVER be traitor because of it.

**Comment by LordMyroc** [comment]
Firstly, I didn't say paranoia wasn't important, I was saying that people being paranoid about everything and everyone all the time is a bad idea. All it does is encourage people to never interact with anyone else on the off chance that they're an antag out for your blood. And being able to trust one particular department on the station doesn't suddenly eliminate paranoia from the game. Partially because there's still a myriad of other people out there who you can't immediately trust, and partially because you being able to trust security does not mean that security can trust YOU. It's not like it's unheard of to have trusted roles in a mafia/whodunit/whatever-the-hell-you-choose-to-call-that-kind-of game.

Secondly, if we are going to define what type of game Space Station 13 is we'll be here all week, and you'll most likely see a different answer from everyone involved. Everyone plays this game for a different reason, and prefers different flavors to his 2d spessman experience. You seem to want the game's mafia themes to be more important. That's an alright opinion for you to have, but it seems so far that most of the server disagrees with you.

**Comment by Arthurdentist** [comment]
@gbasood 

IAA can already be traitor and indeed have their own job specific traitor item (briefcase gun)

**Comment by rmariani** [comment]
@gbasood
IAA can be traitor, changeling or vampire. If they couldn't be, I would requested it to be so in this PR.

@LordMyroc Why do you think optimizing Mafia aspects degrades the rest of the experience? You haven't given an argument about why this PR is bad but traitorling captain/HoP is acceptable. "Nobody should ever fear for their character's round-long life because that might not be why they play" is a terrible line of reasoning precisely because the unclassifiable pluralism that is SS13's nature.

**Comment by LordMyroc** [comment]
Personally if you ask me antag captain/HoP (and loyalty implanted people in general) shouldn't be a thing either, but I don't speak for the entire server so I'm not going to elaborate the point further.

And like I said earlier, the more you encourage people to be paranoid, the more you take away from the rest of the game as you discourage people from talking to and interacting with each other. In a game that is almost all about player interaction, I don't need to tell you why that's a bad idea. At the same time, having antagonists is important in order to liven up rounds and not make the game a grinding job simulator in space. You need to strike a careful balance between the two, and I don't think this change is very conductive to that.

But what I think doesn't even matter. The server was polled about it, and the majority were opposed to the change. Why are you still trying to push for this change when most of the server is against it?

**Comment by gbasood** [comment]
well I'm dumb

**Comment by ihadtoregisterforthis** [comment]
:-1: No thanks

**Comment by ghost** [comment]
Not a big fan of loyalty implanted roles that can't usually be loyalty implanted but otherwise :+1:

**Comment by rmariani** [comment]
If I closed this PR and put detective/sec officer back in restricted _but_ unrestricted IAA (because they are useless), would people be more amenable to this change?

**Comment by Imagebard** [comment]
IAA gets Loyalty Implants roundstart

**Comment by rmariani** [comment]
Sure, but there are no gameplay reasons for them to be excluded from a role. That trumps lore reasons

**Comment by SangriaMonkey** [comment]
All a ling needs is one pair of cuffs to faceroll the server in twenty minutes. Full sec regalia would make them very hard to notice.

**Comment by rmariani** [comment]
Cable cuffs are, for all intents and purpose, identical to handcuffs. Anyone can make them, I think you've been playing ling wrong.

**Comment by SangriaMonkey** [comment]
Cable cuffs are a lot easier to slip out of. If a security ling is chainstunning you in regular cuffs you're not getting away period unless there's some serious greytiding going on.

**Comment by rmariani** [comment]
Cable cuffs take half the time to break out of, which is like a minute. That's orders of magnitude more time than is needed to interrupt a breakout attempt

**Comment by ghost** [comment]
Security cuffs are 2 minutes.
Cable cuffs are 30 seconds.

**Comment by FudgePucker** [comment]
Also another thing to consider is security is trusted and NEEDS that trust, if an engineer trys to stun you, and you murder him, it is valid. If a security officer tries to stun you, and you murder him you are banned for grayshittiry.

If officers can be antags then they

**Comment by FudgePucker** [comment]
FUCK THIS FUCKING PHONE

Can't arrest people because stuns = death. People would only play sec for antag roll and suicide if they don't get it.

**Comment by SangriaMonkey** [comment]
Stuns don't equate to instant death. Most idiots forget to keep you stunned or are too busy writing their ebin villainous monologues to notice you resisting out of cable cuffs. The issue with security lings is the fact that when 90% of players see someone getting dragged by a uniformed officer in cuffs, they don't even bat an eye, whereas Urist McScrubgloves the engineer will get his shit kicked in when he walks by a crowd with a screaming captive.

**Comment by gbasood** [comment]
> People would only play sec for antag roll and suicide if they don't get it.

I feel like that's a problem for admins, though

**Comment by rmariani** [comment]
Naivety of players shouldn't affect design. Players should (and will) adapt.

Anyway, I am closing this re-restricting sec and detective for cult in a new PR, but otherwise keeping the changes. That seems to be the biggest point of contention.

**Pull request closed without merging**
