### PR TITLE
doubles the time it takes to smoke a pipe

### PR DESCRIPTION
**Pull request by toomykins**
I don't like having to take out my pipe, refill it and relight it every other minute.

:cl:
 * tweak: pipes can now be smoked for double as long.

### CODE REVIEW

**Comment by angryturnip** [comment]
more efficient sucking

**Comment by Eneocho** [comment]
Skill issue just refill it with ambrosia

**Comment by jwhitak** [comment]
Regular cigarettes are 300, cob corn pipes are 400, blunts are 420. I think 200 is still too low, and this PR could easily justify 400.

**Comment by toomykins** [comment]
i can't increase it now! people have already voted for the 200 second mark, i can't just increase it to 400 and hope their support stays the same... this is a democracy, damnit!

**Pull request merged**
