### PR TITLE
Robodropper

### LINKED ISSUE #7293: Medborg Industrial Dropper does not work properly
You can use it to transfer stuff between containers but when used on a mob you get the message about squirting something into someones eyes but nothing is actually happening. No reagents are transferred and the dropper stays at full capacity.

This might affect other droppers as well but I've only tried it with medborgs.

### PR DESCRIPTION
**Pull request by clusterfack**
No longer has a specizlied afterattack proc that functioned identically except for the fact it was far inferior and buggy.
Fixes #7293

### CODE REVIEW

**Comment by BestName** [comment]
Thank you. According to some nerd in deathchat this has been broken for a while but no one has bothered to report it.

**Comment by 9600bauds** [comment]
>this has been broken for a while but no one has bothered to report it.

HMMMMM that sounds familiar

**Comment by BestName** [comment]
You forgot to make it a child of dropper. Now it doesn't work at all.

**Comment by clusterfack** [comment]
Ah yeah whoops Ill fix that

**Pull request merged**
