### PR TITLE
Revert the awful fucking chair sprites holy shit

### PR DESCRIPTION
**Pull request by d3athrow**
Reverts d3athrow/vgstation13#7992

### CODE REVIEW

**Comment by SkowronX** [comment]
honk

**Comment by ghost** [comment]
Custom vote started by DrCelt.
The new chairs are
Type vote to place your votes.
You have 60 seconds to vote.

Vote Result: Awful but still better than the old chairs with 16 votes
Great, they should stay the same. had 4 votes
Awful, and should be changed back had 15 votes

**Comment by ghost** [comment]
They also look awful in game, I apologise for supporting them everyone

Still better than the old chairs though

**Comment by ghost** [comment]
The new chairs are bad. Bring back the old chairs.

**Comment by Zth--** [comment]
Still better than the old ones

**Comment by Shadowmech88** [comment]
:+1: x :100:

**Comment by ghost** [comment]
I already have perfected clicking on the old ones to unbuckle, how will I powergame with chairs now?

**Comment by 9600bauds** [comment]
Altclick em

**Comment by NigglyWiggly** [comment]
Thank fucking god

**Comment by Boxe** [comment]
>They also look awful in game, I apologise for supporting them everyone
>Still better than the old chairs though

no fuck you

**Comment by ghost** [comment]
@Boxe You've not played the game since like last year go home

**Comment by Praecordia** [comment]
who thought these new chair sprites were a good idea seriously

**Comment by Boxe** [comment]
@DrCelt http://game.ss13.moe/logs/2016/02-February/04-Thursday.log


[16:25:47]ACCESS: Login: Boxed_I/(Isaac Harrow) from [NOPE] || BYOND v509

eat my fat cock

**Comment by NigglyWiggly** [comment]
@Praecordia 
Dylan

**Comment by gbasood** [comment]
Wait what
When I merged these I must've not been paying attention to the actual icon change I didn't think they overwrote the default icon states
Fuuuuck

**Comment by 9600bauds** [comment]
Well it doesn't really help that the PR had little info and one tiny image with no in-game preview

**Pull request merged**
