### PR TITLE
Adds Gravy to Pork Tenderloin

### PR DESCRIPTION
**Pull request by Cartlord**
I'm adding 4u of Gravy to Pork Tenderloin, because it takes Gravy to make. I chose 4u because a rise n' shiny requires 5u and contains 2u, and I figure doubling the input should result in doubled output.
**I did not test this**, but I figured I wouldn't need to, since I only changed one line and made sure it was consistent with other lines in the file (I actually just copied the line from the rise n' shiny's contents and changed the 2 to a 4).
:cl:
 * tweak: Pork tenderloin now contains gravy.

### CODE REVIEW

**Comment by Eneocho** [comment]
Should work fine.

**Comment by ghost** [comment]
> I did not test this

**Comment by WindowsErrors** [comment]
hey i don't test things like, 60% of the time and you don't see anyone calling me out for it

**Comment by Eneocho** [comment]
> > I did not test this

Come on man, literally a copypasted line. It's not like he made a whole puddle system.

**Comment by Eneocho** [comment]
> > > I did not test this
> 
> Come on man, literally a copypasted line. It's not like he made a whole puddle system.

**Pull request merged**
