### PR TITLE
Added the defective cloning pod to Dorfstation's arrivals shuttle

### PR DESCRIPTION
**Pull request by DeityLink**
dorfpod

Also fixed time of death being incorrect on ghosts that came from a decapitated head.

:cl:
* rscadd: Dorfstation now features a defective cloning pod among the other ancient cryogenic pods. Ghosts of players who died can click it at least 10 minutes after they died to respawn as if they came out of a cloning pod. However this means respawning with clone and brain damage, and a guaranteed genetic disability. Therefore you can decide for yourself whether to wait and preserve your identity, or respawn with a new identity from an ancient cryo pod. Alternatively, wait for the crew to set up medbay with a proper cloning pod.

### CODE REVIEW

**Comment by Dacendeth** [comment]
Are there any intercomms in that room, or any other way to scream for help since you come out with clone damage?

**Comment by Jackreturnswithaveangenace** [comment]
Cool idea.

**Comment by DeityLink** [comment]
> 
> 
> Are there any intercomms in that room, or any other way to scream for help since you come out with clone damage?

Nope, but after testing a few times myself the damage wasn't so bad that I couldn't walk out of there myself. Worst case scenario I couldn't get up but I could still crawl to the ladder. That should be enough to get someone's attention right?

**Comment by DeityLink** [comment]
Alternatively the crew can build a treadmill and cryopod in front.

**Comment by mrflarg** [comment]
nice sprite

**Comment by Jackreturnswithaveangenace** [comment]
I'll wait until this is merged or not before doing more mapping as it makes things a bit tedious, plus that's more time to listen to feedback.

**Pull request merged**
