### PR TITLE
buffs dionas by making them resistant to fire

### PR DESCRIPTION
**Pull request by diegoxt45**
dionas is just too weak rn

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Based

**Comment by d3athrow** [comment]
are you stupid

**Comment by ShiftyRail** [comment]
1) This is quite a bold change, going from 2.5 to 0.33 means they take 7.5 times less damage (!) and 3 times less damage than a human (!!!)
2) You are only buffing the dionae nymphs, not the species
3) Dionae are meant to be weak
4) wtf is this

**Comment by diegoxt45** [comment]
> 1. This is quite a bold change, going from 2.5 to 0.33 means they take 7.5 times less damage (!) and 3 times less damage than a human (!!!)
> 2. You are only buffing the dionae nymphs, not the species
> 3. Dionae are meant to be weak
> 4. wtf is this

yeah sorry bro i'm currently fixing that as we speak

**Pull request closed without merging**
