### PR TITLE
Makes proximity sensors 50% less spooky.

### LINKED ISSUE #6051: Ghosts can trigger proximity sensors
Revision: 56751dda5a51e47843b6c15cd06eec49146e4291

Ghosts are able to trigger proximity sensors - or at the very least, proximity sensors as in the proximity sensor-speaker assembly shown below.

ghosts can trigger prox sensors

When ghosting into the proximity sensor's trigger area (in this case, a 3x3 area around the sensor) or moving inside this area as a ghost, the proximity sensor triggers (which in this case means activating the speaker).

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes #6051

### CODE REVIEW

**Comment by clusterfack** [comment]
Beams have the PROXMOVE flag?

**Comment by PJB3005** [comment]
I don't know but the code already ignored beams specifically so I figured I'd keep it.

**Comment by ihadtoregisterforthis** [comment]
>removing spookiness on October

**Comment by PJB3005** [comment]
:^)

**Pull request merged**
