### PR TITLE
Emagging ID computers still does nothing

### LINKED ISSUE #6701: emagged hop id computer wont authorize
(WEB REPORT BY: 420africanamerican REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> dd634d27ebb33f64765287964d34c321bd024891
> General description of the issue
> when emagged the id computer doesnt let you change with any id
> 
> What you expected to happen
> emag
> let me use any id
> 
> What actually happened
> emag
> nothing
> 
> Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #6701

### CODE REVIEW

**Comment by PJB3005** [comment]
Better idea:

Make it so that if you emag an ID computer, it'll look like it authorized, and you can edit ID cards.

Except the changes to ID cards don't actually get done so if you're a dork trying to give yourself all access like this you'll just end up pranked.

**Comment by Imagebard** [comment]
>Emag actually breaking ID scanners

*Whoa there*

**Comment by Intigracy** [comment]
WYCI

**Comment by Probe1** [comment]
Write what your PRs actually do instead of just writing "Fixes"

copy the changelog if you're lazy.

**Comment by Intigracy** [comment]
The commit message is literally right underneath the OP.

Stop being lazy.

**Comment by Probe1** [comment]
Says the guy whos trying to close an issue without addressing it.  clean that shit up and show some pride this isn't a pub server.

**Comment by Probe1** [comment]
I believe in you intichan

**Pull request closed without merging**
