### PR TITLE
Zam Foodery Update and Condiments Deluxe

### PR DESCRIPTION
**Pull request by Optimism333**
## A Zammin' Day ##

Have you ever wanted your Zam food right NOW when you got it out of the cargo merch computer? Perhaps you were surrounded by a supermatter sea and unable to reach a microwave, but wanted to enjoy your last meal? Fret no more!

Introducing the Zam meal model mark 2! The meal is now preheated for you by the mothership and packed in an insulated box, so that when it is warped to you you need only take off the packaging and eat!

But that's not all. Zam Snax has developed its own line of condiments to pair with meals. We are introducing Zam's Mild Sauce as a new tasty food additive. Made with only the freshest mothership spices and sulphuric acid. For those greys who like to live more on the wild side, there is Zam's SPICY Sauce. Dangerously flavorful! Guaranteed to make your liver scream in higher doses! Please consume responsibly, and do not share with human friends. It hates human livers even more than grey livers.

And finally, every Zam meal now comes with a complimentary pack of Zamitos for additional snacking. Rejoice!

With all this good news is a small catch. Zam Snax is introducing it's first price hike. All meals will now cost an additional five credits. Praise the mothership, and all hail the Chairman!

### **Sprite Updates** ###
I've updated the sprites of all the Zam meals, the Spider Slider, and Moon Cheese to show food previews of the contents and further reduce the excessive copy paste of the Zam mascot. I think I'm happy where it will be now. It's on the Zam biscuit package, it's on the delivery bag, it's on the NotRaisins, and it's on the machine, but it's not on anything else. (Old is on the left, new is on the right)

TvDinnerComparison
ZamSnacksUpdates

### **Zam Meal Changes** ###

- Zam meals no longer need to be microwaved. They're like those fully cooked meals you can get at the market. Just unwrap and eat!
- Zam meals come with a packet of Zam's Mild Sauce and a packet of Zam's Spicy Sauce (more details on those below).
- Zam meals now come with a bag of Zamitos for additional snacking and hunger satisfaction.
- All Zam meals are 5 credits more expensive.
- An original Zam Steak and Nettles has returned to the code (the one with the 5u of Doctor's Delight), however it cannot be obtained anywhere currently. I'll probably turn it into a loot item for a grey-themed vault

### **New Zam Condiments** ###
ZamSpices
ZamSpicePackets

- **Zam Spices:** A simple reagent with a very small nutrition value, but it is necessary to make Zam Mild Sauce and Zam Spicy Sauce. It can be obtained in exotic condiments and is now present in Zamitos instead of salt or pepper. It cannot be created on the station.
- **Zam's Mild Sauce:** A sauce made by combining Zam Spices with Sulphuric Acid. It's surprisingly palatable for most species, hence the name. It has a mild nutrition value comparable to ketchup and mayonnaise.
- **Zam's Spicy Sauce:** A diluted toxin made by activating certain enzymes in Zam's Mild Sauce with strong acid and unstable mutagen as a catalyst. It has a slightly higher nutrition value than ketchup. Works as a grey version of hot sauce and is known to be very popular among mothership denizens. It's a terrible poison for all other species, and can even poison greys in quantities past 15u. I'll write a summary of how it works below if anyone is interested.

**Up to 15u**

- If grey, you get positive messages and occasionally "your throat feels hot!" (similar to hot sauce)
- If anyone else you cough, splutter, and dry heave. You may take small amounts of toxin damage, but nothing serious

**15u to 30u**
- If grey, you start getting negative messages and experiencing slight toxin damage comparable to other species in the above stage
- If anyone else you begin jittering. Toxin damage becomes more likely and will be more serious, chance of vomiting, very low chance of slight liver damage

**30u and Beyond**
- If grey, you start getting VERY negative messages and will start jittering. You may also vomit, take higher toxin damage, and minor liver damage. Thankfully it doesn't get any worse than this
- At this point anyone else will start having a VERY bad time. Jittering continues, chance of vomiting is much higher, toxin damage is beyond what dylovene alone can keep at bay, and your liver will start taking a serious beating. You will also audibly scream occasionally due to the intense burning sensation in the abdomen.

What if you're a poor everyman and some asshole grey just rounded the corner and shot you with a giant syringe of Zam's Spicy Sauce? Not to worry, as everyone knows there's one cure for any spice. It's... milk. Just perfectly ordinary everyday Space Milk will rapidly purge Zam's Spicy Sauce from the body.

### **Zam Condiment Chemistry** ###
You're going to need Zam Spices to get anywhere, and currently they can only be obtained through Zamitos and exotic condiment crates. So gather some up before you try making your own sauce!
- **Blue Goo:** 3 parts Zam Spices + 2 parts Locutogen = 5 parts Blue Goo
- **Mild Sauce:** 3 parts Zam Spices + 2 parts Sulphuric Acid = 5 parts Zam Mild Sauce
- **Spicy Sauce:** 3 parts Zam Mild Sauce + 2 parts Polytrinic Acid + 5u Unstable Mutagen (Catalyst) = 3 parts Zam Spicy Sauce

## Closing Thoughts ##
As always I'm open to feedback and criticism. I tested Zam's Spicy Sauce a lot before it was in a place where I figured it was reasonably balanced, but I'm open to suggestions if someone thinks it's too strong or too weak in some regard. Or just badly coded, which it might be!

I'll try to accommodate any reasonable requests, I hope some players will enjoy the new reagents and such. And... that's all.

### **Noted Additional Changes** ###

- The two free packages of Zam biscuits in the Zam Snax vending machine contraband have been replaced with six packets of Zam's Spicy Sauce (10 credits each)
- The warnings about the Zam meals not being for human friends has been removed from the merch computer. That's actually a mistake and I'll put them back if anyone wants me to.
- Zam Spicy Sauce is animated because it's an EVIL substance. I'm not sure how to get a proper preview going though, so just take my word for it.
- Not sure if I mentioned it above, but all the Zam condiments have a chance of showing up in exotic condiment crates. Zam's Spicy Sauce has the lowest chance, naturally. (Zam Spices = 10, Zam Mild = 5, Zam Spicy = 3)

[content] [sprites]  [balance]

:cl:
 * rscadd: Added unique Zam food condiments. They come with Zam meals and sometimes appear in exotic condiment crates.
 * rscadd: Zam meals are pre-cooked and no longer need to be microwaved.
 * rscadd: Zam meals now include a bag of Zamitos for additional snacking
 * tweak: Updates Zam Spider Slider, Zam Moon Cheese, and Zam packaged meal sprites.
 * tweak: Zam cargo merch meals are slightly more expensive.

### CODE REVIEW

**Comment by jwhitak** [comment]
Imagine ordering the exotic garnishes crate and getting nothing but Zam Spices... Chef's gonna have a fun time with that! Good update.

**Comment by Eneocho** [comment]
Supermatter seas are not canon, spessmen know not of such events until a cascade (which also isn't canon) happens. How would a spessman know about supermatter seas if their main requirement is a universe destroying event?
Consider making Zam Spicy a 5 weight on the condiment crates, it ain't that dangerous (compared to the one other 1 weight condiment).
The Zam Spicy recipe should also give you 5u, for consistency with Zam Mild and Zam Spices.
Consider giving Zam Spices and it's derivatives a minor healing effect (Zam chemistry helps with burns?).
Since it's treated by milk and gives you heat effects, consider making Zam Spice a recipe that requires capsaicin (1:1:1 Capsaicin-Sacid-Nutriment? or something similar.)
There's probably a few too many if(prob(5))s on the zam spicy code.
Zam Spices and Zam Spicy are a bit too similar in the code name and might be a bit confusing for adminbus and stuff.
Perhaps Polytrinic Palooza should have some Zam Spicy inside, it already is a deathtrap, might as well make it fancy.

**Comment by Optimism333** [comment]
> Supermatter seas are not canon, spessmen know not of such events until a cascade (which also isn't canon) happens. How would a spessman know about supermatter seas if their main requirement is a universe destroying event? Consider making Zam Spicy a 5 weight on the condiment crates, it ain't that dangerous (compared to the one other 1 weight condiment). Consider making the Zam Spicy recipe also give you 5u, for consistency with Zam Mild and Zam Spices. Consider giving Zam Spices and it's derivatives a minor healing effect (Zam chemistry helps with burns?). Since it's treated by milk and gives you heat effects, consider making Zam Spice a recipe that requires capsaicin (1:1:1 Capsaicin-Sacid-Nutriment? or something similar.) There's probably a few too many if(prob(5))s on the zam spicy code. Zam Spices and Zam Spicy are a bit too similar in the code name and might be a bit confusing for adminbus and stuff. Perhaps Polytrinic Palooza should have some Zam Spicy inside, it already is a deathtrap, might as well make it fancy.

**Consider making Zam Spicy a 5 weight on the condiment crates, it ain't that dangerous (compared to the one other 1 weight condiment).**

I'll bump up the weight to maybe 3.

**Consider making the Zam Spicy recipe also give you 5u, for consistency with Zam Mild and Zam Spices.**

It gives less because it's more concentrated, so to speak. It's also the only one of the three that's harmful, so there's a reason it isn't consistent.

**Consider giving Zam Spices and it's derivatives a minor healing effect (Zam chemistry helps with burns?)**

Sorry, I'm not doing this. It's a food item, not medicine.

**Since it's treated by milk and gives you heat effects, consider making Zam Spice a recipe that requires capsaicin (1:1:1 Capsaicin-Sacid-Nutriment? or something similar.)**

While it does have flavor text effects similar to hot sauce, it's not chemically the same. It's a toxin that causes a sensation of heat in the tissue it touches, rather than actually raising body temperature (And truth be told, I couldn't figure out how to code the temperature increasing effects of capsaicin into it anyways). I also want to stay away from human-based produce to keep it with a weird chemical formula that's unique.

**There's probably a few too many if(prob(5))s on the zam spicy code.**

Yeah, that's fair. I'll try and clean it up a little.

**Zam Spices and Zam Spicy are a bit too similar in the code name and might be a bit confusing for adminbus and stuff**

I'll make their code names a bit more distinct.

**Perhaps Polytrinic Palooza should have some Zam Spicy inside, it already is a deathtrap, might as well make it fancy.**

I'll think about it. I have another drink I have to change the formula for in a pr soon.

**Comment by Eneocho** [comment]
I had meant a healing chem for greys, similar to gravy for vox or milk for skeleman (we don't have that many grayy players anyway, so it wouldn't be powergamed).

And for the capsaicin part, capsaicin uses a data variable as a timer and checks said variable for specific times. It then increases the heating rate at said times (1-15, 15-25 and 25-inf). Condensed capsaicin does the same (1-15 and 15-30, interestingly, it seems condensed capsaicin doesn't heat you up after you reach the 31 timepoint, you just vomit).
If you want just the barebones heating, no fancy increasing heating rate change, you can use: 
`M.bodytemperature += [YOUR VALUE HERE] * TEMPERATURE_DAMAGE_COEFFICIENT`
For reference, capsaicin has 0.6-0.9-1.2, condensed capsaicin has 0.9-1.1, novaflour has 3 and hell ramen has 10. 
You probably want it hotter than capsaicin for the ZamSpicy, equal to capsaicin for ZamMild and weaker than capsaicin for Zam Spice.
If you want specific effects for races, you can use:
`if(is[YOUR RACE CHOICE HERE](M))`
   `M.bodytemperature += rand([YOUR MINIMUM RANDOM VALUE HERE],[YOUR MAXIMUM RANDOM VALUE HERE])`
Or you can add a proc to that specific race's chemical and reagent handle, like how dionae stop regenerating when on hyperzine, that's on the species handle, not on the hyperzine code. Though I'm sure someone would complain about how it isn't the way to do it.

**Comment by Optimism333** [comment]
> I had meant a healing chem for greys, similar to gravy for vox or milk for skeleman (we don't have that many grayy players anyway, so it wouldn't be powergamed).
> 
> And for the capsaicin part, capsaicin uses a data variable as a timer and checks said variable for specific times. It then increases the heating rate at said times (1-15, 15-25 and 25-inf). Condensed capsaicin does the same (1-15 and 15-30, interestingly, it seems condensed capsaicin doesn't heat you up after you reach the 31 timepoint, you just vomit). If you want just the barebones heating, no fancy increasing heating rate change, you can use: `M.bodytemperature += [YOUR VALUE HERE] * TEMPERATURE_DAMAGE_COEFFICIENT` For reference, capsaicin has 0.6-0.9-1.2, condensed capsaicin has 0.9-1.1, novaflour has 3 and hell ramen has 10. You probably want it hotter than capsaicin for the ZamSpicy, equal to capsaicin for ZamMild and weaker than capsaicin for Zam Spice. If you want specific effects for races, you can use: `if(is[YOUR RACE CHOICE HERE](M))` `M.bodytemperature += rand([YOUR MINIMUM RANDOM VALUE HERE],[YOUR MAXIMUM RANDOM VALUE HERE])` Or you can add a proc to that specific race's chemical and reagent handle, like how dionae stop regenerating when on hyperzine, that's on the species handle, not on the hyperzine code. Though I'm sure someone would complain about how it isn't the way to do it.

Thanks for the suggestions. I'm going to see if I can add a temperature increasing factor to the Zam's Spicy Sauce while I'm cleaning up the probability code a little.

Previous commit increased the weight of Zam's Spicy Sauce to 3 for the exotic condiment crate, and the ID was changed to ZAMSPICYTOXIN. That should be more distinct.

**Comment by Optimism333** [comment]
Testing found some weird results. I used your  suggestion below:

M.bodytemperature += [YOUR VALUE HERE] * TEMPERATURE_DAMAGE_COEFFICIENT

 When I plugged 2 into the equation, it made the Zam Spicy Sauce WAY too lethal. Then when I dropped it down to 1.2 it didn't do anything at all to body temperature. I settled on about 1.4 for greys and 1.6 for other species. At these values it increases body temperature, but it takes a while to climb up and shouldn't cause any trouble unless you have much more than 15u in the system. 

I'm only going to do the temperature increasing variable for Zam Spicy Sauce for now. I also figured out how to make it give the HUD alert like capsaicin does, so hooray.

**Comment by Optimism333** [comment]
> Supermatter seas are not canon, spessmen know not of such events until a cascade (which also isn't canon) happens. How would a spessman know about supermatter seas if their main requirement is a universe destroying event?

Not entirely true! It can also be seen in one of the away missions, so presumably there's ways it can occur in spessmans without the universe destroying event.

**Comment by Eneocho** [comment]
You said "Perhaps you were surrounded by a supermatter sea and unable to reach a microwave, but wanted to enjoy your last meal?"
This implies the seas are expanding, which doesn't happen on the away missions, thus the phenomenon would still require impossible knowledge, but I concede on the seas being known part.

**Comment by Eneocho** [comment]
With all these Zam food PRs, we desperately need some Zam vendors stationside (even one would do), that'd also encourage more players to try the grayys.

**Comment by Optimism333** [comment]
> With all these Zam food PRs, we desperately need some Zam vendors stationside (even one would do), that'd also encourage more players to try the grayys.

Burnt added one to Island. I spotted it in the pr screenshot.

**Comment by SonixApache** [comment]
this man straight up laying down his own lore through use of fastfood

I hope you know that we already have a small grey-themed vault, perhaps you should throw some of your stuff in it.
[brokeufo.dmm](https://github.com/vgstation-coders/vgstation13/blob/c077fc9ee7966568780ee0d720de11689b5f719e/maps/randomvaults/brokeufo.dmm)

**Comment by Eneocho** [comment]
> 
> 
> > With all these Zam food PRs, we desperately need some Zam vendors stationside (even one would do), that'd also encourage more players to try the grayys.
> 
> Burnt added one to Island. I spotted it in the pr screenshot.

I would recommend not to get to too excited for Island. Chunk-style stations have not worked well here and have been removed/reworked more than once.

**Comment by BomberBro** [comment]
The overuse of the logo felt more realistic to me than the actual images of the food to be honest.

**Comment by Optimism333** [comment]
> The overuse of the logo felt more realistic to me than the actual images of the food to be honest.

I can understand that, I just disagree. From a spriting perspective it started feeling extraordinarily lazy and dull to just paste that logo on everything, as nice as it is (Blithering made it, that's why it's nice). 

It also isn't that interesting to look at as a player in-game in my opinion, at least not if every single product has it. I think this puts it in a good place: it's on the delivery bag you get the food in, it's on the Zam biscuits package, it's on the NotRaisins, and it's on the machine. Everything else has a preview of what the food contents are or a little design like the drinks.

Even so, there's still a small chance to get the Trusty Tea can with the old Zam logo (added at Eneocho's request), and I've retained one of the old Zam meal box sprites with the mascot. It can't be obtained at the moment, but I intend to use it as vault loot and a little throwback to the old design.

**Comment by Eneocho** [comment]
I still think that the chance for the old logo should've been added to all the drinks. Having it only on one drink feels weird and out of place, noy to mention obscure as hell. I'll take my win, even if partial though.

**Comment by Kurfursten** [comment]
Confl

**Comment by Optimism333** [comment]
> Confl

Hopefully should be fixed now.

**Comment by Eneocho** [comment]
Are you gonna make the sauces spicy or is that for another PR?

**Pull request merged**
