### PR TITLE
Makes hydro trays non-dense

### PR DESCRIPTION
**Pull request by gbasood**
Unless someone can think of a reason they SHOULD be dense, because right now it can produce some weird things with Bump() that people are messing with in the effort to make Bump not shit

### CODE REVIEW

**Comment by Exxion** [comment]
I _think_ the point of that was to make it so that it would act like a table when its cover was closed
But why they didn't just make it _actually not dense_ when open is beyond me

**Comment by gbasood** [comment]
@Exxion Nothing about that proc actually made it behave differently when it was closed though

**Comment by Exxion** [comment]
Oh yeah, not sure what I was thinking
...What the fuck were they trying to do?

**Comment by gbasood** [comment]
It's from baycode merged by pomf in 2014
KILL IT

**Comment by 9600bauds** [comment]
KILL IT

**Pull request merged**
