### PR TITLE
Remove hos/cap restriction from roundstart nukies.

### PR DESCRIPTION
**Pull request by gurfan**
This would allow Captain/Head of security players to spawn as ops. With the same lowered chances as the rest of sec.

:cl:
 * tweak: Captain and Head of Security players can now roll roundstart nukeops, with lower chances.

### CODE REVIEW

**Comment by Sooose** [comment]
Wizard: Sure, whatever.
Nukies: Removing some key disk securers seems a little silly and unnecessary if they were happy playing the job anyway.

**Comment by PrimeDSS13** [comment]
the other day I saw a manifest of 1 cap 1 hos and like 3 sec officers turn into just 1 cap and 1 hos because the rest became nukies

why would you want this except with them as well
the fact that the enemies roles that cause nukies to trigger can become nukies is silly on its own, now it's going to be that plus the nuke disk isn't secured

**Comment by Jackreturnswithaveangenace** [comment]
accelerationism is not the way to improve the server, we tried that already

**Comment by gurfan** [comment]
emojis have spoken

**Pull request closed without merging**
