### PR TITLE
Escape Pod Computers

### PR DESCRIPTION
**Pull request by gurfan**
How do escape pods pilot themselves back to central command? There must be some kind of computer controlling it.
After a few hours of investigation, station engineers managed to scrub off the invisible spray hiding the escape pod computers for God knows how long. 

Since the introduction of the autopilot system, these computers have fallen out of date and are mostly inoperable by humans.
They are still vital to the escape pod's functionality, however. Shorting the computer out using an electromagnetic device could produce disastrous results. 

:cl:
 * rscadd: Adds pod control computers to station escape pods. Hacking them with an electromagnetic card causes them to crash into the emergency shuttle mid-transit. They can be repaired with a screwdriver and soldering iron.

### CODE REVIEW

**Comment by gurfan** [comment]
https://user-images.githubusercontent.com/51427771/163040828-9e4c799d-41cb-4c90-92ee-1a39222108c7.mp4

**Comment by NiftyRyanyan** [comment]
Pod babies on suicide watch.

**Comment by Eneocho** [comment]
P O D
O
D

B A B B Y
A
B
B
Y

**Comment by Eneocho** [comment]
Now I'm conflicted. On the one hand pod toddlers deserve the rope, on the other, suicidebombing the shuttle is based.

**Comment by Exxion** [comment]
You don't have to suicide bomb it. Just emag the computer and leave. Go emag another. Collect them all.

How often do you think these would be repaired? It sounds like emagging the pods is just free kills.

**Comment by gurfan** [comment]
> You don't have to suicide bomb it. Just emag the computer and leave. Go emag another. Collect them all.
> 
> How often do you think these would be repaired? It sounds like emagging the pods is just free kills.

Empty pods won't crash into the shuttle.

**Comment by Kurfursten** [comment]
> How often do you think these would be repaired? It sounds like emagging the pods is just free kills

I could think of a way to counterbalance it. What if you can emag the console, but it takes on a distinctive color while emagged (e.g.: red screen) and it can't be emagged while the shuttle is called/docked.

This means that antags can't just go emag pods right before the shuttle arrives to make them crash in as free shuttlebombs, they have to emag them in advance. Meanwhile, engineers have the opportunity to respond to reports of red shuttle computers before the shuttle takes off. If they fail to use the 10 minute shuttle call + 3 minute launch window to respond to a report, that's on them.

**Comment by gurfan** [comment]
> > How often do you think these would be repaired? It sounds like emagging the pods is just free kills
> 
> I could think of a way to counterbalance it. What if you can emag the console, but it takes on a distinctive color while emagged (e.g.: red screen) and it can't be emagged while the shuttle is called/docked.
> 
> This means that antags can't just go emag pods right before the shuttle arrives to make them crash in as free shuttlebombs, they have to emag them in advance. Meanwhile, engineers have the opportunity to respond to reports of red shuttle computers before the shuttle takes off. If they fail to use the 10 minute shuttle call + 3 minute launch window to respond to a report, that's on them.

I like this idea better, I'll do this instead

**Comment by gurfan** [comment]
- Escape Pods will crash if empty again
- Pod Computer refuses to be emagged while the emergency shuttle is on its way
- Computer flashes red when in need of repair.

**Comment by gurfan** [comment]
> * Escape Pods will crash if empty again
> * Pod Computer refuses to be emagged while the emergency shuttle is on its way
> * Computer flashes red when in need of repair.

@Kurfursten 
One issue I see with these changes is that nobody is going to take a pod that's clearly malfunctioning.  I'm not sure what the right way to balance it is. I don't want it to be a brainless and riskless shuttle-bomb but at the same time, surprising people who take an escape pod and don't open the panel to inspect the wires was my goal.

**Comment by pedr69** [comment]
>crash if empty

at least have it crash in if there's SOMETHING inside
a pod full of dead clowns crashing in would be better than 4(yes there's four) empty pods crashing in, gibbing 60% of the shuttle

**Comment by Kurfursten** [comment]
Perhaps the panel always turns to a green "preparing to launch" light when the shuttle is docked with the station -- whether it's emagged or not. If you showed up early and got in the pod before it docked, or you checked routinely for tampering, you would see the light. If you just climb in as a podbaby in the last 3 minutes you get owned. (Still possible to counter by opening the panel to check, just less obvious)

**Comment by Eneocho** [comment]
There should be a centcomm pod babby place in the beach where the pod babies get teleported/land so they can be appropriately mocked.

**Comment by WindowsErrors** [comment]
i remember on beestation the escape pod computers had a non-emag use where if it was code red or code delta you could use the computer to prematurely send the escape pod to lavaland to avoid the impending destruction and there was a little locker on the inside wall of the escape pod that would unlock and it had some eva suits and oxygen tanks and pickaxes and the russian rations from the russian surplus crate and some other survival equipment too that i forgot

**Comment by PrimeDSS13** [comment]
as the number one pod crasher I support this PR

**Comment by Kurfursten** [comment]
Add information about this to the wiki, specifically some engineering related page - so people can diagnose and fix problems with these computers.

It might belong under Hacking since it's wire related? Or Engineer since they'll fix them

**Pull request merged**
