### PR TITLE
Remaps the Dojo to actually be a Dojo

### PR DESCRIPTION
**Pull request by ValkyrieSkies**
The Spider Clan has stopped being cheapskates and pretending that acoustic panelling is oriental and has instead forked out the cash to actually decorate their dojo with authentic tatami flooring and shoji walls.

newDojo

A few people have requested that the tatami mats be added to the tile painter, but I'll be doing that in a seperate PR in future because my train's almost arrived at the station.

[sprites]

## Changelog

:cl:
 * imageadd: Added tatami mat to floor icons and shoji walls to wall icons
 * tweak: Made the Ninja Dojo not hideous

### CODE REVIEW

**Comment by Eneocho** [comment]
I had a feverdream hallucination that I added back the crazed weeaboo as a 1/10 chance to replace the ninja. Is this a sign?

**Comment by adacovsk** [comment]
All that effort for a ninja that briefly sees his dojo before going into the station, getting tased and dying to a clown within 3 minutes...

**Comment by agentofzog2** [comment]
Needs wall scrolls.
Ideally something with motivational lines like:
"If you cannot slay your foe with one hundred shuriken, throw one thousand shuriken!"
"Compose your death haiku before you are being beaten to death"
and
"YEEART!"

**Comment by Eneocho** [comment]
Add a training turret that lets you "train" the holo projector dodging.

**Comment by Blithering** [comment]
Looks like a nice redesign, maybe group up the training doors on one though, its a bit weird to have one on each side of the table, even if it is symmetrical.

**Comment by DrSnips** [comment]
Are these edits of my old tatami mat sprites or your own? Nice stuff no matter what.

**Comment by Eneocho** [comment]
If we assume the tatami tiles are accurate, this sends the whole proportions we assumed out the window. We assumed each tile was 1m x 1m, but this implies each tile is actually somewhere around 2.73m x 2.73m. So the spessmen are not midgets, they're in fact giants.

**Comment by ValkyrieSkies** [comment]
> Are these edits of my old tatami mat sprites or your own? Nice stuff no matter what.

Made them from scratch, my man.





> If we assume the tatami tiles are accurate, this sends the whole proportions we assumed out the window. We assumed each tile was 1m x 1m, but this implies each tile is actually somewhere around 2.73m x 2.73m. So the spessmen are not midgets, they're in fact giants.

I'm considering adding more types of tatami pattern in the tile painter PR, so enjoy the scaling chaos I'll surely introduce with that.



> All that effort for a ninja that briefly sees his dojo before going into the station, getting tased and dying to a clown within 3 minutes...

Ninja has potential to be a lot more, and one day I may very well see to fixing that myself.

**Comment by Blithering** [comment]
> If we assume the tatami tiles are accurate, this sends the whole proportions we assumed out the window. We assumed each tile was 1m x 1m, but this implies each tile is actually somewhere around 2.73m x 2.73m. So the spessmen are not midgets, they're in fact giants.

Tatami mats shrink in the presence of bluespace.

**Comment by ShiftyRail** [comment]
Merging this right now but if you want to keep working on that, more than encouraged.

**Pull request merged**
