### PR TITLE
[Bugfix] Fixing twitch/tourettes pixel offset not resetting

### PR DESCRIPTION
**Pull request by DeityLink**
blah

### CODE REVIEW

**Comment by clusterfack** [comment]
This wont work, it'll break if someone buckles themselves to something

**Comment by DeityLink** [comment]
Why would it?

**Comment by DeityLink** [comment]
@clusterfack tested while buckled on a bed, on a roller bed, and on a janicart. No issue.

**Comment by clusterfack** [comment]
It's not WHILE being buckled that matters. It's buckling while its occurring.

**Comment by DeityLink** [comment]
you mean buckling at the exact frame where it occurs? Sounds pretty unlikely for two reasons:

* animate() happens instantaneously ("This change will take place immediately, but will be displayed to users as a gradual change over a period of time. ")
* if the user is buckling to something that change its offset, it'll usually reset its offset to its proper location (riding a janicart was used as a workaround for that bug until now)

**Comment by clusterfack** [comment]
Yes the first animate happens instantly, but the second one waits until the first one completes.

So imagine the following scenario
-I have this status effect
-It sets my old pixel to some value
-It animates to the new value
-During this first animation I buckle to something
-It animates back to the old pixel value I had before I buckled

**Comment by DeityLink** [comment]
point taken, how about that?

**Comment by clusterfack** [comment]
Yeah looks like it should work

**Comment by PJB3005** [comment]
Add fixes X in there.

**Comment by Probe1** [comment]
:+1:

**Pull request merged**
