### PR TITLE
Adds Dorf Station to the map vote on the release anniversary of DF

### LINKED ISSUE #29505: Feature Request: Players Can Vote for Dorf in August
I picked August because it doesn't have other holidays going on, Snaxi is disabled in that month, Dwarf Fortress was released in August, and as someone else said "it's hot like a forge".

Discuss.

### PR DESCRIPTION
**Pull request by ghost**
Closes #29505 
Not sure if this is the right file path name, someone correct it if so.
Compilable version of map provided by @DeityLink 
:cl:
 * rscadd: Dorf Station can now be voted for on August 8th, the anniversary of the release of Dwarf Fortress.

### CODE REVIEW

**Comment by gurfan** [comment]
does dorf station even compile

**Comment by Eneocho** [comment]
The Buildtism and miningtism gang will flourish.

**Comment by DeityLink** [comment]
> 
> 
> does dorf station even compile

last I checked it didn't because of a wrong type path on some centcomm armor.

**Comment by DeityLink** [comment]
I'll get something to eat then I might fix that

**Review by ShiftyRail — CHANGES_REQUESTED** [review]
You __must__ add it to CI if you're going to do that.

**Comment by ghost** [comment]
> You **must** add it to CI if you're going to do that.

Done

**Review by ShiftyRail — APPROVED** [review]

**Pull request merged**
