### PR TITLE
Adds a "wake up occupant" option to Sleepers

### PR DESCRIPTION
**Pull request by 9600bauds**
- Added a 'Wake-Up Cycle' option to Sleepers, which will try to wake up the occupant. This is intended to work as an alternative to the Mancrowave. Alt-clicking a Sleeper while an occupant is inside will automatically start this cycle.
- Fixed inaccurate sleeping time remaining (the Sleeper tells you for how long will this guy remain asleep if undisturbed)
- \improper for Sleepers and Sleeper consoles
- Optimizes Sleeper interface with list2text

Addresses part of #8047

### CODE REVIEW

**Comment by CptWad** [comment]
misleading title, this actually improves the sleeper in general too

**Comment by 9600bauds** [comment]
Improves as in fixing the timer thing?

**Comment by CptWad** [comment]
yes thank you :+1: :+1: :+1:

**Comment by Shadowmech88** [comment]
> \improper for Sleepers and Sleeper consoles

Why are those capitalized anyway? Is it a brand name?

**Pull request merged**
