### PR TITLE
Fixes the areas in bagel's IAA office

### PR DESCRIPTION
**Pull request by DelaminatingShard**
Maintenance was leaking into the IAA's office on bagel
Before:
areaslol
After:
areaslol2

First noticed when the sound system on the south wall would only play when I got near it.

:cl:
 * tweak: Fixed the areas in bagel's IAA office

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
You need to run the map cleaner before committing, see https://github.com/vgstation-coders/vgstation13/wiki/Mapping-and-you.

**Comment by DelaminatingShard** [comment]
haha whoops
lemme see I can fix this

**Comment by DelaminatingShard** [comment]
dammit
tried to fix it, still not working. Should I just make a new pr with a new branch?

**Comment by PJB3005** [comment]
What commands did you use to attempt to fix it, exactly? You need to prepare the map cleaner with an older version of the file, THEN run clean map with the modified map.

**Comment by DelaminatingShard** [comment]
I downloaded bagel from the github here, replaced the modified version with the downloaded one in the map files, ran 1prepare_map, then replaced the downloaded map with the modified one in the map files, then ran 2clean_map.

**Comment by PJB3005** [comment]
Hrm that should've worked.

Though on the "make a new PR" thing: making a new PR is *never* the solution.

**Comment by DelaminatingShard** [comment]
itworked
made a new branch and started over. this time not forgetting to use the map tools. Seems like it worked.

**Comment by PJB3005** [comment]
Oh you know what it was?

You didn't change the old commit, so it had to fix the old commit, thus resulting in that bunch of changes the second time.

If you pushed that first attempt I'm pretty sure it'd have fixed the PR.

**Comment by DelaminatingShard** [comment]
Oh shoot, okay.
Lemme see if I can push the first branch now.

**Comment by DelaminatingShard** [comment]
Well, shoot.
Now I can't even get bagel to show up in the change list.

**Comment by SonixApache** [comment]
pull, reset and merge bleeding-edge until you're synced to bleeding-edge again
run maptools prepmap
make changes
run maptools cleanmap
stage commit and push bagelstation

**Comment by DelaminatingShard** [comment]
uh, did that work?

**Comment by PJB3005** [comment]
Definitely did!

**Comment by DelaminatingShard** [comment]
Hooray!

**Review by PJB3005 — APPROVED** [review]

**Comment by Shadowmech88** [comment]
Is it normal for a map change to remove a line but not replace it with another line?
It seems as though the total number of lines in the map file has decreased by one.

**Comment by PJB3005** [comment]
Yes. That's how the map format works. At the top is a list of "tile types", which contain the data for a tile. At the bottom is the actual tile map using these types, so he simply removed a tile type and replaced the tile using it with one that was the same as another tile.

**Pull request merged**
