### PR TITLE
Makes wizard den a spawned dungeon of 5 random types

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[general][role]

## What this does
instead of having them individually in the map .dmm files over and over, this instead takes all the unique kind of wizard dens and makes them a dungeon loaded in when the role gets created, based on the 5 current unique types in the game
removes the check for spawnpoints in available() or ready() because other dungeon spawning roles don't need it

## Why it's good
less map bloat, one less thing to add in any new map

## Changelog
:cl:
 * rscadd: Wizard dens no longer have their appearance tied to certain station models.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I would be worried about a lagspike giving away the creation of a den, but then again it works fine for dojos already

**Comment by Eneocho** [comment]
> I would be worried about a lagspike giving away the creation of a den, but then again it works fine for dojos already

Lagspikes sources aren't that obvious. For all you know the miner accidentally hit a massive gibtonite vein and the explosion calculations took a while to complete.

**Comment by adacovsk** [comment]
Since there are three wizard modes does this spawn three separate dungeons if dynamic triggers all modes? I think removing landmarks would actually help with roundstart times since there should be less landmarks to search through. This should be done for nuke ops too!

**Review by Kurfursten — CHANGES_REQUESTED** [review]
I notice you did not spawn any wizard dens for Civil War of Casters

**Comment by SECBATON-GRIFFON** [comment]
> Since there are three wizard modes does this spawn three separate dungeons if dynamic triggers all modes?

nah, the "unique" flag is set on the dungeon

**Comment by SECBATON-GRIFFON** [comment]
> I notice you did not spawn any wizard dens for Civil War of Casters

the wizard den is spawned for any faction of type /datum/faction/wizard, and both factions in civil wars are a subtype, so it still works (confirmed with testing too) @Kurfursten

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
