### PR TITLE
1 year meme rule

### PR DESCRIPTION
**Pull request by jknpj**
I'm very tired of all these japanese isekai/academy/demon lord crap I'm always seeing when I'm finding a good manga to read. I've turned to korean manhwa and chinese cultivation manhua. Sure chinese cultivation manhua's facing the same problem with Japan an isekai but manhua has a fresh feeling to it and is very very less cringe same goes for korean manhwa

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Open it you pussy

**Comment by drawsstuff** [comment]
reopen this you pussy

**Comment by Kromkar** [comment]
Open this

**Comment by jknpj** [comment]
fiine

**Comment by Kromkar** [comment]
@DeityLink obey the emojicracy

**Comment by DeityLink** [comment]
@jknpj fuuuuuuuuuuuuuuuck

**Pull request merged**
