### PR TITLE
unathi soghun gear update

### PR DESCRIPTION
**Pull request by SonixApache**
blithering gave me icons for this a while ago and i forgot to implement them again like always
thanks blithering for the cool icons

soghun set now doesn't have missing pixels, and now comes with a helmet

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
bro just remove the unused aliens already

**Comment by DrSnips** [comment]
I like having a few extra races around. It makes the frankensteins more interesting.

**Comment by ghost** [comment]
> 
> 
> bro just remove the unused aliens already

don't say the R word in this house

also whitelist unathi for janitor

**Comment by Probe1** [comment]
Isn't that how lizards got introduced to TG?

**Pull request merged**
