### PR TITLE
Big Xenoarchaeology update

### PR DESCRIPTION
**Pull request by DeityLink**
Shaving yet another chunk off the upcoming Centcomm Orders revamp for the sake of atomicity, which allowed me to even expand a bit on it, and give Xenoarch some well deserved love.

image
image
image
xenoarch scanner
90932112-49f1c080-e3fe-11ea-817f-747e355dd492containeremag
imagedestroy beacon

:cl:
* experiment: Big Xenoarchaeology update!
* imageadd: The depth scanner, digsite locators, core sampler, rock sliver, as well as the solution trays all have new sprites.
* tweak: The core sampler now works without the need for sample bags, but takes one second to extract a sample. It's got sounds now too.
* rscadd: You can use a pen on a rock sliver to label it.
* rscadd: Edited the description of rock slivers, some of the xenoarch-related reagents, as well as the xenoarch sample analysis machines to help players understand each of their purposes.
* tweak: Removed the beacon, and locater device from Excavation Tools closets due to their utmost uselessness in regard to the job. The locater (renamed locator) device however can now be acquired from the Protolathe at Bluespace Tech Level 2. It still looks just like the disk pinpointer though.
* tweak: The xenoarchaeological digsite locator has been buffed to always show digsite material colors (requires Anomaly Tech Level 3)
* tweak: The advanced xenoarchaeological digsite locator has been buffed to also highlight turfs with buried large artifacts (requires Anomaly Tech Level 4)
* rscadd: The Alden-Saraspova Counter is FINALLY available from RnD, barely 4 years after I added the fucking tech tree, and gives you the distance to the closest Large Artifact. You can also fit them in your excavation belt (requires Anomaly Tech Level 5)
* rscadd: Added Hard Disk Drives. As useless as Corrupted Data Disks, and both may now be found in maint loot spawners
* rscadd: Added Encrypted HDD (Anomaly Tech 5), now spawned by Anomaly Analysers when a large artifact gets analyzed for the first time. Replaces that anomaly tech data that used to be in the Anomaly Report. Deconstructing one of those is enough to get the advanced xenoarchaeological digsite locator which will highlight buried large artifacts.
* tweak: The distance to the nearest artifact given by the Fourier transform spectroscope is a lot more reliable now that it counts distance in a circle rather than a square.
* rscadd: You can slap Artifact Analysis reports onto Anomaly Containers, allowing people who examine the container to read the report.
* tweak: Anomaly Containers are now access restricted to science. You can break them open still using an emag, guns, or explosions.
* imageadd: Anomaly Containers have a slightly different appearance when containing a large artifact, or when broken.
* tweak: Placing a Large Artifact into an anomaly container automatically toggles off its effects.
* rscadd: Large Artifacts that have both been analyzed and had their primary effect activated at least once now add points to the crew score (wow, scientists can finally contribute to the crew score lol)
* rscadd: You once again have a very small chance of finding a Syndicate Beacon instead of a Large Artifact in Xenoarch. You can use it to become a traitor, but the beacon will explode after a short delay if you were already part of another faction, or antag banned.
* rscadd: Unlike the old Syndicate Beacon, it can be re-used, but subsequent traitorifications will require admin approval, so you'll be able to write a cover letter to the Syndicate for why they should hire you. If you bother admins too much, they will detonate the beacon.
* imageadd: The Syndicate Beacon now has its own sprite that looks a bit like a laptop, separating it for good from the wish granter.
* rscadd: Since I was confused at first between the Syndicate Beacon and the Singularity Beacon, I judged a good idea to have a regular non-syndicate Singularity Beacon spawn as well among the large finds. It has the same rarity as a large Supermatter Crystal, given its round-ending potential.
* tweak: Upped the rarity of Construct Shells so they're more common than the round ending items.
* bugfix: Fixed a few large artifacts such as the Warping Claws, the Essence Printer and the Communication Crystal being deemed mundane by the Anomaly Analyzer.
* rscadd: A new edition of the Out on the Dig manual is out! Now with information actually relevant to the job of xenoarchaeology!
* rscadd: Added a new item to the RD's locker. The Anomalous Energies Locator, which locates the closest currently activated Artifact or Anomaly Power Utilizer on the current Z Level. Something to help deal with rogue Xenoarchaeologists.
* bugfix: Fixed large artifacts with a touch effect not visibly activating, or being logged.

### CODE REVIEW

**Comment by Kammerjunk** [comment]
why's there no emoji reaction for "I have observed this and even though I physically can't care less, I still want everyone to know I've seen it"

**Comment by gurfan** [comment]
Why does the Alden-Saraspova Counter require anomaly 5 while the advanced locator only requires anomaly 4, if the advanced locator seems do do what the counter does better?

**Comment by boy2mantwicethefam** [comment]
@Kammerjunk it's called 😐 and despite what people think it's not 👀

**Comment by DeityLink** [comment]
@gurfan Are you really saying that an item that only lets you know if there is an artifact in view is better than an artifact that lets you find every single artifact in the Z Level at ludicrous speed?

**Comment by gurfan** [comment]
Now that I think about it, the levels make sense

**Comment by DeityLink** [comment]
I might improve a few more sprites

**Comment by Kammerjunk** [comment]
@boy2mantwicethefam not available as a reaction

**Comment by DeityLink** [comment]
wait holdup, the syndicate beacon and singularity beacon are actually two different things huh. maybe we'll have a chance for both.

**Comment by DeityLink** [comment]
Alright I'm done. This should be good.

**Comment by DeityLink** [comment]
Added a new item to the RD's locker. The Anomalous Energies Locator, which locates the closest currently activated Artifact or Anomaly Power Utilizer on the current Z Level. Something to help deal with rogue Xenoarchaeologists.

Fixed large artifacts with a touch effect not visibly activating, or being logged.

**Pull request merged**
