### PR TITLE
Get Flat Icon DELUXE, featuring Photography being fixed forever

### LINKED ISSUE #21851: Some blob sprites don't appear on photograph
When taking a picture of some blob, nodes and maybe resource nodes don't appear. Factory blobs still appear somehow.

### LINKED ISSUE #24862: Pictures do not accurate represent items on a marble statue
(WEB REPORT BY: bobthomas REMOTE: 206.221.180.138:7777)
# Revision
64c34b49082db854eebad33cddff8f07218e646c

# Description
See title
# Steps to Reproduce
Put items on your marble statue and take a picture
# What you Expected
A furnished marble statue on the picture
# What Actually Happened
A naked marble statue on the picture

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #21851
Fixes #24862
imageimage
imageimage

On top of the new getFlatIconDeluxe(),
this adds a new get_icon_dir_count() proc that tells you if an icon_state has 1 dir, 4 dirs, 8 dirs, or is animated.
as well as a new photography_act() proc that triggers on any atoms that has its picture taken by a camera. Station blueprints now use it to tell the camera that they've been captured.

:cl:
* experiment: Photography Camera had their underlying mechanics thoroughly reworked, which should have fixed most bugs related to them, including some objects being invisible, having the wrong orientation, mannequins not wearing clothes on pictures, etc...
* bugfix: Fixed clothing being offset on cyber mannequins.

### CODE REVIEW

**Comment by Exxion** [comment]
It still looks like a few of the blob connections aren't showing up. Specifically the horizontal and diagonal ones.

**Comment by Eneocho** [comment]
The vampire microwave nerf we weren't expecting.

**Comment by DeityLink** [comment]
> 
> 
> It still looks like a few of the blob connections aren't showing up. Specifically the horizontal and diagonal ones.

I tried a few different things, once it only showed the horizontal ones. It's irregular, I assumed that it came from get_icon_dir_count() at first but even adding an exception for blobs didn't fix. But at least the blobs themselves are all visible now.

**Comment by ghost** [comment]
now make it capture lighting overlays :^)

**Comment by DeityLink** [comment]
> 
> 
> now make it capture lighting overlays :^)

Not when europa lights are around the corner.

**Pull request merged**
