### PR TITLE
muh references

### PR DESCRIPTION
**Pull request by Intigracy**
>A small plaque telling the story of an autistic child.
It details how the child cuts some pieces of the teacher's cheese for his sandwich, and then takes away everyone else's sandwiches when they also use the cut cheese.
The story ends with him crying in a corner after the other children falsely tell his parents that he inappropriately touched a dog.
There is also a picture of some broken forks.

It's in the bar.

### CODE REVIEW

**Comment by Exxion** [comment]
>There is also a picture of some broken forks.

:+1:

**Comment by Intigracy** [comment]
Oops forgot to clean_map

**Comment by 9600bauds** [comment]
Very subtle

**Comment by Intigracy** [comment]
That purple one is a description of our DMCAing friend :^)

**Comment by Chnkr** [comment]
@Intigracy nice meme

**Comment by ghost** [comment]
I don't think this is something we should be commemorating, plus plaques are a meme

**Comment by Shadowmech88** [comment]
This game is like 85% memes.

**Comment by gbasood** [comment]
If the doxxing hadn't happened I'd be 100% for this
But enshrining doxxing in code as humor is not so great

**Comment by Intigracy** [comment]
Maybe instead it should mention kicking a hornets' nest and crying when he's stung.

**Comment by Exxion** [comment]
That would be way worse.

**Pull request closed without merging**
