### PR TITLE
Proto-Kinetic Pump-Shotgun

### PR DESCRIPTION
**Pull request by jwhitak**
# But why though...

Little while back I was looking into the pka/kpa/etc code for some reason and learned something pretty cursed. This was in the code:
```
/*
/obj/item/weapon/gun/energy/kinetic_accelerator/shoot_live_shot()
	overheat = 1
	spawn(20)
		overheat = 0
		recent_reload = 0
	..()
*/
/obj/item/weapon/gun/energy/kinetic_accelerator/attack_self(var/mob/living/user)
	if(overheat || recent_reload)
		return
	power_supply.give(500)
	playsound(src.loc, 'sound/weapons/shotgunpump.ogg', 60, 1)
	recent_reload = 1
	update_icon()
	return
```
For the non-coders looking here, this is non-functioning code that would let you pump your pka like a shotgun to fully recharge it. It was like discovering that your gun had infinite ammo this whole time and somehow nobody knew about it. Well, this code is as old as the gun itself is, and more importantly: it doesn't work. ``recent_reload`` is set to 1 in the base object and is never changed to 0 anywhere except in the commented out code.

But. Cool idea. How do I make it happen?

## What this does
image

This PR implements a new proto-kinetic accelerator, called the proto-kinetic pump-shotgun.  It's intended to be a side-grade to other options such as the spur, plasma cutter, or buying 10+ pkas and keeping them on a belt.

image

While it only holds two shots, it can be pumped in hand to reload those two shots instantly. There is a two second cooldown on the pump action. And while no sound can be heard in space, it ignites with electricity when pumped. While the base pka deals additional damage in low pressure (<50kPa) (15 base +15 low pressure), this shotgun deals further increased damage in low pressure (15 base + 25 low pressure).

image

You can obtain this shotgun via a modkit available in the mining vendor's premium section (aka you need a coin) for 250 credits.

image

Finally, uh... don't let the clown touch it. Just, don't.

### Also:

image

The pka particles have been updated for all guns that use them. They will be the usual green shade while in a pressurized environment. However, when they reach full force by being shot in a vacuum, they'll be a blue-white instead. This is only a visual effect added to the already-existing bonus damage.

Code-side, some projectile variables have been added to replace the hard-coded modifiers that existed beforehand. Additionally, the energy particle icon used (only in pka shots) has been made greyscale, so it may now be easily recolored using byond's standard .color variable.

## Why it's good
Implements a long broken feature left in the oldecode... wait, no, that's a bad thing.

Gives the clown a new target to make funny things with... wait, no, that's bad too!

Uhh, gives an interesting new side grade for miners who are tired of using the spur, plasma cutters, good luck i'm behind 10 pkas, or good luck i'm behind 10 roid monsters... wait, no, miners are not tired of that.

Uhhhhhhhhhhh, errr, ermmm...  it's not I guess!

## How it was tested
image
(the power cannot be contained)

## Changelog

:cl:
 * rscadd: Adds the proto-kinetic pump-shotgun modkit to mining vending machines under their premium selection.
 * tweak: Proto-kinetic accelerator shots now appear blue-white when they're shot at full force in low pressure environments.

### CODE REVIEW

**Comment by RealestEstate** [comment]
the different color projectile in high/low pressure environments is a good touch.

**Comment by SECBATON-GRIFFON** [comment]
would like if these could be applied to plasma cutters too

**Comment by jwhitak** [comment]
The plasma cutter fires a subtype of this projectile, so yes, it's inherited this color changing property.

**Comment by SECBATON-GRIFFON** [comment]
> The plasma cutter fires a subtype of this projectile, so yes, it's inherited this color changing property.

i meant the modkit, sorry if not clear

**Comment by jwhitak** [comment]
Not a fan for several reasons. The goal is to give additional side options for an end game miner, not have a more powerful combined tool. 

Plasma cutters already deal (+15) bonus damage to roid mobs and xenos, function as diamond drills, can cut though rwalls, have increased melee stats (sharpness and hot tip), and hold 15 shots with effectively infinite ammo for an ammo-based gun (no magazine management, only throw maximum stack in all at once, instant load times). They even have something most weapons in this game lack: a safety.

All this and they don't even have a unique sprite! They're just reusing the plasma torch's. (edit: or it would be better to say the plasma torch is reusing the plasma cutter's sprite? They certainly could use a tweak)

This upgrade just lets you reload the standard kpa in hands, plus a low pressure damage buff. But these are powerful upgrades. I consider it basically comparable to the above load out due to the relative ease of access (250 credits, coin, in a vending machine) and the raw strength of an in hands use reload. This doesn't need to be given to an already stacked tool.

**Comment by ErrorsWindows** [comment]
^ maybe you should just repump your weird miner gun


https://github.com/user-attachments/assets/805d8360-01a4-4329-989b-759ad9564103

**Review by west3436 — APPROVED** [review]

**Pull request merged**
