### PR TITLE
Packedstation kitchen/bar rework

### PR DESCRIPTION
**Pull request by Probe1**
**(Packed) Reworks** packed kitchen to have more space, bartenders area to have more space.  Moves MoMMI nest next to CE office.  Moves maint behind the kitchen downward to atmos.

image

image

🆑 

* tweak: (Packed) Reworks packed kitchen to have more space, bartenders area to have more space.  Moves MoMMI nest next to CE office.  Moves maint behind the kitchen downward to atmos.  Botany has been expanded by one tile and some things have been shifted around.

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
While you are touching the mommi nest, could you move the recharger around? The protolathe can't be reached without moving it or standing on top of it every time.

**Comment by groosbstrd** [comment]
capture
Since that maint area is two tiles wide (dunno if that is cause of your change or if it's all ways been that way) could botany be made slightly larger like in pic?

**Comment by Probe1** [comment]
OP updated!  
Tables in the kitchen. Bartenders shit in the bar. Tables shifted in MoMMI nest. Botany expanded to take use of maint.

**Comment by groosbstrd** [comment]
Sweet

**Comment by ghost** [comment]
Boot it up, spawn carp until one spawns by the CE office and see how it plays out with the usual Poly murder scene.

**Comment by Probe1** [comment]
I mean it'll be fine it's just a carp.

**Pull request merged**
