### PR TITLE
Fix being able to eat implanted implants

### LINKED ISSUE #5667: The eat superpower allows you to eat implants
Using the eat superpower while loyalty implanted lets you eat your loyalty implant. http://puu.sh/jNw3R/09ccf77420.png

### PR DESCRIPTION
**Pull request by ghost**
Since it allows you to eat absolutely anything "in view or range", this includes anything in your body. Which right now only contains implants. So that fixes that

Fixes #5667

### CODE REVIEW

**Comment by clusterfack** [comment]
Compile failed

**Comment by dylanstrategie** [comment]
Negative, it's good, open the details

**Comment by clusterfack** [comment]
Ah it errored out

**Comment by clusterfack** [comment]
Use oview() or orange() with the mob as the center, the center and its contents are excluded from that proc

**Comment by dylanstrategie** [comment]
The problem is that it is intended for the mob to eat items on its turf, aka its inventory

**Comment by Intigracy** [comment]
Can you eat organs with this?

**Comment by dylanstrategie** [comment]
Only objects

The only thing this changes is that you can no longer eat implanted implants, which are simply treated as objects inside the mob, like everything in their inventory

**Comment by Intigracy** [comment]
So then you can still eat items implanted into the chest cavity.

**Comment by dylanstrategie** [comment]
Possibly, but then that's the Eat genetic power being absolutely shit

**Pull request merged**
