### PR TITLE
REMOVE GOONCHAT

### PR DESCRIPTION
**Pull request by DamianX**
REMOVE GOONCHAT remove goonchat you are worst chat. you are the chat idiot you are the chat smell. return to goonestation. to our /vg/ cousins you may come our contry. you may live in the zoo….ahahahaha ,goons we will never forgeve you
cetnik rascal FUck but fuck asshole goone stink goons sqhipere shqipare..goon genocide best day of my life. take a bath of dead goon..ahahahahahGOONESTATION WE WILL GET YOU!! do not forget the goonecode leaks .goone we kill the king , goone return to your precious no rp….hahahahaha idiot goon and goons smell so bad..wow i can smell it. REMOVE GOONCHAT FROM THE PREMISES. you will get caught. russia+usa+croatia+slovak=kill goon...you will leak/ tupac alive in /vg/, tupac making album of /vg/ . fast rap tupac /vg/. we are rich and have gold now hahahaha ha because of tupac… you are ppoor stink goon… you live in a hovel hahahaha, you live in a yurt

tupac alive numbr one #1 in /vg/ ….fuck the goon ,..FUCKk ashol goon no good i spit﻿ in the mouth eye of ur serb and contry. 2pac aliv and real strong wizard kill all the goon farm aminal with rap magic now we the vg rule .ape of the zoo presidant georg bush fukc the great satan and lay egg this egg hatch and goon wa;s born. stupid baby form the eggn give bak our clay we will crush u lik a skull of pig. /vg/ greattst countrey

### CODE REVIEW

**Comment by Accipitermaris** [comment]
unga not know "goonchat" but unga put hunting spear on stone wall anyway

**Comment by DamianX** [comment]
After testing, this does not fix the viewport freeze.

**Comment by ghost** [comment]
https://youtu.be/86lczf7Bou8

**Comment by SysadminJeroen** [comment]
Why even open a PR if you don't do the basic testing?

**Comment by ghost** [comment]
@Jeroen52 in order to do that testing, he used the test serbia

**Pull request closed without merging**
