### PR TITLE
Starman 3.0, hopefully the last one

### PR DESCRIPTION
**Pull request by ghost**
Various changes, a lot of them. Too much for me to remember, but here are some big ones:
>Added like 6 more new sound tracks and improved the sound ability.
>Raised CD of starstorm from 180 seconds to 300, added 4 more meteors.
>Using :b now communicates exclusively with other starmen; you can't hear normal binary anymore.
>Added a login message with some basic info on what exactly you are. Removed the last law.
>Added 2 other starmen - deluxe and super. Identical to the starman except in appearance. The starman chain of command dictates that deluxe > super > normal, so this allows for leadership.
>Fixed psi lifeup not healing completely destroyed components. This means I also had to add an optional third variable to mob/living/silicon/robot/heal_overall_damage that can be set to 1 to allow for damaged components to be processed.
>Lots of other minor adjustments.

:cl:
 * rscadd: More starman changes!

### CODE REVIEW

**Comment by ghost** [comment]
And yes, it is meant to be a silicon. It is a robot. Silicon deathstate is usually indicated by its eyes turning off or mmi popping out, but of course we don't have eyes on the menacing STAR MAN.

**Comment by SonixApache** [comment]
\>17 MBs of meme sounds

**Comment by ghost** [comment]
The music pretty good, boss

**Comment by Exxion** [comment]
Everyone has to download all of it every time the server updates
The download is compressed but 17MB is a lot
Almost 10% of our entire sounds folder IIRC

**Comment by ghost** [comment]
It's 2019, nigga.

**Comment by jknpj** [comment]
Say that byond's terrible, terrible download speed.

**Comment by Exxion** [comment]
You want to add 10% to our sound folder for one adminbus-only mob
This is ridiculous

**Comment by FudgePucker** [comment]
Eventually it could be a mid round antag.

Maybe down grade the normal starman from having a pulse rifle to a laser cannon.

**Comment by SonixApache** [comment]
alternatively, we could delet this

**Comment by ghost** [comment]
Pulse rifle with 4 sec cd is worse than a normal .6 second CD laser rifle in everything except destroying walls.

**Comment by Killette2** [comment]
When playing starman combat feels difficult. dodging anything is clunky as you have to click the spell and then the tile (unless you have a dedicated hotkey, which you still must press). Being a an occasionally teleporting duck makes you an easy target to anyone who's not starving or half dead. I'm not sure how well your health and psi up mitigate this issue, as psi up was not functioning when I played but this issue should be considered and maybe playtested by mins occasionally in the thunderdome.

**Comment by ghost** [comment]
Yeah, which is why it has such strong abilities. You're a sitting duck. To be fair I think you were retarded if it was that deff round, but you still do have a point.

**Comment by Kurfursten** [comment]
2 songs was enough

**Comment by Kurfursten** [comment]
Seriously, let's not bloat up our downloads with new songs for this. Take out the music. You already have two whole songs for a special adminbus only monster (admins could already just play music for)

**Pull request closed without merging**
