### PR TITLE
Sorts R&D designs by name

### PR DESCRIPTION
**Pull request by ghost**
[tweak][qol]

## What this does
Makes the names of designs as displayed on R&D consoles be sorted by name under each category every time they get refreshed when enabled as a setting in the R&D console settings. (such as adding levels and deconstructing things)

## Why it's good
More consistency with the order they're displayed in, more muscle memory to it.

## Changelog
:cl:
 * tweak: R&D designs now show up in alphabetical order under their categories, when toggled on in the settings menu. Is off by default.

### CODE REVIEW

**Comment by pedr69** [comment]
gonna be a nope from me boss
as it is, you can see what new shit got unlocked because it's at the bottom of the category now
sorting by name would just be a clusterfuck

**Comment by TurboGay** [comment]
Would it be possible to have this as an optional toggle?

**Comment by Eneocho** [comment]
Toggle and we have a deal.

**Comment by jwhitak** [comment]
My problem personally is that the stock parts are usually scrambled into strange places in the current sort-list-by-research-order. Alphabetical will partially fix this since I can just go to where their names are in order. Deep down though, I wish stock parts were subgrouped by tier.

**Comment by ghost** [comment]
> Would it be possible to have this as an optional toggle?

Made it into one, off by default.

**Pull request merged**
