### PR TITLE
More Clouds

### PR DESCRIPTION
**Pull request by Kurfursten**
image
**Box of Waste-Os (Now With Supermatter Chunks!)**
This is full of chemical waste, but if you purge it with ethanol (just like cleaning out the TEG) you can get those juicy supermatter chunks inside! It's not enough to turn your shard into a supermatter crystal, but it can boost your output and mean you need less from xenoarch.

image
 **Antimatter Axe Conversion Kit**
What kind of madman fights a fire with an axe? The antimatter axe is the solution to that question. Converts your boring matter axe into an antimatter one. It is full of stars and inhales fires, extinguishing them and cooling rooms, when wielded/unwielded. It deals less damage than a real, material fireaxe, but it can also fit into incredibly small spaces.

image

**Master Toolbox**
This toolbox just looks insanely cool, I've wanted to use it for a while. And what do you hate most about toolboxes? The trouble of dropping them: this one has a safety grip you can engage inhand so you won't ever drop it. Great for moving a bunch of metal or glass to a build site. It even quick-gathers!

:cl:
* rscadd: The Cloud IX crate now has three new items: an antimatter axe for fighting fires, Waste-Os Now With Supermatter Chunks!, and a master toolbox for moving a lot of materials and proving that you are the boss.

### CODE REVIEW

**Comment by DrSnips** [comment]
While I can understand why you have put them in the trader.dm file I'm not particularly in love with the idea of children just being all over the place. Personally, I would rather see comments in trader.dm pointing to where you might find the items or wherever the parents are.
This is just my autism posting so make of this what you will.

**Comment by Eneocho** [comment]
Please tell me you can eat the Waste-Os for some dank power and massive toxdamage or something.

**Comment by Eneocho** [comment]
Does the axe mean I can cuck a permanent TEG by placing a firesuit monkeyman with the axe inside? Also, the axe should do more damage than a normal one (antimatter-matter anihilation and all that), but be slower for balance.

**Comment by Kurfursten** [comment]
It literally contains chemical waste which sadly doesn't actually have any effect currently, as far as I know. I guess I could add terrible penalties for drinking it and allow you to get it chunks out by drinking instead of engine degreaser. I'm kind of picturing a person tipping the box up to drink the waste and having supermatter splinters FALL ON THEIR FACE though.

The axe activates only when you wield/unwield it. Wield: extinguish fires in the area and breathes in some gas. Hold: cools down to T20C. Unwield: Releases gas back into the air. The reason the axe does less damage was because I was toying with the idea that you could dismiss it and resummon it, like that cult blood dagger. Since it's not material, and whatnot. This is fun because axes are cumbersome.

**Comment by Eneocho** [comment]
> 
> It literally contains chemical waste which sadly doesn't actually have any effect currently, as far as I know. I guess I could add terrible penalties for drinking it and allow you to get it chunks out by drinking instead of engine degreaser. I'm kind of picturing a person tipping the box up to drink the waste and having supermatter splinters FALL ON THEIR FACE though.

My idea was that since it's a "cereal" with supermatter flakes, you could eat the cereal to get some powers (like the shock healing of slimes/golden glubbs, or some massive rad resistance due to something something you absorb the power of the SM), at the cost of being terribly, possibly lethally poisoned, liver damaged or something.

It'd be a way to get cool powers and an alternative use to the cereal box (Since you don't always get shard engines, so you could use the waste-Os as a power source instead of a _power_ source), but it couldn't be powergamed alone as a trader, since most of the times traders play alone and eating the liver hurting cereal would be deadly.

> 
> The axe activates only when you wield/unwield it. Wield: extinguish fires in the area and breathes in some gas. Hold: cools down to T20C. Unwield: Releases gas back into the air. The reason the axe does less damage was because I was toying with the idea that you could dismiss it and resummon it, like that cult blood dagger. Since it's not material, and whatnot. This is fun because axes are cumbersome.

Makes sense. It could be a telescopic axe, you hold it as a pocket sized metal stick when folded but it expands to a fully sized axe when activated. The less damage can be then handwaved as "most of the power produced by the anihiliation it causes going to the axe's antimatter containment"

**Comment by Kurfursten** [comment]
I want to keep the chemical waste component on the cereal because it highlights the other engine I haven't given any love, the TEG. It's flavored around being cleaned out the same way a TEG's circulators are.

**Comment by Eneocho** [comment]
> 
> 
> I want to keep the chemical waste component on the cereal because it highlights the other engine I haven't given any love, the TEG. It's flavored around being cleaned out the same way a TEG's circulators are.

You can't make it have both the chemwaste and that effect system I described? Maybe 1u of a special chem (like the EMP thingy on potent ham, which really should be revamped, since even a 20x20 EMP is stronger, unless it has another effect I am not aware of) that gives you that power if you drink it, but you can't separate it, you either drink the chem alongside the chemwaste or you dissolve both with the ethanol.

**Comment by Eneocho** [comment]
Also, how would you overhaul the TEG? I'd make them have a range of pipe entrances (from 1 to 5), so you can feed up 5 lines with hot/cold plasma simultaneously since I've never, regardless of extra piping, extra plasma, anything, managed to reach max flow per circulator.
What else could there be? You can't really change the TEGs without making a lot of stuff from scratch or changing things that won't necessarily get accepted (like changing the volume/heat transfer rate for heat pipes).

**Comment by Kurfursten** [comment]
That sounds like a good subject for a discussion Issue where people could pitch ideas in one place. I do have some ideas but I don't want to get too distracted.

**Comment by Blithering** [comment]
We have a supermatter shade mob, could have turning into one be the penalty for breakfast of champions.

**Comment by strawberrytan** [comment]
I don't want meme cereal that gives you meme powers but that's not in the scope of this PR anyway

**Comment by DrSnips** [comment]
> We have a supermatter shade mob, could have turning into one be the penalty for breakfast of champions.

Aren't they EXTREMELY hazardous to even exist? They just dump rad everywhere and lot of them. That sounds like a really bad idea.

**Comment by BomberBro** [comment]
I hate the idea of guaranteed supermatter splinters, and I hate the idea moreso of guaranteed supermatter crystals (via mechanic scanning a machine). It makes the entire thing less special when it's not really that difficult (20 minute job for a traitor mechanic if that) to get an instant round ending bus item like that.

**Comment by Kurfursten** [comment]
It won't be scannable. Nor would I say that having a trader in a round (and one who is buying engineering crates) is guaranteed.

>What about the vendor

Before this PR comes off WiP, the tradevend will be a vendor no more. It never should have been scannable, or hackable, or have a throw wire - these are all just because putting things in the vendor was a lazy solution a long time ago. For years I have considered rebuilding it properly as a unique thing, and now is finally the impetus to take action. I just hate making UIs. If I didn't, this would have happened years ago.

So in any case, don't vote based on thinking it will be possible to get enough splinters for a crystal from traders, because that won't be the case. This PR is fully on hold until my new project is done.

>re:strawberry

Yeah I'm not into the superpower cereal idea at all either. I like it how it is, an homage to engine degreasing like in the TEG.

**Comment by help-maint** [comment]
Regarding the chemical waste discussion:
Chemical waste exists in some Discount Dan foods and is easily made via polyacrylate, so it's not supposed to be _extremely deadly_ to ingest (it's just burnt lube really)

**Comment by mrflarg** [comment]
would be cool if the anti matter axe could shoot out fire if you use it on fire enough, nothing lethal just to look cool.

**Comment by Durgen** [comment]
i keep the faith

**Comment by Blithering** [comment]
One day for sure.

>Aren't they EXTREMELY hazardous to even exist? They just dump rad everywhere and lot of them. That sounds like a really bad idea.

With the changes to rad collectors that might open the way to a low maintenance but less effective alternative to the gourmonger engine, if you can find someone fool enough to step into containment and take a bite. As for bad idea, its about as bad of an idea as chewing on flakes of supermatter in the first place.

**Comment by Eneocho** [comment]
> With the changes to rad collectors that might open the way to a low maintenance but less effective alternative to the gourmonger engine, if you can find someone fool enough to step into containment and take a bite.

"Engiman says: "Hey clown, eat this."" "Aunt Scootaloo exclaims: "Ok!"" "Aunt Scootaloo tries eating from the box of Waste-Os and bites a supermatter splinter, rapidly mutating into a supermatter shade."

**Comment by Eneocho** [comment]
@Kurfursten 
Today I will remind them

**Comment by DeityLink** [comment]
> The antimatter axe is the solution to that question. Converts your boring matter axe into an antimatter one. It is full of stars and inhales fires, extinguishing them and cooling rooms, when wielded/unwielded.

must resist pointing out that's not how anti-matter works at all but I like the item mechanically.

**Comment by Kurfursten** [comment]
@Eneocho This is waiting on the vendor overhaul that I am working on, which I hope to post next week

**Comment by Eneocho** [comment]
> 
> 
> > The antimatter axe is the solution to that question. Converts your boring matter axe into an antimatter one. It is full of stars and inhales fires, extinguishing them and cooling rooms, when wielded/unwielded.
> 
> must resist pointing out that's not how anti-matter works at all but I like the item mechanically.

Lets just say it uses antimatter as it's power source and has all of the other stuff powered by said antimatter.

**Comment by DeityLink** [comment]
antimatter isn't a source of power on its own. It's an unstable form of existence that causes high energy release when it comes into contact with actual matter. The process is highly explosive and dangerous and AME are basically giant antimatter explosion containers that can convert that energy into electricity. The action of extinguishing fire sounds instead like something an entropy accelerating device would do, and anti-matter is as anti-entropy as it gets.

**Comment by Eneocho** [comment]
> 
> 
> antimatter isn't a source of power on its own. It's an unstable form of existence that causes high energy release when it comes into contact with actual matter

Lemme correct myself: Lets just say it uses antimatter as it's power source via annihilation, but it's a small attogram amount so no (visible) explosion. 

>The action of extinguishing fire sounds instead like something an entropy accelerating device would do, and anti-matter is as anti-entropy as it gets.

The axe could just be syphoning away the fuel then something something annihilating said fuel it with the antimatter inside the axe to power more fuel-sucking.

>entropy accelerating device

We need guns that use such devices to freeze the target.

**Comment by Eneocho** [comment]
`>there's a massive fire`
`>rush for my trusty antimatter fireaxe`
`>grab the antimatter fireaxe`
`>the handle is also antimatter`
`>both me and the axe explode`
`>shuttle gets called`

**Comment by Blithering** [comment]
To be fair an axe that accelerates the heat death of the universe by causing its own entropy field just to make fires go out faster sounds badass.

**Comment by Eneocho** [comment]
@Kurfursten
Today I will remind them, again.

**Comment by Kurfursten** [comment]
This is not abandoned, it's just that making the new trader "vendor" is very tedious. I hate working with NanoUI and it uses Nano. I had really hoped to have it done by now but it's been a slow crawl to work on. I even thought it might be done a month ago.

**Comment by Kurfursten** [comment]
As promised, now that you can't duplicate more of those delicious Waste-Os, I am coming back to this PR. It's still a WIP but it's my priority for this week.

**Comment by Exxion** [comment]
>antimatter isn't a source of power on its own. It's an unstable form of existence

Antimatter is no less stable than normal matter. Both are annihilated when they contact the other. There just happens to be more normal matter in our universe, for reasons we do not understand.

>anti-matter is as anti-entropy as it gets.

I don't think this means anything

**Comment by Kurfursten** [comment]
It's **FINALLY** done

Some notable changes
* New, animated sprite for the antimatter axe. The description also makes it clear that it's not actually made out antimatter and that's just a clever name for whatever this exotic material is.
* Antimatter axe now inhales a lot more air from the room. It has extended lungs (illegal).
* Master toolbox can now quickgather materials and has a more verbose description.
* Wasteos will clear out any bad reagents you pour in so you don't accidentally brick the item.

**Pull request merged**
