### PR TITLE
Investigation Glasses

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Adds a unique version of the Tracking Glasses to the Detective Gear box. This version combines the SecHUD with the tracking capabilities of the eye tracking glasses. Added a unique sprite and worn-sprite.

## Why it's good

Helps increase the detective's investigative abilities.

## Changelog

:cl:
 * rscadd: Investigation Glasses can now be found in the Detective Gear box, allowing detectives to track eye movements.

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
the 10 year return of the detective thermals

**Comment by tinysaturn** [comment]
can't wait to get instantly gunned down by a detective using .357 ammo after briefly admiring the RD's head I just stuffed into my bag

**Comment by Eneocho** [comment]
This gives me an excuse to stunglove the detective and stomp on the glasses, based.

**Comment by Theophrastus1** [comment]
Nice another way to make detective mains commit suicide

**Comment by Eneocho** [comment]
You could approach the detective and autoclick examine the clown's bike horn, such that it saturates his glasses, not letting him see anything other than HONKY MCCLOWNO looks closely at the BIKE HORN.

**Comment by west3436** [comment]
> You could approach the detective and autoclick examine the clown's bike horn, such that it saturates his glasses, not letting him see anything other than HONKY MCCLOWNO looks closely at the BIKE HORN.

feature

**Comment by Eneocho** [comment]
Don't get me wrong, west. I'm saying I WILL be the clown that does that to the detective, not that it should be fixed cause someone will do it.

**Comment by xeroxemnas** [comment]
I WEAR MY SUNGLASSES AT NIGHT SO I CAN KEEP TRACK OF VISIONS IN MY EYES

**Comment by Kurfursten** [comment]
confl

**Comment by pedr69** [comment]
BRO YOUR BRANCHES

**Comment by west3436** [comment]
JUST FUCK MY SHIT UP

**Pull request closed without merging**
