### PR TITLE
Traitor discount item of the day

### PR DESCRIPTION
**Pull request by ShiftyRail**
image

On suggestion of some anon on the thread. The idea is to show some lesser-known traitor items (such as freedom implants) and encourage players to build their antag ideas around them, rather than go for tried and true greytide/eimplant/etC.
Should change every day at midnight (server time).
Cost reduction is a flat 50%. Too much? Too little? Open to discussion.

I personally do not believe this fixes the flaws with many of these items (chiefly, that they are too niche to be useful, and in most cases will just be evidence-burden, or that they are clumsy to use), but this is a first step to remind people that those items "exist."

For now, all items are available, and 3 are discounted. This is also open for debate.

:cl:
- rscadd: Up to three uplink items will now be "discounted" each round, to encourage players to try new/underused items.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
I assume this will also take the "random" item into consideration? As in it would effectively be 1/4 the cost if you random a discount item? Not a bad thing at all, just checking.

I like the idea, but I also think you should remove bundles and uplink implants from the possible discount pool. 1/2 cost bundles would be absurd, and 1/2 cost uplink implants would effectively allow you infinite TC, since getting one on a random roll already profits you TC.

**Comment by ShiftyRail** [comment]
>I assume this will also take the "random" item into consideration?

Yes, the "random" item will also have its cost discounted if it happens to pick one item one day. Good point on bundles/uplink one.

**Comment by wotisjanitor** [comment]
can the cooperative cells ones get discounted? it would be funny

**Comment by ShiftyRail** [comment]
They can, although to my knoweldge it never brings the cost down to something a single traitor can afford. Can make something special for them, too.

**Comment by Kurfursten** [comment]
You're already using persistence. Instead of cycle through every item on a discount, why don't you just track which items are rarely picked and discount those? Instead of having some day where emag and ebow are half price.

**Comment by ShiftyRail** [comment]
Could be good actually, but such a system will need a bit of inertia. Like keep track of when items are picked and then exclude those items picked the last day of the possible choice? I'm not sure of the details, to be honest.

I wanted something simple at first to build on.

**Comment by GreatBigFailure** [comment]
If you do end up going with less-common items being discounted, I think preventing overly popular items from being discounted would be a better route than discounting less popular ones. I can see syndicate soap and the toolbox ending up forever-discounted with no one wanting to pick them, for example. If you just prevent emags and other popular ones there will be a bigger pool of interesting but not often picked items.

**Comment by jwhitak** [comment]
Generate new selections per round, please (even if it's a high probability of being the same items)! I don't want to see people metagaming based on what they themselves had discounted in their own antag round.

**Comment by DorainGrey** [comment]
> Generate new selections per round, please (even if it's a high probability of being the same items)! I don't want to see people metagaming based on what they themselves had discounted in their own antag round.

Yeah I feel persistence is a bit much, just a random selection is fine. I don't think it'll be metagamed but simplicity is usually best. 

I definitely agree though, it'd be nice to remove emag, ebow from the rotation.

**Comment by Eneocho** [comment]
fuck it make the emag 3tc all the time so you can buy all the nonstandard items whilst keeping the funny card

**Comment by wotisjanitor** [comment]
nopony uses the ebow

**Comment by ShiftyRail** [comment]
@jwhitak 

>I don't want to see people metagaming based on what they themselves had discounted in their own antag round.

What sort of metagaming? "Oh I know the ebow/esword is on discount so I'll be careful about it"?

**Comment by jwhitak** [comment]
That sort, yeah. Esword discounted is one thing, but, for example: if you see a rarely taken item like the cargo wrap on discount in your antag round and the next round you see a dude running around openly with cargo wrap? It's suddenly more stressful on you how to react to this properly since you have the meta knowledge of the discount from last round. I guess it's not a huge deal, but just something to keep in mind. Randomness would give some deniability.

Even if you don't change this though you'll still have my thumbs up. Cool feature.

**Comment by nervere** [comment]
Big agree with Dilt here, a per-round rotation just makes sense over a daily one.

**Comment by ShiftyRail** [comment]
Will make it round by round, then.

**Comment by Eneocho** [comment]
Instead of being called Discount of the Day it could instead be called "Discounted Surplus", it'd fit with the whole rarely used items are cheaper 'cause they make the stuff like the syndiesoap and nobody uses it, so they end up with surplus.

**Comment by ShiftyRail** [comment]
Done all suggestion, it's now a round-by-round thing.

**Comment by Kurfursten** [comment]
what's going on with those tgui bundle changes?

**Comment by ShiftyRail** [comment]
I had to slightly change the TG UI interface for the uplink and I guess it changed the bundled/compiled file.

**Comment by Kurfursten** [comment]
Just for the sake of security, check a few other tgui machines like merchandise computer, sec cams, etc. to make sure this did not have any unintended consequences for tgui, otherwise code looks fine

**Comment by ShiftyRail** [comment]
image

Seems to be working (other than this branch being on EU lights)

**Pull request merged**
