### PR TITLE
Small Spessmart update

### PR DESCRIPTION
**Pull request by unid15**
* Spessmart backroom now contains a fuel tank and every tool needed to destroy rwalls. Unless you somehow lose or break these tools, you can now escape from a locked down spessmart

* Windows at the entrance are now tinted. This means rogue space carps or other hostile mobs will no longer aggro on the spessmart greeters, break windows and trigger lockdown

* Fixed runtime that caused the bots to no longer ~say welcome to costco I love you~ greet new customers

* Updated some spessmart prices

* Added new spessmart goods. Most importantly:
  * goliath hides (50)
  * advanced lazarus injector (750) 
  * socket wrench (150)
  * shuttle destination disk to a random vault with a docking port (90) - the vault might be spessmart itself
  * camera that takes 5x5 photos (300)
  * energy shields (1000)
  * bullwhips (200)
  * morningstars (300)
  * subspace tunnelers (500)
  * powersinks (700)
  * emags (1500)
  * cloaks of cloaking (800)
  * chloral hydrate injectors disguised as pens (1200)
  * syndicate device analyzers (15000)
  * pills: cyanide(400), drugs(20), nanobots(500), creatine(700)
  * chempack(350) and chemmask(350)
  * DNA injectors: elvis, swedish (50), jump, matter eater (250), hulk (500)
  * Dual lightsaber (3200)
  * Chemsprayer (300)

### CODE REVIEW

**Comment by Kurfursten** [comment]
Update wiki pls

**Comment by Yelier** [comment]
Emag for 500 sounds fucking crazy. Other than that, nice stuff.

**Comment by ghost** [comment]
The robots in the entrance are movable and fly out of the entrance if the door gets opened, unless that was fixed

**Comment by AutismSpider** [comment]
Emag should be 2000 or 3000

**Comment by DamianX** [comment]
subspace tunneler for 500?

**Comment by Shadowmech88** [comment]
@smalIboss
It was fixed, the entrance robots are encased by windows on all sides now.

**Comment by Shadowmech88** [comment]
>Spessmart backroom now contains a fuel tank and every tool needed to destroy rwalls.

Isn't the perimeter of Spessmart made of indestructable rwalls, though? Or are the rwalls at the entrance just normal rwalls?

**Comment by unid15** [comment]
Only the shopping area is surrounded by indestructible rwalls (with no shutters), the rest of the store is normal walls/rwalls

Also I had no idea that there was a list of vaults on the wiki. Whoever made it did a great job!

Will update the wiki when it gets merged

**Comment by Probe1** [comment]
@unid15 Please redo how the clothing is handled with a list of what can spawn instead of anything with a few exclusions.  It isn't maintainable and frequently shit comes up that have no sprites and no one knew existed.

**Pull request merged**
