### PR TITLE
Syndicate Elite Strike Team suits

### PR DESCRIPTION
**Pull request by DeityLink**
image
chicken for scale

:cl:
* rscadd: Added new rigs for the Syndicate Elite Strike Team, to replace the old-looking black space suits. Their armor values are midway between nuke ops' and deathsquads'.
* imageadd: OSIPR ammo bar is now red, to fit the Elite Syndies better.

### CODE REVIEW

**Comment by yclatious** [comment]
Goddamn that looks nice, good job mate.

**Comment by Riekland** [comment]
syndicate strike teams are fat! FAT!

**Comment by Blithering** [comment]
There's an unused 'heavy' syndi hardsuit that could be recoloured for this to make them look more imposing
quick mockup 
syndi

**Comment by DeityLink** [comment]
@Blithering That's the nuke op leader suit. Also more imposing isn't what we're going for here. The idea was "reverse-engineered deathsquad technology", and you'll notice that the deathsquad suits are pretty slim despite their protection.

Not to mention these suits are meant to be optimized for piloting mechas, so huge and bulky is counter productive.

**Comment by Blithering** [comment]
Fair enough. I'll probably finish off the sprite anyway, more options for bus shenannigans.

**Comment by Intigracy** [comment]
Why does that suit have boobs, Blithering.

**Comment by Shadowmech88** [comment]
They're tactical boobs to distract enemy combatants.

**Comment by Blithering** [comment]
4eaae26028a004cba75f636bb81b2abb
umojanmarine_sc2-hots_devart1

Nipple lights are a proud tradition of power armour.
They are powered entirely by chafing.

**Pull request merged**
