### PR TITLE
Grue Health Regen scaling adjustment

### PR DESCRIPTION
**Pull request by Dacendeth**
## What this does

Changes Grues Health regen based on kills

```
Current Grue health regen based on consumes(1.5) 
0	4.5
1	6.75
2	10.125
3	15.1875
4	22.78125
5	34.171875
6	51.2578125
7	76.88671875
8	115.330078125
9	172.9951171875
10	259.49267578125
20	10 is already 100% per tick
```

```
This PR changes (1.1)
0	4.5
1	4.95
2	5.445
3	5.9895
4	6.58845
5	7.247295
6	7.9720245
7	8.76922695
8	9.646149645
9	10.6107646095
10	11.67184107045
20	30.2737497719652
```

## Why it's good

Grues after 5+ kills basically are unkillable due to being able to just run away with their speed scaling, and I figured the speed is a fun aspect of the antag while the health regen is more frustrating to deal with as there's nothing really you can do if it runs away turbo fast and instantly heals and comes back over and over.

I will say that rewriting this to something more sane would ultimately be better but I am a simple one line changer.
## How it was tested

Ate things and recorded the health regen changes for a few kills, then did math for rest of it.
## Changelog

:cl:
 * tweak: Grues health regen has been lowered massively

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Are they going to get anything to make up for their awful early game?

**Comment by Dacendeth** [comment]
Personally I think the best thing to do overall for them is a complete rework that removes all the scaling but buffs their base stats but hinacode is a nightmare to undo.

**Comment by MercuriusGH** [comment]
skill issue moment

**Comment by ErrorsWindows** [comment]
> Personally I think the best thing to do overall for them is a complete rework that removes all the scaling but buffs their base stats but hinacode is a nightmare to undo.

truly, the threat that God sends if He doesn't see enough people for xenos

**Comment by jwhitak** [comment]
Folks have been complaining about Grues so cutting off the snowballing a bit is a good idea. Grues probably need some more advanced work done on them, but this bandaid will do well enough for now.

**Pull request merged**
