### PR TITLE
Revert "Fixes a duplicate Bump() for bumping on turfs"

### LINKED ISSUE #9684: Have to manually click on tiles for mining
(WEB REPORT BY: aceedex REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b568fab0d12fed2021d087c8aef247cdd2d3b8fe 
> 
> General description of the issue
> Instead of just bumping into walls and starting to mine, now I need to go around clicking on em to start the mining proccess
> 
> What you expected to happen
> To just shoulder tackle walls to make minerals appear
> 
> What actually happened
> The mining proccess is now a giant pain in the bootyhole that would only be enjoyed by a legitimate mental patient
> 
> Steps to reproduce if possible
> Grab a pickaxe and try to mine

### PR DESCRIPTION
**Pull request by Exxion**
Reverts #9673, fixes #9684

Fixing this properly will have to wait for basically a full rewrite of move code

### CODE REVIEW

**Comment by gbasood** [comment]
I think this won't break meteor code which was why I wrote it in the first place, but we'll still have things bumping turfs after they've already bumped a thing once for no raisin

Would rather see a fix at mob/living/carbon/human level for mining turfs

**Comment by Exxion** [comment]
The second call to `Bump()` on the turf immediately returns 0 for most things anyway, so it's pretty much irrelevant

**Comment by gbasood** [comment]
I don't know, I feel like this isn't the only way to fix it if it's just mining

**Comment by clusterfack** [comment]
Sood I investigated this and it goes much deeper than just mining, this is definitely the best way for now

**Comment by Exxion** [comment]
I like how everything immediately obvious worked with my last "fix" but then absolutely everything else didn't

**Comment by Probe1** [comment]
[house of cards code]

**Comment by clusterfack** [comment]
It's literally a hack built on top of a hack built on another hack.

**Pull request merged**
