### PR TITLE
Hud Scaling

### PR DESCRIPTION
**Pull request by clusterfack**
I hate busywork

Huds now scale positioning with client view.

Exceptions : pretty sure damageoverlay, darkmask, blurry vision which all have unique sprites and dont use screen locs. To fix those we need to use scale() along with a standardized proc for changing view size.

### CODE REVIEW

**Comment by PJB3005** [comment]
FINALLY

**Comment by clusterfack** [comment]
I told everyone how to do it but no one actually bothered

**Comment by Probe1** [comment]
more like no ones as smart as you

:+1:

**Comment by PJB3005** [comment]
Clusterfack is the hero we want, but don't deserve.

**Pull request merged**
