### PR TITLE
[HOTFIX] REEEEEEEEEEEpairs comparison circuits

### PR DESCRIPTION
**Pull request by unid15**
fixes comparison circuits not working if the second value is an assembly

### CODE REVIEW

**Comment by 9600bauds** [comment]
One hundred percent tested?

**Comment by unid15** [comment]
yes :100:%

**Comment by 9600bauds** [comment]
Drop a message when you want this merged after Travis finishes

**Comment by unid15** [comment]
let's do this @9600bauds

**Comment by 9600bauds** [comment]
wooooooow

**Comment by PJB3005** [comment]
`:^)`

**Comment by ghost** [comment]
Haahhahaha

**Pull request merged**
