### PR TITLE
Removes gas miners from Box Station main station

### PR DESCRIPTION
**Pull request by Hinaichigo**
[balance]
## What this does
This removes the gas miners from the atmos area of the main station on Box. This is a first, probationary step in the wider removal of most gas miners from most maps. If it's received well and plays well, then we can proceed further. Though gas miners have been in the game for a long time and may seem innocuous or even beneficial, I beseech the reader to consider my reasoning here.

## Why it's good
  The atmospherics system is designed to circulate gas through the station, pumping gases to fill spaces with target levels of gas, and scrubbing and filtering out unwanted gas. This functionality works perfectly fine without gas miners. So what do gas miners actually do? Functionally, they continually release a given type of gas into the surrounding air if they detect a local air pressure of less than 10k kPa. Above that value, they remain idle. At roundstart, the atmospherics gas chambers on most maps are initialized with pressures well above this value, so the gas miners are idle, only activating if there is a significant drop in chamber pressure, perhaps as a result of a massive hull breach. Gas miners, then, essentially serve as a way to prevent the station from running out of gas in the event of a massive loss of atmosphere.
  Now, one may ask: "Isn't this a good thing? Don't we want the station to always have enough gas to keep running?" If we think from the in-round perspective of a NanoTrasen employee, then this makes sense. But in terms of the effect it has on the gameplay, it is different. There are many ways to sabotage a station: release the singularity, bomb the bridge or medical, kill the crew, sabotage the power system, etc. Indeed the struggle to keep the station intact and running smoothly is one of the essential, core elements of the game. And as we all well know, there are ways to rebuild, but if it does get too catastrophic, the shuttle gets called and the round ends. One might wonder why I rehearse these fundaments here; I think it's important to keep them in mind while we turn our attention back to gas miners.
  I posit that the risk of the station catastrophically losing atmosphere _should_ be embraced as part of the gameplay, not minimized or prevented. It is the job of atmospherics technicians, engineers, and security staff to keep this from happening. Gas miners essentially "water down" the dangers of atmospheric mishaps, which I believe is to the detriment of the richness of the round dynamics.
  Having a readily-available, unlimited source of gas also lowers the richness of the sandbox-simulation. Gas no longer is a vital, precious resource to be managed and utilized efficiently; it becomes something of infinite abundance that can be disposed of and replenished without significant consequence, which is very much apart from the general design philosophy used in most of the other systems in the game.
  And finally, from a lore perspective, gas miners don't make sense in the context of how everything else works. In one round I saw someone pulling a gas miner that through the hallways to refill the depleted atmos. The mental gymnastics required to prevent immersion breaking there were Olympic level. Either there is a space elevator with a gas pipeline connected to the station, a continuous stream of drones are flying in and loading fresh canisters of gas, or the gas is being teleported in via some form of telescience. None of these are satisfactory, because they imply some sort of immutable, unseen component of the station that the players lack control or influence over. The telescience explanation also doesn't make sense because generally teleportation is either done by magic, is uncontrolled (wormholes), is controlled but fairly short-range, or is expensive, costing precious telecrystals to get items to syndicate agents. The implication that NanoTrasen has brought telescience to such a high art that the capacity to cost-effectively and continually teleport massive quantities of gas thousands or hundreds-of-thousands of miles is a standard feature on their stations, doesn't make sense.

## Changelog
:cl:
 * rscdel: Removed gas miners from atmospherics on Box Station.

### CODE REVIEW

**Comment by adacovsk** [comment]
Maps like deff drain air rapidly even with minor breaches, this would require multiple map overhauls and doesn't solve the issue of breaching the pressure chambers. If anything, consider keeping the miners anchored

**Comment by Hinaichigo** [comment]
Each map could be treated appropriately. And we could also amp up the security around the chambers. But consider that you can simply approach from space and snip the singularity emitter wires on Box as well, which is arguably more catastrophic, and that there are also lots of reserve gas canisters in atmos already.

**Comment by DorainGrey** [comment]
> Each map could be treated appropriately. And we could also amp up the security around the chambers. But consider that you can simply approach from space and snip the singularity emitter wires on Box as well, which is arguably more catastrophic, and that there are also lots of reserve gas canisters in atmos already.

That kind of a false equivalence, the singularity is only one of many engines. You accept that risk when you set it up, instead of other safer engines. 
Atmos has no alternative, so easy sabotage there is unavoidable and affects all rounds, not just ones where the singularity is setup.

**Comment by Hinaichigo** [comment]
You're right to say that atmos is a critical component of the station. What I'm saying is that it being critical doesn't mean it should be made "less critical" via gas miners, but instead it should be protected and secured (by players) with the same level of diligence as say, the AI core or the armory. In other words, the desired effect of this change is to make safeguarding the integrity of the atmos system more important.

**Comment by DorainGrey** [comment]
While I do like the idea of a gas economy & encouraging the re-use of gas through the waste filter for example, I don't think the benefits outweigh the cons on /vg/station specifically. I'll outline why.

- Plasma cooling: The amount available in atmos chambers alone, is simply not enough to do any good atmospheric projects. Cooling large amounts of plasma down to absolute zero, would easily exhaust all the available gas. This leaves very little scope for any actual atmospherics or engineering projects.

- Breaches: As pointed out above, breaches eat up a lot of gas. Each tile on station is 2500L in volume, our ideal laws tell us that each tile therefore needs approximately 103.5946 Mols of gas. Which means even a small six tile room uses 600-700 mols of gas out of total 61541.4~ Mols available in Box's atmospheric chambers. Large breaches like hallways or maintenance use substantially more gasses, so any sort of major damage and the station will run out quickly.

- Sabotage: In the situation of sabotage, what is the crew supposed to do? Even if there way to order gas from centcomm, you'd need huge amounts to be able to just fill the distro and re-pressurize a room. Honestly it seems like it would be a round-ender most of the time.

- Gameplay: What gameplay does this actually enable that outweighs the negatives above? 
It does encourage saving waste gasses, but all that involves is flicking one digital valve to enable the waste filter loop in atmos.

**Comment by AutismSpider** [comment]
can air

**Comment by Dacendeth** [comment]
Nah.

**Comment by DorainGrey** [comment]
> You're right to say that atmos is a critical component of the station. What I'm saying is that it being critical doesn't mean it should be made "less critical" via gas miners, but instead it should be protected and secured (by players) with the same level of diligence as say, the AI core or the armory. In other words, the desired effect of this change is to make safeguarding the integrity of the atmos system more important.

Atmospheric chambers aren't protected though, they are easily accessible with a ghetto spacesuit and require minimal tools to cripple.

Contrast this to the AI core, which on box for example is on the middle of the station, surrounded by multiple reinforced walls, doors and literal cannons.

The armory is similar, it's protected by double layers of reinforced walls, a security force. There's even a dedicated person, to ensure it stays secure.

You can't expect people to protect atmospherics, unless you give it similar defenses which wouldn't be feasible or fun.

**Comment by RedrobotAnnie** [comment]
Gotta be a better way than gutting an entire feature, nope.

**Comment by Pastamadness** [comment]
I believe that Atmos has been ruined for a long time with the miners and everything being setup at round start but this is a horrible chance by itself.
The moment people realized how easy it was to vent and empty the gas storages it became a common habit by traitors and griefers who didn't want to instantly bomb or singuloose but to nevertheless ruin the station forever and encourage a shuttle call.

This change of yours should only be accompanied by an actual system to make refilling Atmos easier, be it related to power, cash or minerals, perhaps make the miners work for a time only by consuming resources. To make gasses into actual resources to be managed and Atmos tech a real job again.
Would the retards here just vote it down because lmao fuck changes that aren't memes? Yes, but it's still the only viable alternative to removing the necessary crutches and griefing tools that are the miners.

**Comment by WindowsErrors** [comment]
Yep this is definitely a pull request submitted by Hitachinago

So you think atmos should be guarded with the same security as the armory and the AI? Even though it has multiple doors that lead directly to main maintenance tunnels, none of which are covered on security cameras, covered with shutters, or even kept with a nearby light fixture to deter any kind of forced entry?

___

I used to play on beestation and they had gas floors instead of gas miners

The roundstart supply of gas on DeltaStation (the normal map that the server was always set to when I was playing), was, for all practical purposes, infinite where it didn't matter. The gas floors started with about 1,000,000 moles of oxygen and nitrogen and similar amounts of CO2 and plasma, which was enough to repressurize (with the standard 20% oxygen 80% nitrogen 101 kpa mix) about 12,000 tiles plus some change. Even with areas constantly being drained, with the default atmos setup it'll still take hours for the tanks to completely empty while trying to repressurize the area

No one ever thought "Oh no, I need to close up this breach or our limited supply of air will run out soon"

What me and the other ssethtiders would quickly learn, however, was to simply take the fire axe that just so happens to spawn across the way from the gas tanks, smash the windows on the gas tank that lead directly to space, thereby venting the entire air supply of the station permanently within about 90 seconds of roundstart. Now the rest of the station realizes with creeping horror over the ensuing minutes that the only practical way to repressurize the station after any breach is to use the limited supply of canisters in maintenance or rig up a shitty little gas sucking operation on lavaland
Meanwhile that plasmaman or IPC that still has the fire axe and a firesuit has gone to the other side of the station, smashing external windows all the while, depressurizing arrivals, departures, security, science, dorms, the permabrig...

It was fucking silly, not even considering any perspectives on "fun" or "game balance" or anything like that, but the mere reality that a single guy with a toolbox can literally destroy the entire primary gas reserve in seconds with no way to replenish it

Even if they didn't do that, it's 25 minutes into the round and then along comes an innocent little atmos tech named WindowsErrors wanting to also use the oxygen for tritium or BZ or whatever and it's only too late that they realize that they've unknowingly burnt _literally the entire station's oxygen supply_ in less than 15 minutes in the incinerator making tritium

___

Gas miners aren't more "balanced", or more "fun", they're simply more sane, because it makes the gas supply a continuous, interruptible, repairable, and constructible process. It becomes a question of the number of breaches, the setup and configuration of atmos, whether or not someone has sabotaged and deconstructed the gas miners, or whatever, there's more things that can be done on both sides of the equation and the major station-wide interactions with atmos like continuous hull breaches or re-pressurizing areas remains pretty much the same than if there were just bare gas floors

**Comment by gurfan** [comment]
>So you think atmos should be guarded with the same security as the armory and the AI? 

yes, actually
Atmospherics is supposed to be a high security area and the fact that you can access it from maintenance is silly.

Regardless I don't really like this PR. Gas miners are far from perfect but gutting them without replacing them *at all* is beyond dumb. You might as well remove the atmospheric technician job and also every vent on the station if you do this.
Breaches are very common and air is lost every time someone exits the station through an airlock. This is not something that can really be prevented. All it takes is one man with a wrench to breach the window next to the bridge and make the hallway unusable.
Once the station inevitably loses its atmosphere, now there is no way to fix it.
Even if the gas chambers were filled with a lot of gas roundstart, there is no safety in place preventing vents from pumping gas out into space. When a breach occurs and goes unfixed (which happens most of the time) all the stored gas will be gone in an instant. The game, in it's current state, is not designed to treat gas as a finite resource.
Then there's also the plasma miner which is crucial to generating large amounts of power.
Gas miners are silly and it would be cool to replace them with something more interesting but this is absolutely retarded.

**Comment by WindowsErrors** [comment]
Yea exactly, how about we spend our time for a much more viable cause, maybe what half the other people here said by finding a way to increase the security of atmos before we start cutting redundancies, if atmos is the same level of security as the armory then that means it's about the same tier of security as that thing on Line where the armory and the evidence storage have those windows that directly border maintenance

Seriously, the situation of some random assistant just slithering into atmos through the maintenance door right in front of me with the emag still in their hands has happened more than once, there was even a time where they straight up asked me how to plasmaflood because they didn't know atmos and I stalled them until the redshirts came (they e-implanted)

I say this half jokingly but security gets portable ID locked barriers for their maintenance doors while the engineers have to settle with walling it off like this is the Triangle Shirtwaist Factory or some shit

**Comment by Hinaichigo** [comment]
I'll probably close this and take a look at making them consume power in exchange for gas production, possibly along the lines of them being "bluespace miners" each tuned to teleporting a specific molecular structure of gas. Maybe the power required per mol/s would be nonlinear so to get more gas out of them you have to increasingly amp up the power, and they could produce waste heat and require cooling or something.
I'll keep this open for a while to see what people have to say.

**Comment by Kurfursten** [comment]
I agree with your basic premise that Atmos issues should be a big deal, but I am satisfied already that the dark triad of Atmos issues is already enough.
1. Breach/ZAS deadly on a local level/depressurization spreads/fire lock annoyance
2. Maintain pipes against sabotage
3. Large rooms take significant time to refill

I feel if you ask anyone to rank various issues on the station, they would rate "major breach" as already one of the more important to deal with.

**Comment by adacovsk** [comment]
> I'll probably close this and take a look at making them consume power in exchange for gas production, possibly along the lines of them being "bluespace miners" each tuned to teleporting a specific molecular structure of gas. Maybe the power required per mol/s would be nonlinear so to get more gas out of them you have to increasingly amp up the power, and they could produce waste heat and require cooling or something. I'll keep this open for a while to see what people have to say.

With #32613, the miners could be put on a very low priority and this would really work well. I really want to see this

**Comment by pedr69** [comment]
yeah, make them take big watts to run instead of removing
gives engies something to do with the power

**Comment by Cartlord** [comment]
I do agree that they should be immovable, but removing them is a wretched idea.

**Comment by Exxion** [comment]
I agree that the gas miners in their current state are bad design, but just removing them with no viable replacement isn't really an option.

**Comment by Exxion** [comment]
I think there was a PR a while ago to replace them with the thing from #25157, or something. That machine's not all that interesting, though. I'd like to see something that actually requires some effort to get it to produce large amounts of gas, but can produce a *lot* of it if you do put the effort in. No idea what form that would take, though.
There's also the issue of lowpop, which needs *some* kind of relatively low-effort means of restoring atmos after breaches. Off the top of my head, some way to purchase supplemental air from cargo? Don't know how that would work either, though.

**Comment by Hinaichigo** [comment]
>I'd like to see something that actually requires some effort to get it to produce large amounts of gas, but can produce a lot of it if you do put the effort in.

Sub-linear gas output per power scaling might do this.

> Off the top of my head, some way to purchase supplemental air from cargo?

I was thinking about something like a "bluespace pressure vessel" that contains a massive amount of moles, enough to completely fill the station at least once over.

**Pull request closed without merging**
