### PR TITLE
Security belts can now hold .45 pistols

### PR DESCRIPTION
**Pull request by SonixApache**
_"If tasers fit in there, why shouldn't the pistols?"_

### CODE REVIEW

**Comment by Kurfursten** [comment]
You should let them carry entire pistols.

**Comment by SonixApache** [comment]
belts can't do math

**Comment by ghost** [comment]
So they can carry the pistol in their belt, but not the magazines for it?

**Comment by SonixApache** [comment]
Magazines already fit in the belt, actually.
And in bandoliers, too.

**Comment by FudgePucker** [comment]
Hell they could fit in bandoliers before the pistol was made. Its a subtype of magazine.

**Pull request merged**
