### PR TITLE
Delay Assassinate

### PR DESCRIPTION
**Pull request by Kurfursten**
You will now receive your assassinate objective after 10 minutes.

Untitled

Before you know the target's name they are called something from this list: data leaker, critical personnel, loved one of our enemy, mole, Nanotrasen asset, brilliant mind

I for one welcome assassinating Grug Unga, brilliant mind.

🆑 
* rscadd: Objectives can now exist as a delayed type where the target is chosen later. Assassinate is delayed 10 minutes for most antags (but not for revolutionaries). This means that latejoining within the first 10 minutes is functionally equal to being ready at start for roundstart assassinations.

### CODE REVIEW

**Comment by ghost** [comment]
What is this trying to solve?

**Comment by Caboozles** [comment]
Latejoins, I believe?

**Comment by Zth--** [comment]
This doesn't solve latjoins at all

**Comment by Kurfursten** [comment]
No one change will fix a multifaceted issue with many causes. With every step, we draw closer.

**Comment by Sooose** [comment]
Do people seriously latejoin just to not be a jectie?

**Comment by bathosbathtime** [comment]
A non-zero amount of people, yes.  I would bet the number of people is "1" but this will help nonetheless.

**Comment by Kurfursten** [comment]
I had an idea while observing today. I bet I can write this in a way that it instantly gives you your target if the shuttle docks at the station (or if you are autotratored after it docks). That way you don't get greentext blocked by late conversion.

**Comment by Goldsteel** [comment]
GRUG NO LIKE

**Comment by agentofzog2** [comment]
Don't kill the greentext speedrun!

**Comment by SonixApache** [comment]
Why doesn't it tell you who the target is once said target is identified?

**Comment by Kurfursten** [comment]
You can check it in IC->Notes

**Comment by SonixApache** [comment]
Yes, I know, but why doesn't it just tell you?

**Comment by Kurfursten** [comment]
No particular reason I suppose, it would be very easy to change if you wanted to. Just add [target.name] to the PostDelay() text

**Pull request merged**
