### PR TITLE
Borg Voices

### PR DESCRIPTION
**Pull request by Kurfursten**
0% tested because I can't get "hear player voices" pref to stay on while local testing

:cl:
* rscadd: Silicons now speak with their own voice sounds.

### CODE REVIEW

**Comment by SonixApache** [comment]
conflicts?

**Comment by TGFH** [comment]
Will this make it so people/posibrains in mechs have voices as well? That would be a welcome addition IMO.

**Comment by Kurfursten** [comment]
for now just silicons so yes to pAIs, no to posibrains, no to MMIs, no to people in mechs

**Comment by ShiftyRail** [comment]
@Kurfursten Want me to do the secret repo PR ?

**Comment by Kurfursten** [comment]
Yes please

**Pull request merged**
