### PR TITLE
Adds welding mask toggles to plasmaman engineer and atmos tech helmets

### PR DESCRIPTION
**Pull request by Repth1**
[tweak][consistency]
Adds welding mask toggles to plasmaman engineer and atmos tech helmets

For #21315 

:cl:
 * tweak:  In-built welding masks added to plasmaman engineer and atmos tech helmets

### CODE REVIEW

**Comment by Ephx1** [comment]
Just grab welding goggles, nerd

**Comment by Kitfox88** [comment]
muh mesons

**Comment by SonixApache** [comment]
just get welding goggles

**Comment by Repth1** [comment]
should the science helmet welding mask be removed then?

**Comment by bathosbathtime** [comment]
The vox also get welding toggles on their helmets if they are engineering, right?
Don't forget them if that's the road you're going down.  Racial differences should have weight to them so I would enjoy it in theory.

**Comment by Irradiation** [comment]
Plasmeme doctors also have a welding toggle for their helmet, so this sure sounds like a big case of consistency issues.

**Comment by Repth1** [comment]
im happy either way, it should just probably be consistent which jobs do or do not get welding mask

**Comment by jknpj** [comment]
I'm going to regret this later, most likely.

**Pull request merged**
