### PR TITLE
The Thermal Entropy Update: Subsystems & blowing on sausages

### PR DESCRIPTION
**Pull request by DeityLink**
**The values of this system have been adjusted to offer the best possible gameplay experience alongside the changes made by #35516**

Because I think that we don't need to simulate absolutely accurately the thermal dissipation of every single reagent container every moment, I coded a custom process that takes care of it in a much more abstract and arguably less realistic way, but that I think the average player will like more (and that consumes a negligible amount of CPU)

Basically: every 2 seconds, the container checks the surrounding air, and adjusts its reagents' temperatures inching toward room temperature using Newton's Law of Cooling. No dissipation occurs and the room temperature doesn't change. If the thermal difference is low enough, the process stops, saving even more CPU, and only resuming if the object is moved, or once per minute to ensure that passive temperature changes caused by fires, breaches and other good stuff eventually affects them.

The subsystem portion of #35516 as well as the one feature that depends on it: blowing on stuff to accelerate their entropy.

Here's the Profiler after letting the game idle for about 11 minutes with thermal dissipation disabled and the APC/SMES recharged. (I reset the counters at roundstart so the init stuff doesn't interfere)

image

:cl:
* experiment: Implemented a new subsystem that revamps the way reagent containers normalize their temperature in relation to the environment. This new method makes reagents reach room temperature quite faster on average (except when using a Stasis Beaker), and has been finely adjusted so temperature changes are more noticeable while also feeling realistic. You can Alt Middle click a beaker or food item to blow some air on them and accelerate the process. As an added bonus, this system consumes a negligible amount of CPU compared to the one in effect until now, and is much simpler to read and adjust, thus more maintainable.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Not urgent but when you get a chance please move over the performance charts to the OP of this PR as well - this PR will be automatically merged on Dec 12 (unless we find anything objectionable in the code review).

**Comment by DeityLink** [comment]
Sure, there you go.

The truth is that most of the CPU used by the subsystem in the profiler pics of the other PR comes from all the features I added on top _because_ the subsystem's own CPU usage was low enough to allow it.

**Comment by Kurfursten** [comment]
That's fair. If you want to reprofile on the ss alone you are more than welcome.

**Comment by DeityLink** [comment]
That's what I did! The Profiler pic in the OP was captured just an hour or so ago. It's just the CPU usage of the subsystem (and its impact on the reagent containers in the world)

**Comment by DeityLink** [comment]
And this here: https://github.com/vgstation-coders/vgstation13/pull/35516#issuecomment-1837276135
was the CPU usage WITH the other features. You can compare with the machinery subsystem to get an idea of the ratio

edit: actually it seems about the same overall, huh. Well regardless it's about **3.4% - 3.8%** of the machinery subsystem's Total CPU. With their optimizations to Thermal Dissipation Ember got the Total CPU usage to about **7%** of the machinery Total CPU. That's an improvement compared to before for sure. 

edit 2: might be worth noting that using spawns() instead of a subsystem somehow brought the CPU usage much lower https://github.com/vgstation-coders/vgstation13/pull/35516#issuecomment-1837181759 Maybe some optimizations can be done to subsystems as a whole. Not that I have any idea where to look at.

Anyway I guess we'll get the values that matter once our PRs are merged and we look at the Profiler during an actual round.

**Pull request merged**
