### PR TITLE
Airlocks now open and close much faster

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Halved duration basically
I did this PR because I think it's way more fun if the airlocks opened faster but that's it
image
Hope you like this PR as much as I do
If there are any problems please yell at me

:cl:
 * tweak: Airlocks will now open and close twice as fast

### CODE REVIEW

**Comment by RealestEstate** [comment]
the sec metaclub hates this PR because it will make it easier to escape from them

**Comment by SkowronX** [comment]
just make it so you can move through airlocks during their animation

**Comment by RealestEstate** [comment]
already a thing unless you mean immediately after it starts opening

**Comment by Exxion** [comment]
No, there was a PR to do that but it didn't go through

**Comment by ShiftyRail** [comment]
big buff to yakety saxxers

**Comment by PJB3005** [comment]
Do the same for windoors while you're at it.

**Comment by boy2mantwicethefam** [comment]
they already open fast

**Comment by Kurfursten** [comment]
I would prefer if some doors like the vault or armory "secure" type door still had the long animation to give them a little more oomph

That said the votes are clear on this

**Pull request merged**
