### PR TITLE
Fixes give spell forever

### LINKED ISSUE #9235: Give Spell under VV stops working.
Usually about half an hour into the round, give spell for mobs stops working and does absolutely nothing.

### PR DESCRIPTION
**Pull request by clusterfack**
Fixes #9235

### CODE REVIEW

**Comment by SkowronX** [comment]
THANK YOU. Good lord that shit pissed me off.

**Comment by gbasood** [comment]
>spells = null removed

why

**Comment by SkowronX** [comment]
#9235

**Comment by clusterfack** [comment]
Spells is a global list of spells which give spell draws from. Spells = null was mistakenly added for GC purposes into this destroy, but in reality it was nulling the global spells list which made give spell do nothing since had nothing to draw from.

**Pull request merged**
