### PR TITLE
Human leather color now depends on the color of their species' skin color

### LINKED ISSUE #19527: Grey skin is human colored
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
e803fb3f284ce39fb87b227867a9f063413042e2

# Description

Grey skin when skinned is human colored.
# Steps to Reproduce

Skin a grey, this isnt rocket science

# What you Expected

Grey Skin
# What Actually Happened

Pink Skin

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #19527

:cl:
* tweak: Human leather color now depends on the color of their species' skin color. (mask2697)

### CODE REVIEW

**Comment by Optimism333** [comment]
Could you perhaps show a screenshot of what it looks like after this change?

**Comment by DeityLink** [comment]
> 
> 
> Could you perhaps show a screenshot of what it looks like after this change?

image

Also made me discover that grey had no actually defined skin color so I fixed that

**Comment by GreatBigFailure** [comment]
Asking to have whips and leather items share the effect would be greedy and unreasonable. I'm doing it anyway.

**Comment by Eneocho** [comment]
I'd change the PR name and changelog to humanoid skin, since currently it sounds like butchering a human of a specific colour makes leather of that colour instead of the humanoid-based thing.

Also, seconding the leather products to have the different colours as well.

**Comment by Eneocho** [comment]
Can you add a bright yellow skin for clown leather? Please. I'll pay half a pomfcoin.

**Pull request merged**
