### PR TITLE
Pinpointer pinpointer in Hos locker

### PR DESCRIPTION
**Pull request by tuypo1**
Adds a pinpointer for the captains pinpointer to the head of securities locker on all maps
This does not interfere with nuke ops they use a special type of pinpointer that the pinpointer pinpointer ignores
used a pinpointer pinpointer instead of just a pinpointer so things aren't TOO easy for traitor HOS and to make things more interesting when somebody steals the pinpointer to hunt the captain
<box>
<deff>
<general>
<meta>
<packed>
<roid>
<tested>
<tweak>

:cl:
 * rscadd: Added a pinpointer pinpointer to the hos locker

### CODE REVIEW

**Comment by tuypo1** [comment]
Ah shit what did I break

**Comment by boy2mantwicethefam** [comment]
just give him a second pinpointer

**Comment by ghost** [comment]
You didn't commit the code for the pinpointerpinpointer

**Comment by tuypo1** [comment]
alright thanks glass, I will try and figure it out in the morning

**Comment by boy2mantwicethefam** [comment]
Have you tampered with mapping recently? Looks like mapping conflicts and only mapping, Travis didn't even kick in

**Comment by ghost** [comment]
I had assumed that a pinpointerpinpointer didn't already exist, but on web I see now that it looks like mapdiff bot broke. Try changing an arbitrary line and recommitting.

**Comment by tuypo1** [comment]
Alright I will try that, Maybe it is somehow related to that bug where lockers sometimes spawn with 2 of everything

**Comment by tuypo1** [comment]
Still won't quite work, I am tempted to just close this, redo it from scratch and open a new pr but I think I will wait to see if anybody can figure out the problem by the time I wake up tomorrow

**Comment by Kammerjunk** [comment]
it's not a compilation problem, it's a merge conflict
your branch has conflicts because merging it would break the history. check https://github.com/vgstation-coders/vgstation13/commits/Bleeding-Edge/code/game/objects/structures/crates_lockers/closets/secure/security.dm to see the commit history and compare dates to your own branch

**Comment by FudgePucker** [comment]
Obviously the next step is giving the HoP a Pinpoiner Pinpointer pinpointer

**Comment by brndd** [comment]
The HoP should get a Captain's Spare pinpointer pinpointer.

**Comment by Blithering** [comment]
Given how easy it is to melt, space or janiborg trash bag a pinpointer, a second regular pinpointer makes more sense than something to locate the first one.

**Comment by SonixApache** [comment]
>adding a joke item into a locker that's already filled to the brim with other shit

**Comment by tuypo1** [comment]
>Given how easy it is to melt, space or janiborg trash bag a pinpointer, a second regular pinpointer makes more sense than something to locate the first one.

makes me wonder if maybe the pinpointer should be given some similar protections tot he disc

**Comment by tuypo1** [comment]
Anyway going off what @Kammerjunk said I think the problem may be related to the sec essentials boxes, I won't be able to fix this for a while though, and if more people end up saying they would rather just a regular pinpointer I will close this when I get back and switch to that

**Comment by Kammerjunk** [comment]
the essentials boxes, yes. your branch is several months old. there is a commit point on vgstation13/Bleeding-Edge that modified this file that your branch tuypo1/new-pinpointer does not have

**Comment by RealestEstate** [comment]
@GlassEclipse 
#20158
it exists, made by yours truly

**Comment by Durgen** [comment]
Does it use the same sprite?

**Comment by agentofzog2** [comment]
> 
> 
> > Given how easy it is to melt, space or janiborg trash bag a pinpointer, a second regular pinpointer makes more sense than something to locate the first one.
> 
> makes me wonder if maybe the pinpointer should be given some similar protections tot he disc

Last time I checked the pinpointer already has trashbag and pacid protection.

**Comment by RealestEstate** [comment]
@durgen no it uses my original OC donut steel fan sprite called “blue pinpointer”

**Comment by tuypo1** [comment]
This seems rather controversial so rather than trying to fix this I will close it and see if people react better to just a regular pinpointer

**Pull request closed without merging**
