### PR TITLE
Update sql page

### PR DESCRIPTION
**Pull request by MadmanMartian**
An old coder has returned, and informed me of an issue.

This page needs to be updated any time you add something to the sql. #22365 will need to update this page too before it is merged.

### CODE REVIEW

**Comment by Kammerjunk** [comment]
so is this the cause of the nameless SQL errors that have popped up now and then

**Comment by MadmanMartian** [comment]
no? maybe?

**Comment by Exxion** [comment]
If it's error 0 then that's not even an error, if I understand correctly

**Comment by Kammerjunk** [comment]
amazing

**Pull request merged**
