### PR TITLE
Renames every instance of wizmobile into firebird

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
@iFlashYou 
:cl:
 * spellcheck: Changed every instance of "wizmobile" in the code to "firebird". This will not impact gameplay.

### CODE REVIEW

**Comment by SonixApache** [comment]
if it doesn't affect gameplay or the player front-end there doesn't really need to be a changelog

**Comment by boy2mantwicethefam** [comment]
I'm not a sneaky coder

**Comment by SonixApache** [comment]
Nobody who reads the changelogs cares about this change nor really knows what it even does.
No need to clutter the log with back-end shit that doesn't affect anyone.

**Comment by boy2mantwicethefam** [comment]
it will help innocent admins to know that wizmobile was changed to firebird so that they finally trade it with a smaller delay for my goonecode when I raid the satellite with hulk powers

**Comment by SonixApache** [comment]
fair

**Comment by iFlashYou** [comment]
speedmerge

**Comment by ShiftyRail** [comment]
You don't need a changelog for that at all but that's not terribly confusing

**Pull request merged**
