### PR TITLE
Cursed Dice Tweaks

### PR DESCRIPTION
**Pull request by JonathanSpaceStation**
This PR changes some aspects of cursed dice; specifically:

1. A roll of 1 will no longer turn you into a cluwne, instead it turns you into a catbeast; I've been meaning to suggest this change for a long time because being cluwned is real awful especially compared with the kinds of rewards offered by the dice, and it often means cursed dice remove people from the round far too easily.
2. A roll of 2 - 5 will no longer turn you into a catbeast, this is now something that can only happen on a roll of 1
3. cat ears from bad rolls now have the awful text filters applied to them
4. New Reward: a bag of 5 random potions can now be granted for good rolls

<tweak>

:cl:
 * rscadd: Cursed dice has now been tweaked with a new reward, and with cluwning being removed as a possible punishment

### CODE REVIEW

**Comment by Dacendeth** [comment]
Dice not cluwning the unluckiest is sad, should make on a roll of 1 it picks randomly between awful things, and cluwne is one of them.

**Comment by JonathanSpaceStation** [comment]
Being cluwned is just anti-fun; I think in their current iteration cursed dice are just too likely to remove people from the round and I don't think thats great for an item that is fairly straightforward to acquire. 

Cluwning should remain what it was originally envisioned as; an admin punishment

**Comment by SonixApache** [comment]
Cluwnes can be uncluwned through non-admin methods and usually, in my experience, in mid-highpop, someone getting cluwned leads to the Quest for Uncluwning which is fun for all parties involved.
However I do agree that it is pain and an admin punishment for a reason. A double roll like @Dacendeth suggested might be an idea: on a 1-1 is cluwne, 1-2 is faguette, 1-3 and beyond is various flavors of catbeast.

**Comment by JonathanSpaceStation** [comment]
I really think you are overestimating how fun it is for anyone involved; only fix (outside of staff of change) is being a high cost machine, so its more often a case of whether a scientist has had the time and resources to make it (usually not).

Cursed dice in their current form are a bit of a grief trap because the moment one appears on station; a good chunk of people will rush to roll it. Depending on how many rolls you get before it explodes or goes inert; you can get anywhere between 2 - 5 people dying cause of it. Removing cluwning at least means that there isn't a scenario where the victims are (extremely unlikely) to be fixable.

I wouldn't be adverse to adding other punishments but I think cluwning is just bad

**Comment by Kurfursten** [comment]
I've also been part of the uncluwning quest and I think it's fun. One time on Roidstation I had to rescue the RD with the mind machine.

**Comment by gurfan** [comment]
~~The mind machine doesn't even work on cluwnes, I'm not sure why that is being brought up.~~ The only way to fix a man turned cluwnes is through a clone backup, in my experience.

Edit: that might have been because the cluwne was a cultist I'm actually not sure

**Comment by JonathanSpaceStation** [comment]
@gurfan mind machine does work on cluwnes for what its worth

**Comment by Kurfursten** [comment]
I have definitely uncluwned someone with a mind machine

**Comment by Blithering** [comment]
Maybe if it transmogrified instead of full mob replace, so when you're put out of your honking misery your corpse can be human.

**Comment by Kurfursten** [comment]
The emojis have spoken, though I dislike it

**Pull request merged**
