### PR TITLE
Rogue robot improvements (number one will shock you!)

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
This took a while, it's untested and this is why it's a draft.
Here's the changes:

- **Hacked robots cannot be blown up.** This is the most balance-wise change here and possibly the most important, which is why I'm putting it upfront. They can't be locked down either.
- **Malfunctioning AI can subvert robots not under its control.** As a bonus, it is able to see every robot that isn't rogue or emag-subverted and take control of them. It also can't take control of robots that are subservient to other malfunctioning AIs.
- **Traitor robots gained a new ability.** They may now choose to disconnect from the AI network, becoming permanently invisible on the robotics console and unlocking their emagged module. They are also notified of this ability. (I tried to check if they are already granted the emag module but I just didn't find anywhere)
- **A slightly neater robotics console menu.** For malf AIs that it. They get a red message on the first menu signifying they have a higher amount of control over the robotics console, as well as some messages showing the current status of robots, whether they are under its control or out of its control as well as toggle the hacked status on its robots.
- **Malfunctioning robots can toggle their underlings' hacked status.** That means you can disarm the robot of the emagged module as well as leave it open to being affected by the robotics console.
- **Slight typo fix for the security code reset ability.**
- **Cleaned up the robotics code a little bit.**

To-do: Find a way to balance the fact that the rogue robots are harder to kill without the console. 
To-do: Clean up a little bit.
To-do: Add emagged defines for standard emagging and malf borg emagging
To-do: Fix traitor robots being easy to check against because there were two conflicting ideas that haven't been addressed in the timespans that I wrote their code

Code review appreciated.
I'm kinda proud of this PR, though I'm worried it's getting too much stuff because one thing led to another and...

:cl:
 * rscadd: Malfunctioning AIs can now take control of robots that aren't rogue or already under the control of a malfunctioning AI.
 * rscadd: Traitor robots now spawn with the ability to disconnect from the AI network, making them invisible on the robotics console and unlocking their illegal module.
 * tweak: Subverted robots can no longer be blown up or locked down. 
 * spellcheck: Cleaned up the traitor robot's ability description a bit.

### CODE REVIEW

**Comment by ghost** [comment]
Why not. tbh we can trade a slew of AI improvements for removing the AI's ability to just plasma flood for free and that's gucchi to me

**Comment by boy2mantwicethefam** [comment]
By the way, tell me if I forgot to mention something

**Comment by bthomas2** [comment]
this is going to make game balance weird, but interesting

**Comment by DrSnips** [comment]
Not a fan of borgs being removed from the robo console. This sounds like a bad idea.

**Comment by boy2mantwicethefam** [comment]
That's why I want to balance it but I'm not sure how yet, I can't just ship "lol u cant do anything against malf borgs invasion tough luck" and it not be a terrible choice, but I'm not sure how this could be balanced yet

**Comment by Caboozles** [comment]
One balance is that you can metatest hacked/malf by just locking the robots down.
Though I guess for malf AI can toggle that, but that's pretty questionable in and of itself, since effectively there's no reason to ever put them in hacked state other than to free them.

I 100% do not support subverting borgs not currently under AI control. There's an entire setup to enable that, and it shouldn't be removed.

**Comment by boy2mantwicethefam** [comment]
That's why I gave the malf AI the ability to remove the hack status on its robots, allowing them to be affected by the console
I didn't address traitor robots yet out of confusion, I will address it when I work on it, sorry about that, traitor robots will be normally affected until they use their special ability to go off the grid
What is the setup of getting control of other AI's robots? I do not know about it if there is one. I don't know what setup you're referring to that's being removed, sorry

**Comment by DamianX** [comment]
unatomic

**Comment by Caboozles** [comment]
I more mean that you can remove a borg from the AI network. Unless you can add some way of some wire fuckery. Very common to prevent tampering in case of a rogue AI.

**Comment by juanototo2** [comment]
@dylanstrategie 
You're implying that removing the AI's ability to fludd blasma instantly will even be allowed to be merged with the rest of the ideas.
With our luck, this one will go through but the followup PR to disable silicon access to atmos machinery will be downboated.

**Comment by juanototo2** [comment]
Also the only way you're going to make malf bearable without the robotics console is either giving everyone ion rifles at roundstart or making killing the AI also kill all of its slaved borgs.

**Comment by ShiftyRail** [comment]
> They may now choose to disconnect from the AI network, becoming permanently invisible on the robotics console and unlocking their emag module. They are also notified of this ability. (I tried to check if they are already granted the emag module but I just didn't find anywhere)

>given all emagged robots an emag

**Comment by boy2mantwicethefam** [comment]
Emagged module

**Comment by Kurfursten** [comment]
still wip

**Comment by FudgePucker** [comment]
Aw man when you said robot I thought you meant stuff like floor bot clean bot and medbots, not cyborgs

**Comment by boy2mantwicethefam** [comment]
I'm gonna work on this at a later point

**Pull request closed without merging**
