### PR TITLE
[Sprites] skull in-hand sprite

### PR DESCRIPTION
**Pull request by DeityLink**
skull

Alas poor chaplin

### CODE REVIEW

**Comment by Brolaire** [comment]
thats a bit big i think..

**Comment by AutismSpider** [comment]
to big mang

**Comment by PJB3005** [comment]
Funnily enough that isn't actually too big. It's a human skull.

**Comment by Intigracy** [comment]
It's slightly smaller than his head.

Perfect size.

**Comment by Imagebard** [comment]
Nothing in this game really is to scale. The problem is that its a little bigger than most in-hand items, I guess.

**Comment by clusterfack** [comment]
Alas poor yorick

**Comment by DeityLink** [comment]
@Imagebard I don't think that's a real problem. The point of adding that sprite was so people can parody Shakespear properly, and it would look infinitely better like this than if we had to sacrifice details to make it smaller.

Plus I mean come on, we're literally right now celebrating the 400 years since his death, there's no rule set in stone saying that in-hand items have to be smaller, all they need is to have a credible size.
But if it bothers you, I can make the skull's on-floor sprite bigger, although that seems completely pointless to me.

**Comment by Imagebard** [comment]
>I can make the skull's on-floor sprite bigger

That would just make the case even worse, you're actually trying to make a item to-scale when no such thing has ever existed.

**Comment by DeityLink** [comment]
What are you talking about? Most helmet/hat sprites look much bigger on the floor, and to scale when worn. **Here the skull looks already small when on the floor.**

**Comment by ihadtoregisterforthis** [comment]
Why not use the same that's on the trophy rack?

**Comment by DeityLink** [comment]
Because the trophy rack is supposed to hold no less than 3 skulls at once. And they had to be reduced in size to have all 3 fit there. But they don't look nearly as good as the fully sized one for obvious reasons.

**Comment by Brolaire** [comment]
is it possible to reduce the sprite size by 1px in vertical direction? like, i think if you remove the row above or below the nose hole it'd be perfect in size while still being detailed

**Comment by ihadtoregisterforthis** [comment]
I still think they look too large, compare it to a regular human head.

**Comment by Brolaire** [comment]
have you tried my suggestion? its basically a skull without the lower jaw in height if you remove 1px

**Comment by DeityLink** [comment]
skullfaced

@Brolaire it's already meant to look like a skull without a lower jaw

**Comment by DeityLink** [comment]
redone the sideway sprites

side

**Comment by Zth--** [comment]
really nice

**Pull request merged**
