### PR TITLE
Make MindSwap not crash people

### LINKED ISSUE #26423: mindswap crashing both parties and sending the wiz back to the lobby
#### Description of issue
wiz has mindswap (from a bundle)
wiz uses mindswap
wiz and the guy he's mindswapping both crash
the spell WORKS in that the other guy got mindswapped, but the wiz got sent back to the lobby as a new_player except he wasn't actually in the lobby system. he didn't get the lobby menu and he couldn't see the splash screen

additionally, we got a warning log about them having the same ID and CID. @ShiftyRail probably has some info about why that happens

#### Difference between expected and actual behavior
expected it to not send the wiz into lobby limbo or make me think someone's multikeying

#### Steps to reproduce
not actually sure, it doesn't always happen and I can't see any special conditions here (cause I didn't see it happen)

#### Server revision

c2562b7093b28fac6538e1b082b281e7874a4cf2

### PR DESCRIPTION
**Pull request by ShiftyRail**
Fixes #26423 (hopefully). I originally wanted to rework the way spells are given to make more use of our mind transfer procs and potentially fix a few mind swap abuses but it would cause a lot of hassle for other cases (genetic powers not transfered, etc), so I decided not to.

### CODE REVIEW

**Comment by Exxion** [comment]
The second dummy seems pretty superfluous, since even with just the one there's no point when you're transferring a mind into a mob that hasn't had its mind transferred out yet
Make sure that works and is necessary

**Comment by ShiftyRail** [comment]
It works, for sure.  Necessary is harder to say, since I can't reproduce the original issue on live.

My argument for using two dummies is that we have never observed crashes for a mob with a client to a clientless mob. I just want to make sure the clients were transferred to dummies (safe) BEFORE making the transfer from one mob to the other. 

At best, it fixes the issue. At worst, the transfer fails but the mob was already transferred to a `/mob/living/`, so it shouldn't cause a CTD.

**Comment by Exxion** [comment]
The mobs are already clientless when being transferred to even with only one dummy, though

**Comment by Kurfursten** [comment]
Since crashing is pretty bad, let's merge this to see if it resolves the problem, and we can work on it from there

**Pull request merged**
