### PR TITLE
Prevents eavesdropping on Syndicates #13681

### PR DESCRIPTION
**Pull request by mtpowell**
Performs a check on the entered frequency, if it's the Syndicate frequency, informs the user it's encrypted.

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
This is a really bad solution. We should just put a low cap on the frequency range of the machines instead, and make sure sec radio and such is in that low range too.

**Comment by PJB3005** [comment]
Also a frequency being encrypted is not how frequencies work.

**Comment by Probe1** [comment]
But the security channel is supposed to be recorded

**Comment by mtpowell** [comment]
It's not a clean solution, but in comparison to the relative code, it fits right in 😄 

You can also encrypt radio channels, I'm not here to argue specifics, I figured I'd toss the user some sort of error instead of throwing them back at the main screen. Could always edit it to say ' Wrong encryption key.'

**Comment by PJB3005** [comment]
@Probe1 right I forgot about that, derp.

Should make this a define however.

**Comment by mtpowell** [comment]
@PJB3005 
Used an already defined const from communications.dm so it's not hardcoded and changed the flavor text

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
