### PR TITLE
New hairstyle - Half-shave

### PR DESCRIPTION
**Pull request by CodenameB**
This adds a new hairstyle for female characters - a half-shave. Get your cyberpunk on.

Requested in the thread. >>177470528

Update: Now includes manbun to address the problematic sexism in adding female hairstyle. Thank @Orangerush for helping us check our waifu privilege. 

image

image

### CODE REVIEW

**Comment by Orangerush** [comment]
wow sexist much? what about the manbun for males

**Comment by salamandooo** [comment]
Looks great, can't wait to make an edgy lesbian character

**Comment by AI-Is-Rogue** [comment]
Would use it on a male character.

**Comment by Kammerjunk** [comment]
@salamandooo I dunno, seems we're all full on edgy lesbians

**Comment by CodenameB** [comment]
Ugh, I am not happy with the manbun, but after much tweaking I still can't get it to look how it does in my head. Just gonna have to stop messing with it an upload.

**Comment by yclatious** [comment]
>edgy lesbian haircut

excuse_you_did_you_just_misgender_my_godkiller

SMT bus items when

**Comment by SonixApache** [comment]
@yclatious when you code them

**Comment by ghost** [comment]
Manbuns are trash tbh
It's the natural fedora

**Comment by jknpj** [comment]
Add the half shaven for males too

**Comment by ghost** [comment]
New hair makes me happy.

**Comment by Intigracy** [comment]
Sorry about the conflict, I'll merge this once you fix it.

**Comment by Orangerush** [comment]
@Commandersand isn't that the point??

**Comment by Exxion** [comment]
While manbuns and fedoras are both signs of dickbags, I feel that they are signs of different *kinds* of dickbags

**Pull request merged**
