### PR TITLE
Improvised defibrillator

### PR DESCRIPTION
**Pull request by Securitymain**
[content]
Someone in dchat pitched this idea a few days ago when I asked for something I could add before I get cloned. It's finished now, almost a week later
## What this does

Adds an improvised defibrillator made from 2 pie tins, cable and a any kind of cell

Stats:
- Defib delay of 90 (Real one has 30)
- Charge cost 2500
- Shocks user if they don't have insulation
- Shocks patient for minor amount of damage
- No warning messages when something goes wrong. (Instead of "try taking off their hardsuit" you just get "Nothing happens". Cables don't talk)
- Removing the cell is tricky if you don't use a screwdriver. You might just touch uninsulated pieces of cable! (If you are insulated, however..)
- Can't spam it like the real one. So no combining ultra cell + insulateds + some sort of stun to instantly husk someone!
- Doesn't fit in defib chargers, gotta replace the cell

Tell me if something else should be changed/nerfed or if this was even a good idea

## Why it's good

Gives greyshirts a way to defib their best friend after they blow up toolstorage

Video of item in use:
https://streamable.com/cvton9

grafik

## Changelog
:cl:
 * rscadd: Added improvised defibrillator: 2 pie tins, cable coil and a cell

### CODE REVIEW

**Comment by ManopolisJones** [comment]
Very nice, I've had ghetto defib in my ideas guy text document for a while now, it's just a shame the sprite is ugly as sin.

**Comment by Irradiation** [comment]
> Very nice, I've had ghetto defib in my ideas guy text document for a while now, it's just a shame the sprite is ugly as sin.

Such is the price to pay for ghetto medical tools. Don't look at ghetto splints.

**Comment by Securitymain** [comment]
The curse of coder sprites..

**Comment by Eneocho** [comment]
Can you make it also work with soda cans?

**Comment by Eneocho** [comment]
How does this interact with the emag? It is a child of the OG defib so it should have the same emag act, but it would stand to not have any (can't 'hack' a battery jury rigged to a metal sheet) or have a special one that reduces the delay or something.

**Comment by Securitymain** [comment]
it makes no sense. where would you slide an emag in

**Comment by RealestEstate** [comment]
I find the sprite quite charming

**Comment by Eneocho** [comment]
> it makes no sense. where would you slide an emag in

My point exactly. Either it doesn't get emagged at all or just handwave some bullshit like "you hook the wires from the emag (it's supposed to have a mini generator whatever on it to power the emagging process) to the improvised defibrilator's battery, charging it in the process", as it is right now, however, it would inherit the regular defib's emag behaviour, which I'm sure would cause some unexpected shit.
Also, it seems the defib uses attackby with an emag as check instead of the emag_act check.

**Comment by SonixApache** [comment]
god i hate the magic-emag afficionados
good content

**Comment by Securitymain** [comment]
your emagger concerns are unfounded, emag_act is defined for obj/machinery, not for this type of item, which is why they all use attackby emag instead

one of the many inconsistencies

**Comment by Eneocho** [comment]
> emag_act is defined for obj/machinery, not for this type of item

I swear I remember some objects, not machinery, use emag act, like the clown's soundsynth. https://github.com/vgstation-coders/vgstation13/blob/ed35b9475e616965274065701c44b15f4de825ce/code/game/objects/items/devices/sound_synth.dm#L87-L93

**Comment by SonixApache** [comment]
make your :cl: better and be sure to update the wiki once this is merged (preferably before it is merged)

**Comment by BomberBro** [comment]
The emagged defib does Fuck You levels of damage not only to you but to your heart which is almost impossible to fix without surgery, let's not make a weapon that strong even easier to get. Beyond that, holy shit we don't need more things the emag can magic into wacky weapons or tools.

**Comment by Eneocho** [comment]
It seems you are not understanding, I'm saying to either REMOVE the emag check from this ghetto defib, cause it currently inherits the check from the regular defib or rework it so it does ghetto shit. Not to buff the emagged defib. My issue is that the normal defib emag behaviour is inherited to the ghetto defib.

**Comment by Securitymain** [comment]
> 

it does not inherit the emag behavior of the defibrillator as it overwrites attackby()

and even if it also overwrites attack() which calls shock_attack or something if emagged

**Comment by Eneocho** [comment]
Good then.

**Comment by Blithering** [comment]
This is cool, but I would prefer if improvised defibrillation was just a case of opening up the chest cavity and directly stunbatoning the heart.

**Pull request merged**
