### PR TITLE
Removed a bunch of references to src in global procs

### PR DESCRIPTION
**Pull request by DamianX**
sample text

### CODE REVIEW

**Comment by ShiftyRail** [comment]
How did byond interpret that previously

**Comment by boy2mantwicethefam** [comment]
Aren't those equipment things required for location?

**Comment by ShiftyRail** [comment]
@boy2mantwicethefam no, they'll just be spawned in nullspace before being equipped.

**Comment by DamianX** [comment]
I think it's just set to null

**Pull request merged**
