### PR TITLE
Removes nikita missiles from vault until a fix is in for IEDs.

### PR DESCRIPTION
**Pull request by Probe1**

### CODE REVIEW

**Comment by SonixApache** [comment]
You can stick nikita missiles in IEDs?

**Comment by JustSumBody** [comment]
You can also stick RPG missiles in, and those DON'T break everything
most every bullet can be put in an IED as shrapnel

**Comment by SonixApache** [comment]
That's fucking great.

**Comment by N3X15** [comment]
Bot didn't bitch and since this is a quick and dirty fix for a serious server-crasher, I'll go ahead and merge this until we have something more concrete.

**Comment by ultraplen** [comment]
>not allowing missiles in IEDs 


its like you nerds HATE fun


For real though, if missiles are larger than w_class_tiny this is a one line easy fix. I´ll be able to open a PR in a few hours but if you dudes want to hot fix it before that, go to the get_projectile proc on the bullets (can't remember exactly what i called it) and add in a size check.

edit: setting shrapnel_amount = 0 on the missiles is a better fix of course

**Comment by Probe1** [comment]
Oh no we need to fix this the right way and figure out what made nikita missiles fucking go crazy.  Because something else will make them go crazy.  Was it IEDs or was it Nikita missiles?  

Or else you're just putting a bandaid on the problem and hoping it never happens again (it will).

**Comment by ultraplen** [comment]
Missiles shouldn't be launched from IEDs anyways famalam so that needs to be fixed regardless of the nikitas.

The issue could be my `launch_at()` proc thats used to launch projectiles. Perhaps the nikitas need some extra parameters set upon launch to function properly. I haven't seen the nikita code though so I really can't tell. What weapon are they supposed to be shot from even?

**Comment by Shadowmech88** [comment]
They're supposed to be shot from the Nikita missile launcher, and controlled by the shooter afterward.

**Comment by ultraplen** [comment]
Thats probably where the issue is then. Sounds like this can be resolved by giving them a custom `launch_at()` which prevents the infinite explosions and stuff.

**Pull request merged**
