### PR TITLE
Fixes SME

### LINKED ISSUE #16673: SME issues.
A recent issue has come up with the sme. A shard in an atmos of large amounts of O2 will self stimulate and flash red. This is normal until you realize that it's not cooling properly. I had a valid passive cooling set up with a mostly n2 atmos and the cooling worked as expected. Then I switched it over to the o2 atmos for the o2 stim and the shard room started to heat up dramaticly unlike in the past. Ive done this in the past without the problem about a week ago. The H.E pipes used were working properly and were slightly cooling the room but the heat rapidly shot up unlike how it was in the past where it was a manageable heat increase. This was greatly outpacing 25 H.E pipes that were space cooled and this wasnt an issue a week or so ago. I then swapped out the gas back to n2 to stop the o2 stim and the shard went back too being cooled just fine. The I filled the room with a similar amount of mols of n2 as there was o2 in the end.
Im makes me believe that the o2 stimulated state of the sme is a tad bit broken right now.

### PR DESCRIPTION
**Pull request by Exxion**
i forgot lol

Fixes #16673 

0% tested since I don't know what the SME is supposed to behave like anyway. If someone wants to test it, I can load it up on the PR test server, but I'm pretty certain that this is mathematically correct.

### CODE REVIEW

**Comment by SkowronX** [comment]
> I don't know what the SME is supposed to behave like

**Comment by Exxion** [comment]
Yes, that is, in fact, exactly what I said

**Comment by gbasood** [comment]
\>hey PJB take a look at this
\>"way ahead of you"
\>6 hours later
@PJB3005

**Comment by PJB3005** [comment]
I did look at it but yes I forgot to hit approve.

It's not like I'm all that good with atmos anyways, it's fine.

**Comment by gbasood** [comment]
>it's fine

do or die boys

**Pull request merged**
