### PR TITLE
Latejoin ling

### PR DESCRIPTION
**Pull request by adacovsk**
More atomic

:cl:
 * rscadd: Changeling can now be latejoined

### CODE REVIEW

**Comment by Eneocho** [comment]
Add a window to choose in case you don't want to be ling, like space ninja.

**Comment by adacovsk** [comment]
> Add a window to choose in case you don't want to be ling, like space ninja.

done

**Comment by DamianX** [comment]
Why don't traitors also get that option? I figured it was only for off-station antags.

**Comment by adacovsk** [comment]
> Why don't traitors also get that option? I figured it was only for off-station antags.

seems like it can be applied to any latejoiner without much issue

**Comment by DamianX** [comment]
Should it?

**Comment by SonixApache** [comment]
The original reason I added the late-join prompt was people would join as a role and be turned into an off-station antag, which they didn't expect.
I don't think non-off-station antags necessarily need it; they can just lay low if they want to muck about on-station or turn off the role if they don't want to be selected in the first place.

**Comment by adacovsk** [comment]
> The original reason I added the late-join prompt was people would join as a role and be turned into an off-station antag, which they didn't expect. I don't think non-off-station antags necessarily need it; they can just lay low if they want to muck about on-station or turn off the role if they don't want to be selected in the first place.

done

**Comment by Eneocho** [comment]
fair enough

**Comment by godietxt80** [comment]
I like it, it spreads paranoia

**Pull request merged**
