### PR TITLE
Gilded Bike Horn

### PR DESCRIPTION
**Pull request by Shadowmech88**
gilded_horn_display
Adds the gilded bike horn, an instrument that plays honking sounds. It is one of the possible items inside a randomized instrument supply crate, and can also be found in a big band supply crate.
Other than the `attack_self()` and suicide emote, the gilded bike horn has the properties of the normal bike horn.
Makes use of the bike horn soundfont distributed by aberrantkenosis.

Demo of instrument: http://puu.sh/sSrt3/1e9ee6dace.webm

:cl:
 * rscadd: Added a gilded bike horn instrument to random instrument supply crates and big band supply crates.

### CODE REVIEW

**Comment by JustSumBody** [comment]
too good for the cargo crate tbh
also nice choice in track :ok_hand:

**Comment by Exxion** [comment]
I need a Cruel Angel's Thesis instrument code thing, stat

**Comment by JustSumBody** [comment]
@Exxion I tried using the one on TG's wiki but the range for the instrument is pretty limited in the higher area, lot of notes dun werk

**Comment by FudgePucker** [comment]
Praise the honk mother
:+1:

**Comment by Probe1** [comment]
http://ss13.moe/wiki/index.php/Supply_Crates
http://ss13.moe/wiki/index.php/Piano

Update the wiki please.

**Pull request merged**
