### PR TITLE
bottles now get their overlay back

### PR DESCRIPTION
**Pull request by ghost**
Also the alpha from regular beakers and glasses is added to bottle update_icon

:cl:
* bugfix: Chemistry bottle overlay fixed

### CODE REVIEW

**Comment by ghost** [comment]
no clue how that slipped past, sorry folks

**Comment by eplgr** [comment]
No emojis are enough to express my feelings right now.

**Comment by Kurfursten** [comment]
🙌

**Comment by carshalash** [comment]
Oh, I thought my byond was just fucked. thanks fam, that shit was triggering me.

**Comment by SonixApache** [comment]
yaay

**Comment by eplgr** [comment]
I think this causes bleach bottles to have no reagent filling overlay.

**Pull request merged**
