### PR TITLE
Fixes cargo carts being able to load anchored atoms

### PR DESCRIPTION
**Pull request by jknpj**
Don't let your bugs be your features.

:cl:
 * bugfix: Fixes a cargo cart bug that allowed people to load anchored things on them.

### CODE REVIEW

**Comment by BomberBro** [comment]
Make the juke be an exception to this so we can still have music vans

**Comment by Kharkov72** [comment]
😔

**Comment by PrimeDSS13** [comment]
unironic feature

**Comment by anunknownentity03** [comment]
i want my vendor tractors to still be a thing

**Comment by gurfan** [comment]
why change it?

**Comment by SonixApache** [comment]
make an exception for vending machines 😔

**Comment by GreatBigFailure** [comment]
Make a powered version that lets you anchor things to it.

**Comment by ArchSunder** [comment]
very gay

**Comment by tuypo1** [comment]
> Make a powered version that lets you anchor things to it.

mule as well

**Comment by ArchSunder** [comment]
Only good and fun things have come from this. Either make it into a feature or leave it.

**Comment by BurntDevil** [comment]
Mobile vendors and stuff on carts are fun, why do you hate fun?

**Comment by gbasood** [comment]
Not a feature.
If things were meant to be moveable, they wouldn't be anchored. The entire point of that system is to prevent this.
If you want a music van, code it.

**Comment by gurfan** [comment]
but it's fun

**Comment by SonixApache** [comment]
bless you sood

**Comment by DamianX** [comment]
This is indeed a bug. If you want something to be able to function while on a cart, you should code it to do so instead of relying on this bug. This should be merged.

**Comment by Shadowmech88** [comment]
I'm generally a big fan of Rule of Fun, but the ability to tear literally anything off the ground with just standard Cargo equipment is game-breaking territory. There are a lot of things in the game that are balanced around not being able to move them at all/move them without special tools, and to fly in the face of that with such ease and reliability has the potential to ruin a lot of rounds.
Mobile vendors and mobile jukeboxes are both fun and harmless, yes, but people who enjoy them are free to re-add them later on purpose using code that is designed to function that way.
A few pros should not stand in the way of fixing a bug that has such a long list of cons.

**Comment by ShiftyRail** [comment]
Dammit Zth--

**Comment by PrimeDSS13** [comment]
what the hell

**Comment by ghost** [comment]
Time to readd this as a feature.

Also determining whether something is a bug vs feature is entirely a state of mind. The more gamebreaking aspect of carts is the fact of the easily purchased ZAS proof/projectile blocking vehicle and none of you can prove me wrong.

**Pull request merged**
