### PR TITLE
Stack all Sand into Sandstone with a Single Click!

### PR DESCRIPTION
**Pull request by GermanSanta**
🆑
Quality of Life Botanist Carpal Tunnel Prevention!

⚫ rscadd: Compacts all sand in hand into sandstone with a single click! Including sand underneath you as well.
      Adds to already made sandstone below you.

### CODE REVIEW

**Comment by Eneocho** [comment]
Change the changelog to the following, or similar, cause yours is not properly formatted:
:cl:
* rscadd: Crushing sand into sandstone will now turn all the sand in one click, including any sand on the floor beneath you.

**Comment by SonixApache** [comment]
wtf eneocho that's my job

**Comment by Eneocho** [comment]
image
You're too slow!

**Review by west3436 — CHANGES_REQUESTED** [review]
This doesn't seem like the best approach. Instead, I'd suggest an input box which lets you specify how many bricks you want to make given the amount of sand held in your hand rather than on your tile. If you can't implement that it's fine, but you absolutely still need to update the changelog formatting.

**Comment by GermanSanta** [comment]
No

**Comment by Dacendeth** [comment]
What if I only want to make a little.

**Comment by SonixApache** [comment]
alt is better

**Comment by west3436** [comment]
Implemented in #36766 with a more consistent approach.

**Pull request closed without merging**
