### PR TITLE
fixes some delays

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Basically when you broke out of something in less time than the delay you would still wait some more not doing anything because the delay was several seconds higher
I removed delays except for a special delay that resisting will look for so you don't spam it.
:cl:
 * bugfix: Fixed being stunned for longer than intended if you resisted out of most things in less than 10 seconds. Resisting is now generally less jankier.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Nevermind I removed the delays and just slapped a small special delay so that you don't spam much.

**Comment by MadmanMartian** [comment]
okay, so you delay special by a second, but then don't check if special is delayed?

**Comment by boy2mantwicethefam** [comment]
I already checked, special is delayed earlier, makes resist return, that's why I removed every other special check

**Comment by Kurfursten** [comment]
I guess this is getting in entirely on the opinion of @ComradeDispenser 

Should one man have THIS MUCH power??

**Pull request merged**
