### PR TITLE
New Revolution - Making Team Deatchmatch Better

### PR DESCRIPTION
**Pull request by ghost**
From the creator of Meteors 2 : Electric Boogaloo and other FUN! code experiments comes a new step in trying to make gamemodes no-one likes ~~even less liked~~ better

New features and other changes include : 
- Revolutionary Implants. Because everyone is sick and tired of magical flash conversions
- Experience a whole new level of actually having to git gud by being forced to subdue your target for long enough to stick them with a needle. Flash provided, way to shut them up ~~isn't~~ is, and it is your buddy the parapen. C4 not included
- Experience a limited supply of conversions. Every guerilla fighter is precious, and if your little clique just flies straight into Security's windshield you're fucked. gg no re (Current stock is 6 per Rev Head, so 21 Revs total. Ways to get more implants not yet included, maximum is two lockboxes with three implants and one implanter)
- Experience all the risks of actually having a brainwashing implant. Lie about your track record when you get shoved into an advanced scanner. Avoid EMP blasts like the plague, they deconvert Revolutionaries and fuck Head Revs up (sometimes, 0.3 probability per close hit, 0.05 otherwise)
- But seriously, if you are a Head Rev you better protect your shit. Being put under the scalpel or having your precious super rev implant exposed to a good old EMP will cause you to die very hard. You've been warned
- A whole new level of actually having to get your hands dirty. Instead of flashing half of the civilian crew on station and then scooting off to hide in some Maintenance locker with a stash of Library porn, you will now have to be on the ground
- You have the means of production, of revolutionaries. Just like Cultists, you can't just hope for your new converts to get more people converted. You can obviously decide to entrust someone else with your remaining implants, but then you'll have to be careful. If they're caught, the implants are toast
- A new radical mean of forcing leaders to arise. While Head Revolutionaries can tell all their fellow Revs with magical floating bubbles, regular Revolutionaries only recognize Head Revolutionaries. Now, you will have to organize the rabble, and the rabble will have to hold up on the murderboning. All the more reasons to organize and stay undercover
- Experience a new level of stress with shuttle calls. Nanotrasen's official policy about revolutionary movements is no longer to wait around doing fuck-all, but to try and recover all remaining loyal crewmen and heads. If the shuttle extracts successfully with heads, the crew wins a minor victory. Otherwise, the Revolutionaries win a minor victory. All the more reasons to guard that Shuttle Bridge until it docks
- Experience a new level of not having the round end three minutes in because the Research Director, being the only head, decided to take a trip to the Asteroid. Heads and Head Revs can now be anywhere and not automatically lose. Of course, it's a dumb thing to do for Head Revs since the crew can call the shuttle, and Heads can get the boot for extending the round for no reason (and will cause a Revolutionary Victory if they don't show up for the shuttle)
- The Chaplain is now nonconvertible. He is already devoted to god, and stuff
- If Revolution jobbans get implanted, they die. I'm not too sure about that one, but the Cult already handles this by turning them into an Artificer, aka taken out of the round
- RIP Anti-Rev and RP-Rev, we never knew ye

Word of warning concerning merge-ability, not every change could be tested. Detailed list of what was and wasn't tested and certified as working below

Shit that was tested and should work as far as I can tell : 
- Implanting, being implanted, having your implant removed via surgery or melted down via EMP along with all associated effects (conversion, deconversion, death, blacklists)
- Removing flash conversion
- Adding all items that will be used by Head Revs
- Rev icons, making sure Head Revs see everyone and Regular Revs only Head Revs
- Most fluff text

Shit that wasn't tested : 
- Victory code. Little to no changes, only shuttle victory was added (finished = 3)
- Most of the actual, technical gamemode code that can't be done by simply turning mobs into Revs (objectives, initialization, victory conditions, victory, other checks)

Discussion goes below. This isn't WIP, but changes can always be made

### CODE REVIEW

**Comment by 9600bauds** [comment]
At a glance, this just seems like a massive one-sided nerf to everything rev related rather than addressing the gamemode
Like, Cult doesn't have half of these restrictions and it's still a 30% win rate or thereof

**Comment by dylanstrategie** [comment]
Well I mean, it's kinda hard to do any meaningful changes to Rev without nerfing it

The flash conversion was the main thing that basically had to go, at least in my design but I think other people will agree. For the rest, it's mostly design experimentation

It's not like Revolution is a player favorite anyways. Once any code problems are ironed out, we can just test

**Comment by NigglyWiggly** [comment]
Hope you're ready to get shit on in the thread hard.
This all seems pretty alright, though, except maybe the no magic-rev-bubble for the non head revs thing.

Also sec running around with Ion rifles blasting people's implants apart will happen right away.

**Comment by SonixApache** [comment]
So if you just arm sec with ion guns the round is over?

**Comment by dylanstrategie** [comment]
I'm aware of the risk with EMP, but this seemed like something natural, especially since all other implants get destroyed by EMP blasts

I could make the Revolution implant immune to EMP blasts and instead harmed by things like hits to the head, but then it would be contrarian with all other implants in game

**Comment by clusterfack** [comment]
Instead of a crew minor victory can you make a king of the hill style thing.

If only head revs are on the shuttle rev minor victory
If both heads and head revs its a draw
If only heads crew minor victory
If he
If only head revs are on the shuttle rev minor victory
If both heads and head revs its a draw
If he

**Comment by dylanstrategie** [comment]
I'll look into it

**Comment by FudgePucker** [comment]
Okay some of this shit is stupid.
>Only 4 implants
>Having to implant
This is fucking stupid.
Cultists take a long time to convert, BUT THEY GET SUPER STUN AND TELEPORT POWERS.
That means unless you can make chloral, the first thing out of their mouths will be "HALP, (x) IS HED REV" over the radio.
>Chaplin can't be converted
Fucking stupid. What reason would you do this?
>Implants
Oh great, security implanting everyone wasn't bad enough, now everyone has to line up into a scanner, oh boy something you didn't think of is about to come up.
>EMP'S KILLING
WHAT FUCKING DRUGS ARE YOU ON?
NO REALLY, I WANT SOME, IT MUST BE SOME GOOD SHIT.
Security can just walk around firing the ion rifle into crowds once revs are found.
If they live they aren't revs, if they die then they were valid anyways.
>IMPLANTS
THERE ARE NOW ONLY TWO WAYS OF CONVERTING
SHUTTING OFF COMS AND THEN STUN CUFF IMPLANT
OR CHLORALING.
WHAT MADE YOU THINK THIS WAS A GOOD IDEA?
WHY NOT JUST HAVE A SPECIAL FLASH THAT HEAD REVS ONLY GET ONE OF, BURN IT OUT BY FLASHING PEOPLE TOO FAST AND YOU ARE SCREWED, IT ALSO STILL ONLY HAS A FEW USES.
THERE I JUST FUCKING SOLVED THE ISSUE.

One of the few times I won rev as a head rev was by plasma flooding and getting lucky.
These changes will just make it so that getting all the head revs into all the atmos hardsuits and then plasma flooding would be a 100 times better option than trying to convert.

The only reason revs stood a chance was by the massive tide they could throw at security, cult has, better communication, better stun options, better base options, better combat options, better pretty much everything.

**Comment by SangriaMonkey** [comment]
The EMP vulnerability will get abused like fucking crazy. And limiting the size of the revolutionary force is only going to make the ten or so people bone everyone else even harder (which is already an issue with select players). People will just rush to get loyalty implanted for them valids if this goes through and stays in rotation for long enough, *which it probably won't judging by people's reactions*.

You can't really compare it to cult. The cult has magic and talismans that make getting people to nug up and shut up less difficult. With rev you have to be quick and rely on the tide, which can't happen when you have to chloral people individually and keep them on a leash without alerting the authorities, who'll just call the shuttle and mow down anyone without an implant.

Rethink this.

**Comment by dylanstrategie** [comment]
To answer your feedback : 

* 4 implants per Head Rev isn't a final value. It's just the maximum amounts I can squeeze in a single implant lockbox. I highly consider giving the Head Revs more, but I want it to be a bit limited to force gorilla tactics
* Implanting seems natural. You're brainwashing them. That's my design idea here
* Head Revs will have to find some way to subdue their first targets until they can consider paralyzing or destroying the comms
* Chaplain answers to God. And really that's one person out of at least 25
* Mass scanning is about the same as mass implanting or mass hitting people with Bibles. Once covert ops are broken, shit happens, the crew needs to be able to do SOMETHING
* I'm considering EMPs. A solution I think would be fair is making the probabilities much, much lower to punish ion rifle spamming. Ion Rifle still toasts loyalty implants, cuts helmets and destroys electronics though, so you can't spam it willy nilly

Also Sangria, I'm distancing it from Cult. I'll consider getting your first converts, although the truth is that unless you're quick or have a trick up your sleeve, converting is hard. Maybe some sort of mute item, or straight up giving them a parapen. I'll have to think about this

**Comment by Boxe** [comment]
lmao2cult

**Comment by FudgePucker** [comment]
Just give them 2 auto injectors with chloral.
Once used up they are worthless and the trash version aren't red flags.

**Comment by dylanstrategie** [comment]
I think I'm going to give them a parapen (if it's still two charges, I need to check) or the auto-injector. If it's two charges, I highly prefer the parapen

**Comment by dylanstrategie** [comment]
Parapen also included in the above push

**Comment by Boxe** [comment]
why would they need a parapen

**Comment by dylanstrategie** [comment]
To get their first conversion

**Comment by Boxe** [comment]
why would they make someone retarded and in a coma just to convert them

**Comment by AutismSpider** [comment]
parapen bit much it gives them brain damage fitting for this game mode any way.

**Comment by Boxe** [comment]
more like fitting for the creator of this PR

**Comment by dylanstrategie** [comment]
Alright, I'll look into it again. A custom parapen should be fair enough

**Comment by SangriaMonkey** [comment]
Ouch

**Comment by AutismSpider** [comment]
dylan just use the sleepy pens and not parapen.

they can be reloaded with any chem you want and start with mix of sleep toxin and chloral

**Comment by utilitas-** [comment]
Fucking WRECKED
We should restrict Dylan from thinking of new ideas. He's clearly terrible at them. Just bug fixing and dick sucking other coders. The only proper way to fix Rev is to make it the Deathmatch mode - embrace the chaos, not try to "balance" it.

**Comment by dylanstrategie** [comment]
But, that is the sleepy pen ?

**Comment by Boxe** [comment]
iirc sleepy pen and parapen are different

**Comment by NigglyWiggly** [comment]
They are

**Comment by AutismSpider** [comment]
no way fix rev for real just rename the fucking thing to team death match or take it out for good.

Rp rev sure as hell not going work most of people here can't RP for shit

**Comment by Boxe** [comment]
just remove it and a couple other things involved with this PR

**Comment by utilitas-** [comment]
RP X mode obviously can't work for any amount of time. You should stop worrying so much about muh roleplay and embrace the team deathmatch. At least then you get to have some fun instead of worrying about other people's way of fun.

**Comment by Theophrastus1** [comment]
From my experience with anything stamped with Dylan's work on it, he needs a dedicated person to balance what he creates.

I don't think implants are the way to go, a revolution is never a long drawn out process, it's a violent, chaotic burst and forcing it to be drawn out turns it into cult lite. If you don't like the flash, instead give Head revs something like a blackjack that is a 100% knockout chance if no protective headgear is worn, and if they are wearing any you could drop it to 25% or 50%, just numbers being thrown out here, and that should give them enough time to implant the mark instead of having to make chloral or giving them a sleepypen. The sleepypen idea is stupid honestly, and it's just unfitting to knock out your target for a few minutes in order to implant them in seconds.

Instead of just trying to compare it to a different game mode, why not look at the issues it has on our station as its own mode and address those instead of blindly swinging a nerf bat around.

**Comment by AutismSpider** [comment]
you must be joking about the issure part.

let me some up rev for you.

flash people flash SOME MORE! soon more then half the station is rev with the little to no sec we have and the one or three heads we have get beat to death or ebin auto injectors with chloral and turn into monkey/head chop off.

**Comment by PJB3005** [comment]
:-1: What the shit is this dylan.

**Comment by ComicIronic** [comment]
Can you explain why these changes are necessary?

**Comment by CptWad** [comment]
I was okay with us phasing out rev.
It has always been a bad gamemode because it was just deathmatch.
It must go the way of the meteor. To only be for when admins want to prove that these gamemodes were removed for a reason.

**Comment by IratePirate** [comment]
Rev is an awful gamemode and none of these changes fix it up enough to make it worth touching with a barge pole. Put your skills to better use adding things to modes with content issues yet potential like Malf or Raiders instead of this nonsense.

**Comment by AutismSpider** [comment]
Slap dipshit who put rev back in game mode list and burn them in a fire on top of that.

**Comment by Iamgoofball** [comment]
why don't you try it out first and prove it's bad before dissing it

**Comment by AutismSpider** [comment]
He trying to make a bad game mode better. over all not going work with how people play and act here.

Better off killing rev off as a game mode here and using the implants for spy game mode etc give the dead sleepy pen some use.

**Comment by Iamgoofball** [comment]
what is wrong with trying to make a bad gamemode better

**Comment by optimumtact** [comment]
it's like an unthemed cult

**Comment by d3athrow** [comment]
seems interesting but unfeasible given the propensity of people abusing mechanics, ie ion rifles 4 everybody

**Comment by dylanstrategie** [comment]
Outside of hiding rev implants on body scanners, I could always nerf EMPs again to basically have a very low chance of destroying implants

The thing is that ion rifles cause massive damage, there's three of them, they are extremely unwieldy and can't exactly be used willy-nilly, so i think there's a balance going when a full EMP blast has a 30 % chance of deconverting

**Comment by FudgePucker** [comment]
I have been thinking about this.
The main issue with rev is no communication system and mass conversion.
Why don't we just give a way to communicate with other head revs... And remove converting.
The good things about this are, you can scale revs to security, heads of staff, and gen. station population, only people who want to be revs will be revs meaning its more like newcops with its team set up instead of someone getting converted that fucks everything up, it still retains paranoia because anybody could attack you... just not everybody, in fact a line of constant communication would make rev 10 times more dangerous.
Downside I see is it being full strength at round start due to not having to convert.

**Pull request closed without merging**
