### PR TITLE
In-hand Jumpsuit Adjustments

### PR DESCRIPTION
**Pull request by falcon2346**
## What this does
Adds a set of hand sprites for the CE's jumpsuit, which was previously using the sprites for the green jumpsuit. Also corrects the hand spites for the Anomaly, Biomech, Botany, Electrician, Engine Technician, Maintenance Technician, Mechatron, and Pharmacist jumpsuits which were previously using sprites for the opposite hand.
[consistency] [oversight] [sprites]

## Why it's good
You can now tell when someone is carrying the CE jumpsuit in their hand at a glance. Also corrects a visual error with several alt-title jumpsuits.

## Changelog
:cl:
* imageadd: Added CE jumpsuit hand sprites
* tweak: adjusted several other jumpsuits for consistency

CE jumpsuit in-hand sprites:
dreamseeker_0VwcF2pUAz
dreamseeker_mhpgWLr2Hp
dreamseeker_WmPVy5w179

### CODE REVIEW

**Comment by Eneocho** [comment]
Kinda weird that the suit is always facing the camera regardless of the direction you're facing.

**Comment by falcon2346** [comment]
> Kinda weird that the suit is always facing the camera regardless of the direction you're facing.

While I agree, it's the case for every other jumpsuit as well so I've opted to keep it consistent with the others.

**Comment by Eneocho** [comment]
> it's the case for every other jumpsuit as well so I've opted to keep it consistent with the others.

Well, for most jumpsuits it isn't that noticeable, but here it is uncomfortably noticeable.

**Comment by falcon2346** [comment]
Made some changes to make the direction the jumpsuit is facing somewhat more ambiguous by removing the line of pixels down the center, along with some other, minor changes to it.
dreamseeker_2S6qFUvNbZ
dreamseeker_bkUgNVwkB2
dreamseeker_esMocFZMBF

**Comment by Eneocho** [comment]
Ye that looks better.

**Pull request merged**
