### PR TITLE
Makes filter/mixer density 0.

### LINKED ISSUE #3703: Make gas mixer/filter density 0.

### PR DESCRIPTION
**Pull request by clusterfack**
Resolves #3703.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Nuuuuuuuuuuuu

**Comment by BestName** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/
Cum on dude, do you really want to manually close the issue?

**Comment by clusterfack** [comment]
I thought address was on that list

**Comment by PJB3005** [comment]
:+1:

**Pull request merged**
