### PR TITLE
adds a chance for runtime to spawn with her old (really old) sprite

### PR DESCRIPTION
**Pull request by nervere**
Cats don't have a 25% chance to say "Esp!" for nothing.

## Why it's good
Soul. esp

It's unclear who originally made the sprite, but KorPhaeron was the last to touch it back in 2016 so credit goes to him I guess.
## Changelog

:cl:
 * rscadd: Added a method of transforming Runtime to her old sprite using a 5u methylin syringe.

### CODE REVIEW

**Comment by cloutcode** [comment]
soul overload

**Comment by jwhitak** [comment]
Using the old sprite is powerful. I'd be fine with a full swapover. If not, doing something actively in game to cause the sprite swap. Round luck is bad. Relying on luck to see the funny cat sprite? Leave that for game mode antags, not this. 100%, 0%, or an ingame mechanic, and you get my updoot.

And I want to because the old sprite is sovl.

**Comment by SonixApache** [comment]
never seen this before, did bay cut it after their split or something?

**Comment by Kurfursten** [comment]
> Using the old sprite is powerful. I'd be fine with a full swapover. If not, doing something actively in game to cause the sprite swap. Round luck is bad. Relying on luck to see the funny cat sprite? Leave that for game mode antags, not this. 100%, 0%, or an ingame mechanic, and you get my updoot.
> 
> And I want to because the old sprite is sovl.

Maybe feeding Methylin to Runtime causes the sprite to change, as a reference to how it expands minds? I wouldn't want Runtime's current sprite to go away entirely because I have grown attached to it over the last decade.

**Comment by githubuser4141** [comment]
> Using the old sprite is powerful. I'd be fine with a full swapover. If not, doing something actively in game to cause the sprite swap. Round luck is bad. Relying on luck to see the funny cat sprite? Leave that for game mode antags, not this. 100%, 0%, or an ingame mechanic, and you get my updoot.
> 
> And I want to because the old sprite is so

Or traitors could swipe an emag on Runtime to change their sprite as a funny effect? It's weird how none of the pets can be emagged, it'd be cool if Ian for example would gain the bipedal Ian sprite that I saw exactly once in TG (No idea if it's still around)

Citrus could gain an ability to walk around on all fours and carry up to one crate like a MULEbot with some other effects

**Comment by DorainGrey** [comment]
> Or traitors could swipe an emag on Runtime to change their sprite as a funny effect? It's weird how none of the pets can be emagged, it'd be cool if Ian for example would gain the bipedal Ian sprite that I saw exactly once in TG (No idea if it's still around)
> 
> Citrus could gain an ability to walk around on all fours and carry up to one crate like a MULEbot with some other effects

Emag a pet?
I've heard it all now.

Kurf's idea is good.

**Comment by Pastamadness** [comment]
Super gay. Go back.

**Comment by Inorien** [comment]
why not just turn it into a fuckin eevee or epson or whatever pomf likes

**Comment by pedr69** [comment]
>Or traitors could swipe an emag on Runtime

EMAGGABLE SNOWBALLS WHEN??

**Comment by nervere** [comment]
> > Using the old sprite is powerful. I'd be fine with a full swapover. If not, doing something actively in game to cause the sprite swap. Round luck is bad. Relying on luck to see the funny cat sprite? Leave that for game mode antags, not this. 100%, 0%, or an ingame mechanic, and you get my updoot.
> > And I want to because the old sprite is sovl.
> 
> Maybe feeding Methylin to Runtime causes the sprite to change, as a reference to how it expands minds? I wouldn't want Runtime's current sprite to go away entirely because I have grown attached to it over the last decade.

Razz suggested baking Runtime in a genetics machine to get the result. Would that be possible without being annoying to code around? How do you feel about the idea? If we find an alternative way to get the sprite that people like, I can lower the base chance that Runtime spawns with it to be much lower.

Also open to the Methylin idea, I just don't know what peoples' ideas are atm.

**Comment by BomberBro** [comment]
This should only happen with the cultify effect from an artifact or cult related business, I like the sprite but it's a little too zany and DUDE REFERENCE LMAO to be so common now that we're well past the age of blatant stuff like metroids. 

What does the inhand look like?

EDIT: >>Death sprite is just the normal one flipped 180

**Comment by shitmaper** [comment]
Using crayons on runtime should turn her into the appropriate eevelution.
But if you try to use the blue one you get instagibbed

**Comment by nervere** [comment]
> What does the inhand look like?

It's just a normal cat. I'm pulling from old sprites here, this pre-dates being able to scoop up and hold the pets.
image

**Comment by Kurfursten** [comment]
> Razz suggested baking Runtime in a genetics machine to get the result. Would that be possible without being annoying to code around? How do you feel about the idea? If we find an alternative way to get the sprite that people like, I can lower the base chance that Runtime spawns with it to be much lower.
> 
> Also open to the Methylin idea, I just don't know what peoples' ideas are atm.

The dna scanner can only take carbon types, and simple animals are not those. You can change this but it might be non-trivial since you'd need to make sure there are no unintended consequences.

**Comment by PavelCIA** [comment]
God hates Pokemon

**Comment by cloutcode** [comment]
> EDIT: >>Death sprite is just the normal one flipped 180

wait until this guy kills ian

**Comment by Eneocho** [comment]
>baking Runtime in a genetics machine to get the result. Would that be possible without being annoying to code around? How do you feel about the idea?

You're overcomplicating the thing, just have an attackby on the genetics machine that checks if you "attacked" it with Runtime, then a blurb saying that exposure to the radioactive beams on the machine triggered dormant mutations and finally just swap the icons between regular and espeon runtime. It's doesn't have the (potential) depth a full on rework to the genetics system that includes simplemobs would have, but it would take barely 10 lines to make, if that.

**Comment by ErrorsWindows** [comment]
> Or traitors could swipe an emag on Runtime to change their sprite as a funny effect? It's weird how none of the pets can be emagged, it'd be cool if Ian for example would gain the bipedal Ian sprite that I saw exactly once in TG (No idea if it's still around)
> 
> Citrus could gain an ability to walk around on all fours and carry up to one crate like a MULEbot with some other effects

bro we don't even have citrus retarded ass hubboid monkey

**Comment by calzilla1** [comment]
Have the cat changed after being blessed (holy water splash + bible whack) by the chaplain due to the amount of SOVL involved.
It'll also be that most coveted "chaplain + medbay synergy"

**Comment by tinysaturn** [comment]
Considering the source material, injecting Runtime with any kind of vaccine should cause the change instead of an lame random chance roll imo

**Comment by djkramer123** [comment]
Kurf's idea is a good one

**Comment by nervere** [comment]
I will implement Kurf's idea with the methylin, then.

**Comment by Pastamadness** [comment]
> I will implement Kurf's idea with the methylin, then.

Make it karmotrine. It's more fitting, being a silly immersion breaking and trans-friendly chemical and not instantly obtainable.
Edit: on second thought phazon salts could work too. It's another stupid chem with some basic effort needed to obtain. Plus it's already a reference to a dumb Nintendo game so it's fitting.

**Comment by nervere** [comment]
@Kurfursten I have implemented the methylin idea. Reduced base chance of sprite happening naturally from 25% -> 1%, although I can also remove that part if you'd like.

**Comment by SonixApache** [comment]
remove roundstart chance and it's golden IMO

**Comment by Kurfursten** [comment]
As a compromise to the detractors, remove the roundstart chance. I think it might just be confusing to see without explanation at roundstart as CMO anyway. I feel confident that methylin is easy enough to mix that people will have no trouble seeing the alt sprite if they want to.

Remember to add this to the wiki, maybe on the CMO page.

**Comment by nervere** [comment]
> As a compromise to the detractors, remove the roundstart chance. I think it might just be confusing to see without explanation at roundstart as CMO anyway. I feel confident that methylin is easy enough to mix that people will have no trouble seeing the alt sprite if they want to.
> 
> Remember to add this to the wiki, maybe on the CMO page.

Roundstart chance removed and a hint at this feature has been added to the CMO's wiki page.

**Pull request merged**
