### PR TITLE
Liberates Bagel

### LINKED ISSUE #19795: Bagel is ded
rest in peace
What caused the disconnect with datums?

### PR DESCRIPTION
**Pull request by ShiftyRail**
Wish I didn't have to do this.
Sad I do.

Closes #19795

:cl:
- tweak: Misc bagel improvements. Bagel now made reasonably smaller

### CODE REVIEW

**Comment by DamianX** [comment]
You didn't *have* to

**Comment by Kurfursten** [comment]
In what way does this map bagel smaller?

**Comment by Exxion** [comment]
It doesn't. Check the edit log on the OP

**Comment by SonixApache** [comment]
silly 🆑

**Comment by ShiftyRail** [comment]
@SonixApache The original was "Liberates Bagel", blame Madman

**Pull request merged**
