### PR TITLE
Machinegod cult: the revive!

### PR DESCRIPTION
**Pull request by PJB3005**
I picked up machinegod cult.

copy of the old docs & stuff [here](https://docs.google.com/document/d/14L8UkrRmIyMJRDlaWHrRGSkbxBqzUY3UxHGwQOrFcCw/edit?usp=sharing) and [here](https://docs.google.com/spreadsheets/d/17e6PByDTVZHMzcP-tpWbq8V3T-OmPFAmFbbZKv4mJOw/edit?usp=sharing) and [here](https://www.dropbox.com/s/l5pnmyhwqel2m5f/clockcult-revenants.mdown?dl=0) (last one not a copy)
old PR over at #5236

**Credits:**
- @VelardAmakar - Tons of code & lore & the idea...
- @remierichards - More code.
- @SkowronX - sprites
- @FuryMcFlurry - sprites

obviously still DNM and WIP like the old one.

### CODE REVIEW

**Comment by VelardAmakar** [comment]
godspeed

**Comment by FuryMcFlurry** [comment]
I am still on the boat for this one.

**Comment by SangriaMonkey** [comment]
rip velard
I hope this gets finished the current cult is boring as hell

**Comment by SkowronX** [comment]
ncsjehckpo1rvjxov

**Comment by FuryMcFlurry** [comment]
Added tile conversion animation 


Made in like 20 mins

**Comment by FuryMcFlurry** [comment]
clockdooropening

Clock door being worked on!

**Pull request closed without merging**
