### PR TITLE
Adds a Headline system to newscasters

### PR DESCRIPTION
**Pull request by ValkyrieSkies**
Ever feel like your articles just don't pop out enough? With this new system, you can stick a headline at the head of articles, and this headline will be announced by newscaster units too whenever you submit a new article.

news

## Changelog

:cl:
 * rscadd: Added the headline system to newscasters.
 * tweak: Some minor reformatting to the newscaster layout.

### CODE REVIEW

**Comment by ExpulsionSnooper** [comment]
comments next pls

**Comment by Eneocho** [comment]
> comments next pls

spesschan via newscasters when

**Comment by pedr69** [comment]
reminds me of that one time that the pregenerated news channels(tau ceti and whatever the other one is) had some news on them that weren't the "john smith won the lottery!"

**Comment by ValkyrieSkies** [comment]
> reminds me of that one time that the pregenerated news channels(tau ceti and whatever the other one is) had some news on them that weren't the "john smith won the lottery!"

That's one of the things that inspired this honestly - I've made posts on TCD that have just been totally ignored because everyone's desensitized to it and assumes it's just another nothing post.

**Pull request merged**
