### PR TITLE
added a thing that spawns windows and grilles for mappers

### PR DESCRIPTION
**Pull request by DamianX**
You map this bad boy in and you get a grille and windows on all sides except for the sides that connect to a tile with a bad boy of their own
~~Stolen from~~ Heavily inspired by baystation

don't spawn these after roundstart

### CODE REVIEW

**Comment by Irradiation** [comment]
What happens if I spawn one of these after roundstart? Asking for a friend.

**Comment by DamianX** [comment]
you get a useless spawner object that does nothing

**Comment by ghost** [comment]
Can you make them work their magic on New() so badmins can use them for buildmode?

**Comment by DamianX** [comment]
It's trivial to make it work like that but the selling point of these things is that they can avoid placing windows for directions adjacent to other spawners, if we do this in New() we cannot do that for obvious reasons, so I'm opting to instead only support my intended use-case. Feel free to improve on this, though.

**Pull request merged**
