### PR TITLE
Adds a random vault - space cabin and space pond

### PR DESCRIPTION
**Pull request by xpcybic**
Just a cozy little cabin next to a pond. Nothing dangerous or bloodthirsty to be found here at all.
screenshot 2016-03-19 02 45 19
A little less risk/reward than the other vaults. I just wanted to make something neat for people to look around rather than loot and leave. Briefly tested and confirmed working. (The broken icon is a smoking pipe.)

### CODE REVIEW

**Comment by ghost** [comment]
Space fishing when?

**Comment by ihadtoregisterforthis** [comment]
This would only need some shoreline.

**Comment by Probe1** [comment]
I hate getting all 2realism4u but that's pretty silly.  It's space.  It's a vacuum.  Can't it be a pond inside some walls?  Water tiles in a gasless vacuums pretty weird.

**Comment by clusterfack** [comment]
Convert it to unid's new system

**Comment by xpcybic** [comment]
Working on the rebase and also walled it in like so; two sandstone doors leading in
screenshot 2016-03-19 23 45 32

**Comment by xpcybic** [comment]
oh my fucking god how did i manage that

**Comment by xpcybic** [comment]
Ready 4 merge at present

**Pull request merged**
