### PR TITLE
Two New Tunes to Immerse You Into Suicide Mood

### PR DESCRIPTION
**Pull request by ihadtoregisterforthis**
The following are now added to the list of sad songs that can play in your immediate area after a suicide by gun:
• Only Time - Enya
• Suicide is Painless - Johnny Mandel and Mike Altman

### CODE REVIEW

**Comment by Kurfursten** [comment]
Inflating our codebase, one meg at a time.

**Comment by SonixApache** [comment]
bee to the el oh ay tee

**Comment by N3X15** [comment]
Enya's already on the list.
Quit adding fucking songs, we don't need the world's entire library of emo music to convey a fucking suicide.

**Comment by ihadtoregisterforthis** [comment]
Enya wasn't on the list though.
>bloat

Would you prefer if ported this from another codebase instead?

**Comment by Exxion** [comment]
*Resource* bloat actually *is* a thing. People have to download the resources the first time they connect, and occasionally afterwards. Adding more songs just adds more resources to download.

**Comment by Gunosaguki** [comment]
https://www.youtube.com/watch?v=pTA0DSfrGZ0 can't forget this

**Comment by ihadtoregisterforthis** [comment]
Both songs are in the jukebox already, which kills the situational setting.
And we really need the resource space for vox_reminder20 and so forth

**Pull request closed without merging**
