### PR TITLE
Fixes the eclair sprite

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
Now they're tiny and cute!

### CODE REVIEW

**Comment by gbasood** [comment]
Before/after?

**Comment by 9600bauds** [comment]
no it's a feature

**Comment by ShiggyPiggy** [comment]
>conflicts. Amazing tbqh.
Here's the after: 
eclair

**Comment by Jeroen52** [comment]
Hhehehe, the Old Empire Bar caused that.
The sprites are in the same spritebank.

2016-04-07 16:00 GMT+02:00 ShiggyPiggy <notifications@github.com>:

**Comment by Senaat1** [comment]
Please don't merge this.

**Comment by Brolaire** [comment]
hello?

**Comment by 9600bauds** [comment]
never

**Comment by Brolaire** [comment]
delete this

**Comment by Jeroen52** [comment]
@ShiggyPiggy Fix the conflicts when?

**Comment by ShiggyPiggy** [comment]
To be quite honest never or maybe later some day I dunno PR closed thanks everyone

**Pull request closed without merging**
