### PR TITLE
Cursed be the choice: A slight vampire rework

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Makes the gameplay more engaging for the vampire, gives the vampire less asspulled stuns blah blah blah
I did it because it would be fun
- Glare removed
- Enthralling thematically replaced with hypnotize, hypnotize functionality removed
- Vampires can now suck people on the spot because biting down on someone stuns them. Vampires are stunned for two seconds after stopping from sucking someone to prevent juggling . If they decide to be merciful and let their victim go, the victim won't remember being sucked, though they can remember things like a combat scenario before being sucked if that combat scenario happened
- Vampires are no longer blocked by their mask or their victim's mask when sucking blood
- A vampire's blood-sucking is visible to everyone nearby
- Heartbeat sound when vampire sucks someone
- Slight optimizations
- Some typo fixes

Todo:

- [x] A short view-over over the changes to polish things and fix stuff introduced by this change
- [ ] Testing the changes on the test server if they work
- [x] Pestering people for an audio file or two for biting people and a short heartbeat sound to be played to both the vampire and the victim because that would be cool

:cl:
 * rscadd: Vampire bites will now stun their victims, with a two-second recoil stun period for the vampire once it finishes sucking blood.
 * tweak: Vampires ignore the presence the masks, including their own, when it comes to sucking blood.
 * tweak: It is visible to everyone nearby if a vampire is sucking someone's blood.
 * rscdel: Glare and enthrall have been removed, with hypnotize replacing enthrall's role (this means enthrall is basically renamed to hypnotize, and you can't do this to blind people).
 * soundadd: Added deep heartbeat noise for vampire sucking.
 * spellcheck: Fixed a bunch of typos.

### CODE REVIEW

**Comment by Irradiation** [comment]
So instead of a cooldown and mild blood-cost based combo, you're giving vampires a on-the-tap instant melee stun that SOMEHOW people can't even know who's actively on their neck or even remember that they got sucked?

**Comment by ShiftyRail** [comment]
So rather than a spell they stun when they bite you

**Comment by DrSnips** [comment]
Even if you put the text there to "forget" who bit you there were only so many people around you before then to inflict it. I don't think that part is really going to do anything.

**Comment by boy2mantwicethefam** [comment]
What do you mean they don't know who's on their neck?
Some vampire players expressed reluctance in removing people from the round and they know it will bite them in the ass if they let people go because it may lead to the victim calling out the vampire, so here's some "RP enforcement", this is also a reference to VTMB

Instead of a glare->hypno->cuffs->remove radio->drag into dark corner->suck dance you can suck people on the spot, very good for ambushes and such. Remember that this is a single-target thing and that their multi-target ranged stun and single-target knockout have been sacrificed, could be better-coded to give the vampire a short stun after stopping to suck someone, as if they recoiled from taking their teeth out of someone. Though the question is what to do with thralling/hypnotize, as there is no longer a way to make someone shut up reliably, I'll think of that one but I am open to suggestions from the community, my current idea is to make it stun for the duration but slap a long cooldown if it fails if that doesn't already happen.

It's worth a try to rely on players for the "forget that you got sucked" part, but time will tell if it will work, I'm risking anyway.

**Comment by tuypo1** [comment]
>the victim won't remember being sucked

Yeah fuck off with that bullshit.

>Some vampire players expressed reluctance in removing people from the round

Don't design around players who sign up for antag roles but then don't want to antagonise, if you are too much of a pussy to kill turn vampire off.

**Comment by Irradiation** [comment]
If you want to be a reference to VTMB, than instantly latching on to somebody isn't a 100% chance to succeed on either the tabletop of the vidya. Since we don't have ~~skills~~ to boost your chance of combat bloodsucking, you might as well require the victim to be attacked/stunned before being able to latch on. Or if you're right behind them, but I doubt that BYOND can handle that.

**Comment by ShiftyRail** [comment]
It is not entirely unreasonable to make "forgetting" stuff a gameplay mechanic.
Gameplay being restrained by roleplay is what ghost roles and silicons are about.

While the detail of silicon policy is far from perfect, the general concept of "follow your laws" is accepted

**Comment by ShiftyRail** [comment]
It is not entirely unreasonable to make "forgetting" stuff a gameplay mechanic.
Gameplay being restrained by roleplay is what ghost roles and silicons are about.

While the detail of silicon policy is far from perfect, the general concept of "follow your laws" is accepted

**Comment by boy2mantwicethefam** [comment]
Consider that vampires that kill will still kill and the "you don't remember anything" is more of an optional thing for vampires that don't want to kill much

Some stuff with being right behind them was attempted in different changes but it's generally clunky and not worth it given movement and such

**Comment by GoodG1448** [comment]
I guess a vampire could go unknown if they wanted to remain unidentified and don't suck people dry. I don't remember if you have to remove/push your mask off to suck off people tho. This "forgot the succ" thing would be different if we had cones of vision.

Maybe add a blind target spell/distort own face or some shit and then bite stun+succ.

**Comment by Irradiation** [comment]
Birdniggere and Plasmemes can suck through helmets and mask while humans have to take off their own helmets and presumably masks to succ.

**Comment by boy2mantwicethefam** [comment]
Weirdly enough, I was actually just working on this before I read your posts. Vampire maturity will allow you to suck people's blood without taking off your mask or their mask.

**Comment by Irradiation** [comment]
Hypnotize was technically a blinding effect before this change, honk @GoodG1448

**Comment by DrSnips** [comment]
Id like to imagine they just have a type of straw to do it

**Comment by GoodG1448** [comment]
What about a spell that mimics the face of someone else for a short ammount of time to hide the vampire's real identity? People can get tested if caught, false identity could lead security to chase red herrings.

**Comment by boy2mantwicethefam** [comment]
I think that was already done by @ShiftyRail with the shapeshifting rework

**Comment by GoodG1448** [comment]
Is it roundstart spell though? I like the idea of removing stun combos and moving the face mimic skill as a starting vampire spell.

**Comment by tuypo1** [comment]
I feel like it would be easier to just remove the requirement for mask removal for all vampires.

**Comment by boy2mantwicethefam** [comment]
It's not a roundstart spell but you gain the spell at the first threshold (100 blood sucked)

I can get behind the idea of removing the mask requirements honestly

**Comment by boy2mantwicethefam** [comment]
New changes:
- Vampires no longer need to remove their mask or their victim's mask to suck blood
- Rejuvenate optimized a bit so it checks for the VAMP_HEAL power flag instead of if the vampire has 200 blood or more, no change
- Fixed a hypnotize typo introduced by this change

**Comment by ShiftyRail** [comment]
Instead of a 20 seconds stun every 3 minutes, vampires have now a 6 seconds stun every time they bite someone

20/20 PR

**Comment by boy2mantwicethefam** [comment]
I've introduced a 2-second stun for vampires after stopping from sucking someone to prevent juggling

**Comment by tuypo1** [comment]
Well now that vampires can just bite through masks there is no reason to keep that making people forget bullshit, it's not like gas masks aren't absurdly abundant.

**Comment by SonixApache** [comment]
does it still tell you who is succing you when you're asleep


\>Glare removed
could work
\>Enthralling thematically replaced with hypnotize, hypnotize functionality removed
don't rename abilities to other abilities, just delete hypno if you're gonna delete hypno
\>Vampires can now suck people on the spot because biting down on someone stuns them. 
So it's like cult, where the antag gets a free pass on your restraintment? I mean, at least they won't need to chloral / cuff people anymore, right?
\>If they decide to be merciful and let their victim go, the victim won't remember being sucked, though they can remember things like a combat scenario before being sucked if that combat scenario happened
going to be annoying to enforce but pretty good idea tbh, it's a decent attempt to solve the "guy falls out of the cryo tube and screams KAYLIE MORGAN IS THE VAMPIRE" shebang.
\>Vampires are no longer blocked by their mask or their victim's mask when sucking blood
good, dumb feature
\>A vampire's blood-sucking is visible to everyone nearby
Works well with the on-the-spot succing, can you post a screenshot? Is it visible initially, or when you walk past it?

In fact, a little webm of the heartbeat sound would be nice too. Does it play once, when you succ?

**Comment by boy2mantwicethefam** [comment]
https://raw.githubusercontent.com/vgstation-coders/vgstation13/f07be2d7c8f6f837d8233714ba6f71cd6e707e80/sound/misc/heartbeat_deep.ogg
This plays at half volume, I think there is too much bass but the community judges that. Sucking blood is visible when you walk past it as the vampire will show off a message once in a while, preferably I'd have had the victim's sprite get closer to the vampire when being sucked but sprite movement on grab is a TG thing that I'm gonna port at some point hopefully
Heartbeat sound plays every 5 seconds when sucking someone, I could tweak that if it ends up being annoying

The test server has the vampire changes, so it'd be great if anyone could test it and give feedback

**Comment by Kurfursten** [comment]
This does not look good for having support to pass

**Comment by boy2mantwicethefam** [comment]
Really enjoyed making this as I believe it's a genuine improvement to current vampire, but people don't want it because they saw that vampire stuns on bite and that's saddening

**Pull request closed without merging**
