### PR TITLE
Adds portable machine toolbox and portable dispenser toolbox subtype

### PR DESCRIPTION
**Pull request by ghost**
[gameplay]

Needs a few finishing touches and proper in-game implementation.

## What it does
This adds a portable machine toolbox item. It can be used to deploy a nonmodifiable machine to any convenient location. When deployed, there is a verb to undeploy it. Emagging it causes the machine to deploy emagged. This also adds the portable dispenser toolbox. It's a prefab version that gives you a special portable dispenser. Poot dispenser here.
## Why it's good
Interesting item. Feature creep. I don't know, busy work while I am not busy?
## Changelog

:cl:
 * rscadd: Added portable machine toolbox. It can deploy a machine quickly and conveniently.
 * rscadd: Added the portable dispenser toolbox. It can put dispenser here.

### CODE REVIEW

**Comment by pedr69** [comment]
might be a good idea to add an april fools check

**Comment by Eneocho** [comment]
pootis

**Comment by tinysaturn** [comment]
obligatory
[1486045003216.webm](https://user-images.githubusercontent.com/78547984/228617253-997125b5-0496-426f-8a57-57cd9390622e.webm)

**Comment by pedr69** [comment]
i'm working in improving this, specifically having the machine get broken into the circuit+stockparts if you get pushed over while holding it
but there's a problem, `dropped()` gets called twice when the item's actually dropped, and once when it gets `qdel`'d during deployment - i can't use that to deconstruct the machine because it happens too often
do we have a `"this item was removed from my hands"` proc?

**Comment by Exxion** [comment]
I mean it *is* removed from your hands when you put it in your backpack or pass it to another person
Maybe look into `u_equip()` though?

**Comment by pedr69** [comment]
yeah i decided to use `slipdropped()` instead
with the side effect of allowing m*ners to stash multiple 'spencers in their BOH

we don't really have an "involuntarily dropped" proc

**Comment by ghost** [comment]
> might be a good idea to add an april fools check

This will be done. The item currently isn't accessible via ordinary means.

**Comment by Eneocho** [comment]
Requesting that you have to whack it with a wrench a couple times (with the appropriate wrench sound effect) for it to deploy, rather than wrenching it normally.

**Comment by ghost** [comment]
> Requesting that you have to whack it with a wrench a couple times (with the appropriate wrench sound effect) for it to deploy, rather than wrenching it normally.

Aight.

**Comment by ghost** [comment]
I have expanded functionality. 

- The dispenser starts unanchored.  It will not work unanchored.
- Hitting it twice with a wrench anchors it. It makes a loud noise. 
- Deploying now takes five seconds.
- The undeployed now has a sprite and uses the grey toolbox in-hand.
- The deployed now has a nice sprite.

I wouldn't mind making this a chemist traitor item.

**Comment by Eneocho** [comment]
These are the wrench hitting a building sound effects, could you make it so it plays either sound when you hit it?
https://files.catbox.moe/dhbqef.wav https://files.catbox.moe/1ew81h.wav
Having this as a traitor item would be amazing, please implement it that way.
If you do implment it as a tator item, the syndicate one should use the red toolbox icon, as the syndicate colour scheme is Red. NT could get one with a blue toolbox inhand as a centcomm/adminbus item or phazon locked research (you stuff a machine WAY bigger than a toolbox into a toolbox, them's clearly phazon/bluespace magics at work).
The undeployed version could have an attackby with wrenches (1 to deploy, 2 to "build"), instead of having to use a deploy verb then wrenching.

**Comment by gurfan** [comment]
👍 
cute sprites 

As a chemist traitor item I wouldn't really see the point since chemists already have like, chemistry access.
Does it really need to be a traitor item? Would it be good as one? I'm not sure, more brainstorming needs to be done.
Either way even as just an April Fools PR I think this is a funny little addition.
Couple suggestions:
If you're trying to parody the TF2 dispenser, it should be deployed by throwing the toolbox on the ground and whacking it with a wrench, not by using it in hand.
Also more polish could be added: deploying animations, playing the tf2 wrench sound when you hit the dispenser, or shaking the dispenser visually when you whack it (just like how machines shake visually when you kick them)

Write a better PR description and changelog though.

**Comment by Eneocho** [comment]
>As a chemist traitor item I wouldn't really see the point since chemists already have like, chemistry access.
Does it really need to be a traitor item? Would it be good as one? I'm not sure, more brainstorming needs to be done.

It could have specialized buttons that directly dispense certain chemicals, instead of having to mix them yourself with proper ratios for QUICK on-the-run chemistry. (Grab the dispenser, run to a safe location, quickly build, instantly fill your bluespace beaker with lube/pacid, undeploy and refill the chem sprayer while on the run).
Or it could have an area of effect depending on what chemicals it has made and has inside. You make, for example, keloderm and piccolyn. As long as you're within X tiles of the dispenser you get constant microdoses of kelotane, dermaline and piccolyn.
The former would allow for aggresive chemistry, as you would bypass the recipes and could be done on the run. The latter would work closer to the tf2 dispenser, dispensing all the reagents it has made and has inside to the nearby user(s), which would not be that useful on the run, but would allow for last stands.

**Comment by SECBATON-GRIFFON** [comment]
some other servers have a traitor engineer sentry gun that works exactly like this

**Comment by DorainGrey** [comment]
I think this would be cool for outside april fools as well, could lock it behind high level research, trader etc.
Can think of a couple of good uses.

**Comment by ghost** [comment]
I've continued to labor on this. I'm sorry it wasn't an April Fool's joke. I will add the wrench noises later on. The new new version:
- You have to wrench the toolbox on the floor instead of wrenching the machine.
- This can now work for *any* machine.
- It can now be emagged. It will emag the machine on spawn.
- It's now an actual toolbox.

**Comment by Eneocho** [comment]
Please man, use these sounds https://files.catbox.moe/dhbqef.wav https://files.catbox.moe/1ew81h.wav for the wrench sound, it's the same sounds tf2 uses when the engineer hits the machine.

**Comment by ghost** [comment]
> Please man, use these sounds https://files.catbox.moe/dhbqef.wav https://files.catbox.moe/1ew81h.wav for the wrench sound, it's the same sounds tf2 uses when the engineer hits the machine.

I will use these noises.

**Comment by Eneocho** [comment]
Many thanks. I also have the "hitting the sentry/dispenser/teleporter with no effect" sound effect, if you want it.

**Comment by ghost** [comment]
image

**Comment by gurfan** [comment]
:(

**Comment by Eneocho** [comment]
it's so joever bros...

**Pull request closed without merging**
