### PR TITLE
Adds Brain Damage Lines for Mimes

### PR DESCRIPTION
**Pull request by Kharkov72**
Cuck.
Also I am not going to stand around as a mime to test this because I'm lazy and focusing on music stuff.

:cl:
 * rscadd: *Mimes for you to suck his dick

### CODE REVIEW

**Comment by Kurfursten** [comment]
I'm blocking this PR at it involves breaking emote rules (e.g.: using emote to talk, such as just saying me "cuck")

**Comment by Kharkov72** [comment]
we live in a society

**Comment by DamianX** [comment]
as opposed to `lifelike texture ;_;`

**Comment by Exxion** [comment]
The existing ones already break the chat rules, yeah
No fun allowed

**Comment by Kurfursten** [comment]
Appeal it to the headmins, if they say I'm wrong, I'll apologize

I don't think badness justifies more badness

**Comment by DamianX** [comment]
why do you keep working on snaxi then

**Comment by Kurfursten** [comment]
Just to be clear, we're 100% done with on-topic discussion and we're just going to dab on each other with epic burns for the rest of this PR right?

Because I've got a few for you too.

**Comment by boy2mantwicethefam** [comment]
>the entire venom dance copypasta

Please consider opening the PR

**Comment by Kammerjunk** [comment]
image
don't shoot the massager

**Comment by PrimeDSS13** [comment]
Closed before anyone could talk about it.
sad!

**Comment by Kurfursten** [comment]
If Veers is okay with it it's his call

I can't reopen this though because it was a deleted branch.

**Pull request closed without merging**
