### PR TITLE
Fixes #10069

### LINKED ISSUE #10069: Gibself does not log before gibbing
ADMIN LOG: _no key_/(Admin) used gibself.

### PR DESCRIPTION
**Pull request by ghost**
fixes #10069
and FIXES WHOEVER REMOVED PHANTOM GIBS

### CODE REVIEW

**Comment by Exxion** [comment]
As far as I can tell from the history, phantomgibs with gibself NEVER worked
Only with regular gib
And that still works

And I doubt this will work, by the way, for phantomgibs
Phantomgibs with the gib command don't do it that way, at least
It just spawns gibs if used on a ghost, rather than trying to gib the ghost

**Comment by Exxion** [comment]
Yeah no it won't work. You can't gib ghosts.
But that return that you removed was redundant anyway because calling `gib()` on a ghost just returns immediately

**Comment by Intigracy** [comment]
Like he said, phantom gibs work for gib via vv currently, but not gibself.

You're just a wrong dummy.

**Comment by ghost** [comment]
*shrug, I added them, then.

**Comment by clusterfack** [comment]
WOW NONATOMIC PR

**Comment by Probe1** [comment]
#bringbackphantomgibs

**Pull request merged**
