### PR TITLE
Context click code module

### PR DESCRIPTION
**Pull request by ComicIronic**
Added a system for contextual attack-selfing on items.
This on its own permits hooks into various uses, but the one majorly supported is buttons.
You can define inbuilt context buttons, or create attachable buttons for
other items.
The remote datum is not tied to the remote item, which is just an example of how you would implement its functionality.

Context-clicking:
- The return_clicked_id can be set to give custom IDs given an x and y
  position on the icon
- return_clicked_id_by_params does all the messy work of converting
  params into a valid x and y click for return_clicked ID
- action() can be set for custom behaviour, passed an item or not

Buttons:
- Remote datums allow the use of button devices, as well as adding them or removing them
- Buttons have an on_press functionality
- This allows you to make remotes for anything using, for example, a signaller button (space garage doors ho!)
- No truly functional buttons exist - all the current ones just play sounds, for testing purposes
- Buttons adapt to their remote - the remote passes the shape a button icon has to be, and its displacement
- New buttons follow the base shape for remotes, and then can be attached anywhere

Moved code around, split the datum into a subtype to clarify its functionality.

### CODE REVIEW

**Comment by Midaychi** [comment]
So with this you could make objects have buttons on them in hand or in world? Ie: Put three switches on the particle accelerator middle bit or have a gun with knobs, and each switch or knob can be clicked on to do something different? 

It's neat, could be used for things you don't want to use verbs or hud buttons or right click menus for, but kind of runs into the problem of pixel clicking.

**Comment by ComicIronic** [comment]
Yes.
The hope is to remove as many verbs from the player experience ingame as possible, so that more stuff is done by context clicking.

Designing to avoid pixel-hunting will obviously come into it.

**Comment by Midaychi** [comment]
Maybe like a magnifier tool?
You use the magnifier shortcut and click on a machine with buttons or switches or whatever and it takes a closeup picture of the object, pops it up in a window, and lets you click the switches/buttons?

**Comment by HoaxIT** [comment]
Been playing with this, amazing stuff :+1:

**Pull request merged**
