### PR TITLE
Russian Reintroduction (tgstation goonecode containment update)

### PR DESCRIPTION
**Pull request by CptWad**
addressing #12047
Since russains were the main focus: they have been re-added.
yes
In addition, I have bolstered the loot.
I added the maint spawners (yes the ones from deff) and 1 high risk maint spawner (the one that can spawn a powersink or a deagle)
along side that, a gun spawner
It is now worth going to this satellite
I am open to further suggestion as to what to add or subtract to this

### CODE REVIEW

**Comment by aceedex** [comment]
c-20r. Do it

**Comment by CptWad** [comment]
the gun spawner can spawn a gyro jet among other things
look over spawners.dm it has all three loot spawners next to eachother

**Comment by coldcola** [comment]
are they now able to not be cheesed? make them resistant to space and shit so one breach doesn't give you epic loot.

**Comment by icantthinkofanameritenow** [comment]
@coldcola 
The area exposed to space is significantly lowered. Only way to cheese it is to go straight through the viscerators.

**Comment by Skullyton** [comment]
We need some sorta russian mech mob for the final 'boss'

**Comment by SonixApache** [comment]
The russians are easy as fuck to fight, unlike the horrors. This would make getting some phat loot way too easy.
Do those tiles around the lasers mean space has been removed? Because that would be a massive mistake.
Add some more hostiles to the path leading into the containment (or fill the containment room with viscerators?) and maybe less to the path to the teleporter so people can get out if they feel outgunned.

**Comment by Skullyton** [comment]
Just make one side into a 'russian petting zoo' filled with bears

**Comment by NigglyWiggly** [comment]
>Completely enclosed by giant walls and stuff.
Remember when this was an abandoned telecomms satellite that just so happened to have the goonecode on it with a bunch of russkies to defend it

**Comment by CptWad** [comment]
yeah I made it less than a year ago
but it was too easy too cheese, so I agreed that it needed to be buffed to a degree

**Comment by Sprok0** [comment]
The double one-sided windows ruin simple animal pathfinding, they won't move onto a tile with one of the windows without breaking it first.

**Comment by CptWad** [comment]
\\>git didn't tell me it was conflicting for two days

man I hate map prs so fucking much. Touch one tile on a map and you make all other prs conflict

**Comment by icantthinkofanameritenow** [comment]
RIP

**Pull request closed without merging**
