### PR TITLE
Stunglove changes.

### PR DESCRIPTION
**Pull request by ComicIronic**
Stunglove code moved to Touch, all found instances of the snowflake removed.
Making stunglove modifications now multiplies the gloves' Siemens coeff, rather than adding.
Shocking someone with stungloves now shocks you as well if your gloves conduct.
Rather than applying damage manually, stungloves use the more realistic electrocution proc - because they're ghetto stuns, they aren't safe.

I know it's the freeze, but this is mainly for discussion of the changes involved.
Haven't made the gloves unhideable, but that might require refiddling the hiding code.

### CODE REVIEW

**Comment by 9600bauds** [comment]
:+1:

**Comment by Kurfursten** [comment]
If nothing else :+1: for the snowflake removal.

**Comment by Probe1** [comment]
I'm in favor of anything short of removing them entirely and reducing their effectiveness to only insulated gloves is a strong move.  If I have the choice between torching my only pair of insulated gloves with no spares left and spending the extra 10 seconds making a stunprod, I'll take a hard look at the circumstances and make a hard decision instead of instantly going to the scrubgloves.

**Comment by BestName** [comment]
What do you mean torching?
Correct me if I'm wrong but this new system multiplies the siemens coeff of the gloves by 3 and zero times three is still zero.

**Comment by Kurfursten** [comment]
@BestName is correct, this is a buff to insulated stungloves, a nerf to most stungloves, and a bigger variance range to budget insulated stungloves.

**Comment by Probe1** [comment]
I see, I did not understand the siemens coeff and mistakenly assumed it meant the opposite of what it did.  I thought it would shock the user even harder if used for normal work.  

I would remove that part @ComicIronic .  The idea in my mind is you are making a decision.  Do you need a weapon or a tool?  If I can work with scrubgloves on then I will make them every round just because I can.

**Comment by dylanstrategie** [comment]
>Changing the cell's electrocution proc

Nah thanks

It was made this way on purpose

**Comment by ComicIronic** [comment]
What was the reason, because it was making the spessman equivalent of a AA battery do 40-60 damage.

**Comment by 9600bauds** [comment]
This when

**Comment by Probe1** [comment]
apparently never.  i think it's something that should be pursued but maybe the idea changed to be more accepted

**Pull request closed without merging**
