### PR TITLE
A SERIOUS METACLUB ISSUE REPORTED BY OUR GOOD FRIEND BAUDS

### PR DESCRIPTION
**Pull request by Probe1**
Flips the monitor in the wardens office upside down by switching dir from 1 to 2.  It was originally 'upside down' facing south to give the warden the illusion that it was right side up but seeing as its next to a window and players can see it from all perspectives it just results in confusion.

image

### CODE REVIEW

**Comment by 9600bauds** [comment]
good job

**Comment by 9600bauds** [comment]
Missed chance for the title to be A SERIOUS METACLUB ISSUE REPORTED BY OUR GOOD METACLUB MEMBER BAUDS

**Comment by Probe1** [comment]
oh you're right I blew it and now it's too late.  if only you had been in the metaclub you could have messaged me with our exclusive steam friendship and told me the epic title.

**Comment by Probe1** [comment]
yeah tested works nothing else changed merge whenever (right now I have more important things to map tomorrow with meta)

**Comment by 9600bauds** [comment]
what's the worst that can happen

**Comment by Probe1** [comment]
metaclub confirmeeed

**Pull request merged**
