### PR TITLE
Give Shaft Miners their own headset with Cargo and Research channels

### LINKED ISSUE #4745: Give Miners a Science headset, or Scientists a Supply headset
More often than not there's no communication whatsoever between miners and scientists (and even less with mechanics), which is terrible for inter-departmental cooperation and leaves both ends to guess if the other is doing their job at all.

These last shifts when I played either role, I printed a station-bounced radio and abused the fact that you can listen and talk into any channel with them, purely to be able to talk to the people on the other end. It's improved the cooperation between jobs a LOT, and the quality of my job in general. Especially as Miner, because then I can check if anyone's doing R&D, make sure research is done and I'm not too early when coming back, check if the Mechanic exists and how many materials does he want, check if Robotics knows what they're doing and whether they will need phazon or not...

Maybe if Science could talk into Supply, with the rest of Cargo overhearing, they could even offer to mail the materials (I'd like to point out that there is even LESS communication between miners and Cargo than there is between miners and Science).

Ultimately, if radio privacy is a concern, maybe create a new "Mining" channel that only Miners and Scientists can hear into?

### PR DESCRIPTION
**Pull request by ghost**
Because Shaft Miners are basically serving R&D, and Quartermasters don't want to hear the Roboticist's constant bitching, we now have Mining Headsets !
- Mining Headset included. Has access to the Cargo and Science channel and has a special, distinct sprite (darker shade of brown with a small antenna)
- Added a matching encryption key while using the sprite convention
- Updated Cargo's headset to glorious Cargonia orange instead of shitty stock white
- Mining headset added to Mining lockers, on spawn on Shaft Miners and on miner corspes

Fixes #4745

Changelog included

### CODE REVIEW

**Comment by Shadowmech88** [comment]
I think it'd be better to make a separate mining channel and give both miners and Science access to it.
After all, the miners wouldn't want to hear all the chatter going on over Science, they'd just be concerned with ore requests and the like, which could be made over the mining channel.

**Comment by dylanstrategie** [comment]
I personally don't like the idea of a Mining channel. It's better for the Miners to be directly involved in Research matters, given that they will be charged with supplying R&D with what they need

**Comment by 9600bauds** [comment]
Personally agreed myself, and from my time listening into Science they don't ever talk about anything confidential anyways. Just bitching at each other about noone doing R&D and "who the fuck took the welder tank".

**Comment by ComicIronic** [comment]
I've seen miners on the Science channel often enough, it's never been an issue.

**Comment by FudgePucker** [comment]
Having access to the science channel would be a ton more better, that way you can discuss and over hear over science channel to see if someone knows how to run the telepad, that way you can have your corpse be brought back.

**Pull request merged**
