### PR TITLE
Abandoned crates can now be emagged properly

### LINKED ISSUE #25655: Emagging abandoned crates does weird things
#### Description of issue
If you emag a locked abandoned crate, you get these messages at the same time:
image
Functionally, this doesn't do anything because the crate stays locked and it says the 'chances' to defuse are the same.

If you emag a closed, but unlocked abandoned crate, you re-enable the decalock.
The decalock has the same number of 'chances' to guess it as before, and the code to unlock it is the same.

#### Difference between expected and actual behavior
Emagging a locked crate does nothing, or opened it.
Emagging an unlocked crate does nothing.

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Fixes #25655 
Using an emag on an abandoned crate is already handled by the parent, in this case what happened was that after using an emag, it went on with the proc, it afterwards checked (after having the emag used on it) if it was attacked by a multitool, it fails that check which kicks in the "else if" check that makes it return the parent's attackby. Because "locked = 0" (because of the abandoned crate's attackby), the check for the emag in the crate's attackby fails because the crate has to be locked (which it isn't, because the parent's attackby was called after the abandoned crate's attackby made locked == 0), so it goes to the "else if" check that checks whether the item is a card (which the emag is), if it's not opened and if it's not locked (all of which are true) which would make it turn locked back to 1, meaning the crate would remain locked.
Tested.
:cl:
 * bugfix: Fixed abandoned crates not being able to be busted open with an emag.

### CODE REVIEW

**Comment by FudgePucker** [comment]
It's a feature.

In all seriousness though, abandoned crates can contain the police baton, the best melee weapon you can obtain outside of admin bus due to it being an unlimited charge stun baton, your chances of opening it should not be effected because you have a mememag.

The interface for the abandoned crate is incapable with the emag or some stupid shit like that.

**Comment by boy2mantwicethefam** [comment]
you can get the police baton on roid with only a crowbar
it's also rare for it to have a police baton
and uhhhh emagging abandoned crates open is intended, it's in the code

**Comment by PavelCIA** [comment]
you can also get a infinite stun baton by just replacing the roundstart power cell in one

**Comment by SonixApache** [comment]
just replace the emag act with a message saying it doesn't work lol

**Comment by boy2mantwicethefam** [comment]
it's a bugfix not a balance change

**Comment by Kammerjunk** [comment]
not at all true

**Comment by ShiftyRail** [comment]
By the application of this tag I make everyone equally unhappy
Cold take on this : emag already serves a lot of purposes and if we consider this as a "balance" change, it's not really needed

**Comment by d3athrow** [comment]
cryptographic sequencers attack modern nanotrasen electronics and cryptography, it would make sense for older production items to be unaffected by it :^)

**Comment by PrimeDSS13** [comment]
I agree with Sonix. Instead of just removing the interaction have it say it doesn't work as a form of feedback.

**Comment by boy2mantwicethefam** [comment]
In a separate PR maybe

**Comment by Kurfursten** [comment]
Barry is 100% right that this is a bug and not opening is unintended behavior (it even acts super buggy where it unlocks and then relocks immediately).

One of you who dislikes this fix should just open a counter-PR, it's a two line change to override the emag act and instead return a message saying it doesn't work - you could literally do it from the web editor it's such a small change. We can vote on that separately - and if you're not passionate enough about your position to make a counter PR then why argue? Until then, I'm gonna push this through. If nothing else because it looks *bad* when it happens with current behavior and it needs to change one way or the other.

**Comment by Kammerjunk** [comment]
don't care about this change but "this is a bugfix" is pretty blatantly dishonest tbqh

**Comment by Kurfursten** [comment]
What I want you to do, Kammerjammer, is to grab an earlier version of this repo before this bugfix, open up your local server, and go emag an abandoned crate and see how buggy it looks. It's stupid. It gives you the unlock and relock messages simultaneously. But I guess that was intended behavior in your mind.

**Comment by Kammerjunk** [comment]
intended? no, that's why I used the word "dishonest"
if it's a "thing," as people seem to think it is, removing it under the pretense of bugfixing isn't honest

**Pull request merged**
