### PR TITLE
Flash powder flashbang

### PR DESCRIPTION
**Pull request by SonixApache**
motivation: flash powder is a pointless chem that fucking sucks -- this makes it actually have value

🆑 
 - tweak: Flash powder now works identically to flashbangs.

### CODE REVIEW

**Comment by SonixApache** [comment]
Maybe I should add some sort of minimum limit for flashpowder to flash?

**Comment by aceedex** [comment]
Why not two separate reactions?
Flash powder and bang powder

**Comment by SonixApache** [comment]
Because flashpowder already instantly flashes uselessly, and I don't want to have to make flashbangflash() and flashbangbang() procs

**Comment by aceedex** [comment]
Doing it like this though means you need to have both eye protection and ear protection to avoid eating your own bang. Nothing useless about how current flash powder works aside from free sunglasses being ez to get

Just do flashflash () flashbang ()

**Comment by SGuivenne** [comment]
Ear protection is really easy to get, its just that nobody uses it since being deaf is generally a bigger detriment for short term gain.  That said it would make you way more robust in theory.

**Comment by juanototo2** [comment]
hello Chemistry metaclub, go away

**Comment by ShiftyRail** [comment]
Since it doesn't have a lot of feedback, I'll post in the thread to see if there are any particular strong opinions about it.

**Comment by Kitfox88** [comment]
I don't think it should be as strong as an actual flashbang but having it be a smaller radius without the deafening would be cool. Maybe make some sort of ghettochem flash with a soda can or some shit.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I dislike this simply because it means I can't flash without banging anymore
I would be OK with it if the bang was a separate chemical reaction, but it would still be kinda creepy

**Comment by ShiftyRail** [comment]
There doesn't seem to be that much opinion on this so

**Comment by SonixApache** [comment]
Fun fact, you could've changed the line into `holder.my_atom.flashbangprime(FALSE)` and it wouldnt've deleted people anymore.

**Pull request merged**
