### PR TITLE
MoMMI Spaghetti fix

### LINKED ISSUE #11248: MoMMi spaghetti not working properly
(WEB REPORT BY: rattletrap REMOTE: 172.93.109.202:7777)

> Revision c8d679e1bc0bdd3f99107dfa51401c224d0d0650
> 
> General description of the issue
> Eating MoMMi spaghetti only seems to work half the time, sometimes it doesn't make you start beeping booping at all, and other times it gives you the wrong virus and you become a cyborg instead of a MoMMi.
> 
> What you expected to happen
> MoMMi spaghetti turns you into a MoMMi
> 
> What actually happened
> MoMMi spaghetti didn't work after eating it once, second time it worked except it turned me into a cyborg
> 
> Steps to reproduce if possible
> Eat MoMMi spaghetti

### PR DESCRIPTION
**Pull request by coldcola**
mommi

I had another implementation of this recommended to me but I couldn't get it working properly, this seems to work and not break anything though.

this also adds changelog update missing for #12181 - I guess I fucked something up.

this closes #11248

### CODE REVIEW

**Comment by BarneyGumball** [comment]
You're removing all the sanity checks.  You should make autist nanites their own type, not a subtype of nanites.

**Comment by coldcola** [comment]
I attempted to do that by removing the `reaction_mob()` and adding the mommi transformation to the parent's proc and had no luck.
I looked through the previous PRs that have affected this thing and I think that was how the code originally was yet has never worked. I could be and probably am wrong though.

**Comment by BarneyGumball** [comment]
Just make `/datum/reagent/nanites/autist` into `/datum/reagent/autistnanites`.  Reagents are handled via IDs so the only thing you have to do is add is the things it was inheriting from nanites (desc, colour, etc).

**Comment by coldcola** [comment]
I will do that shortly and see how it turns out.
thanks.

**Comment by BarneyGumball** [comment]
Nearly there but you need to set the reagent vars for `autistnanites` like normal nanites have, ie:

```
description = "Really autistic microscopic construction robots."
reagent_state = LIQUID
color = "#535E66" //rgb: 83, 94, 102
```

**Pull request closed without merging**
