### PR TITLE
Supply borg xenoarchaeology upgrades

### PR DESCRIPTION
**Pull request by ghost**
Two upgrade modules:

Normal
* Contains: excavation drill, depth scanner, measuring tape, core sampler
* Tech levels required: Materials 2, Engineering 4, Anomaly 2
* Materials: Iron 70,000, Glass 20,000, Uranium 2,500

Advanced
* Contains: diamond excavation drill, advanced digsite locator, anomaly locator
* Tech levels required: Materials 4, Electromagnetic 4, Engineering 5, Anomaly 4
* Materials: Iron 80,000, Glass 40,000, Uranium 5,000, Plasma 2,500, Diamond 2,500
* Requires previous upgrade

Let me know if tech levels or mat requirements should be tweaked

:cl:
 * rscadd: Supply borgs now have upgrades that let them do xenoarchaeology work, in aid of research

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for the content label, must've not known it existed

**Comment by gurfan** [comment]
How does the battery utilizer work as a borg module, can you slap a battery with it to insert it in? Also there's no reason to give the borg both the advanced locator and the regular locator.

**Comment by gurfan** [comment]
I don't expect this module to pop up that often because it already requires anomaly tech to begin with, but I'm sure someone will mention this. Doesn't giving silicons access to jobs like these kind of go against the idea of silicons being a social, subservient role?

**Comment by ghost** [comment]
> How does the battery utilizer work as a borg module, can you slap a battery with it to insert it in?

Might have to snowflake it

**Comment by jknpj** [comment]
I'd honestly drop the battery utilizer

**Comment by ghost** [comment]
> I'd honestly drop the battery utilizer

Done

**Comment by cloutcode** [comment]
> I don't expect this module to pop up that often because it already requires anomaly tech to begin with, but I'm sure someone will mention this. Doesn't giving silicons access to jobs like these kind of go against the idea of silicons being a social, subservient role?

it fucks with xenoarch

speedmerge

**Comment by DrSnips** [comment]
For what reason does this module exist?
If you require anom research to get even the base it means arch research has already been done to an extent.
If a robo wants anom research for whatever reason they would need someone else to suit up and go digging. Then see above.
Robo don't need anom research for anything besides grippers, and now this. No sane person makes them.

**Comment by ghost** [comment]
> If you require anom research to get even the base it means arch research has already been done to an extent.
> If a robo wants anom research for whatever reason they would need someone else to suit up and go digging. Then see above.
> Robo don't need anom research for anything besides grippers, and now this. No sane person makes them.

Or you could get it from trader vendors on an odd day, unlike the gripper which is specifically excluded
Might add it to the premium selection, but I dunno

**Comment by Kurfursten** [comment]
Probably never gets made, but there's nothing _wrong_ with it codewise. This was a close vote though so if it has problems it can be reverted.

That said, I find it hard to imagine this will ever even get printed.

**Pull request merged**
