### PR TITLE
Enlarges spider queen

### LINKED ISSUE #15601: you can pick up spider queens
(WEB REPORT BY: mchotnspicy REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

c4081d2d5d83627b70dab44ea823fbb9c6cc9baf
>General description of the issue

you can pick up spider queens for a few seconds.
>What you expected to happen
no picky the big boi

>What actually happened
picked that bitch up

>Steps to reproduce if possible
i managed to do it on aggro mode, dragged the queen to me when adjecent

### PR DESCRIPTION
**Pull request by unid15**
Fixes #15601

### CODE REVIEW

**Comment by MadmanMartian** [comment]
hang on a minute; Doesn't this mean you can pick up other spider subtypes too?

**Comment by unid15** [comment]
Yep, but it makes a bit more sense because they aren't xbox huge. They force themselves out of your hands anyway if they're hostile

**Comment by ultraplen** [comment]
impressively quick fix, even if its an easy one

**Comment by clusterfack** [comment]
You had a perfect chance to call this PR "embiggening spiders" and you flubbed it

**Pull request merged**
