### PR TITLE
Toggle Mute SPS sounds

### PR DESCRIPTION
**Pull request by robosperg**
Revival of #23459, now with 100% more salt

SPS units can now be muted to prevent your ears from bleeding when the clown gets a hold of 5, or 50, if the mechanics are feeling spiteful and spamstrips them off a monkeyman. Units start with sound on and unactivated units still play sounds like on live.

Tested, everything should be working as intended. (Unless something changed since original PR was made)

Special thanks to the pizza pasta man for handholding me through all of this.

:cl:
*rscadd: You can now toggle the overwatch sounds on SPS units.

### CODE REVIEW

**Comment by robosperg** [comment]
This is 100% because someone did this earlier, and the sounds kept being played despite the SPS being two rooms away 15 minutes after the stripspam stopped.

**Comment by gurfan** [comment]
never

**Comment by ShiftyRail** [comment]
Blame Celt

**Comment by SonixApache** [comment]
I THINK you need a space in your :cl:
```
* rscadd: You can now toggle the overwatch sounds on SPS units.
```` 

good change, :+1: from me

**Comment by iFlashYou** [comment]
Thats the price of having the sps

**Comment by KingofHONK** [comment]
imagine getting pranked so hard you have to go to github to cope

**Pull request closed without merging**
