### PR TITLE
Destroyed antagonist bodies no longer refund threat

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * rscdel: Destroyed antagonist bodies no longer refund Dynamic Mode threat.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
It's an okay solution to get people to keep antags in the game but all it does is just lead to antags being turned into borgs and they become part of the crew forces while giving nothing back to antags
I had fun occasionally destroying antag bodies to make more come, giving a lucky guy, ghost, or latejoiner the golden antag ticket to fuck around and do whatever with more freedom
It also has a problem where it can give more threat than it costs with autotraitor, autotraitor consumes no points but destroyed traitors still refund threat

**Comment by ShiftyRail** [comment]
An alternative way is to set the define to zero.

**Comment by DamianX** [comment]
I'd rather remove dead code on this one

**Comment by ShiftyRail** [comment]
Fair point

**Pull request merged**
