### PR TITLE
Firelock frame manipulation (construction/deconstruction)

### PR DESCRIPTION
**Pull request by imw-Oculus**
Summary:
Increases the player's ability to interact with firelocks.

Features:
- Deconstruction via welding then wrenching (as opposed to the much less available socket wrench)
- Construction of frames via stack recipe (5 metal, 5 seconds)

Testing:
- [x] Construction from metal
- [x] Deconstruction using welder wrench
- [x] Expected behavior when using fire alarms

If you have any thoughts on balance, or the change from socket wrench to wrench for deconstruction, let me know.

:cl:
 * rscadd: Firelock frame construction. Use 5 metal in hand.
 * tweak: Firelock deconstruction, weld and wrench rather than socketwrench.

### CODE REVIEW

**Comment by ghost** [comment]
Welder wrench for firelocks is a very very very bad idea, that's a major buff to atmospherics floods / depressurisation.

**Comment by Probe1** [comment]
What Celt said

**Comment by ihadtoregisterforthis** [comment]
Being able to remove them with basic tools is a buff to ZAS attacks but at the same time firelocks can be still banished by simply welding them open, even if it's reversible

**Comment by abagone** [comment]
Personally I think fire locks of pretty redundant and if someone starts a plasma fire I've been killed by fire-locks more often then they have helped because they've slowed me down as I try to get out of a burning room. 

And like ihadtoregisterforthis said 

>simply welding them open

 they're already really easy to sabotage if you want to.

**Comment by imw-Oculus** [comment]
I can add a few more required tools, would that be a happy medium?

**Comment by Aurx** [comment]
Anyone who can remove them under this system can disable them just as easily right now, since it takes the exact same first step.

**Comment by imw-Oculus** [comment]
Alternate suggestions for this implementation are welcome, of course

I'll start by making them block during construction, so it's not just one-step-to-flood.

**Comment by abagone** [comment]
What if the fire-locks were tied to the air alarms so that you would have to hack the air alarm to power down the fire-locks in the area kind of like how you have to power down an airlock (by cutting all but the bolt wire) to dismantle it? 

Like you add a new button to the air alarm or wire that turns off fire locks and lets you deconstruct them with the method above but only when they're not powered. 
Also when they're not powered they should close because they use power to stay open so people can't just sabotage the power to lock them all open.

And perhaps also remove the welding them while they're open.

And one last thing I'm pretty sure fire-locks already rely on air alarms to tell the area temperature (and if they don't they should) so why not make them more tied to the air alarms?

**Comment by ghost** [comment]
Celt, you can also just weld them while they're open. While I agree outright removal is far harder to deal with than simply unwelding, they're still both signalling that you have about 80 seconds before it hits. Deconstruction arguably takes longer than welding and emagging/bolting the station in half, exiting through med then smashing dat mf Roast button. Making them easy to replace also offsets as unlike before where well there's no sockets left Eat It, anyone can band-aid by plonking one and two windows down to buy time to go blow distro in maint with an assembly, molotovs, or fuel fire.

**Comment by Probe1** [comment]
@abagone has a good compromise with his post.  Do that.  Make the construction and deconstruction simple but require them to be unbolted by a button on the air alarm.  Obviously this is a boon to engiborg/malf but they already aren't seriously impeded by firelocks if they want to flood.

**Comment by imw-Oculus** [comment]
Sounds good to me. I'll get that up and working tomorrow.

**Comment by RaccoonBro** [comment]
Putting the ability to deconstruct the firelocks onto the air alarms would be a major buff to them, wouldn't it? Socket wrenches aren't common but restricting it to people with engineer IDs/e-mags only seems worse. A proper flood will still bypass firelocks considering each area has their own vent/scrubber.

Just requiring it to take a few more steps would probably be a better solution.

**Comment by ghost** [comment]
Welders still "deconstruct" it for for most traitor purposes if they don't want to stop at the "validmepleaseIshouldn'tbetouchingthis" panel
People building who want it gone can trivially hack air alarms
It is easier for people to hack an air alarm than it is for them to steal and break an atmos crate or an atmos tech

It's kind of an elegant solution in that it rewards knowing the wires or punishes not having glubbins by turning off the area's devices if you bungle it and can't fix it than simply being able to wrench it.

Firelock buttery is more about spreading a local where you aren't using the vents. Like from a canister, molotovs, tox storage, or the incinerator

**Comment by ringringllingling** [comment]
dude, why add more bloat?

**Comment by imw-Oculus** [comment]
Bloat?

**Pull request merged**
