### PR TITLE
Being unconscious makes you not hear sound

### PR DESCRIPTION
**Pull request by ghost**
[tweak]

Like #29098 but much better implementation.

:cl:

* tweak: Being unconscious through any means now makes sure that you don't hear anything happening around you

### CODE REVIEW

**Comment by ShiftyRail** [comment]
I don't like the idea of making the unconscious play "experience" even less interactive than it is currently.

**Comment by ghost** [comment]
> I don't like the idea of making the unconscious play "experience" even less interactive than it is currently.

Sometimes it gives metaknowledge like if a vampire is sucking your blood.

**Comment by ShiftyRail** [comment]
That should be dealt with by admins admonishing the player, like we already do with flashes of light when being unconscious.

**Comment by Kurfursten** [comment]
Not enough support

**Pull request closed without merging**
