### PR TITLE
Removes the silencer as a starting item from revsquad

### PR DESCRIPTION
**Pull request by JustSumBody**
Who thought this was a good idea

### CODE REVIEW

**Comment by SonixApache** [comment]
if one person gets the gun, and the other gets the silencer...

**Comment by TheFriggenSawbones** [comment]
@SonixApache thats TERRIBLE for A LOT of REASONS

**Comment by SonixApache** [comment]
The proper solution to this is to make it so the gun doesn't come loaded with ammo.
And give someone else a magazine.

**Comment by gbasood** [comment]
Due to the limited number of revsquaddies this idea was bad and I support this change

**Pull request merged**
