### PR TITLE
Checks Forwarded Crates on Shuttle Return Button Press

### PR DESCRIPTION
**Pull request by jwhitak**
# Something to help the new cargo techs...
image

## What this does
Adds a friendly popup warning if you are about to send the supply shuttle back when you have a cargo forwarding request that isn't properly fulfilled.

## Why it's good
This can help a newer cargo tech figure out the forwarding system a little easier, and warn a more experienced one from making an error.

The popup might annoy people who are blatantly stealing cargo forward crates, but honestly, there should be more of a punishment than just oh no you don't get your forwarding bounty after stealing a full supermatter crystal and ending the universe.

## Changelog

:cl:
 * rscadd: Adds a warning message before returning a cargo shuttle with incomplete crate forwards
 
[tested] [qol]

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
wut r u CASUL?

**Comment by WindowsErrors** [comment]
I have whipped more than one insolent cargo technician for sending back a supply shuttle without checking the inside to make sure it was empty, thereby permanently deleting hundreds of dollars worth of items

**Comment by Eneocho** [comment]
I'm troubled with this one. On the one hand, QOL for cargo techs. On the other hand, SKILL ISSUE.

**Comment by Kurfursten** [comment]
I agree with Eneocho (for once)

I wish there were a more elegant way. It's not like we put a warning on it when you open a blasma canister. Maybe what we REALLY need is a more direct and immediate punishment for someone who fucks up. That'll learn em.

**Pull request merged**
