### PR TITLE
Rewrites the fax code and stuff

### PR DESCRIPTION
**Pull request by sonime**
Makes a new admin verb, Send-Fax, which is like replying but without needing a fax to reply to.

Redoes the reply code to call SendFax() instead of hardcoding it.

Also makes faxes and prayers show up in the Special window if enabled.

### CODE REVIEW

**Comment by PJB3005** [comment]
Looks good :+1:

**Comment by sonime** [comment]
Thanks!

**Comment by ghost** [comment]
:+1:

**Comment by ririchiyo** [comment]
This doesn't belong in the box reserved specifically for adminhelps and adminPMs.

**Comment by d3athrow** [comment]
window1.msay_output seems to be for admin comms in general either admin to admin or player to admin/vice versa so I don't see an issue with merging this.

**Comment by Senaat1** [comment]
To be quite honest here Riri i think you should fuck off, this is a great idea. Prayers tend to be drowned out by other shit.

You're not even an admin, why do you get a say in this?

**Comment by TheEliminator16** [comment]
I agree with this change, as someone who is very involved with prayers. I really want this merged, I've long wanted the ability to send faxes without having received one first. MERGE WHEN

**Comment by ghost** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
@ririchiyo this is extremely important thank you

**Comment by Zth--** [comment]
:+1:

**Comment by Cisrox** [comment]
fuck off riri

**Comment by MemeFury** [comment]
fuck off, riri

**Comment by Sordine** [comment]
Fuck off riri you dumb cunt

**Comment by Imagebard** [comment]
fuck off riri

**Comment by sonime** [comment]
To be fair, Riri is not only a codermin, but a long-time contributor to our codebase. He also was the one who made the special window.

However, if you were on more and doing things, you would know how easy it is for faxes and prayers to get lost in the chat. Seeing as how it's vitally important for jobs like IAA and Chaplain to get admin backing, moving it to the special window is the only move that makes sense.

Seeing as how your code says msay.output, it's clear that the special window is meant for more than ahelps.

Also, adding a DNM simply because you don't like it is an abuse of privilege, seeing as how a controversial tag is far more befitting of what just happened. Instead, if you want to deny a change simply because you don't like it, and not because it would detriment from the admins ability to perform, maybe the TG codebase would for you better.

**Comment by ghost** [comment]
> maybe the TG codebase would for you better.

btfo

**Comment by TheEliminator16** [comment]
Agreed. Especially since pomf is onboard with this, there's no reason to not merge this. Riri is the only one who doesn't like this and he doesn't admin for the game.

**Comment by Senaat1** [comment]
To be fair, Riri hasn't coded anything that got merged since May, hasn't played the game since 2009 and hasn't ever been an actual admin that had to deal with adminhelps or prayers.

I think this is a great idea because it's incredibly easy to miss prayers in the clusterfuck of secondary spam about people adding plasma to beakers and god knows what else.

And you might think prayers don't belong in that window but i'll give it to you straight like pear cider made from 100% pears, i don't think you belong as a collaborator.

**Comment by TheEliminator16** [comment]
Holy shit this comment section is harsh as fuck

**Comment by d3athrow** [comment]
Despite riri's complaint gonna go ahead and merge this and if somehow the special tab gets clogged up i'll make another window myself.

**Comment by TheEliminator16** [comment]
B A S E D

**Comment by Senaat1** [comment]
YEAH FUCK YEAH POMF

BASED CHICKEN GOD

BAWK BAWK

**Comment by ghost** [comment]
:+1:

**Comment by Imagebard** [comment]
I told you all that Ririch was abusing his coder position
You didn't listen

**Comment by sonime** [comment]
Thank you.

**Comment by Kurfursten** [comment]
This was painful to watch.

Thanks for working on the fax code, though. Fax code is awful, I've worked with it before. :+1:

**Comment by sonime** [comment]
@pjb3005 is the one who made me make it a proc.

**Comment by ihadtoregisterforthis** [comment]
And a happy new year

**Comment by Zth--** [comment]
Happy new year!

**Comment by Senaat1** [comment]
Happy new year bro.

**Comment by sonime** [comment]
Happy new year to yall too

**Pull request merged**
