### PR TITLE
Malf Roll Adjustment

### PR DESCRIPTION
**Pull request by ghost**
Malf has rolled naturally once in the last month. It shouldn't be common to keep the novelty, but this is just absurd.
Roundstart threat requirements were like so, where each number represents a 5 player range (0-5, 5-10, 10-15, etc.)
90,90,90,90,80,70,50,30,20,10
So not only do you need 4 enemy jobs, you also need extremely high threat since we're back to lowpop. I made requirements much more likely to be met, but also reduced the weight by 1. It is now:
90,80,70,60,50,40,40,30,30,20
Additionally, required enemy jobs is now 3 at lower pops.
t. unbiased AI player
:cl:
 * rscadd: AI roll chances altered.

### CODE REVIEW

**Comment by ComradeDispenser** [comment]
What even are the AI enemies?

**Comment by SonixApache** [comment]
fix malf first
then make it more common

**Comment by ghost** [comment]
???

**Comment by SonixApache** [comment]
#23072

**Comment by agentofzog2** [comment]
Bring back traitor AI instead.

**Comment by SonixApache** [comment]
\>still busted

**Pull request merged**
