### PR TITLE
test_tiny updates

### LINKED ISSUE #16123: test_tiny lacks an account database
This matters because you can't test anything regarding the economy, getting messages like `Please wear an ID with an associated bank account.` instead.

### PR DESCRIPTION
**Pull request by DamianX**
Fixes #16123 
Adds three lights to the arrival shuttle and a table with a bunch of full chief engineer belts
Adds an account database
dreamseeker_2017-11-11_05-12-59
dreamseeker_2017-11-11_05-13-11

### CODE REVIEW

**Comment by Kurfursten** [comment]
I was just thinking the other day, it sure would be pretty handy if test_tiny came with a couple of engine options for engineering testing. Out of scope, but if the mood strikes you.

**Comment by DamianX** [comment]
I may consider making a separate map strictly for engineering, I'd rather keep test_tiny as small as possible

**Comment by PJB3005** [comment]
> as small as possible
> has a ton of asteroid tiles to slow down startup

**Comment by DamianX** [comment]
what did he mean by this
Were they placed there for a reason?

**Comment by PJB3005** [comment]
@DamianX I highly doubt it.

Asteroid tiles have horrendous startup time so it's ironic that the "needs to load fast" map uses the slowest turf in the game.

**Comment by DamianX** [comment]
Alright, don't merge this, I'll look into this

**Comment by DamianX** [comment]
Replacing the entire mining section with space tiles made no measurable difference, maybe 1s on a good run but it's hard to get precise measurements so it might just not make any difference. This is good to go as far as I'm concerned.

**Pull request merged**
