### PR TITLE
Disallow nonhumans from taking HOP HOS Captain.

### PR DESCRIPTION
**Pull request by Allspice**
Can't have no shit birds leading our glorious NanoTrasen stations, nosirree.

I was considering restricting all heads of staff from nonhumans. But only restricting implanted heads seems like an okay compromise.

### CODE REVIEW

**Comment by SonixApache** [comment]
i for one welcome our silicone overlords

**Comment by Praecordia** [comment]
make it happen

**Comment by Exxion** [comment]
I don't personally care either way, but the players *did* vote for this

**Comment by Exxion** [comment]
Also this should probably be a config option

**Comment by Allspice** [comment]
> Aren't there defines for the species names? If so: use them.
Defines for only vox plasman trees that I saw, and comments suggest that those defines are only for their unusual reagent interactions. Also the trader whitelist uses the string "Vox" like I used "Human".

**Comment by SonixApache** [comment]
:100:% tested?

**Comment by jakmak** [comment]
Yeah I feel that birds shouldn't be in the high command but should be able to be the lower heads. I feel that allowing them to be CE,RD,CMO is good and disallowing them from the big 3 HOP,HOS, and cap is a good balance between immulsions and balance and reduces the LAW 2 GAS THE CAPTAIN RACE WAR NOW! Also dis allow all non humans from captain when?

**Comment by coldcola** [comment]
>law 2 gas the captain race war now!

but that's such a good shitter test.

**Comment by coldcola** [comment]
you can latejoin as bird captain, don't know if that's intended or not.

**Comment by TheFriggenSawbones** [comment]
this is dumb as hell

**Pull request merged**
