### PR TITLE
WIP DNM New Map, Egg Station

### PR DESCRIPTION
**Pull request by AlphaBuffalo**
Lots of work to do, learning as Im going, also, if there are any ideas please share. Right now this map is just a bunch of walls and areas to go with them, but it gives a preview to what it will look like.

Currently missing:
Arrivals
Escape
Holodeck, fitness, and other minor rooms
maintenance

### CODE REVIEW

**Comment by AlphaBuffalo** [comment]
Thinking about it, it looks more like a box with curved edges than an egg...

**Comment by Kurfursten** [comment]
Post images

**Comment by Probe1** [comment]
It's a good start but it needs to be further along than this for constructive feedback.

@Kurfursten 
vgstation13_ mapseggstation dmm _-_dream_maker_2015-11-17_21-34-35

**Comment by Zth--** [comment]
That's half an egg

**Comment by AlphaBuffalo** [comment]
It is half an egg, but I was trying to figure out how to do a PR which is why I added this

**Comment by AlphaBuffalo** [comment]
update 11-17


FLOOR TILES!

**Comment by AutismSpider** [comment]
Make the station run only on super matter or the R-UST!/TEG combot on top of the solars.

**Comment by AlphaBuffalo** [comment]
Im gonna post another PR

**Pull request closed without merging**
