### PR TITLE
Adds in a new brain damage line

### PR DESCRIPTION
**Pull request by ShiftyRail**
No description available

### CODE REVIEW

**Comment by SonixApache** [comment]
not worth immortalizing

**Comment by BomberBro** [comment]
This is a line from brain damage, but this is not a brain damage line.

**Comment by DeityLink** [comment]
I like the reference but I am inclined to agree with sonix as well

**Comment by boy2mantwicethefam** [comment]
what

**Comment by ShiftyRail** [comment]
I agree with the comments

**Pull request closed without merging**
