### PR TITLE
Time agent fixes

### LINKED ISSUE #30563: Couldn't teleport to the station as time agent (Box station)
(WEB REPORT BY: redstein REMOTE: 206.221.180.138:7777)
# Revision
1aa8e6e738a1acb488b9417a7f34901da8dd8f5e

# Description
Was stuck in the time agent room for a while with no way to teleport in

# Steps to Reproduce
Be time agent
Try to go to the station without admin help
????
profit

# What you Expected
To play

# What Actually Happened
Stuck in the time cube

### LINKED ISSUE #30749: Time agent's jecties are absolutely broken.
You get the "Locate" objective, but the jectie doesn't select anything to locate so you always fail, for example.
On localhost I couldn't test any jectie, the only way I managed to get the "Extract through anomaly" jectie to fire was to manually force the broken jecties to success.

### LINKED ISSUE #30936: Time Agent Evil Twin escape doesn't work
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
cdd473d6aeebd6c859e68ddb086fd667c71a2fe0

# Description
Role description says: "Steal your doppelganger's jump charge, erase him from the timeline,
and use the jump charge to escape through the temporal anomaly before it's too late."
Using a jump charge on an anomaly does nothing
# Steps to Reproduce
Use stolen jump charge on anomaly
# What you Expected
To get teleported off the station/deleted
# What Actually Happened
Nothing

### LINKED ISSUE #31546: Time agent doesn't work (crazy I know)
(WEB REPORT BY: niftyryanyan REMOTE: 206.221.180.138:7777)
# Revision
79f6e560719c8314ad3908b2cb92ef079dc6a368

# Description
My screen is black but I still have my hud and can interact with my items
# Steps to Reproduce
Take evil time agent
game breaks
# What you Expected
for it to not be black
# What Actually Happened
my game is bugged

### LINKED ISSUE #31647: time agent doesn't link to wiki
i became a time agent and didn't see the wiki link
either i'm blind or there's no link
also too lazy to fix it myself

### PR DESCRIPTION
**Pull request by ghost**
[bugfix][gamemode][role]
image
How the "Locate" objective should really look now.
Closes #30563.
Closes #30749.
Closes #30936.
Closes #31546.
Closes #31647.

:cl:
 * bugfix: Time agent greetings now link to the wiki guide.
 * bugfix: Time agent location objectives now list their items properly instead of just saying "Locate".
 * bugfix: Time agents can also now actually locate these items.
 * bugfix: Time agent twins no longer spawn in nullspace.
 * bugfix: Time agent twins can now teleport out of the void between timelines.
 * bugfix: Time agent twins now receive their objective.
 * bugfix: Time agents can now leave through the time anomaly with a jump charge.

### CODE REVIEW

**Comment by SonixApache** [comment]
you're a legend

**Comment by Eneocho** [comment]
The original code also called for more than just the locate objective, such as the rearrange sensitive items or erase from timeline jecties, but those two didn't get called since it was broken on the locate one, can you fix those too (and add them to the jectie rotation if possible)?
Also, does this add the wiki page to the Special Roles tab on the character menu thing?

**Comment by ghost** [comment]
> The original code also called for more than just the locate objective, such as the rearrange sensitive items or erase from timeline jecties, but those two didn't get called since it was broken on the locate one, can you fix those too (and add them to the jectie rotation if possible)? Also, does this add the wiki page to the Special Roles tab on the character menu thing?

Erase from timeline is already on the objectives, I'll see about foolproofing the rearrange one before adding it.

**Comment by Eneocho** [comment]
Did you add the wiki to the special roles tab on the character selection?

**Pull request merged**
