### PR TITLE
An Attempt At Grey Random Names

### PR DESCRIPTION
**Pull request by Optimism333**
<muhimmulsions>

### I thought I'd attempt making some name lists for ayys. What I've more or less come up with is the following: ###
- Ayy hobos and random names will now have more alium sounding names (currently they just use human ones). A handful are subtle references, with a single one being a little less subtle. Some are copied from existing mobs in the game, such as: Klaatu, Barada, Nikto (Which is a reference in itself)
- I tried to avoid silly on-the-nose references and anything that sounded like the name of a static
- Ayys only have a 50% chance to have a surname

### Some Examples: ###
First Names (Male): Neelix, Iaatu, Hu'klepp, Baklet, Kypto, Quvok, Zaphod, Zuglok
First Names (Female): Neemqui, Jueqklata, Bu'kleppa, Daaqui, Llaxora, Nakxma, Adrakka
Surnames: Addrokop, Malbamynegi, Jurzonklet, Krenglvak, Neetetgan, Threpalorox

### I wanted to reflect the long period of contact that ayys have had with humans in their random names. And for those who don't care about the lore stuff, maybe you'll find some of the examples amusing. ###
- An ayy has about a 10% chance to have a humanized name. The name structure is usually an ordinary but unassuming first name, and a random noun as a surname. A food item, a location on Earth, an object... perhaps something they found interesting about Earth culture.

### Some Examples: ###
Names (Male): Ford Prefect, John Biscuit, Bill Bourbon, Joe Texas, Allen Birmingham, Igor Moscow
Names (Female): Claire Khachapuri, Anna Crisps, Hyun Bulgogi, Maria Macaroni, Paola Zacatecas

### Bonus Video: ###
https://github.com/vgstation-coders/vgstation13/assets/81007356/b21129ee-27ed-48f2-a556-2db9a2097e82

## Share Ideas Perhaps? ##
- Please discuss if you have suggestions. Feedback is always appreciated.

:cl:
 * rscadd: Grey hobos and random characters will now have more ayylium sounding names

### CODE REVIEW

**Comment by wotisjanitor** [comment]
Yes! This is how I've been naming my greys for years. This is a really great PR.

**Comment by wotisjanitor** [comment]
Neelix, lmao

**Comment by Eneocho** [comment]
Please make it so John Nanotrasen is one of the possible random humanized names. It's a regular name and a megacorp they found interesting.

**Comment by Optimism333** [comment]
Added a bunch of names based on suggestions from various sources. Almost doubled the number of humanized last names.

**Comment by BomberBro** [comment]
We need more Bort license plates in the gift shop. I repeat, we are sold out of Bort license plates.

**Comment by nervere** [comment]
John Nanotrasen is a bad meme. Johnson Lovelocker is and always will be the canon name for the CEO.

**Comment by Optimism333** [comment]
Let's just say that as an addendum to the mothership accords with Nanotrasen, ayys are not allowed to take the surname Nanotrasen for copyright reasons. Also to dispel rumors that Nanotrasen management has been infiltrated by mothership spies, which it definitely has not been.

**Pull request merged**
