### PR TITLE
Adds more fart sounds.

### PR DESCRIPTION
**Pull request by Kharkov72**
*fart

:cl:
 * soundadd: *fart

### CODE REVIEW

**Comment by plosky1** [comment]
Now this is the quality PR we've been needing

**Comment by SkowronX** [comment]
heredth pls go

**Comment by Lokiamis** [comment]
remove farts

**Comment by ShiftyRail** [comment]
But why

**Comment by Kharkov72** [comment]
I made a joke low quality pr and it had enough ups to get merged the absolute madmen

**Comment by brndd** [comment]
Add new thing... good.

Change old thing... bad.

Remove old thing? VERY bad.

**Pull request closed without merging**
