### PR TITLE
Makes steaming hot food drop from being held too long unless not feeling pain or wearing black or insulated gloves (plus ovenmitts, new glovetype)

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][tweak]

## What this does
only applies this to edible things because this would ruin any other job
image
adds oven mitts, a non-dextrous glove type found on chefs (starts in their pockets) and in kitchen crates that can handle hot food and provide 20% shock protection. (10% more than botanists, let me know if it should just be the same or thereabouts)

## Why it's good
flavor to chef job
makes people treat hot food like "hot potatoes"
plus stuff out of microwave goes below steaming in heat after a few seconds anyways, and i don't think this applies if on utensils or plates.

## How it was tested
put mitts on, holding steaming food from a microwave for a while with and without it.

## Changelog
:cl:
 * tweak: Steaming hot food now needs captain, combat or insulated gloves to be held for more than half a second if the player can feel pain, otherwise the hand takes 5 burn damage. Other gloves do not prevent this, but allow them to be held for longer and dropped with less burn damage.
 * rscadd: Adds oven mitts, a new type of glove found on chefs and in kitchen crates than can hold steaming hot food, but makes the user less dextrous when worn.

### CODE REVIEW

**Comment by jwhitak** [comment]
This is a no from me for a bunch of reasons: Touches too much stuff unatomically (such as cargo crate ordering) for a niche feature. Yellow gloves are electrically resistant, not heat resistant. Makes hot food handling troublesome in too many edge cases such as fast food. Hurts antags who want to make really hot food burn people. Using existing frameworks like burn armor is likely a better idea than current implementation. I could go on.

I strongly recommend talking to the community about your ideas before putting keys to code.

**Comment by SECBATON-GRIFFON** [comment]
> This is a no from me for a bunch of reasons: Touches too much stuff unatomically (such as cargo crate ordering) for a niche feature.

doesn't touch cargo stuff at all as far as i can tell. the kitchen crate is the one mapped in.

> Yellow gloves are electrically resistant, not heat resistant.

they seemed to be heat resistant in the code before i touched this, hence included in the title.

> Makes hot food handling troublesome in too many edge cases such as fast food.

originally this was actually going to be all reagent containers type objects but i knew it would make doing chemistry a pain so i reduced the scope to this, the job i pictured it for. but thanks for the tip about fast food.

> Hurts antags who want to make really hot food burn people.

since this has been reworked to briefly allow holding food this is now likely again

> Using existing frameworks like burn armor is likely a better idea than current implementation.

would like to know what you mean by this, (closest i could find is armor against "energy" and "laser" in clothing) wouldn't mind accounting for it too.

> I strongly recommend talking to the community about your ideas before putting keys to code.

until you mentioned the scope thing with fast food i thought this would be too minor of a thing to.

**Comment by SonixApache** [comment]
cute but this sounds like a massive pain in the ass for little gain
i already have too much shit to juggle as chef

**Comment by cloutcode** [comment]
cute glubbs

**Comment by Cartlord** [comment]
I do not want to have to fuck around even more with fast food ordered from the Cargo merch console, so this is a no from me

**Comment by jwhitak** [comment]
Now that I had time to look at it, I withdraw parts of my earlier complaint. There's already temperature frameworks in place for heat resistance, such as heat_conductivity. Which you used. Which yellow gloves have. So that whole aspect was wrong on my part.

The issue of making undocumented and unatomic changes remain. You're changing the kitchen crate on all maps to be consistent, which can be good, but is undocumented. You're changing how different crates spawn stuff in, which can be good, but is undocumented and unrelated to this PR's context.

And your biggest crime here is making a temperature-related PR...

**Comment by SECBATON-GRIFFON** [comment]
> Now that I had time to look at it, I withdraw parts of my earlier complaint. There's already temperature frameworks in place for heat resistance, such as heat_conductivity. Which you used. Which yellow gloves have. So that whole aspect was wrong on my part.
> 
> The issue of making undocumented and unatomic changes remain. You're changing the kitchen crate on all maps to be consistent, which can be good, but is undocumented. You're changing how different crates spawn stuff in, which can be good, but is undocumented and unrelated to this PR's context.
> 
> And your biggest crime here is making a temperature-related PR...

was preparing to fix these but this PR is getting unpopular as it is so i'm just closing it

**Pull request closed without merging**
