### PR TITLE
Meme disease type is now admin-only. Fungii can only appear in random dishes (take 2)

### PR DESCRIPTION
**Pull request by DamianX**
Deity is pretty sure memes alone made latejoin diseases way worse than they originally were.

:cl:
* rscdel: Meme diseases can no longer appear outside of adminbus.
* tweak: Fungii may now only appear in random dishes.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
quick speedmerge it

**Comment by bathosbathtime** [comment]
Just wait out the three day wait period. The process is a good thing, I assure you.

**Comment by SonixApache** [comment]
that was 2 days and 20 hours

i'll have your collab status for this, i guarantee it mother fucker

**Comment by DamianX** [comment]
yeah revert it
democracy has been subverted once again
appalling

**Pull request merged**
