### PR TITLE
Yoda deathgasp for april fools and clothes

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
You have to die for it to happen
:cl:
 * rscadd: Added a new deathgasp sound, only active during April Fools or if you wear roughspun robes. This will only play when you die.
 * bugfix: Fixed a bug where xenomorphs could spam screams.

### CODE REVIEW

**Comment by BomberBro** [comment]
should be a roughspun robes exclusive, April Fools is funny and all but the capacity for sound spam since you don't have to die is pretty high

**Comment by Kurfursten** [comment]
we should just put all sound-based emotes on a single cooldown instead of having a separate cooldown for each one
also this is 33% longer than it needs to be, it's silent for the last second

**Comment by boy2mantwicethefam** [comment]
@BomberBro Idea: Roughspun robes allow you to use it outside of April Fools and I add a flag that specifically checks if the deathgasp was caused by death or not

**Comment by BomberBro** [comment]
I like both, I'm not sure if the former would get public support though

**Comment by DamianX** [comment]
unatomic

**Comment by boy2mantwicethefam** [comment]
Merge it anyway

**Pull request closed without merging**
