### PR TITLE
Adds a sound toggle for SPS

### PR DESCRIPTION
**Pull request by robosperg**
SPS units can now be muted to prevent your ears from bleeding when the clown gets a hold of 5 and spamstrips them off a monkeyman. Units start with sound on and unactivated units still play sounds like on live.

Tested, everything should be working as intended.

Special thanks to the pizza pasta man for handholding me through all of this.

:cl:
 * rscadd: You can now toggle the overwatch sounds on SPS units.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Huge sec buff

**Comment by robosperg** [comment]
image

**Comment by boy2mantwicethefam** [comment]
Just remove their sound bro lol no more alerts

**Comment by robosperg** [comment]
This still gives the alerts in chat to nearby people, the only thing this touches is the sound itself

**Comment by ShiftyRail** [comment]
I still feel this completely negates the drawback of giving everyone a SPS (which I something I wish was done more often)

**Comment by iFlashYou** [comment]
If the clown manages to get 5 of them without getting his ass kicked than he deserves to earrape sec

**Comment by SonixApache** [comment]
I really don't see the point.

**Comment by ghost** [comment]
just remove SPSes bro just force sec to use a CMC like everyone else lol

**Comment by robosperg** [comment]
The emojiocracy has spoken

**Pull request closed without merging**
