### PR TITLE
Adds virologist to the list of medical jobs so crew manifests properly tag them as Medical instead of Miscellaneous

### PR DESCRIPTION
**Pull request by Probe1**
explanatory

testes tested nightly :100:%

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
What happened to the Psychiatrist and Nurse job title?

**Comment by PJB3005** [comment]
@Jeroen52 bay RP.

**Comment by Probe1** [comment]
@Jeroen52 I really don't know about Psych.  Nurse is an alt title for doctor.  That's why previously Virologist was sorted under Medical since medical doctor is there in the list I changed.

**Comment by SysadminJeroen** [comment]
@PJB3005 Would be interesting if there was a Psychiatrist that has Med+Sec/Brig access and has the job to handle mentally retarded shitters using chloral and straightjackets.

**Comment by Kurfursten** [comment]
Technically that's closer to an Orderly, and Paramedics already have that access combo

**Pull request merged**
