### PR TITLE
More chat fixes.

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes icons in chat, whoops.
Fixes links.
Sets default font to Verdana, changes line height to 1.2 (previously 1.4 which was a bit much)

Adds Wingdings and Comic Sans.

### CODE REVIEW

**Comment by Exxion** [comment]
> Adds Wingdings

Absolute madman

**Comment by SysadminJeroen** [comment]
I actually used Wingdings when IC wasn't sanitized.

**Comment by Exxion** [comment]
Yes
Then you got banned for ROGAN
You're both absolute madmen

**Comment by SysadminJeroen** [comment]
`<div id="divCheckbox" style="display: none;"><audio controls autoplay><source src="https://example.com/audio/rogan.mp3" type="audio/mpeg"></audio></div>`
Edit: lel it was invisible.

**Comment by ihadtoregisterforthis** [comment]
Selectable Comic Sans or only added?
Because that could render the disability useless.

**Comment by liltiptop** [comment]
> adds wingdings and comic sans

https://www.youtube.com/watch?v=dfyNnUgK8qE

**Comment by ihadtoregisterforthis** [comment]
[#1](https://github.com/goonstation/goonstation-2016/pull/1)

**Pull request merged**
