### PR TITLE
Fancy Pens

### PR DESCRIPTION
**Pull request by Apogee-dev**
pens

Adds two new pens: the Multi-pen and Fountain Pen. Multi-pens have the ability to cycle colors between black, blue, and red by using them in-hand, while fountain pens write in a fancy schmancy script font and are sharp enough to put an eye out! Good luck getting the blood out if you have an accident with one.

Fountain pens can be found in the IAA Office, Library, and Captain's Office, while multi-pens can be found in the IAA Office and HoP Office. Currently, map changes are limited to Boxstation to minimize conflicts. I'll probably update the other maps one at a time with pens and paperbins/folders.

:cl:
 * tweak: Slightly updated pen sprites; red and blue pens should be easier to recognize at a glance.
 * rscadd: Added Multi-Pens to the HoP and IAA Offices on Boxstation. Use them in-hand to cycle colors.
 * rscadd: Added Fountain Pens to the Library, Captain's Office, and IAA Office on Boxstation. Careful- they're sharp!
 * bugfix: Red and blue pens now write in the correct color.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can the fountain pens be used as scalpels due to the sharpness? If so, please add a chance for tox damage on fail (something something ink in the blood).

**Comment by Apogee-dev** [comment]
> 
> 
> Can the fountain pens be used as scalpels due to the sharpness? If so, please add a chance for tox damage on fail (something something ink in the blood).

Failing surgery with a pen should give the victim a random tattoo. We don't have a system for that, but it'd be funny as hell.

**Comment by DeityLink** [comment]
I'm just glad the red and blue ones can now be recognized at the glance. Have they been fixed to actually write in their associated color?

**Comment by Apogee-dev** [comment]
> 
> 
> I'm just glad the red and blue ones can now be recognized at the glance. Have they been fixed to actually write in their associated color?

Oh shit, I forgot to add that to the changelog. Yes, I fixed the issue. It was calling "color" for the text color when the color variable on pens is actually "colour".

**Comment by DeityLink** [comment]
Thank fucking god, I remember they used to work properly when I started playing in 2013 but it's been broken for literally most of the time since.

**Pull request merged**
