### PR TITLE
Fixed projectiles getting stuck in photo booths

### LINKED ISSUE #31454: Photo booths capture projectiles, which can result in !!FUN!!
#### Description of issue
image

#### Steps to reproduce
fire projectile into photobooth, sometimes at an angle to prevent bumping

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/c9d6a779d6f2fd1b4a375ec2b7ed1fe3acad710f/code/modules/paperwork/photography.dm#L756

#### Server revision
Game: 81f4042e2a3ea8abea6a0cc816a5a0dc90e8e28c 
Patches: d2d8284cefe331992a20db0f4fedb3e1b63c7713

### PR DESCRIPTION
**Pull request by DamianX**
It works but I'm not sure if this has unwanted side-effects.
Fixes #31454

### CODE REVIEW

**Comment by Exxion** [comment]
Probably a good failsafe anyway

**Comment by Exxion** [comment]
So have you tested this for those unwanted side effects? In particular with projectile penetration.

Also technically this doesn't fix the underlying issue, but it does fix the big problem it causes, and fixing the underlying issue is a pain in the ass. I'm still not sure exactly how best to handle it.
Incidentally, this also would have prevented the taser window bug from being as terrible, I think. Hence why I said it's a good failsafe to have. Might be good to log when this trips so the bugs it indicates don't go totally unnoticed, though.

**Comment by DamianX** [comment]
It seems to completely break penetration. Nothing goes through.

**Comment by Exxion** [comment]
I guess you could instead have it check in `process()` or `process_step()` if it stays in the same place for some number of iterations (while not timestopped or something). Not sure whether that number should be one or a few.

**Pull request closed without merging**
