### PR TITLE
[Cult 4 Spinoff] Holy Salts, featuring rune removal and cult base locating

### PR DESCRIPTION
**Pull request by DeityLink**
https://user-images.githubusercontent.com/7573912/120055170-9c6aa800-c034-11eb-894b-1a0c86af79de.mp4

:cl:
* rscadd: All condiment bottles can have their content spilled over the floor if they are set to transfer 10 or more units. The amount spilled depends of the transferable amount set.
* rscadd: Spilling 10 or more units of black pepper over the floor will create a cleanable mess.
* imageadd: Tweaked the icons for salt piles and pepper mills.
* rscadd: Added Holy Salts, a new reagent that can be easily produced by putting normal table salt in presence of a 5u catalyst of holy water. Just like salt, it will create cleanable piles when 10u of it are spilled over the floor.
* rscadd: When salt piles are spawned, they now emit particles when they detect the presence of cult runes (even if concealed), talismans, tomes, and most other cult paraphernelia. After a set amount of time, the runes will be destroyed, the talismans and tomes will burn, and the other objects will break and melt away. The delay is 5 minutes for regular table salt, and 20 seconds for holy salts and starts when the pile is created.
* rscadd: When a Path Entrance rune or a talisman attuned to a Path Exit rune is destroyed by a salt pile, a blood jaunt visible for a short duration will zoom toward the corresponding exit, giving the crew a hint as to the location of the Path Exit, and potentially a cult base. The jaunt will make a distinctive noise once it reaches the exit, letting any cultist near it at the time know that their base might be compromised.

### CODE REVIEW

**Comment by Blithering** [comment]
I'm not a fan of the cult base locating thing, its already hard to keep a base undetected without packing everything up and fucking off to space.

**Comment by DeityLink** [comment]
Well it's not like you get the exact position. Also if you can somehow erase the rune before the salt deletes it, it won't emit the jaunt.

**Comment by Eneocho** [comment]
>
> All condiment bottles can have their content spilled over the floor. The amount spilled depends of the transferable amount set.

The service chads nerf we weren't expecting.

**Comment by gurfan** [comment]
What happens when a salt pile is made over a concealed rune

**Comment by DeityLink** [comment]
> 
> 
> What happens when a salt pile is made over a concealed rune

The pile will emit particles, and the rune will be destroyed as if it weren't concealed.

> 
> 
> > All condiment bottles can have their content spilled over the floor. The amount spilled depends of the transferable amount set.
> 
> The service chads nerf we weren't expecting.

if people wanted to grief the chef by removing the content from the condiment bottles they could already do that by just chugging it down.

**Comment by Blithering** [comment]
>Well it's not like you get the exact position. Also if you can somehow erase the rune before the salt deletes it, it won't emit the jaunt.

But you only get the warning when its too late, and a pinpointer arrow even for a brief moment is a big deal when you're talking something this stationary.

**Comment by boy2mantwicethefam** [comment]
Shouldn't salt dissolve in holy water?

**Comment by DeityLink** [comment]
Maybe but for convenience's sake, salty holy water and holy salts will be essentially the same thing here.

**Comment by gurfan** [comment]
Cult space bases and teleporting antagonists in general are a big ass pain to fight against and giving security some clues as to where people are fucking off too is a big step in the right direction. I think that all cult-teleports should show the blood bubble briefly in order to give people a clue as to where the cultist is going but that's outside this PR.
Cult bases can be built in a minute or two if you know what you're doing, and a cult should have multiple bases to retreat to anyway. Defending a base is also part of the fun.

**Comment by DeityLink** [comment]
> I think that all cult-teleports should show the blood bubble briefly in order to give people a clue as to where the cultist is going but that's outside this PR.

Let's not get ahead of ourselves, I wouldn't go that far unless cultists could do it with a normal spell. Most bases are still gonna be on-station.

> Cult bases can be built in a minute or two if you know what you're doing, and a cult should have multiple bases to retreat to anyway.

I doubt more than 2 or 3 cult players in our playerbase can achieve that.

**Comment by Blithering** [comment]
Space bases are gay, sec shouldn't have to scour the borders of the z level for them and cultists shouldn't have to build them to avoid detection.
Maybe keep the blood pinpointer for space bases (using whatever code detects whether or not the sacrifice can spawn a bloodstone on the altar) but leave it out for ones onstation, its hard enough to keep one servicable base secret, let alone multiple.

**Comment by gurfan** [comment]
Does this make it possible to wet/lube multiple floors using condiment bottles

**Comment by DeityLink** [comment]
> 
> 
> Does this make it possible to wet/lube multiple floors using condiment bottles

well yeah it does. A possible tweak would be to have the minimum amount needed to make water or lube stick to the floor be 2u. This way you'll have to set the condiment bottle to 10u transfer, and will be able to only wet 5 tiles instead of 50.

**Comment by DeityLink** [comment]
@gurfan there, that should make it a bit harder to abuse it. At the very least it won't be more efficient than a Space Cleaner bottle refilled with lube.

**Comment by DeityLink** [comment]
> Space bases are gay, sec shouldn't have to scour the borders of the z level for them and cultists shouldn't have to build them to avoid detection.

I completely agree, but until I can provide cultists with tools that make setting up bases on station easier/faster/safer this seems to me like a reasonable middle ground, rather than completely preventing space bases altogether.

> Maybe keep the blood pinpointer for space bases (using whatever code detects whether or not the sacrifice can spawn a bloodstone on the altar) but leave it out for ones onstation, its hard enough to keep one servicable base secret, let alone multiple.

I might change it this way later, I'd like to see how the change affects rounds first.

**Comment by TGFH** [comment]
> 
> 
> > Well it's not like you get the exact position. Also if you can somehow erase the rune before the salt deletes it, it won't emit the jaunt.
> 
> But you only get the warning when its too late, and a pinpointer arrow even for a brief moment is a big deal when you're talking something this stationary.

Sounds like balance to me. Security can't talk to ghosts (by way of cult papers) or astral project to scout the entire station the way cultists can.

**Comment by PrimeDSS13** [comment]
Isn't there a way to fix this issue other than making it so the clown can't actually use his water flower with lube?
That thing is already near useless, and on a side note Gurfan mentioned to me that it'll probably fuck up lube tomatos as well.

Do condiment shakers even need a spill 1u option? What would it actually achieve in this PR/gameplay? I'm curious if changing that might work as a better fix.

**Comment by DeityLink** [comment]
> Do condiment shakers even need a spill 1u option?

That's their main reason to be, they can be used on food to inject their reagents. Originally only 1u and 50u were available, 50u being meant for clowns to grief chefs and bar visitors by "uncorking the salt shaker so they accidentally use it all at once".

The easiest way to prevent abuse without changing anything else would be to hard-code 1u not actually spilling on the floor directly on the condiment bottle. I can do that.

**Comment by DeityLink** [comment]
There we go. Reverted the change to lube, condiment bottles have to be set to at least to their new 10u setting to spill anything on the floor, otherwise you get a message telling you that the lid isn't sufficiently open or something. That should prevent the PR affecting anything else.

**Comment by Allspice** [comment]
@TGFH things work out such that sec/crew disproportionately benefits from scouting and round knowledge compared to antags. see also, scry wizards fooling around and getting shotgunned, and then the round gets sent to shit as sec grabs the orb and snuffs out every remaining antag.

as for bases, making station bases "viable" would be nice, but I also don't think spes bes deserves as much whinging as it gets, so long as the cult needs actual people (i.e. not expendable manifested ghosts) to be on-station to make progress. and I think shades take damage in space now or whatever, so they don't get to zoom out airlocks and find the base again for free.

**Comment by DeityLink** [comment]
@Allspice 

> and I think shades take damage in space now or whatever, so they don't get to zoom out airlocks and find the base again for free.

They take 1 damage per Life() tick which, if they're full HP, should be enough to reach a base by going there straight. It was mostly meant to prevent shades hanging around in space forever while breaking windows out of spite.

**Comment by TGFH** [comment]
@Allspice 
The change doesn't render bases or even space bases nonviable. It just makes it so that if cultists wish to use their free infinite teleports they either have to take steps to insulate themselves from danger, or they just have to accept that they're risking something when they use such a powerful tool.

**Comment by Allspice** [comment]
it's less a matter of this change making station bases "nonviable", and more I'm not sure that they are "viable"/practical even now, with how things usually play out. excepting setups in telescience which might turn into a cult base as a side thing, but are primarily used for teleconvert fuckery.

also, without the modification blithering suggested, this change would probably hurt station bases disproportionately to spes bes. e.g. on box, sec tries to grab someone around science, but that person telezoops away and their tele bubble points southeast.

**Comment by gurfan** [comment]
>. e.g. on box, sec tries to grab someone around science, but that person telezoops away and their tele bubble points southeast

the blood bubble hint only appears when a path entrance is destroyed by salt

**Comment by DeityLink** [comment]
Exact. Sec needs to get ahold of a path entrance, or tele-talisman. And even if they do some cultists could theoretically jump into to erase it even partially then teleport away to prevent it from revealing the position.

**Comment by Blithering** [comment]
>And even if they do some cultists could theoretically jump into to erase it even partially then teleport away to prevent it from revealing the position.

Assuming you have a guy on permanent astral so you can know these things are occurring in time to do anything about it, you really think rushing into an area sec are watching like a hawk to wait for the blood pinpointer, jumping on the rune to erase it and trying to teleport out without catching a tase just for being unimplanted in view of sec is gonna work?

It's also gonna make wraiths the "oops I fucked over the cult" role moreso than before, due to their new gimmick of making path runes without being able to conceal them. Not only is it a big red flag that there's a cult, but now every time the wraith uses one its gonna be traceable back to the base.

**Comment by DeityLink** [comment]
@Blithering I'm not saying it's something easily doable/to rely on. I don't think sec can reliably catch someone with a teleport talisman either (either they catch a cultist without talisman, or the cultist teleports before the taser takes effect)

>It's also gonna make wraiths the "oops I fucked over the cult" role moreso than before, due to their new gimmick of making path runes without being able to conceal them. 

That means you should avoid making entrances leading to the base before the cult goes loud/is large enough to afford losing a base. Path exits are still safe. And once again it's better than sec offs having to run around the Z Level's borders with a jetpack and a GPS anytime a space base appears. Either way it's all theorycrafting from this point on. Why don't we see how this feature actually affects rounds?

**Comment by Blithering** [comment]
I suppose, but again, I was mainly concerned about on-station bases.

**Comment by Kurfursten** [comment]
conflicts

**Pull request merged**
