### PR TITLE
Update Credits

### PR DESCRIPTION
**Pull request by clusterfack**
Adds some new people to the credits for their help with our codebase

### CODE REVIEW

**Comment by 9600bauds** [comment]
but i'm 9600bauds

**Comment by clusterfack** [comment]
Thats even sillier

**Comment by 9600bauds** [comment]
I am a silly man

**Comment by clusterfack** [comment]
Fixed

**Comment by Iamgoofball** [comment]
https://github.com/clusterfack/bugfixstation13/pull/3

**Comment by IratePirate** [comment]
>entire category absorbed

:^)

**Comment by clusterfack** [comment]
@IratePirate Ye now go find more delightful sounds

**Pull request merged**
