### PR TITLE
New airlock machinery sprites

### PR DESCRIPTION
**Pull request by kol1th**
# Scope of PR

Airlock machines now have new sprites. **CEV-ERIS** made them, and I made the construction step ones. 

# Feast for your Eyes
**OLD:**
image

**NEW:**
image

**IN ACTION:**
image

# Changelog

🆑 
* imgadd: Airlock machinery now has a new set of sprites!

### CODE REVIEW

**Comment by Lokiamis** [comment]
Is the difference between the new button you posted and the button next to the airlock intentional? Not sure if the bottom is being cut off, they're only one layer of yellow buttons.

**Comment by kol1th** [comment]
Different sprite 
image

**Comment by Chucklemonger** [comment]
Why?

**Comment by PJB3005** [comment]
I like the shading but the perspective change is dumb. All on wall objects have a strict front facing 2D sprite, you just ruined that.

**Comment by Exxion** [comment]
Oh, I just saw that as a lighter band around the top, not the actual top face of it

**Comment by PJB3005** [comment]
If it's supposed to be a random lighter band it's really poorly done.

**Comment by Shadowmech88** [comment]
Same here, I didn't realize it was 3D until you pointed it out.

**Comment by Riekland** [comment]
okay kolith stop
first off these sprites are awful all round and are made by a retard, either sprite them anew or don't bother
SECOND you need to have the outline be a lot closer to the rest of the sprite, it looks fucking awful right now
you must must MUST keep the outline from being too noticable
ps stop fucking porting their shit sprites, port something cool like loadouts
the old ones are shit but the solution is not replacing the dogshit with horseshit

**Comment by Exxion** [comment]
Porting loadouts is a bit more easily said than done
Porting sprites is, too, I guess, but barely

**Comment by PJB3005** [comment]
While I think @Riekland's wording is kind of hard, he's 100% right here.

These sprites are crap and even I could do a better job at them.

**Comment by kol1th** [comment]
>Keep the outline from being too noticeable

The old one is quite literally a black outline

>stop porting their shit sprites

They have good sprites though. I have better sprites for these same exact things, but people would whine and scream "IT LOOKS TOO GOOD FOR /vg/!",  so I didn't bother.

**Comment by Riekland** [comment]
did you miss the part where I said just because we have shit sprites right now doesn't mean we can replace them with things that are just as shit
try posting the fucking better sprites you fagotron and learn how to read past your dads crotch

**Comment by kol1th** [comment]
Epic my dude, thanks for the personal insults!

**Comment by PJB3005** [comment]
> The old one is quite literally a black outline

Yes. It is. Now guess what. Because the rest of the sprite is a lot darker there's less contrast and it's a lot less noticeable!

> They have good sprites though.

Then why are you porting the shit ones instead?

>  but people would whine and scream "IT LOOKS TOO GOOD FOR /vg/!", so I didn't bother.

No. They whine and scream when you're ruining the art style. See #13934.

**Comment by kol1th** [comment]
How do you feel about these, then, my dudes?

https://dl.dropboxusercontent.com/s/lancu1c6a2rnzq4/airlock_machinery.dmi?dl=0

**Comment by PJB3005** [comment]
Really damn good but the perspective is still messed up.

That said they do look a lot better with the messed up perspective.

👍 from me, I'm fine with changing the perspective of air alarms and stuff anyways.

**Comment by Riekland** [comment]
The sensor and access button are lovely but I think the control panels could do with less colours, they seem busy
much better than what we have or would be getting with this PR though

**Comment by kol1th** [comment]
Nothing is set in stone, my lad.

That's why we make open pull requests instead of directly commiting.

**Comment by kol1th** [comment]
Screenshots will be updated momentarily

**Comment by kol1th** [comment]
image

Gonna need to change some mapping vars later though. It doesn't look the greatest without it.

**Comment by IAGFPRMF** [comment]
Not **keypady** enough IMO Kolith calm down homie don't get mad at me ok

**Comment by PJB3005** [comment]
Why would it have to be a keypad for a UI that had practically 4 buttons?

**Comment by SonixApache** [comment]
Where are you getting these sprites?

**Comment by Zth--** [comment]
I like this one. It makes me want to fix their code. Can you port floors?

**Comment by kol1th** [comment]
Good things to come.

**Pull request closed without merging**
