### PR TITLE
Revert "makes dionae the supreme race like we always wanted!"

### PR DESCRIPTION
**Pull request by ShiftyRail**
i am racist against plants

### CODE REVIEW

**Comment by diegoxt45** [comment]
terrible pr and will break the balance

**Comment by boy2mantwicethefam** [comment]
It's a test merge for about 7 days to see what people think about it, then if people don't like it we can revert it

**Comment by DamianX** [comment]
bLeEdInG eDgE eXpErImeNt

**Comment by ShiftyRail** [comment]
:newspaper_roll: you are being silly

**Pull request merged**
