### PR TITLE
Revert "Adds the "Impostor" character from the 2018 hit video game "Among Us""

### LINKED ISSUE #28970: Amogus sprite is broken
#### Description of issue

When you turn from initial position amogus sprite turns invisible

#### Difference between expected and actual behavior

I expected amogus. I turned invisible. Please make it look the same whatever direction you face.

#### Steps to reproduce

1. Be amogus
2. Turn

#### Specific information for locating
amogus

#### Length of time in which bug has been known to occur
 
It never worked I guess

### PR DESCRIPTION
**Pull request by BomberBro**
"My name is Amogus, King of Kings;
Look on my Works, ye Mighty, and despair!
Nothing beside remains. Round the decay
Of that colossal Wreck, boundless and bare
The lone and level sands stretch far away.”

closes #28970

:cl:  
- rscremove: Removes the "Impostor" SCP reskin

### CODE REVIEW

**Comment by DrSnips** [comment]
sus

**Comment by Kurfursten** [comment]
To be clear, I can't reproduce the reported bug that the sprite doesn't work. I have no problem here, moving around and killing.
image

**Comment by Pspiotrek** [comment]
Maybe it was bussed wrong? I guess it works then.

**Comment by Kurfursten** [comment]
I am inclined to think you are right that it was bussed wrong, but I can't find the logs yesterday to see what went wrong.

Also
> They didn't even add left and right facing sprites, much less backwards

That really was lazy

**Comment by ghost** [comment]
when the antag is griff

**Comment by d3athrow** [comment]
change the imposter to simple mob with amogus sprite
looking at it too long gives you brain damage
eventually your character will involuntarily point at it and yell "haha amogus"

**Comment by Eneocho** [comment]
> 
> 
> change the imposter to simple mob with amogus sprite
> looking at it too long gives you brain damage
> eventually your character will involuntarily point at it and yell "haha amogus"

Almost based.

**Comment by ShiftyRail** [comment]
feel free to re-revert this on April the 1st

**Pull request merged**
