### PR TITLE
Secret mode will be rolled sometimes

### PR DESCRIPTION
**Pull request by ShiftyRail**
One of the easiest options put forward in #23153.

50% chance to roll secret at roundstart ; whether or not it did get secret will be displayed on round-end report

Admins can of course override it if they so desire in Dynamic Mode Options

### CODE REVIEW

**Comment by utilitas-** [comment]
But why?
Why staple in yet more half measures instead of doing it properly once and leaving it to be? Right now, it's already better than the TENSIONER of olde. All the injection costs and probabilities simply need balancing, ergo set probability of cult and vampire and ninja to zero and be done with it.

**Comment by boy2mantwicethefam** [comment]
>half of dynamic games should be one antag type so that half of rounds are vampstended

**Comment by ShiftyRail** [comment]
Some lads wanted that experience back. I'm just making it possible.

Keep in mind that even in secret mode, latejoin minor antags and traitors can spawn. (NB: ninja is not minor)

**Comment by SonixApache** [comment]
i for one welcome our vampstended overlords

**Comment by ShiftyRail** [comment]
Hard to be vampstanded when autotraitors can still spawn

**Comment by jknpj** [comment]
>sometimes
>50%

**Comment by FudgePucker** [comment]
Have extended be more common instead.
It helps remind people that, maybe it isn't the wizard, cult, or vampire that causes rounds to become turbo gunk, it's you.

**Comment by jknpj** [comment]
Might as well fix dynamic

**Comment by ghost** [comment]
I think this deserves a try just to see what happens. Classic secret ruleset isn't the same as secret gamemode, it's basically dynamic but only minor antags and autotraitor can roll after the roundstart big bad. 

If it ends up being more bearable then that could provide insight on what should be fixed with dynamic instead of blindly changing things.

**Comment by SonixApache** [comment]
how about starting it off a bit lower, like 10 or something

**Comment by Kurfursten** [comment]
The support is not there for this.

**Comment by ShiftyRail** [comment]
Not enough support

**Pull request closed without merging**
