### PR TITLE
Removes 0.01 metabolism on some reagents that have no reason to have 0.01 metabolism

### LINKED ISSUE #15068: Internal bleeding is a joke for vox specifically
One of the more minor racial upsides for vox is that they have a couple extra extra chems for healing toxin damage. (Gravy, which heals toxin damage at double the rate of antitox but is metabolized significantly faster, and nitrogen, which heals toxin at the rate of antitox and suffocation at the rate of dexalin, but is metabolized 20 times more slowly.) (Neither has the reagent clearing property of antitox though.)
In nearly all scenarios, this is barely useful. Nitrogen is mostly just useful because it lasts a really long time. It can keep you alive and awake at a slightly lower blood level and it can extend how long you can survive without a mask and tank for quite a while, but not indefinitely.
There is, however, one case in which nitrogen is really, really good, though: Taking along with absurd amounts of bicard to heal internal bleeding. Antitox works for that too, but you need to take only 5% as much nitrogen for the same amount of bicard. Plus, it heals some oxygen damage from your low blood, as well.

Proposal: Make the bicard OD deal more damage to vox.
Or nerf nitrogen, but please don't

### PR DESCRIPTION
**Pull request by ghost**
Notably Nitrogen, which was usable as a Vox-exclusive antitox that lasted 20 times longer than normal. The rest have no effect at all it's just weird.

Fixes #15068

### CODE REVIEW

**Comment by Exxion** [comment]
Fixes #15068

**Comment by ghost** [comment]
Yes, thank you, I had forgotten

**Comment by Kurfursten** [comment]
Cook gravy 👍

**Comment by PJB3005** [comment]
Isn't Nitrogen a Vox dexalin, not an anti-toxin?

**Comment by ghost** [comment]
Both

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
