### PR TITLE
Standardised if/while/for/switch formatting to have a space.

### PR DESCRIPTION
**Pull request by ComicIronic**
It's not a standard until you standardise it.

### CODE REVIEW

**Comment by clusterfack** [comment]
Ew gross, standardize it to NOT have a space

**Comment by Exxion** [comment]
Yeah fuck you Comic
No spaces

**Comment by ComicIronic** [comment]
Standard in most languages and IDEs is to have a space, and for good reason.

**Comment by clusterfack** [comment]
What reason could that possibly be

**Comment by ComicIronic** [comment]
It's more legible, and separates control keywords from methods.

**Comment by clusterfack** [comment]
Really? It's not even slightly more legible

**Comment by ghost** [comment]
> oranges wants no spaces

strongly considering changing my opinion on this now

**Comment by ghost** [comment]
Has anyone written these standards that are being enforced down? Seems we're just piling things up all of a sudden to make PRs a pain.

This is the first I've ever seen of this 'comparison statements must have a space' standard, and looking at most of the current active PRs, nobody seems to follow it

**Comment by ghost** [comment]
Yeah I'm in favour of no space, but this is not something that matters.
You want something that matters?
src.

**Comment by ComicIronic** [comment]
These standards can only become enforceable once we standardise them - I'm looking into ways we can automate the simpler formatting changes to keep consistency without coder burden.

**Comment by PJB3005** [comment]
👌

Seriously, this is a genuine readability improvement, especially in a language where there's no form of braces or even colons (python).

**Comment by ghost** [comment]
@ComicIronic you could have a bot automatically fix that on any new PR- I'm sure PJB knows a way

**Comment by clusterfack** [comment]
I wouldn't want it to have a space even if it required no effort to write, it makes the code less readable.

**Comment by Exxion** [comment]
I'm not sure it really affects readability either way
But it's ugly as fuck

**Comment by unid15** [comment]
Don't do this it's so ugly

**Comment by StarSmasher44** [comment]
Really don't get why a space like  this  would  be  a  better  thing  .
The extra readability (if there is any since I'm not seeing it) is pretty quickly followed by a death wish because in the end I'm gonna have to update this source with my changed one which already turned into a pain in the ass with the last random set of standards.

I just prefer it as it is, tbh.

**Comment by ComicIronic** [comment]
The conversion is simple - just do a sed replace. 

`s/( |\t|^)(if|for|while|switch)\(/$1$2 (/g` would do it, where \t is the actual tab character.

**Review by PJB3005 — APPROVED** [review]

**Comment by optimumtact** [comment]
I would like OP to name these languages that standardize on a space, because I've literally never seen code written in such a stupid manner

**Comment by Exxion** [comment]
I honestly can't believe I have to do this on this kind of PR but

**Comment by Intigracy** [comment]
confrictu / arguing

**Comment by ComicIronic** [comment]
Off the top of my head, C# and Java default formatting has a space between control words and conditions or loop code.

**Comment by ComicIronic** [comment]
RIP this PR and the bad taste that voted against it.

**Pull request closed without merging**
