### PR TITLE
[WIP] Shuttle datums and features

### PR DESCRIPTION
**Pull request by unid15**
This PR introduces shuttle datums, cleaning up the code and making creation of new shuttles VERY easy for coders and mappers

https://www.youtube.com/watch?v=y-lhcxiAP3E

---

**Feature list**:
- Shuttle datums
- Replaced research/mining shuttle compouters with a universal shuttle control computer (which can connect to either of these shuttles, or the salvage shuttle if given a password)
- Custom shuttles with two ways to create them, one using verbs for admins and one with a new item for users (the beacon based area designator is WIP and adminbus only, however)
- Fun admin features:
- "Extend shuttle" command which creates an area of the same shape as a selected shuttle, centered at you. The new area is connected to the selected shuttle and the shuttle can be sent there immediately.
- "Shuttlify" command which turns an any area into a shuttle
- "Lockdown" command which prevents a shuttle from being used by players (doesn't work on cargo/escape/specops shuttles)
- "Move shuttle" command which allows you to instantly move any shuttle to any of its areas
- And other utility commands designed to make ruining a round as easy and quick as possible for the admins

**To-do list**:
- Remove bugs

### CODE REVIEW

**Comment by FudgePucker** [comment]
I was the one who asked for player built shuttles in the thread, but that was a very large request.
Will you fix the taxis for taxi station to use these? Maybe also add in the features that let admins add derelict to the options for the taxis?

Also nice job. :+1:

**Comment by Unfit** [comment]
I have player built shuttles planned
Unless I didn't account for something, it's going to be fairly simple with shuttle datums

**Comment by Unfit** [comment]
Custom shuttles are live
I probably won't get a lot of opportunities to continue coding until I come back from holiday, so work will continue in about 2 weeks

**Comment by Unfit** [comment]
only a few shuttles need porting now (specops, emergency, cargo)

after I'm done with that I'll work on giving admins more ways to fuck shit up (like changing where the emergency shuttle/cargo shuttle docks, instantly adding areas to shuttles with a push of a button, etc)

**Comment by Unfit** [comment]
Almost ready for action

**Comment by FudgePucker** [comment]
RIP
"Fuck map editing" - Hitler, 2016

**Pull request closed without merging**
