### PR TITLE
Makes Busta-Nuts great again

### LINKED ISSUE #8707: Add nutriment back into Bustanuts
Syndie-cakes are still free and still have nutriment and it has caused zero issues
BUSTANUTS OR RIOT

### PR DESCRIPTION
**Pull request by 9600bauds**
Busta-nuts now have nutriment once again. As a compromise to keep them free, they're now a contraband item. To prevent hacked Getmore machines from having TOO MUCH free nutriment, lowered the stock of Busta-Nuts and Syndie-Cakes to 4 each.
I've never actually seen Syndie-Cakes out of stock, in fact I rarely see the machines hacked ever so I don't foresee anyone caring about the 2 missing cakes

Fixes #8707

### CODE REVIEW

**Comment by Imagebard** [comment]
>I've never actually seen Syndie-Cakes out of stock, 

Except when they're at SOLD OUT because some chemist or someone hoarded all 6 of them.
Why are you fucking with syndicakes, anyways?

**Comment by 9600bauds** [comment]
For free nutriment if there's no Chef or when I have something like 12 burn
They have no chemistry uses if that's what you mean

**Comment by Imagebard** [comment]
>or when I have something like 12 burn

I have a theory.
Every time I met an empty-of-syndicakes dispenser, it was because someone like 9600bauds emptied them to fix their 12 burn/brute damage which would have healed naturally soon.

**Comment by 9600bauds** [comment]
I take only one, I assume the rest are gone because of people now seeing that they're unlocked and free
Besides, "soon" VS "now and also fill my hunger bar so that I won't have to do it anyways later"

**Comment by Probe1** [comment]
I usually empty the whole vend after making my rounds hacking machines when there's no real engineering work.  That way people see it's there.

Anyway removing nutriment from bustanuts was GAY.  GAY GAY GAY.

**Comment by 9600bauds** [comment]
and not in a cool way

**Comment by Probe1** [comment]
test 

░░░▄▄▀▀▀▀▀▀▀▀▄▄
░░█░░░░░░░░░░░░█
░█░░░░░░░░░░░░░░█
█▀▀██▐███▀▀██▐████
█░░█▌████░░█▌█████
█░░░▀▀▀▀░░░░▀▀▀▀░█
█░░░░░░▄▄▄▄▄▄░░░░█
█░░░░░█░░░░░░█░░░█
░█░░░█░░░░░░░░█░█
░░█░░░░░░░░░░░░█
░░░▀▀▄▄▄▄▄▄▄▄▀▀
It's BAD to be a FAG!
Post this on the wall of a HUGE FUCKING QUEER and tell them how DISGUSTING they are

**Comment by Boxe** [comment]
i demand free vending machines

**Comment by 9600bauds** [comment]
sure, but they only have floortiles and they are always set to throw contents at people

actually that's a great idea

**Pull request merged**
