### PR TITLE
Adds a single wall to boxstation maintenance

### PR DESCRIPTION
**Pull request by nervere**
I have fixed this injustice:

image

[box]

### CODE REVIEW

**Comment by wotisjanitor** [comment]
soulless....

**Comment by Theophrastus1** [comment]
WHERE IS THE SOUL

**Comment by adacovsk** [comment]
remove the single pipe underneath the tool storage wall while you're at it

**Comment by nervere** [comment]
> remove the single pipe underneath the tool storage wall while you're at it

Done.
(it was two pipes)

**Pull request merged**
