### PR TITLE
Fixes being able to brush-spam to get a polar star/spur

### LINKED ISSUE #6994: Spur and Polar Star can be bruteforced really fast
Surround yourself with rocks containing artifacts/dig sites, spam your excavation strength 1 duster on all surrounding rocks until you get spur/polar star.

It shouldn't be this easy to get an auto recharging combat shotgun.

### PR DESCRIPTION
**Pull request by MadmanMartian**
closes #6994

As I'm not too sure if you can do prob(decimal), the chance to find them is now 1 in 100, rather than 1 in 500

### CODE REVIEW

**Comment by Exxion** [comment]
Who changed that name?
Anyway don't change the drop chance

EDIT: Yes, `prob()` works with decimals

**Comment by Exxion** [comment]
OK I should have requested changes I guess, but Unatomic should be treated as DNM anyway

**Comment by MadmanMartian** [comment]
DNM till justified

**Comment by Exxion** [comment]
If there's a reason to include everything, it isn't unatomic and shouldn't have the tag

**Pull request merged**
