### PR TITLE
Adds actual sprites for treadmills

### PR DESCRIPTION
**Pull request by doobiedoo23**
Adds animated sprites for treadmills to replace the original conveyor belt knockoff ones.

Couldn't get a good recording of the animated sprites in action, but here's how they look when the treadmill is off.

http://i.imgur.com/AgDsXgR.png

### CODE REVIEW

**Comment by ghost** [comment]
Something seems off about the sprite. Can we see a picture of it in game?

**Comment by DrCelt** [comment]
/

**Comment by MercuryDoll** [comment]
Seconded. I believe it's the straight-top-down perspective, it lacks depth.

**Comment by doobiedoo23** [comment]
They looked alright in-game when I checked them. I'll try to grab better screenshots tomorrow as right now my Dream Daemon is dying and barely able to host a test server. 

If they do end up lacking depth I'll work on them, anything is better than the old conveyor belt.

**Comment by doobiedoo23** [comment]
Wait I'm dumb I changed no files

forgot to commit, I'll fix that when I get a chance

**Comment by ghost** [comment]
NEVER TRUST A DUB

**Comment by doobiedoo23** [comment]
f i x e d

also dw i've noticed the big ugly line in the first one I'll fix this all up

**Comment by Kurfursten** [comment]
It would be really nice if you would consider looking for a better sound while working on this PR too

**Comment by SkowronX** [comment]
That's going to clash so hard with isometric objects.

**Comment by doobiedoo23** [comment]
probably

but hey that's what criticism is for, I'll work on the sprites to give them some of that sweet isometric depth and maybe work on finding a better sound tomorrow

**Comment by MercuryDoll** [comment]
> isometric

That's not what we're using though, ss13 isn't diagonal. The graphics are (for the most part) regular 3/4 perspective, with some things having an oddly slanted sideview (like the soda vendors).

**Comment by doobiedoo23** [comment]
http://i.imgur.com/pnfgiPK.png

This is it in-game. Not as great as I remember, gonna have to put in some work on it.

**Comment by Zth--** [comment]
I think it looks pretty good

**Comment by 9600bauds** [comment]
pls side view too

**Comment by ComicIronic** [comment]
Yeah, top down is not appropriate for something that isn't a wall or a door, really.

**Comment by doobiedoo23** [comment]
fixed ugly-ass sprites

in-game screenshots and gifs incoming

**Comment by doobiedoo23** [comment]
reworked the sprite entirely to give it a slightly more futuristic style and the illusion of depth
animations simply refuse to run properly when i record them as gifs due to my craptop, but they work fine

**Comment by ihadtoregisterforthis** [comment]
Try to get the screenshots in 32x32 or 64x64

**Comment by ghost** [comment]
@doobiedoo23 is this loss

**Comment by clusterfack** [comment]
Looks like an abortion to me.

Lets add it.

**Comment by 9600bauds** [comment]
Did you mean a miscarriage?

**Comment by doobiedoo23** [comment]
@DrCelt http://i.imgur.com/ozUvhdP.png

**Comment by ComicIronic** [comment]
Make the red dot consistent for directions.

**Comment by clusterfack** [comment]
@9600bauds That would imply it wasn't intentional

**Pull request merged**
