### PR TITLE
Mulebots update

### PR DESCRIPTION
**Pull request by Zth--**
# video https://streamable.com/nrglsr

# horn https://streamable.com/o04vli

Adds a new laser assembly to control mulebots. Don't look at the code yet, still heavy wip. I will write a little bit more later, I'm tired right now

- [x] Ability to unload crates onto cargo carts
- [x] Maybe slow it down a bit?
- [x] Fix motor wires
- [x] Add a horn and re-routing after failing to pass a carbon or some obstacle
- [ ] Fix unloaded crate layer
- [ ] Clean files
- [ ] Load/unload sound
- [ ] Finish the laser thingy and make it buildable
- [ ] Check I don't break pai stuff
- [ ] Either integrate or rework the navbeacon system
- [ ] Notifications to cargo
- [ ] Disable diagonals?
  - [ ] Fix blood tracks (depends on diagonals)

### CODE REVIEW

**Comment by Viciousaurus** [comment]
I aprove any improvement made to the Mulebots, and this sounds amusing, but if you make them move diagonally I'll fucking hunt you down. No need to increase the speed either.
Ideally, they should do the very basic thing they are meant to do; that is, give them an order to go to a certain department' beacon, unload its cargo, and return without a cargo member having to walk there. The problem right now is that the pathfinding sucks shit, they get stuck too easily, and in many maps they are simply broken. 
About your ideas, I love the idea of a laser to give them remote orders to load, unload crates and the laser can deal with the problem of mules getting stuck. Only thing I'd add to this is that if you send it to deliver a payload and they get stuck, they could send back an error message back saying "road blocked, payload undelivered, etc"

**Comment by WindowsErrors** [comment]
i will write this to future me that vehicular manslaughter carries a mandatory 10 year prison sentence with no chance of parole

**Comment by Zth--** [comment]
>I aprove any improvement made to the Mulebots, and this sounds amusing, but if you make them move diagonally I'll fucking hunt you down. No need to increase the speed either.

They'll move diagonally, I have no intentions of messing with the algorithm yet. I reduced their speed though (check the second video)

> Ideally, they should do the very basic thing they are meant to do; that is, give them an order to go to a certain department' beacon, unload its cargo, and return without a cargo member having to walk there. The problem right now is that the pathfinding sucks shit, they get stuck too easily, and in many maps they are simply broken.

The new algorithm makes better paths. Also I made some improvements on the handling of obstacles (creatures), so they try new routes avoiding said creature. About the broken navbeacons I have no plans of fixing that in this PR.

>Only thing I'd add to this is that if you send it to deliver a payload and they get stuck, they could send back an error message back saying "road blocked, payload undelivered, etc"

Noted, will do

**Comment by ShiftyRail** [comment]
😔

**Pull request closed without merging**
