### PR TITLE
HTML UI Interfaces - Crew Monitoring Comp

### PR DESCRIPTION
**Pull request by clusterfack**
-THEY DON'T LAG LIKE NANOUI MAPS!!
-Only crew monitoring computer exists
-It was coded on the assumption it only shows the current zlevel's minimap, we can modify this but I personally agreed with that method of handling it to start with
-There is a check now for html range that doesn't require calling range(), and allows silicons to use the html interfaces at range

Todo:
Make it not dependent on the zlevel you are on, this is possible but discuss whether its necessary because it requires a bit of effort
The original dot on the minimap is still super fucking small, I need to find the element to make it larger
Make sure toggling suit sensors queues an update

### CODE REVIEW

**Comment by clusterfack** [comment]
We can also use the minimap generator to create minimaps for the pda maps automagically

**Comment by clusterfack** [comment]
Oh I almost forgot, thanks to @nullquery for making the base for this wonderful piece of UI

**Comment by Intigracy** [comment]
Any way to sort the listings on the computer alphabetically?
Or even just by department, anything but the random, unorderly jumble of colors we have now.

**Comment by clusterfack** [comment]
They are sorted by the department right now, we can probably add an option to sort alphabetically without too much trouble

**Comment by nullquery** [comment]
@Intigracy @clusterfack Was my patch included? https://github.com/tgstation/-tg-station/pull/10407 and https://github.com/tgstation/-tg-station/pull/10449

**Comment by clusterfack** [comment]
Yes they were included, though I made my own version of tgstation/-tg-station#10449

**Pull request merged**
