### PR TITLE
Allows forges to smelt ores

### PR DESCRIPTION
**Pull request by ghost**
[content]
Accepts one stack at a time, forge must be above melting temperature for ore to smelt and match recipe.
Let me know if it needs balancing.
:cl:
 * rscadd: Blacksmithing forges can now smelt ores, one pile at a time. (except plasma, the fuel)
 * tweak: Ingredients checking now only looks for the material datum instead of the entire parent ore processor object, for more flexibility.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you smelt slag or do you still need to recycle it?

**Comment by ghost** [comment]
> Can you smelt slag or do you still need to recycle it?

It's ore type so it'll get the temperature smelt check stuff.

**Comment by DeityLink** [comment]
would it be much work to give that functionality to cult forges as well?

**Comment by ghost** [comment]
> would it be much work to give that functionality to cult forges as well?

Probably not even though they aren't the same type at all, all I really changed is allowed ores to be smelted from heating them, so anything can call attempt_heating() on them to do it. Not everything does right now, tested it with laser scalpels and they did nothing.

**Pull request merged**
