### PR TITLE
Adds new peanut based foods, hopefuly without conflicts

### PR DESCRIPTION
**Pull request by ComradeDispenser**
[tested][sprites]
Since peanuts have finally been added to the game I have decided to make something you can actually do with them besides eat them raw and mutate them into rocknuts.

Peanut butter is made with three peanuts and one unit of salt.
Grape jelly is made with one bunch of grapes and five units of sugar.
A PB&J sandwhich is made with two slices of bread, peanut butter and grape jelly
Salted peanuts are made with three peanuts and five units of salt.

image
Spritework is all done by me, with the exception of the salted peanuts, which was shamelessly lifted from a denied PR from six years ago, PR #1046, made by some guy named Heredth I guess.

I also created a new .dmi for future food projects to use, food2.dmi.
.dmis can only contain a certain amount of icons before they start culling icons to make room for new ones, which is how we lost and had to remake the sprite for dead corn, and the current food.dmi was looking a bit full, so I decided to play it safe and make a new one to start filling with brand new content.

:cl:
 * rscadd: Added peanut butter, grape jelly, peanut butter and jelly sandwiches and salted peanuts as cookable foods

### CODE REVIEW

**Comment by SonixApache** [comment]
>that's a salted peanuts

😕

**Comment by PrimeDSS13** [comment]
Now all we need to add are peanut allergies.

**Comment by Zth--** [comment]
Will merge once you update the wiki

**Comment by ComradeDispenser** [comment]
Wiki finally updated!

**Pull request merged**
