### PR TITLE
Adds male corgi and corgi family crate to cargo

### PR DESCRIPTION
**Pull request by ThHuberResearch**
Adds two new crates to cargo:
Male corgi crate:
- Costs 250 to keep Ian valuable
- Contains a generic male corgi

Corgi family crate:
- Costs 300
- Contains Lisa, a generic male corgi and a puppy

This makes it easier to get puppies. Currently HoPs usually let you breed Lisa with Ian anway if you want puppies. The relatively high cost of the male corgi keeps Ian valuable.
The new male corgi crate can also be used to swap Ian with a generic boring corgi and see how long it takes for the HoP to notice you stole his dog.

:cl:
 * rscadd: Added male corgi crate to cargo. Costs 250, contains a male corgi.
 * rscadd: Added corgi family crate to cargo. Costs 300, contains a male and a female corgi and a puppy.

### CODE REVIEW

**Comment by SonixApache** [comment]
Ian is the only stud on this station.

**Comment by gbasood** [comment]
\>every female will be named Lisa
terrifying

**Comment by ThHuberResearch** [comment]
I kept it that way because a lot of stuff (for example, all wooden crates including goat and chicken use an icon called "lisacrate") and I thought that maybe there is some weird reason there are references to Lisa everywhere?
I think I would be able to make the female corgi have a random name from a list, if that is a thing that should exist?

**Comment by N3X15** [comment]
Emojicracy sez no

**Pull request closed without merging**
