### PR TITLE
Xenoarch Drill

### PR DESCRIPTION
**Pull request by frangi**
A new drill obtainable through research to avoid the chore that is using the manual kit.

### CODE REVIEW

**Comment by ComicIronic** [comment]
>wclass 1
>variable dig depth
>low digtime

I'd up this to a far higher research level, or people are going to get it from Research immediately.

**Comment by frangi** [comment]
I'm up to suggestion.

I actually copied the weight class from the surgical drill.
Variable dig depth is the only reason I want this item, along with its bulk. It's impossible to click the fucking picks, it's a headache due to how small they are.

The digspeed is slower than the normal picks, on par with the handaxe, and that can be tweaked, what do you suggest? 50?

About the research tree... well, I'm open for suggestions here too. maybe up everything by 1?

**Comment by DeityLink** [comment]
ah, about that, this is the kind of tool that I'd like to make available from R&D using the upcoming anomaly tech tree. If you want you can just PR the code for the item and let me implement it in the research paths.

**Comment by frangi** [comment]
well, we don't know how much time it'll take for you to actually complete your anomaly rework, so why not pull this in for now, and then revert/overwrite when you'll actually push your work?

As it is now, being a digger is extremely boring mainly due to the excavation picks' handling, it's a nightmare. It's physically hard to click them. This, along with the depth scanner change would already make this job 10x times more enjoyable.

**Comment by d3athrow** [comment]
I feel like it makes no sense as a drill is hardly a precision tool.

**Comment by DeityLink** [comment]
That too. Spending time delicately extracting artifacts and changing tools is actually charming for some people, I think the issue is elsewhere, though I agree that the handpicks need bigger sprites.

**Comment by frangi** [comment]
We can adjust the fluff about the item, Also drills can be precise, ever been to a dentist? We can make them "ultrasound" drills or whatever.

**Comment by frangi** [comment]
I believe this should be in a better state now. It's now basically an -endgame- item, requires diamond to be built and has a more "believable" reason for doing its work right.

**Pull request closed without merging**
