### PR TITLE
Horror form fixes, part 1

### LINKED ISSUE #18580: Lings can spam horrorform
#### Description of issue
You can spam horrorform, it plays that animation and scream sounds each time. It doesn't regenerate player health (I tested this to see if it does.)  I don't think this is a feature.

#### Difference between expected and actual behavior
Expected not to be able to spam horroform. It doesn't cost any chemicals to do so.

#### Steps to reproduce 
Suck five losers become the perfect killing machine.

#### Length of time in which bug has been known to occur
No idea.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by DamianX**
- Horror lings can't use the horror form verb anymore
- Moved `set_species` before the sleep to prevent spamming on the verb

Closes #18580 
:cl:
 * bugfix: Changelings cannot spam horror form any longer.
 * bugfix: Fixed "Horror Form" costing 0 chems.

### CODE REVIEW

**Comment by Intigracy** [comment]
no fun allowed

**Comment by aceedex** [comment]
Cant we call horror scream spam a feature? or add it as a spell once youve horror formed?

**Comment by Exxion** [comment]
Why?

**Comment by aceedex** [comment]
its fun

**Comment by MusgardTiger** [comment]
actually horror scream as a verb with like two minutes cooldown could be neat.

**Pull request merged**
