### PR TITLE
Vampire Hypnotize now only fails on blinded people if their blindness is genetic or because of a blindfold.

### LINKED ISSUE #26924: vampire is broken
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
8021aaf5395f8ad5300f936e9b7845ac202b370e

# Description
https://gyazo.com/2495f2ba2906dfdf6848f0a5795eb4e6
# Steps to Reproduce
glare then try to hypnotise
# What you Expected
be able to hypnotise
# What Actually Happened
I died

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #26924

:cl:
* tweak: Vampire Hypnotize now only fails on blinded people if their blindness is caused either by genetic or worn items. So you will no longer fail Hypnotized because you recently cast Glare. (mastercasual)

### CODE REVIEW

**Comment by Dacendeth** [comment]
So a blindfold wont protect me anymore?

**Comment by DeityLink** [comment]
> 
> 
> So a blindfold wont protect me anymore?

Turns out there are 3 different things that give the blind overlay and the glare blindness, genetic blindness, and blindfold blindness are all different.

**Comment by Blithering** [comment]
What about good old "welded 100 times in mesons" blindness?

**Comment by Kurfursten** [comment]
well?

**Comment by DeityLink** [comment]
@Blithering @Kurfursten Using the welding tool so much literally gives you the BLIND genetic disability

image

So yeah doing that will protect you from Hypnotize as well lol

**Pull request merged**
