### PR TITLE
Gun recoil no longer shakes your screen

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I don't like my aiming going XCOM when I fire a revolver. Recoil itself still exists but it mostly affects inaccuracy in case the gun is defective. It's not that I hate recoil as a concept but BYOND is limited enough that the closest thing to a proper recoil was making your screen boogie whenever you fired a gun
:cl:
 * tweak: Guns with recoil will no longer shake your screen when fired.

### CODE REVIEW

**Comment by Irradiation** [comment]
I dunno man, as weak as it is, at least it makes you feel like you shot something strong, instead of laser-tag lasguns.

**Comment by boy2mantwicethefam** [comment]
I kno-oh fuck, THE HECATE

**Comment by utilitas-** [comment]
the Hecate definitely should have screenshake, railgun too
the mosin nagant rifle shouldn't have screenshake, but the obrez also definitely should, already makes you look like Kruschev pounding shoe on desk and shouting angry plan to bury NATO in deep grave.
also consider the L6-SAW

**Comment by boy2mantwicethefam** [comment]
I made the hecate projectile shake cameras
@Irradiation I see your point but I think the camera shake is just too strong for anything, the "oomph" feeling should come more from the sound than anything
@utilitas- Yeah sure

**Comment by Irradiation** [comment]
Maybe you're just a bitch in terms of feeling it from the screen shake.

**Comment by boy2mantwicethefam** [comment]
@utilitas- Railgun uses magnets and has no recoil as a result because there is no conventional bullet backblast to propel the gun backwards while the projectile goes forward
I checked the Obrez and L6 but I don't want to add recoil to them yet because then it would be an oversight where Obrez and L6 do recoil but stuff like shotguns don't and then I'd have to ditch this PR and preferably make a new system where wielding the gun removes the spread but then I'd need even more sprites for even more guns seeing as most guns are basically one-handed and you probably get the idea
@Irradiation I guess I'm a bitch in that regard, I just don't consider much oomph from the screen shake, I see it as too hacky and too disorienting, recoil oomph works far better in other mediums like shooters and such

**Comment by utilitas-** [comment]
\>and has no recoil as a result
ligga.
newton's first law.
literally anything that fires any projectile in any way has recoil. if it had no recoil, you wouldn't be going anywhere.
and who gives a shit about realism, the real important part is how it feels, and if you're going to charge up the railgun to max, you better believe I want it to feel fuckin' beefy.
in fact, make the screen shake dependent on the power of the projectile, it has a variable available for it

**Comment by ShiftyRail** [comment]
My immersions

**Comment by boy2mantwicethefam** [comment]
Terrible reception and an anon working/used to work on something better made me consider closing this

**Pull request closed without merging**
