### PR TITLE
The suit modification thingy can now repaint plasmaman and vox suits

### PR DESCRIPTION
**Pull request by DamianX**
https://user-images.githubusercontent.com/6307265/126763745-5c65fe20-fcdf-4d97-a362-52e45e4f09aa.mp4

the footage is pre-alpha: this also unatomically fixes the already-broken animation but I'm not capturing another video

:cl:
 * rscadd: The suit modification station can now repaint plasmaman and vox suits.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
Finally, no more praying for a HOS suit.

**Comment by Kurfursten** [comment]
Looking at the build sprite lists -- does this allow you to get special suits like the bee plasmaman and cult plasmaman?

**Comment by Eneocho** [comment]
> 
> 
> Looking at the build sprite lists -- does this allow you to get special suits like the bee plasmaman and cult plasmaman?

Here's hoping it lets you build both, since the cultist plasmeme suit looks great (and wearing one as non cultist during a cult round is asking for death).

**Comment by DamianX** [comment]
Only if there's a job that would make you spawn with one of those, which there isn't. It would be pretty dumb because they're sold by traders.

**Comment by Eneocho** [comment]
> 
> 
> Only if there's a job that would make you spawn with one of those, which there isn't. It would be pretty dumb because they're sold by traders.

I thought that beekeeper plasmemes spawned with the bee suit.

**Comment by wotisjanitor** [comment]
> Only if there's a job that would make you spawn with one of those, which there isn't. It would be pretty dumb because they're sold by traders. 

I mean, the bee suit is literally just black and yellow so i don't see why it'd be trader only. I do see that for cultist suit though.

**Comment by mrflarg** [comment]
Wait so plasmamemes can not just fucking spray themself to look like secoffs?
How overpowered do you want these snow flake bubble babies. 
Just fucking remove blood from them and the need to eat already. and make them heal from plasma fires while you are at it.

**Comment by DamianX** [comment]
immagine
I made it so only suits that you would have access to are available. Steal the captain's ID if you want the plasmaman captain suit.

**Comment by Kurfursten** [comment]
I think that's a good way of handling it. He anticipated the trader complaint too.

**Comment by Blithering** [comment]
>Wait so plasmamemes can not just fucking spray themself to look like secoffs?

Sec jumpsuit lockers have no ID restriction, so its even easier to look like one as another race.

**Comment by wotisjanitor** [comment]
> Sec jumpsuit lockers have no ID restriction, so its even easier to look like one as another race.

You're forgetting that sec and captain suits have more armor than others.

**Comment by Kurfursten** [comment]
This does not change the suit to be an actual armored suit, it only changes the sprite. It also appends the description, "The colors are a bit dodgy"

This is like when you washing machine with a crayon to get yellow gloves. They aren't insulated.

**Comment by Eneocho** [comment]
> Just fucking remove blood from them 

Plasmemes don't have blood.

**Pull request merged**
