### PR TITLE
Add a lockbox for virus dishes.

### LINKED ISSUE #25066: [Feature Request] Disease Dish Storage Box
<Featurerequest>
Virology could really use a storage unit for labelled disease cultures. Culture trays have a fairly large sprite, so placing them on the table in virology isn't a great solution because you'll run out of room fairly quickly if you start ordering disease crates. I think you could probably use a modified sprite of the vial holder, and maybe even the lockable one as well for particularly dangerous diseases. I'd just like a place to put them that isn't spread out all over the table or stacked up on the floor.

### PR DESCRIPTION
**Pull request by ghost**
image
image

Fixes: #25066
:cl:
 * rscadd: Added a lockbox for virus dishes.

### CODE REVIEW

**Comment by DamianX** [comment]
wow wtf is that sprite

**Comment by tuypo1** [comment]
The spirit looks fine to me

**Comment by Zth--** [comment]
I don't reeeaaally see the reason for using an overlay instead of simply spriting it in.

**Review by Zth-- — CHANGES_REQUESTED** [review]
Please sprite it instead of using an overlay

**Comment by charlottesgit** [comment]
Please oh god please. I had somebody release a virus that turned people into rainbows and got executed for it. Why was the infected blood locked up but not the diseases themselves?

**Comment by ghost** [comment]
> 
> 
> I don't reeeaaally see the reason for using an overlay instead of simply spriting it in.



> 
> 
> Please sprite it instead of using an overlay

A `few lines of code` VS `spriting 3 unique sprites`.
🤔 
Either way, **I'm** not spriting it. If someone else does, sure I'll use theirs. If no one does, go ahead and close this.

**Comment by ghost** [comment]
lol im finna head out so imma close this

**Pull request closed without merging**
