### PR TITLE
Revert "Damage effects for items broken out of lockboxes", now with more precision.

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
Reverts d3athrow/vgstation13#11753

But this time it keeps the changes to weapon permits and logging, the only thing directly reverted is the actual addition of weapons being damaged.

### CODE REVIEW

**Comment by Exxion** [comment]
(Normally I wouldn't tag as [Controversial] so early, but it's a continuation of a PR that was)

**Comment by icantthinkofanameritenow** [comment]
Where the hell is the conflict? I can't find it, and can't fix it.

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/pull/12151

**Comment by icantthinkofanameritenow** [comment]
Well, I went and addressed the conflict, and it didn't do shit.

**Comment by icantthinkofanameritenow** [comment]
Re-remaking this thing, because fuck git.

**Pull request closed without merging**
