### PR TITLE
Makes the code compile under 510.

### PR DESCRIPTION
**Pull request by PJB3005**
**Note:** because I couldn't be bothered to add a shitton of #if directives this'll also make it so the code NEEDS 510.

Also I need to make sure I didn't break anything.

**OH GOD GIT WHAT ARE YOU SMOKING**

### CODE REVIEW

**Comment by clusterfack** [comment]
Oh shit son, smooth

**Comment by PJB3005** [comment]
Okay it doesn't work at all due to screen object changes.

**Comment by neersighted** [comment]
tgstation/-tg-station#14981

**Comment by gbasood** [comment]
Supposedly, we can get some performance improvements by migrating to 510. Supposedly.
We should really get shit working.

**Comment by clusterfack** [comment]
Yes, once this is fully ready we'll force it in.

**Pull request closed without merging**
