### PR TITLE
Anchor arms give tackle bonus

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Anchor arms now give a slight tackle boost to offense and defense (15) but not to range.
## Why it's good
Look at those arms man, you could tackle the heavens with those.
## How it was tested
Spawned the arms, tackled a naked monkeyman 10 times, succeeded the tackle roll each time.
:cl:
 * rscadd: Anchor arms now give a slight tackling boost to offense and defense.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
they very clearly did nothing in the episode doe

**Comment by boy2mantwicethefam** [comment]
They are balloons

**Comment by Eneocho** [comment]
i find the idea of them giving you actual buffs really funny, even though they are balloons

**Comment by Eneocho** [comment]
it do be like that

**Pull request closed without merging**
