### PR TITLE
Ram Fixes

### PR DESCRIPTION
**Pull request by Kurfursten**
Now more OOP
Also includes spiffy new upgraded sprite for post ramkit ram

ram
@Exxion @I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE 

🆑 
* rscadd: The battering ram gets a new, animated sprite if upgraded with the trader upgrade kit.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
The security metaclub strikes again!
add changelog pls

**Comment by Exxion** [comment]
This is better but it would be even better if the roboram were a separate subtype, and overrode `can_ram()` accordingly

**Comment by Kurfursten** [comment]
This way we're covered against mommers who pick up the default ram too

**Comment by Exxion** [comment]
I'm not really sure under what circumstances a MoMMI should use the ram but OK

**Comment by Kurfursten** [comment]
Never, this covers us against them using it

**Comment by Exxion** [comment]
Oh right
But the solution I suggested would do so as well

**Pull request merged**
