### PR TITLE
Robotics for the Robos

### PR DESCRIPTION
**Pull request by Apogee-dev**
One of two solutions to the "roboticist is just scientist but worse" issue. Do not merge if #29906 is merged. Removes robotics access from the Scientist job, leaving only Roboticists, the RD, and silicons with access to robotics.

:cl:
 * rscdel: Removed robotics access from the Scientist job.

### CODE REVIEW

**Comment by Dacendeth** [comment]
Scientists shouldn't have robotics access, but also the robotic fab shouldn't require access to use, so scientists can still hack in/break windows, like a paramedic and chemistry.

**Comment by Apogee-dev** [comment]
> Scientists shouldn't have robotics access, but also the robotic fab shouldn't require access to use, so scientists can still hack in/break windows, like a paramedic and chemistry.

Agreed on that one. As much as I hate the idea of random players hacking into robotics to build yet more overtuned mechs, it's a consistency issue with almost all of the other production machines and consoles in the game, like atmos pipe dispensers, chemistry machines, and the RnD console, that anyone can use if they hack into the room. Actually, I'll probably open up yet another separate PR for that, it's a change we could use regardless.

**Comment by Apogee-dev** [comment]
>the robotic fab shouldn't require access to use, so scientists can still hack in/break windows, like a paramedic and chemistry.

Opened up #29909 with regards to this. Should make this PR more viable as well, since if both are merged scientists could still hack into robotics if they really need to fix a borg or can't live without waving their phazon boner around.

**Comment by Jackreturnswithaveangenace** [comment]
The only real gameplay argument for scientists to have access to robotics is to make R&D quicker and this seems more appropriate as a solution than just giving roboticists science access. The two jobs are separate, though they're in the same department.

**Comment by DeityLink** [comment]
Ok but add an exofab to R&D so I can make those three syringe guns myself then.

Access wasn't department-wide back when I started playing SS13 and that fucking sucked. Worst case scenarios scientists will just ask the HoP for access at roundstart.

**Comment by DeityLink** [comment]
I swear the only people who upvote this do not play scientist.

**Comment by Kurfursten** [comment]
We should return to pre-badclown access levels for a week so that everyone can enjoy the feels of "station engineer can't enter atmos", "botanist can't enter kitchen", "shaft miner can't use the cargo console", etc.

**Comment by Durgen** [comment]
maybe this would have made sense in 2017, but pop is too low in 2021 to distinguish between scientist and robo like this

**Comment by Apogee-dev** [comment]
> Ok but add an exofab to R&D so I can make those three syringe guns myself then.
> 
> Access wasn't department-wide back when I started playing SS13 and that fucking sucked. Worst case scenarios scientists will just ask the HoP for access at roundstart.

That's part of why I opened #29909 (although it's also a change i've seen players asking for for quite a while), since that would just put scientists in the paramedic's position of only being separated from extra equipment by one window. I don't feel too strongly either way, but if this is the one that gets merged the exofab lockout would otherwise become a significant problem.

**Comment by DeityLink** [comment]
Exofab shouldn't be locked anyway, that I'm sure everyone agrees. I'd rather lean toward Robotics having more science access. Jobs are useful to indicate to the rest of the department what you're gonna focus on. (We should split the rest of the science jobs already)

**Comment by Apogee-dev** [comment]
> Exofab shouldn't be locked anyway, that I'm sure everyone agrees. I'd rather lean toward Robotics having more science access. Jobs are useful to indicate to the rest of the department what you're gonna focus on. (We should split the rest of the science jobs already)

I've been toying around with a science job split recently (I'll have to wait until one of these robo PRs gets merged to push that though), splitting it up into Scientist for standard/toxins and Xeno Researcher for xenoarch/xenobio/xenobotany. There's still some issues with that split (namely xenobio is onstation and toxins is offstation, so they aren't that neatly divided by where they do their work) but the xeno theme linking those alt titles together makes sense imo.

**Comment by DeityLink** [comment]
As a science player and xenoarch main I don't quite agree with your split.

* Xenoarchaeologist should be its own job with Anomalist as an alt title
* Xenobiologist should be its own job

* Xenobotany and Toxins should still be Scientist alt titles

Either way they should all keep full science access.

The reasoning being that Xenobotany has actually very little to do with xenoarch, beyond taking place at the outpost, and Xenobio has nothing to do with either. Xenobotany also doesn't have enough dedicated player to warrant graduating from just being a title imo.

That'd be like grouping together Virologist, Chemist and Geneticist under the same job.

**Comment by Jackreturnswithaveangenace** [comment]
R&D having an optimal route that involves the three syringe guns from the robotics fab is an R&D issue.

- There's other ways to get the research, its not the only one.
- You can just break in, its not like you don't have the tools to do it.
- The fact that "research and development" is not research but rote learning a pattern of kicks and clicks is thematically bleh (but aside from the tetris machine no one really has a better idea right now).

**Comment by Jackreturnswithaveangenace** [comment]
Also asking sympathy for scientists is a bad pubic relations idea when our 9/10 of our respondents to this survey placed the RD last in the list of people to be cloned (further testing with a bald scientist named 'Horatio' required).


Fun fact, the assistant and the cuffed/husked pimp suit wearer were usually first to be cloned.

**Comment by Eneocho** [comment]
> the assistant and the cuffed/husked pimp suit wearer were usually first to be cloned.

based

**Comment by PrimeDSS13** [comment]
I'm all for this PR, but only if #29909 is also merged. I think it will give Roboticist an actual purpose, and I think the fact that all of science has the same access is a bit silly (the solution isn't to just make roboticist another alt title of scientist).

also just because minmaxxing research requires you to hack one more door doesn't mean this PR doesn't make sense Deity

**Comment by DrSnips** [comment]
Now to wait for everyone to realize this change is retarded.

**Comment by Kurfursten** [comment]
That's the nice thing about a living codebase, we can try things and if people hate it, it can change

**Comment by DeityLink** [comment]
I'm already mad, fuck this change

**Comment by DeityLink** [comment]
> also just because minmaxxing research requires you to hack one more door

you really think I'm not just gonna just break straight through the window?

**Comment by DrSnips** [comment]
> > also just because minmaxxing research requires you to hack one more door
> 
> you really think I'm not just gonna just break straight through the window?

This.

**Comment by DrSnips** [comment]
*In fact. I motion to limit chem access to chemists seeing how popular this one was. 
It has a dedicated role after all and chemist is just MD but worse.*

**Comment by Kurfursten** [comment]
You know how to make a PR

**Comment by FlintBarrel** [comment]
Necro-posting to tell you all that this was a terrible idea, and it makes roboticist a much shitter role than just going scientist and breaking in.

**Pull request merged**
