### PR TITLE
NPC pathfinding through border-windows

### PR DESCRIPTION
**Pull request by DeityLink**
problem

I've fixed it using the same method that @Exxion used by in #9894

Tested. Still blocks mobs and projectiles as normal.
solved

### CODE REVIEW

**Comment by clusterfack** [comment]
>Since the movecode update


This is false, this is always how it worked

**Comment by DeityLink** [comment]
Really? That's not what the other admins on the server told me when they brought this issue to my attention. It's clearly a new bug.

**Comment by PJB3005** [comment]
Yeah wouldn't be suprised if NPC pathfinding was always crap.

**Comment by clusterfack** [comment]
You are welcome to test it yourself genius, load up the code from before the move update.

**Comment by Shadowmech88** [comment]
I've seen the Russians on the satellite exhibiting this behavior, where they must break the inner layer of windows before they can move onto the tile.

It's definitely been like that as long as I can remember.

Sometime here soon I plan to increase the intelligence of some simple_mobs a little, for example making them see portals as obstructions and purposefully avoid them.

**Comment by ComicIronic** [comment]
I do not suggest this fix - it is a patch for a non critical issue. NPCs should be fixed instead to use better path code.

**Comment by DeityLink** [comment]
@clusterfack 
I'm not saying you're lying. This is what I've been told.

@ComicIronic 
"should" is the keyword here. Who's going to do it? 
For anyone who wants to give it a shot, NPCs move using BYOND's walk_to() proc, which takes dense obstacles into account.

**Comment by clusterfack** [comment]
The admins have never known a lick about anything going on with the code, and the only credit I've EVER given them was when they correctly guessed the server memory leak problem was caused by shuttles.

**Comment by gbasood** [comment]
@DeityLink I didn't fix that what, that's Exxion's PR
@ComicIronic Okay let's throw in more expensive code for pathfinding instead of fixing up what we have, why not? I mean that sounds perfectly reasonable to me. Because NPC pathfinding is so crucial it deserves the most complicated and expensive logic.

**Comment by Intigracy** [comment]
This doesn't make it so you can walk through fulltile windows, does it?

**Comment by ComicIronic** [comment]
> Okay let's throw in more expensive code for pathfinding instead of fixing up what we have, why not?

Because speed is secondary to quality. You code well, and you make it fast. You don't make arbitrary code very very fast, because what's the benefit? Your speed is just for shit features.

NPC pathfinding for hostile mobs is not frequently-used code: it's totally acceptable to code it properly for a minor cost.

**Comment by DeityLink** [comment]
@ComicIronic Then can you please tell me how to code it properly? Because I gave it a shot and it didn't look good. And don't say that "NPC pathfinding for hostile mobs is not frequently-used code" it's used literally every round. whether by carps, by russians, rabid slimes, it's getting used every rounds.

**Comment by gbasood** [comment]
> Because speed is secondary to quality.

No, not really.
Pathfinding, especially in BYOND, is a highly expensive operation.
Pathfinding is fine as it is, except for this one bug.

**Comment by ComicIronic** [comment]
> it's used literally every round

Yes, infrequently. By constract, Life() code is also used every round but very frequently within it.

> No, not really.

>

> Pathfinding is fine as it is, except for this one bug.

A bug which is going to repeat itself for every object that doesn't block but is dense. So you're going to change major parts of the game to fit a system which itself pretty broken because it doesn't work with pass flags in the first place. That's coding around the issue.

**Comment by gbasood** [comment]
@ComicIronic If you think you can design a more efficient pathing system, by all means, do.
Turning down a bug fix by saying 'just make pathing better' is incredibly detrimental.

**Pull request merged**
