### PR TITLE
Revert "Small box changes (#23564)"

### PR DESCRIPTION
**Pull request by SonixApache**
This reverts commit 64f95945515ba56040e39a36b32cb6700a3aa79f.

c'mon dudes

### CODE REVIEW

**Comment by Kharkov72** [comment]
+30,038
is this the pr that saves vgstation?

**Comment by Kurfursten** [comment]
Speedmerge is a bad practice even for jokes
Bad 🆑 
Swapping files is stupid
And jokes should not mess with map priority.

**Comment by tuypo1** [comment]
At the very least there should have been a way to make it as a joke that didn't mean so much data would have to be redownloaded.

**Comment by ComradeDispenser** [comment]
Un-merge now!

**Comment by Exxion** [comment]
Maps aren't assets. Clients shouldn't have to redownload anything.

**Comment by tuypo1** [comment]
Hm you are right, I jumped to conclusions about how much data it would be without really thinking it through.

**Pull request merged**
