### PR TITLE
Three New Virus Symptoms

### PR DESCRIPTION
**Pull request by Arthurdentist**
Adds three new Virus Symptoms, one annoying, one bad and one good
- Chicken Pox (Stage 3)
  Makes you obnoxiously cluck and bawwwk like a chicken
- Vox Pox (stage 4)
  Makes you into an obnoxious vox (who are pox)
- Delightful Effect (stage 4)
  More powerful optimism effect that makes you synthesis Doctor's Delight

Do not merge yet, I am trying to think of some possible new good syndromes, because the bad far outweighs the good.

### CODE REVIEW

**Comment by SkowronX** [comment]
Voxpox yes

**Comment by Senaat1** [comment]
Please make people with Chicken Pox lay eggs. I want the station to be swamped with chickens.

**Comment by Probe1** [comment]
^

holy god what senaat said

**Comment by Arthurdentist** [comment]
Still doing a bit of testing but everything should be sorted now and ready to merge (If Travis doesn't freakout and supposing I haven't missed everything)

Added a changelog and  Chicken Pox now makes you vomit up eggs

**Comment by Probe1** [comment]
You're the best.

**Comment by Midaychi** [comment]
Any chance of using strength and such? They're part of the viro system, and have variables that are mutatable by a lesser mutate call. Usually the higher the strength of the virus symptoms the higher effect.

**Comment by Arthurdentist** [comment]
I am not sure what you are on about Midaychi, can you point me to an example in the code?

**Comment by Arthurdentist** [comment]
Well I look around and I'm not sure what Midaychi means exactly but everything works fine. Should be all ready to go.

**Comment by Midaychi** [comment]
Apparently it's used as multiplier in disease.

Strength : [E.multiplier * 8]. Verosity : [E.chance * 15]  (from disease2.dm)

Chance is already handled via the code, as it's "Chance in percentage each tick" of a symptom activating.

Strength is "The chance the effects are WORSE". The disease analyzer spits out a paper with numbers on the strength and verosity and stuff.

Here's an example where it's used.

/datum/disease2/effect/radian
	name = "Radian's Syndrome"
	stage = 4
	maxm = 3
/datum/disease2/effect/radian/activate(var/mob/living/carbon/mob,var/multiplier)
	mob.radiation += (2*multiplier)

**Comment by Arthurdentist** [comment]
I could possibly use it but im not sure it would really add anything to any of these symptoms in particular.

Vox Pox straight up turns you into a vox, there ain't many ways to make that more severe and Delightful Syndrome works pretty much how I want it too anyway, its just a better version of a pre-existing syndrome.

Maybe it could be incorporated in Chicken Pox? I am not sure, I don't think it really fits in there.
I had to play around with the probability values on that particular syndrome so that the symptoms weren't too frequent to prevent annoying chat spam. I think it is all fine as is.

**Comment by clusterfack** [comment]
It would have been a good thing to add to delightful syndrome, stronger symptom = more DD

**Pull request merged**
