### PR TITLE
adds hand pickaxe voucher

### LINKED ISSUE #16100: Hand Pickaxe appears in the Mining Vendor's prices list
@SonixApache  in #14028 you left the hand pickaxe in the prices list.

### PR DESCRIPTION
**Pull request by SonixApache**
Adds a voucher that can be exchanged at a dwarven mining equipment machine for a hand pickaxe. A voucher spawns in every xenoarcheologist locker.
Contains the same change as #16101, so also resolves #16100.
tested

🆑 
 - rscadd: Added a hand pickaxe voucher to xenoarch lockers. It can be redeemed at a mining vending machine.

### CODE REVIEW

**Comment by DeityLink** [comment]
Hold on what?
Are you giving miners a reason to break into the xenoarch lockers again?

**Comment by SonixApache** [comment]
If they're going to break into xenoarch, why not just grab a hand pick from the equipment closets in the first place? They're both locked.
This is basically so that scientists can authorize mineoarchs without too much hassle.

**Comment by DeityLink** [comment]
Why should scientists be the ones having a say in that though? I'd expect no less but a head of staff giving that kind of privilege. That looks really awkward. I've always been against the entire concept of mineoarchs so I'm against it.

**Comment by N3X15** [comment]
* Added [Balance] because something something breaking into xenoarch lockers?

**Comment by ghost** [comment]
I'd rather that the excavation system was overhauled so regular drills no longer have any chance to get any strange rocks and they get a negative red flavor text message so they'll finally, finally, FINALLY stop fucking mowing down even war digsites for 1/25th value in their quest to be an asshole. I understand they can get picks/hand pick from opening our lockers but it's too easy of a low-hanging fruit for them to just tear it up while they drill around.

**Comment by SonixApache** [comment]
No-go on this one.

**Pull request closed without merging**
