### PR TITLE
Jecties

### PR DESCRIPTION
**Pull request by kilozombie**
image

I found the mental picture of "jecties" being these sweet gelatin treats funny enough to make some stupid sprites for the meme.

Whether anything related to objectives even changes and whether this gets merged or not I don't care this was funny to make have a good day

jectie_large

Make 'em out of 5 cherry jelly and 10 sugar. Currently there's a 40% chance for greentext to appear on the jectie, but when (if?) stats.ss13.moe comes back, I'll shift the chance to be perfectly accurate for solo antag win rate.

:cl:
 * rscadd: Jecties!

### CODE REVIEW

**Comment by bathosbathtime** [comment]
I would like the recipe of cherry jelly and sugar to be somewhere in the OP.

**Comment by kilozombie** [comment]
Sure thing.

**Comment by MadmanMartian** [comment]
Are you able to update the wiki yourself? Or would you prefer somebody else to update it for you? Or would you prefer the recipe be ingame only?

**Comment by kilozombie** [comment]
I updated the wiki for the Poutine Expansion and should be able to handle it fine myself. Might even make it a slow-moving GIF between the red and green states to get all fancy.

**Comment by MadmanMartian** [comment]
That sounds very fancy indeed

**Comment by MadmanMartian** [comment]
Group Jectie when?

**Comment by kilozombie** [comment]
Might do some kind of group jectie, gimme a day to decide

**Comment by Kurfursten** [comment]
13 bites is a lot

**Comment by kilozombie** [comment]
jectie_group

I made a 64x64 sprite for group jecties with 4 states (Jectie Major, Jectie Minor, Crew Minor, Crew Major) but don't really know what to do with it.

**Comment by SonixApache** [comment]
the tea is a nice touch

**Comment by SonixApache** [comment]
update the darn wiki

**Comment by kilozombie** [comment]
@SonixApache 
image

**Comment by SonixApache** [comment]
CTRL+F'd yesterday, didn't see anything, guess I've got brain problems🙂

**Pull request merged**
