### PR TITLE
tgui TEG

### LINKED ISSUE #24910: TEG interface displays wrong pressures for the hot side except right after being opened
The title isn't quite right but it's already too long
For some reason, the TEG interface is correct right after you click the TEG, but the inlet and outlet pressures for `circ1` are backwards every time it updates without you clicking it. This happens despite the same proc being called to update the interface in both cases.

### PR DESCRIPTION
**Pull request by DamianX**
Another `html_interface` falls

f5xlaRCoak

fixes #24910

:cl:
 * tweak: Changed the user interface for the thermoelectric generator to TGUI.

### CODE REVIEW

**Comment by Exxion** [comment]
Does this happen to fix #24910? I see TGUI handles updating differently, and that's a timing issue

**Comment by SonixApache** [comment]
`
    tweak: Changed the user interface for the thermoelectric generator to TGUI.
`

**Comment by DamianX** [comment]
I'm not sure what was going on with regards to that issue but I took that screenshot after I let it run for a while, and the inlet pressure is higher than the outlet pressure as expected, so I guess it's fine?

**Comment by Exxion** [comment]
I'm not really sure why I never updated that issue to explain what was going on, but if memory serves, the problem was that the TEG updated its UI after it moved the gases from its inputs to its outputs, but before the pipenet subsystem equalized its inputs and outputs with their respective pipelines
Both the hot and cold side were wrong but it was more obvious on the hot side

**Comment by DamianX** [comment]
I see. It should be easy to update the UI whenever we want rather than let the TGUI subsystem do it every .9 seconds or whatever that is.
What's the proc that does the equalizing?

**Comment by Exxion** [comment]
As long as it updates independently of the pipenet, it should be fine. Excepting lag, there's no delay between those events.

**Comment by DamianX** [comment]
Then it should indeed be fixed, because it does update independently of the pipenet.

**Pull request merged**
