### PR TITLE
Adds interior hallway to Defficiency Tradeship

### PR DESCRIPTION
**Pull request by Probe1**
The original design was created before Hellish ZAS was set to default.  There is now an undue burden on players created by the depressurization from accessing the trade ship.

Before
image

After

nqmfll

Closes https://github.com/d3athrow/vgstation13/issues/12606

:cl: 
* tweak: Deff Tradeship no longer requires a spacewalk between the Outpost and the Ship.

### CODE REVIEW

**Comment by PJB3005** [comment]
> The original designe was created before Hellish ZAS was set to default. 

Sure about that?

**Comment by Probe1** [comment]
Yes.  I created it before the server started using Hellish ZAS by default.

**Comment by JustSumBody** [comment]
HE'S BACK

**Comment by Probe1** [comment]
oh gosh

**Review by PJB3005 — APPROVED** [review]

**Comment by Exxion** [comment]
I'm about 95% sure that Hellish has been the default since LONG before you did that. Most people just didn't know.

**Comment by Kurfursten** [comment]
They're saying that the pot goes out the door now due to ZAS. I used to play trader a lot shortly after Probe added trade shuttles and that definitely never happened to me, so either reports are wrong or we've upped the ZAS.

**Comment by Sprok0** [comment]
ZAS was fixed to pull things semi-recently, which is what would cause that.

**Comment by Intigracy** [comment]
That's the only change that would have caused it and is probably what he's
referencing.

**Comment by kilozombie** [comment]
Looks really good.

**Pull request merged**
