### PR TITLE
Posibrain pacification

### PR DESCRIPTION
**Pull request by MadmanMartian**
Addressed #20637 #11896

The absolute worst way of approaching this, through enforcing roleplay via code. 

This makes it so posibrains can not do harm, rather than have a roleplay rule to follow of do no harm.

### CODE REVIEW

**Comment by Intigracy** [comment]
Even while inside cyborgs, with their own laws?

This is atrocious.

**Comment by SirSkeleto** [comment]
>making spiderbots entirely useless

no, thanks

**Comment by Lunstra** [comment]
Just change the text to "above all else do not harm your crew" then you can still slap them in mechs to fight mobs and they can defend themselves against mobs if ripley mining etc while being "safe" to put in mechs cause they still cant robot uprising against the crew, and nothing currently stops them being useful by being in a clarke or odysseus and being roboengi/medic, heck you could put them in a gygax with tasers to make them robosec too.

**Comment by Intigracy** [comment]
Or just make them able to be synced to an AI's laws / uploaded to directly with sync turned off.

**Comment by Hoshi-chan** [comment]
This is absolute garbage.

But, if you do merge this, why not make it so that you can emag a posibrain to remove its inability to harm, or make it exclusively loyal to the syndicate, or auto-subvert any borgs it's placed into.

At least then there's a way around it, and a new way for tator tots to antagonize people.

**Comment by ghost** [comment]
I don't like this one. Personally I think we just need to change the "Above else, do no harm" to "Do not harm the station or the crew" or something similar. This just allows them to 'fight' things in mechs or spiderbots.

The other option is just to remove them from being able to go inside mechs. It's sort of bad anyway, you can't take them out once they're in, they're probably buggy as hell. I don't know, but the idea that the admins decided that because the text says "do no harm" you cant even attack a simple mob is ridiculous.

**Pull request closed without merging**
