### PR TITLE
Pass on minimum player counts for gamemodes

### PR DESCRIPTION
**Pull request by ghost**
This is up to discussion, mostly value-tweaking !
- Add an explicit comment to gamemodes.dm. We do NOT want required_players to be a smaller required_players_secret, since it BLOCKS the gamemode playing completely. This is a failsafe, not a population control
- Apply that change to many gamemodes

Population changes pass and reasoning : 
- Borer from 10 to 20 players. Low-pop does not benefit from an antagonist that can literally reproduce (getting more antagonists into the round) and otherwise fuck shit up quickly while being ridiculously hard to get rid off without taking players out of the round
- Traitor-Chan from 10 to 15. A Traitor and Changeling mix needs more players to deploy seamlessly, especially since the Changeling will start taking people out of the round quickly
- Cult from 15 to 20. Gamemode relies on converting non-antags, so we need a significant pool of non-antags. The station should also be reasonably staffed for what is about to happen (looking at you, Security and Command)
- Malfunction from 15 to 20. Significantly reduces the chances of AIs without Cyborgs (it's rare to not have Cyborgs with 20 players at least) and the station needs to be decently staffed for the crew to have any chance (otherwise the AI might as well just shock every door and call it a day
- Mixed from 25 to 30. It's antag-boogaloo, the gamemode. We want a fully staffed station, WITH space for non-productive antag teams (possibly upwards of 10 antags) to withstand this
- Nuclear from 25 to 20. Putting it at the same level as Cult, plus Nuke Ops don't convert anyone, they just shoot through to get their objective
- Revolution from 25 to 20. Precisely same reasoning as Cult
- Traitor from none to 5. One starting Traitor is fun to absolutely no-one, might as well play Extended or hope for AutoTraitor (which can still trigger at minimum pop since it creates Traitors as it goes)
- Ragin' Mages from 15 to 30. No, we don't want to send multiple Wizards to a station that isn't even fully staffed. This is a magical apocalypse, so we need a fully staffed crew ready for anything

Any gamemode not mentioned above has seen no changes

### CODE REVIEW

**Comment by dylanstrategie** [comment]
Compile is working, Travis is having a giggle, that is all

**Comment by IratePirate** [comment]
The best thing you could do is make the threat and number of antags in a round based on the player count. For instance you could have 3 man nuke op squads on 15 players, 4 for 20 and 5 for 25, 2 Blobs above 40 players, less starting cultists during lowpop etc.. Just food for thought.

**Comment by AutismSpider** [comment]
we get two blobs when the player count is 50+ right now

If any thing we would lower it to 35 or 40+

**Comment by Probe1** [comment]
>Traitor from none to 5. One starting Traitor is fun to absolutely no-one, might as well play Extended or hope for AutoTraitor (which can still trigger at minimum pop since it creates Traitors as it goes)

so instead of a round maybe being boring it's guaranteed to be boring

>Nuclear from 25 to 20. Putting it at the same level as Cult, plus Nuke Ops don't convert anyone, they just shoot through to get their objective
>Malfunction from 15 to 20. Significantly reduces the chances of AIs without Cyborgs (it's rare to not have Cyborgs with 20 players at least) and the station needs to be decently staffed for the crew to have any chance (otherwise the AI might as well just shock every door and call it a day

I see you argue that there won't be enough crew to handle malf here, then argue that there'd be enough crew to handle nuke ops.

>Borer
shouldn't be re-added.

The only one that really makes sense to me is increasing traitor-ling.

**Pull request merged**
