### PR TITLE
Fixes items not being removed from inventory slots on bite-harm intent

### LINKED ISSUE #32620: Unable to take items out of storage with harm-bite intent on
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
[bugfix]
# Revision
9335b52b65476bac3da7d71aba0ad5667d7084b6

# Description
Items unable to be interacted with other than right clicking when selecting them in a storage box/backpack/etc type menu with harm and bite intents on.

# Steps to Reproduce
* Select harm and bite intent
* Have a backpack or similar on
* Put item in
* Try to take the item out

# What you Expected
Item in hand

# What Actually Happened
Nothing happened

### PR DESCRIPTION
**Pull request by Hinaichigo**
[bugfix]
This fixes #32620, by making it so clicking an item in a storage slot on bite-harm intent will remove it from the storage slot properly. Also moved some code around to a nicer place.

:cl:
 * bugfix: Items can be removed from storage slots while on harm-bite intent.

### CODE REVIEW

**Comment by adacovsk** [comment]
Can you look into not being able to bite when you have no arms/arrested? #32206

**Comment by Hinaichigo** [comment]
I'll take a look at it.

**Comment by WindowsErrors** [comment]
I think that one's because biting is a harming action like any other, it's the same reason why kicking requires an empty hand

But if you _really_ want to take a look at it, look [here](https://github.com/vgstation-coders/vgstation13/pull/23255), just remember that there's a very good reason why this wasn't merged

**Comment by Kurfursten** [comment]
why move it out of its own file?

**Comment by Hinaichigo** [comment]
I was thinking it'd be easier for people to find if they want to add new functionality to those procs for `obj`, unrelated to breakability. And I was thinking all the vars for `obj` should be in the same file.
Maybe I should put it back or at least put the breakability-related procs back into their own file?

**Comment by Kurfursten** [comment]
Yes, I think having the breakability procs in their own file is better; the system is large enough that it warrants its own file in the same way we split off human_defense from human etc

**Comment by Hinaichigo** [comment]
That makes sense. I put it back in it own file.

**Comment by Kurfursten** [comment]
By the way, putting your name on a system is oldcoder (like, pregoonleak) brain. The only time you need to label the source of code is if you used something from another codebase and are including the notification for licensing.

If you hang around and code a lot, your tentacles will eventually be in everything anyway.
image

**Pull request merged**
