### PR TITLE
Overlay fixing and atmos magboots.

### LINKED ISSUE #2406: Magboots icon clipping through hardsuits
They should either be above the hardsuit layer or have the extra pixels on the side trimmed off. Or maybe they just shouldn't be thigh highs compared to all other footwear in the game

untitled
.

### PR DESCRIPTION
**Pull request by ComicIronic**
Special magboot reskins for atmos techies. Feel special today!
Magboot toggle code made more sensible.
Humans now properly update to hide and show icons that are hidden by other equipped items.
I would like to unite hidden flags at some point, but the current system works fine enough.
Fixes #2406.
(NB: atmos magboot sprites shamelessly stolen from custom_items.dmi)

### CODE REVIEW

**Comment by Boxe** [comment]
what do the boots look like

**Comment by ComicIronic** [comment]
These boots

**Comment by d3athrow** [comment]
conflicts

**Comment by ComicIronic** [comment]
No conflicts

**Pull request merged**
