### PR TITLE
[Sprites] fireplace revamp

### PR DESCRIPTION
**Pull request by DeityLink**
fire

The flames and glow around it are an overlay so it shines really well in the dark. On top of that the lighting has been rescaled so it doesn't jump around unrealistically. The sprite also update a bit more frequently so transitions are much smoother.

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Did you update the sprite with the stockings?

**Comment by DeityLink** [comment]
Of course. I had to since the sprite is now 64x64.

spr

**Comment by Exxion** [comment]
Holy fucking shit you're not dead

...I probably should have said this on one of your other open PRs instead

**Comment by Ephx1** [comment]
> A three dimensional object on a 2D object

My eyes hurt

**Comment by clusterfack** [comment]
You liked the fireplace poster better?

Also it'd be nice if it had 4 directional sprites

**Comment by Zth--** [comment]
It's like 100x times better

**Comment by Ephx1** [comment]
It certainly looks nicer, but it looks wonky on a wall.
Like it's sitting exactly on top rather than attached to.

**Comment by LordMyroc** [comment]
Walls themselves look pretty wonky when you think about it. Perspective is all over the place in this game.

**Comment by 9600bauds** [comment]
I like this very much

**Comment by ghost** [comment]
10/10

**Comment by Shadowmech88** [comment]
:+1:

**Comment by ghost** [comment]
@DeityLink I love you.

**Comment by DeityLink** [comment]
@Exxion Don't feel bad, I put a decent amount of efforts into that PR

firechange

fireprogress

**Comment by SangriaMonkey** [comment]
merge when

**Comment by ghost** [comment]
Ghetto bar should start with a fireplace honestly

**Comment by DeityLink** [comment]
Or a campfire to fit the theme. I might redo those sprites as well later.

**Comment by Shadowmech88** [comment]
What about going the middle ground and making it a fire pit?
Nicer than a campfire, still not as nice as a fireplace.

**Comment by DeityLink** [comment]
The current campfire sprite looks like a firepit so it's already basically one. I just think it can be drawn a bit better.

**Comment by 9600bauds** [comment]
A fireplace is not a very ghetto thing

Doesn't the captain's office already start with a fireplace

**Comment by Shadowmech88** [comment]
The captain's office does currently start with a fireplace.

**Comment by Zth--** [comment]
I think it should provide 50% more lighting, It's kind of weak

**Comment by clusterfack** [comment]
Doesn't that make it cozier?

**Comment by DeityLink** [comment]
@Zth-- what @clusterfack said. If you keep feeding it planks to keep it bright it shouldn't be an issue.

**Comment by FudgePucker** [comment]
Why not have the ability to make fireplaces out of bricks?
You have a reaction to make clay (pots), just add one for bricks.
You could also throw bricks though the IAA's office window after he lays you off.

**Comment by DeityLink** [comment]
@FudgePucker I have plans for that, but that'll wait after the freeze.

**Comment by ghost** [comment]
Am I reading correctly that you didn't remove the old fireplace sprites?

**Comment by DeityLink** [comment]
The old fireplace sprite are still in atmos.dm . Think I should remove them?

**Comment by ghost** [comment]
Probably, if they're unused.

**Pull request merged**
