### PR TITLE
buttbots now have an incrementing chance to explode when talking

### PR DESCRIPTION
**Pull request by MadmanMartian**
:cl:
*rscadd: Buttbots now explode if they say too many things

### CODE REVIEW

**Comment by Zennyization** [comment]
Sucking the fun out of the game again, why do people hate fun?

**Comment by MadmanMartian** [comment]
Honestly this PR was done to give @Reviire a step-by-step guide on how to make a PR. Buttbots have been known to turbocrash the server in large amounts however, so what would you suggest @Zennyization ?

**Comment by Reviire** [comment]
<3

**Comment by yclatious** [comment]
Dont dunk the bots of butt by making it a 50% chance when they speak 10 bloody times, at most 1% per talked, if the issue is buttbots crashing the server, find another way other than blatantly biased shit that makes it useless, prob(5*times_talked) means that if they talk 20 times, probablility of 100% explosion, if my headache ridden brain isnt fucking me up.

A buttbot that talks 20 times is a useless meme machine. Either have it check at 100 spoken lines to explode or reduce chance to 1% if you are that intent on killing fun but atleast do it so it can actually do something.

**Comment by Zennyization** [comment]
@MadmanMartian The issue is I just dont see why this feature needs to exist. You say there is an issue with them crashing the server. That's not an issue with the Buttbots, why implement a stop-gap "solution."

**Comment by MadmanMartian** [comment]
That is a very fair observation, I'll work on optimizing the buttbots if possible first, then we'll see if people are still asking for buttbots to have a certain limitation

**Pull request closed without merging**
