### PR TITLE
Seeds have initial names

### PR DESCRIPTION
**Pull request by clusterfack**
To help with vending machine code

### CODE REVIEW

**Comment by Exxion** [comment]
What about modified seeds?
... Actually never mind. At this point, probably the best solution to any problems related to inserting seeds back into the MegaSeed Servitor is just removing the ability to do that. There are at least two machines in the room that do a better job of it anyway.

**Comment by clusterfack** [comment]
How do you get the name for inserting modified seeds into a vending machine? It likely takes the name directly from the seed doesn't it?

This is fixing a problem resulting from the fact that I made vending machines use initial() instead of creating a new object to collect the name of every object at roundstart.

**Comment by Exxion** [comment]
Oh, you're probably right
I maybe shouldn't try thinking at 5 AM

But I bet inserting modified seeds into the MegaSeed Servitor breaks them in other ways anyway

**Comment by DeityLink** [comment]
:+1:

**Pull request merged**
