### PR TITLE
Dynamic mode NTAW2: lower costs for Nuke Ops

### PR DESCRIPTION
**Pull request by ShiftyRail**
Lower the cost, and threat requirements, or midround new cops. 
This means that more nukies will spawn, at a lower population requirements.

Do note that by making the threat requirement lower, not only does this increases the chance of seeing nukies, it also means they are likely to spawn "alone". Currently, at 15 pop (for instance), it takes 80 threat for dynamic mode to consider sending nukies.

But with 80 threat, the nukies might come after a ninja, several traitors, or a wizard. Now, it takes 40 threat for dynamic mode to consider sending nukies. Since nukies cost 30 threat, it is very likely that this will be the only midround antag sent.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
How does midround nukies populate the team? From ghosts or is a solo nukie possible?

**Comment by ShiftyRail** [comment]
From ghosts. Nukies team size scales with population.

**Comment by PavelCIA** [comment]
can you add a check that there must be a captain/HoP/HoS for the nukies to spawn so they dont just kill the jobbie CMO for the disk?

**Comment by ShiftyRail** [comment]
@PavelCIA I prefer not to add those kinds of hard checks to the game. Nukies naturally happen in rounds with more populations, and a captain already boosts their chances of spawning.

**Comment by Kurfursten** [comment]
Conflicts

**Pull request merged**
