### PR TITLE
Detective Revolver Modification Changes/Nerfs

### LINKED ISSUE #34628: The Detective Revolver can fire 357 without a chance of breaking
In the code, screwdriving the detective revolver to accept 357 ammo is supposed to give it a chance of exploding. This, to my knowledge, does not happen and as far as my google skills can tell you can't fire 357 out of a 38 anyway. 

More importantly though, there's a detective conversion kit for this item to make it 357 without a chance of failure that's flat out useless due to the fact that you can get an identical item from a toolvend. It also lets seccies get the equivalent of a traitor revolver pretty damn fast but the det revolver is already pretty strong so I'm not sure how much difference it'd make in a combat scenario. 

[bugfix]

### PR DESCRIPTION
**Pull request by jwhitak**
@west3436 told me to open my own so oh boy here we go.

As an aside, further modifications from the following should be done in a future PR, such as changing explosion chance %s, changing what the traitor kit can do, etc.

## What this does
Changes detective revolvers so that they follow the following behavior:
### Unmodified
* Can load .38
* Can fire .38
### Modified with Screwdriver
* Can load .38 and .357
* Can safely fire .38
* Can fire .357 but with an explosion risk of 10%-60% based on bullets in gun
* The explosion will actually cause an explosion sound and show a visible message
* The gun will be deleted
### Modified with Traitor Kit
* Can load .38 and .357
* Can safely fire .38 and .357

## Why it's good
Fixes a 10 year old bug, causes a flame war, convinces detectives to use their regular knockdown bullets when stopping crime, closes #34628.

## How it was tested
image
image
bang bang bang BOOM (picture was me exploding it before i even could finish loading the gun)

## Changelog

:cl:
 * bugfix: Detective revolvers can now explode when improperly modified.

### CODE REVIEW

**Comment by Theophrastus1** [comment]
If I could suggest something that might pacify the rabid det players, consider making the resulting explosion damage delete the hand used to fire it akin to when someone attempts to fire a DNA-locked lawgiver

That way it works similarly to another gun we have that was added later on, as well as giving a resulting "cost" for any fears players might have that someone is just gonna forcibly blow up their revolver every round

**Comment by Kromkar** [comment]
> If I could suggest something that might pacify the rabid det players, consider making the resulting explosion damage delete the hand used to fire it akin to when someone attempts to fire a DNA-locked lawgiver
> 
> That way it works similarly to another gun we have that was added later on, as well as giving a resulting "cost" for any fears players might have that someone is just gonna forcibly blow up their revolver every round

Or the thing someone else suggested where it damages the gun and you need to repair it

**Comment by djkramer123** [comment]
C'est la vie, an end of a era. To repost what I said elsewhere:
> instead of the revolver just getting qdel'd it should break and have to be fixed through some number of steps 
deleting things is lame
i.e screwdriver to fix the barrel, welding tool to fix the cracks etc.

>bonus points if there's a ghetto way to quickly fix it, like wrapping it up with cable coils or something that then actually risks destroying it completely if it misfires again

Would be worth looking into for a future pr regarding it, and would be better than just blowing off someone's hand like the lawgiver does imo.

**Comment by nervere** [comment]
> If I could suggest something that might pacify the rabid det players, consider making the resulting explosion damage delete the hand used to fire it akin to when someone attempts to fire a DNA-locked lawgiver
> 
> That way it works similarly to another gun we have that was added later on, as well as giving a resulting "cost" for any fears players might have that someone is just gonna forcibly blow up their revolver every round

Destroying your hand is usually a benefit for the subset of extremely annoying people that enjoy being uncuffable.

**Comment by SonixApache** [comment]
i don't see why the other one had to die for this but this ancient bug has to go either way

**Comment by ErrorsWindows** [comment]
I propose that if the detective gets a magnum revolver kit then the cargonians and redshirts get [the full auto glizzy switch](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/projectiles/guns/gun_parts.dm#L26) that has also been left unused in the code for years

https://github.com/vgstation-coders/vgstation13/assets/122955989/aefa7e36-8aaa-4aa8-bc4a-6ba26a54bf8f

**Review by west3436 — APPROVED** [review]

**Comment by Blithering** [comment]
Rabid det player reporting in, this seems fine, although as it stands there's no reason not to screwdriver your revolver roundstart just in case.
Maybe have the default able to load both with the 10-60% explode chance on firing .357, and have screwdriver ghetto upgrade give up .38 loading in order to reduce the explosion chance to a flat 10%?

**Comment by jwhitak** [comment]
You can modify your revolver round start if you want to, with no clear mechanical drawbacks.

Keep in mind this is an illegal modification to your firearm and makes it an illegal weapon per Space Law Code 4. You can't tell the difference between a gun modified wtih a screwdriver and a gun modified with an illegal traitor-kit. Might be enemy contraband, might be a makeshift weapon... either way, I hope the Hoss gave you permission to possess that gun. After all, if any other security officer notices? You're gonna be brigged for five-ten minutes, have your gun confiscated, and be suspected as a traitor for the rest of your shift... If they know their Space Law (they don't).

**Comment by SonixApache** [comment]
> Keep in mind this is an illegal modification to your firearm and makes it an illegal weapon per Space Law Code 4. 

There is nothing in space law that says that you cannot modify a weapon, else bartenders that saw off their shotgun would also get the book.
You could try to argue that it falls under "crafted weapons", but the weapon is standard-issue and not crafted and there's usually a good justification for the modification. You could argue that it is a "weapon or explosive with high potential for lethality" but that gets waved off by the 'departmental access' part of that code.
You could book a detective with a modded gun with negligence or manslaughter if they break a window or pop a bystander by accident with their souped-up gun, but otherwise, it's perfectly legal to modify the gun.
It's a violation of SOP, but nobody cares about SOP and incompetence is still not a crime.

**Pull request merged**
