### PR TITLE
black food coloring recipe

### PR DESCRIPTION
**Pull request by gurfan**
combine colorful reagent and carbon

:cl:
 * rscadd: Black food coloring can now be made by mixing carbon and colorful reagent.

### CODE REVIEW

**Comment by smalIboss** [comment]
fuck yes

**Comment by robintime** [comment]
stop i was about to do this

**Comment by gurfan** [comment]
i am first

**Comment by ghost** [comment]
i wanted to do this but with grinding crayons

**Comment by d3athrow** [comment]
based

**Pull request merged**
