### PR TITLE
Revert "Improves A* pathfinding with One Weird Trick"

### PR DESCRIPTION
**Pull request by Probe1**
Reverts d3athrow/vgstation13#13301

https://github.com/d3athrow/vgstation13/issues/13307

### CODE REVIEW

**Comment by 9600bauds** [comment]
firefox_2016-12-26_01-20-06

**Comment by Probe1** [comment]
What a test merge that was.

**Comment by Iamgoofball** [comment]
i still don't get why it broke

**Comment by Iamgoofball** [comment]
i blame the { in the file

**Comment by Probe1** [comment]
I don't even know why it's using ``` { } ``` .  

But on the other hand I don't care because it works well enough not to break and I have things people want me to do.  

If you want to port us a better A* file plus that nice optimization (and it doesn't shit the bed for unknown inexplicable reasons) I will be indebted to you.  I gotta do some mapping then code a shocky net gun then make sure antag datums get going and a long boring list of other things people like.

**Pull request merged**
