### PR TITLE
Adds Piccolyn

### PR DESCRIPTION
**Pull request by Kurfursten**
If you have less than 10 brain damage, aren't dead/unconscious, and have 90% or higher health with Piccolyn in your system, you will thank a random doctor that you can see for the dose, at which point the piccolyn goes away.

Honestly, I didn't even test this. I'll do that in a bit.

🆑 
* rscadd: Adds Piccolyn, a chemical made from copper, tungsten, and fluorine. It causes patients to thank their doctors.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Also because the list is just the TF2 "healed by medic" list. I realized when compiling this it would just make it more common though.

If it makes you feel better, imagine one has a Brooklyn accent and the other has a Texan accent

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Thanks

**Comment by SonixApache** [comment]
thanks doc

**Comment by Kurfursten** [comment]
By the way, the medicine decides you are a doctor if you are wearing a medHUD. Let me know if you think of a better criteria. I'd rather not use mind's assigned_job.

Medbelt is another good one since I never see anyone nigger those, assistants usually preferring their plastic bags

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I have literally welded medbay's plasticflaps to make myself a plastic bag before since medbelts suck so hard

**Comment by beesil** [comment]
Thanks doc

**Comment by Blithering** [comment]
Maybe instead of medhud, have it check for medical jumpsuits?

**Comment by Hoshi-chan** [comment]
Can you make it alter the color palette momentarily when it procs the effect? You know, like the noir gene, but just for a second?

Also, please don't forget to make the code check for the presence of hard-working medical borgs who will spike all meds with piccolyn once this is merged.

**Comment by Kurfursten** [comment]
Tomorrow I am literally running a 5K

But perhaps Sunday??

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It's already good2go if you ask me

**Comment by SonixApache** [comment]
What needs doing? Just testing?

**Comment by Kurfursten** [comment]
Needs:
* To check for borgs in addition to doctors
* Identify doctors by uniforms instead of by medhuds (I plan to make a new helper proc is_wearing_any which will check against a list instead of just one individual item like is_wearing_item)
* Testing

**Comment by Kurfursten** [comment]
Finished and thoroughly tested. Wow, this has to be the most elaborate meme ever with 2 whole new helper procs.
* Removed duplicate thank lines
* Added more name-based thank lines to increase the likelihood of referring to the thank target by name
* Borgs eligible to be thanked. Instead of being referred to by first name, as they lack one, they will have an endearing name like "robot", "borg", or "autodoc".
* Dead or unconscious targets will not be thanked.
* Humans are thanked on the basis of wearing any medbay uniform, even virologist or geneticist outfits.

**Pull request merged**
