### PR TITLE
removes roundstart candy machine, oven, and cereal maker from the kitchens

### PR DESCRIPTION
**Pull request by MadmanMartian**
For some strange reason mapcleaner didn't take bagelstation into account

'Goof kitchen' machines not removed:

- Deep fryer, as it actually uses reagents
- Grill, as it only adds a flavourtext and a color transformation matrix to the object on it
- Ice cream machine, as this can be reworked to require certain reagents, and lets you be an ice cream parlour.

The ones that are removed had a fair amount of complaints associated with them, mainly them being associated with 'shit chefs' making deep fried flour bag cereal donk pocket pie cereal cake

~~They can still be built via RnD~~ Turns out they were so ill-planned, they don't even have circuitry or internal parts.

**Related PRs to the kitchen rework:**

- #16820 Reworks the Ice cream machine to contain and use resources
- #16812 Removes the weird and wonderful goofkitchen machines
- #16829 Adds an actual oven

### CODE REVIEW

**Comment by yclatious** [comment]
The hero we need but dont deserve

**Comment by Cyadox** [comment]
Delet goof :ok_hand:

**Comment by sonime** [comment]
[Angry deadpoo sounds]

**Comment by ghost** [comment]
You say the ice cream machine, the worst offender, can be reworked instead of removed. Why can't these be reworked too?

New chefs being shit isn't a reason to remove muh dead human lung cereal. They will be shit anyways. The only one of these I wouldn't mind removing is the candy machine because ALL the things it can make have awful sprites.

**Comment by sonime** [comment]
Will there be a new way for chefs to make donk pockets to make up for the loss of the oven?

**Comment by MadmanMartian** [comment]
That can be arranged, yeah

**Comment by sonime** [comment]
Then make it so.

**Comment by MadmanMartian** [comment]
Make a pastry using the rolling pin, flour, etc.

Take a knife to it, cuts into 3 raw empty donk pockets.

stuff ingredients into raw donk pocket.

Put in microwave (Would prefer oven but that's part of the rework that is the reason this PR is being made) to get [ingredient] donk pocket

**Comment by Blithering** [comment]
5 flour, 5 [any chemical] 1 paper sheet in a microwave maybe?

**Comment by SonixApache** [comment]
what if we turned the microwave into a general purpose kitchen heating/cooling appliance

**Comment by sonime** [comment]
Sounds like some goofchem, boyo.

**Comment by Praecordia** [comment]
i like having the shit chef machines more tbh
makes good chefs stand out

**Comment by Chazach** [comment]
but why are silly machines so offensive to """"""serious chefs"""""" that they are relegated to science to never be seen again? shitty meme foods will always exist as well as shitty chefs, now they will just have shorter and less absurd names and just be plated burnt messes and deepfrying even more things

**Comment by ghost** [comment]
We're just gonna see more deep fried ambrosia vulgaris leaf, grilled bunch of grapes and bread slice on a plate sandwiches on a plate.
Then they'll want to remove sandwiches.

Really, if the food having pretty names is so important to you, the proper solution would be to make pretty foods desirable for the chef to make. But food is mostly just a nutriment packet, a couple of mild healing chems at most. Even bartender drinks and botanist plants do more interesting stuff. No wonder some chefs don't care.

**Comment by MadmanMartian** [comment]
Because I'm working on reworking them so that you can still have the silly stuff, it's just not out of thin air.

**Comment by AutismSpider** [comment]
if you want silly names just use pen on the food you  dumb fucks

**Comment by ghost** [comment]
If you're reworking them already, why remove them now, only to have to re-add them later?

**Comment by EenKogNeeto** [comment]
I play a lot of chef and still think removing them is stupid. Locking them behind R&D is akin to just removing them forever. Case and point: How often do you see a confectionator?

**Comment by Kurfursten** [comment]
Are you sure you can build goofkitchen machines at R&D? They don't have circuits or components listed in their New() in cooking_machines.dm if so, besides the confectionator

Seems more like a cargo thing anyway unless you're adding upgrades.

**Comment by Jubisloviu** [comment]
@sonime 
you can already cook Donk Pockets on the microwave, it`s just 5 flour + 1 faggot.
/datum/recipe/donkpocket
	reagents = list(FLOUR = 5)
	items = list(/obj/item/weapon/reagent_containers/food/snacks/faggot)
	result = /obj/item/weapon/reagent_containers/food/snacks/donkpocket

**Comment by ultraplen** [comment]
I generally like PRs that clean up round-start content, and make gimmicks require more effort, but in this case I'd rather see all the machines reworked. If it's between this and no change though, 👍🏿

**Comment by agentofzog** [comment]
Don't you take away my deep fried diona nymph cereal motherfucker.

**Comment by MadmanMartian** [comment]
after my rework is done, then we'll do mapchanges

**Comment by chesse20** [comment]
i like the machines though they are so funny

**Comment by MadmanMartian** [comment]
trying to preserve the funny, don't worry

**Pull request closed without merging**
