### PR TITLE
Fix traitor reaganomics

### PR DESCRIPTION
**Pull request by ShiftyRail**
Fix the bug regarding traitors (1 and only 1 at roundstart)

[bugfix]

:cl:
- bugfix: There should be more than one and only one roundstart traitor now

### CODE REVIEW

**Comment by ShiftyRail** [comment]
it appears from experimental evidence that the problem is bigger than that

**Comment by ShiftyRail** [comment]
Now entirely fixed and tested

image

The issue is probably that I wanted to condense the two `if`s back when I originally coded this and I didn't test it again after. Who knows! At any rate, this is now [100%]

**Comment by PrimeDSS13** [comment]
"""""""100% tested""""""""

**Comment by ShiftyRail** [comment]
Well it now is

**Pull request merged**
