### PR TITLE
Autocall Revert

### PR DESCRIPTION
**Pull request by bathosbathtime**
The auto shuttle call apparently breaks the game if an admin uses admin recall on it. I quickly put together this PR to revert it, but I just went into #32751 and undid the changes. Testing it now, going to take a while to test recalling and calling in different ways.

## What this does
reverts the changes made in #32751

## Why it's good
Quick and dirty way of removing a game stalling bug.

## Changelog

:cl:
 * rscdel: Removed Shuttle Autocall

### CODE REVIEW

**Comment by Hinaichigo** [comment]
I never was fond of the recall in the first place.

**Comment by bathosbathtime** [comment]
From what I determined in testing, the autocall proc itself that the shuttle uses is unrecallable by any means. This makes sense as it was originally used only when it because physically impossible to call the shuttle in game without admin intervention. I'm going to keep this PR up because I don't like the original change but if you wanted to keep it you could either change the autocall proc to be recallable or make a separate autocall for the shift "ending" that can be recalled to fix the issue.

**Comment by adacovsk** [comment]
why don't you just fix it yourself?

**Comment by bathosbathtime** [comment]
Because I don't like it? I explained that already please learn to read.

**Comment by bathosbathtime** [comment]
Locally tested calling normally, admin recalling, and leaving the game on for 40 hours straight. The shuttle no longer autocalls on local testing.

**Pull request merged**
