### PR TITLE
Antagonists Refund Threat

### PR DESCRIPTION
**Pull request by Kurfursten**
When an antagonist is completely destroyed, not cyborgified or perma'd, they can refund threat to the round. This threat will never go over the round's starting threat_level. This is important because, say Vampires rolls 3 vampires with 20 threat_level, the threat cannot regenerate up to 32  (20-18+10+10+10). This also means if a madmin slams the sleeper agent button repeatedly it will not cause threat inflation.

**Skip to bottom for TL;DNR**

**Modes and Costs**
*Unaffected: Destroying these antagonists refunds nothing*
* Team Modes: Revhead/Revolutionary, Blood Cultist, Nuclear Operative, Malfunctioning AI/Malfbot, Blob Overmind/Cerebrate, Vox Raider, Mad Monkey
* Pseudoantags: Survivor, Crusader, Magician, Wizard's Apprentice, Greytide Leader/Greytider, Vampire's Thrall
* Responders: ERT, Deathsquad, Elite Syndicate Strike Team

*Affected*
**Traitor** - 10 threat per traitor destroyed
* Traitors can appear in two main ways: roundstart and midround/latejoin
* Midround and latejoin add (or convert) player to traitor at a time. Midround (converts an existing player) costs 10 and latejoin costs 5.
* Roundstart costs a flat rate of 10 no matter how many traitors are made. In an exceptional round with, say, 90 threat and 60 players, this could generate 10 traitors.  For threats under 60, no more than 1 traitor per 10 players, plus 1 (e.g.: 30 players 4 traitors).
* Traitors can be perma'd safely, and therefore are the least likely to be destroyed.

**Vampire** - 10 threat per vampire destroyed
* Vampires are only generated at roundstart (or with the stone mask).
* Like traitors, these cost one upfront lump cost of 18. Unlike traitors, they will not inflate past (players/10)+1. A typical highpop could have 3-4 vampires.
* Vampires are often tested in the chapel, and therefore the most likely to be destroyed.

**The Grinch** - Holiday only. 10 threat for Grinch destroyed.
* Grinches may appear as a roundstart or midround ruleset, costing 10. Only one appears.
* Grinches are rarely destroyed, and usually displayed as a trophy. This could change if the mode is refined.

**Wizard** - 5/20/40 threat per wizard destroyed
* Wizards appear in three ways: roundstart, midround (cheap), and midround (expensive)
* Roundstart wizards cost 30 and generate only one wizard. Destroying this wizard refunds 20.
* Ragin' Mages may fire midround with a variable cost:
* If roundstart wizard existed, a ragin' mage will cost 10. Destroying this wizard refunds 5.
* If roundstart wizard didn't exist, a ragin' mage will cost 50. Destroying this wizard refunds 40.
* Wizard bodies are sometimes preserved for medical experiments.

**Crazed Weeaboo** - 10 threat per weeb destroyed
* Crazed weeaboos appear as a midround or latejoin ruleset.
* Only one is created at the cost of 10 threat.

**TL;DNR**
Base refund value: 10 (Traitor, Vampire, Weeaboo, Grinch)
Double Agent: 5 (Bus only)
Wizard: 5/20/40 (depends on how much the wizard cost to generate)

🆑 
* rscadd: Completely annihilating a solo antagonist will now regenerate some of the round's threat.
* rscadd: If a mode is rolled by dynamic but no one applies, it will refund the threat.

### CODE REVIEW

**Comment by Killette2** [comment]
So I get to destroy antagonist for better odds of becoming an antagonist?

**Comment by Kurfursten** [comment]
More or less

**Comment by boy2mantwicethefam** [comment]
:s Valid secured DON'T GIB HIM put his body in our morgue and forget about him

**Comment by Kurfursten** [comment]
Traitor gang taking advantage of this to clone each other whenst?

**Comment by Killette2** [comment]
At least people might subconsciously ash vampires less, or more.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Wait... It wasn't already like this?

I thought this was the point of dynamic?

**Comment by Kurfursten** [comment]
Allow me to summarize
* threat_level is the max threat for the round, threat starts equal to threat_level and is spent on antags
* it never goes up currently but this is one of two PRs to change that
* the other PR would boost both threat and threat level, up to 100 (see #21276 )

**Comment by Kurfursten** [comment]
**New Feature!**

Now if the mode sends out apps for a midround ruleset and no one applies, it refunds the threat for the mode. No more wasted threat.

**Comment by Kurfursten** [comment]
Hoping that in the next 24 hours I'll clear conflicts and I have a great idea for threat logging so admins can see how it went up and down on the check antags screen

**Comment by MadmanMartian** [comment]
what's roid doing in here?

**Comment by Kurfursten** [comment]
There's no way to fix it, I get roid station lineendings on everything. If a PR gets conflicts there is absolutely no way to rebase without """updating""" roidstation (because it gets confused about line endings mid rebase not before or after you can't do config and then hard reset). It's just a copy of the latest roid.

Now when I rebase I'm going to have to pull down the latest roid again because the labor console got added. Roidstation is the bane of my personal existence.

**Pull request merged**
