### PR TITLE
Removes upper limit on volume pumps

### PR DESCRIPTION
**Pull request by Smedley8**
Removes the upper limit/sanity check on volume pumps so that supercanisters are now viable.

First PR so hope it isn't too controversial.

### CODE REVIEW

**Comment by brndd** [comment]
This has some consequences beyond canisters:

1. Default unupgraded waste setup can not clog anymore.

2. It uncaps a bottleneck with the TEG, which may or may not be intentional but is definitely a good limit on the TEG's power output, see https://github.com/vgstation-coders/vgstation13/pull/22680#issuecomment-491599028 for the reason why.

3. It allows you to infinite-pressurize the freshly buffed air pumps, which were balanced around the fact that they have limited capacity.

**Comment by DrSnips** [comment]
1. This is the opposite of an issue.
2. Fair enough but all engineering is just extra autism after 300k to the grid and the only thing that really cares about more power is the magic matter maker and rail guns.
3. Being able to fill a room with air quickly is a good thing but not so much if we have plasma in it. I think it's a net positive still.

**Comment by brndd** [comment]
>This is the opposite of an issue.

It is not. Roundstart setups are flawed by design. Engines don't start set up either, and neither should atmospherics. Waste being able to clog gives you a meaningful reason to upgrade it with a design that can't clog (or doesn't clog as easily), just like supply being badly bottlenecked by the pumps it's being fed by gives you a meaningful reason to upgrade that.

>Being able to fill a room with air quickly is a good thing but not so much if we have plasma in it. I think it's a net positive still.

Canisters of holding invalidate all other mechanics designed to refill rooms quickly, such as portable air pumps and the industrial vaporizer. Though if filled with infinite pressure, portable air pumps in their buffed state are even better for this than canisters, given that they have more volume and give you more precision for the room's target pressure without compromising flow rate.

And yes, like you said this also enables 300 gigapascal griffcanisters full of 1 K plasma.

&nbsp;

edit: and I forgot about this one

>Fair enough but all engineering is just extra autism after 300k to the grid and the only thing that really cares about more power is the magic matter maker and rail guns.

Autism can't be too easy or the payoff is diminished. Getting big numbers should require big effort. This goes for both atmospherics and engineering. Wrenching down a layer manifold and a handful of scrubbers is too little work for achieving infinitely large autism numbers, and wrenching down a bunch of volume pumps is even less work than that (because you don't need an autism cube). Big numbers should be something to be marveled at, not something that happens every round and can be done by any low-effect engineeringlet.

**Comment by FudgePucker** [comment]
Just set it so that the pressure gradient has an effect on flow rate at very high pressure diffrences.

Or you know, super pumps, the idea that everybody shit on.

**Comment by brndd** [comment]
>Or you know, super pumps, the idea that everybody shit on.

I don't think they were a bad idea. They're certainly on my mental list of atmos stuff to do Some Day. Though I would tie them in with engineering autism by making them use lots and lots of power, so there's an extra outlet to dump your 12 jiggawatts on.

**Comment by abernd** [comment]
Just make the maximum pressure dependent on the pressure delta across the pump. Being able to chain pumps in series to reach a higher ultimate pressure makes sense.  For example, having two pumps in series could reach 2X their current maximum pressure, and so on. 

Regarding supercanisters, there should be at least three methods to attain them currently. It's just a little more cumbersome than using scrubbers.

**Comment by brndd** [comment]
>Just make the maximum pressure dependent on the pressure delta across the pump. Being able to chain pumps in series to reach a higher ultimate pressure makes sense. For example, having two pumps in series could reach 2X their current maximum pressure, and so on.

Shit, that's not a bad idea. I think it may have some problems with setups where the pump's input is the same network as its output, but I reckon those could be worked out.

**Comment by SonixApache** [comment]
powercreep

**Comment by ValkyrieSkies** [comment]
Just add alternate versions with a higher limit then but don't use them in any roundstart setup so they require actual player initiative.

**Comment by DrSnips** [comment]
You would still have to interact with the round start setup to change the rates. Currently 3 clicks will "upgrade" the roundstart setup by making it just a normal pipe if you want to do the bare minimum.

**Comment by brndd** [comment]
@DrSnips 
volume pumps are set to 200 l/tick by default, so all you would need to do is turn it on.

**Comment by Killette2** [comment]
Making better pumps without involving sc*ence? OY VEY!

**Comment by LordMyroc** [comment]
If the entire overpressurization debate is about wanting to make supercanisters, I don't understand why we don't just add canisters with a higher capacity.

**Comment by brndd** [comment]
> If the entire overpressurization debate is about wanting to make supercanisters, I don't understand why we don't just add canisters with a higher capacity.

Portable air pumps have twice the volume of canisters, and the recently changed air tanks, which can now be moved and constructed with 5 metal, have 2.5 times the volume of canisters (but lack release controls so you can only use them by wrenching down pipes).

The problem is that to placate people who want 300 gigapascal (or more) canisters, you'd have to add a container that holds 60000 litres of gas in order for it to have a comparable amount of moles at standard canister pressures. Having that amount of gas makes no sense from a gameplay perspective and never did. It is, as some say, "overpowered".

**Comment by FudgePucker** [comment]
I mean one argument for giga canisters is that it enables localized atmospheric sabotage over just putting the plasma in distro.

When I am a malf engineering cyborg, do you prefer for me to disable science by dragging a "fun" can to science, or just putting plasma into distro?

**Comment by Smedley8** [comment]
Gonna close this due to inactivity,
Also was sent sekret metaclub documents related to injectors and vents,

**Pull request closed without merging**
