### PR TITLE
[Meta] FIX ENTIRE GAME

### LINKED ISSUE #3300: [Metaclub] minor mapping issue in EVA
ss 2015-03-03 at 05 27 04

The table the radios are resting on should be an rtable for consistency purposes.  really serious stuff here.

### PR DESCRIPTION
**Pull request by Exxion**
Fixes #3300. There is truly nothing else to say.

### CODE REVIEW

**Comment by N3X15** [comment]
MERGE IMMEDIATELY HOLY SHIT WHY WASN'T THIS DONE EARLIER

**Comment by Probe1** [comment]
you saved us all @Exxion 

you saved us all.

**Comment by IratePirate** [comment]
You thought it was a mistake?

**Comment by Probe1** [comment]
oh fuck

**Pull request merged**
