### PR TITLE
Changes wizard organs to non-robotic on spawn so they can't EMP themselves

### PR DESCRIPTION
**Pull request by gbasood**
honk

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
Would it be O.robotic == 1 to check for something like "needs glasses"?

If so, you miight want to check for that, too. Lost count the amount of times I've prayed for a pair of specs and gotten a "Top kek" as a reply.

Thanks Deity.

**Comment by gbasood** [comment]
Shortsightedness is unrelated to that
In fact it's a gene or eye damage.

**Comment by ghost** [comment]
Odd, before I've only had the "needs glasses" gene, EMPd in the hideout, and lost all sight.

**Comment by gbasood** [comment]
EMPs are also unrelated. EMPs only affect organs with robotic == 2

**Comment by ghost** [comment]
:-1:

**Comment by gbasood** [comment]
still works better than hypothermia

**Comment by ghost** [comment]
at least I didn't self merge hypothermia :^)

**Comment by 9600bauds** [comment]
at least hypothermia compiled ;^)

**Pull request merged**
