### PR TITLE
Remove cheeki breeki

### PR DESCRIPTION
**Pull request by MadmanMartian**
due to an unfortunate turn of events, there was a 5% chance of a russian spawning in the cargo station. This would trigger the sleeping mimic, who would pursue the russian onto the cargo shuttle, while also enraging it with its mateba.

This led to a quartermaster being consumed by said enraged mimic 8 minutes later when he called the shuttle, which also led to them shouting at me.

angry_about_features

### CODE REVIEW

**Comment by aceedex** [comment]
Hey, I think it was funny

**Comment by Irradiation** [comment]
@MadmanMartian Another detail that came to my mind, I'm not sure if somebody with all-access/cargo access was a thieving bastard/pushed the supply shuttle recall button often, but I've had 2 supply shuttles come in EMPTY in a row in the same round that I got OMNOMNOM'd by a mimic.

**Comment by Blithering** [comment]
All I heard was 'cargo may get a free mateba' 
Retain feature!

**Comment by Kurfursten** [comment]
@Irradiation next time you see this, ahelp and try to get more info for us, it's really hard to pin down the cause without knowing what's going on

**Comment by Irradiation** [comment]
At the time, I thought it was just somebody thieving/recalling the shuttle, so I didn't think ahelping it would go anywhere. Sowwy.

**Comment by ghost** [comment]
Слыш, ты, блядь, сука, я тебе сейчас покажу какая она "несмешная", нахуй!

**Comment by Intigracy** [comment]
сука блядь

**Comment by AutismSpider** [comment]
>remove free gun and pet wooden chest

is you of serious comrade

**Comment by CptWad** [comment]
wait what the hell

**Comment by MadmanMartian** [comment]
when a mob is seen as a 'free gun', you know there's problems.

**Comment by chesse20** [comment]
i dont really understand this but being attacked by a mimic with a 5% chance isnt really a bug its just a random event

**Comment by DamianX** [comment]
Deemed as feature by popular demand + conflicts, closing.

**Comment by MadmanMartian** [comment]
woo

**Comment by Irradiation** [comment]
Delet ruskies, they are breaking my impulsions

**Pull request closed without merging**
