### PR TITLE
Change fertilizer from snowflake bottles into actual bottles

### LINKED ISSUE #20576: Feature Request:Remove the special snowflake bottles from the botany vendor
Title says it all, those bottles are stupid 10 unit beakers that you can't even toggle their transfer ammount

Proposed change: Change them to normal 30u bottles and cut their ammount in the vendor by 2/3
inb4:"but muh powercreep, now botany gets FREE 30u containers"
\>Cans are available everywhere and they hold 50u

### PR DESCRIPTION
**Pull request by ghost**
New bottles of fertilizers, comes into actual bottles, meme descriptions attached! The farmbot might be a little worse off but it's out of the scope of the PR... do people even use farmbots seriously anymore ?

:cl:
 * rscadd: Fertilizer now comes into actual bottles of 30u that function like actual chemical bottles. Botanist also gets a lot more fertilizer as a bonus because cutting it by three feels stingy. Fixes #20576.

### CODE REVIEW

**Comment by Exxion** [comment]
Yes, everyone who is not a masochist uses farmbots

**Comment by ghost** [comment]
I'm gonna do a feature check on farmbots then, at least to make sure the new containers work right. For now the only obvious issue I've seen is that the new bottles splash on it when inserted, but then so do buckets already

**Review by MadmanMartian — COMMENTED** [review]
May want to check if vaults such as the biodome don't have mapped fertilizer bottles

**Comment by ghost** [comment]
I'll check the vaults, yeah. Also... I'm at a bit of a loss for the farmbot. It works perfectly as long as you put lids on reagent containers, though. Also it now accepts big beakers, buckets and such and any type of fertilizer, so that's nice

**Comment by ghost** [comment]
Well, zoo_truck wasn't even running previously due to lizard path being changed, also someone forgot their backup folder in there, nice

**Comment by strawberrytan** [comment]
yeees i hate those snowflake bottles so mucj

**Pull request merged**
