### PR TITLE
Detective Fluff

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
Adds luminol and associated mechanics (part of @Zuhayr's port of Aurora forensics) and some alt. titles/outfits to the detective's closet.
To do:
- [x] Fix conflicts
- [x] Add the uniforms and titles
- [x] Not get yelled at for violating AGPL
- [x] Make a changelog

### CODE REVIEW

**Comment by Zuhayr** [comment]
Fair warning, this hasn't been tested on Bay's live server yet.

**Comment by BestName** [comment]
Testing is for nerds. We're living on the edge. :sunglasses:

**Comment by ShiggyPiggy** [comment]
I'm not entirely sure what's going on but I pushed 2 more commits via Github Desktop that fix the conflicts and add the changelog, so this should be good to go and merge.

**Comment by ShiggyPiggy** [comment]
I've gone a bit wild with the commits and I can't still figure out squash, ohgodohgod.

**Pull request closed without merging**
