### PR TITLE
Trader Name Fix (SBO8)

### LINKED ISSUE #20999: Trader Latejoins No Longer Show Name
Pretty sure this was caused when we reordered some calls in the latejoin proc to fix dynamic spawning people without traitor uplinks. I think what's happening now is that it tries to fire the announcement before the mob is actually created/named

### PR DESCRIPTION
**Pull request by Kurfursten**
real name

fixes #20999

🆑 
* bugfix: Trader latejoin message will now show name

### CODE REVIEW

**Comment by MadmanMartian** [comment]
those special characters, did you edit this through DM?

**Comment by Kurfursten** [comment]
those have been there, the only change to those I made was the removal of a space character that was unsightly

**Comment by MadmanMartian** [comment]
If you did it through DM, you've done clucked up and they'll show weird in goonchat, different encoding in DM.

**Comment by Kurfursten** [comment]
Are you sure? I originally wrote it in DM and it appears fine right now

**Comment by Kurfursten** [comment]
now uses compatible characters (tested)

**Comment by Kurfursten** [comment]
@exxion

**Comment by Exxion** [comment]
I liked the old characters better, but them breaking every time anyone touched the file was getting old

**Pull request merged**
