### PR TITLE
fixes #7581

### LINKED ISSUE #7511: Botany3: Nettles, deathnettles, novaflowers can't be grinded
Putting them into grinder and grinding them results in 0 chems.
Novaflowers have to be put in using a plantbag.

### LINKED ISSUE #7581: Meat cleaver has a flipped sprite if you're looking to the north
https://i.imgur.com/1B7h2tE.png

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #7581

### CODE REVIEW

**Comment by d3athrow** [comment]
was about to say

**Comment by Intigracy** [comment]
shhh

**Comment by clusterfack** [comment]
Pretty sure these files are over the icon limit, are you sure you did it right?

**Comment by Intigracy** [comment]
Yes.

You can't edit the icons inside, but you can use the flip and rotate and shift left/right/up/down buttons.

**Comment by PJB3005** [comment]
@Intigracy I wouldn't be so sure of that the file's size dropped by 50 KB.

**Comment by Intigracy** [comment]
Where's it tell you that?

**Comment by Intigracy** [comment]
Oh.

These overfilled dmis are so terrible.

**Comment by clusterfack** [comment]
Every time

**Pull request closed without merging**
