### PR TITLE
Increases Diona speed to reduce dependence on Hyperzine.

### PR DESCRIPTION
**Pull request by Reviire**
Increases their speed somewhat so they're not essentially immobile without Hyperzine. Really, it's retarded. They already take over double burn damage in return for their benefits, no need to make them completely reliant on a chemical to move. 

REEEE I need to fix my bleeding edge branch to get rid of the commit removing a file I added. 

:cl:
 * tweak: Diona speed increased slightly.

### CODE REVIEW

**Comment by Probe1** [comment]
1.  it's just tweak you don't have to add rsc.
2.  lets not make a bunch of PRs predicated on one PR merging.

See https://github.com/vgstation-coders/vgstation13/pull/17645 and whether or not that's merged to remove the DNM label.

**Comment by Reviire** [comment]
I think this is a necessary PR either way. Their speed isn't justified. Hyperzine staying or being removed, they shouldn't have such a dependence on it to move around.

**Comment by Dacendeth** [comment]
They have a lot more advantages besides the brute regen such as no blood, pain immune, radiation immune, low pressure immunity, no breathe, and cold resistance. I think the speed penalty is pretty fair.

**Comment by Pathid** [comment]
@Dacendeth In practical terms the cold resistance just makes space put them into a coma forever that they can't ghost out of or become catatonic. Also that 2.5x burn modifier.

**Comment by AutismSpider** [comment]
@Dacendeth not full radiation immune to  many rads and they black out the cold puts them into a coma unless they have a chest borer to heat them up

**Comment by jknpj** [comment]
This PR is missing the point of playing diona.

**Comment by jknpj** [comment]
Also @Dacendeth  they aren't immune to low pressure nor have cold resist, what the fuck made you think that

**Comment by DamianX** [comment]
Delete this. Dionae are not supposed to be fast.

**Comment by Pathid** [comment]
@jknpj Not the cold resist mutation, they have altered thresholds.
https://github.com/vgstation-coders/vgstation13/blob/b09481717b21d92cfcaf192ac21c35603d51e7e0/code/modules/mob/living/carbon/species.dm#L806-L811
But like I said, all it saves them from is damage, due to hypothermia they still go into permasleep.

**Comment by Dacendeth** [comment]
@jknpj They don't take pressure damage from space tiles, even naked? That's what I'd call low pressure resist at least.

**Comment by jknpj** [comment]
They do take low pressure damage. I don't want to pull a harse with "you'd know if you played diona" but you're free to test it if you don't believe me. As long you're not in hyperzine you'll heal the pressure damage, sure, but you still get the low pressure alert.

**Comment by LavosIG** [comment]
This is needed especially if the hyperzine changes come out because as of current dionae are the same speed as completely crippled characters in wheel chairs without hyperzine, and his speed change is a moderate change specifically to compensate for A: the already existing clunkiness (not balanced) of dionae and B: the potential merge of a PR removing hyperzine, a chem most players who actually play dionae say is an essential requirement to play the race. If you complain what the players deem as a "requirement to play" is broken in most circumstances and needs to be removed (hyperzine) basic came design dictates you have to compensate to address its removal. Don't be league of legends lads, clunkiness is not a game design feature, its bad game design in general and we should work towards fixing all of it. No one has complained about dionae hyperzine meta at all in any of the hyperzine removal discussions, only I brought it up at all and if I didn't you wouldn't care still because you don't actually play or know the race or how it feels. So I feel like this isn't actually a balancing issue, just a "I hate dionae" issue. Welding tools do 40 damage to dionae per hit just use it and stop complaining their unbalanced.

**Comment by LavosIG** [comment]
And sorry to double comment but permasleep is essentially dying without being able to at least be in dead chat unless you Ghost tab ghost which is permadeath, and no one rescues trees from space so saying dionae are op because of no pressure ignores their biggest weaknesses.

**Comment by jknpj** [comment]
Someone showed me i was wrong about the pressure alert dionas get(they get the warning one, not the damage one), i apologize for being rude about it.

**Comment by Reviire** [comment]
That was the main point of this PR. Diona players being against the removal/nerfing of Hyperzine because it's "Required" for Diona. This is terrible design, a race shouldn't be so bad in some aspect that they require a chemical to counteract this change. If Diona aren't supposed to be fast (Read: not god awfully slow), why haven't we completely removed Hyperzine or Cocaine affecting them? 

Personally, I'm of the opinion Hyperzine shouldn't affect crit slows, hunger slows and racial slows.

They should move at a relatively decent speed without Hyperzine, hopefully removing this dependency they have. A dependency on the go fast chemical is retarded.

**Comment by Praecordia** [comment]
SLIPPERY SLOPE

**Comment by Dacendeth** [comment]
I think changing it from 7 to 4 is too much, i'd be willing to upvote a smaller change of 7 to 6 personally.

**Comment by Reviire** [comment]
@Dacendeth Just to put it into perspective, a Vox with a softsuit and Vox magboots has 3.75 speed. Human with RIG + Magboots moves at 3.33 or so. Dionae would still be the slowest default by far, moving at 4 without anything else.

**Comment by LavosIG** [comment]
7 to 4 only sounds like too much because you haven't actually tried playing with 7 without hyperzine. If the hyperzine changes are made, which is incredibly likely, it will be impossible to play with 7 or 6 default. For perspective moving at 6 is what fat wheelchair'd humans with no legs move at i'm pretty sure.

**Comment by Reviire** [comment]
Dude Hyperzine lmao. Gotta go fast and be a human that takes 2.5x burn damage.

**Comment by Probe1** [comment]
Don't snap at each other.

**Comment by TurboGay** [comment]
Diona lack bones to break, blood to bleed and regenerate damage which is a huge upside in a server with Baymed. Vox have no real upsides to even consider bringing Diona close to them in speed.

**Comment by Dacendeth** [comment]
@LavosIG I almost never take hyperzine as a Diona, my refusal to take it once upset someone so much IC they attempted to disarm me and force me to take some. The only time their speed becomes annoying to me is when you're too slow from magboots/cold to go through a fast closing airlock.

**Comment by Reviire** [comment]
@TurboGay You're missing the point. I'm not bringing them close to their speed, I'm bringing them close to their speed with other large slowdowns enabled. While the Dionae itself has none to speak of and is still vulnerable to things like celthermia or ZAS lmao.

Being too slow to go through an airlock is wew lad.

**Comment by TurboGay** [comment]
I'm not missing the point, Diona have huge upsides in exchange for their downsides, which include their speed and vulnerabilities. If you want them to be closer in speed to the other races which have no large upsides, remove/alter the upsides and then alter the downsides, a smaller speed buff would be fine but 4 is far too much for the positives of the race.

**Comment by LavosIG** [comment]
You are ignoring the severity of the downsides and upsides to suit what you think dionae should be instead of what they actually are right now. And to be frank you don't know what 4 movement speed is otherwise you wouldn't think they would even compare to humans still. Its not like thats a fixed value either even if you knew what 4 meant. IF its too much it would be noticable and turned back or slowed down immediately but I really don't think you know what your talking about Turbo and i'm not trying to be mean when I say that I just think you don't see ahead enough steps to realize what a post-hyperzine world is going to look like for all races anyway.

And dacendath i'm glad that you play a role in which you dont have to move fast but any type of medbay, miner, cargo, or security roll as dionae without hyperzine as of current is basically griefing your department. Dionae as of current without hyperzine move as slow if not slower then a wheelchaired fat human with no legs. I've tested.

**Comment by jknpj** [comment]
Can i close this now?

**Comment by Probe1** [comment]
Imagine if I had accidentally hit merge haha.  Just as a joke haha just because I mistook the buttons haha.  I wonder how the server would react?  How weird would that be right? haha.

**Pull request closed without merging**
