### PR TITLE
Revert snowmap. Goddamnit.

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by ghost** [comment]
This accomplishes nothing other than childish point scoring. You said I had 24 hours to fix the issues with it - it's been one.

**Comment by DrCelt** [comment]
This accomplishes nothing other than childish point scoring. You said I had 24 hours to fix the issues you had with it an hour ago.

**Comment by PJB3005** [comment]
You had 24 hours until i learnt the server crashed.

Also retroactive review of a PR is goddamn painful.

**Comment by ghost** [comment]
The server crashed because of an unknown runtime error that does not occur on any other map, there is no need to revert a PR over that, as it's a self contained problem that will not occur unless the map is forced by an admin who I have warned not to do

**Comment by mrpain666** [comment]
Ok what if we could...
Ok just listen here....
What if we could find the problem and..
Ok dont lose me now...
Ok so what if...
What if we could just...
Ok just pay attention for just a little longer here...
What if we could just find the problem and fix it?

**Comment by PJB3005** [comment]
How much times did you reread that @DrCelt before deciding which emoji to use?

**Comment by ghost** [comment]
@PJB3005 I clicked the wrong button I'm too tired it's Christmas day I don't want to be arguing about this

**Comment by Intigracy** [comment]
This was supposed to be good.
Instead it made everything worse and was overhyped.

Like Obamacare.

If only it had been done in bits and pieces.
And maybe actually tested. That'd probably have helped too.

**Comment by gbasood** [comment]
it was tested locally before it was merged
I don't know what fucked the serb but whatever it was fucked watchdog because it hasnt restarted the serb either

**Comment by ghost** [comment]
I'll find the cause of whatever killed the server if it kills me

**Comment by Probe1** [comment]
It was probably watchdog not modified to account for it and freaking out.  If it wasn't something on your end (or my end when I did a precursory test compile and join days ago) then it's something on the servers end which you won't find.

Go enjoy your Christmas.

**Comment by gbasood** [comment]
I know we've since covered all this shit but it wasn't watchdog
you know just for the record in case someone finds out about this a year later

**Pull request merged**
