### PR TITLE
Converts the clown roid to a vault

### PR DESCRIPTION
**Pull request by MadmanMartian**
:cl:
 * tweak: The clown asteroid has now been converted into a vault

### CODE REVIEW

**Comment by Irradiation** [comment]
In laymen terms, this means that you can't reliably rush te clown 'roid to get quik-phazon & bananium. Maybe people will start doing xenobio now :^)

**Comment by yclatious** [comment]
Based & clownpilled. Honk Honk.

**Comment by aceedex** [comment]
bad. sad. bad

**Comment by Hoshi-chan** [comment]
Is there a tag for feature removal? Because that's effectively what this is.

Just fucking get rid of the clown roid as the _only_ place for phazon/bananium and make them very rare materials found deep in the asteroid, as well. Like, around the giant rockernaut, or that vault on roidstation. Right now mining can mine the western field with a sonic jackhammer and never touch the roid again for the rest of the round. Give them a reason to keep mining.

**Comment by SkowronX** [comment]
rip

**Comment by SonixApache** [comment]
add motivation to OP pls

**Comment by ghost** [comment]
I would be ok with this if space exploration didn't involve removing yourself from the round for a small chance of find something useful just when the shuttle is about to dock. Add deep space scanning or a way to navigate space that doesn't involve staring at two coordinates on a poorly refreshed html screen.

**Comment by jknpj** [comment]
derelict mommis will need a new source of materials

**Comment by Sooose** [comment]
I would like to give this the thumbs up but as jknpj said it would screw over the derelict MoMMIs.

**Comment by KingofHONK** [comment]
no!

**Comment by MadmanMartian** [comment]
@Hoshi-chan It already spawns in the rockernaut arena, and xenobiology is arguably easier than the clown roid because you can infinite-loop slimes for unlimited phazon/bananium

**Comment by Caboozles** [comment]
Does this have an intended purpose other than nerfing the Phazon mech?

**Comment by Sooose** [comment]
@MadmanMartian Let's be honest the clown roid is by far the easiest  place to get every material you need for RnD and then some. Duping phazon with a material synth is incredibly easy, no need for xenobio RNG.

**Comment by Durgen** [comment]
mimes are behind this PR

**Comment by kernikov** [comment]
> derelict mommis will need a new source of materials

[#22220]

**Comment by SonixApache** [comment]
literally why
i'm still waiting on the why
*why*?

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment]
Is it possible to make a vault guaranteed spawn?

**Pull request closed without merging**
