### PR TITLE
Make grues "work" on snaxi

### LINKED ISSUE #33823: Grue is balls on snaxi
There's no real maint on snaxi, so it spawned me in the chapel with the lights off. Within a minute while I was reading a guide from under the table, the AI was able to track me by my grue name and fry me in 4 seconds before I could ventcrawl. Another grue was spawned and had a similar fate

### PR DESCRIPTION
**Pull request by nervere**
Framework to make grues "work" on Snaxi.
Does this by using pre-determined manual spawn points, if they exist, to spawn grues.
If no such manual waypoints are found (they'll only be mapped in to Snaxi), it'll use the normal spawn method.

Since these manual spawnpoints can really only be placed outdoors (or in the caves, to a lesser extent), this will also restrict grues to only spawning at night. If you can think of any viable on-station spawns, however, let me know as those are ideal.

## To Do:
- [x] Write the framework
- [ ] Test the framework
- [ ] Add spawnpoints to snaxi
- [ ] Restrict grues to only firing at night on snaxi
- [ ] If grue fails to fire as a random event due to it not being night, set a variable (in world ticks) indicating it as such, re-try the random event, and disallow selection of grue if recent failure to pick it. Or just disallow grue being picked if it's snaxi and nighttime. (I haven't looked at event code yet.)
- [x] (maybe) Allow grues to smash wall-mounted lanterns (found in the caves)

## Why it's good
System isn't perfect but it's better than them spawning in Snaxi's microscopic maintenance tunnels and instantly dying.

Note: I was originally going to make grues only spawn in the surface mine's caves, but decided against it as they tend to be filled with space bats that kill you. It'd suck just as bad to die to those, so the cave spawns will only be around the beaten path that miners can walk along.

Closes #33823

## Changelog

:cl:
 * tweak: When the map is Snaxi, grues will exclusively spawn during the night, in the outdoors.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
How long is the day-night cycle on snaxi? Maybe it could delay spawing in until night.

**Comment by nervere** [comment]
> How long is the day-night cycle on snaxi? Maybe it could delay spawing in until night.

Night lasts 36 minutes and I think day is more or less the same duration.
Also, I saw you talking about grue wall-mounted lantern balance in #33860. I didn't know those were smashable, so I just checked it off my To-Do for this PR and I'll let you handle what balance changes you find appropriate.

**Comment by Hinaichigo** [comment]
I guess 36 mins would be a bit too long to delay it.

For the nighttime check I recommend taking a look at the rulesets' `acceptable()` proc in dynamic_rulesets_midround.dm. Antag spawns use a separate trigger system than events like meteors. Also keep in mind grue spawns in midround versus latejoin are technically two different rulesets so the check should go in both.

**Comment by nervere** [comment]
> I guess 36 mins would be a bit too long to delay it.
> 
> For the nighttime check I recommend taking a look at the rulesets' `acceptable()` proc in dynamic_rulesets_midround.dm. Antag spawns use a separate trigger system than events like meteors. Also keep in mind grue spawns in midround versus latejoin are technically two different rulesets so the check should go in both.

Will do, thank you! And yeah I've already made changes to both rulesets so I'll make sure to cover both.

**Comment by Hinaichigo** [comment]
One way to do this that might be nice is to move the grue valid spawn point check into `acceptable()` and then have it use mapped spawn points if any exist, and default to the current behavior otherwise. There's already a darkness check in the current spawn check that could indirectly handle the day/night check automatically (although there could be some edge cases where it turns day right after the grue spawns in that case maybe, I'm also not sure how sudden the change is on snaxi).

**Comment by nervere** [comment]
Don't have time for this right now but I'll reopen and complete when I do.

**Pull request closed without merging**
