### PR TITLE
Goblins now do brain damage!

### PR DESCRIPTION
**Pull request by GermanSanta**
Due to popular demand of wanting brain damage. I fixed the ancient spaghetti code by making "BRAIN" into BRAIN on goblins. So they actually make people retarded.
rscadd: Brain Damage
rscremove: spaghetti

### CODE REVIEW

**Comment by DamianX** [comment]
It's still dumb, though? #25893

**Comment by BomberBro** [comment]
You can easily make a ton of these things since every theatervend has 5 rainbow clown outfits (actually, they're easier to make than normal goblins). Really bad idea imo unless it gets changed to 1 per vendor

**Comment by Caboozles** [comment]
Please no. This turns goblins from a shitposting tool into an actual weapon.

This would make producing ~50 or more goblins a serious threat.

**Comment by Zth--** [comment]
Your changelog's format is wrong

**Comment by Dacendeth** [comment]
Counteroffer, Creating clown goblins causes brain damage.

**Comment by jknpj** [comment]
demand not popular enough

**Pull request closed without merging**
