### PR TITLE
Adds eggnog

### LINKED ISSUE #28374: eggnog does not exist
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
gamebreaking

### PR DESCRIPTION
**Pull request by IThe-TI**
[sprites]
What better way to spend the cold winter months than to sip on a sugary custard, spiked with whatever booze you have, in front of the fireplace?

This PR adds eggnog, which can be made by mixing two parts milk, one part cream and an egg yolk (egg in the grinder).
The eggnog can be enhanced by adding equal parts eggnog and rum with a light dusting of cinnamon powder.

closes #28374
:cl:
 * rscadd: Added eggnog

### CODE REVIEW

**Comment by SageOfLight** [comment]
Delicious egg.

What about a spice.

**Comment by IThe-TI** [comment]
> 
> 
> Delicious egg.
> 
> What about a spice.

Seeing how there's no nutmeg, I could add cinnamon powder to the recipe

**Comment by Kurfursten** [comment]
I think in service stuff it's important to keep it simple: most recipes don't include everything that actually goes in. However, you did include the cinnamon sticks in the icon, so I think they should be in the recipe. Perhaps this?

>Egg Yolk + Milk + Cinnamon

5 ingredients is a lot for a drink and cinnamon is already a relatively difficult ingredient since it requires badgering botany for a nonstandard food

**Comment by SageOfLight** [comment]
> I think in service stuff it's important to keep it simple: most recipes don't include everything that actually goes in. However, you did include the cinnamon sticks in the icon, so I think they should be in the recipe. Perhaps this?
> 
> > Egg Yolk + Milk + Cinnamon
> 
> 5 ingredients is a lot for a drink and cinnamon is already a relatively difficult ingredient since it requires badgering botany for a nonstandard food

Make cinnamon a higher quality alternative with a bonus effect maybe?

**Comment by Kurfursten** [comment]
It would be reasonable if there was a basic eggnog of just milk+cream+yolk, then you can combine that basic eggnog with booze or cinnamon to create higher tier eggnogs

**Comment by SonixApache** [comment]
be sure to [update wiki]

**Comment by Kurfursten** [comment]
Update Wiki or I will remember this!

**Pull request merged**
