### PR TITLE
Rack directional sprite

### PR DESCRIPTION
**Pull request by brndd**
[sprites]
I don't know why these things never had directions in the sprite. I added some by just rotating and mirroring the sprite appropriately. They're ugly, but only as ugly as the original, IMO.

:cl:
 * rscadd: racks now have directional sprites

### CODE REVIEW

**Comment by brndd** [comment]
what in the fuck happened with the commits

**Comment by brndd** [comment]
Don't create new branches off a feature branch, kids.

**Comment by Exxion** [comment]
Those are definitely not only as ugly as the original
We're entering fifth-dimensional space here

**Comment by brndd** [comment]
I think the original is supposed to represent a rack of 5 shelves at some odd perspective. The rotations follow the same perspective.

The best solution of course would be to redraw the whole sprite so it makes a bit more sense, but hell if I'm going to do that.

**Comment by ghost** [comment]
image
This is the rack if it had open plates. Turning it makes LITERALLY no sense.

**Comment by brndd** [comment]
I always saw it as a rather poorly-drawn version of this:

silver-muscle-rack-freestanding-shelving-units-ur301260pb5p-sv-64_1000

I don't think it makes sense for it to be a bicycle rack like that considering throughout the stations they're generally just used as shelves, and items are put on top of them as they would in shelves (rather than going in between the slots like they would on a rack like that).

**Comment by RealestEstate** [comment]
what Glass said. also I think the racks look fine, but maybe choosing from different styles of racks  would be cool too.
the rotations are very ridiculous, especially given the mismatching perspective

**Comment by kilozombie** [comment]
Yeah it's clear you're looking at a different kind of object than all other human beings
It's a flat surface bicycle rack type thing that you can rest items on top of-- that's why it has the (finicky) behavior of being able to put items on different slats depending on where you click
Oh, that's also what the outcroppings on top are. It's clearly not what you put in your image, because if it were, it would have been drawn that way

**Comment by brndd** [comment]
>that's why it has the (finicky) behavior of being able to put items on different slats depending on where you click

That could just as well apply to putting items on different shelves.

That said I forgot about that behaviour and can't be arsed to write the code to make it deal with rotations so whatever.

**Comment by Exxion** [comment]
It took a lot of work but I finally managed to see how you could see it as shelves
It's definitely not supposed to be shelves and nobody else sees it as shelves but if you squint really hard it's possible to see it

**Pull request closed without merging**
