### PR TITLE
Therapy Couch

### PR DESCRIPTION
**Pull request by Kurfursten**
image

🆑 
* rscadd: Traders are now selling a therapy couch. When you lay back on it, you can almost hear the calming ocean waves. Relaxing here relieves a lot of mental ills, including hallucinations, jitters, stutters, and pain.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
psychologist job when

**Comment by ShiftyRail** [comment]
image

**Comment by DrSnips** [comment]
Based and Freud pilled.

**Comment by jknpj** [comment]
Take a seat.

**Pull request merged**
