### PR TITLE
Adds plantpot rustling sound

### PR DESCRIPTION
**Pull request by Goldsteel**
This adds a sound effect when you interact with plantpots to make them rustle when searching or stuffing things into them. There is also a slight message addition that tells you the plant pot is empty if it did not contain anything when you root in the roots.

:cl:
 * rscadd: Decorative plantpots now rustle when you interact with them.

### CODE REVIEW

**Comment by SonixApache** [comment]
Is this audible for everyone or just the person who is rustling?

**Comment by Goldsteel** [comment]
I think this is audible to everything around the plantpot.

**Comment by Goldsteel** [comment]
It's a local sound, so whatever that means. We can edit the radius to make it one tile I suppose.

**Review by MadmanMartian — APPROVED** [review]

**Comment by DeityLink** [comment]
Add those plant pot rustling sounds to the **/obj/item/claypot**
found in **code/modules/hydroponics/hydro_tools.dm**

**Comment by Goldsteel** [comment]
That already works with the current code. I tested it.

**Pull request merged**
