### PR TITLE
Adds Mirror of pain to the spellbook bundle

### PR DESCRIPTION
**Pull request by JustSumBody**
Recoil effect randomizes the user's appearance, because mirror or something
100% OC icon do NOT steal
image

### CODE REVIEW

**Comment by Exxion** [comment]
That recoil effect might be usable to the wizard's advantage if they're going for stealth

**Comment by JustSumBody** [comment]
Don't think recoil triggers if you already have the spell, just says "you've already read this one."

**Comment by Exxion** [comment]
I'm pretty sure that's exactly when recoil _does_ trigger

**Comment by Exxion** [comment]
Well apparently I was wrong
When does it trigger then?

**Comment by JustSumBody** [comment]
Spellbook is used by person one, and he learns spell. The spellbook is now "used"
If anyone that already knows spell tries to read it, they're just told they've already learned it and nothing happens.
If someone else that DOESN'T know the spell comes along and tries to read it, they're hit by the recoil.

Unless the wizard comes up with some plan to lose his mirror of pain spell just for the spellbook's recoil(or leaves it for another wizard during raging maybe? They can't get the bundle and an apprentice since bundle takes all their points, so that's out) I don't see it being an issue, but feel free to discuss

**Comment by ComicIronic** [comment]
Honestly, if the wizard does somehow set up a way to use the recoil effectively, they've earned it for being imaginative.

**Pull request merged**
