### PR TITLE
makes PDAs times new roman again

### LINKED ISSUE #31955: PDA font is all retarded and shit
(WEB REPORT BY: theophrastus REMOTE: 206.221.180.138:7777)
# Revision
71c8bfcc3859029cc63c4192c579ef5df8f6b68b

# Description
New PDA font is huge and forces me to scroll on the PDA. Also looks like ass.

# Steps to Reproduce
>open PDA
>Vomit

# What you Expected
perfectly fine font we had

# What Actually Happened
gay retarded font

### PR DESCRIPTION
**Pull request by robintime**
change bad
closes #31955

:cl:
 * tweak: PDAs are times new roman again. all is right in the world

### CODE REVIEW

**Comment by djkramer123** [comment]
The PR that saved /vg/

**Comment by Theophrastus1** [comment]
god bless this mess

**Comment by ghost** [comment]
change good

**Comment by Kromkar** [comment]
> change good

Next time don't ruin things with sneaky changes not in your changelog

**Comment by DamianX** [comment]
Someone post a screenshot of the new one

**Comment by Eneocho** [comment]
All hail robintime, saviour of /vg/.

**Comment by Eneocho** [comment]
> change good

Make it a separate PR man, sneak coder bullshit will be reverted.

**Comment by Dacendeth** [comment]
image
NEW | OLD

**Comment by Exxion** [comment]
I'm forced to agree with Kanef for once. The monospace font is based.
That said, silently bundling it with other changes is cringe

**Comment by DamianX** [comment]
They both look like trash btw

**Comment by Theophrastus1** [comment]
Now Post comparisons of the Messenger screen

**Comment by Eneocho** [comment]
Add both with a toggle on player settings, I kinda like the monospace one, even though the Times New Roman one has a place in my SOVL.

**Comment by ShiftyRail** [comment]
Computer modern PDA font when

**Pull request merged**
