### PR TITLE
Achievements and Scoreboard polishment

### PR DESCRIPTION
**Pull request by DeityLink**
I know you guys occasionally like to give Golden cups to players to reward their skill, or lack thereof, with custom names and all, and I thought that we could use more buttons under the Fun tab, so I made a "Give Achievement" proc:

achievemen

Achievements are summarized bellow the crew score on the scoreboard, at the end of the game, which brings me to the other aspect of this PR: polishing of the endgame scoreboard:

newscoreboard

### CODE REVIEW

**Comment by Probe1** [comment]
By scoreboard do you mean https://github.com/d3athrow/vgstation13/issues/2810  the statistics too?

**Comment by DeityLink** [comment]
no, just look at the pictures

**Comment by DeityLink** [comment]
statistics can wait for the feature freeze.

**Comment by Probe1** [comment]
I was holding out hope.  Don't let me down, no one has cared and I want to see it happen!

**Comment by clusterfack** [comment]
I'm starting to wonder if this should all start being displayed in a popup, because the score screen is just causing byond lag from displaying these huge blocks of text (especially you silicons and derelict mommis with your lawsets)

**Comment by DeityLink** [comment]
@clusterfack That's a good idea actually, but I'll probably do it in another once this one gets merged.

**Comment by ComicIronic** [comment]
Not to mention Byond's High-larious "scroll on new message" feature making it impossible to read the roundend info.

**Pull request merged**
