### PR TITLE
removes drag damage

### LINKED ISSUE #14469: Drag damage feedback / discussion
discussion of #14447 and #14468 and #14477 and #14535 and #14670 and #14746 and  #15271
a rundown of current drag damage mechanics and notes:
- Dragging someone who is knocked down AND has an unsplinted fracture AND is under the effect of gravity will, with a medium chance, cause brute damage
- Dragging someone who is: knocked down AND bleeding AND is under the effect of gravity will, with a chance based on their % of remaining blood, cause bloodloss
- Chances and damage are generally doubled when the person being dragged is in crit
- Correct procedure is to either splint or bandage someone before transport, or to transport them by roller bed / locker / office chair / bodybag / yellow intent grab

one good note from invoid:

> I like the drag change. It just needs blood trails that dont cause footprints when walked over

### LINKED ISSUE #19122: drag damage is a bad feature and was disabled for a reason
These are my points from many hours of both observing and of playing Medbay.

### It penalizes the wrong person
Drag damage penalizes the wounded person and Medbay for the carelessness of the dragger, who is almost universally apathetic and unaccountable for his mistake.
Most people just don't care or don't remember that drag damage exists, it's somebody else's problem, and then they almost NEVER hear from it again. This happens often even with silicons, who should be the most concerned about it.
This is something that you can appreciate the most if you observe a lot. Also, I think this is the most dooming part of drag damage, because it can't exactly be fixed <sup>unless you bring back that bug that made the dragger get damage instead of the dragee</sup>

### It's inconsistent
Drag damage only applies if you had brute damage. You can have one guy with a mangled foot and one guy dying from toxins, both roughly the same on the triage scale, and only one of them will suffer drag damage if pulled. It's very arbitrary on gameplay terms and I think feeds into point 1, if you drag two dudes and nothing happens to them you'll probably care less next time.

### It's disproportionately damaging
It does a lot of fucking damage and it's the annoying to fix kind of damage
In terms of "how long it will take Medbay to fix that", drag damage is often just as bad or even worse than the original injury. And we're comparing "intentionally stab someone four times" to "make the small mistake of not fetching a locker", so it feels even more out of place.

### It's really fucking annoying
When you need to drag someone three tiles from a sleeper to cryo and you also need to fumble buckling and unbuckling them or their cranium fucking splits open the tedium of it starts to grate on you and you're probably starting to hate the Paramedic's job a little more every passing day just for indirectly causing this plight upon you.

#### I am not opposed to adding difficulty to Medbay, but I feel strongly that drag damage in particular is a terrible implementation of difficulty.

### PR DESCRIPTION
**Pull request by SonixApache**
[balance][discussion][drama][why][needsservervote][etc]
I added this back when there were a lot of paramedics, because I felt it'd make them more useful.
Plenty of arguments have been made for and against, but honestly I don't think there are a lot of people think this is a good feature at this point. Let us kill it for good.
closes #19122, closes #14469, closes #19365

🆑 
- rscdel: Dragging someone who is bleeding no longer makes them lose more blood
- rscdel: Dragging someone with broken bones no longer causes their broken organ to take more damage

### CODE REVIEW

**Comment by Irradiation** [comment]
Just purely theoretically of course, apart from surgery-on-thje-go and looking like a big boy who's got his shit together, what's the ponit of carrying a rollerbed now?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
People can't walk through you or your patient if you do so nobody can interrupt your pilling
And if they try to resist out of your rollerbed they are a vampire changeling and can be beheaded freely

**Comment by Irradiation** [comment]
Can't you also acheive that if you drag somebody inside a locker/on a rollerchair?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
No, rollerbeds have a special snowflake exception, like dragging people in cuffs nobody can push-bump you

**Comment by Pathid** [comment]
How do you feel about the idea of leaving the blood loss part in, just toned down?

**Comment by SonixApache** [comment]
added changelog that explains what drag damage even used to do since apparently there's confusion regarding it
i'll toss up an alternate PR tomorrow which just tones down the blood- and bruteloss and maybe i'll also toss up another one to make splints less shit

**Comment by beesil** [comment]
Agreed with what Irradiation said about toning it down, and relevancy of roller beds.

Another option is removing drag damage while walking.

**Comment by Pathid** [comment]
>Another option is removing drag damage while walking.

Grab-intent dragging already doesn't do damage. (Neither do click-moving and even throwing, funny enough.) Though it would remove a slight knowledge barrier.

**Comment by mtpowell** [comment]
@Irradiation 
Roller beds should come with IV drips and maybe some other useful tools

**Comment by SonixApache** [comment]
Yeah, with #19365 and #19368 open, I'm going to close this. If dragdamage still doesn't work with those changes, I'll update this and re-open it.

**Comment by Kammerjunk** [comment]
@Irradiation What came first
The rollerbed or the drag damage

**Comment by d3athrow** [comment]
@SonixApache There is a reason why I removed drag damage from the code 5 fucking years ago
Same with getting hurt while moving about with items lodged in your organs/limbs.

**Comment by Irradiation** [comment]
@Kammerjunk I wouldn't know, I wasn't there to witness the OG harmdrag and handle_embedded objects or whatever.

**Comment by SonixApache** [comment]
ok

**Pull request merged**
