### PR TITLE
Lazarus injectors don't reset butchering drops, minor butchering changes

### PR DESCRIPTION
**Pull request by Sprok0**
Mobs now remember their butchered status through lazarus revival.

Partially butchered mobs are weaker than intact mobs, removing chunks of meat reduces max health, and skinned mobs take double damage.

The basilisk diamonds and hivelord core are converted into butchery drops, rather than just appearing when the mob dies.

Fixes a minor bug where a butchered mob's sprite was updated before the butchering completed, mostly visible with spider sprites having one more leg than they actually had left.

Butchering products can have the time it takes to butcher them changed, rather than being the same for all of them. Spider and frog legs take half default time, hivelord cores take one tenth default time.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
> Partially butchered mobs are weaker than intact mobs, removing chunks of meat reduces max health, and skinned mobs take double damage.

This is even worse for miners than the last PR was. Now not only do they have to find multiple goliaths in order to upgrade their suit, but they can't even use those goliaths in combat afterwards because taking their plates cripples them.

**Comment by coldcola** [comment]
would that mean the only way for pokememe to occur is via antag?

**Comment by TheFriggenSawbones** [comment]
it means choose between getting the minersuit upgrade or having a Goliath fuck things up

**Comment by Intigracy** [comment]
I now find this change acceptable with the change.

**Comment by Shadowmech88** [comment]
> it means choose between getting the minersuit upgrade or having a Goliath fuck things up

Yes but my question is why? Why is that a necessary change?
Have we been facing an epidemic of miners in max-armored hardsuits fucking up antags with teams of goliaths?

This PR seems to be trying to solve a problem that, to my knowledge, doesn't exist.

**Comment by coldcola** [comment]
/obj/item/weapon/lazarus_injector
desc = "An injector with a cocktail of nanomachines and chemicals"

As a thought I would think nanomachines capable of restoring hivelord's hearts or goliath's hides.

**Comment by Sprok0** [comment]
I can change the description if the ~lore~ doesn't fit

**Comment by Kammerjunk** [comment]
> Have we been facing an epidemic of miners in max-armored hardsuits fucking up antags with teams of goliaths?

There was one guy who got some cult buddies into trouble with a goliath that accidentally got loose, but other than that, I haven't seen or heard of it.

**Comment by kol1th** [comment]
> getting multiple plates from a single goliath is a good thing

wow

**Comment by clusterfack** [comment]
>Have we been facing an epidemic of miners in max-armored hardsuits fucking up antags with teams of goliaths

Are you saying we should only code it out if it affected someone personally and they got mad at it?

**Comment by Shadowmech88** [comment]
I'm saying that if we're going to remove or change functionality to, ostensibly, fix some kind of problem, we should be sure that the problem actually exists.

**Comment by aceedex** [comment]
Perhaps, if people seemingly enjoy it AND it doesn't seem to break the game in half, then it's not really worth removing anyway

I've already argued as to how long it takes to do, and how relatively rare goliaths can be. Crippling them was an extra step that didn't need to be taken, considering how retard mob AI is, you just made something useless even more useless

**Comment by clusterfack** [comment]
The Goliath hardsuit plate system was not designed to be maxed out easily in every round.

**Comment by Shadowmech88** [comment]
I don't think that what it was initially designed to be is relevant, especially considering how long ago it was made.

What matters is what the community thinks the best option is _now_.

**Comment by clusterfack** [comment]
Tbat clearly inst the case, since lockboxes were reverted despite what the community thought.

**Comment by Shadowmech88** [comment]
Because Pomf himself disliked the idea.

Being that his money keeps the server alive, I think it's fair for his opinion to matter more than the community's as a whole.
But the community's stance as a whole should definitely take second place over the opinions of individual players and coders.

**Comment by Exxion** [comment]
Yeah Pomf has always had final say
But the community is second

**Comment by Donnager** [comment]
Does the minersuit upgrade occur very often? I didn't even know it was possible until a few days ago and changing this makes it seem like it'd be only possible to max one hardsuit a round even after a lot of effort. 

Even if it is very strong what is the problem with that, the game isn't a fighting game so armor really isn't that important. Armor still means nothing in this game, one stun is death so why does it matter if somebody is able to get some armor and take a few extra clicks to kill?

**Comment by Kuranon** [comment]
I think there's only about 6 goliaths on the roid on a good day so this just makes it impossible to actually get a fully upgraded hardsuit (which nobody actually took the time to do because it's mostly useless unless fighting mobs)

**Comment by Kuranon** [comment]
Nobody has ever had an issue with a miner that was unkillable by melee either because stuns and lasers still exist and rule combat in this game. This is just nerfing mining for the sake of it I think.

**Comment by Kuranon** [comment]
I don't understand why this change exists tbh. Are you trying to make the game more realistic or something? More realistic doesn't always mean something is better or more fun and it's just making miners have less fun things to do in a job where the fun is mostly random chances

**Comment by Shadowmech88** [comment]
Shouldn't this have had a changelog entry, at the very least?

**Comment by ScrambledSteak** [comment]
> CLUSTER MERGES THIS WHILE PEOPLE ARE STILL DEBATING

hrzy9zc

**Pull request merged**
