### PR TITLE
Monkey blood limiting.

### PR DESCRIPTION
**Pull request by Allspice**
"Fixes" #12068 while making monkeys technically not infinite sources of blood.

### CODE REVIEW

**Comment by PJB3005** [comment]
Did you make monkeys actually get oxyloss from lack of blood? Blood regen?

**Comment by Allspice** [comment]
NOPE
If someone else wants to do that good on them, the only thing I want to do is make them "limited" containers of blood so virology can function properly.

**Comment by Intigracy** [comment]
Monkeys shouldn't have the same amount of blood as humans though.

**Comment by Allspice** [comment]
The numbers for monkey vessels can always be changed.

**Comment by clusterfack** [comment]
This gives blood to things like slimes though ?

**Comment by Allspice** [comment]
It actually gives all nonmonkey nonhumans a vessel that is null which is perhaps shittier. My preferred option is unlikely to happen, so that leaves either this or giving a vessel only to monkeys and humans, which I think would drum up some annoying code duplication.

**Comment by clusterfack** [comment]
This should at least have
- Vessel transferring over when monkeyizing - unmonkeyizing
- Blood regen slowly occurring

Ideally it would also have oxyloss, even in a very basic form.

**Comment by Intigracy** [comment]
I'll fix this PR for you if you want.

**Comment by Intigracy** [comment]
Note to self: Monkeys have a little less than 3/4 the blood amount per kg than humans do.

**Comment by gbasood** [comment]
@Intigracy so are we talking canadian thanksgiving or

**Comment by Intigracy** [comment]
Yeah, next year's :^)

Merging #12141 until such time as blood code can get a rewrite (probably never, though I'm offering $$).

**Pull request closed without merging**
