### PR TITLE
TEMPORARILY comments out male VOX announcement voice to hopefully solve connection issues

### PR DESCRIPTION
**Pull request by Exxion**
image

We have good reason to believe that the connection failures are related to having a very large number of files in our rsc. This is a fast way to cut out a fucking lot of them. (The files are not removed, but they are no longer referenced in the code, so they are not included in the rsc.)

There is a possibility that the related BYOND bug will be fixed, and we won't have to do anything other than revert this PR when that happens. Otherwise, we should finish N3X15's system to generate the words on the fly rather than compile them into the rsc. Either way, this PR is explicitly intended to be reverted.

This is not the correct way to do this, and even if we do somehow decide to leave this voice out, this PR should be reverted and it should be done properly. I don't think that's the decision that'll be made, though.

Also, I removed the male voice because people in the Discord seemed to agree that it was used less, but I can remove the female one instead if people would prefer it.

### CODE REVIEW

**Comment by DorainGrey** [comment]
Speed merge when.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
where is the unfinished realtime synthesizing code?

**Comment by Exxion** [comment]
Somewhere in here, I think: https://github.com/N3X15/ss13-vox/tree/master/ss13vox

**Comment by ValkyrieSkies** [comment]
I always preferred the masculine voice personally. The feminine voice also probably has an unfair advantage as far as usage perception goes because :
- It's the default voice
- It's the voice used for a number of automated announcements

**Comment by gurfan** [comment]
@Exxion Any updates related to this?

**Comment by Exxion** [comment]
Lummox has basically not mentioned it
I'll look into the on-the-fly generation system

**Pull request merged**
