### PR TITLE
WIP: Metroids

### PR DESCRIPTION
**Pull request by N3X15**
Currently just oldcode retrieved from the depths of Mercurial with what appears to be ancient icon asshattery scripts that are probably useless.

Needs more discussion about how these fit in with slimes before we continue.

## WHY

image

## Changelog

:cl:
 * rscadd: Metroids

### CODE REVIEW

**Comment by N3X15** [comment]
Also this will likely fail to compile because it's literally just copypasta'd from the hg failstation repo.

**Comment by jwhitak** [comment]
I don't mind even if this winds up just being a sprite swap with the current slimes, I'm down for the change.

**Comment by juanototo2** [comment]
Perhaps have these work as effectively the Karmotrine-equivalent for xenobiology? Get metroids from somewhere else -- space, roid, xenoarch, etc.. and drag them back, then do xenobio things, and you get stuff too strong, weird, cool, etcetera for regular xenobio.
I don't know, man. Just spitballing here.

**Comment by Cartlord** [comment]
If this isn't ready for emrge, you can mark it as a Draft.

**Comment by N3X15** [comment]
> Perhaps have these work as effectively the Karmotrine-equivalent for xenobiology? Get metroids from somewhere else -- space, roid, xenoarch, etc.. and drag them back, then do xenobio things, and you get stuff too strong, weird, cool, etcetera for regular xenobio. I don't know, man. Just spitballing here.

I have no fucking idea what Karmotrine is, but I'm guessing you mean special chems you can't get anywhere else? Because that could be interesting.

**Comment by ghost** [comment]
y cant metroid crawl

**Comment by Hinaichigo** [comment]
How do metroids work originally?

**Comment by Liquid-Bob88** [comment]
> I have no fucking idea what Karmotrine is, but I'm guessing you mean special chems you can't get anywhere else? Because that could be interesting.

Karmotrine comes from ancient seeds.It's a chemical for special cocktails. It's xenoarch content though and unless the xenoarch is not interested in guns, you won't see it often.  I just wonder what could be the source for your metroid mob. How rare do you want it to be ?

**Comment by N3X15** [comment]
> > I have no fucking idea what Karmotrine is, but I'm guessing you mean special chems you can't get anywhere else? Because that could be interesting.
> 
> Karmotrine comes from ancient seeds.It's a chemical for special cocktails. It's xenoarch content though and unless the xenoarch is not interested in guns, you won't see it often. 

k.  Thanks.

> I just wonder what could be the source for your metroid mob. How rare do you want it to be ?

Currently, I'm thinking one or two eggs spawn in a vault in a sealed chamber (r-window box).

> How do metroids work originally?

Metroids are slimes on steroids (although they were the original code for slimes).  They used to be extremely aggressive and could quickly fuck up xeno if you made a wrong move. I don't remember the feeding monkeys = friendly metroid code working very well.  It would be standard procedure to have at least two xenobios or an XB and some poor fucker the XB dragged in, so there was at least some level of backup.

Otherwise it was largely the same:  Feed babby, grow adult, make them split, kill one and bonesaw its core out (fuck the slime extractor), rinse and repeat.  The flavors came later after TG turned them into slimes and tamed them a bit.

We may want to think about alternative names/sprites in case Nintendo does object to their usage.  I really don't see them freaking out too much, though, since we aren't using their likeness for monetary gain.  Roros were the first stab, but from what I understand, they were also extremely lame.

**Comment by Theophrastus1** [comment]
Finally, the ability to milk metroids and harvest their delicious jellies and jams for chem buffs will come true.

**Comment by Blithering** [comment]
Perhaps metroids could be a slime core reaction when injected with phazon?

**Comment by xeroxemnas** [comment]
Lawsuit waiting to happen.

**Comment by angryturnip** [comment]
> Perhaps have these work as effectively the Karmotrine-equivalent for xenobiology? Get metroids from somewhere else -- space, roid, xenoarch, etc.. and drag them back, then do xenobio things, and you get stuff too strong, weird, cool, etcetera for regular xenobio. I don't know, man. Just spitballing here.

God forbid xenobio be more interesting at roundstart

**Comment by xeroxemnas** [comment]
More super dangerous mobs that xenobio can "accidentally" release besides xenomorphs on the roid would be cool yea.

**Comment by Kurfursten** [comment]
Today I will remind him

**Comment by N3X15** [comment]
> Today I will remind him

Design doc is up

https://gitlab.com/N3X15/open-design-docs/-/blob/main/content/ss13/vgstation13/samus-returns/index.md

**Comment by Kurfursten** [comment]
Greetings from Germany, kill the animals

**Comment by Eneocho** [comment]
Any news?

**Comment by ghost** [comment]
Derelict PR, feel free to re-open if revisited.

**Pull request closed without merging**
