### PR TITLE
Corpse generation cleanup

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[tweak][performance]

## What this does
optimises some stuff here in there in an attempt to make these initialize faster. also stops runtimes.
mainly stops creating new job datums for every type and just uses initial(type) on subtypes **only** if corpseidaccess is set.
## Why it's good
faster inits, less runtimes.

### CODE REVIEW

**Comment by adacovsk** [comment]
Well done

**Comment by Kromkar** [comment]
1) the performance increase, if any, is too small to be noticeable
2) this makes the code less maintainable

there are several reasons we abstract regular or common tasks by putting them into functions and one of them is so if they ever need to be changed, you only need to change it once

**Comment by gurfan** [comment]
Anytime someone says the word "faster" in a PR they should be forced to prove it

**Comment by SECBATON-GRIFFON** [comment]
> Anytime someone says the word "faster" in a PR they should be forced to prove it

corpses used to take 0.2 seconds on average to init, this brings it down to 0.1 or less, depending on cases

**Comment by Kammerjunk** [comment]
tbf maybe we should just rm -rf ./, that'd save a lot of init time

**Comment by Hinaichigo** [comment]
I sort of think the adjustXYZloss procs should be used for simplemobs, instead of modifying the losses directly, even if it doesn't change much currently. That way it passes through their scaling modifiers and will make it more consistent and easier to expand on their damage system in the future.

This is a special case so maybe an exception is warranted but still I think it merits some consideration.

**Comment by SECBATON-GRIFFON** [comment]
> 1. the performance increase, if any, is too small to be noticeable
> 2. this makes the code less maintainable
> 
> there are several reasons we abstract regular or common tasks by putting them into functions and one of them is so if they ever need to be changed, you only need to change it once

removed some of these changes since the improvement with them is totally negligible anyways

**Comment by adacovsk** [comment]
I cry. At least fix the runtime

**Comment by Kromkar** [comment]
> I cry. At least fix the runtime

Go away

**Pull request closed without merging**
