### PR TITLE
Mime Goblins inject you with nothing!

### PR DESCRIPTION
**Pull request by GermanSanta**
Mime Goblins now have a chance of injecting you with 1 unit of nothing. Which will make you quite quiet.

🆑 
rscadd: Mime Goblins can now inject you with nothing

image

### CODE REVIEW

**Comment by Dacendeth** [comment]
Mime goblins already silence you, and Nothing doesnt silence anyways.

**Comment by GermanSanta** [comment]
Nothing does silence. So a lot of mime goblins = long silence.

**Comment by Eneocho** [comment]
> 
> 
> Mime goblins already silence you, and Nothing doesnt silence anyways.

All nothing based cocktails silence you to a degree, as far as memory serves.

**Comment by ghost** [comment]
another step toward making goblin makers kill-on-sight

**Comment by Exxion** [comment]
>All nothing based cocktails silence you to a degree, as far as memory serves.

There are only three of them and only one of those silences you.
Also, no, pure Nothing does not silence you. So all this PR does is makes it so that mime goblins heal mimes.

**Comment by Eneocho** [comment]
Should inject Silencer instead.

**Comment by Eneocho** [comment]
>be mime
>make 30 mimegoblins
>they attack and inject someone constantly
>that someone dies to liver failure due to the large amounts of alcohol

**Comment by Exxion** [comment]
Silencer is non-alcoholic

**Comment by Eneocho** [comment]
> 
> 
> Silencer is non-alcoholic

I meant the mimes as the PR currently is, would inject "Nothing". Wasn't nothing alcoholic? I could've sworn it was.

**Comment by Kurfursten** [comment]
Given that :confused: has always been a soft down, I'm thinking there isn't enough support for this.

Moreover, as Exxion said, it doesn't even accomplish its stated intention.

**Pull request closed without merging**
