### PR TITLE
Roidstation 1.2 Hotfixes

### LINKED ISSUE #19244: roidstation xenobiology slime extract fridge dies and never comes back, can't unwrench to move it either.
#### Description of issue
power went out, fridge was unusable and unwrenchable, it just had to sit in the corner dead. 

I've noticed there are lots of APCs in the room in a weird layout, I assume this is what is fucking with the power to the fridge. each cage seems to have its own APC except the bottom right which also holds the power to the lights?

#### Difference between expected and actual behavior
I can understand it not working when there is no power but when it had come back on the machine still refused to work. The other problem is that it cant be unwrenched? As far as I know simply trying to unwrench it with a tool did nothing, it was trying to store the wrench.

#### Steps to reproduce 
roidstation xenobio, put something in the machine, with power, cut power to the room, notice how you cant put things in. restore power, still unable to use the machine, or wrench to a different part of the room that is getting power.

### LINKED ISSUE #19317: Detective office windoor access on roid
(WEB REPORT BY: tolan1 REMOTE: 172.93.109.202:7777)
# Revision
49b9a131db5a4e9882dc337351967d95077decea

# Description
Detective doesn't have access to the windoor in front of the morgue tray and medical records in his own office
# Steps to Reproduce
Try to use a windoor in your own office, 2 tiles from where you spawn
# What you Expected
open sesame
# What Actually Happened
ACCESS DENIED

### LINKED ISSUE #19331: roid lightswitches
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)
QM office has no lightswitch
only cargo bay lightswitch is in backroom
HoP office has no lightswitch
custodial closet west of HoP office has no lightswitch
locker room south of HoP office has no lightswitch
cloning lab has no lightswitch
engineering lockers has no lightswitch
CE's office has a small problem related to the title of this issue, i don't know if you'll be able to figure out what it is
EVA has no lightswitch
medbay front desk has no lightswitch
holodeck control, no lightswitch

honestly just fucking write a unit test to find rooms without lightswitches and work from there

### LINKED ISSUE #19332: Roid Intercomms
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
There are quite literally zero(0)intercomms in public spaces on roidstation

why

### LINKED ISSUE #19348: rogue vendtable in roid medbay
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)
https://i.imgur.com/iKluhpN.png

### LINKED ISSUE #19395: missing pipe asteroid station
(WEB REPORT BY: riolenn REMOTE: 172.93.109.202:7777)
# Revision
96f159591515adc68368366e0e90f95f811d40c8

# Description
asteroid station air pipe at 218,173

# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #19396: wrong pipe asteroid station
(WEB REPORT BY: riolenn REMOTE: 172.93.109.202:7777)
# Revision
96f159591515adc68368366e0e90f95f811d40c8

# Description
wrong pipe used at 135, 218, 1 on the waste line

# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #19403: Empty machine frame in research unusable
(WEB REPORT BY: autisticmouse REMOTE: 172.93.109.202:7777)
# Revision
113190d7c1dbefbdbaeaaff89b2a859c68ad26b5

# Description

There's an empty machine frame by default in RD, but you can't add cables to it.

# Steps to Reproduce

# What you Expected

It to work

# What Actually Happened

### PR DESCRIPTION
**Pull request by GeneralVeers25**
Fixes numerous small issues and bugfixes.

Closes #19332 
Closes #19331 
Closes #19317 
Closes #19403 
Closes #19395 
Closes #19396 
Closes #19348 
Closes #19244 

Also Issues #19199 and #19165 aren't related to Roidstation specifically.

:cl:
 * rscadd: Roidstation: Nanotrasen Internal Affairs has mandated that the station be equipped with more espionage-capable general intercomms. And also light switches.

### CODE REVIEW

**Comment by GeneralVeers25** [comment]
Keeps fucking up so I'm gonna try again.

**Comment by ShiftyRail** [comment]
@GeneralVeers25 It's not a Travis fail

**Comment by GeneralVeers25** [comment]
Reopened because I'm being dumb.

**Comment by jknpj** [comment]
Tell cyberboss

**Pull request merged**
