### PR TITLE
Allows merch computer food to be poisoned by does not tip backdoor

### PR DESCRIPTION
**Pull request by ghost**
[content][tweak]
Seemed thematic with cargo.
Also standardised the poisoning of food effects, allowing for more variety with each.

:cl:
 * rscadd: Cargo merch computers are now no longer safe from the "does not tip" backdoor item.

### CODE REVIEW

**Comment by Eneocho** [comment]
How do you explain it IC though? The explanation for the Pizza is that they poison it before sending it to you since you're a "does not tip" monster. How do you explain the merch computer food?

**Comment by ghost** [comment]
> How do you explain it IC though? The explanation for the Pizza is that they poison it before sending it to you since you're a "does not tip" monster. How do you explain the merch computer food?

Sent to the station too as fast food?

**Comment by WindowsErrors** [comment]
i'm fine with it

fuckers keep leaving their Takis wrappers and hot sauce smegma all over the floor of the cargo lobby anyways

**Comment by Eneocho** [comment]
> Sent to the station too as fast food?

I've always felt the merch vendor synthesizes what you buy in the moment instead of delivering it, though I guess that works?

**Comment by Kammerjunk** [comment]
this doesn't look good

**Comment by jwhitak** [comment]
@Kurfursten 

This PR changes how poisoned pizza works and is not documented in the title/changelog. Previously, each pizza would have a specific poison. New PR combines all the lists. Secret antag idea I had was ruined. This is not enough to revert but dear lord please someone audit this man's PRs before merging, especially if it's less than 24h old...

**Comment by Kammerjunk** [comment]
ok actually let me quantify that

as far as standardising food poisoning goes, it looks like it combines several lists of unique reagents that were specifically relevant for their respective pizzas (mutagen for veggie pizzas, infected blood for meat pizzas, bad trips for shroom pizzas, and the big roulette wheel of fun for margaritas) into one big static list that's the minimum possible set of possible reagents for any poisoned snack.
without really knowing how static `static` is in DM, it doesn't look overrideable for inherited snacks that may want a _different_ set of reagents, not an _extended_ set (which is the minimum thing a base function should do).

moving on, it just seems like an unimaginative standard. infected blood on a meat pizza is kinda funny. maybe less so in a freshly-grown poppy (a grandchild of /snacks)

**Comment by Kurfursten** [comment]
You know what, there is a very reasonable point to be made there. For my part, I was kind of bothered by the typecheck to see if it's a ZAM food. In reality, the best way to do this would be to make it OOP. Makepoisonous on grey food should just add water because that's funny for grey food. Infected blood just for meat products as Kammer says. etc etc

**Pull request merged**
