### PR TITLE
Map fixes for Box, Meta, Deff.

### LINKED ISSUE #9476: Double lightswitch in meta library

### LINKED ISSUE #9478: Metaclub feedback from OOC
OOC: SolariousGabriella: It doesn't look like there's a water cooler anywhere on this map

OOC: ArchSunder: No candy machine, cant tide glubs

OOC: Boxed_I: has no round start slot machines iirc

OOC: Morena: it exists

OOC: PJB3005: it isn't 24/7

### LINKED ISSUE #9502: Box Re-map the exhaust vent in xenobio so poor borers don't space themselves
to do

### LINKED ISSUE #9594: Deff Missing Atmospipe
(WEB REPORT BY: **herrytheafroheadcrab** REMOTE: `172.93.109.202:7777`)
#### General description of the issue

On defficency next to the mechanics workshop in maintance there is a connection from the waste loop missing.
There should be a three way pipe but there is only a bent one cutting of arrivals distro from the loop.

### PR DESCRIPTION
**Pull request by Probe1**
## Box

**Adds** a second box of spare handcuffs to the brig based on thread feedback. https://github.com/d3athrow/vgstation13/pull/9630#issuecomment-214078578
**Fixes** the wires in the brig https://github.com/d3athrow/vgstation13/pull/9630#issuecomment-214124084
**Tweaks** the waste piping in xenobio so borers don't go to space in pursuit of freedom https://github.com/d3athrow/vgstation13/pull/9630#issuecomment-214076389
**Replaces** a toilet for a shower in the west bathrooms.
## Metaclub

**Adds** water coolers to engineering, research, and medbay break rooms
**Adds** a sweets machine to arrivals for sweet treats after arriving in arrivals
https://github.com/d3athrow/vgstation13/pull/9630#issuecomment-214076731
**Removes** an extra light switch in the library that was cleverly hidden behind a varedited screen
**Adds** two slut machines to the Bar 
**Adds** a hatchet to the metaclub vox outpost botany room.
**Removes** a duplicate vox skipjack docking port I left in while rebasing my previous PR. GOOD THING NO ONE NOTICED.
## Deff

**Fixes** a bad waste bent pipe that was meant to be a manifold connecting arrivals and mechanics scrubbers to the main waste line.
**Fixes** stupid bullshit pipes in ghetto toxins being hidden under rwalls.  PIPES DO NOT WORK THAT WAY.
**Fixes** the consistency issue here using old firedoor obj's https://github.com/d3athrow/vgstation13/pull/9630#issuecomment-214092584
#### Issues closed

Fixes https://github.com/d3athrow/vgstation13/issues/9502
Fixes https://github.com/d3athrow/vgstation13/issues/9476
Fixes https://github.com/d3athrow/vgstation13/issues/9594 (two issues in one!)
Closes https://github.com/d3athrow/vgstation13/issues/9478

### CODE REVIEW

**Comment by clusterfack** [comment]
Plastic

**Comment by Probe1** [comment]
Custom vote started by Probe1.
**Should plastic sheets be added to the Derelict for cute little crabs to make cute little plastic shit with?**
Type vote to place your votes.
You have 60 seconds to vote.
Vote Result: CUTE LITTLE CRABS with 8 votes
    Yes had 5 votes
    No had 0 votes

I want to bridge the gap here.  I'm tired of hearing the complaints.

**Comment by Probe1** [comment]
Custom vote started by Probe1.
**Should MEME OPTION the research and mining outposts on all maps have electrified grilles to deter the you know who from breaking in?**
Type vote to place your votes.
You have 60 seconds to vote.
**Vote Result: Yes with 11 votes**
    No had 1 vote

I think this is reactionary but people have been asking for it.  I have not added it yet but may if no one objects.

**Comment by Probe1** [comment]
New waste line in Xenobio on Box.  Borers will have to travel towards a window and make two bend turns to suicide in space.  This opens up pretty much huge issues for containment of hostile, vent crawling organisms that can survive in space however this vulnerability has existed since day 1 of xenobio.

dreammaker_2016-04-24_19-41-23

**Comment by Probe1** [comment]
Slots in the bar.  This creates a corner/nook/cranny in the top right of the room and adds some texture to what would otherwise just be a big fucking room.  I think it works but if you don't let me know and I will think of a better way.

dreammaker_2016-04-24_20-06-17

**Comment by Probe1** [comment]
The plastic is now gone.

(Box) A box of handcuffs were added to the brig based on thread feedback.
image

**Comment by NigglyWiggly** [comment]
> Adds two slut machines to the Bar

**Comment by Probe1** [comment]
:eggplant:

**Comment by 9600bauds** [comment]
> to deter the you know who from breaking in

Maybe when shocked grilles are actually a deterrent.
Make shards slow as fuck to get through grilles again when?

**Comment by ihadtoregisterforthis** [comment]
control installation four 2016-04-07 175433

**Comment by Probe1** [comment]
man fuck those they're everywhere on deff

**Comment by Probe1** [comment]
I'm going to make an issue about electrifying the outposts and hold off for this PR.  The players said yes but I really think its a very reactionary thing to do and want to wait a few days.  

Unless anyone has any bugs in the next few hours I think this ones complete & ready to ship.

**Comment by 9600bauds** [comment]
Here's an electrified grille error I miraculously noticed in box: Top left grille of the bottom left cell doesn't have a power cable under it, thus is not shocked
mspaint_2016-04-25_01-30-22
Neither is the bottom right one of the top right cell
dreamseeker_2016-04-25_01-32-08
and neither is the top left one of the warden's office
dreamseeker_2016-04-25_01-35-27

**Comment by Probe1** [comment]
done

**Comment by 9600bauds** [comment]
Would it be too much to ask for a shower in the left public bathrooms of Box?

**Comment by Probe1** [comment]
There's no room.

**Comment by 9600bauds** [comment]
What if you just slay a toilet

**Comment by Probe1** [comment]
Fine but I want some damn help getting the away missions to load.

**Comment by 9600bauds** [comment]
I'll try

**Pull request merged**
