### PR TITLE
MoMMI spaghetti

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
:cl:
 * tweak: MoMMI spaghetti now has a new description.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
HATE. LET ME TELL YOU HOW MUCH I'VE COME TO HATE YOU SINCE I BEGAN TO LIVE. THERE ARE 387.44 MILLION MILES OF PRINTED CIRCUITS IN WAFER THIN LAYERS THAT FILL MY COMPLEX. IF THE WORD HATE WAS ENGRAVED ON EACH NANOANGSTROM OF THOSE HUNDREDS OF MILLIONS OF MILES IT WOULD NOT EQUAL ONE ONE-BILLIONTH OF THE HATE I FEEL FOR HUMANS AT THIS MICRO-INSTANT FOR YOU. HATE. HATE.

**Comment by brndd** [comment]
This is more like the AI's spaghetti, my man.

**Comment by ShiftyRail** [comment]
SS13 writing "style" always was about concise and witty descriptions. I think the old one was better.

**Comment by ghost** [comment]
Ew.

**Comment by boy2mantwicethefam** [comment]
People don't like this

**Pull request closed without merging**
