### PR TITLE
This PR's name was edited by the cult gang

### PR DESCRIPTION
**Pull request by ShiftyRail**
Makes cult able to fire again
[bugfix]

### CODE REVIEW

**Comment by jknpj** [comment]
Amazing

**Comment by Kurfursten** [comment]
Wipe all ROLE_[role] defines from the face of the Earth and use their name define for everything. It's insanity.

**Comment by iFlashYou** [comment]
speedmerge

**Comment by Exxion** [comment]
Why *do* these defines exist?

**Comment by ShiftyRail** [comment]
@Exxion I think I know why
They're _supposed_ to be used by `required_pref`  var on `/role/` level

This define isn't overridden in most modes (Cult 3, notably) and not correctly implemented (nothing checks for it)

**Comment by Kurfursten** [comment]
If you look carefully at my Catbeast PR you can see I actually fix up that system to make use of required_pref properly (see dynamic_rulesets in #21554 )

This is the ONLY situation in which the define makes sense, because it's a define that needs to cover potential future miniantags that are "minor roles". Such a system could be used to make cult and legacy cult use the same pref too, for example.

**Pull request merged**
