### PR TITLE
Various tweaks and additions to Box, added new RnD server and console to derelict

### PR DESCRIPTION
**Pull request by bthomas2**
:cl:
 * rscadd: Box: added Derelict RnD server and console, added beans to maint crate, hair dye to dorms.
* tweak: Box: gave captain some new items, added misc items to station, changed salvage shuttle.
 * rscdel: Box: removed, moved or changed a few items.

cslider
fixup
fixup2
fixup3
fixup4
fixup5
fixup6
fixup7

### CODE REVIEW

**Comment by brndd** [comment]
You did it, champ! Well, almost. You used the `step_x` and `step_y` vars which break smooth movement. Replace them with pixel_x and pixel_y. You can do this with a text editor by opening the map file and doing a search-and-replace. There's also a Python script in the maptools folder that does this for you.

**Comment by SonixApache** [comment]
You may want to preface your changes with "Box:" so people know what map you're talking about

**Comment by Kurfursten** [comment]
Very nice, you got that diff down to a reasonable number. You're practically a mapper now.

**Comment by SonixApache** [comment]
😕

**Pull request closed without merging**
