### PR TITLE
Staffs can now only be fired by wizards

### PR DESCRIPTION
**Pull request by ShiftyRail**
[balance] [tweak]
As requested by @iFlashYou.

### Reasoning : 

Staffs are extremely powerful and can gunk rounds by themeslves even if after the wizard is dead.
They can also be used to undo whatever chaos the nerd managed to instill.

I have no strong feelings about it. On the one hand, I understand the general idea behind it. On the other hand, this chaos, fun, and emergent gameplay is what makes ss13 what it is.

:cl:
- tweak: Staffs (change, necromancy...) can now only be used by wizards.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
My vote goes out to the emergent gameplay. Besides the wiz has plenty of resources for managing their staff if they don't want it used against them, including a whole spell about just that.

Besides, if a traitor gets hold of a staff, then good for him. It's not like he has lmaoblink+lmaobind to make it much worse either.

**Comment by LumpyGiraffes** [comment]
> My vote goes out to the emergent gameplay. The wiz has plenty of resources for managing their staff if they don't want it used against them, including a whole spell about just that. And un-staffofchanging people after the wizard dies seems fine to me, it's always chaotic, people never manage to unchange everyone, and it's not like the wizard's _effect_ on the round gets reverted.
> 
> Besides, if a traitor gets hold of a staff, then good for him. It's not like he has lmaoblink+lmaobind to make it much worse either.

Exactly this

**Comment by Kurfursten** [comment]
Hear me out. The fact that the staff can gunk a round after the wizard is gone is *part* of the purchase.

Why do you buy summon guns? It's arming the crew. Isn't that insane and suicidal? No, it's because giving everyone guns and pseudoantag status will generate chaos and gunk for the shift. The round that inspired this PR was a shift where the wizard literally was caught and killed less than 60 seconds after arriving on the station, but his staff of change warped the shift -- and I think that's actually an interesting purchase choice.

And the beautiful thing is the temptation of power. Iroquois almost cremated that staff of change right away. Almost. But oh, the seduction of possibilities.

**Comment by SonixApache** [comment]
I think this is a good change. Fuck non-wizards using magic artefacts of round-fucker +1.
Did you ensure they don't work in turrets either?

**Comment by bathosbathtime** [comment]
I don't like this change.  Hard limiting player options sucks.

**Comment by kilozombie** [comment]
SoC is the gift that dead wizards leave behind, like how a phoenix pops out of ash or whatever.
I appreciate this being put up as a PR for voting but I am very much against it. As Kurf describes, throwing artifacts into the mix is part of the way Wizard makes chaos.

**Comment by ShiftyRail** [comment]
Looks like this is not going to happen.

**Pull request closed without merging**
