### PR TITLE
Better spider eyes and more perception goodness

### LINKED ISSUE #26565: Mushmen darksight
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
5fe14f48b619bbc0c031b216d58d63a82b865cb7

# Description
Mushroom men, the creatures thriving in darkness, have darksight like humans. 
# Steps to Reproduce
Be mushman, walk into maint tunnel, get disappointed that you, creture that's supposed to live in darkness, can't see jack shit in said darkness
# What you Expected
To be able to see far in darkness, like ninja or at least gray
# What Actually Happened
I can't see shit and have to rely on flashlights that starve me

### PR DESCRIPTION
**Pull request by DeityLink**
#29932 but better

Fixes #26565

image
image
image
image
image
image

:cl:
* experiment: Giant Spider vision has been reworked, fixing transparency issues among other things.
* experiment: Catulism Syndrom (stage 3) now actually provides much improved vision in the dark. Tajarans also benefit from it by default. Incidentally, so can other human species should they have tajaran eyes implanted through surgery.
* experiment: Mushroom people also see better in the dark by default, but not quite as good as Tajarans, however their genetic spell now lets them switch to a different mode of perception that let's them see even better in dark areas than lit ones.
* experiment: Lastly Constructs can also see a bit better in the dark, although with a red tinge.

### CODE REVIEW

**Comment by SonixApache** [comment]
Holy shit, that's pretty fucking good. Does this affect darkvision in general?

**Comment by DeityLink** [comment]
> 
> 
> Holy shit, that's pretty fucking good. Does this affect darkvision in general?

I decided for my sanity that I wasn't gonna go through every single instance of mobs being able to see in the dark no. Stuff like night vision goggles work just like before. They could be improved later.

**Comment by Eneocho** [comment]
Consider adding this to grue as well since it's the only other nightvision mob that happens with any regularity in the serb, be it adminboos or SoC.

**Comment by SonixApache** [comment]
i hope this paves the road to creatures being able to actually see within their darkvision range

**Comment by DeityLink** [comment]
Repo conflict fixed.

**Pull request merged**
