### PR TITLE
some minor lightswitches

### LINKED ISSUE #35225: Asteroid Station's Head of Personnel office does not have a lightswitch

### LINKED ISSUE #35231: Boxstation medbay central area does not have a lightswitch
[box]

### PR DESCRIPTION
**Pull request by toomykins**
adds lightswitches to
* boxstation medbay
* roidstation HoP office
* roidstation HoP personal quarters
* roidstation abandoned smithy
fixes #35231
fixes #35225 
heres a screenshot of the most important one
image

:cl:
* tweak: boxstation's medbay now has a  light switch
* tweak: roidstation's HoP OFFICE, HoP personal quarters and the abandoned smithy now have a light switch

### CODE REVIEW

**Comment by jwhitak** [comment]
\>makes pr called minor light switches
\>boxstation medbay light switch

you absolute mad lad

**Comment by gurfan** [comment]
What's the point of having a light switch in medbay, especially in such a open place? There's never really a good reason to turn the lights off there, and now any assistant/clown/mime/whatever can just shut them off for shits and giggles.

**Comment by Exxion** [comment]
What's the point of having a light switch anywhere?
But yeah, that might not be the ideal place to put it

**Comment by pedr69** [comment]
remove medbay lightswitch

**Pull request merged**
