### PR TITLE
Added lightbulbs to some dark corners in Box

### PR DESCRIPTION
**Pull request by ValkyrieSkies**
library
cargo 

Added some lightbulbs to some pretty dark areas of Box such as in cargo, library, and the gateway.

[tested] [box]
## Changelog

:cl:
 * rscadd: Added some more lights to Boxstation.

### CODE REVIEW

**Comment by pedr69** [comment]
library one isn't really necessary imo, there's a desk lamp right there

**Comment by Inorien** [comment]
Desk lamps would be a hell of a lot better if they were the way they used to be (or powered by a cell or something) and not inextricably linked to and dependent on the room's APC

**Comment by ValkyrieSkies** [comment]
> library one isn't really necessary imo, there's a desk lamp right there

Mm, I recognize that, but if the round starts without a librarian then all the lamps start turned off as well as the lights, and it's kinda annoying to flick a lightswitch on only for an area of a room to still be dark thus requiring you then go and turn more lights on. Seems like the kinda thing you'd avoid when designing a room in the first place.

**Comment by Inorien** [comment]
The library one is good imo, I hate hitting the light switch and there's still a huge dark patch in the middle. I'm not sure if that one completely goes away with high efficiency lights like some of the other dark spots

**Comment by Pastamadness** [comment]
I actually think that the radio room being a dark room stuck in the middle of maint fits the theme of old backup machinery storage.

**Comment by ValkyrieSkies** [comment]
> I actually think that the radio room being a dark room stuck in the middle of maint fits the theme of old backup machinery storage.

If it were any other piece of machinery I'd probably agree, but it's a machine that can very easily pump out super lethal doses of radiation with a simple fuck-up so it seems a bit silly in-universe that it'd just be in a room with zero lighting for someone working on it.

**Comment by Pastamadness** [comment]
I don't think it's not in-universe for a galactic megacorp to forget deadly, old machinery in maint at all when we have deff.
It's still not a big deal anyway.

**Comment by Kurfursten** [comment]
> > I actually think that the radio room being a dark room stuck in the middle of maint fits the theme of old backup machinery storage.
> 
> If it were any other piece of machinery I'd probably agree, but it's a machine that can very easily pump out super lethal doses of radiation with a simple fuck-up so it seems a bit silly in-universe that it'd just be in a room with zero lighting for someone working on it.

doesn't it glow blue in use? the darkness makes it more obvious when it's in danger mode

**Comment by ValkyrieSkies** [comment]
By popular request I've removed the light and switch from the media server room, but I did place an abandoned flashlight in the corner.

**Pull request merged**
