### PR TITLE
mask of the goat

### PR DESCRIPTION
**Pull request by SonixApache**
requested by goat
image
this is as codersprite as it gets

if you want me to ruin more of your requests or otherwise make horrible looking content, 
[ko-fi](https://ko-fi.com/T6T31SDFQ)

### CODE REVIEW

**Comment by Kharkov72** [comment]
i mean yeah that's basically how the masks look

**Comment by Kharkov72** [comment]
gost

**Comment by SkowronX** [comment]
make the pupils horizontal

**Comment by SonixApache** [comment]
what pupils?
verti hori

**Pull request merged**
