### PR TITLE
Allows you to find arcane tampered pocket mirrors as small artifacts

### PR DESCRIPTION
**Pull request by JonathanSpaceStation**
## What this does
Wizards can currently arcane tamper mirrors to make them cursed; but you will almost never see one in game and I thought it was a waste and could potentially work as something interesting to find as a xenoarch find.

This adds them as possible finds; I opted to add them to the temple digsite on the basis that the house digsite currently has a lot of good / interesting finds already, although welcome to change this depending on how people feel about it.  

## Why it's good
Another artifact that can be found; the code for arcane mirrors already existed, this just makes them something you can find outside of extremely rare wizard shenanigans

## Changelog

:cl:
 * rscadd: Arcane Tampered Pocket Mirrors can be found in temple digsites as small finds

### CODE REVIEW

**Comment by pedr69** [comment]
just make arcanetamper apply to a random object on your screen instead of being a directed cast

**Comment by ErrorsWindows** [comment]
xenoarchs need to be goon-telesci pilled where half the stuff will either outright kill you, have some debilitating side effect, or is straight-up useless for practical gameplay

**Comment by JonathanSpaceStation** [comment]
> just make arcanetamper apply to a random object on your screen instead of being a directed cast

 just to be 100% clear this PR does not change how that spell works in any way; it just allows you to find a mirror that has been tampered in a digsite.

**Comment by Eneocho** [comment]
What does the tampered mirror do? Randomize your appearance?

**Comment by Eneocho** [comment]
The description for the tampered mirror artifact feels a bit out of place to me, even for a wizard-adjacent item.

**Comment by JonathanSpaceStation** [comment]
> What does the tampered mirror do? Randomize your appearance?

it randomises your species / appearance and name yes

> The description for the tampered mirror artifact feels a bit out of place to me, even for a wizard-adjacent item.

yeah its kinda bad but I wanted it to be distinguishable from a regular mirror; if only in a subtle way. I'll try and think of something better unless anyone has any suggestions

**Comment by SonixApache** [comment]
don't arcane tampered things get untampered when a wizard dies or something
will this cause issues with that

**Comment by JonathanSpaceStation** [comment]
> don't arcane tampered things get untampered when a wizard dies or something will this cause issues with that

It shouldn't do because as far as I can see, when a wizard dies its only the items that wizard has tampered that get untampered. That being said if a chaplain was to bless the mirror it would turn into a normal one; but I think that's a fine interaction to keep for this

**Pull request merged**
