### PR TITLE
Makes the Boxstation MoMMI nest a vacuum

### PR DESCRIPTION
**Pull request by brndd**
[box]

## What this does

Makes the Boxstation MoMMI nest a vacuum at roundstart.

## Why it's good

The MoMMI nest has a single airlock directly into space. If you open it, the air alarm annoyingly goes off, shutting the firelock, and if you open the firelock all your plastic bags and soap and sulphuric acid get sucked out into space. Because the fastest way to engineering from the MoMMI nest is to walk through space, it is nice to be able to open the airlock.

No organics should ever be in the MoMMI nest, and the only way for them to get into the MoMMI nest is to walk through a vacuum, so there are no downsides to making it a vacuum. Repressurizing it if necessary also only takes a couple of minutes due to the room's small size.

## Changelog

:cl:
 * tweak: Boxstation: MoMMI nest starts out as a vacuum

### CODE REVIEW

**Comment by pedr69** [comment]
your vents?

**Comment by brndd** [comment]
It is faster to crawl into the vent, come out in the recycling room, walk out the recycling room airlock and spacewalk to the aft port solars to get to engineering than it is to ventcrawl all the way there.

This just cuts out the unnecessary trip to the recycling room.

**Comment by Kurfursten** [comment]
Won't the room refill off the vent at roundstart within like a minute or two...?

**Comment by lol-and** [comment]
Nah. I like printing boards from the mommi nest when the rogue AI fucks with science

**Comment by gurfan** [comment]
The vent is just going to refill the room, isn't it? I agree that the place getting ZAS'd every time the door open is a problem but there are better solutions.
If you want to reinforce the "mommis only" idea, you can just remove the door and have the vents the only way of entering. If you just want to fix the airflow issue, you can just add a double door, cycling airlock, airtight flaps, double firelocks, whatever.

**Comment by brndd** [comment]
> The vent is just going to refill the room, isn't it? 

No, because I set the vent's external pressure bound to 0 (and ditto for the scrubber). The vacuum preset should do this automatically but it doesn't work for mapped-in presets due to, if I remember correctly, some technical limitations I was too lazy to overcome when I coded the presets.

> airtight flaps

I think MoMMIs can't pass under those.

edit: if you want to repressurize it, you can easily do so remotely from the Central Atmospherics Computer by setting the room's preset to Human.

**Comment by brndd** [comment]
> it IS faster to crawl to engi through the pipes

No it's not. I have timed this.

> and now that this is merged box is inconsistent with all the other maps which have the room pressurized roundstart

Box is the only one with a single airlock leading directly to space. Others either have no airlock or have a double airlock (Deff; Deff also has a direct airlock into maint so it couldn't be a vacuum anyway). Well okay, Synergy has a direct airlock into space, but nobody plays that map.

Wheel's one is also a vacuum just like Box.

**Pull request merged**
