### PR TITLE
Mannitol now makes you say stuff copypasted from some erased posts on disliked /tg/station merges.

### PR DESCRIPTION
**Pull request by Eneocho**
I've heard a lot of players ask for Mannitol lately. It apparently works as a brainmed on tgcode, so it now gives you a blurb on how you feel your mind healing with a small chance of saying one of the copypasted stuffs.

:cl:
 * rscadd: Mannitol is now TGfugeeworthy.

### CODE REVIEW

**Comment by Jackreturnswithaveangenace** [comment]
> "im sure this pr is good and all and i havent read the description but im leaving my thumbs down that wont change anything because i cant trust anything from shrek coder"

Going to kill myself the third time I see this said in game. Should be a bit more subtle.

**Comment by Eneocho** [comment]
Alright, how about this. I couldn't figure out a way to make that one line feel IC so I removed it and changed the "bee" one to be IC friendly.

**Comment by ghost** [comment]
stop

**Comment by Eneocho** [comment]
Alright, I can see when a lame-joke PR didn't land, closing.

**Comment by SonixApache** [comment]
i already added Mannitol as a subtle joke chem to meme TG creatures with, no need to blow it out of the water

**Pull request closed without merging**
