### PR TITLE
Taser/Egun projectile nerf

### PR DESCRIPTION
**Pull request by ghost**
This creates a 1,3 second delay between being hit by a taser bolt and actually getting stunned.
It also applies 75% movement slowdown immediately on hit.
This could hopefully change the meta of gunfights being immediately decided by landing the first taserbolt.

nweh

Basically you can retaliate with lasers(I think you can fire at least 2 or 3) or a taserbolt of your own within the 1 second of being hit.

🆑 
experiment: Getting hit by taser or egun projectiles now stuns after a 1.3 second delay instead of immediately. It slows you down between being hit and being stunned.
wip: The above is in as a trial of the change and will be reverted on November 3, at which point it will be polled on. t. Intigracy

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Also makes you scream every shot

**Comment by ghost** [comment]
Getting tazed is painful innit.

**Comment by ShiftyRail** [comment]
As much as I rely on them, if you do that, don't forget to adjust things like flashbangs.
I'd be okay with experimenting this.

**Comment by Accipitermaris** [comment]
This is an interesting change, although by no means an overhaul so it will create some eccentricities as it relates to other ranged means of stunning such as rubber bullets and flashbangs.

I may have shilled for this on here previously, but I think giving flashbangs a minimum timer of 3 seconds may alleviate that eccentricity should this get merged.

**Comment by ShiftyRail** [comment]
Worthy of note is that now that taser has a visual indication of pain (the scream), it means that secborgs can't randomly tase humans
I'm 100% okay with this

**Comment by Accipitermaris** [comment]
Oh wow I didn’t even think of that.
[It’s a FEATURE] [Honk] [IT’S LOOSE]

**Comment by aceedex** [comment]
Nice try but the healthhud hasnt dropped meatbag

Dont think its a bad change and willing to try it out tbh. Specially since it gives beanbags a niche of instant stun

**Comment by Accipitermaris** [comment]
The health hud drops in the gif but it’s pain damage. Is that human harm? The health scanner will register as someone in near-crit from pain (taser in the mouth) as having 23% or so health with 0 listed damage types much like having genetic damage.

**Comment by ghost** [comment]
Not a fan for this in maints with burn paincrit as easy as it is and we already had a light version of this with firefights in metastation brig just being whoever got stunned first by a longshot would just get back up, restun, and collect those balids on whoever got tased later in the exchange. Well-intentioned but not a solution.

If it does get merged, there needs to be an admin ruling on just lethaling first and letting the fryer sort it out.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I literally can't understand your post or how metastation brig relates @SarahJohnson489

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I literally can't understand your post or how metastation brig relates @SarahJohnson489

**Comment by ghost** [comment]
The intent of the pr is to give the tased a chance to shoot back which may be an electrode or enough to paincrit before they are stunned

Meta's brig has a long hallway and occasionally has blind fire electrode firefights in which someone gets off a taser shot before they are stunned and their shot carries on to stun the other shooter.

In the event this happens the one who was stunned first gets autovictory by getting up first to restun and cuff or kill. This isn't a solution.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Okay, that makes more sense, it means if you manage to tase the guy during your 1.3s grace period you instawin in a 1v1

**Comment by ghost** [comment]
yeah

**Comment by ghost** [comment]
That's not how it works.
If X stuns Z
Then Z stuns X
X can stun Z again since Z falls over before X.

**Comment by kilozombie** [comment]
> That's not how it works.
> If X stuns Z
> Then Z stuns X
> X can stun Z again since Z falls over before X.

Think really really really hard about what you just wrote
Z got stunned first, so Z gets up first

**Comment by ghost** [comment]
>Think really really really hard about what you just wrote
Z got stunned first, so Z gets up first

Z got stunned twice, 2nd time being after X got stunned.

**Comment by ghost** [comment]
Yeah, I'm thinking about the situations where they're on the bottom of the mag, edge of LoS shooting, they just miss for some godawful reason, corners and obstacles that're being shot around. Basically anything where it's not as simple as just tase him again.

**Comment by kilozombie** [comment]
> Z got stunned twice, 2nd time being after X got stunned.

X stuns Z. This is a 15 second stun but only applies 1.3 seconds in. Right before that 1.3 seconds happens, Z shoots a stun at X and hits. By the time this stun hits X, Z's stun has already allotted at least 1.3 seconds, but probably more due to travel time.

This means X's 15 second timer starts when Z's timer is already at 11-13 seconds. This means Z, who was _stunned first,_ gets up a good few seconds before the person who should actually win the fight due to being more robust on the initial shot.

**Comment by ghost** [comment]
The stun doesn't start progressing until it actually stuns.
Besides, after Z gets stunned for the 2nd time the stun timer resets, doesn't it?
And you still waste some time picking up your gun after standing up.

**Comment by kilozombie** [comment]
> The stun doesn't start progressing until it actually stuns.

...What the fuck are you talking about?

If it's a 15 second stun, and there's an additional 1.3 second timer on top of that, that's a 16.3 second wait period. Z is _still running that down first,_ getting a head start over X who should have won. Just because in the code the timer hasn't started running yet doesn't matter, because it still factors into the absolute duration until X or Z can stand up and win the fight. In this case, Z will get up first, having at _least_ a 1.3 second head start.

I'm still in favor of this change for many other reasons, but this has to be fixed, otherwise it's stupid as hell.

**Comment by ghost** [comment]
But Z gets stunned twice so you might as well consider that X got stunned first, turning your argument around.

**Comment by kilozombie** [comment]
> But Z gets stunned twice so you might as well consider that X got stunned first, turning your argument around.

Why does Z get stunned twice? Are you relying on X having the foresight to wait out their timer as long as possible to get a second stun in on Z when they've fallen over? What if X is out of taser shots? This makes no sense.

**Comment by Accipitermaris** [comment]
“Worst shooter wins” in stun-stun stalemates seems to be an unavoidable contrivance of this design.
I hate not supporting this though because I do appreciate attempts to rework this stuff. Maybe there’s another way of doing it, idk

**Comment by ghost** [comment]
I'm relying on X dodging Z's stun, AND IF he fails to dodge it(gets hit), to then reapply the stun on Z.
Being out of ammo after one stun is a fringe case tbh.
But this whole issue could probably be worked around with some more code anyway.

**Comment by kilozombie** [comment]
> I'm relying on X dodging Z's stun, AND IF he fails to dodge it(gets hit), to then reapply the stun on Z.

Remember, that's a 1.3s (or less) grace period for X to figure out what just happened, line up the crosshairs on a horizontal man, and shoot a taser without it being blocked, flying overhead (extremely common), or just flat out being too late.

**Comment by ghost** [comment]
I suppose you're right.
But keep in mind the same thing applies to Z. He has 1,3seconds to retaliate by succesfully hitting X with a taser.

**Comment by ghost** [comment]
I wonder if it would be possible for taser bolts you fire to have 100% miss chance when you get hit yourself while still being able to hit your opponent with harm laser.

**Comment by ShiftyRail** [comment]
How about the shot making you drop your items in hand, and a double-tap still being an instant stun.

**Comment by ghost** [comment]
You mean that the 2nd bolt would end the delay early? Could be done I think.
Not so sure about dropping your weapon since half of the reason for the grace period is being able to retaliate (with something that isn't another stun i.e bullet or harm laser)

**Comment by coldcola** [comment]
is this another "i got kill nerf pls" because it's clearly wasn't thought out properly.

**Comment by Durgen** [comment]
exciting suggestion. It’s worth testing.

**Comment by strawberrytan** [comment]
I support the change and I want to see how it turns out in game

**Comment by Shadowmech88** [comment]
This also opens up the opportunity to have things that increase the delay without making you outright immune to stuns.

**Comment by kilozombie** [comment]
What if getting stunned during the grace period knocked you down instantly, and maybe increased the stun by a few seconds? That'd make the weird 1v1 situations a tad more manageable.

**Comment by SonixApache** [comment]
Would be interesting to test out.

**Comment by Dacendeth** [comment]
I have a very serious question, does this apply to lasertag tasers?

**Comment by ghost** [comment]
It doesn't.

**Comment by Caboozles** [comment]
Just make certain clothing reduce your stun timer. IE Sec armor can chop that stun by 5 seconds or so. The change has a nice idea, but there’s no reason a well-armored person should take it as raw as a naked man.

So from a sec standpoint, you should keep your armor, and if the suspect is heavily armored you shouldn’t be alone.
From an antag standpoint, that taser is strong, but you should be wary when engaging sec directly unless you’re prepared. 

People want stuns to be less impactful, just make it so they can be mitigated. Armor can soften lasers, why not tasers?

And obviously make it so only armored hardsuits should count.

**Comment by ghost** [comment]
After a conversation with @MadmanMartian I've came to a conclusion that being able to stun your enemy during the grace period and stand up before him is, in fact, a feature not an error.

**Comment by ghost** [comment]
I don't like this at all. All it'll do is piss off people who play Security. What'll happen is most of the time when they go to tase a criminal, they'll just get counter-tased and lose the fight. This will cause more Security to want to switch to beanbag rounds, but we already know that they can't because if an AI or Cyborg exists, it's harm alarms everywhere and they'll be further impeded from doing anything.
While instant-stun based combat is frustrating and I don't like it, this doesn't fix anything. There's still tonnes of insta-stuns and by removing ranged one you just... move the goalposts. What's next, we make slipping on water a 50/50 chance, sometimes instead of tripping on lube you just slide forward? Stungloves, completely removed. Then we add stamina and disablers, beanbag shots lower stamina, nerf chloral and other stunning chemicals because that's what people would move to next, before we know it the only way combat works in this game is hitting people repeatedly with lethals and they might get stunned and lose or just die before hand.
If you want to fix the combat you need to sit down and critically think about the system as a whole, not pigeonhole on one aspect you don't like with kneejerk-tier reactions with minimal discussion. It's not something just one or two people can do either, it takes a lot of people and a lot of work.

TG already uses the disablers and stamina system, and as someone who played there for a while it's not good, because they made the same oversights, they left in other insta-stun systems, so nearly everyone opts for them. In the few months I played there, I was apprehended with a disabler a total of twice, most would rather opt to draining their entire gun with two stun shots than faff around spamming disabler shots, or otherwise using alternative insta-stuns. Stunsticks, slips, pushes, and mostly, resorting to straight up murder, instead of using this stamina system because the alternatives are too powerful.
We whine that they're validhappy children but it comes as part of the combat system. When the "good guys" have a smaller arsenal in dealing with the "bad guys", they get frustrated and begin to act in ways outside of the RP and slightly outside of the rules. 

I went off on a tangent and left this unfinished because I got bored of typing, but in short:
no this is not a good idea, please stop making kneejerk tier changes and instead sit down in a public focus group and think of the bigger picture.

**Comment by SonixApache** [comment]
@Caboozles getting tazed while wearing clothes should do burn damage and nothing else

@morenaaa holy shit you need to chill out

**Comment by ghost** [comment]
>What'll happen is most of the time when they go to tase a criminal, they'll just get counter-tased

I'd say this will actually happen less than most of the time.

**Comment by DeityLink** [comment]
You just saved spess.

**Comment by god-jesus** [comment]
put this in so we can see how shit/not shit it'll feel

**Comment by SGuivenne** [comment]
@morenaaa Just do what I do as sec and try to systematically emotionally break the AI.

**Comment by bathosbathtime** [comment]
Dealing damage takes every life tick to take effect.  When someone is shot, there is often a moment that they keep moving an acting after they get hit before they fall over dead.  This is a good feature that simulates the carrying over of momentum, but also means stuns are objectively stronger.  While stuns still have a variety of strengths over lethals even with this change (liability, cost, munition, having to hit multiple times, and so on) I still feel that this PR is very good as it brings tasers more in line with how damage is handled, even if it doesn't use the same exact system.

**Comment by SGuivenne** [comment]
Of course this goes into the problem of why unless you can instantly shoot someone into crit or insta gib them lethals are generally not worth protracted gun battles.   Even if you score a hit you'll generally pause long enough trying to do a follow up that you'll eat shit immediately.

**Comment by Ratvar** [comment]
Make it so you can't control your movement while you are in pre-stun? Like sliding on ice, carrying momentum without real control over the body. Makes it harder to "he got stunned first so he wakes up first and valids me" while still giving a chance to do something

**Comment by Intigracy** [comment]
fyi the "damage" the taser deals is agony/halloss, the same as the holodeck weapons.

**Comment by Intigracy** [comment]
I'm going to merge this for a week until next Saturday at which point it'll be polled on.
Changelog edited to reflect as such.

**Comment by Kammerjunk** [comment]
btw tasing isn't harm this shouldn't have to be said

**Comment by DeityLink** [comment]
Tasers having a chance to cause heart attacks based on the health of your heart organ or a cardiac disability when?

**Comment by Kammerjunk** [comment]
fucking never

**Pull request merged**
