### PR TITLE
Makes hall near dorms in packed flow smoother

### PR DESCRIPTION
**Pull request by ghost**
[packed]
The main fix in this PR:
image
Should make this map clearer to navigate.

Rearranged command areas
image

:cl:
 * tweak: Packed now has nicer flowing halls near dorms

### CODE REVIEW

**Comment by Eneocho** [comment]
The Gateway hallway is painfully small. Feels out of place.

**Comment by ghost** [comment]
> The Gateway hallway is painfully small. Feels out of place.

Fixed

**Comment by PrimeDSS13** [comment]
this seems like it would just map the make a more generic
perfectly straight and rectangular hallways are boring
image

**Comment by cloutcode** [comment]
I like the command area. The hallway fix, I could do without, as it does not address the issue of packed, in my opinion of all the shit in the middle being there in the first place, rather than being hard to navigate. Also what PrimeDung said

**Comment by ghost** [comment]
Seems unpopular, will close and ask for proper feedback

**Comment by Eneocho** [comment]
Aww, I liked it.

**Pull request closed without merging**
