### PR TITLE
Metaclub Bar Changes

### PR DESCRIPTION
**Pull request by beesil**
[meta][qol] A lot of small fixes, qol, and aesthetic changes for the Metaclub bar.

- Adds a bandolier in the backroom, as well as a stack of glass and metal in the closet.
- More space and tiles (rather than wood) behind the bar.
- Moved ice cream machine to the kitchen.
- Fixed a rogue fake wood tile underneath a door.
- Moves the trash can over to the vending machines.
- Adds curtains and tomato stains to the stage.

Before: image
After: image

:cl:
 * rscadd: Adds a bandolier, as well as a stack of metal and glass to the Metaclub bar.
 * tweak: Slight aesthetic tweaks to the Metaclub bar. Includes making more space behind the counter, adding tiles behind the counter, moving the ice cream maker to the kitchen, moving the trash can, and adding curtains to the stage.

### CODE REVIEW

**Comment by Tehsapper** [comment]
the new arcade machine needs a stool as well.

**Comment by incakola** [comment]
tomato stains, why?

are the windows and windoor still under the curtains? is keeping the windows & windoor a good idea?

**Comment by FudgePucker** [comment]
People didnt like the last performance

**Comment by beesil** [comment]
@Tehsapper Fixed the stools and updated the screencap.

@incakola For flavor mostly, meta feels a soulless currently imo. The windows and windoor are still there, but could be easily removed.

**Pull request merged**
