### PR TITLE
Pharaoh's Riches

### PR DESCRIPTION
**Pull request by Inorien**
https://www.youtube.com/watch?v=d13DV0gMDXE

## What this does

Adds a new variant of the slot machine. "Pharaoh's Riches" is an Ancient Egypt style machine with symbols like reed, bird, ankh, eye of horus, etc. If you get 10 ANKH RANKHS (patent pending) from lining up 3 ankhs, you get to the bonus stage, where you will have a chance to win the jackpot. The jackpot accumulates every spin cost in addition to a random base amount and persists across rounds. 

At least it'll do all that when I write it

## Why it's good

https://www.youtube.com/watch?v=d13DV0gMDXE

## Changelog

https://www.youtube.com/watch?v=d13DV0gMDXE

### CODE REVIEW

**Comment by Inorien** [comment]
closing this while its on backburner

**Comment by Inorien** [comment]
i am very retarded

**Comment by Kurfursten** [comment]
I have a compromise proposal for you:
1. Ditch all the special mechanics
2. Cut the sound down to 5 seconds. You may include up to 3 variants like the original slots
3. Ask our spriters for an egypt variant of the slot

This could be a realistic path to finishing your PR even if it doesn't accomplish everything you wanted.

**Comment by Kurfursten** [comment]
Closing because you've said you don't have time to work on it. You can request this be reopened.

**Pull request closed without merging**
