### PR TITLE
Allows you to wear bedsheets as capes

### PR DESCRIPTION
**Pull request by doobiedoo23**
They fit in your back slot.

You can finally live out your fantasies as a middle-aged LARPer with these sick new capes, here's what a few of them look like in action: 

There's a new back sprite for every bedsheet in the game.

### CODE REVIEW

**Comment by gbasood** [comment]
Edited so the image is embedded
Also, holy shit, what's with all the people using merge commits
What Git client did you use?

**Comment by doobiedoo23** [comment]
I'm using Git desktop

**Comment by gbasood** [comment]
Don't.
Use SmartGit or Git Bash. Github for Desktop is awful.

**Comment by Kurfursten** [comment]
What ever happened to good old American command line? Is patriotism dead?

**Comment by Exxion** [comment]
The merge commits are irrelevant with auto-squash anyway, aren't they?

And I admit to using GitHub for Desktop too. Works well enough for me for most purposes and I use command line for the rest

But I also never have merge commits because I always make sure merges are just fast forward when I can

**Comment by gbasood** [comment]
@exxion Actually they still fuck up git history
Also gross

**Comment by gbasood** [comment]
@doobiedoo23 For now this is fine but in the future you'll want to use a client that doesn't merge commit without you telling it to

What does a player do to obtain these currently?

**Comment by doobiedoo23** [comment]
gotcha, i'm a total baby coder but i'll keep it in mind

all players have to do is find a bedsheet (which, conveniently enough spawns on a bed) and put it on their back slot

**Comment by gbasood** [comment]
And what selects the color of the bedsheet?
Also, add a changelog file.

**Comment by PJB3005** [comment]
@gbasood duh, the bedsheets you're wearing determines it.

**Comment by ComicIronic** [comment]
Looks nice, let @clusterfack decide if the commits are going to kill it or give it NFD.

**Comment by clusterfack** [comment]
Commits are fine, auto squash will take care of them, just change the commit message

**Comment by TheFriggenSawbones** [comment]
next we need to add bedsheet ghosts

**Comment by Probe1** [comment]
"""""ghosts""""""
anonymous-kkk

**Pull request merged**
