### PR TITLE
Chaplains can't be vampires anymore

### LINKED ISSUE #20159: Roundstart Chaplain can Spawn as a Vampire
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
22f57f09e918f0894715cf90706b4b603b88fc61

# Description

This kills the Chaplain
# Steps to Reproduce

Spawn as chaplain, be roundstart vampire
# What you Expected

To not spawn as a vampire and not die
# What Actually Happened

Dies screaming and on fire and burns to ash.

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #20159

### CODE REVIEW

**Comment by CptWad** [comment]
hold on
better extend that to cultists too

**Comment by ShiftyRail** [comment]
Nice, it's also not in there

**Comment by CptWad** [comment]
predicted like a true wizard

**Comment by MadmanMartian** [comment]
This shows a bigger issue, dynamic rulesets aren't respecting the roles restricted and protected jobs

**Pull request merged**
