### PR TITLE
Adds vox meat

### PR DESCRIPTION
**Pull request by MadmanMartian**
:cl:
 * rscadd: Butchering techniques have been developed so that you can butcher vox to yield vox meat. We are not sure why this was developed, but it has been.

### CODE REVIEW

**Comment by DamianX** [comment]
subtype of rawchicken so we can still make trader nuggets?

**Comment by beesil** [comment]
Mmm...

img

**Comment by kilozombie** [comment]
Just like chikun used to make

**Comment by Hoshi-chan** [comment]
So it's still chicken, then? So long as it's still chicken.

**Pull request merged**
