### PR TITLE
Actually adds the config option for enabling wages

### PR DESCRIPTION
**Pull request by Intigracy**
The code already exists for it sans the actual config.txt change.

https://github.com/d3athrow/vgstation13/pull/9310/files#diff-d1d7be6cb37d19d5574375c4c884b805R541

Enabled by default.

@Clusterfack or @D3athrow

### CODE REVIEW

**Comment by clusterfack** [comment]
Oh thats so cute you think you can modify server's configs like that :blush:

**Comment by Intigracy** [comment]
That's why I mentioned you you fag.

**Comment by PJB3005** [comment]
@clusterfack wanna bet I can fuck with the server config given enough fucking with advanced proccall?

**Comment by clusterfack** [comment]
@PJB3005 You literally have secret repo access, you can modify server configs anytime you damn well please

**Comment by PJB3005** [comment]
@clusterfack :^)

**Comment by Probe1** [comment]
giddyup

**Comment by clusterfack** [comment]
Remind me about this later

**Pull request merged**
