### PR TITLE
Extra ghost spells

### PR DESCRIPTION
**Pull request by ghost**
image
[tested][qol]
Just makes these clickable HUD things. Also uncomments station holomap one and makes it functional.
:cl:
 * rscadd: Ghosts can now become a derelict MoMMI, become a space hobo, teleport, toggle sechud and hide ghosts from their spells

### CODE REVIEW

**Comment by Kurfursten** [comment]
Spells *feel* like they're supposed to be there for things you might do frequently, like haunt, jump in/out of your corpse, boo, etc. Not one time actions to stop being a ghost. Maybe that's just me who feels that way though.

Maybe instead of 3 buttons to become mommi, space hobo, mouse you could have one button for "New Character" that would then present you with those 3 options.

**Comment by Dacendeth** [comment]
I agree with Kurf, I dont really feel the become hobo/mommi/mouse need to be spells, everything else is good though.

**Comment by PrimeDSS13** [comment]
This is super bloated as is.

**Comment by PavelCIA** [comment]
bloat

**Comment by Kurfursten** [comment]
Lack of support

**Comment by ghost** [comment]
Will rework this idea into something that isn't spells one day.

**Pull request closed without merging**
