### PR TITLE
Gives mechanics Engine access

### PR DESCRIPTION
**Pull request by west3436**
The Mechanic is immunized against all dangers: one may call him a useless role, parasite, assistant with gloves, it all runs off him like water off a raincoat. But tell him to setup an engine and you will be astonished at how he recoils, how injured he is, how he suddenly shrinks back: "I don't have access.”

:cl:
 * rscadd: Mechanics now have engine access.

### CODE REVIEW

**Comment by RonPaul08** [comment]
Why not just remove assistant plus and put the equipment in R&D where it belongs rather than giving shitters access that will be exclusively used to shardbomb

**Comment by jwhitak** [comment]
- This PR fits in line with other cross-departmental access. Robotics has access to R&D, Scientist have access to robotics.
- It removes the "I'm a mechanic I can't do an engine" excuse.
- The current expectations of those in the Engineering department include setting up power. Mechanics cannot do this: If you are a mechanic, you literally have to break in to set up even an AME, or spend your own money on cargo parts (which mechanics can't open either because it requires engine access). Without breaking into somewhere, all a mechanic can do alone would be a Solars-related or Treadmill-related engine. Good thing they have EVA access.
- Adding engine access does not allow shardbombs on Box without hacking or outside aid, since the shard is in the secure storage that requires CE access to open (or otherwise breaking in, which this PR doesn't affect).

Despite all of the above, this is a cursed PR, probably even deserving of the grudge code label, because this comes after the Boxer incident of threatening to perma the Mechanic who won't set up power. Prepare to be thumbed down, west.

Alternative PR ideas: Remove Mechanic, or move them to the Service department where they belong. Remember to take their Engineering access with them.

**Comment by GreatBigFailure** [comment]
This at least gives people insisting mechanics set up engines a leg to stand on. It's going to personally annoy me in round since I'll actually need to do it, but it's probably better for the serb as a whole.

>Remove mechanic reeeee

Remove access. Remove jobs. Everyone mommi, no antag. Finally, an efficient station.

**Comment by joaomarcosh** [comment]
Just give the mechanic his own exclusive engine. Its inefficient but he can make multiple on them and if someone has done research he can upgrade it to be better.

**Comment by GreatBigFailure** [comment]
If this PR doesn't pass, probably due to people mixing up memes and reality, again, then alternative suggestion:
Split engine access into two categories. Major and minor, or whatever you want to call them. Major would be round ending things like the shard, the singularity, etc. Minor would be less dangerous/complex engines like solars, AME, maybe gourmonger. 
Then you give mechanics only minor engine access. That way engineers still have their niche but you're still doing what this PR set out to do. 
Obviously that's a fair bit more work, but very doable.

@joaomarcosh WYCI

**Comment by jwhitak** [comment]
Actually, an addon to my last comment:
- Everything here could be said about Mechanics and Science as well. Should we give mechanics research access because they're on the science roster?

I'm actually starting to think moving Mechanic to Service is a good idea. What is wrong with me.

**Comment by SonixApache** [comment]
all the confusion on what department to place mechanics in just proves to me that they have no right to exist

**Comment by Optimism333** [comment]
I don't really feel strongly about this one either way. I already think it's perfectly reasonable to ask a mechanic to set up some basic form of power if there are no engineers, the engineers are dead, or they all disappeared for some reason.

However, I do think the suggestions to give the mechanic partial access to quick engine setups or even their own unique ghetto engine are more interesting than this.

**Comment by GreatBigFailure** [comment]
>10 thumbs down
>Zero explanation from any of them

**Comment by ghost** [comment]
> > 10 thumbs down
> > Zero explanation from any of them

access creep is bad

**Comment by GreatBigFailure** [comment]
Under different circumstances I would agree. I don't think mechanics need this, they're their own job with a different goal than engineers. Just about everyone else disagrees with me though and insists that despite the entire point of the access/job system, mechanics are supposed to be doing engines. Because the playerbase has decided to stick its fingers in their ears and smash their head against the wall until the think stops it's probably best to give baby their bottle so we can stop having this argument.

**Comment by DrSnips** [comment]
Mechanics are an odd job and while they intend to do 2 things, engineering and science, but succeed in neither of them. Like the above posts say this isn't the way to fix them.
Why should I play mechanic over a regular engineer? I lack access to the generally important parts of engi and can't make any meaningful contributions to power.
Why should I play mechanic over a regular scientist? I lack access to any of the important parts of sci and usually just build my own setup in a cramped office.
This PR aims to mostly solve the 1st but then you get the other side of this coin. Why would I play engineer when I could just play mechanic and get access to the proto, science gen, and tcomms on top of all the major parts for power setup?
I honestly think the best solution is to just cut it out. Sometimes you need to know when to cut the dead weight.

**Comment by GreatBigFailure** [comment]
>I honestly think the best solution is to just cut it out. Sometimes you need to know when to cut the dead weight.

People enjoy playing the job. That isn't dead weight. You're also ignoring the unique things about the job selectively. 

1. If you can't make engines you aren't as good as engineers
2. If you can't do R&D you aren't as good as science
3. But if you could then you'd be better because you also have your fabricators, scanner, and general focus on machine construction rather than engine construction

Why did point 1 and 2 ignore point 3? 
Once again people are mixing up reality and memes.

**Comment by DrSnips** [comment]
I did address point 3.
>Why would I play engineer when I could just play mechanic and get access to the proto, science gen, and tcomms on top of all the major parts for power setup?
I call BS about mechanics being machine and item producers for the station on a regular enough basis. What machines is the mechanic making each round for the station? If people wanted to get a machine, or items for that matter, they visit science before mechanics because it's consistent (research done there, materials drop there, less likely to be making spacepods, synthesizing infinite antitox/spacelube, or making hammer forged dildos to shove up themselves) and it's recognized by literally everyone that mechanics are just not as good.

**Comment by TGFH** [comment]
Mechanic really shouldn't be station engineer+.
It's not a big ask to have a mechanic just get the AI to let them in or have the acting cap grant them access if needed.

**Comment by adacovsk** [comment]
put a pacman in all the mech offices, I could maybe make a PR for PACMAN more upgradable??

**Comment by Armadingus** [comment]
Jesus Christ.
Engineers break into CE's roundstart every time to press the secure storage access button all the time, do they need CE access? Can we let engineers say it's not their job to setup power if they can't access basic amenities with their ID cards?
I don't personally believe in the mechanic's job being to set up power, even in a lowpop setting where they are best suited to it as the only engineering staff with access to press the secure storage button and roundstart hacking equipment. But even if it was their job, bite the bullet, live with the consequence of being a disgusting halfbreed jobby and just hack in. It's the price you pay for extra access and if you didn't want to setup power at all, then you don't deserve engineering access in any shape or form.

TURN IN YOUR YELLOW GLOVES IF YOU CAN'T HANDLE THE SHOVES.

**Comment by GreatBigFailure** [comment]
@Armadingus You're mixing up IC and OOC reasoning. 
OOC I agree with you. Short of HoP/Captain, mechanics have the best access to just about everything because of their roundstart equipment. When there's no one else to set up engines then OOC it's reasonable to ask/want mechanics to do it and they probably should. It's always weird to see a chemist hack in and make an AME. 
IC it's not their job because they don't have access. Gameplay-wise, access to doors is practically meaningless because of hacking. The only thing access really matters for is machines/buttons. It makes opening lockers easier but even then it's not hard to get around it. The actual purpose of access, at least for doors, is more RP oriented in designating jobs. If you have access to somewhere then part of your job includes that. If you don't, then it's not your job. People always ignore this when talking about mechanics but, conveniently, don't ignore departments which follow the exact same IC logic as access, but without any actual mechanical factors like locked doors.

OOC it's reasonable to say mechanics should set up engines during deadpop as a sort of courtesy. IC it's not their job and there shouldn't be IC ramifications for not doing it, as there often are. This PR fixes that issue. Though it also just makes them better than engineers mechanically, which isn't good at all.

**Comment by west3436** [comment]
I don't think we have a clear majority answer to this. Going to close it unless collabs want to revive it. I will be whipping up a new alternative change for Mechanics soon:tm:

**Pull request closed without merging**
