### PR TITLE
Removes the stun from the ac2 mech lmg

### PR DESCRIPTION
**Pull request by Dacendeth**
Rapid fire ballistic stuns are not very fun, and kind of makes the taser mech attachment pointless.  

:cl:
 * tweak: Mech Ac2 bullets no longer stun.

### CODE REVIEW

**Comment by Eneocho** [comment]
any nerf that cucks the roboticist powergamer is a good nerf

**Comment by githubuser4141** [comment]
> Rapid fire ballistic stuns are not very fun, and kind of makes the taser mech attachment pointless.
> 
> 🆑
> 
> * tweak: Mech Ac2 bullets no longer stun.

Not a contributor, but maybe buffing the the Ac2 bullet's damage wouldn't be a bad idea, because 30 damage total is pretty underwhelming compared to the scattershot or laser alternatives..

**Comment by djkramer123** [comment]
imagine suggesting buffs for mechs

**Comment by Dacendeth** [comment]
im not touching damage with this pr if someone else wants to do it after by all means.

**Pull request merged**
