### PR TITLE
Mouse wheel based RPD control.

### PR DESCRIPTION
**Pull request by PJB3005**
Also non standard formatting changes.

Controls are ctrl+scroll to change between favorites RPD schematics, shift+scroll to change layers, and alt+scroll to change direction.

RIP #13584

There is currently an issue where using alt+click and such with an RPD still works and it overrides the damn RPD's own click. I'll need to figure out a way to prevent this.

Oh there's another one: adding a favorite screws with the schematic's options menu.

🆑 
* rscadd: You can now control the RPD and alike with your mouse wheel! Alt+scroll changes direction, shift+scroll changes layer, and ctrl+scroll changes the schematic from a new "favorite" list!

### CODE REVIEW

**Comment by Probe1** [comment]
Siiiiiiick

**Comment by clusterfack** [comment]
I think we're at the point now where we're using every single possible type of input jesus christ how does anyone even learn this game.

Next I think we should make it so you have to plug in a gamepad to use all these fresh new hotkeys we're spittin out.

**Comment by Exxion** [comment]
A keyboard has WAY more inputs than a gamepad

**Comment by clusterfack** [comment]
The keyboard is tapped out, all future hotkeys will require voice controls using the Kinect"&#174"

**Comment by Shadowmech88** [comment]
All future hotkeys can be input as morse code combinations using the spacebar.

**Comment by clusterfack** [comment]
I had an idea recently where we add a usb breathalyzer to your computer and depending on how drunk it detects you are when you blow into it you have a whole span of different hotkeys.

**Comment by Exxion** [comment]
That reminds me of Goon's drunkmin system
An admin can declare another admin (or themselves) to be drunk, which limits their ability to fuck with the round, and they have to solve a math problem to undo it

**Comment by clusterfack** [comment]
That could have saved rei on so many occasions

**Comment by kol1th** [comment]
This is optional, right?

**Comment by Exxion** [comment]
1. How would a control be not optional? You can just... not touch that button.
2. WHY the FUCK would you want to not control it this way?

**Comment by SysadminJeroen** [comment]
I want this so bad, makes my job as atmostech much easier.

**Comment by jakmak5** [comment]
why not both this and https://github.com/d3athrow/vgstation13/pull/13584 ?

**Comment by Probe1** [comment]
Because your PR is terrible for the reasons I've explained @jakmak5 .  You never even explained why.  You just want it.  You are not meeting my banana sticker standard for game design.

**Comment by PJB3005** [comment]
@jakmak5 if you actually sat down, took a cynical eye, looked at the problems of the RPD and what needs doing to fix them, you wouldn't come to "let's just remove the delay".
You're just throwing powercreep ideas at the wall hoping they stick, and the powercreep ideas have no thought put into them.
At best the delay means you need to wait half a second longer between moving your character to a new location to be able to lay pipes again. This half a second accounts for bloody nothing in practice.

The real problem with the RPD is the extreme amounts of mouse movement needed to change directions and layers. You basically have to cut off part of your viewport to get the menu close *or* you need to move halfway across your screen to hit the 5 pixel window that is the pipe layer selector, and then back to place the pipe itself.

So that's what I did. I removed the redundant mouse movement, but still left a skill ceiling.
Your 5 layer mode would sort of fix the problem (but not really, it didn't eliminate the mouse movement to change schematic or directions), and remove all forms of skill from it too.
With my approach there's still a reward for being able to control your mouse and ctrl/shift/alt button efficiently.

**Comment by Exxion** [comment]
That skill ceiling stuff kind of sounds like bullshit, but I don't care because this removes the ridiculous tedium anyway

**Comment by PJB3005** [comment]
Ready!

**Comment by BobdaBiscuit** [comment]
M E R G E D 
W H E N

**Comment by BobdaBiscuit** [comment]
A B S O L U T E
M A D M A N

**Comment by FudgePucker** [comment]
I don't even know why anyone would care about the balance of the RPD anyways.
This is the game where if you jump someone with a fire ax you can get disarm shoved and killed because of a dice roll, but GOD FORBID IF WE MAKE A CHORE ANY EASIER.

**Comment by Probe1** [comment]
yeah its just a game who cares lmao

😦

**Pull request merged**
