### PR TITLE
Default throwforce changed to 0 from 1

### PR DESCRIPTION
**Pull request by Dacendeth**
## What this does

This changes the default throw force from every object from 1 to 0, this does nothing to any object that has a defined throw force for itself, ie thrown shards will still instantly kill you when thrown by an explosion.
## Why it's good

The default melee force of objects is 0 for a reason, it prevent silly interactions where it doesnt make sense to be hit by it to damage you and I think that should apply to thrown objects too.

The goal is to prevent explosions from making literally every object thrown at you being lethal while still maintaining explosions ability to throw things designed to be lethal killing you.
No longer will a thrown burger instantly kill an unarmored person.
## Changelog

:cl:
 * tweak: Changed default object throw force from a 1 to a 0 to prevent some insanity related to explosions.

### CODE REVIEW

**Comment by west3436** [comment]
Have you tested how this impacts throwing things? Does everything just drop after a single tile like throwing paper does?

**Comment by Dacendeth** [comment]
This has no impact on the range you throw things

**Comment by Eneocho** [comment]
getting gibbed from a piece of paper at mach10 is funny and I will die on that hill

**Comment by Dacendeth** [comment]
> getting gibbed from a piece of paper at mach10 is funny and I will die on that hill


Add throw force to paper then if that's what you want.

**Comment by Eneocho** [comment]
i'll correct myself
getting gibbed from trash, a piece of bread, a rubber duck, a banana peel, etc at mach 10 is funny and I will die on that hill

**Comment by hacker-on-steroids** [comment]
do not like making trash shrapnel going from insanely dangerous to completely harmless
if you wanna tone down the instakills and nerf the damage you should at least make them embed into the flesh

**Comment by SonixApache** [comment]
i don't see why anyone would be against this
i feel like pomf's no-discussion addition of the trash-now-kills-you code never took into account that sheets of paper would now disintegrate you if thrown across the room by the explosive equivalent of a fart

**Comment by KingofHONK** [comment]
One time as clown I slipped and stole an HOS' gun during a highspeed chase and tried to tase him with it. The HOS got up and took out his backup egun, set to kill.  Forgetting that I couldn't have even fired it if I got lucky with clumsy, due to the DNA lock, the lawgiver instead exploded. It gibbed my hand, causing me to pass out in pain. When I came to, the HOS was laying dead nearby. 

The lawgiver had betrayed him, sending a loose wire flying straight through his abdomen, killing him instantly. I owe shrapnel my life, and I can't watch while someone tries to grudgecode it out just because they get owned!

**Comment by Dacendeth** [comment]
But this pr can be merged and then a pr to make cables have a throwforce can be made afterwards to maintain cables specially doing that if that's what people want.

The reason I feel the base should be 0 is the same reason Melee is 0, imagine if Melee was non zero, and you could murder people by smacking them with paper and folders or a burger or any of the countless items without any defined force because nobody set specific force of 0 for them.

**Comment by githubuser4141** [comment]
> One time as clown I slipped and stole an HOS' gun during a highspeed chase and tried to tase him with it. The HOS got up and took out his backup egun, set to kill. Forgetting that I couldn't have even fired it if I got lucky with clumsy, due to the DNA lock, the lawgiver instead exploded. It gibbed my hand, causing me to pass out in pain. When I came to, the HOS was laying dead nearby.
> 
> The lawgiver had betrayed him, sending a loose wire flying straight through his abdomen, killing him instantly. I owe shrapnel my life, and I can't watch while someone tries to grudgecode it out just because they get owned!

That's ridiculous.. why can't we make it based on velocity, so small items lose their velocity almost immediately after passing 1-3 tiles, large items require more energy to be thrown (and therefore a more powerful explosion)?

So.. a piece of wire would lose its velocity after 2 tiles, slowing to do significantly less damage, then another 1-2 tiles later it stops completely. An anvil (very heavy) retains its velocity, but requires a much larger explosion to gain velocity.

**Comment by GreatBigFailure** [comment]
Does this affect tackling? 
Things like tackling windows were unintended but (in my opinion) beneficial quirks of tackling. I'm wondering if this would accidentally disable that.

**Comment by Kurfursten** [comment]
Lazy solution to a very real problem. Shrapnel is a menace but how about just toning down the throw power instead of this?

**Pull request closed without merging**
