### PR TITLE
More fun bee toys

### PR DESCRIPTION
**Pull request by DeityLink**
- Feral bees now select a new target more randomly.
- Added the bee gatling gun. each projectile deals 5 tox damage. Equipments with "bio" armor, will mitigate the damage. Bio suits for instance will completely negate it. Projectiles spawn a bee when they disappear. If they hit a mob the bee is spawned on top of them and will immediately target them, if not they will target a random nearby mob. The projectiles don't damage anything beside mobs.
- Added bee nades. Self explanatory.
- Bees no longer despawn when they don't have a home apiary.

bee gun and bee nade currently admin spawnable only

### CODE REVIEW

**Comment by Killette2** [comment]
This is not my dream ;_;

But an improvement in the right direction

**Comment by clusterfack** [comment]
If you want your dream realized exactly as you imagine maybe you should learn to code man

**Comment by Killette2** [comment]
I paid $350 for software to design my own games, however have never designed anything I am happy with.

I have problems.

I'm not going to complain about your work as you did a good job, I just have to ask where the idea of a bee gun and grenade came from?

The point of weaponizing bees was to make them stronger via botanical means, such as the floral somatoray and feeding plants toxin to improve their stringer sharpness and venom toxicity, and this is just making weapons that seem to have no work involved into using them.

See toxins mixing has to make the bombs
xenobio has to make the red/gold/oil slime extracts
shaft miners have to kill and capture the creatures they plan to release on the emergency shuttle
science has to do RnD before getting the cool guns (admittedly this one isn't hard)

I just imagined more of a work for reward approach to this, but this is better than nothing at all.

**Comment by DeityLink** [comment]
@Killette2 some guys in #6333 mentionned bee guns, and it's true the idea has been floating around for ages. There's some in terraria too (and there are bee traps in Don't Starve, which I play a lot lately)

Anyway, I was in a good mood tonight, and wondered "wait we have gatling guns, that shouldn't be to hard to have the bullets create bees" and that's how it was done half an hour later. Then someone in the thread asked for Bee Nades when I posted the webm and I thought "why not, it shouldn't take too long to code either, we already have grenades that spawn viscerators and carps so I'll just make it a child of those".

Most of the time was actually spent editing the sprites.

Oh and this PR wasn't meant to address your issue by the way, it's just something I've been meaning to code in a long time.

**Pull request merged**
