### PR TITLE
Nicer looking intake entry and outlet ejection

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[sprites]

## What this does
puts them on a plane above all objects and mobs and makes the movement into these objects look smoother.

## Why it's good
the outlets having the items appear briefly above them on ejection always looked weird.

## Changelog
:cl:
 * tweak: Disposal chutes and outlets are no longer underneath the items they take in and out.

### CODE REVIEW

**Comment by SonixApache** [comment]
show before and after pics maybe

**Comment by SECBATON-GRIFFON** [comment]
> show before and after pics maybe

still trying to get the overlay to show up at all

**Comment by dinnerwoerror** [comment]
dang i kinda liked seeing the giant clog of somebody dumping a bunch of closed crates down the trash all at once

**Comment by Exxion** [comment]
Looks like you forgot `relative_plane()`

**Comment by SECBATON-GRIFFON** [comment]
> Looks like you forgot `relative_plane()`

yeah i figured that out pretty quick

**Comment by SECBATON-GRIFFON** [comment]
by the way does flick() work on overlay images or icons at all or am i out of luck and need to look for a workaround @Exxion

**Comment by Exxion** [comment]
I really don't know anything about `flick()`. I'd check how it's used elsewhere in the codebase.

**Comment by SECBATON-GRIFFON** [comment]
even avoiding use of flick() in every way it's somehow still not working so i'm abandoning the whole underlays thing. it'll look a bit weird but still a ton better than how it did before. (if any advice on a fix that works comes along i can just revert the commit)

**Pull request merged**
