### PR TITLE
Antag datum

### PR DESCRIPTION
**Pull request by chesse20**
🆑 
 * rscadd: Adds Antag Datums

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Darn I was about to make that joke Damian

**Review by DamianX — CHANGES_REQUESTED** [review]
Please move this under the `code/datums` directory and make sure to add the new file to `vgstation13.dme`.

**Comment by chesse20** [comment]
alright ill work on that

**Comment by chesse20** [comment]
fixed

**Review by DamianX — CHANGES_REQUESTED** [review]
The changelog is not using the correct format, see https://raw.githubusercontent.com/vgstation-coders/vgstation13/140c1d1c3c3fd0fc337886388c4f7e1e1026b449/.github/PULL_REQUEST_TEMPLATE.md and https://github.com/vgstation-coders/vgstation13/blob/1fb4a796dc464f8c2f7a443b033fbe5450105382/html/changelogs/example.yml for examples of proper changelogs. You also seem to need to go back to TG.

**Comment by chesse20** [comment]
fixed 😋

**Review by DamianX — CHANGES_REQUESTED** [review]
No, it needs to be a list.
Like this:
```
:cl:
 * rscadd: Adds Antag Datums
```
instead of
```
:cl:
rscadd: Adds Antag Datums
```

**Comment by chesse20** [comment]
alright

**Comment by DamianX** [comment]
This implementation is very lightweight compared to the [existing project](https://github.com/vgstation-coders/vgstation13/projects/10). Can you describe the main differences between them, and explain the reason why you didn't contribute to the `role_datums` branch instead? Please use 400-500 words. (This task should take 50-60 minutes).

**Comment by chesse20** [comment]
im working on a roblox game right now ill try to explain my implementation of antag datums sometime tommorow

**Pull request closed without merging**
