### PR TITLE
Nuka Cola tweaks

### LINKED ISSUE #35507: You can crush the Nuka cola plastic/glass(?) bottle into a crushed metal can
(WEB REPORT BY: tinysaturn REMOTE: 209.222.101.3:7777)
# Revision
89f7b1d376c2349a70e8e5cd838e032e242ce3bd

# Description
what

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #35507

imageimage

backend change: split the coins icons off from items.dmi

:cl:
* tweaks: Nuka Cola bottles are now made of glass, and can no longer be crushed like a can in your hand. They can however be shattered when thrown or used to hit someone, be flipped when you have the sober gene, or used to prepare a molotov.
* imageadd: Fixed Nuka Cola bottles having the same hole that soda cans get when you open them, instead their cap gets visibly removed.
* rscadd: Opening a Nuka Cola bottle now actually gives you a bottle cap.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can the caps be used as coins for vending machine purposes? something something Old World Blues' The Sink.

**Comment by DeityLink** [comment]
You'll find out!

**Comment by wotisjanitor** [comment]
can they be smashed over peoples heads

**Comment by DeityLink** [comment]
yes

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
