### PR TITLE
Adds human light vision adjustment.

### PR DESCRIPTION
**Pull request by ComicIronic**
How well humans see in the dark changes over time.
Spending too much time in bright light can make it difficult to see in maint.
Spending too much time in darkness can cause sudden changes in brightness to blind or blur the player.

### CODE REVIEW

**Comment by DeityLink** [comment]
>only affects humans and human species
>that thing about sudden changes
It worries me a bit. It stems from a good idea (can't recall having seen HDR in a 2D game before) but there's going to be issues. what does the eye consider darkness? can we get screenshots to see its effects in game?

**Comment by ComicIronic** [comment]
It only affects humans because the only other major player-controlled group would be silicons, and they shouldn't be affected by lighting changes.

>can we get screenshots of its effects ingame

Tragically, Byond a shit, so there's little to see with screenshots.
It permits the player's rightclick menu to extend further in the dark, however.
>what does the eye consider darkness

Less than 5 lighting_lumcount.
lighting_levels
This is a good demonstration. When lighting falls below 1 on that picture, the human's darkness adjusts by 1, and so on. 

It's also rather difficult to get blinded or blurry vision from a lightchange, since most hallways are actually illuminated pretty poorly.

**Comment by DeityLink** [comment]
Wait so, the dark areas don't actually appear clearer when you're in the dark right?

**Comment by IratePirate** [comment]
Well it sounds cool at least, don't like the idea of it being human only though.

**Comment by ComicIronic** [comment]
The dark areas don't actually 'light up', Byond just extends the range at which you can right click to see the tile contents.

>human only

Its more of a test with humans than anything else. Which other mobs should it affect?

**Comment by DeityLink** [comment]
>The dark areas don't actually 'light up

oh ok good. was worried it'd conflict with the weak light of the new hell/supermatter endgame universes.

Also imo it should at least affect all carbons.

**Comment by ZomgPonies** [comment]
I love the concept in theory, but it should be tied into darkvision and what now. Make people with darksight more sensitive to sudden changes in lighting/flashing would make more sense as a feature, but that's just my opinion.

**Comment by d3athrow** [comment]
by human you mean carbon/human and not the species correct?

**Comment by DeityLink** [comment]
It seems to affect every carbon/humans. I kinda wish it even affected every carbons but whatever.

**Comment by ComicIronic** [comment]
Fugg.
For another time, then.

**Pull request closed without merging**
