### PR TITLE
Renamed whiskey

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
By popular vote, and also because RIP skeleboners, whiskey is renamed to "Ack Daniel's"

### CODE REVIEW

**Comment by Intigracy** [comment]
haha conflicts.

**Comment by Probe1** [comment]
:-1:

**Comment by Iamgoofball** [comment]
why the fuck isn't this on milk bottles you dipshit

**Comment by dannno** [comment]
no

**Comment by Arthurdentist** [comment]
don t act dumb

**Comment by Intigracy** [comment]
This is actually pretty witty with the naming.

But haha conflicts.

**Comment by ShiggyPiggy** [comment]
Uh okay guys I think I got it this time

**Pull request closed without merging**
