### PR TITLE
Rewrite isolation centrifuge. In Nano.

### PR DESCRIPTION
**Pull request by PJB3005**
Made the code not shit. Use Nano because Deity hates it.

:cl:
- tweak: the virology isolation centrifuge is 3x cooler now. 

image

### CODE REVIEW

**Comment by DeityLink** [comment]
I really don't like this at all honestly, it's just fine with its minimalist UI and no useless crap on screen distracting you. Half the info here is useless.

**Comment by Irradiation** [comment]
Capture
Remove what I scribbled out and it'll be a nice upgrade. The info about the centrifuge lock and all the small text is superfluous and just makes the interface look busy as hell.

**Comment by tuypo1** [comment]
I think its cool, maybe not the warnings but the power usage and whatnot.

**Comment by PaulRitter** [comment]
What happened to this being an rp-game? i personally don't mind the extra bit of fluff

**Comment by PJB3005** [comment]
Yeah I knew the bottom bit was gonna need some explaining.

The status thing started when I made the eject/insert buttons get greyed out when the device is active (instead of always seeming available but dumping a message to chat.. Yuck).

It wasn't immediately obvious *why* the vials were locked in so I figured having a status message like that would maybe help make the user realize why. 

It kinda went from there, really. The RPM meter actually does change depending on how fast the machine is processing (due to imbalance/upgrades). The warning gets printed to make it more obvious that *you're doing it wrong*, and the RPM helps make it easier to understand how the imbalance works and see when you're perfect at it. Both of these are based on my first experience with the thing. When I first walked into virology the guy using the centrifuge had it completely unbalanced, and I really do think this kind of info should be communicated to the player somehow to make the mechanics clearer.

Then the power usage is ditto for when I saw they left the centrifuge on in the same round. 

I understand that a lot of this is redundant information but I think it adds a lot of flavor to the UI. Bay kind of leans towards this too with a lot of computer UIs I've used and I love it about them. If this device were real there very well might be these kind of warning / status messages.

The footer text is then me realizing along the way that all these SS13 machines would have this kind of safety text on them. I just feel like it would add a lot of flavor to the game if correctly implemented and why not start here, eh? If somebody has any idea for more witty warning text I'm definitely open to it. Also the locking mechanism thing was me going overboard with making sure the user makes that connection that power = locked. I understand if it's overdoing it though. 

I also made sure to put all this on the bottom so it would be more out of view.

**Comment by Irradiation** [comment]
>SS13 machines
>Safety text

Good one

**Comment by PJB3005** [comment]
What's more funny: no safety text at all or safety text written with the intent of being ignored?

**Comment by Irradiation** [comment]
None, because they most other machines don't even have safety text and NT clearly doesn't care enough about safeties in general.

**Comment by PJB3005** [comment]
Well then we gotta start somewhere.

**Comment by tuypo1** [comment]
>NT clearly doesn't care enough about safeties in general.

There are warning songs absolutely fucking everywhere

**Comment by Irradiation** [comment]
If you want safeties, shove it into the machine description so it doesn't clog up the actual machine interface.

**Comment by tuypo1** [comment]
I don't really care if the safety warnings exist or not but I do really like the power usage and rpm
Putting the warnings in the description seems like a good solution.

**Comment by PJB3005** [comment]
Yeah but I can't shove THIS MANY meme safeties into a machine description. Also examine is pretty shit.

There are things I could do with the CSS to keep the flavor text in the UI but be less distracting such as reducing background contrast and shoving it down to the bottom of the page.

**Comment by PJB3005** [comment]
Also @tuypo1 makes a good point. If NT didn't give a shit about safety then why is engineering filled with warning stripes? Do those also clutter up the map?

**Comment by ShiftyRail** [comment]
I don't see much issue with the little flavour text
Not like I'm ever going to play virologist again anyways

**Comment by DeityLink** [comment]
If everyone is fine with it then just go ahead then.

But please spare the incubator.

**Comment by PJB3005** [comment]
image

You're welcome.

**Comment by DeityLink** [comment]
:angry:  motherfucker

**Comment by brndd** [comment]
why is this still a draft

**Comment by DeityLink** [comment]
shhh

**Comment by PJB3005** [comment]
@brndd because I realized the implementation of the centrifuge back end was sub par because I didn't grasp the code fully. Also I need to clean the UI definition up a bit to ensure consistency in the table layouts.

**Comment by Kurfursten** [comment]
Is this still a WIP?

**Comment by PJB3005** [comment]
image

**Comment by Kurfursten** [comment]
That happens with WIP stuff more than you'd think

**Pull request merged**
