### PR TITLE
Ayy Rigsuit Kits and Balance (Cargo)

### PR DESCRIPTION
**Pull request by Optimism333**
## PR Summary ##
It always bothered me that ayys could get rigs hot and fresh out of cargo crates, especially since a system for constructing rigs has existed since #30053. 

A rig is a very useful tool, and I think more investment and interaction should be dropped into getting a unique non-station one than paying 200 credits and hoping you get a lucky roll.

Blithering was kind enough to sprite some rigsuit part kits, and I've made this pr to try to address this.

Ayys will need to buy rig kits (200 per 2 kits), and hardsuit frames (200 per 3 frames), and do some assembly before they can enjoy a personalized functioning rigsuit. While this doesn't increase the average price of the rigs much, it does increase the minimum price required to get rigs: 400 credits to buy the kits and frames to make 2, and some assembly still required.

### Sprites ###
Three new rig kits have been added.

image

### Grey Space-Ex Changes ###
- The grey space-ex crate no longer has rigs, it only comes with the explorer space suit (the grey and red one that isn't a rig).
- The grey space-ex crate is cheaper overall: 200 credits -> 175 credits

### Mothership Uniforms ###
- These are no longer contraband. It was kind of silly that some ayy-themed uniforms were, but ayy rigs weren't. So I've reversed that.

### New Ayy Rig Kit Shipments ###
- Two kinds of ayy rig kit shipments have been added

**GDR rig parts**
- Costs 200 credits, comes with a worker rig kit and a researcher rig kit
- Minor contraband (needs a solder or permissions changes on the cargo console to unlock the shipment)
- Can be found under the "Science" category on the cargo console
- Robotics access required to unlock the crate

**MDF rig parts**
- Costs 200 credits, comes with one soldier rig kit
- Minor contraband (needs a solder or permissions changes on the cargo console to unlock the shipment)
- Can be found under the "Security" category on the cargo console
- Armory access is required to unlock the crate

### Why touch the stats? ###
- These rigs were always a bit on the weaker side statwise compared to station rigs, and I don't think that was unreasonable before given that they were stupidly easy to acquire, not requiring any access or assembly.
- Now that they will require more cash, access, and assembly, I think it's reasonable to at least make them comparable to on-station rigs statwise. So an ayy who invests the time and effort to get their own personal rig will be a bit more rewarded for their efforts.

### Worker Rig Stat Changes ###
Old: (melee = 30, bullet = 5, laser = 20, energy = 5, bomb = 25, bio = 100, rad = 50)
New: (melee = 40, bullet = 5, laser = 20, energy = 5, bomb = 35, bio = 100, rad = 50)

Slightly buffed melee and explosion protection. Basically is now comparable to an on-station engineering rig.

### Researcher Rig Stat Changes ###
Old: (melee = 30, bullet = 5, laser = 20, energy = 5, bomb = 40, bio = 100, rad = 40)
New: (melee = 40, bullet = 5, laser = 25, energy = 5, bomb = 50, bio = 100, rad = 35)

Slightly buffed melee, laser, and bomb protection. Slightly reduced rad protection. Is now a bit of a mirror to the worker rig, and comparable to a xenoarch suit with lower rad and bomb protection, but more laser protection.

### Soldier Rig Stat Changes ###
Old: (melee = 40, bullet = 5, laser = 50, energy = 5, bomb = 30, bio = 100, rad = 20), Medium Hardsuit Slowdown
New: (melee = 50, bullet = 15, laser = 50, energy = 15, bomb = 35, bio = 100, rad = 20), High Hardsuit Slowdown

Slightly buffed melee and bomb protection. Increased rig slowdown. The soldier rig is a pretty strong combat rig, and doesn't really have a station equivalent. However, it's more expensive than the worker and researcher rigs, and has higher slowdown to compensate for its good melee and laser protection.

### Administrator Rig Stat Changes ###
Old: (melee = 50, bullet = 25, laser = 70, energy = 25, bomb = 40, bio = 100, rad = 50), Previously came with default cell
New: (melee = 60, bullet = 30, laser = 70, energy = 25, bomb = 50, bio = 100, rad = 50), Comes with better power cell

Slightly buffed melee, bullet, and bomb protection, rig comes with a better starting cell. This suit doesn't show up on the station, but I think that for a high end rig that can only be acquired by defeating a boss mob and going through a very dangerous vault, its stats were still a bit mediocre. 

**Can be worn by humans now!**
image
Because of its more advanced construction, this rig can form a seal around a human body. Human hobos and players who defeat Administrator Zorb can actually wear his suit!

## Thanks for Reading ##
Please leave some feedback, if you have some. It's always appreciated.

[sprites]  [content] [tweak] [balance]

:cl:
 * rscadd: Added ayy rig kit shipments at cargo: 200 credits per 2 kits (frames must also be purchased and some assembly required)
 * tweak: The grey space-ex crate no longer contains ayy rigs and is a bit cheaper 200 -> 175
 * tweak: The defensive stats on the ayy rigs have been slightly buffed
 * tweak: Mothership uniforms are no longer contraband

### CODE REVIEW

**Comment by Optimism333** [comment]
Feedback on price numbers and stat adjustments is appreciated. Pr is partially tested, and all seems okay so far.

**Comment by ManopolisJones** [comment]
Although I like the changes from the grey space ex crates being rig suit gatcha boxes to actually being able to pick and choose the rig you'd like to make (even though the military rig is e-magged locked, poor thing) I cannot say I agree with putting mothership uniforms out of contraband and into normal rotation. 
When I first began writing this, it was under the presumption that the new rigsuit parts were in normal rotation much like the grey space X suit, however to that line of thinking I was wrong. The thing about it too is, I agree the rigsuits should be under contraband, but it's for the same line of thinking as the mothership uniforms. These are acid proof outfits that come with boots, and special stats associated with them. Lest we not forget, the mothership uniforms come with both adventurer outfits and security outfits (Which have combat stats associated with them requiring no access to unlock).
I could go perhaps go further into it, but in closing, I think if grey uniforms are to see some kind of wider distribution not requiring the extra hoops of circuitry and soldering irons, it would have to take form of some kind of alien clothing vendomat pack, or hell, if you wanted to get crazy with it, you could just use our existing clothing vendomat and put them in as a premium coin item.

**Comment by Optimism333** [comment]
> Although I like the changes from the grey space ex crates being rig suit gatcha boxes to actually being able to pick and choose the rig you'd like to make (even though the military rig is e-magged locked, poor thing) I cannot say I agree with putting mothership uniforms out of contraband and into normal rotation. When I first began writing this, it was under the presumption that the new rigsuit parts were in normal rotation much like the grey space X suit, however to that line of thinking I was wrong. The thing about it too is, I agree the rigsuits should be under contraband, but it's for the same line of thinking as the mothership uniforms. These are acid proof outfits that come with boots, and special stats associated with them. Lest we not forget, the mothership uniforms come with both adventurer outfits and security outfits (Which have combat stats associated with them requiring no access to unlock). I could go perhaps go further into it, but in closing, I think if grey uniforms are to see some kind of wider distribution not requiring the extra hoops of circuitry and soldering irons, it would have to take form of some kind of alien clothing vendomat pack, or hell, if you wanted to get crazy with it, you could just use our existing clothing vendomat and put them in as a premium coin item.

Okay, I can understand that perspective. If other players also want mothership clothes to remain lite contraband, I'll revert the change in the pr.

**Comment by NigglyWiggly** [comment]
@Optimism333 
Obligatory
https://www.youtube.com/watch?v=kArgQz1RKmk




Also allowing a human to wear an alien rig is shameful and you should feel bad even though I understand your reasoning

**Comment by Optimism333** [comment]
> @Optimism333 Obligatory https://www.youtube.com/watch?v=kArgQz1RKmk
> 
> Also allowing a human to wear an alien rig is shameful and you should feel bad even though I understand your reasoning

Well that makes me feel a bit bad. However, I do stand by my reasoning.

Is there anything else in the pr that you have feedback on?

**Comment by Optimism333** [comment]
After some thought, I think I overly restricted the ayy soldier rigsuit by making it emag contraband. Instead it's now regular contraband, and only one kit comes per 200 credit shipment.

**Comment by Blithering** [comment]
I will admit hardsuit construction is something that completely passed me by, does this mean getting some ayy flavouring on your suit doubles the price of a hardsuit? Or is there some material cost that's bypassed by getting the grey modkit?

**Comment by Optimism333** [comment]
> I will admit hardsuit construction is something that completely passed me by, does this mean getting some ayy flavouring on your suit doubles the price of a hardsuit? Or is there some material cost that's bypassed by getting the grey modkit?

Basically, the price floor to get ayy rigs is higher: instead of just paying 200 credits to buy a grey space-ex shipment and hoping you get lucky, you need to pay 200 credits for a shipment of modkits, and 200 for the frames. Then you need to bypass the crate's robotics access lock, either by having the access, or by other means. Then you need to do some fairly straightforward assembly, add a cell and the modkit, and you can have two ayy rigs ready to go (or one if you purchase the soldier's rig).

The price per unit is about the same as before: ~200-250 credits. However, there's a larger initial price to get production going, and more steps involved now than just getting the rig ready to use out of the box.

Hope that answers your question.

**Comment by Optimism333** [comment]
Because of its intended use being geared more towards combat, I moved the soldier rig parts from the science section of cargo to the security section. Instead of robotics access, the crate requires armory access.

I also made the ayy rig part kits resistant to acid but vulnerable to water, to be consistent with the suits.

**Pull request merged**
