### PR TITLE
The big changeling overhaul

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
To show that I'm doing SOMETHING at least, I'm going to create this PR, which I plan to encompass multiple modifications to Changelings. 

This first one is simple- it makes DNA extract sting free and yields 1 evolution point per genome. I plan to add arm blades and several other powers from Polaris as well...assuming anyone can help me port the fucking things, because I have no clue which of their procs corresponds to ours. And as a relatively novice coder doing a big project, I will need someone to triple-check my work every step of the way.

### CODE REVIEW

**Comment by Probe1** [comment]
Consider multiple PRs instead of sitting in development hell because of hurdles.  I do it with mapping frequently.

**Comment by icantthinkofanameritenow** [comment]
@Probe1 

At this point, I think I might have a better chance of getting this done via refactoring the entire gamemode code as Riri suggested on IRC. Though that would mean having the slighest clue of how to do THAT.

**Comment by Intigracy** [comment]
Polaris's absorbing through stings makes changeling even more boring than it is currently.

**Comment by icantthinkofanameritenow** [comment]
But on the other hand it means that changelings don't necessarily need to kill in order to upgrade powers and gain identities. Besides, absorption will be worth more and I'll also refactor power costs to make it so some will be too expensive for extraction alone to cover.

**Comment by icantthinkofanameritenow** [comment]
Closing this for the moment due to the fact that any such change will need to be done all at once, since the individual ones won't work very well in isolation. Sorry probe, but your method of doing things won't work here.

**Pull request closed without merging**
