### PR TITLE
Mining bar

### PR DESCRIPTION
**Pull request by MadmanMartian**
For when you need to tap out while mining.

Contains:
 - Dusky the barbot. Will talk while people are in vicinity, and greet you when you come through the door.
 - Some bar machines
 - That's about it.

TODO:
 - [ ] Need a sprite for a wall-mounted PACMAN for miners to put plasma ore and sheets into.
 - [ ] Make an evaluate_surroundings component and a chemist component, so dusky can actually make drinks

### CODE REVIEW

**Comment by SGuivenne** [comment]
Thanks Travis

**Comment by MadmanMartian** [comment]
bad map vars

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/maptools/clean_stepxy.py

**Comment by Durgen** [comment]
screenshot?

**Comment by MadmanMartian** [comment]
robot fortress rho 2018-09-19 222819

It's an ugly little thing and the pipes keep fucking up. If you've got any recommendations on how to comfy it up, I'm all ears

**Comment by Durgen** [comment]
@MadmanMartian some ideas
-  poker table and cards
- rapid service fabricator, bartender hat, 
- small boxing ring/rage cage
- slot machines
- n2 locker for traders
- posters
- maybe some windows
- neon bar sign
- Juke

**Comment by Durgen** [comment]
the tragic thing is that this will probably just get blown up or drilled into most rounds, is there any way to mitigate that?

**Comment by MadmanMartian** [comment]
stanford roost six 2018-09-20 034925
If it happens, it happens.

**Comment by Kurfursten** [comment]
I've noticed a lot of engineering stuff shits the bed when it's spawned in like a vault

See: biodome

**Pull request closed without merging**
