### PR TITLE
Runechat is invisible if you're invisible.

### PR DESCRIPTION
**Pull request by PrimeDSS13**
(now tested!(tm))

Makes it so that if your character is invisible via potion, cloak, or some other way you no longer have runechat appear over your head. This is a problem because it runechat follows the speaker for a good few seconds, and lingers. You could just locate the speaker instantly, encouraging the invisible man to silent shuffle. This was never a problem before, and it will no longer be a problem after this.

:cl:
 * tweak: Invisible people no longer have runechat appear over their head.

### CODE REVIEW

**Comment by Kurfursten** [comment]
What relationship does this PR have with #28070 ?

**Comment by PrimeDSS13** [comment]
> 
> 
> What relationship does this PR have with #28070 ?

That PR is just emotes, but this one is words as well. Also, it's time to do some actual testing and fixing.

**Comment by Gazathor** [comment]
Sorry kid this sounds like a feature!

**Comment by Exxion** [comment]
Alternative: Make the speech bubble appear if you're invisible too
I think it's fine to be able to know where someone is by hearing them speak, but it's not fine that you only can with certain settings turned on

**Comment by PrimeDSS13** [comment]
While that would be better, you'd still be able to directly pinpoint and follow people with it and the problems I stated would still be around. You do bring up a good point with all the settings stuff though, people who don't go into settings now are at a clear disadvantage due to bubble while typing, runechat, and better FPS all being off by default.

**Comment by TGFH** [comment]
I think it's sort of a feature but I'm not really opposed to removing it. It makes sense that you can locate someone invisible if they just said something loud enough for you to hear it.
They do also have the option of only speaking over the radio currently, since you automatically whisper whenever you use your headset.

**Pull request merged**
