### PR TITLE
Add stop pulling and body zone targeting buttons to grues (WIP)

### LINKED ISSUE #32313: GRUE'S CANT STOP DRAGGING SHIT
(WEB REPORT BY: pulserider REMOTE: 206.221.180.138:7777)
# Revision
c97c32dafa1be14413a480d9c928117fee8fc169

# Description
I dragged a catatonic officer as a grue. He had a flashlight. I died because I couldn't stop dragging him.
# Steps to Reproduce
Drag something as a grue
Suffer in agony as you cannot stop dragging unless you drag something else
# What you Expected
To be able to stop dragging items / people
# What Actually Happened
grue gets dunked by a braindead officer

### PR DESCRIPTION
**Pull request by Hinaichigo**
This is a draft for adding a "stop pulling" button to grues as well as body zone targeting (not yet complete) I'm posting it as a draft for now because I have a question/am stuck on something. To get the buttons to work properly I have to add `mymob.client.reset_screen()` to `grue_hud()`. However, doing so seems to break the visuals and make everything blurry. I thought maybe it was related to the custom grue-vision colors and such so I commented that out to test but the same blurriness bug still occurred. So I'm wondering if anyone knows how to fix that or what could be causing that bug.

The blurriness seems like only the lighting layer is being rendered and not the actual atoms beneath it.

I also need to update the icons.

[wip][help]

Closes #32313
:cl:
 * rscadd: Stop pulling and zone targeting buttons for grues.

### CODE REVIEW

**Comment by pedr69** [comment]
related
#32313

**Comment by adacovsk** [comment]
No need for a stop pulling button. Instead, stop pulling when grue takes damage. Simple as

**Comment by Hinaichigo** [comment]
People have been asking for a stop pulling button specifically. Stopping pulling when they take damage is interesting, but one issue is that it might make pulling victims out of a bright room into the darkness hard to do.

**Comment by adacovsk** [comment]
> People have been asking for a stop pulling button specifically. Stopping pulling when they take damage is interesting, but one issue is that it might make pulling victims out of a bright room into the darkness hard to do.

They're lil babies. Plus, I think it's a good nerf for grue while also benefitting them

**Comment by Hinaichigo** [comment]
They actually can already stop pulling by ctrl-clicking or using the "stop pulling" verb. Only, not everyone knows about that it seems, and since other mobs have it and it's been requested several times I'm thinking it could be good to be consistent.

I think I see what you're getting at with the damage thing, but something I've been thinking about is making the light damage ticks more frequent, happening every ingame tick or so rather than every 2 second "Life ticks". If we did that then it would make it very hard to pull if they dropped what they were pulling when damaged.

edit - Unless it didn't count light or burn damage and only dropped upon receiving brute damage or something.

**Comment by Eneocho** [comment]
I said it on the grue feedback thread on the forums, but teen grues are insufferably weak while adult grues are impossibly strong in comparison. It really needs some rebalancing so teens don't die instantly, since you die to the lighting so fucking quickly and even some tame anti-grue precautions (such as wearing a lantern in the pocket) will most likely kill you before you eat your victim, not to mention the powerfaggotry of tiling maint with light tiles which just instacucks the grues. 
I've played grue some 20 times and only once did I manage to get to turn adult and that was with a lucky laggy spessman to consume. After the turboweak part it was relatively easy, but the beginning is way too hard even against regular crew (you can die to fucking PDA lights while eating crew, I know this because it happened). You heal way too slow as a teen to survive someone chasing you, which means you gotta engage, and they can just shoot you once or twice and you're done.

**Comment by Hinaichigo** [comment]
What'd be the best way to address that? Increase the healing speed, decrease the light damage for juveniles, or something else?

**Comment by Eneocho** [comment]
I'd say increase the healing speed, since that'd help with both tanking hits and light exposure for longer than just making light do less damage.
Or making them able to ventcrawl, but that's a whole balance change.

**Comment by Hinaichigo** [comment]
I was typing this up when you responded so I'll just say it here instead of editing the above post.

To prevent juvenile grues from being able to simply rush down someone who's well prepared (has a flashlight) I feel like maybe an ideal solution would be something along the lines of increasing the survivability or evasiveness of the juvenile rather than the offensive potential directly. I think it is nice to have the juvenile stage be somewhat of the "gate" that separates the grue who needs to lurk and be stealthy and hide its presence from the crew initially, from the adult grue who can rush people down and slay them with relative ease.

But yeah I think the healing speed thing could help address that, as you say. Maybe a factor of 1.5x the current rate?

**Comment by Eneocho** [comment]
I'd say increase by a factor of 2, they heal incredibly slow. If it turns out to be too strong we can dial it back later.

**Comment by Hinaichigo** [comment]
Sounds good.. and maybe slightly decrease the per-being eaten healing?

**Comment by Hinaichigo** [comment]
Now.. if only I knew why `reset_screen()` is causing everything to look blurry here.
It's almost like it causes only the lighting overlay to render and hides all the actual sprites and everything under it.

**Comment by Eneocho** [comment]
I haven't touched it, but I hear UI code is a disaster, I wish you best of luck here.

**Comment by Hinaichigo** [comment]
It's weird because as far as I can tell everything should be the same as the cult constructs, for whom pulling and zone targeting works fine, but apparently something is different. I'm not sure what yet.

**Comment by Hinaichigo** [comment]
Gonna close this until I figure it out.

**Pull request closed without merging**
