### PR TITLE
Adds wifebeaters to underwear

### PR DESCRIPTION
**Pull request by BurntDevil**
Adds wifebeaters and husbandbeaters so you can dress appropriately while beating your waifu or husbando of choice. Comes in 3 flavors for males and females.

<a href="https://imgur.com/79qRFpx"></a>

:cl:
 * rscadd: Shipments of wifebeaters have been sent out, crewmen.

### CODE REVIEW

**Comment by KingofHONK** [comment]
https://youtu.be/OiUoXAfVjuI

**Comment by beesil** [comment]
solid idea, but shading is inconsistent, chests of fem sprites look really off and the neon pink is ugly

**Comment by BurntDevil** [comment]
yea I need to mess with the pink one some, and the tiddies i hadnt noticed were a line too high up, fixing them now

**Comment by SonixApache** [comment]
about time

**Comment by BurntDevil** [comment]
that should clean up any remaining issues

**Pull request merged**
