### PR TITLE
Adds a screen alarm for renaming yourself

### PR DESCRIPTION
**Pull request by MadmanMartian**
So that the name function doesn't take away priority from the main game screen until you want it to

~~Still need to test with monkeys, I believe they don't have screen alarm code yet for their HUD~~

:cl:
 * rscadd: For clowns, mimes, AIs, ninjas, wizards and monkeys, the change name popup has been moved to a screen alarm. Click the screen alarm, and it will bring up the previous popup.

### CODE REVIEW

**Comment by DamianX** [comment]
Wizards and apprentices should use this as well

**Comment by MadmanMartian** [comment]
Okay, monkeys work

**Comment by brndd** [comment]
Maybe with this PR it'd be time to remove the limit on the naming attempts, and just make the screen alarm persist until you pick a name successfully.

**Comment by jknpj** [comment]
But then you'd be able to keep your name change as clown and change it when you're wanted.

**Comment by brndd** [comment]
You can already do that under this system.

**Comment by jknpj** [comment]
The alarm only lasts for 30 seconds though.

**Comment by brndd** [comment]
Nevermind in that case.

**Pull request merged**
