### PR TITLE
Spesschan

### PR DESCRIPTION
**Pull request by ShiftyRail**
spesschan

[content]

:cl:
- rscadd: Added anonymous mode for newscasters' feeds

### CODE REVIEW

**Comment by Kharkov72** [comment]
>walk into the bar

**Comment by oversane** [comment]
I hate Moot, what a faggot

**Review by Kurfursten — CHANGES_REQUESTED** [review]
As far as I can tell there's no true logging of who said what, so this will be bad if people start to ock ick or do other unsavory things in anon mode.

**Comment by ShiftyRail** [comment]
My evil plan, foiled

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
