### PR TITLE
Allow most vehicles to spin once again

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * tweak: Vehicles can once again change direction without moving by holding CTRL and arrow keys.

### CODE REVIEW

**Comment by Exxion** [comment]
\>see that line
\>wonder who the fuck wrote it
\>check blame
\>it was me

**Comment by Exxion** [comment]
Anyway it was removed from the Firebird specifically because ghosts could spin it and make it impossible for wizards to aim fireballs, then for some reason everyone told me to remove it from all vehicles

**Comment by DamianX** [comment]
I like the double negative when you set `noghostspin` to 0, too.
I've excluded firebirds once again.
It's pretty stupid that we abuse the same var for deciding both whether ghosts can make something spin, and whether it can be rotated by the actual driver.

**Comment by Exxion** [comment]
That isn't intentional
That var prevents ghosts and incapacitated/restrained players from spinning the thing
But if you're buckled to it, you're restrained, which either didn't occur to me at the time or wasn't the case back then

**Comment by DamianX** [comment]
Deity changed it here a month ago #30441

**Comment by Exxion** [comment]
Ah, I see
What the fuck?

That should 100% be a separate var, but also allowing ghosts to spin vehicles except the Firebird is good as well

**Comment by DeityLink** [comment]
I added this specifically to prevent ghosts from spinning the Adminbus

**Comment by Eneocho** [comment]
Still mad that you can't spin the shuttle chairs or the chapel pews anymore.

**Comment by Exxion** [comment]
>I added this specifically to prevent ghosts from spinning the Adminbus

You added what exactly to prevent ghosts from spinning the Adminbus? I added both this var and this line of code, ~~and at the time of both of those, the Adminbus was not a vehicle~~
Also,
1. Why should ghosts not be able to spin the Adminbus?
2. Why would it be preferable to block them from spinning *all* vehicles rather than just the two you don't want them to spin?

EDIT: I remembered something incorrectly but the rest stands

**Comment by DamianX** [comment]
With the latest commit there's one var that decides whether something can spin at all, and one var that decides whether ghosts can spin it.
Below is a table of all chairs and their new vars. Let me know if something is off.

EDIT: worth noting that something having `ghost_can_rotate = TRUE` but `can_rotate = FALSE` still won't be able to spin at all.

| type | name | can_rotate | ghost_can_rotate |
|------|--------|--------------|--------------|
| /obj/structure/bed/chair/e_chair | electric chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/wood/normal | wooden chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/wood/pew/left | pew | ❌ | ✔️ |
| /obj/structure/bed/chair/wood/pew/right | pew | ❌ | ✔️ |
| /obj/structure/bed/chair/wood/pew/mid | pew | ❌ | ✔️ |
| /obj/structure/bed/chair/wood/pew | pew | ❌ | ✔️ |
| /obj/structure/bed/chair/wood/wings | wooden chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/wood/throne | throne | ✔️ | ✔️ |
| /obj/structure/bed/chair/wood | chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/holowood/normal | wooden chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/holowood/wings | wooden chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/holowood | chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/comfy/turn | comfy chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/comfy/brown | comfy chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/comfy/beige | comfy chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/comfy/teal | comfy chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/comfy/black | comfy chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/comfy/lime | comfy chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/comfy/red | comfy chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/inward/beige | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/inward/lime | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/inward/brown | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/inward/teal | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/inward/black | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/inward/red | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/inward | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/outward/beige | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/outward/lime | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/outward/brown | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/outward/teal | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/outward/black | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/outward/red | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn/outward | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/turn | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/left/beige | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/left/lime | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/left/brown | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/left/teal | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/left/black | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/left/red | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/left | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/right/beige | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/right/lime | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/right/brown | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/right/teal | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/right/black | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/right/red | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/right | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/mid/beige | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/mid/lime | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/mid/brown | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/mid/teal | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/mid/black | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/mid/red | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch/mid | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy/couch | couch | ❌ | ✔️ |
| /obj/structure/bed/chair/comfy | comfy chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/office/light | chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/office/dark | chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/office | chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/folding | folding chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/shuttle/red | seat | ❌ | ✔️ |
| /obj/structure/bed/chair/shuttle/blue | seat | ❌ | ✔️ |
| /obj/structure/bed/chair/shuttle/yellow | seat | ❌ | ✔️ |
| /obj/structure/bed/chair/shuttle/white/custom | seat | ❌ | ✔️ |
| /obj/structure/bed/chair/shuttle/white | seat | ❌ | ✔️ |
| /obj/structure/bed/chair/shuttle/gamer | seat | ✔️ | ✔️ |
| /obj/structure/bed/chair/shuttle | seat | ❌ | ✔️ |
| /obj/structure/bed/chair/plastic/plastic_chair | plastic chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/plastic | chair | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/adminbus | Adminbus | ✔️ | ❌ |
| /obj/structure/bed/chair/vehicle/tractor | tractor | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/clowncart | clowncart | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/firebird/santa | magic snowmobile | ✔️ | ❌ |
| /obj/structure/bed/chair/vehicle/firebird | Firebird | ✔️ | ❌ |
| /obj/structure/bed/chair/vehicle/gigadrill | gigadrill | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/gokart | Go-Kart | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/janicart | janicart | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/lightcycle | light cycle | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/secway/custom/everything | The Towberman | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/secway/custom | Baby | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/secway | secway | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/snowmobile/universal | snowmobile | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/snowmobile/security | security snowmobile | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/snowmobile | snowmobile | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/wheelchair/multi_people | wheelchair | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/wheelchair/motorized/syndicate | medical malpractice | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/wheelchair/motorized | motorized wheelchair | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/wheelchair/wheelchair_assembly/cannon | cannon | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/wheelchair/wheelchair_assembly | wheelchair assembly | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle/wheelchair | wheelchair | ✔️ | ✔️ |
| /obj/structure/bed/chair/vehicle | vehicle | ✔️ | ✔️ |
| /obj/structure/bed/chair | chair | ✔️ | ✔️ |

**Comment by DeityLink** [comment]
@Exxion 

> You added what exactly to prevent ghosts from spinning the Adminbus?

This line here, last month, which was a small oversight I literally took ages to fix but finally got around to do. https://github.com/vgstation-coders/vgstation13/commit/6b53923fee54d69a47d0af0c589f2e847ad1ba5f#diff-c1575e6bd910cc9e12eb22299d1f8ad66683f6f9cce62607b1e4568afe1ef91cR14

I should have been more specific, I only also added the var to pews and shuttle chairs and didn't touch the other vehicles, I thought I might had but turns out no. Plus since the adminbus subtype now has the var directly set, it would be unaffected by a change of the parent's default value so I really should double check the code before I complain.

1.  Why should ghosts not be able to spin the Adminbus?

My immulsions, only admins should have any level of control over the adminbus.

2.  Why would it be preferable to block them from spinning all vehicles rather than just the two you don't want them to spin?

I wouldn't want that for all vehicles, I failed my INT roll earlier and didn't elaborate what I meant in my comment, sorry for that.

**Pull request merged**
