### PR TITLE
Fixes Utility Borer Attack Spam and Other Things

### PR DESCRIPTION
**Pull request by Shadowmech88**
Fixes the fleshshot's attack delay so borers can't go fist-of-the-north-star on opponents. They are now able to land an attack with the fleshshot only once per second, though it can still be fired as fast as the borer is able to fire it.

Reduces the bone sword's force from 20 to 18, reduces the bone hammer's force from 35 to 25.

Defense-spec borers now get a verb to produce an EMP instead of doing it via a chem. The cost is still 100 chems per EMP.

### CODE REVIEW

**Comment by clusterfack** [comment]
The ham serum is supposed to be that way.

The real question is why are you using it the way you are?

**Comment by Shadowmech88** [comment]
Yeah, I guess I could put it into a verb.
I just figured that since there was already a chem that could make EMPs, I might as well use that.

_Why_ is it intended to only function on eating? If you produce a potent ham, grind it up, and inject yourself with it, why shouldn't the effect still take place?

**Comment by clusterfack** [comment]
Because we didn't want people grinding up the chem and doing that with it

**Comment by Shadowmech88** [comment]
Oh, alright.
Guess I'll turn it into a verb, then.

**Comment by clusterfack** [comment]
Much appreciated

**Comment by Shadowmech88** [comment]
Alright, done.

**Pull request merged**
