### PR TITLE
The "Thunderdome" playlist will now appear in the bar jukebox

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I like it. I want to hear it more often. The bar is also a common location for a rage cage.

:cl:
 * rscadd: The bar's jukebox now has the "Thunderdome" playlist.

### CODE REVIEW

**Comment by brndd** [comment]
>2567
>walk into bar
>A Functioning God starts playing

**Comment by juanototo2** [comment]
Add the thunderdome disc to the trader, xenoarch, or some other external source that makes it somewhat rare but not impossible to acquire. I like it too, but it has to be special -- same thing for the malfdelta and nukesquad discs.

**Comment by boy2mantwicethefam** [comment]
Music is too good to restrict it to the trader and it already belongs on the russian DJ station which is raid-able.

**Comment by Kurfursten** [comment]
Lack of strong support to overcome the specialness of the disk
Wouldn't oppose seeing it as vault loot or something though, more useful vinyls should be findable

**Pull request closed without merging**
