### PR TITLE
ion rifles are now EMP proof

### LINKED ISSUE #12551: Ion Rifles short other Ion rifles
(WEB REPORT BY: acedick REMOTE: 172.93.109.202:7777)
>Revision 17b57e93c63540e1ecd6b513747953d9

>General description of the issue
Ion rifles' localized ion effect usually doesn't short the ion rifle itself that fired it even if you're caught in it, however with another one on my person the ion shorted that one. This is running off the assumption that ion rifles themselves should be resistant to being ion blasted.

>What you expected to happen
Ion rifle would not short and lose all charge, like the rifle that was fired.

>What actually happened
Ion rifle that was fired remains charged, other ion rifle does not.

>Steps to reproduce if possible
>have two rifles
>fire ion blast close enough to get caught
>other ion rifle will lose charge, fired one will not

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #12551

:cl:
 * tweak: Ion Rifles are now EMP proof, so they cannot ion themselves.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by ComicIronic** [comment]
This is on either you or cluster as playing collabs.

**Comment by Exxion** [comment]
>Cluster
>Playing

**Comment by ComicIronic** [comment]
Well what else does he do in the Discord

**Comment by Exxion** [comment]
Play games that are not SS13
Talk about code
Talk about things

**Comment by ghost** [comment]
Cluster doesn't really play nah

**Comment by 9600bauds** [comment]
I used an ion rifle once, I qualify

**Pull request merged**
