### PR TITLE
Fixes #9863

### LINKED ISSUE #9863: INFINITE MEDICAL MODULE BOARDS
#### Description of issue

Mediborgs can take infinite medical module upgrades

#### Difference between expected and actual behavior

Expected it to only take one, but instead INFINITE UPGRADED HYPOSPRAYS
#### Steps to reproduce

Use more than one medical module upgrade on a mediborg
#### Specific information for locating

Medical module board
#### Length of time in which bug has been known to occur

I'd assume since 510, but I haven't tried before now
#### Server revision

416f345e9029f0fccacf211221a265d43a19994f
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by ghost**
fixes #9863

### CODE REVIEW

**Comment by ComicIronic** [comment]
Can you check if you can do the same thing for service borg upgrading and then fix that as well?

**Comment by ghost** [comment]
@ComicIronic sure

**Comment by Intigracy** [comment]
Something tells me all the borgs that have an upgrade module have this issue.

**Comment by ghost** [comment]
I'm gonna rewrite this nonsense.

**Comment by ghost** [comment]
this was way out of the scope I was intending

**Comment by ghost** [comment]
not worth fixing
why did I do this

**Comment by Probe1** [comment]
Now you understand why I failed two separate times to fix this issue.

**Pull request merged**
