### PR TITLE
Slightly reworks how credits and jingles work

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Basically the benefit is that the host can just dump files into folders without changing anything, the only thing that would have to be changed code-wise is if there are new folders

**BEFORE IT IS MERGED** the host needs to
- Add two folders, one called "default" and one called "nuke" and move the songs to their respective folders

that's it

### CODE REVIEW

**Comment by Kurfursten** [comment]
Let us know when you get pomf to do that

**Review by ShiftyRail — APPROVED** [review]
Code looks ok, but I'm not sure if the relevant files got pushed to the media repo.

**Comment by Kurfursten** [comment]
THE FILES BARRY

**Comment by boy2mantwicethefam** [comment]
tomorrow:tm:

**Comment by DamianX** [comment]
Did you do the thing?

**Comment by boy2mantwicethefam** [comment]
Pomf is supposed to do it BUT HE'S LAZY

**Comment by SonixApache** [comment]
WHEN

**Comment by boy2mantwicethefam** [comment]
re-open this if pomf wakes up

**Comment by SonixApache** [comment]
@d3athrow WAKE UP

**Comment by d3athrow** [comment]
let it be known that barry is too stupid to use git and instead of admitting as such sat quiet for the last 2 weeks before closing the PR while trying to blame it on me.

**Pull request closed without merging**
