### PR TITLE
Maps now require at least 2 votes to be considered for weighted voting.

### LINKED ISSUE #9640: Remove Weighted Map Vote
Issue is very straight forward. Whenever this kicks in majority of the playerbase is forced to play on a map they don't want to and some or most of them leave the server depending on the current pop. 

If it was low or low-mid pop this turns the whole thing into deadpop.

### PR DESCRIPTION
**Pull request by Intigracy**
closes #9640 

Memers who vote for the map and then quit when it wins, smh. Now it will take 2 memers.

### CODE REVIEW

**Comment by MusgardTiger** [comment]
This is at least something.

Even better make it at least five votes because 2 memesters can still cause an issue and if five memesters decide to gang up, so be it I guess.

**Comment by ghost** [comment]
:-1:

**Comment by ghost** [comment]
Fair enough, although I would prefer a more profound rework down the line

**Comment by Exxion** [comment]
:-1: :heavy_multiplication_x: :100:

**Comment by Zth--** [comment]
the real solution here is to remove taxi

**Comment by clusterfack** [comment]
Yeah no this is dumb, better that we make the ballot numbers anonymous and secret and just remove taxi which is **the thing you all are really complaining about when you make this anti-weighted map vote issues**

**Comment by ghost** [comment]
How about if it gets a tenth of the vote at minimum, it gets in?

That way, no more moaning about 'Oh, one guy's being a dick', because it'd need 1 in 10, 2 in 20, 3 in 30 etc. to get a chance at the map.

**Pull request closed without merging**
