### PR TITLE
pAI Slot Tweaking

### PR DESCRIPTION
**Pull request by Kurfursten**
Fully tested

🆑 
* tweak: The pAI can now inject chems (or hand food to master) from anywhere, even a bag, internals box, or slotted into the PDA.
* tweak: When ejecting a pAI from the PDA, it will attempt to place into your hand instead of the floor.

### CODE REVIEW

**Comment by Diavill** [comment]
pOWER creep

**Comment by jknpj** [comment]
Closes #15493

**Comment by Shadowmech88** [comment]
It may be a balance concern that a pAI in a smart laser is now capable of healing its master as well as attacking for them.

**Comment by Kurfursten** [comment]
I'm not too worried honestly. Smart lasers are not common and pAIs don't many chems at their disposal.

They aren't like borers who can shit out tons of chems with no delay that are tailored to the problem, like dex plus or bicaridine. They've got tricord on a fifteen second delay.

**Pull request merged**
