### PR TITLE
Sodium and water explosions

### PR DESCRIPTION
**Pull request by ghost**
[content][tested]
Mainly done for immulsions sake, the reaction from this also creates a chemical similar to potassium hydroxide called lye. The former has also been renamed potash, for consistency.
Tested with chemical reactions, no real hiccups or new risks of explosions with normal recipes, (save sodium polyacrylate) just be extra careful from now on with the order of ingredients of any reaction that uses both sodium and water at any point, making sure they aren't in the beaker together.
:cl:
 * rscadd: Sodium and water are not safe to mix by themselves anymore. Its product is now lye, a potassium hydroxide analogue.
 * tweak: Potassium hydroxide has been renamed potash.

### CODE REVIEW

**Comment by Armadingus** [comment]
what happens here then
image

**Comment by ghost** [comment]
> what happens here then image

Worked if you input them in the right order, but it made a test fail. Changed it to 3 parts carbon, 2 part lye, 1 part water, with some tweaks so it behaves the same.

**Comment by west3436** [comment]
Make sure Lye causes burn damage at least to humans

**Comment by ghost** [comment]
> Make sure Lye causes burn damage at least to humans

It inherits potash so it does.

**Comment by Eneocho** [comment]
If I mixed 100u Sodium and 100u Potassium with 200u Water, would it explode once, twice or would it be equal to a 200u x 200u Waterpot?

**Comment by ghost** [comment]
> If I mixed 100u Sodium and 100u Potassium with 200u Water, would it explode once, twice or would it be equal to a 200u x 200u Waterpot?

Tested this actually, explodes once and wipes the contents of the beaker.

**Comment by Eneocho** [comment]
Figured as much, no wacky double bombs. You COULD add an interaction for double explosions or at least make both count as one reagent for waterbomb purposes (so 150 sodium and 150 potassium act like 300 potassium for the bomb reaction).

**Comment by ghost** [comment]
> Figured as much, no wacky double bombs. You COULD add an interaction for double explosions or at least make both count as one reagent for waterbomb purposes (so 150 sodium and 150 potassium act like 300 potassium for the bomb reaction).

That last one doesn't sound like too bad of an idea, honestly.

**Comment by djkramer123** [comment]
This PR is a bad idea

**Comment by Eneocho** [comment]
> > Figured as much, no wacky double bombs. You COULD add an interaction for double explosions or at least make both count as one reagent for waterbomb purposes (so 150 sodium and 150 potassium act like 300 potassium for the bomb reaction).
> 
> That last one doesn't sound like too bad of an idea, honestly.

I would love to see double bombs though.

**Comment by Kurfursten** [comment]
Lacking support

**Pull request closed without merging**
