### PR TITLE
adds pharaoh clothes to magivend

### PR DESCRIPTION
**Pull request by RealestEstate**
The recent raids on the various ancient Egyptian tombs throughout the sector have awoken a large population of once hibernating Space Pharaohs. In search of the necessary financial income to restore their lost tombs, many of these newly awaken mummy kings have went to seek employment opportunities from places like the Wizard's Confederation.

:cl:
 * rscadd: Pharaonic themed clothing available to wizards from their local magivend

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
WE

**Comment by DrSnips** [comment]
WUZ

**Comment by Ephx1** [comment]
SPACE KANGZ

**Comment by tuypo1** [comment]
Ah dammit, I had a kangz joke in mind but you guys preempted it with a low effort reference

**Comment by RealestEstate** [comment]
it was inevitable

**Pull request merged**
