### PR TITLE
Removed round-start vampires

### PR DESCRIPTION
**Pull request by DamianX**
Same reason lings got removed: not fun.

:cl:
 * rscdel: Removed round-start vampires.

### CODE REVIEW

**Comment by Inorien** [comment]
Anyway, how are the wife and kids doing?
_Spontaneously sprouts fangs_
Oh sorry I just suddenly remembered I was a vampire
MUH IMMULSHUNS
Would it be feasible to raise the chance of rolling vamp/ling on latejoining? Or is that turbo shittery

**Comment by tayachiya** [comment]
Remove the wiz as well while we're at it, because they have some really un-fun spells.
Oh and tator because parapen
Why the hell are the paranormal antags being removed?

**Comment by ddolll** [comment]
Vampire was a mistake.
Compared to ling, vampire:
- Has a much larger emphasis on snowballing, with roundstart vamps more or less a once-per-3-minutes parasting combo, and endgame vamps having screenwide stuns, revives, walls of slaved allied antagonist, and a billion mobility, combat and surveillance options. This pretty much enforces the least interesting and enjoyable (for the crew, and honestly for the vampire unless you're a huge faggot) playstyle since you almost have to stealthmurder people with your silence+stuns in order to get powerful, and powerful vampires are almost unstoppable if they play conservatively.

- Is a worse stealthmurder focused antag. They are just bad in general. Silently depopulating the station leads to long rounds where most of the players are dead, and that's just uninteresting both for those who survive and those who don't. There's not even a 'whodunnit' aspect to stealthy vampires, since you can literally check if someone is or isn't a vampire. Vampires don't ever stop wanting more blood, and the benefits they gain from snowballing are so huge that there's no reason for them to ever stop and go loud. Really high blood vampires can just thrall every second person instead of murdering them, which yet again makes the round not only not end but also involve no other gameplay than that based around the movements of someone who literally never has to take risks. At least lings killed people quickly enough that the round came to a head.

- Is based entirely around metachecks in terms of prevention and combating, since metachecks allow you to objectively clear people of being vampires or objectively determine that someone is a vampire. Holy water is also an absolute necessity for nonantags to deal with thralls, since there's not really any other way to deal with them that doesn't involve possibly/likely removing nonantags from the round forever for no good reason.

**Comment by Exxion** [comment]
>commenting out code with block comments

**Comment by TheFriggenSawbones** [comment]
please

lets stop removing shit. dynamic is fuckin bonkers anyways i dont trust it to roll anything

**Comment by Orangerush** [comment]
You forgot to somehow get banned from vampire "to make a point"

**Comment by ShiftyRail** [comment]
If the problem is lowpop vampire, then you can make its threat requirement 101 on the first few levels to make it unable to roll on deadpop, which is where it's the most frustrating.

**Pull request closed without merging**
