### PR TITLE
Buffs cow and goat milk production.

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Cows and Goats now make more milk, anywhere from 10-15u (from 5-10u) and make it more often, with cows outproducing goats, milkwise.
Also buffs the total milk storage for goats to 100 and cows to 150.
## Why it's good
On testing how cows (and by extension, goats) worked we realized just how bad at making milk they were, so I made this.
## How it was tested
Numbers went up.

:cl:
 * tweak: Cows and Goats make more milk, with cows outproducing goats.
 * tweak: Goats can now store 100u of milk, Cows can store 150u.

### CODE REVIEW

**Comment by CrazyAmphibian** [comment]
where's the powercreep tag when we need it?

**Comment by Eneocho** [comment]
ask kurf, he stole them before leaving

**Comment by SonixApache** [comment]
cowmaxxing

just get more cows / goats, what is this shit, what kind of horrible abusive rancher are you

**Comment by Eneocho** [comment]
The expected value per tick for milk, according to dilt, was 0.375u, and since milk is stored inside the mob, the cows would also metabolize the milk, at the baseline FOOD_METABOLISM rate, which is 0.4u.
This means that, per tick (averaged), a cow made less milk than it was consuming, thus always being close to empty.

**Review by west3436 — APPROVED** [review]

**Pull request merged**
