### PR TITLE
Readds secways and makes them orderable from cargo for 500 credits

### PR DESCRIPTION
**Pull request by JustSumBody**
beep
Alright, so the secway keys are locked in a box with the warden, they'll no longer spawn with them. There are 4 keys at the start of the round. Any secway key works with any secway.

### CODE REVIEW

**Comment by kol1th** [comment]
image

**Comment by ScrambledSteak** [comment]
> 1000 credits
> 1000 FUCKING CREDITS

How is a goddamn segway the same price as two supermatter shards, which come from the CORES OF GAS GIANTS and can probably be used to POWER CITIES.

**Comment by clusterfack** [comment]
Can you make it so it requires a key and a set of keys spawn in a lockbox in wardens office

**Comment by jknpj** [comment]
@Aurantiaco  _¯\_(ツ)_/¯_

At this price, how much time does it take for a wagecuck officer buy his own secway?

**Comment by Exxion** [comment]
Did you make it so that secways don't generate keys when spawned anymore?

**Comment by PJB3005** [comment]
@Exxion probably not.

**Comment by Exxion** [comment]
Yeah it does say that, but I didn't see in the code where he changed it so that it wouldn't
I still don't see in the diff what did it, but looking at the whole file it looks in order so whatever

**Comment by Kurfursten** [comment]
Do Secways have infinite power or do they need to be charged like a motorized wheelchair?

If they need to be charged, bring the price down to equal the wheelchair. If they're infinite, price seems fine.

**Comment by Intigracy** [comment]
How about since you don't even get keys with them that you lower the price to 500?

**Comment by clusterfack** [comment]
Codewise its ready to ship I have no concern

**Comment by clusterfack** [comment]
Lets see how it goes family

**Comment by kol1th** [comment]
what could possibly go wrong? :^)

**Pull request merged**
