### PR TITLE
No Flask

### PR DESCRIPTION
**Pull request by Kurfursten**
@DamianX  was right and I was wrong. It did feel less special if you could get it more frequently, Karmotrine should remain a xenoarch thing.

🆑 
* rscdel: Removed the ancient flask from the tradevend.

### CODE REVIEW

**Comment by ghost** [comment]
make it so the flask can only be decanted by users with the sober gene

**Comment by Dacendeth** [comment]
Replace it with flask that passively fills itself with beer.

**Comment by Kurfursten** [comment]
Cute idea

**Comment by RealestEstate** [comment]
yo what if we made ancient plants a premium item in the seed vendor

**Comment by tuypo1** [comment]
> yo what if we made ancient plants a premium item in the seed vendor

That would be way worse
I haven't played much lately to know what sort of effect this had but that would be straight up broken

**Pull request merged**
