### PR TITLE
Reduces average flash stun from 20 seconds to 10 seconds

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
## Why it's good

Ubiquitous, common, and instant. Their stun duration is excessive compared to other, far more restricted items, and the only way to block them is through protective headwear and glasses, which would be a good balance if the stun duration wasn't so excessive for NOT having the protection. It's not really immersive compared to what they do (which is excessively blind someone), and if you use them sparingly enough (at least once a minute) they will never burn out, providing unlimited uses for something that's scattered in Technical Storage, the Bridge, Robotics (as one-use flashes, those don't have unlimited uses but they can be printed) etc.
How is a flash causing as much shock as getting thoroughly electrocuted is? Where's the fun in that? Flashes should be devastating to silicons but not THAT incapacitating to regular people.

Actual changes:
- Base flash strength against humans (NOT silicons, you're basically pointing it at their eyes) reduced from 20 seconds to 10 seconds; people who wear active meson scanners will get stunned for 20 seconds instead of 30 (thirty seconds if you had your mesons on! Unbelievable).
- Mounted flasher duration reduced from 20 seconds to 10, including against cyborgs (it's not quite directed at their visual sensors). Arguably this could be left to its full duration because its primary use is letting officers remove cuffs from the prisoners they've captured.
- Portable flasher (the one that officers can mount) duration reduced from 16 seconds to 8 seconds, including against cyborgs.

:cl:
 * tweak: Flashes will now stun humans for 10 seconds instead of 20 seconds. Silicons will still be stunned for 20 seconds, as it is directly targeted towards their sensors.
 * tweak: The stun from the mounted flashers has been reduced to 10 seconds for both humans and silicons.
 * tweak: The stun from the portable flashers (the ones that you might see around the Brig to deter criminals) has been reduced from 16 seconds to 8 seconds for both humans and silicons.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
I can't ever recall being flashed for more than 10 seconds. Perhaps I am misremembering. I think this is a pretty big change to balance, though and I'm not convinced it's needed.

**Comment by boy2mantwicethefam** [comment]
Flashes last 20 seconds, about as much as stunbatons and tasers do.

**Comment by bathosbathtime** [comment]
I am against this PR for its reduction in cyborg stun times. Should those be removed from the PR, I would be apathetic to this PR.

**Comment by boy2mantwicethefam** [comment]
Stationary flashers rarely come up against silicons, considering the fact that they don't even trigger portable flashers.
Regardless, I am closing the PR due to a negative initial reception.

**Pull request closed without merging**
