### PR TITLE
We have you surrounded, come drink your corn syrup

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
Adds corn syrup, a cheaper production alternative of sugar made with 10 units corn oil, 2 units sugar and 5 units universal enzymes as a catalyst, inspired by its real life arise of usage.

## Why it's good
Allows faster production of sugar with lesser amounts and a supply of corn oil.

## Changelog
:cl:
 * rscadd: Nanotrasen has you surrounded, come drink your corn syrup by mixing 10u corn oil and 2u sugar with 5u universal enzymes as a catalyst. Discount Dan has also taken a liking to it, putting it in his products in light of the cost reduction discoveries.

### CODE REVIEW

**Comment by Eneocho** [comment]
This is a hard nerf to ghetto chem due to not only not getting raw sugar from groans soda or discount dan's, but the sugar you get from electrolysis is way less than previously intended. You get 30u sugar on Filk: Sugar Blast. Now you only get 6. 
Also your recipe calls for moonshine not corn oil.

**Comment by Killette3** [comment]
I can't wait to fuck up the chefs fryer corn oil reserve with his own bags of sugar and enzymes for a new fried flavor

**Comment by Exxion** [comment]
>Also your recipe calls for moonshine not corn oil.

That's because corn oil plus enzyme makes moonshine
This is really not an ideal disambiguation method but whatever

**Comment by west3436** [comment]
> This is a hard nerf to ghetto chem due to not only not getting raw sugar from groans soda or discount dan's, but the sugar you get from electrolysis is way less than previously intended. You get 30u sugar on Filk: Sugar Blast. Now you only get 6. Also your recipe calls for moonshine not corn oil.

Dude please stop with muh balance nitpicking
You can walk into maint on any map and grow sugarcanes for sugar by 12:10

**Comment by Eneocho** [comment]
Its not nitpicking (and I'm very against "muh balance > fun", see the jetpack PR for example). You literally can't do ghetto chem as you can currently if this passes. You'll be forced to not only centrifuge the chems first but electrolyse as well and you won't get as much when electrolysing. I'm all for flavour and SOVL, but this hard nerfs a beloved part (for me) of being a greyshirt.

**Comment by Eneocho** [comment]
If corn syrup worked as an alternative to sugar in the sugar-using chemical recipes I'd be ok with it.

**Comment by Exxion** [comment]
> If corn syrup worked as an alternative to sugar in the sugar-using chemical recipes I'd be ok with it.

Good news: That's what the majority of changed lines in this PR are for

EDIT: Oh wait, it's only for *cooking* recipes
That's not really consistent with current usage of reagent lists

**Comment by Eneocho** [comment]
Now you see what my issue is.

**Comment by SECBATON-GRIFFON** [comment]
> This is a hard nerf to ghetto chem due to not only not getting raw sugar from groans soda or discount dan's, but the sugar you get from electrolysis is way less than previously intended. You get 30u sugar on Filk: Sugar Blast. Now you only get 6. Also your recipe calls for moonshine not corn oil.

pretty sure you can still get real cane sugar in other non-dan vendors, this only applies to dan products

> EDIT: Oh wait, it's only for _cooking_ recipes That's not really consistent with current usage of reagent lists

can make it chems too if it's THAT much of a problem

**Comment by Eneocho** [comment]
>can make it chems too if it's THAT much of a problem

please do

**Comment by Exxion** [comment]
For the inconsistency specifically, just changing the name of the define to something that reflects its intended use would be fine
I'm honestly not even sure what the gameplay purpose of the PR is, though. It seems to just be for a meme that I've never heard anyone else repeat. Yeah, you *say* it lets you make more effective sugar, but in the game it's not really any easier to get corn oil than sugar. I haven't played botanist in a while, so correct me if I'm wrong, but isn't sugarcane one of the fastest-growing plants?

**Comment by Pastamadness** [comment]
Could you add some mild hallucination-healing to the reagent effect or would that be too memetic?

**Comment by WindowsErrors** [comment]
space station 13 players will get controversial over truly some of the strangest things

**Comment by Eneocho** [comment]
Can you please implement this
>can make it chems too if it's THAT much of a problem

**Comment by xeroxemnas** [comment]
> space station 13 players will get controversial over truly some of the strangest things

Eneocho hates the antichrist

**Comment by WindowsErrors** [comment]
> > space station 13 players will get controversial over truly some of the strangest things
> 
> Eneocho hates the antichrist

i do too

**Comment by Kurfursten** [comment]
Given that this is substantially close and affects several common recipes, I would like to see you come to a compromise on this issue. Tweak the recipe so that everyone will be happy.

**Comment by WindowsErrors** [comment]
come drink your New Coke

**Comment by SECBATON-GRIFFON** [comment]
> Given that this is substantially close and affects several common recipes, I would like to see you come to a compromise on this issue. Tweak the recipe so that everyone will be happy.

made the recipes all work with it too, and put normal sugar back in filk: sugar blast @Eneocho

**Comment by Eneocho** [comment]
Alright, that's acceptable. As long as it works on the ghetto recipes as normal sugar.

**Comment by Kurfursten** [comment]
Are there any other objections from the peanut gallery? Speak in the next 24 hours or hold your peace.

**Comment by Blithering** [comment]
Peanut gallery reporting, griefo: crystallic is another that might need to retain real sugar, since I don't want to know if syrup crystalises.

**Comment by Exxion** [comment]
Fructose is *much* more soluble in cold water than sucrose, but it must crystallize eventually, since you can just buy bags of pure granulated fructose
EDIT: Actually, I think some of the other stuff in corn syrup inhibits the fructose from crystallizing, maybe

**Comment by Kurfursten** [comment]
I think he's done enough to meet compromise and the votes have swung more in favor anyway

**Pull request merged**
