### PR TITLE
Revert "Reagent containers gradually heat up and cool down to match the air temperature in their location (air temperature doesn't change)"

### PR DESCRIPTION
**Pull request by SonixApache**
Reverts vgstation-coders/vgstation13#34855

~~i hate going into crit because i want to consume noodles
i hate going into crit because i ate a slice of pizza
i bet this causes the constant stutters(no i have no proof)~~
edit: as i said in https://github.com/vgstation-coders/vgstation13/pull/35189#issuecomment-1765288511 and https://github.com/vgstation-coders/vgstation13/pull/35189#issuecomment-1765572791, i just want to kill The Stutter and hope the collabs agree

### CODE REVIEW

**Comment by west3436** [comment]
While this made showers very fun sources of 0K air, this is a half-baked feature which causes more issues than fun overall.

**Comment by KingofHONK** [comment]
REMOVE BUGGY CODE UNLESS THE BUGS ARE BASED THEN DONT TALK ABOUT THEM OR FIX THEM EVER

**Comment by Substance455** [comment]
I am going to stun prod you
and then force feed you boiling hot noodles
and then you'll die

fucking c*ders

**Comment by SonixApache** [comment]
this PR is a knee-jerk reaction to a perceived issue and doesn't actually fix the dying-to-noodles issue
i'd ask the collabs to try it to see if it fixes the stutter, but that's a pretty low-tech approach to trying to solve the stutter issue

**Comment by Hinaichigo** [comment]
Revert #34842 instead if you want to avoid the ramen thing.

Reverting #34855 as you propose here, won't have the desired effect, and would only keep the ramen hotter and possibly cause more of an issue since it can no longer cool down.

Alternatively you could do this (or something similar, like increasing the temperature threshold for burn damage) to avoid gutting:
#35190

**Comment by pedr69** [comment]
wrong PR, retard
this will only make the noodles stay hot forever

**Comment by Eneocho** [comment]
>reverts the wrong PR

sonix momento

**Comment by kilozombie** [comment]
Revert both PRs

**Comment by Hinaichigo** [comment]
I think maybe people have some confusion about #34855, thinking that it knocks you out or something like the old mob-thermal mass PRs. It just makes it so reagents cool down and heat up over time. All the stuff where reagents temperature actually interact with mobs is in other PRs like the scalding one.

**Comment by Hinaichigo** [comment]
Two alternatives to fix the ramen issue:
#35190
#35191
Feel free to vote on whichever you feel is best.

**Comment by falcon2346** [comment]
I 100% believe that this PR probably wouldn't exist without the server lag and we don't even know for sure if this is what's causing it. I think we should probably actually find out where it comes from before making kneejerk reverts that might break other things.

**Comment by Hinaichigo** [comment]
If someone with profiler access on the server could please check it'd be appreciated.
My own testing locally showed it to be relatively modest in terms of resource use (screenshots in the original PR), where during a fire it used less resources than the lighting system, but maybe the live server could be different.

Also it's set to be one of the lowest priority subsystems, and the subsystems in general have lag-prevention interruption systems where they wait till the next tick to continue processing if there's too much to do in one tick.

**Comment by Inorien** [comment]
Agreed with Falcon that we still have no proof this is causing the stutters, we should hold off on acting over it until there is evidence of it

**Comment by SonixApache** [comment]
> Revert #34842 instead if you want to avoid the ramen thing.
> 
> Reverting #34855 as you propose here, won't have the desired effect, and would only keep the ramen hotter and possibly cause more of an issue since it can no longer cool down.
> 
> Alternatively you could do this (or something similar, like increasing the temperature threshold for burn damage) to avoid gutting: #35190

thank you, I realized that myself and now I want to push this through to see if it will kill The Stutter

**Comment by Hinaichigo** [comment]
Just ask an admin to turn it off in-game with the admin panel to test if it affects the stutter. There's a button there that you can easily do that with.

**Comment by Exxion** [comment]
From basic testing, the subsystem is rather expensive, but not significantly worse than lighting. I highly doubt it is causing the stuttering. Perhaps it can explode in some weird niche scenario, but it seems fine so far.

Though I should clarify that by "fine" I mean it's probably not causing visible performance issues in-game. Its performance is still not what I would call great.

**Comment by wotisjanitor** [comment]
> Agreed with Falcon that we still have no proof this is causing the stutters, we should hold off on acting over it until there is evidence of it

WHATEVER YOU DO, DO NOT TEST IT DOE

> I think we should probably actually find out where it comes from before making kneejerk reverts that might break other things.

DO NOT TEST THIS

> wrong PR, retard
this will only make the noodles stay hot forever

Slavic dna prevents these people from reading the main purposenof the PR, which is to see if the recently merged cooling PR is responsible for the lag.

**Comment by Hinaichigo** [comment]
@SonixApache if this gets merged (instead of disabling it with a one-var change to the config settings), it will re-introduce the behavior where making a hot pill exchanges the heat with the air, and people may complain about it again once they make a 2000K caramel pill. I was thinking to make a new PR disabling it myself in the event of this being merged but currently irl I'm not in a situation that allows me to easily compile and test (phone only). So I'm mentioning this as a reminder about that in case you want to pre-emptively consider addressing that.

**Comment by SonixApache** [comment]
The Stutter is supposedly gone so I am closing this as it is no longer needed, and likely wasn't the cause in the first place.
If The Stutter does come back, I suggest looking at #35260 instead.

**Pull request closed without merging**
