### PR TITLE
Raises lasercannon damage (40->60)

### PR DESCRIPTION
**Pull request by ddolll**
Increases lasercannon damage to 60, twice that of regular lasers (which was the orignal reason for the damage being 40).

### CODE REVIEW

**Comment by DeityLink** [comment]
Laser Cannons have been kinda underwhelming for years, people always go for AEG instead, so this is a good change in my book.
However note that this might affect the damage of laser shot by the turrets on the old tcomms satellite.

**Comment by Caboozles** [comment]
I think the Tsat turret damage raising isn't a bad thing. They're meant to be hyper lethal.

**Comment by ddolll** [comment]
This will change the Tsat turrets, mech laser cannons, certain 'random projectile' weapons, and some admin spawn only weapons in addition to actual lasercannons.

There are a bunch of places where you get shot by two turrets at once, which with this change will instantly crit you, but there's almost no cases where you'd get hit by turrets where you weren't already fucked (because you're now slowed and can't avoid turrets for whatever reason was in place before) since it's so trivial to not get hit by turrets in the first place.
I don't think it's a change that really matters much tbh.

**Comment by ghost** [comment]
I mean if they still fire slow as shit then nothing really changes so go for it. Maybe laser mechs will be slightly better than bullet mechs with the high damage but we'd have to see, not many people even use combat mechs as is.

**Comment by DamianX** [comment]
something something 3 days something

**Pull request merged**
