### PR TITLE
Add pre-commit git hook system

### PR DESCRIPTION
**Pull request by ComicIronic**
Git hooks are shell scripts that act at certain stages of the git VCS process to help do whatever you feel like, such as auto formatting. This sets up a version-controlled folder for our hooks (tools/git-hooks) and splits the pre-commit hook into a script that loops through a directory, which allows for multiple independent scripts for a single hook.

tl:dr; this is how we're going to be automating formatting standards.

TODO:
- [x] Add batch equivalent of install-hooks

### CODE REVIEW

**Comment by ComicIronic** [comment]
To get the benefit of this, you'll have to make sure you include the `.gitconfig` file manually, which is relatively easy. Just add:

```
[include]
    path = ../.gitconfig
```

to your `.git/config` file.
We can't do this through git itself because that's a security risk.

**Comment by PJB3005** [comment]
See, I told you it can't be done 100% automatically.

Also make a batch file (and sh script) to add that to your git config file.

**Comment by ComicIronic** [comment]
Yeah, I'm not so happy with this solution. The main thing was to have a way to add and remove independent hooks, but with the version upgrade and the issue with .gitconfig, I think I'll just modify the install script and have it copy to .git/hooks anyways. 

It would be nice to have a repo maintained config file people had set up, but it's not a priority.

**Comment by ghost** [comment]
> We can't do this through git itself because that's a security risk.

How?

**Comment by ComicIronic** [comment]
.git folders hold information you're not meant to share. Hooks also allow for arbitrary script execution, so you should really install them manually.

**Comment by ComicIronic** [comment]
Alright, I got rid of the .gitconfig change and instead edited install-hooks.sh to create a script master in the hooks folder that runs all our VCSd hooks from our public folder automatically. A commit will now fail if any of the hooks exit non-0.

**Comment by ComicIronic** [comment]
Unless someone knows enough bash or cares enough, I want to merge this in. It would be useful to be able to set up Python scripts for automatic repo editing.

**Pull request merged**
