### PR TITLE
Falling out of the escape shuttle/pods now has an associated sound

### PR DESCRIPTION
**Pull request by nervere**
## What this does
Mobs being ejected from a shuttle now play a funny sound when they get thrown out.

https://github.com/vgstation-coders/vgstation13/assets/26285377/2129588d-5f3b-4694-8f0c-4483ad3f9e82

## Why it's good

https://www.youtube.com/watch?v=bF1MDtoWHUY
[sound]
## Changelog

:cl:
 * rscadd: Falling out of the escape shuttle/pods now has an associated sound.

### CODE REVIEW

**Comment by Eneocho** [comment]
Requesting for the clown to have a special sound effect and/or someone wearing the mexican outfit to play la cucaracha.

**Comment by pedr69** [comment]
why isn't the sound only being heard by the guy that fell out?
i thought you couldn't hear sounds in space

**Comment by SonixApache** [comment]
silly and out-of-place

**Comment by Hinaichigo** [comment]
For funny round-ends this might work but for round-ends with a serious or intense vibe I don't think it fits.

**Comment by Exxion** [comment]
Very good for April Fools. Bad otherwise.

**Comment by Eneocho** [comment]
A bumping sound for non april fools (guy hits the side of the shuttle or something). The funny sound effect for clowns/clumsy and april fools.

**Comment by calzilla1** [comment]
Even for AF its not that funny. If you want humor it should be a short cut off scream like the one that plays when someone gets deleted

**Comment by Eneocho** [comment]
Play the wilhelm scream

**Comment by Exxion** [comment]
lego yoda

**Comment by nervere** [comment]
I'd rather have this be April Fool's only than closed entirely, but at the same time I'm trying to brainstorm good places for this to be used without it being confined to a single day... I dunno.

**Comment by Eneocho** [comment]
I'm telling you man the wilhelm, yoda and/or tyler1 (admin delete) screams, faded as they get sucked. A wackier sound for clumsy, ALL WACKY during april fools.

**Comment by Kurfursten** [comment]
Lacks support

**Pull request closed without merging**
