### PR TITLE
[MDB Ignore] Christmas Lights ! (DO NOT SQUASH THE COMMITS)

### PR DESCRIPTION
**Pull request by ShiftyRail**
After a bit (a lot) of git fiddling I dusted off Europa Lights and put them on parity with Bleeding-Edge.
This PR will allow us to test them again on the test serb, if we want.

Do note that it doesn't target Bleeding-Edge.

### CODE REVIEW

**Comment by N3X15** [comment]
oh god everything is on fire

**Comment by ShiftyRail** [comment]
>oh god everything is on fire

It's just catching up to 600+ commits, nothing that unusual.

**Comment by ShiftyRail** [comment]
also if you merge this - don't squash the commits

**Comment by Kurfursten** [comment]
Let me just quickly review these infinite files

image

**Comment by Eneocho** [comment]
> Let me just quickly review these infinite files
> 
> image

Just start reviewing the first file in a minute and review each subsequent file in half the time that you reviewed the last. You'll be done in 2 minutes.

**Comment by ShiftyRail** [comment]
Again it's litteraly just copying Bleeding-Edge to Europa lights
With 600+ commits it's normal that it can't cope

**Comment by ShiftyRail** [comment]
All the actual changes are here:
https://github.com/vgstation-coders/vgstation13/pull/31620/commits/8e56bbaaa9b3a90e2e3756f4f520b45906fe96fa

The last commit fixes a TGUI binary (???) conflict that I didn't spot
I have partially reverted https://github.com/vgstation-coders/vgstation13/pull/30755 too because I am not happy with how it looks, can redo it later no probs

**Comment by ghost** [comment]
> > Let me just quickly review these infinite files
> > image
> 
> Just start reviewing the first file in a minute and review each subsequent file in half the time that you reviewed the last. You'll be done in 2 minutes.

it really *tends towards* reviewing being faster with each file.

**Pull request merged**
