### PR TITLE
Ghetto screwdriver

### LINKED ISSUE #22172: Make coins useable as ghetto screwdrivers
'cus it's cool. Maybe make them a lot worse than screwdrivers, like 30 seconds to unfasten a window or something.

<featurerequest>

### PR DESCRIPTION
**Pull request by PaulRitter**
[gameplay][system][tested]

i replaced the macro isscrewdriver with a /obj/item/proc/~can_be_used_as_screwdriver~is_screwdriver(mob/user) with return FALSE

overrid ~can_be_used_as_screwdriver~ is_screwdriver for /obj/item/weapon/screwdriver and /obj/item/weapon/coin, but coin only returns true if on harm intent

fixes #22172

:cl:
 * rscadd: coins can now be used as ghetto screwdrivers
 * rscadd: chocolate coins can now be used as ghetto screwdrivers

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Good lord why not just change the macro

**Comment by jknpj** [comment]
> 
> 
> Good lord why not just change the macro

This can be useful later, i guess.

**Comment by PaulRitter** [comment]
> This can be useful later, i guess.

also the macro didn't give me a way of accessing the user, which i needed for the harm intent check for the coin

**Comment by ShiftyRail** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE We actually talked about it in the d*scord, you can't easily check who the user is simply by changing the macro.

**Comment by Exxion** [comment]
Also this is how it always should have been

**Comment by DamianX** [comment]
I'd prefer the name to be something easier like `is_screwdriver`.

**Comment by PaulRitter** [comment]
yeah you're right, changing it now

**Comment by SonixApache** [comment]
i feel like adjusting isscrewdriver to just check if something is a coin would've been better

**Comment by PaulRitter** [comment]
i said that too, but the discussion ended on this being the better solution. ask exxion idk

**Comment by Exxion** [comment]
As was said above, that wasn't really possible, and this is a better system anyway

**Comment by brndd** [comment]
Does this apply to chocolate coins as well? If yes, please don't change that.

**Comment by PaulRitter** [comment]
no it doesn't, but have you ever tried to turn a screw with chocolate coins? Ah whatever, i'll add it for the memes.

**Comment by Zth--** [comment]
Passing `user` as an argument for a "is_screwdriver" proc is confusing.
Anyways, this is runtiming with monkey recyclers. Monkeys don't have this proc as it is defined at /obj/item/ level.

https://github.com/vgstation-coders/vgstation13/blob/35ea8f380d4d497142dfbba3323fb97a8216acf6/code/game/machinery/machinery.dm#L602

**Comment by Kurfursten** [comment]
why is the monkeyrecycler calling attackby with a mob as the item arg??

**Pull request merged**
