### PR TITLE
Closes #13135

### LINKED ISSUE #13135: virus samples and machines
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
every time the analyzed sample is mutaded the machines adds a "OUTDATED:" to the description if you mutate it multiple times it turns to OUTDATED : OUTDATED : OUTDATED : OUTDATED : GNAv2 based virus lifeform - stamm #5437, #5437

>What you expected to happen
only 1 OUTDATED: added to the desciption

>What actually happened
 OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED: 

>Steps to reproduce if possible
mutate a virus with the machine multiple times

### PR DESCRIPTION
**Pull request by despotate**
closes #13135

didn't test

### CODE REVIEW

**Comment by Probe1** [comment]
Put Closes [link to issue] in the thread OP

**Comment by despotate** [comment]
where

in the body of the PR?

**Comment by Probe1** [comment]
That's it!

**Comment by Probe1** [comment]
NOW TEST IT

**Comment by ghost** [comment]
Tests are for nerds

**Pull request merged**
