### PR TITLE
Fixes cloning from backup using your DNA at time of death instead of DNA at time of backup

### LINKED ISSUE #8102: Cloning Issue (Monkeyism)
(WEB REPORT BY: vonzippenstein REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9cb2cff81bce122c4596573433b45605e3d5e52e
> 
> General description of the issue
> Go in clone pod as a human and come out as a monkey.
> 
> Steps to reproduce if possible
> Take a monkey and copy his SE. Inject his SE into a crew member. Inject a clean SE to re-humanize the monkey. Kill the human and clone it. It comes out a monkey.

This seems to happen independant of the information saved on the cloning machine. One round I had saved my DNA at round start. I monkey'd and humanized myself some time later. And when I died someone cloned me from the backup at the cloning machine and I still came out a monkey.

Lately when I monkey around I try to leave a can of methylin to drink and a clean SE around in medbay to overcome the bug.

### PR DESCRIPTION
**Pull request by Exxion**
Also, in doing so, somehow fixes #8102
I really have no fucking idea why #8102 happened in the first place but this fixes it so whatever

### CODE REVIEW

**Comment by Exxion** [comment]
Wait actually let me check one thing

**Comment by Exxion** [comment]
Alright, yes, this *somehow* fixes it even in the case you get monkeyed and re-humaned *before* you get scanned, even though there's absolutely no reason it should fix that case

Also you apparently pop out as your original appearance now, even if you had a different one when you were scanned
Cloning is truly magical

EDIT: Apparently your brain keeps its original DNA when your body's DNA is altered
I really have no idea whether this is a bug or not

**Comment by Exxion** [comment]
Oh my god that last thing I just said is what caused it in the first fucking place
The brain's DNA is set properly when monkeyized but not when un-monkeyized
So when you get monkeyized and de-monkeyized, your brain still has monkey DNA
And you get cloned from your brain's DNA

I have *no* fucking idea why this didn't happen when scanned after death but whatever

**Comment by Exxion** [comment]
I'm going to look into this some more and potentially fix much of cloning's bullshit at once

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
>your brain still has monkey DNA

Many such cases!

**Comment by Exxion** [comment]
Hey you want to know something *really* weird?
Throughout all my attempts so far, the cloned body ends up either looking like the appearance at death, or the appearance at the time of scanning *except* with the hair color from the appearance at death (but everything else visible is from the scanned appearance)

**Comment by strawberrytan** [comment]
Metaidentifies the barber as the killer

**Comment by Exxion** [comment]
Not actually fixing all of cloning's bullshit at once because some of it may not actually be bugs
As this PR stands right now:
* When cloned, you come out as the appearance dictated by your DNA at the time you were scanned. This is not necessarily the same thing as coming out with the same appearance you had when you were scanned, because not everything that changes your appearance actually changes your DNA. In general, you'll end up with your roundstart name and appearance.
* ~~The above does not apply to your hair color, which for some reason still comes out the same as it was when you died~~ Honestly I can't figure out what determines hair color. Your hair color is randomized the *first* time you monkey and un-monkey, but stays the same all other times, and you come out with that hair color

**Pull request merged**
