### PR TITLE
Obliterates the black market from existence

### PR DESCRIPTION
**Pull request by ghost**
people asked for it

:cl:
 * rscdel: Removed the black market from the game.

### CODE REVIEW

**Comment by 9percents** [comment]
it already collects the dust on bridge like stamps and evidence room
I say we keep it

**Comment by ghost** [comment]
the code will still be in the repository if someone wants to go back and finish it

**Comment by ShiftyRail** [comment]
Technically fixes a few bugs

**Comment by d3athrow** [comment]
how will glass ever recover

**Comment by PrimeDSS13** [comment]
sadly, I don't think he will.

**Comment by KingofHONK** [comment]
holy based

**Comment by Killette2** [comment]
It has potential but I never ever used it.

**Comment by Coxswain-Navigator** [comment]
I think it should remain, even with its current limited item pool it's very useful to those who know how to use it. At least the buying aspect, the selling aspect is pretty much entirely moot to my understanding.

**Comment by ghost** [comment]
> 
> 
> I think it should remain, even with its current limited item pool it's very useful to those who know how to use it. At least the buying aspect, the selling aspect is pretty much entirely moot to my understanding.

This PR was done on a whim based on people bitching about it for months. I think there are good ideas in the black market but they should be taken out individually and implemented into a better-designed system.

**Comment by SonixApache** [comment]
can you just do #24050 instead

**Comment by Kurfursten** [comment]
I would've supported keeping it if Glass was still around because I am a believer in projects that can be refined over time with playtesting, but he is gone and this is derelict.

**Comment by Irradiation** [comment]
In all fairness, if he was still around, he'd be on his #2836127 attempt at coding japanese nanites or other related subject.

**Comment by ShiftyRail** [comment]
3 days rule + huge popular support + Kurf approving it (another collab) = good to merge

**Comment by SonixApache** [comment]
meme collab

**Comment by ShiftyRail** [comment]
@SonixApache ????
explain

**Pull request merged**
