### PR TITLE
pAIs with the chem module can also make Cola and Beer

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
If you have the chem module, you can dispense some cola or beer to your master.
You can already make coffee and tea with the chem module so this isn't out of place.
## Why it's good
You can fulfill the party pAI experience, become the drinks dispenser.

:cl:
 * rscadd: pAIs with the chem module can now make cola and beer as well.

### CODE REVIEW

**Comment by Eneocho** [comment]
Not to be confused with the medicine module, the chem module also makes coffee and tea, so this isn't out of place.

**Comment by MercuriusGH** [comment]
support ALL pAI power creep

**Comment by Servalfang** [comment]
m yes inject the beer directly into my veins mmm

**Comment by Eneocho** [comment]
> m yes inject the beer directly into my veins mmm

The chem module already injects coffee/tea/salt directly into your veins.

**Comment by kilozombie** [comment]
Prepare for unforeseen consequences

**Comment by Kurfursten** [comment]
This is a weird PR. Coffee does have an important role because it can wake you up, but there's really no reason to ever inject beer into your owner. And worse, there's no safeguards against overdosing on beer unlike the prompt for overdosing your host as borer. I could foresee a lot of ahelps from this.

Cola just cools you down. It's harmless but most people will never notice it, unlike coffee with the shakes and fast waking. Still, I get that it's a useful parity for high-heat situations.

Trash the beer and save the admin team from ahelps -- or create a warning prompt to avoid overdoses that destroy livers.

**Review by Kurfursten — CHANGES_REQUESTED** [review]
drinking is bad for you

**Comment by Eneocho** [comment]
You can already overdose with several of the pAI chems, do I really need to remove the beer? I made this PR specifically so you could partypAI, and it ain't no party without beer.

**Comment by Kurfursten** [comment]
Aside from sleep toxin, which is **obviously bad** to give a host if you aren't malicious, what other chem do they have with a real chance of death? Not just headache flavortext or the tiny amount of brute you get from arithrazine.

Beer overdose actually destroys the liver and kills regularly.

**Comment by Eneocho** [comment]
Checking the ethanol OD, in order to reach the "liver death" stage of alcohol consumption, you must've passed well past the dizzy, confused, blurry vision AND passing out ticks, you only start getting liver damage when your user is blackout drunk, and even then, you can quickly purge the stuff in one go with smoke (which yea, might give people around your user 1 or 2u of beer but that's quickly disposed of).
Off the top of my head, bicaridine, antitox and spaceacillin can also be overdosed.
All in all, bicaridine is the only one that can actually legitimately kill, cause, yeah, spaceacilin can kill too, but that's such a small amount of tox for an overdose it is barely noticeable, however, there is a use for bicaridine OD in that it tames IB.
Warning that you are about to OD your user doesn't sit right with me, at least not with a "YOU ARE ABOUT TO OVERDOSE THE GUY" warning. That's a borer feature cause they are literally a pseudo-organ when inside the dude that can taste the blood to check for chems, the pAI just has a generic mediscanner inside (and that's only if they take the medical module), and those do not tell you which chems you have consumed.

**Comment by kilozombie** [comment]
I don't want a pAI to be able to give space beer. Great way to cause a lot of problems.

**Comment by Kurfursten** [comment]
I think this is just going to cause ahelps for very very little payoff. Injecting booze is not nearly as fun as drinking it yourself. In fact, it might be even more fun to let the pAI foodsynth make beer bottles and soda cans.

**Comment by Eneocho** [comment]
I'll yield to the metaclub

**Pull request closed without merging**
