### PR TITLE
Removes remains from cult walls

### LINKED ISSUE #5704: Destroying a cult wall leaves behind remains and blood
why would you give artificers a quality of life change to calm their autism by allowing the conversion of walls and floors they can't stand over but then make it so destroying a wall which is their way of getting about leave behind blood and remains RUINING EVERYTHING
if it's about leaving behind a trail the cult walls and lack of regular wall kind of do that already

can_remains_even_be_removed_without_deleting_them

please no working as intended tag

### PR DESCRIPTION
**Pull request by Zth--**
Fixes #5704 
Readd it with small probabilities when remains are cleanable

### CODE REVIEW

**Comment by Intigracy** [comment]
:+1:

**Comment by DeityLink** [comment]
Zth imo you should have the Artificer's wall spell remove the remain. I like being able to reliably place remains as artificer.

**Comment by Zth--** [comment]
Well I don't think that spawning remains every single time you deconstruct a cult wall is nice... it feels like a bug to me. Also #5714 is working on cleanable remains so I won't touch them. What I can do is make it 50% to spawn remains

**Comment by DeityLink** [comment]
>it feels like a bug to me.
Cult dwells in blood magic. Think of the levels of Doom, or similar games where the walls are made of flesh and bones. In our case there are skulls inside those walls.

**Comment by Zth--** [comment]
Then you should see those remains on the sprite itself. When you deconstruct it, you're literally destroying the wall

**Comment by Arthurdentist** [comment]
Could always give artificers the ability to make remains instead of keeping the convoluted wall method.

**Pull request merged**
