### PR TITLE
Roidstation 1.3 Hotfixes: PANIC BOOGALOO

### PR DESCRIPTION
**Pull request by GeneralVeers25**
:cl:
 * bugfix: Escape Shuttle no longer starts docked to the station. The Bridge has power. Cargo has Status Displays. Other bugfixes.

### CODE REVIEW

**Comment by ghost** [comment]
One more thing just a sec

**Comment by ghost** [comment]
Freezer needs to be on cryo's side of the pump as it heats the gas. 

/obj/machinery/atmospherics/unary/cryo_cell/process()
	..()

	if(stat & NOPOWER)
		on = 0

	if(!node)
		return
	if(!on)
		updateUsrDialog()
		return

	if(occupant)
		if(occupant.stat != 2)
			process_occupant()

	if(air_contents)
		temperature_archived = air_contents.temperature
		heat_gas_contents()
		expel_gas()

	if(abs(temperature_archived-air_contents.temperature) > 1)
		network.update = 1

	updateUsrDialog()
	return 1

**Comment by SonixApache** [comment]
I'll do that seperately since veers is indisposed right now.

**Comment by ghost** [comment]
Cargo lobby apc isn't wired

**Pull request merged**
