### PR TITLE
reworked the crew console to be a holomap

### LINKED ISSUE #5945: List of the problems the crew monitor has
- ~~Z-Level swapping is just screwed, trying it kills the monitor for you. Relog or wait some time for it to work again.~~ The menu to Z-level swap is fucking DISGUSTING, it takes several tries to even punch in the z-level, constantly unfocusing the window.
- Suffocation damage isn't blue on the map screen damage listings.
- People who are dead on the map screen are always listed as being alive when moused-over.
- Positronic Brains always look dead on the map screen.
- Text overlaps occasionally in a clusterfuck on the text screen. DOES actually happen, only with really long names usually Vox, they'll crossover to the health status and no amount of window resizing helps.
- ~~Sometimes while switching over maps between rounds, the previous map will display instead of the one you're currently on. This only happens if you do not disconnect and reconnect between map changes.~~
- Sometimes when switching Z-levels, the crew monitor mixes them up, showing say, the asteroid z-level while showing main station suit sensors.

### PR DESCRIPTION
**Pull request by PaulRitter**
[dnm][qol]

closes #5945

This version of the CMC would feature no more popo-html-frankenstein-ui. Like seriously, the js is a fucking mess. Also this would be way faster and more reliable.

- [x] add icons for every person using suit sensors (duh)
- [x] add a infobox triggered by mouseover
- [x] fix the vox- and syndicate-crewconsole
- [x] use deitys new fancy icons
- [x] textview, use the old one
- [X] z-level switch
- [x] display silicons
- [x] add a freeze-functionality (maybe on infobox open)
- [x] cache things like map and icons
- [x] kick out user if console looses power
- [x] make the tooltip interface a seperate object, so others can use it
- [x] add some background to the map/improve overall visibility
- [x] output tooltip info in chat on iconclick for coords copy-paste and such fun
- [X] implementing the new textview design
- [X] find some bugs to fix
- [x] dead people don't show up on the holomap
- [x] fix the textview forcing focus all the time. dammit byond
- [x] add comments
- [x] multiuser

### Holomap Crew Monitor
- tracks crew and silicon (updates every second)
- if you hover over crew/silicon markers, it gives you a infobox with the damage + their name + job
- won't update positions when infobox is opened
- clicking on a marker will parse that persons info (damage, name, job, pos) in the chatbox
- z-level switch, tracks on all z-levels
- caching of icons, maps and buttons to make it more efficient
- actually not shitty and unstable
- can be disabled while textview is still active

### Textview Crew Monitor
- very lightweight, sends a html doc over browser to the user
- updates with the holomap, so every second
- you can disable/enable updating for the textview
- you can disable/enable the holomap to free up your window

### Useful vars
- holomap_z_levels_unmapped: list which holds all z_levels which should be available for tracking, but shouldn't have a map loaded
- holomap_z_levels_mapped: list which holds all z_levels that should be available for tracking and should have a map rendered
- holomap_filter: can be set to HOLOMAP_FILTER_VOX or HOLOMAP_FILTER_NUKEOPS to show their bases on z_level 2

### Misc
- /obj/abstract/screen/interface/tooltip, an interface that has a tooltip that opens on mouseover

### Things to maybe rework in the same way later
- (Advanced Security Cameras)
- Air alarm
- Bhangmeter

image

image

:cl:
* rscadd: Crew Monitoring Consoles now use the holomap-system

### CODE REVIEW

**Comment by SonixApache** [comment]
Add spaces in your boxes if you want a fancy actual checkbox list you can check off.
```
TODO:
- [x] This is checked off
- [ ] This isn't
```

Though the idea of using the holomaps is REALLY nice, I'm seriously concerned about readability.
Text missing is a pretty big change, and I don't think holomaps really support mouse-over info.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Needs to have text-only still as an option

**Comment by Zth--** [comment]
This solves one of the few problems of playing on linux. :thumbsup:

**Comment by PaulRitter** [comment]
i won't do it as mouseover as there is probably no way for byond to track you mouse position and that sounds really resource-consuming. After some sleep i decided to make an infobox which you can toggle by clicking the person, which then follow the person/icon around. this may change if i can't do it, lets see

**Comment by PaulRitter** [comment]
scratch that, mouseover it is

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It is possible, we already have tooltips for radials and spell icons for example. Whether people would like that though, I don't know, it might be tricky to copypaste their coordinates etc

**Comment by PaulRitter** [comment]
i was thinking of making a "freeze" button or maybe make the interface freeze if you holdclick it

**Comment by Durgen** [comment]
The man who saved very gay station

**Comment by RaccoonBro** [comment]
The map view the crew console has right now is horrible, this would be a welcome change.

**Comment by ValkyrieSkies** [comment]
Fuck holomaps tbh, having the map on its own window makes it much easier to use alongside Telesci or Sec Cameras. Not a fan at all personally.

**Comment by PaulRitter** [comment]
Now ready to merge, unless you got some critique or features you want added

ps: remove [dnm]

**Comment by PaulRitter** [comment]
adding multiuser

**Comment by SonixApache** [comment]
hey while you're on the AIs
what about borgs and mommers
and remoteview / telekinesis

**Comment by PaulRitter** [comment]
borgs and mommers should still go up to the console since they can control it manually like a human

remoteview and telekinesis is another story tho, that might be something for a seperate pr, this one is already very stuffed with features

**Comment by SonixApache** [comment]
👌 
(borgs and mommers could use the CMC from anywhere before though)

**Comment by PaulRitter** [comment]
i mean ok
guess i'll add it

**Comment by PaulRitter** [comment]
merge this, its wanted and needed and works and is tested

**Pull request merged**
