### PR TITLE
Pod Station Tweaks

### PR DESCRIPTION
**Pull request by Optimism333**
## PR Summary ##
I noticed when skimming the logs that some players had been trying to use the cryopod spawner on pod station to spawn in and daringly clear it out or escape. I had quite a few thoughts about this. Mostly I was just surprised players were approaching the vault this way, but why not help them along and facilitate that gameplay?

I made a few tweaks to help those players out. 

podstation

**More Notably:**
- There's now a regular first aid kit in the station restroom.
- There's two ghetto spacesuits and a multitool in the station tool room
- There's a second cryopod at the station that spawns in a safer spot, but the one out in space is still there for players who want a bit more of a challenge
- There's an additional empty high-level power cell in the tool room
- There's now a large stack of metal and a large stack of glass out on the shelves near the parking lot instead of a single glass sheet

Hopefully with these changes it should be easier for cryopod players to clear out the station and make it a home, or leave it behind if they'd rather go looking for the main station. I also don't think these changes will greatly upset the balance of the amount of loot the vault offers.

[vault]  [tweak]

:cl:
 * tweak: Added some helpful survival gear to the pod station vault for cryopod players
 * tweak: Added a second cryopod to the pod station vault, this one is in a safer spot

### CODE REVIEW

**Comment by Kromkar** [comment]
based and emergent gameplay pilled

**Comment by Eneocho** [comment]
Incredibly honked. Could probably use either high level cells (for the pods) or jetpacks (so you can get out of the pod, bodyblock it and change/crank the cell).

**Comment by Optimism333** [comment]
> Incredibly honked. Could probably use either high level cells (for the pods) or jetpacks (so you can get out of the pod, bodyblock it and change/crank the cell).

There's already an empty high-level cell in the tool room, but I'll add another one.

**Comment by Eneocho** [comment]
I meant super cells or ultra cells. High cells run out real fast when spacepodding.

**Comment by Optimism333** [comment]
> I meant super cells or ultra cells. High cells run out real fast when spacepodding.

How fast is real fast? Even if that is so, the hand crank should allow someone to get places in a pod beyond the life of one high-capacity cell.

I'm not really sure on this one. I'll consider it if someone else also thinks the two high capacity cells won't be enough.

**Comment by Eneocho** [comment]
Just tested. For space exploring (the main reason to use pods normally) they last around 4-6 minutes of constant use which sounds like a lot but you need to do a ton of back and forth to find vaults (In my 2 test rounds I didn't find a vault despite emptying a cell each time).

**Comment by Optimism333** [comment]
> Just tested. For space exploring (the main reason to use pods normally) they last around 4-6 minutes of constant use which sounds like a lot but you need to do a ton of back and forth to find vaults (In my 2 test rounds I didn't find a vault despite emptying a cell each time).

Fair, and I appreciate that you were willing to test it to give me feedback. However, given what you told me I think that the high capacity cells will be fine enough when paired with the crank charger in the tool room. If it becomes an issue with multiple players I'll reconsider.

**Comment by Eneocho** [comment]
Guess that works.

**Comment by ManopolisJones** [comment]
If you put a breath mask next to the red canister outside and maybe a space blanket, you reckon a suitless pod baby could survive the outside spawn without falling unconscious and suffocating?

**Comment by Optimism333** [comment]
> If you put a breath mask next to the red canister outside and maybe a space blanket, you reckon a suitless pod baby could survive the outside spawn without falling unconscious and suffocating?

There already is a way to survive the outside spawn. Don't keep reading if you want to figure it out yourself, but here's how it goes...

There's an emergency inflatable shelter just two tiles away, so if you're quick you can pop out of the pod, inflate it, and jump in. Even without internals you can jump out and in in little intervals while pulling the shelter to get to the station. There's also a crowbar in the red toolbox nearby so you can force open the airlocks.

But for anyone who doesn't want to go through that trouble, there's the one inside. And if the other pod man is a good samaritan, he can pull the outside one in so that the next poddie can spawn in safely.

**Pull request merged**
