### PR TITLE
fixes #7333

### LINKED ISSUE #7333: Nazi Coat German doesn't translate
That's Soldier's Coat. It is a normal-sized item.
Ein Mantel gemacht, um die VerbÃ¼ndeten zu zerstÃ¶ren.

Real minor shit.

/obj/item/clothing/suit/soldiercoat

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #7333

The previous one was showing up as messed up when I opened DM even, but it's not showing that way on the diff.

This one is showing up fine in DM.

### CODE REVIEW

**Comment by BestName** [comment]
You sure "ß" will show up properly in-game with non-german locale?

**Comment by Intigracy** [comment]
ja

ja

**Comment by ihadtoregisterforthis** [comment]
But this is not a fix, this is evading the problem

**Comment by Intigracy** [comment]
We can't fix byond not accepting all unicode, dummkopf.

We can change it to still be fitting the nazi german theme however.

https://www.youtube.com/watch?v=u1sEt3NjHNA

**Comment by BestName** [comment]
Well none of us are BYOND devs so none us can fix it.

**Comment by Exxion** [comment]
When you can't fix the underlying problem, getting around it _is_ a fix

**Comment by ihadtoregisterforthis** [comment]
I would call the phonetical rewrite on the comments a fix, this is more of a roundabout route.

**Comment by Intigracy** [comment]
Why intentionally misspell german words when we can reference a catchy nazi marching tune?

**Comment by PJB3005** [comment]
I think you can write ö as oe in German.

**Comment by Intigracy** [comment]
b-but muh sick references

**Comment by clusterfack** [comment]
Goon chat when! It can probably do unicode somehow

**Comment by Intigracy** [comment]
WYCI :^)

**Comment by clusterfack** [comment]
Yeah maybe if I get some HUGE thing I need to procrastinate on for a week

**Pull request merged**
