### PR TITLE
Icon optimization woo

### PR DESCRIPTION
**Pull request by gbasood**
This is just optiPNG applied to icons in the repo, including a script to do it all over again.
Reduces icon folder size from 40 MB to 34 MB.
Most of that filesize is from lobby screen GIFs, which I can't optimize anyway

### CODE REVIEW

**Comment by ghost** [comment]
Only 6MB saved?

**Comment by gbasood** [comment]
6MB over 50-70 players is kinda important
Still, the main culprit is those loadscreen gifs

So really it looks like 20% chopped off the .dmi file sizes total

**Comment by gbasood** [comment]
Well this is weird
I can't add the tools because they're in the tools folder and `git add tools/ -f` doesn't work
And there's conflicts on things I can't find, rebasing doesn't reveal them

**Comment by ghost** [comment]
Are you sure you're rebasing up to date?

**Comment by gbasood** [comment]
For some reason smartgit wasn't actually fetching changes. Re-pushing shortly

**Comment by 9600bauds** [comment]
Excellent

**Comment by clusterfack** [comment]
Isn't it possible to host those loading screens externally and have them load up once the game starts?

**Comment by clusterfack** [comment]
Also as this overwrites any file and will conflicts with everything be reeeeally sure please

**Comment by gbasood** [comment]
@clusterfack I loaded up the game and everything displays just fine, including animations
External loading screens would have to be done via HTML/JS to be loaded externally without bogging down server in order to send the image

**Comment by ihadtoregisterforthis** [comment]
Try it on a secondary server then, can't take chances

**Comment by gbasood** [comment]
I mean we can though
That's the beauty of version control, if something about this fucks up it can always be reverted.

**Comment by gbasood** [comment]
Alternatively, I can just port the tools and we can leave icons as-is for now if you feel the number of changes are too heavy

**Comment by FudgePucker** [comment]
Maybe just have one splash screen per update.
That way it still changes enough to not be stale, but you have to download less resources.

**Comment by clusterfack** [comment]
You would also have to download resources EVERY time @FudgePucker, the best solution is to have them loaded off somewhere and download them when the game starts. I mean hell we see goon has some CDN that does the same thing I believe.

**Comment by FudgePucker** [comment]
Well that would also probably work.
I mean if it needs to redownload resources anyways, it would swap out the splash screen with another one in rotation.

So if a pullrequest gets merged and the roundends and new version compiles, it would swap out the splash screen for another one.
If this is even possible.
EDIT: Another idea, just have one splash screen then rotate it out every week or so manually.

**Comment by clusterfack** [comment]
@FudgePucker It only redownloads resources when you change the .rsc (sprites), to my knowledge.

**Comment by PJB3005** [comment]
@FudgePucker yes it's possible but it would cause way more bandwidth usage because clients would need to constantly redownload the RSC.

**Comment by gbasood** [comment]
preload_rsc can be set to a URL to load RSC files from
but if the RSC file doesn't change names, the client will never retrieve it more than once, EVEN THROUGH UPDATES, unless the name changes

**Comment by clusterfack** [comment]
@gbasood That's how preload_rsc works, in theory, but I don't believe it works at all even right now

**Comment by clusterfack** [comment]
Unless at some point this is 'done', its just going to be a continually conflict generator for you

**Comment by gbasood** [comment]
Problem is I don't know what you guys want me to do for it to be 'done'.
I can just implement the tools and we can keep on not using them until we've got all the PRs that would mess with icons closed?

**Comment by ghost** [comment]
Make it do it at the same time as changelogs are made nerd

**Comment by gbasood** [comment]
@DrCelt then we'd end up with conflicts regardless
Sometimes an icon can go through optimization twice, with a different result, but with overall size basically unaffected.
This is a tool best used by a human, not automation

**Comment by ghost** [comment]
How silly

**Comment by ihadtoregisterforthis** [comment]
Gib tools plox

**Comment by gbasood** [comment]
Alright, this should be JUST the tools now.
Won't be so useful for single-icon optimization as is though
Although the way the script works, I **THINK** that if you're cd'd into a directory, it'll only optimize icons within that directory and deeper.

**Pull request merged**
