### PR TITLE
More noticable binary chat

### LINKED ISSUE #9434: Robotic Chat and Instances of "Borg"
While I'm here I might as well bring this up as I've always wanted to. Can we get some other colour for robotic chat besides black that's simply put in italics? It's easily lost under a swarm of chat and actions, at least I find (maybe I'm just bad), and I miss the AI kindly informing me about important things.

Also would be neat if sentences with borg in them were some how highlighted for a borg player, but I'm not sure how possibly this is.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #9434

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Don't use AI's pink. Font sounds right.
I dare suggest making medical a bit greener

Otherwise I don't think the color purple is being used in chat other than for sinister messages.

**Comment by clusterfack** [comment]
I already use a color just like that for ancient chat

**Comment by CptWad** [comment]
When will a sillicon use .y ever?

**Comment by Exxion** [comment]
Only MoMMIs even _could_ see ancient communication

**Comment by clusterfack** [comment]
What

**Comment by Exxion** [comment]
You need to have the crystal somewhere in your inventory (or within an item in your inventory) to see ancient communication

**Comment by Intigracy** [comment]
I'll fix it later smh.
What even is ancient chat?

Also humans can see binary at points so it can't clash with their channels either.

**Comment by clusterfack** [comment]
Its my super secret artifact of funtimes

**Comment by Exxion** [comment]
> super secret

It's a rare xenoarch find
You get six pretty bluish crystals which act as uninterruptible, rangeless walkie-talkies.
Anyone with one anywhere on their person can hear Ancient Communication and talk over it with :y

**Comment by clusterfack** [comment]
SPOILERS REEEEE

**Comment by PJB3005** [comment]
It's also the only feature clusterfack ever coded.

**Comment by clusterfack** [comment]
Not only is that wrong, its pretty rude

**Comment by PJB3005** [comment]
Alright one of the only ones.

**Comment by clusterfack** [comment]
Still pretty rude

**Comment by ihadtoregisterforthis** [comment]
It's a feature that Cluster did once and it's good.

**Comment by Intigracy** [comment]
Doot doot here's an updoot.

I made it slightly bigger because having binary should make it your number 1 focus tbh. Even (ESPECIALLY) as a human with a binary key.

**Comment by nuklearcellphoneg** [comment]
Apply this to whenever someone says your name too? :3

**Comment by Exxion** [comment]
You can already do that with Goonchat
It's in the options menu

**Comment by nuklearcellphoneg** [comment]
Wow what a time to be alive

**Comment by SangriaMonkey** [comment]
Courier is a heinously ugly font.

**Pull request merged**
