### PR TITLE
Vox specific Dexalin.

### PR DESCRIPTION
**Pull request by Eneocho**
Vox specific Dexalin, even though I don't main Vox. 
Jury rigged, for I've never done this before.

Voxalin is mildly toxic to non Vox, Dexalin is toxic to Vox. Plus versions are appropriately more toxic.

I know an idea like this was made before in https://github.com/vgstation-coders/vgstation13/pull/5447; but half a decade has passed, people have come and gone, maybe give it a second thought?

### CODE REVIEW

**Comment by ShiftyRail** [comment]
>emojing your own PR

**Comment by DamianX** [comment]
I don't hate nor love the idea but I don't see it as a worthwhile addition as things stand right now. I will elaborate as soon as any argument in favor of this PR is made by anyone.

**Comment by chesse20** [comment]
this will lead to both vox complaining about cyro taking longer to fully heal due to toxin damage being given to them in the mix, and vox medical players putting voxalin in the cryo and then everyone else complaining about cyro taking longer and having to take toxins damage.

-vox main who plays cmo often and will put voxalin in the cryo mix

**Comment by gurfan** [comment]
I support this because I intend to never make voxalin.

**Comment by JevilUndertale** [comment]
Most cryos don't even use Dexalin+ (since it's not really necessary at all), so I don't see that being a big problem. I think this fits nicely with the whole snowflakey-ness that Vox have.

**Comment by Gazathor** [comment]
yes yes cousin today we sell poison dexalin to crew

**Comment by Eneocho** [comment]
What if when dexalin and voxalin mix, they created Cryolin? An all Species Dexalin that only worked on cryogenic conditions?

**Comment by Dacendeth** [comment]
I dont like this unless you add voxalin kits and make them guaranteed in the n2 lockers.

**Comment by DamianX** [comment]
The thumbs spoke

**Pull request closed without merging**
