### PR TITLE
Increases Engineering and CE RIG suit rad protection to 100%.

### PR DESCRIPTION
**Pull request by Reviire**
So, people want to reduce the gap between MoMMIs and engineers, that's cool. But, I really think this is where we should be starting. Radiation protection doesn't exist below 100%, it's still very likely you will straight up die spending any amount of time near a shard as an engineer, which really makes their job harder when dealing with a shard. Unlike a MoMMI, which just vent crawls inside and fixes whatever needs fixing.

So, this increases the radiation protection of the engineering and CE RIG suits to 100%. Not the atmos suit or any other suit. I think it's a fair change considering you'll just die with less than 100%, and if you wear a rad suit, the -250 degree temps and 5kPa will kill you instead. If you fix the atmosphere the shard explodes. 

The random commits that exist because I didn't know how to github annoy me. 

:cl:
 * rsctweak: Increases radiation protection of engineering and CE RIG suits to 100%.

### CODE REVIEW

**Comment by DamianX** [comment]
Radiation is too strong but powercreeping engineering hardsuits further is not a direction I like.
See #17191 for more discussion

**Comment by jknpj** [comment]
Xenoarchs can't abuse it as easily as engineers as they don't start with foam extinguishers and a shard

**Comment by Reviire** [comment]
At best I'm looking at this as a temporary fix, something we could revert when radiation is toned down to more reasonable levels. But I don't really wanna touch radcode.

But something needs to be done at least until the point we fix it entirely. Engineers just die if they go near an active shard.

I dunno, should I instead try to fuck with rad code so it doesn't destroy things that have high rad resistance?

**Comment by DrSnips** [comment]
This change will buff the ability for people (who are likely antags) to drag the shard around station and rad blast people. A part of the balance of this is that rad suits dont have the pressure resistance and such like hardsuits do. Making it so you could only radblast people for as long as you survive that areas atmos.
Silicons and carbons have defined roles. One of silicon's roles is shard removal if things go south.

**Comment by Reviire** [comment]
Well, after discussing it with others I think It'd be a better idea to solve this issue in other ways, namely, adding a way to quickly power down the shard for engineers. Which would in no way touch rad/hallway shard balance.

**Pull request closed without merging**
