### PR TITLE
credits mute button

### PR DESCRIPTION
**Pull request by robintime**
for when you don't feel like curbing your enthusiasm

:cl:
 * rscadd: adds a mute button to the lower left corner of the credits

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Give it a way to save settings on a per-client basis, unless that's already handled, otherwise you'd have to uncurb your enthusiasm every time the credits roll unless you just mute it via the credit sounds settings

**Comment by PrimeDSS13** [comment]
loss of culture
/vg/ is done for

**Comment by robintime** [comment]
> Give it a way to save settings on a per-client basis, unless that's already handled, otherwise you'd have to uncurb your enthusiasm every time the credits roll

if you want to be enthusiastic you have to work for it barry. click the button every time like a man or toggle it off in the settings like a coward

**Comment by gurfan** [comment]
make it list the people who mute it in ooc

**Pull request merged**
