### PR TITLE
Ninja energy katanas can't be hooked into eachother to make dual energy swords anymore

### PR DESCRIPTION
**Pull request by SonixApache**
0% tested, shouldn't break anything but if it does whatever

🆑 
 - rscdel: You can't make dual energy swords out of e-katanas anymore

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
@Hoshi-chan I WILL INSULT YOU IN A LIGHT AND NON-SERIOUS WAY, WHY DID YOU HAVE TO GIVE AWAY THE SECRETS OF THE METACLUB

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Everyone knew that one already we're just too lazy

**Comment by FudgePucker** [comment]
At least make it so you can combine the katanas to get duel welded katanas. Avenge your fallen brother and become death.

**Comment by boy2mantwicethefam** [comment]
I was thinking the same thing, but what should it be? Are there any dual katanas?

**Comment by SonixApache** [comment]
We don't currently have any code for dualwielding melee weapons, but if you can come up with something I can try it.

This is the simple (((bugfix))), actual content can replace it later.

**Comment by Hoshi-chan** [comment]
If you want to make it a feature instead of feature loss, make it so that combining two energy katanas gives you a daikatana. Wielded with both hands on activation. Can only be wielded by ninjas, like the regular energy katana.

**Review by jknpj — CHANGES_REQUESTED** [review]
>returning attackby

The absolute madman. Make a new unmergeable var and check against it or something, but not this.

**Comment by SonixApache** [comment]
alright, figured this was too easy to work

**Comment by Kurfursten** [comment]
you don't even need a special var, just 

```
if(istype(W,energykatanapath))
 return
else
 return ..()
```
and preferably with a fail message

**Comment by jknpj** [comment]
muh modularity

**Comment by ghost** [comment]
Closes: #22539

**Pull request merged**
