### PR TITLE
Kippahs

### LINKED ISSUE #34443: [feature request] yamulka / kippah
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
c1c561edb494069dde7de3b81bcc5e5f0f20e722

# Description
Hat for jews

### PR DESCRIPTION
**Pull request by RealestEstate**
Adds ~~yamalkas~~. ~~4~~ 5 different colors, stocked in the chaplain vendor, which are chosen at random when one is dispensed. 
Rabbis come equipped with a kippah.

yamalkas

Resolves #34443.
[content][sprites]

:cl:
 * rscadd: Adds kippahs. Rabbis start with one of five different colored kippahs, and the chapel vend dispences 5 more.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
You should add a simple black one as well. Jewish men wear kippa durint a variety of occasions like in synagogue and when sitting shiva

**Comment by DeityLink** [comment]
Most ones I see in the street are plain black yeah.

**Comment by sushi-vomit** [comment]
'Yamalka' is a strange thing to name it.
You could go Kippah for proper Hebrew name, or Yarmulke if you want Yiddish, but I don't believe I've ever seen it spelled 'Yamalka".

**Comment by DeityLink** [comment]
and yeah those are also mostly known as kippahs to my knowledge.

**Comment by RealestEstate** [comment]
Ok will namechange and make a simple black variant. Dnm until then

**Comment by Kurfursten** [comment]
confl

**Comment by Theophrastus1** [comment]
can't wait to superglue these to schlomo's head every round

**Comment by RealestEstate** [comment]
did... did I fuck up the rebase?

...ok I guess not

**Comment by RealestEstate** [comment]
Ready for merge

**Comment by Kurfursten** [comment]
I checked, you merged perfectly, no issues

**Pull request merged**
