### PR TITLE
Blob now gibs corpses

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Discuss something to balance this with
Thinking of removing the reduced brute damage so even crewmembers can start bashing the blob instead of just lasers and trying your luck with limited welders
:cl:
 * tweak: Blob now gibs corpses, so drag your friends away!

### CODE REVIEW

**Comment by SonixApache** [comment]
👎 shit change and low-effort to boot

**Comment by GoodG1448** [comment]
What happens if the nuclear disk carrier gets gibbed?. The backpack/container gets left behind or the disk teleports somewhere else?

**Comment by boy2mantwicethefam** [comment]
Supposedly any items left on the floor are destroyed and if gibbing makes the person drop the items it will eat the items, nuke disk always gets teleported when it's destroyed and blob destroys it

**Comment by Arthurdentist** [comment]
this just makes it harder to recover if the blob is defeated; I don't really see the point in this change other then making things more tedious.

**Comment by boy2mantwicethefam** [comment]
Also by the way this PR SHOULDN'T be merged until something is discussed to balance this

**Comment by ShiftyRail** [comment]
This isn't a game of checks & balances where you automatically make X acceptable by giving Y as a compromise
It shouldn't be, anyways.

You should motivate this change on its own.

**Comment by Blithering** [comment]
The bodies are usually buried under the blob anyway, so the only time they'll be recovered is when a blob is beaten back.

**Comment by Arthurdentist** [comment]
@Blithering if the blob has been beaten back, then what is the point in making the crew tediously put heads back onto bodies (if the heads even remain mind you, cause that is by no means guaranteed). This is just a bad no-fun change.

**Comment by Blithering** [comment]
I was arguing against it, people who have been overwhelmed by blobs tend to stay dead unless they can limp away or get uncovered later down the line as it is.

**Pull request closed without merging**
