### PR TITLE
Possible fix for slimes making people glide across the ground until punched and also fixes MoMMI parking brakes in a non-atomic way

### LINKED ISSUE #7763: Mommi's with the parking break on can get out of flashes
I tried to flash a mommi but it could still move, after much effort and repeated (failing) flashes I managed to emag it
It told me that its parking break would let it out of flashes
I saw the parking break lights on the mommi so I imagine it DOES work like that
would require two people to test properly

### PR DESCRIPTION
**Pull request by 9600bauds**
I don't know what this is but I know it's shit and it absolutely should not be like this

Maybe a fix for #7021 but I don't know
fixes #7763

### CODE REVIEW

**Comment by clusterfack** [comment]
I saw the same proc and was going to change it when I had free time, but there are lots of canmove edits there if you really want to fix it you need to kinda fix all of them

**Comment by 9600bauds** [comment]
I grepped for canmove edits and they seemed to all be either for simple mobs, for stuff like ventcrawling/climbing in-out of a mech, or transform procs
I looked through all the cases and this one seemed to be the only blatantly wrong one, I'm guessing the rest have their reasons to be there since I've never heard of people gliding across the ground after getting out of a mech

**Comment by ghost** [comment]
Vampires do the same thing.

**Comment by CptWad** [comment]
Its clone damage disabling a leg from what I have heard. Its the same thing as people who spawn in with 1 leg or no leg. They crawl when people who do it with legs that still _exist_ meaning they are crawling at their regular run speed

**Comment by 9600bauds** [comment]
Actually I'm pretty sure something like this is the cause for #7763

**Comment by 9600bauds** [comment]
Can't find a canmove edit for vampires, what the fuck

**Comment by 9600bauds** [comment]
There, fixes #7763
No clue about vampires though

**Comment by Exxion** [comment]
Slimes making people crawl happens because they clone damage the legs. Self-punching at this point doesn't fix it. It's only after they get fixed by cryo that they speedcrawl and can punch themselves to fix it.
I _think_ it has to do with _healing_ clone damage

**Comment by CptWad** [comment]
The punch is post-healing the damage, guess it just tells the game that the limb is healed and they should be standing now

**Comment by Imagebard** [comment]
Alternatively, the punch rolled for the knockdown/stun chance and hit.

**Comment by 9600bauds** [comment]
Insidious NFD

**Comment by 9600bauds** [comment]
Self-merging is a sin and I'm already going to hell.

**Pull request merged**
