### PR TITLE
Alt+Click Rotate on Engineering Machinery

### PR DESCRIPTION
**Pull request by DorainGrey**
## What this does
Allows you to rotate, Emitters, Shield Capacitors, Prisms, PA Machinery, gyrotrons and fuel injectors with ALT+Click instead of the verb.

## Why it's good
Makes the game less mouse heavy.

## Changelog

:cl:
 * tweak: Can now rotate Emitters, Shield Capacitors, Prisms, PA Machinery, gyrotrons and fuel injectors with ALT+Click

### CODE REVIEW

**Comment by Eneocho** [comment]
Speedmerge now

**Comment by BomberBro** [comment]
This bullshit had a long time coming

**Comment by kernikov** [comment]
Add gyrotrons and fuel injectors as well please.

**Comment by Eneocho** [comment]
Dear god yeah, gyros and injectors too.

**Comment by DorainGrey** [comment]
> Add gyrotrons and fuel injectors as well please.

Done.

**Pull request merged**
