### PR TITLE
Outpost fixes

### PR DESCRIPTION
**Pull request by Angelite191**
>Polished up the research station a bit, fixing the conveyor belts.
>Fixed the mining station's conveyor belts >implying anyone uses those
>Removed the blatantly unneeded O2 lockers in the research outpost airlock system
>added an ACTUAL STACK OF GLASS AND METAL for usage in the emergency storage room in the research outpost.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Images.
You can also make lists on Github using -.

**Comment by Angelite191** [comment]
Lists are for NERDS! Do I look like a nerd!?

outpost changes 3
outpost changes 2
outpost changes 1

**Comment by Angelite191** [comment]
I don't know how I got the merge conflicts, please sent all the helps.

**Comment by ComicIronic** [comment]
The conflicts likely come from your changelog file.
This is why you use PR files instead of having a general one.

**Comment by Angelite191** [comment]
I've been using the same file I always have. The YML file. I just didn't make this one before the PR. Is it really that big an issue?

**Comment by Angelite191** [comment]
HOW DO I FIX IT!?

**Comment by Angelite191** [comment]
I MADE IT WORSE!

**Comment by clusterfack** [comment]
Hahaha if you used the most recent version of bleeding edge pomf had a compile error still in there.

**Pull request closed without merging**
