### PR TITLE
Limb gibbing

### PR DESCRIPTION
**Pull request by unid15**
Massive blunt damage may now cause a limb to be gibbed, instead of being torn off. Gibbed limbs are fully destroyed, creating a bloody mess on the floor. Gibbed heads leave a brain. 
A limb has to be at its maximum damage threshold to be gibbed, same rules as for being torn off

Damage / limbgib chance table:
<16 - 0%
16 dmg - 8%
22 dmg - 27%
30 dmg - 64%
\>34 - 100%

:cl:
 * rscadd: Large amounts of blunt brute damage (16 and more) will gib limbs, instead of severing them. Gibbed limbs are destroyed, but heads still leave an intact brain.

### CODE REVIEW

**Comment by SkowronX** [comment]
There better be a webm demonstrating buckshot sploding a head.

**Comment by unid15** [comment]
there's also a sound
i think i might improve the visuals a bit by sending the gibs and the brain flying

**Comment by SkowronX** [comment]
Needs extra little skull chunks flying around

**Comment by unid15** [comment]
no sprites for that unfortunately, but i made it create moving gibs



this doesn't only work with guns, but with any blunt weapon with 15 force or higher (details in the PR body). magboot stomping just became a lot cooler

**Comment by ghost** [comment]
Seems a little lame that I can't cut limbs off with fireaxes, but weak guns still mysteriously sever

**Comment by unid15** [comment]
There's some concern regarding head gibbing - the brains slowly die when outside of a head, so if you headgib somebody without a cloning backup and their brain isn't saved in time, it's pretty much permadeath to them
Thoughts on that? It's a bit of a complicated issue to fix because it'll affect game balance

**Comment by Lokiamis** [comment]
teensier brain icon when

**Comment by Sooose** [comment]
All I need to pop out a brain is a toolbox now? I see a lot more people getting removed from the round permanently.

**Comment by unid15** [comment]
It'll take about 12 hits on average to gib a head with a 15 force toolbox, assuming the head is already at maximum damage (which I think is around 100). From 100% HP, that's 19 hits. If you have the time and space to do that, then you probably already have the means to remove them from the round in some other way, like by chopping their head off and spacing it, IMHO

**Comment by Pathid** [comment]
I feel like having the premeditation to get a sharp object and also carry the head somewhere to space it is a good filter though. Now it will just be whack, whack, whack, -> leave the brain to die after several minutes because chances are nobody's gonna come and stick it in a freezer.

**Comment by unid15** [comment]
Or I could raise the damage threshold to something like 30, so that you'll have to find some actual weapon for limbgib instaed of using a toolbox

**Comment by DamianX** [comment]
Raising the threshold sounds good, what are the most accessible 30+ damage weapons, to get an idea?

**Comment by Lokiamis** [comment]
>I see a lot more people getting removed from the round permanently

Good

**Comment by unid15** [comment]
>what are the most accessible 30+ damage weapons, to get an idea?

Magboot stomps and bullets, can't think of anything else. Maybe unarmed attacks if under enough buffs (knukcledusters, hulk, tajaran hands etc)

**Comment by DamianX** [comment]
Does the wiki really need to be updated for this? Where?

**Comment by jknpj** [comment]
Guetto Surgery/Speedborging

**Comment by unid15** [comment]
Gonna update when it's merged

**Comment by yackemflam** [comment]
Doesnt buckshot only deal 15 damage per shot?

**Comment by unid15** [comment]
16 or more damage now, so toolboxes are excluded

**Comment by yackemflam** [comment]
Found out how much damage a buckshot shot does.
It 10 brute per shot. And every shell makes 9 shots.

**Comment by ghost** [comment]
If this gets merged, someone better make the Lawgiver [proc explode on a DNA mismatch.](https://www.youtube.com/watch?v=9YO8_lLLcJM)

**Pull request merged**
