### PR TITLE
Increases EMP stun to 20-24 seconds for strong EMP and 10-14 for weak EMP.

### PR DESCRIPTION
**Pull request by Sailol**
As the description says, it increases the stun that borgs recive when they get hit with an EMP to 10-12 for the strong part of the wave and to 5-7 for the weak part of the wave.
My reasoning for the change is as follows:

* EMP is a rare damage type whose sources are more often than not wasted after one shot, i.e granades, supermatter, admin intervention, etc. Hence, I belive it's nonsensical that a weapon that can be recharged over and over again, and is furthermore common such as the stun batton to do more stun damage than an EMP, even to a squishy carbon
* RP-wise I do not find any sense on flashes and flashbangs doing more to disable a borg than an electrical overload, considering that one only overloads the sensors on the borg and the other overloads the sensors, the servos, the components, basically everything that has circuitry on it.

I understand fully that borgs need to be stronger than carbons, and that a competent crew can stop a machine rebellion, but this fix is mostly for the other users of EMPs, chiefly traitors, raiders, and wizards.
Considering that traitors do not necesarilly have acces to the console nor do they always have acces to flashes (which, if you are not security or robotics, already implies stealing the one on the checkpoint, and you are not the only traitor and/or graytider around), they need some way to fight borgs with lawsets that allow them to kill the antag in question (all of the default lawsets allow for the birds to get valided by borgs).
Oh, and don't forget that EMPs burns flashes up.
In essence, I belive an increase in stun time allows for someone to either better gauge the situation and consider retreat if overwhelemed by borgs or wreck a managable number without wasting a lot of granades or shots on their ions, both of which will be on short supply in a prolonged fight.

I am ready to get memed now.
EDIT:
Due to a github bug, I couldn't edit my old PR, I made this new one.
I discussed things with Probe, and I've lowered the EMP from my old one, because 30 secs of stun was a bit too radical. 20 seconds is a stun batton stun, so I've compromised to a 20-24 seconds stun.
:cl:
* tweak: Changed EMP stun to borgs to 10-12for strong EMP, 5-7 for weak EMP.

### CODE REVIEW

**Comment by jakmak3** [comment]
For the love of god we need SOMETHING to make the anti borg weapons actually be effective against borgs. ion grenades are total trash and i once saw someone dump a full emp rifle into a sec borg which stood still for 8 seconds until it woke up and continued as if nothing happened

**Review by PJB3005 — APPROVED** [review]

**Comment by Probe1** [comment]
@jakmak3 you dont shoot someone with a taser 8 times then bitch they aren't dead.

you shoot them once then beat them for a while then shoot them again.

**Comment by Ephx1** [comment]
Ion -> Flash smash
Borgs can't do anything against this and die as quick, if not quicker, than a human.
Even if you somehow _didn't_ kill it, there's a big chance you've already knocked out the cell and it's basically dead anyways, or is blind and can't do anything.

**Comment by Exxion** [comment]
Yeah but ion rifles aren't tasers

**Comment by Probe1** [comment]
They really are.  They stun for as long.  They also do damage.  They're better than tasers.

**Comment by Sailol** [comment]
Problem with borgs is that ions are uncommon, sendomly thrown, and you need another weapon to beat the borgs with it, and all borgs have a stun integretaed on them.

**Comment by Exxion** [comment]
Ion rifles SHOULD be better than tasers, considering you CAN'T FUCKING PUT THEM IN BACKPACKS

**Comment by Ephx1** [comment]
A stun that's bypassed by mucking about in maintenance for a few seconds. The few you could argue having real stuns are janitor and secbot.
As I said before, make ions more common and buff those shit grenades.
Also, I'm totally behind allowing ion guns in backpacks.

**Comment by 9600bauds** [comment]
We need an ion gun that's not a rifle

**Comment by aceedex** [comment]
There was an ion pistol PR a while back that had the right idea. Salvage that

**Comment by jakmak3** [comment]
Ok how about this. As we all know ions are in a weird place. 

They are intended to be a anti mechanical weapon (borgs and mechs) which also cause havoc for electrical systems and energy based weapons (radios, draining energy weapons, causes firelocks and doors to flip out). When fighting mechs they preform amazingly well and when going up against anyone with any mechanical organs or limbs cause the person with said organs that was effected to immediately keel over. They also are good for inhibiting people relying on electronics (radios and energy weaponry ) by disabling them and draining their battery. 

The cost for this equipment is either for ion rifles having a ultra rare found in 3 places in the game item (security armory, vox skipjack, and nuke ops ship) which is also the size of a shotgun rendering it impossible to fit in a backpack and also being a ultra noticeable and highly conspicuous weapon

For the ion grenades some also rare items achievable either by
 A: meta knowledge of the one on the derelict, 
 B: deficiencies armory,
 C: the nuke op/raider ship, or 
 D: spending your limited traitor telecrystals on buying some from your uplink.
 The grenade itself being a 1 use non rechargeable and highly recognizable weapon which gives off a single EMP blast.

Both of these items being rare, exotic, and very noticeable make them hard to come by. When going up against carbons and mechs it preforms amazingly by being able to disable radios, drain weapon charge, and outright deal massive damage to mechs. 

However when used on silicons do a very very minimal effect of a slight bit of damage and a stun roughly shorter than a tazers stun. The effect of this is so unnoticeable that i have seen cyborgs eat a full ion rifle charge and as soon as their 8 second stun wore off they immediately resumed their murdering as if nothing happened. Being able to practically 1 hit someone with a mechanical limb but not being able to even wound a cyborg is clearly unbalanced.

Along with this change what if also EMP rifles were swapped with EMP guns round start which fit in backpacks and maintained the same stats they have now. More EMP rifles would be able to be purchased by cargo and adding the EMP rifle with double the battery and the same size as a shotgun being added to R&D for the price of minerals to balance it out. Also to not leave ion grenades in the dust what if they emit several EMP blasts at once to cause maximum havoc.

Overall we need to look at the current state of ion weaponry and consider reworking the ways ion weapons work while also making them more common.

Not to mention that EMP pistol idea aint half bad.

**Comment by Probe1** [comment]
http://ss13.moe/index.php/poll/80

**Comment by Ephx1** [comment]
I mean, all that means now is Ions are targeted even harder than before. Good luck with science saving you, or if cargo even exists.

**Comment by Probe1** [comment]
Comic no.

**Comment by jakmak3** [comment]
Let it be known that i still stand by my original EMP buff and that even it was not strong enough to be balanced.

**Comment by 9600bauds** [comment]
N E E D S

C H A N G E L O G

**Comment by ComicIronic** [comment]
What's the point of a server vote if I can't use it to make sweeping balance changes despite never playing the game?

**Comment by 9600bauds** [comment]
Oh yeah that's what they're for but leave them up for a day at least

**Comment by Probe1** [comment]
It's been open for less than 24 hours and server votes are a week.  We'll address it at the end of the week if it swings the other way.  

Please today has been hard enough don't be cuhrazy.

**Comment by Probe1** [comment]
Also as an unrelated note I'm all for test merges for these kinds of things and reverting if it's a bad change, just as long as that's said instead of just hitting merge.

**Comment by 9600bauds** [comment]
it also NEEDED A C H A N G E L O G

**Comment by ComicIronic** [comment]
It has a changelog!

**Comment by 9600bauds** [comment]
Oh.

I actually don't know why I thought it didn't.

ss 2014-01-23 at 04 49 31

**Pull request merged**
