### PR TITLE
Away mission preparations.

### PR DESCRIPTION
**Pull request by ComicIronic**
Added the addZLevel proc, used to sanitize map init and generate the accessable_z_levels list, which is no longer hardcoded.
Fixed a couple of maps I ended up using in testing.
Added more debug data to a debug verb for maps.
Added the movementJammed var, which stops a zlevel being reachable by drift.
Added the movementChance var, which controls how likely a zlevel is to be reached by drifting.
Made the maploader add any new zlevels it creates to the map's zlevel list.

### CODE REVIEW

**Comment by SkowronX** [comment]
EEEEEEEEEEE my alien world plans might be a reality soon.

**Comment by VelardAmakar** [comment]
What I want to know if it's possible to write to an existing z-level using map data

**Comment by ComicIronic** [comment]
It is, but you have to specify it. Look at the z_offset arg for the maploading proc.

**Comment by VelardAmakar** [comment]
Nice, that's good. Now, can I tell it to read from a selection of a .dmm file? Like if I want to to read from x32-x64 and y134-y166?

**Comment by ComicIronic** [comment]
Not currently.

**Pull request merged**
