### PR TITLE
Fixes #6365

### LINKED ISSUE #6365: Leather shoes sprite shows a pixel of skin
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

ea0f3a8343449f1efca6f7ed0051037117d15d80 
Has one pixel that still shows part of your foot. Kinda annoying

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
Fixes https://github.com/d3athrow/vgstation13/issues/6365
I'm almost a real coder tbh

### CODE REVIEW

**Comment by clusterfack** [comment]
You know the rule, post sprites!

**Comment by DeityLink** [comment]
If all he did was adding a single pixel I think we can cut him some slack.

**Comment by clusterfack** [comment]
That's what they all say, until something happens because we didn't follow the rule

**Comment by ShiggyPiggy** [comment]
clusterfack it s just one pixel jesus christ

**Pull request merged**
