### PR TITLE
Openning and flicking cult tome pages now does somes low volume short-range noise

### PR DESCRIPTION
**Pull request by DeityLink**
Because we've had those sound files in the game since forever but they're only used by newspaper that nobody ever prints.

:cl:
* rscadd: Added some page turning sounds when flicking the pages of arcane tomes. Can be heard up to 2 tiles away. 3 tiles if the tome was on the ground and a ghost did the flicking.

### CODE REVIEW

**Comment by iFlashYou** [comment]
"AAH I HEARD BOOK PAGES TURN IN MAINT"

**Comment by yclatious** [comment]
Can you also add it to newspapers? The thought of fucking with sec by reading the news in maint is just too precious.

**Comment by GoodG1448** [comment]
Sound synth too

**Comment by DeityLink** [comment]
@yclatious did you even read the PR's description?

**Comment by Blithering** [comment]
Think he meant the audible radius, not the sound itself

**Comment by agentofzog2** [comment]
add it to books too

**Comment by MadmanMartian** [comment]
add it to all books

**Comment by DeityLink** [comment]
Alright fine it works on all books and even bibles now. All storage containers will now support custom rustling sounds.

**Comment by DeityLink** [comment]
@Blithering the newspaper's audible radius when you turn pages is already the full 7 tile view.

**Comment by MadmanMartian** [comment]
What the fuck sorta books have you been reading for it to be so loud?

**Comment by DeityLink** [comment]
Books with BIG PAGES.

**Comment by Blithering** [comment]
reading books made of tinfoil in an echo chamber

**Pull request merged**
