### PR TITLE
Reverts chem stings & chem spits, re-adds classical stings.

### PR DESCRIPTION
**Pull request by ghost**
:cl:
 * rscdel: Changeling chemsting/spit has been reverted back to changeling classic stings.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
This PR reverts the change to ling that gave it ranged chemical spits and chemical sting.

It gives it back the good old regular stings (sans deathsting - it was removed by another PR).

I made this branch because there was a desire to bring back to the rotation. I just gave the link to someone that could want to defend it.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Why didn't you make this PR yourself instead of a proxy war

**Comment by ShiftyRail** [comment]
Mistake, I typed "PR" when I meant "branch" in an earlier comment

My understanding of the situation was that people wanted ling back but couldn't find a way to code it back in the game, either due to Gitphobia or not understand antag datums code (which is fair).

I made these branches solely for helping people that truly wanted ling back. I could have make the PR myself but then I would just have said, "X asked me to PR this, I have no particular interest in it" and that would have not been a good way to start the discussion.

The author of the PR can defend it by editing his OP or someone else can use the branch as a baseline.

**Comment by ghost** [comment]
I mean this in the politest way possible, but I know you were incredibly upset about antags silently depoping rounds.  Why, might I ask, are you moving to have changeling (the pinnacle of silent station depop'ing) readded after your recent experiences and feelings?

**Comment by ShiftyRail** [comment]
I don't like shitty antags but I hate inertia more. I intended to have an honest talk on changeling and question if it needed to be brought back or not.

Didn't actually thought that people would make the PRs if they didn't want to defend it. It just seemed to me that people had gitphobia that prevented from actually making a change they wanted made.

**Comment by DrSnips** [comment]
I'd like to see one or the other with ling and vamp. They have extremely similar styles of gameplay and I can't say their mechanics warrant having both succ'n'space antags.

**Comment by Allspice** [comment]
@ShiftyRail pretty sure the real inertia was ling not getting removed or relevant changes for however many years

**Comment by bathosbathtime** [comment]
change log when

**Pull request merged**
