### PR TITLE
Accounts Auditing

### PR DESCRIPTION
**Pull request by Kurfursten**
I could have just fixed the bug, but I thought this was more fun for everyone.
* If you try to input a wage over 10000 (about 10x what the whole station earns), it causes the machine to shoot out sparks and fail! You couldn't get this much anyway.
* If you put in a wage more than the entire station earned last cycle, it triggers an announcement requesting a high priority audit.
* If you double someone's wage, it requests a low-priority audit. These are almost always okay, but it gives the IAA some roleplaying potential.
* Admin ghosts do not trigger audits.
* Sharp-eyed users might notice there are some ways to avoid triggering the audit if you're careful. Be sneaky, spaceman...

image
Uh oh, I gave myself more than the entire station earned.

image
Someone with an emag just gave me 2000 per cycle. It wasn't me, really.

🆑 
* bugfix: Fixed a bug where you could cause an infinite error with unprotected input on wages.
* rscadd: You may now trigger an audit with suspicious wage modifications.
* rscadd: You can now repair the Accounts Database if it is emagged.

### CODE REVIEW

**Comment by gurfan** [comment]
Will repeatedly setting a high wage spam multiple audits?

**Comment by Kurfursten** [comment]
It will, but if you have the access to do that you can already do it with the communications computer priority announcement. It's not a bad idea to change it so that it won't play a second audit alert if that account was already under high priority audit. I should mention it's not SUPER spammable because you have to put a number inside the popup box and click okay.

Still, if it's a big worry I can add a cooldown.

**Comment by gurfan** [comment]
> It will, but if you have the access to do that you can already do it with the communications computer priority announcement. 

I'm pretty sure that has a cooldown to prevent people spamming it, though I might be wrong. It's not a big issue and things like gremlins/alert spam exist, but it's something that came to my mind.

**Comment by Eneocho** [comment]
Does this still let you siphon the credits from the debit cards? Do I need to do a tedious series of changes for the audit not to fire?

**Comment by Kurfursten** [comment]
You can lower wages on credit cards with no warning alert if that's what you mean. It only warns if wages go up suspiciously.

**Comment by Eneocho** [comment]
> You can lower wages on credit cards with no warning alert if that's what you mean. It only warns if wages go up suspiciously.

Based on a cursory read, it wouldn't send any warning if each individual wage change is less than 2x the last wage, correct? 
So if I wanted to give myself 500 credits I siphoned from the debit cards, and I started with, say, 10 credits, I'd need to do 10 -> 19 -> 37 -> 73 -> 145 -> 289 -> 510. I'd need to do this across 6 wage cycles to not send any warning. Do I understand this correctly or did I get it wrong?
Alternatively, I'd need to create a new account to which I'd send all the money, and since it wouldn't have had any wages before, there was no "wages doubling", therefore avoiding an audit, is this correct?

**Comment by Kurfursten** [comment]
That's right... or you can just set your wage to 0 and then to whatever. I could set more robust checks against this, but I kind of thought it was fun to have some means of getting around it by cooking the books.

**Comment by Eneocho** [comment]
Do you need to set it to zero for at least one shift, or going down to zero then immediately to 510 work?

**Comment by Kurfursten** [comment]
I feel a bit like I'm ruining the mystique by telling you how to subvert the audit in the PR itself.

**Comment by strawberrytan** [comment]
I really like this but I have one criticism. The global announcement should be more like the opening paragraph of the bridge faxpaper and not name the user. So the fax paper does name the suspicious individuals and the global announcement does not.

> Financial Audit Required

> Central Command detected an unusual wage increase has been authorized at the accounts database on your station. Although command staff have broad latitude to set wages within reason, there are documented cases of abuse, off-books dealing, cryptographic sequencing, and even simple security errors such as leaving a computer logged in without supervision. For this reason, STATIONNAME/your station Internal Affairs is requested to audit any recent wage modifications.

**Comment by Kurfursten** [comment]
As a compromise I have clarified in the text that the user is merely logged in as [name] instead of definitely that user. This is definitely the LYNCHING announcement though.

**Pull request merged**
