### PR TITLE
New outfit for the theater vendor

### PR DESCRIPTION
**Pull request by CodenameB**
Give yourself over to absolute pleasure with this PR. This will add Dr. Frank N. Furter's classic costume from the Rocky Horror Picture Show to the vending machine in the theater. 

The costume comes in three parts: gloves, uniform, and shoes; and I guarantee when you wear it, in just seven days it will make you a man.

Don't dream it. Be it!

image

I see you shiver with antici
.
.
.
.
.
pation.

:cl: 
 * rscadd: New theater exclusive costume

### CODE REVIEW

**Comment by RFultra** [comment]
https://www.youtube.com/watch?v=tkplPbd2f60 YES

**Comment by Arthurdentist** [comment]
Should have a very small chance of spawning in the medbay lockers.

**Comment by Lokiamis** [comment]
it's just dumb fucking fetish gear disguised as a reference
wedding dresses are bad enough

**Comment by Arthurdentist** [comment]
its a classic cult sci-fi reference, and its 'fetish gear disguised as a reference' in the same way that the Jabroni Outfit is.

Hardly think this is on the same level as shitty waifus traipsing around in wedding dresses or whatever.

**Comment by ghost** [comment]
thriller suit when

**Comment by strawberrytan** [comment]
Waifucreep

Why contain it

**Comment by CodenameB** [comment]
@strawberrytan Technically, this outfit is meant for men.

**Comment by Arthurdentist** [comment]
merge when

**Comment by ghost** [comment]
The opening comment used all the good quotes that I can think of.

**Pull request merged**
