### PR TITLE
go commit numbergame

### PR DESCRIPTION
**Pull request by help-maint**
## Admin is stabbing himself with the pen and pouring their soul into the paper! It looks like they're trying to commit sudoku.
dreamseeker_15_05_2021_23_06_06_37
I spent 3 hours trying to make the sudoku playable but
dreamseeker_15_05_2021_22_05_05_17
A- papercode is terrible
B- papercode lags horribly if you have a lot of fields
C- papercode is hardcoded to have a 50 field limit
so no it's not playable

:cl:
 * rscadd: You can now sudoku by suiciding with a pen while holding a blank piece of paper.

### CODE REVIEW

**Comment by Eneocho** [comment]
Just make it a 6x6 sudoku.

**Comment by help-maint** [comment]
I'd rather kms

**Comment by GreatBigFailure** [comment]
This is very good

**Comment by Exxion** [comment]
>no thicker lines between the boxes

**Comment by help-maint** [comment]
BYOND uses early 90's HTML that doesn't support :nth-of-type() so I lost interest

**Comment by Exxion** [comment]
Just use tables within tables

**Comment by Eneocho** [comment]
> 
> 
> Just use tables within tables

A blood black nothingness began to spin.

**Comment by Exxion** [comment]
If you have 90s tools, gotta use 90s solutions

**Comment by Eneocho** [comment]
> 
> 
> I'd rather kms

Suicide with phazon/hyperzine making you km/s when

**Pull request merged**
