### PR TITLE
Sprite issue fixes

### LINKED ISSUE #5586: (WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Voice changer disappearing
>Revision (Should be above if you're viewing this from ingame!)
09f185b68a28bf49031a7bb23176e62d01c1ea7b

>General description of the issue
Voice changer not having a clickable symbol after being changed to facehugger form and pushed out of ones face

>What you expected to happen
Have the mask in hand or something

>What actually happened
I have an "empty" slot in my backpack which I cannot click but is blocking space.

>Steps to reproduce if possible

### LINKED ISSUE #6965: Dismembered Limb sprite issue
(WEB REPORT BY: pomf123 REMOTE: 158.69.55.2:7777)
The dismembered arm object has no sprite for the East (4) direction.

### LINKED ISSUE #7287: Brown gloves have no sprite when worn
(WEB REPORT BY: unid REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> aec8a97d60b1c6504bee0bf3a467312e7eaed0ae
> 
> General description of the issue
> Brown gloves have no sprite when worn
> 
> Steps to reproduce if possible
> Put a rubber stamp with insulated gloves into the washing machine, receive gloves that are invisible when worn

### LINKED ISSUE #7676: Bedhead hairstyle inconsistency.
https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/01/2016-01-12_19-24-45.webm

### PR DESCRIPTION
**Pull request by TheEliminator16**
This PR is to fix the sprite issues found in these four issues: fix #5586, fix #7676, fix #7287, fix #6965
- Issue with voice changer disappearing when set to facehugger form and pushed out of the face
- bedhead hairstyle inconsistency
- brown gloves sprite not showing up on mob
- dismembered arm sprites missing one direction, depending on which arm it was

### CODE REVIEW

**Comment by Exxion** [comment]
Please put some form of "fix," "close," or "address" before each of those issues so they autoclose when this is merged

**Comment by TheEliminator16** [comment]
Like that?

**Comment by Exxion** [comment]
Yeah, that'll work.
Also have fun with the binary file conflicts

**Comment by TheEliminator16** [comment]
Yeah I have no idea what I need to do. It just has to do with the changelog and gloves/color.dm

**Comment by Exxion** [comment]
It's almost certainly a conflict on one of the sprite files, which means it has to be fixed manually

**Comment by TheEliminator16** [comment]
I mean I did a rebase and the only things it was telling me were conflicting were the two files I mentioned. I think the changelog is an issue because I still had a copy on my local repository, so it marked it as a modification rather than an addition, but I don't know about the other one.

**Comment by Exxion** [comment]
Oh, it only complained about those two? That's no problem then.
...Wait, how could you get conflicts on your own changelog and a one-line change like that?

**Comment by TheEliminator16** [comment]
I know far less about this than you do, man

**Comment by Exxion** [comment]
What was the command you used to do the rebase?

**Comment by TheEliminator16** [comment]
git rebase Bleeding-Edge

then git rebase -X theirs Bleeding-Edge

**Comment by Exxion** [comment]
Huh. Not sure what's up then.

**Comment by TheEliminator16** [comment]
How the hell did I get conflicts on like 5 changed lines? I updated bleeding edge RIGHT before doing this

**Comment by Exxion** [comment]
That shouldn't matter because none of them should have conflicted even if you hadn't

**Comment by TheEliminator16** [comment]
I barely know anything about github, what even causes a merge conflict?

**Comment by Exxion** [comment]
When two people changed the same line on separate branches
Unless it's a binary file like the .dmis, in which case any change to the file on two different branches causes a conflict

**Comment by TheEliminator16** [comment]
Besides the rebase function, what can I do to solve this? Is there any way to see what SPECIFICALLY is conflicting?

**Comment by Exxion** [comment]
Yeah, it should show up in the file unless it's one of the .dmis

**Comment by TheEliminator16** [comment]
Now, it's just stopped giving me errors entirely when I try to rebase. What the hell did I do wrong here?

**Comment by Exxion** [comment]
I honestly couldn't tell you. Sorry.
Try just killing the branch and redoing the changes.

**Comment by TheEliminator16** [comment]
So apparently I made a whole new PR? And this one works? Whatever, I'm not going to question it, how do I close a PR?

**Comment by Exxion** [comment]
Right beside the post comment button

**Comment by TheEliminator16** [comment]
I swear I'm not brain damaged

**Comment by TheEliminator16** [comment]
Anyway yeah new PR: https://github.com/d3athrow/vgstation13/pull/7829

**Pull request closed without merging**
