### PR TITLE
Re-adds recursive cereal

### PR DESCRIPTION
**Pull request by SonixApache**
🆑 
 - tweak: re-added recursive cereal

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Unless I'm missing something, doesn't the presence of the `findtext()` prevent the creation of "cereal cereal cereal cereal"? Sure, you can re-cereal something by renaming it, but what is the *point* then?
For that matter, you could also just make a normal cereal and use a pen to name it "cereal cereal cereal cereal," couldn't you?

**Comment by SonixApache** [comment]
Externally, it'd be "Captain-O's"
Internally, it'd be captain's spare ID cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal cereal.

The difference is the picture on the box, and the idea behind it.

**Comment by MadmanMartian** [comment]
But, why?

**Comment by Exxion** [comment]
@Shadowmech88 That's how it always was
@MadmanMartian Because it's funny and harmless and an absolutely classic bug

**Comment by arc166** [comment]
It was soul.
If you don't get it, you as soul less.

**Comment by cowboybuttsdrivemenuts** [comment]
the fact this wasn't speedmerged is a travesty

**Comment by Intigracy** [comment]
Unlike burgers and stuff, this won't endlessly add a longer and longer name and a larger and larger sprite, completely harmless.

It also makes the check consistent with other foodstuffs, like the candy machine. That also uses findtext instead of an istype.

Dumb but harmless.

**Pull request merged**
