### PR TITLE
One step to make the repo TOS-compliant

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Word filters were left up and noted to be word filters

### CODE REVIEW

**Comment by ghost** [comment]
bruh

**Comment by DrSnips** [comment]
Once again we, gamers, are being oppressed by the big man. We must fall back on the other 14.7 thousand in [redacted].

**Comment by ShiftyRail** [comment]
premature and silly

**Comment by oversane** [comment]
great work microsoft

**Comment by Kharkov72** [comment]
I for one welcome our git overlords

**Comment by SonixApache** [comment]
nigger

**Comment by ghost** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=55&t=26318#p555437

This actually was the reason behind the TG takedown so it may not be a terrible idea to reconsider in case someone decides to report us as well.

**Pull request closed without merging**
