### PR TITLE
Adds David Bowie's Starman to the title screen

### PR DESCRIPTION
**Pull request by unid15**
I mean come on it's the current year

### CODE REVIEW

**Comment by 9600bauds** [comment]
:+1:

**Comment by Arthurdentist** [comment]
sure :+1:

**Comment by CptWad** [comment]
There needs to be a [Sound] label
also :+1:

**Comment by ghost** [comment]
:+1:

**Comment by clusterfack** [comment]
Trying to find a way to softcode the lobby music into a jukebox playlist so this doesn't bloat the rsc by 5mb

**Comment by PJB3005** [comment]
@clusterfack that's gonna require modifications to the media server code and shit.

**Comment by clusterfack** [comment]
Well yeah but it's not particularly complex compared to jukeboxes

**Pull request merged**
