### PR TITLE
DNA injectors should now disappear after injecting someone with a monkey-to-human or human-to-monkey SE

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
:cl:
 * bugfix: DNA injectors will now properly disappear after injecting someone with a monkey-to-human or human-to-monkey gene

### CODE REVIEW

**Comment by jknpj** [comment]
The anti-detective cabal strikes again

**Comment by boy2mantwicethefam** [comment]
dummy

**Comment by tuypo1** [comment]
Yeah, removal of evidence doesn't seem like such a great idea

**Comment by boy2mantwicethefam** [comment]
i'll bite
what currently happens is that DNA syringes disappear immediately after injecting someone with it (as they should) but monkeyization makes the DNA syringes not disappear as they should until AFTER the monkeyization finishes
This PR fixes it

**Comment by jknpj** [comment]
I'll still miss these

**Pull request merged**
