### PR TITLE
RSF update

### PR DESCRIPTION
**Pull request by Riukanojutsu**
Removed :Pen and cigarette from RSF
added :flask, deck of cards and candles

Added RSF to hacked autolathe menu for 4/5 of the price of the RCD

Changed Matter capacity from 60>40 and matter catridge value from 30>20

Fixed: the RSF having unlimited range.
Fixed: Not being able to put a mattercatridge in the RSF unless you used the whole cartridge (If you had 31 matter it said it was full)

### CODE REVIEW

**Comment by SarahJohnson489** [comment]
Put the paper back in at least. I don't think anyone else has done it or at least not often but it's useful in cult even if there's a buttload of other sources it's another good one that's not obvious folder of cult talismans if you get redtided.

Ciggs was a good style and there's no benefit to removing them. Especially if you spawned with only 100 credit salary

Consider adding a consumes matter cartridges to fabricate blahblahblah if you're worried about it.
I'd like to see the roundstart flasks to stay but whatever.

**Comment by Riukanojutsu** [comment]
I guess I can put paper back.

Ciggs is just no. You can get them from machines (and one of them is in the bar, which is the main reason why it was suggested I remove these.) and even if you spawn with 100$ you will have enough to buy cigs+lighter. Distributing cigs one by one was just dumb and it was never used. Im trying to keep the RSF "menu" as small and useful as possible.

"Consider adding a consumes matter cartridges to fabricate blahblahblah if you're worried about it." Im not sure what you mean by that since every item cost matter already. Its not about spamming the item rather than it doesnt need to be spawned there since theres a machine where you can buy them in the bar already.

Roundstart flask are no necessary since you can spawn them with roundstart items with the RSF. They just clutter the already very cluttered bar and it would be redundant to keep them.

Thanks for your feedback.

**Comment by Probe1** [comment]
I like removing things that make money redundant.  My first reaction was "Why are cigs removed, that's a bar-item and it makes sense".  But on second thought, it's one of many things that make the whole economy pointless.

**Comment by ComicIronic** [comment]
You have to use the mapmerger to make map edits.

**Comment by Riukanojutsu** [comment]
Yea I know. Ill revert and redo it.

**Comment by Riukanojutsu** [comment]
suffering

**Comment by ComicIronic** [comment]
Are you using some sort of YAML configured editor? All the tabs have become spaces.

**Comment by Riukanojutsu** [comment]
Im using dream maker with default sertting

**Comment by Riukanojutsu** [comment]
what the fuuuuuuuuuuuck

**Comment by ComicIronic** [comment]
What are the mapchanges for?

**Comment by Riukanojutsu** [comment]
I want to move the RSF to the backroom of the bar, put a matter cartridge on it to show that it requires one to work (a lot of people seem to not know this) and remove the flask from the table near the barvend since you can spawn them at roundstart with RSF.

**Comment by Probe1** [comment]
keep at it riu

**Comment by Riukanojutsu** [comment]
I have to redo the pr because I didnt properly update my shit or something
Like, rsf.dm and autolathe.dm are ready to be merged but the rest of my code aint up to date or something. Git is fucking hell to use and its honestly more trouble than the coding I did so far. shits fucking crazy.

**Pull request closed without merging**
