### PR TITLE
Prevents honker blast deaf/stutter stacking, increases duration. 

### PR DESCRIPTION
**Pull request by Reviire**
After experiencing the honker blast in a round, I think it's a bit too strong. Rapidly spamming it can cause stuttering and deafness that lasts for over 20 minutes.  Triples the stuttering time, and nearly triples the deafness time. 

Ignore the random chem_master_4000 deletion, unless that's a problem. Still figuring out github but I think I've got it. 

:cl:
 * rsctweak: Honker blast can no longer stack stutter/deaf times, triples duration of both.

### CODE REVIEW

**Comment by SonixApache** [comment]
image
`ear_damage = 0
ear_deaf = 0`
ethylredoxrazine
`dizziness = 0
drowsyness = 0
stuttering = 0
confused = 0`

potassium potassium nitrogen nitrogen silicon silicon carbon carbon oxygen water
honker defeated

good job on gitting gud though :+1:

**Comment by ValkyrieSkies** [comment]
I DIED PLS NERF

**Comment by Reviire** [comment]
>Died
deafness/stuttering doesn't lead to death, it's just annoying. And silly you can quickly stack it to absurd numbers. If you take the chemicals to fix it, this PR wouldn't affect you at all, so nothing changes in that regard.

**Comment by Reviire** [comment]
Stuttering and deafness hardly leads to dying, it's not like I'm changing the 10 second stun it has.

**Comment by SonixApache** [comment]
image

**Comment by Probe1** [comment]
Present your ideas like an adult instead of linking images of chem recipes and saying git gud.  I agree with you but theres no reason to be a big dutch bully!

**Comment by FudgePucker** [comment]
The H.O.N.K. is exposed to be extremely over powered yet extremely pointless. Bananium ore is right next to phazon ore.

**Comment by AutismSpider** [comment]
people left out can put weapons on the fucking honk or have people forgotten the xenofucker honk mech?

Were the clown and his Honk blast and D drill  killed pack of xenos by honk blasting and drilling them one by one.

**Comment by FudgePucker** [comment]
Wait you can put weapons on the HONK? That sort of kills the point of a clown mech doesn't it?

**Comment by AutismSpider** [comment]
@FudgePucker yup honk can take weapons and mining gear

**Comment by SonixApache** [comment]
@Probe1 
Argument is "there is no need for this since common chemicals directly counteract this issue".
"Git gud" as in "good job in learning how to operate github well". It's a pun.

**Comment by Probe1** [comment]
Ye I knew where you were going with it but we need to rise above and work together.  Or we'll fall into shitposting and locked PRs.

**Comment by ghost** [comment]
You can't tase someone 5 times to stun them for a full minute, you can't slip someone 5 times to floor them for a long while, you can't flash someone 5 times to make their screen white forever. Off the top of my head the only thing that works like that are chemicals of which you actually need to make more of.

This is what this PR changes (pretty fucking generously at that). The circlejerk about wow look at how gud I am for powergaming chems misses the point, badly.

**Comment by Reviire** [comment]
Anyway, this change won't affect people who chug chemicals anyway. But people who aren't able to access those chemicals don't really deserve to be stuttering and deaf for 20 minutes.

It's hardly a nerf, the real nerf it should get is to not be a no cooldown 15x15, 10 second stun which can be followed up with an AC2 or d-drill.

**Comment by Probe1** [comment]
Take this back to the issue and get people to agree with a change.  It was too early for a PR.

**Pull request closed without merging**
