### PR TITLE
higher TEG ciurculator flow

### PR DESCRIPTION
**Pull request by CrazyAmphibian**
[tweak]

alternative to #36431 

## What this does
increases the max flow rate of the TEG so that it can go to 100%. this affects power output and gas use rates.
Capture

## Why it's good
fixes the flow rate being stuck at 33%.

## Changelog

:cl:
 * tweak: the TEG can now use 100% of its flow capacity instead of being limited to 33%

### CODE REVIEW

**Comment by SonixApache** [comment]
how does this interact with the ethanol greasing?

**Comment by CrazyAmphibian** [comment]
it doesn't change anything dealing with lube or waste+ethanol

**Comment by west3436** [comment]
What does the power generation look like for a basic roundstart Box TEG before and after this change is implemented?

**Comment by CrazyAmphibian** [comment]
without: 440-100 kw

with: 400-90 kW

yes, the roundstart produces around 10% less from this one test (could be due to slight variations)
the numbers aren't that much different, which makes sense actually, because the same amount of energy is being given to the TEG, just at different speeds

**Comment by DamianX** [comment]
> ## Why it's good
> 
> fixes the flow rate being stuck at 33%.

That is a what, not a why!



> without: 440-100 kw
> 
> with: 400-90 kW
> 
> yes, the roundstart produces around 10% less from this one test (could be due to slight variations) the numbers aren't that much different, which makes sense actually, because the same amount of energy is being given to the TEG, just at different speeds

You probably messed up testing. Did you use lube at all? You should have seen 0 difference if you didn't use lube, and 3x difference if you did, if the code comments are to be believed.

**Comment by DamianX** [comment]
And why in the gosh darn is this a server vote? Are you going to have a server vote for every PR that conflicts with another? No one knows how this works, apparently not even the author.

**Comment by CrazyAmphibian** [comment]
> You probably messed up testing.

i mean yeah, the setups were not exactly the same due to the time it takes for gas to flow into the hot and cooling loops, but in terms of fuel supply they were the same

> Did you use lube at all?

the roundstart setup does not include lube.

> You should have seen 0 difference if you didn't use lube, and 3x difference if you did, if the code comments are to be believed.

there'd be a difference since more gas is available for use in the TEG than before. This affects it without lube. The result shows that the impact on low-end setups is negligible.

> And why in the gosh darn is this a server vote

i don't really know but i don't think it's a bad thing

**Comment by DamianX** [comment]
> > You should have seen 0 difference if you didn't use lube, and 3x difference if you did, if the code comments are to be believed.
> 
> there'd be a difference since more gas is available for use in the TEG than before. This affects it without lube. The result shows that the impact on low-end setups is negligible.

Wrong.
Your change only affects this line:
`volume_capacity_used = min((last_pressure_delta * air1.volume / 3) / (input_starting_pressure * air1.volume), 1)	//How much of the gas in the input air volume is consumed.`
Which only affects the variable `volume_capacity_used`, which is only used here:
```
//If our circulators are lubed get extra power
if(circ1.reagents.get_reagent_amount(LUBE)>=1)
	last_gen *= 1 + ((circ1.volume_capacity_used * 100) / 16.5) //Up to x3 if flow capacity is 33%
if(circ2.reagents.get_reagent_amount(LUBE)>=1)
	last_gen *= 1 + ((circ2.volume_capacity_used * 100) / 16.5)
```
which means it will only have ANY impact when lube is used, therefore any testing you have done is irrelevant if you didn't use lube.

**Comment by DamianX** [comment]
I should clarify that variable is also used by the "Flow capacity" element in the UI, which is why the progress bar goes up to 99 instead of 33 now.

**Comment by CrazyAmphibian** [comment]
> which means it will only have ANY impact when lube is used, therefore any testing you have done is irrelevant if you didn't use lube.

no? test the code for yourself if you don't believe me.
lube has no impact on the flow rate at all. all it does is multiply the power output.

**Comment by DamianX** [comment]
That's correct, lube is supposed to multiply the power output. Your change only affects power generation when lube is used.

**Comment by CrazyAmphibian** [comment]
> That's correct, lube is supposed to multiply the power output. Your change only affects power generation when lube is used.

it doesn't. it always affects the maximum power generation.

**Comment by DamianX** [comment]
Could you point me to the line or lines responsible for that?

**Comment by CrazyAmphibian** [comment]
Nevermind, you are correct about the lube thing
i was confused because it uses 2 varibles for flow (thank you oldcoders)

**Comment by jwhitak** [comment]
Lubing your TEG is now more powerful. Beware.

**Pull request merged**
