### PR TITLE
Adds 1x1, 5x5, 7x7 photo functionality. Cameras can switch between 1x1 and 3x3 photos

### LINKED ISSUE #7607: AI camera issue
(WEB REPORT BY: somhuan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d2f2bae98f971619a669eabe31c98eab5c834d8e 
> 
> General description of the issue
> AIs cannot take pictures of people or animals, only objects
> 
> What you expected to happen
> Use active camera on a person, take a picture of that person
> 
> What actually happened
> Active camera refuses to work on any type of human or animal, and only works on objects.
> 
> Steps to reproduce if possible
> Be AI, attempt to make portraits.

The workaround I use for this is taking pictures of objects near people, but ghost chat brought up to me that this might actually be a bug and not a feature, so here you go.

### PR DESCRIPTION
**Pull request by unid15**
- Adds admin spawnable 5x5 and 7x7 cameras
- Normal and sepia cameras can be zoomed in (for 1x1 photos) or out (for 3x3 photos) by altclicking or using a verb
- Fixed being unable to take photos of yourself / the turf you're standing on
- Fixed AIs being unable to take photos of mobs (Fixes #7607)
- **100% tested**

### CODE REVIEW

**Comment by clusterfack** [comment]
I don't want to say the idea is bad, it's just extremely dangerous because get flat icon is so costly that you can already freeze the server for a second with a 3x3 photo. Ideally lummox is going to add a function to convert an appearance to an icon directly some day and bypass the need for it.

**Comment by 9600bauds** [comment]
Speaking of, the statpanel thing when you alt-click already uses the thing's proper icon. Is there a way to implement that into the \icon[src] macro?

**Comment by ghost** [comment]
@clusterfack 

Are you sure this is not a one time IO operation that's causing the hangs? As in size is the minor factor, it's the fact it makes the picture at all.

**Comment by 9600bauds** [comment]
getFlatIcon() slowly and painstakingly rebuilds icons from their underlays, overlays, colors, icon_state etc. because BYOND is shit

**Comment by ghost** [comment]
> 2% tested

Is such a thing even possible?

**Comment by clusterfack** [comment]
@TermedClepe 
No it's not and I'm not even sure what you said makes sense really

@9600bauds 
It doesn't show the correct image to my knowledge as evidenced by the cable coils that show up as white in the stat panel, the problem with /icon[src] is that it uses the base icon and doesn't use the actual appearance which is essentially the exact same problem we have here.

**Comment by ghost** [comment]
@clusterfack

Sometimes people write to disk to store small temporary things, like the photo image. This ends up in unexpected lags because the writing is running on the same thread as everything else. Just stabbed in the dark, no idea how it's implemented in byond.

**Comment by unid15** [comment]
100% tested and ready

The only new feature here is cameras being able to take 1x1 photos, so there won't be more lag unless mememins spawn a bunch of 7x7 cameras

**Comment by ghost** [comment]
I think currently cameras can't take a photo of the tile you're standing on, can you fix that?

**Comment by unid15** [comment]
done

**Comment by unid15** [comment]
also fixed AIs being unable to take photos of mobs

**Comment by PJB3005** [comment]
@clusterfack does a feature request for appearance2icon exist on the BYOND forums?

**Comment by clusterfack** [comment]
Not to my knowledge, we discussed it briefly in a developer help section once. But I never got around to making an actual request. Perhaps there's one from years back to bump but I haven't checked.

**Comment by unid15** [comment]
when

**Pull request merged**
