### PR TITLE
Fixed bees never coming out of their apiary on some maps

### LINKED ISSUE #23493: Bug and Hornets do not spawn on defficiency and meta club
(WEB REPORT BY: germansanta REMOTE: 206.221.180.138:7777)
# Revision
106e9d17accd7614718b17a92a2df0e547522cab

# Description
Fill the apiary's with beeezz, with vegetables, fruit, and basic plants around them. They never spawn on defficiency and meta club.

# Steps to Reproduce
Make bees with beeezz and a queen bee packet. On defficiency and meta-club.

# What you Expected
Bees to spawn out of hive

# What Actually Happened
Nothing spawned

### PR DESCRIPTION
**Pull request by DeityLink**
Shouldn't have removed it from world.dm in #23283 R0B0

Fixes #23493

:cl:
* bugfix: Fixed bees never coming out of their apiary on some maps.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
but now the runtimes start again

**Comment by DeityLink** [comment]
@MadmanMartian I kept the call to initialization you added to the bee datums' New()

**Comment by nuklearcellphoneg** [comment]
ty

**Comment by SonixApache** [comment]
very hip PR

**Pull request merged**
