### PR TITLE
Finally (mostly) fix window pulling-Now with added window pushing!

### LINKED ISSUE #3515: (WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) Can't pull windows in the direction they're facing
>Revision a3d8d26835ddf904da2046864f5d9f71d1e939d6 

>General description of the issue
Title

>What you expected to happen
the window would be pulled just fine

>What actually happened
it didn't get pulled

>Steps to reproduce if possible
1. make a loose (1 dir)window
2. attempt to pull it into the direction it's facing

### PR DESCRIPTION
**Pull request by Exxion**
That was actually surprisingly painless, considering how old and annoying this bug is.
Windows can now be pulled in the direction they are facing.
This was accomplished by making a special case for border objects in Adjacent(). (Don't worry, it's only one line.) Before checking if a border object is blocking the turf the targeted object is on, it now checks if the border object blocking the turf _is_ the targeted object. This really shouldn't cause unintended behavior elsewhere, but I can't guarantee that it won't anyway due to the sheer quantity of old and/or weird code.

Fixes #3515.

~~Windows have a similar issue with being pushed in the direction they're facing. I'll look into that, too, but this PR doesn't fix it.~~
Fixed it.

While testing this, I also noticed that windows can be pulled through anything except other windows in the opposite direction as they are facing, but this is unrelated to my change. I'll report that separately, though, as I can't fix it for reasons I will explain in the report.

### CODE REVIEW

**Comment by 9600bauds** [comment]
fuck yes

**Comment by Exxion** [comment]
What is Travis' deal?
Oh well. Let's see if I can fix and test window pushing before Travis builds this.

**Comment by Exxion** [comment]
Travis is really backed up or something. I did it before the build even started.
The fix is a tad snowflakey, but not nearly as much so as the three lines that immediately follow it.

**Comment by Exxion** [comment]
After looking back over this, I think there's still a semi-obscure case in which it would fail. I should be able to fix that by this afternoon.

**Pull request merged**
