### PR TITLE
can't perform CPR if you have no lungs

### PR DESCRIPTION
**Pull request by MadmanMartian**
for consistency sake, if you can't blow up a balloon, you can't blow into somebodies mouth to blow up a pair of lungs.

Pointed out by 
crab_atting_me

:cl:
* rscadd: You can no longer perform CPR if you lack lungs or can not breathe.

### CODE REVIEW

**Comment by jknpj** [comment]
Not sure why this got a balance tag

**Comment by Pathid** [comment]
Means you can't CPR as an adult diona, golem, skellington or slimeperson. This has me wondering if compression-only CPR would be worth putting in.

**Comment by Probe1** [comment]
Well.. it is game balance.  [Balance] isn't [Do Not Merge but Pink instead of Red].

**Comment by MadmanMartian** [comment]
@Pathid our method of crit would have to change then, as currently the CPR is so you can breathe a little bit, not to help pump the heart.

**Comment by Blithering** [comment]
Maybe if this goes through, adding a CPR bag somewhere would be a good idea, as with vox and plasmamen likely to die horribly if they attempt CPR this leaves only humans and greys able to keep people alive

**Comment by Megamaw** [comment]
i also think doing cpr on plasmamen would be disastrous for the person attempting, honestly

(joke about making humans and greys already being overpowered goes here but i couldnt think of one. add your own if youd like)

**Comment by jknpj** [comment]
>(joke about making humans and greys already being overpowered goes here but i couldnt think of one. add your own if youd like)

No we're not going to bring skeletons back.

**Pull request merged**
