### PR TITLE
Character setup role names

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[role]

## What this does
Screenshot_20230119_185001
adds this to set your name at the start of the round or on borging, with the namepick option still in place.

## Why it's good
one less thing to do when joining a round, makes proper clown and mime names show up on the arrivals announcements.

## Changelog
:cl:
 * tweak: Clown, Mime, Cyborg, AI and MoMMI names can now be configured in character setup.

### CODE REVIEW

**Comment by gurfan** [comment]
Fuck no.
This bloats up the character setup menu and I want to be able to choose names based on what happens at roundstart. I like naming my AI/Cyborgs something similar to what the other silicons have named themselves. I hate that this encourages static names for these roles too, I would much prefer to just pick a name in game rather than fiddle around with the clunky character menu.

**Comment by SECBATON-GRIFFON** [comment]
> This bloats up the character setup menu

i was debating having it be context dependent, like if the preview shows up for clown or mime on the player icon then you could pick the clown or mime name, but that seems even clunkier.

**Comment by west3436** [comment]
Why not implement the character settings screen change but also keep the namepick if you want to change it?

**Comment by SECBATON-GRIFFON** [comment]
> Why not implement the character settings screen change but also keep the namepick if you want to change it?

deciding to keep it now along with this @west3436 @gurfan

**Comment by boy2mantwicethefam** [comment]
This might have unforeseen consequences but I like the idea of pre-setup names, especially when it concerns freshly arriving to the station, it's weird to see a mime with a completely regular name.

**Comment by pedr69** [comment]
might fix #30368, sorta?

**Comment by Servalfang** [comment]
No.

**Comment by tinysaturn** [comment]
I don't see the issue with this if you still get the normal namepick upon joining
Maybe see if you can put this under a tab that expands when you click on it

**Comment by Kurfursten** [comment]
I suggest a sub-menu like we have for disabilities/limbs. That way there is no menu bloat, but it's also accessible pre-round.

**Comment by SECBATON-GRIFFON** [comment]
will revisit some other time

**Pull request closed without merging**
