### PR TITLE
The "Economy" update, part 1

### LINKED ISSUE #5014: PDA atm app and transaction logging
Yet another terrible feature request.

First change, have all digital transactions logged, so the captain or whoever can look through them. Excuse to use physical credits for payment for illicit things.

Second.
Have an app you can download onto your pda/buy/whatever from the pda thing. The ATM app.
To use this app, you must have an id card inserted. Opening the program prompts you for a pin and account number, and if you enter them correctly for that ID, from then on the PDA is authorized.

Wearing the authorized pda lets you use vending machines without asking for a pin, atms without asking for account numbers and pins, and allows you to do player transactions without entering account numbers or pins. Just swipe and go. 

Ejecting the id card automatically de-authorizes the pda though, and you can manually de-authorize in the pda interface. The app might also have an option to view transaction logs of the linked account.

It'd also be neat if somehow this also worked the other way as well, ie: depositing into your account from a transaction from another player.

As a possible extra, heads could have secure accounts that'd require a DNA sample in addition to authorize. Of course, how you get this DNA sample is up to you I'm sure.

This would make digital transactions easier to manage between players, and maybe allow for easier implementation of economy in the future.

### PR DESCRIPTION
**Pull request by DeityLink**
roundstart

transac
- Bank accounts no longer have a chance to spawn with Zero security (aka the "ATM stays unlocked with all my info" bug)
- "Balance Check" app now re-dubed "Virtual Wallet and Balance Check". Installed on all PDAs by default. Lets you check the transactions and balance of both your bank account and your ID's virtual wallet. Lets you print and absorb currency (only bills for now).
- ATMs let you transfer funds between your bank account and your virtual wallet. Credits withdrawn at an ATM no longer have a chance of appearing "behind" the ATM.
- If you're wearing a wallet on your ID slot, withdrawing money at an ATM or printing currency with a PDA will send the credits directly inside your wallet. Wallets can now also be bought at Merch Computers.
- Added lots of new wallet sprites for every kind of IDs. Up'd wallet storage slots from 10 to 20. Can also be worn on belts now.
- Credit Chips can now only contain up to 10 bills of one kind, down from 100. You're more likely to see big stacks of dosh now.
- Starting money for both virtual wallet and bank account are random between 100 and 250. Which means between 200 and 500 total dosh at round start.
- Fixed a Station Map app bug that caused BoxStation's map to not render.
- When your ID is in your PDA, you can transfer money to other people's PDAs. They'll receive a notification and get the money as soon as they put their IDs in their PDA.
- Vending machines and the like now use credits from your Virtual Wallet by default. The exception is the Cargo supply computers which still use bank accounts since payments are delayed.
- Setting your bank account's security to Zero lets you make purchases using your bank account's money when your virtual wallet has insufficient funds.
- The cargo tax is now part of the supply pack's price (20% of it).
- Service borgs cannot print dosh anymore. (Sorry guys)

It's "Economy", not Economy. Quotation marks are important, because I'm not trying to create a real-world economy. Here's a few points I said on IRC:

1-"Economy" in SS13 must NOT be mandatory for the players to use. We're not forcing them to use it.

2-"Economy" in SS13 must be easy to use and intuitive. As N3X15 said, players always take the path of least resistance, which is why this PR is a huge step up from the current state of money in the game (since money is really easy to transfer from player to player now, doesn't require EFTPOS bullshit, and bills can be printed/absorbed without the need of an ATM)

3-Goods that can be bought with money (in the merch computer for example) should NOT be overly convenient tools, weapons, etc, but rather luxuries, toys, good examples include clothing (we have tons of unused clothing sprites in the game which don't fit with the Autodrobe's clown theme. We could allow players to purchase them here instead) or toys like Cyadox's upcoming Poker suitcase, paintings...

4-Admins will have a certain degree of control over this economy, the next parts will add salaries, bonuses, orders, and admins will be able to regulate it in real time (as nanotrasen), which gives the IAA a much more important job, he can now report which crew members are doing a good/bad job and salaries can be adjusted in consequences. Or adminbus events featuring crisis, global strikes, recession, etc.

Fixes #5014

I'll be away for a few days at my parent's. Feel free to discuss/point out issues in my code. I'll take care of it when i get back. (I might or might not access a computer until Tuesday)

### CODE REVIEW

**Comment by DeityLink** [comment]
The obscene number of lines changed is because I absolute-pathed job_controller.dm

**Comment by dylanstrategie** [comment]
+1037 -665 really isn't obscene for a full rework of a major system like the economy

**Comment by DeityLink** [comment]
@dylanstrategie that's the thing, it's not a full rework yet, I'm only reworking the accounts, I haven't added salaries yet.

**Comment by DeityLink** [comment]
Didn't expect this merged so soon. I guess I'm getting better at it. (or people are keeping their arguments for the PR that adds salaries)

**Pull request merged**
