### PR TITLE
UnRe-adds extended

### PR DESCRIPTION
**Pull request by Manleto**
reverts #29396
I don't like extended 

:cl:
 * rscadd: Extended is no longer back! It canot roll depending on the threat level. If extended is not rolled, antags will spawn in the round until an admin decides so.
 * rscdel: Extended

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
I wouldn't complain if it was less common but I like it, personally. There's a lot of reasons it's good byond just "Long round" too.

**Comment by Manleto** [comment]
> I wouldn't complain if it was less common but I like it, personally. There's a lot of reasons it's good byond just "Long round" too.

Let admins force it when they have some sort of an idea, 99 percent of extended rounds are terrible.

**Comment by TGFH** [comment]
Extended is awful and typically kills the population. It should be bus only or exceedingly rare.

**Comment by west3436** [comment]
Extended rounds are the very definition of soul you cretin

**Comment by Manleto** [comment]
It's not bad faith, I just don't like extended.

**Comment by jwhitak** [comment]
This reverts #29396 to note, a little more* than one month after it was merged. The vote should probably be tossed to a server poll.

Fun facts: There have been 64 extended rounds since then, 30 of which have had additional game modes called into play after round start (admins may have done non-listed gamemode changes in the other ones, such as calling meteors or other busses).

**Comment by ghost** [comment]
I actually agree with manylo, forced extended should not be allowed to roll naturally. "Extended" can happen naturally through Dynamic rolling low threat.

**Comment by DamianX** [comment]
where's the data

**Comment by DrSnips** [comment]
Take your ADHD meds.

**Comment by cmdrstupid** [comment]
I like extended, but I might be in the minority here. It's worth a server poll. More information is always better. If we've had 64 extended rounds, how many is that out of total?

**Comment by Optimism333** [comment]
I like extended rounds provided they don't roll back to back, but I don't know how a solution could be coded that locks extended from rolling two rounds in a row.

Here's a suggestion, though. How about taking a poll to gauge player opinion? Ask whether it's fine as is, if the frequency of extended rounds needs to be reduced, or if they want it removed from rotation unless forced by an admin (like this pr does). 

Edit: Thought some more about this, and I changed my mind. It would be better if the ruleset was left to admin intervention if they have a cool idea for player interactivity or something to spice up the round. I agree with the pr creator, but a poll would still be worthwhile to gauge community opinion.

**Comment by gurfan** [comment]
Ancient summed it up nicely
There have been memorable extended rounds but most are boring. There have been plenty of long, extended-like rounds before extended was brought back.
This should have a server poll also.

**Comment by jwhitak** [comment]
64 extended out of around 410 rounds (this is approximate, I don't know what exact round the extended PR merged on)

**Comment by dunsel-hordon** [comment]
Lets put it this way. 
People that are complaining about extended are fucking brain dead.
Extended is literally BUS THE ROUND.
Git good, do a gimmick, make it a fucking interesting gimmick, and then make it obvious enough to where admin will go along or try a fax or praying.
Or alternatively use extended to learn some new jobs or how to do new shit during the round. Stop just doing the same autistic shit each round.

**Comment by TGFH** [comment]
@dunsel-hordon 
> Extended is literally BUS THE ROUND.

The issue here is that extended rolls by itself. This argument makes no sense when you take that into account. It can (and does) roll when there are no admins to bus anything. Besides, it's not really fair to expect admins to always be ready to bus stuff when much of the time they're probably just alt+tabbed and waiting for ahelps to respond to rather than actively observing.
 
> Or alternatively use extended to learn some new jobs or how to do new shit during the round. Stop just doing the same autistic shit each round.

You don't get an early warning that it's going to be extended. Personally I don't think it's super hard to figure out that it is extended, but telling players "Just metagame and guess the round type, then play around that." is incredibly stupid.

**Comment by DeityLink** [comment]
I like extended rounds, but imo it shouldn't fire more than once a day at most (just like cult lmao)

**Comment by Blithering** [comment]
I feel low threat rounds are extended enough to encounter in the day to day. Having the round roll extended on top of that just makes it more tedious. If an admin wants to bus he can set the round type manually, rather than having it roll when there's noone around to bus or noone has any ideas to fill the dead air.

**Comment by DrSnips** [comment]
There's also the reverse of that. "If the round already has antags or are planned to happen then I don't need to force the round into extended as they're still alive/could be selected and will make the round something."

**Comment by slightly-floating** [comment]
\>All five sec members kill themselves in the brig within an hour and log out

lol. Extended.

**Comment by BomberBro** [comment]
Extended should just straight up not fire during sub 25 player rounds, that's really the line where extended stops being a player driven event with lots of admins on and becomes instead the millstone which hangs about the neck of veegee station.

**Comment by Manleto** [comment]
> 64 extended out of around 410 rounds (this is approximate, I don't know what exact round the extended PR merged on)

How long do those rounds last?

**Comment by slightly-floating** [comment]
> I like extended, but I might be in the minority here. It's worth a server poll. More information is always better. If we've had 64 extended rounds, how many is that out of total?

A server poll where the people that would vote to remove it aren't even playing.

**Comment by KillFurries** [comment]
@dunsel-hordon 
> People that are complaining about extended are fucking brain dead.
> Extended is literally BUS THE ROUND.
> Git good, do a gimmick, make it a fucking interesting gimmick, and then make it obvious enough to where admin will go along or try a fax or praying.

How the fuck would I know that it's extended and admins will now bus in things for me? Not everyone is in the discord metacomming with admins. I am supposed to telepathically realize that there are no antagonists and nothing will happen so I need to come up with some gimmick and bother admins about it until they make the game interesting? You're straight up saying that extended is dogshit because the only way to make it interesting is bothering admins and forcing them to make it not extended.

**Comment by calzilla1** [comment]
Extended rounds are fun because they're a litmus test on how people react if there's no motivator to push people, letting them roam on their own; let them do what makes them happy. Which apparently is to turn the station to complete and utter fucking anarchy because ho-lee-shit does extended rounds feel the most batshit insane. Wizard and revs have nothing on the gunk caused by sheer _boredom_

**Comment by SnakeEater14** [comment]
Extended has been fucking awful. We already had de facto extended with low threat rounds, adding official extended on top of that has just been dreadful.

Everyone who talks about how extended is always chaos and gunk city only remember the extended rounds with 30+ pop. That is far beyond the norm. 

Most extended rounds have sub 15 by the middle of the round because people catch on that nothing interesting is happening and log off.

And while security players killing themselves due to nothing happening is a meme and makes them look shitty, I can’t really blame them. Being a security officer on extended when there’s only 6 other people on the station is the most boring shit imaginable. I’ve resorted to alt tabbing and reading Kate Chopin stories while sitting at the brig desk, waiting for something to happen.

Extended fucking sucks man

**Comment by Dacendeth** [comment]
if loose catbeast didnt exist we wouldn't need forced extended rounds and could actually have low threat rounds where nothing happens naturally every now and then.

**Comment by DeityLink** [comment]
Actually I'm gonna try my own PR to fix Dynamic in a moment. It's an idea I've mentioned several times but never actually applied.

**Comment by ShiftyRail** [comment]
Fine, you will get your data you Dumbos.

**Comment by ShiftyRail** [comment]
An extended round happens about once every day or every two days. It's arguably too much. It's also comparable to what extended rounds used to be before the 31/11/2017, at a time of higher pop (and better players). It also had a much greater randomness and could fire indiscriminately, even in high pop rounds, even three times in a row.

extended

/vg/ didn't die then. I'm not sure if this is the cause /vg/ is dying now. Maybe we have different players who enjoy different things.

I'm going to see what I can do to make it happen less often or maybe not as much in a row - maybe make the serb remember the last time it rolled extended ?

I'm not going to merge this without a server vote anyway. If I were facetious I would reply "just man up and play the game". Roleplaying and interacting with non-antag is also part of ss13.

**Comment by DeityLink** [comment]
I'm offering some alternative/additional tweaks to the way Dynamic picks its ruleset which should help not only Dynamic but other rulesets from hogging the spotlight #29753

**Comment by SootyBear42** [comment]
The only time extended should role is if the jannys are gonna actually do something with it.

**Comment by Blithering** [comment]
@DrSnips 
>There's also the reverse of that. "If the round already has antags or are planned to happen then I don't need to force the round into extended as they're still alive/could be selected and will make the round something."

You could wait til next round and force extended for it, having it roll randomly isn't a good idea because it relies on admins being online and ready for bus whenever RNG decides, rather than just letting the admins set it up as and when.

**Comment by Manleto** [comment]
I'll work on something else but I still think this should have a server vote given that people who are banned (like toomy) are voting in clearly bad faith.

**Comment by gurfan** [comment]
good idea once again ruined by manylo

**Pull request closed without merging**
