### PR TITLE
Replaces borer sprite with a multidirectional one made by Blithering

### PR DESCRIPTION
**Pull request by Gef21**
thanks mr blithering

### CODE REVIEW

**Comment by 9600bauds** [comment]
[Sprites PR without pictures]

**Comment by Gef21** [comment]
it's the same sprite it just spins around a little http://i.imgur.com/s4tIxtf.png

**Comment by Kurfursten** [comment]
Wouldn't it make more sense to take a cue from the lizard sprite on demonstrating direction?

That is to say, when everything else faces south, it is facing the "camera". We don't have upside down humans.

**Comment by Gef21** [comment]
bay has them like that and it looks really bad http://i.imgur.com/eobiCyb.png

**Comment by kol1th** [comment]
The bay one looks fine tbh

These look awful

**Comment by Exxion** [comment]
Both look bad
Let's try a 3/4 view

**Comment by Aurx** [comment]
Fuck that, let's just resprite everything and make SS13 isometric.  Iso is love.

**Comment by Probe1** [comment]
Yeah nerd redo the entire codebase

**Comment by Gef21** [comment]
okay yeah I'll get right on that haha http://i.imgur.com/uk1quSD.png

**Comment by Probe1** [comment]
Borers need in hand sprites but that's not your fault.  Consider doing that for your next project.

**Comment by Probe1** [comment]
Also bays sprites aren't spectacularly better, don't have animation, and you didn't make a PR for them.  If you think you have better sprites then go for it we're open all night.

**Pull request merged**
