### PR TITLE
Random job will no longer give you head roles

### LINKED ISSUE #9879: Add a "Random job" and "Random job excluding heads" setting for job preferences
https://www.youtube.com/watch?v=mVQ_GhCq_1c

### PR DESCRIPTION
**Pull request by kol1th**
Fixes #9879

### CODE REVIEW

**Comment by ComicIronic** [comment]
What about players who want to be able to roll a head as random? The feature request was for having the choice.

**Comment by ghost** [comment]
@ComicIronic I read into the code and it was actually intended that you could not get head if you randomed, but some ancient job refactor didn't implement that - look into getrandomjob() in the same file.

**Comment by ComicIronic** [comment]
Looking over this again, I question if this fixes it at all. The assignment for head roles in that loop is done with `CheckHeadPositions`, which picks random players to go in head positions. The only thing you'd be changing is picking for pref-set heads, which is thankfully handled already so this line isn't breaking anything, but it shouldn't be doing anything either. `GiveRandomJob` is called later.

**Comment by ComicIronic** [comment]
And either way, the original issue was a request to have multiple random settings, not to change it so that random rolling would never make you a head.

**Comment by kol1th** [comment]
I couldn't find a way to add a new option to the prefs screen. I blame celt, personally.

**Comment by kol1th** [comment]
Well, this is dead for now.

**Pull request closed without merging**
