### PR TITLE
Slime humans now heal from electricity

### PR DESCRIPTION
**Pull request by Zth--**
This is a big buff for a shit mutantrace.
If shock_damage (from powernet) is 100, then the slime human will heal 50 brute and 50 burns.

You would say this is too OP, but really, it's damn easy to kill a fucking slime human.

http://ss13.moe/wiki/index.php/Races#Slime_People

**tested, it works**

### CODE REVIEW

**Comment by AutismSpider** [comment]
yes all it takes is a cup of water toss on them like a grey for toxin damage/cold temps

**Comment by Probe1** [comment]
ok sure.

**Comment by Zth--** [comment]
why DNM tag?

**Comment by AutismSpider** [comment]
This better be good if it got the dnm

**Comment by clusterfack** [comment]
@ririchiyo You shit say something before you add the label

**Comment by ghost** [comment]
Being able to overheal as a slime by just syphoning from the powernet when?

Could be interesting to see electricity junkies hopped up on an entire SME's worth of energy

**Comment by Hoshi-chan** [comment]
If you're going to make them heal ludicrous amounts just by touching exposed wires with power in the grid, you should make them unresponsive to normal means of healing, the way that you wouldn't heal a robot limb with a bandaid.

**Comment by Shadowmech88** [comment]
I don't think that's necessary. Slimepeople were pretty worthless balance-wise until this.
Sure, they can heal a lot of brute and burn just by touching a wire now, but you can still freeze them to death by spraying them with a fire extinguisher or splashing them with water.

**Comment by Zth--** [comment]
They already can't enter cryo without dying

**Comment by ghost** [comment]
Also would help when you get sprayed in xenobio and you're probably near the liver damage threshold.

**Comment by gbasood** [comment]
Okay here's my only balance concern
How easy would this make it for a slime person to hack? Normal people would need gloves or they'd risk death, but slime people wouldn't

**Comment by AutismSpider** [comment]
@gbasood acting like we have round start slime people takes bit of time to get green slime core by then all the good shit is gone any way

**Comment by Shadowmech88** [comment]
@gbasood 
Golems currently have that ability. They're impervious to burn damage, including what they would receive from electrocution.

**Comment by gbasood** [comment]
We'll try it out I guess

**Pull request merged**
