### PR TITLE
Removes the generic newscaster channels

### LINKED ISSUE #13404: Remove fake newscaster channels
They're not interesting, nobody reads them, they condition players to ignore newscaster beeps, and they make newspapers worse/less likely to be used because you need to click past them to get to player-made content.

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Wholesale feature removal of the default newscaster channels (Tau Ceti Daily and Gibson Gazette).

## Why it's good

As mentioned in #13404, these are rarely (if ever) used by admins, their random article generating function rarely seems to work, and they just take up space in newspapers that could be filled with actual articles from player-made channels.

Closes #13404.

## Changelog

:cl:
 * rscdel: Removed the generic newscaster channels.

### CODE REVIEW

**Comment by SonixApache** [comment]
my bay
my SOUL

**Comment by SacredAtom** [comment]
Fix it instead of removing it

**Comment by west3436** [comment]
> Fix it instead of removing it

I don't have time to do that - happy to close this if somebody else makes a PR to fix it.

**Comment by BomberBro** [comment]
Editor Mike Hammers is out of a job. If I can give a suggestion how about one of them is kept and uses those PDA news messages that NOBODY reads.

**Comment by Kurfursten** [comment]
Someone has a half-baked implementation leftover in the code where there were supposed to be trade events reported in the news that would affect cargo requests. Too bad it never got done.

It's true that nobody reads these, it'd be nice if there was a single automated news channel that had some interesting news that DID affect the round...
> Beware - METEORS IN YOUR AREA on the rise!

or even better, automated reporting... (obviously inferior to true journalist reporting)
> The grid check today lasted 76 seconds [picture of random crewman standing in dark]

**Comment by Inorien** [comment]
fuck off

**Comment by Inorien** [comment]
no
if anything this feature should be properly expanded

**Comment by west3436** [comment]
Going to close this and the associated issue - maybe someday an ambitious coder will rework these.

**Pull request closed without merging**
