### PR TITLE
Outfit datums : death commandos

### PR DESCRIPTION
**Pull request by ShiftyRail**
[system]
Something I got motivated to do again. Doesn't take too much effort and it's interesting enough to code.

Convert the death commando `equip` proc to use an outfit datum. In time, I want the custom strike team outfit datum to be entirely designed by the admin who created it.

The target branch is `outfit datums` because the outfit datum "update" should be all in one.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Oh, and for the ease of review, just look at the last commit.

**Comment by boy2mantwicethefam** [comment]
bro you'd be better off just copypasting the changes on a brand new branch

**Comment by ShiftyRail** [comment]
I don't want to clutter the repo with another useless branch.

**Comment by boy2mantwicethefam** [comment]
well first of all you can delete the branch when it gets merged, or if that can't be done ask pomf
second of all everyone's just made a clone of the repo and made branches off the clone to compare them to the og repo without making branches off the og repo itself

**Comment by utilitas-** [comment]
\>files changed: 6,115

**Comment by ShiftyRail** [comment]
It's called rebasing.

**Comment by ShiftyRail** [comment]
image

It works

**Comment by ShiftyRail** [comment]
Weird, it compiled on my machine
It's not Travis acting up, it's the icon diff bot ; probably because of the 3000+ commits diff

**Comment by ShiftyRail** [comment]
Please merge this one so another, easier to review PR can be put up.

**Pull request merged**
