### PR TITLE
fixes #14642

### LINKED ISSUE #14642: There is no sprite for the new capsule sold in the tradervend
It is invisible in game, and I have only been able to pick it up via alt-clicking a tile.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Kurfursten**
fixes #14642

### CODE REVIEW

**Comment by SonixApache** [comment]
meaningful title, fixes #x in description
commit message also sucks but whatever

**Comment by SonixApache** [comment]
god damnit pjb

**Comment by Kurfursten** [comment]
You can cursor over the issue number to see what it fixes

**Comment by SonixApache** [comment]
you can't mouse over the number in the title, and that's not the point
image
this shit is annoying in the history

**Pull request merged**
