### PR TITLE
Immunity Scanner tweaks and more in-hand icons

### LINKED ISSUE #23695: Immunity Scanner Has no tech levels
(WEB REPORT BY: robosperg REMOTE: 206.221.180.138:7777)
# Revision
dbe01311cf0a9af1b10c0505a7c697f6fb0c8938

# Description
The device analyzer can't seem to scan the immunity scanner!

### PR DESCRIPTION
**Pull request by DeityLink**
image

Fixes #23695

:cl:
* imageadd: Added in-hand icons for growth dishes.
* imageadd: Added in-hand and belt icons for the health analyzer and the immunity scanner.
* tweak: Tweaked the immunity scanner's properties so they align with health analyzers' (now a tiny item instead of small, can now be worn on belts, can be recycled at an autolathe and deconstructed at R&D, etc...)

### CODE REVIEW

**Comment by MadmanMartian** [comment]
Can they be added to the things that can hold health analyzers, like the medbelts, lab coats, etc?

**Comment by DeityLink** [comment]
@MadmanMartian to medical belts yeah, to labcoats no as I just found out. Now fixed.

**Comment by robosperg** [comment]
closes #23695

**Comment by SonixApache** [comment]
How do you make all these inhands? Just drawing?

**Comment by DeityLink** [comment]
@SonixApache the health analyzer had an unused inhand icon in a .dmi, but it was missing some directions and ugly in others so I fixed it up, then slightly modified it for the antibody scanner. For the virus dish I used the "small dish" sprite that also appears on the disease analyser.

I use Gimp with layers with the default human sprite from human.dmi to move the item in a pleasing/relatively identifiable location, and erase pixels that should be hidden.

The process of creating the sprites for the other hand is the easiest part. Takes about 10 seconds:
flip

**Pull request merged**
