### PR TITLE
Revert "Sanitizes Github, So we can get public access again." because we didn't even get public access again

### PR DESCRIPTION
**Pull request by Cartlord**
Reverts vgstation-coders/vgstation13#34400
Not much to say. The original removed a bunch of identity so we could get listed again, not bothering to just put it in defines - and then we didn't even get listed.

### CODE REVIEW

**Comment by angryturnip** [comment]
fartlord

**Comment by BomberBro** [comment]
fartlord

**Comment by tinysaturn** [comment]
based fartlord

**Comment by nervere** [comment]
Pomf only just recently contacted GitHub. This takes time, could take weeks.

**Comment by pedr69** [comment]
yeah it's been 10 days now and us gamers are still opressed

**Comment by PrimeDSS13** [comment]
fartlord

**Comment by SonixApache** [comment]
fuck off

**Comment by kacurasuo** [comment]
fartlord

**Comment by Inorien** [comment]
fartlord

**Comment by djkramer123** [comment]
fartlord

**Comment by Irradiation** [comment]
fartlord

**Comment by Exxion** [comment]
Bro can you at least wait for them to give a response

**Comment by Servalfang** [comment]
fartlord

**Comment by d3athrow** [comment]
fartlord

**Comment by Eneocho** [comment]
basedlord, but yeah, at least wait first

**Comment by Irradiation** [comment]
https://i.4cdn.org/vg/1688135414240064.png

**Comment by d3athrow** [comment]
[fartlord](https://i.4cdn.org/vg/1688135414240064.png)

**Comment by Irradiation** [comment]
yey

**Comment by Pastamadness** [comment]
Upvotes are winning therefore you must merge this!
edit: nvm
edit ii: thanks for the gold, kind stranger!

**Comment by ValkyrieSkies** [comment]
🤡

**Comment by DeityLink** [comment]
Nothing of value was lost, and certainly not any "identity"

**Comment by d3athrow** [comment]
*fart

**Comment by Hinaichigo** [comment]
Time will tell, was it worth it?

**Pull request closed without merging**
