### PR TITLE
forces extended on castlestation again

### PR DESCRIPTION
**Pull request by gurfan**
While forced extended on castlestation was a bug, I felt that there have been good rounds even without any antagonists, and I think a few people seem to agree. 

[vote]

:cl:
 * tweak: Castlestation has been dragged back into extended hell.

### CODE REVIEW

**Comment by juanototo2** [comment]
Nah, man. I want nukeops on castle.

**Comment by TGFH** [comment]
/verygay/

**Comment by Kurfursten** [comment]
Created server poll due on 22nd

**Comment by Kurfursten** [comment]
56/44 vote against

Pretty close, too bad there's no way to compromise on this

**Pull request closed without merging**
