### PR TITLE
Adds roombas, adds attack roombas

### PR DESCRIPTION
**Pull request by ghost**
Adds roombas, constructable out of 5 sheets of metal, a bucket, and a prox sensor, functionally a clone of the cleanbot

They glide around the station, cleaning messes, and potentially pinching peoples ankles if you attach a fork and a lighter to them

Sprites and idea courtesy of @Blithering 

roomba

:cl:

* rscadd: Adds roombas, constructable from a bucket, a prox sensor, and 5 sheets of metal

### CODE REVIEW

**Comment by diammz** [comment]
make them stop for a moment and rarely break completely when people step on them

**Comment by Riekland** [comment]
>functionally a clone of cleanbots
OH NO
I thought it was agreed that no new bots would be added until some brave soul fixes the bot code?

**Comment by clusterfack** [comment]
Does it drive around like a roomba actually does? In random directions and circles?

**Comment by Probe1** [comment]
God I hope not I don't wanna imagine the astar overhead.

speaking of which now I want bots to spam CALCULATING ROUTE in a neutral female voice every time they move.

**Comment by Exxion** [comment]
@Probe1 
But... that wouldn't use A*

**Comment by Probe1** [comment]
Won't it?  Hows it going to get a path to messes?

**Comment by Shadowmech88** [comment]
It *won't* get a path to the messes.
The way an actual Roomba works is it just moves around the room bumping into obstacles, and eventually it covers the whole floor that way. But it doesn't actually aim for messes.

**Comment by PJB3005** [comment]
A roomba basically mows your law. Except the law is your living room and it only mows up messes.

**Comment by Probe1** [comment]
Yeah I know what a roomba is I just didn't think it was going to be re-created 1:1 since you know.. why would you when we have something better.  But hey whatever lets do it.

**Comment by Shadowmech88** [comment]
Maybe roombas could move much faster than cleanbots to compensate for the fact that they don't target anything.

**Comment by ghost** [comment]
Conflicts hopefully resolved

**Comment by Probe1** [comment]
@Skullyton are you planning on going for the ideas suggested here, or just sitting happy on the initial implementation?

**Comment by ghost** [comment]
Well, most would involve making it its own bot, which as was said by @Riekland is a nono until somebody fixes botcode

diammz is totally doable, where if somebody crosses the floorbot it could just shudder for a moment

**Comment by Blithering** [comment]
If this gets reworked later into it's own bot, It would be cool  to be part mulebot, allowing Ian or Runtime to ride it while it cleans.

**Comment by AutismSpider** [comment]
Can't you make pai slot for the roombas and a knife slot?

https://www.youtube.com/watch?v=-cD4mrTvVhM

**Comment by ghost** [comment]
You can already attach a fork and lighter to them.

I'll look into pAI slots, didn't want to go unatomic

**Comment by Probe1** [comment]
You can get to that in a new PR.  Lets not sit in hell.  

Also we have janiborgs and janitors, yo.  

Make sure the wiki gets updated.

**Comment by Zth--** [comment]
Please update the wiki

**Comment by ghost** [comment]
roomba

**Comment by ghost** [comment]
Changes made, sorry for the delay

**Pull request merged**
