### PR TITLE
Fixes POS products view, Prevents charging below the lowest denomination, and other tweaks/fixes

### PR DESCRIPTION
**Pull request by WhiteHusky**
Fixes POS' since all products use strings as their key and not numbers, causing the mod operation to not work.

Also prevents charging below the lowest denomination
image
And adds ingame explanation on how the subtotal and taxes are calculated.

There's now a define going by `LOWEST_DENOMINATION` for the lowest denomination we have in the game along with `round_to_lowest_denomination` to help make sure other machines don't use factions of our lowest denomination.

:cl:
* bugfix: POS' product views now work.
* bugfix: POS' no longer charge below the lowest denomination
* bugfix: POS' now prompt if you want to log out.
* bugfix: POS' now charge the linked account if spacecash is used instead of blackholing the spacecash.
* tweak: POS' now separate the login name like the rest of the other screens.
* rscadd: POS' now make change if the order was canceled

### CODE REVIEW

**Comment by Pathid** [comment]
Does this make it not runtime at all? I recall there being multiple issues with this file. What about logging out, changing settings, etc.

**Comment by WhiteHusky** [comment]
Did more testing and it seems pretty bulletproof at the moment, but encountered one situation where the taxes had a rounding error where it had a repeating number, but given that's something that's seen a bunch of other places for no good reason I'm not going to worry over it.
Anyways, 
image
Fixed the logout.

**Comment by WhiteHusky** [comment]
Also made sure the POS doesn't charge below the lowest denomination.

**Comment by iFlashYou** [comment]
Just remove them

**Pull request merged**
