### PR TITLE
Adds a new bridge officer uniform

### PR DESCRIPTION
**Pull request by Blithering**
Changes the uniform that bridge officers spawn with from a standard blue jumpsuit and coat to a new one.
bridgey
Left is without the jacket, right is with.
:cl:
 * imageadd: Added a new outfit for bridge officers

### CODE REVIEW

**Comment by Riekland** [comment]
this is fancier by far than even the cap's ceremonial outfit
it could do with a little less flair

**Comment by Praecordia** [comment]
i like that it's fancy, BO has no responsibility besides sitting on the bridge and looking nice anyway

**Comment by Orangerush** [comment]
Give the captain that and give the Bridge officer aka B.O. an edited captains ceremonial outfit

**Comment by Blithering** [comment]
I could remove the braid from the BO one and give the captain a version that matches his colour scheme, or I could make bridge officers spawn without the coat and put it in their lockers.

**Comment by Blithering** [comment]
bofficerberet

**Comment by Blithering** [comment]
Hadn't actually made the commit to change the jacket yet, was just putting up a preview to see if people preferred it, I guess I'll open a new PR with the captain jacket and change the BO one at the same time.

**Comment by Blithering** [comment]
In a world with darkblue jumpsuits and lawyer jackets uglying up the bridge

**Pull request merged**
