### PR TITLE
Mechanics have access to the engines

### PR DESCRIPTION
**Pull request by DamianX**
:^)

:cl:
 * tweak: Mechanics can now open the engine rooms airlocks.

### CODE REVIEW

**Comment by SonixApache** [comment]
>doesn't remove mechanics entirely

bad solution to the "mechanics are the only 'engineering' staff but never set up power" issue

**Comment by wotisjanitor** [comment]
just let them hack in. They aren't engineers.

**Comment by mrflarg** [comment]
we have collars, just make them auto spawn when there are no engineers/when there are miners.

**Comment by GreatBigFailure** [comment]
If this doesn't pass I will use it as further excuse not to make engines when asked.

**Comment by Kurfursten** [comment]
Not enough support

**Pull request closed without merging**
