### PR TITLE
An attempt to rework lighting from an hero (WORK IN PROGRESS - DO NOT MERGE)

### PR DESCRIPTION
**Pull request by ghost**
- Objects in container now emit light. Objects in all containers, but it's better than nothing ain't it ?
- Objects in containers properly update light around then when the area is lit, and appreciably updates the lighting level
- This has not broken regular lighting (aka shit not in containers) in any appreciable form from the extensive testing I've done to try and pinpoint the problems so far

Problems :
- Tiles in full darkness aren't updated by objects in containers. Why ? I don't fucking know. It just shits itself and goes "Yeah fuck this everything is equal to 0". Maybe some useless redundant failsafe somewhere is cockblocking everything, because the formulas seem correct
- This seems near-constant. For some reason at odd intervals the tile updates and then just goes pitch black again when the light is moved away. I just don't know

Again, THIS IS A WORK IN PROGRESS AND NOT SUITABLE FOR RELEASE. Why am I PRing this ? To get assistance. Find something odd, send a comment

Also I know about the items with snowflake coding (aka flashlights, mostly) aren't updated yet. They will be once this shit is fixed

### CODE REVIEW

**Comment by dylanstrategie** [comment]
Since I will be off, please do NOT close the PR if shit's broken. It is, I'm just looking for assistance (and naturally Rizon had to find that fucking time to have their security certificate run out)

**Comment by Lokiamis** [comment]
I don't understand why objects in containers would emit light.

**Comment by IratePirate** [comment]
Yeah i'm confused too. If a light is turned on and put inside a crate it would only emit a tiny amount of light at best.

**Comment by Duny-** [comment]
>let's make lighting even more illogical

**Comment by dylanstrategie** [comment]
The goal is to unfuck mobs carrying lights. Picking up something as a mob puts it into your "container". The amount of snowflake coding is borderline

I'll close this, I just don't remember where I went with this. Seemed like a good idea at some point

**Pull request closed without merging**
