### PR TITLE
Readds controversy

### PR DESCRIPTION
**Pull request by Aurx**
DELICIOUS
FLAT
BLUESPACE

### CODE REVIEW

**Comment by clusterfack** [comment]
No, we've already discussed this here https://github.com/d3athrow/vgstation13/pull/13626, where about half the people disliked it. And instead replaced it with this https://github.com/d3athrow/vgstation13/pull/13715 which had unanimous support.

There is no reason to tread over this topic AGAIN.

**Comment by Aurx** [comment]
Unanimous is a strong word.  

Either way I'll be setting up a serb poll so we can get proper feedback AS SOON AS I CAN FIGURE OUT THIS DOGSHIT UI THANKS [insert name here]

**Comment by clusterfack** [comment]
The flat bluespace could barely compete with what has been described to me as yellow poop, it surely fares even WORSE against a superior sprite.

**Comment by Exxion** [comment]
Fuck off, Cluster.
The PR this reverts was unanimously voted *against*.

**Comment by clusterfack** [comment]
That was some bullshit you faggots were trying to pull to subvert all the prior votes on the topic, after you snuck in the change under everyones noses.

**Comment by BobdaBiscuit** [comment]
Current sprite looks like ass, flat bluespace is objectively better.

**Comment by clusterfack** [comment]
Have you even seen the current sprite ingame yet?

**Comment by Exxion** [comment]
Can you actually point me to a vote that DIDN'T come up in favor of flat bluespace?
Also, #13715 set the sprite TO flat bluespace.

**Comment by BobdaBiscuit** [comment]
Yes I have cluster, it still has eye gouging tile edge issues and is just a mess of triangles, only improvement is it's now blue.

**Comment by clusterfack** [comment]
@Exxion I know it did, and nowhere in that PR did it mention that it would. Which is why we made the PR that this one is trying to revert.

**Comment by 9600bauds** [comment]
I have absolutely no idea where are you getting the word "unanimous" from

You need to have a tea and eat a bagel

**Comment by eplgr** [comment]
This is just awful. The other sprite won (and got voted for, and got everyone believe that was gonna be in game) and you decided to be sketchy as fuck and change it without anyone knowing. Well not you, but you get the point.

And now you want to use every tool at your disposal so you get what you want.
Geez.

This quickly turns in a "I will open as many PRs as I can until I win. Fuck what other people think".
>Let's do a server poll because I didn't win the votes!

**Comment by BobdaBiscuit** [comment]
But flat blue space won in all instances of the emoji meme votes.

https://github.com/d3athrow/vgstation13/pull/13626 had 16 for, 11 against.
https://github.com/d3athrow/vgstation13/pull/13715#issuecomment-276010524 has 11 for 4 against
https://github.com/d3athrow/vgstation13/pull/13744 was a meme pr with 6 votes against it and none for it.
https://github.com/d3athrow/vgstation13/pull/13715 by itself is a general overhaul of the event, not just the sprite.

**Comment by Shadowmech88** [comment]
What about the OP of #13715 that added the textured bluespace sprite, which had 13 votes for and 0 against?

**Comment by BobdaBiscuit** [comment]
That is a overhaul of the event itself with bug fixes since it was broken, not a sprite pr alone.
If you actually looked at the votes 4 people put a thumbs up for the PR itself along with the flat sprite comment n3xis made.

The real solution to this is a poll on the sprite, not bundled with any functionality or bugfixes which you can manipulate to look like what you want.

**Comment by eplgr** [comment]
https://github.com/d3athrow/vgstation13/pull/13715#issuecomment-276010524 was the reason of all the controversy. He did not state he had actually changed anything; personally, I thought of that post as:
*One person says he liked more the old plain blue sprite
*Nexis says "me too" and posts an (probably old?) example
Clearly I am not the only one who had those similar thoughts, or else we wouldn't be arguing about anything. He didn't even update the original post.

It was an extremely misleading situation, you can't just say "people actually VOTED for it".

**Comment by BobdaBiscuit** [comment]
"you can't just say "people actually VOTED for it"."
"The other sprite won"

Really makes you think.

**Comment by eplgr** [comment]
Maybe I was not clear enough, maybe you can't read properly, but I tried to explain why it was a misleading situation (regarding THAT ONE post) and therefore you can't claim that people wanted that sprite because of those votes on that one post.

**Comment by Aurx** [comment]
THIS "NO THEY WANT MY THING" "NO MINE" BULLSHIT IS WHY WE'RE HOLDING A SERVER VOTE, RETARDS.
Now shut the fuck up and make your vote heard.

**Comment by 9600bauds** [comment]
You say https://github.com/d3athrow/vgstation13/pull/13715#issuecomment-276010524 was the source of the controversy but whether anything was silently changed in the PR or not, that's still 11 to 4 people who prefer the classic sprite to the new one

**Comment by Shadowmech88** [comment]
11 to 4 out of those who voted. I'm sure a lot of people, like myself, didn't view that comment as "Hey by the way guys I've decided to make the sprite look like this again" and so didn't bother putting an emoji on that comment at all.

**Review by PJB3005 — APPROVED** [review]

**Comment by Aurx** [comment]
Should link the poll.  
http://ss13.moe/index.php/poll/89

**Comment by clusterfack** [comment]
@9600bauds The sprite rework that changed the sprite to the textured bluespace had zero opposition to it whatsoever. Nobody disliked it.

Only then a few days after that Nexis changed his PR to the old flat bluespace without telling anyone and posted it in his PR like 'personally I preferred this'. I can really only conclude they were trying to do some conspiratorial nonsense just like how they all downvoted the PR to change it back to what he actually said he did in the OP.

**Comment by Intigracy** [comment]
Let's just wait until we see how the poll turns out, since this is purely a cosmetic change.

If it ends up 50-50ish we'll just ask pomf to pick.

Holy shit this is being made way more of an issue than it should be.

**Comment by Boxe** [comment]
give it the space tile sprite instead

**Comment by optimumtact** [comment]
it's good to know that vg can also bikeshed

**Comment by ghost** [comment]
here's a bluespace tile thing I made in case anyone thinks it's a better alternative
bluespace

also transitions from tile to tile seamlessly

**Comment by 9600bauds** [comment]
@Optimumtact Bikeshedding is our favorite passtime, our national sport, and our spirit animal.

**Comment by Exxion** [comment]
I still like the flat one thematically and also due to references
But that one is by far the best alternative, @unusualcrow

**Comment by BlueNexus** [comment]
How about using Baystation's bluespace sprite?
jstwogb

**Comment by Exxion** [comment]
That sprite is what started this whole fucking shitshow

**Comment by Aurx** [comment]
Poll has concluded.  Vote was for blue crystals.  
If anybody particularly feels they want one of the sprites proposed since the poll was created, they can make a poll or get somebody to make one.  

Exxion, that's nothing like the sprite that "started this whole fucking shitshow".

**Comment by Exxion** [comment]
Yes it is
In the Discord
The first PR wasn't opened for no reason, you know

**Pull request closed without merging**
