### PR TITLE
Red Ribbon Arm

### PR DESCRIPTION
**Pull request by Shadowmech88**
red_ribbon_arm
Adds a new item, which can be equipped in the belt slot in order to give a mob an additional hand slot.

Not sure how it should be obtainable. Wizard artifact, maybe?

### CODE REVIEW

**Comment by jknpj** [comment]
Wait, i got this one.

04-thirdarmsash

**Comment by Shadowmech88** [comment]
Any resemblance to existing fictional pseudo-appendage garments is purely coincidental.
As you can clearly see, mine is red.

**Comment by Gunosaguki** [comment]
Ignoring my interest in xenoarch. it feels like a possible artifact, maybe a "large" artifact similar to how stone mask and changeling vial are

**Comment by Kurfursten** [comment]
Yeah, this isn't a reference to anything at all.

maxresdefault

**Comment by ghost** [comment]
make it a traitor item so that you can meme with three shields as an OP
Hell you should make it an illegal tech for R&D that also requires biological research so that people don't valid you as soon as they see it

**Comment by Gunosaguki** [comment]
make it require anomaly research! Make anomaly research actually used for something

**Comment by Blithering** [comment]
I'd say include it in the wizard room loot tables
Also is the hand granted by wearing this item still usable while cuffed? Would it be usable while restrained with the belt?

**Comment by Gunosaguki** [comment]
wizard room loot table would be nice. all the "room" loot tables honestly need touching up since they vary so little

**Comment by Shadowmech88** [comment]
>Also is the hand granted by wearing this item still usable while cuffed?

Being cuffed disables *all* hands, no matter how many you have.

>Would it be usable while restrained with the belt?

The belt only works while it's equipped in your belt slot.

**Comment by SonixApache** [comment]
status?

**Comment by Shadowmech88** [comment]
I still need to make it obtainable somehow.

**Comment by SonixApache** [comment]
that's always an afterthought

**Comment by Gunosaguki** [comment]
Yeah you can still make it admin spawnable for the time being.

**Comment by SonixApache** [comment]
okay, ideas for obtaining

put it in the clothing safe spawner @spawners/spawners.dm#L1151
or tie it to a voucher that you can use at clothing vends and put that in the clothing safe spawner

Or put it up for sale at spessmart.

Or make it a wizard artifact. That seems fine. Would be fun to get with summon magic.

Or go full retard and make it craftable from a toolbelt, a human arm and a human hand.

**Comment by Gunosaguki** [comment]
might be a bit too easy to access if its in the safe, . wizard artifact or xenoarch artifact seems to be the best options at the moment

**Comment by Shadowmech88** [comment]
I was thinking a Xenoarch small artifact, like the happiest mask is.

**Comment by Intigracy** [comment]
👌 👌 👌

**Comment by Shadowmech88** [comment]
I forgot to add a changelog.

**Comment by SonixApache** [comment]
quick, make a new PR with a changelog

**Pull request merged**
