### PR TITLE
wizborg

### PR DESCRIPTION
**Pull request by SonixApache**
borgs with wizard brains now get access to a wizborg sprite
draft and on hold until someone can tell me where these sprites are stolen from and if the licensing is ok
dreamseeker_2020-06-25_22-17-58

TODO:
 - [ ] figure out licensing
 - [ ] swap order so wizborg is first option

### CODE REVIEW

**Comment by Gazathor** [comment]
is this so we know which borg has bound object and blink on the crew

**Comment by SonixApache** [comment]
it's mostly because jknpjr posted the icon and said "someone should add this to wizborgs"

**Comment by Blithering** [comment]
At this point it might be faster to remake the sprite ourselves.

**Comment by DamianX** [comment]
Scream for this to be reopened once you figure out the license.

**Pull request closed without merging**
