### PR TITLE
Restricts weighted map voting with configurable filters

### PR DESCRIPTION
**Pull request by ComicIronic**
There is an option to disable this filtering.
This stops players putting down a vote for a single map and that winning when there are multiple choices.
Filters include a minimum share of total vote filter, and a minimum vote rank filter.

The code is currently set to remove options with less than 10% of the vote.

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
Didn't we implement weighted voting so that we would play a map that isn't Box?

**Comment by Shadowmech88** [comment]
Yes, and it does that.
But what if 30 people want to play Metastation, and only 1 person wants to play Busstation? Should that 1 person be able to override the majority just because we have weighted voting?

**Comment by SysadminJeroen** [comment]
@Shadowmech88 The chance of that happening is once every 31 votings.
Look at weighted voting like this.
- Everyone places their votes in a box.
- System picks a random vote from the box

**Comment by ComicIronic** [comment]
Weighted voting has revealed its main issue to be that very small groups can swing the vote, which means that even if you have a big group of people who want to play a non-Box map, you can end up in a situation where nobody is happy.

This doesn't remove weighted voting, it just restricts the way it works.

**Comment by ScrambledSteak** [comment]
restricting votes is a violation of democracy
are you some kind of commie fuck?

**Comment by Shadowmech88** [comment]
Weighted voting itself was already a violation of democracy. It removed the ability of the majority to rule.

**Comment by kol1th** [comment]
I mean, it just happened where 2 votes outweighed 15+.

Good fix :+1:

**Comment by Shadowmech88** [comment]
Weighted voting is the reason we've played the least-liked map SIX times in a row now.

**Comment by ihadtoregisterforthis** [comment]
The lack of weighted voting is why we played box for entire days in a row

**Comment by Shadowmech88** [comment]
I'm not saying to remove weighted voting.
But it's stupid that a couple people can fuck everyone else over like this.
Excessively small win percentages should be outright ignored.

**Comment by SysadminJeroen** [comment]
"Excessively small win percentages should be outright ignored."
If we are going to make a threshold, how high will we set it?
1 vote? 2 votes? 10%? 33%?

This also means that if a map wins of which 1 player voted for, and 30 players voted against... it means that there was a 3.33% chance of that map vote winning.

**Comment by ComicIronic** [comment]
The threshold is currently set to 10%.

> The lack of weighted voting is why we played box for entire days in a row

Which you dislike but the majority wants.
I remind you all that this is a server and a codebase that you share with other players. We do not have map variety just because that is something to strive for.

**Comment by Probe1** [comment]
What Comic said.

1 person voting Deff opposed to 30 and Deff wins is not a good design.  Especially when people leave.

**Comment by Exxion** [comment]
So uh
Since when did people support this?
Because last time it was suggested, the person who did so got memed on ULTRA hard
#7897
And a bonus: #9642

**Comment by Probe1** [comment]
@Exxion I think intigracys implementation was flawed because it fucks over lowpop or when the vote doesn't pop up.  a % is a better choice.

I won't lie right here - my straight up answer to people that want 1 person to choose the map is this:  Fuck em.

We drop players because of these shenanigans.  People have a worse time because one guy thinks its funny.  The system does not work well enough and should be improved exactly as this PR improves it.

**Comment by SysadminJeroen** [comment]
As suggested somewhere else, how about hiding total number of votes and total votes?

**Comment by clusterfack** [comment]
I'm literally going to bring back randomized maps if you guys start restricting weighted voting like this

**Comment by ComicIronic** [comment]
But why?

This lets players continue to use weighted voting when there's the chance of a non-Box map making it without the hate for a map with very few votes actually succeeding.

I don't understand this obsession in the first place with forcing players to play maps they don't enjoy. This is a game for the playerbase.

**Comment by clusterfack** [comment]
Because it's arbitrary nonsense. If 1/10th of the playerbase wants to play a map we can play it 1/10th of the time.

If your argument is that people are troll voting or that 'winning by 1 vote is awful' then make the vote done by secret ballot.

**Comment by ComicIronic** [comment]
But secret ballot would just hide the issue. I don't object to the idea of players KNOWING a map won with 1 vote, I object to the idea that you can have a system which encourages map variety and then still leaves the overwhelming majority unhappy because a map can win by one vote.

Unpopular maps kill the server, because people refuse to play them. What's wrong with the current situation is that you can go 50% Box, 49% Meta, and 1% Bus, and Bus can win out, even though there is 99% disagreement with it and Meta would be the far better choice if you want to force variety on players.

This has been blatantly demonstrated by the rise of troll voting.

**Comment by clusterfack** [comment]
That's a terrible argument 'oh no it might make the majority angry', having playtime on maps proportional to the amount of people voting for them is **literally the goddamn point of the weighted voting system**

**Comment by ComicIronic** [comment]
Which is part of the reason I think it's a terrible system, but weighted voting on its own hasn't provided a solution to the problem of malicious votes.

My point is that you can ensure map variety without picking a situation where nobody is happy.
Like I said, we should be doing map variety for the reason that the players want it, not just because it's one of the things you feel like we should do.

**Comment by clusterfack** [comment]
Secret ballot would already solve the problem of 'malicious voting'

**Comment by ComicIronic** [comment]
How

**Comment by clusterfack** [comment]
Because no one would even know who voted for what, there's no trolling someone with 'oh I'm the single person who voted for bus'

**Comment by ComicIronic** [comment]
Which won't stop one person voting for Bus anyways just to have the mapvote roll it.

**Comment by clusterfack** [comment]
I guarantee you, hide the votes cast and no one will fucking care

**Comment by ComicIronic** [comment]
I think that's highly naive - people are likely to announce their votes in OOC anyways, and it's not unlikely that the vote for an unpopular map is going to only be one or two people.

Really though, you're missing the point that the issue is that a map is able to win thanks to a concentrated malicious minority rather than people knowing who that minority are.

**Comment by ghost** [comment]
I agree with cluster here.

**Comment by ghost** [comment]
As an addendum though; we really need to check that the code actually produces weighted results.

**Comment by Probe1** [comment]
@clusterfack People vote by participation.  When deff wins multiple times in a row because 1-2 people voted for it out of 30, others leave.  Having variety and weighted voting is okay.  Having people bail because maps only a single guy wanted win isn't.

I'm not sure why we're even arguing about this.  It's setting a minimum to be considered which should have been part of the package when it was first coded.  It does not improve the server / player experience to have one guy troll everyone else and drop players because of it.

When the options are keep doing something that hurts the server or tweak it then there isn't another option.  Tweak it so it works better.

**Comment by clusterfack** [comment]
>When deff wins multiple times in a row because 1-2 people voted for it out of 30, others leave.

When deff wins 10% of the time because 10% of the people vote for it they are getting their proportion of the playtime on the map they WANT TO PLAY.

**Comment by Probe1** [comment]
10% of the players aren't voting for Deff and if they were then the code suggested would not be a factor in map selection.

**Comment by clusterfack** [comment]
When deff wins x% of the time because x% of the people vote for it they are getting their proportion of the playtime on the map they WANT TO PLAY. 

This is the point of weighted voting.

**Comment by Probe1** [comment]
Lets crunch numbers.  Here's the raw data of map votes from the last week.  http://pastebin.com/vT5au5mJ

I'll be back.

**Comment by Probe1** [comment]
http://pastebin.com/W0ftG5d8 Listing of all votes where Deff won from the previous week.

There were 118 rounds this week.
Box won 73 times
Metaclub won 8 times
Deff won 10 times
Bus won 26 times
Hogwarts won 1 time [16:05:35]VOTE: <b>Random Weighted Vote Result: Hogwarts station 13 with 12 votes and a 92% chance of winning</b><br>    Fuck off prae had 1 vote and a 7% chance of winning
= 117 weighted votes 

Defficiency was available on 82 rounds

Deff wins 12% of the time it is available but on average only receives 11% of the average votes.

I'll now look back before Bus was added.

**Comment by Probe1** [comment]
http://pastebin.com/rhgWqvAx Listing of all votes where Deff won from the first week.

May 1st - May 8th

There were 111 rounds
Box won 78 times 70%
Metaclub won 19 times (17%)
Defficiency won 14 times (12%)
Total weighted votes: 111

So what does that tell us?

Deff gets played about 12% of the time.  It doesn't get 12% of the votes.

**Comment by ghost** [comment]
@probe1 where's the stats for the vote percentages?

**Comment by Probe1** [comment]
In the pastebins.

**Comment by clusterfack** [comment]
Looks like its working exactly as you would expect apart from some small statistical variance

**Comment by ghost** [comment]
> Deff wins 12% of the time it is available but on average only receives 11% of the average votes.

I don't see how that's a bad thing. That's a very small margin of error and only occurs over the period of a month and would average out if you took a higher sample. What's the problem?

**Comment by ghost** [comment]
Also you appear to interpret it incorrectly in that you're only taking the votes which defficieny WON and doing analysis on that.

**Comment by 9600bauds** [comment]
Was fixed with the removal of Bus ;^)

**Comment by ComicIronic** [comment]
rip pip this

**Comment by Megamaw** [comment]
maybe if you actually explained why this was a good idea people would support it

as is it just looked like (to me, at least) we were going to play box 100% of the time, which would suck

**Comment by ComicIronic** [comment]
"I object to the idea that you can have a system which encourages map variety and then still leaves the overwhelming majority unhappy because a map can win by one vote.

Unpopular maps kill the server, because people refuse to play them. What's wrong with the current situation is that you can go 50% Box, 49% Meta, and 1% Bus, and Bus can win out, even though there is 99% disagreement with it and Meta would be the far better choice if you want to force variety on players.

This has been blatantly demonstrated by the rise of troll voting."

**Comment by Megamaw** [comment]
idk about you, but whenever I see Box Station, i usually hold off on joining. box is more of the same boring shit I've been playing for like six years.

what you're saying just looks like mere opinion and conjecture, esp. since meta club, if you ask me, blows more chode than bus

**Comment by ComicIronic** [comment]
Troll voting was not conjecture, it was a serious problem at the time this PR was created that was emptying the server due to Bus having issues. 

That's not an opinion, it was statistically happening again and again when one person would vote for the map, especially if they weren't going to play the next round. 

Your opinions on Meta are not relevant to the issue - if you want map variety, it's better to have a system that picks the most-liked map that isn't the main one rather than one which picks a map nobody wants to play.

**Pull request closed without merging**
