### PR TITLE
Jukebox Mapping

### PR DESCRIPTION
**Pull request by GermanSanta**
🆑

objadd: Adds a Holy Jukebox to Chapels.

### CODE REVIEW

**Comment by GermanSanta** [comment]
holyjuke

**Comment by Servalfang** [comment]
watsit do

**Comment by WindowsErrors** [comment]
if you emag it do you get to play powerwolf

**Comment by Eneocho** [comment]
>watsit do

The holy juke plays a dedicated list of religious-themed music. See here: http://ss13.moe/media/source/holy

**Comment by GermanSanta** [comment]
> watsit do

Plays religious based song instrumentals I edited/remixed to sound better. 
Includes a variety of religions such as Christianity, Islam, Clownism etc.

**Comment by Eneocho** [comment]
The themes are:
Adminism, America, Capitalism, Christianity, Clockwork Cult, Clownism, Dorfism, Elder Scrolls, Evolution, Homosexuality, Islam, Judaism, Medbay, Mimeism, Slamism, Toolboxia and Vampirism.

**Comment by ghost** [comment]
can this be a premium coin item

**Comment by Hinaichigo** [comment]
> if you emag it do you get to play powerwolf

It'd be cool to have cult jukeboxes too with demonic/goth choral, and dark synthwave type music.

**Comment by Kurfursten** [comment]
Did you test this to make sure the sound plays in the right room? As in not just in the chapel.

Flatpacks often have a problem with the machine being made where they were vended. You need to vend one, move the flatpack to the hall, open it up, and see if it works correctly.

**Comment by jwhitak** [comment]
I have given pomf an mp3 for Primitivism. If this is merged, we can now unga in the chapel.

**Comment by Eneocho** [comment]
You'd have to add the primitivism song to the playlist though.

**Comment by jwhitak** [comment]
Where is the file that we can change for the playlist? It seems as if the server auto-populates the playlists based on what files are located in the media server at the start of each round.

**Comment by Eneocho** [comment]
You're right, I got confused with the vidya playlist.

**Comment by Kurfursten** [comment]
I think instead of implementing it as a flatpack you should just map it into the map. This seems like a roundabout way to avoid mapping.

Is there any upside to doing it this way? Particularly because you would be able to generate an infinite number of jukeboxes with pietyvend recharge packs which is something we've tried to avoid - making lots of Jukeboxes

**Comment by jwhitak** [comment]
Pietyvend recharge packs are unobtainable, to note.

I can see some pros to keeping it in the pietyvend. Mainly, access level in order to get another jukebox. But I can see cons: Someone innocently PRs the pietyvend recharge packs into a cargo crate for example...

**Comment by Kurfursten** [comment]
Ah, that is good to know. However, you can flatpack vending machines so that's one way to reproduce them. Currently you can't flatpack jukeboxes.

**Comment by jwhitak** [comment]
The cursed mechanic scanner, bane of people who want to make new machines... Merigng it as-is could result in a flood of holy jukes...

**Comment by Eneocho** [comment]
Just make the current pietyvend that's only roundstart and has the jukebox unscannable, then add a child pietyvend sans jukebox to the supply crates. All done without mapping new vendors.

**Comment by Kurfursten** [comment]
It still doesn't justify why this is better than just mapping holy jukes

**Comment by Eneocho** [comment]
Mapping is a torture method we shouldn't subject our coders to.

**Comment by Hinaichigo** [comment]
Hmm I think it would be better to map it as well. Constructing a juke just feels weird.

**Comment by GermanSanta** [comment]
> Ah, that is good to know. However, you can flatpack vending machines so that's one way to reproduce them. Currently you can't flatpack jukeboxes.

That's a good point. Perhaps making it premium with a gold coin would prevent this?

**Comment by Eneocho** [comment]
> > Ah, that is good to know. However, you can flatpack vending machines so that's one way to reproduce them. Currently you can't flatpack jukeboxes.
> 
> That's a good point. Perhaps making it premium with a gold coin would prevent this?

You can just get coins from vendors/coin press.

**Comment by Kurfursten** [comment]
Forgive me for uttering these words, but Eneocho is right. That doesn't fix it. However, this is a good time to learn mapping. Swing by coder discord if you have trouble and we can help.

**Comment by GermanSanta** [comment]
Update: Mapped and Completed. Removed the flatpack code.

**Comment by Kurfursten** [comment]
Look at you, and all the diffs look clean. I'm legitimately proud GS. Good work!

**Pull request merged**
