### PR TITLE
add top 10 title screen art contest finalists as splash screens

### PR DESCRIPTION
**Pull request by nervere**
## What this does
See this thread for reference: https://ss13.moe/forum/viewtopic.php?f=40&t=6793
The following screens (top 10) are added:
#1 - A Day In The Life - made by SalmonIsTasty
#2 - Me, Ian, and The World - made by Kvistor
#3 - Mad Ablino - made by IrishManiac
#4 - Spare Rush - made by TinySaturn
#5 - Cryo Drinker - made by yvvel
#6 - Sleep Tight Nukie - made by Botanics
#7 - The Agent - made by @sleepingvine on Discord
#8 - Cleanup Crew - made by @candycaneanniahlator_etherware2 on Discord
#9 - Poster from Atmosia - made by Basil
#10 - Joyride - made by Eneocho

[fluff]

## Changelog

:cl:
 * rscadd: Added the top 10 splash screen art submissions from the recent contest. Art attributions: SalmonIsTasty, Kvistor, IrishManiac, TinySaturn, yvvel, Botanics, @sleepingvine (discord), @candycaneanniahlator_etherware2 (discord), Basil, Eneocho. Art submissions can be viewed here: https://ss13.moe/forum/viewtopic.php?f=40&t=6793

### CODE REVIEW

**Comment by ghost** [comment]
>Adding raider in the morgue

**Comment by nervere** [comment]
> > Adding raider in the morgue

The thread on the forums appears to be somewhat incorrect, or at least the wrong dataset to use for this PR. It details the votes for #1 best splashscreen, not the data for the "which splashscreens should be in the game" vote. Dilt has given me the correct data, seen below:

image

I will update the PR accordingly. Raider in the Morgue will be replaced with Joyride.

**Comment by kilozombie** [comment]
I would immediately veto Joyride, I think it's too eyesearing

**Comment by nervere** [comment]
Joyride has been replaced with a version that is 4x slower as to make it less eye-searing.
New version:

4 times

**Comment by Eneocho** [comment]
> Joyride has been replaced with a version that is 4x slower as to make it less eye-searing. New version:

I'd make it a bit faster, maybe only 3x as slow as the original copy? the 4x feels a bit too slow. Make sure to specify I only clipped the original pic and added the logo, I didn't draw the original gif.



How about this speed?
Also, checking the slower gif, it seems you just quadrupled every frame, instead of using only 5 frames with 4x the delay.

**Comment by Kurfursten** [comment]
I already stated I thought it was reasonable to include all of the candidates which got at least 50%+ of the admin vote. If someone really hates Joyride they could maybe try to see if there is support to retract it in a later PR, but as far as I'm concerned there has already been a server vote for all of these.

**Pull request merged**
