### PR TITLE
Adds 2 new PACMAN engines.

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Adds two new PACMAN engines:
B.A.B.Y.P.A.C.M.A.N, an engine that burns bananium and P.R.O.F.E.S.S.O.R.P.A.C.M.A.N, an engine that burns phazon.
## Why it's good
Gives an engineering use for bananium and phazon.
:cl:
 * rscadd: You can now make B.A.B.Y.P.A.C.M.A.N engines and P.R.O.F.E.S.S.O.R.P.A.C.M.A.N engines, consuming Bananium and Phazon respectively.

### CODE REVIEW

**Comment by angryturnip** [comment]
The bananium one should be P.A.C.L.I.A.C.C.I.

**Comment by Kurfursten** [comment]
Why not DRPACMAN? In keeping with MRSPACMAN

**Comment by Eneocho** [comment]
> Why not DRPACMAN? In keeping with MRSPACMAN

I just googled for a couple pacman names and professor/baby pacman were the first I saw. I can change 'em if you want, though.

**Comment by Kurfursten** [comment]
Oh, if it's real then by all means

**Comment by hacker-on-steroids** [comment]
pacman - 5000W / fuelrate, burns plasma
superpacman - 15KW / fuelrate, burns uranium
mrspacman - 40KW / fuelrate, burns diamond
babypacman - 100KW / fuelrate, burns bananium
professor - 250KW / fuelrate, burns phazon

**Comment by CrazyAmphibian** [comment]
cool and all but i don't recall the last time i saw a pacman engine used

**Comment by Eneocho** [comment]
> cool and all but i don't recall the last time i saw a pacman engine used

I use them relatively often whenever I make botany power (diamond-making splice -> mrs pacman). Bananium engines are long-term possible if you have a good source of powerful bananas and a phazon sample. Phazon engines will, for the most part, remain purely coolfeature since it's so stupidly expensive.

**Pull request merged**
