### PR TITLE
Adds CE's new toolbelt to the premium section of the derelict vender.

### PR DESCRIPTION
**Pull request by FudgePucker**
For an item so good there should be more than one in the entire universe.
I added one of these bad boys to the vender on the derelict and for bus. (Back when we had that asteroid build bus where we had to leave the station, one of these venders would have helped.)
Hopefully it won't be too OP, considering it is in the middle of space, unpowered, and requires a coin.

### CODE REVIEW

**Comment by Probe1** [comment]
i don't like it.

**Comment by FudgePucker** [comment]
Yea but you also need a coin.
People thought that requiring a coin for the CE jumpsuit was a bad idea.
I don't see how having a single other belt in the middle of space behind a access locked vender requiring a coin is going to make starting with one round start and also having the best rigsuit on the station seem like less.

**Comment by Probe1** [comment]
you don't need a coin for the CE jumpsuit.

**Comment by FudgePucker** [comment]
You do now :^)
#4248

**Comment by Probe1** [comment]
Fair enough.  Still no.  Stop diluting something good for CEs.

**Comment by CptWad** [comment]
:-1: keep it solo. Maybe make it a tator objective too.

**Comment by 9600bauds** [comment]
With how hard it is to get the belt I don't think adding it to the derelict undermines someone's will to play CE very much.
I sure wouldn't get a coin and go out to space for a slight belt upgrade. But maybe as miner I'd bring it back and make someone's day.

**Comment by FudgePucker** [comment]
I don't think that people will decide not to play CE just because there is a another one of your belts in deep space.
You still get bridge, brig, tcom access on top of engineering access, and also the best rig suit with out bus intervention, you also get the best magboots with out bus intervention.
You are still in charge of engineering.
This doesn't get rid of the carrot, or lengthen the stick, it just puts a tiny slice of carrot out in space.
No one doesn't play shaftminer because there are pickaxes on clownroid and in the pirate ship.

**Comment by ComicIronic** [comment]
I don't think this is a good idea.
Certain useful items should remain solely available to the department heads.

**Comment by FudgePucker** [comment]
The CE already has one.
The CMO gets a hypospray
The HoS gets his kickass trenchcoat
The Captian gets his laser
The HoP gets Ian
and the CE gets the best rigsuit in the game.
Least amount of slowdown for a spaceworthy exosuit outside of bus, and has some radiation sheilding. Also the only other rigsuit that can withstand high pressure and plasma besides the atmospheric rigsuit.
Nobody is going to play CE just for the belt, belt is just extra on top of the suit.

**Comment by bustygoku** [comment]
:-1:

**Comment by FudgePucker** [comment]
Eh fuck it. Mostly negative feedback, and now it has conflicts.
Killing it.

**Pull request closed without merging**
