### PR TITLE
WHYDYOULEAVEYOURKEYSUPONTHETABLE?

### PR DESCRIPTION
**Pull request by ghost**
YOUWANTEDTO
:cl:
 * rscadd: Keys left upon the table are informed about being left there by who, because they wanted to.

### CODE REVIEW

**Comment by DeityLink** [comment]
I don't get it?

**Comment by SonixApache** [comment]
i get it, but i don't understand

**Comment by Eneocho** [comment]
this felt like a barry PR. take my thumbs up

**Comment by ghost** [comment]
> I don't get it?

you make korn references with (somebody) was (someone) and not get this

**Comment by DeityLink** [comment]
ohhh, SoaD of course, I never quite learned the lyrics, I sung the speedy parts as gibberish.

**Comment by Eneocho** [comment]
> 
> 
>I sung the speedy parts as gibberish.

based

**Pull request merged**
