### PR TITLE
Change majority of the service department

### PR DESCRIPTION
**Pull request by SysadminJeroen**
Note: Majority seen in this PR, especially the booths at the windows, came from an anon in the thread.

Modify the majority of the service section of the station.
- Change the layout of the bar
- Swapping the Theater Backstage and Bar Back Room around.
- Adding a door to the Bar Back Room that goes directly into the kitchen, due to walking to the kitchen from behind the bar taking longer.

dreamseeker_2016-08-17_19-59-15
dreammaker_2016-08-17_20-07-14

### CODE REVIEW

**Comment by PJB3005** [comment]
Not really a fan of the position of the vending machines to be honest.

**Comment by SysadminJeroen** [comment]
@PJB3005 I'm not too fond for it myself, but couldn't find a better spot. Where would you like them placed?

**Comment by Kurfursten** [comment]
New theater is too cramped for two people

New bar backroom is too huge.

Broke mail system, now mail to theater goes to bar backroom and there's already a bar mail point.

1 tile chokepoint in the bar is bad

**Comment by SysadminJeroen** [comment]
@Kurfursten Thanks, I forgot about the mail.

In my opinion the theatre backstage is large enough for how much it is getting used.
The bar backroom is huge, but it is closer to the Kitchen and Hydroponics.

I could maybe shorten the bar backroom a bit to place the vending machines near the kitchen exit.

**Comment by ComicIronic** [comment]
The bar itself is way too big - what would the bartender ever use that middle block of turfs for?

**Comment by SysadminJeroen** [comment]
@ComicIronic That is what he decides, he might turn it into a Rage Cage.

**Comment by FudgePucker** [comment]
Replace the two potted plants with the vending machines under the bathrooms.
Move the cash register over to the left, have a ref table below the still, and replace the far right table of the bar with the arcade machine, that way it looks like a bartop arcade machine.

I like the amount of room the bartender has, you can go make some more tables to have room for mixing drinks.

**Comment by ComicIronic** [comment]
Why would a bartender rip up all his reinforced tables to make a rage cage by using an extra three empty tiles in the middle of his bar? I'm talking about behind the counter.

**Comment by Exxion** [comment]
That area behind the bar isn't really too big. The current one is too small if you want to build the machines. There's exactly enough room behind the current one to build all the bartending machines if you remove the Boooze-O-Mat. Some spare room is nice.

**Comment by SysadminJeroen** [comment]
@FudgePucker 

I could move a bit of the bartender backroom near the kitchen exit one up north, there I can fit all three machines.

I think that people could break in if I replace the table with the arcade machine.

**Comment by kol1th** [comment]
@ComicIronic 

Every time I've played as bartender, I've had to remake the actual counter area due to lack of space. With this, there's room (as @Exxion said) to make + place the advanced machines, and also place more table space.

**Comment by Intigracy** [comment]
Why is there no entry to the theatre?

**Comment by SonixApache** [comment]
Middle of the actual bar section is the perfect place to put the advanced bartending machines,

**Comment by PJB3005** [comment]
For the vending machines:

Move that little table and the chairs with that sigar in the bottom right to where to door to the toilets are, then move the door to the toilets so it's where that entertainment monitor currently is.

Then put the vending machines where that table & sigar used to be.

**Comment by FudgePucker** [comment]
@Jeroen52
That's why you put a table behind the arcade machine. Maybe move the still to the backroom (who even uses the still enough to have it in the main work area?) And have a second table there as well.
So it would be arcade machine table table.
This would make it harder to break in because you would have to move the arcade machine before welding the table. Also two more tables for work space. Two tables vertically prevents them from flipping in.

**Comment by SysadminJeroen** [comment]
@FudgePucker It is a good idea, however the back area is rather large and I am more confident shrinking that a little bit to place the machines where the walls of the back area were.

And I personally use the still a lot, if you put a hot chilli in them and choose Vodka you get Sbiten.

It appears that in the meanwhile a merge conflict happaned, which I'll have to resolve before.

**Comment by Iamgoofball** [comment]
If you're putting a big ass open table kitchen entry, remove the one facing the hallway. You don't need two of them at once.

**Comment by FudgePucker** [comment]
You can use one to put burgers to feed the station and use the bar side one to have snowflake food and orders.

**Comment by ghost** [comment]
But... why?

**Comment by FudgePucker** [comment]
Why not?

**Comment by Exxion** [comment]
Box's current bar is bad
This is an improvement, albeit a small one

**Comment by gbasood** [comment]
@Kurfursten 

> 1 tile chokepoint in the bar is bad

I'm not entirely sure how that's any different than what Box has now.

**Comment by Kurfursten** [comment]
@gbasood 
untitled

**Comment by SysadminJeroen** [comment]
Currently too busy IRL to work in this, and due to the number of downvotes I am closing this for now.

**Pull request closed without merging**
