### PR TITLE
Box fixes/changes.

### LINKED ISSUE #8186: Better use of mailing system on Box and Taxi
I noticed that Defficiency and Metaclub have both a specific mail outlet for untagged parcels; this way, if someone from anywhere on the station needs to take an item somewhere, they can just wrap the item (there are package wraps in almost any department), take a pen, add a note on the parcel (for example, "send to RnD") and put it in a disposal unit; the parcel will exit from the mail outlet instead of the regular disposal outlet:
at this point, the cargo tech will (hopefully) notice the parcel (better if you just yell at him via radio/message him via PDA/requests console), move the mouse on it to read the note, add the tag with the destination tagger and send it via disposal mail.

I like the idea very much, so why do not use it on Box and Taxi too? Especially for Taxi, sometimes could be very frustrating to walk around stations to take/bring an item, so using this system would be very useful.

I tried to modify both delivery offices on box and taxi to add a mail outlet, trying to not waste any room space (you just need to add a Wrapped Sorting Junction before the disposal outlet):

mail

i noticed that the other guy on the server opened an issue for this last detail: #8183

P.S.: talking about cargo, reminder about this too: https://github.com/d3athrow/vgstation13/issues/6800

### LINKED ISSUE #13072: cryocell volume pump on boxstation
on box, the volume pump used to flush cryocells is hidden under the medicine closet; i think that it should be easily visible like all other maps, for example modifying it like this:

flush

### LINKED ISSUE #13099: Box cargo ATM deposits money onto window tile
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)
When you press the withdraw button on the cargo ATM in box, the money plops out onto the window tile just northwest of the ATM.

### PR DESCRIPTION
**Pull request by Probe1**
### Ready for Review/Merge.

(Box) Removes a badly placed ATM in Cargo https://github.com/d3athrow/vgstation13/pull/13308#issuecomment-271129148
(Box) Diverts cryo emergency purge valve to the left instead of the north so its invisible to players. https://github.com/d3athrow/vgstation13/pull/13308#issuecomment-271129153
(Box) Tweaks disposals so players can send unlabeled packages to Cargo.  https://github.com/d3athrow/vgstation13/pull/13308#issuecomment-271129148

Closes https://github.com/d3athrow/vgstation13/issues/13099
Closes https://github.com/d3athrow/vgstation13/issues/13072
Closes https://github.com/d3athrow/vgstation13/issues/8186

### CODE REVIEW

**Comment by Probe1** [comment]
dreamseeker_2017-01-07_23-29-47

**Comment by Probe1** [comment]
dreamseeker_2017-01-07_23-30-00

**Comment by 9600bauds** [comment]
oh god no now we'll get asshats actually realizing the "VENT CRYO" button exists

**Comment by SonixApache** [comment]
👍  on the ATM
👎 on the emergency valve
lot of shitters will turn it on when they see it

**Comment by Probe1** [comment]
I'm pretty sure it's been there longer than Pomfs server.  It doesn't cause any egregious issues on Meta or Deff.

**Comment by yclatious** [comment]
Don't like you removing the cargo ATM as it allowed QMs and techs to easily just get cash from the cosiness and safety of cargo, no risk of random clowns or greyshits taking the id, put it someplace else in there or keep it in, rest is fine

**Comment by Probe1** [comment]
There's an ATM in the QM office.  He gets nice things.  Cargo techs don't.  Go out in the hall like every other player in the game.

**Comment by Probe1** [comment]
I appreciate that I'm being horribly dismissive and it is good feedback.  I'll take another try.

1.  The cryo vent valve is on all maps and only on Box is it obscured.  When we play other maps cryo sabotage isn't any more common than it is on Box (and it's very rare).  The steps to rectify it are as simple as sabotaging it.  Just walk into the paramedics, grab the extra O2 canister, and wrench it in.  If you need more the stations got dozens, from atmospherics to toxins storage to the _many_ located off the main hallways that anyone can access.   We're not making foolproof maps here.  We have to have good things and bad things.  Risk and efficiency.  We have to think of both the antagonist and the players working in a department.

2.  Cargo having a private ATM is weird.  It's the only department that has a private ATM and other than handling shipping there isn't anything particular to Cargo that warrants it.  Mining does, but only because @JMWTurner never added an Account Security Preference to the character setup page and every round miners have to go set their security to 0.  That's a separate issue.  The QM handles the Cargo Account and has a pretty good justification for his own private terminal.  Which is why he has one in his office and I had no qualms over fixing.  ATM robberies are extremely rare as is, and robberies in general are also very uncommon.  I can't recall the last time I observed one or saw one in game while playing.  I don't think we can empirically cite a threat of having your money stolen as a reason Cargo needs their own private round-start terminal.  The only justification I can see for it is convenience. Convenience that keeps players in their departments, away from other players, not interacting with anyone, and encourages isolation.  

On top of all this, you can _build your own ATMs_ so if it's a big +++ to have one, it can be easily done.

**Comment by SonixApache** [comment]
Box is a LOT more common than the other maps.
Shitters are a lot more out of their element on non-box maps.

Whatever, just do it, see how often cryo gets emptied out.

**Comment by Probe1** [comment]
Believe me if I ever change anything and it causes a huge fuck I will be right there to unchange it.  In this very PR I accept that my "easter egg" of putting @PJB3005 's excellent christmas lights in the ghetto bar isn't an easter egg if I've received _nine_ bug reports about how I forgot to remove them.  I moved them somewhere more hidden.

**Comment by yclatious** [comment]
Never did know you could build a ATM of all things, if that's the case, sounds more than fine by me, ill still miss the atm being there roundstart, but eh, no big loss.

**Comment by SonixApache** [comment]
You can't build ATMs, ability to do so was removed a long time ago because you just needed a bit of metal.

Did that get reverted again?

**Comment by uazuaz** [comment]
@9600bauds @SonixApache 
that's why i also opened this https://github.com/d3athrow/vgstation13/issues/13071
by the way, when gas pumps were added to cryocell pipes i didnt's see people abusing them.

**Comment by Probe1** [comment]
I'm never using mapping (general) again I hate that tag.

**Pull request merged**
