### PR TITLE
Downsizes mantainability nightmare into slightly smaller mantainability nightmare

### LINKED ISSUE #10774: Borg beaker + IV = dropped borg beaker.
I thought we managed to kill all these bugs with the borg beaker ages ago...

### LINKED ISSUE #12707: Medical Borg issue
Medical module has an odd interaction when using an IV.
Placing the borg's beaker into the IV stand and then removing it will break it, disallowing it being stored or used by the borg until it is placed into a machine such as a chem master and removed and restored in the borg, or the borg is reset.

### PR DESCRIPTION
**Pull request by 9600bauds**
Supposedly fixes https://github.com/d3athrow/vgstation13/issues/12707 and supposedly fixes #10774
I have NO FUCKING IDEA if it works correctly because I have NO FUCKING IDEA how mediborg beakers are SUPPOSED to work in the first place, please someone who has actually played mediborg before test this

### CODE REVIEW

**Comment by Intigracy** [comment]
By all accounts this should fix it, it's just copypasting while removing the copypasting.

**Comment by PJB3005** [comment]
Maybe have a generalized proc for ejecting a beaker or whatever and then make the borg beaker override that?

**Comment by 9600bauds** [comment]
The var/beaker is defined in every individual machinery, so copypaste is sadly needed unless someone went and made a subtype.

Or, you know

::::::::::::::

**Comment by Probe1** [comment]
tumblr_inline_o5h0lvrswm1t83v1x_500

dont mind me i'm just posting a cute cat in a dead PR that may be ready to merge but no one knows for sure

**Comment by 9600bauds** [comment]
and this is why I hate touching silicon inventorycode
I don't know how it's SUPPOSED to work in-game.

**Comment by ComicIronic** [comment]
>silicon code 

HUERGH

**Comment by ComicIronic** [comment]
This is going in.

**Comment by Intigracy** [comment]
If it's in one of the borg's "hands" as a selected module, it goes back there.

Otherwise it puts it back in its "bag"

**Pull request merged**
