### PR TITLE
Make Birbs Beautiful Again

### PR DESCRIPTION
**Pull request by ghost**
Readds the light green Vox skin tone, added 2 new ones from Paradise (Azure, Emerald)

first row is light green, fifth row is azure, sixth row is emerald

:cl:
 * rscadd: Re-added light green Vox skin tone
 * rscadd: Added 2 new Vox skin tones, Azure and Emerald

### CODE REVIEW

**Comment by kol1th** [comment]
Sure why not

**Comment by ghost** [comment]
Frikkin parrots

**Comment by yclatious** [comment]
Can you get a picture of the new vox skin tones? The vox pandering is shit already, but atleast make some quick screenshots so people who do play vox can see it.

**Comment by Ephx1** [comment]
Those do look pretty bad.

**Comment by ComicIronic** [comment]
Are you sure the rows are the right way around? I'd expect azure to be blue and emerald to be green.

**Comment by Exxion** [comment]
The last couple do look a bit wonky but honestly I don't care because you've also brought back the classic

**Comment by Intigracy** [comment]
Finally I can have my neon colored fursona

Slippin' on down that old slippery slope

**Comment by yclatious** [comment]
Like you expected anything else from a vox themed PR intigracy, like any of us would or do.

**Comment by Intigracy** [comment]
No more pork barrel pr's

Make github great again

**Comment by cadaverouscoyote** [comment]
those new ones are gross

**Comment by SangriaMonkey** [comment]
Call me when they come in Fade or Gucci

**Comment by Kurfursten** [comment]
I don't know what anyone is talking about, there's no way the dark blue and green are worse than the light green. It's like neon. It's from a completely different palette. The tone is all wrong.

**Comment by Exxion** [comment]
The light green is the original, and so much better than any of the others

**Comment by SkowronX** [comment]
Make more quill styles. Minr are poopy

**Comment by Ephx1** [comment]
@Exxion 
I disagree, vox work better with more grimy dark colors.
Something like a light black would be a better addition than any of these.

**Comment by KasparoVy** [comment]
That screenshot seems vaguely familiar! @Ephx1 Feel free to make some mock-ups. I think it'd be interesting to see how dark/"grimy" themed Vox would look.

**Comment by Ephx1** [comment]
The colors we already have, for example, these are far too bright

**Comment by Intigracy** [comment]
If people want more colors I can add more, I made the current 3.

**Comment by Intigracy** [comment]
Still on my todo is adding color selection for the quills selection, in the same way the skin is handled (NOT a color wheel)

**Comment by NigglyWiggly** [comment]
No

**Comment by SkowronX** [comment]
lel

**Comment by uraniummeltdown** [comment]
@PJB3005 @clusterfack @ComicIronic @Intigracy Merge please

**Comment by Ephx1** [comment]
no thanks

**Comment by Intigracy** [comment]
Remember to treat people who use azure/emerald even shittier than the usual Vox.

**Comment by NigglyWiggly** [comment]
What
Why

**Comment by Intigracy** [comment]
Because even though I personally don't like it, I won't force my view on the majority.

**Comment by Kammerjunk** [comment]
I also think it's pretty shit but all I will do is treat rainbow birds worse than normal birds 👍

**Pull request merged**
