### PR TITLE
Reticulated Vest

### PR DESCRIPTION
**Pull request by Kurfursten**
Do you wish botany could contribute more during blob? Now they can make reticulated vests at the biogenerator for 500 points.

Features:
* Reduce incoming emitter damage by 60%
* Suit storage slot can hold a large oxygen tank or liberator laser rifle
* Will absorb up to 2 blob hits for you (icon updates and conspicuous messages given)
* Can recycle after broken for a little wood

Limitations:
* Has no armor values, so useless for any other defense
* Not space proof - no pressure or temperature protection
* Suit storage can't hold a wide variety of objects like a hazard vest
* Biogenerator itself is quite slow if un-upgraded, meaning they are hard to quickly mass produce

🆑 
* rscadd: Botany can now print reticulated vests at the biogenerator. They excel against blobs.

### CODE REVIEW

**Comment by Eneocho** [comment]
BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED BASED

SPEEEEDMERGE NOW

**Comment by jwhitak** [comment]
This PR adds a whole new defense type: BEAM DEFENSE! Protects you from BEAMS.

**Comment by djkramer123** [comment]
Neat item, would've liked to see energy armor fixed though, considering that dealt with emitter damage amongst other things.

**Comment by wotisjanitor** [comment]
great, now we need at least one botany player

**Comment by pedr69** [comment]
thought energy armor did this but apparently not
it used to shorten/skip stuns, does it do literally nothing now?

**Comment by Kurfursten** [comment]
Energy armor does not mitigate emitters or stuns. I have heard there are some obscure weapons that might use it, but I am not sure if that's true.

**Comment by djkramer123** [comment]
Energy armor did both of those things before it broke as a result of this(?) PR #23303

**Comment by DorainGrey** [comment]
While Energy Armour values should be fixed, I think separating beam defense from energy defense is actually a good thing.
It allows for Engineering suits to be granted high beam protection, without the corresponding high stun defense.

**Comment by ManopolisJones** [comment]
I dunno man, the fact nine out of ten times the station is breached when there's blob happenings makes me feel like this vest is not-so-useful, that is to say, will probably never get used outside of the first time it's seen in game since everyones gonna be in space suits fighting the blob.

**Comment by pedr69** [comment]
could perhaps add airtight blobs, made by evolving strong blobs?
and encourage the blob not to breach the entire station, somehow

**Comment by Eneocho** [comment]
> could perhaps add airtight blobs, made by evolving strong blobs? and encourage the blob not to breach the entire station, somehow

Could work, you couldn't use the breaches to triangulate blobs with that, which gives some stealth to the blob, but there's a strict benefit for the blob to breach the station, since that directly endangers the defending crew.

**Comment by Kurfursten** [comment]
I was toying with this idea that blob resource nodes would produce more resources if the air quality is good, to encourage blobs that don't wreck outside walls. Blob restraint is on by default anyway.

Also, maybe blob factories would produce good, breathable air.

**Comment by pedr69** [comment]
WITHOUT OXIGEN BLOB DONT EVOLUATE??!

**Comment by Eneocho** [comment]
> I was toying with this idea that blob resource nodes would produce more resources if the air quality is good, to encourage blobs that don't wreck outside walls.

That would be a hard nerf to midround blob, since those breach upon impact.

**Comment by Blithering** [comment]
Maybe instead if the blob not breaching, this could be an opportunity for more botany blob defense options? A friendly kudzu variant that grows in the direction of breaches and grows thicker in that area to seal it? Or a plant that creates a bubble of breathable air in an xtile circle around where it's growing?

**Pull request merged**
