### PR TITLE
Something that everybody who has ever used an RPD will be infinitely thankful for

### PR DESCRIPTION
**Pull request by 9600bauds**
RPDs will now create pipes in the layer and the direction that the RPD was set to when the pipe started building, rather than when it finishes. This means you can effectively place multiple pipes in different layers and different directions at the same time.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Handy, but please update your PR to include what it does in the description so others don't need to read the code.

**Comment by 9600bauds** [comment]
It's my secret method to get PR review against people's will, otherwise few people read the code

**Comment by PJB3005** [comment]
:+1:

**Comment by ghost** [comment]
> clickbait title

:-1: to be honest
The change is great though

**Comment by 9600bauds** [comment]
It's not clickbait if it's objectively true

**Comment by ghost** [comment]
Yes it is.

**Comment by FudgePucker** [comment]
:+1: :+1: :+1:
Celt can go fuck himself, this is the single most greatest PR ever created.
I want to suck your dick for making this improvement.

**Comment by Ephx1** [comment]
Definitely a yes, I hope this gets implemented onto the tile painter as well.

**Comment by 9600bauds** [comment]
ty chicken man of coding

**Pull request merged**
