### PR TITLE
Cooking jecties now results in actual jecties

### PR DESCRIPTION
**Pull request by ghost**
[content][tested]

## What this does
image
image

## Why it's good
Immulsions

## Changelog
:cl:
 * rscadd: Cooking jecties now result in actual objectives that show up in the end of round scoreboard.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Nice. Could end up with some really long scoreboards.

**Comment by Servalfang** [comment]
Mission specifications decrypted.

**Comment by Hinaichigo** [comment]
So do you need a 100% green rate to get the green text?

**Comment by ghost** [comment]
> So do you need a 100% green rate to get the green text?

Basically

**Comment by Kurfursten** [comment]
Funny but I don't think I want to scroll past 200 lines of this on the roundend report

**Comment by luigil101** [comment]
would be more fun if it rolled an actual recipe as an objective
if the chef runs out of ideas, he can cook a jectie to get a jectie

**Comment by Cartlord** [comment]
Seconding luigil101's idea.

**Comment by Eneocho** [comment]
Thirding the idea but the jectie dish turns green if the chef fulfills the jectie's jectie.

**Comment by Hinaichigo** [comment]
I like it as is without rolling a random recipe objective. Otherwise it starts delving into the territory of objectives for non-antags.

**Comment by Eneocho** [comment]
> roundstart objectives for non-antags

We already have those, they're called centcom requests.

**Comment by Cartlord** [comment]
> Thirding the idea but the jectie dish turns green if the chef fulfills the jectie's jectie.

Ooh, what if green jecties have something special in them, like a healing chem?

**Comment by DamianX** [comment]
I hate this

**Comment by Eneocho** [comment]
Make it so all jecties start red and give you a recipe to cook. If you complete it, it turns green. That way it's an actual jectie instead of RNG deciding if you get that greentext.

**Comment by Eneocho** [comment]
poor implementation but i guess

**Pull request merged**
