### PR TITLE
Adds metal foam grenades for the engivend and new engineering poster

### LINKED ISSUE #10584: Add metal foam grenades to engi vends premium item list
i'll do it when I get back from my walk and I don't want to forget.  the engi vends premium items suck.

### LINKED ISSUE #12647: Posters commemorating that time the engineering team flew too close to the sun
A couple of posters celebrating the meme machine (https://www.youtube.com/watch?v=pIiBB1dA-3o).
noshardforu
Nick's shard ban
engineering
Engineering at it's finest
Download link for icons: http://s000.tinyupload.com/index.php?file_id=01811044685279698653

### PR DESCRIPTION
**Pull request by Probe1**
The premium/contraband items for the engivend are pathetic.
Adds a new engineering poster

Closes https://github.com/d3athrow/vgstation13/issues/10584
Closes https://github.com/d3athrow/vgstation13/issues/12647

### CODE REVIEW

**Comment by Probe1** [comment]
I meant for these to be separate PRs but pushed them to the same branch by mistake.  Fuck it.

**Comment by jakmak3** [comment]
gib screenshot of the new poster

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/issues/12647

The second poster.  The first was not added.

**Comment by jakmak3** [comment]
looks good

**Comment by Kurfursten** [comment]
Good stuff, makes coins a little more covetable

**Comment by Shadowmech88** [comment]
Does `/obj/item/weapon/grenade/chem_grenade/metalfoam` contain iron foam, or aluminum foam?
Aluminum foam might be more useful to engineers for patching breaches, since it doesn't create metal foam walls.

**Comment by Kurfursten** [comment]
@Shadowmech88 Aluminum

You know, it would be nice if foam tiles reacted with an adjacent space tile to transform into a foamwall tile. Just think how intuitive that would make breach patching.

**Comment by Shadowmech88** [comment]
>it would be nice if foam tiles reacted with an adjacent space tile to transform into a foamwall tile. 

Why is that necessary? Metal foam floors do a fine job of plugging breaches.
The only reason I left foam walls in for iron foam grenades is for quickly creating obstructions/barricades.

**Comment by Kurfursten** [comment]
Metal foam floors are excellent for internal breaches but a little lackluster for the most common kind of breach you face on an average shift: external breaches. Meteors pummel maintenance and ruin a big segment.

If they created a wall where they touch space, this would fully plug the breach in the case of an external explosion or impact.

**Comment by Shadowmech88** [comment]
Couldn't you just use iron foam grenades for that, and break down the iron foam walls where you need to walk?
Iron foam grenades still create foam floors on space tiles, they just *also* create metal foam walls on top of them and wherever else the foam spreads.

**Comment by Kurfursten** [comment]
Sure, but those don't come in the boxes about to be included in engivend, hence why I was talking about it here instead of in a separate Issue

**Comment by Shadowmech88** [comment]
The solution then, would be to add iron foam grenades to said boxes, or to their own box type.

**Comment by Probe1** [comment]
Do either of you want something specific out of this PR?

**Comment by Shadowmech88** [comment]
I don't.

**Comment by Kurfursten** [comment]
No, just something to meditate on.

**Comment by Probe1** [comment]
okie dokie just making sure I didn't miss something.  

I could add one of each type of foam grenades if you like.

**Comment by ComicIronic** [comment]
It's also going in.

**Pull request merged**
