### PR TITLE
Cult Aura

### PR DESCRIPTION
**Pull request by GermanSanta**
Do not Merge! This is still a WIP!

There has always been a bit of controversy around cult? 
What's going on? Who's cult! So much chaos at security shooting crew members who aren't cult! The crew hiding for their lives having to retaliate from not only the cult but from security. I'm sure this made admins go crazy.

Well what this pr aims to do is to fix this issue. When cult reaches tier 3 or higher it adds an auric underlay on all cult member to easily distinguish them from crew.

:cl:
 * rscadd: Adds an aura around Cult Members at Tier 3 or higher

### CODE REVIEW

**Comment by GermanSanta** [comment]
cult aura

**Comment by tuypo1** [comment]
Sure, I am willing to try something that might alleviate a bit of the cult hate., I would have gone with a more reddish color though

**Comment by juanototo2** [comment]
Make it slightly transparent too.

**Comment by 9percents** [comment]
aura is good(sprite could use work) but at this point it's a deadtell who is a cultist, so a small buff in exchange for a reveal would be nice

**Comment by PrimeDSS13** [comment]
now I can collect my valids at double the speed with half the thought put in, hoorah.

**Comment by ShiftyRail** [comment]
Doubles down on what's bad with cult instead of trying to make it better
don't like that

**Comment by dunsel-hordon** [comment]
It completely removes the need for implanting people now. I would say the only way this goes through is if all cult at that point by default become immune to stun effects

**Comment by ghost** [comment]
so this PR just makes getting valids easier? what happened to the overlay pale bodies get when in crit?
I don't know, I think most of cult's problems stem from things that happened before act 3. Turning it into complete team deathmatch is stupid, but in the end that's just what act 3 is.

**Comment by GermanSanta** [comment]
vox-aura 
Updated Aura. This pr might take some time as the underlay keeps growing darker and darker. Which leads me to believe that multiple underlays are being stacked on each other.

**Comment by KingofHONK** [comment]
I like the whole race to bloodstone and defend or destroy them part of act 3, but nit the TDM part of it, is there any way we could just make act 3 less valid wars and more dangerous scavenger hunt?

**Comment by GermanSanta** [comment]
That's the issue with cult. Everyone has a gripe with something but not sure on a solution. This is just one aspect of that and if necessary can easily be moved to only being act 4 or higher. Act 3 was the most feasible first solution as cult is already outted. (the implants still work/fall out during Act 2)

**Comment by GermanSanta** [comment]
Personally I found people not acting during Act 3 to be incredibly underwhelming. People should be taking action at this point, not rping as fat sec due to fear of possibly killing a crew getting that bwoink. The time for stealth was during Act 1 and Act 2.

If anyone has any suggestions i'd them to post them here. A bit hard to make cult adjustments/additions when the issues aren't specified.

**Comment by aceedex** [comment]
Ill give it a 👍 but hope we do an experimental merge to see how people feel about this in round. 
My main gripe is that since you are 100% outed with a big "IM BALID" mark, you'll want to make MORE preparations while you arent, leading more into the act 1-2 problems. 

Something that I'd like to suggest is the cult getting the aura when within X tiles of a bloodstone, so that they can retain SOME anonymity around the station but having to put their neck on the line when defending bloodstones.

**Comment by PrimeDSS13** [comment]
I agree with an Aceedex, a test merge is probably advisable, The radius idea is pretty good as well, so you aren't just caught off guard and hit with a "Kill this person" marker.

**Comment by tuypo1** [comment]
Yeah making it only activate close to bloodstones sounds like a great idea

**Comment by SonixApache** [comment]
i'll go for blatant accelerationism and give it a :+1:

**Comment by boy2mantwicethefam** [comment]
I wanted to do this change in the PR so I'm giving my justification hoping at least SOMEONE will change their mind and upvote the PR instead of downvoting it.

Cult has problems. We can all agree on that, but one problem I have discovered is what an absolute clusterfuck the entire thing becomes at the bloodstone phase. The bloodstone phase is literally TDM, nobody can deny that, but problems arise because cultists are indistinguishable from normal crewmembers. An officer accidentally shotguns a civilian because the civilian was close to him during the stone phase and then admin problems arise because that's kinda how it is, and unless someone is actively smashing a stone you can't actually tell if he's on your side, and for officers the problem arises where they have to waste time stun and stripping anyone that comes close to check for cult items. I've played cult, I've played against cult, I pinpointed the problem in the bloodstone act, and it can be fixed with the cult aura. Cult can't get harmed by this because people will still be hammering at the stone to destroy them, but everyone else can have a better time not getting shot because they'll know at that point who's a cultist.

**Comment by tuypo1** [comment]
Seriously who the hell is downvoting this, I am the biggest fucking cult apologist around and even I think it is a good idea

**Comment by ShiftyRail** [comment]
@tuypo1 it's not a secret that I dislike cult, but the problem is both the philosophy behind the gamemode and the multiple layers of unfariness (on BOTH sides) that makes me hate it

This PR doesn't attempt to fix the wrong elements in cult design philosophy, and while it does make the last phase a bit less loopsided, it's not nearly enough to fix what's frustrating with cult

**Comment by Kurfursten** [comment]
What are those wrong elements?

**Comment by ShiftyRail** [comment]
Chiefly that the most rational way ton play is to be a powermemer asshole.
Security is more powerful on the stages where cult is low. It's in their interestinterests to be assholes and call the shuttle now because nothing says that they will be able to in 20 minutes.
Cult has a ton of toys they can't use until a given act. This encourages them to be overly prudent silly shufflers. And so on.

In short it all culminates to the final TDM race with stacked odds.

Not to mention the few things that are downright frustrating to play against.

**Comment by Kurfursten** [comment]
>Chiefly that the most rational way ton play is to be a powermemer asshole.
>It's in your interest to call the shuttle early because you might not be able to later

Fair for the other ones but this is literally true of everything. That's why it's called powergaming. Because it's powerful.

And the problem with early calls applies to a lot of modes - you want to call before it snowballs (blob, revs, xenos, etc. - but even a particularly nasty wizard)

>Cult has a ton of toys they can't use until a given act. This encourages them to be overly prudent silly shufflers.

In theory shouldn't the prospect of new toys encourage moving on to the next act? Say it was reversed and they can only use powerful toys early on... they'd never want to advance the act until everyone is dead.

**Comment by PJB3005** [comment]
I definitely don't like the blood stone phase, but I don't think this could make it any worse.

The entire gamemode is basically set up so that when the bloodstones activate the cult already has the odds stacked in their favor. This will slightly reduce their advantage, namely the advantage of "the crew can't trust *eachother* because they don't know who is cult and who isn't".

I'm not sure much can be done about it being a TDM. It's not ideal but let's at least level the playing field.

**Comment by DamianX** [comment]
Even if this wasn't controversial, this code is broken: it iterates over all cultist roles in the world instead of looking at whether src is a cultist.

**Pull request closed without merging**
