### PR TITLE
Mulebot update (stolen content)

### PR DESCRIPTION
**Pull request by ShiftyRail**
Lifted from Zth--. Don't cry for us, brave man.

Original text:

# video https://streamable.com/nrglsr

# horn https://streamable.com/o04vli

Adds a new laser assembly to control mulebots. Don't look at the code yet, still heavy wip. I will write a little bit more later, I'm tired right now

- [x] Ability to unload crates onto cargo carts
- [x] Maybe slow it down a bit?
- [x] Fix motor wires
- [x] Add a horn and re-routing after failing to pass a carbon or some obstacle
- [x] Fix unloaded crate layer
- [x] Clean files
- [ ] Load/unload sound - unfulfilled
- [x] Finish the laser thingy and make it buildable
- [ ] Either integrate or rework the navbeacon system - unfulfilled
- [ ] Notifications to cargo - unfulfilled
- [ ] Disable diagonals? - deemed too funny to fix
  - [ ] Fix blood tracks (depends on diagonals)

-- 
I just fixed the laser pointer and made it spawn in the QM's, the Captain's, and the HoP's lockers.

:cl:
- rscadd: New laser pointer for the QM. Command the mulebots from a safe distance. Does not interfere with PDA summoning.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
cargo bros is it real..?

**Comment by Viciousaurus** [comment]
I may have spared your life for cult but I will not tolerate diagonal movement.
Good to see this wasn't completely abandoned though.

**Comment by Eneocho** [comment]
Cargochads, we died and are in heaven, this can't be real.

**Comment by GreatBigFailure** [comment]
Thank goodness. At long last.

**Comment by WindowsErrors** [comment]
engineer wrangler

**Comment by Exxion** [comment]
Just so you know blood track code has absolutely zero support for diagonal directions and would require significant changes to allow for them

**Comment by Eneocho** [comment]
Can you make additional pointers or is it a unique item like holotools, hyposprays, etc?

**Comment by ShiftyRail** [comment]
@Exxion can't be that hard. Can it?

@Eneocho unique for now.

**Comment by Exxion** [comment]
Bloodtracks are consolidated to one object per tile, as you probably know. The tracks that exist as part of a given bloodtrack object are stored as direction bitflags, so there's nowhere to store diagonals separately from a combination of two orthogonal directions. No, it's probably not that hard a change to make, but it does mean changing *some* fundamental part of bloodtracks.
There's also the issue of our movement system not actually allowing true diagonal movement for most objects. Diagonal movements are (again, for most objects) two separate cardinal steps just with no delay between them. It's easy to allow an object to make true diagonal movements, but this allows it to move through diagonal gaps unless its `step_size` is smaller than its hitbox because lol byond
It also causes problems with movements near walls also because lol byond

**Comment by WindowsErrors** [comment]
we can wait

**Comment by Eneocho** [comment]
Any update on this @ShiftyRail?

**Comment by ShiftyRail** [comment]
Mergeable @Kurfursten sorry for the delays

**Comment by Eneocho** [comment]
Does the signaler system interact with pAI mulebots in any way?

**Comment by Armadingus** [comment]
Since this thing doesn't exactly come with an instruction manual, here's some things on how to use it.

- point (shift + middle mouse) at a mulebot with the laser in hand to assign a mulebot to the laser
- pointing to an area/objects also tells where the assigned mulebot must unload/load things
- activate the laser in hand to toggle between unloading and loading
- rightclick the laser and use the clear-assigned-mulebot verb if you want to stop using a previous mulebot

Needs this wiki section updated to reflect this http://ss13.moe/wiki/index.php/Cargo_Technician#MULEs

**Comment by Eneocho** [comment]
Updated

**Pull request merged**
