### PR TITLE
Access denied

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
It's been almost 3 years since I made #24177 so I figured I should give it a try this time, but with some changes:
- The chance to trigger it on non-april fools days are 1 in 1000, otherwise it's 1 in 10.
- Actually works when trying to open an airlock you have no access to now instead of when an airlock is closing.

:cl:
 * rscadd: Added a rare sound for trying to access airlocks that one doesn't have access to.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Damn you Github and your "automatically set it to draft" and then "close the PR"!!!

**Comment by jwhitak** [comment]
I look forward to holding into a door for an hour trying to get a funny noise. Code Bloat, though it would be funny on April Fools (only).

**Comment by boy2mantwicethefam** [comment]
"code bloat" my fellow player it's literally three lines and a sound file.

**Comment by ghost** [comment]
stop

**Comment by ShiftyRail** [comment]
mqknnq2ebZ1qz4rgp

**Pull request merged**
