### PR TITLE
Fix/science biohazard shutters layering

### LINKED ISSUE #10915: Science biohazard shutters layer above open airlocks
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0d91b25673f35182d69c6e36175ad143f2e1db89
> 
> General description of the issue
> When airlocks in science are open, they are entirely covered by the biohazard shutters, making it impossible to interact without alt-click
> This is on boxstation
> 
> What you expected to happen
> Open doors to appear above open blast doors
> 
> What actually happened
> They don't
> 
> Steps to reproduce if possible
> Open a science airlock with a blast door on the same tile

### PR DESCRIPTION
**Pull request by SysadminJeroen**
This fixes the issue where the science biohazard shutters would appear over the airlocks when the airlocks were opened.

Fixes #10915

### CODE REVIEW

**Comment by PJB3005** [comment]
Put fixes #X in the PR description so it autocloses.

**Comment by SysadminJeroen** [comment]
@PJB3005 Done.

**Comment by FudgePucker** [comment]
Thank god. That was grinding my gears so much.

**Comment by PJB3005** [comment]
> "fixing" it by var editing the object on the map.

Band. Aid.

**Comment by SysadminJeroen** [comment]
@PJB3005 no band ples i am newbie mapper

**Comment by PJB3005** [comment]
A proper fix would be to chance the shutter layer to be below the airlock when open, but above when closed.

**Comment by SysadminJeroen** [comment]
@PJB3005 It is already like that on my side.

**Comment by FudgePucker** [comment]
I mean honestly the emergency shutters are turned on so rairly that even if it looks ugly as well when they are on, being able to close the door behind you to stop tailgaters is 10000 times more important and should be merged asap

**Comment by kernikov** [comment]
still broken, check the issue page

**Comment by SysadminJeroen** [comment]
@kernikov the fuck, are you sure you checked out the correct branch and commit? I walked past each and every door and it was fine.

**Comment by kernikov** [comment]
Oh sorry, I noticed one of the doors was fixed and assumed this was merged.

**Comment by SysadminJeroen** [comment]
Not a problem @kernikov.

**Pull request merged**
