### PR TITLE
Revert Europa Lights [MDB Ignore]

### PR DESCRIPTION
**Pull request by ShiftyRail**
As much as I am proud of it - I am very proud of it - it's not ready for BYOND yet.

It seems a non-zero amount of users are still having lag/performance issues, and that for those who can run it, it can be choppy at times.

Lummox has said that the renderer will get a much needed update in 515 which should come before the end of the year. 

I've kept all the work done on lights so far on a separate branch that will continue to receive updates.

As soon as BYOND is ready, I will push that again. I do believe this new lighting system has a lot of potential and, once all the bugs are fixed and BYOND allows us to render it properly, could be the thing differentiating /vg/ from other serbs.

I've tested that gameplay-wise, it doesn't change anything. Goonlights are still here and everything works fine.

:cl:
- rscdel: Europa Lights have been put on a separate branch as we wait for BYOND to be able to handle them better.

### CODE REVIEW

**Comment by SonixApache** [comment]
✝️

**Comment by DamianX** [comment]
image

**Comment by GreatBigFailure** [comment]
Hopefully it's ready before snaxi season ends. I've been looking forward to a Christmas tree and cozy campfire with these lights.
Dont give up

**Comment by DeityLink** [comment]
Does this also revert the Perception conversion PR then? I think I think some of the procs added in the wake of Europa Lights were quite useful

**Comment by Armadingus** [comment]
F

**Comment by ShiftyRail** [comment]
@DeityLink Yes, spiders will work as before Yuro Lights.

**Comment by SootyBear42** [comment]
"could be the thing differentiating /vg/ from other serbs."
I'm not against switching to Europa provided it's ready but this comment just strikes me as strange, how are we not different compared to other SS13 servers?

Our server culture and partial gate keeping alone I feel is quite different and that it forces new players to acclimatise to our customs, we also allow for certain opportunities when it comes to roleplay.

**Comment by ShiftyRail** [comment]
You are correct, though I feel a little technological uniqueness - and the nice "atmospheric" or "ambiance" effects that can be derived from the flexibility offered by lights - would be a good additionnal selling point.

**Pull request merged**
