### PR TITLE
 Adds the Slave Status Subsystem for AIs, courtesy of TEEGEE

### PR DESCRIPTION
**Pull request by jknpj**
siliconcreepisnotajoke

:cl:
 * rscadd: Adds the Slave Status Subsystem for AIs, they can now check the name, health, battery, module, location, status and the amount of slaved silicons they have

### CODE REVIEW

**Comment by Probe1** [comment]
Really lowers that skill ceiling between good AIs and bad ones but you know what?  I'm not sure if it's really a bad thing.

**Comment by Ephx1** [comment]
Is that just a tab? I'm not sure I like that at all. Emagged borgs are instantly unslaved the second they are subverted. At the very least the cyborg upload has to be checked manually.

**Comment by Sooose** [comment]
Does this mean borgs just drop off that list as soon as they are emagged?

**Comment by Reviire** [comment]
Suggestion. What if you remove location tracking, but keep all borgs in the list. So all AIs can see the status of all borgs, it shouldn't be a big problem. If they want to check sync they can check the cyborg console, because unsynced borgs wouldn't drop off their status list.

I don't think there'd be a big problem with being able to see whether unslaved borgs are dead or alive and all that stuff. You can track them anyway since they have a camera.

**Comment by jknpj** [comment]
@Sooose 
Yes


@Reviire 
>remove the location

Can be done, i guess. Not being a "GPS, but better" isn't really the point of the feature

>watch all borgs

That defeats the point of the feature

**Comment by SonixApache** [comment]
alternate suggestion; allow the AI to pull up an integrated borgo panel

**Review by DamianX — APPROVED** [review]

**Comment by ghost** [comment]
Seems like a reaaaaaaaally major nerf to emagging borgs.

**Comment by imw-Oculus** [comment]
Logically makes sense, but as others have pointed out - poor for balance.
Wouldn't be so bad if it requires a special component be installed. But by default? No.

**Comment by Probe1** [comment]
Honestly, no.  Not as this is implemented.  It needs to account for the difficulty it would add to emagging cyborgs.  

I love the quality of life.  But it absolutely fucks over traitors emagging borgs.  Maybe if it wasn't removed when they were un-slaved.

**Comment by toomykins** [comment]
guess the emag can use some nerfs anyway

**Comment by jknpj** [comment]
I have a workaround for the metacheck, going to work on this later today.

**Comment by DamianX** [comment]
or not

**Comment by jknpj** [comment]
Maybe some other day

**Pull request closed without merging**
