### PR TITLE
Makes it so the Autodrobe Contraband creep spray makes cleanable decals, rather than actual beno weeds.

### PR DESCRIPTION
**Pull request by Eneocho**
Not a good idea for the fake creep to actually be real creep (what in god's name is on that grape drink).

:cl:
 * bugfix: The Autodrobe contraband creep spray now makes cleanable creep decals instead of actual weeds.

### CODE REVIEW

**Comment by smonkeM** [comment]
The point was to be real weeds. The "fake" is that it isn't a benomorph that spread it.

**Comment by Eneocho** [comment]
> The point was to be real weeds. The "fake" is that it isn't a benomorph that spread it.

Yes, but there's some grieffing issues with them being real. Clown does le beno gimmick and "spreads weeds", then an actual beno appears and 80% of the station is already primed for beno mayhem. We don't give the clown actual antag tools, we give them faux tools that look real until closer inspection, like the foam changeling scythe, the foam crossbow/dart, the toy eswords, etc.

**Comment by smonkeM** [comment]
> Yes, but there's some grieffing issues with them being real. Clown does le beno gimmick and "spreads weeds", then an actual beno appears and 80% of the station is already primed for beno mayhem. We don't give the clown actual antag tools, we give them faux tools that look real until closer inspection, like the foam changeling scythe, the foam crossbow/dart, the toy eswords, etc.

The weeds don't self-propagate and there's a limited amount from either the autodrobe or using dansauce if #34605 merges. I would prefer to take a balance pass by lowering the quantity/amount available rather than make them something the janny dabs over with a mop. I think a bigger issue may actually be that the weeds don't automatically die since they're not connected to a Xeno node, and I'm unsure of what other methods are available to remove them. Pacid?

Re: other tools: I agree, which is why I wanted to put it under contraband as a hacked item and the consequences that come from it as a result (space law) and something you can discern with a keen eye (no connected nodes) rather than an easily observable decal. Do decals appear "on top" of the ground as an object you can examine or just e.g a blood spatter on top of the tile?

It may be more graceful to make a dummy object with the same appearance that doesn't bestow plasma regeneration to benos if the consensus is that this is round ruining.

**Comment by Eneocho** [comment]
>there's a limited amount from either the autodrobe or using dansauce if https://github.com/vgstation-coders/vgstation13/pull/34605 merges

You can just get extra autodrobe supply packs in order to get more of the gunk juice, reducing the volume on the sprayers won't change that, you can just get more vendors.

>It may be more graceful to make a dummy object with the same appearance that doesn't bestow plasma regeneration to benos if the consensus is that this is round ruining. 

That would have some issues for the benos then, cause then they couldn't spread their weeds and/or wouldn't know if they have spread there or if the clown was just fucking with em. And if the faux vines become real vines once connected to a beno node, we go back to the original issue of the vines powering benos, they'd just need to put 1 node somewhere and now the massive clown-sourced vines are all plasma-refilling.

>under contraband as a hacked item and the consequences that come from it as a result (space law)

Contraband/hacked items aren't really illegal items, as far as implementations go, for most items they're just gated items so it takes a modicum of effort to get them or are items that go against the main theme of the vendor (like a medivend vending poison), unless you mean to tell me plant fertilizer (diethylamine), school glue, cola, lipstick, coffee, spoons, antitox pills, dumb hats/clothes/shoes, vodka, hair dye, donut boxes, etc are illegal.
Also, as far as spess law is concerned, contraband only extends to makeshift weapons, consoles/weapons/explosives/mechs without permit or antag gear. Anything else is fair game. The aforementioned items, and the creep spray are both fair game.

**Comment by Hinaichigo** [comment]
It makes more sense that NT wouldn't be stocking a latent xenobiohazard in their clothing vendors.

**Comment by SonixApache** [comment]
there's really no harm in having these weeds be actual weeds

**Comment by Hinaichigo** [comment]
It's probably not a huge deal in terms of the clown helping the xenos, but lore wise it's kind of gymnastics inducing.

**Comment by PrimeDSS13** [comment]
this just makes it lame

**Comment by angryturnip** [comment]
> Yes, but there's some grieffing issues with them being real. Clown does le beno gimmick and "spreads weeds", then an actual beno appears and 80% of the station is already primed for beno mayhem. We don't give the clown actual antag tools, we give them faux tools that look real until closer inspection, like the foam changeling scythe, the foam crossbow/dart, the toy eswords, etc.

There's some griefing issues with space lube being real. Clown does le lube gimmick and "spreads lube", then nuke ops show up and 80% of the station is already primed for nuclear mayhem.

**Comment by Eneocho** [comment]
Lube dries in a minute or so, not the same. And mass lubing is usually punished with death.

**Comment by Kurfursten** [comment]
I think Eneo's point is very reasonable since this was based on the events in a real round.

**Pull request merged**
