### PR TITLE
Adds railings to some bars for decoration

### PR DESCRIPTION
**Pull request by ghost**
[box][deff][meta][packed][snaxi][bagel][synergy][roid]

### Box
image
### Roid
image
### Meta
image
### Synergy
image
### Deff
image
### Lowfat bagel
image
### Snaxi
image
### Nerve
image

## What this does
Sections off parts of each of these bars with railings for decoration. Above view is from strongDMM, not in game. Could be too excessive or cluttering, let me know what parts are.

## Why it's good
Makes bars look nicer by default.

## Changelog
:cl:
 * rscadd: Railings have now been installed to most station bars

### CODE REVIEW

**Comment by WindowsErrors** [comment]
waiting for the day when kane-f adds functionality for the railings to be used for setting up an elevated DDT throw that does 30 damage to the head and upper body

**Comment by PrimeDSS13** [comment]
too much clutter + will have to be removed every time you redo the bar

**Comment by kilozombie** [comment]
I really like railings but most of these look awful. I like the Roid ones and that's it

**Comment by ghost** [comment]
Will just do a lesser scope with these

**Pull request closed without merging**
