### PR TITLE
Revert "Europa lights 2021"

### PR DESCRIPTION
**Pull request by Exxion**
Reverts vgstation-coders/vgstation13#29551
EXTREMELY fucked. Lights getting moved by conveyors, client lag AND extreme server CPU usage, lighting overlays looking like shit while moving, probably others
Emergency revert while fixes are worked on

### CODE REVIEW

**Comment by d3athrow** [comment]
why wasn't this tested before merging lmao

**Comment by Exxion** [comment]
It was, but I guess not enough

**Comment by ShiftyRail** [comment]
I tested it. As it turns out, Box on solo is not the same as Roid with 30 players. An extremely difficult concept.

Roid has a lot more lights by design.

I know what's causing it to lag. I think. Keep this open, but bear with me for at least 15 minutes.

**Comment by d3athrow** [comment]
shadows look silly with a lot of them overlapping

**Comment by Exxion** [comment]
If a fix is pushed this PR won't work anyway
But go ahead if you think you can fix the worst stuff before the round ends

**Comment by Exxion** [comment]
Oh, I will also point out that I stress-tested an earlier version than what was merged for server lag, and it was fine. Something must have broken since then.
I did manage to lag the server but that was by putting several hundred lit flares on a conveyor loop

**Comment by ShiftyRail** [comment]
Right, so let's take this from the top camly.

- Sparks are teleporting instantly between portals
- There's an issue with walls shadows and sprites
- There's an issue with shadow glide

All of these are getting fixed. Probably. The revert may have been a panic answer, but we are back.

**Comment by PJB3005** [comment]
@ShiftyRail make a conveyor around box bridge, fill it with opaque bananas and sprinkle flares around the place. That's what we did to stress test original baylights.

> why wasn't this tested before merging lmao

Lol it's baylights all over again.

**Comment by ShiftyRail** [comment]
We tested this.

**Comment by Exxion** [comment]
@PJB3005 
>I did manage to lag the server but that was by putting several hundred lit flares on a conveyor loop

**Comment by WindowsErrors** [comment]
i scooped up a bunch of lights in a crate and then i opened it in the darkened chapel and the crate looked like the glowing briefcase from pulp fiction except it was the light of god because of how bright it was

**Comment by Exxion** [comment]
I did notice while stress testing that with enough lights, the light overlays completely overpower the shadow overlays, yeah
I believe this was deemed a "feature" though

**Pull request merged**
