### PR TITLE
Faint is now a temporary knockdown

### PR DESCRIPTION
**Pull request by ShiftyRail**
I've had people complaining than emoting *faint put them to sleep.

:cl:
- tweak: Faint is now a temporary knockdown instead of a 200 seconds sleep.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
What the fuck this one is supposed to SLEEP you for 3 seconds

Yet another casualty of the emote refactor

**Comment by ShiftyRail** [comment]
I was told it was a knockdown for 3 seconds
Currently it's a sleep but for too long
Personally I would think that if you were fainting you'd end up being asleep more than 3 seconds but that's me

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I'm 100% sure it used to be a 3-5 second sleep and I know this because you could use it to powergame through surgery

I interpreted it as a cartoonish swoon or something

**Comment by Exxion** [comment]
This is what it was before:
image
No idea why that became 200, but it was the original emote datums PR that did it

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
:thinking:

**Comment by ShiftyRail** [comment]
Ok I'll fix it back to what it was before

**Comment by Exxion** [comment]
But it was 10

**Comment by Dacendeth** [comment]
next change *collapse back to Paralyse(2) for other powergame reasons.

**Comment by ShiftyRail** [comment]
You already cannot emote when you're asleep so the check was redundant.
I tested this

**Pull request merged**
