### PR TITLE
Fixes borer going out of hosts with superfart

### LINKED ISSUE #16988: Superfart with Borers is Superbroken
#### Description of issue
If you superfart with a borer inside of you, it throws the borer out of your body and it keeps its verbs as if it is inside of you, but can move independently and ventcrawl.

#### Difference between expected and actual behavior
Slugs shouldn't come out the bum, or maybe they should?  All I know is that it is best if they don't keep their internal verbs that can help you across the map.

#### Steps to reproduce 
fart with a borer inside of you while you have the superfart genetic power.

### PR DESCRIPTION
**Pull request by ShiftyRail**
Fixes #16988 
Tested

### CODE REVIEW

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
There has to be a better way than hardcoding it.

See if you can change it to view(get_turf(src),aoe_range) so it may not taking into account objects within the host?

**Comment by ShiftyRail** [comment]
@MadmanMartian `oviewers` is the correct proc.

**Comment by MadmanMartian** [comment]
@ShiftyRail will that only take into account mobs on turfs in view of the object?

**Comment by ShiftyRail** [comment]
http://www.byond.com/docs/ref/info.html#/proc/oviewers

>This is just like viewers(), but it excludes the center object and its contents from the list. It is a list of all other mobs that can see the center object.

**Review by MadmanMartian — APPROVED** [review]

**Comment by MadmanMartian** [comment]
good stuff

**Pull request merged**
