### PR TITLE
Reworks Defficiency atmos to be less chaotic

### PR DESCRIPTION
**Pull request by MrSegi**
Screencap of the new area

Gutted the old atmos area for deff and reworked it. Hopefully this makes the area far less chaotic. Also added a windoor for the atmos delivery area. Previously you could destroy the plastic flaps and be inside of atmos control.

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Have you tested this live?

**Comment by Probe1** [comment]
You're missing pipes running from the o2 and n2 miners to the orange mix line.

The pipes leaving from atmos to the station are really well done.

**Comment by MrSegi** [comment]
Conneced O2 and N2 lines to the mix

Also reworked the engineering airlock access requirements, this enables atmos techs to finally access their own department. Replaced the Supermatter engine room exterior airlock with doors that have their timing mechanism altered by default.

> Have you tested this live?

Yes, I have tested this on a local server. Everything works as it should.

**Comment by Probe1** [comment]
Plop a manifold around here so atmos techs can get their mixed gas into canisters and shit easily without ripping up pipes every round.

image

Otherwise :+1:

**Comment by Duny-** [comment]
bluethumbsup

**Comment by Boxe** [comment]
fuck you duny

**Pull request merged**
