### PR TITLE
Explosive implants can now hear and be triggered.

### LINKED ISSUE #2554: Explosive implant = borked
They don't work. You can implant yourself but when you say your phrase you don't explode.

### PR DESCRIPTION
**Pull request by gbasood**
Resolves #2554

Explosive implants that haven't been implanted won't explode, which may or may not be a bad thing, but should only affect people who are spawning shit I think.

### CODE REVIEW

**Comment by gbasood** [comment]
This should now be fixed up enough to merge in.

**Comment by ComicIronic** [comment]
Can you explain what the issue was?

**Comment by SkowronX** [comment]
They didn't fucking work.

**Comment by ComicIronic** [comment]
That's obvious from the bug report. I'm asking about the code issue.

**Comment by ririchiyo** [comment]
They didn't work because they never actually heard the message.

**Pull request merged**
