### PR TITLE
adds some melee damage logging

### PR DESCRIPTION
**Pull request by SonixApache**
This adds some damage logging for melee attacks. They go in the attack logs.
I can't promise it'll work for everything, but it works for punches, kicks, bites and weapon attacks
and by weapon attacks I mean I tested it with toolboxes, rusty energy axes, holo eswords, batons and rubber ducks - those all worked.
The total damage accounts for armor, so it (supposedly) only logs the actual damage done.

damage_logs

Some things to consider:
 - This is just melee logging... what about ranged attacks?
 - Hits from thrown weapons?
 - Edge cases?
 - Log all mobs or just target / assailant mobs with minds?
 - add coordinates?
 - remove "old" hit message and only use the new one?

### CODE REVIEW

**Comment by SonixApache** [comment]
blocked
mist

now has support for armor absorption, armor blocking, shield blocking and flat misses

**Comment by ghost** [comment]
how does this look in the variables list?

**Comment by SonixApache** [comment]
image
fills the attack_log list pretty rapidly

**Comment by ghost** [comment]
Could the intent/damtype and damage lines be combined or are the values not accessible at the same time?

**Comment by SonixApache** [comment]
They're handled in pretty seperate areas, but I could try to combine them if you think that's a good idea.

**Comment by DamianX** [comment]
Doubling the amount of messages in the attack log could be annoying but the additional information could be worth it. OK from me.

**Comment by SonixApache** [comment]
can always pull it out if it's too much, just remove the lines over yonder
https://github.com/vgstation-coders/vgstation13/blob/b156613c87eba4356f2350493822357ea49b6670/code/_onclick/item_attack.dm#L81-L89

**Pull request merged**
