### PR TITLE
HoS Office Shutters

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[box]

The HoS Office now has Privacy Shutters. They start closed to ward off carp.

At the request of @DrSnips 

New Office with shutters: https://lambda.sx/wNg.PNG

:cl:
 * rscadd: BoxStation: Nanotrasen has finally ponied up and installed privacy shutters in the Head of Security's Office to deter pesky carp and Vox Raiders.

### CODE REVIEW

**Comment by DrSnips** [comment]
Thanks for this. I'm not a very big fan of the space carp pet HoS always has dispite the spawner being moved in the past. On top of that the HoS's room felt the least secure of all of the head rooms.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Should not start closed

**Comment by DrSnips** [comment]
I suggested the shutters as a compromise between walls and windows so people had the option to open them for whatever reason. Personally the best option (in terms of security) would be to move the HoS office into sec so it wouldn't be breached at all.

**Comment by ShiftyRail** [comment]
This is a good change, but the carp issue could be solved by just moving the carp spawner further to the East

**Comment by DrSnips** [comment]
We've already pushed it east in the past but we continue to have issues because they creep west after they spawn.

**Comment by GeneralVeers25** [comment]
I'd like to propose altering this PR a little to include some the greatest hits from Dylan's Brig PR.

https://lambda.sx/ksd.PNG

Notably adding a second solitary chamber, expanding the armory slightly, and giving the Warden a nice door to Interrogation.

**Comment by ghost** [comment]
\>one-thick exterior armoury wall
_AHHHHHHHHHH_

Otherwise I love it

**Comment by ShiftyRail** [comment]
Change the title & CL if you're going to change that PR radically

**Review by MadmanMartian — APPROVED** [review]

**Comment by GeneralVeers25** [comment]
Closed. This got out of hand.

**Pull request closed without merging**
