### PR TITLE
Various HUD Fixes

### LINKED ISSUE #35932: You can see the loyalty implant even if someone is wearing a tinfoil hat
(WEB REPORT BY: tinysaturn REMOTE: 172.93.101.77:7777)
# Revision
09927af122d13c7f6af8f1dc646652a97bb96b28

# Description
Tinfoil hat used to hide this I'm pretty sure

# What you Expected

# What Actually Happened

### LINKED ISSUE #35945: Cannot set arrest status as PAI
When playing a pai with security package installed, cannot set the arrest status of someone. The ' [none] ' field is unclickable. Everything else like viewing security comments or changing medical status works, however.

### PR DESCRIPTION
**Pull request by jwhitak**
# No more Bouncy Security HUDs!

## What this does
This PR does a variety of bugfixes with the new HUD datums.
* Ports over all in game HUD related images to a new child of images so that they can be more easily cleaned up on every HUD update instead of using a string search through every single client image.
image

* Handles offset HUDs differently so that they can be shifted without interfering with the position of the original cached HUD. This affected the Brig Medic and pAI in such a way that their own HUDs would 'bounce' around while in range of any security HUD, OR security HUDs would be permanently stuck offset after entering the range of the aforementioned, depending on creation order of the HUD objects in question. Also, adjusts offset values slightly.
image

* Adds tinfoil hat checks that were forgotten when the security HUD was split into its three components. Now, instead of just the job square being hidden, your implants and arrest status will be hidden as well. Just like the good ol' days...
image

* Removes the now unnecessary pAI hasHUD proc override, which fixes pAI's ability to set people to arrest.
image

## Why it's good
Fixes #35932. Fixes #35945. Fixes the bouncyHUD issue that went unreported on github. Bugfix valids.

## Changelog

:cl:
 * bugfix: Brig Medic HUDs no longer break all Security HUDs in their range, and vice versa.
 * bugfix: pAI can set people to arrest again.
 * bugfix: Tinfoil hats now protect you against all aspects of Security HUDs, instead of just hiding your job.

[bugfix] [ui]

### CODE REVIEW

**Comment by MercuriusGH** [comment]
I'm pretty sure pAI's not setting people's arrest status is a feature, not a bug. The records are meant to be view only

**Comment by jwhitak** [comment]
pAI setting arrest is a feature, has been since pAI had a security HUD, and I know exactly when and how I broke it by mistake.

**Comment by SonixApache** [comment]
:+1: for bugfix, :heart: for whatever else you did (i didn't look)

**Comment by hacker-on-steroids** [comment]
PAI's being able to mess with the records breeds the absolute worst type of powergay
especially after #35865 gets merged

**Comment by djkramer123** [comment]
PAIs being able to set arrest status is horrific

**Comment by Kurfursten** [comment]
This is a fix in its current state. If someone would like to strip pAIs of arrest power (reasonable) they should make a separate PR.

**Pull request merged**
