### PR TITLE
Removes Maintenance Access from all of those who do not Maintain.

### PR DESCRIPTION
**Pull request by ghost**
[discussion][controversial]

We are quick to hate things like space bases in certain game modes, but do not acknowledge that they are a symptom of nearly everyone having free access to what should be the derelict areas of the station and a large number of roles ruthlessly hunting through and digging for valids round after round.  The purpose of this PR is to provide all game modes with more breathing room for antagonistic things to occur station side, as well as for station roles to contribute more towards the actual functioning parts of the station.  Additionally makes illicit hacking into there and maintenance access on agent IDs a lot more meaningful.

Assistant:  Currently acts more like psychotic Mad Max-esque vagrants than actually working as interns for a top-of-the-line research facility.  Should be participating in common areas instead of being a tunnel rat.

HoP: Absolutely no reason to be here.  Needs to handling Command duties and their office.

Quartermaster: In a quasi-head of staff and needs to be tending to cargo.  Absolutely no reason to be a tunnel rat.

Cargo Technician: Has a duty within cargo and has no reason to have this has a basic form of access

Shaft Miner: Makes the least sense of all of the cargo roles with maintenance access.  Has a duty to the asteroid and should not be freely maintenance crawling ever.

Chaplain:  A civilian role who tends to the chapel.  Why the hell would civilians have access to the maintenance tunnels of a secure research facility?

Mechanic: A hybrid role with duties to be upgrading departments and dealing with lesser and more public aspects of research and engineering.  One of the worst offenders of being a maint-crawling valid hunter and already has ludicrous levels of access.

Clown:  Civilian staff that is tailored to the crew.  Why the hell would civilians have access to the maintenance tunnels of a secure research facility?

Mime Civilian staff that is tailored to the crew.  Why the hell would civilians have access to the maintenance tunnels of a secure research facility?

Librarian:  A librarian of all things.  Why the hell would civilians have access to the maintenance tunnels of a secure research facility?

Paramedic:  Should not be running gung hoe into secure maintenance tunnels without a security team getting access and security the scene first.

HoS:  Needs to be handing Command matters and their department.  Crawling through maintenance alone is the last thing this role ever needs to be doing.

Security Officer:  The absolute worst offender of maint crawling valid hunting for the sake of such and the biggest reason for this PR to exist.  If we hate space bases so much then we need to actually give antagonists room to function and not have people pushing every wall in there and eyeballing every tumor out of place until the antagonists have had time to be noticed and for there to be a reason to get maintenance access and to go clear it out.

Detective:  Should not be digging in there until it becomes a security matter.  Give antagonists some room to breathe.

Warden:  No.  And blocking off all of maintenance round start with those barriers is not a valid reason.  That is part of the reason for this PR to exist.

:cl:
 * rscdel: Removes maintenance access from all of those who do not maintain the station

### CODE REVIEW

**Comment by Irradiation** [comment]
>Almost nobody left with maintenance access

I, for one, welcome our Dorms/Bathroom cult base.

**Comment by Senaat1** [comment]
Fuck you, anti-maintenance gang already took maintenance access from lawyers (which was a travesty and a miscarriage of justice) and now want to rob the innocent assistant and security officer of their right to roam free?

I'm going to THUMBSDOWN this.

**Comment by drawsstuff** [comment]
Harse back at it again with the shit takes

**Comment by ghost** [comment]
I can smell the filthy c*ders tactics and stratagem from a thousand kilometers away.

This is a PR made so ridiculous that no one shall support it. The c*der will follow it up with a more reasonable reduction to maint access changes after this one is denied in hopes to represent his new edition a reasonable balancing act.

DO NOT FALL FOR THEIR MIND TRICKS

**Comment by Senaat1** [comment]
The Free Access To Maintenance Always, Now! Committee (FATMAN) wants to make it clear that NO removal of maintenance access will be tolerated.

**Comment by KingofHONK** [comment]
A daring PR, upvoted for the pure balls on this madman

**Comment by ghost** [comment]
> 
> 
> Harse back at it again with the shit takes

image

**Comment by SonixApache** [comment]
cargo techs occasionally have to go unfuck mules in maint but then again nobody uses mules so it's probably fine

i see (and have heard) no reason for this to not be merged

**Comment by Kurfursten** [comment]
I do think paramedics and librarians (journalists) should get to keep maint access. Paramedic gives up chemistry access for more mobility in rescue. Journalist is so otherwise superfluous it's nice to give them the ability to slink around and take shady pics.

**Comment by ShiftyRail** [comment]
If this & #28582 both get rejected, then by res judicata we are legally forbidden from even bringing up the subject for upwards of one year

**Comment by drawsstuff** [comment]
> > Harse back at it again with the shit takes
> 
> image

Is it not security's job to patrol and look for suspicious activity? What better place than the tunnels.

**Comment by PavelCIA** [comment]
I'm sure once nobody has maintenance acccess /vg/ will turn into a High RP server

**Comment by jknpj** [comment]
> I'm sure once nobody has maintenance acccess /vg/ will turn into a High RP server

You can remove the access from people but you can't remove their inner shitter. People will just hack their way into maint and nobody will say anything because it will be the norm. Don't you remember the last no-maint access period?

**Comment by xeroxemnas** [comment]
This is guaranteed to die because of the assistant main faggos but you get an A for trying.

**Comment by ShiftyRail** [comment]
@xeroxemnas there is probably more political pressure coming from the sec mains than assistants here.

**Comment by xeroxemnas** [comment]
>implying post-flarg security isn't just assistants in red.

**Comment by dunsel-hordon** [comment]
No civilian jobs should have maintenance access. Along with cargo, science, medical. Mechanics are a hybrid between science and engineering and should keep their maintenance access. Head roles should also have it along with sec as they need to be able to patrol. Obviously engineers need it too.

**Comment by Senaat1** [comment]
> > implying post-flarg security isn't just assistants in red.

As it should be.

**Comment by DoomerGloomer** [comment]
Detective should absolutely have it, as well as Paramedics.  Unless you want paramedics to just be CMC/Telepad jockeys, which is gross.  Otherwise mostly agree.

**Comment by ShiftyRail** [comment]
"Assistants in Red" might be an exaggeration, but Security is way funnier - for you [usually] and other players [most definitively] - if you don't take it that seriously.

**Comment by Kammerjunk** [comment]
restricting 99% of the playerbase (that is to say, everyone except our 5 engineering players) from accessing maint will not cause more maint bases

**Comment by gurfan** [comment]
upvoted solely because this is the engineercreep we need

**Comment by Senaat1** [comment]
I think the problem is the fact that cult sucks, not that sec has maint access.

**Comment by ghost** [comment]
I rest my case.
A FUCKING HOUND

**Comment by PavelCIA** [comment]
How to fix antags being forced to antagonize in maintenance:
1. remove AI

**Comment by beesil** [comment]
Removing maint access from paramedic seriously hinders their ability to retrieve bodies, as well as encourages tsci paramedics like Doomer said. I agree that validhunting mechanics is a problem, but removing their maint access isn't the right way to solve it. Lukewarm on the rest.

**Comment by ShiftyRail** [comment]
If the intent of this is to strip security of its maint access, then why not, but something something reactionary PRs

**Comment by DrSnips** [comment]
You had me with the first half and then the second half made me drop this.

**Comment by ghost** [comment]
repeating myself from the other PR but mucking with access levels is a very ass-backwards way of getting at what should really be a frank discussion of what our expectations are for roles and gameplay and we already did this a year ago

at least this one is pushing people in that direction

**Comment by plosky1** [comment]
This is like a bill in the US, where there is tons of crap to hide the one real change. If your goal is to remove sec from maint, I propose doing it like this.

Regular security: No longer has maint access unless threat level is blue/red.
Detective: Has maint access for investigations.
HoS: Has maint access.

This will prevent sec from maint diving UNLESS there is an active threat. Then they are allowed to go and patrol as needed.

**Comment by TGFH** [comment]
Baronze is 100% right here. Dumb bad faith PR made out of anger and probably intended to be a door in the face type thing.

**Pull request closed without merging**
