### PR TITLE
New APCS, Cells, Power switches

### PR DESCRIPTION
**Pull request by kol1th**
# Scope of PR

This PR adds new sprites from **CEV-ERIS**. The sprites are for APCs, Light switches, and cells. 

Like comment and subscribe : )
# Clever Image Section Name

** IN ACTION:**
image

## APCS
**OLD:**
image

**NEW:**
image
## LIGHTSWITCHES

**OLD:**
image

**NEW:**
image

## CELLS

**OLD:** 
image

**NEW:**
image

# Changelog
🆑 
* imgadd: Adds new sprites for APCs, lightswitches, and cells. Hurrah!

### CODE REVIEW

**Comment by clusterfack** [comment]
Tbh I like the old cell and lightswitch better

**Comment by gbasood** [comment]
I prefer old cell but new lightswitch

**Comment by clusterfack** [comment]
What does the light switche's off state look like?

**Comment by kol1th** [comment]
image

**Comment by CptWad** [comment]
I like the switches, easier to click
but I agree on the cells, do they match with the APC or something? Post more pics

**Comment by kol1th** [comment]
They match the APC, yes, but I wanted to just see what others thought about it. 

image

**Comment by Lokiamis** [comment]
In-game screenshot pls

**Comment by kol1th** [comment]
@Lokiamis Updated original post.

**Comment by Ephx1** [comment]
The APCs, like your other button sprite fiddling, look very off with the flat walls that we have

**Comment by Lokiamis** [comment]
Do the APCs look strange when placed on the left, right, or top side of a wall? It looks like they have a base which is supposed to touch the floor.

**Comment by kol1th** [comment]
Look about the same as they do with our current ones. I don't have pics of those.

**Comment by 9600bauds** [comment]
AAAAAAAHHHHH THE PERSPECTIVE 
AAAAAAAAUUUUGHHHHHHHHHHHHH THE PILLOWSHADING

**Comment by kol1th** [comment]
I see NO PILLOW SHADING here buddy

**Comment by Exxion** [comment]
Gonna be honest: Not really a fan of the new APCs
Don't like the colors, and our current ones are kind of... iconic? But that's a shit reason not to make them look better

That said, as with nearly all purely-aesthetic changes, I only give roughly 8% of a shit

**Comment by 9600bauds** [comment]
Divert thine eyes to the APC and its majestic coat of pillowshading

**Comment by 9600bauds** [comment]
Also AAAAA MUH ATOMICITYYYY

**Comment by kol1th** [comment]
I've never heard the word "atomic" in my life.

**Comment by Exxion** [comment]
If you want a specific critique, the new APCs' colors are too dull. They should  be closer to the current ones. Especially the screen colors, though if the case were brighter, it would also be nice

**Comment by Shadowmech88** [comment]
I like our current cell sprites better.

**Comment by kol1th** [comment]
The old APC sprites were stark contrast with neon blue, I don't think I want that again

**Comment by Exxion** [comment]
>contrast is bad

**Comment by kol1th** [comment]
It's not a good contrast

**Comment by Exxion** [comment]
I agree that the old APC sprites are... outdated, but the contrast is like the least of their problems, if it's even a problem

**Comment by kol1th** [comment]
🤷‍♂️

**Comment by RoyalSev** [comment]
There are not enough words to describe how much I hate the Goon-style 2.5D/Isometric sprites. Not a fan of the colours either

**Comment by kol1th** [comment]
Because you don't know enough? 😎

**Comment by RoyalSev** [comment]
Catch these hands motherfucker

**Comment by kol1th** [comment]
👐

**Comment by N3X15** [comment]
I really don't know why you're so intent on changing the style of the station when this stuff clearly doesn't work on our flat walls.

**Comment by kol1th** [comment]
I think they look better. 🤷‍♂️

**Comment by N3X15** [comment]
The style isn't even remotely the same and they look out of place.

**Comment by kol1th** [comment]
I think it's just an upgrade.

**Comment by N3X15** [comment]
upgrades

**Comment by kol1th** [comment]
MUH
PERSPECTIVES

**Comment by 9600bauds** [comment]
🎨

**Comment by JustSumBody** [comment]
Tfw to intelligent to understand art

**Comment by yclatious** [comment]
Kolith, your intention is good, seriously, I know you mean well, but for fucks sake my man, what is this perspective bull you are trying to push us in, if you want us to get a graphical upgrade so badly, remove the perspective bollocks or ask a spriter to remove it for you, adding in graphical upgrades from stations with different walls and different perspectives is not a upgrade.

**Comment by SonixApache** [comment]
why would you use the wrong colors for the BSOD

**Comment by DamianX** [comment]
I like all the old ones better.

**Comment by Exxion** [comment]
The more I look at the new APCs, the shittier they look

**Comment by PJB3005** [comment]
rip

**Comment by ghost** [comment]
shoulda just removed the new cell smh

**Pull request closed without merging**
