### PR TITLE
killed my other PR and coded something useful like prescription sec/medHUDs

### PR DESCRIPTION
**Pull request by ghost**
:3c
Prescription sec huds have a chance to spawn in regular security lockers and prescription medical huds spawn in medical lockers

:cl: 
 * rscadd: Prescription sechuds have a chance to spawn in security lockers
 * rscadd: Prescription Medical huds spawn in medical lockers
 * rscadd: Prescription Mesons have a chance to spawn in engineering lockers

### CODE REVIEW

**Comment by ghost** [comment]
MIGHT AS WELL GIVE THE MESONS ABLE TO SPAWN

**Comment by ghost** [comment]
chance to because there's already a lot of those types so you have to be REALLY unlucky for you to not roll prescription glasses for your job if you need them

**Comment by Shadowmech88** [comment]
What if we just added contacts that could be equipped without actually taking up an inventory slot, allowing you to use all eyewear with bad eyesight?

Also they have a 5% chance to fall out each step.

**Comment by SonixApache** [comment]
>he actually did it the absolute madman

neat, good shit

**Comment by CodenameB** [comment]
Instead of a chance roll, can we have one guaranteed pair per location and let R&D craft more?

The reason being, it seems silly to have random chance determine if medbay or security are filled with prescription glasses, why would Nanotrasen ever stock that many?

**Comment by SonixApache** [comment]
Having them coded ingame makes it easier for mins to do stuff with them.
Naturally it'd be great if relevant jobs would start with appropriate prescription eyewear if required, and it'd be nice if you could just slap prescription glasses onto HUDs to combine them or something, but this is a good step.

**Review by PJB3005 — APPROVED** [review]

**Comment by Intigracy** [comment]
add a space between the * and rscadd

**Comment by ghost** [comment]
doooooooone

**Pull request merged**
