### PR TITLE
Wiz limbs AND organs become organic if they're robotic on spawn

### PR DESCRIPTION
**Pull request by gbasood**
Added three procs to humans for use in situations similar to wizard spawning:

``` DM
make_all_robot_parts_organic()
make_robot_internals_organic()
make_robot_limbs_organic()
```

And changed the code that made wiz organs organic to use those.

Previous shitty self-merge did not include robotic limbs because I fucked up

### CODE REVIEW

**Comment by gbasood** [comment]
TRAVIS WHERE ARE YOU

**Comment by ghost** [comment]
Don't worry I'm sure you've 100% tested this and know it won't cause a compile error so you may as well self merge

**Comment by gbasood** [comment]
I actually did test if this built before I made the PR

**Comment by ghost** [comment]
Well of course you did, what kind of person wouldn't?

**Comment by gbasood** [comment]
Maybe the kind of person who wouldn't check if their noirblock broke monkeymanning :^)

**Pull request merged**
