### PR TITLE
Secret Repo Decommissioning 3: Account Age Checks

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Moves account age checks for server votes and AAC script execution to the public repo.

## Why it's good

Transparency and eventual compliance with AGPL requirements.

## How it was tested

It wasn't! It's just a copy-paste, so nothing will break. Procnames have been changed to prevent a secret repo conflict.

## Changelog

:cl:
 * rscadd: Account age checks for voting and AAC scripting have been moved to the public repo.

### CODE REVIEW

**Comment by hacker-on-steroids** [comment]
when teaching newfag engineers, i've seen at least 2 of them stopped by the AAC check
it should also give the player a message instead of simply not working
perhaps the better alternative would be to make the AAC unable to lag the server to a crawl in the first place (limit it to updating 50 devices per tick? add a second or 2 cooldown on the manual single-execute button?)
i'm not sure if the script auto-run continuing even after the console is unpowered got fixed

**Comment by nervere** [comment]
The AAC check is definitely way too strict. 7 days would be a more reasonable account age to restrict.

**Comment by CrazyAmphibian** [comment]
\>30 days to use the AAC
this explains a lot about my early engi struggles...

**Comment by Eneocho** [comment]
Oh that explains why I've had issues teaching newengis how the engines work.
Yeah maybe pull it down to 7 days like the others say.

**Comment by CrazyAmphibian** [comment]
Why does the AAC have a age limit, anyways?
All it's really used for is pipe autism

**Comment by Eneocho** [comment]
> Why does the AAC have a age limit, anyways? All it's really used for is pipe autism

it's can be used to instantly switch all the vents and scrubbers to plasmaflood settings and to instantly plasmaflood mapwide, and ban evaders have a history of doing just that, so an age check was put in place.

**Comment by CrazyAmphibian** [comment]
> it's can be used to instantly switch all the vents and scrubbers to plasmaflood settings and to instantly plasmaflood mapwide, and ban evaders have a history of doing just that, so an age check was put in place.

Ain't that the CAC? Last I checked the AAC could only switch 1 scrubber/vent (that doesn't have an id) at a time

**Comment by Eneocho** [comment]
Yes, the CAC can be used to that effect but that requires an ID with access. An AAC with the proper script can instantly swap settings for all vents and scrubbers with no access required, you do need a script though, but the floodscript is floating around and is not hard to find.
All mapped vents/scrubbers have a unique ID on the same frequency, so a script that tells ALL vents/scrubbers to switch settings to eject plasma and NOT scrub it back is a simple thing. It's a long ass script since each vent/scrubber is independent from each other, so if you have 50 scrubbers and 50 vents, you have to command each of them independently.

**Comment by CrazyAmphibian** [comment]
just get rid of copy+pasting AAC scripts

**Comment by Eneocho** [comment]
That'd make the AAC useless, as the main use for the AAC is to automate annoying to set up stuff, and for that you often use script pasting, I tend to make my vents/scrubbers with the same IDs and frequency so I just paste my vents/scrubbers script which saves me a bit of time. Other engineers/atmosians do the same.

**Comment by CrazyAmphibian** [comment]
\>he doesn't make a new script every game
weak.

**Comment by SonixApache** [comment]
add feedback for the player while you're at it

**Comment by hacker-on-steroids** [comment]
>no feedback

:(

**Pull request merged**
