### PR TITLE
Fixes big eclair sprite being invisible

### PR DESCRIPTION
**Pull request by JustSumBody**
It's named big_eclair in the .dmi so there we go

### CODE REVIEW

**Comment by Kurfursten** [comment]
Dammit @DrCelt what were you thinking in #12938 ? You can't just give a food bitesize 30. That means every time you take a bite, you take in 30u reagents. Most foods have a bitesize around 2-3 and the largest around 5.

There are two  main problems with this:

>1. The food item doesn't feel very big when you can eat the whole thing in 2 bites
>2. Because we decided to keep meme iv drips, you can simply drain all the reagents out of a massive eclair with an iv (anyone can build this with 2 sheets metal), then load chloral, cyanide, whatever into the eclair. Now instead of delivering a usual 5u reagents like a syringe, you can forcefeed to deliver 30u reagents.

**Comment by ghost** [comment]
@Kurfursten it's a FEATURE

**Comment by DrCelt** [comment]
@Kurfursten it's a FEATURE

**Comment by 9600bauds** [comment]
You can already do all that by just using fruit, which can have huge bitesizes

**Comment by Kurfursten** [comment]
@9600bauds True (the bitesize calculation there is pretty dumb too), but I believe the largest you can get with grown foods is 26, so this is even more creep.

**Comment by Probe1** [comment]
Yeah thats pretty retarded and something else being retarded is no excuse to make other things retarded.

BUT thats not really the scope of this PR so lets just have a simple bug fix then fuck with the eclair.

**Pull request merged**
