### PR TITLE
Fixed non-blob meteors being invisible while fired at the station

### LINKED ISSUE #23666: Meteor gun fires invisible meteors
Uh

### LINKED ISSUE #27307: cannot see meteors moving through space
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
ad88297da8d1505caef75d2d19c6ce2f6282ebeb

I cannot see meteors moving through space. Dorms told me to make a bugreport about it, I remember being able to in the past, and I'm not sure why this is happenning right now, something might have changed.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #27307
Fixes #23666

:cl:
* bugfix: Fixed meteors being invisible while fired at the station. (gurfan)

### CODE REVIEW

**Comment by DamianX** [comment]
I see this is adding new icons but surely those already existed somewhere? Are you copypasting them rather than pointing the objects to the right icons?

**Comment by DeityLink** [comment]
> 
> 
> I see this is adding new icons but surely those already existed somewhere? Are you copypasting them rather than pointing the objects to the right icons?

moving projectiles use the _pixel icon state, while static one use the regular icon_state. There's no reason to have a regular meteor icon_state (just having _pixel icons would suffice) but I've added both so that badmins who spawn them manually can easily select and delete them. So blob meteors are now visible when spawned (they previously only had _pixel) while regular meteors now also have _pixel.

Reminder that meteors are projectiles.

Although now that you mention it, I gotta remove the other directions. _pixel states only need one.

**Comment by DamianX** [comment]
Doesn't sound great but I'm glad I helped.

**Comment by Kurfursten** [comment]
Are you going to do that removal as part of this PR?

**Comment by DeityLink** [comment]
> 
> 
> Are you going to do that removal as part of this PR?

Turns out meteors already had only one direction I'm dumb, you can merge it now.
image

**Pull request merged**
