### PR TITLE
Gunk Soup Embassy and Gunk Soup sprite update.

### PR DESCRIPTION
**Pull request by Eneocho**
Many thanks to @tinysaturn for the idea and spritework.
Space Turkish officials have come to parlay with Nanotrasen at the Embassy. The Gunk Soup Embassy, that is.
Made with 2 cockroach meat, 1 cardboard sheet, 1 red crayon, 5u Water and 5u Gunk.
sprite2 sprite1
Consuming the Gunk Soup Embassy will spawn two cockroaches with a custom name. Killing these special cockroaches will drop a fez.
Updates the regular Gunk Soup sprite to something more unique.
ezgif-5-b2ae6916e6
:cl:
 * rscadd: Gunk Soup Embassy, made with 2 cockroach meat, 1 cardboard sheet, 1 red crayon, 5u water and 5u gunk.
 * tweak: Changes Gunk Soup sprite.

### CODE REVIEW

**Comment by Theophrastus1** [comment]
jesus christ, from small beginnings to backroom deals with the turkish embassy

**Comment by Hinaichigo** [comment]
You could consider changing the word politician to diplomat.

**Comment by Eneocho** [comment]
> You could consider changing the word politician to diplomat.

I could, then again people refer to politicians as cockroaches and that kinda fits as a double-layered joke.

**Comment by Hinaichigo** [comment]
When's the blinking sprite used versus the non-blinking?

**Comment by Eneocho** [comment]
> When's the blinking sprite used versus the non-blinking?

I actually intended to have both blinking but overwrote the blinking frame when giving the roach the fez.
As for the sprites, there's a 50% chance for either sprite when cooking with a 10% chance to swap to the other sprite after 20 ticks (actually 20% chance for a sprite roll then 50% for either sprite to be selected).

**Comment by Eneocho** [comment]
> jesus christ, from small beginnings to backroom deals with the turkish embassy

GunkCo(TM) has risen.

**Pull request merged**
