### PR TITLE
Adds a thing

### PR DESCRIPTION
**Pull request by clusterfack**
It does work but I need to find a way to disable diagonal movement. Will make movement more responsive and more independent from clientside latency when its finished.

### CODE REVIEW

**Comment by BarneyGumball** [comment]
God yes make my Australian ping less noticeable :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Megamaw** [comment]
so uh, what is it?

**Comment by Intigracy** [comment]
"Will make movement more responsive and more independent from clientside latency when its finished."

**Comment by clusterfack** [comment]
Stills needs a little work to be finished

**Comment by clusterfack** [comment]
Alright, after some discussion on byonds forums found the best way to make it cardinally movable and not 8 directionally movable. Great job boys pack it up move it out.

**Pull request merged**
