### PR TITLE
Library Sprites

### PR DESCRIPTION
**Pull request by Kurfursten**
image

New sprites for 3 library machines + shag carpet

Credits
Research archive: Zeek
Accounting computer: Civ13
Others: me

🆑 
* rscadd: New sprites for accounting computer, library scanner, research archive. New shag carpet.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you make the carpet or is it limited only to mapping?

**Comment by Eneocho** [comment]
Can you make the carpet or is it limited only to mapping?

**Comment by Kurfursten** [comment]
Shag carpet is current not obtainable but exists in item form, meaning if it is mapped you can pry it up and move it. I thought it would be kind of funny if it was so old from the Space 70s that you could only get it by prying it up, but maybe a method will be added to acquire it later like a secret item in the habitat depot vendor.

**Comment by DeityLink** [comment]
I think the carpet should have some borders like regular carpets do, maybe of a darker shade of orange. It's a bit hard on the eyes right now.

**Comment by Kurfursten** [comment]
Normal carpet makes sense to have a border because we use it more like a rug in our mapping, but this isn't intended to be a rug.

This version is actually both darker and oranger than the original, this was workshopped in the spriting channel. I'm pretty happy with where it landed, A certain harshness _is_ the 70s America aesthetic.
e2d6f2f3f545b407fc17fbaa47c23a28
Old-office-cubicles-and-retro-open-plan-office-layouts-from-the-70s
Cf-dSzjWsAQJsas

**Comment by west3436** [comment]
I can smell this image

**Comment by Eneocho** [comment]
I expect at least one adminbus themed around the backrooms (original concept with no monsters, just eternal tedium) using this floor and the sandstone walls.

**Pull request merged**
