### PR TITLE
Fixes zero blood problem

### LINKED ISSUE #17512: Can't add blood to a human with 0% blood
#### Specific information for locating
I'm guessing here:
https://github.com/vgstation-coders/vgstation13/blob/2e0b33bf5e78773df8a72a6fdf85a0d7057dd71c/code/modules/organs/blood.dm#L266-L296

#### Length of time in which bug has been known to occur
Not a recent thing. Could be very old for all I know.

#### Server revision
Game: 956843085a7a5b417857547b64a6fc7a09526cb0 
Patches: 1f151d7a38ff2301172c5585b8ec3a972ca3efe6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Pathid**
Fixes #17512

:cl:
* bugfix: Fixed a long-standing bug which caused the blood vessels of a human whose blood level had dropped to zero, or close to it, to glitch out and become unusable forever.

### CODE REVIEW

**Comment by Blithering** [comment]
Does this mean we can revive husks?

**Comment by Probe1** [comment]
That isn't a bug or related.  Husks have to be cloned in a t3 cloner.

**Comment by Blithering** [comment]
I'm talking about the fact that when you're husked by burn damage your blood levels get set to 0, even if you are then patched up to defibbable levels you can't be revived because of this

**Comment by Probe1** [comment]
Oh?  I didn't realize your blood was set to 0.  My mistake.

**Comment by Pathid** [comment]
@Blithering It probably does mean that. The defib checks for M_NOCLONE instead of M_HUSK like it really should.

**Comment by Blithering** [comment]
Neat, station of the living dead soon.

**Pull request merged**
