### PR TITLE
Economy 2019 Part B

### PR DESCRIPTION
**Pull request by Kurfursten**
The main economy reform was too vulnerable to blocking because it lacked atomicity. I'm going to split it in three to make it easier to push through.

Part A is aimed at accounts issues, Part B will target vending machine improvements, and Part C will be where we take on the miner metaclub.

I changed the plan for the malfunction a wire a bit based on feedback (e.g.: bolas from the secvend, syringes from the medvend).

🆑 
* tweak: Throw wire will now only throw free goods.
* bugfix: Fixed a bug where partial packs could be used on anything
* bugfix: Fixed a bug where vending machines would not be turned off by their turnoff effect

### CODE REVIEW

**Comment by ghost** [comment]
I do not like unbeatable protections for things, such as DNA locks, pod locks and special unhackable vox vendors.

This will make all (priced) vendor items unobtainable without an account with sufficient money, despite having physical access and multitude of reasonable tools to do so. Which ruins my immersion among other things.

Having a currency/economy system in place is good. However there should be a way to play around it at all levels with effort.

**Comment by Kurfursten** [comment]
We can go back to the malfunction wire system from the original PR but I thought people didn't like it. Or we can even have both.

Malfunction wire basically damages the machine for a chance of dropping a bunch of goodies at once. On the plus side it's more active than babysitting a throw machine or setting up a monkey next to it - and crew are incentivized to care if someone's hacking the machine since it's annoying if they break it with hacking.

**Comment by bathosbathtime** [comment]
I think people disliked losing the throw wire, and not the malfunction wire itself.

**Comment by SonixApache** [comment]
@codeungabunga can't you just use cold hard cash to pay for the stuff like everyone else?

**Comment by Kurfursten** [comment]
@bathosbathtime You have that backwards? This new version keeps the throw wire and it's the one the silentgang is downvoting. I tried to appease them with this new version but you can never know what the silentgang wants.

**Comment by ghost** [comment]
@SonixApache what I mean by that is that there should always be a way to get the vendor goods without paying.

**Comment by SonixApache** [comment]
i cannot condone institutionalized criminality

**Comment by aceedex** [comment]
As the representative for the silent gang I will communicate that everyone enjoys some good ol free shit once in a while. The only extra security features Id like is on custom vendors

**Comment by bathosbathtime** [comment]
I mean that now there is no way to get goods from hacking.  The throw wires as is in this PR is good enough for me, but the lack of a malfunction wire means you have removed hacking as a means to get goods from vendors entirely.

**Comment by Kurfursten** [comment]
I can bring back the malfunction wire but it causes problems with expensive item vendors if the labor points PR is rejected. Miner has less incentive to mine when he's better served using a multitool to get his toys.

The problem in a general sense is that it's hard for money to be valuable when it is much, much easier to just hack a machine than acquire money. People complain there's nothing to spend money on, but that's because the primary use of money is for vending machines that can be hacked for goods.

Even my original malfunction wire that damaged the machine was only a partial fix to this problem, but it does make getting free stuff slightly more difficult so it's a step in the right direction as a compromise at least.

**Comment by aceedex** [comment]
I dunno, I usually find its better to mine than to wait for RNG to give me what I want considering the metric ton of stuff in the miningvend already

**Comment by SonixApache** [comment]
Hacking machines to get free things is a dumb mechanic that should be replaced with something more risk/reward than just pressing a button and placing a mouse down.

Fuck the wire. Restrict item-throwing to the aggressive advertising random event.

Replace it with breaking the machine to get stuff out of it. Make it a crime that can be seen. Make it have consequences to not use your limited resources.

**Comment by Kurfursten** [comment]
We could go the LAWWW route... It might be involved to make it work though.

Ifsomeone supplies a siren/alarm sound I could make it flash lights and play LOUD NOISES when you smash in. It could even send a beepsky-like All Points Bulletin on the sec channel.
>Alert. Damage detected to NT vending property in Central Primary Hallway.
Swipe sec ID to disarm alarm.

Alternatively... what if vending machines regularly took pictures of the area around them? They would prune pictures older than say, 15 minutes. Detective ID swipe could access the memory banks and take a picture out before it gets pruned. This could open up some serious investigation potential for crimes even unrelated to commerce. "There was a fight in tool storage? Detective, pull the pictures from the toolvend... let's see if they were in frame."

**Comment by aceedex** [comment]
I still hold that getting a mouse to get hit with items costs the most precious resource in the game: time
hell, make the interval between item launches vary from machine to machine if its THAT big an issue, but I feel it aint

**Comment by agentofzog2** [comment]
Hacking every machine to toss random items at passerby is a time honored tradition and this gay PR will kill it.

**Comment by bathosbathtime** [comment]
I feel that the malfunction wire gives security and the rest of the crew a reason to prevent thievery, as a failed attempt can result in a loss of goods for everyone.  One of the bigger problems I see with throw wire hacking everything is that security doesn't have much of a reason to stop getting free stuff, and even has many reasons to not prevent the hacker(s) as the crew may interfere so they keep getting free stuff as well.
The picture idea is pretty neat though, I do like the potential for more investigative opportunities.
Siren is megabad, feels way too braindead.

**Comment by ghost** [comment]
You should separate the bug fixes into another PR since nobody will disagree with those.

**Comment by FudgePucker** [comment]
Instead of just have the throw wire shoot out free items at people that walk by, make it throw purchased items REALLY HARD at people that buy things, doing like 10 brute damage and knocking them down.
Would be better for nefarious deeds.

**Comment by Kurfursten** [comment]
The bugfix parts of this will come back separately

**Pull request closed without merging**
