### PR TITLE
Changes the Nar'Sie Spawn Animation

### PR DESCRIPTION
**Pull request by ihadtoregisterforthis**

### CODE REVIEW

**Comment by Zth--** [comment]
Oh shit

**Comment by clusterfack** [comment]
See now this is closer to what I was imagining at the start

**Comment by AI-Is-Rogue** [comment]
Now this is the entrance Nar'Sie deserves.

**Comment by jknpj** [comment]
beautiful

**Comment by Shadowmech88** [comment]
This is great. Did you make this?

**Comment by ihadtoregisterforthis** [comment]
Yes, all OC, do not steal.

9 frames are spawn animation, and other 9 are regular narsie moving for a smooth transition. I left the code intact since I couldn't get any meaningful difference changing the `sleep(10)` line on a personal server.

This is what it looked like
https://webmshare.com/M0gbL

**Comment by ghost** [comment]
@ihadtoregisterforthis Can I port this to my codebase, with credit?

**Comment by Probe1** [comment]
Go for it @gt33 our licenses are compatible for art assets.

**Comment by ihadtoregisterforthis** [comment]
Legalities aside go ahead

**Comment by ghost** [comment]
Thanks :)

**Pull request merged**
