### PR TITLE
Ungunks carog computer

### PR DESCRIPTION
**Pull request by ShiftyRail**
#19452 had a good idea (somewhat) but a terrible execution that resulted in a very common interaction being made unnecesarily more tedious
It also had the unintended (?) consequence of making a quick emag+order guns more time-consuming which is not fun.

Maybe we can find a way to ensure safety of your bank account that's not just adding a layer of tediousness.
:cl:
- rscdel: You no longer need to write down your pin for each and every interaction at the cargo computer.

### CODE REVIEW

**Comment by SonixApache** [comment]
alternatively, don't straight-up delet, but make it only apply when the account is set to high security
and then, god forbid, maybe someone will make account security a character preference option

**Comment by WhiteHusky** [comment]
The entire PR was about bank account security levels were not completely respected or not at all. The charge flow was supposed to ensure that it would maintain being consistent and you'd be safe knowing that if you had an account security of `1` you'd need a PIN to charge from your account. Not have it bypassed because a random machine didn't respect it (except in strange edge cases).

We could refactor account securities that'd allow the old 'Swipe N' Charge' we are used.

```
0 - Account Number
1 - Card Present -- DEFAULT
2 - Account Number + PIN
3 - Card Present + PIN
```
Which would really need a change to the proc that does the whole security checking and adding the selection to the ATM.

**Comment by WhiteHusky** [comment]
The whole Supply Console was caught in this idea due to how it charges from the person's account by default unless requisitions was turned on, using the Cargo Account's funds.

**Comment by ShiftyRail** [comment]
@WhiteHusky If this was what your idea was about then it was actually much more trouble than it's worth

People use that machine a lot and you needed to type your pin for EACH item ; medbay players can order 4 crates of blood bags. That's just tedious.
It's also a set of 2 input prompts, which are frankly annoying.

You need to find a better way to do it.

**Comment by ProfanedBane** [comment]
I was gonna try some stuff where for the PIN thing it just checks your IC notes if your pin is located there and auto enters it if so, could be a decent solution. Of course you'd need to do some anti meta shit like have lings know the ic notes of people they succ etc.

**Comment by ShiftyRail** [comment]
Losing your ID should have consequences, including someone buying shit with it.

**Comment by WhiteHusky** [comment]
Thanks to @SonixApache to suggesting changing the check security proc because I was about to throw a fit to what was done initially.

**Comment by ShiftyRail** [comment]
Your idea rendered a basic interaction a pain in the ass to execute, I'm honestly surprised nobody smashed the revert button sooner

**Comment by SonixApache** [comment]
I said this in the discord and I'll say it again here.
Why do cargo computers not try to subtract from the wallet first?

**Comment by WhiteHusky** [comment]
@SonixApache Due to how Cargo Computers actually take funds.
They don't take funds immediately after an order is requested, instead once the order is 'Approved' and delivered it'll be taken from the source account.
Otherwise it'll be taking from the wallet *through the air* which kinda rubs wrong.

Honestly I've should've just made it where the funds are taken and held instead permitting that the computer can take funds in the future.

**Comment by spoonylove** [comment]
Can you do slot machine account memes again?

**Comment by SonixApache** [comment]
@WhiteHusky Adding more security levels might be interesting. Consider #19547 if you do it.

**Pull request merged**
