### PR TITLE
Breaks up Chemistry-Reagents into different files

### PR DESCRIPTION
**Pull request by MadmanMartian**
good lord

:cl:
 * tweak: The chemistry reagents file has been broken up into individual files. Please report any discrepancies.

### CODE REVIEW

**Comment by Irradiation** [comment]
Debatably makes it more of a mess to find a specific reagent, as you have to sift through arbitrarily classified files instead of just CTRL-F'ing something.

On the other hand, putting Drinks into their own section is just about the only one I'm 100% onboard with.

**Comment by utilitas-** [comment]
great now I have to ctrl+f through ten different files if I want to barman while I chemistry
it would be acceptable if there were only two files, one for chemistry and one for all the drinks

**Comment by MadmanMartian** [comment]
but if you want to barman while you chemistry

A) Just go to the drinks reagent page
B) The recipe location haven't been touched, just the reagent definition locations

**Comment by utilitas-** [comment]
All the chems and drinks are in the same file, so I just need to open one tab to know all of them.
Separating them into chemicals and drinks makes sense, at least. Otherwise all the categories are very arbitrary and there's no reason to split them up into ten different files. Except for incense, that should really be in its own file. Split it up into chemistry reagents, drinks and incense.

**Comment by MadmanMartian** [comment]
Why are you looking for reagent definitions while you play?

**Comment by Probe1** [comment]
I was going to merge that to be honest.  I just needed to back-burner it because of the size and time it would take me to check over.

**Comment by utilitas-** [comment]
Because it's significantly more convenient than the wiki pages?

**Pull request closed without merging**
