### PR TITLE
Leather Jackets are IN

### PR DESCRIPTION
**Pull request by ManopolisJones**
It was a pain in the ass to do, but it was totally worth it.

## What this does
Separates the leather jacket from the greaser outfit, adding a new leather jacket suit item, as well as adding support for grey and vox races. New leather jackets has storage and can hold an airtank and flashlight in it's suit storage slot, much like hoodies. Adds the new leather jackets and it's variations to the Suitlord, the nar-sie variant specifically requires you to hack contraband for it.

jacketicons

thesetwoguys

2dude

meandthehomie

whatitdo

Poor Fatty

what, how

looky here

## Elaboration
This has been a long time coming for me, I was always thinking we needed some leather jackets proper, but considering they were stuck behind the greaser outfit, nothing was getting done about it. That is of course until now. The greaser outfit proper is the shirt from the casual secoff outfit with the pants from the original greaser outfit. This is most prevalent from the fatsprites, considering they had a pretty unique way of showing you were a fatass with your belly sticking out. I thought it was good so I stuck with it. The hardest to do was the vox, which just tells me why nobody ever adds vox support to outfits, but using the HOP outfit as my base to edit off of, I think it turned out pretty well. The only real issue with this PR is that the old maint spawn on box where you'd get the greaser outfits won't have leather jackets in them, which I'll leave for somebody else to touch (since that's rearing closer into the relm of mapping, which I am not yet ready for). It also bears mentioning that unlike the original greaser outfit which was a random variation via "colors", the alternate jackets (tunnel snakes, spider, nar-sie) are more like their own thing, this was of course to add support to holding items inside the jacket, as well as the suit slot. I personally hope to see more jackets in the future, but this'll have to do until then.

:cl:
 * rscadd: Adds new leather jacket suit items to a suitmaster near you!
 * tweak: greaser outfit now supports vox and grey races natively.

### CODE REVIEW

**Comment by Eneocho** [comment]
Could you add a variant that's made with leather sheets?

**Comment by ManopolisJones** [comment]
> Could you add a variant that's made with leather sheets?

good idea, but not for this PR

**Comment by wotisjanitor** [comment]
could you fix the grey gimp suit sprite as well? its too tall. this issue talks about it #33021

**Comment by Hinaichigo** [comment]
> Could you add a variant that's made with leather sheets?

Would be cool to have different colors and properties of leather and such based on the creature it came from.

**Comment by wotisjanitor** [comment]
@Dacendeth do you got something to say

**Comment by NigglyWiggly** [comment]
This is real good, whoever made the original greaser outfit sprites is a dumbass for not doing it this way in the first place tbh

**Comment by Kurfursten** [comment]
I know keeping your changelog short required some restraint so I'm proud of you

**Pull request merged**
