### PR TITLE
Prison vault

### PR DESCRIPTION
**Pull request by unid15**
A vault divided into two parts

1) shuttle wreckage that spawns in space. it's damaged beyond repair, and contains a shuttle destination disk

2) the prison itself - a small facility/outpost on the surface of a distant planet (with an atmosphere eerily similar to Mars) with prison cells, interrogation room and rooms for the prison staff. There are no enemies or extraordinary items in the prison, and it's surrounded by invisible borders so you can't leave it even if you break the walls You can only get to the prison by using the disk from 1 on a shuttle computer

### CODE REVIEW

**Comment by Kurfursten** [comment]
Since it's on a space asteroid anyway, way not add a mining gulag?

**Comment by FudgePucker** [comment]
I agree.
This could be a better alternative to solitary, an unexcapeable perma

**Comment by PJB3005** [comment]
Personally I think it looks really weird how the mars floors are fully lit, yet the walls of the prison are not lit on the outside.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten

If you're going to do that, it may be a good idea to make sure the vault has its own atmosphere on the outside so nobody ruptures a lung.

**Pull request merged**
