### PR TITLE
Killer tomatoes can now actually kill if provoked

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
changes killer tomatoes from a friendly mob to a retaliating hostile mob, with its attack damage being potency divided by 6.666666(...), (30 at 200 potency, 1.5 at 10) and health potency divided by 3.66666(...). (75 at 200 potency, 3.75 at 10) the person who planted them is immune to this retaliation. they have a weakness to plant-b-gone.

## Why it's good
shouldn't they be killer?

## Changelog
:cl:
 * rscadd: Killer tomatoes now actually... kill, when provoked by anyone other than their harvester.
 * rscadd: Killer tomato killing power is now decided by potency.
 * tweak: Killer tomatoes now dislike plant-b-gone.

### CODE REVIEW

**Comment by Eneocho** [comment]
Good middle ground between their current passive behaviour and the intended killer behaviour. Bonus for treadmill engines, since if they are aggressive they'll move with intent instead of the randomized movement.

**Comment by SECBATON-GRIFFON** [comment]
> Good middle ground between their current passive behaviour and the intended killer behaviour. Bonus for treadmill engines, since if they are aggressive they'll move with intent instead of the randomized movement.

i'm debating making a traitor item that always makes them hostile to everyone except their planter to go along with this sometime.

**Comment by Eneocho** [comment]
Make them take damage from plant b gone for consistency with plants and diona (the other plant mob) and be harvest into the mob instead of making a 'plantable' mob item. This would make it usable for hostile botany, since the tomatomob would appear upon pbging kudzu, and the pbg would anger the local tomatoes.
Altenatively, you could make a further down mutation that's always hostile upon harvest and keep the regular killer tomatoes killer in name only.
'killer' tomatoes and _killer_ tomatoes

**Comment by SECBATON-GRIFFON** [comment]
> Make them take damage from plant b gone for consistency with plants and diona (the other plant mob) 

did this, walking mushrooms should have it too maybe but outside the scope of this PR.

> and be harvest into the mob instead of making a 'plantable' mob item. 

walking mushrooms are like this too, so i dunno.

**Comment by Eneocho** [comment]
>walking mushrooms

You mean the regular brainless pet mushrooms or the shroom men? Cause the shroom men share the diona behaviour.

**Comment by pedr69** [comment]
>40 damage simplemobs

what

**Comment by Hinaichigo** [comment]
I guess the mushroom thing is to prevent lag in the case of self harvesting mushroom kudzu? It might be nice to have both them and killer tomatos spawn directly and just limit the number somehow.

Unrelated but it'd be cool to have the mushroom battle system fleshed out a bit more too.

**Comment by SonixApache** [comment]
might be an idea to rename them from `tomato` to `killertomato`

**Comment by SECBATON-GRIFFON** [comment]
> > 40 damage simplemobs
> 
> what

actually its 20 damage at 100 potency

**Comment by adacovsk** [comment]
Mushrooms aren't plants fool

**Comment by pedr69** [comment]
>actually its 20 damage at 100 potency

yes, and potency caps at 200

**Comment by Eneocho** [comment]
> > actually its 20 damage at 100 potency
> 
> yes, and potency caps at 200

198 actually (muh shitcode), for a nifty 39.6 damage

**Comment by SECBATON-GRIFFON** [comment]
> > actually its 20 damage at 100 potency
> 
> yes, and potency caps at 200

made it 30 damage and 75 health at 200, a 25% decrease

**Comment by ManopolisJones** [comment]
I had a similar idea to turn the killer tomatos into a traitor botanist item and give them something like pliable wolf AI, where they'd follow the planter around and attack folks. Just another idea gone to the wayside for one reason or another.

**Comment by Killette2** [comment]
The planter is not immune to tomato retaliation, and is often the second to die along with the aggressor. However this is funny and balanced, and I think it should stay that way.

**Pull request merged**
