### PR TITLE
Defficiency vox outpost update

### PR DESCRIPTION
**Pull request by Konater**
I made something that isn't good enough for box but maybe good enough for deff. I compiled it to make sure everything worked and now I'm totally sure that the distro and waste pipes aren't mixing together. I had to snip the pointy bits off the skipjack to get it to dock nicely and also changed a bunch of outside lights to lanterns on the asteroid to make up for the outside smelter.
If it isn't obvious I have no idea how to use smartgit or github. I swear I used a branch the first time but I had to delete it since I didn't know how to apply updates to it.
outpost

### CODE REVIEW

**Comment by Imagebard** [comment]
>If it isn't obvious I have no idea how to use smartgit or github. I swear I used a branch the first time but I had to delete it since I didn't know how to apply updates to it.

Inb4 "squash those commits"

**Comment by Konater** [comment]
Please it's a miracle that this pull request exists

**Comment by Probe1** [comment]
I wasn't saying it wasn't good enough for box.  I was saying that it'd be endless bickering over whether we wanted it and you can have this merged right away if its >Deff

**Comment by PJB3005** [comment]
No need for squashing commits anymore, carry on being a monster with your git history.

**Comment by Probe1** [comment]
Where do the raiders dock at?

I still think the smelting stuff needs to be indoors and having power on the roid is just all around PROBLEMATIC because people will wrench down chargers/machines anywhere and they'll get area power.

**Comment by Konater** [comment]
Raiders dock at the bottom left corner, there's a button on the skipjack that unbolts it like the station dorms
The explored asteroid is already powered though and I changed all the remaining light bulbs to lanterns

**Comment by Probe1** [comment]
I'm surprised it fit.  Nice job.  I'm not going to be a stick in the mud over the smelter but I still think its better served in the outpost proper.

**Comment by Probe1** [comment]
Alright map priority is all yours.

**Comment by Konater** [comment]
Uh oh

**Comment by Probe1** [comment]
It's ok!  All you have to do is rebase the changes from my PR!  Just take bleeding edge and use the map patcher and you should be all good.  Ask PJB3005 in irc if you need help.

**Comment by PJB3005** [comment]
https://youtube.com/watch?v=CXpuRIZzJog

**Comment by Probe1** [comment]
https://www.youtube.com/watch?v=qVaTANRyJfE&feature=youtu.be&t=7

**Comment by Shadowmech88** [comment]
RIP

**Comment by Probe1** [comment]
noo

**Comment by Imagebard** [comment]
[Henk]

**Pull request closed without merging**
