### PR TITLE
Revert "flip it turnways (#14540)"

### PR DESCRIPTION
**Pull request by ComicIronic**
Due to #14639, reverting this.
This reverts commit 6f5fade083e28cd1b26e226005bcfedb0f3624cc.

:cl:
 * bugfix: Fixed missing in-hand sprites for common items.

### CODE REVIEW

**Comment by eplgr** [comment]
That changelog, 🤔

**Comment by Exxion** [comment]
I don't see the issue

**Comment by clusterfack** [comment]
Look at the filesizes

**Comment by Exxion** [comment]
I meant I don't see the issue with the changelog

**Comment by clusterfack** [comment]
Oh, have no idea what he's talking about

**Pull request merged**
