### PR TITLE
Fixes glass of cream desc. Issue 12114

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/d3athrow/vgstation13/issues/12114

untitled

### CODE REVIEW

**Comment by Exxion** [comment]
That would be a suboptimal way to fix it if it didn't look better this way anyway
But it does, so :+1:

**Comment by Intigracy** [comment]
Eww...

**Comment by clusterfack** [comment]
I'm pretty sure that glass is half empty not half full, someone change it for me

**Comment by invoid9** [comment]
booger has the same issue, but wasn't reported

**Pull request merged**
