### PR TITLE
Pneumatic Cannon weight change

### LINKED ISSUE #5237: Pneumatic Cannons Too Big For Bags of Holding
You can wear them on your belt, I don't see why you wouldn't be able to put them into the largest backpack.

### PR DESCRIPTION
**Pull request by Wizardcrying**
Fixes #5237.

### CODE REVIEW

**Comment by Wizardcrying** [comment]
The build passed before, what?

**Comment by Exxion** [comment]
The error is with Travis, not your change. Travis failed to properly try to compile it for reasons I don't actually understand.

**Comment by ComicIronic** [comment]
Happens sometimes.

**Comment by Wizardcrying** [comment]
There's no actual need for a final decision; it just lets you stick an item that fits on your belt into a bag of holding where it otherwise couldn't.

**Comment by Exxion** [comment]
NFD is the tag that tells Pomf to look at it. As far as I'm aware, the only things that get merged by anyone other than Pomf are really urgent fixes and things that Pomf already merged but were accidentally reverted by another PR.

**Comment by ComicIronic** [comment]
>There's no actual need for a final decision

Enjoy your unmerged PR for eternity, then.

**Comment by Wizardcrying** [comment]
@Exxion I see.

**Pull request merged**
