### PR TITLE
Adds PES 5 League Mode theme to lobby song list

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Pro Evolution Soccer 5 as well as PES 5 - League Mode soundtrack belong to Konami
https://www.youtube.com/watch?v=kGrhrgNU_HQ

:cl:
 * soundadd: Added PES 5 League Mode theme to lobby songs.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
groovy

**Comment by tuypo1** [comment]
Well at least it's not FIFA

**Comment by Zth--** [comment]
add soccer balls

**Comment by brndd** [comment]
Do we really need more random copyright-infringing lobby songs that have nothing to do with space?

**Comment by boy2mantwicethefam** [comment]
Yes.

**Comment by tuypo1** [comment]
I am pretty sure konami doesn't care enough about videogames anymore to go suing some tiny ss13 server

And it is Kojimas fault

**Comment by Kurfursten** [comment]
Not enough public interest after 7 days

**Pull request closed without merging**
