### PR TITLE
New jacket with armor vest underneath for the Captain.

### PR DESCRIPTION
**Pull request by SnakeEater14**
Adds a naval officer inspired jacket to the Captain's locker. The jacket is unarmored, but underneath lies a robust security vest.

image

:cl:
 * rscadd: Adds jacketed armor to Captain's locker.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
it's pretty strong

**Comment by SonixApache** [comment]
It's essentially just an armored vest (as found in the captain's locker) except with a bathrobe over it.

**Comment by SnakeEater14** [comment]
> it's pretty strong

I was wary of anyway thinking it was OP, so I just copypasted the armor values from the security vest, which the Captain already has in his locker.

**Comment by PrimeDSS13** [comment]
fair

**Comment by Kurfursten** [comment]
It looks SO good.

And by the way, even if it wasn't the same stats, captain needs more toys (preferably ones he spawns with instead of in locker) to encourage captain sign ups

**Comment by xeroxemnas** [comment]
Need to steal the captain's saber from TG to complete the look.

**Comment by ShiftyRail** [comment]
Looks queer as fuck

**Comment by Blithering** [comment]
Kinda bugs me that it uses a different blue to the rest of the captain gear.

**Pull request merged**
