### PR TITLE
Sends a discord killphrase after a round has ended

### PR DESCRIPTION
**Pull request by ShiftyRail**
## About this PR

With https://github.com/PJB3005/MoMMI/pull/42/files, this, and a small secret-repo change (notably, telling the MoMMi what is the discord identifier to the #ick channel), this will allow the server to send a kill phrase to the discord. 

This kill phrase will lock the #ick channel of the discord (meant for """game discussion""") for a duration of **5** minutes, and post a link to the 4chan thread.
After that time, the channel will be opened again.

## Reasoning for this PR

The idea is to revitalise the 4channel thread by moving post-round discussion here.
The idea of this PR was suggested by Bomber Harris. It is also authorised by Pomf.

### CODE REVIEW

**Comment by SonixApache** [comment]
horrible idea
the thread is infested with extremely dedicated autists that do not tolerate any actual discussion, and mods do not exist
at best this will just piss people off and kill off even more discussion - as anti-fun as it gets

calling it a 4channel thread also tells me this was made in bad faith

**Comment by anunknownentity03** [comment]
I don't see this changing a thing if at all it's probably going to move the game discussion to the ock channel on the discord.

**Comment by Kammerjunk** [comment]
without condoning or condemning the PR itself, Sonix is dumb
on a related note, he's also currently wrong

**Comment by SootyBear42** [comment]
If there's even a chance of it possibly making the thread less dead than it is, then go for it.

**Comment by DrSnips** [comment]
The ock discord channel just becomes what ick was like Anun. said. This does nothing of benefit.

**Comment by SnakeEater14** [comment]
I like the idea and think it’s worth a shot 👍

**Comment by PrimeDSS13** [comment]
suggestion: if people move discussion to a different area of the discord tell them to stop and then murder them

**Comment by ghost** [comment]
Worth a shot

**Comment by Babaganosh** [comment]
no thanks i don't want to be forced into whatever the hell you want to call that shit thread

**Comment by ghost** [comment]
maybe lock the entire discord up.

**Comment by bungofungo** [comment]
not a single one of the admins (including you) is going to enforce discussion on the discord.

**Comment by BomberBro** [comment]
I don't think anybody would say that the 4chan thread wasn't the most important place to discuss the round up until maybe 2019, and though it's a lot of nostalgia there's a lot more that can be done with the medium than discord. Discord is flat out terrible for multiple conversations, it's nearly impossible to hold a discussion in the same channel over 2 topics, and any more than 4-5 people discussing something completely bricks a channel for anybody else. Beyond that, and maybe this is just the nostalgia talking, I really think greentexts and long effortposts provide better game discussion than discord. It's fun to hear about the perspectives of others and the anonymity (though often and easily abusable) is something unique to 4chan. 

I think it's completely valid to say that determined autists can bring down the thread, but this was mostly done when the thread was already empty and dead. It's a lot harder to steer discussion away (and also avoid getting reported enough for the sleepy mods to take action) when a thread is active. This might all just not work either, and that's fine too. We can just revert it later, I'd just be happy we tried something instead of complaining how bad it's gotten.

**Comment by gurfan** [comment]
can we start with deleting all channels except #ick first

**Comment by ghost** [comment]
possible chemo that could cure the thread, worth a shot

**Comment by SageOfLight** [comment]
This won't work but go at it you absolute clowns.

**Comment by djkramer123** [comment]
thinking that this will revive the thread is delusional

**Comment by cloutcode** [comment]
what's 4channel

**Comment by TGFH** [comment]
I don't think this is very likely to actually help much at all unless the 4chan jannies do something about the dedicated Schizophrenic NEETs that spam the thread whenever they get riled up.

**Comment by jwhitak** [comment]
Stupid PR that decreases functionality, communication, and community.

Some issues I feel that will come up if this PR is approved:
- Discord users won't go to the 4chan thread if the #ick channel is muted, they'll simply go to another discord channel, of which there are plenty, and the game of whack-a-mole begins. Another channel would assume #ick's current role, making this PR pointless.
- Assuming enforcement of 'DON'T TALK ABOUT SS13 WHEN ROUND IS OVER' on discord - which I believe to be unlikely given how hardcore of a rule change this would be and how our moderation is fairly easy going - it may result in a splinter discord server where this rule is not enforced, further splitting the community.
- Barring that, the worst case is that on round end folks would just find something else to do that isn't vgstation. Discord chat between rounds keeps people online.
- Due to the above, playercount will probably drop slightly. The increased activity to the thread is unlikely to attract more users to counter the effects.
- If the above is wrong and users do go to the thread, the thread schizos will make the whole experience between rounds worse vs discord.
- Players don't like being forced to do something (accept a 'downgraded' chat experience). Admins will be forced to actively enforce this or else the PR is pointless.

Ultimately I feel that If the discord chatters don't have a place to chat about ss13, they're not going to go to the ancient ass 4chan threads... they're just gonna go somewhere else.

**Comment by PlausibleDeniability** [comment]
I say put it to a poll.

One scenario that I can see being pretty annoying is people tend to chat in ick about the game in general, having it suddenly close for 10 minutes mid conversation would be really annoying.

I'd suggest a pre-warning message when the shuttle arrives at the station saying the channel will be locked in x minutes and unlocked in x minutes.

**Comment by BomberBro** [comment]
Already talked about the thread schizos, nobody is being forced to do anything here. If you don't want to post in the thread, then wait ten minutes or post in another channel if you feel strongly about it. 
>Due to the above, playercount will probably drop slightly. The increased activity to the thread is unlikely to attract more users to counter the effects.

The thread is (was?) basically our main source of players. We're not a public server, this server being mentioned is completely banned on reddit, the only way you'd hear about this server normally is via the thread or by word of mouth, the latter not being affected at all in this case.

**Comment by KingofHONK** [comment]
This should be decided with a server poll

**Comment by ghost** [comment]
I can't say I respect any attempt to revive the /vg/ thread for the sake of this server in its current state.  If it was actually about the format and benefit of using an imageboard thread for post-round discussion then we would be hosting our own pomf server imageboard specifically for such, but it isn't about that.  It's about wanting to use a 4chan thread for this server's public image and wanting to be able to tailor it specifically for this server in a public facet.  It's purely a ego thing.  I also think its stupid how many of you in this discussion don't even play the game and are bike shedding this.  Maybe if you actually logged in and played a round every now and then, we wouldn't be at 3-5pop for half of our days and could generate enough interest in the server and users to actually be able to influence the /vg/ thread.  This is a problem of not enough players to control a public 4chan thread in favor of our server and nothing else.  Grow up and just host your own imageboard if you want it that badly.  We aren't getting the thread back unless more people actually play and no amount of trying to force it with things like this is going to work.

**Comment by jwhitak** [comment]
> The thread is (was?) basically our main source of players. We're not a public server, this server being mentioned is completely banned on reddit, the only way you'd hear about this server normally is via the thread or by word of mouth, the latter not being affected at all in this case.

This is correct, but I feel the theoretical increase of posting on the thread from blocked discord users won't actively increase the number of interested players, or even improve the quality of the thread. It would just inconvenience the already-attracted users that vg already has.

As an aside, before merging, you may want to include new warning announcements in the #ick channel (like, say, 60 second warning?) before it's suddenly muted, so that folks know that their conversations are about to be cut short.

**Comment by KingofHONK** [comment]
Downboated only because this implementation will not accomplish anything, would be on board with trying something that will actually work, not some half assed change that just pushes all of the post round discussion to #ock. This isnt even a half assed attempt, its a no balls one.

**Comment by jwhitak** [comment]
Mentioned on discord: A better implementation might be a shorter duration with a tongue-in-cheek notice such as "This is your three minute shutdown reminder to go post in the thread!" so that it doesn't consume the entire time in-between rounds.

**Comment by BomberBro** [comment]
I wouldn't mind it terribly if it was five minutes (three might be fine but I'm less sure on that) instead of ten if that makes it easier on people, not sure how many people voted against or for it solely on the basis of the length of time though.

**Comment by BomberBro** [comment]
Also, since some were confused, in addition to locking the channel the mommi posts a link to the thread.

**Comment by PrimeDSS13** [comment]
I agree that 5 is probably a good compromise, though I doubt that'll change any votes Harris.

**Comment by ShiftyRail** [comment]
A lot of comments and opinions. Two things :

- Going to change it from **10** minutes to **5** minutes.
- I did check if the thread was "schizo-free" before making that PR. It seems that discussion is possible, there is just not enough people that care. I wouldn't have made this PR otherwise.

And of course this will be ultimately decided on a server poll.

@jwhitak Keep in mind that this is a 10 minutes (soon to be changed to 5) cooldown. The question was never to delete the discord wholesale. I don't believe it would be profitable or even possible at this point in history. However, for a very long time there was an overlap between those two communities. A reminder that, yes, there is a place called 4chan where you can go to talk about ss13 (and has been such a place for over 13 years now, including 7 years of Pomf-hosted /vg/station) doesn't hurt.

@HarseTheef Yesterday, a Sunday, in the Euro evening/American afternoon (~22h Paris time), there was over 60 players on this server. There is definitively more than enough people to revitalise the discussion on 4chan.

@KingofHONK Idea here is a "middle-of-the-road" solution that doesn't upset the status quo too much, while still trying to change things. You may call it a "no-balls", but it's the price of compromise.

**Comment by PlausibleDeniability** [comment]
> A lot of comments and opinions. Two things :
> 
> - Going to change it from **10** minutes to **5** minutes.
> - I did check if the thread was "schizo-free" before making that PR. It seems that discussion is possible, there is just not enough people that care. I wouldn't have made this PR otherwise.
> 
> And of course this will be ultimately decided on a server poll.
> 
> @jwhitak Keep in mind that this is a 10 minutes (soon to be changed to 5) cooldown. The question was never to delete the discord wholesale. I don't believe it would be profitable or even possible at this point in history. However, for a very long time there was an overlap between those two communities. A reminder that, yes, there is a place called 4chan where you can go to talk about ss13 (and has been such a place for over 13 years now, including 7 years of Pomf-hosted /vg/station) doesn't hurt.
> 
> @HarseTheef Yesterday, a Sunday, in the Euro evening/American afternoon (~22h Paris time), there was over 60 players on this server. There is definitively more than enough people to revitalise the discussion on 4chan.
> 
> @KingofHONK Idea here is a "middle-of-the-road" solution that doesn't upset the status quo too much, while still trying to change things. You may call it a "no-balls", but it's the price of compromise.

Can we get a warning message in #ick when the shuttle arrives at the station or leaves saying it's gonna get locked in x minutes for x minutes to stop conversations getting cut off?

**Comment by ghost** [comment]
@ShiftyRail   Cherry-picking the highest pop day and the highest pop time slot is a bit dishonest.  Sunday has always been the server's highest pop day and that is a horrible basis given how much of an outlier it is compared to the usual activity for the majority of the week

**Comment by xeroxemnas** [comment]
Easiest way to revive the thread is delete the bloated discord entirely. But this is good enough I guess.

**Comment by mrflarg** [comment]
I have a better solution, I will be your discord schizo, I will post nonstop in ick. all I ask for is a portion of patron funds.

**Comment by yclatious** [comment]
Teach bitches how to swim by throwing em in the ocean. A tactic that pisses folks off hardcore, but it teaches them well, so fuck it and try it out, why not, even if just to dab on Sonix.

**Comment by Shadowmech88** [comment]
Is 5 minutes long enough for adequate discussion to happen? It may be short enough that people would rather simply wait it out.
Whether this solution works or not, I'm supportive of any measures to siphon some life out of Discord for the thread. The server can't simply be deleted; a new one would be made within minutes just like last time that happened.
I would rather such a Pandora's Box have never been opened, but now that it has, the best that can be done is mitigation.

**Comment by juanototo2** [comment]
I just downboated so I could have a perfect 26/26 split vote and watch the world burn.

**Comment by ShiftyRail** [comment]
@juanototo2 Won't have too much effect, this will be decided in a server vote. http://ss13.moe/index.php/poll/214

**Comment by ghost** [comment]
Fuck it, lets at least try this system.

**Comment by Irradiation** [comment]
I say we testmerge this for a 2 week period and see what happens. There should be an automatic revert when the 2 week timer comes up and we get """tangible""" results.

**Comment by ghost** [comment]
It's pretty pointless for this to effect only one channel in a discord of 32 channels.  If you actually want to go down this road, then it really should effect every channel in the discord if you want """tangible""" results.

**Comment by xeroxemnas** [comment]
Just send a command that reports the discord to the furry moderators and gets it deleted if this merges.

**Comment by Kurfursten** [comment]
This server poll is viewable here: https://ss13.moe/index.php/poll/214
It will close on January 25.

**Comment by Kurfursten** [comment]
Poll closed:

> 54.03% for
> 39.52% against
> 6.45% other

By order of Veers, this will be merged for 2 weeks. (Until February 8)

**Comment by ShiftyRail** [comment]
Need to tell PJB to merge it on his end.

**Comment by Eneocho** [comment]
> (Until February 8)

May 6th, 2021

**Comment by gurfan** [comment]
did you happen to miss the second poll

**Pull request merged**
