### PR TITLE
Mechanic Update

### PR DESCRIPTION
**Pull request by Kurfursten**
**General**
- Tier 3 parts now require plastic instead of metal/glass/uranium/gold/silver/plasma.
- The RPED now requires plastic instead of gold/silver.

**Engineering**
- The SMES can now be upgraded in terms of power capacity, input, and output.
- The component list was tweaked, but is of similar difficulty to previous design
- Ditto: Portable SMES, for both
- Prism component list significantly simplified
- Freezer and Heater recipes simplified
- Freezer and Heater may be upgraded to heat and cool to greater extremes.

**Civilian**
-  The Biogenerator can now be upgraded to generate more biomass per nutriment, and to work faster.
- Hydroponics Trays now have a Toggle Light verb (does not interfere with bioluminesence). Unnoticable at its weakest level, but useful at higher levels.
-  Upgrading a tray reduces weed spawn chance, helps mutations occur, and improves the onboard light.
- Vending Machines have received a very slight buff to default throw rate.
- Vending Machines can now be upgraded to throw items more often.
- Microwave components simplified; upgrades not compromised
- Washing machines can now be built. Upgrading them will make them process faster.
- Fax is now buildable and can be upgraded to send faster.
-  Fixed a bug where the Fax would still be recharging with negative recharge time remaining.
- The Processor and Chicken Processor have been merged into one
- The Processor's component list was simplified
- The processor can now be upgraded to work faster.

**Medical Bay**
- Chem Masters can now be upgraded for more pills, bigger bottles, and bigger chemical reservoir.
- The virus incubator display now tells you the growth level of the inserted dish.
- The virus incubator can now be upgraded to grow faster and mutate more often.
- The virus isolator is now a machine instead of a computer and can now be upgraded to work faster.
- The virus analyzer can now be upgraded to work faster and require a lower minimum virus growth.
- The DNA modifier can be upgraded to spit out SE syringes faster.
- The reagent grinder is now easier to build.

**Science**
- The mech port may now be upgraded to increase charge speed.
- The mech floor may now be upgraded to store power for an instant transfusion, like a cyborg recharger.
- Monkey Recycler can now be upgraded to recycle more efficiently, and recycle live monkeys.
- The six Xenoarcheology machines related to analysis can be built, and upgraded to work faster.

### CODE REVIEW

**Comment by PJB3005** [comment]
You can use power cells for the SMES.

**Comment by Zth--** [comment]
:+1:

**Comment by Kurfursten** [comment]
@N3X15 Please remove conflicts and add Map Priority

This contains edits to every map file to change the pathing of the isolation centrifuge

**Comment by FudgePucker** [comment]
I am kinda erked on the tier 3 parts requiring plastic because science doesn't have any plastic.

I understand mechanics having plastic but miners not bringing them the other materials, but you are screwing over scientists who want to upgrade science or robotics.

I am guessing there isn't a way to have it be plastic or other mats for alternative construction costs?

**Comment by Kurfursten** [comment]
@FudgePucker There is a way, you could make a redundant design and have it listed twice

Scientists could also just cannibalize their own plastic flaps (they have tons) to make more parts than they'll ever need

In a PERFECT world, though, this would encourage scientists to collaborate with mechanics or botanists a little bit for machine upgrading.

**Comment by Zth--** [comment]
Update the wiki please, the update is pretty much useless if don't.
Also I found out you can't deconstruct (I can only open the maintenance panel) OR build washing machines (the circuit is not listed)

**Comment by Kurfursten** [comment]
@Zth-- Ah, yeah, I see what's wrong with the washer.

**Pull request merged**
