### PR TITLE
Summarily executes Travis

### PR DESCRIPTION
**Pull request by Exxion**
I'm guessing @d3athrow has to take the repo off Travis's service to fully complete this process but I don't know how it works
The new Actions-based CI is faster, more granular, and will actually remain free (at least for the time being)

### CODE REVIEW

**Comment by SonixApache** [comment]
✝️

**Comment by ghost** [comment]
That will teach them for wanting financial compensation for their goods and services.

**Comment by Exxion** [comment]
If anything it helps them because we're not using their resources anymore

**Comment by ShiftyRail** [comment]
Rest in peace Travia, 2015-2020

**Comment by d3athrow** [comment]
@Exxion travis isn't showing the repo in the dashboard.

**Comment by DamianX** [comment]
Rest in peace. All hail our Microsoft overloards.

**Comment by Exxion** [comment]
@d3athrow Is there a way to log in as the org?

**Pull request merged**
