### PR TITLE
Saner attempt at GitHub AUP compliance

### PR DESCRIPTION
**Pull request by nervere**
Closes #33074
## What this does
This PR attempts to bring the repository fully in-line with GitHub's Acceptable Use Policies (AUP).
Words that are used as slurs in the code are modified or removed. I used the response from GitHub pasted in Adam's PR as a reference to create this PR, seen here: https://github.com/vgstation-coders/vgstation13/pull/33074#issuecomment-1227798008

## Why it's good
If this is the path we must take for the repository to be viewable without login, I'd rather we do it the right way.
Unlike the PR this closes, no random curse words are removed, references to being gay / sexuality /gender are not removed, and an attempt to preserve cultural references in the code is made, just without slurs.

It's my strong belief that users having easy access to view code, pull requests, and issues is paramount to a healthy codebase.

## Disclaimer
I am not acting on behalf or at the request of Pomf or the collaborators.
This is my personal attempt at solving this issue. This is not __the__ solution, it is __my__ solution.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
If this allows people to keep up their anonymity while staying up to date with the codebase and it's changes, I'm all for it.
This is better than the last PR because most of the changes are just comments and the occasional examination description anyways, so this PR has no effect on actual server culture or gameplay.

**Comment by adacovsk** [comment]
Removing niggerman but not replacing it with Lovecraft's Cat is a travesty. Gay as an insult is verboten

**Comment by nervere** [comment]
> not replacing it with Lovecraft's Cat

I felt that would've been a bit too much on the nose, but that's just me.

>Also you're missing lots of instances

I don't think so. I couldn't find anything else with grep.

**Comment by gurfan** [comment]
retarded

**Comment by ShiftyRail** [comment]
We have TG (I think) as a precedent. Did they do something similar? Did it work? How did Github react to their requests for information/appeal? Here for /vg/ they do not appear keen on telling the exact reason why.

**Comment by Eneocho** [comment]
If you're taking out n*ggerman you damn better replace it with lovecraft's cat.
It's on the nose as hell but I refuse to lose that to muh guidelines.

**Comment by pedr69** [comment]
couldn't you just #define GAMER_WORD and replace "niggerman" with "[GAMER_WORD]man"

**Comment by Hinaichigo** [comment]
Honestly better to move the repo to the free-speech-oriented GitGud or something than compromise on something like this.

I've noticed recently a good number of projects are moving off of GitHub nowadays, self-hosting, etc. Many options available that allow one to maintain one's freedom of expression.

**Comment by TGFH** [comment]
Add more slurs to the code instead.

**Comment by tuypo1** [comment]
It is not hard to just make an account
that or move to a different site, moving to a different site is probably the better option actually because censorship here is just going to keep getting worse

**Comment by KingofHONK** [comment]
We should not allow outside forces to moderate how we decide to run the server. GitHub does not care about space station 13, none of the people who work there have probably even played it nor have they ever heard of our server. Complying to this without the promise of even getting our public status back is also fucked. This PR should only be entertained as a last resort, we should explore different options first.

**Comment by Eneocho** [comment]
Can't we move to an alternate git service? Not sure which one however.
That being said is it really that bad to have the git hidden? We can just post about the current PRs on the bread like the MoMMI and GitClown anons did back then (and the sh*tcord already gets automated PR reposts). If someone wants to complain about the PR on the git or give their emoji they'd need an account either way so no harm in just having it hidden.

**Comment by tinysaturn** [comment]
>If someone wants to complain about the PR on the git or give their emoji they'd need an account either way so no harm in just having it hidden.
This. If someone cares so much about seeing the individual PRs and their code changes, why not make an account? Until you make one your opinion on them literally doesn't matter and all you can do is cope and seethe + it's been like this for years.

**Comment by ShiftyRail** [comment]
>GitHub does not care about space station 13, none of the people who work there have probably even played it nor have they ever heard of our server. 

Demonstrably false. TG is one of the biggest repo of the entire site, /vg/ itself is probably in the top 50. We had regular interactions with them through DCMAs and other issues. The Github staff knows about us. 

>without the promise of even getting our public status back is also fucked.

TG had the same problem, did what felt reasonable and they got their repo back. IIRC they even got a full ban while we only got hidden - Github explicitly told us we don't violate the terms of service.

>we should explore different options first.

Not sure there are any. Gitlab doesn't scale enough and doesn't have the moderation tools needed and that's the biggest self-hostable alternatively. The only unclear thing on their part is whether the content (words in the code) or the activity (comments & al.) is what got us hidden - Github doesn't feel like telling us. Honestly, a few words in the content feels like a weird hill to die on when the actual activity on the server is and will remain free. 

There's nothing to be lost from asking Github to unhide us after removing what amounts to 4 words in the entire codebase, mostly in comments. If the issue is what users post, maybe it's time to exercise some self-censorship or something. The notion that Github underpaid interns will delete our repo in a fit of executive pique is entirely baseless and pure paranoia.

**Comment by aerlx** [comment]
kill yourself nigger

**Comment by ShiftyRail** [comment]
Up yours, woke moralists. We'll see who reverts who.

**Comment by PrimeDSS13** [comment]
After looking into the TG thing, I confirmed that they had their repo straight deleted due to the slurs in their codebase a few years back. After a few PRs to sanitize it, they had their repo fully restored by Github.
If Github went out of their way to NSFW us instead of fully deleting our codebase like TG, I see no reason why they would hesitate to unNSFW us if such content was hidden or removed. 

Regardless, while this isn't what's considered the "epic" route (even though it doesn't change much), and thus I don't think it'll pass, I still think it's more important to /vg/s culture to allow anybody to see the repo regardless of account (anonymous).

**Comment by ondrej008** [comment]
> After looking into the TG thing, I confirmed that they had their repo straight deleted due to the slurs in their codebase a few years back. After a few PRs to sanitize it, they had their repo fully restored by Github. If Github went out of their way to NSFW us instead of fully deleting our codebase like TG, I see no reason why they would hesitate to unNSFW us if such content was hidden or removed.
> 
> Regardless, while this isn't what's considered the "epic" route (even though it doesn't change much), and thus I don't think it'll pass, I still think it's more important to /vg/s culture to allow anybody to see the repo regardless of account (anonymous).

You need an account to play the game itself, but viewing the repo should be possible without an account, why?

**Comment by pedr69** [comment]
you can view the 4chan thread without an account
you can view the forums without an account
you can view the logs without an account
you can view the wiki without an account
you could view the github without an account
you should be able to use the fucking web without an account

fuck off discordites

**Comment by Eneocho** [comment]
>fuck off discordites

based

**Comment by ShiftyRail** [comment]
@pedr69 a very principled response but one that ring a bit hollow given what's at stake.

If you don't want to register for an account to view the git, then it's simple. You remove the slurs and that's easy as 1 2 3.

**Comment by aerlx** [comment]
@pedr69
yeah you "should" but you also "should" be able to say wrongthink without it being censored
Advocating censorship so that people don't have to make accounts is further from my ideal than the current status quo.

**Comment by ShiftyRail** [comment]
Censorship? Wrongthink? Jesse, what the fuck are you talking about?
This is a service we're using for free. And we're talking about a few comments in the code, or perhaps one item. Come down to Earth and realise that you can't have it both ways.

**Comment by aerlx** [comment]
>Come down to Earth and realise that you can't have it both ways.
Yeah I just said that, and the way I picked is cool and awesome and the way you picked is gay and retarded.

**Comment by SECBATON-GRIFFON** [comment]
just move everything onto a gitea instance at git.ss13.moe already

**Comment by aceedex** [comment]
My opinion doesn't matter but I think we should email the CEO of github the word nigger

**Comment by d3athrow** [comment]
there is no guarantee these changes would affect the current objectional content flag the repository has. if github gave a list of infractions i would reconsider any changes made at such a time.

**Pull request closed without merging**
