### PR TITLE
No MoMMis or AIs on purge day

### PR DESCRIPTION
**Pull request by ShiftyRail**
I should care more about code quality but it's the epic meme day after all!

### CODE REVIEW

**Comment by BomberBro** [comment]
Remove the AI portion, nephew.

**Comment by smalIboss** [comment]
> Remove the AI portion, nephew.

ai needs to die too

**Comment by ShiftyRail** [comment]
There, no redmonts

**Comment by ShiftyRail** [comment]
Greenlit by your Headmin

**Comment by ValkyrieSkies** [comment]
Admins are the weakest of us all.

**Comment by boy2mantwicethefam** [comment]
This is not getting reverted btw, the silly cone menace is over

**Pull request merged**
