### PR TITLE
 Wizard spell for breaking lightbulbs.

### PR DESCRIPTION
**Pull request by ghost**
A wizard spell for breaking bulbs within 7 tiles from you.

:cl:
 - rscadd: added a wizard spell that breaks lights within 7 tiles of you.

### CODE REVIEW

**Comment by DeityLink** [comment]
Wait, how about instead adding Dumbledore's lighter that turns the lights off?

**Comment by Shadowmech88** [comment]
Wouldn't that be strictly less effective than this spell?
Even if it burned the lights out instead of just turning them off, it'd still be something you have to carry around and manage in your inventory.

**Comment by SGuivenne** [comment]
@Shadowmech88 its a lighter, it fits in literally any slot including your box

**Comment by Shadowmech88** [comment]
Right, but when you want to use it you have to open your backpack and then your box and take it out instead of just clicking a "cast spell" button.
Not that I'm saying the lighter couldn't be added, but to take the place of this spell it needs more utility, otherwise it'd only be worth a few points.

**Comment by SonixApache** [comment]
put this at the bottom of your OP
```
:CL:
 - rscadd: added a wizard spell that breaks lights
```

**Comment by DamianX** [comment]
I don't think this is a worthwhile addition.

**Comment by SonixApache** [comment]
Same, though I think it'd be nice for a cost 2 cantrip.
Enough cantrips and we can warrant their existence.

**Comment by ghost** [comment]
Cost and cooldown seem a little high to establish a darkened territory or to overcome the massive light tube saturation since you don't just overload the whole area like a silicon can.

@SGuivenne It adds up when you're carrying and managing so much other stuff.

**Comment by ghost** [comment]
How much should the cost/cooldown be lowered?

**Comment by ghost** [comment]
Took the liberty of decreasing cost to 5, cooldown to 15 and range to 7.
Maybe it could work as a set of several low cost spells?

**Comment by SonixApache** [comment]
changelog busted somehow, replace the `:CL:` with a 🆑 emoji

**Comment by DamianX** [comment]
needs to be `:cl:`, not `:CL:`

**Comment by ghost** [comment]
Done.

**Pull request merged**
