### PR TITLE
A modern and progressive bar sign

### PR DESCRIPTION
**Pull request by jknpj**
barsign
Sprite by @moistnugget. Also tweaks barsign code to be able to adjust signs that only need a single axis fixing.

:cl:
 * rscadd: Adds a modern and progressive barsign made by @moistnugget

### CODE REVIEW

**Comment by ghost** [comment]
Does this barsign automatically shock white people who get close?

**Comment by Riekland** [comment]
Is this some kind of new meme from twitter or something
It looks like shit

**Comment by ghost** [comment]
>Twitter

It just a joke sign poking fun at liberals

**Comment by Shadowmech88** [comment]
image

It's an older meme, sir, but it checks out.

**Comment by Durgen** [comment]
needs parentheses

**Comment by Riekland** [comment]
could you at least add I dunno, a darker outline to the letters
it's just so 2D
fuck off I know it's a 2d space sim game you know what I fucking mean

**Pull request merged**
