### PR TITLE
"Grandmaster" Wiz/Cult Concept

### PR DESCRIPTION
**Pull request by Kurfursten**
I talked about this idea with Deity a bit. I had some downtime so I threw about half of it together. I'll finish it if people like the idea. It could be a bus option or a normal ruleset, but either way it should cost a good chunk of threat. **So feel free to emojiocracy this up or down, I'm not gonna work on it further until I see what people think.**

tl;dnr: Latejoin ruleset sends someone to the wizard den. They only get 60 spell points (3 slots "traditional" wizard) and a very limited spell list (see below). They also get cult robes and are told to solo-raise an altar on station (easily done with robes) and raise their own cult from scratch. The true solocult experience.

Freebies: Full cult robe outfit, tesseract, tome, maybe a couple starter talismans

**Available Spells**
**Robeless:** Smoke, Break Lightbulbs, Charge, Become Snakes, Forcewall, Bound Object, Fire Breath
**Robed:** Pain Mirror, ~~Doppelganger~~, Feint, Teleport, Lightning (I am the Senate)
**Artifacts:** Mental Focus, Soul Stone Bundle, Lesser Predicted Potions, Glow Orbs, Phylactery, Prestidigitation Bundle, Summon Identity, Grandmaster's Robes

The idea behind these spells is, to quote Deity
>"If a solocultist joins late, I want him to be stealthy, not like a wizard"

These are the spells I viewed as conceivably stealthy enough. Without blink and jaunt, a wizard-cultist would have to be much more careful about how he engages.

**New Artifacts**
**Summon Identity:** Available for wizards on LABOR DAY and grandmasters all year. Summons a dead man (lootable job specific clothes) from a random non-unique maintenance-access job (e.g.: cargo tech, engineer), a syndicate ID, and injects your identity into the manifest. Vacation by laboring, it's Labor Day!
**Grandmaster's Robes:** Slightly higher cult power than normal robes (90 total) and count as wizard garb for spells. These are enough to reduce forge heat to half and count as +3 cultists when raising a structure. Altars should be a breeze.

**Also Featuring** Admin spellbook can always buy any artifact or spell no matter the holiday or round status, meaning you can now pray for summon guns as a ragin' mage.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
how the fuck does a cultist become a grandmaster if they're supposed to summon the geometer lmao

**Comment by Lunstra** [comment]
More mid round antags is good and this is a pretty good one conceptually too.

**Comment by Kurfursten** [comment]
Sure, I'm not too attached to Doppelganger. I should note Blink is not available though. Blink is the least stealthy spell in the whole game and arguably the prime enabler for loud wizards. Jaunt being the other.

**Comment by ShiftyRail** [comment]
A wizard cultist is going to be rather though to fight, especially if they have options to lay low and keep the initiative
I'm curious as to how it'll work out

**Comment by DeityLink** [comment]
I'd like the concept of wizards and cult to remain as far from each other as possible.

image

Like, this fucks up the progression of a cult round, by trivializing the most challenging part of it for the cultists. Why not make a completely separate antag?

I mean come on cult was created originally for the very purpose to split features away from wizards.

**Comment by Coxswain-Navigator** [comment]
It is my firm belief that wizard and cult should remain separate. You could instead turn this idea into two separate antagonists.

Grandmaster wizard: Pretty much a stronger, higher threat wizard. Almost everyone hates gunwiz so maybe make grandmasters unable to use guns or even purchase norobes to prevent a stealthwiz.

Geometer of blood agent: Basically a solocult, the main difference here is that they cannot use converts and are not subject to the acts system. They have the runes memorized without a book, and have a specific objective that may or may not lead to the formation of an actual cult. They specifically have objectives to take their secrets to the grave. Each objective completed may allow them to pick a tattoo at a spire or grant them soul stones(?)

Let me know what you think.

**Comment by Hoshi-chan** [comment]
I was gonna upboat this, but Cult is Deity's baby, and if he says no, that's should probably be the end of the discussion.

Cockswain's idea is a nice way to salvage it though, or else you could just adapt what you already have (access to more powerful robes in exchange for being solo) to create a midround solocult antag. I really like the idea of a more powerful wizard, but who comes with more restrictions on how he can approach things. Maybe instead of being a separate antag, it could just be an option for all wizards; eschew guns, stealth, disguises, hardsuits, et cetera for greater magical power.

**Comment by DeityLink** [comment]
@Cockswain @Hoshi-chan Well if I had to measure the potential issues with Cockswain's idea that'd be:

* Wizards are already incredibly strong solo, I rarely ever see gunwiz, doesn't prevent them to wreck havoc on the station, how would you make a wizard even stronger? Do we even need stronger wizards?
* The whole concept of runes sucks if you're solo, their main draw of writing them and raising structures is that your allies can use them too, otherwise, you're just taking extra time setting up a spell that's generally gonna be outclassed by quite a few other wizard spells.
* Runes, tattoos, and basically every cult features are finely tweaked and balanced for the progression of the cult faction, 

Lastly I have plans for latejoin solocult but I put them on hold for until the viro rewrite is done because I wanted to work on something other than cult for a while. Kurf's concept is all but the true solocult experience, easy mode if anything, Cockswain concept is a bit closer to my plan which involves having a powerless scholar perform specific seemingly random or even dangerous tasks to learn the ritual that will let them become an actual cultist.

**Comment by Blithering** [comment]
Leaving a wall of text here because I found this PR while waiting for a bus and have nothing to do but ideaguy things:
SoloCult antag could be a semi-observer, vague name idea whisperer, completely invisible to all but cultists and ghosts, has no way to interact with crew other than marking them as potential targets for cultification and development from there. 
Whisperer would slowly convert people to cultists by getting them to perform certain sacrifices; sacrifice of flesh, killing a random station animal, sacrifice of blood, spreading blood standard cult style, and sacrifice of spirit, jabbing themselves with a pen and signing a spawned in contract. Once they complete these sacrifices they can become proper cultists, and a cult round would begin as normal. 
Whisperer would have to pick his targets carefully, as there's no telling beforehand who is gonna call the cops, but is himself untouchable. Blessing anyone he has marked as an acolyte would immediately reset any progress towards cultification and make them unable to be contacted until the blessing wears off.
In order for cult not to have a permanent invisible tattletale to scout out ahead for them, once the standard number of starting cultists have been created, the veil thins enough for the whisperer to enter the plane of the living in his true terrifying form (a shade)
Also for the wizard grandmaster, add a lich bundle. Noone ever picks the specific set of spells required to have the lich king armour under normal circumstances.

**Pull request closed without merging**
