### PR TITLE
Fixes the roundstart assistant-to-sec ratio.

### PR DESCRIPTION
**Pull request by ShiftyRail**
# About this PR

The bug was caused by #21320, unintentionally, as the assistant checks relied on them being picked **last** and always as a **LOW** priority option.
Unslowflaking it meant that the assistant role could be given as any normal role, before sec roles could be attributed, and as such before the check was done.

I personally don't think this is really needed, but there's been a demand for it, so here it is.

It is more or a less a "de facto feature", or a legacy bug, so I'll let other admins decide if it needs a poll, balance tag, etc. At any rate I don't believe this should be merged without some discussion.

# Technical notes

Tested the best I could. The first assistant is always allowed, so I simulated that one assistant was always present in the game.
Then, I readied up as a lone assistant (fail), and with two accounts, as an assistant and a sec off (success).

I'm not sure if the old logic of the check worked. It looked weird and buggy to me. (entire job controller is god dammit, rework when ?)

# Changelog

:cl:
- bugfix: The sec-to-assistant ratio of 1 for 2 is now enabled at roundstart.

### CODE REVIEW

**Comment by BomberBro** [comment]
I support this if only to cut down on the 10 assistant 0 normal job meme rounds where you latejoin into the space equivalent of detroit, but I don't like that the assistants are tied solely to security. Max assistants should be bumped to 2 also imo with no security present.

**Comment by SonixApache** [comment]
i can't believe you actually fixed it
good on you

**Comment by ShiftyRail** [comment]
React with :heart: to this comment if you want the PR to go through in its current form, or :tada: if you want some modifications (2 non-sec assistants, taking into account engineering, medical...)

**Comment by Accipitermaris** [comment]
i only support this because it shakes up the gravity-well-of-apathy-fueled status quo. if there was a remove security PR i'd support that in tandem with this.

**Comment by ShiftyRail** [comment]
@Accipitermaris Isn't it a tad flimsy as a reasoning ?

**Comment by Accipitermaris** [comment]
@ShiftyRail absolutely, but the oldfriend headmins of /vg/ who might oppose this change or have a well thought out, experienced-based third option are indefinitely MIA. leaving us to either kick rocks or perilously make our own fixes from our limited viewpoint which tends to be pure guesswork on our part. like the "give everyone maintenance access" experiment.

**Comment by ShiftyRail** [comment]
I don't think it's pure guesswork if it's well argumented. Anyone can make their opinion on the subject worth hearing if they bother to explain it in clear, simple, and logical terms. Someone who played back when the stars were young and the singulo would crash the serb doesn't have a necessarily better opinion than a newfriend, just one with more context.

Anyway, my take on this is that it's going to frustrate players who want to join a round without committing to a particular role, it's going to frustrate Librarians/IAA/Whatever RP roles we have left who see their place usurped by assistants in a different clothing...

I'm not a fan of the assistant limit at all. I for one actually like fighting the tide, but that's a minority opinion.

"It'll upset the status quo" is a silly reasoning. Let's not go too far in a few places.

**Comment by BomberBro** [comment]
Why contain it? We should see what works and what doesn't, otherwise we'll just stagnate. If something actively hurts the game it can just as easily be reverted. As for those RP roles, we still commonly get the people that play those roles just for exotic assistant even without the cap.

**Comment by ShiftyRail** [comment]
>If something actively hurts the game it can just as easily be reverted

[x] Doubt

**Comment by BomberBro** [comment]
We're done with the permanent "testmerges". I don't like the idea that we can't test anything ever again just because people did gay things ages ago, we're never going to see how certain changes will play out just by theorycrafting in github.

**Comment by SonixApache** [comment]
I really don't think fighting the tide is fun.
I think 2 nullsec assistant slots is good. Maybe even three.

**Comment by ShiftyRail** [comment]
There's an edge case I just thought of I need to fix.

**Comment by ghost** [comment]
And now do a max security limit with something like a 5-crew-to-1-security ratio.

**Comment by SonixApache** [comment]
what @Baronzegit said but in reverse

**Comment by ghost** [comment]
What @Baronzegit said but unironically

**Comment by ShiftyRail** [comment]
The job controller wasn't meant for such elaborated rules. To do something like that would probably mean to rewrite it entirely.

**Pull request merged**
