### PR TITLE
Clumsy people using a zippo have a chance to set themselves on fire with class when lighting their cigarette

### LINKED ISSUE #24140: Clumsy and zippos
(WEB REPORT BY: dacendeth REMOTE: 206.221.180.138:7777)
# Revision
10c21eb6f6d1f76e212c5666263d10b980f452bb

# Description
Clumsy people can use zippos just fine with fancy emote text, this feels wrong.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #24140

image

:cl:
* rscadd: Clumsy people using a zippo have a chance to set themselves on fire with class when lighting their cigarette or a campfire.

### CODE REVIEW

**Comment by Eneocho** [comment]
How does this interact with clumsy plasmemes? They set themselves on fire and the suit puts it out? Or do clumsy plasmemes have an exception?

**Comment by DeityLink** [comment]
I guess we'll find out.

**Comment by ghost** [comment]
> 
> 
> How does this interact with clumsy plasmemes? They set themselves on fire and the suit puts it out? Or do clumsy plasmemes have an exception?

Suits are not universally fire-immune.

**Comment by Dacendeth** [comment]
plasmeme suits will put the fire out.

**Pull request merged**
