### PR TITLE
Bundle of Syndicate Bundles

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Adds 6 new syndicate bundles and ~removes~ reduces the chances of 2 because they're awful and ~hated~ perplexingly tolerated.
I like bundles, if I can't think of a gimmick I'll pick a bundle and try to get creative with it. I tried to make these flexible rather than have a single obvious intention.

**~Removed~ Reduced Chance Of**
Screwed (powersink, bomb, space suit)
Lordsingulo (singulo-beacon, emag, space suit)

I've seen people say they specifically don't take bundles because these two exist just to waste their TC. Don't like em.
They now have 25% the chance they previously had of showing their stupid ugly faces.

### New Bundles
"Chance" is compared to other bundles. Not the chance of getting it when you buy a bundle. 

**Clown**
Chance: 50%
- Permanent invisible spray
- 2 Superglue
- Punchline
- Living long balloons (7, the same as buying it normally)
- One use spellbook for shoe snatch

**Druid**
Chance: 50%
- 6 Spawner grenades. Each having an equal chance of being a carpnade, bearnade, or beenade
- 6 Chaos eggs
- Druid wintercoat

**Actor**
Chance: 100%
- 5 NT report falsifiers
- A megaphone
- Voice changer
- Agent ID
- Chameleon projector
- A random amorphous mask

**Eugenics**
Chance: 50%
- 8 DNA injectors containing hulk, xray, telekinesis, no breath, regeneration, run, jump, and strong

**Alchemist**
Chance: 50%
- 1 lesser predicted potion bundle (10 identified potions)
- 1 less potion bundle (12 unidentified potions)
- 2 random chemical packs, the same ones Traders sell

**Jackpot**
Chance: 7%
- 2 Random syndicate bundles, they could even be jackpots!

:cl:
 * rscadd: Added 6 new Syndicate bundles
 * tweak: The singulo and screwed bundles are 75% less common

### CODE REVIEW

**Comment by SonixApache** [comment]
>Removed the singulo and screwed bundles

[balance][discussion][20x:-1:]

**Comment by GreatBigFailure** [comment]
> > Removed the singulo and screwed bundles
> 
> [balance][discussion][20x👎]

Don't like it, bad bundles. singuloose gay

**Comment by djkramer123** [comment]
Screwed bundle should've never been a thing in the first place.

Good riddance.

**Comment by Armadingus** [comment]
While I really despise people destroying the station with little to no interaction with other people in complete stealth with that Screwed bundle.
I think that people who are too inexperienced to make bombs should have the opportunity to use big bombs occasionally. I am surprised to see this come up in a PR made by you, Rubylips, because you used to do fun gimmicks with the blastcannon.

**Comment by KillFurries** [comment]
More bundles good. Eugenics bundle sucks. Actor bundle is a downgrade to the stealth bundle which also comes with a cryptographic sequencer. The two removed bundles could have a chance reduction instead of outright removal. It's rare to see good singulooses and a good maxcap explosion, now there's going to be even less of them.

**Comment by SonixApache** [comment]
#25204 - #25605

i like the first two but i think giving wizard shit to non-wizards is the gay

**Comment by ghost** [comment]
I'd prefer vastly lowering the chances of getting singulo and screw bundles than outright removal.

**Comment by GreatBigFailure** [comment]
Unremoved the screwed and singulo bundles, gave both a 25% chance so I have to look at them less.

**Comment by DeityLink** [comment]
> 
> 
> > > Removed the singulo and screwed bundles
> > 
> > 
> > [balance][discussion][20x👎]
> 
> Don't like it, bad bundles. singuloose gay

bad opinion

**Comment by DamianX** [comment]
append-only codebase

**Comment by calzilla1** [comment]
Not a big fan, most of them are "a bunch of one situational/meme item (potions, animal spawning grenades, report falsifiers, DNA injectors)" while they might be powerful, I'm not sure just giving a tot a bunch of one-use goodies is exactly conducive to gimmicks or any sort of fun play-style. If I was gonna micro this, give clown one more superglue and spray (one for each hand), remove druid entirely, lower the report falsifiers to 2 for actor, and put in a cham projector and DNA scrambler (though this might make it just a better bloodyspai, which is good because bloodyspai is pretty awful), give eugenics half as many injectors/ none at all, a rad gun, an emag, an organ extractor, and a pocket sat (modified to have a DNA modifying machine) for that evil genius "kidnap and mutate into unspeakable horrors" kind of antag, give alchemist a "street alchemy" spellbook, and jackpot is fine.
The main thing Im getting at is that these should have tools that are not only almost always usable, but cover a wide berth of playstyles instead of funneling the hapless tator into a single defined role.

**Comment by GreatBigFailure** [comment]
I can see the line of reasoning but I disagree about them being too specific when it comes to gimmicks.
The potions and to a lesser extent the grenades have RNG to which you're getting. The potions specifically will be used very differently round to round and I can think of a bunch of different gimmicks depending on which you get. The grenades are absolutely going to mainly be used for mob loosing and I fully admit I just wanted a non-bus way to get those grenades because they're fun, but I also think it's at least a more entertaining loud murder bundle than "Gun and also a gun". 
Actor is meant to be a build-your-own-bus tool but I fully admit falls short. A cham projector is a good idea, I might also add a few other items but I want to keep the high amount of falsifiers. Since seeing the bundle will be rare people will stop thinking reports are falsifiers once they see 3-4 of them. 
The gene injectors can be used in a bunch of ways, most people who get a few of those powers from a mystery dice use them in nearly-antagonist ways anyway.

All this said I'm by no means married to these specific bundles. I literally made this at 2am because I couldn't sleep and needed an hour or so to relax. I just can't help but compare them to the other bundles and see them as preferable. I'll tinker a bit though.

**Comment by GreatBigFailure** [comment]
Alright did some tweaks based on feedback:

- Added 1 more glue to clown
- Reduced druid grenades to 6 from 7, added 6 chaos eggs to the bundle 
- Added an amorphous mask and a chameleon projector to actor
- Added 2 of the rng chem packs traders have to alchemist

**Comment by Kurfursten** [comment]
For a long time I've thought bundles should be divided into different categories and you choose a class of bundle.
"Mass Destruction" gets you stuff like singulo, screwed, hacker
"Up Close and Personal" gets you stuff like American Psycho, Hotline Miami, Sith, Highlander, smooth operator, Ocelot
"Weird" gets you all the other stuff that isn't about murderboning, like bloody spy, balloons, bangerboy, emags and glue

This way people have a little more control. Weird is where most of your ideas would fall -- they're not really about getting a gun or ebow. I can understand where you're coming from, but the majority of bundles are about methods for killing. So instead of tugging both ways and making both sides unsatisfied, split bundles into different groups to please both sides.

**Comment by GreatBigFailure** [comment]
I agree but that isn't really the point of this PR.

**Comment by Eneocho** [comment]
Since you're touching up the syndie bundles, can you reduce/remove the chances for the Hacker bundle if there are no silicons on board? I still remember one round in which the IAA tator got fucked because they bought the bundles, got hacker and there were absolutely no silicons on board, so they wasted 14 TC.

**Comment by Eneocho** [comment]
The clown bundle's Living Long Balloons will not work, since they need you to be clumsy to use them properly. Perhaps change them for 1 or 2 banana grenades?

**Comment by GreatBigFailure** [comment]
Good idea and good catch. I thought the balloons were usable without clumsy which is why I picked them. I think I'll add a clumsy injector to the bundle and tweak the contents accordingly

**Comment by GreatBigFailure** [comment]
Added a clumsy mutation injector to the clown pack. After looking at the things requiring clumsy I decided to keep the balloons.

**Comment by Eneocho** [comment]
>Added a clumsy mutation injector to the clown pack. After looking at the things requiring clumsy I decided to keep the balloons.

Out of all the clown items on the pack, the only one which demands clumsy to be present is the balloons, you can still use the punchline as a non-clumsy individual (Clumsy individuals crank it way faster), is it prudent to just add a clumsy gene syringe?

**Comment by GreatBigFailure** [comment]
I think it adds some flexibility to the pack and promotes non-murder antagging. Clumsy is a pretty big buff to punchline for more reasons than crank speed too.

**Comment by Eneocho** [comment]
For real man, please add a check to the hacker bundle in case there's no silicons on the round. See #29644. That shit haunts me at night.

**Comment by GreatBigFailure** [comment]
> For real man, please add a check to the hacker bundle in case there's no silicons on the round. See #29644. That shit haunts me at night.

I plan on it but I'd prefer to in a second PR. This one was just meant to be a quick bundle addition rather than changing how they work too much. I'd rather include it in a PR similar to what Kurf suggested.

**Pull request merged**
