### PR TITLE
Dorf Station; or, a Terrible Mistake

### PR DESCRIPTION
**Pull request by Jackreturnswithaveangenace**
A complete overhaul of the old unfinished dorfstation.dm map to be a dorfmode ready one time event. 4 zlevels, 1 for the main station/asteroid/voxpost/derelict, 1 for centcom, 1 for vaults and DJ sat and abandoned shuttle, 1 for pure vaults. Just in time for this weekends dorf event. @BurntDevil helped with mapping the derelict ship.

Much of the stations necessities will need to be ordered in via cargo, but there is enough left behind by the previous construction crew to get started. I highly recommend setting up airlocks and firedoors in the hallways as a first priority while engineering sorts out power.

Blueprints have been placed for the crew to use. I would have relied on the crew using construction permits alone, except that would have required making every area "space" and I fear for how that would have turned out. _If there is a better solution let me know before saturday and I'll try to apply it._

### Caveats

I made this less of a empty roid with a cargo bay and more of a badly designed, barely built station eked out of the rock so that people don't need to wear internals forever. There is a safe area to mine without needing internals which will be clear upon examination of the station layout and by using mesons to see where the atmospheric boundary is marked by evenly spaced regular walls.

## Images

The full map (blurred out details outside of the core station)
dorf3

Real Dwarf Fortress Sprites I made myself!!!
authentic sprites

Engineering, ready to go!
engineering exists

Please do not push to get out of the cryo shuttle, we will all get out eventually
where it all begins

**Featuring: 3 tile wide hallways!!!!!!**
3 tiles wide

:cl:
 * rscadd: Adds a fully dysfunctional station for dorfmode events. Room for both chilling out in caves and building a functioning station. Includes a derelict ship mapped by BurntDevil.

### CODE REVIEW

**Comment by Jackreturnswithaveangenace** [comment]
Also do not, I repeat, do NOT blow up the welding tank room before firelocks and airlocks have been put down. I have tested this.

**Comment by DeityLink** [comment]
@Jackreturnswithaveangenace if you've blurred details because they contain secrets, you might want to give them their own areas and then give those areas `holomap_draw_override = HOLOMAP_DRAW_FULL` (if they're rooms inside the asteroid for example) or `holomap_draw_override = HOLOMAP_DRAW_EMPTY` (if they're a ship or small structures sightly off from it). Otherwise players will just build a station holomap and see them all.

**Comment by Jackreturnswithaveangenace** [comment]
Thanks, I'll have a look at that.

**Comment by Jackreturnswithaveangenace** [comment]
Did a final once over, made sure vaults were spawning correctly and there wasn't anything else I could think to add without overhauling the entire map. She's ready to go.

**Comment by ShiftyRail** [comment]
Why the random wires ?

**Comment by Jackreturnswithaveangenace** [comment]
> I made this less of a empty roid with a cargo bay and more of a **badly designed**, **barely built** station eked out of the rock

I'm not sure which random wires in particular you mean, but that's the explanation either way.

**Pull request merged**
