### PR TITLE
Increase rocket speed to normal projectile values

### PR DESCRIPTION
**Pull request by ghost**
Yeah, this might not fix the myriad of very strange collision issues, but at least the rockets travel faster than a geriatric patient now, so that's something

:cl:
 * rscadd: Massive increased RPG projectile speed because it's a rocket, you know

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Aren't those the player-controlled Nikita thing
The whole point of making them slow is so that it actually matters that the player controls them I thought

**Comment by SonixApache** [comment]
make sure you lower it for the nikita so it remains controllable

**Comment by ghost** [comment]
Unless I misread something, the nikita has hard-set speeds

**Comment by ghost** [comment]
Did a full testing check, the Nikita is not affected at ALL by those changes, it still uses its current movement method of speeding up the longer it is set on the same course, and resetting when turned

**Comment by ShiftyRail** [comment]
As if Nuke Ops wasn't easy mode enough already

**Comment by Kurfursten** [comment]
Forgive them, they know not what they 👍

**Pull request merged**
