### PR TITLE
removes wheelstation

### PR DESCRIPTION
**Pull request by SonixApache**
it's not even in the mapvote and afaik it's universally loathed

naturally, this will require accompanying secret repo and travis changes

If you want to see more quality content removal like this please pay my salary
https://www.patreon.com/pomf

### CODE REVIEW

**Comment by cloutcode** [comment]
take a penny, leave a penny
i'm expecting the "readds bagel" pr on my desk by 5

**Comment by FlintBarrel** [comment]
I'm gonna miss that gigantic chapel

**Comment by ShiftyRail** [comment]
You forgot to remove it from Travis.

**Comment by SonixApache** [comment]
I don't know how to remove things from Travis.

**Comment by ShiftyRail** [comment]
Edit `.travis.yml` in your repo, CTRL+F "wheelstation.dmm" and remove that line
done

**Comment by Zth--** [comment]
Zip it and move it to an "archived" or "unmaintained" folder instead? This way future new mappers can pick it up easily

**Comment by SonixApache** [comment]
future mappers can just go to this PR to grab the last version of the .dmm

**Comment by DamianX** [comment]
rest in peace

**Pull request merged**
