### PR TITLE
Revert "squeak squeak motherfucker"

### PR DESCRIPTION
**Pull request by carshalash**
Reverts d3athrow/vgstation13#10834 I warned you

### CODE REVIEW

**Comment by ComicIronic** [comment]
But why

**Comment by carshalash** [comment]
I warned him.

**Comment by ComicIronic** [comment]
That's no good.

**Comment by TheFriggenSawbones** [comment]
zachary what the fuck

**Comment by carshalash** [comment]
I warned him.

**Comment by ComicIronic** [comment]
Keep your Discord memes out of the repo, this is not your toyhouse.

**Comment by 9600bauds** [comment]
¿??

**Pull request closed without merging**
