### PR TITLE
Wizard staff sprite and size changes

### PR DESCRIPTION
**Pull request by SonixApache**
- Makes the staff of Animation and Wand of Destruction use some of the unique sprites we have laying around
- Moves wizard shit sprites from guns.dmi to wizard.dmi
- Moves the Staff of Necromancy to modules\projectiles\guns\energy\special.dm where the other staffs are and adjusts the appropriate paths (which also means it's the same size as other staffs now)
 - Allows staffs to be worn on wizard robes

Staff of Focus, Staff of Change, Wizard
staffs
Staff of Necromancy, Staff of Animation, Wand of Destruction

:cl:
- imageadd: The Staff of Animation and Wand of Destruction now use unique sprites.
 - tweak: Wizard robes may now hold staffs.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
What about shortening the wand of destruction a bit, so it's not the same size as the staves?

**Comment by Shadowmech88** [comment]
Also, the wand of destruction still needs to be made obtainable in some way, though that could be done in a different PR.

**Comment by SonixApache** [comment]
Wand of Destruction and it's llifekiller variant are ridiculously strong, might be best kept for bus. Maybe map them into an away mission. Working on the sprite now.

**Comment by SonixApache** [comment]
@Shadowmech88 
resize compared wands
afterresize full comparison

**Comment by Sprok0** [comment]
This allows you to put the staff of necromancy in a turret and it'll fire staff of change projectiles, is there any reason to make it a subtype of energy guns if it doesn't actually use any gun code?

**Comment by SonixApache** [comment]
@Sprok0 
It's a self-contained gun, change done mostly to make the resize and carry allowing easier, and because it's weird that one of the five staffs isn't where the other four are. 
Necromancy turrets sound like a benefit rather than a defecit to me.

**Pull request merged**
