### PR TITLE
New Lobby Splashscreen

### PR DESCRIPTION
**Pull request by gurfan**
Credit: @Kromkar

EternalScientist480

## Changelog

:cl:
 * rscadd: Added a new lobby screen made by Kromkar.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Needs more science attire otherwise 7/10

**Comment by wotisjanitor** [comment]
Low Quality

**Comment by Kromkar** [comment]
> Low Quality

Rude

**Comment by Kromkar** [comment]
> Needs more science attire otherwise 7/10

I didn't really know what else to put on him beyond the pants and PDA

**Comment by boy2mantwicethefam** [comment]
Jumpsuit and labcoat (with necktie)
Ablative vest
A bag of holding on his back (maybe revealing a few guns like a subspace tunneler with a bluespace crystal on it)
The gloves (stolen via a telesci spreadsheet) and PDA are good

**Comment by Kromkar** [comment]
> Jumpsuit and labcoat (with necktie) Ablative vest A bag of holding on his back (maybe revealing a few guns like a subspace tunneler with a bluespace crystal on it) The gloves (stolen via a telesci spreadsheet) and PDA are good

Give me all the sprites for that and I'll probably PR an update for it

**Comment by boy2mantwicethefam** [comment]
I doubt it's possible to fit the jumpsuit, labcoat, necktie, ablative and bag of holding sprites over the image without it looking ugly compared to just hand-drawing it like the other clothes so have an assembled subspace tunneler.
tunneler

**Comment by nervere** [comment]
Low effort edit of an existing splash screen, and for what? Some anti-semitic /pol/ bait? Pass.

**Comment by Kromkar** [comment]
> Low effort edit of an existing splash screen, and for what? Some anti-semitic /pol/ bait? Pass.

Sorry but I was doing this for one of our glorious headmins

**Comment by pedr69** [comment]
needs more ablatives and gaygax mechas

**Comment by BomberBro** [comment]
What Nervere said but unironically. Splash screens shouldn't reek of 10 minutes in MSpaint, especially if they aren't even animated. At the minimum the "scientist" should be completely redrawn in the same pose as a real scientist instead of splashing the paint bucket tool on a guy that doesn't look like one.

**Comment by tinysaturn** [comment]
>muh  andysemantism hurrr

and they said the TG headmin was actually le based THOUGH
Anyway, I agree the scientist doesn't have much of a science look
He looks like an assistant who just stole a scientist's PDA (deep civilian conspiracy??!!!!??)
I think the bloodied knife ought to be replaced by the holo-tool e-sword + boy2man's suggestions

**Comment by SECBATON-GRIFFON** [comment]
yeah give him more of an actual sci coat if you're just gonna reference a wyatt mann cartoons

**Comment by dinnerwoerror** [comment]
why do they persecute artists so?

**Comment by SonixApache** [comment]
garbage

**Comment by Kromkar** [comment]
Alas, another tortured artist denied the chance for his vision to be realized, at the behest of an insidious international cabal.

**Comment by gurfan** [comment]
@Kromkar Let me know if you want to try again.

**Comment by dinnerwoerror** [comment]
why do they persecute you so?

**Pull request closed without merging**
