### PR TITLE
MULEs Work Again

### LINKED ISSUE #35545: MULE, you are broken - let me count the ways
1. Could not deliver to a further navbeacon (medbay) but could to janitor
2. Then janitor stopped working too, so it's clearly not a problem with the beacon
3. All MULEs, if on, will try to go to the laser pointer, causing collision issues
4. All MULEs seem to queue up laser pointer orders, so if you turn one off to avoid the above, next time you turn it on it will hurry to go to every place you've ever pinged before any package orders
5. They never stop flashing! Even if power is off or status is not moving, they stay flashing!
6. Pinpointing crates to pick them up doesn't work anymore
7. Auto unload didn't work when it arrived at flaps
8. Auto return didn't work either
9. Auto pickup crate isn't working - crates will instead interrupt pathfinding
10. Cell power never drains? Unsure since it was such a pain to get them to move at all, but even moving back and forth and leaving it online, the cell charge didn't seem to deplete. Nothing in mulebot code seems to reduce it.

### PR DESCRIPTION
**Pull request by jwhitak**
# MULEs Work Again
image

## What this does
Makes MULEs work again, while also keeping all the fancy features from #31944 such as the laser pointer.

There's a large changelog of small bugs that were fixed, see below for more details. Some easy QOL features were added as well, such as a menu showing all the valid navbeacons available as delivery destinations, and a slight improvement to the cargo PDA app.

Fixes #35545, #33854, #32455, #26208. However, the PR did not test pAIs inside of MULEs, so the issues with those may persist. Additionally, this code is an absolute MESS. If there are any new bugs, try to be descriptive as possible on where you run into them.

## Why it's good
You can send your hacked MULE down the halls with your PDA again just like old times.

## Changelog

 * bugfix: MULEs actually work now.
 * bugfix: Cargo PDA app also works.
 * bugfix: MULE lights no longer blink forever.
 * rscadd: The Cargo PDA app now includes some upgrades: a select-your-destination menu, a cell-charge display, and a description of what it's carrying.
 * rscadd: Local MULE configurations also show this menu where possible.
 * bugfix: MULE Laser Pointers correctly identify if they are loading/unloading, and you can now load/unload adjacent crates.
 * bugfix: MULEs will now correctly listen for commands that mention them directly - no longer will all the bots respond at once.
 * rscadd: Large order queues can be cleared by summoning the MULE to your location, or power cycling it.
 * bugfix: MULEs automatically unload when they are sent to a beacon with a load.
 * bugfix: MULEs automatically load when they are sent to a beacon without a load, and there's something they can pick up there.
 * bugfix: MULEs will automatically return to their home base after going to their destination.
 * bugfix: The above three settings are configurable, but are on by default.
 * bugfix: MULEs can now navigate to far away navbeacons.
 * bugfix: MULEs should correctly report their status, ie: moving, idle, etc.
 * rscadd: MULEs now use power. 2 units per step. You can view their charge via the PDA or directly on the MULE.
 * bugfix: Boxstation Janitor Navbeacon now points the correct direction for delivery.
 * bugfix: Fixes indefinitely decaying old bot targets (floorbots, etc)

:cl:
* bugfix: MULEs work again, won't blink forever, properly report status.
* bugfix: MULE laser pointer now properly works, including loading and unloading.
* rscadd: The MULE PDA app works and is now more descriptive + selects from valid destinations.
* bugfix: MULEs once again use charge from their internal power cell.
* bugfix: Bots will never get stuck ignoring a target permanently as an old target.

### CODE REVIEW

**Comment by toomykins** [comment]
upvote for bugfix
image for making them use their batteries, poor mules.

**Comment by Servalfang** [comment]
Does this fix laser pointer mules permanently giving up if they can't pathfind around a target?

**Comment by jwhitak** [comment]
> Does this fix laser pointer mules permanently giving up if they can't pathfind around a target?

They do not permanently break down, but they will give up if there's literally no path to something. If it's because something's been put in their way, there's going to be some honking before it does give up. When it gives up, it'll usually just sit in that location by default with the laser pointer. PDA default will be to return home.

**Comment by ErrorsWindows** [comment]
they should make the honking noise when they run someone over
honest to god at the speed they go it would be actual natural selection, you'd have to be a deer in the headlights to get run over and killed by it and the car horn would just be the perfect insult to injury

**Comment by SonixApache** [comment]
that :cl: is way too big

**Comment by Kurfursten** [comment]
Add this advice line to wiki: `Large order queues can be cleared by summoning the MULE to your location, or power cycling it.`
As well as any other advice you deem relevant

I fixed your changelog to be reasonable (I have done this for Deity many times)

**Pull request merged**
