### PR TITLE
fixes #12773

### LINKED ISSUE #12773: fuel cans and welder tools
#### Description of issue
fuel cans can't be used to refill welder tools anymore; if you use a welder tool on a fuel can nothing happens, if you use a fuel can on a welding tool you will splash the fuel on the welding tool and on the floor.

#### Length of time in which bug has been known to occur

noticed today but i haven't used it in a while so i don't really know

#### Server revision

a5aa9e00802d5a10c916f8cb89606ec6c8e8d621 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Kurfursten**
Gives opencontainer to welders, silicate sprayers. fixes #12773

If other stuff needs it, guess we'll just have to rely on reports

:CL:
* bugfix: Welders and silicate sprayers are open containers now, meaning you can use fuel cans on them once again.

### CODE REVIEW

**Comment by Probe1** [comment]
Doesn't "Fixes #12345" need to be in the issue itself to auto close?

**Comment by Kurfursten** [comment]
That's why I edited it

**Comment by Probe1** [comment]
CRAFTY DEVIL

**Review by Probe1 — DISMISSED** [review]
looks gud 2 me

**Comment by Shadowmech88** [comment]
>Gives opencontainer to extinguishers

Doesn't using a wrench on a fire extinguisher give it the opencontainer flag already?
Giving it the opencontainer flag by default will make it impossible to stuff reagent containers into the nozzle.

**Comment by JustSumBody** [comment]
Also worth noting that giving fire extinguishers open container would affect #12235

**Comment by Kurfursten** [comment]
@Shadowmech88 Could you do that previously? Because previously opening the nozzle granted it OPENCONTAINER, so how were you stuffing something in without the OPENCONTAINER flag?

**Comment by Shadowmech88** [comment]
>Could you do that previously? Because previously opening the nozzle granted it OPENCONTAINER, so how were you stuffing something in without the OPENCONTAINER flag?

If you open the nozzle and use a beaker on it, you pour the beaker's contents into the fire extinguisher.
If the nozzle is closed and you use a beaker on it, you stuff the whole beaker into the nozzle, which lets you shoot it out of the extinguisher.
Same goes for all reagent_containers.

**Comment by PJB3005** [comment]
Same goes for most small items, you mean.

At least the launching bit.

**Comment by ComicIronic** [comment]
You have the option of automatically making the borg extinguisher wrenched, which is a better idea than modifying all the other extinguishers and taking away existing behaviour.

**Comment by Sprok0** [comment]
This would also mean that medborgs start with lube/polyacid extinguishers, while their emag item is just a spray bottle.

**Comment by Kurfursten** [comment]
@ComicIronic The existing behavior was already taken away. You used to be able to use fuel cans to refill extinguishers without having to unwrench them. It doesn't make sense to me that you need to remove the fillcap to fill an extinguisher from a can but not from a tank.

**Comment by ComicIronic** [comment]
Just because it was like that in the past doesn't mean it's correct for it to be like that now. If you can only refill a wrenched extinguisher, then you can only refill a wrenched extinguisher. Adding exceptions to that are only confusing behaviour. I think it's better to have it toggleable so you can still put stuff in the nozzle without pouring it into the extinguisher itself.

**Comment by Kurfursten** [comment]
I think I have come up with a compromise that will satisfy everyone.

I will create a new proc can_pour_into(obj/O) that returns OPENCONTAINER and can be used in the check for pouring, however, for the extinguisher object I will override the proc and return whether the pouring object is a fuel can. This way, fuel cans can retain their old ability to fill extinguishers without removing the fill cap, but it will not affect silicon balance or the ability to jam objects into the extinguisher.

**Comment by Probe1** [comment]
@ComicIronic what do you think f that

**Comment by Intigracy** [comment]
:+1:

**Comment by Shadowmech88** [comment]
It'll mean that fuel cans in particular can't ever be jammed into extinguisher nozzles.
I don't think that's a big deal, though.

**Comment by ComicIronic** [comment]
Wait, why should fuel cans refill extinguishers?

**Comment by Kurfursten** [comment]
Because they have since they were made, and what's the point of storing fluid in a fuel can if it's easier to one-click on a water tank?

**Comment by ComicIronic** [comment]
>Because they have since they were made

Just because it was like that in the past doesn't mean it's correct for it to be like that now.

>what's the point of storing fluid in a fuel can if it's easier to one-click on a water tank?

Because the fuel can is for storing fuel, for welders, and not for refilling water-spraying safety equipment? It seems like asking why the nozzle of a fuel pump can refill my car but is too big to fill a water bottle.

**Comment by Kurfursten** [comment]
Have you ever actually read the description of the fuel can?

**Comment by ComicIronic** [comment]
Then the convenience should be having water with you instead of needing to find a tank, but I don't see a compelling reason to give the fuel can a snowflake interaction when it's going to be used by people who would only be holding wrenches anyways.

**Comment by Sprok0** [comment]
The fuel can is for holding fuel for welders and acid for soldering irons, I've never even considered putting water in it.

**Comment by N3X15** [comment]
Looks like changes are planned but haven't been committed yet.  Contact a collab to have NF removed when the changes are done.

**Comment by Kurfursten** [comment]
In the spirit of getting this out of my hair, I just discarded the extinguisher changes entirely

This shouldn't be controversial anymore, just merge it

**Pull request merged**
