### PR TITLE
Smallstation: I can map too!

### PR DESCRIPTION
**Pull request by PJB3005**
Look I'm making a map!

Images inbound.

### CODE REVIEW

**Comment by clusterfack** [comment]
Conflicts

**Comment by Zth--** [comment]
It's like a mix between the derelict and the mining outpost, I like it :+1:

**Comment by PJB3005** [comment]
@clusterfack this map isn't read yet, at all.

**Comment by clusterfack** [comment]
CONFRICTS

**Comment by PJB3005** [comment]
Happy now?

**Comment by IratePirate** [comment]
Neat.

**Comment by FudgePucker** [comment]
AI shouldn't be that exposed.

If I am looking at this right, it is one Rwall away from being exposed from space.

Although I guess if the AI isn't that connected to the station, the cyborgs could drag it to a mining outpost undetected, but if a traitor needs to steal an AI it might be a little too easy.

**Comment by SysadminJeroen** [comment]
@FudgePucker I agree, it also seems that the comms are badly defended as well.

Other than that I think that this smaller map would be appreciated in certain time zones when there aren't a lot of players online.

**Comment by Ephx1** [comment]
I think my only complaint thus far (aside from AI core) is that it looks like medbay directly borders space with the tasty breakable windows. Medbay already gets depressurized every other round via bombing, it looks like we're just cutting out the middleman.

**Comment by ShiggyPiggy** [comment]
The only thing about this I dislike is that there's only one chemistry machines set in Chemistry.
It's one of the most used things in medbay, you know.

**Comment by PJB3005** [comment]
If I surrounded comms with some asteroid it'd be suprisingly well defended, also some turrets / camera / double r walls should help a lot.

**Comment by PJB3005** [comment]
wrong button

**Comment by sonime** [comment]
Out of curiosity, how does this have conflicts?

**Comment by PJB3005** [comment]
@sonime because instances (var edited objects on the map, what all the maps **ab**use) are terrible, and I did the better thing and made a ton of subtypes instead.

**Comment by sonime** [comment]
Ah

**Pull request closed without merging**
