### PR TITLE
Clicking yourself with an RCD/RPD won't bludgeon yourself anymore

### PR DESCRIPTION
**Pull request by gurfan**
## What this does
Clicking yourself with an RPD/RCD won't bludgeon yourself anymore.

## Why it's good
I'm tired of this shit.

## Changelog

:cl:
 * tweak: Clicking on yourself with an RPD/RCD won't bludgeon yourself anymore.

### CODE REVIEW

**Comment by gurfan** [comment]
epic title

**Comment by jwhitak** [comment]
In engineering, my speeseman would often return from space covered in blood. It was usually his own, thanks to self-whacks with the RPD. This will solve most of the covered in blood problems.

**Comment by WindowsErrors** [comment]
tooly the electrical toolbox says: remember, I'm always deadly even on help intent

**Comment by pedr69** [comment]
>can't do it even on harm intent

how much baby proofing do we need?

**Comment by wotisjanitor** [comment]
> how much baby proofing do we need?

we get it you go on 4chan

**Comment by PavelCIA** [comment]
Hitting yourself with a RCD should instantly build a wall and gib you

**Comment by djkramer123** [comment]
that would be great as a suicide interaction

**Comment by Rhimrifer** [comment]
If at least one of my own tools isn't covered in blood when I get back I know I've been slacking. But seriously, why is the RPD/RCD getting special treatment? Only time I've nearly consistently smacked myself is when I'm making an h/e grid. I've still smacked myself with more crowbars & pipe wrenches than the RPD.

**Comment by Kurfursten** [comment]
I think Rhimrhifer does have a point about consistency (I mean, you're gonna still wrench yourself) but the votes are clear on the public's view

**Pull request merged**
