### PR TITLE
firedoor shortcut

### PR DESCRIPTION
**Pull request by Kurfursten**
Was originally shift click but then I realized AIs might sometimes want to examine the door to check its pressure diff first.

🆑 
* rscadd: Silicons (and adminghosts) can now open a firelock without a warning prompt via ctrl-click.

### CODE REVIEW

**Comment by DamianX** [comment]
The warning is there for a reason.

**Comment by Blithering** [comment]
Crowbars are for those too cool to read warning labels

**Comment by Kurfursten** [comment]
There are times in life when a madmin or malf wants to open a lotta firedoors pronto.

**Comment by DamianX** [comment]
I'm not opposed to admins being able to bypass the warning but I would prefer if silicons couldn't accidentally do it.

**Comment by Kurfursten** [comment]
I don't think anyone actually feels strongly about this other than me and I don't actually care about sillycons so I'll just comment out silicons so it's admin only

**Comment by ghost** [comment]
Eh, it's really helpful for AI and borg. It's rarely just one or two firelocks you gotta open. God help you when you're trying to open ahead while dragging and pushing two things.

**Pull request merged**
