### PR TITLE
Fixes storage atoms having a stupid attackby()

### PR DESCRIPTION
**Pull request by PJB3005**
AKA fixes RPDs on storage atoms.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This didn't fix the problem for me

**Comment by PJB3005** [comment]
You actually inserted the RPD into it, right?

**Comment by Kurfursten** [comment]
Right, although it also still happens if the backpack is full which is kind of annoying but understandable

**Comment by PJB3005** [comment]
Yeah this still lets it happen when the backpack is full (intentional)

**Comment by Kurfursten** [comment]
Get on the test server and I'll show you, I'm reproducing it right now with space in backpack

**Pull request merged**
