### PR TITLE
Violet Crayon back to Purple

### LINKED ISSUE #25102: Purple crayons are incapable of coloring stuff.
(WEB REPORT BY: potatomancake REMOTE: 206.221.180.138:7777)
# Revision
a7ab877f80e501efc4e4d07471cdd98625ef80ca

# Description
Washing machine reactions for purple crayons no longer work since https://github.com/vgstation-coders/vgstation13/pull/24706 .

Purple crayons got renamed to violet crayons, and since it looks like the washing machine looks at colourName on crayons to figure out what it should be colored, it's looking for violet versions of things instead of purple and breaking. Also tested it on coloring eggs, which calls the same line.

The irony is palpable.
# Steps to Reproduce
Put the crayon formerly known as purple in the wash with my gloves
# What you Expected
Purple gloves
# What Actually Happened
Machine ate my crayon and I still have yellow gloves

### PR DESCRIPTION
**Pull request by ghost**
Should fix some things that rely on using purple crayons, like dying gloves. Fixes #25102. Should not break Ancient's slime dyeing thing unless there's some underlying thing that really depended on the crayon being named violet that I don't know about.

:cl:
 * bugfix: Violet crayon renamed back to Purple

### CODE REVIEW

**Comment by jknpj** [comment]
replace every violet with purple

**Comment by ghost** [comment]
Sure, but at least nothing depends on paint being labelled Violet.

**Comment by jknpj** [comment]
the slime paint thing does

**Comment by ghost** [comment]
Unless I am reading #24706 incorrectly, it doesn't depend on the labels of the colours, it just depends on the hexadecimal colour associated with the colour. The change that Ancient made related to the colour of the crayons was unnecessary.

**Comment by Kurfursten** [comment]
When you eat a crayon according to that PR, it grabs the color off a specific kind of paint. `M.reagents.add_reagent("paint_[colourName]", 10)`

So the crayon colourName needs to match a name (e.g.: violet and paint_violet). It pulls the hex off of whatever paint it matched.

**Comment by ghost** [comment]
Yeah, I see now, I was reading it wrong then by missing that [colourname] reagent. Closing then until I can fix it all up.

**Pull request closed without merging**
