### PR TITLE
power cells are now smol

### PR DESCRIPTION
**Pull request by ScrambledSteak**
Power Cells are now SMALL items, so they fit in pockets. Because you could put them on gloves and they'd fit in your pocket, but they wouldn't fit in your pocket by themselves. ???

:cl:
- tweak: Made power cells small items, now they fit in your pockets.

### CODE REVIEW

**Comment by Sprok0** [comment]
I've always thought they were like car battery sized, and the fact that they vanish into stungloves is dumb

**Comment by ScrambledSteak** [comment]
Stungloves shouldn't even be a thing if they're the size of car batteries

**Comment by Sprok0** [comment]
Originally you just put wires on gloves, then rubbed a cell against them to charge them up. I don't know who decided to make actually attaching the cell to them a thing

**Comment by Exxion** [comment]
The concept of charging wires up doesn't actually make any sense at all

**Comment by Sprok0** [comment]
It was like a static shock type thing, it'd zap you if you tried to do it with non-insulated gloves, but I guess someone along the line decided stungloves needed to be stronger and more available?

**Comment by Exxion** [comment]
Yes
That doesn't make any sense
Wires and other conductive things are the *worst* for holding some kind of static charge, except in specific circumstances such as capacitors
And a battery can't impart a static charge to something because it requires a closed circuit (also except for capacitors)
(I don't think charges on capacitors actually count as static, but close enough)

**Comment by clusterfack** [comment]
What about power cells size being based on strength

**Comment by ScrambledSteak** [comment]
I thought the advancements in technology would've let R&D make all these ridiculously strong batteries while keeping a small size. They all fit perfectly into APCs after all.

**Comment by Anton-Kr** [comment]
APCs are s till relatively large-ish stationary structures.

**Comment by Sprok0** [comment]
Better solution: Make stun gloves normal sized items

**Comment by Megamaw** [comment]
6 years i've been playin this game and no one's once implied to me they're supposed to be car batteries. look at how fuckin small that sprite is.

i support this pr

**Comment by PJB3005** [comment]
I always knew they're supposed to be car batteries but never felt like it.

Also, don't we have a joke power cell called an NT AA battery?

**Comment by kilozombie** [comment]
Also, you can fit 14 of them in a toolbox. They can't possibly be car battery size
ALSO, can't you put potato batteries in APCs? Potatoes fit in pockets, potato batteries fit in APCs, therefore APC size objects should fit in pockets.

**Comment by Sprok0** [comment]
You can fit the same number of full size fire extinguishers in a toolbox too.

This is the sprite that convinces me most that they're car battery type things.
carbattery

**Comment by Iamgoofball** [comment]
@Sprok0 nothing in this game follows a proper scale

you shouldn't be thinking about the size of the item's gameplay inventory size based on sprites, think about it from a balance standpoint(which is worthless too because it's a fucking battery)

**Comment by kilozombie** [comment]
Measure it by how much damage it does, DPS, status effects, range, attack delay, and Nanotrasen Market asking price.

**Comment by Iamgoofball** [comment]
exactly

**Comment by 9600bauds** [comment]
Just nuke scrubgloves into not being a straight upgrade from stunprods already.

**Comment by Iamgoofball** [comment]
You guys would have to ignore players completely, they hate shitglove removals.

**Review by ComicIronic — APPROVED** [review]

**Review by Probe1 — APPROVED** [review]
Balance wise it's acceptable.  I'll pester for an in game vote (not a server poll) to make sure no one really gives a shit.

**Review by PJB3005 — APPROVED** [review]

**Comment by Probe1** [comment]
Custom vote started by Kammerjunk.
**Should batteries fit in pockets and boxes?**
Type vote to place your votes.
You have 60 seconds to vote.

OOC: Ephx: aaaaaaaaaaaaaaaaaaaaaaaaaa

OOC: Firestickman: Wait, they don't?

OOC: Raffa2: i'm a little triggered, it's a change

**OOC: Hugobertington: IF YOU VOTE YES, YOU ARE ENGINEERING LE SLIPPERY SLOPE OF ATTACK ANIMATIONS AND TABLE CLIMBING AND HIPPIE TEEGEE BAY REEEEEEEEEEEEEE**

OOC: SiliconEagle: battery?

OOC: SiliconEagle: There are batteries in ss13?

Vote Result: **Yes with 21 votes**
	No had 2 votes

**Pull request merged**
