### PR TITLE
Dandelion Field 13

### PR DESCRIPTION
**Pull request by DeityLink**
image

backend:
* added support for particles on hydroponic plants
* added support for roots showing up in hydroponic trays, but not on soil
* added support for plants having multiple harvestable stages with different products
* added support for plants to react to wind

image
dandelionblowdandelion
airflow
image

:cl:
* imageadd: The old vaguely dandelion-looking weeds have had an art pass and now look slightly more like dandelions.
* rscadd: Added dandelion seeds to the MegaSeed Servitor's contraband products.
* rscadd: Dandelions may be harvested as soon as their yellow flowers have bloomed, but waiting further will allow the flowers to turn into pappus, which can be harvested themselves.
* rscadd: Dandelion flowers can be ground for their yellow dye, or turned into leafy incense by using it on an incense oil container.
* rscadd: Dandelion pappus can be used 3 times to spread their seeds onto nearby empty trays or soil.
* rscadd: Dandelions both in trays or harvested as pappus will spread their seeds when exposed to air currents.
* imageadd: Added in-hand icons for Dandelions, Sunflowers, Harebells, Novaflowers and Moonflowers.
* bugfix: Pre-mapped tower-cap logs can now be properly have their seeds extracted.
* bugfix: Flavor texts when plants mutate and whatnot should now properly account for the plant's designation being singular or plural.
* rscadd: Dandelions can be mutate into Dandelions(?) which re-use the old weeds sprites.

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
you know what
i like this
would be cool if you could make wishes with the second stage one tho, maybe make it work like adminprayers?

**Comment by hacker-on-steroids** [comment]
>here, blow on this dandelion
>pushes it into your mouth as you breathe in
>PPFPPFPFPPFTPPTT

**Comment by DeityLink** [comment]
good news for the nostalgic ones, the old dandelion weeds can be grown again by mutating dandelions. 
image

they have the same stats they used to have so you can splice their Phytochemistry with another plant if you wish to reduce its potency for some reason.

**Comment by Eneocho** [comment]
SPEEDMERGE WHEN?????

**Comment by wotisjanitor** [comment]
Merged in 1 day actually feedback this guy

**Pull request merged**
