### PR TITLE
Lifts ghost body restrictions on becoming space hobo

### LINKED ISSUE #29946: Gibbed players can't become space hobos
#### Description of issue
Space hobo button rejects gibbed players, presumably because they don't have a body to return to and therefore it thinks they're observers.

#### What you expected
be space hobo

#### What actually happened
You must have had presence on this plane to become this.

#### Steps to reproduce
1. get fed to duck or singulo or gibber or etc
2. press hobo button
3. don't be hobo

### PR DESCRIPTION
**Pull request by ghost**
[tweak]
Because some users and even admins have given this the okay due to the fact that this role doesn't really cause much trouble anyways.
Closes #29946.
:cl:
 * tweak: Ghosts no longer need to have an active corpse or presence in a round to become a space hobo.

### CODE REVIEW

**Comment by Armadingus** [comment]
Can you tell me what happens when you observe and go space hobo before the round starts and wait until the timer finishes?

**Comment by ghost** [comment]
> Can you tell me what happens when you observe and go space hobo before the round starts and wait until the timer finishes?

You can just immediately become one now, like with mice and mommis

**Comment by Armadingus** [comment]
Let me be more specific.
Will you end up spawning in primary tool storage with the assistants upon roundstart, if you were to spawn in as a hobo while everyone else is readying up?

**Comment by ghost** [comment]
> Let me be more specific. Will you end up spawning in primary tool storage with the assistants upon roundstart, if you were to spawn in as a hobo while everyone else is readying up?

Thanks for notifying this, should be easy to fix.

**Pull request merged**
