### PR TITLE
Vocal Implants

### PR DESCRIPTION
**Pull request by ghost**
[content]
Another idea I've had for a long time but only did now.

## What this does
Adds a new type of implant called vocal implants to the engineering specials in syndicate uplinks, costs 8 TC and 6 with a discount for mechanics and the chief engineer.
When used in hand, has two modes: basic and advanced. Basic can set an input phrase (with full regex support) and one or more output phrases any amount of times; when implanted in someone, their voice will have the input phrase changed to their output one. Advanced is a reimplementation of NTSL as used in telecomms traffic control computers, procs and vars retooled to fit mob speech.

## Why it's good
Gives "telecommunications technicians" their own thematic traitor item that allows for not as lethal antagonising with heavy customisability.

## Changelog
:cl:
 * rscadd: Syndicate traitors can now purchase vocal implants from their uplinks, costing 8 telecrystals. (6 with a discount for mechanics and chief engineers) When used in hand, it has a basic and advanced mode: basic can set input phrases that can be turned into outputted ones when spoken by the person they are implanted in, and advanced is a full scripting language as seen in telecomms computers retooled to modify the mob's speech.

### CODE REVIEW

**Comment by Eneocho** [comment]
Lets see if I get it: 
I get that implant, set it so "help" becomes "sneed" and implant it onto the captain. If he screams "HELP" it will get turned into "SNEED", correct?
Kinda underwhelming considering you can use scripts to do that without using your limited TC, though I guess it could come in use on the occasion they start using station bounced radios instead of comms.

**Comment by pedr69** [comment]
but bounced radios already go through comms? provided the comms are up

**Comment by Eneocho** [comment]
I meant when they switch to a non-tcomm frequency after you tampered with the messages for long enough.

**Comment by tuypo1** [comment]
Seems a bit overpriced but I like it

**Comment by ghost** [comment]
> Seems a bit overpriced but I like it

What would you suggest? 6 normally 4 discount?

**Comment by tuypo1** [comment]
I would suggest closer to 2 and 1 with discount

**Comment by Blithering** [comment]
Sounds fun, can you set multiple phrases to check for by implanting them repeatedly?

**Comment by ghost** [comment]
> Sounds fun, can you set multiple phrases to check for by implanting them repeatedly?

You can set multiple on one implant

**Comment by boy2mantwicethefam** [comment]
The lalilulelo

**Comment by tuypo1** [comment]
Oh well if it's multiple on one implant I take back saying it should be only 2 TC, 3/4

**Comment by west3436** [comment]
I just don't see these being purchased more than once per user (then they'll realize they are lame). Scripts are far more powerful and as soon as a victim notices a filter is being applied they'll just say things using different words.

**Comment by Blithering** [comment]
> I just don't see these being purchased more than once per user (then they'll realize they are lame). Scripts are far more powerful and as soon as a victim notices a filter is being applied they'll just say things using different words.

Scripts only work over radio, whereas this modifies what they're saying. As for changing the words, that's just a battle of imagination between the person trying to get help and the guy setting the filters.

**Comment by Eneocho** [comment]
We all seem to be forgetting that you gotta implant the things into your target, so he either knows he's implanted and will try to get it removed (for all he knows it's an e-implant), or he knows you are the syndie, which is not good for your survival.

**Comment by Blithering** [comment]
> We all seem to be forgetting that you gotta implant the things into your target, so he either knows he's implanted and will try to get it removed (for all he knows it's an e-implant), or he knows you are the syndie, which is not good for your survival.

Or you prepared beforehand and he knows neither?
wear a disguise, knock him out beforehand, he only knows he got knocked out by some unknown and woke up fine, runs to sec, thanks to the vocal implant he says I got [a bomb, allahu akbar]! and then the explosive implant you also put in him goes off.

**Comment by ghost** [comment]
> I just don't see these being purchased more than once per user (then they'll realize they are lame). Scripts are far more powerful and as soon as a victim notices a filter is being applied they'll just say things using different words.

I did already say I want to add a script implementation to these in this PR or another

**Comment by ghost** [comment]
Starting to make an advanced mode similar to telecomms scripting now @west3436

**Comment by Eneocho** [comment]
wiki updated

**Pull request merged**
