### PR TITLE
reverted the change that made cat ears give brain damage

### LINKED ISSUE #18462: I think the cat ears brain damage thing has run its course.
I think we have evolved where this novelty/meme pr is no longer required.  it was a nice joke 6 months ago, but this isn't really a good way to handle "people are doing things I don't like."   I move that we revert this change.

### PR DESCRIPTION
**Pull request by Intigracy**
closes #18462 

:cl:
- tweak: Reverted the change that made cat ears give brain damage over time.

### CODE REVIEW

**Comment by ghost** [comment]
jesus fuck who thought merging this was a good idea

**Comment by ghost** [comment]
@falafox rational thinkers
we live in a society

**Comment by ghost** [comment]
hi thread kids

**Comment by DamianX** [comment]
we literally had a server poll about this

**Comment by SonixApache** [comment]
Yes, we shifted the brain damage from OOC to IC. Now the time has come to reverse this again.

**Comment by Gringonius** [comment]
So much for democracy

**Pull request merged**
