### PR TITLE
Increases Rev Reveal Threshold to 50% of the Crew

### LINKED ISSUE #24138: rebalance rev alert
the rev alert happens at way too low a threshold
i've been revhead twice since this was merged, and the alert is such a pain in the ass

this time around, I was only able to use my flash once before we were forced to go loud.
please up the percentage to maybe 60% or 70% of the station

I would wager that revs have 0 victories since #22805 was merged

### PR DESCRIPTION
**Pull request by Kharkov72**
closes #24138 
40 may be a bit low, as the people you AREN'T implanting are going to be people like security and heads who are kinda significant threats, but cults 60 is too high for a faster gamemode like this
discuss
[discussion]

:cl:
 * tweak: Revs now get revealed at 50% of the crew converted instead of 40%

### CODE REVIEW

**Comment by Durgen** [comment]
i think 50 is still too low
consider that with this merged, the heads go from zero to 100 and immediately go code red and get backup in the form of an ERT
tbh the original should just be reverted, but if we are insisting on a threshold, I would say 70 is better

can someone grab the winloss stats on rev after 40% was merged? I think it would be instructive on how hard rev is cucked by this

**Comment by brndd** [comment]
fuck revs tbh

**Comment by utilitas-** [comment]
The reveal threshold should discount loyalty implanted crew. And then set it to 90%.

**Comment by boy2mantwicethefam** [comment]
tbh I wanted to do this but set the reveal threshold to 60% where the revs had the majority advantage

**Comment by Durgen** [comment]
emojis might be misleading on this, because some people probably want the threshold even higher

**Comment by ShiftyRail** [comment]
Indifferent about 50%, vehemently opposed to anything above. Revs grow exponentially, 40% was a perfectly fine treeshold.

**Comment by incakola** [comment]
why not just 40% of total crew including silicons?

**Pull request merged**
