### PR TITLE
Slot machines influenced by luck, scratch cards less influenced by luck, & made luckier clovers rarer.

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
This makes slot machines affected by luck. Also makes it so getting clovers beyond two-leaf and four-leaf requires a bit more luck to do, so it's a little harder to get your hands on them. I didn't realize how straightforward it was to get a plant with 100+ potency originally.

## Why it's good
Since scratchcards are affected by luck it seems natural to have slot machines affected as well. And this is less of a "money glut" risk than scratchcards because each slot machine has way less cash in it than the scratch card jackpots. And observing and messing around a bit yesterday it seemed rather easy to get the higher tier clovers so hopefully this makes it a bit nicer.

:cl:
 * rscadd: Slot machines are now affected by luck.
 * tweak: Made lucky clovers a bit more rare.
 * tweak: Scaled down scratchcard luck influence.

### CODE REVIEW

**Comment by Cartlord** [comment]
Robust Harvest alone can get a plant to ~138 Potency, though it gets slower the closer you are to 140. That seems like a good number to balance your thing around.

**Comment by Kurfursten** [comment]
Thread so far has confirmed what I said in the original PR, which is that no one has noticed bad luck effects whatsoever but it has already been gamed to produce huge amounts of credits from near guaranteed wins at gambling (they said slot machine but I am guessing they meant scratch off lotto tickets since this PR is the one that adds luck to slots). This PR leans into the idea that luck is just a mechanic for winning money. I don't like it but it's consistent with the original PR, where that was also the case.

**Comment by Eneocho** [comment]
I messed around with the clovers and managed to get the highest tiers. It's not that easy per se, a regular player would need to be very lucky to get them, but once you do get them (either via mechanical knowhow or just dumb luck) they're very powerful.

**Comment by Eneocho** [comment]
Since you're tweaking the clovers, please make them not leave crumbs when eaten.  Just add base_crumb_chance = 0 to the clover snack.

**Comment by pedr69** [comment]
>making huge amounts of money

good?
do you know about the random lottery, which has a chance to give you a million and a half credits without doing ANYTHING, and notifies noone, apart from a newscast which doesn't even tell you who won?

**Comment by Kurfursten** [comment]
Yes, also bad, only redeeming factor is that it is very rare and not gameable. I don't know why anyone would want to be compared to one of the least inspired chunks of oldcode. I'm guessing Hini's next PR will be to make luck affect that event too.

**Comment by Hinaichigo** [comment]
Would it be better if luck didn't affect gambling, or affected it less? Maybe with the luckier clovers being rarer it'll be a bit tricker. Money itself doesn't have that much utility, aside from ordering cargo items, as far as I know, and having a lot of money doesn't necessarily make someone overpowered or give them access to rare items or allow them to cheese other people in combat or anything. Clown or someone could lubeslip them and snatch the money out of the PDA even.

Or does it mess with mining balance?

The scratchcards do seem a bit excessive currently, so I'll tone those down.

> please make them not leave crumbs when eaten

How come? I kinda like the idea of the botanist eating fistful after fistful of clovers and the janitor having to clean the clover juice off the floor.

**Comment by Kurfursten** [comment]
I think one of three things should happen: either luck should impact the gambling games less, a win of any amount should cause a loss of temporary luck, or their base winrate should be adjusted down to accommodate the new way to win. Their original winrates were fairly generous and based around no luck, but now anyone seriously intending to play a lot of slots or scratch off is going to be stacking luck. I've never bought the "we don't use money for much" argument - we've been slowly adding more uses for money for eight years now and this always comes up. Money is more meaningful than it has ever been - vending prices have been reformed, you can easily pay or tip people using the money dispense button on your PDA,  we now have a trader role with a variety of useful toys, department funds and miner incomes have both been adjusted down to fight inflation, and even more recently we have someone going over the cargo crates.

Regarding my more general complaint, that you don't notice luck at all unless you're stacking it for gambling - I would like to see more non-gambling related impacts for luck; more sources of bad luck and more effects for bad luck. Maybe eating clovers boosts your luck for a time but then karma swings back around and you get a penalty. You could offset this by eating more clovers of course, but then you would become basically addicted in a cycle of luck.

**Comment by Hinaichigo** [comment]
I see your points. I'll think about ways to incorporate what you said.

And if anyone has ideas for ways to get (un)luck or effects of (un)luck, let me know.
Some possibilities:
- coming into contact with an undead creature
- clovers containing some chemical which is mildly toxic above a certain threshold
- cursed dice giving, and being affected by, luck or unluck when rolled
- d20 rolls affected by luck

**Comment by Eneocho** [comment]
>clovers containing some chemical which is mildly toxic above a certain threshold

No point on this one since you can always splice it out. Or just chug alicin.
>And if anyone has ideas for ways to get unluck or effects of unluck, let me know.

We could add our own luck rituals, no need to base it on real luck superstition. Following that concept, here are some ideas:
* Slipping 3 times within one minute makes you temporarily unlucky.
* Syndie "unlucky gun" that fires bullets with condensed 0 leaf clover essence acquired in deep syndicate botanical labs, making you comically unlucky until you die/30 minutes pass.
* Bad Luck curse for wizards.
* Stepping on broken glass while not wearing footwear.
* Wizard Liquid Luck and Liquid Misfortune potions for lucky/unlucky wizard stuff (and some luck effects on some wiz spells or a spell that changes its effect based on luck).
* Pulsing the wrong cable on a vendor without gloves and/or shocking yourself on a vendor when trying to use it (you had no way to know and got shocked, unlucky)
* Alternate effect to farting on a bible (if you survive you become unlucky).
* Failing 10 tackle rolls in a row.
* Failing 10 scratch tickets in a row.
* Wearing certain clothing (unlucky but good in another way? roundstart randomized jumpsuit colour for unluckiness?)
* Not taking the keys with you when you leave the janicart.
* Having a glass shard from a broken beaker on you.
* Bus/rare monkey's paw item that either makes you very, very lucky or very, very unlucky, with 5 uses.
* Having the nuke disk on you (would add to the responsibility of keeping it safe and would enable le funny unlucky clown gimmicks when implanted onto his ass).
* Setting yourself on fire, either via causing the fire and not leaving in time or by failing a clumsycheck.
* Eating floorpills with bad effects.
* Hearing the forbidden tale (WGW) (You hear "One day while andy was masturbating" and get unlucky).
* Tripping/Slipping after running with scissors on you.
* Falling into crit from exclusively o2 damage with a roundstart unused tank on you (no excuses).
* Wearing cursed clothing, such as the unremovable cat ears+kneesocks combo from a bad diceroll (keep the regular catears and kneesocks neutral, only affect the cursed version).
* Grabbing a permaglued item by accident (doesn't happen if you permaglue while on hand).
* Being spooked by a ghost 3 times within 4 minutes (counteracted by drinking/splashing holy water or being blessed by a priest).
* Walking on the same tile as a ladder without using it.
* Smashing your head on a table 2 times in a row.
* Consuming Mannitol (punishment for the tgfugee).

**Comment by Hinaichigo** [comment]
Appreciate the ideas.

**Comment by Eneocho** [comment]
Trying to come up with ideas that are both gimmicky but not ruin some gameplay is hard. You could make it so eating burned messes is unlucky, but that would ruin the gunk chef gimmicks (which I find hilarious).

**Comment by Hinaichigo** [comment]
One thing I was thinking of is, if there's someone who keeps winning and cashing scratch cards, maybe a representative of the scratch card company (recruited from obsgang) comes over to try to do a product recall and take back the money or something.

And if he dies on the station.. it could invoke the wrath of the company and then it'd get into the corporate strike teams idea people were discussing recently. Maybe it could also work like if you vandalize a Groans Soda vending machine, an (armed) Groans Soda Loss Prevention Associate would come to request compensation.

>He is wearing a Groans Soda™ employee's jumpsuit.
>It has a Groans Soda™ logo pin, and a waistband holster attached.
>He is holding a limited edition Groans Soda™ promotional pen in his right hand.
>He is holding a clipboard in his left hand.

**Comment by Kurfursten** [comment]
I know your heart is in the right place, but having a dial-an-antag option is going to ENCOURAGE people to spam slot machines

**Comment by WindowsErrors** [comment]
i know there's gonna be at least one cargo gimmick where they get the scratch card company representative to come over and take them as a hostage

**Comment by Kurfursten** [comment]
More like it will happen every shift and no one will join as the antag role that spawns with a clipboard and a "kill me" t-shirt

**Comment by WindowsErrors** [comment]
if we are in a position to judge the slot machine spammers would we be in the same position to judge the people sent to stop the slot machine spammers?

**Comment by Kurfursten** [comment]
I don't get what you mean. No, you can't attack someone just for winning at slots a lot, which is why the role would need to be an antag. But if people knew winning slots summons a person they can valid, and that valid has no weapons, that would be used to provide entertainment for people who like to turn sprites sideways. This is the same discussion we had with prisoner transfer all over again.

**Comment by jwhitak** [comment]
I'm honestly leaning for removal of luck. If we have to keep it, we have to get stuff tweaked ASAP, with PRs like this one. Thumbs up emoji, please speedmerge.

It's too easy to just auto-win all of the lottery right now, and get all the positive mutations in a radstorm. There's no other purpose for luck (that I can tell). It wasn't clear in the previous PR what effect on the game luck would have... but now it's obvious: It's a means to just metagame lots of money and good powers. Let me underline: metagame. You don't get lucky and stumble upon a 4 leaf clover, you spam-grow them as a botanist intentionally for the purposes of cash. The reward is vastly greater than doing baby cargo orders. There's no means of getting randomly lucky, it's all intentional. Bad luck is rare enough and specific enough to effectively not exist as a downside. Something's gotta change.

**Comment by Hinaichigo** [comment]
As is currently, this PR nerfs the effects of luck on scratch cards and also makes it harder to get rarer clovers.
Though I'm not sure if it's metagaming per se to deliberately do something for the purposes of a reward. If you want resources, powers, an advantage, you do some in-game action. Trying to get a lucky item and then use it to your advantage is just one way to do this, along the same lines of mining up materials, doing research, and then making a high techlevel weapon. It is unbalanced currently and hopefully this PR will fix that, but I wouldn't call it metagaming.

And yeah luck should have more uses. It's a general system that things can plug into so they don't have to all be added at once, and people can add things incrementally if they have ideas.

**Comment by Eneocho** [comment]
Could you explain how the odds to get the rarer clovers work currently and the luck calculations for the luck based events for the wiki please?

**Comment by Eneocho** [comment]
You overcompensated too hard, man. Even with three seven leaf clovers and twenty-ish six leaf clovers, the most I won were 200 credits from a phazon ticket. There's no point in stacking massive luck modifiers if you can get the same odds by playing the supermatter tickets with robotic limbs.
I got substantially more money from the slot machines than the scratch tickets.

**Comment by Hinaichigo** [comment]
I guess we have to find some ideal sweet spot.. I'll mess around with the values a bit more.

**Comment by JonathanSpaceStation** [comment]
On a roll of 13 cursed dice always explode, but it feels like a really poor interaction because it means that you can potentially hurt people who you are standing near; as an alternative, you could make it so that a roll of 13 makes you extremely unlucky, that would be my suggestion

**Comment by Hinaichigo** [comment]
That sounds good. I'm going to wait for things to settle a bit more with the slots and scratch cards and see what people think, and then possibly rebalance them and maybe add some stuff like that with dice, maybe even with normal d20s and cursed dice too so you can get an advantage playing DnD getting lots of high rolls... only with dice it's hard to say you'll always want a high roll.. or the DM could be rolling, or there's plenty of situations where you might prefer a lower roll, so probably not change the actual rolling probabilities, except maybe for the cursed ones.

To do that (and coins) properly you'd need a way to specify what kind of outcome you want.. Maybe by whispering or saying "C'mon two!" while holding the die...

**Pull request merged**
