### PR TITLE
Cryogenics rework

### LINKED ISSUE #17345: Make Cryo Not Dupe Reagents
What it says on the tin.

https://github.com/vgstation-coders/vgstation13/issues/543

This might be relevant.

### PR DESCRIPTION
**Pull request by MadmanMartian**
Fixes cryo duping reagents, courtesy of reagents.reaction(mob, TOUCH) just adding more reagents without removing the reagents it is adding to the person. Closes #17345 

Because of this, Cryo would run through all of its chemicals within seconds, so now it has its own buffer reagents that the person is affected by. The beaker you place within cryo steadily injects reagents into cryo itself. Injection can be toggled, and the rate of injection can be controlled at a higher level of scanning module.

Reagents are not consumed from this buffer unless they can actively get to the user (Clothing with reagent permeability prevention will prevent consumption of the reagent.) so putting somebody in a hardsuit into cryo will do nothing to the buffer. The buffer itself, due to how touch reagents works, transfers half of itself every time it processes the occupant.

Cryo no longer passively heals brute, burn, oxygen deprivation, and toxin damage for free. 

:cl:
 * rscadd: Cryogenic tubes have now been reworked.
 * tweak: Cryogenics no longer passively heal brute, burn, oxygen deprivation, and toxin damage for free.
 * tweak: Cryogenics no longer duplicate chems put within them.
 * rscadd: The beaker placed within the cryo tube now steadily injects reagents into the tube itself, which are transferred to the occupant through touch. If the occupant is wearing impermeable clothing, they will not be consumed.
 * tweak: Cryo now consumes power.
 * rscadd: Upgrading the internal components of cryo now enables different abilities and increases active power consumption. Tier 2 scanning modules enables the ability to tweak injection rate, maximum injection rate depending on manipulator tier, Tier 3 scanning modules enables the cryo being able to auto-eject occupants at full health. Tier 4 scanning modules means cryo no longer stuns the occupant.

### CODE REVIEW

**Comment by robosperg** [comment]
I would like to see the passive heal remain, even if nerfed, +1 to everything else though

**Comment by Kammerjunk** [comment]
hi I actively said "totally do this" before it got made
I don't play though and I'm legally braindead so speak up or forever hold your peace

**Comment by Desuiseiseki** [comment]
Sneaking a bugfix in with your nerf.
Okay this is epic.

**Comment by Kurfursten** [comment]
I have two concerns
1. How do you empty the cryo tube if someone floods it with toxins?
2. It does not appear you can inspect the contents of the tube, only see if it has chemicals at all. You can still see the beaker contents but that's not what the patient is getting exposed to.

**Comment by MadmanMartian** [comment]
1. I could and will add a button for "vent chamber"
2. I was erring away from having the chambers contents be directly examinable, instead you need better scanning tech to get a good estimate via the UI.

**Comment by Probe1** [comment]
I would appreciate an audible sound and text alert that notifies people nearby that cryos beakers are empty.  Only activated when there is a beaker inserted so cryo isn't just constantly bitching.

**Comment by MadmanMartian** [comment]
Okay. Toggleable, and goes off if both the beaker and cryo itself are empty while an occupant resides within?

**Comment by bathosbathtime** [comment]
Please do not hide what is injecting into the patient behind science upgrades.

**Comment by Probe1** [comment]
I think that is the best idea.  Alert when a person is -in- cryo and the beaker is empty.  That resolves superfluous alarms that will annoy people while still making people aware there is a problem.

**Comment by MadmanMartian** [comment]
Some suggestions as to what the scanning modules should do would be appreciated

**Comment by Kurfursten** [comment]
T2 scanning modules automatically filter vomit out of cryo. You could even have it go to a buffer if medbay wants to ship it to the chef for recycled nutrition cubes.

T3 scanning modules add an "auto eject" toggle if the patient reaches full health. It's on a toggle so that you can prevent it from dumping someone who you're storing there temporarily because they have a virus [you need buy time for a cure] or internal bleeding [surgeon is busy].

T4 scanning modules reduce the patient's sleep to 0 every tick, allowing them to stay fully conscious inside cryo. Since these are almost never brought back from the roid, it should be pretty special.

**Comment by bathosbathtime** [comment]
They could tell you the exact amounts of the reagents, they could tell you how much damage each amount of reagent could heal, they give better diagnostics on the patient.  What reagents are present in the buffer, even without a number of units attached to each specific reagent, would be workable for T1.

**Comment by Probe1** [comment]
Just as an aside, T4 parts need improvement on their implementation.  I've almost exclusively played xenoarch in the time I've been back and when I see an Unknown on the scanner I consider it as bad as a carbon site.  Getting a _single_ T4 part and having to go back to the station, decide who gets it because no one urgently wants this stuff, and delivering it/arranging a pickup is too all too much.

Sorry for the aside.

**Comment by MadmanMartian** [comment]
>An unknown on the scanner

I fixed that bug recently. Odd.

**Comment by MadmanMartian** [comment]
So, turns out cryo never used power, because it was inheriting from machinery/atmospherics whose active and idle power usage are 0, so if it were turned on then the APC were to lose power, they would remain on indefinitely.

Yeah, I'm fixing that.

**Comment by bathosbathtime** [comment]
How large is the buffer?

**Comment by MadmanMartian** [comment]
The reagent buffer is 1000 units

**Comment by MadmanMartian** [comment]
That's as much as I'm willing to feature creep cryo for now.

**Comment by ShiftyRail** [comment]
Not sure if I understand it right, but I am not sure if making the tubes consume a fuckton of chems is a good idea

Medbay should be about solving problems and not slaving away at the chem dispenser 

But again I didn't play med in ages

**Comment by SonixApache** [comment]
if possible, being able to only put the cryo tube stuff back into a beaker rather than just ejecting it into the ether would be nice
like the IVs, where you can either take or recieve reagents, but no inbetweens

**Comment by MadmanMartian** [comment]
Okay

**Comment by nuklearcellphoneg** [comment]
is it finally time

https://github.com/vgstation-coders/vgstation13/issues/543

**Comment by MadmanMartian** [comment]
yes

**Comment by plosky1** [comment]
So if you put a regular 100u beaker with cryomix in, and it consumes half on touch, people inside will be dosed with 50u of an assload of chems? I believe you can OD on some of them if they go over a limit.

**Comment by MadmanMartian** [comment]
That's what the injection rate is for

**Comment by MadmanMartian** [comment]
god I hate HTML UIs

image

**Comment by FudgePucker** [comment]
>that's as much as I am willing to feature creep cyro

>In a PR that totally knee caps it

**Comment by Kammerjunk** [comment]
@ShiftyRail solve problems in a way that doesn't involve tossing every patient in cryo

**Comment by Probe1** [comment]
😰

**Comment by Irradiation** [comment]
Eff

**Comment by SonixApache** [comment]
Why??

**Comment by Kurfursten** [comment]
what was this waiting on? just the UI fix?

**Comment by Probe1** [comment]
I think so

**Pull request closed without merging**
