### PR TITLE
Un-nerfed Skeletons

### PR DESCRIPTION
**Pull request by Megamaw**
"When you code it," they said. So I did. No excuses, now.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
It seems a little dishonest to make the argument that there's no reason not to bring skeletons back due to their nerfs and then, once they are brought back, un-do the nerfs on which you based your argument.

image

**Comment by Megamaw** [comment]
i had yet to play with the nerfs.

they were way too fuckin' much. nearly diona speed, and the only racial benefit not mattering(no breathe) because amplified brute means they die instantly if any area is depressurized.

at the very least, I hope this starts up a dialogue about balance if it's not merged.

**Comment by TheFriggenSawbones** [comment]
god bless you

**Comment by TheFriggenSawbones** [comment]
god bless you

**Comment by carshalash** [comment]
There's lessening nerfs and then there is this.

**Comment by Exxion** [comment]
Alright I can deal with reducing the nerfs
But you are completely removing every single possible disadvantage other than lack of chems, all at once
Take things step by step, man

**Comment by carshalash** [comment]
If you were serious about this, you would have made it so that skeles are able to eat, have a 1.5 brute damage modifier  and given them a speed similiar to a normal fat human being.

This would be like if me or yahir came in and made a PR to make skeletons get super telepathy, normal punches and completely immune to being sprayed. Or if my boy exxion up there included vox into the asimov lawset.

**Comment by Megamaw** [comment]
i honestly dont think you guys have played skeletons to realize how awful 'no chems/pills' is

if you want to give a race a bunch of downsides, you should probably give them some upsides. right now, if this gets merged, they're still worse humans by virtue of a: no chems and b: not asimov protected.

**Comment by Shadowmech88** [comment]
>if this gets merged, they're still worse humans by virtue of a: no chems

I'm pretty sure races with the NO_INJECT flag can still consume pills and drink from medicine bottles.
Additionally, their upsides are not needing to breathe and having no blood.

**Comment by Shadowmech88** [comment]
A dry skeleton weighs something like 15% what a normal human weighs.

What about keeping the brute modifier, but making skeletons *faster* than humans instead of slower?

**Comment by carshalash** [comment]
Bingo, exactly why I said all they needed to have was the eating flag. 

And literally every other race but human isn't protected by asimov.  Removing the brute modifier 100% makes absolutely no sense at all considering how bones work.

**Comment by Megamaw** [comment]
see i've suggested that before but the answer was always a resounding no, and idk if that works right because iirc i remember someone saying its hard to make something faster than humans

**Comment by Shadowmech88** [comment]
It used to be. I altered the speed calculations so that it's possible now, even using a species datum. Grues, for example, are faster than humans.

**Comment by Exxion** [comment]
Even if you think that these changes *are* reasonable, still do them one at a time. Change it a bit. Still too weak? Change it again.
What you've done here is *HALVED* the brute damage they take, increased their speed by a shit ton, and removed all non-numerical drawbacks except one that is both a positive and a negative
To be entirely honest, it looks like a meme PR in this state

**Comment by IAGFPRMF** [comment]
Making them faster than other races sounds nice.

I'd rather not have assistant skeletons swarming the Nuke Ops shuttle like the old days so keep the ack (mostly) cracked

**Comment by Intigracy** [comment]
the obvious solution is to remove skeletons

**Comment by PJB3005** [comment]
Here's the way I see skeletons:

They're a literal joke that's only selectable out of humor, because they're so terrible nobody wants to select them, and nobody should ever want to other than humor. 

I'm fine with buffing them but only if they can't be selected round start. 

Big 👎 from me.

**Comment by Kammerjunk** [comment]
Shitter meme race is shit to play?
Oh well, whatever, nevermind.

**Comment by yclatious** [comment]
Have to agree with PJB, they are nothing but a joke race made for skeleton puns or other stupid shit, if you want to buff them so they aren't complete shit then make them non roundstart, otherwise fuck off with your skeleton fetish maw.

**Comment by nuklearcellphoneg** [comment]
Skeletons are a joke race

**Comment by Riekland** [comment]
Why are skeletons a roundstart race
Why are there vox other than traders/raiders/adminspawn
Why would you have skeletons be a thing outside haha wizards and haha genetics NO FUCK OFF WHY NOT ISNT AN ANSWER

**Comment by ghost** [comment]
Their brute mod discourages people to play a meme race so less people go around making bone puns and "ACK ACK ACK"

**Comment by yclatious** [comment]
Just because a shit race has a bad side to it doesn't mean it should be enabled roundstart, if your logic was sound we would enable Tarjarans because they periodically stun themselves and have a speech filter to shit like "KILL MEOW". 

Crack the ack, Skin the cat, Gas The vox, race war now.

**Comment by Megamaw** [comment]
Whether or not we have skeletons isn't up to collabs or coders, it's up to Pomf, whether people like it or not.

even with this, they're still currently a worse pick than diona, plasmaman, vox, or human.

is there a problem with wanting to balance what we have? surely, if this is somehow 'busted', someone would have explained why by now, right?

if you have a counterproposal, I'd love to see a PR.

**Comment by Orangerush** [comment]
Crack the ACK, Play plasmamen instead!

**Comment by yclatious** [comment]
I have a counterproposal, lets remove the skeletons.

The best way to solve a issue is to remove its source, nobody actually likes skelefuckers except mega, they add nothing interesting but bone puns and ACK ACK ACK, they are shit to play, players who play them tend to be eh anyways and nobody will miss them anyhow since we can shitpost about zonbie plasma skeletons instead,

Unfortunately, Git is my sworn mortal enemy so ill leave the job to someone else.

**Comment by Shadowmech88** [comment]
>even with this, they're still currently a worse pick than diona, plasmaman, vox, or human

I disagree. Your proposed changes leave them with only two downsides, one of which can be an advantage in certain situations, and the other can be remedied with a hyperzine pill if necessary.
Additionally, they have the advantages of lacking blood as well as nearly all internal organs, and not needing to breathe.
While dionae and plasmamen both have better strengths, they also have weaknesses to compensate. The skeletons' proposed downsides are very slight, to the point where they're definitely better than vox and arguably better than even humans, outside the issue of Asimov.

But the main issue here is how much you're buffing them, not just that you're buffing them at all.
Instead of halving their brute modifier and tripling their speed and giving them drinking and eating all in one go, why not split those up into a series of PRs? Buff them a little, see how that plays out, buff them a little more if necessary, et cetera?

**Comment by ihadtoregisterforthis** [comment]
Don't un-nerf skeletons, buff them sensibly. 
I support the extra speed

**Comment by Blithering** [comment]
I liked the no drinking and eating parts, they were fun, even if getting chefs to blend their hard made food and inject it into a slab of meat was a pain.
That said, I would personally like to see skeletons buffed heavily and made wizard and genetics only again.

**Comment by ComicIronic** [comment]
>Whether or not we have skeletons isn't up to collabs or coders, it's up to Pomf, whether people like it or not.

I mean that's really not the final decider of a lot of these issues, and it's certainly not something to hide behind to avoid criticism.

**Comment by Exxion** [comment]
If you think Pomf is going to support this, you're delusional, anyway

**Comment by yclatious** [comment]
Why did skeletons ever even get re—added to roundstart anyways?

**Comment by Shadowmech88** [comment]
Because someone complained about them not being available at roundstart for five months.

**Comment by yclatious** [comment]
How many months do I need to bitch and moan to get them removed then? Cant let these memes be dreams, lets finaly remove skeletons the same way they were introduced, someone with a love/hateboner bitching till someone budges :^)

**Comment by SonixApache** [comment]
@Intigracy you're supposed to write it in all lowercase dummy

**Comment by Ephx1** [comment]
lmao
also: "muh meme race" is still a very good reason for them not to be brought back. Spurdos when?

**Comment by Megamaw** [comment]
okay, i've gotten some good feedback on this. i think i'm ready to make a more reasonable PR in a bit.

though to be fair i've also gotten some very non-constructive meme feedback, so to those of you that didn't actually put in your two cents, get bent

**Pull request closed without merging**
