### PR TITLE
Max News Feed Length 1024 -> 9216 characters PLUS Large Input window

### PR DESCRIPTION
**Pull request by gurfan**
## What this does
Increases the max length of newscaster messages and lets you input text using the big message box, instead of the tiny one-line input, since going back and correcting typos was a slog.
I can't figure out how to get line breaks to work, though, I'll give that another shot when I'm not tired.

## Why it's good
I want to write.

## Changelog

:cl:
 * tweak: Increased the amount of characters you can write in a news feed
 * tweak: Writing in a news feed now uses a proper text box.

### CODE REVIEW

**Comment by ErrorsWindows** [comment]
does this also affect the PA system so the copypasta doesn't get cut off halfway through

**Comment by SECBATON-GRIFFON** [comment]
now we just need pencode for these

**Comment by Theophrastus1** [comment]
by all known laws of aviation

**Comment by jknpj** [comment]
What could possibly go wrong?

**Pull request merged**
