### PR TITLE
msay now has a sound effect

### PR DESCRIPTION
**Pull request by Intigracy**
waaagh
https://cdn.discordapp.com/attachments/245856152276041728/634556344246075408/-adminhelp.ogg

### CODE REVIEW

**Comment by SonixApache** [comment]
jesus no
make it something inconspicous, please, jesus

**Comment by Intigracy** [comment]
waagh

**Comment by Probe1** [comment]
Waaaaah

**Comment by Probe1** [comment]
But seriously. Not that.

**Comment by DamianX** [comment]
lol no

**Comment by DeityLink** [comment]
Heh, I love it.

**Comment by Intigracy** [comment]
I'll do a non meme PR for this that lets you select from a few choices in prefs.

**Comment by Intigracy** [comment]
Waaaagh

**Pull request closed without merging**
