### PR TITLE
Slimming Down Tradevend

### PR DESCRIPTION
**Pull request by Kurfursten**
Part of my crusade to make the list in the tradevend not so long and also crate-ize more stuff. This does a few things.
* Instead of buying individual capsules, you can get the gachakit with all 60. It's a random possibility in the new...
* Shoal junk crate. It has all the weird miscellaneous stuff. Gives 9 items, buy up to 3 times. Exact contents below.
* New outfitter vendor for the stuff not intended to be sold. Holds the spare suits, PDAs, IDs, stamps, crackerbox, and replacing the old donutbox, a new biscuitbox. Poly wanna biscuit?
* You can no longer separately buy advanced clown shoes, but they are guaranteed to be in the wonderful wardrobe (instead of a chance of getting a second pair). This doesn't count against the normal wardrobe item count.
* You can no longer buy brass and replicant alloy separately, but ralloy and brass both now appear in odd materials.

Shoal Crate Contents
* 5x Skin Dye
* 5x Upgrade Injector
* 5x Super Upgrade Injector
* 3x Box of Winter
* Generous Crank
* Borer Egg
* Echoes Vinyl (this may one day move to a service oriented crate)
* Sea Devil (ditto)
* Therapy Couch
* Station in a Can
* Bluespace Crystals Box (possibly may move to a future science oriented crate)
* Capsule kit

**Overall** this gives you more junk for less investment, but takes away some control so you are encouraged to buy upfront and see what's available, then market what you have.
Example contents: 2 skin dye (10ea/20), 2 upgrade injector (15ea/30), 1 super injector (50), 1 box of winter (50), therapy couch (50), bluespace crystals (150)
You would have paid:  350
You now pay: 100 

🆑 
* tweak: Several tradevend products were moved into the new shoal junk crate, which gives 9 random items.
* rscadd: Tradevend objects not intended for sale (e.g.: PDAs, spare IDs) have been moved to new outfitter.

### CODE REVIEW

**Comment by Blithering** [comment]
Weren't the gacha balls added as a form of intentional bloat so you couldn't just cut the throw wire and get all the good stuff?

**Comment by Kurfursten** [comment]
They were but you can't hack the tradevend at all now. To be honest, I would just remove them but I am sure someone would say "but my gacha gimmick!" so I figured I'd just consolidate them all into 1 object.

**Comment by cloutcode** [comment]
i, for one, support the gacha-fication of the trader role

**Comment by Eneocho** [comment]
I always thought that the unhackable-ness of tradervends was a bug. At least make it hackable to use without access.

**Comment by Kurfursten** [comment]
Nope, it even has a specific unhackable var for it, it's very much a feature (just like you can't hack the exosuit fab, for instance). Besides just avoiding traders getting all their products for free with the throw wire, you have to remember that all trader items are zero sum. So for example, if someone latejoins as trader and the scientist has already broken in to buy a bunch of the things out of their vendor, they're permanently denied the opportunity to sell those things -- unlike other jobs such as R&D or Cargo where those things can still be printed (and to be honest these roles don't care whether there's demand on station for an object).

In a perfect world, the tradevend wouldn't be a vendor at all, it would be some kind of unique machine or computer. But works for now. Anyway, all of this discussion is out-of-scope for PR.

**Comment by juanototo2** [comment]
Also.
>science oriented crate
I for one cannot wait for the advanced EOD helmet upgrade kit, for all your ablino needs. Oh and maybe something that links up with the autolathe and protolathe and allows you to automatically recycle tier 1 parts and print fresh tier 3 or so parts when you're out of parts in your PBRPED. That would be fun and nice.

**Comment by Eneocho** [comment]
Can't wait for botany/service oriented crates.

**Comment by ShiftyRail** [comment]
Map priority is less important now that we got TGM maps which hardly conflict with one another. (keyword is hardly)

**Comment by agentofzog2** [comment]
I bought a crate and didn't get the winter box I wanted. Revert this.

**Pull request merged**
