### PR TITLE
Box medbay relighting

### PR DESCRIPTION
**Pull request by ShiftyRail**
This PR doesn't even add that much light sources - the bulk of it is re-arranging the existing light sources so that they're less isolated, complement one another better.

I tried as much as possible to avoid having one source on top of a wall-mounted machinery like an air alarm. 

:cl:
- tweak: Box Medbay has a slightly different lighting.

### CODE REVIEW

**Comment by DeityLink** [comment]
By the way have you re-added that firelock?
image

**Comment by ShiftyRail** [comment]
No, I guess I can do it

**Comment by Kurfursten** [comment]
but will you?

**Comment by Kurfursten** [comment]
No need now

**Pull request closed without merging**
