### PR TITLE
removes (almost) all instances of "src."

### PR DESCRIPTION
**Pull request by Intigracy**
List of exceptions, I just reverted the changes to the files rather than fix the erroring lines:
http://hastebin.com/zapoweyuxa.tex

This is definitely going to cause conflicts if it gets merged.

If merged, no further instances of src. will be accepted unless it's neccessary (it does have uses)

If closed we don't give a shit about src. anymore

### CODE REVIEW

**Comment by clusterfack** [comment]
src.

**Comment by Intigracy** [comment]
Make a line comment :^)

**Comment by Shadowmech88** [comment]
How much does this reduce the repo's filesize by?

**Comment by 9600bauds** [comment]
this shit has gone too far

**Comment by Intigracy** [comment]
Before
3.14 GB (3,379,423,759 bytes)

After
3.14 GB (3,379,357,563 bytes)

66196 bytes difference
66.196 kilobytes
0.066196 megabyte

**Comment by clusterfack** [comment]
Well if were going to make @pjb3005 s suggestion a real standard, this is necessary. I wont support sniping about a pr 100 times anymore if this doesnt go through.

**Comment by Intigracy** [comment]
I just did this so we can be consistent, I don't care either way.

**Comment by 9600bauds** [comment]
We're wasting a non-trivial amount of time in a 100% trivial subject. This is worse than premature optimization, this is literally pointless.

**Comment by Exxion** [comment]
This is worse than pointless because we run the risk of breaking stuff in the event someone used a function-level variable and object-level variable with the same name for some reason and needed to  reference the object one in the function

**Comment by ComicIronic** [comment]
Yeah, you're going to break at least one case where src was actually necessary, so I don't support this.

**Comment by SysadminJeroen** [comment]
`+3,974 −3,975`
Why are you removing one more line than you're adding?

**Comment by ComicIronic** [comment]
ai_laws has a trailing empty line that was removed

**Comment by ComicIronic** [comment]
Woops

**Comment by Intigracy** [comment]
`src.` is a dumb meme we can kill it now

**Pull request closed without merging**
