### PR TITLE
Removes Box

### PR DESCRIPTION
**Pull request by PJB3005**
`<ririchiyo> do the same thing to box now PJB3005`
`¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by FudgePucker** [comment]
POSTING IN AN EBIN PR

**Comment by ScrambledSteak** [comment]
No weapons
Deff only
Final destination

**Comment by ultraplen** [comment]
we are approaching max meme too quickly

**Comment by jknpj** [comment]
Make sure to remove map voting so we can play meta/deff in turns!

**Comment by Exxion** [comment]
Remove all maps from rotation so that an admin must be on to force a map every round

**Comment by gbasood** [comment]
remove code
remove wiki
make a bunch of obscure undocumented mouseclick interactions with LMB, MMB and RMB
remove ghosts

don't you want to be like the cool kids

**Comment by optimumtact** [comment]
Good luck, warmest regards

**Comment by kol1th** [comment]
meme prs :eggplant:

**Comment by SangriaMonkey** [comment]
:alien:

**Comment by ghost** [comment]
Heart station only when? Do you have enough turbines King of Engines?

**Comment by gbasood** [comment]
archipelago station when

**Comment by ihadtoregisterforthis** [comment]
[Needs Changelog]

**Comment by PJB3005** [comment]
Wait do people REALLY want box to die?

w e w

**Comment by optimumtact** [comment]
How did you get the dark theme?

**Comment by ihadtoregisterforthis** [comment]
tgnowallowed

**Comment by PJB3005** [comment]
Wait what? I don't have that switch theme button.

I just use this userstyle: https://userstyles.org/styles/37035/github-dark

**Comment by ihadtoregisterforthis** [comment]
madeyoumire

**Comment by PJB3005** [comment]
I've been memed.

Goddamnit.

**Comment by Megamaw** [comment]
i can't believe it. we're removing more features. It's Skeletons all over again

**Pull request closed without merging**
