### PR TITLE
'Mimes' isn't a real verb #7723

### PR DESCRIPTION
**Pull request by Arthurdentist**
New action reads '[subject] mimics placing their hands against a flat surface whilst pushing against it'

### CODE REVIEW

**Comment by d3athrow** [comment]
Mimes is a real word as its a shortened version of pantomime

```
verb
3rd person present: mimes

    1.
    use gesture and movement without words in the acting of (a play or role).
        convey an impression of (an idea or feeling) by gesture and movement, without using words; mimic (an action or set of actions) in this way.
        "he stands up and mimes throwing a spear"
        synonyms:   act out, pantomime, gesture, simulate, represent
        "she mimed picking up a phone"
```

**Comment by Arthurdentist** [comment]
maybe if you are a pleb

**Comment by gbasood** [comment]
Mimes was fine, it was 'surfacing' that was fucked up.

**Comment by Kurfursten** [comment]
Moreover, use an actual gendered pronoun. We're not tumblr here.

**Comment by clusterfack** [comment]
Mimes is definitely a real word

**Comment by Exxion** [comment]
Mimes is definitely a real word
Also fixes #7723

**Comment by Arthurdentist** [comment]
what do you propose kurfursten, using 'he' in all instances or checking for the Mime's gender? The first is daft and the second is far too much effort. 

Using their is fine. Don't be scared of the SJW boogey(trans)woman.

**Comment by gbasood** [comment]
@Arthurdentist there's a text parsing helper made just for checking the gender
remove 'mimics' re-add 'mimes'

**Comment by Arthurdentist** [comment]
Controversial flag when.

I'll change it tomorrow when I wake up.

**Comment by d3athrow** [comment]
theres nothing controversial, the word exists and is valid verbage

**Comment by Arthurdentist** [comment]
it was a joke but whatever

**Comment by 9600bauds** [comment]
pomf pls

**Pull request closed without merging**
