### PR TITLE
Fixed sound in `playsound_local()` being played with `to_chat()`

### PR DESCRIPTION
**Pull request by ghost**
remove pjb + python

### CODE REVIEW

**Comment by ghost** [comment]
Wouldn't that have fucked with anything broadcast through << ? Technically a bunch of announcements use this for sound

**Comment by clusterfack** [comment]
No, its functionally identical right now, but if pjb ever finishes what he is working on it would have broken it

**Comment by PJB3005** [comment]
@clusterfack I actually have an `if(!istext(thing))` for that very reason, which just does a normal `<<`.

**Comment by ghost** [comment]
@PJB3005 Should've made it print a warning in that case, so you can find stuff like this.

**Pull request merged**
