### PR TITLE
Fixes #2702

### LINKED ISSUE #2702: Cyborg Jetpack breaks after refueling
I've seen this occur a few times, mommi or cyborgs that refill their jetpack do not regain the ability to jetpack move through space. Space will still be 'sticky' to them if they have jetpack stabilization on and they will have the jetpack move effect going over lattices but they can no longer spacemove.

### PR DESCRIPTION
**Pull request by clusterfack**
Jetpacks wouldn't regard trace gases as gases, therefore any jetpack using trace gases like N2O would break when there's really no reason for it to disallow trace gases at all.

### CODE REVIEW

**Comment by ComicIronic** [comment]
How is this related to #2702? That was about general refuelling, it doesn't mention N2O.

**Comment by clusterfack** [comment]
I must have refueled it with N2O, you said you tested it and that it doesn't happen under normal circumstances.

**Comment by clusterfack** [comment]
*cough*

**Comment by d3athrow** [comment]
changelog please.

**Pull request merged**
