### PR TITLE
Wizard hardsuit no longer slows you down and can no longer be contaminated by plasma

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
This is a powerful change, which I don't expect will be accepted, but it's still a sort of good change.
Also adds immunity to contamination. If this PR doesn't pass I'll make the contamination immunity a separate PR
:cl:
 * balance: The wizard hardsuit does not slow you down anymore.
 * balance: The wizard hardsuit is now immune to plasma contamination.

### CODE REVIEW

**Comment by DrSnips** [comment]
Slowdown removal:
The firebird is a common pick to go along with this and removes the slowdown issue already as well as giving the user other perks.
Plasma proof:
This is begging for abuse with push/bind and plasma+o2 miners to make huge fires. The no robes and atmos suit consumes more points and enables that as well so either a price increase(+10 points maybe?) is needed or removing this. I'm sure players overall would love more plasma flood and fires.

**Comment by boy2mantwicethefam** [comment]
Removal of slowdown is more of an experimental thing to get the hardsuit to be more useful by giving it an unique effect that most station hardsuits do not have, because the hardsuit is kind of mediocre by itself (not counting the two PRs I made that aim to give it some usefulness). Firebird is a very good point because I did not consider it when I made the PR, but vehicles are still 'hit or miss' because if someone gets close enough they can either dismount the wizard or take the keys from the car, but personally the main appeal of the firebird itself is that it's strong enough by virtue of being able to go through doors and tables barely impended and has freedom of movement in space.
Making the hardsuit unable to be contaminated with plasma is another addition that serves to give it some usefulness when it costs as much as a spell does. The hardsuit can be contaminated by plasma or plasma guns and it is debilitating. It's unlikely that a wizard is going to start to plasma flood especially when the hardsuit is not fireproof

**Comment by aceedex** [comment]
Hol' up
Giving it plasmaguard means the wizzman can just plasmaflood with impunity thats nuts man. If the suit and helm couldnt be contaminated themsleves thats cool but giving it plasmaguard is nutty.

**Comment by boy2mantwicethefam** [comment]
But they can't plasmaflood if their hardsuit isn't fireproof

**Comment by boy2mantwicethefam** [comment]
Anyway people don't like this so I'm gonna speedy-close it and get away with it

**Pull request closed without merging**
