### PR TITLE
it's just a balloon

### PR DESCRIPTION
**Pull request by Intigracy**
it's just a balloon

http://ss13.moe/forum/viewtopic.php?f=4&t=2218

### CODE REVIEW

**Comment by Intigracy** [comment]
by request of a dummy admin

**Comment by xpcybic** [comment]
what the heck's a syndicate :confused:

**Comment by gbasood** [comment]
:+1: i guess

**Comment by Exxion** [comment]
I feel like I'm missing something here

**Comment by Intigracy** [comment]
read the thread in my OP

**Comment by Exxion** [comment]
Apparently my mind has just started filtering forum links out of everything I read because half the time I don't have the access to read them

**Comment by clusterfack** [comment]
It is jus balloon, why you heff to be shitcurity

**Pull request merged**
