### PR TITLE
Redo #12064, radiation collector log curve.

### PR DESCRIPTION
**Pull request by PJB3005**
See #12064 for details.

### CODE REVIEW

**Comment by carshalash** [comment]
Where did the engineer touch you yesterday pjb?

**Comment by PJB3005** [comment]
Do I need more reason to ignore ALL feedback on this github related to balancing engineering? Because this PR is a whole ton of it.

This ENTIRE PR is dropping the numbers of you "autists" in the name of balance but you can't accept it.

Jesus fuck I'm tempted to self merge it so hard.

**Comment by LordMyroc** [comment]
What is there to balance by lowering numbers? As long as you have sufficient power it doesn't matter if you have 3 megawatts or 3 million megawatts, so why are you going to such great lengths to nerf engineering related stuff into the ground? What is the problem of having such high numbers when those numbers are meaningless to begin with?

**Comment by PJB3005** [comment]
@LordMyroc so we can make engineering meaningfull in some far future.

**Comment by LordMyroc** [comment]
So why not begin by giving it meaning and creating uses for excess power? You're putting the cart before the horse.

**Comment by BobdaBiscuit** [comment]
Don't you think these prs might be accepted more if this meaningfull-ness was included in them? Instead of gimping autism for something that will never arrive, or will in like 2 years time.

**Comment by PJB3005** [comment]
@LordMyroc then I'll nerf the usage of engineering and everybody will complain that I'm nerfing something important.

**Comment by d3athrow** [comment]
rad collectors were already nerfed years ago by dylan, no need to nerf them even more.

**Comment by ghost** [comment]
Why not a coefficient of consumption?

The more radiation it has to absorb, the more plasma that's consumed from the tank

**Comment by gbasood** [comment]
I like that idea more
My original PR was a bad approach, didn't reward/punish what I wanted it to

**Comment by PJB3005** [comment]
@Skullyton that's bad. Then going too hard on the collectors makes you burn through plasma too quickly.

**Comment by gbasood** [comment]
...So?

**Pull request closed without merging**
