### PR TITLE
Fix ushanka "shaving" your head.

### PR DESCRIPTION
**Pull request by ghost**
[bugfix]
This was caused by setting the ``flags`` to ``HIDEHAIRCOMPLETELY`` in tandem with setting ``body_parts_covered`` to HEAD. For some reason those two don't play well together. I couldn't find where they interact and cause the bug. The ushanka should be the only one that did this. (I mass searched for any references to ``HIDEHAIRCOMPLETELY``. 
**This system should be looked at by someone who knows what they're doing.**
:cl:
 * bugfix: Ushanka no longer shaves your head with Russian space magic.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
I thought it did this intentionally

**Comment by ghost** [comment]
Danke comrade, hopefully the issue I opened was closed

**Comment by Probe1** [comment]
@dylanstrategie check for me would you please

**Comment by ghost** [comment]
All good

**Pull request merged**
