### PR TITLE
Moves around some items in paramedic closets and adds paramedic magboots sprite.

### PR DESCRIPTION
**Pull request by DrSnips**
Looking over the contents of the paramedic locker I noticed that it had a lot of extra items in it so I removed some of them like 4 pairs of gloves down to two. This makes it so there's exactly two full sets of paramedic outfits rather than two full sets and two half sets. The EVA locker has a webbing in it now so it's consistent in all maps. I also <s>moved the internal bleeding aid kit to the general locker, and</s> added one more kit so there is truly two paramedic sets. (each kit has 4 injectors only rather than a full 7 per kit)
In list form:
Paramedic general locker
-2 paramedic softcaps
-2 latex gloves
-2 paramedic vests
-2 emergency oxygen tanks
<s>+2 internal bleeding first aid kits</s>
Paramedic EVA locker
-1 magboots
+1 paramedic magboots
fm
+1 internal bleeding first aid kits
+1 paramedic webbing
:cl:
* tweak: Paramedic locker contents have been shuffled a bit.
* rscadd: Paramedic EVA locker now has two internalbleeding kits. (8 total bio foam injectors)
* rscdel: Removed some of the extra paramedic gear leaving two complete sets of outfits.
* rscadd: Paramedic webbing added to the EVA locker.
* imageadd: The magboots in the paramedic EVA locker now have paramedic colors.

### CODE REVIEW

**Comment by aceedex** [comment]
my issue with this one is shitters breaking paramedic windows just for those foam injectors. a lot easier to smash and grab than to run out with a locker. otherwise good stuff

**Comment by DrSnips** [comment]
I have a little more faith in our server than that. It might happen frequently for a short while after the change but after that it will likely settle down.

**Comment by Pathid** [comment]
Biofoam injectors are unique and irreplaceable. Why move them out of the secure locker? What's your reasoning here?

**Comment by ghost** [comment]
the red cross kind of looks like crap on the magboots, removing it would be better

**Comment by DrSnips** [comment]
I doubled the count of them to 8 so it's not as scarce and they are able to be scanned by mechanics. As I said before I have a bit more faith in our server to not steal them every singe round. The red cross is the active/inactive indicator for the magboots fyi.

**Comment by ghost** [comment]
wow those magboots are ugly

**Comment by DrSnips** [comment]
If you throw a sprite here I can swap it. I put 0 effort into it but yeah it's pretty ugly. I will work on it a bit more when I get the chance.

**Comment by ShiftyRail** [comment]
>-2 paramedic softcaps
-2 latex gloves
-2 paramedic vests

For what purpose, if I may ask ?
The Sprite itself doesn't look that bad, but it would be more interesting to see how it performs in-game, (without a paramedic EVA gear which hides them).

**Comment by DrSnips** [comment]
Sprite in the op has been updated.
Old
fm
New
fm
Color palette matches the paramedic EVA in the new.

**Comment by DrSnips** [comment]
Stat wise they are just normal magboots. As for removing the clothes I was just cutting out some of the clutter while I was changing the paramedic lockers.

**Comment by Pathid** [comment]
> they are able to be scanned by mechanics

I'm pretty sure they can't be. I've tried this before and they have no origin tech.

**Comment by DrSnips** [comment]
I guess Ive been lied to this whole time. I will fix that but not in this PR.

**Comment by DrSnips** [comment]
Would people like the bleeding kits back in the access locked paramedic locker? I'm thinking about moving them back.

**Comment by Blithering** [comment]
If the secure locker is only gonna have the EVA gear inside it might be worth replacing it with a SSU

**Comment by DrSnips** [comment]
OP  updated with recent changes.

**Pull request merged**
