### PR TITLE
Makes brute/burn damage to limbs without organs not count towards total health for crit/death purposes

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[tweak]

## What this does
see title, overall brute and burn loss procs also have the damage taken overall adjusted to be multiplied to the total number of external organs divided by those with organs to compensate and make them function similar to how they used to, same in the healing process.
getbruteloss() and getfireloss() default to ignoring organs without internal ones, except for some healing chems and medbots, which heal organs with interal ones with priority; and also pain/shock calculations.
probably nerfs shocks from things wired to the grid at huge power if that matters (but at >200 damage or so it probably doesn't matter anyways due to the effect of damage still bleeding into other limbs)

## Why it's good
a bit more realistic, stops the weird thing where you need to remove someones limbs to revive them without cloning.

## Changelog
:cl:
 * rscadd: Damage taken to limbs without internal organs no longer contributes to a loss of overall health.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
Actually soulless

**Comment by gurfan** [comment]
>[tweak]

lol

**Comment by gurfan** [comment]
If I understand this PR right, it's making limb damage essentially do.... nothing? I get what the point of it is but you will have to rework lots of other things(like electrical shocks ) for such a change to make sense.

**Comment by SECBATON-GRIFFON** [comment]
> If I understand this PR right, it's making limb damage essentially do.... nothing? I get what the point of it is but you will have to rework lots of other things(like electrical shocks ) for such a change to make sense.

just made sure it causes pain in the last commit, bleeding and bone breaking are still things too, but yeah good idea if this  doesn't do anything like slow down walking or make you drop items by itself.

**Comment by pedr69** [comment]
so what you're saying is that if i laser someone in the kneecap 4 times he'll just walk it off(and get some pain damage after a minute) instead of going into crit and fukken dying?

**Comment by SECBATON-GRIFFON** [comment]
> so what you're saying is that if i laser someone in the kneecap 4 times he'll just walk it off(and get some pain damage after a minute) instead of going into crit and fukken dying?

walk it off ideally not, but it takes more burn damage shots to reach crit by just firing there now (brute ones would still cause it by heavy blood loss)

**Comment by DorainGrey** [comment]
I think the defib thing makes sense, it is weird not being able to revive someone because their hand has 200 burn damage. 
The rest of the changes don't make much sense.

**Comment by SECBATON-GRIFFON** [comment]
> I think the defib thing makes sense, it is weird not being able to revive someone because their hand has 200 burn damage. The rest of the changes don't make much sense.

i mean if it did send them into crit but could still defib they'd just die instantly on revival anyways

**Comment by twirling-jesters** [comment]
I understand the sentiment here, but even within real life, very traumatic limb damage can have systemic effects on the body that can lead to someone entering critical condition (even when we don't factor in hypovolemic blood loss.) Circulatory shock as a result of SIRS, for instance, can occur just from severe burns. The body as a system isn't modular, and unfortunately, damage to even our extremities can throw our vital signs into disarray. It's going to have to be a thumbs down for me.

**Comment by githubuser4141** [comment]
> I understand the sentiment here, but even within real life, very traumatic limb damage can have systemic effects on the body that can lead to someone entering critical condition (even when we don't factor in hypovolemic blood loss.) Circulatory shock as a result of SIRS, for instance, can occur just from severe burns. The body as a system isn't modular, and unfortunately, damage to even our extremities can throw our vital signs into disarray. It's going to have to be a thumbs down for me.

I think it'd be better to rework the medical system to actually work like this, instead of stubbing your toe x25 times and being beaten with a fireaxe x5 times leading to the exact same cause of death/critical state. It's not incredibly realistic to be totally fine at 99 damage, go into crit at 100 damage, then be healed out of critical state by someone applying 1 band-aid to your toe.

Or RNG / actual wound types/injuries should come into play, and going into crit/dying _should have a defined cause, like you're saying it does IRL._ Because currently crit status doesn't require any reason, other then "you have over 99 damage of any type on any location", and because there's no difference between scratching yourself (5 damage) and a bullet (12 damage). Lasering someone's kneecap should lead the the same issues it'd have IRL with an element of RNG added. 

Otherwise it's a bit silly to point to RL injuries when.. um, you can heal any 'severe trauma' in VG's by applying a fricking bandaid. Surely it's less believable for a astronaut who's in excellent shape in the 25th century (so probably doesn't have any underlying health issues) to go into cardiac arrest from, say, rubbing his hand on poison ivy five times, then be resusciated by putting burn cream on his hand and doing CPR (then he's somehow 100% fine no biggie lol) then it is to have a more forgiving limb damage system that doesn't **guarantee** death from mangling one's hand up, I mean, people in industrial settings get mangled hands/fingers sure you COULD die, but I think death at the scene if you're not bleeding isn't too common at least it's not *100% chance to go into cardiac arrest* like it is here.

At the end of the day you can stitch up someone's hand instantly, on the spot, which of course causes the actual damage to 'go away' and gets them out of crit so VG's medical isn't realistic to begin with.

IMHO we should port Nebula/Baystation's system, then tweak the values from there - or, there's offshoots like Lifeweb/Civ13 where they've tweaked damage to be even less forgiving. We could add tier 4, 5, 6+ injuries that are only caused by certain amounts of damage (a 60 dam bullet should be inherently more dangerous then a 6 damage nerf dart x10) or whatevs.

**Comment by pedr69** [comment]
>a 60 dam bullet should be inherently more dangerous then a 6 damage nerf dart x10

it is, >15 damage brute hits can cause IB, and cause it more often the more damage they do
>then be resusciated by putting burn cream on his hand and doing CPR

severe burns(>50 i think) dont heal when treated, you need chems
i agree that being fine at 99 damage, then horizontal and unconscious and dead at 100 sorta sucks
maybe a soft crit where you're forced horizontal but still conscious? pain sort of does this but very badly

**Comment by PrimeDSS13** [comment]
do you remember
I remember
#24133 #24261

**Comment by githubuser4141** [comment]
> > a 60 dam bullet should be inherently more dangerous then a 6 damage nerf dart x10
> 
> it is, >15 damage brute hits can cause IB, and cause it more often the more damage they do
> 
> > then be resusciated by putting burn cream on his hand and doing CPR
> 
> severe burns(>50 i think) dont heal when treated, you need chems i agree that being fine at 99 damage, then horizontal and unconscious and dead at 100 sorta sucks maybe a soft crit where you're forced horizontal but still conscious? pain sort of does this but very badly

TG has soft crit and it's the same thing as hard crit only 100x more frustrating as you can crawl, whisper but can't use your hands or talk. It's confusing for newbies as they'd probably try to crawl somewhere safe to heal (because they think they'd heal naturally lol) only for time to pass...... and..... absolutely nothing to happen. I'm not kidding if you're at 100 damage on /TG/ (or 120 damage) it actually takes several IRL minutes for you to go into hard crit, that's 7 minutes of crawling around as a mute hard stunned idiot expecting to die or be healed instead you're in 'crit limbo' where you're conscious, can crawl across the map several times, can whispher but can't do anything else, it's a lot worse then hard crit which at least makes thematic sense.

Goonstation or Paradise do 'VG crit' best - it's soft-crit (but coded as a disease with stages, you can talk, slowly walk, use items, but you're stunned every few seconds and you generally go into hardcrit after a minute even at 100 damage.) It's bullet spongey as hell, however.

**Comment by SECBATON-GRIFFON** [comment]
> do you remember I remember #24133 #24261

pepperidge farm remembers

**Comment by pedr69** [comment]
what if, instead of the current 100%, or this(and the older limbdamage) PR's 0%, limbs instead counted some portion of the damage towards the overall health
say 75% on arms/legs, and 50% on hands/feet
so if you laser someone in the hand 4 times, he'd have
40 burns on the hand - contributing 20 damage to overall 
75 burns on the arm - contributing 56 damage to overall
5 burns on the torso - contributing 5 damage to overall

120 total burn damage but 81 "overall" damage, so not quite in crit

**Pull request closed without merging**
