### PR TITLE
Cult 2020 Rework #2: Soul Stone cleanup and tweaks

### PR DESCRIPTION
**Pull request by DeityLink**
So this was originally just one fifth of the planned part #2 of the cult revamp but this alone took me the entire day so I'd rather keep things as easy to review and atomic as possible.

Most of this PR is a refactor of how soul stoning works from a code standpoint, with a new datum used by both soul stones, gems and blades doing the heavy lifting, instead of having a bunch of /obj/item level procs.

The soulstone.dm file itself has been moved from `code\datums\gamemode\factions\legacy_cult` to the more sensible `code\game\objects\items` and the item's type path has been changed from `/obj/items/device/soulstone` to just `/obj/items/soulstone`, the /device type adding absolutely nothing to the item.

There are a few gameplay changes still:

:cl:
* rscadd: Soulstoning someone with a soul gem instead of a soul stone shard will spawn a coffer containing their belongings, their skull, and a glass of their blood like failed conversions currently do (but not for long, conversion overhaul coming very soon)
* rscadd: Committing suicide while holding a soul stone, soul gem, or soul blade that don't already contain a shade will let you capture yourself. Most useful when done with a soul blade obviously. Using a soul blade this way will set its blood count to 50 if it was any lower.
* tweak: Pale Bodies now drop all their items upon death instead of them being destroyed when they dust.
* tweak: Shades have had their HP raised back to their original value, from 40 to 50 (It was lowered in 2018 on the day after Cult 3.0 released because apparently people thought they were too strong somehow?)
* tweak: Shades and Constructs can now understand galactic common, and speak it with :1. This includes chaos blades. Non-cult constructs on the other hand can speak in cult chants if they so desire using :5.
* tweak: Edited the name and description of a few Artificer spells for consistency and clarity.
* bugfix: Fixed various cult and antag items being freely scannable by mechanics.
* bugfix: Fixed a few instances where soul stones or blade could capture a sacrifice target (not counting using an empty soul blade for the sacrifice)
* bugfix: Potentially fixed remaining instances of shades in soul blades not properly getting their UI

### CODE REVIEW

**Comment by Irradiation** [comment]
I, for one, welcome our glorious Soul Sword overlords.

**Comment by DeityLink** [comment]
I doubt this would make them popular overnight. They're even more of a glass canon than Wraiths are. However I'm considering to buff their blood regen, maybe have them benefit from the cultist regen just from standing close to one instead of being held.

**Comment by tuypo1** [comment]
Or at least a lesser version of the regen from standing close yeah.
also they should probably just be able to move freely during the feast

**Comment by SonixApache** [comment]
I lament the fact that Chaos Blades are now generic talking swords, but it is probably for the best.

**Comment by DeityLink** [comment]
As opposed to being a talking sword that cannot even be understood? I really don't see what's there to lament about. It's incredibly frustrating for both the player in the blade and the one who activated it.

Were chaos blade meant as a joke?

**Comment by SonixApache** [comment]
I always thought the intention was that the wielder could understand the sword and vice versa.

**Comment by coronasaurus** [comment]
consenting to be converted when?

**Comment by DeityLink** [comment]
@coronasaurus since 2 years ago 🤔 

@soniixapache no such feature. Chaos Blades have 
		S.universal_speak = TRUE
		S.universal_understand = TRUE
which means that they understand their wielder but they still speak in cult-tongue by default. At least now they get a message explaining that they can use :1 to speak in galactic commons.

**Comment by DeityLink** [comment]
Ready for review.

**Comment by SonixApache** [comment]
Wonder what kind of mandela effect planted that idea in my head. Also interesting how you managed to ping my alt.
Either way, good PR.

**Pull request merged**
