### PR TITLE
Mothership grey clothing now melts from water (canon)

### PR DESCRIPTION
**Pull request by adacovsk**
@Optimism333 wanted to make some stuff be immune to acid, but melt in water, just like the greys themselves

## What this does
- Changes the `acidable` procs to `dissolvable` and returns either `PACID` or `WATER` rather than just true or false.
- fixes some semi-related alien shitcode `acidify`

## Why it's good
- Requested feature
- Better RP for greys exposed to water?
- Funny

## Changelog

:cl:
 * rscadd: Grey clothing, while highly resistant to acid, has some drawbacks. It now melts in water!

### CODE REVIEW

**Comment by Eneocho** [comment]
While I get the idea it's kind of a huge fucking leap. Synthetic clothing material (plastics, metal, etc) does not melt with water. If nothing else the ayy clothing should only be acidproof, not weak to water.

**Comment by adacovsk** [comment]
it's a very specific subset of clothing, primarily used to counter greys on the mothership... They don't have water on their home planet okay

**Comment by Eneocho** [comment]
Even then it rustles my fucking jimmies real hard. There's no reason beyond feature(TM) to have that. It's neat I'll admit, but it feels really weird.

**Comment by adacovsk** [comment]
yes, I would be quite upset if I didn't have water too

**Comment by WindowsErrors** [comment]
> While I get the idea it's kind of a huge fucking leap. Synthetic clothing material (plastics, metal, etc) does not melt with water. If nothing else the ayy clothing should only be acidproof, not weak to water.

if xenonauts taught me anything, it's not the water vapor-based nerve gas that kills the alien, it's the fluoride inside of it that does the job

**Comment by Eneocho** [comment]
Guess that works as DEEP LORE(TM).

**Comment by Optimism333** [comment]
> Guess that works as DEEP LORE(TM).

Much like humans shower fully clothed in water, ayys will now be able to shower fully clothed under acid. That's a win in my book.

**Comment by Optimism333** [comment]
> While I get the idea it's kind of a huge fucking leap. Synthetic clothing material (plastics, metal, etc) does not melt with water. If nothing else the ayy clothing should only be acidproof, not weak to water.

I usually like to give and take with these kinds of things, so as not to creep ayys into being OP. There are a couple clothing items that are immune to water and acid both, though not very many. High-end items like the MDF Heavy Armor, and the ayy Leader Rigsuit and uniform.

Having clothing/armor that is immune to acid is pretty strong imo, even with the vulnerability to water.

But I'm open to hearing what others think about the idea.

**Comment by Eneocho** [comment]
My complaints are mostly immulshons based, don't worry. It is a good feature, but it feels incredibly awkward to me for them to somehow have plastic that melts under water. 
That is, if they don't have their own plants that DO in fact suffer from water (this is a subtle hint at adding ayy plants, including some weird ayy-cotton plants that make fruit that melts with water).

**Pull request merged**
