### PR TITLE
A PR to remove the Snow Taxi map from the rotation except for certain months

### PR DESCRIPTION
**Pull request by ShiftyRail**
Said months being January and December. Let's be honest, 4°C is way too hot for New York City and we have Snaxi as early as October sometimes, and it can get stick around as late as April. Let's stop this madness once and for all. The days are getting longer, the sun is shining, birds start to sing and the first trees blossom by April. We do not need an arctic station map this late in the year and it is madness it is able to stay in rotation this long.

:cl:
- tweak: Snow Taxi is now only available during the months of December, January, February, and July.

### CODE REVIEW

**Comment by mrflarg** [comment]
Would rather play it in the summer tbh.

**Comment by PavelCIA** [comment]
best PR 2021

**Comment by bathosbathtime** [comment]
Only having it in both the dead of winter and height of summer would be interesting.
Let the australians and brazilians feel included in having winter snaxi, too, even if only as a side effect.

**Comment by ghost** [comment]
If it's supposed to be a winter map then it should be December, January and February. Spring doesn't official start until mid March but usually by the end of February (although climate shifts are making this later and later every year) the weather is at a point where nobody would really consider it Winter any more and the flowers are starting to bloom and the blossom is forming on the trees.

I'd be for month restricting it to December, January and February, as these are the months most likely for world-wide snow

**Comment by Dacendeth** [comment]
As much as I dont like this map I feel February should be included as well.
image

**Comment by PavelCIA** [comment]
add a santa claus minor role for snaxi then you have an excuse to restrict it to the 24 & 25th december only

**Comment by ShiftyRail** [comment]
Following amendments the following months have been added to the list : February and July (for Austr*lian winter).

**Comment by d3athrow** [comment]
remove the temperature check then.

**Comment by ShiftyRail** [comment]
Will do.

**Comment by TGFH** [comment]
Keep the temperature check and speedmerge it.

**Comment by Eneocho** [comment]
Keep the cold temperature check for December, January, February. Put a very hot temperature check on July so summer heat on New York equals cold in the southern hemisphere. Or alternatively, put a second cold temperature check on a southern hemisphere city.

**Comment by ghost** [comment]
Speed merge it.

**Pull request merged**
