### PR TITLE
Advanced Health Scanner HUD

### PR DESCRIPTION
**Pull request by djkramer123**
The CMO's locker now spawns with a pair of Advanced MedHUDs. They function as regular health scanner huds and science goggles with the addition of having flash protection, meaning they'll no longer be the only head without it roundstart. Only one pair spawns in the locker and they can't be scanned by the regular mechanic's scanner.

81fa45628ec27f686afcae2968a280aa

96e6b189f35bbff1c73ba6b1b7a4e094

Thanks to @Optimism333 and @robintime being awesome and patient with me the HUDs now also function as science goggles, without the purple overlay. 

d39ea11316d0e21d8d220de84878a5f5

:cl:
 - rscadd: The CMO's locker now spawns with a pair of Advanced MedHUDs which function as both MedHUDS and Science Goggles with added eye protection, making them no longer the only head without it roundstart.

### CODE REVIEW

**Comment by Dacendeth** [comment]
You look like a dweeb.

**Comment by Optimism333** [comment]
Haha, nerd HUD

(I can help you add the science goggles function later if you need some help with that)

**Comment by djkramer123** [comment]
> You look like a dweeb.

fucked up


> Haha, nerd HUD
> 
> (I can help you add the science goggles function later if you need some help with that)

also fucked up
(yes please thank you)

**Comment by Eneocho** [comment]
Can the glasses be scanned by hacked device analysers (the syndie one)?

**Comment by djkramer123** [comment]
> Can the glasses be scanned by hacked device analysers (the syndie one)?

Not currently no, though after talking to a few people I feel like it should be able too. It seems too snowflakey for them to not be. I'll make that change when I finish autistically changing pixel by pixel on the sprite.

**Comment by SonixApache** [comment]
make the nightmare vision a toggle

**Comment by djkramer123** [comment]
> make the nightmare vision a toggle

it is

**Comment by ManopolisJones** [comment]
Hope you can rip those dumb stupid glasses off the CMO's face and step on them like any other pair.

**Comment by adacovsk** [comment]
I prefer the look of the regular health scanner HUD, but maybe dark blue instead of light blue

**Comment by djkramer123** [comment]
> I prefer the look of the regular health scanner HUD, but maybe dark blue instead of light blue

While I somewhat agree, It wouldn't make much sense that something that only covers one eye would protect you from flashes. The sechuds that only cover one eye for instance don't offer eye protection.

**Comment by Eneocho** [comment]
Make it a two eye medhud, lorewiseTM you use the expanded screen as the secondary where the nightmare vision mode is.

**Comment by djkramer123** [comment]
> Make it a two eye medhud, lorewiseTM you use the expanded screen as the secondary where the nightmare vision mode is.

I wanted to do something like that originally, however my artistic ability ends at recoloring other sprites, I might mess with the it more in the coming day or two but I wouldn't count on anything.

**Comment by Theophrastus1** [comment]
Why do they get flash protection? Neither of the "components" have flash protection.

**Comment by Eneocho** [comment]
Because all other heads get flash protection eyewear, it's consistent with the rest of the heads, if somewhat powercreepy.

**Comment by Theophrastus1** [comment]
> Because all other heads get flash protection eyewear, it's consistent with the rest of the heads, if somewhat powercreepy.
I get that, but i still feel its pretty powercreep

**Comment by Eneocho** [comment]
It is powercreep, but it adds consistency to the heads of staff, since CMOs were the only head without flash protection eyewear and most people don't even consider CMO a Head of Staff, due to them being far removed from the command chain and its expectations, CMO is a captain only when there's no other head and the nature of the beast (WILD RIDE) means they rarely get to be command staff, rather being a doctor with cooler toys.

**Comment by ghost** [comment]
be sure to add this to the possible traitor steal objective items if anyone still cares about updating them like me

**Pull request merged**
