### PR TITLE
[Sprites] new admin lasergun sprite

### PR DESCRIPTION
**Pull request by DeityLink**
old sprite: 
oldadmin

new sprite:
newadmin

Now hopefully it looks actually golden and not deep fried.

### CODE REVIEW

**Comment by Probe1** [comment]
github really needs a `¯\_(ツ)_/¯` reaction

**Comment by Shadowmech88** [comment]
> not wanting a deep-fried laser gun

**Comment by DeityLink** [comment]
Fun fact: Over a year ago I remember people saying that deep frying laser guns made them infinite, and at the time I had no idea how that was possible. It occurred to me today that they must had gotten admin laserguns from an adminbus, and thought those were actually deep fried laserguns. Or even better, an admin renamed a lasergun to "deepfried laser gun".

Either way if for the sake of bus you really need a deep fry-colored laser gun, just take a regular lasergun and set its color var to "#FFAD33"

**Comment by Probe1** [comment]
well now I want deep fried laser guns.

**Pull request merged**
