### PR TITLE
Allows plasmamen to be HoS, HoP and captain again.

### PR DESCRIPTION
**Pull request by Blithering**
Adds plasmamen to the whitelist for the restricted heads of staff roles, as they are canonically humans who were caught in a plasma incident, and it makes sense some of them held rank prior to their change. 

Endorsed by not one, but two collaborators! 
debate

:cl: 
 * rscadd: Plasmamen can be captains, HoPs and HoSess-s-s-s again.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I don't have any opinion on this or anything meaningful to add, I just wanted to get in before 100 replies

**Comment by kernikov** [comment]
AI, doorcrush the captain to death.

**Comment by ghost** [comment]
*round start uploads nt default*

**Comment by kernikov** [comment]
From the captain's quarters to the AI upload, there are 6 airlocks on box.
Do ya feel lucky, punk?

**Comment by SonixApache** [comment]
If you're so shit at AI that you can't bolt your upload at roundstart BEFORE someone walks in, I don't know what to tell you.

**Comment by kernikov** [comment]
>bolt your upload at roundstart

That's metagaming, it's code green and there are no threats.

**Comment by SonixApache** [comment]
plasmemes wanting to touch your laws are threat enough

**Comment by mtpowell** [comment]
Sounds like fun to me

**Comment by DamianX** [comment]
AI IS NOT OBEYING THE CAPTAIN BLOW THE BORGS
this sounds stupid to me as long as asimov keeps being the default

**Comment by Durgen** [comment]
deepest lore

**Comment by TheFriggenSawbones** [comment]
is this a fucking april fools joke pleasePLEASE DONT BE

**Comment by kol1th** [comment]
Good april fools pr. 👍

**Review by Probe1 — APPROVED** [review]

**Comment by Riekland** [comment]
Probe FUCK OFF
ps we need to remove all non-humans from all head roles

**Comment by Probe1** [comment]
Plasmamen are trans-human mutants and continually have been employees of NanoTrasen.

Also check that rudeness at the door mister.

**Comment by Shadowmech88** [comment]
It seems unwise for NT to allow applicants that the silicons do not have to obey for high command positions.

They may have previously been humans, but that doesn't mean they are currently fit for the positions.
A piano player who loses his hands shouldn't be allowed to keep his job just because he used to perform it well.

**Comment by SonixApache** [comment]
they're 
PURPLE
SKELETONS

**Comment by AutismSpider** [comment]
>Wizard teleports to station
>AI turns on the Captain, HoS and HoP because they're plasmaman shits and are trying to kill the wizard

There's a reason it's human only, it makes the AI at least not murder them or some smart ass clown law twos the ai to make a purple pan cake.

**Comment by kernikov** [comment]
I believe bay has a solution to this problem, clearly NT Default needs to be the default lawset instead of ASSMOV.

**Comment by ghost** [comment]
The problem only exists if this PR is merged, we shouldn't change the default lawset just so the 5 people that play plasmamen can play implanted head roles.

If we are going to change the default lawset just for them, why not allow all races to be implanted heads?

**Comment by yclatious** [comment]
I know we agreed to only plasmemes, and while I am a man of my word, I also remember that the deal included a permanent captainban from sawbones blithering.

**Comment by ghost** [comment]
i say no solely to prevent sawbones from feeling happiness

**Review by PJB3005 — APPROVED** [review]

**Comment by ihadtoregisterforthis** [comment]
But sawbones banned from captain is part of the deal

**Comment by clusterfack** [comment]
Just as God (me) intended

**Comment by Intigracy** [comment]
NT Default is shit

**Comment by SonixApache** [comment]
fucking why
why crack the ack but allow the purple memes

**Comment by Kammerjunk** [comment]
Skelememes were humans once too tbh

**Comment by yclatious** [comment]
I still dont see a sawbones perma captain ban. Honour the deal dammit

**Comment by Probe1** [comment]
Because Plasmaman are non-shit skeletons.

**Comment by SonixApache** [comment]
i wholefully disagree

why would a purple skeleton welded into a hazmat suit be appropriate for *any* kind of position of authority

**Comment by Probe1** [comment]
Because people said so.  

For the same reason we have ballistic weapons on a space station.  And space wizards. 



 It makes enough sense that it can be demonstrated logically and I have only so many shits I can give.

**Comment by SonixApache** [comment]
what

**Comment by JustSumBody** [comment]
Space wizards should NEVER be used as an argument in favor of something because, as several others have said before "they're the exception, not the rule." Not everything should be zany just because "we have wizards that can blow people's asses off so why not"

In a similar vein as saying, PURELY HYPOTHETICALLY OF COURSE "we have undertale references so why not ____ reference?" or on the opposite end of that, throwing a stink over a certain MEDICAL GUN of some description being functionally similar to another video game gun

Just going *purely hypothetically* of course

**Comment by Probe1** [comment]
April fools is over  buddy.

**Comment by Blithering** [comment]
But I wasn't fooling, just never got around to making a PR

**Comment by Megamaw** [comment]
wait did they revert this

**Comment by Exxion** [comment]
Yes
To be honest, it probably wasn't a great idea to open a real PR on April Fools'

**Comment by Blithering** [comment]
Reverting was the right thing to do, considering it was merged within a day of being opened for jokes, I'll open a new PR for proper consideration.

**Pull request merged**
