### PR TITLE
removes crawling

### LINKED ISSUE #16723: Revert Crawling
Completely negates slips and traps of any kind without any equipment, and as a Clown I cannot abide by this gross affront to both nature and Honkmother.

### LINKED ISSUE #16925: Something Needs To Change: Box Perma or Crawling
Found this in the thread. Tagging @hugh-g-rection and @MadmanMartian for obvious reasons.

Now I personally don't have a dog in the fight of which one we change but this isn't acceptable.

### PR DESCRIPTION
**Pull request by MadmanMartian**
Seems that the people who liked crawling have disappeared, and now it is universally hated.

Removing by popular demand.

closes #16925 closes #16723 

:cl:
* rscdel: Crawling removed.

### CODE REVIEW

**Comment by TurboGay** [comment]
I don't think crawling should be removed merely over an easier way to escape box permanent confinement among a few other things. I'm very much against features being removed or nerfed into the ground because of minor balance issues because nobody wants to fix the problems the features may have or because it affected them negatively in a round.

Instead maybe you shouldn't be able to crawl unless there's a floor tile under you to prevent the situation from happening as you'd need metal sheets in order to pull that escape off and potentially succumb to hypothermia in the process. I don't believe crawling is universally hated in our server, more so that a majority of the playerbase doesn't even view the github to chime in with their input and even fewer know these issues are being discussed in the first place.

**Comment by ShiftyRail** [comment]
Reverting might not be necessary. Don't listen to the memers.

Just make it a "do_after" with one-two second delay. Gonna put some effort into your crawling.
Adjust that with number of limbs.

**Comment by SonixApache** [comment]
Being able to actually do anything once you lose a leg is a godsend.
It's only natural that a feature changing movement in such a drastic way would run into some issues with our finely crafted maps.

**Comment by ultraplen** [comment]
It's a cool immulsion feature, and I'd rather see it improved upon than removed.

**Comment by SysadminJeroen** [comment]
There was enough time to nerf crawling.

If no one is going to take the heat of nerfing a massively overpowered feature I'd say just remove it until it can be properly brought back.

**Comment by MadmanMartian** [comment]
I have been trying to nerf and fix it as best as I can with the feedback I have been given, but nobody is giving feedback.

**Comment by Sooose** [comment]
The only problem I see is that crawling makes it really easy to just rest and crawl around someone with a gun, pushing them over and taking their gun. Being able to survive a perma escape on one map in particular hardly seems like a good reason to remove crawling.

**Pull request closed without merging**
