### PR TITLE
Medic Armors

### PR DESCRIPTION
**Pull request by Apogee-dev**
Adds a medic armor vest which can be made by using a green crayon on a sec vest and a Trauma Team hardsuit, intended to be used for adminbus or vault loot. The Trauma Team hardsuit is an armored hardsuit that has better radiation shielding than the sec hardsuit, but gives up the sec suit's additional melee armor and a small amount of laser, energy, and bomb armor. The Trauma Team hardsuit can also store both security items and medical items in its suit storage slot (but, notably, not bolas or cuffs).

paramed_armor mockups

:cl:
 * rscadd: Medic armor vest, made by using a green crayon on a sec vest. Use bleach to return to original skin.
 * rscadd: Trauma Team hardsuit, currently only available by bus

### CODE REVIEW

**Comment by BomberBro** [comment]
Can armor currently be washed to make it go back to normal?

**Comment by west3436** [comment]
Why don't we just give this to the one in a hundred players who choose to be medical ERT?

**Comment by Apogee-dev** [comment]
> Can armor currently be washed to make it go back to normal?

I considered that, but since armor gets covered in blood on a near-constant basis anyone who wants to legitimately use it as an armor skin would end up re-applying it constantly after washing off (compare with the clowned armor, which is mostly just meant as a prank to annoy secoffs with a pink eyesore and is fairly easy to fix as a result). I'll have to think of another way to restore a medic vest to its original skin if a permanent conversion proves to be unpopular.

> Why don't we just give this to the one in a hundred players who choose to be medical ERT?

We already have a medical ERT suit, and more importantly the trauma team suit looks almost nothing like the ERT suits, so it would stand out in a pretty bad way.

**Comment by Blithering** [comment]
Castle station paramedics could use the suit, since they pretty much fit the heavily armed rescue team who will put a bullet in you then charge you for revival theme. The vest being green is a bit strange, as it doesn't fit either the sec or paramedic colour scheme, and the trauma team suit which it does match isn't gonna be part of their kit.

**Comment by Apogee-dev** [comment]
> Castle station paramedics could use the suit, since they pretty much fit the heavily armed rescue team who will put a bullet in you then charge you for revival theme.

I'll leave the mapping to the mappers, or at least I don't plan on wrapping any map changes into this PR. 

>The vest being green is a bit strange, as it doesn't fit either the sec or paramedic colour scheme, and the trauma team suit which it does match isn't gonna be part of their kit.

I chose the teal on the vest mostly to match the brig medic uniform shown in the mockups (which, yes, is a separate, still open PR, but I was working on these simultaneously and split them up to keep things atomic); teal's adjacent to navy and complementary with burgundy. I think it looks pretty solid on the sec and paramed uniforms too, personally, but that's obviously subjective. Medbay's kind of weird in that its department color is actually white, and it's used with a ton of secondary colors that tend to differ based on the actual job within medbay. The closest thing to an overall secondary color it really has is green, since that's the color used for medbay backpacks and doors. Anyway if there's enough demand for it I'll recolor the medic vest to be a little bit more generally-applicable in color scheme.

**Comment by Kurfursten** [comment]
How about adding a sheet of metal to transform it since it changes the armor values? Then screwdrive it to remove.

**Comment by Kurfursten** [comment]
Splash bleach to remove? Paramedics can get it pretty easily and you don't bleach most things.

**Comment by Apogee-dev** [comment]
> Splash bleach to remove? Paramedics can get it pretty easily and you don't bleach most things.

Yeah, that should be pretty simple to do. I'll add it in shortly.

**Comment by Apogee-dev** [comment]
Medic vest can now be cleaned by spraying bleach, or anything else that calls the decontaminate() proc. in other words, you can remove the skin in the same ways as clowned armor.

**Comment by Kurfursten** [comment]
Conflicts

**Pull request closed without merging**
