### PR TITLE
Revert "liberator gun buff"

### PR DESCRIPTION
**Pull request by adacovsk**
Liberators are too strong now

Reverts vgstation-coders/vgstation13#32236

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Liberators are strong but what made/broke that round was the quantity of them, not any individual guns themselves
Plus the crew was very capable, and the blobs didn't have the best positioning (their cores wide open to space flanking).

It's just bad luck imo.

**Comment by adacovsk** [comment]
it's been bad luck the past month at least

**Comment by Kurfursten** [comment]
We haven't seen them used enough to judge if they're too strong now. Need to see them printed more.

**Comment by adacovsk** [comment]
> We haven't seen them used enough to judge if they're too strong now. Need to see them printed more.

bro, I'm INTJ, I got the intuition, trust me

**Comment by WindowsErrors** [comment]
what even is the liberator gun

**Comment by Blithering** [comment]
> what even is the liberator gun

Cheaply printed laser that does does less damage when shot at non-blobs. Think the hunting rifle but FUTURE

**Comment by WindowsErrors** [comment]
if it's the hunting rifle of the future then why does it take 10 shots to knock someone over in the game but only one hunting rifle shot to knock someone over in real life

**Comment by Blithering** [comment]
I meant the vox trader hunting rifle. As for compared to real life, I guess because NT uses 3D printed bullets containing no gunpowder.

**Pull request closed without merging**
