### PR TITLE
Security Rocket Launcher 

### PR DESCRIPTION
**Pull request by bathosbathtime**
[balance]

## What this does
This pull request adds rocket launchers to all armories, removed the gold requirement to make them, removes the silver requirement for stun rockets, and removes the uranium requirement for EMP rockets. This PR has also expanded the armories of box, xoq, roid, snaxi, packed, and wheelstation. Packed HoS office and Detective's office were also touched to fit the new armory, with the HoS losing a filing cabinet and the detective's office losing a newscaster. This PR also adds plastic to the rocket launchers starting materials to match its cost to make. I am unsure if they are even recyclable.

## Why it's good

The core idea behind security RPGs is to give players a safer version of the RPG to use so that when they roll nuke ops a total party kill due to a mishandled RPG is less likely. This expands on this core idea by making the SecRPGs more accessible. The cost of the rocket itself is now more in line with the other weapons in the ammolathe, beating out all other weapons in cost but being comparable to the vector in costing only metal, glass, and plastic with the gold cost being removed. The rockets themselves are single shots that cost far more metal than any other ammo in the ammolathe which I believe is fitting for their power. They are more expensive than every other ammo in the ammolathe with the sole exception of explosive shotgun shells. However, I believe the single shot nature of rockets compared to the pump-action nature of a shotgun means that the rockets being cheaper, or at least easier to supply as plasma isn't easily compared to metal costs, should cause it to heavily overshadow explosive shotgun shells. These changes have considered the cost of other forms of weaponry security could be using, most notably the shotgun, the vector, the egun, and grenades, and I believe the bulkiness of the RPG, the fact that it is single shot, and the sheer cost of rockets compared to any other form of ammo means that rockets should not pose serious threat to the balance of the game.
## How it was tested

First, the costs were tested in the ammolathe, and the rockets fired from a printed SecRPG. Next, each map was edited, compiled, and walked through. The SecRPGs were also fired to test if they worked. Further, any change that touched an APC, such as wheelstation or packed station, had the SMES units filled with the admins secrets panel and were observed until the started charging in the APC menu and also until the sprite itself turned yellow. After each map was edited, it was opened in StrongDMM to be saved in the TGM format before getting a commit made as per the mapping guide on the wiki.
## Changelog

:cl:
 * rscadd: Added Rocket Launchers To The Armory On Most Maps
 * rscdel: Removed Filing Cabinet From Packed HoS Office
 * rscdel: Removed Newscaster From Packed Detective Office
 * tweak: Removed Gold Requirement For Ammolathe Rocket Launcher Recipe
 * tweak: Standardized All Nanotrasen Rockets To Cost Only Metal

### CODE REVIEW

**Comment by hacker-on-steroids** [comment]
half the maps having 6 rocketlaunchers feels a bit silly
metaclub having one floating in space is even more silly

**Comment by wotisjanitor** [comment]
Mega stupid

**Comment by ErrorsWindows** [comment]
pshoom WPHOOM rocket launcher

**Comment by bathosbathtime** [comment]
Removed the stray RPG in space outside of metaclub. Unsure how I missed that the first time, sorry about that.

**Comment by Eneocho** [comment]
oh boy what a fine day
image
I sure hope i don't get fucking RPGd by some lowly shitcurity

**Comment by SonixApache** [comment]
unatomic + meme content but it'll get merged anyway

**Comment by ErrorsWindows** [comment]
> oh boy what a fine day image I sure hope i don't get fucking RPGd by some lowly shitcurity

we can stop the grey tide if god wills it inshallah
afghanistan police station roleplay

**Comment by cloutcode** [comment]
why remove uranium from EMP rockets when the EMP reaction uses uranium and ion carbines cost uranium

**Comment by wotisjanitor** [comment]
EMP's are a pretty big deal.

**Comment by bathosbathtime** [comment]
Going to standardize the amount of RPGs in each armory to three for regular pop maps and possibly one for low pop maps, or none. Also going to move the cost reduction to its own PR. While I think it is still atomic as the PR aims to make the RPG more accessible and these two changes are simply the means to reach that goal I at least understand that they're two different changes and will be splitting them as my understanding of it being atomic may very well be incorrect and/or biased. I am also saying I'm going to do this instead of just doing it because I'm inside of a tropical storm currently, and my power and internet are "spotty" right now.

**Comment by Eneocho** [comment]
You definitely messed something up while remapping. Adding a bunch of stuff definitely shouldn't be 150K line changes on the map files.
Also the CL is wrong now that you reverted the stats changes.

**Comment by hacker-on-steroids** [comment]
not a mapper but i think this is because strongdmm and the default byond mapper or whatever he used save files a bit differently? 
half the file is "different" but it's just name and desc lines that have switched places, should have no real effect
see the mapdiffbot renders, the maps are all normal

**Comment by Eneocho** [comment]
the standard is to export the thing with strongdmm to the clean remap files, i've gotten pestered for mis-exported maps before, though that was when kurf the head collab, guess it now depends on exxion/dilt/west's judgement.

**Comment by bathosbathtime** [comment]
Recent events in the administration has taken my attention, and this would need to be re-made from scratch anyway, so I'm going to close this PR. I'll have to try making it fully in strongdmm to see if that works. Thank you for your feedback!

**Comment by Eneocho** [comment]
you'd probably just need to load the map files and export them again via strongdmm

**Pull request closed without merging**
