### PR TITLE
Burning barrel and bunsen burner fuel tweaks

### LINKED ISSUE #34204: make bunsen burners actually useful
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
110eeb7446d0ebb14a7a50fdf8b5c4a635c34170

# Description
make bunsen burners actually useful. theyre cool i like addin the fuel to them n stuff n turning them on but theyre fuckin usless
# Steps to Reproduce

# What you Expected
bunsen burners always fuckin sucked u shouldnt have to use cauterys n shit to heat shit up 
# What Actually Happened

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
This increases the amount of energy transferred per tick to reagents being heated by bunsen burners and burning barrels.
The current value for ethanol is 3900 J every object processing tick (0.5 seconds) or 7800 W. At the same time, ethanol is being burned at 10ml/second. Burning a liter of ethanol releases 23.6 MJ, so this means an ethanol-burning bunsen burner would be operating at 236000 W, about 30x the power of the current value.
So, it seems that there's lots of room to buff these heating tools without going "over unity".
Given the availability of ethanol (readily available from the nearby chem dispenser), and also other considerations concerning heated chems, this reduces the fuel consumption rate of all of the fuels to 20% of their current values, and increases the wattage by a factor of 3. Note that these aren't dependent on each other, so fuel will last 5 times longer and burn with 3 times as much power. So a 15x increase in efficiency, to around half of the theoretical power output (based on ethanol).

Closes #34204

## Why it's good
Makes it easier to heat reagents and reduces reliance on the laser scalpel.

## Changelog
:cl:
 * tweak: Bunsen burners and burning barrels are more fuel-efficient and effective at heating.

### CODE REVIEW

**Comment by Dacendeth** [comment]
You might want to fix barrels actually working, currently you cant put any chem in them.

**Comment by Hinaichigo** [comment]
Do you know when it stopped working?

**Comment by Dacendeth** [comment]
#34191 around that time is the best I can do

**Comment by Eneocho** [comment]
This as well #34631, duplicate of #34191

**Comment by xeroxemnas** [comment]
Extremely based PR 
Maybe people will actually make shit like alkycosine now.

**Comment by Eneocho** [comment]
Hmm, this also indirectly increases the total o2 consumed and co2 released per tick. Won't be that big an issue unless doing massive autismo heatings, but still.

**Comment by xeroxemnas** [comment]
brb suffocating myself in chemistry from too much chooming.

**Comment by Hinaichigo** [comment]
I don't think it does, as the O2 consumption and CO2 production are per-tick not per-volume, and they remain unchanged in this PR.
I've been considering reworking this a bit and just having heat of combustion defined on the reagent level which would also have the oxidizer and combustion products with the proper molar ratios per u. This could work with fuel spills and stuff too.
I think ShiftyRail was working on having smoke/soot particles be gases in the air which could be interesting to tie into that. Having more trace gasses like water vapor and soot (as a de facto gas).
Water vapor seems kinda fun too because maybe then you could have ultra-hot steam and stuff doing way more damage than simple hot air.
And seems cool to have a room full of hot air and smoke after a fire.

**Comment by Eneocho** [comment]
I meant per unit. Fully consuming 100u of ethanol would now shit out 5x the co2 and consume 5x the o2 overall. It is not that big a deal if you are not going industrial chem (without using a laser scalpel for some reason), but it is worth noting.

**Comment by Eneocho** [comment]
I believe #34103 is the culprit for the broken barrels.

**Comment by Eneocho** [comment]
Should close #34204.

**Pull request merged**
