### PR TITLE
Advanced Kidneys

### PR DESCRIPTION
**Pull request by CodenameB**
This PR adds a new type of cybernetic enhancement for the crew: Advanced Kidneys.

By having these inserted into your body, you will slowly heal toxin damage naturally. No more getting 1u of toxin and having to deal with not having 100% health and annoying messages until you go to medbay. They are also slightly more damage resistant, just like advanced lungs. In game, they will use the name "toxin filters" to tell people what they do. Prosthetic livers have been appropriately renamed. 

I suspect they will be heavily requested by engineers and genetics staff who always find themselves getting 5 or so units of toxin damage from radiation. 

Doctors should note that removing healthy kidneys still deals a lot of toxin damage, so make sure to have a little anti-tox ready for the post-surgery.

Advanced Kidneys cost the same as advanced lungs to build, and have the same technology requirements as the other advanced organs.

:cl: 
 * rscadd: Added a new advanced organ - kidneys. These will filter toxins out of your body automatically.
 * tweak: Prosthetic liver renamed "artificial metabolizer" to reflect the fact it doesn't actually filter toxins.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
I was under the impression that the filtration function of the kidneys primarily involves metabolic wastes like urea, while the liver holds the chief role in the filtration of foreign drugs and toxins.

**Comment by CodenameB** [comment]
The liver metabolizes toxins and breaks them down, but it doesn't actually filter them. The kidneys filter the blood out.

**Comment by Shadowmech88** [comment]
By the time the liver's done with them, are they even toxins anymore? The kidneys may remove the waste product, but as far as getting rid of the toxins themselves, it seems to me that the liver's more important.

**Comment by ghost** [comment]
yes, they are still toxic, that is why people die if they skip out on dialysis.  The short and sweet of it is that you are both right and wrong.  The chemicals the liver handles are metabolic in nature, whereas toxins in space can have a metabolic origin or from things such as radiation.  The nature of things are too different from IRL to really compare.  In theory, good enough kidneys could handle it all (excusing every other important function of the liver, it is not like you could live without it).  At this point we are just making shit up though in regards to actual organ function, so who cares.

**Pull request merged**
