### PR TITLE
[DRAMA] Added a space suit crate to cargo

### LINKED ISSUE #16646: Feature request: Space Suit crate on cargo
i mean, come on now.
you can order a space suit for vox, also for plasmamemes and there's also one for greys only
why not for the humans too?, just make it expensive like 200 bucks each
it could really help those dark dorf times when peoples that took the suits have fucked off and you're left doing nothing because you didn't chose a race with a roundstart space suit, or you didn't got lucky to get a suit quickier, so you have to sit down in the outpost doing jackshit.
inb4 "just use a firesuit bro."

### PR DESCRIPTION
**Pull request by DamianX**
Closes #16646

:cl:
 * rscadd: Space suits are now orderable from cargo.

### CODE REVIEW

**Comment by jknpj** [comment]
whatever

**Comment by AlphaBuffalo** [comment]
I honestly don't see a problem with this, cargo already has access to mining hardsuits

**Comment by ghost** [comment]
This is the white softsuit with hueg slowdown
And no magboots

A lot of people would literally prefer to be naked than take this

**Comment by SkowronX** [comment]
give it a try. revert if shit gets ridiculous.

**Comment by Fruktlimpa** [comment]
As long as there are no magboots

**Comment by Blithering** [comment]
Ghetto suits kind of fill this niche, but choice is a good thing

**Comment by gbasood** [comment]
This is gonna get a merge with a big asterisk on it, depending on results.
Anyone who feels like they can make a good argument against it after it's gone through a round or two is free to hit the "revert" button and state their case in the revert PR.

**Pull request merged**
