### PR TITLE
Better Ian Mechanics

### LINKED ISSUE #24122: dogs are essentially fucking locusts with how much they eat
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
259b9a7c16d1244ca5e795e45a3255f4d741994b

# Description
dogs literally won't stop eating
a single corgi ate everything in the kitchen
they just won't fucking stop
# Steps to Reproduce
spawn 200 pizzas
spawn a corgi
observe the destruction
# What you Expected
Make food, serve food to people, corgi eats a slice of pizza and is content
# What Actually Happened
Slave to the canine syndicate, shoveling barrels of food into its gaping maw every second to keep it somewhat sated

### PR DESCRIPTION
**Pull request by Kurfursten**
fixes #24122

Instead of just eating 4 bites always and taking in no reagents, corgis now actually eat food. They won't eat if they are overfull. They will whine if hungry. You can poison Ian with bad food. No mechanics to make chocolate poison Ian are included.

Small or tiny creatures that eat food get double nutrition from it. (Don't worry, roundstart Ian can still easily demolish a whole box of donuts, I tested)

🆑 
* rscadd: Small or tiny animals get double nutrition from eating food.
* rscadd: Ian is no longer a bottomless pit for food, but will whine if he's underfed.

### CODE REVIEW

**Comment by DeityLink** [comment]
While you're at it please add a dog food bowl that you can click with food items to drop them on top of it. It's probably been sitting in one of my ancient TODOs for half a decade.

**Comment by Kurfursten** [comment]
I don't think that's in scope for this one, this was really just to fill a request for Sonix

**Comment by SonixApache** [comment]
dog bless you kurf, you are a blessing upon this codebase and a shining star of the community
at last, my kitchen will be safe from the canine menace

**Comment by Blithering** [comment]
> dog bless you kurf, you are a blessing upon this codebase and a shining star of the community at last, my kitchen will be safe from the canine menace

Until we release 101 corgi puppies on the kitchen

**Comment by Eneocho** [comment]
Does this ruin the classic dog treadmill engine?
­>can't poison ian with chocolate
why

**Comment by Kurfursten** [comment]
It's just not in scope to add mechanics for it. Most chocolate items don't even have the coco reagent in them so you'd need to create a new flag for items with chocolate, and then it just spirals into feature bloat.

> Does this ruin the engine?

No, but if you don't give him any food at all he will whine miserably a lot

**Comment by Eneocho** [comment]
dude literally just make it so eating raw chocolate poisons it, stuff made with chocolate is fine due to something something processed food, there's no need to overfeature this thing, literally just have chocolate bars be poisonous as an easter egg (since you can poison it with other stuff, or just shoot it if you want ian dead)
>No, but if you don't give him any food at all he will whine miserably a lot

some say suffering is the cornerstone of every great engine

**Comment by Kurfursten** [comment]
Ruby has (correctly) informed me that mice do not actually eat food either, much like corgis used to, and instead just get a flat 10 nutrition from attacking food. This does mean that if you inject nutriment into a mouse it still gets double bonus, but they won't get double when eating for themselves.

That's a little bit weird, so I'm just going to take the joke about mice rejoicing out of the CL.

**Pull request merged**
