### PR TITLE
Biomass no longer has a fetish

### LINKED ISSUE #23021: On top of a myriad of other problems with it, biomass has a weird fetish for only growing southward
#### Description of issue

The random event biomass has a raging hardon for only growing southwards, see pic below
https://i.imgur.com/WKmn1wh.png
That biomass went south through 3 windows all the way to the goddamn PA in engineering before growing north a single tile

#### Difference between expected and actual behavior

For it to grow in a somewhat balanced fashion like vines (and also not grow into windows where it is AIDS to remove but thats a different problem)

#### Steps to reproduce

Literally just watch biomass spawn, I've seen this happen every single time this crap spawns I just never bothered making an issue about it before

#### Specific information for locating

Mash that spawn vines button until biomass happens

#### Length of time in which bug has been known to occur

Fuck knows, probably since biomass was first made because its horrible gunk.

### PR DESCRIPTION
**Pull request by Zth--**
Fixes #23021

While I'm on it, can we make biomass a bit more interesting?

[bugfix]

:cl:
 * bugfix: Biomass now spreads randomly instead of south-only

### CODE REVIEW

**Comment by Intigracy** [comment]
is get_step_rand really that non-random?

**Comment by Zth--** [comment]
Yes. http://www.byond.com/forum/post/141080

I tested it, the bias is enormous

**Comment by DrSnips** [comment]
I'd rather just axe biomassdue to its lack of sanity like how it goes through windows sometimes.

**Comment by DrSnips** [comment]
Don't get me wrong. I'm glad it's finally getting some attention but it's a long way from being completely fixed when we already have vines and powercreeper which are light years more interesting.

**Comment by utilitas-** [comment]
and lightyears more annoying to deal with/horrifyingly laggy

**Comment by DrSnips** [comment]
You got me there on powercreeper being badly coded as well.

**Pull request merged**
