### PR TITLE
Fixes Scrambler and Microwave Ray Effects Ignoring Shield Blocks

### PR DESCRIPTION
**Pull request by Optimism333**
## Bad Bug, Bad ##
There's a bug with the disintegrator alternate mode rays (microwave and scrambler) where they apply their effects even if blocked by a shield. Only damage is getting blocked.

I'm trying to squish the bug so that ray damage AND effects are blocked properly by shields.

[bugfix]

:cl:
 * bugfix: Microwave and scrambler rays can now be properly blocked by a shield.

### CODE REVIEW

**Comment by Optimism333** [comment]
Oh no, I have done something horribly wrong. Please hold.

**Comment by Optimism333** [comment]
Well, that was a learning experience. Anyways, it seems to work properly now.

**Comment by WindowsErrors** [comment]
is it sort of like how you can block a stun baton with a shield but you still get stunned

**Comment by Optimism333** [comment]
> is it sort of like how you can block a stun baton with a shield but you still get stunned or can catch a cream pie when someone throws it at you but you still get creamed

Yeah, it's similar. In either case it's weird to get the feedback in chat that the projectile was blocked/caught, but have its effect applied anyways.

**Pull request merged**
