### PR TITLE
Adds 12 new bar signs

### PR DESCRIPTION
**Pull request by JStheguy**
Just as the title states, this adds 12 extra bar signs to give a bit more variety in choices. Also destroys the universe by adding an extra 104KB to the total uncompressed file size.
borkborkborkros
boxtollbar
boyster
brokendraems
chemlab
clun
commoonism
fammydammy
foreman
meem
soclub
yahtzee

### CODE REVIEW

**Comment by Nienhaus** [comment]
My email said JStheguy. I thought you died. Oh also cool signs.

**Comment by PJB3005** [comment]
We moved to gitlab

**Comment by Probe1** [comment]
Good signs.  

>Der Fuhrers Trinken Haus

top kek.  but still, we've on gitlab now.  https://gitlab.com/vgstation/vgstation/merge_requests

**Comment by BestName** [comment]
Or are we?

**Comment by PJB3005** [comment]
Nope we're back on GitHub.

**Pull request merged**
