### PR TITLE
Clockcult 3: Clockcult harder.

### PR DESCRIPTION
**Pull request by PJB3005**
Hey look GitHub didn't let me reopen #5432!

copy of the old docs & stuff [here](https://docs.google.com/document/d/14L8UkrRmIyMJRDlaWHrRGSkbxBqzUY3UxHGwQOrFcCw/edit?usp=sharing) and [here](https://docs.google.com/spreadsheets/d/17e6PByDTVZHMzcP-tpWbq8V3T-OmPFAmFbbZKv4mJOw/edit?usp=sharing) and [here](https://www.dropbox.com/s/l5pnmyhwqel2m5f/clockcult-revenants.mdown?dl=0) (last one not a copy)
old PR over at #5236

**Credits:**
- @VelardAmakar - Tons of code & lore & the idea...
- @remierichards - More code.
- @SkowronX - sprites
- @FuryMcFlurry - sprites

obviously still DNM and WIP like the old one.

### CODE REVIEW

**Comment by SkowronX** [comment]
Let's finish this.

**Comment by FuryMcFlurry** [comment]
clockworkdoorbolted
clockdooropening

guess I'm going to pick up the doors again and make them cool as fuck

**Comment by DeityLink** [comment]
Godspeed

**Comment by FuryMcFlurry** [comment]
What needs to be done anyway sprite wise

**Comment by PJB3005** [comment]
@FuryMcFlurry https://docs.google.com/spreadsheets/d/17e6PByDTVZHMzcP-tpWbq8V3T-OmPFAmFbbZKv4mJOw/edit#gid=1961890894

**Comment by SangriaMonkey** [comment]
When

**Comment by FuryMcFlurry** [comment]
cannot find you on irc @PJB3005  so gonna post the clockwork door here. pls noone else download sekrit only
http://puu.sh/kKbIT/9ec9d89b9a.dmi

**Comment by Skullyton** [comment]
The ratvar sprite's got me hyped for this.

**Comment by FuryMcFlurry** [comment]
https://puu.sh/l7RQE/ce34ec42fb.dmi

Added the tinkers daemon sprites. have fun because i cant tell of the animations are good enough due how alpha works on the byond tools.

Picture of the daemon itself
tinkersdeamon

**Comment by PJB3005** [comment]
Guys windows obviously doesn't want clockcult to finish.

**Comment by SkowronX** [comment]
Then fix it or find an alternative.

**Comment by PJB3005** [comment]
Eh windows deleted the folder randomely whilst I was doing something else so it's fine.

**Comment by PJB3005** [comment]
https://dl.dropboxusercontent.com/u/107028026/ShareX/2015/11/2015-11-04_15-36-45.webm

**Comment by SkowronX** [comment]
Nice

**Comment by FuryMcFlurry** [comment]
AAAAAA
that effect needs to be on a different overlay or else it looks ugly m8
Also please update the spreadsheet if you could please.

**Comment by SkowronX** [comment]
I think it looks fine.

**Comment by SkowronX** [comment]
ratnnar

**Comment by PJB3005** [comment]
I assume that overlay was for the vanguard power.

Also powers aren't on the spreadsheets.

**Comment by FuryMcFlurry** [comment]
Go add them then. Or hire someone to do so.

**Comment by Imagebard** [comment]
Are there any negative effects for Clockwork cultists messing with Nar-Sie stuff? Just asking.

**Comment by PJB3005** [comment]
No plans for it, though I'll definetly add them.

**Comment by DeityLink** [comment]
You should ping me some time on IRC so we can discuss Nar-Sie/Ratvar cults possible interactions. Once we get there.

**Comment by ghost** [comment]
Cult v Cult when?

**Comment by Imagebard** [comment]
>Conflicts

Here we go.

**Comment by PJB3005** [comment]
Itt's been conflicting for like, months now...

**Comment by ghost** [comment]
W
H
E
N

**Comment by PJB3005** [comment]
never

:(

**Comment by SkowronX** [comment]
Perhaps some day. I just hope to be there.

**Comment by PJB3005** [comment]
If I ever finish this I'll reopen it I guess...

**Comment by Imagebard** [comment]
wakemeup

**Comment by ghost** [comment]
Since I forgot to mention, this is being rewritten from scratch as part of a PR on /tg/station that I'm doing. Check the link above.

**Comment by ihadtoregisterforthis** [comment]
More reasons for this codebase to already finish this, competition

**Comment by ghost** [comment]
I would rather not have another code competition. That happened on /tg/ with economy a while back and it was disastrous.

We _can_ have different versions of the same gamemode though, as we are different codebases.

**Comment by ghost** [comment]
> no code war

what a time to be dead inside

**Comment by PJB3005** [comment]
There is a code war though.

**Comment by ghost** [comment]
Just leave it alone, it's been three months since you did work on this. If there's a code war, it's closer to the Cold War than an actual conflict.

**Comment by ihadtoregisterforthis** [comment]
Your attempts to deter our side have no effect

**Comment by PJB3005** [comment]
@Xhuis I see it as competition.

**Comment by ghost** [comment]
Suit yourself, but I don't have any will to have another code war.

**Comment by PJB3005** [comment]
https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/06/2016-06-05_15-22-48.webm

**Comment by ihadtoregisterforthis** [comment]
What is even going on on that webm?

**Comment by SkowronX** [comment]
Interactive mini ui for the clockwork daemon that chooses which component to mass produce

**Comment by Imagebard** [comment]
That's PJB3005 is showing us that he's not all bluff.

**Comment by PJB3005** [comment]
https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/06/2016-06-05_21-16-40.webm

**Comment by PJB3005** [comment]
New sprites from Skowron.

**Pull request closed without merging**
