### PR TITLE
[Sprites] New baton item_state

### PR DESCRIPTION
**Pull request by DeityLink**
batonsprite

You now see a glow around the tip of stunbatons when they get turned on.

### CODE REVIEW

**Comment by clusterfack** [comment]
I dont see it

**Comment by gbasood** [comment]
@clusterfack The one on the left is glowing slightly

**Comment by Brolaire** [comment]
if you add two pixel to the tip area people will deffo see the difference

**Comment by DeityLink** [comment]
Well it's most noticeable when you switch states. The idea behind that change was that now, when a bunch of sec officers oppress the clown at the bar, they can draw out their stun batons and they'll visibly become activated.

**Pull request merged**
