### PR TITLE
Adds an eerily familiar vault that smells like rockmen

### PR DESCRIPTION
**Pull request by Probe1**
https://youtu.be/0p0jlAgZpBY

The vault has heavy use of random spawners to keep loot fresh.  It contains all the trappings of its inspiration.  Engineering, Medical, Shielding, DOOR ROOM, and more.  Loot severity is mild with the most notable inclusion being a bunch of nikita missiles where the missile rack was in its inspiration.  No nikita launcher was included.  

Contains a complete and functioning power system and a faux atmospheric one.  Hopefully one day we'll redo shuttle datums and we can have dynamic shuttle docking.

dreamseeker_2016-12-29_16-11-05

🆑 

 * rscadd: Adds the iconic Kestrel as a vault.

### CODE REVIEW

**Comment by Exxion** [comment]
KESTR*E*L

**Comment by Probe1** [comment]
you saw NOTHING

**Comment by Exxion** [comment]
OK I get that you're going for accuracy, but those external airlock areas are FUCKHUGE and may cause things onboard the ship to be ZASed

**Comment by Probe1** [comment]
Seems fine in testing on Hellish.  It only creates an issue when players stand there with the door open trying to ZAS everything.

**Comment by Riekland** [comment]
REBEL FUCKING SHITS

**Comment by Sprok0** [comment]
Where are the golem simple mobs that will punch you to death

**Comment by Exxion** [comment]
That's kind of surprising, but if it's tested then whatever

My only other complaint is that the door room's pretty silly, but there's not really a more appropriate thing in the codebase to put in a door room

**Comment by Probe1** [comment]
Yeah I'm not coding a door console for this.  Someone said they'd like to and if they do I'll update.

@Sprok0 the only simple mob golems are wiz ones and I'm not super interested in going deeper into this.

**Comment by 9600bauds** [comment]
Few immediate concerns:

1) APC in the camera room slipped off the wall
2) The drones can open doors
3) Needs washing machine
4) The door room is excellent, don't change it

**Comment by Probe1** [comment]
Fixed 1 already

2. Drones path randomly and never managed to exit the room in the (up to 30 minutes) testing.  Now they technically could, but they'd have to randomly move through several rooms then path all the way to the station and even then they're retaliate so something would have to hit them.

**Comment by Kurfursten** [comment]
@9600bauds The door room would actually be a little more accurate if it was full of door bolt/open buttons a la dorms, but instead associated with each airlock on the ship. You know, for tactical depressurization and door sealing during raids.

**Comment by Probe1** [comment]
that sounds thrilling to do but I must pass on linking like 32 doors.

**Comment by Intigracy** [comment]
Why is the top engine area windowed but not the bottom?

**Comment by Probe1** [comment]
I'm not sure what part you're referring to.  The atmos section above is there for visibility.  The AME section is so players can extend it if they feel triggered by the 3x3 AME (AMEs don't handle mapping very well).

**Comment by Shadowmech88** [comment]
Maybe he's referring to how the port engines are directly exposed to the interior cavity while the starboard engines are completely behind a wall?

**Comment by Probe1** [comment]
Oh that?  No reason, just how I decided to do it.  It doesn't affect atmos I believe and can change it if it looks awful but I didn't find the difference notable enough.

**Comment by unid15** [comment]
>Hopefully one day we'll redo shuttle datums and we can have dynamic shuttle docking.

What do you mean by dynamic shuttle docking? If you mean docking two shuttles together then you can already do that

**Comment by Probe1** [comment]
I mean letting players create shuttle docking ports.

**Pull request merged**
