### PR TITLE
Winning Vaults Added

### PR DESCRIPTION
**Pull request by Kurfursten**
Adds the great vaults from our January contest!

🆑 
* rscadd: A materials research lab and ruined pod dock can now be found in space.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Tested these on local and they're good to go

**Comment by Eneocho** [comment]
weren't there a couple more vaults than just these?

**Comment by Kurfursten** [comment]
Stranger was added in a separate PR
Deity and Realest both PR'd their own vaults

**Comment by Eneocho** [comment]
ah yeah that makes sense

**Pull request merged**
