### PR TITLE
Delayers - Muh fps Update

### PR DESCRIPTION
**Pull request by clusterfack**
# Fixes delayers 
So that they are now world.time agnostic, therefore 
-while they will still be affected by something like latency (a slowdown doesn't mean you can shoot 3 times at once)
-they will no longer be affected by tick_lag (a lower tick_lag doesn't mean you can shoot 3 times faster than normal).

###  Consequences
- [x] Using any fps wasn't possible before due to breaking balance/gameplay elements
- [x] You can now use any fps without any significant noticeable effect on gameplay, except higher framerate

### CODE REVIEW

**Comment by Iamgoofball** [comment]
but muh scenic quality

:+1:

**Comment by clusterfack** [comment]
Alright, I've reviewed everything present here and everything appears to check out to me so I welcome any comment so this may be put through more quickly and efficiently, because holy fuck that many files is going to end up conflicting with something.

If you notice some systemic identical issue with a large quantity of them, just leave one comment and I'll address it all at once next time I get a chance.

**Comment by BestName** [comment]
But muh silky smooth 11fps

**Comment by d3athrow** [comment]
moshi moshi pomf desu

**Comment by Iamgoofball** [comment]
why

**Comment by clusterfack** [comment]
There was a better way

**Pull request closed without merging**
