### PR TITLE
Fixes bugs

### LINKED ISSUE #8068: slots
(WEB REPORT BY: talux00 REMOTE: 158.69.55.2:7777)

> 77520459064c0945f3ea61969973a55966fb467b 
> 
> Whenever you equip an item in the suit storage, the sprite of said item stay on the hand but the item itself go to the storage and the only way to unequip it/use it, is to unequip your armor/suit.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

### LINKED ISSUE #8070: Suit Slots
(WEB REPORT BY: xsdew REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Spawning in as a plasmaman, I had no plasma tank, yet I was able to use internals Like normal
> 
> What you expected to happen

Spawning in with a plasma tank on my suit slot as a plasmaman

> What actually happened
> Internals are on and running but no plasma tank on my persons
> 
> Steps to reproduce if possible
> Currently just spawning in, I dont know if its with late join or the suit slot specifically

### PR DESCRIPTION
**Pull request by ghost**
Prevents runtimes when debugging hypothermia
Fixes bugs.

fixes #8070 & fixes #8068 as well as two unreported bugs:
1. hypothermia doesn't work
2. space suits nerfed accidentally

### CODE REVIEW

**Comment by 9600bauds** [comment]
Did hypothermia not work all this time

**Comment by ghost** [comment]
It's been accidentally disabled since err, #8005

**Comment by clusterfack** [comment]
>hypothermia doesn't work

:sob: :laughing:  100% tested

**Comment by ghost** [comment]
@clusterfack wow rude

**Comment by 9600bauds** [comment]
Get memed on kid

**Comment by ghost** [comment]
@DrCelt
Please make atomic PRs instead of a dozen different fixes in one.

**Comment by Exxion** [comment]
Termed you're not even a coder

**Comment by 9600bauds** [comment]
non-atomic bugfixes are fine nerd

**Pull request merged**
