### PR TITLE
fixes poker tables, organizes structures.dmi

### LINKED ISSUE #3519: (WEB REPORT BY: thataxxguy REMOTE: 198.245.63.50:7777) Minor graphical error on Gambling Tables
2x2 Gambling Tables top and bottom halves do not connect properly graphically, looks wonky due to this..

Minor graphical error.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #3519

nice and organized

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
What's the process to organizing the icons?

**Comment by Intigracy** [comment]
By type.

I put all the border windows together, the plasma ones were seperate before, then I put the windows in order, then the tables in order.

Damage sprites are after their respective windows.

girder/breakgirder/displacedgirder, with the two unused icons at the end.

There were also duplicates of wood tables, same icon name and same icon.

**Comment by ihadtoregisterforthis** [comment]
I was actually asking 'how2 ogarnise .dnmi'

**Comment by Intigracy** [comment]
Select icons to move, ctrl x, click a diff icon, ctrl v. It pastes your selected icons in order **after** the one you clicked.

**Comment by ihadtoregisterforthis** [comment]
I was hoping for a better secret way, but thanks.

**Comment by SkowronX** [comment]
FUCKING TEST SHIT, GOD DAMN

**Comment by clusterfack** [comment]
Smooth

**Pull request merged**
