### PR TITLE
Fixes #6754

### LINKED ISSUE #6754: Editing mobs' ckeys is requiring both +DEBUG and +VAREDIT which is pretty shit, see below.
Coders ree, due to Celt's SDQL fuckery half the admins cannot change ckeys of mobs, which proves it rather difficult to fix things like antags and borers!

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
My issues are fly, my commits are sick. Seriously though, THIS IS IMPORTANT!
Fixing people, and shit.

### CODE REVIEW

**Comment by 9600bauds** [comment]
Don't paste the whole link, just the hashtag

**Comment by Probe1** [comment]
Make sure @nuklearcellphoneg and @d3athrow are cool with it please.

**Comment by nuklearcellphoneg** [comment]
ok

**Comment by Probe1** [comment]
:+1:

**Pull request merged**
