### PR TITLE
Revert "EVERYBODY (almost) has maintenance access"

### PR DESCRIPTION
**Pull request by d3athrow**
Reverts vgstation-coders/vgstation13#25112

### CODE REVIEW

**Comment by Goldsteel** [comment]
Probably for the best. It was an interesting experiment at least.

**Comment by Zth--** [comment]
So... what are the conclusions of this "experiment"?

**Comment by Goldsteel** [comment]
We learned: 
1. Don't merge things on a whim and correct them with the opposite extreme.
2. Access wasn't really an issue to begin with.

**Comment by jknpj** [comment]
http://ss13.moe/index.php/poll/198

**Pull request merged**
