### PR TITLE
Revert of revert of Adds Avali as a playable race

### PR DESCRIPTION
**Pull request by Konater**
I missed playing resomi on baystation years ago so I brought them here.  Sprites taken from Glasseclipses april fools pr which are borrowed from Polaris, which are apparently in turn borrowed from Bay.
They are small feathered raptor things based on things that apparently have official lore, I'm sure a specific someone would love to tell you about it on your local general.
I look forward to my ban.
 
Things still to be done by someone that isn't me because I am a smoothbrain
- Apply the skintone to the tail
- Apply the limb feathers to the base sprite with hair colour
- Figure out why picking skintone doesn't seem to apply on spawn
- Give mechanical punishments for existing

### CODE REVIEW

**Comment by ghost** [comment]
ok clown main
also you gotta UPDATE your FILES you CLOWN

**Comment by JTGSZ** [comment]
Yeah man, you need to make it work.

**Comment by drawsstuff** [comment]
absolute mad lad

**Comment by JevilUndertale** [comment]
Yes. Broly Culo approves of this PR. Broly Culo thinks that this PR is NECESSARY in order to make /vgstation/ a better game. And to be fair, is Broly Culo ever wrong?

**Comment by ShiftyRail** [comment]
Na

**Comment by ghost** [comment]
what the fuck am I reading I'm not glasseclipse

**Comment by SageOfLight** [comment]
Who the fuck and why the fuck.

**Comment by Accipitermaris** [comment]
what in the god damn

**Comment by d3athrow** [comment]
lol

**Pull request closed without merging**
