### PR TITLE
Allows all assemblies to be attached to wires

### PR DESCRIPTION
**Pull request by ghost**
[content][consistency]
I don't know why this wasn't already a thing
Should open up a ton of more gimmicks, like voice activated door bolts and etc
:cl:
 * rscadd: All assemblies can now be attached to wires, not just signallers

### CODE REVIEW

**Comment by Exxion** [comment]
Out of curiosity, what happens if you attach an infrared emitter?

**Comment by GreatBigFailure** [comment]
> Out of curiosity, what happens if you attach an infrared emitter?

That was also my immediate question

**Comment by Eneocho** [comment]
I guess the emitter ray fires in a specific direction? This would need a specific check to choose which direction (and laser type) is the emitter firing.

**Comment by Exxion** [comment]
Yes, if it fires at all, it would probably be south. But I don't know if it fires at all.

**Comment by Eneocho** [comment]
can't wait for the inevitable WGW-opened door

**Comment by DeityLink** [comment]
now you're thinking with redstone

**Comment by ghost** [comment]
> Out of curiosity, what happens if you attach an infrared emitter?

Should now work

**Comment by Kurfursten** [comment]
> 
> 
> > Out of curiosity, what happens if you attach an infrared emitter?
> 
> Should now work

Yes but what happened in testing? Which way did it laser?

**Comment by ghost** [comment]
> > > Out of curiosity, what happens if you attach an infrared emitter?
> > 
> > 
> > Should now work
> 
> Yes but what happened in testing? Which way did it laser?

It lasered the way it was set in the item itself, previously before tweaks it didn't at all

**Pull request merged**
