### PR TITLE
Changes for BYOND 512

### PR DESCRIPTION
**Pull request by DamianX**
With these changes we can compile on 512.
512 doesn't _completely_ work yet (DM crashes when compiling tgstation.dm, but works fine on test_tiny.dm) but this also compiles on 511, so here it is.

### CODE REVIEW

**Comment by gbasood** [comment]
Did you also try running this, and not just compiling?

**Comment by DamianX** [comment]
test_tiny runs

**Comment by gbasood** [comment]
Only thing about this is I don't think it actually works *outside* of 512 right now.
At least it didn't when I tried to testmerge it via the bot

**Comment by DamianX** [comment]
I can't see how that would be the case, I'm just renaming a bunch of vars?

**Comment by Cisrox** [comment]
whaat the fuck

**Comment by DamianX** [comment]
Waiting on [this](http://www.byond.com/forum/?post=2338657), for the record

**Comment by DamianX** [comment]
Now waiting on http://www.byond.com/forum/?post=2340796

**Comment by DamianX** [comment]
I don't think I'll be following this closely in the near future so I'm closing, if someone wants to take over they should feel free to do so. I'm not gonna delete the branch.

**Comment by PJB3005** [comment]
Here's a script to fix the map files.

https://gist.github.com/PJB3005/60ca8097e0cd4f986209a90a008fe156

**Comment by gbasood** [comment]
Tested locally
0 runtimes on roundstart
forgot to check hard dels but that's probably down too because of the bugfixes they've described since 511

**Comment by ShiftyRail** [comment]
Not even a runtime related to smooth walls ? I usually get that on roundstart. 🤔

**Comment by DamianX** [comment]
Someone should figure out which paths need `use_tag` set

**Pull request closed without merging**
