### PR TITLE
New Rev Modes: RevSquad and Provocateur

### PR DESCRIPTION
**Pull request by Kurfursten**
**Midround**: Rev Squad
* Takes 3 ghosts
* An elite team disguised as cargo techs arrive with satchels loaded up with 2-4 BULLET-based guns and equipment (vastly improved from the original RevSquad, read below)
* Each has a flash good for 1 conversion (also possible to roll an extra flash in gear), an emp-proof RevSquad headset, and insulateds
* Each also has an EMP pulsar, which constantly (toggleable) emits EMPs in a short range every 2 seconds. These make taking on the Rev Squad an entirely unique experience that demands bullet counterplay or other methods of engagement like slip traps.
* Convertees will receive a message informing them that there are limited conversions and to stick with the squad.

**Latejoin**: Provocateur
* A less threatening version of Revolution, one latejoiner (with a valid job) becomes a revhead!
* There are no other revheads and revolutionaries are warned that they will not be able to convert more crew if they lose their provocateur. Protect him or her at all costs! Convertees will receive a different message indicating they must protect their sole revhead.

---

**RevSquad Guns** (2-4)
* Deagle, Deagle Camo, Deagle Gold, Gyro Pistol, Beretta, Luger, Assault Rifle (XCOM), Sawn-Off Shotgun, Uzi, Stechkin Pistol, Colt Single Action Army

**RevSquad Gear** (Remaining slots)
* Emag, Vest, Prescription Sunglasses, Telescopic Baton, Classic Baton, *Extra Flash*, Box of Flashbangs, Box of Smokebombs, Box of Handcuffs, Box of Bolas, _or..._

New Items (Gear):
* Chaos Bandolier: Holds only IEDs. Starts with 14 loaded.
* Fully Loaded Slimbelt: A slimbelt loaded up with tools.
* Fully Loaded Ammo Pouch: An ammo pouch that detects which random guns you received and gives +2 mags for each (or speedloaders)
* Spray Bottle of Lube + Spray Bottle of Sodium Polyacrylate (set of 2)

---

Under the hood bonus: 
* re-wrote the messages for spawning as a rev head or being converted in normal revs
* no mode of rev will ever fire if a previous form of rev already fired
* revolution won't end before 5 minutes after gamestart

🆑 
* rscadd: Added a new midround mode, RevSquad.
* rscadd: Added a new latejoin mode, Provocateur.

### CODE REVIEW

**Comment by Irradiation** [comment]
Give them the Automag as a pistol too, if they already have Deagles & Colt SAAs.

**Comment by Durgen** [comment]
people will metagay and be extra suspicious of groups of cargo techs

could the rev squad use randomized civies instead?

**Comment by Kurfursten** [comment]
I don't necessarily think that's going to be a concern. Think of this more like only a slightly more subtle nuke ops. They're loaded down with very loud guns and pulsars that are constantly throwing off highly obvious EMPs, plus flashing people over to their side for a blitz. It's kind of like "if you see 5 people with the same last name not on the manifest, it's ops". It's fine to identify 3 non-manifest cargo techs are BIG TROUBLE.

**Comment by Kurfursten** [comment]
This is ready

**Comment by gbasood** [comment]
revsquad 2 electric boogaloo

**Pull request merged**
