### PR TITLE
Storage items don't auto-collapse at 7 items if not full

### PR DESCRIPTION
**Pull request by help-maint**
Bear with me, because it's hard to explain what this PR does, why it's needed, and why it's not optimal.

Now that most containers have a storage limit based on the size of the items inside (rather than a static number of slots), you can run into issues trying to use storage that has 8 items inside.
For example, this box that is inside my backpack:
dreamseeker_11_04_2021_06_11_11_50
If you remove one of the pieces of paper, the inventory collapses back into 1 row. And now if you want to put the paper back, you have to find the box's icon again, because there is no "empty inventory slot" you can click anymore.
mspaint_11_04_2021_06_20_20_06
This can range from 'annoying but doable' in the case of backpacks, since you're wearing them and thus are always somewhere on your HUD, to 'just plain fucking annoying' for nested storage (box inside a backpack inside a toolbox inside a BoH: you have to close the box, open the BoH, open the toolbox, open the backpack, and then finally click the box, and you need to do this every time you want to remove an item from this box and then put it back).

What this PR does is leave an empty row on-screen if your storage still has leftover room, and has 7, 14, or 21 items inside.
dreamseeker_11_04_2021_05_56_56_53
This solves the problem, but it's not perfect, because there are cases where your backpack may have 7 items inside but only enough space for 1 more TINY item. And you may not actually have a tiny item that you want to put inside, so you're probably thinking "wtf why is this empty space here if I can't put anything inside?".

Other servers solve this better by having inventory icons have different sizes depending on the size of the item, so that they always add up to a full bar. Until someone ports that, this is the 2nd best option.

:cl:
 * tweak: Storage items won't collapse if they're not full, so you can always remove the 8th item and then put it back by clicking the same spot it was in.

### CODE REVIEW

**Comment by Kammerjunk** [comment]
though maybe not perfect, this is so so much better than right now

**Comment by DrSnips** [comment]
Maybe rather than resizing icons the bags get some kind of overlay or a ghost item in them that has that info. How to present that info is something. You could give people a straight number and hope players learn it (ie my bag has 2 weight points left so I can only hold 1 more item)

**Comment by Dacendeth** [comment]
This is going to make having a exactly 7 tools in a toolbelt/slimbelt more annoying and screen cluttering and i cannot agree with that.

**Comment by help-maint** [comment]
Yup that's the edge case. If you can think of a better solution I'll try it, otherwise, lesser of two evils

**Pull request merged**
