### PR TITLE
removes straight jacket from orderly

### PR DESCRIPTION
**Pull request by Apogee-dev**
Self-explanatory, orderlies no longer spawn holding a straight jacket. This does not remove the straight jacket found in medbay storage.

Straight jackets are actually pretty nasty if they're abused since you can't resist out of them, and it's better to keep them limited to the single jacket found in medbay storage on every map. Putting them in the orderly's hands on spawn over-emphasizes the shitter control aspect of his job too, when in reality he's primarily a janitor and roleplay job. When orderlies do need to deal with troublemakers, they should be ejecting them from medbay, not detaining them (and if you really need to detain somebody, you can use bandages or biohazard tape as ghetto cuffs)
:cl:
 * rscdel: Orderlies no longer spawn with a straight jacket.

### CODE REVIEW

**Comment by Servalfang** [comment]
reason?

**Comment by Apogee-dev** [comment]
> 
> 
> reason?

edited the PR description with reasoning, but in short straight jackets are too easy to abuse and giving extras to the orderly over-emphasizes part of the job i really intended to come last in priority. Orderly is a janitor and paper-pusher first and a bouncer last.

**Comment by SonixApache** [comment]
i for one think security nurses should get even *more* super handcuffs, to really emphasize the necessity of their role

**Comment by Kurfursten** [comment]
From what I have seen of orderly plays - and I have seen a lot of them both playing the role, being around medbay, and observing a lot - the straight jacket isn't a big deal. But I also won't miss it because it does send the wrong message about what role orderly fills. I said as much before on a few occasions - orderlies should be kicking out disruptions, not imprisoning them.

But I would like to see more orderly content created instead of just slowly chipping away at them like the last few PRs.

**Comment by Apogee-dev** [comment]
> But I would like to see more orderly content created instead of just slowly chipping away at them like the last few PRs.

I do agree that I'd like more content for orderly, if i could only think of it. I don't think this or the injector reduction PR count as chipping away content, though. The straight jacket and the injectors are still there, it's just that we had too many of them. I opened the original orderly PR fully expecting that the job would need balance adjustments in the future or even expecting to revert it should it not go over well. That orderly was as well-received as it has been and has only needed very minor adjustment is a minor miracle in my eyes.

Anyway, whatever new content I add for orderly in the future is probably going to take the form of paperwork and records-related additions. I don't really see what I could do to expand on the janitorial side of things.

**Comment by Kurfursten** [comment]
Roundstart bleach bottle + spray bottle would be nice
Special orderly belt that can hold your odd mix of things - the suitcase is just a bit cumbersome
Maps really need to be mapped with recordkeeping in mind with easy access to a cabinet for orderly
Ability to upload a copy of fullbody scan reports straight into medical records (same with autopsy reports, and...)
Special health analyzer that can print a copy of its results for records

Just some ideas

**Comment by Apogee-dev** [comment]
> Roundstart bleach bottle + spray bottle would be nice
> Special orderly belt that can hold your odd mix of things - the suitcase is just a bit cumbersome
> Maps really need to be mapped with recordkeeping in mind with easy access to a cabinet for orderly
> Ability to upload a copy of fullbody scan reports straight into medical records (same with autopsy reports, and...)
> Special health analyzer that can print a copy of its results for records

Every medbay has a roundstart spray bottle of space cleaner or several iirc, and chemistry to make bleach (I don't want to take away bleach being something unique to the janitor here, and it's easy to make if you take enough care to avoid gassing yourself).

You suggested the belt back when I was first coding orderly and i'm still iffy on it, though it WOULD encourage orderlies to not use up one of the med belts. Filing that away for later consideration.

I considered paperwork map updates earlier when I was adding the paper bins, and I'll probably go through them later. I don't want to give medbay a photocopier for forms because there's a public one in the library, but a file cabinet wouldn't be terribly out of place. The CMO office always has one for this purpose, actually, but it's not like orderlies have access to that. If medbay had more of a dedicated office or records area to work with this would be a lot easier...

The printer scanner is a good idea and one I'll probably code.
Same for report uploading, though I'm pretty awful at working with console UIs.

**Comment by Kurfursten** [comment]
I already do steal the spray bottle and I already do make assloads of bleach, but are you aware of how much charge it takes to fill a spray bottle up with bleach? It's also somewhat tedious to do because of the small result size until you get at least a bluespace beaker.

**Comment by Apogee-dev** [comment]
> 
> 
> I already do steal the spray bottle and I already do make assloads of bleach, but are you aware of how much charge it takes to fill a spray bottle up with bleach? It's also somewhat tedious to do because of the small result size until you get at least a bluespace beaker.

alright, that IS a fair point. You _can_ dilute it with water and still get the same cleaning effect- I do that all the time as janitor to make that measly 15u bottle last- but you're right, a bottle for the orderly wouldn't go amiss. It's just a question of where to put it since orderlies don't get their own closet or office and i'm not thrilled at the idea of adding one. Probably the chemistry closet.

**Comment by BomberBro** [comment]
Pandora's Box has been opened, no mortal may close it...

**Comment by Eneocho** [comment]
> Special health analyzer that can print a copy of its results for records

The CMO's health analyzer can print results, but I'm not sure giving an orderly a CMO Analyzer Lite would be a good idea.

**Comment by Apogee-dev** [comment]
> 
> 
> > Special health analyzer that can print a copy of its results for records
> 
> The CMO's health analyzer can print results, but I'm not sure giving an orderly a CMO Analyzer Lite would be a good idea.

yeah, I know. I wouldn't give the orderly any special function to his analyzer except letting it print scan results. Alterntatively, one could bake that functionality into every scanner.

Then again, you won't get the full results without the proper body scanner anyway, and those already print.

**Comment by Blithering** [comment]
What about the ability to assign triage priority to patients? Might be helpful to be the organisation guy if the medbay is swamped, you can sift the fridge munching lot from those who are full of IB and 2 seconds from chestbursting.

**Comment by Apogee-dev** [comment]
> 
> 
> What about the ability to assign triage priority to patients? Might be helpful to be the organisation guy if the medbay is swamped, you can sift the fridge munching lot from those who are full of IB and 2 seconds from chestbursting.

That sounds like a feature that would be best baked into the medHUD, like setting people to arrest using secHUDs. I'll think about how to work that one.

**Comment by Anton-Kr** [comment]
Bay iirc has triage tags for their medhuds.

**Comment by Kurfursten** [comment]
>Simply adding a high priority care tag

Extremely easy

>Adding tags with different symbols for Broken Bones, Internal Bleed, Suicide/DNR, etc.

Actually useful

**Comment by Apogee-dev** [comment]
> 
> 
> What about the ability to assign triage priority to patients? Might be helpful to be the organisation guy if the medbay is swamped, you can sift the fridge munching lot from those who are full of IB and 2 seconds from chestbursting.

That sounds like a feature that would be best baked into the medHUD, like setting people to arrest using secHUDs. I'll think about how to work that one.

> 
> 
> > Simply adding a high priority care tag
> 
> Extremely easy
> 
> > Adding tags with different symbols for Broken Bones, Internal Bleed, Suicide/DNR, etc.
> 
> Actually useful

Originally I was thinking symbols for priority level (DNR, low, normal, critical) but having icons for specific conditions marked on the medHUD would be really useful.

**Comment by Kurfursten** [comment]
This is close enough that I will give it to end of week

**Pull request merged**
