### PR TITLE
some content for mapping

### PR DESCRIPTION
**Pull request by unid15**
- Added 3 new floors to floors.dmi
- lava icon's animation is now smoother
- Added mars turfs with almost scientifically accurate atmos (we don't have argon so it's been replaced with nitrogen)

### CODE REVIEW

**Comment by gbasood** [comment]
@PJB3005 XGM when

**Comment by PJB3005** [comment]
@gbasood ask @clusterfack

**Comment by unid15** [comment]
what's XGM?

**Comment by SkowronX** [comment]
Mars Z level in the works?

**Comment by clusterfack** [comment]
Suspiiiiicious

**Comment by ComicIronic** [comment]
XGM is ZAS gas datums

**Pull request merged**
