### PR TITLE
Fixes cable dipping

### LINKED ISSUE #35720: Lashing with Cable Coils dips them
(WEB REPORT BY: dovemite REMOTE: 209.222.101.3:7777)
# Revision
673c4e2def23743a0ed422614f4d4be2b66fdc64

# Description
Hitting yourself with cable coils by mistake dips them into you and dyes them white. Unsure if this applies to other players
# Steps to Reproduce
Hit self with Cable Coils
# What you Expected
You lash yourself in the chest with the cable coil!
# What Actually Happened
You lash yourself in the chest with the cable coil!
You dip the cable coil in <insertname>

### LINKED ISSUE #35721: Lashing with Cable Coils dips them
(WEB REPORT BY: dovemite REMOTE: 209.222.101.3:7777)
# Revision
673c4e2def23743a0ed422614f4d4be2b66fdc64

# Description
Hitting yourself with cable coils by mistake dips them into you and dyes them white. Unsure if this applies to other players
# Steps to Reproduce
Hit self with Cable Coils
# What you Expected
You lash yourself in the chest with the cable coil!
# What Actually Happened
You lash yourself in the chest with the cable coil!
You dip the cable coil in <insertname>

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #35720
Fixes #35721

Fixed it on handcuff and forgot to do it on cables as well

:cl:
* bugfix: You can no longer dip cables in mobs, re-enabling you to lash people with them.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Somewhat nuclear option is it not? This removes dipping in any non-item open containers like structures (cauldrons) or machinery (TEG circulator).

**Comment by DeityLink** [comment]
Actually here's a better question, why do humans return true on is_open_container() ? this itself is a source of many other bugs right now, you can drink some paint and then dip the brush in yourself, etc.

Was this always a thing? How badly would it break the game to change it?

**Comment by Dacendeth** [comment]
i'd guess if humans were not an open container you wouldnt be able to syringe chems into them or take blood samples?

**Comment by Kurfursten** [comment]
> Actually here's a better question, why do humans return true on is_open_container() ? this itself is a source of many other bugs right now, you can drink some paint and then dip the brush in yourself, etc.
> 
> Was this always a thing? How badly would it break the game to change it?

Probably interfaces with sprayed reagents or something, would want to do testing with it

**Comment by DeityLink** [comment]
Alright I went through the entire code and found only two instances in the code where is_open_container() was plausibly intended to apply to mobs as well, so I just removed the child is_open_container() from /mob/carbon/living, and added the extra check where applicable, while removing all the redundant checks for ismob(). Mobs can always be given the OPENCONTAINER flag if you want them to be treated as such. In the meantime this should solve every issue involving is_open_container.

I tested to make sure that syringes and sprays still work as expected, and they seem to.

**Pull request merged**
