### PR TITLE
Sawn off ion rifles

### PR DESCRIPTION
**Pull request by ghost**
[content]
image
Can be sawn off in the same manner as a shotgun.
Has a 25% chance to fail and EMP everything around it on sawing and whenever fired. (may adjust if wanted)
Can fit in backpacks and on belts like normal sawn offs.
:cl:
 * rscadd: Ion rifles can now be attempted to have their barrels sawn off, although they become a bit more unreliable to shoot as a result.

### CODE REVIEW

**Comment by Kurfursten** [comment]
This reminds me of the time I made a sawn off computer tower. Cut off the part with my monitor hookups, power supply, and disk drives so that I could fit it in a smaller space.

**Comment by ghost** [comment]
> This reminds me of the time I made a sawn off computer tower. Cut off the part with my monitor hookups, power supply, and disk drives so that I could fit it in a smaller space.

Eh, kind of why I made it fail randomly when firing

**Comment by boy2mantwicethefam** [comment]
What the actual fuck

**Comment by west3436** [comment]
Ion Carbines already exist - can't you just make those fit inside backpacks?

**Comment by DeityLink** [comment]
Now that's just silly.

**Comment by SonixApache** [comment]
> 
> 
> Ion Carbines already exist - can't you just make those fit inside backpacks?

They already do, that's literally why they were made. Well, not literally, they were made because someone wanted to add full-scale ion rifles to the protolathe and that seemed over the top. But they fit in backpacks / on belts. #22771 


What might be an interesting option is having this turn it into a melee weapon, like a makeshift EMP baton.

**Comment by ghost** [comment]
> Ion Carbines already exist - can't you just make those fit inside backpacks?

These use the normal rifle type ammo, carbines use gimped shots

**Comment by PavelCIA** [comment]
Sawn off laser guns when?
>25% chance to set yourself on fire

**Comment by Eneocho** [comment]
These should be less accurate to reflect them having a shorter "barrel" instead of the EMP chance.

**Comment by SageOfLight** [comment]
Cut in half an electronic device.
It still works.
Not a 50% failure chance because of how absolutely fishbrained this is.

Based and absolutely fucking stupid pilled.

**Comment by ghost** [comment]
> These should be less accurate to reflect them having a shorter "barrel" instead of the EMP chance.

If I could code this, sure

> Cut in half an electronic device.
> It still works.
> Not a 50% failure chance because of how absolutely fishbrained this is.

Up it to 50?

**Comment by SageOfLight** [comment]
> Up it to 50?

I'm mostly joking since you pretty much destroyed the weapon since god knows what vital electronics were inside the barrel. It's not like cutting off a gun barrel AT ALL.

It probably had emitters inside it that are gone now and you're just holding an exploding battery with a trigger.

**Comment by Eneocho** [comment]
> 
> 
> > These should be less accurate to reflect them having a shorter "barrel" instead of the EMP chance.
> 
> If I could code this, sure

You could look at the ricochet taser's code for ideas on how to make it less accurate.

If you can't make it be less accurate, instead of EMP-ing, it should have a 1/4 chance to not shoot, needing you to manually "pump" it (like a shotgun) so it unsticks.

**Comment by Blithering** [comment]
@kane-f If you're interested in other failure effects for sawing off guns, there's the old lockbox damage PR https://github.com/vgstation-coders/vgstation13/pull/11753 , people were against the balance change, but there were some amazing misfires that could possibly be copy/pasted wholesale such as the entire battery firing off with an increasing chance per shot of the weapon exploding (see gif)
7226b3e6-8127-11e6-888a-3a6d5ed53d23

**Comment by BomberBro** [comment]
Sawn off ion rifles should IMMEDIATELY explode into a medium sized EMP when fired

**Comment by calzilla1** [comment]
Sawn off ion rifle should create a 1x1 explosion, send out a giant EMP pulse, and gib the shooter.

**Comment by xeroxemnas** [comment]
This niche is already filled by ion carbines. Retarded secmain just wants to interact with science even less.

The full sized ion rifles are supposed to be bulky and not easily portable. That's the entire point. That's why they do more damage than the ion carbines. This change would make ion carbines even more useless since everyone would just use the sawn off ion rifles instead.

**Comment by Kurfursten** [comment]
image

Just for everyone's info

**Comment by DeityLink** [comment]
Replace this PR with the ability to saw off any weapon. Cutting their sprite in half, and leaving them 90% the time unusable, with in the worst case some shit happening when you saw them off, potentially based on cell charge.

**Comment by Eneocho** [comment]
>Replace this PR with the ability to saw off any weapon.

Can't wait for the sawn-off sawn-off shotgun.

**Comment by Kurfursten** [comment]
Mmm sawn off taser and sawn off invisible finger gun

**Comment by DeityLink** [comment]
> 
> 
> Mmm sawn off taser and sawn off invisible finger gun

sawing the finger gun should drop your hand

**Comment by Blithering** [comment]
RIP fun PR.

**Pull request closed without merging**
