### PR TITLE
Adds 'nevervars' list consisting of step_x and step_y

### PR DESCRIPTION
**Pull request by Intigracy**
In case it's not obvious from the name, they can never be edited (via vv at least)

### CODE REVIEW

**Comment by Intigracy** [comment]
This makes it so admins trying to pixel edit don't accidentally fuck up entire rounds anymore.

**Comment by Aurx** [comment]
Might be worth adding some sort of feedback if somebody without +DEBUG tries to edit a lockedvar.

**Comment by Intigracy** [comment]
It gives the message automatically unless it's passed a 0 for the second arg.

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/admin/holder2.dm#L56

**Comment by Aurx** [comment]
Huh, that's a thing?  
You can tell how long it's been since I haven't had +DEBUG.  

God I'm a fucking geezermin.

**Pull request merged**
