### PR TITLE
Changes "NanoTrasen" to "Nanotrasen"

### PR DESCRIPTION
**Pull request by BestName**
While I was doing #8058 I noticed that in certain instances "Nanotrasen" was spelled as "NanoTrasen". Since "Nanotrasen" has the majority I've decided, for the sake of consistency and autism, to get rid of "NanoTrasen".
There were a few instances of "NanoTrasen" in some of the map files but I didn't change those because I don't like touching the maps.

### CODE REVIEW

**Comment by BestName** [comment]
Please don't look for typos in the changed files this time.

**Comment by clusterfack** [comment]
Please stop I'm worried for your mental health

**Comment by BestName** [comment]
There's no stopping the autism train

**Comment by FudgePucker** [comment]
But isn't it abriviated (yes I know I misspelled it) NT?

**Comment by BestName** [comment]
Yes it is. Why do you ask?

**Pull request merged**
