### PR TITLE
code of conduct - short and sweet edition

### PR DESCRIPTION
**Pull request by Intigracy**
adds a code of conduct because it's important to have one

### CODE REVIEW

**Comment by Aurx** [comment]
While you're at it, document the formatting and coding standards.  They're still recorded absolutely fucking nowhere, right?

**Comment by Intigracy** [comment]
Those are being worked on atm

**Comment by Lokiamis** [comment]
Embarrassing to read tbh

**Comment by ShiftyRail** [comment]
I don't know, the first draft seemed perfectly fine.

**Comment by Blithering** [comment]
Replace code of conduct with the beepsky rant

**Comment by Aurx** [comment]
Just leave it blank, that'll be most accurate.

**Review by jknpj — APPROVED** [review]

**Pull request merged**
