### PR TITLE
Box Server Room actually has atmosphere now????

### PR DESCRIPTION
**Pull request by Kharkov72**
It was brought to my attention that the server room on box usually doesn't have air in it because it all gets vored by the vent. Now it uses h/e pipes and has a vent in it from distro. Will test and post fancy pics soonish.
Does some mild reorganizing to the room as well.
[box]
Really though how the fuck was the server even working.

:cl:
 * rscadd: Box Server Room is now equipped to actually function.

### CODE REVIEW

**Comment by Kitfox88** [comment]
the ABSOLUTE STATE of BOXBABS

**Comment by Kharkov72** [comment]
Untitled
Untitled2
About to fix the air alarm but his is how it looks now.

**Comment by Kharkov72** [comment]
Untitled5
_God has forsaken us._

**Comment by Kharkov72** [comment]
Untitled
Speak now or forever hold your piece.

**Pull request merged**
