### PR TITLE
BusStation: Ready for Public Testing

### PR DESCRIPTION
**Pull request by Kurfursten**
**All images, previous discussion, and description** in #7713

This clean PR will be a good place for ongoing critique of the map for improvement after it goes into public testing. BusStation is a map made from scratch in the spirit of Taxi Station. With a completely new floorplan, bigger rooms, separated Taxis, plus abundant alternate transport via mail sorter, space pods, and space suits, BusStation is all about mobility.
bus

Still needs to be enlarged to @dylanstrategie dimensions
Still needs @unid15 vault areas

@d3athrow Put this on the test server or in the rotation, it's ready for public testing!

### CODE REVIEW

**Comment by Exxion** [comment]
DO
NOT
SET
`step_x` OR `step_y` EVER
EVER
EVER

**Comment by SysadminJeroen** [comment]
Quality Code

**Comment by Exxion** [comment]
Just change all the `step_x` references to `pixel_x` and the same for `step_y`
Otherwise it will break gliding, and possibly (however unlikely) movement as a whole

**Comment by Kurfursten** [comment]
It happens when you use nudge in mapping automatically. It's not my fault BYOND has a shitty mapping program.

**Comment by xpcybic** [comment]
Posting here to remind myself to look at it :open_mouth:

**Comment by Kurfursten** [comment]
I should have reminded myself that overconfidence is a slow and insidious killer. And by slow I mean "I should have finished this 4 months ago before I left"

EDIT: Okay, step_x is purged. I can safely wash my hands of this PR until some testing gets done. It's all on you, Contributors.

**Comment by CptWad** [comment]
step

**Comment by Durgen** [comment]
could there be unfinished bridges between the stations for mommis to work on?

**Comment by Arthurdentist** [comment]
train station when

**Comment by Kurfursten** [comment]
@Arthurdentist You joke, but EuropaStation has some pretty cool trams.

**Comment by ihadtoregisterforthis** [comment]
The vox outpost could have assorted canisters, but that can go along live test tweaks

**Comment by Imagebard** [comment]
I'm trying to find the maint tunnels to hide dead people in here, and I'm having trouble.
Can I have a bigger map, at least?

**Comment by SysadminJeroen** [comment]
@Imagebard, I think that the map is meant for lowpop/deadpop. So just hide
them in a corner or in a locker.

2016-05-18 17:51 GMT+02:00 Imagebard notifications@github.com:

**Comment by Kurfursten** [comment]
@Imagebard There are three enlarged maps on the old PR's OP. Maint is actually fairly extensive on SiliMed station and decent on CivEng. It's present but a little lackluster on Secsci, but at least it's not a deadend like Taxi maintenance. Just in the spirit of being helpful though, here are some highlights to guide you.

highlighted

**Comment by Imagebard** [comment]
Secschi having less maint AND a sec base on it makes scientists a little too protected, but otherwise its fine.

**Comment by Exxion** [comment]
I keep reading "Silimed" as "Slimed"

**Comment by Kurfursten** [comment]
@Imagebard As-is traditional, Miners and Scientists benefit from being to hide from those security officers on their research station on the roid. I am not too worried about science antagonists having it "too hard".

**Comment by Imagebard** [comment]
I wrote that because of people with scientist targets having it too hard, but that applies too

**Comment by kol1th** [comment]
:+1:

**Comment by xpcybic** [comment]
A little late but here's some things I've caught so far:
screenshot_2016-05-18_18-01-15
- Hole in the wall here
- Missing cabling here by the telepad console and in xenobio
- Some firedoor inconsistencies all around; mixture of full-tile and one-direction firedoors, firedoors missing at some airlocks/desks
- Check the floor in ghetto surgery, it has blocks_air = 1which causes weird atmos issues (this happened on box previously)
- From my understanding the old taxi AI core was laid out such that the turrets couldn't hit people properly; maybe copy the updated one I made?
- Also look at my updates to taxi's research outpost with larger xenobotany and wired emitter
- Does that shuttle console need to be in a powered area to work? Right now it's in the asteroid area

**Comment by Kurfursten** [comment]
Good catches. Pity about one of those things requires immediate attention and the others are polish. Looks like it'll be another commit before it goes public.

**Comment by ihadtoregisterforthis** [comment]
There was also a large hole on the science department, on the "break room".

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis That was only in the rough draft version of science. That image didn't even have completed power lines or pipes.

**Comment by ComicIronic** [comment]
You should discontinue full-tile firelocks. We switched over to directionals for a reason.

**Comment by ComicIronic** [comment]
New map label

**Comment by ghost** [comment]
Now to hope we don't create yet another stillborn map. Taxi was a shame, but it was created during the "Small maps for small pops" meme and was too cramped and shitty to save

**Comment by Kurfursten** [comment]
Okay, I'm going to sweep through and fix xpc's catches. Meanwhile, new info from thread:

http://www.strawpoll.me/10260130/r

**Comment by Kurfursten** [comment]
I have to say, xpc's new core is really nice looking. I was able to port it almost entirely, except for some slight modifications, such as updating the pipes to be layered. Everything else was fixed too, I believe. I also added a little more detail to maint in places it was dry.

**Note to self: Vox outpost botany could use a mini-hoe**. This isn't game-breaking since a hoe isn't needed immediately and they can trade for it, but I want to fix it in the next round of changes, even if we go live before that.

**Comment by Kurfursten** [comment]
@ComicIronic @PJB3005 @Clusterfack Unless you have further objections, this can move to NFD. Last time I wasn't proactive, this sat around for four months.

**Comment by d3athrow** [comment]
this is on test server btw

**Comment by Kurfursten** [comment]
Is it the same IP as the test server listed in the thread and on the wiki? If so, I don't think that's right.

I even called the shuttle. It wasn't on the vote panel. Tried Taxi just in case, still nothing.

**Comment by Kurfursten** [comment]
Pomf came through and it was put up on the test serb. Did pretty exhaustive testing today with Obereth, a community member. Most of the feedback was positive. I found these issues which have been resolved for the next revision.
- Some brig areas were not properly defined (as it was rebuilt following suggestions from the previous PR)
- Two doors near the rebuilt brig didn't have tiles under them
- One botany door to maint had a wall under it
- Added some lights
- Added a hoe to Vox outpost
- Defined the space sorter as an area. I don't know why this was necessary - I don't think Taxi did it, and I think it worked previously in testing, but clearly something about autoconveyors has changed because it won't run outside a defined area now.
- Fixed a missing cable to the podbay on eng/cargo
- Adjusted Civ/Eng bridge
- Fixed a missing cable to Xenobio maint
- Fixed Virology airlock buttons being hidden under a poster
- Door under airlock to mining half of research station
- Fixed airlock access to courtroom
- Completely reworked Toxins and the maint outside of it
- Added a lot of detail work to Perma
- Made the needlessly-small hcapel office a bit larger
- Fixed the Vox SMES being infinite (oops)

**Comment by ghost** [comment]
Crap, not again.
Seems like you knew about the conveyors already, too. Hope that's my last Useless issue

**Comment by Durgen** [comment]
Some Bus feedback:
- The exterior of the stations are a bit dull. More walkway and exterior latice would be nice.
- the map display on the crew monitoring computer is offset a bit
- AI upload is a bit cramped
- doors that have the maint hatch screwed open seem to be using the normal sprite while closed. Not sure if also a bug on the normal server?
- I found that other door with a wall under it. It's near comfy chairs and tables on medical station
- no room for a toxins zoo :cry:  maybe we could have a virology zoo?
- I'm not a fan of how security lockers are spread out across the stations and only 4 are in the brig
- pod bay near mechanic should be mechanic only
- no metal or glass in thsi podbay
- the hop office is a little dark
- intercom in CE office needs to be tuned for Poly and turned on
- RD office and Science break room need some comfy
- the bar could use more stools

Great job overall. I'm excited to play it for real.

**Comment by Kurfursten** [comment]
Thanks for the feedback, I'll take those into consideration. Actually, I was looking for an idea for another maintenance room to fill out the science station maint, and a zoo seems like a good idea.

**Pull request merged**
