### PR TITLE
Doomguy clothes and cleanup

### PR DESCRIPTION
**Pull request by DeityLink**
Removed tons of those deprecated sideway sprites, and added Dizor's Doomguy sprites, with placeholder ground icons.

### CODE REVIEW

**Comment by DeityLink** [comment]
oh good, conflicts, let's see...

**Comment by FudgePucker** [comment]
YOU ARE HUGE! THAT MEANS YOU HAVE HUGE GUTS!
RIP AND TEAR!

Now all we need is a traitor bundle that comes with a double barreled shotgun with ammo and the suit.

**Comment by CptWad** [comment]
>EDIT: also his belt should be able to hold any weapon ever. You should be able to carry 8 weapons

We need more belt types for badminstuff in general.

**Comment by FudgePucker** [comment]
Bluespace belts.
They can hold anything a backpack can, but you can wear it as a belt.

**Comment by Iamgoofball** [comment]
you should make it so that you strafe when moving left or right with this armor on

**Comment by Dizor** [comment]
Just need to finish up the boots, been a busy work week.

**Comment by DeityLink** [comment]
@Dizor Oh hey Dizor, did you finish those on-the-ground sprites?

**Comment by Dizor** [comment]
@DeityLink 
Yup, let me slap the updated PSD up here
https://www.dropbox.com/s/z5fl97tixabmidx/doomgy.psd?dl=0

**Comment by DeityLink** [comment]
oh cool, I guess I'll finish it up tomorrow.

**Pull request merged**
