### PR TITLE
Changes changes

### PR DESCRIPTION
**Pull request by eswordthecat**
qwhieubvuw bqwhdvuq wjhvd uqjvdqwhjdqbsdhabsd hjavsdvhajsvdasjhdasvd avhdasd

### CODE REVIEW

**Comment by ComicIronic** [comment]
>no PR message

MERGE NEVER

**Comment by eswordthecat** [comment]
What do you want? Copy and paste the commit messages in PR message?

**Comment by clusterfack** [comment]
Wait does this mean blob has to waste an attack to expand on a lattice tile? Sounds like it.

**Comment by eswordthecat** [comment]
@clusterfack No, it's the same how ex_act works but for blob not explosion.

**Pull request merged**
