### PR TITLE
PR template

### PR DESCRIPTION
**Pull request by Probe1**

### CODE REVIEW

**Comment by Probe1** [comment]
thats what you get for not rebasing

**Comment by Intigracy** [comment]
```
If you're working with PNG and/or DMI files, you might want to check out and install the `pre-commit` git hook found [here](tools/git-hooks). This will automatically run `optipng` (if you have it) on your added/modified files, shaving off some bytes here and there.
```

That link won't work when it's in the edit menu.
[here](tools/git-hooks)
vs

```
[here](tools/git-hooks)
```

Also that link doesn't work from inside of a PR because it's referencing the PR, as you can see if you click my link above vs click https://github.com/d3athrow/vgstation13/tree/Bleeding-Edge/tools/git-hooks

**Comment by Probe1** [comment]
Shit no one understands and likely never uses :+1:

**Comment by PJB3005** [comment]
Does this even work?

**Pull request merged**
