### PR TITLE
Vox Mining and Engineer Helmet Lights

### PR DESCRIPTION
**Pull request by falcon2346**
## What this does
Adds toggleable lights to the Vox Mining, Engineer, Atmos, and CE helmets, which all have a light visible on the sprite that is not able to be used. As the lights do not require a battery to run, they are slightly weaker than the ones found on hardsuit helmets, having only a brightness of 3 instead of 4. While somewhat unatomic, this also makes a correction to the Mining helmet sprite to fix a visual inconsistency in the West facing sprite.

## Why it's good
Makes the helmets mechanically align with their sprites. Additionally, it's a pain to fix pipes without a decent light as rooms with recently sealed breaches are often dark, making Material Scanners difficult to use. This was only a problem for Vox, as other species can use the standard hardsuit with a built in light.
[oversight]
[sprites]
[tested]

https://github.com/vgstation-coders/vgstation13/assets/111808553/4c039a3c-ae55-4f50-9216-b4819ef379f8

Helmet

## Changelog

:cl:
 * rscadd: Added toggleable lights to the Vox mining and engineering staff helmets
 * imageadd: Added lit versions of the sprites for these helmets
 * tweak: edited the names of the sprites for the adjusted helmets to allow for the lit versions to be made (example: vox-civ-engineer is now vox-civ0_engineer)
 * tweak: adjusted the mining helmet for visual consistency

### CODE REVIEW

**Comment by Kurfursten** [comment]
conflicts

**Comment by Kurfursten** [comment]
bad news: you still have conflicts on hats.dmi

**Comment by falcon2346** [comment]
Yeah I know. Had to step out for a bit, I'll leave another comment when it's fixed.

**Comment by falcon2346** [comment]
Alright, I have literally no idea why it's still conflicting. I cloned the bleeding edge and added the sprites to the new one and it's still showing conflicts.

**Comment by falcon2346** [comment]
Apologies, I could not think clearly due to the room being 95 degrees. I should be able to resolve the conflict now.

**Comment by Kurfursten** [comment]
diffs look good, congrats on conflict resolution

**Pull request merged**
