### PR TITLE
Unique tile painter sprite

### PR DESCRIPTION
**Pull request by RealestEstate**
Finally gives a unique sprite to the tile painter. No more shared icons with the RPD.
tile_painter

[sprites]
originally made by BomberHarris with slight tweaks by me.

:cl:
 * imageadd: The tile painter now has a unique sprite.

### CODE REVIEW

**Comment by ManopolisJones** [comment]
almost looks like a ghetto tile painter, but I do like it

**Comment by SonixApache** [comment]
shading looks weird but i'll take it

**Comment by Eneocho** [comment]
Upgrade to the tile painter so it paints all tiles in a 3x3 square around itself when?

**Comment by BomberBro** [comment]
Oh man, I haven't seen that sprite in probably 3 years. If you want to touch it up any more feel free.

**Comment by Kurfursten** [comment]
conflicts

**Comment by Kurfursten** [comment]
Realest please

**Comment by RealestEstate** [comment]
I will fix it. I've been a bit preoccupied

**Comment by RealestEstate** [comment]
@Kurfursten 
done

**Pull request merged**
