### PR TITLE
A new lawset for MoMMIs during Dwarf Fortress.

### PR DESCRIPTION
**Pull request by SysadminJeroen**
Using game-panel you can set the MoMMI and Silicon lawset to something else, but only lawsets that exist in the game already.

Game-panel doesn't allow you to make completely new laws, and I really want a lawset for Dorf Fortress.

:cl:
 * rscadd: Added the Dorf lawset, made for Dwarf Fortress.

### CODE REVIEW

**Comment by yclatious** [comment]
A dorf lawset so borgs can actually help crabs build shit instead of faffing about, lad, you just made me realize how much I wanted it. Cheers.

**Comment by SysadminJeroen** [comment]
@yclatious This would make borgs and MoMMIs pacifist WE BUILD autists.

I usually notice that humans do fuck all during Dorf rounds and rarely actually build.

**Comment by yclatious** [comment]
I know what it does buddy, that's why I like it.

**Comment by N3X15** [comment]
* Added [Balance] because adds new laws that needs discussion.

**Comment by Aurx** [comment]
I'd ditch laws 1 and 5.  
Law 1 is just griefbait since shitlords will be technically correct as they excuse "Dorfy actions" with it.  Like "Dorfs kill intruders with axes all the time, I'm a Dorf, that assistant was intruding, so I killed him with an axe." or "Dorfs go crazy if they can't do their secret projects and they stole my circuit boards so I went crazy".  It's fixable in policy but I don't see any reason to include it if it'll need policy.  
Law 5 is meaningless since if the silicon fucks off it's already either breaking or following law 4.  

Law 2 is sorta meaningless, but should be harmless.

**Comment by SysadminJeroen** [comment]
@Aurx People using law 1 to harm because it isn't "you may not harm a being regardless of circumstance and intent" is pretty retarded, especially if two laws down there is that law.

Besides that, I don't see people going killing everyone on Robocop because "Serve the public trust.", and I don't see borgs killing everyone on Corporate preemptively because of "You are expensive to replace.".

**Comment by Aurx** [comment]
Law priority, man.  When L1 says jump, L2 doesn't get to say no.  

Robocop works because we have a policy patch that says "don't be a murderous fuck".  It's also hard to manhandle "serve the public trust" into murder.  
Corporate "works" because the first three laws are very very difficult to manhandle into being imperatives and even if you did they'd say the same thing as law four.  
"You are a Dorf" however is pretty easy to pull shit out of your ass to justify shittery with.

**Comment by SysadminJeroen** [comment]
@Aurx I don't see how this law would be any more dangerous than Robocop.

Other than that, would you be okay with it if I moved "You may not harm any being, regardless of intent or circumstance." all the way up and remove "Do not leave your home."?

**Comment by Blithering** [comment]
Might be an idea to change law 2 to 'any sentient being' or borgs are gonna get killed by roid mobs a lot

**Comment by SysadminJeroen** [comment]
Yeah, but I don't want MoMMIs just patrolling around the roid and killing all mobs.

This is a lawset that is focused on MoMMIs after all.

**Comment by Aurx** [comment]
But you explicitly stated that it's for MoMMIs AND Borgs.

**Comment by SysadminJeroen** [comment]
I could tweak it so it works for both, but my primary intentions were to make a lawset for MoMMIs.

**Comment by Shadowmech88** [comment]
Do you intend to tweak it to work for borgs, or are you satisfied with it as it is now?

**Comment by SysadminJeroen** [comment]
I'll go and tweak it right now, however this lawset is made specifically for MoMMIs.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
