### PR TITLE
Make the NT report falsifier more costly, requires traitor collaboration

### PR DESCRIPTION
**Pull request by ShiftyRail**
What it says on the tin.

- costs 4 times as much.
- needs two traitors to meet up and collaborate to get the tiem.
- add a way to trade TCs physically between traitors.

Need to be tested.
 
**Reasoning :** 
The item gunks rounds and should require some planning by the traitors to be used.

### CODE REVIEW

**Comment by Irradiation** [comment]
>tie a TC trade mechanic with the nerf of an item

Ayy fucking lmao. Unatomicity is thataway.

**Comment by PrimeDSS13** [comment]
>grudgecoding

bro...

**Comment by Gazathor** [comment]
sneakycoder sneakycoder i see you, here you try here you try, to grudge code anew

**Comment by ShiftyRail** [comment]
@Irradiation That feature can easily be recycled and, in fact, I plan to add it separately if it passes. I just added it here to make it easier. Don't be too bureaucratic.
@PrimeDSS13 Not grudgecoding if small_boss suggested it first.

**Comment by ghost** [comment]
I need a quick rundown on what led to this.

Also, there are far more reasonable ways of """nerfing""" the falsifier than fucking over solo antags who want to run gimmicks.

**Comment by ComradeDispenser** [comment]
>antag runs gimmick
>makes a fun round happen
>grudge code happens not even an hour after the fact

**Comment by Irradiation** [comment]
You and I both know that traitors openly cooperating & knowing of eachother's status has happened less than 5 times in year of 2019 (I'm making that number up, but I have a feeling it's less than 2 times that it even happened in 2019).

Just stick with your removal PR, at least your feelings are honest there.

**Comment by smonkeM** [comment]
The irony is that one of the antagonists attempted to cooperate by saying codewords to the other (known) antagonist when cuffed by him, and got killed anyway, in the very round that triggered this PR. The concept is dead in the water.

**Comment by PrimeDSS13** [comment]
Somebody makes this announcement in a round using a report falsifier:
>Crew, we here at Nanotrasen are devoted to finding new ways of enriching the lives of our employees. Due to the popularity of thunderdomes and bloodsports in general, we have elected for Space Factory Thirteen to be a station of unrestricted combat. We officially sanction any personnel vs personnel actions, hereby dubbed "PvP", in the maintenance tunnels of the station. Any attempts to interfere with these bloodsports will cause our inspectors to come through.

It's a runescape gimmick, so small_boss backs it up by putting skulls over the heads of people who kill.
Then this interaction happens.
>[18:08:57]SAY: Axel Messager/Shifty_rail (@@213,198,1) As Galactic Common : And hear this also, centcomm:
[18:09:06]SAY: Axel Messager/Shifty_rail (@@213,198,1) As Galactic Common : Your PVP idea is shit and you're all retarded
[18:09:25]SAY: Axel Messager/Shifty_rail (@@208,192,1) As Galactic Common : No time for this
[18:10:01]SAY: Axel Messager/Shifty_rail (@@217,194,1) As Galactic Common : Well, yes, this is interesting
[18:10:09]SAY: Axel Messager/Shifty_rail (@@217,194,1) As Galactic Common : Very immersive, I like it
[18:10:21]SAY: Axel Messager/Shifty_rail (@@217,194,1) As Galactic Common : As in
[18:10:28]SAY: Axel Messager/Shifty_rail (@@217,194,1) As Galactic Common : I'm immersed in joy and peace
[18:10:52]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">Shifty_rail/(Axel Messager) shot Ezudiko/(Smoke Manmuscle) <span title='traitor'>(A)</span> with a /obj/item/projectile/beam>
[18:11:00]ACCESS: Login: Shifty_rail/(Axel Messager) from [NOPE] || BYOND v512

(going braindead)

>[18:11:16]ADMIN: HELP: Shifty_rail/(Axel Messager): Fuckingg no rp retard - heard by 2 non-AFK admins.
[18:11:24]ADMIN: HELP: Shifty_rail/(Axel Messager): Admin hippie instead faggot - heard by 2 non-AFK admins.
[18:11:39]SAY: Axel Messager/Shifty_rail/(Axel Messager) (@211,192,1) Deadsay: mutters, "I'm very glad I'm on vg on not hippie"
[18:11:46]SAY: Axel Messager/Shifty_rail/(Axel Messager) (@211,192,1) Deadsay: spooks, "PVP mode"
[18:11:49]SAY: Axel Messager/Shifty_rail/(Axel Messager) (@211,192,1) Deadsay: complains, "Fucking seriously"
[18:12:10]SAY: Axel Messager/Shifty_rail/(Axel Messager) (@211,192,1) Deadsay: cries, "if you think this is funny you unironically should kll yourself"

Then the round ends, and an hour later this PR is up. You fell for the falsifier 100%. Total grudge PR man, how can you even deny it. Even if Small_Boss supports the idea, the execution isn't right.

EDIT: I think I've been reading too many forum posts.

**Comment by ghost** [comment]
what is this

**Comment by Lokiamis** [comment]
It's not grudgecoding if I have a scapegoat to hide behind

**Comment by boy2mantwicethefam** [comment]
https://www.youtube.com/watch?v=BJhF0L7pfo8

**Comment by SonixApache** [comment]
maybe if certain retarded admins would stop advertising for blood sports events this kinda thing wouldn't be necessary

separate the feature

**Comment by ShiftyRail** [comment]
Litteral not grudgecoding, it's a banbait item that entitely devaluatrs legitimate buses. But ok

**Pull request closed without merging**
