### PR TITLE
Removes illegal tech from chem mask

### PR DESCRIPTION
**Pull request by jakmak3**
does what the title says. Removes the need for illegal tech for the chem mask in the protolathe

### CODE REVIEW

**Comment by Kurfursten** [comment]
I don't know about this. The mask + pack combo is nuts strong, and science doesn't really need any buffs in terms of ability to murderbone. At least the illegal tech makes them work for it. And it IS a syndicate item so I don't know why it shouldn't be illegal tech.

**Comment by Shadowmech88** [comment]
> The mask + pack combo is nuts strong

How often does anyone even make it even when they DO have the tech levels for it?

> And it IS a syndicate item

To my knowledge there isn't any job that allows traitors to order it via PDA.

**Comment by jakmak3** [comment]
kurfurst i have never seen anyone use the chem mask for its intended purpose and ive only seen it made once by another player for baneposting IC. The fact that such an obscure item needs max illegal tech when it is not even a syndicate item is horrible balance

**Comment by Kurfursten** [comment]
It doesn't have a lockbox does it?

Just seems like some pretty serious power creep for a department loaded up on power already since "its intended purpose" is mass murder and making trips to medbay irrelevant.

**Comment by jakmak3** [comment]
kurf it doesnt have a lockbox and besides filling a chem pack with healing chems is a ineffective version of use of chems unless if you were in the middle of combat in comparison to several pill bottles of 50u pills of healing chems. And for the powercreep of science what do you suggest be done to balance this out for the whole station? We could add this to cargo order in a locked crate or the premium item in the medivend+ and even for both of those it would be completely ridiculous for imhulisons and balance in general

**Comment by Kurfursten** [comment]
To balance it out I suggest you put it in a lockbox like other combat tech items that aren't illegal.

**Comment by jakmak3** [comment]
> lockboxes
> balance

Even if that was somehow balanced it still makes no sense. The banemask is not inherently a dangerous item. By that logic we might as well put the adv EOD suit in a lockbox aswell as the adv welder goggles

**Comment by Kurfursten** [comment]
Putting them in lockboxes shows that they're still illegal so that it won't become standard practice for scientists to walk around with their creatine/synaptizine masks. I know that's what you're trying to do because with petty material requirements and tech requirements that get met every shift, it will be 100% standard for every scientist to walk around with a constant synaptizine drip from their chem dispenser if this gets merged.

Stop pretending like we're not talking about ez-hulks. The same as welding goggles? Really? Not even you believe that.

**Comment by Exxion** [comment]
The chempack/chemmask combo even has the emergency beaker or whatever it's called that is basically _designed_ for creatine

**Comment by Shadowmech88** [comment]
The beaker slot is completely designed for creatine. Creatine has a different metabolism rate than most chems so you can't just stick it into the main tank with the rest of the chems.

**Comment by ComicIronic** [comment]
These requirements are incredibly easy to meet, and Science doesn't need more bullshit toys to hoard. Unless there's a genuine reason to make the mask available so easily, this is a bad change.

**Comment by FudgePucker** [comment]
Also isn't getting max illegal research easy enough to do using robotics by deconing tesla relays?

**Comment by ComicIronic** [comment]
Or just sending someone to the Derelict  and have them telesci back if you don't feel like waiting for/using materials.

**Comment by ComicIronic** [comment]
Not habbening.

**Pull request closed without merging**
