### PR TITLE
fixes box sci lights

### PR DESCRIPTION
**Pull request by SonixApache**
minor oversight

#### AFTER
after2

#### BEFORE
before

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Are those light tiles?

**Comment by SonixApache** [comment]
they were, and now they are not

**Comment by DamianX** [comment]
updated pic, then?

**Comment by SonixApache** [comment]
updated

**Comment by iFlashYou** [comment]
>lights on windows

**Comment by SonixApache** [comment]
like i said, oversight

**Comment by SonixApache** [comment]
closing in favor of #20363

**Pull request closed without merging**
