### PR TITLE
Transmitters are now anchored by default.

### LINKED ISSUE #5639: (WEB REPORT BY: intigracy REMOTE: 198.245.63.50:7777) Radio transmitter can be on while not anchored
>Revision (Should be above if you're viewing this from ingame!)
0bc1057d264d04343779de69b169cc001e348e64

>General description of the issue
See below

>What you expected to happen
Transmitter to turn off if not anchored

>What actually happened
A borg murdered the whole crew with a transmitter

>Steps to reproduce if possible
Turn on transmitter
Unanchor
Drag around

If that doesn't work, try unanchoring first, then turning on.

Why it's bad:

### PR DESCRIPTION
**Pull request by Intigracy**
You can also change the anchored state now, since you couldn't before.
fix #5639

### CODE REVIEW

**Comment by Kurfursten** [comment]
It's a machine, you can just change line 24 from

>machine_flags = MULTITOOL_MENU | SCREWTOGGLE

to

>machine_flags = MULTITOOL_MENU | SCREWTOGGLE | WRENCHMOVE |  FIXED2WORK

What you're PRing is actually really, really bad in its current state because it means you can't reposition any transmitter.

**Comment by Intigracy** [comment]
Well, this latest commit addressed it.

**Comment by clusterfack** [comment]
Whether or not this has fixed2work, it doesn't address someone turning on the transmitter unwrenching it and dragging it around.

**Comment by Intigracy** [comment]
@N3X15

**Pull request closed without merging**
