### PR TITLE
sick references

### PR DESCRIPTION
**Pull request by Intigracy**

### CODE REVIEW

**Comment by jernaumorat** [comment]
No, this is stupid.

**Comment by Intigracy** [comment]
no you are

**Comment by ghost** [comment]
Who are you?

**Comment by Intigracy** [comment]
you just can't handle my memes

**Comment by Exxion** [comment]
As much as I like memeing, this is phrased a bit oddly, considering the Goonecode is not a liquid and if you can see that examine text it's already outside of the case

**Comment by Exxion** [comment]
:+1:

**Comment by Intigracy** [comment]
there's a man who appreciates fine memes

**Pull request merged**
