### PR TITLE
Civilian shrooms

### LINKED ISSUE #30574: [Feature Request] Mushmen should be able to join the crew as mimes, or atleast sillycons like everyone else
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
sneed

### PR DESCRIPTION
**Pull request by SonixApache**
closes #30574
More roles? 

:cl:
 - rscadd: Mushroom men can now be mimes.

### CODE REVIEW

**Comment by BomberBro** [comment]
Said it before in the other PR but I really, really don't like killing off the novelty of a race like this. Seeing it everywhere just makes it less special.

**Comment by gurfan** [comment]
I hate interacting with mimes and mushmen are almost as bad.

**Comment by Servalfang** [comment]
everywhere?

**Comment by Kurfursten** [comment]
This is looking unlikely but has 3 days to gain support

**Comment by SonixApache** [comment]
shroom-b-gone

**Comment by Servalfang** [comment]
we need mushsilicons though; every other race that im aware of gets to be one

**Pull request closed without merging**
