### PR TITLE
Allows NT MoMMIs to choose their own sprites

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
wraps it in with the namepick, since they don't choose their own modules.

## Why it's good
more customisation for them, user preference.

## Changelog
:cl:
 * rscadd: Station MoMMIs now have more control over their appearance.

### CODE REVIEW

**Comment by gurfan** [comment]
couldn't they already do this

**Comment by SECBATON-GRIFFON** [comment]
> couldn't they already do this

nah it's been random at roundstart for ages

**Comment by Eneocho** [comment]
> > couldn't they already do this
> 
> nah it's been random at roundstart for ages

Dude what, you literally press the "MODULES" button on the bottom left and select your icon.

**Comment by SECBATON-GRIFFON** [comment]
> > > couldn't they already do this
> > 
> > 
> > nah it's been random at roundstart for ages
> 
> Dude what, you literally press the "MODULES" button on the bottom left and select your icon.

wait really? i'll close this then

**Comment by pedr69** [comment]
heh, idort

**Comment by SECBATON-GRIFFON** [comment]
> > > couldn't they already do this
> > 
> > 
> > nah it's been random at roundstart for ages
> 
> Dude what, you literally press the "MODULES" button on the bottom left and select your icon.

actually it's on the bottom right and called something else.

**Comment by Eneocho** [comment]
Same thing, but the point stands, you can select your sprite.

**Pull request closed without merging**
