### PR TITLE
Kitchen spike diona nymph sprite

### PR DESCRIPTION
**Pull request by DeityLink**
dionaspike

Considering chefs frequently meatspike diona nymphs resulting from failed dionas, I judged that it deserved its own sprite by now.

### CODE REVIEW

**Comment by clusterfack** [comment]
Now we just need a diona-fication animation for the treemen

**Comment by Kurfursten** [comment]
Wasn't this content?

**Comment by Kurfursten** [comment]
There are plenty of ways sprites can cause new bugs. Mistaken pathing. Trying to add a sprite to any read-only dmi. Any actual code surrounding the sprite change itself (e.g.: if you derive a path instead of a hardcoded path). Besides, bug fixing causes bugs, too. (e.g.: #6620) The potential for bugs is ubiquitous and can appear anywhere, even in a sprite content PR.

It doesn't seem in the spirit of the freeze to merge content updates of any kind is all I'm saying.

**Comment by DeityLink** [comment]
That's for the maintainers to decide.

**Comment by Kurfursten** [comment]
Just trying to ensure we keep freeze consistency. We're coming up on a month of freeze now, so it can be easy for anyone to make an innocent mistake and let a content update slip by, forgetting that the freeze is on. I don't think anyone here was trying to game the system intentionally.

**Pull request merged**
