### PR TITLE
Makes compile fail below 511

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
>not tabbing

**Comment by PJB3005** [comment]
What.

**Comment by SysadminJeroen** [comment]
Hold on, let me make a diff.

**Comment by SysadminJeroen** [comment]
```patch
From 70c5cab8598c02d42175828ad071117c2e1e4bb8 Mon Sep 17 00:00:00 2001
From: Jeroen de Neef <jeroen52@gmail.com>
Date: Sat, 15 Apr 2017 02:59:37 +0200
Subject: [PATCH] I like tabs they make it all more readable.

---
 __DEFINES/setup.dm | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/__DEFINES/setup.dm b/__DEFINES/setup.dm
index a8726e60d9..ea95113991 100644
--- a/__DEFINES/setup.dm
+++ b/__DEFINES/setup.dm
@@ -1,6 +1,6 @@
 //This file was auto-corrected by findeclaration.exe on 25.5.2012 20:42:31
 #if DM_VERSION < 511
-#error Your version of byond is too old, you need version 511 or higher
+	#error Your version of byond is too old, you need version 511 or higher
 #endif
 #define RUNWARNING // disable if they re-enable run() in 507 or newer.
                    // They did, tested in 508.1296 - N3X
-- 
2.11.1.windows.1


```

**Comment by PJB3005** [comment]
PR it yourself you meme.

**Comment by SysadminJeroen** [comment]
Fine, I will.

**Comment by SysadminJeroen** [comment]
#14663

**Pull request merged**
