### PR TITLE
why the fuck did I do this?

### PR DESCRIPTION
**Pull request by TheEaterOfBeans**
why?

### CODE REVIEW

**Comment by TheEaterOfBeans** [comment]
this PR is bad

**Comment by DeityLink** [comment]
Honestly I think more of greyshits than clowns when I hear space asshole.

**Comment by TheEaterOfBeans** [comment]
this PR is bad

**Comment by DeityLink** [comment]
The best clowns I've seen were not being shitters so that's not my experience.

**Comment by Eneocho** [comment]
If nothing else, the clown holiday would be "Honkmother's Day", not Space Asshole's day. SA is more a greyshirt than a clown.

**Comment by Kurfursten** [comment]
Two weeks and you couldn't find even one other person who likes this idea?

It's just kinda eh.

**Comment by Kurfursten** [comment]
Why not I guess? Maybe this will be your gateway to coding something a little more meaningful

Updated your CL for clarity

**Comment by TheEaterOfBeans** [comment]
this PR is bad

**Pull request merged**
