### PR TITLE
Less Annoying Tail Surgery

### PR DESCRIPTION
**Pull request by 13spacemen**
amputate tail:

- hemostat to clamp vessels
- saw to cut off

attach tail:

- retractor to prepare area
- attach tail/robotail

## Why it's good
Less intrusive

## Changelog

:cl:
 * tweak: Tail amputation is done with hemostat + saw, tail attachment with retractor + tail

### CODE REVIEW

**Comment by DrSnips** [comment]
How would you ever know that you should be on an intent to preform this surgery?

**Comment by 13spacemen** [comment]
@DrSnips how would you ever know how to do half the stuff on /vg/? checking the wiki

**Comment by PrimeDSS13** [comment]
not in line with the other surgeries

**Comment by DrSnips** [comment]
It's a design choice I personally hate and I also hate that it's perpetuated without a good justification.
No other surgery depends on an intent. So rather than finding a way to differentiate the type of surgery it's a snowflake method. I could at least interpret that a tail connects to the groin area and I could poke with various tools but I would never happen upon the guess to use an intent.

**Comment by west3436** [comment]
Can you please just make it either only give a popup on the first action or just have a totally unique set of surgery steps in the groin?

**Comment by falcon2346** [comment]
Just make it like: scalpel to start the incision, saw to remove the tail. There, unique from surgery. 
We don't need to have intent based surgery for this one feature

**Comment by 13spacemen** [comment]
ok intents are removed, made a specific tail surgery which doesn't interfere with any other surgeries

**Pull request merged**
