### PR TITLE
[Bugfix] Fixed temperature gun projectiles that weren't moving

### PR DESCRIPTION
**Pull request by DeityLink**
bleh

### CODE REVIEW

**Comment by Intigracy** [comment]
You should just double check all OnFired()'s :^)

**Comment by DeityLink** [comment]
@Intigracy 
I did, that was the last one.

**Comment by Shadowmech88** [comment]
Does this also fix wizard fireballs and xeno queen neurotoxin? Both of those were having this same problem.

**Comment by DeityLink** [comment]
@Shadowmech88 Wizard spells were fixed over a week ago, Xeno queen neurotox was fixed a few days ago.

**Comment by PJB3005** [comment]
Put a fixes X in there so it autocloses.

**Pull request merged**
