### PR TITLE
Better tracking implant locator

### PR DESCRIPTION
**Pull request by DeityLink**
image
better

implants that are no longer in their original mob/that are in a dead mob will show in red/dark

:cl:
* rscadd: The Tracking Implant Kit now contains as well a tracker holomap, allowing you to easily keep track the implanted individuals on the current Z level.

### CODE REVIEW

**Comment by SonixApache** [comment]
good content
good shit
good good good

**Comment by GreatBigFailure** [comment]
Makes me wonder why I never see sec putting trackers in their officers. This is really useful.

**Comment by DeityLink** [comment]
I might do some polishing when I get home tonight.

**Comment by tuypo1** [comment]
I prefer the current one, it's more of a game

**Comment by DeityLink** [comment]
@tuypo1 this doesn't replace the current one, both locators are in the kit. The holomap one doesn't give you the ID of each marker either.

**Comment by tuypo1** [comment]
>The holomap one doesn't give you the ID of each marker either.

I suppose that's a fair trade off then, and this way when I am just messing with greytide I can take the weaker locator to keep things interesting and grab the more precise tracker when actually important shit is happening

**Comment by DeityLink** [comment]
image
done with the polishing, the holomap now properly updates every process(), with markers smoothly updating their location as on uniform holomaps. Also changed the color scheme to a more reddish appearance since it's a sec holomap.

**Comment by DeityLink** [comment]
I'd like to point out that Travis has completed successfully despite the "Some checks haven't completed yet" message. 
image

**Comment by DamianX** [comment]
This is fine though I'm not a fan of the prisoner management console being left shitty and untouched.

**Pull request merged**
