### PR TITLE
Aliens no longer take double burn damage

### PR DESCRIPTION
**Pull request by unid15**
They're a total joke right now ;

### CODE REVIEW

**Comment by SkowronX** [comment]
:+1:

**Comment by PJB3005** [comment]
:+1:

**Comment by clusterfack** [comment]
Immune to electricity when

**Comment by Probe1** [comment]
:+1:

**Comment by Ephx1** [comment]
But clusterfack, that's the highlight of a xeno round for me as AI, zapping clueless xenos with doors.

**Comment by Probe1** [comment]
sadly we have to give in somewhere @ephx1 because xenos get rolled every time.

**Comment by Ephx1** [comment]
No worries, I'll just have to practice my doorcrushing skills instead.

**Pull request merged**
