### PR TITLE
Colorblind preset for goonchat, gives non specific radio a different color.

### PR DESCRIPTION
**Pull request by eplgr**
It *works* on my machine. But I have no idea if all of the stuff I added was actually needed. The thing is that I had to make the common channel a separate channel from the radio channels, which was not the case before.

### **UPDATE: this now changes the chat palette to be colorblind friendly.** 
With a new preset.

# Explaining
~~The reason and purpose is to properly identify other channels that are not the `common` one more easily.
Orange is basically the only color left to use.~~
Tweaks so that colors are now colorblind friendly. Also, separates the radio colors from the Common radio color, explained above.

# In-game changelog
:cl: 
 * rscadd: Added colorblind preset for goonchat (you can find it under the chat's configuration button along with the other options)
 * rscadd: Common and radio channels now have different colors: common kept the green, radio is now orange.

### CODE REVIEW

**Comment by eplgr** [comment]
I don't know why the tabs are fucked up.

**Review by Probe1 — APPROVED** [review]

**Comment by PJB3005** [comment]
While we're at it could we make engineering a more distinct color, I'm not sure whether it's my color deficiency or not but I can't keep them separated.

**Comment by eplgr** [comment]
@PJB3005 engineering's color is way more dim and brownish, but I'll see what I can do in a few hours when I get back.

**Comment by PJB3005** [comment]
I meant between common and engineering, at a glance I flat out cannot see the difference other than the [engineering] tag.

**Comment by Exxion** [comment]
Oh.
Yeah they're completely different if you're not colorblind

Which is not to say they shouldn't be changed, because why make things harder for colorblind people?

**Comment by PJB3005** [comment]
Should probably just give goonchat multiple color pallettes.

**Comment by N3X15** [comment]
Yeah, just have a Javascript fragment fuck with the CSS.

**Review by PJB3005 — APPROVED** [review]

**Comment by eplgr** [comment]
Heavily updated the aim of the PR.
Also, suggestions are welcome but before posting I'd suggest you give http://safecolours.rigdenage.com/colourchoice.html a read.

**Comment by PJB3005** [comment]
The problem is that my type of color blindness is one type of color blindness, you may have made it better for me but you may have ruined it for somebody else and we wouldn't know.

We need user selectable palettes.

**Comment by eplgr** [comment]
@PJB3005 This should work for *everyone*. I don't even know the type of color blindness you have.
Just think of any other game: they offer just 1 colorblind mode for a reason.

**Comment by PJB3005** [comment]
I think most games offer just 1 colorblindness mode because it'd be effort to implement and not worth dev time OR it's simply not something that matters as much.

**Comment by SonixApache** [comment]
Battlefield series from 3 onwards offers like 3 modes.

**Comment by PJB3005** [comment]
I'm working on a color preset switcher for goonchat, only need to test it now which involves the dreaded recompile.

**Comment by PJB3005** [comment]
https://github.com/eplgr/vgstation13/pull/2

**Comment by Shadowmech88** [comment]
So does this mean players will have the option to keep their chat colors as they are now?

**Comment by PJB3005** [comment]
@Shadowmech88 yep.

**Comment by eplgr** [comment]
I think this is ready to go.

**Comment by eplgr** [comment]
Well, wait, it seems I still need to tweak some things.

**Comment by eplgr** [comment]
Done, also updated OP's screenshot.

**Pull request merged**
