### PR TITLE
Medicalconstruction

### PR DESCRIPTION
**Pull request by Kurfursten**
I already made the joke that this was a bug fix once but let's do this changelog again in that format just for humor posterity.
- Fixed a bug where you couldn't construct or deconstruct the Sleeper, Full Body Scanner, Operating Table, or Morgue Tray
- Fixed a bug where you couldn't invert the direction of the Sleeper, Full Body Scanner, or Morgue Tray
- Fixed a bug where the circuitboards and designs for the Sleeper and Full Body Scanner did not exist.
- Fixed a bug where the Sleeper and Full Body Scanner did not benefit from component upgrades.
- Fixed a sprite issue where the Full Body Scanner and Morgue Tray had no opposite facing sprite.
- Fixed a map issue where Full Body Scanner Consoles and Sleeper Consoles appeared on the map.
- Fixed a bug where Full Body Scanners and Sleepers did not automatically generate their own consoles.

+Fully tested
-Only fixes boxstation. But having extra consoles is harmless.
-Voice detection non-functional

I'll get it all fixed before the Feature Freeze ends.

new menu

### CODE REVIEW

**Comment by clusterfack** [comment]
Did you... unspan all the messages?

**Comment by Kurfursten** [comment]
It appears that happened, though I don't recall doing it.

I'm blaming ghosts.

**Comment by DeityLink** [comment]
merge conflicts

**Comment by Kurfursten** [comment]
@DeityLink I expected this would happen, mostly because of map changes while waiting for feature freeze to end

**Comment by Kurfursten** [comment]
Conflicts resolved by deleting boxstation, surely this will solve everything

Apparently I lost some other files too. We'll see what we can do about that tomorrow.

**Comment by Kurfursten** [comment]
Having trouble resolving map issues; instead of playing back the head and trying to resolve the map conflicts and merge conflicts at the same time, I'm going to start fresh and import the code.

**Comment by DeityLink** [comment]
I've been there

**Pull request closed without merging**
