### PR TITLE
Cult EMP rune buff

### PR DESCRIPTION
**Pull request by brndd**
It was suggested in #22576 that making the EMP talisman stronger would be preferable to letting cult stun mechs. I don't really think cult *needs* to be stronger against mechs, but I do think cult being able to stun mechs is a little silly, so here's an alternative solution.

The EMP talisman now does three EMPs in one use, spaced two seconds apart. There's room for tweaking here: it could eg. only be two EMPs, or the delay could be three seconds. Let me know what you think. As a reminder, cult EMPs have a heavy range of 1 tile (this is where the EMP deals full damage) and a light range of 3 tiles (this is where the EMP deals half damage).

The reason I went with a series of EMPs was that there's not really a good way to make a single EMP stronger, things tend to be somewhat balanced against ion rifles when it comes to EMPs (eg. a magdump of 10 shots from an ion rifle is enough to take out a Durand -- stun talismans currently are as strong as a single ion rifle shot, meaning it will take about 10 of them too), and this way there's some counterplay because eg. silicons may be able to avoid the second and third pulse if they run away, while slower mechs will have a more difficult time.

:cl:
 * tweak: Cult EMP rune (Pulse) now creates a series of 3 EMPs spaced two seconds apart.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
But EMP talisman does jack against mechs and there's a chance mechs won't stay near or adjacent the EMP rune
Full-power EMP takes half of the current battery charge and deals 50 damage
Personally I think the real cult killers are phazons, and they can noclip through walls

**Comment by Caboozles** [comment]
So if I'm getting this right, in essence it'll take a bit more than 3 paper-runes to kill a durand? If so, I think this is a pretty okay buff. It'll also be really good at disabling sec's tasers and such because of the rapid fire.



And I don't think we should be thinking of this as a deathmatch gamemode again. If a Roboticist is building Phazons, convert him. Make them yours.
There literally has not been a single round with a phazon in which the cult didn't autismcorner on their own and act surprised when the half of the station they didn't touch ends up spelling their demise.

**Comment by brndd** [comment]
> So if I'm getting this right, in essence it'll take a bit more than 3 paper-runes to kill a durand?

Yes, assuming all the EMPs hit perfectly. This also gives the EMP spell a secondary area denial ability, sort of, especially if produced en masse.

**Comment by Hoshi-chan** [comment]
This is bad theorycrafting. Nu-cult EMPs were never intended to be used on mechs, they were intended to be used on downed officers and the like to shut their SPS off and drain their weapons. It doesn't matter how many EMP pulses you attach to the rune, it's still useless against mechs because the mech just moves the fuck off the tile and it's useless.

If using the "stun" rune on mechs bothers you, remove the stun interaction for mechs and borgs from the stun rune and move it to the pulse/EMP rune instead, so that slapping borgs or mechs with a talisman will shut them off for a while.

**Comment by DrSnips** [comment]
I'm just going to repeat what I said before. Mechs shouldn't have an instant counter (read: stun) where you completely stop a mech with a single action. Mechs cost a good amount of time and resources and saying they should be just as weak and vulnerable as a person not in an expensive exosuit is wrong.

**Comment by brndd** [comment]
Mechs are pretty slow. If you use this in melee range of them, I don't think they're going to be able to avoid all of the EMPs by just walking away.

**Comment by iFlashYou** [comment]
They will maybe eat one emp but then you are dead.
Better would be to make the emp talismans ranged so you can use it inhand to have the emp around you or click stuff further away so the emp gets generated around them

**Pull request merged**
