### PR TITLE
Nerf showers

### PR DESCRIPTION
**Pull request by yackemflam**
Make showers not the best option when cleaning yourself

:cl:
rscadd: Water pressure was reduced

### CODE REVIEW

**Comment by salamandooo** [comment]
Why do the people that need showers the most always hate them so much

**Comment by boy2mantwicethefam** [comment]
Pretty okay considering it's part of the "stop making cleaning so easy" thing, but you should increase the chance to 10% per tick because right now it'd take roughly 40 seconds of sitting under a shower to clean up

**Comment by MadmanMartian** [comment]
Soap should give a bonus chance

rubber ducky too

**Comment by DrSnips** [comment]
For what purpose?

**Comment by ghost** [comment]
there are a few reasons I could assume you would want to do this but:

1. You should tell us your specific reason as it will make it more likely to pass
2. You can instantly clean anything that isn't plasma with a spray bottle of space cleaner

**Comment by yackemflam** [comment]
Theyre too strong in a myriad of ways from cleaning all of the blood off of you in basically 1 tick to ghetto cryo to ghetto warmers to slipping(no one really uses this though tbh, but it does show that theyre super strong compared to anything else that just cleans)

**Comment by Gazathor** [comment]
sooo... the issue is that a shower cleans too fast? why exactly is this an issue. have you had a situation where a man cleaning his clothes off real fast has changed a situation?

**Comment by ghost** [comment]
This is a poor solution to the problem you're presenting because there's still other methods that clean even more efficiently. If you really want to make it more difficult to clean stuff then you should address all of these methods and balance them accordingly. Maybe add more depth to how staining works so that you can have different degrees of staining (ie. more reagents/blood increase the stained-ness) that progressively more cleaning to wash out.

**Comment by Exxion** [comment]
>slipping

Most other things that clean do a better job of slipping than showers do

**Comment by bathosbathtime** [comment]
Update the comment right above about the percent chance per tick.

There are also better methods for doing everything you just mentioned, including cleaning, so I am not convinced this is needed. Except maybe ghetto-warming, I am not sure how fast that works. Then again, warm water is a good way to heat something as water has a high heat-capacity so it makes sense hot showers would warm you quickly.

**Comment by jknpj** [comment]
I don't get why this is an issue.

**Comment by ArchSunder** [comment]
what extremely specific occurrence with a shower had a negative impact on your round leading to the creation of this PR

**Comment by Zth--** [comment]
holy

**Pull request closed without merging**
