### PR TITLE
[BOX] Make the Vox trading post actually usable as a trading post

### LINKED ISSUE #2951: Vox trading floor is not practically and safely usable.
Unless I'm an idiot and missed something, there is no (practical) way to use the trading floor on the Vox trading post. Even opening a window over a table between the trading floor and the actual Vox area for a couple seconds will transfer enough air to render the Vox side uninhabitable to Vox until the atmos system cleans out the oxygen (which it doesn't even do by default). The Vox could just don suits before engaging in trading and wait out the decontamination afterwards, I suppose, but it takes several minutes and the doors cannot be opened without contaminating the entire outpost. It seems much more practical to just make a proper airlock between the two sides and ditch the table system entirely. That or make the processing room much smaller, give it more scrubbers, and label the doors in a way that suggests they should not be opened while trading is in progress or afterwards.

EDIT: Since it's not that hard a fix, it would probably make a good first contribution. If nobody replies to this or something in a few days, I'll just fix it myself. I'd go ahead and do it, but I'm too busy and probably will be for a few days.

### PR DESCRIPTION
**Pull request by Exxion**
So, the trading area of the Vox trading post was previously... a bit odd. It was impossible to move anything from one side of the wall to the other without contaminating the entire trade processing room with filthy oxygen.
image
Notice how all doors are single doors.

This was annoying, at least to me. So I fixed it.
image
Items can simply be thrown through the airtight flaps onto the table opposite each chair.
The airlock at the top is... a bit of a bad method, I admit, but airlock controllers don't appear to support movement between atmosphere types, just atmosphere and vacuum. That airlock is really just two doors set to close quickly with a scrubber and vent between them. It does seem to work well enough to prevent contamination of the processing room, though, at least with reasonably low usage.
Oh, and there is one change in the vault room just above the screenshot. I had to rearrange the pipes slightly, so now the vent in that room is fed from the hallway beside it rather than the processing room.

Fixes #2951

### CODE REVIEW

**Comment by SkowronX** [comment]
Confrictu

**Comment by Exxion** [comment]
I don't know enough about Github to really know what that means, but it seems odd, given that I only changed 72 lines in one of the most neglected parts of one file.

**Comment by Duny-** [comment]
dmms are shit, welcome to mapperbus.

**Comment by Exxion** [comment]
I found the conflict and I want to punch whoever made this save format

**Comment by Exxion** [comment]
Fuck. I did not mean to do that.

**Comment by Exxion** [comment]
Well that was moderately ridiculous, but look! No more conflict and I didn't accidentally undo every commit from today!
The fire safety closet in the processing room is gone now, but a fire can't really happen there anyway.

**Comment by Angelite191** [comment]
Oh man, Watching these commits are like looking in a mirror. Also, you get my approval.

**Comment by Exxion** [comment]
FUCK. MORE CONFLICTS.
Give me e moment.

**Comment by Exxion** [comment]
Oh god what the fuck did I do

**Comment by Exxion** [comment]
I fucked my branch beyond repair. Let me reopen this.

**Pull request closed without merging**
