### PR TITLE
Bar Sign Refurb Pack I.I

### PR DESCRIPTION
**Pull request by MintyEtude**
Remake of #28788 because I was defeated by conflicts. I will have my revenge another day.
Woah! 4 old bar sign sprites [sprites] that had the happy default dorfy-man now are gonna get new sprites [sprites]! Two of them are even of particularly high-effort! Isn't that cool? AND THAT'S NOT ALL: these sprites that have been touched now also have descriptions so it's less boring to look at them. Wow! (what do you mean, it's unatomic? what do you mean, bay licensing?)

https://user-images.githubusercontent.com/17928298/107073183-ca965480-67c5-11eb-83b4-76d08a8982af.png

:cl:
- imageadd: Some old bar signs [Saucy Clown, Clown's Head, The Damn Wall, Limbo] have been refurbished with shiny new neon tubing. Take a look around your local establishment next time the rest of the crew gets stone drunk off whiskey and starts blasting ancient showtunes throughout the station.

### CODE REVIEW

**Comment by MintyEtude** [comment]
I'll figure out the cool kids way of solving confliggs next time I swear

**Comment by MintyEtude** [comment]
WAIT DON'T MERGE IT YET I HAVE TO DO SOMETHING

**Comment by MintyEtude** [comment]
OKAY NOW YOU CAN MERGE IT (after the checks pass)

**Comment by MintyEtude** [comment]
WAIT NO

**Comment by MintyEtude** [comment]
THIS TIME FOR SURE (checks will pass)

requesting speedmerge to free me from my torment

**Comment by SonixApache** [comment]
incorrect :cl: syntax, replace with this
```
:cl:
- imageadd: Some old bar signs have been refurbished with shiny new neon tubing. Take a look around your local establishment next time the rest of the crew gets stone drunk off whiskey and starts blasting ancient showtunes throughout the station.

**Comment by MintyEtude** [comment]
> incorrect 🆑 syntax, replace with this
> 
> ```
> :cl:
> - imageadd: Some old bar signs have been refurbished with shiny new neon tubing. Take a look around your local establishment next time the rest of the crew gets stone drunk off whiskey and starts blasting ancient showtunes throughout the station.
> ```

oh right i just copypasted the thing i'll fix it right quick

**Comment by Kurfursten** [comment]
If you ever remake a PR, link to the old one in the OP

**Pull request merged**
