### PR TITLE
Defficiency Maintenance [redy 4 merge]

### LINKED ISSUE #8835: Why is there a Biohazard warning under a table in the Ghetto Library of Defficiency
Why is it there

### LINKED ISSUE #9903: Deff Tcomms
(WEB REPORT BY: tifora REMOTE: 172.93.109.202:7777)
Defficiency's Telecommunication air alarm is improperly configured. It is not set up as a cold room which means there is a permanent air alarm activated all round.

### LINKED ISSUE #9967: [Deff] No O2 canister in EVA, but there still is a N2 canister somehow
I would think that no O2 canister is calculated shittiness if not for the N2 canister right there
Gas the Vox, or don't gas anyone

### LINKED ISSUE #10036: Thrown Trash stays on station z-level
Henk

### LINKED ISSUE #10395: The Deff outpost Eng Vend doesn't work  even if you have Vox access
(WEB REPORT BY: durgen REMOTE: 172.93.109.202:7777)
plz fix

### PR DESCRIPTION
**Pull request by Konater**
removes that one unshielded area decal from the derelict library, fixes #8835
adds firefighter helmets everywhere there's a firesuit, fixes some issue an anon posted on thread
adds an oxygen canister and metal to eva at the cost of two suits, fixes #9967
adds gavel and block to courtroom
adds shower curtains to the shower room and perma
adds a vault locker to the armoury
combines a few dorm rooms to become a shared dormitory so I have an excuse to add curtains
adds curtains to the theatre at the cost of the windows
replaces the telecomms floor with the floor used in tgstation that was varedited to start out cold so the air alarm doesn't go off, fixes #9903
adds an electric chair to the execution room
moves those grilles out in space so that they don't block the disposals mass driver, fixes #10036
removes the access requirement from the vox outpost engi vend, oops, fixes #10395
moves those fucking disposal windows in cargo up a tile so trash doesn't hit them
adds bar stools to the bar
since floor decals can't be pixel x'd I've moved all of the unshielded area decals onto walls
replaces the red border floor tiles I missed in the right of the picture
fixes the hos privacy shutters not blocking sight when closed
adjusts the areas in perma so that half of the sleeping quarters aren't maintenance/derelict
replaces the airlock controller to get into perma with a flasher because it didn't work

theatre and dorms

minimap - https://drive.google.com/file/d/0B_Bv_tVbIjxddUlMdTJwS1NoTjg/view?usp=sharing

### CODE REVIEW

**Comment by Probe1** [comment]
I should just come out and say it at this point.  I've kept my mouth shut because god I don't want to deal with it.

All the radiation signs in Deff maint have bad var alignments.

**Comment by Konater** [comment]
fuck that I don't want to deal with it either

**Comment by Probe1** [comment]
They're all on the floors instead of the walls and it looks awful.

Its not in the scope of this PR but one day we will have to align them to the walls.

image

That one outside the library is how the ENTIRE MAP is

**Comment by Intigracy** [comment]
I'll do it after this is merged if he doesn't.

**Comment by Konater** [comment]
I did it so that intigracy has more time to finish antag datums :tada:

**Pull request merged**
