### PR TITLE
APA

### PR DESCRIPTION
**Pull request by kilkun**
-added new armor, advanced power armor

-adminbus only
-replaced heavy armor

-removed reference to heavy armor from spawners.dm

-added APA sprites

needs to be given a good home, was planning on making it cost 40tc and giving it to the syndies.

Maybe lower stats and hand off to syndicate black ops as the standard armor to match the new and improved swat suit deathsquad has.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>90 resist to lasers

>buy single suit

>send in op with suit on

>immune to all of security's guns

**Comment by kilkun** [comment]
There are shotguns in the armory. If sec cant walk two tiles over to grab a
shotty or have rnd build smgs, then thats secs fault.

40 telecrystals is a fucking rip off for a superslow bit of armor that has
some bullet protection, no temp or heat or pressure protection and takes up
your back and belt slots.

**Comment by FudgePucker** [comment]
You are under estimating the power of stun proof.
You still have hands, just carry the gun you get at round start with you and shoot them, if you hit them before getting hit by a shell, they get knocked down instantly and stunned so that you can knock them into crit.
Also, science won't have diamonds by the time new cops hit the station.

**Comment by Exxion** [comment]
I could be mistaken, but I don't think that's what slot_flags does

**Comment by kilkun** [comment]
>I could be mistaken, but I don't think that's what slot_flags does
That's what I was told they did. If not, I'll write a snowflake system for it because nothing else exists.

>You are under estimating the power of stun proof.
It's not stun proof, it's taser and egunproof.

Beanbags, all types of batons and flashbangs still stun. Might change that last one though.

And again, for 40tc, it's going to be the ONLY thing ops could buy. On top of being extremely susceptible to flamethrowers, vacuum and overpressure, it slows you down to a crawl. People in NT softsuits with magboots turned on move faster. 

This means ops will only have their knockdown smgs, two eguns, their hardsuits, and one op wearing this thing. For 40 tc it NEEDS to hit hard and it NEEDS to be worth it.

It's not a balance issue if security is too retarded to grab the beanbags. The point of adding new shit for antags is so that security has to respond by updating their tactics. What's the point of just adding in more shit sec can just tase, cuff and inject with polyacid?

>Also, science won't have diamonds by the time new cops hit the station.
Security has shotguns. They should learn to use them.

Might make ion rifles stun, but only after I'm completely sure what I want to do with it. Again, giving it to Ops as a 40tc super weapon was just a possibility.

**Comment by Iamgoofball** [comment]
I just remembered that you guys don't have scaling ops and scaling op TCs.

**Comment by Exxion** [comment]
slot_flags designates the slots an item *can* be placed in, not the slots it *always* takes up

**Pull request closed without merging**
