### PR TITLE
better icon for 'tgs' on changelogs

### PR DESCRIPTION
**Pull request by Intigracy**
:^)

old b4

new after

:cl:
- tgs: Added a better icon for TG ports on the changelog.

### CODE REVIEW

**Comment by kol1th** [comment]
go back

**Comment by optimumtact** [comment]
approved :+1:

**Comment by Zth--** [comment]
Memes

**Comment by 9600bauds** [comment]
It needs more Stan Rogers

**Comment by SkowronX** [comment]
No problem here.

**Comment by Iamgoofball** [comment]
agplv3 violation we're dmcaing you right now

**Pull request merged**
