### PR TITLE
Remove unused plugin system

### PR DESCRIPTION
**Pull request by DamianX**

### CODE REVIEW

**Comment by Probe1** [comment]
What was it ever used for?

**Comment by DamianX** [comment]
Added by N3X15 in 2015, never used for anything.

**Comment by Probe1** [comment]
Mighta been for [DATA EXPUNGED].

**Comment by DamianX** [comment]
Ah, indeed.

**Comment by Shadowmech88** [comment]
Could it have been used for something neat? I didn't even know it existed.

**Comment by Probe1** [comment]
Could have yes, was in the 3 years it existed no

**Comment by Shadowmech88** [comment]
Still, why remove it if it could potentially be useful at some point?

**Comment by DamianX** [comment]
Because it's useless code that we would keep running for no reason and it's trivial to re-implement if needed.

**Comment by Probe1** [comment]
_Next season on_

hoarders

**Comment by SonixApache** [comment]
SCP-VG
🤔

**Pull request merged**
