### PR TITLE
Remove flashbangs from the game.

### PR DESCRIPTION
**Pull request by ShiftyRail**
Flashbangs are by far the worst and most overpowered object of the game,
offering a 10*10 stun of over 15 seconds to most foes, while being
abundant and virtually inoffensive against the security officers who use
it.

Most importantly, they stun cyborgs, who are by far in need of buffs in
the current ss13 meta.

This change aims to restore an attempt at balance in the ss13 ecosystem
by simply removing flashbangs from the game.

:cl:

- tweak: Flashbangs have been removed from the game.

### CODE REVIEW

**Comment by Irradiation** [comment]
That's a very spicy PR you got there, frogman. The sec metaclub won't allow it.

**Comment by Ephx1** [comment]
April Fool's is shaping up to be really good.

**Comment by ShiftyRail** [comment]
@Irradiation As a man of principles I am ready to withstand any metaclub's wrath and fury

**Comment by MiniMeatwad** [comment]
i like this but i think flashbangs could be reworked instead

**Review by Durgen — COMMENTED** [review]
kek

**Comment by Chazach** [comment]
FUCK IT; KISSYOUR ASSES GOOD BYE CODE MEN! I AM SELFDESTRUCKTING THE GITHUB!!!!

**Comment by ghost** [comment]
I feel like this is a good start but it needs to be counter-balanced by removing more things.

**Pull request merged**
