### PR TITLE
Lamborghini Mob Update Icons [PHENOMENAL IMPROVEMENT]

### PR DESCRIPTION
**Pull request by 13spacemen**
0_iAtFOZfZYrLepZyG

## What this does
Removed the old "abstract overlay" objects, replaced them with byond's builtin /mutable_appearance

Replaced some icon procs with mutable appearances, like in update_hair()

Removed a lot of copypasta in update_icons, also made it more readable

## Why it's good

Much faster, I profiled it and it's 5x faster, probably more

## Changelog

:cl:
 * tweak: Mob icon updates should be much faster
 * rscadd: Monkeys rest and get up just like humans

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
what is the new speed of breathing air

**Comment by Eneocho** [comment]
thank you mr taint

**Comment by PrimeDSS13** [comment]
this PR accumulates negative energy in all of my chakras
(no clarification)

**Comment by MercuriusGH** [comment]
What color is your firebird?

**Comment by Eneocho** [comment]
Prepare for unforeskinned consequences

**Comment by SonixApache** [comment]
i don't get the jokes but this seems good

**Comment by SECBATON-GRIFFON** [comment]
also i hope this PR helps with adding replays to the game, heard the biggest roadblock is human appearance stuff

**Comment by Eneocho** [comment]
> also i hope this PR helps with adding replays to the game, heard the biggest roadblock is human appearance stuff

God, imagine being able to replay the game step by step, able to watch everything from every perspective.
See the jobby+ experience of the chemist making meds, or experience the seething rage of the greyshit that got shittered by birdsec.
I need it.

**Comment by incakola** [comment]
I was expecting a lamborghini mob based on title

**Comment by SECBATON-GRIFFON** [comment]
> God, imagine being able to replay the game step by step, able to watch everything from every perspective. See the jobby+ experience of the chemist making meds, or experience the seething rage of the greyshit that got shittered by birdsec. I need it.

i was imagining adding support to security cameras for it, like a recording system

**Comment by Kurfursten** [comment]
confl

**Comment by DeityLink** [comment]
Do we have some profiling anywhere with before/after comparison? So far the only thing I've observed is that photography is once again broken 
image

And that people show up bald on the round end scoreboard (and other html interfaces that display a flat version of a player sprite)

image

**Pull request merged**
