### PR TITLE
Adds Vox sprites for the Gumshoe alt-title's clothes

### PR DESCRIPTION
**Pull request by ghost**
A quick hack-job so that they aren't straight-up invisible.

image

[sprites]

### CODE REVIEW

**Comment by jknpj** [comment]
Do they even start with this instead of their suit? Monthy reminder that outfit datums could prevent this.

**Comment by ghost** [comment]
They don't, but I added the gumshoe stuff to the locker in another PR. In retrospect, I probably could've included this with it, but I avoided it because something something atomicity.

**Comment by Intigracy** [comment]
Adding a new clothing item with the sprites for individual races isn't unatomic though.

**Comment by ghost** [comment]
It was mostly because it was a seperate item from the one I was adding, so I wanted to be better safe than sorry.

I can go ahead and shove this into the other PR if it'd be A-okay, though!

**Pull request closed without merging**
