### PR TITLE
Fat Hardsuit Modkit

### PR DESCRIPTION
**Pull request by Kurfursten**
my response to #24745

The secvend now has a modkit that can turn your sec hardsuit into a fat-compatible sec hardsuit. But beware trying to wear a fatsec hardsuit if you aren't fat... to one so thin like a malnourished skeleton, the suit cannot form a perfect seal and it is basically useless because it leaks heat and biotic organisms. Regaining your fat will restore your suit's benefits.

🆑 
* rscadd: The secvend now has modkits to make your sec hardsuit into a fatsec hardsuit. Beware wearing this if you know the meaning of the word diet.

### CODE REVIEW

**Comment by SkowronX** [comment]
why not expand this so that future hardsuits can get fat versions

**Comment by Kurfursten** [comment]
I only have the one sprite right now so the others would be blank.

**Comment by SkowronX** [comment]
ughhh fine. be right back

**Comment by GermanSanta** [comment]
Wish I knew about this project a bit before it was merged... but my original plan was to give the security hardsuit a little extra boost to help balance the trash security hardsuit compared to that of other hardsuits as quoted. (Although I do find this as a good merge to find a middle ground for those who want to rp as fatsec and those who don't exactly agree with the security hardsuit buff)

"Engineering gets rad protection
Atmos gets 100% heat, fire, and plasma protection
Security gets donuts"

With all the issues of them not being able to tell cult members from crew in the third stage. To people cloning and copying themselves amongst multiple crew members. They have to decide to trust their instincts with a possible bwoink or do nothing and more and less fail. 

Therefore the best course of action is to do nothing and eat  So why not just let them get fat? If a greytide gets caught my a man in a fat security hardsuit that slows down after moving a few yards... well he should rethink his life.

All this aside,
The goal was to give the security hardsuit something unique. In order to balance security and the security hardsuit compared to the benefits of antags and other more useful/atmos hardsuits.

**Pull request merged**
