### PR TITLE
Adds a brute force melee weapon to combat borgs; the impact hammer

### PR DESCRIPTION
**Pull request by SonixApache**
🆑 
 - rscadd: Combat borgs now come equipped with a brute force melee weapon; the impact hammer.

### CODE REVIEW

**Comment by mtpowell** [comment]
ONE LITTLE NERF AND MY MOMMI GOT SCARED

**Comment by SonixApache** [comment]
my next PR is "makes all borgs a bit slower"

**Comment by Ephx1** [comment]
Don't they get the plasma cutter?

**Comment by SonixApache** [comment]
Plasma cutter is much a weapon as a welding tool is. It does decent burn damage, sure, but it's more intended for wall breaching.

**Comment by Blithering** [comment]
does it play a cuckoo sound on hit?

**Comment by SonixApache** [comment]
Plays a slowed down version of the slam-head-on-table sound. Why a cuckoo sound?

**Comment by Blithering** [comment]
hammer
Risk of Rain reference. HAN-D's hammer plays a cuckoo sound when winding up for a swing

**Comment by ghost** [comment]
>slight chance of drizzle reference

add in the commando's space suit next tbh

**Comment by Exxion** [comment]
It's like a whistle. Not really a cuckoo sound

**Comment by SonixApache** [comment]
@Blithering holy shit, that's supposed to be a cuckoo sound? I thought it was just generic robot noises.

**Comment by Blithering** [comment]
It always sounded like a cuckoo to me. For those who have no idea what we're on about, https://youtu.be/2fM89kQ4e7s?t=200 the sound plays a couple of times around that time

**Comment by Intigracy** [comment]
30 seems pretty high

**Comment by Intigracy** [comment]
Nvm the attack delay makes up for it

**Pull request merged**
