### PR TITLE
Coloured light tiles

### PR DESCRIPTION
**Pull request by unid15**
Since the previous functionality of light tiles being randomly broken or flashing was removed,

Allows using a multitool on light tiles to change their colour
Possible colours: white, light blue (default), red, green, yellow, dark blue, purple

### CODE REVIEW

**Comment by PJB3005** [comment]
yes please
:+1:

**Comment by ComicIronic** [comment]
But does their light color change?

**Comment by PJB3005** [comment]
Doesn't look like it

**Comment by Unfit** [comment]
Unless I'm doing this thing incorrectly, colourfully glowing tiles appear to be a bit bugged


Maybe once we get baylighting it'll get better

**Comment by FudgePucker** [comment]
Can you make it so that you can link the floors by multitool to a atmos automations computer? I want to be able to have a SME that changes color based on temp... And toataly not making strobe lights for my dance club.

**Comment by Unfit** [comment]
I'll try to add that

**Comment by FudgePucker** [comment]
Hell yea.
It might be hard to implement, but have it so that you can change colors and change power setting.
I love you dude.

**Comment by Unfit** [comment]
Yeah it'll take quite a while, because right now I barely know how multitools, buffers and atmos automation computers work. Also multitool menus only exist for machines and not items or turfs afaik, so it'll require some small rewriting.
I'll add it in a separate PR after this gets merged.

**Comment by PJB3005** [comment]
Yeah, multitool menus are /obj (/obj/machinery for MOST of the useful code though)

You could make them atom level I guess

**Comment by FudgePucker** [comment]
Oh yea, floor tiles are turfs not machines.
I hope it would be possible.

**Pull request merged**
