### PR TITLE
Expands Box Genetics to improve traffic

### PR DESCRIPTION
**Pull request by ValkyrieSkies**
Ssethbay has really made it clear just how fucking cramped cloning can get when bodies start piling up, especially when brainlet geneticists who are ignoring cloning entirely for 'muh powers' keep shoving their way in and out while other doctors are trying to save lives.

This change makes cloning larger to prevent the severe bottlenecking it often experiences and gives geneticists their own door to the rest of medbay to prevent them from making traffic issues worse.

[box] [tested]
:cl:
 * rscadd: Remodeled Box Genetics to make it less cramped

### CODE REVIEW

**Comment by DrSnips** [comment]
Can we make the middle airlock green because that one is medical access iirc.

**Comment by ValkyrieSkies** [comment]
Nah, it's medical and science; Genetics is technically a Research/Medical department so I wanted to keep the science access within the department, and cloning is technically part of that department.

The medbay-facing airlocks are green because they're medical only so scientists don't have a free backdoor pass to enter into medbay proper.

**Comment by strawberrytan** [comment]
they actually do if they can open the door to the cloner, since the button on the wall opens the door to medbay proper

**Comment by ValkyrieSkies** [comment]
Ah, good catch. I'll just make it a green door as suggested then.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Needs a potted plant for the clonejank aesthetic

**Comment by Hoshi-chan** [comment]
Do Cryo next.

**Comment by ValkyrieSkies** [comment]
Potted plants belong in corridors, civvie areas, and offices, not sterile medical environments tbh.

**Comment by ValkyrieSkies** [comment]
merge me fuckers

**Comment by ShiftyRail** [comment]
No other PR seem to be touching Box, so this is good to go.

**Pull request merged**
