### PR TITLE
Fixes dynmode problems

### LINKED ISSUE #29554: Nukies and blob rolled at the same time
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
88ffb70118d9dfc7d757e0d0ead628f9a8955a45

# Description
Ops + blob both at roundstart in a contested system, who the fuck thought this is a good idea

# Steps to Reproduce
Play game, expect to have fun

# What you Expected
To have fun
# What Actually Happened
I did not have fun and this is stupid

### LINKED ISSUE #29555: DYNAMIC IS FUCKED SOMEONE FIX IT
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
88ffb70118d9dfc7d757e0d0ead628f9a8955a45

# Description
duplicate of #29552 but with a better title

LOOK AT THIS:
Threat Log
Starting Threat: 55.0717, midround: 43.9724
12:05: Roundstart Vampires spent 15
12:05: Roundstart Blob Conglomerate spent 45
12:05: Roundstart Syndicate Traitors spent 10
Remaining threat/threat_level: 0/55.0717
Remaining midround threat/threat_level: 43.9724/43.9724

### PR DESCRIPTION
**Pull request by ShiftyRail**
The thing when you try to dynamic mode is that you can't be sure you took everything into account because it's so vast
I have no idea how threat counts were done before but I guess they're back now!

image

Closes #29555
Closes #29554

:cl:
- bugfix: Fixes things with dynamic mode

### CODE REVIEW

**Comment by DeityLink** [comment]
@Kurfursten made a spend_threat() proc, you might wanna use that instead.

https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/datums/gamemode/dynamic/dynamic.dm#L744

Also it's already being called in the executing_roundstart_ruleset() proc

https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/datums/gamemode/dynamic/dynamic.dm#L451

I'm not sure but this might lead to threat being deducted a second time after the fact.

**Comment by ShiftyRail** [comment]
Then why does it not work? 😔

**Comment by ShiftyRail** [comment]
Nevermind I get it

**Comment by boy2mantwicethefam** [comment]
Changelogs

**Comment by ShiftyRail** [comment]
it's just a bugfix

**Comment by DeityLink** [comment]
You removed the spend_threat() at line 447 but there's the one at line 452 to remove as well.

**Comment by boy2mantwicethefam** [comment]
Don't treat changelogs as tedious paperwork to fill out, treat them as your way to have a little fun. Sometimes just explaining what was wrong and what was fixed is amusing in itself. Give them the Sims 3 patchnotes treatment

**Comment by DeityLink** [comment]
This. Patch-notes are one of my favourite thing to do after a PR. Even if it's just a bug fix players like to know what went wrong.

**Pull request merged**
