### PR TITLE
Rogue Fabricators

### PR DESCRIPTION
**Pull request by MadmanMartian**
The Neo-Soviet MoMMI units, left for countless years to maintain a constantly degrading station, have found a new way of breaking their z-locks and programming, so as to proliferate.

The fabricator arrives through hiding within the midst of a meteor shower, colliding with the edge of an unknowing station, burrowing in like a tick, and beginning its programming cycle: Consume, Reproduce, Continue.

The end goal of a rogue fabricator is fairly open. Produce worker drones through the hijacked fabricator it is built around, produce more fabricators and advanced drones from the acquired metal, and break down the station until there is nothing left of use.

NEEDED:
 - Sprites [ ] (Please, my codersprites are horrid)
 - Drone subtypes
 - - Worker [ ]
 - - Guardian [ ]
 - - ???
 - Structures
 - - Energy syphon
 - - Mass recycler
 - - Meteor cannon

:cl:
 * rscadd: Adds the rogue fabricators

### CODE REVIEW

**Comment by ghost** [comment]
Call it the GrandMommi
Mommi - mother
Grandmommi - grandmother
this is basic shit robo

**Comment by RealestEstate** [comment]
I second GrandMoMMI

**Comment by tuypo1** [comment]
You may want to consider looking at TGs swarmers for ideas since it is essentially the same basic idea

**Comment by Blithering** [comment]
Sounds fun, will try spriting some tomorrow

**Pull request closed without merging**
