### PR TITLE
Snaxi 3: The Atmos One

### PR DESCRIPTION
**Pull request by Kharkov72**
Mostly just cleaning up pipes, ones that are facing the wrong way, ones that are missing connections, etc etc.
The most minor out of all of these so far.
Notably, this removes the pipes from the ghetto bar, because running pipes over there wouldn't make it very ghetto with how relatively far away it is. I WAS debating running in distro pipes from the backway, but eh.
[snowmap]
Update: Some actual significant changes:
-The yetis in the northern cave have been replaced by russians, as they are ROBUST as FUCK.
-However, they have not completely left the snow...
Untitled
-there are plans to flesh out the ice caves into a kind of labyrinth, but the focus is on stations for now
 
-Solar computers in the abandoned solar control rooms have either been removed or replaced with power monitor computers.
-There are now showers in all the front medical checkpoints, and the ghetto bathroom in the medical station has two showers as well. At this point, there are showers in dorms, perma, the ghetto bathroom, and the medical checkpoints, so that should be enough
untitled2

:cl:
 * rscadd: Snaxi pipes are less gunk.

### CODE REVIEW

**Comment by SonixApache** [comment]
did you fix the missing tiles under the doors that someone posted

**Comment by Kharkov72** [comment]
The one in telecomms, yes. If there are others, let me know.

**Comment by Kharkov72** [comment]
fuck you @MadmanMartian

**Comment by MadmanMartian** [comment]
I was pinged to merge it, what's wrong?

**Comment by ShiftyRail** [comment]
Merged too soon

**Comment by MadmanMartian** [comment]
image

**Comment by ShiftyRail** [comment]
I think there was a regrettable miscommunication between our snowmap mappers here

**Comment by plosky1** [comment]
Yes uhhhhh kharkov apparently was doing more while we were talking about some new stuff.

**Comment by MadmanMartian** [comment]
Okay, my bad

**Comment by plosky1** [comment]
Nah it's mine, I asked you to merge because I thought it was finished.

**Pull request merged**
