### PR TITLE
Bullet Storm

### PR DESCRIPTION
**Pull request by Shadowmech88**
volley_gun
I'll take a better sprite if anyone would like to offer one.

Adds the Bullet Storm, a single-shot non-reloadable volley gun that fires a wave of 100 pellets, each dealing 10 damage.
WebM of it in action: http://puu.sh/tRpal/da4441a016.webm

:cl:
 * rscadd: Added the Bullet Storm, a single-shot non-reloadable volley gun that fires a wave of 100 pellets, each dealing 10 damage.

### CODE REVIEW

**Comment by Exxion** [comment]
One *thousand* damage

The lag a mere 100 projectiles causes is a testament to BYOND's incredible optimization

**Comment by N3X15** [comment]
Needs to throw you backwards

**Comment by Shadowmech88** [comment]
I initially wanted to do 1000 projectiles at 1 damage each, but that really was too much for it to handle.

**Comment by Kitfox88** [comment]
Can't wait for this shit during a gunwiz round

**Comment by Exxion** [comment]
One shot. Twenty kills.

**Comment by calzilla1** [comment]
That's what i call a trick shot!

**Comment by PJB3005** [comment]
Electric glove whip when?

**Pull request merged**
