### PR TITLE
bully roundstart on april fools day

### PR DESCRIPTION
**Pull request by MadmanMartian**
On april fools, you won't know what mode it could be just from reading

:cl:
* rscadd: Adds new gamemodes, to prepare for antag datums

### CODE REVIEW

**Comment by Arthurdentist** [comment]
No Malcolm in the Middle?

Or everyone's favourite roundtype 'Six Hours extended with shuttle calling disabled'

**Comment by MadmanMartian** [comment]
you suggest them, I'll add them

**Comment by Blithering** [comment]
monkey madness added as a random event maybe? recruits a ghost for pun pun if he's still alive and the end begins from there

**Comment by jknpj** [comment]
add 'Nations'

**Comment by yclatious** [comment]
High RP Extended is the best mode 
:^)

**Comment by vampirebat74** [comment]
Baby's day out mode when

**Comment by DrSnips** [comment]
Dino wars

**Review by gbasood — APPROVED** [review]

**Pull request merged**
