### PR TITLE
BAWK

### PR DESCRIPTION
**Pull request by DeityLink**
Originally part of #4255 , I think I wanted to allow @d3athrow to automatically wear it if he used the "Spawn yourself as a Test Dummy" button. The head was never commit but I re-did it probably better.

image

image

image

:cl:
* rscadd: Added the white chicken suit I sprited back in 2015 and forgot to actually PR all this time. A single costume can be obtained from the AutoDrobe after inserting a coin.
* imageadd: Improved the chicken suit and head in-hand icons.

### CODE REVIEW

**Comment by Eneocho** [comment]
Add a small piece of paper or something that says you're the god of the station if wearing the pomfsuit.

**Comment by DeityLink** [comment]
I think the description on the suit is enough.

**Comment by Eneocho** [comment]
> 
> 
> I think the description on the suit is enough.

Fair enough.

**Comment by Eneocho** [comment]
There being only one chickenbox on the premium side of the autodrobe kinda goes against the current standard of there being 3 copies of the premium clothes.

**Comment by DeityLink** [comment]
The others will make do with yellow chicken suits. Or you can get an autodrobe vending pack.

**Comment by Eneocho** [comment]
There was that one thing with putting a human with a chicken suit on a food processor to turn em into nuggets, does the pomfsuit work too?

**Comment by DeityLink** [comment]
yes

**Pull request merged**
