### PR TITLE
Removes unused files

### PR DESCRIPTION
**Pull request by Iamgoofball**
Come on, I know ignoring The Goof(tm) is the hot meme and all, but stop leaving useless garbage in the files. Entire file is commented out.

### CODE REVIEW

**Comment by TheFriggenSawbones** [comment]
Hi goof, you're on the wrong github again. Let me help, https://github.com/tgstation/tgstation

**Comment by Iamgoofball** [comment]
Hi Sawbones, you're on the wrong github again. Let me help, https://github.com/Citadel-Station-13/Citadel-Station-13

**Comment by SonixApache** [comment]
good call tbh

**Comment by Intigracy** [comment]
Removing unused files is actually helpful though, as seen in the pr linked people sometimes edit the wrong file.

**Pull request merged**
