### PR TITLE
HoP Loyalty Implant

### PR DESCRIPTION
**Pull request by clusterfack**
Loyalty implant added to the HoP

### CODE REVIEW

**Comment by dylanstrategie** [comment]
:+1:

**Comment by Probe1** [comment]
why not?  the hop has extreme power thanks to the ID computer, is the natural second in command when a captain isn't there (something pomf has ruminated in the thread on and confirmed), and is a deadly enemy even more so than security when culted.

it's a good decision.  thanks for posting it in the thread for exposure.  I appreciate that almost as much as the change itself.

**Comment by VelardAmakar** [comment]
about time

**Comment by CptWad** [comment]
Dunno. Used to be the HoP was an arbiter between sec and the crew with lawyers.
Hops plays sec often so him having an implant in him makes less problems.
Also the antag selection should reflect this as HoP can be a starting cultist and giving him an implant will be bad news bears

**Comment by clusterfack** [comment]
Added suggestion to prevent hop from being a roundstart cultist.

**Comment by Kurfursten** [comment]
:+1: If IAAs have implants, why not the HOP?

**Comment by SarahJohnson489** [comment]
15/10, may get cultists to learn to remove implants and will kill the HoP's that just want more valids.

**Comment by Arthurdentist** [comment]
Im going to be a dissenting voice and say I don't agree with this change. The Head of Personnel should be staying as far away from Security Business as possible. Although he is Second in Command he is still on the same level as all the other heads and nobody is calling for the RD, CMO and CE to have Security Implants when they can be just as powerful and dangerous. 

If we look at who has security implants already, the Captain has one because he is the supreme authority on ship, the IAA are (allegedly) the direct link between Centcomm and the station and finally all the security members have them because they are, well security. 

The Head of Personnel isn't security. Although he is Second in Command he also isn't the 'Deputy Captain', he is the person in charge of the cargo and civilian departments not covered by the other heads and the person in charge of assigning people and moving them around. I already think too many people play the role as 'Almost but not entirely unlike Captain / Head of Security' and a change like this would only help to further encourage that. 

As a final note i'd also like to say I consider a Cultist CMO to be far more deadly then a Cultist HoP, any day of the week. Medbay Cult is the best cult.

**Comment by Probe1** [comment]
Those points made by Arthur are excellent and touch on the core issue of what role does the HoP truly play?  I feel that the way players approach the HoP role undermines his post, and that the reality of it means the HoP is more important than just another head whether we choose to accept it or not.  

HoP players that do not give themselves all access, put their egun in their backpack and treat themselves like princes who can interfere in any department with impunity, are rare.  IC or OOC intervention by IAA or admins is even rarer.  

Do we draw a line here and firmly restate that the HoP is not any different than the CE and despite having great power over access he should not be treated like the way we often treat him with special impunity?  If the HoP role is special and will remain special in the future, then an implant is the right course to take.  However if a real effort by players and staff is made to minimize the long accepted gameplay of the HoP and realign him to only be the Head of Civilians, then the implant is unnecessary.

A point of consideration not yet discussed is the HoPs access over the stations accounts and funds.  Would NT ensure that the person behind their entire payroll for the station is loyal to it?

**Comment by clusterfack** [comment]
I would also like to note that the distinction between the HoP, HoS, and Captain from the RD, CE, and CMO is that the former are all given weapons that have lethal capability along with armor and sunglasses and access to the sec channel, while the latter are merely given flashes to incapacitate rowdy workers.

**Comment by Probe1** [comment]
| >he thinks I don't use my flash to disable uppity mommis

I think that staff need to figure out where the hop is supposed to be.  We have plenty of evidence from players that play how they think the HoP should be played.  It's almost always at odds with Arthurs comment.  But Arthurs comment is also what the official description of HoP is supposed to reflect.  

You'll either have to enforce it, acquiesce, or delay any changes and keep a blind eye towards the position.

**Comment by PJB3005** [comment]
the HoP is more powerfull than the HoS in anything but name, merge this pls.

**Comment by Arthurdentist** [comment]
as far as cult rounds go, the most powerful cultist is the CMO cultist. Access to chloral for super easy conversions and far more trustworthy then the HoP who has no buisness being in chemistry or near it.

RD and Science Cult is also more powerful, access to all the fun toys and the science asteroid station which gives them plenty of amazing places to hide, places no one visits.

The head of personnel can do both of those things by giving himself access, but he is still the head of personnel, he has no business in either of those departments and so him doing anything in either of them is very suspicious. If you think the main issue at stake is the fact that the HoP is too powerful a cultist, then surely we should implant the CE, RD and CMO as well.

**Comment by clusterfack** [comment]
Whoops

**Comment by clusterfack** [comment]
I'm more focused on the lack of consistency with the role than I am about anything to do with "balance"

But in the end the only round this would really affect is cult, and while I dont think having a HoP as a roundstart cultist is overpowered, I dont think any cult should be able to get a direct line to everything said over security as well as all access by the conversion of one unimplanted individual.

**Comment by Hoshi-chan** [comment]
No.

And while you're at it, take the armored coat and energy gun out of his locker, and remove the security channel from his headset.

**Comment by Probe1** [comment]
i'd rather have that to be honest, and there was talk a few months ago about giving the hop a unique weapon like the detective to placate him for self defense.  but that hasn't happened so

**Comment by Boxe** [comment]
remove the armored coat and add a verb to the HoS coat that makes the icon cycle between nazi and jensen

**Comment by clusterfack** [comment]
It's not like I'm saying 'this will end the debate on what hop should be' if this gets merged or not, I'm just making him consistent with what he is right now. If someone else wants to modify what he starts off with after this, they are completely free to do so.

**Comment by CptWad** [comment]
I want to vote yes again.
Also Give him some antag protection. I am tired of seeing a hop ling or traitor kill everyone in the first half hour just because he can

**Comment by d3athrow** [comment]
ill run a month long vote

**Comment by clusterfack** [comment]
http://ss13.pomf.se/index.php/poll/31

**Comment by Probe1** [comment]
ay did you see me post that in an argument that pomf doesn't veto things the community wants and that the person in the thread was talking a lot of rot?

**Comment by clusterfack** [comment]
Not an actual compile failure you silly person we switched to vgstation13

**Comment by clusterfack** [comment]
I rebased this to show it's not a compile failure, tada. Now if this got any attention that'd be great.

**Pull request merged**
