### PR TITLE
Xenomorph inventory update.

### LINKED ISSUE #15650: Alien larvae's Hide power displays messages incorrectly
(WEB REPORT BY: panthid REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
de3bc7604a921b924c9e2297541ab4c9772d7c11

>General description of the issue
Use of the alien Hide power gives the name of the power, "hide" in the message instead of the alien's name.

>What you expected to happen
"Alien larva scurries to the ground !"
"Alien larva slowly peeks up from the ground..."

>What actually happened
"hide scurries to the ground !"
"hide slowly peeks up from the ground..."

>Steps to reproduce if possible
Watch an alien larva use Hide.

### PR DESCRIPTION
**Pull request by jknpj**
cuff larva stun larva

How it works, by @Intigracy 

How it actually works:
https://webmshare.com/KD5Xv

Closes #15650

:cl: 
 * bugfix: Fixes an ancient bug that prevented big xenos and larva from being handcuffed/bodycuffed. Big xenos can break cuffs as fast as a hulk while larva take the same amount of time as other carbons.
 * bugfix: Fixes an ancient bug that prevented xeno larva from being stunned.
 * bugfix: Also fixes larvae hide spell.
 * rscdel: Removes non-used head and chest slot from big xenos.
 * tweak: Big xenos and larva can't ventcrawl or evolve while cuffed.
 * tweak: Updates xeno inventory window.

### CODE REVIEW

**Comment by ghost** [comment]
Nice. Any chance of xenos ever getting real bodies for surgery, nuggeting for taming, and being allowed back into sleepers/cryo? We need absolute madmen RD's brainswapping officers into xenos even if it takes a high-tech xenos-man machine interface from anomaly/decon'd xeno limbs

**Comment by Exxion** [comment]
Yes.

A very, very slim one that is

**Comment by Shadowmech88** [comment]
What about grafting cybernetics onto them to make xeno slaves that follow silicon laws?
Niggly had some neat robo-xeno sprites.

**Comment by SkowronX** [comment]
What happens if a larva tries to evolve while cuffed?

**Comment by SkowronX** [comment]
Git gud larva scum

**Comment by PJB3005** [comment]
@SarahJohnson489 when you port it from Bay.

**Comment by N3X15** [comment]
* Adding [Balance] because xeno combat changes

**Pull request merged**
