### PR TITLE
Reverts energy swords cutting through walls and doors

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
I wince because it's some pretty terrible code, it's also never used in-game because few people know about it. Please God forgive me for making coding spaghetti
:cl:
 * rscdel: Melee energy weapons can no longer cut through walls and airlocks

### CODE REVIEW

**Comment by MadmanMartian** [comment]
Never forgive, never forgetti

**Comment by boy2mantwicethefam** [comment]
Glad you could bake it, Martini

**Comment by brndd** [comment]
R-word?

**Comment by SonixApache** [comment]
this kills the ninja

**Comment by SirSkeleto** [comment]
just refactor it if you don't like how it looks

**Comment by boy2mantwicethefam** [comment]
It's pretty clunky too, r-walls can't be punched through because ??? but hulk works perfectly fine

**Comment by PrimeDSS13** [comment]
this is a nice feature though, just rewrite the code.

**Comment by ghost** [comment]
testmerge when

**Comment by boy2mantwicethefam** [comment]
17 downvotes, now it's a fair fight

**Comment by Zth--** [comment]
It's dead, Jim

**Pull request closed without merging**
