### PR TITLE
Letting you move in space around blobs

### PR DESCRIPTION
**Pull request by DeityLink**
Since blobs had to be made not dense, and that harmless blobs from blob clusters are now a relatively common thing, this should help people move around the blob as they remove it.

### CODE REVIEW

**Comment by 9600bauds** [comment]
I figure this is a good place to ask, is there a way to call locate() with multiple arguments?
i.e. locate(table OR chair)

**Comment by DeityLink** [comment]
@9600bauds http://www.byond.com/docs/ref/info.html#/proc/locate

and no

**Comment by ComicIronic** [comment]
Aren't blobs required to be on turfs?
Also, this doesn't really make sense, because you can't touch the blob in the first place to use it to move around.

**Comment by 9600bauds** [comment]
I did check the F1 dreammaker menu but that's not known for being complete or helpful

**Comment by DeityLink** [comment]
@ComicIronic Blob can spread over space just fine, albeit more slowly. I wrote a wall of text to explain the change to clusterfack. With the blob clusters coming like meteors, once the nodes have been taken care off all that's left is to clean up all that green harmless biomass. And forcing people to throw items/carry a fire extinguisher to do it is just bad design.

Again, it's the intended behaviour.

ps: space tiles ARE turfs.

**Comment by Imagebard** [comment]
>Blob can spread over space just fine, albeit more slowly

Which is why the space blob meteor event is pretty shitty unless you're a veteran blob: You're beyond vulnerable to space-side attacks.

**Comment by Exxion** [comment]
@9600bauds 
No, but iterating through the thing you're trying to locate things in and checking the type is faster than `locate()` anyway, or at the very least used to be

**Comment by DeityLink** [comment]
@Imagebard There are two space meteor events. The first one (which will fire the most often) doesn't have any overmind, so that concern is unwarranted. And even then what does this have to do with fixing a bug?

**Comment by FudgePucker** [comment]
without oxigen blob don't evoluate

**Comment by ComicIronic** [comment]
@clusterfack

**Pull request merged**
