### PR TITLE
Roach farms can now make up to 100 cockroaches instead of just 50.

### LINKED ISSUE #34060: Buff roach farms
Roaches are capped at 50 alive per world or z-level, before they stop hatching from eggs. 50 is pretty low on the scale of fun. I get why there can only be 50 space carp in the world for carp farms but 50 roaches feels a bit restrictive.

### PR DESCRIPTION
**Pull request by Eneocho**
### What this does
Cockroaches now have an extended child cap of 100, double the previous value.
Closes #34060
### Why it's good
Factory farming cockroaches, gunk burgers eaten across the cosmos.
[tweak]
:cl:
 * tweak: Extends the child cap for cockroaches to 100, from 50.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
I hate them

**Comment by Eneocho** [comment]
> wotisJANITOR hates cockroaches

the gunkbros will NEVER bend the knee to the janny

**Comment by calzilla1** [comment]
More like wotistranitor

**Comment by angryturnip** [comment]
Next make it 1000

**Comment by Killette2** [comment]
I can confirm that this cap spreads across all Z-levels currently. There was too many roaches at the pod drive in that I couldn't spawn a single 1 on the station.

**Pull request merged**
