### PR TITLE
Everyone on castle is a survivor

### PR DESCRIPTION
**Pull request by ShiftyRail**
I blame Barry for this.

:cl: 
- rscadd: Everyone on Castle station starts with the survivor role.

### CODE REVIEW

**Comment by ghost** [comment]
You okay, bud?

**Comment by ShiftyRail** [comment]
http://ss13.moe/forum/viewtopic.php?f=18&p=33268#p33268

If we're going to have to deal with this on a semi-regular basis, might as well cut the red tape entirely.

**Comment by boy2mantwicethefam** [comment]
What can I say except you're welcome?

**Comment by boy2mantwicethefam** [comment]
If you're going with this I also recommend making a slightly different version of Survivor that explicitly says not to murderbone or generally do catastrophic shit like loosing the singulo

**Comment by ShiftyRail** [comment]
Sure.

**Comment by ShiftyRail** [comment]
"Live (and die) by the Non-Aggression Principle. Do not destroy station property. Defend your rights - but do not infringe those of others."

**Comment by ghost** [comment]
Wouldn't that just be exactly the same as not being a survivor (antag)?

**Comment by ShiftyRail** [comment]
I would say that the only binding words of this flavour text translate to "don't singuloose, don't plasmaflood, and don't go on a shooting spree just because you have an antag status." 

This would make it clearer - on both sides of an engagement - that they are allowed to escalate it in any way they want.

**Comment by SonixApache** [comment]
don't we have a rule against PRs made in bad faith or something
also at least tag yourself with bad faith, coward

**Comment by TGFH** [comment]
Why contain it? Let it spill over the schools and churches, let the bodies pile up in the streets. In the end they'll beg us to save them.

**Comment by ghost** [comment]
time to declare central primary sovereign territory and shoot anyone who enters for violating the NAP

**Comment by APCUnlocked** [comment]
Those rules you've put into this new "castle-specific survivor" mean nothing, since we have antag freedumbs and if we don't, you're gonna end up with the exact same ban requests you've linked as a reason for this PR. Bad faith and so on.

**Comment by ShiftyRail** [comment]
>I would say that the only binding words of this flavour text translate to "don't singuloose, don't plasmaflood, and don't go on a shooting spree just because you have an antag status."

>This would make it clearer - on both sides of an engagement - that they are allowed to escalate it in any way they want.

**Comment by PrimeDSS13** [comment]
this has to be the lowest RP pull request I've seen in a while
literally "guys vote for the mode to be free for all!!!!"

anyways on a less in the moment note, if this PR merges I really do think it's just gonna be played a few times and then either this PR will be reverted, or in the more likely setting castle will be pulled from the vote. maybe that's shiftys goal all along...

**Comment by juanototo2** [comment]
I agree with PrimeD. Switching to downthumber.

**Comment by juanototo2** [comment]
Make sure the objective is written in bold, massive red "DO NOT SINGULOOSE, DO NOT PLASMAFLOOD, DO NOT KILL EVERYONE FOR NO REASON, BUT ESCALATION RULES ARE RELAXED" so NOBODY can misunderstand.

**Comment by TGFH** [comment]
Special escalation rules would be a joke. You either get unbridled chaos or banbait city. Pick your poison.

**Comment by bungofungo** [comment]
this is going to open up a gigantic can of worms on antag freedoms, and people are going to toe the line hard with this, i shudder to think of a station where every single crew member has the mentality of a borg hoping they get purged so they can kill everyone within visual range

**Comment by ShiftyRail** [comment]
Castle is a noRP station

**Comment by toomykins** [comment]
put this to a community poll and then force castle for 6 consecutive rounds

**Comment by ShiftyRail** [comment]
If another admin wants to make a poll on this, sure.

**Comment by SonixApache** [comment]
put this to a community poll and then force castle for two weeks

**Comment by Kammerjunk** [comment]
one of the worst ideas out there

**Comment by Kurfursten** [comment]
It's always difficult when you need to make 20+ people upset either way. Based on talks with the administrative team, this doesn't look like it's the right fit.

**Pull request closed without merging**
