### PR TITLE
Head Fixes

### LINKED ISSUE #31680: head duplication surgery
(WEB REPORT BY: fitzbond REMOTE: 206.221.180.138:7777)
# Revision
348f29631d6ca0f258fdd67a9b4142589cfcc449

# Description
Head from monkeman attached to headless body results in body receiving head, but still having monkemanhead too.

# Steps to Reproduce
-find a headless playerbody (I had found a player's body and brain, but not their actual head, I put the brain into an MMI)
-take monkeman
-circularsaw head of on violent intent without finesse (this is what I did, I assume other forms of head removal will net the same end result, but I did not test)
-prep headless playerbody for head reattachment
-attach monkehead

# What you Expected
monkehead going from my hand onto the player body

# What Actually Happened
monkehead went onto the player body, but also still remained in my hand, i.e. head duplication.

### PR DESCRIPTION
**Pull request by Cyadox**
[bugfix]
Fixes the rest of the jank I added by accident, and retains previous fixes. Also added some comments to explain what half this shit does, and some sanity so we're not passing null organs from limbs to the body. 
Lastly, fixes an issue where you would get stuck in 'Cavity/Implant surgery' if you cut off a head you're doing "normal" surgery on, and could no longer do the head reattachment surgery.

Closes #31680

:cl:
 * bugfix: Fixes dupe issue when using monkeyman heads in lieu of the original corpse's head during head reattachment surgery
 * bugfix: Exploded heads will delete eyes from the body too 
 * bugfix: You will no longer be stuck in implant/cavity surgery if the head is cut off after you've opened it surgically.

### CODE REVIEW

**Comment by adacovsk** [comment]
I knew the eye bug would take you down a rabbit hole, I'm surprised you took on the fixes, good job

**Comment by Cyadox** [comment]
> I knew the eye bug would take you down a rabbit hole, I'm surprised you took on the fixes, good job

Stitch in time saves nine - it wouldn't have been so bad if it was made with any sane approach. That's last time I presume how things work...

**Comment by SonixApache** [comment]
fix title

**Comment by Cyadox** [comment]
Ah, thanks Kurfust. I didn't see the notification

**Pull request merged**
