### PR TITLE
Code Red Maintenance Security Override

### PR DESCRIPTION
**Pull request by toomykins**
[content]
re-pull requesting this specific thing cuz it was a feature attached to a more controversial access tweak.

- Heads of Staff can swipe the keycard device to limit maintenance to Security only on Security level Red.
- Revocation of Maintenance overrides no longer requires an additional swiper on the keycard device.

Upsides for seccies
- makes hunting baddies easier on code red

downsides for seccies
- crew becomes very angry with sec, rise in nonantag petty crime.

:cl: 
- rscadd: Heads of Staff can swipe the keycard device to limit maintenance to Security only on Security level Red.
- tweak: Revocation of Maintenance overrides no longer requires an additional swiper on the keycard device.

### CODE REVIEW

**Comment by zakanater19** [comment]
lol

**Comment by Irradiation** [comment]
bruh

**Comment by toomykins** [comment]
well shit nevermind then
security codes stay forever irrelevant

**Comment by KingofHONK** [comment]
Aw man this one was gunna be good whyd u close it

**Comment by toomykins** [comment]
cuz fuck you thats why

**Comment by xeroxemnas** [comment]
I woulda upvoted it if you kept it open tbh.

**Pull request closed without merging**
