### PR TITLE
Adds Socket wrench to Prolathe

### PR DESCRIPTION
**Pull request by DorainGrey**
## What this does
Adds Socket Wrench to the Prolathe, requiring engineering 1. The cost is set at 10000 iron.

## Why it's good
Allows you to effectively deal with plasma floods if the original wrenches have been stolen/destroyed. There's no other way to acquire them other than the atmos tech locker.

## Changelog

:cl:
 * rscadd: Added Socket Wrench to prolathe

### CODE REVIEW

**Comment by Eneocho** [comment]
Very nice, though I'd place it on the CONTRABAND tab instead of the tools one.
Prepare for the coder cabal to tell you why it's a bad change for some reason.

**Comment by Eneocho** [comment]
Also consider making it more expensive metalwise, perhaps a full sheet (3500) instead of 250? It's a SIZE_LARGE item after all, compared to the regular wrench SIZE_SMALL.

**Comment by BomberBro** [comment]
Socket wrench is a really freaking strong tool, should be gated behind cargo at the very least so it leaves a paper trail.

**Comment by Eneocho** [comment]
> Socket wrench is a really freaking strong tool, should be gated behind cargo at the very least so it leaves a paper trail.

This sounds good on paper until you get half the cabal complaining that it's yet another cargo buff.

**Comment by DorainGrey** [comment]
> Socket wrench is a really freaking strong tool, should be gated behind cargo at the very least so it leaves a paper trail.

Like as a melee weapon or it's tool usage? All it does is allow you to open pressurized pipes and it's a default item.
I will move it to contraband and raise price as requested.
Gating it behind cargo, means it's effectively useless when you actually need it. 2 minutes+ for it to arrive means the whole distro is screwed.

**Comment by pedr69** [comment]
make it RCD tier expensive
RCD/RPD's can also be made in the hacked lathe and are expensive as fuck
the engiborg socket wrench upgrade also needs a ton of metal

**Comment by DorainGrey** [comment]
> make it RCD tier expensive RCD/RPD's can also be made in the hacked lathe and are expensive as fuck the engiborg socket wrench upgrade also needs a ton of metal

Done, it now costs as much as an RCD.

**Comment by WindowsErrors** [comment]
yea trust us when we say the socket wrench is strong

**Comment by jwhitak** [comment]
I'm honestly confused to why it's forbidden levels of strong. It's a wrench that is LARGE (drawback), does damage like a toolbox, and is one of the only things able to handle overpressurized pipes.

**Comment by WindowsErrors** [comment]
i will unwrench your pipes

**Comment by Eneocho** [comment]
>I'm honestly confused to why it's forbidden levels of strong. It's a wrench that is LARGE (drawback), does damage like a toolbox, and is one of the only things able to handle overpressurized pipes.

Fearmongering about mass pipe unwrenching even though a mediocre no access syndie can get his hands on a locker socket wrench (emag 2 doors and a locker) and mass pipe unwrench yet it never happens.

**Comment by Kurfursten** [comment]
You actually can print more of these, like most engineering specials, at the ancient matter synth

In practice I have never in 8 years seen someone destroy all socket wrenches, or even try.

**Comment by DorainGrey** [comment]
> You actually can print more of these, like most engineering specials, at the ancient matter synth
> 
> In practice I have never in 8 years seen someone destroy all socket wrenches, or even try.

It's happened to me twice recently, once purposely and once accidentally.
This PR just helps out anyone else in the situation, I do not see any reason to leave this item unobtainable normally. 
Even if this never happens again, why not? It won't harm anyone being in there and its far from the most powerful thing in there.

> > I'm honestly confused to why it's forbidden levels of strong. It's a wrench that is LARGE (drawback), does damage like a toolbox, and is one of the only things able to handle overpressurized pipes.
> 
> Fearmongering about mass pipe unwrenching even though a mediocre no access syndie can get his hands on a locker socket wrench (emag 2 doors and a locker) and mass pipe unwrench yet it never happens.

You can even unwrench normal distro pipes with normal wrenches, the only place you probably can't is atmos at which point there's better ways to cause damage.

**Comment by adacovsk** [comment]
> In practice I have never in 8 years seen someone destroy all socket wrenches, or even try.

I've done it multiple times

**Comment by Dacendeth** [comment]
There's more socket wrenches on every map than the ones in atmos.

**Comment by DorainGrey** [comment]
> There's more socket wrenches on every map than the ones in atmos.

Where?
Other than in the antique matter synth, or that weird Derelict Engi vending machine. There is no source on most maps, Dorf, Lampery are the only ones with spawns outside the atmos lockers.

**Comment by ManopolisJones** [comment]
I think the real add to the autolathe would be welding goggles to contraband, but otherwise got no opinion on this. I just know they're robust and you barely see them.

**Comment by SonixApache** [comment]
mechanics can just scan and print socket wrenches

**Comment by DorainGrey** [comment]
> mechanics can just scan and print socket wrenches

That's not the point, it's to have an alternative when they are all stolen or get destroyed.
Nor does it really have any relevance, a mechanic can also scan other tools, yet they are printable at the autolathe.

**Comment by Kurfursten** [comment]
Mixed feelings because mechanic can easily make an autolathe to outfit engineering so he keeps his role as engineering outfitter, but also this will most likely just make people go to cargo for engineering stuff, continuing a growing dependence on cargo. Previously the mechanic would supply the RUST circuits, but those got put in a crate recently too.

We should be growing the idea of mechanic as engineering supplies, not shrinking it. What about a protolathe item with just engineering 1? That way it's less to cargo and it doesn't require any R&D.

**Comment by DorainGrey** [comment]
> Mixed feelings because mechanic can easily make an autolathe to outfit engineering so he keeps his role as engineering outfitter, but also this will most likely just make people go to cargo for engineering stuff, continuing a growing dependence on cargo. Previously the mechanic would supply the RUST circuits, but those got put in a crate recently too.
> 
> We should be growing the idea of mechanic as engineering supplies, not shrinking it. What about a protolathe item with just engineering 1? That way it's less to cargo and it doesn't require any R&D.

That's fair, I can get behind that. I'll change up the PR when I have time.

**Comment by Kurfursten** [comment]
Chief engineer has mechanic access, no hope required. I happen to know Dorain plays CE anyway, and we should encourage more people to.

**Comment by DorainGrey** [comment]
This has been updated as requested @Kurfursten

**Pull request merged**
