### PR TITLE
Smoke may no longer be dragged

### LINKED ISSUE #28540: Drag Smoke
(WEB REPORT BY: kirbythewizard101 REMOTE: 206.221.180.138:7777)
# Revision
81b84a0e2ef9b7569516aa9ac5608e7eca107b5b

# Description
Being able to drag smoke
# Steps to Reproduce
set off a smoke bomb (in this case it's weed killer) and right click drag it
# What you Expected
Not to be able to drag fucking air
# What Actually Happened
watching a plasmeme drag weed killer to kill kudzu

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #28540 (wtf)

### CODE REVIEW

**Comment by KingofHONK** [comment]
NOOOOOOOOO

**Comment by SonixApache** [comment]
rip @PrimeDSS13

**Comment by PrimeDSS13** [comment]
no no no no

**Comment by Armadingus** [comment]
What does this mean for geneticists using the mutagen smoke on the human collider conveyor thing?

**Comment by ShiftyRail** [comment]
@Armadingus ~~This should only affect human-dragged smoke. Natural motion of the gas is still possible. For the LHC (Lying Humans Collider), this changes nothing as the device relies on multiple reactions from the same puff of smoke every time the human crosses the smoke cloud, not on any motion of the gas itself~~

Apparently it does. RIP LHC, might be reintroduced in another PR.

**Comment by DamianX** [comment]
huge hydroponics buff

**Comment by xeroxemnas** [comment]
"Smoke may no longer dress in drag"

Wtf this PR is bigoted.

**Pull request merged**
