### PR TITLE
Grants janitors the amazing ability to converse with mice speech.

### PR DESCRIPTION
**Pull request by DeityLink**
I see nothing but great comedy potential coming from that.

:cl:
* rscadd: Decades of roaming maintenance tunnels and interacting with its denizens have granted janitors the ability to understand the speech of mice and rats.

### CODE REVIEW

**Comment by SonixApache** [comment]
mousecreep

**Comment by Shadowmech88** [comment]
>Decades of roaming maintenance tunnels and interacting with its denizens

Shouldn't this description include assistants, as well?
Also, what if people with sufficient brain damage were able to understand mice?

**Comment by Arthurdentist** [comment]
I don't think this really makes sense and I am not sure it really adds anything of value. Seems like it would mostly be an avenue for people to pick mouse, run to the janitor asap and try and reveal round secrets.

On that note though, Librarians (on occasion) and catbeasts as well also understand mousespeak, so maybe my concerns about this are unfounded.

**Comment by ShiftyRail** [comment]
It is already a Librarian gimmick

**Comment by jknpj** [comment]
It doesn't matter, someone filtered mice to only be able to say "squeak" because "muh metagaming"

**Comment by Durgen** [comment]
Make it a 1/10 chance to be able to speak mouse so ghosts can’t metagay

**Comment by DeityLink** [comment]
@jknpj wait so mice can only say squeak even among themselves?

**Comment by Kurfursten** [comment]
That is not the case, mice have speak_override = FALSE. Override must be true to force default animal speech.

I am mostly convinced by Arthur. I think the reason it's harmless Librarians get an extra language is that it's not predictable.

**Comment by jknpj** [comment]
They used to have it set to TRUE #17339

**Comment by Kurfursten** [comment]
Been a year since #17443

**Comment by jknpj** [comment]
Understandable

**Comment by SonixApache** [comment]
re-open #14129

**Comment by Goldsteel** [comment]
I can see this being metagaming bait honestly, as funny as it is, it's going to get abused at some point but you can just do that with any role like borer/pAI so why not? I agree with making it a percentage chance, though, kind of like an easteregg you aren't instantly told about.

**Comment by SirSkeleto** [comment]
Just like if you die, ghost, and get cloned, mice can't reveal anything that they themselves haven't seen. Anything else is bannable.

**Comment by Blithering** [comment]
Have it so that janitors can only understand the final squeaks of mice he catches with mousetraps. That way the most meta thing he'll hear is 'faggot'

**Comment by DeityLink** [comment]
I see 5 thumbs down but relatively little discussion from them in the comments

@SonixApache what's specifically concerning about mousecreep?
@Arthurdentist if people meta with round knowledge they're not supposed to have can't we just handle it the same we handle it for every other players?
@ShiftyRail I think languages are underused but that's my personal opinion. Also librarians only having a "chance" to have it doesn't mean janitors can't have it imo.
@MadmanMartian @Lokiamis what are your thoughts on this exactly?

**Comment by Lokiamis** [comment]
Mice speaking to people is stupid and I don't agree with adding nonsensical things because it's funny.

**Comment by DeityLink** [comment]
fair enough

**Comment by SonixApache** [comment]
what lokiamis said and also mice will become too powerful if they can communicate with *even more* crew

**Comment by Kammerjunk** [comment]
for once I agree with Deity that if someone is being a metagay, ban them like you'd ban someone who became a diona nymph or borer in order to tell round secrets
byond that idc about this one way or the other

**Pull request merged**
