### PR TITLE
Update line

### LINKED ISSUE #31685: Trader bug
(WEB REPORT BY: memdic REMOTE: 206.221.180.138:7777)
# Revision
348f29631d6ca0f258fdd67a9b4142589cfcc449

# Description
I was playing a trader vox, and when I found the trader, it said that he was closed due to bad atoms. Atoms were 100% nitrogen. 
# Steps to Reproduce
Honestly, I am not sure. Guess sometimes "bad atoms" just happen and traders cant play
# What you Expected
To trade, duh
# What Actually Happened
Trader did not give me any crates even when I had the money on the table and clicked on the crate. Atoms were perfectly breathable.

### PR DESCRIPTION
**Pull request by adacovsk**
- switched out bridge SME telescreen for singulo telescreen
- added some bounced radios to brig
- some catwalks for wires
- fixed trader (Closes #31685)
- #31653 not sure if there need to be a fix here, z4 and z5 mostly the same as box and this has never been an issue. Maybe just a fluke. I do not plan on fixing it because I don't think it's an issue.

:cl:
 * tweak: Fixed trader on Frankenline

### CODE REVIEW

**Comment by Eneocho** [comment]
The issue with the goonsat thing is that sometimes random vaults spawn way too close to a map edge, thus bleeding over to the neighbouring Z-level. It happens more often than people think but we don't get too many rounds with space exploration so it's mostly unnoticed. Not a problem with line but rather with the way vaults spawn, there's no(t enough?) check(s) to avoid bleeding over with the larger vaults.

**Comment by adacovsk** [comment]
Thanks Eneocho. They don't necessarily "bleed over", but the holomap takes extents greater than the z-level itself.

**Comment by Eneocho** [comment]
I've seen the bleed-over myself, I had found the dark site prism vault and it was sliced at the right side so you could not kill the beno queen.

**Comment by Kurfursten** [comment]
mapping priority given to #31630

**Comment by adacovsk** [comment]
I took the commit from the other PR, added it here, then reverted it from the other PR. So everything should be fine

**Comment by adacovsk** [comment]
> I've seen the bleed-over myself, I had found the dark site prism vault and it was sliced at the right side so you could not kill the beno queen.

Sounds like a problem with map prodecural generation (which I would have no idea how to fix) too.

**Pull request merged**
