### PR TITLE
Fix plant b gone sprite

### PR DESCRIPTION
**Pull request by SonixApache**
old plantbgone sprite is in hydrophonics.dmi which is one of the 13 cursed read-only .dmi files
plantbgone
Tested.

:cl:
 - imageadd: PlantBGone spray bottles now have the same offset as chemistry spray bottles

### CODE REVIEW

**Comment by Probe1** [comment]
dem armory commits

**Comment by SonixApache** [comment]
oh goddamnit

**Comment by SonixApache** [comment]
remember to branch off your bleeding edge, kids

**Review by PJB3005 — APPROVED** [review]

**Comment by Probe1** [comment]
UGH

**Pull request merged**
