### PR TITLE
You can now check your sacrifice's location by communing with Nar'sie at an altar

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
You can also do this with astral journey but I think it's pretty fair to have this.
:cl:
 * tweak: Cultists can now know their sacrifice's location by communing with Nar'sie at an altar.

### CODE REVIEW

**Comment by Caboozles** [comment]
This should solely be tied to the corresponding nerf to bloodstones. Cult does not need any standalone buffs.

**Comment by boy2mantwicethefam** [comment]
I want to make cultists visible during the stone phase anyway but progress is taking some time

**Comment by ShiftyRail** [comment]
Not enough

Make the sacrifice target immediately gib, ban them, and ddos the current non-cult players
This will truly fix cult

Make sure that all of this is announced in big red text in the chat, cultists have some trouble with reading things, this should help them!

**Comment by boy2mantwicethefam** [comment]
cringe ass nae nae sec baby

**Comment by Blithering** [comment]
This is good because noone, not the cultists, not the non-antag crew, likes cult stalling for 40 minutes due to the sac target being braindead in a DNA modifier tube.

**Comment by ShiftyRail** [comment]
It'd be better if it was kept as an Astral Journey only perk.

I didn't know this could happen and I think it's actually a cool neat
feature/"emulgeant gameplay".

Maybe add an action button to jump to the sac target as as Astral cultist.

**Comment by jknpj** [comment]
I'd rather have a comms console check. Come on papa narnar i need to recall that shuttle!

**Comment by plosky1** [comment]
@ShiftyRail currently astral journey has no jump to target or haunt method, so unless you get lucky and spot the sac target running down a hallway, it's not that reliable.

If they're in a tube or closet or something you're fucked with astral journey.

**Comment by ShiftyRail** [comment]
Then we should a way to haunt the sacrifice target to Astral Journey
creative gameplay over obvious braindead solutions

**Comment by DeityLink** [comment]
I'm kinda in support of this PR, but as Shifty pointed out this makes Astral Journey even more obsolete, even though all it's barely good at right now is keeping tabs on sec, and then it takes time to take action since you need to wake up first anyway.

So I think we should merge this, and then rework Astral Journey down the line so it becomes more interesting. Maybe you could actually do stuff that affect the real world, placing runes, I dunno...

**Comment by SonixApache** [comment]
hey make it so if you do this it spooks your target (like with the ghost Boo! spell)

**Comment by ShiftyRail** [comment]
It's less than Astral Journey is obsolete, and more than cultists don't feel the need to use it (either because it comes too late to make a difference in early stages, or that gathering intel isn't as useful when you're murderizing everyone/"going loud" in later phases)

**Comment by DamianX** [comment]
This is objectively good because it makes cult more speedrunnable. Less time spent in a cult round is objectively a good thing and should be pursued at all costs.

**Comment by tuypo1** [comment]
>Cult does not need any standalone buffs.

You do understand that although this is a buff to cult it is also good for cult haters because it means shorter cult rounds

**Comment by SonixApache** [comment]
so how much blood / how many organs does it cost to do this? there's a cost, right?

**Comment by boy2mantwicethefam** [comment]
Hahaha

**Comment by SirSkeleto** [comment]
astral journey works fine
dont see why we need to hold everyone's hand

**Comment by tuypo1** [comment]
>dont see why we need to hold everyone's hand

Because it's frustrating for all involved on both sides when rounds cannot progress because nobody can find the target

**Comment by SonixApache** [comment]
😔

**Pull request merged**
