### PR TITLE
Added a Jack Frost AI screen display

### PR DESCRIPTION
**Pull request by Moonman1946**
- Added a Jack Frost screen display for the AI
That's it. After seeing Mothman get added i thought to myself: "Why not?"
And here it is, ladies and gentlemen.
ezgif-4-a7ee21af11
Ain't he a cute one? He blinks every five seconds. Have in mind, it's my first rather serious spritework ever, so if you deem it shit feel free to tell me what's wrong so i can improve myself. I've also wanted to make a Jack Frost AI Hologram, but that comes later.
It edits:

- The AI.dmi file, to add the sprite
- The AI.dm file, so you can choose the sprite.

### CODE REVIEW

**Comment by SonixApache** [comment]
Eyes should be more oval. 2x6 rectangle?

**Comment by Arthurdentist** [comment]
does he blink like that in whatever he is from cause it looks like he has shrinking eyeballs

**Comment by Riekland** [comment]
I really don't think we need more AI sprites
In any case, it would do better looking like a CRT or actually behind a screen, to fit with the rest of the AI sprites

**Comment by DamianX** [comment]
needs a changelog

**Comment by Riekland** [comment]
nexis did you not see the person saying it needs a changelog

**Comment by Exxion** [comment]
Something this minor really doesn't

**Comment by DamianX** [comment]
i just really like changelogs

**Comment by SonixApache** [comment]
If it affects the players, or adds non-stealth things for the players to work with, it needs a changelog.

**Comment by Exxion** [comment]
It really doesn't.
It's not like people in the position to use this would fail to notice it. It appears in the list. It also has no real impact on gameplay.

**Pull request merged**
