### PR TITLE
Doubles the effectiveness of shaking someone awake 

### PR DESCRIPTION
**Pull request by Dacendeth**
Shaking someone awake always felt really weak to me so I went ahead and buffed it, Medborg revivalprod also improved similarly. No changes have been made to shaking people who are stunned or knocked down.

:cl:
 * tweak: Shaking people awake who are asleep is now twice as effective.

### CODE REVIEW

**Comment by Kurfursten** [comment]
What situation is this aimed at?

**Comment by Zth--** [comment]
It would be nice to move all these magic numbers to defines and start to make sense of them. Like, what are common values for `sleeping`? how much is too much? and how long does it last?

**Comment by Kurfursten** [comment]
1 sleep = 1 tick = 2 seconds
sleep verb gives you 150 sleep = 300 seconds = 5 minutes
Stoxin repeatedly sets your sleep to 30 (at max data)

**Comment by Dacendeth** [comment]
@Kurfursten Well the idea stemmed from your sounds are wakeful pr, I was happy that shaking was going to wake people up faster thanks to it playing a sound, but you closed that pr and I still wanted shaking to be better. Mostly for surgery reasons when you don't have access to a sleeper.

**Comment by Zth--** [comment]
This kills the coffee strat and I don't like that

**Comment by Probe1** [comment]
Having strats to get around jank code is bad.

**Pull request merged**
