### PR TITLE
Nu Cryo: Feedbackcreep

### PR DESCRIPTION
**Pull request by jknpj**
feedback
Having upgrades is fine and all, but having a visual feedback of the actual amount of chems that your cryo tube has is more important. I was also requested to give medbay a way to check the occupant's reagents, so you can now use your reagent scanner on the tube to check'em.

:cl:
 * rscadd: You can now use your reagent scanner 
 * rscdel: You can now see the amount of the reagents inside the cryo tube without scanning module upgrades

### CODE REVIEW

**Comment by DrSnips** [comment]
Yet another change that doesn't do anything for us. Just give us back the old cryo already.

**Comment by PrimeDSS13** [comment]
While the change is solid and interesting, I feel like this is just gonna lead to people saying "We can't revert nu-cryo, people have put too much work into it already. Let's just keep tweaking it". Applying the reagent scanner change to old cryo would be nice though.

**Comment by jknpj** [comment]
>"We can't revert nu-cryo, people have put too much work into it already"

But you can revert nucryo without touching anything that was touched in this PR. Even with old cryo the reagent info is important enough to want it by default.

**Comment by SonixApache** [comment]
all downboats should be treated as upboats since the only argument for the downboats so far has been "it's not a revert so i don't want it"

**Comment by juanototo2** [comment]
Well last revert got the c*llab treatment because a single PR was merged that """""""fixed""""" a SINGLE issue with the utter disaster that has been, is, and will continue to be until put out of its misery nucryo.

**Comment by juanototo2** [comment]
Thus, git posters are attempting to prevent said treatment from happening again and voice their support for a new revert to be posted, and get merged for real this time.

**Comment by juanototo2** [comment]
Also, how very, VERY funny you are turning the colloquial 180 degrees when you specifically said in the revert nucryo PR after it got closed that none of the issues that people wanted to revert nice to for were fixed in the PR.

**Comment by SonixApache** [comment]
i can't update my revert PR till this gets merged or closed, i'd rather have it merged sooner so i can get it over with

**Pull request merged**
