### PR TITLE
New IAA alt title job - Bridge Officer

### PR DESCRIPTION
**Pull request by BurntDevil**
Adds "Bridge Officer" to IAA's alt titles. Bridge Officer is a junior command position well below the Heads that exists to coordinate efforts from the bridge using consoles, faxes and command headset. It is a simple job that functions differently from IAA or Lawyer but fits within the clerical branch of the station.

### CODE REVIEW

**Comment by BurntDevil** [comment]
Basic alt title job. Should give players who want a supporting role that has interdepartmental communication something to do. Essentially a bridge warden. Get on the bridge, setup consoles, support and communicate as needed.

**Comment by FudgePucker** [comment]
Seems like a good idea.
For players that want to help out the station instead of being a huge obnoxious dildo.

**Comment by SonixApache** [comment]
Did you test this with SEChuds and whatnot?

**Comment by Durgen** [comment]
Will it answer to the captain?
Will it get it's own jumpsuit?

**Comment by FudgePucker** [comment]
I would assume they answer to all the heads because the job is pretty much coordinating and secretary work for command.

I think they would need a command headset, maybe one with command and common only so their locker doesn't become a major target in an unsecure area

**Comment by BurntDevil** [comment]
Sec Huds show the IAA icon. I have BO spawning in a dark blue jumpsuit with blue suit jacket, with the command headset. I'll find time down the road to make a custom bridge officer sprite set.
I didnt change the "you answer to...." supervisor text. It'll still say it answers to centcomm, law, and captain.

**Pull request merged**
