### PR TITLE
MoMMI Spaghetti is now grey and has BIG FLASHING LIGHTS

### PR DESCRIPTION
**Pull request by Gringonius**
Because sticking them between regular boiled spaghetti to trick people is too much of a dick move.
Current sprite:
spag2
PR's sprite (sped up to hell):
spag1

### CODE REVIEW

**Comment by Irradiation** [comment]
Can you post a picture of before/after the sprite change?

**Comment by Irradiation** [comment]
I'd make the sparks purple in color, since crab spaghetti is made of plasma. Otherwise a nice recolor.

**Comment by Gringonius** [comment]
I think that blue, red and grey are the more iconic MoMMI colors, that's why I went with that.

**Comment by Exxion** [comment]
Not to suggest that you shouldn't put sprite changes in the PR body, but for future reference you can always* click the Details button here:
image
To see all changed/added/removed sprites.

*When IconDiffBot doesn't decide not to work

**Comment by Reviire** [comment]
It's supposed to be a dick move. The other dick move is death juice in the food, are we gonna sprite that too?

**Comment by SonixApache** [comment]
how about blue triangle eyes that occasionally glow red?

**Comment by Gringonius** [comment]
> 
> 
> It's supposed to be a dick move. The other dick move is death juice in the food, are we gonna sprite that too?

Serving death berries is one thing, serving normal food with death berry juice sneakily added is another. Roburgers always had their own sprite and it's overdue that MoMMI Spaghetti gets its own.
Just because you're a dick it doesn't mean that it's ok.

**Comment by Intigracy** [comment]
If you still want to be a dick with it, grind it up and inject it into regular spaghetti.

**Pull request merged**
