### PR TITLE
Malfunctioning AIs that take over the station can now detonate the nuclear bomb with a button

### PR DESCRIPTION
**Pull request by gurfan**
## What this does
Malf AIs that successfully take over the station get a button on their UI that allows them to detonate the nuclear bomb, like before.
Also fixes malf jecties.

## Why it's good
The malf rework made it so that AIs needed to hack the nuke and see it in order to blow it up. I thought that this would be an interesting challenge and add some more depth to the gamemode but it ended up being pretty unintuitive. Its also a big letdown when the round just ends without some sort of explosion or climax.

## Changelog

:cl:
 * rscadd: Malf AIs that successfully take over the station get a button on their UI that allows them to detonate the nuclear bomb, like before.

### CODE REVIEW

**Comment by Eneocho** [comment]
Does this make it so they can hack it regardless of location (such as it being outside camera view) or is it just a "press here for kaboom" button?

**Comment by gurfan** [comment]
> Does this make it so they can hack it regardless of location (such as it being outside camera view) or is it just a "press here for kaboom" button?

press button nuke explodes

**Comment by adacovsk** [comment]
can you put some bounds on stage so we don't get negative percentages?

**Comment by nervere** [comment]
I got cucked out of nuking the station because it went off-cams before, I appreciate this change.


> can you put some bounds on stage so we don't get negative percentages?

Soulless

**Pull request merged**
