### PR TITLE
Hub entry shows round time, shuttle time, map, next map

### PR DESCRIPTION
**Pull request by 13spacemen**
## Why it's good
More info in the hub is always good, you can get more players if the map looks interesting
For example most other servers don't have Horizon or Taxi or whatever, so new players may join in order to check out the /vg/ exclusive maps
Having an idea of roundstart/end is also good

Also codewise moved the shuttle timer proc off status displays

## Changelog

:cl:
 * rscadd: Hub entry shows round time, shuttle time, map, next map

### CODE REVIEW

**Comment by gurfan** [comment]
The hub description was designed to be fully customizable by admins in-game without the need for code changes. Instead of changing the description here, you should add the round time and next map as variables you can set in the description, the same way it's done for map name, player count, etc, already.

Then just bug an admin to change the hub.

**Comment by 13spacemen** [comment]
@gurfan reason I did not add them as variables for admins to set is cuz I want these stats to always be present no matter what. it's important info for hubbies

I am open to changing it tho

**Comment by kilozombie** [comment]
I am completely indifferent to this. It might be a good thing, but /vg/ only appears on the hub at low playercounts anyway, so players on the hub are going to be introduced via "2 players online, station time 17:56, map is Box Station, next map is %UNKNOWN%"

That might actually be a nice kind of player to covet, someone who wants an old-school experience and is okay with lowpop, but I digress

**Comment by Kurfursten** [comment]
Given that this PR affects our presentation to the Hub and it has to do with projection of server image, I believe this falls within the bailiwick of the head administrators. I will refer this to them for decision.

**Comment by Kurfursten** [comment]
Headmins like it

**Pull request merged**
