### PR TITLE
Fixes a year old severely underplanned change. Clowns can cuff again.

### PR DESCRIPTION
**Pull request by carshalash**
Yeah, remaking clowns antag gimmick to be solely relying on their murder tools instead of allowing them to fuck around with gimmicks like a clown should is retarded. Especially when the original purpose of in/tg/racys pr was to stop that.

### CODE REVIEW

**Comment by Pathid** [comment]
Could use `if(user.mind.special_role)` to have cuffs always work just for antag clowns instead.
Or rather `if(!user.mind.special_role)`

**Comment by carshalash** [comment]
Listened to change suggested by @Pathid No bad boy clowns trying to griff as non antag should be handcuffing people now.

**Comment by carshalash** [comment]
Remembered the very important topic of the old clown antag testing days in the discord. This is a very difficult situation.

**Comment by carshalash** [comment]
I may need to talk with the chicken about having a poll of whether it should be antag only or not due to metagaming checks which we all remember. Or just put some heavy thought onto it.

**Comment by Pathid** [comment]
Yeah, that's wise. Gotta be careful with things that enable antag-tests like that.

**Comment by carshalash** [comment]
Forgot the old days of "CLOWN SHOOT GUN NOW"

**Comment by Aurx** [comment]
Why not just make antag clowns able to toggle their clumsiness at-will?

**Comment by RealestEstate** [comment]
that's a really good idea honestly.

**Comment by DeityLink** [comment]
I'm sad that never in the original code, nor in the fix, does the clown has a chance to cuff himself. Or is that already a CLUMSY test?

**Comment by Intigracy** [comment]
That's literally the code he's changing.

**Comment by carshalash** [comment]
Getting stuck in a 30-1min stun trying to uncuff yourself from a shitty 50/50 chance as an antag is kind of cancerous.

**Comment by Blithering** [comment]
What if clowns could cuff people with long balloons instead, that way they stick with the theme

**Comment by SonixApache** [comment]
murderclowns are not funny

**Comment by SangriaMonkey** [comment]
clowns were never funny

**Comment by carshalash** [comment]
@SonixApache Thats... literally why i'm making the pr? So that they can actually detain people and do gimmicks instead of murder clown.

**Comment by carshalash** [comment]
Okay, apparently people have misunderstood the purpose of this pr.

At the moment, the only tools a clown has as an antag are those that were coded in after in/tg/racys nerf. This means that the clown still relies on his slipping via pda or banana as his sole method of incapacitating someone (Thanks lube crawling.).  The time window of the slip being the sole form of incapacitating that a clown gets is kind of absolute trash, the person being fucked with still has the option of screaming over comms for help for some time before the clown is able to handcuff which is perfectly fair and balanced. The way it is now deprives clowns of being able to do many different gimmicks that don't involve player death or removing them from the round, with the change they'd be able to do dumb kidnapping gimmicks and being able to utilize superglue clothing on people instead of it being used to keep weapons on hand or just the same old gluing shit to peoples hands for a few minutes before surgery.

I'm really not understanding why you wouldn't want this to be a thing, encouraging a certain role to focus entirely on playing their antag style on killing and removing people from rounds is pretty shitty, doing it to the clown of all things however is just absolutely retarded.

**Comment by DamianX** [comment]
If you have an issue with murderboning clowns then remove the murderbone items?

**Comment by carshalash** [comment]
:thinking:

**Comment by Aurx** [comment]
You can't code out bad play.  Murderboner clowns will find a way to murderbone.  
So code fun things for fun people.

**Comment by carshalash** [comment]
You can code out non murderbone play however apparently which has been done.

**Comment by SonixApache** [comment]
the proper solution would be to port baycode yellow intent

**Comment by Blithering** [comment]
Can't clowns use invisible sprayed cages to capture people? A little creativity can bypass most problems. Also non antag clowns being able to cuff opens the door to a lot of trouble

**Comment by DamianX** [comment]
Can we close this?

**Comment by Probe1** [comment]
smqox48

**Pull request closed without merging**
