### PR TITLE
Changes the recipe for Mead to use Honey instead of Sugar

### PR DESCRIPTION
**Pull request by ghost**
Mead is impossible to make due to the Sprinkles recipe taking priority, and we actually have honey now!

Will update the wiki if merged!

:cl:
 * tweak: The recipe for Mead now uses Honey instead of Sugar.

### CODE REVIEW

**Comment by ghost** [comment]
why don't we just remove sprinkles or change it if it messes with a lot of recipes

**Comment by Exxion** [comment]
Wow, someone actually tried to make mead?

**Comment by ghost** [comment]
@Commandersand I'll let someone else decide on that, I just realised it makes a lot more sense to use honey and kills two birds with one stone.

@Exxion muh alcoholism

**Comment by Exxion** [comment]
I'm just impressed
I've played nigh-exclusively bartender for over a year and I've never once seen mead, and I think I've only been asked for it once (and didn't have the materials to make it at the time)

**Pull request merged**
