### PR TITLE
Adds the survivor's hardsuit

### PR DESCRIPTION
**Pull request by jknpj**
image

I told Osseus to use a single "Asteroid EVA" suit for roidstation and the madman agreed to it. The idea behind its stats is something that can be used by both xenoarchs and miners, it has:

* 40% melee res
* 65% bomb res
* 100% bio res
* 50% rad res
* 40% anomaly res
* Can be reinforced with goliath plates

Adminbus-only until roidstation, i guess. Sprites made by @Blithering

### CODE REVIEW

**Comment by DrSnips** [comment]
So with this new suit how do xenoarchs plan to move supermatter crystals? Silicons are a decent solution to this but I'd rather not have to rely on another party in order to move my autistic garbage off of the roid. Maybe some kind of suit upgrade that you get with anomally research(so its mainly locked to/for xenoarch) that boosts rad resist to the suit?

**Comment by jknpj** [comment]
Crystals don't emit radiation when discovered unless you hit it with something. I used to do it just fine as plasmaman (their scisuit has zero rad/anomaly res)

**Comment by boy2mantwicethefam** [comment]
ror suit but when a worm touches u u die

**Comment by Blithering** [comment]
Alternatively you could ask an engineer for a shard crate to move it

**Comment by Kurfursten** [comment]
Mining set: melee = 40, bullet = 5, laser = 20,energy = 5, bomb = 35, bio = 100, rad = 80 and 0% anomaly resistance (fully reinforced, reaches 90 melee)
Excavation set: melee = 0, bullet = 0, laser = 0,energy = 0, bomb = 0, bio = 100, rad = 100 and 70% anomaly resistance (excavation set has the same stats as the anomaly suit but -20% anomaly resistance)
*Survivor* set: melee = 40, bullet = 0, laser = 0, energy = 0, bomb = 65, bio = 100, rad = 50 and 40% anomaly resistance

Baseline differences (not factoring in potential for 90 melee from goliath plates)
**Mining: -5 bullet, -20 laser, -5 energy, +30 bomb, -30 rad, +40% anomaly
Excavation: +40 melee, +65 bomb, -50 rad, -30% anomaly**
_A note about anomaly resistance: scientists will normally have base 20% due to wearing latex gloves and science goggles_

Anomaly resistance probably "doesn't matter" unless there are two xenoarchs active because most xenoarchs will swap into the anomaly suit for the full 100% before working, but it's a situational plus for miners because if the xenoarchs start pulsing weird 40 range shit from their base they have a little resistance against it.
Melee resistance is a big plus for xenoarchs because even though they probably won't hunt 5 goliaths to reinforce their suit up to 90, it's a non-insignificant protection against random monsters like hivelord broods that can chase scientists down.

Roidstation really needs renders available to make a call on whether these are necessary or creep. Of all the maps where you'd really want anomaly resistance on a miner, for example, Packed stands out with its combined outpost.

**Comment by jknpj** [comment]
**For Xenoarchs:**

Pros
+ More melee resistance against stronger mobs
+ Good chunk of resistance against gibtonite/explosives
+ Less slowdown due being a hardsuit

Cons
- Loss of 100% radproof (making you more likely to die to radiation artifacts that start triggered)
- Loss of almost 100% anomalyproof (making you more likely to die to dangerous artifacts that start triggered)
- Suits are now most likely going to get stolen by powergaming scientists/antagonists

**For Miners:**

Pros
+ Good chunk of resistance against gibtonite/explosives
+ A fair amount of anomaly res (40% isn't too shabby for a suit that isn't designed to handle anomalies)

Cons:
- Loss of minor bulletproof
- Loss of minor energyproof
- Loss of decent laserproof
- Loss of almost half of its radproof


I tried to solve issues in both jobs. Miners and Xenoarchs now have their own suit, not an engineer suit reskin or a softsuit with 100% radproof and 90% anomalyproof, their very own asteroid-delving suit. I'm still worried about giving scientists access to hardsuits but it's not like they can't just steal mining hardsuits when they want to. Osseus wanted a reason to remove the chemistry dispenser from roidstation's research outpost and i feel that this will make that change more appealing. 

I also expect this to make miners and xenoarchs look more friendly to each other, as they now share not only the soil under their magboots, but also the very skin between them and the cold vacuum of space.

**Comment by Kurfursten** [comment]
I don't know how I feel about most of it but the last point is probably the biggest substantial negative. Telling jobs apart at a glance is a non-insignificant part of game design and making miners and scientists identical takes away from that. We even give virologists and geneticists subtly different labcoats from normal doctors, for example. This seems most significant on a map like roidstation where, at least what I imagine from having playtested it one time, there will be a higher than average amount of miner/xenoarch interaction with the rest of the crew.

**Comment by Blithering** [comment]
Identification is partly why I thought a plates only version might be a good idea, the visible jumpsuit underneath would give enough indication what department you're from. It does kind of look weird though

**Comment by strawberrytan** [comment]
A really janky solution to occupation recognition would be the suits starting off unusable or softsuit tier with no resistances, but constructed with a stash of modification kits in cargo locked and science locked lockers respectively with coloured shoulders or something

**Comment by jknpj** [comment]
@Kurfursten you've still got their ID, bags and belt to tell them apart. I've grow used to see assistants and clowns using atmos hardsuits only to be given away by their bag, i don't particularly see it as an issue.

**Pull request merged**
