### PR TITLE
Kill SPS 2: The Double Tap

### PR DESCRIPTION
**Pull request by ghost**
Because @drawsstuff said I didn't have the cajones. Alternate to #26671. 

:cl:
 * rscdel: Removes the SPS from security boxes, HoP locker, and Captain locker

### CODE REVIEW

**Comment by anunknownentity03** [comment]
i love it :)

**Comment by drawsstuff** [comment]
he actually did, the absolute mad lad

**Comment by ghost** [comment]
This is a meme PR.

**Comment by west3436** [comment]
secmains seething

**Comment by ghost** [comment]
Too controversial, too bold, too dangerous for our time.

**Pull request closed without merging**
