### PR TITLE
Synergy 2.0

### PR DESCRIPTION
**Pull request by Viciousaurus**
Like an stranged father seeking redemption, I am once again working on my little project, Synergy.

synergylat

This update/rework aims to remove unneeded extra space from the map and make it a bit more suitable for the lowpop that I often see it played on.

Notable changes:

- Westside hallway have been reshuffled, saving space and moving some offices closer to the main hallway.

- The zoo is now smaller and it shares it's former space with a more centered EVA storage.

- Brig has been shrinked while being faithful to it's core design.

- Northern maintenance tunnels have been expanded.

- Trader ship is a bit fatter.

- Some hallways are slightly shorter.

- Added some directional signs pointing towards the chapel, trader dock

- And a lot of minor changes all around

As I had to move large chunks of maps, a lot of misplaced items are to be expected.

Been away from github for a long time so I fucked up the first PR, time for rounds two.

[general]

:cl:

 * tweak: Synergy has been reworked a bit.
 * rscadd: Added more directional signs

### CODE REVIEW

**Comment by Dacendeth** [comment]
Can you make the plastic flaps in the south west maint airtight this time around, they're kind of pointless otherwise.

**Comment by DamianX** [comment]
I'd just make them walls, not sure why I went with flaps in the first place.

**Comment by Viciousaurus** [comment]
I'll get down on that once I figure out what the fuck is going on

**Comment by RaccoonBro** [comment]
I beg you to center the SS13 logo under the arrivals shuttle doors, just move it two tiles to the left

**Comment by RaccoonBro** [comment]
Some tidbits:

- I don't think the new maintenance tunnel to the west of Escape adds anything. Having it be open to space helps make Escape feel less claustrophobic.
- The lounge in Science feels awkward with it being in the hall and with the pane window to the right. Consider expanding the library to the east a bit and making it into a combo library/lounge setup. If ya really wanted you could move it to the connecting hallway between Science and Medical to give both departments a place to chill.
- Add a vending machine or two to the halls outside Chapel. Long day at the gym will work up a hunger.
- Don't shy away from having windows in maint, they help break up the look a bit and can be handy to have around. Take a look at Box, most of the maintenance tunnels that touch space have windows!
- Likewise, don't shy away from having parts of maint be one tile wide, at least in parts. It also works to change up the feel of maintenance. Box/Deff/Roid/Meta vary the width of the maintenance halls to good effect.
- Final maint thing: part of what makes maint on other maps feel good is how much straight up junk is in there. Random wood barricades and grilles, pointless walls, small side rooms that serve no real purpose, etc. It's all fluff, and it certainly doesn't need to be to the level of Deff's maint, but it helps make it feel good.

Synergy is a really comfy map, the departments themselves are fantastic. Good stuff.

**Comment by Pancakemines** [comment]
A few more ai holopads would be nice, off a quick glance and memory I think at least they're missing in medbay, mechanics, cargo, probably a few other places that they're at usually on other maps. I know we all hate ais but at least this way you can force them to talk to you and distract their all seeing eye. The brig one also doesn't quite reach interrogation which is probably for the best but up to you, I think this is also the map where the detective has no access to interrogation which is a bit annoying if you want to collect/pass off evidence.

**Comment by Eneocho** [comment]
Add fucktons of main pill locations please.

**Comment by Viciousaurus** [comment]
Diffbot keep shitting itsef for no reason so I'll try one more time with a clean repository.

**Pull request closed without merging**
