### PR TITLE
Enigmatic Extraterrestrials (EETs)

### PR DESCRIPTION
**Pull request by Kurfursten**
eet **Something is out there...** eet

EETs are a new sort of mini-antag that will test the limits of how well our playerbase can control itself. It's a little ambitious but I think we're ready. EETs come in two flavors: Hostile (HEET) and Peaceful (PEET). Only the former are valid, and the latter do not have typical antag freedom to kill people on a whim. Like with any ambiguous antag, the crew will have to suss out which valids can be claimed. EETs will be announced by command report 5 minutes after they become active as a faction.

**Objectives**: EETs are unique in that they always share the same 2 factional objectives, but each gets 2 personal objectives as well. Personal objectives often involve strange things, like performing implant surgery, spreading their religion, collecting station literature, taking photos of various species, or vacationing in high risk areas such as the brig. HEETS can also have objectives to spread a virus or destroy NT data, or even murder.

Other objective ideas I've had: spill radium, receive hugs, hear speakers, acquire trash items, disable cameras, disable common radio, 

No matter what, though, their faction objectives are always to collect 10,000 welding fuel for their shuttle's main core and to ensure all EET minds, whether HEET or PEET, are onboard their ship at the end. But wait, what if the crew kills some of your HEETs and won't allow them to be cloned? Not to worry, their mind can be preserved in the Enigmatic Continuum if retrieved. Think of these minds as blob eyes; they can float around and talk to the other EETs with telepathy (unless muted) but otherwise are no longer a nuisance to the crew.

---

Obviously, this is deeply WIP. I'm putting it up now so people can talk about it and so that I can have access to it on my 3 different computers more easily.

Objectives
- [x] Acquire books
- [ ] Spread virus
- [ ] Delete data
- [x] Eat nutriment
- [x] Give implants
- [x] Refuel ship
- [ ] Open bank account
- [x] Escape with minds
- [ ] Sample organ
- [x] Photograph species
- [ ] Spread plants
- [x] Spread religion
- [x] Replace organs
- [ ] Vacation in high risk area

Items
- [x] Mind chip
- [ ] Enigmatic implant 1
- [ ] Enigmatic implant 2
- [ ] Enigmatic implant 3
- [ ] Enigmatic implant 4
- [ ] Enigmatic implant 5
- [ ] Enigmatic implant 6

Structures
- [x] EET Ship Core
- [x] EET Archive
- [x] EET Continuum
- [ ] EET Datacore

Mapping
- [x] Area coded and defined
- [x] Mothership first draft
- [ ] Mothership final draft

Dynamic
- [x] Midround ruleset
- [x] Role defined
- [x] Faction defined
- [x] Equip EET
- [x] Logo
- [x] RoleHUD

### CODE REVIEW

**Comment by aceedex** [comment]
Ayy lmao

**Comment by DrSnips** [comment]
Lacks YEETs. SMH TBH fam.

**Comment by ghost** [comment]
I like it except for the ban baiting part with having a friendly variant. Imagine a wizard could spawn in friendly and you'd punish people for shooting them on sight.

This is vox inviolate all over again.

**Comment by Kurfursten** [comment]
It's inspired by a mode that TG has called Syndicate Traitor. In that mode any crewmember could be an antag but not all of them are so you have to figure out who is valid to kill with careful observation.

I figured if TG can handle that level of restraint, we can.

**Comment by bathosbathtime** [comment]
I'm hoping the YEETs can't launching fireballs out of their mouth or blink around a room, giving you time to be able to interact with them before the valids are collected.
I like the friendly version as it can add a lot more psyop, you know?

**Comment by ghost** [comment]
By psyop you mean crew forcefully playing nice due to OOC protection?

**Comment by Kurfursten** [comment]
It's IC protection, here's the command report

>"The unitary collective of aliens which top Nanotrasen xenologists hae dubbed \"enigmatic extraterrestrials\" has been spotted in your sector of space. Regard them with caution but not outright hostility. The aliens should be presumed friendly until proven otherwise. Good luck in establishing the future of our diplomacy with this little understood polity."

Like I said in the OP, I know it's ambitious to expect our playerbase to be able to determine if someone is valid *before* shooting, but based off experience from modes like Traitor and Vampire I think we are ready for something like this. Almost every shift of SS13 requires you to carefully scrutinize at least one individual to figure out if they are disloyal (even ops and wizard can go quiet...); modes like blob where there's no ambiguity at all are really the exception.

**Comment by spoonylove** [comment]
Are they squids?

**Comment by Kurfursten** [comment]
As the icon implies they are greys 
eet

**Comment by SonixApache** [comment]
ayy lmao

**Comment by Zth--** [comment]
What happens when they get back home? the round ends? the guys get deleted?

**Comment by Kurfursten** [comment]
They hang around doing their stuff indefinitely, the round is not ended by them.

**Comment by Hoshi-chan** [comment]
I don't really understand the concept here. So they're like alien tourists, but also vox raiders? Are they just going to be greys?

**Comment by Kurfursten** [comment]
No, tourists are Arthur's miniantag idea, you can talk to him about their development, but as of yesterday I know that he hasn't moved forward much with the project.

Yes, they will be greys.

**Comment by SirSkeleto** [comment]
leave x amount of floor pills
have x people consume your floor pills

**Comment by Coxswain-Navigator** [comment]
I honestly love this. Really hoping they get some sort of UFO to fly around in, maybe making them only able to use that one grey language? However, I have one concern with this. While HEET's having antag freedom sounds good on paper, its probably just going to result in a bloodbath every time. Perhaps they should be discouraged from unnecessary killings, unless it directly correlates to their objectives. I would just be really disappointed if this got merged and HEET's ended up being like ops where they just murder everyone in sight. Might also want to consider a way to bring the murder victims back into the round in some way, shape, or form.

**Comment by Kurfursten** [comment]
They already have a UFO, the design is subject to change. It is red and white themed.
They already speak Grey quacks only but I was thinking of changing it to outright wingdings

I wouldn't worry about them being like Ops, a big part of ops is access to bombs and C20rs. EETs will be more about teleportation power for infiltration/exfiltration, abductions, etc.

**Comment by Arthurdentist** [comment]
is there anyway you could make them obviously distinguishable from normal greys? Not really sure what that would be but I think it might be helpful

**Comment by Kurfursten** [comment]
They will be wearing the grey space suits which are orderable from cargo but no one normally orders it, and in the future I plan to make them speak in Wingdings so that will make them obvious.

They won't be glowing or anything though, so if they take off their suit you may have to rely on manifest like with nuke ops or vampire (though, note, that nuke ops don't get announced by command report so they can be stealthier)

**Comment by agentofzog2** [comment]
Seems like it would be pretty boring for the nonantag variant if you can't speak with the crew.

**Comment by Kurfursten** [comment]
You can still mime

That being said the launch version probably won't have wingdings (or even all the implants, objectives, tools, etc. I'd like). Rather than ship something all at once like Cult3 it's more likely to go on as something we experiment with and develop over time with player feedback, like we did with ninja. (still an evolving situation)

**Comment by Kurfursten** [comment]
At Probe's urging I will look into making forward progress on this some time this week

**Comment by Kurfursten** [comment]
Wow, 3 weeks went by fast. This is still on my radar but I'm clearly not holding up my end on this.

**Comment by Probe1** [comment]
:(

**Comment by SonixApache** [comment]
rip

**Comment by Eneocho** [comment]
Would love to see this being revived.

**Pull request closed without merging**
