### PR TITLE
Temporarily removes the ability to pick up projectiles while they're timestopped

### LINKED ISSUE #10856: Fireball explodes A LOT if picked up while timestopped and thrown
Well, sometimes it fails to explode at all, sometimes it explodes once, and sometimes it explodes multiple times. I thought I had the circumstances worked out, but apparently not. I THINK it has to do with how many objects are either where it hits or near where it hits or something, but I can't seem to reproduce it reliably. Bauds can confirm it happened several times on the testing server, but I failed to narrow down exactly what made it explode multiple times.

Projectiles can still only be picked up while timestopped, but it's quite buggy, in this way as well as others. Perhaps the ability to pick up projectiles at all should be removed until it's made less buggy.

### PR DESCRIPTION
**Pull request by Exxion**
I intend to fix the bugs later and bring this back, but the bugs are too bad to leave in in the meantime
Especially #10856

Closes #10856

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Oh no, not the temporary removal again

**Comment by Exxion** [comment]
Even if I do never get around to fixing it, there are like eight people total who know you can do it anyway
I doubt anyone will miss it

**Comment by Shadowmech88** [comment]
Would it be THAT much more difficult to simply prevent _specifically_ picking fireballs up until you fix the issue with them?

**Comment by Exxion** [comment]
No, it wouldn't be difficult at all
But that's not the only associated bug
Only the most major one and the only reported one
And fixing everything properly isn't so easy

Other bugs include:
1. The same projectile can be used multiple times because it slips out of your hand after timestop wears off but your hand still holds a reference to it so you can retrieve it from nullspace after it's `qdel()`ed and throw it even after it's already hit something
2. Throwing it while outside of timestop is exactly the same as throwing it inside timestop
3. Some really weird and esoteric shit that I haven't really figured out yet, but is definitely not working properly

**Comment by Exxion** [comment]
Fuck it, I'll just fix it properly

**Comment by ghost** [comment]
@Exxion https://www.youtube.com/watch?v=rcjpags7JT8

**Comment by Exxion** [comment]
To be fair, I'm basically always busy with actual life stuff
But I have some free time for a while now, so maybe I'll fulfill a handful of promises

**Pull request closed without merging**
