### PR TITLE
Changes terrible placeholder with less terrible REFERENCE

### PR DESCRIPTION
**Pull request by jknpj**
muh references

Because the precious placeholder didn't even had proper icons for all dirs. Also made it check for artifacts so they don't get magically deleted, just pierced through.

:cl:
 * imgadd: The large artifact "gigadrill" is now a shameless TTGL reference.

### CODE REVIEW

**Comment by N3X15** [comment]
Gonna leave this open for a bit for feedback purposes.

**Comment by Aurx** [comment]
Way, WAY too blatant.

**Comment by ghost** [comment]
I know we're full of references but we don't need more. Could have just made any kind of riding drill instead.

**Comment by ghost** [comment]
>Also made it check for artifacts so they don't get magically deleted, just pierced through.

What does this mean for those of us who have never touched xenoarch? Can you just hold down a button and find all artifacts?

**Comment by jknpj** [comment]
@Unknown-as-Captain it means instead of ignoring and qdeling the artifacts inside it'll break them just like a drill would.

**Comment by jknpj** [comment]
@SarahJohnson489 feel free to sprite it. I am merely using what i already had done, i just want to get rid of the current 2-sprite placeholder.

**Comment by Shadowmech88** [comment]
Reference or not, I just don't like the idea of Lagann being reduced to nothing more than a simple rock-breaking vehicle.

I think it would be far more appropriate as an adminbus mech.

**Comment by jknpj** [comment]
Some madman mailed me actual sprites, lemme remake it

**Pull request closed without merging**
