### PR TITLE
Makes hearts fly off of human heads when you headpat them

### LINKED ISSUE #13560: Head pat inconsistency
I have noticed that head pats as they currently exist are inconsistent with the previous feature involving Ian.  Hearts appear above a corgi's head when you pat it.  I propose we expand this feature to the full range of all things that can have their head patted now.

### PR DESCRIPTION
**Pull request by RFultra**
Fixes
#13560

:cl:
 * rscadd: Fixes an inconsistency between corgi and human head patting

### CODE REVIEW

**Comment by TheFriggenSawbones** [comment]
fuck you and die

**Comment by ultraplen** [comment]
leave the server and never come back

**Comment by RFultra** [comment]
never

**Comment by salamandooo** [comment]
no one can provide a reason not to merge this, and that's a fact

**Comment by ChugMonkey** [comment]
Now I can watch as my waifu's enjoy my head pats! Great addition 10/10

**Comment by Riekland** [comment]
head patting should have never been implimented and the only people who use it all deserve bans for borderline erp

**Comment by yclatious** [comment]
>no one can provide a reason not to merge this

Do you really, and I do mean _really_ want to be chased down by guys like avada and be called CUTE, CUUTE all the time as they just furiously headpat anything and everything.

I mean, if you don't, you are a well adjusted member of society that doesnt seek fake affection from 2d avatars of some of the most autistic human males to exist, but if you, hot diggity damn, Id sooner run into a super matter crystal lake than be that desperate tbqhwyfampaichi

**Comment by Chazach** [comment]
every emoji on this comment will be counted as a vote to repo ban emilia

**Comment by ghost** [comment]
>reason not to merge

Emilia didn't even make a new sprite, if this is merged it would mean that by VG lore Ian is a human as human's getting headpatted and Ian getting headpatted both cause a similar magical reaction of a pink heart appearing. Effectively this ruins asimov, the AI can no longer confirm the humans are not just very weird corgi's. This also would affect vox and greys, making them part of the human-corgi species.

Issac Asimov didn't think of this when he wrote his books.

**Comment by Moonman1946** [comment]
made an acc to downvote

**Comment by salamandooo** [comment]
If you're playing as a girl you deserve to be harassed @yacalat

Men don't get headpatted

**Comment by yclatious** [comment]
>@yacalat

For a zionistic jew, id expect youd take a break from killing syrian babies to type my name right lad, cmon now.

**Comment by salamandooo** [comment]
@Donagger it'll create an extra level of complexity in ai/human interaction, improving the game

**Comment by Intigracy** [comment]
nvm shitpost all you want

**Comment by d3athrow** [comment]
headpats giving females pain killers when
gotta overdose waifus in a sneaky way

**Comment by RFultra** [comment]
Lets open this PR

**Comment by d3athrow** [comment]
Let's not

**Comment by RFultra** [comment]
Let's

**Comment by jknpj** [comment]
Please don't, you're making the same mistake i did with *vent

**Comment by Exxion** [comment]
It's a meme PR anyway
And honestly a pretty good one

**Comment by RFultra** [comment]
thanks I made it myself

**Comment by Moonman1946** [comment]
let's not do that today

**Comment by yclatious** [comment]
Begone @EmiliaMcWaifushitter

**Comment by Moonman1946** [comment]
@yclatious that's my line wtf

**Comment by liltiptop** [comment]
I'm here for the drama.

**Comment by Megamaw** [comment]
people said MY prs were bad

but then _**THIS**_

**Comment by strawberrytan** [comment]
i think it's time to re-open this

**Comment by RFultra** [comment]
Yes

**Comment by Intigracy** [comment]
I'll merge it and a pr removing headpats at the same time.

**Pull request closed without merging**
