### PR TITLE
Meta club brig remap

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[meta]
This is a full remap of the MetaClub Brig and Security Department.

The original MetaClub Brig is pictured here:
metabrigoriginal1

and it's got lots of problems:
- no Security Lobby or Desk
- no visibility on cells
- lacking gear in brig and armory
- interrogation room is offset/barely used
- brigbay is a total disaster
- two execution chambers (there's another on the off-station perma)
- no shooting range

So I've done my best to correct this. New brig is pictured here:
metabrigredo2-9

:cl:
 * rscadd: MetaClub: Full Brig/Security remap. Security now has a full lobby, new cells, a firing range, and a new office.
 * rscadd: MetaClub: Added shutters to the gateway to allow for public access.
 * bugfix: MetaClub: Fixed a floating APC, removed an extra air alarm in the Captain's office.

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
dang i kinda wanted the pax implant in the armory locker

**Comment by GeneralVeers25** [comment]
I have an alternative layout for the hallway outside the cells that expands it to three tiles.  It does shrink the lobby. I'm impartial to the change, but I wanted to suggest it here in case anyone prefers it.
metabrigredo2-8-2

Full credit to Kernikov for the suggestion.

**Comment by pedr69** [comment]
advanced first aid kit creep
interrogation observation has no intercom
removal of soul from the office area

**Comment by GeneralVeers25** [comment]
I swapped to the 3-tile hallway behind the cell block and added an intercom to the observation room above Interrogation. Updated photo in the original post.

**Pull request merged**
