### PR TITLE
Terrorist envelopes

### PR DESCRIPTION
**Pull request by Krimsonkhan**
:cl:
 * rscadd: Added terrorist envelope traitor uplink item. An indistinguishable envelope rigged to release a cloud of polytrinic acid smoke upon being opened. Can be tagged and mailed via disposals. Costs 6 TC, 5 TC for cargo techs and quartermasters.

### CODE REVIEW

**Comment by ghost** [comment]
I feel like this will make people unnecessarily paranoid about opening envelopes. Something less powerful or more subtly annoying (silently infecting the opener with some kind of virus?) would make antagonizing less obvious when envelopes start getting sent around.

**Comment by Krimsonkhan** [comment]
Yeah I could see that. Originally I was going to make it something like that but I thought it would be too weak. You think it should be a random virus or something more specific?

**Comment by DrSnips** [comment]
I like the idea behind it but the issue with pacid smoke is that it destroys it's own evidence making it a no/low risk item. If you keep pacid smoke maybe bump up the cost by 2 or 3.

**Comment by Krimsonkhan** [comment]
Envelopes are so underused now anyways that this would probably just fuck that up even more. I like the idea of mail terrorism but maybe as an uplink item it is not the best of ideas. People can always just add a proximity sensor assembly to a crate or something. I am going to close this PR after giving it a little more thought.

**Pull request closed without merging**
