### PR TITLE
Moves Challenge.dmm to broken folder

### PR DESCRIPTION
**Pull request by Probe1**
I have no idea why but it causes quite a lot of lag.  Furthermore, with the new away mission loader landmarks may not be functioning as intended and it needs to be fixed before it is used on server.

### CODE REVIEW

**Comment by Probe1** [comment]
also ten to one its beams and we should end up scrapping it in favor of a redesign from the bottom up.

**Comment by ComicIronic** [comment]
You shouldn't scrap old systems just to rewrite them, it introduces more bugs for little payoff.
Nexis beams need a cleanup, but they're a good system besides.

**Comment by Probe1** [comment]
I didn't say to scrap beams.  Challenge was designed with a different kind of beams and a landmark system.  At this point it needs a remake.  Either way it's causing a lot of lag when it's loaded and this should be merged to keep people from loading it

**Comment by Intigracy** [comment]
Challenge was designed with the old projectile beams in mind.

**Comment by Probe1** [comment]
holy shit this wasn't merged yet?

what part of "its broken please merge" was difficult to understand

**Comment by 9600bauds** [comment]
Was bought over by a picture of many chicks I have no option but to merge now

**Pull request merged**
