### PR TITLE
Adds shitty sprites for shrapnel

### LINKED ISSUE #8066: Bullet shrapnel has no sprite
Specifically bullet shrapnel removed via surgery

### LINKED ISSUE #8215: Missing or Orphaned Sprites
I've got two sprite issues needing to be looked at, one more important than the other.
Firstly, Bullet Shrapnel. It counts as an object you can pick up when removed and cuts like glass if stepped on, which is bad for freshly stripped patients, but also means without alt clicking you cant pick it up. Could be really dangerous for any naked crew members being worked on as being placed there could cut them up if not cleaned.

Secondly, Plasterer's jacket, the yellow and green one from the Costume Autodrobe hides your uniform while its equipped, showing you in your skivvies and a jacket, probably not as intended but could be used to hide objectives if found out.

### LINKED ISSUE #8457: Invisible "Shrapnel" coming from Crossbows
One round on Deff as raiders, I found myself stepping on Glass shards for no reason on the ship.
Alt+clicking showed an invisible item labelled "Shrapnel". If it isn't a roundstart thing, I have no clue where the hell it came from. It was in the cockpit of the ship, under one of the chairs I believe.

### LINKED ISSUE #13990: (Bullet) shrapnel has no sprite and acts as broken glass when on the floor
#### Description of issue

Bullets and shrapnel that get stuck in a wound can be removed through surgery, but when removed they have no sprite.
Furthermore, stepping on the shrapnel gives you a *You step in the broken glass!* message.

### PR DESCRIPTION
**Pull request by SonixApache**
Glass shards painted non-translucent black.
fixes #13990, fixes #8066, fixes #8215 (CELT DIDN'T MENTION IT WHEN HE FIXED IT), fixes #8457

dreamseeker_2017-03-12_10-06-39

*There's something inside the unknown's chest, but you just missed it this time.*
I'm going to add a fucking golden hemostat next, fuck this
**tested**

:cl:
 - imageadd: Shrapnel (from bullet wounds) now has sprites.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Those are *really* bad.
At least darken the bright parts, as-is it literally just looks like grey glass.

**Comment by SonixApache** [comment]
well i mean it literally is just glass, but alright

**Comment by SonixApache** [comment]
how's this newsprite
newspritebig

**Comment by Shadowmech88** [comment]
Better, looks more like chunks of metal now.

**Comment by SonixApache** [comment]
Note that those are seperate sprites, not just one.

**Comment by diammz** [comment]
the outlines are supposed to be dark unless you want to portray transparent objects

**Comment by Shadowmech88** [comment]
You should probably update the images in the OP.

**Comment by SonixApache** [comment]
OP updated

**Pull request merged**
