### PR TITLE
Nuclear Operatives Holosuits and Strategic Station Holomap - Part 2: Map changes

### PR DESCRIPTION
**Pull request by JMWTurner**
strategic

:cl:
- rscadd: Added Strategic Holomaps at the Syndicate Bases of box, deff, meta, and taxi.

### CODE REVIEW

**Comment by JMWTurner** [comment]
@Intigracy @ComicIronic Part 1 got merged, here's the map changes.

**Comment by PJB3005** [comment]
> Taxi but not Bus.

👏 

Bus worst map ever.

**Comment by JMWTurner** [comment]
@PJB3005 I planned to add them to bus and mini as well but I can't open either in DM.

In the case of bus it's because /obj/item/weapon/aiModule/core/celtic and /obj/item/clothing/glasses/night are undefined.

**Comment by PJB3005** [comment]
Don't even bother nobody cares about those maps anymore.

**Comment by JMWTurner** [comment]
Fixed the Defficiency conflict

**Comment by JMWTurner** [comment]
This PR was meant to be merged at the same time as Part 1, just saying.

**Comment by Intigracy** [comment]
Wait, is this just a map on the syndicate outpost? Is that even useful at all, considering the shuttle leaves?

**Pull request merged**
