### PR TITLE
Fixes loaded rotation of some items

### LINKED ISSUE #32095: Ejected TEG vault can spawn rotated and that breaks all the piping.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
Title

### LINKED ISSUE #32103: Hobo hut not rotated properly
image

### PR DESCRIPTION
**Pull request by ghost**
image
Closes #32103.
Closes #32095.
[bugfix][vault]

:cl:
 * rscadd: Pipes in space hobo shacks are now found in working condition much more often.

### CODE REVIEW

**Comment by Eneocho** [comment]
This fixes all pipe rotation issues? You can whitelist some of the vaults with piping issues then.

**Comment by ghost** [comment]
> This fixes all pipe rotation issues? You can whitelist some of the vaults with piping issues then.

Will try this, but a lot more are also not whitelisted for disposals pipe issues, which I want to fix in this PR but doesn't work yet.

**Comment by Eneocho** [comment]
Since you're on the fixing rotation stuff on this PR, can you fix tile painting rotation? Some of the vaults, such as spessmart, have tiles with warning lines that get messed up when rotating.

**Comment by DamianX** [comment]
Prepare for unforeseen consequences

**Pull request merged**
