### PR TITLE
Computer On/Off Animations

### PR DESCRIPTION
**Pull request by gurfan**
https://user-images.githubusercontent.com/51427771/184977960-f9050273-dc77-437b-aef8-9aeb80171bab.mp4

special thanks to primeD

## What this does
Computers now have on/off animations.
There is a small delay before computers turn on/off when gaining/losing power from an APC. This is to make losing power look more 'natural' (see video above)
This delay does not happen when you dismantle/construct/wrench computers.

## Why it's good
It looks nice.

## Changelog

:cl:
 * imageadd: Computers now have on/off animations.

### CODE REVIEW

**Comment by ExpulsionSnooper** [comment]
SOVL

**Comment by djkramer123** [comment]
the pr that saved /vg/

**Comment by Eneocho** [comment]
Sovl...

**Comment by WindowsErrors** [comment]
don't merge it let's see if we can get to 100 pending pull requests

**Comment by Eneocho** [comment]
>don't merge it let's see if we can get to 100 pending pull requests

Speaking of, why the lack of merges lately? Even bugfixes or hotfixes are pending.

**Comment by PrimeDSS13** [comment]
special thanks to you for actually doing it the madman

**Comment by WindowsErrors** [comment]
it might have to wait, we're already at 60, at this rate it'll take only two or so weeks

**Comment by ExpulsionSnooper** [comment]
Now we need just lights flickering off when the power dies for maximum atmosphere.

**Comment by WindowsErrors** [comment]
dang we totally could have gotten to 100 though

**Comment by Eneocho** [comment]
>dang we totally could have gotten to 100 though

And give the collabs a rest? Never. NO SOLACE FOR HE WHO DOES IT FOR FREE.

**Pull request merged**
