### PR TITLE
Space Gorillas

### PR DESCRIPTION
**Pull request by jewishneocon**
we finally in the gorilla game
ayy
oo oo ah ah banana

### CODE REVIEW

**Comment by Boxe** [comment]
why doesnt it cry for booty borgs

**Comment by jewishneocon** [comment]
busta somehow only left an unimplemented gorilla sprite, no gorillionaire sprite (I know a screenshot of it exists)
thats can be added

**Comment by d3athrow** [comment]
just ask him on steam

**Comment by 9600bauds** [comment]
where's pas

**Pull request merged**
