### PR TITLE
Robo cryo rework revival

### PR DESCRIPTION
**Pull request by SonixApache**
revives #24195
🆑 included

looks like this

### CODE REVIEW

**Comment by brndd** [comment]
Those "Active" and "Vicinity" buttons need to be aligned with the buttons above them.

**Comment by SonixApache** [comment]
I agree, but I'm not even going to attempt to make any changes to the UI.

**Comment by MadmanMartian** [comment]
Reason they don't align properly is that the class a button is automatically given leans to the left, so comes before any text given even if it leans left as well.

Was not fun to wrestle with

**Comment by brndd** [comment]
I created a button helper back when I was messing with nano that should ... help with that. Can't remember the syntax, but the State Laws UI uses it.

Unless those are made using said button helper in which case 🤷‍♀️ and looking at them they aren't even HTML buttons but rather just nanoui links.

**Comment by MadmanMartian** [comment]
The nanoui links become HTML during the loading process. You could provide an override class as the fifth argument. That could work.

https://github.com/vgstation-coders/vgstation13/blob/18e97bcc9ef7a36d26491db3febe60c6466fe9fb/nano/js/nano_base_helpers.js#L25

**Comment by Probe1** [comment]
So does this work?

**Comment by SonixApache** [comment]
"I tested it"
It works as well as it did in the last commit of the previous PR, the UI is decent, just not perfect.

**Comment by MadmanMartian** [comment]
tell me how it goes

**Pull request merged**
