### PR TITLE
Debit Cards, Bank Account Disable, & Other Retrofits

### LINKED ISSUE #19322: Custom vendors not trader-friendly, and go by ID name rather than linked account
#### Description of issue
Two seperate issues here.
One, the custom vendor is pretty much useless to the job that it should be the most useful to, since they can't turn off edit mode on the vendor as vox IDs are NOT account linked, and even if they were, it wouldn't work because...
Two, the vending machine checks for name rather than linked account. This is obviously NEVER going to work for traders, and it makes it a fair deal easier to spoof, especially by someone with an agent ID.

#### Difference between expected and actual behavior
Traders should be able to use the custom vendor to facilitate easier trading, however the way it's set up doesn't let traders use it at all.
Traitors should not be able to steal everything from said vendor simply by purchasing an Agent ID and changing the name to "Trader Shoal", but they can totally do that.

#### Steps to reproduce 
Attempt to use a custom vendor as trader, realize your ID doesn't work, ahelp to try and find some sort of solution, be absolutely bewildered when account linking doesn't fix it until you go code diving and find, for some reason, it goes off of name.

#### Specific information for locating

Because of aforementioned code diving, I have the exact location of the offending code.
https://github.com/vgstation-coders/vgstation13/blob/61e36ee262535713912d9bafbc80661b6eb54dd3/code/game/machinery/vending.dm#L476-L489
However, just changing it to check the account on the ID will NOT make it work for traders, as their IDs are not associated with the account.

#### Length of time in which bug has been known to occur

Ever since #18921 was merged.

#### Server revision

Game: 49b9a131db5a4e9882dc337351967d95077decea 
Patches: 998316155b9c9210ca3d87fb7313d9cf2b30f871 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by WhiteHusky**
Adds in debit cards which only hold account information so they can be given to someone else, such as a subordinate, to charge from your account. ~~Assuming they know your PIN or downgraded your account security.~~ Unless the bank account is at security level 3, the debit cards can be swiped without PIN.
image

New debit cards can be created from an ATM
image

Debit cards can be used inside a ATM
image

Debit card
image

Debit card when spawned in without a account number
image

Department debit card
image

Captain or Elite debit card
image

Department debit card when spawned and var edited in.
image

Be *that person* and flash your debit card
image

Define authorized users for debit cards
image

Authorized users are recorded in the transaction log
image

Debit cards can be used at the supply/order console
image

Debit authorized names are recorded
image
image

POS' now show the account name
image

**TODO:**
- [x] Debit card(s) to the trader shuttle.
- [x] Debit cards on each department's desk ~~for everyone to steal and waste it all on surprise pizzas~~
  - Actually in each head's locker.
- [x] Debit cards to be accepted at ATMs

Fixes #19322 
:cl:
* rscadd: Debit cards can now be printed from a ATM for $5, allowing traders and department heads to print off cards that can be used.
* tweak: Debit cards don't require a PIN when swiped at a merchant. Unless it's account level 3 then it'll ask for PIN.
* rscadd: Department heads get a debit card for their department in their lockers.
* rscadd: Traders get a debit card on their shuttle computer.
* rscadd: Bank accounts can be disabled by the user or by an admin from the database database. User disables can be removed by the user, but administrative disables have to removed by the admin.
* rscadd: Supply and Order consoles can now read from a debit card.
* rscadd: Supply Orders and request forms mention the authorized name if a debit card was used.
* rscadd: POS' now show the account name being used
* tweak: Card flow now checks if the source account and destination account is the same, ignoring the available funds.
* tweak: Card flow has been changed to support debit cards.
* tweak: Retrofitted several machines to use the new charging flow and/or accept debit cards.
* tweak: Card flow messages show which card is being used.
* bugfix: POS' will use the station account if for some reason the linked account got unlinked for any reason.

### CODE REVIEW

**Comment by jknpj** [comment]
door keys when

**Comment by Kurfursten** [comment]
Seems to have interesting potential with departments like medbay or engineering where subordinates might want to borrow money from the dept acct.

**Comment by WhiteHusky** [comment]
Well I didn't understand what I was doing and botched a merge.
Now I lost the work I did and I'll have to figure out if I can restore or if it's gone.

**Comment by WhiteHusky** [comment]
So far this is mostly complete. Probably need to do a few more tests since I've done a few changes without checking if they worked.

New addition is that debit cards can be swiped without a PIN, as defined by a global, just for the anarchy that might entail when heads have a chance of being robbed of their debit card for shenanigans.

**Comment by WhiteHusky** [comment]
Added account disabling in case the rampant account fraud becomes a problem for someone.

**Comment by WhiteHusky** [comment]
Add a way to add authorized user to the card so you can figure out which card is being used by who. Of course it won't prevent McAssHat from using the card as The Captain.

**Comment by WhiteHusky** [comment]
Supply computers can now read from a debit card

**Comment by WhiteHusky** [comment]
Again. Finished.
Assuming I don't think of something else to wedge into this PR.

**Comment by MadmanMartian** [comment]
Feature creep can come after ingame evaluation/testing

**Pull request merged**
