### PR TITLE
Add the full Inquisitor set to the Chap's vending machine

### PR DESCRIPTION
**Pull request by ghost**
I've been asked to add the Inquisitor set to the Chaplain's vending machine. It's a full suit of religious garb that prolly works for a few religions, two per like the rest, not premium. I think this should work fine for people who want more Barbie dress-up options. The inquisitor suit is technically a bit more robust than the rest tho, if that matters

chap_vend

:cl:
 * rscadd: Added the full Inquisitor set to the premium items in the Chaplain's PietyVend vending machine.

### CODE REVIEW

**Comment by Hoshi-chan** [comment]
Ah, more chaplain powercreep...

**Comment by ghost** [comment]
If needed, I can bring the suit down to normal suit armor ranges, aka 10, 5. Either that or put it in Premium. Either would work for me, I just don't want to dunk on an item I didn't code

**Comment by Dacendeth** [comment]
This should be premium like the other armored priestly outfits you get from that vendor.

**Comment by SGuivenne** [comment]
Only if we can turn our Null Rod into a Bolter.

**Comment by jknpj** [comment]
They are an armored wizgarb, so might be better to keep them as premium items

**Comment by OceanMonn** [comment]
Honestly, yeah just make em premium

**Comment by KingofHONK** [comment]
always in favor of WH40k shit to fuel the fucking AUTISM

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
make em premium

**Comment by ShiftyRail** [comment]
>requesting changes for something that's not a problem in code quality

**Comment by MadmanMartian** [comment]
Inquisitors clothing actually has armor to it

>head
armor = list(melee = 0, bullet = 0, laser = 15, energy = 15, bomb = 0, bio = 0, rad = 0) 
>suit
armor = list(melee = 40, bullet = 25, laser = 5, energy = 0, bomb = 0, bio = 0, rad = 0)


Slightly less armored helmet, but more armored suit than the templar set, which is under premium
>head
armor = list(melee = 20, bullet = 5, laser = 2,energy = 2, bomb = 2, bio = 2, rad = 0)
>suit
armor = list(melee = 40, bullet = 5, laser = 5, energy = 5, bomb = 0, bio = 0, rad = 0)


The inquisitor armor's meant for a deathsquad-like that deity was coding. If it's going to be added at all, it should be under premium.

As a collab, you're also to review balance, not just code quality, or would you prefer to be in dabville right now?

**Comment by ShiftyRail** [comment]
Still not a code quality problem
Not that the changes shouldn't have been made

**Pull request merged**
