### PR TITLE
TGUI Exosuit Control Console

### PR DESCRIPTION
**Pull request by gurfan**
oUqHl0RARU
oUqHl0RARU

:cl:
 * imageadd: The Exosuit Control Console uses a fancy new TGUI.

### CODE REVIEW

**Comment by BomberBro** [comment]
>tweak

Extremely debatable. Regardless, it should also instantly gib the roboticist.

**Comment by gurfan** [comment]
> > tweak
> 
> Extremely debatable. Regardless, it should also instantly gib the roboticist.

You were still able to destroy mechs with the console before this, you just had to repeatedly press the detonate button because of the convoluted way it worked before.

**Comment by SonixApache** [comment]
>tweak: Detonating a mech using the console now immediately destroys the mech.

yeah, okay, separate that

**Review by DamianX — APPROVED** [review]

**Comment by gurfan** [comment]
> > tweak: Detonating a mech using the console now immediately destroys the mech.
> 
> yeah, okay, separate that

ok

**Comment by Kurfursten** [comment]
Confl

**Comment by gurfan** [comment]
Confligs fixed.

**Pull request merged**
