### PR TITLE
Deletes the airlock painter which has no function or icon from metaclub.

### PR DESCRIPTION
**Pull request by Probe1**
Closes https://github.com/d3athrow/vgstation13/issues/8781

### CODE REVIEW

**Comment by Konater** [comment]
rip

**Comment by Probe1** [comment]
The coffee is delicious.

**Comment by Kurfursten** [comment]
I think @autismspider wants it

Why don't you fix it instead?

**Comment by ihadtoregisterforthis** [comment]
F

**Comment by ComicIronic** [comment]
Goodbye you little shit

**Comment by Kurfursten** [comment]
Merged 11 minutes after being posted? Metaclub on metaclub.dmm

**Comment by Probe1** [comment]
It hasn't worked for over a year and I only changed one thing.  People are 100% welcome to fix it but since it took two months and me doing it myself just to remove the broken item from the map I doubt the interest is just gonna appear any time soon.

**Comment by Intigracy** [comment]
Remind me in June off it's not done yet.

**Pull request merged**
