### PR TITLE
Combining Changeling's Transform and Change Species

### PR DESCRIPTION
**Pull request by adacovsk**
Currently, Transform and Change Species are separate and I don't understand why. It causes some sprite issues if you transform into someone from another species, like a bugman. There isn't really a good reason to change your species **only** because it's really sus too. Basically, you look retarded and people know you're retarded

## What this does
I modified Transform to also include Change Species

## Why it's good
One less icon... Streamlined

## Changelog
:cl:
 * tweak: Combined Changeling's Transform with Change Species into one button

### CODE REVIEW

**Comment by Eneocho** [comment]
You can transform into a skrell and buy canned bread, that's as good a reason as any to have the change species power.

**Comment by adacovsk** [comment]
> You can transform into a skrell and buy canned bread, that's as good a reason as any to have the change species power.

You still need to have the DNA of the Skrell to transform or change species anyway. You could never change species on a whim

**Comment by Eneocho** [comment]
I know, but you can just buy the skrellcubes, ask genetics for a humanizing SE, turn the skrellmonkey into a skrell, get their genes, become the frogman then buy the canned bread.

**Comment by Killette3** [comment]
If you like retarded changeling facts consider that no matter what race you are, lesser form turns you into a human monkey

**Comment by adacovsk** [comment]
> If you like retarded changeling facts consider that no matter what race you are, lesser form turns you into a human monkey

I considered being able to take the DNA from all species monkeyforms, but the issue is that they don't have DNA and it requires more thought to actually do

**Pull request merged**
