### PR TITLE
Removes burn damage from hot liquids

### PR DESCRIPTION
**Pull request by Dacendeth**
## What this does

Removes the burn damage from drinking hot stuff, while keeping the non lethal pain.
## Why it's good

Dying from drinking stuff isn't fun or immersive, though the pain from drinking something that's hot feels flavorful enough to keep in.
## Changelog

:cl:
 * tweak: Hot liquids only cause pain and no longer cause potentially lethal burn damage.

### CODE REVIEW

**Comment by Eneocho** [comment]
I'd rather the damage is kept but capped at 5 burn tops per consumption.

**Comment by GreatBigFailure** [comment]
Making it pain/hal damage, whatever we call it, is definitely the right way to go about it. 
It means you can make full on goofy ridiculous hot drinks that pain crit people without it actually killing anyone. More fun RP and rare but unique mechanical interactions, less annoying face melting for sipping coffee

**Comment by DeityLink** [comment]
The damage is already capped. I have no strong feelings for or against this, but I would kinda wish that before merging that you would wait a week or two after #35516 (if the thermal entropy system remains), since I think having a visual feedback of a drink being too hot would change players' perception of it.

I feel like the overall soured opinion of players toward burning liquids is mainly due to that lack of signs, and it's a shame that none had been added since it was a thing, but since that's soon to be remedied, maybe you may reconsider that change.

**Comment by jwhitak** [comment]
A dude yesterday brought a lunch box into the burn chamber for me. In the time it took him to go horizontal (I was in my suit), the food + soda became fully lethal to eat. Ask me how I found out...

**Comment by DeityLink** [comment]
Well there's another issue, and it's that the damage is re-applied at each bite. So getting splashed once by 50u of  4.000.000°C water hurts much less than biting 5 times in a burger at 3.000°C, which denotes a flaw in the system. One may argue that food should just ignite at that temperature, and drinkable liquids evaporate. This would be another way to avoid the issue.

**Comment by Kurfursten** [comment]
Is this still something people want now that we have steam indicators?

**Comment by Dacendeth** [comment]
Now that steam indicators are a thing I dont really care, if someone else wants to repopen it go ahead.

**Pull request closed without merging**
