### PR TITLE
Gives plasmamen lawyers their own suit

### LINKED ISSUE #12639: 10,000 bees in a suit (but not really)
Sprites for plasmaman suits specific to beekeepers and lawyers. 
plasmalaw
buzzman
I would also like to request that the plasmaman suit orderable from cargo is changed from the assistant suit to the generic, non job specific one (that lawyers currently use).
Download link for sprites: http://s000.tinyupload.com/index.php?file_id=04078784234571162324

### PR DESCRIPTION
**Pull request by Blithering**
Adds a plasmaman lawyer suit, complete with attempt at wearing a tie.
plasmalaw

also adds a plasmaman bee suit, adminspawn only.
buzzman

Changes the suit contained in the plasmaman crate orderable from cargo from the assistant suit to the generic orange one to keep it obtainable.
closes #12639

This is my first attempt at making a PR so please make sure I haven't broken anything.
Edit: hey look, conflicts! those are things real coders have go wrong!
Edit2: It finally works! Big thanks to @Skullyton and @Probe1 and the people in the howdoicode channel for taking a weekend to explain every way I managed to break a simple task and how to fix it
:cl:
*rscadd: Adds two new plasmaman suits.

### CODE REVIEW

**Comment by DoctorMonkey** [comment]
just bee urself

**Comment by TheFriggenSawbones** [comment]
god bless you

**Comment by SonixApache** [comment]
Back up your work, update your repo, check if the stuff is still there (and put it back if it isn't) then push.

**Comment by SkowronX** [comment]
Now that you can into pr you can finally add all those other sprites you made

**Comment by Riekland** [comment]
Wait what I thought you put the bee suit in as the one botanists with the beekeeper title get

**Comment by Probe1** [comment]
He did put people said it was over the top.

**Comment by Megamaw** [comment]
why is this closed

stop having it be closed

**Comment by Blithering** [comment]
I realised how fucked the branch was, couldn't fix it once the conflicts came back. I'll open a new one once I manage to get smartgit working again and remember not to use the bleeding edge branch this time.

**Pull request closed without merging**
