### PR TITLE
Highlander Bundle for Uplink

### PR DESCRIPTION
**Pull request by small-boss**
Adds a new bundle to the uplink with the following items:

- A highlander outfit that acts as a wizard robe
- A claymore (does 40 brute damage, 1.2 sharpness)
- A pack of glue
- A vinyl for the jukebox
- A spellbook that gives the user a alternative version of mutate without the laser eyes.

The chance for getting it is 100, the standart chance.
Is it too strong/too shit? Should I make it rarer?

:cl:
 * rscadd: Added a new bundle to the uplink, the Highlander bundle.

### CODE REVIEW

**Comment by small-boss** [comment]
Feel free to give me a custom sprite for the spellbook, otherwise I'll work on something

**Comment by boy2mantwicethefam** [comment]
Absolutely based

**Comment by Kharkov72** [comment]
https://www.youtube.com/watch?v=awfKesorGyo

**Comment by small-boss** [comment]
Everything tested, made sure that it's not in the wizard's spellbook and that the original mutate doesn't get touched

**Comment by small-boss** [comment]
It's ready.

**Comment by oversane** [comment]
SCOTLAND F O R E V E R

**Comment by KingofHONK** [comment]
image

**Pull request merged**
