### PR TITLE
FUCK PLASMA. FUCK SPACE SUITS. FUCK flags = FPRINT  | PLASMAGUARD.

### PR DESCRIPTION
**Pull request by liltiptop**
I REMOVED CONTAMINATION BECAUSE CTRL-V ING flags = FPRINT  | PLASMAGUARD FOR EVERYTHING AND THEN SEEING THAT MY PULL IS FUCKED IS SERIOUSLY GOING TO MAKE ME KILL MYSELF.

YES I AM MAD.

Please test!
<3 
liltiptop

### CODE REVIEW

**Comment by gbasood** [comment]
> Please test!

disgusting

**Comment by liltiptop** [comment]
> Please test!
> disgusting

Sorry. My laptop is a toaster.

**Comment by liltiptop** [comment]
https://www.youtube.com/watch?v=4gO7uemm6Yo

**Comment by Imagebard** [comment]
>I REMOVED CONTAMINATION

ITS HAPPENING

**Comment by ghost** [comment]
But plasma contaminates things!

**Comment by Imagebard** [comment]
So does radiation but I don't see any radiation contamination system

**Comment by Probe1** [comment]
I'm perfectly ok with adding a radiation contamination system if you're volunteering to code it.

**Comment by Probe1** [comment]
>Removing contamination
 >Please test it for me

What fevered dream is this

**Comment by Imagebard** [comment]
>I'm perfectly ok with adding a radiation contamination system 

A MODERATOR BETRAYING HIS OWN PLAYERBASE
TRULY EVEN MORE DISGUSTING

**Comment by Boxe** [comment]
what's so hard about slapping the flag on a few suits?

**Comment by Intigracy** [comment]
continuous-integration/travis-ci/pr — The Travis CI build failed

**Pull request closed without merging**
