### PR TITLE
Revert "RPD immitation TGUI"

### PR DESCRIPTION
**Pull request by F-OS**
[ui]
Reverts vgstation-coders/vgstation13#35977
https://github.com/vgstation-coders/vgstation13/pull/35977#issuecomment-1965321064
> @ [Kurfursten](https://github.com/Kurfursten) 
> Personally I don't like either but you are welcome to click the revert button and see if you can get support

Looks like shit, no sovl. Doesn't properly render (at least on my machine)
Hate how much darkmode is forced too.

### CODE REVIEW

**Comment by jwhitak** [comment]
Could you open an issue with a screenshot of how it renders for you, alongside what OS/etc you're using? Even if this doesn't manage to get merged, it sounds like legitimate bugs that need fixing.

**Comment by CrazyAmphibian** [comment]
the PR was open for like, 2 weeks for you to give feedback for how it looked

**Comment by CrazyAmphibian** [comment]
couldn't tell you why there are rendering errors with the images, but that's been an issue before the new UI was merged (and is often fixing by closing then re-opening the menu or switching schematics)

**Comment by SonixApache** [comment]
don't we have a "use TGui" pref or something

**Comment by F-OS** [comment]
> don't we have a "use TGui" pref or something

I wish

**Comment by toomykins** [comment]
> don't we have a "use TGui" pref or something

we have an option for how to render tgui, but not for switching between nano and tgui. not every tgui panel has a nano alternative anyway.

**Comment by hacker-on-steroids** [comment]
>the PR was open for like 2 weeks

might come as a shocker but some people who play the game don't check the github every day, or at all
i know this because i was one of them until some schmuck broke OOC coloring when changing dark mode stuff, so i had to create an account and fix his mess

**Comment by falcon2346** [comment]
I like the new UI

**Comment by F-OS** [comment]
Still nushit tgui but the icons not rendering isn't your fault and seems some people like it.

**Pull request closed without merging**
