### PR TITLE
Remove Disease Touch from Vampires

### PR DESCRIPTION
**Pull request by gurfan**
☢️ option
## Changelog
:cl:
 * rscdel: Vampires no longer have disease touch.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
No.

**Comment by Securitymain** [comment]
grudgecode

**Comment by west3436** [comment]
[I ded]

**Comment by pedr69** [comment]
how would we make vamps/lings not shit?
it it even possible?

changing deathtouch to turn people into maint lepers instead of killing them might be more fun but i'm not gonna code it because i hate vampires

**Comment by SonixApache** [comment]
reason given: none
merges given: none

**Comment by Kurfursten** [comment]
Contentious, lacks a justification in the PR body, I'm surprised it got the support it did

I've been killed by this a few times and it's annoyingly fast, but it is an expensive kill spell and fairly high profile. I think it's fine.

**Pull request closed without merging**
