### PR TITLE
Kicking or EMPing shuttle computers can cause them to move the shuttle

### PR DESCRIPTION
**Pull request by DamianX**
I've always wanted a way to send the shuttles without access.

:cl:
 * rscadd: Kicks and EMPs hitting shuttle computers now have a chance of sending the shuttle.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Please add to the kick list on the wiki https://ss13.moe/wiki/index.php/Shortcuts#Kicking

Also: I think the trader PDA cartridge does basically the same thing as this proc, so if you could update it to use your try_move proc instead for maintainability, I would appreciate it

**Comment by DamianX** [comment]
Do we want to prevent certain shuttles (the trader shuttle?) from being affected by this?

**Comment by Kurfursten** [comment]
If you're okay with the security shuttle being kickable I'm okay with the trader shuttle being kickable.

**Comment by Eneocho** [comment]
time to kick the emergency shuttle console

**Comment by DamianX** [comment]
Really all I want is to be able to use the mining and research shuttles if you get stranded on z5. I don't care about the rest. Also, the emergency shuttle has no shuttle console.

**Comment by Kurfursten** [comment]
My gut says be bold on this one. Let's allow it and if we need to restrict some special shuttles more, we can do that.

You've put kicking a shuttle console at a very conservative 5% chance, meaning if you want to ride a shuttle you have to be very patient and seriously risk breaking your foot (unless you are the RD). I don't think that's practical for anyone but the truly dedicated/desperate. The existence of RD shoes does mean that someone could spamclick the console if they have them, though, since there is no cooldown.

**Pull request merged**
