### PR TITLE
Allow players to change their vote after they cast it

### PR DESCRIPTION
**Pull request by ShiftyRail**
Made after gathering feedback related to that. You will now be able to cancel your vote by clicking on a button next to the vote options.
I tested this by also implementing also for custom votes.

On a more technical note, the nanoUI interface for voting is outdated and not used anymore. The voting panel uses the HTML+JS Ui abomination instead. In the event that someone re-uses the oven-ready nanoUI interface template instead, the function is also implemented there.

:cl:
- tweak: Players can now cancel their vote in a custom vote or a map vote.

### CODE REVIEW

**Comment by Exxion** [comment]
You could definitely already do this unless someone broke it recently

**Comment by APCUnlocked** [comment]
> You could definitely already do this unless someone broke it recently

It has been broken for some time now

**Comment by Eneocho** [comment]
> 
> It has been broken for some time now

That's a server quote if I've ever seen one.

**Comment by ShiftyRail** [comment]
@Exxion That feature was used to vote multiple times and remove other people's votes, so I removed it and I'm now adding it back in a sane way.

**Pull request merged**
