### PR TITLE
Fixed a server crashing blob issue with the AME

### PR DESCRIPTION
**Pull request by DeityLink**
bleb

:cl:
* bugfix: Fixed a server-freezing bug caused when a blob tries to expand on the AME. The AME now properly becomes a blob.
* imageadd: Fixed the AME's sprites so AME shield parts don't appear invisible or badly oriented anymore.
* bugfix: Admin Ghosts can now access APCs like silicons, like they are supposed to.

### CODE REVIEW

**Comment by ghost** [comment]
This is stupid

**Comment by DeityLink** [comment]
That's what the code was supposed to do, but it caused an infinite loop that caused endless blobs to spawn on a single tile.

**Comment by Intigracy** [comment]
Still stupid

**Comment by Exxion** [comment]
Honestly this should have been on the secret repo
But it's too late now

**Comment by N3X15** [comment]
Please remove this entire feature, it's just dumb.

**Pull request merged**
