### PR TITLE
Fixes Poutine Oceans and Citadels erasing plates used on them

### LINKED ISSUE #32375: Plates used on the Poutine Ocean/Citadel are deleted upon consumption
(WEB REPORT BY: luigil101 REMOTE: 206.221.180.138:7777)
# Revision
a5673433ee111725aa37837ed5e0f8f5ec0eff30

# Description
the relatively limited number of plates the chef gets evaporates before the might of Canada when they shouldn't be
# Steps to Reproduce
take plate
use on poutine ocean/citadel to get some
eat
# What you Expected
to get the plate back
# What Actually Happened
plate was consumed alongside the poutine

### PR DESCRIPTION
**Pull request by DeityLink**
[bugfix]

Fixes #32375

:cl:
* bugfix: Poutine Oceans and Citadels no longer erase plates used on them, so you can now get multiple servings with a single plate.

### CODE REVIEW

**Comment by robintime** [comment]
deity what are you DOING

**Comment by Eneocho** [comment]
What the FUCK, deity is back? CULT 4 TIME LETS GOOOOOOOO

**Comment by Optimism333** [comment]
Nice to see you around again, even if it's just for bug fixes

**Comment by Eneocho** [comment]
Jokes aside, yeah. Good to see you again.

**Comment by Cartlord** [comment]
is this because of last night's incident
edit: you forgot to link https://github.com/vgstation-coders/vgstation13/issues/32375

**Pull request merged**
