### PR TITLE
Plasmamen can now wear Cult Robes. The old "armor" is still available from vox traders. Also fixed lots of plasmamen cult robes/armor interactions. And adding winter robes too why not. Can this title get any longer?

### PR DESCRIPTION
**Pull request by DeityLink**
image
image
image

:cl:
* tweak: Plasmamen using the Summon Robes rune now actually get cult robes. The old armor that used to spawn can still be purchased from traders, and now actually provides cult benefits when equipped.
* tweak: When using the Summon Robes rune, plasmamen now keep their plasma tank in their suit slot. And when using the blood tesseract, their cult suit and hood are now deleted and replaced with the suit and helmet they had stored in it.
* bugfix: Fixed Cult Armor and Helmets not regulating the body temperature of plasmamen or extinguishing them.
* imageadd: Plasmaman Cult Armor and Helmet are now animated.
* bugfix: Fixed monkey clothes not having their in-hand sprites show up.
* rscadd: Added Winter Cult Robes and Hood for all species (even monkeys). Those will appear in place of regular robes when using the Summon Robes rune on the snow Z Level.

### CODE REVIEW

**Comment by Blithering** [comment]
Cult grows stronger one commit at a time.

**Comment by Blithering** [comment]
You know if you added the diona armour you could make that title even longer, just saying.

**Comment by DeityLink** [comment]
It looks really cool but I really don't think they need the extra armor lol

**Comment by Blithering** [comment]
Counterpoint: they can already wear the cult armour can't they? A unique sprite would make it easier to tell which ones you need to laser.

**Pull request merged**
