### PR TITLE
Make lootcrates admin spawn only

### PR DESCRIPTION
**Pull request by gbasood**
Hey everyone publically shame Angry Duck because he thinks that it's git's fault he can't read the manual

### CODE REVIEW

**Comment by yclatious** [comment]
Quack

**Comment by Kurfursten** [comment]
Since we already have a datelocked item on the merch computer (valentine chocolate), why not just lock lootbox to the 1st of April?

**Comment by Intigracy** [comment]
I think it'd be a better meme item if it would actually drop things ranging from shit to decent as a 99 prob gamble, with the other 1 prob being gibbing.

Gibbing could say "You've achieved a sense of accomplishment."

Put more effort into your memes.

**Comment by SysadminJeroen** [comment]
@Intigracy That is really an anti-meme.

This is actually a meme.

**Pull request merged**
