### PR TITLE
Adds spider icon for standard module borgs, ala Dizor

### PR DESCRIPTION
**Pull request by gbasood**
Icon from #6364 as the only one that doesn't have height/center consistency issues (and also the coolest)

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
I suggest you give it a spin on a station, near other  borgs and hummies

**Comment by PJB3005** [comment]
Man I'd have loved that medical borg sprite too.

Those sprites are so good, sad thing @Dizor dissapeared.

**Comment by Imagebard** [comment]
If Dizor dissipated then why is #6364 still open?

**Comment by PJB3005** [comment]
Good point.

**Comment by gbasood** [comment]
They were great, and we CAN still use all of them, but they have consistency issues with height/perspective that are kinda annoying when you notice them.
If the perspective of an object changes based on the direction then it's going to get really annoying to look at eventually

**Comment by Imagebard** [comment]
@gbasood And who is currently playing with sprites on /vg/station? 
Other than Niggly, I mean.

Actually, where can I find the other borg sprites?

**Comment by PJB3005** [comment]
@Imagebard they're all in the DMI in the PR, just download it ("view raw" in the files tab)

**Comment by gbasood** [comment]
To be clear, the DMI in the original pr

**Comment by Imagebard** [comment]
Okay, I *finally* see the height difference now. Sprites looking at north/south are one pixel lower than those looking west/east.
Pain in the ass.

**Comment by gbasood** [comment]
Yeah, that and the side views are flat perspective and the front/back are oblique-ish.

**Comment by Imagebard** [comment]
I tried fixing security but It seems I should give up for now.

**Comment by clusterfack** [comment]
Tachikomas incomign

**Comment by Ephx1** [comment]
yaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaay
Now we need the others!

**Comment by Dizor** [comment]
I'm kinda alive. I think I had gone in and standardized all the other borg heights and centers but never got around to reupping them after I kinda went on hiatus. For two months.

**Comment by NigglyWiggly** [comment]
Hey @Dizor 
I was wondering if you're planning on finishing those not-marina sprites.
If not, I was wondering if you'd mind postin' em somewhere so I could try to make the other directions for them, a friend of mine really wants to see them in game

**Comment by Dizor** [comment]
Yeah give me a bit. I kinda got stuck on the Engineer sprite and gave up for a while. I'll try finishing it but if I dont feel confident to get it done I'll send you the files.

**Comment by gbasood** [comment]
Yeeee
Fix those up they looked good

**Pull request merged**
