### PR TITLE
Brig Medic (Paramedic alt title)

### PR DESCRIPTION
**Pull request by Apogee-dev**
Adds a new alt title for the paramedic, the Brig Medic. Brig Medics start the round with a new uniform, access to the medical and security radio channels, and a loyalty implant. They do not get any additional access to security that paramedics don't normally get, and they do not have a weapons permit. While they cooperate more closely with security than a normal paramedic, they still ultimately answer to the CMO and are considered part of the medical department. The brig medic is effectively an alt title for paramedics that intend to make the most of their brig access and spend their time stitching together secoffs and scraping prisoners off of the cell walls.

brigmedic
xeno_brigmedics
:cl:
 * rscadd: Brig medic alt title for paramedic. comes with medsec headset, loyalty implant, and outfit.

### CODE REVIEW

**Comment by Eneocho** [comment]
I'd remove the loyalty implant from the brig paramedic. It's literally a doctor for sec, not a gun wielding guy who could threaten NT's interests. And since they don't have a gun permit, they wouldn't be able to carry guns without getting cucked by beepsky.

**Comment by Apogee-dev** [comment]
> I'd remove the loyalty implant from the brig paramedic. It's literally a doctor for sec, not a gun wielding guy who could threaten NT's interests. And since they don't have a gun permit, they wouldn't be able to carry guns without getting cucked by beepsky.

The reason for the loyalty implant is because without it, this would be one of only two non-implanted jobs with regular access to security comms, and unlike the journalist, brig medics are intended to work directly with sec on the premises of the brig itself. The little green square goes a long way towards getting secoffs to trust you enough to actually stitch them up without their buddy breathing down your neck in the surgical theater.

**Comment by KillFurries** [comment]
Seems ok, but some details need to be ironed out. Do these brig medics spawn in the brig? I don't think the brig medic should get access to the normal paramedic gear so he can steal the paramedic's space suit, they should get their own and it should look different.

**Comment by Apogee-dev** [comment]
> Seems ok, but some details need to be ironed out. Do these brig medics spawn in the brig? I don't think the brig medic should get access to the normal paramedic gear so he can steal the paramedic's space suit, they should get their own and it should look different.

Brig medic is just a paramedic alt title, so they still spawn in the paramedic's office and use all of the same gear and resources as a typical paramedic, including the space suit. They also fill a paramedic job slot, so I don't really consider a brig medic taking the paramedic hardsuit to be stealing any more than a normal paramedic taking it would be. That being said, I am spriting a Trauma Team space suit I plan to add in a separate PR as vault loot / adminbus fodder. If there's enough demand for it I could find a way to implement that as an option for the brig medic.

**Comment by Eneocho** [comment]
Then just leave it as an IC action. Make the paramedic get organically implanted inside the round, which would also help in trust, since they saw you willingly get that implant instead of having it roundstart.

**Comment by KillFurries** [comment]
> I don't really consider a brig medic taking the paramedic hardsuit to be stealing any more than a normal paramedic taking it would be

A brig medic would mostly be hanging around the brig and tagging along during raids. A normal paramedic recovers bodies from space and breached areas. It would suck if a normal paramedic couldn't recover bodies because a brig medic took the space suit and is getting in firefights in maint where he doesn't need a space suit.

**Comment by Apogee-dev** [comment]
> A brig medic would mostly be hanging around the brig and tagging along during raids. A normal paramedic recovers bodies from space and breached areas. It would suck if a normal paramedic couldn't recover bodies because a brig medic took the space suit and is getting in firefights in maint where he doesn't need a space suit.

Sure, but that's already a problem with paramedic as it is. There's almost always only one paramedic space suit to go around, and if one of the paramedics grabs it and fucks off or just wastes his time running around in it when he doesn't really need to, the other paramed's left high and dry. This is probably one of the reasons paramedic has EVA access, so he can grab a spare suit from there if necessary. The only real solution to that would be to map in an extra paramedic closet in brigbay or make the paramedic closet spawn an extra space suit, both of which are probably out of scope for this PR in particular.

**Comment by PavelCIA** [comment]
I feel like the Brig Medbay should get slightly expanded if security gets a designated medic. Maybe add a surgical table and basic tools so the medic can operate on officers in the safety of the brig. It's probably out of scope for this PR but I just wanted to throw it out there. This also might piss some people off.

**Comment by drawsstuff** [comment]
> Then just leave it as an IC action. Make the paramedic get organically implanted inside the round, which would also help in trust, since they saw you willingly get that implant instead of having it roundstart.

We have medical interns as an alt title for assistants, should that happen organically too?

**Comment by west3436** [comment]
> Then just leave it as an IC action. Make the paramedic get organically implanted inside the round, which would also help in trust, since they saw you willingly get that implant instead of having it roundstart.

Merchant alt-title for traders start with an implant for a similar reason. I don't see why you think this is such a big deal - if you want paramed traitor roles then don't play as Brig Medic.

**Comment by Eneocho** [comment]
> 
> 
> > Then just leave it as an IC action. Make the paramedic get organically implanted inside the round, which would also help in trust, since they saw you willingly get that implant instead of having it roundstart.
> 
> We have medical interns as an alt title for assistants, should that happen organically too?

I don't get your point. My point was that an implant is internally (from the game's perspective and mechanically) unnecessary. If the sec staff still wants their doc to be implanted, they can implant him in a few seconds, but don't implant em roundstart.

**Comment by Eneocho** [comment]
> 
> 
> > Then just leave it as an IC action. Make the paramedic get organically implanted inside the round, which would also help in trust, since they saw you willingly get that implant instead of having it roundstart.
> 
> Merchant alt-title for traders start with an implant for a similar reason. I don't see why you think this is such a big deal - if you want paramed traitor roles then don't play as Brig Medic.

But the difference there is that a merchant is functionally the same as a trader, just with some added fluff. A brig paramedic would have a wildly different game than a normal paramedic, but neither paramedic should be implanted since they are, by definition, not sec.

**Comment by west3436** [comment]
> A brig paramedic would have a wildly different game than a normal paramedic, but neither paramedic should be implanted since they are, by definition, not sec.
In what meaningful way would it be different considering the access is identical? You absolutely can, as I have several times before, play as bric medic right now as a paramedic. I am failing to see how the Brig Medic starting with an implant is a negative to anyone. What is the down side here, as you still haven't specified how this is a bad idea?

**Comment by APCUnlocked** [comment]
Upboating for the uniform alone. I don't think brigbays should get expanded at roundstart however, it'll just take away even more reasons for security to interact with the rest of the crew, leading to the red tribe mentality but worse. Let brigbay expansions/upgrades happen through the hands of the brig medic rather than giving them stuff for free.

**Comment by drawsstuff** [comment]
> Upboating for the uniform alone. I don't think brigbays should get expanded at roundstart however, it'll just take away even more reasons for security to interact with the rest of the crew, leading to the red tribe mentality but worse. Let brigbay expansions/upgrades happen through the hands of the brig medic rather than giving them stuff for free.

This. We've had a few people (looking at you, _Henry_) who have played this role before, even went and got a job name change at the HOP who ended up doing this. It encourages outside interactions to go out and secure proper medical tools unless you want to make do with what the map gives you, which is often very little (but does lead to creative solutions such as dead rev blood transfusions).

**Comment by robintime** [comment]
> We've had a few people (looking at you, _Henry_) who have played this role before, even went and got a job name change at the HOP who ended up doing this.

hi this was me! im so happy to see this added as something i can take roundstart without impacting available security officer slots. 

the reason i stopped playing this character was because i upset a lot of medbay mains by getting medical access each round (if there were no mechanics online, i had to go there to either scan the machines myself to get a chem dispenser for the brig, or use the ones in chemistry and make my meds on the spot), and also because i could only really play him when there were at least four other officers (i hung out in the brig and was basically a support instead of participating in manhunts / combat / field execution, so if there was a low amount of officers i'd have to actually partake in that instead of leaving it to the robust).

both of these problems are solved by making it a paramedic alt title (you are supposed to be in medical as its your home department, no one expects you as a member of medical to do security work beyond maintaining prisoners and being there to pull downed officers out of combat), so i'm really excited to see this go through and will probably return to playing it myself when people aren't grabbing the paramedic slot every round due to the new title!

as for brigbay expansion, i agree it should stay the way it is currently instead of being fleshed out in map updates. by the time i dropped the character i could get a full medbay in the brig with chems done at 12:20. timing yourself to see how fast you can set something workable up (and rushing to do it before shit goes down) is part of the fun i feel.

thank you for this PR thank you so so much

**Comment by Blithering** [comment]
I would say give it the secborg style big bold red text on spawn reminding them they're a member of medbay, not a sec officer and shouldn't pretend to be one.

**Comment by Apogee-dev** [comment]
> I would say give it the secborg style big bold red text on spawn reminding them they're a member of medbay, not a sec officer and shouldn't pretend to be one.

I'll look into that and see how it feels in testing. It feels kind of weird to give an alt title a unique message like that, but on the same hand, merchant also gets a unique message on spawn and is the only other instance of an alt title getting a loyalty implant where the base job does not.

> multiple comments about brigbay expansions

Yeah I'm not going to do any remapping, at least in this PR, and my personal stance is that the majority of brigbays are fine as they are for roundstart. since brig medic has access to most of medbay by default all you really need for a sub-30-minute upgrade project is a cooperative mechanic. Or just access to his office.

**Comment by Blithering** [comment]
I think a limited brigbay is healthy, you can stabilise the prisoner who "accidentally slipped" and has a broken skull, but medbay is still gonna be your destination afterwards. It ties in to keeping sec from becoming fully isolated from other departments and too paranoid to go anywhere but their own special medbay when wounded for fear of antags.
(incidenally the trauma team suits would be _ideal_ for castle station, where the concept of BACK THE FUCK OFF WHILE WE HEAL THIS GUY OR EAT A BULLET can be properly enacted)

**Comment by Armadingus** [comment]
I dislike the advantages this PR brings to brig medic over paramedic.
Far as I can tell, as a brig medic, you have all the paramedic gear plus an implant and sec radio, those two items are very impactful. As Apogee said, you are more trustworthy with a green square over your head, since you roll antagonist less and you are protected against conversion. This also paints standard paramedic in negative light, it can be seen as people are making a conscious choice towards rolling for antagonist and because of that, I believe that people will prefer being treated by a brig medic over a paramedic, if they have the option between the two.
This sucks if you simply want to play paramedic and people avoid you, meanwhile brig medic gets that trust for little cost.

There should be a severe drawback to having those items or brig medics should not have those items at roundstart.

**Comment by drawsstuff** [comment]
> I dislike the advantages this PR brings to brig medic over paramedic.
> Far as I can tell, as a brig medic, you have all the paramedic gear plus an implant and sec radio, those two items are very impactful. As Apogee said, you are more trustworthy with a green square over your head, since you roll antagonist less and you are protected against conversion. This also paints standard paramedic in negative light, it can be seen as people are making a conscious choice towards rolling for antagonist and because of that, I believe that people will prefer being treated by a brig medic over a paramedic, if they have the option between the two.
> This sucks if you simply want to play paramedic and people avoid you, meanwhile brig medic gets that trust for little cost.
> 
> There should be a severe drawback to having those items or brig medics should not have those items at roundstart.

The drawback _is_ the implant, it hampers your antag chances significantly. What you said also applies to traders vs merchants, who get a lot less scrutiny and legal paperwork for the person who cares about such things.

**Comment by APCUnlocked** [comment]
> There should be a severe drawback to having those items or brig medics should not have those items at roundstart.

The drawback is the implant honestly, it lowers your chance of rolling for antagonists and completely excludes you from cult and revs. Not to mention we have an alt-title with functional differences (i.e loyalty implant) in the merchant/trader job. I don't think much will change about how people react to paramedics.

Edit: oh wow same thing said twice, epic

**Comment by Armadingus** [comment]
> The drawback _is_ the implant, it hampers your antag chances significantly.
>
It's not enough of a drawback and it's not even a drawback if you do not want antagonist rolls.
I'll have you know merchants give up a coin for an implant, the coin gives you access to very good items as well.

**Comment by west3436** [comment]
Is ss13 a competitive game? Are you really making an argument about balance for an alt title which will have a lowered antag roll rate?

**Comment by Apogee-dev** [comment]
> I dislike the advantages this PR brings to brig medic over paramedic.
> Far as I can tell, as a brig medic, you have all the paramedic gear plus an implant and sec radio, those two items are very impactful. As Apogee said, you are more trustworthy with a green square over your head, since you roll antagonist less and you are protected against conversion. This also paints standard paramedic in negative light, it can be seen as people are making a conscious choice towards rolling for antagonist and because of that, I believe that people will prefer being treated by a brig medic over a paramedic, if they have the option between the two.
> This sucks if you simply want to play paramedic and people avoid you, meanwhile brig medic gets that trust for little cost.
> 
> There should be a severe drawback to having those items or brig medics should not have those items at roundstart.

The implant is, at least from feedback I received regarding the medsec radio prior to this PR, seen as something of a pre-requisite to having a sec headset. The only non-implanted role with access to sec radio is the librarian via his intercoms, and a librarian piping up on sec comms almost always raises a few eyebrows. I see the sec radio itself as a necessity for brig medic because his intended duties are primarily retrieving wounded officers and treating prisoners, followed by paramedic's normal duties. in the case of prisoners, the brig medic (intentionally) doesn't have access to perma or the brig cells, and needs to be able to contact secoffs or ideally the warden to let him in. Only really avoidable if the warden's at his office to talk to personally or if mappers added sec intercoms to brig medbay. Retrieving and supporting officers in the field, though, absolutely requires sec comms because they're almost always on the move, and any situation in which officers are wounded is likely a dynamic one that may have changed drastically by the time the brig medic's arrived on the scene. You can, of course, put a sec encryption key in the paramedic's normal headset, but in doing so you've removed a working headset from one of the sec lockers, which you don't have access to in the first place.

> The drawback is the implant, it hampers your antag chances significantly. What you said also applies to traders vs merchants, who get a lot less scrutiny and legal paperwork for the person who cares about such things.

This is true for players that actually care about antag roles, but there's a little more to this- the brig medic has another drawback in that his post is halfway across the station from medbay (or on the opposite side, on some maps) and lacks almost all of the facilities a normal paramedic has access to, including the all-important crew monitoring computer. the brig medic still reports to the CMO and is still going to have to abandon his post if medbay needs extra hands, and if he wants to improve on the his post's lackluster facilities he's looking at a much more significant setup time than most other medbay jobs and the cooperation of a mechanic or, if he's really unlucky, scientist (by comparison, a normal paramedic just has to grab his gear and set up the tubes, and that's only if another medical player hasn't taken care of it). In other words, brig medic faces slightly more difficult circumstances as far as what he has to work with is concerned.

**Comment by APCUnlocked** [comment]
Adding to the "trust" argument, most of the time as a paramedic you're either grabbing corpses where trust really doesn't matter since well, the lad's dead or treating wounded people which most of the time is solved by making them eat a pill. I fail to see how suddenly the crew would be more anxious around a normal paramedic doing his duties just because there's an alt-title most people don't care to pick since they want to roll for antags. This is all of course from my experiences playing paramedic and you might have differing opinions but to me it sounds like a "this in theory could happen and it's bad" when in-game it's "who the fuck cares lmao gimme that bicardine bihh". Not to mention security already leaves their dead comrades bodies in medbay for people to loot ALL THE TIME.

**Comment by BomberBro** [comment]
In the dark future of 2025 all jobs will either be related to security or assistants in some way.

**Comment by PavelCIA** [comment]
Brig Engineer, Brig Janitor and Brig Scientist PRs are almost done

**Comment by Blithering** [comment]
@PavelCIA brig sec when?

**Comment by PavelCIA** [comment]
Right after I finish the Brig MoMMI PR

**Comment by Apogee-dev** [comment]
> @PavelCIA brig sec when?

sounds like a good idea, we could even give him a fancy coat and hat to signify his position as master of the brig

**Comment by Kurfursten** [comment]
This is going to be a very hot take but I think the role SS13 could use the most is the exact opposite of this: not a medic dedicated to brig, but an "officer" dedicated to medbay. Basically, an **Orderly** whose role is to report to the CMO and keep the flow of medbay moving. They would be responsible for restraining people who run amok in medbay, filtering assistants who tailgate in, protecting med storage from looting, and otherwise assisting medical staff. Medbay is particularly vulnerable to conversion modes because people wander in constantly and doctors are too busy with patients to manage doors.

I could envision the role with maybe special gloves that guarantee disarms turn into shoves if they hit, authorization to use sedative, etc. Like security officer, the role would be timegated and one could be banned for using their tools to validhunt instead of protect medbay or who are too jumpy with the chloral [this might even justify a dedicated wiki rules page]. The job would not get its own dedicated office but would spawn in the break room and might have a special locker in there with their tools.

**Comment by Apogee-dev** [comment]
> This is going to be a very hot take but I think the role SS13 could use the most is the exact opposite of this: not a medic dedicated to brig, but an "officer" dedicated to medbay. Basically, an **Orderly** whose role is to report to the CMO and keep the flow of medbay moving. They would be responsible for restraining people who run amok in medbay, filtering assistants who tailgate in, protecting med storage from looting, and otherwise assisting medical staff. Medbay is particularly vulnerable to conversion modes because people wander in constantly and doctors are too busy with patients to manage doors.
> 
> I could envision the role with maybe special gloves that guarantee disarms turn into shoves if they hit, authorization to use sedative, etc. Like security officer, the role would be timegated and one could be banned for using their tools to validhunt instead of protect medbay or who are too jumpy with the chloral. The job would not get its own dedicated office but would spawn in the break room and might have a special locker in there with their tools.

The idea of assigning a security or quasi-security player to medbay is another one I've played around with a lot. Theoretically speaking, we have all of the tools in game already for the various departments to have assigned security officers (that's why each head gets department armbands in his office), the problem is that there aren't really any game mechanics that actually encourage doing this or even any in-game indication that it _can_ or _should_ be done, without the metaknowledge that it's a thing. As you mentioned, though, medbay in particular could benefit from some kind of dedicated protection more than most other departments, and it actually is a case of _protecting_ the department rather than reining it in (as would be the case for cargo or science). I really like your idea, and the idea of having a protective role that isn't actually part of security is an interesting one and a nice solution to the problem. I might just take up the task of coding it once I finish the trauma team suit if nobody else starts on it first.

**Comment by Apogee-dev** [comment]
Added insectoid, grey, and vox sprites for the uniform since I'd managed to overlook it earlier.

**Comment by TGFH** [comment]
> 
> 
> In the dark future of 2025 all jobs will either be related to security or assistants in some way.

This. To me this just seems like something that will result in fewer people playing paramedic.

**Comment by beesil** [comment]
Giving a job a loyalty implant stops them from being converted, but they need to be added to the `restricted_from_jobs` and `protected_from_jobs` lists for individual roles to have a lower roundstart/midround antag roll rate. As of right now, brig medic has the same antag roll rate as paramedic.

**Comment by Blind-Watcher** [comment]
I'd much rather have an Orderly than a Brig Paramedic. It'd just be another player than sits in brig with nothing to do, and would be chastized for leaving brig. At least the Warden has cameras to watch.

**Pull request merged**
