### PR TITLE
ABSOLUTELY DISGUSTING

### PR DESCRIPTION
**Pull request by jknpj**
:cl:
 * rscdel: Insectoids jobs are now restricted to Azziztant, Botanizt, Quatermazter, Cargo Tech, Zhaft Miner, Clown, Mime, Janitor, Chaplain, Engineer, Atmoz Tech, Mechanic, Zcientizt and Roboticizt.

### CODE REVIEW

**Comment by SageOfLight** [comment]
Hey, can you not?

This seems all kind of reactionary and deliberately taking away options rather than adding them.
No real reason is provided even.

**Comment by boy2mantwicethefam** [comment]
are you sure you want to do it like that though?
Why not just add the blacklist to the jobs?

**Comment by ShiftyRail** [comment]
whitelists >>> blacklists

**Comment by bathosbathtime** [comment]
Bug chefs! Bug chefs! Bug chefs!

**Comment by PrimeDSS13** [comment]
lawyer bugs when

**Comment by beesil** [comment]
Keep paramedic bugz.

**Comment by Buchse** [comment]
alright, but why besides shitposting?

**Comment by tuypo1** [comment]
Head rolls (and quartermaster which should be a head roll anyway) for humans and humans only

**Comment by TGFH** [comment]
Bugs do not belong in the kitchen or medbay.

**Comment by tuypo1** [comment]
I mean supposedly the lore is that they don't care about mess but do care about actual dirt and stuff, I doubt anybody is gonna stick to that though

**Comment by anunknownentity03** [comment]
i'd say no to this, let the bugs have their fun

**Comment by ghost** [comment]
I already did this why are you trying to do it again

**Comment by SageOfLight** [comment]
Because and I quote; "I just did what people were asking in dead chat but either too afraid or lazy to do."

image

**Comment by tuypo1** [comment]
Wait I thought this was just a no head roles thing at first and upvoted it, now that I took a proper look I have come to the conclusion this PR is retarded, there is no rhyme or reason here

**Pull request closed without merging**
