### PR TITLE
[Balance] AI Integrated Radio

### PR DESCRIPTION
**Pull request by Kurfursten**
Fills #4380
- AI now has integrated radio, with a captain key
- New configure radio verb for AI

### CODE REVIEW

**Comment by Shadowmech88** [comment]
The only problem I can see with this is that the AI is now able to listen to every radio channel at once, instead of just three simultaneously. This makes it even more all-seeing than it already was with its camera network.
I'm not really for or against the change myself, though.

**Comment by Shaska-** [comment]
Would it be possible to only give them speech access to the channels?
That way they'd keep their unique 3-channel radios, but be able to quickly respond on the channels they're listening to, instead of having to fiddle with the microphone.

**Comment by Midaychi** [comment]
This pr is fine as it is, and the ai really should be connected to everything.
If anything, I'd add this feature persisting if the ai is carded, and disable it if the wireless is disabled.

**Comment by PJB3005** [comment]
@Shadowmech88 it's not like the AI can't just use a TCS script to do that already.

**Comment by Ephx1** [comment]
Is it happening? Has the time for Big Brot- AI to keep the station truly from harm as always intended?
I am a bit on the fence on this now, but at least I don't have to deal with three shitty intercomms that make me want to gouge my eyes out every time I have to swap between each one just to talk on a channel.

**Comment by d3athrow** [comment]
>The only problem I can see with this is that the AI is now able to listen to every radio channel at once, instead of just three simultaneously. 

Why are you not doing this with NTSL as an AI anyways?

**Comment by PJB3005** [comment]
@d3athrow I even do that as MoMMI and carbon

**Comment by ComicIronic** [comment]
2stronk

**Comment by Kurfursten** [comment]
This hasn't been discussed since the discussion tag was added 2 days ago.

Is this ready for NFD? Do you want to do polling? What's the deal?

**Comment by Ephx1** [comment]
I suppose that's just it, it's 2stronk according to Comic and perhaps he would like either
A: A discussion how to make it slightly less all-seeing
or
B: If the community is fine with it as the way it is

Playing AI all the time, I would just love this, I don't have to cycle through my shitty intercoms that I usually have set to core private, just in-case someone comes knocking to change laws every round.
Which leaves me to one single changeable intercom, usually it's not set to anything, but occasionally I'm tasked to get on Security channel because some criminal is out and about.
I also like talking directly to people as AI, using a PDA message of some sort, because really, nobody ever looks at the chat log radio unless they're specifically watching it for a reply, or its their own department channel color. 

But I can understand why people would view it as overpowered or too invasive. Such as for example, Security executing people, that's absolutely never going to happen now unless the Captain or another head changes laws for it (Protip: they almost never do). Or they talk about it directly with other people.
Sometimes if enough antags are in a department, they'll even collaborate with one another on radio, in the case of Revolution and a majority of the time, Cult after they've bulldozed everything.

**Comment by Midaychi** [comment]
How about: The comms headset is part of a console in the PDA messaging room, and a human with access to that room can change the key if the ai pops out the existing one first, and they just start with general + private?

Then they can bug the RD or CE to give them a new one?

**Comment by ComicIronic** [comment]
I think it makes the AI too difficult to silence.
Following the original issue suggestion of a control panel for the intercoms would have been more sensible, in my opinion, because this gives the AI a lot more power in terms of instant channel switching and a constant radio that cannot be removed.
Not to mention the listening potential of an AI eavesdropping on EVERY SINGLE CHANNEL.

**Comment by FudgePucker** [comment]
I had an idea that would balance this out some.
One of the most difficult things to do on the station is anonamasly send messages across the station. PDA messaging has your name attached, and can be evesdroped on by the ai or RD, newscasters require you to have an id and lists your name.
What if you could use a soldering iron on glass to make a blank circuit board, turn it into a special board, attach it using a soldering iron and wire to some computers, and have it be able to do various things.
It would make a new feature sink, emags get every thing hacking related, this would add in a new way to add features you don't want everyone using, but it won't require the magical hacked id card with wires sticking out.
Be able to hack a news caster to call the captain a condom without being tracked.
Make a new radio channel that jumbles audio so they can't recognize voices.
Hack the request computer to authorize your own orders.
Modify the pda upgrader to hack into the pda messaging server.

It would let you overcome big brother with some hard work

**Comment by Kurfursten** [comment]
I don't really strongly care enough about this change to fight for it.

**Comment by PJB3005** [comment]
Hey it's back.

Still :+1:  :heavy_multiplication_x: :100: to this.

**Comment by SangriaMonkey** [comment]
when

**Comment by Ephx1** [comment]
I think my feelings still stand from before. I like it a lot and want to use it, but I can see why people wouldn't.

**Comment by d3athrow** [comment]
travis file is out of date which pulls an old version of byond.

**Comment by Probe1** [comment]
I'd rather it not be all channels personally.  It makes malf easy modo and isn't necessary.

**Comment by Kurfursten** [comment]
I think this PR is a good place for discussion, but after we're fully decided on what exactly should be coded, I'm going to just write a new branch. The amount of code that goes into making this happen is actually quite small, and I'd rather not try to rebase through five months of system changes like to_chat.

So do a poll or something and tell me exactly what to code and I'll do it.

**Comment by ihadtoregisterforthis** [comment]
Thanks stealthcoders

**Pull request closed without merging**
