### PR TITLE
Brings back old bluespace sprite

### PR DESCRIPTION
**Pull request by Intigracy**
It looks like this
ejwfwveogyamanc7cabawybgbrgsnfflape17o577-s-83kbo8ygbgd7qvxm7tvklt58f-lxk-nux-wgylbqcbfhfihzig4rj6qqmsacrx5fjfqwfdnnntg81y-nu98fwq0gnq

### CODE REVIEW

**Comment by Zth--** [comment]
Why not goons? at least they have an animation

**Comment by clusterfack** [comment]
Not animated
No texturing

Great "improvement"

**Comment by kilozombie** [comment]
Why are you mad, clusterfack? This is an easy texture to convert to 64x64.

**Comment by N3X15** [comment]
Here's why.
 * The yellow texture is the older texture.  I made both, and bluespace looks better, and it therefore was used after the yellow placeholder.
 * It's flat blue because that's what the old "bluespace" bug looked like.
 * We're pestering spriters to come up with new 64x64 shapes so that we can get rid of the straight edges.
 * It makes Clusterfack mad as hell.

**Comment by kol1th** [comment]
Absolutely disgusting

**Comment by clusterfack** [comment]
It was a bad change 2 years ago, and it's a bad change now.

I wouldn't be against this if it wasn't so absolutely dogshit. It's been this long and the best you can do is still a plain blue square.

**Comment by N3X15** [comment]
It's supposed to look that way, Clusterfack.

**Comment by kol1th** [comment]
I get the joke but MY EYES

**Comment by Shadowmech88** [comment]
Some would say that "it looks bad intentionally" is not a justification for adding something that looks bad.

I don't care either way, though.

**Comment by gbasood** [comment]
if someone wants to animate something to make it more than a flashing, static tiling icon (yellow supermatter) by all means
I'm personally biased torwards something Giygas-like:

**Comment by NigglyWiggly** [comment]
For what purpose
It looks like complete shit and it always has, why would anyone actually want this

**Comment by NigglyWiggly** [comment]
>It's flat blue because that's what the old "bluespace" bug looked like.

Wait what
Does the term 'bluespace' come from a bug that made space blue, or something? I never actually thought about it

**Comment by PJB3005** [comment]
@NigglyWiggly if you got nullspaced waaaaaay long ago (due to teleporter bugs for example), your screen didn't turn black, but that shade of blue.

And that's how the term "bluespace" was born.

**Comment by SonixApache** [comment]
post current for comparison

**Comment by Exxion** [comment]
It's bad

**Comment by SonixApache** [comment]
Looks more like the stuff the supermatter's made of than a pure blue square.

**Comment by Probe1** [comment]
I'm fine with adding bluespace back in as a fun admin button or even a toggle if you want but.. look, it was pretty bad.  It was just laziness.

**Comment by murnandreams** [comment]
Is this for the texture of the supermatter sea, that's being proposed? You want to turn it to just plain blue? That's boring as shit.

**Comment by Aurx** [comment]
Bluespace turfs keep track of which directions are valid for expansion.  That can be used to determine which directions have bluespace in them.  Create a series of sprites for each combination of filled directions.  Sprites should have flat color bluespace blue edges in directions that are filled, and a gradient or animation spreading from there to the center of the tile.  The result will be a spreading blob with a pure bluespace blue interior instead of a spreading clusterfuck of squares.

**Comment by NigglyWiggly** [comment]
being intentionally bad doesn't make it any less bad, unfortunately.
If it were some crazy blue effect and not just fading in blue boxes, then sure, but as it is I'd say no.

**Comment by Exxion** [comment]
Yeah, the edges are pretty shit
But, at least in my opinion, even just the pure blue boxes look better than the AWFUL supermatter sea

**Comment by ghost** [comment]
I really really liked the blue space and really really hated the puke yellow sea

**Comment by ghost** [comment]
The reason I liked it was simple: it's the end of the world, the supermatter isn't expanding or whatever, it's exploded, the universe has ended. What happens when the universe ends? The lack of colour. The lack of feeling, the cold, clinical blue, of the universe's final form, where energy, gas, heat, is all absent . The galactic blue screen of death - you can't restart from this one.

**Comment by Aurx** [comment]
But we do restart from it.

**Comment by AlphaBuffalo** [comment]
you could do an event horizon idea where you have matter being changed and dissolved into the new state of blue space

**Comment by kilozombie** [comment]
Idea: getting caught in the bluespace nullspaces you, instead of killing you and making you into a ghost. Killing yourself is literally preferable to actually getting caught in it.

**Comment by Aurx** [comment]
But you can just ghost and teleport/haunt out of nullspace.

**Comment by kilozombie** [comment]
Damn.

**Comment by Aurx** [comment]
I mean, it would trap all the newbies who don't know how to get a ghost out of nulloc.  That'd be something at least.

**Comment by kilozombie** [comment]
Could you disable the ghost verb after touching the supersea?

**Comment by Exxion** [comment]
You could, but that's a stupid idea

**Comment by N3X15** [comment]
Superceded by #13715

**Pull request closed without merging**
