### PR TITLE
Sprite fixes - fix #4085, fix #6673, fix #7487

### LINKED ISSUE #4085: (WEB REPORT BY: 1pirateguy REMOTE: 198.245.63.50:7777) Clown mask doesn't toggle
>Revision (Should be above if you're viewing this from ingame!)
3dc5c33ab14e473fd0d938557b2ff145fd7dd6f1 

>General description of the issue
Trying to push clown mask up results in a missing sprite error

>What you expected to happen
Expected to have a clown mask above my face

>What actually happened
Sprite error

>Steps to reproduce if possible
Try to push clown mask up

### LINKED ISSUE #6673: Two sprite issues
Not sure if this is true each time, but it seems the HoP jacket item displays as the worn object facing west, hole in the sprite for hand and all.
The item Pirate's Jacket always has the back facing the screen on the in-hand sprite.

### LINKED ISSUE #7487: Slime soup from meat crate invisible
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> The slime soup I got in a trophy meats crate is invisible
> 
> What you expected to happen
> To see something that reassembles a slime soup
> 
> What actually happened
> The Item is invisible
> 
> Steps to reproduce if possible
> Order trophy meat crates hope for RNG

### PR DESCRIPTION
**Pull request by TheEliminator16**
- Added slime soup sprite which was previously missing
- Fixed an issue with the HoP coat having holes where the hands should be when not worn
- Fixed an issue with pushing the clown mask off of your face making it disappear

Note: this does not address the other half of #6673 regarding the pirate coat item

### CODE REVIEW

**Comment by TheEliminator16** [comment]
Conflicts
Every time
I'm not making the same mistakes, I'm updating my repo every time, I'm using new branches and different changelog names

**Comment by 9600bauds** [comment]
You're not updating it right somehow
mspaint_2016-02-01_21-32-04

**Comment by TheEliminator16** [comment]
Fair enough. I'd rather just redo all this stuff than sort out the conflicts

**Comment by ghost** [comment]
You know you have to pull from the main repo before you rebase, right?

**Comment by TheEliminator16** [comment]
Jesus, I think the issue is that I'm trying to wean myself off of Git for Windows and I'm realizing I don't know how to consistently update my shit with SmartGit

**Comment by gbasood** [comment]
Honestly, SmartGit doesn't have a super simple way to update stuff based on your remote, at least as far as I know. I've been using the CLI for that.

**Comment by 9600bauds** [comment]
Literally the pull button

**Comment by gbasood** [comment]
You'd have to set your tracked branch to upstream though

**Comment by clusterfack** [comment]
1. Have one branch of bleeding edge tracking upstream
2. Pull upstream

**Pull request closed without merging**
