### PR TITLE
Plank

### PR DESCRIPTION
**Pull request by ghost**
second edition

original
plank

:cl:
* rscadd: You can now draw on a wooden plank with a crayon to create Plank, and use soap on Plank to turn it back into a regular plank.

### CODE REVIEW

**Comment by ghost** [comment]
How do you fuck up a meme PR with getting a conflict on a DMI before Travis has had its way with it?

**Comment by ghost** [comment]
jesus christ looks like my branch is already outdated

**Comment by Probe1** [comment]
People still said no to the memes.  Sorry no memes.

**Comment by ghost** [comment]
nah it was 12:4 +1s to -1s on the last PR

eggs d

**Comment by Probe1** [comment]
Oh ok thank you for correcting me I didn't realize we were on Reddit and your PRs are merged by upvotes.

**Comment by ghost** [comment]
then i guess we need a server vote :^)

serious note: now there's soap to turn it back to regular wood, so you can't ruin an entire stack of wood anymore which was pretty much the main issue

**Comment by Riekland** [comment]
???
??
?
I see no issue here except for the fucking awful sprite please explain

**Comment by Probe1** [comment]
The previous PR discussed it at length.  People don't want a 10 year old meme in the game for no reason other than we can.  Yes, we have plenty of memes in the game.  Most are in one way or another related to science fiction or the server.  Some are recent jokes people are amused to see reflected in the game.  This is none of the above and it only serves to annoy people down the line.

  Then collaborators are asked why the fuck they merge this shit and all you little rascals that want your dank meme content merged remain silent.

**Comment by ghost** [comment]
>fucking awful sprite

it's SPOT ON

**Comment by ihadtoregisterforthis** [comment]
Maybe it's too spot on

**Pull request closed without merging**
