### PR TITLE
Mining Support Patch

### PR DESCRIPTION
**Pull request by Kurfursten**
I wanted to have this out sooner but 4th of July and gf all weekend after that

🆑 
* rscdel: The Proto-Kinetic Accelerator is no longer purchased at the mining vendor ($300)
* rscadd: A PKA warp voucher can be bought at the mining vendor ($25). This turns into a PKA when brought into the mine.
* rsadd: Science can now produce PKA lockboxes for a small amount of iron and a moderate amount of plasma. It requires mining access to open, and 6 materials research (equal to diamond drill).
* tweak: Sending plasma back to centcomm on the supply shuttle now pays out 5x as much, for a total of 10x (it originally paid 2x value).

### CODE REVIEW

**Comment by Kharkov72** [comment]
having a voucher that turns into a pka when you use it in the mine seems kinda roundabout, what's wrong with just having the pka be in the vendor?

**Comment by MadmanMartian** [comment]
what's wrong with the PKA being in the mining lockers?

**Comment by Kurfursten** [comment]
@MadmanMartian Being in the mining lockers is fine. If people would prefer that I could make each locker spawn 3 guns and call it a day.

@Kharkov72 25 credit guns in a vendor, we wanted to avoid the situation where it becomes popular for assistants to hack in through that side door in maint and buy 12 guns with their starting $300. It's true that PKAs are reduced impact damage in normal atmos, but they still pack a punch of ranged brute damage.

**Comment by MadmanMartian** [comment]
3 guns to a locker? but each locker's supposed to supply one miner each.

**Comment by BomberBro** [comment]
This is a good fix, but would this mean cargo only gets 50-100 per 50 sheets since they previously only got 10-20? Sending over a full stack used to net thousands upon thousands and since the mining nerf wasn't supposed to hurt cargo it seems like an unnecessary gimp.

**Comment by Kharkov72** [comment]
So they'll just need to go to the roid, and on roidstation that's as easy as walking outside for a few seconds to swooce several PKAs. I'd just keep it at a miner-level expense

**Comment by bathosbathtime** [comment]
You should have more than one PKA if you are doing mining; I would use at least two in the lockers.
Do the vouchers fit on the belt?  And is the entire z-level considered the mine or just the astroid itself?  How does this interact with roidstation?  Other than these possible quirks, I think this is a fine solution.

**Comment by FudgePucker** [comment]
>Miner level expense

Wow, it's almost like SOMEBODY nerfed mining into the fucking ground. "Miner level expense" is now peanuts, you cant raise the price to prevent an assistant from getting a gun, and expect miners to make enough to even buy the required minimum of three. And yes, the required minimum to go into mob territory is three, if you say it's less, STFU, you have never played mining.

I think somebody else put it best, the best way to make money as a miner is to mine enough for a diamond drill, break into vault, and blow up the fridge with gibbinite

**Comment by amikawaii** [comment]
What is the theoretical endgame of "we have to fix this thing because assistants literally can not have it"

**Comment by MadmanMartian** [comment]
removing assistants, making them a job you can only play with a new account.

first few days - base assistant
after that, you choose one of the assistant subtypes to introduce you to a job.

Play a few days of that subtype, you unlock the base department. Play a few days as a job in the base department, you unlock the leading jobs of that department.

**Comment by Kurfursten** [comment]
@bathosbathtime They are small objects, they can fit in the pocket or box. It triggers when you enter an area that is area/mine/explored or area/mine/unexplored. On Roidstation this is not the whole z-level but it is pretty much everything outside to the right (not including the hallway between xenobio and science).

@BomberBro Reducing inflation from "bringing in the thousands of credits" was the original intent of the PR. I was going to lower supply shuttle income later with a separate PR but, having not looked at the shuttle sell code at all, I obliviously answered "I haven't touched selling plasma cost" without realizing it just takes the mineral value instead of having its own value. You're right that this reduces the amount cargo is bringing in per shipment, but a stack of plasma is not hard to come by. I might even think this is more than cargo needs to make off a stack, but I want to give it a shot at this level and see how things go. Remember, the most expensive cargo items have been significantly dialed back in cost. However, if you think there are particulars that need to be reduced more, *please* tell me, I'd be happy to re-examine the most expensive crates.

@Kharkov72 I am aware that on some maps this is easier than others (notably, on Deff the mining shuttle does not have access, so you can ride it over to the mine, hack a few doors, and get ye guns). However, I am a strong believer that adding small barriers to entry can have a noticeable impact on play. I believe this is sufficient to prevent the problem from becoming egregious.

**Comment by BomberBro** [comment]
Oh, I didn't know that the cargo crates got reduced as well, that should make it a lot better then, this sounds good to me.

**Comment by MadmanMartian** [comment]
How about this for an alternative; The mining vendors are moved to the mining outposts?

**Comment by Kurfursten** [comment]
That would also be agreeable to me. On roidstation they could be moved to the mining "outpost" north of the station. If someone (Veers?) maps the changes I will change this PR back so the vendor contains guns. I'll still keep the warp voucher code in the PR though, since it's very modular and could be useful some day.

**Comment by tuypo1** [comment]
Better idea, nerf the pka pressure damage even further, make it totally useless on station.

**Comment by SonixApache** [comment]
Nah, this is fine. Least retarded option.

**Pull request merged**
