### PR TITLE
Revert "༼ つ ◕_◕ ༽つAMENO༼ つ ◕_◕ ༽つ"

### PR DESCRIPTION
**Pull request by PJB3005**
Reverts d3athrow/vgstation13#9198

### CODE REVIEW

**Comment by 9600bauds** [comment]
I'm extremely disappointed in everyone this year

**Comment by Kitfox88** [comment]
requesting do not merge tag

**Comment by NigglyWiggly** [comment]
Vote Result: Please jesus can you just fucking kill me put a gun to my head and just do it with 18 votes 
    BEES BEES BEES ? ? ? had 1 vote
    BEES BEES BEES BEES had 3 votes

**Comment by ihadtoregisterforthis** [comment]
old vg is dead

**Comment by Tokanova** [comment]
revert this revert now ree

**Comment by Senaat1** [comment]
:+1: to this PR, april fool's day is almost over anyway.

**Comment by Tokanova** [comment]
why not just
add an option for mememins to turn it off and on at will rather than complete removal
theirs already a function to make it 'true'

> 'enableTwitchify': true, // I am so sorry

so set it to false.

**Comment by PJB3005** [comment]
Yeah, make it possible for admins to turn it on sounds better.

**Comment by PJB3005** [comment]
Note: I'm not coding that.

**Comment by Intigracy** [comment]
I think it should instead be tied to the holidays code we have, and just auto activate on apr 1.

**Comment by PJB3005** [comment]
Nah next April's fools needs to be something else.

**Comment by clusterfack** [comment]
NEXT april fools day? Surely we will have remade ss13 by then

**Comment by ihadtoregisterforthis** [comment]
That's the spirit

**Comment by 9600bauds** [comment]
Let's also code a year-round button to force everyone to be a skeleton except let's not fucking do that

**Pull request closed without merging**
