### PR TITLE
Reduce extended weight by half

### PR DESCRIPTION
**Pull request by ShiftyRail**
Simply put it should make it roughly half as likely to roll.

I apologise for the quick and dirty webedit but I can't use my computer right now.

:cl:
 * rscadd: Extended weight reduced my half

### CODE REVIEW

**Comment by Eneocho** [comment]
the autismprojects, ruined.

**Comment by KillFurries** [comment]
Next reduce the weight of the average extended enjoyer by half

**Comment by ghost** [comment]
just do more away missions bro

**Comment by PavelCIA** [comment]
speedmerge eet

**Comment by ShiftyRail** [comment]
May God forgive me for this

**Comment by PavelCIA** [comment]
hes finna doing it

**Comment by PavelCIA** [comment]
wtf I love france now

**Comment by DrSnips** [comment]
When I did this I got de-collabed. Is this ThE mEtA cLuB at work?

**Pull request merged**
