### PR TITLE
Adds IC in OOC protection to LOOC.

### PR DESCRIPTION
**Pull request by SysadminJeroen**
This PR is bretty simple, #11622 but for LOOC.

Whenever I have a lot more free time I'll add a beter IC in OOC protection, when I know how to do it and if I don't forget it.

### CODE REVIEW

**Comment by coldcola** [comment]
how many IC in LOOC have you seen?

**Comment by SysadminJeroen** [comment]
One, my own, today.

**Comment by coldcola** [comment]
how? what is the hotkey?

**Comment by Exxion** [comment]
I don't think there is one by default, but you can always make new hotkeys for yourself

**Pull request merged**
