### PR TITLE
Adds the Bangerboi bundle.

### PR DESCRIPTION
**Pull request by DrSnips**
[content] [balance]
A request from discord for more "fun" bundles. It contains the items in the changelog below. It doesn't really have any direct killing power but it has a lot of stopping power.

:cl:
 * rscadd: Added a banger boy bundle to the list of possible syndicate bundles. It contains 6 cluster bangs, a grenade launcher, a pair of sunglasses, and a pair of radio earmuffs.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I mean it's a cute meme but I'd hate to see the actual content in the live serb. If I got this as tator I'd have nothing for my TCs except essentially a loud weapon that's really bad to go loud with and sec is practically immune to. If I died to this as nonantag I'd feel kinda sorry for the tator for having gotten this shitty bundle, but I'd still be a little miffed that I got screenwide AoE horizontaled.

Cute meme but bad meme

**Comment by DrSnips** [comment]
Bundles are pretty notorious for being shit and are rather just memes. You don't buy them expecting anything worth while <i>cough cough hotline or screwed bundle</i> you expect memes.

**Comment by Killette2** [comment]
Can you make it 3 boxes of clusterbangs and 3 boxes of flashbangs instead?

**Comment by SonixApache** [comment]
6 clusterbangs is all i want in life

**Comment by MadmanMartian** [comment]
Personally ew because more stuns

**Review by MadmanMartian — APPROVED** [review]
it works I guess

**Pull request merged**
