### PR TITLE
Shocking Handshakes

### PR DESCRIPTION
**Pull request by mtpowell**
Requires stungloves.
- Handshaking with people will continue until the battery is drained.
- Better battery cells = longer handshake = more damage
- Shittier gloves(budget) on the target = more damage(depends on siemens coefficient)
- Insulated gloves protect you from shocking handshakes
- 10% clumsy chance to shake hands with yourself

Things to do
- ~~Check for clumsy and make them handshake themselves~~

Example image

:cl:
 * rscadd: You can now handshake shock people with stungloves

### CODE REVIEW

**Comment by mtpowell** [comment]
Can someone remove the silicon.dm commits from this PR? I must've fucked up from my last PR

**Comment by TheFriggenSawbones** [comment]
since this is a classic clown prank, maybe don't have a clumsy effect. Or perhaps just make it a low % chance to happen

**Comment by Intigracy** [comment]
Or just make it shock both of them.

Honk.

**Comment by mtpowell** [comment]
Should be good now, clumsy has a 10% chance of shocking yourself

**Comment by mtpowell** [comment]
@Intigracy 
Nice catch

**Comment by Exxion** [comment]
Did you... record that sample gif with a camera pointed at your screen?

**Comment by mtpowell** [comment]
@Exxion I used https://gyazo.com/

**Comment by Exxion** [comment]
Wow
I guess gyazo just makes really shitty gifs then

**Pull request merged**
