### PR TITLE
Removed Assault Rifle design.

### PR DESCRIPTION
**Pull request by ComicIronic**
Based on discussion in another issue that determined that the Assault Rifle has no comfortable niche in research gun designs, I've decided to remove it.

### CODE REVIEW

**Comment by Konater** [comment]
can we remove the xcom armour too?

**Comment by Orangerush** [comment]
Move all weapons to illegal research tree except for the Nanotrasen™ issued taser gun

**Comment by ghost** [comment]
If you move everything to the illegal research tree then what's the point of the weapons tree

**Comment by Orangerush** [comment]
You're right, lets just remove the weapons tree too

**Comment by Imagebard** [comment]
@Konater 
Why? they're pretty weak.

**Comment by Konater** [comment]
Science dindus love them anyway and I think they look dumb

**Comment by 9600bauds** [comment]
The current sprite is bad enough to warrant it

**Comment by icantthinkofanameritenow** [comment]
While I did want the AR nerfed, this isn't what I had in mind.  Are you sure there's no other way to make its stats a bit more reasonable?

**Comment by Orangerush** [comment]
@icantthinkofanameritenow lower number of bullets in the magazine, doesn't start with bullets, higher cost to make them higher cost to make new bullets that's just off the top of my head. You could also lower stun time if you want to go down that road

**Comment by icantthinkofanameritenow** [comment]
@Orangerush

I did all of that in my PR, the one comic linked to. It starts with no bullets at all and the price of the bullets is elevated on par with the SMG's. That, and its stun duration is reduced to 2 seconds so one shot isn't going to let you cuff somebody.

**Comment by Orangerush** [comment]
well there we go, no need to remove it

**Comment by aceedex** [comment]
terrible. I look forward to the removal of all guns in the future since each one will become a flavor of the month until there's nothing but toolboxes left

**Comment by Blithering** [comment]
@icantthinkofanameritenow The problem with the stun on the AR isn't the possibility of being cuffed. If you're cuffing someone with the intent of letting them live then you shouldn't be using a brute damaging weapon in the first place, and if your intent is to kill them then you can just keep firing to refresh the stun and they'll have no chance. That said removing the assault rifle is going to cause a lot of people to complain.

**Comment by ComicIronic** [comment]
@aceedex You said yourself that the Assault Rifle wasn't powerful enough to put it behind the material progress wall, and I think a bullet weapon is always going to be innately too powerful to go before that progress wall unless you nerf it to shit, so this is the compromise.

Don't act like the AR is getting this for any reason other than how powerful it is. Guncreep can go home.

**Comment by Zth--** [comment]
The question is, why don't we have a wiki with all information about guns and their power? It would be easier to see what's missing and how to balance. I'm making one about hardsuits and armors

**Comment by aceedex** [comment]
Guncreep? is that what we're really calling somethings that's been around since forever?

It's honestly astounding to me that to you people ARs are worse than the devil, but there's absolutely not a peep about cargo being able to mass order eguns, another gun capable of both stunning with the same proficiency as an AR, a lethal modes which a much, much stronger lethal option for not even materials, just fucking credits. The stuff miners drag in by the BUTTLOAD because of miningvend toys.

I've already said my piece about increasing base costs+adding plastic on top of shortening the stun time. I think it's a fair compromise that allows you to make em early and fairly efficiently without being complete bull and putting them behind the roid material wall. 

It's also a terrible terrible practice to just remove something because you can't think for a little more in order to fix it, the exact same thing that broke droppers for what I think is just wanting to get something over with. It's a bad practice

**Comment by ComicIronic** [comment]
> since forever

You mean for two years?

> there's absolutely not a peep about cargo being able to mass order eguns

In secured crates, which cargo can't just open. A scientist in research has everything available to them to break open a lockbox and get to the gun inside, assuming people are even willing to let the protolathe spawn a lockbox instead of bitching about that too.

> I think it's a fair compromise that allows you to make em early and fairly efficiently

This is the issue: why should you be able to make them early or efficiently? Why should such a weapon be available to scientists so easily at all? What does it benefit the game except for gun autists to have the rifle be so easily obtainable?

Consider that you should be comparing this to a revolver which costs TC to buy.

> It's also a terrible terrible practice to just remove something because you can't think for a little more in order to fix it

It's also terrible practice to keep something in if it's out-of-place.
We thought about it:
"Let's give the AR some higher mat costs for how strong it is"

> WAAAAAAAH NO YOU CAN'T DO THAT

"Alright, let's nerf it so it's appropriate to its current mat cost"

> WAAAAAAAAAAAH NO YOU CAN'T DO THAT EITHER

And so my conclusion was that we can't put it either side of the material wall without upsetting baby about his automatic pacifier  and maybe it's time to wean you off it entirely.

**Comment by ghost** [comment]
If you believe cargo can't open secure crates then i'm sorry, play the game more. It's the same thing as scientists 'not' being able to open the lockboxes.

**Comment by ComicIronic** [comment]
How can cargo open secure crates on their own?

**Comment by ghost** [comment]
Blow it up, goat it open, or 'gib' it. All of which they can do without leaving cargo, and mostly leaves people none the wiser that anything has happened.

**Comment by 9600bauds** [comment]
Run the crate over with the mining shuttle

**Comment by icantthinkofanameritenow** [comment]
@aceedex 

Unlike RnD, Security watches Cargo like hawks and can shut them down much faster since the HoS has access to Cargo to begin with. Plus, "gun cargo" is much more infamous on the server so Sec knows to expect it more often and punishes it more harshly when they're caught. At least, that's how I see it. 

In any event, I think I've solved the problem by just removing the AR's ability to stun entirely.

**Comment by Orangerush** [comment]
Literal baby posting 

This has gone too far @ComicIronic

**Comment by aceedex** [comment]
What a nasty post. Equating discussing a balance change to whining just to discredit it. It wouldn't be so coarse if I'd at least been actually throwing a tantrum simply going "NO NO NO" instead of at the very least explaining my stances and the logic behind them.  We disagree on things and that is fine, but Let's not act like children. The entire purpose of the repo being public is being able to discuss these things.

@icantthinkofanameritenow 
to a certain extent, I agree with you. A certain extent. 
A- Making balance changes not because something is unbalanced but because of the way people in the server *might* play is I think very poor form. 
B- We're having this discussion right now because _someone_ thought science weapons were too strong. Is that not a sign of notoriety itself? given that everyone always watches science because of explosions as well why not give them even stronger weapons if they're always being watched?

I understand what you said, why you said it and to a certain point agree, but I don't think that sentiment is something we should base balance on

**Comment by ComicIronic** [comment]
> if I'd at least been actually throwing a tantrum

Really, because what does 

> No. Fuck off. Don't nerf the fucking thing into the ground so it's no longer usable to the point it might as well be removed like the AEG.
> 
> Leave it as is. Or if you really really dislike the idea of anyone but sec and cargo having absurdly easy access to decent weapons, put a very minimal gold requirement so you can't shit them out roundstat

sound like to you?
Throughout that PR, you were rejecting nerfs because fundamentally you believed the AR didn't need any. The idea that we were having any kind of discussion, instead of trying to suggest changes that would get the stamp of approval from gunbaby supreme, is laughable.

**Comment by aceedex** [comment]
Yes, that is my starting post and I later went more in depth as to why I think the way I do. At the time, I believe we were talking about not only raising the cost but also dropping the stun altogether and lowering damage, which I think calls for a response like that. 

I do think the AR is fundamentally fine, with the only terrible factor about it being how easy to mass produce it is. Ultimately, I'm not a collaborator so I don't decide what gets merged or not. Why you're even looking at it as seeking my approval is beyond me. I don't think it's a good change, I've argued why it isn't, I've argued why I think I'm right but ultimately it doesn't fall on me what goes through. I already said before that at this point, it's an agree to disagree sort of deal

The fact that you've taken to name calling isn't exactly inspiring either. I could call you oversensitive and a myriad of other things but that accomplishes nothing

**Comment by Konater** [comment]
lol

**Comment by icantthinkofanameritenow** [comment]
@aceedex 
I guess part of it is that Cargo is easier to raid since they're more openly accessible to the "public" and have gotten enough shit over guncargo-ing to be wary of doing so when it's not needed. But the point I'm trying to make is that as much as I'm unhappy with the current status quo for it, trying to remove the offending item(s) entirely is the absolute last thing I want to do. 

In any event, the AR should now be in a relatively acceptable position; while the stun is gone, the damage is unchanged and the price still only requires metal and glass. Of course it's not the best compromise, but I have a feeling it's the best we can do at this point.

**Comment by aceedex** [comment]
If you ask me, an AR without a stun is just going to be defaulted to burst fire most of the time, which means it's just a self-pumping combat shotgun

 ¯\_(ツ)_/¯

**Comment by icantthinkofanameritenow** [comment]
It'll also be much less accurate than a shotgun, be more likely to hit bystanders, and be more expensive to reload.

**Comment by Blithering** [comment]
@icantthinkofanameritenow Wouldn't that mean it then achieves it's goal of replicating the x-com rookie mindset?

**Comment by icantthinkofanameritenow** [comment]
@Blithering
Never thought of it that way, but now that you mention it I suppose you're right.

**Comment by Intigracy** [comment]
Why not just remove the stun and nerf the damage.
It should be less than a laser shot when you consider that it causes bleeding.

**Comment by Orangerush** [comment]
@Intigracy   :ok_hand:  :ok_hand:

**Comment by Blithering** [comment]
100% agree with @Intigracy  there needs to be a reason to upgrade to laser and then plasma when the higher research tiers are reached.

**Comment by aceedex** [comment]
It's less upgrade to, and more "why even make if we can wait 15 minutes while doing research for miners to deliver, then we can just straight up make plasma"

Laser weapons are also generally better than plasma

**Comment by icantthinkofanameritenow** [comment]
@aceedex 

Only if you don't know how to use the latter effectively.

**Comment by aceedex** [comment]
I'd be inclined to disagree. Sure, they irradiate, plasma contaminate and have higher damage, but they're still a projectile

**Comment by icantthinkofanameritenow** [comment]
And? If you made them a beam, they'd be the only weapon anyone ever used other than the egun and AEG.

**Comment by FudgePucker** [comment]
Remove the stun on the rifle.
A combat shotgun with lethal shells has to be pumped to shoot again, and it doesn't cause knock down.

**Comment by aceedex** [comment]
Nothing in particular. But generally beams are simply better

**Comment by Rhydens** [comment]
It's up to security to keep people who are getting access to tech their not allowed in line, to be honest.

**Comment by 9600bauds** [comment]
Have you been in the shoes of a Sec officer trying to make sure Science is not printing guns? It's the one of the worst hells imaginable, especially without borg all-access.

**Comment by icantthinkofanameritenow** [comment]
But they're so bad at it.

**Comment by icantthinkofanameritenow** [comment]
And let's also remember than many officers look the other way as long as they can get a gun themselves.

**Comment by Rhydens** [comment]
Yes, I static in sec @9600bauds

**Pull request closed without merging**
