### PR TITLE
Makes greys acid resistant more consistent, makes it into a define

### PR DESCRIPTION
**Pull request by MadmanMartian**
Thought it odd that there was an inconsistency regarding greys in this matter. Made it into a define rather than species checking. Now, greys are immune to acid damage, but water still melts them.

:cl:
 * rscadd: Greys are now properly immune to sulphuric and polyacid

### CODE REVIEW

**Comment by Irradiation** [comment]
Do a quickie on the changelog to state that they are now properly immune to **sulphuric/sulfuric/orange juice** acids.

**Comment by MadmanMartian** [comment]
Makes them immune to polyacid too, or should that not be the case?

**Comment by Irradiation** [comment]
I thought they were only meant to be immune to sulf memes

**Comment by MadmanMartian** [comment]
I have no clue. the comments suggest only sulphuric acid, but that seems weird.

**Comment by Irradiation** [comment]
Looking at reagent code, Greys are only immune to Sacid.

**Comment by SGuivenne** [comment]
I mean worst comes to worst you just get poly acid-water memes, even though such a mix should immediately explode into a fireball and sulfuric acid smoke.  (See actual superacid IRL).

**Comment by Kurfursten** [comment]
Since no one seems to be opposed to this I'm gonna merge it

**Pull request merged**
