### PR TITLE
Snaxi Garage

### PR DESCRIPTION
**Pull request by Kurfursten**
I know I said I would do MedSci next but I have scrapped plans for it twice.

Here's something smaller and more reasonable. A new public garage for Snaxi, it comes with a key fabricator and 9 public snowmobiles. Seconds until garage is empty at roundstart? I'm guessing around 90.

image

Please wait for #24538 so I can change this to cement!

:cl:
* rscadd: Snaxi has a new public garage with snowmobiles. We hid the keys under the snowmobiles instead of under the mat.

### CODE REVIEW

**Comment by DrSnips** [comment]
Why is that north west part blocked by the snowmobiles?

**Comment by Kurfursten** [comment]
The garage architect didn't expect the garage to be full past 12:06pm, and neither of those machines should be necessary immediately at roundstart (keyfab and space heater).

**Comment by SonixApache** [comment]
*why*

**Comment by Kurfursten** [comment]
People said they thought snowmobiles would help flow.

I thought about what your counter arguments might be, and I found theoretical-Sonix made some interesting points. I'll have a PR up today to address them, probably. Keep an eye out for that.

**Pull request merged**
