### PR TITLE
Hydroponics icon refactoring

### PR DESCRIPTION
**Pull request by ghost**
This PR:
- Refactors hydroponics to use individual DMI files for each plant instead of one for every plant
- Restores some missing plant/seed icons
- Adds new seed icons for the unobtainable synthmeat plant and variants by Comrade Dispenser

I still need icons for the following things:
- Peanut packet and item
- Weed packet and item
- Brown mold packet and item

The latter two are unobtainable by normal means AFAIK so if this somehow manages to be ready for merge without them it's not a big deal.

Exotic seeds and nofruit are tested and work fine. Everything is not 100% tested as I didn't grow all ~90 plants to make sure none were missing a state. None of them SHOULD be missing a state, but it's possible that some could be mislabeled. I also didn't test the mutation that adds extra produce items to plants, but I THINK it should work fine, maybe.

:cl:
 * bugfix: Hopefully fixed a variety of issues with hydroponics plant icons and restored some missing ones.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Sneed

**Comment by SonixApache** [comment]
\>individual files for EACH PLANT
holy shit what why

**Comment by ghost** [comment]
it makes adding new ones easier and circumvents lummox's retarded icon state limit in a less janky way than overloaded read only DMIs

**Comment by SonixApache** [comment]
yeah but bloating the thing with a hundred extra files seems a bit over the top for that

Can't you just split it in two, or four?

**Comment by ghost** [comment]
Unless there's a higher performance cost for having more files I don't see an issue, everything is labelled and organized cleanly. 

If there is a technical reason to not have individual files then I can redo it to have categorical DMIs instead.

**Comment by ComradeDispenser** [comment]
You remembered to include my sprite for dead corn too, right? 

If no one else does it I'll get to work on the other sprites you need either this evening or tomorrow.

**Comment by ComradeDispenser** [comment]
Requested spritework should be done now, let me know if you need any more.

**Comment by ghost** [comment]
I think I have everything I need. I'm gonna clean this up a bit and use categorical DMIs instead of individual ones so that it's a bit more compact before I consider it ready, though.

**Comment by ghost** [comment]
Gonna close this temporarily since I haven't had time to work on it. I'll re-open it once I can get everything a bit neater.

**Comment by ancientpower** [comment]
I changed my mind, I think it's fine like this. This is probably safe to merge as-is.

**Pull request closed without merging**
