### PR TITLE
Revert "Minor ZAS Optimizations"

### PR DESCRIPTION
**Pull request by west3436**
Reverts #37277. This likely is causing Metastation atmos issues and I don't have time to work on this right now. I may come back to it later or use a different approach at speeding up ZAS.

### CODE REVIEW

**Comment by Eneocho** [comment]
I could swear some of the issues were caused by fucked up mapped-in overlapping pipes

**Comment by west3436** [comment]
> I could swear some of the issues were caused by fucked up mapped-in overlapping pipes 

Could be but like I said I'm very busy irl rn so I don't have time to to check. This is just the safe option

**Comment by Eneocho** [comment]
No I mean, they posted screenshots of the fucked up pipes, pretty sure that's the main issue, the ZAS optimization just exacerbated it.
image

**Comment by Eneocho** [comment]
Wait nevermind, there are issues on other maps as well.

**Comment by noirogen** [comment]
It was initially thought that the problem was simply waste mixing into distro, but after testing removing those overlapping pipes, pressure still rose infinitely. 

The bug happens whenever a pipenet updates, even without any gas being input/output into it. Seems to be some kind of calculation error, the rate of increase/decrease scales with pressure. 

I tested reverting the ZAS optimization PR, and that stopped the issue completely

**Comment by noirogen** [comment]
I'm not super familiar with atmos code yet but, it also kinda seems to be correlated with pipenet size/devices connected. The portable air pumps outside engineering on Metastation are on their own isolated pipenet, and they don't experience the increasing/decreasing despite the fact that that pipenet should be receiving constant updates. The bug might be connected to vents?

**Comment by jwhitak** [comment]
We can re merge this when west has time to debug.

**Comment by west3436** [comment]
> I'm not super familiar with atmos code yet but, it also kinda seems to be correlated with pipenet size/devices connected. The portable air pumps outside engineering on Metastation are on their own isolated pipenet, and they don't experience the increasing/decreasing despite the fact that that pipenet should be receiving constant updates. The bug might be connected to vents?

I'm guessing I simply used a get_readonly_air() where I shouldn't have which would cause a change to a gas mixture without the mixture properly updating in the air subsystem. If you can identify specific cases you found that'd be a huge help when I can get back to this.

**Comment by noirogen** [comment]
image

This is the simplest setup where I can get the bug to happen; with only one vent it's stable. Doesn't matter if the vents are on or off. Canister was for seeding it with gas, pump for updates. It starts off decreasing by like .1 kpa per tick, but if you unwrench the canister it will start increasing by .1 kpa per tick

**Pull request merged**
