### PR TITLE
Bar/Kitchen Revamp

### PR DESCRIPTION
**Pull request by Rei1226**
Reibay 2: Eletric Boogaloo

ss13 bar

### CODE REVIEW

**Comment by ComicIronic** [comment]
DME should not be here.

**Comment by Rei1226** [comment]
Didn't think so, but for some reason it keeps wanting to do that #define bullshit. I'll revert the dme

**Comment by Boxe** [comment]
>rei maps something that isnt shit

bullshit who are you

also pls gib chef soap for keeping homicide evidence in backroom only
also maybe have the windoor to the bar be a glass airlock instead, windoors 2 ez to destroy and 2 annoying 2 create
also >piano in the theatre

**Comment by SarahJohnson489** [comment]
Oy vey goyim.

You don't have the soda and coffee vendor in the bartenders room for a bunch of drinks you have to bitch to others for lemonjuice and shit.

Before pic, after pic, make sure it's all there. We need to stop having to go over this every time

**Comment by Rei1226** [comment]
Does the bartender really need a soda and coffee vendor when there's one right in the bar now?

**Comment by Arthurdentist** [comment]
yes because the bartender should be able to make the most basic drinks without having to leave the behind of his bar.

**Comment by SarahJohnson489** [comment]
Yeah, there's a fair bit of drinks they can make from it and a couple look good for variety not to mention it provides a good bit if you want a non-alcoholic menu gimmick.

**Comment by Boxe** [comment]
fuck you reiduny

also pls add in a basic drink dispenser for shit like gin/vodka/soda and a bottle rack for storing the clusterfuck of bottles

**Comment by Duny-** [comment]
\>entrance to the kitchen is a secure windoor in a public place
Might as well remove the door altogether.
I'd move the holopad further to the right for rage cages and put the vending machines somewhere else for the same reason (the bartender should be the one serving the drinks anyway). 
It looks like the vents and scrubbers were placed by a deficient monkey compared to the rest of them everywhere on the map which were placed by dylan's ocd.
Backroom lacks a camera. 
The bartender should have its own cola and coffee vending machines. 
There should be a table between hydrophonics and the kitchen (just make it a simple table so it's easy to disassemble if that's the problem).
A bit weird to place the trash behind a customer's chair with all this empty space near walls.
Down-right chair shouldn't be here and the topmost stool next to the kitchen makes no sense.
There is also no point of sale for the hallway but nobody cares about that.

**Comment by Duny-** [comment]
Also Rei a shit

**Comment by Rei1226** [comment]
Disposals moved, wires and pipes fixed up, windows once again placed next to entrance to bar, camera and vending machines added back to backroom
ss13 bar

**Comment by IratePirate** [comment]
Fix the wiring so it doesn't go under walls in bar storage. Needs to run under doors. Also get rid of the scrubber pipes under the bar storage wall and have them run out into maintenance. If that makes sense.

Looks good though.

**Comment by Rei1226** [comment]
Fixed, thanks

**Comment by SarahJohnson489** [comment]
Where's the bartender disposal for when cargo tags and sends shit through disposals + disposaling empty bottles? I'd say swap the table and the booze-o-mat and put the disposal left of the top right corner.

I'm not familiar with the disposals routing system, will you need to adjust something so things tagged bar still get there?

**Comment by Arthurdentist** [comment]
As Duny said, I think you should have a proper door leading into the kitchen. Nothing is more annoying then being the chef and having some greytide shitters steal your shit from the kitchen. Don't make it easier for them.

**Comment by Rei1226** [comment]
Another disposal placed behind bartender's counter. Keg moved to backroom. Disposal pipes have to go through the wall unfortunately because the pipes can be really wonky sometimes when placed near each other and spit garbage out of each other.

Also added a bit more lighting

Not going to change the windoor to kitchen since people were bitching to me in the thread about making it a windoor instead of a regular door (including pomf)

ss13 bar

**Comment by Rei1226** [comment]
Tile painter, crowbar and metal placed in bartender's back room in case he decides he wants to rip up the wood floorboards and put down his own design instead. Metal removed from bartender counter

**Comment by frangi** [comment]
Looks really good, finally the chef has proper sight of the bar.

Only things I don't like: 
-south holodeck, in particular the walls facing the windows.
It looks a bit stupid to me, maybe try shifting the holodeck up? Or I'm sure the holodeck windows aren't actually part of the holodeck, you could try experimenting by replacing the S - SE side with walls.

-no maint access directly from the bar, but this is really minor, I guess we'll see a lot more traffic from the holodeck area, which is good.

**Comment by SarahJohnson489** [comment]
Give a screwdriver to unsecure the wood floor tiles instead of destroying wit ha crowbar and a wrench to move machines then

Do a once over as AI then as officer for light/camera coverage and labels

What's his face modified things so that the rsf starts in the back with matter carts. check out the changelog for it if you want to match

**Comment by Riukanojutsu** [comment]
where dat RSF at?

**Comment by SarahJohnson489** [comment]
He said it was in the back under the pile of crap IIRC. When he's all done he's probably gonna want to delete then put it back so it's on top or do some pixel x/y to get more stuff visible

**Pull request merged**
