### PR TITLE
Farsight is now a toggle

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Also fixes random cryokinesis typo that was old for whoever knows long and telekinesis typo
:cl:
 * tweak: The farsight genetic power is now a toggle ability, in case you didn't want your overlays to be ruined indefinitely and the like.
 * spellcheck: Fixed a typo for the description of cryokinesis superpower.
 * spellcheck: Fixed a typo for the telekinesis superpower (not observable in-game).

### CODE REVIEW

**Comment by SirSkeleto** [comment]
can we get a toggle for some of the other potentially annoying """powers""" as well
chameleon and noir come to mind

**Comment by boy2mantwicethefam** [comment]
Noir isn't a superpower, but okay for chameleon, though I need a sprite for the spell

**Comment by SirSkeleto** [comment]
scaling down a poorly cropped jpg of a chameleon is top comedy
https://cdn.discordapp.com/attachments/400267521120403465/561230792924332035/chameleon-sleepy.adapt.945.1.png

**Comment by boy2mantwicethefam** [comment]
Though I think of leaving chameleon for another time, mostly because it would start turning unatomic (even if it's already unatomic as it is including this random typo I'm fixing)

**Pull request merged**
