### PR TITLE
new ai holograms

### PR DESCRIPTION
**Pull request by robintime**
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj

made these to go along with a couple existing core sprites, specifically the alien queen, gondola, syndikat, and wasp

open to more suggestions for holograms (dont say fix the advanced hologram system i dont know how to do that) bonus points if they correlate to a core sprite

:cl:
 * rscadd: adds four new hologram sprites

### CODE REVIEW

**Comment by Eneocho** [comment]
Can we get Lampy the Lamprey as an AI hologram?

**Comment by GreatBigFailure** [comment]
Clown in a cardborg helmet

**Comment by Eneocho** [comment]
A standard AI holo that sometimes blinks into a red malf AI holo then back into the normal AI holo.
A red malf AI holo for when the AI is actually malf.

**Comment by robintime** [comment]
> Clown in a cardborg helmet

I like this one, I'll see what I can do

**Comment by cloutcode** [comment]
floating ball of fire to go with firewall

**Pull request merged**
