### PR TITLE
Round Randomized Reagent

### PR DESCRIPTION
**Pull request by ebakai**
## What this does
Adds effects to simpolinol for player controlled `/mob/living/carbon/human`s. The effects are randomly selected during server initialization. 

## Why it's good
* Potent healing chemical? Horrible poison? Waste of everyone's time? There's only one way to find out!
* Gives players a reason to make simpolinol. Only 50u have been made this year (by one guy).

## Todo
Feedback and ideas are appreciated.
- [x] Convert the global variable into a list
- [x] More logging
- [x] Test all the effects

#### Effects
- [x] Brute/oxy/tox/fire/clone/brain damage / healing
- [x] Instant death with a chance of gibbing or explosion
- [x] Simplemob transformation
- [x] Boring guy transformation
- [x] Catbeast transformation
- [x] Damage type scrambling
- [x] causes hallucinations

## Changelog
:cl:
 * experiment: Nanotrasen's pharmaceutical division is asking for volunteers to test the effects of simpolinol on complex sentient lifeforms

### CODE REVIEW

**Comment by ExpulsionSnooper** [comment]
Very nice, giving research a reason to actually research. Exactly what makes anomaly hunting so great.

**Comment by Eneocho** [comment]
Some effect ideas:
* Phazon's advancedmutate.
* pAIsmoke's electrolyzing into smoke components.
* Instant water-potassium reaction (purging all reagents).
* Species change to gray with a chance for the reagent to work like water.
* Species change to insectoid with a chance for the reagent to work like insecticide.
* Increasing/Decreasing max health.
* Increasing/Decreasing damage type resistance.
* Increasing/Decreasing thresholds for hypothermia/hyperthermia.
* Inverting reagent behaviours while in body (If you have the chem on you, drinking pacid heals burns while drinking kelo causes burns).
* Does nothing but has a 1/10000 chance for 300x300 waterpot-sized explosion.
* Does nothing but has a 1/100000 chance for 50u nitroglycerin explosion.
* Does nothing but has a 1/1000000 chance for shard-sized explosion.
* Does nothing but has a 1/10000000 chance for maxcap explosion.
* Does nothing but has a 1/100000000 chance for nuke explosion and round end (HENK!!!)
* Reagent works like poison/acid for one random species.
* Does nothing.
* Forces the user to say excerpts of WGW.
* Makes the user reflect bullets/lasers/tasers.
* The user lubes the tiles he walks on.
* The user releases colourful reagent smoke clouds.
* Changes the colour of the user's blood/skin/hair.
* Makes you perfectly space resistant.
* Reverts your pressure resistance so vacuum is good while 101kpa is lethal.
* Makes you retarded.
* Fills you with blockizine.
* Completely neutralizes a specific chem's effect (medicine or poison/acid), such that you can drink the neutralized chem like water.
* Turns you into the amogus flash that just got added.
* Behaves exactly as a specifc chem.
* Instantly repairs all your organs.
* Turns any reagent into more of itself (like midazoline).
* Turns any reagent (except itself) into another reagent.
* Oxycodone-tier painkiller.
* Pain toxin that increases the pain counter.
* Increases/Reduces RAD_TICK (like greyshit vodka).
* Spawns simplemobs from you like the amino-chems.
* Freezes time around the user every couple of ticks (5 tiles?).
* Sends stuff to the past/future like the special time grenades.
* Turns you into a ling/vampire.
* Instantly kills you if you are a ling/vampire.
* Instantly kills you and deletes your brain.
* Turns you into a zombie.
* Instantly kills you and animates your corpse.
* Makes your punches stronger.
* Increases/Decreases your tackle attack/defense.
* Increases/Decreases your tackle distance.
* Increases your strong value (like sports drink) by a randomized multiplier.
* Reverts your controls (so you need to press down to go up).
* Rotates your screen (like upgraded disorient).
* Hulks you.
* Makes you invisible.
* Makes you wide/tall.
* Replaces your limbs with robotic parts.

**Comment by Eneocho** [comment]
I would've made this a feature of Mannitol, not Simpolinol, since Simpolinol is almost never made (same with most metals-dependent recipes) and already has a functionality, while Mannitol is relatively common and has no use besides fluff. 
Giving Mannitol some use would encourage more ghetto chem with a gambling theme. You might heal from that near death after facing a rogue captain, or you might die an even quicker death. All you can do is open a can and drink.

**Comment by ebakai** [comment]
Potentially getting round removed for drinking a soda is lame. I intend to keep things flexible enough that nerfed randomizers could be added to mannitol (or whatever) in the future, but it's out of scope for now.

I chose simpolinol *because* it's underused. No sense in cluttering things up with a new reagent when there's one just begging for some work. It also makes sense to me lore wise. Simpolinol already works on simplemobs because ???, why shouldn't ??? interact with human consciousness to produce wacky effects?

**Comment by Eneocho** [comment]
> I chose simpolinol *because* it's underused. No sense in cluttering things up with a new reagent when there's one just begging for some work. It also makes sense to me lore wise. Simpolinol already works on simplemobs because ???, why shouldn't ??? interact with human consciousness to produce wacky effects?

I get that, but it's quite different to theorycraft your reagent than to have it used in game.
Midazoline, Bumcivillian, all the amino-reagents, phalanximine, etc, all suffer from the same thing. They're cool conceptually but they are too expensive or weird to make that they never see any use. 
And it's not like Mannitol is a new reagent, it's been there for a while (Mann's drink on Groans Soda vendors). It literally has no effect while the simpolinol already has one.
Having the effects on Mannitol would allow for the randomized nature to be used relatively often, since you don't have to overcome the need for silver, which limits the crafting of this Simpolinol to RnD and sometimes Chemistry.
I'm telling you, don't fall for the "we must make it rare/expensive" idea, that just makes your change unusable.
Just look at the randomized reaction with Phazon-Nothing. It is way too expensive to be worth it (10 whole phazon sheets for 1u of a random chem, which most of the times is a drink).

**Comment by ebakai** [comment]
If simpolinol is still too expensive even with interesting effects, then it needs to be cheapened. Replace the silver with tricordrazine and a plasma catalyst, whatever.

I don't necessarily want this to be expensive, and I don't want it to be rare, but I do want it to have to be deliberately made.

**Comment by gurfan** [comment]
> Some effect ideas:
> 
> * Phazon's advancedmutate.
> * pAIsmoke's electrolyzing into smoke components.
> * Instant water-potassium reaction (purging all reagents).
> * Species change to gray with a chance for the reagent to work like water.
> * Species change to insectoid with a chance for the reagent to work like insecticide.
> * Increasing/Decreasing max health.
> * Increasing/Decreasing damage type resistance.
> * Increasing/Decreasing thresholds for hypothermia/hyperthermia.
> * Inverting reagent behaviours while in body (If you have the chem on you, drinking pacid heals burns while drinking kelo causes burns).
> * Does nothing but has a 1/10000 chance for 300x300 waterpot-sized explosion.
> * Does nothing but has a 1/100000 chance for 50u nitroglycerin explosion.
> * Does nothing but has a 1/1000000 chance for shard-sized explosion.
> * Does nothing but has a 1/10000000 chance for maxcap explosion.
> * Does nothing but has a 1/100000000 chance for nuke explosion and round end (HENK!!!)
> * Reagent works like poison/acid for one random species.
> * Does nothing.
> * Forces the user to say excerpts of WGW.
> * Makes the user reflect bullets/lasers/tasers.
> * The user lubes the tiles he walks on.
> * The user releases colourful reagent smoke clouds.
> * Changes the colour of the user's blood/skin/hair.
> * Makes you perfectly space resistant.
> * Reverts your pressure resistance so vacuum is good while 101kpa is lethal.
> * Makes you retarded.
> * Fills you with blockizine.
> * Completely neutralizes a specific chem's effect (medicine or poison/acid), such that you can drink the neutralized chem like water.
> * Turns you into the amogus flash that just got added.
> * Behaves exactly as a specifc chem.
> * Instantly repairs all your organs.
> * Turns any reagent into more of itself (like midazoline).
> * Turns any reagent (except itself) into another reagent.
> * Oxycodone-tier painkiller.
> * Pain toxin that increases the pain counter.
> * Increases/Reduces RAD_TICK (like greyshit vodka).
> * Spawns simplemobs from you like the amino-chems.
> * Freezes time around the user every couple of ticks (5 tiles?).
> * Sends stuff to the past/future like the special time grenades.
> * Turns you into a ling/vampire.
> * Instantly kills you if you are a ling/vampire.
> * Instantly kills you and deletes your brain.
> * Turns you into a zombie.
> * Instantly kills you and animates your corpse.
> * Makes your punches stronger.
> * Increases/Decreases your tackle attack/defense.
> * Increases/Decreases your tackle distance.
> * Increases your strong value (like sports drink) by a randomized multiplier.
> * Reverts your controls (so you need to press down to go up).
> * Rotates your screen (like upgraded disorient).
> * Hulks you.
> * Makes you invisible.
> * Makes you wide/tall.
> * Replaces your limbs with robotic parts.

kill yourself immediately 
A randomized reagent is cool but some of these ideas are so unbelievably dumb no amount of rarity should excuse them

**Comment by Eneocho** [comment]
> kill yourself immediately A randomized reagent is cool but some of these ideas are so unbelievably dumb no amount of rarity should excuse them

I'm just spitballing some ideas, it's up to the coder to implement what he likes, he asked for ideas and I provided some that came to mind. Relax a little, man.

**Comment by assmops** [comment]
some random negatives
1. temporary monkeyization/species change
2. removal of dexterity/fine motorics (unable to use guns, etc)
3. random large amount of brain damage (60+ minimum)
4. random amount of toxin damage, ranging from 10-80
5. activates a random genetic disability, with bias towards tourettes/lisp/swedish/clumsy

some random positives
1. heals a random amount of brain damage 
2. acts as a strong painkiller until metabolized
3. deactivates a random genetic disability
4. maxes a random virology antigen
5. changes your faction/adds you to a faction (to make certain simplemobs nonhostile to you, things like nukies/spessmart should be blacklisted)

some random neutrals

1. changes all damage types around (ie, if you have 30 brute and 10 burn, you could end up with 30 toxin and 10 clone)
2. literally nothing happens
3. makes a simplemob clone of yourself
4. causes hallucinations
5. literally nothing, but it notifies an admin like a prayer, to let them create their own effect

**Comment by ebakai** [comment]
I could use advice on how to properly do the initialization stuff I'm doing at the end of randomized_reagent.dm. General advice and criticism are also welcome, of course.

**Comment by kernikov** [comment]
Add admin logging for what it does.

**Comment by ebakai** [comment]
I think I'm finished with this idea for now. Please shill for this PR in the discord.

**Comment by ebakai** [comment]
@Kurfursten
Merge or tell me why I'm stupid please

**Pull request merged**
