### PR TITLE
Refactored implants

### LINKED ISSUE #28900: You can greytide implant Syndicate Challengers
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
851bbea25d6220a1fb55474d16c0e5bde09b3cdf

# Description
Syndicate Traitors can't be implanted but challengers can, leading to someone having protect and kill objectives for the same person.

### LINKED ISSUE #30729: Implants Breaking after surgery
(WEB REPORT BY: knife28 REMOTE: 206.221.180.138:7777)
# Revision
a8b0b98965c75ef83e623666d7513b7fa5c58ef0

# Description
Certain implants break after surgery

# Steps to Reproduce
>Inject person with Freedom (and potentially other) impant
>Perform surgery on their chest
>see if implant still works
# What you Expected
The implant would work as normal, uncuffing me 

# What Actually Happened
During a traitor round, I implanted myself with a freedom and uplink implant. The CMO performed surgery on my chest and afterwards I was unable to use my freedom implant.

### LINKED ISSUE #30807: Explosive implant not triggering on *deathgasp for Nuklear Operative.
(WEB REPORT BY: cmdrstupid REMOTE: 206.221.180.138:7777)
# Revision
b575a71b92add50e00eb6a85ae1b02d0ac9ed2e4

# Description
As a roundstart operative, got tased and cuffed, and eimplant didn't activate on *deathgasp. This was using a macro set to *deathgasp. Tried while stunned, tried while cuffed and being pulled, tried cuffed and not pulled, tried while in crit.

# Steps to Reproduce

# What you Expected
A borg getting the bing bong bannerino for dragging a bomb into a crowded area.

# What Actually Happened
A flukie spamming *siezes up and falls limp* like an idiot.

### PR DESCRIPTION
**Pull request by DamianX**
Closes #30807
Closes #30729 I think. I think the surgery had nothing to do with it, they were just broken.
Closes #28900

:cl:
 * bugfix: Fixed explosive implants not being triggered by the *deathgasp emote (or death).
 * tweak: Attempting to use an implant on a mob that's not compatible with it will no longer consume the implant. Loyalty and greytide implants are still consumed if the target resists the implant, as before.
 * tweak: Implanting a compressed matter implant into someone else will no longer let the implantee choose the activation emote. The implanter chooses instead.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
While you're at it, can compressed matter implants only give the emote activation message if you use it on yourself? There's a lot of potential goofs with using them on someone else ruined by the give-away.

**Comment by DamianX** [comment]
image
Done. Only the guy doing the implanting gets to choose the emote.

**Comment by GreatBigFailure** [comment]
Hell ya, thank you.

**Comment by GreatBigFailure** [comment]
>All those exile implant changes

I still don't know why but it really did refuse to work when I just made it imp_in and got rid of the theExile var. It should have changed nothing. Maybe if I re-read it now it would become obvious but I guess it doesn't matter.

**Comment by cmdrstupid** [comment]
That was fast! Thanks DamianX!

**Pull request merged**
