### PR TITLE
Moves nuke ops shuttle farther from the station, other small changes

### LINKED ISSUE #7591: Make the Nuke-Ops shuttle console require an agent ID to use
Banning people for stealing the shuttle is stupid, but if there's an issue with people being able to steal it, let's make it more of a challenge to do so.
The console could be made DNA-dependent, removing the possibility of a crewmember using it, but that's no fun at all.

### LINKED ISSUE #10332: Nuke OP Access
Crew members can still Nuke OP/Raider shuttles by simply touching the computer.

Probe1 - Today at 1:57 AM
i've never understood that rule and think its a code issue more than an admin issue
if a player finds it a player finds it
if they shouldn't be allowed to ship jack then the console should have 

req_access =list(sydicate_access)

and if a playyer kills a nuke op (or heister), FINDS the ship, and steals it then good on him.

nuklearcellphoneg - Today at 2:06 AM
^
hey let's make an issue I'm sure it will get fixed

Probe1 - Today at 2:27 AM
it would take like
30 seconds to fix
legit make an issue and i will

### LINKED ISSUE #10782: Nuke ops only get one military PDA
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision d9d1058108444a2c181fd3d9178da1f56744d22f 
> 
> General description of the issue
> If the shuttle shutters are dropped and the person with the PDA dies, ops can't practically get onto their own shuttle.
> 
> What you expected to happen
> Five PDAs, one per operative. Perhaps without the built-in dex cart.
> 
> What actually happened
> Just the one PDA.
> 
> Steps to reproduce if possible
> Become an operative, look around on your shuttle.

### LINKED ISSUE #11525: Make the Nuke Ops shuttle be further away from the station or something
Some of the docking areas are way too close to the station and it brings up that whole "metagaming" thing. Like currently you can see the shuttle from solars and shit like that. With our maps being 500x500 or whatever can't we have it deeper in space or something, to make it more clear when people are being meta dicks

### PR DESCRIPTION
**Pull request by Sprok0**
Moves all the syndicate shuttle docking points about two to three screens away from the station, now that ops get holomaps showing where the shuttle is at.
Makes ops spawn wearing holosuits, rather than needing to swap suits from their lockers.
Gives ops jetpacks 50% more capacity, to compensate for more mandatory flight distance.
Moves the pinpointers into the individual op lockers, instead of leaving them all in the gear closet.
Moves the door function from the detomatix cart to a new cart.
Gives each personal locker a PDA that can open/close the shuttle blast door.
Makes the PDAs not start with a registered name, so you can put your agent ID name onto them.
Removes the extra agent IDs from the personal lockers.
The syndicate shuttle control computer can't be emagged.
Gives the syndicate shuttle three more docking points, for a total of 8 around the station, one at the mining outpost, one at the research outpost, and one at the comms satellite.

Fixes  #11525
Fixes  #10782
Fixes #7591, but not really because that was fixed earlier
Fixes #10332 same as above
Fixes half of #6798

### CODE REVIEW

**Comment by jakmak3** [comment]
would this be enough to stop metagaming fags from waiting at the op shuttle though?

**Comment by Sprok0** [comment]
I'm fine with people actually chasing ops to the shuttle, not with people flying around the station and "happening" to come across the shuttle. With each op being able to close the blast doors and there not being a bunch of agent IDs lying around to give access to the console, this should cut down on the ease of hijacking the shuttle. I kind of want to put gun turrets on the shuttle but that's probably too far

**Comment by ComicIronic** [comment]
Haven't you made it easier to hijack because any op dying without a detonation now gives the door control to the crew?

**Comment by Sprok0** [comment]
That isn't any different from now, when an op dying without destroying their gear gives them access from the agent ID, or by hacking the door that no one ever puts the blast doors over because there was only one PDA, or by breaking the front windows that no one remembers to put the shutters down.

 If an op is stripped they're ruined anyway,  the crew would have their holomap and be able to track all the ops and their ship.

**Comment by Probe1** [comment]
>OP dying without blowing up in the poor sods face that stunned him

**Comment by TheFriggenSawbones** [comment]
god bless you

**Comment by ComicIronic** [comment]
Is there still an option for stealth ops to send in someone who isn't wearing a holosuit?

**Comment by Sprok0** [comment]
They can take the holobadge off their suit, or switch to the normal syndicate jumpsuits in their lockers, or buy a chameleon jumpsuit

**Comment by Intigracy** [comment]
Yes.

He put the regular tactical jumpsuits back in the lockers when he put the holosuits on nuke ops by default.

**Comment by ComicIronic** [comment]
Looks fine, left to someone for balance.

**Comment by Probe1** [comment]
Seems fine to me balance wise.

**Comment by Intigracy** [comment]
If you're curious where the conflict came from:
https://github.com/d3athrow/vgstation13/pull/12634/files#diff-ce2bcb95dc603bbe41e96e5130de2bb4R12043

One of the few things the map merge tools don't account for, new turf definitions in the middle of the file (stupid byond).

**Comment by ComicIronic** [comment]
Unfortunately, has map conflicts.

**Comment by Intigracy** [comment]
If this is ready, it'll be merged when the conflicts get fixed.

**Comment by Sprok0** [comment]
conflicts removed

**Comment by Probe1** [comment]
This is why I'm such a nagger about getting map PRs merged.  FUCK MAPPING CONFLICTS.

**Comment by Sprok0** [comment]
Is there any better way to de-conflict maps other than manually re-doing all the changes on an updated map, because that's not so awful with moving a few objects around, but I cannot imagine doing it for anything more in-depth.

**Comment by Intigracy** [comment]
I've never tried before but you could try using prepare_map.bat, then
rebasing onto bleeding-edge, then clean_map.bat.

**Comment by Probe1** [comment]
I've done that before ^

**Pull request merged**
