### PR TITLE
Prevents restrained spam

### LINKED ISSUE #14374: Moving while cuffed spams the message
#### Description of issue

if you attempt to move while cuffed it spams the message enough to crash byond

#### Specific information for locating

handcuffs, probably other types of cuffs

#### Length of time in which bug has been known to occur

a few days? i just noticed that was the problem when the game crashed

#### Server revision

da57131d66f7a8213961b137837e099b755f6b7a 
Patches: c59333d8d4afdada839834747f67f85c9c964805 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by mtpowell**
Fixes #14374

### CODE REVIEW

**Comment by Exxion** [comment]
That copypaste hurts me
Not that it's your fault

**Comment by mtpowell** [comment]
This whole game hurts me

**Review by PJB3005 — APPROVED** [review]

**Comment by mtpowell** [comment]
Wait is that 'changing org' shit still fucking up PRs?

**Comment by PJB3005** [comment]
It only fucked up PRs made before we changed the org (not the case here), and even the ones that are still fucked up can still be merged manually by us.

Don't worry about it.

**Pull request merged**
