### PR TITLE
Minor aesthetic virtual wallet changes

### PR DESCRIPTION
**Pull request by adacovsk**
Finally uncouples a bunch of things from mind.initial_account so characters don't need a mind to be equipped.

Tested roundstart: mimes, clowns, AI, trader, captain, QM, wizard, malf AI
Tested latejoin: wizard, trader, mime, clown, infiltrator, changeling
Tested midround: wizard, prisoner
Tested account creation and linking with IDs
Tested cargo computer, vending machines, ATMs (all functions)

## What this does
- Changes account creation slightly so that virtual wallets can also be defined as a parameter. Basically reorganizes virtual into database accounts, instead of having separate accounts in IDs, minds, and in the database (WHY). Money and virtual are still separate inside the money_account datum in the account database, but are accessed in a similar way now. About 600 lines of code were changed, dedicated to removing `money_account` from IDs and `mind`
- Renames ID member variable `associated_account_number` to `account_number`
- Renames some `create_account()` variables to `money_account` names to avoid confusion (trust me, it gets confusing)
- consolidates some backend functions that all did the same thing
- cargo console computer uses your virtual account instead of bank account to purchase
- transaction history displayed in PDA now combines both virtual wallet and bank account together
- makes `attemptlatejoin` slightly less cluttered

image
how PDA currently looks (only visual change):
image
image

## Why it's good
- Reorganizes some backend stuff so that things are more clear and uncoupled

## Changelog

:cl:
 * tweak: transaction history displayed in PDA now combines both virtual wallet and bank account together

### CODE REVIEW

**Comment by west3436** [comment]
What does this look like to a player now? Does the round just start and we wait at the lobby screen until everything is fully loaded or are we going to face another strange purgatory before we can actually start moving?

**Comment by adacovsk** [comment]
> What does this look like to a player now? Does the round just start and we wait at the lobby screen until everything is fully loaded or are we going to face another strange purgatory before we can actually start moving?

Splash screen

**Comment by west3436** [comment]
wait hang on this isn't atomic at all what the fuck

**Comment by pedr69** [comment]
to think all this happened because someone was upset because the department lights took 2 seconds to turn on after roundstart

**Comment by adacovsk** [comment]
> to think all this happened because someone was upset the department lights took 2 seconds to turn on after roundstart

TEN SECONDS

**Comment by Hinaichigo** [comment]
It'll be nice aesthetically to have the round start in a fully-loaded state.

**Comment by west3436** [comment]
This is now removing the virtual wallet? What the fuck?

**Comment by djkramer123** [comment]
smells like unatmoic in here

**Comment by PrimeDSS13** [comment]
entirely unatomic also horrible change
virtual wallets are what protects your entire bank account from being drained
it's ridiculous to remove features because it interferes with a bug you made apparent

**Comment by kernikov** [comment]
This is peak "sneaky coder menace", shame on you.

**Comment by Kurfursten** [comment]
Having virtual wallet and station account be separate is a valuable thing that comes up a lot. Like, for example, no less than 24 hours ago I stole all the money out of 3 player PDAs. That didn't hurt them too much because they could just go get more from the ATM, but without virtual wallets I could've taken them for everything they're worth.

**Comment by adacovsk** [comment]
> Having virtual wallet and station account be separate is a valuable thing that comes up a lot. Like, for example, no less than 24 hours ago I stole all the money out of 3 player PDAs. That didn't hurt them too much because they could just go get more from the ATM, but without virtual wallets I could've taken them for everything they're worth.

I know, before I removed it, I mentioned I would add security preferences to withdrawals from PDAs, but it seems a majority disliked the idea, so I'm no longer doing it

**Comment by adacovsk** [comment]
I am not sure why there are downvotes, I undid the changes regarding merging the virtual wallet and bank account together. They will remain separate and keep both their same functionalities

**Comment by Hinaichigo** [comment]
Can you still remember your bank account info with Notes?

**Comment by adacovsk** [comment]
> Can you still remember your bank account info with Notes?

yes

**Comment by NigglyWiggly** [comment]
This is one of the least atomic PR’s that isn’t a bunch of new features I’ve ever seen

no-naked is good though

**Comment by adacovsk** [comment]
> This is one of the least atomic PR’s that isn’t a bunch of new features I’ve ever seen
> 
> no-naked is good though

It's actually atomic, but comes with fixes and better code readability. There's no way around this in mind.dm:

```
/datum/mind	
var/datum/money_account/initial_account
var/initial_wallet_funds = 0
```
And:
```
/obj/item/weapon/card/id
var/datum/money_account/virtual_wallet = 1	//money! If 0, don't create a wallet. Otherwise create one!
```

**Comment by Hinaichigo** [comment]
The eyes of both of them were opened, and they knew that they were naked. So they sewed fig leaves together, and made coverings for themselves.

**Comment by WindowsErrors** [comment]
hey if the cargo console computer uses the wallet instead of the bank account to purchase stuff won't it become impossible to order stuff using the budget cards

**Comment by adacovsk** [comment]
> hey if the cargo console computer uses the wallet instead of the bank account to purchase stuff won't it become impossible to order stuff using the budget cards

Nope those are card, not card/id

**Comment by adacovsk** [comment]
> hey if the cargo console computer uses the wallet instead of the bank account to purchase stuff won't it become impossible to order stuff using the budget cards

Nice catch

**Comment by pedr69** [comment]
oh yeah could you make the cargo computer take from the virtual wallet while you're unatomising everything

**Comment by Theophrastus1** [comment]
goddamn i wanna drop a rock in your head's direction sometimes for shit like this

**Comment by WindowsErrors** [comment]
see, being unatomic doesn't count for bug fixes

the trick is where the line is between bug fixes and not bug fixes

**Comment by west3436** [comment]
nakedness somehow has stopped happening now so I don't see the necessity of this PR

**Comment by pedr69** [comment]
it did, but now the rounds start anywhere from 11:58 to 12:00

**Comment by adacovsk** [comment]
> nakedness somehow has stopped happening now so I don't see the necessity of this PR

It actually still happens but not to yourself. It will get worse with more players

**Comment by SECBATON-GRIFFON** [comment]
why is this still open

**Comment by adacovsk** [comment]
> why is this still open

I can still improve the systems but been busy

**Pull request closed without merging**
