### PR TITLE
added plasmeme librarian suit

### PR DESCRIPTION
**Pull request by cloutcode**
Because I like suits and I think more unique suits is a good thing to have.  Includes an entertaining small hat for all the journalist plasmemes out there. If anyone wants to tell me why adding something to suits.dmi makes it smaller, I am open to all information

librarain plasmeme

:cl:
 * rscadd: Added a plasmaman librarian suit that plasmamen librarians now spawn with.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
cute hat

**Comment by SonixApache** [comment]
should make a no-hat version for librarians and only apply the hat version for journalists tbh

**Comment by cloutcode** [comment]
the hat is good

**Comment by ArchSunder** [comment]
wait is that a halo sword cursor

**Comment by juanototo2** [comment]
>unironic custom cursors
>CY+7

**Comment by cloutcode** [comment]
ok if you guys have a problem with my custom cursors i don't wanna hear it in my PR okay
image

**Comment by PrimeDSS13** [comment]
thought the PR was good but then I saw the cursors.
gonna have to drop a thumbs down now...

**Comment by Kurfursten** [comment]
conflicts

**Comment by cloutcode** [comment]
FUCKFUCK FUCK FUCK I FUCJKED IT UP

**Comment by aceedex** [comment]
Rip

**Comment by Kurfursten** [comment]
just re-download the sprites from your old commit, no big deal

**Comment by cloutcode** [comment]
GIVE IT A SECOND
IT'S JUST A SPIKE, IT'LL SOON STABILIZE

**Comment by cloutcode** [comment]
I FIIIIIIIIIXED IT

**Pull request merged**
