### PR TITLE
Horizon Changes

### PR DESCRIPTION
**Pull request by plosky1**
Lots of changes so just look at the render. Notable sec overhauled (big thanks to @SonixApache), mechanics and tech storage moved, maint connected more, library and chapel expanded, and more QoL fixes.

ship

:cl:
 * rscadd: Big changes to Horizon, notably sec overhaul, tech storage and mechanics moved, library and chapel expanded, disposals fixed, and more.

### CODE REVIEW

**Comment by jknpj** [comment]
It looks less like a shuttle and more like a station. What the fuck happened?

**Comment by plosky1** [comment]
Since we don't have code allowing ships to have multiple areas, the lore is that the engines are broken. @ me when we have that, or an item that allows movement through hyperspace.

**Comment by SonixApache** [comment]
image
?

**Comment by plosky1** [comment]
Just render problems, they're electrified from both directions.

**Comment by thestubborn** [comment]
still see an air alarm over the cargo autolathe, oh and were the weirdness of the levers fixed?

**Comment by plosky1** [comment]
Levers were fixed in the original push of this PR.

**Comment by plosky1** [comment]
Closes #25331 #25329 #25306

**Pull request merged**
