### PR TITLE
set "save map by coordinates" category to server instead of fun

### PR DESCRIPTION
**Pull request by toomykins**

### CODE REVIEW

**Comment by CrazyAmphibian** [comment]
now do the rest of the admin tools

**Comment by toomykins** [comment]
> now do the rest of the admin tools

@jwhitak said to fuck off

**Comment by CrazyAmphibian** [comment]
> @jwhitak

nobody cares.

**Comment by toomykins** [comment]
> > @jwhitak
> 
> nobody cares.

exactly

**Pull request merged**
