### PR TITLE
Removes no_shoes slowdown

### PR DESCRIPTION
**Pull request by yackemflam**
Because there are no evidence that either way is faster.

### CODE REVIEW

**Comment by jknpj** [comment]
What lazy way to do it

**Comment by yackemflam** [comment]
Not really, it leaves in the choice to increase or decrease it in the future
Also there's a function that relies on it

**Comment by yclatious** [comment]
Get some shoes on hippie.

**Comment by jknpj** [comment]
the cold floor of the station makes you slower

**Comment by DamianX** [comment]
so if there's a fire you run faster?

**Comment by ghost** [comment]
Did you test this?

**Comment by Blithering** [comment]
Clearly space shoes have been designed by shoe scientists to increase your performance.

**Comment by CptWad** [comment]
gee if shoes don't matter then why don't Olympic runners stop wearing shoes? They don't contribute at all to speed so therefore there IS NO REASON to wear shoes. We should all go back to the STONE AGE where we drive cars using are BEAR DAMN FEET

**Comment by yclatious** [comment]
Everyone in the station is running all the damn time, have you ever ran in flip flops or barefoot? Shit is not optimal at all and running barefoot hurts when you are doing it fast, put some fucking shoes on you half assed hippie.

**Comment by Riekland** [comment]
okay dude no

**Comment by d3athrow** [comment]
No

**Comment by yclatious** [comment]
Pomf has spoken, feetfags btfo.

**Comment by SonixApache** [comment]
fucking sandrunners

**Comment by yackemflam** [comment]
Again, there are no evidence that running with shoes or without makes you slower

**Comment by d3athrow** [comment]
I give no shits what you think it's purely for balance and nothing more

**Comment by yackemflam** [comment]
1960's olympic runner did set a world record (at the time) for a MARATHON

**Comment by yackemflam** [comment]
And what's so balanced about it?

**Comment by SonixApache** [comment]
we had this discussion in discord about 2 months ago where we also told you you're a dumb fuck

there is absolutely no need for the big chicken to repeat every single reason we already gave you

**Comment by RFultra** [comment]
Fucking NO

**Comment by Fruktlimpa** [comment]
It is obvious. The spessman with shoes worry not for what he might tread upon and thus runs at maximum speed.
The spessman without shoes worry about stepping on shards, dna-injectors, used syringes, virus syringes, junk of all kinds of shit, and more, and thus unconsciously pace himself so that he has time to react.

**Comment by Arthurdentist** [comment]
this change nerfs shoe snatch

**Comment by yackemflam** [comment]
no one called me a dumb fuck because there is legit no difference between running with shoes and running without shoes. a BUNCH of articles says it

**Comment by yclatious** [comment]
You have gotten two dirrect "no"s from the chickun, 14 👎 , 2 😕  and about 6 people saying you are a dumbfuck.

It isnt going to pass.

**Comment by SonixApache** [comment]
02/21/2017, ick channel. Look up the logs yourself.

**Comment by yackemflam** [comment]
Thats a lot longer than 2 months

**Comment by yackemflam** [comment]
Looked it up, I see beach talk, spess fun bucks talk, and food talk

**Comment by Intigracy** [comment]
This is less about realism and more about the gameplay effect it has.
Also have you ever walked barefoot on a cold floor, it sucks.

Pomf said no and I don't see anyone else at all having an issue with lack of shoes making you slower, so I'm just gonna close this.

**Pull request closed without merging**
