### PR TITLE
Demilitarize Castle Station

### PR DESCRIPTION
**Pull request by gurfan**
- Removes all guns from the map (excluding tasers in command lockers) 
- Removed extra weight and the security requirement bypass for the nukeops ruleset, making it *much* less likely to fire

:cl:
* tweak: Castle Station has been demilitarized.

### CODE REVIEW

**Comment by BurntDevil** [comment]
speed merge when

**Comment by Eneocho** [comment]
Downboated because of the nukeops roll nerf, keep the sec bypass at least or it will never roll.

**Comment by gurfan** [comment]
> Downboated because of the nukeops roll nerf, keep the sec bypass at least or it will never roll.
It can roll if there is a Captain an AI

**Comment by ShiftyRail** [comment]
Castle is a fine map if played once in a while. The guns ruin it by making it skip the most basic escalation steps to always go to murder. This happened before and this will happen again. You may abstract away the map itself or drown the metaphorical fish in the water of details, but these facts are true:

1. Castle is not a map like the others.
2. People do not treat it as a map like any other.
3. It wasn't intended to be a map like any other.

4. Therefore, it should have a special thing that makes it unique - natural escalation in the absence of sec.
5. But Castle has guns. Escalation cannot happen, as if you wrong someone they can just jump straight to murder if they feel like it.

6. People get salty from this state of facts. So either we do the paradoxical thing of pretending a station which isn't like the others follows normal rules - or we do the sensible thing of removing the guns and allowing escalation to happen naturally.

You can't argue with those facts.

**Comment by boy2mantwicethefam** [comment]
Cargonia buff

**Comment by SonixApache** [comment]
removing mapped guns does not remove the guns, it merely ensures the guns are only in the hands of cargo, a few laser musketeers and the occasional vault explorer

people deafulting to murder is a player issue, not a code/map issue

**Comment by BurntDevil** [comment]
Shifty isnt wrong in that by having a shitload a guns and no sec that it gives people the mistaken idea that they are supposed to be used, which causes escalation to be skipped. And since we dont suspend the rules regarding that, it creates an issue.
Nor is Sonix wrong in that this is a player issue. Normally I'd be against removing content like this, because its silly to move content because some people abuse it, but in this case its different.
Castle doesnt play like other maps, and people see a ton of guns so they use the guns. By limiting the access to guns, you give less of the impression that this somehow means you're supposed to use them. I understand the intent of having guns, youre supposed to be able to fend for yourself without sec, and band together to fight ops or revs, but the reality is people abuse them. 
The gun PR should have came with a greeting notice that all rules are in effect still. Additionally, Castle should never have fired outside of curated bus rounds. Since we arent getting rid of Castle's rev unlock mechanic, we have to do something to shape how the map is supposed to play, and the surplus of guns going away does that in part.

My concern remains that cargo and sci having all the guns (mechs for that matter too), is that players will still abuse the weapons without security to check the behavior. The novelty of that will run thin quickly. I dont think getting rid of those will do much beneficial either, because blacksmithing still exists. The notice that all rules are still in effect should be added, or the map shouldnt be loaded outside of curated bus events. Either that, or we actually suspend some of the rules and have a shitty deathmatch map, which I doubt will go over well, but perhaps thats what people want. This would have to be stated in the greeting message as well, clearly, so people understand whats going on and the nature of the map.

So yea, this pr is a good first step but it wont fix the overall issue with Castle entirely. We should discuss how to further fix the issue so the map is less of a ban-magnet.

**Comment by Eneocho** [comment]
Well, you can still rely on the good old ghetto weapons like the blunderbuss, crank laser, boot-in-a-box, spears, etc.

**Comment by Eneocho** [comment]
> We should discuss how to further fix the issue so the map is less of a ban-magnet.

It ain't an issue about the guns. Many rounds in lowpop-turned-highpop we've had guns for A, B, C reasons and they have not been used to go one on one against your fellow spessmen. It's that people feel like the map is a chaotic no-rules map. The simplest way to make the map a non-ban magnet map would be to just lift the "admin protection/regular rules" on castle station. Everyone would expect the chaos and gunk. It already is that way, that would just standardize it (and thus control it, somewhat).

**Comment by SonixApache** [comment]
What could be done is to increase the ratio of less-than-lethals to lethals.
Also, someone should revive the thing that gives everyone the NT-22 pistols. No man unstrapped.

**Comment by BomberBro** [comment]
pandora's box etc etc

**Comment by DeityLink** [comment]
Ain't that like the entire point of castle?

**Comment by ShiftyRail** [comment]
No. The point is that there's no security, not that there are guns available. They were not even part of the design.

**Comment by DeityLink** [comment]
But who will protect the crew from antags if there's no guns and no sec?

**Comment by Kurfursten** [comment]
I would support this if it was separate from the Nuke Ops change. Maybe try closing this and reopening as two separate PRs.

**Comment by Blithering** [comment]
I agree that maybe downgrading everyone's issued conflict resolver to a piddly .22 might help, particularly if you aren't given more ammo after the first lot, it becomes your emergency gat rather than your way of saying hi to the department across the hall.

**Comment by GreatBigFailure** [comment]
Replace them with makeshift weapons or less click die options. Laser muskets, whips, rail guns in engineering, a siege cannon in cargo (also let's them open crates) revialer, syringe gun etc in medical, give the janitor a Chem sprayer, give the clown 2

**Comment by WindowsErrors** [comment]
you know, this has been up a little bit, so I decided to do a bit of light reading, so bear with the length of this because this is a history of castle station

so this whole thing starts when castle was originally added in November 2018 (3 years minus a week - feel long in the tooth?)

https://github.com/vgstation-coders/vgstation13/pull/20847

what changed? you guys used to love it, even gurf and Shifty. I've only been here a couple months so it's not like I've got rosy retrospection or something like that, better look a bit more...

the months went by, castle got added to the rotation in August 2020

https://github.com/vgstation-coders/vgstation13/pull/26774

hold up you're telling me the older iterations of castle didn't even have the gun lockers? they only got added a year ago? they even bumped up the nuke ops spawn chance in celebration of it, I almost feel sad for the people in the past, they don't get to enjoy the guns like we do

https://github.com/vgstation-coders/vgstation13/pull/28116
https://github.com/vgstation-coders/vgstation13/pull/28117

and here comes the Troubles, January 2021, everyone decides that there's an issue with castle all of a sudden

apparently castle was extended, and it's a BUG, so quash it

https://github.com/vgstation-coders/vgstation13/pull/28390

wait no undo we liked extended

https://github.com/vgstation-coders/vgstation13/pull/28391

well now that there are antags on castle and they're here to stay and the whole place is basically banbait station, might as well make everyone an antag now

https://github.com/vgstation-coders/vgstation13/pull/28713

ok you know what guns and antags were a mistake because [3 people got shot and killed by a Kenosha Kid wanna-be](http://ss13.moe/forum/viewtopic.php?f=18&p=33268#p33268), remove them

https://github.com/vgstation-coders/vgstation13/pull/28716

(you know, Shifty, as a side note I once made a petition in around December 2019 for Beestation Sage for traitor to be the only game mode and it got like 35 signatures and I still have the google doc somewhere)

they even wanted to remove cargo, what?

https://github.com/vgstation-coders/vgstation13/pull/28743

we may never know what incited or incites the castle troubles. is it the presence of the guns? the escalation? is it the removal of extended? but eventually the whole castle troubles cooled down for a while until recently, where the discussion is once again reignited by something stupid or whatever it is

anyways that's about it, just wanted to bring in the historical perspective of this intraserver shit fling, don't really have anything else to contribute to this, but as someone a while ago once said, it's always difficult when you need to make 20+ people upset either way

**Comment by SonixApache** [comment]
>what changed? you guys used to love it, even gurf and Shifty. I've only been here a couple months so it's not like I've got rosy retrospection or something like that

people support(ed) it because pranked le epic troll based retard bussin or whatever the modern equivalent buzzword of doing dumb things for fun is
and then the non-antag killcount started rising, admins started sweating, people started dying 4noraisins and those people's schadenfreude turned to schaden

**Comment by DamianX** [comment]
this is so sad

**Comment by WindowsErrors** [comment]
it is

**Pull request closed without merging**
