### PR TITLE
Vox trade ship for Box

### PR DESCRIPTION
**Pull request by Probe1**
[Images](https://github.com/d3athrow/vgstation13/pull/9905#issuecomment-217333805)

**Adds** a Vox Tradeship to Box.  This can be piloted by Vox to the station.
**Adds** Vox Access to avoid hijackings.
**Tweaks** Arrivals Docking to accommodate two ships.
**Tweaks** Vox Outpost Docking to accomodate a ship.
**Fixes** Vox Outpost scrubbers to remove o2 at round start

### CODE REVIEW

**Comment by Probe1** [comment]
After consideration, adding an automated announcement system for the Vox Tradeship would be nice but would not fit well when it does not apply to any other ship.

I still feel this is a good addition but will table it until the tradeships are in for each map.

**Comment by Probe1** [comment]
I'm currently stuck in one place.
1.  Lmao none of the scrubbers at vox outposts are set to remove oxygen because of bad coding.

**Comment by Probe1** [comment]
dreamseeker_2016-05-05_22-31-26
dreamseeker_2016-05-05_22-32-08

**Comment by Probe1** [comment]
Ready to merge.

**Comment by Zth--** [comment]
It's a bit ugly but I like the idea

**Comment by Probe1** [comment]
its definitely supposed to be.  its not high level nanotrasen stuff, its scrap shit thrown together by dirty burds.

**Comment by Brolaire** [comment]
I think a single airlock on the south wall might be a good idea, as a sort of escape route into space instead of getting cornered by cultistwizardlingopscurity. Just my opinion

**Comment by Probe1** [comment]
I put the windows in for that one.  iunno.

**Comment by Konater** [comment]
I guess I should have subtyped everything I used for the deff outpost

**Comment by Probe1** [comment]
depends on how likely it is to be used in two places.

**Comment by Konater** [comment]
I used an outpost prefix for all the names, so the scrubbers, vents, apcs, air alarms and three vendors

**Comment by clusterfack** [comment]
Vox traders are fucking lol

**Pull request merged**
