### PR TITLE
The Ultimate Bartender Power Creep - Episode Two : Flair Bartending

### PR DESCRIPTION
**Pull request by DeityLink**
The long awaited sequel to #21816 !

bottle flipping

NBAYiy

image

https://github.com/vgstation-coders/vgstation13/assets/7573912/37ebbea4-e78c-4bdb-9b46-3b0acb1e3b59

:cl:
* rscadd: Bartenders (and anyone else who obtains the Sober gene) have awakened the cool ability to flip the bottles and flasks they pick up, as well as empty glasses. Simply switch to grab intent to use this perk.

### CODE REVIEW

**Comment by DeityLink** [comment]
Yes detectives can do it too since they start with the gene.
flask flipping

**Comment by Eneocho** [comment]
Can you juggle the shaker?

**Comment by DeityLink** [comment]
as shown in the video.

**Comment by Eneocho** [comment]
Video doesn't load on my end, good to know I guess.

**Comment by DeityLink** [comment]
Martians cannot get the Sober gene but if they could, the code is already in place to support the fancy flipping. (in other words pray for it if I'm online as admin)
martian flipping

**Comment by DeityLink** [comment]
clown flip
clumsy fingers have a chance to let the bottle fall on the floor.

**Comment by Optimism333** [comment]
The only downside of this pr is that now all the other service jobs will feel lame in the bartender's bottle flipping presence.

Great stuff, though!

**Comment by Blithering** [comment]
This opens the door to full blown juggling for the clown later down the line.  I want to have a clown tragically die when his hulk wears off halfway through his anvil juggling routine.

**Comment by DeityLink** [comment]
I can easily add this feature for other items down the line. Some items could be flippable by everyone, others only if they fulfil some requirements, some with a custom animations, some with either a custom sprite or a scaled down version of their default icon.

I'll keep that for another PR so we don't delay the Bartenders their new toy.

**Comment by Theophrastus1** [comment]
this better work for molotovs and IEDs

**Comment by DeityLink** [comment]
it works for molotovs as displayed by the clown above.

**Pull request merged**
