### PR TITLE
Fixes MoMMI namepick

### LINKED ISSUE #14444: Mommi namepick
(WEB REPORT BY: riolenn REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Can't pick a mommi name when you are crated from a pbrain in middle of the round

>What you expected to happen

to be able to pick a name 
>What actually happened
You cannot choose your name any more.

>Steps to reproduce if possible

### LINKED ISSUE #15290: MoMMI's constructed by the roboticist cannot pick their name
I always found it wierd how cyborgs are able to choose their name upon creation (and later alter it once more via reclassification module), while MoMMIs are incapable of doing so unless created automatically at roundstart. 

I can understand having MoMMIs on the derelict be incapable, so as to differentiate from station MoMMIs, however MoMMI's created by the roboticist are also not given the option, despite also being station MoMMIs, heck even cyborgs created by a Malf AI's borging machine can choose their own name (At the AI's discretion).

Does anyone else seem to think this is an issue?

### PR DESCRIPTION
**Pull request by SonixApache**
sood figured out what the issue was
namepick was being called before mobs were in their bodies
fixes #15290, fixes #14444

🆑 
 - bugfix: mommis can now pick their name again

### CODE REVIEW

**Comment by gbasood** [comment]
https://github.com/vgstation-coders/vgstation13/pull/15335/files?diff=split&w=1

So it looks like all that really changed was adding the customname check and `spawn(0)`?

**Comment by SonixApache** [comment]
Correct!

**Comment by SonixApache** [comment]
aaaaaaaaaaaaaaaaaaaaaaa

**Comment by SonixApache** [comment]
WAIT WHAT

**Comment by Exxion** [comment]
That means the code is ordered incorrectly, probably

**Comment by SonixApache** [comment]
no i had 84 files changed all of a sudden
Dunno *why* this is an issue or why it's fixed or what the spawn even does.

**Comment by Exxion** [comment]
I mean the fact that it's fixed by the `spawn()` means the code is ordered incorrectly

**Pull request merged**
