### PR TITLE
changes several dark mode text colors to be readable

### LINKED ISSUE #26784: Purple Text on Dark Mode
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
1f6dd7464da6501fe255ba8459f8ab093b051cef

# Description
On roundstart, Darkmode,  when you declare ready, it's very purple and hard to read.
# Steps to Reproduce
Declare ready with darkmode.
# What you Expected
Readable text.
# What Actually Happened
Purple unintelligable text with black background.

### LINKED ISSUE #26785: Darkmode Adminhelp PM
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
1f6dd7464da6501fe255ba8459f8ab093b051cef

# Description
Admin PMs from a working admin on darkmode are a dark red and can't be seen easily.
# Steps to Reproduce
Recieve a PM from an admin on dark mode.
# What you Expected
Readable Text.
# What Actually Happened
Nigh unreadable text unless selected.

### LINKED ISSUE #26881: dark mode's service and common channel colors are the same
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
38fe8336fa204264c2cc078c964df4e682af1ccb

### LINKED ISSUE #27079: Dark Mode Channel Colours
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
dfe8704726a02c4997f4991d98c6d476c029a6c5

Supply, Service and Common all have the same colours on Dark Mode for me. And as I'm very lazy and don't know how to read it's nearly impossible for me to tell if someone is trying to talk on these radios over common, so most of the time I miss it, because paying attention to every message on common will drive anyone insane so sometimes I filter it out.

### LINKED ISSUE #27651: Darkmode service channel color is the same as common
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
bef81d7aae4331e924bd6e93041e3c10170a8230

# Description
Darkmode service channel color is the same as common
# Steps to Reproduce
1. join as service job
2. use :d prefix
3.observe color
# What you Expected
a slightly darker yellow-y or at least different color
# What Actually Happened
same color as common

### LINKED ISSUE #27658: Colour palette on dark mode problem
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
34b7e27544426513a953120e983ab3f27913f9c5

# Description
Universal Recorder output is a dark red, almost unreadable with the black background.
# Steps to Reproduce
Record and reproduce anything with the universal recorder.
# What you Expected
Readable text.
# What Actually Happened
Eye strain.

### LINKED ISSUE #28126: Dark Mode Color Issue
(WEB REPORT BY: bobobozo REMOTE: 206.221.180.138:7777)
# Revision
30d4e5fce7cc007ee0d22dd7effa129c969ece5a

# Description
The fuckin supply channel is the same color as common. Very confusing. Also service
# Steps to Reproduce
Speak in almost any other channel aside from security or command and I think science
# What you Expected
To see a corrosponding color to that specific department
# What Actually Happened
I just see green

### LINKED ISSUE #28563: AdminPMs are a dark crimson colour in dark mode and are unreadable
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
19d940561159cf69cce516bdc5dd4600289ddcff

# Description
what it says in the tin
# Steps to Reproduce
adminpm someone 
# What you Expected
readable text, perhaps bright red or orange
# What Actually Happened
unreadable text

### LINKED ISSUE #29091: Minor Darkmode complaint about radio color
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
3abb1d9be42594e461b9353ebc952e3c1f3d96b9

# Description
Supply radio and common radio are the same color,or atleast similar enough that I can't tell them apart. Service is similar IIRC
# Steps to Reproduce
use darkmode radio
# What you Expected
orange?brown?
# What Actually Happened
a

### PR DESCRIPTION
**Pull request by robintime**
watch this im about to get 9* closevalids with 5*  lines of code
closes #28126, closes #29091, closes #27651, closes #26881, closes #27079, closes #27658, closes #26785, closes #26784, closes #28563

:cl:
 * tweak: added the service and supply channel to dark mode
 * tweak: makes admin PMs brighter on dark mode (including anything that uses .maroon)
 * tweak: makes anything that uses the .recruit color readable  on dark mode
 * tweak: made some other dark purple color brighter because i felt like it

### CODE REVIEW

**Comment by Eneocho** [comment]
Since you're working on Darkmode code, you could also fix the AdminPMs being a really dark red, which is barely readable against a dark background.

**Comment by robintime** [comment]
these are all the colors on dark mode for admin things, though there are a few missing from darkmode that lightmode has

jjjj

do you know which of these, if any, is the adminPMs color?

**Comment by Optimism333** [comment]
> watch this im about to get 5 closevalids with 2 lines of code
> closes #28126, closes #29091, closes #27651, closes #26881, closes #27079
> 
> 🆑
> 
> * tweak: added the service and supply channel to dark mode

Thank you, sir. No longer will I have to highlight string service.

**Comment by Eneocho** [comment]
> 
> 
> 
> 
> these are all the colors on dark mode for admin things, though there are a few missing from darkmode that lightmode has
> 
> jjjj
> 
> do you know which of these, if any, is the adminPMs color?

AdminPM has a dark purplish red, like wine, none of those match. I actually tried to fix it once, but due to not finding the thing I gave up.

**Comment by Eneocho** [comment]
Should it also close #27913?

**Comment by robintime** [comment]
> AdminPM has a dark purplish red, like wine, none of those match.

i'll find the hexcode for it tomorrow then and see where it shows up



> Should it also close #27913?

i was looking at that one as well, but their issue seems to be moreso that <I>everything</i> is showing up as colorless for them, not just service and supply. basically it's unrelated to this

**Comment by Eneocho** [comment]
> 
> 
> > AdminPM has a dark purplish red, like wine, none of those match.
> 
> i'll find the hexcode for it tomorrow then and see where it shows up

Getting you the hexcode now, actually.

**Comment by Eneocho** [comment]
Seems to be #800000 or near.
image

**Comment by Eneocho** [comment]
These are the ones that match on bright mode:
>
>.sinister				{color: #800080;	font-weight: bold;	font-style: italic;} /* /vg/ */
>.newscaster				{color: #800000;}
>.cult					{color: #800080; font-weight: bold; font-style: italic;}
>.maroon					{color: #800000;}


On that note, those 4 should get a bit brighter to also be readable.

**Comment by robintime** [comment]
looks like .sinister, .cult, and .newscaster all already had different colors on dark mode but .maroon didn't, despite it being the same exact color on bright mode. very cool

**Comment by Eneocho** [comment]
Should it also close #28563, #27658, #26785 and #26784?

**Comment by robintime** [comment]
thanks for pointing those out! probably shouldve gone and checked myself haha BUT they're linked now
(one of those i hadn't actually fixed so i just ... did that too)

**Comment by gurfan** [comment]
cringe darkmode

**Comment by Eneocho** [comment]
> 
> 
> cringe darkmode

Enjoy your eye damage.

**Comment by ShiftyRail** [comment]
Eyelets, the lot of you

**Comment by Eneocho** [comment]
> 
> 
> Eyelets, the lot of you

image

**Pull request merged**
