### PR TITLE
Removes the ability to use items over large distances through cameras

### PR DESCRIPTION
**Pull request by unid15**
You can no longer click on stuff that's too far away from you

Prime offenders were gravity wells, as you could devastate the entire station from complete safety with a gravity well and a camera console / remote view power. Other items that could be abused were photo cameras and subspace tunnelers.

This PR will allow using cameras to take photos through camera computers, but not through the remote view power.

:cl:
 * bugfix: You can no longer use most items or telekinesis through security cameras or remote view.
 * tweak: Polaroids can take photos through security cameras. Subspace tunnelers can be used through both cameras and remote view.

### CODE REVIEW

**Comment by Blithering** [comment]
Does this also prevent the use of telekinesis through cameras?

**Comment by ghost** [comment]
This better not nerf genetics antag, it's the only medbay antag that doesn't involve le tricky pricky juice

**Comment by SonixApache** [comment]
thanks yred

**Comment by ghost** [comment]
>yred

I've seen at least one trader steal LITERALLY everything bolted down through cameras and subspace tunneler and I don't think it was yred

**Comment by Arthurdentist** [comment]
Photos through cameras / remote view should stay, primarily because its funny. 

Or maybe there could be a sort of psychic camera? would be neat either way. 

(this was brought up in an issue eons ago, the consensus at the time was to leave it, but gravity wells and such things didn't really exist back then either.)

**Comment by Shadowmech88** [comment]
>Other items that can be used with this are cameras and subspace tunnelers.

I'm not sure what you mean by this.
Do you mean subspace tunnelers can still be used through cameras after this change?

**Comment by SonixApache** [comment]
The subspace tunneler is supposed to be the one exception to this, I think.

**Comment by DamianX** [comment]
Yeah but then it would be fun
this cannot be allowed

**Comment by Exxion** [comment]
Photos through cameras should still work, but should give you brain damage
Taking a picture of a screen works, but is disgusting

**Comment by unid15** [comment]
This PR will disable the ability to click on stuff through cameras/remote view, unless it's near your actual mob. So naturally, this removes telekinesis, subspace tunnelers and practically everything else unless it's specifically allowed in the code.

I've allowed polaroids to take photos through cameras, but not through remote view.

**Comment by Shadowmech88** [comment]
>unless it's specifically allowed in the code.

How does one specifically allow it? Because subspace tunnelers are supposed to be allowed.

**Comment by ghost** [comment]
>bug fix

IT'S A FEATURE REEEEE

**Comment by unid15** [comment]
The item's attack_remote(target, user, eye) proc must call afterattack to make the item usable through remoteview/cameras.

Allowed subspace tunnelers

**Comment by unid15** [comment]
No longer DNM, by the way

**Pull request merged**
