### PR TITLE
P-ray scanners now cost 10x the materials

### LINKED ISSUE #16902: P-ray scanner is the exact same price as a T-ray scanner
It's way way better so it should cost way more

### PR DESCRIPTION
**Pull request by DamianX**
Fixes #16902

:cl:
 * tweak: P-ray scanners are now 10 times as expensive to build compared to the T-ray scanners.

### CODE REVIEW

**Comment by Sooose** [comment]
This kills the scientist.

**Comment by Boxe** [comment]
that's a bit expensive

**Comment by DrSnips** [comment]
For what reason?

**Comment by DamianX** [comment]
> It's way way better so it should cost way moreà

did you not read the issue?

**Comment by Pathid** [comment]
Presumably it's because they counter invisibility. As far as amount of use goes, their main purpose in the game now is to be scattered around to make a dragnet for invisible people.

**Comment by SonixApache** [comment]
2 and a half sheets of metal, half a sheet of glass. Right?
Doesn't seem that bad.

**Comment by Killette2** [comment]
You wouldn't complain if you saw how astonishingly cheap both were to begin with. It's still very cheap with this change.

**Pull request merged**
