### PR TITLE
Adds medibot voucher to medical safe loot

### PR DESCRIPTION
**Pull request by SonixApache**
image
Adds a medibot voucher to the medical safe loot spawners.
The voucher can be redeemed at a *NanoMed Plus* for a Nanotrasen Advanced Medibot.
The medibot is just a subtype of the mysterious medibot.

🆑 
 - rscadd: Medical safes have a new unique voucher in them.

### CODE REVIEW

**Comment by ghost** [comment]
Not gonna add or change the  chems on the medibot? Just gonna leave it with dexplus, dermaline, anti toxin, and bicaridine?

**Comment by SonixApache** [comment]
Yup.
I'm thinking about making the voucher work on the wall-mounted nanomeds as well, but I'd have to come up with something for those to contain.

**Comment by ghost** [comment]
Well shit, then this voucher'd better be rare

**Comment by SonixApache** [comment]
I have no idea how common *medical safe*s are, but since they contain shit like nanobots and whatnot I'd assume they are.

**Comment by Intigracy** [comment]
Pretty sure they show up in vaults

**Comment by ghost** [comment]
Going off of https://github.com/vgstation-coders/vgstation13/pull/12743 , you get a 75% chance of getting the medical spawner to roll something from its list to add to the safe contents.  That seems in line with my experiences popping the safe as well.

**Comment by Riekland** [comment]
Does the captain even know the combination to the safe?
I think maybe if we add more stuff that's just generally beneficial like this then there might need to be a way to get them in a more legal fashion than Major B&E and theft

**Comment by SonixApache** [comment]
It's supposed to be a rare toy you can get sometimes. Having to bust into the vault and crack the safe is fine.

**Comment by Kurfursten** [comment]
Yes, it is after all not as though this is the only way to get a mysterious medibot.

I think it's a neat little loot idea, more interesting than a bottle of chloral on the list.

**Comment by Intigracy** [comment]
You know what I think?

**Comment by SonixApache** [comment]
yaaaay

**Comment by SonixApache** [comment]
i cracked the safe today and got my own voucher, so that's cool

**Pull request merged**
