### PR TITLE
Labor Console: Noncrew Functions

### PR DESCRIPTION
**Pull request by Kurfursten**
A whole new page for non-crew!

Ever really wanted an AI but no one is willing to volunteer? Now you can request an AI. These silicon volunteers get
* No manifest injection
* No bank account or PDA
* An ID with robotics access only

These new latejoin jobs cannot be selected unless the HOP has increased the limit. They should be impossible to preference or ready up for.
* Some supplies to build their new body (plasteel, circuit, and cables OR arms/legs and metal) **Special thanks to @MadmanMartian for calculating the metal costs**

A priority trader gets a fancy transparent PDA instead of having to buy a shitty vox PDA.

Also includes the commented out remnants of the Convict role I mentioned in the Discord.

TODO: I realize now only in hindsight that these latejoin silicon volunteer jobs appear on your job preferences. That will go away, it won't crowd space there.

borg

🆑 
* rscadd: The labor console can now request traders to arrive and do business.
* rscadd: The labor console can now request volunteers for cyborgification or AIization.

### CODE REVIEW

**Comment by DrSnips** [comment]
Why not just have them start as a silicon? As for AI maybe shipping them in a box like a flatpack and are a radio MMI.

**Comment by Kurfursten** [comment]
I considered that but I also considered it needed to be weighed against

>Roboticist: They're takin' our jobs!

**Comment by DrSnips** [comment]
That aside why do they have incentive items? To MAYBE encourage them to fill their role? I don't feel like that really makes them fill the role however and they can just decide to use it as assistant 0.5.

**Comment by Kurfursten** [comment]
They get the alternate incentive *instead* of a box of goodies that they'd have no use for as a silicon. Borg gets a random upgrade (not including engineering gripper) that might help them decide what module to pick, AI gets a baggie with screwdriver and carrots to upgrade a few cameras.

There's always the threat that any job can be used as assistant 0.5 (mechanics?) but this job has access only to robotics, not even maintenance.

**Comment by Ephx1** [comment]
Why not just have it be an object you add to the core's construction? Intelligence receiver + off posibrain, then an HoP can request one. That way robotics can still build stuff without the need of this weird job.
Oh, and maybe it gets a station wide announcement.

**Comment by Kurfursten** [comment]
That's an interesting approach to it, although it has the problem that it requires the roboticist to basically invest all the resources and time to make an AI upfront without any promise one will appear. With posibrains a roboticist can hold off on making anything til a mind shows up.

**Comment by ShiftyRail** [comment]
Non-round-start silicons should be built by the roboticist.

**Comment by DrSnips** [comment]
I'm just not fond of the idea that they start in a carbon body. It seems counterproductive and unnecessary. Maybe they start as a spider bot? (for the lack of a better silicon place holder)

**Comment by DeityLink** [comment]
I've got a better idea: a machine similar to the Labor Computer in robotics in which you can plug a posibrain and set up a planned role (AI, Borg, Mommi). This way:

* latejoiners see the requested "AI (posibrain)" or "Cyborg (posibrain)" etc job marked as Requested
* upon joining, they immediately jump into the posibrain
* roboticist can then proceed to build their body

Roboticists keep their job, no weird compromise of half-roboticists joining just to build a body for themselves, people can now latejoin as silicon and be one immediately (and not one of those MMI abominations)

**Comment by DrSnips** [comment]
I like that solution a lot better.

**Comment by Kurfursten** [comment]
I also like that idea, although I envision it slightly differently. Instead of a computer with an interface, it's something more like one of your gun rechargers where it floats the posi sprite (actually I could really just crib a lot of that code)

The slots would only appear while at least one unoccupied posi is on the machine. HoP could still prioritize the role for visibility (though I think at that point we can do away with rewards).

**Comment by DrSnips** [comment]
If the HoP enables the role and robotics doesn't have a cube on their side then that does nothing for anyone but annoy spectators since I'd imagine it would say something like "AI posibrain" but crossed out on the join list leading to possible confusion. Just make it robotic side only so we can avoid inconsistency issues.

**Comment by Kurfursten** [comment]
Either you didn't understand or I didn't explain it well.

Control of whether the job appears at all would be based on whether a posi is loaded, but the HoP should still be able to prioritize it by moving it to the top when it is available. It's inconsistency if there's a latejoin job the HoP can't preference.

**Comment by DrSnips** [comment]
Probably me not understanding. I've looked into it a little bit more now based on the first PR. My bad on not knowing too much about the priority system.

**Comment by DeityLink** [comment]
The thing I had in mind was also similar to a gun recharger. Except with an interface that lets you specify what silicon body you're planning to give them. (and possibly which cyborg module).

And also I kinda thought it'd be neat is this was fully separate from the HoP and Labor console, and instead managed by the RD (since it's not about adding actual "Human Resources" but robots to the station). Poor RD badly need some responsibilities.

**Comment by MadmanMartian** [comment]
so, you basically hook the posibrain up to the internet rather than waiting for a soul to manifest from the aether?

I like it.

**Comment by DeityLink** [comment]
That's exactly the idea.

**Comment by Sooose** [comment]
If it was kept in robotics you could even just replace the operating table computer there with it. A surgery monitor when everyone is going to robotics to either be debrained or have a robo limb installed is near pointless. Honestly the surgery monitor is pointless altogether, it could really use some love (like be a pseudo body scanner for whoever is laying on the adjacent table).

**Comment by jknpj** [comment]
You know the drill.

**Pull request closed without merging**
