### PR TITLE
Radio messages no longer show the speaker's ID's assigned job

### LINKED ISSUE #9552: Revert default telecomms due to balance
What I mean by this, is how telecomms by default now states your job title beside your name.

You can easily see where this makes being an imposter over comms very difficult if not impossible as a changeling using the mimic voice ability.

### PR DESCRIPTION
**Pull request by DamianX**
Balance/immulsions vs QoL

Closes #9552

Could be controversial.

### CODE REVIEW

**Comment by jknpj** [comment]
you can still do it with tcomms, can't you

**Comment by Exxion** [comment]
You can, but someone would have to actually do it

**Comment by jknpj** [comment]
Not like we don't have ready-to-use scripts in the wiki

**Comment by Pathid** [comment]
Surely a script doing it isn't any better, immulsions-wise.

**Comment by Kevak** [comment]
-1. Same reason as the other one.

**Comment by jknpj** [comment]
I mean, it's not that bad. At least it's something for AIs/Mechanics to do.

**Comment by DrSnips** [comment]
Down boated because you can no longer see Clown (as captain) at 12:05. As for an actual point why does this need to be changed. The only person who is complaining about it is killette it seems.

**Comment by Kammerjunk** [comment]
Not only can you still do it with tcomms, but this was made a default feature specifically *because* it was done with tcomms every round.

**Comment by Accipitermaris** [comment]
wouldnt mind this if the arrivals announcement computer announcements stood out more, right now they just kinda blend in with the rest of the green goo

**Comment by Allspice** [comment]
if the one certifiably beneficial tcom script was made a default: What does that imply about people entering telecomms now

**Comment by Kammerjunk** [comment]
Well, the existence of one beneficial script doesn't disqualify the existence of others, but from what I've seen, it's usually memes or gimmicks (like dice-rolling or incrementing a personal score from your message). Sabotage seemed to be done from the silicons more than the carbons.

**Comment by Exxion** [comment]
Yeah I'd say that it should either be left as-is or removed from telecomms as well
I'd argue for the former
But doing it this way just makes for yet another thing someone has to do at roundstart, the same way every round

**Comment by SonixApache** [comment]
make tcomms programs save/load onto disks, make the current system into a program that's loaded into tcomms by default

**Comment by Killette2** [comment]
What about the problem where you can see the exact icon of the headset (whether it's a security, cargo, regular headset, wall radio, or station bounced radio) that a person is speaking in? That's just as immulsion breaking and it's not even a telecomms thing to my knowledge. How should you be able to know this information ICly?

**Comment by DamianX** [comment]
hello @Killette2 #18370

**Pull request closed without merging**
