### PR TITLE
Swaps the box gateway and the box abandoned office

### PR DESCRIPTION
**Pull request by Kharkov72**
[box]
Fufills #23234 
Does what it says on the tin, moves the rarely-used gateway to arrivals, and moves the could-be-used-more office over to where it was.
Here's the current version of the new office.
Untitled

And here's an alternate version (Not currently being used, more a mockup for discussion's sake)
Untitled2

Aand here's the gateway
Untitld

:cl:
 * rscadd: Box Gateway and Abandoned Office have swapped!

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Purely for your consideration:
This is the layout I went with before I gave up

dreammaker_2019-06-12_21-43-57

It lacks oomph but I like the elevated gateway

**Comment by Kurfursten** [comment]
I think I actually like the stairs one more.

**Comment by kilozombie** [comment]
The stairs one has a good aesthetic but I really like the version in the OP for looking more like a staging area from Stargate and whatnot.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Unfortunately the fact that the gateway is front-facing top-down makes it tricky to place it in a horizontal room, otherwise it would be ez to aesthetically combine stairs+staging area

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Also, I notice you forgot to move the warning stripes in the hallway. Maybe the office could use some windows too?

**Comment by SonixApache** [comment]
\>even more useless rooms for the recent tumor addition
\>vox traders now have to walk even further from their neutral zone ship to set up a shop
\>no maint door

but why

**Comment by beesil** [comment]
Office needs a maint door but more autism building space always is a :thumbsup: from me.

**Comment by Kharkov72** [comment]
I'm not a huge fan of stairs, but I DO like that suggested layout. Here's my take on it, along with some tweaks to the office, including repiping and a maint door.
Untitled
Untitld

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Looks good
Nitpicks: Gateway room seems to lack a light tube on the left side. While you're at it, maybe you could move the light tube right outside the door so it's not on top of the warning stripes.
Office should also probably have 2 light tubes rather than 4

**Comment by Kharkov72** [comment]
Some lighting tweaks coming in, now with action shots rather than map renders
Untitled
(Yes, that light fixture next to the gateway can be reached, all is well)
Untitld
(That burnt out light is a feature)

**Pull request merged**
