### PR TITLE
New Changeling ability: Bioimmunity

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Start eyeing the people that aren't coughing more closely.
This doesn't actually make the changeling immune to disease, but rather immune to the symptoms of a disease, meaning that you can totally act like some living disease incubator if you want. Eat your heart out Nurgle chaplains (I don't think I've actually seen one in a while though). It's also a toggle so the changeling CAN experience symptoms if they want.
Costs 2 evolution points. I came up with that number because the ability is in all likelihood niche, disease outbreaks are rare and they're often cured, so it's more of an "on-the-moment" "let's not get messed up by the diseases that the crew hasn't dealt with" deal. OR the changeling is the virologist (or wants to spread whatever disease he got from maint mice), in which case it would be cool if he could walk around spreading all that stuff like some sort of fucked up asymptomatic patient zero. Remember that 2 points is 2/3 of the points you get from sucking someone dry in dorms.

Problem 1: I need a sprite for the ability to show up in the HUD. It does show up in the HUD but it's blank.

:cl:
 * rscadd: Added a new Changeling ability: Bioimmunity. For 2 points the changeling gains the ability to no longer be affected by disease symptoms, which can be toggled.

### CODE REVIEW

**Comment by Eneocho** [comment]
>Problem 2: I need a better name than "Immunity to Disease". Something that sounds cool and 'biological'.

A few I came up with:
* The obvious 'Bioimmunity'. 
* Symptostatic Organelles (Cell organelles keep the symptoms in stasis).
* Anti-pathogenic Apoptosis (The infected tissue is constantly undergoing cell death).
* Cellular Wall Hardening (Pathogens can't interact with hardened cells).
* Gene-Tailored Phagocytes (Specialty white cells keep all symptoms at bay).
* Pathogenic Containment Cysts (Infected tissue get stored in little baggies).
Any of these would require a bit of flavour text on ability toggle to explain the return of the symptoms: The organelles stop resisting the infection, the apoptotic cells stop suiciding, the cell wall softens, the phagocytes are commanded to retract or the cysts are popped.

**Comment by BomberBro** [comment]
Should have a threshold of 90 so that a traitor virologist doesn't randomly get 100% shut out by a guy completely immune to his antagonism while also safely avoiding almost all randomly generated diseases.

**Comment by boy2mantwicethefam** [comment]
@Eneocho I'll go for Bioimmunity. It leaves a bit to the imagination.
@BomberBro
1. It's already shockingly easy to become immune to an outbreak by just wearing a space suit and some internals that can last for several hours, the only thing that can actually infect someone at that point is a Meme but it has only 2 stages, and fungal viruses which have a really hampered spread, it can't do much to antagonize. Plasmamen already start off essentially immune to conventional diseases and so do vox for the most part.
2. Virologist antagonist actions are rare. Seriously rare. This is part of why the ability doesn't cost 3 or more points. If the virologist gets away with breaking the machinery after spreading his disease around he'd also need to take a trip to R&D and smash everything to prevent the (very few) competent people from rebuilding the Virology lab using printed circuit boards. Almost nobody does it, let alone with any regularity. I don't think most traitor virologists even bothered to give their diseases some extremely high antigen threshold given that as long as it's above 50-51 it's already essentially in the "safe from anything short of a vaccine" territory (save for nanoflaxicin which nobody makes, seriously I've checked the medbay fridge many rounds and never seen it). Even radium consumption only purges the disease momentarily before it settles back in.
3. Diseases are easy to cure. Someone sits on a bed with some spaceacillin in their system and then their vial of blood gets taken to a spinny thing and in a few seconds (it's exponentially faster the closer it is to 50% and the more it surpasses 50%, which is the limit for spaceacillin antigens) it pops out an antigen that's ready to be duplicated over and over and completely shut down the virus.
4. Wait for #33958 to get merged before we can have both traitors and changelings in the same round, lol
5. Plague-spreading changelings are cool

This is all why I believe that changelings should get away with total disease immunity for as long as it's active, with emphasis on 1. Curing diseases and blocking them is already pretty easy enough which is superior to being immune to the symptoms, and if a virologist has to rely on his disease to do all the fighting then he's not doing a good job given how most diseases aren't immediately harmful and incapacitating, giving the crew plenty of time to retaliate or find a cure. I could add a chemical upkeep of 1 while it's active to compensate but beyond that I seriously do not believe it needs a mechanical change, it's fine as it is.

**Comment by BomberBro** [comment]
_\>I don't think most traitor virologists even bothered to give their diseases some extremely high antigen threshold given that as long as it's above 50-51 it's already essentially in the "safe from anything short of a vaccine" territory_
If a virologist puts in the effort to get it to 100 he should be rewarded then, if they stick to 50 garbage viruses he gets eaten for his trouble. I believe funguses can also ignore most of the immunities for the meme races. 
_\>Diseases are easy to cure._
GREATLY depends on the round, and if a changeling loads himself up on mega anthrax enough where it's an issue it's likely that there's not gonna be a functioning medbay to cure it. Sure, scientists can make their own tube and cure it... but science can already do pretty much anything and shouldn't even be given a thought for balance discussion. Mechs alone mean they don't have to worry about most bad guys. From my experience if there's a traitor/incompetent virologist a cure can take 20-30 minutes to finally roll around. 
_\>Plague-spreading changelings are cool._
Maybe, I also worry it's gonna be a "win more" mechanic where you have no hope of fighting a ling as anyone except a suited bubble boy/mech because any contact contracts you with some mega AIDs that knocks you down without being able to do anything since he already SMASHED and SLAMMED virology making it. This doesn't just shut out traitors either, as far as I remember deity made a special virus for cult which the ling would also be immune to despite being supernatural.

**Comment by boy2mantwicethefam** [comment]
I think there would have to be a different reward system for making viruses that are tougher to cure than changelings getting affected too. After all if that's the only real incentive for a virologist to try to push his virus' power to the max then it's not a good enough incentive (and I believe virus power already correlates somewhat with symptom power but I am not sure of the exact mechanics). I also believe that biosuits completely ignore diseases (even fungal ones, save for memes, which can't do much in the first place) so if it really goes FUBAR the uninfected can don some biosuits, but they're not common.

I only mentioned Science in the context of how a virologist could deal with perpetuating a virus or how the crew can deal with it. It might be a no-balance nightmare land (that is also deeply entangled into the way Mechanics works, so doing away with how designs work is very difficult) but it's still something worth considering because it's a real tool that both groups can use. Personally I very rarely see antagonist virologists taking any real action, and the crew taking so long to deal with a disease stems from the sheer inexperience of dealing with the antagonistic usage of viruses (on top of everyone thinking that "someone else will fix it, not my problem"). A plague changeling deliberately spreading disease could nudge that. It is self-balancing, take Blink wizards for an example, the crew simply moved to using "one-hit-kill" weapons such as shotguns and syringe guns to deal with them (or trapping tiles with IED bear traps, I don't remember if that works), stealthy antagonists looked into EMPs and craftier alternatives to deal with and around the SPS, maintenance tunnels filled with light floor tiles in response to grues, SMES shutdowns against pulse demons. If pressured enough the players will simply adapt, and there's almost zero "disease pressure" as it is, in most rounds people take a detour to medbay, grab the 5u vaccine pill and leave.

The changeling itself can be a virologist too, which would be extra good for an antagonist virologist looking to spread their own diseases using themselves rather than smashed petri dishes and spilled blood, a virologist who wants to be immune to their own symptoms has no choice but to cure themselves of the disease completely.

Your worries are justified but diseases take some time to advance in stages (a minimum of 200 seconds per stage, up to 800 seconds to reach stage 4, plus a varying probability per threshold to actually advance to the next stage), a non-viro changeling can't just barge into Virology and start cooking a plague to make Nurgle proud right away because it takes a significant amount of time, especially finding viruses or mutating them until the desired symptoms are found and extracted. If there is already a virologist there then the power and its gimmick gave them a reason to visit Virology and interact with the virologist there. Who knows, maybe it will lead to some cooperation.

After all these changeling PRs I am going to take a break from updating the changeling to see how they play out and what the consensus is after they've been given all these nice changes. After all the only real way to know how it would play out is if it's in the game.

**Comment by DeityLink** [comment]
> deity made a special virus for cult which the ling would also be immune to despite being supernatural.

@BomberBro I only wrote a quick concept for it but it's gurfan who implemented it.

**Pull request merged**
