### PR TITLE
Mushroom-men can now be janitors and botanists

### PR DESCRIPTION
**Pull request by Servalfang**
Some of our fungal friends from the shoal have decided to take up an honest job. Good for them!

## What this does
Allows Janitor and Botanist mushmen

## Why it's good
Lets us see a bit more of a rare species in a believable way

## Changelog
:cl:
 * rscadd: Some fungal members of the shoal have decided to take up an honest living on-station.

### CODE REVIEW

**Comment by Kromkar** [comment]
Why not?

**Comment by Eneocho** [comment]
Could you add some special interactions with the plants or with cleaning? Such as a diona liver like interaction with plants/trays (like extruding a special fluid that increases plant growth/maturation speeds), or the ability to clean surfaces by walking barefoot (like how they can eat by walking on top of food), consuming whatever was in that tile, meaning if they clean that way they can get poisoned from welderfuel, fed from food crumbs, get infected from floor mucus/blood, etc.

**Comment by Servalfang** [comment]
> Could you add some special interactions with the plants or with cleaning? Such as a diona liver like interaction with plants/trays (like extruding a special fluid that increases plant growth/maturation speeds), or the ability to clean surfaces by walking barefoot (like how they can eat by walking on top of food), consuming whatever was in that tile, meaning if they clean that way they can get poisoned from welderfuel, fed from food crumbs, get infected from floor mucus/blood, etc.

Beyond the scope of this PR, the capabilities of my skill, and also not something I desire to do
I could consider coding some special interaction where they use clippers on themselves to get the seeds that grow into them.

**Comment by Eneocho** [comment]
Ye that sounds good, though I wish those other ideas get implemented eventually, since a janishroom cleaning by walking thus saving on cleaning utensils sounds like a very NT thing to do.

**Comment by ManopolisJones** [comment]
I don't like mushmen and I especially don't want to see them on the station as normal employees, but i'll at least say this, if they can be jannys and botonist, you'd figure they could also be assistants. I mean, I figure you chose janitor and botonist as it would be easier to convince people to add this once trader exclusive species to the station, then some time later grant them all the station roles barring heads of staff. However, assistant being the lowest common denominator job a space man can get, you'd figure it would also be included for the shroomers.

**Comment by Servalfang** [comment]
> I don't like mushmen and I especially don't want to see them on the station as normal employees, but i'll at least say this, if they can be jannys and botonist, you'd figure they could also be assistants. I mean, I figure you chose janitor and botonist as it would be easier to convince people to add this once trader exclusive species to the station, then some time later grant them all the station roles barring heads of staff. However, assistant being the lowest common denominator job a space man can get, you'd figure it would also be included for the shroomers.

If they wear grey, they're gay. Also, no, this isn't mushroomcreep. I would downthumb a PR that enables them access to most jobs.

**Comment by BurntDevil** [comment]
I dont mind this as long as it stays jannie and botany, but we all know by the end of the year we're gonna see Warden Shrooms on the arrival shuttle. Which is what is going to happen immediately anyway - they will beeline straight to the HoP unless this becomes mechanically enforced. 

So I expect people to be taking these roles expressly for job transfers, eating slots for people who actually want to play those roles and wasting them. Unless you code some sort of mechanic to job lock them, the entire purpose of this job requirement is moot.

**Comment by Eneocho** [comment]
I mean, same thing can happen internally with any species locked class. A plasmeme can be ascended to captain despite being prohibited from starting as one, a tradershroom can say fuck it and become a stationside engineer. Implementing a job lock goes against the point of having a head of personnel, and the HoP can free the janitor/botanist slot if need be.

**Comment by BurntDevil** [comment]
The HoP can just hire trader shrooms using current mechanics, so why even bother with the pr?

**Comment by wotisjanitor** [comment]
> The HoP can just hire trader shrooms using current mechanics, so why even bother with the pr?

You upvoted it anyway

**Comment by Servalfang** [comment]
> The HoP can just hire trader shrooms using current mechanics, so why even bother with the pr?

Well, for one, you actually CAN'T unlock more slots for trader,
For two, nobody is going to pick trader and immediately march to the HOP and ask for a job, and
three, if they did do that, they would get told to fuck off retard

**Comment by tinysaturn** [comment]
looking forward to playing pranks on the fun guys by leaving deathnettles on the floor

**Comment by Kammerjunk** [comment]
first they came with non-antag vox, and I didn't speak up...

**Comment by pedr69** [comment]
>make infinite burnt messes
>leave them all over the floor
>stupid fucking mushrooms walk over and absorb the floorgunk

fund it

**Comment by Eneocho** [comment]
> > make infinite burnt messes
> > leave them all over the floor
> > stupid fucking mushrooms walk over and absorb the floorgunk
> 
> fund it

There was this one round I was making "experimental burgers" with rare ingredients, like a frostoil hell ramen burger or diamond carrot burgers. I eventually made some burgers with burnt messes, ZAS pulls them to a regular tile, shroomtrader walks over, "eats" the bunch and collapses from toxins, diamond and hell ramen heating his ass to 1000°C seconds later.
That's as close as we can get to the jannieshroom cleaning spilt blood/radium/mucus/fuel by walking on it until someone actually codes it.

**Comment by SonixApache** [comment]
#30628

**Comment by Servalfang** [comment]
this was like 12/4 2 weeks ago. Mins tryna filibuster me.

**Comment by Eneocho** [comment]
Kurf said in another PR he's in recovery from surgery, and he's one of the main code reviewers here. We have stuff from October and earlier still pending review.

**Comment by Kurfursten** [comment]
Not in favor personally but it has a meaningful majority. Give it a week and someone can open a revert next Sunday if they hate it.

EDIT: I am sure that misclick probably sent someone watching mommi in discord on an emotional rollercoaster.

**Comment by Servalfang** [comment]
i was asleep when it happened lol

**Pull request merged**
