### PR TITLE
lol

### PR DESCRIPTION
**Pull request by bthomas2**
:cl:
 * rscadd: Did stuff!
 * rscdel: did other stuff!

### CODE REVIEW

**Comment by anunknownentity03** [comment]
shit pr

**Comment by bthomas2** [comment]
you would know shit, since you eat so much of it

**Comment by boy2mantwicethefam** [comment]
Where is the maintenance
https://www.youtube.com/watch?v=9McGKrxOnB8

**Comment by toomykins** [comment]
not as bad as my pr's
i vouch

**Comment by anunknownentity03** [comment]
owned

**Pull request closed without merging**
