### PR TITLE
Updates default config MOTD to look more like in-use one

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[tweak][grammar]

## What this does
tries to make its appearance match the main game server's one, with some punctuation and grammar fixes.

## Why it's good
WE'RE NOT BAY!!!

## Changelog
:cl:
 * tweak: The default config MOTD now bears more resemblance to the current server.

### CODE REVIEW

**Comment by adacovsk** [comment]
no soul

**Comment by boy2mantwicethefam** [comment]
- Add a link to /vg/'s rules
- Keep the reminder that it's a roleplaying server that people should stay in-character for

**Comment by SECBATON-GRIFFON** [comment]
> * Add a link to /vg/'s rules
> * Keep the reminder that it's a roleplaying server that people should stay in-character for

this still doesn't show up in the actual game, just localhost servers. maybe that would be worth a reminder.

**Comment by nervere** [comment]
Our MotD sucks and gets updated like once a year. It's certainly not worthy of being the model for the code.

**Comment by pedr69** [comment]
updating the base MOTD sort of defeats the purpose anyway no?
it's supposed to be SO SHIT that no server host would keep the default one

**Comment by Eneocho** [comment]
Requesting for the MOTD to be the WGW copypasta.

**Comment by Kurfursten** [comment]
Lack of support

**Pull request closed without merging**
