### PR TITLE
Moved posibrain recruitment to a recruiter datum

### LINKED ISSUE #13360: Positronic doesn't ping you for signup if prefferences for it are set to No
(WEB REPORT BY: shaska REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
2cc0be67bdd4af02d70434bad8c01233c60f70d7

>General description of the issue
Having posibrain prefferences set to no doesn't offer you to sign up for it when it's activated when your special role prefference for it is set to no.

>What you expected to happen
To recive a link that lets me sign up for the brain, but without it automatically signing me up for it.

>What actually happened
Nothing

>Steps to reproduce if possible
>Observe
>Wait for roboticist to activate the posibrain
>Recieve no sign-up link

### PR DESCRIPTION
**Pull request by Pathid**
Closes #13360 

:cl:
* tweak: Ghosts with their posibrain role preference set to "No" will now get a prompt to opt in when a posibrain is activated. Setting the pref to "Never" will hide the prompts.

### CODE REVIEW

**Comment by AutismSpider** [comment]
will it do this for TG eggborg/ball?

**Comment by Pathid** [comment]
Oh fug I forgot about those.

Edit: Looks like they should work as-is.
To answer your question, yes.

**Comment by Hoshi-chan** [comment]
Wait, shouldn't this _not_ ping people set to 'never'?

**Comment by Pathid** [comment]
Sure. It wasn't clear to me how to do that at the time but I'll get on that. It was more of a priority for pAIs because they're much more spammable.

**Comment by Riekland** [comment]
why would you ever make it ping people who actively changed their preferences to no or never

**Comment by Pathid** [comment]
@Riekland Because, if you have it on yes or always, it will automatically opt you in. If you look at the linked issue, players want an option where you can see the pings without having to retract every ping you don't want to be signed up for. Anyway it's just a chat prompt, not a pop-up window.

**Comment by Riekland** [comment]
So if I'm to understand this correctly it's Always = opts you in with no prompt, Yes = opts you in with a prompt to opt out, No = opts you out with a prompt to opt in, and Never = opt you out with a prompt to opt in

Which sounds great to me but why would you make it so there's no prompt if you set it to never

**Comment by Pathid** [comment]
Always gives you a prompt and it's effectively the same as Yes. Having no prompt would mean no warning at all that you were going to be put in a posibrain. Like I said this is in the chat and not a thing that pops up over your screen.

>but why would you make it so there's no prompt if you set it to never

I figured somebody might not want to see the text, and it sounded like you and Hoshi wanted that functionality but whatever, it doesn't matter to me.

**Comment by jknpj** [comment]
Yes/No only work for a single round and you need to set it manually, this means if you have posibrain to Never you'd miss posibrain prompts, even if you'd ocasionally want to pick it up without always being drafted. This is fine.

**Pull request merged**
