### PR TITLE
Adds Stellar Carpets (from TG).

### PR DESCRIPTION
**Pull request by ghost**
You can get them from cargo. Features a nice six-pronged star with no relation to any religion.

image

Note that the code for carpets and floor tiles in general is insanely fucked but I'm not going to fix the hardcoded if statement problem.

:cl:
 * rscadd: Added stellar carpets to cargo.

### CODE REVIEW

**Comment by west3436** [comment]
shalom

**Comment by SonixApache** [comment]
too bright, shading is different from the normal carpet, meme religion carpet
👎

**Comment by Eneocho** [comment]
neon bright that doesn't match the aesthetic nor the feel of all other carpets

**Comment by west3436** [comment]
We don't have an "aesthetic", stop that. He's not mapping these in anywhere; if you don't like em don't build them or rip them up with a crowbar in protest.

**Comment by SonixApache** [comment]
@west3436 we absolutely do have an aesthetic, you dweeb, use your eyes

**Comment by Theophrastus1** [comment]
replacing schlomo's office with these every round

**Comment by falcon2346** [comment]
I don't necessarily hate it enough for a thumb down but it looks odd. Specifically it doesn't really look like a carpet, I see it and think painted metal because there's just 0 texture to it. Needs a bit of noise I think.

**Comment by bathosbathtime** [comment]
Dunno about it fitting the art style or not but I think it is ugly.

**Comment by zakanater19** [comment]
JEWS

**Comment by Eneocho** [comment]
> We don't have an "aesthetic", stop that. 

we absolutely do, we're the old spess aesthetic, we (/vg/) have had this discussion hundreds of times at this point, [kurf even recalling that exxion had made the same point](https://github.com/vgstation-coders/vgstation13/pull/32567#issuecomment-1126867311) like 5 years prior (godspeed kurf). this doesn't match with any carpet, it feels too neon-y eyerape (privilege of the clowns and artists) and is lacking murkiness, or depth, as falcon said
also the stars are 1 pixel off-center on both the X and Y axis and it bothers me, it feels like a low effort sprite
if the brighness is toned down a bit and some more detail added I'd remove my 👎🏻, something like this:
altstartile
image

**Comment by falcon2346** [comment]
> > We don't have an "aesthetic", stop that.
> 
> we absolutely do, we're the old spess aesthetic, we (/vg/) have had this discussion hundreds of times at this point, [kurf even recalling that exxion had made the same point](https://github.com/vgstation-coders/vgstation13/pull/32567#issuecomment-1126867311) like 5 years prior (godspeed kurf). this doesn't match with any carpet, it feels too neon-y eyerape (privilege of the clowns and artists) and is lacking murkiness, or depth, as falcon said also the stars are 1 pixel off-center on both the X and Y axis and it bothers me, it feels like a low effort sprite if the brighness is toned down a bit and some more detail added I'd remove my 👎🏻, something like this: altstartile image

Honestly I'm still not even a big fan of this though it does look a whole lot better. I feel like the fringes are just way too big.

**Comment by MercuriusGH** [comment]
the edge parts are way too thick
the sprites could use some modifications to fit in with the normal carpet

**Comment by ghost** [comment]
It appears my low effort PR to add a carpet purely because it had a jewish star on it is very controversial.

**Comment by SonixApache** [comment]
> It appears my low effort PR to add a carpet purely because it had a jewish star on it is very controversial.

make it gooder

**Comment by ghost** [comment]
This is all the effort I'll be putting in unless someone wants to edit the carpet sprite.

**Comment by hacker-on-steroids** [comment]
you could try asking [No.](https://arch.b4k.co/vg/thread/473034205/#473515608)[473515608](https://arch.b4k.co/vg/thread/473034205/#q473515608) for a full spoonfeed if you don't want to edit the directional sprites

**Comment by west3436** [comment]
I am innocent of the blood of this just PR. The emojitocracy shall see to it.

**Comment by hacker-on-steroids** [comment]
look i'm not saying it didn't happen but six trillion downvotes?

**Pull request closed without merging**
