### PR TITLE
Re-adds holodudes

### PR DESCRIPTION
**Pull request by unid15**
It's 2018 people

disabled by default, admins can enable it

:cl:
 * tweak: Admins may now enable advanced hologram spawning in the holodeck

### CODE REVIEW

**Comment by Pathid** [comment]
Hey you know, the Shutdown System option on the console is still commented out. Was that intentional or...?

**Comment by unid15** [comment]
It's got nothing to do with holodudes so I won't touch it

**Comment by Pathid** [comment]
My mistake. For some reason I thought it was for holopeople.

**Comment by Blithering** [comment]
can they still do non-holo damage?

**Comment by unid15** [comment]
i believe they can, but then again there can't be holodudes in a round unless an admin explicitly enables them

**Comment by Pathid** [comment]
I think the most they get to that effect is the message, "Do not damage the holodeck. Do not harm crew members without their consent."

**Comment by jknpj** [comment]
Let's see how this goes

**Pull request merged**
