### PR TITLE
Revert "Fixes #10005"

### LINKED ISSUE #10005: Project Mind can be used to metagame someone's real identity
If someone masks their identity by any means, such as using someone else's ID and a mask, an agent ID, whatever have you, things get tricky and meta-ey.
Their FAKE name is displayed in the list of people you can project mind to (i.e. "Don Newman"). Up until you send the message, they are always displayed using their FAKE name.
dreamseeker_2016-05-10_16-44-47

However, the chatbox message you get afterwards uses their REAL name.
dreamseeker_2016-05-10_16-45-34

Someone using a voice changer to impersonate someone else? Let me whip out my project mind real quick so I can instantly confirm there are 2 identical names on the list. Sure there are, let me call them a faggot real quick. Oh that's who they really are.

### PR DESCRIPTION
**Pull request by d3athrow**
Reverts d3athrow/vgstation13#10644

### CODE REVIEW

**Comment by TheFriggenSawbones** [comment]
hi pomf

**Comment by d3athrow** [comment]
hi

**Comment by Imagebard** [comment]
>Forcibly merged a PR that didn't pass TRAVIS

I want the star wars character to go.

**Comment by clusterfack** [comment]
It's not that it didn't pass travis, travis doesn't finish when you merge before all checks pass

**Pull request merged**
