### PR TITLE
Raiders fixes

### PR DESCRIPTION
**Pull request by MadmanMartian**
- Fixes typo (Hesit -> Heist)
 - Vox spawning landmark function now mimics other landmark function
 - Raider equipping and moving moved from faction to role
 - Raider equipping functions moved to misc-gamemode-procs
 - Raider shuttle made into a dungeon, loaded when the faction is made.
 - Raiders now choose their own loadout, from a vending machine located within the vox raider shuttle

### CODE REVIEW

**Comment by Kurfursten** [comment]
If this gets merged with mapping priority, the only thing I need to fix on my end to resolve conflicts is to delete the raider shuttle, right?

**Comment by MadmanMartian** [comment]
yup

**Comment by ghost** [comment]
does this fix the ruleset only selecting one player even when there's multiple eligible candidates?

**Comment by MadmanMartian** [comment]
Potentially, but that's hard to tell when I've only got myself to test with

**Comment by ShiftyRail** [comment]
Most of those things related to loadout(s) were already fixed by outfit datums :/

**Comment by MadmanMartian** [comment]
Well, this gives raiders the chance to choose their own loadout

**Comment by ShiftyRail** [comment]
Outfit would do the same thing, but I can probably combine both of them. Even make it a fancy new screen alarm.

**Pull request merged**
