### PR TITLE
Weighted voting with a threshold

### PR DESCRIPTION
**Pull request by Pathid**
An attempt to address #18537

This makes it so choices with less than 15% of the vote are discarded. Would appreciate help making the threshold configurable or something other than just a var.

### CODE REVIEW

**Comment by Mothblocks** [comment]
what does this do in the edge case nobody votes

**Comment by Pathid** [comment]
Nothing different from what it does now. What exactly, I'm not sure of since it's not handled in this file. I believe it just reloads the same map.

**Comment by SonixApache** [comment]
when

**Comment by Allspice** [comment]
why not do weighted shit if there's no map with a majority vote

**Comment by MusgardTiger** [comment]
Good change tbh.

**Comment by vampirebat74** [comment]
yes, YES!

**Pull request merged**
