### PR TITLE
Fixes Autolathe not eating reinforced glass or reinforced plasma glass

### LINKED ISSUE #5042: Autolathe can't eat reinforced glass anymore
this is extremely important as it allows me to easily accrue metal and glass to feed the derelict autolathe by bullying derelict mommis and tearing up the reinforced glass from their solars

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #5042, but is affected by #7099

### CODE REVIEW

**Comment by Kurfursten** [comment]
If you had named or described this PR better I wouldn't have spent time rewriting a solution, PLEASE name and describe PRs

EDIT: Nevermind, it seems like you didn't fix it. I have a solution, then.

**Comment by 9600bauds** [comment]
???
The name is pretty descriptive, what else could I have added?

**Comment by Kurfursten** [comment]
It was my mistake, I thought you fixed #7099

**Comment by 9600bauds** [comment]
Oh, aite then, have fun fixing that one

**Pull request merged**
