### PR TITLE
Adds eclairs

### PR DESCRIPTION
**Pull request by ShiggyPiggy**
https://i.imgur.com/yieIWuC.png
Recipe: 5 Flour, 5 Cream, a chocolate bar.
POSSIBLY MORE ECLAIR FUNCTIONALITY LIKE CUSTOM CREAM TYPES IF I BECOME A
NON-MEME CODER.

### CODE REVIEW

**Comment by gbasood** [comment]
>non-meme coder

that's a meme if I ever saw one

**Comment by Iamgoofball** [comment]
you can bake my eclair~

**Comment by Boxe** [comment]
wiki best be updated if this gets merged

**Comment by ShiggyPiggy** [comment]
@Boxe yup, if it does. And for the initial "what do" the recipe is in the changelog.

**Comment by ihadtoregisterforthis** [comment]
April fools never ends, does it?

**Comment by Blithering** [comment]
@ShiggyPiggy I know this already got merged, but http://s000.tinyupload.com/index.php?file_id=47464292607601035443 for a less massive icon.

**Pull request merged**
