### PR TITLE
Fixes botany with a less-than-100% chance of also breaking other things

### LINKED ISSUE #25937: Botany is kinda broken
(WEB REPORT BY: luzzgawr REMOTE: 206.221.180.138:7777)
# Revision
26cf227e3ccd1c41f1bdff3879c5f38eb3802739

# Description
Several rounds have been spent splicing and purging potency and different properties into plants, only to find that it does absolutely nothing. Trying to purg condense capascin into chilis from ghost chilis, for example, will result in the normal capascin. Ive also seen other botany peeps talk about this issue, that potency isnt increasing the chems in certain plants they are making
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by Exxion**
Dude I fucking hate BYOND and oldcoders
Fixes #25937

### CODE REVIEW

**Comment by ShiftyRail** [comment]
I told you this would happen!

**Comment by Exxion** [comment]
Now the code is more robust
Or it should be but I don't trust BYOND with adding parameters to `New()` because of its named arg bullshit

**Comment by FoggyDayWindyCay** [comment]
Potency is still broken, you can get a plant as high potency as you want but when you harvest it the harvested plant has baseline potency.

**Comment by FoggyDayWindyCay** [comment]
Also potted plants might be broken too, I tried putting moonflowers in pots and while they did transplant the plants themselves don't appear in the pot.

**Comment by Exxion** [comment]
Can't reproduce the potency part. Works fine for me. What plant did you find the issue with?

**Pull request merged**
