### PR TITLE
TEG nerfs.

### PR DESCRIPTION
**Pull request by PJB3005**
Makes it so the TEG needs to be making thermal power for more than 5 ticks straight before power will actually be outputted. This prevents people from just slapping a couple canisters in and being able to run the station with a TEG that's jammed every other tick.

Also divides the thermal power output by 4.

**Note:** I have no tested this.

### CODE REVIEW

**Comment by Imagebard** [comment]
>**Note:** I have no tested this.

Oh here we go

**Comment by ghost** [comment]
> 5 ticks straight

That won't work with how the TEG works. It produces power for a few ticks, then because atmos processing, doesn't for a few ticks. It's inconsistent

**Comment by PJB3005** [comment]
Skullyton that's caused by shit setups. 

I'll test it tomorrow, I made the code on my slow Linux laptop so I couldn't test it.

**Comment by 9600bauds** [comment]
Ideally you would add some sort of warning that the thing is jamming

**Comment by PJB3005** [comment]
Alright good idea I'll add that to the UI.

**Comment by PJB3005** [comment]
Alright good to go.

**Pull request merged**
