### PR TITLE
adds 2 secways to the maps

### PR DESCRIPTION
**Pull request by Intigracy**
box / deff / meta respectively, white selection rectangle identifies where they are since it's a bit hard to see from the map editor

secwaybox

secwaydeff

secwaymeta

### CODE REVIEW

**Comment by SkowronX** [comment]
Goodness we are becoming more like goon aren't we.

**Comment by kol1th** [comment]
thanks inti :+1:

**Comment by clusterfack** [comment]
You guys always put everything on the map, this is why we never end up getting content that could be used for ECONOMY or such

**Comment by ComicIronic** [comment]
What cluster said, make a secway crate instead. We need less map content and more interaction incentives.

**Comment by Shadowmech88** [comment]
Besides, having two at roundstart will lead to officers being at each others' throats over who gets them.
Making them a crate is better because then it's up to the individual officer as to whether or not he wants to buy one.

**Comment by kol1th** [comment]
Having them be a crate wouldn't be, "sec has to order them to get them", it would be "AI ORDER 25 SECWAYS LAW 2" or cargo ordering a shit ton, and then everyone has one.

**Comment by ComicIronic** [comment]
You could make them expensive. 2 is already a small number for the department, have Officer Shitter get a summer job for his first car.

**Comment by Shadowmech88** [comment]
Cargo would still have to blow them open if they were access-restricted.

Though it would bring up a new issue; if they were orderable from Cargo in any fashion, they would be the first _renewable_ source of vehicles for the station, ever.

**Comment by FudgePucker** [comment]
Did someone say the magic words to summon me?

> MUH INTERACTION

OH BOY, NOW CARGO GETS SECWAYS AND SECURITY WILL NEVER USE THEM.
BUT AT LEAST WE CAN THINK THAT SOME FUCKING INTERACTION BETWEEN PLAYERS BESIDES VALIDS IS GOING ON.

**Comment by PJB3005** [comment]
```
<Comic> Hey Clusterfack
<Comic> Close [11073] and get them to make it a crate
```

**Comment by FudgePucker** [comment]
OH GREAT, NOW CARGO GETS JANICARTS, AND SECURITY DOESNT GET SHIT

**Pull request closed without merging**
