### PR TITLE
Removes warning from hydro scan code

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[cleanup]

### CODE REVIEW

**Comment by SonixApache** [comment]
so what does this do

**Comment by Eneocho** [comment]
> so what does this do

I apparently fucked up and copied the same line (from my test shit) twice on two different places while updating the plant analyzer, causing issues. This fixes that. It's a back-end fix not visible change to the player so it has no changelog.
Thanks for noticing it and fixing it, kanef.

**Comment by SonixApache** [comment]
@Eneocho 
yeah but where does the 'warning' kick in, especially if it's not front-end?
are you saying you made a PR that caused a warning to print in the console every time you compiled?

**Comment by Eneocho** [comment]
No, on my local testside it didn't warn at all, it was when copypasting the thing from my local copy of the game to the browser code editor that I fucked up and pasted the thing wrong, so the original copy of the check was still in it's original place and the new place I had moved it to, thus causing the warning.
I should've noticed, but the PR checks didn't spit out anything wrong, so I didn't. The warning probably appears on the logs, and kanef noticed.

**Comment by Eneocho** [comment]
Closing since the same issue got fixed by #36294.

**Pull request closed without merging**
