### PR TITLE
adds leather aprons to anvil crates.

### PR DESCRIPTION
**Pull request by RealestEstate**
Anvil crates will now contain 1 leather apron each.
it has very minimal melee protection (10)
20 laser protection and 800 degrees of temperature protection.

:cl:
* Anvil crates now contain a complimentary leather apron.

### CODE REVIEW

**Comment by RealestEstate** [comment]
https://cdn.discordapp.com/attachments/245876940274139166/514642375184875520/unknown.png

**Comment by Durgen** [comment]
how useful would that be in a mild plasma fire

**Comment by Dacendeth** [comment]
@Durgen I asked someone a similar question and they told me a firesuit is 30,000 protection so the 800 this gives isnt very much.

**Comment by RealestEstate** [comment]
correct. most armors are around 600 including leather armor iirc, so this is just 200 over this. some gloves and shoes apparently offer 1500

**Pull request merged**
