### PR TITLE
Christmas Cake

### PR DESCRIPTION
**Pull request by Shadowmech88**
Changes fruitcake sprite to be an actual fruitcake.
fruitcake_display fruitcakeslice_display
Adds Christmas cake, using what was previously the fruitcake sprite. Christmas cakes can be baked by microwaving a fruitcake with 10 sugar and two eggs (to make the icing). Christmas cakes have 10 more nutriment than fruitcakes.

Also, microwaving a gingerbread man cookie with a grey slime core now spawns a living gingerbread man.

### CODE REVIEW

**Comment by Probe1** [comment]
If you feel up to it add butchering for gingerbread men to produce ..gingerbread men

**Comment by Shadowmech88** [comment]
<strike>How many gingerbread men should each gingerbread man produce when butchered?</strike>
Actually, I'll just replace their `meat_type`.

**Review by Probe1 — APPROVED** [review]
I don't see any errors.

**Comment by Shadowmech88** [comment]
@Probe1 
Done.

**Comment by Probe1** [comment]
Update the wiki please.

**Pull request merged**
