### PR TITLE
Ports Bay's typing indicators

### PR DESCRIPTION
**Pull request by ShiftyRail**
It's a small bubble which shows up above your head when you're talking. I initially wanted to make it only show to other people with the preference, but this is a fair bit of overhead and shitcode for a minor gain, so I'm just going to make those opt-in.

As far as I am aware, there is no way to code something equivalent for non-hotkey mode users.

Tested.

:cl:
- rscadd: Added an option which let you show a small speech bubble when you are typing a message using hotkey mode.

### CODE REVIEW

**Comment by RaccoonBro** [comment]
Doesn't Goon have bubbles for non-hotkey users or am I going crazy?

**Comment by tuypo1** [comment]
Neat
Probably going to lead to more typebaiting but I would say not having to stop in the hall to see if somebody wants to talk to me is worth it

**Comment by ShiftyRail** [comment]
I have one very simple solution
tell typebaiters they're gay

**Comment by tuypo1** [comment]
Sounds like a good plan

**Comment by Killette2** [comment]
I doubt it but would this be possible for people typing in the command bar at the bottom either? Having a type window appear in my face felt terrible when I played

**Comment by ShiftyRail** [comment]
I can think of a way to do it, but it's terrible shitcode.

**Pull request merged**
