### PR TITLE
Fixes excavation suit storages spawning with survivor suits.

### PR DESCRIPTION
**Pull request by Gringonius**
I have no idea how this started happening all of a sudden.
[bugfix]

:cl:
 * bugfix: Fixes excavation suit storages spawning with survivor suits.

### CODE REVIEW

**Comment by Irradiation** [comment]
Might want to delet that commit where you fiddle with RAMsay

**Comment by Gringonius** [comment]
How the fuck did that carry over? I need to figure out how for a moment.

**Comment by Irradiation** [comment]
You probably changed branches or something and did a ADD ALL. Or if you used SmartGIT, you've been memed by SmartGIt.

**Comment by Gringonius** [comment]
hol up

**Pull request closed without merging**
