### PR TITLE
Chameleon clothes can no longer turn into clothing items that have no icons, fixes washing machines

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
:cl:
 * bugfix: Chameleon clothes (the jumpsuit and no-slip shoes) can no longer turn into clothing items that have no icons.
 * bugfix: Assistant jumpsuits will no longer turn into invisible clothes when re-colored into a washing machine with a stamp. This was due to a bug caused by the assistant jumpsuit having its own icon file compared to other jumpsuits.

### CODE REVIEW

**Comment by Eneocho** [comment]
soulless

**Comment by Exxion** [comment]
Consider using `existing_typesof()`

**Comment by dinnerwoerror** [comment]
i should mention that putting a grey jumpsuit and a head of staff's stamp into the washing machine gets you the head of staff jumpsuit except it doesn't have the icon so will it also prevent switching to those

**Comment by boy2mantwicethefam** [comment]
The head of staff jumpsuits are normal, but it sounds like the washing machine is broken. Will fix.

**Comment by boy2mantwicethefam** [comment]
The problem appears to be the fact that assistant jumpsuits have their own icon file (icons/obj/clothing/assistant.dmi) compared to every other jumpsuit that uses a shared file. I have fixed this by making the colored suit also inherit the icon file of the jumpsuit it's trying to replicate. I've done the same for every other clothing object in the washing machine just to make sure.

**Pull request merged**
