### PR TITLE
Roidstation: New AI Core/Upload, Telecomms, and Auxiliary Engineering

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[roid]

## What this does
Renovates the Roidstation's AI Core, Upload, and Telecomms by shuffling them around. This will make the AI Upload and Core more secure - the AI is, however, extremely vulnerable to being shard bombed.

Auxiliary Engineering has also been re-arranged to make the TEG more accessible.

New Images:

RoidAICoreRedo5

RoidAuxEngineeringRedo

## Changelog
:cl:
 * rscadd: Roidstation: Now has a new AI Core, Upload, and re-arranged TEG Engine.
 * bugfix: Fixed a lot of missing wires.

### CODE REVIEW

**Comment by d3athrow** [comment]
minus 1.6 million lines

**Comment by TheEliminator16** [comment]
Merge this immediately
Defile yourself and face to deletion

**Comment by Hinaichigo** [comment]
There's something so nice about the idea of the AI being liquid cooled via crab cave water. For that reason I must vote no.

**Comment by Hinaichigo** [comment]
Also telecomms is hardly a place where much ever happens, compared to the AI core being a hot spot where people try to break in and out of quite often. It seems like a downgrade both aesthetically and gameplay-wise in terms of the map flow to do this. Reducing the possible angles-of-access, and necessitating hardsuits to go through space, or shardbombing, which is kind of a one-trick pony's one-trick, is kind of reducing variety of situations that can happen with the AI on the map. And also I think it's generally more fun to struggle over controlling the AI's laws than destroying the AI outright.

**Comment by wotisjanitor** [comment]
absolutely not

**Comment by Eneocho** [comment]
What Hinaichigo says plus the fact that you moved the assorted engineering machinery further back (where the TEG would've been previously) and in a weird order, which makes getting them a hassle. So a no from me.

**Comment by Eneocho** [comment]
There's also the thing that if stuff got to the point where sharting the AI is an accepted idea, people won't care about the hole in the middle of the station (nobody really uses the crab cave).

**Comment by GeneralVeers25** [comment]
I can easily re-arrange the stuff in storage if you'd like.

**Comment by Eneocho** [comment]
My main issue with this change is the AI core being relocated to Tcomms, not the TEG stuff, though the tweak is appreciated.

**Comment by DorainGrey** [comment]
The storage change is good from an engineering perspective, it makes piping plasma to the TEG substantially easier. TEG's should be next to atmos where possible, our current maps are really bad for not doing this.
Whereas, I can't actually recall a time I've used the engineering storage stuff beyond setting up the abandoned singularity chamber, so it being moved back is a non issue.


As for people complaining about breaking in, the walls are only 1 thick around the back, that more than makes up for having to go into space. It's still substantially easier to break into, than any other AI core on other stations.

**Comment by Hinaichigo** [comment]
Also, it makes more sense to have telecomms on the periphery of the station, (especially on roid where rock might block signals) for signal reception, while the AI is considered a very expensive and mission-critical piece of equipment that must remain secure from the tampering of outside forces. Having the AI chamber one rwall away from space on the edge of the station seems off.

**Comment by SECBATON-GRIFFON** [comment]
no AI pool = sovlless and downboat

**Comment by Kurfursten** [comment]
Due to partial contention, I will leave this for a week

**Comment by d3athrow** [comment]
@Kurfursten teach him how to use the map diff fixer thing

**Comment by Kurfursten** [comment]
@d3athrow We haven't needed to do mapcleaner for some time. In this case, the problem seems to be that he has mistakenly forgotten to encode as tgm, thus causing the massive diff. I will teach him how to do it if he doesn't know, but I am assuming he just messed up his save preferences by accident.

EDIT: Veers confirmed on discord and I gave him guidance

**Comment by Kurfursten** [comment]
~4.5k is large about sounds about right

**Comment by Hinaichigo** [comment]
Can someone please explain "Why it's good" for this?

**Comment by cloutcode** [comment]
no room for triumvirate.

**Comment by Kurfursten** [comment]
He has a point, you didn't place triumvarite spawns

**Comment by pedr69** [comment]
>no room for triumvirate

am i missing something?
image

**Comment by Kurfursten** [comment]
No, you're right, I thought those were the borg spawn markers in the first room. I guess I'm just used to seeing the triumvarite in the same chamber. That's fine.

**Comment by Eneocho** [comment]
Soulless. The death of Roidstation.

**Pull request merged**
