### PR TITLE
Adds anti-tampering to almost all security crates

### PR DESCRIPTION
**Pull request by jknpj**
This is super spicy and i could just make an issue instead but i went ahead and made it a PR anyways.

:cl:
 * rscadd: NT reduces the wage of security officers to make anti-tampering crates viable for almost all security crates.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Where's the fun in ~~collecting cargo valids~~ keeping order if there's no resistance ?
It's like making an electrical maintenance crate shock you.

**Comment by jknpj** [comment]
Since i can't emoji my own PR, my say on this change is that the anti-tampering is too harsh and also needs some kind of warning, but the idea by itself ain't so bad.

**Comment by Exxion** [comment]
You can, but a robot (as well as everyone else) will make fun of you for it

**Comment by Accipitermaris** [comment]
im not against tweaking the finer details of guncargo

but i think a less controversial way would be to tweak the contents of the crates themselves for more fun round progression

[Example: Energy Guns are the end all be all of Blob/Xeno management because you can upgrade them as Advanced Energy Guns. But it's impossible to simply order a large pile of Energy Guns without also wasting space on tonnes of Ablative Vests that you don't want. So you gotta shuffle around a bunch of stuff to make room in your guncrate; you can't just order a pile of Eguns like you can Smart Laser Guns. If this is a deliberate balance choice it seems odd because Ablatives are generally categorized in that high risk item space. Not saying Ablatives should be harder to get, just lamenting that you can't spam Eguns without also spamming the high risk items you don't need.]

**Comment by Durgen** [comment]
the absolute madman

**Comment by Irradiation** [comment]
An absolutely spicy PR if I ever saw one.

Since there's a handful of people on the discord (and possibly the thread and Git) that don't seem to know what the anti-tamper does, here you go:
Upon using a non-standard crate opening way (IE: not using an emag or an ID with valid access), the crate will spew a cloud of smoke containing 12u of Sulphuric Acid, 16u of Condensed CAPSAICIN and 40u of CAPSAICIN. This results in a portion of the crate's content being melted, along with giving a good dose of anti-rioting to the eyes (and mouth) of whoever was close enough to the crate.

Before I start posting my opinion on the topic, I suggest you **don't** put an anti-tamper on the Russian Weapons crate & SpecOps crate. Those crates require the console to be **emagged**, not soldered. In addition, they require _no access_ to open by default and thus don't require an emag to bust them open. Freedom for the cargonian that doesn't want to carry an emag to open that specific crate, along with any other crewmember that got access to cargo and successfully ordered contraband.

**Comment by jknpj** [comment]
Oops, goona fix those

**Comment by Chazach** [comment]
fake and gay

**Comment by SonixApache** [comment]
get out

**Comment by Blithering** [comment]
Give emitters a chance of causing the ammunition to discharge in random directions instead
Heating bullets is a bad idea

**Comment by SonixApache** [comment]
bring back goats

**Comment by AutismSpider** [comment]
only if lock boxes get the same shit too if not fuck off with this booby trap shit.

**Comment by Hoshi-chan** [comment]
I thought the word of the chicken was that he doesn't want crates or lockboxes booby-trapped.

What happened to that?

**Comment by Exxion** [comment]
I believe the word of the chicken was that he didn't want it, but would defer to the players if they did.
The point is moot though because there's no way in hell this change would pass a server poll

**Comment by Kammerjunk** [comment]
I wouldn't call a sacid cloud "a good dose of anti-rioting to the eyes (and mouth)" but I suppose it puts the rioter out.
image

**Comment by Blithering** [comment]
why not just the anti tampering system in abandoned crates that destroys the contents without damaging anything else?

**Comment by DamianX** [comment]
http://ss13.moe/index.php/poll/153

**Pull request closed without merging**
