### PR TITLE
Spider Revolution, Part 2: Midround Ruleset

### LINKED ISSUE #28876: [Feature Request] Playable spider functionality
Spiders have some... interesting AI, to say the least. Hyper obssessing over unreachable objects to the point where you can toolbox them to death is a commonly reported issue, but it's only partially the reason I'm making this. If you're somehow turned into a spider, be it through a wizard's transformation potion, or amorphous mask, you have no way to control or use your abillties. 

here

I made these icons a long while ago, and I'd love to see them get some use. (from left to right, spin web, cocoon object, lay eggs, spit webs, evolve into queen). 

INFO FOR CODERS (For those who don't know how spiders work. This isnt a suggestion, it's how they're currently set up and what would need to be replicated for player funtionality):

-Only green eyed spiders and queens can lay eggs. 
-Only green eyed spiders can evolve into queens
-Using the cocoon spell on a corpse should give a use of lay eggs, otherwise you should not be able to lay eggs
-Only spider queens can spit webs, and though they dont have a spell, player spiders can already use this ability by clicking a distant object
-Living mobs can be cocoon'd and succ'd as well as corpses for means of producing eggs

OPTIONAL TO DOs:

-Make player spiders a possible ghost role / blob storm type event / gamemode / ect.
-Tie player spider existence outside of potions and masks to biohazard alert level.
-Allow Nurses and Queens to heal from feeding from dead mobs

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #28876
image
:cl:
* experiment: Added a brand new midround ruleset, become a spiderling as part of a spider infestation. Terrorize the crew, and above all, break every light you come across!

### CODE REVIEW

**Comment by ghost** [comment]
nice

**Comment by Optimism333** [comment]
A vile force of darkness has arrived.

**Comment by BomberBro** [comment]
It should be currently noted that spiders currently can speak/understand galcomm just fine like cartoon animals

**Comment by Eneocho** [comment]
What a terrible night to have a curse.

**Comment by Eneocho** [comment]
> 
> 
> It should be currently noted that spiders currently can speak/understand galcomm just fine like cartoon animals

What if Spiders spoke insectoid so bugmen can understand em?

**Comment by tinysaturn** [comment]
> 
> 
> It should be currently noted that spiders currently can speak/understand galcomm just fine like cartoon animals

I like this, very unnerving aspect.

**Comment by drawsstuff** [comment]
convenient .ogg for admin use following the merging of this PR

https://files.catbox.moe/4pk7gn.ogg

**Pull request merged**
