### PR TITLE
Nu Ayy Laborer Rig Helm

### PR DESCRIPTION
**Pull request by Optimism333**
## PR Summary ##
The coder sprite hardhat that I did for this rigsuit ages ago never sat right with me. I still felt that the helmet was lacking in identity and detail compared to the other ayy rigsuits. 

Thankfully Blithering was kind enough to give a pass at the helmet, and I think it looks a lot better than before.

### Old Laborer ###
143680758-5101d562-9f2f-4355-805e-af3e3af35cc0

143722686-033ab94d-d8c5-4fa0-b8eb-e862600c2884

### Nu Laborer ###
image

image

## Bonus Welding Shield Toggle ##
The laborer suit helmet can toggle a welding protection shield on and off! This also causes a sprite change on the helmet. It doesn't make the suit stronger in any way, but it adds some interactivity and a style point.

https://github.com/vgstation-coders/vgstation13/assets/81007356/45dd0961-ccae-470f-b3c9-27db6d7a520f

[sprites]  [tweak]

:cl:
 * tweak: Updated the sprites of the grayy laborer helmet (thanks to Blithering)
 * rscadd: The grayy laborer helmet has a unique welding shield visor (toggle)

### CODE REVIEW

**Comment by ManopolisJones** [comment]
rip the big head space construction worker

**Comment by Optimism333** [comment]
Blithering also gave me some sprites for a welding visor toggle, so I will see if I can add it to the helmet.

image

**Comment by Optimism333** [comment]
Thanks to help from Kurfurst and Exxion, I was able to add a bit more interactivity to the laborer pressure suit!

It now has a welding visor toggle that can be used! (Sprites by Blithering)

https://github.com/vgstation-coders/vgstation13/assets/81007356/61ebdf88-dfdf-4bfc-8b6a-a273c0c3fe15

**Comment by wotisjanitor** [comment]
Even better

**Comment by Optimism333** [comment]
Closed and redone in #34813 to avoid icon conflicts.

**Pull request closed without merging**
