### PR TITLE
Improves A* pathfinding with One Weird Trick

### PR DESCRIPTION
**Pull request by Iamgoofball**
Improves A* pathfinding performance, **bots lag less**

# old
687474703a2f2f692e696d6775722e636f6d2f37636d363975442e706e67
# new
687474703a2f2f692e696d6775722e636f6d2f516245547448792e706e67

PS. this file is horrifying please port our A* from here please:

https://raw.githubusercontent.com/tgstation/tgstation/master/code/orphaned_procs/AStar.dm

### CODE REVIEW

**Comment by N3X15** [comment]
FUCK OFF

**Comment by Iamgoofball** [comment]
WE'RE FULL

**Comment by Probe1** [comment]
First for atmos

**Comment by 9600bauds** [comment]
Does this include blackpowder?

**Comment by Probe1** [comment]
Yeah it looks good to me.  Meme title aside

**Comment by Probe1** [comment]
Test Merge

**Pull request merged**
