### PR TITLE
Voting System

### LINKED ISSUE #28633: Admin polls disable round end map vote.
#### Description of issue

What it says in the tin, whenever an admin makes a poll for whatever reason, the map vote is disabled, forcing the current map again since no vote had place.

#### Difference between expected and actual behavior
Expected a round end poll to choose a map despite an admin poll having taken place yet don't get any.

#### Steps to reproduce
Start a round, make a random poll, end the round. There should be no map vote.

#### Length of time in which bug has been known to occur
No idea, but seems to be a long know bug.

[administration] [bug] [qol]

### LINKED ISSUE #30908: Snowbox loaded despite Waystation winning map vote
#### Description of issue
This log:
http://game.ss13.moe/logs/2021/09-September/25-Saturday.log
This vote:
```
[00:50:56]VOTE: <b>Random Weighted Vote Result: Waystation won with 2 votes and a 20% chance of winning.</b><br>	 Box Station had 8 votes and a 80% chance of winning.<br>	 Synergy Station had 0 votes.
[00:50:56]GAME: Players voted and chose.... Waystation!
```

But we didn't get Waystation, we got Snowbox.

#### Server revision

16ead9cc558a05023a1bcaa641d599f990c4f11d

### PR DESCRIPTION
**Pull request by adacovsk**
[system][qol]

The current voting system is very confusing and difficult to use or modify, so I updated it. Admins can now call map votes and vote method through the regular vote verb. Closes #28633, Closes #30908

🆑
- rsadd: Admins can modify voting methods!

### CODE REVIEW

**Comment by SonixApache** [comment]
if there is no front-end change, no :cl: is needed, unless you are expecting issues that need to be reported

**Comment by wotisjanitor** [comment]
ok so you're just creeping your voting that nobody wanted into this one

**Comment by PrimeDSS13** [comment]
now that it's mentioned the fact that persistent voting was snuck into this PR is a bit strange

**Comment by SonixApache** [comment]
not sure how i feel about you implementing #31803 except as admin option instead of always-on

**Comment by adacovsk** [comment]
> not sure how i feel about you implementing #31803 except as admin option instead of always-on

the persistent voting method will not be implemented in this PR. I'm going to try to change the voting system to nani UI now that everything is clear

**Comment by ghost** [comment]
I feel like everybody who thumb'd up this didn't even look at the files changed at all. 
It really seems like you've just tried to find the sneakiest way to add your map-voting style into the code somehow so later you can just try your hardest to get people to accept a PR to enable it because it's "just uncommenting some lines" or something. 
Incredibly disingenuous PR. The fact it hasn't been noticed by a collab and just closed is kinda insane.

**Comment by adacovsk** [comment]
> I feel like everybody who thumb'd up this didn't even look at the files changed at all. It really seems like you've just tried to find the sneakiest way to add your map-voting style into the code somehow so later you can just try your hardest to get people to accept a PR to enable it because it's "just uncommenting some lines" or something. Incredibly disingenuous PR. The fact it hasn't been noticed by a collab and just closed is kinda insane.

was being lazy and I don't see the problem. I'm not really sure why players care so much about backend stuff that isn't even used

**Comment by Kurfursten** [comment]
Given that he split the persistence mode out of this PR, there's nothing controversial about it anymore

**Pull request merged**
