### PR TITLE
Revert "Removes HOGAN lawset"

### PR DESCRIPTION
**Pull request by SonixApache**
Reverts d3athrow/vgstation13#11552

Because even if it is a meme of sorts, bad silicons and bad decisions by admins should not be a reason to remove something that could actually make things fun in the right hands.

Especially not near-instant self-merges.

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
FOUR VOTES HERE WE COME
LET'S MERGE THIS WITHIN THE HOUR!

**Comment by kol1th** [comment]
Stop.

**Comment by Intigracy** [comment]
It's not an okay meme as long as it's not my meme - kolith 2016

**Comment by gbasood** [comment]
@Intigracy Contain your fucking salt
I don't care if @kol1th is a massive autistic diaper baby all the time but right now you're being an asshole

**Comment by TheFriggenSawbones** [comment]
can we put in the rules the basic human rights as established by some convention or maybe I can ask my mom what she thinks basic human rights are

**Comment by SonixApache** [comment]
A reference to the (space) UN's universal declaration of human rights + space law would be all you need imo.

**Comment by aceedex** [comment]
Removing it in the first place was retarded considering that we have crap like celtic, one human, oxygen is  harmful to humans and other stupid shit right in the upload

**Comment by Allspice** [comment]
Onehuman and oxytoxic are clear antag bait, but the problem with Hogan and Celtic is that the boards give they pretend to be ""legitimate lawsets"" and then players and admins both get asshurt when the silicunts shit on the crew's parade after upload.

**Comment by SkowronX** [comment]
I don't think I've ever seen someone use the lawset recently.

**Comment by gbasood** [comment]
Neither of them are legitimate lawsets
thinking about the implications of the lawsets for more than 10 seconds reveals that they effectively state nothing

**Comment by Durgen** [comment]
Did anything even happen to the Borg that murderboned on Hogan the other day?

What is the threshold of acceptable shittery on this lawset.

**Comment by gbasood** [comment]
In terms of administration? HOGAN is basically purged

**Comment by Durgen** [comment]
Ah, then I vote don't revert.

**Comment by Megamaw** [comment]
bring it back dagnabbit

**Comment by SysadminJeroen** [comment]
I interpret the HOGAN lawset as the following.

> Make sure that all men can do what they want.
> Fight for law and order, but put rights in priority.
> And do not let yourself get blown up or destroyed, unless that is to preserve the right of every human and to fight for what is right.

That means to leave the women alive, unless the women threaten the rights of men.

A rule could also be added that murdering (women) needlessly is prohibited unless ordered to do so.

**Comment by Aurx** [comment]
Please do not re-add.  If somebody really wants the AI running this (and to be banned when the silicons go nuts), the freeform core board is always there.

**Comment by SysadminJeroen** [comment]
@Aurx vote then.

**Comment by Aurx** [comment]
The day I use emoji is the day I ban myself from life for shitposting.

**Comment by SonixApache** [comment]
> In terms of administration? HOGAN is basically purged

wow, that's pretty stupid

**Comment by mrpain666** [comment]
If you must bring it back, put it on the same table with Antimov, because that's pretty close to the scrutiny we admins are going to start giving it now.

**Comment by gbasood** [comment]
I honestly think that in the case of silicon laws, since admins are the ones who have to deal with them (and also silicon players but most of the good silicon players have to deal with much worse than this), maybe the only people whose opinions matter for both HOGAN and CELTIC are the admins? Maybe

Also, I don't think HOGAN is fun. At all. It's one of the most bland memes we've had. I'd rather see a player actually get creative with purge+freeform than use this.

**Comment by SonixApache** [comment]
So the mins decide to take a massive dump on it because it's based off some wrasslin joke?
Can you really not look past the whole 'lel hulk hogan xd' part and just focus on the actual laws?

**Comment by mrpain666** [comment]
We're shitting on it because it's so fluid and open to interpretation you can theoretically get away with doing pretty much ANYTHING. If you must keep it put it on the experimental table with Antimov and such.

**Comment by SonixApache** [comment]
I'd like to argue that 'the rights of man' at the very least aren't very open to interpretation, since there's plenty of documents dictating them. Kind of in the same vein that 'humans' aren't defined in ASIMOV, but we have a pretty solid idea of what a human is.
Update the [wiki](http://ss13.moe/wiki/index.php/Guide_to_Silicon_Laws#Hogan) to be a little more descriptive?

**Comment by gbasood** [comment]
@SonixApache The rights of man are documented WHERE in spess?

We don't have bills of rights in SS13.

**Comment by troots** [comment]
rights as in if someone loses their left hand or leg you don't give a heck ya dingus it's so simple

**Comment by SonixApache** [comment]
Alright. It's mostly the mins that want this gone, and since they're the ones that mostly have to deal with it there's no real point in keeping this. Good discussion!

**Pull request closed without merging**
