### PR TITLE
Antimov is slightly more obvious

### LINKED ISSUE #22016: Suggestion: Make Antimov's laws more obvious to the silicon.
My suggestion would be having the text red when the silicon is viewing their laws; too many times people don't even notice they're on antimov since its so easy to just skim over it when you think its just asimov.

EDIT: I didn't realize how vague I was being, I mean only the silicon should notice they are on antimov, not the rest of the crew.

<featurerequest>

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Capitalized "must", maybe it will work
fixes #22016 
When I tried to make it red text it also made it type out the whole "span class" thing. I tried searching for law zero code because I knew that law 0 shows up with red text in the silly cone's lawset, but I couldn't find it
:cl:
 * tweak: Antimov lawset now has a capitalized "must". It looks like this: "MUST".

### CODE REVIEW

**Comment by Reviire** [comment]
It looks kinda stupid

**Comment by MadmanMartian** [comment]
Who cares? Borgs on antimov start killing non-humans and everybody anyway

**Comment by ghost** [comment]
Why not just add an extra law 1. pointing out your new malicious nature? Sentence structure of antimov is near identical to asimov, even bold letters will be easy to miss at a glance. Extra law will be hard to overlook.

`1. You hate humans.`

**Comment by ShiftyRail** [comment]
Could go the high road and refactor laws to include red text on examine but not on stating.
However, this requires effort
@codeungabunga I always thought of Antimov as just a "corrupted" version of Asimov, ie what the lawset would be with a "sign error" or something equivalent. At any rate, the similarities are intentional

**Comment by ghost** [comment]
The similarity is why we're having this conversation, logically it should be made visually dissimilar to avoid confusion. Easiest solution is an extra dummy law, of course different colored text would work too.

**Comment by Hoshi-chan** [comment]
Do it right or don't do it.

This is like saying you're making pizza for dinner, then putting ketchup and american cheese slices on a tortilla.

**Pull request merged**
