### PR TITLE
The Interdimensional Bank - a persistent money leaderboard.

### PR DESCRIPTION
**Pull request by ghost**
This PR adds the interdimensional bank to emergency shuttles - an ATM terminal which essentially just allows you to deposit money near round end and watch the number go up as time goes on and compete against others for riches. No, you cannot withdraw. 
I'm open to suggestions for funny/unimpactful benefits from being interdimensionally rich! As well as other ideas like confetti on the shuttle whenever someone deposits money and reaches a milestone.

And yes, it HAS to be on the emergency shuttle and not Centcomm. People need to be able to push you over and deposit the money into their account.

- [ ] Finish basic functionality to make sure deposits work.
- [ ] Map the Interdimensional ATM onto each map's emergency shuttle.
- [ ] Finish basic modifications to ATM sprite for the interdimensional ATM.
- [ ] Create an in-game leaderboard for richest ckeys.

:cl:
 * rscadd: Added an interdimensional bank ATM to the emergency shuttle, which allows you to deposit money persistently within rounds for clout.

### CODE REVIEW

**Comment by anonymoose-contributor** [comment]
This seems like a funny idea, but most of the time the shuttle's already an absolute disaster to deal with when it arrives, adding a new interactable thing with a small window of use is just going to further make an evacuation a giant mess.

**Comment by PrimeDSS13** [comment]
Since we already have a monthly leaderboard for "money in PDA/bank account at end of round", wouldn't this directly be counter to that? Seems like it would just be 2 competing systems for that same thing.

**Comment by kilozombie** [comment]
If anything, I think this should be something you can do at a *normal* ATM. Just a "deposit into savings account" button that saves it permanently to your character slot, and has no leaderboard at all. Purely a number goes up thing.

**Comment by DrSnips** [comment]
I do like the any ATM idea as an expansion upon this idea but I feel like miners would absolutely ruin this idea as with most other economy related things.

As for ideas of what to get out of doing it that are just for fun, maybe something like you can get a bank card that comes in fun appearances as you go through tiers (as unlocks so you could still use a previous tier card if you're past it). I would be willing to contribute to the required sprites.

**Comment by ghost** [comment]
I personally like the idea of it being round-end only so that it's more of a competition and a focal point as a reason to reach the escape shuttle. Miner money definitely breaks this though, so I would probably go and simply cut all mining costs and gains in half (or more) after this just to make it on-par with everything else.

**Comment by gurfan** [comment]
Interesting idea but money currently doesn't have enough value to warrant this. Fix that first.

**Comment by DrSnips** [comment]
something something JUST MAKE MINER-EXCLUSIVE CURRENCY ALREADY. We literally can't have any discussion about anything money related without miners undermining the concepts mechanically.
You really want to let them still cash in miner coins for cash? Just put cash in the vendors that way it 1) caps the capability for how much they can earn per round and 2) Lets you control how much they're making atomically IE 1 miner-coin buys 100credits. That too much? Just reduce that credit amount or raise the reqirement.

**Comment by DrSnips** [comment]
Oh yeah, one head's up about economy. Keep in mind that you can pull from department cards which is also effectively a giant wad of cash people can just pull from.

**Comment by anonymoose-contributor** [comment]
Money will continue to serve no purpose on /vg/ until something people practically need to enjoy a round is restricted to a purely monetary transaction without any possible third party ways to obtain said McGuffin. Like others have said, your head is in the right-ish place, just perhaps either make your idea have its own identity or solve the pre-existing issues we have instead of trying to ignore them.

**Comment by Eneocho** [comment]
Clearly the solution here is to make the money longterm storable IC like Kilozombie says, but make it so it checks THAT account instead of your virtual wallet+round account for the richest spessman, resetting the richest list if that character/ckey hasn't logged in in a month.

**Comment by SonixApache** [comment]
cute but i don't think it'd be worthwhile
a rounds survived stat to track might be interesting though

**Comment by falcon2346** [comment]
> cute but i don't think it'd be worthwhile a rounds survived stat to track might be interesting though

Personally I don't think I, nor anyone else, needs another reason to be salty about getting owned. I'm not a fan of any sort of leaderboard that doesn't reset regularly, as anything like that will be occupied 100% of the time by people that have played since said leaderboard's creation and newcomers will just see it as something they can't really participate in. Just a "number goes up" thing that only you see wouldn't be bad though.

**Comment by ErrorsWindows** [comment]
how do i withdraw money from my interdimensional bank i need more metal and fuel for fuse bombs and i already eftpos'd all the dead people's money from the medbay

**Comment by DamianX** [comment]
Hello @malfunctioning-ai 
Thank you for submitting your proposed changes to the vgstation13 project. It would appear that your pull request has bypassed some of the sections in our template, specifically the "Why it's good" part. This section is crucial for us to understand the impact and reasoning behind your changes. It helps maintainers and the community to quickly grasp the benefits and potential implications of the proposed modifications.

Could you please take a moment to update your pull request description to include this information? Providing a clear and detailed explanation will significantly aid in the review process, ensuring that everyone understands the value your changes bring to the project. Additionally, adhering to the template guidelines helps streamline the discussion and decision-making process for all contributors involved.

If you have any questions about how to fill out the template or why this information is necessary, feel free to ask. We're here to help guide you through the contribution process and make sure your efforts are recognized and understood by the community.

Looking forward to your update, and thank you for your contribution to vgstation13!

Best regards,

DamianX

**Comment by djkramer123** [comment]
I like this idea, though with miner money and botanists being able to abuse luck to spam jackpot/scratchoff wins it feels a bit lackluster, to name two. Those would need to be looked at before this is worth having really. 

I like the idea of cosmetic tiers of bank cards though, that sounds fun.

**Comment by ghost** [comment]
Seems like people dislike the idea of persistent leaderboards for some reason. I thought it was a cool idea and a fun thing to do on the escape shuttle but guess not, alas.

**Pull request closed without merging**
