### PR TITLE
New xenoarch drill

### PR DESCRIPTION
**Pull request by frangi**
I made a mess with the other PR (#2717).

This version should have "better" fluff regarding its abilities to precisely excavate (thanks to Emisune).

The requirements have also been upped and it is now at the end of the research tree.

Like I said in the previous PR, once deity gets to his xenoarch rework, the drill can be changed and incorporated into it.

### CODE REVIEW

**Comment by IratePirate** [comment]
Can you post a picture of the sprite?

**Comment by frangi** [comment]
Some anon posted it in the thread some days ago. It looks really "alien" but I don't know if the surgical drill or a modified sprite of it would be a better fit.

**Comment by SkowronX** [comment]
Looks like a giant syringe. Make the tip look more like a drill.

**Comment by frangi** [comment]
what about this?

**Comment by frangi** [comment]
This should be good to go. Balance discussion is always welcome tho.

**Comment by Duny-** [comment]
I don't really know how this affects the game as I don't know much about xenoarch. 
I can tell you I'm jealous of your ability to make a sprite that doesn't look like shit for your item though.

**Comment by frangi** [comment]
If you look at the old PR, pomf's concern was about the item not making sense, which I think I mended, Comic's concern was mainly the early research unlock.

What this item does is "lategame" replace the excavation pick set + handpick, 8 items total, two items removed from your belt.

The other advantage is not having to fondle with you excavation kit, which previously had microscopic sprites (fixed now by another of my PRs), it was immensely frustrating. The excavation kit contains 7 picks with a determined depth they can dig to (1,2,4,6,8,10,12), the handpick does 30.

The other final advantage is having access to the 12>30cm spectrum of excavation, which permits to excavate items faster since you need less "hits" to get to the desired depth. Consider that a rock depth is about 200cm, and it can contain multiple items at different depths.

Having access to "odd" depths doesn't actually give any advantage, since every depth/clearance you need to excavate to is even.

So yes, it's 8 items in one + the bonus of a wider excavation spectrum + no fondling. I think such abilities are permissible considering the research requirements and the need of diamonds and silver to produce the item.

**Comment by Duny-** [comment]
I guess that sounds alright since xenoarch is currently a chore, we'll see once it's in.

**Pull request merged**
