### PR TITLE
Adds Dave to non-Roid maps (2.0)

### PR DESCRIPTION
**Pull request by Gringonius**
Again, adds Dave to, or near, the mining outposts of other stations. This time it gets its own little enclosure but I'm still open to suggestions of what else they could contain. Right now I'm thinking of adding a little dead monkey  in mining clothes but I'm not even sure what Dave eats. 

Slightly unatomic by adding a little ugly sign warning people about Dave's enclosure, Roid included.
expensive prison eight 2019-01-29 154315

687474703a2f2f6d617064696666626f742e64657874726173706163652e6e65742f46696c65732f31303434313138382f35363233343730372f302f61667465722e706e67

:cl:
 * rscadd: Adds Dave to other maps.

### CODE REVIEW

**Comment by Gringonius** [comment]
Is the map diff render bugged or did I fuck up?

**Comment by Kurfursten** [comment]
This seems to be a really big invitation for shaft miners to fuck up their own air supply. I really think that it's a bit too dangerous just putting one wood door there and fragile roid walls that could be instantly mined through or blown by gibtonite.

**Comment by Gringonius** [comment]
I wanted it to look a little ghetto and made sure that the walls touching the room wouldn't spawn minerals but I could replace the door with an airlock in box and deff.

**Comment by Kurfursten** [comment]
For Packed you could just use fences

**Comment by Gringonius** [comment]
On second thought Dave can just open the wooden doors and leave anyway. I'll try those fence doors.

**Comment by Gringonius** [comment]
Done, fences doors in meta and packed, glass mining airlocks in deff and box. Both should prevent Dave from escaping and help with air leaks where simulated.

**Comment by SonixApache** [comment]
>build station around a roid that some friendly alien showed you
>declare him station mascot and celebrated hero
>he gets cloned and thrown onto other mining stations for corporate reasons

sad

**Comment by Arthurdentist** [comment]
Its nice to have some unique things on each station; I don't really see the need in porting Dave over to other stations.

**Comment by SonixApache** [comment]
i think the poster is cute though

**Comment by Gringonius** [comment]
I guess that some unique map features are more unique than others in the eyes of the playerbase.

**Comment by Arthurdentist** [comment]
The poster would actually be neat on Roid Station, could do a PR for that

**Pull request closed without merging**
