### PR TITLE
Morgue Access Change

### PR DESCRIPTION
**Pull request by Jackreturnswithaveangenace**
Requested by @PrimeDSS13. He paid me two whole pomf coins for this.

:cl:
 * tweak: People with morgue access can now no longer use the morgue interior door as a shortcut to sneak into medbay.
 * rscdel: Security checkpoint on deff has door into medbay removed to keep in line with the new policy.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
bless

**Comment by Kromkar** [comment]
As a lifelong SecMain I approve of this idea. A little more conversation, a little less action, please.

**Comment by Irradiation** [comment]
Can't morgue-nerds already do this?

**Comment by Eneocho** [comment]
This ruins the fun for the botany chads and absolutely wrecks my immulshon.

**Comment by BurntDevil** [comment]
>cant go into medbay as chaplain any more

lynch he

**Comment by BomberBro** [comment]
I don't have any real horse in this race, but slapping the tags "bugfix" and "oversight" on a PR that fixes neither of those things strikes me as dishonest. From a basic search #18594 comes to mind as a PR that **intentionally** added security access to morgues in some maps, so it's not a bugfix or an oversight here, and qol on a PR that arguably decreases qol for many jobs is whatever. 

Besides the terrible tagging my only suggestion for this PR is letting detectives keep the access for investigations I guess.

**Comment by SonixApache** [comment]
am i really going to have to hack into medbay like the filthy assistants do

**Comment by Kammerjunk** [comment]
yes? why would you get free access

**Comment by Kammerjunk** [comment]
@BomberBro sec still has morgue access, which means detectives can still get into maint
it's just only the exterior airlocks, so they can't use it to tailgate into medbay

agreed on the tags though, bugfix is probably actually used by collabs

**Comment by ShiftyRail** [comment]
Given how often officers are called to help medical, given how often officers die and need to be looked after, given how often medbay is raided, I think it's a bad thing to remove this "backdoor access" wholesale.

I think it's also a neat thing that Chefs and other people can get access to medical this way. It makes rounds more dynamic.

It's definitively not a bug fix.

**Comment by PrimeDSS13** [comment]
this doesn't stop any investigations in the morgue, as kammer said
security just doesn't have access to a department for no reason now

**Comment by ShiftyRail** [comment]
I'm withdrawing my downboat because I realise it's probably just a crutch I've gotten too used to.

As much as it's a crutch, it's a very useful one. In a world where sec is not as prone to hostile powergaming and protagonista syndrome, and there's more trust between it and other players, I don't think this PR would be needed. Nobody really minded me when I used it to rescue people or to help an officer being cloned.

I do dislike the removal of sec checkpoint door on Deff, because it turns the room into an antag lootbox (again), and adds up to the many reasons why the Deff experience is inferior to other maps.

**Comment by Kammerjunk** [comment]
copied from my own posts in the D*scord so I'm not just shouting this where it doesn't matter
- I don't like the sec blob rolling into medbay and taking it over, and this looks like it'd lessen that some
- I can't see an argument for sec having medbay access that you can't equally apply to any other department, and I don't like sec just getting access to places they don't actively need as part of their job

this will also mean that sec will leave physical evidence since they'd have to break in, whether it's the glubbs they're wearing or the windows they've broken, which will make it more obvious when they *are* being shitters, but still defensible when it's for a good reason

**Comment by bathosbathtime** [comment]
I think the checkpoint should at least be it's own PR as it feels like it is specifically intentional as opposed to the morgues probably being an oversight.

**Comment by beesil** [comment]
Too often I've seen a group of security roll into medical and silently do surgery on each other rather than interacting with medical staff. This PR will make that less of an accessible option, which I think is a good change in that it encourages interaction and makes security less of an all-powerful force.

I agree that the checkpoint should be in another PR however.

**Comment by Jackreturnswithaveangenace** [comment]
It seems my social commentary with tags was not seen as amusing by old sec metaclub members. As a fellow member I apologise. I see it isn't an oversight because @ShiftyRail had intended for security to have access to medbay while not having access to medbay (who has also helpfully gone ahead and changed the tags), in which case I will call this bad design and powercreep that we have kept around for a long time out of convenience for ourselves. Non-HoS Security does not have backdoor accesss to:

- Engineering
- Science
- Botany
- Kitchen
- Cargo
- Bridge
- Etc.

Whatever theoretical arguments that could be applied to them being able to enter medbay without actually having general access apply to all of these areas. The actual use of this back-door, including the route via the checkpoint on deff, is as a way for security and others to run in and self-treat or stand around awkwardly while doctors just do their best to not make a fuss. Personally I have only changed this because it was asked for and clearly a lot of people are now of the opinion it shouldn't be the way it has been. That said, there has been talk elsewhere that this is "unatomic", which is clearly nonsense because the purpose is singular and the security checkpoint having access defeats the purpose.

```Besides the terrible tagging my only suggestion for this PR is letting detectives keep the access for investigations I guess.```
@BomberBro Do you mean access to the morgue or the ability to walk into medbay (and not any other department) without needing to ask?

**Comment by Jackreturnswithaveangenace** [comment]
teeehee whoopsie

**Comment by BomberBro** [comment]
Walk in to medbay via morgue so they can medical scan corpses, I feel bad for detectives in this economy since they only exist to be crime scanner pinatas so they need all the help they can get

**Comment by Kammerjunk** [comment]
I'm not sure I follow. detectives need to be able to walk into medbay proper so they can scan the corpses that are being worked on, or is it for the corpses that might get left in medbay?

**Comment by ShiftyRail** [comment]
In plain words, it's to give detectives access to medbay so that they have a slightly easier time doing their job. Why not.

**Comment by Jackreturnswithaveangenace** [comment]
They can ask, or just perform autopsies on the table like they always have (and there is generally easy access to health analyzers elsewhere), or another PR can be made that gives them medbay access or puts a scanner somewhere like the morgue or brig's medical. I don't think you're being honest about not having a horse in this race, but detectives don't need that access, it is just a nice gameplay shortcut.

A good PR might be to make the detective less a part of security and give them more medbay, access, though. Perhaps take their guns away and move their office out of the department altogether. I like that suggestion.

**Comment by cloutcode** [comment]
bros
coroners when?

**Comment by SonixApache** [comment]
Can we remove brig access from paramedics, CMOs and blacktiders then? They have no reason to be in there.

**Comment by PrimeDSS13** [comment]
sonixapache moment

**Comment by ShiftyRail** [comment]
I predicted this comment.

**Comment by Dickwrath** [comment]
People are asking to leave a medical scanner in the autopsy room like they completely forget that Detective's have a medical scanner built into their PDA. I personally do not feel Detective would need any additional access changes as a result of this PR. Given Detective is the social role of security, there's no reason they can't just talk to medbay and be loosed in like everyone else instead of wordlessly entering through the back door. At least pretend you're going to ask questions relevant to investigation instead of the reality of just scanning blood and prints.

I also feel everyone on this PR is too focused on the Sec implications. Let me remind people of just how many roles have Morgue access.

-All of Security
-Chef
-Botanist
-Bartender
-Roboticist
-Research Director
-Chaplain

And maybe a few others that aren't springing to mind. But that's a huge amount of people who have access to Medbay just from having access to the morgue, and thus free entry. Changing the access to the medbay sided door will mean these jobs can still access the morgue for its intended purpose, (meat for service, asses for research, funerals for chappy) while disallowing them to circumvent front door access. 

I dislike playing medbay because too many people invite themselves in to help themselves, be it the aforementioned security officers to do surgery on themselves, or people raiding the chem fridge. Medbay needs more control over their own department, and people need to start letting them do their jobs. Forcing people to talk and engage with the doctors in a game that heavily relies on interaction can only be a good thing.

_Also if you want access during a round for whatever reason just ask the HoP, he's so, so lonely..._

**Comment by TGFH** [comment]
For security specifically I don't really get the complaints about security "taking over medbay." I have very rarely seen sec doing surgery on eachother when doctors were available to do that surgery. The vast majority of the time if sec is in medbay for any extended period, it's to babysit someone else that is being cloned/in surgery so they aren't robbed blind before they wake up, which is extremely common.
As for the Deff checkpoint I often wonder why it exists at all. There's another security checkpoint by arrivals on the opposite side of the morgue. Nobody ever really uses it.

**Comment by PavelCIA** [comment]
why yes I chloral and behead security in medbay for trespassing as non-antag CMO, how could you tell

**Comment by Killette2** [comment]
It's been pretty ingrained in me for a long time what IDs I can have steal to enter medbay. Now you're telling me it has to be an actual doctor's?

**Pull request merged**
