### PR TITLE
Fixes #6570

### LINKED ISSUE #6570: Exofabs become invisible while active
>Revision
f1ec4a92f99a9f5d4b39822a7a3ac5c9c8625db9 

>General description of the issue
Fucked

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #6570

### CODE REVIEW

**Comment by PJB3005** [comment]
That's not a fix.

**Comment by DeityLink** [comment]
That's what hotfixes are. And it's not either a bad way to do it. Swallow you pride.

**Comment by PJB3005** [comment]
I can't find any way to get this to work other than a noticable `sleep(1)`.

i'll get it tot he BYOND forums I guess.

**Comment by DeityLink** [comment]
In the meantime I'm offering a decent solution here. I understand that overlays are preferred when you've got an item with many different (and possibly simultaneous) states but it's not the case here.

**Comment by PJB3005** [comment]
Alright I made [a bug report](http://www.byond.com/forum/?post=1981629)

**Pull request merged**
