### PR TITLE
The Paint & Linen Update [Splinter 3]: Mapping Changes

### PR DESCRIPTION
**Pull request by DeityLink**
image

* Maps that have an Art Storage have had some of the new items added and an additional Patron des Arts, additionally to the one still far in the back of most libraries.
* Snaxi’s Library now has its own Patron des Arts vending machine, moved there from the nearby Rec Room.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I said this before but I don't like putting the art vendor in art storage because it was supposed to be a draw to the library. I also said this elsewhere: I think the art storage room should be depreciated as a hallway room and become more of a library annex on our maps. That main hallway real estate could be used for new small-space gimmicks like a mini barber shop, public garden, build space, fire shelter, etc. while the librarian could have a more complete art storage next to the library, expanding their role as go-to art job.

**Comment by DeityLink** [comment]
I respectfully disagree with your disagreeing. People place paintings all around the station already, it's not a hobby confined to the library specifically. And it's up to the Librarian to attract people to their library, and they now have really cool tools to do so. I'm not removing the art vendor from the library after all.

288907900-90807a43-8866-4a58-8e2e-e2ca919c0dcb

That being said I agree that merging the art storage with the Library is not a bad idea. So is repurposing the Library as more of a Museum, or entertainment room, that provides both art, literature, and entertainment.

And that is way out of scope of this PR.

If the art storage must go, it should have gone back when the art vendor was added, or at a later PR. I think it's dumb that our stations have "art storage rooms" that haven't been updated since I added sculpting mannequins to the game despite a whole painting system having since been added to the game.

**Comment by jwhitak** [comment]
Kurf is right.

Merge this anyway. Deity had to break a fully functional, complete feature set, so this would all be easier to review. Now it's considerably more difficult to add a few little items here and there for the art room vs the vendor. We can talk full library rework after the whole painting/cloth new systems are added properly.

**Comment by GreatBigFailure** [comment]
I mean we have the assembly vendor in multiple spots, booze vendor in the caps office too, etc. 
I do think it makes a bit more sense to have it be a recharge pack instead, but it's an extremely minor difference.

**Comment by Kurfursten** [comment]
Booze vendor in the cap's office (or a smoke machine or whatever) isn't what I'm talking about. That's a highly secure area. It's MORE WORK to do that than to go to the bar - but even if you do decide to break into cap's office for some reason, that's increasing player interaction all the same, just with the cap instead of with the bartender.

Putting an extra art vendor just in the hallways means that people will be pulled toward the hallway and non-interaction with another player instead of going to the library where they might interact.

**Comment by DeityLink** [comment]
I disagree with the idea that players are less likely to interact in a primary hallway, than at the back of the Library. And I also really think your concern that this might have a substantial impact on the amount of people coming to interact at the library is unwarranted.

Anyhow, **I'm ready to compromise and replace the vendor in the art storage room with a table holding some of the new items**. However with the atomization of the main PR, this one only holds the required type paths to the already mapped new items, and none of the sprites etc, and I don't want to edit the map trying to place invisible items, or spend time re-adding the items to the branch to do mapping and then removing them again. Instead I'm offering **to open another PR within the week following the merge of the update to do just that.** It'll be much more convenient for me. It will also bring at least some temporary attention to the art vendors to players who might have never actually paid attention to it and then come to seek it out at the Library after it returns to being its only location. We both stand to win with this solution.

**Comment by wotisjanitor** [comment]
according to heatmaps, nobody is interacting with anyone in the library and everyone is interacting with people in the hallways. It's not going to be 4 people going to the library at the same time and then talking about art. It's going to be 4 people going to the library 45 minutes apart from each other, spending 5 seconds buying their merchandise, then leaving.

**Comment by GreatBigFailure** [comment]
> according to heatmaps, nobody is interacting with anyone in the library and everyone is interacting with people in the hallways. It's not going to be 4 people going to the library at the same time and then talking about art. It's going to be 4 people going to the library 45 minutes apart from each other, spending 5 seconds buying their merchandise, then leaving.

Team hallway deathtrap wins again

**Comment by Kurfursten** [comment]
That's the point. People aren't interacting in the library because there are scarce draws to it. In fact, unless new heatmaps have been taken I'm not aware of, those heatmaps are even before the art vendor was added. If you keep adding things to hallways and not to specific rooms you can't then turn around and use that as evidence that nothing should be added to those rooms.  Yes, we are aware the room is underutilized, that's the point. You are looking at things entirely backwards.

In fact, you have completely refuted Deity's argument that there are enough things in the library to draw people there already.

**Comment by DeityLink** [comment]
When I said 

> "And it's up to the Librarian to attract people to their library, and they now have really cool tools to do so. "

I was referring specifically to the new paint roller floor painting I'm adding in the update, hence the image. I don't think I ever said "that there are enough things in the library to draw people there already". But it's 3:30 am so I might be wrong. If I'm not though, please don't misunderstand my words.

**Pull request merged**
