### PR TITLE
Paramedic Access Tweak

### PR DESCRIPTION
**Pull request by Kurfursten**
This adds Morgue and Genetics access to the paramedic so he can do
something about all those bodies he finds.

### CODE REVIEW

**Comment by Probe1** [comment]
I think it'd be better if the door to the cloner had genetics access rather than the other way round.  Genetics is not the purview of a paramedic, however the cloner on Box is in genetics.  The solution is to change one doors access, and leave the other door into genetics proper unchanged.

**Comment by Duny-** [comment]
Should be changed on the map instead

**Comment by d3athrow** [comment]
Put genetics in science and open cloning to all medical staff.

**Comment by Kurfursten** [comment]
I agree that it would be better to just change the door access. I'm going to close this and reopen a PR with the door changed instead.

**Comment by Probe1** [comment]
Thanks for sticking with it Kurfursten!

**Pull request closed without merging**
