### PR TITLE
Cup Ramen self heating again

### LINKED ISSUE #16788: dry ramen doesn't turn into undry ramen when mixed with water
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
# Revision
bb83beadcbce952295d60e10cdbc2bc2f7d63d1c

# Description
adding water to dry ramen from the getmore machine doesn't undry it like it used to. needs more testing

### PR DESCRIPTION
**Pull request by ihadtoregisterforthis**
This PR adds calcium oxide as a reagent. Calcium oxide becomes calcium hydroxide in contact with water, and gets very hot. Two or three units are enough to boil water.
This also adds this construction material to cup ramen as a way to use it and a way to obtain it.
All the properties of the reagents were taken from various sources so if anyone is feeling picky about numbers it can be changed

Not included: any use for calcium hydroxide, ill effects to eating either, wiki update, calcium.
Ramen now needs a weird amount of water to fully boil and I don't know a good solution to that.

Fixes #16788

----
:cl:
* tweak: Cup ramen is self-heating again
* rscadd: Added quicklime as a heating chemical for your reagent temperature needs

### CODE REVIEW

**Comment by Kurfursten** [comment]
Use the react_discretely var for this in that case. react_discretely will handle one reaction at a time no matter how it's delivered (whether all at once or slowly droppered in). Then just adjust how much you want it to heat up per reaction since you will have a consistent result.

Magic!

**Comment by ihadtoregisterforthis** [comment]
It just werks, and with less caustic powder

**Comment by SonixApache** [comment]
Why can't ramen just work as catalyst to heat up water?

**Comment by Pathid** [comment]
@SonixApache Funny you should ask that. *cough* #16811 It would be perhaps cleaner to do it that way, but then you wouldn't be able to isolate the self-heating part of it for some future use.

**Comment by SonixApache** [comment]
or we could just not isolate it and leave the only self-heating reagent in the game as self-heating until someone has an actual need for it

**Comment by ihadtoregisterforthis** [comment]
Options were
>Reverting the need for boiling water
Changing the description so it's no longer self heating
Adding a "boiling water" reagent
Adding chems to heat it inside the cup
Make the cup itself heat up which is the IRL case but with cans

If the noodles automatically boil the water it's the same as not needing boiling water for it. It is a solution but a lot of internal theorycrafting led me to do this instead. 

Also I just remembered the chef can cook the same ramen cups as the ones from vendors from only flour and cardboard.

**Comment by Pathid** [comment]
@ihadtoregisterforthis Oh yeah. This is going to end up causing sundae ramen to be harder to make since the calcium oxide will need to be removed.

**Comment by SonixApache** [comment]
What's wrong with having the ramen cup heat it up?

**Comment by ihadtoregisterforthis** [comment]
It didn't occur to me until I had already made the PR

**Comment by Probe1** [comment]
@ihadtoregisterforthis hows the PR doing?  Ready for review?

**Comment by ihadtoregisterforthis** [comment]
This is ready, it's just bad. I don't know how to make the container heat itself. Water and calcium hydroxide remnants on the cup are shitty but don't detract the ramen effects. Also thought of adding hot water to water dispensers on another PR, but there are barely any on any station.

Both powders cause irritation and I can look for a fitting effect for ingestion, but slaked lime isn't highly toxic when dissolved in water. Recipes that need ramen are only slightly affected, every proper kitchen has a chemmaster and the extra reagents can be removed, something already required for getting maple syrup. 

As for ways to get calcium from bones or making hydrated lime into fresh quicklime, I feel it would be very unatomic. Adding more uses for hydrated lime sounds irrelevant while it's a rare subproduct.

**Comment by Kurfursten** [comment]
Do it like soda cans do. Have the first attack_hand make it self heat with a sound effect, rather than drinking. That's how they do the little pop the tab bit.

**Comment by ihadtoregisterforthis** [comment]
The thing now causes coughing and lung damage which might be weird. One vendor ramen cup causes 2.5 lung damage, meaning bad damage happens just above three full cups.
Also microwave ramen now doesn't have the thing.

**Comment by Probe1** [comment]
Why?  I see what just don't understand why.

**Comment by ihadtoregisterforthis** [comment]
It was the closest I could get to throat damage. I'm open to other options.

**Comment by Probe1** [comment]
Do regular torso damage instead.  Imagine making the choice between cheap food with lung damage or cheap food without in game.  Damaging internal organs necessitates a surgery.

**Comment by Pathid** [comment]
Lung damage is no joke. Dan's food doing liver damage is different because you can heal liver damage with anti-tox if it's below a certain threshold.

**Review by MadmanMartian — DISMISSED** [review]
Add a way to acquire /obj/item/weapon/reagent_containers/food/drinks/dry_ramen/heating

**Comment by SonixApache** [comment]
worst timeline

**Pull request merged**
