### PR TITLE
Adds Parkinson's Law of Triviality

### PR DESCRIPTION
**Pull request by 9600bauds**
I absolutely cannot think of a single reason to justify doing this instead of something else

### CODE REVIEW

**Comment by Probe1** [comment]
TECHNOLOGY tag

**Comment by Exxion** [comment]
> `sound/effects/lingrounds.ogg`

**Comment by 9600bauds** [comment]
shh

**Comment by unid15** [comment]
:+1: beautiful

**Comment by NigglyWiggly** [comment]
> sound/effects/lingrounds.ogg

Why did you do this

**Comment by 9600bauds** [comment]
explorer_2016-04-14_19-33-27
it is keeping a theme
someone will someday go through sounds/effects seeing what effects there are and won't be expecting it

besides it's a nice sound effect

**Comment by ghost** [comment]
I think it can be done even better than that : 
- Create a new var list called "open_sound" or something to that effect
- Add the three sounds
- Use a pick instruction in playsound, which will do the random stuff for you

This allows people to add new sounds on the fly, or badmins to edit it

If we ever had this behavior to new items (snacks, other bottles, etc), this will also allow us to directly inherit the behavior much more easily

**Comment by 9600bauds** [comment]
Yeah sure

**Pull request merged**
