### PR TITLE
fixes runtime in striketeam.dm's jobban check

### PR DESCRIPTION
**Pull request by Probe1**
Closes https://github.com/vgstation-coders/vgstation13/issues/14492

Thanks for the quick diagnosis @mtpowell

### CODE REVIEW

**Comment by Intigracy** [comment]
if you return instead of continue then the first person looped through that's jobbanned ends the recruitment for everyone else

the problem is a null client trying to do O.client.is_afk()

put !O.client before the first check

**Comment by mtpowell** [comment]
Yes, listen to @Intigracy , I fucked up

**Comment by Probe1** [comment]
I don't know what you mean @Intigracy just edit the PR would you

**Comment by Intigracy** [comment]
fixed

**Comment by JMWTurner** [comment]
This is the best April Fools PR

**Pull request merged**
