### PR TITLE
He's the boss. Boss cultist.

### PR DESCRIPTION
**Pull request by ShiftyRail**
Featuring very high-quality sprite. It's the cult squid, but with more tentacles.

image

## What

The first cultist to be drafted in a blood cult gets a special icon, and the status of boss cultist.
He can also speak directly to other cultmonkeys via `:x` to coordinate.

## Why

Every single other team antag has a leader. A cult leader might make cult slightly less of a confusing slugfeast with everyone doing their own thing in their corner of the map. It might also allow them to do `gimmicks` more often, and allow for funnier rounds.

We were talking about Cult IV and it was an idea I had in mind to make cult suck less to fight against so that other annoying things about it can be addressed.

:cl:
- rscadd: During Blood Cult, one cultist is the chief of the Cult and can talks directly to other cultists by using ":x". He gets also a special HuD icon.

### CODE REVIEW

**Comment by juanototo2** [comment]
Wow, I can't believe my idea was implemented!

**Comment by APCUnlocked** [comment]
Long have we waited. Any way to make some sort of an optionality check so that the newfag cultbabby can't become leader by accident or is that gonna be a feature(tm)?

**Comment by ShiftyRail** [comment]
It works the same way nuke ops do, no seniority check. Could add one for both roles in a later PR.

**Comment by Irradiation** [comment]
;x how do you do, fellow cultists? I'm converting the captain in dorms.
;haha it was a joke

**Comment by APCUnlocked** [comment]
> It works the same way nuke ops do, no check seniority check. Could add one for both roles in a later PR.

I'd like that, not sure what the majority think of it though. Good PR nonetheless.

**Comment by iFlashYou** [comment]
You probably could solve some problems with cult if just every cultist gets access to :x at the start/conversion

**Comment by ShiftyRail** [comment]
@iFlashYou This particular PR was #26717. It was somehow rejected even though it would make sense. (I don't like cult but I wouldn't downvote it)

It seems this one will get merged, though.

**Comment by Blithering** [comment]
That's pink.

**Comment by beesil** [comment]
Good content, boss baby cultist icon should be more red and less hot pink though.

**Comment by Sooose** [comment]
Really wish I could opt out, I don't want to lead nukies either.

**Comment by ShiftyRail** [comment]
I can't sprite.

**Comment by djkramer123** [comment]
this is the pinkest red I've ever seen

**Comment by TGFH** [comment]
a764554b9be6b6cb61b73031ff852adc

Make runes the same color

**Comment by DeityLink** [comment]
image

That's not cult 4 though

**Comment by DeityLink** [comment]
I'm fine with this temp crutch until I get to the Cult 4.0 role PR

**Comment by jknpj** [comment]
It's pink.

**Comment by Kammerjunk** [comment]
it's clearly fuchsia

**Comment by ShiftyRail** [comment]
I'll try to make it less pink the other day

**Comment by ShiftyRail** [comment]
image

Less bad sprite offered generously by @Blithering (god bless)

**Comment by gurfan** [comment]
thats one angry squid

**Pull request merged**
