### PR TITLE
Fixes being able to whisper while silenced.

### LINKED ISSUE #8647: Still able to Whisper while Changeling Silenced
Apparently not an intended feature, was suicide vest-ed by a poor sport while absorbing them on the asteroid.

Poor sport proceeded to convince me it was an intended feature and get super-butthurt about my inquiry as to it's legitimacy so have fun!

### PR DESCRIPTION
**Pull request by gbasood**
Fixes #8647

### CODE REVIEW

**Comment by Exxion** [comment]
But can you still whisper while paralyzed by the Neurotoxin drink, etc.?

**Comment by gbasood** [comment]
Haven't changed that, so yes.

**Comment by Exxion** [comment]
So that uses a different variable than silent?

**Comment by gbasood** [comment]
Paralysis doesn't effect the silence var, yeah.

**Pull request merged**
