### PR TITLE
humans are now naked by default + randombodies can roll no underwear

### PR DESCRIPTION
**Pull request by SonixApache**
requested by the degenerates in discord 
🆑 
 - tweak: humans are now naked instead of growing with diapers on them
 - tweak: randombodies can now be naked

### CODE REVIEW

**Comment by Lokiamis** [comment]
Monkeys first

**Comment by Shadowmech88** [comment]
One step closer to VOREstation.

**Comment by 9percents** [comment]
one thing that I would suggest is to make monkeymen still wear diapers because monkeys wear them

**Comment by utilitas-** [comment]
tighty whities **rule the nation**

**Comment by ghost** [comment]
about fucking time

**Comment by SonixApache** [comment]
monkeymen have random DNA and as such get random underwear afaik

**Comment by ComradeDispenser** [comment]
Your undies are part of your DNA?

**Comment by ghost** [comment]
> 
> 
> Your undies are part of your DNA?

spessmen have augmented genomes that include genetic coding for their underwear which is made out of nanomachines

**Pull request merged**
