### PR TITLE
Improved baseball bat throwing logic

### PR DESCRIPTION
**Pull request by DamianX**
The original implementation tried to rotate the direction by a random number between -30 and 30, which doesn't work because `turn` only accepts multiples of 45.
I've changed it so the object is thrown in the direction the batter is facing, with a random rotation of either -45, 0 or 45 degrees.

:cl:
* tweak: Knocking things away with a baseball bat now throws them in the direction the batter is facing, with a chance to deviate 45 degrees in either direction. Being more sporty makes batting more accurate.

### CODE REVIEW

**Comment by Kurfursten** [comment]
If you wanted to, you could get more precise direction randomization the way most scattering works, which is to pick a tile some distance away and throw at it.

It would also be neat if sportiness increased accuracy

**Comment by DamianX** [comment]
Made it so drinking sports drinks makes you 5 times more likely to throw where you're looking at.

**Comment by DamianX** [comment]
I just realized I committed the changes to the sport vars with the new macros. I made those because I was originally going to check something like `if(get_sportiness() > SPORTINESS_SPORTS_DRINK)` but then I did it differently. I can keep them like this or revert them

**Comment by Rabbidx7** [comment]
Love it. Make the bar not shit by switching the location of the counter. Either make it where the kitchen is now, and connect hydro to the kitchen through the livestock area, or make the bar at the top. If you go with the first suggestion though, it will allow people to grab food from the hall and not be forced to go into the bar, its a good change, imo.

**Comment by Kurfursten** [comment]
Pretty sure that comment [now deleted] is intended for the island kitchen PR

**Comment by Rabbidx7** [comment]
> Pretty sure that comment is intended for the island kitchen PR

It's not, but I'm gonna post it there too. Stop making the kitchen the bar ASAP

**Comment by boy2mantwicethefam** [comment]
Changelog

**Comment by GreatBigFailure** [comment]
More sportiness buffs is a beautiful thing.

**Pull request merged**
