### PR TITLE
Xgm new

### PR DESCRIPTION
**Pull request by ghost**
Because something this crazy isn't worth being lost over an argument

PJB3005 commented 15 days ago • edited

So last year in August, me and @clusterfack started this. We lost steam and forgot about it. To not lose steam this time I'm just gonna make the PR so people can shout when.

I'm reviving this now, but it's still very WiP and in no way merge ready.

I lost the commit history due a Git issue, see here for the history: https://github.com/vgstation-coders/vgstation13/tree/XGM

Checklist:

- [ ] `#warn` TODOs need to be fixed.
- [ ] Zone regen has bug where sprites get lost for a tick.
- [ ] Fire needs balancing.
- [ ] Update with latest fixes from bay.
- [ ] Make plasma not ignite below visibility.

### CODE REVIEW

**Comment by ghost** [comment]
I'll tell you this now. I've no idea how any of this works.

Let's take a look-see

**Comment by Anton-Kr** [comment]
When

**Comment by PJB3005** [comment]
Absolutely never I've lost all interest in coding SS13.

SS14 all the way.

**Comment by Exxion** [comment]
>SS14

See you in a couple months when the shitcode collapses in on itself again

**Comment by PJB3005** [comment]
At least coding SS14 is enjoyable and I'm learning something useful.

**Comment by Exxion** [comment]
We're taking this PR to the chop shop. It's getting cut up into smaller, more manageable pieces. Stay tuned.

**Comment by Intigracy** [comment]
Doing the same thing to snowmap when

**Pull request closed without merging**
