### PR TITLE
Added feedback to bar sign error

### PR DESCRIPTION
**Pull request by JMWTurner**
I mistook a case of missing feedback for a bug. Turns out that someone decided that you need to stand south of a bar sign to edit it. However there are no error messages when you try to do it from the north, leaving you to believe that you ran into a runtime error.

### CODE REVIEW

**Comment by ComicIronic** [comment]
The only issue I can see with this is that south is a dir-locked direction, and this message won't work when we enable client dir changes.

**Comment by JMWTurner** [comment]
I think that barsigns being dir-restricted is dumb in the first place personally.

**Comment by gbasood** [comment]
Is there any reason to have them dir restricted?

**Comment by PJB3005** [comment]
Yeah I'd just remove the restriction.

**Comment by JMWTurner** [comment]
That was @eswordthecat 's idea https://github.com/d3athrow/vgstation13/commit/41f790c3b548d9a6abf6737f18aba1c6d1077a6f#diff-960a6e0866918c680d35a4ef5a1402b5R59

I guess I'll just remove that line then.

**Comment by JMWTurner** [comment]
revision 1
- reverted having to stand south of a barsign to interact with it.

**Comment by ghost** [comment]
There will never be client dir. Screencap this comment.

**Pull request merged**
