### PR TITLE
fix double VOX announcement, oven circuit board, shuttle/power computer unwrenching, and some more

### LINKED ISSUE #23632: Power Monitor is Shitcode
it's fucking code/modules/power/monitor.dm instead of a machine of some sort, meaning that it has to have snowflaked code for screwdrivering and it doesn't have said snowflake code for wrenching. It probably needs refactored

### LINKED ISSUE #27528: borer inside human turned zombie get blackscreen
#### Description of issue
be borer inside human
human turns into zombie
blackscreen
grafik

also when ghosting i spawned in the arrivals shuttle

#### Difference between expected and actual behavior
to be spit out, dead or inside the zombie

#### Steps to reproduce
see description

[bugfix]

### LINKED ISSUE #29445: "Bluespace connection lost" announcement is spoken twice
I think the sound file itself contains the same audio twice.
@N3X15

### LINKED ISSUE #29458: "Do not touch strange alien artifacts" roundstart reminder spoken twice
[sound][bugfix]
Same as bluespace lost issue it seems
@N3X15

### LINKED ISSUE #29589: Oven is not functional machinery
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
7b5288fa0a7b44aeeb088fb28cf3f161d8442267

# Description
The oven, produced from soldering an oven circuit board with a soldering iron does not have any actual function, unlike the oven in the kitchen.
# Steps to Reproduce
Solder a blank circuit board from a piece of glass, solder the oven circuit board from the blank circuit board, assemble the machine, and load fruit into it.  The ingredient will be accepted and the oven will turn on immediately, but does not actually do anything.
# What you Expected
I expected the oven to be the EZ bake oven that the kitchen has, which can create food from ingredients with a menu of options for pastries it creates like bread, donuts, and pie.
If it would not do this, I would expect it to function the same as a microwave, inserting the exact ingredients resulting in a specific food dish.
# What Actually Happened
The oven accepts ingredients and turns on, but simply stays in the 'on' animation and never produces any food.
No menu ever appears offering a recipe to select either.
It simply appears to be operating without actually doing anything.

### LINKED ISSUE #29674: Shuttle consoles cannot be unbolted
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
6919a00ef3b6d38924641a6ccdc3fbbebb4ddb6d

# Description
Shuttle consoles UI interact instead of allowing unbolting
# Steps to Reproduce
Use wrench on console
# What you Expected
Unbolt and move
# What Actually Happened
UI interacting

### PR DESCRIPTION
**Pull request by gurfan**
Fixes #29589 
Fixes #23632
Fixes #29674 
Fixes #29458 
Fixes #29445
Fixes #27528

[bugfix]

### CODE REVIEW

**Comment by Eneocho** [comment]
Now THAT'S what I call unatomic!

**Comment by Eneocho** [comment]
Does the oven get improved in any way with better parts (faster cooking, multiple stuff simultaneously, etc)?
Also, since the EZ-Oven is now craftable, the cereal and candy makers should be too.

**Comment by gurfan** [comment]
upgraded parts don't matter,  it's just the ez bake oven, I'm not adding more stuff to the solder menu because that isn't the point of this PR

**Comment by Eneocho** [comment]
> 
> 
> upgraded parts don't matter, it's just the ez bake oven, I'm not adding more stuff to the solder menu because that isn't the point of this PR

I meant that for consistency it should be done at some point.

**Pull request merged**
