### PR TITLE
Make only one changeling spawn

### PR DESCRIPTION
**Pull request by Manleto**
Look I don't know how to code, sorry for making so many PRS.  

this is part of the "test run" if it turns out that one ling is fun we can test with more. 

I am less confident about this change, if anything it means less people get to try it for themselves.  However I understand that people are worried about the perma removal. 

If you'd rather have more lings thumbs this one down.  
.

:cl:
 * rscadd: Made only one ling spawn

### CODE REVIEW

**Comment by Kurfursten** [comment]
The only truly interesting thing about Changeling is that there are several and they can either team up or hunt each other down. It's a very curious dynamic because working together they can be super deadly but they are incentivized to kill each other for big genome rewards. Limiting ling to 1 removes the one thing that makes it a cool mode.

**Comment by DeityLink** [comment]
Like I said in the Discord, the reasoning behind this PR is lacking:
* by capping the amount of lings to 1 you drastically reduce the amount of players who get to try playing as one, which impedes your goal of seeing if today's playerbase would enjoy it.
* you didn't actually change anything about the antag itself, the reason why it got removed in the first place. People don't like ling at a conceptual level, it needs a full rework to be made more unique and interesting. Currently Vampire just does its gimmick just way better.

I really think that today's playerbase has moved even further away from a place where an antag like ling is acceptable, but on the other hand I could be wrong, and in either case it's a new thing to try out for many players. We'll see how this goes.

**Comment by ghost** [comment]
I'd like to see ling reduced to 1, but only along with the other changes I suggested. People want ling to be The Thing: The Role, but in order for that to be the case it should be one really strong antag that still feels fair to die to. Reducing current ling to one would alleviate the rampant murderbone and round removal but it's not balanced around being a single antag spawn.

**Comment by DamianX** [comment]
See the comments above, #27814 and #27813

**Pull request closed without merging**
