### PR TITLE
Makes goliaths use tentacles only when target is not on a space tile

### LINKED ISSUE #5108: goliaths can use their tentacles in space
what

### PR DESCRIPTION
**Pull request by ThHuberResearch**
Fixes #5108
First coding attempt, tell me if I did something wrong. Tested on a local server and worked. 
What I did exactly:
add a check to see if the turf it wants to make tentacles on is space, and if it is not, spawn tentacles as usual. If it is space nothing happens.

I made a goliath follow me around in space and it did not create any tentacles on space tiles (confirmed that it did do this before).
Goliaths still create tentacles on other floors (tested on local server with this change)

:cl:
 * bugfix: Goliaths spawn tentacles only when the target is not in space

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Looks good other than the changelog. Get rid of the /:cl: at the end.

**Comment by jknpj** [comment]
you don't need <s>to go back</s> that /:cl:

**Review by PJB3005 — APPROVED** [review]

**Comment by Aurx** [comment]
Does this prevent tentacles from spawning in space tiles adjacent to the targeted tile?

**Comment by PJB3005** [comment]
@Aurx doesn't look like it actually.

**Comment by ThHuberResearch** [comment]
Thanks, that should be fixed now. When it spawns the three "side-tentacles" now it checks the turf they are being spawned on for whether they are not space tiles (!istype(turf, /turf/space) and if they are not, it makes a tentacle.

**Pull request merged**
