### PR TITLE
Firefighting equipment crate

### PR DESCRIPTION
**Pull request by brndd**
I don't think there was any way to get firesuits other than the ones that exist at roundstart, and none of the crates contained extinguishers either (should they go missing from extinguisher cabinets). This adds a crate to cargo under the Supplies tab that contains:

- Two firesuits
- Two gas masks
- Two firefighter helmets
- Two fire extinguishers

It costs $20, which is in line with similar supply crates (yes, they are really quite cheap). I decided against including the fire axe because that might make this too much of a powergay crate, even though there are multiple fire axes quite readily available on all stations. Roboticists rejoice.

Additionally, there is an **advanced firefighting equipment** crate under Engineering that contains the following:

- One fire axe
- Two foam fire extinguishers

It costs $25 and is locked to atmospherics access.

There's probably lots more minor stuff that could be added to the cargo terminal. I might take a more comprehensive look at some point, this and hardsuits (#22649) were just the ones off the top of my head.

:cl:
 * rscadd: Added a firefighting equipment crate to the cargo computer under Supplies. It contains firesuits, fire helmets, gas masks, and extinguishers. Also added an advanced firefighting equipment crate under Engineering that requires atmospherics access and contains a fire axe and two foam extinguishers.

### CODE REVIEW

**Comment by FudgePucker** [comment]
Awesome.
This is the only way to get more than three (three) foam extinguishers on the station.
I don't know how I feel about this, on the one hand it is the only real way to fight really hot fires other than waiting for a year for the air alarm to cool down the area, on the other hand it is REALLY POWERFUL and can fuck the atmos in an area.

**Comment by robosperg** [comment]
mechanics can scan and print foam extinguishers, ancient matter synth can also make more

**Comment by Durgen** [comment]
chance of fire axe?

**Comment by Blithering** [comment]
I would say fire axe would be a bad idea, people would just buy the crate for the big melee weapon, leading to access restriction debate etc.

**Comment by FudgePucker** [comment]
Like, what use does the fire axe have with fighting fires?
Oh, yea, it can open firelocks, just like a crowbar, that can fit in your backpack, or your pocket, or your toolbelt.
Oh it can smash windows in one hit, so that way you can spread the fire around instead of just using the window as a one tile airlock.

**Comment by brndd** [comment]
I could make the fire axe into a contraband crate, but I don't know what else to put in there. I don't think the foam extinguisher is dangerous enough ("IC"-wise, since it's just a fucking fire extinguisher) to warrant putting into a contraband crate, and yes I'm fully aware that a few sprays of it will cool a hallway down to -100°C.

Alternatively it could be in an "advanced firefighting equipment" crate that contains a couple of fire axes and like 4 foam extinguishers and requires atmos access to open. This way the normal crate wouldn't contain foam extinguishers.

**Comment by FudgePucker** [comment]
I dont see the point in having the fire axe orderable.
Dont even bother telling me it will be behind an access requirement. It's not like cargo DOESNT aquire an emitter every round.

**Comment by Kurfursten** [comment]
I don't want to see foam extinguishers orderable, especially not in a crate that isn't even locked. Foam extinguishers are extremely powerful tools that can very quickly ruin all the major hallways just dragging a watertank with you. I've never had a situation in years of engineering where I ran out of foam extinguishers.

The rest is totally fine

**Comment by brndd** [comment]
> Dont even bother telling me it will be behind an access requirement. It's not like cargo DOESNT aquire an emitter every round.

With an emitter cargo can get far more dangerous weapons than the fire axe.

I think I'll put foam extinguishers and the fire axe in a crate that needs atmos access.

**Comment by brndd** [comment]
It is done. I believe the access requirement is sufficient to keep this crate from being abused. If you have the means to bust open crates you have access to much more dangerous stuff than foam extinguishers or fire axes (guns, singularities, shards, emitters...), and if you already have atmos access you probably already have foam extinguishers, so I think this will be alright.

**Comment by FudgePucker** [comment]
I think the only reason that engineering doesn't run out of foam extenguishers right now is because the new friends don't know how robust they are. There's only three of them.

**Comment by jknpj** [comment]
the advanced crate is literally too cheap.

**Comment by brndd** [comment]
> the advanced crate is literally too cheap.

Do you have a better idea for the price? Most crates are very cheap. A crate containing two eguns costs 30 credits, for instance.

**Pull request merged**
