### PR TITLE
Centcom Updates 3 Return of the maps 

### LINKED ISSUE #7163: Bar inconsistencies
1. The bartender gets an RSF on every map (two on Meta) (???) but only gets compressed matter cartridges for it on Box.
2. The bartender gets a double barrel on Box and Meta but a standard shotgun on Taxi and Deff.
3. The bartender does not get a rag on Box.

### LINKED ISSUE #7243: Xenobotany on the roid has no clippers in the crate
Give me plant clippers or give me death

### LINKED ISSUE #10222: Cabin 1 on Metaclub is not linked to the door button
Door can't be bolted, if you press the bolt button nothing happens

Just another case of bad id_tag instancing

### LINKED ISSUE #10454: Everything about the gooncode sat is hilariously dysfunctional
Problem 1)
You can cheese every single Russian by just breaching any room and then just letting them all suffocate as you go. Speaking of, even if you bolt open both starting airlocks, the air doesn't drain for some reason.
Problem 2)
The russians will actually cheese themselves for you.
dreamseeker_2016-06-08_17-13-01
They'll break every single fucking window for some reason.
Problem 3)
The turrets can still be deactivated with a head of staff ID.
Problem 4)
For some fucked up reason, the inner windows SOMEHOW protect you from the turrets
https://a.uguu.se/EU7NrVGpWH8h_Desktop06.08.2016-17.32.10.02.webm

### LINKED ISSUE #10517: ATMs in other maps cargos
Saw Bus stations cargo for the first time last night.
It's got something that's been sorely needed in the other maps cargos for a very long time.

An ATM inside cargo itself and the QMs room.

Too often the situation is, transferring money to and from accounts only to be robusted, robbed, or honked in the hallways.

Think it'd be worth adding in?

### LINKED ISSUE #10623: Meta Club map issues
(WEB REPORT BY: kernikov REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 778f64fcb19aa9845fa123de92002a95acaf7ba6
> 
> General description of the issue
> Metaclub Cryo table isn't a reinforced table, can't place the wrench on it. Aux bathrooms near arrivals won't open with a MD ID.
> 
> What you expected to happen
> The opposite of the above.
> 
> What actually happened
> The above.
> 
> Steps to reproduce if possible
> Exist on metaclub.

### LINKED ISSUE #10910: Mule cannot find security or janitor dropoff destination on box station.
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision 0d91b25673f35182d69c6e36175ad143f2e1db89 
> 
> General description of the issue
> Set janitor or sec as mule destinations and it wont path. Kind of a downer when you want to send sec shit.
> 
> What you expected to happen
> Slowly meanders to sec/janitor and drops off.
> 
> What actually happened
> Mode: Unable to locate destination
> 
> Steps to reproduce if possible
> Get on or put stuff on a mule, set target to security/janitor then hit proceed

### LINKED ISSUE #10985: Defficiency supermatter monitor lacks cameras
(WEB REPORT BY: higgsbonbon REMOTE: 172.93.109.202:7777)

> f01cfbadfc946f6440c379dffcf7bf1f2b296901 

Defficiency Supermatter Monitor is not connected to any cameras.

### LINKED ISSUE #11101: the pirate shit in metaclub has no light fixtures
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

no lights

> What you expected to happen
> lights
> 
> What actually happened
> no lights
> 
> Steps to reproduce if possible

go in the pirate ship and find no lights

### LINKED ISSUE #11103: there is only one spade in hydroponics
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> feac920487ed604e23e413c289f04239d1a5fe2b 
> 
> General description of the issue
> there is only a single spade in hydroponics, and tough luck if it gets lost or stolen.
> 
> What you expected to happen
> I expected there to be a spare spade in each botanist locker
> 
> What actually happened
> the only spade in all of hydroponics in the crate, which isn't ID locked, so any butthead can just steal such a high risk item easily.
> 
> Steps to reproduce if possible
> be botanist, look for spades.

### LINKED ISSUE #11746: Feature Request: Add playing cards to box
(WEB REPORT BY: rattletrap REMOTE: 172.93.109.202:7777)
There are nifty playing cards that spawn on the metaclub locker room and bar, it would be nice to see them spawn on box. Maybe in the bar, library, and fitness room. Assuming this would be a very simple addition.

### LINKED ISSUE #11813: Derelict MoMMIs on Metaclub don't have their "don't leave the station" law
(WEB REPORT BY: mayneez REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Basically derelict MoMMI doesn't have the law that forbids them from leaving the station
> 
> What you expected to happen
> I expected the MoMMI to have that law
> 
> What actually happened
> It didn't
> 
> Steps to reproduce if possible
> Spawn as MoMMI on metaclub, check laws

### LINKED ISSUE #11814: Wrong computers in Metastation's DJ Station backroom
(WEB REPORT BY: mayneez REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0f9616e623dcab5af936d4b15bc7f108fc8c9749 
> 
> General description of the issue
> DJ station on Metaclub has two solar control computers, instead of one solar and one power monitoring one, like other maps do
> 
> What you expected to happen
> Two different computers to be back there, to check power load and set solars, not one working and one not working solar computer
> 
> What actually happened
> Two same coputers, with one, where power monitoring one should be, not doing anything
> 
> Steps to reproduce if possible
> Just go to DJ station on Metaclub

### LINKED ISSUE #11884: ERT doesn't get magboots
How can they respond to emergencies if they can't even respond to zas

### PR DESCRIPTION
**Pull request by CptWad**
centcomfull
This time its better I promise
All special characters are corpses to be revived and taken over. I am told this is how you add mobs without breaking things.
other things
minimap
new layout of most of the shit
Wizard  stations now surrounded by void. Immershuns
wiz-tg
wizard-meta
Same somewhat goes for syndie bases which now feature fuller snow and bases. Nothing inside said bases but when you have mensons or thermals on your immershuns wont break. 
syndie-tg

updated ERT photo
ert

fixes #11884
fixes #11746
fixes #10910
fixes #10517 
fixes #10454 
fixes #7163 
fixes #7243 
fixes #11103 
fixes #10985
fixes #11814
fixes #11813
fixes #11101
fixes #10623
fixes #10222
fixes #11884

### CODE REVIEW

**Comment by CptWad** [comment]
goddamn it I forgot to cleanmap

**Comment by CptWad** [comment]
I swear byond maps are made of magic and tears

**Comment by whorena** [comment]
Either deff or metaclub has a really, really cool wizard hideout, I think we should make it the standard across all the maps. It's similar to this new one in that it's surrounded by all that weird aura-y stuff, but its like split into sections and there's a un-movable crying orb in one of them. 
Unfortunately the map renders don't show the centcomm renders so I can't remember exactly which of the two it is.

I like this though, a lot more comfy. Maybe people wont kill each other so fast so they get to relax on the pretty grass and stuff.

**Comment by CptWad** [comment]
its deff
I agree but I think its meant to be deff exclusive or something. Ill let someone else do it since my plans were mostly just immershun and admin bus nonsense. I guess I can do a part two where I do shit like that but this update is already big enough as is

**Comment by invoid9** [comment]
>magboots in ert gear area

[thumbsupemoji]
[hoorayemoji]
[bigsmileyfaceemjoi]

**Comment by whorena** [comment]
note: have you removed the access requirements from the booze machine? It always irked me when I got to centcomm and couldn't dispense any bottles. 
And I don't think the jukebox even works at centcomm, unless that was intentional, but it's a nice piece of fluff. 
With centcomm all fluffed out and stuff, I'd like to see it being used more.

**Comment by Exxion** [comment]
The booze machine is empty anyway, if memory serves

**Comment by Intigracy** [comment]
Please add a way to open the blast doors leading to the ERT shuttle.

**Comment by Skullyton** [comment]
Copypasting what an anon said in the thread: Hey wad 
ERT needs a stack of cardboard boxes for holding more shit if you din't move them under those extended emergency tanks there. It's always frustrating and often someone else empties and takes the existing ones before I can get one.
Couple empty backpacks to hold shit
Some extra toolboxes so everyone has tools and they can haul shit with the empties
Box of pdas for when admins flub


Some electrical toolboxes for wire
A lot more metal, and some more glass
Fuel tank and some large beakers
An engi-vend or at least a couple high-caps so they can get the ball rolling
3 soldering irons and 4 large beakers of sacid
A radsuit closet for handling the radiation heavy problems
3 or 4 gadget bags and a table with 10 of each basic stock part
4 Station bounced radios so they can talk
10 matter chips per RCD so we can actually fix shit with its horrendous cost instead of only getting to load 1 rcd and box the spare chip
4 boxes of flares
Breathe deep carts for the eng op so he can check distro and can compositions right away
They need a fourth pair of insulates

Sec man could use a taser for his belt
Holster so at least he can take the ion without immediately losing it or his backpack
Some robust pda carts
A rack with parts for 3 beepskies and another with parts for an ed-209

Med man could use some bicard pill bottles and iron bottles/pizza
a defib
sheet of plasma so he can at least ghetto chem some clonex and meat with some highcaps
Circ & parts for a defib wall charger
surgeon switchtool regular surgary tools, and the T3 surgical tools
2 boxes of monkey cubes
rollerbed
4 or 5 O- blood packs

Some closets and a crate or two to pack surplus supplies without having to wrench metal a closet.
A chute with a disposal outlet into the wall so they can stack solids like canisters and the scrubbers into a crate
A small room with 10 regular space suit ssi's or whatever they're called so they can bring suits for people in a errything is bombed emergency

**Comment by SarahJohnson489** [comment]
Edited it a bit and added some things I missed. 

Couple empty backpacks to hold shit
Some extra toolboxes so everyone has tools and they can haul shit with the empties. [!!VITAL!!]
Box of pdas for when admins flub


Some electrical toolboxes for wire. Like 12 actual ones. Wiring adds up fast.
A lot more metal, and some more glass
Fuel tank and some large beakers
An engi-vend or at least a couple high-caps so they can get the ball rolling
3 soldering irons and 4 large beakers of sacid
A radsuit closet for handling the radiation heavy problems. Like moving an energized shard or dealing with a transmitter
3 or 4 gadget bags and a table with 10 of each basic stock part
4 Station bounced radios so they can talk
10 matter chips per RCD so we can actually fix shit with its horrendous cost instead of only getting to load 1 rcd and box the spare chip
4 boxes of flares
Breathe deep carts for the eng op so he can check distro and can compositions right away
They need a fourth pair of insulates
Socket wrench
3 RPD's
8 Foam extinguishers for 2 each, (One is dogshit and gets you nowhere at a crawl)
2 water tanks
At least one advanced toolbelt so the eng op can actually hold shit. I doubt the ERT suit can even hold socket wrenches like the atmos suit
An unsecured O2 gas miner to setup a new distro immediately
Crate with an AME control unit, 5 jars of fuel, and 24 AME shielding or a crate of 3 Pacman T3 parts+circs, a superpac board and parts, a couple hundred plasma and 200 uranium. Having both and they pick could be good as well
A supply shuttle console circuit and a sec of rnd circuits and stock parts in the unlikely case of cargo, sec storage, mechanics, rnd and robo all getting btfo at once.
Box of teleporter parts
Vending machine with 10 telebeacons and 10 gps in its list for finding non-sec gps people and moving shit
4 hand tele's so the ops can rapidly move men and supplies across the station to wherever it's needed long as one guy functions as the switchboard
Firefighter Ripley with clamp, mech rcd, and foam extinguisher. Have near it, a fuel tank, water tank, and a crate with highcap cells in it for the pilot to load and go to town building a station
A crate with 9 micro-manips, 4 hyperwave filters, 3 high-powered micro-lasers, 2 subspace treatment discks, 1 subspace ansible, 1 wavelength analyzer, 1 ansible crystal, 1 subspace amplifier, circuits for a subspace receiver, bus mainframe, processor unit, subspace broadcaster, 3 cable coils, 20 metal, and a gadget bag


Sec man could use a taser, pepperspray for his belt
Holster so at least he can take the ion without immediately losing it or his backpack
Some robust pda carts
A rack with parts for 3 beepskies and another with parts for an ed-209
Couple rechargers that they can unwrench and bring with them


Med man could use some bicard pill bottles and iron bottles/pizza
A defib
Circ & parts for a defib wall charger
Sheet of plasma so he can at least ghetto chem some clonex and meat with some highcaps
Surgeon switchtool regular surgary tools, and the T3 surgical tools
2 boxes of monkey cubes
Rollerbed, a table parts, an rtable parts, and a scanning module
4 or 5 O- blood packs


Some closets and a crate or two to pack surplus supplies without having to wrench metal a closet.
A chute with a disposal outlet into the wall so they can stack solids like canisters and the scrubbers into a crate. The outlet's adjacent to and facing the wall with a wall behind the outlet too so they just bounce off and stack on top of the outlet so you can pack it all into a crate you launched with it.
A small room with 10 regular space suit ssi's or whatever they're called so they can bring suits for people in a errything is bombed emergency 
Add an oxygen only tank dispenser to take with the suits for an air's fucked emergency


3 cyborg skeletons or a stack of all the parts for them, 3 radio mmi's, 3 posi's
Crate of 3 hydro tray parts, 15 metal,3 diona pod seeds, hoe, bucket, 3 flashlights, wrench and a beaker of cryox
3-4 pAI cards for anyone who wants to operate with the ERT
Loose AI core circuit. the med op can get some plasteel from the eng op and get a willing AI quickly to coordinate and support


A bunch more space cleaner bottles, ammonia bottles, and boxes of cleaner grenades for mucus/viral sputum ERT
4 scythes, some more plant-b-gone bottles, boxes of weedkiller nades, some toxin bottles, and a goat crate or two for vines ert


W E B U I L D

B U I L D
U
I
L
D

BUILD THE EMERGENCY AWAY!

**Comment by SarahJohnson489** [comment]
Oh shit, uh, and a crate with 8 right robo arms, left robo arms and 7 right robo legs, left robo legs.  While you're not always lucky, you get the occasional guy you can bring back after amputation and some blood.

**Comment by CptWad** [comment]
there are no blast doors between the ERT and the shuttle.

**Comment by CptWad** [comment]
oh lord all those walls of text just loaded. 
I dunno about making the ERT being the absolute cure all. While their use can be great giving them all the fun toys can suck the fun out of antags
ill see about adding whatever I find reasonable. I do know SOME of those things I added already (pdas, boxes etc) but some other good shit is the bounced radios which yeah they do need.

**Comment by FudgePucker** [comment]
Yea but ERT is rarely called upon.
They are the ERT, they are supposed to be able to handle emergencies, not 4 dudes in minimal gear being sent on a suicide mission.
ERT would be called for more if they were better equipped.

**Comment by SarahJohnson489** [comment]
Yeah, I just figure since it's the only team for central command that would be responding to all the stations in range, they may as well have the gear to fairly effectively do their job. Especially the repair and treat dead/wounded parts instead of basically sending 4 hands in hardsuits to dig through wreckage for an hour to gather bits and bobs.  If they have the gear to make a real difference it'll make them feel more like an ERT rather than a find a cell for an apc and find a comms team.

**Comment by Durgen** [comment]
Your pull fixes this
(Ert not getting magboots)
https://github.com/d3athrow/vgstation13/issues/11884

**Comment by CptWad** [comment]
ert
Ok heres the ERT shit
I wont go any farther, WE SORT OF BUILD BUT NOT REALLY

**Comment by JMWTurner** [comment]
>Major Creed

but Creed is already his title

And he already has an equipment in Select Equipment (the "specops commander" or something one)

Just so you know I'm planning huge changes to ERT and Deathsquad after holochips get merged so I'll rebuild their areas from scratch.

**Comment by SarahJohnson489** [comment]
RIP station in a ripley.

**Comment by CptWad** [comment]
major creed is a major because thats an even rank for someone when compared to the others I put.
as for the deafsquid not much is changed, but if you want to look over corpse.dm and change what creed is wearing then go for it. Its faster to jump into creeds skin>rejuv than to >gamepanel>mob>wait for load>find carbon/human>right click human>select equipment>select officer>take over>varedit name onto human

I thought a camera comes with the courtroom if I am not mistaken

ERT changes are by request. You can make changes if you wish with your new holomap stuff. Just know that me and cluster both agree that bolting off the ERT and deafsquid from the main of centcom is for the better.

Nobody uses the holding pen. When they ever do, its not like they wont gib/teleport them back home

**Comment by JMWTurner** [comment]
>I thought a camera comes with the courtroom if I am not mistaken

Nope, the centcom's courtroom camera was moved over to the station's courtroom months ago.

**Comment by CptWad** [comment]
even thinking of camera code gives me a migraine
ill do it later ill be busy all morning

**Comment by JMWTurner** [comment]
All you have do do is place an /obj/machinery/camera/hearing preferably on the tile bellow the judge's desk. Also change the following vars:

**Comment by CptWad** [comment]
did the thing for the cameras
changelog too
also since I have been hogging the map files I decided to pay it forward and clear up a lot of the map tag(s)
fixed things and shit
#11746
#10910
#10517
#10454
#7163
#7243
#11103
#10985
#11814
#11813
#11101
#10623
#10222

Non-issues I request closure on, or they are already fixed
#10582
#8799
#8703

This is a bug not a mapping issue
#4002
#10587
#8698

This is a preferences issue, not a mapping issue. Two spawn points already exist.
#11258

This touches the sacred ancient navbeacon code and I ain't gonna try it. 
#8973

Needs more testing
#11634
#10932

**Comment by CptWad** [comment]
it compiles. Ill stop here before I break everything

**Comment by clusterfack** [comment]
Put those in the description not the title genius

**Comment by CptWad** [comment]
ok

**Comment by Kammerjunk** [comment]
:100: PERCENT TESTED

**Comment by CptWad** [comment]
ok I did test it but not extensively so like 50% but

**Comment by Kammerjunk** [comment]
It's just CentComm anyway

**Comment by Shadowmech88** [comment]
>fixes #10454 

What did this PR change on the Goonecode satellite? The OP makes no mention of any changes to anything other than the Centcomm Z-level.

**Comment by gbasood** [comment]
@CptWad 
are you the one I need to blame for mapping in emags and uplinks onto centcomm that runtime on roundstart because the config isnt loaded before their `New()` fires
#12347
or did someone else do this with all of the centcomms on every map

**Pull request merged**
