### PR TITLE
RPD hotfix

### PR DESCRIPTION
**Pull request by Kurfursten**
No longer attempts to make pipes when placed in a storage object

### CODE REVIEW

**Comment by PJB3005** [comment]
Really?

**REALLY?**

I'm 99.9% sure you were in IRC when I said that it's the cause of the `attackby()` of the backpacks and shit lacking a `return 1`, not the fault of the RPD.

And FYI: this also affects the RCD, tile painter, and RSF.

Bandaid / 10

**Comment by Kurfursten** [comment]
So I can move it up to RCD so they all inherit it. No big deal.

Why not have a bandaid solution instead of no solution?

**Comment by PJB3005** [comment]
*Sigh

The solution is to give the `attackby()` of storage items a `return 1`, that's it, what you're suggesting is a shitload of snowflake, the kind of code that makes bugs.

**Comment by Kurfursten** [comment]
One line of code "a shitload" does not make

**Comment by PJB3005** [comment]
Okay it's not a shitload, but it's still oldcode tier.

**Comment by Kurfursten** [comment]
Since PJB did it his way, I'll close this

**Pull request closed without merging**
