### PR TITLE
remove nervestation and related files from code

### PR DESCRIPTION
**Pull request by nervere**
## What this does
NerveStation was a briefly-lived map by Kane-f that was tested for two weeks (at most?) and swiftly taken out of rotation (because it wasn't good). It has been nearly 2-3 years now, the original author has deleted his GitHub account, and the map has never been played since its original short debut. It lives on as code bloat, so this PR removes it.

## Why it's good
The map hasn't been touched in forever except by people who maintain all maps with their general mapping changes. It has been abandoned and has not seen any work to fix the map's numerous outstanding issues. It would be best if no one further wastes their time trying to maintain this in their general changes to maps.

### CODE REVIEW

**Comment by Eneocho** [comment]
`>nervere fixes his map by deleting it`
poetry

**Comment by nervere** [comment]
its NOT MIIIINE AGGHGHHGH

**Comment by Eneocho** [comment]
i dunno man, if kanef made it'd be kanestation

**Comment by toomykins** [comment]
> i dunno man, if kanef made it'd be kanestation

or... fstation?

**Comment by Eneocho** [comment]
the secret is revealed...

**Comment by angryturnip** [comment]
If kanef made it why wasn't it called kanefstation?

**Pull request merged**
