### PR TITLE
Custom painting revival

### PR DESCRIPTION
**Pull request by ShiftyRail**
Re-opening of #29839. Honestly, I did absolutely nothing, this was already in a perfectly mergable state, the poor guy just featurecreeped it too much and lost his track.

I just salvaged what he did, got myself familiar with the UI so that I can debug it later on. I will try to add on the features jellyveggie wanted his painting thing to have in the future but right now this is simply too good to pass up.

I also corrected a few errors with the icon. The painting brush is a disgusting downsized google image search. Someone please make a better one.

Palette added.

Original PR body:

Customized player made paintings, You might remember this from 2-4 months ago from positng on the thread.
You can now build a variety of blank canvases using a stack of wood: 
* Small: 2 stacks, as usual.
* Portrait: 3 stacks. Wide as a small painting, and about as tall as a wall
* Landscape: 3 stacks. Portrait but rotated 90 degrees.
* Large: 5 stacks: covers nearly the entire wall.

showcase
Untitled
New blank canvases side by side with some existing paintings for comparison.

Onto the painting UI:
* Pick a color to paint with from the little colored squares, the big colored square is your active color. 
* Modify opacity (0 to 1) for better control on how much paint is applied
* Colors mix using the RYB formula:  blue and yellow makes green and all that
* You can name, describe, and sign your paintings on the Info tab
* Like piano songs, painting templates can be imported and exported through the Import tab. A "Help" tooltip explains how the templates are structured.
* Once you've imported a template, you can use it on the Template tab. Click on a color region to paint the entire region with your desired color and opacity. You can move any regions you're done with off the list.
* Templates are merely that, properly matching the intended result is up to the player's ability and resources. It's also useful in that, say, if there's a series of arrow templates you can choose wether to paint the arrow green or blue instead of white.
* When done, press Save changes for your painting to be saved onto the canvas. Make sure to do this between paining tool changes (eg. press save before switching from the red crayon to the blue crayon).

crayon

Use a painting tool on a canvas to start drawing, colors and painting opacity available to you will depend on your tool of choice:
* Pens: you'll only have the one color of the pen available to you: Black, red, blue, whatever. Maximum opacity is reduced to 15%.
* Crayons: Crayons have two colors available to them and same max opacity as pens. Reminder that you can use rainbow crayons in hand to customize said colors
* Painting brush: New item, built using a stack of wood. Holds a single color, can use 100% opacity. Use on a reagent container to take on it's reagents' color when painting, basically a color picker. Use on a container with water, space cleaner, or paint cleaner to clean the brush.
* Palette: Held in hand when painting with a brush, adds it's colors to those available while painting. Use a brush on it to mix your custom color palette into it.

Caveat: The whole thing works off the canvas API, unavailable to Internet Explorer 8 or older. Meaning, **you won't be able to paint if you're on Linux**. I think you can still paint through the Template tab, but I'm not entirely sure. 
Sorry.

:cl:
 * rscadd: (jellyveggie) Staff shortage has prompted Nanotrasen to broaden our horizons: Fine Arts graduates are now welcome! You may now be able to expect crewmates to know how to use a crayon on a canvas.
 * rscadd: Build a blank canvas using a wooden stack, current sizes are: Small, Landscape, Portrait, and Large.
 * rscadd: Use a painting tool on a canvas to start drawing: Pens, crayons and brushes work.
 * rscadd: Build a brush using a wood stack, and dip it on a reagent to take on it's color. Order some paint from cargo, or paint with blood and orange juice.
 * rscadd: Like piano songs, you can import and export painting templates for later use. However, actually managing to match the template's expected result is up to your ability and resources.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
we need an aisle

**Comment by ghost** [comment]
oh hey thanks for getting around to this, i cant into our UI code too much aside from calling a popup browser datum on things so i got nothing done.

**Comment by wotisjanitor** [comment]
i mean easel!!!

**Comment by ShiftyRail** [comment]
I don't know why Line fails, the thing it is complaining about exists in the repo. Maybe a CI issue?

**Comment by ShiftyRail** [comment]
This is in a mergeable state. I will attempt to get a palette working this evening - I don't believe it will be too hard.

I would really appreciate if something contributed a sprite for the easel. Fun fact, in French we call it a chevalet.

**Comment by ghost** [comment]
if it doesnt work on linux it probably wont work on virtualbox win7 vms either

**Comment by ShiftyRail** [comment]
image

**Comment by Kurfursten** [comment]
People like the palettes, you should add a way to get them

**Pull request merged**
