### PR TITLE
Fixes corpse spawners showing on crew monitoring computer + more corpse spawner features

### PR DESCRIPTION
**Pull request by unid15**
- Corpses from corpse spawners (like those on the clown roid) no longer show up on the crew monitoring computer because of suit sensors
- Added some cool parameters for corpse spawners, now they can create husked corpses, corpses with various types and amounts of damage (instead of 200 oxy), corpses with random names, genders and appearances and items
  - Variables on spawners (corpseuniform, corpsesuit, ...) can be either paths or lists of paths. In the second case, a random path from the list is used
  - New obj/effect/landmark/corpse/civilian creates a (more-or-less) unique dead human being

### CODE REVIEW

**Comment by Probe1** [comment]
Nice work unid!

**Comment by Intigracy** [comment]
Nice work unid!

**Comment by ghost** [comment]
Nice work unid!

**Comment by ghost** [comment]
Cool stuff unid!

**Comment by Intigracy** [comment]
Skullyton you suck.

**Comment by Intigracy** [comment]
wow Skully ruined it

**Comment by Kitfox88** [comment]
FUCK DUNY

but COOL WORK

**Comment by Probe1** [comment]
BAN HIM FOR RUINING OUR SPECIAL MEME

**Pull request merged**
