### PR TITLE
Makes the life of powergame genetics harder.

### PR DESCRIPTION
**Pull request by PJB3005**
[bug]

So, due to ARRAYS START AT 1, the upper/lower bounds for SetSEState were completely wrong.
This means that mutagen would make EXTREMELY easy to identify blocks.

This is now fixed. Now a bad mutation can be ANYWHERE between 802 -> FFF, instead of always being either 801 or 802. Same goes for the other mutation tiers.

:cl:
 * bugfix: Reminded genetics code that ARRAYS START AT ONE. As a result, unstable mutagen will now actually randomize SE blocks properly.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
(The Genetics metaclub will remember this)

**Comment by SonixApache** [comment]
>PJB kills the gas chamber strats

I figured people wouldn't touch it because genetics is extremely tedious and unengaging, even *with* shortcuts. (In other words, balance out removing the shortcut with something nice, like an intended shortcut, new effects, or a complete rework of genetics to make it less shit)

Fix your 🆑 though.

**Comment by SNilWillIllShill** [comment]
Either burn Genetics to the ground and rebuild it from there, or stop removing a shortcut that, while unintended, is a necessary evil for current state of Genetics.

**Comment by PJB3005** [comment]
Hey man I'm just fixing an off by one bug nothing to see here.

**Comment by ghost** [comment]
You can't start to balance features before their bugs get fixed, this is a good first step and shows that tedium is a problem with genetics.

A solution for another PR could be making machine upgrades significantly lowering this tedium or even offering console "upgrade" cards that would speed up the process.

**Comment by ShiftyRail** [comment]
On the one hand, I wasn't aware the gas chamber was a bug and I actually thought it was just an unintended effect of an actual feature (Mutagen only triggering negative mutations.)

On the other hand, gas chambers were fun to see.

**Comment by aceedex** [comment]
Why tho

**Comment by Kitfox88** [comment]
FUCK GENECLUB NERVE STAPLE WHEN

**Comment by jknpj** [comment]
PR testmerged to the test server

**Comment by Sooose** [comment]
I support removing the gas chamber but this won't fix that problem. This will just make genetics much harder to do if bad genes won't activate until FFF.

**Comment by PJB3005** [comment]
> `This will just make genetics much harder to do if bad genes won't activate until FFF.`

That's not what this PR changes. This PR fixes the values assigned to SE blocks when mutagen activates them. Mutagen is supposed to pick random mutations and activate them, so it also has to set the SE block "above" the lower activation bound (`DAC` for powers yada yada) so that the mutation STAYS on.

Now it TRIES to pick a random SE value that is above the lower activation bound, but due to the bug fixed in this PR, the ranges for that were fucked. So instead of having the full range of SE values (activating a disability can set thee SE anywhere between `802` to `FFF`), it only ever picked `801` or `802`.

**Comment by Sooose** [comment]
I misunderstood your PR then, this is much better. Gas Chambers took all of the autistic fun out of genetics in the first place, I miss the days of watching medbay completely burn to the ground while you sit in your comfy chair with your fellow geneticist and kept taking autism syringes.

**Comment by ShiftyRail** [comment]
I don't believe sitting behind a chair pushing buttons is the kind of experience that should be encouraged in a multiplayer game based around player interactions.

**Comment by jknpj** [comment]
>I don't believe sitting behind a chair pushing buttons is the kind of experience that should be encouraged

Well, maybe genetics isn't for you? I do enjoy my chair-buckled multi-console genetics drifting.

**Comment by Sooose** [comment]
I specifically mentioned the fact that I miss doing genetics with other geneticists and teaching them genetics, shifty. Gas Chambers are just a way to get all major powers within minutes due to the fact that they're abusing a feature of mobs moving within smoke.

**Comment by ShiftyRail** [comment]
Fair points, there is indeed a teach/learn aspect of it I didn't consider.

**Comment by Hoshi-chan** [comment]
This was inevitable. Nobody should be acting surprised.

That being said, genetics is in desperate need of a rework, and until something better is, at the very least, being designed, if not coded, the gas chambers are a necessary evil.

**Comment by jknpj** [comment]
They aren't. Genetics wasn't designed or balanced to have all human dna mapped at 12:20. As a matter of fact, this won't kill gas chambers, but will make them a lot less effective.

**Pull request merged**
