### PR TITLE
Necrophage

### PR DESCRIPTION
**Pull request by MadmanMartian**
Silly idea for an alien antag type. What is it? We don't know.

 - Necrophage
 - Rather than moving under things like legs, lets loose a vine to pull itself in the direction it wants to go, or to pull things towards it.
 - Consumes organic material, to either improve itself, or duplicate itself
    -One idea was to evolve the ability to ventcrawl, or have it as an initial power
    -Harden self. Consume biomass at half the rate, but gain armor
    -More vines.

Currently a lot of the stuff is placeheld by slimecode (HUD, physical interaction, etc.). Will remove as we develop the idea further.

Ideaguys welcome.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Give it an end-goal

**Comment by Arthurdentist** [comment]
https://www.youtube.com/watch?v=L7SkrYF8lCU

**Comment by ddolll** [comment]
Ventcrawl + grows by eating people is an amazing recipe for a silent station depopulator.

**Comment by Coxswain-Navigator** [comment]
Well a necrophage would consume dead organic tissue, so perhaps we could take some ideas from the thing (assuming we don't do that for ling) that they would primarily absorb corpses, maybe a bonus for husked corpses. This would give medbay and the chef/chaplain an actual reason to properly dispose of corpses. Perhaps it could be more of a zombie thing, with powers based on how it died. I'm going to need more to work with to give you the idea of a complete antag. It could even be some sort of mushman antag, if you want to put those fun guys into not-so-fun use.

**Comment by SonixApache** [comment]
blood gun

**Comment by KingofHONK** [comment]
Ventcrawler that moves @ walking speed. Slowly eat peoples feet off if they stand on or maybe even adjacent tiles for too long. Simple yet effective. people can still crawl away of course. Perhaps it could upgrade its abilities and be able to eat a leg off from the vent, or even hands. 

Can spend points to lay an egg in corpses that have been left out and make even more of the ankle biting assholes, makes a gibbed mess so an MD might look in morgue and discover it. Give a corpse a MedHUD icon where it shows an infected corpse similar to how facehugged people have.

Counters could include: engineers/atmos techs can with t-ray scanners to track down. Vent welding could always be an option. Use chems on your shoes to poison them. Make it incredibly weak outside of a vent so if it gets caught out it will likely perish. Make them low low hp so something like an IED would take them out inside of a pipe.

**Comment by MadmanMartian** [comment]
Update:
 - Ventcrawl added, calls updatemove where appropriate
 - The vinewhip is now called on RangeAttack, less buggy that way
 - Ventcrawl's ventcrawl_remove is now called after moving the person out of the pipe, rather than before they're removed from the pipe

**Comment by Hoshi-chan** [comment]
Sounds like a good place to start for reworking/remaking changeling. Start as an amorphous ball of biomass, yank yourself around with tentacles (like hookshots), crawl through vents, consume corpses and other small shit. Once you gain enough mass, gain the ability to locomote yourself more efficiently, imitate crewmembers whose bodies you've consumed, transform parts of your mimic body into weapons, et cetera. 

With enough mass, you can also duplicate yourself by sacrificing half of your biomass to recruit a ghost to serve as a new necrophage, or, if threatened, split a piece of yourself off, which can retreat into a vent while your old body continues to exist as some sort of simple mob; it'd keep you alive, but at the expense of most of your amassed biomass

Rather than being a strictly stealth antag, despite requiring a sort of subtlety, absorbing bodies should be fast, noisy, and violent, and leave a bloody mess. It should be pretty obvious that a necrophage is aboard, not two hours of silence as everyone disappears without a trace. In lieu of stuns, sleep, or other oft-maligned methods of takedown with zero counterplay, maybe give it disarms and very short knockdowns, so that fighting it is a proper scrap, not "Oops, I got within one tile, now I'm dead."

That's all I've got.

**Pull request closed without merging**
