### PR TITLE
Fixes Give Random (Head) Job

### PR DESCRIPTION
**Pull request by bear1ake**
https://github.com/Baystation12/Baystation12/pull/12605
https://github.com/tgstation/-tg-station/pull/16567

### CODE REVIEW

**Comment by CptWad** [comment]
Hmmm
I guess its a good fix
I mean having less heads of staff is bad but I rather not get HoS every game just because I have it on low

**Comment by Shadowmech88** [comment]
@CptWad 
I don't think that's what it means.

It seems that originally, the "Give random job if preferences unavailable" option was intended to exclude head jobs from the possible random job it would give you, so players that didn't choose head positions wouldn't randomly be made into heads.

If you have a head position that isn't set to "never" though, I believe it will still take higher priority over non-head jobs during normal job assignment.

**Comment by CptWad** [comment]
oh alright then

**Comment by bear1ake** [comment]
@Shadowmech88 look at this:
https://github.com/Baystation12/Baystation12/commit/c02a6b2e9a613105d6c61efa3c81cbcaaf1bd674

**Comment by Probe1** [comment]
I've seen more than a few people bitch about this happening and I couldn't figure out the root cause.  It's a smart change to be honest.

Also it SHOULD be working already but the code was broken and no one realized/cared to investigate and fix.

**Comment by clusterfack** [comment]
Thanks

**Pull request merged**
