### PR TITLE
Adds a lizard pet

### PR DESCRIPTION
**Pull request by unid15**
He is lizard and his name is Wizard

:cl:
 * rscadd: The captain's office now has a pet lizard. Sprite is courtesy of @Blithering

### CODE REVIEW

**Comment by jknpj** [comment]
AI upload for maximum meta

**Comment by FudgePucker** [comment]
Shuttle has been called. Reason: Wizard in AI core

**Comment by Blithering** [comment]
I'd say make him randomly blink around the station, just like a real wizard

**Comment by SkowronX** [comment]
did you seriously just copy paste the wizard antag icon onto a lizard sprite

**Comment by Shadowmech88** [comment]
Could just add it to the wizard's den.

**Comment by yclatious** [comment]
If it isnt the wizards pet, you fucked up.

**Comment by AutismSpider** [comment]
name him/her King Gizzard and slap him in the wizards den

**Comment by N3X15** [comment]
Please mark WIP shit as WIP.

**Comment by Blithering** [comment]
lizwiz

**Comment by Fruktlimpa** [comment]
MERGE WHEN?

**Comment by SkowronX** [comment]
ded

**Comment by chaoko99** [comment]
Cannot merge.

**Comment by nuklearcellphoneg** [comment]
But why not Lizzie

**Comment by nuklearcellphoneg** [comment]
The Wizzie

**Comment by SonixApache** [comment]
repair this
or just remove the mapping aspects and add those later

**Comment by chaoko99** [comment]
Porting this elsewhere at some point.

**Comment by Shadowmech88** [comment]
@unid15 do you plan to fix the conflicts on this?

**Comment by SonixApache** [comment]
just kill the mapping aspects

**Comment by Fruktlimpa** [comment]
Forever in coding limbo. RIP lizard.

**Comment by gbasood** [comment]
that hat is huge
please

**Comment by PJB3005** [comment]
But that makes it better!

I'm not sure how much more you can shrink the hat without it becoming unrecognizable though.

**Pull request closed without merging**
