### PR TITLE
Fixes mousetrap assemblies not working for grenades (#4227)

### LINKED ISSUE #4227: Mousetrap assemblies don't work on grenades
They work by themselves when dropped on the floor, but when attached to a grenade they won't trigger anymore.
Untested on bombs

### PR DESCRIPTION
**Pull request by 9600bauds**
Fixes #4227
ss 2015-05-07 at 10 27 51

### CODE REVIEW

**Comment by Iamgoofball** [comment]
finally :+1:

**Comment by IratePirate** [comment]
You glorious son of a bitch.

**Comment by d3athrow** [comment]
Not merging unless you make the assembly apparent.

**Comment by 9600bauds** [comment]
?
How do you mean?

**Comment by d3athrow** [comment]
It needs to be obvious that its a mousetrap assembly.

**Comment by 9600bauds** [comment]
None of the other assemblies are shown on the grenade or bomb sprite. This isn't some minute detail that I forgot, this is just a hotfix to get things working as intended.
If you're telling me that bombs not displaying what assembly they have attached is an issue, that's fine, I can get behind that. But you're pinning the responsibility of fixing that on me, and trying to get me to bundle it with a hotfix. There hasn't been an open issue or any discussion on assemblies either, so that I would have even known you might have wanted this prior to making my PR. And it's not like there is some huge balance issue that would keep this specific hotfix from being merged, because not only prox sensors are pretty much better and more readily available than mousetraps, but mousetrap assemblies already work on BOMBS.
Again: I didn't make grenades, I didn't make grenade assemblies, I have never worked on either prior to this hotfix. You're telling me to make a new content system for displaying assemblies on primed grenades, which is content I might not know how to do, want to do, or be able to sprite. If you want me or someone else to try, you can bring up the issue prior, but why is this hotfix getting held up over this? Didn't it come up when mousetrap assemblies were fixed on bombs a couple of weeks ago?

**Comment by Iamgoofball** [comment]
Also @d3athrow do you even mean the assembly you hold in your hand or a finished grenade with a mousetrap assembly

**Pull request merged**
