### PR TITLE
VOX Update for Feb 22 2021

### LINKED ISSUE #28800: VOX Wordlist Requests
Long overdue, I know.

This is an issue for requesting all the words you want in the next package of VOX words. You can also list pronunciation errors so I can (try to) fix them.

## Known Issues
Words with bad pronunciations I know about but can't fix due to complex bugs in the voices:
* bag
* go

## Already Added

```
sound/AI/vox_reminder17 = Reminder: Do not take gifts from Santa Claus.  He is a registered sex offender. Please report him to security if seen.
sound/AI/vox_reminder18 = Happy Vox History Month!
```
(Considering making seasonal announcements and moving them to their own lists)

## Rurus
Because they apparently need to be said, and because I don't want to host this shit on gitgud.  Their upload speeds are atrocious.

* No slurs
* No lewds
* No illegals in the US of Free Speech
* If it's a sound effect, link to the sound effect and what the `_id` should be.
  * If you want it cropped out of a larger video/sound, make clear which section should be extracted or do it yourself with youtube-dl + audacity.
  * Bear in mind that sound effects are put through a series of bandpass filters and echoes so it sounds like a PA.  This will make them sound shittier *by design*, and not all sounds can go through this process without being rejected for shitty outcome.

## Current sounds
* https://github.com/N3X15/ss13-vox/tree/master/wordlists
  * You can also make PRs there.

## Timeline
* Due to commitments during the week of the 20th, submissions will be closed on the 19th.

[sound]
[vox]
[discussion]
[sound]

### PR DESCRIPTION
**Pull request by N3X15**
Added a bunch of new words.  This PR does not include OTF support.

Final update before we switch to [OTF](https://github.com/N3X15/ss13-vox/commit/48b0ba9a51a7bee431ccfd86bfb2cae876d80b82), which I should have a PR for next monthish.

## Summary

Adds a bunch of words from #28800

## Related

* Closes #28800 

## Changelog

:cl:
- rscadd: Added a bunch of new words to VOX announcements.

### CODE REVIEW

**Comment by N3X15** [comment]
I should note I will be out of town from the 23rd for about a week (depending on a few things), so I may not be able to respond.

**Comment by boy2mantwicethefam** [comment]
Door stuck is the best emote though

**Comment by Eneocho** [comment]
Downboated since it removes the all time classic door stuck.

**Comment by Kurfursten** [comment]
I've moved this to draft as N3X has a personal family emergency and can't work on it right now. Don't expect for him to reply to comments until he gets back.

**Comment by gurfan** [comment]
what's fucked about doorstuck

**Comment by cloutcode** [comment]
not to take advantage of a man who's dealing with family issues but MEN IT IS TIME TO RALLY OUR FORCES IN DEFENCE OF _DOORSTUCK

**Comment by N3X15** [comment]
Finally home.  

Re-added `_doorstuck`. Was removed because of [this comment](https://github.com/vgstation-coders/vgstation13/issues/28800#issuecomment-774517135) on the request issue, and listening to it on my laptop.

**Comment by DamianX** [comment]
cringe

**Comment by PrimeDSS13** [comment]
Make sure to edit the changelog.

**Comment by N3X15** [comment]
> 
> 
> Make sure to edit the changelog.

Fixed

**Comment by Eneocho** [comment]
> 
> 
> > Make sure to edit the changelog.
> 
> Fixed

Your summary still says you removed _doorstuck.

**Comment by N3X15** [comment]
> 
> 
> > > Make sure to edit the changelog.
> > 
> > 
> > Fixed
> 
> Your summary still says you removed _doorstuck.

Summary shouldn't be consumed by the changelog bot, but fixed nonetheless.

**Pull request merged**
