### PR TITLE
Removed floorlength braid tripping

### PR DESCRIPTION
**Pull request by RFultra**
Cmon guys
its the current year

did i do this right?

### CODE REVIEW

**Comment by AI-Is-Rogue** [comment]
>Removed floorlength braid tripping

>EmiliaMcWaifushitter

🤔

**Comment by kol1th** [comment]
Next PR: 

>Tajaran are now playable, and no longer valid.

**Comment by JustSumBody** [comment]
SLIPPERY SLOOOOOOOOOOOOOOOOOOOOOOOOOOOPE

**Comment by Aurx** [comment]
BAN
HE

**Comment by RFultra** [comment]
Guys please act like adults here
this is a safe space

**Comment by Aurx** [comment]
NOT FOR YOU IT'S NOT

**Comment by 9600bauds** [comment]
I believe I've found a better solution
#13919

**Comment by 9600bauds** [comment]
you didn't even remove the flag define
:tada:

**Comment by RFultra** [comment]
implying I can actually code
I am just here because of the wyci memes

**Comment by Aurx** [comment]
BANNED
HE

**Comment by RFultra** [comment]
hmmmmmee
rude

**Comment by 9600bauds** [comment]
Why is this tagged controversial?
That's reserved for PRs with actual controversy!

**Comment by Probe1** [comment]
I don't know I was desperately trying to figure out what labels applied.

**Comment by Aurx** [comment]
I'd say to start with DO NOT MERGE and go from there.

**Comment by Probe1** [comment]
At this rate I'm going to have to remake the Aurx'd label.

**Comment by RFultra** [comment]
I don't see what is wrong with this PR
Why are you all so negative

**Comment by Aurx** [comment]
I'm not being negative.  
I'm completely positive this shouldn't be merged.

**Comment by Probe1** [comment]
Alright I'll play along but I'll close the PR afterwards.

1.  Silly waifu hairstyle was added with a caveat that it makes you trip.
2. Silly waifu player wants to remove that.
3.  Everyone laughs at silly waifu player.

**Comment by nuklearcellphoneg** [comment]
i want a custom label :(

**Pull request closed without merging**
