### PR TITLE
survival boxes adjustments

### LINKED ISSUE #4932: Add a bandage to the starter box
What kind of corporation sends people in with a tank full of oxygen in case there's no air, but not a single medical item in case they stub their toe?

Having a single bandage on board would help people not bleed out all the time.

### PR DESCRIPTION
**Pull request by Intigracy**
survival boxes are now named survival box
survival boxes spawn with single use bruisepack

changes path of box/engineer to box/survival/engineer, adjusted everywhere it's used accordingly
checked our 4 main maps (box, meta, deff, taxi), none of them use box/engineer so I don't have to edit the maps

removed partial pathing all over boxes.dm

fixes #4932

tested

### CODE REVIEW

**Comment by FudgePucker** [comment]
What about giving engineering boxes (the ones that engineers start with that have an extended emergency tank) an autoinjector filled with 3u antiradiation meds 2u antitoxin/a metal foam grenade for hull breaches?

**Comment by Intigracy** [comment]
I'd rather it remain things to help them survive rather than things to help fix the station.

the autoinjector is because /engineer is also used by miners, atmos techs, mechanics, and paramedics, and I'd rather not snowflake engineers having a unique box

**Comment by Probe1** [comment]
metal foam grenades are extremely good.

anyway it seems fine to me.  unneeded, but fine.

**Comment by gbasood** [comment]
> single use bruisepack

Can you change their names as well? Because sanity

**Comment by Intigracy** [comment]
Sure thing fam.

**Comment by Intigracy** [comment]
I did you one better, sood.

bandaid

**Comment by Intigracy** [comment]
:+1: great PR OP is a great guy

**Comment by Boxe** [comment]
merge when

**Pull request merged**
