### PR TITLE
Player spawn reworks

### PR DESCRIPTION
**Pull request by ghost**
[administration][bugfix]
image
image
Should also fix logging issues only showing players in the starting area as new player mobs in the above too.
Also tidies up wizard equip code to make it actually use outfit datums.
:cl:
 * bugfix: Active human mobs in the world are no longer teleported to their player pref job role on roundstart.
 * bugfix: New players no longer hear the AI bootup sound when the game starts with one.

### CODE REVIEW

**Comment by DeityLink** [comment]
I am grateful

**Comment by Kurfursten** [comment]
Did you take 30 commits to make this PR?

**Comment by DeityLink** [comment]
> 
> 
> Did you take 30 commits to make this PR?

It do be like that sometimes 
image

**Comment by ghost** [comment]
> Did you take 30 commits to make this PR?

The multi-Z one I did took 253, and pulse demons took 144

**Comment by SonixApache** [comment]
scream at the collabs if this is good to go
also hearing the AI spawn is a feature

**Comment by Eneocho** [comment]
No longer being unable to hear the AI bootup sound is kinda sad. It was a good way to know if there was an AI at roundstart.

**Comment by ShiftyRail** [comment]
This broke everything

**Pull request merged**
