### PR TITLE
Revert "Revert "Merge pull request #23752 from MadmanMartian/from_hells_heart…"

### PR DESCRIPTION
**Pull request by SonixApache**
Reverts vgstation-coders/vgstation13#28435

### CODE REVIEW

**Comment by d3athrow** [comment]
y

**Comment by SonixApache** [comment]
i cannot think of a single good thing to come from `*dab`

**Comment by DrSnips** [comment]
Piss off. It was just voted back in.

**Comment by SonixApache** [comment]
it was gone for a good reason, your reddit upboats hold no sway

**Comment by Irradiation** [comment]
No sway except for the chicken himself merging it.

**Comment by juanototo2** [comment]
>SonixApache

>hates fun so much he goes against the word of fucking Pomf and effectively everyone else

Wow, what a fucking surprise

**Comment by boy2mantwicethefam** [comment]
Juanototo made such an atrocious comment I decided to upvote the PR out of spite

**Comment by DrSnips** [comment]
Screenshot_20200221-151835_Discord
Daily reminder that sonix is simply too smart and knows what's best.

**Comment by ghost** [comment]
I bet Sonix can't even provide one reason why a funny secret suicide emote is detrimental to the game.

**Comment by SonixApache** [comment]
@ancientpower Sure, here's a reason; it's a noob trap. 
I have proof of it; that one admin feedback / deadmin request or whatever thing about people farting and dabbing in a locker.

Again; there is nothing good about this addition.

**Comment by ghost** [comment]
It gives you a warning that you will be killed instantly, if someone clicks through that then they deserve to die.

**Comment by Kharkov72** [comment]
That's it. I'm tired of this, I will take down this fucking tranny metaclub once and for all. I'm going to the forums, and getting that faggot SonixApache banned if its the last thing I do.
Let me tell you my side of the story. The entire crew was in a locker. Another guy was dabbing so I did it and got killed. Admin refused to revive me despite the fact the crew was having fun dabbing and farting in a locker. So if you put yourself in an admin's position how would you respond to this? A round where literally nothing is happening everyone is goofing off and having fun, and one guy makes a mistake.
Would your revive him? Or let him be taken out early for the rest of the round? Personally, I would revive him for the sake of the round being fun. Even if he was a target of an antag, he would have been back naturally anyway. That faggot SonixApache should be deadminned for not reviving me, and if you do not the tranny metaclub will crumble when I strike my keyboard with my fists.
Soon, you will all see.

**Comment by d3athrow** [comment]
That's it. I'm tired of this, I will take down this fucking tranny metaclub once and for all. I'm going to the forums, and getting that faggot SonixApache banned if its the last thing I do.
Let me tell you my side of the story. The entire crew was in a locker. Another guy was dabbing so I did it and got killed. Admin refused to revive me despite the fact the crew was having fun dabbing and farting in a locker. So if you put yourself in an admin's position how would you respond to this? A round where literally nothing is happening everyone is goofing off and having fun, and one guy makes a mistake.
Would your revive him? Or let him be taken out early for the rest of the round? Personally, I would revive him for the sake of the round being fun. Even if he was a target of an antag, he would have been back naturally anyway. That faggot SonixApache should be deadminned for not reviving me, and if you do not the tranny metaclub will crumble when I strike my keyboard with my fists.
Soon, you will all see.

**Comment by Kammerjunk** [comment]
Revert "Revert "Revert "Merge pull request #23752 from MadmanMartian/from_hells_heart…"

**Comment by DrSnips** [comment]
That's it. I'm tired of this, I will take down this fucking tranny metaclub once and for all. I'm going to the forums, and getting that faggot SonixApache banned if its the last thing I do.
Let me tell you my side of the story. The entire crew was in a locker. Another guy was dabbing so I did it and got killed. Admin refused to revive me despite the fact the crew was having fun dabbing and farting in a locker. So if you put yourself in an admin's position how would you respond to this? A round where literally nothing is happening everyone is goofing off and having fun, and one guy makes a mistake.
Would your revive him? Or let him be taken out early for the rest of the round? Personally, I would revive him for the sake of the round being fun. Even if he was a target of an antag, he would have been back naturally anyway. That faggot SonixApache should be deadminned for not reviving me, and if you do not the tranny metaclub will crumble when I strike my keyboard with my fists.
Soon, you will all see.

**Comment by ShiftyRail** [comment]
Sorry Sonix, but you have been dabbed on.

**Comment by DrSnips** [comment]
Pressing D to dab

**Comment by SonixApache** [comment]
every day we stray further from god

**Pull request closed without merging**
