### PR TITLE
New plant and reagent: Squash

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Adds a mutation for the pumpkin: Squashes.
image
Squashes work on all recipes that ask for pumpkin and are filled with Squash (the reagent).

The Squash reagent/drug is a double edged performance enhancer that makes you tackle better overall. 
Should a NON-dwarf consume it, they'll suffer some shortening pains (as opposed to growing pains) for 30 seconds, after which they'll turn into dwarfs as long as they have some squash in them, however, should they run out of squash, the sudden immediate growth to full size will shatter **_every bone in their body_**, unless their bones were hardened beforehand.

Squash can also be produced chemically by mixing equal parts Manlydorf, Degencalcium and Hyperzine.
## Why it's good
New content good, plants cool, new dangerous drugs for double edged sword decisions.
## How it was tested
Spawned in, made character a dwarf, took squash, tackled, waited to run out of squash, worked fine.
Spawned in, took squash, suffered the shortening pains properly, dwarfized, tackled, waited to run out of squash, regrew to full size, bones broke properly, worked fine.
Dosed pumpkin vines with mutagen, they mutated into squash vines, worked fine.

:cl:
 * rscadd: Squash plants! Mutate a pumpkin to get your very own squash. They are not as efficient at making nutriment, but are filled with precious Squash (reagent).
 * rscadd: The Squash reagent/drug is a double edged performance enhancer that boosts your tackling abilities. If consumed by non dwarves, they'll suffer brute damage for 30s before turning into a dwarf (as long as Squash is still in their system). If they run out of squash, the recoil from growing back to normal size will break every bone in their body, unless their bones were reinforced with Degencalcium beforehand. 
 * rscadd: The Squash drug can be manufactured by mixing equal parts Manly Dorf, Degenerate Calcium and Hyperzine.

### CODE REVIEW

**Comment by cloutcode** [comment]
i support this message

**Comment by SonixApache** [comment]
>meme chem that breaks all your bones

why
*why*

**Comment by angryturnip** [comment]
Funny, good sprite, but meme chem that breaks all your bones is bad

**Comment by Eneocho** [comment]
It's supposed to be a risky drug, unlike almost every other drug we have that do nothing of note as the side effect.
Also, that's how the original ideaguy suggestion was and I liked the suggestion enough to make it. It only breaks your bones, you suffer no brute damage otherwise. 
And let me remind you that we already have a chem that breaks all your bones almost instantly if misused (Degenerate Calcium), which is actually a component to make Squash.

**Comment by Blithering** [comment]
Is there a threshold for it? Can you put 0.000001u into a guys food and immediately break all his bones the moment its metabolised?

**Comment by Eneocho** [comment]
> Is there a threshold for it? Can you put 0.000001u into a guys food and immediately break all his bones the moment its metabolised?

Takes 15 ticks (30s) to reach the threshold, so no. During the first 15 ticks you receive a fair amount of brute, but no bone breaking. It's AFTER you pass the threshold that you're in the bone breaking leagues, though if you manage to harden your bones to their maximum hardness (via degenerate calcium) before running out of squash, your bones will survive unharmed.

**Comment by west3436** [comment]
Breaking all of your bones because you ate squash is very silly and will own players who think they're just making food with squash. I hate this, but I'll let @jwhitak have the final say.

**Comment by Eneocho** [comment]
Remember that Degencalcium is a thing already, and that it breaks your bones if you're under 30 brute. If you find you were dosed with squash you have until the effect runs out to reinforce your bones with Degencalcium to not have them break, and if you were dosed with too little Squash it works as a brute damage poison only, since you never reached the threshold. 
There are a lot of toxic chemicals in plants already, it's part of the fun as a botanist/chef to know what to and not to use when cooking (or use anyway if syndie).

**Comment by west3436** [comment]
> Remember that Degencalcium is a thing already, and that it breaks your bones if you're under 30 brute. If you find you were dosed with squash you have until the effect runs out to reinforce your bones with Degencalcium to not have them break, and if you were dosed with too little Squash it works as a brute damage poison only, since you never reached the threshold. There are a lot of toxic chemicals in plants already, it's part of the fun as a botanist/chef to know what to and not to use when cooking (or use anyway if syndie).

Degenerate Calcium is incredibly difficult to make; squash is a basic plant that wouldn't appear toxic since it isn't irl. This is like making pumpkins cause burn damage to people who consume them.

**Comment by cloutcode** [comment]
> Takes 15 ticks (30s) to reach the threshold, so no.

how many u is that

**Comment by Eneocho** [comment]
Currently? 0.75, but I can up that to 1u or 2u if that seems better.

**Comment by west3436** [comment]
Mixed support on this one and I still really don't love a basic vegetable like squash having these sort of effects. I'd recommend trying this again with squash as a simple food item which can be used in some unique dishes then make a mutated version of it with a silly name which has the bone breaking effects.

**Comment by Eneocho** [comment]
> Mixed support on this one and I still really don't love a basic vegetable like squash having these sort of effects. I'd recommend trying this again with squash as a simple food item which can be used in some unique dishes then make a mutated version of it with a silly name which has the bone breaking effects.

If I reopen this with that change, would you merge it?

**Comment by west3436** [comment]
> > Mixed support on this one and I still really don't love a basic vegetable like squash having these sort of effects. I'd recommend trying this again with squash as a simple food item which can be used in some unique dishes then make a mutated version of it with a silly name which has the bone breaking effects.
> 
> If I reopen this with that change, would you merge it?

Yes!

**Comment by Eneocho** [comment]
The intention behind having squash being like this instead of being a regular plant first is that squash and pumpkin are really close to being the same plant, and making a fully new intermediary plant solely to not have the toxins feels off to me, especially since the intention also was being able to use squash on recipes that called for pumpkin, meaning you'd have Pumpkin (normal), Squash (normal, functionally the same as pumpkin with only a sprite change, unwanted intermediary) and "Slammed Squash" (This implementation of squash, with the toxin).
What if I change the name to very obviously imply this ain't your everyday squash? That way the "basic vegetable" angle is taken into account, whilst also not adding a new, mostly useless, intermediary.

**Comment by west3436** [comment]
> What if I change the name to very obviously imply this ain't your everyday squash? That way the "basic vegetable" angle is taken into account, whilst also not adding a new, mostly useless, intermediary.

Sure

**Pull request merged**
