### PR TITLE
Fixes Some Sprites To Properly Fit Ayys

### PR DESCRIPTION
**Pull request by Optimism333**
## Some of these bothered me more than others... ##
But they were all pretty quick and easy to fix. Will do more if/when I have some time in further prs. But I think this takes care of some of the more obvious ones.

greysuitstuff

ayymasks

## What the pr does and why ##
- Fixes a couple of suit and mask items having bad fits on ayys. All the ones in the screenshots above are fixed. As a bonus, I also added a line of code so the mining rigsuit uses its proper grey sprite. It had one, it just wasn't using it.

[sprites]

:cl:
 * tweak: Fixes some mask and suit sprites so that they fit ayys properly

### CODE REVIEW

**Comment by wotisjanitor** [comment]
Could you fix bandanas as well? Like the ones you can get from the sec clothing locker. They don't fit grey heads at all

**Comment by Optimism333** [comment]
> Could you fix bandanas as well? Like the ones you can get from the sec clothing locker. They don't fit grey heads at all

Eh, okay. I'll look at them later today if I have some time

**Comment by Optimism333** [comment]
Fixed the muzzle and red bandana to have ayy-fitting sprites. I wanted to do the welding helmet and gladiator helmet too, but that will cause a .dmi conflict with my mothership vault pr, so I'll wait.

ayymasks

Edit: Come to think of it, the suits will cause a .dmi conflict with my mothership vault pr... crap.

**Comment by Optimism333** [comment]
Closing this for now. I'll save the sprites and open it again on a fresh branch soon.

As soon as there's no risk of a backwards .dmi conflict, anyways.

**Pull request closed without merging**
