### PR TITLE
Metaclub cargo disposal shortcut

### PR DESCRIPTION
**Pull request by Probe1**
dreamseeker_2017-01-14_18-23-33

Very short and sweet PR.  Cargo now has a shortcut to stuffing crates into disposals.

Closes https://github.com/d3athrow/vgstation13/issues/13450

🆑 

 * rscadd: Metaclub Cargo now has a shortcut conveyor to send crates into disposals without walking a circuitous route.

### CODE REVIEW

**Comment by Kurfursten** [comment]
It's not typical to have a conveyor belt that doesn't have plating under it, but it's not that big a deal. If you do decide to go back, though, maybe some warning stripes too.

**Comment by Probe1** [comment]
Sure.  I"ll change that tonight.

**Comment by Durgen** [comment]
this would be even better if you switched the directions of the shuttle belts.
currently the north belt unloads the shuttle, and the south belt loads the shuttle.

**Comment by Probe1** [comment]
I thought about that but couldn't decide if it was "too easy".

**Pull request merged**
