### PR TITLE
Adds the ability to search by fingerprint in medical records

### PR DESCRIPTION
**Pull request by PlausibleDeniability**
So from my experience playing detective, one of the most time consuming things I do is manually go through the medical record list checking for fingerprint hashes, this lets you search for the string directly, like the Name, ID or DNA.

My first time making a proper change to DM code, the way I've done this is most likely not best practice - gib feedback

Unsure why this isn't already a feature, may be a controversial topic

8Qeu6qSz0n

[qol]
[tested]

:cl:
 * rscadd: Medical Record software updated, you can now search records by fingerprint!

### CODE REVIEW

**Comment by RealestEstate** [comment]
Not controversial, I think we all just have been using ctrl-f

**Comment by N3X15** [comment]
You may want to `break` out of the loops when you find a match, otherwise it'll keep searching until it runs out of records to iterate.  Not really a big perf hit since this isn't triggered a ton, but it's a good practice to get into.

Also as noted in Discord, the double-parens aren't needed.

**Comment by PlausibleDeniability** [comment]
> 
> 
> You may want to `break` out of the loops when you find a match, otherwise it'll keep searching until it runs out of records to iterate. Not really a big perf hit since this isn't triggered a ton, but it's a good practice to get into.
> 
> Also as noted in Discord, the double-parens aren't needed.

Good catch, I've added breaks to the for loops, there's also two for loops surrounding on lines 501 and 519, should I be amending these to also break so it's consistent?

**Comment by Zth--** [comment]
> Unsure why this isn't already a feature, may be a controversial topic

It was intended, I don't remember the exact justification but it has to be somewhere in the code. Probably balance reasons

**Comment by Pancakemines** [comment]
It's because you search fingerprints on security records that's why you have both. I don't think the change matters either way but that's why it is like that. I guess someone decided it makes more sense for fingerprints to only be searchable in security records which kind of checks out. I don't know if it's in the code but it's specifically mentioned on the guide to forensics/in the detectives book.

**Comment by PlausibleDeniability** [comment]
> 
> 
> It's because you search fingerprints on security records that's why you have both. I don't think the change matters either way but that's why it is like that. I guess someone decided it makes more sense for fingerprints to only be searchable in security records which kind of checks out. I don't know if it's in the code but it's specifically mentioned on the guide to forensics/in the detectives book.

Ah, I am smol brain, didn't even know you could search for fingerprints in the sec records

**Pull request closed without merging**
