### PR TITLE
Alphabetizes all name files, doesn't remove/add anything.

### PR DESCRIPTION
**Pull request by Intigracy**

### CODE REVIEW

**Comment by ComicIronic** [comment]
Why are you taking names out?

**Comment by ultraplen** [comment]
> removing max as a male name

**Comment by ultraplen** [comment]
@ComicIronic most of the removed ones were added back in if you check the list of the added names

edit: a few were added back in

**Comment by 9600bauds** [comment]
Why are you removing names

**Comment by ComicIronic** [comment]
Why would you move names around

**Comment by Intigracy** [comment]
All the removed ones are dupes fyi.

**Comment by SysadminJeroen** [comment]
Why are you removing names?

**Comment by Intigracy** [comment]
I removed duplicates

**Comment by Intigracy** [comment]
w/e I'll just alphabetize it in this PR and remove dupes later

**Comment by clusterfack** [comment]
Hahaha holy shit do we really have a file with like thousands of names in it? Damn

**Comment by Intigracy** [comment]
1,502

iirc it's not even used

**Pull request merged**
