### PR TITLE
Turret code refactoring/trimming

### PR DESCRIPTION
**Pull request by ghost**
[tweak][consistency]

Standardises process into check_target() and get_new_target(), adds an actual gun to the base type, removes the area checks, makes popUp(), popDown(), process() and shootAt() inherited, and a bunch of other stuff I probably forgot.

Feedback very, very welcome.

:cl:
 * tweak: Turret code has been standardised and slimmed down greatly

### CODE REVIEW

**Comment by help-maint** [comment]
Can I break one of the AI's turrets to get the gun inside?

**Comment by ghost** [comment]
> Can I break one of the AI's turrets to get the gun inside?

Not sure if I should throw this in or not.

**Comment by Eneocho** [comment]
> 
> 
> > Can I break one of the AI's turrets to get the gun inside?
> 
> Not sure if I should throw this in or not.

Would be fun.

**Comment by Eneocho** [comment]
Does this fix that weird thing where if you subspace a turret or its cover out of its room it deletes itself?

**Comment by ghost** [comment]
> Does this fix that weird thing where if you subspace a turret or its cover out of its room it deletes itself?

It should

**Comment by Kurfursten** [comment]
Mapping conflicts

**Comment by kane-f** [comment]
> Mapping conflicts

Resolved

**Comment by ghost** [comment]
@Kurfursten 
> Mapping conflicts

Resolved

**Pull request merged**
