### PR TITLE
Robocop.mp3 Campfire rendition - lobby music

### PR DESCRIPTION
**Pull request by nervere**
## What this does
New lobby music, arranged by Nuklearcellphoneg.
Full file (github doesnt support sound files so here's a discord link lol):
https://cdn.discordapp.com/attachments/1021591979022364672/1134234426495225886/robocop_campfire.ogg
[sound]
## Changelog

:cl:
 * rscadd: Added new lobby music - Robocop.mp3 But You're Around A Campfire - arranged by Nuklearcellphoneg.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
I dunno sounds kinda weird

**Comment by nuklearcellphoneg** [comment]
To nitpick, Jonathan Dunn composed it, I arranged it.

**Comment by pedr69** [comment]
i'll upvote this when the lobby music stops playing at earrape volumes every round so i can turn it back on without going deaf

**Comment by nervere** [comment]
> To nitpick, Jonathan Dunn composed it, I arranged it.

Fixed.

**Comment by wotisjanitor** [comment]
next pr idea: remove darude sandstorm from the code

**Comment by SonixApache** [comment]
harmonica is great, progression is great
the slight echo is weird and doesn't really add much
the synth instruments sound bad, like they're from a 1990s keyboard for kids
theme feels unfitting for spess/snaxi

hold on to this till we get DesertStation

**Comment by nuklearcellphoneg** [comment]
> harmonica is great, progression is great the slight echo is weird and doesn't really add much the synth instruments sound bad, like they're from a 1990s keyboard for kids theme feels unfitting for spess/snaxi
> 
> hold on to this till we get DesertStation


Well how about a song about the clown instead https://youtu.be/6mAt73CtepQ it'll have like one minute of silence though

**Comment by Theophrastus1** [comment]
ScrapMetal.mp3 vibes

**Comment by Kurfursten** [comment]
Reminds me of Glitter Gulch mine. I don't think it's a perfect lobby song. Using it for a desert station isn't a bad idea.

**Comment by nervere** [comment]
Vote is split 50/50 so we'll save this tune for when someone gives us a desert map.

**Pull request closed without merging**
