### PR TITLE
Yet another batch of mapping stuff

### LINKED ISSUE #3691: [Box] tank storage unit items appear underneath tank storage unit
Tank storage units are the containers that hold large oxygen tanks and plasma tanks.  In the case of every single other tank storage unit an item that is removed from it appears on top of the storage unit.  In this single tank storage unit in telecomms, they appear underneath it and you have to either alt click or pixel hunt to find them.

Weird right?

image

### LINKED ISSUE #4598: !!PANIC!! waste and distro loops connected between telesci and medbay break room
panic
Oh god send help

### PR DESCRIPTION
**Pull request by ghost**
And here we go again :
- Fix broken distribution/waste overlap in Medbay Maint that caused the distro and waste loops to mix together. No idea who did it, but now it's fixed. Honk
- Re-introduce Medical E.V.A. Requested a trillion times, especially given that no-one cares for that room with a single N2 canister. I thought it was done already, but it wasn't. Now it really is
- Fix my recent changes to Mining. ALL airbridges now use catwalk and the Research airbridge's surroundings were cleared up so that it can be circumvented easily without a pickaxe. All Mech Bay stations are now outside of their stations and in their station's area
- Remove some double walls around cycling airlock areas in Mining, rework structure whenever applicable
- E.V.A now has 2 Plasteel stacks and 4 Metal stacks, up from 3-1. The Pod Bay no longer has Plasteel and now has 2 Metal stacks and 2 Glass stacks, up from 1-0
- Hazard a fix at the Telecomms Tank Storage
- Fix missing APC in ASMaint2 (yes there's two areas, as if I was supposed to know)

Fixes #4598
Fixes #3691

Changelog included

### CODE REVIEW

**Comment by ComicIronic** [comment]
Need images of Medical EVA.
Is it using the medical hardsuits?

**Comment by dylanstrategie** [comment]
It's using the suit dispensers, let me take a pic

**Comment by ComicIronic** [comment]
Are they the medical hardsuit suit dispensers?

**Comment by dylanstrategie** [comment]
Yes

**Comment by dylanstrategie** [comment]
eva_and_podbay

**Comment by PJB3005** [comment]
I'd get rid of that cobweb, also make sure you replaced the N2 floor with a normal one

**Comment by dylanstrategie** [comment]
>N2 Floor

What now

**Comment by PJB3005** [comment]
the floor of the vox EVA area you replaced was N2 flooring, which had no O2, make sure you replaced it with a regular floor

**Comment by dylanstrategie** [comment]
Fuck, I'll fix it as soon as possible, so likely tomorrow

**Comment by dylanstrategie** [comment]
Okay, I have checked, and as expected it is NOT a Vox/N2 floor

So the map is ready

**Pull request merged**
