### PR TITLE
Expands Emagged Cloner Options

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Emagging a cloning computer lets you change the corpse's species and name. Currently it only lets you pick from the more common species. This allows you to pick from almost every humanoid species, including grue, lich, and ghoul. 
Just seems more fun.

[tweak]

:cl:
 * tweak: Emagged cloners now have more options.

### CODE REVIEW

**Comment by gurfan** [comment]
if people want to be a ghoul they should have to perform dark radiation rituals and majik, not just use an emagged cloner

**Comment by ghost** [comment]
agree that grue should stay behind needing to get radiated to shit, it's cooler that way

**Comment by Dacendeth** [comment]
You cant even clone golems normally as they lack genetics to allow it so I feel like you shouldnt be able to make some pop out of the cloner.

**Comment by SonixApache** [comment]
:+1: to shroom, diona, muton
:-1: to the rest

**Comment by GreatBigFailure** [comment]
Grue, Ghouls and Golems fair enough, I see the reasoning. Why no skeletons though? Liches are I guess a little special but mechanically they're very, very shitty.

**Comment by Blithering** [comment]
It's fine with leches as they currently are, but I'd rather make liches less mechanically shitty, and not have to remove them again.

**Comment by GreatBigFailure** [comment]
> It's fine with leches as they currently are, but I'd rather make liches less mechanically shitty, and not have to remove them again.

Mostly unrelated to this PR but I've been wanting to do that for a while but just can't think of any way I think people would accept. Got any thoughts?

**Comment by Blithering** [comment]
>Got any thoughts?

TONS. But agreed it's off-topic for this PR, telegram me or ping me on discord an I'll dump my lich ideasguy pile on you.

**Comment by SonixApache** [comment]
skeletons are already available through genetics and it's a meme to clone people into them
liches are literally created through dark magic

**Comment by strawberrytan** [comment]
Grues are very powerful but this could be funny

**Comment by Arthurdentistss13** [comment]
I would just add Diona and leave it at that

**Comment by ghost** [comment]
remove grues, ghouls, slimes, and golems as those are all intended to be special species obtained through specific means

add frankensteins

**Comment by Kurfursten** [comment]
Negative after a week, try some other configuration of races

**Pull request closed without merging**
