### PR TITLE
Defficiency Wizard Den Change

### PR DESCRIPTION
**Pull request by Konater**
Magivend now stocks five of everything, slippers are magical. There are invisible walls everywhere to stop you from breaking windows and stepping onto a space tile. Everything is unsimulated. The eye acts like a fixed scrying orb so wizards can have a look at the station before jumping in.
wizden

### CODE REVIEW

**Comment by Probe1** [comment]
change em all

**Comment by Ephx1** [comment]
> The eye acts like a fixed scrying orb so wizards can have a look at the station before jumping in.

So basically the scrying orb is now useless on this map.
That's not to say it isn't a neat thing though.

**Comment by CptWad** [comment]
scrying orb gives you xray though, allowing you to cast some spells through walls

**Comment by Probe1** [comment]
eh it says it in the OP.  this ones fixed.  you can't take it with you.  The scrying orb can be used anywhere, anytime.

**Comment by ihadtoregisterforthis** [comment]
Mid term goal should be having one of those on the other maps.

**Comment by Imagebard** [comment]
Holy shit what

**Comment by CptWad** [comment]
d o p e

**Comment by Probe1** [comment]
ALL MAPS OR RIOT

**Comment by Shadowmech88** [comment]
^

This is definitely more wizard-y than the current default wizard den like we have on Box.

**Comment by Konater** [comment]
I can add it to box and meta if I ever find out how to use smartgit

**Comment by Probe1** [comment]
startingcodingwithsmartgit

**Comment by ihadtoregisterforthis** [comment]
Do not change Meta and Box wizard dens. Meta has it's custom den, and it's perfect. Box doesn't deserve changes, it's the vanilla map.
Change only Deff

**Comment by Konater** [comment]
Probe it's the pulling and applying commits stuff I can't do, if I wanted to update box I'd need to get that updated arrivals somehow

**Comment by Probe1** [comment]
yeah don't bother with this PR just open a new one after merge

@ihadtoregisterforthis I don't get what you're saying about Box.  Meta sure.

**Comment by clusterfack** [comment]
Download the new version of bleeding edge and then tell it to rebase onto that new version. It's that easy.

**Comment by Konater** [comment]
I rebase to head yeah?
hurf durf

**Comment by Kurfursten** [comment]
I think I liked it better with the space background than the blue void

**Comment by Shadowmech88** [comment]
I like it with the blue.

**Pull request merged**
