### PR TITLE
CE-only advanced RCD

### PR DESCRIPTION
**Pull request by ghost**
image

## What this does
Gives chief engineers their own advanced version of the Rapid Construction Device, as the normal one is already available from hacked autolathes.
Allows the reinforcement of normal metal walls into reinforced ones (2 matter units) and plating floors into reinforced tiled ones. (1 matter unit)
Holds 90 units instead of standard 30 and builds normal recipes twice as fast.

## Why it's good
Should encourage more building while giving the CE a unique item again.

## Changelog
:cl:
 * rscadd: Chief engineers now get their own advanced rapid construction devices, capable of reinforcing already existing floors and walls with an extended capacity of 90 units and building twice as fast.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Maybe don't put it on the desk at roundstart because anyone can break in and take it. Needing to research it adds more inter-department interaction. Or you could put it in the locker.

**Comment by ghost** [comment]
> Maybe don't put it on the desk at roundstart because anyone can break it and take it. Needing to research it adds more inter-department interaction. Or you could put it in the locker.

Locker sounds good.

**Comment by Kurfursten** [comment]
Sounds good but I am a little worried about the upgrade to r-wall feature being extremely robust. The rest sounds fine.

**Comment by BomberBro** [comment]
The CE's RCD should allow him to construct a little friend :)

**Comment by jwhitak** [comment]
Like the idea, but in practice I'm fearful that we're going to see rwall spam if people find out it exists. Also, can this device also deconstruct rwalls?

**Comment by Servalfang** [comment]
i wouldn't call it any more powerful then something like the RD's holotool when you crank it up, or the "literally cannot be fired illegally (usually)" lawgiver

**Comment by pedr69** [comment]
>max science before you can build fucking anything

i hate this
why not just have it need plasma 3

**Comment by Eneocho** [comment]
Good device, bad balance attempt with the plasma reinforced compressed matter. We don't need another snowflakey item with only one use. Just make reinforcing stuff into their plasma variant use a lot more compressed matter, say 3 wallsworth (since it takes like 3 normal walls of effort to disassemble an rwall).
Also, the RCD disassembling has been broken for a while now, disassembling small stuff should be cheaper (according to the code and wiki) than disassembling a wall, but disassembling anything costs 5 units in any scenario.

**Comment by Eneocho** [comment]
Give it a feature to construct reinforced plasma windows.

**Comment by ghost** [comment]
> >max science before you can build anything

It comes preloaded with matter, and there's spares in CE office

> i hate this why not just have the cartridges need plasma 3

Could reduce the research cost
 
> also i don't think the upgraded rcd's should be protolathable - all the other head of staff specific gear isn't

Only the cartridges for it are, I specifically made this because the normal one is on lathes to begin with.

**Comment by Eneocho** [comment]
Limiting its use to shit you can only get from a protolathe would ensure nobody ever uses it since getting shit from science is a chore by itself, let alone the alleged "engineering staff" mechanics. I insist, just make it use regular compressed matter but make it cost 15 matter to reinforce, that way building a complete reinforced wall would cost 20 matter, almost a third of the allotted 90 matter, balancing the R-wallspam with sheer cost.

**Comment by west3436** [comment]
Ditch the snowflake cartridges, there's no reason for them. Seems like you just want to keep them due to the gambler's fallacy with your spritework.

**Comment by Eneocho** [comment]
If the snowflake cartridges get merged I will immediately make a PR that removes them and just makes the reinforcement expensive. There's no goddamned reason to have snowflake single use items when the regular cartridges would work.

**Comment by luigil101** [comment]
the purple looks nice so we could just keep the purple sprite in the tool but use normal matter

**Comment by ghost** [comment]
> the purple looks nice so we could just keep the purple sprite in the tool but use normal matter

I have to make it look unique somehow, even if I decide it should be better to do away with the plasma cartridge stuff.

**Comment by ghost** [comment]
> Like the idea, but in practice I'm fearful that we're going to see rwall spam if people find out it exists. Also, can this device also deconstruct rwalls?

Not yet, worried this would make the PR more contested, will add separately

**Comment by Eneocho** [comment]
>Not yet, worried this would make the PR more contested, will add separately

bruh what, just make it so you can "unreinforce" a wall for the same cost of reinforcing a wall (which should be 10 regular matter, so building and reinforcing 6 walls costs your whole 90 regular matter)

**Comment by ghost** [comment]
Finally removed the seperate cartridge type stuff since it seemed more unpopular anyways @Eneocho @west3436

**Comment by jwhitak** [comment]
Maybe unpopular but I liked the double cart look, even though the unique carts are gone.

**Comment by ghost** [comment]
> Maybe unpopular but I liked the double cart look, even though the unique carts are gone.

It looked like something uncomfortable to actually hold though.

**Comment by WindowsErrors** [comment]
the AI watching helplessly as two cargo workers with RCDs completely seal the entire security hallway in less than a minute

image

**Comment by Eneocho** [comment]
They'll need hihg intenstyty carogneering to get the fancy RCD to trap sec.

**Comment by Eneocho** [comment]
Does the advanced RCD emit sparks? I feel like it shouldn't, to reinforce the idea of being the better version.
Also, are you gonna add an unreinforcing floors/walls mode anytime soon?
A module to reinforce regular windows into their plasma variant would be nice too, and would fit as well with the floor/wall reinforcing.

**Comment by pedr69** [comment]
advanced piper when

**Comment by Eneocho** [comment]
Advanced Piper that comes with the benobiology upgrades by default.

**Pull request merged**
