### PR TITLE
Revert twitchchat memes

### PR DESCRIPTION
**Pull request by Intigracy**
Reverts d3athrow/vgstation13#9198

### CODE REVIEW

**Comment by Intigracy** [comment]
All good.

**Comment by Boxe** [comment]
memes

**Comment by ihadtoregisterforthis** [comment]
Can't it be left commented out instead?

**Comment by Intigracy** [comment]
meme emoticons might get added for ooc at some point

**Comment by gbasood** [comment]
I thought someone wanted to add an admin toggle for them

**Comment by PJB3005** [comment]
RIP

**Comment by ihadtoregisterforthis** [comment]
ripepperonis

**Comment by CptWad** [comment]
aww I was gonna make ss13 themed emotes
rip indeed
:broken_heart:

**Comment by Intigracy** [comment]
```
meme emoticons might get added for ooc at some point
```

**Comment by ihadtoregisterforthis** [comment]
`riPepperonis`

**Pull request merged**
