### PR TITLE
Gno Gnomes

### LINKED ISSUE #31452: Remove fetish content from Island Station
Now on GitHub™, just like the admins like it.
Link to the original forum thread: http://ss13.moe/forum/viewtopic.php?f=49&t=6058

It recently came to my attention that our fine codebase and our fine server have been sullied, defiled and tainted. You see, recently a person called "BurntDevil" (a player, admin and mediocre mapper on this fine server) has added his map "Island Station" to our map rotation.
This map features a small garden area, slightly south of the medical bay, containing a punching bag. This item features a modified sprite. Furthermore, there is another modified item in aft-port maintenance, near the solars.

The problem lies within these two items, here you can see them pictured.
image
image

You, an observant gentleman, might suggest that these are merely generic gnomes and not fetish content. While that is true at first glance, there is some context that the /vg/ playing gentleman must consider before reaching a verdict on these gnomes.
I would have no problem with these if they were created by somebody else (although the assistant gnome is quite similar to the assistant miniature figurine that is already in our codebase and thus not really necessary to add to the game), but sadly these sprites were "drawn" by the aforementioned player, admin and "mapper" BurntDevil.
BurntDevil is quite notorious for his sexual deviancy, especially in regards to gnomes. I have compiled a small album of images, showing BurntDevil posting his sexually suggestive sprites of gnomes on the /vg/station Discord server or simply stating his sexual attraction to these fictional creatures.

> amount of gnome messages
> **Here you can see the amount of messages containing the word "gnome" BurntDevil has posted to the /vg/station Discord.**
> 
> gnome woman sprite
> **A "gnome broad" in a revealing dress, crated by BurntDevil**
> 
> tiddydress gnome
> **More of the "gnome broad", this time titled "tiddydress gnome"**
> 
> gnome gif
> **An animated .gif created by BurntDevil, showing the "gnome broad" aka the "tiddydress gnome"**
> 
> hottub gnome
> **A female gnome in a bikini sitting in a hot tub. Apparently created by BurntDevil for another gnome lover.**
> 
> i would if possible wow gnome
> **BurntDevil voicing his urge to have sexual intercourse with a female gnome from another video game.**
> 
> nigga i'd fuck a gnome
> **No comment needed**

**Now you might say, how are these related to the gnomes found on Island Station? Well...**

burntdevil showing gnome collection
gnome collection circle

If you take a look at the circled gnome sprite, you can clearly see that it is the same as the one found in the garden area on Island Station. This sprite is literally in the same file as his other fetish sprites such as the "tiddydress gnome".

Now tell me, gentlemen of /vg/station, do you truly want gnome sprites, created by a man with a gnome fetish, on your server? A man who has created some vile fetish images of said creatures? I say, do not enable this behavior, as it might spiral out of control. Today it is a generic gnome sprite, tomorrow it is the "tiddydress gnome" added to your server.
I request the removal of the two gnome sprites from Island Station.

Thank you for your attention, gentlemen.

**PS:**

Island

### PR DESCRIPTION
**Pull request by Kurfursten**
closes #31452

Deleted 2 gnomes from Islandstation

🆑 
* tweak: Central Command has recalled all lawn gnomes from Islandstation.

### CODE REVIEW

**Comment by Kromkar** [comment]
Ho ho ho ha ha ha ho ho ho he he ha

hello me old chum
Im gnot a gnelf
Im gnot a ganobblin
Im a gnome and you've been gnomed!

**Comment by SonixApache** [comment]
not worth immortalizing

**Comment by ghost** [comment]
replacing one shit reference with another, what's the point

**Comment by ShiftyRail** [comment]
In french it's called ciseaux, which sounds a lot like a commonly thrown around epithet for such cases

**Comment by Eneocho** [comment]
If the scissors cut through threads with ease, shouldn't it be on the locker room? (Logic is Thread -> Textiles -> Clothing)

**Comment by ghost** [comment]
full post, this PR is kinda in bad faith.
the issue has quite a clear consensus, with nearly every serious post on it being "remove the assistant gnome, its a reference".
Instead, you've came and made a PR that removes both and adds another reference, and then not changelogging it?
It's really shitty, what's the point of the discussing in the issue PR if you're not going to listen to what people suggest and then shoehorn in your own epic meme alongside it? 
so, non-atomic etc etc etc, or leave it to burnt to maintain his own map.

**Comment by KillFurries** [comment]
^retard
Liked this PR and the issue because I support removing this. Just because I didn't leave a comment doesn't mean I agree with the two people who said that they only want the assistant gnome removed. The people who leave comments don't get to claim that everyone agrees with them and people should not listen to them. If I wanted only the assistant gnome removed I would say so.
You don't get to leave a comment under a PR that is supported by the majority and say it needs to be changed because two comments created a consensus.
Do people from now on have to leave a comment after upboating stating they support the PR so they don't get lumped in with some ''consensus?''

**Comment by ghost** [comment]
> ^retard Liked this PR and the issue because I support removing this. Just because I didn't leave a comment doesn't mean I agree with the two people who said that they only want the assistant gnome removed. The people who leave comments don't get to claim that everyone agrees with them and people should not listen to them. If I wanted only the assistant gnome removed I would say so. You don't get to leave a comment under a PR that is supported by the majority and say it needs to be changed because two comments created a consensus. Do people from now on have to leave a comment after upboating stating they support the PR so they don't get lumped in with some ''consensus?''

Another post in bad faith.
I count at least 6 people saying it. 
And the rest pretty much mocking you in the comments for the completely unhinged request.
At least try to engage without being a schizo.

**Comment by Kurfursten** [comment]
Okay, I don't mind changelogging it, Morena. Honestly, don't get so worked up.

**Comment by ghost** [comment]
Not worked up, just wondering why it's okay to reference stupid drama but a player reference isn't okay. In the end the result is the same. If you really want those scissors in the game for whatever reason, put it in a different PR.

**Comment by F-OS** [comment]
Upvoting in favor of removing both Gnomes.

**Comment by adacovsk** [comment]
Updooted so I have the monopoly on gnomes

**Comment by dackjaniels69** [comment]
I would like my station 100% gnome free thank you very much

**Comment by Kurfursten** [comment]
Morena, you only seem worked up because you're taking this so seriously, big long replies over what is to all of us a joke - both the gnomes themselves and this loony obsessed with burnt. The scissors are a mockery of that obsession.

But this is the start of advent and in the spirit of giving I will do away with them, since I can tell it means a lot to you.

**Comment by gurfan** [comment]
ditch the scissors

**Comment by SonixApache** [comment]
ditch the scissors

**Comment by PavelCIA** [comment]
replace it with a circumcision clamp

**Comment by bathosbathtime** [comment]
The gnomes make me uncomfortable given their source has made sexual posts about gnomes in the past and I'd rather they get scorched out completely. I don't find it strange that someone would put in effort to get them removed given this context, though I do agree it is funny they never put any of that effort into making a PR to do so.
Apathetic towards the scissors. Second replacing them with a circumcision clamp.

**Comment by ghost** [comment]
> Morena, you only seem worked up because you're taking this so seriously, big long replies over what is to all of us a joke - both the gnomes themselves and this loony obsessed with burnt. The scissors are a mockery of that obsession.
> 
> But this is the start of advent and in the spirit of giving I will do away with them, since I can tell it means a lot to you.

it's not a mockery when you give them what they want. people don't celebrate being mocked.

**Comment by Kurfursten** [comment]
As Morena says, the people have spoken and I give them what they want! No scissors.

Now is your cue to celebrate. 🎉

**Comment by SonixApache** [comment]
i don't know why you're hyperfocussing on morena but thank you for removing the thing that celebrates those that destroy our home

remove `gardengnome.dmi` while you're at it

**Comment by ShiftyRail** [comment]
This has obviously a clear majority. If someone wants to add back scissors, it's fairly easy to do.
Now let's put this to rest

**Comment by Kurfursten** [comment]
See this is why you come off as worked up. I was lampooning this mountain out of a molehill situation. Calling someone schizophrenic is not a celebration of that person, and in fact thread schizo is just a noname too cowardly to even post their thoughts for themselves, like we do.

But schizo is not "destroying our home" and in fact has no power. I made this PR because I wanted to, not by any external compulsion, and in fact I didn't even bother to read schizo's post until he made it here on l github where mapping changes belong.

Lighten up.

**Pull request merged**
