### PR TITLE
Mailing things to centcomm

### PR DESCRIPTION
**Pull request by unid15**
Revival of an old PR
- Adds postage stamps
- QM's office starts with one
- They can be ordered from cargo at the price of 500$/stamp
- Putting a postage stamp on a parcel and shipping the parcel away on the supply shuttle will teleport the parcel to a special room in centcom, and notify admins

### CODE REVIEW

**Comment by DeityLink** [comment]
AAAAAAAAAAAAAAAAAAH

But that conflicts with the update I'm cooking up right now! I'm also adding a way for the crew to export stuff to centcom but your method conflicts a lot with mine.

**Comment by unid15** [comment]
okie

**Comment by unid15** [comment]
@DeityLink are you still working on that

**Comment by DeityLink** [comment]
Not anymore, feel free to go at it.

**Pull request closed without merging**
