### PR TITLE
New gravitational karmotrine drinks

### PR DESCRIPTION
**Pull request by ghost**
[content]

Two new drinks:

* gravsingulo Gravitational Singulo
* gravsingularitea Gravitational Singularitea

Based on their original respective drinks, recipe is 1 part drink 4 part karmotrine resulting in 1 part of each.

Has a time-based consumption limit that pulls people in further and further, until eventually damaging the consumer and replacing them with a 1x1 singulo, similar to baguloose ones, once the pass-out limit is reached as if in beer. Metabolism is 2.5 times faster than normal beer's, so this requires roughly 150u or 3 full drinks to be consumed to activate this.

Don't try doing this on a monkeyman, they'll just gib and spawn a useless toy singulo instead.

:cl:
 * rscadd: Bartenders now have two new karmotrine drink recipes to make their bars more attractive

### CODE REVIEW

**Comment by BomberBro** [comment]
I think the drink making you pull things towards you is funny but making a whole-ass singulo is a little much.

**Comment by ghost** [comment]
> I think the drink making you pull things towards you is funny but making a whole-ass singulo is a little much.

I set the limit really high on purpose to almost never make it occur but I could honestly remove this part if you want, the first part alone was the original idea

**Comment by dunsel-hordon** [comment]
250 really isn't much
I would say raise that to 1000 as even moving 1000 units of fluid is very prohibitive and no one will accidentally drink 1000 but i can easily see someone drink 250 and not knowing the danger of this drink.

**Comment by Viciousaurus** [comment]
Bonk! Atomic Punch that lets me fill radiation collectors and gives other people cancer when?

**Comment by Eneocho** [comment]
250 sounds like a decent threshold, besides you'd need massive amounts of both the base drink and karmotrine to do it, at which point it's faster to just raid RnD and baguloose. Make it change sprite based on the amount of the drink on the glass. Blue-black if 15u, purple-black if 30u, black if 45+u.
Could also use a "supermatter" drink that synergizes with singularity drinks.

**Comment by ghost** [comment]
> Make it change sprite based on the amount of the drink on the glass. Blue-black if 15u, purple-black if 30u, black if 45+u.

My original idea was to make the sprites yellow themed like super singulos but this could work... maybe

**Comment by Eneocho** [comment]
> 
> 
> > Make it change sprite based on the amount of the drink on the glass. Blue-black if 15u, purple-black if 30u, black if 45+u.
> 
> My original idea was to make the sprites yellow themed like super singulos but this could work... maybe

If we ever get a supermatter drink, it could make the super singularity drink if you mix it with the gravitational singulo.

**Comment by ghost** [comment]
> > > Make it change sprite based on the amount of the drink on the glass. Blue-black if 15u, purple-black if 30u, black if 45+u.
> > 
> > 
> > My original idea was to make the sprites yellow themed like super singulos but this could work... maybe
> 
> If we ever get a supermatter drink, it could make the super singularity drink if you mix it with the gravitational singulo.

I don't think spessmen should have this much power
That aside I did come up with a convoluted recipe for making one, involving dragging xenoarch supermatter chunks into a supermatter beaker from traders and grinding it, consuming the grinder by "ashing" it but attempting to grind it in a normal container just ashes the entire thing.

**Comment by Eneocho** [comment]
> > If we ever get a supermatter drink, it could make the super singularity drink if you mix it with the gravitational singulo.
> 
> I don't think spessmen should have this much power
> That aside I did come up with a convoluted recipe for making one, involving dragging xenoarch supermatter chunks into a supermatter beaker from traders and grinding it, consuming the grinder by "ashing" it but attempting to grind it in a normal container just ashes the entire thing.

I would just make the supermatter synergize with the scrungulo karmo drink making it yellow.
The SM drink itself could have a 3:3:1 chance to either stun you like a tazer, shock you with 80 burn damage or give you a special shock healing ability (akin to the golden gloves in the cloud IX PR).
The SM+Scrungulo Karmo drink would be yellow and would not metabolize (to mirror the infinite nature of yellow scrungulos) and would have a permanent gravity field, enough to snatch things out of people's hands but no more.

**Comment by beesil** [comment]
> Supermatter Drink

Sippermatter? I agree though that the drink making a singularity is Too Much.

**Comment by Dacendeth** [comment]
This is incredibly dangerous because unlike baguloosing where you die to do it, you can just feed a monkeyman and leave a timebomb singuloose somewhere.

**Comment by Eneocho** [comment]
Could it have a 1 in 100 chance to become a grabibational scrungulo and spawn a scrungularity instead?

**Comment by ghost** [comment]
> This is incredibly dangerous because unlike baguloosing where you die to do it, you can just feed a monkeyman and leave a timebomb singuloose somewhere.

Could make it check if the reagant holder has an active mind to spawn the singulo, and if not it just gibs them and spawns a toy singulo instead.
Update: Done.

**Comment by Eneocho** [comment]
> 
> 
> > This is incredibly dangerous because unlike baguloosing where you die to do it, you can just feed a monkeyman and leave a timebomb singuloose somewhere.
> 
> Could make it check if the reagant holder has an active mind to spawn the singulo, and if not it just gibs them and spawns a toy singulo instead.

Infinite and reliable Singulotoy source? Too much power for a spessman.

**Comment by Kurfursten** [comment]
Conflicts

**Comment by ghost** [comment]
> Conflicts

Resolved

**Comment by Kurfursten** [comment]
It also takes 250 ticks, meaning 500 seconds, or >8 minutes. 
Plenty of time to run for charcoal

**Pull request merged**
