### PR TITLE
Fixes drinking water extinguishing cigarettes

### LINKED ISSUE #36414: drinking any liquid extinguishes cigarettes.
(WEB REPORT BY: yvvel REMOTE: 172.93.101.77:7777)
# Revision
febb5580f5f3d492db6f15b04aa642ce9f8f8971

# Description
drinking any liquid extinguishes cigarettes.
# Steps to Reproduce
1. smoke
2. drink something while smoking
3. get upset that your cigarette is gone
# What you Expected
it to not fucking extinguish itself
# What Actually Happened
it got extinguished.

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* bugfix: Fixed drinking water extinguishing cigarettes.

### CODE REVIEW

**Comment by angryturnip** [comment]
Can you make it still behave the old way if someone has brain damage?

**Comment by Theophrastus1** [comment]
maybe they should take the smoke out of their mouth before they try to drink

**Comment by Inorien** [comment]
> maybe they should take the smoke out of their mouth before they try to drink

what are you a fuckin casual

**Comment by Dacendeth** [comment]
> maybe they should take the smoke out of their mouth before they try to drink

image

**Pull request merged**
