### PR TITLE
[Meta] Science changes and other misc fixes

### PR DESCRIPTION
**Pull request by IratePirate**
science

-layout changes to science
-new research dock added
-science corridor extended
-new maint area between research, toxins launch, research dock
-telescience moved
-autolathe added to research
-fixed pipe on minisat
-added scalpel and removed incision management from surgeries
-removed the free cable coil from the solars
-decals to pod bay
-made solars less annoying to wire with some wiring changes

### CODE REVIEW

**Comment by ComicIronic** [comment]
Telescience control could stand to be 4 tiles smaller so you could add shield gens or just expand the chamber a bit.

**Comment by IratePirate** [comment]
tele

More suitable?

**Comment by ComicIronic** [comment]
Very.

**Comment by IratePirate** [comment]
Can be merged.

**Pull request merged**
