### PR TITLE
Fixed a thing with the singularity maybe?

### PR DESCRIPTION
**Pull request by DamianX**
What's the worst that could happen?

### CODE REVIEW

**Comment by jknpj** [comment]
:thinking:

**Comment by DamianX** [comment]
`(NORTH || SOUTH)` is equivalent to `(NORTH)`
clearly they meant `(NORTH, SOUTH)`

**Comment by ShiftyRail** [comment]
Faith-driven development

**Comment by SonixApache** [comment]
🤔

**Comment by Exxion** [comment]
I have no idea what in-game behavior this would actually change, but this is obviously what the code was intended to be

**Pull request merged**
