### PR TITLE
(READY TO MERGE)FIXING GREY SPRITES: THE BEGINNING

### PR DESCRIPTION
**Pull request by kol1th**
First baby steps to fixing grey sprites. Greys won't have underwear due to sprite conflicts for now. (I will enable them later I swear.) Sprites courtesy of @NigglyWiggly 

image

image

image

image

image

IF YOU HAVE ANY INTEREST OR SPRITES, PM ME SOMEWHERE AND I'LL MAKE YOUR DREAMS REALITY.

### CODE REVIEW

**Comment by 9600bauds** [comment]
I give this PR a thumbs up

**Comment by carshalash** [comment]
Thank you babe

**Comment by kol1th** [comment]
As-is this currently has NO sprites for hardsuit helmets, but ONLY hardsuit helmets. I'm not sure why.

**Comment by Intigracy** [comment]
why are sterile and sterile_up the same icon wtf

**Comment by NigglyWiggly** [comment]
They're not, I promise.

**Comment by NigglyWiggly** [comment]
Also I did not do the Clown, Mime, or Breathmask sprites, that was Kokuten

**Comment by kol1th** [comment]
@Intigracy doesn't matter since there is no sterile_up. in regular mask.dmi it's just the breath mask up sprite. I have no idea why it's there.

**Comment by optimumtact** [comment]
Some of these sprites aren't even grey

**Comment by kol1th** [comment]
All of them are resprited to fit greys.

**Comment by clusterfack** [comment]
Fixing grey sprites: the end?

**Comment by kol1th** [comment]
mobile memes

**Comment by xevonix** [comment]
Please make a sprite for the red bandana to properly fit on the greys face when toggled down.

**Pull request merged**
