### PR TITLE
Adrenal Gland

### PR DESCRIPTION
**Pull request by MadmanMartian**
Adds the adrenal gland, literally just a combat tweaking organ.

In combat, should you take a heavy blow (currently a quarter of your maximum health) you will receive a burst of adrenaline to help with fight or flight.

Adrenaline counts as a pain killer, akin to oxycodone in the way it also stops you from being able to perceive just how much damage you have, as well as giving you some increased strength for a time, and increasing heart rate. 
This would prove useful to help escape from, or give you an upper hand in, dangerous situations , such as being on the receiving end of high-damage attacks from heavy laser fire, or a giant spider queen slapping you and breaking all of your limbs in one shot because our simple animal combat balance is terrible currently.

The current species that have adrenal glands are: Humans, Greys, Vox, and Tajarans specifically, as well as any species that do not override the organ list, so likely Skrell and Unathi.

Because human code is dumb, have had to move around a bit of human's /New so that the on_attack event exists by the time we're initializing organs. This may lead to unintended side effects like everyone being able to speak sol common. Will continue prodding and poking to reduce said side effects.

Very much a balance tweak. Would like conversation as to how this could be tweaked for better or worse, or arguments against it being added at all.

[balance]

:cl:
 * rscadd: Adds the adrenal gland, which gives you a burst of adrenaline should you receive heavy damage in a single blow.
 * rscadd: Adds adrenaline, which acts as a pain killer, strength modifier, and tachycardic.

### CODE REVIEW

**Comment by Tokanova** [comment]
super cool idea dude, hope it gets through
is there going to be a sprite for the adrenal gland if someone wants to remove it with surgery to cuck someone?

**Comment by brndd** [comment]
Can you replace it in surgery with a synthetic adrenal gland that provides military-grade powergay chemicals? Can adrenaline be somehow extracted?

**Comment by Dacendeth** [comment]
Why not plasmamen too, they have every organ a human has left over from when they used to be human,  what logic is it that they'd be excluded from having this one?

**Comment by SonixApache** [comment]
neat

**Comment by strawberrytan** [comment]
Plasmamen do not have blood

**Comment by bathosbathtime** [comment]
I would like plamamen to have a functional useless gland to keep with consistency if at all possible.  Could even have it inject plasma instead so you can implant it into people to absolutely nuke them when they take heavy damage.

**Comment by Dacendeth** [comment]
I don't see what not having blood has anything to do with anything, they have a heart even though they don't have any blood why not an adrenaline gland?

**Comment by strawberrytan** [comment]
I just think the functionality would be a nice added distinction between the species with blood(and bleeding) and the species without (diona, plasmamen, skeletons)

**Comment by MadmanMartian** [comment]
I wanted to avoid giving the undead & combat-oriented species adrenal glands, such as the plasmaman (It's undead, right? & heavy burn resistance), dionae (incredible brute and toxin regen), and the manifested (starting out with no pain)

**Comment by Lokiamis** [comment]
Won't this put more emphasis on stunning first, often considered the worst part of our combat system?

**Comment by brndd** [comment]
Adrenaline reducing stun duration?

**Comment by Chazach** [comment]
Is a quarter of your max health count as 25 or 50?
As a standalone I think this is pretty neat but we have to be vigilant to avoid falling into hippie future hell where you can get an adrenal implant in sci to make you invincible/being able to synthesise meme chems to avoid stuns completely

**Comment by MadmanMartian** [comment]
25, as the negative health is determined by a config, whereas maxHealth is 100/tweakable by phazon.

**Comment by SonixApache** [comment]
ignore the non-human advocates

**Comment by SirSkeleto** [comment]
I am concerned about the way that this favors stun-based combat over lethals, as currently stuns are (in my opinion, which is probably shared by a non-insignificant part of the population) much stronger, and this serves to nerf only lethals, whereas stuns remain untouched. It's a neat idea but I am concerned for the consequences.

**Comment by Tokanova** [comment]
perhaps adrenaline should just as equally cuck stuns as much as it does lethals?

**Comment by AutismSpider** [comment]
Let's make some lethals even worse but keep stuns the same 

all i see form this PR unless this PR cucks the shit out of stuns in some way

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Even if adrenaline reduces stuns, you still get it from taking damage, which encourages opening up with stuns.
This is a very difficult topic to get right, and other servers have gone down hippie hell trying. Let's have a discussion first before blindly changing stuff, get the goals of the PR figured out.

**Comment by Lokiamis** [comment]
>This would prove useful to help escape from, or give you an upper hand in, dangerous situations , such as being on the receiving end of high-damage attacks from heavy laser fire, or a giant spider queen slapping you and breaking all of your limbs in one shot because our simple animal combat balance is terrible currently.

I don't think you should be able to run away at max speed from a giant spider queen wound or heavy laser fire, and I don't think you clearly explained why you think it would be good if you could do this. If I hit somebody with a fireaxe he gets a strength boost? I don't know about that.

**Comment by SonixApache** [comment]
there is literally no reason to ever not open with stuns
this doesn't change that in any way other than making non-stun battles (ie. boxing and nothing else) slightly more interesting

That said;
 - having Adrenaline kick in a few seconds after it enters your system would be good
 - making you a bit slower once it wears out might also be good
 - Does speeding up your heartrate make you bleed faster? because it should.

**Comment by Lokiamis** [comment]
@sonixapache
There are several legitimate reasons, let's not be dishonest. A common one would be a fight between a taser and a laser. The laser wielder has a significant advantage in that his weapon is hitscan. Despite needing 2 extra shots to win the fight, he knows that his shots are more likely to connect, each shot will slow the enemy down and inflict pain, maybe there's a window he can use to his advantage, every bit of distance he can get from his enemy lowers their likelihood of tagging him etc. This change would give even more of an advantage to the taser user. And it's not clear to me if it would affect something like boxing. Does the health need to be lost in one hit or would multiple small blows in a short period trigger it?

**Comment by Hoshi-chan** [comment]
* Does speeding up your heartrate make you bleed faster? because it should.

Oh, I hate this.

**Comment by MadmanMartian** [comment]
I assumed it would be to help keep blood pressure up to offset low blood, but it seems to be used in three places.

Sleepers and the health analyzer to show the persons heart rate

The operation table for the pulse display overlay.

Bit of an underuse.

**Comment by Blithering** [comment]
Could you have using the gym equipment produce a small amount of adrenaline?

**Comment by DeityLink** [comment]
Hey here's an idea @MadmanMartian , have the activation of the adrenaline gland cause people with the Hulk gene to automatically hulk out if it's off cooldown.

**Comment by MadmanMartian** [comment]
>auto hulk

I'm gonna say no to that one, thank you.

**Comment by Blithering** [comment]
RIP

**Pull request closed without merging**
