### PR TITLE
Lowered the volume of the science goggles's pathogen scanner being toggled

### LINKED ISSUE #23554: pathogen scanner sound spam
(WEB REPORT BY: rpaul REMOTE: 206.221.180.138:7777)
You turn the pathogen scanner off.
You turn the pathogen scanner on.
You turn the pathogen scanner off.
You turn the pathogen scanner on.
You turn the pathogen scanner off.
You turn the pathogen scanner on.
You turn the pathogen scanner off.
You turn the pathogen scanner on.
You turn the pathogen scanner off.
You turn the pathogen scanner on.
You turn the pathogen scanner off.
You turn the pathogen scanner on.
You turn the pathogen scanner off.
You turn the pathogen scanner on.
You turn the pathogen scanner off.

ouch my ears

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #23554

:cl:
* tweak: Lowered the volume of the science goggles's pathogen scanner being toggled

### CODE REVIEW

**Comment by Kurfursten** [comment]
How about LITERALLY ANY OTHER SOUND EFFECT besides "egun toggled".

I would take bees buzzing, VOX saying "whoop", and disposal pipe clang over it.

**Comment by DeityLink** [comment]
Meh, surely I'm not the only one thinking the sound fits, if only too loud.

**Comment by Kurfursten** [comment]
Sure it fits, it is also terrible and makes me think someone's about to laser me every time I go into medbay

**Comment by Dacendeth** [comment]
kind of weird that these are the only goggles with a sound effect.

**Comment by tuypo1** [comment]
> kind of weird that these are the only goggles with a sound effect.

when you compose it

**Pull request merged**
