### PR TITLE
Removes random event powercreeper

### PR DESCRIPTION
**Pull request by jknpj**
:cl:
 * rscdel: Powercreeper won't spawn randomly anymore

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
IT'S THE FORSAKEN R-WORD

**Comment by DrSnips** [comment]
Can we just put it in deep gay baby jail until the creator decides to completely test it?

**Comment by utilitas-** [comment]
please god yes
powercreeper is the random event of all random events that gunks everything the most
not even rods have shit on it
(spacetime anomalies back fucking when)

**Comment by Irradiation** [comment]
Just EMP with your backpack Ion and Discountt Dan EMP bars bro
Just wear glubbs bro

**Comment by utilitas-** [comment]
there isn't an emp big enough to clear all that fucking powercreeper
you know you've done a design snaffu when the most effective way to remove your round annoyance is with one of the most immediate round-ending tools: subermadder shord

**Comment by ghost** [comment]
Finally. It takes up a random event slot and adds nothing to the round that my boys biomass and kudzu weren't already adding.

**Comment by ShiftyRail** [comment]
Just use tape on it

**Comment by Tokanova** [comment]
Fuck power creep, I always end up losing a robo limb when someone goes a bit too gungho with EMPs to fight it

**Pull request merged**
