### PR TITLE
adds (staff of) sinterklaas

### PR DESCRIPTION
**Pull request by SonixApache**
sinterklaas
*top: mitre and staff - left: before getting staffed - right: after getting staffed*

- adds sinterklaasfeest holiday
- adds staff of sinterklaas artifact that turns people into zwarte piet
- zwartepietify proc
- adds sinterklaas mitre

todo:
 - [x] make staff holiday-only from spellbook
 - [x] getting the staff should change your beard
 - [ ] add strooigoed 'weapon' that turns into candy when thrown
 - [ ] add some types of candy for the above
 - [ ] give it to people that get pietified with maybe a ROLE
 - [ ] robe and shoes for the sint, shoes for the piet, add an outfit box
 - [ ] more modes for the staff? gift giving mode?
 - [ ] other memes? sounds?

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
https://www.youtube.com/watch?v=D-oE_uRoRmA

**Comment by ShiftyRail** [comment]
A bit too much melanin in this staff
I fear this might be conductive to poor roleplay (no racism intended)

**Comment by SonixApache** [comment]
I intend to add a "spread cheer and candy" line or something similar to whoever gets transformed once I get the candy coded in
and i can probably change the melanin* into full-body make-up

**Comment by SonixApache** [comment]
Gonna mark this as [basically done] because i didn't get around to finishing it, will make PR to remove it from the spellbook again to prevent memes

**Pull request merged**
