### PR TITLE
*** FEATURE FREEZE IN EFFECT

### PR DESCRIPTION
**Pull request by N3X15**
# Feature Freeze September 2015

No new feature PRs will be accepted until the bugs listed [here](https://github.com/d3athrow/vgstation13/milestones/Feature%20Freeze%20%28Sept%202015%29) are fixed.

### CODE REVIEW

**Comment by DeityLink** [comment]
yaaay

**Comment by PJB3005** [comment]
PR/10

**Comment by FudgePucker** [comment]
@N3X15 
Hey can you add https://github.com/d3athrow/vgstation13/issues/5873 to this?
I am sick and fucking tired of this bug popping up over and over and over and over again.
If it is fixed outside of a feature freeze then theres a chance it will be overwriten to give a department a new table or some stupid shit like that fucking over the SME all over again.

**Comment by PJB3005** [comment]
YES FINALLY!

**Pull request closed without merging**
