### PR TITLE
Adds more places for the vox skipjack to fly to

### PR DESCRIPTION
**Pull request by jakmak6**
With raiders intended to be a quick and mobile force the fact their ship can fly 4 places (5 if you count the round ender) makes no sense when the nuke op ship can fly basically anywhere the nukies can go and beyond. This raises the amount of places the vox skipjack can go. NOTE does not affect the traders ship

These places include

- 5 more places on z1(station)

- 4 places on asteroid

- and 2 more away from station (comms sat and deep space)

This also renames the round ending destination from "deep space" to home base since a actual deep space (located on z6) was put in so vox have a place to run and hide for respite without fear of powergaming borgos/sec officers/miners/blood thirsty captains/ clowns from find them

### CODE REVIEW

**Comment by Kurfursten** [comment]
>six

Should we start a betting pool on how many Jakmaks there will be by end of year?

**Comment by Aurx** [comment]
>clown roid

Literally why

Also how the hell do you keep going though so damn many usernames.

**Comment by kernikov** [comment]
Mix rounds are going to be funny if the newcops and birbs both try to jump to the same spot.

**Comment by jakmak6** [comment]
because when i clone the repo to many times eventually it turns into the repo would get to 99% and error out and the only way to fix it is a new account

And kern i made sure that the nukie ship and vox ship dont collide when they dock at the same location. They use 2 diffrent sets of docking ports that are far enough away from eachother to prevent memery

**Comment by jakmak6** [comment]
the maptool refuses to cooperate as in its not reducing the lines changed
And its only giving me issues with taxi and test_box. deff meta and box have their lines changed reduced

**Comment by Shadowmech88** [comment]
Why are you cloning the repo multiple times?
I haven't used the clone command since I first made my local repo.

**Comment by Probe1** [comment]
Clean your map before submitting a PR.  

Also no clown roid what even

**Comment by Probe1** [comment]
http://ss13.moe/wiki/index.php/Guide_to_Mapping#How_to_get_your_map_merged

Secret protip:  You can download the dmm files directly from the repo and rename them tgstation.dmm.backup if you've fucked up badly and don't have a clean backup of the map.

You can (and should) also discard edits to maps you do not plan on messing with.

**Comment by Probe1** [comment]
You are still changing a fuckton of lines on ministation.dmm

**Comment by Probe1** [comment]
Stop commiting files you aren't intending to change, like test_box.dmm

**Comment by Exxion** [comment]
Yeah, why the fuck are you cloning the repo more than once?

Also that is an absolutely ridiculous number of destinations

**Comment by Durgen** [comment]
raiders will be able to steal emitters from the derelict for even faster speedrun memery

**Comment by jakmak6** [comment]
i have removed the clownroid aka derelict flying thing. Birbs can no longer go to derelict z level

**Comment by kol1th** [comment]
You can delete repos and start over like that, not make a new account
Jesus christ

**Comment by Probe1** [comment]
>jakmak3 added some commits
 >jakmak6
Just fucking shoot me.

**Comment by mtpowell** [comment]
@Probe1 

This is what happens when you tell people WYCI :^)

**Comment by PJB3005** [comment]
Jakmak10 when.

**Pull request merged**
