### PR TITLE
Fixes mapping errors in Box Station.

### LINKED ISSUE #11816: map error in box station
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> there is a table under the mechanics  research console for no reason
> 
> What you expected to happen
> no tables under the consoles
> 
> What actually happened
> there is a table there
> 
> Steps to reproduce if possible
> go on vg station
> see a table under the mechanics console thing

also the mechanics office in box should be bigger

### PR DESCRIPTION
**Pull request by icantthinkofanameritenow**
Fixes #11816 and #11818

### CODE REVIEW

**Comment by CptWad** [comment]
I mean atmos alerter thingawhatsy

**Comment by icantthinkofanameritenow** [comment]
Yeah, I deleted it and then replaced it in order to make the fix.

**Comment by CptWad** [comment]
weird the commit does not show that
theres already an air alarm in that room so whatever

**Comment by icantthinkofanameritenow** [comment]
It should work normally, and when I tried testing it nothing weird happened. I'll keep an eye on it just in case if something pops up in that area later. Worst case, I can just put the alarm somewhere else.

**Comment by CptWad** [comment]
literally a two click fix for it if there is
but its scool

**Pull request merged**
