### PR TITLE
Emags and Glue bundle tweak.

### PR DESCRIPTION
**Pull request by Eneocho**
Kinda weird that you get 4 glues but only 3 emags.
## What this does
You now get equal amounts of glue and emags (3 and 3)
## Why it's good
Consistency good

:cl:
 * tweak: Emags and Glue syndicate bundle now has equal amounts of emags and glue (3 of each).

### CODE REVIEW

**Comment by jwhitak** [comment]
You get 4 glue and 4 emags now, not 3 and 3. Had to look at the code to tell.

**Comment by Eneocho** [comment]
I thought it was obvious that it was an increase. I'll put it explicitly on the PR.

**Comment by DorainGrey** [comment]
You get 5 boxes if you roll this bundle which is well in excess of the 14tc paid to roll and has much greater value in comparison to the other rare bundles as well.
So for "Consistencies" sake, it'd make a lot of sense to make it 3 & 3.

**Comment by Eneocho** [comment]
> For consistency, you could always reduce it. After all you get 5 boxes if you roll this bundle which is well in excess of the 14tc paid to roll. So for "Consistencies" sake, it'd make a lot of sense to make it 3 & 3.

Guess that works too.

>Not 4 & 4 but I doubt the PR is actually about that.

I was testing some arcane tamper stuff on localhost and spawned the emag box instead of a regular emag, it felt weird to have only 3 emags to 4 glues so I made this in 5 minutes.

**Comment by DorainGrey** [comment]
> > For consistency, you could always reduce it. After all you get 5 boxes if you roll this bundle which is well in excess of the 14tc paid to roll. So for "Consistencies" sake, it'd make a lot of sense to make it 3 & 3.
> 
> Guess that works too.
> 
> > Not 4 & 4 but I doubt the PR is actually about that.
> 
> I was testing some arcane tamper stuff on localhost and spawned the emag box instead of a regular emag, it felt weird to have only 3 emags to 4 glues so I made this in 5 minutes.

Sorry I removed that comment because I realized it was a bit uncalled for, very passive aggressive.

**Comment by Eneocho** [comment]
>Sorry I removed that comment because I realized it was a bit uncalled for, very passive aggressive.

No worries man.

**Pull request merged**
