### PR TITLE
Headsets will now show the prefixes necessary to access the channels

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
frequencies
(ignore the Supply one I fixed it but didn't want to launch the game again just for a screenshot)

Now you can actually know for sure how to use each frequency.
The way it is implemented is a little bit too dirty and manual but at least it's also low-impact, I would have liked to start defining the prefixes (which are in code/modules/mob/living/say.dm, line 33) but they're actually sorted in alphabetical order already because bad things happen if a prefix is used for two different channels/languages.

:cl:
 * rscadd: Channels in the headset will now show the prefix required to communicate through them.

### CODE REVIEW

**Comment by jwhitak** [comment]
nice changelog

**Comment by boy2mantwicethefam** [comment]
I accidentally pressed enter when writing the title.

**Comment by pedr69** [comment]
could probably also add something to raider and nukeop headsets to let them know ; is the raider/nukeop frequency

**Comment by boy2mantwicethefam** [comment]
@pedr69 I want to add that in some form at some point in the future but I'm not exactly sure how.

**Comment by SonixApache** [comment]
good change :+1:

**Pull request merged**
