### PR TITLE
Disable snaxi because it doesn't compile and if voted just loads box instead after some time

### PR DESCRIPTION
**Pull request by DamianX**

### CODE REVIEW

**Comment by Eneocho** [comment]
>disable snaxi

The hero we needed

**Comment by Kurfursten** [comment]
Dunno when we got in the habit of just removing things.

Snaxi works on local for me. I can run it no problem, with no obvious compile issues. I offered to fix it, but no one seems to know what the problem is. It's not tool pathing, that's the first thing I checked.

**Comment by Kurfursten** [comment]
It looks like there was some miscommunication here.
image

**Comment by DamianX** [comment]
I mistakenly assumed the reason the map was not available was due to errors, especially considering removing things from /vg/station is not a possibility, but it looks like the reason was that pomf wasn't aware snaxi was supposed to be available during July. This change is not needed now that the code checks whether the map file exists anyway.

**Pull request closed without merging**
