### PR TITLE
Monthly money leaderboard

### PR DESCRIPTION
**Pull request by adacovsk**
[tweak]

:cl:
 * rscadd: Money leaderboard should reset monthly

### CODE REVIEW

**Comment by WindowsErrors** [comment]
hopefully people will be more creative than just rushing known money glitches at the start of the month but we all know what's really gonna happen

**Comment by Eneocho** [comment]
I'd take it down to weekly or bimonthly leaderboard, but this is fine too. No more 1.INF money leaderboard.

**Comment by kilozombie** [comment]
> hopefully people will be more creative than just rushing known money glitches at the start of the month but we all know what's really gonna happen

FWIW the reason the current leaderboard is broken is because a couple people got into the Vox Metaclub and grabbed the gorillion credit chip

For this reason I must downvote this PR it's too funny to have the numbers be fucking broken

**Comment by kilozombie** [comment]
Oh shit I'm completely wrong, the leaderboards ARE fucked with money glitches, everyone has infinite money. Downvote rescinded, ass blasted

**Pull request closed without merging**
