### PR TITLE
Sound Synthetizer facelift

### PR DESCRIPTION
**Pull request by 9600bauds**
Basically rewrote the thing because it was awful.

+changes: 
-  - rscadd: "The Sound Synthetizer now uses a popup list to choose between sounds."
-  - soundadd: "Tweaked some Sound Synthetizer sounds that were particularly hard to hear to make them a bit louder. Also disabled random pitch in a couple of Synthetizer sounds that normally do not have randomized pitch, so they sound a little closer to the real deal."
-  - soundadd: "Added 4 sounds to the Sound Synthetizer, each one more annoying than the last, at least two of which may have comedic potential."

Sounds added: Quack, "Wow, this is just like one of those japanese animes", muffled boom (make the HoS think Cargo is using IEDs!), and a countdown thing I found

### CODE REVIEW

**Comment by CptWad** [comment]
Bless you

**Comment by 9600bauds** [comment]
a-choo

**Comment by Exxion** [comment]
Please #6958

**Comment by 9600bauds** [comment]
what is "taps"

**Comment by Exxion** [comment]
https://www.youtube.com/watch?v=WChTqYlDjtI

Just like the first few notes

**Comment by 9600bauds** [comment]
It's a little bit long, gibe a short version

**Comment by clusterfack** [comment]
"Wow, this is just like one of those japanese animes"

But my super secret admin verb, why are you making it so everyone can use it

**Comment by ihadtoregisterforthis** [comment]
You need to click the buttons to play or set the sound? Does the pop-up stay or closes on click?

A security sound could be added, like the hailer or a beepsky line.

**Comment by 9600bauds** [comment]
Idunno I found that sound, no idea it was even a verb

Also, you pick the sound from the list and then you use it in your hand or smack people to play the sound

**Comment by clusterfack** [comment]
Yeah it's one of the admins 'fun' adminverbs

**Comment by Intigracy** [comment]
tfw no adminhelp.ogg
tfw no laser or esword sound

**Comment by CptWad** [comment]
>Giving people heart attacks

Intigracy we could go to jail for that

**Comment by 9600bauds** [comment]
For laser and esword sounds you have the practice laser and toy esword which are even better

**Comment by Wizardcrying** [comment]
WHY DID WE SWAP OUT TG'S ANIMES.OGG FOR OUR SHITTY VOX ONE
WHY

**Pull request merged**
