### PR TITLE
Carshalash gets angry about clowns being unable to cuff part 3

### PR DESCRIPTION
**Pull request by carshalash**
Okay, now you can cuff only if you're an antag.

### CODE REVIEW

**Comment by Aurx** [comment]
Antag check!

**Comment by ShiftyRail** [comment]
Antag check + snowflake check (code-wise) wombo combo

**Comment by Dacendeth** [comment]
What if you just changed cuffs to drop on the ground instead of cuffing the clown, like with a flash?

**Comment by Probe1** [comment]
He's back!

**Comment by ShiftyRail** [comment]
C*llabs........................

**Comment by Pathid** [comment]
Antag clowns could use a button that toggles clumsy, like someone said last time.

**Comment by carshalash** [comment]
tfw you make a different balance change but ivory tower closes it an hour after being made.

**Comment by ShiftyRail** [comment]
This is a badly coded change that clearly wasn't well thought-out. And that has been refused before. Sorry Carsh but it's true.

I'll make what Decadenth suggested when I'm home.

**Pull request closed without merging**
