### PR TITLE
Added workaround for nanoui bug

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * experiment: Added a work-around for the bug that prevents nano UI from opening: use the "Fix NanoUI" verb under OOC. Then, you should be able to use the thing you wanted to use.

### CODE REVIEW

**Comment by DamianX** [comment]
Should be obsoleted by #20722

**Comment by DamianX** [comment]
#20722 and #20798 didn't fix it

**Comment by MadmanMartian** [comment]
is open_uis mob level or world level?

**Comment by DamianX** [comment]
It's a mob var

**Pull request merged**
