### PR TITLE
Beer in Water Fountains

### PR DESCRIPTION
**Pull request by Kurfursten**
Requested by Dorms

If it is April Fool's Day, or you are currently logged in with Headmin rights (did not deadmin), the sink will only dispense beer for you, not water.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Do that for the entirety of October, not April Fools

**Comment by toomykins** [comment]
i'm sure the beer coming out of sinks won't be entirely annoying when testing shit

**Comment by Kurfursten** [comment]
Just turn off PERMISSIONS for yourself, you don't need it for anything in testing anyway

**Comment by ghost** [comment]
> 
> 
> Do that for the entirety of October, not April Fools

https://www.youtube.com/watch?v=RelMNcu7LOI

**Comment by help-maint** [comment]
Is there a headmin joke I'm missing

**Comment by Eneocho** [comment]
> 
> 
> Is there a headmin joke I'm missing

something something alcoholics

**Comment by ghost** [comment]
> Is there a headmin joke I'm missing

The feature was requested as a joke by dorms in admin chat, in reference to the youtube link I posted.

**Comment by Kurfursten** [comment]
rather than do this to every sink as a joke I think I'll just make a beer fountain subtype

**Comment by Kurfursten** [comment]
I went down the rabbithole of giving waterfountains and sinks their own water source and then I realized this is too much trouble for a joke dorms made one time

**Pull request closed without merging**
