### PR TITLE
Mouser Pistol: Reloaded

### PR DESCRIPTION
**Pull request by Kurfursten**
The gun code was already done and the hard part was the super complex mouse labyrinth. Over time I figured that most people would use the mouse labyrinths like one time for gimmicks and then forget about it, so why not just PR the stuff that will get used?

Compared to the old version, this also gives the CMO the discount and prevents transformed mice from suicide.

:cl:
* rscadd: A new medbay special, the Mouser Pistol, will turn you into a lab rat! Find a way to die to return to your normal body with all gear.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
After 10,000 years, at last.
Keeping them separate and at least partially available is a good call. I think half the fun is finding a way to force the mouse to stay alive anyway.

**Comment by Eneocho** [comment]
With how ridiculously nerfed mousecode is, you can literally just exist and die.
Enter a pipe, oops it's underpressured, you die.
Go to kitchen. Eat. You die.
Approach anyone. They stomp or kick you. You die.

**Comment by Kurfursten** [comment]
All intended, although you might find it hard to get people to stomp you if they don't know people are being moused since there are no identifying features. If you die in a pipe there is a special case where it spits you out on the turf.

**Comment by Eneocho** [comment]
> 
> 
> All intended, although you might find it hard to get people to stomp you if they don't know people are being moused since there are no identifying features. If you die in a pipe there is a special case where it spits you out on the turf.

Still, you can literally die seconds from being converted.
Be moused.com, go to a scrubber and enter. Die from asphyxia in 4 seconds. Unless you buff micegang, this will only stay as a poor gimmick weapon.

**Comment by Kurfursten** [comment]
As per the original PR, transmogged mice get 7x health

**Comment by GreatBigFailure** [comment]
The idea is also for the user to come up with some clever way to contain the mouse. We have enough one shot kill guns that anything short of it will be gimmick status regardless. This is a very, very good gimmick though.

**Comment by Eneocho** [comment]
> 
> 
> As per the original PR, transmogged mice get 7x health

Ok, be moused. Enter a scrubber, die 28 seconds later.

**Comment by Dacendeth** [comment]
Not everything needs to be super powerful by default, seems fine how it is.

**Comment by juanototo2** [comment]
I just realized something.

This gun + hand tele + spacebase autism cube with telebeacon = ???
Also note that the mouser pistol stuns the resultant mouse when it successfully transmogs.
Boy this is going to be cancerous if someone actually manages to pull it off...

**Comment by Eneocho** [comment]
> 
> 
>spacebase autism cube with telebeacon

You mean a 3x3 no entrances space cube that can only be reached via teleporter? If so, yeah, very cancerous and most likely will happen within 2 days of this being merged. To build the 3x3 cube (1 tile of space) you don't need more than 40 sheets of metal. I tried acquiring the handtele, the metal, the hardsuit and making the 3x3 cube as a virologist. Literally took me less than 10 minutes. So it's not a question of _if_ people manage to make it, but _when_ will people choose to make it.

**Comment by Kurfursten** [comment]
Needs air if you don't want them to automatically revert back and scream for help, and if you grab a second person the first is just going to hop back through the portal. I'm not too worried about balancing around spacecube+handtele which always has the potential to be bad.

**Comment by Eneocho** [comment]
> 
> 
> Needs air if you don't want them to automatically revert back and scream for help, and if you grab a second person the first is just going to hop back through the portal. I'm not too worried about balancing around spacecube+handtele which always has the potential to be bad.

The air would ZAS in via the hand tele's portal, a single tile would suck so little air of a room that most sensors wouldn't blink. Perhaps one cuck cube per mice would do the trick.

**Comment by GreatBigFailure** [comment]
This doesn't require the mouse.
Parapen them, strip them, toss them in.
Hell put a straight jacket on them without stripping them.
Any number of things can infinitely trap a spessman. We have one shot kill guns, we have acid that can instantly kill you and melt heads. You can eat brains produced from a big kick with easily acquired boots. Very few people do these things because they're not fun. They suck. 
Same rule applies here. People would rather have fun than win, mostly. That's why gimmicks are a thing, a self imposed handicap disguised as a theme.

**Comment by Blithering** [comment]
Please give the janitor the discount instead of/ as well as CMO, janitor can speak mouse to taunt his victims.

**Comment by Eneocho** [comment]
> 
> 
> Please give the janitor the discount instead of/ as well as CMO, janitor can speak mouse to taunt his victims.

It actually makes more sense for the janitorial staff to have the mouser than the medical staff. I can barely remember the last time a virologist actually used mice, while janitors constantly deal with the micegang and the maintmice.

**Comment by Eneocho** [comment]
> 
> 
> Please give the janitor the discount instead of/ as well as CMO, janitor can speak mouse to taunt his victims.

It actually makes more sense for the janitorial staff to have the mouser than the medical staff. I can barely remember the last time a virologist actually used mice, while janitors constantly deal with the micegang and the maintmice.

**Review by ShiftyRail — APPROVED** [review]

**Pull request merged**
