### PR TITLE
EMP cult spell is now available in Act 1

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
This also was in my backlog actually and no I have cult set on never
Discuss
Also if any coder can comb through all the cultcode and tell me if there's something I missed except the spell's roman number tell me, testing was fine
:cl:
 * tweak: The EMP cult spell is now available in Act 1

### CODE REVIEW

**Comment by BomberBro** [comment]
Why contain it?

**Review by ShiftyRail — DISMISSED** [review]
The spell does not actually gib the officer. How can I expect cultists to know how to deal with bodies? This would expose them when they are most vulnerable.
Please correct

**Comment by boy2mantwicethefam** [comment]
Unatomic

**Comment by Kurfursten** [comment]
Of your 3 new cult PRs, this is the one I disagree with. EMP is a high value ability, and that means it **encourages the cult to move forward into act II.** We do not want the cult lingering in act I for a long time. Moving EMPs back into act I will encourage staying there longer as a shufflecult.

That said, this is not as bad as moving things from act III to act II which is really bad.

Code end: looks good, that is the proper define

**Comment by boy2mantwicethefam** [comment]
I think the cult already has enough motivations to move forward act-wise
- The objective of summoning Nar'sie
- The rest of the abilities
- Tattoos

**Comment by ShiftyRail** [comment]
No, they don't.
The only thing this PR encourages is to silently depopulates security on Act I, slog through Act II, and then raise bloodstones when there's no resistence left.

**Review by ShiftyRail — APPROVED** [review]

**Comment by boy2mantwicethefam** [comment]
You can do that in act 2.

**Comment by icantthinkofanameritenow** [comment]
Just ban this moron from the repo, he can't be trusted to not push stupid changes solely because he can't be a competent antagonist.

**Comment by boy2mantwicethefam** [comment]
That's just sad man

**Comment by ShiftyRail** [comment]
@boy2mantwicethefam i think there's significant difference between a dude using EMP's and Stun talismans to enact a plan to depopulate with only two points of failures (himself and the other cultists) than the same thing with at least six points of failure and much more time spent in the round (so more time for them to fuck up).

**Comment by boy2mantwicethefam** [comment]
You can save me some paragraph typing if you tell me whether you want to be convinced or not

**Comment by PavelCIA** [comment]
hahaha nigga how are SPS real just like crush a dans bar haha nigga just like make a mortar

**Comment by icantthinkofanameritenow** [comment]
> You can save me some paragraph typing if you tell me whether you want to be convinced or not

No, you're the one who's supposed to be convincing other people that the SPS is such a big fucking deal that act 1 cult has to be OP just to work around it. (Protip: NOBODY ever bothers to look at the SPS.)

**Comment by aceedex** [comment]
While I don't dislike the idea of being able to grab a high value target in act 1if cultists feel bold I think moving the emp rune down an act is very very dangerous for the reasons shifty described. It might be a bit more work but what would work for me is an early limited version of the emp rune that has a channel time and a tough blood cost when invoked. This way if you wanted to funny paper and convert the captain early on and get all access man on your side you'd need to work with another person to make it happen with much lower risks

**Pull request closed without merging**
