### PR TITLE
Revert "NOBODY (almost) has maintenance access"

### PR DESCRIPTION
**Pull request by jknpj**
Reverts vgstation-coders/vgstation13#25113

7 days.

:cl:
 * tweak: the following jobs have maintenance access again: miner, chaplain, librarian, clown, mime, assistant

### CODE REVIEW

**Comment by ghost** [comment]
I killed my dumb shit of an experiment for this glory

I'm pleased

**Comment by coldcola** [comment]
revert now

**Comment by juanototo2** [comment]
Speedmerge

**Comment by ghost** [comment]
Save our boys assistants.

**Comment by SonixApache** [comment]
7 days is too long, undo it after 1

**Comment by SkowronX** [comment]
fuck

**Comment by PrimeDSS13** [comment]
speedrevert when

**Comment by IzayaChan** [comment]
Just remove maint from all maps.

**Comment by Kammerjunk** [comment]
maybe don't be retarded with ideas that are 16/22 when merged and 16/30 right now

**Comment by Senaat1** [comment]
Based PR, please merge ASAP.

**Comment by SonixApache** [comment]
good experiment

**Pull request merged**
