### PR TITLE
Makes Plasmamen Take 1.5x Brute Damage

### PR DESCRIPTION
**Pull request by Shadowmech88**
In an effort to make them something other than "humans, except better" in combat.

### CODE REVIEW

**Comment by ScrambledSteak** [comment]
make plasmamemes bleed too

**Comment by Shadowmech88** [comment]
One step at a time.

**Comment by ScrambledSteak** [comment]
make plasmamemes turn to ash if they take over 300 damage

**Comment by jknpj** [comment]
- Make them bleed
- Remove their burn resist if they are exposed to o2
- Make their biosuits destroyable by burn damage

Go away with your multiplier, it'll fuck their PVE so much that is not even funny.

**Comment by 9600bauds** [comment]
Bleeding would be bonkers because they couldn't bandage themselves, they're stuck in a suit remember
Since bleeding happens via brute, a higher brute modifier would be enough to offset the nobleed
I think this is a good and necessary change honestly, slapping bleed on top of that would be just silly because you're piling up two weakness in the same damage type

**Comment by jknpj** [comment]
You can remove your suit to bandage yourself without dying just fine.

**Comment by kol1th** [comment]
> Make their biosuits destroyable by burn damage

Time to griff every plasma man.

> You can remove your suit to bandage yourself without dying just fine.

Completely counter intuitive. With Vox, it's fine, since you don't light on fire and fuck up your body temp, but plasma men, well... Light on fire and fuck up body temp.

**Comment by jknpj** [comment]
> Light on fire and fuck up body temp.

It goes back to normal when you put back the suit. I see no issue.

**Comment by FudgePucker** [comment]
Vox take toxin damage that has a chance of organ failure.

Plasma men resist burn damage.

**Comment by NigglyWiggly** [comment]
> Make their biosuits destroyable by burn damage
> 
> Suit containing highly volatile material that has built in extinguishers to prevent the often-on-fire contents from catching on fire
> 
> Can be burnt apart

HONK

**Comment by jknpj** [comment]
They had to be cheap with the suit's outside part. It does not protect from burn damage, after all.

**Comment by Probe1** [comment]
1.75 is too far.

1.5 is pretty high.

1.25 is eh ok.

**Comment by TheFriggenSawbones** [comment]
raise the burn multi to 0.75 reduce the brute multi

**Comment by The-Albinobigfoot** [comment]
In my unbiased opinion, this is a much needed change.

God bless, Shadowmech88.

**Comment by Shadowmech88** [comment]
Given that plasmamen now take 50% burn damage instead of 25% due to a recent bugfix, I'll reduce this to 1.5x.

**Comment by Shadowmech88** [comment]
Changelog added.

**Comment by ghost** [comment]
1.25 sounds more fair - start small and aim high.

**Comment by Shadowmech88** [comment]
Bear in mind that they still have no blood, which makes brute damage much less of a threat to them than it is to the other races.

**Comment by TheFriggenSawbones** [comment]
blood loss isn't that big of a threat in a fight, exceptions would be a welder bomb, floor tiles, maybe a revolver?? (I shot a few people it takes a long time for them to go down from blood loss)

and like isn't the issue that the burn protection is really high for some reason, making us gib from zas might not be the right answer??

**Comment by TheFriggenSawbones** [comment]
still the brute multi is too high, and don't most of the complaints come from the burn res?

Can't we just like make the numbers for both sides small

**Comment by jknpj** [comment]
Why don't just make them bleed? Giving them a brute damage multiplier even bigger than skeletons' multiplier will render their PvE unplayable.

**Comment by TheFriggenSawbones** [comment]
so I did some science,

at 1.5 brute multi -

1 revolver shot is 137.5~ damage
two esword slashes do 136~ damage
Three Floor Tiles will, on average, put the player into crit. or leave them in the 99~ brute area.
One shotgun to the face is an instant kill, at 210~ damage. From one tile away, 137 damage.
Four Telebaton hits to crit.
Five~ Stun Baton hits to crit.

1.5 is way too high, especially considering brute weapons are way more common than lasers.

**Comment by jknpj** [comment]
All i think when i see these PRs about brute damage multiplier is: GOLIATH SMASH

**Comment by ComicIronic** [comment]
@clusterfack

**Comment by Blithering** [comment]
Don't forget our old friend ZAS. Any plasmaman slamming into a sheet of paper or a pencil is not gonna be walking away from it.

**Comment by 9600bauds** [comment]
Sawbones are you sure about these numbers
I think you might be confusing 1.5x for 2.5x
Or you tested this with the bug still in

**Comment by TheFriggenSawbones** [comment]
@9600bauds 
What bug are we talking about here?

And i'm sure, I forked a new repo and added in the 1.5 brute multi.

**Comment by TheFriggenSawbones** [comment]
Ok I just tested it again. Forked a new repo and blah blah. Yeah the numbers are correct.

**Comment by clusterfack** [comment]
The bug where effects are doubled is still in, this will probably be fine once that is merged

**Comment by TheFriggenSawbones** [comment]
ok my b friends

**Comment by Shadowmech88** [comment]
@jknpj 

> Giving them a brute damage multiplier even bigger than skeletons' multiplier will render their PvE unplayable.

Skeletons have a brute multiplier of 2x.

**Comment by jknpj** [comment]
Shocking truth I could swear it was 1.3

**Comment by NigglyWiggly** [comment]
Nah, Skeletoes are super brittle.
Like ridiculously so

**Pull request merged**
