### PR TITLE
Reloading with ammo boxes as a loop of quick single-bullet reloads

### PR DESCRIPTION
**Pull request by Securitymain**
[gameplay]
## What this does

Changes reloading with ammo boxes to be chained-together single reloads, adds sounds to it and to fumbling.
Removed the "Now loading x..." when starting a reload action. You get both a visual(Loading bar, icon states changing) and audio representation of the fact that you are, indeed, reloading. Also a code reason but I don't want to get into that

Video of it: https://streamable.com/0orkyr (Still has the Now loading...)
Turn up your volume

## Why it's good

Currently when using ammo boxes, it's all or nothing. You get a long timer and if you get cancelled at some point, you don't reload anything and a random number of bullets from 1 to however-many-you-have gets dropped on the floor. This is both unrealistic and unfun. 

With this PR, this changes. There will also be a sound for reloading and when dropping bullets on the floor due to fumbling.
There is both a buff and a nerf in this:
+ You can do partial reloads. Get back into the fight quicker. Realism.
- No more multi-box reloading. You used to be able to, say, load 3 * 10 magazines from a single 30 round box. No longer, reload one at a time. Willing to make the reload faster in exchange if people dislike this, but I think the buff/nerfs counter each other well. Also +realism

The total reload speed remains the same

This changes quite a bit of code, I would greatly appreciate it if someone ran this locally and tested some cases, I could have missed something.
I checked: 
- Whatever's in the video
- Trying to load a 357 with 380 and vice-versa
- Spamclicking the same magazine

Or we just merge this and see what happens

## Changelog

:cl:
 * rscadd: Sounds for reloading with ammo boxes
 * tweak: Reloading one bullet at a time with ammo boxes. Allows partial reloads!

### CODE REVIEW

**Comment by Theophrastus1** [comment]
imagine updooting your own pr

**Comment by SonixApache** [comment]
would updoot but you updooted your own PR so you should be repobanned

**Comment by Securitymain** [comment]
Imagine not being a narcissist

@Dacendeth @SonixApache @djkramer123 @Theophrastus1 u win

**Comment by Eneocho** [comment]
sovl...

**Comment by kilozombie** [comment]
>There will also be a sound for reloading

Extremely good, we need more stuff like this

**Comment by Playyne** [comment]
Something I feel is missing is a way to interrupt a reload without fumbling, like declaring that after the current load is done, you stop. And I don't like the unresponsiveness when you click on a different magazine while loading, something should happen there. Like set a flag in the attack_self and attack procs that interrupts the reload loop if you use the box or click on a different mag, if that is possible to do.

**Comment by Eneocho** [comment]
Make it so it mocks you if you reload after a single shot more than once.

**Comment by Securitymain** [comment]
> Something I feel is missing is a way to interrupt a reload without fumbling, like declaring that after the current load is done, you stop. And I don't like the unresponsiveness when you click on a different magazine while loading, something should happen there. Like set a flag in the attack_self and attack procs that interrupts the reload loop if you use the box or click on a different mag, if that is possible to do.

Might do this if this isn't merged by tomorrow or so

actually pls. merge, if i do this itll be a new pr

**Pull request merged**
