### PR TITLE
Breaking out of cuffs and buckles is instant for hulks instead of 5 seconds each

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Just shoot them if they do this. Also technically applies to xenomorphs but they are terrible code and almost literally nobody in the last few years has even attempted to cuff a xeno because xenos are already unstunnable.
The PR was done on request.

:cl:
 * tweak: Hulks now break out of cuffs and buckles instantly.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Travis fails to compile because of a slip check?

**Comment by ShiftyRail** [comment]
:-1: because I don't want to have to shoot people down as a first response.

**Comment by boy2mantwicethefam** [comment]
You won't have to unless they hulk out to break out of places, arguably you still have to shoot people down currently for being hulks.

**Comment by SonixApache** [comment]
I'm okay with this, makes it more obvious that you should just kill the guy instead of trying to stun/cuff him again.

**Comment by Dacendeth** [comment]
I have to thumbs down just because I cuff xenos at all available situations to do so.

**Comment by SGuivenne** [comment]
Can you make it so cuffing xeno larvae still works well as a compromise?

**Comment by boy2mantwicethefam** [comment]
You can cuff larvae? Aren't they simplemobs?

**Comment by PrimeDSS13** [comment]
cuffing larvae prevents them from evolving when

**Pull request closed without merging**
