### PR TITLE
64x64 AME Blob

### PR DESCRIPTION
**Pull request by JMWTurner**
blobb
hurtblob

making blob: https://dl.dropboxusercontent.com/u/33846352/blob1.webm
expanding blob: https://dl.dropboxusercontent.com/u/33846352/blob2.webm
hurting blob: https://dl.dropboxusercontent.com/u/33846352/blob3.webm

:cl:
* rscadd: Added a 64x64 version of the AME blob that looks a bit more like the actual AME.

### CODE REVIEW

**Comment by kol1th** [comment]
Will it lag as much as newblob

**Comment by JMWTurner** [comment]
newblob doesn't lag. It's pulsating animations have been removed. It has less sprites than newblob though, so to answer your question, no it will lag less.

**Comment by kol1th** [comment]
Tell that to my client when it drops to 10 fps looking at newblob

**Comment by JMWTurner** [comment]
Did you look at it today? Skullyton's update was yesterday.

**Comment by ghost** [comment]
Now we're talking

**Pull request merged**
