### PR TITLE
Re-adds malf mode.

### PR DESCRIPTION
**Pull request by MadmanMartian**
- Adds two procs to factions. process (called every time gamemode process is called by the gameticker) and check_win (if 1, game-mode reports that it's finished to the gameticker, triggering smelelele)
- Adds required_role to role.dm. A list of roles that this role will only accept.
- Re adds malfunction mode.

### CODE REVIEW

**Comment by Aurx** [comment]
Merge ASAP, server need its hot milfs.

**Comment by ShiftyRail** [comment]
Antag datums NOW

**Comment by Chazach** [comment]
lads this is our only chance to remove malf for good
dont let it pass you by

**Comment by DeityLink** [comment]
we should place [DATUMS] before pr titles so people don't get confused.

**Comment by DamianX** [comment]
eh, we have the role datums label already

**Comment by ghost** [comment]
Daily reminder the best way to play malf is to just be malfunctioning instead of killdudes blitz. All hail our datum overlords providing other antags to create a power vacuum to justify the milf becoming the hero of man

**Comment by Aurx** [comment]
Daily reminder that the best way to play milf is to do jack fucking shit since the carbons will kill each other or go braindead for you once you wait a few hours.  Or you'll get valided by a meta gay man or outed by a shitborg that breaks direct orders, but that's the risk you take.

**Comment by ghost** [comment]
rib

**Pull request merged**
