### PR TITLE
Blacklist insectoids from service and medical

### LINKED ISSUE #25779: Solution to the roach question
#### Description of issue

Roaches shouldn't be able to have any other job than civilian jobs and engineering.
It make absolutely no sense than a sentient bug would be a security officer in a corporate-state station.
They probably lack the lifespan to do the studies required for medical/science.

That's all.

### PR DESCRIPTION
**Pull request by ghost**
Blacklists insectoids from chef/bartender and all medbay roles except geneticist. This should hopefully placate those who wish to "solve" the "roach menace".

Fixes #25779

### CODE REVIEW

**Comment by Irradiation** [comment]
>except geneticist

It's perfect, geneticists are the worst scum and never leave genetics (or even enter cloning), so nobody will mind!

**Comment by boy2mantwicethefam** [comment]
Do that for vox instead

**Comment by ShiftyRail** [comment]
I will have no roaches in my security force

**Comment by beesil** [comment]
If the argument is that they don't have long enough lifespans to become doctors, you should change the in-game age range to reflect that. 

Also remove the paramedic restriction as it's a six month program for EMT-B and a two year associates for EMT-P (paramedic) in the US.

**Comment by ghost** [comment]
actually I'm just gonna accept this was a dumb idea

**Comment by SonixApache** [comment]
the only dumb part was that you didn't blacklist them from everything

**Comment by SageOfLight** [comment]
image

**Comment by tuypo1** [comment]
Fuck no, when I roll up to play surgeon I don't want there to be less chance of somebody else having signed up to do the boring ass chemistry part of medbay

**Pull request closed without merging**
