### PR TITLE
Sec Snowmobile

### PR DESCRIPTION
**Pull request by Kurfursten**
image
image

image

Its headlights alternate between red and blue, and it needs its personal key (not universal).

Check out icondiff to see new security-red paintjob.

No CL because not located anywhere yet.

### CODE REVIEW

**Comment by ghost** [comment]
Could they be lighter versions of red and blue, given police cars don't tend to drive with their regular headlights turned off but sirens on? It is a cool feature.

**Comment by Kurfursten** [comment]
I think in practice you're going to have your tactical light on anyway

**Comment by ghost** [comment]
That's a fair point, I guess.

**Comment by Caboozles** [comment]
Can you add a totally unnecessary yet hilarious emag function? Asking for a friend

**Comment by Kurfursten** [comment]
Someone could I guess

**Pull request merged**
