### PR TITLE
Hotfixes for Snaxi

### LINKED ISSUE #24006: snowmap library keycard device
image
what is he doing there hahaha!

### PR DESCRIPTION
**Pull request by plosky1**
Basically Kharkov's V3 somehow broke interpolation through something he did on the .dmm file, which strangely also at the same time lowered holomap init from ~150 seconds to 30 seconds. While this lowered time was nice, interpolation being broken was not nice, so I took V2, made all the same hotfixes, and tested it. It works, but we're stuck with the same shitty ~150 second init time.

More forest, cave system's been expanded.

Also fixed #24006 

[snowmap]
[tested]

:cl:
 * rscadd: Snaxi pipes are less gunk, and interpolation should be fixed. Trees have grown, there's been a disturbance in the force, and strange radio signal are being picked up from somewhere on the station...

### CODE REVIEW

**Comment by SonixApache** [comment]
magic

**Comment by ShiftyRail** [comment]
Is this good to merge

**Comment by plosky1** [comment]
Yes

**Comment by plosky1** [comment]
Since this STILL hasn't merged:

The trees have begun to take over, there is now a forest in the South.

A great disturbance has been felt in the force-, err, I mean caves. It seems Luke wasn't so lucky this time.

Nanotrasen Anti-Syndicate systems have been picking up strange wavelengths, the crew may want to check it out but it will definitely be perilous.

**Comment by plosky1** [comment]
Fixed #24006 since not merged yet

**Comment by SonixApache** [comment]
put that in the OP then

**Pull request merged**
