### PR TITLE
Fixed a long-standing bug that affects lights in regards to opaque atoms being destroyed.

### LINKED ISSUE #2145: Metal Foam creates lighting artifacts when you destroy it.
lighterror

This has been in the game for a long time.

### PR DESCRIPTION
**Pull request by DeityLink**
light_update
- Fixed lights not updating when a wall is destroyed (by thermite or a juggernaut's punch for example)
- Fixed lights not updating when a door is destroyed (by C4, or if manually deleted by an admin for example)
- Fixed lights not updating when removing metal foam/smoke, which caused areas to remain permanently dark after a metal foam grenade went off in it. Which I had reported and fixes #2145.

### CODE REVIEW

**Comment by clusterfack** [comment]
Protip deity. When fixing an issue use fixes #issue to autoclose the issue when your pull is merged.

**Comment by DeityLink** [comment]
apparently adding it in the comments section works as well.

**Comment by clusterfack** [comment]
Oh? Good. Yeah we can do that now because we are merging into the default branch now BE and that's what github checks for.

**Comment by ComicIronic** [comment]
I think it would be more sensible to add the opacity line to /atom's Destroy, just to cover all the bases.

**Comment by DeityLink** [comment]
SetOpacity isn't the lightest of procs, I don't think that's necessary, plus that bug wasn't occurring with all opaque atoms (it didn't happen with Mechs for instance). I believe it's good as it is.

**Comment by ComicIronic** [comment]
It's light enough. Any atoms without opacity don't run lighting updates, but those that do will fall under a more general solution than having to add a load of code lines unnecessarily.
If this problem comes back for more atoms in the future, it'll just require more kinds of patchwork. Movable atoms already have a general code for opacity in Destroy.

**Comment by DeityLink** [comment]
oh fine

**Pull request merged**
