### PR TITLE
Add Lights to Gold Hardsuit Helmet

### PR DESCRIPTION
**Pull request by falcon2346**
## What this does
Adds lights and appropriate sprites to the gold atmos hardsuit helmet
[qol]

## Why it's good
Someone might actually use the golden hardsuit instead of leaving it sitting on the table every round.

## Changelog
:cl:
* tweak: The gold hardsuit's helmet now puts out light just like all the others.
* imageadd: Added new sprites for gold hardsuit helmet with light

Ghardsuit

### CODE REVIEW

**Comment by pedr69** [comment]
don't tell them about the toolbox slot

**Comment by jwhitak** [comment]
The golden suit is a sidegrade. You sacrifice some features for other features. You lose the plasma atmos protection but gain a whole ass toolbox storage slot. And now you don't even lose the funny hardsuit lights!

**Comment by NigglyWiggly** [comment]
This feels wrong on a fundamental level.
I don’t have any actual opinion on whether or not this gets merged but it feels morally wrong

**Comment by SonixApache** [comment]
it doesn't have a light on it for a reason
that said you can circumvent it with tac-lights anyway so
powercreep ahoy

**Comment by falcon2346** [comment]
As a frequent player of Atmos Tech myself, I find the slower movement speed to be a bigger deterrent to using it than the lack of a light, especially since Atmos Techs have access to mesons and you can just turn on your PDA light. You'll have both on you most of the time anyways. I suspect that even with the addition of the light it probably won't be used frequently, but it might get some use as opposed to none.

**Comment by jwhitak** [comment]
I am going to agree with falcon here. The pda light and mesons are usually enough to get the job done. Worst case, you could just put a flashlight in your pocket. This is mainly quality of life. The slowdown is the real kicker of the suit, but it HOLDS SO MUCH STUFF IT'S UNREAL. Adding a light on the thing won't break things. Just save a pocket slot from needing a flashlight. 

Also, the suit lights use up your suit battery. Keep that in mind. It's rare for suits to run out of power from using the lights all the time, but it has happened in the past...

**Comment by bathosbathtime** [comment]
It didn't have a light because you painted over it with the gaudy gold paint job. The joke! You killed the joke!

**Comment by falcon2346** [comment]
I'm sorry, I didn't know. I'm a true monster 😔

**Pull request merged**
