### PR TITLE
Updates insectoid monkey form

### PR DESCRIPTION
**Pull request by kestoloppu**
## What this does
Monkey form insectoids now use an animated isopod sprite akin to diona nymphs instead of reusing the sprite for giant roaches.
isopod
Sprites by SageOfLight

## Why it's good
Look at he go 
glubby

## Changelog

:cl:
 * imageadd: Added isopod sprites.
 * tweak: Insectoid monkey form changed from giant cockroach to giant isopod.

### CODE REVIEW

**Comment by angryturnip** [comment]
I like it but it actually ruins my roach chaplain gimmick where I breed a bunch of roaches and then ascend to roachhood

**Comment by Kurfursten** [comment]
I feel like these need a holder so you can pick them up like diona; this would also mean they need inhands + onhead sprite

**Comment by kestoloppu** [comment]
> I feel like these need a holder so you can pick them up like diona; this would also mean they need inhands + onhead sprite

I didn't include the ability to pick them up like you can with nymphs since you can't actually pick up other monkey'd species like humans or greys, but that's something to consider for a future pr.

**Comment by Eneocho** [comment]
Change the name and path to the insectoid monkeycubes (#32322) for consistency.

**Comment by Eneocho** [comment]
I DEMAND the ability to wear the isopods as a hat.

**Comment by Eneocho** [comment]
Also the path for said cubes, or there will be an inconsistency when mapping/bussing, since they're no longer roaches.

**Comment by cloutcode** [comment]
if i saw that damn thing in my bar i would stomp on it until it was a small brown stain

**Comment by kestoloppu** [comment]
> Also the path for said cubes, or there will be an inconsistency when mapping/bussing, since they're no longer roaches.

I think I've done this correctly but correct me if I'm wrong. I have not changed the name or pathing of /mob/living/carbon/monkey/roach because I'm pretty sure that would require deleting the roach.dm file and replacing it with an isopod.dm file and I'm not confident I can do that properly without breaking everything.

**Comment by Viciousaurus** [comment]
Too adorable.
I want ugly roaches so I can be racist against them

**Comment by Eneocho** [comment]
You could rename the roach.dm file (and change the [dme include](https://github.com/vgstation-coders/vgstation13/blob/19612aba969fbd5d3563dfc1e797e06c3f11c724/vgstation13.dme#L1939)), but this is good enough.

**Comment by ManopolisJones** [comment]
hey, be sure to add a meatspike sprite for when it's time for cooking

**Comment by Kurfursten** [comment]
Gonna add a meatspike sprite?

**Comment by Eneocho** [comment]
i want to be able to wear an isopod as a hat, like you can with diona.

**Comment by bathosbathtime** [comment]
Oh, just noticed the vote tag. On it.
EDIT: Server vote made.

**Comment by Kurfursten** [comment]
This PR didn't actually need a server vote and I have no idea why he self-tagged that

If anything, the vending machine UI one is the one that needs a server vote

> i want to be able to wear an isopod as a hat, like you can with diona.

That's fine to request but at the same time I'm not going to force him to fulfill a feature request to get a merge

**Comment by kestoloppu** [comment]
> i want to be able to wear an isopod as a hat, like you can with diona.

I didn't want to add diona nymph features to insectoid monkeys since they don't currently have those abilities. This is just a sprite change for now but that's definitely something to consider for a future PR.



> Gonna add a meatspike sprite?

Not for this PR since only monkeys, humans, and xenos have unique meatspike sprites currently, iirc.

Special thanks to pomf for figuring out the hat issue! Masks and hats should now (reasonably) fit isopods and backpacks were slightly adjusted for a better fit. This PR is ready for merging unless there are any other issues with it.

**Comment by Eneocho** [comment]
>since only monkeys, humans, and xenos have unique meatspike sprites currently, iirc.

Diona nymphs have them too. See #6646.

**Pull request merged**
