### PR TITLE
Fixes mesons and night vision not changing vision when combined with x-rays.

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
[tested]
Finally a legitimately good change/bugfix
Captain
:cl:
 * bugfix: The lighting now properly changes when you use mesons or night vision goggles in combination with the x-ray superpower

### CODE REVIEW

**Comment by jknpj** [comment]
If you want people to take these seriously please stop using 100% tested for everything.

**Comment by boy2mantwicethefam** [comment]
Sure

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
The functionality "works" but this fix is incredibly hardcoded. I haven't investigated how to fix it properly (probably max()ing something in handle_glasses_vision_updates()) but I can tell you this is unacceptable

You're checking for the types of 2 specific objects when you should at the very least be using their relevant see_invis var

**Comment by boy2mantwicethefam** [comment]
I'll look at it more in a bit. This fix is here because x-ray overwrites see_invisible from mesons and night vision to prevent situations in which taking off mesons would remove important visual flags granted by X-ray (three of them, see_mobs, see_turfs, and see_structures, removing mesons for example would remove see_turfs)
Any suggestions how I can fix it good?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
My intuition says this is probably not even the right place in the code to put the fix in seeing how much you had to hardcode it to make it work and that the correct fix is probably max()ing something in handle_glasses_vision_updates()

**Comment by boy2mantwicethefam** [comment]
Max-ing could work, I'll see what I can do with it

**Comment by boy2mantwicethefam** [comment]
handle_glasses_vision_updates is overwritten by x-ray being called every tick, and adding a minimum didn't work there. However, adding a minimum (maximum is not the right one because the less invisibility the more everything visible is, there are values, observer_no_lighting is like 15 while see_invisible_minimum is like 5) between the x-ray vision and anything that reduces visibility has solved the issue with far less item hardcoding and quite literally a few letters, calling for the minimum (more visibility) between x-ray and the user's see_invisible. Thanks!

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
:ok_hand:

**Pull request merged**
