### PR TITLE
Adds inhands to plushies (and an inhand generator Python script)

### PR DESCRIPTION
**Pull request by brndd**
## What this does

2023-11-22T10:56:15

Adds auto-generated inhands to all the plushies. They aren't as good as hand-drawn ones would be, especially because they're all forward-facing instead of having real dirs, but I think they're much better than nothing.

Also adds the script I wrote to create these. Maybe it will be useful later.

## Why it's good

Inhands good.

## Changelog

:cl:
 * rscadd: Added inhands sprites to plushies.

### CODE REVIEW

**Comment by brndd** [comment]
A couple of more screenshot examples. No way am I going to screenshot all of these damn things.

2023-11-22T00:06:15 2023-11-22T00:05:59
2023-11-22T00:05:05 2023-11-22T00:04:43

----

What it means for them all to be forward-facing:

2023-11-22T00:43:30 2023-11-22T00:43:19
2023-11-22T00:43:05 2023-11-22T00:42:48

**Comment by wotisjanitor** [comment]
remove the touhou ones

**Comment by nervere** [comment]
Holy based

**Comment by brndd** [comment]
Even when automatically generated inhands are a pain in the ass. I seriously hope I won't have to import all 408 sprites into DreamMaker manually and redo the couple of manual fixes these have ever again.

**Pull request merged**
