### PR TITLE
Medical Research Vault

### PR DESCRIPTION
**Pull request by Shadowmech88**
Resurrects #8968

medvaultnew

Filled with cyber horrors and a zombie.
Loot seems to consist of a meat cleaver, a stasis beaker, a large bluespace beaker, a beaker of mednanobots, advanced lungs, and a syndie balloon.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Don't merge this yet, spawning it in as a map element seems to break gliding and I don't know why.

**Comment by ComicIronic** [comment]
You have step_y set to 0 in an object in your map.

**Comment by ComicIronic** [comment]
This should not be passing the Travis check - we need to look at the script.

**Comment by Shadowmech88** [comment]
Okay, it's fixed now.

**Comment by Intigracy** [comment]
The script only applies to main map files, not to vaults.

**Comment by Kurfursten** [comment]
Is there a reason this is so cramped? A lot of 1-wide halls.

**Comment by Shadowmech88** [comment]
Don't know, I didn't make it.
I just saw a functional PR languishing in the closed PR list and decided to recover it.

**Comment by Probe1** [comment]
Replace the outer flooring that is exposed to space with plating 👌

**Comment by Shadowmech88** [comment]
Done.
medvaultnew

**Comment by SysadminJeroen** [comment]
Could you apply this patch? It fixes a typo.

```patch
From d5d30c658c1dd58fed61131f005700a4d0576a1e Mon Sep 17 00:00:00 2001
From: Jeroen de Neef <jeroen52@gmail.com>
Date: Fri, 20 Jan 2017 19:04:55 +0100
Subject: [PATCH] Fixes a VERY IMPORTANT typo. Changed `Medicial` to `Medical`.

---
 code/modules/awaymissions/pamphlet.dm | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/code/modules/awaymissions/pamphlet.dm b/code/modules/awaymissions/pamphlet.dm
index 8214960686..9aebe2ea68 100644
--- a/code/modules/awaymissions/pamphlet.dm
+++ b/code/modules/awaymissions/pamphlet.dm
@@ -38,7 +38,7 @@
 	return
 
 /obj/item/weapon/paper/pamphlet/medivault
-	info = "<b>Welcome to the Nanotrasen Research and Medicial facility...</b></br>\
+	info = "<b>Welcome to the Nanotrasen Research and Medical facility...</b></br>\
 			If you are reading this pamphlet then congratulations on your recent reassignment \
 			to this new, state of the art medical facility! You'll be involved in exciting and \
 			ground-breaking research projects and together with other Nanotrasen Medical \
-- 
2.11.0.windows.1

```

**Review by SysadminJeroen — APPROVED** [review]
I approve this typo fix, although `patch apply` was what I prefered.

As it would put the patch as a commit in this PR.
I'm kind of trying to increase my commit count.

**Comment by Shadowmech88** [comment]
I'm not sure if the extra commit would've mattered, all PRs are now squashed into a single commit before being merged.

**Comment by SysadminJeroen** [comment]
Thanks GitHub.

**Comment by PJB3005** [comment]
@Jeroen52 we still have the option for regular merges but squash merges are just much better because you can be a hilarious dork with the commit history and not be told to squash your commits.

Also, rebasing large PRs sucks and merge commits can't be squashed easily.

**Comment by SysadminJeroen** [comment]
@PJB3005 Sometimes commit history can indicate why you did something you did.

**Comment by PJB3005** [comment]
@Jeroen52 then you can open the PR in question and look at the commits. Squash merge commits include a direct link to the PR in question.

**Comment by Kurfursten** [comment]
I don't like this Vault's design. It has a lot of problems we should have caught, but notably a total lack of lighting is extremely annoying, not to mention weird since it's ostensibly a workplace with dead staffers

Also it seems a little over-defended for some minor loot, cyberhorrors three-shot ANYONE (meaning no amount of armor will save you, three hits and you're dead) and this vault has multiple. I guess not every vault needs to be appropriately difficulty balanced, but in the future if  I see this one, I'd probably just grab the cleaver and leave without fighting through any of the rooms with enemies. Since most space travelers are by necessity loners, the rewards of advanced lungs, stasis beakers, switch tools, and bluespace beakers (all more easily obtained at R&D and really only useful to trade to medbay) are not even worth investigating.

**Comment by Probe1** [comment]
I don't agree with the over-defended bit.  I've been there.  It's tough.  But a vault is nothing more than an interesting encounter.  There is no expectation for balance.  There isn't a graph where if X is this challenging it must have Y tier rewards.

**Comment by Kurfursten** [comment]
Maybe I don't like cyberhorrors in general. Three hits to gib anyone through any level of armor is very frustrating.

**Comment by Probe1** [comment]
I'm simultaneously with you and not.  I agree in a standard context a cyber horror is absolutely fucking ridiculous.

But for a vault they are different.  Vaults don't just carry inherent risk a la the Asteroid.  They are unknown structures you (as a NT Employee) weren't meant to go to outside the promise of safety guaranteed to you by NanoTrasen.

I could go for toning it down to a single cyber horror but really one or a dozen players will either have the tools to defeat a simple mob or they won't.

**Comment by Kurfursten** [comment]
Problem is the lack of consistency with medical mob spawners more than the vault itself, really

25% chance zombie - extremely easy to kill
25% chance skeleton - no problem
50% chance cyberhorror - you're fucked if you don't have guns

**Pull request merged**
