### PR TITLE
Boxstation sorting destinations and EVA access fixes.

### LINKED ISSUE #6023: (WEB REPORT BY: hurr REMOTE: 158.69.55.2:7777) Identification Computer bug
>Revision (Should be above if you're viewing this from ingame!)
38a6ba9be99e91b148dd67bcbd689cc586ead170

>General description of the issue
some of the accesses that you set on an ID with the Identification Computer are wrong.

>What you expected to happen
+
>What actually happened
for example, if you activate the access for "EVA" it doesn't give you the access to EVA; on the other hand, if you activate the access to "power equipment" it gives the access to EVA. i only tried EVA so i dont know how many accesses are wrong.

>Steps to reproduce if possible
use a blank ID and try to activate an access each time, then try to open the related door.

### LINKED ISSUE #6326: wrong destinations when sending parcels
(WEB REPORT BY: hurr REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
96874c752ecc178602a4043dc993fa92ad6cafb0

>General description of the issue
on Box Station, some of the destinations are bugged when sending parcels using disposal unit + destination tagger

>What you expected to happen
that every parcel reachs its destination

>What actually happened
BAR
if you send a parcel to bar, the parcel simply comes back to delivery office, coming out of disposal outlet after about 30-60  seconds.

THEATRE
if you send a parcel to theatre it arrives at the bar

CARGO BAY
A) if you send a parcel to cargo bay from the delivery office, it arrives at mechanics workshop instead;
B) if you send a parcel to cargo bay from the delivery chute (west side of cargo, near supply shuttle dock), it arrives at cargo's disposal unit

NOTE: i noticed that there is no label for mechanics workshop, so maybe the destination is right but the label is wrong; if this is the case you still need to fix point B anyway.

OTHER DESTINATIONS
all other destinations seem to work fine but i'm not 100% sure because i just tested them once.

>Steps to reproduce if possible
send stuff to all the destinations.

### PR DESCRIPTION
**Pull request by Faptastic**
- Fixes #6023 by setting the two main EVA doors to EVA access only and the eva/maint access to require both eva and maint.
- Fixes #6326 by completing the destination taggers list to include mechanics and telescience, retagged the 'BAR' pipe to actually register as the bar instead of the theatre, retagged mechanics workshop pipe to the new mechanic tag, swapped out a single pipe leading to telescience for a sort pipe and labelled for that. Tested by sending a crate via mailing to every single destination!
- A desk ball has been added to cargo and the cargo tech & QM have their pdas updated for the ringer
- Subtypes now exist for boxstation sortingjunction pipes but are currently unused pending refactoring.

This is my first map edit, I followed the instructions so I hope it's correct.

### CODE REVIEW

**Comment by PJB3005** [comment]
Instead of using instances in the DM mapper, you should make a subtype in the code with the edited variables, then place that.

**Comment by Zth--** [comment]
Now that you're on it, can you add a bell to cargo?

**Comment by Faptastic** [comment]
I can certainly try, I just realised i cocked up the eva maint access with a comma. Odd considering I'm pretty sure I tested that with a maint only ID, better fix that.
Do I just run the 2nd bat file again when I'm done and ready for another shot at it?

**Comment by unid15** [comment]
Don't bother with replacing that shit with subtypes I've still got the program which did #5930 and with a few tweaks it'll do it in a second

But if there aren't yet subtypes for the junctions then please add some

**Comment by PJB3005** [comment]
@Faptastic there aren't any subtypes, because people didn't think subtypes would be a good idea back then (oldcoder/mappers were idiots), if there isn't a subtype you make one.

**Comment by Kurfursten** [comment]
Make sure that everyone who needs it can still get into EVA. For instance, I am not 100% sure doctors have EVA access but there are medical hardsuits. Check for everyone to be safe.

**Comment by Faptastic** [comment]
Just adding subtypes now, everything else is sorted, including the desk bell, cargo staff have had their pda code updated to install the ringer and all that properly. I'm gonna give the internal doors of eva one last check, they sure as hell can't get in the entrance doors though.

@unid15  If you're gonna take care of it I'll finish up the subtypes but won't use them on the map. I'm trying to see if I can get away with setting their sorttypes via the destination tagger list so even if the list changes order in the future the pipes will accomodate. Otherwise they would probably need one for every single direction, the horror! 2 of the varedits are for direction and iconstate, the other is the destination.

**Comment by SkowronX** [comment]
Are miner pdas affected by the bell?

**Comment by Faptastic** [comment]
No, I didn't think they'd really want to put up with that nuisance while they're digging.
It's not really their job to staff cargonia though if they're passing through it's always nice to take some orders there. I'll add them to the list if people want though.

I've got the subtypes for the pipes mostly done, these are going to be pretty useless on maps besides box though on account of the direction and iconstate varedits. Not sure whether to actually implement them onto the map though if @unid15 is going to take care of it.

**Comment by unid15** [comment]
> these are going to be pretty useless on maps besides box though on
account of the direction and iconstate varedits
Don't see why they'd be useless on other maps (they only differ from normal
junctions by their tag, right? Vareditting the rest of the variables is
👌ok)

**Comment by Kurfursten** [comment]
Wait, you added new mail tags for telescience and mechanics but didn't update the other 3 maps to use them?

**Comment by Zth--** [comment]
Maybe we should have uniqe taggers for each map

**Comment by PJB3005** [comment]
Generally I'm fine with editing `dir` in the map.

**Comment by Faptastic** [comment]
As far as I'm aware everything is working as is now, The only thing I can imagine left might be the pipes being swapped over, perhaps instead of a subtype for every single destination, it's simply every direction of pipe and you instead varedit in the sorttype variable? In the grand scheme of thngs it seems a little cleaner but the potential to re-fuck up the tags will always be there, at least this way the only thing you screw up is failing to correct the direction, a more obvious error.

**Pull request merged**
