### PR TITLE
The grey market

### PR DESCRIPTION
**Pull request by SonixApache**
This adds a robust, fully player-driven economy system to the game.
Takes full advantage of already-present systems, such as the vox Trader role, Cargo's merchandise computer, custom vending machines, Assistant shops, etc.

🆑 
 - rscadd: Enabled the grey market; a player-driven economy system.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
>removing black market
>not even testing your stuff

Sonix................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by juanototo2** [comment]
>forcing people to check diff to see what it actually does
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>this shit changelog

**Comment by SonixApache** [comment]
i made this PR not so much because i am very against the black market but because the idea popped up in my head and i thought it would be funny

**Comment by juanototo2** [comment]
The emagged nikita emojicracy merging won't happen twice my red friend
Especially not with the goals of both being diametrically opposite

**Comment by Kharkov72** [comment]
ironic shitgrudgecoding is still shitgrudgecoding
I still think the emagged nikita funny as it is shouldn't have been merged and I feel the same about this

**Comment by FudgePucker** [comment]
>people calling the Nikita rocket launcher "not in good faith"

>This shitty fucking PR

**Comment by ShiftyRail** [comment]
[x] Based
[x] Brave

**Pull request closed without merging**
