### PR TITLE
Data Disk Inhand Sprites

### PR DESCRIPTION
**Pull request by DeityLink**
image
also include the xenobotany disk sprites

What started out as a virology PR and a tweak to GNA disks got out of proportion. Did I mention that I have ADHD?

Oh, and there's a grey default disk sprite.

:cl:
* imageadd: Added inhand sprites for all data disks
* tweak: The cloning data disks no longer have a random color
* tweak: The Design and Technology disk sprites have now a slightly different color
* tweak: Virus GNA disks are now properly tiny items.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
>ADHD

wait what

**Comment by DrSnips** [comment]
It means he gets high definition ads.

**Comment by ShiftyRail** [comment]
Kinda wish there still was green disks so you could hide the real one in a box of other green disks.

**Comment by DeityLink** [comment]
Implying that failOps wouldn't pick up the wrong disc anyway? Remember to spill all kinds of disk in the hallways during Nuke Ops

**Comment by bathosbathtime** [comment]
I will not support bullying color blind ops but I will support this PR it is very nice

**Comment by DeityLink** [comment]
swapped colors so that GNA disks remain red-orange like they've always be. cloning data disks will now be always blue-purple

**Comment by Kurfursten** [comment]
Broke icons for all shuttle destination disks

**Pull request merged**
