### PR TITLE
Fixes inconsistency with disassembling special chairs not giving back the materials it took to make them

### LINKED ISSUE #9276: Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Description of issue

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Difference between expected and actual behavior

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Steps to reproduce

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Specific information for locating

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Length of time in which bug has been known to occur

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Server revision

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by Intigracy**
stack_recipes.dm is just whitespace changes to make the file look nice since I looked in there for the recipe costs.

fixes #9276

### CODE REVIEW

**Comment by 9600bauds** [comment]
gneiss

**Comment by 9600bauds** [comment]
There's no good reason for a bugfix so simple to be left in the backburner for a week

**Comment by ghost** [comment]
Yes there is, it's called lazy maintainers

**Comment by Intigracy** [comment]
That's not a good reason.

**Comment by 9600bauds** [comment]
I said GOOD reason

**Pull request merged**
