### PR TITLE
Nanite Types for Black Market

### PR DESCRIPTION
**Pull request by ghost**
Adds the first of a variety of nanites to fit the theme of things like combat nanobots and medical nanobots. Black market exclusive.
:cl:
 * rscadd: Nanites added to blek market

### CODE REVIEW

**Comment by MadmanMartian** [comment]
image
Stop trying to add your weird mindbreak fetishes to the game, especially in the same way we asked you not to last time!

**Comment by bathosbathtime** [comment]
It STILL inexplicably changes toy descriptions, if you were wondering.

**Comment by Kharkov72** [comment]
how many times do we need to tell you that japanese nanites are gay

**Comment by AI-Is-Rogue** [comment]
baka desu

**Comment by ShiftyRail** [comment]
Beat me to it

**Pull request closed without merging**
