### PR TITLE
Jungle Fever

### PR DESCRIPTION
**Pull request by Kurfursten**
Honestly this was a massive waste of time but oh well

🆑 
* rscadd: Jungle Fever is migrated to datums. It still can't get started without adminbus.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
:thinking:

**Comment by Kurfursten** [comment]
I mean I guess I could make it a 91 threat roundstart only ruleset

**Comment by DeityLink** [comment]
>/datum/disease/jungle_fever

@Kurfursten we're phasing out those old disease datums, any chance you could instead do it just like the Vampire Disease touch? A single stage pathogen, which may also be cured now.

**Comment by Kurfursten** [comment]
The disease doesn't do anything at all, having it inside you is what makes bites monkeyize people in monkey combat code

I'm not going to clean up the code any further than I have since people don't want it as a mode, honestly I shouldn't have put this much in but it annoyed me that monkeys weren't easily visible as antags on advanced who or antaghud when I bussed it for april fools

**Comment by DeityLink** [comment]
guess I'll do it later.

**Pull request merged**
