### PR TITLE
Lambo Bloody Item Overlays

### PR DESCRIPTION
**Pull request by 13spacemen**
## What this does
instead of every item having its own special bloody sprite icon, every item uses the same one with the power of mutable appearances

## Why it's good
faster and better code

## Changelog

:cl:
 * rscadd: Bloody item overlays are way faster
 * bugfix: Fixed bloody overlays not going away upon cleaning in some circumstances.

### CODE REVIEW

**Comment by DeityLink** [comment]
Players won't notice it being faster. A more tangible change to include in your changelog would be:

* bugfix: Fixed bloody overlays not going away upon cleaning in some circumstances.

**Comment by PrimeDSS13** [comment]
Does this look any different? If it does, please provide pictures.

**Comment by 13spacemen** [comment]
> Does this look any different? If it does, please provide pictures.

no visual changes

**Comment by SECBATON-GRIFFON** [comment]
> Players won't notice it being faster.

wonder how you do include performance changes in PRs then if it's not obvious outside of profiling

**Comment by DeityLink** [comment]
You can mention it. My point was specifically regarding the changelog. Players care more about tangible changes.

**Comment by angryturnip** [comment]
Adam PTSD

**Review by jwhitak — CHANGES_REQUESTED** [review]
Can you run some profilers for this PR? Specifically, memory before PR and after PR. Additionally, differences in map startup times. @DamianX brought to my attention something a while back regarding lists in type definitions. They have to be allocated, which in byond automatically adds a new Init() proc to everything, increasing memory use and general load times for large maps. Considering Byond is 32bit, we *technically* should try to keep memory usage down. And players don't like the added load time to get in the game.

A suggested fix for this is to make the list into a "lazy list". This is done by removing the ``= list()`` definition, leaving it null, and having a new list generated when initially used (in this case, a new blood overlay), and destroying the list (= null) when empty (blood all gone). It's faster and easier on the memory to check for a null entry and generate a new list when needed than it is to generate a new list for every single atom in the whole game at load time.

Moving the ``= list()`` to ``New()`` actually wouldn't be too great either, though tecnically an improvement over the current implementation. We want to avoid having memory allocated to it unless absolutely necessary considering it's all atoms in the game.

This has also been brought up to @DeityLink who authored moodylights and added a list definition to atoms.

**Comment by DeityLink** [comment]
Indeed, I've made a PR to correct that for moody lights #36443

**Review by jwhitak — APPROVED** [review]

**Comment by jwhitak** [comment]
All righty, let's give it a shot.

**Pull request merged**
