### PR TITLE
Deff holodeck

### PR DESCRIPTION
**Pull request by Lokiamis**
whoops took longer than I meant to

untitled

### CODE REVIEW

**Comment by ghost** [comment]
The one room in maint doesn't have a door to it anymore, the one with the greyshirt poster

**Comment by Lokiamis** [comment]
Hidden door.

**Comment by Sprok0** [comment]
The holodeck control room looks like it has a connector instead of an air vent

**Comment by Lokiamis** [comment]
Hahaha fuck me

**Comment by CptWad** [comment]
needs more garbage between showers

**Pull request closed without merging**
