### PR TITLE
Totally refurbish Snaxi Security Station

### PR DESCRIPTION
**Pull request by ghost**
I put my grubby fingers into everything as far as the Security Station goes, so beyond the two gigantic overview screenshots I took, well... gonna have to trust me. Or open the map in DM and check it yerself

Here's an attempt at a changelog:

- Snow Station Security Station has been totally refurbished. Most rooms have extra tiles to work with and a layout that looks less like a tornado went through. If there is ANY issue on the Security Station, forward it please. Tis not too late
- Snaxi Bridge now has all the computers it should have and looks a LOT better, with a window bay that's now secured. Captain's Office has been fixed up to not be so stacked up. Vault now has extra goodies locked away
- Snaxi Chapel has been improved a bit. The maint access that went outside has been moved above it instead of below to make place for some hallway and Bridge extensions
- Snaxi Security Department has been improved a lot bit. More windows so you can actually see around (especially important sightlines like HoS to Armory and Warden to Brig Cells). Armory is bigger and now has a LOT more stock and should be equivalent to Boxstation (unique gear like segways, combat shotties and the mosin nagants were preserved)
- Snaxi Arrivals and Escape has gotten a massive decoration budget and layout improvement and the security checkpoint gimmick that literally no-one used ever has been nuked. Equally, the actual Escape bay now looks more like the other maps instead of being tight and dark
- Snaxi Mining and Xenoarch Bay now looks less dumb and the layout has been improved
- Some minor improvements to other things like the parkings (now fancier and extra spot). Other station reworks pending

scrnshot1
scrnshot2

:cl:
 * rscadd: Snow Station Security Station has been totally refurbished. Most rooms have extra tiles to work with and a layout that looks less like a tornado went through. If there is ANY issue on the Security Station, forward it please. Tis not too late
 * rscadd: Snaxi Bridge now has all the computers it should have and looks a LOT better, with a window bay that's now secured. Captain's Office has been fixed up to not be so stacked up. Vault now has extra goodies locked away
 * rscadd: Snaxi Chapel has been improved a bit. The maint access that went outside has been moved above it instead of below to make place for some hallway and Bridge extensions
 * rscadd: Snaxi Security Department has been improved a lot bit. More windows so you can actually see around (especially important sightlines like HoS to Armory and Warden to Brig Cells). Armory is bigger and now has a LOT more stock and should be equivalent to Boxstation (unique gear like segways, combat shotties and the mosin nagants were preserved)
 * rscadd: Snaxi Arrivals and Escape has gotten a massive decoration budget and layout improvement and the security checkpoint gimmick that literally no-one used ever has been nuked. Equally, the actual Escape bay now looks more like the other maps instead of being tight and dark
 * rscadd: Snaxi Mining and Xenoarch Bay now looks less dumb and the layout has been improved
 * rscadd: Some minor improvements to other things like the parkings (now fancier and extra spot). Other station reworks pending

### CODE REVIEW

**Comment by BomberBro** [comment]
- Add a second secvend, only packed has a single secvend and the map is made for a third of the pop

- An area to interrogate/process people is kinda hard to fit in the small area, but you may want to add a table and two chairs in either the room outside perma or the room with the cells

- No camera/records consoles accessible by officers in the brig

- Brig medbay needs an oxy kit and a anti tox syringe if we're going by b*x standard. I think something a bit thematic like an advanced space blanket would be neat too

- Perma botany has no tools, may want to put the vendors outside to make it a bit more spacious

- The courthouse cuck cube chair should be wooden

- Evidence storage is really easy to break into and steal from since it's only one hacked door away with maint access, maybe add a shutter or an immobile lockable closet for evidence instead like on deff

Other than that looks excellent, armory got a much-needed tune up.

**Comment by brndd** [comment]
why is there a shutter from the armory into the infirmary?

**Comment by ghost** [comment]
Sadly it's the only way you can reasonably do it seeing the Security setup. I already did a pretty massive cleanup, but maybe by exploding and refurbishing the rooms you can about fix it

**Comment by ShiftyRail** [comment]
No carpet on the lobby. I want it to feel grim and utilitarian

image

I hate this windoor already, I don't think it's that useful.

No security records or cameras console accessible for officers. One is mandatory, two would be preferable.

**Comment by ghost** [comment]
Oh yeah, I swapped in a camera and records console in lieu of the two rechargers in the hallway

Also this windoor feels fine to me. HoS can just perma open it

**Pull request merged**
