### PR TITLE
[Meta] Logical continuation update

### PR DESCRIPTION
**Pull request by IratePirate**
-replaces shooting range with security e.v.a (I apologise)
-brig infirmary expanded
-minisat central foyer made larger hopefully to make it less likely people can just run straight past the turrets
-changes to the southern medbay corridor
-incinerator layout changes
-changes to floor tiles in some places
-fixed up execution chamber
-removed the windoor in recycling which was blocking shit (why was this even here?)
-added atmos lockers and more rpds
-botany discs added
-added air alarms where they were needed
-changed some area zoning
-made delivery office conveyor one tile longer to stop people smashing into the flaps
-other misc changes i've forgotten to note down here

### CODE REVIEW

**Comment by ComicIronic** [comment]
Images please.

**Comment by IratePirate** [comment]
m1
m2

**Comment by IratePirate** [comment]
m3
m4

**Comment by ComicIronic** [comment]
Is that an atmos computer in the execution chamber?

**Comment by IratePirate** [comment]
It's the same computer from Box's execution. It was requested (though I personally don't see the point when there's a perfectly usable pump).

**Comment by ComicIronic** [comment]
Injectors don't inject automatically, which is why the computer is needed.

**Comment by IratePirate** [comment]
It seemed to work even without it, just had to open the vent up. I suppose it doesn't matter if the vent and the computer are both there.

**Comment by IratePirate** [comment]
m5
m7

**Comment by d3athrow** [comment]
good to go?

**Comment by IratePirate** [comment]
Should be. Yeah. I'm briefly being sidetracked by writing stuff for the wikia. Nothing else to be done with this. Feel free to merge it.

**Comment by IratePirate** [comment]
Merge whenever.

**Comment by IratePirate** [comment]
Oh. That was fast!

**Pull request merged**
