### PR TITLE
Vending machines can now offer month-specific items

### PR DESCRIPTION
**Pull request by SonixApache**
Vending machines can now offer month-specific items. Let me know if there's any other monthly / holiday special items that you think would be fitting to put into vending machines.

🆑
 - rscadd: Halloween wizard robes are now available from the magivend throughout October

### CODE REVIEW

**Comment by Eneocho** [comment]
clownpods on the botany vendor during april fools

**Comment by anunknownentity03** [comment]
useless

**Comment by Eneocho** [comment]
> 
> 
> useless

It's a coding update. Sure, this by itself adds nothing to the gameplay, but the code being there allows others to easily expand the vendors with month-specific whatevers.

**Comment by ghost** [comment]
> 
> 
> clownpods on the botany vendor during april fools

april fools isn't a month you troglodyte

**Comment by Eneocho** [comment]
> 
> 
> > clownpods on the botany vendor during april fools
> 
> april fools isn't a month you troglodyte



every month is april fools

**Comment by SonixApache** [comment]
>@anunknownentity03 
> 
> useless

i do in fact expect this to be merged on the first of november or later, so i share your sentiment to some degree

**Pull request merged**
