### PR TITLE
Adds a 'mob swarm' button to the secrets panel

### PR DESCRIPTION
**Pull request by gbasood**
Adds a button that spawns a bunch of mobs in a random area from a predefined list.

In retrospect this is possibly too simplistic, but I'm gonna put it up just to see if someone wants it/can think of a way to make it !!FUN!!

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Why not just add a "mob swarm" button and let the admin input the mob they want a swarm of?

**Comment by SkowronX** [comment]
^ I like this idea.
Any mob would be great. Not just simple animals.

**Comment by clusterfack** [comment]
What shadow said

**Comment by gbasood** [comment]
There now it should be mobs of a picked type of a picked amount in a random area from that list
I should probably make them spark or something so they don't just seem to materialize quietly

**Pull request merged**
