### PR TITLE
Removed cooldown on resting, does not remove 1s movement delay on un-resting

### PR DESCRIPTION
**Pull request by 9600bauds**
Well I've seen mostly nothing but negative responses to this change which has absolutely no balance effects so it's time

### CODE REVIEW

**Comment by 9600bauds** [comment]
stop these awful memes

**Comment by clusterfack** [comment]
How do you know it's not simply a vocal minority

**Comment by clusterfack** [comment]
Also I wanted to add max payne style diving by using rest while running and this wont let me

**Comment by Megamaw** [comment]
why does resting need a fucking cooldown?

**Comment by ComicIronic** [comment]
Where's the vote

**Comment by kol1th** [comment]
Yeah, I liked the delay between resting. I always hated seeing people spam rest move down a hallway. Less meme-y things IC the better. :-1:

**Comment by clusterfack** [comment]
Because it does an animation between standing up and laying down that doesn't finish without a cooldown.

**Comment by 9600bauds** [comment]
> How do you know it's not simply a vocal minority

It didn't seem like a minority to me, how do you know anything is not a vocal minority? The people wanting a cooldown could be the vocal minority in any case. If this merits a server vote so be it, I've been trying to get polls made for other stuff without success.
Bear in mind we've already had a vote in the form of votes in the PR and it was 6 to 3 against last I checked

> Also I wanted to add max payne style diving by using rest while running and this wont let me

Why not? Let people rest when standing still, disable resting whike sliding

**Comment by 9600bauds** [comment]
> Less meme-y things IC the better. 

Cooldown on turning WHEN? Fuck those meme MoMMIs doing their meme dancing amirite

**Comment by clusterfack** [comment]
If turning had an animation that would get fucked up by turning too quickly then yeah

**Comment by 9600bauds** [comment]
It's not like the resting animation is even 1 whole second long.

**Comment by clusterfack** [comment]
If you want I'll shorten it to the precise amount of time the animation takes

**Comment by Intigracy** [comment]
yes

**Comment by 9600bauds** [comment]
> Also mechs already have a turn cooldown, so like you're literally self destructing your own arguments here man.

Didn't see that you edited your post here
Mechs have a turning cooldown as a deliberate balancing feature since they need to be facing stuff to interact with it, unlike mobs
I really shouldn't even have to explain the difference

**Comment by clusterfack** [comment]
Sounds to me like the difference between a "deliberate balancing feature" and a "change which has absolutely no balance effects" is entirely subjective.

**Comment by 9600bauds** [comment]
I think a good bullet point to differentiate those would be "changes balance"

**Comment by clusterfack** [comment]
Smells like a load of fucking bullshit because I blew over your strawman

**Comment by 9600bauds** [comment]
clusterfack you are not even making any sense
what

**Comment by clusterfack** [comment]
You're the one propping up fake arguments against the rest change like 
>what if we made turning have a cooldown

How the fuck is that even relevant

**Comment by 9600bauds** [comment]
They would both be unnecessary changes that wouldn't actually affect any gameplay mechanics, just remove something cosmetic 4nr.
I don't need to explain any of this conversation to you Clusterfack, I know you're not stupid. You're perfectly capable of finding the resemblance here on your own. You just have a very evident feedback problem.

**Comment by clusterfack** [comment]
>removing something cosmetic for no reason

Fuck off @9600bauds you're just ignoring my argument that it is fucking up the animation for no reason because you like it you faggot.

**Comment by Intigracy** [comment]
Is liking it not reason enough?

**Comment by gbasood** [comment]
I prefer the rest delay.
I have no logic to back this up.

I don't see a lot of actually good logic backing up wanting to remove the delay, either. Other than >muh dodge rest spam
Which I honestly don't care either way about

This is an _OPINIONS_ PR that is trying to revert an _OPINIONS_ PR.

**Comment by ghost** [comment]
There's no need for rest to have any sort of cooldown. Rest-spam was something fun people would do, and rarely. It had no upsides or downsides to doing it, and all you've done by removing it was remove something people rarely did for a little fun because you didn't like it. 
And I'm pretty sure you need to be able to rest and unrest pretty fast for the Dance Vault, so you ruined that too, thanks.

**Comment by ComicIronic** [comment]
Can you confirm that instead of speculating?

**Comment by unid15** [comment]
Can confirm, DDR minigame is impossible to complete now

**Comment by ghost** [comment]
After some stuff with this today, the entire thing just needs to go. One of the fun things was being able to unrest and quickdraw on people, it was good robust strategy and it's gone. Its an unnessacary nerf. You can't even cheese the AI upload any more with wiggling the turrets.

**Comment by SangriaMonkey** [comment]
How is this even a balance issue?

**Comment by gbasood** [comment]
> You can't even cheese the AI upload any more with wiggling the turrets.

how is cheesing AI upload even a good thing
if AI upload is too robust without rest spam, that's it's own issue

I'd rather see the gane move towards what I want it to be rather than balance for what it is
Because the game, as it is, is kinda shit

**Comment by Iamgoofball** [comment]
at tg we have a legitimate problem with wavedashing to avoid security

it's fuckin garbo and lets players with the ability to make macros like this cheat

**Comment by kol1th** [comment]
Less macros that can be abused the better.

**Comment by ComicIronic** [comment]
> It had no upsides or downsides to doing it
> 
> One of the fun things was being able to unrest and quickdraw on people, it was good robust strategy and it's gone.

Which is it?

**Comment by SangriaMonkey** [comment]
I've literally never seen this used effectively.
How about you actually have an admin talk to the minmaxers who go to these ridiculous fucking lengths instead of constantly sterilizing and childproofing the game.

**Comment by ghost** [comment]
Comic, I was talking about rest-spam as a way to dance in that first comment.
Secondly, I don't think I've ever seen someone on /vg/ outside of me use rest that much, we never really had a problem with it and I pretty much suck at it. Wavedashing isn't a problem on /vg/, you lose a lot of speed when trying to run away from sec, just gives them more time to catch up and hit close range stuff. I've tried the whole spam rest macro while running down a hall to dodge tasers, it doesn't work well here.

**Comment by ComicIronic** [comment]
Still needs a server vote

**Comment by clusterfack** [comment]
Bauds left over this, rip

**Comment by ghost** [comment]
Thanks cluster for this!

**Comment by Shadowmech88** [comment]
Did we ever get a server vote on rest cooldown vs no rest cooldown? It certainly seems controversial enough to warrant one.

**Pull request closed without merging**
