### PR TITLE
Busy Checks on Fabs

### PR DESCRIPTION
**Pull request by Kurfursten**
Duping bugs removed; no fun allowed
- Fully tested

### CODE REVIEW

**Comment by ComicIronic** [comment]
I think the duping was already fixed.

**Comment by Kurfursten** [comment]
@ComicIronic I was able to reproduce the bug on live, after testing this prevents it.

**Comment by Probe1** [comment]
is this the one where you can get free single sheets added to the total if you spam click while the lathe is working and wont' accept materials, then the dialog box for inserting sheets comes up twice, giving you 1 free sheet in the second dialog box if you had inserted all the sheets in the first dialog box?

**Comment by Kurfursten** [comment]
@Probe1 It's the spam-clicking one, yeah.

**Comment by Probe1** [comment]
Cool, I was going to report it when I had time to measure if it actually added free materials or if it was a false message that *said* it added 1 sheet but didn't really.  

Glad to see it fixed anyways.

**Comment by d3athrow** [comment]
This bug shouldnt be possible anymore with the item being checked for location. If pooling didnt automatically reset the stacks amount back to 1 it wouldn't be possible to begin with.

**Pull request merged**
