### PR TITLE
Removes Broken Sprite List button

### PR DESCRIPTION
**Pull request by Zth--**
I almost gas the server when pressing this button, it's completely broken

### CODE REVIEW

**Comment by Kurfursten** [comment]
What happened?

**Comment by ShiftyRail** [comment]
Presumably you only ever want to run that locally. It loops something slighly complicated over every single subtype of `/obj`  (!), and outputs a file (which isn't useful if the files goes on Pomf's serb)
Make it requires +PERMISSIONS instead ?

**Comment by Zth--** [comment]
So when clicked it asks "Are you sure you want to get the broken sprites list?" so you panic and click "no" but it completely ignores you and runs anyways. Then the server freezes while popping off approx 50 runtimes.

**Comment by ShiftyRail** [comment]
Just don't use it on the live server, and fix the faulty Y/N prompt
this shit is meant to be used on local

**Pull request closed without merging**
