### PR TITLE
MSO can't read this so make fun of him (Charsettings fix #3)

### PR DESCRIPTION
**Pull request by N3X15**

### CODE REVIEW

**Comment by Exxion** [comment]
I don't know SQL at all, but what's the worst that could happen?

EDIT: I was going to merge it after posting this but I wisely checked the Discord first

**Comment by yclatious** [comment]
>self merged

**Comment by Exxion** [comment]
Self-merging, when bad, is bad for up to three reasons:
1. It potentially bypasses the peer review process. If the thing was already reviewed and/or nobody else understands it, though, this is irrelevant.
2. It is potentially used to force something in without approval from others. This is only relevant for things that add content or otherwise change gameplay.
3. It invites shitposting. This is *always* relevant. But never really important.

For the sake of standards it's still a good idea to avoid it even just because of 3, but fixing fucked core systems is generally more important than maintaining standards just for the sake of standards

**Comment by yclatious** [comment]
I know im just memeing lad

**Pull request merged**
