### PR TITLE
Supermatter book now resonates strongly with supermatter.

### PR DESCRIPTION
**Pull request by SonixApache**
i saw #35295 and thought "why doesn't this have a special interaction with supermatter?" so now it does

### CODE REVIEW

**Comment by ValkyrieSkies** [comment]
\>no actual description of what it does

**Comment by NigglyWiggly** [comment]
Don't worry about it :^)

**Comment by Eneocho** [comment]
5x a generic item feels like way too little for such an interaction, you can literally throw 5 micro manipulators, 5 glass shards, etc,  for the same result.

**Comment by brndd** [comment]
I like the idea, but on the other hand I'm conflicted about putting special snowflake code that ultimately doesn't do much directly into supermatter.dm like this.

If we had a supermatter_act proc this could be implemented in a much cleaner fashion. Maybe this could be snoflaked in the book's preattack proc or something, though that also is a sort of dirty solution.

**Comment by Kurfursten** [comment]
> 5x a generic item feels like way too little for such an interaction, you can literally throw 5 micro manipulators, 5 glass shards, etc, for the same result.

The manual itself is a generic item that can be printed infinitely at the library computer

**Comment by SonixApache** [comment]
> >no actual description of what it does

un-secret secrets

> 5x a generic item feels like way too little for such an interaction, you can literally throw 5 micro manipulators, 5 glass shards, etc, for the same result.

Like Kurf said, you could just print more of these books. I don't want it to be crazy, just a funny little interaction.

> I like the idea, but on the other hand I'm conflicted about putting special snowflake code that ultimately doesn't do much directly into supermatter.dm like this.
> 
> If we had a supermatter_act proc this could be implemented in a much cleaner fashion. Maybe this could be snoflaked in the book's preattack proc or something, though that also is a sort of dirty solution.

outside the scope of this PR until there's an actual reason to do so

**Comment by Eneocho** [comment]
> > 5x a generic item feels like way too little for such an interaction, you can literally throw 5 micro manipulators, 5 glass shards, etc, for the same result.
> 
> The manual itself is a generic item that can be printed infinitely at the library computer

Yes, they can be printed, but very slowly, due to the printer cooldown (plus the library computer is not buildable, and printing is manual). On the other hand, you can hack an autolathe to just keep shitting out micro manipulators, and it'll make more than 5 (equal to 1 book) in less than the time it takes the printer to recover from cooldown. You can scale up the micromanipulator printing and conveying, you cannot scale up the book printing. It just 1 book every 10 or so seconds.
The amount of energy the book gives is so small it's not noticeable unless used to jumpstart a shard (that you could also start with the emitters or an extinguisher if used for syndies), and even then it's not that much.

**Comment by Kurfursten** [comment]
Library computer will be buildable someday when I resume my librarian updates, I promise. Also might go to a paper-based system for printing instead of just a cooldown to encourage botany/cargo interaction.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
nice make it have an increasing chance of paper jams like with lightbulb flickering and the mechanic needs to come in to fix it
and make replacement ink cartriges require high science levels or bought from vox trader

**Comment by Eneocho** [comment]
>Library computer will be buildable someday when I resume my librarian updates, 

Very cool (that still means printing is manual, thereby infinitely outclassed by hacked lathe printing).

**Pull request merged**
