### PR TITLE
Adds breathmask function to horsehead mask (if necessary)

### LINKED ISSUE #8958: Wizard's Horse Curse leaves Plasmen fucked
Happened twice in a round, when horse cursed the plasman is unable to turn on internals via the HUD or in hand menus.

Pretty easy to reproduce I'd think.

### PR DESCRIPTION
**Pull request by coldcola**
I know this is somewhat under contention as to whether it's intended or not, but I did it anyway.
Tested on private server, spawned a human and was able to set internals.
Discuss.

closes #8958

### CODE REVIEW

**Comment by unid15** [comment]
this is a huge nerf to the horsehead spell

:-1: unless you buff the spell somehow

**Comment by coldcola** [comment]
any suggestions? was labelled oversight/balance when I made the issue.

**Comment by gbasood** [comment]
Could make it so a second level of horsehead doesn't give them internals in some way? Either way it ends up being a nerf though

**Comment by coldcola** [comment]
yeah exactly, I could look into making it a stronger horse curse but then that requires an extra point in the spell which I am unsure if anyone even would want to use a spellpoint for that.

My reasoning for making it act as internals is that the other curses are also relatively benign and don't cause suffocation or quick death, thought maybe this spell was not overly intended to be used as a method of killing people. 
If not that's cool, no merge necessary.

**Comment by gbasood** [comment]
It probably wasn't originally but it's part of the _M E T A_ now

**Comment by ihadtoregisterforthis** [comment]
Can the magical horsemask be melted with a bucket of acid?

**Comment by coldcola** [comment]
pretty sure yes.

**Comment by Exxion** [comment]
Yep. Either kind of acid.

**Comment by Intigracy** [comment]
The horsehead spell is meant to be a major annoyance until you get it removed, which is why I think it's fine as-is where you don't get internal usage.

The mime spell completely mutes you with no cure (sans dying and being cloned), and both the mask and the uniform it gives you are UNACIDABLE, which is why that mask works as internals. The only saving grace is that you get the mime's forcewall spell and can still kill yourself to lose the clothes/spell/silence.

The clown spell is the same, except instead of silencing you it makes you have the clumsy mutation (which gives you 50% chance on most guns for it to explode in your face, some it always happens, as well as handcuffing people sometimes handcuffing yourself instead), and equips you with shoes, uniform, and mask that are still UNACIDABLE. The only saving grace is you can fix the clumsiness via genetics and the clothes via dying.

**Comment by Arthurdentist** [comment]
I agree with Intigracy

**Comment by coldcola** [comment]
@Intigracy 
thanks for the explanation, this makes sense then.

**Pull request closed without merging**
