### PR TITLE
Updates default browser popup CSS

### PR DESCRIPTION
**Pull request by ghost**
[UI][tested]
Before:
image
After:
image
Makes it more similar looking to nanoUI

### CODE REVIEW

**Comment by Kurfursten** [comment]
Not really sure what the voters dislike.

@gurfan @djkramer123 @smallboss @cadaverouscoyote care to elaborate for the rest of us?

**Comment by djkramer123** [comment]
I like how it looks currently more, not much elaboration needed for a visual change

**Comment by godietxt80** [comment]
why

**Comment by Exxion** [comment]
I didn't downvote it because I don't really care, but the contrast between the background and the buttons is a bit low in the new one. I'm guessing this is also the case with current Nano? I don't remember.

**Comment by gurfan** [comment]
> Not really sure what the voters dislike.
> 
> @gurfan @djkramer123 @smallboss @cadaverouscoyote care to elaborate for the rest of us?

I don't like how it looks, the current version has better contrast, and I dislike the NT logo being there

**Comment by DamianX** [comment]
lol

**Pull request closed without merging**
