### PR TITLE
changed laser AK icon

### PR DESCRIPTION
**Pull request by Blithering**
New sprite for the laser AK, old one was a bit tiny.
Old:
laserakold
New:
laser ak
Serving suggestion:
stalker

### CODE REVIEW

**Comment by Aurx** [comment]
The stock is iconic to the '47, man.  Iconic!

**Comment by SonixApache** [comment]
laser AKS-74u?

**Comment by SysadminJeroen** [comment]
What about having both?

**Comment by Blithering** [comment]
regular ak using the same size frame ended up sixty pixels long, thats pretty huge
ak2

**Comment by SonixApache** [comment]
stock attachment overlay
extended barrel overlay

**Comment by Exxion** [comment]
We can just make the actual sprite that size, you know
The issue is that it would look fucked up in containers and your hands

**Comment by Blithering** [comment]
Making an AK modular would be implying that Mikhail Kalashnikov didn't make them perfect straight out of the factory. Blasphemy!

**Comment by Blithering** [comment]
Do we currently have any lasers with a burst fire setting? I could add the larger one as a burst laser and keep the smaller as is

**Comment by Exxion** [comment]
Not as far as I know, but also fuck burst fire, in any context, in any game

**Comment by Blithering** [comment]
Can you think of another easy to implement use for the other sprite if burst fire is a no go?

**Comment by Exxion** [comment]
What? No, I just meant I personally hate using it. I didn't mean you shouldn't add it if you want to.

**Pull request merged**
