### PR TITLE
Adds autoignition temperatures for many items

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Our code already employs an autoignition_temp var was is checked before (very few) items catch on fire in a hot room without the presence of fire. This PR adds a few more autoignition temperatures and assigns them to nearly all appropriate items under code/game/obj and code/modules/clothing. I will hunt down other items placed throughout code as well as flammable structures or machines in a separate PR.

Existing autoignition temperature constants (in Kelvin):
```
#define AUTOIGNITION_WOOD  573.15
#define AUTOIGNITION_PAPER 519.15
```
Added constants (sources below):
```
#define AUTOIGNITION_PLASTIC 689.15 //autoignition temperature of ABS plastic
#define AUTOIGNITION_METAL 1033.15 //autoignition temperature of steel
#define AUTOIGNITION_FABRIC 523.15
#define AUTOIGNITION_PROTECTIVE 573.15 //autoignition temperature of protective clothing like firesuits or kevlar vests
#define AUTOIGNITION_ORGANIC 633.15 //autoignition temperature of animal fats
```
Plastic: https://www.tcforensic.com.au/docs/article10.html
Metal (used steel and a loose interpretation of ignition): http://www.halversoncts.com/141-the-heat-of-combustion-of-steel.html
Fabric: NFPA Firefighting Essentials 7th ed
Protective: NFPA Firefighting Essentials 7th ed
Organic: NFPA Firefighting Essentials 7th ed

**Note: fires rarely heat a room up enough to see even wood or paper autoignition right now. These changes will only be noticed in high-temp fires such as plasma fires until fire is reworked.**

## Why it's good

Part 2 of my crusade in improving fire code. Fires are extremely underwhelming and not dangerous at the moment; items that should be flammable never ignite even when a fire is on the same tile. This aims to enhance the destruction fire can do to any item on the station.

## Changelog

:cl:
 * rscadd: Added autoignition temperatures for many items.

### CODE REVIEW

**Comment by Exxion** [comment]
Glass is already an oxide. It doesn't burn. Silicon burns into glass.

**Comment by west3436** [comment]
> Glass is already an oxide. It doesn't burn. Silicon burns into glass.

okay yeah glass really only melts, lemme scratch that portion

**Comment by Hinaichigo** [comment]
Melting and combusting could be integrated with the breakable objects framework. Objects at extreme temperatures could take energy damage every process() tick or something.
There still isn't a distinction between breaking apart by different means, (aka a fork melting into a metal blob when melted versus shattering when shot with a bullet) but it could be nice.

**Comment by west3436** [comment]
> Melting and combusting could be integrated with the breakable objects framework. Objects at extreme temperatures could take energy damage every process() tick or something. There still isn't a distinction between breaking apart by different means, (aka a fork melting into a metal blob when melted versus shattering when shot with a bullet) but it could be nice.

Agreed that melting/burning needs work in the future. Hopefully this helps lay a better foundation for that going forward

**Comment by Hinaichigo** [comment]
Yeah. Would be nice if you could firebomb the library or bar and turn everything into piles of soot, or all food would turn into a burned mess when burned or something.
Also like the idea of jumpsuits and other clothing burning away if the wearer if on fire for too long.

**Comment by Eneocho** [comment]
Does this affect windows? If you have a fire now does the window melt and the heat spread?
Not really sure I like the firesuits fucking melting.

**Comment by Theophrastus1** [comment]
> Does this affect windows? If you have a fire now does the window melt and the heat spread? Not really sure I like the firesuits fucking melting.

I mean with firesuits in general they should be resistant, but not immune. So your average temp fire they should be fine, but you get mega fucking hot temps due to atmos fuckery, they are obviously gonna melt. Didn't hardsuits work on this at one point too, where the ENG suit had radiation resistance, but the Atmos suit had greater temperature protections? Or they both had them in comparison to something like the voidsuit or the miner hardsuit and sec hardsuit. I think those even fail at a certain temperature outside of the CE suit but i'm not 100% on that

**Comment by west3436** [comment]
> Does this affect windows? If you have a fire now does the window melt and the heat spread?

Not in this PR. As Hinaichigo mentioned melting needs some work that I may do in a separate PR. Pressure already breaks windows and could factor in here.


> Not really sure I like the firesuits fucking melting.

They don't melt, they burn (and they also do IRL). For a big fire, atmos techs should use their heatproof hardsuits rather than a firecoat. If they come across a oh-god-hotter-than-the-sun fire then they can apply the gold hardsuit kit as needed.

**Comment by Eneocho** [comment]
>Not in this PR. As Hinaichigo mentioned melting needs some work that I may do in a separate PR. Pressure already breaks windows and could factor in here.

I don't really like the idea of my favourite R-UST design dying forever due to heat melting the windows. At least make it so plasmawindows are perfectly heat resistant if you DO go forward with the window melting.

>They don't melt, they burn (and they also do IRL). For a big fire, atmos techs should use their heatproof hardsuits rather than a firecoat. If they come across a oh-god-hotter-than-the-sun fire then they can apply the gold hardsuit kit as needed.

At some point even the gold hardsuit is not enough to deal with a fire. Though I guess that at that point the round is essentially over and shuttle called.

**Comment by west3436** [comment]
> I don't really like the idea of my favourite R-UST design dying forever due to heat melting the windows. At least make it so plasmawindows are perfectly heat resistant if you DO go forward with the window melting.

Yeah if anything touches the mechanics of engines I would be very conservative about it, but this one doesn't.
 
> At some point even the gold hardsuit is not enough to deal with a fire. Though I guess that at that point the round is essentially over and shuttle called.

Correct, if the station is hotter than the sun you have bigger things to worry about

**Comment by pedr69** [comment]
does this make metal sheets turn into ash piles at a bit over 1000C?
because i think real iron doesn't do that usually

**Comment by west3436** [comment]
> does this make metal sheets turn into ash piles at a bit over 1000C? because i think real iron doesn't do that usually

Yes
Real metal does, in fact, burn albeit at much higher temperatures than in a standard fire. It'll take a plasma fire to get to those temps

**Comment by Hinaichigo** [comment]
There's kind of an interesting negative feedback loop if fire gets hot enough to melt windows and doors; it could lead to a breach to space that would drain all the air out and extinguish the fire.

**Comment by west3436** [comment]
> There's kind of an interesting negative feedback loop if fire gets hot enough to melt windows and doors; it could lead to a breach to space that would drain all the air out and extinguish the fire.

This does not touch structures so this won't happen. Walls and windows will continue to behave the same as before.

**Comment by pedr69** [comment]
not sure what fire temperatures usually are ingame, but these temps seem very low
i'd make protective clothing ignite at ~1000C, and metal at 1500-2000

**Comment by Kurfursten** [comment]
> not sure what fire temperatures usually are ingame

Temperatures are usually supernatural. As in a plasma cloud catches a spark and gets hotter than the sun.

**Comment by Hinaichigo** [comment]
> say the bar gets set on fire first, your clothes will melt, then the firesuits, THEN the meat slabs, and once the temps get even higher, the plastic forks it just don't make any sense

In this case it's bursting into flame, not melting.

**Comment by west3436** [comment]
> not sure what fire temperatures usually are ingame, but these temps seem very low i'd make protective clothing ignite at ~1000C, and metal at 1500-2000
> 
> say the bar gets set on fire first, your clothes will melt, then the firesuits, THEN the meat slabs, and once the temps get even higher, the plastic forks it just don't make any sense

I don't know why you think it doesn't make sense, these are real world numbers. Firesuits are fire resistant not fireproof.

**Comment by pedr69** [comment]
i'm assuming the bursting into flames uses the currently implemented flame stuff, where the item gets set on fire for a couple seconds, then turns to ash
if you're reworked how that works in one of the PR's i've missed, then i'd be willing to give this a shot, but kevlar vests igniting faster than plastic or meat just seems stupid
and no real world steel is going to burst into flame at 760 celsius

**Comment by west3436** [comment]
> i'm assuming the bursting into flames uses the currently implemented flame stuff, where the item gets set on fire for a couple seconds, then turns to ash if you're reworked how that works in one of the PR's i've missed, then i'd be willing to give this a shot, but kevlar vests igniting faster than plastic or meat just seems stupid and no real world steel is going to burst into flame at 760 celsius

Irl the plastic would melt, the suit would burst into flames, then the melted plastic would ignite. We don't have any form of melting currently, though it's something I can look into in the future. I agree that metal is too low, that temperature is based on 100% oxygen flowing over the steel which is not the case. Likely will just remove metal autoignition altogether.

**Comment by Kurfursten** [comment]
Prepare for unforeseen consequences

**Comment by Eneocho** [comment]
More like foreseen, what with all the complaining and west himself saying that some stuff shouldn't autoignite at all, such as metal.

**Comment by d3athrow** [comment]
people are gonna hate this just like my pressure differentials pr

**Comment by Eneocho** [comment]
I give it a week tops.

**Comment by west3436** [comment]
cowards

**Pull request merged**
