### PR TITLE
Undoes the peacekeeper borg sprite change (and nothing else)

### PR DESCRIPTION
**Pull request by SonixApache**
It's like #13873, but without any code changes.

So they're still peacekeeper borgs and all that, just red again.

### CODE REVIEW

**Comment by jakmak** [comment]
The red looks better than the baby blue. what was the original intention of changing them?

**Comment by SonixApache** [comment]
Distance them from sec? Make them the same color as the UN? Make people not want to play secborg because they look silly? "Because pomf said so" ? Who knows.

**Comment by ihadtoregisterforthis** [comment]
Distance them from sec and "because pomf said so"

**Comment by Probe1** [comment]
So long gay bowser

**Comment by yclatious** [comment]
👌

**Comment by Probe1** [comment]
While we're at it lets do the air tank revert

**Pull request merged**
