### PR TITLE
Blacklist items for travis

### PR DESCRIPTION
**Pull request by Zth--**
Travis now supports blacklisting items for maps. By maps I mean _main_ maps, not vaults nor away missions. It's not smart enough to check for centcomm tho. This is the simplest solution I could come up with

I only added rigsuit helmets. ~~Do not merge until these are fixed~~

Ready to be merged

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
and so the c*llab c*bal returns, not with a bang but with being angry over mappers

**Comment by Kurfursten** [comment]
All of these are, I believe, fixed. Can you verify?

**Comment by Zth--** [comment]
These are still missing:

```sh
Checking file: maps/metaclub.dmm
ERROR: 'rigsuit helmet' found on line 3752. Remove it, please.
ERROR: 'rigsuit helmet' found on line 9364. Remove it, please.

Checking file: maps/tgstation-sec.dmm
ERROR: 'rigsuit helmet' found on line 3166. Remove it, please.

Checking file: maps/RoidStation.dmm
ERROR: 'rigsuit helmet' found on line 7217. Remove it, please.

Checking file: maps/test_tiny.dmm
ERROR: 'rigsuit helmet' found on line 39. Remove it, please.

Checking file: maps/LampreyStation.dmm
ERROR: 'rigsuit helmet' found on line 18155. Remove it, please.
ERROR: 'rigsuit helmet' found on line 20538. Remove it, please.

Checking file: maps/tgstation-snow.dmm
ERROR: 'rigsuit helmet' found on line 255. Remove it, please.
ERROR: 'rigsuit helmet' found on line 281. Remove it, please.
ERROR: 'rigsuit helmet' found on line 301. Remove it, please.
ERROR: 'rigsuit helmet' found on line 4023. Remove it, please.

Checking file: maps/test_box.dmm
ERROR: 'rigsuit helmet' found on line 258. Remove it, please.
ERROR: 'rigsuit helmet' found on line 287. Remove it, please.
ERROR: 'rigsuit helmet' found on line 307. Remove it, please.
ERROR: 'rigsuit helmet' found on line 4056. Remove it, please.

Checking file: maps/defficiency.dmm
ERROR: 'rigsuit helmet' found on line 6666. Remove it, please.

Checking file: maps/bagelstation.dmm
ERROR: 'rigsuit helmet' found on line 3688. Remove it, please.```

**Comment by Kurfursten** [comment]
Feel free to open this again if you want to just delete them so this is mergeable.

**Comment by Zth--** [comment]
It's good to go

**Pull request merged**
