### PR TITLE
Change the law 4 of Corporate

### PR DESCRIPTION
**Pull request by Manleto**
Every single time some braindead idiot uploads corporate, they always berate the AI for not instantly doing everything in it's power to maximize profit.  I figure that it would lead to more fun and interesting rounds if the AI actually had to do stuff to maximize profits (such as increasing mining, allowing cargo to function, etc) instead of just shutting random things down and being annoying.
 🆑 
 * rscadd: Changed the law 4 to (maximize profits) 
 * rscdel: Deleted the previous law 4. 

<!--

:cl:
 * rscadd: Changed the law 4 to (maximize profits) 
 * rscdel: Deleted the previous law 4.

### CODE REVIEW

**Comment by jknpj** [comment]
Kill all the humans and turn them into silicons to maximize profit since you can avoid paying wages that way.

**Comment by gurfan** [comment]
I don't think this will solve the problem of the AI doing things like shutting off lights since expenses are used in calculating profits. Defining things, actions, concepts whatever that generate revenue would be helpful

**Comment by Manleto** [comment]
>I don't think this will solve the problem of the AI doing things like shutting off lights since expenses are used in calculating profits. Defining things, actions, concepts whatever that generate revenue would be helpful

I agree, but I could lead to more interesting things, such as maximizing mining. 

>Kill all the humans and turn them into silicons to maximize profit since you can avoid paying wages that way.

Killing humans is still an expense, and thus would affect the profits

**Comment by jknpj** [comment]
> Killing humans is still an expense, and thus would affect the profits

It's still more profitable since you get to keep 100% of their wages in the the station's account every payroll and silicons don't need to use the majority of the station's facilities.

**Comment by Manleto** [comment]
> It's still more profitable since you get to keep 100% of their wages in the the station's account every payroll and silicons don't need to use the majority of the station's facilities.

How do you know that?  It seems awfully assumptive

**Comment by ghost** [comment]
\>three laws that intentionally and deliberately build to a fourth law through repeated wording
\>remove the wording in the fourth law

Why not combine both versions into one law or something?

**Comment by Manleto** [comment]
> >three laws that intentionally and deliberately build to a fourth law through repeated wording
> >remove the wording in the fourth law
> 
> Why not combine both versions into one law or something?

Because maximize profits implicitly already includes minimize expenses. 

Profits = Revenue - Expenses

**Comment by DeityLink** [comment]
Except you can profit a lot more in some instances where you spare no expenses.

**Comment by Manleto** [comment]
> Except you can profit a lot more in some instances where you spare no expenses.

possibly, but an ai would have to have a good justification for why it's doing something. 

It's in the same way paladin AI's can't just kill everyone, despite "right" being subjective.

**Comment by SonixApache** [comment]
this won't change anything

**Comment by Manleto** [comment]
> this won't change anything

It will, profit = revenue minus expenses. 

AI's will now have to minimize expenses while maximizing revenue.

**Comment by Kurfursten** [comment]
I don't think this holds up unless you reword of all of it. The big problem with Corporate has always been ambiguity. Why do AIs turn lights off, for example? It's not as though the station could be making money by selling joules elsewhere. Turning the cloner off is at least reasonable since replacing people would be an expense.

But this lawset relies far too much on the AI to make assumptions about what generates profit. Does having living humans make profit? Does completing R&D make profit? Should the AI tell Cargo "You're only allowed to order things if you send more plasma back than you spent so we get net gain"? Should the AI send the borgs to destroy all vending machines (to prevent people from spending money) **OR** disable the kitchen to force people to use the vending machines (to make people pay money to CentComm, thus profiting)? This highlights the other problem: profit for who?

**Comment by Manleto** [comment]
if the AI can give a reasonable explanation for its actions then this should be fine. But at the very least this law forces more interesting interactions overall. 

The entire station is controlled by one entity, You should destroy vending machines of normal corp but on new you shouldn't. The expense of buying a snack is offset by the revenue you get from selling it.  Perhaps I should explicitly state the the profit formulas as a separate law, but some basic knowhow should be assumed here. 

CentComm and the Station should be thought of as the same entity, in the same way that someone's hand isn't seen as a separate entity.  Google office in Illinois is not a separate entity, for instance.   Thus, if you increase profits for one it's the same as increasing profits for the other, because they are the same. 

> Does having living humans make profit? Does completing R&D make profit? Should the AI tell Cargo

Again, this comes down to a simply to the consistent interpretation of the AI.  Much in the same way Robocops "pubic trust" isn't explicitly defined, nor is good and evil for paladin.  If the corp  AI decides to kill the whole station, it should have a dam good justification on why this increases profits.  If the AI is going to make assumptions on why dead humans are more profitable (instead of simply getting the HOP to set the wages to zero) it should explain so.  I sincerely doubt it could create a plausible explanation. 


The current corp doesn't allow for mass murder despite the fact that the AI could technically say the people wouldn't be replaced.  It also couldn't argue that it could mass murder the crew because it isn't explicitly stated to be the crew of this space station and it instead protecting the vox traders ship.

**Comment by SonixApache** [comment]
AIs can't handle money. Literally not allowed to, outside of being able to order cargo stuff with the station account.
The station account only gains money from the automatic payroll, doesn't it? Cargo sales go to the cargo account, don't they?

**Comment by Manleto** [comment]
> The station account only gains money from the automatic payroll, doesn't it? Cargo sales go to the cargo account, don't they?

The AI itself doesn't' handle the money, however different things can be done to increase the stations profits.  Mining and whatnot leads to raises because of this.

**Comment by tayachiya** [comment]
Sell everything not bolted down to maximize profits.

**Comment by juanototo2** [comment]
Corporate as written is an Asimov that prioritizes things, which is fun, interesting, and allows for some violation of the AI's default role as a third party without being STD, Paladin or Windowbreakocop. The main problem is that its fourth law, expenses, is open ended, that there is no silicon policy for it to either define other things as expenses, see what is more expensive in what cases, especially whether, say, cloning, the engine, or the AI is more important than the life of a single crewman, and that Corporate as played and as the admins allow is a gold core relocation simulator.

Until a fifth law or silicon policy is added that defines only things that are denoted in its lawset as expenses, and that, say, frowns upon said gold relocation to core, I will not consider Corporate a playable and uploadable lawset as non-antagonist.

**Comment by Dacendeth** [comment]
Remove AI.

**Comment by diegoxt45** [comment]
> Remove AI.

**Comment by Exxion** [comment]
Your changelog lacks the initial :cl: and does not specify law 4 of what.

**Comment by Exxion** [comment]
It still didn't say what you changed the law 4 of, but I guess it's too late now

**Pull request merged**
