### PR TITLE
Return of the retroUI

### PR DESCRIPTION
**Pull request by PJB3005**
Clients can now choose to not use nanoUI (supported UIs only).

I only did the Telescience console (wow, so usefull), but am planning to add more.

### CODE REVIEW

**Comment by ririchiyo** [comment]
Please utilize the browser datum for these kinds of html windows.

**Comment by BestName** [comment]
Damn, I saw the name of the PR and thought you meant this.
ss13-a

**Comment by clusterfack** [comment]
Ha look at the carpets in that picture, what the fuck was going on there

**Comment by PJB3005** [comment]
hunke

Also, this shouldn't have DNM anymore, too.

**Pull request merged**
