### PR TITLE
Admin verbs trimming

### PR DESCRIPTION
**Pull request by ShiftyRail**
Because someone had to do it.
For some reason, I can't join as a ghost to test a few of them on my branch, but aside from that, the system works.

There is an unfortunate mix of spaces and tabs in the global list that should probably be addressed at some point.

The verbs are datums, which means that if anyone with better HTML skills than me wants to code a NanoUI interface it should be easy enough.

Categories done : 
- [x] Admin
- [x] Fun
- [x] Debug
- [x] Server

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Finished, ready to be reviewed

**Comment by Kammerjunk** [comment]
This is a good thing thank
Being able to type half of a verb in the command bar is terribly convenient but way not worth the verb bloat lag

**Comment by ShiftyRail** [comment]
@Kammerjunk The priority verbs are still here : 

```dm
/client/proc/debug_variables,		/*allows us to -see- the variables of any instance in the game. +VAREDIT needed to modify*/
/client/proc/check_antagonists,		/*shows all antags*/
/client/proc/advwho,				/*in addition to listing connected ckeys, shows character name and living/dead/antag status for each*/
/datum/admins/proc/checkCID,
/datum/admins/proc/checkCKEY,
/datum/admins/proc/delay,
/client/proc/player_panel_new,		/*shows an interface for all players, with links to various panels*/
/client/proc/invisimin,				/*allows our mob to go invisible/visible*/	/client/proc/admin_ghost,			/*allows us to ghost/reenter body at will*/
/datum/admins/proc/PlayerNotes,
/client/proc/cmd_mod_say,
/client/proc/cmd_mod_window,
/client/proc/investigate_show,		/*various admintools for investigation. Such as a singulo grief-log*/
/client/proc/dsay,					/*talk in deadchat using our ckey/fakekey*/
/datum/admins/proc/toggleooc,		/*toggles ooc on/off for everyone*/
/client/proc/create_bomberman_arena,
/client/proc/achievement,
/client/proc/debug_reagents, //Allows us to spawn reagents in mobs/containers
/client/proc/create_awaymission, //Allows us to summon away missions
/client/proc/create_map_element,
/datum/admins/proc/startnow,
/datum/admins/proc/restart,
/datum/admins/proc/toggleaban,
/datum/admins/proc/immreboot,
/client/proc/everyone_random,
/datum/admins/proc/toggleAI,
/client/proc/gc_dump_hdl,
```
Are the admins verbs you still have while typing, which represents a removal of (about) 116 verbs.
Contextual/right-click verbs are still here.

This makes me think that I need to see if Jump-To-(area) is still here.

**Comment by ShiftyRail** [comment]
Ruh roh

**Comment by Intigracy** [comment]
code/modules/admin/verbs_datums.dm:385:error: /client/proc/check_words: undefined type path
code/modules/admin/verbs_datums.dm:31:error: /client/proc/check_words: undefined type path

**Comment by ShiftyRail** [comment]
Closing this while I work on other bugfixes so the PR list is not clogged
Coming soon and I'll include a screenshot of every verb working or kill myself

**Pull request closed without merging**
