### PR TITLE
Stun shotgun shells apply the same effect as tasers

### PR DESCRIPTION
**Pull request by DamianX**
So that I can shotgun people and silicons have to be OK with it
Remember to adjust this when reverting #23093

:cl:
 * tweak: Stun shotgun shells apply the same effect as tasers.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
They are stronger than electrodes because they are bullets that can go through windows

**Comment by DamianX** [comment]
I think bullets going through windows don't apply their effects anymore but don't @me about this

**Comment by beesil** [comment]
shhh that's a feature

**Comment by SirSkeleto** [comment]
rip any utility that shotguns once had
all hail laser + keloderm

**Comment by calzilla1** [comment]
Make shotgun tazers do the same stun as pre-nerfed tazers. When's the last time you saw someone using stun shells?

**Comment by DamianX** [comment]
Closing because there's no support and I don't care that much.

**Pull request closed without merging**
