### PR TITLE
Adds a bunch of hand emotes

### PR DESCRIPTION
**Pull request by DeityLink**
image

:cl:
* rscadd: Humans have a few new emotes. ok/okay makes an OK sign, thumbup/thumbsup makes a thumbs up, thumbdown/thumbsdown makes a thumbs down, and peace makes a peace sign.
* rscadd: Added hand count requirements for those emotes. Having your hands broken or amputated will make you unable to perform them.

### CODE REVIEW

**Comment by Eneocho** [comment]
No raising the middle finger emote?

**Comment by SonixApache** [comment]
👌  :+1: :-1: ✌ 
`:ok_hand: :+1: :-1: :V:`
are multiple keys / aliases possible? if so standardizing with the above might be an idea

**Comment by DeityLink** [comment]
> 
> 
> 👌 👍 👎 ✌
> `:ok_hand: :+1: :-1: :V:`
> are multiple keys / aliases possible? if so standardizing with the above might be an idea

The way emotes are implemented, only two aliases are possible, which is kinda dumb.

**Comment by ShiftyRail** [comment]
That's trivial to change.

**Pull request merged**
