### PR TITLE
Adds a facehugger_protection var to all hats.

### LINKED ISSUE #8214: facehuggers
(WEB REPORT BY: mechamusume91 REMOTE: 158.69.55.2:7777)
A single facehugger attacked me and instnatly broke through my hardsuit helmet and infected me.

it would bounce off because its just one of them

in a second it bounced one and instantly jumped again through my helmet.

walking up to one with a hardsuit on

### LINKED ISSUE #8279: Facehuggers can jump diagonally through walls
Facehuggers can jump at victims diagonally through walls as long as there's no corner wall. I have no fancy screenshots about this but I did spend 2000 hours making a mockup in Paint.NET
image3
This seems like an oversight, as having two walls adjacent like this usually prevents you from being able to interact with anything through the corner too.

### PR DESCRIPTION
**Pull request by gbasood**
Only face-protecting hats will actually utilize this value.
Rig suit helmets get a starting value of **8**. All other hats get a starting value of **4**. I'm willing to adjust these values before merging based on feedback. If you have any special snowflake hats you want me to buff, now's the time to mention them.
Mask slot items still do nothing.

Every time a facehugger tries to rip off your mask, it will decrement this value by 1. If it hits 0 or less, facehuggers succeed in ripping it off.

Resolves #8214 although maybe not the way Celt wanted it to I guess? If we want an actual health var for helmets we can always change that but eh
Fixes #8279

### CODE REVIEW

**Comment by gbasood** [comment]
Actually you know what I'm thinking I'll up the values to 3 and 4 respectively.

**Comment by Shadowmech88** [comment]
Are the values reset when you put the helmet back on?

**Comment by gbasood** [comment]
No.

**Comment by ghost** [comment]
Why not? So I should carry multiple helmets?

The fact they rip it off is the problematic part, not when they rip it off.

**Comment by NigglyWiggly** [comment]
@TermedClepe 

> Problematic

#TRIGGERED

**Comment by gbasood** [comment]
I don't think it is. Facehuggers should be able to remove facial protection.

**Comment by ghost** [comment]
@NigglyWiggly

Literally unfun mechanic toxic to gameplay.

:^)

**Comment by PJB3005** [comment]
No magic numbers please, make it defines.

**Comment by NigglyWiggly** [comment]
Facehuggers ripping off breath masks is fine and makes sense
Facehuggers being able to pull off a sealed Hardsuit helmet seems silly

**Comment by ghost** [comment]
@gbasood

They should be able to remove protection that makes sense, like a welder helmet, gasmask and the similar. Hardsuits and space helmets make absolutely no sense.

**Comment by gbasood** [comment]
@TermedClepe Don't start the realism argument again. You're playing a game where you can have a virus that causes someone to spontaneously explode. A game where you can fart on a bible and it causes you to explode. A game where you have fucking space carp. Stop.

**Comment by ghost** [comment]
Stop focusing on my name, there's many people that take issue with the very fact it makes hardsuit helmets vulnerable to facehuggers. Just look at one post above mine. Nobody cares they rip off non hardsuit/space helmets.

**Comment by gbasood** [comment]
I'll say the same thing to Niggly that I said to you.

**Comment by ghost** [comment]
And you'd be wrong in either case. Make a vote in game to see if anyone wants hardsuits to be vulnerable to facehuggers.

**Comment by gbasood** [comment]
The problem is that if I make hardsuit helmets facehugger-invulnerable, everyone would just pick up hardsuit helmets. It doesn't solve the problem I was addressing in the first place.

**Comment by Shadowmech88** [comment]
@gbasood 
What about making it so that the value gets reset when it's put back on, but only after it's been successfully ripped off since the last reset?
That way a person can't just spam-equip their helmet to keep it safe from facehuggers, but they're still able to pick it up off the ground and use it again if they survive it getting ripped off.

I just don't see the sense in making it so that getting the helmet ripped of once renders it permanently useless.

**Comment by 9600bauds** [comment]
So now have you carry multiple helmets and swap them around regularly?
What fresh hell is this? Xenos are already capable of stripping people's helmets, by the way, I don't like this "throw facehugger in general direction of person to AoE instafacehug them" business

**Comment by NigglyWiggly** [comment]
@gbasood 

> Don't start the realism argument again.

There's multiple arguments on github right now to make space not cold, because of realism.

**Comment by 9600bauds** [comment]
By the way, have you looked into the reason why facehuggers can instantly one-two you through your helmet? I haven't really looked into this for a long time but if I'm correct, it's because they use HasProximity(), meaning if you move adjacent to one of them it instantly procs.

**Comment by gbasood** [comment]
@9600bauds I actually just remembered that issue. Now that I think about it, it's probably Crossed() firing Attach() even when facehuggers are inactive.

**Comment by gbasood** [comment]
Vote for if facehuggers should be able to rip off rig helmets (ty Soca)

**Comment by ghost** [comment]
> 11 for 9 against

**Comment by gbasood** [comment]
Where the fuck did you get 9 from

**Comment by Shadowmech88** [comment]
@gbasood 
What was the poll question?

**Comment by ghost** [comment]
The last option means also no, but return fire damage.

**Comment by gbasood** [comment]
@ShadowMech88

**Comment by gbasood** [comment]
@TermedClepe No, that's not what it says. It says 'instead'.

**Comment by ghost** [comment]
YES, INSTEAD OF BEING VULNERABLE

**Comment by NigglyWiggly** [comment]
Pfft

**Comment by ghost** [comment]
I mean fuck dude, even I voted the instead option since aliens are so overpowered.

**Comment by 9600bauds** [comment]
They're already vulnerable to facehuggers of course, just drag them to a resin bed and strip them.

**Comment by gbasood** [comment]
Since the vote was in favor of keeping it, it'll stay in. Values can and probably will be adjusted. Even before merge.

**Comment by ghost** [comment]
> 2 votes on a single timezone decide this

You really have no idea how this works do you? At least ask celt, he made multiple votes during days at different times.

**Comment by NigglyWiggly** [comment]
> A single ingame poll is conclusive enough to decide this

That's silly.
Get pomf to make a server poll or ask around some more at least

**Comment by clusterfack** [comment]
Jesus christ you people and your polls

**Comment by gbasood** [comment]
The PR's not going to get merged within the day, there's plenty of time to get feedback

**Comment by ghost** [comment]
Also make a normal poll not memeing with absolutely unrelated matters to bait votes away.

**Comment by Shadowmech88** [comment]
@gbasood 
What say you to my earlier suggestion regarding resetting the counter after the mask is ripped off?

I think it's fine for facehuggers to be able to get through hardsuit helmets, but I don't like the idea of a hardsuit helmet being completely defenseless against all facehuggers after that, forever.
Especially since it would apparently still be in good enough condition to be airtight.

**Comment by gbasood** [comment]
@ShadowMech88 I feel like people just swapping their hat in and out of the slot would allow players to completely ignore this mechanic so I'm not a fan.

**Comment by 9600bauds** [comment]
Look, you're taking a vote and drawing the majority vote for it. You would do this in a worst case scenario where you HAVE to choose between two radically different AND FINAL choices (e.g. two presidential candidates or something). Even in these cases where one of two different choices HAS to be made, a near-50% split is very bad news because you're still alienating nearly 50% of the entire population.

**Comment by 9600bauds** [comment]
You know how else you could ignore this mechanic? Print a shitton of welding masks.
I'm not seeing the premise here.

**Comment by ghost** [comment]
So according to xeno lore facehuggers can secrete acid to melt helmets. As much as it would be hilarious to see all headgear melt off rather than plop off, I'm arguing here only for keeping aliens at least mildly manageable.

**Comment by gbasood** [comment]
Swapping out two different masks is a lot more cumbersome than just clicking the mask and then clicking the slot it was in to put it back.

**Comment by Shadowmech88** [comment]
@gbasood 

> just swapping their hat in and out of the slot

What I'm talking about is making it so that the counter is reset ONLY when the helmet is successfully ripped off by a facehugger and dropped on the ground. Spamming your helmet_equip slot would do nothing to protect you.

**Comment by ihadtoregisterforthis** [comment]
Voting against this solution, favoring hardsuit helmets staying invulnerable.

If you are really thinking on the lore keep in mind that facehuggers go through thick glass.

**Comment by gbasood** [comment]
@TermedClepe I actually like that idea, but it's difficult to implement, since right now facehuggers are just mask slot items. Attaching them over hats would be a complete overhaul of facehuggers.

**Comment by gbasood** [comment]
@Shadowmech88 That might work I guess but I don't know if I should add yet another var to hats just for facehuggers.

**Comment by Shadowmech88** [comment]
@gbasood 
Why would you need to add another var?
Just have the facehugger itself check the helmet's protection var and reset it to initial(facehugger_protection) when they rip it off.

**Comment by gbasood** [comment]
Ah, that's true.

**Comment by gbasood** [comment]
@9600bauds on the 1 or 2 hit thing:
Facehugger bashes against helmet. If helmet gets removed, facehugger does not go idle. Facehugger hits ground near person. Crossed() fires. Facehugger jumps on face.
I'll add a GoIdle() after helmet removal for now, we'll see if it's more desirable.

**Comment by 9600bauds** [comment]
Okay, so what if someone throws two facehuggers at your general direction?
We need to make this work mechanically before sticking to the lore or calling votes.

**Comment by gbasood** [comment]
First facehugger the hat gets removed, second facehugger attaches to your face.
There's not really a way to make that work any better as-is. I can add a warning message to a person who's facehugger protection is about to be worthless?

**Comment by gbasood** [comment]
That is, it works the way I just described if I add the GoIdle().

**Comment by 9600bauds** [comment]
I'm not entirely sold on the mechanics of this. We're just making facehuggers into very effective, very spammable ranged AoE weapons, and during the entire process we kind of just forgot about the aliens themselves.

**Comment by gbasood** [comment]
I don't think facehuggers should be as easily producable as they currently are.
I'm all for adding double fire damage back.
I'm basically increasing the protection values for helmet each time I change something now. I'm probably going to put rig helmets at 10 and all other types at 6. I feel like that makes facehuggers much less than 'very spammable'.

**Comment by gbasood** [comment]
Shitty warning message added

**Comment by Imagebard** [comment]
>6 facehuggers to break a normal helmet
>10 for RIGs

Holy shit.
If you've played on ColMar you know that smashing 3 facehuggers on someone is a divine happenstance, and once a helmet is damaged there it stays damaged.

**Comment by LordMyroc** [comment]
> You're playing a game where you can have a virus that causes someone to spontaneously explode. A game where you can fart on a bible and it causes you to explode. A game where you have fucking space carp. Stop.

I hate this train of thought. That someone once added stupid shit to the game is not a good reason for adding more stupid shit to the game. I think it's worrying that we're straying further and further from sci-fi space station shenanigans in favor of lolsorandom features that don't fit in at all with each passing day.

I acknowledge that this game having humorous elements that you normally wouldn't expect in a sci-fi environment is a huge part of its charm, but that doesn't mean that one should add just about anything to this game simply because "LOL WHO CARES WE HAVE BIBLEFARTS AND GIBBINGTONS".

(I'm also against this PR in particular because of balance reasons, I don't think lone facehuggers should be that strong. Aliens should have to work harder in order to infect people who take care to deliberately protect themselves from huggers. It's not like they have a problem doing that already.)

**Comment by gbasood** [comment]
@LordMyroc what, lone facehuggers according to this PR currently need 8 jumps at a hardsuit helmet to rip it off and they have a 75% chance of dying on each attempt

I guess I forgot to update the OP for that but still

**Comment by gbasood** [comment]
@Imagebard Aliens for us plays much differently than ColMar still, despite us using modified ColMar facehuggers.

Side note, in the xeno rounds I've seen, the crew still generally manages to do okay.

**Comment by LordMyroc** [comment]
Two hours later and I only just now realize that facehuggers currently ignore ALL protection.

I don't think facehuggers should be able to remove proper face protection under ANY circumstance. Just change it back to how it used to work.

**Comment by gbasood** [comment]
Here's some more opinion gathering I just did after xenos got bussed by @DrCelt:

**Comment by LordMyroc** [comment]
Well, fair enough. I still don't like it, but I'll concede to democracy. I guess this solution is still better than having them ignore protection completely.

**Comment by Imagebard** [comment]
Oh I missed that too.

Either way, this PR does nothing. I realize that you can throw facehuggers at a longer range here, but still. If you're in close range of someone you can just disarm them and strip off their helmet, much more realistic than throwing 6 facehuggers are someone so you *have a small window* to infect them.
Even if this gets merged, the playerbase should still act as if facehuggers are completely unable to remove hardsuit helmets.

**Comment by gbasood** [comment]
> This PR does nothing

As it is, facehuggers can remove any helmets and it's just a percentage chance. All helmets are considered the same. It's definitely doing something.

In fact it's a huge change over what we have currently. So much so that I anticipate that xenos will be put back into the ground.

**Comment by gbasood** [comment]
Or it would be if I ACTUALLY updated rigsuits and helmets the way I thought I did

**Comment by Imagebard** [comment]
>So much so that I anticipate that xenos will be put back into the ground.

Okay fine, lets actually see how things go after this is merged.
Still, calling it:
>Once every six facehuggers you get a small window to infect someone
This will (apparently) put xenos into even ground with crew

**Comment by gbasood** [comment]
no, actually I think it'll put xenos below the ground as in dead rippy peas
Because that's exactly how they were before I did anything with them

**Comment by gbasood** [comment]
closing this in favor of a future rebalance with a focus on nerfing huggers and buffing xenos

**Pull request closed without merging**
