### PR TITLE
Wage payouts to virtual wallets

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content][tweak]

## What this does
allows players to set how much of their wages they want sent to their ID's virtual wallet on payouts instead of the bank account, in % of wages defaulting to 50, in character setup. can also be changed at ATMs in-game
also adds sanity for cases where players have more than one ID with a virtual wallet tied to their account, any money directed to virtual wallets is equally split between all these IDs

## Why it's good
gives more use for virtual wallets, saves hassle of transferring new wages from ATMs

## Changelog
:cl:
 * rscadd: Nanotrasen wage payouts can now be configured to be sent directly to virtual wallets at ATMs, in percentage of wages.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Incredible, I was just thinking of doing this. Great!

**Comment by Eneocho** [comment]
Heistbros...

**Comment by WindowsErrors** [comment]
dang, there goes half the EFTPOS's uses

**Comment by SECBATON-GRIFFON** [comment]
> dang, there goes half the EFTPOS's uses

may i get 1 quick rundown on this

**Comment by Eneocho** [comment]
> > dang, there goes half the EFTPOS's uses
> 
> may i get 1 quick rundown on this

```
>John Nanotrasen bows to the EFTPOS.
>In contact with the syndicate.
>Rumoured to possess money stealing abilities.
>Controls budgets with an iron fist.
>Owns stations and planets all over the galaxy.
>Will bankroll the megacorporation in andromeda.
>EFTPOSGRAD will be the first station.
>In process of EFTPOSforming terra as its personal planet.
>Owns every id in the universe.
>First designer IDs will be EFTPOS IDs.
>Said to have 500+ IQ.
>Ancient honkian scriptures tell of an angel who will descend on space and bring an era of stolen money and purchase vouchers.
>Owns credit factories around the galaxy.
>You likely have EFTPOSbots inside you.
>Every child has the mark of EFTPOS implanted at birth.
>In regular communication with Honkmother and Nar'Sie.
>Discovered the asteroid.
>Learned fluent clown and cultist in under a week with no nanodictionary.
>Full access to space atlantis.
>Megacorps entrust their gold reserves to EFTPOS.
>There's no fort space.
>Only fort EFTPOS.
>About 10 years on a human perspective.
>In reality a timeless entity existing across all points in time and space.
>Able to access the akashic bank records since birth.
>EFTPOS will guide humanity into a new age of money laundering.

```

**Comment by WindowsErrors** [comment]
> > dang, there goes half the EFTPOS's uses
> 
> may i get 1 quick rundown on this

[It's a cargo player thing, you probably won't understand it at first, I only understood it after about 100 hours](http://ss13.moe/wiki/index.php/Cargo_Technician#Points_of_Sale)

Basically, there's a little caveat with EFTPOS scanners and cash registers, when the customer goes to pay, they can either input in all their account information to confirm a purchase or instead just input their card, when you physically input the card it doesn't require any other confirmation... While this does have a legitimate use in that you can use it to pay with department/shoal debit cards (which don't allow direct withdrawl from the ATM for some reason), this also means that if I'm ever strapped for cash I can just grab any old EFTPOS and head down to the medbay, going from dead body to dead body, going through each ID card, and after about 10 minutes I can easily walk out with somewhere in the ballpark of $1,500

Think of it like those RFID debit cards where you just put it against the screen of the machine and it makes payment without even asking you for a PIN or anything, unlike inserting it or the old swipe card method... I've been telling my mom for months that shit's a security risk and where do you think I learned it from?

**Comment by Kurfursten** [comment]
You can withdraw from the shoal account at an ATM by the way, the pin is in your notes

**Comment by WindowsErrors** [comment]
> You can withdraw from the shoal account at an ATM by the way, the pin is in your notes

the cargo department pin is in my notes as well

**Comment by pedr69** [comment]
50% seems like a lot, maybe a flat 5 per cycle going into the virtual wallet instead?

**Review by Kurfursten — COMMENTED** [review]
I noticed you haven't done any rounding anywhere. Have you insured this hasn't caused fractional money payouts?

**Comment by SECBATON-GRIFFON** [comment]
> I noticed you haven't done any rounding anywhere. Have you insured this hasn't caused fractional money payouts?

it does cause .5 to appear on money yeah, is this bad?

**Comment by Kurfursten** [comment]
Yes, money should be in whole numbers for printing purposes

**Comment by pedr69** [comment]
_*laughs in ore processor_

**Comment by SECBATON-GRIFFON** [comment]
removed the decimal issue now @Kurfursten

**Pull request merged**
