### PR TITLE
Cargo MDF crate and bin sprite swap

### PR DESCRIPTION
**Pull request by ManopolisJones**
sponsored by grey storage solutions

## What this does
This removes the old MDF bins and weapon crate sprites that were used for the MDF cargo entries and replaces them with the ones added by the Mothership Lab Renovations.

## Elaboration
I think the bins I originally made (or better put, edited) don't look so great, and with the advent of these new proper sprites, I figure it was high time they got removed and in their stead, replaced with these fresh new ones. As an added bonus, I changed the basic crate sprite from the Grey Space X cargo entry with one of the new crate sprites added by the aforementioned mothership lab renovation.

wowzers

pictured, in no particular order, MDF standard armor locker, MDF standard weapons crate, mothership uniform locker, grey Space-Ex crate

## Changelog
:cl:
 * tweak: Changed MDF and grey cargo entries to have new crate and locker sprites
 * imagedel: Removed grey bin and weapons crate sprites

### CODE REVIEW

**Comment by SonixApache** [comment]
do they come with manifests now?

**Comment by pedr69** [comment]
what do you mean all cargo crates come with manifests

**Comment by ManopolisJones** [comment]
> do they come with manifests now?



> what do you mean all cargo crates come with manifests

Any listings under contraband (that is to say, when you soldering iron a supply board to unlock it) do not spawn with manifests, however e-magged supplies (hidden) do for whatever reason get manifests, and I am unsure why.

**Comment by Eneocho** [comment]
MDF bin bros... we got too cocky...
I kinda liked the bins, they were different.

**Comment by ErrorsWindows** [comment]
still no hexagons

**Pull request merged**
