### PR TITLE
No Mechfab Access Requirement

### PR DESCRIPTION
**Pull request by Apogee-dev**
[consistency]
Alters the mechfabs in robotics to no longer require robotics access to use, bringing them in line with almost every other production-related fabricator, console, and machine in the game. You can use RnD and the chemistry lab without access if you hack in- Now you can do the same with the mechfab.
:cl:
 * tweak: Removed access requirements from the mechfab.

### CODE REVIEW

**Comment by Jackreturnswithaveangenace** [comment]
Hm. There's an argument to be said about keeping mechs off limits, but anything that is considered a combat weapon for mechs is already in a lockbox. I'm in favour.

**Comment by SonixApache** [comment]
lockboxes are a lot easier to get into than exofabs, and mechs are pretty dangerous
make it a wire hack if anything

**Comment by DrSnips** [comment]
We already tried to PR "wires to remove access" in the past. It didn't pass.

**Comment by SonixApache** [comment]
yeah, the joke is that when you just keep to lower complexity and streamline things over and over again eventually due to the playerbase shift and general apathy you'll get it done

**Comment by Apogee-dev** [comment]
> yeah, the joke is that when you just keep to lower complexity and streamline things over and over again eventually due to the playerbase shift and general apathy you'll get it done

It still makes absolutely no sense that the exofab is the only fabricator that's utterly untouchable without department access. Even having to hack it (as in the failed PR you mentioned) is nonstandard. The mechanic's workshop will print for anybody, everyone and their dog breaks into chemistry and/or RnD if the department doesn't watch them 24/7, and even the ammolathe will happily shit out guns and ammo for you no matter who you are. I'm not convinced leaving traitors with just a lockbox to break through (and a mech to build) is significantly more dangerous than somebody just breaking into RnD and printing out two bags of holding.

**Comment by Dacendeth** [comment]
>lockboxes are a lot easier to get into than exofabs, and mechs are pretty dangerous

Easy, just make mech parts(or just the core part) come in lockboxes. Probably just combat mech cores as well, and make em security access to boot because science shouldn't be making combat mechs without security approval anyways.

And make mech drills miner locked so you cant drill of them open.

**Comment by BomberBro** [comment]
The slippery slope has finally slid to the base of the mountain.

**Comment by SonixApache** [comment]
#21150

**Comment by Apogee-dev** [comment]
> #21150

I'm not sure what other options we have at this point. It's practically a prerequisite for #29907 (which, so far, appears to be pretty popular compared to its counterpart), and even on its own this subject's been getting enough attention that i've been hearing players complaining about it consistently since the day I moved to this server. Making it a wire hack doesn't really change much given how most wire hacks get brute-forced by the glubbless anyway (and, as mentioned upthread, is a proposal that's also failed in the past).

**Comment by ghost** [comment]
finally, cargonian mechs

**Pull request merged**
