### PR TITLE
Adds one and changes one Emagged cargo console supply packs ala @isaac in discord

### PR DESCRIPTION
**Pull request by CptWad**
Changes the spec-ops bundle to contain no parapen and no box of incendiary grenades, replaces it with silenced pistol and ammo for said pistol.

Adds a new bundle, Russian weapons crate, which costs 150 credits and gives you three random items, which can be a mosin nagant, ammo for this mosin nagant, empty ammo for the gun and laser aks.

@isaac cant into github so he asked me to PR it

### CODE REVIEW

**Comment by jakmak** [comment]
The exact items and chances of items appearing in the russian weapons crate are as follows

1/12 of getting a mosin nagant, 2/12 getting a laserAK, 3/12 of getting a full 7.62 stripper clip, 3/12 of getting a empty 7.62 stripper clip, 3/12 of getting a 7.62 ammo box. The gun used is the normal nagant and not the orbez

**Comment by CptWad** [comment]
added a changelog

**Comment by CptWad** [comment]
wat

**Comment by ComicIronic** [comment]
>one less parapen

You mean no parapen. "one less" makes it sound like there were multiple and you took one out. There is no longer a parapen in this crate.

**Comment by CptWad** [comment]
ok fixed the pr for comics autism

**Comment by clusterfack** [comment]
Sure the specops one is fine, but the 'buy a shitload of guns in an unlocked crate' is beyond stupid.

**Comment by CptWad** [comment]
@jakmak said its for emagged crates is it not cluster?

**Comment by jakmak** [comment]
It is for a emagged (not soldered) cargo console only meaning locking it would just be redundant since if they could get in the first place than they would be able to get it open like nothing. And also there is a 3 in 12 chance of getting a gun from this and not to mention seeing any of these guns would immediately come with a LYNCH THE CARGO TECHS from the stations sec/greytide/clown.

**Comment by clusterfack** [comment]
Well thats not **so** bad then

**Pull request merged**
