### PR TITLE
Hydroponics bugfixes

### LINKED ISSUE #32921: You can't speed up plant growth using diethylamine if the plant can mutate into another subspecies.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
169f18f49865b0efdfc15eeda1dc310b8e34f4db

# Description
What the title says. 
I had a very powerful eggplant splice and tried to speed it up, due to having a very long maturation time.
Poured the diethylamine, it triggered a species mutationa and I lost my progress.
It works fine for plants without a subspecies.
# Steps to Reproduce
Get a plant with a subspecies, like tomatoes, peanuts, eggplants, etc.
Pour diethylamine to speed up plant growth.
Cry because the plant does not grow and instead evolved into the subspecies.
# What you Expected
Fast growing eggplant splice thanks to the diethylamine.
# What Actually Happened
egg
i got egg from egg-plant

### LINKED ISSUE #32922: Trays don't process nutriment if there's not a plant on them.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
169f18f49865b0efdfc15eeda1dc310b8e34f4db

# Description
Dump some Nutriment (or use food as compost) onto a tray with a plant, the Nutriment gets processed into nutrients for the plant.
Dump some Nutriment onto an empty tray to refill the nutrient storage, it gets processed but the nutrients do not increase.
# Steps to Reproduce
Nutriment (the reagent) onto an empty tray that has the yellow light glowing (needs nutrients). It will consume the Nutriment but not increase the nutrients.
# What you Expected
To fix lack of nutrients on my empty trays.
# What Actually Happened
Only the trays in use processed the nutriment.

### LINKED ISSUE #32923: Can't use sugar to force pest plants to appear.
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
169f18f49865b0efdfc15eeda1dc310b8e34f4db

# Description
Before the mutation and hydroponics rework, you could increase the pest and weed values with sugar (and decrease them with salt). If you poured sugar on a tray and waited long enough, a "pest" plant would spawn in the tray: glowhsrooms, grass, amanita, harebells, etc.
They no longer spawn. The tray is not affected by sugar.
# Steps to Reproduce
Pour sugar on empty tray.
# What you Expected
Pests, weeds and eventually a plant.
# What Actually Happened
Nothing.
Might be related to the issue of nutriment not being processed I reported earlier.

### LINKED ISSUE #32948: Hematophage plants can't get the blood stock refilled
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
70591c188f8d54a325d7bd7662bb8ee5665d3406

# Description
The processing tick is too slow. I dumped 15u of blood on a newborn hematophage and it NEVER went above 0 blood, it just ticked too slow to accumulate.
# Steps to Reproduce
Get hematophage plant. Dump blood.
# What you Expected
For bloodstock to increase like with nutriment and nutrient.
# What Actually Happened
nothing.

### LINKED ISSUE #32949: Xenophysiology Splicing does not mix traits properly
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
70591c188f8d54a325d7bd7662bb8ee5665d3406

# Description
You used to be able to splice two gas creations so the plant made both n2 and o2 for example. It doesn't splice anymore. Mutating this outcome is possible, but splicing it is broken.
# Steps to Reproduce
Get 2 gas creation seeds.
Splice them together.
Only oneg as creation remains.
# What you Expected
2 gas plant.
# What Actually Happened
only oxygen.

### PR DESCRIPTION
**Pull request by adacovsk**
[tweak][bugfix][balance]

## What this does
- update tray icons when nutriment or water is added or removed... Didn't update before because there was no plant.
- nutrient now can be added with no plant
- changed phosphorus and chlorine on_plant_life slightly
- undo some salt changes, made holy salt more consistent with salt for on_plant_life
- does nothing regarding pest and weed levels as it is dependent on the plant, no point in having alert levels show when there is no plant.
- L4Z procs at a higher rate (4x faster)

## Why it's good
- Closes #32923
- Closes #32922
- Closes #32921
- Closes #32948
- Closes #32949

## Changelog

:cl:
 * bugfix: Fixes some hydroponics bugs related salts, and tray icons
 * tweak: Phosphorus and chlorine now increase weeds and decrease weeds in trays respectively
 * tweak: Left4Zed triggers 4x faster

### CODE REVIEW

**Comment by Eneocho** [comment]
What I meant by the pest and weeds thing is that when you added sugar, after a while a random plant would appear in there, generally plants you'd consider weeds or mushrooms, like grass, chanterelle, plump helmets, amanita, glowshroom, harebells and the "weeds" plant (which is great for certain splice fuckery). You can't force them to appear with sugar anymore.
The entire "random plants just appear if the tray is abandoned" mechanic depended on weeds or pests taking over the tray. Sugar was just the way to speed up the taking over, since it sped up weed and pest growth.
The classic sight of an uncrewed hydroponics bay with a lot of the trays with pest plants growing or dead from age doesn't happen anymore. 
Also, you can't get the weeds plant anymore, since you need the tray to get overtaken by weeds and get lucky, but you can't get the trays overtaken by weeds now.

**Comment by adacovsk** [comment]
Fixed sugar, sorry about that. I didn't change it properly at all. As for the weeds, I replaced this code but obviously the weed rate was still too low. It should be betwen 1 and 5% probability. I had a flat 2%. I've changed it to hopefully increase your weeds

```
if(waterlevel > 10 && nutrilevel > 2 && prob(isnull(seed) ? 5 : (1/(1+bees)))) //I hate whoever wrote this check
		weedlevel += 1 * HYDRO_SPEED_MULTIPLIER * weed_coefficient
```

**Comment by Eneocho** [comment]
Appreciated.

**Comment by Eneocho** [comment]
Salt had the effect of killing off the pests and weeds, while causing damage to the plant. A few other chems did similar stuff. Can you take a look at the chems you changed and update their values?

**Comment by adacovsk** [comment]
Updated holy salt and salt to be consistent. How are the rate of changes with the mutations though? Do plants stats change too rapidly?

**Comment by Eneocho** [comment]
For stuff like metabolism I'd actually say a bit slow, even with 45u hyperzine I saw little stat change on the water/nutrient per second. The traits unlocked and locked with consistency and fast enough though.

**Comment by adacovsk** [comment]
> For stuff like metabolism I'd actually say a bit slow, even with 45u hyperzine I saw little stat change on the water/nutrient per second. The traits unlocked and locked with consistency and fast enough though.

Fixed this, log base 10 didn't make much changes with values <10 (obviously) so I changed the formula to something simpler

**Comment by Eneocho** [comment]
The low numbers issue probably also happen with Light tolerance, Production time, Maturation time and yield, given the log10 issue, though I haven't tested changing those values with mutation.

**Comment by Eneocho** [comment]
>update tray icons when nutriment or water is added or removed... Didn't update before because there was no plant.

It wasn't that the icons didn't update. It was that the tray flatout didn't processthe nutriment (chem) if the tray was empty (it did consume the nutriment but no tray nutrition increase). It only consumed it and processed it into nutrition if the tray had a plant. The icons didn't change, but that's to be expected, since examining the tray clearly showed the Nutriment being consumed but the nutrients value of the tray not increasing.

**Comment by Eneocho** [comment]
All the chems that did something to the plant (not including the current mutagens) before the two reworks were:
Blood, Water, Antitoxin, Toxin, Holy Salts, Chlorine, Fluorine, Phosphorus, Sugar, Sacid, Pacid, EZ Nutrient, Robust Harvest, Plant-B-Gone, Insecticide, Adminordrazine, Procizine, Cryoxadone, Clonexadone, Ammonia, Diethylamine, Nutriment, PolypGelatin, Salt, Milk, MoMMI Milk, Soda Water and Beer.

Can you give those a check again? Stuff like Chlorine for example: It used to decrease water by 0.5, weeds by 3, health by 1 and increase toxins by 15. Now it only increases toxins by 8 (on the chem reagents dm). What happened to the other effects?

**Comment by adacovsk** [comment]
> All the chems that did something to the plant (not including the current mutagens) before the two reworks were: Blood, Water, Antitoxin, Toxin, Holy Salts, Chlorine, Fluorine, Phosphorus, Sugar, Sacid, Pacid, EZ Nutrient, Robust Harvest, Plant-B-Gone, Insecticide, Adminordrazine, Procizine, Cryoxadone, Clonexadone, Ammonia, Diethylamine, Nutriment, PolypGelatin, Salt, Milk, MoMMI Milk, Soda Water and Beer.
> 
> Can you give those a check again? Stuff like Chlorine for example: It used to decrease water by 0.5, weeds by 3, health by 1 and increase toxins by 15. Now it only increases toxins by 8 (on the chem reagents dm). What happened to the other effects?

I tried to balance some because of the toxins update I made so that they don't completely destroy the balance instantly, most of these changes were necessary. Toxins now affect waterlevel and vice versa, so decreasing water while increase toxins is redundant. Modified chlorine to reduce weeds, and phosphorus to increase weeds as should be irl... It shouldn't have a huge impact. Hope this is okay

**Comment by Eneocho** [comment]
>undo diethylamine changes

I just realized that the diethylamine issue only happens on baby plants (the species change mutation window), so you could still speed up plant growth even if it mutated genes, just gotta wait for the first growth stage.

**Comment by adacovsk** [comment]
okay I undid it

**Comment by Eneocho** [comment]
> okay I undid it

I'm torn on this one. On the one hand it's consistent to have it as it is currently so it matches the rest of the mutation system, on the other hand, having it pre-mutation rework is more intuitive (you could only find out the issue's solution I described by testing it and thinking about it, it's not obvious as it should) and does not cause unexpected issues when speeding up a plant (like the plant becoming toxic or high toxic while you were waiting for the growth speedup to happen.
I'd revert it as you had, despite the mutation window thing I mentioned, since trying to speed up the plant's growth only to find it becoming toxic is not really a desirable outcome.
A good middle ground would be to make a special ecophysiology mutation call for diethylamine that does not touch toxin affinity, though that's probably more effort that its worth.

**Comment by Eneocho** [comment]
Could you take a look at #32932 and #32931 as well?

**Comment by adacovsk** [comment]
> Could you take a look at #32932 and #32931 as well?

death nettles are not considered plants, and lighting is unrelated... I did make a recent PR regarding lighting that adds some CHECK_TICKS to reduce lag, but it can cause delays

**Comment by Eneocho** [comment]
>death nettles are not considered plants

But they are. You can insert the death nettle leaves, eggs and wooden trunks onto the plant bag without issue as intended (they are valid harvests of death nettle, egg-plant and towercaps respectively), but it doesn't harvest into the bag for some reason.

**Comment by adacovsk** [comment]
>But they are. You can insert the death nettle leaves, eggs and wooden trunks onto the plant bag without issue as intended (they are valid harvests of death nettle, egg-plant and towercaps respectively), but it doesn't harvest into the bag for some reason.

Well, I'm just saying what I was told. Thanks for the bug reports. Upon further codediving, I think the reason why they drop to the floor instead of in the bag is because they need to pass a check on whether you're wearing gloves or cutting it down before it can be put into the bag. Consequently, if you put multiple in the bag you might instantly die without gloves

**Comment by Eneocho** [comment]
If you could keep the diethylamine pre-rework that'd be great. I know I said something about it still being useable to speed up growth if you wait one growth cycle, but man is it annoying to forget you spliced on a plant with available subspecies, pour the dieth and finding that the splice is lost because the plant mutated into the subspecies.

**Comment by adacovsk** [comment]
> If you could keep the diethylamine pre-rework that'd be great. I know I said something about it still being useable to speed up growth if you wait one growth cycle, but man is it annoying to forget you spliced on a plant with available subspecies, pour the dieth and finding that the splice is lost because the plant mutated into the subspecies.

yep, I did that for you already. I tested the consume/exude gasses splice and it works, also blood works properly (I copied old code, stupid me)

**Comment by Eneocho** [comment]
>yep, I did that for you already.

Yes, but you said you undid it. I'm asking you to undo the undoing please.

**Comment by Eneocho** [comment]
Very much appreciated.

**Pull request merged**
