### PR TITLE
Complete - (Not an actual) Powernet Optimization

### LINKED ISSUE #3266: powernets don't seperate properly
if you cut a wire the wires connected to it will stay connected to the same powernets, even if they're fully seperated, it makes seperating networks a pain

### LINKED ISSUE #3368: [Bug] Emitters don't require power once turned on.
This is bad.  Once an emitter has been powered on, it will stay on forever until it's turned off or destroyed.  

Get a wire with power and set up an emitter like it should be done.  Cut the wires leading to it and even directly underneath it.  Watch as it laughs at you.

ss 2015-03-09 at 02 26 47

You can even turn it on and off without it caring about needing a power source.  http://a.pomf.se/yzqayz.webm

@PJB3005 suggests its a powernet issue and not one inherent to emitters.  I don't know the reason why this happens, but I do know it's a pretty bad oversight.   

N3X15 agrees its a powernet issue.

### LINKED ISSUE #3388: Cutting cables doesn't disconnect neighbours from network
Isolate a cable by cutting 2 neighbour cables, use multitool on it and be amazed as it still has juice flowing through it.

### PR DESCRIPTION
**Pull request by clusterfack**
This sets to put right the 'optimization' someone made to powernets a long time ago so that they could handle large explosions. Unfortunately the "defer powernet rebuild" never actually rebuilt the powernets causing them to simply pretend powernets were connected when destroyed by explosions or singularities.

At some point this problem has been further exacerbated to the point where disconnecting powernets doesn't work in the first place. So this PR aims to take a hybrid of the pipenet method of datum networks.

1. Expand properly when adding something to the powernet (pipenets currently dont do this for shame)
2. When the powernet is destroyed by cutting or explosions or something, null the powernet out and store some data about it in the cables
3. When the powernet is used by a machine/cable or by the next tick, rebuild it from the cables giving it its old properties for the new tick update

To be clear: this has no performance gain or loss on the primary server, because the primary server uses defer_powernet_rebuild which results in the same performance but bugs out powernets. Whereas this doesn't bug out powernets.

Also on a related note, this makes make powernets not be slow.

Fixes #3388
Fixes #3368
Fixes #3266

### CODE REVIEW

**Comment by clusterfack** [comment]
Fuck I have another bug I found

**Comment by Probe1** [comment]
will it also fix these?
https://github.com/d3athrow/vgstation13/issues/3368
https://github.com/d3athrow/vgstation13/issues/3266

**Comment by clusterfack** [comment]
Yes it will fix those

**Comment by clusterfack** [comment]
Alright this is ready now. Basically what part 3 of my commit finished off was a few bugs I had accidentally created after 2 while adding in very strong sanity against any runtimes or general failures for power machinery that try to get a powernet when there isn't one. (it will force a manual rebuild now instead of doing nothing)

Power_machinery and powernet process will both make sure their networks have been rebuilt before processing, by just cycling through a short list and checking one var. Also powernets will take on the properties of their last tick so energy isn't 'lost' when cutting powernets over and over. (or a singularity eating wires again and again)

All the bugs or unintended behavior have been painstakingly quashed over the past three days.

**Comment by clusterfack** [comment]
Merge when

**Pull request merged**
