### PR TITLE
Boxstation Fixes + Porting Boxstation Outpost to Metaclub

### LINKED ISSUE #5438: (WEB REPORT BY: apeh REMOTE: 198.245.63.50:7777) Add an intercom Boxstation
>Revision (Should be above if you're viewing this from ingame!)
2867574f4774b4cf95b8dcf74b695a63c0cc42b3 (what a fucking compicated revision name)

>General description of the issue
Telecomms satellite room with two turrets has no Intercom. Why is that an issue? 
Because you can dump someone in there without a headset and they will be forever tormented and never found by anyone. 
It's a fate worse than death.

>What you expected to happen
Intercom to holla for help

>What actually happened
Trapped in there all round realistically but my suffering ended due to dying from chloral overdose.

>Steps to reproduce if possible
Go to telecomms satellite
Go north two doors where the room with two turrets are in
Someone strips you of your headset (and ID)
You are now there forever if there is no AI on board GG

### LINKED ISSUE #6851: Box Research Outpost needs way more disposal bins
A lot of rooms lack them and trash piles up when players do xenoarch/research botany
After further investigation, the only garbage bin on the whole roid is the one in mining in the lounge that leads to the deathtrap.

### LINKED ISSUE #7187: [Box] Atmos freezer/heater have shit placement
You can't reach the freezer/heater controls after connecting a canister, even if the other one is empty.
Don't ask me why I'm heating plasma

### LINKED ISSUE #7217: No light in the west station exit south of Cargo on Box
aaahh

### PR DESCRIPTION
**Pull request by ghost**
It's being done for all other maps, so here comes for Boxstation. That's all the easy ones, I'll take a look at Toxins after that, and the HoP shutter idea sounds at least mildly controversial so I'm going to need a header on that
- Added an intercom in the Tcomms Sat turret room, fixes #5438
- Add a somewhat convoluted Disposals system to the Research Outpost, fixes #6851
- Swapped the Atmospherics canisters around and moved the heating and cooling system to the northern wall, fixes #7187
- Added a light bulb to Engineering Maint EVA exit, fixes #7217

Research Outpost disposals were pretty painful, I'll likely fix the rest of the atmos soon, but it'll need to expand the outpost because right now it's too cramped to run proper atmos through

just_fuck_my_disposals_up

### CODE REVIEW

**Comment by PJB3005** [comment]
You better add all this shit to the other maps dylan.

**Comment by ghost** [comment]
If it's identical, you could copy Box's entire Z-level on top of it, especially since I massively improved Box's asteroid over the couple last PRs to it

**Comment by PJB3005** [comment]
Well @dylanstrategie then do so!

**Comment by ghost** [comment]
new_meta_outpost

I quickly patched it to the Meta roid, this is what the minimap looks like since a full screen would be hard to figure out

**Comment by PJB3005** [comment]
:+1: then

**Comment by Kurfursten** [comment]
:-1: Forgot lightswitch in Xenobotany from the disposals issue

**Comment by clusterfack** [comment]
How much you want to be he broke something so he'd have a reason to edit it again

**Pull request merged**
