### PR TITLE
Taxichanges 2: Disposals (and Other Blunders)

### PR DESCRIPTION
**Pull request by xpcybic**
- Cleaned up obstructive tanks in bar maint
- Fixed two instances of floating light tubes
- Rearranged secure tech storage so racks aren't blocking the door
- Opened up the weird little 2x3 room in atmos
- Fixed broken disposals to hop, theater, bar, atmos
- Adjusted air piping to hop
- Reinforced non-rwalls around engicargo minibridge
- Added external airlocks - north of minibridge, east of genetics
- Made the external airlocks by arrivals actually lead to space
- Fixed a floating door switch in xenobio
- Added plasma canister to xenobio
- Barricade blocks in disposals replaced with window barricades
- Cleaned up windows, areas, and other weirdness in vox outpost
- Little area corrections across the board

let's pretend the last one never happened
again, a second or third pair of eyes looking the map over would be a huge help

screenshot 2016-01-04 18 25 01
screenshot 2016-01-04 21 58 57

### CODE REVIEW

**Comment by Kurfursten** [comment]
That wall in atmosia looks kinda weird but I guess it isn't a huge deal. Pics of repaired disposals in front of botany/HOP?

**Comment by xpcybic** [comment]
screenshot 2016-01-05 00 18 33

Regarding the atmos wall: I was running out of places to put the extinguisher, axe, etc so I left a little divider there

**Comment by Ephx1** [comment]
1aa5b8be-b342-11e5-9225-1563809b7bc5

One thing of note, last I played taxi this area in red could not be seen by AI. Would you say that's intentional? If not could you add a camera or two in the area please?

**Comment by IratePirate** [comment]
> pipes under reinforced walls
> shig

**Comment by Kurfursten** [comment]
Not really his fault, Taxi does this everywhere

Box does it a little, too.

**Comment by xpcybic** [comment]
@Ephx1 Obviously having some blind spots is intentional but that's a relatively important place so I'll put one there. Also thanks for making me notice the camera on the door :ok_hand: 
@IratePirate I tried to get pipes away from rwalls as much as possible but sometimes it was _very hard_ to avoid

**Comment by d3athrow** [comment]
changelog for the players

**Comment by Kurfursten** [comment]
Chef doesn't have access to his own maintenance now

**Pull request merged**
