### PR TITLE
Fish tanks QoL and new environment

### LINKED ISSUE #21384: Fish tanks still buggy
Deconstructing them results in glass and circuit but no metal or wire

~~Sometimes sea devil appears to eat itself or something, it will just vanish, we need fish datums~~

### PR DESCRIPTION
**Pull request by adacovsk**
[QoL][feature]

This simplifies the fish tank code and makes it more readable. There were some unnecessary functions that just resulting in each work. As part of @Optimism333 's ideas for grey stuff, I've added in an acidic environment for grey fish types. Currently, this just adds the mechanics.

## What this does
- Adds `hatching` and `acidic` boolean variables to the egg objects, instead of having lists for separating the data for some reason.
- `acidic` means that the fish can live in an acidic environment
- An acidic environment occurs when you dump acid into the fish tank. This kills your regular fish but is good for the acidic fish and vice versa.
- Adds an overlay to show the acidic environment
- R*moved stupid comment flavor-text

## Why it's good
Adds additional functionality to fish tanks, and makes the code more readable and easier to modify

Closes #21384

## Changelog
:cl:
 * rscadd: You can put acid in fish tanks (don't do this)!

### CODE REVIEW

**Comment by Kurfursten** [comment]
This code was in desperate need of refactor. The source was trash code and it was ported with minor alterations.

I haven't read yours yet but thanks for taking it on

**Comment by adacovsk** [comment]
> This code was in desperate need of refactor

Work in progress. If I miss anything, let me know once it's out of draft, thanks

**Comment by Eneocho** [comment]
fish genetic engineering when

**Comment by Kurfursten** [comment]
Looks like you're refactoring all item interactions, so please hit this bug #21384

**Comment by Kurfursten** [comment]
I think I see a lot of room for improvement here, but I need to come at it fresh. Tonight or tomorrow.

**Comment by adacovsk** [comment]
> Looks like you're refactoring all item interactions, so please hit this bug #21384

I am looking at how it's constructed, and it's only glass? I don't think you need metal or wire

**Comment by Kurfursten** [comment]
You put the glass and circuitboard into a machine frame - 5 metal plus 5 wire. When you deconstruct it, it only returns glass and a filter, nothing from the machine frame. It doesn't even leave a machine frame behind. This is inconsistent with other machines.

**Comment by adacovsk** [comment]
> You put the glass and circuitboard into a machine frame - 5 metal plus 5 wire. When you deconstruct it, it only returns glass and a filter, nothing from the machine frame. It doesn't even leave a machine frame behind. This is inconsistent with other machines.

okay that makes sense

**Comment by ShiftyRail** [comment]
I feel absolutely awful for not making this OOP when I had the time back then and I ported it. It's a very archaic piece of code.

**Comment by Eneocho** [comment]
Is this ever getting merged?

**Comment by adacovsk** [comment]
It's definitely more usable once this is merged... I'm not touching it again since it's been months now and I've forgotten everything

**Comment by ghost** [comment]
Derelict PR, feel free to re-open if revisited.

**Comment by Eneocho** [comment]
speedmerge before it get closed again!

**Comment by adacovsk** [comment]
ready for review/merge

**Pull request merged**
