### PR TITLE
Mothership Cyberscrimp Sprite Change

### PR DESCRIPTION
**Pull request by ManopolisJones**
minicyberscrimp-1

cyberscrimp-1

## What this does
Updates the sprites for the Saucer Drone and Hover Disk from the mothership lab vault.

## Elaboration
Optimism had these sprites commissioned for our never was away mission he was working on, once upon a time. He had requested me to put this together and PR it, so these great sprites might not go to waste (also for the fact he felt he'd never get around to actually making this PR himself).

very nice

## Changelog
:cl:
 * rscadd: Updated saucer drone and hover disk sprites

### CODE REVIEW

**Comment by BomberBro** [comment]
Based on the icondiffs, does this also remove the espeon sprite?

**Comment by SonixApache** [comment]
image

**Comment by Kurfursten** [comment]
It does do that but not intentionally, this is just normal icon conflicts. That will be solved when he resolves icon conflicts, which are the second worst kind of conflicts. God have mercy on his soul.

Also: I dislike this, the old sprite was more readable and stood out better against the floor, particularly the minidrone. The new sprite is inarguably more detailed though.

**Comment by ManopolisJones** [comment]
> It does do that but not intentionally, this is just normal icon conflicts. That will be solved when he resolves icon conflicts, which are the second worst kind of conflicts. God have mercy on his soul.

 Goodness me, icon conflicts. I don't even know where this furry fuck even came from, or what need I do to fix what seemed like a simple sprite swap.

**Comment by Kurfursten** [comment]
A consequence of your last fetch date. Ask Exxon to help you

**Comment by pedr69** [comment]
keep the old minidrone

**Comment by Optimism333** [comment]
Not sure whether to be flattered or disappointed that some spessmen prefer my old codersprites vs the newer ones I had commissioned.  To each their own, I suppose.

The new minidrone has rotating lights, better shading, and more detail on the little cockpit. Personally I think it looks a lot better than the old version. I do concede that the purple cockpit from before stood out better against a floor background since it was a solid color, but I think the loss of some readability for a more detailed sprite isn't a terrible trade.

The drones also have a lot of movement. They bob up and down, the lights rotate (in the new one), and the thruster increases/decreases (moreso in the new version). I'm pretty sure they should catch the eye well enough to be readable for a player, even with the sprite update.

**Comment by ManopolisJones** [comment]
I'm just gonna go out on a limb here and assume importing in the exact same sprite set, with the exact same name, in the exact same spot, will resolve this so called "icon conflict".

**Comment by Kurfursten** [comment]
Unfortunately, icon files are encoded into binaries, which means that even if they match exactly, they don't know they match unless you tell them that they do. That's why I recommended to talk to Exxion while I recover from surgery.

**Comment by pedr69** [comment]
conflict seems pretty resolved to me
image

**Comment by Kurfursten** [comment]
well yes it would look resolved if you didn't read/comprehend my comment at all and also didn't look at the github warnings at all
image

**Comment by pedr69** [comment]
alright disregard i suck cocks

**Comment by ManopolisJones** [comment]
> Unfortunately, icon files are encoded into binaries, which means that even if they match exactly, they don't know they match unless you tell them that they do. That's why I recommended to talk to Exxion while I recover from surgery.

Ah, that is unfortunate, I suppose if it was as intuitive as just matching the DMI it wouldn't be such a pain in the ass to resolve normally. I was originally going to close the PR, and put up a new one, (and perhaps inquire about how to fix such a thing properly later) but our good friend Optimism wishes to put up the fixed PR himself.

**Pull request closed without merging**
