### PR TITLE
Extended rounds are now less likely if there's been an extended round in the last three days

### PR DESCRIPTION
**Pull request by ShiftyRail**
Because apparently people are going insane if there's no valids to kill.

:cl:
- rscadd: Weight of the Extended ruleset is halved if there's been another extended ruleset in the last days.

### CODE REVIEW

**Comment by TGFH** [comment]
We gave peace a chance. I prefer the #29742 nuclear option.

**Comment by DeityLink** [comment]
Alternatively/Additionally #29753

**Comment by ShiftyRail** [comment]
This "nuclear option" will not go down without a server vote. In the so-called golden age of the server with waifus, highpop, and vampstanded we had an higher rate of extended rounds.

**Comment by DeityLink** [comment]
> 
> 
> This "nuclear option" will not go down without a server vote. In the so-called golden age of the server with waifus, highpop, and vampstanded we had an higher rate of extended rounds.

God I had successfully forgotten that we had a waifu age, why did you remind me

**Comment by KillFurries** [comment]
Where's the bad faith label?

**Comment by mrflarg** [comment]
How about admins stop being boring incels and actually play into peopels gimmicks/projects on extended to give the round flow.

**Comment by xeroxemnas** [comment]
They would rather just alt + tab and look up dolphin porn instead of answering prayers or centcom faxes or whatever.

**Comment by Kurfursten** [comment]
Do you still want to press for this PR now that pseudo-RNG is in?

**Comment by ShiftyRail** [comment]
Nah

Le mar. 15 juin 2021 à 23:11, Kurfursten ***@***.***> a
écrit :

**Pull request closed without merging**
