### PR TITLE
Grayy Soldier Suit Energy Resistance Fix

### PR DESCRIPTION
**Pull request by Optimism333**
<tweak>

## What Does Energy Resistance Even Do? ##
- I have absolutely no idea.

## What Does the PR Do? ##
- Fixes a mistake leftover from the first Grayy space suit pr. The soldier suit was supposed to only have 15 energy resistance like the helmet does, not 30.

:cl:
 * rscadd: The Grayy Soldier Suit energy resistance has been reduced: 30 ->15

### CODE REVIEW

**Comment by Dacendeth** [comment]
Energy resist does nothing right now, not since the armor rework to be % reduction.

**Comment by Kurfursten** [comment]
Misread this as the solder suit, filled with delicious sulfuric acid

**Comment by Optimism333** [comment]
> Energy resist does nothing right now, not since the armor rework to be % reduction.

Dang, that's unfortunate. I thought maybe it might affect the duration of taser stuns or something like that.

**Comment by Eneocho** [comment]
> 
> 
> Misread this as the solder suit, filled with delicious sulfuric acid

That actually sounds like a decent armor/utility suit. You can link your solder to the solder suit and have 100u sacid for use instead of the regular 15u, if you get killed, the sacid is sprayed around in a puff of smoke, as a last fuck you to the killer.

**Comment by BomberBro** [comment]
energy resists affects the e-sword and e-bow iirc, as well as a few other very niche weapons

**Comment by Dacendeth** [comment]
Huh look at that, it does work against ebow, no dice on the energysword though. Still it used to do a lot more when it worked against tasers.

**Pull request merged**
