### PR TITLE
Bear pun

### PR DESCRIPTION
**Pull request by MadmanMartian**

### CODE REVIEW

**Comment by Kharkov72** [comment]
gee bill, FREE hyperzine?

**Comment by MadmanMartian** [comment]
Not free, it's 20 credits

**Comment by aceedex** [comment]
Honeslty these purposeless meme PRs are kind of unbearable

**Comment by Kurfursten** [comment]
Remind me which maps already have one of these budget vendors at roundstart? And ideally how many/where

**Comment by MadmanMartian** [comment]
looks to be none, but the packs themselves are orderable from cargo.

**Comment by Kurfursten** [comment]
Since this requires ordering a vendor on any map but Bagel (not in rotation) it seems fine

**Comment by ghost** [comment]
Hyperzine is already free from chemistry dispensers so I don't see the issue.

**Comment by SonixApache** [comment]
- make it a coin item, that one doesn't have coin items yet
- ~~do soda cans even hold more than 30 units?~~ yeah, they hold up to 50, so that's fine

**Comment by SkowronX** [comment]
tf2 is for casuals

**Pull request merged**
