### PR TITLE
Cage bugfix

### LINKED ISSUE #8545: Cage Issue
(WEB REPORT BY: mxr41 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Dissolving a cage with acid as a xeno while inside the cage results in being killed or nullspaced.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

### PR DESCRIPTION
**Pull request by unid15**
Fixes #8545

### CODE REVIEW

**Comment by gbasood** [comment]
Could you work on #8435 as well? Not necessarily during this PR just thought I'd nag

**Comment by unid15** [comment]
I think I already fixed it

edit - yeah I did http://puu.sh/nokux/b44695840c.png

**Comment by 9600bauds** [comment]
Aaaaaahhhhhhhh dreammaker

**Comment by gbasood** [comment]
I think you might want atom/movable? (sp)

**Pull request merged**
