### PR TITLE
Adds a new lobby screen.

### PR DESCRIPTION
**Pull request by Probe1**
There were a few more lobby screens in the works that I was sitting on.  This is the only one that panned out.  Here it is!  Thank you to AncientOaf for creating it and @SonixApache for helping resize it.

title21

:cl:
 * rscadd: Adds another new lobby screen, thanks to AncientOaf and his radical art skills.

### CODE REVIEW

**Comment by SkowronX** [comment]
"/vg/station placement needs some work. can you post the version without it?

**Comment by N3X15** [comment]
Maybe put a stencil on its chest, below VALIDHUNTER.

**Comment by Kurfursten** [comment]
will this be further edited?

**Comment by Kurfursten** [comment]
no?

**Comment by SonixApache** [comment]
it's from the thread, artist unknown, don't count on it

**Pull request merged**
