### PR TITLE
Changes Default Preferences

### PR DESCRIPTION
**Pull request by DorainGrey**
## What this does
Changes Default FPS setting to -1, enabling greater FPS.
Changes Default say bubble setting to enabled.
Enables runechat for mobs by default.

## Why it's good
I think these features make the game dramatically easier to understand and play, especially for newer players. New players shouldn't have to dig into obscure settings to make the game anyway similar to other SS13 servers.
This will not impact players who do not like this, as they will be toggled off.

## Changelog
:cl:
 * tweak: Default Preferences tweaked to enable over 30 FPS, runechat & say bubbles.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
Mr. Kurfurst close this PR

**Comment by Theophrastus1** [comment]
> Mr. Kurfurst close this PR

fuck off moron

**Comment by ErrorsWindows** [comment]
ayo, runechat on by default?
aight i'm thumbing down and never coming back to this, unironically a hubbie change

**Comment by pedr69** [comment]
>-1 FPS

still choppy as fuck
have it default to 120 or something actually sane

**Comment by DorainGrey** [comment]
> > -1 FPS
> 
> still choppy as fuck have it default to 120 or something actually sane

Are you sure? Seems fine to me and anyone I asked.
I can change it if it's an issue.

**Comment by DorainGrey** [comment]
> ayo, runechat on by default? aight i'm thumbing down and never coming back to this, unironically a hubbie change

Why does it matter to you, this only affects new players.

**Comment by wotisjanitor** [comment]
See how these snakes try to argue

**Comment by pedr69** [comment]
>giving hubbies sane defaults..... BAD

what

**Comment by Booperkin1** [comment]
Runechat on by default is good for the hubbie newfriends we are getting and if you don't like runechat like me you can just turn it off

**Comment by Kromkar** [comment]
> See how these snakes try to argue

Fuck off retard

**Comment by PrimeDSS13** [comment]
would you be willing to change the end round jingle option to "all" instead of "classics" as default
it's a bit weird the default is the same 2 noises when we have a list of 12~ that could be playing

(honestly I don't even think end jingles work anymore though)

**Pull request merged**
