### PR TITLE
Grue Bugfixes

### LINKED ISSUE #31933: Nu-Grue: Grue-o-vision emergency shuttle lights issue
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
a858910d2e78a647e23933bfa15effc8db5d838c

# Description
Emergency shuttle blinking lights in primary hallways are a blinking solid colour that overlays ontop of everything, making it impossible to see anything as grue
# Steps to Reproduce
be grue
shuttle gets called
# What you Expected
to be able to see
# What Actually Happened
can't see shit

### PR DESCRIPTION
**Pull request by Hinaichigo**
A few bugfixes for grues.
:cl:
 * bugfix: Fixed grue ruleset not executing properly and allowed for more spawn locations.
 * bugfix: Fixed Eat ability timer not working properly.
 * bugfix: Fixed emergency lighting completely blinding grues.

Fixes #31933

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Also how do I hide all the previous commits?

**Comment by adacovsk** [comment]
you delete your previous branch and make a new one, just make sure you fetch the latest bleeding edge and merge it with yours

**Comment by Hinaichigo** [comment]
Oh I see, thanks.

**Comment by Hinaichigo** [comment]
Okay now emergency lights shoudn't be so glaring and even red light like that from flares will appear bright.

**Pull request merged**
