### PR TITLE
Cigar/cigarette chemical fluff

### PR DESCRIPTION
**Pull request by ghost**
[content]
This PR makes tobacco actually have beneficial effects and refines the negatives a bit.

- **Nicotine** now reduces jitter, drowsiness and confusion by 1 on each tick, making it a weaker ethylredoxrazine.
- **Tobacco** does the same, but with a 5% probablility of lung damage per tick. If it goes over 5 lung damage, there is a chance you start coughing, if it goes over 10, it starts causing cancer too.
- **Unfiltered tobacco** is a new reagent, that triples the effects of the nicotine inside with the cost of it 4 times more likely to do lung damage (5 > 20%)
- **Danbacco** has none of those upsides but a 50% chance to cause bad effects.

## Cigarette brand changes:

All of these are on top of containing 5 tobacco, unless noted:

- **Shoalsticks/bidis** now contain 5 units of gravy, to heal vox.
- **Golden carps** now contain 1 unit of gold powder, from their rolling paper.
- **Starlights** now contain 3 units of dexalin and 2 units of leporazine, to make being in space less painful.
- **Lucky strikes** now contain purely unfiltered tobacco.
- **Deluxe** lucky strikes also contain 5 units of hyperzine on top of this.
- **Redsuits** now contain the reagents required to make a small puff of smoke ~~and also a small chance to contain camera bugs~~.
- **NT standards** now contain 5 units of sprinkles, to heal security and command.
- **Spaceports** have a small amount of their tobacco replaced with danbacco, for economy reasons.

And cigars too, why not.

- **Cigars** now contain double the tobacco of a cigarette.
- **Cohiba robusto** cigars contain 5 units of sportdrink, for extra robustness.
- **Premium Havana** cigars replace 5 units of their tobacco with pure nicotine, for less downsides.

Let me know if any of these need tweaking or balancing.

:cl:
 * rscadd: Cigarettes in vending machines now have some extra "medicinal" purposes to them, according to supposed research or ad campaigns.

### CODE REVIEW

**Comment by Optimism333** [comment]
I like the spirit of this change, but I do want to dig a little into some questions.

Primarily, did you have a chance to test roughly how many cigarettes it takes to get the really bad effects? Like in the most extreme example: Danbacco, how many cigarettes can you smoke before heavy risk of lung cancer?

**Comment by ghost** [comment]
> I like the spirit of this change, but I do want to dig a little into some questions.
> 
> Primarily, did you have a chance to test roughly how many cigarettes it takes to get the really bad effects? Like in the most extreme example: Danbacco, how many cigarettes can you smoke before heavy risk of lung cancer?

The danbacco downside was already there before I coded this, if anything gating it behind 10 lung damage is a nerf.

**Comment by west3436** [comment]
dangerous Big Tobacco propaganda

**Comment by PrimeDSS13** [comment]
While I'm not sure how "5% a tick" translated into actual gameplay, to go down this road of making cigarettes give you cancer should probably also include cancer being properly implemented at all. 
As of current, cancer is extreme gunk code and nigh uncurable. It own-zones people hard.

**Comment by SonixApache** [comment]
>turns fluff deathsticks into actual deathsticks

haha no thanks

>adds cancer-causing reagents
>adds the primary bus/meme-only cancer-causing reagent in large quantities

HAHA NO THANKS

**Comment by ghost** [comment]
make it so if you're smoking a cigarette IR beams are revealed in a 5x5 radius

**Comment by gurfan** [comment]
>5% probablility of lung damage per tick

This is ridiculously high.
Smoking tobacco (except danbacco) shouldn't have any bad or positive effects, just keep it as fluff. The title of this PR is misleading; these are big changes.

**Comment by smalIboss** [comment]
this is insane
cancer would be pretty funny but make it an absolutely minuscule chance
get rid of hyperzine and healing chemicals

**Comment by Kurfursten** [comment]
Cigs are honestly fine as fluff

Does having a favorite brand really need to be a matter of powergaming?

**Comment by Eneocho** [comment]
Does this affect blunts?
As far as I remember blunts start with 5u of tobacco by default, I don't want my uberweed to also cause lung cancer.

**Comment by TGFH** [comment]
"A small chance to cause cancer" and "Kanef PR" combined together means it's going to cause cancer 100% of the time and probably lag the server in the process.
Also AFAIK you can't even normally acquire danbacco so nerfing its negative effects is pretty much irrelevant.

**Comment by Eneocho** [comment]
The better way to add fluff would be to add visual differences to the cigarettes and/or some fluff text a-la locutogen/blue goo that tells you you're better than [INSERT CREWMEMBER HERE] for smoking [INSERT BRAND HERE].

**Comment by SonixApache** [comment]
doublepost but i think cigs gathered enough fluff when we went from two brands to 9.

**Comment by ManopolisJones** [comment]
I for one think it's a neat idea, but I gotta wonder why the redsuits would make the puff of smoke, and the NT standard gives the sprinkles, it should probably be the other way around. Also cigarettes go out in the vacuum of space(?) making the shit in starlights kind of redundant, more so when you factor in metabolism.

**Comment by ghost** [comment]
do not add ways to put cancer back in the game. do not add ways to put cancer back in the game. do not add ways to put cancer back in the game. do not add ways to put cancer back in the game. do not add ways to put cancer back in the game. do not add ways to put cancer back in the game.

**Comment by ghost** [comment]
Pending rework.

**Comment by anunknownentity03** [comment]
bitches don't just sweat out the tumors smh

**Pull request closed without merging**
