### PR TITLE
Fixed an edge case where manually placing cables in space didn't check for proper support

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* bugfix: Fixed an edge case where placing cables in space didn't check for proper support.

### CODE REVIEW

**Comment by pedr69** [comment]
>can no longer RCL in space

the eternal coder...

**Comment by Kurfursten** [comment]
RCL being able to place cables floating in the void of space is actually an intended feature and is even on the wiki (Guide to Engineering)

**Comment by DeityLink** [comment]
This PR only addresses an edge case with manual cabling though. It's unrelated to the RCL.

That being said the RCL rewrite PR #35241 doesn't let the player place wires over space, but since you tell me it was an intended feature I'll put it back there.

**Comment by pedr69** [comment]
i'll be damned, you can click on a cable you're standing behind it to place it backwards
image

**Comment by Kurfursten** [comment]
That's good to know; I didn't look at the code on this since I was out at dinner

**Pull request merged**
