### PR TITLE
tgui merch computer

### PR DESCRIPTION
**Pull request by DamianX**
JQbZRLOEuz

I'm continuing my crusade against `html_interface`. It's really just a stripped down version of the uplink UI.

:cl:
 * tweak: The merch computer has a new user interface.

### CODE REVIEW

**Comment by Eneocho** [comment]
TGUI still lags the fuck outta my trashcan whenever I open it. Can you add a toggle to and from TGUI?

**Comment by GreatBigFailure** [comment]
Can you make this one brighter? Probably make the buttons say the full "credits" rather than cr. This version is a bit too sterile and minimalist for the merch computer, more of a tone complaint

**Comment by DamianX** [comment]
@Eneocho
> 
> TGUI still lags the fuck outta my trashcan whenever I open it. Can you add a toggle to and from TGUI?

nope

@GreatBigFailure
> Can you make this one brighter? Probably make the buttons say the full "credits" rather than cr. This version is a bit too sterile and minimalist for the merch computer, more of a tone complaint

image

Do you like this one better?

**Comment by DamianX** [comment]
There's a bunch of themes to try
TdwyICZ8ZD
MqBZiehd3l

**Comment by gurfan** [comment]
I think the orange theme fits best, though the background logo should be changed.

**Comment by DeityLink** [comment]
Any chance the icon of the item could be displayed as well?

**Comment by Kurfursten** [comment]
confl

**Comment by DamianX** [comment]
image

The background image is a bit cringe and there's way too much margin between the entries now that I've added images, and sending a bunch of base64 blobs each time the interface refreshes probably isn't great, but I guess I'm done with this

**Comment by Eneocho** [comment]
I like the first blue one the best. An option could be to add them all and add a settings button to change the colour scheme you're getting for muh personalization.

**Comment by Kurfursten** [comment]
Confl

**Comment by Eneocho** [comment]
It got merged with "cr" instead of "credits".

**Pull request merged**
