### PR TITLE
Hides the amount of people readied up to non-admins

### PR DESCRIPTION
**Pull request by ShiftyRail**
## Reasoning

This should help with the "24 readied up"phenomenon as well as help to prevent the Nuke Ops manifest count roundstart.

:cl:

- rscdel: Non-admins can no longer see the amount of people who readied up in the pre-game lobby.

### CODE REVIEW

**Comment by DamianX** [comment]
gay

**Comment by iFlashYou** [comment]
you are gay

**Comment by Killette2** [comment]
Then how do we know who to pressure to ready up?

**Comment by Accipitermaris** [comment]
wouldn't stop the "bunch of dudes latejoining 0.2 seconds into the round" phenomenon imo (& the 14ready 24ready phenomenon by proxy although the numbers would be less exact. for those who want to force X gamemode to not happen, they can just never ready up.)

**Comment by ShiftyRail** [comment]
@Accipitermaris I have been told to disable latejoining for the first 30 minutes but I prefer to do so in another PR

**Comment by MusgardTiger** [comment]
this is a good first step 👏

**Comment by DamianX** [comment]
towards turning into TTT

**Comment by bathosbathtime** [comment]
Finally some admin power creep.
To prevent this from being a shitpost, I will add that people should just put one single slot job role they want to high and have no other job slot filled with the setting to kick to lobby if they want to late join.  I beg of you.

**Comment by Blithering** [comment]
When datums roll out, will it be possible to delay the round type decision by a few minutes so people have time to latejoin and we have a more representative crew size?

**Comment by Accipitermaris** [comment]
Stealing someone else’s idea to say that it should also be lifted if the lobby pop is below 15
10 in the lobby 1 ready is not uncommon at all for deadpop & no one wants to ready up into an empty server

**Comment by DrSnips** [comment]
I second the thing about low pop. I've seen plenty of lobbies times where 13 people are connected but only 2 or 3 are actually ready. This is partly due to some people looking to fill certain needed roles if no one selected them round start, like engi or med, and fill those in as needed.

**Comment by ghost** [comment]
For those of you who don't pay a lot of attention, when the round starts there's a text telling you what gamemode it can be.

Literally the only changes this makes are no more metagaying ops (good) and no more annoying lobby spam of REEEEEEE FIVE MORE READY UP REEEEEEE (good)

**Comment by Accipitermaris** [comment]
A lot of the times I ready up for rounds I otherwise wouldn’t play doing so will get the ready count up to 25 ready

Removing the counter means less metagaming ops & less people deliberately unreadying to limit the gamemodes, but it also means less of the former as well when we don’t have a lot of wiggle room at all during highpop rounds to unlock these gamemodes (it’s usually something like 30~ in the lobby at highpop, so 25+ ready requires a high ratio to ready up)

**Comment by MusgardTiger** [comment]
I know that some people ready up to hit 25 readyups because they are kind souls but 25+ antags are 25+ for a reason. They work best when there is a sizeable crew to oppose them, having disinterested or alt+tab'd crew isn't doing anyone any favors. 

As for low pop argument, why would you expect people to ready up to play if you yourself won't because >not a lot of people playing. Like ready up if you wanna play and if you don't think round will be fun for you because there aren't enough people around nobody is stopping you from going afk or braindead.

**Comment by Diavill** [comment]
>This should help with the "24 readied up"phenomenon
citation fucking needed
Also french PR

**Comment by Accipitermaris** [comment]
>I know that some people ready up to hit 25 readyups because they are kind souls but 25+ antags are 25+ for a reason. They work best when there is a sizeable crew to oppose them, having disinterested or alt+tab'd crew isn't doing anyone any favors.

sure but it's worth mentioning that without people deliberately readying up to 25 it's likely we wouldn't have any [insert 25 gamemode here] nuke op rounds in 2018. ideally the ready quantities would be adjustable to what a given server's "highpop" is, & what is considered highpop for us has changed massively over the past 2 years, but our ready values for the various gamemodes haven't adjusted to that.

>As for low pop argument, why would you expect people to ready up to play if you yourself won't because >not a lot of people playing. Like ready up if you wanna play and if you don't think round will be fun for you because there aren't enough people around nobody is stopping you from going afk or braindead.

positive feedback loop vs negative feedback loop
see people readying up --> ready up 
don't see if people are readying up --> don't ready up because you don't know that other people are readying up --> don't ready up because other people aren't readying up --> repeat
both of these can happen with shown and hidden ready quantities but hidden ready quantities steers us toward the latter
ideally you want lobby mechanics that encourage people to play as opposed to anything else

**Comment by MusgardTiger** [comment]
Not having highpop antags would be preferable to having them and them steamrolling the crew. I think every nuke ops we've had recently absolutely shat on the crew because there weren't enough people around to oppose them. 

Please keep in mind that we live in the worst timeline, we are in the negative feedback loop.

**Comment by Accipitermaris** [comment]
I agree about that
I just don’t think this particular change would have a positive effect on that feedback loop

**Comment by Tokanova** [comment]
have players who aren't readied by the time the round starts be immediately ejected to observer mode with no chance of joining the round for the rest of its duration.
or just remove readying up altogether and have being in the game count as 'readied' with no possible unready state. you don't wanna play? turn the game off.

**Comment by Fruktlimpa** [comment]
@DamianX How is this a step closer to TTT? I can understand all other arguments in this PR but this one makes no sense and just seems thrown in there 4noraisons.

**Comment by ShiftyRail** [comment]
@diavil

>french PR

Thanks for the laugh

**Comment by Killette2** [comment]
I personally don't feel like playing a round if it has under 15 players roundstart. If the atmosphere feels dead so will I and I'd rather be braindead. How will I know how many people are playing if this gets pushed?

**Comment by GreenHairedAssistantRickysSmellyDick** [comment]
Terrible PR. Personally I like to check the lobby to see if my friends are readied up, if I don't see any friends readied up I don't play. This PR would mean I need to pm them "hey are you playing this round" which would be metagaming. The PR encourages me to metagame, just for wanting to play with my friends.

**Comment by Exxion** [comment]
>"24 readied up"phenomenon

Not a problem

>Nuke Ops manifest count roundstart

Problem

My gut reaction is to say fuck this PR but honestly it's not totally unreasonable

**Pull request closed without merging**
