### PR TITLE
removed polling from +PERMISSIONS

### PR DESCRIPTION
**Pull request by Intigracy**
Now it's its own flag, +POLLING

chickensaysitsgood

http://ss13.moe/index.php/admins

100% ready2merge

### CODE REVIEW

**Comment by 9600bauds** [comment]
thank you

**Comment by Aurx** [comment]
We see here the wild TGmin, trying to code features for a position he has yet to be accepted for.  

Dangerously proactive.

**Comment by Exxion** [comment]
I don't know, that admin title that isn't trialmin and his possession of all flags except +PERMISSIONS sure makes him LOOK like an admin

**Comment by Aurx** [comment]
> they haven't been reading the admin-only forums
> they're not keeping up to date with the admin-only news

**Comment by Exxion** [comment]
It would be difficult for me, a non-admin, to do that

**Comment by Aurx** [comment]
IC issue, valid, not my problem

**Comment by Intigracy** [comment]
Aurx and Arse have 2 letters in common, both start with an A, and both are four letters.

Really makes you think don'tchathink.

**Comment by clusterfack** [comment]
Is this actually going to work, I'm pretty sure it wont

**Comment by Aurx** [comment]
@clusterfack I don't see any obvious errors, what makes you think he fukt up?

**Comment by clusterfack** [comment]
Because he didn't change the sql that controls admin permissions

**Comment by Intigracy** [comment]
http://ss13.moe/index.php/admins

Like I said, I'm fairly sure the sql just stores the bitflag value.

**Comment by Intigracy** [comment]
chickensaysitsgood

**Comment by Intigracy** [comment]
Surprisingly I was able to test this locally without a database.

(toggled off)
ADMIN LOG: Intigracy/(Intigracy) toggled the +POLLING permission of intigracy
(clicking poll button)
Error: You do not have sufficient rights to do that. You require one of the following flags: +POLLING.
(toggling again)
ADMIN LOG: Intigracy/(Intigracy) toggled the +POLLING permission of intigracy
(no error, but no database so no poll stuff shows up either)

**Comment by Aurx** [comment]
Tested on live server and works fine.

**Pull request merged**
