### PR TITLE
NTRV Horizon

### PR DESCRIPTION
**Pull request by plosky1**
The NTRV Horizon, or Nanotrasen Research Vessel Horizon. Because fuck the threadposters who said I can't map.

Created entirely by me. Has been tested. Probably some stuff that's wrong though.

output

:cl:
 * rscadd: MORE MAPS - NTRV Horizon

### CODE REVIEW

**Comment by plosky1** [comment]
For some reason xoq got added too, no clue how to delete those two files but they're already in the codebase and change nothing so.

**Comment by plosky1** [comment]
There we go, should be clean and nice.

**Comment by Lunstra** [comment]
I thought this looked kinda big at first but on closer inspection it actually seems to be sort of halfway between packed and box in size, maybe closer to packed in size than box? Either way the only bad thing I can say without having played on it is there's a lack of maint to hide in or expand on but on the other hand fuck maint rapists, but aside from that it looks pret- wait where is the crab nest? AHHHHHHHHHHHHH

**Comment by RaccoonBro** [comment]
Maint seems rather plain. As far as I can tell the abandoned bar is the _only_ room in maint. It needs some more rooms, or just equipment/lockers in it every so often. Right now its just barren

**Comment by RaccoonBro** [comment]
Crew also look to have a very, very easy path into the AI core. Two r-walls and a SMES won't do much since it touches the hall next to it

**Comment by brndd** [comment]
To my understanding this is supposed to be a lowpop-ish map like Packed. The hallways certainly don't look large.

The zig-zagging straight line (yes I know that's an oxymoron) maint is a bit boring though. I really think you should sacrifice the ship's symmetry to put something in there. Or don't sacrifice the symmetry and just bulge it out symmetrically. It doesn't need tumours, it just needs a couple of rooms with things like gas masks in them.

**Comment by Exxion** [comment]
That walkway behind the engines is definitely an OSHA violation

**Comment by jknpj** [comment]
>Still has the SS13 logo

:thinking:

**Comment by RaccoonBro** [comment]
A few more thoughts after looking it over:

- The chapel being separated from the crematorium is a bit awkward. Swapping Chapel and the room above it may make it work a bit better.
- Separate sides of the Escape shuttle is a really neat idea, love it.
- Some rooms seem a bit large. Theater + Theater Storage is larger than the AI core (and has any clown ever used the Theater properly?)
- People _will_ break into medical storage if it's against the halls like that.
- Cargo has no access to the maint tunnel above it. A door in the storage room would help.
- Dorms is a bit awkward. I like the idea, but the area with the dorms themselves looks like a generic hallway. It lacks 𝚜 𝚘 𝚞 𝚕
- Some of the maint hallways are dead ends if you don't have access. If you enter maint above R&D or above the Courtroom and head south, there is no way out without going back the way you came, and those are very long halls
- Can traders dock to the station? How does mining get around?

Love the concept and think it works pretty well, just some oddities

**Comment by plosky1** [comment]
> > Still has the SS13 logo
> > 🤔

sprite me a new one

@RaccoonBro I'm currently making some minor changes, I'll see about swapping chapel because I agree on the awkwardness part. Miners share a shuttle with science, which is above science. Traders can do on the middle right side where the doors go to space.

**Comment by plosky1** [comment]
NTRVH

Added sec hardsuits, moved tech storage, added maint hallway connection, added crab room.

**Comment by Kammerjunk** [comment]
god that's a lot of rwalls

**Comment by Kurfursten** [comment]
I gotta say when I saw the PR name I was hoping it was going to be a microstation for lowpop alongside packed

**Comment by plosky1** [comment]
> I gotta say when I saw the PR name I was hoping it was going to be a microstation for lowpop alongside packed

It's not a micro-station, but it's definitely for lowpop. It's around the size of packed.

**Comment by Kurfursten** [comment]
Real thoughts:
* No one is going to be able to get the roboticist's attention from that desk
* Pipes under r-walls top right
* Pipes under walls for no reason near fitness
* Pipes under double r-walls to AI upload (actually there are probably a bunch of pipe issues)
* That sec lobby is no good, not a comfy place to sit and wait for reports
* Interrogation too far from lobby, not a natural room to handle talks in. You need a second room somewhere near the lobby where you can take prisoners to buckle in and talk to them. On box this isn't actually the real interrogation room, it's the room to the left of warden
* Jani office flaps are weird
* Public view into crematorium?
* Missing cell timers on 3/4?
* MoMMIs sometimes want a door into room to move machinery etc

**Comment by Irradiation** [comment]
>Can break into the HoS office simply by breaking a window in the courtroom.

Sasuga

**Comment by Kurfursten** [comment]
more like

>hiding a stun revolver in maint

**Comment by Lokiamis** [comment]
0/10 I don't see any artillery

**Comment by tuypo1** [comment]
Personally I would have put disposals up against space instead of having a tunnel between it and the outlet but I have no real major complaints

**Comment by plosky1** [comment]
Made a custom logo, and removed most of the piping problems. The only atmos pipes going through walls is at the command center now and that is a deliberate design choice.

NTRVHnew

**Comment by Kurfursten** [comment]
I just realized that the shorthand way people will refer to this map is "NTR"

**Comment by brndd** [comment]
That's because it cuckolds you out of playing on good maps.

**Comment by DamianX** [comment]
Maybe that's why Bay uses N[x]V rather than NT[x]V.

**Comment by incakola** [comment]
I enjoy how each map brings its own gimmick
I think you aren't making the most of your "spaceship" gimmick
Should an emergency shuttle actually dock with the ship?
Should all the escape pods be 1*2?
There is untapped gimmick potential

Also not a fan of the extreme zig zag maint
It's your map so do what your want
Excited to play it soon

**Comment by Kammerjunk** [comment]
no really why is this rwalls

image

why is the entire outside is made of rwalls
this is unprecedented

@incakola unfortunately it probably won't be viable to move the entire ship for escape if that's what you mean

**Comment by plosky1** [comment]
The outside being rwalls was for lore-reasons in that a space-ship traveling through space would have to weather debris, etc. I'm certainly open to changing it though.

The medbay area is rwalled because its storage and people will try to break in.

The south area is a relic of old sec, and shouldn't be rwalled.

**Comment by Kammerjunk** [comment]
haven't seen that happen so often
image

**Comment by veles2001** [comment]
Looks pretty cool. It reminds me of some of the goone maps.

**Comment by incakola** [comment]
@kammerjunk no we are abandoning ship
I mean we could have a large escape pod or two already docked
Or some other idea?

**Comment by SonixApache** [comment]
had a discussion about how bad the brig is on this, here's my takes

if the armory could be made slightly more square and less retarded, it would be good
this brig has a lot of dumb dead space that should not be there
warden's office should be shoved upwards, with his seat right in the center in front of the desk
EVA gear should be moved to the locker room
armory and locker room could probably be swapped
dead space at cell 3 should be killed somehow
should put tables at the end of the cell hallways
det's office could just be shoved forward into the hallway, that way we could have an actual brigbay
and an actual perma prep room
there's no execution chamber either, nor is there a cheeky for-sec-only disposals bin into space
there's no fucking cameras anywhere

**Comment by plosky1** [comment]
output

New changes. I'm honestly too tired to fix security, but I added a break room.

New maint areas that have straightened out hallways for the diagonal-fearing members of this community, and rooms.

Most of the new maint rooms are thanks to @BurntDevil

**Comment by Exxion** [comment]
pointy

**Comment by BurntDevil** [comment]
lookin good

**Comment by plosky1** [comment]
Changed the entire name so I'm rebasing.

**Comment by PaulRitter** [comment]
theres one line of missing pipe spots running down nearly in the middle of the ship.

just look in the canteen and go up or down, its in both dirs

**Comment by PaulRitter** [comment]
oops i missed the close

anyways cryo is also fucked (pipewise)

**Comment by brndd** [comment]
The missing pipes are probably a map render bug.

**Pull request closed without merging**
