### PR TITLE
Europa Lights 2021 - version 3 - wall shadows working edition

### PR DESCRIPTION
**Pull request by ShiftyRail**
Updated 28/05

## Europa Lights 2021

image

image

https://webmshare.com/bxLO4
https://a.pomf.cat/ftmdyc.webm
https://webmshare.com/3KrMX

### Introduction

Europa Lights are a new lighting engine. Unlike Goonlights, which works by combined many lighting corners objects to create an illuminated station, Europa Lights works by combining many individual *sprites* into a single atom superimposed over the game world. Being a lot less complex, this system is easier to work with and allow a much greater control over the lighting engine than Goonlights did.

light systems comp

### Features

- Every shadow, every light source, every effect is fully customisable by spriters or coders and can be dynamically adjusted at runtime.
- For example : if you want an antagonist that makes shadows much sharper by simply being around, you can do it. This could be an effect for a vampire antagonist.

- The annoying goonlight bug in which you could see the light bleeding over walls from the other side of the room is **fixed**. Cultists and maint cubbies rejoice.

- Europa Lights run at a negligible server-side cost. During testing I never saw the procs related to Europa Lights go in the top 10. By constrast, Goonlights are the most taxing system of the server. It never makes the server kneel, but it frequently needs to stop updating or slow down if the pop is too high or if something particularly demanding is taking place. Whenever your helmet light suddenly stops to follow you, this means Goonlights was paused due to lag. This shouldn't happen with Europa Lights.

- Europa Lights allow for directional flashlights. The light cone emitted by the flashlight is fully customisable. The same is true for, say, a fire. 

- Europa Lights update instantly. This means your helmet headlights (for example) will follow you instantly when you walk in maint. By constast, **goonlights update on a ticker**, which means there is a minimum latency of 0.2 seconds on light updating.

- And probably much more!

### Limits

1. Generating sprites

Europa lights require a manually drawn sprite for every light range there is. Currently there are only sprites for 5 light ranges. One would need to draw or generate the shadow for every single of those light ranges. Bigger light ranges require extremely big sprites, which run the risk of crashing or severely compromising Byond's performance, especially client-side.
It appears that the bug which caused most of the crashes in the latest version has been **fixed**.

The code I used to generate those sprites is a mix of Matlab and Python. You can find it here : 
https://gist.github.com/ShiftyRail/911f608f122c3ce355b3a67c16a23718 (warranty void if used.)

2. Choosing sprites

It is not possible to dynamically set an atom's `icon` in Byond. You cannot set a filepath as a string and use `file` to locate it without multiplying the cost by 1000, as you are no longer using the `.rsc`. This makes adding multiple DMIs for light sources, shadow cones and corners, etc, difficult to write. 
This is not a performance issue, more like a limit on the maintainability of the system.

3. The "hack" to fix light bleeding

The way I fixed light bleeding over walls is hacky. 
Okay, I found a little hacky solution to the problem of light bleeding over walls.
I cast two light atoms. One that bleeds its shadow over walls, the other doesn't. The atom that bleeds its shadow over walls is TILE_BOUND and therefore will not be seen if you don't directly see the light. The other atom is not TILE_BOUND and allows you to see a light cone without being in its direct vicinity.
As hacky and clumsy as it is, it actually works pretty well, better than I would have expected. 

There are essentially two paths now we can take.

a) The "brightness matters most" path. This means the lights will illuminate the world differently depending on the angle your character looks at them. Any wall or tile "indirectly" lit by the light atom is not visible unless you can directly see it.

It's the way that I worked with the most and is showing the best results so far. While you won't notice anything jarring (and it be a nice IC effect to suddenly see something if you get closer to the light), in some cases you will find yourself in the dark as soon as you lose sight as a light bulb or an airlock closes behind you.

It's personally what I would like to work with.

b) The "consistency matters most" path. This will try to make the lighting as independent of your position as the engine allows. (I can't guarantee it will be 100% position independent, however). I explored it a bit, and while it works, it results in a much darker station which might need a lot of remapping to work as indented, or to do more work with the shadow cones.

Feel free to comment on the option you want.

If [http://www.byond.com/forum/post/2685712](this feature request) get addressed, this hack will no longer be needed.

### Useful links

Original PR for reference : #15738
[https://gist.github.com/ShiftyRail/911f608f122c3ce355b3a67c16a23718](Sprites generation files)

### Gallery

fire
light_tiles

apcs in the dark

:cl:
- experiment: A new lighting system is used in place of Goonlights.
- rscadd: This system is darker, with objects casting shadows.
- rscadd: It allows for many effects: flickering of light sources, objects glowing in the dark, more control on the shape of light sources, etc.
- rscadd: Some objects - supermatter shards, AME cores, glow in the dark.
- rscadd: Firecamps emit more light.
- rscadd: The system is lighter on the server than goonlights.
- bugfix: This new system fixes the problem of goonlights bleeding over walls.
- experiment: All maps have been heavily reworked to accommodate for this new system. Your feedback is requested on this new lighting layout: report anything that may appear out of place.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
This should be mostly working. Only thing remaining to important are the maps (I can probably recover my work on previous iterations of Europa Lights). Also need to do some serious testing on Roid station.

**Comment by gurfan** [comment]
The lighting on those zigzag r-walls above the sec/med computers in the second image looks really wierd. The wall next to the meeting room door also has wierd lighting

**Comment by Eneocho** [comment]
Can't wait for this to be properly merged. Sad to see the end of the AoE lanterns, but this is fine too.

**Comment by DamianX** [comment]
image
This does look really off

**Comment by ShiftyRail** [comment]
I accidentally uploaded the wrong image, hold on

image

I know that one is not perfect either but there's a bit less bleeding here.

**Comment by ShiftyRail** [comment]
**
image
**

image

Really happy with how blurring turned out.

**Pull request merged**
