### PR TITLE
Adds two multitools to Defficiency's Primary Tool Storage

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
## What this does
Adds two multitools on one of the tables in Primary Tool Storage, because Primary Tool Storage doesn't have multitools.
## Why it's good
More in line with other maps where multitools are easily accessible in and around Primary Tool Storage. Defficiency on the other hand encouraged assistants to break into Mechanics and EVA to get multitools.
## How it was tested
Launched the map and saw the multitools.
primary tool storage

## Changelog

:cl:
 * rscadd: Defficiency's Primary Tool Storage now has two multitools.

### CODE REVIEW

**Comment by MercuriusGH** [comment]
Uhh hello? It's called Defficiency? The primary tools storage is deficient!
Use those wirecutters little greyshirt

**Comment by hacker-on-steroids** [comment]
put them somewhere in maint instead
i thought that was the whole point of deff

**Comment by boy2mantwicethefam** [comment]
There's already one in Maintenance. But only 1.

**Comment by jwhitak** [comment]
I would have thoughtlessly merged thism but now you have presented before me the opposite consistency issue. Instead of 0 multitools (vs 1 in most maps), now deff tool storage will have 2 multitools (vs 1 in most maps). If maint is supposed to have another multitool vs most maps, that is where it should be.

**Comment by boy2mantwicethefam** [comment]
Just about every station has at least one multitool in or around Primary Tool Storage, and multitools in Maintenance are not too rare. Roidstation is the only exception because the multitools spawn in a fully-fledged mini-room past a Maintenance airlock in the vicinity of Primary Tool Storage. Also the fact that Defficiency does not have the tool closets that most maps have, instead electing to RNG-spawn some of the items on the tables, but the "assistant tool spawner" as it is called in the code has a lot of non-tool garbage mixed in. Also, tool closets have a 5% chance to contain insulated gloves.

**Comment by jwhitak** [comment]
Original author of the map, Duny, states: "Just ignore him, close it. Deff is already greyshit paradise thanks to the ruins. They don't need more. God I feel like I'm dying." I respect his wishes.

**Pull request closed without merging**
