### PR TITLE
Book Burning

### PR DESCRIPTION
**Pull request by gurfan**
## What this does
Lets you set books on fire using hot objects (matches, welders, flares, etc) after a short delay.

## Why it's good
Lets you purge heretical texts in a flashy way.

## Changelog

:cl:
 * tweak: Books can now be set on fire. This includes bibles, but beware the wrath of Space Jesus.

### CODE REVIEW

**Comment by Theophrastus1** [comment]
burning the bible should smite as farting on it does

**Comment by adacovsk** [comment]
> burning the bible should smite as farting on it does

or holy smoke (bad for vampires)

**Comment by gurfan** [comment]
> burning the bible should smite as farting on it does

I added the ability to burn bibles (they are technically not books) and you get punished in the same way farting on one punishes you

**Comment by Eneocho** [comment]
I could swear book burning (with a welder or lighter) was a thing already.

**Comment by west3436** [comment]
If you're doing this you might as well have it trigger at the paper autoignition temperature as well. I can give you the proc to override later

**Comment by west3436** [comment]
Override fire_act to include your proc and this outta trigger whenever it's in a room on fire to keep consistency

**Comment by Hinaichigo** [comment]
Currently can you flamethrower a big pile of books and have it ignite?

**Comment by Kurfursten** [comment]
Conf

**Comment by NigglyWiggly** [comment]
What kind of monster would do such a thing

**Comment by Eneocho** [comment]
Could you add a special interaction if you burn a "bible" as a member of the atheist "religion"? I know there's a special text for going euphoric if you wear a fedora, but it could be expanded to include atheist chaplains/crew in general.

**Comment by xeroxemnas** [comment]
BURN A BOOK, SAVE A TREE

**Comment by shitmaper** [comment]
literally Fahrenheit 451

**Comment by Eneocho** [comment]
> literally Fahrenheit 451

"No, captain, you don't understand. I'm preserving the literature here, that's why I read WGW on comms."

**Pull request merged**
