### PR TITLE
Zombie buttons

### PR DESCRIPTION
**Pull request by adacovsk**
[ui]

Just adds a button for evolve. It's currently barebones and adds/removes no additional functionality beyond just replacing the verb. This includes no spell icon

## What this does
- This turns the evolve verb into the evolve spell for zombies.

## Why it's good
You no longer have to search through your interface to evolve. Gives a platform for more zombie spells in the future? I'd like to perhaps add evolution paths to necromorphs but maybe that's not canon. Let me know in the comments.

:cl:
 * rscadd: Switched the evolve verb to a spell button for zombies.

### CODE REVIEW

**Comment by KingofHONK** [comment]
I think expanding zombie stuff would be a fun idea.

**Comment by Blithering** [comment]
I can see room for further evolution down both zombie evolution paths. Crimson heads are easy since they can evolve into lickers, and the infectious ones could evolve an infectious bite (Crew holding each other at gunpoint demanding to know whether the other party for bit would be great)

**Comment by adacovsk** [comment]
> I can see room for further evolution down both zombie evolution paths. Crimson heads are easy since they can evolve into lickers, and the infectious ones could evolve an infectious bite (Crew holding each other at gunpoint demanding to know whether the other party for bit would be great)

Only have puker, exploders, and leapers...

**Comment by Kurfursten** [comment]
conf

**Comment by xeroxemnas** [comment]
zombies are more fun than benos tbh. I should TC trade for a staff of necromancy one day.

**Pull request merged**
