### PR TITLE
Allows monkey recyclers to recycle all non-sapient animals

### PR DESCRIPTION
**Pull request by ghost**
[content][qol]
Also renames the machine to the animal recycler to make it more broad.
Should allow for the making of animal cubes out of most things (dead things with no biotic items like before) from carps to mice, except for player controlled mobs (unless emagged)

:cl:
 * rscadd: Monkey recyclers have been reformatted into being general purpose animal recyclers, now allowing the cubing of all non-sapient life... in most cases.

### CODE REVIEW

**Comment by Eneocho** [comment]
Does this mean cyberhorror cubes? Because I want me some cyberhorror cubes.

**Comment by ghost** [comment]
> Does this mean cyberhorror cubes? Because I want me some cyberhorror cubes.

If you can incapacitate them for the machine.

**Comment by Eneocho** [comment]
> > Does this mean cyberhorror cubes? Because I want me some cyberhorror cubes.
> 
> If you can incapacitate them for the machine.

The classic cryostun and boom, cybercubes.

**Comment by jwhitak** [comment]
Here's the mechanics so far:

The machine can grind any non sapient living creature and make cubes of them. It's basically the monkey recycler, but allows for any living (or previously living) creature, defined with the isliving() proc.

At base upgrades, no emag, it can only grind unconscious, non-sapient creatures. It needs three to make a single creature cube.

Better manipulators reduce the amount of creatures needed to get a cube, down to one at tier 3 parts.
Better lasers, at tier 3, allow you to grind CONSCIOUS non-sapient creatures.

Emagging allows you to grind sapient (has a key/ckey) creatures, though the above upgrades still apply. You still need tier 3 lasers to grind conscious creatures. I can't see any mechanics to link a ckey to the resulting cube, so this is a round removal action. Kanef says that he is working on this though.

**Comment by Eneocho** [comment]
>Emagging allows you to grind sapient (has a key/ckey) creatures, though the above upgrades still apply. You still need tier 3 lasers to grind conscious creatures. I can't see any mechanics to link a ckey to the resulting cube, so this is a round removal action. Kanef says that he is working on this though.

Just copypaste whatever code trash compactors use when emagged to cube a person. Cubepeople are still conscious and can speak/scream.

**Comment by ghost** [comment]
> Emagging allows you to grind sapient (has a key/ckey) creatures, though the above upgrades still apply. You still need tier 3 lasers to grind conscious creatures. I can't see any mechanics to link a ckey to the resulting cube, so this is a round removal action. Kanef says that he is working on this though.

Made it so the mind transfers to a new key from a body archive cube on creation, bringing them back.

**Comment by Eneocho** [comment]
> Made it so the mind transfers to a new key from a body archive cube on creation, bringing them back.

Does that include items and clothing? If memory serves me well that's how the emagged trash compactors work.

**Comment by ghost** [comment]
> > Made it so the mind transfers to a new key from a body archive cube on creation, bringing them back.
> 
> Does that include items and clothing? If memory serves me well that's how the emagged trash compactors work.

You have to strip them to recycle them so no, not necessary.

**Comment by Eneocho** [comment]
> > > Made it so the mind transfers to a new key from a body archive cube on creation, bringing them back.
> > 
> > 
> > Does that include items and clothing? If memory serves me well that's how the emagged trash compactors work.
> 
> You have to strip them to recycle them so no, not necessary.

Then it seems like a worse trash compactor.

**Comment by Blithering** [comment]
Does this mean you could cube and recycle bodies with a fully upgraded machine and bring back the dead?
Also in the case of emagging and grinding 3 player bodies, who gets the result?

**Comment by ghost** [comment]
> Does this mean you could cube and recycle bodies with a fully upgraded machine and bring back the dead?

I should add a check if the body is dead to make it not transfer the mind or something.

> Also in the case of emagging and grinding 3 player bodies, who gets the result?

Picked at random from body archives of the same mobtype.

**Comment by Blithering** [comment]
Sounds good, but bringing back the dead is kinda consistent with cube behaviour, and might help the criticism of being compactor but worse. Maybe there's a balanced that could be reached so that it doesn't completely invalidate the cloner once upgraded and emagged, but still exists as a novel revival method. 
Perhaps have rapid expansion from cube to dude break a few bones, or maybe require defibbing afterwards.

**Comment by Cartlord** [comment]
...But if it's EMagged, that enables malicious shit. Why not make it actually round-remove people if maxed out and EMagged, so you don't need to worry about its bullshit revive powers?

**Comment by Hinaichigo** [comment]
Does a monkey recycler necessarily resurrect the same monkey? I would say no. It grinds it down and compacts into into a cube of just-add-water instant monkey. And in the unupgraded case of 3 monkeys per cube this makes it seem even more so the case. So if a human is ground down and compacted into a cube of just-add-water instant human, and you then add water, what happens? Does the same person come out? I could see the case for a randomized catatonic human coming out.

Needing defibbing or breaking the bones doesn't apply for current monkeys so I'm not sure that it'd be consistent.

**Comment by Eneocho** [comment]
I say just use whatever system the trash compactor uses for humanoids with an amount exception so you only need 1 to recycle a human (something something humans larger than monkeys in game).

**Comment by Hinaichigo** [comment]
If you put in a grey would a grey cube come out?

**Pull request merged**
