### PR TITLE
Repaths common tools and surgery tools. 

### PR DESCRIPTION
**Pull request by DrSnips**
[formatting] [needs review]
This is a pretty broad change and manual review is going to be pretty long. This PR does 1 big thing and has 2 minor changes for complete transparency.
1. Repaths all common tools to have .../weapon/**tool**/xyz.
2. Moves some code for welders to the proper location of welder code.
3. Adds /obj/item/weapon/tool
This last one is the main reason for the change. It allows broad changes to common tools without having to do changes per item or something odd in the weapon parent which is much broader than most would want for just "tools".

I plan to do something after these changes, Rubber bands and tool color labeling. But because these changes are so big there needs to be a "IN CASE OF OH SHIT BREAK GLASS" revertible PR.

:cl:
 * experiment: Re-pathed common tools. Only a change code wise but MIGHT mess some stuff up. Report any issues with common tools (crowbars, wrenches, screwdrivers, etc.) please.

### CODE REVIEW

**Comment by DrSnips** [comment]
Awesome, map conflicts. I'd like to claim map priority for this maybe.

**Comment by ShiftyRail** [comment]
The issue is that `/obj/item/weapon` is a useless typepath. It does nothing except provide a default icon file which is overridden in most cases. Some places in the code manually typecheck it, but this is bad code which should be removed.
Rather than add another layer of pathing, I would encourage removing `/obj/item/weapon` all together.

**Comment by DrSnips** [comment]
Somebody else in the future can do that because I'm not going to take responsibility for anything that messes up and have to deal with it.
I just want a common parent for basic tools.

**Comment by ShiftyRail** [comment]
>Somebody else in the future can do that because I'm not going to take responsibility for anything that messes up and have to deal with it.

You're simply making it harder for that person.
At least, make it `/obj/item/tool/whatever`.

**Comment by DrSnips** [comment]
So be it. I need to redo it all anyway because synergy

**Comment by DrSnips** [comment]
This is now **DNM**. See the above PR that is auto-linked.

**Pull request closed without merging**
