### PR TITLE
Fixes some minor grammar/spelling errors (properly, this time)

### PR DESCRIPTION
**Pull request by ghost**
Oops.

Hopefully I used \him properly and didn't do something stupid.

### CODE REVIEW

**Comment by Kurfursten** [comment]
iirc there's another grammar issue with placing an empty plastic bag (or was it backpack?) into a trash bin, check the message

**Comment by ghost** [comment]
I might as well do that while I'm here. Gimme any more if you remember them!

**Comment by ghost** [comment]
... whoops. Well, it should still work. That's probably everything if nobody else has anything to fix.

**Comment by Kurfursten** [comment]
Yep, that should do it

**Pull request merged**
