### PR TITLE
Metaclub Changes

### LINKED ISSUE #9813: Metaclub Genetic Tradepost needs windows by the shuttle door

### LINKED ISSUE #10582: metaclub safe is bad
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> its content is useless old code trash and items you can easly get
> 
> What you expected to happen
> have cool muderboning stuff
> 
> What actually happened
> garbage and a paint
> 
> Steps to reproduce if possible
> open metaclub safe
> get trash items

### LINKED ISSUE #11671: Metaclub vox genetics outpost needs plasma
the gimmick of the metaclub vox outpost is genetics
It has modification consoles, vox chickens, chem dispensers, chemmasters, cryo, cloning, mancrowave, but no plasma
seems like an oversight

### LINKED ISSUE #12636: Metaclub has several toolbelts that are incorrectly pathed
is
/obj/item/weapon/storage/belt
should be
/obj/item/weapon/storage/belt/utility

Will fix.

### LINKED ISSUE #12641: cant reach the d20 in the wizard hideout (metaclub)
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

the d20 cant be reached without breaking the tables
>What you expected to happen
d20

>What actually happened
cant get it

>Steps to reproduce if possible
be in the wizard hideout in the metaclub station and see how you cant reach the d20

### PR DESCRIPTION
**Pull request by Probe1**
**Fixes**
Updates belt paths
Moves the D20 at the wizards den to be accessible

**Additions**

Adds 3 silver coins hidden on Metaclub to alleviate the glubb shortage
Adds new super secret items to the vault safe
Adds plasma and a grinder to the Vox Genetic Research Outpost for whatever reason that was requested.
Made Xenobio easier to leave for borers by redrawing the pipe.  You still need to be let out but the pipes to enter the station are right there in the airlock.
Added earmuffs and eyepatches to Security Medbay to satisfy the "MAKE IT DIFFERENT" tax
Added bonesetter to escape shuttle to complete the collection.
Added ATM to Metaclub Mining.

**Changes**
Changes Vox Tradepost Dock to have windows instead of RWalls so you can see if theres a ship there before opening the airlock

Closes https://github.com/d3athrow/vgstation13/issues/10582
Closes https://github.com/d3athrow/vgstation13/issues/9813
Closes https://github.com/d3athrow/vgstation13/issues/11671
Closes https://github.com/d3athrow/vgstation13/issues/9834
Closes https://github.com/d3athrow/vgstation13/issues/12636
Closes https://github.com/d3athrow/vgstation13/issues/12641

Somewhat tackles https://github.com/d3athrow/vgstation13/pull/12638

### CODE REVIEW

**Comment by Shadowmech88** [comment]
>Added earmuffs and eyepatches to Security Medbay to satisfy the "MAKE IT DIFFERENT" tax

But does it count if Boxstation's *also* has that stuff?
I thought what people wanted was for each station's Brig Medbay to have something unique to offer.

**Comment by Probe1** [comment]
@Shadowmech88 Boxstation doesn't have eyepatches.  The earmuffs are in the firing range on box.  

realtalk if you give me an idea on Metaclub brig medbay that 1. doesn't diminish the importance of actual medbay (so nothing good) but is totally unique to metaclub (so no adv medkit) hey I'll plop it in.

**Comment by Shadowmech88** [comment]
Oh, my bad, I thought you had added eyepatches and earmuffs to Boxstation's Security Medbay in some other PR. Can't remember where I thought I read that.

**Comment by Probe1** [comment]
na I added "Charcoal, Antitox, and the original inaprovaline syringe" to replace the 3 inaprovaline syringes and added some happy pills for decor and fucking up innocent naive security officers.

**Pull request merged**
