### PR TITLE
Fixes the Jester's Duit typo

### LINKED ISSUE #8821: Very Critical Issue
(WEB REPORT BY: kitfox88 REMOTE: 158.69.55.2:7777)

> Revision
> c6368b079cce5ebc170956a21a70b02f6efa664e
> 
> General description of the issue
> Jester Suit is titled Jester Duit
> 
> What you expected to happen
> Not to have my immersions ruined
> 
> What actually happened
> I was sucked out of the magical world of spacemen back into my shitty life
> 
> Steps to reproduce if possible
> Read

### PR DESCRIPTION
**Pull request by TheFriggenSawbones**
I DID IT.
Fixes #8821

### CODE REVIEW

**Comment by 9600bauds** [comment]
I told you

**Comment by TheFriggenSawbones** [comment]
you didnt tell me anything

**Comment by TheFriggenSawbones** [comment]
the meta coder cartel doesn't think a simple typo fix is ambitious enough for them so guess what people's champion sawbones has to step up to the plate

**Comment by ShiggyPiggy** [comment]
The friggen Sawbones actually did it, the absolute masman

**Comment by clusterfack** [comment]
Great job you'll be a collaborator in no time at this rate

**Comment by TheFriggenSawbones** [comment]
bless you

**Comment by TheFriggenSawbones** [comment]
WAIT DID I FUCK UP THE CHANGELOG

**Pull request merged**
