### PR TITLE
True Knock

### PR DESCRIPTION
**Pull request by Kevak**
Knock now unlocks or otherwise opens a larger assortment of things! Including lockers, lockboxes, and crates! It's also arguably slightly flashier now due to that. 

Tested locally.

..There's really not much else to add here. Said I would do this earlier in the week. Couldn't sleep so decided may as well get it done.

:cl:
 * tweak: Reports indicate Local Wizard Federation Sects have received some tips from distant colleges. Beware of wayward knocking and hide your valuables. Electronic locking is no longer safe!

### CODE REVIEW

**Review by MadmanMartian — COMMENTED** [review]
Maybe make it part of one of the upgrades?

**Comment by Kevak** [comment]
Knock does not currently have upgrades beyond the standard cooldown reducers which are received from different parts of spellcode. Viable but it'd be a bit of a headache. I don't necessarily see it as 'needed' but if the consensus is such, I can do it.

**Comment by Chazach** [comment]
knock is woefully shit, especially with all the new and very stronk wizard spells
i would say having this as default is fine

**Comment by Kurfursten** [comment]
This seems fine to me mostly because I've never felt a reason to use Knock over Jaunt, and even Jaunt is less popular than Blink

**Comment by Dacendeth** [comment]
Should make it unlock borg covers too.

**Comment by Kevak** [comment]
I considered that but felt it would need notable player discussion first. So I opted to not do that in the initial PR. I’d rather come back to it in a future PR and see what the general consensus is for that specifically.

**Comment by Pathid** [comment]
You could have it do APC covers too. And bot maintenance hatches.

**Comment by Kevak** [comment]
I considered those as well. Falls under the same reasoning as the borg/mommi covers.

**Comment by Kevak** [comment]
This has been merge ready for like a week. Does anything need changing or..?

**Comment by Probe1** [comment]
Just your usual balance wait.  It never hurts to pester collabs if your PR hasn't seen attention in a few days.

**Comment by Kevak** [comment]
Fair enough.

**Pull request merged**
