### PR TITLE
Ports tg ponies over to vg

### PR DESCRIPTION
**Pull request by optimumtact**
At @9600Bauds request

### CODE REVIEW

**Comment by SkowronX** [comment]
:+1:  Give me the ponies
th_sagat_laugh

**Comment by Probe1** [comment]
THANKS ORANGES!

Hey what's your ckey?  I want to make you an admin!

**Comment by optimumtact** [comment]
Hey man, no problem it's NikNakFlak in game, thanks bro

**Comment by ghost** [comment]
Quality

**Comment by 9600bauds** [comment]
Wooooow you didn't even port it

**Comment by gbasood** [comment]
> oranges is NikNak

i don't know how to feel about this

**Comment by clusterfack** [comment]
Good because it's a lie?

**Comment by Probe1** [comment]
we're just meming here and its time for this to go.

but I have been meaning to ban someone for 1,000 years ever since I learned that bans don't have an upper limit.

**Comment by optimumtact** [comment]
You don't like my PR ? :cry:

**Comment by 9600bauds** [comment]
Don't worry I had a laff

**Comment by Aranclanos** [comment]
this is awful and unfunny :-1:

**Comment by Intigracy** [comment]
I agree with Aranclanos.

**Comment by clusterfack** [comment]
Poor oranges you tried

**Pull request closed without merging**
