### PR TITLE
fixes wire sprites being different for some reason

### LINKED ISSUE #9070: Diagonal Wires
Hi, this is Cisrox here, the true issue reporting extravaganza. I'm here to show you how diagonal wires don't line up.

really nigga

They just go like this, and have a weird split in the cable that makes no physical sense.
The cable is from the bottom middle of the tile, to the upper left hand side.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #9070

### CODE REVIEW

**Comment by gbasood** [comment]
10/10

**Comment by clusterfack** [comment]
Neat

**Comment by Cisrox** [comment]
hi cisrox here
WHAT ABOUT THIS YOU !@#!@

**Comment by clusterfack** [comment]
Ruh roh

**Comment by Intigracy** [comment]
I can't fix that without redoing all the sprites.

cry

I'll do it sometime this week.

**Comment by ihadtoregisterforthis** [comment]
Well the sprites are aligned, but the colors aren't. There should be a way to recolor them so it isn't noticeable.

**Pull request merged**
