### PR TITLE
Invisible Ripley fix

### PR DESCRIPTION
**Pull request by JMWTurner**
I'm sorry.

### CODE REVIEW

**Comment by PJB3005** [comment]
:ok_hand:

**Comment by TheFriggenSawbones** [comment]
i forgive you

**Comment by SonixApache** [comment]
so much for invisible ripleys

**Comment by SonixApache** [comment]
Pretty sure this makes them start in the 'there's someone inside' sprite, not the 'feel free to get in' sprite.

**Comment by JMWTurner** [comment]
Ripleys were the only mechs that didn't have their initial_icon set though. @SonixApache So unless it already does it for other mechs, then it shouldn't.

**Pull request merged**
