### PR TITLE
Revert "Remove a fetish line (#18854)"

### PR DESCRIPTION
**Pull request by SysadminJeroen**
This reverts commit a5bab8b2a662f089d0bf07f611f4c6877d04a3bf.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
actually based

**Comment by ShiftyRail** [comment]
Why not bring it back in all its former glory
```
visible_message("[src] lets out a [pick("shameful","disgusting","laughable","horrible","hollow")] noise out of his disgusting anus hole thing.") 
```
Totally hilarious

**Comment by iFlashYou** [comment]
Farts removed when?

**Comment by jknpj** [comment]
No.

**Pull request closed without merging**
