### PR TITLE
Removes HOGAN lawset

### PR DESCRIPTION
**Pull request by gbasood**
Why has this lawset stayed in for so long anyway
It's pretty bad
It's literally just a meme
We already have a meme lawset

### CODE REVIEW

**Comment by kol1th** [comment]
:ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand:

**Comment by TheFriggenSawbones** [comment]
please

**Comment by MusgardTiger** [comment]
upvoted and liked and subscribed hoping to see more of your content

**Comment by ScrambledSteak** [comment]
Tito "Dickman" Dick: and if a borg uses HOGAN to do stuff that'll get somebody banned then I think they got hogan wrong
zealot: hogans a mistake
Tito "Dickman" Dick: should I make a push that permanently removes hogan
zealot: honestly yeah
zealot: we added it
zealot: saying that if it becomes a problem
zealot: we'd shoot it

I'd say it's reasonable enough. Nobody even bothered to update the wiki and nobody understands it. 2memey even if I think hulkster is great.

**Comment by kol1th** [comment]
merge

**Comment by gbasood** [comment]
If someone can actually fault me on reverting a thing I merged in the first place that's incredibly shit then so be it

**Comment by SonixApache** [comment]
can we ban shiticon players rather than ban lawsets

**Comment by SysadminJeroen** [comment]
@unid15 I think that you may have dropped the slide where men didn't die and waifufags were put in their place.

**Comment by SonixApache** [comment]
revert when

**Pull request merged**
