### PR TITLE
Dont step on snell

### PR DESCRIPTION
**Pull request by ShiftyRail**
Had the idea after an ahelp exchange
:cl:
- tweak: You can now walk over snails on harm intent to damage them.

### CODE REVIEW

**Comment by SageOfLight** [comment]
I ask that doing it barefoot causes damage from the shell

**Comment by Eneocho** [comment]
Make it so if you step on the snail, you have a 50% chance to crack the shell.

**Comment by Manleto** [comment]
I downvoted this because I don't want snails to be harmed

**Comment by GreatBigFailure** [comment]
Make them die when stepping over salt piles too.

**Pull request merged**
