### PR TITLE
Adds "Pause after first step" functionality to ventcrawling

### PR DESCRIPTION
**Pull request by BobdaBiscuit**
Since seeing xenos etc come flying out of vents unintentionally is hilarious and navigating shit as a borer with high ping is horrifyingly terrible I've added in https://github.com/d3athrow/vgstation13/pull/12846 for ventcrawling.

Same deal as before, if the preference is set it makes you pause for a moment after your first move, then you go whizzing off as usual.

Default behaviour remains the same.

:cl: rscadd: Added "Pause after first step" functionality to ventcrawling.

### CODE REVIEW

**Comment by Ephx1** [comment]
I think it'd just be better to have a toggle of popping out of vents automatically or having to use the ventcrawl verb again to get out.

**Comment by BobdaBiscuit** [comment]
Most likely but this is just correcting missed functionality for a previous PR.

**Comment by Zth--** [comment]
I can't (and couldn't) test because I'm far away from home, in Uruguay. I'll probably play some spess next weekend

**Comment by PJB3005** [comment]
The problem with flying out of vents accidentally is mapping error.

While working on my own map I took care to not have this issue by making it so that every vent was behind a turn you had to take yourself. There should never be a straight section of pipe that ends in a vent directly, there should always be a corner to the vent.

**Comment by Probe1** [comment]
That sounds like a maintainability nightmare @PJB3005

**Comment by PJB3005** [comment]
@probe1 how so?

**Comment by Probe1** [comment]
Because you'd have to teach everyone that pipes must be designed in X way, on top of not running under walls and being in logical places.  

It sounds an awful lot like it'd be better to just give players control over leaving vent behavior rather than map everything with it in mind.  Ones a small job and the other is a big job that will always have to be checked.

**Comment by PJB3005** [comment]
I don't see how having mapping standards is a maintainability nightmare.

**Comment by Probe1** [comment]
It's not a "Don't do this it'll make everything shit" standard.  It's having a policy to get around some oversight behavior that could be handled once and for all by having a player option to leave pipe exits or pause when they reach them then leave on the next input.  That would fix it forever and for good.  Changing all the maps and maintaining them in respect to that change, and checking new map submissions in respect to that change..

Huge amount of work for the gain of very few that would slow down mapping so we can get around writing a quick check and toggle.

**Comment by Zth--** [comment]
I don't think having switches for everything is good design in a game. I see the mapping standard as the real solution here.

**Comment by Probe1** [comment]
That "mapping standard" is redoing every single unary/scrubber for a minority of players then enforcing it for all time.  

Don't get me wrong if people were banging down my door to change this I'd totally be on it but only a few have ever said they consider it a problem.  I've accidentally popped out of pipes a few times.  But my thought wasn't that I should undertake a large and very tedious project to change the game.  It was to be more careful when getting near pipe exits.

**Pull request merged**
