### PR TITLE
Makes hand crank charger more powerful

### PR DESCRIPTION
**Pull request by SonixApache**
for 201127548
🆑 
 - tweak: Hand crank charger now adds 10 times more power units per crank

### CODE REVIEW

**Comment by ghost** [comment]
I have to disagree with this, I thoroughly enjoyed mashing my use hotkey and my m1 key simultaneously and constantly for 20minutes straight while sitting in a chargeless spacepod.  It was very good and engaging gameplay.

**Comment by FudgePucker** [comment]
Was that sarcastic or are you really that HARDCORE?

**Comment by EdXbtkOEwGw** [comment]
Don't APC cells have 1000 charge max?
Seems like it would take 100 seconds to fully charge an APC pre-buff (now 10sec)
I would argue charging your workstation APC during a blackout is a much more sensible use for a crank than powering a fukken spacepod.

**Comment by Kurfursten** [comment]
Yeah, the original purpose of crank chargers was to help with stuff like blackouts, not really to trivialize the power source of space exploration.

Either way it doesn't seem like a satisfying solution to anyone. Should space pods just have infinite energy? That seems to be what Harse wants in this case. I'm not saying it's right or wrong but that's a different debate. On the other hand crank chargers are already fairly practical for charging your own workplace APC or doing ghetto chemistry, though a smaller 1.5x or 2x buff wouldn't be unreasonable.

**Comment by Pathid** [comment]
APC cells have 2500 charge max and the delay is 1/10 of a second. Pretty sure this would make it possible to easily charge your APC in 2.5 seconds using a macro.

**Comment by ghost** [comment]
@Kurfursten incorrect.  I couldn't care less about spacepod charge.  I was just using a cheeky example.  It is generally fine for its purpose which can be achieved in one or two cells before you ditch it.  Spacepods being terrible for long-term space exploration.  Even with this change I wouldn't use one long-term

I like this change, because no one has fun smashing a button for a few minutes straight.  It is not fun nor engaging gameplay.  Ultimately I wouldn't be affected by this change in the slightest.  It is just nice to see a move away from supremely unfun game design.  I remember using one a week or two ago, and I asked myself: "Who in god's name thought it was a good design?"  Obviously someone with a carpal tunnel and/or an auto-clicker fetish.

**Comment by Aurx** [comment]
Crank chargers need a rework so they're just something you hit the "go" button for and then it automatically cranks until you stop it.  Clickspam just encourages macros and external utilities.

**Comment by Kurfursten** [comment]
Maybe if you had to wield it and it slowed you to a walk while cranking. Something suitably inconvenient so that we don't have officers autocranking a new cell in their offhand while batoning with their main hand.

**Comment by Pathid** [comment]
Ought to have to two-hand it at the very least.

**Pull request merged**
