### PR TITLE
Every PR before this will probably have to be remade to be able to be merged

### PR DESCRIPTION
**Pull request by Intigracy**
Earlier today, we moved the repository to an organization.  This broke something and old PRs can't be merged, nor can they be reopened if closed.

### CODE REVIEW

**Comment by BobdaBiscuit** [comment]
reeee

**Comment by Probe1** [comment]
Just add a label that says remake your pull request and apply it to all open poker quests

**Comment by Shadowmech88** [comment]
Can a PR still be merged if it's currently ready?

**Comment by N3X15** [comment]
Current status: GitHub support ticket pending.

**Comment by SonixApache** [comment]
PLS NO

**Comment by SysadminJeroen** [comment]
@SonixApache Oh yeah

**Comment by kol1th** [comment]
what is this

**Review by PJB3005 — APPROVED** [review]

**Comment by N3X15** [comment]
Current Status: Still no response from GitHub.

**Comment by N3X15** [comment]
Current status: Empty inbox.

**Comment by N3X15** [comment]
I received an update from GitHub's staff.  They are looking into it and are going to be sudoing into my account to test some things.

**Comment by N3X15** [comment]
Another update from GitHub, their engineers are investigating.  They also gave us a workaround that doesn't work.

**Comment by Exxion** [comment]
Don't we already have a workaround that *does* work, albeit inconveniently?

**Comment by N3X15** [comment]
GitHub touched base again, no ETA.

**Comment by Intigracy** [comment]
lol

**Comment by Intigracy** [comment]
th-thanks github

**Comment by Intigracy** [comment]
github fixed it

**Pull request closed without merging**
