### PR TITLE
Access tweaks

### PR DESCRIPTION
**Pull request by Kurfursten**
The access clusterfuck for the AI integ restorer is fixed, cloner requires
medbay access, RD gets mechanic workshop, mechanics get science foyer,
added machines to research outpost for research botanists (required deletion of one table)

The tweak to the outpost very small.
untitled

### CODE REVIEW

**Comment by Konater** [comment]
Xenobotany needs a bioballistic delivery system, lysis-isolation centrifuge, smartfridge, botany equipment lockers that scientists can open, water tanks/buckets (you deleted the two there before), flora disk box(es), a hand labeler and lastly pipes to harvest or drain the gases that some strange seeds will generate
xenobotany

**Comment by TermedClepe** [comment]
If you add a bioballistic delivery system and a lysis-isolation centrifuge, what's the point of hydroponics?

Is science supposed to have a clone of the entire station for their use? They are already able to build pretty much anything except cargo dependent items.

**Comment by Konater** [comment]
Botany wasn't supposed to have that shit in the first place

**Comment by TermedClepe** [comment]
@Konater
But science was supposed to have their own hydroponics, chemistry, medbay, mining access and a myriad of other things plus the ability to manufacture it all? Sure.

**Comment by Konater** [comment]
Yes because of xenoarcheology and xenobotany

**Comment by TermedClepe** [comment]
@Konater
I see, there's no reasoning with you.

**Comment by Kurfursten** [comment]
@Konater You can get water from the Chem Dispenser, and space is at a premium.

I think, soon, someone needs to look at completely redoing Box Station's research outpost, but that isn't this PR. The addition of new machines is just a bandaid fix (that is actually still fundamentally linked to the nature of the PR). I wanted this PR to be non-controversial if possible.

Mechanics were locked out of one of their departments, so they get Research access. Research Director was unable to check on its subordinates, so it gains Workshop access. Paramedic was unable to clone patients, so the door access changed. Chief Engineer was unable to use the AI Integrity Restorer, so the door access changed. Research Botanists were unable to produce their own seeds, so instead of giving them door access to botany, they got backup machines. They are different approaches, but each fix is aimed at giving a role access to something it needs.

**Comment by Midaychi** [comment]
You could give the chef a public garden and some helpers like bay,
You could remove chemistry and put in its place a chemical dispenser that upgrades as science increases its research levels (ie put beaker in and press the tricord button, whine at science till there's a clonexadone button, etc),
You could merge mechanic and pod bay into engineering,
Then you could merge chemistry and botany into the research station.

**Comment by Kurfursten** [comment]
@Midaychi This PR is not aimed at making a significant change to Boxstation. This PR is strictly to fix a few issues with access. The only changes are to door access and to add 4 objects (2 machines, 2 venders).

**Pull request merged**
