### PR TITLE
Fixes RUST turbine infinitely runtiming

### PR DESCRIPTION
**Pull request by kilozombie**
Again, this one is entirely Deity pointing something out and it seemingly working in tests.

Remade because I don't know how to use Git and nuked my mistakes from orbit.

### CODE REVIEW

**Comment by utilitas-** [comment]
That is not a R-UST turbine. It is in no way associated with the R-UST, and is far older than even the singularity engine. I don't even know if it works anymore on ZAS.

**Comment by kilozombie** [comment]
> That is not a R-UST turbine. It is in no way associated with the R-UST, and is far older than even the singularity engine. I don't even know if it works anymore on ZAS.

It is certainly gunked beyond my skill to decipher.

I only call it a R-UST part because it's found in test-rust.dmm

It shouldn't spawn for ANY REASON AT ALL, but regardless began spewing out hundreds of runtimes on a map where it should have had no way to exist. This is just a safeguard in case it ends up on a map again.

**Comment by PJB3005** [comment]
Then just remove it from the code completely?

**Comment by kilozombie** [comment]
Removing this alongside legacy minimaps are two things I've found during this escapade that would probably be helpful in the future, but I think it's for another time and a more competent coder

**Comment by utilitas-** [comment]
I just mapped a theoretical map test of the turbine engine as it was roughly in r47, and yep, it still somehow works. Generates sweet fuck all, but that's normal. No runtimes.

Also, don't remove it. It works perfectly fine as a backup power source (generating about 30kW per turbine when burning plain plasma mix), and I believe I could map it into an incinerator. It's not like the incinerator of any map can serve its intended use anyway.

**Comment by PJB3005** [comment]
If you want to re-introduce the turbine that's fine too, but this thing is gonna need a hell of a lot bigger of a code cleanup to be worthy of being put back on station. Go all out or don't bother.

**Comment by kilozombie** [comment]
I'm just trying to fix a server-fucking bug so that I can be done with this whole thing, PJB

I was given an ultimatum and I'm fulfilling it

**Comment by Exxion** [comment]
I strongly doubt this bug actually fucks the server since it looks like a pretty harmless runtime, but it's still a runtime

**Pull request merged**
