### PR TITLE
Give the Ideal Gas Constant (R) three decimals

### PR DESCRIPTION
**Pull request by ghost**
Directly from Google, when looking up "Value of R" :

> The gas constant R is 8.314 J / mol. K.

This game is an atmospheric simulation program at its core, so let's have precise atmospheric simulation

I would change other atmosphere-related things in here, but they would need more work to be included correctly

Changelog included

### CODE REVIEW

**Comment by ComicIronic** [comment]
Why did this need a changelog really now

**Comment by dylanstrategie** [comment]
Why not

**Comment by dylanstrategie** [comment]
Wrong button

**Comment by ComicIronic** [comment]
Because why does the playerbase need to know
Who is so affected by this extra decimal place that it must recorded in a public place that isn't just the Git history?

Also, changelog bloat is a real thing.

**Comment by PJB3005** [comment]
Duh, the guys at toxins need to make their mixes more precise because of this.

**Comment by clusterfack** [comment]
He has a point, making the gas constant .05% more accurate really doesn't deserve a changelog

**Pull request merged**
