### PR TITLE
YOOOOOOOOOOOO

### PR DESCRIPTION
**Pull request by jknpj**
image

Sah-moo-rhai wear salvaged from @d4n0w4r's trello. No changelog because i'm not actually adding them anywhere, yet.

### CODE REVIEW

**Comment by SonixApache** [comment]
YOOOOOOOOOOOOOOOOOO

add a wardrobe with them in it, put a nip symbol for 'clothes' on it, and toss it in the dojo

**Comment by DeityLink** [comment]
>it doesn't actually add the sound

my disappointment is immeasurable.

**Comment by Blithering** [comment]
You'd also need to add one of those bamboo log waterfall things for the preceding clonk.

**Comment by tuypo1** [comment]
Do we have all the costumes needed to fully perform the mikado yet

**Comment by SonixApache** [comment]
@DeityLink we already *have* the sound.
`sound/effects/yooooooooooo.ogg`

**Pull request merged**
