### PR TITLE
Alcatraz QoL

### PR DESCRIPTION
**Pull request by Kurfursten**
Benefits secborgs and syndie officers too. Vamphead was always supposed to go through shades, dunno why I included the eyeprot check. The screech and extra force let you do some fun breaching escapes in a pinch.

🆑 
* tweak: The shrunken vampire head can now be used inhand once per minute to screech and break glass within 1 tile. Unlike a real screech, this does not stun anyone.
* tweak: The shrunken vampire head flash now pierces eye protection like vampire glare. It also has 7 force instead of 0.
* tweak: The depocket wand is now small enough to fit in pockets.
* tweak: The energy shotgun now indicates how to toggle its fire mode when examined (alt-click).
* tweak: The autocuffer can now be used on orange shoes.
* tweak: Removing cuffs from shoes now executes their removal effect (e.g.: explodes syndicuffs, deletes borg cuffs)

### CODE REVIEW

**Comment by Blithering** [comment]
Not sure why a detective would want to breach the station, but sure why not.

**Comment by Kurfursten** [comment]
Sometimes when a hardboiled dick is hot on the case, a few ugly mugs get him cornered in a shifty alleyway and the only way out is through.

**Comment by calzilla1** [comment]
While you're touching up the energy shottie, could you add some sort of indicator to it to show if it's ready to fire or not? Like how the Glock has a red light to show that it's empty

**Comment by Kurfursten** [comment]
I don't think any of the shotguns have an indicator to say if there's one in the chamber

**Comment by SonixApache** [comment]
no guns have examine indicator, a few guns have sprite indicators
a single red/green LED would be good enough for  indicating ready status

i'll do it if this gets merged before you do it

**Comment by Kurfursten** [comment]
Added Sonix's autocuffer sprite, I'll leave any shotgun editing to him

**Pull request merged**
