### PR TITLE
Box execution chamber, revisited

### PR DESCRIPTION
**Pull request by ShiftyRail**
[box]
Partially addresses #22822 

The confession room :

conff room

New execution chamber :

Exec+gas room

Global view :

image

This moves the execution chamber a bit further to the North, so that perma inmates have full view of it and can get the tools in it if they want to escape.

To fill the void a bit, a room which is supposed to serve as a "confession room" for death row inmates has been added. It contains a bible and some flowers to help the inmates relax.
(Let's be honest most people will just use it to intrude brig via space)

Compiled and playtested. Everything seems to work.

**Why?**

The main reason is to partially address the remark in the issue mentioned, which is that it's now relatively harder for greyshirts to escape perma. This gives them access to the execution room and its resources again.

:cl:
- tweak: Box execution chamber has been moved a bit further to the North, and a room meant to confess death row inmates before their execution has been added.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
image

Alternative canister room for a more "geometrical" outline.

**Comment by ShiftyRail** [comment]
image

Fixed a rogue APC and added a oxygen first-aid kit in execution.

**Comment by KingofHONK** [comment]
I dunno how I feel about the confession room, why add a room that wont serve any function? Something like a janitorial/tool closet for the warden to keep brig in good order would be a lot more useful, however I understand if that's considered powercreepy.

**Comment by brndd** [comment]
Please fix the execution chamber Air Alarm while you're changing stuff there. It needs to have brig access, there's an air alarm subtype for that (`/obj/machinery/alarm/execution` or something).

**Comment by Lokiamis** [comment]
Chaplincreep is the best creep

**Comment by ShiftyRail** [comment]
@KingofHONK It's mostly for ""flavour"".

**Comment by SirSkeleto** [comment]
does it count as blessed ground

this is important

**Comment by ShiftyRail** [comment]
It doesn't.

**Comment by SonixApache** [comment]
'Bed' room needs a vent so you can not get fucked by infinite nitrous.
Vent as in blast doors that lead into space, not a floor vent.
Although maybe a vent to repressurize would be good?

Oh, wait, there's scrubbers. Nevermind? Still, blast door venting is cool.

**Comment by ShiftyRail** [comment]
They're scrubbers, yeah.

**Comment by nuklearcellphoneg** [comment]
Bless you, this blessed pr brought to you by the French love of contingencies and agencies.

**Comment by ShiftyRail** [comment]
Thinking of switching up the newscaster and the intercom for spicy `:i` shenanigans

**Comment by ShiftyRail** [comment]
Done for now.

**Comment by brndd** [comment]
FIX THE AIR ALARM RRRRRRRRRRRRRRRRRRRRRRREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Kurfursten** [comment]
I foresaw this conflict
Many said there would be no conflicts, but I always knew
Such is the way of mapping

**Comment by brndd** [comment]
I will make this VERY simple

1) the air alarm in the execution room needs to be `/obj/machinery/alarm/execution`

2) the air alarm in the execution room **currently is** `/obj/machinery/alarm`

3) this means that the central atmospherics computer in the room is useless for all brig staff

4) the central atmospherics computer still exists in the room despite being useless for all brig staff

**Comment by ShiftyRail** [comment]
Curse you Plosky
I'll fix it tonight probably

**Comment by ShiftyRail** [comment]
Oh God I forgot the map cleaner

**Comment by ShiftyRail** [comment]
Conflicts fixed.

**Pull request merged**
