### PR TITLE
Advanced RCD plasma window reinforcement

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
Allows chief engineer advanced RCDs to turn reinforced windows into reinforced plasma ones when a dark purple slime extract is applied

## Why it's good
saves building these too

## How it was tested
Using the advanced RCD with the plasma reinforced window schematic on reinforced winows

## Changelog
:cl:
 * rscadd: Advanced RCDs now have a new schematic that lets them turn reinforced windows into their plasma varieties for 5 matter units each, if a dark purple slime extract is applied. This will only affect the first full window and first normal window of each rotated direction on the tile, so building multiple on one tile and converting them all won't work.

### CODE REVIEW

**Comment by jwhitak** [comment]
The advanced RCD can already make rwalls without plasteel and holds considerably more matter than a regular RCD. Letting it make windows of an exotic material (plasma glass is difficult to secure) right out of the box is too much. This might be a good upgrade from science, but as-is, I gotta thumbs down.

**Comment by SECBATON-GRIFFON** [comment]
> The advanced RCD can already make rwalls without plasteel and holds considerably more matter than a regular RCD. Letting it make windows of an exotic material (plasma glass is difficult to secure) right out of the box is too much. This might be a good upgrade from science, but as-is, I gotta thumbs down.

would bumping the cost up do?

**Comment by jwhitak** [comment]
The encouragement here is for more interdepartmental stuff compared to straight buffs+adding a way to get reliable and effectively infinite plasma glass round start.

And if it's too expensive, why even have it?

**Comment by SECBATON-GRIFFON** [comment]
> The encouragement here is for more interdepartmental stuff compared to straight buffs+adding a way to get reliable and effectively infinite plasma glass round start.

another idea could be to "scan" reinforced plasma glass onto the thing to unlock this, but it could probably just encourage ripping it out of the TEG windows.

**Comment by kernikov** [comment]
No thank you, there are plenty of more balanced methods of plasma glass.

**Comment by SECBATON-GRIFFON** [comment]
> This might be a good upgrade from science, but as-is, I gotta thumbs down.

made it one now

**Pull request merged**
