### PR TITLE
Fixes Phazon Mutation Allowing Mobs with No Fat Sprites to Be Fat

### LINKED ISSUE #16725: Phazon mutations can make FAT VOX
Fat vox are not meant to exist because they're invisible when naked.

### PR DESCRIPTION
**Pull request by Shadowmech88**
Prevents mobs from gaining the `CAN_BE_FAT` flag via phazon mutation if they did not already have it.
Did not actually test this one, but I don't see any reason why it wouldn't work.
Fixes #16725.

:cl:
 * bugfix: Phazon mutation will no longer allow species to become fat if they can't already, to prevent icon errors.

### CODE REVIEW

**Comment by SGuivenne** [comment]
>but I don't see any reason why it wouldn't work.

You underestimate BYONDs power.

**Comment by Exxion** [comment]
What exactly are you trying to do with this code? Because I don't think it does what you think it does.
Also, even if it does, it could be much simpler.

**Comment by Exxion** [comment]
Ignore my last comment; I'm a dumbass
This is still not what you want though
`^=` is toggle, not remove
You want `&= ~`

**Comment by Shadowmech88** [comment]
If we don't have a list of all the bit operators somewhere, we should. Bitwise operators are hard.

**Comment by Exxion** [comment]
The only operations used commonly are:
`flags |= FLAG` (`flags` = `flags` OR `FLAG`): Add a flag
`flags &= ~FLAG` (`flags` = `flags` AND NOT `FLAG`): Remove a flag
`flags ^= FLAG` (`flags` = `flags` XOR `FLAG`): Toggle a flag

**Pull request merged**
