### PR TITLE
Adds a secrets file

### PR DESCRIPTION
**Pull request by clusterfack**
Allows coders to #include files within the secret repository by allowing the override of this file.

### CODE REVIEW

**Comment by Exxion** [comment]
So are you telling me that everything currently on the secret repo is added onto existing files?

**Comment by PJB3005** [comment]
@Exxion yes.

**Comment by clusterfack** [comment]
Worse than added onto existing files, they override existing files

**Comment by Iamgoofball** [comment]
holy fuck

remove secret when?

**Comment by clusterfack** [comment]
Never, it's gonna be great, we're gonna make a wall.

**Comment by GeneralGoose** [comment]
is this legal

**Comment by PJB3005** [comment]
@GeneralGoose Yes.

Technically it's a loophole in the GPL but whatever.

**Comment by Iamgoofball** [comment]
this is illegal, you know

you should rebase to tg

**Comment by PJB3005** [comment]
> this is illegal, you know

Nope.

> you should rebase to tg

You should rebase to /vg/.

**Comment by Iamgoofball** [comment]
i did
https://github.com/tgstation/tgstation/pull/19572

**Comment by Arthurdentist** [comment]
You have been charged with failing to properly license assets in a game made of stolen assets how do you plea?

**Comment by GeneralGoose** [comment]
memes

**Comment by clusterfack** [comment]
Even if our entire codebase was AGPL the secret repo would still be legal, as you can use closed source GPL code with it, since they are explicitly compatible.

**Comment by GeneralGoose** [comment]
I thought this is possible, but probably illegal
why has nobody ever done this then to hide their **S.E.C.R.E.T.S** ?

**Comment by Exxion** [comment]
We've already had a secret repo for a long time
This just makes it less bad

**Comment by GeneralGoose** [comment]
fucc da palice then

**Comment by ComicIronic** [comment]
You can't have closed-source GPL - if you were distributing the secret product in any way, you'd be obligated to, yknow, release the source for it. That's how FOSS works.

**Comment by clusterfack** [comment]
Something something distributing binaries GPL loophole

**Comment by PJB3005** [comment]
@ComicIronic Pomf isn't distributing the compiled server binaries however so it's legally ok.

**Comment by GeneralGoose** [comment]
we need a space lawyer in here

**Comment by DrCelt** [comment]
Again, licenses are not an actual issue. We are a non commercial insignificant project. Who's going to bring /vg/ to court over this?

**Comment by gbasood** [comment]
Even if it were a legal issue, it could be addressed when it became an issue, not before
Someone saying 'comply with your license' needs to happen before legal proceedings

**Comment by GeneralGoose** [comment]
@DrCelt i'd surely go to court over someone hiding space clown secrets from me
though seriously this game's community isn't the best

**Comment by F-OS** [comment]
what is this secret repo?

**Comment by Shadowmech88** [comment]
@F-OS 

The secret repo is where code that Pomf doesn't want just anyone to see is stored. The code that calculates antag rolls, for example.

**Comment by F-OS** [comment]
ah

**Comment by GeneralGoose** [comment]
im calling the police

**Pull request merged**
