### PR TITLE
The Batlinggun

### PR DESCRIPTION
**Pull request by SonixApache**
batlinggunupdate

High caliber less-than-lethal intervention. Sprites by the wonderful @Blithering, with moral support from @GreatBigFailure.
Fires 5 batons per burst, maximum of 50 shells (so 10 bursts).
Can be reloaded with batons. One baton is worth ten shells or two bursts. Be sure to check your cells...
Costs 18 TC. Wardens and Heads of Security get it for 12.

OOPed the minigun, hopefully.

TODO:
 - [ ] Update Wiki post-merge

🆑 
 - rscadd: Added the Batling gun, a baton gatling gun for crooked law enforcers. Sprites by Blithering.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
what are those shells it's leaving behind

**Comment by SonixApache** [comment]
Shell casings. It's the outer shell of the baton.

**Comment by DeityLink** [comment]
Frankly you should remove the shell casings altogether on that one.

**Comment by SonixApache** [comment]
I have solved the casings issue for you.
However, suddenly realized that the impacts don't make the baton hit noise.

**Comment by DeityLink** [comment]
But the casing is still visible on the baton 🤔 

Either have it only fire the tip, or even better have stunbatons spawn where the bullets land an no casings.

**Comment by SonixApache** [comment]
That's actually not the case, look closely. The baton handle is cut from the projectiles and falls on the floor in the form of a 'casing'.
I thought about stunbaton-spawn-on-hit but then it might as well be a pneumatic cannon. Think it's funnier this way.

**Comment by tuypo1** [comment]
I was expecting a gun that shot Bats to go along with the one that shoots bees but this is far better

**Comment by DamianX** [comment]
fix conflicts

**Pull request merged**
