### PR TITLE
Fixes "Write in Blood"

### LINKED ISSUE #14165: Can't examine blood on a tile anymore
#### Description of issue
Blood on tiles used to be able to be examined, It didn't have much use beyond flavour on its own, but in cult rounds ghosts can write in blood to spook the living. Not being able to examine means that you can't read what's written.

#### Difference between expected and actual behavior
Expected to be able to select blood or blood writing on a tile when right clicking, can't

#### Steps to reproduce 
try to read the blood writing outside the zombie room in deff maints, or right click on any tile with blood.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### LINKED ISSUE #24045: blood overlay related issues
#### Description of issue

this is a shitty report but i ran into this shit just now and i just want to have it written down

punching someone into paste doesn't bloody your hands
if you and everything you own is covered in blood, it won't show if that blood doesn't have DNA
showers don't wash your hands
sinks wash your hands straight through your gloves
there's no obvious way to get blood on your hands (?)
the write-in-blood verb disappears after you use it once or twice but it doesn't remove the blood from your hands which makes it weird

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #24045
Fixes #14165

image
bloody_doodles

:cl:
* bugfix: Fixed humans no longer having bloody hands unless they're wearing gloves.
* bugfix: Fixed surgery steps that should bloody your hands no longer doing so.
* rscadd: The Write in Blood verb has been reworked. Both ghosts and humans now have it at all time under the Ghost and IC tab respectively. When using it you will attempt to write on your tile. Ghosts need to be either visible, or the cult must have reached the bloodstone phase. They will look for a blood splatter or footprint in an adjacent tile, if there are several they will get the option of which one to use, along with the source's color hex code. Humans however need blood on their hands or gloves and will use that one. You can preview your message before confirming like when using a crayon. There can be only one doodle per tile, and it carries DNA and color from the source blood. Also unlike the old bloody doodles, those are maptext'd, and can be read without being examined.
* rscadd: Punching someone on a limb that is currently bleeding will splash their blood on your hands.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you deathwrite something in blood? As in a note before succumbing (like the whisper at crit, but you write instead).

**Comment by DeityLink** [comment]
could be added in another PR

**Comment by Eneocho** [comment]
> 
> 
> could be added in another PR

Please do.

**Comment by DeityLink** [comment]
Nah, got other stuff to work on. I'm not the only coder here. Allowing humans to write in blood at all instead of just ghosts was already beyond my original scope.

**Pull request merged**
