### PR TITLE
fix critlog

### PR DESCRIPTION
**Pull request by toomykins**
i guess it didn't work before?
this should make critlog actually log the crit

### CODE REVIEW

**Comment by help-maint** [comment]
Did you check that this works for fake damage sources, such has hallucination damage from being tased a lot

**Comment by toomykins** [comment]
nope

**Comment by Kurfursten** [comment]
It was working before, it just added it to the body's VV (accessible in a live round only), not to the logs visible to users.

Probably good to keep it on both for live investigation purposes

**Comment by toomykins** [comment]
i believe add_attacklogs still adds it to the live attack logs.

**Pull request merged**
