### PR TITLE
Removes the on_destroyed event for turfs

### PR DESCRIPTION
**Pull request by ShiftyRail**
Turfs are never "destroyed", they are just changed and replaced internally by Byond. Their `Destroy()` proc is never called, and as a result the `on_destroyed` event has no reason to be on those objects.

This saves us about ~500 000 datums and lists in memory usage. (3,234,561 to 2,737,027 lists, to be exact).

I tested it by letting a singulo run wild and checked for runtimes. Nothing out of the ordinary happened.

### CODE REVIEW

**Comment by DamianX** [comment]
`Destroy` is definitely called on turfs that change. The `on_destroyed` event on turfs could potentially be useful but nothing currently uses it, so this change is fine. That said, not creating the event in the first place is definitely better than deleting it.

**Comment by Exxion** [comment]
All four of the events that we have on every single atom in the game except space turfs should probably not be created until they're used
This would involve a noticeable refactor though

Thank fuck we don't have them on space turfs

**Comment by ShiftyRail** [comment]
@DamianX Are you sure ?  `Destroy` should only called within `qdel()`, and besides window for some reason (*cough* Dylan *cough*), nothing in the codebase calls destroys explicitly, and if you try to `qdel()` a turf, it throws an error and `del`s it instead. 

@Exxion I think z transition has no reason to not be relegated to `atom/movable`. Density change is the only one I think make sense in all atoms.

**Comment by Exxion** [comment]
Windows don't call `Destroy()` directly anymore
They did for a long time though

**Comment by DamianX** [comment]
I thought `Destroy` was not only called by `qdel`, but also by `atom/Del`, which is called on turfs by BYOND when they get replaced by another turf.
Looking at the code it looks like I'm wrong, that's only true for movables, which makes sense since `qdel` only works on movables.
I wonder why some turfs like `/turf/simulated/wall` override `Destroy`, then. They probably meant to override `Del`?

**Comment by ShiftyRail** [comment]
I'm just going to relegate it to `atom_movable`. I thought datums had a `on_destroyed`, but apparently not.
@DamianX : yep, `Destroy()` is entirely user defined. The thing with walls is dead code. Atom/Movables do manually call it in their `Del()`, but not regular atoms :

```dm
/atom/Del()
	DeleteFromProfiler()
	..()
```

```dm
/atom/movable/Del()
	if (gcDestroyed)
		if (hard_deleted)
			delete_profile("[type]", 1)
		else
			delete_profile("[type]", 2)

	else // direct del calls or nulled explicitly.
		delete_profile("[type]", 0)
		Destroy()

	..()
```

**Comment by gbasood** [comment]
I'm not sure if this *truly* reduces memory usage by the amount you describe, since BYOND uses a prototyping system, it should not (in best case scenario) use much less memory after this PR.
That said I'm not 100% on how that system works in this particular use case so who knows maybe I'm wrong

**Comment by Exxion** [comment]
Only works for compile-time values, which excludes datums and lists

**Pull request merged**
