### PR TITLE
Adds the MSGS.

### PR DESCRIPTION
**Pull request by PJB3005**
I had some old code from half a year ago lying about.

MSGS stands for Magnetically Suspended Gas Storage.

The MSGS's sprite.

The UI of the MSGS.

It's basically one of those large atmos tanks.

You can toggle the input on or off.

And you can set the output's pressure.

**TODO:** Make it work based on a maxmimum amount of moles instead of pressure.

### CODE REVIEW

**Comment by Exxion** [comment]
Why magnetically suspended? To account for arbitrary temperature?

**Comment by PJB3005** [comment]
Because the idea started as "SMES for gas", so I worked magnets into the name.

**Comment by clusterfack** [comment]
Why would the max amount be a molarity? The force required to keep them in suspension depends upon pressure.

**Comment by PJB3005** [comment]
My logic is that in magnetic suspension the thermal expansion is irrelevant, and that the actual limit is the pure molarity.

**Comment by clusterfack** [comment]
Well I mean if you're looking for a theoretical constraint to the machine it should be a point at which the forces holding the gas in place are no longer sufficient, which would be dependent on pressure. But whatever it doesn't really matter.

**Comment by AutismSpider** [comment]
So how much gas do i need to dump in this thing so it blows up like nuke?

**Comment by PJB3005** [comment]
I didn't add any form of explosions, sorry.

**Comment by AutismSpider** [comment]
Don't have to really. 

1st thing that came to mind when i saw this was how big of a Canister bomb would this be.

**Comment by DeityLink** [comment]
I am so sad this PR didn't actually have anything to do with metal gear.

**Comment by clusterfack** [comment]
metal gear?

**Comment by Exxion** [comment]
METAL SOLID GEAR SOLID

**Comment by FudgePucker** [comment]
Some quick questions;
How mobile with this thing be? Can I wrench it up with the gasses still in it and they stay in it or is it permanently stationary while gas is in it?
What is its maximum output and input rates? Is it pressure or volume based?
Why does it need a maximum in the first place? I have seen normal ordinary canisters have the pressure in them be in scientific notation, why does a canister that just requires 10 steel sheets hold more than a device that requires power that is made to hold large amounts of gas?

**Comment by PJB3005** [comment]
@FudgePucker 

> How mobile with this thing be?

Yes, it's mobile like the TEG circulators.

> What is its maximum output and input rates? Is it pressure or volume based?

Maximum output is 4500 kPa, behaves like a normal pump.

Input is the same as an air injector at max.

> Why does it need a maximum in the first place?

Eh I thought it'd need balance.

> why does a canister that just requires 10 steel sheets hold more than a device that requires power that is made to hold large amounts of gas?

The MSGS has 10x more volume than a regular canister.

**Pull request merged**
