### PR TITLE
Deluxe HoP cartridge and access change app

### PR DESCRIPTION
**Pull request by ghost**
[content]
image
Normal version not available by any means yet, hacked antag version can be bought in an uplink for 20 credits (12 if HoP or captain)
Let me know if this price is good, or if the access requirement should be there regardless of hacked status.

:cl:
 * rscadd: The HumanResources9001 DX PDA cartridge allows remote changing of the name, assignment, account number and accesses of any ID inside a PDA that has an active messenger on. Traitors can also purchase a hacked version of this that bypasses ID authority and mostly has a chance to avoid notifying the target.

### CODE REVIEW

**Comment by gurfan** [comment]
Being able to remotely change the access of anyone is extremely silly

**Comment by Kromkar** [comment]
> Being able to remotely change the access of anyone is extremely silly

So is coding something like that and removing the player interaction aspect of the Head of Personnel

**Comment by Eneocho** [comment]
Remote access changes are boring, silly and go against the point of having access consoles.

How about this:
You ask for the ID of the user, slot it inside the HoP PDA and change the access from there. Basically a portable access console instead of a remote access changer. 
The syndie one could disable one kind of access globally for a few minutes (for example, all engineering access is shutdown, doors flat out refuse even captain IDs), with a similar timer requirement to the LOIC ion law thing.

**Comment by WindowsErrors** [comment]
the idea in it of itself is sound, the whole concept of a portable identification computer or communications console or accessing one in a portable manner is one that's been shown in multiple other SS13 codebases, even we sort of have something like that already in the form of the PDA alerts monitor which has to be linked to an already existing station alerts computer (which I use very often as the engineer)

but like what literally everyone else has brought up the main gripe is probably going to be with the sheer power level of remotely changing people's access without their consent

imagine the redshirts getting their hands on one and acting like mini AI by just cutting the access of the guy they're trying to arrest so they physically can't run away through the doors of their own workplace, imagine the nuke ops just buying this through the uplink, imagine a whole bunch of other nightmare powertrip scenarios that the people here are inevitably going to come up with

**Comment by SonixApache** [comment]
should be merged but not be accessible, this is awful

**Comment by Theophrastus1** [comment]
absolutely not fuck off can't wait for people to rush schlomo to nab his PDA

i also see that courier font

**Comment by ghost** [comment]
Will just close this and keep the code for something else some other time.

**Comment by Kurfursten** [comment]
This would have been incredibly powerful - way too powerful. Just the application alone of remotely turning off a suspect's ID until they can be arrested catapults us into true police state power.

Personalized remote access changes are something I have considered on a couple of occasions so I understand where you're coming from, but you need to have a very delicate touch with it.

**Comment by WindowsErrors** [comment]
it was a good idea though

**Comment by Eneocho** [comment]
Turning it into a passcode-based portable access console would've been better instead of the remote thing.

**Comment by WindowsErrors** [comment]
actually who am I kidding, this was a stupid moment, real smoothbrain, you better come up with some excuse for this, like how I just say I was smoking something at the time even though I've never taken drugs once in my life, just so people don't think I'm a moron

**Pull request closed without merging**
