### PR TITLE
Buffed cryo's cooling power to make up for oversight.

### LINKED ISSUE #8052: CELT FUCKED UP CRYO AND I CAN'T BELIEVE I DIDN'T NOTICE SOONER
So, when @DrCelt said "nerfed everything that caused cold", he meant it.
# THE RATE AT WHICH CRYO COOLS PEOPLE WAS ALSO SEVERELY NERFED, WHICH MEANS THAT CRYO TAKES A SIGNIFICANT AMOUNT OF TIME BEFORE CRYOX AND CLONEX (MAIN COMPONENTS OF CRYO) TAKE ANY EFFECT.

I had a creeping suspicion that Cryo seemed to not work very good lately, but I didn't suspect this. Yep, it's fucked up ladies and gentlemen.

Comparison .webm's soon.

Some quotes to live by:

> I don't think it's fair to blame the wild ride on the thermal homeostasis regulator.
> 
> I've talked with people who play doctors before and after this change, and many of them have said "Actually, yeah, I've found the ride easier after this"

### PR DESCRIPTION
**Pull request by ghost**
Huh. That's pretty cool actually.
Turns out the reason wasn't because of me nerfing anything that does cold damage, but rather nerfing heat loss to the environment, and cryo is effectively just a fancy environment apparantely. Luckily there's already code in here to pick up the pace when cryo's environment isn't up to scratch.
fixes #8052

### CODE REVIEW

**Comment by 9600bauds** [comment]
I'll test this later to see how does this new rate compare to the pre-hypothermia one. By how much did you nerf heat loss to environment?

**Comment by ghost** [comment]
@9600bauds By a very significant margin when wearing clothing. By a decent margin when not. Previously you'd turn to bodytemperature = 20C in about five seconds. Now, you don't. Please go ahead and check it compared to pre-hypothermia, I think a 10 x estimate is probably about right, though.

**Comment by 9600bauds** [comment]
~~Seems to be sliiiightly faster but it's in the ballpark.~~ Fix works as promised.

**Comment by 9600bauds** [comment]
~~To be specific I saw jumps of about ~50 degrees at a time, old cryo was about ~40.~~

Nevermind I averaged wrong

**Pull request merged**
