### PR TITLE
Adds a super rare Syndie Bundle

### PR DESCRIPTION
**Pull request by Arthurdentist**
contains the GRAND PRIZE

### CODE REVIEW

**Comment by ComicIronic** [comment]
How horrifying.
New epidemic of suicides sweeps SS13.

**Comment by NigglyWiggly** [comment]
10/10

**Comment by Arthurdentist** [comment]
This bundle is worth 70 telecrystals
if anything its overpowered

**Comment by DrCelt** [comment]
Make it a higher chance.

**Pull request merged**
