### PR TITLE
Xenoarchaeology Nerf

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* rscdel: You no longer have a chance to find certain types of coins when excavating a digsite.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Delete this cousin

**Comment by xeroxemnas** [comment]
implying admins ever listen to prayers anyway

**Comment by Eneocho** [comment]
Keep it as it is, admins almost never answer the "gimme a wish" token that are the coins or goonecode. At least the ((((((((((((xenoarcheologist)))))))))))) will have something to brag about that isn't those fucking ZAS claws.

**Comment by DeityLink** [comment]
No. this was an oversight. Better remove the coins altogether.

**Comment by Eneocho** [comment]
> 
> 
> No. this was an oversight. Better remove the coins altogether.

It can always be a (((feature))).

**Comment by Dacendeth** [comment]
image

**Comment by Kurfursten** [comment]
I think it's fair to honor the content creator's wishes in this case

**Pull request merged**
