### PR TITLE
magazine color marking with crayons

### PR DESCRIPTION
**Pull request by SonixApache**
code bounty from @BurntDevil 
mmm_grayons

:cl:
 - imageadd: You can now add colored markings to glock/USP mags by using crayons. Clean the markings away with soap.

### CODE REVIEW

**Comment by Eneocho** [comment]
Does the rainbow crayon work too for specific colours? Or is it only clown yellow?

**Comment by Eneocho** [comment]
On my way to paint the ammo pink after homosexualizing the eguns.

**Comment by SonixApache** [comment]
i forgot that the clown crayon has a color selector thingy built in - yes, selecting a different color works
image

**Comment by cloutcode** [comment]
alec baldwin maxxing by marking all the ammo in the armory as practice rounds

**Comment by calzilla1** [comment]
If you're doing this, drop a box of crayons in the brig somewhere (also something something Marine Corps MRE)

**Pull request merged**
