### PR TITLE
Makes contamination sprite easier to see

### PR DESCRIPTION
**Pull request by Arthurdentist**
related to #7623 but doesn't fix it. I'm not skilled enough to deal with the mess that is contamination code but this at least makes it easier to spot. Its not uncommon for someone to come to medbay and die of toxins without noticing they are dressed in plasma drenched clothing. 

<u>New Sprites:</u>
new sprite

plasma sprite

### CODE REVIEW

**Comment by Ephx1** [comment]
I was about to say why not just make it bright green, but plasma is the only thing that does this isn't it?
:+1:

**Comment by Arthurdentist** [comment]
Yeah at the moment plasma is the only thing which can cause it which is why I made it purple, so that dim people can make the connection easier.

**Comment by gbasood** [comment]
Until someone decides to kill contamination or make it less shit, this is a big improvement.
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by 9600bauds** [comment]
Exactly what gbasood said, pretty much.
:+1:

**Comment by IratePirate** [comment]
10/10 QOL change.

**Pull request merged**
