### PR TITLE
Adds two new levels of power cell

### PR DESCRIPTION
**Pull request by MadmanMartian**
- Ultra Cell
    - 50000 charge capacity. That's a lot of fun
 - Rad cell
    - Low charge holding capacity, but recharges itself over time

### CODE REVIEW

**Comment by ghost** [comment]
Why?

**Comment by bathosbathtime** [comment]
Self-charging APCs would be weird.  I'm guessing the rad cell is more for weaponry and equipment?

**Comment by Blithering** [comment]
It could be used for low consumption/uptime equipment like heaters or air conditioners just fine

**Comment by Caboozles** [comment]
Can the rad cell be upped to at least 500 so it can be utilized on spacepods with some R&D?

**Comment by SonixApache** [comment]
:cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl: :cl:

**Pull request merged**
