### PR TITLE
Fixes #17190

### LINKED ISSUE #17190: Cant actually remove peoples security records or manifest for NT AIs dancing around their laws.
(WEB REPORT BY: ineptneckbeard REMOTE: 172.93.109.202:7777)
When you use the sec console to delete a record, it simply goes through but doesnt update the record, making it basically pointless and a waste of time.

The HoPs machine for editing jobs cannot be edited and does not work to fire people so the AI stops bickering.

There is currently no way to fully remove the initial record, making AI unable to consider someone "fired" as it had to ask an admin, hence this issue.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #17190

### CODE REVIEW

**Comment by ghost** [comment]
PS: fuck that entire file's code it needs an entire refactor and I am not doing it not a chance in hell.
Also I reckon this stopped working around the time we changed everything from del() to qdel()

**Comment by ghost** [comment]
pop quiz
the SECURITY console has an option to delete ALL of the records of an individual. This does not work because it's coded to set a local variable to null. But even if that weren't the case;
what would it have deleted? A little hint: it is the SECURITY console and it is deleting ALL of the records
is it A) ALL of the records
B) The General record (ie crew manifest)
C) The SECURITY records
or D) the medical records

**Comment by ghost** [comment]
the answer is the medical records :)

**Comment by ghost** [comment]
is this another 1000 bugfixes challenge

**Comment by ghost** [comment]
actually, don't merge this one yet.

**Comment by jknpj** [comment]
>18 days ago 

:100:

**Comment by DamianX** [comment]
when

**Comment by ghost** [comment]
Wake me up milf [Can't wake up]

**Comment by DamianX** [comment]
image

**Pull request closed without merging**
