### PR TITLE
A circle is 360 degrees

### PR DESCRIPTION
**Pull request by BlueNexus**
Just in case you weren't aware.

### CODE REVIEW

**Comment by kol1th** [comment]
🤔

**Comment by Exxion** [comment]
I decided to look back at the history to see who fucked up so I could laugh at them
But turns out that this has been the case for SO UNFATHOMABLY LONG, there aren't fucking records.
Blame doesn't cite an author, and instead just shows a link to the *fucking /tg/station SVN*
This number has been fucked up NOT ONLY since before we split from Bay
*NOT ONLY* since before Bay split from /tg/
But *since before /tg/station moved to a Git repo*
It has been the wrong number for at least seven years

**Comment by PJB3005** [comment]
Beautiful.

**Comment by Kurfursten** [comment]
You know why oldcode has 365 degrees

Because you turn 365 degrees and walk slightly to the right of it

**Comment by Aurx** [comment]
Watch as we merge this and everything breaks.

**Comment by Probe1** [comment]
Watafak

also this may affect solar tracking and the sun.

**Comment by Exxion** [comment]
Probably only visually

**Comment by CptWad** [comment]
no as in solar tracking uses degrees so lets make sure it does not break because its missing five nonexistant degrees

**Comment by PJB3005** [comment]
What could go wrong?!

**Comment by clusterfack** [comment]
If only they used a define, then it would have said YEARS instead.

**Comment by Exxion** [comment]
That proc just converts the degrees to a `dir`
For solar tracking, I'm pretty sure the only thing the `dir` affects is the visuals

**Pull request merged**
