### PR TITLE
Added a large beaker to Box chemistry.

### PR DESCRIPTION
**Pull request by SysadminJeroen**
It was requested in #10767, very simple.

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
Should I make a changelog or nah?

**Comment by Kurfursten** [comment]
I don't know about this. It's not hard to get another large beaker from one of the three sources with roundstart access to more beakers, or even buy from traders. It just reduces department interaction.

Why doesn't R&D start with some uranium, gold and silver? Why doesn't the mechanic start with a console screen? The botanist with a full beaker of mutagen? We think it's a good thing to encourage players to interact because it's a social game.

**Comment by ComicIronic** [comment]
Yeah, I don't think this should be done either. Convenience has become too much of a design buzzword at the cost of interaction.

**Comment by 9600bauds** [comment]
This is something that would greatly benefit me when I play Medbay and I'm not sure if that's a good thing honestly

**Comment by FudgePucker** [comment]
@9600bauds oh no a chore would be easier and less tedious. It would ruin the balance of the entire station, even though science can make large blue space beakers, chem sprayers, and multi fire syringe guns.

ITS THE END OF THE SERVER AS WE KNOW IT.

just merge it.

**Comment by ComicIronic** [comment]
Small changes should still be considered. Whining helps nobody and just makes you look like a little bitch.

**Comment by 9600bauds** [comment]
I'd fully support QoL changes like this if they are just tedium all within the same department, but this is pretty entry-level departmental cooperation.

**Comment by FudgePucker** [comment]
> interaction
> having to depend on cargo or science to do your job

Fuck you, its just another large beaker.
Science gets an autolathe and the protolathe, and the station doesn't depend on them to make meds for the entire station.
Its just a single fucking large beaker for QoL. God forbid if chemistry is made less of a fuckjng chore.

> muh interaction
> Fuck interaction.

**Comment by 9600bauds** [comment]
Wew

**Comment by clusterfack** [comment]
Those sure are some hot opinions

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker

Nice job undermining your own argument. It takes about two minute to walk to RnD or Cargo to ask for one.

In fact, you don't even need to leave Chemistry for an extra large beaker. There's one right in the grinder at roundstart that nobody ever remembers to take out. Use that instead.

**Comment by Shadowmech88** [comment]
> you don't even need to leave Chemistry for an extra large beaker. There's one right in the grinder at roundstart that nobody ever remembers to take out. Use that instead.

If there's two Chemists, then two of the large beakers go into cryo, the large beaker from the grinder gets used by one chemist, and the other chemist doesn't get one.

**Comment by FudgePucker** [comment]
Yea and after that walk you have to hope that research wasn't abandoned by who was doing it fucked off to valid hunt and the xenoarch and xenobio researchers still have on their ringer. Or that who ever went cargo didn't fuck off after getting their guns and gloves.

You shouldn't have to depend on the two most shitty departments to do your chore that helps the station.

Oh no chemistry getting another large beaker and not having to deal with assholes before being able to do their job effectively will fucking DESTROY THE META

Cargo can still provide another pill collector, science can make them blue space beakers.

What the fuck is giving another large beaker going to do to the nonexistent interactions between departments?

**Comment by icantthinkofanameritenow** [comment]
Here's an idea then: stop as if it's the coders' job to help you deal with shitheads. If you want that beaker so badly, break the windows to RnD and make the damn thing yourself.

Or if you're not retarded, ask Security to do their jobs and arrest the lazy bums for dereliction of duty. That's a thing in space law, you ought to be wielding that charge like a fucking sledgehammer.  But if course that might actually require talking to people, which it seems you and several others openly despise doing. By any chance did you have the bad judgment to not go to RnD immediately at roundstart when people are most likely to be there?

Although knowing your attitude, they may just not want to deal with you. I could understand that, to say the least.

**Comment by kol1th** [comment]
I have NEVER had a problem getting more beakers for chemistry.

**Comment by AutismSpider** [comment]
i don't know man gotten MDs asking for beakers at cargo more then going off to jerk off lab that is R&D

More or less what R&D is lab for jack asses who use it to make guns unless you like wasting time yelling at them for adv kits and shit.

**Comment by icantthinkofanameritenow** [comment]
That's funny, it normally takes me less than a minute for them to get advanced kits made when I ask for them. Maybe you just have to find better people to man RnD. 

But  in all seriousness, Chemist should have only one slot anyway. Having more than one person just has them getting in each other's way or otherwise being redundant.

**Comment by SangriaMonkey** [comment]
If you're a lone chemist you can just use the starting two for the cryo mix and the grinder's beaker for your chem work until you can be bothered to ask for more or a scientist shows up with bluespaces. Zero interaction needs to go on between you or anybody else unless you spawn with a coworker.

**Comment by ComicIronic** [comment]
Not habbening.

**Comment by SysadminJeroen** [comment]
RIP

**Comment by ConkerDev** [comment]
What about giving every department an object spawner, and walling them off with centcomm walls from other (potentially dangerous) people? Its a QoL improvement! No department inefficiency! Phazons at round start! All stations start with an already set up SME! Science maxed!

**Comment by nuklearcellphoneg** [comment]
thumbs down

Having more large beakers without having to travel around enables quite a large rate of production for chemistry while removing the need to walk between departments.

Yay, now the chemist can sit in his rwall chloral fort.

**Comment by FudgePucker** [comment]
Its just one large beaker. One.
ONE.
if two chemists enter round start one of them has to go to science to get a large beaker instead of starting on the chore that medbay needs done to run smoothly.

The chore that is not very fun.

Its like expecting engineering to have to order parts for the engines from cargo instead of getting any of them round start.
Pros: MOR INTUR AHTUN
Cons: we spend every round in the dark.

**Comment by ComicIronic** [comment]
Still not habbening.

**Comment by icantthinkofanameritenow** [comment]
And it's a false equivalence. One chemist is all that's needed for Medbay to function, two is convenient in the right circumstances but far from compulsory. In practice, I find the second one is much more useful as another doctor, seeing that Chemists have full medbay access just like 90% of the other medbay staff.

Engineering on the other hand flat out needs multiple people to work at its best since when shit hits the fan, multiple places at once usually need to be fixed rather than just the one.

And if Cargo is so full of shitters as you claim.it is, why haven't you ahelped or filed any ban requests against them? If they aren't doing their job,  you can't just shrug your shoulders and give them the message that they can keep getting away with it. This is an administrative problem you want fixed, not a coding one.

**Comment by FudgePucker** [comment]
@icantthinkofanameritenow Because its easier to just add another large beaker to chemistry than it is to expect the player base to not be shit.

**Comment by clusterfack** [comment]
Doesnt chem have a second large beaker in the AIO grinder

**Comment by 9600bauds** [comment]
third*

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker 
Because the easy way out will fix the massive underlying problems SO easily and won't send a message to the shitters that their shittiness is encouraged, right? 

It's not expecting the playerbase as a whole to not be shit, it's sending them a message that if they're going to be shit, then they'll have to suffer the consequences for it. You know, like what should have been happening from the very beginning. 

But what do I know? I'm not the one who's going to be receiving shitposts about "REEEEEEE BADMIN WANTS US TO DO OUR JOBS, DEADMIN HE" for hours on end.

**Comment by Intigracy** [comment]
Maybe if you're seeing everyone else as a problem then they aren't the
problem.

**Comment by icantthinkofanameritenow** [comment]
Then enlighten me and tell me what the problem is, because depending on your perspective the issue is either the obstinacy of Shitter Central (AKA: RnD and Cargo) in refusing to always be available when needed or the laziness of people who want everything in their workspace to be perfectly set up from the second the round begins.

**Comment by nuklearcellphoneg** [comment]
Chemistry has plenty of small beakers in the boxes for cryo, or for mixing things. If they want to improve that, they need to take it upon themselves. Yes, more large beakers at start would be desirable, but they don't need them.

**Pull request closed without merging**
