### PR TITLE
Goblin Fix

### PR DESCRIPTION
**Pull request by GermanSanta**
Allows the brain damage of the goblins to actually work.
Changes the old string code to a define code
melee_damage_type = "BRAIN" into melee_damage_type = BRAIN
This is a legacy fix/balance request as the original clown goblin also contained the string code
:cl:
 - tweak: Clown and Mime goblins now cause brain damage when they hit you.
 - bugfix: Fixed ancient bug where things that were supposed to cause brain damage (such as goblins and mind batterers) never actually caused brain damage

### CODE REVIEW

**Comment by ghost** [comment]
please learn to use git ignore

**Comment by Kurfursten** [comment]
Use a decriptive changelog. This is gibberish to non coders. No CL no merge.

**Comment by SonixApache** [comment]
The :CL: is for players. Describe what this actually means for the players.

Example:
```
:cl:
 - tweak: Clown goblins now cause brain damage when they hit you.
 - bugfix: Fixed ancient bug where things that were supposed to cause brain damage (such as clown goblins and mind batterers) never actually caused brain damage
```

**Comment by GermanSanta** [comment]
That's really all it does though. It fixes the old code so brain damage actually works.

**Comment by GermanSanta** [comment]
B3njIrdyQxalEdhWcKkYUQ

**Comment by Kurfursten** [comment]
This is a better CL, good on this end, now just needs time for votes to accumulate

**Review by Kurfursten — APPROVED** [review]

**Comment by DamianX** [comment]
terrible idea, never merge this

**Comment by SonixApache** [comment]
don't just straight up copy over my example goddamnit read nigga READ

**Comment by PrimeDSS13** [comment]
clown goblins and mime goblins shouldn't do brain damage at all in my opinion

**Comment by aceedex** [comment]
For how easy they are to make I don't think they should be able to if you have 11 or more

**Comment by DamianX** [comment]
dumb

**Pull request closed without merging**
