### PR TITLE
Glagow's Stage 3

### PR DESCRIPTION
**Pull request by falcon2346**
[tweak]
## What this does
Changes Glasgow's to a stage 3 symptom instead of stage 2 making it both much less likely to roll, and take longer to manifest.

## Why it's good
Glasgow's being the only stage 2 danger 4 symptom means that it was rolling near constantly. This prevents glasgow's from appearing 33% of the time a random disease appears

## Changelog
:cl:
 * tweak: Changes Glasgows from stage 2 to stage 3.

### CODE REVIEW

**Comment by jwhitak** [comment]
Looks good (code-wise). This should end the 33% for glasgow to be in your randomly picked diseases! No more diseases making you lethally drunk before you may even notice the other symptoms... Now it has a lower chance to roll, later on in the disease.

**Comment by DeityLink** [comment]
Finally, I won't have to explain why it happens so often again and again 😌

**Comment by KingofHONK** [comment]
Glasgows is guaranteed death with the liver damage, and the inevitable organ failure is either a clone or surgery, which is a time consuming treatment. Combine that with like 5++ people....yeah it's crippling. Good change.

**Comment by hacker-on-steroids** [comment]
i just realised the title says GLAGOW

**Pull request merged**
