### PR TITLE
Brings back old supermatter sprite

### LINKED ISSUE #2362: Switch Supermatter Bluespace expansion to the old sprites
People think they're supposed to jump on the bluespace the Supermatter creates.  Its retarded.

### PR DESCRIPTION
**Pull request by clusterfack**
THERES PROBABLY AN ISSUE ABOUT THIS SOMEWHERE
Fix #2362

### CODE REVIEW

**Comment by clusterfack** [comment]
It looks like this

**Comment by Probe1** [comment]
image

**Comment by clusterfack** [comment]
I only committed half

**Comment by Probe1** [comment]
I'm into this.  It suffers from tiling appearance but I'm into it.

**Comment by Imagebard** [comment]
As matter of fact.
#2362

**Comment by Probe1** [comment]
2362 doesnt seem so long ago

**Comment by Imagebard** [comment]
Thank you for replying to my 2 year old issue.

**Comment by Manaony** [comment]
Go for it.

**Comment by 9600bauds** [comment]
it's a little
tiley

**Comment by clusterfack** [comment]
Well sure it doesn't tesselate well, but I consider that better by virtue of the fact the current one tesselates only because **its currently just a solid color with no detail**.

**Comment by gbasood** [comment]
It technically fits the color scheme of supermatter shards better.
The problem isn't so much that it doesn't tile well so much as it is that the borders of the tiles are incredibly obvious.
I would honestly prefer something 'noisier' that would tesselate better.

**Comment by DrCelt** [comment]
I preferred bluespace.

**Comment by clusterfack** [comment]
Nerds who put in code and don't fix their bugs don't get to have an opinion

**Comment by DrCelt** [comment]
I just fixed bugs!

**Comment by PJB3005** [comment]
Revert this.

**Pull request merged**
