### PR TITLE
Extremely important code refactor hotfix

### PR DESCRIPTION
**Pull request by ghost**
also check 'em

### CODE REVIEW

**Comment by clusterfack** [comment]
Jesus christ get a life

**Comment by ihadtoregisterforthis** [comment]
But what if someone ports something from this codebase and then everyone starts calling it VG, akin to TG?

**Comment by ghost** [comment]
This refactor is highly important to prevent the decline of this server.

**Comment by clusterfack** [comment]
They already all do, intentionally or no, because they think we're like TGstation

**Comment by 9600bauds** [comment]
Clusterfack let's stop pretending that anyone that codes for free for a 4chan server of an obscure autist game in a decade old atrocious anime game engine has a life

**Comment by Boxe** [comment]
this is legitimately autism

like no joke this is autism taking control

**Comment by 9600bauds** [comment]
Autism is a buzzword

**Comment by Boxe** [comment]
so is fun but we still use that :^)

**Comment by gbasood** [comment]
this is so fucking stupid

**Pull request merged**
