### PR TITLE
Chisel improvements for #6882

### PR DESCRIPTION
**Pull request by Probe1**
Resolves https://github.com/d3athrow/vgstation13/issues/6882 by adding a period and also adds some cancel buttons!  Hurrah for cancel!

### CODE REVIEW

**Comment by Probe1** [comment]
I'd like to add a selectable list as well but need to find appropriate code to sample and learn from.  I'm thinking crayons.

**Comment by Exxion** [comment]
Honestly, it would probably be better if it only opened one dialog box. You can add extra details in the first one. Unless it has some extra purpose I'm not aware of, which is possible.

**Comment by Probe1** [comment]
I'm having a hard time figuring out how to make it look nice without the second dialogue @Exxion .  The first one is the name, and the second one is the description.

**Comment by Probe1** [comment]
Well I'd like to make it a selectable list but after an hour of trying I can't figure it out.  Oh well.

**Comment by 9600bauds** [comment]
Everyone lend your energy to Probe!

**Comment by Probe1** [comment]
More like just tell me how to do it cause I'm drawing a blank.  I did meet the problems raised in the issue however.

**Comment by gbasood** [comment]
If you want to worry about punctuation, you could check if the inputted message contains a period, too.

If I input "A coder." I'd get two periods, that's just plain silly.

**Comment by 9600bauds** [comment]
Have you tried
var/what_the_guy_chose = input("Whatchu want man") as null|anything in list("option a", "option b", "etc")

**Comment by Probe1** [comment]
You're talking to me like I have an idea of what you're saying.  I tried a lot of things like that and it didn't work because I don't understand it.

**Comment by Probe1** [comment]
huzzah I got it working.

**Comment by Probe1** [comment]
``` DM
/obj/item/weapon/chisel/afterattack(atom/target, mob/user as mob, proximity)
    if(!proximity) return
    if(istype(target,/turf/simulated/wall))
        var/turf/simulated/wall/W = target
        W.add_fingerprint(user)
        if(!W.engraving)
            var/engraving_name = sanitize(input(usr, "Depicted on the wall is an image of ...", "Basic engraving", null) as null | text)
            if(!engraving_name) return

            var/engraving = sanitize(input(usr, "Depicted on the wall is an image of [engraving_name]. ...","Details of the engraving", null) as null | text)
            if(!engraving) return

            var/engravingdesign = input("Your engraving", null)as null|anything in list("Amyjon"="amyjon", "Face"="face", "Matt wuz here"="matt", "Vive la Revolution"="revolution", "Engi"="engie", "Guy"="guy", "End is nigh"= "end", "Dorf"="dwarf", "uboa"="uboa") 
            if(!engravingdesign) return

            user.visible_message("<span class='notice'>[user.name] starts engraving something on the [W.name].</span>", "<span class='notice'>You start engraving an image of [engraving_name] on the [W.name].</span>")
            if(do_after(user, target, 60))
                if( !istype(W, /turf/simulated/wall) || !user || !src || !W ) return
                if( W.rotting )
                    user.visible_message("<span class='warning'>The [W.name] crumbles under [user.name]'s touch!</span>", "<span class='warning'>The [W.name] crumbles under your touch!</span>")
                    W.dismantle_wall()
                    return

                var/quality = rand(1,10)
                if(blessed) quality = rand(8,10)
                switch(quality)
                    if(1 to 4)
                        W.engraving_quality = "an" //depicted on the wall is [quality] image of ...
                    if(5 to 7)
                        W.engraving_quality = "a finely-designed"
                    if(8 to 9)
                        W.engraving_quality = "an exceptionally designed"
                    if(10)
                        W.engraving_quality = "a <span class='notice'>masterfully designed</span>"
                        to_chat(user, "<span class='warning'>It's a masterpiece!</span>")

                engraving = {"Depicted on the wall is [W.engraving_quality] image of [engraving_name][(use_name ? " by [user.real_name]" : "")]. [engraving]."}


                var/icon/engraving_overlay = new/icon('icons/effects/crayondecal.dmi',"[engravingdesign]",2.1)

                W.overlays += engraving_overlay
                W.engraving = engraving
                user.visible_message("<span class='notice'>[user.name] finishes engraving [W.engraving_quality] image of [engraving_name].</span>", "<span class='notice'>You finish engraving on the [W.name].</span>")
```

I added

``` DM
var/engravingdesign = input("Your engraving", null)as null|anything in list("Amyjon"="amyjon", "Face"="face", "Matt wuz here"="matt", "Vive la Revolution"="revolution", "Engi"="engie", "Guy"="guy", "End is nigh"= "end", "Dorf"="dwarf", "uboa"="uboa") 
            if(!engravingdesign) return
```

and 

``` DM
var/icon/engraving_overlay = new/icon('icons/effects/crayondecal.dmi',"[engravingdesign]",2.1)
```

after removing 

``` DM
var/icon/overlay_type = pick("amyjon","face","matt","revolution","engie","guy","end","dwarf","uboa")
var/icon/engraving_overlay = new/icon('icons/effects/crayondecal.dmi',"[overlay_type]",2.1)
```

Only the overlay for the last thing on the list (uboa) shows an overlay.  They are all displayed on the list in game but only uboa produces an overlay.  The rest produce an engraving, but it is not visible.

**Comment by unid15** [comment]
``` DM
var/engravingdesign = input("Your engraving", null)as null|anything in list("Amyjon"="amyjon", "Face"="face", "Matt wuz here"="matt", "Vive la Revolution"="revolution", "Engi"="engie", "Guy"="guy", "End is nigh"= "end", "Dorf"="dwarf", "uboa"="uboa") 
            if(!engravingdesign) return
```

That input would return "Amyjon", "Face", "Matt wuz here", "Vive la revolution", "Engi", "Guy", "End is nigh", "Dorf", "uboa". Of these only "uboa" can be found in 'icons/effects/crayondecal.dmi', which is why other engravings aren't visible!

Try this instead:

``` DM
var/list/engravings = list("Amyjon"="amyjon", "Face"="face", "Matt wuz here"="matt", "Vive la Revolution"="revolution", "Engi"="engie", "Guy"="guy", "End is nigh"= "end", "Dorf"="dwarf", "uboa"="uboa") 

var/engravingdesign = input("Your engraving", null)as null|anything in engravings
if(!engravingdesign) return

var/engraving_icon_state = engravings[engravingdesign]

//Get icon
var/icon/engraving_overlay = new/icon('icons/effects/crayondecal.dmi',"[engraving_icon_state]",2.1)
```

**Comment by Probe1** [comment]
I got the idea from crayons.dm.  I guess it works differently there and I don't understand it.  I'll try your way now.

``` DM
var/list/graffitis = list(
                    "Random"="graffiti",
                    "Cancel"="cancel",
                    "Left arrow"="left",
                    "Right arrow"="right",
                    "Up arrow"="up",
```

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/objects/items/crayons.dm#L81

**Comment by unid15** [comment]
> I don't understand it

Here's how list associations work: if you have a list L

``` DM
var/list/L = list("Object 1" = "baba",
"Object 2" = "bebe",
"Object 3" = "adolf")
```

and you do

``` DM
var/choice = input("Select something you like", null) as null|anything in L
```

then the choice variable will be either "Object 1", "Object 2", "Object 3" or null. If you want to get "baba", "bebe" and "adolf" from that then you have to do it like this

``` DM
world << L[choice]
```

L["Object 1"] returns "baba", L["Object 2"] returns "bebe" and L["Object 3"] returns "adolf"

**Comment by Probe1** [comment]
So, yesterday when I used

``` DM
var/mob/winner = input("Who's a winner?", "Achievement Winner", null) as null|anything in player_list
    if(!winner) return
```

`anything in player_list` was an associative list?

**Comment by unid15** [comment]
Not sure what you mean by that but 

``` DM
var/list/L = list("Object 1" = "baba",
"Object 2" = "bebe",
"Object 3" = "adolf")
```

is pretty much the same as

``` DM
var/list/L = list("Object 1", "Object 2", "Object 3")
```

The only difference is that with the first one you can do L["Object 1"] to get "baba", L["Object 2"] to get "bebe" etc.

And **as null|anything** means that input can return any value, or null (if the cancel button is hit). If you had

``` DM
var/list/random_stuff = list(new /mob/donk, "chocolate", 42, 57, new /mob/donk/agressive, "santa claus is coming to town")

var/example_A = input("Select something", "A") as null|anything in random_stuff
var/example_B = input("Select something", "B") as null|mob in random_stuff
var/example_C = input("Select something", "C") as num in random_stuff
var/example_D = input("Select something", "D") as null|text in random_stuff
```

example_A would allow you to select anything from the list ("Donk Dude", "chocolate", 42, 57, "Evil Donk", "santa claus is coming to town") + cancel button
example_B would allow you to select mobs from the list ("Donk Dude", "Evil Donk") + cancel button
example_C would allow you to select numbers from the list (42, 57) but NO cancel button
example_D would allow you to select text from the list ("chocolate", "santa claus is coming to town") + cancel button

and iirc _input("Select something", "E") as mob|text in random_stuff_ would allow you to select both mobs and text

**Comment by Probe1** [comment]
oh good instead of removing the changelog it removed the code.

**Comment by Probe1** [comment]
I have no idea how to rebase to resolve conflicts and can't even find what I'm conflicting.

**Comment by unid15** [comment]
git pull --rebase upstream Bleeding-Edge

then do "git status" and the red files at the end are the ones that have conflicts

these files will have something like this

``` DM
>>>>>>HEAD
Bleeding-Edge part of the code
=========
your part of the code
<<<<<<<<commit name
```

after resolving do "git add /code/game/file_i_just_fixed.dm"

after resolving everything do "git rebase --continue"

**Comment by Probe1** [comment]
The best way to start your day is with a mountain of frustration.

@unid15 thank you again for all the help.  I couldn't have done it without you.

**Comment by Probe1** [comment]
Tested, works, not touching it again unless someone finds anything wrong.  Still can't believe I somehow got conflicts on my changelog from yesterday that was already merged.

**Pull request merged**
