### PR TITLE
Fixed OOC color for dark theme

### LINKED ISSUE #32302: dark mode text
(WEB REPORT BY: uchla REMOTE: 206.221.180.138:7777)
# Revision
f4f39393aaf5bdfecb3b12b8ccefa69c4c8e3300

# Description
OOC text for non admins is too dark on dark mode making it hard to read
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by DamianX**
I've restored the previous glorious yellow OOC text for the dark theme.

Fixes #32302

### CODE REVIEW

**Comment by DamianX** [comment]
Obsoletes #32305

**Comment by Eneocho** [comment]
Dangerously based.

**Comment by adacovsk** [comment]
madman

**Comment by DamianX** [comment]
Haven't quite figured out what I did earlier, but whatever. Now adminbussed OOC colors are seen by dark theme users as well.

**Comment by angryturnip** [comment]
Thank god. The dark blue is borderline unreadable on my monitor

**Comment by Eneocho** [comment]
speedmerge now

**Comment by pedr69** [comment]
LOOC and OOC are the exact same color now
good job c*ders

**Comment by pedr69** [comment]
on the non experimental, default experience, normal mode, of course.
i don't know what the dark mode fixes are because i don't use dark mode but please stop breaking shit

**Comment by Eneocho** [comment]
> LOOC and OOC are the exact same color now good job c*ders

That's how it worked on darkmode and what god intended.

**Comment by pedr69** [comment]
>that's how it worked on darkmode

and you niggers broke the light mode OOC and LOOC colors, they're identical now
i'll restate, by fixing your gay ass experimental shit, you made the default chat experience worse.
i wouldn't give a shit if it didn't mess with light mode but it does

**Comment by Eneocho** [comment]
I actually dislike the change (and its eventual fix) because it now forces you to see the snowflake OOC colours for the admins even on darkmode.

**Pull request merged**
