### PR TITLE
Mouse hat

### PR DESCRIPTION
**Pull request by jknpj**
micehat

Also fixes mobs inside mob holders surviving supermatter_act.

:cl:
 * rscadd: You can now put mice on your head.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I wonder how long until putting a mouse on your head causes small amounts of brain damage 🤔

**Comment by FudgePucker** [comment]
Let player controlled mice be able to control players.

**Comment by ghost** [comment]
Will they be able to get down themselves, or are we dooming mice to starve to death on our heads as some sort of sick trophy?  Why do we even still have mice nutrition if the wire chewing and sabotage was never even put in?

**Comment by Pathid** [comment]
Fairly certain any living mob can resist out of an inventory. And if it works like nymphs, attempting to move would free you anyway.

**Comment by jknpj** [comment]
Yes, moving breaks the mob holder just like with nymphs

**Comment by unid15** [comment]
[lol nice](https://pp.userapi.com/c841522/v841522447/5925b/LOmA2eNeFzg.jpg)

**Pull request merged**
