### PR TITLE
Revert "Optimizes some movement code"

### PR DESCRIPTION
**Pull request by Exxion**
Reverts vgstation-coders/vgstation13#32332

April Fools is over

### CODE REVIEW

**Comment by Jack7D1** [comment]
You know, maybe diagonal movement isn't all that bad..

**Comment by Eneocho** [comment]
I like the diagonal movement now, keep it.

**Comment by ghost** [comment]
As the author of the April Fools' PR I say it should be removed and then be subject to a server poll since it's a very controversial feature.

**Comment by Eneocho** [comment]
Keep it and poll if we should remove it instead of removing it and poll if we should re-add it.
I'm all for it becoming part of movementcode, it's ROBUST and fun(ny).

**Comment by Exxion** [comment]
We've been over this before. The April Fools PR gets reverted, and a new PR can be opened if people want the feature to stay.

**Pull request merged**
