### PR TITLE
Add a mouth hole to the Balaclava

### PR DESCRIPTION
**Pull request by ghost**
Holy shit I can't spell this fucking word
- Add a mouth hole to the Balaclava, shows on mob sprite and item sprite

I'm aware it looks a bit wonky by itself, but it looks perfectly fine on a mob. We just happen to have a one pixel nose. Why the short face ?

bacalava_front

bacalava_side

bacalava_item

cheeki_breeki

### CODE REVIEW

**Comment by DrCelt** [comment]
Beautiful.

**Comment by smet19** [comment]
It would be better if you add old balaclava as another item

**Comment by dylanstrategie** [comment]
I don't see how I could have both items exist, is there even an official term for balaclavas with and without mouth holes ?

**Comment by smet19** [comment]
3 hole and 1 hole balaclava

**Pull request merged**
