### PR TITLE
Railing fixes

### LINKED ISSUE #32777: Railings Not Targeted For Smashing
Zombies with environmental smash flags who will smash girders and such won't smash railings

@kane-f

### LINKED ISSUE #32925: Environment Smashers Need to Interact With Rails
Pretty awkward seeing things that can even smash through walls getting stopped because someone built some railings - worse because players can hop over them.

@kane-f

### LINKED ISSUE #34600: Railings dont hold simple mobs
(WEB REPORT BY: calzilla1 REMOTE: 206.221.180.138:7777)
# Revision
35673e3083f35c5db7d06548612a5dfbb776c9ab

# Description
Made some railings to hold cows and chickens but they just phazed through it
# Steps to Reproduce
>Build railings
>Put cow in fenced off area
>They walk right past it
# What you Expected
For a nice petting zoo
# What Actually Happened
Animal escape

### LINKED ISSUE #34782: Couche sprites are layered above railings
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
8078c3eb86f3ead0ad27b4cf389352c38e991149

# Description
Couch segment sprites are layered over railing sprites
# Steps to Reproduce
Place a couch, place a railing, spin the couch to check directionals
# What you Expected
Railing visible
# What Actually Happened
Couch visible

### LINKED ISSUE #34853: Couches and chairs overlay on top of railings
(WEB REPORT BY: bungofungo REMOTE: 206.221.180.138:7777)
# Revision
3fd5a26381828cb0cef6639c0afe206d45761173

# Description
Couches and chairs appear over railing sprites at certain angles, particularly facing downwards, 6 o clock, south, however you wanna label it.
# Steps to Reproduce
Build railing for decoration, build couch or chair on same tile
# What you Expected
Railing takes priority and covers furniture like it does for machines 
# What Actually Happened
Ugly looking situation where a chair or couch is phasing through a railing

### LINKED ISSUE #34911: make so animals cant get past raillings
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
9e32cd263de90541cf23651273be707f8492d280

# Description
railings are cool feature and you can make chicken coups and stuff but the animals dont give a fuck and just walk through them. if humans have to drag click to go over a railing then animals shouldnt be able to just warp through# Steps to Reproduce

# What you Expected

# What Actually Happened

### LINKED ISSUE #35044: Fix railing furniture clipping
#### Description of issue
Furniture clipping through raillings depending on direction, typically back and right side of couchs and sofas. Forward facing furniture doesn't clip through.

depiction below

railings

### LINKED ISSUE #36265: chair sprite incorrectly showing above railing sprite
(WEB REPORT BY: angryturnip REMOTE: 172.93.101.77:7777)
# Revision
c9c36c71b8c0627a90cd5ba3a3e5e341e1caa774

# Description
see pic: https://files.catbox.moe/425txr.PNG
# Steps to Reproduce
make a comfy chair and wooden railing on the same tile
# What you Expected
the railing to be in front of the chair
# What Actually Happened
see pic above

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[bugfix][tweak]

## What this does
Closes #32777.
Closes #32925.
Closes #34600.
Closes #34782.
Closes #34853.
Closes #34911.
Closes #35044.
Closes #36265.

## Why it's good
requested changes

## Changelog
:cl:
 * bugfix: Railings now layer over chairs and potted plants properly. Potted plants now get hidden by curtains properly too
 * bugfix: Hostile mobs that can smash railings are now able to do so, taking into account the amount of damage they can cause (so for example, a goliath would need 4 hits to tear down a normal railing)
 * tweak: Various things that are allowed to pass tables are now no longer able to pass railings too, with exceptions for biomass, powercreep vines, meteors, small camera TVs, medical records laptops, rechargers, grinders, chemical puffs, any effect that already passes through tables, vines, boomboxes, monkeys, MoMMIs, bees, crickets, mice, spiderbots, cockroaches, grinches, saucer drones, viscerators, parrots, snails, hookshots, blob spores, all projectiles and all holdable items.

### CODE REVIEW

**Comment by hacker-on-steroids** [comment]
> Hostile mobs that can smash railings are now able to do so

basically every hostile mob has the SMASH_LIGHT_STRUCTURES flag, which means railings are now fucking useless for containment

**Comment by SECBATON-GRIFFON** [comment]
> basically every hostile mob has the SMASH_LIGHT_STRUCTURES flag, which means railings are now fucking useless for containment

that's what railings were specified under when they were originally PR'd

**Comment by SECBATON-GRIFFON** [comment]
> basically every hostile mob has the SMASH_LIGHT_STRUCTURES flag, which means railings are now fucking useless for containment

railings were under this flag in the original code too

**Comment by hacker-on-steroids** [comment]
i'd use SMASHWALL instead - i think a railing is closer to a girder than a rack, toughness wise
also, i foresee people bugreporting "wtf why are these monsters escaping their cage???"

**Comment by SECBATON-GRIFFON** [comment]
> i'd use SMASHWALL instead - i think a railing is closer to a girder than a rack, toughness wise also, i foresee people bugreporting "wtf why are these monsters escaping their cage???"

fair point, but tables are light structures too, which has me torn on how to approach this. also personally i'd put railings around the same as windows

**Comment by Dacendeth** [comment]
Any chance I can get you to add the alt click rotate feature of windows to railings?

**Comment by SECBATON-GRIFFON** [comment]
> Any chance I can get you to add the alt click rotate feature of windows to railings?

already added in #36218

**Pull request merged**
