### PR TITLE
Components! TGUI uplinks! Oh god!

### PR DESCRIPTION
**Pull request by DamianX**
- Completely removed all "hidden uplink" objects, replaced them with:
- Component datums! As seen on ~~TV~~ TG, but I completely disallow duplicate/inheriting components (and currently transfer between owners but that's WIP), which means 90% of the complexity is just not there. The whole thing is under 80 lines.

Practically, any item can now be an uplink. Admins can just give things the uplink component _and change a few vars_ and it works automagically.

image

Thanks again to stylemistake for the original UI.

:cl:
 * tweak: Syndicate uplinks have a new user interface.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Thank you for your service.

**Comment by gurfan** [comment]
finally

**Comment by jknpj** [comment]
Won't this kill traitors for loonix users?

**Comment by DamianX** [comment]
idk, test it?

**Comment by TGFH** [comment]
> 
> 
> Won't this kill traitors for loonix users?

Freetards owned.

**Comment by Exxion** [comment]
>Won't this kill traitors for loonix users?

Nano is broken on Linux but as far as I know TGUI works fine

**Comment by SonixApache** [comment]
blessed pizzaman

**Comment by jknpj** [comment]
fuck it, ship it.

**Pull request merged**
