### PR TITLE
Vampires are now universal receivers

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Less negativity, more positivity!

:cl:
 * rscadd: Vampires are now able to consume any type of blood through regular consumption or injection rather than just compatible blood types.

### CODE REVIEW

**Comment by Eneocho** [comment]
Couldn't this become a metacheck, cause their records say they are from one blood type, but they take any type (universal recipient blood types nonwithstanding).

**Comment by boy2mantwicethefam** [comment]
I'm pretty sure holy water is a more noticeable metacheck.

**Comment by content-to-remain-anonymous** [comment]
>imprison O- vampire
>pump random blood into him
>extract universal donor blood

sounds fun
you can already do this but it's abusing a bug

**Comment by Eneocho** [comment]
> >imprison O- vampire
> >pump random blood into him
> >extract universal donor blood

Someone post the vampire engine pic

**Pull request merged**
