### PR TITLE
Graffiti... but epic

### PR DESCRIPTION
**Pull request by ShiftyRail**
## What this does

image

You can graffitti with any crayon colour and any shape you want, on any floor. And I mean any. Go wild.
Only colour that will not be accessible is the #aaaaaa grey (as I need at least "one" colour to convert to transparent).
All other shades of grey will be accessible. 

For now, you can only shitpost with crayons, which limits somewhat your accessible colour palette. If the need arises, or if people enjoy it, you could in theory scribble with all available painting tools. You could also scribble on walls, if you want. All this isn't a code problem, but more of a "should we allow it" problem.

Regular graffiti is not going away, if that's something you are worried about.

## Why it's good

Epic art on the station, better possibilities to shitpost, overall, nice stuff to do. The colours do appear slightly muted on screen but that might just be because of the crayon colours themselves.

## Changelog
:cl:
 * rscadd: You can now use crayons to graffiti anything on the floor. Anything.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
epic

**Comment by Eneocho** [comment]
holy sovl... shifty... redeemed...

**Comment by Eneocho** [comment]
Did you check the rainbow crayon's (and the mime crayon) multi-colour painting? Do they work fine? Can you paint with any of the rainbow crayon available colours (sans #aaaaaa)?

**Comment by ShiftyRail** [comment]
Yes

**Comment by RealestEstate** [comment]
basedbasedbasedbasedbased

**Comment by Eneocho** [comment]
Since this makes actual graffiti, would you consider changing the chav disability so it makes it faster to paint? It already makes it faster to engrave walls with a chisel.

**Comment by ShiftyRail** [comment]
Speed doesn't really matter so it would just be a flavour effect, but yes - doable.

**Comment by Kurfursten** [comment]
confl

**Comment by ShiftyRail** [comment]
fixed

**Comment by Eneocho** [comment]
@ShiftyRail Can you implement it such that you can also floor graffiti with paint?

**Comment by Eneocho** [comment]
Noticed that this accidentally restores the actual vinemaking functionality of the clown's grape drank spray.

**Pull request merged**
