### PR TITLE
disabled cult

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * rscdel: disabled cult

### CODE REVIEW

**Comment by BomberBro** [comment]
Holy based

**Review by BomberBro — COMMENTED** [review]
This still doesn't prevent cult from spawning via the xenoarch pamphlet. It's a minuscule chance but are we really going to take the risk?

**Comment by robosperg** [comment]
replace it with oldcult, dont remove the gamemode from rotation entirely

**Comment by boy2mantwicethefam** [comment]
based but im downvoting on principle that it might actually go thru

**Comment by ghost** [comment]
thought this was about putting nar'sie in a wheelchair

**Comment by ShiftyRail** [comment]
Cult, in his 2.0 version, could still be re-implemented somewhat easily. Would probably need a bit of dusting off to actually work, though.

**Comment by Irradiation** [comment]
>Makes the PR
>Self-Upboats and Downboats

**Comment by DeityLink** [comment]
It's been 6 months now since I began a break from spess for my graduation year and very minimal changes have been done to cult by anyone since then. The last time I gave R0B0 a list of changes I thought would help but then he just vanished. If no one is gonna ass themselves to make it so that more players like Cult then do a proper server poll, as, to quote Kammer: 
image
If cult is to be disabled for the time being then so be it.

To publicly clarify some of my positions:
* Anyone is welcome to try and make changes to cult, no matter how some people try to meme it I'm not forbidding people to make changes, I'll still voice my concerns if I don't like the changes or the reasoning behind but if it can make the antag better for the players then so be it.
* I do not think that cult in its current form is perfect, very far from it, there are lots of issues, some of which that became apparent later than others. I don't think that I am a beacon of game design, I'm still learning with each game and feature I work on and I think everyone here can bring forth very good ideas that I might not consider (on that note, many of Cult 3.0's features, such as the tattoos, where ideas from the community)
* I DO want to take shots at fixing cult, I've got a good bunch of concepts I'd like to try, but I stand by my decision of not investing myself into spess until my studies are finally over (in June). Whether cult is still the same then, or has been disabled, or modified, I intend to work on it then. But until then if the mode is insupportable for the majority of players feel free to disable it for the time being.

>Cult, in his 2.0 version, could still be re-implemented somewhat easily. Would probably need a bit of dusting off to actually work, though.

It'd need a lot more than just dusting off... many of the things people don't like in Cult 3.0 (such as the TDM aspect) are exacerbated in "Cult 2.0"

**Comment by KingofHONK** [comment]
Cant wait till wiz is gone next too! Love it!

**Comment by aceedex** [comment]
No tators
Box only
Final destination

**Comment by ShiftyRail** [comment]
>It'd need a lot more than just dusting off... many of the things people don't like in Cult 3.0 (such as the TDM aspect) are exacerbated in "Cult 2.0"

That's not true. I would say in no uncertain terms that cult 3 is badly designed *from the top* and for three reasons

1. Unfair (when cult 2 had just a few bad elements, cult 3 is rifle with them)
2. Themeless (cult 3 is the mode that doesn't know what it wants to be, it's both murderbone and ultra stealth ; cult 2 had both more freedom in how it played out AND you knew more or less what its theme was)
3. Foreign to the game (extremely linear mission-based mode that more or less plays like a coop game where the other's side fun is treated as negligeble quantity at best, in a game based on interaction and reciprocity ; cult 2 had, at least, some non-linearity with deconverts, no bloodstones, no acts, and other stuff)

I mean no offence to you or anyone but Cult 3 misses its target by a long shot and fosters one and only one way to play the game, and a terrible one

For more details, read https://gist.github.com/ShiftyRail/4e701cc6a8f94f1270d40fded70a0999 (didn't write part 2 or 3 yet but there's already SOME content to sort through)

>Anyone is welcome to try and make changes to cult, no matter how some people try to meme it I'm not forbidding people to make changes, I'll still voice my concerns if I don't like the changes or the reasoning behind but if it can make the antag better for the players then so be it.

You're not forbidding people, that's granted, but we both know that the author of the PR matters as much, if not more, than its content

**Comment by Exxion** [comment]
Cult 3 has a lot of good, but it's buried by a lot of bad
I think we could remove the bad and leave the good for a good Cult 3.5 without having to go all the way to 4

**Comment by bathosbathtime** [comment]
Who exactly is going to remove the bad?
Are we going to suffer cult while we wait for this fix or are we going to shelf cult until it is fixed?

**Comment by Exxion** [comment]
1. Probably nobody lol
2. Honestly I would have said shelve it, but it seems others disagree

**Comment by DeityLink** [comment]
1. This pretty much. No one did for 6 months.
2. Serve Vote dangit. I think it be disrespectful to disregard the opinion of those who actually enjoy the antag despite its flaws (and who keep pinging me whenever PRs like this one are made)

**Comment by bathosbathtime** [comment]
There is a server vote up, but this PR was closed with a few hours.
https://ss13.moe/index.php/poll/201

**Comment by Kammerjunk** [comment]
I don't like how formulaic it is - you either do nothing at all or you actively help the cult, nothing fun and different is allowed because you can't fuck over other cultists
I don't like antag checks because I think they're antithetical to how gamemodes (usually) function in spess
I don't like how when it rolls cult, it's always cult because even if you kill them all, you don't know that you've killed them all and you can't stop being hitlers because if you do, the round just ends an hour later because the cultists have been quietly cult-jobbing away
I don't like boxing

**Comment by ShiftyRail** [comment]
>Cult 3 has a lot of good

Debatable, it definitely has a good UI, neat looking spirites, nice spells, and no research is a good thing, but those don't make a gamemode good or bad, the logic behind those spells and how the *players* use them do

@DeityLink I made a gist of what I thought was badly designed about cult, you can read it if you like
It's long and has big words but there's no insults, and I tried to be constructive

**Comment by ghost** [comment]
Why are we trying to remove functional gamemodes from the codebase ?

Changeling was one thing, and it's still not back in any capacity. If we remove Cult it's pretty much a permanent removal because between SS14 and other coders not being arsed anymore it'll never be reworked

**Comment by DeityLink** [comment]
@ShiftyRail I already saw it a few days ago. I agree on a few points, disagree on others. Either way it's not my problem for a few more months.

**Comment by tuypo1** [comment]
Cult is fun and the tedium of recall spam was already fixed by giving them a way to track their target

**Comment by Kammerjunk** [comment]
>between SS14 and other coders not being arsed anymore it'll never be reworked

yes dylan that's exactly the point

**Pull request closed without merging**
