### PR TITLE
Hydroponics Mutations

### LINKED ISSUE #28624: Feature Request: A way to remove specific chems from a plant's phytochemistry via either a tool or xenobotany machine.
I play botany a lot, and it's always a kick in the nuts to see a great plant that I can't effectively mass use because it has a chem that doesn't help, like the solanine (toxin) in ambrosia vulgaris or the cyticine (synaptizine) in ambrosia deus, both of which make blunts pointless, since smoking a normal blunt makes you somewhat poisoned while a godblunt can kill you (1u cyticine equals about 60 toxdamage and since a godblunt, regardless of potency, has more than 1u, smoking a godblunt is a death sentence.)

Other times, when making materials-fruit (like glowberries for uranium) the presence of nutriment is a problem, since it always outnumbers the material, making any grinding woefully slow since you have to remove the nutriment every time to keep going.
Many times you find the ideal exotic seed, only to find out it not only makes the chems you wanted but also 3 different poisons.

You can ADD chems to a plant via splicing, but there's no way to remove specific chems from it.
Please add a way to remove specific chems from a plant's phytochemistry.
[featurerequest] [qol]

### PR DESCRIPTION
**Pull request by adacovsk**
[system]

The mutations code for hydroponics is awful to read and hopefully this brings about more possibilities. After talking with a couple veteran botanists, I noticed that they used splicing/purging to accomplish most of what they wanted to achieve, avoiding mutations, mainly because of the low odds of getting a mutation that they wanted.

I remade the PR because I messed up the commits, previously #32730

## What this does
- Refactor and redo the whole mutation system
- Rather than mutagen and radium causing all mutations, I broke it up such that:
   - Mutagen affects phytochemistry genes, put teleporting into xenoecology
   - Radium affects morphology genes
   - Uranium affects bioluminescence genes
   - Bicardines affects ecology genes
   - Kelotanes affects ecophysiology genes
   - Hyperzines affects metabolism genes. Metabolism now contains `fluid_consumption` and `nutrient_consumption`
   - Creatine affects development genes
   - Dexalins (Thymol) affects xenoecology. I'll put the very esoteric traits under here, like consume/exude gases and teleporting.

- Removes `custom_plant_metabolism`, `severity`, `yield_mod` and `mutation_mod`: these made barely any impact when used, and were rarely used, and convoluted.
- Rebalanced some toxins in on_plant_life() for some chems
- `parasite` combined with `carnivorous` now known has `voracious` to reduce the number of traits... Level 1 voracious results in the plant eating both weeds and pests. Level 2 `voracious` is HCARN
- Left4Zed actually does something now (1% chance to proc any mutation each tick currently)
- Metabolism no longer exude/consume gases
- Morphology mutations can affect appearance
- Modifies creatine recipe so untable mutagen can count as a reagent in recipe so botanists can produce it.
 - Creatine can be made with Poppies, Ambrosia, glowshrooms, regular and death nettles, but procs more often to compensate
- Somatray affects phytochemistry and development only. This may change. WIP
- fixes a broken hematophage
 
## Why it's good
- This should allow botanists more possibilities with their plants, and hopefully more possibilities for coders in the future as a big limiting factor was usability of the old code
- Mutating phytochemistry has a chance to remove a chemical. Closes #28624. While it is a roundabout way to eliminate chemicals, I don't see an easier way to do it until I modify seed machines (which I'm not doing for this PR).

## Changelog

:cl:
 * tweak: Reworked hydroponics mutations, see PR #32851

### CODE REVIEW

**Comment by adacovsk** [comment]
@eneocho @jwhitak @saul_myers it's on the test server now

**Comment by Eneocho** [comment]
* The seed extractor's tag for the voracious gene is still CARN, instead of VORA or similar.
* Voracious directly causes HCARN, perhaps change HCARN's name?
* Genegroup name is Xenoecology instead of Xenophysiology.
* Thymol is almost impossible to find without very good luck with seed gambling or a willing benoarch, both of which not very common, this will cause a dependence on chemistry instead of the self-sufficiency the untable mutagen and creatine changes implied. 
* Xenoecology (should be xenophysiology) splicing/purging seems to work fine.
* Microdosing (1u at a time) with mutagen or radium doesn't do shit.
* No indication for species change mutations (tomato to blue tomato in this case), it just transformed without warning. Add a notice that tells you when the mutagenics, species-change or not, have run out on the tray please. We used the "The plant shudders/droops/etc." notification as indication that the dose was fully consumed and a new one was needed. Due to development/phytochemistry mutations not happening that often this notification is no longer useful. Please add a notification that indicates this or make mutations guaranteed.
* PLEASE make mutations guaranteed on each dose instead of a chance per dose. As it is currently, microdosing (a main botany mechanic) doesn't do shit. This would also solve the aforementioned no notification issue.
* I can't make any plant species reliably, even after pouring 20u radium THEN 20u mutagen on the same orange plant, no mutation proc'd at all, not species (to silicate citrus) nor dev/phyto.

**Comment by Eneocho** [comment]
image
These are the results of adding 20u of the mentioned chem to a baseline seed.

**Comment by Eneocho** [comment]
All in all, it's currently a no from me. Mutations on a chance instead of guaranteed per dose is a no go, I can't do shit.

**Comment by adacovsk** [comment]
> All in all, it's currently a no from me. Mutations on a chance instead of guaranteed per dose is a no go, I can't do shit.

- mutations on chance is how it works currently
- I tried adjusting it so that it procs at about the same time it procs for current mutations
- In my PR, 5u is necessary for each proc: do you really want a 30u bottle procing 30 times in a few seconds? I can switch it to 1u but I'll have to lower the probabilities most likely for consistency. Keep this in mind: I've removed `mutation_level` which used to convert radium and mutagen via `hydroponics/process()` then `on_plant_life()` then on the next `hydroponics/process()` it would consume the `mutation_level` to trigger `mutate()`. This takes time, which is why I have to use probabilities to slow it down to make it a little more consistent, time wise

>No indication for species change mutations (tomato to blue tomato in this case), it just transformed without warning. Add a notice that tells you when the mutagenics, species-change or not, have run out on the tray please. We used the "The plant shudders/droops/etc." notification as indication that the dose was fully consumed and a new one was needed. Due to development/phytochemistry mutations not happening that often this notification is no longer useful. Please add a notification that indicates this or make mutations guaranteed.

This is all flat out wrong... It does provide feedback when it transforms into another species, I didn't even touch that proc. It's just because you're trying to use 1u

Anyway, I'm trying to balance it so it works for you. No need to get antsy about it, I can switch it back to 1u, just need to make some updates

**Comment by adacovsk** [comment]
@Eneocho updated it with your changes. Just be aware that you can dump a whole bottle into a tray, and it'll slowly process it using 1u at a time

**Comment by adacovsk** [comment]
test server isn't updating, I'll close and open again

**Pull request closed without merging**
