### PR TITLE
RCD window construction/deconstruction

### PR DESCRIPTION
**Pull request by ghost**
[tested][content][qol]
output
Does not allow deconstruction of plasma windows, 2 matter units per window (subject to change)
Applies for mech/borg ones too.
:cl:
 * rscadd: All RCDs are now equipped with modules to transform compressed matter into windows and deconstruct them, unless made of plasma.

### CODE REVIEW

**Comment by Eneocho** [comment]
Why not plasmawindows? It could make plasmawindows at 5 matter instead of 2.

**Comment by Eneocho** [comment]
Also, can you add a single window version so you can build the window without the grille?

**Comment by ghost** [comment]
> Why not plasmawindows? It could make plasmawindows at 5 matter instead of 2.

It doesn't make rwalls either, it's thematic

**Comment by GreatBigFailure** [comment]
Excellent, RCD buffs are much needed and good for both gimmicks and station repairs.

**Pull request merged**
