### PR TITLE
Doing stuff to Deff

### LINKED ISSUE #7446: Metaclub has no Vox Station
Played Vox Raiders on Metaclub. We tried to go to the Vox trading station or whatever. It was just empty space.

Possibly extends to Deff and Taxi?

### LINKED ISSUE #7535: [Deff] No Autolathe in Research & Development
(WEB REPORT BY: myroc REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f0d192e03f12243b1d70fcdbb102bbc87567a19d 
> 
> General description of the issue
> Deff RnD does not have an autolathe.
> 
> What you expected to happen
> An autolathe in RnD.
> 
> What actually happened
> There was no autolathe in RnD.
> 
> Steps to reproduce if possible
> Wait 50 rounds for deff to win the vote. Enter RnD.

### LINKED ISSUE #7950: Hallway is now space [deff]
fuck
@Duny

### LINKED ISSUE #8337: Defficiency Has No Spawn Area for ERT and Deathsquad
The admins were completely unable to send either of them.

Thanks @Duny.

### LINKED ISSUE #8374: Lacking some xenobotany tools at Deff's science outpost
_Even with doubts where and what is the problem, I'm posting this so you higher-beings can simply teleport there and check_

One of the science outposts has a xenobotany room lacking tools, with at least no plant analyzer (last time I had to pray for one), no gene modification machines and maybe even none of those closed-gas hydroponics (for plants with special environment). I'm not really sure if this is the only thing lacking, or if it was really lacking. About the map, I noticed Box shares his outpost with another station, so the one I'm refering to is the one who doesn't share with Box (pretty sure is Deff).

Edit: @Skullyton confirmed it's Deff's

### PR DESCRIPTION
**Pull request by ghost**
IT'S DONE, MERGE IT

Got tired of waiting for duny to fix his map.

Sorts out the abomination that was the piping "leading" to xenobiology, by leading, I mean they just weren't going there in the first place (pipe leading to nothing in the rwall, and a manifold a bit further down pointing towards an empty rwall). Also added some more vents because of the size of the room, and also another vent to the research corridor.

Ventilation is important

Expands on the xenobotany area on the research station, so it's usable for botanical research rather than a broom cupboard

New xenobotany

Fixes #8374

Added an autolathe to R&D. Have a paddy about this one ye great jessie about "Muh casuals"!

Betcha didn't think I'd do it

Fixes #7535

Fixes #7950 by adding the proper area to that hole

DAY 2:

Copypasted meta's centcomm onto deff, the shuttles should all be compatible still, didn't find anything through testing. ERT shuttle needs a bit of tweaking as it still uses the holodeck-esque way of transferring between areas, at least the areas to do so are still there at least.

Deathsquad shuttle leaves a lot to be desired, and I'm gonna have to do some research if we want the vox skipjack and salvage shuttles to be moved in.

Also removed stools from the brig, as they were all converted to weapons a while back whereas before they were just seats.

Fixes #8337 

DAY 3:

Moved the mancrowave in medical from 2 rooms away from cryo to 6 paces. Also removed that weird security-only room from medbay that was never used and tossed in a crew monitoring computer on front desk. Fixed a few misplaced areas in the SME room, and sorted the centcom ferry out, should be good to work.

goodbye easy pepperspray

Never use nudge, it changes step rather than pixel.

Day 4 and a bit:

Added the Vox skipjack, the salvage shuttle, and fixed escape pods. Also adds a Vox outpost on a neighbouring asteroid to the mining roid.

This fixes #7446 #5434 #8228

### CODE REVIEW

**Comment by PJB3005** [comment]
:-1: on autolathe because hug box :+1: on autolathe because people will play this amazing map more.

**Comment by gbasood** [comment]
I've never really thought that having the Protolathe not make everything an Autolathe does was anything but silly as fuck so :+1:

**Comment by CptWad** [comment]
OK
But @Duny- will disapprove

**Comment by Duny-** [comment]
So sorry for having a job casual child. Leave the chickens to me I'm just waiting to see if I'm going to be homeless or well paid the next 6 months after this one before I start fixing shit for free again.
I'm okay with this PR as it is. Except for the vent above a pipe in xenobotany, haram as fuck.

**Comment by SonixApache** [comment]
replace protolathe with protolathe board like on taxi

**Comment by ihadtoregisterforthis** [comment]
Three rogue tiles, you could fix them while you are close.
stanford drydock 54 2016-02-16 214147

Don't pay attention to the indoors singulo

**Comment by ghost** [comment]
Well, found the problem with those tiles, 2 of them are AME, and one of them is engine, so they won't respond to icon_state alarm for that area

nice areas

**Comment by CptWad** [comment]
shit like that is usually accidents when fiddiling with areas and accidently clicking the map instead of the scrolly bars

**Comment by ghost** [comment]
Okay, final day I plan to handle this. 

Escape pods, vox skipjack with shuttle docking placements, salvage shuttle with shuttle docking placements are all that I'm aware need doing

**Comment by ghost** [comment]
Fukken changelogs, how do they work?

**Comment by ghost** [comment]
Oh, they don't like colon symbols, good to know

**Comment by ghost** [comment]
As far as I'm concerned, I'm done. #8342 Seems to be more of a problem with the goonecode containment area so might not be completely confined to defficiency.

**Comment by ihadtoregisterforthis** [comment]
derp office omicron 2016-01-12 222453
How does this even happen

**Comment by ghost** [comment]
@ihadtoregisterforthis Wait what.

How'd that get there? That's something from the asteroid

**Comment by ghost** [comment]
Sink in the xenobotany 
Hoe and hatchet in the xenobotany crate for weeds and harvesting ligneous plants
Heater and rpd in toxins

edit: two more monkeycube boxes for xenobio to match box. It helps you multi-pen your first grey splits to help you get purples faster for a more sustainable run.

**Comment by ghost** [comment]
Added a sink and hatchet to xenobotany, the hoe was already there.

Heater is "in", but it's a bit of a squeeze, RPD is also in.

Also fixed the like 6 rogue plasma-filled tiles that seemed to have manifested.

@9600bauds Can I get a Needs Final Decision tag for this now?

**Pull request merged**
