### PR TITLE
Packed Lightswitch Edition

### PR DESCRIPTION
**Pull request by MusgardTiger**
Adds eight light switches to following departments/rooms: EVA, Janitoral Closet, Podbay, Auxillary Storage, Cargo Office, HoP Office, Bar, Kitchen, Brig.

Also adds a soap in janitors closet and chef's crate.

This is my first actual pull request so I probably fucked something up, I followed the guides but I suffer from tiny brain syndrome. Also not sure if mapclean did anything for me, this pull request looks big wew.

### CODE REVIEW

**Comment by DamianX** [comment]
You used `step_x`
don't use `step_x`
use `pixel_x` instead

**Comment by MusgardTiger** [comment]
i will try to sort this out tomorrow

**Comment by MusgardTiger** [comment]
imma work on this again unless somebody adds those lightswitches and soaps or the impending changes are done with. 

Hopefully with less conflicts and 10 hours of braindamage 😀

**Comment by ShiftyRail** [comment]
@MusgardTiger You don't need to close it like that - just open PackedStation.dmm in notepad++ and search & replace `step_x` => `pixel_x` (same for y)

Nevermind it's a conflict

**Pull request closed without merging**
