### PR TITLE
Noir is now guaranteed to activate

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
But it's nowhere, noired, noired, static on my blindside
:cl:
 * tweak: Noir now always activates on the first DNA change instead of the default 45% chance.

### CODE REVIEW

**Comment by KingofHONK** [comment]
Based

**Comment by Probe1** [comment]
Why should we add this change?

**Comment by SGuivenne** [comment]
> Why should we add this change?

IIRC its because of issues with detectives.

**Comment by Kurfursten** [comment]
Conflicts

**Pull request merged**
