### PR TITLE
Reduce DNA modifier injector creation cooldown by half

### PR DESCRIPTION
**Pull request by brndd**
[gameplay]

Powercreep etc

It takes fucking ages (30 seconds, less if the machine is upgraded which it will virtually never be) to produce gene injectors in the genetics DNA modifier machines. To get around this, experienced players juggle both machines so they spend less time waiting, among other advanced tactics.

This PR halves that cooldown time to 15 seconds, which should hopefully make juggling two machines at once less necessary. The juggling method is also probably going to start hitting diminishing returns around here (there are only so many injectors you need, after all), so I don't think it's going to make two machines overpowered by making genetics four times as fast as one machine currently is or something. And if it does, I'm just going to argue that it's a \~high-skillcap\~ mechanic that \~rewards highly skilled play\~.

:cl:
 * tweak: Genetics machines now refill their injector banks twice as fast.

### CODE REVIEW

**Comment by ghost** [comment]
I support the idea of reducing the base time but half might be a bit much. It's fairly common to spend more time on getting blocks above the activation threshold than on waiting for the injector cooldown, even when taking advantage of mutagen etc.

Making the cooldown shorter is definitely worth a try just to see what happens. Maybe 20 seconds? As it is now you aren't going to get very far with genetics unless you have two players working on it for upwards of an hour, and rounds where genetics makes progress AND there's something to use powers on are exceedingly rare.

**Comment by boy2mantwicethefam** [comment]
I'm a genetics player and I like this powercreep

**Comment by ghost** [comment]
It should cost biomass and have no cooldown in the same way cloner has a biomass cost, so geneticists actually do their job and get biomass for cloner.

**Comment by Kurfursten** [comment]
Currently: 30 seconds per injector with all default parts, upgrades to 6 seconds with level 3 (**can get to 0 with level 4, but this is rare**). This PR: 15 seconds per injector, upgrades to 3 seconds with level 3

I don't really see why this is necessary. Timegating is part of the genetics balance. You've got science access and medbay is the most commonly upgraded department. C'mon.

**Comment by TurboGay** [comment]
> 
> 
> Currently: 30 seconds per injector with all default parts, upgrades to 6 seconds with level 3 (**can get to 0 with level 4, but this is rare**). This PR: 15 seconds per injector, upgrades to 3 seconds with level 3
> 
> I don't really see why this is necessary. Timegating is part of the genetics balance. You've got science access and medbay is the most commonly upgraded department. C'mon.

By the time science swings by to upgrade things and in the rare case that they even realize geneticists want upgrades, you should have all powers already so the only thing it would affect is distribution of powers.

**Comment by Kurfursten** [comment]
For the record, this PR and most of genetics in general is a mistake. So when people complain at me in 2 months for merging this it will be written down that THIS IS THE FUTURE YOU VOTED FOR WITH YOUR 👍

**Pull request merged**
