### PR TITLE
Wizard Spell: Fire Breath

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds a new spell which allows the user to breath fire, similar to jackal firebreathers.
It has a 10 second cooldown, and does not require robes to cast, like Fireball.
Unlike fireball, it costs half the standard price, and is aimable by default. It can be upgraded a maximum of eight times, four in cooldown reduction, and four in power. Upgrading the spell's power increases the size of the fire plume created.

Thanks to @Intigracy for the spell icon.

:cl:
 * rscadd: Added a new wizard spell which allows the wizard to breathe fire.

### CODE REVIEW

**Comment by Orangerush** [comment]
Add stretchy limbs so I can do full dhalsim

**Comment by ihadtoregisterforthis** [comment]
He already did with borers

**Comment by ghost** [comment]
>invocation = "SPY'SI MEAT'A'BAL"

Funny, It should have a chance to say "Y'GA FL'MA" T B H

**Comment by Megamaw** [comment]
is this going to heat up the area so much it kills the wizzyman too

problem i had with ring of fire.

**Comment by Shadowmech88** [comment]
The fire blast projectile does not alter the temperature of the local atmos. It is the same for the flamethrower.

**Pull request merged**
