### PR TITLE
Greys out internal organ items when they die

### PR DESCRIPTION
**Pull request by Pathid**
Since we have a HARDCORE organ death system and there's an age-old TODO for this.

dead organs

:cl:
* imageadd: Organ items now grey out when they die after being left out too long.
* bugfix: Fixed dead organs not getting fully reset when revived.

### CODE REVIEW

**Comment by strawberrytan** [comment]
Damn, I was thinking greys would be exuding all their organs violently when they die

**Comment by Irradiation** [comment]
Hopefully people will have a clear indication to rush a still-alive brain to a freezer now.

**Comment by Pathid** [comment]
That's the idea.

**Comment by Blithering** [comment]
the-transformers-the-movie1986-optimus-prime-group-shot

**Pull request merged**
