### PR TITLE
Ninjas smirk when they dodge attacks

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Requested by @jknpj 
Added procs for when someone dodges an attack

:cl:
 * tweak: The Spider Clan's ninjas are now more smug.
 * rscadd: Added a smirk emote.

### CODE REVIEW

**Comment by robintime** [comment]
FUCK SORRY

**Comment by boy2mantwicethefam** [comment]
lel

**Comment by jknpj** [comment]
image

**Comment by Eneocho** [comment]
NOTHIN' PERSONNEL KIDD

**Comment by RaccoonBro** [comment]
😏

**Comment by drawsstuff** [comment]
*teleports behind u

**Pull request merged**
