### PR TITLE
Tackling someone with an item out will also throw the item

### PR DESCRIPTION
**Pull request by ShiftyRail**
An idea I had. Should make it harder/funnier/whatever to get that sweet taser after you used your ranged disarm against that poor officer.

:cl:
- tweak: Tackling people will also throw away whatever they're holding.

### CODE REVIEW

**Comment by Blithering** [comment]
Does tackling have the same chance to set off guns old, defunct disarming did?

**Comment by Optimism333** [comment]
> Does tackling have the same chance to set off guns old, defunct disarming did?

I don't believe so, but it probably should.

**Comment by DeityLink** [comment]
Can't wait to tackle waiters holding piles of plates.

**Comment by Eneocho** [comment]
Can't wait for some weird interaction with a glued item eventually throwing the item but the guy can keep using it.

**Comment by Blithering** [comment]
>be regular law abiding spessman, enjoying a refreshing bottle of welder fuel
>see officer approaching, go to offer him my spare fuel bottle since he seems thirsty
>need somewhere to store my burning rags while I pass the bottle to him, put it in the end of the bottle for safekeeping
>officer tackles me
>fire everywhere
>BWOINK

Many such cases.

**Comment by DamianX** [comment]
Why is this code so bad?

**Comment by Kurfursten** [comment]
>It throws the items even if the tackle failed

IT WAS A MISTAKE
MISTAKE

**Pull request merged**
