### PR TITLE
[Box] Vox Outpost

### LINKED ISSUE #11158: Safe on Box vox outpost is not worth opening
Opening the safe on the vox outpost safe is a 30 minute affair.
First you need to trade for [spoiler]steal[/spoiler] a stethoscope from medbay.
Then you have to crack the safe, a very time intensive process.

Your reward is 10 diamonds, uranium, plasma, gold, etc.
This could easily be achieved by mining in half that time.
The vox safe needs a better reward in it. Perhaps some syndicate item like an emag, an agent ID, or a chameleon jumpsuit.

### LINKED ISSUE #11380: (Box) Make Outpost Great Again
This has been brought up by a few other people. Each of the Vox outposts kind of has a gimmick - Meta has all that research equipment, good gear, chemistry, genetics, surgery, virology. Deff has mining, a single chemistry dispenser, and other nice perks (wizard cards, crossbow, drink dispensers). The big plus that Box used to have before @dylanstrategie updated it was that it had a staggering 22 trays, which is more than the main station even has. Now it has a much smaller number.

Since Botany is kind of the outpost's gimmick, it might be nice if the Box outpost started with more trays, some farmbots, maybe bees, and even xenobotany machines. Big bonus if whoever maps it adds trader access to the whole outpost so that minertide and scientisttide don't immediately raid it for jetpacks at roundstart. Especially since we've finally done away with traders having the option for no ID.

### PR DESCRIPTION
**Pull request by Kurfursten**
fixes #11380
fixes #11158
fixes unreported mapping bugs with the Vox EVA door (basically, none of the buttons worked at all)
adds Vox trader access to almost all of the outpost (not to the frontal trade floor or trade ship dock external airlocks)
- Tested access on all doors
- Tested atmos thoroughly, including oxygen leakage from trade shuttle, to make sure all rooms have proper nitrogen tiles, and the atmos network
- Tested powernet and lighting
- Tested docking of both the raider shuttle and salvage shuttle

I've shown pictures of this to several traders in-game to get feedback, and it seems positive. However, I am **open to further revision**. Here's a basic rundown:
- New design incorporates natural shielding from the asteroid walls, reduces unnecessary walking distances by rotating the station "back" into the asteroid so that shuttles can dock more naturally. The trade floor room has moved very little from its original place.
- Number of trays increased back to 22, pre-Dylan numbers.
- Outpost now starts with bees, xenobotany, one floral somatoray, farmbots, and an extra microwave. These establish the "gimmick" of the Box outpost as botany-focused, as opposed to the mining-focused Deff outpost and research-focused Meta outpost.
- The treadmill is hooked up to the SMES if you want to generate a little power. Or you can sell it to the station.
- In response to requests, the safe is now somewhat more desirable to crack because it contains an additional 1,000 credits.

v2

Note: The botany trays are placed in a 3x3 pattern with no spaces because of how bees work. This is the most efficient way to use bees.

### CODE REVIEW

**Comment by ghost** [comment]
"eeh" = (/obj/structure/table/reinforced,/obj/structure/plasticflaps/mining,/obj/machinery/door/poddoor{id_tag = "tradefloor"; **layer = 3;** name = "Trade Shutter"},/turf/simulated/floor/vox{icon_state = "rockvault"},/area/vox_trading_post/trade_processing)

**Comment by Kurfursten** [comment]
Good catch Skully. I'll fix it during revisions, though, I'm sure someone will come up with something insightful worth changing.

One thing that I have been personally mulling over is the maintenance shaft. Here's the plus sides:
- Some traders I talked to like the maintenance shaft because it makes the station feel more "rustic"
- Provides a natural place to store cleaning supplies

Benefits of taking it out
- Can slide botany up, access it from the main hall - saves steps if you are going to the salvage shuttle or trade floor instead of the trade shuttle

**Comment by ghost** [comment]
To me it just doesn't quite seem dirty enough. A bit too clean considering it's got giant space chickens living in it.

Might be just the floor coloring though
deff_vox_outpost

**Comment by Kurfursten** [comment]
It's amazing how opposite some people want things. I heard some traders say they wanted rustic and messy, wooden themes. Some said they wanted modern and colorful. You say you want dirty and messy, @ihadtoregisterforthis says "clean and empty" (exact quote).

And let's be clear here - I'm totally fine with _any_ solution. If we can find any consistent opinion I am happy to map that, or someone else can map it from scratch, I don't care how we get there. I just want:
- To restore the Box outpost to its former glory as the "botany focused" outpost
- To remove that super lanky walkway to board the shuttle

So if that means experimenting with colors, we can do that. Let's just figure out what to do. Do we want wood paneling? Dark tile spam? Hell, we could use white like the research outpost to evoke a sterile feeling. We could go solid green tones and add a ton of plants. Anything.

**Comment by ghost** [comment]
It needs to have a "nest" appeal. I don't think you can get that with clean, It needs to feel cluttered and ghetto, as if measures were cut when making it.

**Comment by Kurfursten** [comment]
If you bring me a quality sprite of a nest, I will literally replace the closets and tables with a new nest structure object.

**Comment by ghost** [comment]
So top down or side on?

I asked in the thread, but no reply so far

**Comment by Kurfursten** [comment]
Table perspective

**Comment by Kurfursten** [comment]
If you don't think you can manage it, I'll fix the layers and we can ship as-is.

100% of in-game polled Traders felt the new design was an improvement over the old, so that has to count for something. If we want to add nest racks later, we can do that in a different PR.

But if someone has some suggestions as to how to color halls, I'd be happy to listen, and I can add some other messy stuff too like dirt, cockroach remains, etc.

**Comment by ghost** [comment]
Sorry, it had completely slipped my mind. I'll get onto it now

**Comment by ghost** [comment]
Messed about with making a nest through using the current bed as a reference, made some sorta sleeping mat instead

I'll work on a more nest-like nest while using the table as reference now, just leaving the mat here 
bedmat

**Comment by PJB3005** [comment]
How about we make it so that we can have certain parts of the map be picked from a few sets and loaded dynamically?

So one round you get the clean vox outpost, then the dirty one, messy one every once in a while...

**Comment by Durgen** [comment]
The safe still sounds underwhelming and will never be cracked.

It would be dope if it had some nondestructive syndicate item in it.
Maybe a chameleon projector or something?
Raiders use them so maybe all birbs have an affinity for them /deepestlore/

**Comment by Kurfursten** [comment]
It might be more interesting to delete the contents of the safe entirely and make it generate a code sheet every shift so that the birbs can actually use the safe for storage.

**Comment by ComicIronic** [comment]
Keep discussion about the vox safe to its issue unless this PR is intended to address it: #11158

**Comment by Kurfursten** [comment]
@ComicIronic The most popular response of that issue for fixing the safe problem was to add some cash to the safe, so this PR does that.

**Comment by Durgen** [comment]
A safe with a code sheet would be cool

**Comment by Kurfursten** [comment]
@Skullyton If you're not feeling it I'll just finish the PR now.

**Comment by Kurfursten** [comment]
If Skully doesn't reply today I'm gonna fix this up and get it ready for merge.

@DrCelt Any specific requests? An example of a more rundown part if you want to compare is the raider dock, note the dirt, missing tiles, and barricades.

**Comment by ghost** [comment]
@Kurfursten Just a little less ghetto than that in my opinion

**Comment by ghost** [comment]
Go for it, I can't get a good looking nest done

**Comment by Kurfursten** [comment]
@DrCelt What you think bby?

untitled

**Comment by Durgen** [comment]
Won't the low light levels screw with botany a little?

**Comment by Kurfursten** [comment]
Not unless you move the trays. In testing, those trays received 5.6 lumens, and _almost all_ plants won't be harmed until you go below 2 lumens.

I could just add lights in botany though.

**Comment by PJB3005** [comment]
Add some lanterns or something.

**Comment by Kurfursten** [comment]
Someone posted pictures in the thread and reception to sandy floor + ghetto lighting seems very mixed. You could do some polling, but I'd really like to hear what people who _actually play trader_ say. I've tried interviewing a few in character to get thoughts, but that's a very slow and painstaking route.

Adding lanterns is easy, but at the end of the day I just want to get it to a place where people are happy with it. Maybe going to glowshroom lighting was too far.

**Comment by Durgen** [comment]
I'd perfer a normally lit, non rustic outpost
t Tahki

**Comment by ghost** [comment]
> non rustic outpost 

Why even play vox

**Comment by Durgen** [comment]
#10471 you can probably add this one too

**Comment by Kurfursten** [comment]
I dunno, I guess we could poll with

> Use "lit" outpost
> Use "glowshroom" outpost
> Keep current outpost

**Comment by Kurfursten** [comment]
Here is what my polling has determined:

> About 20% of respondents say they "never" play trader or raider, and these people almost universally want to keep the outpost unchanged
> The vast majority of players play trader "occasionally" and like the rustic look
> There is a strong correlation between players who play trader "frequently" and prefer the clean look

Other stuff:
- A couple of people have specifically mentioned the silver airlocks don't match the rustic look, which seems reasonable
- Based on suggestions, I think it would be a good idea to put a crate full of light fixtures in maint so that any Vox who wants to light up the outpost could do so more easily - a good compromise

**Comment by Durgen** [comment]
Broken lights work really well on the salvage shuttle

**Comment by FantasticFwoosh** [comment]
Some sort of large area for keeping boxen (who ironically are just called box) would be appreciated, we can craft cages ourselves out of plasteel but hydroponics especially on the OP map rework photo draft is compact for bees. Therefore our options for raising space pigs (pending more interesting livestock than chickens via a smattering of mad science meets GM farm ranching for profit with alien species, though catching/raising xenomorphs is always interesting) without cluttering up the base are limited.

A specific 'ranching' or even just a 'zoo/containment' area for things like slimes/some NPC's already in cages etc to sell to station xenobio/eat/breed for profit wouldn't go amiss for keeping boxen (in the rare chances that vox remember that wallets have coins for the machine/can be hacked with insulateds) as a primary function in a purpose made room. 

That or just a open empty construction room to be made into whatever we want it to be flexibly in order to stash our loot/machines or whatever inside.

---

Also additional comment in regards to relevant issue #11847 in which the ID access needs to be updated for all the non-personal lockers too, as they are all access also and don't even require ID to be present on the person either.

---

As to station aesthetics, i think we really need to decide on how the birds acquired the station/ship in the first place for artistic direction. Was it built by semi-technologically advanced vox beings a decade or so ahead in tech (as suggested by advanced alien suits and unique techs) or just colonized by a bunch of smart dirty bird nomads/corsairs/free traders already intact who literally put a flag down, moved all their supplies inside and fashioned the space to their needs.

The Vox station we have now is pretty deliberately built and leans towards the former, as its quite rightly stated to be owned by the vox and already has a built for purpose trading post, things are in orderly compact and 'neat spaces'. Changing it towards glowshroom lit and sandy/alternative floors leans towards the latter. Its more a question of WHAT IS a Vox?

**Comment by Intigracy** [comment]
Why does the front desk have plastic shutters if it also has blast doors?

It's harder to break into the front area of the vox outpost than it is to break into the HoP office.

**Comment by Kurfursten** [comment]
The plastic flaps just keep oxygen from coming in, but there's a more fundamental question there below the surface: why is there a trading room with oxygen there at all? The trade shuttle is oxygenated. Honestly I see no reason for a front desk at all. No trading ever goes on there, and likely never will. It's much more efficient to trade on the station. The front desk is an artifact of a time that has passed.

I think removing it entirely would be a better design choice. Then, rotate the main stock room into its place and shift the salvage shuttle dock airlock down and to the left (into the stock room's place).

**Comment by Exxion** [comment]
That trading floor dates back to long before the shuttle was added, and its design sucks ass (though not as much ass as it once did)
It would make perfect sense to remove it

**Comment by FantasticFwoosh** [comment]
Relevant to issues #11860 & #11861 

Will this vox base be the uniform replacement for different vox starts? (as in no risky salvage journey in the future on meta-map that requires the suit to spawn on your character just to survive) because we need a **proper suit up area and or eva** if we are ditching them for vox trader casualwear on the safe breathable and pressurized bases and saving the suits for spacewalks/plots/salvaging or self preservation

At-least 1 security checkpoint would also not be amiss as Vox have no readily available weaponry to use on their trading station in self defense besides (on box start) a cache of hollow darts but no dart gun.

If ideally out of the max spawns of vox traders for each kind of position you could have 4/3/2 on the trading ship 2/3 salvaging and atleast 1 of each department running (if vox trader ever picks up in popularity) between hydroponics (room for 2 but depends of space & plant variety) 1/2 security guard (unless 1 of the guards patrols and watches the trading ship as a bouncer) and 1 engineer (summarily expanded to research duty when and if traders obtain via stealing/bartering a entire RND set)

So on a skeleton crew, typically 2 traders and 2 salvagers (unless they pick it dry and run off to join the traders/vox base crew as spare staff) 1 hydro, 1 guard and 1 engineer to maintain (with another possible committed scientist drawn from spares) not to mention spare miners.

Works out at a skeleton fully minimum staffed vox crew of 9 (with a spare 3 for 1 RND and 2 miners for 12) currently fitting the max capacity of the current dorms without suddenly making it unlimited capacity for spawning within the same proximity.

**Comment by Kurfursten** [comment]
No, I don't have any intention of changing metastation.

I don't really get what you're saying, there's a max of 3 trader slots and I don't think anyone is interested in raising that. Most shifts in my experience have 0-1 traders, and only occasionally multiple. 9 sounds outrageously high.

**Comment by Intigracy** [comment]
don't mind killette #2, he's straight from TG

**Comment by CptWad** [comment]
hey @Kurfursten since another map pr for box is up do you plan on fixing the conflicts?
I mean ill do it for you since this is actually OK
I am personally waiting to merge some shit too so were in the same boat

**Comment by Kurfursten** [comment]
You can feel free to take the map file off the PR and do anything you want with it, I really don't have time to contribute anymore, sadly. Thanks for volunteering, though.

**Comment by CptWad** [comment]
aight I have it downloaded you can delete your branch if you want to now

**Comment by Probe1** [comment]
@Kurfursten GET IN DISCORD

Also either re-open this sucka tonight or I will.  Great PR.

**Comment by Kurfursten** [comment]
Be my guest, take it and run

**Comment by Probe1** [comment]
Oh fuck you deleted your repo when the DMCA happened damnit.  I was like hey easy job just paste it into box and fuuuuuuuuuuck nevermind.

**Comment by Kurfursten** [comment]
Contact me on Steam

**Comment by Probe1** [comment]
YOU DELTED ME ON STEM

**Pull request closed without merging**
