### PR TITLE
All the EOLs are now LF.

### PR DESCRIPTION
**Pull request by PJB3005**
Fuck you too 0D :^)

[Proof that this is only LF conversion, no other changes snuck in.](https://github.com/d3athrow/vgstation13/pull/7733/files?w=0)

### CODE REVIEW

**Comment by clusterfack** [comment]
And thus the war on all open PRs begins

**Comment by PJB3005** [comment]
Just run `find . -type f -name "*.dm" -print0 | xargs -0 dos2unix` oh wait.

**Comment by PJB3005** [comment]
Though really it should be really easy to fix for those PRs, just override the file completely.

**Comment by Exxion** [comment]
So is this setting it back to how it was before everything got ruined?

**Comment by PJB3005** [comment]
No it's setting it to the literal opposite, which it should be at anyways.

**Comment by Exxion** [comment]
So what happened to ruin everything anyway? Config change?

**Comment by clusterfack** [comment]
1. We didn't have standardized line settings so PJB threw in changes to EVERY file with to_chat
2. Tried to standardize them using .gitattributes to one type
3. This lead to annoying problems where git wouldn't recognize whitespace changes while having changes and leave people in a bugged out state

**Comment by clusterfack** [comment]
WHAT COULD POSSIBLY

GO

WRONG

**Pull request merged**
