### PR TITLE
you can now see in the roundend screen if rulesets got bussed

### PR DESCRIPTION
**Pull request by PaulRitter**
[qol][powercreep]
image
image

works for latejoin, midround and roundstart
:cl:
 * rscadd: roundend screen now shows if rulesets got forced by admins so you can metagrudge properly
 * rscadd: you can also see the threat log

### CODE REVIEW

**Comment by PaulRitter** [comment]
also [tested] oops

**Comment by juanototo2** [comment]
grudgecode, but GOOD grudgecode

**Comment by Irradiation** [comment]
Time to ban everybody that upboated the PR for metagrudging.

**Comment by SonixApache** [comment]
On that note, if an admeme changes the threat level by raising the threat, the endround screen doesn't show it.

**Comment by PaulRitter** [comment]
didn't know that was an option, could log that too
whats the verb?

**Comment by SonixApache** [comment]
you click the threat number on the check antags panel

**Comment by d3athrow** [comment]
You're just a bundle of bad PRs aren't you

**Comment by PaulRitter** [comment]
*dab

**Comment by PaulRitter** [comment]
i feel attacked

**Comment by DamianX** [comment]
Paul is a good boy he dindu nuffin

**Comment by boy2mantwicethefam** [comment]
pomf...bro...that's kind of cringe

**Comment by d3athrow** [comment]
2bad

**Comment by ShiftyRail** [comment]
I see no real reason to close this

**Comment by juanototo2** [comment]
Reopen you mongs

**Comment by kilozombie** [comment]
why in god's name did pomf want to close this

**Comment by bathosbathtime** [comment]
Forcing rulesets is already logged, yes?  I have no strong feelings one way or the other so long as the information itself is available.  Do find it strange that it was closed though.  The metagrudging comment was a joke, no?

**Comment by boy2mantwicethefam** [comment]
based

**Comment by soyconsumer** [comment]
really makes you think huh

**Comment by PaulRitter** [comment]
so to increase the chances of pomf reopening this, you can know see the threat log in the roundend screen
image

**Comment by SonixApache** [comment]
travis says you're full of shit

**Comment by PaulRitter** [comment]
>github conflict editor

**Pull request merged**
