### PR TITLE
Slapping glasses off NERDS.

### PR DESCRIPTION
**Pull request by ghost**
Exactly as advertised, behaves just like slapping someone's cheeks except instead of aiming at the head you aim at the eyes and it has a 25% chance to knock off their glasses if they don't have something else covering it (i.e. hardsuit).

:cl:
 * rscadd: You can now slap glasses off somebody by disarm intenting someone while aiming at their eyes.

### CODE REVIEW

**Comment by Eneocho** [comment]
The glasses metaclub will remember this.

**Comment by jwhitak** [comment]
This can primarily be used to steal sechuds.

**Comment by jwhitak** [comment]
Additionally, use drop_item instead of u_equip. Current code ignores the canremove flag... Aka, slap off super glued goggles and other unintended side effects.

**Comment by Eneocho** [comment]
> This can primarily be used to steal sechuds.

Based. Have 2 greyshirts harass a seccie, tackle him, slapsteal the sechud then harmstomp the hud. Better dead than red.

**Comment by wotisjanitor** [comment]
This sucks and so does the slapping feature

**Comment by Kurfursten** [comment]
Ear protection should reduce success chance or prevent entirely. Anything that covers the ears will pin the glasses to the head.

**Comment by ghost** [comment]
Aren't headsets ear protection technically? I feel like that would not make sense.

**Comment by Eneocho** [comment]
> Aren't headsets ear protection technically? I feel like that would not make sense.

He means something like wearing earmuffs and glasses, you'd have the earmuffs on top of your ears, thereby holding the glasses in place. A headset is only placed in one ear, so it'd offer no such protection.

**Comment by ghost** [comment]
Well sure but I'm not sure there's a way to differentiate that in the code.

**Comment by Kurfursten** [comment]
Headsets do not provide ear protection. Here's what does:
- Earmuffs or headset earmuffs

Here's what provides noisedampening
- Helmets (sechelmets, hardsuit helmets, engineering helmets)
- Cult hoods (comment: "these hoods cover the ears")
- The HoS head items

Nothing else provides either

**Comment by Blithering** [comment]
Does this differentiate goggles from glasses?

**Comment by PavelCIA** [comment]
rev buff

**Comment by Optimism333** [comment]
I feel like this is a bad addition mechanically. Wearable items should generally stay attached to players unless someone purposefully takes the time to remove them, whether by getting a stun or fooling them into standing still long enough. Glasses in particular, since several provide flash protection and/or other utility.

It it were just limited to prescription glasses that'd be a bit more reasonable, while still allowing for the joke in the pr title.

**Comment by Eneocho** [comment]
Agreeing with optimism despite the fact I'd love to slap the glasses off of a seccie.
Regular glasses that are just held on place by the ears? Sure go for it. Visors are held around the head, so they'd stay in place, HUDs are borderline on either side, but I'd err on the side of caution and just make them nonslappable either, or with a very small chance.

**Comment by PrimeDSS13** [comment]
I'm not sure how much fun it'll be to play with this mechanic, since nearly every job wears glasses.

**Comment by Kurfursten** [comment]
> I'm not sure how much fun it'll be to play with this mechanic, since nearly every job wears glasses.

I think we need a new space law before this gets merged on destruction of property. Amazingly, we do not have this. You could argue that this is Petty Theft (3 minutes) to Theft (5 minutes) depending on the value of the glasses (e.g.: mesons vs sechuds) -- but I think destroying an item of limited quantity to spite another person represents a slightly higher level of malignancy.

Does this slap action leave fingerprints?
Does stomping glasses leave fibers on the resulting shard?

**Comment by Kurfursten** [comment]
I realized today that this allows you to slap out contacts which is just silly

**Comment by Eneocho** [comment]
> I realized today that this allows you to slap out contacts which is just silly

taking out contacts from someone should take a fair bit longer than taking out glasses or mesons, since you're reaching into the eye to take the contacts out so you'd have to be careful to not crush the contacts or poke the guy in the eye

**Comment by GreatBigFailure** [comment]
Add glasses chains so people can defend against it, but look way nerdier for doing so

**Comment by Cartlord** [comment]
\>rev in cargo
\>rev slaps qm
\>qm loses shades
\>instant qm rev
\>every rev round becomes a cargonia/guncargo round
please do not do this

**Comment by Blithering** [comment]
Rather than needing eye protection protection, how about making this unique to monocles?

**Comment by Kurfursten** [comment]
Even though this has a positive ratio, we haven't seen the author engage with this PR in over a month. I think in its current form it just has too many problems and encourages people strongly to never take their hardsuit helmet off. We don't want secoffs to wear sechardsuit at all times just so they won't get glasses smashed.

**Pull request closed without merging**
