### PR TITLE
Holoray

### PR DESCRIPTION
**Pull request by DeityLink**
ray

I still can't into producing high quality webms to showcase my features. Which is a shame because it looks better animated.
https://www.dropbox.com/s/bulpqh2elxxrt1u/holoray2.webm?dl=0

The ray can go through walls but so does the hologram so who cares (actually I do but I'm tired).

:cl:
* rscadd: Added a transparent animated holographic ray between an holopad and its AI hologram
* rscadd: EMPs turn off AI holograms

### CODE REVIEW

**Comment by Ephx1** [comment]
Would it be at all possible to add click facing to holograms like with humans?

**Comment by DeityLink** [comment]
It'd be a bit complicated, since technically you're not moving the hologram but the AI eye. The hologram is just trying to keep up. I'd rather not touch AI code just for that feature.

**Comment by Ephx1** [comment]
No problem, still a great addition.

**Comment by Pathid** [comment]
The hologram still doesn't have a speech bubble, does it? I guess that's out of the scope of this PR though.

**Comment by DeityLink** [comment]
nope

**Comment by FudgePucker** [comment]
How could a hologram talk? Its just projected light. The AI speaks from speakers, the hologram having a speech bubble doesn't make sense.

**Comment by Pathid** [comment]
Sure, although technically it would be the holopad speakers playing sound while the hologram mouths the words, a visual indication of that would be nice. Similar to how cyborgs and even MMIs and posibrains get speech bubbles even though it's "just speakers."

**Pull request merged**
