### PR TITLE
changes holy water's metabolism back to standard

### PR DESCRIPTION
**Pull request by SirSkeleto**
it was only high for deculting in cult 2, see no reason not to make it standard again :)
[tweak] [balance]

:cl:
 * tweak: holy water has standard metabolism now

### CODE REVIEW

**Comment by Irradiation** [comment]
Put in a changelog you nerd.

**Comment by SirSkeleto** [comment]
[balance]

**Comment by SonixApache** [comment]
still obliterates in cult3 and vamp, come on

**Comment by DeityLink** [comment]
Are you kidding? It's a very potent weapon against cultists and vampires. Holy Incense injects you with holy water basically.

**Comment by ghost** [comment]
A slight huff of incense would destroy vampire's usable blood and encourage even more silent antagging.

**Comment by Dacendeth** [comment]
Holy water unthralls still doesnt it? You could chug a bunch of holy water to prevent being thralled.

**Comment by eplgr** [comment]
Can you explain what this PR does exactly? Is this a buff to holy water? Because it actually needs a huge nerf.

**Comment by SonixApache** [comment]
Makes it so holy water has a very low metabolism, meaning it'll stay in your system for a long time.

**Comment by DeityLink** [comment]
@eplgr yeah it's a huge buff. It essentially causes holy water to linger FIVE TIMES as long in your system.

**Comment by Kurfursten** [comment]
@Dacendeth No, unthralling is done with Bibles

**Comment by Kurfursten** [comment]
This does not appear to be turning around any time soon.

**Pull request closed without merging**
