### PR TITLE
Continuous Beams

### PR DESCRIPTION
**Pull request by Shadowmech88**
The sprites of beam projectiles are now continuous, rather than broken.
The old sprites were left in, in case someone wants to use them in the future.
The appearances of the captain's laser beam and antique laser beam are unchanged.

WebM for comparison: http://puu.sh/tiKCr/9efccd061c.webm

:cl:
 * tweak: The sprites of beam projectiles are now continuous, rather than broken.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by 9600bauds** [comment]
What's with the flickering near the end of the webm?

**Comment by Shadowmech88** [comment]
Must be a recording error. It didn't look like that when I was recording it.

**Comment by Lokiamis** [comment]
> The appearances of the captain's laser beam and antique laser beam are unchanged.

Why not?

**Comment by Intigracy** [comment]
Because it's an antique.

**Comment by ihadtoregisterforthis** [comment]
#6350 whoever is in charge of the tags would need to update this after merge

**Comment by Exxion** [comment]
@Lokiamis Because those two don't use linear projectiles

**Comment by Intigracy** [comment]
They do though, as shown in the video, he just intentionally left them as the old version.

**Comment by Exxion** [comment]
When was that changed?

**Comment by Shadowmech88** [comment]
>They do though, as shown in the video

They don't, I just temporarily changed the captain's laser to use linear movement for the purposes of comparing the old and new laser styles.
The captain's laser and antique laser both still use the old laser sprites as well as non-linear movement.

**Pull request merged**
