### PR TITLE
Construction Update

### PR DESCRIPTION
**Pull request by clusterfack**
IV drips toggle mode verb is now under object like it should be
Intercoms are now constructable and deconstructable
Light switches are now constructable and deconstructable
Air alarm deconstruction works now
Cable coils has its own file under stack
Cyborg radio has its own file under radio

### CODE REVIEW

**Comment by IratePirate** [comment]
Have you added intercoms and light switches to the Guide to Construction on the wikia out of curiosity

**Comment by clusterfack** [comment]
I was waiting till merge for that

**Comment by MusgardTiger** [comment]
And he never did.

**Comment by d3athrow** [comment]
😂

**Pull request merged**
