### PR TITLE
Starts working on reworking xenos - Xeno ruleset

### PR DESCRIPTION
**Pull request by MadmanMartian**
Converts xenos to a ruleset, rather than a random event

### CODE REVIEW

**Comment by Kurfursten** [comment]
Nice

**Comment by Irradiation** [comment]
>/datum/dynamic_ruleset/midround/from_ghosts/faction_based/xenos
	name = "Xenomorph infestation"
	role_category = /datum/role/xeno
	my_fac = /datum/faction/xeno_hive
	enemy_jobs = list("AI", "Cyborg", "Security Officer", "Warden", "Detective", "Head of Security", "Captain")
	required_enemies = list(3,3,3,3,3,2,1,1,0,0)
	required_candidates = 1
	weight = 5
	cost = 35
	requirements = list(90,90,90,80,60,40,30,20,10,10)

BANIC

**Comment by Sooose** [comment]
I'd agree with the weight dropping but I'm assuming it's high for initial testing purposes like blob was.

**Comment by jknpj** [comment]
Purple tag of death

**Comment by MadmanMartian** [comment]
reeee

**Comment by Kurfursten** [comment]
It's cursed! Two coders have given up now.

**Pull request closed without merging**
