### PR TITLE
revert malf hack time back to a flat 60 seconds

### PR DESCRIPTION
**Pull request by gurfan**
I've played through a few malf rounds after this change (including twice as malf) and I don't like it. While I think most people would agree that malfs have a tough time, they should be strengthened in other ways besides reducing the hack time. I think the change makes malf a little *too* easy, the AI doesn't need to plan a strategy anymore or even bother to hide hacked APCs. The hacking time is short enough to the point where the AI can go delta with only a few APCs then just continue hacking its way to victory. This is a grudgecode.

:cl:
 * tweak: The hack time for Malfunctioning AIs has been reverted to a flat 60 seconds.

[tweak]

### CODE REVIEW

**Comment by ghost** [comment]
you need to update the unit test for malf hack timers too, check the travis log if you can't find it

**Comment by gurfan** [comment]
done

**Comment by SonixApache** [comment]
~~this **un**checks a box in #23072~~
wait no it doesn't

yeah this is probably fine
Hacking APCs is one of the most annoying parts of malf, but it's probably fine

shouldn't you use `60 SECONDS`, though?

**Comment by boy2mantwicethefam** [comment]
May I recommend either increasing the amount of APCs until 15 seconds is reached or doing that and also raising the maximum limit to around 30 seconds?

**Comment by dunsel-hordon** [comment]
I'd say malf as a whole needs a bit of an overhaul. Make it so that as a malf ai you must hack apc's but when you hack apcs you get points that let you buy upgrades as a malf ai.

**Comment by DamianX** [comment]
Bad change. Anything that makes it end sooner is good in my book.

**Pull request merged**
