### PR TITLE
[Revival] Radio jammer traitor item

### PR DESCRIPTION
**Pull request by ghost**
Just removing the conflicts this had. (#24085)

# Original PR
Adds a new traitor item inspired by the old goon radio jammer for 8 TC. Comes with a fresh sprite and a sound effect upon activation.
This device actively disrupts radio communications in 7-tile radius. It requires an installed power cell to function. The default high-capacity cell you can find anywhere will last for about a minute or less, so you'd want a bigger one. Also if you yoink the cell while the device is still activated you'll get shocked.
It works as following once activated:

Any radio device (headsets, intercoms, station-bound radios) at point-blank range will be completely silenced (no receiving or sending at all)
In 2 tile range all radio messages (received or sent) will be 99% garbled, simillar to damaged telecomms effect.
3-tile = 80% gibberish rate
4-tile = 66%
5-tile = 40%
6-tile = 25%
7-tile = 12%
If someone can hear from multiple affected radio receivers, only the least garbled message will be shown.
I believe that this is a good balance between being OP and being able to counter the headset or station-bound radio ;HELP macro spam meta as an antagonist. It might not be 100% suitable for silent antagging, because anyone nearby will notice that's something is fishy.
That's why I'm up for discussion about message garbling rates, silence range and power usage. At first I wanted to use some RNG (like 5% chance for a msg not to be silenced if you're in 2 tile range), but then I realized that people would just spam through that.

:cl:
 * rscadd: added new traitor item - the radio jammer. It actively disrupts all radio communication through headsets, intercoms and radios in 7 tile range and can be purchased for just 8 TC. Power cell and screwdriver not included.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
"just" 8 tc more like JUST

**Comment by Eneocho** [comment]
Can't wait for sec to metagame the radio jammer by triangulating the jammer person and hunting for balids.

**Comment by Apogee-dev** [comment]
Looks great, though I wish the total mute range were just slightly increased. Keeping someone at point blank range until they're incapacitated is difficult to say the least, and an obviously-jammed radio message (because it's the only circumstance in which only select people will have garbled transmissions) is pretty much just as good as a ;HELP MAINT

Also, does this affect SPS in any way?

**Comment by Tehsapper** [comment]
Thank you man, funnily enough I also was looking into reviving this PR recently.

**Comment by Kurfursten** [comment]
It would be nice if someone added a freebie jammer to the pocket satellite, that feels thematic

**Comment by Servalfang** [comment]
i think it should be 6 instead of 8 myself

**Pull request merged**
