### PR TITLE
Cleanup Deff Engineering

### PR DESCRIPTION
**Pull request by gurfan**
OLD
dreamseeker_AbT3EpvS4H

NEW
dreamseeker_plv6yq99Jo

Removes random spiderwebs and dust.
Removes maintenance guide that went outside maintenance.
Removes random floating light fixture.
Removes extra PA part.
Adds some colored tiles to make the area look less flat.
Adds some floor decals indicating where radiation collectors should be placed.

**Why its good** 
Makes this part of engineering look somewhat nicer.

:cl:

* tweak: The aft part of Defficiency Engineering has had a small touchup.

### CODE REVIEW

**Comment by Kurfursten** [comment]
A bit lazy on the border colors weren't you?

**Comment by wotisjanitor** [comment]
Keep the dust and cobwebs, every other department on every map has this

**Comment by adacovsk** [comment]
unconnected pipe on the left unconnected wire on the right

**Comment by Kurfursten** [comment]
Now that you mention it... it looks like you have a wire to nowhere in the external airlock, and is that vent connected in the singulo gen room? I'm also suspicious that one light tube is not enough for a room of that size. Could you post an image in-game?

Also, weird that you put the shutter button where you can't get to it initially because of collectors, and that there are 6 collectors but only 4 knots

**Comment by gurfan** [comment]
improved border colors, added two more knots for the collectors, move the collectors to the other side of the room, improved lighting, fixed misaligned vent, added a fire alarm and an air alarm, removed random wires

> Keep the dust and cobwebs, every other department on every map has this

this is false, you're thinking of permagunk

**Comment by adacovsk** [comment]
image update please

**Comment by gurfan** [comment]
dreamseeker_plv6yq99Jo

**Pull request merged**
