### PR TITLE
Changed names of telecommunications equipment

### PR DESCRIPTION
**Pull request by DamianX**
In an effort to salvage #14387, this time in atomic easily-reviewable PRs.

Changes the names of telecommunications equipment.

### CODE REVIEW

**Comment by Knightkiller11** [comment]
So do all Circuit Boards have lowercase names in brackets? or does the game autocorrect that proper?

Cause seeing "Circuit Board (telecommunications bus)" instead of "Circuit Board (Telecommunications Bus)" wil probably drive me insane

**Comment by Exxion** [comment]
There's not really any reason it *should* be capitalized. It's not a proper noun.

**Comment by Knightkiller11** [comment]
Well it's mainly the consistency with pretty much every other circuit board in the game that gets me, cause looking through the rest of the file seems to show every other board being capitalized regardless

**Comment by Exxion** [comment]
Yeah, that's fair
Perhaps someone will go and change the rest, too

**Comment by DamianX** [comment]
Yeah, ideally all circuitboards would have to be renamed. I may do it if I ever finish this.

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
