### PR TITLE
Christmas content:  Jingle bells, Onesies & Animated light up Christmas sweaters

### PR DESCRIPTION
**Pull request by PlausibleDeniability**
### Jingle bells
This is an item that functions like maracas in hand, playing a jingle and can also be attached to shoes, functioning like clown shoes, jingling every step.

Even after toning down the volume, it's pretty annoying, so it's not available outside buses, feel free to change this with future PRs - preview video https://streamable.com/kcmjz6

Shout out to @SonixApache for helping me out considerably with this item's code

image

### Onesies
image
image
image

### Light up Christmas sweaters
redjumper bluejumper greenjumper

### Blue Santa hat
Added a blue variant to match the sweater colours
ibn5E4QJIS

[qol]
[sprites]
[tested]

:cl:
 * rscadd: Created a jingle bell that makes noise like maracas, or attached to shoes to make noise like clown shoes!
 * rscadd: Created several Christmas onesies, available in the festive supplies crate!
 * rscadd: Created a blue santa hat to go along with the others!
 * rscadd: The ugly Christmas sweaters are now animated and have a vox variant!

### CODE REVIEW

**Comment by cloutcode** [comment]
GRAY VARIANTS PLEASE I PAY YOU 100 DOLLAR

**Comment by SonixApache** [comment]
i take no responsibility

**Comment by PlausibleDeniability** [comment]
> GRAY VARIANTS PLEASE I PAY YOU 100 DOLLAR

~~I'll do this tonight 👌~~ Done

**Comment by kilozombie** [comment]
Top tier spriter on campus, goddamn

**Comment by PlausibleDeniability** [comment]
Aseprite_iGb1tCSTT1
Aseprite_iYLi2AOoMO

Added greyshit grey and paincrit pink colour onesies

**Comment by cloutcode** [comment]
NOT THAT GRAY AAAAAAAAUGH

**Comment by TGFH** [comment]
I love the animated ones.

**Comment by SonixApache** [comment]
i think he ment gray as in the aliens

**Comment by PlausibleDeniability** [comment]
Yeah I realised that after the fact, there just not enough grey players for me to be arsed doing it, if anyone else feels like doing it they can go for it

**Pull request merged**
