### PR TITLE
adds potassium carbonate to bananas

### LINKED ISSUE #16508: Small amount of Potassium from Bananas
#### Description of issue
Disclaimer: Paying to add code in no way guarantees a merge request will go through.  At any rate, its only a dollar, so pull that stick out your butts.

I would like to request a feature so that you get a very small amount potassium from grinding bananas.  I think this will cause chaos and generally contribute to the fun of the game.  I have posted a dollar bounty on bountify and the link is here: https://bountify.co/vg-station-add-feature-to-grind-bananas-for-very-small-amounts-of-potassium

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by MadmanMartian**
what it says on the tin. 0.1 potassium carbonate to start off with, increasing by potency/30

Potassium carbonate can be electrolyzed for potassium, oxygen, and carbon.

closes #16508 

:cl:
* rscadd: Bananas now have potassium in them

### CODE REVIEW

**Review by Shadowmech88 — APPROVED** [review]

**Comment by Aurx** [comment]
Now you need to make banana juice explode when mixed with water.

**Comment by ghost** [comment]
So this is just for lmao2uwater2upot powergaming, then?

**Comment by ShiftyRail** [comment]
Water-pottasium being able to happen in the human body is kinda ridiculous in itself, since the average human is about 60% water, and as such needing to ingest water for it to happen is spacemen physics, but that's the fault of our (basic) reagent system.

**Comment by Fruktlimpa** [comment]
I was first worried it was going to be a very easy portable waterpotas reagent clearing thing, but 0.1 potas will instantly metabolize.
You'd have to chug like 20 bananas to have enough in you for you to have time to switch to water and get the reaction.

**Comment by Killette2** [comment]
I don't like this because of how banana is grinded to turn into pure banana. Separating a small bit of potassium every time you need pure banana essence. For example, there are 3 drinks that bartenders can make that require bananas and having that little bit of potassium would be a pain in the ass for a bartender to get rid of.

A compromise that I could think of is make it so banana could also act as potassium in some chemistry recipes.

**Comment by Shadowmech88** [comment]
What if bananas yielded potassium when ground, and banana essence when juiced?

**Comment by Hugh-G-Rection** [comment]
Just make banana essence the botany equivalent of potassium, like Kathalai or Opium. This isn't a terrible idea at all I promise.

**Comment by Aurx** [comment]
What if all fruits contained a modicum of water, so harvesting high yield high potency bananas would blow out your speakers?

**Comment by Hugh-G-Rection** [comment]
It's already possible to get exotic plants that contain potassium and water, though rare. Have a screenshot somewhere of "The orange? violently explodes!"x7 on harvest, though it's possible it's changed since then.

**Comment by Aurx** [comment]
I just want a clown to get blown up because the botanist powergamed their bananas.  
Is that too much to ask?

**Comment by Killette2** [comment]
@Hugh-G-Rection it's actually not possible anymore, someone took the fun

**Comment by gbasood** [comment]
\>grind banana
\>add protein mix
\>add water OH SHIT MY HANDS
this is why you use milk in protein shakes kids

Posted this in the issue but I didn't notice the PR so I'm reposting it:
the reason that banana potassium doesn't explode you when you eat a banana and drink water is because the potassium is bound up in a more complex molecule or something
you'd need to do some C H E M I S T R Y to unbind it
additionally, there's this nerd who tried to chemistry it and it doesnt seem like it worked too well for him, even with a large volume of banana peels:
https://youtu.be/A4EOw6AWzwU

but hey maybe for the sake of video games there's a potassium banana that grind down real good

**Comment by Shadowmech88** [comment]
>the potassium is bound up in a more complex molecule or something
>you'd need to do some C H E M I S T R Y to unbind it

We could make electrolyzing banana essence yield potassium and something else.

**Comment by MadmanMartian** [comment]
Potassium & banana essence = banana essence. Unlimited nanners

**Comment by MadmanMartian** [comment]
@Shadowmech88 updated

**Comment by yackemflam** [comment]
Why not have banana essence act as a stablizer for potassium?

**Comment by Killette2** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Do you still get just banana essence if you juice them instead of grind? This can become the bane of bartenders everywhere if not

**Pull request merged**
