### PR TITLE
Speak finnish randomly when brain damaged

### PR DESCRIPTION
**Pull request by carshalash**
I don't really know how to describe this, you guys can see what it does  pretty easily. Blame deadpool

### CODE REVIEW

**Comment by Intigracy** [comment]
finnish*

**Comment by carshalash** [comment]
Finnished fixing the typo.

**Comment by sonime** [comment]
I DID NOT REQUEST THIS REEEEEEEEEEE

**Comment by sonime** [comment]
I DID NOT REQUEST THIS REEEEEEEEEEE

**Comment by ihadtoregisterforthis** [comment]
This could be it's own gene actually

**Comment by 9600bauds** [comment]
ugh

fine

**Comment by aceedex** [comment]
Spurdos are nice
Not big of a fan on the actual lines

**Comment by clusterfack** [comment]
Literal meme code

**Comment by 9600bauds** [comment]
Do you see why I made the [Memes] tag now?

**Comment by clusterfack** [comment]
Memes tag is a meme

**Comment by 9600bauds** [comment]
it's memes all the way down

**Comment by ihadtoregisterforthis** [comment]
12924510_1019331831474894_3397375645041411821_n

**Comment by AutismSpider** [comment]
snab

**Comment by Arthurdentist** [comment]
assburger

**Comment by BestName** [comment]
That's not even Finnish and as a Finn I'm triggered.

**Comment by Probe1** [comment]
Pick like 1 from the list and add it, we don't need an entire new column of spurdos greatest hits.  If that.

**Comment by Brolaire** [comment]
I feel like Hit me rite in Benis and Oh fugg :-DD are enough

**Comment by unid15** [comment]
benis bambini x--dd

(remove the emoticons though please, if needed then add a custom emotion like /me laughs retardedly)

**Comment by xpcybic** [comment]
i turn the cabtin into a clow :DD-DDD------D:DDD

**Comment by carshalash** [comment]
Reduced as requested. My b

**Comment by SangriaMonkey** [comment]
:bear: :ok_hand:

**Comment by Brolaire** [comment]
> meme PRs get 24 votes
> others get 7
> fug :D

**Comment by ihadtoregisterforthis** [comment]
Many of those are duplicates

**Comment by carshalash** [comment]
17 votes that are unique. We did it deadpool.

**Comment by Brolaire** [comment]
merge?

**Comment by clusterfack** [comment]
He toned it back a lot, I guess its not so bad now

**Comment by Probe1** [comment]
Its still bad but there's only so many fucks I can give and this is not worth them.

**Comment by BestName** [comment]
Stop appropriating my culture shitlords!

**Pull request merged**
