### PR TITLE
Good Market Changes

### PR DESCRIPTION
**Pull request by bathosbathtime**
This pull request adds three items to buy on the black market.  Baby space carps, skub, and dork cubes can now be bought.  Finally we can carp breed without relying on a random event.  Beaming baby carp directly to maintenance to subjugate the assistants is a feature not a bug, but I can disable cheap and normal purchases for that item if it is deemed too much.
The dork cube is also back.  I like this item.  I do think it fits in the black market and I don't mean that as an insult.  It feels sufficiently 'illegal' if there ever was a universally illegal item in space.
Skub requires no explanation.

Tested and compiled locally

:cl:
 * rscadd: Adds baby carp, skub, and dorkcubes to the black market.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
>he added skub

SKUB CHADS WWERE WE ATE

**Comment by Kharkov72** [comment]
>skubfags

begone

**Comment by boy2mantwicethefam** [comment]
FUCK YOU SKUB IS THE BEST

**Comment by Kurfursten** [comment]
📞 Merge the PR with Skub in it? But Monsieur Bogdanoff, it has only been up for 30 minutes. No, no, I understand, we'll tell them it contained a critical hotfix. Just, a little more time.

**Comment by DrSnips** [comment]
wtf I love skub!?

**Comment by tuypo1** [comment]
>A stolen box filled with unknown loot.  Something is sloshing inside.

I'm not entirely clear what a dork cube does but a reliable way to get glorious skub sounds nice, although the idea you should need to go to an illegal market to get something so amazing is absurd.

Spawning carp seems a bit much though.

**Comment by utilitas-** [comment]
Skub should have a minimum of 0 and a maximum of 1. There is power in its scarcity. If everyone could just have their own skub, where would we be then?
But maybe it should be scannable with a traitor mechanic's analyzer.

**Comment by SonixApache** [comment]
\>another lootbox PR

why

**Comment by tuypo1** [comment]
So what does the dork cube do exactly?

**Comment by AI-Is-Rogue** [comment]
>he doesn't know

😏

**Comment by tuypo1** [comment]
Well I figured out what the dork cube does and I wholeheartedly support having more ways for players to gib themselves.

**Comment by FudgePucker** [comment]
#11442 its time

**Comment by SonixApache** [comment]
*why*

**Comment by tuypo1** [comment]
>why

accelerationism

**Pull request merged**
