### PR TITLE
Adds knuckledusters

### PR DESCRIPTION
**Pull request by unid15**
:facepunch: _Perfect to gain an edge in an unfair ~~street~~ maint fight_ :facepunch:

- Added brass knuckles; a glove item that increases damage done by punching, as well as granting a bonus chance of weakening your opponent
- All punches deal 3 more damage with brass knuckles on. So the normal 0-5 damage becomes 3-8. Chance of weakening your opponent is increased from 1/12 to 1/4 per punch.
- Wearing knuckles makes you less dexterous, and therefore unable to use computers and such
- A pair of normal knuckledusters may be bought by traitors for 1 TC.
- A pair of spiked knuckles that add **5** to damage and increase weaken chance to **1/3** may be found in the smooth operator syndie bundle. Also, both types of knuckles can be spawned by maint loot spawners
- Knuckledusters may also be used without being worn, being 5 (7 for spiked ones) force weapons

---

Below are comparisons of 5 normal fist punches, 5 punches with brass knuckles on and 5 punches with spiked knuckles on. 

**Other changes**
- Claws mutation (found in tajarans) no longer increases chance of weakening by same amount as spiked knuckles. It still does the same damage

**Fun facts**
- A hulk tajaran with spiked knuckledusters on deals 13 - 18 damage per punch with a **1/2** chance of knocking his enemies out

### CODE REVIEW

**Comment by Probe1** [comment]
Pretty awesome content but that sprite has got to be reduced in size.

**Comment by unid15** [comment]
How's that?

**Comment by Probe1** [comment]
still xbawks huge but better.

**Comment by unid15** [comment]
It's roughly the size of other gloves

**Comment by Probe1** [comment]
Looks good when compared then.

**Comment by PJB3005** [comment]
@unid15 the thing is, you just straight up scaled them down didn't you? Now they look very blurry.

**Comment by unid15** [comment]
Not that bad imo

**Pull request merged**
