### PR TITLE
Ports Captain's Parade Uniform

### PR DESCRIPTION
**Pull request by SonixApache**
Ports 'Captain's Parade Uniform' from TG.
I always found it a shame that there's a parade tunic and parade cap, but no uniform.
Looks like it should go with a ceremonial sword or something, though.

image
image

image

### CODE REVIEW

**Comment by mtpowell** [comment]
Did you include it in the captains locker? It's supposed to spawn in their locker.

**Comment by Shadowmech88** [comment]
Based on the code, it's currently adminspawn only.

**Comment by Riekland** [comment]
tbh I feel like the captain should have only one outfit so they're easy to identify
Also most all the people who wear the parade shit are utter comdoms
DONT FUCKING PORT THE SWORD WHATEVER YOU DO

**Comment by Exxion** [comment]
Port the sprite for the sword but make it a flimsy piece of shit that breaks if you ever hit someone with it
It is just ceremonial after all

Our just port the sword. Not like it would be stronger than the caplaser or telebaton.

Or also you could just not port the sword

**Comment by Lokiamis** [comment]
green captain when

**Comment by Exxion** [comment]
About one eon ago

**Comment by SonixApache** [comment]
I might port the sword, but with 5(?) force and 0 sharpness. Ceremonial.

**Comment by Exxion** [comment]
5 force might be excessively low. That's like... the same as an unarmed punch, right? Or just slightly higher?
Honestly even if it were on par with one of the shitty katanas, the captain would still have to be an idiot to use it over the telebaton in actual combat

Then again, it could also get stolen

**Comment by SonixApache** [comment]
Same as a crowbar. Rusty katana level could work.
Think punches are, what, two force?

**Comment by yclatious** [comment]
The sword, with significant force values, would at most be either captain ban bait for a retard going MGR with a sabre on a greyshit or a greyshit prize for stealing it and then making his personal display case/wearing it infront of sec for bragging rights.

Don't port it, a greyshirt that wants to nigger weaponry and get tidal points can already steal his stamp, pinpointer, chain, laser and nuke disk since they never take when it matters, don't also give them a miniature HE sword, "captains a comdom" doesn't stop being true just because you gave em a extra means to do comdomry at melee to anyone he doesn't like.

**Comment by SonixApache** [comment]
A 5 force 0 sharpness 'sword' isn't exactly something worth stealing or using apart from bragging rights.

**Comment by yclatious** [comment]
That's why I said that if it had significant force values, low force itd just be greyshirt bait for sec to get perma valids, but even then I wouldn't like it in because inevitably we would have one retard from TG to ask for it to be good instead of decorative and I don't want that possibility to begin with. I get the intention is good but I don't think there would be a alot of oposition from a lot of people to get it powerfull when it would be in.

**Comment by Shadowmech88** [comment]
What if it had no force and made no sound on hit, but displayed a message to the user and did a `local_playsound()` on hit that makes the user *think* they're really fucking their opponent up?

Meanwhile the opponent is receiving messages like "Stunlocker Weldspace pitifully smacks you with the ceremonial sword."

**Comment by SonixApache** [comment]
@yclatious nobody wants captains with uber weapons, people agree the cap's laser is strong as fuck as-is.
I see your point, but I really doubt it'll happen. I'll have the revert PR ready when it does.

@Shadowmech88 
Hitting people with flashlights and toys still hurts, don't see why a ceremonial (plastic?) sword wouldn't. Kinda like it, though.

**Comment by yclatious** [comment]
Its not me doubting you won't make the revert PR sonix, I have trust in you, I just cant say the same for the tidal wave of TG wanabee retards who can with realistic chance outnumber people who have good sense and then spout emojicracy when they won, for better or worse.

**Comment by SonixApache** [comment]
Actually, yeah, fuck this.

**Comment by Exxion** [comment]
>A human punch is 2 force

Wow, I didn't know diona/catbeast/unathi punches were buffed by THAT much
Also, what's a grey's punch? 1 force?

**Comment by SonixApache** [comment]
@Exxion I may be misinformed.

**Comment by Shadowmech88** [comment]
Why close this? It's a perfectly good uniform.

**Comment by Probe1** [comment]
🤷‍♂️

**Pull request closed without merging**
