### PR TITLE
The "Punch" spell no longer shrapnels the wizard nor the victim + a fix

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
When I made the Punch spell it also came with an explosion whitelist that allowed explosions to ignore the wizard, so that the wizard won't be basically punching someone with the force of a fireball (kinda) at close range and then get violently destroyed by the ensuing explosion. Unfortunately the shrapnel addition to explosives effectively rendered that point moot, as it was very likely that the debris launched forward by the explosion from the Punch would slam right into the wizard, obliterating them. Frankly it was a significant motivation for attempting to nerf shrapnel damage on two separate occasions.
After the pull request was made I realized that the Punch spell, for the last year, has been ridiculously lethal against its victims; the shrapnel affected them too. They are now immune to the Punch shrapnel too, because that's cool and because it's balanced. Sorry for the Punch-induced instakill grievances for the last year or so.

This PR makes both the wizard and their target immune to the shrapnel caused by the Punch spell, by adding a shrapnel whitelist which gets carried all the way to throw impact code, in which neither the target nor the wizard will get damaged. They will still be hit, it's just that they won't take any damage from being hit, so if a bola happens to be launched by an explosion in will still entangle whoever it hits.

Also fixes a bug where for a brief moment a timestopped target getting Punched would spin.

:cl:
 * rscadd: The Wizard's "Punch" spell will now also make both the wizard and their target immune to the damage caused by any shrapnel launched by the ensuing explosion. It will not, however, cancel any effect that the shrapnel may have, such as bolas entangling their targets.
 * bugfix: Fixed a bug where if a wizard used the "Punch" spell on a target frozen in time it would permanently displace their sprite.

### CODE REVIEW

**Comment by Eneocho** [comment]
I haven't messed with Punch wizardry that much, does the explosion whitelist include non-wizard-sourced explosions? As in, if grey mcshirt welderbombs the wizman, does the wizard stay unharmed?

**Comment by boy2mantwicethefam** [comment]
No, the wizard is only immune to his Punch's own explosion.

**Comment by Eneocho** [comment]
Ah, ok.

**Comment by DorainGrey** [comment]
I think it serves as an important balance, to how powerful timestop + punch can be.

**Comment by djkramer123** [comment]
Making them immune to shrapnel damage should be an empowerment investment

**Comment by boy2mantwicethefam** [comment]
@DorainGrey It's a terrible balance that makes the Punch spell, ironically, unusable in close quarters or right next to walls because the shrapnel is likely to kill the wizard if the target impacts something too close. There are way worse things that can be used during Time Stop too, and from a distance.
@djkramer123 3 upvotes on your message and I'll do it.

**Comment by DorainGrey** [comment]
> @DorainGrey It's a terrible balance that makes the Punch spell, ironically, unusable in close quarters or right next to walls because the shrapnel is likely to kill the wizard if the target impacts something too close. There are way worse things that can be used during Time Stop too, and from a distance.
 
I don't know of anything that can easily instant kill you on hit like punch with the explosion does. Though I'm interested to hear any combos which do?
Which is why it syncs so well with timestop. 

If explosions are such a weakness for a close range spell, then maybe it shouldn't have them?

**Comment by boy2mantwicethefam** [comment]
It's very likely that the Punch has been made extra lethal by the shrapnel from whatever is being destroyed smashing into the victim, exacerbating the damage. I will fix that by adding the target to the shrapnel whitelist, rendering them immune to the shrapnel just like the wizard. You know, for balance.

**Comment by gurfan** [comment]
Punch is already extremely powerful. I would prefer if wizards had to worry about shrapnel.

**Comment by pedr69** [comment]
can you also fix bodies being rotated forever

**Comment by boy2mantwicethefam** [comment]
The PR should already try to fix that, or at the very least one case of it.

**Comment by lol-and** [comment]
You call it bug-fixing I call it soul-sucking. Life for the spin

**Comment by boy2mantwicethefam** [comment]
The spell still spins targets, it just won't permanently displace their sprite anymore when punching them during time stop.
The bug was caused by the part of the code responsible for it getting called because throw_at() momentarily prevents the thrown target from being timestopped, but for some reason it didn't call the rest of the code that made sure to reset the target's sprite. The fix turned out to be initially delaying the spin first instead of delaying the spin after doing it the first time.

**Comment by lol-and** [comment]
I know what I said

**Comment by boy2mantwicethefam** [comment]
Not every bug is sovlfvl!

**Pull request merged**
