### PR TITLE
Adds 3 more right and wrong summoning spells

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Summon explosives, Summon electromagnetic cards, summon mechs
Summon explosives:
 - Costs 40 points
 - Gives the Mad Bombers a selection out of 5 boxes of bombs
 - Mad Bombers have the objective to imitate Cuban Pete
 - Only one explosive is directly dangerous
 - Has a very, very low chance of giving out a TTV as a bonus
 - Can give out a box of: Flashbangs, EMPs, clusterbangs, shrapnel IEDs, chrono grenades

Summon emags:
 - Costs 20 points
 - Gives the Saboteurs emags.
 - Saboteurs have the objective to sabotage

Summon mechs:
 - Costs 40 points
 - Gives the Mech Warriors(TM) a selection out of 5 mechs
 - Mech Warriors have the objective to fight other Mech Warriors, but they can do whatever they want.
 - Only 2 mechs are properly weaponized
 - Can give out a Ripley, Odysseus, Clarke, Gygax, or Durand

All the survivor objectives are actually reskinned "Stay alive until the end of the round" objectives which means they fail if they die.
Saboteur excuse objective may or may not be broken.
Added box of clusterbangs, box of IEDs, and 4 preloaded mechs to the code.
:cl:
 * rscadd: Added 3 Summon spells. Summon Explosives, Summon Electromagnetic Cards, Summon Mechs. Summon Explosives and Summon Mechs cost 40 points instead of 20.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
it was tested

**Comment by ShiftyRail** [comment]
Are the mechs which are "properly weaponised" given at random or only to people that were lucky enough to roll survivor ?

**Comment by boy2mantwicethefam** [comment]
According to the "Right and wrong" code itself, there is a 35% BYOND prob chance that people are turned into survivors and are given the items

**Comment by Hoshi-chan** [comment]
I said it in discord, I'll say it here again: even a _single_ emag can cause a tremendous amount of chaos, let alone giving them to 35% of the fucking crew with the explicit objective to sabotage as much shit as possible. Every airlock on-station will be emagged open within three minutes. It's pretty much a guaranteed shuttle call. All that's not even considering the incredibly low cost you've assigned to it, or that it's explicitly spawning _traitor items_ that can otherwise only be acquired by traitors. You might as well call it "Summon Autotraitor".

Summon explosives sounds incredibly lame, to be honest. We had discussed custom grenade mixes in discord when you first brought this up, but what you've decided upon is a single, weak explosive, a single absurdly strong explosive, and a bunch of items that aren't really explosive at all, they just happen to be grenades. What about regular old explosive grenades? C4? RPGs?

The mech thing still just seems... off to me. Much like the emags, it seems like no matter how you price it, you're introducing far too much into the round, and to no real benefit to the wizard. The wizard's not going to pilot a mech, he's not going to be able to reasonably take one down if he encounters someone inside of one, and honestly, how many of the mechs are just going to wind up taking up space in the hallway, especially all the unwanted odysseuses, ripleys, and clarkes? How often do you even see people requesting those mechs, that you think they'd use them if they were just suddenly thrust upon them?

Yeah, that's how I want to spend my wizard-created traitor round, slowly walking down halls in a fucking Ripley. No thanks.

I usually dig your PRs, but this one sort of stinks. I still think Summon Explosives has potential, but not the way that you're presenting it here.

**Comment by boy2mantwicethefam** [comment]
Emags aren't THAT powerful
Summon explosives is going to have more stuff because I find it lacking currently

**Comment by Hoshi-chan** [comment]
> Emags aren't THAT powerful
> Summon explosives is going to have more stuff because I find it lacking currently

It's not about power. It's about impact. Last round we had a single man with an emag. In minutes he emagged most of the station open (not exaggerating), emagged open the AI upload and subverted the AI, and emagged just about every device, console, and sign on the station.

It took us about an hour to clean it all up. This was _one_ traitor, being _actively pursued_ by sec. Imagine the damage that three could do, or five, or ten, especially when given the explicit objective to do so by the spell.

**Comment by Irradiation** [comment]
>Emags aren't THAT powerful
>Emags aren't THAT powerful

You can shitpost on discord all you want, but fuck off with those blatant lies.

**Comment by boy2mantwicethefam** [comment]
>Last round

That's lowpop and people can get away with a lot of things
I was thinking of changing the stuff saboteurs are given because just emags doesn't really live up to the saboteur's namesake

**Comment by Hoshi-chan** [comment]
> > Last round
> 
> That's lowpop and people can get away with a lot of things
> I was thinking of changing the stuff saboteurs are given because just emags doesn't really live up to the saboteur's namesake

We had five people on sec.

And an AI, though it was briefly subverted.

**Comment by boy2mantwicethefam** [comment]
Fair

**Comment by Caboozles** [comment]
Just add these explosives to summon weapons (and add Nikita and RPG as a super low chance for that hilarity)

**Comment by yclatious** [comment]
I like fun. I dont like actual retardation. This is so far out of balance its like God doing the meteor balance patch on dinosaurs.

No.

**Comment by Zth--** [comment]
Wow these are bad. The emag one could be fixed if it spawned emags with a limited use (maybe 5?). Bombs are boring as fuck and also why.
Mechs? No.

**Comment by Exxion** [comment]
Last I checked, everyone gets weapons with summon guns/swords, not just the survivors
May have changed, but I doubt it

**Comment by Caboozles** [comment]
Not everyone gets it anymore. I actually can’t say survivors only without checking the code directly, but anecdotally the past 3 summons I have not had anything appear near me.

**Comment by Exxion** [comment]
Oh yeah, it looks like ever since datums they're only given to survivors
Was that intentional, @ShiftyRail?

**Comment by DrSnips** [comment]
These are pretty lame not gonna lie. Mech one is going to be a snooze fest, emag one is going to be big gay and instant shuttle calls with emagged console shitposts, and the explosives one is just DUDE BOMBS but gayer.

**Comment by SonixApache** [comment]
full retard

**Comment by ShiftyRail** [comment]
@Exxion I'm pretty certain I actually fixed that #19955
Maybe someone unfixed it, I don't know

**Comment by Exxion** [comment]
Ah, you're right. Looks like @Kurfursten un-fixed it in #21311.

**Comment by Kurfursten** [comment]
What an oversight. That's a really easy fix if someone would like to just slide that prob(65) down below equip_survivor

(I'm also noticing that this prevents summon spells magicians from getting multiple bundles because they would be iswizard. Intentional??)

**Comment by Exxion** [comment]
Wizards not getting anything from summoning is intentional, yes. It's intended to cause chaos, not to get the wizard some fancy tools.
It *used* to not give *any* antags items, which kind of fucked over people who rolled survivor on the first summon if the wizard used more than one

**Comment by Kurfursten** [comment]
No, no, you're forgetting that magicians *from summon magic* are subtypes of wizards and therefore get skipped if summon magic is picked multiple times

**Comment by Exxion** [comment]
Oh, sorry
Then yeah that's not intentional
Why are they subtypes of wizard instead of survivor though?

**Comment by Kurfursten** [comment]
Supposedly(?) it has interactions with spells that check for the wizard role? I don't know if such things exist for real though that's hearsay

**Comment by Coxswain-Navigator** [comment]
I think summon explosives has potential, but the other two gonna be hard to execute with any sort of sanity. However, adding a ghost role that allows you to spawn in the thunderdome as a mecha warrior might be fun.

**Comment by boy2mantwicethefam** [comment]
people didn't like this so I'm closing it for now

**Pull request closed without merging**
