### PR TITLE
fixes #6831

### LINKED ISSUE #6831: Shiggy your waifu crate is fucked
It don't work 
Can't give a reason for the order, can't receive waifu shit

### PR DESCRIPTION
**Pull request by Kurfursten**
@ShiggyPiggy Supply ordering doesn't like the & character

fixes #6831

Fully tested

### CODE REVIEW

**Comment by FudgePucker** [comment]
Ah, guess the name of the order being too long would fuck it up, but why would have it fucked up because of something as silly as length?

MISSION ACCOMPLISHED.
EDIT: Is it the &?

**Comment by Probe1** [comment]
> formalware

formal **wear**

**Comment by Kurfursten** [comment]
@FudgePucker & is a special character, it probably had weird interactions with the rest of the code

**Comment by FudgePucker** [comment]
Yea I just realized that the moment you posted it because "incendiary weapon crate" would also be too long.

If it is in quotations, wouldn't it be a string though?
Is byond really that shitty that you can't use special characters in strings?

**Comment by Kurfursten** [comment]
Probably works with escape characters, you might be able to find some documentation if you dig in the api

**Comment by clusterfack** [comment]
Deja vu

**Comment by Probe1** [comment]
He misspelled formalwear..

**Comment by 9600bauds** [comment]
it is an analogy and social commentary on the state of waifus

**Comment by Kurfursten** [comment]
You're not actually supposed to wear the clothes. They're formal wares.

**Pull request merged**
