### PR TITLE
Crab Claws and Crab People (draft)

### PR DESCRIPTION
**Pull request by JonathanSpaceStation**
## What this does
This is an attempt to add crab claws which you can attach to people. 
image

More specifically adds a hidden "crab human" species with crab hands, and later will add these crab hands as a butcher product from giant crabs so that an enterprising surgeon can butcher a crab and upgrade an assistant. 

There is a lot that needs to be done and I realise this approach is probably not the best way to do it; but if I can get it working I do think this would be a fun potential addition. Looking for any critical feedback as I am really not a coder and would appreciate the help. 

Goal is to be able to butcher crabs and then attach the resultant claws to assistants; crab claws allow you to pinch and deal a decent chunk of damage, but prevent glove wearing and using machines. 

Credit to @falcon2346 for the sprites

## To Do
- Crab hands as butcher product from crabs
- Dexterity check; currently if your species is "crab" then you are prevented from using machines, but if you are a human who has had a crab claw attached via surgery, you can use machines fine. Need to make the dexterity check attached to the crab claws themselves and not the species. 
- Have someone smarter then me look at this
## Changelog

:cl:
 * rscadd: Added crab claws which you can attach to people via surgery

### CODE REVIEW

**Comment by SECBATON-GRIFFON** [comment]
when all the world is metrosexual, the crab people shall finally reign supreme

**Comment by hacker-on-steroids** [comment]
;LING
wait nevermind

**Comment by ghost** [comment]
I have to imagine making this a new species is going to cause some issues, I think a better approach would be to copy the code for robotic limbs minus the robotic part and alter it to be crab.

**Comment by JonathanSpaceStation** [comment]
> I have to imagine making this a new species is going to cause some issues, I think a better approach would be to copy the code for robotic limbs minus the robotic part and alter it to be crab.

I did try this initially but I had trouble figuring it out; to put it simply limb / organ code is a nightmare. Furthermore things like attack messages and punch damage for limbs are inherited from species.

The biggest issue I could anticipate is somebody getting this species via some unforeseen mechanism. Most likely culprits would be staff of change, via Frankenstein and possibly via the xeno chimera virus. I've tried or will try to account for all of these, but if there is a smarter way to do this then I am all ears.

**Comment by JonathanSpaceStation** [comment]
just going to close this, don't really have the time or motivation to finish and I think we really need organ datums which is far beyond my skill to code

**Comment by Eneocho** [comment]
what a shame

**Pull request closed without merging**
