### PR TITLE
Purges Ninja and its snowflake/badcode

### PR DESCRIPTION
**Pull request by clusterfack**
Removes basically any and all active references to the ninjacode. A fresh slate if we were to port ninja code from someone now.

Honk

### CODE REVIEW

**Comment by dylanstrategie** [comment]
We will be better off this way. No serious progress can be made on the code with such snowflake messes all over it, was the same with other procs like meteor_act()

**Comment by FudgePucker** [comment]
RIP in piss speess ninja.
Admins can just bus someone in with HF katana

**Comment by IratePirate** [comment]
Thank fuck. Good job.

**Comment by Intigracy** [comment]
Quick, before there's conflicts!

**Comment by SkowronX** [comment]
Good riddance

**Comment by Probe1** [comment]
inb4 someone returns from the grave to say they were working on it and if you'd just give them another 3 years they'll have it fixed up

**Comment by Intigracy** [comment]
They can shove it up their ass and reimplement it when it's done.

**Comment by Probe1** [comment]
the joke in there was it happens from time to time.  but not with this.  ninjas just there because no one had yet removed it.

**Comment by ComicIronic** [comment]
Guys, I hired a team of twelve Mexican badcoders to recode the gamemode, and they say they'll be done by next year!

**Comment by Intigracy** [comment]
Next year they can reimplement ninja then.

**Comment by Intigracy** [comment]
And I do realize you guys are joking, but it's just that shit like that
actually DID happen fairly often with numbers and coderbus on tg, and it's
irritating as shit.

**Comment by Zuhayr** [comment]
We moved all the ninja functionality over to our hardsuit system on Bay, might be worth looking at porting that over.

**Comment by clusterfack** [comment]
That sounds great

**Comment by Probe1** [comment]
ninja back when

**Comment by dylanstrategie** [comment]
Quite literally when you code it

**Pull request merged**
