### PR TITLE
Ports self-replenishing containers from bay, Adds a chance for Urns and Bowls to be self-replenishing containers

### PR DESCRIPTION
**Pull request by jknpj**
ancient manly dorf
Urns and bowls now have a small chance(12.5%) to spawn with the ability to replenish themselves (0.3 un per tick, the're a glass child so they can hold up to 50 un) with an reagent from the list below:

BLOOD
HOLYWATER
CLEANER
LUBE
NOTHING
FROSTOIL
CAPSAICIN
WATER
FUEL
PLASMA
MOONROCKS
CARPPHEROMONES
ETHANOL
DRINK
HIPPIESDELIGHT
PWINE (Poison Wine)
MANLYDORF
CHANGELINGSTING
CITALOPRAM
PAROXETINE

:cl:
 * rscadd: Ports self-replenishing containers from bay
 * tweak: Xenoarcheology urns and bowls now have a change to spawn as self-replenishing containers

### CODE REVIEW

**Comment by PJB3005** [comment]
We should have an an extremely rare large artifact as replenishing container of Adminordrazine.

**Review by PJB3005 — APPROVED** [review]

**Comment by FudgePucker** [comment]
>Lube

How about no.

**Comment by Aurx** [comment]
>We should have an an extremely rare large artifact as replenishing container of Adminordrazine.

Adminodrazine honestly shouldn't even exist, much less ever be available to players.

**Comment by PJB3005** [comment]
@Aurx I disagree.

It's basically just invincibility against non-one shots.

Doesn't fix bones, doesn't revive you, doesn't save you from being gibbed.

**Comment by AutismSpider** [comment]
@FudgePucker you do know can ghetto make lube round start?

**Comment by SonixApache** [comment]
Neat.

**Comment by jknpj** [comment]
>thinking lube is bad

Watch as admins give the clown a self-replenishing container of super glue.

**Comment by Aurx** [comment]
>container

I was thinking self-replenishing nodrop chemsprayer of yellow paint and lube.  Glue too, if it has a sprayed effect.  

@PJB3005 I don't get why you don't see an issue with having to gib somebody to kill them while they utterly refuse to die or stay stunned.

**Comment by Intigracy** [comment]
shoulda done zombiepowder instead of changelingsting

**Comment by Exxion** [comment]
Yeah, Changeling Sting is just a mildly annoying-to-make drink

Also, what the fuck is `DRINK`?

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/blob/101a516beed8455460012087bfc0c3b9072e1115/code/modules/reagents/Chemistry-Reagents.dm#L3719

It's actually unused anywhere but here, neat.

**Comment by Intigracy** [comment]
The best one on that list is MOONROCKS which looks like it does literally nothing.

**Comment by Exxion** [comment]
`DRINK` also does nothing
Its purpose is to be the parent of other drinks
It is, however, guaranteed to be mildly hilarious the first couple times someone finds a bowl that generates it

**Comment by Intigracy** [comment]
MOONROCKS seems fine in that at least it's lore-y.

I'll swap the changelingsting for zombiepowder and remove the DRINK

**Comment by Exxion** [comment]
Please don't remove `DRINK`

**Comment by Intigracy** [comment]
#14339

**Comment by Riekland** [comment]
MOONROCKS are what's in discount dans, right? Aren't all of those just copy pasted toxic things?

**Comment by nuklearcellphoneg** [comment]
Nope

**Pull request merged**
