### PR TITLE
Outfits datums - BE Parity WITHOUT being Orwellian

### PR DESCRIPTION
**Pull request by ShiftyRail**
**FOR THE LOVE OF GOD IF YOU MERGE THIS DON'T USE SQUASH AND MERGE THANKS**

I did a dumb in a recent PR that accidentally rewrote history, which wasn't at all what was intended.
I apologise to Git Brother for my sins and certify that this PR is doubleplusgood.

We've always been VG station.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
/vg/ not VG mm'kay

**Comment by ShiftyRail** [comment]
ssethbabies have been unpersoned, begone

**Comment by SonixApache** [comment]
/vg/ not VG ok
fucking meme collab

**Comment by Kharkov72** [comment]
what is this anyways

**Comment by ShiftyRail** [comment]
@SonixApache read 1984 and learn to get a bad joke
@Kharkov72 a way to get the branch on which outfit datums are working on the same level as the main one
in other words, fixing conflicts, plain and simple

**Pull request merged**
