### PR TITLE
IT JUST WORKS

### LINKED ISSUE #10901: Asteroid next turf overlays show under the space parallax
The rock outcroppings around asteroid tiles don't show properly over space

It seems pretty obvious that the overlay's layer must not be high enough compared to the parallax, or something of that order

Since asteroid code is some real spaghetti code, it's hard to tell what in the new parallax and layering system broke it partially

@clusterfack

### PR DESCRIPTION
**Pull request by ghost**
I MEAN IT JUST WORKS
IT JUST WORKS PERFECTLY
FIXES #10901 BUT WHY CARE ABOUT THAT THIS IS THE BEST
WATCH THIS WEBM
THERE IS
NO UPDATE_ICON, NOR PROC CALL.
NONE
ZILCH
NADA
RIEN
http://puu.sh/rP8bR/358414fc68.webm
ALL POSSIBLE BECAUSE OF 🛫🛩️🛬✈️😍😩👌🏻💦🍆
OTHERWISE I FILLED THE TEST TINY MAP WITH THE BASE TURF OF MINERALS AND IT TOOK MAYBE FIVE SECONDS OF LAG OH MY GOODNESS GRACIOUS IT JUST WORKS

### CODE REVIEW

**Comment by clusterfack** [comment]
See pixels doesn't work, unless you've solved the click catcher issue.

**Comment by DrCelt** [comment]
http://puu.sh/rP8k4/c4e0100782.png

**Comment by Intigracy** [comment]
According to clusterfack this'll break the click catcher.

**Comment by Exxion** [comment]
Yeah
He said that two comments ago

**Comment by ghost** [comment]
Thanks byond tag added please thanks

**Comment by optimumtact** [comment]
I paid 100 dollars for this flag and apparently it's only of use to vg coders

what a waste

**Comment by Intigracy** [comment]
Feel free to re-open this if you can convince Lummox to fix the behavior of see darkness, or if you have another way to fix this that isn't relying on it.

**Comment by ghost** [comment]
LADS IT'S HABBEDIG

**Pull request closed without merging**
