### PR TITLE
Missing corn icon

### PR DESCRIPTION
**Pull request by ghost**
:cl:
 * imageadd: Adds a missing icon state for corn.

### CODE REVIEW

**Comment by SonixApache** [comment]
🤔 
image

**Comment by ComradeDispenser** [comment]
Why don't we just add the synthmeat plant back in?

**Comment by bathosbathtime** [comment]
Why is the file cleanup undocumented

**Comment by ghost** [comment]
So uhhhhhhhhhhhhhhhh dmis have a limit of 512 icon states with no warning when you add more which broke the entire fucking thing by trying to add one state.

Instead of this bandaid fix, I am going to work together with Comrade Dispenser to split the file into individual dmis for each crop because fuck oldcoders.

**Comment by DrSnips** [comment]
>each plant has it's own DMI

I feel like this is worse than having just one or two DMIs for plant stuff

**Comment by Exxion** [comment]
It isn't

**Comment by ghost** [comment]
> 
> 
> > each plant has it's own DMI
> 
> I feel like this is worse than having just one or two DMIs for plant stuff

The way it is right now is actually the exact opposite of how you should organize game assets.

**Pull request closed without merging**
