### PR TITLE
allows gloves to fit on toolbelts

### PR DESCRIPTION
**Pull request by Hatterhat**
see title. just adds gloves to the toolbelt's can_only_hold list
:cl:
 * rscadd: Gloves can now be haphazardly tucked into toolbelts.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Switchtools are already absurdly good, they really don't need this buff

**Comment by Hatterhat** [comment]
after mulling over it (read: checking the code channel and thinking "wait, fuck"), i'm narrowing this down to just gloves

**Comment by Dacendeth** [comment]
This wont make quick equiping gloves go into the belt instead of swaping gloves will it?

**Comment by Hatterhat** [comment]
> 
> 
> This wont make quick equiping gloves go into the belt instead of swaping gloves will it?

equip_to_appropriate_slot's slot equipment priority has gloves above belt, so i'm pretty sure it should swap gloves

edit: can confirm, quick equip swaps gloves

**Comment by xeroxemnas** [comment]
BELTCREEP
BELTCREEP

**Comment by Blithering** [comment]
Toolbelts could already fit insulated gloves couldn't they? What other types would an engineer need to cart around?

**Comment by xeroxemnas** [comment]
> Toolbelts could already fit insulated gloves couldn't they? What other types would an engineer need to cart around?

Stungloves of course

**Comment by Hatterhat** [comment]
yeah this pr's kinda dogwater

**Pull request closed without merging**
