### PR TITLE
add secret alienwhitelist.txt code back

### PR DESCRIPTION
**Pull request by adacovsk**
So one of my previous PRs removed some code because it didn't work with what I was doing (and it didn't work period). So I made a new PR that re-adds it back, but it does work but with some more limited functionality, as the other system works extremely well for whitelisting/blacklisting jobs and species. "All" does not work though.

## What this does
image

## Why it's good
- anyone who can edit alienwhitelist.txt can play as any species they choose as long as it actually exists

### CODE REVIEW

**Comment by ghost** [comment]
this is a bad implementation and should probably be removed rather than made functional

i don't have a reason for this it's just my intuition

**Comment by ManopolisJones** [comment]
Seeing this PR makes me think we need added Muton functionality as a species

**Comment by NigglyWiggly** [comment]
But if we were to actually allow players to play as Mutons, they might eventually ask why they have 2 right hands!

**Comment by Kurfursten** [comment]
Closed for ancientpower's reason

**Pull request closed without merging**
