### PR TITLE
Fix cached HTML maps sometimes overriding the current map

### PR DESCRIPTION
**Pull request by clusterfack**
Fixes some issue or another, I cant find it

### CODE REVIEW

**Comment by clusterfack** [comment]
Really only just adds the name of the map to the minimaps file so there's no collision in the cache between them.

**Comment by gbasood** [comment]
Does this not also change how minimaps are generated so that they're stored with their long name?

**Comment by DrCelt** [comment]
>Really only just adds the name of the map to the minimaps file so there's no collision in the cache between them.

So it won't work when dealing with say a new map update?

**Comment by gbasood** [comment]
I mean, we could do checksums for maps to handle most caching issues

**Comment by Imagebard** [comment]
>Fixes some issue or another, I cant find it

It should be important for consoles that use a image of the map to make a easy interface to see cameras and the such.

**Comment by clusterfack** [comment]
Okay explaining time the since there's some confusion
1. Mini maps are generated on a per round basis
2. They are stored in the cache of users with the only name difference being the z level
3. This causes either byond or the asset cache, I do not know which, to not overwrite it. Which causes an earlier cached minimap to appear on a different station.
4. Since everything that uses these minimaps specifically uses this proc to name or get the name this causes no issues.

**Comment by ihadtoregisterforthis** [comment]
Why are minimaps generated all the time anyways?

**Comment by clusterfack** [comment]
Because nobody has coded them to not

**Comment by gbasood** [comment]
Okay but @clusterfack the minimap generation filenames haven't changed, so wouldn't they now be trying to access minimaps that aren't there because the filename it's looking for is different from the filename it generated the minimap under?

**Comment by clusterfack** [comment]
The fuck are you talking about, the minimap generation filenames WOULD be changed.

**Comment by clusterfack** [comment]
Look 9 lines below my change

**Comment by gbasood** [comment]
well nevermind then I thought I saw something different there OH WELL

**Pull request merged**
