### PR TITLE
Fixes lighting overlays & pooling

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by ComicIronic** [comment]
We need to figure out a macro for passing the resetVariables args up as simply as possible because the way people are coding them means they aren't filtering through properly.

**Comment by clusterfack** [comment]
Why not?

**Comment by ComicIronic** [comment]
What isn't reset by the top level proc is decided by the arguments passed to it. 

Consider

```
datum/foo/resetVariables (...)
    bazz = null
    .. ("bazz")

datum/foo/bar/resetVariables (...)
    bozz = null
    .. ("bozz")
```

The second reset-exclusion will never reach the top proc and bozz will be reset to initial () even though the code looks like it shouldn't, because foo's reset doesn't pass the args up.

**Comment by clusterfack** [comment]
Isnt that why we pass up (whatever, args)?

**Comment by ComicIronic** [comment]
We should be doing that, but it's not done here, and to my knowledge, it's not done elsewhere either. I don't know if you have to pass up the argslist instead.

**Comment by clusterfack** [comment]
I thought it was done everywhere and this is the exception

**Comment by ComicIronic** [comment]
Sadly not.
Some resetVariables signatures even omit the ..., so I don't even know if they pass to parent correctly when they DO use args. But plenty of them don't pass up.

**Comment by PJB3005** [comment]
`...` to define an ellipse is complete cosmetic.

**Comment by ComicIronic** [comment]
What happens if you don't define the arg at all, though? You can just get `resetVariables()`, and I don't know what happens if you do `..()` with that.

**Comment by ComicIronic** [comment]
I'll make a PR for those resetVariables changes.

**Pull request merged**
