### PR TITLE
Multiplies spell prices and spellbook points by 5

### PR DESCRIPTION
**Pull request by unid15**
Spellbook now has 25 points. Most spells now cost 5 points, no clothes costs 10, santa bundle costs 15, spellbook bundle costs 25.

Now we can have cheap spells and expensive spells. Like 2 point knock and 6 point jaunt.
I'll adjust prices and add some cheap cantrips soon

### CODE REVIEW

**Comment by CptWad** [comment]
sure why not

**Comment by Exxion** [comment]
You may want to explicitly point out in the changelog that there is effectively no change here, because I can guarantee that some dumb fuck will fail to figure that out from what's already there and will commence shitposting

**Comment by ComicIronic** [comment]
Will merge first spell cost balance PR <sub>after review</sub>

**Comment by CptWad** [comment]
wow that was fast

**Comment by Killette2** [comment]
This can go wrong easily, I still want to see it happen anyways.

**Comment by Exxion** [comment]
How could it go wrong?

**Comment by Killette2** [comment]
Bad balance changes, a constant shifting "spell meta" due to price shifts, certain conflicting combos making spell pricing difficult because a spell is ok in one combo, but OP in another.

**Comment by ComicIronic** [comment]
Better than the completely static spell meta we have now.

**Comment by Killette2** [comment]
It's only static if you don't want to have fun. Wizard is do whatever you feel like, not minmax.

**Comment by CptWad** [comment]
but now I can get 5smoke 5blink and buttbot so I can meme all over people

**Comment by ComicIronic** [comment]
And the new spell meta will only exist if people choose to not make fun picks, what's your point, TermedClepe?

**Comment by Killette2** [comment]
You can already make fun pics now, there's no reason to force new prices on the players when anyone can already pick any spell. It's your fault if you pick mutate every wiz round.

**Comment by ComicIronic** [comment]
People are still incentivised to pick the best spells because everything is an equal investment. If fun picks were cheaper, it would be less of a penalty to the wizards who went for them.

**Comment by Killette2** [comment]
I mean that is true, but lots of "fun/useless" spells are actually pretty damned good utilities.

arse nath is lethal, exploding someone without an ass does a fuck ton
double shoe snatch has the glass shard effect
horse mask can allow oxygen deprivation or n2o flooding
mime and clown curse are tactical for obvious reasons

these are all considered useless or fun spells

**Pull request merged**
