### PR TITLE
Revert "Reduces a lot of stuns"

### PR DESCRIPTION
**Pull request by ShiftyRail**
Reverts vgstation-coders/vgstation13#23093

This is a Bleeding-Edge experiment, so we will merge this revert in about a week and hold a vote.

### CODE REVIEW

**Comment by Diavill** [comment]
revert it fucking now

**Comment by Caboozles** [comment]
Lube is down to a 2-4 second stun with chems.
Tasers down to a 2-4 second stun with chems.
Water is literally 2 seconds with chems.

All this does is encourage massive powergaming. This solves nothing.

**Comment by Irradiation** [comment]
Here are some exciting test results:

WATER:
-With Synaptizine = 2-3 seconds
-With Synaptizine+Cytisine = 1-2 seconds

LUBE:
-With Synaptizine = 3-5 seconds
-With Synaptizine+Cytisine = 1-3 seconds

10 SECONDS STUNS
-With Synaptizine = 5-7 seconds, if you're too far, you might not have time to cuff.
-With Synaptizine+Cytisine = 3-5 seconds, if you're 5 tiles away from the guy that gets tased and you IMMEDIATELY rush and cuff him, he's get up as soon as you finish the last tick of cuffing.

**Comment by Irradiation** [comment]
That said, only the odd scinigger will have the time/autism/ressources to obtain Cytisine in appreciable quantities, so it's fair to say that Synaptizine+Cytisine is a massive fringe case that will probably never happen.

**Comment by small-boss** [comment]
If you already go for shit like Synap + Cyt why not just make a creatine mix?
I have never in my life seen someone actually use those chemicals, and even with these changes to stun time I do not think they will see any more use than before. 
Officers now simply have to baton a prep after tasing him if they want to reliably keep him down.

**Comment by ShiftyRail** [comment]
@Diavill Had it not been for the laws of this land I would have self-merged it

**Comment by Irradiation** [comment]
Also it turns out that if you're not El Sonic, slipping a guy with water and trying to cuff him is a very spooky thing now, due to how fast they get up.

**Comment by Diavill** [comment]
what the stun nerf pr basically did was cockblock any attempt at cuffing someone reliably well. The purpose of the nerfs was to reduce stun based combat but it basically made batonning someone mandatory if you ever want to cuff them without them popping up and unzipping their dick because baton stuns werent reduced

**Comment by Kammerjunk** [comment]
@small-boss synap is decent because of how easy it is to create
you do need 20u anti-tox per unit of synap, but that also means 1u synap lasts 3 minutes and 20 seconds

**Comment by ShiftyRail** [comment]
The only concrete consequence of this nerf that I can see right off the bat is that it is now even harder to escape perma, as water slip has been reduced and stealing a taser has less value 

I find it gayer than our sec force

**Comment by ShiftyRail** [comment]
One consequence of this is that the stun-implant dance is a lot more annoying to perform

**Comment by ShiftyRail** [comment]
Following Intigracy's example in #20472, I'm self-merging this revert while a poll to evaluate the proper impact of the change is up : http://ss13.moe/index.php/poll/193.

While there has been a poll running during the week of the experiment (http://ss13.moe/index.php/poll/191), I do not believe this was the correct way to gather feedback about this. This does not mean the results should be completely ignored, simply that I do not believe this was the proper way to handle the experiment.

You can use this PR to direct any suggestion of tweaking about the original PR.

**Comment by Irradiation** [comment]
Capture

**Comment by boy2mantwicethefam** [comment]
>self-merge

**Comment by bathosbathtime** [comment]
Did this have some form of changelog

**Comment by Exxion** [comment]
Definitely looks like "keep it" won both polls
Even though the choice to not merge it had the most votes, two separate choices said to merge it, and those together had more votes
By the way that's a pretty dirty tactic

**Pull request merged**
