### PR TITLE
Adds laceup shoes to the Shoelord 9000 and amish suits to the Suitlord 9000

### PR DESCRIPTION
**Pull request by ghost**
Someone mentioned to me it'd be nice to have them in the vendor seeing as you can't otherwise acquire them without traipsing off to the asteroid or looting your local IAA/Detective.  I couldn't think of a reason _not_ to add them!

### CODE REVIEW

**Comment by yclatious** [comment]
Wait, the ultra fancy IAA shoes? Dang, that's really nice, thanks for adding them.

**Comment by Riekland** [comment]
Speaking of IAA stuff, could we possibly get the black trousers and white shirt in the vendors? The IAA gets a set with a black tie and it's objectively the best looking jumpsuit in the game, I need one without the fucking tie give it to me

**Comment by ghost** [comment]
That'd be pretty rad, actually, but seeing as it's literally 'Internal Affairs Uniform' I'd probably not be able to get away with adding job-specific stuff to the vendor (unless nobody honestly cared).

Contraband? Premium? It is a pretty nice suit, after all.

**Comment by Blithering** [comment]
I think there's a version with no tie that spawns in the barman's back room. It's called the amish suit.

**Comment by ghost** [comment]
Can't believe I forgot that thing exists. Well, the Hatlord has top hats, so the Suitlord having amish suits should fit nicely. Good to merge, presuming Probe is okay with it.

**Comment by Kurfursten** [comment]
It doesn't matter that much but I'd add the shoes to the contraband list instead

**Comment by ghost** [comment]
I'll defer to your better judgement on that! People do love hacking the machines every opportunity they get, anyway.

**Comment by Riekland** [comment]
Ah ah ah, no, the amish suit has those gay puffy bits at the shoulder that make you look like an autisme
IAA gets a perfect, crisp white shirt

**Comment by ghost** [comment]
@Riekland I checked the uniform DMI for the IAA/barman/amish suits and they're the same, differences are generally the ties/belts. Barman has a little bowtie, IAA has a green tie, and the amish one has no tie.

(if you want something else though i could probably do it just say)

**Comment by Riekland** [comment]
what the fug
I might just be retarded then goddamn

**Comment by Probe1** [comment]
I'm hesitant to add many different security uniforms since security needs to be recognizable to everyone or else it's a random with a gun.

**Comment by ghost** [comment]
This is true. Different styles would be nice, but difficult without having them all similar enough in style to still be recognisable. Ah well.

**Comment by Blithering** [comment]
Keep uniforms uniform.

**Pull request merged**
