### PR TITLE
Steals the recorder sprite that's on every server but ours

### PR DESCRIPTION
**Pull request by Konater**
I saw a lot of these when I was mapping, old ones at the top in case you've never used one
old1
old2
old3
new1
new2
new3
interro

By all means downvote this if you don't want it in

### CODE REVIEW

**Comment by clusterfack** [comment]
You don't like the old one better?

**Comment by Konater** [comment]
If I did this PR wouldn't exist

**Comment by clusterfack** [comment]
The 'new' one you can't even see the buttons, nor the tape spinning.

**Comment by Konater** [comment]
I'd say it's pretty hard to miss in 2x but I forgot dylan still plays in 32x32

**Comment by PJB3005** [comment]
No issues seeing the buttons or tape here, big :+1: from me.

**Comment by Zth--** [comment]
I like the new one. Can't +1 because fuck mobile

**Comment by FudgePucker** [comment]
Goons looks diffrent

**Comment by Imagebard** [comment]
I'm sorry but I like the current one better.

**Comment by Shadowmech88** [comment]
I recognize that the new sprite is objectively higher-quality, and at the same time I would rather we keep the current sprite.

A regular recorder and a universal recorder are two different items, right?
What about giving the universal recorder the newer sprite?

**Comment by Imagebard** [comment]
I think all recorders are universal. Never seen a "regular recorder".

**Comment by Imagebard** [comment]
And I'd rather have the universal recorder use the old sprite and the normal recorder the new sprite.

**Comment by Konater** [comment]
It's pretty clear the majority don't like it, I wouldn't want it in even if yes barely won either

**Pull request closed without merging**
