### PR TITLE
changes the cost of the revolver from 13 tc to 12 tc

### LINKED ISSUE #22628: Change the cost of .357 revolver from 13TC to 12TC
It's shitty that when you buy the revolver for 13TC, you can only afford 1 additional box of ammo for 4TC and not 2 because you're short by 1TC for the second ammo box.

### PR DESCRIPTION
**Pull request by SirSkeleto**
[powercreep] [balance]

An item that you can get seven of with a space suit, welding goggles, and patience? 13TC? This also solves the issue of not being able to buy that 4 TC item that you can print at any hacked autolathe, in case that was a thing you wanted to do. I'm also gonna write a PR that makes that a lot cheaper too (how I'd go about fixing it), but some retard wanted this so here it is.
fixes #22628
also see #22631

:cl:
 * tweak: lowers the cost of "fully loaded revolver" from 13 -> 12 TC

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Just "tweak:" is okay

**Comment by SonixApache** [comment]
~~revolver murderbone is cheap and easy and overdone, no need to make it even cheaper~~
Yeah but mathwise it makes more sense I guess.

**Comment by agentofzog2** [comment]
This is bad logic since a large portion of the syndicate catalog can just be replaced with something found or made normally, the advantage is you get the item immediately and without having to do something suspicious.

**Comment by spoonylove** [comment]
Make it nine, so you can order two to akimbo with 2 reloads with the other PR

**Comment by SirSkeleto** [comment]
> Make it nine, so you can order two to akimbo with 2 reloads with the other PR

if this gets merged sure i'll do another
but no way in hell is the other pr getting merged lol

**Comment by Blithering** [comment]
Space suit and welding goggles? Lah dee dah rich man. Firesuit, bear pelt hat and sunglasses work just fine

**Pull request merged**
