### PR TITLE
Further fixes examining and pointing with right-click and restores a functionality

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Now you can properly right-click through walls as a ghost to examine and point at stuff.
Restores a forgotten functionality where you can now show your held item by pointing at it with right-click
-->
:cl:
 * bugfix: Now you can right-click examine and point at stuff from walls.
 * bugfix: Restored an old functionality that allows you to show off a held item by right-click pointing at it.
 * bugfix: Go nuts, you can now point at stuff while inside lockers, MMIs, mechas, whatever, using right-click commands.

### CODE REVIEW

**Comment by DamianX** [comment]
does this fix #20772?

**Comment by boy2mantwicethefam** [comment]
I think that could be a problem with how the AI eye works in the first place, wasn't aware of this issue. No, don't think it fixes that, considering that right-clicking is integrated I think the fix is to just not let the AI have these verbs over what it looks over to. You can thank byond for its integrated right-click function. I'll try to post on byond's forums for a possible solution

**Comment by boy2mantwicethefam** [comment]
Yea you know what nah, I expect some dumb response

**Comment by DamianX** [comment]
It used to be fine before it was changed last year.

**Comment by boy2mantwicethefam** [comment]
I'm going to rework this

**Pull request closed without merging**
