### PR TITLE
Fixed countless DNA related bugs, also including Vox and Grey genetic inconsistencies

### LINKED ISSUE #27909: UI+UE injectors have no effect on vox post-tailfix
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
4cc7a43be7c4d794b89b9a34c50ba5be7403b6bc

# Description
UI+UE injectors do not update vox sprites. Possibly related to recent colored vox tailfix.

# Steps to Reproduce
Clone vox for random apperance. Copy UI+UE from original body and inject.

# What you Expected
Clone takes apperance of original sprite

# What Actually Happened
Sprite unchanged

### LINKED ISSUE #28562: Vox UI Genetics are fucky
When cloned they all come out greenskinned, and you cant change their genetic skin color with genetics even if you copy the look of a differently colored vox. Injecting any non green vox with any UI syringe does nothing, however if you rejuvenate them after they become green as well for whatever reason.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #27909
Fixes #28562

Also taken this opportunity to remove the shameless spawn(1) I threw in #27949

:cl:
* bugfix: Genetics' DNA Modifiers can finally be used to alter Vox or Grey skin color, and DNA Injectors will properly copy appearances to them. (loppu & Dacendeth)
* bugfix: Fixed an old obscure bug where a DNA Injector would give you a different hair or beard than that of the mob whose DNA it was produced from.
* bugfix: Fixed a few instances where appearance modifications wouldn't properly update your DNA.
* bugfix: Fixed the admin Edit Appearance button and Magic Mirror listing hair or beard styles that your mob isn't compatible with (and that would be invisible anyway).
* bugfix: The Morph genetics power now works properly for non-human species. 
* tweak: When using a mirror or such to edit your appearance, the hair style and beard style that your mob are currently displaying will be selected by default in the list.

### CODE REVIEW

**Comment by SonixApache** [comment]
>Fixed the admin Edit Appearance button and Magic Mirror listing hair or beard styles that your mob isn't compatible with (and that would be invisible anyway).

not all of them were invisible
riot
(this is a joke)

**Comment by Eneocho** [comment]
I just wish you could store your original appearance so you could morph back.

**Comment by DeityLink** [comment]
Since the option selected by default (minus gender) is the one you currently have, you can at least note them down.

**Comment by Eneocho** [comment]
This reminds me, can you fix Ghouls being gene uneditable? Once you become a ghoul, you're stuck with all the disabilities you get from radiation and can't get gene scanned, cloned or anything. It is a very big limit to a species that requires a whole scientific ritual to achieve. See #30084. It'd require removing the NO_CLONE flag upon ghoulification.

**Comment by DeityLink** [comment]
Not in this PR.

**Comment by Eneocho** [comment]
> 
> 
> Not in this PR.

This implies it can/will happen in the future and that's good enough.

**Pull request merged**
