### PR TITLE
Reagent addiction/tolerance system, take two

### PR DESCRIPTION
**Pull request by ghost**
[content][system]
Adds support for these, this time without any effects so that they can be added on a case-by-case basis atomically. Currently no reagents have addictive properties yet.

:cl:
 * rscadd: Reagents can now have the property to become addicting or build up a tolerance when consumed. Addiction causes withdrawal affects while tracked when the reagent is not in system and tolerance increases the minimum amount needed to affect a mob, without changing the overdose threshold.

### CODE REVIEW

**Comment by Eneocho** [comment]
You added the tolerance system to ethanol, add it to the CL.

**Comment by ghost** [comment]
> You added the tolerance system to ethanol, add it to the CL.

Everything has it, but I'm open to leaving it whitelist only.

**Comment by Kurfursten** [comment]
Still a tough split. But since this is harmless until actually implemented, I'll break in favor of the merge.

**Comment by godietxt80** [comment]
oh my god you actually pushed it

**Comment by Eneocho** [comment]
You sneakycoder'd some tolerance to hyperzine, space drugs, oxycodone, tramadol and ethanol, come on man. You've been told before.

**Comment by Eneocho** [comment]
> Still a tough split. But since this is harmless until actually implemented, I'll break in favor of the merge.

It is on all chems, not a whitelist, but rather all chems suffer from tolerance now (1/10th their metabolic rate). There's even dedicated specific values for the hyperzine, space drugs, oxycodone and ethanol (and thus all alcohols), it will affect chem considerably.

**Comment by djkramer123** [comment]
kuuuuuuurf

**Comment by Kurfursten** [comment]
It's a 50% split, someone had to make a call.

Let's see if it literally destroys medbay or if no one can tell the difference in one week.

**Comment by jwhitak** [comment]
I didn't actually see this get upvoted so highly... This is a strict numbers nerf on chemicals (both good and bad chemicals). They are only 90% as effective now vs beforehand (ex: 10u bicard pill, only 9u will heal). This stacks, so shoving another pill with no time between will mean 18u/20u will work.

This includes nutriment. You need more food now.

**Comment by Eneocho** [comment]
Revert it and add the system WITHOUT the tolerance system enabled. It's supposed to be a frame.

**Comment by bathosbathtime** [comment]
For the record, the call should have been to close the pull request.

**Comment by Eneocho** [comment]
Agreed.

**Pull request merged**
