### PR TITLE
Removes Nuke Revs/Revs Wizs

### PR DESCRIPTION
**Pull request by ShiftyRail**
People that already got an antag role shouldn't get a second one at roundstart.

### CODE REVIEW

**Comment by Accipitermaris** [comment]
extremely detailed & in depth counter argument: i once rolled blob vamp

**Comment by ShiftyRail** [comment]
This shouldn't be possible, as roundstart rulesets are supposed to prevent that, I'm just applying it to delayed ones

**Comment by Irradiation** [comment]
Remove [Blob]-[X antag] while you're at it.

**Comment by DrSnips** [comment]
Better idea that solves that. Remove blob entirely

**Comment by Intigracy** [comment]
2 wizards spawn
1 is revhead
Immediately flashes other wizard

**Pull request merged**
