### PR TITLE
'Summon Hardsuit' won't delete worn items anymore

### LINKED ISSUE #16795: Bound object and Summon robes suit storage
(WEB REPORT BY: tugamix666 REMOTE: 172.93.109.202:7777)
# Revision
bb83beadcbce952295d60e10cdbc2bc2f7d63d1c

# Description
upgraded summon robes spawns a oxygen tank in your suit storage, and removes whatever you had in there forever, making it unable to be called with bound object
# Steps to Reproduce
be wiz get upgraded summon robes, put something (in this case a staff of change) into your suit storage and cast summon robes
# What you Expected
to not lose the staff of change to the void
# What Actually Happened
it went poof, unable to be called with bound object

### PR DESCRIPTION
**Pull request by DamianX**
Closes #16795

### CODE REVIEW

**Comment by gbasood** [comment]
Wouldn't this now not replace robes?

**Comment by DamianX** [comment]
It will still replace them, but it will drop the old items at your location instead of deleting them.
```
if(delete_old)
  qdel(old_item)
else
  old_item.forceMove(L.loc)
```

**Comment by DamianX** [comment]
Now that I think about it, we might want to call the procs to unequip items in there.

**Comment by gbasood** [comment]
maybe

**Pull request merged**
