### PR TITLE
Holding a flashbang while it goes off voids your flashbang protection

### PR DESCRIPTION
**Pull request by 9600bauds**
Sound from flashbangs already stuns you briefly even through full protection if you're within 2 tiles, this makes it so that suicide bombing with a flashbang in hand gives you the full stun time instead.

:cl:
 * tweak: Flashbangs now further ignore ear protection if you hold them while they go off.

### CODE REVIEW

**Comment by Probe1** [comment]
/shrug

seems ok to me but i am a very big fan of flashbang suicide bombing so this will negatively affect my play style.

**Comment by yclatious** [comment]
I personally don't see why a nerf to the good sec officers who are desperate enough to flashbang suicide is a good thing, thematically it doesn't make much sense either, someone with eyeglases, a helmet or hardsuit helmet and ear muffs should naturally be more resistant to the effcts of a flashbang than a random greyshit that starts yaketi saxing like the best of them after having toolboxed the clown, stungloved the cap and stolen his ID.

Flashbangs are already a rather underused item and to me, nerfing their ease of use seems a bit odd, its a nerf to a good item that could stand to be used a lot more, they should be encouraged, not nerfed in my opinion.

**Comment by 9600bauds** [comment]
Thematically speaking it makes all the sense in the world that a shockwave-based effect, which has dropoff with range, would be the strongest if you were holding the damn thing. In real life, holding a flashbang while it goes off can KILL you. 

The "bang" part of the flashbang already works like this, with flash protection but not ear protection it will only stun you for 4 seconds rather than 10 if you were far away enough. Even with full ear protection it will still stun you for 2 seconds if you're within 2 tiles. A longer stun for being even closer is only keeping with the theme of what is already in the game right now.

I use flashbangs every single time I play Security Officer, I don't see them as being underused in the least, in fact if anything they are a little cheap. They are a screen-wide AoE stun (if you think THAT's underused you're nuts), I find that their ease of use should be a little harder than to allow allahu-ackbaring with a grenade.

**Comment by yclatious** [comment]
I say thematically but I mean within the whole level of "realism" we have in ss13, wizard are still a thing, people still survive from repeated, massive concussions to the head from toolboxes and will only go down from the 6th one instead of the 3rd, we allow all of this, so I didn't and don't see much reason to start making people die from em, or to make it so the guy with all the protection he can get gets as screwed as the dude that has none, because unless I am remmebering wrong, even if he might be at the edge of the screen, he will still get up slightly later than you.

I mostly used them as suicide tools since I both never could tell when they would blow and because randomly as sec, my internet decided to shit itself, making it rather embarassing to play sec as, but atleast halfway effectively, even with the lag. If you do believe its cheap as fuck, I wont try and change your mind, I think they are effective and do the job right, but ill still disagree with the pr. Good on you for using em though, back when I used to play a lot more sec, I never saw them getting used by my fellow redshirts, so thanks for being effective.

**Comment by 9600bauds** [comment]
Of course, I'm not about to make people die from flashbangs

**Comment by yclatious** [comment]
I said die from em and so on but I meant that as in the general idea of making people lose their edge with protection being about the same as dying from em, since we already allow a certain level of crazy shenanigans, I didn't see the point of adding either, and they seem about the same in terms of "severity", ss13 was never about hard reality or aplying realism.

Relax, I wasn't implying youd make people die from holding flashbangs, nobody here is that dumb.

**Comment by Huuuuuuuuuuugo** [comment]
>Assisstant yakiet saxes down central hallway
>Still in frame of him
>Secboy chasing after him
>Taser no chargo
>lol bolas
>Hold flashbang in hand till it goes poof
>Assistant and Secboy go horizontal
>Secboy gets up before assistant, gets the stun baton on him and arrests
>Perp in custody

NOW

>Assisstant yakiet saxes down central hallway
>Still in frame of him
>Secboy chasing after him
>Taser no chargo
>lol bolas
>Hold flashbang in hand till it goes poof
>Assistant and Secboy go horizontal
>Assistant and Secboy get up at same time, yaketi sax continues on

OR

>Throw Flashbang at Assistant
>Assistant sprints out of frame and range of flashbang
>Secboy still in frame and range of flashbang
>Secboy goes horizontal
>Assistant speeds off into maint land
>Perp escapes custody

MAGNIFICENT DESIGN

**Comment by 9600bauds** [comment]
Cook your grenades, man. You don't even go horizontal if you threw it more than 2 tiles.

Alternatively, use them for room breaching

**Comment by Huuuuuuuuuuugo** [comment]
>Room breaching

When has this ever truly happened
I can only guess cult but the second they see/hear the door open it's skidaddlin time
Bonus points if you throw it on but the nade gets caught on the very last frame of the opening animation

**Comment by 9600bauds** [comment]
Tailgaters/B&E, mostly

**Comment by Shadowmech88** [comment]
Currently flashbangs are nearly a straight upgrade to tasers. They stun everyone on the screen, don't require aiming, and all the officer has to do is keep the target in sight until it goes off in his hand. They can even be combined with a taser to stunlock everyone in the room once the flashbang stops them from moving.
I think the current behavior is bad design. Flashbangs should be more of a sidegrade to tasers. Larger area of effect, a bit more difficult to apply.

At least now the officer will have to put some thought into when and where they throw the flashbang rather than just activating it and chasing the target.

**Comment by Probe1** [comment]
@Huuuuuuuuuuugo I have no idea what you'd call most flashbang usage except for breaching a fortified position.  I mean yeah sometimes I throw them at the clown cause its funny but 9/10 times I'm throwing them because someone traded mobility for a defensive advantage.

**Comment by 9600bauds** [comment]
I think Shadowmech88 hit the nail in the head here. Being able to suicidebomb with flashbangs is crummy design and crummy balance. I say this as someone who often suicidebombs with flashbangs and man, is it cheap, but it's so good I'd be an idiot to not do it.

**Comment by Intigracy** [comment]
You can still suicidebang if you throw it at the last second, you just need to put a tad more effort into it.

**Comment by 9600bauds** [comment]
There is a valid point to be made that it's a little bit risky to do so because of BYOND time and features, but then again this was the case for all grenades except flashbangs until now. You couldn't cock up flashbangs before.

**Comment by Probe1** [comment]
Why throw it?  That involves pressing R and clicking?

Just press Q.  

@9600bauds does this cover if you're on the same tile as it or only if it's in your hand?  If it does then you can basically just drop it at the last second.  But it also means that hitting someone directly with a flashbang would be like a critical hit.

**Comment by 9600bauds** [comment]
Only if you're holding it

Dropping it at the last second seems like a worse "throw it at the last second"

**Comment by Intigracy** [comment]
Activating grenades automatically activates throw mode.

**Comment by Probe1** [comment]
Custom vote started by Kavlax.
Holding a flashbang while it goes off voids your flashbang protection: Y/N?
Type vote to place your votes.
You have 60 seconds to vote.

Vote Result: Yes holding a flashbang as it explodes should void protection with 12 votes
	No holding a flashbang as it explodes should not void protection had 2 votes
	Who cares. had 2 votes

**Comment by Probe1** [comment]
Make sure you update the wiki so people don't think it's a bug.

**Comment by 9600bauds** [comment]
http://ss13.moe/wiki/index.php/Security_Items#50px50pxFlashbang

**Pull request merged**
