### PR TITLE
fixes the raider shuttle not being able to move to vox outpost on deff

### PR DESCRIPTION
**Pull request by Intigracy**

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by Intigracy** [comment]
Forgot the area.

**Comment by Konater** [comment]
This shouldn't be an issue I cut the pointy bits off of the skipjack and tested it ages ago
You might want to check that button to lift the bolts is still there on the skipjack

**Comment by Intigracy** [comment]
The pointy bits are still very much on the skipjack.

**Comment by Konater** [comment]
Is the door control button on it? It's likely someone copied and pasted the ship over if they were trying to fix something on all maps.

**Comment by JustSumBody** [comment]
image
This is the deff skipjack
If I had to guess, Wad's centcomm changes copy pasted the skip. Or an outpost change? Who knows

**Comment by Konater** [comment]
cptwad why

**Comment by Intigracy** [comment]
The pointy bits are still very much in the skipjack.

**Comment by Konater** [comment]
The bottom airlock's bolted and the button to unbolt it was removed, at least raiders spawn with tools

**Pull request merged**
