### PR TITLE
Adds a crossfade mode to songs for the jukebox.

### PR DESCRIPTION
**Pull request by ShiftyRail**
This doesn't do anything yet, but this allows our DJs or anyone using the jukebox system to do sick crossfades if they specify it so.

The way it is done is really pretty dumb, you have two players and they just take turns playing songs. 
There is no other way to do it, VLC can't do crossfades on its own.

I'll test it locally using my collab powers to get the config files from the secret repo.

Once I'm sure this doesn't break anything jukebox-wise, I'll see if I can add some songs with a programmed crossfade and test it again.

Tell me if I did it wrong.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
This is actually working a lot easier and neater than I expected. I still have a few tests to run but this doesn't break the jukebox at all, in itself. There is an issue if you switch songs too fast, which I *think* I fixed but can't test tonight.

**Comment by ShiftyRail** [comment]
Working as intended. A bit of it is shitcoded, but it's needed to get around the limitations of the `process` thing and ensure the audio is sent as soon as possible, and also to make sure we can stop music, wait for it to be stopped, and push another.

**Comment by DamianX** [comment]
Did you test this with WMP?

**Comment by Kurfursten** [comment]
As Damian requested, test with WMP

**Comment by ShiftyRail** [comment]
WMP doesn't play as nice with resuming songs when they left :(
VLC works fine, the crossfading works well, and doesn't really mind resuming a song when it's playing, however WMP really can't seem to pick up a song at a given time. 

I think it was already the case before, but it would just abruptly cut off the long before switching to the other if the user exited the room and went back.

With this system, it will play the two songs one over the other for much longer than wanted. The only way the user can stop it is to exit the room and enter it again, but it breaks everything on the next crossfade.

**Comment by DamianX** [comment]
Just disable it entirely for WMP

**Comment by tuypo1** [comment]
Is this like multi track listening or something?
https://www.youtube.com/watch?v=N2CKKV4Z44A

**Comment by ShiftyRail** [comment]
@tuypo1 not really, though you could do something similar.
The real reason is something a lot more boomer and simple : most music tracks end up with a slow fadeout, especially the ones that got released in the 70-80's.  The next track is loaded and starts to play during this fadeout.

This was done order to let DJs queue up the next song and raise its volume while the old one was failing. Real DJs don't exist anymore, it's all pre-programmed tracks, but this kind of song outro is still pretty popular for compilations or in titles played by 24/7 music stations because you never let the ear of the listener rest, it's very effective to catch their attention.

Even without a fadeout time, if the outro of your song is a straight cut (or something that isn't meant to have sound playing over), this system let the other song play straight away instead of waiting on byond time and VLC loading the track. I tested it, it was pretty cool.

**Comment by ShiftyRail** [comment]
currently untested. Will report back tomorrow.

**Comment by ShiftyRail** [comment]
Now tested, compiled, and working. Feature is disabled on WMP.

**Comment by tuypo1** [comment]
Neat

**Pull request merged**
