### PR TITLE
Grayy Rig Sprite Updates v4

### PR DESCRIPTION
**Pull request by Optimism333**
## Ayy Lmao (Final version to disintegrate all conflicts.) ##
I did my best to make some edits to improve the overall appearance of the worker and leader rigsuits. I hope experienced spriters will forgive my amateur work. Thanks to Blithering for making the original sprites and therefore making this pr a possibility.

 * The worker rigsuit now has a hardhat to better differentiate it from the researcher rigsuit (old and new comparison below). I also improved the butt shading on the rear view sprite.
Screenshot (341)
Screenshot (347)

 * The Leader rigsuit has been redesigned with more uniform coloration, bigger shoulder pauldrons, and a bubble dome helmet instead of the previous partial dome. (old and new comparisons below) 
Screenshot (342)
Screenshot (344)
Screenshot (343)
Screenshot (345)

 * Sprites for the rig helmets in their item states and with flashlights on were also updated.

:cl:
 * The Grayy worker and leader rigsuits have had their appearances updated.

### CODE REVIEW

**Comment by Optimism333** [comment]
@Kurfursten Conflicts should be fixed in this version.

Edit: Not sure why some checks failed. Let me know if I need to do something on my end to fix that.

**Comment by Jackreturnswithaveangenace** [comment]
I think you need to start fresh with a fully up to date branch off the bleed-edge, then import only those sprites you're added to the dmi's and see what happens then. I compared your dmi's vs my up to date versions of the dmi's and it's missing a chicken suit, which suggests you might be using an older image set.

No idea if that will actually fix it, but the error you're getting in the travis is a fairly generic "failed to execute" error, so starting with a clean slate might help anyway.

**Comment by Kurfursten** [comment]
Jack is basically right, the errors you're seeing are because you're rolling back changes in other files as you didn't fetch the latest version of the repo.

**Comment by Optimism333** [comment]
I fetched the latest version, and that seems to have fixed the issue. I'm pretty sure the sprites should be fine, as there's no .dmi conflict, and I did see the new chicken suit in the files when I checked.

**Pull request merged**
