### PR TITLE
Vampire nerfs

### PR DESCRIPTION
**Pull request by unid15**
- Hypnotise costs 10 blood (up from 0)
- Bat form costs 30 blood up from 0 (like before #2583)
- Chiroptean screech costs 30 blood up from 10 (like before #2583)
- Shadowstep now costs 20 blood up from 0

:+1: / :-1: ?

### CODE REVIEW

**Comment by CptWad** [comment]
Switch hypno with glare since glare works through anything
having to ONLY use glare at the start would be real hard for jobs that don't have access to chloral or the trust of the crew

**Comment by ihadtoregisterforthis** [comment]
:suspect: 
Powers using up blood changes the way it's played. I imagine that forces players to either actively hunt necks, have a consistent lair of monkeys, or stockpile and make a suicide rush. But there will sure be more action coming from them.

**Comment by AutismSpider** [comment]
shadowstep/Bat form should cost bit more then that try like 40 or 30

Chiroptean screech should be 50 or 100 it only stop by one item that makes you deaf to all sounds

**Comment by Kurfursten** [comment]
I think we should go back entirely to pre-Kilkun vampire costs meaning 20 blood instead of 10, AND return 50 blood cost to Shapeshift

**Comment by AutismSpider** [comment]
bat form should have its old cost of 50 blood shadowstep 30

**Comment by TermedClepe** [comment]
I like how this doesn't address getting full power in literally 5 minutes if you start as geneticist.

**Comment by Imagebard** [comment]
>Powers using up blood changes the way it's played.

You mean that it returns to the old way its played. The way it was meant to be played.
Either way, :+1: to returning vampire blood costs. I don't know how this shit stayed unfixed for such long time.

**Comment by ghost** [comment]
Looks good to me. Right now Vampire rounds end up with either all vampires valid within ten minutes or a nigh-invincible fuck just running around killing everyone

**Comment by CptWad** [comment]
I'll update the wiki once it gets merged.

**Comment by icantthinkofanameritenow** [comment]
All this sounds good to me as well.

**Comment by CptWad** [comment]
*WHEN*
also, heres  #7724

**Comment by clusterfack** [comment]
To me it seems chiroptean screech should cost a lot considering it wrecks absolutely everyone. 

And shadowstep/bat form should be less costly considering they make the vampire much more surviveable.

But it doesn't really matter to me

**Comment by CptWad** [comment]
@clusterfack Hell we can always change it again. This just re-adds blood costs. If it needs changing we will change it. Just later. After the ice melts and the features return for spring

**Comment by CptWad** [comment]
If I update the wiki now will this get merged?

**Comment by clusterfack** [comment]
Whatever let's do it

**Comment by CptWad** [comment]
shit but I am not home to update wiki, ill do it soon (tm)

**Comment by 9600bauds** [comment]
feechur frees

**Comment by Imagebard** [comment]
It was made before the future freeze you dork

**Comment by clusterfack** [comment]
It's not like he developed it during the freeze unless CELTY

**Comment by Kurfursten** [comment]
It's also balance not a feature but whatevs

**Comment by CptWad** [comment]
wiki updated :book:

**Pull request merged**
