### PR TITLE
Sepia cores now stop time when injected with phazon

### PR DESCRIPTION
**Pull request by SonixApache**
"Sepia will now stop time in a somewhat large radius for a few seconds when injected with phazon"

#14770, but without money changes.
Changelog included in files.

### CODE REVIEW

**Comment by DrSnips** [comment]
Why not just merge the other one? Economy hardly matters outside of a line drawn at 300 credits (can a common person afford it round start or not by themself).

**Comment by SonixApache** [comment]
something something slot machine out of thin air

**Comment by ghost** [comment]
something something instant 10k out of thin air

**Comment by DrSnips** [comment]
Yeah, slot machine is a bit over the top.

**Pull request merged**
