### PR TITLE
Map fixes

### PR DESCRIPTION
**Pull request by Probe1**
Fixes https://github.com/d3athrow/vgstation13/issues/6898 by adding the HoS jacket that somehow we've come to believe belongs to the HOS
Fixes an unreported junction sorting HoS packages into the Theater Backroom.  Honk.  https://github.com/d3athrow/vgstation13/pull/6907#issuecomment-162567860

https://github.com/d3athrow/vgstation13/issues/6805 Adds deskbell to medbay  https://github.com/d3athrow/vgstation13/pull/6907#issuecomment-162566696
https://github.com/d3athrow/vgstation13/issues/6580  Adds deskbell, windoor, and coins to cargo https://github.com/d3athrow/vgstation13/pull/6907#issuecomment-162567071
https://github.com/d3athrow/vgstation13/issues/6580  Adds belts and blast doors for cargo like on other maps https://github.com/d3athrow/vgstation13/pull/6907#issuecomment-162567071

Closes https://github.com/d3athrow/vgstation13/issues/6845 https://github.com/d3athrow/vgstation13/pull/6907#issuecomment-162567355

### CODE REVIEW

**Comment by Probe1** [comment]
image

**Comment by Probe1** [comment]
I named it the beltanator

image

**Comment by Probe1** [comment]
image

**Comment by Probe1** [comment]
image

**Comment by Probe1** [comment]
I seriously hate conveyors.  Unlabeled, identical icon, hell.

**Comment by PJB3005** [comment]
ITT: Why all you fucks should never make an instance ever again.

**Comment by Probe1** [comment]
Couldn't get the stupid shit to work.  The beltanator dream is dead.  Now it is just a straight line.

**Comment by 9600bauds** [comment]
Dear probe
You gotta modify the belt's variables
If someone can build it in a live round, you can do it in the map editor

**Comment by ihadtoregisterforthis** [comment]
Why not invent slower conveyors?

**Comment by PJB3005** [comment]
@Probe1:
1. make subtypes
2. set `reverse = 1` on the misbehaving corner one.

**Comment by Probe1** [comment]
@9600bauds I tried, while checking it out in game one of the fucking conveyor pieces made my client crash.  I don't want to look at them again I've had enough.

**Comment by Kurfursten** [comment]
Might be nice if the belt ended in a chute to the mail line - if you can manage the space.

**Comment by N3X15** [comment]
We really need a conveyor resprite with arrows on the belt itself.

**Pull request merged**
