### PR TITLE
Fixes vaults spawning on top of each other

### PR DESCRIPTION
**Pull request by unid15**
0% tested but probably works but who knows what might happen

I'll test later

### CODE REVIEW

**Comment by Probe1** [comment]
2qnqf2y

**Comment by ghost** [comment]
My kind of PR 👌🏻

**Comment by ComicIronic** [comment]
The only thing it looks like this does is reverse the arguments of `block`.

**Comment by unid15** [comment]
Currently the area in which you can't place a vault is (vault_x-80, vault_y-80, vault_z to vault_x, vault_y, vault_z)
This makes it (vault_x-80, vault_y-80, vault_z to vault_x **+ vault_width**, vault_y **+ vault_height**, vault_z)

**Comment by ComicIronic** [comment]
So why is it that I can't put another vault 80 tiles to the left or down from a vault, but as close as I want to the right or up?

**Comment by unid15** [comment]
It's a very dirty trick to make the code faster. When spawning a vault, the code gets its height and width, and for every already spawned vault - a rectangle of (old.x - new.width, old.y - new.height TO old.x + old.width, old.height) is marked as an invalid location for a new vault.  Because new.width and new.height would be different for every new vault, this had to be calculated a lot of times

This was very slow when used on big areas and took about two minutes to place 18 vaults, so I made this cheat that substitutes new.width and new.height with the number 80, so the list of invalid locations can be generated much faster and only once

**Comment by ghost** [comment]
@unid15 What if you made a vault that was 100 tiles wide and high? Wouldn't it be better to use the vault datums to define their height and width?

**Comment by unid15** [comment]
Then you'd have to build a separate list of invalid turfs for every vault, which can get fairly slow on huge maps with lots of them. If you assume every one is sized 80x80, you can do the job much much faster

**Comment by unid15** [comment]
100% tested

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
