### PR TITLE
Changes some typepaths

### PR DESCRIPTION
**Pull request by unid15**
/obj/screen -> /obj/abstract/screen
/obj/Overlays -> /obj/abstract/Overlays
/obj/fire -> /obj/effect/fire
/obj/lightribbon -> /obj/effect/lightribbon
/obj/map -> /obj/abstract/map
/obj/skeleton -> /obj/structure/skeleton
/obj/poutineocean -> /obj/structure/poutineocean

tested

### CODE REVIEW

**Comment by PJB3005** [comment]
A possible consideration could be to move `/obj/abstract` into `/atom/movable`

**Comment by unid15** [comment]
Then it's not going to show up in dream maker's object view

**Comment by PJB3005** [comment]
True but you don't need screen objects in the object view do you?

**Comment by unid15** [comment]
I would if I wanted to find their code

Tested and couldn't find any issues

**Comment by ComicIronic** [comment]
The mapping object tree shouldn't really be relied on for code-finding - it doesn't list datums and there's no reason for lots of stuff to be on it in the first place.

**Comment by unid15** [comment]
no more conflictos

**Comment by ComicIronic** [comment]
tgstation has 30000 changes

**Comment by ComicIronic** [comment]
:clap: tgstation no longer has 30000 changes. Is this ready?

**Comment by unid15** [comment]
Yes  it is

**Comment by Probe1** [comment]
Remember that time you added a dirty map edit to tgstation and I merged it wasn't that fun lets never
do
that
again

**Pull request merged**
