### PR TITLE
Restricting Summon Guns/Magic/Blades to roundstart wizards only

### PR DESCRIPTION
**Pull request by DeityLink**
:cl:
* bugfix: Once again, only roundstart wizards may summon guns, magic, or blades.

### CODE REVIEW

**Comment by SGuivenne** [comment]
Mark this for controversial, its effectively another bit of the same vote thing going on with the other wizard nerf patch.

**Comment by DeityLink** [comment]
It's basically reverting to how it was until Datums were merged like two weeks ago. You guys can tweak it afterwards, but here it's a bugfix.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It's not controversial until there's controversy

**Comment by Gringonius** [comment]
Wouldn't making a version of those spells that did not create survivors for mid-round wizards be a better solution?

**Comment by ShiftyRail** [comment]
What is the whole point of summoning things if not to create chaos/antags ?
I personally don't see much wrong with those spells. Perhaps the weapons distributed shouldn't be as strong, and the proportion of antags smaller.

**Comment by Gringonius** [comment]
To give the wizard a bigger challenge, to give shitter wizards guns to loot from the crew, to enable fun since antags don't have to go for their texts or murderboning everything.

**Comment by DeityLink** [comment]
sneaking in some new logo icons for the survivor roles: 
image

**Comment by DeityLink** [comment]
@Gringonius see now, what you're asking for is actual balance changes. Here I'm just fixing a bug.

**Comment by Kammerjunk** [comment]
@ShiftyRail roundstart wiz summoning antags 5 times isn't quite the same as that happening several times
Summon X spells aren't given to Ragin' Mages, only to roundstart wiz, but if a wiz can fire midround then what even is the difference

**Comment by DeityLink** [comment]
@Kammerjunk The point is that all the wizards that are able to use it should be spawned at roundstart. Someone getting spawned as wiz midround is much more likely to Summon X if they can.

**Comment by Hoshi-chan** [comment]
Now close the one that tries to nerf SoC and summon spells on the grounds that they're ruining rounds due to latejoin wizards and ragin mages.

**Pull request merged**
