### PR TITLE
inventories you're viewing no longer close when you move (if you stay in range)

### PR DESCRIPTION
**Pull request by nervere**
## What this does
Ever alt-click a storage container, then move around (while staying within one tile of it)? You probably noticed it closed the inventory view. Why does it do this? No particular reason, and it sucks! Now, provided you're within a one tile range of any inventory while viewing it, this will no longer happen.
## Why it's good
Inventories closing when you're still in range is extremely annoying.

[qol]
## Changelog

:cl:
 * rscadd: Inventories you're viewing will no longer close when you move around, provided you stay within a one tile range of them.

### CODE REVIEW

**Comment by DamianX** [comment]
Is `Adjacent()` more appropriate? Things may be in `view()` but still unreachable, for example if they're behind a window.

**Comment by nervere** [comment]
Good call, I'll change that in a bit.

**Review by Kurfursten — CHANGES_REQUESTED** [review]
adjacent

**Comment by nervere** [comment]
@Kurfursten Done.

**Review by Kurfursten — APPROVED** [review]

**Pull request merged**
