### PR TITLE
Revert "Revert "Revert "Minor fix for explosive chemical reactions"""

### PR DESCRIPTION
**Pull request by kilozombie**
Reverts vgstation-coders/vgstation13#17160

### CODE REVIEW

**Comment by Chazach** [comment]
can you smelelelel what the PJB is closing

**Comment by ghost** [comment]
oh I can fucking smell it alright.

**Comment by Kurfursten** [comment]
What a time to be alive

**Comment by kilozombie** [comment]
Github is a dictatorship, but it can't hurt to try and shout a little.

**Comment by yclatious** [comment]
VIVA LA C*DERV*LUTI*N

**Comment by small-boss** [comment]
wow still not closed

**Comment by TheFriggenSawbones** [comment]
i swear to fucking god ill finish what i shouldve started and genocide the coders

**Comment by kilozombie** [comment]
The reason for this revert:
PJB and N3X don't feel like they should follow any order or rules and are self-merging and merging each other. Continually shutting down discussion and dissent is enough to make me think they should be removed as collabs, but I don't remotely have that power, so the best I can actually do is try to demonstrate how and where they're doing what I just said.

**Comment by Chazach** [comment]
yamero

**Comment by TheFriggenSawbones** [comment]
I agree with Kilo 100%. The change seemingly came from nowhere and so far the collab response has, for the most part, been shitty.

How about we revert N3xis thing and work with whatever pjb's doing later.

**Pull request closed without merging**
