### PR TITLE
Reduces Cult weight to 2, down from 3 - 2, electric boogaloo

### PR DESCRIPTION
**Pull request by Kharkov72**
"If #23198 got reopened and got the same support, it would get merged"
this is that
[role][gamemode]

:cl:
 * tweak: Cult's weight has been lowered, making it less likely to roll at roundstart.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
wow

**Comment by utilitas-** [comment]
Why the fuck did this not get merged in the first place?

**Comment by tuypo1** [comment]
Because cult isn't as constant as you people make it out to be

**Comment by FudgePucker** [comment]
>Because cult isn't as constant as you people make it out to be

:joy: :joy: :joy: :joy:
Oh btw, its cult

**Comment by Irradiation** [comment]
Oh look, this PR roughly has the same support as the previous one

**Comment by utilitas-** [comment]
Oh look, it's almost like cult still happens way too often. You'd know that if you would play the game.

**Comment by SonixApache** [comment]
it's almost like any gamemode seems to fire too often when we only have like 5 of them

**Comment by tuypo1** [comment]
Yeah, we really need to port gang or something

**Pull request merged**
