### PR TITLE
Cafe & Bar crates for cargo

### PR DESCRIPTION
**Pull request by NigglyWiggly**
Adds a 20 credit crate with a brewer board, 10 mugs, and a kettle, and a
40 credit crate with booze and soda dispenser boards, 10 drinking
glasses, and a shaker.

Thanks again to FudgePucker for making the boards!

### CODE REVIEW

**Comment by FudgePucker** [comment]
Maybe have a way for the kettle color to be randomized instead of always red.
There are multiple different colors for kettles, it would be a shame if they went to waste.

**Comment by NigglyWiggly** [comment]
I tried to set that up, but couldn't get it to work right. I might just be dumb, but this is probably the best I can do with it

**Comment by FudgePucker** [comment]
Maybe make a new kettle that is random,.
Like how the exotic seeds are.

**Comment by NigglyWiggly** [comment]
That's what I did.
I gave all the kettle a colour var, assigned the appropriate color to each different version, and made a random one that would pick from the colors when it was spawned. It always just showed up with no icon though

**Comment by FudgePucker** [comment]
Well poop.
Red is alright I guess.
Maybe have one out in space as a joke.

**Comment by AutismSpider** [comment]
odd when the kettie were spawn in by admins i got green and purple one.

**Comment by NigglyWiggly** [comment]
Yeah, there's a red, blue, green, and purple one

**Comment by FudgePucker** [comment]
I can't wait until this gets merged so I can have tea partys.

**Comment by FudgePucker** [comment]
Is there some conversation going on in msay or the IRC?
This hasn't been merged yet and there is no converstation going on how this could be problematic or anything.

**Comment by ComicIronic** [comment]
Did you do

    /obj/item/weapon/reagent_containers/glass/kettle/random/New()
        ..()
        icon_state = "kettle_[pick("green", "blue", "red", "purple")]"

**Comment by NigglyWiggly** [comment]
Nah.
The different colors of kettles are actually entirely different kettles, because I'm dumb. So I essentially copied and pasted the random lipstick code to this and changed the details to make it work, but it didn't end up working so I scrapped it and went with red.

**Comment by FudgePucker** [comment]
Woo tea parties are go.

**Pull request merged**
