### PR TITLE
Adds winter spellbook to game and makes some old christmas spells a bit more presentable

### PR DESCRIPTION
**Pull request by Arthurdentist**
This PR adds a new spellbook for wizards, the Winter Spellbook. This Spellbook operates similarly to the Ancient Spellbook, and is only available through the Spellbook Bundle. If you are lucky enough to find one, you'll be able to learn one of four random christmas spells with which you can terrorise the crew.

I also tidied up the Wrap Spell and the Snowmobile spell a bit, giving them invocations that are more in line with the other spells we have, and also fixing a bug where the wrap spell didn't have a name. Finally the Wrap Spell is now a 'wait for click' spell, and doesn't use an old style menu when casting. 

:cl: 

- rscadd: Added a new spellbook, available from the spellbook bundle.  If you are lucky enough to find it, the winter spellbook will grant you one of four, Christmas-themed spells that are otherwise only available during Christmas.

### CODE REVIEW

**Comment by Arthurdentist** [comment]
lighter

spellbook sprite courtesy of @NigglyWiggly

**Comment by MadmanMartian** [comment]
Don't suppose you can add some spell aspect flags to these while you're at it?

**Comment by Arthurdentist** [comment]
@MadmanMartian I think that is better handled by a different PR ultimately, for the reasons we discussed on discord.

**Comment by jknpj** [comment]
@Arthurdentist update wiki

**Pull request merged**
