### PR TITLE
Sounds update part 1 of ?

### PR DESCRIPTION
**Pull request by Zth--**
## Added sounds
- [You are a Vampire](http://puu.sh/lpAlc/3c551d0ffe.ogg)
- Shutter doors ([open](http://puu.sh/lpxCf/715fd0009f.ogg) and [close](http://puu.sh/lpxDj/9f3107a6b6.ogg))
- [Gun spawn spell](http://puu.sh/lpxFR/4a074e3ea4.ogg)
- [Egg squash](http://puu.sh/lpxGL/4c77622991.ogg)
- [Borer hatch](http://puu.sh/lpxH8/e8071d4671.ogg)
- [Airlock permission denied](http://puu.sh/lpxmM/8035a463c5.ogg)
- [Deep fryer](http://puu.sh/lpxBy/412daff2d3.ogg)
- Rip sound when clicking on wrapped crate (this is poster rip sound)
## TODO (will do on another update)
- _Modified laws_
- _Some religious sound to spawning cultists_
- _Arcade sounds (win/lose)_
- _Flashlight on/off_
- _Drills sounds_
- _Simple animals (will do on a future update)_
- _Cloning pod eject_
- _Vending machine purchase successful/failed_
- _Valve opened/closed_
- _Sink used_
- _Laundry machine running_

**I personally think sounds are really important on a game, and we're lacking them. So I'll be working on this.**

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Drilling in the asteroid makes a wall hitting sound. It can eventually be heard if you mine from inside a hidden room, and it destroys immersions. A drilling sound would be most nice.

**Comment by Ephx1** [comment]
Maybe a shuttle docking sound for the mining/research shuttles?

**Comment by Probe1** [comment]
:+1: 
Vampire was a huge one for me, but so would be changeling.  Wizards kinda self evident but could be nice.

Basically all the antag roles need an audible notification.  That is what I'd like to see.

**Comment by Ephx1** [comment]
Just have the Wizard spawn notification be this:
https://youtu.be/8oWAb5NVALw

**Comment by Zth--** [comment]
Drills added to the todo list. Shuttles maybe on the next update.

About the ling... I'm not sure how should it sound, but I'll work on it

**Comment by Ephx1** [comment]
One of these for ling?
https://youtu.be/VgyiBrY_cNM

**Comment by Zth--** [comment]
Hm, maybe. I have a folder of horror sounds, I'll check them tomorrow.

**Comment by Probe1** [comment]
Changeling imo
https://youtu.be/lfdRTvytNvY?t=110

**Comment by Kurfursten** [comment]
Cloning pod eject
DNA modifier irradiated
Fabricator at work (autolathe, protolathe, general fab, flatpack fab, exosuit fab, spacepod fab, etc.)
Deconstructive analyzer working
Vending machine purchase successful
Vending machine purchase failed
Valve opened/closed
Sink used
Shower running

**Comment by Ephx1** [comment]
> Shower running
Time to fill the halls with not only slipping, but ear rape.

**Comment by 9600bauds** [comment]
Oh man, Summon Guns one is great

**Comment by Probe1** [comment]
It is!

**Comment by Zth--** [comment]
>Fabricator at work (autolathe, protolathe, general fab, flatpack fab, exosuit fab, spacepod fab, etc.)
>Deconstructive analyzer working
>Shower running
I'm afraid I can't add those because we don't have something like stopsound, and byond's loops for sounds sucks. Correct me if I'm wrong, but that's not possible until someone codes it.
I'll work on the other ones

**Comment by Zth--** [comment]
What do you think about [this](http://puu.sh/lqHv9/96b3676ece.ogg) one? It's for the spawning cult members

**Comment by Probe1** [comment]
not a huge fan

**Comment by Zth--** [comment]
Yeah it doesn't convince me

**Comment by Kurfursten** [comment]
I've been mulling over whether I should speak up for a few days, but I'm just going to say it. I don't like the idea of an airlock-denied sound. As the mechanic I don't want the clown slamming into my door over and over to spam me with denied sounds. As a traitor, I don't want a loud BUZZ to go off right before I emag a door because I accidentally bumped it. I think the red lights are a subtle and pleasant middleground between no feedback and too much.

**Comment by Zth--** [comment]
I think we should try it, if people don't like it then I can easily remove it.

#### Since I'm busy with uni, this will be a small update.

I will keep making updates, don't worry

**Comment by clusterfack** [comment]
Well it may have been ready to go, at some point

**Comment by Kurfursten** [comment]
I did a small scale poll to see if people would like an access denied sound for doors about a week ago. I was surprised to find it was about 50/50, so may as well let it go to live and let people try it out.

I was sure the polls would turn up a lot more negative responses, but if half the players want it, far be it from me to try to deny them.

**Comment by Zth--** [comment]
Somehow changelog was giving errors.
Well this is ready to go...  i'll be back in january!
merry christmas!

**Pull request merged**
