### PR TITLE
Makes chocolate, avocados, peanuts, garlic and grapes harmful to dogs (plus their products)

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]
to cherish the end of parole, here's a fun thing from the backlogs

## What this does
see title

## Why it's good
flavor and realism

## How it was tested
feeding them to ian (animal testing edition:tm:)

## Changelog
:cl:
 * rscadd: Ian can no longer eat anything with avocados, garlic, peanuts, cocoa powder or grape juice in it, as this is, yknow, fatal to dogs. All dogs in the game in fact.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
😢

**Comment by CrazyAmphibian** [comment]
don't forget onions and garlic, too

**Comment by SECBATON-GRIFFON** [comment]
> don't forget onions and garlic, too

we don't have onions in the codebase, wyci
also, is it specifically the allicin that does it to them? cause i can make it so if so

**Comment by Eneocho** [comment]
> we don't have onions in the codebase, wyci also, is it specifically the allicin that does it to them? cause i can make it so if so

it's the thiosulfate in the garlic, rather than the allicin, so it should be garlics specifically
also hot coco, subhuman hot coco, coco, creamy hot chocolate and chocolate milk, plus all the dishes that contain peanut, avocado, chocolate, grape or garlic.

**Comment by falcon2346** [comment]
Time to break the HoP's window when he isn't looking and throw a chocolate bar in

**Comment by SonixApache** [comment]
what about cats
and catbeasts

**Comment by RealestEstate** [comment]
should also probably make pets reluctant to eat poisonous foods

**Comment by angryturnip** [comment]
> should also probably make pets reluctant to eat poisonous foods

Why? Animals don't know chocolate is bad for them

**Comment by SECBATON-GRIFFON** [comment]
> what about cats and catbeasts

if you have any suggestions it'd help

**Comment by Eneocho** [comment]
make it so ian isn't a fucking locust that eats everything within a minute, give him a fair cooldown timer, maybe 30s per food item? so he still eats the chocolate, but it takes a while

**Pull request merged**
