### PR TITLE
Easels and frames (or lack thereof)

### PR DESCRIPTION
**Pull request by jellyveggie2**
Adds easels to place your paintings on. Paintings on easels can be interacted with the same way a painting on a wall can
easels

The shelf-like part that the painting rests on and the holder piece at the top will automatically adjust to a canvas' dimensions. Supports custom paintings only.
Sprites need replacement by someone who actually knows how to sprite.

Also, canvas now can have their frame removed (or re-added) because I can't figure a way to make them look god on easels otherwise, and because large paintings are already large enough without an extra 2 pixels of frame surrounding them and and making clicking on the easel a pixel hunt.

[needspritework]
:cl:
 * rscadd: You can now use wood to build easels and display your paintings. Wrench to deconstruct.
 * tweak: Canvas no longer start with wooden their frames. You can add a frame to a painting with wood, or remove it with a crowbar.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you move the easels for that on the move painter experience?

**Comment by jellyveggie2** [comment]
You can pull/push them around.

**Comment by BurntDevil** [comment]
Sprites look fine.

**Comment by Eneocho** [comment]
I just realized that you could use the frameless paintings to make a 24x48 painting by placing two frameless larges next to each other. This opens a whole lot of possibilities.

**Comment by jellyveggie2** [comment]
Can't say I'm too fond of the easel sprites myself, they feel kinda flat and out of place, but if no one sees any issue with it then sure, may as well keep them.

Also Eneocho, I guess?
Untitled
Gap is still the same size after all, just without frames. Personally I think I'm having an easier time conceptualizing both paintings as being the same on the framed ones, but perhaps I've just grown used to that due to working with two monitors. Also, lucky thing I had the perfect template for this from a different test.

**Comment by Eneocho** [comment]
Not as seamless as I imagined, but it still works somewhat I guess.

**Comment by Eneocho** [comment]
Can you share those two templates?

**Comment by jellyveggie2** [comment]
They're originally the same template, a 48x24 made with #31699 in mind, but here: [Left](https://ss13.moe/wiki/index.php/Painting_Templates#Swordsman_.28Dwarf_Fortress.29) and [right](https://ss13.moe/wiki/index.php/Painting_Templates#Axeman_.28Dwarf_Fortress.29)

**Pull request merged**
