### PR TITLE
Magician Outfit

### PR DESCRIPTION
**Pull request by Arthurdentist**
New Outfit for Wizards. It acts in the same manner as a normal Wizard Robe so you can cast all your favorite spells whilst wearing it. Also added one to the premium section of the Clown's Vendor, so the Clown can perform a little stage magic too.

Comes with a Magic Top hat which uses the pre-existing Collectible Top Hat sprite. 

magician finished

### CODE REVIEW

**Comment by Shadowmech88** [comment]
I notice the outfit doesn't have shoes. In order to cast spells, the wizard would have to wear his sandals with it, which would clash a little with the fancy magician suit in terms of appearance.

Also I think it'd be neat to make the top hat a container with one slot so that you could pull stuff out of it.

**Comment by Arthurdentist** [comment]
I was going to create magical black shoes as well, but they already exist as part of the Marisa outfit and they can be found in the wizard den too, I could probably add a pair to the vendors though. 

The Top Hat idea is good, it would be cool if you could do that with all wizard hats.

**Comment by DrCelt** [comment]
Sounds great!

**Comment by Arthurdentist** [comment]
I have added a pair of Magical leather boots to the wizard vendor so that you can more easily complete the outfit, without finding the pair of magic shoes hidden under the Marisa outfit.

**Comment by Shadowmech88** [comment]
I made some bunny sprites for that summon rabbit spell you were talking about.
bunnies

**Comment by Arthurdentist** [comment]
I'll do that as a separate PR sometime but cheers

**Comment by Arthurdentist** [comment]
this was migrated over and is already in the code.

**Pull request closed without merging**
