### PR TITLE
Fixes #11133

### LINKED ISSUE #11133: Filled MMIs are immune to supermatter
(WEB REPORT BY: aurx REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4fb6a0e943eef40b29944088c8c8e88346dd4616
> 
> General description of the issue
> A MMI with a brain in it that hits supermatter will flash into ash but not vanish.
> 
> What you expected to happen
> Them to go the way of all mortal matter.  
> 
> What actually happened
> It stayed around.  
> 
> Steps to reproduce if possible
> Saw this when the derelict MoMMIs had rigged a mass driver pointing into supermatter to autofire and committed suicide by supermatter.  

Runtime logs look clean of anything related to this.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Iamgoofball** [comment]
holy shit

**Comment by Probe1** [comment]
HE DOES IT AGAIN THE MAD LAD

**Comment by kilozombie** [comment]
Just keep this up til 2017 and nobody will be capable of complaining

**Comment by ComicIronic** [comment]
Why does this even work?

**Comment by ghost** [comment]
@ComicIronic ```qdel(mmi) //Delete the MMI first so that it won't go popping out.```
I presume once upon a time this was a del, so it completely deleted it from the game. Before this PR however, it still holds a reference to the GC'd MMI so it spawns that upon the MoMMI dusting despite it being deleted - resulting in an undeletable (because it's already been deleted) MMI

**Comment by PJB3005** [comment]
And did you actually test it to double check it works?

**Comment by ghost** [comment]
@PJB3005 what why would I test this

(Yes)

**Pull request merged**
