### PR TITLE
Misc. Packed fixes

### LINKED ISSUE #18133: There is no blue toolbox on Packed's bridge.
There is one in each and every bridge. Consistency.

### LINKED ISSUE #18293: Packed's bar has no APC
That's all.

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### LINKED ISSUE #18308: Packed engineering access
(WEB REPORT BY: majesticmastodon REMOTE: 172.93.109.202:7777)
# Revision
bfdda846636eac7dba837336b393963cfdcc3940

# Description
Mechanic doesn't have engineering access on Packed

# Steps to Reproduce
Just be a mechanic on packed and go to engineering
# What you Expected
For the doors to open so I can take glubbs and singuloose
# What Actually Happened
The doors didn't open

### LINKED ISSUE #18490: Trader shuttle blocks the way for spacepod in Packedstation
Title, if the trader shuttle is docked at the station you can't get to space via space pods, but it may be a feature(?)

### PR DESCRIPTION
**Pull request by PromethTK11**
fixes #18490 
fixes #18308 
fixes #18293 
fixes #18133

Also adds a bit of a "ruin" exposed to space on the space between atmos and medbay maint so there's some room to play as an engineer in lowpop

### CODE REVIEW

**Comment by Kurfursten** [comment]
pic of the added content

**Comment by DamianX** [comment]
MapDiffBot works now, look at the "checks" tab

**Comment by Tokanova** [comment]
What's with moving the sleepers and body scanners in medbay?

**Comment by PromethTK11** [comment]
lol, I though that the sleeper and scanner change didn't made it, I was sure that I reverted them, I was just trying to do an aesthetic change to see how they will look on that position

**Comment by Accipitermaris** [comment]
I'm not really sold on the "ruins", they seem more fitting for a map style of Deff than they do Packed. (The ruins themselves are taken from Deff Maint. A bit soured on the "monkeys in maint" thing in particular because it makes Xenomorphs 300% more anti-fun extract for crew.)
I think something like a vacant office/ghetto bar in the orange rectangle would be a more fitting way of giving Engineers room to play with on Packed.

afterdo
(As a tangent, we do have a number of derelict engineering spaces as Space Vaults, but the fact that they don't spawn on Z1 means that no one ever uses them because of the massive inconvenience found in that endeavor.)

**Comment by PromethTK11** [comment]
Actually yes, they're copied from deff, and I thought something like that too, probably adding some kind of incinerator or something like that in maint, vacant office and things, this was more to the target of fixing shitty maint that I rushed when I did the map.

Btw, I'll look the derelicts to find inspiration

**Comment by PromethTK11** [comment]
Actually you gave me an idea

**Comment by DamianX** [comment]
fix iiiiiiiiiiit

**Comment by PromethTK11** [comment]
Taking this down, university suck out a lot of time, and there's not internet to work on this rn

**Pull request closed without merging**
