### PR TITLE
You no longer suffer from hallucinations when dead

### LINKED ISSUE #27918: Roid lich can cause corpses to hallucinate in deadchat
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
f71eb96f269ee37767bd56be5e1320bf6cc53c99

# Description
Azlin can cast hallucinate on corpses which causes them to deadsay hallucination effects that would normally be sound effects to the player ([03:34:22]SAY: Zezree/*no key*/(Zezree) (@209,140,3) Deadsay: stammers, "Beep, boop")

# Steps to Reproduce
Die to azlin, might also require mousing or some other method to make your old corpse catatonic

# What you Expected
nothing

# What Actually Happened
old corpse randomly speaks hallucination effects into deadchat

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #27918

:cl:
* bugfix: You no longer suffer from hallucinations when dead. (loppu)

### CODE REVIEW

**Comment by DamianX** [comment]
Why process any of the hallucination stuff at all if the dude is dead? Wouldn't returning early in the proc if the dude is dead make more sense?

**Comment by DeityLink** [comment]
I thought some of the hallucination stuff could be fun to still experience while dead.

**Comment by DamianX** [comment]
This doesn't work, the check happens before the spawn.

**Comment by DeityLink** [comment]
Should have checked for all spawn() and sleep() this time.

**Comment by Eneocho** [comment]
What about the spiritbreaker toxin? Do you still hallucinate after death?

**Comment by Eneocho** [comment]
> 
> 
> What about the spiritbreaker toxin? Do you still hallucinate after death?

@DeityLink

**Pull request merged**
