### PR TITLE
Adds three new bar drinks and a new hot beverage.

### PR DESCRIPTION
**Pull request by TurboGay**
Spritework and ideas/recipes courtesy of @beesil. Adds three new drinks and a cozy hot beverage to the bar.

The Mudslide:
mudslidebig
Recipe is one part Antifreeze, one part Black Russian and one part Irish Cream.

Boysenberry Blizzard:
boysenberrygif
Recipe is one part Liquid Plasma, four parts Snow White and one part Berry Juice.

Sacrificial Mary:
sacrificialmarygif
Recipe is one part Vodka, two parts Blood, and one part Lime Juice.

Creamy Hot Chocolate:
creamyhotchocolate
Recipe is one part Hot Chocolate/Cocoa and one part Cream.

All recipes and drinks working when tested locally.

:cl:
 * rscadd: adds the mudslide drink/reagent/sprite
 * rscadd: adds the boysenberry blizzard drink/reagent/sprite
 * rscadd: adds the sacrificial mary drink/reagent/sprite
 * rscadd: adds the creamy hot chocolate drink/reagent/sprite

### CODE REVIEW

**Comment by Zach720** [comment]
sneed

**Comment by Eneocho** [comment]
Looks nice.

**Comment by mrflarg** [comment]
>more hot chocolate 
>still no milkshakes
>still no chocolate milk

**Comment by Kurfursten** [comment]
There is a milkshake, it's just ugly so no one makes it

**Pull request merged**
