### PR TITLE
Pets; Slightly less retardation edition

### PR DESCRIPTION
**Pull request by NigglyWiggly**
I'm too stupid to fuck with conflicts and shit so fuck that noise. This
one should work.

### CODE REVIEW

**Comment by CptWad** [comment]
:ok_hand:

**Comment by PJB3005** [comment]
@NigglyWiggly confirmed @dylanstrategie

**Comment by Probe1** [comment]
i'd still rather see the librarian get a cat than a flying book.

**Comment by NigglyWiggly** [comment]
The cat is in you nerd, the book was only for bus anyway

**Comment by Probe1** [comment]
da best

**Pull request merged**
