### PR TITLE
[MDB IGNORE] Fix DJ satellite wiring issues

### LINKED ISSUE #32908: Boxstation Derelict DJ Sat Radio Transmitter Broken
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
b6830325574dd89a4c2f60a5086c8c57c4033e77

# Description
DJ Sat Radio Transmitter does not have a cable knot under it and even if placed, will immediately turn off.

### LINKED ISSUE #34278: Ruskie DJ Station's Radio Transmitter is not wired roundstart
(WEB REPORT BY: makagame REMOTE: 206.221.180.138:7777)
# Revision
66e3f972de6fbe5ceaffb551813b6475dd665db6

# Description
Ruskie DJ Station's Radio Transmitter is not wired roundstart
# Steps to Reproduce
Visit Ruskie DJ Station and try to enable Radio Transmitter
# What you Expected
Radio Transmitter
# What Actually Happened
It demanded to be connected to a power source, I had to manually wire it to the station's SMES.

### PR DESCRIPTION
**Pull request by jellyveggie2**
## What this does

Wires the DJ satellite's solars, SMES input, SMES output and radio transmitter together into the same grid such that the transmitter is wired and powered roundstart, independent of solar panel orientation.

Applies to what I'm pretty sure is every station except the test stations and Lamprey. 
Lamprey shall remain cursed with a lack of proper wiring.

Fixes #34278
Fixes #32908

Also, takes advantage of the new poer monitor to adds a tiny bit of russian flair to the satellite's SMES. 
For muh immulsions.

## Why it's good

It's been annoying and confusing some players for a while apparently. They'd probably know how to make a better case than I would.

Some alternative solutions:
* Add a cable coil somewhere on the satellite, maybe some insuls too. Make setting up the sat a DIY project that doesn't force the player to travel back to the station/derelict for tools/materials
* Make the DJ sat's transmitter not require a powered cable. Maybe the russians put rad cells in their radio transmitters or something. 

## Changelog

:cl:
 * bugfix: Fixes wiring issues with the radio transmitter in the DJ satellite.

### CODE REVIEW

**Comment by jellyveggie2** [comment]
Wait fuck why is there an extra SMES on xoq's satellite now. 
I knew this was going too well for my first mapping PR.

**Comment by jellyveggie2** [comment]
Fuck it, I'll look into why MapDiffBot won't let me delete the extra SMES tomorrow.

**Comment by jellyveggie2** [comment]
Alright no that's it, either MapDiffBot2 broke or it hates this PR's guts now for some reason.
Last commit should be identical to 1f9cf3778d29fb888821d9069847c4f426a4125d, which passed fine, it should not be breaking now.

**Comment by jellyveggie2** [comment]
I've given up, it'll have to be an MDB IGNORE now.
RIP mapdiffbot, you will not be missed.

**Comment by pedr69** [comment]
akkumuljator

**Pull request merged**
