### PR TITLE
Nerfs floor tiles buffs toolboxes

### PR DESCRIPTION
**Pull request by clusterfack**
This is the way spess should be comrades

### CODE REVIEW

**Comment by kol1th** [comment]
yes

**Comment by 9600bauds** [comment]
>25

There is no possible way this can go wrong.

**Comment by clusterfack** [comment]
I was holding back from 30

**Comment by kol1th** [comment]
> 25
I just noticed that holy shit
no maybe 20 at max, that's a LOT of fucking damage, they already hurt

**Comment by Probe1** [comment]
cough 20

**Comment by 9600bauds** [comment]
Didn't even update the syndietoolbox force 2/10

**Comment by AutismSpider** [comment]
Ahh time for meme pulls

**Comment by TheFriggenSawbones** [comment]
boys this is the most unamerican shit you rothschild goons

**Comment by SangriaMonkey** [comment]
>25 damage meme mashers scattered about the station in nearly every emergency oxygen locker

:eggplant:

**Comment by Shadowmech88** [comment]
What about making a toolbox's force scale with the cumulative w_class of the items inside it? More stuff inside it means heavier toolbox which means more damage.

**Comment by AutismSpider** [comment]
@Shadowmech88 better slow attack speed down of the tool box by shit ton then

**Comment by Shadowmech88** [comment]
Hasn't stopped people from favoring the executioner's sword over the standard sword, despite it having thrice the attack delay.

**Comment by Exxion** [comment]
>25

Is this a fucking joke?
That's the same as the motherfucking wielded fire axe

**Comment by AutismSpider** [comment]
@Shadowmech88 takes very little force cut people open to start a massive bleed out  one hit form executioner does this same with the spear

**Comment by 9600bauds** [comment]
>still doesn't update the syndietoolbox's force

While you fix this up let's discuss why are floortiles even a bad thing

**Comment by Shadowmech88** [comment]
@Exxion
Fire axes have 40 force when wielded. 10 force when not wielded.

**Comment by kol1th** [comment]
MEME PULLS
:eggplant:

**Comment by Exxion** [comment]
I could have sworn it was 25

**Comment by kol1th** [comment]
>regular 20
>syndi 24

**Comment by clusterfack** [comment]
Now you're just complaining for complainings sake

**Comment by Probe1** [comment]
Just do it for a week it'll be fun.

**Comment by Exxion** [comment]
So why exactly should toolboxes, found in every single O2 locker on the station, be the most powerful melee weapons on the entire station save for the fire axe and arguably the executioner's sword?
Even wielded spears only have 18 force

**Comment by kol1th** [comment]
> Just do it for a week it'll be fun.

you absolute fucking madman

**Comment by 9600bauds** [comment]
I can see toolboxes getting some use even at 15 force desu, and syndie toolboxes can have any force sure why the fuck not

I'm finding it hard to rationalize trashing floortiles however

**Comment by clusterfack** [comment]
Spears get bonus force based on the sharpness of the shard. You're trying to obfuscate the subject. A wielded spear with 18 force is literally given the prefix "useless".

**Comment by Shadowmech88** [comment]
How much damage does a wielded spear with a reinforced plasma glass shard do?

**Comment by clusterfack** [comment]
It depends upon sharpening

**Comment by AutismSpider** [comment]
@Shadowmech88 nigger plasma spears never got in so it turns into normal glass spear base on how sharp the shard was

**Comment by 9600bauds** [comment]
Where do you get this fabled "nigger plasma"?

**Comment by Probe1** [comment]
@9600bauds tinted glass + plasma

**Comment by Shadowmech88** [comment]
Nigger plasma when?

**Comment by Exxion** [comment]
God damn it stop putting new features for existing items in separate files from the original items
That's the force spears always had when wielded until a couple months ago, but OK
But still, 25 force one-handed is ridiculous
20 is still pretty high, but not as absolutely and clearly broken

**Comment by Exxion** [comment]
Also upvoting your own PR is dirty

**Comment by SangriaMonkey** [comment]
He's turning into Dylan

**Comment by clusterfack** [comment]
*Not allowed to support your own PR*

**Comment by 9600bauds** [comment]
Shhhhhh sangriamonkey don't jynx it

**Comment by SangriaMonkey** [comment]
:eggplant:

**Comment by AutismSpider** [comment]
@SangriaMonkey if it was dylan it be a nerf not a buff

**Comment by 9600bauds** [comment]
Half of this PR is a nerf

**Comment by TheFriggenSawbones** [comment]
100% of this PR is just hog wash it's what killed american literature

**Comment by 9600bauds** [comment]
You guys don't get it. Cluster is just misunderstood.

His aunt was killed by floortiles.

**Comment by kol1th** [comment]
> You guys don't get it. Cluster is just misunderstood.

His aunt was killed by floortiles.

my aunt is a toolbox, please remove this PR

**Comment by SangriaMonkey** [comment]
Old Ant Scootaloo never caught a break did she

**Comment by SplergeBucket** [comment]
buff the damage of everything
these nerfs are shit

**Comment by Intigracy** [comment]
I like the idea of having it based on the toolbox's w_class (which updates when you put items inside).

**Comment by dylanstrategie** [comment]
Nerfing floor tiles to not be shitler shurikens ? Yes sir

Although regarding the toolbox, I would prefer if the toolbox's force was set by the w_class (substitute for mass, which we don't have) of all objects in the container, which should be an innate container variable somewhere. Make it so a toolbox crammed with heavy objects does maximum force, but an empty toolbox does close to or lower than the current damage

Something like 10-20 with 10 force allocated to w_class. Syndicate toolboxes get an innate 5 force bonus because they're robust Syndicate tech

Seeing how max_combined_w_class = 28, I would say that something close to 0.35 force per w_class carried in the toolbox should be fair. You won't get exactly 20, but with enforced rounding it should be close

**Comment by 9600bauds** [comment]
I'm still waiting to hear why should floortiles be nerfed. I think they're in a good position of acting like a ghetto ranged weapon, and they're more of a sidegrade than first impression would let you on to.

It also seems to make little sense to me to nerf something that barely even sees any use, if floortiles were OP, don't you think everyone would use them? It's been really a while since I've seen anyone actually throwing them, and I can say that with complete honesty.

**Comment by dylanstrategie** [comment]
I have seen people use floor tiles, the problem is that antags don't use them since antags will usually try to steal a fireaxe, sec supplies or purchase insta-para sypplies and that crewmen with actual responsibilities will go loot the Armory

So it's usually a ghetto weapon, and a tremendously powerful one at that. 15 damage for a weapon you can generate literally anywhere but deep Maintenance and Space with a crowbar, and that can be thrown a screen's length is huge. As such, it makes all other ghetto weapons a lot less useful. Throwing tiles at someone is as powerful as trying to hit them with a glass spear, or just bashing them with the toolbox before the buff

**Comment by Probe1** [comment]
@9600bauds floortiles were always OP but they took away my toolboxes so I didn't speak up.

**Comment by 9600bauds** [comment]
It's significantly less damage than a glass spear. I think there are a few factors that you need to consider before you write it off as "too powerful" but rather than get in-depth with the downsides of floortiles I'm going to go with logic first.

If floortiles are so good that they make other ghetto weapons less useful by comparison: Then why do I see almost nobody ever use floortiles? I vividly remember most times I find improvised weapons on people or see them used. Stungloves are by a huge margin the most popular choice. Circular saws are also a popular choice, and some people swear by their swords. I've even seen people with railguns, blunderbusses, etc.
But I can't remember ONE single sighting of floortiles in my recent memory.
Once again: If they're so OP, and they make other ghetto weapons less useful, *why is nobody using them*?

Secondly: This change to toolboxes is going to obviously shift around the meta of ghetto weapons. Now there are going to be force ~20ish weapons everywhere, even more readily available than floortiles. So doesn't this already make floortiles less useful by itself? It makes zero sense to me to buff toolboxes AND nerf floortiles at the same time.

**Comment by Probe1** [comment]
Stun gloves and circ saws are used for the same reason.  Knockdown.  Floor tiles are a different bag.  They're ranged.

**Comment by 9600bauds** [comment]
And that's why I consider floortiles to be a sidegrade. Not only do they not have any knockdown, they don't work on people that are knocked down at all. And after this toolbox buff, they're not even comparable damage anymore.
I really don't see the reason to nerf them, and if they do get nerfed then I really really don't see the reason to make them USELESS.

**Comment by AutismSpider** [comment]
How hard did sawbones meme on you to get floor-tiles nerf him and four other people are know to tile the shit out of people+table combo

Like hell have floor tile  Constructs to death and xenos (constructs are shit any way unless its a Wraith)


Whats the point of making tool boxes hit as hard as Eswords and hulk out people? tools box's happen to be all over the fucking station

**Comment by gbasood** [comment]
@AutismSpider Once upon a time toolboxes were the only way to robust
Also holy shit I can barely understand your sentences sometimes

**Comment by Skullyton** [comment]
Floor tiles a shit

Floor tile shurikens when, to counteract this balancing?

**Comment by 9600bauds** [comment]
At least make the two balance changes into two different PRs

**Comment by Boxe** [comment]
>force 20 toolboxes

:eggplant:

**Comment by NigglyWiggly** [comment]
@AutismSpider 
>tools box's happen to be all over the fucking station

Floor tiles are literally all over the station, mang.

@gbasood English isn't his first language, he's an angry Russian (?) robot crab

**Comment by AutismSpider** [comment]
@NigglyWiggly people rarely use them both rods and floor tiles do 15 damage 25 if you happen to have feel strong mut or hulk out

**Comment by Shadowmech88** [comment]
This has twice the number of likes as dislikes.
Personally, I think it's good for merge.

**Comment by 9600bauds** [comment]
I don't know how many of these votes are for toolboxes and how many of these votes are against floortiles. I'm kind of pissed that both changes were bundled into one honestly.

**Comment by Probe1** [comment]
We should really just split it up, re-open now that the meme fervor has died down, and probably drop toolbox damage a further 5 to fifteen which is cool and pretty fucking robust.

**Comment by 9600bauds** [comment]
I think toolboxes would be pretty good and see use at 16/25syndie, but sure let's make them 20 for a week and see where it goes, would be fun

**Comment by clusterfack** [comment]
Nobody likes nerfs, if you were to nerf something without buffing something else you nerf would be described as an 'arbitrary nerf' and would be downvoted and shitposted into oblivion.

**Comment by 9600bauds** [comment]
>Nobody likes nerfs

meanwhile
https://github.com/d3athrow/vgstation13/issues/9766

**Comment by clusterfack** [comment]
Meanwhile https://github.com/d3athrow/vgstation13/pull/2804

**Comment by 9600bauds** [comment]
The only thing needed for people to get behind a nerf is years of repeated abuse

**Comment by clusterfack** [comment]
Just redeeming my one time only "I told you so" for that one

**Comment by 9600bauds** [comment]
you already redeemeed it in #9766 :^)

**Comment by clusterfack** [comment]
I didn't link it

**Comment by 9600bauds** [comment]
It's fine, you deserve to redeem it up to 3 times
make the third one count

**Comment by clusterfack** [comment]
Thank you I'll save it for a rainy day

**Comment by ShiggyPiggy** [comment]
>you can obtain floor tiles with just using the crowbar already found in the emergency lockers
>suddenly, meme toolboxes are a problem
Hmm.

**Comment by 9600bauds** [comment]
Just realized there's no changelog here

**Comment by KingCrimsonIJW** [comment]
Just fucking make knives trowable weapons slightly stronger than floor tiles and make floor tiles a bit less stronk

**Comment by 9600bauds** [comment]
Someone in the thread said: "just reduce floortile throw range"

**Comment by PJB3005** [comment]
How the fuck are you throwing a 4m<sup>2</sup> metal floor tile with your hands anyways?

**Comment by 9600bauds** [comment]
Have you ever wondered why thrown floortiles are so robust?
One floortile has a volume of 937.5 cm^3 when recycled at an Autolathe. Since metal sheets seem to be made of pure iron, that would give each individual floortile a weight of exactly 7.38 kilograms.
But what about it's dimensions? We know that in-game, one tile is exactly 2m*2m. Logically, a floortile would need to be that big to cover one tile. How a spessman manages to fit a floortile in a backpack, nobody knows. With a volume of 937.5 cm^3, you can calculate the thickness of each floortile to 0.23 millimeters. That's just 3 times the diameter of a human hair.
As a fun fact, a stack of 50 metal sheets weighs 1480 kilograms and has the volume of around 1.2 full bathtubs. Engineers are stronk to carry that in their backpack.

**Comment by PJB3005** [comment]
The thing is the station's base plating protecting people from space is made out of these things so it can't just be regular iron, there's no way that could support anything.

**Comment by 9600bauds** [comment]
The good news is that the mass density of industrial steel is pretty similar to pure iron so the numbers are still around the ballpark

**Comment by 9600bauds** [comment]
As for how to throw it

https://www.youtube.com/watch?v=H3byfZY7YT4

**Comment by 9600bauds** [comment]
ALSO: I heard a myth that having throw intent on and standing still would make you catch things thrown at you, that WHEN?

**Comment by SarahJohnson489** [comment]
Floor tiles are fine. Don't wear your memeboots you stole 4noraisins from eva at roundstart, eat your 4noraisins, pay attention and you're perfectly safe to zoom away from a floor shitter while calling him out. If absolute madmen want to juggle active hands and fling ineffectually instead of just shooting with real guns or slip murdering you, let em.

The old pomf meme of toolboxes hitting harder if you jam it full of heavy shit sounds better than a straight force boost.

**Comment by Exxion** [comment]
@9600bauds I think other codebases have that already
I seem to remember doing it on /tg/ long ago when I still played there
But I may be remembering incorrectly and just crazy

**Comment by TheFriggenSawbones** [comment]
if everyone was only a little bit more robust they wouldn't care about floortiles

**Comment by AutismSpider** [comment]
@9600bauds TG has you catch toss at you when on throw intent+disarm-intent

**Comment by ihadtoregisterforthis** [comment]
Given the lines on the tiles when placed I would think they are foldable

**Comment by Probe1** [comment]
Re open with 15 damage and a separate PR for floor tiles.

**Comment by 9600bauds** [comment]
Rate this funny for 15force
Rate this hooray for 20force
Thumbs up for meme option

**Comment by AutismSpider** [comment]
yes lets Nerf floor tiles and rods not assault rifles can be made dirt cheap and do 20 damage+knock down.

don't t give me that lock box shit you can open them with ied or beak of water+poss

**Comment by Shadowmech88** [comment]
You need more than five seconds and a crowbar to make an assault rifle.

**Comment by 9600bauds** [comment]
Attainability is ONE factor of many

**Comment by gbasood** [comment]
Also, ammo is a thing.

**Comment by AutismSpider** [comment]
Assault rifle has 30 shots m8 ammo cheap to make like the gun

**Comment by Probe1** [comment]
The guns so cheap that before ammo was added to the protolathe, people just printed new assault rifles.

:clap: :clap:

**Comment by gbasood** [comment]
Sounds like a problem with guns, doesn't it?

**Comment by 9600bauds** [comment]
If I didn't know better, I would say that yeah

Instead, I'm going to say that it's a problem with lockboxes

**Comment by gbasood** [comment]
Or maybe the cost of getting those guns at all is too low?
To an extent it doesn't matter what goes on with lockboxes. If someone in R&D wants to hand out guns like candy they will, because it's dirt cheap for them to do so and they have nothing better to do after research is done.

**Comment by ComicIronic** [comment]
Every time you blame lockboxes, the Communists win.

**Comment by 9600bauds** [comment]
Wait are we saying lockboxes are not a bad system

**Comment by ComicIronic** [comment]
There is no lockbox solution that doesn't end with a potas scishitter or a Officer McLawBoner screaming at you about how the game is terrible.

People don't want real lockboxes you can't blow up because that's no fun, and they don't want real lockboxes you can blow up because that's pointless. Instead, we have fake lockboxes you can blow up and Sec can see an ID on.

**Comment by 9600bauds** [comment]
Exactly what's the difference between a "fake lockbox you can blow up" and "real lockbox you can blow up"

**Comment by ComicIronic** [comment]
You can open the fake lockbox without blowing it up and this will record the ID used to unlock it.

**Comment by 9600bauds** [comment]
But then we don't have fake lockboxes

**Comment by ComicIronic** [comment]
It's not a real lockbox because there's no access restriction. I consider it to be a box of minor inconvenience. Less of a lockbox, more of a closed box.

**Comment by PJB3005** [comment]
@ComicIronic we don't have those anymore.

The issue is that disposing of them was easy as fuck.

If sec got notifications about lockboxes, with location AND ID, then maybe they'd be useful.

**Comment by AutismSpider** [comment]
@PJB3005 people would just blow them up any way zero fucking risk when blowing up lock box's or any type of box for that matter you get the item out of it

**Comment by FudgePucker** [comment]
Make a computer that records when a lockbox is damaged, but make emags bypass it.

So now you need to get an ID or emag to stealthily get guns

**Comment by Intigracy** [comment]
Stop going off topic.

I don't like this PR.

**Comment by 9600bauds** [comment]
To get back to the topic: 
The vote was completely unanimous for toolboxes to be 15 force instead of 20, so that just needs one change. Leave syndietoolboxes at 25 force too, why not
Floortile nerf was self-admittedly only bundled with this buff because there's no way it would pass alone
I would agree with giving floortiles a shorter range, or nerfing their damage REASONABLY, not down to "completely worthless"

**Comment by clusterfack** [comment]
What vote?

**Comment by Intigracy** [comment]
The emojis in your OP I'm guessing.

**Comment by 9600bauds** [comment]
firefox_2016-05-30_20-18-30
This vote

**Comment by clusterfack** [comment]
It looks like you were being memed on

**Comment by 9600bauds** [comment]
Meme magic wills it, Clusterfack

**Comment by clusterfack** [comment]
Mine has more votes

**Comment by 9600bauds** [comment]
Could it be that many people want it, just not in it's current form?
How come nobody voted for 20force in a whole month?
This goes against your philosophy of why votes are worthless to you, namely "people just want everything buffed and nothing nerfed"
And this is github votes, too

**Comment by PJB3005** [comment]
Server poll when.

**Comment by 9600bauds** [comment]
When we decide if votes are good or not and stick to that choice

**Comment by Shadowmech88** [comment]
There's really no reason *not* to split the buff and the nerf.
I don't see this getting merged otherwise, under the argument of "well people would never vote for it if it was just the nerf, tberefore the whole PR shouldn't be merged."

**Comment by clusterfack** [comment]
Don't be faggot shadowmech you should know people meme on any nerf as clearly shown AGAIN by the recent fridge nerf proposed by dylan.

**Comment by Intigracy** [comment]
Nerfs are cool and all but this is making it completely useless.

**Comment by clusterfack** [comment]
Is that a bad thing for an item that can be stacked 50 times over and stored in a backpack?

**Comment by 9600bauds** [comment]
Making ANYTHING completely useless is bad, don't be a faggot

**Comment by clusterfack** [comment]
There are plenty of things that are useless

**Comment by 9600bauds** [comment]
Is that supposed to be a good thing?

**Comment by PJB3005** [comment]
Not everything needs a use. Floor tiles already have one so why are you calling them useless?

**Comment by 9600bauds** [comment]
You're making this comment in a PR that makes toolboxes into deadly weapons

**Comment by clusterfack** [comment]
A storage container that cant be worn and is outclassed by the toolbelt?

**Comment by 9600bauds** [comment]
They hold a lot of all items, not just tools, and can carry metal
I've used them a few times to make conveyor belts 
But hey, not everything needs a use so let's give them 5 force, right?

**Comment by clusterfack** [comment]
A carried backpack can carry metal as well

**Comment by 9600bauds** [comment]
If it wasn't convenient to use the toolbox, I wouldn't have used it. Helps carrying the circuit boards too.
Why are we even arguing about this? Where did this "things are only allowed one use" notion come from? Let's also make the welding tool a bad weapon and remove screwdriver eyestabbing, they already have other uses.
Except not because that's stupid and we're just going in circles in this argument and this latest circle is probably the most far-fetched yet.

**Comment by Boxe** [comment]
:eggplant:

**Comment by clusterfack** [comment]
Who is arguing for 'precisely one use' when we we're just arguing about whether the toolbox has ANY

**Comment by ComicIronic** [comment]
You can make the toolbox twohandable and have that increase its force

**Comment by PJB3005** [comment]
Merge when?

**Comment by ihadtoregisterforthis** [comment]
How much damage did it settle at?

**Comment by 9600bauds** [comment]
Everyone said 15 but Clusterfack doesn't want to change it

**Comment by clusterfack** [comment]
"Everyone said 15"

**Comment by Exxion** [comment]
image

**Comment by clusterfack** [comment]
Except not a single person who supported this PR with a thumbs up on the OP even 'voted' in that poll 
(excepting skullyton who both thumbed up my pr and thumbed it down)

**Comment by Exxion** [comment]
>Only people who like the PR enough to thumb it up have valid opinions

**Comment by FudgePucker** [comment]
How much force is on other weapons?
How much more damage does the toolbox at 15 do compared to a lit welding tool.

Sure tool boxes are everywhere, but grabbing a crowbar and getting some tiles to throw at people as it stands deals more damage, and fits in your backpack. A welding tool fits in your pocket and deals more damage. A bar, some wire, a wirecutter, and a power cell makes a stun baton, letting you stunlock murder people, it also is concealable in a back pack.

The fact that you can't store toolboxes makes them the worst weapon choice, the only reason to use one in a fight is as a last stand and you have not prepared ANYTHING, a welding tool is better. Even then just going for a disarm shove is better.

**Comment by clusterfack** [comment]
>Just make a poll in the middle of the thread from people who are buttblasted where not even a single of the PR's supporter votes in it and assume its what people have unanimously voted for

**Comment by Exxion** [comment]
Well
It is what people almost unanimously voted for, so far at least
The impromptu poll was made in the middle of the thread, but was never closed
People can still vote on it
If you really want to pretend people want toolboxes to be the second most powerful melee weapon available to non-traitors, then at least drum up your supporters to vote rather than saying a vote is invalid because they wouldn't.

**Comment by clusterfack** [comment]
We had a vote, it was right at the top of the PR and people made their decision clear. Maybe you should get people to vote after all it is still open rather than saying the vote that objectively has more people voting is invalid.

**Comment by Exxion** [comment]
The OP isn't a vote
What are you even talking about
17 people said they liked the PR, 13 said they didn't
But neither of those say anything about whether people want 15 or 20 force toolboxes, especially considering that the PR isn't atomic and they could have been voting due to the floortiles

**Comment by clusterfack** [comment]
It's a fucking whole lot more valid than your butthurt shit in the middle of the thread 'vote' that nobody fucking voted in except the people who thumbed down the PR.

**Comment by Exxion** [comment]
It really isn't
But anyway, it has been demonstrated in the past that GitHub opinions aren't even really that closely related to the average player's opinion
Make a server vote or two

**Comment by clusterfack** [comment]
Okay, since almost everyone who was against this explicitly voted for 15 force, and since I couldn't care enough, we're doing that.

**Comment by ihadtoregisterforthis** [comment]
>1 check was pending

**Comment by Skullyton** [comment]
>Self merging

**Comment by Skullyton** [comment]
https://github.com/d3athrow/vgstation13/pull/10742

Ya broke the rurus

**Comment by clusterfack** [comment]
Ha "rules"

**Comment by gbasood** [comment]
We talked about it actually before he did it
I would have merged it if not him

**Comment by SangriaMonkey** [comment]
oy vey

**Pull request merged**
