### PR TITLE
purge turfs list

### PR DESCRIPTION
**Pull request by gbasood**
@clusterfack told me this will make the server stop breaking on startup
I don't believe him but hey

### CODE REVIEW

**Comment by gbasood** [comment]
100% tested tag on this PR is no longer a meme
I actually tested this and it compiles and runs
only runtimes are the ones that already happen at round start

**Comment by Probe1** [comment]
That's something.  We really need to get our memory usage under control.  The server should _never_ crash from running out of memory, but here we are.

**Comment by Exxion** [comment]
Might help if we had more than 2 gigs

**Comment by PJB3005** [comment]
We still aren't crashing from running out of memory very often.

Why BYOND manages to fail to create a list of ±24 MB (assuming each entry in the list takes 16 bytes of memory which is already really bloody large) is BYOND me.

**Comment by Exxion** [comment]
Because just about every single fucking thing you do to a list copies it internally, apparently
According to Lummox, the `Out of resources!` runtime is thrown *exclusively* by `list.Copy()`, which means every line that has thrown that runtime does something that internally copies the list
Most notably, declaring a `for in` loop

**Pull request merged**
