### PR TITLE
Stuff Niggly sprited but couldn't be assed to code so I had to:

### PR DESCRIPTION
**Pull request by ghost**
@NigglyWiggly
- Adds pajama hats, which you can now find in the PJ closet
- Adds greaser outfits from the suit dispenser.
- Adds casual hoodie and jeans or casual hoodie and skirt.
- Adds a keyhole sweater
- Adds winter casualwear and spring casualwear to the winter crate and mixet closet respectively

(yes I know it's a feature but I had nothing better to do)

### CODE REVIEW

**Comment by ihadtoregisterforthis** [comment]
Of course you had to

**Comment by Exxion** [comment]
OTP

**Comment by sonime** [comment]
OTP

**Comment by 9600bauds** [comment]
OOP

**Comment by ghost** [comment]
These are hot.

**Comment by clusterfack** [comment]
How much pillow talk did it take to convince you to do this

**Comment by SkowronX** [comment]
images

**Comment by NigglyWiggly** [comment]
@SkowronX

**Comment by 9600bauds** [comment]
##WARNING: Type /obj/item/clothing/under/greaser does not inherit /atom/New().  Please ensure ..() is called, or that the type calls AddToProfiler(). in code/game/atoms.dm at line 130 src: the greaser outfit 

Sounds serious

**Comment by ghost** [comment]
Whoops

**Pull request merged**
