### PR TITLE
Adds a hairpin to the waifu supply crate

### PR DESCRIPTION
**Pull request by Konater**
This is a serious pull request

### CODE REVIEW

**Comment by NigglyWiggly** [comment]
> blackf

The Blackf jumpsuit is feminine no matter who wears it.
Even if they are a man.
What I'm saying is it gives men tits.

**Comment by Konater** [comment]
Well fuck

**Comment by kol1th** [comment]
you're my hero

**Comment by xpcybic** [comment]
@NigglyWiggly 

> What I'm saying is it gives men tits.

Are you trying to tell me there aren't people on the server who want this

**Comment by ghost** [comment]
@xpcybic He's saying he wants it

Able to hack doors with the hairpin when?

**Comment by NigglyWiggly** [comment]
Celt you already know tits do nothing for me.

**Comment by Konater** [comment]
muh waifus

**Pull request merged**
