### PR TITLE
kicking admins without worrying about flags

### PR DESCRIPTION
**Pull request by Intigracy**
by request of @Aurx

### CODE REVIEW

**Comment by Aurx** [comment]
Rational for change: AFKmins is a bit of a problem, and kick-abuse is easy to solve in the event it occurs.

**Comment by clusterfack** [comment]
Why is having an AFK admin a problem

**Comment by ghost** [comment]
'faggot spaced me, admins wouldnt do anything so I went Diona and beheaded the shitbag' Niggly was AFK in lobby, no ahelps were answered, so he went diona twice, beheaded his previous killer, and spaced the body over those two lifetimes. - jimdandy PERMANENT

**Comment by Aurx** [comment]
There's no issue with an AFKmin who's just alt-tabbed or otherwise able to respond to ahelps, but when they're well and truly gone it can cause issues.  
Players can't tell if an admin is ignoring them or AFK.  When all 'mins are either AFK or busy, ahelps go untouched and players assume silly things or get irritated.  Worse, players ahelp and don't follow up later or make a ban request, but the ahelp goes unhandled due to no admins actually being there.  
Ideally admins would log out instead of going truly AFK, but that doesn't happen.  By allowing anymin to kick anymin, we can be self-policing and kick anymin that's actually AFK.

**Comment by clusterfack** [comment]
@Skullyton That's entirely different. You're describing a situation with NO admins online answering his ahelp.

This system would be one in which there are afk admins and non afk admins and the non afk ones are kicking the afk ones for some(?) reason.

**Comment by clusterfack** [comment]
How is being able to kick other admins who are supposedly AFK going to help this problem in any way?

**Comment by ghost** [comment]
@clusterfack He saw that there was an admin on, and being a player was unable to see the status of them (Said status being AFK in lobby), so assumed that when his ahelps weren't answered, they were being ignored.

**Comment by clusterfack** [comment]
@Skullyton I can guarantee you that having afk admins online giving the illusion of watchfulness is going to make the players act far more responsibly than having none online at all. And **either fucking way** how would this have been solved by this PR? No one was there to kick niggly.

**Comment by PJB3005** [comment]
Tbh somebody that does something like that is likely to slip up sooner rather than later anyways.

**Comment by Aurx** [comment]
By telling admins to kick AFKers before they log off.

**Comment by clusterfack** [comment]
That's retarded for a number of reasons that I shouldn't have to explain to you but will anyway:

1. Having an AFK admin makes the players act better than having no admins online at all, there's a reason shitter safaris involve stealthmining and why I used to afk overnight when we had NO late night admins for months back in the day.
2. Literally nothing about the AFK system tells you if an admin is actually there to listen to ahelps or not.
3. I cant think of a single thing such a policy would help, even disregarding the actual damage I think it will do.

**Comment by Aurx** [comment]
I am of the opinion that moderate and reported grief is better than mild and unreported grief.  
I also don't notice much shittery when I shitter safari these days.

**Comment by clusterfack** [comment]
>I am of the opinion that moderate and reported grief is better than mild and unreported grief.

What do you mean by this

**Comment by Aurx** [comment]
That I feel players are more likely to report grief via ban requests etc if they know there are nomins and that such is preferable to the decreased grief but ambiguity and inaction caused by only AFKmins.

**Comment by clusterfack** [comment]
Even in the era of no late night admins, this is something that never happened. It's simply not bore out by history.

**Comment by Aurx** [comment]
It's entirely possible I'm being overly optimistic.

**Comment by mrpain666** [comment]
No harm in giving us the ability to try. If it doesnt work we can stop doing it. Just give us the chance to test it.

**Comment by clusterfack** [comment]
The chance to test what? People hopefully making more ban requests because all admins are offline? That's a fucking terrible idea.

**Comment by Aurx** [comment]
It's better than ahelps going unheard and not being acted on.

**Comment by clusterfack** [comment]
It's actually not. I'm sorry guys but this is just too stupid for me to allow.

**Comment by Intigracy** [comment]
Hi errorage.

**Comment by Intigracy** [comment]
Lately when there's no admins on someone pops on discord and pings @server admin and then someone hops online.

This doesn't happen if some faggot has been AFK the entire day just completely ignoring the game.

Way to abuse your position as a coder to veto a completely administrative policy though.

**Comment by ComicIronic** [comment]
We can set something up on the server that will automatically ping the Discord channel when a new player joins and there hasn't been an active admin in x minutes.

**Comment by PJB3005** [comment]
Working on Discord ahelps right now.

**Comment by Aurx** [comment]
Discord ahelps solves the issue too.

**Comment by Aurx** [comment]
Of course, this means I now have to try to herd my catmins into discord.

**Comment by mrpain666** [comment]
I absolutely despise discord

**Pull request closed without merging**
