### PR TITLE
Blob Rebalance

### PR DESCRIPTION
**Pull request by Kurfursten**
This is essentially an entire rebalance of how Blob operates to make it more passive/outpost based instead of getting a few resource blobs before slamming down 20 normal blobs in a row.

I've done some testing with this and I'm pleased with how it feels so far, but I'd like to do some more maybe on the test server with other players.

***Costs***
Node 60->15 (-75%)
Attack 5-> 15 (+200%)
Shield 10->5 (-50%)
Resource 40->30 (-25%)
Factory 60->45 (-25%)

*The main function of this change is to make it easier to access defensive staying-power tools like shield blobs and nodes, but harder to spam click down individual attackers with a little bank.*

Note that now it costs as much to attack one time as to make an entire node. That's really significant! It also means if you spend 90 resources you can only attack six times in a row, so better make those count.

***Other Changes***
* (Buff) Can alt click your core to toggle "restrain blob" (will not passively eat walls, can still actively eat walls). Blob starts like this. No cost. Used to remain stealthy when you first pop, or keep cover walls from collapsing.
* (Buff) Objects under a blob will get hit (like Phazons)
* (Buff) Objects under a blob near the core will get hit multiple times for massive damage
* When a blob hits a TTV, it will trigger it (mostly to make sure the above changes do not invalidate bombs)
* (Nerf) Resource blobs create resources half as often (4 SEC->8 SEC)
* (Nerf) Core income lowered from 4->2 per 2 sec
* Adjusted Blob intro text to be more concise

🆑 
* tweak: All blob costs massively changed to encourage node and shield development over rushing down enemies with expand blob.
* tweak: You can now restrain your blobs from melting walls passively by alt clicking your core.
* tweak: Objects under blobs (like Phazons) will get hit by blobs.

### CODE REVIEW

**Comment by DrSnips** [comment]
One of my issues with blob is that it completely invalidates several players and divides the crew in a few ways. 
People with laser guns
People with suits
People with crowbars/firelock access
People who have a combination of some but not all.
A common misconception is that blob is the vs the whole crew and this isn't quite true. If you fall in #4 you're most likely not able to assist in fighting it, an example is medbay being locked in their own area due to a lack of crowbars or general crew lacking #1 or #2. #2 is especially true since the lack of a suit means you will be taking constant low pressure damage due to it always being vented in blob so long term fights are impossible. Blob attacks usually end in broken bones and internal bleeding which requires you to be out of the fight and when almost every attack results in one you lose numbers fast.
I'm not sure how to address these issues but feel free to throw ideas out there.

**Comment by SGuivenne** [comment]
How about instead of this we actually put some sort of cooldown on slime attacks so it cant be spammed to instakill people.

**Comment by Exxion** [comment]
Like it used to be before newblob
Remember when it was actually possible to fight the blob in melee and wasn't just suicide?

**Comment by Kurfursten** [comment]
I studied blob on local for hours, making edits to the code so I could see how fast resources were coming in from where, and which blobs were actually getting pulsed, and how often.

My first conclusion was **old blob got resources and expanded much more slowly**. It wasn't even a matter of resource blobs triggering more often since they have a timer delay, but tons of resources coming from the core right off the bat. But this surprised me because I expected the opposite: most modern blobs don't feel unstoppable until they have a couple resource blobs. I realized that part of the relationship was that **lasers are stronger than they used to be**, which is why a fresh blob dies so easily early on. There was another difference too **because old blob pulsed more slowly, it didn't destroy the very reinforced walls it wants to use for cover, meaning old blob got outed later**.

In order to be able to survive against new lasers blobs need to be able to generate shields and nodes more cheaply, and some of their income is justified to rebuild destroyed blobs before focus fire takes out their core. But while I wanted fast rebuilding to be possible, **new blob had a habit of saving up 100 resources to slam down 20 expansions at once, running over all attackers**. My solution to this was dramatically increase rebuild costs, which means you can desperately try to cover your core (and ideally upgrade to shield) but it is extremely expensive to quickly lash out more than 1-3 tiles.

I hope this explains my logic for all of the changes. I know it can be hard to see without experiencing it yourself.

**Comment by Exxion** [comment]
I don't know this for certain, but I'm *pretty* sure that oldblob had a brief cooldown on expanding, too, so you couldn't just rocket across a whole room to chomp someone walking by in an eighth of a second

**Comment by Kurfursten** [comment]
Part of the reason for that was Deity made a QoL change that added ctrlclick to expand, which made rocketing much easier. Before that you had to click the expand blob power, then click the tile you wanted.

**Comment by Exxion** [comment]
>It was incidental all along

IMO there *should* be an actual cooldown
Like a quarter second or something
But I guess we should see how this PR goes first

**Pull request merged**
