### PR TITLE
Pox raiders, datums style

### PR DESCRIPTION
**Pull request by ShiftyRail**
[role] [content] [wip]

The long awaited sequel.
Vox raiders are a midround ruleset, which pools up to 5 ghosts to raid the station. They've got 30 minutes to raid as much stuff as possible, with a random weight defined at the start of the heist (engineering items, medical items, etc, can be defined as the priority).

They can also be tasked to abduct brilliant minds/high value targets for the shoal, with an associated score.

Once the raid is finished, the score of the team is counted and will be displayed on the final round report, and immediately to the vox raiders (and maybe to ghosts, idk).

The score will be saved to file (using persistence subsystem) and compared to the best score of the month/best score of all time.

Done :
- [x] : the faction and role itself
- [x] : midround ruleset
- [x] : equip raiders
- [x] : countdown for the time

To do : 
- [x] : Handle evacuation of abducted prisonners
- [x] : Generate objectives
- [x] : Give the vox designated lockers to store their shit
- [x] : Count and display the score
- [x] : Save score to file

:cl:
- rscadd: Vox raiders are back. Watch your coins!

### CODE REVIEW

**Comment by ValkyrieSkies** [comment]
For the evacuation of prisoners and loot, just give them a static teleporter device on their ship which is purely for dropping off loot; functionally it'll just delete whatever is placed inside and add the points to their score.

When the 30 minutes are ending, maybe give them a countdown to get back to their ship before it departs permanently and deduct points for every raider they're missing (bringing back a corpse is fine though).

**Comment by Durgen** [comment]
raiders always lacked the tools for abduction
give them 1 or 2 cham jumpsuits

**Comment by ghost** [comment]
Will raiders have their hands tied by OOC rules preventing them from murdering crew for no reason or will they be actual antags?

**Comment by ShiftyRail** [comment]
I was of the belief that the "inviolate" jectie was nothing more than a playstyle suggestion and if I remember correctly, one person got banned for it, years ago.

**Comment by ghost** [comment]
That doesn't answer the question.

**Comment by ShiftyRail** [comment]
Well to me this never was a rule more of a suggestion so I don't know maybe ask more/other admins
I would personally say it's just a suggestion but it's not my call to make alone

And also I got one (1) headmin ruling that they're antags and as such, valid to you and don't have restrictions in what they can do

**Comment by aceedex** [comment]
no borgs hijacking bird shuttles no buy

**Comment by Coxswain-Navigator** [comment]
Code some real pirates
gas the vox

**Comment by AI-Is-Rogue** [comment]
Different pirates based on each race when

**Comment by GoodG1448** [comment]
martian squad ufos that kidnap people for probing when

**Comment by ValkyrieSkies** [comment]
The Inviolate was removed from Vox Raiders like the year before they were removed anyway.

**Comment by KingofHONK** [comment]
no, we must go even FURTHER.  If abducted, the prisoners are now in gay vox baby jail and the raiders now play a warden role where they must make sure they dont make THE GREAT ESCAPE

**Comment by coldcola** [comment]
bring back the inviolate! 

just kidding don't bring back the inviolate or this antag type

**Comment by PaulRitter** [comment]
just make them put all the booty in a vault/cargobay on the ship or something and count a sum from the items in that area when the ship leaves

**Comment by Intigracy** [comment]
The only guy who got banned for the inviolate that I know of only got banned from raider for it, nothing else

**Comment by FudgePucker** [comment]
Being abducted sounds boring as hell if there is no way to feasibly get out.
Make it so that ghosting out on the ship doesn't give you a cool down on becoming a ghost role.

**Comment by ShiftyRail** [comment]
@FudgePucker, you will be sent back to the station in an inflatable once the vox are finished.

**Comment by Gringonius** [comment]
What incentive do raiders have to actually just take themselves out of the round other than pointless numbers?

**Comment by ShiftyRail** [comment]
@Gringonius Having their ckey and their character names remembered for the ages if they beat the scoreboard.

**Comment by ShiftyRail** [comment]
Putting this on hold while I'm taking a break

**Comment by ShiftyRail** [comment]
If I don't finish this this week-end I'm quitting /vg/ forever

**Comment by MadmanMartian** [comment]
>all those DMM conflicts

Bet you wished you implemented that load stuff I talked about

**Comment by ShiftyRail** [comment]
Almost there. Need to do the necessary mapping (again), but this shouldn't take too long ; it's just adding a few landmarks to the vox shuttle.

I also need items for low, medium, and high priority items. 
After that, this should be ready for a live test.

**Comment by strawberrytan** [comment]
wot if you could buy back stolen items from a soldering hacked cargo console, like those random boxes of returns you can buy off amazon

**Comment by ShiftyRail** [comment]
@strawberrytan I'm focused on finishing this on time, but this is definitively a good idea.

**Comment by ShiftyRail** [comment]
Done for me, just need to test it

**Pull request merged**
