### PR TITLE
New ways to get blood as vampires

### PR DESCRIPTION
**Pull request by ghost**
[content][role]

## What this does
* Adds a way to silently drain blood from people as vampires, a roundstart spell called "Sleight of Teeth" which is a toggle. (default off) When on, there is an initial delay of 30 seconds before biting, (15 for mature vampires) and draining takes twice as long.
* Drinking blood in a reagent container that has DNA tied to a human player in the game can now add to your total and usable blood count by half the volume ingested, fully for mature vampires and a quarter if the player is unconscious or dead.

Let me know if these could be adjusted or balanced. Would ideally like #32889 merged before this so I can implement a better volume check.

## Why it's good
Adds 2 new less lethal or obvious ways to drain blood from people with appropriate drawbacks.

## Changelog
:cl:
 * rscadd: Vampires now start with a spell that allows silent draining of blood, however it has a lengthy preparation time and is less time efficient at draining overall.
 * rscadd: Vampires can now gain blood power from drinking the blood of any active player if in a reagent container, with doubled effects on their total and usable blood counts if they're mature, and halved if the player is unconscious or dead.

### CODE REVIEW

**Comment by WindowsErrors** [comment]
my cat sure as hell doesn't use silent biting

**Comment by gurfan** [comment]
sleight of teeth
Can't you think of something more creative than "silent biting"?

**Comment by Blithering** [comment]
> sleight of teeth Can't you think of something more creative than "silent biting"?

Scrape and lick.

**Comment by ghost** [comment]
> > sleight of teeth Can't you think of something more creative than "silent biting"?
> 
> Scrape and lick.

Used both of these, first as name and second in description.

**Comment by Eneocho** [comment]
>Scrape and lick.

I would be FAR more suspicious of the guy that just scratched my arm and started licking it/his hand.

**Comment by Eneocho** [comment]
>Drinking blood in a reagent container that has DNA tied to a human player in the game can now add to your total and usable blood count by half the volume ingested, fully for mature vampires and a quarter if the player is unconscious or dead.

Does it check for a ckey? Could you get valid blood from a morgue body that got cloned?

**Comment by ghost** [comment]
> > Drinking blood in a reagent container that has DNA tied to a human player in the game can now add to your total and usable blood count by half the volume ingested, fully for mature vampires and a quarter if the player is unconscious or dead.
> 
> Does it check for a ckey? Could you get valid blood from a morgue body that got cloned?

It checks the mobs of player_list, which all have clients, so no.

**Comment by Kurfursten** [comment]
Surprised we didn't see more votes on this, but it seems people want it. If nothing else we can try it, maybe it will spice up vampires a bit?

**Comment by Eneocho** [comment]
wiki updated

**Pull request merged**
