### PR TITLE
Adds stamps for the warden, the internal affairs agent and the chaplain

### PR DESCRIPTION
**Pull request by brndd**
[sprites]
[general]

A couple of days ago I was playing HoP and told someone asking for armory access to bring me a stamped paper of consent from the warden. They came back telling me that the warden has no stamp, and they were right. That's how this PR was born.

The IAA and warden stamps are just recolours of existing stamps, but the chaplain's stamp (as in, the stamp it makes on the paper sprite) was made to look like a seal, because those are holier.

I also added the stamps on all the maps. Merge conflicts ahoy.

:cl:
 * rscadd: Added stamps (for paperwork) for the warden, the IAA and the chaplain. The chaplain's stamp produces a holy seal rather than a boring mundane stamp.

### CODE REVIEW

**Comment by SirSkeleto** [comment]
loving the seal tbh

**Comment by Blithering** [comment]
Do these have the same washing machine interactions as other stamps?

**Comment by brndd** [comment]
They have washing machine interactions, but not the same ones. Warden's stamp creates a dark red jumpsuit, IAA creates a ~~dark~~ light blue one, and Chaplain creates a red one. If you have better ideas for what they should create, let me know.

**Comment by Durgen** [comment]
Balance tag please

This makes the stamp collection minigame a bit more difficult

**Comment by Kurfursten** [comment]
Maybe IAA should be green like the centcomm stamp

**Comment by brndd** [comment]
> Maybe IAA should be green like the centcomm stamp

Good idea.

**Comment by Kurfursten** [comment]
Mapdiff didn't run but I read the diff manually

**Pull request merged**
