### PR TITLE
Moneybags poked at, Mint poked at with a bargepole

### LINKED ISSUE #8423: Overfilled moneybags change resolution when opened
help me
I don't know dick about coding but when a money bag is left at a coin press and fills over its limit it does this nonsense.

### LINKED ISSUE #9641: Moneybags are limited to 7 items
#### Description of issue

The moneybags that are created when crafting coins at the coinpress are limited to 7 items. The only exception seems to be the coinpress itself, if you have a bag with 10 coins, take one out and try it to put it back in, it says it's full.
#### Difference between expected and actual behavior

To fill all these coins back into the bag.
#### Steps to reproduce

Acquire materials, make coins, take coin out, try to put it back in.
#### Server revision

f65a28b3b5641cd91b8ca5e5d8fa3584c7df973e Current 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by ghost**
Money bags limit has been drastically increased, from 7 to 300, so you can actually get a sizable haul in them now.

Closes #9641 

Additionally turns on the option for items to be 'compressed and numbered' rather than showing each individual item, because it was causing some weird visual nonsense if the mint was well supplied and left on.

Closes #8423

Attempted to rework how the mint puts money into moneybags in proximity, but ran into a bit of a brick wall when doing so, so just commented it out like the scrub I am. This also disables the mint from making a new money bag each time it can't find one in proximity when printing coins.

Because this kills the primary source of money bags, added 2 money bags to the mining equipment crate. They're also acquirable from a biogenerator (Cheaper to create than an ore bag, for some reason)

### CODE REVIEW

**Comment by Intigracy** [comment]
Nice changes all around.

**Comment by ghost** [comment]
yay

**Comment by gbasood** [comment]
@Clusterfack thinks that compressed and numbered doesn't work btw

**Comment by ghost** [comment]
Welp, it was working when I was testing it. I'll take a look when I get back

**Comment by ghost** [comment]
It's working for me right now
military fortress seven 2016-04-29 153307

**Comment by clusterfack** [comment]
Thats great news, I had zero confidence that it would

**Pull request merged**
