### PR TITLE
Botany additions

### LINKED ISSUE #3192: Only 2 botanist lockers but 3 botanist job slots - Box map
There's only 2 botanist lockers in botany but 3 botany job slots, please add another botany locker.

Also https://github.com/d3athrow/vgstation13/issues/3166 while you're at it.

Perhaps another spade too. I should probably learn how to map.

### PR DESCRIPTION
**Pull request by ghost**
botany

Adds another botany locker, adds a spade, plant clippers and a bucket to each botany locker.

Moves xenobotany machines one tile to the east, moves contents of one table into the botany hydroponics crate.

Should fix #3192 and #3166

### CODE REVIEW

**Comment by CptWad** [comment]
:+1:

**Comment by Duny-** [comment]
>machine over the apc terminal
Otherwise it looks alright

**Comment by Probe1** [comment]
wut

we don't need 3 spades 3 wirecutters and 3 buckets.  what all did you add?

**Comment by TermedClepe** [comment]
@Duny
The machines were over the apc terminal before, all I did was move them 1 tile to the east.

@Probe1
I only added what I wrote in the first post.

I recommend you actually play botanist for a round instead of hysterically crying over something you don't understand. As it is without this change, you already could spawn as botanist, never leave botany and feed the entire station twice over in the first few minutes.

The only thing that this changes for a botanist is the presence of plant clippers, which are literally just wirecutters that are part of botany roundstart preparation route regardless since you need to hack your vendor with a multitool for better plants, otherwise everything was already in botany available.

I do not see how having each botanist have their own set of basic job tools is in any way negative as opposed to having a single tool shared between all 3. If you can somehow produce an argument against this then by all means go and start removing tools from other departments with the same reasoning.

**Comment by Probe1** [comment]
Termed pls, I'm a very capable botanist and am well aware of what is spawned.   If you want a ton of wirecutters, go to any given youtool or cargo or research or the million other places to get them.  

There's no reason to give every department everything and that's reason enough.  Don't get your panties in a twist.

**Comment by TermedClepe** [comment]
@Probe1
>or doing a proper job and getting plant clippers in the game
Those are plant clippers not wirecutters.

Meta has even more gear for botany, more trays, bigger department, extra hoe and a hatchet in addition to several full lockers, a hand labeler, a condimaster machine and nobody is making a big deal out of it but you.

I don't understand how you think buckets, spades and plant clippers will somehow make botanists never leave department or somehow lower player interaction. Buckets are purely cosmetic as you can poop out as many flasks from chem master as you want to serve the same purpose, or just use one of the beakers. Plant clippers are just a trip to nearest tool vendor which you have to make anyway to hack your vendor.

Where's this loss of player interaction you claim? How does botany stop relying on other jobs with this change?

**Comment by 9600bauds** [comment]
There's also the fact that after you have a Robotician make you a farmbot you only have one single spare plant analyzer.
Given that botany is often a shared job, this is a little too tight compared to other jobs. I've never had to order a kitchen supply crate as Chef unless kitchen got bombed the shit out of, or ran short of device analyzers as Mechanic.

**Comment by d3athrow** [comment]
plantcutters may just look like wirecutters as they're a child of wirecutters I think.

**Pull request merged**
