### PR TITLE
Flipped an inequality sign to fix plants growing 35% slower than they should be and never healing on their own.

### PR DESCRIPTION
**Pull request by despotate**
Fixed waterlevel detection stunting and harming well-watered plants, and healing water-starved plants.

This has been around for years and apparently no one's ever noticed you can just grow shit without water, and it'll do so faster and healthier.

### CODE REVIEW

**Comment by Exxion** [comment]
It's  TECHNICALLY balance
But nobody will  disagree with it anyway

Also, in the future, rather than closing the bug report before opening the PR, leave it open but put
"Fixes #[whatever number the bug report is]" in the OP and the issue will automagically close when the PR is merged
It's not a big deal, though, for this one

**Comment by Exxion** [comment]
Also I want to make a label for stupid one-character errors causing significant problems
Like this and #11547

**Comment by despotate** [comment]
Putting the "hydro" in "hydroponics" isn't a balance suggestion, it's a bugfix.

**Comment by Exxion** [comment]
[Balance] means it changes balance at all, at least according to the tagging guidelines
Which is why I felt the need to explain myself because it barely applies here

I'm not sure if anyone knew this bug existed, but you might want to add a changelog, just in case

**Comment by Exxion** [comment]
Yeah I am going to have to insist on a changelog, but do that and it's golden

**Comment by despotate** [comment]
No idea how to do that.  Babby's first github experience here.

**Comment by despotate** [comment]
Did it.

**Comment by Exxion** [comment]
I don't think there's supposed to be a space before the hyphen
It might work either way, but I'm not sure

**Comment by despotate** [comment]
"There needs to be a space after the - and before the prefix."

Confusing instructions - removed the space before the -.

**Pull request merged**
