### PR TITLE
Some more kicking stuff

### LINKED ISSUE #8544: You can kick paitings off walls.
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> bef905aad65ed3da2ed3b0d1b185921b2013dd84
> 
> General description of the issue
> If you kick a painting, it will move 1 block. Do it correctly and you can kick one off a wall.
> 
> What you expected to happen
> My leg!
> 
> What actually happened
> Kicked a painting into the middle of a hallway.
> 
> Steps to reproduce if possible
> Harm intent, kick intent, kick the crap out of it.

### PR DESCRIPTION
**Pull request by unid15**
- Sunglasses stomping is back
- Kicking machinery makes it shake (just like vending machines). This includes airlocks
- Allowed kicking items of w_class 4. Slightly changed how being strong affects item kicks
- Some tweaks to kicking posters, signs, paintings. Fixes #8544

### CODE REVIEW

**Comment by ghost** [comment]
Webm of shaking airlocks because that sounds awfuk

**Comment by 9600bauds** [comment]
I'm a little bit worried about kicking wall-mounted machinery breaking their offset

**Comment by 9600bauds** [comment]
Nevermind I see you fixed that

**Comment by SkowronX** [comment]
Have the buff gene affect kicking force and what w_class things you can kick

**Comment by unid15** [comment]
removed airlock shaking because it kinda sucked, otherwise shaking is same as vending machines

**Comment by clusterfack** [comment]
You could probably making shaking shear the machine using the transformation matrix so it looks like its swaying on the top side

**Pull request merged**
