### PR TITLE
Starman robots are now kinda chill

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
[He looks kinda chill.webm](https://github.com/vgstation-coders/vgstation13/assets/41342767/c071e9ad-bfcb-486f-99f6-b3b50e3ffa5e)

:cl:
 * rscadd: Starman robots can now do some moves.

### CODE REVIEW

**Comment by MercuriusGH** [comment]
holy shit

**Comment by DeityLink** [comment]
Ok but make it play a short soundbyte of Ronaldihno Soccer 64's title theme

**Comment by ghost** [comment]
Starmen should be a minor antag or something instead of adminbus only. Surprised nobody did anything with it in like the 4 years since I coded it.

**Comment by ghost** [comment]
Also, try setting its appearance flag variable to "2817" to see if that improves the aliasing any.

**Comment by boy2mantwicethefam** [comment]
I'm going to look into providing a better version of it.

**Comment by SonixApache** [comment]
good shitpost

**Comment by SECBATON-GRIFFON** [comment]
is this a reference to something

**Comment by DeityLink** [comment]
I dunno but a 2D character being smoothly animated doing a capoeira kick or similar [will never not be funny](https://youtu.be/KCLoyhjqph4?si=j2xhGxCf77uepdqC&t=82).

**Comment by kilozombie** [comment]
> Starmen should be a minor antag or something instead of adminbus only. Surprised nobody did anything with it in like the 4 years since I coded it.

It was really jankily coded IIRC

**Comment by west3436** [comment]
> It was really jankily coded IIRC

the fella you replied to coded it lmao

**Comment by kilozombie** [comment]
> > It was really jankily coded IIRC
> 
> the fella you replied to coded it lmao

I was there when the books were written wench, I know what Glass hath brought

**Comment by boy2mantwicethefam** [comment]
chill
It's done but due to the way it's been coded there's a pretty unavoidable bug where it can be in the wrong position for a frame or two.

**Pull request merged**
