### PR TITLE
Ports Noble-series cyborg icon from Paradise

### PR DESCRIPTION
**Pull request by jknpj**
2f55cbf8-ff4c-11e6-876c-95bc58290c87

:cl:
 * rscadd: Adds the Noble-series icon for all basic cyborg types

### CODE REVIEW

**Comment by ghost** [comment]
I really like that service sprite

**Comment by ghost** [comment]
Solid as heck.

**Comment by Exxion** [comment]
THE HANDS ARE LOWER ON THE EAST/WEST SPRITES

**Comment by Blithering** [comment]
Neat, but that poor janiborg having to scoot around doing a handstand to clean anything

**Comment by TravellingMerchant** [comment]
I've never played VGstation but I hope you like the sprites! I had a great time making them.  

I might go back and edit the hands in the future but I'm quite busy at the moment. Who knows!

**Comment by Exxion** [comment]
Oh and also all the ones with stripes on the arms have the stripes missing on the north sprite

**Comment by jknpj** [comment]
Yeah i noticed that, i also messed up the engineering one's eye, let me fix it.

**Comment by TravellingMerchant** [comment]
Did you edit them or something? How exactly did you mess it up?

**Comment by Blithering** [comment]
The eyes are on a different layer, to make em show up in the dark

**Comment by jknpj** [comment]
i forgot to remove the light from the default engineering second icon, as it is animated.

**Comment by SonixApache** [comment]
neat

**Comment by TravellingMerchant** [comment]
Heads up, fixing the borgs arms and making some cosmetic changes. Will let you know when they are done.

**Pull request merged**
