### PR TITLE
Increases rune limit

### LINKED ISSUE #8963: Cultist max rune limit is too low for our current needs
```

 if (rune_list.len >= 26+runedec+ticker.mode.cult.len) //including the useless rune at the secret room, shouldn't count against the limit of 25 runes - Urist
            alert("The cloth of reality can't take that much of a strain. Remove some runes first!")
            return 

```

ritual.dm

This was probably good in 2010-2011 when it was coded but due to an increase in runes, players, and complexity of cult, this should be eliminated or increased from 26.

### PR DESCRIPTION
**Pull request by clusterfack**
Closes #8963 
I honestly don't know how you are using all the runes

### CODE REVIEW

**Comment by Probe1** [comment]
Neither do I but it came up.  I suspect wall runes which probably didn't exist when the limit was added.

**Comment by Imagebard** [comment]
How much runes can you place now? 103? Or 40?
Regardless, :+1: since this doesn't even need to exist.

**Comment by clusterfack** [comment]
With 0 cultists, 25. 
With 4 cultists, 41.
With 9 cultists, 61.

Each cultist has 4 runes to themself, and the powergamers split up the starting 25. 

The number was completely arbitrarily chosen by me.

**Comment by ihadtoregisterforthis** [comment]
Sounds like a good magic number.

**Comment by Intigracy** [comment]
```Incrases```

**Comment by gbasood** [comment]
@Intigracy 
literally unreadable terrible spoiler
I could only see it by hitting edit on your post

**Comment by DrCelt** [comment]
I didn't even know that there was a maximum amount of runes. Huh.

**Pull request merged**
