### PR TITLE
Added a small sound to signal to revheads that they have been converted

### PR DESCRIPTION
**Pull request by ShiftyRail**
From the first ten notes of Wide is my Motherland.
https://www.youtube.com/watch?v=E4p-N4LvhqA

Historically, this was used by the communist countries to preface their propaganda broadcasts.

I noticed that other antags have sort of a "startup" sound and rev doesn't. The theme itself might be a little calm for what the gamemode essentially is, but I like it.

:cl:
- rscadd: Added a new sound to tell rev heads that they've been converted.

### CODE REVIEW

**Comment by Eneocho** [comment]
I feel the audio is a bit too long.

**Comment by ShiftyRail** [comment]
@Eneocho the ingame thing is 10 seconds and 10 actual notes

**Comment by Servalfang** [comment]
don't like the music. Get something else maybe.

**Comment by tuypo1** [comment]
I like the choice of tune

**Comment by Eneocho** [comment]
I know, but it still feels kinda long to have a 10s audio.

**Comment by tuypo1** [comment]
Yeah maybe bring it down to 5 seconds

**Comment by ShiftyRail** [comment]
You can't, because that wouldn't be the actual interval signal

**Comment by Kurfursten** [comment]
Alien 2s
Traitor 4s
AI Traitor 10s
Vampire 7s

It's not too bad considering some of what we do have, main worry is how calm it sounds but I guess it's fine

**Pull request merged**
