### PR TITLE
ZAS no longer blows/sucks things that are pulled or grabbed

### LINKED ISSUE #11879: ZAS-pulling makes body recovery very difficult
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
Due to the "fixing" of ZAS, it is nearly impossible to recover bodies by hand now thus making paramedic's job useless.
If a body is in space, trying to bring the body through an airlock causes them to be sucked away by the airflow even if the paramedic/doctor/good samaritin is wearing magboots.
Simply opening the airlock will cause a body in space fly away from the station if it is resting outside of any exterior exits to the station. 
For example, if anyone who got sucked out from the double airlocks (which might I add has no use in escape anymore due to the ZAS fixing because they are full of pressure which negates any use they might have provided in the past) were to toss a belonging in an attempt to return to the external airlocks, anyone attempting to rescue them would simply end up chucking their corpse into the unrecoverable depths of the vast unknown of space.
This means that the only way to recover any bodies outside of the station is to telescience it back into the station or it is lost forever. I do not think you intended to have this issue occur when fixing ZAS.

### PR DESCRIPTION
**Pull request by Sprok0**
Trying to retrieve a body or something from outside the station airlocks should be reasonably possible now.

Fixes  #11879

### CODE REVIEW

**Comment by SkowronX** [comment]
finally

**Comment by Probe1** [comment]
I feel like it should only be grab but that will probably impact how aware people are that the feature exists so it'd be better to do both.  Even if ideally the player was required to switch to grab and grab someone.

**Comment by Probe1** [comment]
Also I'm very glad you addressed this because someone wanted to change our entire atmospheric system over it instead of just doing this 😆

**Comment by Sprok0** [comment]
If it was only grab, it wouldn't work on canisters and lockers and whatnot

**Comment by uazuaz** [comment]
nice, thanks

**Comment by 9600bauds** [comment]
Doesn't this let two players become ZAS-immune by passively grabbing eachother?

What if this just applied the airflow effect to the thing that's grabbing you instead?

**Comment by Exxion** [comment]
Maybe just
Don't do it with grabs
Because two people *can't* pull each other

**Comment by Sprok0** [comment]
It only stops being moved by zas, you'll still get knocked down if you don't have magboots, at which point the grab/pull breaks and you get smashed into walls

Also, two people can absolutely pull each other, I tested that specifically

**Comment by uazuaz** [comment]
if you're ZASed you'll lose the grip/pull, therefore the item you were grabbing/pulling will be also ZASed.
this is useful when you're using magboots, pulling people and stuff inside the station will not be a pain in the ass anymore.

**Comment by 9600bauds** [comment]
Then it's probably OK

**Comment by carshalash** [comment]
On one hand I'll no longer get to laugh at people while being a ghost watching some poor sap fail to save someone, on the other hand it wont happen to me anymore.

**Comment by Intigracy** [comment]
Yes.

**Comment by Probe1** [comment]
My merge valids!

**Pull request merged**
