### PR TITLE
Fucking hell Celt

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes assholes being able to @​everyone the admin Discord channel server side. Fixes on my end already done so this only needs to get merged.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Can you change the description to actually reflect what you've done, which is make messages not ping the Discord if there's an admin online on the server?

**Comment by PJB3005** [comment]
Uh, what? All this PR does is bring the server up to date with https://github.com/PJB3005/MoMMI/commit/68e8daad99ac28e4d27b64d1a2e80652f9918cb0 on MoMMI's side.

If there's any actual functionality changes then please point them out, because that's not intentional.

**Comment by ComicIronic** [comment]
But this is clearly doing something to the logic, because otherwise you wouldn't have added an argument to a proc.

If it's not changing anything, why does it exist?

**Comment by PJB3005** [comment]
Because before I made that commit on MoMMI, you could actually ping everyone in the Admin help channel on discord by Admin helping the discord ping role sequence (`<@&

**Comment by PJB3005** [comment]
God fuck you GitHub mobile there was no way I hit the comment button and you know it.

Anyways if you just send @ everyone as Admin help it'd piss off everyone in the Admin channel because they just got troll pinged. So what I did was, I made MoMMI filter out mentions by putting a zwsp after them, and removed the `{ADMIN_PING}` escape sequence because of how open to abuse it was, and I just made the HTTP GET sent to my server to actually make MoMMI say something have an argument for whether to ping server admins, which this new code uses.

This will need to be merged for the pings to work again by the way.

**Pull request merged**
