### PR TITLE
Castle should no longer be broken + Travis additions

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Added Snaxi, Castle, Lamprey, xoB and boxesstation to Travis

### CODE REVIEW

**Comment by DamianX** [comment]
The changelog is meaningless to players

**Comment by boy2mantwicethefam** [comment]
It's good for admins that want to bus

**Comment by DamianX** [comment]
ok retard

**Comment by GreatBigFailure** [comment]
I think most players understand what "Map now compiles" means.

**Comment by ShiftyRail** [comment]
This kind of information has no direct impact on the game and on players. You don't need to make a CL for it. Please remove it.

**Comment by boy2mantwicethefam** [comment]
k

**Pull request merged**
