### PR TITLE
Requests console logging

### LINKED ISSUE #15242: RC consoles messages aren't logged
#### Description of issue
Messages sent with RC consoles, the green things on the wall that people use to bug cargo, aren't logged as far as I know.

#### Difference between expected and actual behavior
use RC console to ERP with cargo, find message in logs
vs
use RC console to ERP with cargo, nothing in logs

#### Steps to reproduce 
Send a message with an RC console, check logs

#### Specific information for locating
`/obj/machinery/requests_console`
`/code/game/machinery/requests_console.dm`

#### Server revision
dbf39a1e0c2d781bd9b87ad4491bf02019ca0261

### PR DESCRIPTION
**Pull request by DamianX**
ERPers beware.
Also wow, this is some real oldcode.

Example log line:
> [14:08:28]RC: DamianQ/(Gabriel Harris) sent a message through Medbay RC (Medbay) to captainsdesk. Message: "meet me in dorms". Stamped: <font color='blue'><b>Stamped with the chief medical officer's rubber stamp</b></font>. Verified: <font color='green'><b>Verified by Gabriel Harris (Chief Medical Officer)</b></font>. Prority: -1

Fixes #15242

### CODE REVIEW

**Comment by jakmak** [comment]
What if the RC console whenever it receives a message it PDAs everyone in the receiving department like a service bell but better

Fixed stroke speak

**Comment by DamianX** [comment]
Is that autocorrect or a stroke? Also when you code it, I guess.
The RC console DOES need some work, though.

**Comment by SonixApache** [comment]
"*some*"

**Comment by N3X15** [comment]
Will need configuration changes, will let Pomf merge this if he wants to.

**Comment by ghost** [comment]
If it does pda everyone, the pda will need a toggle like the pda send/receive and the pda's ringer app.

**Comment by chatsonf** [comment]
@d3athrow What's up with this

**Comment by d3athrow** [comment]
Whats up with what

**Pull request merged**
