### PR TITLE
Games vendor from tgstation

### PR DESCRIPTION
**Pull request by brndd**
A friend of mine told we should have this, so I ported it over. Original spritework by WJohn CC-BY-SA 3.0, didn't use any of the code haha avoided agpl again get owned oranges. Original PR here: https://github.com/tgstation/tgstation/pull/33265

The spritework was modified slightly to match the perspective of the rest of our vending machines.

There's not a whole lot to put in this machine **yet**. If/when we add any games in the future they should go in here. I also didn't map this in anywhere (@Kharkov72 can do that) but the library back room is probably the best place to put it.

Oh yeah and I added loaded dice so that there's something more to put in this thing. They roll their maximum roll about 33% of the time.

It sells:
- Playing cards
- Une cards
- Dice bags
- Loaded d6 (contraband)
- Loaded d20 (contraband)
- Skull (premium)
- Wizard card (premium)

:cl:
 * rscadd: Added a games vending machine that sells playing cards and dice and some other junk.

### CODE REVIEW

**Comment by calzilla1** [comment]
Make the "Fun" a bit bigger or the glass a bit taller. Theres a lot of dead space on the top

**Comment by Lokiamis** [comment]
Bring back the janky chess board from oldstation. I'm pretty sure it's still in the code.

**Comment by brndd** [comment]
it's called negative space @calzilla1 look it up

(that's how the original sprite was and I'm not touching it because spriting is the big gay)

**Comment by calzilla1** [comment]
I know, but I like dead space alot more

**Comment by ComradeDispenser** [comment]
Aurora has chess sets, checker sets, tarot cards and I think they have a not-Pokemon and some other type of trading card game in their code.
We could try stealing, I mean borrowing their code for more stuff.

**Comment by Tokanova** [comment]
> Aurora has chess sets, checker sets, tarot cards and I think they have a not-Pokemon and some other type of trading card game in their code.
> We could try stealing, I mean borrowing their code for more stuff.

Steal that code if you're so great

**Comment by brndd** [comment]
Aurora is AGPL so that poses some licensing problems. Though we could just steal the sprites and write the code for them ourselves, because with stuff like trading card games the spritework is usually the most laborious part of the ordeal.

**Comment by spoonylove** [comment]
Contraband tetris circuitboard

**Pull request merged**
