### PR TITLE
Grue gets burnt by lights based on a timer instead of Life() ticks

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
- A 2-second timer counts down for as long as the grue is in the range of a light
- If it counts down to 0 the grue takes damage
- If the grue gets to darkness the timer counts up at twice the speed, back to 2 seconds

Because I'm tired of having to try to smash lights and having to time it to the Life() ticks!

Also featuring:
- A bugfix that prevents the HUD from getting spawned over and over again, meaning that a grue could eventually end up with lots of hidden HUD images
- Immediate darkness updates, the moment the light updates the moment the darkness HUD indicator updates
- two codersprite indicators for the darkness, signifying how long until the timer reaches 0 (it's the light warning but it goes from grey to lighter to bright)

:cl:
 * rscadd: Grues now take damage from lights based on constant exposure rather than at seemingly random intervals due to Life(), with a delay of 2 seconds before they take damage. This "timer" recovers by staying in darkness, at twice the normal speed it decays. The "darkness" indicator will also display differently-colored danger indicators for staying in the light, based on how long until the grue takes damage from the light.
 * tweak: Changed some things about the way the movement penalty and increasing light damage are done for grues. The movement penalty and increasing light damage will happen after the grue is burnt by the light and will persist for 2 seconds before resetting. Continued exposure to the light will, however, delay both from recovering.
 * tweak: The grue's "darkness" indicator will now update immediately.
 * bugfix: Fixed a bug where duplicate grue HUD icons would spawn constantly over and over.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
now reopen the pr to remove the sound

**Comment by Hinaichigo** [comment]
Nice. Maybe you could reduce it to 1 second or something too.

**Comment by Hinaichigo** [comment]
Maybe that HUD bugfix will allow for the stop pulling button and other indicators I wasn't sure how to get working in #32484.

**Comment by gurfan** [comment]
fuck yes. Relying on Life() was so jank.

**Comment by boy2mantwicethefam** [comment]
Reducing it to 1 second would cause the grue to get roasted too fast

**Comment by Hinaichigo** [comment]
Could also decrease the per-tick light burn damage to compensate (could be a single var that controls this to make tweaking it easier in the future).

On that note, you should probably consider moving the `alem_adjust()` and `accum_light_expos_mult` stuff outside of Life() and into your new stuff here as well. That's what handles the increased damage the longer you stay in the light.

**Comment by boy2mantwicethefam** [comment]
Good catch, I didn't consider those procs.
They will now only run when the grue is damaged by the light and should reset after 2 seconds. Exposure to the light will delay the penalty countdown. Being in the dark will reset the light damage multiplier.
As for the faster light burn damage I think it would get too spammy with the sounds.

**Pull request merged**
