### PR TITLE
"Lights on" lowpop event

### PR DESCRIPTION
**Pull request by ghost**
[content][qol]

## What this does
As described in #32491, waivers all minor engineering access and fully charges any SME that charges during the event period, if population is 6 or lower and there is no engineers and SMES are not charging.

## Why it's good
Should help with power failures on a low population.

## Changelog
:cl:
 * rscadd: Stations short on power, general staff and engineering staff can now have their SMES filled by centcomm if a power source can be set up.

### CODE REVIEW

**Comment by pedr69** [comment]
this will fill the SMES even without any intervention on all maps but synergy, since there's an engi-engi SMES on the vast majority of maps, providing engineering with power

**Comment by ghost** [comment]
> this will fill the SMES even without any intervention on all maps but synergy, since there's an engi-engi SMES on the vast majority of maps, providing engineering with power

That also means it won't fire since it does that same avail check in the can_start proc. Might change it to power alert checking instead.

**Comment by Hinaichigo** [comment]
I like the access but I don't like the automagic charging; makes engineers obsolete kinda.
From an IC perspective the crew would be benefited from having the extra power, but from a gameplay point of view it's not ideal I think; it automates something best left to players.
Powercreep in a very literal sense.

**Comment by Hinaichigo** [comment]
Maybe instead of a fixed period, the event could end 1 minute after enough power gets charged into the SMES.

**Comment by Eneocho** [comment]
Instead of magically recharging power, centcom could send one or two filled portable SMES units (the ones you use to sell/buy power) so the crew has to install the SMES themselves.

**Pull request closed without merging**
