### PR TITLE
New Grey Rigs

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Adds 4 new rigsuits fit specifically for greys. Sprites by Blithering, descriptions and numbers by Optimism. I basically just copy pasted a bunch.

greysuitsides
rigsground

From left to right: worker, researcher, soldier, leader
The "Grey Space-Ex" cargo crate now contains either the existing soft suit, or one of the worker, researcher, or soldier rigs. It also now costs 200 rather than the previous 100 credits. 
The leader version is currently unobtainable, it'll likely be vault loot at some point in the future.

-->
:cl:
 * rscadd: 4 new grey-specific rigsuits, 3 of which are available at cargo.

### CODE REVIEW

**Comment by SageOfLight** [comment]
ayyyy

**Comment by ShiftyRail** [comment]
big heads

**Comment by KillFurries** [comment]
Why do g(r)ayys get cool suits? This is anti-human discrimination

**Comment by strawberrytan** [comment]
I don't like the look of the leader suit's colours

**Comment by Blithering** [comment]
@strawberrytan What would you change about the colours to work better?

**Comment by ghost** [comment]
you had me scared and thinking that this would be handed out to assistants for a sec

**Comment by Kurfursten** [comment]
Conflicts

**Comment by GreatBigFailure** [comment]
> Conflicts

Just waiting for a "We'll merge this immediately afterward" to fix them. I'm not risking dealing with dmi conflicts twice. Once is bad enough.

**Comment by Kurfursten** [comment]
You can ping me directly when it's fixed, I have looked at the code

**Comment by GreatBigFailure** [comment]
Closing this one and making another one because conflicts. Don't have time to wrestle with git.

**Pull request closed without merging**
