### PR TITLE
Nu Away Mission: Valkor XV

### PR DESCRIPTION
**Pull request by Optimism333**
## Hopefully it will have been worth the wait... ##
 If you'd just like to read my attempt to summarize this project, skip to the next section.

I'd been wondering for some time about trying my hand at making an away mission in the aftermath of the mothership lab vault. It always seemed like it would be too much to do, and really, it was. I forked out a bit of my own change for the spritework, because if I did sprites, mapping, AND coding again this would probably never get released.

I wasn't planning on making a draft, but I think it's valuable for feedback since I've left the Discord. I would really appreciate any coding advice and general input on this one. Even though it's not even close to being done, I'd value feedback to make sure I don't do pointless work and suggestions for alterations to the mission.

I doubt I'll be able to accommodate any crazy feature requests at this point, but if it's minor and fun, I'll try.

Anyways, enough rambling. Without further ado...

## Valkor VX ##
- A fun getaway to a new alien cave ecosystem, with new creatures to kill and a valuable resource to collect for those sweet space credits!
- Explore the surface of a world on the fringes of Nanotrasen and Mothership territory! Check out a grey mining facility deeper in the caves for more loot and creatures to blast!

### Planned Features ###
- At least three levels (Two finished, third in progress)
- Various alien cave creatures (Nearly finished)
- Interactable flora (Partially implemented)
- Various environmental hazards with some counterplay (Unfinished)
- Radioactive crystals that can be mined and shipped to Centcomm for a significant payday (Partially done)
- Some new ayy-themed enemies (Sprites received, coding unfinished)
- Some fun loot ideas (Still brainstorming)
- Unique ambience soundtracks (Received, not yet implemented. Thanks DonteVIII!!!)

### Level 1 Preview ###

- The landing zone and Nanotrasen FOB. The "safe zone", where players can get kitted or drag people back who got into trouble

### Level 2 Preview ###

- The upper caves. Lightly radioactive with small pools of corrosive acid. And there's some creatures living out in the dark as well, only illuminated by the light of crystal clusters. Some of them are quite dangerous.

### Mob Sprite Previews and Behavior ###
image
image
image

https://user-images.githubusercontent.com/81007356/209048153-ea6953c4-3421-44aa-802f-5f053f0e108c.mp4

https://user-images.githubusercontent.com/81007356/209048203-85849905-6f08-4a31-b934-b39a636b027e.mp4

https://user-images.githubusercontent.com/81007356/209048246-3a56f834-e9b3-432f-94d2-572b2079c37f.mp4

[away]  [help] [wip]

:cl:
 * rscadd: Adds the Valkor XV away mission, complete with new mobs and a new environment

### CODE REVIEW

**Comment by Optimism333** [comment]
Old as hell branch, so conflict resolution will be fun.

**Comment by wotisjanitor** [comment]
Super cool. Is this more combat oriented or exploration, or even more puzzles?

**Comment by Optimism333** [comment]
> Super cool. Is this more combat oriented or exploration, or even more puzzles?

There's a fair bit of combat, but I'm trying to make this more exploration oriented. The main fun is supposed to come from experiencing a completely new environment, spritewise and with new soundworks and mobs.

It's been a bit of a challenge trying to make plants, animals, and a unique look to the terrain that all meshes together. But hopefully most players will agree this is a unique and neat addition to the vg environments.

Haven't even showed off the ayy base sprites yet, got some new stuff there too.

**Comment by pedr69** [comment]
>vaults/gateways that arent just a trillion simplemobs with tator weapons, and the reward for clearing being more guns

yes

**Comment by wotisjanitor** [comment]
Some xenobio content would be cool

**Comment by wotisjanitor** [comment]
> Some xenobio content would be cool

Like being able to collect samples or something, and maybe get something from it like a new slime extract

**Comment by Optimism333** [comment]
Took a pause on this because the spriter I was relying on for most of the assets dropped out of contact for a while. Will try to get some more progress done soon.

**Comment by Optimism333** [comment]
Much as I hate to do this, I just don't have the free time or interest to work on this project anymore.

If anyone else has interest, I'd be happy to pass along the sprite assets. Quite a few are good ones, and I'll hold on to them for a while in case anyone wants them.

**Comment by Eneocho** [comment]
what a shame, i'll keep an eye on this, just in case

**Comment by SacredAtom** [comment]
> Much as I hate to do this, I just don't have the free time or interest to work on this project anymore.
> 
> If anyone else has interest, I'd be happy to pass along the sprite assets. Quite a few are good ones, and I'll hold on to them for a while in case anyone wants them.

Can you merge just the mobs that are finished themselves for future buses?

**Comment by Optimism333** [comment]
> > Much as I hate to do this, I just don't have the free time or interest to work on this project anymore.
> > If anyone else has interest, I'd be happy to pass along the sprite assets. Quite a few are good ones, and I'll hold on to them for a while in case anyone wants them.
> 
> Can you merge just the mobs that are finished themselves for future buses?

Sorry, but no. I'm quite done with ss13 coding for the time being.

But if anyone wants to salvage the mob code here, it worked pretty well last I tested it. It just needs to go through review and get some fixes/polish. And like I said, I'll happily pass along the remaining sprite assets.

One guy in the coder Discord already expressed some interest, and I'm happy to share the sprites with anyone else who wants them.

**Pull request closed without merging**
