### PR TITLE
Vault Lockers

### PR DESCRIPTION
**Pull request by Shadowmech88**
Adds a new type of locker, the vault locker. Vault lockers are immovable, have 100 times the health of a standard secure closet, and are explosion-proof and EMP-proof.
Adds a single vault locker to the armory of every station except Defficiency.
Boxstation gets two vault lockers to replace the two secure closets it has now.

Secure closets are fine for the most part, but having a regular secure closet inside the armory is a bit silly because the room is full of things you can use to break the closet open. An item is no safer inside that secure closet than it would be on the armory's floor. Hence the vault locker.

vault_locker

### CODE REVIEW

**Comment by Konater** [comment]
> deff

nooooo

**Comment by Shadowmech88** [comment]
Why not Deff specifically?

**Comment by Konater** [comment]
I remapped deff security and I'm waiting for probe's pr to go through before I copy and paste it all over

**Comment by Shadowmech88** [comment]
Oh shit, sorry. I'll postpone the change to Deff until yours goes through.

**Comment by Shadowmech88** [comment]
Alright, the changes to Defficiency are removed.

**Comment by Konater** [comment]
Thanks

**Comment by Kurfursten** [comment]
100 times the health and explosion-proof seems a bit much. The armories don't even have bombs.

Or is an attempt to stealth-buff the brig for meteor game mode?

**Comment by Shadowmech88** [comment]
These are the same stats they had in #9179, way before the fridge nerf. I just tore them out so I could PR them separately for the sake of atomicity.

**Comment by ComicIronic** [comment]
@clusterfack

**Comment by Blithering** [comment]
The crates on bus station could be replaced with these (or some other kind of locker). As it stands  they cannot be relocked.

**Pull request merged**
