### PR TITLE
Fixes re-admining not restoring the AntagHUD verb

### LINKED ISSUE #25123: Re-admining doesn't restore the AntagHUD verb
#### Steps to reproduce
- Be ghost
- Deadmin self
- Readmin self
- Look in the ghost tab and be disappointed antagHUD is not there

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #25123

### CODE REVIEW

**Comment by SonixApache** [comment]
Normally you would put a description of what the PR does in the title,
and add a :cl: since this is something that (some) users might want to know about.
Not too sure if it's necessary in this case.

**Comment by DeityLink** [comment]
Unless it affects players extensively I generally don't add a changelog for admin-related bugfixes.

**Comment by DamianX** [comment]
I think `add_admin_verbs` and `remove_admin_verbs` should take care of this

**Comment by Kurfursten** [comment]
Damian is right, if this is the only verb not being re-added it needs to be fixed at the source for maintainability

**Comment by DeityLink** [comment]
Fixed and tested.

**Pull request merged**
