### PR TITLE
Some subsystem init speedups

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[performance]

## What this does
rewrites the lighting subsystem to search by area first, skip ones without dynamic lighting, and then search the turfs in the area to apply it to, cutting down the time by half (0.5 seconds) while applying the same logic
moves mining suprises into the skip vaults thing if set in the config
addresses #36631 by cutting down object init by 1.2 seconds from that and 1.7 in total
2.2 seconds shaved overall

## How it was tested
booting up tgstation.dmm

## Changelog
:cl:
 * tweak: Lighting and object subsystems are now notably faster, with about 2.2 seconds shaved off server initialization overall on boxstation as an example

### CODE REVIEW

**Comment by Eneocho** [comment]
kanef roams free with init speedup PRs while my homie adam is still held prisoner by the powers that be... we truly do live in a society...
we live in a soycity

**Comment by boy2mantwicethefam** [comment]
If the skip vaults config is the one that disables vaults from spawning then it might not have a real impact on live improvements.

**Comment by SECBATON-GRIFFON** [comment]
> If the skip vaults config is the one that disables vaults from spawning then it might not have a real impact on live improvements.

that's why i didn't factor it into the time i posted

**Comment by SonixApache** [comment]
prepare for unforeseen consequences

**Review by west3436 — APPROVED** [review]
This is pretty unatomic and we've been burned badly by "speed up init" PRs in the past but we'll give it a shot. In the future please keep these more atomic so we can more easily isolate bugs to a single PR.

**Pull request merged**
