### PR TITLE
Made EMPs instant(?)

### PR DESCRIPTION
**Pull request by DamianX**
I don't know if this is a good thing or a bad thing but there you go.

https://webmshare.com/play/WPX0M

### CODE REVIEW

**Comment by ShiftyRail** [comment]
There's a noticeable delay in the beginning ; is it a video artefact or did it freeze you ingame too ?

**Comment by DamianX** [comment]
There was a small delay but no "freeze"

**Comment by Dacendeth** [comment]
does this fix that ultra lag that happens when a large amount of shards explode at once?

**Comment by DamianX** [comment]
most likely not

**Comment by Hoshi-chan** [comment]
But seeing the EMP wave slowly approaching you and knowing that your organs are about to explode is fun.

**Pull request merged**
