### PR TITLE
Remove maptools since apparently they should not be used anymore

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by Irradiation** [comment]
Prepare for unforeseen consequences.

**Comment by Kharkov72** [comment]
long live strongdmm

**Comment by toomykins** [comment]
so it corrupts maps? it also corrupted my willingness to ever touch dmm's again

**Comment by SonixApache** [comment]
can it just check for tgm and not fuck with those

**Comment by Exxion** [comment]
It only operates on the main maps and all of those are TGM
Except the map merge driver but I don't even know if anyone has it set up, since you have to do that locally

**Pull request merged**
