### PR TITLE
Made a drug dealer kit

### PR DESCRIPTION
**Pull request by yackemflam**
not all bundle's should be about killing, but that doesn't mean you can't defend yourself

:cl:
rscadd: Added a drug dealer bundle to the uplink kits, sell some drugs kid

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Neat

**Comment by SonixApache** [comment]
last stand pills contain expensive stuff
meh

**Comment by yackemflam** [comment]
it also kills you

**Comment by drawsstuff** [comment]
You can do better by just stealing a chemistry machine.

**Comment by yackemflam** [comment]
you can do a better than most bundles

**Comment by SonixApache** [comment]
it doesn't kill you if you stick it in a beaker and take out the parts that kill you
Which was my point

**Comment by boy2mantwicethefam** [comment]
Pretty sure nukies can already do that

**Comment by ghost** [comment]
please DOCUMENT YOUR FUCKING CHANGES IN THE PR DESCRIPTION

also this bundle has way too much shit, bundles are supposed to have a directed purpose because you buy them when you don't have any ideas for antagonizing

**Comment by Kammerjunk** [comment]
this bundle it's just the BEST bundle it can fit EVERYTHING
it's for drug dealers
it's for viscerators
it's for murderboners
it's for stealth

bundles shouldn't be like that

**Comment by PrimeDSS13** [comment]
viscerator knife seems kind of thrown in
doesn't really fit the theme

**Comment by yackemflam** [comment]
I can change it into a normal butterfly knife

**Comment by ShiftyRail** [comment]
There's absolutely no need for a butterfly knive either
just make it about drug dealing not drugdealing with stealth-murder caracteristics

**Comment by SonixApache** [comment]
do you nerds know nothing about drug dealing
you use the knife to cut the coke

**Comment by jknpj** [comment]
Thanks for your drugdealing lessons, sonix.

**Pull request closed without merging**
