### PR TITLE
Hand tele's "None (Dangerous)" setting will automatically scramble its destination with every activation

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Selecting the "None (Dangerous)" setting will now create a portal in a random location rather than set a fixed random location, meaning that each portal will be in a different destination, still has a 5% chance of throwing you into zlevel 3 but only when initially setting it for "None (Dangerous)" because then the hand tele wouldn't really be used by anyone except antags if it could literally space you and everyone nearby on a 1/20 chance

:cl:
 * rscadd: The hand tele will now automatically scramble its destination when its destination is "None (Dangerous)".

### CODE REVIEW

**Comment by wotisjanitor** [comment]
@Rubylips thoughts

**Comment by Eneocho** [comment]
Requesting to keep the two portals on the same tile, cause it helps with certain structure stacking techniques, and it would be funny to me if it had a "the teleportation is so seamless you feel you haven't moved at all!" message like the Teleporter machine has.

**Comment by boy2mantwicethefam** [comment]
What is the structure stacking technique?

**Comment by Eneocho** [comment]
I've used same tile portals to stack shardboxes on the same tile when messing with ultratiny setups (6 tiles total or smaller). It can be done with regular portals in two different locations, so it's not a huge loss, though it can be a pain. 
I mainly just want the funny "seamless teleportation" text.

**Comment by GreatBigFailure** [comment]
> @Rubylips thoughts

I had a bit of a giggle that I was summoned for this.
So the destination scramble thing is a good change if I understand right. Basically just makes the danger setting more of a wild card, which is the whole purpose of using it. 
I'd skip the part about preventing portals from being on the same tile though. You can do some neat stuff by stacking them so you can leapfrog.

An example would be easiest:
Shuttle is about to leave
Oh no the mime is locked in surgery and I don't have tools
Portal shuttle -> robotics or whatever, grab tools
Portal robotics -> medical, free mime
Then you go back through the portals to the shuttle, even though there was no beacon on the shuttle.

**Comment by DorainGrey** [comment]
Yeah there's a lot of handy things you can do with two portals.

Aside from that, it's really important functionality in general to prevent two users using same beacon from getting each others way. Or when you are getting chased and have to open multiple portals, I can't imagine waiting for default portal close time.
I don't see any benefit to changing this, what's the reasoning?

**Comment by djkramer123** [comment]
First part is good, similarly to what others said I don't like the second part

**Comment by boy2mantwicethefam** [comment]
Removed the "no stacking portals" part.

**Comment by Eneocho** [comment]
I will now 👍🏻 your PR

**Pull request merged**
