### PR TITLE
Incentives of Command

### PR DESCRIPTION
**Pull request by Kurfursten**
What makes a man turn captain? Lust for gold? Power? Or is he just born with a heart full of captaincy?

I didn't even test this yet because #24563 will cause conflicts when it merges first

Captain gets any of these that aren't inside the captain's office area: captain spacesuit, antique laser, hand tele, pinpointer. He also gets backed up in genetics.
HoP gets a box of 7 random Ian-compatible hats and a laz injector

🆑 
* rscadd: High priority captains/HoPs are now incentivized with special rewards.

### CODE REVIEW

**Comment by DrSnips** [comment]
Interesting PR. A bit early to say much though.

**Comment by FudgePucker** [comment]
Captain also needs the helmet to his suit as well. He has a spare suit in his locker, but only one helmet.

I also can not :+1: this hard enough. Your office looks like a shoe store after a hurricane when you late join.

Also maybe set HoP and Captain to high priority if there are neither, they are the only two who can do it outside of admins, and we both know that the assistant that ran off with the spare will NEVER do it.

**Review by DamianX — COMMENTED** [review]
You need to remove all these items from `critical_captaincy_equipment` on `Destroy` or they'll never GC

**Comment by SonixApache** [comment]
doubling the amount of stupid powergay stuff on the station seems pretty lame to me

i hate to give you more WYCI material, but a pda cartridge or advanced pinpointer that helps him locate them for a limited time would be a nicer, less powergay addition
just straight up giving him a pinpointer would be alright, though if people start to meta during nuke ops / malf that'd be pretty gay (and there'd be no real way to prove it)

box of hats is 👌👌👌
alternatively just give the cap a green captain hat, hats are good

**Comment by ShiftyRail** [comment]
I think this is going to encourage latejoin as captain more than reading up as the job.

**Comment by Kurfursten** [comment]
It is only for high prio

**Comment by FudgePucker** [comment]
Not really, the only job that would be able to abuse this to gain meta advantage would be HoP, and if an admin notices that the HoP lots the captains office then sets captain to high priority you could tell them to knock it off.

This also wouldn't encourage late joining over readying because it only gives you the stuff if your office has been looted. So unless you enjoy spending all fucking round hunting for all twenty all access IDs, readying up at the start is the best option. It would make late joining less of a nightmare.

**Comment by Kurfursten** [comment]
I forgot to mention, adding the captain's helmet isn't necessary since it'll be converted to a rigsuit in that other PR, so it will be foldout like other helmets.

**Comment by FudgePucker** [comment]
Oh cool

**Comment by Kurfursten** [comment]
It looks like there's currently strong opposition to the idea that people should receive a reasonable reward for pitching in where they're asked. Maybe someone will pick up the idea of improving this system in a year or two.

**Pull request closed without merging**
