### PR TITLE
Replaces the placeholder gigadrill icon with this russian gigadrill icon

### PR DESCRIPTION
**Pull request by jknpj**
drill

Same as the last time, minus TTGL references.

:cl: 
 * tweak: The artifact gigadrill got a new icon thanks to the russian community

### CODE REVIEW

**Comment by N3X15** [comment]
Did we get permission?

**Comment by N3X15** [comment]
Nvm, see that they posted it themselves in #sprites-and-sounds on Discord.

**Comment by Exxion** [comment]
That clashing perspective makes me want to shoot myself

**Comment by Riekland** [comment]
this looks like actual trash who thought it was a good idea to merge it

**Comment by ghost** [comment]
good thing it's never used when it's actually found

**Comment by SonixApache** [comment]
better than the old one

**Comment by Exxion** [comment]
Quick, I need someone who can draw to draw this from a different angle, with the guy leaning at like a 45 degree angle to the left

**Pull request merged**
