### PR TITLE
Civil War of Casters (New Roundstart Ruleset)

### LINKED ISSUE #21897: Latejoin Ragin Still Costs 50
I'll fix this in the upcoming Wiz Wars PR

### LINKED ISSUE #21922: Wizard Can Still Spawn Without Equip
This is the same bug from 4 and 3 weeks ago respectively.

This time it happened to an observer on MR ruleset with seemingly no runtimes. LJ ragin had already fired therefore Wiz Federation faction already existed. We thought this was fixed 2 weeks ago.

### PR DESCRIPTION
**Pull request by Kurfursten**
In Civil War of Casters 4 wizards (number negotiable, also potentially calculated based on player count or enemies) are sent to attack the station, one every 7 minutes. Every wizard sent is put on an alternating faction, starting with the WPF.
* **The Wizardly Peoples' Front**: "The WPF are a faction within the Wizard Federation. The only people they hate more than Nanotrasen are the Peoples' Front for Wizards."
* **The Peoples' Front for Wizards**: "The PFW are a faction within the Wizard Federation. The only people they hate more than Nanotrasen are the Wizardly Peoples' Front."

In addition to their normal objectives, they get the new faction-level Destroy Faction objective, which they succeed at if their enemy faction has no living members. This makes this the first ruleset to offer players both faction and role level objectives.

fixes #21897
fixes #21922
BANDAID fix for #21948 (These people will be disregarded from apps)

🆑 
* rscadd: A new mode, Civil War of Casters. Whoever wins, we lose!
* tweak: Midround Ragin' Mages will no longer be discounted if Wizard fired at roundstart.
* bugfix: Latejoin Ragin' Mages properly reduced down to match Midround levels.
* bugfix: Midround Ragin' Mages will not leave you unequipped and unnamed in the arrivals shuttle if there was an earlier wizard.
* bugfix: Midround From Ghost rules will no longer fail because of picking someone who is dead but not ghosted.

### CODE REVIEW

**Comment by Blithering** [comment]
Wizwars
Scufflin' Sorcerers
Mage Mobs
Gangdulf the Grey

**Comment by Exxion** [comment]
Honestly you can use Wizard Wars if you just change the name of the current Wizard Wars
This will be much more common and thus its name is more important

**Comment by Kitfox88** [comment]
yer a blood now, 'arry

**Comment by Arthurdentist** [comment]
Love the concept but really don't like the theme / references. I think it would be better as 'Wizard Wars', perhaps having it so that the first wizard on each team gets to pick the name of their faction similar to vampires if that is possible.

If that isn't possible, I think it'd be better to just have one faction as 'The Wizard Federation' and the other as something like 'The Magician's Guild', or something similar. Two rival wizard factions instead of sub-factions of the Federation, a bit like Nanotrasen and the Syndicate.

**Comment by DeityLink** [comment]
I liked wizards attacking each others during old Ragin'

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
Change the names.

**Review by MadmanMartian — APPROVED** [review]

**Pull request merged**
