### PR TITLE
In-Hand-Radio Fix.

### PR DESCRIPTION
**Pull request by ghost**
Restores a lost feature that allowed you to speak into radios in your hand without having the microphone on.
This would make using station-bounced radios a bit more straightforward and less annoying since you don't have to keep the microphone on to talk.
Doing so usually transmitted idle background chatter and clogged up the radio channel in the process.
The response team channel and the right hand "channel" occupied the same key, 'r', so I've moved the ERT channel key to '-' to fit right next to the death squad key, which is '0'.

:cl:
 * bugfix: Restores lost feature that allowed you to talk into held radios without having the microphone on, use .l and .r to talk into the radio in the respective hand
 * tweak: The ERT radio channel is now accessed with the '.-' key

### CODE REVIEW

**Comment by SkowronX** [comment]
After all these years

**Comment by Pathid** [comment]
Unfortunately 1 is already assigned to galactic common for if you have your default language set to something else.

**Comment by ghost** [comment]
@Pathid Damn, didn't notice. What key should it be instead? '.9'?
Edit: Noticed that 9 is used by the mouse language.
Seems like a lot of the say keys are assigned inconsistently, not sure what I should change the ERT key to.

**Comment by Riekland** [comment]
wait what this was removed

is that why no-one came to save me when I screamed

**Review by Probe1 — DISMISSED** [review]
What panthid said.  1 is already used.

**Comment by ghost** [comment]
I have just checked the language.dm and say.dm file more thoroughly and found a possible candidate for the new ERT key, a dash '-'.
I chose this key for the following reasons:
 * It is free
 * It is right next to 0, the Death Squad key, on a standard English keyboard, making it fairly appropriate
 * I checked several keyboard layouts including AZERTY, the German QWERTZ, several russian layouts and more on wikipedia (https://en.wikipedia.org/wiki/Keyboard_layout), and most of them feature the dash as a basic key without needing shift or alt modifiers, making it easy to access

Unless someone is offering a better candidate, I'll push a commit with '-' as the new ERT key.

**Pull request merged**
