### PR TITLE
XGM

### PR DESCRIPTION
**Pull request by Exxion**
rand(15, 70)% tested

I realized fixing ZAS shit would be easier if I did this first, so I wouldn't have to fix it twice
Completely coincidental this was finished mere hours after role datums. Guess it's just major system overhaul day.

There are no intentional gameplay changes except for three minor bugfixes, having to do with oxygen requirements for cigarettes and campfires, and volatile fuel burning (which I don't think even appears in-game). This is otherwise purely a system change, assuming I didn't fuck up.

Not done testing, but I took sleeping pills a while ago and will *not* be awake in 30 minutes

:cl:
 * experiment: Did some internal changes to gases. Please report anything unusual because this is supposed to have no effect on gameplay.

### CODE REVIEW

**Comment by Exxion** [comment]
:thinking:
It compiled and ran just fine locally

**Comment by Exxion** [comment]
Oh that's right
BYOND bug that was fixed in a newer version than the server is running

**Comment by Exxion** [comment]
Downgrading status from "Needs more testing" to "Could use more testing but is probably fine"

**Comment by ShiftyRail** [comment]
@Exxion Did you try to fill an oxygen tank this time

**Comment by Exxion** [comment]
I didn't even touch the relevant code, but incidentally, yes

**Pull request merged**
