### PR TITLE
Gives lawyers round start bridge access

### PR DESCRIPTION
**Pull request by Konater**
Now they can be useless and call the shuttle/make bridge announcements/eat donuts at the same time

### CODE REVIEW

**Comment by Probe1** [comment]
ok fine.  IAA is pretty shitty and needs something.

**Comment by Senaat1** [comment]
:ok_hand: :+1: :100: :eggplant: :smoking: :sunglasses:

**Comment by 9600bauds** [comment]
Sure, what's the worst that can happen

**Comment by 9600bauds** [comment]
If they eat all the donuts I'm throwing them out though

**Comment by Senaat1** [comment]
give lawyers more brig access so they have access to all the donuts on the station

**Comment by ComicIronic** [comment]
OBJECTION pride station wide

**Comment by Senaat1** [comment]
this is the single most important game-changing pr in the hsitory of vg and i deMAND THIS GET MERGED!! :gun: :angry:

**Comment by CptWad** [comment]
this is fine

**Comment by gbasood** [comment]
> call the shuttle

fax, yo

> make bridge announcements

literally a lawyer, why

> eat donuts

disgusting

**Comment by Probe1** [comment]
I don't know its basically throwing shit at the wall and seeing what sticks.  

You know, lawyer and IAA are really two different kinda jobs here.  A stations internal affairs agent might reasonably have this kind of access but a stations lawyer?

**Comment by Shadowmech88** [comment]
Is it possible to assign access based on job title rather than job slot?

It doesn't really make sense for a lawyer to be able to call the shuttle.

**Comment by ComicIronic** [comment]
Jobs with different titles and different access are different jobs.

**Comment by Shadowmech88** [comment]
Can two different jobs have the same office?

**Comment by Konater** [comment]
I had internal affair agents in mind, they're supposed to be loyalty implanted agents of nanotrasen and it makes sense they would have the responsibility

**Comment by clusterfack** [comment]
IAAs are supposed to be the captain's spies that only report to him.

**Comment by Shadowmech88** [comment]
> IAAs are supposed to be the captain's spies that only report to him

Source?
If they're modeled after actual agents of Internal Affairs Bureaus, I'd think they would report to whatever entity oversaw the station as a whole, i.e. Nanotrasen.

**Comment by DeityLink** [comment]
Hope they can access the meeting room as well. Is it included with the Bridge access?

**Comment by Konater** [comment]
Yes, where they may find more donuts

**Comment by clusterfack** [comment]
I read it somewhere a long time ago and thought it sounded really neat. It's better than them working for 'Nanotrasen' because that makes them no better than a chaplain.

**Pull request merged**
