### PR TITLE
Shift/Alt/Ctrl clicking the turf below an airlock Shift/Alt/Ctrl clicks the airlock. AI camera will not jump on double shift/alt/ctrl click (only regular double click)

### PR DESCRIPTION
**Pull request by gurfan**
FUCK pixelhunting and FUCK jumpy cameras.

[qol]
[tweak]

### CODE REVIEW

**Comment by d3athrow** [comment]
time to have my borg stack airlocks on one tile then shock lock and bolt them all in just 3 clicks.

**Comment by gurfan** [comment]
I thought airlocks couldn't be stacked, uhh

**Comment by gurfan** [comment]
they cannot be stacked, but I added a break just in case

**Comment by Kurfursten** [comment]
You have my vote if shift clicking the tile sends a ctrl click to the door, ctrl sends alt, and alt sends shift.

The AI should suffer.

**Comment by gurfan** [comment]
I should mention this only affects the AI because it uses a special type of click, Im not sure how to implement turf-clicking for borgs besides having it check if the clicker is a borg every time somebody clicks a turf, which I think would be a really inefficient way of doing it

**Comment by DamianX** [comment]
never merge this

**Comment by SonixApache** [comment]
alert collabs
tell damian to suck a circuit board

**Comment by Kurfursten** [comment]
Conflicts

**Comment by gurfan** [comment]
conflicts fixed

**Pull request merged**
