### PR TITLE
Lo and behold, more mapping

### LINKED ISSUE #4881: Old firelock sprites on box that weren't changed
ss 2015-06-07 at 01 59 50
ss 2015-06-07 at 02 06 43
ss 2015-06-07 at 04 20 40

@ComicIronic

### LINKED ISSUE #5211: (WEB REPORT BY: Anonymous REMOTE: ) Stools in Boxstation locker room/ Weapon stools are broken?
Rather than being the usual structure/stools like in the bar, they are the weapon/stools, which means you can't sit on them nor deconstruct them.

Part 2 is that Weapon stools appear to be a bit bugged, when setting them back down by clicking on them in-hand, they disappear entirely rather than be set back down, not sure if this is an oversight or a genuine bug.

>How to reproduce

Go to Boxstation locker room, and try to sit on a stool.

Pick up said stool, and try to put it back down.

### PR DESCRIPTION
**Pull request by ghost**
The ride never ends

Main and only non-bugfix change :
- After many requests, the stun baton in the Research Outpost has been removed in favor of a multitool. They both test the same effect for artifacts, but one of the two is obviously never used for artifact testing and is instead looted every single fucking round due to being extremely powerful as a personal defense or robusting weapon. The other is useful for door hacking, I suppose

Bugfixes :
- Stools in Boxstation's Locker Room are now structure stools instead of weapon stools. There's no reason to have them start as weapon items (which are normally only created from picking up stools) and this breaks stuff. Fixes #5211
- Using CTRL+F, patience and a bit of common sense, eradicate all full-tile firelocks and default state border firelocks ("Emergency Shutter" instead of "Firelock South") from the map. Fixes #4881 hopefully forever
- Gave the Trade Outpost's hallways glass airlocks an actual name, instead of "Glass Airlock". Purpose for the outpost outside of looting still not here
- Mining Station Storage now has a glass airlock, like all other airlocks on the station. No reason to hide what is behind that door

No screenshots needed because all changes are extremely explicit

### CODE REVIEW

**Comment by clusterfack** [comment]
What if someone wants to hide bodies in the storage area?

**Comment by dylanstrategie** [comment]
There are lockers in here, put the bodies in the locker, or shove them out of the way of the door (besides, there's a window bay in the storage area)

**Comment by clusterfack** [comment]
I think having a room that isn't instantly visible actually does serve a valuable purpose for antagging - body hiding, changeling absorbing, vampire consuming, etc.

**Comment by ComicIronic** [comment]
Most departments have hidden backrooms for a reason.

**Comment by dylanstrategie** [comment]
There are hidden backrooms on Mining. Few people enter the Telecommunications chamber unless the comms are out, the Maintenance Room is here and can easily host a locker which won't look suspicious, the toilet can hold a body, and you have the entire asteroid for body hiding if you have E.V.A gear

**Comment by FudgePucker** [comment]
No really why are you worried about mining base not having another hidden room when its off station, has dorm rooms and other rooms, AND HAS AN EVA AND THE BEST PLACE TO HIDE BODYS.
Window airlocks would also let you see if the room is vented into space from a busted window without having to open it first

**Comment by ComicIronic** [comment]
A closed firelock which appears above the door should tell you if the room is vented to space.

**Comment by FudgePucker** [comment]
Are there firelocks in mining base?

**Comment by dylanstrategie** [comment]
There might be, but I didn't check in-depth. The research station certainly does

**Comment by d3athrow** [comment]
>After many requests

Where are these requests? I've literally had nobody complain about the baton except you

**Comment by PJB3005** [comment]
I approve of the multitool though

**Comment by dylanstrategie** [comment]
I've seen many people in deadchat react in complete disbelief when a Scientist antag broke their face with a stun baton five minutes in

**Comment by FudgePucker** [comment]
I approve of removing the stun prod. Science already has, toxins, xenobio, xenoarch, and research for antaging, they don't fucking need a stunrod round start.

They can already make a rapid syringe gun five mins in.

**Comment by SarahJohnson489** [comment]
Trade outpost needs some fixing up and a non-antag shuttle bay and we'd be able to have vox traders

And leave our artifact monkey prod alone. They can get super cell stun gloves in their pocket and bag a circular saw. It's just blowing smoke over mad nerds that got dunked for being sloppy

**Comment by ComicIronic** [comment]
>It's just blowing smoke over mad nerds that got dunked for being sloppy

I don't see how it's sloppy to not automatically prepare a self-defense weapon and then get hit by an instant stun on the most isolated part of the station.

**Comment by SarahJohnson489** [comment]
Gotta listen to your feels and split when you get the heebie jeebies or see the shuffle.

**Pull request merged**
