### PR TITLE
This PR just fixes a bug that allows mushroom men to smoke

### PR DESCRIPTION
**Pull request by toomykins**
indeed

### CODE REVIEW

**Comment by Eneocho** [comment]
Make it so they can hold the cigarette, but it doesn't do anything other than just be there burning slowly. 
Sometimes a shroomman just wants to feel cool.
Or make it so shroommen can smoke if the cigarette is placed on the shoe slot, cause they already "eat" with their feet, why not smoke as well?

**Comment by Eneocho** [comment]
Just saw the other PR, lel.

**Comment by SonixApache** [comment]
they have no breathing hole, this makes sense

**Comment by wotisjanitor** [comment]
> they have no breathing hole, this makes sense

Same for greys.

**Comment by falcon2346** [comment]
Let the mushmen have their smoke break, it's funny.

**Comment by ghost** [comment]
Downvoting because the PR to enable smoking is not winning. I'd rather be able to smoke as a mushroom via a bug than not be able to smoke at all.

If smoking is removed I'm going to join as Smokey the mushroom and set myself on fire in game.
image

**Comment by Kurfursten** [comment]
This PR has better popular support. It's also consistent with inability to play lip-based instruments.

**Comment by Eneocho** [comment]
heretic, come on man
a shroom can't blow a trumpet since he doesn't have lungs but he definitely can hold a cigarette on a face fold

**Pull request merged**
