### PR TITLE
Delete tgstation.dmm

### PR DESCRIPTION
**Pull request by bthomas2**
:cl:
 * rscadd: Did stuff!
 * rscdel: did other stuff!

### CODE REVIEW

**Comment by Kharkov72** [comment]
bring it back coward

**Comment by BomberBro** [comment]
probably the most powerful PR we've ever had

**Comment by ghost** [comment]
brave and b*sed

**Comment by bthomas2** [comment]
> 
> 
> bring it back coward

ok

**Comment by SkowronX** [comment]
seething?

**Comment by press-mark** [comment]
powerful

**Comment by jknpj** [comment]
wait for it

**Comment by ghost** [comment]
remove all non-deff maps and you can have my upboat

**Comment by Zth--** [comment]
guys I didn't have a backup

**Comment by RealestEstate** [comment]
it's >TG so obviously it's bad

**Comment by DamianX** [comment]
Finally free from the TG shackles

**Comment by N3X15** [comment]
adams family clapping

**Comment by SonixApache** [comment]
"no"

**Comment by brndd** [comment]
real talk though why don't we rename tgstation.dmm to boxstation.dmm

**Comment by Exxion** [comment]
Lots of config files and shit

**Comment by Probe1** [comment]
real question why do we still have vgstation.dmm

**Comment by N3X15** [comment]
Probably in the unrealistic hope someone will eventually maybe fix it

**Comment by brndd** [comment]
```
$ cat maps/vgstation.dmm
"a" = (/turf/space,/area)

(1,1,1) = {"
aaaaaaaaaa
aaaaaaaaaa
aaaaaaaaaa
aaaaaaaaaa
aaaaaaaaaa
aaaaaaaaaa
aaaaaaaaaa
aaaaaaaaaa
aaaaaaaaaa
aaaaaaaaaa
"}
```

🤔

**Pull request closed without merging**
