### PR TITLE
Adds some more clothing to the wonderful wardrobe

### PR DESCRIPTION
**Pull request by beesil**
Very lazily adds some new clothing options to the wonderful wardrobe, listed below:
- Vampire coat
- Richard outfit and mask
- Sneaking suit and headband (otherwise unobtainable!)
- Galo Sengan outfit
- Raincoat
- Departmental armband set
- HoP and HoS plasmaman suits (same armor values as plasmaman captain suit)
- Grey spacesuit
- Biker outfit
- Monkey softsuit and a helmet
- Headset earmuffs
- Vault 13 jumpsuit
- Xeno leather suit & helmet (similar armor values to gem-studded hardsuit)
- Rabbit foot charm

Additionally bundles the plasmaman suits into one 'item' and replaces one of the ancient spacesuits with a helmet. My reasoning for this change is that you get the same few sets of items every time and that it would be cool to see some otherwise hard to obtain clothing in-game. Open to suggestions for more items to add.

:cl:
 * rscadd: Adds more variety to the wonderful wardrobe.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
~~The raincoat is a traitor item, though. Pretty sure biker helmet is part of a bundle too.~~

Nevermind, it's the RNG wardrobe, it's fine

**Comment by Dacendeth** [comment]
How about adding the plasmaman head of personel and head of security suit/helmet to it?

**Comment by beesil** [comment]
@ShiftyRail 
The biker outfit is part of a traitor bundle which is why I'm hesitant to include it, the raincoat can be made with plastic though.

@Dacendeth 
Sure.

**Comment by Kurfursten** [comment]
Please remove plasmaman suits instead of adding them, they're awful, no one ever buys them except maybe one plasmeme buys a cult suit. It sucks when 4 of your rolls are wasted on plasmaman stuff.

Alternately, put ALL the plasmaman gear into a smartclothing box as a single item

**Comment by drawsstuff** [comment]
A few suggestions to improve variety in randomization

-Xenomorph Leather Armors. Might be a bit much but I've never seen anyone make them before.
-Grey Pressure Suits
-Unathi Breacher suits for when magic dice, harmbay, or staff of change devastates the station
-Bubblehelms
-dispatch uniform
-mario and luigi outfits
-Waldo
-The Alt Security rigsuit we have in the sprites called rig1-secTG that everyone seems to forget exist (and rig0-secold)
-Hos and warden berets also exist in the dmis for some reason? and security has jumpsuits that arent in the formal wear crates (the navy ones? i might be wrong) they also have the "corporate" set of jumpsuits that just... exists, even comes with its own hat
-all the old bay donator leftover items like e_beret_badge, alice_mccrea_1, enos_adlai_1, norah_brigs_1, ect
-some of the special sunglasses like star and purple
-the vault 13 suit

There's so much more but some of this is just hard to shove in, like the fact we have sprites and accessories for knee, shoulder, and neck guards.

Pick what you want from this list really, I didn't make too much of an effort to balance it

**Comment by beesil** [comment]
@Kurfursten 
I've had people buy the suits fairly often, would bundling them into one roll like the winter coats be an acceptable alternative?

@drawsstuff 
great suggestions, I'll look at how much of these are actually coded in a few minutes

**Comment by Blithering** [comment]
Please add ancient space helmets, the suit is part of the current list, but no helmet to go with it. 
Also there's the stormtrooper modkits, which might be fun for sec.
The knee shoulder and neck guards drawsstuff suggested would be a better fit for the alcatraz crate I reckon.

**Comment by Kurfursten** [comment]
Yeah that's functionally the same as the smartbox
@Blithering I have to believe that's a typo because it spawns 2 suits but no helmet, I think whoever added it just messed up

Other suggestions:
Headset earmuffs, monkey spacesuit, rabbit's foot, dracula coat, pharaoh mask

**Comment by Eneocho** [comment]
Instead of adding plasman suits that almost never get sold (except in the rare case the local plasmeme feels like coughing money for something he already has to a degree).
Try instead making it a separate wardrobe. Say a plasma wardrobe, with all kinds of plasma related stuffs.

**Comment by beesil** [comment]
bundled the plasmaman suits into one item, swapped one of the ancient suits for a helmet, added:

- grey spacesuit (obtainable from cargo and not many grey players currently, but good flavor)
- biker outfit
- monkey softsuit and a helmet to go with it
- headset earmuff
- vault 13 jumpsuit
- xeno leather suit & helmet (similar armor values to gem-studded hardsuit, too good?)
- rabbit foot

unfortunately a lot of the things Draws mentioned aren't coded (the lizard suit + bubble helm are racelocked and I don't imagine them selling well outside of very specific circumstances). I think that the stormtrooper modkits would be better suited for one of the security crates, or their own item.

**Comment by Eneocho** [comment]
> 
> 
> bundled the plasmaman suits into one item, swapped one of the ancient suits for a helmet
> 

Impossibly based. I think the Xeno Leather thing is actually ok in balance. I would offset it slightly in that you have no dexterity (something something, xeno claws).

**Comment by Eneocho** [comment]
I would love to see clothing that has some special effect while worn, like the xeno amulet letting you understand xenospeak or the monki suit letting you speak monkey.

**Comment by ShiftyRail** [comment]
Is it a done deal or do you wish to add more to this ?

**Comment by beesil** [comment]
unless there are more suggestions it's set

**Pull request merged**
