### PR TITLE
PDA money transfer tweaks

### LINKED ISSUE #15110: You can send money through PDA even in z-levels with no signal to messaging server/radio/nothin'
so people can dial 911 while lost in space WEEWOOWEEWOO

### PR DESCRIPTION
**Pull request by MadmanMartian**
Sending money via PDA now depends on there being
- Active comms link between the two z levels
- Active messaging server

closes #15110

### CODE REVIEW

**Comment by Diavill** [comment]
no
NO
how will i send one credit to nerds as a signal to pick me up now?

**Comment by FudgePucker** [comment]
Simple explanation, banking software is more advanced than the budget hardware the station uses. The PDA's banking software uses quantum computing to update its information instantaneously across the universe.

**Comment by ShiftyRail** [comment]
Well, that was _one_ use for money on the station

**Comment by Aurx** [comment]
Really, the money system needs to be properly integrated everywhere so everybody cares about it if it's ever going to matter to anyone but traders.

**Comment by ghost** [comment]
Money is for magbites and chococoins you shitlers

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
