### PR TITLE
PackedStation bar tweaks

### PR DESCRIPTION
**Pull request by brndd**
[packed]

Powercreep etc.

This is basically #22449 but for Packed. There was less space here (due to no backroom), and getting rid of the still is obviously not an option even though it's pretty much a completely useless legacy machine. That's why there's no coffee brewer here. A circuit board for it is provided in the locker, should the bartender wish to become a barista.

I also changed the rtables behind the counter (not the counter itself) into regular tables for convenience and aesthetic reasons.

After: 

Before (sorry this doesn't exactly match the after pic and I'm too lazy to take a new one):

:cl:
 * rscadd: Packedstation bar now has soda and booze dispensers, and a circuit board for the coffee dispenser. It is also now easier to make a comfy, moody lowpop bar because the windows leading into Botany have been removed and blackout curtains have been added that can be closed to stop light from the kitchen leaking into the bar area.

### CODE REVIEW

**Comment by Hoshi-chan** [comment]
Hi, I have a request. 

Could you put curtains or shutters or something over the grille windows, to optionally block out the light coming from botany? A lot of the time when bartenders try to decorate that place, it becomes this huge hassle to dismantle the bar just to get to those windows to block out the light coming in from botany.

Like, say if you're trying to cultivate a cozy atmosphere in your lowpop bar.

**Comment by brndd** [comment]
That's a good idea. I think I'll remove the windows opening into botany altogether and add some blackout curtains that can be closed to cover up the kitchen (they spawn open). I think I also want to do something about the windows opening into the hallway, because given the bar's small size there'll be lots of light pollution coming in from there. I've been told there's a type of window that can darken (turn opaque) via button signal, so I'm thinking of using those as soon as I figure out what they're called.

Here's what I've got so far. I repainted the floor and took out a couple of bulbs to give you some idea of what it might look like if you tried to make it moody.

**Comment by Exxion** [comment]
>still is ... pretty much a completely useless legacy machine.

Shut the fuck up

**Comment by brndd** [comment]
The only thing the still produces that you can't get elsewhere in the bar more easily is engine degreaser. If it let you avoid messing with universal enzymes to produce some boozes (eg. sake) that'd be neat, but it doesn't.

~~Also uh, DNM this until I manage to get the tintable windows working. It's a bit more complicated than I expected.~~ Nevermind the tintable windows are a big enough can of worms to not warrant bothering with for this PR.

**Comment by brndd** [comment]
Alright, I removed the superfluous windows into botany and the kitchen area and added blackout curtains that can be closed to create a very moody atmosphere (and to make the kitchen area more private so you can drag the botanist's body into the gibber without everyone in the canteen seeing you). There's a new pic in the OP.

I wanted to make the windows into the hallway smartglass, but I can't be arsed dealing with the Git bureaucracy required to make that work (smartglass was a bit buggy before I fixed it in #22465) so if you want light from the hallway to not leak into the bar you'll just have to renovate that yourself.

**Comment by Exxion** [comment]
Yeah, you can get the things it produces elsewhere, and always have been able to. It's a flavor machine. Bartender is a flavor job.
And can you reach the soda dispenser and booze dispenser at the same time?

**Comment by brndd** [comment]
Yes.

**Pull request merged**
