### PR TITLE
(WIP) Fossilized Plants Revisited

### PR DESCRIPTION
**Pull request by Kurfursten**
I'm officially on hiatus. Not a mental health break or some protest - just work has picked up again, grad school is coming back, and all those things in life that deny us time to code anymore. This is a little something I was working on before, I figured I'd post it here and maybe make some edits over time if I find a minute here or there to work.

**Basic Premise**: A while back, Deity added a bunch of neat fossil plants, but most of them weren't very interesting for botanists. Providing things like capsaicin (which you can access immediately with chilis) or poison wine (why would you give this to the bartender as a nonantag?), most of it didn't add up to fossil plants existing as anything but a curiosity. This seeks to change that. At the same time: people were complaining that back in the good old days, we had booze that had actually fun effects instead of just getting you drunk. And someone suggested a good Xenobotany gene idea. The stars were aligned.

**Each alien plant given some attribute that makes it useful or interesting to the service department.**
- Jurlmah contains Clonexadone, which heals plants and de-ages them, and can be used for synthmeat in the kitchen.
- Amauri contains smoke, and its fruit has the unusual NOREACT property which could be used for some interesting xenobotany
- Gelthi has harvest_repeat = 2, based off the Falling Fruit suggestion ( #8891 ) - should self harvest. **Needs testing**
- Thaadra has an amazing starting potency, the altertemp gene, and still contains frostoil **May need to adjust temp tolerance, test further**
- Surik now contains Karmotrine, which can be made into a number of special cocktails (listed below)
- Poison Wine, which would have been otherwise unobtainable, now uses its old sprite and appears in the boozeomat as a premium reagent.
- Lemon-Lime Soda, which was previously unobtainable, is now possible to make by mixing Lemon Juice + Lime Juice + Soda Water
- You might sometimes get Lemon-Lime at a soda machine if you choose the orange soda Starkist
- Brawndo, found in the remaining fossil plant, now disables warning lights on hydroponics trays, because it has what plants crave. Fun for service pranks.

Karmotrine is used to make a bunch of _fun_ drinks only accessible if the xenoarcheologist or miner brings back Surik and the botanist grows it. A pretty decent wall - don't expect to see these every shift. All received animated sprites. 
animations
- Smoky room - causes the player to say random noir-inspired lines and gain the NOIR defect **Needs fixing, does not gain NOIR gene**
- Rags to Riches - causes the player to shed small amounts of money, not competitive with mining by any means for cash
- Bad Touch - causes hallucinations and hallucination damage **Not working**
- Electric Sheep - causes humans to spark, causes MoMMIs to get drunk (unlike any other alcohol) **MoMMI function not working - silicons don't seem to gain reagents via transfer in testing, may need hacky solution**
- Suicide - Induces repeated instant vomiting until exhausted
- Metabuddy - When examined, shows the player their own ckey. Drinking causes a cult-like M icon to appear over the player and anyone else who drank some. **Overlay not working**
- Waifu - Inspired by schoolgirl mode, turns the imbiber into a female and puts on a schoolgirl outfit
- Scientist's Serendipity - If a glass contains less than 10 units, not animated. If it contains more, animated and can be used for large amounts of research. Only useful if Karmotrine can be found before R&D is maxed out, but provides ample research in a wide variety of categories.
- Beepsky Classic - In the system of security team, plays a hailer effect. In the system of anyone else, briefly stuns and plays a stunbaton sound.
- Spiders - When you drink this, a spider pops out of your mouth. AAAA.
- Weedeater - Grants a weed eat spell effect, like the Diona verb. May eventually be better to give Diona this spell instead of using verbs, but I didn't want to be even less atomic. **Not properly granting the spell on consumption.**

**Naturally, adjusting what's contained within each of the fossilized plants is up for discussion, and I intend to edit the wiki whenever this project finishes, presumably in the distant future.**

### CODE REVIEW

**Comment by 9600bauds** [comment]
Ahhahahhaa this is amazing

**Comment by 9600bauds** [comment]
Do not eat plastic bottlecaps though

**Comment by JustSumBody** [comment]
> Bad Touch

:smirk:

**Comment by carshalash** [comment]
> Get surik fruit from no-fruit
> Get service borg
> ???
> Waifus.

**Comment by FudgePucker** [comment]
AAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNDDDDDDDDDDDD I close my PR

**Comment by Intigracy** [comment]
no-fruit can be made to ignore the xenoarch ones, fam.

**Comment by Shadowmech88** [comment]
Given how fast the no-fruit cycles, the odds of being able to get one specific plant from a no-fruit are pretty small, even taking into account the fact that the loop is predictable. It's for that reason that ambrosia cruciatus was left in its possible picks.

If it _really_ becomes an issue, the cycling order could always be randomized, which would make it nearly impossible to get a specific desired plant.

**Comment by Intigracy** [comment]
confrictu

**Comment by ComicIronic** [comment]
RIP this confrictu PR
Feel free to reopen if/when updates happen.

**Pull request closed without merging**
