### PR TITLE
Shut up games vending machine

### PR DESCRIPTION
**Pull request by brndd**
## What this does

Removes the cheesy spoken-out-loud slogans from the games vending machine.

## Why it's good

This thing is usually next to the library D&D table and can be annoying if you're actually playing D&D there.

## Changelog

:cl:
 * tweak: The games vending machine no longer speaks

### CODE REVIEW

**Comment by Dacendeth** [comment]
Weird change, all it takes is a screwdriver to turn off vending machine messages.

**Comment by brndd** [comment]
I guess, but it's always better not having to do that. These are kind of annoying and I say this as the guy who added this vending machine in the first place.

**Comment by SonixApache** [comment]
just turn it off
i despise the lotto machine and barvend but turning them off by default is ~~gay~~ _right sorry mrs. github_ a bad precedent and removes content that doesn't need removing

**Comment by wotisjanitor** [comment]
Close this PR

**Comment by brndd** [comment]
> Close this PR

OK fam

**Pull request closed without merging**
