### PR TITLE
make PDA health scanner better

### PR DESCRIPTION
**Pull request by 9percents**
it doesn't show limb damage
this pr makes it

:cl:
 * tweak: PDA healthscanner got a small update and now shows damage for specific limbs.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Well then why even take a scanner as a doctor ?

**Comment by 9percents** [comment]
it has the memory of the last readout

**Comment by DrSnips** [comment]
The health analyzer still possesses many traits like being able to scan heads. Anything to make the PDA version a good backup is nice.

**Comment by GreatBigFailure** [comment]
> Well then why even take a scanner as a doctor ?

Mechanic PDA works as a device scanner with the only difference being not being able to deposit one scan at a time, which is never ever used. Device scanners are still taken.
Science PDA works as a signaler, signalers are still taken.
It can just be more convenient to have a separate device for things, especially with how clunky the PDA UI can be at times.

**Pull request merged**
