### PR TITLE
AI can no longer control emagged doors

### PR DESCRIPTION
**Pull request by BroseidonMOO**
AI now get a helpful message and cannot control doors at all when the door is emagged. Previously they had limited control that didn't matter (such as bolting an unbolting, although the door could never be opened or closed until repaired). This now removes that entirely so the AI/borg doesn't mistakenly think the door is functioning.

### CODE REVIEW

**Review by N3X15 — APPROVED** [review]

**Comment by ghost** [comment]
can the ai hack the door as if door wire were cut? i'm not saying they should, seeing as the entire door circuit gets fried, but just curious

**Comment by BroseidonMOO** [comment]
No, this just provides information to the AI that the door circuitry is fried, as previously it would show the interface and everything would seem fine, but you couldn't actually open or close the door. You were able to bolt and unbolt it, but that didn't matter because the door would be stuck anyway until the circuitry was repaired.

All this does is stops the UI from coming up and gives a message that its busted, rather than opening the UI and making it look like everything is fine.

**Comment by Aurx** [comment]
Does this provide said message on hotkey interaction or the Open radio link?

**Comment by BroseidonMOO** [comment]
No, although it didn't previously either. I didn't want to just hack into Topic, which is how it calls it from hotkeys.

**Pull request merged**
