### PR TITLE
Ports moving/lying/dead diona nymph sprites from Eris/Bay

### PR DESCRIPTION
**Pull request by jknpj**
nymph
https://webmshare.com/1wAW3

Nymphs now drop all their items on death to avoid silly floating gear.

### CODE REVIEW

**Comment by 9600bauds** [comment]
Wait, so you stun a nymph and it goes to sleep?

**Comment by Lokiamis** [comment]
The hats are unfortunate

**Comment by AI-Is-Rogue** [comment]
I find this cute.

**Comment by Ephx1** [comment]
Yeah killing them will be much more satisfying now.

**Comment by Blithering** [comment]
What about the roast nymph recipe?

**Comment by jknpj** [comment]
@Blithering still looks the same

**Comment by Blithering** [comment]
I meant last time I checked that wasn't in /vg/ codebase, can that be ported?

**Comment by jknpj** [comment]
Let me have a look at it

**Comment by Blithering** [comment]
dionaroast
This is the icon, already in the game files. Checked on the test server and you can't put diona nymphs in a microwave.

**Comment by Kitfox88** [comment]
I think the hats and backpacks staying still while the sprite itself animates is a little awkward, but otherwise I like it.

**Comment by jknpj** [comment]
@Blithering i'll port it once the simple mob holder bug gets fixed

**Comment by Blithering** [comment]
Woop, more bizarre food.

**Comment by Exxion** [comment]
What simple mob holder bug?

**Comment by jknpj** [comment]
@Exxion nymphs survive being microwaved because you're microwaving the mob holder and when the mob holder is gone it just drops the nymph, this happens with all simple scoopable animals

**Comment by Shadowmech88** [comment]
Mob holders should really just delete their held mob when they themselves are deleted.
We can just put the code for dropping the mob into `dropped()` before the code that deletes the holder.

**Pull request merged**
