### PR TITLE
Cookable Sugar and Salt cubes

### PR DESCRIPTION
**Pull request by Eneocho**
## What this does
Microwaving 10u Sugars (regular sugar or corn syrup) makes 5 sugar cubes. Doing the same with 10u Salt makes 5 salt cubes.
## Why it's good
Food fluff is good.
:cl:
 * rscadd: You can make sugar or salt cubes by microwaving 10u sugar/corn syrup or salt respectively.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
squidmoko set you up to this I know it

**Comment by Eneocho** [comment]
> squidmoko set you up to this I know it

Nope, I was thinking that having the wild west vault horses and a wooden cart as a Luddite variant to the tractor+cart would be a cool idea, then theorycrafted how they'd work, and figured you could tame the horse with carrots and salt cubes. But we didn't have salt cubes so I quickly made this.

**Comment by MercuriusGH** [comment]
Ian/corgi drawn carriages

**Comment by Blithering** [comment]
Now you can pull off the classic "one lump or two?" Gag and promptly get gunned down by sec.

**Pull request merged**
