### PR TITLE
Strange wheelchair now allows you to buckle other people to it

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Remind me in about an hour or two to make this code less worse
:cl:
 * tweak: You can now buckle other people to the strange wheelchairs that can fit multiple people.

### CODE REVIEW

**Comment by Kurfursten** [comment]
First: if you are going to do this, don't do it with pasting, do it with inheritance to be more OOP

Second: does anyone actually want this? I actually think it's a little annoying. If you can't even convince someone to get into your chair why should you be able to drag them in? It'd be like if you could force people to join your religion as chaplain but then they can still leave it if they want anyway. What's the point?

**Comment by boy2mantwicethefam** [comment]
Wild ride

**Comment by cloutcode** [comment]
speed merge now now now

**Comment by GreatBigFailure** [comment]
>What's the point?

More options means more fun. There's no harm in it since you can buckle people into anything else already. Maybe you have no legs but you do have arms, and your armless, legless buddy is squirming on the floor. Now you can help him out. I know that'll never happen but whatever.

**Comment by gurfan** [comment]
the emojicracy has spoken

**Pull request merged**
