### PR TITLE
Revert "Too much corn oil can give you a heart attack (#25814)"

### PR DESCRIPTION
**Pull request by SonixApache**
This reverts commit 89dadf53a3c6d37e7ccf4cebaef86ab94ca755da.

completely untested by yackem, this code is never called and throws a warning in the compiler

### CODE REVIEW

**Comment by SirSkeleto** [comment]
yeah im thinking he's based

**Comment by boy2mantwicethefam** [comment]
kay, lemme fix

**Comment by Kammerjunk** [comment]
amazing

**Comment by SonixApache** [comment]
@boy2mantwicethefam don't bother, the man should test his code

**Comment by PrimeDSS13** [comment]
>code is never even called

dear lord

**Pull request closed without merging**
