### PR TITLE
plasmaman meat

### PR DESCRIPTION
**Pull request by robintime**
now they can have the shitty rotting flesh they always deserved, worth 0.5 units of nutriment as opposed to the 3 of generic meat.

:cl:
* rscadd: gives plasmamen their own special meat when butchered.

<sprites><oversight>

### CODE REVIEW

**Comment by Eneocho** [comment]
Skelemen when gibber'd produce bones. Shouldn't plasmen produce plasma bones?

**Comment by FlintBarrel** [comment]
how hard would it be for you to make it purple? Also does this affect the amount of biomass a cloner would get?

**Comment by BomberBro** [comment]
Plasmamen aren't just skeletons, they're more like ghouls (which is why they have skin during surgery). Meat may want to have a bit of plasma in there too.

**Comment by robintime** [comment]
> Skelemen when gibber'd produce bones. Shouldn't plasmen produce plasma bones?

i was originally going to make them produce bone sheets when butchered just like skelemen do, but like bomber said they actually DO have flesh which i realized while coding that


> how hard would it be for you to make it purple?

i actually did try out several different colorations for the meat sprite! it was originally light purple and then pinkish purple which both (in my opinion) looked bad next to the plasmaman sprite itself because the colors simply didn't match. i decided to go with dull indigo because it's between the color of the skin and the plasma bits. i think if i were to make it a saturated purple it wouldn't give off the same effect of being dry and unhealthy, but i'll play around with it.

>Also does this affect the amount of biomass a cloner would get?

i'm pretty sure every meat item gives the same amount of biomass, as cloning.dm references the parent meat and not specific meat types.

> Meat may want to have a bit of plasma in there too.

uno momento

**Comment by robintime** [comment]
alright, the plasmaman meat now has 5 units of plasma in it, which i can't believe didn't occur to me to do in the first place. thank you bomber!

as for the sprite:
meat
here are a couple mock color changes i made really quick, with the current one on the far right. let me know if any of these are preferable and i'll clean that one up!

**Comment by KingofHONK** [comment]
JUICY

**Comment by Optimism333** [comment]
> alright, the plasmaman meat now has 5 units of plasma in it, which i can't believe didn't occur to me to do in the first place. thank you bomber!
> 
> as for the sprite:
> meat
> here are a couple mock color changes i made really quick, with the current one on the far right. let me know if any of these are preferable and i'll clean that one up!

I think either of the two in the center could do. The dull shade of purple seems appropriate.

**Comment by robintime** [comment]
cleaned it up a bit and made it more purpley! thoughts?
meat
(the purple again commit is this, i forgot to save the .dmi haha my bad)

**Comment by Optimism333** [comment]
> cleaned it up a bit and made it more purpley! thoughts?
> meat
> (the purple again commit is this, i forgot to save the .dmi haha my bad)

Very good. I give it a plasma/10

**Comment by Eneocho** [comment]
> 
> 
> alright, the plasmaman meat now has 5 units of plasma in it

On my way to non antag kill, butcher twice and revive the plasmeme assistant to acquire plasma.

**Comment by Eneocho** [comment]
> i was originally going to make them produce bone sheets when butchered just like skelemen do, but like bomber said they actually DO have flesh which i realized while coding that

They could give plasmabones when gibbed.

**Comment by Eneocho** [comment]
Does plasmeme meat produce the same amount of biomass for the cloner?

**Comment by Eneocho** [comment]
> 
> 
> Does plasmeme meat produce the same amount of biomass for the cloner?

@robintime

**Comment by robintime** [comment]
> Does plasmeme meat produce the same amount of biomass for the cloner?

my bad on the late reply, didn't check git for a few days! as i said before, i'm PRETTY sure every meat gives the same amount of biomass. i COULD make it give less, but i'm not sure if that would have any large impact repercussions on plasmeme gameplay or not (in terms of for example butchering a dead body and using the body's meat to clone someone when medbay is fluoride)

**Pull request merged**
