### PR TITLE
How do we engiener=

### PR DESCRIPTION
**Pull request by CptWad**
latest meme
after an AI plasmaflooded and killed EVERYONE but two people an engineer and one CE, central command asked them how everything he was doing
The CE responded: "How do we engiener="
he never responded after that

### CODE REVIEW

**Comment by CptWad** [comment]
what

**Comment by gbasood** [comment]
pick(1,2,3)
if(1) say shit
if(2) say shit
if(3) drool

w h y
I know it's not your code so I'm not forcing you into changing it but I'm complaining here because I can

**Comment by CptWad** [comment]
ok

**Comment by CptWad** [comment]
wait we can

**Comment by gbasood** [comment]
because it doesnt mean anything if they do
We can require that PRs get approved by at least one contrib I think before merging

**Comment by Intigracy** [comment]
when contribs do it the check is green

**Comment by Intigracy** [comment]
"I know it's not your code so I'm not forcing you into changing it but I'm complaining here because I can"

**Comment by gbasood** [comment]
@Intigracy yes exactly

**Pull request merged**
