### PR TITLE
All Dogs Go To Heaven 2

### LINKED ISSUE #30431: sec doggy doesnt like brig medic and other issues
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
9beaa3b9272824f5e15dfb19e142e8f6f61cc3ff

# Description
brig medic cant open wolf cage from traders and the wolf smashes tables/glass/anything it can when following its owner
# Steps to Reproduce
try to open wolf crate from traders as brig medic. Second part: tell your dog to follow you by pointing at it, lead it adjacent to tables, glass, etc, and watch it destroy the station as if the security it's made to help aren't doing that enough already
# What you Expected
friendly doggy who help
# What Actually Happened
doggy that i had to get help to open, and who smashed shit

### PR DESCRIPTION
**Pull request by Kurfursten**
closes #30431

🆑
* tweak: Tamed wolves will no longer smash objects when wandering about, but if they lose their master they may revert to destructive ways.

### CODE REVIEW

**Comment by DamianX** [comment]
Do they re-gain the object-smashing when the leader dies?

**Comment by Kurfursten** [comment]
No, but you also don't stop being a wolf's alpha on death I believe -- for example if you get killed but the dog survives you can still be cloned and come back to it. Or if you both die and you laz the dog.

**Comment by DamianX** [comment]
```
if(stance == HOSTILE_STANCE_IDLE && !client)
			//Check if the alpha is still alive
			if(pack_alpha)
				if(pack_alpha.isDead())
					visible_message("<span class = 'notice'>\The [src] lets out a mournful howl. </span>")
					//Howl noise?
					pack_alpha = null
```
this makes me think what you said is wrong, especially since `pack_alpha` would point to the old mob

**Comment by Kurfursten** [comment]
You're right. Okay, I can make them smash again when wild.

**Comment by GreatBigFailure** [comment]
Maybe have them start smashing when they're very hungry as a sort of natural warning

**Comment by Servalfang** [comment]
gordon?

**Pull request merged**
