### PR TITLE
Box: Return of the Vacant Office

### PR DESCRIPTION
**Pull request by GeneralVeers25**
The much-awaited and possibly quite controversial rework/shrinking to Box Telecomms is finally here. The pictures will do it more justice than my words can. Compiled and locally tested, I found no blind spots on any cameras and everything should work.

Old Telecomms: 
old_tcomms

New Telecomms:
new_tcomms2

New HoS Office:
new_hos

New Engineering Secure Storage:
new_secstorage

[box]
:cl:
 * rscadd: Box: Telecomms has been shrunk and optimized to provide free real estate for the rest of the station. Some new vacant offices and construction areas have been added, including the one that was so popular as a Bar during the brief period while Mechanics was gone.
 * rscadd: Box: The HoS Office will also no longer be infested by carp every shift.

### CODE REVIEW

**Comment by ghost** [comment]
Gen access windoor the parts so they don't get the zas succ and end up all over the place.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Telecomms seems to have no cooling pipes?

**Comment by GeneralVeers25** [comment]
@SarahJohnson489 Good idea, I've added them.

@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE Are you sure? This is what the pipes in the room look like.

new_tcommspipes

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Oh ok it just doesn't show in the screenshot

**Comment by Riekland** [comment]
I can now turn the aft hall into a freezing shithole with just one simple wall removal, epic

having a fully functional mech charger just sitting in maint is a bad idea

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah sure my choice for sabotage will be painstakingly removing a rwall to unleash the deathly cooling power of a single dinky freezer on 20000L of hallway air

Not breaking a window to space or something

**Comment by DamianX** [comment]
Does the wall around the HoS office actually do anything?

**Comment by ghost** [comment]
You already could if you hacked a door open Riek.

**Comment by Hoshi-chan** [comment]
What's the deal with the broken window and atmos tape? This is Box, not Deff.

**Comment by GeneralVeers25** [comment]
@Hoshi-chan it's there for gameplay purposes. In the current version, there is a clear path from the auxiliary room with the gas canisters into the Server Room itself which doesn't trigger the Control Room turret. The broken window and tape designates marks where that path is now. Putting a wall there would eliminate the path, since you'd have to deconstruct a telecomms server to get into the cold room.

@DamianX it provides some meteor protection. The HoS Office on Box is the most exposed office on any map to meteors and carp - all other maps have a similar shield somewhere around it. This is just providing it with the same level of protection. I also moved the carp spawner further away so they won't immediately beeline the dog.

**Comment by DeityLink** [comment]
~So the Void Jetpack and NASA space suits weren't placed in a new location? imo you could replace either one of those two electrical lockers or the snacks machine with it. They had a purpose, even if almost negligible, in allowing you to enter the tcomms' cold room unharmed.~ Disregard that, I found it.

**Pull request merged**
