### PR TITLE
talons no longer break windows

### PR DESCRIPTION
**Pull request by unid15**

### CODE REVIEW

**Comment by Iamgoofball** [comment]
why?

**Comment by Imagebard** [comment]
@Iamgoofball 
If you actually played /vg/station you'd know why.
Now sod off.

**Comment by AutismSpider** [comment]
@Iamgoofball  we cant have nice things here

**Comment by Iamgoofball** [comment]
@Imagebard open codebase shitbag

@AutismSpider okay

**Comment by Imagebard** [comment]
@Iamgoofball 
I am just trying to remind you that you're not important and nobody listens to you because you can't code and you have a bad sense of balance on the game so even when commenting on PR's you're often wrong and following your suggestions would be catastrophic to /vg/station as proven by what happened to /tg/station after you started coding here.

**Comment by Iamgoofball** [comment]
you're the only person who seems to throw a hissy fit over me commenting on an open codebase I'm not banned from, you should re-evaluate your situation

i'm trying to provide constructive feedback and you start drama out of the blue every time

maybe you're the real problem?

**Comment by Imagebard** [comment]
>constructive feedback

*You don't even play on /vg/station anymore.*

**Comment by Iamgoofball** [comment]
Thanks for ignoring the starting drama bit.

**Comment by AutismSpider** [comment]
@Imagebard  what do you mean he cant code? He coders better then potato man that's for damn sure

**Comment by ghost** [comment]
Wow rude I didn't need to be brought in to this

**Comment by Zth--** [comment]
Seems like image beard has some anger problems

**Comment by clusterfack** [comment]
You didn't know he had a phd in being mad?

**Comment by 9600bauds** [comment]
I don't really see the point in this because the Vox still need their nitrogen tank which you can't strip them of, so they can still break out of brig but whatever

**Comment by FudgePucker** [comment]
If they hit the window with the tank you confenscate it.
Gassing vox is the most fun you can have as security. Take the tank and walk away.

**Comment by 9600bauds** [comment]
FYI even humans can break through a window so long as they have literally ANY item including ID or jumpsuit, just throw it at the window over and over

**Comment by Shadowmech88** [comment]
Is that intended? It doesn't really make sense for something that can't break a window via hitting to be able to break a window via throwing.

**Comment by 9600bauds** [comment]
Fuck if I know

**Comment by FudgePucker** [comment]
People who break brig windows are the worst. When I tried being a nice warden and just put someone in for five mins (after I reduced it from 10 behind hos back), he started breaking the window, wallflash confiscate stuff increase it to 10 mins. He kept smashing the window.

What the fuck is wrong with people? Do they want to be buckeled cuffed in solitary with a straight jacket and muzzle?

**Comment by AutismSpider** [comment]
@FudgePucker use the sleeper next time and give them 20 units of sleep toxin

**Pull request merged**
