### PR TITLE
Buffs clowns

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Requested by @BomberBro 
Bike horns will now play curaracha if the clown honking it wears a sombrero and a pancho

:cl:
 * rscadd: Clowns can now unleash their inner mexican via bike horns when wearing the mexican outfit box set.

### CODE REVIEW

**Comment by Apogee-dev** [comment]
sweet jesus, a genuinely good barry PR

**Comment by SonixApache** [comment]
barry PRs hit me the same way as those post-ironic deep-fried children's memes do
it's an abstract type of shitpost

**Comment by Dacendeth** [comment]
How is this a clown buff, cant anyone wear the outfit and benefit?

**Comment by ghost** [comment]
please us this for the horn sound, its obligatory
https://a.pomf.cat/fwvpmn.wav

**Comment by boy2mantwicethefam** [comment]
@Dacendeth Clumsy check, which clowns have.

**Pull request merged**
