### PR TITLE
Optimizes update_action_buttons

### PR DESCRIPTION
**Pull request by clusterfack**
Shaves off another ~10% of human life() I'd say.

How it works right now:
Makes a new image of the action object from its icon state and icon.
Blends it with the obj/screen button.
For up to 5 objects, every tick.

How it works after I optimized it:
Makes a new image once, sets its appearance to that of the action object (costless)
Since the image's loc is the obj/screen button it requires no blending
Does nothing else because my system isn't shit

### CODE REVIEW

**Comment by clusterfack** [comment]
Currently has a bug where I is not being passed through getfrompool into the new of the obj/screen which is resulting in a runtime error, halp

**Comment by Probe1** [comment]
:+1: Continue the battle against Life()

**Comment by clusterfack** [comment]
This will be about 20-25% total since how it was originally, you can check the PR for the last one I'm using the same profile

Also the database query was the blockbox stuff not actual lag

**Comment by clusterfack** [comment]
I've been investigating it and it points to a pooling bug that has yet to be seen before where the first of a new type isn't being called with arguments? Will try to fix today.

**Comment by clusterfack** [comment]
Fixed it

**Pull request merged**
