### PR TITLE
[DNM] Shuttle Wall Resprite

### PR DESCRIPTION
**Pull request by Shadowmech88**
Partial remake of #15051 except with more attempt at compromise and less immediately closing it upon realizing that people have different opinions.

Just doing the walls for now, I'll change the floors in a different PR if at all.
shuttle_comparison
New walls on the right.
The purple corners are there because this was taken from within the map editor.

[DNM] because I haven't actually edited the map at all yet, I wanted to get more feedback on the sprites first.

### CODE REVIEW

**Comment by SonixApache** [comment]
oh god i don't like change

**Comment by ghost** [comment]
It's like the old sprites, but with a bunch of grey lines crisscrossing​ through them

**Comment by optimumtact** [comment]
mine looks better than yours

**Comment by Lokiamis** [comment]
Ok I don't know who made these sprites because there are 3 motherfuckers trying to get them in, but it needs to end. I'm going to bully you for the sake of the server.
Look at them. They're shit. They are bad sprites compared to the ones we have now. They belong in fucking oldstation. You shouldn't sprite in mspaint with the square brush.

untitled

**Comment by Shadowmech88** [comment]
PJB originally made them, I just recolored them.

**Comment by PJB3005** [comment]
Dear god what a fucking disgrace.

**Comment by PJB3005** [comment]
Here's the reason my sprites don't work with fucking white.

Because I absolutely hate the flat top down "might as well be a metal plate placed flat" perspective, I want to give my sprites SOME perspective.

This is why in the original sprite, there's a clear "side" to the sprites, the light area, and the inside of the sprite is supposed to be IN BETWEEN these.

Being in between, it's supposed to be fucking dark. And the lines over the dark area are supposed to be support struts or something.

Now make them dark and oh shit there's so much contrast.

**Comment by PJB3005** [comment]
> You shouldn't sprite in mspaint with the square brush.

yeah it's almost like everything is a fucking square when you try to reduce busyness on the sprite and you're working in a meager `32x32`

**Comment by Shadowmech88** [comment]
Personally, I like these because I think they give the shuttle walls a boxier look, like what I think of when I picture a wall. The current shuttle walls, in my opinion, look kind of bulbous, almost cylindrical due to their shading, which is odd for a wall.

I agree that they lack detail compared to the current walls, but unfortunately I don't think I have the skill to improve the design or detail of the proposed sprites.

**Comment by SonixApache** [comment]
Needs comparison shot in the OP.

**Comment by Shadowmech88** [comment]
Done.

shuttle_comparison

**Comment by NigglyWiggly** [comment]
I honestly can't even tell what these lines are supposed to be.
I mean the current shuttle sprites have their problems, (namely the dark spots on the corner of each tile that keep it from looking like it's one smooth thing) but these certainly don't alleviate any of that

**Comment by Zennyization** [comment]
I think that the old sprites look better than the new ones.
For some reason the new ones make the shuttle look incredibly sharp and it's more grey than white.

**Comment by Shadowmech88** [comment]
I don't have the spriting skill to increase the detail on these, so it looks like the nays have it.
Do we still want the tile generating script? I could put that in a separate PR.

**Comment by RealestEstate** [comment]
the old walls have form. they look rounded; the shading on them is gradual yet reflective of the shape. notice the shadows cast by the ridges get bigger towards the base? that's all it took for it to convey the cylindrical shape of the wall, and it did a damn good job at it. so I ask why bother fixing what isn't broken(I would even argue that this are some of the best sprites on our server as far as walls go, imho.)?
the new walls however, they make no rhyme or reason. there's no shadow, there's no form(or if there is a form, it's lost in the placement of the hard monochrome angular lines) it's noisy, and the shading looks almost inversed to what it should actually be. this recolor looks worse than the already unappealing original made by pjb. just giving my 2 cents.

**Comment by optimumtact** [comment]
holy shit this repo is slow lmao

**Comment by Exxion** [comment]
We have like eight active coders, if that
Also can you go away

**Comment by SonixApache** [comment]
kill

**Comment by Exxion** [comment]
Not really sure why I didn't do that last time I was here

**Comment by Intigracy** [comment]
scrnshot1

**Comment by SonixApache** [comment]
Would look good on a syndie shuttle. Better than those weird blocks.

**Comment by Intigracy** [comment]
scrnshot1

**Comment by Intigracy** [comment]
We have a grayish version of the shuttle wall in the DMI already as well.

scrnshot2

**Pull request closed without merging**
