### PR TITLE
Keycard-gated hammerspace vaults revival

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[vault]

## What this does
brings back #32546 with suggested changes by @Kurfursten
image
entering a vault (from old PR)
image
image
image
easy finds
image
easy level vault, pod parts with infinite cell buried behind the curtains with parts
image
image
image
normal finds
image
normal level, a control centre with a computer that lists all vaults and their Z levels
image
hard level, a bar with a telepad to bring people to and from the bar, that bypasses the telejam set on the z-level with dungeons it's loaded on while still blocking people with bags of holding coming in. (hard finds are unchanged, and still 1x1 with either space, a lattice or a roid floor)

## Why it's good
thought this PR could use a good touchup

## Changelog
:cl:
 * rscadd: A mysterious small room guarded by a door with keycard slots can now be found in space, with the keycards to gain entry scattered in other parts of space. They say it's bigger on the inside, and depending on how hard it was to search for keycards, it could be either a pod part storage, control room, or fully fitted bar...

### CODE REVIEW

**Comment by djkramer123** [comment]
"found a pretty unique idea"

**Comment by Pastamadness** [comment]
Why yes I find my own old PRs neat ideas for me to find again, how could you tell?

**Comment by ErrorsWindows** [comment]
no no, if you think about it, through cell mitosis and recycling, kanef would technically be a different person by now, therefore it's somebody else's pull requests

**Comment by SECBATON-GRIFFON** [comment]
sorry, having issues compiling stuff right now, will revisit later

**Comment by Kromkar** [comment]
Lmao

**Comment by gurfan** [comment]
Much better than the last PR, though I don't know why you want to use those teleporters instead of just keeping the whole vault in one place.

**Comment by SECBATON-GRIFFON** [comment]
> Much better than the last PR, though I don't know why you want to use those teleporters instead of just keeping the whole vault in one place.

the bigger on the inside thing just looks neat

**Comment by gurfan** [comment]
Why is there a combat shotgun in the bar and not a double barrel?

**Comment by SECBATON-GRIFFON** [comment]
> Why is there a combat shotgun in the bar and not a double barrel?

kurf's suggestion was to add a 12 barrel one that's not quite deathsquad, not sure what he meant at first but changing it to NT12 now

**Comment by Kromkar** [comment]
When this inevitably breaks are you going to fix it?

**Comment by SECBATON-GRIFFON** [comment]
> When this inevitably breaks are you going to fix it?

keycard, vault loading and area portal stuff still works, just tested that

**Comment by gurfan** [comment]
> kurf's suggestion was to add a 12 barrel one that's not quite deathsquad, not sure what he meant at first but changing it to NT12 now

The NT12 isn't a twelve-barrel....

**Comment by SECBATON-GRIFFON** [comment]
> > kurf's suggestion was to add a 12 barrel one that's not quite deathsquad, not sure what he meant at first but changing it to NT12 now
> 
> The NT12 isn't a twelve-barrel....

if such a gun doesn't exist i guess i could just make it the normal one then

**Comment by BomberBro** [comment]
If you want an epic fallout 2 reference put the yellow keycard next to a destroyed pod and dead pilot

**Comment by pedr69** [comment]
well there's no more pulserifles so i guess it's an improvement

**Comment by Kurfursten** [comment]
Can't not like my own ideas, it's brainchild nepotism!

**Comment by SECBATON-GRIFFON** [comment]
> If you want an epic fallout 2 reference put the yellow keycard next to a destroyed pod and dead pilot

and here's where we'd put destroyed pods on this map
IF WE HAD ONE
(wyci i guess)

**Comment by SECBATON-GRIFFON** [comment]
test

**Pull request merged**
