### PR TITLE
Fat Security Hardsuit

### PR DESCRIPTION
**Pull request by GermanSanta**
The security hardsuit is just bad and needs something done for all those donut eating wardens, and golems.

Sec
sec2
sec3
download

### CODE REVIEW

**Comment by Kharkov72** [comment]
-EVA powercreep
+++++THE FATSEC META IS UPON US

**Comment by RealestEstate** [comment]
I'll take fatsec over femsec anyday

**Comment by Accipitermaris** [comment]
look at the size of this lad

**Comment by iFlashYou** [comment]
Either all or no hardsuits should have the fat variant

**Comment by GermanSanta** [comment]
Engineering gets rad protection
Atmos gets 100% heat, fire, and plasma protection
Security gets donuts

**Comment by GermanSanta** [comment]
Noticed there were 3 sprites visible on the each hand when looking forward. This has been fixed and everything is ready to go.

**Comment by strawberrytan** [comment]
I would be all for this if their beer belly hung out and it wasn't spaceproof for fatties

**Comment by SonixApache** [comment]
losing your space proofness is the price you pay for fatsec
:-1:

**Comment by Blithering** [comment]
fatsec ascended

**Comment by Kurfursten** [comment]
I don't like the inconsistency of fat-compatible hardsuit Could you at least make it a subtype? Like the gold atmos modkit or the stormtrooper modkit. That would be a good compromise for everyone I think. Modkits could be premium secvend or in the armory or trader or cargo or R&D or in your backpack when signing up with the obese disability, dealer's choice basically.

Not only would this help with immersions and compromise, but it would also mean being fatsec is a conscious choice. You mod your kid to do it ahead of time to accept your girth instead of just getting a perk of being sec if a fat virus goes around or chef dumps cornoil into all his food.

**Comment by Probe1** [comment]
@Kurfursten way of handling it was way cleaner.

**Pull request closed without merging**
