### PR TITLE
New Horizons Await

### LINKED ISSUE #25492: Horizon telescience literally unusable
(WEB REPORT BY: dustyny REMOTE: 206.221.180.138:7777)
# Revision
5abd023dae5105045e2e56cdc5591f90113f3ca0

# Description
horizon telescience console in front of entrance to area
# Steps to Reproduce
play horizon, go to telescience
# What you Expected
to be able to use the room without remodelling
# What Actually Happened
have to move console to have a functional room

### LINKED ISSUE #25509: Horizon medbay needs roller beds
Seriously there's none.

### LINKED ISSUE #25675: Horizon Robotics and RD mapping
Two issues I found:

- The mechbay room is not connected to the grid
- There is a missing scrubber or vent in the RD hallway outside robotics and it does not connect

It's looking better, plosky, but still finding stuff for you to fix.

### LINKED ISSUE #25745: Horizon- Improper maintenance door
(WEB REPORT BY: fentanyl REMOTE: 206.221.180.138:7777)
# Revision
e67cac20c356e7a019c3cb306b3d0b45be96470f

# Description
the maintenance door above the courtroom front door is a surgery maintenance door
# Steps to Reproduce
spawn, walk to area
# What you Expected
proper door
# What Actually Happened
improper door

### LINKED ISSUE #26483: NRV Horizon Central Acess mounted frames inactive
(WEB REPORT BY: invadergad REMOTE: 206.221.180.138:7777)
# Revision
800a44d8bef2c45036f5dce0e4ef16b5ee1aac7e

# Description
Most of central hallways mounted frames (newscasters, holomap, air alarm) appear to be inactive

### LINKED ISSUE #26489: Horizon: 'Space' hallway
image

Certain areas are not defined, a lot of the stuff on the walls and floor is labeled "Space".
This can be fixed ingame by using the blueprints or construction permit to define an area.

### LINKED ISSUE #26495: Horizon: Janny office has no Space Cleaner
he does it for free
also has no disposals bin which means he cant receive stuff in the mail

### LINKED ISSUE #26496: Horizon: Lack of portable air canisters/heaters/coolers in maint
what it says on the tin

### LINKED ISSUE #26501: Horizon: has 0 meteor protection (and a poverty of external airlocks)
horizon has 0 grilles or solars to protect against meteors so it gets fucked up the worst of any modern map
also it has a very low amount of external airlocks to space from maint, which is related to the lack of solars

### LINKED ISSUE #26504: Horizon Trade Outpost Weirdness
3 bottom tiles are not in the area, they're space
no left entrance meaning you have to hike around 100 tile to enter from the north when latejoining

### LINKED ISSUE #26508: horizon xenobio
just WHAT is going on here

and while we're here why are the cages so god damn SMALL?

### LINKED ISSUE #26518: Horizon: brig feedback
interrogation is way too far from the cells to be practical. it should go where the sec break room is so it's connected to the cells as there's no "unsecure interrogation room" like on box.

brig as a whole has basically 0 table space, the brig locker room has like 7+ items stacked on top of 2 tables

there should be a proper evidence room seeing as the horizon brig is around the same size as the snowmap brig

### LINKED ISSUE #26520: Horzon - There's one ATM on the entire station.
[horizon]

How do you expect me to gamble my life savings away at the slots if there's no damn ATMs

### LINKED ISSUE #26521: Horizon: Mining Storage APC area is too small
doesnt power the whole room, outpost camera computer is unpowered and has to be moved closer in. basically apc area is too small.

### LINKED ISSUE #26522: Horizon - Mech Bay APC isn't actually wired to the grid, doesn't charge
The Mech Bay isn't actually wired up properly, so it gets no external power. Not sure where the issue lies, but the wire goes into the Science wing.

### LINKED ISSUE #26523: Horizon: Entire Map Needs Area Redefinement
[12:55 PM] small_boss: >literally half the station has no area set

this is a very general thing but a ton of zones on the map have no areas set and/or are missing APCs. i know there are a lot of individual issues open for APC problems but this is really worth making an issue for in general due to how wide reaching the issue is so it doesn't get forgotton about

### LINKED ISSUE #26527: Horizon: Brig Hall has no APC
noticed this only because the lights start off at roundstart and there's no mapped in way to turn them on. it's no doubt not the only area missing an apc

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[horizon]

At last, the NRV Horizon has been refitted and released from drydock. Now on its maiden voyage, it carries the hopes of an entire corporation into the unknown!

Features: many bugfixes. A re-mapped Medbay. And airlocks that indiscriminately throw careless spacemen into the void! I hope you have your suit sensors on. The orange arrows represent the throwers. The blank spaces are there for where the shuttles dock.

As an aside, because it is impossible to board the ship without using a shuttle, the Nuke Ops are forced to deploy to the Asteroid and hijack one of the three shuttles (Salvage, Vox, or Research) to get on board the station.

Known Issue: Meteors, Blob Storms, Death Squad Mechs, Immovable Rods, and anything else hurled at the station via random event or admin bus will not impact the station. It is moving too fast.

New Render:

nuhorizonfinal

New Vox Shuttle:

VoxShuttle

New Salvage Shuttle:

salvageshuttlehorizon2

Closes #26527 
Closes #26523 
Closes #26522 
Closes #26521 
Closes #26520 
Closes #26518 
Closes #26504 
Closes #26501 
Closes #26496 
Closes #26495 
Closes #26489 
Closes #26483 
Closes #25745
Closes #25675
Closes #25492
Closes #25509
Closes #26508 

:cl:
 * rscadd: Horizon: Re-organized Medbay to improve the flow and make the department feel less stretched-out and awkward. Added a bell to the back entrance so Doctors get pinged and don't forget about people waiting there.
 * rscadd: Horizon: Security has been overhauled. The Armory has been re-organized. The Brig only has two cells, but there's a guillotine in case it gets overcrowded.
 * bugfix: Horizon: Disposals and pipes have been rerouted to avoid going under walls wherever possible.
 * rscadd: Horizon:  The ship is now actually moving. Entering space is risky, as a misstep can send you hurtling off into space. Some areas of the station, particularly those inside the meteor shields, are relatively safe.
 * rscadd: Horizon:  The ship now utilizes a new "gas sink" to pull gas molecules in from hyperspace. All gases must be filtered out in Atmos before they can be used.
 * bugfix: Horizon: A whole ton of bug-fixes. Missing pipes have been replaced, lost wires have been found, forgotten areas and APCs have been remembered, broken windows have been repaired.
 * rscadd: A new Z-level, "Hyperspace," which represents a ship moving forward through space.

### CODE REVIEW

**Comment by GeneralVeers25** [comment]
For reference, here is a video of a bomb dropping on the station, showing off the new base turf:

https://thumbs.gfycat.com/SlimSecondGosling-mobile.mp4

And here's me slipping off a cat-walk into space:

https://thumbs.gfycat.com/RealisticInsidiousHornedtoad-mobile.mp4

**Comment by Dacendeth** [comment]
Comms console still on the arrivals shuttle huh.

**Comment by GeneralVeers25** [comment]
> Comms console still on the arrivals shuttle huh.

Wew.

Gone now, good catch.

**Comment by Dacendeth** [comment]
How do nuke ops approach attacking this station, since jet packing in seems like not an option?

**Comment by GeneralVeers25** [comment]
> How do nuke ops approach attacking this station, since jet packing in seems like not an option?

> As an aside, because it is impossible to board the ship without using a shuttle, the Nuke Ops are forced to deploy to the Asteroid and hijack one of the three shuttles (Salvage, Vox, or Research) to get on board the station.

**Comment by Dacendeth** [comment]
I should learn to read.

**Comment by Kurfursten** [comment]
re:trade shuttle

Oof it's so thin, it's so hard to pile up your merchandise with that little space especially when you have stuff like a wonderful wardrobe, matter synth, vacuum, autolathe, that's already too much for the space you have provided. Did you remember to put horizontal windows above and below the sliding table window so you can display stuff on the counters without it getting snatched during a deal?

**Comment by GeneralVeers25** [comment]
Updated the Vox Cargo Shuttle to add extra space for you, @Kurfursten.

**Comment by SonixApache** [comment]
\>As an aside, because it is impossible to board the ship without using a shuttle, the Nuke Ops are forced to deploy to the Asteroid and hijack one of the three shuttles (Salvage, Vox, or Research) to get on board the station.
Slam-dunk option or docking option would be good then, considering you're locking the ops out of the station unless they get an emag or nab an unsuspecting miner/scientist. Also, this cripples the death squad mech launcher.

Guy commented in the thread that the spiders will break the captain's locker and then migrate and ruin everything nearby - keep that in mind. Sideways cockpit with no forward-facing window is an interesting choice...

Those are the complaints, :+1: overal.

**Comment by GreatBigFailure** [comment]
HoP office needs an alert swiper
I'd say either expand the mechanic office a bit, maybe using the little waiting room beside it, or replace the reinforced walls with normal walls to let the mechanic build. 

Besides that I'm looking forward to it. It's a really neat concept.

**Comment by KingofHONK** [comment]
Humbly requesting more windows from maint to space for opportunities to ZAS eachother into the void as a last ditch combat effort

**Comment by DeityLink** [comment]
Remember to update the surgery holosign switch following #27156 (set its id_data to "surgery") and add the virology ones as well.

**Comment by GeneralVeers25** [comment]
> >As an aside, because it is impossible to board the ship without using a shuttle, the Nuke Ops are forced to deploy to the Asteroid and hijack one of the three shuttles (Salvage, Vox, or Research) to get on board the station.
> Slam-dunk option or docking option would be good then, considering you're locking the ops out of the station unless they get an emag or nab an unsuspecting miner/scientist. Also, this cripples the death squad mech launcher.

The Research/Mining shuttle to the main asteroid does not have access requirements, so that is always an option. All Nuke Ops need to do is bust down the doors. I reserved the slam dunk/docking options for the Death Squad and Elite Syndicates. I know that the mech launcher doesn't work (neither do immovable rods, meteors, blob storms, or anything else that launches stuff at the station because the ship is just moving too fast) but it's not like squids can't bring their mechs on the shuttle.

> Guy commented in the thread that the spiders will break the captain's locker and then migrate and ruin everything nearby - keep that in mind. Sideways cockpit with no forward-facing window is an interesting choice...

I tweaked the salvage shuttle. Updated the picture.




> Humbly requesting more windows from maint to space for opportunities to ZAS eachother into the void as a last ditch combat effort

Why not. I've added a few small portholes around maintenance.



> HoP office needs an alert swiper

Added

> I'd say either expand the mechanic office a bit, maybe using the little waiting room beside it, or replace the reinforced walls with normal walls to let the mechanic build.

Sure. I replaced the walls with regular walls for building but a full rework is gonna have to wait until I completely re-do the Brig in a later PR. That maintenance is not friendly to quick changes.

> Besides that I'm looking forward to it. It's a really neat concept.

Full credit to @plosky1 for the original map.

**Comment by SonixApache** [comment]
you made the shuttle even worse but at least it makes sense now structurally so whatever
fuck you robo and fuck the spider migration season

**Pull request merged**
