### PR TITLE
New Wizard Spell: Summon Snacks / Diabeetusol Rework

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Adds the summon snacks spell. A single target spell similar to shoe snatching charm. This one's my favorite.

### Summon Snacks
**Cost: 20, requires robes, 30 second cooldown**
Forces a snack and drink into the target's hands. The wizard can target himself. If the target is holding anything at the time they drop them to hold the delicious munchies. The munchies can't be dropped, they can only be eaten or fed to someone else. 

**Upgrades:**

**Speed, 10 per level, max 3**
Minimum cooldown is 15 seconds

**Amount, 1 per level, max 5**
Reduces how much of the snack you can eat per bite by 1u of chem per level, effectively increases how long it takes you to eat the food without increasing how many chems are inside.

**Power, 25 per level, max 1**
Adds 1u of diabeetusol to both the snack and drink. See that section for why this costs so much and should cost more. 

**Move, 0 per level, max 4 (sort of)**
Move changes what's on the menu. They each have different chems in them but are only mildly different. Levels 0-3 are menus, getting it to level 4 resets it to 0 so you can cycle through them. I like the Dan one.
sponsoredbydiscountdans

### Diabeetusol
I originally made this as a hasty finish to the gingerbread vault and always hated how it turned out. It was made to only match the weapons found in the vault.
Since it was the perfect thing to match the theme here I've reworked it to match the intended concept much better and be generally more fun/flexible. 

Diabeetusol metabolizes very slowly, has an extremely high nutrition value, and functions differently depending on how much sugar you have in your system. If you have less sugar than diabeetusol then you'll become confused, dizzy, your vision will blur, and now and then you'll pass out for a second. If you have more sugar then you'll rapidly gain weight. Once you're past a certain amount of nutrition your heart explodes. Also it makes you play tuba sounds which makes me smile.

**If anyone has suggestions for more "menus" please throw them at me. They're really easy to slap in there and I think it's a fun mechanic.**
:cl:
 * rscadd: New Wizard Spell: Summon Snacks
 * tweak: Diabeetusol V2: Full Fat

### CODE REVIEW

**Comment by ghost** [comment]
>Also it makes you play tuba sounds which makes me smile.

can we get a webm of this in action

**Comment by GreatBigFailure** [comment]
I'll make one tomorrow. I was giggling like an idiot while testing which is a good sign.

**Comment by juanototo2** [comment]
Reduce the starting cost to 10 a la street alchemy and this spell becomes perfect.

**Comment by juanototo2** [comment]
Besides, diabeetusol costs too much for the cost of Blink and a shitty option. I mean, you MAYBE kill if he willingly chooses to consume the snacks instead of rushing to the nearest chem dispenser for acid or removing his hands, he doesn't use lipozine or waterpotass to clear himself of it, and he lets him gain enough weight to die, AND he doesn't get cloned or even surgerized and defibbed.

**Comment by GreatBigFailure** [comment]
Originally it was 15 with power being another 15. I'd be happy to change it if it's majority opinion but during testing I realized how strong the spell can be. Diabeetusol used to just be a tiny buildup -> heart explodes, but now it's extremely debilitating until it's gone or your heart explodes. So it's less funny immediately-lethal chem and more removing that person as a threat for a bit unless they eat a bunch of sugar which will almost guarantee their heart explodes.
The food has really high nutriment without diabeetusol. With it you become fat super fast and can't force any more food down, meaning you have a hard time emptying your hands. Turns it from a tasty disarm to a 30 second cooldown force-pickup double superglue until you can feed it to a monkey. 

All that said this was during testing. It's hard to say how it works in an actual round.

**Comment by GeneralVeers25** [comment]
A few extra combos for you:

Pizza Night - "N'OT DE'LIV'RY" or "P'ZZA P'ZZA" - a slice of pizza and a regular cola
Brunch - "BREK'FEST CL'B" - waffles or a fried egg and a bloody mary.
State Fair - "H'RT AT'CK" or something, no clue really - Corn Dog and Candied Apple
FatSec - "H'PPY P'G" or "B'D C'P NO D'NUT" - Donuts and coffee

You could also do a lot of "National" menus - a French one that gives you escargot and frog legs, or a German one that gives you sauerkraut and a sausage, really the possibilities are endless. Props if you also make them give you a stupid hat too.

**Comment by GreatBigFailure** [comment]
Just gonna save myself 3 hours and make a new PR. Fuck it.

**Pull request closed without merging**
