### PR TITLE
adjusted normal and fat sec jumpsuit, armor and sec armor sprites

### PR DESCRIPTION
**Pull request by SonixApache**
leave a comment about which ones you do and don't like

courtesy of @drawsstuff
🆑 included
Left: old - Right: new - Below: @jackfailure edits
oldspritesnewsprites
morefat

personally 
- i like the properly adjusted armor sprites for fatties
- i'm impartial about the color change though i feel like the darker red wouldn't shade well with blood
- i don't like the new armor as a replacement, but wouldn't mind it as alternative

so it's a :-1: from me

### CODE REVIEW

**Comment by KingofHONK** [comment]
I dont care for the armor either. Everything else is good tho. The ballistic vest looks too military.

**Comment by ghost** [comment]
Looking at them really closely in game I think they're slightly off. The jackboots are better black, while the I think the original red security suit pops out at the player better than the new one. The original red actually looks good with the new armour, and that's because it compensates for the brighter colour being used on the armour. Also the visibility of the back leg on the side-on sprite goes against how we do most other sprites. So some takeaways.

- I think the armour might look great a little bit darker, or with a darker outline, maybe some less blank grey space
- The uniform could do with more pop to it, just a tiny amount
- Jackboots should stay black
- God we need a proper fatsec armour sprite and this might be it with some tweaks

**Comment by ghost** [comment]
>fucking with jackboots

keep them dark please
Jumpsuit is fine, but I like the look of our classic armor more than the armor from this PR

**Comment by boy2mantwicethefam** [comment]
let he who is without bad taste cast the first stone

**Comment by Exxion** [comment]
Looks dull and washed-out

**Comment by PrimeDSS13** [comment]
I prefer the brighter colors, to be honest.

**Comment by SonixApache** [comment]
okay well i like jack's fatsprites more
gonna probably eventually close this and pick&choose the best parts based off feedback
and make a new one or just update this one

**Comment by Kammerjunk** [comment]
I'm just here because I like new sprites

**Comment by drawsstuff** [comment]
Go ahead and close this if you want and play pick and choose. Maybe relegate the jackboot sprites to swatboots or make the armor an alt.

**Comment by beesil** [comment]
The new jumpsuit sprite looks great. Agree with everything Jack said about the boots, as well as sad to lose the little badge/nametag(?) thing on the old armor.

**Comment by ShiftyRail** [comment]
I think the new red is a bit too washed-out and contrasts less with the rest of the sprites in the game.

**Comment by drawsstuff** [comment]
ebtter

how about now?

I'll be working on re-adding the badge

**Comment by nziswat** [comment]
What's the point of spiriting the regular armor to look like ballistic armor when ballistic armor is already in the game? I like the way it looks but I think it's a little unfitting as to what 'body armor' is supposed to be. Alternatively go all the way and resprite the sec helmet to be a black PASGT

**Comment by 9percents** [comment]
I like the change to armor
it doesn't look like an armored wifebeater

**Comment by PrimeDSS13** [comment]
split this into two, maybe even three different PRs to be honest.
one for the fatsec sprite fix and one/two for the resprited armor and jumpsuit.

**Comment by Blithering** [comment]
Personal opinions
Uniforms 
old > new
The brighter red pops more, and the details on the darker one are a lot harder to see clearly
Boots
old > new
Shiny black polished boots being noticeably different to black fabric is a good thing
Armour
old = new
Not really got an opinion on this, the added strap details are nice, but the badge being gone is a shame.

**Comment by SonixApache** [comment]
conflicts and such

**Pull request closed without merging**
