### PR TITLE
Adds BWOINK to the sound synth

### PR DESCRIPTION
**Pull request by GermanSanta**
SSethtide was like a year ago. And I want people to die from panic attacks

### CODE REVIEW

**Comment by Exxion** [comment]
It was removed for very good reason. It's a meta sound, relevant only because of its OOC meaning.

**Comment by jknpj** [comment]
No.

**Comment by DrSnips** [comment]
> 19 commits

**Comment by SonixApache** [comment]
[user was banned for this post]

**Comment by DamianX** [comment]
I recommend seeing medbay for a prescription of Alkysine.

**Pull request closed without merging**
