### PR TITLE
Changes the red alert notification from redalert1.ogg to notice1-freq…

### PR DESCRIPTION
**Pull request by SysadminJeroen**
…-0.39.ogg, that is a reference to Defcon the Game.

This is the new sound: [https://my.mixtape.moe/ampqos.ogg](https://my.mixtape.moe/ampqos.ogg)

:cl:
 * tweak: Changed the red alert noise.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
christ that's an ugly sound

**Comment by SysadminJeroen** [comment]
It is alike to notice1, however I ripped this directly out of defcon and set the frequency to 0.39 to make it sound like the Defcon Game soundeffect whenever you go to a different defcon alert state.
redalert.ogg is just this sound at normal speed and repeated 3x.

Edit: Here is an example how it sounds in Defcon. https://youtu.be/-wnZX8oR4dY?t=5m58s

**Comment by Probe1** [comment]
That is terrible.  I don't like the sound we have for red alert _now_.  This change would make it louder, angrier, and with more reverb.

**Comment by ghost** [comment]
Reference to a !!FUN!! game or not, it still sounds pretty bad, IMO.  The current alert sounds were ported from Bay a few months ago, and I think they're just fine.

**Comment by SysadminJeroen** [comment]
@Probe1 How could I make it better? Make it not blow out your speakers?

**Comment by SonixApache** [comment]
This sounds more like Delta to me.
Then again, I guess nobody takes red alert serious.

**Comment by SysadminJeroen** [comment]
Delta already has a noise, and is only used for Malf.

And I think that the reverb is a nice touch, especially since the hallways would echo the alert around the station.
That and you can never have enough reverb.

**Comment by Riekland** [comment]
the reverb is half life elevator shaft tier

it's dumb and also gay because the hallways of the space station are seperated by airtight doors dumbass

**Comment by SysadminJeroen** [comment]
Not sure if half life elevator shaft tier is good or bad in your opinion.

And you're talking about "muh airtight doors dumbass" but you can hear people knocking on windows and explosions happening on the other side of the station.

**Comment by Irradiation** [comment]
Hell, you can hear explosions happening at the other end of the asteroid somehow, evem if you're borderline out of the Z-level.

**Comment by SysadminJeroen** [comment]
I think that Delta is only used for malf, and malf already has a noise whenever it goes Delta.

**Comment by DamianX** [comment]
no one seems to want this

**Pull request closed without merging**
