### PR TITLE
Firefoam Poppers

### PR DESCRIPTION
**Pull request by west3436**
## What this does

**Adds Firefoam Poppers:**
- Boards are printed at a Circuit Imprinter with the Engineering 2 tech level.
- Requires 1 scanning module and 2 manipulators.
- Will trigger if it catches on fire or if a fire is within 1-3 tiles (with upgraded scanning modules).
- Sprays fire foam in a radius of 4 tiles; up to 10 with upgraded manipulators.
- Can be mounted on the ceiling which will make it invisible and non-dense (can be walked through).

**Thank you to @RealestEstate for the sprites!**

Undeployed item state:
item

Deployed machine state:
deployed

Triggered machine state:
activated

Deploying animation:
deploy

Triggering animation:
activate

Triggering video with sound:
https://github.com/vgstation-coders/vgstation13/assets/66280799/7dc6afc4-7302-4eb7-8948-698a8d8b7038

**How to use:**
- Print the board and add components as you would for any machine.
- Use a wrench on the completed machine to "minify" and pick it up.
- Use the minified object in-hand to toggle between floor or ceiling mounting.
- Apply it to the turf you want it located at.
- Touching the deployed popper will tell you its current scan and extinguishing range.

**Demo:**
https://github.com/vgstation-coders/vgstation13/assets/66280799/6ec0174f-b5ad-4ae4-babf-740a28f643cf

## Why it's good

- Provides Engineers & Atmos Techs a way to help prevent fires in critical areas like the Bar or Library.
- Adds another form of Science-Engineering interaction.

## Changelog

:cl:
 * rscadd: Added Firefoam Poppers which will spray fire-suppressing foam when a fire is detected.

### CODE REVIEW

**Comment by ghost** [comment]
I mean you could touch up the downscaled rimworld sprite a lil...

**Comment by west3436** [comment]
> I mean you could touch up the downscaled rimworld sprite a lil...

I could, but I won't! Happy to use sprites any competent spriter gives me.

**Comment by SonixApache** [comment]
How do you see the ceiling-mounted ones?

**Comment by west3436** [comment]
> How do you see the ceiling-mounted ones?

They still show up when you right click or alt-click the tile; additionally, a t-ray scanner will reveal them (they're also flipped upside down so you can tell them apart from ones on the ground).

**Comment by Theophrastus1** [comment]
get a real sprite!!!!

**Comment by Eneocho** [comment]
the popper sprite looks terrible outside of the rimworld visual context
also, instead of making it a machine, make it a grenade with an expensive/slow to make chemical reaction, then make it so each atmosian and atmos locker spawns with 1 grenade
this way fire protection stays reactive over proactive, would give a small roundstart supply and would encourage hardworking atmosians to ask the chemist nicely for some firefoam mix to make more, or stronger grenades

**Comment by kilozombie** [comment]
I like the sprite. Fuck all y'all

**Comment by kilozombie** [comment]
> instead of making it a machine, make it a grenade with an expensive/slow to make chemical reaction, then make it so each atmosian and atmos locker spawns with 1 grenade...

The whole point of this is to have a defensive measure against fire that doesn't require active firefighting, same as the firefoam poppers in Rimworld.

**Comment by Eneocho** [comment]
fair enough
still don't like the current implementation of generic extinguisher foam over a semi permanent firefoam, but that's fair

**Comment by RealestEstate** [comment]
tweaked a bit to look more fitting imo.

image

[popper.webm](https://github.com/vgstation-coders/vgstation13/assets/25192877/5438f091-c7ca-4d4f-92d9-6d4e3db27e8b)

the dmi:
https://cdn.discordapp.com/attachments/1084300577862856857/1244419321824808970/popper.dmi?ex=66550b4e&is=6653b9ce&hm=b38fe61e27d6183640c54c33d80516119e9f9f2072746695fe265ce9cfc6fc10&

**Comment by Inorien** [comment]
are we allowed to just blatantly steal the rimworld sprite
RealestEstate's looks way better anyway :^)

**Comment by ErrorsWindows** [comment]
yea it would fit with the stolen aesthetic of /vg/

**Comment by west3436** [comment]
> are we allowed to just blatantly steal the rimworld sprite
> RealestEstate's looks way better anyway :^)

Probably not! Yes, I'll be using his sprites

**Comment by Eneocho** [comment]
I like realestestate's icon more.

**Comment by west3436** [comment]
Draft until I receive the better sprites from @RealestEstate

**Comment by Eneocho** [comment]
> Draft until I receive the better sprites from @RealestEstate

he literally linked them above
here as a catbox https://files.catbox.moe/eeihem.dmi

**Comment by west3436** [comment]
Sprites and animations updated in OP.

**Pull request merged**
