### PR TITLE
Clean up Unsorted a little

### PR DESCRIPTION
**Pull request by adacovsk**
Unsorted.dm has a lot of bloat

## What this does
- Removes some unused functions in unsorted, replaces a hardcoded list that was rarely used

## Why it's good
Would be good to completely remove unsorted.dm. A step in the right direction.

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Don't know if it's good to remove things just because they aren't used. Having them in the code lets them potentially be useful down the line.

**Comment by adacovsk** [comment]
> Don't know if it's good to remove things just because they aren't used. Having them in the code lets them potentially be useful down the line.

If they need it, will they know it exists or where to find it?

**Comment by Kurfursten** [comment]
He used the R word

**Comment by Kurfursten** [comment]
I have looked over this code and I can certify this is a genuine "emojis have no idea what they're talking about" moment. Having looked over the obscure defines and procs here, I am confident these helpers aren't needed and if they are, they would be trivial to re-implement. Some of them, like anyprob and SAFECRASH are so pointless as to be headscratching. Others, like the mob finding proc, approach things entirely backwards. As I looked down the removed list, the only one that looked useful was create_progressbar_on and then I realized he wasn't even removing that, just moving it to a different file.

There is truly nothing that will be missed in this PR.

**Pull request merged**
