### PR TITLE
Adds food press circuit board + option for blank boards

### PR DESCRIPTION
**Pull request by SonixApache**
:cl:
 + rscadd: The food press now has a circuit board, which you can fashion from blank circuit boards.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Why on the solder list though?

**Comment by SonixApache** [comment]
@Kurfursten the 3 components of it are on the solder list and there's no other way to get the circuit board (aside from spessmart, probbly)

**Comment by Kurfursten** [comment]
What I meant was why not put all the goof kitchen stuff on the circuit printer like most machines instead of an engineering tool?

**Comment by SonixApache** [comment]
¯\_(ツ)_/¯

**Pull request merged**
