### PR TITLE
Fixes #6826, fixes #6969

### LINKED ISSUE #6826: Mann's Drink not a child of soda_can, can't make IED with it
title

### LINKED ISSUE #6969: Can't electrolyze Silicate
I was able to use an Electrolyzer to ghettochem anything I got my hands on, but it wouldn't do anything to a beaker of Silicate. No clue why

### PR DESCRIPTION
**Pull request by 9600bauds**
Why the christ does the electrolyzer have a goddamn huge list of allowed reactions rather than a tiny list of blacklisted reactions?

### CODE REVIEW

**Comment by Kurfursten** [comment]
Because it was new at the time and we didn't know which reactions would be added in the future. So if we did a blacklist it won't catch new ones. But I think it has been in the game long enough that we're feeling safe regarding the power of ghetto chem. Don't make a lazy bandaid fix, just set it so that it can handle all reactions.

**Comment by Kurfursten** [comment]
Also: Groan's Banned Soda comes in a bottle, not a can.

**Comment by 9600bauds** [comment]
I'm not sure what the fuck did I do there for a sec

**Comment by Kurfursten** [comment]
You're seriously not going to remove the whitelist? It needs to go.

Even you complained about it in your comment. Don't complain about it, fix it. It's a really easy fix.

**Comment by 9600bauds** [comment]
To be fully honest I didn't really look at the code to see if the whitelist was necessary or not, I figured it was some hardcode thing like the seed icons, will see about it in a while

**Comment by Kurfursten** [comment]
Just replace the for loop that uses the whitelist with this

for(var/R in typesof(/datum/chemical_reaction/))

**Comment by Kurfursten** [comment]
Delete the list and replace line 1787 with this:

for(var/R in typesof(/datum/chemical_reaction/))

**Comment by 9600bauds** [comment]
That would do it, yeah. You're right, I probably should have read into this fix a little more.

**Comment by 9600bauds** [comment]
I'm going through all the chemical reactions and funnily enough, we have some defined reactions that use chemicals that don't exist. For instance, coffee is made by combining coffeepowder and water... but we don't HAVE coffeepowder. It generates an error, but I don't see any possible issues coming from this

**Comment by Kurfursten** [comment]
Comment out offending recipes if you find them, please.

**Comment by Kurfursten** [comment]
I really hate to be the one to say this because I know how annoying it is to add on another commit after you've just done three in a row, but this could probably use a changelog.

I won't raise hell over it though. These are good fixes. :+1:

**Comment by 9600bauds** [comment]
Whoops it got merged before I could

**Comment by Kurfursten** [comment]
Just add it into the changelog on you next thing

**Comment by 9600bauds** [comment]
I already did :^)

**Pull request merged**
