### PR TITLE
Service borg sneed and feed

### PR DESCRIPTION
**Pull request by jknpj**
:cl:
 * tweak: The service cyborg HUEY and cooking upgrades don't require anomaly tech anymore.

### CODE REVIEW

**Comment by gurfan** [comment]
sneed

**Comment by cloutcode** [comment]
how will traders ever recover, since they're well known for always selling the rare borg upgrades they always get to the many borgs of various modules on the station

**Comment by jknpj** [comment]
They still need gold and plastic, i only made them not require anomaly research. The shitbirds will be fine.

**Comment by cloutcode** [comment]
gold and plastic are easy as hell to get
either way i upboated but was just bringing up a possible complaint while also acknowledging that traders almost never buy borg upgrades and even if they do they're not guaranteed to get the right upgrades for the borgs on station, get science to buy the upgrades and install them since they can make most of them on their own, or even have borgs on station at all. especially service borgs

**Pull request merged**
