### PR TITLE
Welding down shuttle seats now only gives 2 plasteel back down from 5

### LINKED ISSUE #19865: Request: Adjust Shuttle Seats
Requiring 5 plasteel makes them somewhat obnoxious to build if you want to make them, but it also means that arrivals is a treasure trove of usually around 125 plasteel at roundstart to anyone with a welder. Wouldn't it be better for both autism building AND less looting if it was made to 1 sheet instead? (Arrivals would still be worth like 20 plasteel) This is a really small change and easy to PR but I thought I'd put it up for discussion.

@DeityLink

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #19865
:cl:
* tweak: Welding down shuttle seats now only gives 2 plasteel back down from 5.

### CODE REVIEW

**Comment by DeityLink** [comment]
nevermind the floating intercom

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Uhhhhhhhhhhhhhh don't they still need 5 to make

**Comment by DeityLink** [comment]
Yes they do, so you'll waste plasteel if you build then deconstruct them. Fully intended.

**Comment by DeityLink** [comment]
Why not? This change is meant to curb down the powergaming of deconstructing all the seats in arrivals, while not affecting the cost of building one.

**Comment by Dacendeth** [comment]
I really don't like it when materials gained back from deconstruction differ from the cost to construct something, punishes you needlessly for relocating something. Can't you just make the cost to build 2 as well?

**Comment by SonixApache** [comment]
this is 2.5 times as retarded as the chairs themselves

**Comment by ghost** [comment]
The chairs are just cosmetic right? Just make it cost 2 plasteel too which'll help if it's ever made mandatory for some part of it after the player shuttle construction goes through.

**Pull request closed without merging**
