### PR TITLE
Revert TEG power output code all the way...

### PR DESCRIPTION
**Pull request by PJB3005**
Back to how it was in July (pre initial buff).

@ririchiyo was right all along.

### CODE REVIEW

**Comment by Exxion** [comment]
Well don't PING him

**Comment by Probe1** [comment]
nerf, not render obsolete.  it was so bad back then that no one except the inquisitive atmos tech would touch it.  it was made too good.  we all knew it.  but it led people to try it.  make a sane reduction, not a return to the dark days when no one used it because it took much longer to get the same results as other engines (with the added bonus of unreliability and fast burning fuel).

**Comment by ghost** [comment]
Half way it, nerd.

**Comment by PJB3005** [comment]
The old TEG was exactly where it needed to be, I was an ignorant idiot back then.

**Comment by PJB3005** [comment]
@Probe1 the TEG wasn't used back then because it was alien, not because it had output that's not as good as the SME.

The reason my MR on GitLab gave the TEG use is because people thought "oh this thing got made better let's try it!", not because it now produced a shitload of power.

The fixing of the wiki's TEG guide also helped a TON.

**Comment by Iamgoofball** [comment]
so why does power output matter

all that matters is "does it make the bare minimum to power the station"

**Comment by ghost** [comment]
@Iamgoofball go home goofball

**Comment by Iamgoofball** [comment]
serious question tho

**Comment by ghost** [comment]
@Iamgoofball serious reply tho

**Comment by Iamgoofball** [comment]
:joy:

**Comment by 9600bauds** [comment]
Because it lets people cheat at pissing contests

**Comment by PJB3005** [comment]
Goof has a point for once.

**Comment by ghost** [comment]
Yeah, the old power generation reduction was fine before it was buffed and you could make niggawatts with 2 canisters for 4 hours. Once you got the old one figured out you'd still put out 1MW yields in 10 min and could take it further. That people had trouble with it stems from a lack of resources of how to set one up, how it works, and didn't want to put time in to figure it out. People just needed a hand up so they weren't as discouraged and had a better idea of what to improve when they make 200W then jam.

**Comment by PJB3005** [comment]
Alright I finally tested it and I've make sure it works.

**Comment by Probe1** [comment]
The TEG is almost never set up anymore because of jamming and it should be made more responsive instead of nerfed.

It's better than it was currently but this would send it right back to the "Why fucking bother" corner.

Give the TEG some heuristic diagnostics like an error report screen.  The existing UI is confusing and unhelpful.  Nerfing it in its current state would send everyone except bored, personal achievement hunting atmospheric techs back to the place they were before where the TEG was an oldcode engine that no longer fit in modern engineering.

**Comment by PJB3005** [comment]
@Probe1 that's just false.

It jams due to shit setups, if people got their shit together and made good setups we wouldn't have this issue.

**Comment by Probe1** [comment]
@PJB3005 Call it what you want but that won't change reality.  People already find the TEG to be unreliable and replaceable.

**Comment by PJB3005** [comment]
@Probe1 maybe we should fix the setup on the maps and fix the wiki so it's easier to set up then?

**Comment by PJB3005** [comment]
@Probe1 I also want to mention not every engine has to be straight forward.

Look at the R-UST.

**Comment by gbasood** [comment]
@PJB3005 But no one except the biggest autists use the TEG and honestly you could easily get away without using it

**Comment by FudgePucker** [comment]
The main issue with the TEG is the fact that it has minimal output for the amount of work you put in.

Honestly, the whole thing is too fucking complex.

'Oh man I finally finished the set up, oh wait never mind it jams, let me spend the next ten hours solving it'

With the SME the problem is much more simple.
Just keep it cool, really, its not going to fuck up unless you don't keep it cool.

I have done hundreds of SME set ups, hundreds of burn chambers, and hundreds of cold loops, but fuck me I could never get the TEG to work making a new set up.
Doesn't help that praying for the TEG parts as a derelict MoMMI is harder than asking for a shard.

**Comment by MercuryDoll** [comment]
Noone really touches the TEG because barely anyone can figure out how to make it run, it needs quite some setup time and when you thought you finally finished and it looks like it's producing enough power for the shift it jams for no apparent reason and you start at zero. Not even the finest Autismos Techs could comprehend the entirety of it. I'd love to try out all the available engines and even when someone builds a 5 crystal SME i like to tinker with the other available engines, but the TEG is one i never was able to decypher.

**Comment by PJB3005** [comment]
@FudgePucker that's false. Ririchiyo gave me a screenshot of a TW TEG pre buff, and @SarahJohnson489 summed it up perfectly as well.

If the engine's too difficult for you then stop crying, not everything has to be easy.

**Comment by Probe1** [comment]
Yeah it's great right now PJB its just a coincidence that NO ONE CAN MAKE IT WORK and before you buffed it NO ONE WANTED TO.

Now we loop back to the same tired debunked arguments that we should nerf every other engine to make the TEG better by making everything else worse.

**Comment by PJB3005** [comment]
@probe1 I have never seen people argue that the other engines should be nerfes.

When did I say it works right now? Right, I didn't.

**Comment by Kurfursten** [comment]
Just merge this

A nerfed-but-working TEG is better than a broken TEG

**Comment by gbasood** [comment]
happening

**Comment by kol1th** [comment]
maybe it'll WORK now

**Comment by 9600bauds** [comment]
:tada:

**Comment by Intigracy** [comment]
p.s. power production matters for things that rely on power for damage

like shocked doors and shocking yourself on wires and that neat gun and those neat gloves

**Pull request merged**
