### PR TITLE
Decreased chance of security/command to get antag roles from 33% to 20%

### PR DESCRIPTION
**Pull request by DamianX**
I am SICK and TIRED of vampire captains and vampire officers.

:cl:
* tweak: Decreased the chance of security and command personnel to get antag roles.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Might be worth to have a number for each antag type & have it very low for vamp, but less low for autoraitor

**Comment by DamianX** [comment]
when you code it

**Comment by ShiftyRail** [comment]
Ok give me a full night's rest

**Comment by Durgen** [comment]
daynightgif

**Comment by SonixApache** [comment]
command/sec antags should be very rare tbh
it almost always results in extreme shittery

**Comment by ShiftyRail** [comment]
Alternative PR : #21041

**Comment by Intigracy** [comment]
Shifty's does this in a much better way.

**Pull request closed without merging**
