### PR TITLE
Fixed being able to still identify gender of people wearing Vox helmets

### PR DESCRIPTION
**Pull request by DeityLink**
image

### CODE REVIEW

**Comment by DeityLink** [comment]
follow-up to #28219

**Comment by SonixApache** [comment]
vox helmets are literally transparent though

**Comment by DeityLink** [comment]
@SonixApache They seem all very opaque to me, 
image

**Comment by jknpj** [comment]
Why the fuck can you tell the gender of a thing based on their face alone

**Comment by DamianX** [comment]
I guess because female sprites literally have a different face?

**Comment by jknpj** [comment]
>I guess because female sprites literally have a different face?

Not on vox... right?

**Comment by DamianX** [comment]
No, probably not.

**Comment by SonixApache** [comment]
image
kinda the same as hardsuits i guess

**Pull request merged**
