### PR TITLE
comments out changeling rounstart ruleset

### PR DESCRIPTION
**Pull request by SonixApache**
call me when it's not shit

🆑 
 - rscdel: changeling has been removed from rotation pending improvement

### CODE REVIEW

**Comment by ghost** [comment]
Comment out roundstart ops and make them only available from mid/lateround observers and ghosts so you can't meta the manifest.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Needs to also remove latejoin lings

**Comment by SGuivenne** [comment]
@Kyunny that sounds uniquely like an administration issue.  Being shit and metagaming antags based on flagrant things you wouldn't know without being a metagaming shit heel is not allowed.

**Comment by ghost** [comment]
Even if you go out of your way not to act on it you will behave differently even on a subconscious level.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Then we better get right on removing deadchat

Anyways out of scope open an issue

**Comment by TheFriggenSawbones** [comment]
pending improvements (that'll never happen)

**Comment by SonixApache** [comment]
@TheFriggenSawbones WYCI

**Comment by SonixApache** [comment]
this was the 10 000th closed PR, by the way

**Pull request merged**
