### PR TITLE
Logs unknown artifacts & Fixes gas and temp triggered secondary effects never turning off

### LINKED ISSUE #6649: Artifact activation is not logged.
It'd be very useful to know if someone say, flooded the shuttle with plasma with an artifact.

### PR DESCRIPTION
**Pull request by jknpj**
usertouches
primaryo2
secondarydefault

Only logs unknowns for now, already i'm working on replicator, cloner and anomaly battery logs but that's for another PR

Closes #6649

:cl: 
 * bugfix: Gas/Temp triggered secondary artifact effects can be toggled off now

### CODE REVIEW

**Comment by Probe1** [comment]
Does it still spit out a billion logs?

**Review by PJB3005 — APPROVED** [review]

**Comment by jknpj** [comment]
I managed to cut by half so it won't be a problem unless you have someone spamming nongloved bump in a double touch trigger artifact

**Comment by Probe1** [comment]
>Unless someone does what they do.

Put a sleep check on notify_admins.  If its happened in the last 2 seconds, do not notify admins again for another 2 seconds.

**Comment by jknpj** [comment]
Old and busted

**Comment by Probe1** [comment]
What?

**Pull request closed without merging**
