### PR TITLE
Snaxi Vaults

### PR DESCRIPTION
**Pull request by Kurfursten**
Did you know that the outside of Snaxi actually consists of a lot of sub areas, including 4 massive "outer reaches" at the edges?
Did you know each reach is rather enormous, some 10,000 tiles? And most of it is lonely, empty snow.

Presenting vaults to fill the gaps. They're not full of monsters and loot, although there are some things to be had and the occasional creature. Most are flavor. This PR includes 24 vaults to find. Each of the four reaches will spawn 2-4 vaults for a total of 8-16 each shift.

These snow vaults are quite small, and range in size from 3x3 to 15x15. Some are just environmental, some have creatures, and some are a brief reprieve from the storm outside. A few examples

**Bus Stop**
image

**Frozen Pond**
image

**Thermal Plant**
image

**Wolf Cave**
image
Feral wolves will attack you, and are permanently at 250 nutrition. You can still try to tame them as they bite you, but it's riskier.

**Kennel**
image
Pliable wolves won't turn hostile. They remain at 400 nutrition until tamed.

**Hotspring**
image
Capybaras pacify an area like pillbugs.

WIP:
Having a bug with get_turfs() in vault generation
Waiting on Shallows PR to clear

:cl:
* rscadd: There are now vaults to discover on the Snaxi outer reaches.
* rscdel: Converted the old Santa cabin and construction site on Snaxi into random vaults.
* tweak: Wolves won't lose nutrition until tamed, and tamed wolves will lose nutrition much slower.
* rscadd: Feral wolves will always attack, whereas pliable wolves are much easier to tame.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
The creature in the Kennel will be repeatedly killed by wolves

**Comment by Kurfursten** [comment]
I think faction magic should take care of that (but I will check in testing)

**Comment by boy2mantwicethefam** [comment]
Don't wolves get mad if they're hungry

**Comment by Kurfursten** [comment]
I'm refactoring wolves as part of this PR so that wolves only starve if they are tamed wolves, and also reducing the rate of starvation overall, and also splitting them into two types. None of this is committed yet, but there will be a several mob additions for this PR (including capybaras). I guess I ought to put up a WIP tag.

**Comment by SonixApache** [comment]
capybaras...

**Pull request merged**
