### PR TITLE
Uploading laws now need both target silicon and console to be on the same z-level

### PR DESCRIPTION
**Pull request by jknpj**
What says on the tin. law.dm is a fucking huge mess of badcode and i didn't want to include any big refactor in this PR but i still removed the relative pathing so i guess @DamianX is still going to yell at me.

:cl:
 * tweak: Uploading laws now need both target silicon and console to be on the same z-level

### CODE REVIEW

**Comment by Probe1** [comment]
Github needs a 👌 reaction.

**Comment by FudgePucker** [comment]
What do you mean I can't print an ai upload board and set it up on the research outpost?

:+1:

**Comment by Ephx1** [comment]
I can't actually remember the last time someone did that, since maint is fairly expansive enough on most maps to make it ridiculously easy to hide away a console. I have no complaints about this PR, though.

**Comment by DamianX** [comment]
image

**Comment by Aurx** [comment]
Anyone who really wanted to not be found would set up a space-base anyways.  This just forces them to go all or nothing.

**Comment by Diavill** [comment]
what about the law upload on centcomm for admemes

**Comment by Aurx** [comment]
Admins can just dick with the laws through the player panel, through varedit, or spawn an upload in the ass-most end of Z1.  
I don't think I've ever seen the cent upload used, anyways.

**Comment by chesse20** [comment]
what about the 2 z level ice map thats being worked on. What if a borg is on a different floor of the station than the console

**Comment by Pathid** [comment]
I'd say make an exception if the console's on Z2, but that would end up including transit space, wouldn't it?

**Comment by ghost** [comment]
wait, does that mean that telescience rogue AIs will be unable to be reset?

**Comment by DamianX** [comment]
While this makes subverting harder it also makes un-subverting harder. Not sure how I feel about this.

**Comment by Pathid** [comment]
Not an elegant solution IMO, but we could have consoles on either Z1 or the upload room be special, and able to reach other levels.

**Comment by Aurx** [comment]
The elegant thing to do would be to assign each Z a "priority" and check that the console and AI share a Z or the console's Z has a priority greater than the AI's turf's Z's priority.  
IE, a console on cent could upload to any AI, a console on the station could upload to any AI not on cent, and a console anywhere else would be limited to its Z.

**Comment by Caboozles** [comment]
Well, this creates a mild issue with the idea of "Spacebound" AI.

For example, an AI hanging out on the DJ station suddenly is immune, making it go from a simple fun concept to a huge defense against subversion.

Also, another even more dangerous idea is the concept of teleporting the AI to random coordinates on the derelict/MoMMi nest. As long as there's power, there is exactly no way for the crew to return the AI if subverted somehow. AIs have _full_ station control on other Z-levels. All this does is encourage removing the AI from the z-level.

**Comment by jknpj** [comment]
Is it time to make use of atoms_share_level and make silicons unable to interact with other Z-levels?

**Comment by Probe1** [comment]
I'd be concerned if that ever happened but I've never seen a DJ Station Traitor AI.  And MALF would lose if it tried that.

**Comment by Caboozles** [comment]
I don't think it's a thing for tator/Malf. Tator/Malf don't care about laws to begin with, and unless someone is generous enough to give you the coords, you're better off just being "stealthy".
I'm talking subversion. 

As it stands, you won't ever see anyone move a subverted AI, because there's no benefit to it.
But if I were to subvert the AI during a cult round, and load it onto the trader shuttle, or god help us the salvage shuttle, which I am 99% sure has power by testing it on the test server, you do not have a physical way to track the AI. As such, you can subvert it, move it, and nobody on station has a chance of even FINDING the z-level the AI, unless you stumble across it by pure luck, or build 4 consoles on 4 z-levels in an attempt to track it down.
AI still have full control over system power.

Either make the solution just be you can only do it on z-level 1, or add a way to track where an AI is at all times, so that if an AI does go into hiding (And I have seen a tator AI hide in the research outpost) you can at least know what level it's on and attempt to return them to normal

**Comment by jknpj** [comment]
of course you JUST need the salvage shuttle for that

**Comment by jknpj** [comment]
Theorycrafting wins

**Comment by Probe1** [comment]
Wait why?

**Comment by Aurx** [comment]
The concept is sound man, you can fix the issue that's been discussed.

**Comment by Caboozles** [comment]
Just throw a way to know what Z-level the AI is on. Maybe not a GPS tracking as to not ruin some fun malf/tator gimmicks, but something as easy as knowing what Z-level the AI is at all times would totally be a fix to that issue.

My only concern is that without any method of knowing where the AI is, there's no way to return it to "normal"

**Comment by Aurx** [comment]
That's a good way of handling it, but what device would do that?  
I outlined another possibility above, which I think is better at conserving the function of the existing uploads.

**Comment by jknpj** [comment]
Alright time to find a way

**Comment by Aurx** [comment]
Either of the ways proposed so far should work.  
Caboozles proposed adding a way to tell what Z an AI is on.  Upshot is that it means an off-Z AI has a degree of protection from laws, downside is that it makes hiding off-Z harder for AIs.  
My suggestion was to assign each Z a priority, and check (console.z.priority > AI.z.priority || console.z == AI.Z).  Upshot is that it keeps the centcomm and station uploads working 24/7 while blocking the research station uploads, downside is that we can't actually do z.priority so we'd have to have a somewhat awkward workaround.  It'd also half-break on a two-z station without further refinement.

**Comment by Intigracy** [comment]
How's this unatomic?

**Comment by Probe1** [comment]
I assumed he just tagged lotta stuff

**Comment by jknpj** [comment]
I'll just leave this for the next generation to salvage if they want to fix upload shitcode.

**Comment by Aurx** [comment]
Not formatted correctly and likely missing runtime checks, but here, I did it for you.  

Replace the same level check with
```upload_z_compatible(AI a, console c) {
    if(a.z == c.z)
        return TRUE;
    if(get_z_priority(c.z) > get_z_priority(a.z))
        return TRUE;
    return FALSE;
}
```

Add
```
get_z_priority(int z) {
    if(z == STATIONZ)
        return 1;
    if(z == CENTCOMMZ)
        return 2;
    return 0;
}
```

**Comment by Aurx** [comment]
Oh, and it's in some bastard version of C that lacks return types, but you can fix that.

**Pull request closed without merging**
