### PR TITLE
Delicious Pie

### PR DESCRIPTION
**Pull request by Kurfursten**
- Tweak: All pies are now children of pie, which makes them throwable
- Content: New trash item for pies. Instead of plates, they produce pie tins.
- Tweak: Throwing a pie generates a pie tin
- Content: Putting two pie tins together makes a tinfoil hat
- Content: Tinfoil hat: blocks the HUD (but not the examine features) of the SecHUD, blocks teleportation, and blocks mind_affecting powers when worn
- Tweak: Re-examined the code of some powers and spells. Now targeted.dm has var/mind_affecting which uses the old human/proc/can_mind_interact. The implication of this is a greater defense provided by PSY_RESIST and now tinfoil hats.
- Tweak: Made the fail text on can_mind_interact more descriptive
- Tweak: Added mind_affecting = 1 to remoteview, empath (mind read), project_mind, and mindswap
- Content: Discount Dan pies! Cheap comedy humor available at your neighborhood vendor. Just don't eat it.

### CODE REVIEW

**Comment by PJB3005** [comment]
What is it with @Kurfursten and self tagging PRs?

**Comment by Kurfursten** [comment]
I saw someone else do it and thought it looked like a good habit, @PJB3005

**Comment by PJB3005** [comment]
Yeah but a lot of times the maintainers just end up removing the self tag from the title so I don't really see the point

**Comment by Kurfursten** [comment]
I remove it myself once they put a real tag on there (if they don't, which they usually do)

It's just to help visibility until a maintainer has a chance to tag it

**Comment by Intigracy** [comment]
You should make it block all huds instead of just sechud, so there's a drawback to it.

**Comment by Kurfursten** [comment]
@Intigracy For clarity, by "all HUDs", you mean "also medical", right? I'm just asking in case there's one I'm forgetting.

I like the idea of it blocking all HUDs now that I consider it, but of course the main downside is opportunity cost (e.g.: no hardsuits, no helmets, no headlamps, can't look stylin', etc.)

**Comment by Intigracy** [comment]
Yeah.

**Comment by ComicIronic** [comment]
Tinfoil hats: the new powergamer item.

**Comment by FudgePucker** [comment]
Does it also prevent beepsky from arresting you if you are set to arrest?
It is going to be funny to poison any pies that assistants request for tinfoil hats to powergamin.
'Oh want to griff sec? Here, have 50 units of toxins asshole, enjoy eating my hard work in one bite.'

**Comment by Kurfursten** [comment]
@FudgePucker It does not have any impact on Beepsky or arrest records. This solely makes it so that officers don't IMMEDIATELY notice your job/implants/arrest status. They can still see your job/arrest status by examining you.

**Comment by FudgePucker** [comment]
@Kurfursten 
Ah then it isn't OP at all.
Can't wait for clown gimmicks involving beliving everyone is out to get them wearing a tinfoil hat and screaming about goverment coverups.
Good job :+1:

**Comment by ComicIronic** [comment]
>Ah then it isn't OP at all.

It still blocks teleportation, wizard spells, and mind powers!
There's no reason to not always be wearing one or having one in your inventory, especially since Security isn't going to be able to take them off a station full of people wearing them.

**Comment by Kurfursten** [comment]
Only one wizard spell, mind swap.

**Comment by FudgePucker** [comment]
>Teleportation

Okay that might be a little overboard, but it only screws telescientists over really, and don't scientists already have it too easy as antags? 'Oh no I can't teleport this one person. Oh wait I forgot I had 6 bombs ready to go blow up the station.'
>Mind powers

Fitting because those grays want to send you subliminal messages. (FUCK GENENETICS)
>Wizard spell(s)

It doesn't block the only spell that matters.
I will give you a hint.
Its EI NATH.
:^)

**Comment by Kurfursten** [comment]
Incidentally you can also "block" teleportation by turning off your suit sensors and not carrying a GPS. This is more of a downside, because it means you can't be rescued with telescience.

There are probably rare circumstances where you want your suit sensors on but are afraid of being yanked by a telescientist and murdered... but those are so rare, you'd have to be a tinfoil hat wearer to worry-- oh.

**Comment by FudgePucker** [comment]
@Kurfursten 
YOU SEE ITS PERFECT.
All the powergamers who would look like crazys in real life will now run around with tinfoil hats.
'Why are you wearing a tin foil hat' 'SECURITY AND THE SCIENTISTS ARE AFTER ME, GRAYS DID 9/11'

**Comment by Exxion** [comment]
Does the hat also prevent the wearer from using the blocked abilities?

**Comment by PJB3005** [comment]
It should if it doesn't IMO.

**Comment by Exxion** [comment]
It definitely should.
After a quick look at the code, I don't think it does, but I could have missed something.

**Comment by Kurfursten** [comment]
Not in the current state, I can do that though.

**Comment by Kurfursten** [comment]
You can no longer cast mind_affecting spells or powers with a tinfoil hat on, and it also blocks health HUD -- both as requested

Fully tested, please move to NFD

**Comment by d3athrow** [comment]
ATOMIC
PULL
REQUESTS

**Pull request merged**
