### PR TITLE
Adds the Donut Burger

### PR DESCRIPTION
**Pull request by PrimeDSS13**
Has science gone too far?

image
This PR adds the donut burger, made from two donuts and one piece of normal meat. Whether sprinkled or non-sprinkled donuts are used does not affect the result. 
It contains nutriments and sprinkles, and is quite filling.

I am uncertain on where I got the sprite from, but I thank whoever created it. If you wish for credit or for me to change the sprite feel free to reach out. 

:cl:
 * rscadd: Added the donut burger, for the hungry security man.

### CODE REVIEW

**Comment by gurfan** [comment]
absolutely disgusting

**Comment by SysadminJeroen** [comment]
This is an abomination.

**Comment by Viciousaurus** [comment]
Does it heal secmen?

**Comment by Theophrastus1** [comment]
now add the GUNKburger

**Comment by PrimeDSS13** [comment]
> 
> 
> Does it heal secmen?

Since it contains sprinkles, it applies the same healing effect as donuts and other sprinkle-containing items. It also fills security up more because of it.

**Comment by DeityLink** [comment]
Which leads me to realize that we don't have bagels in the game!

**Comment by Theophrastus1** [comment]
> 
> 
> Which leads me to realize that we don't have bagels in the game!

Bagelstation duh

**Review by Zth-- — APPROVED** [review]
will merge after you update the wiki

**Comment by PrimeDSS13** [comment]
oh god oh fuck

**Comment by Kurfursten** [comment]
wiki is updated but conflicts

**Comment by PrimeDSS13** [comment]
gonna open a new PR for this soon since I can't be assed to fuck around with it

**Comment by Kurfursten** [comment]
Or just learn how to fix conflicts

**Comment by Zth--** [comment]
I removed the entry from the wiki. Feel free to reopen when (if) you fix the conflicts

**Pull request closed without merging**
