### PR TITLE
Allows people to communicate with each other via holopad

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
image
image
image
image
image
image
image
adds this as another option on top of requesting an AI presence
when used, projects you onto a target holopad of choice in the same area of space

## Why it's good
another method of department communication

## How it was tested
using them as an AI, and then as a person

## Changelog
:cl:
 * rscadd: AI holopads are now general holopads, allowing anyone to broadcast a hologram of themselves to another target holopad if used as such, and someone on the other end accepts the call. They can still be used to request the presence of an AI as an option as normal too. The "set holocolor" right click verb or alt clicking as a humanoid player can change the color of the projected hologram. Cannot be used by humans while an AI is using it, and AI usage overrides any human usage.
 * tweak: The "show item" verb now displays "you" instead of their name to the player using it.

### CODE REVIEW

**Comment by west3436** [comment]
On one hand I really like this feature in shiptest

On the other hand this is a telephone nerf

**Comment by SECBATON-GRIFFON** [comment]
> On one hand I really like this feature in shiptest
> 
> On the other hand this is a telephone nerf

i'm conflicted too. i started this feature in august 2023. did we even have telephones then?
actually, telephones could still be useful for anonymous calls if you somehow don't have a disguise on you while masking your voice. niche but still

**Comment by angryturnip** [comment]
What happens if an AI uses the holopad while someone is receiving a transmission from someone else? Are there two holograms or are they prevented from using that holopad? And visa versa

**Comment by SECBATON-GRIFFON** [comment]
> What happens if an AI uses the holopad while someone is receiving a transmission from someone else? Are there two holograms or are they prevented from using that holopad? And visa versa

AIs, codewise, would be prevented from using this while someone else is. now made it so people can't use it while an AI is using it

**Comment by angryturnip** [comment]
I feel like AIs should get priority on it to override the non-silicons transmitting, personally. Considering it's originally meant for them

**Comment by SECBATON-GRIFFON** [comment]
> I feel like AIs should get priority on it to override the non-silicons transmitting, personally. Considering it's originally meant for them

good point but it's funny to be able to turn them off

**Comment by west3436** [comment]
> > On one hand I really like this feature in shiptest
> > On the other hand this is a telephone nerf
> 
> i'm conflicted too. i started this feature in august 2023. did we even have telephones then? actually, telephones could still be useful for anonymous calls if you somehow don't have a disguise on you while masking your voice. niche but still

I think an approach here could be requiring upgraded parts to allow more than just AIs to use the pad. That way we have a default p2p comms tool (telephones) then with upgrades you can have p2p holographic comms. Bonus points if you make this work across z levels with top-tier parts.

**Comment by SonixApache** [comment]
cool
but why

also post a video of both sides of this

**Comment by SECBATON-GRIFFON** [comment]
> I feel like AIs should get priority on it to override the non-silicons transmitting, personally. Considering it's originally meant for them

made it so now

**Comment by west3436** [comment]
@SECBATON-GRIFFON please make this request-based so holograms can only appear on a given pad if a request has been made from one pad to another. Transmitting to any pad without requesting just makes this a better security camera.

**Comment by SECBATON-GRIFFON** [comment]
> @SECBATON-GRIFFON please make this request-based so holograms can only appear on a given pad if a request has been made from one pad to another. Transmitting to any pad without requesting just makes this a better security camera.

uh, you don't really see the other end when you do this, just hear. which probably makes it a better telephone, but with the downside being that people fully see your character sprite. that being said the request thing still feels like a good idea. i'll see what i can do

**Comment by hacker-on-steroids** [comment]
>hologram has clothes

!!!
can your ID be stolen remotely with this?

**Comment by SECBATON-GRIFFON** [comment]
> > hologram has clothes
> 
> !!! can your ID be stolen remotely with this?

no, it just copies your sprite as a flat icon. there might be better ways to do this but point is nothing can interact with the hologram itself

**Comment by wotisjanitor** [comment]
Security cameras for everyone!

**Comment by SECBATON-GRIFFON** [comment]
request system added now @west3436

**Comment by PrimeDSS13** [comment]
redundant/makes phones irrelevant and kinda confusing tbh, I like the idea of people using holopads vaguely though

**Comment by west3436** [comment]
Reception is mixed on this one and I fear this is going to result in Unforeseen Consequences. We may come back to this one later but for now I'm gonna close it.

**Comment by SonixApache** [comment]
re-open this you coward

**Comment by SECBATON-GRIFFON** [comment]
STOP THE COUNT

**Comment by wotisjanitor** [comment]
5 vs 3

**Pull request closed without merging**
