### PR TITLE
Malf Announcement Falsifier Tweaks: Custom Announcements + Fake Faction Music

### PR DESCRIPTION
**Pull request by gurfan**
The fake announcement module for Malfunctioning AIs has been improved. 
Like before, the module costs 15 points and has three uses per purchase.

Upon use, the AI can choose from a list of pre-existing announcements (like before) OR they can create their own custom announcement. The custom announcement function works identically to the report falsifier purchasable from the syndicate uplink.

Pre-Existing announcements that have gamer music associated with them will have their respective music played when chosen. Music is normally handled within faction code so the playlist for each announcement needs to be set manually. The current announcements that will trigger music when faked are:

Revolution Detected
Malf AI Delta (why would you pick this?)
Supermatter Cascade
Meteor Round
Jungle Fever
Cult - Bloodstones Raised
Cult - Bloodstone Anchor Detected
Nuclear Operatives
Blob - Nuke Authorized

In addition, the following announcements will stop any thematic music:

Blob - Quarantine Lifted
Revolution Toppled
Malf AI Destroyed
Jungle Fever Contained
Cult Defeated

In addition, Cult/Revs/Ops/Malf announcements will trigger their respective alert levels when announced as active/defeated. 

If the AI has gone delta, the delta music cannot be stopped or replaced using the announcement module and the alert level cannot be changed.

:cl:
 * rscadd: Malfunctioning AIs can now send custom falsified announcements.
 * rscadd: Malfunctioning AIs that fake pre-existing announcements will cause the announcement's respective music to play or stop, so long as the AI hasn't started their takeover yet.

### CODE REVIEW

**Comment by Kurfursten** [comment]
The monkey endgame announcement on this list sends a real nuke code.

**Comment by gurfan** [comment]
feature

**Comment by DeityLink** [comment]
add "the emergency shuttle has docked with the station" and "the timer has been reduced to 10 seconds" these always get me hard when I'm hallucinating.

**Comment by beesil** [comment]
I predict the meta easy win strategy becoming using the cult announcement to raise to code red then having your borgs switch to combat module.

**Comment by Kurfursten** [comment]
I really don't like the implementation of this because it is bad maintainability. What you're doing here is just mimicking the behavior found in the stage() code. Which means if stages get adjusted, this won't match anymore. This is kind of awkward as-is, but I guess it works.

**Pull request merged**
