### PR TITLE
Small fixes to Box Outpost

### LINKED ISSUE #10713: Box trade outpost too big for skipjack to dock
#### Description of issue

The docking on the Box trade outpost intended for the vox skipjack (and salvage shuttle?) goes one tile too far down. The issue in that round was settled when the skipjack's destroy_everything was set to 1
skipjack 2fat
#### Difference between expected and actual behavior

The shuttle is unable to dock without destroy_everything = 1. Instead, it remains in the "hyperspace" area until sent to an area it can dock at.
#### Steps to reproduce

Get to the Vox Skipjack
Attempt to send it to the "Vox trading outpost" destination
#### Server revision

c680e4fb1d6856c014105f3afddc38064125e916
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) (Searched for all issues, open or close, with the word "skipjack" and "trader outpost")

### LINKED ISSUE #10729: No Minihoe on Box Outpost (Additional Dylan Regrets)
In addition to #10719 and #10713 there is no longer a mini hoe on the outpost making it impossible to remove weeds.

Thanks @dylanstrategie

### PR DESCRIPTION
**Pull request by ghost**
Here's the fixes you wanted : 

Fixes #10729 : 
- Changed Botany crate to a Botany locker with general access in Box Outpost, should have all the tools instead of some half-assed bundle
- Added eight crates, four in the Armory (replaces racks) and four in the large Trading Floor (bottom, centered). Should be more than enough for trading needs.

Fixes #10713 : 
- Expanded trade dock by one tile to account for the xboxhueg Vox Raiders Shuttle

Simple fixes, completely explicit. I'll work on the Outpost more in-depth with actual changes in the N E A R     F U T U R E

### CODE REVIEW

**Comment by Kurfursten** [comment]
The wiki could stand for some updating in regards to the changes you've made to Box outpost

http://ss13.moe/wiki/index.php/Trader#Vox_Outpost

**Comment by ghost** [comment]
Indeed, but I'm not 100 % forced to do it. I will look into it if I find some extra spare time

**Comment by ComicIronic** [comment]
Images

**Comment by ghost** [comment]
What for, I told you the changes
- Four racks turned into four crates
- Four extra crates in four squares on the bottom middle of the Trade Floor
- Shuttle dock hallway expanded one tile outwards
- Changed the half-filled Botany crate into an all-access closet

**Comment by ghost** [comment]
a_fucking_crate

**Comment by ihadtoregisterforthis** [comment]
Move the chicken to the oxygenated area for the time being.

**Comment by ghost** [comment]
No urgent need, Colonel Gravy is just going to be a goner until someone fixes him

**Comment by ihadtoregisterforthis** [comment]
So, either move it where it won't die, or remove it

**Comment by Kurfursten** [comment]
Changing the atmos requirements on a simple mob is trivially easy. So easy that I'm willing to do it for you if we can come to a consensus on what Vox chickens should breathe.

Because it seems kind of shitty to say "only nitrogen" because that means if you monkeyfy a Vox on the main station they are doomed to death in the next 20 seconds which seems to defeat the point of monkeyfying them. Maybe just remove the minimum oxygen and require only a minimum N2 but no maximum O2?

**Comment by ghost** [comment]
Well, Vox monkeys are supposed to come from Vox, so they should really just keep their 100 % N2 preference

**Comment by Kurfursten** [comment]
Are we all on board with that? Maybe @Probe1 could do a poll or something, since it seems to affect a lot of people

I don't have strong opinions myself, I am just wary to change it unilaterally

**Comment by Shadowmech88** [comment]
Can vox chickens wear a mask and nitrogen tank? Because if not, then oxygen toxicity would make being a vox chicken on the station a guaranteed death sentence.

**Comment by Kurfursten** [comment]
Since they're children of monkeys who can wear a mask, I would say yes, but they would likely only be able to use human masks (not vox masks) and like monkeys, it's a big hassle because you have to dedicate one hand permanently to carrying the tank (and the other to your ID if you have one)

**Comment by ghost** [comment]
Here's the think with vox chickens - They can't use hands at all because they kinda lack arms, so somebody would have to give them a tank and mask.

I suggest going for inbetween, that they can survive a basic air atmosphere, and a full nitrogen atmosphere, if that's possible.

Also, to get around the 'can't use hands' problem, could have it so they have a single 'hand' slot that they can use when they're dosed on methylin, and the 'hand' is their beak.

**Comment by Kurfursten** [comment]
Yes, it is simple to manipulate the atmos requirements in that way

As for hand slot stuff, ask @unid15

**Comment by unid15** [comment]
Are vox chickens simple animals or monkeys?

**Comment by Kurfursten** [comment]
Monkeys

see monkey/vox.dm

**Comment by carshalash** [comment]
So nearly a week later and all of the trader botany stuff is still useless. Cheers

**Comment by ghost** [comment]
There apparently isn't a hoe or a hatchet on the box outpost, had some vox come in and trade me a jetpack for my hoe, only to realize there isn't a spare on the research outpost either.

**Comment by PJB3005** [comment]
You still need to fix the outposts on the other maps...

**Comment by Kurfursten** [comment]
All of the outposts are a little different, there is just a little consistency between them. All of the others have their botany tools though, as far as I know

**Comment by PJB3005** [comment]
So what? He's adding things to the Box Vox outpost that the others should have too, but they don't get it (looking at the crates).

Shit like this is why people hate other maps.

**Comment by Kurfursten** [comment]
Don't deff and bus already have crates?

And meta is literally a wreckage site

**Comment by Kurfursten** [comment]
Why isn't this merged?

**Comment by ComicIronic** [comment]
Because nobody has merged it yet.
What kind of question is that?

**Comment by Kurfursten** [comment]
I figured there was some unspoken holdup

If there isn't, will you?

**Comment by ComicIronic** [comment]
Now that #10848 is merged, maybe.

**Pull request merged**
