### PR TITLE
starting the crusade against relative pathing

### PR DESCRIPTION
**Pull request by PaulRitter**
[qol]

i am mad cause i cant fucking find procs so here i go removing relative pathing one file at a time

all i am doing is searching for cases using regex, redoing them by hands and searching the file for other cases not caught (mainly overrides, those are hard to find) while im at it

what i already did
- search for all relative New() using `\tNew\(`
- search for very fucked procs with `\tproc\n`, `^proc\n`
- search for relative pathed vars with `\tvar\n`, `^var\n`
- whereever i found any of this, i went though the file and fixed all occurences of relative pathing

what i searched but yielded low/no results
- `\natom\n`, `^atom\n`
- `\nobj\n`, `^obj\n`
- `\ndatum\n`, `^datum\n`

DEUS VULT

PS: if you think this isn't needed, take a look 
image

:cl:
 * experiment: removed alot of relative pathing, report any strange behavior

### CODE REVIEW

**Comment by brndd** [comment]
You won't find space-indented relative pathing with that, right? Might want to use `\s+proc/` etc.

You might also want to look for relative pathing by a regex that matches all definitions where the line *doesn't* start with one of Byond's types (`var/`, `/obj/`, `/datum/`, etc.) but still holds a definition (ends in a forward slash or a close parenthesis, or something; this might be hard to define).

**Comment by PaulRitter** [comment]
it is literally impossible to define cause things sometimes look like this

`obj`
`.........test`
`...................var/abc`

thats why >removed almost all of relative pathing

**Comment by Kurfursten** [comment]
Is this a WIP?

**Comment by ShiftyRail** [comment]
>did not do sprite_accessories.dm yet

This might be the one file in which relative pathing is actually useful imo

**Comment by PaulRitter** [comment]
no longer wip

**Comment by PaulRitter** [comment]
~also the conflicts were resolved in my latest commit, but i don't know how to set the conflict to be resolved.~ nvm found it out

the conflict was triggered by someone updating flavourtext for drinks after i merged upstream

**Pull request merged**
