### PR TITLE
Refactored holodeck code

### PR DESCRIPTION
**Pull request by DamianX**
just boring refactoring, functionally equivalent, nothing to see here

### CODE REVIEW

**Comment by Kurfursten** [comment]
May I suggest gold medal in a display case instead of a captain's locker?

**Comment by DamianX** [comment]
It's all placeholders. And I assume you mean "captain's ID" because I don't think I've messed with any captain's lockers in this

**Comment by SonixApache** [comment]
did you happen to fix / re-add the space and library decks

**Comment by Kurfursten** [comment]
My bad, it was on Olympic Station centcom, not on main station.

**Comment by Eneocho** [comment]
Can you give the holomen an internal radio so they can talk to the crew? Also possibly the option to interact with the holoroom console.
inb4 out of scope

**Comment by Kurfursten** [comment]
You're definitely right, that is out of scope

**Pull request merged**
