### PR TITLE
Fixes Box Cloner board not being a machine circuit board

### LINKED ISSUE #11091: Box cloner needs a computer frame instead of a machine frame
(WEB REPORT BY: justsumguy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2e470598b259fb4d1576c1b9f99068ace1139f54
> 
> General description of the issue
> Trying to make a box cloner with a machine frame causes it to reject the circuit, instead you make it with a computer frame
> 
> What you expected to happen
> frame_desc = "Requires 1 Matter Bin and 2 Capacitors   "
> 
> What actually happened
> "The machine frame rejects boards of this type"
> 
> Steps to reproduce if possible
> Try to build a box cloner

### PR DESCRIPTION
**Pull request by JustSumBody**
closes #11091
I thought this would take longer so I put up an issue but I forgot I am a ONE LINE WONDER
Tested exhaustively

### CODE REVIEW

**Comment by kol1th** [comment]
:100: % tested?

**Comment by ComicIronic** [comment]
Check if there's a define for that. It should be a define.

**Comment by JustSumBody** [comment]
Not sure there is one unless I'm missing it, nothing in that file uses it at least
Should I change that as well?
How exactly would I change that?

**Comment by Intigracy** [comment]
#define MACHINE "machine"
then replace every usage of machine with MACHINE

**Comment by JustSumBody** [comment]
I'm also just now realizing "box cloner" could be confused with "the cloner on box station" especially since I don't think most people know the pig exists

**Pull request merged**
