### PR TITLE
Allows mini hoes to be put on labcoat suit storage

### PR DESCRIPTION
**Pull request by RFultra**
Allows mini hoes to be put on labcoat suit storage

minor xenobotany buff

### CODE REVIEW

**Comment by CptWad** [comment]
Uh 
The changes lack anything to do with miniholes.
Approve the mini-hoe however.

**Comment by CptWad** [comment]
>cant edit on moblie

REEE

I mean labcoats. Nothing to do with coats

**Comment by Exxion** [comment]
What are you talking about

**Comment by RFultra** [comment]
w-what

**Comment by CptWad** [comment]
Im having a bad day

**Comment by RFultra** [comment]
wanna talk about it?

**Comment by CptWad** [comment]
Yeah i just made an idiot of myself on the github of an autistic apaceman simulator.

**Comment by RFultra** [comment]
it's okay, I did that too

**Comment by SonixApache** [comment]
make avada do it himself

**Comment by Commandersand** [comment]
>himself

Avada is a girl(male)!

**Pull request merged**
