### PR TITLE
Update assistant jumpsuit to match their colors

### PR DESCRIPTION
**Pull request by toomykins**
i've never actually written DM-code before and I haven't tested this so it might just not work i dunno i tried

:cl:
 * rscadd: i think assistants that can speak gutter now spawn with a brown jumpsuit instead of a grey one
 * rscdel: literally nothing

will most definitely not crash the server if applied
pls unban me

### CODE REVIEW

**Comment by Arthurdentist** [comment]
for what purpose

**Comment by Orangerush** [comment]
> for what purpose

He wants to continue the legacy of brown shirt gutter speakers 🦅 🎆 🍔 🔫

**Comment by toomykins** [comment]
fun

**Comment by yclatious** [comment]
Id like to point out that Travis doesnt even compile. Not only is toomy a memelord shitter but he cant even make a PR with a basic if statement and have it be accepted.

Wew lads.

**Comment by toomykins** [comment]
hey you try making a functional if statement then this is like my first try

**Comment by SonixApache** [comment]
get_out

**Comment by toomykins** [comment]
all these downthumbs when really, nobody has any arguments against the need for instant brown jumpsuits for gutters.

**Comment by yclatious** [comment]
This pr is much like your life Toomy. A joke.

You never explain a joke, it stops being funny. Stop asking us to explain why this is funny.

**Comment by Exxion** [comment]
MoMMI doesn't do this automatically anymore so I'll do it manually:

>reacting to your own PR

**Comment by ShiftyRail** [comment]
A profound statement

**Pull request closed without merging**
