### PR TITLE
binary is no longer so big

### LINKED ISSUE #9538: That Robotic Talk font is god-awful, FIX IT
I don't know who put their hands on it, but please change it back

It just looks awful. Just use TT and call it a day, or don't use any special font at all

### PR DESCRIPTION
**Pull request by Intigracy**
What don't you like vote:

closes #9538

### CODE REVIEW

**Comment by 9600bauds** [comment]
rigged poll needs meme option

**Comment by Intigracy** [comment]
meme option is last option

**Comment by 9600bauds** [comment]
more meme

**Comment by xpcybic** [comment]
**Weighted Vote Result: I like it with 1 vote**

**Comment by Gringonius** [comment]
Any plans to stop using the ugly as sin font either?
Regards, that one vote.

**Comment by NigglyWiggly** [comment]
<sub>01010111 01101000 01100101 01101110 00100000 01100001 01110010 01100101 00100000 01110111 01100101 00100000 01100111 01101111 01101001 01101110 01100111 00100000 01110100 01101111 00100000 01101010 01110101 01110011 01110100 00100000 01100011 01101111 01101110 01110110 01100101 01110010 01110100 00100000 01100010 01101001 01101110 01100001 01110010 01111001 00100000 01110100 01101111 00100000 01100001 01100011 01110100 01110101 01100001 01101100 01101100 01111001 00100000 01100010 01100101 00100000 01101001 01101110 00100000 01100010 01101001 01101110 01100001 01110010 01111001 00111111

**Comment by Intigracy** [comment]
01010111 01101000 01100101 01101110 00100000 01111001 01101111 01110101 00100000 01100011 01101111 01100100 01100101 00100000 01101001 01110100

before there were no complaints,
now there is a surge;
please just click the button,
the one that says merge.

**Pull request merged**
