### PR TITLE
Role datums

### PR DESCRIPTION
**Pull request by MadmanMartian**
Let's see what the damage is.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
The damage is quite extensive it seems.

Oh dear

**Comment by MadmanMartian** [comment]
thanks IconDiffBot

**Comment by DeityLink** [comment]
good lord

**Comment by DeityLink** [comment]
From now on and until the end of the feature, we gotta do a merge every months at least. Then again it could take a month to fix all that.

**Comment by DeityLink** [comment]
>	MadmanMartian  wants to merge 52 commits into Bleeding-Edge from role_datums

Wait hold on nigga what are you doing?

**Comment by SysadminJeroen** [comment]
I might be wrong with this, but did you try rebasing the code on  `Bleeding-Edge`?

**Comment by PJB3005** [comment]
Good job you broke it by using a squash merged PR to update a branch.

Hard reset the branch back to BEFORE #17383 and just run `git merge upstream/Bleeding-Edge` like a sane person jeez.

**Comment by SysadminJeroen** [comment]
RIP antag datums you were delicious.

**Pull request closed without merging**
