### PR TITLE
Plasma beaker cost reduction

### PR DESCRIPTION
**Pull request by iFlashYou**
Lowered the plasma cost for the plasma beakers because 12000 plasma was a bit too much and to get back familiar with git.

:cl:
 * Reduced the plasma cost of plasma beakers to 8000 from 12000

### CODE REVIEW

**Comment by Irradiation** [comment]
Nice sc*ence buff, nerd.

**Comment by ShiftyRail** [comment]
Effectively this doesn't change much, and this might make medbay see these more often, so +1

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Not like medbay even wants them so whatever

**Comment by Irradiation** [comment]
It's a classic case of "By the time that science can provide better beakers or whatever, chemistry doesn't need them anymore".

**Comment by iFlashYou** [comment]
The only way to fix this would be to have bluespace beakers and plasma beakers roundstart in chemistry.

**Pull request merged**
