### PR TITLE
remove_from_storage return value fixes

### LINKED ISSUE #17022: Chewing gum is completely impossible to remove from the box
Not even clickdragging the box into a table works.
Only happens with chewing gum. Started happening very recently.

### LINKED ISSUE #17023: Can't remove lighter from the cigarette pack/cigarettes are invisible in the hand
#### Description of issue

The lighter is stuck in the cigarette pack

#### Steps to reproduce 

1. buy a cigarette pack and a lighter
2. take a cigarette out, it can't be seen in your hand
3. Put it in your mouth
4. Light it
5. Put lighter in cigarette pack
6. cry as you can never remove it again, even doubleclicking the cigarette pack just empties all the cigarettes but not the lighter

#### Length of time in which bug has been known to occur

Must have become broken kind of recently, i had successfully removed lighters from packs before

#### Server revision

cfea3ae501ced31e1d8ab8556856afb3918f590a

### PR DESCRIPTION
**Pull request by Pathid**
Closes #17023
Closes #17022
:cl:
* bugfix: A storage bug affecting cigarette packets, gum packs, chicken buckets, clipboards, and lazarus belts was fixed.

### CODE REVIEW

**Comment by EdXbtkOEwGw** [comment]
merge NAAOOWW

**Comment by SonixApache** [comment]
changelog

**Comment by Pathid** [comment]
Okay, done.

**Comment by DamianX** [comment]
it's a bit late now

**Comment by Pathid** [comment]
Yeah I guessed PJBot didn't work like that but it was worth a shot.

**Pull request merged**
