### PR TITLE
'YOU FEEL A WEE BIT CHILLY' removed

### PR DESCRIPTION
**Pull request by Arthurdentist**
Without a doubt my greatest single contribution to this game. 

triggering celt

Also removed the line about seeing your own breath because getting that message whilst floating in space is silly.

### CODE REVIEW

**Comment by ghost** [comment]
:-1:

**Comment by Exxion** [comment]
Celt you can see your breath in a room that is literally on fire as long as you are still cold enough

**Comment by ghost** [comment]
That'll fire "you start to feel cold" occasionally when they are already freezing

**Comment by Arthurdentist** [comment]
then I'll change it to 'you feel cold' instead.

**Comment by 9600bauds** [comment]
>no period

**Comment by ghost** [comment]
:-1: :-1: :-1: :-1:

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=lYnrjhrkt-0
to be honest

**Comment by 9600bauds** [comment]
I thought you were from Scotland

**Comment by Arthurdentist** [comment]
nah he's english

**Comment by ghost** [comment]
[triggered]

**Comment by Exxion** [comment]
I really hope this doesn't end up with a [Controversial] tag but at this rate it might

**Comment by 9600bauds** [comment]
needs periods

**Comment by ghost** [comment]
Please tag controversial

**Comment by Arthurdentist** [comment]
full stops\* added

**Comment by gbasood** [comment]
One person is not a controversy

**Comment by ihadtoregisterforthis** [comment]
I'm against this

**Comment by ghost** [comment]
two people is a controversy

> merging a controversial PR

wew

**Comment by 9600bauds** [comment]
Controversial tag is a Riri meme

**Pull request merged**
