### PR TITLE
Makes bullets faster

### PR DESCRIPTION
**Pull request by MadmanMartian**
They are now twice as fast as they were before.

### CODE REVIEW

**Comment by Accipitermaris** [comment]
can you run into your own bullets? (i've heard you can already do that, but i haven't personally looked into it...)

**Comment by Dacendeth** [comment]
syringe guns are going to be scary

**Comment by DeityLink** [comment]
I read somewhere that projectile speed should be a multiple of ticklag to avoid some issues.

**Comment by ShiftyRail** [comment]
Much better than the alternative IMO.

@Accipitermaris If the bullets are fast enough, this shouldn't be (hopefully) a problem anymore.

**Comment by DeityLink** [comment]
@MadmanMartian https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/projectiles/projectile.dm#L103
And I believe server ticklag is 0.66

**Comment by Intigracy** [comment]
Server ticklag is still 0.33

**Comment by Intigracy** [comment]
.5 is pretty close to 1.5 the ticklag, we'll find out if it causes problems or not and adjust it to 0.66 if it does.

**Comment by SonixApache** [comment]
🆑

**Comment by MadmanMartian** [comment]
like a month too late, my duder

**Comment by SonixApache** [comment]
much like you, i only just noticed

**Pull request merged**
