### PR TITLE
Uncomment fire_act

### PR DESCRIPTION
**Pull request by clusterfack**
For funsies

### CODE REVIEW

**Comment by PJB3005** [comment]
merge when

**Comment by dylanstrategie** [comment]
merge when

**Comment by clusterfack** [comment]
pull #4444 guaranteed victory

**Comment by PJB3005** [comment]
Uncomment some fire_act()s on things like canisters too.

**Comment by clusterfack** [comment]
None of them are commented, only the fire_act of fire itself was commented out

**Comment by PJB3005** [comment]
oooooh

**Comment by ririchiyo** [comment]
I believe it was commented out for a reason because it was causing lag at some point. You may actually want to run a profile and see if any issues come up from this.

**Comment by clusterfack** [comment]
No it was only removed under suspicion of possibly causing lag, I was profiling fire since long before it was removed and it never did

**Pull request merged**
