### PR TITLE
buckets now have a reagent overlay

### PR DESCRIPTION
**Pull request by SonixApache**
image

🆑 
 - rscadd: buckets now have a reagent overlay

### CODE REVIEW

**Comment by Exxion** [comment]
dude minecraft lmao

**Comment by Lunstra** [comment]
No longer will I accidentally water a plant with my mutagen bucket.

**Comment by SonixApache** [comment]
i'm not sure what's better
image

**Comment by Exxion** [comment]
The ones on the right
They still aren't *good* but I don't really think you can do it well in such a small number of pixels

**Comment by SonixApache** [comment]
sticking with right, then

**Pull request merged**
