### PR TITLE
Fixed microwave failing for no reason

### LINKED ISSUE #22118: Microwaves unexpectedly fail to cook
I'll put the right ingredients in, and it causes a burnt mess and even destroys the microwave.

I have been playing chef for 2 and 1/2 years at this point and I know when I fail to put the right ingredients in. After testing with rigor and making sure I'm absolutely sure of every recipe, the microwave is still fucking up recipes over and over and over.

### LINKED ISSUE #26129: Microwave recipes involving reagents often fail
In recipes that require reagents, it seems very common that something will fuck up and the microwave will just produce burnt mess, even with the correct ingredients.
Two microwaves side by side, both with 15 flour in? One will fail, one will correctly make bread. Is there some kind of attached random fail chance for microwaves that was added in the last couple of years? AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

### PR DESCRIPTION
**Pull request by DamianX**
Closes #26129
Closes #22118

please subscribe to my patreon
[Patreon](https://www.patreon.com/damianspessmen)

:cl:
 * bugfix: Fixed a bug that caused microwaves to fail despite inserting the correct ingredients.

### CODE REVIEW

**Comment by SonixApache** [comment]
did it really decide beforehand that it wasn't going to work?

**Comment by DamianX** [comment]
Yes, this behavior was entirely deterministic. You could reproduce it by inserting salt from a salt shaker into 4 different containers. The fourth container will contain an amount of salt that is represented as a 1, but is actually infinitesimally smaller than 1, because of the way floating point math is used by reagent code.
`trans_to` performs a division, then a multiplication, so that it can divide each reagent in equal parts. This introduces rounding errors that manifested in the resulting amount of salt added to the microwave being an infinitesimally smaller amount than what the recipe demands, so the fix here gives it a ±0.1 margin of tolerance.

**Comment by Kurfursten** [comment]
>The fourth container will contain an amount of salt that is represented as a 1, but is actually infinitesimally smaller than 1, because of the way floating point math is used by reagent code.

This makes me feel angry.

**Comment by Exxion** [comment]
Don't worry that's just how you feel when any bug is ever caused by floating point math

**Comment by Kurfursten** [comment]
I've been thinking about this more and more. Wouldn't it have been better to do a small rounding operation in `trans_to` and cut the head off the snake? Like on the order of 0.001 - nobody cares about losing less than one one-thousandth of a reagent.

**Comment by DamianX** [comment]
I also thought that the issue was supposed to be addressed at that level, and briefly tried to, but I don't think it's the right solution.
Rounding would just mean that small amounts would either come into or disappear from existence, and I expect most of the code not to deal well with it at all.
I expect examining a beaker and reading "0.9998 units" with that approach.
Or even eventually losing the entirety of a container's content by repeatedly (cleverly?) transferring reagents between it and another.

**Comment by Kurfursten** [comment]
Being able to sieve out a small reagent with cunning and dedicated ghetto workshoppery instead of just using the chem master sounds like a FEATURE to me but hey

**Pull request merged**
