### PR TITLE
Assistants on suicide watch

### PR DESCRIPTION
**Pull request by help-maint**
Sister PR to #29455 so people stop being mad at me for fixing a bug that seemed like an innocent bugfix but I did not realize was actually a fucking legacy bug landmine until I was typing the changelog
This will not compile until #29455 is merged

:cl:
 * rscadd: Paroxetine (the chemical) now prevents you from suiciding, and will revert suicides if you can medicate someone with it before they die. No luck if they die before you get there though.

### CODE REVIEW

**Comment by gurfan** [comment]
cute

**Comment by PrimeDSS13** [comment]
I will now support BOTH PR's.

**Comment by Eneocho** [comment]
Won't be that useful since most suicides kill the character seconds after they suicide, meaning you won't have enough time to drag the guy to medical for paroxetine which would encourage some people having a possible hallucination chem at all times.
Make it so if you dunk the brain in paroxetine inside a jar you can remove the suicide flag. Which would give a more after-death use to the chem too and would encourage surgical procedures.

**Comment by help-maint** [comment]
Cucking someone out of suicide is funny

Clown performing safe suicides with paramed help is funny

Reviving someone 20 minutes after they suicided isn't funny & directly contradicts the point of suiciding

I rest my case

**Comment by Eneocho** [comment]
If the guy wants to be dead he can just not return to the brain/body after it was dunked in peridaxon. But most of the time you wont be able to unsuicide a guy unless you powergay and have peridaxon on you in the first place which is already a massive risk since peridaxon can be electrolized into mindbreaker. Hence why I want the brain-peridaxon so you can revive the brain if you took more than 20 seconds to help the guy.

**Comment by BomberBro** [comment]
I have typed "suicide" into the command line, pressed enter, then clicked "Yes" when the game warned me that this would make me unrevivable, and now I cannot be revived. How could this happen to me...

**Comment by ghost** [comment]
#29455 is merged now

**Pull request merged**
