### PR TITLE
Cosmetic Tail Organs

### PR DESCRIPTION
**Pull request by 13spacemen**
Adds cosmetic tail organs which can be amputated and attached to people, select groin during surgery
Made Vox have actual tails rather than it being baked into the chest sprite
Vox tails are waggable with the *wag emote, anyone with a Vox tail can wag it even humans

Can't wag catbeast or lizard tails due to lack of animated sprites

## Why it's good
Vox needed actual tails, also fixes the issue where Vox tails didn't have a SOUTH dir, and fixes issue where tails would not show up on character preview menu

Tail surgery is a cool and fun addition

Also with the addition of cosmetic organs [they do not take damage or react to disease, they just affect sprite and can be added/removed]

We can add wings or other organs

## Pics and Vids

Screenshot 2024-02-23 182056
Screenshot 2024-02-24 033248

https://github.com/vgstation-coders/vgstation13/assets/46101244/c701aff0-354e-4ab0-865e-b2b8783697a2

https://github.com/vgstation-coders/vgstation13/assets/46101244/5e4332fa-db45-4783-a680-a7e74f71e072

https://github.com/vgstation-coders/vgstation13/assets/46101244/05d98f0c-1c11-49cc-a1a8-7aa25e39ae9f

## Changelog

:cl:
 * rscadd: Added cosmetic tail organs
 * rscadd: Tails can be added and removed via groin surgery
 * bugfix: Vox tails have a proper SOUTH dir
 * bugfix: Tails show properly in character preview

### CODE REVIEW

**Comment by RealestEstate** [comment]
he came back with the wag....

**Comment by JonathanSpaceStation** [comment]
this is destined to fail if you insist on keeping the tail wagging

**Comment by jwhitak** [comment]
This adds a whole cosmetic organ subsystem to the code, which... well. ~~Prepare for unforseen consequences. These organs are immune to standard methods of taking damage, and are not exempted from ``for organ/extenral in mob`` checks - they simply nullify any damage they receive. This will affect chemical healing/harming for sure, and likely other things.~~ Misremembered, most lookups don't go for stored organs in a mob, it goes for the organ list - the cosmetic organs are not stored in this organ list.

This PR also adds an undocumented runechat hiding option for emotes, and applies it to the tail wagging emote by default.

Finally, if it isn't clear, the animated tail wagging complete with message to chat is still here, though it uses the above runechat hiding system to make it less obvious.

**Comment by angryturnip** [comment]
Remove the wagging and I'll change to an upvote

**Comment by 13spacemen** [comment]
@jwhitak the cosmetic organs have their own list in humans, so they dont get included in most of the checks for EOs in H.organs

**Comment by PrimeDSS13** [comment]
tie this guy up and put him on a railroad track

**Comment by jwhitak** [comment]
I've done a quick glance over the underlying code, the cosmetic organs should be OK in terms of medical/damage. Almost all of the organ lookups properly use the human mob's procs, which have been properly edited to not include tails, and they are stored on a seperate list from the traditional organ list for the stuff that skips the procs and looks up the human organs directly. No misshapen tails when cloning, etc.

That leaves the tail wagging.

**Comment by west3436** [comment]
fetish content

**Comment by SonixApache** [comment]
~~cool~~
remove the wagging

**Comment by falcon2346** [comment]
Neat, but it's pretty overwhelmingly clear it's never going to pass with the tail wagging included. Just drop that aspect from the pr at this point, I really want to see the rest in game

**Comment by ghost** [comment]
This is f*rry fetish content even without the wagging.

**Comment by Eneocho** [comment]
my guy, tail mechanics are welcome
the wag isn't, the majority is strictly against the wag, having the wag WILL make it so your PR does not pass, period, simply because people see "wag", think "fetish content" and downvote
remove the wag and this would be an easy merge

**Pull request closed without merging**
