### PR TITLE
Fixes security job inconsistency

### PR DESCRIPTION
**Pull request by MercuriusGH**
## What this does

As outlined in here https://github.com/vgstation-coders/vgstation13/pull/35830 , there is an inconsistency in the security job set.
This PR fixes this.
## Why it's good

A diverse security is a more balanced, understanding and better performing security. A leadership position filled in with individuals of diverse backgrounds will pave to way to a tomorrow where a man of grey and a man of red can understand and work together.

PS: GOD BLESS AMERICA
OIG 8v7q1oEV

## Changelog

:cl:
 * tweak: Removes erroneous HoS whitelist

### CODE REVIEW

**Comment by jwhitak** [comment]
I've had an ayyyy hoss gimmick I've wanted to do for a while...

Does the hoss gear even fit aliens?

**Comment by MercuriusGH** [comment]
> I've had an ayyyy hoss gimmick I've wanted to do for a while...
> 
> Does the hoss gear even fit aliens?

I'm pretty sure it does, the surveyor set definitely has sprites for all species
Oh yeah, the plasmeme HoS suit is also pretty sick IIRC

**Comment by mentgah** [comment]
stop making meme prs

**Comment by SonixApache** [comment]
go forth into the world and find the error of your ways

**Comment by Kurfursten** [comment]
Mentgah is fully right on this one. Could we be open to changing race restrictions on roles? Sure.
Is this obviously a revenge PR for the two that just got closed? Of course it is.

Please don't make github the home for your drama referendum.

**Pull request closed without merging**
