### PR TITLE
Make changeling require more threat.

### PR DESCRIPTION
**Pull request by Manleto**
This is inline with my other proposed change.  

I want changeling back, but I don't want ling every round because I don't wanna mess with things beyond my understanding I decided to not mess with the weight. 

This makes it slightly more likely then civil war of casters but far lass likely then it was before.

:cl:
 * rscadd: Made the ling require more threat

### CODE REVIEW

**Comment by Irradiation** [comment]
>I don't want ling every round

You're really going to have to touch the weight for that, but in practical terms:
-Boost the threat COST. You barely upped the threat REQUIREMENT to a point where the average 40-50 threat round will roll Changeling+Traitor like it used to be until we removed Changeling.
-Jack up the threat REQUIREMENTS. Probably to something along the lines of 
requirements = list(80,80,60,50,40,20,20,20,10,10

**Comment by ShiftyRail** [comment]
https://docs.google.com/spreadsheets/d/1kbYWTjYOPS_FrG5fURSHF8e531r3fUQHcyNqfjUoH0k/edit#gid=0

This spreadsheet simulates (approximatively) 20 dynamic rounds. Input parameters are the average population of those round, the threat requirements (with only two tiers for simplicity) and the weights of the rulesets. You can play with it if you want, and see what's the average percentage you got.

Do note that every cell with a white background in the spreadsheet is a calculation step, not a result.

Cost of a ruleset isn't considered here. It just takes the average number of time that ruleset  is elligible for a draft as a proportion of all available rulesets. This also only works for roundstart rules.

**Comment by DeityLink** [comment]
@Irradiation I really don't think we need to up the threat cost since he's also capping the amount of ling players to 1 though.

It's already higher than the vampire ruleset.

**Comment by DamianX** [comment]
The proposed change mentioned in the OP is #27813, now closed.
Given that changeling in the current iteration is not being readded to the rotation, changes to the ruleset would have to depend on the yet-to-be-coded new incarnation, making this change irrelevant.

**Pull request closed without merging**
