### PR TITLE
Security Centcomm order: Captured antags

### PR DESCRIPTION
**Pull request by ghost**
[content]

Todo:
- [ ] Check for dead antagonists, and halve credit payout
- [ ] Move ghost of qdel'd player back to z1
- [ ] Testing in general

:cl:
 * rscadd: Captured antagonists may now be sent to centcomm when an order is requested for them, for credits

### CODE REVIEW

**Comment by BomberBro** [comment]
TTT traitor tester where you line up the crew and attempt to send them to Centcomm until one finally succeeds

**Comment by ghost** [comment]
> TTT traitor tester where you line up the crew and attempt to send them to Centcomm until one finally succeeds

Gonna add a lot of checks first or do some rewriting to make sure sec is the one doing it (ie security record checks, cuffed checks, whatever other ideas)

**Comment by gurfan** [comment]
I don't like that this discourages keeping antags in perma or exiling them, this is just another way to round remove people.

**Comment by ShiftyRail** [comment]
Pretty straightforward validhunting licence/antag checker, hard pass.

**Pull request closed without merging**
