### PR TITLE
Pesticide now damages insectoids

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Requested by boxed
As much as polyacid (15)
Untested, also it feels barebones so I'll let the collabs tell me what to add

:cl:
 * tweak: Pesticide sprays now damage insectoids

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Test it.

**Comment by boy2mantwicethefam** [comment]
Soon :tm:

**Comment by Irradiation** [comment]
>Untested

The prodigal son returns.

**Comment by dunsel-hordon** [comment]
I know plantbgone damages mushmen so this makes sense

**Comment by GreatBigFailure** [comment]
Wait, is pesticide not a chem? It just works off attack, not a touch reaction? So I guess no roach smoke. Sort of balances itself then.

**Comment by ghost** [comment]
have it make the spray sound on attack and I'll leave an updoot

**Comment by juanototo2** [comment]
It's not a chem. This is effectively just a toolbox. Increase it to 30 or something so people actually have a reason to brandish pest spray to kill pests.

**Comment by Kurfursten** [comment]
It doesn't even make a spray effect when you attack or a spray sound like bottles do

**Comment by KingofHONK** [comment]
Will this work every spray tick like pacid works?

**Comment by Kurfursten** [comment]
Not in this implementation

**Comment by juanototo2** [comment]
What a fucking lazy addition. This deserves an improvement or remake by someone who knows what they're doing.

**Comment by PlausibleDeniability** [comment]
The bug metaclub will not forget thiz...

Take upvote

firefox_5lgpm8uoqm

**Comment by Eneocho** [comment]
Change the pest spray item to a pest spray chem, like the plantbgone sprays you have in botany backroom. Then copypaste the code from plant-b-gone diona and change it to insectoid.

**Comment by boy2mantwicethefam** [comment]
I'm putting this PR on freeze until #28873 gets merged, btw I haven't checked the PR the last few days

**Comment by boy2mantwicethefam** [comment]
I'm closing this PR since #28873 does it better

**Pull request closed without merging**
