### PR TITLE
Revert "Adds the emagged nikita to the black market!"

### PR DESCRIPTION
**Pull request by jknpj**
"Don't vote in a PR 24-3 if you don't want it. If you want to fight the emojis you are welcome to make a revert request."

_Originally posted by @Kurfursten in https://github.com/vgstation-coders/vgstation13/pull/23690#issuecomment-517317582_

:cl:
 * rscdel: Removes the emagged nikita from the black market!

### CODE REVIEW

**Comment by ShiftyRail** [comment]
*They may say I'm a dreamer...*

**Comment by tuypo1** [comment]
No, Let it stay for a while so people can see right from the start what the black market will inevitably turn into

**Comment by Kurfursten** [comment]
Intentionally making a change you think is bad for the purposes of manipulating opinion is peak Yredcoding. In a just world, anyone involved in this kind of thing would be repobanned.

Instead we live in the world where our coding standards call for no one-line-ifs, but not that all changes be made in good faith.

**Comment by boy2mantwicethefam** [comment]
Leave it in, it's one of the most based things to be added this year

**Comment by jknpj** [comment]
If this isn't the flaw of emojicracy, i don't know what is.

**Comment by DrSnips** [comment]
>emojis are wothless when I don't agree with them.

Epic and original stance my dude.

**Comment by Exxion** [comment]
@Kurfursten If everyone involved with it were to be repobanned, *you* would be repobanned

**Comment by Blithering** [comment]
Screw emagged nikita, https://github.com/vgstation-coders/vgstation13/pull/19119 revival when

**Comment by bathosbathtime** [comment]
Nice try collabs, but this two-step dance isn't going to cause me to discredit the will of the community.
Emojiocracy is bunk though, poll it to get those good results.

**Comment by jknpj** [comment]
Emojis aren't worthless. Blindly trusting the emojicracy is, though.

**Comment by ghost** [comment]
Ironically, I think the nikita has shown how exaggerated the impact of the black market is. I've spectated and played like 6 rounds and the only time I remember it being used was by Jack Dale, where he promptly said, "Hey boys, testing out this Nikita!" followed by an explosion somewhere he was presumably gibbed in, forgotten forevermore.
At this point I would keep it in as a meme. There are way better ways to make an explosion without having to ride the missile.

**Comment by plosky1** [comment]
It is funny that retardposters like @tuypo1 have extreme outcry towards this, but actual in-game impact by the emagged nikita is basically non-existent.

**Comment by ghost** [comment]
Damian presented a sizeable--if ironic--argument for adding the emagged nikita, if it's really that detrimental to the black market then it should be easy to present an argument for such.

I don't even think the black market is a bad idea and I think the emagged nikita is ultimately an inconsequential joke that fails to prove Damian's point.

**Comment by plosky1** [comment]
I still think it should be trader-only to sell items, and open to everyone to buy items, as this completely marginalizes their entire purpose, but oh well.

**Comment by kilozombie** [comment]
Traders existing in the context of every other job already having basically everything they want is what marginalizes traders.

Moreover, the basic premise of Trader is what marginalizes Trader.

The primary loop for playing Trader fucking sucks and it's a letdown nearly every round. The intended way to be a trader bird is infinitely worse than the unintended shitbird way, and the unintended shitbird way is unpleasant for everyone else.

haha but that's a discussion for another time

**Comment by ghost** [comment]
Birb
In a future update I plan to make a Black Market Operative antag role that's basically a soft antag whose job is to make cash + gets a market administrator uplink, birbs would get higher chance of being it. So there's that.

**Comment by SonixApache** [comment]
@Kurfursten Did you really merge that one thinking it was in good faith?

**Comment by Kurfursten** [comment]
Like I said, we don't live in a just world.

**Comment by SonixApache** [comment]
😔

**Comment by ghost** [comment]
woke

**Comment by FudgePucker** [comment]
>Wahhh, people added something funny and harmless to my super serious market. I need to counter grudge code them, it is OBVIOUS that this was done with ill intent.

:joy: how much longer until we get as bad as TG?

**Comment by Kurfursten** [comment]
For the record, I don't think the emagged nikita actually matters one way or the other, you can see my commentary on it from Discord yesterday (main server, ick channel).

```
ancientpower Yesterday at 2:27 PM
kurf what is your opinion on the emagged nikita

Kurfurst Yesterday at 2:27 PM
I think it doesn't actually matter because it's just an expensive lootbox
```

My comment was aimed at what @tuypo1 had to say regarding "there should be bad things to make people angry" (which is the definition of admitted ill-intent, if you disagree with this, you are just smallbrained). I wouldn't even bother making this clarification but it looks like about half the posts on this thread are about what I had to say. Obviously if it was something that actually mattered then no emoji ratio would matter. No amount of 👍 will compel the merge of something that crashes the server, for example.

**Comment by jknpj** [comment]
Adding emagged adminbus items to the blackmarket is "i mapped this scp/adminbus item in my map because i want people to play it"-tier. It doesn't matter if it's the groans-o-matic or the energy axe, it's just dumb.

**Comment by ghost** [comment]
It depends on the item. Some adminbus items are just normal items waiting to be used, others are bullet storm supermatter shit that should be saved for ending gunked rounds.
You sure do like making broad generalizations.

**Comment by SonixApache** [comment]
coward

**Pull request closed without merging**
