### PR TITLE
removes the chance of viruses automatically curing themselves upon infecting an individual

### LINKED ISSUE #15307: Virus is broken completely now
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
When you contract a virus your body develops the antigens instantly which makes it useless. You don't even need radium or a doctor. It just autocures itself at stage one.

pls fix

### PR DESCRIPTION
**Pull request by MadmanMartian**
closes #15307

### CODE REVIEW

**Comment by yclatious** [comment]
He actually did it, the mad lad.

**Comment by iFlashYou** [comment]
Cure via Radium will still work?

**Comment by MadmanMartian** [comment]
yes

**Comment by SysadminJeroen** [comment]
Virology more useful? Yes please!

Op 31 jan. 2018 19:14 schreef "MadmanMartian" <notifications@github.com>:

**Comment by Pathid** [comment]
Wait a minute, was that issue really complaining about the one-time 5% immunity chance? Seems like this is just taking away depth here. Isn't finding the one person in twenty who rolls natural antibodies technically an alternative to following the "one size fits all" radium method every time? The same method which doesn't even require the involvement of the virology machines anyway?

**Comment by MadmanMartian** [comment]
It's somewhat backwards, to the point where a 'virus' event fires, and patient zero instantly clicks immune, meaning a 15~ minute wait for the next event with nothing going on.

**Comment by ShiftyRail** [comment]
I believe the original problem was about viruses curing themselves _over time_ magically, including beneficial ones.

A better (but harder, and unrelated) buff to Virology would be IMO to be able to select which antibodies you want to isolate.

A good virlogist did a beneficial virus, call it V1, whose antibodies are VO.
A random event creates a virus, call it V2, whose antibodies are AM.

The only way to produce AM and not VO is to :
- get blood from a victim of V2.
- isolate V2.
- breed V2 in the pathogen incubator
- inject it in a fresh, non-infected monkey.
- harvest antibodies the usual way.

This assumes the manipulator doesn't catch V1 at any point of the operation.
This is long and usually not worth the risk of letting V2 in the station for so long, as well as prone to error.

**Comment by MadmanMartian** [comment]
Closing in favour of #17303

**Pull request closed without merging**
