### PR TITLE
Revert "Revert "Goonchat UTF-8 support and better string highlighting.""

### PR DESCRIPTION
**Pull request by PJB3005**
Reverts d3athrow/vgstation13#11450

Yes, I just tested it and it works on IE9, doesn't on IE8 but if #11452 has a general agreement, then this isn't a problem.

The reason a relog is needed is because chat doesn't reload between reconnects, so it was still running the outdated Javascript.

### CODE REVIEW

**Comment by clusterfack** [comment]
Can you give us any guarantees this will work? I mean if so just self merge this

**Comment by PJB3005** [comment]
Alright if we want to slightly screw over IE8 users (an error when the game loads and string highlighting broken for them) it's fine.

**Comment by clusterfack** [comment]
How do we tell people to get IE8 so that it will work

**Comment by PJB3005** [comment]
Okay hang on I'll just remove the mark.js stuff.

**Comment by PJB3005** [comment]
Good to go.

**Pull request merged**
