### PR TITLE
fix #6817

### LINKED ISSUE #6817: Infinite cables from lightswitch
Screwdriver lightswitch, spam click it with wirecutters.

### PR DESCRIPTION
**Pull request by ghost**
fix #6817

### CODE REVIEW

**Comment by clusterfack** [comment]
You fixed these by checking the state with the do_after, as in
```
if(do_after(stuff) && state == x)

**Comment by ghost** [comment]
Technically this does the same thing though

**Comment by 9600bauds** [comment]
it does it worse

**Comment by ghost** [comment]
Does it better to be honest as it also prevents someone doing anything else at the same time

**Comment by clusterfack** [comment]
Mine prevents someone else from doing it at the same time, yours does not you mean

**Comment by ghost** [comment]
touché

**Comment by 9600bauds** [comment]
This way also prevents you from screwdrivering three different, adjacent things at once, commonly seen with any do_afters

**Comment by ghost** [comment]
Yeah, that's not a bad thing though

**Comment by 9600bauds** [comment]
Either fix EVERY instance of this or leave this one just as broken

**Comment by ghost** [comment]
fixed

**Pull request merged**
