### PR TITLE
Janitor Cargo Crate Tweak

### PR DESCRIPTION
**Pull request by Kharkov72**
Removes a bucket and a sign, in return adds a box of mousetraps.
_The mouse metaclub will remember this_

:cl:
 * rscadd: The Janitor Cargo Crate has mousetraps now.

### CODE REVIEW

**Comment by juanototo2** [comment]
How about KEEP the bucket and sign
It's a fucking janitor crate, it's so fucking irrelevant to powergaymen that it's honestly stupid
For the cost of unlocking one you could unlock a guns crate

**Comment by djkramer123** [comment]
Why remove the bucket and sign

**Comment by djkramer123** [comment]
Why get rid of the mop buckets and signs from the janitorial crate?

Why not just add the mouse traps to it?

**Comment by Kurfursten** [comment]
His thinking might've been that no janitor in the history of SS13 has walked around carrying four (4) buckets.

**Comment by Kharkov72** [comment]
Yeah that's essentially it, but it you want me to keep them then heck I will

**Pull request merged**
