### PR TITLE
New Meta Library

### PR DESCRIPTION
**Pull request by Kurfursten**
I haven't done the final touches because I thought I'd put it up for comments. Summary:
* Added missing accounting computer
* Added missing disk duplicator
* Added missing research archive
* Added missing games vendor
* Added the new librarian closet, which allows us to avoid hardmapping his clothes on every map! This will make future new librarian items much easier to add.
* Overall, total bookshelves increased by 1.
* Art storage now by library
* Old art storage (by bar) has become a barber

image

🆑 
* rscadd: The Metaclub library got some new furniture!

### CODE REVIEW

**Comment by Pastamadness** [comment]
The bookshelves near the easels don't really seem to fit the theme of the corner. A table for placing art supplies would be better and wouldn't block view of the paintings from inside either.

**Comment by Kurfursten** [comment]
I understand where you're coming from, but this time it was a conscious choice. Not only does this make librarian players happy because there are more bookshelves, but you can sneak around and sabotage the art due to the sightline - which I've noticed some people enjoy doing on the Roid library where it's more broken up. The good news is that bookshelves cost more wood than a simple wood table, so if you want to convert from shelf to table it's fast and easy to do so.

**Comment by Pastamadness** [comment]
It still looks out of place. Something is missing there.

**Comment by PrimeDSS13** [comment]
I'll miss the reading rooms

**Comment by Kurfursten** [comment]
I think it just looks odd without the carpet detailing. Here's in-game.
image

@PrimeDSS13 I feel you, and I actually think there is room to possibly bring them back in the future by encroaching on maint to the left. The design I have here is designed with that potential future in mind - I'd like to get the library in first though since a change to maint and bathrooms might cause unnecessary backlash.

**Pull request merged**
