### PR TITLE
Fixes eggs not being picked up by bags (addresses #2693)

### PR DESCRIPTION
**Pull request by ghost**
Eggs' `attackby()` was defined twice, and the last one didn't call `..()` so neither bags nor egg colouring would work. Fuck you Bay.

### CODE REVIEW

**Comment by Probe1** [comment]
I love when you guys do this and fix something within minutes of me posting it.

**Comment by wwjnc** [comment]
I had been wanting to fix this since I've felt the pain of a trillion chickens on botany pushing you around the last days.

**Comment by ComicIronic** [comment]
And this is why you don't use relative pathing.

**Comment by d3athrow** [comment]
chickens are pushing you around?

**Comment by Probe1** [comment]
@d3athrow try making a chicken farm.  they love to push.

**Pull request merged**
