### PR TITLE
Misc boxstation tweaks

### LINKED ISSUE #13178: Box's SME room and radiation belt event
On boxstation, during a radiation belt event, there is no shielded area near the SME room except for the escape pod; i think that at least the small storage near the SME room could be shielded.

radiation belt

### LINKED ISSUE #13975: Box Radio Transmitter room is walled off
good work
@Lokiamis

### PR DESCRIPTION
**Pull request by DamianX**
Xenobotany sink: #14205 (don't close, this only fixes box)
image

Media server room: Fixes #13975
image

Buckshot: #13783 (don't close, this only fixes box)
image

Engineering radiation shielding: Fixes #13178
image
image

Removed wall from telesci to make the room symmetrical: no linked issue, courtesy of the Italian metaclub
image

Mechanics AI holopad: #13683 (this should probably be re-opened, deff is still not fixed, I think?)
image

UPDATE:
 - Fixed the telescience wall
 - Added mechanics holopad
This is how it looks right now:
image
image

:cl:
 * rscadd: Boxstation: added a sink to xenobotany, buckshot shell box in the warden's office and an AI holopad in mechanics.
 * tweak: Boxstation: Auxiliary Engineering is now radiation-proof, removed a wall from telesci, removed a wall blocking the media server entrance.

### CODE REVIEW

**Comment by Zth--** [comment]
**_Anon from the thread:_** ```I don't have a github account but I have a problem with this PR. The last one, the removal of the wall, means the walling around science is no longer "linked." If he wants to remove that wall he needs to put another new wall under the airlocks to complete the room. This pushes into Maint a little and you'd have to move the rack that is currently occupying this position. ```

**Comment by DamianX** [comment]
Updated the OP.

**Comment by Probe1** [comment]
Use the words Closes/Fixes/Resolves [Issue Number] so it automatically closes the issues you've linked.

**Comment by Probe1** [comment]
Also condense your changelog.  Hit the high notes you don't need to record everything.

**Comment by DamianX** [comment]
Done!

**Pull request merged**
