### PR TITLE
[Bugfixes] bunch o small fixes

### PR DESCRIPTION
**Pull request by DeityLink**
- Fixed the Adminbus' layer being to low.
- Fixed the Adminbus' jukebox not spawning facing the correct direction.
- Vampires names and ckey on the Round End Information are now in bold, just like for every other roles.
- Fixed the sprite of unpowered/broken Mass Driver computers
- Fixed the old Mass Driver computers that were using the new Pod Computer sprites instead of their regular old computer sprites (such as the one in the Derelict chapel/on the Syndicate ship)

### CODE REVIEW

**Comment by DeityLink** [comment]
Alright, should be good for merge.

**Comment by clusterfack** [comment]
Squashing this would be just awesome. Four lines per commit.

Just use git rebase -i upstream/Bleeding-Edge, and replace pick with squash for the last 4 commits.

**Comment by DeityLink** [comment]
Squashing commits is piss easy with smartgit, you can do it without using any command lines (I still use one to force push)

**Comment by clusterfack** [comment]
It's not that hard with command lines either, though yes certain git clients make it reeeeally easy but its hard to keep track of who uses what

**Pull request merged**
