### PR TITLE
Removes auto-shading on beheading, but cultists can now shade properly from severed heads or brains. Merry Christmas

### PR DESCRIPTION
**Pull request by DeityLink**
#28444 but better

:cl:
* tweak: Cultists no longer auto-shade on Act 1+ when beheaded.
* tweak: Cultists that have been decapitated/de-brained can now choose to shade when using the Ghost verb.
* tweak: However whether they try to shade while still in their body or after they've been decapitated/debrained/mmi'd, they can only do so up to 60 seconds after the time of death. (living cultists can still shade out anytime they want of course)
* tweak: Shades now take 1hp of damage per Life() tick while in space, killing them in about one or two minutes. So no more sitting in space breaking windows.
* tweak: Shades also now take damage and get slowed by holy water just like constructs do.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
I see where this comes from but this is so very forgiving for the cultists. Now it's not enough to kill them and behead them, you have to always deal with a shade as well.

**Comment by boy2mantwicethefam** [comment]
Shades are extremely easy to kill

**Comment by ShiftyRail** [comment]
Still, in an exchange which the cultist already lost heavily by dying AND allowing his body to get beheaded (which is a permadeath sentence to any other antag), the cultist gets another "get out of jail free" card.

**Comment by boy2mantwicethefam** [comment]
Vampires and wizards can jaunt away from cuffs
Just weld the vents if you worry about shades bro

**Comment by BomberBro** [comment]
Keep in mind that shades recently got a buff to their health recently, Barry.

This is a really abhorrent change and makes stopping shading all but impossible unless security starts putting pacid into their pepper sprayers (which I might unironically do if I play sec during cult with this garbage). This makes it incredibly hard to actually kill shades now since you can't prevent it, and unless they shade directly in the brig you won't be able to kill them before they fuck off. 
This isn't just about shades zipping into constructs either, I've seen shades fuck off into space after cult gets utterly destroyed then go on to smash windows and vent shit out of spite, even going as far as fucking up the SME. Shades can run as fast as a human in space in any direction forever so there's no good way of catching them once they start doing this. This PR will just make both the construct spam and especially the spite venting more common.

**Comment by boy2mantwicethefam** [comment]
The mistake here is implying that all these things will only appear with the PR and haven't existed for literally 2 years or more. Keep in mind that almost every merged cult PR ever since its inception was a nerf one way or another, or that shades deal the equivalent of fist damage. If you really want to prevent venting the station then just make a PR to prevent fist-damage mobs from breaking windows since they are simplemobs, this PR doesn't influence anything regarding that, only that people can't cheese cultists to death by decapitating them

**Comment by DeityLink** [comment]
>Now it's not enough to kill them and behead them, you have to always deal with a shade as well.

But that's the entire bloody point! That was the intent the whole time. Auto-shading was added originally to fix people trying to circumvent that by beheading.

@ShiftyRail 
> Still, in an exchange which the cultist already lost heavily by dying AND allowing his body to get beheaded (which is a permadeath sentence to any other antag), the cultist gets another "get out of jail free" card.

Same thing again. That's their trump card that other antags don't have, and it's not as if it let them respawn as pale bodies either, or even with a human body at all in that regard.

**Comment by DeityLink** [comment]
@BomberBro they got a 10hp health buff (which was their original health, back when they were already considered very squishy). They still die in just as many hits from any sec weapons, and it just takes 2 more punches for unarmed crew to deal with them.

**Comment by BomberBro** [comment]
@boy2mantwicethefam This happens all the time, a couple weeks ago I even saw one dragging the shard. It's not new and it's likely to only get worse with more shades. If shades were prevented from doing this somehow though I'd be indifferent to this PR. 
> Keep in mind that almost every merged cult PR ever since its inception was a nerf one way or another

This isn't a MOBA, cult doesn't need a buff for every nerf. If it makes the gamemode better I think it should get added or removed regardless (I'm a supporter of giving cultists some early communication method or a few leaders to order around lackeys so you don't get some loser drawing runes in the courtroom and can organize).

**Comment by boy2mantwicethefam** [comment]
How many maps even have the shard vulnerable? From all I remember all of the shard chambers were completely surrounded by collector structures that couldn't be bypassed by shades, at least on Box and Roid

**Comment by BomberBro** [comment]
That's a "feature" of Deff, I've seen it happen on roid funnily enough but I'm pretty sure it was left out in the open in engineering beforehand because ???

**Comment by DeityLink** [comment]
After discussions on Discord with @BomberBro the following change has been added:

* tweak: Shades now take 1hp of damage per Life() tick while in space, killing them in about one minute. So no more sitting in space breaking windows.

This should prevent most of the frustration that could occur from a shade escaping.

**Comment by Irradiation** [comment]
What happens if the cultist shades while he's inside a locker (locked or not)?

**Comment by KingofHONK** [comment]
I will happily shelve any game balance issues short term if it means another metacheck can be purged from this gay earth

**Comment by Kammerjunk** [comment]
>But that's the entire bloody point! That was the intent the whole time.

"that's intended" is uhhhhhhhhhhh not really a defence against "that's dumb"
that said, what @KingofHONK said. traitor testers are a fucking video game-y plague

**Comment by Kammerjunk** [comment]
also not that it matters but one minute and 40 seconds*
the mob subsystem is scheduled for every 2 seconds

**Comment by ShiftyRail** [comment]
I for one cannot wait for security officers to start carrying bottles of polyacid to make short work of any heads they win and keep that habit for other gamemodes such as Traitor

**Comment by DeityLink** [comment]
> I for one cannot wait for security officers to start carrying bottles of polyacid to make short work of any heads they win and keep that habit for other gamemodes such as Traitor

@ShiftyRail Don't blame me for sec offs always going for the most meta and powergamey way of dealing with anything they can encounter in this game. I stopped using telesci to acquire all the cool toys as a scientist at roundstart years ago and I never build space bases as cultist. Be the change you want to see.

**Comment by DeityLink** [comment]
I remember back when replacing the atmos digital valve at roundstart with a manual valve on the off chance that the AI was malf was a bannable offense.

**Comment by Kammerjunk** [comment]
it still is
maybe people dislike malf less

**Comment by DeityLink** [comment]
> so I guess you can't pre-emptively lock them in a gay-shade-jail that way until they expire.

@Irradiation This is safer than having the shade spawn at the head's old loc since it may as well be inside someone's bag and the last thing we want is a mob in an inventory slot (they can't even be removed).

**Comment by DeityLink** [comment]
> maybe people dislike malf less

@Kammerjunk How is that related to this PR at all? Thanks a lot for your contribution.

**Comment by ShiftyRail** [comment]
I would if going easy on cultists didn't force me into an uphill & frustrating battle.

Don't get me wrong, but view it from the crewman's perspective. You do everything "right" : you win the initial engagement, you behead the dude, and the guy who made two grave mistakes still has a chance to come back as a jugger or a wraith.

It's one of the little things that makes fighting cult tiresome. Extreme punishment for one side, with the biggest stun in the game, an immense snowball potential, less information, a much more stressful position to be in (oh shit, am I accidentally killing non-antags? Will I get a ban?), but the other side has plenty of safety nets, with the concept of shading - which is buffed here -, 100% correct info on who to kill and who not to kill, a reliable stun indicator for their papers, the fact that most of their tools cannot be used against them...

I am all for safety nets in ""game design"", but they should exist on both sides!

I might be the stereotypical "old man yelling at bloodstones", but there is a reason why in some cases, some crews prefer to call the shuttle right away at the first sign of cult rather than try and fight them.
If this metacheck is such an important thing, do it in a way that doesn't feel like a huge straight buff.

**Comment by DeityLink** [comment]
But there's so many other ways you could go about the initial engagement. If they come back as a jugger or wraith that means they have a forge and altar set up. The best way to gauge if a cult is competent or not would be to keep them alive or sedated and with a tracking implant, this way not only do you see if the rest of the cult bothers to summon them, but if they do you get the location of their base. This way not only do you prevent them from being a shade altogether (unless they suicide) but you prevent them from raising any other constructs by destroying their base.

Seriously does sec really never use tracking implants during cult rounds? What good are safety nets when you don't use them.

> with the biggest stun in the game,

doesn't matter when even a taser/stunbaton stun from an officer is just as much of a game over 90% of the time for cultists as well. Stuns are overpowered in spess, no matter their duration. The cult stun's duration only guarantees time to attempt a conversion, but even a 10 seconds stun would be enough if the goal was just to decapitate.

**Comment by ShiftyRail** [comment]
>doesn't matter when even a taser/stunbaton stun from an officer is just as much of a game over 90% of the time for cultists as well. 

Well, no, not with this buff it isn't.

I see a guy standing next to an illegal W, doing clearly cut shit. Let's say I tase them, kill them, keep the head on my backpack. Then what?

I can't toss it to space, because if he's got good reflexes, he'll ghost out in the airlock, walk near the walls and join the cultos.
If I carry it on my bag, I have to walk to chemistry, which may be destroyed, busy, or enemy territory. On my way there, the culto can shade when next to a vent and go away scot-free. If I get ambushed on the way there, and I run away, the shade can use it as their cue to just go away and exit. If I get ambushed and fight, the cultos can get a shade poking me in the back or body-blocking me.

This essentially FORCES you, whenever cult is confirmed, to fill your peperspray with polyacid. This is silly.

>Seriously does sec really never use tracking implants during cult rounds? What good are safety nets when you don't use them.

Might be a viable idea if you have 1-3 suspects and enough people to track them. In Cult, everyone is a suspect...

**Comment by coronasaurus** [comment]
metagays seething

**Comment by DeityLink** [comment]
@ShiftyRail reposting all I wrote on Discord for people here to see I guess

> Let's try that again
you see that guy next to an illegal W
you tase him, cuff him, and bring him to the brig where you immediately bucklecuff him
see if you can have him or not confess about being a cultist, either way you tracking implant them and have them locked naked in solitary confinement until you can ascertain for sure
such as checking the DNA of the blood on the rune
Seriously why did I go to such lengths to make sure runes carry on the DNA of those who drew them if they're never getting checked anyway
While they're locked in solitary confinement there is no risk of them escaping as a shade
and if they get summoned out they'll out the location of the cult base
so in one case you have one less enemy to worry about, in the other you can immediately catch the rest of them
or at least one other
Basically there are no outright advantage to beheading anymore
beheading became a thing in the first place because cultists couldn't shade while beheaded which was an oversight

**Comment by DeityLink** [comment]
You can still prevent shading by either eating the brain or pacid-ing the head, but you can always acquire pacid the same way you acquire loyalty implants **after** cult has been confirmed, and it gives the cultist a more reasonable timeframe to shade out than getting shot twice in the head.

**Comment by Kammerjunk** [comment]
>How is that related to this PR at all? Thanks a lot for your contribution.

well, I'd say it's about as relevant as "I remember back when replacing the atmos digital valve at roundstart with a manual valve on the off chance that the AI was malf was a bannable offense." if you can't follow it, that isn't my fault

**Comment by DeityLink** [comment]
The point was "people taking measure on the off chance of there being a specific antag" being banned. If we're banning it for malf why wouldn't carrying pacid as secoff from roundstart also be banned and what does this have to do with people liking cult or malf?
 @Kammerjunk 

(Also I'm not saying I vouch for it being banned, I just think it'd be annoying for Secoffs to have to worry about that every round and that they really should just bother getting pacid after a cult's been confirmed but then some will agree that the cult will get the initiative and I disagree because most cults can't do shit with their initiative while sec has gotten pretty good at it but here we are)

**Comment by ghost** [comment]
"Immediately catch the rest of them" feels rather optimistic considering unless the guy was sedated the whole time, he's probably aware he has some kind of an implant, can communicate this to his fellow culties, and they are now equally aware of the situation and in their base that they can quickly escape/fortify/set up an ambush near, plus one extra body that they can hand an instant defeat paper to and tell to stand by the door and wait.

Whereas if you behead them and kill the shade, that's one less cultist/potential construct to worry about.

A cult that uses its tools properly is a nightmare to deal with, so I can't really fault people for jumping to thinning the herd, even if there's a theoretical "better" solution (which requires assuming that the cultists are not competent and the officers are). But all of that is a bit beyond the scope of this PR, which is a definitely a buff to cult but probably an improvement over the bootknife test.

**Comment by Kammerjunk** [comment]
because people dislike dealing with a malf AI considerably less than they dislike dealing with a cult (probably also due to rate of occurrence)
and because what Shifty actually said was not that they'd start carrying pacid roundstart in case it's cult, but that they'd start grabbing pacid when they find out about a cult, and that carrying pacid would slowly become normalised to the point where it would eventually be acceptable for sec to carry pacid

I'll guarantee you that if malf was as common and as painfully opaque (e.g. if not all silicons became malf and you got banned for killing the wrong silicons), people would get real tired of the mode and start preparing for its eventuality

**Comment by DeityLink** [comment]
@sumireiro-sora

That's obviously optimistic but if the guy doesn't get summoned then you've achieved the same results of having one less enemy to worry about right now (assuming the guy even had the cult comms ability)

> they are now equally aware of the situation and in their base that they can quickly escape/fortify/set up an ambush near, plus one extra body that they can hand an instant defeat paper to and tell to stand by the door and wait.

Who's optimistic now? I'd dream of ever observing a cult being this competent, for real.

Also I completely agree with you, killing the shade is the easiest move to me. Bring the head to escape, either it shades out and you laser it twice and it's dead, or it dies in space.

Cult is only broken on paper, which I agree is a design issue. A properly organized cult is way too strong potentially, while a lone cultist is way too weak, both which I want to address down the line.

@Kammerjunk Do sec offs carry loyalty implant at roundstart all the time though? It's used not only for cult but for revs too.

**Comment by DeityLink** [comment]
Updated the changelog again. Following discussion with @ShiftyRail we've agreed with a compromise where dead cultists can now shade out only up to 60 seconds following their death. Current changes:

* tweak: Cultists no longer auto-shade on Act 1+ when beheaded.
* tweak: Cultists that have been decapitated/de-brained can now choose to shade when using the Ghost verb.
* tweak: However whether they try to shade while still in their body or after they've been decapitated/debrained/mmi'd, they can only do so up to 60 seconds after the time of death. (living cultists can still shade out anytime they want of course)
* tweak: Shades now take 1hp of damage per Life() tick while in space, killing them in about one or two minutes. So no more sitting in space breaking windows.
* tweak: Shades also now take damage and get slowed by holy water just like constructs do.

**Comment by Kammerjunk** [comment]
no
they carry knives :^)

**Comment by SonixApache** [comment]
latest iteration is a great change, good work

**Comment by kernikov** [comment]
Just make separate head-only "wisps" for beheaded cultist shades. EZ FIX

**Comment by APCUnlocked** [comment]
Why do they have the ability to shade after being beheaded in the first place? I ain't seen no vampires or wizards fucking off back to their buddies after getting their heads blown off.

**Comment by DeityLink** [comment]
@APCUnlocked yep, that's a cult exclusive ability. Their only innate ability even beyond writing runes.

**Comment by gurfan** [comment]
ah great, now security gets to babysit the head of every cultist for a minute after beheading them, why even bother at all?

**Comment by DeityLink** [comment]
That's the point, beheading them and keeping the head is just a guarantee that you'll have them in your sights when they shade (which may or may not actually be desirable depending on if you're fighting other cultists at that time). In the worst case scenario if you ignore it, you have a shade loose, which only represents a threat to the station if there is a base setup and ready to turn it into a juggernaut (in which case, don't waste time decapitating and go find that base, since even if you kill the shade the cult can eventually summon the shade back anyway (I mean they have the potential to, but they rarely do, reminder that most cultists have no idea what most of their abilities actually are and it's my fault, you've gotta admit that the shadeout is at least one cult abilities that is among the better understood by both cultists and the crew thanks to it not requiring lengthy setups beyond the altar)))

Also having security lose the habit of decapitating cultists may be desirable given the upcoming deconversion update (tm) that I'll definitely get back onto soon. I've had a week of paid leave and rest, now I'm 100% operational and surely can handle both supporting my work, SS13, my TF2 map's definitive edition, and playing games on the side.

**Pull request merged**
