### PR TITLE
Hardsuits from cargo

### PR DESCRIPTION
**Pull request by brndd**
[content] [powercreep]

As things stand if all the roundstart hardsuits go missing, as they often do, you're shit out of luck. However there's still enough of them on station accessible with sufficient ease for antags and powergayers to almost never have trouble getting them, so this lack of hardsuits usually just ends up shafting latejoiners in long-running rounds. So why not allow them to be ordered from cargo?

This adds engineering, atmos, mining, medical and security hardsuits to the cargo console under Clothing for ~~$250~~ $350 a pop, except the atmos hardsuit which is $400. Each crate comes with the hardsuit (which includes the helmet), appropriate magboots and a breathing mask, to match the roundstart suit storage units. There's also the paramedic's EVA suit at ~~$200~~ $300, it's cheaper because it's apparently not a proper hardsuit but I can make it cost the same if this sounds silly. Every crate requires appropriate access to the department the hardsuit belongs to in order to unlock.

~~I also made the existing civilian space suit only $150, because at $200 it felt a bit too expensive compared to the real hardsuits, and making it cheaper might make breaking into EVA or engineering for a hardsuit a bit less appealing in comparison (though who am I kidding, breaking in is free).~~

~~Untested because apparently the fucking cargo shuttle console doesn't work under Wine (or at least doesn't work under my Wine installation). It compiles fine, and really, how could I *possibly* fuck up adding a bunch of items into a list? Hah hah... I'll test this when I get back to my desktop tomorrow.~~ Turns out I just forgot to compile libvg, now officially 100% tested.

:cl:
 * rscadd: Hardsuits can now be ordered from cargo. The following hardsuit crates are available under the Clothing tab for $350 per crate: engineering, mining, medical, security. The atmospherics suit is available for $400. Additionally, the paramedic softsuit is available for $200. Each crate contains the hardsuit and its helmet, magboots, and a breath mask. Each crate requires appropriate access to unlock.

### CODE REVIEW

**Comment by brndd** [comment]
Perhaps hardsuits could also be added as something R&D can produce. At least to my knowledge this is not currently the case.

**Comment by ghost** [comment]
Expect security mains to complain about losing snowflake hardsuit monopoly.

**Comment by brndd** [comment]
The security hardsuits require armory access to open, and all the other hardsuits also require appropriate access as well. I don't think this is really rife for abuse thanks to this access requirement, and if Cargo's busting crates open the relatively steep $250 price tag will make them feel every hardsuit order in their back pocket (plus cargo already has lots of hardsuits they can get from mining).

**Comment by SonixApache** [comment]
Box comes with 8 engineering hardsuits, 5 atmos hardsuits, 5 security hardsuits, and two medical hardsuits. And a CE hardsuit but whatever.
Is having to go into space as one of these roles and not having enough suits really a common occurance?
Is it so important to have easy access to hardsuits that softsuits should be completely thrown into oblivion?

Is this change really warranted?

**Comment by kernikov** [comment]
Something something life boats on the Titanic

**Comment by SonixApache** [comment]
something something civilian softsuits

**Comment by brndd** [comment]
As a principle I don't think it's good to have roundstart items that are completely irreplaceable, unique items notwithstanding. Hardsuits get "used up" in that the longer a round goes on the fewer will be available due to people getting spaced with them, going braindead with them on in some ass end of the station, etc. It may not be a common occurrence for them to run out, but they're also not the kind of item that should be completely irreplaceable. Another example of this kind of item is the firesuit, which is not available from any vendor or crate and I can't help but think that can't *really* be intentional... might PR that separately later.

This change specifically does not target civilians because of the access requirement. Anyone who can open these crates already has access to a roundstart hardsuit. I don't think it's going to compete for civilian space suits because of that. They're also more expensive than the civilian hardsuit, even if I undo the price reduction for it (and if I do undo it, then I'll increase the paramedic suit's price to $250).

**Comment by GoodG1448** [comment]
What about a crate with 3 of those orange softsuits perma prisioners get from the roid work camp?

**Comment by aceedex** [comment]
I dislike it, as we already have softsuits in cargo, ghetto spacesuits and shelters in fire alarms. 

Would much rather have a modkit that turns a soft suit to a hardsuit or give the existing hardsuits research values so that they may be scanned by mechanics, and tie a fair mineral cost to em

**Comment by Blithering** [comment]
Calling it now, if this gets merged no-one will buy anything but atmos suits. 
All in all, I think its a bad idea to make hardsuits this easy to obtain, a large part of the danger of life on a space station is the fact that there aren't enough suits to go around, and the easy to obtain ones are enough of an inconvenience to deter people from wearing them constantly.

**Comment by SonixApache** [comment]
>This change specifically does not target civilians because of the access requirement.

I really hope you don't actually believe access requirements deter anyone.

>I don't think it's going to compete for civilian space suits because of that. 

I don't think there's anyone that would willingly step into a civilian softsuit if they could get a hardsuit with about an equal level of difficulty.

**Comment by Blithering** [comment]
>if Cargo's busting crates open the relatively steep $250 price tag will make them feel every hardsuit order in their back pocket

Doesn't the money from cargo orders go into the cargo account anyway? Either way $250 still means every crew member can afford a suit of their own roundstart, sometimes without dipping into their accounts

**Comment by mtpowell** [comment]
Should make them something above the round start funds and make the atmos suit more expensive, for obvious reasons

**Comment by brndd** [comment]
@SonixApache 

> I really hope you don't actually believe access requirements deter anyone.

But they do, to a degree. Put insulated gloves behind engineering access and witness the shitstorm that would ensue. Busting crates open is way more effort than hacking EVA open and getting a suit from there is, yet in the overwhelming majority of rounds EVA still has most of its suits present.

Either way I increased the prices for the suits. They're now $350 each, except the atmos suit which is $400 and the paramedic suit which is $300.

**Comment by MadmanMartian** [comment]
don't mean to burst anyones bubbles, but as of #22009 hardsuits have been available from cargo.

**Comment by Blithering** [comment]
@MadmanMartian only if there's an emag going around.

**Comment by tuypo1** [comment]
Sounds like a good idea to me

**Comment by Fruktlimpa** [comment]
"AI, order 20 hardsuit crates"
"Yes of course human"
Hardsuits. FOR EVERYONE.
Cargo personnel have no morals and would have no qualms about distributing hardsuits to the populace so every round henceforth is going to be 90% of the crew in hardsuits constantly.
Space is dangerous and should stay dangerous, it should not be effortless to acquire protection from space.
If you are not a job that requires you to venture into space then you should not have easy access to hardsuits.

**Comment by brndd** [comment]
AI doesn't have infinite (ok, $5k starting) money anymore. The miner could still do that, but hopefully Kurfurst will fix that part of the economy soon.

Also there's absolutely nothing preventing the AI (or the miner) from doing that same thing with regular space suits, which are already in cargo and cost even less. Yet it never happens.

Also we have not one but two races that get a free roundstart space suit yet those haven't killed the game either.

**Comment by SonixApache** [comment]
That's because civilian spacesuits are slow as balls and not very suited for indoor use.
Whereas hardsuits barely get a speed malus, get free lights, armor, and nobody cares when you wear it.

**Comment by brndd** [comment]
just fucking close this already

**Pull request closed without merging**
