### PR TITLE
Lowfat Bagel

### PR DESCRIPTION
**Pull request by plosky1**
It's that time of year. Actually tested multiple times (lol). Something's probably still broken but I had 9 monkeys running around for an hour and everything worked so.

A lot of this was @beesil . Unfortunately basil has disappeared once again, so I'm uploading. If basil comes back and wants to change shit, I'll upload their changes.

Trade sprite courtesy @kane-f

voxtbig

More sprites courtesy boxed

gull_xing

lowfatbagelcomp

### CODE REVIEW

**Comment by Exxion** [comment]
>ERROR: 'step_x' found on line 1699. Remove it, please.

**Comment by ghost** [comment]
but why is the singularity back

**Comment by plosky1** [comment]
> but why is the singularity back

real bagel has singularity

**Comment by DamianX** [comment]
It looks like a better version of bagel in all regards, but it's still xbox hueg, which was the main big issue.

**Comment by DamianX** [comment]
Also, you need to save in the TGM format.

**Comment by plosky1** [comment]
> It looks like a better version of bagel in all regards, but it's still xbox hueg, which was the main big issue.

Purely size-wise, it's around Box's size. But it's much easier to get around places making movement faster and it seem smaller when actually playing.

**Comment by beesil** [comment]
I got busy with life stuff, sorry. It's probably best you take this over, but there's a big list of stuff that I noticed while looking/working on this that needs to be fixed:
- Security hardsuits on abandoned outpost will result in miners with sec hardsuits every round.
- The morgue body disposal spits whatever you put down it back out after a few seconds.
- Sneaky detective thermals + vectors in the armory.
- No oxygen tank dispenser/oxygen canister in the armory EVA.
- Tons of missing table dressings (notably mechanic's office, art storage), missing air alarms, missing lightswitches, missing firelocks, stray pipes/wires.
- Maint room full of sunglasses.
- Abandoned bathroom uses a lamprey area that prevents ghosts from crossing it.
- Several of the brig windoors have the wrong access requirements (brig medbay, drunk tank, warden's desk).
- Missing xeno spawnpoints.
- Missing lightbulbs in dorm rooms.
- Ninja glove training poster in main halls.
- Broken disposals sorting (possibly fixed).
- Probably a bunch more stuff I'm forgetting.

I'm all for this getting into the game, but before this is merged it needs a very, very through quality check.

**Comment by plosky1** [comment]
First is the stuff that's intended, which is det thermals, vectors in armory which is standard, maint room, and abandoned bathroom area. I'll go back through the areas you listed but most of it I've already fixed.

Missing lightbulbs in dorms is intended for that northern room due to fire in fireplace will light it up.

Will remove the posters and recheck missing items.

**Comment by plosky1** [comment]
Alright, I've just done an EXTENSIVE item/light switch/comms sweep and added some in where they were missing. Everything else has been addressed EXCEPT:

thermals in det
vectors in armory
maint room of sunglasses
abandoned bathroom area

If consensus is that these items should go, I will. As for now though I think they add flavor and should be left alone.

Besides that it's been playtested somewhat extensively. I will reupload along with a custom Vox tradepost sign that was just sprited.

Otherwise it should be good to go unless someone points out something. I also removed all the stuff that we talked about earlier from the old perma on z5 @beesil and it is, as of now, just some assistant corpses and a little bit of lore.

**Comment by Eneocho** [comment]
A direct line from hydroponics to medical and science without twists and turns? Based.

**Comment by juanototo2** [comment]
> 
> 
> Alright, I've just done an EXTENSIVE item/light switch/comms sweep and added some in where they were missing. Everything else has been addressed EXCEPT:
> 
> thermals in det
> vectors in armory
> maint room of sunglasses
> abandoned bathroom area
> 
> If consensus is that these items should go, I will. As for now though I think they add flavor and should be left alone.
> 
> Besides that it's been playtested somewhat extensively. I will reupload along with a custom Vox tradepost sign that was just sprited.
> 
> Otherwise it should be good to go unless someone points out something. I also removed all the stuff that we talked about earlier from the old perma on z5 @beesil and it is, as of now, just some assistant corpses and a little bit of lore.

Keep the maint sunglasses room, ditch the fucking detective thermals holy fucking shit. Thermals are antag tools for a a reason - they're very, VERY good intel. I don't care about the rest.

**Comment by RaccoonBro** [comment]
Arrivals is a bit barren. Maybe add a way to get into dorms from the hall that connects to the shuttle. At the very least add a maint door for that lil' maintenance area.

Looks real nice though

**Comment by gurfan** [comment]
I really liked the R-UST on bagel :(

>thermals in det

remove these god damn

**Comment by plosky1** [comment]
Updated. Removed thermals, added maint door at arrivals.

**Comment by ShiftyRail** [comment]
Let's see how this one goes.

**Pull request merged**
