### PR TITLE
Makes scattershot fire buckshot rounds

### PR DESCRIPTION
**Pull request by SonixApache**
tested
webm: https://puu.sh/w8ArE/8999940923.webm

🆑 
 - tweak: The LBX AC 10 "Scattershot" now fires buckshot rounds.

### CODE REVIEW

**Comment by ghost** [comment]
yamero
buckshots only good for close range and at that point you can just punch people with the mech

**Comment by SonixApache** [comment]
you'd be surprised how extremely extremely effective this is
download the branch and see for yourself
The spread of the pellets is entirely dependent on how far away you're aiming.  On a marauder with zoom optics enabled you can condense the entire blast into one tile.

**Comment by FudgePucker** [comment]
Does it stun though?
Scattershot last time I checked caused stun on hit. Also the 3x1 shot pattern is perfect for hallways

**Comment by SonixApache** [comment]
Doesn't fire c-20r bullets anymore, so no.
Spread's kinda nice this way, not as... weird.

**Comment by Blithering** [comment]
> The spread of the pellets is entirely dependent on how far away you're aiming. On a marauder with zoom optics enabled you can condense the entire blast into one tile.

Do you mean the spread is tighter the further away you aim?

**Comment by SonixApache** [comment]
Yup. I'll make a webm tomorrow.

**Comment by Blithering** [comment]
Neat, does this affect the damage of the weapon?

**Comment by SonixApache** [comment]
@Blithering Damage is slightly more or less, depending on how many pellets hit you.
Current master build scattershot:
dreamseeker_2017-06-02_13-48-56
For some reason the forced-spread it's supposed to have didn't work, so that's one click per catbeast.

And then my change.
Max spread:
dreamseeker_2017-06-02_13-56-53

mid spread:
dreamseeker_2017-06-02_13-55-58

min spread:
dreamseeker_2017-06-02_13-56-10

WEBM: https://puu.sh/w8ArE/8999940923.webm

**Comment by Intigracy** [comment]
How slightly more?

**Comment by SonixApache** [comment]
@Intigracy 
Scattershot fires C-20r rounds, so every shot is 20 damage + stun. It fires four rounds per shot. 
Buckshot is 10 damage per pellet, and it fires 9 pellets per bullet, and it fires 2 bullets per shot.
So it went from (4\*20 = 80) + stun (depending on if it actually scatters or just hits you with all 4 bullets) to (10\*9*2 = 180) without stun (depending on how many pellets hit you). It's only possible to hit someone with **all** the pellets at point blank.
See also: the post above yours, showing health bars.

**Comment by Intigracy** [comment]
This is deathsquad mech only, right?

**Comment by SonixApache** [comment]
No, this goes on any combat mech. Maybe I should halve the amount of projectiles.

**Comment by SonixApache** [comment]
okay, so now it's (10*9 = 90)

**Pull request merged**
