### PR TITLE
logs check ai laws

### PR DESCRIPTION
**Pull request by Intigracy**
logs check ai laws

### CODE REVIEW

**Comment by gbasood** [comment]
why

**Comment by Intigracy** [comment]
Because it wasn't there when I needed it to be.

**Comment by gbasood** [comment]
I just don't get what case would require knowing IF an admin used check ai laws

**Comment by Intigracy** [comment]
Besides the whole anti-cheating sentiment (e.g., admin using check laws and finding it's malf), this came about because I was wondering when/if admins checked the AI laws in http://ss13.moe/forum/viewtopic.php?f=18&t=2813 to know it was still Asimov.

**Comment by Intigracy** [comment]
tl;dr transparency

**Pull request merged**
