### PR TITLE
Ninja teleport skill now also attacks

### PR DESCRIPTION
**Pull request by SonixApache**
[update wiki]

🆑 
 - tweak: The space ninja "Teleports behind you" skill now also attacks.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
The best change

**Comment by MadmanMartian** [comment]
Isn't this what we were trying to avoid when remaking space ninja?

The insta-gib attack?

**Comment by SonixApache** [comment]
Current behavior:
Enable teleport -> click on person with sword -> end up behind person with sword -> click on person again to attack them with sword

after changes:
Enable teleport -> click on person with sword -> end up behind person with sword and attack them automatically

Do you think that's too powerful?

**Comment by MadmanMartian** [comment]
yeah, there's still the chance to stop them, rather than an auto-attack spell

**Comment by aceedex** [comment]
Since its a free hit it needs something so that spamming it soon as you can isnt the best thing to do, a delay between the teleport, reduced damage, being unable to act after landing the hit, something

**Comment by MadmanMartian** [comment]
So, this is a free double hit?

That's 80 potential damage, 40 guaranteed

**Comment by Blithering** [comment]
Maybe have them actually move there quickly rather than blink behind them? sorta like a jaunt?

**Comment by Kurfursten** [comment]
I believe the choice to make it not attack was very intentional. The ninja sword is nuts and one guaranteed hit from surprise could make this antag into an absolute monster. After they're slowed from the first attack it's hard to get away or defend one's self.

Please reconsider.

**Comment by BomberBro** [comment]
Why is the ninja getting even more inane buffs when it's already stupidly powerful? Don't balance it around newbies fluking, the ninja currently has: noslips, a free voice changer, an esword, shurikens that 2 shot the average jobbie, free reusable blink, electric zucc from any borg or APC, and other freebies. 
It's not like a ninja is a particularly interesting antag either, it's entire goal is just silent round depopulating (or loud, it's not that hard given the weaponry).

**Comment by SonixApache** [comment]
doesn't actually have noslips

**Comment by Blithering** [comment]
I was initially in favour of this PR, but I agree they really should focus less on murdering humans, and more on messing with silicons. 
For example, I think they should have their regular smokebombs replaced with EM smoke ones that make borgs that enter it temporarily have a "there is no ninja, return to your prior tasks" law added.

**Comment by Allspice** [comment]
Seems like the teleport puts your melee attack on cooldown even though it doesn't hit the dude.

**Comment by tuypo1** [comment]
Ninja SHOULD be extremely hard to beat 1v1

**Comment by SirSkeleto** [comment]
god forbid antags be scary
also note that when teleporting, your viewport changes, so you can't click them twice without having to move your mouse, and you have to be careful not to hit your own guy, so you can't quite spam click either.

**Comment by Irradiation** [comment]
Or you can target somebody's leg when you auto-hit on the teleport, which knowing the damage it deals, will instantly break it the bone and cause lmao pain slowdown, leading up to a swift combo cleanup. Or maybe it'll knock the guy on the floor immediately.

**Comment by bathosbathtime** [comment]
Automatically attacking feels hand-holdy to me.  Like it or not, clicking on the other person while not clicking on yourself is part of the difficulty of melee combat that this will partially supercede.  Further, it turns a pure utility spell into an attack while keeping the utility on one of the strongest combat antagonists we have.
I would agree with making combat easier or less janky, but not when it is only for one party.

**Comment by tuypo1** [comment]
Ninja SHOULD be nearly unbeatable one on one
If you want to nerf it focus on the shurikens.

**Comment by SonixApache** [comment]
@Irradiation you can't actually target with this spell, it auto-aims for the head as-is.
There's also the same attack delay as with anyone else. I'm considering raising it a bit for the teleport.

**Comment by SonixApache** [comment]
How about this:
- Double melee cooldown so no quick follow-up attack
- Target the chest rather than head

**Comment by tuypo1** [comment]
I don't have that much expirence with ninja so don't put too much stock in my opinion but that seems like a fair compromise to me.

**Comment by MadmanMartian** [comment]
why are you having the free-attack at all when you can just activate the daemon then attack?

don't have the game be played by the game.

**Comment by SonixApache** [comment]
Because suddenly, it goes from being a kind of useless mobility skill to being an offensive skill.
~~See also: Feint.~~ Wow, feint also doesn't attack. How pointless.

I'm not sure what you mean by 'activate the daemon then attack'.

**Comment by SonixApache** [comment]
This is a very mixed reception PR and I have some ideas on how to improve it so I'll try a V2 some time.

**Comment by Kurfursten** [comment]
I thought the latest pitch was at least serviceable.

**Pull request closed without merging**
