### PR TITLE
Makes supermatter chunks/splinters scanneable.

### PR DESCRIPTION
**Pull request by GoodG1448**
**Motive:**

Basically to have another work-around for getting/making supermatter crystals other than getting lucky with large artifacts or adminbus. In theory, it would require three different jobs to work together in order to get a crystal. The miners to get phazon/diamonds in order to print it, a xenoarchologist getting lucky finding a chunk while digging and the mechanics to actually scan them/print new ones (Engineering could be added to the mix since they have to fuse the chunks with the shard in order to make the crystal and then set up the supermatter engine with the crystal in it.

The item isn't that dangerous, only retards lose limbs if they try to pick it up even when the description says that is dangerous to do that.

[tweak]

### CODE REVIEW

**Comment by SonixApache** [comment]
i am stumped as to why you would think this is a good idea

**Comment by GoodG1448** [comment]
Supermatter cascade has the chance to be a 5% more frequent with this change. Really, the chunks are meant to be expensive to make, It is not like a mechanic will print 10 ( and we all know that mechanics not always get materials) of these and leave them in the hallways. Stepping on them doesn't do shit and you can't mass driver into other people to shard them. Hell, you can order fucking shards crates from cargo for 500$ and mass driver them if you want to.

IED bombing them might be the worst case scenario. But that's just an inefficent and expensive way to create EMPs/breach the station.

**Comment by DrSnips** [comment]
Research values are nice but if you truly wanted to set its materials you can make a design datum for it, like in anomaly, and just not give it any research requirements. This is how I gave ammolathe items fixed costs. Unless you wanted the cost to be mostly random then disregard me.

**Comment by Kurfursten** [comment]
I would much prefer for the shards to just be much more common artifact finds, like minor artifacts. Perhaps even one of the most common kinds.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
in the future plastic is such a rare and mystical material that it can create supermatter

**Comment by SonixApache** [comment]
in my canon space plastic is a mix of plasma and wood

**Comment by jknpj** [comment]
In fact, all it takes is a powergaming scientist. Trust me, this is a terrible idea.

t. got bwoinked for being a terrible humans being by finding and blowing crystals in the research outpost as traitor, making impossible for others to escape

**Comment by GoodG1448** [comment]
It would take an awfull lot of time to get manage to do all that as a single person, let alone in a single round that last 1-2 hours. Lets check:

- A xenoarch has to find a supermatter chunk in order to scan it. Technically speaking someone could powergame its way looking for tech digsites.

- A mechanic has to scan the thing and then upload the desing into the general fab. Not that hard.

- Then the miners/someone does mining have to get enough diamonds to print another 2 or 3 chunks (If 2 then it is 40 plasma, 6 phazon, 10 diamonds and if 3, 60 plasma, 9 phazon and 15 diamonds) in order to have enough chunks to form the supermatter.

           - And that if you have roundstart miners, if not then the scientist would have to build their own smelter/stacking machines + Ripley mech and do that for themselves.
           - Or a bored mechanic that has access to the research outpost.

- This means that someone has to go to the clown roid and get those materials back to the station.

- Then have the engineers move the shard to a secure room and use a  conveyor belt to feed the shard said chunks.

- The SM crystal is done.

I can make it cost even more diamonds and plasma if you are worried about people upgrading the general fab and reducing the cost. On other topic, you have MoMMers that might benefit them their autism from this.

**Comment by MadmanMartian** [comment]
Bad bad idea. It doesn't even make sense that the protolathe can now make _things that are made in the cores of gas giants_

**Comment by GoodG1448** [comment]
The tech levels required to be able to print from the protolathe it are impossible to get. AFAIK there's not way of getting anomaly past 6.

I guess I'll close it for the lack of support.

**Pull request closed without merging**
