### PR TITLE
should fix the runtimes

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by clusterfack** [comment]
Either rocks need to be made into something other than an ore, or they a material datum so we don't run into further legacy issues

**Comment by PJB3005** [comment]
Suggested fix: remove xenoarch.

A la https://github.com/Baystation12/Baystation12/issues/10170 style

**Comment by clusterfack** [comment]
Those were some pretty random links

**Comment by Midaychi** [comment]
Speaking as someone who knows xenoarch in and out, the rocks really add nothing but clutter and inconvenience. The removal of the random debris rocks produced via picking out artifacts, completely, would not negatively affect xenoarch or the server in any way.

**Comment by ComicIronic** [comment]
How else would you get muh guns?

**Comment by Midaychi** [comment]
What?
No, the debris rocks. The meatballs produced by picking with excavation picks and drills. Their removal would be fine.

If you're referring to strange rocks, then removing those would be fine too. 

The reasoning: When you excavate, the goal is to reach the exact center while the field is active at the right setting. This produces the small artifact without having to go through a strange rock.  If you fuck up and miss, the small artifact either breaks or comes out as a strange rock.

Making 'it breaks' the only outcome would not detriment xenoarchaeology, because properly digging small artifacts out does not produce strange rocks, and strange rocks have no use in xenoarchaeology besides  some minor research levels and the ability to abuse a minor bug) them to locate large artifacts. (the bug is that the signal and range of a large artifact is set on the rock core when you core it, and you can carry strange rocks around and rock core them at will.)

**Comment by clusterfack** [comment]
Yeah to be honest I'm really not sure what they are supposed to be for. They don't do anything, you could just remove them.

**Comment by Midaychi** [comment]
I think strange rocks were originally meant to be 'hey I found this caught in the ore box of my ripley' and then cael added them to normal excavating as well to make digging too shallow not be a 'lol you lose'

**Comment by PJB3005** [comment]
IIRC if you pick strange rocks up with a satchel then stick them into an ore box, they just dissapear.

**Comment by Midaychi** [comment]
Ok, proposal for removing the rocky debris tile.

Option 1, the 'maintain functionality' method:
Remove rocky debris, and instead make large artifacts come out of the mining tile when rocky debris would normally show up. Just require that the actual destruction of the mining tile be done through excavation tools, or it breaks the large artifacts. 
And no, mining with normal mining tools and getting rocky debris is and always has been 100% trolling people.


Option 2, the 'enhance consistency and difficulty' method:
Remove rocky debris, and instead make large artifacts consistent with small artifacts. That is, make excavating them work exactly like small artifacts. (As opposed to currently, where you just wail on the tile with a small mining pick till it pops out)

How excavating large artifacts would work with option 2: 

Step 1: You find the unknown signature, but this time it actually has a depth and a material type and a radius. 

Step 2: Now you need to figure out what the stats are, and then dig it out.

--- Sub-Option 1: The stats are hidden by interference from the depth scanner as they are now. You would have to get to the point where depth scanner is picking up an unknown artifact, then core the tile.  

You then take this core sample back, prep it into a sample tray, You choose what sort of carrier fluid you think it might be, and add 1 unit analysis liquid and 1 unit carrier fluid into the sample tray. 

You then run it through the ion mobility machine to see if you were right about the carrier fluid; if wrong, then go try another carrier fluid by removing the existing one with the chem master and adding a new one, if right, then proceed to the Fourier Transform spectroscope.

You then run the sample tray through the Fourier Transform spectroscope, which would have a special operating mode for when you take a core sample from the exact tile a large artifact is in; if the carrier fluid is correct it will tell you the core depth and the radius instead of the range.

Now, armed with both the carrier fluid and the core depth + radius, you can set up the field generator on the dig site, and dig the large artifact out as if it were a small artifact.


 -- Sub-Option 2: The stats are no longer hidden by interference, and you can just get the information you need to dig it out via the depth scanner.

**Comment by Midaychi** [comment]
Also, re: 
[03:26:44] <@clusterfack> I like to think rocky debris are punishment
[03:26:54] <@clusterfack> for drilling through my goddamn digsites fuck you miners
and 
[03:28:27] <Midaychi> when you break a small artifact it has a chance to spawn a stack of like 20 material

-- Remove the chance to spawn huge stacks of materials when you break a small artifact, and make destroying digsites have a 75% chance to apply the effects of the nearest unknown artifact on the breaker.

**Comment by PJB3005** [comment]
Er, midaychi, this has nothing to do with rocky debris at all, don't see why we'd need to remove them.

**Comment by d3athrow** [comment]
This isnt a fix
it's sanity.

**Comment by PJB3005** [comment]
It is now since I've removed the useless rocks that caused it.

**Pull request merged**
