### PR TITLE
Update Meteors gamemode

### PR DESCRIPTION
**Pull request by ghost**
While Meteors hasn't been remotely recognized as a gamemode for more than half a year, it's still often used by the admins as a delicate way to say "Fuck you" to the current playerbase. And while what buttons the admins press is their responsibility, it would be nice if that "Fuck you" would not terminally lag the server

Non Meteors gamemode changes : 
- Added a helper proc that checks if there are any dense objects on a turf. Useful to quickly find an empty spot to drop something on
- Meteor waves were changed to have their initial delay fire before the meteor strike, not after
- Added meteor wave naming (Using Greek because that's fancy)
- Bhangmeters, which were already useful to track what meteors were actively destroying, will now actively report information about upcoming meteor waves. Admins also get the message
- Removed camera shake on meteor explosions since explosions now shake the camera in general
- Bhangmeters will no longer vocalize small and normal meteor explosions. Only big meteors will be reported on radio. All three types still create marks on the bhangmeter

Meteors gamemode changes : 
- Cut on a lot of the waiting around bullshit. Wave is now announced 3 to 5 minutes in (down from 10 to 15). Shuttle arrives in 30 minutes (down from 45). That's a minimum of 20 less minutes spent waiting around, you're welcome
- Crew has a bit more time to prepare, from 5 to 7.5 minutes. Since this eats on shuttle time, that means the shuttle actually comes after 22.5 to 25 minutes (though it stays docked for an extra 3 minutes unless rushed)
- Fixed Meteors warning not firing most of the time
- Fix a whole lot of messages
- Meteor landmarks have been completely removed from the code. Instead, all the supplies will pick turfs in the Bar to drop in, using the aforementioned shiny new helper proc
- Supplies have been updated. The EOD closets were removed (let's be honest, a bombsuit isn't useful with hullbreaches around), EVA will be trusted for oxygen tanks and EVA gear, all the other supplies were shoved into crates and tweaked to be more plentiful (bigger material stacks, equipment in boxes to spawn more in, etc)
- Added an actual shield wall generator and added a bhangmeter drop (will simply spawn live, at worst might warrant moving, but the Bar should be big enough for maneuvering)
- Actual meteor count has been cut from (100, 200) down to (50, 100) to account for recent changes that massively improved meteor hit rate

Snapshot of the Bhangmeter at roughly shuttle arrival : 

meteors_damage_profile_new

No major lag spikes have been noticed, outside of a few suspicious runtimes here and there caused by other objects being destroyed more or less spectacularly, at worst it'll be an excellent stress test and profiler proof-test

### CODE REVIEW

**Comment by N3X15** [comment]
Code looks good. content_dense() could probably be renamed to "has_density()" or "has_dense_content()", but whatever.

**Comment by PJB3005** [comment]
Oh my oh my that bhangmeter screenshot looks sweet.

**Comment by FudgePucker** [comment]
Giving another bhangmeter and in easy access seems like a really really shitty idea.
Last time there was meaty whores someone turned on an intercom's microphone next to it and common was spammed by it to the point of lagging the game if you didn't turn off radio.

**Comment by dylanstrategie** [comment]
I'll see what I can do about it. The problem is that the current bhangmeter code, either the bhangmeter registers the explosion or it doesn't at all. I might be able to split this into "register" and "vocalize"

**Comment by FudgePucker** [comment]
Have it stop vocalizing if the explosions are too close together, if you can please.

**Comment by Probe1** [comment]
:+1: 
don't think anyone has ever been happy to see meteors but whatever its worth a shot

**Pull request merged**
