### PR TITLE
Update assistant jumpsuit to match their departments

### PR DESCRIPTION
**Pull request by bathosbathtime**
Mistakes into miracles.
This PR makes it so assistants' alt-titles change what color jumpsuit they spawn with.
Assistant = Grey
Technical = Yellow
Medical = White
Research = Purple
Cadet = Red

Compiled and tested locally.

:cl:
 * rscadd: Assistant alt-titles alters attire

### CODE REVIEW

**Comment by Inorien** [comment]
Can we have it so the jumpsuit that flashes different colours gives a random title

**Comment by Kurfursten** [comment]
I think you have it backwards Inorien. Title determines the jumpsuit, not the other way around.

**Comment by Intigracy** [comment]
You could also change armband names/descriptions and just have them spawn with a grey jumpsuit with the correctly colored armband attached.

https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/clothing/accessories/armband.dm

**Comment by toomykins** [comment]
literally every color but brown
disappointed

**Comment by Durgen** [comment]
I suspect Intigracy’s suggestion would be chosen over this one in a server vote.

**Comment by bathosbathtime** [comment]
While true, it would also have to exist

**Comment by Intigracy** [comment]
If you want one I can make one, just ask.

**Comment by Orangerush** [comment]
@Intigracy make one

**Comment by SirSkeleto** [comment]
greyshit sec - grey jumpsuit, red armband :thinking:

**Comment by bathosbathtime** [comment]
Arm bands feel too official for me, I want to keep it basic with jumpsuits that could be easily taken from the suit vending machine.
Of course, I wouldn't be against arm bands if they were introduced, I just won't go out of my way to get them in.

**Comment by Exxion** [comment]
They already exist but aren't really used much of anywhere
I think there are some on Deff?

**Pull request merged**
