### PR TITLE
[Content] Can you quack like a duck...?

### PR DESCRIPTION
**Pull request by DeityLink**
- Revamped bike horns. Their honk sound is now their hitsound, so hitting someone with a bike horn will make it honk. That also means that admins can replace that sound with anything.
- Rubber duckies finally make a quack sound, totally ripped from Duck Game. They can also be pressed twice as fast as regular bike horns since their sound is shorter.
- Bike horns' press delay is now tied to a variable, which admins can edit, so honking faster than Hokuto no Ken is now possible.

### CODE REVIEW

**Comment by clusterfack** [comment]
Haah waaw #5708

**Comment by DeityLink** [comment]
oh snap

**Comment by Intigracy** [comment]
For posterity.

**Comment by DeityLink** [comment]
@Intigracy eh?

**Comment by Intigracy** [comment]
oops I deleted it.

fixed now.

**Comment by DeityLink** [comment]
ah ok.

**Pull request merged**
