### PR TITLE
Fixes time agents needing to do RnD to finish their jecties.

### PR DESCRIPTION
**Pull request by Eneocho**
All stations have a long range AI upload instead of a regular AI upload. Time agents needed to find a regular AI upload circuit despite there being none of those stationside, meaning the time agent needed to do RnD and print their own to finish the locating since it somehow didn't inherit to the subtype.
[bugfix][oversight][hotfix]
:cl:
 * bugfix: Time agent locate objective should call for the proper AI upload circuit (long range) instead of the currently unused in any station regular one.

### CODE REVIEW

**Comment by Exxion** [comment]
1. This file is insane.
2. This shouldn't be necessary. It should already work since that's a subtype. But I assume you wouldn't have opened this if you didn't discover in-game that it didn't work?
3. Goddamn, fuck this file. If it were like seven years old I wouldn't be surprised, but files this recent should not look like this.

**Comment by Eneocho** [comment]
All the time agents that have rolled that circuit that I've seen have not gotten the jectie to work with the regular available circuit so yeah.

**Comment by DamianX** [comment]
At a glance I didn't understand why Exxion hated this file so much but the more I look at it the more I'm like...what? Why is any of this the way it is?

**Comment by pedr69** [comment]
it's in the secure part of tech storage?
at least it is on box

**Comment by Intigracy** [comment]
> 2. This shouldn't be necessary. It should already work since that's a subtype. But I assume you wouldn't have opened this if you didn't discover in-game that it didn't work?

Does locate() search for subtypes?
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/datums/gamemode/objectives/target/locate.dm#L47

**Comment by Exxion** [comment]
Yes.

**Comment by Kurfursten** [comment]
While it is true that this change should not be necessary, this will also mean that the objective has the more descriptive full name which is good

**Pull request merged**
