### PR TITLE
Add Shop Access

### PR DESCRIPTION
**Pull request by AlphaBuffalo**
When there is a shop, most of the time to keep people out of your storage room or just from stealing you stuff, you have to go to the HoP and ask for something like Silent Access because normally the Mime and the Captain have that access. I just added another one for immulsion and you can guarantee that no one else will have that access on them unless there is a power gayming assistant who stole the spare.

### CODE REVIEW

**Comment by Hikato** [comment]
A couple things I noticed:

On line #70 of access.dm, you called it "access_taxi" instead of "access_shop".

And on line #294, you have "access_Shop".  May need to lowercase the "s" on shop.

**Comment by AlphaBuffalo** [comment]
Thanks Hikato

**Comment by Hikato** [comment]
The Captain will also have the access, since, well, y'know. :P

**Comment by AlphaBuffalo** [comment]
Eh, the captain is just another power gayming assistant, but with more power.

At least in my eyes

**Comment by AlphaBuffalo** [comment]
Its the change long that keeps failing the pass again.

**Comment by PJB3005** [comment]
> Eh, the captain is just another power gayming assistant, but with more power.

I've heard that actually playing captain and bossing people around is very fun.

**Comment by AlphaBuffalo** [comment]
I always hated captain because Im not creative enough to do something fun with it. But most captains I see are just OP sec officers

**Comment by AlphaBuffalo** [comment]
wew passed this time

**Comment by ghost** [comment]
Shit man, make Shop 1,2,3,4,5. It's rare but why not if you're already at it.

**Comment by NigglyWiggly** [comment]
Why not just make Misc. 1, 2, 3 or something?
A specific access like this would be useful for more than just a shop, y'know.

<sub> Does setting door access actually work now? It's been broken for as long as I can remember

**Comment by ComicIronic** [comment]
We could create a way for the HoP to make new accesses, which would allow whatever people wanted.

**Comment by AlphaBuffalo** [comment]
Can I make a proc for that? Gives me a chance to learn procs

**Comment by Shadowmech88** [comment]
Access setting works, but it's incredibly unintuitive, making a lot of people think it doesn't work at all when they fail to do it right.

**Comment by ComicIronic** [comment]
It won't kill anyone.

**Comment by AlphaBuffalo** [comment]
WEW I made a change :dancer:

**Pull request merged**
