### PR TITLE
Maintenance Boogaloo 2: Maint additions to box by ghetto bar

### PR DESCRIPTION
**Pull request by plosky1**
Here we go again.

moneyshot1

This is a picture of the overall changes. First thing to note is that pod bay has been moved to arrivals and detective's office has been moved to the other side of sec hallway. The rest of maint has been connected to the maint underneath det's office. There has also been a connection to the end of security hallway. Multiple rooms have been added, and solars left alone except for being moved. A hole was left for detective's to look out into space and feel gloomy because reasons.

moneyshot2

This is a close-up of the actual maint changes. Backroom for ghetto bar has been expanded. Ghetto bathrooms has been moved. A monkey gym that contains gym stuff found on roid but not on box has been added. A plasma shelter with windows looking out into hallway has been added. A ghetto kitchen south of the extended ghetto bar backroom has been added. A literal maint cave has been added for Grug. The bee lives on in the ghetto bathrooms secret room. A joy mask for even more controversy

[box]
[controversial]

:cl:
 * rscadd: Extensive additions to box maint by ghetto bar to security hallway. Pod bay was also moved to arrivals.

### CODE REVIEW

**Comment by kilozombie** [comment]
Reeeeally don't like the look of Maint on this one, chief. It's even more rectangular and bland than the last proposition.

**Comment by plosky1** [comment]
I took accip's idea and used it while moving space pods. Yes, the exterior shape is bland but trying to do exciting ideas for big maint changes on box is near impossible to do, let alone with exciting shapes. The intent behind this change is to spice up maint with more rooms while increasing connectivity. This accomplishes that goal.

Also it _is_ box station 😏

**Comment by kilozombie** [comment]
You don't have to make your maint look like it has no effort poured into it just because it's Box.

**Comment by plosky1** [comment]
Of course. However in my 4 part series of box maint overhaul, this part of the station is impossibly to modify without becoming a tumor if you dont stay close to the stations original shape. So while is is a flat line and relatively boring from the outside, it matches up to sec hallway very nicely while still achieving the goals I set out to do. There’s been a lot of work done on the interior and for this situation I think thats what matters.

Also my comment before of ‘it is box’ was in reference to that its in the shape of a box, on box station.

**Comment by kilozombie** [comment]
image
If you are planning on renovating the interior, this is where I'd start. There's very little polish here and while the shape is interesting, it's just kinda *there* without much development.

image
I don't care if it matches up to the sec hallway very nicely, it's so flat that it looks bad.

**Comment by Hoshi-chan** [comment]
What a brilliant way to remove box from the rotation. Slowly make PRs that make it so shit that even box babies don't want to play on it.

**Comment by SonixApache** [comment]
Maint with no pipes or wires isn't maint, it's just a shitty hallway. I understand what you're trying to do, but it looks bad.

add a maint door into arrivals, upper section
add a maint door into the pod bay
remove the fucking emoji mask

If you're going to stick with the detective feedback, maybe do the sensible thing and just move his office to the north side of the hallway so you don't have to make giant square meme windows in the middle of maint.

**Comment by GoodG1448** [comment]
This is my take on it:
58072613-dbbcaf00-7b65-11e9-9102-cb5747ec73c2

I guess you could make an star gazing room/crappy greenhouse (marked oragen, yellow dots are chairs) to avoid that L shaped angle to make it look less boxier or expand the bar a little bit and add some chairs and tables next to the windows (marked green). Maybe add one of those maintenance storages just south of the star gazing room.

One of my concerns is the lack of an airlock by the wall marked in purple. Also, the bar backroom is unnecessarily big. Other right chunk of the meme space box could be used as a barred/unused interrogation/torture room, maybe make the dectective's window out of smartglass and put a switch in his office linked to the windows.

**Comment by Kurfursten** [comment]
I'm liking the new position of the emergency plasma shelter a lot. Consider slapping an external airlock on it so that it seals better against atmos leaks.

**Comment by iFlashYou** [comment]
>boxbabies dont want to play box anymore because a bit of maint got added

**Comment by FudgePucker** [comment]
>People complaining about the maintaiance looking a little too box-y

>On box station

Uh, guys.

**Comment by FudgePucker** [comment]
I like it, one concern about the ghetto bar though, are those buttons on the wall or the table?

**Comment by plosky1** [comment]
Ill be making some of the changes suggested here soon.

**Comment by Lokiamis** [comment]
I think stuff like grassy caves and emoji masks look terrible. There's a fuckhuge 8x8 walless flat area because of the rage cage. And a monkey gym? It doesn't look like a maintenance tunnel. Just too goofy for my tastes.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
maintmonkey shit needs to stay in deff

**Comment by plosky1** [comment]
moneyshot1
moneyshot2

Big changes

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Isn't "gym loot" some strong stuff you have to go through a vault to get?

**Comment by plosky1** [comment]
Yep you're right. Removing it.

**Comment by SonixApache** [comment]
image
Put this door slightly higher so you can get in it when the firelocks are down.

Apart from that, this is as good as you can get it, I think.

**Comment by plosky1** [comment]
Done, pictures updated.

**Comment by bathosbathtime** [comment]
I dislike the detective office nearly touching the brig.
We need every possible reminder that the detective isn't an officer.

**Comment by plosky1** [comment]
On an instinctual level of hate for sec I agree, but it's got its own maint and view into space to contemplate life choices so I think it's ok.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Readd the mousetrap box in ex-secmaint

**Comment by plosky1** [comment]
#22997 and #22882 ? If so, that doesnt conflict, whichever gets merged first will just have to change those rwalls to regular walls.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
No, the maint room with the circular bins that used to be under box infirmary
It had a very fun mousetrap box that is now gone

**Comment by plosky1** [comment]
Ah hmm. I'll find a place to put it in.

**Comment by plosky1** [comment]
rattrap

Updated

**Comment by kilozombie** [comment]
image
How is this even real? This is just horrible and pointless map design. This looks like a joke section we'd put on Ladderstation but it's not even funny, it's just a pointless loop with a pointless window.

Put more clutter in! Put more purpose into areas! Don't just make hallways and be done with them.

**Comment by plosky1** [comment]
Added clutter and fixed hallway. Checked over other areas and it appears to be fine but any advice or suggestions are always welcome.

moneyshot2

**Comment by ShiftyRail** [comment]
I don't believe this and the brig rework will conflict, brig is way up North and it only conflicts if we're touching the same line.

**Comment by Kurfursten** [comment]
You might be surprised what can conflict. Sometimes it decides to encode lines in a different order.

**Comment by groosbstrd** [comment]
I don't like it

**Comment by bathosbathtime** [comment]
Server Poll:
http://ss13.moe/index.php/poll/189

**Comment by plosky1** [comment]
small update via request 
test1

**Comment by Kurfursten** [comment]
I like downfacing detective office, not sure how I feel about -1 airlock separating brigbay from maint though

**Comment by plosky1** [comment]
brigbay1

as per instructed, two doors now for maint breaker to get through. door to perma brig was also pushed up.

**Comment by Kurfursten** [comment]
Right arm of the maintenance one: top right maint remodeled, added chapel morgue, ghetto theater, etc
Right leg of the maintenance one: bottom right maint remodeled as toxins goes away
Left leg of the maintenance one: Bottom left maint changed to accommodate Tcoms renovations
Left arm of the maintenance one: this PR

Be careful, I am pretty sure the next box PR is going to change the AI core into maint

**Pull request merged**
