### PR TITLE
Changes Assassinate to use special_role if needed

### LINKED ISSUE #12233: ERT members can be chosen as cult sacrifice targets
Wouldn't be so weird on its own, but the job title they're given in the objective description is listed as MODE
Presumably the same happens with deathsquad, but I'm talking out my ass for that.
image

### PR DESCRIPTION
**Pull request by Kammerjunk**
Fixes #12233 
Currently, assasinate/cult sacrifice objectives go solely off of `target.assigned_role` and `sacrifice_target.assigned_role` respectively which, if special roles like ERT members or wizards are in play, will make the objective read "Sacrifice/Assassinate Big McLargehuge, the MODE."
This changes it to use the target's special_role (which seems to be designed specifically for this) if the assigned_role is MODE by ripping off someone else's work in code\datums\mind.dm
I'm at a loss regarding how to test the cult part of it, so if anyone can assist there, that'd be super. I can't seem to select the game mode datum using SDQL (I guess you can't select datums?) and there's no link to it in the cultists' minds.

### CODE REVIEW

**Comment by Kammerjunk** [comment]
Wait dammit I forgot to change the title.
I don't suppose that's possible now

**Comment by Exxion** [comment]
The title of the PR? Just click the edit button to its right.
If you mean a commit message, no you can't change that, but nobody gives a fuck

You can always change a PR's title, but make sure to never name it anything too embarrassing because there will forever be a record of all its previous titles

**Comment by Kammerjunk** [comment]
Right, well, before I do that, then, I know this is also a thing that happens in ragin' magin' because wizzes are also MODEs. I don't suppose it'd be unatomic to fix that here too.

**Comment by Exxion** [comment]
Nobody actually cares about atomicity with bugfixes
I mean a PR containing multiple bugfixes is fine as long as the bugfixes are actually just bugfixes and don't affect balance or something in any significant way, and also it's ONLY bugfixes

There are exceptions to that which are hard to explain succinctly
But generally fixing multiple minor bugs in the same PR is fine, especially if they're related like these ones are

**Comment by sonime** [comment]
You could test this by shoving a ckey into a random mov and giving yourself the assassinate objective. That should hopefully give the other mob as the target.

**Comment by Kammerjunk** [comment]
wizarding
That was certainly easier to test.

**Comment by Kammerjunk** [comment]
@sonime Works great for stuff like wiz, but cult is ~unique~ regarding objectives.

**Pull request merged**
