### PR TITLE
gold Atmos suits bugfix

### PR DESCRIPTION
**Pull request by ghost**
i summon my inner c*der to NERF THEE

previously the suits could hold ANY WEAPON TYPE and bags of holding what the fuck
instead of trashing them so that even less people ever use the gold suits they can hold toolboxes instead of everything

:cl:
 * rscdel: Gold atmos suits can no longer hold EVERYTHING but they will still be able to hold toolboxes

### CODE REVIEW

**Comment by DamianX** [comment]
delet this:

- I'm going to get a conflict on my PR
- You can hold TOOLBOXES ???
- The default `allowed` list for `/rig`s seems fine to me, probably no need for the snowflake

**Comment by ghost** [comment]
TOOLBOXES yes MORE storage but you're more slow

**Comment by PJB3005** [comment]
Might as well port duffelbags tbh.

**Comment by carshalash** [comment]
image
I think somebody already did that a long time ago.

**Comment by Exxion** [comment]
Put a space between the asterisk and rscadd in the OP

**Comment by PJB3005** [comment]
@Exxion you know collabs can edit PR bodies right.

**Comment by Exxion** [comment]
Yes, but I'd rather tell him that so he knows in the future so I don't have to do it every time.

**Comment by SonixApache** [comment]
mistakes were made, but it was fun while it lasted
image image
image image image image

**Comment by Intigracy** [comment]
I see nothing wrong with this.

**Comment by Blithering** [comment]
This probably went so long without being noticed because noone uses the storage slot for anything but airtanks.

**Comment by DamianX** [comment]
```
>he doesn't put the socket wrench in there
>he doesn't switch between RPD and socket wrench with the quick equip
```

**Comment by ghost** [comment]
>everyone shoots it down

O k

**Comment by gbasood** [comment]
@Commandersand just change it so it cant hold literally every weapon
use sonix's screenshot to showcase why

**Comment by SonixApache** [comment]
Just replace the last item in the list with toolbox.

**Comment by ghost** [comment]
why didn't you just say that earlier ¯\_(ツ)_/¯

**Comment by ghost** [comment]
>holds pickaxes

??????????????????????

**Comment by SonixApache** [comment]
unfuck the slowdown

>holds pickaxes

we just don't know

**Comment by ghost** [comment]
done fam

**Comment by ghost** [comment]
wait did i do it right

**Comment by SonixApache** [comment]
👌

**Comment by Shadowmech88** [comment]
The bug has existed for three years, since this commit by N3X15: https://github.com/vgstation-coders/vgstation13/commit/60b69ddf1ee182b1c8724cef356dd96bfde2dd69

**Comment by SonixApache** [comment]
You can close this PR, since we now know *who the fuck coded gold atmos suits*.

**Comment by ghost** [comment]
nani

**Comment by SonixApache** [comment]
@Commandersand the 'helpful' title of this PR + shadowmech's last post

**Comment by ghost** [comment]
So Really just close it and leave the suits as they are?

**Comment by SonixApache** [comment]
no, change the title to not be stupid

the commit message and branch names are also stupid but that's for next time

**Comment by gbasood** [comment]
also your changelog entry is fucked
`rscdel` is what you want

**Comment by Exxion** [comment]
I'd say `tweak` personally

**Comment by ghost** [comment]
Why the fuck does this have so many reddit downvotes?

**Comment by Exxion** [comment]
It's worth noting that `/obj/item/weapon` isn't just weapons. It's the majority of all items.

**Comment by gbasood** [comment]
@Unknown-as-Captain did something different before

**Comment by Shadowmech88** [comment]
What did it do before?

**Comment by Blithering** [comment]
Added more slowdown

**Comment by Shadowmech88** [comment]
Well, we can't be sure which votes are from that and which are from the current change.
I personally voted against the current change, for example.

**Comment by Exxion** [comment]
You voted against not allowing it to store nearly anything worth storing?
It could store the fucking battering ram unless twohand code prevents that (which I don't think is the case, though I could be wrong)
Given the same condition, it could store Ian
Literally any storage item
Many other things

In its current state, its entire list of allowed items is redundant except three entries because the last entry is so all-encompassing

**Comment by Shadowmech88** [comment]
My position is indefensible.
I just personally like the bug and think it's funny.

**Comment by Exxion** [comment]
Fair enough, I guess

**Comment by ghost** [comment]
This PR shouldn't even be tagged balance, it's a hotfix.

**Comment by SonixApache** [comment]
It can't store corgis, I've tried.

**Comment by Intigracy** [comment]
@Unknown-as-Captain `did something different before`

**Pull request merged**
