### PR TITLE
Box: E/W airlocks before upload now equally spaced

### PR DESCRIPTION
**Pull request by Inorien**
## What this does
Moves the airlocks and firelocks east of AI upload one tile to the west each

Before:

image

After:

image

## Why it's good
looks cleaner by accounts of many

## Changelog

 * tweak: Box: Moved airlocks in front of AI upload

### CODE REVIEW

**Comment by Inorien** [comment]
whoa why is it -1,600,000 deletions
i literally just did nudge-west on 6 objs

**Comment by Kromkar** [comment]
> whoa why is it -1,600,000 deletions i literally just did nudge-west on 6 objs

Try 1,644,720.

**Comment by ValkyrieSkies** [comment]
> whoa why is it -1,600,000 deletions i literally just did nudge-west on 6 objs

Aren't we not supposed to use nudge or some shit?

**Comment by Inorien** [comment]
i tried again using StrongDMM and enabling tgm format, this time using explicit creation/deletion of objs rather than nudging
now there's less fucked up diff but its still really fucked up

**Comment by Inorien** [comment]
ok i unfucked it now

**Comment by Kromkar** [comment]
It looks like you fucked up some Atmos pipes in the process.

**Comment by Eneocho** [comment]
the PR that saved /vg/

**Comment by Lokiamis** [comment]
I really hope nobody with autism looks at this picture

ss13

**Comment by ErrorsWindows** [comment]
this change: 👌 👌

**Comment by pedr69** [comment]
what am i supposed to be seeing in the red circled areas?

**Comment by Inorien** [comment]
> what am i supposed to be seeing in the red circled areas?

the tile colours aren't symmetric

**Comment by tinysaturn** [comment]
sovless

**Pull request merged**
