### PR TITLE
Changed all relative paths to absolute

### PR DESCRIPTION
**Pull request by DamianX**
I've deleted unused procs as I encountered them. Nothing else has been changed.

### CODE REVIEW

**Comment by ghost** [comment]
probably should just comment out unused procs

**Comment by DamianX** [comment]
Why?

**Comment by Eneocho** [comment]
Because someone may find an use for the unused procs.

**Comment by Exxion** [comment]
That's what Git history is for
Also you don't find a proc and make a feature around it, you make a feature and find/create procs to support it

**Comment by DeityLink** [comment]
I agree with Exxion in principle, but sometimes finding unused procs is great food for ideas (that you can then implement with a better proc). And nobody ever checks git history. The removed procs are virtually invisible unless another coder tells you they existed.

**Comment by Kurfursten** [comment]
confl

**Pull request merged**
