### PR TITLE
Fixes secondary main power and secondary backup power wires in airlocks

### PR DESCRIPTION
**Pull request by 9600bauds**
Airlocks have two main power lines (aka test wire) and two secondary power lines.
However, only one of each of those wires worked when pulsed. This is why the term "test wire" is singular in game lingo: If you use a wirecutter to test the wires, you'll see that there are actually two main power wires, however, only one of them will actually work with a multitool (which is the most popular hacking choice).
What does this fix mean?
Yes, it will be twice as easy to find the test wire with a multitool, since there will actually be two like there were intended to be. Yes, you will be more likely to find the test wire than the shock wire. I am so, so sorry.

### CODE REVIEW

**Comment by PJB3005** [comment]
>[warning] [long-overdue bugfix that is inadvertently balance-altering due to broken code legacy warning] Fixes secondary main power and secondary backup power wires in airlocks not doing anything when pulsed [Balance] [HONK]

**Comment by SangriaMonkey** [comment]
A one in four chance to open any door, and then any number of doors afterwards isn't a smart idea.

**Comment by PJB3005** [comment]
Aw, riri ruined all the fun

**Comment by Exxion** [comment]
Buzzkill

**Comment by clusterfack** [comment]
Add two new wires you scrub

**Comment by 9600bauds** [comment]
~Prease undastandu that this is not some sekrit greytide agenda push, I just so happen to be the unlucky sod to accidentally find this absolute landmine of a bug and now is unfortunately in charge of fixing it~

That said: There were apparently always meant to be 2 of each wire. And in fact, you can still access both of them by cutting the wires rather than pulsing them: even live in the server right now, you can use a wirecutter rather than a multitool and instantly double your chances of hitting a test wire.
Is it silly that there are 2 of each wire? Sure, but I don't want to bear that weight if I add something stupid like an alert AI wire and everyone turns out to hate it and my name is echoed across the ages as the only man worse than goof.

**Comment by clusterfack** [comment]
Well it may have been silly that there were 2 of each wire, but at least they had some distinction, now they are identical. I almost wonder if the fact there was 2 of each wire was a mistake due to the fact there was meant to be 2 wires main/backup.

But either way, if they are just going to be identical anyway may as well remove them and add something else.

I'd think you could add some fun ones if you thought, off the type of my head you could add a wire to prevent the airlock from becoming airtight after closing.

**Comment by PJB3005** [comment]
@clusterfack, that no air seal wire is just evil.

**Comment by clusterfack** [comment]
@PJB3005 Of course there should be some kind of overlay/icon to show that it hasn't fully closed

**Comment by 9600bauds** [comment]
See, that's why I'm the unfortunate sod to bump into this bug. I've never played Sec, so I don't know how Sec deals with people hacking wires. I'm not the person to think of some new wire functionality because I have no guarantee that it's proper or that people will even want it.

The code and the wiki have stated for years (I'd love to hear an estimate on how long this has been broken) that there are two main power and two backup power wires... did nobody ever question this in all those years?

**Comment by SangriaMonkey** [comment]
Sec doesn't. Can't. The most they can do is try to recover the stolen property (hah) or screwdrive the door for the victim. You might luck out with a detective scanner but even then you can only brig the theif in a fishbowl for a few minutes which hasn't actually deterred anyone from doing anything ever. 

If this goes through you're going to enable anyone with the nerve to effortlessly glide through anywhere without even grabbing a multitool.

**Comment by 9600bauds** [comment]
>If this goes through you're going to enable anyone with the nerve to effortlessly glide through anywhere without even grabbing a multitool.

You gotta logically back up those claims when you make them. Especially the "without even a multitool" part, which sounds a little weird since this bug is literally ONLY with multitools.

**Comment by SangriaMonkey** [comment]
I guess I misread something but the point stands. People already hack around like fucking crazy. Why make it easier?

**Comment by 9600bauds** [comment]
That's what I'd like to ask whoever fucked this up years ago, whose fuckup comes to haunt me in this day

**Comment by Shadowmech88** [comment]
I'm not sure whether this was intended behavior, but when hacking doors I've noticed that both power wires are currently useable with a multitool, in different stages. The distinction is that one power wire is only shuts off the power when pulsed if the door is completely powered, and the other power wire only shuts off the power when pulsed if the door has just recovered its power from having the first wire pulsed. So when people initially go through the wires to find the test wire, they overlook the second one since it has no effect on the unhacked door, but knowing it can be handy since it'll let you immediately cut power to the door again with a multitool as soon as the power comes back to the door, instead of having to wait 10 seconds or however long it is before the first wire becomes usable again.

**Comment by 9600bauds** [comment]
Those are the primary and secondary power wires, the thing is that there's actually two of EACH. You can test that with a wirecutter.

**Comment by clusterfack** [comment]
New door wires WHEN

**Comment by ComicIronic** [comment]
Just bump wire_count up by 2 or 3 to compensate, and I'll mark this NFD

**Comment by 9600bauds** [comment]
I'd rather have two wires that do nothing for multitools than make hacking easier and have two wires that always do nothing.
I don't really want to add new wire functions because that's almost guaranteed to end up not working in my favor. I'm not terribly attached to this PR anyways.

**Comment by d3athrow** [comment]
>There were apparently always meant to be 2 of each wire

No there was a main power and aux power wire. If you cut main power aux would take over in about 30 seconds. if you cut both the door would never open/close after that.

**Comment by ComicIronic** [comment]
Then how do you explain the code

**Comment by d3athrow** [comment]
>Then how do you explain the code

Probably some shitty relic from bay12's luna code when they ported their shit to -tg-station code. tgcode has always had 1 main power wire and 1 auxillary power wire.

**Comment by 9600bauds** [comment]
TG code has the same bug tho

**Comment by ghost** [comment]
Wew that bump

**Pull request merged**
