### PR TITLE
Removes ponies from possible clown names.

### PR DESCRIPTION
**Pull request by carshalash**
The memelord giveth and the memelord taketh away.

### CODE REVIEW

**Comment by clusterfack** [comment]
Why though

**Comment by carshalash** [comment]
My man, she's not even a good one like applejack.

**Comment by 9600bauds** [comment]
I didn't even know this was a reference to something

**Comment by clusterfack** [comment]
It isn't

**Comment by ihadtoregisterforthis** [comment]
:+1: I remember seeing this removed a while ago.

**Comment by carshalash** [comment]
http://mlp.wikia.com/wiki/Scootaloo 

Literally a horse.

**Comment by Probe1** [comment]
How do you know someone watches MLP?

Don't worry they'll tell you.

**Comment by clusterfack** [comment]
This name is far older than MLP, removing it because some show you dislike (or like enough to know a minor side character it seems) has been created in the meantime is silly.

**Comment by SkowronX** [comment]
Meme PRs are my favorite

**Comment by BestName** [comment]
@clusterfack 
sieppaa

sieppaa2

**Comment by CptWad** [comment]
god forbid removing ponyshit becomes [controversial]

**Comment by Imagebard** [comment]
Just merge it

**Comment by 9600bauds** [comment]
> This name is far older than MLP, removing it because some show you dislike (or like enough to know a minor side character it seems) has been created in the meantime is silly.

chrome_2016-04-22_15-09-17
chrome_2016-04-22_15-09-43

This is pretty open and shut if you ask me
Unless Clusterfack has an aunt named Scootaloo or something

**Comment by TheEliminator16** [comment]
Something something Barneyfag something something

**Comment by SangriaMonkey** [comment]
:horse: :gun:

**Comment by Boxe** [comment]
to be fair, hypothermia and cancer both got merged despite their controversy.

**Comment by Senaat1** [comment]
:+1:

**Comment by Imagebard** [comment]
>if you don't setup your name we'll give you a MLP one

Honk

**Comment by ghost** [comment]
So, everybody's scared of this name because it's associated with MLP?

This is some silly logic right here

**Comment by Boxe** [comment]
well hey if this PR doesn't get merged just remember to make a new ckey called Scootaloo and ban evade constantly while fucking up rounds

eventually someone will remove the name from the clown defaults :)

**Comment by DeityLink** [comment]
Funny coming from a website that has a fucking /mlp/ board.

**Comment by Boxe** [comment]
>Funny coming from a website that has a fucking /mlp/ board.

you realize that /mlp/ is a containment board right

**Comment by 9600bauds** [comment]
that's like saying "funny coming from a game with a /vore/ server"

**Comment by DeityLink** [comment]
Right, looking at it this way, every board but /vg/ is a containment board, and every thread but /ss13g/ is a containment thread as well.

**Comment by chatsonf** [comment]
I can't find any evidence of a non-pony related scootaloo in my time searching it
Even before the MLP show came out scootaloo was a name of one of their ponies.
All this name can cause is silly "kill the pony lover" stuff.

**Comment by Boxe** [comment]
>Right, looking at it this way, every board but /vg/ is a containment board, and every thread but /ss13g/ is a containment thread as well.

no it's legitimately a containment board

do you not understand its history

**Comment by DeityLink** [comment]
Why is this even an issue? Why are people arguing whether scootaloo is a pony or not? Who gives a fuck? TF2 has pony references, lots of game have pony references, even our code has undertale references now. Genetics has homestuck references, SS13 is literally a meme game filled with references. Why are pony references in particular an issue? It's not the removal of that feature that bugs me, it's that the idea even crossed your mind.

Well if what you wanted was to make a controversial PR then that's a success.

Also "I bring my memes into your game and removes the memes I don't like", literally.

**Comment by mikecari** [comment]
Carshalash is just a greytiding memeshitter trying to start shit as always. Why you keep giving this guy so much leeway I'll never know.

**Comment by NigglyWiggly** [comment]
> even our code has undertale references now

You added those you fucking goober

**Comment by 9600bauds** [comment]
It's worth noting that some people expressed distaste for the undertale references too

**Comment by DeityLink** [comment]
Yes I did :^)

But I didn't remove references from a show I didn't like at the same time.

**Comment by chatsonf** [comment]
We've already been toning back down on references already (see #9315)
And most people are fine with references that are generally enjoyed
MLP is generally disliked, which is why a good amount of people would rather have the option gone.

The biggest problem is that people who get random clown names are going to be new, and they won't like being treated like a piece of shit just because they happened to roll a random name now associated with my little pony.
If they choose their name to be related to scootaloo that's fine, they know what will come of it.

**Comment by DeityLink** [comment]
You do know that clowns set up their names at round start right? It's just one of the "suggested" default names that are set if you don't wanna choose a particular name.

**Comment by NigglyWiggly** [comment]
Oh yeah speaking of which.
Remove undertale references fucking when

**Comment by chatsonf** [comment]
Yeah I do know, change the part "get random clown names" to "choose the random given clown names" and my argument still holds.

**Comment by DeityLink** [comment]
> round starts
> game asks you "do you wanna be called scootaloo?"
> player says "nah, I'll call myself Cacadoizo"

the end.

**Comment by Senaat1** [comment]
We should remove all the Homestuck references as well tbqh famiglia smh

**Comment by chatsonf** [comment]
> round starts
> be new player and decide being a clown would be fun
> game asks you "do you wanna be called scootaloo?"
> player can't be arsed to think of anything better and says "Welp I am going scootaloo then"
> ends up getting bullied by greyshitters thinking they like mlp
> decides to stop playing cause of a shitty first round

There's literally no benefit to having scootaloo in the suggested names, while most of the time it won't matter, when it does it can seriously ruin someone's day

**Comment by gobblecoque** [comment]
> defending homestuck and tumblrtale refrences
> absolutely haram

**Comment by DeityLink** [comment]
That's it Furbeh, I'm forever associating you with "that one spessmen that always thinks of highly improbable scenarios with improbable results as arguments to reject new ideas".

Let's list the key points this time shall we?
- Guy that plays SS13 for the first time ever
- On vgstation
- Chooses clown for his first round despite all the guides recommending that you go assistant or service jobs
- The random name that the game gives them is Scootaloo
- They happen to not know that the name is associated with MLP
- They decide to keep the name
- They come across people who would bully them just because of their name, EVEN THOUGH BULLYING THE CLOWN IS PART OF SS13 CULTURE
- They would stop playing forever because of that experience, without telling the admins, or trying another job

Jesus christ furbeh

**Comment by Senaat1** [comment]
Why not just remove it in an effort to remove more random references nobody asked for? Remove the homestuck horns as well, if those aren't gone yet.

And everything else homestuck.

**Comment by TheEliminator16** [comment]
Agreed. Leave the horns, just resprite them to not be Homestuck.

Though, the game is heavily built on references, we just need to decide which ones are the ones we actually want.

**Comment by 9600bauds** [comment]
Do the homestuck horns even do anything?

**Comment by Senaat1** [comment]
Make you look like a retard, mostly.

**Comment by 9600bauds** [comment]
I mean besides the cosmetic effect

**Comment by DeityLink** [comment]
/datum/dna/gene/disability/horns
    name = "Horns"
    desc = "Enables the growth of a compacted keratin formation on the subject's head."

That's literally it. They don't do anything, they don't interact with anything. They allowed people to have a Punished Snake MGSV event a while ago.

**Comment by chatsonf** [comment]
This isn't me rejecting an idea, this is me supporting an idea.
Also crazier things happen in SS13, don't write things off just because they seem highly unlikely, that's how you make greentext.

Is there any reason to keep scootaloo as a suggested name? Variety? Replace it with a few more clown names, like Chuckles or Pickles or Krusty or something.

**Comment by DeityLink** [comment]
Why do you need to remove names as an excuse to add new ones?

> Is there any reason to keep scootaloo as a suggested name?

Is there a reason to remove it? beside "muh mlp"

**Comment by chatsonf** [comment]
I am just trying to figure out why people would rather not remove a name that gives no benefit of its existence.

**Comment by DeityLink** [comment]
Is this some troll logic? Come on, it's not any name we're trying to remove is it? Otherwise I wouldn't be writing the 50th post of this PR.

**Comment by Shadowmech88** [comment]
Many of the clown names could be argued to "not give any benefit to their existence." They're just names.
I doubt the game would be seriously impacted even if we removed ALL the suggested clown names and just made every clown's default name "Honkers." Most clowns write in their own name anyway.

However, the fact that all the names are "useless" is still not a reason to remove them. They don't hurt anything by being there.

**Comment by chatsonf** [comment]
I just gave an example where "scootaloo" can cause a bad scenario, even though it is highly unlikely.

**Comment by DeityLink** [comment]
you're talking about the scenario that I just proved how implausible it was just a few posts ago right? Eh, alright, I'm getting to tired for this shit. goodnight.

**Comment by MusgardTiger** [comment]
Giving a single fuck about any of this is one of the major symptoms of being a dumbass.

t. Mustard Tiger MD (meme doctor)

**Comment by Praecordia** [comment]
do you ever wonder how we get 50 comments on a meme PR and no comments on actual PRs?

**Comment by Senaat1** [comment]
Shitposting.

:100: :+1: :eggplant: :ok_hand:

**Comment by clusterfack** [comment]
I'm not understanding all this anti-clown bullying sentiment here, clowns are there to be bullied.

**Comment by DeityLink** [comment]
@Praecordia He's still far from my high-score. Take grain, this is how you make a true meme PR: https://github.com/d3athrow/vgstation13/pull/1938

**Comment by Boxe** [comment]
:eggplant:

**Comment by chatsonf** [comment]
Standard Clowns are friends, not punching bags
The ones that spray space lube and bananas everywhere deserve it though

**Comment by chatsonf** [comment]
The real question though is does clusterfack have an aunt named scootaloo

**Comment by Senaat1** [comment]
deity present the family tree

**Comment by clusterfack** [comment]
When I die my final words will refer to my favorite toy scooter, scootaloo.

**Comment by SangriaMonkey** [comment]
> star wars is bad but shows about gay horses are okay

:eggplant: :eggplant: :eggplant:

**Comment by Senaat1** [comment]
your mother is a gay horse

**Comment by NigglyWiggly** [comment]
Remove Homestuck references
Remove Undertale references
Remove MLP references

**Comment by DeityLink** [comment]
Remove librarian, it's a meme job anyway.

**Comment by NigglyWiggly** [comment]
That has literally nothing to do with anything in this entire PR.

**Comment by Senaat1** [comment]
are you okay, deitylink?

that was kinda weak

**Comment by Boxe** [comment]
>Remove librarian, it's a meme job anyway.

:eggplant:

**Comment by DeityLink** [comment]
I'm not good at making memes, sorry Senaat.

**Comment by MusgardTiger** [comment]
Next time on Github: "Star Wars enthusiast crusading for the removal of Star Trek medicine references from the code"

**Comment by chatsonf** [comment]
God unrelated, but one of the worst mistakes was allowing my friends to choose their own jobs when they wanted to try playing.
They ended up being chaplain and librarian and didn't know what the fuck to do.

**Comment by carshalash** [comment]
Oh god christ it's up to 70 comments. I'm closing this, I created a monster.

**Comment by chatsonf** [comment]
NO BRING IT BACK IT HAD SO MUCH TO LIVE FOR

**Comment by DeityLink** [comment]
Bartender is the best first job. You don't have any obligations, but crewmembers are still going to come to you with requests. That way you learn how to use your hands, and no wait Carsha I was still talki.......

**Comment by TheEliminator16** [comment]
YOU CAN'T CLOSE THE CONTROVERSY

**Comment by Boxe** [comment]
:eggplant:
 :woman:
 :cry:

**Comment by Senaat1** [comment]
Someone ban Furbeh for metagaming

**Comment by carshalash** [comment]
FUCKING CHRIST WHAT DO YO PEOPLE WANT

**Comment by Boxe** [comment]
:eggplant:
:woman:
:smile:

**Comment by SangriaMonkey** [comment]
We want the :eggplant:

**Comment by MusgardTiger** [comment]
NO BREAKS

**Comment by Senaat1** [comment]
:eggplant:

**Comment by DeityLink** [comment]
So as I was saying, you should have told them to play bartender, plus it's a good introduction to reagents, and can then proceed into chemistry. Also it teaches you to protect Pun Pun.

**Comment by Senaat1** [comment]
HIGH RESOLUTION MEMES

**Comment by NigglyWiggly** [comment]
Why is this controversial in the slightest

**Comment by DeityLink** [comment]
You guys know that they're making an actual emoji movie? jesus christ

**Comment by Senaat1** [comment]
they should cast me as the :100: :eggplant: character

**Comment by MusgardTiger** [comment]
+

https://github.com/Senaat1

# 

dic pic

**Comment by clusterfack** [comment]
Because its completely subjective and requires zero technical knowledge to understand? Everyone should know by now parkinson's law of triviality.

Also you just asked me to add it spurdos now you're removing this? Make up your mind people pro meme or anti meme.

**Comment by 9600bauds** [comment]
This is the ultimate proof of parkinson's law of triviality

**Comment by Senaat1** [comment]
gondola job when

**Comment by DeityLink** [comment]
> not wanting to be the :joy: :ok_hand: character

**Comment by carshalash** [comment]
I'm so sorry.

**Comment by Boxe** [comment]
:eggplant:       | :eggplant: :eggplant:

:eggplant: :eggplant:  |  :eggplant: :woman:

**Comment by Exxion** [comment]
> 91 comments when I clicked this god damn fucking issue name
> 95 now, perhaps as much as a minute later

**Comment by NigglyWiggly** [comment]
Boxed I'm going to fucking hurt you

**Comment by Senaat1** [comment]
we need a "spicy meme" emote

**Comment by 9600bauds** [comment]
I figure this is a good time to ask: When's the metaclub's weekly duck game match? I don't have anyone to play it with

**Comment by SangriaMonkey** [comment]
# _intuitive memeing_

**Comment by MusgardTiger** [comment]
P A R K I N S O N ' S 

L A W 

O F 

S H A K I NG

**Comment by DeityLink** [comment]
YOU PLAY DUCK GAME?

**Comment by clusterfack** [comment]
We should all get together and play risk of rain.

**Comment by Exxion** [comment]
YES PLEASE

**Comment by Senaat1** [comment]
You guys should play FFXIV with me.

**Comment by Boxe** [comment]
hold on let me launch RoR and i'll host

**Comment by DeityLink** [comment]
I've played RoR with Velard a year or so ago.

Anyway bauds, add me on Steam http://steamcommunity.com/id/DeityLink/

**Comment by carshalash** [comment]
It's 100 comments, I never asked for this. This is more controversial than hypothermia.

**Comment by DeityLink** [comment]
Don't you need Evolve to play RoR multiplayer properly?

**Comment by Boxe** [comment]
no lmao

**Comment by clusterfack** [comment]
Loader is my waifu, also no I have no idea what evolve is so no you don't need it.

**Comment by Exxion** [comment]
Not if you forward ports

**Comment by DeityLink** [comment]
Alright then, who else is up for RoR?

**Comment by Boxe** [comment]
join the /vg/station chat for ip

**Comment by NigglyWiggly** [comment]
I'm glad we can take a PR that wasn't too serious, make it VERY SERIOUS, and then just fucking shitpost all night in it.
Why is this still unlocked

**Comment by Exxion** [comment]
And HAN-D all the way

**Comment by SangriaMonkey** [comment]
chef is the best rain risker tbh

**Comment by DeityLink** [comment]
Commando 4ever

**Comment by Probe1** [comment]
[%100]

**Comment by Boxe** [comment]
anyone else coming for RoR?

**Comment by Senaat1** [comment]
no i wish i wasn't  busy

**Comment by Boxe** [comment]
c'mon it's just a quick game

**Comment by DeityLink** [comment]
There's 3 of us for now.

**Comment by Senaat1** [comment]
in a raid tho

**Comment by Boxe** [comment]
fuck raids come dance in the rain

**Comment by TheEliminator16** [comment]
Shit son did someone say RoR?
IP?

**Comment by Boxe** [comment]
/v/station chat fam

**Comment by TheEliminator16** [comment]
> cancer chat

I'll pass

**Comment by Boxe** [comment]
c'mon fam i ain't postin my ip on github

**Comment by DeityLink** [comment]
I have elim on steam I think, I'll tell him

**Comment by DeityLink** [comment]
Oh wait, I don't think I do after all

**Comment by Boxe** [comment]
senaat throw the ip at him already

**Comment by Senaat1** [comment]
done

**Comment by clusterfack** [comment]
Chef is literally the worst

**Comment by Boxe** [comment]
bandit is where it's at fam

**Comment by NigglyWiggly** [comment]
Bandit is the only correct answer you fucking idiots

**Comment by DeityLink** [comment]
I bet you play Sniper in dota, too

**Comment by Boxe** [comment]
>ASSFAGGOTS

**Comment by NigglyWiggly** [comment]
> Playing DOTA

Can we fucking remove Deity already

**Comment by PJB3005** [comment]
Man huntress best.

**Comment by Boxe** [comment]
>huntress

kys my man

**Comment by clusterfack** [comment]
A character for babies

**Comment by d3athrow** [comment]
This was a possible name before tiny cartoon horses was ebin meme

**Comment by carshalash** [comment]
Nah, some absolute madman actually researched which one took place first.

**Comment by 9600bauds** [comment]
Another absolute madman couldn't find any non-MLP content when searching for the name

**Comment by d3athrow** [comment]
whatever then

**Comment by Senaat1** [comment]
POMF MERGED IT, AHAHA

**Comment by Boxe** [comment]
praise be

**Comment by TheFriggenSawbones** [comment]
what the fuck is up

**Comment by SangriaMonkey** [comment]
:chicken: :eyes: :ok_hand: :100: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :clap:

**Comment by Shadowmech88** [comment]
> highly controversial
> merged in less than a day

**Comment by carshalash** [comment]
Thank god it didn't get any more comments.

**Comment by 9600bauds** [comment]
shhh you'll jynx it

**Comment by Senaat1** [comment]
is futa gay

**Comment by PJB3005** [comment]
Hi I'm commenting to improve the comment count.

**Comment by carshalash** [comment]
God damn it, you know how much that tempts me.

**Comment by 9600bauds** [comment]
dylan_mug-r97f093b1f54d45a0a35fe2afb42a5374_x7jgr_8byvr_324

**Comment by ihadtoregisterforthis** [comment]
heart 
teeth_smile

**Comment by SangriaMonkey** [comment]
:monkey:

**Comment by clusterfack** [comment]
Why pomf

**Comment by NigglyWiggly** [comment]
#9576 when

**Comment by DeityLink** [comment]
I play Risk of Rain for a while and you guys meme behind my back I see.

**Comment by Exxion** [comment]
This is, hands down, the best thread on our GitHub

**Comment by Probe1** [comment]
We still meming?  REAL NIGGA HOURS START AFTER ITS BEEN MERGED.

WHO THE FUK UP?

**Comment by DeityLink** [comment]
IMAGEBARD DID YOU TAKE THAT GIF IN A DURARARA THREAD? I AM THE ONE WHO MADE IT!!

mask2

oh wait nevermind, not the same size

**Comment by Imagebard** [comment]
FIRST OFF THAT GIF IS TOO SMALL

SECONDLY DID YOU FIRST POST IT IN 4CHAN?

**Comment by Boxe** [comment]
REAL :eggplant: HOURS

SMASH THA FUKEN :eggplant: BUTTON!!

**Comment by DeityLink** [comment]
I posted it on the day the first episode of X2 Ketsu came out, yes

edit: my gif is much smoother than yours.

**Comment by Imagebard** [comment]
>on 4chan

Forget it, I saved a repost of a repost probably.

**Comment by ihadtoregisterforthis** [comment]
kappa

**Comment by chatsonf** [comment]
Congrats deity you're famous

**Comment by DeityLink** [comment]
That's nothing new is it? :^)

As much as I'd love to keep memeing all night long I really gotta sleep now. Thank you everyone, that was lovely. @carshalash your avatar is ponies you fucking hypocrite. You better revert that change tomorrow or I'll send the internet police after your ass!

**Comment by carshalash** [comment]
Man, it's the best photo of pasqualo trianglini I could find. Now i'm gonna have to find a better one.

**Comment by NigglyWiggly** [comment]
> Your avatar is ponies

No it isn't.
It's a webcomic called It Hurts and there is a scene involving the main character obsessing over pony toys that is entirely dropped afterwards.
But even if it was ponies that wouldn't really make him a hypocrite for wanting to remove ponies, ya big dork

**Comment by kol1th** [comment]
you all sicken me

**Comment by Imagebard** [comment]
@kol1th Who are you, lost child?

**Comment by Probe1** [comment]
@Imagebard he's @kol1th 

I'm 100% :eggplant: on it.

**Comment by kol1th** [comment]
@Imagebard 
i'm kolith

**Pull request merged**
