### PR TITLE
Removes slime cores from mechanic scanner list

### PR DESCRIPTION
**Pull request by Probe1**
Closes 
https://github.com/vgstation-coders/vgstation13/issues/14404

### CODE REVIEW

**Comment by PJB3005** [comment]
Well done you blew the autoclose.

**Comment by Probe1** [comment]
how did I manage that?  I'm an overachiever I tell you.

**Comment by PJB3005** [comment]
Extra newline.

**Comment by ComicIronic** [comment]
It
can't
understand
your
accent

**Pull request merged**
