### PR TITLE
Fixes the effect of space lube on TEG circulators.

### PR DESCRIPTION
**Pull request by twirling-jesters**
## What this does
Changes the effect of space lube on TEG circulators to actually be significant.

This requires some explanation, so I'll point out some of the things I noticed-- Firstly, when adding space lube to circulators during regular gameplay, I noticed pretty much no difference in power output for the TEG. I initially thought that the code to update the power output just wasn't firing at all, until I looked a little bit further into it. Here's the current code for determining the power bonus from space lube:

https://github.com/vgstation-coders/vgstation13/blob/0471421e9a28d6f362942470054f4b9ac7092462/code/modules/power/generator.dm#L131-L135

This seems fine, if the volume capacity of circulators hit around 33 and max out around there. The comment here would make sense: 33/16.5 = 2. The power output would be tripled.

HOWEVER:

When we look at the actual code for the volume capacity of circulators, we see this:

https://github.com/vgstation-coders/vgstation13/blob/0471421e9a28d6f362942470054f4b9ac7092462/code/ATMOSPHERICS/components/binary_devices/circulator.dm#L60

Flow capacity is represented as a float between 0 and 1. Meaning we have to multiply it by 100 to actually matter.

## Why it's good

Makes it actually worth banging on chemistry's window and asking for space lube as an engineer.

## Changelog

:cl:
 * bugfix: Fixed space lube not increasing power output for TEG circulators properly.
 * tweak: TEG circulators now hold 100 units instead of 25.

### CODE REVIEW

**Comment by Eneocho** [comment]
I've always feel lube is burnt a bit too fast to be useable, could you tweak lube consumption to be slower (or make the circulator storage larger)?

**Comment by pedr69** [comment]
lube isnt even consumed if the temperature is low enough i think?

**Comment by Eneocho** [comment]
> lube isnt even consumed if the temperature is low enough i think?

Indeed, it only decays into chemical waste after reaching 3500K, but that's a relatively quick to reach temperature for regular TEG setups and babby temperature for high performance autismo RUSTs.

**Comment by twirling-jesters** [comment]
> I've always feel lube is burnt a bit too fast to be useable, could you tweak lube consumption to be slower (or make the circulator storage larger)?

Done, circs should hold 100u of fluid now as opposed to 25.

**Comment by Kurfursten** [comment]
It has a special interaction that no other chemical reaction uses (even though it is totally modular and anyone can set this as a var) - the heat will only convert a single unit of lube at a time, which expends the heat and generates 0.2 units of waste. This then is supposed to be degreased with ethanol. So the engine has to be continually spicy to gradually convert all of the lube.

Also keep in mind that 3500 reagent temperature is not the same as pipe temperature, because heat transfer has to happen.

**Comment by Eneocho** [comment]
Even then, kurf, it is eaten way too fast on optimized TEGs or RUST-linked TEGs. I for one would like if it got consumed slower, but a larger container also works.

**Comment by Eneocho** [comment]
> Done, circs should hold 100u of fluid now as opposed to 25.

Add this to the changelog under tweak

**Comment by pedr69** [comment]
hmmm what if you mixed a drop of leporazine(with its infinite heatcapacity) into the TEG lube mix
everyone knows about medbay cryomix autism but where is the engineering TEGmix autism?

**Comment by Eneocho** [comment]
It isn't infinite heat capacity, it's 10000 heat capacity as seen on _DEFINES/setup.dm.
At first I dismissed it, but on testing I see you were onto something all along. With an optimized regular TEG setup (25000K inlet) it takes about 3 seconds to heat by 3 degrees. It takes a good 25 minutes for the first lube unit to decay into chemwaste if you use lepo (then 27m for the remaining lube), meaning an autocleaning mix (20u lube, 4u ethanol, 1u lepo) takes a whopping 9 hours 24 minutes to decay completely with this particular optimized setup, leaving only 1u lepo.

**Comment by Kurfursten** [comment]
Leave it as it was to encourage chemistry autism, update wiki with advice

Only disappointed that the optimal mix is so simple, but that's hardly in scope

**Comment by Exxion** [comment]
Most of the insanely ludicrous reagent specheatcaps should probably be changed, but it's thematic for leporazine in particular, and also less impactful for mob heating due to leporazine's actual purpose
Until and if they do get changed, though, phalanximine has an even higher specific heat than leporazine, albeit relatively slightly

**Pull request merged**
