### PR TITLE
NO VOX ALLOWED

### PR DESCRIPTION
**Pull request by jknpj**
nopox

Another great decal set made by @RealestEstate 

Not mapped anywhere.

### CODE REVIEW

**Comment by Durgen** [comment]
Map them into uploads lol

**Comment by brndd** [comment]
I like number 4 the most. I think it might be good to trim this down to just a couple of icons, feels a little weird having 6 subtle variations of such a niche sign in the dmi.

**Comment by Exxion** [comment]
There are like two people who use the haircut in the third one

**Comment by kilozombie** [comment]
Second and/or fourth one are best. Good work @RealestEstate

**Pull request merged**
