### PR TITLE
Revert "Revert "Revert "Minor fix for explosive chemical reactions"""

### PR DESCRIPTION
**Pull request by ghost**
Reverts vgstation-coders/vgstation13#17160

### CODE REVIEW

**Comment by ghost** [comment]
a true hero that his c*derbase doesn't deserve.

**Comment by kilozombie** [comment]
pleasenote

**Comment by Durgen** [comment]
the c\*der/playerbase class antagonism is real, because c*ders continuously choose to make it real

**Comment by Durgen** [comment]
screen shot 2018-01-20 at 7 44 50 pm

someone should ideally merge this and wait for the poll

**Comment by MechaMusume** [comment]
b-b-b-b-but voting doesn't work so c*ders would be allowed to merge whatever they feel like with zero vetting or input then try shout down anyone that disagrees

**Comment by SysadminJeroen** [comment]
^ this guy totally ignored the post above him ^

**Comment by small-boss** [comment]
dont let the players vote, only our collabs know whats good for this server

**Comment by Praecordia** [comment]
Revert "Revert "Revert "Revert "Minor fix for explosive chemical reactions"""" when?

**Comment by Irradiation** [comment]
@Praecordia 
When you code it.

**Comment by gbasood** [comment]
As I said elsewhere:
>Alright
Fuck this drama
@d3athrow will figure out what he wants to do when he wants to
I'm gonna lock this until then because otherwise it will turn into shit flinging
I'm not trying to prevent discussion of all this but until people cool down a bit this issue isn't helpful.

**Pull request closed without merging**
