### PR TITLE
H.O.N.K. Movement sprites

### PR DESCRIPTION
**Pull request by JMWTurner**
honk

https://dl.dropboxusercontent.com/u/33846352/dreamseeker%202016-08-31%2018-25-38-04.webm

### CODE REVIEW

**Comment by ghost** [comment]
This is not 120fps movement.

**Comment by ghost** [comment]
honk

**Comment by clusterfack** [comment]
This looks so wrong

**Comment by JMWTurner** [comment]
I wanted it to look goofy as fuck.

I have plans to animate the rest of the mecha, but they'll have much smoother/realistic looking animations.

**Comment by SkowronX** [comment]
Somehow, I love it and don't love it at the same time.

**Comment by JMWTurner** [comment]
Isn't that everyone's relation to clowns in general?

**Comment by clusterfack** [comment]
I cant say that it is

**Comment by gbasood** [comment]
I feel like it fits the theme of clowns being fucking stupid

**Comment by ComicIronic** [comment]
If you used the moving icon state system, be aware that it will activate every time the atom moves, including when being pulled or pushed. Same thing happened to bolas.

**Comment by JMWTurner** [comment]
revision 1
- Mechs won't attempt to run while drifting through space

@ComicIronic The only other weird case I can think of is when they get dragged by a singularity but I think we can overlook that one.

Those procs I defined could also allow custom sprites for mechs moving through space using thrusters.

**Comment by Intigracy** [comment]
This is great.

**Comment by NigglyWiggly** [comment]
Couldn't you cut out the first frame of this and set it to reverse?
That's a really minor thing but still

**Comment by JMWTurner** [comment]
@NigglyWiggly The first frame has to be the default pose, the one the mech takes when not moving.

**Comment by Arthurdentist** [comment]
got a gif of it in action on the station?

**Comment by JMWTurner** [comment]
@Arthurdentist Just watch the webm in the OP

**Comment by Durgen** [comment]
reminds me of this
https://en.m.wikipedia.org/wiki/Sallie_Gardner_at_a_Gallop

**Comment by PJB3005** [comment]
PANIC MERGE BECAUSE WE NEED A SERVER RECOMPILE.

**Pull request merged**
