### PR TITLE
All red cables on box, deff, packed are now yellow

### PR DESCRIPTION
**Pull request by DamianX**
image

So that I can see what I'm clicking on in maintenance tunnels with red pipes.
~~If the thumb gods don't hate this I'll do it for the rest of the maps.~~

:cl:
 * tweak: All previously-red cables on Box, Deff and Packed are now yellow.

### CODE REVIEW

**Comment by SonixApache** [comment]
👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

FUCK RED CABLES

**Comment by tuypo1** [comment]
Bout fucking time holy shit what were oldmappers thinking

**Comment by Kharkov72** [comment]
NOOO THE HECKIN PIPERINOS

**Comment by strawberrytan** [comment]
that was a feature

**Comment by tuypo1** [comment]
Me standing outside your house with a bat is also a feature

**Pull request merged**
