### PR TITLE
defibs no longer work on heartless sods

### LINKED ISSUE #14807: Defibrillator Functions on Races Without Hearts
Skeletons, for example.
It just doesn't make sense.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #14807

:cl:
 * tweak: Defibs no longer work on people without hearts.

### CODE REVIEW

**Comment by Intigracy** [comment]
~~As-is this probably doesn't work, I'll fix it when I have a chance~~

**Comment by ghost** [comment]
I always thought your avatar was a super matter shard

**Comment by Intigracy** [comment]
I lied, this works as advertised.

**Comment by ghost** [comment]
We should add heart attacks to the game, give more reason to take care of your ticker besides 'it gives me oxyloss every so often'

**Comment by Kurfursten** [comment]
I love attacking people with hearts as much as the next guy, but no matter how well you take care of your heart you can't use it after it's removed from your body.

**Review by PJB3005 — APPROVED** [review]

**Comment by ghost** [comment]
Yeah, it's weird. Harm Defib, catastrophic liver failure, virus, and flipping a table full of items a couple times is about it off the top of my head. At least there's the bleach-ammonia smoke for fucking lungs. Perhaps revive the tachycardiacs in the health code to actually work for giving people heart attacks?

**Comment by Intigracy** [comment]
Or add it as a downside to hyperzine.

**Comment by SonixApache** [comment]
Should use `get_heart()` since that exists now.
Also dionae have hearts but they don't use them.

**Comment by DamianX** [comment]
Why do dionas have hearts?

**Comment by ghost** [comment]
This done?

**Comment by Intigracy** [comment]
Yeah Diona hearts is desperate

**Pull request merged**
