### PR TITLE
Remove random item from discounted surplus

### PR DESCRIPTION
**Pull request by ShiftyRail**
Seems like it can bring the cost down to 0 in some cases.

### CODE REVIEW

**Comment by angryturnip** [comment]
Don't remove the jackpot god roll

**Comment by Dacendeth** [comment]
the co-op bundles should be illegal too, reducing something that was intended to require multiple people down to something one person can get is silly.

**Comment by hacker-on-steroids** [comment]
but muh free boxes!!!!
image

**Comment by githubuser4141** [comment]
Is it actually 0? Why not fix that instead, I've clicked it maybe once it when it said '0' and it still took away TC, so maybe it's just a visual glitch.

**Comment by Eneocho** [comment]
god how I wish the CANNOT REPRODUCE label was still a thing, what a thing to lose

**Comment by ShiftyRail** [comment]
@githubuser4141 it is. 50% discount from random item, 50% discount for discounted surplus.

Random item cost 0 to buy, apply both discounts, then picks an item that you can afford with the remaining TCs.

In most cases, items have a hard-limited "discounted cost" variable and there seems to be a cap, at 50% of that discounted cost (???). Bundles do not have it, which means their cost does go down to 0.

This means when you get down to 0 TCs, you can still press the random item button and always get bundles.

I think it is a bit silly to get an effective 80% discount on most stuff, even if the bug with 0 TCs is fixed. The random item should not be a part of the discounted surplus. It is an oversight.

**Comment by Kurfursten** [comment]
Infinite bundles is bad for the shift, worse it's one of those secret meta tricks where you only get infinite TC if you know it. If you want this to be a feature, just make a PR where 1 in 50 shifts a traitor gets infinite TC to murderbone.

**Pull request merged**
