### PR TITLE
Tweaks Service and Medical radio colors to make them more distinct from Common radio

### LINKED ISSUE #11405: Medical chat channel color is very similar to general chat color
(WEB REPORT BY: rei1226 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

9debda602789f89c86f5106da2808e629554f274 

> General description of the issue

Medical chat color is exactly the same as the general chat color. You can't even distingiush between the two.

> What you expected to happen

Readable medical text

> What actually happened

Medical chat channel blended in seamlessly with general chat channel

### PR DESCRIPTION
**Pull request by 9600bauds**
**!! NOT FINAL - SUGGESTIONS/FEEDBACK MUCH APPRECIATED !!** - Fixes #11405

At some point, the chat color for Medical radio got somehow re-assigned to the Service radio. Meanwhile, the Medical radio got given an ugly color that looks very very close to the Common radio channel.
This is my solution that is guaranteed to leave everyone thoroughly dissatisfied:

Before
photoshop_2016-12-29_23-08-58
dreamseeker_2016-12-29_22-55-01

After
asd
dreamseeker_2016-12-30_16-09-57

I am DEFINITELY listening out for better ideas on the colors here.
For reference this is the old one
photoshop_2016-12-29_21-56-56

:cl:
 * tweak: Tweaked the Medical and Service radio colors to make them more distinct from the Common radio color.

### CODE REVIEW

**Comment by kol1th** [comment]
It makes me uncomfortable but I think it's a good change. Sometimes I can hardly tell medical and common apart with f.lux, and service is never used so that doesn't bother me much.

**Comment by 9600bauds** [comment]
I was actually going to look up how much the service channel is used but the logs don't store what channel something was said in

**Comment by Intigracy** [comment]
fixes #11405

**Comment by 9600bauds** [comment]
whoops I forgot

**Comment by Probe1** [comment]
its fine

**Comment by yclatious** [comment]
I like it, supply is barely ever even used and medbay deserves the sleek blue instead of the pizza makers, rum and coke mixers and glorified peasants.

**Comment by 9600bauds** [comment]
I still don't like the "common but slightly darker" color though. Any better ideas?
 * must be dark enough to be legible
 * can't be similar to another dept. color (see the color wheel)
 * can't be pink

**Comment by despotate** [comment]
Try a shade of brown. It's what I always envision as the color of service.

Like a much lighter, more saturated (is that the word?) supply.

**Comment by 9600bauds** [comment]
Supply already has it

**Comment by despotate** [comment]
I believe the eye resolves the differences between shades of red better than any other color so I'm sure we can stuff service somewhere in between supply and chemistry

edit: I've never been a chemist so I didn't notice that everyone in your color wheel is a chemist - I meant that light pink color

**Comment by Shadowmech88** [comment]
I personally don't have a problem telling the Common and Medical channels apart.

But if you're going to change it, why such a drastic change? Why not leave Service how it is and change Medical to the proposed Service color?

**Comment by 9600bauds** [comment]
Medical not having the light blue is a travesty, it fits better

Besides, the Service channel is used much, much less, so we can say we hid the problem under the rug

**Comment by despotate** [comment]
http://www.colorhexa.com/c0a17d for service WHEN

**Comment by 9600bauds** [comment]
dreamseeker_2016-12-30_00-51-10
Maybe a little darker

**Comment by Intigracy** [comment]
But that's perfect.

**Comment by SysadminJeroen** [comment]
It looks fine on my screen, but perhaps it'll look terrible on different monitors.
Just a little darker would put it in the safe zone, not like Service is an important channel to listen to anyways.

**Comment by 9600bauds** [comment]
dreamseeker_2016-12-30_00-52-39

**Comment by despotate** [comment]
The service channel blends forgettably into the background just like the people who work there

**Comment by Shadowmech88** [comment]
>Medical not having the light blue is a travesty, it fits better

In what way? Nothing in Medbay is light blue except the CMO's jacket.
If we're going for "quintessentially Medbay," the most common Medbay color after white is green, like one finds on medical kits, medical bedsheets, medical jumpsuits, virology jumpsuits, and nanomed vendors.

**Comment by 9600bauds** [comment]
IDs, Medibelt, MediHUD

Green is unfortunately taken, which is what led to the problem in the first place

**Comment by Shadowmech88** [comment]
Right, so they went with a blue-green, which some people still have a problem distinguishing. I'm not saying it shouldn't be changed, but I don't see the need to change it to a completely different color rather than just tweaking the values a little to make it more different.

Also aren't Medical IDs a dark blue anyway?

**Comment by 9600bauds** [comment]
I did try just tweaking the values slightly, I wasn't happy with how it looked at all

**Comment by Shadowmech88** [comment]
How does http://www.colorhexa.com/4d6cae look? That's the Medical ID color.

**Comment by despotate** [comment]
slightly lighter version of command / 10

**Comment by Shadowmech88** [comment]
It's about halfway between current Command and current Service.

**Comment by 9600bauds** [comment]
dreamseeker_2016-12-30_01-19-10
It's very similar to Command, which would be hell for CMOs

**Comment by Intigracy** [comment]
That service color is damn sexy and despotate is a genius.

**Comment by kol1th** [comment]
The tan for service just werks, it's different enough from Supply and still hardly used that I don't think people will have a problem with distinguishing the two.

**Comment by ComicIronic** [comment]
The tan is a little bit too light, I find it harder to read against the white background.

**Comment by 9600bauds** [comment]
b4
dreamseeker_2016-12-30_00-52-39
after
dreamseeker_2016-12-30_16-05-59

Better/worse?

**Comment by ComicIronic** [comment]
Better. I'd keep it there, looks good.

**Comment by Exxion** [comment]
I am so sad that commit message will be lost (to the main repo) when this is squashed and merged

**Comment by Probe1** [comment]
i'm pretty sure we can edit commit messages

**Comment by 9600bauds** [comment]
I think this PR is about ready now
I honestly expected controversy
crack

**Comment by kol1th** [comment]
fantastic image

**Review by ComicIronic — APPROVED** [review]

**Comment by Intigracy** [comment]
15-1, clearly this cannot be merged.

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/commit/75c5bf5bfd798d3ca3bd205d6492f6e2b3152532

It remains in the description 5ever fyi

**Pull request merged**
