### PR TITLE
Fix resisting out of package wrapped lockers

### LINKED ISSUE #7715: You can't resist out of package wrapped lockers anymore
You get fucked.

### PR DESCRIPTION
**Pull request by clusterfack**
Fix #7715

### CODE REVIEW

**Comment by Intigracy** [comment]
Does #6835 still exist?

**Comment by clusterfack** [comment]
Well I didn't make any effort to fix that one so, probably

**Comment by Intigracy** [comment]
fix it boyo I'll give you an imaginary dollar.

**Comment by clusterfack** [comment]
Any specific delay time we should have on it?

**Comment by Intigracy** [comment]
Not that I can think of. Maybe a little less than a locker, considering it's only paper.

**Pull request merged**
