### PR TITLE
Admin VV Typesetting Changes

### PR DESCRIPTION
**Pull request by jwhitak**
# Admin Stuff

## What this does
1. Changes VV editing Types such that it attempts to find a common prefix in order to make the list more readable. This affects all type selection menus.
image
2. Moves the right click edit gun projectile variables menu here, to the VV dropdown (since it was showing up on all objects in the game...)
image
3. Adds the ability to change projectile_types shot out of a gun, including an easy to use menu for it. Power users can edit bullet_type_override directly.
image
image
image
image
4. Removes a server-crashing level bug where a hookshot projectile subtype can be fired out of the roulette revolver (or any other non-hookshot) and effectively lag out the server.
image
(this happened 5 minutes after I fired the gun, and it never unfroze again after this)

## Why it's good
OLD
image

NEW
image

## How it was tested
Had a lot of fun.
image
image
image
image
image
image

## Changelog

:cl:
 * bugfix: Roulette Revolvers are less likely to crash the server with hookshot projectiles, again.
 * rscadd: Admins have even more projectile weapon tools at their disposal.

### CODE REVIEW

**Comment by Eneocho** [comment]
Does the type search change also affect the spawn menu? cause that would help a lot when spawning shit

**Comment by jwhitak** [comment]
Yes.

**Comment by SECBATON-GRIFFON** [comment]
that "yes, have me be deadminned" line kek
just erm make them not crash the server?

**Comment by jwhitak** [comment]
Because the issue is complex, and I wasn't interested in deep diving to fix a bug that can only be caused by vving something you shouldn't. The hookshot stuff ideally shouldn't be a projectile type at all, but they're old code, so that's where they ended up.

**Review by west3436 — APPROVED** [review]

**Pull request merged**
