### PR TITLE
Engine Degreaser

### PR DESCRIPTION
**Pull request by ringringllingling**
This is an option to get ethanol from the still.  It uses the vodka sprite.

### CODE REVIEW

**Comment by ringringllingling** [comment]
Hi!  Have you ever wanted to use the still to get ethanol?  Then this is the pull for you!

**Review by Probe1 — COMMENTED** [review]
Tested and works.  Curiously it did not get me immediately drunk, or even do anything unhealthy to me, but that's the fault of chemistry coding.

**Comment by Exxion** [comment]
Ethanol is one of the weakest alcohols
Blame oldcoders

**Comment by Probe1** [comment]
I'd rather blame dylan.  He's the fall guy!

**Comment by Probe1** [comment]
Make sure you update the wiki Derpycobra or the kebab will get you.

**Pull request merged**
