### PR TITLE
Revert "AI Cyborg-Shells"

### LINKED ISSUE #27889: stuck in AI shell
(WEB REPORT BY: surrealitarian REMOTE: 206.221.180.138:7777)
i clicked the button to go back to my core and the button fucking disappeared and now im an AI shell forever HELP

### PR DESCRIPTION
**Pull request by jknpj**
Reverts vgstation-coders/vgstation13#27708

Closes #27886

### CODE REVIEW

**Comment by ghost** [comment]
apparently shells destroyed in certain ways will send people back to the lobby so this should probably be speedmerged until the feature can be made more sane

**Comment by boy2mantwicethefam** [comment]
fix it bro, do I really need to be the one to fix it?

**Comment by gurfan** [comment]
revert it until its fixed please @ancientpower

**Comment by Exxion** [comment]
He can't

**Comment by Eneocho** [comment]
Here's hoping it will be fixed and remerged one day.

**Comment by gurfan** [comment]
@Eneocho 
This *was* fixed and remerged. It was reverted again because the idea sucked.

**Pull request merged**
