### PR TITLE
Adds the silicate sprayer.

### PR DESCRIPTION
**Pull request by PJB3005**
Adds the silicate sprayer, always hated it when Urist McGreytider goes around damaging windows, but you're too lazy to reasemble them to fix them? Look no further!

silicate

The concept is simple, load it with silicate, and use it on some damaged windows! It'll be good as new in an instant!

Silicate sprayers are available at YouTools or autolathes.

If you wanna go further than that, there's always the advanced version, ask your local R&D departement!

honk

This advanced version comes with a bigger tank, and the ability to reinforce windows, up to TWICE their normal strength.

Now, due to the only source of silicate being chemistry (yes I uncommented the reagent), there are now also silicate tanks around the station!

silicate

Other changes:
- Added .sh versions of the map merger scripts, for UNIX operation systems.
- Fixed window damage overlay code.

Blame the map merger for the stupid amount of diffs on the maps.

### CODE REVIEW

**Comment by AutismSpider** [comment]
How big is the sprayer?

Does this only fix the window or just hardens it? or does both?

**Comment by PJB3005** [comment]
@AutismSpider it's size 2, and it fixes the windows, doesn't harden them.

**Comment by Kurfursten** [comment]
I like it. Also on a more interesting level, this provides an easy source of aluminum and silicon to ghetto chemists.

**Comment by PJB3005** [comment]
@Kurfursten yeah that's also something I thought about.

**Comment by ihadtoregisterforthis** [comment]
Will this lotion make my plasma glass grow strong again?

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis High linecount is sourced purely to 3/4 of the maps. Map clean tool sometimes works poorly - the hell of working on map PRs.

**Comment by Probe1** [comment]
:+1: 

I'll review the maps in the morning to make sure it cleaned properly.

Silicate doing nothing has bothered me since my first day here.  Glad to see it finally get fixed.

**Comment by Exxion** [comment]
I'm a bit disappointed that silicate does nothing on its own and only works in the sprayer. I wanted silicate gas grenades.

**Comment by Kurfursten** [comment]
PJB could create a new proc in window that contains the improvement code, and the advantage of the sprayer would be that it calculates exactly how much is needed (as it does currently) so none is wasted.

I had thought of it before but it was such a significant change to how he has it now, it seemed like a lot to ask.

**Comment by Exxion** [comment]
Can always do it later

**Comment by PJB3005** [comment]
@Kurfursten at the moment the sprayer is to repair windows, not reinforce them, though I could add an advanced version that does it.

@Exxion do you honestly expect that you can splash a window with silicate to fix it?

**Comment by Exxion** [comment]
It's how it was designed before.
And yes, though it wouldn't be smooth or transparent anymore.

**Comment by Kurfursten** [comment]
@PJB3005 By improve I meant repair, but like I said, no obligation.

**Comment by PJB3005** [comment]
@Kurfursten I actually just added an advanced version which also has the ability to reinforce.

Also this PR is done.

**Comment by ihadtoregisterforthis** [comment]
Again, does this have effect on plasma windows?
What about tinted ones?

**Comment by PJB3005** [comment]
@ihadtoregisterforthis it affects any window, any.

**Comment by Kurfursten** [comment]
@Probe1 What were your findings about the map changes?

**Comment by ihadtoregisterforthis** [comment]
Should silicate tanks be bought via cargo too?

**Comment by PJB3005** [comment]
@ihadtoregisterforthis there's some on the maps by default, but yes they can be bought from cargo too.

**Comment by Zth--** [comment]
Please update the wiki
http://ss13.pomf.se/wiki/index.php/General_Items#Water_Tank
http://ss13.pomf.se/wiki/index.php/Guide_to_Chemistry

**Comment by PJB3005** [comment]
Will do.

**Comment by FudgePucker** [comment]
In hindsight, this makes it WAAAAYYYYYYYYYYYYYYYYYYYYYY too easy to get thermite through ghetto chem. Use a crowbar on some floor tiles and weld them to get some metal, make a grinder, make a electroiser, eletrosise the silicate THAT IS NOW IS IN BULK IN EASILY ACCESSABLE PLACES, ENTIRE TANKS OF THE SHIT, add iron, tada now you have all access.

Aluminium was only obtainable before this part from the chem despenser, every single chemical that has aluminium in it reacts upon mixing, besides thermite, and now silicate.

How much longer before people powergame round start to have buckets of thermite?
How much longer until there is a gaping hole into armory every round from space?
How much longer until there are holes leading into every (now empty from looting) department?

**Pull request merged**
