### PR TITLE
No guns - or non-traitors antagonists - on Castle station

### PR DESCRIPTION
**Pull request by ShiftyRail**
The way the experiment was supposed to work originally.
Removes the guns introduced by #28116, make Castle only spawn traitors and minor rulesets (Mice, catbeast, rambler...)

I believe a map without security and with its special escalation rules can be fine. Maybe in time we will learn that Security was a mistake.
A map where everyone starts with more weapons than Security roundstart, with unclear rules of escalation, is not a good experiment. You didn't just remove sec, you transformed everyone into a worse version of security with less responsibilities and less admin oversight.

If the people really want to turn this into nations, or escalate civil wars, they will find a way. Giving all departments some of the best guns in the game as early as 12:05 was a mistake.

🆑 
- tweak: Departments on Castle Station no longer start with guns. Only traitors and minor antagonists will spawn on Castle Station.

### CODE REVIEW

**Comment by Eneocho** [comment]
I would remove strict traitor antags on castle station. After all, It's no longer a Nanotrasen station. Challengers, on the other hand, would still make sense.

**Comment by ghost** [comment]
If Castle actually has special escalation rules and that isn't just a collective delusion we're all suffering due to memes then that should probably be stated somewhere *officially* because I'm not aware of it being any different from other maps except for its role removal memes

**Comment by west3436** [comment]
Just give everyone Survivor status on Castle since this is already a meme map

**Comment by ShiftyRail** [comment]
I still believe that Castle would work better without the guns.

**Pull request closed without merging**
