### PR TITLE
[DNM] Added a cycling state toggle to pathogen huds

### PR DESCRIPTION
**Pull request by DrSnips**
# DNM

## What this does

CMO hud and science goggle (pathogen goggles) now cycle the visual state.
Off -> (Purple overlay + Viruses) -> (No overlay + Viruses) -> [loop back to off]
## Why it's good

Some people don't like to live in Barney vision when there's a virus around, some people do, this gives you the option. Who doesn't love options?
## Changelog

:cl:
 * rscadd: CMO hud and science goggle (pathogen goggles) now cycle the visual state. IE Off -> (Purple overlay + Viruses) -> (No overlay + Viruses) -> [loop back to off]

### CODE REVIEW

**Comment by DrSnips** [comment]
Tested on both cmo huds and sci goggles. If there's any others let me know please because apparently the CMO hud is a snowflake.

**Comment by DeityLink** [comment]
So to explain my opinion on that matter:
The point of the purple overlay of science goggles was twofold: contrast/and incentive to not keep it enabled at all time, so if you suddenly find yourself surrounded with pathogen when enabling it, it's much more dramatic
If you can keep it enabled at all time (because sure it's gonna be hard to see in blood, but it's the green pathogen clouds/yellow contact mobs/items that people actually care about) you lose that "jumpscare effect", which imo is a shame.

As an alternative, I'm suggesting that the purple overlay could instead be changed to use a BLEND_MULTIPLY blending mode 
image

which is a lot easier on the eyes

image

If anything, this provides vaporwave vision which also fits the science goggles aesthetics.

**Comment by DrSnips** [comment]
The multiply thing does look a bit less drowned out but it doesn't really solve the issue of people not wanting to live in The Box Dimension while trying to deal with a virus. I'm gonna be honest it doesn't look all that different at a glance and only when I'm REALLY looking at sprites up close can I tell.
You can try and make it look as less-bad as you want but if the person's gripe is that it's purple at all then that doesn't resolve it.

**Comment by DeityLink** [comment]
My point was that people probably don't like the purple because it's a filter that actually drowns out/hides the background with some transparency. The mushroom man dark vision mode has a purple tint and I don't think anyone's ever complained about that one because it's not a filter like the science goggles one.

**Comment by DrSnips** [comment]
Gonna push back on that a little and that's more likely a result of nobody playing mushmen to even notice or care.

**Comment by DeityLink** [comment]
That's just my opinion on the matter, like you said it's a matter of taste so at least this gave me an idea for color-tinted glasses.

**Comment by DrSnips** [comment]
The requester has requested further changes to the back end of things. The content of the PR will be unchanged but I basically need to redo this entirely.
Putting this on DNM until then.

**Comment by DrSnips** [comment]
gonna get back to this, I had to nuke my fork because I LOVE GITHUB AND TRYING TO REMOVE COMMITS. It's appalling how it's easier to nuke and remake a fork than it is to remove a commit.

**Comment by DeityLink** [comment]
to remove the last commit just do a hard/soft reset to the previous commit, if you want to remove a commit that's older, you have to do a new commit that "reverts" that one, but you cannot just make a commit disappear from the middle of a log tree without doing a reset of some sort.

**Comment by DrSnips** [comment]
The issue came from some bot that made a PR in my fork and I marged it to my fork thinking "what harm could it do?". Turns out it can be annoying so I later tried to revert it and now every time I want to deal with fetches and such it bugs me that I'm 1 ahead because I reverted something that doesn't exist.
So it's in the too late camp and required the nuclear option.

**Comment by DeityLink** [comment]
oh yeah don't merge the bot stuff on your repo, the same update get merged by vg anyway so you get their content by just pulling from upstream.

**Pull request closed without merging**
