### PR TITLE
Adds inflatable barriers to fire closets

### PR DESCRIPTION
**Pull request by beesil**
[tweak][POWERCREEP] 
exactly what it says on the tin

:cl:
 * tweak: adds a box of inflatable barriers to normal and wall mounted fire closets.

### CODE REVIEW

**Comment by Irradiation** [comment]
>a box

**Comment by MadmanMartian** [comment]
@otatoh Why are you making this addition?

**Comment by beesil** [comment]
@MadmanMartian 
I am very angry about retards with crowbars spreading breaches and not using inflatables properly (which will hopefully change if they're more widely available)

**Comment by MadmanMartian** [comment]
So the intention is for more inflatable barriers for public use, in the off chance said public start using them to close up breaches?

**Comment by SonixApache** [comment]
the better solution would be to make firelocks unbeatable

**Comment by beesil** [comment]
@MadmanMartian Yes.

**Comment by MadmanMartian** [comment]
Keep them as engineering stuff. If they're not already there, put them in engineering lockers

**Comment by ShiftyRail** [comment]
They're already in engineering lockers, and underused
I think they're in a perfect place in those cabinets

**Pull request closed without merging**
