### PR TITLE
Adds Photo Booths near the HoP's Office on most maps

### PR DESCRIPTION
**Pull request by DeityLink**
photobooth

:cl:
* rscadd: Added Photo Booths near the HoP offices on most maps. This allows HoPs to use their Security Records computer to update the crew's pictures, or add pictures to brand new records.

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Please put `[MDB IGNORE]` in your PR title.

**Comment by DeityLink** [comment]
> 
> 
> Please put `[MDB IGNORE]` in your PR title.

What? No. Why? Who are you? A coder from Paradise?

**Comment by AffectedArc07** [comment]
> > Please put `[MDB IGNORE]` in your PR title.
> 
> What? No. Why? Who are you?

I host mapdiffbot, and this PR caused excessive load on server resources due to rendering obnoxious amounts of layers on a 512x512 map. You can either put `[MDB IGNORE]` in your PR title or have your repo blacklisted. Up to you.

**Comment by ShiftyRail** [comment]
There is likely an error or a glitch with mapdiff bot, then. Because this PR only changes 10 tiles per map. Are you sure it's not a one-off bug on your end ?

**Comment by ShiftyRail** [comment]
Actually I looked at it. There is a larger chuck of map differences than intended, but individually it's still very few items. No reasonable code would get "excessive load" due to that.

**Comment by AffectedArc07** [comment]
> There is likely an error or a glitch with mapdiff bot, then. Because this PR only changes 10 tiles per map. Are you sure it's not a one-off bug on your end ?

`metaclub` and `snaxi` seem to be the problematic renders, as it has interpreted the diff as being the entire map, despite the diff being much smaller.
image

Diff miscalculations very rarely happen and only tend to break with mutli-Z map renders, as seen here, wheres every other map seems to render just fine.
image

image
image

Diffs are being miscalculated, however this is an issue outside of my control as I dont write the map parser. However, I will say one thing.

image
What is this meant to be? An insult? A statement? Coming at me with a toxic attitude when I made a polite request isn't going to do you any favours

> Actually I looked at it. There is a larger chuck of map differences than intended, but individually it's still very few items. No reasonable code would get "excessive load" due to that.

image

VG maps are 500x500, and have many layers, which means they consume a rather large amount of system resources to render, especially when you consider that a 500x500 SS13 map image is 16K pixels by 16K pixels. 

@ShiftyRail I commend you for approaching this reasonably instead of bringing toxicity to the conversation

**Comment by DeityLink** [comment]
> What is this meant to be? An insult? A statement?

A surprised and reasonable reaction to some unknown person coming without introducing themselves and telling me what to do without explaining why. And when prompted to explain themselves proceeds first to be rude `You can either put [MDB IGNORE] in your PR title or have your repo blacklisted. Up to you.`

> Coming at me with a toxic attitude when I made a polite request isn't going to do you any favours

You're the one coming in this PR with a toxic attitude! Please have some self awareness!

**Comment by AffectedArc07** [comment]
> > What is this meant to be? An insult? A statement?
> 
> A surprised and reasonable reaction to some unknown person coming without introducing themselves and telling me what to do without explaining why. And when prompted to explain themselves proceeds first to be rude `You can either put [MDB IGNORE] in your PR title or have your repo blacklisted. Up to you.`
> 
> > Coming at me with a toxic attitude when I made a polite request isn't going to do you any favours
> 
> You're the one coming in this PR with a toxic attitude! Please have some self awareness!

I guess I should have made it more obvious, even though I have hosted MDB for almost 2 years now, and everyone else seems to get the picture, likely from reading the URLs
image

My first reply was not rude in the slightest, and you know it wasn't, hence why you took my second post into this and tried to paint the toxicity on me, despite you engaging in it first. I treat people the same way they treat me. Come at me with a toxic attitude? Get one back. Why should I bother being polite in future posts down if you are going to attempt to belittle me by saying "What are you, a paradise coder?"

**Comment by ShiftyRail** [comment]
Snaxi:
`no icon: /obj/effect/step_trigger/teleporter/random`

Metaclub:
`icon: /obj/effect/step_trigger/teleporter/random/shuttle_transit`

I **believe** this stuff makes your bot work more than it needs to, since we don't see those in other maps' logs. Does /vg/ crashes your bot often ? Are you happy with retrying this one to see if it wasn't just a strange bug ? Sometimes your bot fails to render, we restart it and it works fine without apparently causing issues on your end.

**Comment by AffectedArc07** [comment]
> Snaxi:
> `no icon: /obj/effect/step_trigger/teleporter/random`
> 
> Metaclub:
> `icon: /obj/effect/step_trigger/teleporter/random/shuttle_transit`
> 
> I **believe** this stuff makes your bot work more than it needs to, since we don't see those in other maps' logs. Does /vg/ crashes your bot often ? Are you happy with retrying this one to see if it wasn't just a strange bug ? Sometimes your bot fails to render, we restart it and it works fine without apparently causing issues on your end.

This wont make the bot work more, if anything it makes it work less. 

VG often doesn't crash the bot, though most of the time your map edits tend to be rather small. I only poke around and see whats causing issues when I literally get pinged with my server saying that theres obnoxious amounts of resource usage, look into it" 

Region edits and the renders themselves are calculated using https://github.com/Spacemaniac/SpacemanDMM, and it works for most codebases, even other ones with many missing icons (Para has the same issue and our maps render fine), hell the rest of yours do. Something about snaxi just doesnt like the region calculation (`--diff-maps`). 

Again, I commend you for actually being polite in this manner and attempting to problem solve, as opposed to trying to belittle me from the getgo.

**Comment by DeityLink** [comment]
> 
> I guess I should have made it more obvious, even though I have hosted MDB for almost 2 years now, and everyone else seems to get the picture, likely from reading the URLs

No one here had the picture before you explicitly said you were the host of mapdiffbot, which I for the record have no idea what it is for I am but a humble gameplay programmer/spriter. Where was I even supposed to see that URL?

> image
> 
> My first reply was not rude in the slightest, and you know it wasn't, hence why you took my second post into this and tried to paint the toxicity on me, despite you engaging in it first. I treat people the same way they treat me. Come at me with a toxic attitude? Get one back. Why should I bother being polite in future posts down if you are going to attempt to belittle me by saying "What are you, a paradise coder?"

No, everyone here agrees that you're coming particularly dry. For all I knew from your first post in this PR you might be either a troll or posted in the wrong repo? First I asked "who are you?" then I checked your profile and saw that you coded often on Paradise, hence I added to my post "a coder from paradise?" hoping to get confirmation.

I didn't see your name in any of our PRs, Issues, or either of our Discords/IRC. I had every good reasons to be surprised and confused. If you read my inquiry as toxicity then I offer you to adjust your perception. I for one wouldn't be offended at being called "a coder from vgstation" I dunno.

**Comment by AffectedArc07** [comment]
> No one here had the picture before you explicitly said you were the host of mapdiffbot, which I for the record have no idea what it is for I am but a humble gameplay programmer/spriter. Where was I even supposed to see that URL?

Given that you are a repository maintainer here, I would expect you to be familiar with the tools you run on your repo, otherwise thats just worrying. You also see the URL any time you view a map diff in fullscreen, which tends to happen if you want to look in detail, which most maintainers do.

> No, everyone here agrees that you're coming particularly dry. 

No one else has commented, apart from ShiftyRail, who has actually been productive in this matter, unlike you.

> For all I knew from your first post in this PR you might be either a troll or posted in the wrong repo? First I asked "who are you?" then I checked your profile and saw that you coded often on Paradise, hence I added to my post "a coder from paradise?" hoping to get confirmation.

You could have easily reworded it 

`Could I ask why you want this? I dont seem to get why, or why you specifically are asking`

I would have been just fine with this.

**Comment by ShiftyRail** [comment]
Latest snaxi PR also failed to render amusingly. 
https://github.com/vgstation-coders/vgstation13/pull/30021/checks?check_run_id=3092291820

The one before that ran fine, but this was 3 months ago.
https://github.com/vgstation-coders/vgstation13/pull/28976/checks?check_run_id=2044660524

I don't know what is causing this problem. There has been no major changes to snaxi or our map structure that would cause this issue. 

I am happy with you throttling our PRs or just temporarily blocking large diffs while you figure it out but I don't think the blame is on us here. We are legitimate users of your service using it the intended way. As you have said yourself we rarely cause you any issues.

We have no intentions of being hostile to anyone, but a little context about what is being discussed wouldn't hurt, now would it ?

Thanks

**Comment by AffectedArc07** [comment]
> Latest snaxi PR also failed to render amusingly.
> https://github.com/vgstation-coders/vgstation13/pull/30021/checks?check_run_id=3092291820
> 
> The one before that ran fine, but this was 3 months ago.
> https://github.com/vgstation-coders/vgstation13/pull/28976/checks?check_run_id=2044660524
> 
> I don't know what is causing this problem. There has been no major changes to snaxi or our map structure that would cause this issue.

Problem with region generation is a SpacemanDMM issue so it may be worth reporting over on that front.


> I am happy with you throttling our PRs or just temporarily blocking large diffs while you figure it out but I don't think the blame is on us here. We are legitimate users of your service using it the intended way. As you have said yourself we rarely cause you any issues.

This can easily be done on any PR anyone creates simply by adding `[MDB IGNORE]` into the title. If you are making a PR that has a lot of map edits with no real important diff (Example: A large turf refactor that changes pathtypes but has no visual diff), the ignore tag is perfect for this.

> We have no intentions of being hostile to anyone, but a little context about what is being discussed wouldn't hurt, now would it ?
> 
> Thanks

I admit that I should have put more context in the first post, but I had gotten used to everyone knowing, since in all the other occasions I have done this, everyone seemed to grasp it quickly, 

Again, thanks for being polite and handling this properly, instead of taking and twisting words.

**Comment by DeityLink** [comment]
> 
> Given that you are a repository maintainer here, I would expect you to be familiar with the tools you run on your repo, otherwise thats just worrying. You also see the URL any time you view a map diff in fullscreen, which tends to happen if you want to look in detail, which most maintainers do.

I'm not really one. I was only given the title to help close deprecated issues and put labels on both issues and PRs.

> 
> No one else has commented, apart from ShiftyRail, who has actually been productive in this matter, unlike you.

Because no one else had any reason to comment in this PR directly. I'm grateful to Shifty for handling the technical aspect with you and being most amiable, and I am just here to insist that you recognize my points.

> 
> You could have easily reworded it
> 
> `Could I ask why you want this? I dont seem to get why, or why you specifically are asking`
> 
> I would have been just fine with this.

The succession of small Wh- words and questions was supposed to convey how surprised and mostly confused I was. The people here are a rowdy bunch who generally write as they speak and are particularly thick skinned. As I had no idea who you were I put into words my most honest thoughts as they crossed my mind without worrying about hurting your feelings.

**Comment by BomberBro** [comment]
The only change in recent memory to sn*xi was the tool repath, but I don't see why that also wouldn't shred the other maps too. Kurfurst would know more. I'm really not sure why metaclub would be breaking it too though, while snaxi is a newish map meta almost never gets updated beyond the bare necessities.

**Comment by ShiftyRail** [comment]
I can't reasonably ask the contributors to put this tag on every snaxi PR or every metaclub PR. We can of course think of it for larger system PR, but that's a tangent. The issue here is with snaxi regions. I guess I can report it but I don't really know what is going on.

**Comment by d3athrow** [comment]
@AffectedArc07 can you please stop deadnaming us, we are /vg/ or /vg/station not VG

**Comment by AffectedArc07** [comment]
> I can't reasonably ask the contributors to put this tag on every snaxi PR or every metaclub PR. We can of course think of it for larger system PR, but that's a tangent. The issue here is with snaxi regions. I guess I can report it but I don't really know what is going on.

Its only for larger ones, and given that map edits have happened many times in the past, I am going to keep an eye on things but I am inclined to believe it may be a fluke, either with this PR or just that one check run itself.



> The only change in recent memory to sn*xi was the tool repath, but I don't see why that also wouldn't shred the other maps too. Kurfurst would know more. I'm really not sure why metaclub would be breaking it too though, while snaxi is a newish map meta almost never gets updated beyond the bare necessities.

See above



> @AffectedArc07 can you please stop deadnaming us, we are /vg/ or /vg/station not VG

My apologies. I am lazy, but if it makes you happy, ill write /vg/ 


EDIT: Looking at other PRs, MDB just conked out without resource issues on https://github.com/vgstation-coders/vgstation13/pull/29613, or atleast I dont have any logs of major resource issues on this day

**Comment by boy2mantwicethefam** [comment]
> 
> 
> > > Please put `[MDB IGNORE]` in your PR title.
> > 
> > 
> > What? No. Why? Who are you?
> 
> I host mapdiffbot, and this PR caused excessive load on server resources due to rendering obnoxious amounts of layers on a 512x512 map. You can either put `[MDB IGNORE]` in your PR title or have your repo blacklisted. Up to you.

Hahahaha oh no no no

**Comment by DeityLink** [comment]
@boy2mantwicethefam pls we've finished sorting things out don't put oil on the fire.

**Comment by boy2mantwicethefam** [comment]
@DeityLink Sir yes sir

**Comment by ShiftyRail** [comment]
@AffectedArc07 also for clarifications we don't really use the github hierachy much. Members and collabs just give technical reviews on stuff and informed opinions on game design things. 

Our horizontal hierachy works just fine and it's a really important thing for our community. Which is why I can't ask the players to put the tag on every small PR.
I will just keep that in mind for the future.

**Comment by AffectedArc07** [comment]
> @AffectedArc07 also for clarifications we don't really use the github hierachy much. Members and collabs just give technical reviews on stuff and informed opinions on game design things.
> 
> Our horizontal hierachy works just fine and it's a really important thing for our community. Which is why I can't ask the players to put the tag on every small PR.
> I will just keep that in mind for the future.

It doesn't need to be tagged on every PR, dont worry. Again, I feel like something about this PR was just a oneoff fluke, but I am gonna keep an eye out for VG map performance in the future.

As for git hierarchy, I come from a place where our github structure is "Maintainer or not in the org", so I apologise for not being aware of you having issue managers. 

I deem this resolved now and have nothing more to add, unless you require responses to things. Feel free to ping at any time, either here or in coderbus.

**Comment by d3athrow** [comment]
@AffectedArc07 
>VG

a

**Comment by AffectedArc07** [comment]
> @AffectedArc07
> 
> > VG
> 
> a

hush

**Comment by DamianX** [comment]
I didn't read the rest of the conversation but I think I have a hunch: we don't use a map cleaner with TGM unlike TG does, because it looked like StrongDMM handled that somewhat. Is that it?

**Comment by Kurfursten** [comment]
@AffectedArc07 Sorry about any confusion on this, Deity is a nice guy and text doesn't really convey tone, but he's an overexplainer and he likes things being explained rather than told as a result. You'll get a lot smoother communications if you just give a really brief explanation with your first request (e.g.: "Please add [MDB IGNORE] as this PR is hitting mapdiffbot with a heavy resource load")

That being said this is a very interesting case. There was a substantially larger snaxi render a few days ago here:
https://github.com/vgstation-coders/vgstation13/pull/30091/checks?check_run_id=3174907644
And it looks like it ran to completion much faster. Not sure that this data helps you much but it's good to have the extra data points so we can track this as it happens. I'd be happy to keep in touch if you let us know when resources are getting hogged so we can cooperate in tracking down the issue.

@DamianX This happened recently on that carp PR too where strongDMM didn't clean it as it should - very unusual. But my edit in 30091 was much larger and it did clean. I think the best solution is to keep an eye out for unusual edit sizes and re-edit afflicted maps to see if that fixes it.

**Comment by PrimeDSS13** [comment]
bring back the poster near the HOP's office on Box
it's essential for workplace morale

**Comment by DeityLink** [comment]
> 
> 
> bring back the poster near the HOP's office on Box
> it's essential for workplace morale

> first comment that's finally about this PR thank god

But it's still there. I just moved it near the bottom of the HoP queue rather than the top. Ironically you would have seen it if you used the MapDiffBot (which I never used myself until yesterday's conversation reminded me it exists, Still I think map change PRs should have pics in the OP)

image

The poster is on top of the wall so it can be seen from both the office, the queue, and even the hallway below.

**Comment by PrimeDSS13** [comment]
woah that's like 3x motivation

**Comment by Eneocho** [comment]
> 
> The poster is on top of the wall so it can be seen from both the office, the queue, and even the hallway below.

How am I supposed to admire the picture while waiting for the HoP to give me access if the poster ain't next the HoP desk.

**Comment by DeityLink** [comment]
You can admire it just fine from a few tiles away! You have to pass next to it anyway.

**Comment by Kurfursten** [comment]
He's referring to the help click text. You need adjacency to admire

**Comment by DeityLink** [comment]
*sigh*, fine. Had to move the hallway intercom up a bit. 
image

**Review by Kurfursten — APPROVED** [review]
This looks good to go, just waiting on my Snaxi PR to clear and then you're golden

**Pull request merged**
