### PR TITLE
Changes lipozine recipe to require capsaicin.

### PR DESCRIPTION
**Pull request by Hinaichigo**
## What this does
This makes it so that lipozine requires capsaicin in its chemistry recipe, changing the recipe to: equal parts sodium-chloride, phosphorous, and capsaicin.

## Why it's good
There are two birds I'm thinking this will stone.
- Becoming skinny again is trivially easy, and so people don't use much of the exercise and gym features that exist. By making lipozine non-trivial to obtain, this might make overeating and fat-related shenanigans more consequential and interesting. For example as obese people can't fit into hardsuits, atmos problems would be more of an issue, and an antag could mess with someone by injecting corn oil into their food and then sabotaging atmos.
- I think chemistry is typically a very self-contained job. Generally, the job consists of pushing buttons on the magic machine and occasionally dealing with breakins. This is masked by the fact that chemistry is situated very close to the hotspot of action known as the medbay, but still I think it could be improved. Lipozine isn't something as vital as bicaridine or clonexadone, but still is fairly often requested by patients, so I think its a good candidate to have it necessitate some outside-of-the-chem-lab interaction, eg. with botany.

## Changelog
:cl:
 * tweak: Lipozine now requires capsaicin to produce.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
pls no I luv lipozine

**Comment by djkramer123** [comment]
this is dumb

**Comment by Hinaichigo** [comment]
I counter that curing any non-infectious disease with a few clicks standing in the same place is uninteresting.

**Comment by tinysaturn** [comment]
If you want a chance at getting this to pass, then you should make also change dietine's recipe to be simple and remove the toxicity from it imo

**Comment by djkramer123** [comment]
It would still be dumb

**Comment by Hinaichigo** [comment]
Please explain why. There's a whole gym area of most maps and metabolism system that hardly ever get considered much because obesity can be instantly removed by waddling to chem and taking 1u of a pill that takes essentially no effort or interaction with other players to produce. I'd understand more for a staple chem like dexalin plus or something, where it just has to be available for the pacing of the round, but obesity is more of an RP and fun thing that's not necessarily going to mean the difference between round-removal or not.

>If you want a chance at getting this to pass, then you should also change dietine's recipe to be simple and remove the toxicity from it imo, Maybe lower the overdose threshold too

I'll take a look at doing that. Maybe it'd be good to have the simple yet less effective version dietine and then the cure-all lipozine be just a bit harder to make.

**Comment by DorainGrey** [comment]
> I counter that curing any non-infectious disease with a few clicks standing in the same place is uninteresting.

It's not just infectious diseases though, Fat sting is common strategy to annoy people.
I've been stung multiple times as an engineer fixing breaches and had my hardsuit fall off resulting in me limping to medbay half dead, forcing me to then spend 5 minutes AFK at a gym machine because the chemical is locked behind botany and thus unavailable is dumb. Especially when it'll probably happen multiple times a round.

> Please explain why. There's a whole gym area of most maps and metabolism system that hardly ever get considered much because obesity can be instantly removed by wadding to chem and taking 1u of a pill that takes essentially no effort or interaction with other players to produce. I'd understand more for a staple chem like dexalin plus or something, where it just has to be available for the pacing of the round, but obesity is more of an RP and fun thing that's not necessarily going to mean the difference between round-removal or not.

For a start, the only gym equipment that actually burns calories is the treadmill. So any changes would require the rest of the machines to actually do something.
Moreover, the rate of calorie burn on machines is extremely slow, it can take over 5 minutes to burn off the required calories.

Can you actually explain why you think this is a good change, beyond requiring people to use the gym machines?

**Comment by djkramer123** [comment]
Making something tedious doesn't make it interesting

**Comment by BomberBro** [comment]
Losing fat from the gym is uninteresting and fucking sucks. Making your fat lardass run the treadmill for 5-10 minutes while doing nothing else is very uninteresting gameplay for the all of 2 seconds it takes to become fat via changeling or virus.

**Comment by Hinaichigo** [comment]
>Can you actually explain why you think this is a good change, beyond requiring people to use the gym machines?

As an analogy, TGstation xenobio has machines that teleport the slimes into the pens for you so you don't get hurt and such and it makes the job "easier". But people have argued that having it require more effort and risk is what makes it fun. So instead of obesity just being "be fat -> go to chem dispenser -> done", a fat person would have to pester the chemist to go across the hallway and get some peppers from the botanist and grind them up, rather than just putting a beaker in and pressing the 3 buttons and taking a swig. And it's not like its phazon or something, chili peppers are really simple to obtain. People often mention wanting more cross-department interaction with reference to cargo, but why not chem as well? Chemist is one of the least dynamic medbay jobs because you generally stand in one place and interact with a single machine. Even grinding the peppers and isolating the capsaicin from the nutriment would be more fun than just using the chem dispenser IMO.

**Comment by Hinaichigo** [comment]
> Losing fat from the gym is uninteresting and fucking sucks. Making your fat lardass run the treadmill for 5-10 minutes while doing nothing else is very uninteresting gameplay for the all of 2 seconds it takes to become fat via changeling or virus.

You also don't necessarily have to run on the treadmill while obese, you can do other stuff and your body will metabolize in the meantime. During that time its a hindrance but not necessarily life-threatening.

**Comment by Hinaichigo** [comment]
I'll close this due to the 'mojis.

**Comment by Eneocho** [comment]
Bad change, much too dependent on the botanist giving a fuck, not being busy with some project or knowing how to get good chili. Giving a way to acquire said capsaicin without botany (albeit at a bad rate) would tame the downboats somewhat.
For example, most reactions that require Frost Oil are NOT done with botany-sourced frost oil (unless doing some splices), but rather ice-sourced (electrolizing 100u Ice makes 10u Frost Oil).
You could make a "Boiling Water" reagent that is made when water gets to 100°c or when ten parts water is mixed with one part capsaicin. This way you'd have a source of capsaicin sans botany if you take the time to boil the water then electrolize it.

**Comment by jwhitak** [comment]
@Hinaichigo Fat is easy to get to and VERY HARD to remove without lipozine. You need to drop 600 nutrition to below like 150 or so, and then wait an *additional timer*. This, even with gym equipment and other bonuses, can take over FIVE to TEN minutes to process when you are *specifically trying to get rid of the fat*. Lipozine immediately kills the fat timer and unfats you regardless of your nutrition. TBH, fat is a really rough status effect to get. Also, not every map has gym machines.

**Comment by pedr69** [comment]
jerry, pull up the dietine chemical procution chart

**Comment by Hinaichigo** [comment]
Might consider redoing this also with tweaks to dietine but... coffee and fuel aren't that hard to obtain either so I'm not sure, and it seems people feel that fatness should be very simple to cure.

**Comment by pedr69** [comment]
in my opinion fatness should be easy to cure shittily - ie dietine
and the proper "instant unfat" lipo needing more than 3 buttonpresses to make

currently dietine is both harder to make and works way worse, and i don't think more than 500u have even been made in total, people just don't know it exists

**Comment by Hinaichigo** [comment]
So for example,
dietine: recipie as easy as lipo's current recipe, cures fatness fairly fast with some tox or liver damage
lipozine: the capsaicin recipe with 1u instant cure with no side effects. 
What would people think of that?

**Comment by Eneocho** [comment]
Still unnecessary complexity without much reward. First rework the Gym Machines to more quickly burn fat (and for the lifting machines to burn fat as well), then add a method to reliably produce capsaicin without botany (electrolizing pepper spray does not count since you need access to sec's pepper spray wall-mounted tank, if it got mapped), only then would this be an ok (albeit kinda controversial) change.
Also, organ damage is an awful idea due to there not being ways to treat it reliably and fast, Peridaxon is fast but expensive and hard to find, while surgery is reliable but long and tedious. Strictly tox damage would be better, then again it would just mean that dietine+dylovene would become the new quickrecipe.

**Pull request closed without merging**
