### PR TITLE
New Loadouts for Wizard Apprentice

### PR DESCRIPTION
**Pull request by Arthurdentist**
addresses #6181 sort of.

Adds four (currently, more to follow) new loadouts for wizard apprentices.

School of Clowning:-
- Clown Curse
- Shoe Snatch

School of Misdirection:-
- Subjugate
- Blind

School of Technology:-
- Disable Tech
- Lightning

School of Muscle Magic:-
- Mutate
- Blink

Taking more ideas in this PR, we could do with a few more.

### CODE REVIEW

**Comment by Rei1226** [comment]
good shit, but do these also fuck over the wizard?

**Comment by Arthurdentist** [comment]
An apprentice can target their own master if that is what you mean but then they can do that anyway.

**Comment by Rei1226** [comment]
Right. I just think that shouldn't be possible, but that'd require more codework

**Comment by Arthurdentist** [comment]
I agree, but that is beyond the scope of this PR.

**Comment by Rei1226** [comment]
good shit then

**Comment by Kurfursten** [comment]
I think there should be a school of punching people in the face. Mutate + Timestop.

**Comment by AutismSpider** [comment]
@Kurfursten That's too strong

Zap master/School of Electromagnetic pulse? 

lighting bolt spell+Disable Technology

**Comment by Shadowmech88** [comment]
School of Immobilization
Time stop and flesh to stone.

School of Obstruction
Instant forcewall

School of Travel
Teleport and ethereal jaunt

**Comment by Arthurdentist** [comment]
your last suggestion already exists shadowmech

**Comment by Shadowmech88** [comment]
To be honest, I've never actually seen the existing list of apprentice schools.

**Comment by Arthurdentist** [comment]
I've added two new loadouts based on suggestions here.

Technology:- 
- Disable Tech
- Lightning

Muscle Magic:-
- Mutate
- Blink

still looking for more, I want there to be a lot of choices.

**Comment by WeinerMaster69** [comment]
Bruh aight heres what we do

Communist Memeifesto

You gotta buy it like a staff and it costs two wizzy points

When you click that shit, you spout some lines from the communist manifsto and anyone who hears it gets some debuffs and shit

Debuffs may include:

Instantly get max hungry 
Unremovable ushankas and russian shit
Shit load of alcohol enters their body
It takes them fucking forever to do anything because of the memes of production

Not a definitive list by all means mang, I really want this communism spell doe

**Pull request merged**
