### PR TITLE
Re-introduce Barricade Revamp

### PR DESCRIPTION
**Pull request by ghost**
Note : This is almost verbatum the commit text from #5292. The only major change was that barricades were repathed to inherit windows directly

This also overrides Kurfurst's changes, but since this PR also added barricade delay, this should pose no problem

Long overdue. Barricades have not been touched ever since they were introduced and hotfixed during Meteors devleopment. While they were created as a straight upgrade to police tape with a pre-existing barricade item, they never really stood out and failed even at the job they were intended for (fortifying hallways and existing window bays, preferably along with keeping the station in about decent shape despite explody explosions)

But now, after having worked on windows and other things, I decided to revisit this, hopefully for the better : 
- Barricade kits now have a new improved sprite which is no longer a copy-pasted plank sprite
  barricade_kit
- You can now create your very own wooden fort with the inclusion of directional barricades to go along full-tile barricades. They have much less health than full-tile barricades (60 for directional, 150 for full, 35 for window/airlock)
- All barricade-related code was moved from deployable (where it didn't belong, given that it's a structure and deployable is under machine) to a new barricade.dm file. barricade.dmi was also added for quick sprite reference
- Major code unfucking and refactor. All of the code for directional barricades was taken from windows. Note that directional barricades let air pass and aren't opaque. They also inherit window
- Some problems with barricades have been fixed, notably being able to instantly destroy them by spamming attack, and hitting windows/opening airlocks when trying to barricade them (now uses preattack with a proper return)
- Barricades can be deconstructed with a crowbar. It takes five seconds due to the fact that it instantly kills an otherwise sturdy item (60, or even 150 health is no joke). User needs to be on harm intent

Full showcase with a bit of fluff : 

fort_meteor

Discussion goes below

### CODE REVIEW

**Comment by Zth--** [comment]
Amazing. Now we only have to add keys to wooden doors and we're good to go

**Comment by Probe1** [comment]
Looks good except user needing to be on harm intent to deconstruct something.  

Harm should be reserved for breaking.  Other intents for building.

**Comment by dylanstrategie** [comment]
Well, harm DOES break the barricade

**Comment by dylanstrategie** [comment]
Will retry once the feature freeze is over and this won't get cucked by map priority. Also thanks for explaining how to do a git rebase

**Pull request closed without merging**
