### PR TITLE
should fix borers not transferring correctly

### LINKED ISSUE #11020: Borer in slime
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)

> Revision c6609a726a394fddd0f2ec974c28fd1c77810b02 
> 
> General description of the issue
> borer is kill when slime becomes adult
> 
> What you expected to happen
> get transferred to new mob
> 
> What actually happened
> i dead pls restart
> 
> Steps to reproduce if possible
> be in slime as borer while others feed it monkeys

### PR DESCRIPTION
**Pull request by Intigracy**
~~This isn't tested yet, I should get a chance to tomorrow.~~

~~Should fix #11020~~

This won't fix it, I see what's wrong and will fix it later.

When multiborer got added the has_brain_worms proc wasn't changed to use the new method of finding borers.

### CODE REVIEW

**Comment by ComicIronic** [comment]
Why on earth would this have fixed it?

**Comment by SkowronX** [comment]
Referencing a specific borer rather than the borer type in general?

**Comment by ComicIronic** [comment]
I think the specific issue is that it's only transferring one borer at a time, since has_brain_worms only returns the head borer. You should find a way to loop through all the borers in the body.

**Comment by Intigracy** [comment]
What Comic said.

It's pretty easy to do, there's another proc that got added that returns the list of borers in the body that I can use, I'll do it later.

**Comment by clusterfack** [comment]
Were you still planning on fixing this?

**Comment by Intigracy** [comment]
Probably this weekend, sorry.

**Comment by Intigracy** [comment]
meh

**Pull request closed without merging**
