### PR TITLE
Revert "forcemove for borgcharger"

### PR DESCRIPTION
**Pull request by Intigracy**
Reverts d3athrow/vgstation13#8789

Causing borgs to nullspace.

### CODE REVIEW

**Comment by ghost** [comment]
> testing is for chumps
> it was still merged

@Clusterfack
AAAAAAAA

**Comment by clusterfack** [comment]
Are you blind celt

**Comment by ghost** [comment]
Yes

**Comment by Intigracy** [comment]
I put that after it got merged you moron lmao

**Pull request merged**
