### PR TITLE
Absolute pathing in message_server.dm

### PR DESCRIPTION
**Pull request by Probe1**
🆑 

 * rscadd: The clown limit has been removed.

### CODE REVIEW

**Comment by SysadminJeroen** [comment]
Merge when? It has been since forever!

**Comment by JustSumBody** [comment]
>not secret repo

one job

**Comment by Megamaw** [comment]
(make it mimes too)

**Comment by Probe1** [comment]
We can do mimes on Bastille Day

**Comment by Exxion** [comment]
>Accurately describing the contents of an April Fools' PR

God damn it

**Comment by clusterfack** [comment]
@Exxion even worse they were trying to tag all prs with an april fools tag

**Comment by Exxion** [comment]
One of the most disgusting things I've heard

**Comment by Probe1** [comment]
I expect to see PRs from both of you since April Fools is so incredibly important but you've just been so busy and could only find the time to bitch and not contribute.

**Comment by Exxion** [comment]
Yeah exactly
I have plenty of time for bitching, but not quite enough to do anything significant

That said, we were complaining about you *doing* something, not you *not* doing something

**Comment by JustSumBody** [comment]
Jesus christ dude

**Pull request merged**
