### PR TITLE
Revised space ninja

### PR DESCRIPTION
**Pull request by DamianX**
The intent behind these changes is to turn space ninja into something that's more in line with the original anti-technology guy idea and less like a generally edgy murderer.
image

:cl:
 * rscadd: Ninja gloves grant a new ability: "Pulse Shuriken": detonates all thrown shuriken, releasing a small EM pulse, and destroying the shuriken.
 * rscadd: Energy katanas can now slice open shutters, such as those protecting the AI core. This is exclusive to energy katanas.
 * bugfix: Fixed a bug that allowed ninjas to throw shuriken with no delay. There is now a 0.8 seconds delay.
 * tweak: Wearing the ninja suit no longer doubles the throwing speed of shuriken.
 * rscdel: The cyber trophy belt can no longer hold humanoid heads.

### CODE REVIEW

**Comment by Eneocho** [comment]
Change it from Pulse Shuriken to Pulse Kunai and we have a deal.

**Comment by DamianX** [comment]
...but they're shuriken? If someone can make the sprites for kunai I can change them.

**Comment by adacovsk** [comment]
Make ninjas look more like Raiden from Mortal Kombat by giving them the straw hat and lightning too. Also require at least a couple sillycons to exist before triggering

**Comment by Blithering** [comment]
I got sprites for emp throwing stars lying around I think. Also an unused ninja suit sprite if you're interested?

**Comment by SageOfLight** [comment]
>remote detonate EMP shurikens

Okay now that makes me moist.

**Comment by PrimeDSS13** [comment]
very nice
While this is much needed, I'd also make sure it checks if any silicons are actually spawned in the round before it decides to roll.

**Comment by SageOfLight** [comment]
At bare minimum I think it should require an AI to spawn so there's a very specific central objective for the anti-silicon shinobi to stab.

**Comment by Kurfursten** [comment]
> The intent behind these changes is to turn space ninja into something that's more in line with the original anti-technology guy idea and less like a generally edgy murderer.

Actually it's the opposite. They started out originally as a generally edgy murderer on Goon, then we made a joke version of that called weeb who was also just a general murderer but pathetic, that got some upgrades then adapted into ninja. It was around this time when they got their new anti-silicon objectives.

I don't object, just setting the history straight.

**Comment by Blithering** [comment]
Would it be possible to turn the box of snap pops into a smokebomb spell (if that's not a thing yet), I don't recall a ninja using those willingly in all the rounds I've played.

**Comment by Eneocho** [comment]
> Would it be possible to turn the box of snap pops into a smokebomb spell (if that's not a thing yet), I don't recall a ninja using those willingly in all the rounds I've played.

This, if the smokespell leaves a wooden stump behind for a few seconds.

**Comment by ShiftyRail** [comment]
Not a fan of the belt no longer holding human heads, but that's easy to change.

**Comment by dunsel-hordon** [comment]
Should change out the smoke bombs and add a function to the suit that produces smoke and requires energy. Downside would be if you use up all your energy your suit locks up makes you move slower

**Pull request merged**
