### PR TITLE
Reduces number of spawning Hobo Shacks

### PR DESCRIPTION
**Pull request by jwhitak**
Why do the hobos get to just have free shanty towns? They're taking real estate away from the real owners of the asteroid... The Goliaths.

These big red BEASTS do not like the idea that random ASSHOLES in FIRESUITS can just MOVE IN! They will no longer permit THREE shacks on their asteroid, and are very much opposed to even TWO! If they smell additional shacks being constructed, they WILL retaliate. You are NOT allowed to inhabit a random building. They WILL use force to stop you.

image

Changes the probability of the number of hoboshacks spawning from (1, 2, 3) to (1, 1, 2).

100% untested.

[easy] [general] [tweak]

:cl:
 * tweak: Reduced the chances of a shanty town forming on the Roid.

### CODE REVIEW

**Comment by tomacatx2** [comment]
based, powerful and absolutely moving PR. fully endorsed

**Comment by ghost** [comment]
this also reduces the hobo spawns to 3-6 max
im ambivalent but its fine i guess

**Comment by Dacendeth** [comment]
I like one shack, means you can spawn with someone and hobo together easier.

**Comment by Kurfursten** [comment]
1-2 is good

But we need a Hobopolis/Squatopia roidvault

**Pull request merged**
