### PR TITLE
(Discussion) Buff batling gun

### PR DESCRIPTION
**Pull request by Securitymain**
[tweak]
## What this does

Buffs batling gun

## Why it's good

Batling gun is rarely ever used. In fact I am the only person that ever buys it and it's only because it's actually fun to use.

Things I believe make babe this not very viable except for the fun of it:
- It runs out of ammo quickly. If you rob all the seccie lockers you end up with an extra 50 shots. Then it's cargo crates or mechanics.
- If you are security, you have access to easy stuns anyway. If you aren't, you have a lot of other, better choices.
- It slows you down when you hold it. Countered by zine/vehicles.
- You can't put it in your backpack or on your armor, it's obvious to anyone what's coming.
- It's extremely expensive at 18 TC.
- You can't murderbone with it at all. The batons it fires do 10 damage. Once one connects all the other shots miss your target. If you click a stunned person, only the first shot connects while the others fly all over.
- Security officers, the job that uses STUN BATONS THE MOST, does not get a discount.

I would like to see this gun buffed because a gatling gun that fires stun batons is a really fun thing to have.
In this PR the cost gets reduced from 18/12 to 16/10 and ammo count is doubled from 50 to 100 and each baton giving 20 ammo up from 10. Security officers are added to the list of discounted jobs.
Increasing salvo shot count also works, but I left it at 5 for now.

I'd like to hear some opinions, especcially from people who have looked at this in their uplink once and chosen not to get it and why.

## Changelog

:cl:
 * tweak: Buffed batling gun

### CODE REVIEW

**Comment by jwhitak** [comment]
Current changelog of buffs
* Cost reduced to 16 from 18
* Security Officers can purchase the Batling Gun at a discount (added to Warden and HoS)
* Magazine size increased to 100 from 50, starting magzine remains full.
* Each baton gives 20 ammo, from 10

**Comment by SonixApache** [comment]
protip: get a genfab for increased ammo production

**Comment by Eneocho** [comment]
Make it take stunprods as ghetto ammo (weaker but more ammo per prod)

**Comment by SonixApache** [comment]
wouldn't fit the aesthetic

**Comment by BomberBro** [comment]
\>You can't murderbone with it at all. The batons it fires do 10 damage.
Did you put a plasma cell into the baton before loading?

**Comment by xeroxemnas** [comment]
> protip: get a genfab for increased ammo production

Can you even scan batons without the traitor scanner which would put you over the TC limit?

**Comment by Securitymain** [comment]
i think batons are a free scan, but it's a lot of setup
There's a reason xero picks the 357 and not this

**Comment by SonixApache** [comment]
do mind that it's more of a joke weapon than a murderboning weapon
making it hit prone targets might be interesting to look into as well at some point

**Pull request merged**
