### PR TITLE
[Meta] Minor fixes

### LINKED ISSUE #2260: [ALL except box/def] Teleporter Satellite is useless
Derelct:There's some bones and a circular saw. Its also damaged. Otherwise nothing.
Consider relocating your spider swarm to this map instead of on-station maint.

Others:No idea

### LINKED ISSUE #2359: Metaclub Paramed office issues
The paramedic office lacks any light fixtures, despite there being a light switch in the room. There is no oxygen cannister for filling up internals in the office, or even in the maint in the vicinity of the office. The paramedic EVA suit locker in the top left corner, below the defib locker cannot be closed on that same tile, needs to be moved before you can even try.

### LINKED ISSUE #2360: METACLUB Minisat SMESes improperly wired, no power source
Shits' gonna run outta power fast less ya slap down some wires, and again if you don't get some power source built there.

### LINKED ISSUE #2588: [metaclub] Visible pipe in ghetto bar
@iratepirate
Top right corner tile has a /visible pipe that does not get covered up.

### LINKED ISSUE #2594: [Metaclub] Cloning Lab Cloner incorrectly placed
The Cloning Pod isn't being detected by the console because it isn't adjacent to the console.

cloning

### LINKED ISSUE #2620: [Metaclub] Smelter output zone on the mining asteroid positioned incorrectly
When using the smelter the output is to the North which happens to be the direction that you feed in ore through the conveyor belt.

### LINKED ISSUE #2657: [Metaclub] Chem dispensers are starting at 0 instead of 50
yeah, what the title said. Boxstation's dispensers start at 50, while metaclub's start at 0, which is quite frustrating

### LINKED ISSUE #2705: Metaclub botany sucks
Everything about metaclub botany is bad. I do not currently have pictures so I will try to explain my best until I can get them. For starters, despite being the biggest botany, it has less trays compared to box and the maintenance is tiny. That would be a bit forgivable but the main problem is the xenobotany section. First there are no flora data disk boxes in there, so you can't even do it in the first place without admins spawning them for you. Second, the xenobotany equiptment is in a 3x3 room, at the ENTRANCE of botany, with objects filling every corner and only 4 out of 9 movable tiles. How are you going to work there when people use that area to go in and out of work? It is a very awkward place to have those machines, especially in a spot where you need to stand still for a little bit to use both of them. Since you cannot build the xenobotany machines, I am sure you cannot move them still, unless that has been updated. The best solution overall would be to remove metaclub, forget it existed, and hope a new map takes its place.

### LINKED ISSUE #2970: [Metastation] No atmospheric monitoring equipment in tcomms monitoring room
We need a console to monitor the temperature of telecomms in the monitoring room.  Check out Box to see how it works.  Otherwise, you have to go in there yourself and find out what temperature it is and that's not an optimal solution.  

Speaking of going into tcomms, it needs proper airlocks like the setup on Box.  Losing cold atmos inside tcomms is bad news.

image

### LINKED ISSUE #3253: [Meta] No Vox trading outpost, salvage ship jumps to nothing
Metaclub doesn't have a Vox trading outpost, which would (theoretically) be used during Vox raiders and allows miners to grab jetpacks from breaking into the Vox armory (plus other stuff)
The salvage ship still has a "trading outpost" beacon, jumping to it just puts you over the asteroid floating around on nothing.
Not a HUGE deal but I miss getting free jetpacks and gas canisters when the server changes to Meta

### LINKED ISSUE #3255: [Meta&others] Pod bay needs R&D console
See #3074 and https://github.com/d3athrow/vgstation13/pull/3213
After recent changes, you need an R&D console to sync research levels for the Spacepod fabricator. As far as I know, Box is the only map that has it yet.

### LINKED ISSUE #3267: Metastation Derelict windoors still fucked
The windoors on box derelict are fixed and act like proper objects, but the meta derelict still has the windoors you can just phase through, and aren't properly aligned with the r-windows around them.

### LINKED ISSUE #3998: (WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Metaclub Access Buttons
>Revision (Should be above if you're viewing this from ingame!)
36d41067a9269a882cc2805fe1b0434bb0ad7258

>General description of the issue
They dont work.

>What you expected to happen
Viro doors would open

>What actually happened
They didnt. Acceess button blinked but doors sayed closed

>Steps to reproduce if possible

### LINKED ISSUE #4022: EVA suits are behind an Atmostech door
Please change the EVA hardsuit door to engineering so more people can get at hardsuits during emergencies.  Both the engineering and atmostech hardsuits are behind a single door with atmos access required which leaves out mechanics and engineer variants that don't have atmos access.

### LINKED ISSUE #4130: Transit tubes cause pressure damage
I managed to fix this briefly somehow but now it seems to be causing damage again. It injures anyone trying to get to the AI satellite.

Maybe someone could code it so you cannot take pressure damage when inside a tube?

### LINKED ISSUE #4173: (WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Meta Club map issue
>Revision (Should be above if you're viewing this from ingame!)
b8d9f808405d2f6f3c3d82ef1ba4e01afb6681ba

>General description of the issue
Bad wiring for the northern emiters on meta

>What you expected to happen
Emitter to start when turned on

>What actually happened
I had to rewire hidden cable before being able to start singuloth safely

>Steps to reproduce if possible
Play Meta

### LINKED ISSUE #4175: Mechanics don't have access to telecomms on Metaclub
https://youtu.be/bTeYncx1xmI?t=18

It would be nice to fix the shit I'm supposed to fix.  Also it still doesn't have a temperature monitoring console.

https://github.com/d3athrow/vgstation13/issues/2970

### LINKED ISSUE #4231: [Meta] Surgery privacy shutters too private
they uh

ss 2015-05-01 at 08 12 09

you uh

ss 2015-05-01 at 08 12 34

you kind of can't reach the button to open them anymore

### LINKED ISSUE #4232: [Meta] Bar backroom needs RSF
One was added to Box, along with a few matter cartridges, however it's missing in Meta much to the bane of anyone wanting pizzaboxes or glasses

### PR DESCRIPTION
**Pull request by IratePirate**
fixes #4232
fixes #4231
fixes #4175
fixes #4173
fixes #4130
fixes #4022
fixes #3998
fixes #3267
fixes #3253
fixes #2970
fixes #2260

Earlier on was fixed (but I forgot to close them)

fixes #3255
fixes #2705
fixes #2657
fixes #2620
fixes #2594
fixes #2588
fixes #2360
fixes #2359

### CODE REVIEW

**Comment by PJB3005** [comment]
'Minor'

**Comment by IratePirate** [comment]
>conflicts

What the fuck? How?

**Comment by PJB3005** [comment]
Gas datum PR is causing this

**Comment by IratePirate** [comment]
Oh for fuck's sake. After a month, really? That's piss poor timing. I'd just spent several hours fixing up Box too.

**Comment by PJB3005** [comment]
I think the map merger comes with a merge driver (some install required), so fixing map merge conflicts shouldn't be too hard, then again I never have, but I'll have to soon.

**Comment by IratePirate** [comment]
That thing hates my PC, same with the map port cleaner.

I'll just redo it from scratch another time or manually merge.

**Pull request closed without merging**
