### PR TITLE
Alt-clicking on doors/shutters

### LINKED ISSUE #10466: You can table someone even if display shutters are down by alt-clicking.
Title.

### PR DESCRIPTION
**Pull request by kol1th**
Fixes #10466

### CODE REVIEW

**Comment by 9600bauds** [comment]
Awful fix famalam, make tabling require adjacency to the table

**Comment by clusterfack** [comment]
Yeah really, jesus christ you didn't even put a comment. Imagine the future coder who sees this and goes *"what the flying fuck is this for"*

**Comment by Exxion** [comment]
I'm with Bauds except I don't think what he suggested would work
Not sure exactly how it should be done, but simply preventing people from clicking on something is not a proper fix
That's what caused grabbable projectiles

**Comment by kol1th** [comment]
@Exxion But you can only not alt click when it's closed. Isn't that kind of the point of closing shutters? To not be able to interact/see what's under it?

**Comment by 9600bauds** [comment]
You can still rightclick, also you can still table a guy if you altclicked before the shutter closed

**Comment by kol1th** [comment]
Tell me how to fix it and I will. I'm still learning code.

**Comment by 9600bauds** [comment]
> make tabling require adjacency to the table

**Comment by Exxion** [comment]
I'm pretty sure you're still adjacent to things under doors

**Comment by ghost** [comment]
@Exxion would likely know.

**Comment by ComicIronic** [comment]
You would be adjacent to a table under a door. It would be better to use  ClickCross(), which checks obstacles.

**Comment by clusterfack** [comment]
@kol1th ?

**Pull request closed without merging**
