### PR TITLE
Adds supermatter shark and bloodvoid cult mobs sprites.

### PR DESCRIPTION
**Pull request by GoodG1448**
I made these in my spare time. I guess some day someone will code them into the game.

Bloodvoid gazer and moths:
pic

Ideas for these:

- Gazer could work as the basilisk from the roid or the hivelord. Either stare people down to boil their blood or spawn moths

- The moths could inject people with lexorin to drain blood supply.

Supermatter Shark:
A wise CE used to say: _"Sometimes you run into the shard, and other times the shard comes to you"_
pic2

Ideas for this one:

- Meme option for admins to spawn at round end

- X% chance of spawning this when an adult carp runs into the shard

- Space vault containing a SM crystal guarded by two of these.

[sprites]

### CODE REVIEW

**Comment by ValkyrieSkies** [comment]
The shark looks kinda awful, I'd keep it to just being an admeme.

**Comment by SonixApache** [comment]
[spritework done needs coder]

**Comment by brndd** [comment]
I thought the shark looked good, though it reminds me more of piranha or something (though it's not like a space fish needs to look realistic). Not sure what it should do though, just have carp AI but when it collides with people it straight up fucking ashes them?

**Comment by strawberrytan** [comment]
Lexorin causes suffocation, not blood loss

Hemocyanine is the bloodletting chemical

**Pull request merged**
