### PR TITLE
Captain now spawns with SecHUDS rather than regular sunglasses.

### PR DESCRIPTION
**Pull request by slightly-floating**
See title. Most Captains (maybe >80%?) go ahead and grab SecHUDS anyway. This saves them the trip to the brig and reduces setup time.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
While I have no issue with Captains grabbing secHuDs (and it's not like there's a shortage of it), it must be a deliberate choice to make the cap player realise what he's doing.

**Comment by KillFurries** [comment]
Sunglasses are cool. Sec HUD is cringe. Put some spare sec glasses in the captain's quarters in the locked locker if any virgin wants to wear them.
You also shouldn't reward lazy powergamers who are too lazy to spend 1 minute grabbing whatever crutch they need. There are a lot of things that people grab roundstart.
>reduces setup time.

Is this an RTS?
>Most Captains (maybe >80%?) go ahead and grab SecHUDS

Citation needed

**Comment by slightly-floating** [comment]
This how it's going to be? Sad. So sad. I wonder how many cumulative minutes will be wasted with the rejection of this PR.

**Comment by ghost** [comment]
To expand on what Shifty already said, this isn't an issue with captains having easy access to secHUDs. It's more of an issue with the captain role being a mixture of seriousness and RP fluff, with the flow of the round determining how the captain plays the role. Captain shouldn't be policing the halls unless there's an emergency, that's the job of security and the HoS.

**Comment by help-maint** [comment]
bro think of my KPM

**Pull request closed without merging**
