### PR TITLE
Box and Meta mapfixes

### PR DESCRIPTION
**Pull request by Probe1**
Closes https://github.com/d3athrow/vgstation13/issues/6022
Closes https://github.com/d3athrow/vgstation13/issues/6240

Adds PietyVend to meta, replacing the chapel locker and moves the one on Box to the original locker position.

Replaces the missing area path xenobio area 7 on metaclub with area 1, which was previously unused.

Deletes a random firelock over a random window in Metaclubs cargo.

Re-orients a firelock near arrivals to face the proper direction on Meta.

Adds a snake named Corpus to the permabrig on Meta to give it some character.

Removes a half dozen unary vents and scrubbers from Box that weren't connected to anything.

Reroutes the waste scrubber in xenobio that was negating the annoying airlocks everyone had to use.  On Box

Fixes a GODDAMN APC in metaclub xenobio that had a dir of 1 instead of 2 which ruined EVERYTHING.

### CODE REVIEW

**Comment by Probe1** [comment]
Box has been playtested.

**Comment by Exxion** [comment]
Its dir is 1 instead of 2
I think that's the issue

**Comment by PJB3005** [comment]
@Probe1 as @Exxion said, the pixel offsets for APCs are mapper only, really, in `New()` the APC's pixe offsets are set based on their `dir`, so that APC's `dir` is `1`.

**Comment by IratePirate** [comment]
Yep, certain objects nonsensically are dir based.

**Comment by Probe1** [comment]
Okay, what do we do to fix it?

**Comment by Exxion** [comment]
Yep

**Comment by PJB3005** [comment]
@IratePirate I'd say in the case of APCs it's very sensical.

**Comment by Probe1** [comment]
Should be good to merge now unless anyone knows of any map issues.

**Comment by dylanstrategie** [comment]
Yes, they are new map issues : 

You can gloss over lack of redundancy, but there are a bunch of obvious problems in here. That's Box Z-1 by the way, if you want the other renders and other Z-levels I can pull them up for you

pipes-0
wires-0

**Comment by Probe1** [comment]
I can click the map button in game I'm a big boy.  But I do need specific problems and not an easter egg hunt.

Also the lack of redundancy is absolutely intended.  It's a game.  We have to fix some things ourselves.

**Comment by dylanstrategie** [comment]
Open the pipe image and scroll around a bit, there are TONS of unconnected vents and scrubbers, and a lot of unconnected pipes (check under airlocks)

Also for the wire map, there also might be a few oddities

**Comment by Exxion** [comment]
I haven't exactly scoured every pixel of that pipe image, but about a minute of looking found me only one disconnected scrubber and two misplaced pipes. Could you possibly say where these tons of issues are?

**Comment by dylanstrategie** [comment]
I've honestly seen more, try the Security > AI Core > Engineering axis

**Comment by Probe1** [comment]
post a picture with problems circled?

**Comment by ihadtoregisterforthis** [comment]
Loose pipes on perma, AI upload and telecomms.

Unconnected stuff on the atmos locker hallway, viro and telecomms again.

Also on telecomms, there's weird stuff that happens if you crawl near the h/e pipes where you hop into the cooling system.

**Comment by dylanstrategie** [comment]
In red : Loose/unconnected atmospherics machinery
In green : Stacked, unlayered atmospherics machinery, which can lead to serious problems
In yellow : Xenobio's separate atmospherics system is clearly breached and any ventcrawling mob can easily enter and leave Xenobio by switching between the vent and the scrubber

pipes-0-annpted

**Comment by PJB3005** [comment]
...

Dylan, you're aware right, that 2 atmos pipes placed in a different direction don't conflict?

Right?

**Comment by dylanstrategie** [comment]
Right, but those aren't just pipes. It's pumps and valves with pipes crossing through them

I'm not certain about it, but it seems dodgy to me

**Comment by PJB3005** [comment]
Why the hell would it EVER be dodgy, have you looked at ANY of the pipes that cross over eachother on the map? Are those dodgy?

**Comment by Probe1** [comment]
I'll get on it.  Thanks for meeting me half way @dylanstrategie

**Comment by FudgePucker** [comment]
@dylanstrategie 
It isn't that dodgy to have pipes crossing across unary devices.
It is one of the main tactics of making super small atmospheric set ups (I made a 4 by 3 SME one time).
However you managed to miss, literally one tile over, a big fuck up, to the right of the scrubber there is a bent HE pipe that is crossed over with a straight normal pipe. Unless they are on different layers, this is impossible. Call the shuttle, the engineers who made this ship broke the laws of physics.

Other concerns. The separated atmospheric devices and pipes are in areas that are easily missed and already have functioning atmospherics, in the example of the one near atmospherics, you can't even see that scrubber, its under the suit storage machines. Of course they should still be fixed.

I thought the main reason why xenobio has a separated atmospherics was to prevent aliums and xenos and other fun experiments that might cause a plasma spill to not contaminate the rest of the station. But I guess because of the recent changes to vent crawling, it used to be that aliums could only crawl though vents and not scrubbers. I guess having that one scrubber go out into space separately instead of waste would fix it.

**Comment by Probe1** [comment]
All pipes dylan circled in red are removed.
All pipes circled in yellow (okay just the one) redone.
All pipes in green left alone because I don't understand the problem and regularly stack pipes in game.

**Comment by dylanstrategie** [comment]
Actually, you need to fix all green pipes except the ones in Toxins

This is ESPECIALLY true for Arrivals and Telecomms Chamber, it's breaking shit and I wager it's the reason why the cooling loop drains every single round

**Comment by Probe1** [comment]
Look I don't know about that but I know the crossed vents in arrivals don't cause problems and I'd be surprised.  

I'm fairly sure that telecomms gets mildly toasty some rounds because the CO2 canisters have no damn gas in them.  

I'm not saying you can't open your own PR after but I don't see any problems with them.

**Comment by FudgePucker** [comment]
@dylanstrategie 
>it's breaking shit and I wager it's the reason why the cooling loop drains every single round

Didn't you just see my last comment?
LITERALLY ONE TURF TO THE RIGHT THE BENT HE PIPE AND ANOTHER STRAIGHT HE PIPE ARE NOT PLACED RIGHT, OVER LAPPING THE WASTE PIPE.

onefuckingturftotheright

Oh but of course, it has to be the unary devices in a perfectly acceptable position, because you don't like the way it looks.

PS: I did the same test for the vent and the scrubber you did have circled, they went back down after being wrenched up.

**Comment by Probe1** [comment]
peeps

**Comment by N3X15** [comment]
Lemme know when this is okay to merge.

**Comment by Probe1** [comment]
changelogs up, playtested, ready on youo

**Comment by N3X15** [comment]
I was talking to the reviewers.

/cc @FudgePucker  @PJB3005 @dylanstrategie

**Comment by Exxion** [comment]
Cold.

**Comment by Probe1** [comment]
Confusing.  Dylan wants things reworked that I'm not going to rework in a fixin PR.  PJB and Fudgepacker want to discuss them with Dylan.

Don't think anyones got issues with the PR itself.  Dylan wants more changed and he is welcome to it in his own because I don't agree that the changes in question are bugs or not working as intended.

**Comment by PJB3005** [comment]
Yeah this should be fine.

**Comment by FudgePucker** [comment]
Merge it when ever you are ready. (Although I guess I will make a bug issue with the two over lapping waste pipes/HE pipes)

**Pull request merged**
