### PR TITLE
Dwarfism and Hulk Are No Longer Mutually Exclusive

### LINKED ISSUE #12036: Dwarfism Prevents Hulking Out
Intended, but I think it should be changed.

The hulk mutation doesn't make you larger, it just makes you stronger. There's no reason you can't be tiny _and_ muscular.

What does everyone else think?

### PR DESCRIPTION
**Pull request by Shadowmech88**
Closes #12036

:cl:
 * tweak: The dwarfism and hulk mutations are no longer mutually exclusive.

### CODE REVIEW

**Comment by clusterfack** [comment]
Lame, it's a feature

**Comment by Exxion** [comment]
Something being intentional does not automatically make it good

**Comment by Kammerjunk** [comment]
> Green midget strongmen punching down walls and windows while screaming in their leprechaun voices

**Comment by SangriaMonkey** [comment]
Wow three comments in half a week
https://youtu.be/T0pewqF8POE

**Comment by Intigracy** [comment]
https://www.youtube.com/watch?v=M-re0HMkldY

**Comment by ComicIronic** [comment]
>can't be big and small.

**Comment by Intigracy** [comment]
Bug an admin with POLLING so we can settle this, please.

http://ss13.moe/index.php/admins

**Comment by Shadowmech88** [comment]
@Intigracy 
A poll was already made.
http://ss13.moe/index.php/poll/76

**Comment by Probe1** [comment]
Gross.  Why would you merge this?  You know better than this @Intigracy .

You can't ask players if they want down sides removed.  It's like asking a child if he wants ice cream for dinner.

**Pull request merged**
