### PR TITLE
Friday the 13th causes 250 less luck to everyone

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[tweak]

## What this does
see title.

## Why it's good
today's the day. (try merge it before it's over maybe)

## Changelog
:cl:
 * rscadd: Friday the 13th is now a very unlucky day.

### CODE REVIEW

**Comment by Eneocho** [comment]
Luck has no real effect on anything other than assorted gambling and radstorm genes which by default always give you bad genes, I say go for it.

**Comment by dinnerwoerror** [comment]
soulful pull request

**Comment by Hinaichigo** [comment]
I think as is this won't apply to most mobs by default, because they have a null `base_luck` var, as the datum isn't initialized until `luck_adjust()` or `add_blesscurse()` is called. If the `base_luck` _datum_ is null,  the `base_luck()` _proc_ isn't called by `luck()` so this check would be skipped on those mobs.

You could maybe put the check in `luck()`, or mob initialization via `luck_adjust()` or making it into a curse.

> radstorm genes which by default always give you bad genes

They can give you good genes too even without any luck shifting.

**Comment by Hinaichigo** [comment]
> radstorm genes which by default always give you bad genes
They can give you good genes too even without any luck shifting.

**Comment by Eneocho** [comment]
> They can give you good genes too even without any luck shifting.

Good to know, but even then luck as a whole is a pretty underwhelming system, and we can't make it more relevant without screams about "MUH BALANCE REEEEEEEEEE"

**Comment by dinnerwoerror** [comment]
make it have 25% extra chance to have ranged shots narrowly miss

**Comment by Killette2** [comment]
What if luck gave you combat advantages but only against simple mobs?

**Comment by Eneocho** [comment]
Would help but not by much, cause most of the time you're fighting against other people, not simplemobs.

**Comment by SECBATON-GRIFFON** [comment]
> What if luck gave you combat advantages but only against simple mobs?

bad unthematic idea

**Comment by Eneocho** [comment]
He meant in general not as a friday the 13th only thing.

**Comment by Hinaichigo** [comment]
In previous discussions I think people have not wanted luck to directly affect things like combat RNG too much because it might turn into a powergaming/grinding thing.

**Pull request merged**
