### PR TITLE
Bar Sign Refurb Pack I

### PR DESCRIPTION
**Pull request by MintyEtude**
Woah! 4 old bar sign sprites [sprites] that had the happy default dorfy-man now are gonna get new sprites [sprites]! Two of them are even of particularly high-effort! Isn't that cool? AND THAT'S NOT ALL: these sprites that have been touched now also have descriptions so it's less boring to look at them. Wow! (what do you mean, it's unatomic? what do you mean, bay licensing?)

image

:cl:
 * imageadd: Some old bar signs have been refurbished with shiny new neon tubing. Take a look around your local establishment next time the rest of the crew gets stone drunk off whiskey and starts blasting ancient showtunes throughout the station.

### CODE REVIEW

**Comment by MintyEtude** [comment]
Dude I am looking EVERY-friggin-WHERE for that rogue pixel and he doesn't show up ANYWHERE (also please don't worry about removing whiskey implant-2 it was duplicate and that was pissing me off)
thelimbo

**Comment by jknpj** [comment]
Maybe it was just the wind.

**Comment by SonixApache** [comment]
cute!

**Comment by Kurfursten** [comment]
Oh boy it's your first time fixing icon conflicts. Ping me in coder discord if you need help.

**Pull request closed without merging**
