### PR TITLE
Attempt fix to mutated limbs

### PR DESCRIPTION
**Pull request by ghost**
Yes, return instructions. I'm pretty serious

Managed to stand up even after my left foot and right foot got malformed from clone loss, so it's worth a try

### CODE REVIEW

**Comment by wwjnc** [comment]
https://www.youtube.com/watch?v=2IRcM9qwDwo

**Comment by PJB3005** [comment]
Dylan, this does absolutely fuck all.

**Comment by RemieRichards** [comment]
Yeah... a return at the end of a function is already implied, you're doing quite literally as @PJB3005 said, "fuck all"

**Comment by clusterfack** [comment]
Reproduce a bug before making a change you think will fix it

**Pull request closed without merging**
