### PR TITLE
Fixes rocknuts potency not scalling

### LINKED ISSUE #25867: Rocknuts force and throwforce isn't scaling at all
what the title says. whichever idiot coded them fucked something up.

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #25867 
unga-bunga coding wins again

🆑 
* bugfix: Rocknut potency should scale properly now

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
we will we will rocknut

**Comment by DamianX** [comment]
I hate it

**Comment by ShiftyRail** [comment]
It's either this or rewriting botany in its entirety

**Comment by DamianX** [comment]
Or you can remove the spawn entirely and see what breaks and fix that instead

**Comment by ShiftyRail** [comment]
I can only agree, but testing all the possible edge cases is giving me a headache in advance

**Comment by DamianX** [comment]
then don't, we'll deal with them eventually or revert

**Comment by RealestEstate** [comment]
honest question, what's wrong with this solution?

**Comment by DamianX** [comment]
`spawn` is being used to re-order the execution of code, which is really bad because, as evidenced by this very issue, it makes it impossible to determine what the fuck is going on
This PR keeps piling on to that, albeit slightly, instead of addressing the issue at its core.
It works, but it's only going to get worse the more spaghetti is added.

**Comment by Exxion** [comment]
Fuck dude just delete the `spawn()`
Anything that relies on it is shitcode anyway
But I'm not convinced anything *does* rely on it

**Comment by ShiftyRail** [comment]
Fine, if you insist, give me some time

**Comment by ShiftyRail** [comment]
Potency does (seem to scale) with this method.

**Comment by RealestEstate** [comment]
glorious

**Pull request merged**
