### PR TITLE
Revert "Revert "adds Szechuan sauce""

### PR DESCRIPTION
**Pull request by kol1th**
Reverts vgstation-coders/vgstation13#14578

I stand for justice

### CODE REVIEW

**Comment by ghost** [comment]
you know what i think kolith is right for once

**Comment by kol1th** [comment]
JUSTICE

**Comment by SonixApache** [comment]
but

**Comment by yclatious** [comment]
For once in your life, you arent a cock sucker kolith

**Comment by Kammerjunk** [comment]
Don't say those words @adu6oo 
What a terrifying thing to say

**Comment by Exxion** [comment]
I think we've hit the meme quota for like a month

**Comment by ComicIronic** [comment]
Reminder that Sauce Helm is a plot to infiltrate the codebase and get users used to meme PRs in our Github.

**Comment by Kammerjunk** [comment]
You hit the meme quota for this month 5 days ago 😏

**Comment by kilozombie** [comment]
mem

**Comment by yclatious** [comment]
HE AINT GOT THE CAJONES

**Comment by PJB3005** [comment]
What if I merged this too?

**Comment by BobdaBiscuit** [comment]
AIN'T GOT THE CAJONES

**Comment by kol1th** [comment]
@PJB3005 Bet you won't pussy

**Comment by kilozombie** [comment]
Do it
you aint got the cajones

**Comment by Intigracy** [comment]
If it takes 9 seasons I want my mcnugget dipping sauce szechuan sauce morty

**Comment by ghost** [comment]
alright 7 emoji thumbs versus zero emoji down thumbs that means merge it

**Comment by Intigracy** [comment]
nothing quite like a revert war to ease tensions

**Comment by BobdaBiscuit** [comment]
THE MADMAN

**Comment by ghost** [comment]
THE MEMES JACK

**Comment by yclatious** [comment]
BACKSTABBING TEE GEE SCUM

**Pull request merged**
