### PR TITLE
Added vending vouchers and coinbox

### PR DESCRIPTION
**Pull request by ComicIronic**
Vending machines now have a lockbox which stores all the coins and other things they accrue over a round.
Vending machines now have vouchers in a general form:
- Vouchers can activate special behaviour for a vending machine
- Only voucher currently coded spawns a random hot drink for free. This is just one of many possible functions.

### CODE REVIEW

**Comment by Probe1** [comment]
Good one.  We were talking about adding vouchers for free discount dans to people who lost at arcade games a while ago.  This is the groundwork for much better but similar ideas.

**Comment by Arthurdentist** [comment]
This looks great, I think this has a lot of potential

**Comment by CptWad** [comment]
:+1: Time for free coins

**Comment by ComicIronic** [comment]
>time for free coins

That time is now.
The mint doesn't cost, you know.

**Comment by CptWad** [comment]
Yes but that takes effort and the mining station which is too much for your average joe robust assistant in need of the magic yellow gloves.

**Comment by ComicIronic** [comment]
Well, your average Assistant Joe will need QM access to get the coins, so he'll be as successful as ever.

**Comment by Exxion** [comment]
>Implying HoP doesn't give everyone who asks for it all access half the time

**Pull request merged**
