### PR TITLE
Meteors will now target the general center of the station like rods, massively increasing the amount that will cross the station

### PR DESCRIPTION
**Pull request by ghost**
Yep, same code as immovable rods. Dearly needed, but I guess no-one but me is ever going to touch Meteors and meteor-related code, right ?

This still means meteors will spread out when hitting the station due to spawning across the entire edge of space, but they will no longer graze or go wide, or just never hit anything

:cl:
 * rscadd: Meteors will now head for the general center of the station, instead of some random location which previously meant that a good half to two thirds will miss wide. You can thank me later for the Meteors rounds.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
I swear to God almighty I made a system EXACTLY for this
Don't override the general code for meteors, make the meteors wave event have high offsets by default for the end direction

This way meteors will strike like a cone closing in on the station

**Review by ShiftyRail — APPROVED** [review]

**Comment by ShiftyRail** [comment]
Code is ok
I'm ambivalent to the change itself, I'm not really a fan of meteor-like events.

**Comment by SonixApache** [comment]
if you're going to re-use the same line 10 times why not just make it the default

**Comment by ShiftyRail** [comment]
Because as I explained in d*scord, this proc should have the most generality possible 

The goal of this PR is to make meteors events attack the station, so the event should be edited, not the proc

**Pull request merged**
