### PR TITLE
Aaaaaaah

### PR DESCRIPTION
**Pull request by PJB3005**
:cl:
* rscadd: Screaming is now audible. Scream away!

### CODE REVIEW

**Comment by ghost** [comment]
Tbh it should stay after April fools

**Comment by ghost** [comment]
Please keep this after April fools

**Comment by kol1th** [comment]
MY EARS, OH GOD IT'LL HURT MY EARS!

**Comment by yclatious** [comment]
*internally buzzes*

Goddamit, no.

**Comment by mtpowell** [comment]
Add *exhaust

**Pull request merged**
