### PR TITLE
Canned Heat

### PR DESCRIPTION
**Pull request by DeityLink**
image

Originally wanted to add as a dumb badmin bus item, but after some thinking it feels like something that would fit as an atmos technician antag item. Feel free to discuss.

:cl:
* rscadd: Added a new Traitor Uplink Item, Canned Heat! Raises the temperature of the surrounding atmosphere by 1000 Kelvin. Discounted for Atmospheric Technicians and Chief Engineer traitors. Every player in the affected area will get a sound and chat warning. Used inside an inflatable shelter will raise its cabin atmosphere's temperature instead.
* bugfix: Fixed plastic spoons and sporks not having in-hand icons.

### CODE REVIEW

**Comment by DeityLink** [comment]
https://www.youtube.com/watch?v=vE4VlA_9OrI

**Comment by angryturnip** [comment]
At what size of a room does it start to become ineffective?

**Comment by cloutcode** [comment]
YOU KNOW THIS BOOGIE IS FOR REAL

**Comment by DeityLink** [comment]
> At what size of a room does it start to become ineffective?

It doesn't, it raises the temperature of the entire "zone" regardless of its size. Since it doesn't create any actual fire the damage it does to the station is relatively easy to fix so I'd like to allow it.

**Comment by DeityLink** [comment]
https://github.com/vgstation-coders/vgstation13/assets/7573912/165f541e-86ac-4a04-b384-886e0c9627f5

**Comment by Hinaichigo** [comment]
Might be nice/consistent if it released a certain amount of joules into the air instead.

**Comment by Eneocho** [comment]
Kinda useless considering you can use the ZAS gun technique for the exact same effect. It doesn't take more than 10m for a good atmosian.

**Comment by Dacendeth** [comment]
that's like saying explosive implants are useless because TTVs exist.

**Comment by Eneocho** [comment]
TTVs are effectively discount nukes that can destroy a good chunk of the station, while explosive implants are a FUCK YOU tool if you get got or you find a victim you want to make boom, they don't fill the same niche.
The Canned Heat and the ZAS Gun tech do the same, but one of them costs TC while the other is free.
I can see the use for it, but it is mostly irrelevant considering you can do the ZAS gun trick.
A better implementation of this (in my opinion) would be a 6 pack, 3 canned heats that set the room to 1000K, 3 canned colds that set the room to 1K. That way you can fully take advantage of ZAS fuckery and hot/cold fuckery, and being able to fuck with heat 6 times per purchase would be way more worth for the limited resource that are TC than just once per purchase.

**Comment by PrimeDSS13** [comment]
Kinda useless considering you can use the aloe growing/mint cooking for the exact same effect. It doesn't take more than 10m for a good botanist/chef.

**Comment by Exxion** [comment]
It would be more realistic and consistent if it increased the room's thermal energy by a fixed amount, but in practice, this would suck. It would either do nothing at all to larger rooms, or turn smaller rooms hotter than the sun.
I'm not sure how I feel about this item as-is working on an *unlimited* zone size, though.

**Comment by Eneocho** [comment]
>Kinda useless considering you can use the aloe growing/mint cooking for the exact same effect. It doesn't take more than 10m for a good botanist/chef.

I get what you are saying, but the point stands. Consider, though, that mint is only available roundstart to the traders and gambling with nofruit/exotic seeds/mutations to get an aloe seed or mint toxin is unreliable at best. Meanwhile, for the ZAS gun tech you only need a flamethrower, which you can make in 1 minute and a plasma tank that has more oxygen than plasma inside. You can do that within 2 minutes for a weaksauce blast, or make a quick space cooling loop in 5 minutes for the spacecold (thus more powerful) shot, not to mention a can has enough gas inside to be used several times; just hook a plasma can and an o2 can to a small cooling loop and use a gas mixer to get more oxygen than plasma onto your receiving can (and thus tank).

**Comment by pedr69** [comment]
how dangerous is this if you pull it in the central primary or bar or another large sized room
i imagine emagging a couple firelocks open so the zones merge you can absolutely demolish a station with one of these

**Comment by Eneocho** [comment]
> how dangerous is this if you pull it in the central primary or bar or another large sized room i imagine emagging a couple firelocks open so the zones merge you can absolutely demolish a station with one of these

`Steal the RCD.`
`Disassemble some walls in maintenance that no-one will notice.`
`The entirety of the station is now one large atmos zone.`
`Pop open the canned heat.`
`???`
`4 degrees of station bacon.`
I take it back, that sounds powerful and unique, it is a special niche the ZAS gun can't directly fill (at that point it's better to just plasmaflood and set fire to it or something). I still think that by itself the canned heat is kinda weak, but on that specific scenario it is incredibly powerful.

**Comment by DeityLink** [comment]
After a first test, it seems emagging doors won't suffice as they keep zones separated, they are connected though, but the heat won't transfer until you move the firedoors, and then it will progressively dissipate as it mixes with cooler air.

image

**Comment by DeityLink** [comment]
second test, if you deconstruct doors instead of just emagging them, only then will the zones merge, and that's when the tool gets increasingly dangerous. This can be achieved fairly easy if you can get your hands on an RCD.

image

**Comment by DeityLink** [comment]
To take that into account I've increased the TC costs to 12 for regular crew and 6 for atmos techs, CE.

**Comment by pedr69** [comment]
breaking windows that don't have a pressure delta(ie open to space on 1  side) also merges zones right?
i like it because it finally gives me an incentive to learn how zas works and it might also teach other spessmen that fire extinguishers can cool superheated rooms

**Comment by PrimeDSS13** [comment]
I would make it 10, so even a non-engineer can get two of them.

**Comment by Eneocho** [comment]
I'd add a description somewhere implying of the zones check, cause for this to be powerful enough to warrant the 12TC, you need to understand how the game checks for atmos and that isn't directly obvious.

**Comment by Hinaichigo** [comment]
It seems sort of strange to have atmos zones be 'canon' in-game. Maybe instead it could be all tiles with an unobstructed path to them in a certain radius or something like that.

**Comment by Eneocho** [comment]
> It seems sort of strange to have atmos zones be 'canon' in-game. Maybe instead it could be all tiles with an unobstructed path to them in a certain radius or something like that.

That's the thing, atmos zones are effectively one huge bendy tile. Checking for actual tile atmos goes against making atmos zone based in the first place, though I guess it wouldn't be that damaging performance-wise to use a tile system on the cans, as they wouldn't be constantly updating, but rather a single update, after which there's no more need for tile checks.

**Comment by Exxion** [comment]
You wouldn't have to actually break it into tiles. You could just count the valid tiles and scale the thermal energy by that.

**Comment by DeityLink** [comment]
> I would make it 10, so even a non-engineer can get two of them.

I'll refrain from further TC tweaking until we've seen it in the players' hands.

**Comment by Blithering** [comment]
Canned air when? 
https://www.youtube.com/watch?v=kCX6H90RvPU

**Comment by Kurfursten** [comment]
Personally I think flat increasing temperature by 500 instead of using energy is egregious but I understand what you are going for

Fix conflicts

**Comment by DeityLink** [comment]
fixed conflicts

**Comment by Exxion** [comment]
I just noticed that you don't call `update_values()` after increasing the temperature

**Comment by DeityLink** [comment]
What's it do?

**Comment by Exxion** [comment]
Updates the `gas_mixture`'s values. Namely pressure. It should always be called after manually editing anything in a `gas_mixture` (which should generally be avoided anyway)

**Comment by DeityLink** [comment]
Luckily it seems to do so automatically, without the need to call it.

**Comment by Exxion** [comment]
No, it's just that it's called frequently in zones because a lot of things happen in them. It should still be called whenever a value is manually changed.

**Comment by Exxion** [comment]
It does indeed not update the pressure if opened in a room with no open doors and containing no vents, scrubbers, breathing mobs, etc. Note that using the air analyzer calls `update_values()` before outputting the readings, so you have to use the ghost verb or something to detect this.

image

**Comment by DeityLink** [comment]
#34657

**Pull request merged**
