### PR TITLE
Adjusts the recipe for Bleach

### LINKED ISSUE #14367: Bleach Recipe Is Bad
Instead of 4 parts + 4 parts + 2 parts = 2 parts, it should be 2 parts + 2 parts + 1 part = 1 part.

This matters because if you have 2 space cleaner, 1 oxygen, 2 salt in your beaker, it won't mix. You simply can't do odd numbers. And the chem dispenser only works in increments of 5.

Basically, you can't make bleach with no leftovers with a large beaker without taking the beaker out of the dispenser, your closest option results in 14 bleach and the aforementioned 2-1-2.

### PR DESCRIPTION
**Pull request by ghost**
Adjusts Bleach to use 2 Sodium Chloride and Space Cleaner and 1 Oxygen rather than 4 and 2 respectively, at Kurfursten's suggestion.

Closes #14367

:cl:
 * tweak: The recipe and resultant amount for Bleach have both been halved for ease of mixing.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by SysadminJeroen** [comment]
The wiki needs an update.

**Comment by Probe1** [comment]
Good catch.

**Comment by SysadminJeroen** [comment]
@Probe1 Do not forget the Quik-Guide.

**Comment by ghost** [comment]
Done!

**Pull request merged**
