### PR TITLE
Adding sake sprites and a new cocktail for it

### PR DESCRIPTION
**Pull request by brndd**
[sprites] [gameplay]

Adds a sake bottle sprite, sake cup sprite (for sake poured into a drinking glass), and a new sake cocktail, the sake martini.

Spritework courtesy of basil.

unknown

:cl:
 * rscadd: Sake now has a bottle sprite and a glass sprite, courtesy of basil.
 * rscadd: Sake is now available in the booze-o-mat and the booze dispenser.
 * rscadd: Added the sake martini cocktail, mixed with equal parts gin and sake.

### CODE REVIEW

**Comment by Tokanova** [comment]
can we have sake heal ninjas?

**Comment by DrSnips** [comment]
Juice that makes you say YOOOOOO.

**Comment by SkowronX** [comment]
いただきます

**Comment by brndd** [comment]
This needs a wiki update if it's merged btw so might want to add that tag.

**Comment by spoonylove** [comment]
beer+Sake for sake bombs recipe

**Comment by brndd** [comment]
Adding recipes is better done after this PR.

**Pull request merged**
