### PR TITLE
Moffuggin Roid Fixes

### LINKED ISSUE #19313: Roidstation miners get mining hardsuits rather than survivor suits.
According to https://github.com/vgstation-coders/vgstation13/pull/18920 mining and science are meant to share a single multipurpose suit type, however only science have survivor suits with mining still getting their proper mining hardsuits.

### LINKED ISSUE #20814: Evac Shuttle Doors have Incorrect ID settings on Roid
(WEB REPORT BY: subs455 REMOTE: 172.93.109.202:7777)
# Revision
f410ab446bf2d295613bf4d99d4123834e1b7f0b

# Description
The Airlocks on the right side of Escape on Roidstation have incorrect ID settings.
# Steps to Reproduce
Try to open it.
# What you Expected
The door to swing open when i walk through it
# What Actually Happened
It stays closed.

### LINKED ISSUE #23856: waste and distro are linked at roundstart on roid
#### Steps to reproduce

*accidentally open a super cool plasma cannister
*the entire station gets plasma flooded

### LINKED ISSUE #24153: You can't fuck with the shuttle on roid
Using shuttle burners is tradition, but on this map they are walled off. This is painful.

### LINKED ISSUE #24602: no blue toolbox in roid bridge
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
70337a2a04d0c525b7412ba23f3681b83b0a98c8

# Description
says on tin

### LINKED ISSUE #25129: Roid Station Captains office has no Lighting Feng Shui
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
293fe7477b44e2b6dc7e30e3700c9f11755d7da1

# Description
The whole right side of it is fucking dark its terrible.

### LINKED ISSUE #25827: Roid Station medbay Feng Shui immediately east of cryo is bad.
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
b8af45303390f398912b98331ff36dc5f59b2a4b

# Description

Please add a light to the wall east of cryo or something so that the lighting isnt needlessly dark.

### LINKED ISSUE #25912: Roid bar door has no access requirement
Literally any living mob can open it.
Please I need my shitter shelter

### PR DESCRIPTION
**Pull request by Kharkov72**
closes #23856 (already fixed)
closes #20814 (already fixed)
closes #19313 (feature and also sci has the hardsuits now)
does #24587 for roid
closes #25129
closes #24602
closes #25912
closes #25827
closes #24153 :

Untitled

also gives the bartender full glass and metal stacks
[roid]

:cl:
 * bugfix: Various Roid Fixes

### CODE REVIEW

**Comment by Irradiation** [comment]
>not reinforced plasma glass on the shuttle engines like the other maps

Truly a powerful man

**Comment by Kharkov72** [comment]
A. Unlike other shuttles they're completely sealed rooms with only doors to let the fire out instead of usual windows
B. What do you take me for a fucking pussy

**Comment by PrimeDSS13** [comment]
yes but also
image
image

**Comment by Kharkov72** [comment]
See B in previous post

**Pull request merged**
