### PR TITLE
Better brain deadchat check

### PR DESCRIPTION
**Pull request by Sprok0**
This is probably a better way to do this, rather than just checking the brainmob's loc

### CODE REVIEW

**Comment by Intigracy** [comment]
It keeps the reference to its container when in a mech then?

**Comment by Sprok0** [comment]
Yes, so it knows to put the mob back into the mmi when ejected

**Comment by ComicIronic** [comment]
It is somewhat better. Is the same code already in place for talking brains?

**Comment by Sprok0** [comment]
What's a talking brain?

**Comment by ComicIronic** [comment]
When you're a brain, you can talk to deadchat so long as you aren't alive.

**Comment by Sprok0** [comment]
Oh, that's almost the same as this,
```if(!(container && (istype(container, /obj/item/device/mmi))))```
Is the check to see if a brain's speech should go to deadchat

**Comment by ComicIronic** [comment]
Can you unify them into a single brain proc to avoid the code duplication?

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
