### PR TITLE
Revenge of the Mannequins

### LINKED ISSUE #22981: Summon mannequins/statues spell for wizards
Just to have a spell that can have synergy with the staff of animation. It would create a random statue (marble or wood) or mannequin (cult or cyber), not sure if anchored or not but it doesn't matter since they will start walking on their own once animated. Maybe a cooldown of 15-20 seconds and a cost of 20 points?

[featurerequest]

### PR DESCRIPTION
**Pull request by DeityLink**
image

Fixes #22981

Also renamed human_face.dmi to hair_styles.dmi so it actually fits its description.

:cl:
* rscadd: Added new mannequin types! Using either a marble (obtainable from cargo) or wooden (craftable) block, you can now sculpt a human woman, or a corgi. Said corgi mannequins can wear items just like real corgis do.
* rscadd: Spessmen have gotten better at sculpting mannequins, and can now sculpt their hair and beards.
* rscadd: Mannequins mobs, such as those that can be found on the drone ship, or created by wizards using a staff of animation on a mannequin, are now able to fire the guns in their hands, and benefit from the armor they are wearing.
* tweak: Flesh to Stone now turns humans, vox, monkeys and corgi into marble mannequins instead of statues. This means that items can be attached on them or removed, but also that when hit by a bolt of animation, they will fight using the items in their hands and benefit from the armor that they are wearing.
* tweak: Apetrine no longer kills or makes unclonable the mobs trapped in a statue if said statue was mostly undamaged (if the mob's HP were above 50 when they got trapped) although they will still take a fair bit of damage and might die shortly after if not given medical care.

### CODE REVIEW

**Comment by Killette2** [comment]
I'm a little confused with the cockatrice related change, how will it work now? The other day I had to grind the bird to help make the cure but are you implying statues can simply be smashed or what?

**Comment by GreatBigFailure** [comment]
Very neat.

**Comment by Eneocho** [comment]
> 
> 
> I'm a little confused with the cockatrice related change, how will it work now? The other day I had to grind the bird to help make the cure but are you implying statues can simply be smashed or what?

As I read it I believe it means that If you apetrine a "healthy" statue, it won't instantly permakill the guy (but spare his items) like apetrine does currently, but will instakill the guy if he was petrified while already injured.

**Comment by Eneocho** [comment]
The rebirth of the Tomboy GF mannequin gimmick.

**Comment by Eneocho** [comment]
Can you change the "haircut" of a statue if you change your mind? Also, on a side note, can you actually paint the mannequins? Spess paint is a foreign concept to me.

**Comment by DeityLink** [comment]
> 
> 
> I'm a little confused with the cockatrice related change, how will it work now? The other day I had to grind the bird to help make the cure but are you implying statues can simply be smashed or what?

* If a wizard did the statue, the mob will automatically come out of it after about two minutes unharmed (well, if the statue took damage, they WILL take the damage upon coming out)
* If a cockatrice made the statue, it never expires and the mob instantly dies.
* Smashing a statue will always gib the mob inside. Generally the head comes out so you can get it back this way.
* Dissolving a statue with apetrine will now deal 50 brute damage to the mob inside. If the mob still has above 0 hp after that, they will come out either alive if a wizard petrified, or dead if a cockatrice petrified them, but still defib/clonable either way. If they had 0hp or less, they'll be husked and their brain will have to be extracted.

**Comment by Blithering** [comment]
>Flesh to Stone now turns humans, vox, monkeys and corgi into marble mannequins instead of statues. This means that items can be attached on them or removed, but also that when hit by a bolt of animation, they will fight using the items in their hands and benefit from the armor that they are wearing.

How does this account for stuff they already have equipped? Do they become loot pinatas? Do they appear as a naked statue regardless? Can you layer clothes on top of statue clothes?

**Comment by DeityLink** [comment]
> 
> 
> > Flesh to Stone now turns humans, vox, monkeys and corgi into marble mannequins instead of statues. This means that items can be attached on them or removed, but also that when hit by a bolt of animation, they will fight using the items in their hands and benefit from the armor that they are wearing.
> 
> How does this account for stuff they already have equipped? Do they become loot pinatas? Do they appear as a naked statue regardless? Can you layer clothes on top of statue clothes?

The clothes the have equipped when they become statues become equipped onto the mannequin, and re-equipped onto them once they get freed. So yeah you can replace their clothing while they're statues.

**Comment by Blithering** [comment]
Well, I suppose that does kind of make sense, but I do not look forward to trying to recover all the shit stolen after getting statued.

**Pull request merged**
