### PR TITLE
Re-introducing Borer brain control...exclusively for monkeys!

### PR DESCRIPTION
**Pull request by DeityLink**
It's my birthday, please let me have my playable monkeys at long last!
More seriously though, I often get the "borer egg about to hatch" prompt but never click it because I don't want to become another player's ~~parasite~~ symbiote, while other players who actually like to play borer may not find a willing player to host them. Being able to take control of a monkey should offer a nice compromise for both of those types.
Of course if the monkey was being controlled by the player, they can still resist to take back control, and I'm not giving borers back their power to harm them.

:cl:
* rscadd: Borers can now use the Assume Control verb when inside a monkey. If the monkey becomes a human afterwards, they lose control.
* rscadd: Borers can now secrete Methylin.

### CODE REVIEW

**Comment by Hoshi-chan** [comment]
Happy birthday!

**Comment by Irradiation** [comment]
What happens if the monkey gets poked by a SE syringe and turns into a human while the borer inside?

**Comment by Shadowmech88** [comment]
A PR has been made for this sort of thing before, and I'll say the same thing here that I said there:
However great you make a support role, nothing beats being able to walk around as something with hands. If borers have the ability to take control of monkeys, then I worry that it's all players who inhabit borers will ever want to do, especially if they can secrete methylin to turn their monkey hosts into tiny full-fledged crewmembers. I feel like a lot of the interesting gameplay alterations offered by borers would be lost if every borer immediately ventcrawled to Genetics and hopped into a monkey. Why ride shotgun when you can take the steering wheel, right? I feel like giving a support role like borer or pAI the ability to gain such a large amount of agency, and with little or no help at that, defeats the purpose of it existing as a support role.

I understand the desire to allow dead players to play monkeys, but I think a better option would be the creation of some kind of Ape Escape-style intelligence helmet for monkeys that polls observers to take control, obtainable from R&D or otherwise.

**Comment by DeityLink** [comment]
I'd like that helmet, but in the meantime, I think this deserves to be given a shot.

**Comment by DeityLink** [comment]
That being said

>However great you make a support role, nothing beats being able to walk around as something with hands.

I'm basically upgrading borers to something in-between of a pAI and a diona, I'm making sure that using a DNA injector will not let the borer be in control of a human.

**Comment by Shadowmech88** [comment]
Personally, I'd prefer borers to be merely a sidegrade to pAIs, having different capabilities, but not necessarily more capability.
The current relative lack of features for pAIs notwithstanding.

**Comment by Blithering** [comment]
pAI compatible trauma override harnesses when?

**Comment by Kevak** [comment]
What happens if a borermonkey gets culted?

**Comment by DeityLink** [comment]
@Kevak The borer-controlled monkey will now be able to use cult stuff, however the cultist role is tied to the mind, which isn't swapped when borers take/release control, therefore when the borer detaches itself, the cultist role will remain with the NPC monkey only. If another borer takes over afterward, that borer will now behave like a cultist, etc
It's janky to say the least.

**Comment by Kevak** [comment]
What happens if a converted borer climbs into a noncultist monkey?

**Comment by DeityLink** [comment]
Borers are simple_animals, like corgis, cows, or space carps. Only carbons may become cultists. That is:

* xenos (humanoid and larvae)
* martians and gondolas
* humans and all species
* monkeys and all species
* slimes

So if a borer that went in a cultist monkey then leaves it and goes in another monkey, it won't have any cult powers there.

**Comment by DeityLink** [comment]
@Irradiation I've sent a commit that ensures that borer controlling a monkey lose control if they get humanized.

**Comment by spoonylove** [comment]
Whats the harm of letting borers control monkies when diona exist to allow players to hop back into the round in a role with hands? More variety is nice to spice things up. Someone may want to be a monkey, someone may want to hop in and be an observer to someone. This can give borers the option to dick around with the crew while they build chems to go lay eggs as well. Perhaps a compromise would be restrict it to first gen borers? Or be an evolution they can reach by growing in someone's head? That way it takes time to see borer controlled monkies.

**Comment by SonixApache** [comment]
>another player's parasite

**Comment by ghost** [comment]
If you're concerned about borers losing their original motivation to inhabit player hosts, make it so they can only take control of a monkey if they spent enough time getting strong enough inside a player controlled host first.

**Comment by DeityLink** [comment]
@codeungabunga that'd go against the two motivations for making this PR highlighted in the OP, and would be annoying for players in-game. Can't wait for "please let me hang on two you for 10 minutes I need to do it because our coders are idiots".
@SonixApache Ok so first you need to hatch a borer egg, and secondly you need that borer to reach a monkey, and that monkey to stay still for 6 seconds which is pretty hard especially when they're in a pen where they keep bumping into each others. My point being, that it's NOT a turbo-respawn, it's time consuming, especially compared to diona, and that unlike diona, they don't even get the possibility of becoming actual humans again. Also unless a scientist is on their side or they get handed a science/all access ID, they shouldn't even be able to hatch more eggs, which means by default we really won't see more than one at a time, especially if no scientist takes care of hatching the first egg.

Oh and one last argument, this gives borer another purpose in life (roleplay as a brain-slug controlled monkey) instead of hunting for antags to become their side-grade, like they're famous for doing.

**Comment by ghost** [comment]
I would personally let them control even full mindless humans, but I know better than to suggest fun.

**Comment by DeityLink** [comment]
Let's not go that far.

**Comment by ArchSunder** [comment]
based

**Comment by SonixApache** [comment]
@DeityLink please do remember that shitters have ways of getting past airlocks that do not involve ID cards, and that borers can produce infinitely more borers.
What happens when a monkey gets human'd with a borer behind the wheel? Does the borer lose control?

**Comment by DeityLink** [comment]
@SonixApache 
`What happens when a monkey gets human'd with a borer behind the wheel? Does the borer lose control?
`
image

**Comment by Shadowmech88** [comment]
Would a borer-monkey on methylin be capable of setting up a borer farm in maintenance and stealing enough monkey cubes to single-handedly create a monkeytide army?

**Comment by DeityLink** [comment]
That sounds technically possible but I can't say for sure how hard it'd be to pull off. Borer give birth through eggs that need to be in a plasma atmosphere, and there are no vents where to vencrawl in maint, so it's unlikely they could pull it off without the crew seeing it coming.

**Comment by Kurfursten** [comment]
I can agree to this as long as borers lose the ability to do any of their borer things while in a monkey. I think we can all agree it would be kinda dumb to have Monkey+++ running around healing itself with chemicals,  making infinite methylin for itself, or using all the meme armborer powers like EMP or hookshot.

**Comment by Shadowmech88** [comment]
>or using all the meme armborer powers like EMP or hookshot

Limb-based powers can't be used in monkeys, or any non-humans for that matter, due to the lack of limbs for the borer to inhabit. Any borers inhabiting carbons only receive the default borer powers, which I assume are the head-based powers.

**Comment by DeityLink** [comment]
@Kurfursten That is the case. To give themselves methylin they need to release control/re-assume control (which takes about a minute during which they're mostly harmless). Furthermore, when inside a monkey, only the "head" borer verbs are available.

**Comment by DeityLink** [comment]
I checked the PR that got closed.

> `+105 −170` compared to my `+21 −8`
> removing passive brain damage while controlling
> brain damage that reduces the time it takes to assume control instead of increasing it
> borer chat while in control

Yeah no shit, they touched too many things at once.

**Comment by Kurfursten** [comment]
I am going to go ahead and give this the green light but I want people to monitor this (and I will as well) for effects on round health. Please feel free to message me or post here with findings.

**Pull request merged**
