### PR TITLE
Ports twintail hairstyle from TGstation, made by Mordeth

### PR DESCRIPTION
**Pull request by SonixApache**
Relevant TGstation PR:
https://github.com/tgstation/tgstation/pull/43564
Relevant Baystation PR:
https://github.com/Baystation12/Baystation12/pull/14275

greyshirtjulianne

### CODE REVIEW

**Comment by Lunstra** [comment]
I'd say suffer not the waifu to live but that fucking slime hairstyle PR passed so just fuck my shit up tbh.

**Comment by AI-Is-Rogue** [comment]
let's go into dorms and apply makeup to each other: the hairstyle

**Comment by yclatious** [comment]
Oh boy, space bartender lesbians from meme game.

Eh fuck it, lets indulge the tranny lads, we gotta be a modern and progressive station. We all do love Arie, even if some of us more than others. Not quite so much sonixhu 2, MaiPai boogaloo, but ah well, cant stop the danes from being danes

**Comment by DamianX** [comment]
upvoted because it's content and therefore inherently good

**Comment by SonixApache** [comment]
maybe i should just port the entire batch

**Comment by ghost** [comment]
stop trying to add this apalling fetish content

updooted

**Comment by ghost** [comment]
japanese nanites when

**Comment by tuypo1** [comment]
God I hope this doesn't lead to more waifushit, although frankly I am surprised we did not have such a hairstyle already

**Comment by ShiftyRail** [comment]
If we're going to classify hairstyles as waifus/husbando baits then why not just default to Baldie + buzzcut tbh

**Comment by tuypo1** [comment]
>If we're going to classify hairstyles as waifus/husbando baits then why not just default to Baldie + buzzcut tbh

I mean it is a plasma research facility and hair could be a fire hazard. 
Actually that gives me an idea, hair should burn off in fires

**Comment by SonixApache** [comment]
oh, i forgot a changelog

**Pull request merged**
