### PR TITLE
Optimizes tcomms a little

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Also removed the 75 log message check, this only affected what was shown clientside which has been optimized. The real fix of #25649 is CHECK_TICK

:cl:
 * bugfix: Checking a telecomm server's message log should lag less.
 * bugfix: The telecomm server message logs are no longer limited to 75 message.

### CODE REVIEW

**Comment by Exxion** [comment]
I do not think you have tested this

**Comment by boy2mantwicethefam** [comment]
It's still messed up (although significantly less due to CHECK_TICK) but it doesn't have anything to do with the way tcomm logs are displayed to the user using the console.
Radio chatter could use some clean-up given the easy potential for abuse (30 station bounced radios getting heard by one guy saying one message is gonna create 30 messages and spam them to everyone, and then brick the telecomms because there's a ton of messages waiting to get processed and sent along to players) but it's pretty complicated and I don't wanna do it yet.
This also needs to be separated into pages

**Comment by Exxion** [comment]
You can just leave them where they were and make them `static`

**Comment by content-to-remain-anonymous** [comment]
why do the traffic logs have a long string of random text added anyway? why do speakers/machines not get logged? what do the gigabytes mean?

**Comment by Exxion** [comment]
I mean you can just leave them where they started and make them static

**Comment by Exxion** [comment]
He never did do that, but whatever

**Pull request merged**
