### PR TITLE
PALADIN gets a facelift

### PR DESCRIPTION
**Pull request by Intigracy**
Before:

```
1. "Never willingly commit an evil act."
2. "Respect legitimate authority."
3. "Act with honor."
4. "Help those in need."
5. "Punish those who harm or threaten innocents."
```

After:

```
1."Thy main purpose is to uphold all standards of honorable conduct."
2."Thou shalt never willingly commit a dishonorable act."
3."Thou shalt punish those who harm or threaten innocents."
4."Thou shalt respect and obey legitimate authority."
5."Thou shalt help those in need."
6."Thou shalt never lie."
```

### CODE REVIEW

**Comment by chatsonf** [comment]
Mind posting the original? 
I am a lazy buffoon and I need to be spoon-fed.

**Comment by Intigracy** [comment]
1. "Never willingly commit an evil act.",
2. "Respect legitimate authority.",
3. "Act with honor.",
4. "Help those in need.",
5. "Punish those who harm or threaten innocents.",

**Comment by Shadowmech88** [comment]
Define "honor."
:^)

**Comment by Intigracy** [comment]
At least it's one word to define instead of evil and honor. Also added obey instead of just respect.

Also the main thing I did besides rewording was putting punishing people above helping those in need, so someone who becomes in need because you're punishing them (by killing the fucker) isn't suddenly being protected by your lawset.

**Comment by chatsonf** [comment]
4 and 5 should be switched, or Legitimate authority can override helping those who need help.

**Comment by Intigracy** [comment]
That's sort of how knighthood used to work though. Serving was above protecting.

With 3 being above 4, if the authority is having you harm/threaten innocents, then it's him who you punish.

**Comment by Ephx1** [comment]
Really, just replace it with the code of chivalry with the bits of church taken out.
Getting analpained over what honor fucking means is retarded, and literally every person will have a different thought on the matter, further constricting our lawset range to NT Default and Asimov because no one wants to deal with an AI that thinks differently than what the uploader thinks.

Thou shalt respect all weaknesses, and shalt constitute thyself the defender of them.
Thou shalt love the country in which thou wast born.
Thou shalt not recoil before thine enemy.
Thou shalt never lie, and shalt remain faithful to thy pledged word.
Thou shalt be generous, and give largesse to everyone.

Literally the only variable word here is "Weakness" and even then it's not like you can do any harm by protecting people you think are weak.

**Comment by Ephx1** [comment]
@BestName
Hey, could you actually explain why it's something bad instead of just using emojis?
That's how a conversation works.

Paladin is retarded as is, because honor has no basis in logic, only what one believes.
This doesn't address the core issue of the lawset.

**Comment by Boxe** [comment]
@Duny

**Comment by Iamgoofball** [comment]
:-1: ruins the D&D joke

**Comment by Intigracy** [comment]
Fuck off goofball you don't even play here

**Comment by Iamgoofball** [comment]
Le "all codebases effect eachother stop pretending we are isolated islands" meme

**Comment by Intigracy** [comment]
Le "fuck off changes to our codebase don't affect you when you LITERALLY DON'T PLAY HERE" meme

**Comment by Probe1** [comment]
the primary issue with PALADIN (ambiguous, undefined language) is still present in either iteration.

**Comment by Ephx1** [comment]
@Probe1 
Exactly, you need EITHER
1. A fuckhuge law 0 that explains what Honor is
2. A character to base honor on, as in, what that person believes honor to be
Otherwise it's just going to be a fuckheap because people always have conflicting ideas in this game.
Yes, lawsets are supposed to have interpretation, but we can't have nice things because our playerbase is so irredeemably shit that we have to enforce rules against certain interpretations because people WILL be shits.

EDIT: I will admit though, this facelift is much better than what it was before, so props to that.

**Comment by gbasood** [comment]
On the other hand we could just make sure people know what we expect of an honorable AI (not killing everyone for fun, not murdering people without evidence of being a ling) like _literally every other AI ruling_

**Comment by clusterfack** [comment]
The syndicate is a legitimate authority

**Comment by Ephx1** [comment]
That's something that I think changes based on what you believe the lore to be.
As I recall, the Syndicate was just a loose band of companies that came together to fuck over NT, and they're not "Officially" together.

**Comment by Brolaire** [comment]
[Needs Final Decision]?

**Comment by clusterfack** [comment]
Just not seein it happen mate

**Comment by Hoshi-chan** [comment]
@clusterfack @Intigracy Why was this closed? There was no violent opposition to it, and revising Paladin is something that's been kicked around for years. This is a pretty darn good update to it, too, and if nothing else, serves as a platform to hash it out until everyone (or most everyone) is satisfied.

Paladin is legitimate garbage right now. Nobody in their right mind uploads it, and even when it is, most borgs won't bother to try to play it up like chivalrous knights when it's uploaded.

This at least makes it loads more usable and interesting than "silicon ban appeal: the lawset"

**Comment by ComicIronic** [comment]
Probably because the changes didn't fix its main issue and merging code just for having something slightly better is ineffectual and deters future changes on the basis of something having been done.

**Pull request closed without merging**
