### PR TITLE
Adds pill collector to the protolathe

### PR DESCRIPTION
**Pull request by Zth--**
If someone stole the only one on box, you were done, there was no way to build another... until this PR!
Also fixes capitalization

### CODE REVIEW

**Comment by Kurfursten** [comment]
They already came in medical crates though. Does this need to be a protolathe item?

The number of things that come exclusively from Cargo is pretty low, I'm not sure I like the idea of shifting one of the last few things that isn't from science to the all-consuming protolathe.

**Comment by Zth--** [comment]
It follows a logic. If medhuds, health analyzers, spectometers, etc, are buildable from the proto/auto, then why shouldn't a pill collector?

**Comment by FudgePucker** [comment]
@Kurfursten 
>Cargo
underpowered

So you are telling me the department that can get yellow gloves, beakers and batteries, and after hacking a single airlock, can get an emitter to open up any crate to give them pretty much ANYTHING.

Here is a list of things that cargo can get ahold of after getting an emitter:
Eguns
Ablative armor
RCDs
RPDs (Don't even need an emitter for the last two, just hack the autolathe)
Bees
Booze
Medical supplys
Autoinjectors (don't even need to get an emitter to make chloral autoinjectors, just electrosise a bottle sleep tox to get 6 chloral)
Combat shotguns
Armor
More emitters
Singularity generators
Super matter shards
Do I really need to go on with the list of things that they can make?

They also get maintanance access, something that science doesn't get.
With a, RPD, gloves and a toolbelt, and maintanance access you can plasma flood by just attaching the incenerators output into distro.

Having a pill despensor in science makes it easy for someone from medbay to quickly walk down the hallway to ask for one instead of having to wait on cargo to hopefuly send you one, and it won't ruin balance (I don't think there is a way to mass murder someone with a pill despensor).

I don't want to tell someone trying to fix medbays wild ride that there really isn't a pill collector avaliable from the protolathe.

**Comment by Kurfursten** [comment]
@FudgePucker You replied to the wrong post, @Zth-- was the one who used the word underpowered. You might be in the wrong Issue entirely, we're talking about pill collectors not plasma flooding.

@Zth-- Because the pill collector isn't a piece of machinery, it's a bag-type item. If anything, add it to the biogenerator along with the other bags. You can apply your same logic to any other item in the game: "If you can make power cells, tools, and airlock control boards from science, why not yellow gloves?" - it's the opposite of what I'm saying. The protolathe doesn't need more items, so saying "the protolathe already has a lot" is not compelling to me for adding more things to the protolathe.

**Comment by Probe1** [comment]
:-1: 

cargo already covers it.  the protolathe needs to be high tech shit.  the pill collector is a scoop.

**Comment by Zth--** [comment]
Closing then

**Pull request closed without merging**
