### PR TITLE
Unreference source object, may help gc.

### PR DESCRIPTION
**Pull request by eswordthecat**

### CODE REVIEW

**Comment by PJB3005** [comment]
Won't do anything, there's no sleeping or spawning in there.

**Comment by eswordthecat** [comment]
playsound is a long proc that's holding the source object for nothing.

**Comment by PJB3005** [comment]
It being long or not doesn't matter, until it's done, the entire server will be locked up and doing nothing other than `playsound`, this is just how single threaded applications work.

**Comment by eswordthecat** [comment]
Some playsound calls is under spawn sometimes, it's not safe to assume that all is just working under a single thread.

**Comment by clusterfack** [comment]
esword is right here, assuming playing a sound halts the proc's end until the sound is completed it would hold an object reference until the procs ends and value_clear() occurs under the hood

**Comment by PJB3005** [comment]
@eswordthecat that's not how `spawn()` works, at all.

`spawn()` doesn't use actual threads; BYOND is single threaded, you can run it in multi thread mode but that's incredibly unstable, and that's for networking and stuff, not for the actual game code.

Consider the following code block:

``` DM
spawn()
    bar()
foo()
```

This will execute `foo()`, then execute `bar()`

`spawn()` just queues up it's code block to be executed the next time the server is doing nothing (all running procs are sleeping, have a spawned code block (where the delay hasn't been reached yet), or there's no other procs running.

**Comment by PJB3005** [comment]
@clusterfack does it actually halt it though, that's contrary to procs such as `animate()` or `flick()`, neither of which halt it.

**Comment by eswordthecat** [comment]
I don't know why it's so controversial just do an = null in this proc.

**Comment by PJB3005** [comment]
Because it's useless (and technically it's an extra instruction so muh compile time)

**Comment by eswordthecat** [comment]
Oh well, time to stop contributing again. Now because of you.

**Comment by PJB3005** [comment]
*sigh

**Pull request closed without merging**
