### PR TITLE
Tweaks unarmed combat formula

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
- Damage and knockdown chance will now get multiplied based on strength, the maximum strength is 4 from a pretty rare combination of hulking out, having the "strong" genetic mutation and having sporty chemicals in your bloodstream. Previously only the hulk gene applied and gave a flat +5 damage punching bonus and +12% chance to knock someone down, now strength multiplies a variable called "punch_damage_per_strength" (3 by default) and increases knockout chance by +4% per strength point (up to +16%)
- RNG damage value from fist combat removed, by default players will deal a default of 5 damage with punches instead of a random value between 0 and 5. Species that dealt increased baseline damage with the punches had their values tweaked to compensate for the lack of additional damage from RNG.
- Missing a punch is now a solid 1/6 chance, and the way it previously worked was that if the damage was 0 it would miss outright, meaning that modifiers such as claws or hulking out would make punches never miss. To compensate for strength having a more effective role in punching, the miss chance is always a solid 1/6 chance, to reflect on the baseline RNG having been a value from 0 to 5 (6 numbers).

This should help standardize unarmed combat (woefully underused) and also contribute ways of improving unarmed effectiveness in-game beside gloves.
If you actually manage to go through the whole effort of having 4 strength and powerful enough gloves to become a murder machine in unarmed combat then you deserve it and I hope someone records your antics for entertainment.
:cl:
 * tweak: Sources of strength such as genetics now contribute to your unarmed power.
 * tweak: Removed RNG values from punches, humans for example will no longer deal any amount of damage from 0 to 5 with punches, but instead a flat 5 damage. Some unarmed damage values have been tweaked to compensate for the ability to gain extra strength.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
Leg days were skipped.

**Comment by BomberBro** [comment]
>RNG value from fist combat removed, by default players will deal a default of 5 damage with punches instead of a random value between 0 and 5.

glad we've finally standardized it for the e-sport scene

**Comment by gurfan** [comment]
i dont get the removal of the rng damage either

**Comment by boy2mantwicethefam** [comment]
You can already miss unarmed melee attacks, this made punching pretty useless if you didn't have any crutches as the average damage would float at around 2.5

**Comment by PrimeDSS13** [comment]
I'm a fan of the RNG tbh

**Comment by boy2mantwicethefam** [comment]
Not really sure how to implement the RNG if that's the case, the idea that started the change in the first place was that strength should affect damage and knockout chance, then it evolved. If I were to add the RNG back it would either lead to an extremely wild range of damage from strength or it could be making unarmed punches too strong if it were added on top of the strength bonus.

**Comment by Blithering** [comment]
So for an example, what would the consistent unarmed damage of a diona chugging the easily obtained sport drink be?

**Comment by drawsstuff** [comment]
How is this going to effect kicks and bites? Bites were used because unlike punches, bites would never miss, and kicks would do on average, more damage, but had a longer cooldown. Catbeasts are also notable for having claws, which allowed for clawing people's eyes out, and even decapitation in extremes. Usually a smart catbeast carries a toolbox instead of relying on their claws to fuck things up, but it's still notable.

**Comment by boy2mantwicethefam** [comment]
@Blithering 20. I probably should tweak this but I'll wait for possible suggestions before committing to it
@drawsstuff Biting and kicking are not affected by this PR. Catbeasts already had their punching damage in the code set lower specifically because of their claws before the PR (they have 2 punching damage because their claws give +3)

**Comment by Blithering** [comment]
I'd personally say 20 is ridiculous for unarmed damage with something as common as some brawndo in you. that's a syndie toolbox right there.

**Comment by boy2mantwicethefam** [comment]
Agreed. I should tone it down but I'm not sure how.

**Comment by Eneocho** [comment]
> 
> 
> Agreed. I should tone it down but I'm not sure how.

Make it a flat +5 per each sports increasing chem (Quantum, Sugar, Sports Drink and Craving Inducing Incense) so you need to be dosed by all 4 to reach the +20.

**Comment by boy2mantwicethefam** [comment]
Sportiness only gives +1 strength though, out of a maximum of +4 strength from all sources of strength

**Comment by Blithering** [comment]
I think part of it was that the old punches averaged out at 2.5 damage, now you're at double that for the baseline and adding buffs on top. Punches from any species shouldn't be doing more than 10 outside of hulk I feel, unarmed should be the last resort unless you put the work in.

**Comment by Kurfursten** [comment]
Let's give this a full week of consideration

**Comment by boy2mantwicethefam** [comment]
I'd like to tweak the numbers while still staying original to the PR's original intent of strength affecting punches.
What I can try doing is give every species a punch value and a "strength boost" variable that will be multiplied by the strength value and added to the total damage number, for example if someone has 2 strength, 5 punch damage by default and a value of 3 in their strength boost variable then the total punch damage would be 11. Does that sound good?

**Comment by Kurfursten** [comment]
If you do that I recommend a new PR for fresh votes

**Comment by boy2mantwicethefam** [comment]
I just hope people will visit the PR once in a while to discuss how to improve the PR

**Comment by GreatBigFailure** [comment]
I think you just need to lower/vary the numbers a bit. Over all it's a good idea, especially the unarmed knockdown stuff.  
Unarmed combat suffers from the same issue as things like explosions: small numbers reducing flexibility. Like if we added an extra 0 to everything it would be easier to tweak but oh well. 
I haven't had time to look at the code but I assume you can keep the RNG to some degree then add your multipliers on top of it. Rather than having a species punch damage add directly to the damage, you could add it to the upper limit of the RNG, which would allow you to keep the multipliers where they are. For example, if a diona has 5 base damage + 5 species damage, that's 10 or, as has been pointed out, an easy 20 with some knowledge of ghetto chems and 30 seconds of effort. More than a toolbox. They will always hit for 20. If instead the diona had 1-5 base + 5 species max now they can hit for 1-10 or 2-20 with a point of strength. Removing the 0 because you're right it was silly. The numbers are very different but I think that could be a fun strength of unarmed combat. For the most part unarmed is used in rage cages or non-antagonist aggressive RP stuff like punching someone who stole something since you know it won't actually risk hurting them too much. Giving the low chance to knock out a tooth or actually require a bandage would be a fun bit of flavor to those interactions. 
These numbers will also probably need tweaking in the future, as every new thing that makes another point of strength possible will greatly effect unarmed combat. 

Finally, please god test Grue. Even with our current system Grue can hit ridiculously hard. They have default claws, hulk and boosted punch damage. With all this I think a Grue could crit in 2 punches, give or take, with a sip of sport drink.

**Comment by boy2mantwicethefam** [comment]
I want to get rid of the RNG, that's one aspect of the tweak. I'm going to nerf the impact of strength on damage by making it a species-based variable whose number is 3 and will halve the effect on knockdown chance (from +8% per strength to +4%)
I thought grue was a bus species so I didn't give it much regard, I'll see what I can do about grues

**Comment by Dacendeth** [comment]
>RNG value from fist combat removed, by default players will deal a default of 5 damage with punches instead of a random value between 0 and 5.

Doesnt this make the fist spell incredibly more busted

**Comment by Kurfursten** [comment]
Not enough support in current form, bring it back with a fresh PR when you tweak it

**Pull request closed without merging**
