### PR TITLE
Fueltanks don't explode when empty

### LINKED ISSUE #24166: Weldertank Explosion Snowflakery Is Bad
Related to #23661 

Instead of welding tanks exploding when you hit them with a lit welder, it should be that one of these two things is true:
* Anything you hit with a lit welder containing a "lot" of fuel should explode
OR
* Chem heating. Fuel explodes with sev based on quantity when it reaches a certain temperature. Hitting things with welders already warms them up.

Right now if you welder an empty tank (or remote signaller it for that matter) it will still explode. Dumb.

### LINKED ISSUE #33806: Empty Welding Fuel Tank still explodes from laser
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
824b0579ddf3a544103e08eeaad902197caf38df

# Description
There was an incident where a player drank all the fuel from a fuel tank and another played decided to shoot it to spook him. Fuel tank still exploded. It is in my opinion and theirs that the empty fuel tank should not have exploded.
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by adacovsk**
## What this does
- fixes bug

## Why it's good
- closes #33806
- closes #24166

## Changelog

:cl:
 * bugfix: Fueltanks don't explode when empty

### CODE REVIEW

**Comment by nervere** [comment]
Soulless.

**Comment by Kromkar** [comment]
Did you test this?

**Comment by Theophrastus1** [comment]
i think it works as intended, when the tank is full, it makes it a much larger explosion. The tank that went off in question for #33806 was empty entirely, but only caused a 1 tile breach, which was immediately repaired once people could stand. Sealed canisters work like this in real life as well, where even if a canister is empty, latent fumes can combust and cause an explosion due to the pressure they're contained with. If anything, make it so that using a drill on them "vents" the fumes and makes it inert.

**Comment by ManopolisJones** [comment]
Come on guys, if we're gonna go the muh fumes route, then how about we actually reflect that in fuel tanks proper by calculating the liquid to fumes ratio in tanks? I mean hell, I thought it was a good idea when somebody posted about it in the thread, trying to weld a full tank just causes it to spill liquid out of the tank causing fire, something closes to half might cause a proper explosion. And how about until we get something like that going for the fuel tanks, we fix this obvious oversight, soul or no soul be dammed.

**Comment by Kromkar** [comment]
> Come on guys, if we're gonna go the muh fumes route, then how about we actually reflect that in fuel tanks proper by calculating the liquid to fumes ratio in tanks? I mean hell, I thought it was a good idea when somebody posted about it in the thread, trying to weld a full tank just causes it to spill liquid out of the tank causing fire, something closes to half might cause a proper explosion. And how about until we get something like that going for the fuel tanks, we fix this obvious oversight, soul or no soul be dammed.

Okay code it and leave it as is currently until then

**Pull request closed without merging**
