### PR TITLE
Splits changelog testing into a separate task for Travis.

### PR DESCRIPTION
**Pull request by gbasood**
Could be sped up a bit more by removing the BYOND building/installing but I'll leave that for someone else

This should make all those concurrent builds do less redundant things meaning all those separate builds will finish faster now

### CODE REVIEW

**Comment by gbasood** [comment]
Well I don't understand ~~batch~~ bash scripting at all so this is in limbo

**Comment by PJB3005** [comment]
> batch 

HERESY THIS IS BASH

**Comment by gbasood** [comment]
okay but still I have no idea how to fix it

**Comment by clusterfack** [comment]
Conflicts and it fails rip

**Pull request closed without merging**
