### PR TITLE
Deff hotfix

### PR DESCRIPTION
**Pull request by Duny-**
Fixes https://github.com/d3athrow/vgstation13/issues/6030
- Removed the leftover walls under mechbay and science entrance doors.

Also:
- Hydrophonics and the kitchen are now only separated by two windoors, no table. This allows the chef and botanists to cooperate easily if they so wish by leaving the windoors open, or to access each room easily in case of no botanists/no chefs by simply asking silicons to open the windoor you don't have access to. Still allows for the same functionality as the table too.
- Heavily modified the list of weapons available at round end.
- Nerfed the entrance of the gooncode facility. Buffed the second room (more of a fix really). Remade the last room, hopefully the emitters cause no problems now. Modified rewards a bit (on top of the gooncode that is), only one is rng-reliant for now.

### CODE REVIEW

**Comment by PJB3005** [comment]
Wait wasn't that a feature?

**Comment by Duny-** [comment]
Why would I go through the trouble of moving robotics to make an entrance only to block it after that nig

**Comment by Kurfursten** [comment]
Because you subsist entirely on the suffering of humans?

**Comment by Duny-** [comment]
If I did I would go outside and watch the news waaay more

**Comment by Probe1** [comment]
:+1: 

the fuck you wall in maint was funny.  the one in robotics is dumb

**Pull request merged**
