### PR TITLE
nuclear fission explosive now actually explodes

### LINKED ISSUE #13882: Nuclear explosions are shit
#### Description of issue

Nuclear explosions do jack squat. They just lock everyone on every Z-level in place. Not even a small explosion, not even a single death, just placelocking. 

#### Server revision

b31abeda2acbee4f619e5b3506439214eb7a7d32

### PR DESCRIPTION
**Pull request by SonixApache**
explosion size may need fine-tuning but seems aight in my tests
closes #13882 ***

:cl:
 - experiment: The nuclear fission explosive now causes a (big) explosion

### CODE REVIEW

**Comment by BobdaBiscuit** [comment]
The fun thing about this is this means toxins autists can legit detonate bombs that are larger than a nuclear explosion with badmins upping the cap to the hardcoded max.

**Comment by ComicIronic** [comment]
I forget how Byond handles turfs for a moment: what happens if the turf the nuke is on get destroyed in the explosion? Is the reference still valid?

**Comment by Aurx** [comment]
You'd expect he'd have tested this and confirmed that it would function.

**Comment by PJB3005** [comment]
@ComicIronic yes, references to turfs always persist unless you change the max(x|y|z) variables.

**Comment by ComicIronic** [comment]
@Aurx you what now

**Comment by BobdaBiscuit** [comment]
Also a reminder that a 22 dev explosion mid station takes 18~ seconds to process, no idea how long the round end screen is but it might take 30-40 seconds to eventually do turf damage.

**Comment by PJB3005** [comment]
Is that recent data because explosions shouldn't be able to lock the server up anymore with check tick.

**Comment by SonixApache** [comment]
image

**Comment by Exxion** [comment]
If a 22 dev takes 18 seconds, a 50 dev would be more like 80 seconds. Square of the scale factor, etc.
But I don't think a 22 dev takes that long anymore.

**Comment by SonixApache** [comment]
if anyone wants to drop a (30, 50, 200) bomb on the main serb to test it be my guest

**Comment by Blithering** [comment]
What size is the AI self destruct explosion?

**Comment by Aurx** [comment]
You mean in malf?  
Ain't none.

**Comment by SonixApache** [comment]
~~~I could add a similar explosion centered on the AI core for malf~~~
I'm too retarded to add an explosion to the AI code for malf, but malf's explosion kills everyone anyway

**Comment by Probe1** [comment]
did anyone test this for round end triggers and such

**Comment by Ephx1** [comment]
Why would it be centered on the AI? I'm pretty sure Malf uses the on-station nuke as well.

**Comment by SonixApache** [comment]
please don't place me in eternal 'needs more testing' hell

**Comment by SonixApache** [comment]
forever

**Comment by SonixApache** [comment]
i'm so happy i could cry

**Pull request merged**
