### PR TITLE
remove sec door access from paramedic

### PR DESCRIPTION
**Pull request by toomykins**
:cl:
 * tweak: no more sec door access for parameds

### CODE REVIEW

**Comment by mentgah** [comment]
total brig medic destruction

**Comment by bathosbathtime** [comment]
I do not support this pull request.

**Comment by falcon2346** [comment]
This just means that brigbay never gets set up again. It's not like they have access to the security offices, lockers, or cells as is, they can literally only walk around the main brig hall and brigbay.

**Comment by Kromkar** [comment]
Bad pr

**Comment by SonixApache** [comment]
ok, but why?

**Comment by toomykins** [comment]
> ok, but why?

unimplanted personnel in brig

**Comment by bathosbathtime** [comment]
Wouldn't this remove brig access from brig medic as well?

**Comment by toomykins** [comment]
> Wouldn't this remove brig access from brig medic as well?

yes

**Comment by CrazyAmphibian** [comment]
> unimplanted personnel in brig

Capture

**Comment by MercuriusGH** [comment]
> > ok, but why?
> 
> unimplanted personnel in brig

but brig medics have implants
low IQ PR

**Comment by SonixApache** [comment]
you had me at unimplanted
but they're not unimplanted
so you no longer have me

so... why?

**Comment by toomykins** [comment]
oh wow parameds are implanted
sorry guys next PR will be about rmeoving paremedicsal

**Pull request closed without merging**
