### PR TITLE
Security borgs are now redubbed as Peacekeeper borgs

### PR DESCRIPTION
**Pull request by Intigracy**
http://ss13.pomf.se/index.php/poll/27

As requested by Pomf.

```
Jul 02 06:50:04 <D3athrow>  http://ss13.pomf.se/index.php/poll/27
Jul 02 06:50:09 <D3athrow>  get to it Intigracy
Jul 02 06:50:35 <Intigracy> So just rename the module?

Jul 02 06:57:48 <D3athrow>  Intigracy rename and make the secborg baby blue
Jul 02 06:57:55 <Intigracy> cool
```

Servbots (standard and service) now are actually different icons from each other, and both changed.

| Old | New |
| --- | --- |
| bloodhound |  |
|  |  |
| marinaSC |  |
|  |  |
| sleeksecurity |  |
|  |  |
| servbot-sec |  |
|  |  |
| securityrobot |  |
|  |  |

| Servbots: |  |
| --- | --- |
| servbot | new |
|  |  |
| servbot-service | new |
|  |  |

### CODE REVIEW

**Comment by Probe1** [comment]
the status quo isn't working very well and a change is welcome.

**Comment by Ephx1** [comment]
This sounds great. People were speaking of a Guardian borg, but this seems cooler.

**Comment by Intigracy** [comment]
Working on making the sprites less ass colored, will be done in a bit.

**Comment by NigglyWiggly** [comment]
When are we gonna have 'pacification borgs'?
I want sec borgs that are pink and have no tools that could be used to hurt anyone, and they have hailers that say things like "Please calm down" and "Don't be upset"

**Comment by IratePirate** [comment]
Looks like Pomf finally cracked. The thread whiners and minority of tards should not dictate revisions to the game code like this. Also that blue doesn't look too great. Will there be a massive overhaul weaponry a la Goon and TG or will this just be a half arsed attempt to pander?

**Comment by AutismSpider** [comment]
Goon removed Sec borg due to rampant abuse, killing and law breaking.

TG code has made them useless over all.

Blue looks like ass.

**Comment by Unfit** [comment]
Mining module renamed to 'mineral excavation module' when :^)

**Comment by ComicIronic** [comment]
This is a good change, since it removes the ambiguity of what the secborg is actually meant to be.

There are too many occasions of secborgs acting as security or cooperating entirely with security, which goes beyond the purview of their laws.

As for
>the community shouldn't dictate the changes to the server
Then what should?

**Comment by dylanstrategie** [comment]
I honestly don't see how this could be controversial, there has been a pretty clear server vote with a large margin

More like a discussion maybe

**Comment by ComicIronic** [comment]
It's controversial because people are posting angry conflicting opinions on it. I thought that would be obvious.

**Comment by SkowronX** [comment]
Try a navy blue.

**Comment by clusterfack** [comment]
Can you do a comparison of the servbot medical vs security?

**Comment by d3athrow** [comment]
powda blue

**Comment by Intigracy** [comment]
||||
|medical|security|standard|

**Comment by Nienhaus** [comment]
These look pretty cool blue.

**Comment by Probe1** [comment]
maybe change the standard color scheme for lego bots away from blue.  your shade of blue seems to work well for peacekeeper borgs.

**Comment by Ephx1** [comment]
Oh, one thing about the "Black Guardian" sprite. The red tube on its back should remain red, or at least it would be consistent. Because I believe it's taken directly from the Standard "Standard" module sprite.

**Comment by Intigracy** [comment]
Thanks for pointing that out, yeah it does take it from robot_old.

**Comment by NigglyWiggly** [comment]
>maybe change the standard color scheme for lego bots away from blue. your shade of blue seems to work well for peacekeeper borgs.

Probe I'm gonna break your face

**Comment by Probe1** [comment]
my sides are shaking i forgot to not call them that

**Comment by NigglyWiggly** [comment]
It's not the fact that you called them legos, nerdo, it's the fact that you'd suggest making them not blue

**Comment by Probe1** [comment]
oh.  well I guess they're different enough as is.

**Comment by bustygoku** [comment]
What's the point of this if the modules used by the borgs haven't changed at all?

**Comment by ComicIronic** [comment]
Because people are confused by the module being called Security, and think that it means that they should be playing Security.

**Comment by bustygoku** [comment]
So now thankfully there's no confusion! Peacekeeper borgs that don't have to help security, and instead be the AI's personal antag hunters.

Much better. Bravo.

**Comment by Probe1** [comment]
change antag to harm and you're correct.  they're the AIs personal harm hunters that stop harm.  

they were always this.  and there have always been players that didn't accept it and instead played security with all access and stun resistance.  

doing nothing changes nothing.  banning people hasn't worked.  better to try something new.

**Comment by AutismSpider** [comment]
only two things to do!

full rework or did what goon did and removed it.

This does nothing just paint job and a new name people will keep playing them as security borgs

**Comment by VelardAmakar** [comment]
it eliminates any kind of "it says security i am security stop persecuting me" shittery
it makes it clear what role peaceborgs have
maybe in the future security can order security borg modules that preinstall a sec module and robocop, complete with classic red paintjob

**Comment by Probe1** [comment]
I think the second thing Velard said will have the most impact.  It clarifies what they are.  Security and spacelaw are synonymous to some players.  There can be no confusion about it when you aren't called security.

**Comment by bustygoku** [comment]
Why not just remove these borgs.

AI's anti-harm laws should not be so easily enforced. Harm will occur. This is ss13. I'm completely sick of "SEC IS NOW BASICALLY HITLER FOR HITTING SOMEONE NOT ON MY WATCH BORGS DEPLOY!!!"

**Comment by ComicIronic** [comment]
>Why not just remove these borgs.

Because then the AI would not have a clear way to stop harm.
I don't see the reason to remove them. The main issue is people playing them as Security and not Asimov.

**Comment by bustygoku** [comment]
"Because then the AI would not have a clear way to stop harm."

Who cares?

AIs are law bound to never CAUSE HARM, *not* STOP ALL HARM like the fun police. They're slaves. They serve the crew. They don't go out of their way to protect the crew (fun police antag hunters to make their existence less boring when they don't get antag).

**Comment by ComicIronic** [comment]
>AIs are law bound to never CAUSE HARM, not STOP ALL HARM like the fun police.

"or, by inaction, allow a human being to come to harm"

**Comment by bustygoku** [comment]
Pay attention kiddo.

If they didn't have a way to stop harm, they wouldn't be breaking the law by not stopping harm. It wouldn't be inaction. That's what that law means. So if we removed secborgs, they AI would point out where harm is occurring, bolt doors, etc. There would be no need for secborgs.

**Comment by VelardAmakar** [comment]
@bustygoku 

1. very correct, i honestly wouldn't mind seeing these borgs go away altogether but i feel we should give peacekeeper a try first i'm all for it as of now
2. i'm lowkey jealous i didn't think of that name first cause i would be rocking that right now if i did

**Comment by IratePirate** [comment]
If the AI had many more abilities at its finger tips to impede other players and stop harm then getting rid of Sec borgs would make sense. Currently, getting rid of them would be absolutely ludicrous and would make silicons overall have much less of an impact on rounds and relegate them to an underplayed second class role like Security.

**Comment by bustygoku** [comment]
Good? They aren't supposed to be as important as the rest of the crew, like command roles, they're robotic slave helpers and this was always the case before people started stuffing MUH SILICON into everything and making them a big part of rounds because it's the only role they played. Frankly it's very anti-ss13

**Comment by ComicIronic** [comment]
Making sweeping generalisations does not make your opinion a fact.

**Comment by Arthurdentist** [comment]
not a fan of the baby blue sprites but that is my only real objection.

**Comment by bustygoku** [comment]
Comic "silicon buttbaby" Ironic:

I've played quite a bit of silicons for a long time, and have witnessed firsthand the slow casualization of silicons and the attempt to turn them into a big part of rounds when they are objectively and literally robot slaves you're supposed to stick convict brains into. This always used to be the case, and what the original coders intended. They weren't intended as a snowflake role for you to live out your gay robot fetishes in, that's what MOMMIs are for. This is complete fact and not my opinion.

Yes, it is my opinion that giving AIs less ways to stop harm would GREATLY improve rounds and silicon player attitudes by moving them away from HARM POLICE assholes that just ruin all the fun for traitors and sec who finally caught that piece of shit wizard and want to smack him around a bit. This is fun, not looking over your shoulder and feeling uneasy when a sec borg is around because GOD FORBID you have fun or brawl when the AI's watchdogs are around.

It's time someone finally said this. Sec borgs are awful gameplay and only played by the worst of people almost all the time.

**Comment by IratePirate** [comment]
>They weren't intended as a snowflake role for you to live out your gay robot fetishes in, that's what MOMMIs are for.

You mean the role that revolves around not communicating with anybody?

>that just ruin all the fun for traitors and sec who finally caught that piece of shit wizard and want to smack him around a bit.

Confirmed for someone who got shitter shattered as an antag because they didn't pick up a flash, buy EMP grenades, subvert or blow them up at the console. The whole point of the silicons is that they are supposed to come into conflict with the crew over harm, they're not supposed to be boring as fuck and just sit by as people violate their laws while they're fixing a wall or serving drinks.

>Sec borgs are awful gameplay and only played by the worst of people almost all the time.

That's obviously greyshirts. Sec borgs actually contribute to the round, especially on a server where actual Security is virtually non-existent at most times leading to steamrolls by overpowered antags.

**Comment by Unfit** [comment]
Standard borgs can apprehend criminals almost as well as secborgs, with the added bonus of being able to provide basic medical care.
They don't have handcuffs or tazers, but I'd say having a wide range of other tools far outweighs that

What if secborgs were removed for a few weeks as an experiment? Then we could have a vote and decide whether quality of rounds increased or decreased

**Comment by bustygoku** [comment]
>Security doesn't exist
>People prefer playing sec borg
>Clearly this isn't a problem with security

Fix security, it's an actual job, and we should prefer to have actual jobs staffed by actual people instead of borgs.

>le u must have been arrested by a secborg to hate them so much!!!

No, actually, the only times I've been stunned by a secborg that comes to mind is when playing nonantag or security by the overzealous harm police.

Confirmed asspained baddie that can't play security without being an unstunnable borg :')

**Comment by VelardAmakar** [comment]
>Fix security, it's an actual job, and we should prefer to have actual jobs staffed by actual people instead of borgs.

honestly this

**Comment by Intigracy** [comment]
Security is a problem, yeah.

I'd much rather be an unstunnable (mostly) killing machine who can only be fought back against in specific circumstances than a regular old stunnable human being.

I'm assuming this is the prevailing logic.

**Comment by Kurfursten** [comment]
:+1:

**Comment by Duny-** [comment]
bluethumbsup
I actually did that once but never made a PR.
Seeing the amount of assmad in the comments make me regret not doing it.

**Comment by SkowronX** [comment]
:+1: Do it

**Comment by bustygoku** [comment]
:+1: gut the secborgs

**Comment by SkowronX** [comment]
when

**Comment by Shaska-** [comment]
>Baby blue

A darker blue would have looked much better
ss13 bluedog

**Comment by Probe1** [comment]
:+1: mergemergemergemergemergebanmergemergemergemergemerge

**Comment by d3athrow** [comment]
elconflicto por favor
if you dont like the color post examples of desired palette swaps

**Comment by Probe1** [comment]
Please don't close.  This really needs merged.

**Comment by NigglyWiggly** [comment]
he closed it because he's afraid of how hard i'm gonna beat him up if he messes with my servbots

**Comment by Probe1** [comment]
please dont hit me either

**Comment by MusgardTiger** [comment]
This is borg politician Mustard Tiger and I strongly believe this PR should be in our code RIGHT NOW, people. Security borgs are misleading by their name, overpowered and they basically kill the security role. They can do everything better than their human counterparts. It is strange that I refer them as counterparts isn't it considering they start on ASIMOV lawset? That's what they are, that's how they are played. You can crack down on few shitter security borgs but you just can't keep up with valid securing that is taking place almost every round.

Security borgs kill the subtlety in traitors work, because the moment somebody utters your name you'll get busted faster than a crippled bank robber. It is painful to set up anything sinister or engage in covert activities when there are snarling metal hounds out for your butt.

An engiborg can't replace a human engineer by function same goes with literally every other borg type maybe except for janiborg. However security borgs can outdo their human counterparts in every way except for lethal injection, they'd be better at that shit if they had fingers trust me on that.

And this is by no means an issue of gitting gud, you can maybe have the upper hand against a security borg in certain situations with certain items but 90% of the time you'll get tazed faster than a homeless californian man on crack.

I believe if we change the perception about security borgs, they'll stop being fun murderers and we'll have fun rounds where antags can actually dare to do something other than murderboning via plasmafire, bombs, guns and adding one human laws.

Please reconsider adding this in.

**Comment by 9600bauds** [comment]
This had a ton of :+1:s already, so here's mine. :+1:

**Pull request closed without merging**
