### PR TITLE
Adds destination taggers and buckshot to autolathe

### PR DESCRIPTION
**Pull request by jakmak3**
This change adds the destination tagger which cannot be created through any other means to the autolathe. This also adds the buckshot shotgun shells which were only present in the cargo shotgun ammo crate to the autolathe contraband. Also moves the rapid service fabricator up from contraband to misc tools since its not a dangerous item. Also i forgot to put changelogs in the previous PRs that i made that were merged so i will wrap them in this

:cl:
* tweak: The cargo destination tagger can be made by the autolathe
* tweak: Adds buckshot shotgun shells to autolathe contraband

### CODE REVIEW

**Comment by Kurfursten** [comment]
Needs changelog
Your OP changelog is wrong

Otherwise I think the changes are good

**Comment by jakmak3** [comment]
christ whats the exact syntax for the changelog to work?

**Comment by Intigracy** [comment]
add a space after the *
I fixed it for you so you can see how to do it in the future

**Comment by clusterfack** [comment]
Please stop updating your branch this way

**Comment by jakmak3** [comment]
i dont know how git works at all im lucky to be able to push changes to the main branch

**Comment by clusterfack** [comment]
Then ask us in discord

**Comment by icantthinkofanameritenow** [comment]
Why did the sleepers even have phalanxamine anyway?

**Comment by jakmak3** [comment]
icant i think it was a left over from when cancer was a actual thing. And since we dont have infections (worse than cancer desu) spacecillin is pretty useless since all it does is slow virus symptom progression

**Comment by SonixApache** [comment]
10+u spaceacillin is a lifesaver if you don't want to get bonezo'd by virusses while a cure is (not) being made.

**Pull request merged**
