### PR TITLE
Fixes tournament lances

### PR DESCRIPTION
**Pull request by unid15**
It's not like anybody will notice because nobody uses them anyways x--p

### CODE REVIEW

**Comment by ComicIronic** [comment]
I'd suggest you make a comment as to why this is the case, because whoever coded it seems to have confused even themselves.

**Comment by PJB3005** [comment]
Welp that's probably my fault isn't it?

**Comment by unid15** [comment]
Added a comment

**Comment by 9600bauds** [comment]
I did notice but I thought I was just doing it wrong

**Pull request merged**
