### PR TITLE
Mecha Graveyard and Mech Wreckage Update

### PR DESCRIPTION
**Pull request by jwhitak**
# I see you through that screen

image

## What this does
This PR updates the Mecha Graveyard with some more interesting loot, and additionally buffs mech wreckage.

### Mech Wrecks
image
Before:
* Only certain mechs can have construction pieces (items you must obtain via the exofab like torsos/arms/chassises) looted.
* Of these, they only contain their torsos and limb parts, except for the HONKER which could contain its chassis.
* When generated, it rolls a 40% twice. Success includes a part. You can have up to 2 parts per mech (most mechs require 8 or more specific parts).

After:
* Same mech restrictions. Can't rebuild a syndie mech for example.
* Of the ones that can, they can contain any major construction piece, including chassis and circuit boards.
* Same odds. It's incredibly unlikely you'll get enough parts to make a whole mech, unfortunately, even after this update. Unless...

### MECHA GRAVEYARD
image
Before:
* 7 set wrecks, 3 of which being "graveyard" wrecks (2x ripley, 1x clarke) with nearly everything to create the mech (except no chassis or circuitboards leaving it impossible)...
* "Graveyard" wrecks always had 3 equipment pieces
* A repair module always spawns
* 46 standard roid turfs that can spawn any standard roid ore

After:
* 14 wrecks placed randomly
* 1 improved "graveyard" mech (ripley OR clarke) which will always contain all the pieces necessary to rebuild it (though you may need to find your own welder and loot up a bit of materials like metal/plasteel)
* The improved mech will have a minimum set of equipment, with a chance of an extra bonus piece
* 2x random equipment spawns
* 46 MECHA GRAVEYARD roid turfs that can contain the rare Nanotrasite and Electrum ores, smeltable into Iron/Plasma and Gold/Silver respectively. Or host them as exotic trading goods...
* The thing that made the mecha graveyard. (Currently just a fancy roid basilisk that drops bones and a generic mecha wreck with no construction parts...)

## Why it's good
Because it might make a 100 credit destination disk useful to traders, it's not.

## How it was tested
image
*squints*

Spawned the mecha graveyard a few times, fought THE SKULLBOT, took apart a mech or two.

## Changelog

:cl:
 * rscadd: Updated the Mecha Graveyard, available via trader destination disk.

### CODE REVIEW

**Comment by jwhitak** [comment]
I'm open to buffing the odds of wrecks having usable construction parts. With current odds, it's practically impossible. Even if you have all 14 wrecks roll the same wreck, you still probably can't rebuild a full mech, since the construction parts roll so low and randomly (up to 2 per wreck but 40% shot each). You basically get just a ripley/clarke from this vault, plus some equipment that may or may not work with it. Good deal to try and sell though.

**Comment by Blithering** [comment]
Maybe have a graveyard specific tool as loot that ups the odds of part salvaging? Also there's the gundam mechs sprited if you want those

**Comment by MercuriusGH** [comment]
what's the deal with the skeleton mecha

**Comment by Blithering** [comment]
> what's the deal with the skeleton mecha

He's got a bone to pick with you.

**Comment by jwhitak** [comment]
It's a graveyard so it has a spooky spooky skeleton in it. His gaze is chilling to the bone! (He runs the place)

**Comment by angryturnip** [comment]
> what's the deal with the skeleton mecha

[It's a graveyard!](https://files.catbox.moe/8mtq66.mp3)

**Review by west3436 — APPROVED** [review]
Code looks good but I still think this disk isn't worth it. You now have to fight a boss to only get loot which can be printed after 10min of mining (and Shaft Miner is one of the most popular jobs, so this happens often). I'd throw some Mauler/Marauder/Seraph parts into the loot table (maybe even one guaranteed) to give a better incentive to purchase this. Players only see a Mauler every 100th round and the other two mechs are pretty much never seen, so having a way to obtain their parts would make this much more appealing.

**Comment by jwhitak** [comment]
This is already a direct buff to the graveyard. Current code, you cannot get a mech in any circumstance. Or anything of value, really. Now, you will get either a ripley or a clarke with some equipment options, with a free charging station for it to boot. I'd say let's try the basic buff first before going all out and letting traders have access to combat mechs.

~~Also, if a slightly faster slightly stronger (same health) basilisk is a boss, then I don't want to know what the actual bosses are...~~ Ok fine, he is technically a boss. Being technically correct is the best form of correct.

**Comment by Kurfursten** [comment]
I don't think that a boss to kill is a downside for most miners. Usually, for an established miner, they're looking for sprites to turn sideways since they already got all their super gear by the time they go to a trader. I guess there is a downside in that maybe scientists won't buy the disk now because they might not carry weapons, but to tell the truth I've never seen one buy the disk. It's a tough sell item.

Overall I think this is good.

**Comment by githubuser4141** [comment]
Isn't the title of 'graveyard' more like a .. junkyard of sorts, where decommissioned or broken mechas are dumped? Having it so the boss robot "created" the graveyard (through combat? by breaking all those mechs?) makes a lot less sense imho for a few reasons:

1. The strength and speed of the boss doesn't match with that many broken mechs, including fast space mechs (that can run away) and combat mechs.
2. The types of mechs that exist don't make sense to be there, unless it's part of a larger structure. Why would there be random assortments of medical and entertainment mechs flying around space? There's also, combat mechs and NT/Syndie mechs, all in the same area?

The way I see it, is a mined-out out asteroid that was used for throwing out old mechs that were broken or disused. There's a little dock/maintenance shed for accessibility with a solar generator/bank. Over time the company that's working here finishes their work and leaves. The junkyard is now abandoned, eventually the dock gets destroyed from space debris and some low-level fauna move in. (Skull mech can be one of em.) That's it.

 Now it's some insane battlefield where like, a big group of phazons, marauders, durands, gygaxes, odysseuses, ripleys, clarkes and HONKs all battled a big skull mech and lost (somehow.) It doesn't make sense. 
 Unless, the skull mech is supposed to be just literally a guard robot that was assigned there by said company. It'd make sense if it's just a regular guard drone that some nerds modified to make it look evil, I guess.

**Comment by Loafin34** [comment]
I like the idea of the fauna somehow activating a disused mech and forcing the junkyard to become derelict

**Comment by jwhitak** [comment]
Mecha Graveyard probably needs a bigger rework than what I've got on offer here. At the very least, this can be a slight bump in quality while we wait for a coder/mapper with the inspiration to take it on...

**Comment by Blithering** [comment]
> The way I see it, is a mined-out out asteroid that was used for throwing out old mechs that were broken or disused. There's a little dock/maintenance shed for accessibility with a solar generator/bank. Over time the company that's working here finishes their work and leaves. The junkyard is now abandoned, eventually the dock gets destroyed from space debris and some low-level fauna move in. (Skull mech can be one of em.) That's it.
> 
> Now it's some insane battlefield where like, a big group of phazons, marauders, durands, gygaxes, odysseuses, ripleys, clarkes and HONKs all battled a big skull mech and lost (somehow.) It doesn't make sense. Unless, the skull mech is supposed to be just literally a guard robot that was assigned there by said company. It'd make sense if it's just a regular guard drone that some nerds modified to make it look evil, I guess.

The guard robot thing makes sense, alternatively it could have been something cobbled together by a junkyard worker out of spare parts, or something that was tossed out while not quite broken and reactivated itself.

**Comment by Killette2** [comment]
The boss often floats off into space aimlessly, it took me a month of seeing him randomly in space to see him randomly stuck in the shuttle docking area's spacegap to make me realize he came from here.

**Pull request merged**
