### PR TITLE
more cult

### PR DESCRIPTION
**Pull request by DamianX**
:cl:
 * rscadd: more cult

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
no

**Comment by aceedex** [comment]
Hello? Based department ?

**Comment by cloutcode** [comment]
yikes, uhhhh cringe much???

**Comment by ghost** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEES

**Comment by SonixApache** [comment]
accelerationism

**Comment by ghost** [comment]
you stupid bitch, you stupid fucking bitch

I can't believe how dumb you are

**Comment by Kurfursten** [comment]
Next PR should be to just rename a bunch of stuff to "Damian"

Like stools, syringes, space ninja mode, title section of the UI on the cargo console and also 2 of the category tabs, wave emote changed to *damian, every reference to MoMMIs replaced with "Damian"

**Comment by ShiftyRail** [comment]
Honestly we should remove emoji voting rights to anyone who posts a meme comment

**Comment by SonixApache** [comment]
@Kurfursten #25916

**Comment by tuypo1** [comment]
> Honestly we should remove emoji voting rights to anyone who posts a meme comment

Dial 8 and ask for the seethe department

**Comment by Kurfursten** [comment]
Wipe this meme from the face of the Earth

**Comment by tuypo1** [comment]
It's not just a meme though, cult is the best gamemode and it should show up more often
Maybe not 3 times as often though

**Pull request closed without merging**
