### PR TITLE
Box, Meta, Taxi fixes

### PR DESCRIPTION
**Pull request by Probe1**
- **General** Adds area called Evidence Storage.
- ~~**Metaclub** Changes Warden APC cell to 10000 charge up from 2500 to prevent power from failing 5 minutes into the round.  The Warden APC powers several rooms unlike on Box so it needs to be brought up a bit or else power fails before engineers can set it up.~~
- **Metaclub** Gives mechanics access to the two engineering doors adjacent to the Foyer, bringing Engineering access in line with Box and allowing a mechanic access in a pinch.
- **Metaclub** Changes area above Warden Office into Evidence Storage.  Changes security locker area into security office.  This will reduce the drain on the Wardens APC and ensure it does not expire before 12:25 (tested in game)
- **Metaclub**  Adds cameras to arrivals and SW medbay so the AI can see the arrival shuttle and the door to viro.  Adjusts camera in courtroom so it can see a dead spot in the corner.
- **Metaclub**  Adds brig access requirement to lockdown button in Warden Office
-  **Taxi** Adds electrified grilles to Engineerings entrance to curb the frequent break ins by assistants that spawn adjacent to Engineering.  Since Engineering doesn't have a foyer and only a door and thin windows separate them from the station, wires were added.
-  **Taxi** Adds conveyor and windows under the disposal chute in taxis recycling area to prevent crates from becoming stuck when multiple come through simultaneously.
- **Box** Adds a conveyor under the disposals outlet to fix an issue when multiple packages come out of the outlet simultaneously, making them get stuck.
- **Box** Swaps APC and Fire Alarm location in Supermatter Room for better AI accessibility so the AI can turn on the APC with the cameras light if all the lights are off.
- **Box** Adds camera to xenobiology maintenance so the AI can see the APC.  Cameras already exist in xenobio maint but there is a deadzone where the APC is.
- **Box** Adds brig access requirement to use lockdown and door buttons in the brig.

Resolves https://github.com/d3athrow/vgstation13/issues/5570
Resolves https://github.com/d3athrow/vgstation13/issues/5645
Resolves https://github.com/d3athrow/vgstation13/issues/5846

Addresses feedback in the thread 
http://boards.4chan.org/vg/thread/117244510#p117250031
http://boards.4chan.org/vg/thread/117244510#p117249797
http://boards.4chan.org/vg/thread/117244510#p117269303

### CODE REVIEW

**Comment by dylanstrategie** [comment]
Manually editing power cells in APC is really terrible. Don't do that. Just split up the rooms like everyone else

We already have an Armory area, check Box

**Comment by Probe1** [comment]
I copied it from the APC directly adjacent to it.  What should I do to fix that apc as well?

**Comment by dylanstrategie** [comment]
Looking at the picture, the Warden's Office includes part of what would be upper Interrogation (the lockers for shit you strip when arresting), the Security Armory and the Security loadout zone

Also yeah, kill off snowflake APCs. Doesn't Metaclub have 3 SMES cells with 20 % power outputting at roundstart ? Like Box ?

**Comment by Probe1** [comment]
Demand is 50kW higher than Box but yes, it has the same engineering setup.

This was my original idea.  

vgstation13_ mapsmetaclub dmm _-_dream_maker_2015-09-26_05-16-42

It looked like shit to have a room defined as security in a few places and warden in other places.  Inconsistent.    But anything else would require the wardens area to be redone.  Changing the cells power was quick and easy.  But I thought it would make a high cap cell spawn in it which was wrong, it just edited the basic 2500 charge power cell to be 10000.  I agree this is shit.

  Do you have any suggestions?

**Comment by Probe1** [comment]
Okay so after investigating, 'most' apcs on all maps have been edited to have 2500 charge.  They're a basic power cell (1000 charge) that has been edited to have 2500.  

Specific to metaclub, the brig hallway APC has been edited to 10000.  The Secure Armory APC cell has been edited to 5000.  Security Office 5000.  Prison Wing (that's Perma) 5000.  Then there's other areas like the HOS Office, Detective Office, Sec Medbay, that have the uniform 2500 cap.  

Furthermore, the "Main APC" in Engineering has a cell with 7500 charge.  The supermatter room 7500.  Atmospherics 10000.  But Atmos Monitoring, Foyer, AME Room, CE Office all have the uniform 2500 capacity.

I have found that the inconsistency is consistent.  APCs themselves have a special 'power cell' that defies the normal capacity convention with 2500 charge instead of 1000.  But everywhere I go on Metaclub, large rooms get larger edited capacities.  

What do we do?  Edit them all, test, and divvy up rooms that are too large?

Is there any way we can use a high-cap cell or super-cap cell in a roundstart APC?  That would be a clean solution.

**Comment by dylanstrategie** [comment]
Usually, it's good practice to divide up large rooms, especially if there are actual, physical divisions to justify it

Also, remember than lighting is usually the biggest station drain. That means large areas tend to drain a lot of power even if they have only basic machinery like alarms and intercoms, so cutting up large areas is important

**Comment by FudgePucker** [comment]
Dividing some of those rooms would be a pain in the ass. Engineering would be a pain because of the PA and splitting it up would add 4 more APCs to deal with, adding more wires to the area already looking like a plate of red spaghetti. How the hell are you going to split up atmospherics? No really, its just one giant room, and the lights cameras and atmos devices out in the gas tanks. Where was this no snowflake varedit policy when the SME chamber got fucked over 10000 times sideways?

**Comment by Probe1** [comment]
They don't exist or else they would be.  I'd have to write some new apcs that start with highs.

**Comment by clusterfack** [comment]
Dividing up engineering is unnecessary as it has its own powernet to draw from with its own reserve power sufficient to cover the area for some time.

**Comment by Probe1** [comment]
Please review.

**Comment by IratePirate** [comment]
You're doing God's work son.

**Comment by PJB3005** [comment]
@Probe1 could you also put conveyors under the disposals outlets used in taxi's belt hell? Those get stuck too.

**Comment by Probe1** [comment]
Can and will.  Needs some windows to make sure it won't pop out but easy enough.

**Comment by Probe1** [comment]
@N3X15 ready for merge when travis is done.

**Comment by dylanstrategie** [comment]
Try checking #5846, this is most likely a simple req_access problem

Also #5869, but then you're going to have to chew through a lot of vents and scrubbers

**Comment by Probe1** [comment]
Added req = "63" (Brig access, All) to brig buttons on Box, added req = "63" to brig lockdown button on meta,

**Comment by Probe1** [comment]
Unless there is a mistake, this is the last commit I want to make for this PR.  There can be a new PR later.

**Comment by dylanstrategie** [comment]
Now to wait for @N3X15

**Pull request merged**
