### PR TITLE
Fixes odysseus sleepers being impossible to escape from

### PR DESCRIPTION
**Pull request by MadmanMartian**
For some strange reason it was constantly applying paralyze and stun and knockdown to whomever was inside, while also fixing the stun (twice) and knockdown for some reason. This has been changed so instead it is just fixing the stun and knockdown.

Now, you can move whilest inside the sleeper, and it will permit you exit from the mech. In addition, should the odysseus run out of power, it will auto-eject all sleeper occupants.

:cl:
 * bugfix: Odysseus sleepers now let the occupant out should the mech run out of power, or the occupant move.

### CODE REVIEW

**Comment by SkowronX** [comment]
rip portable perma

**Comment by spoonylove** [comment]
Giving the actual cell pods for mechs a use

**Comment by ComradeDispenser** [comment]
Now make it so being in space doesn't kill your occupants.

**Comment by FudgePucker** [comment]
Cell pods suck though. Cannot arrest people with it. I struggled to leg cuff some one and get them into the cell in time, they struggled out of it before I could even get down the hallway. Worthless. Odysseys would still be better because a syringe of sleep toxin lasts longer than the time it takes to get out of a cell

**Pull request merged**
