### PR TITLE
Increases maximum queue limit for Protolathe and Circuit Imprinter to 50

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
[tweak]
Now you can build 10 of every component type (5 types) and fill up the RPED this way. No way this can go wrong.
:cl:
 * tweak: The protolathe and circuit imprinter can now fit 50 objects in their queues instead of 30.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
Coould have it scale off of internal parts?

**Comment by boy2mantwicethefam** [comment]
It's a define and the queue thing calls for the define. Would be somewhat more difficult and would take more effort to scale it off internal parts instead of changing the define number to 50

**Comment by RealestEstate** [comment]
based and RPEDpilled

**Comment by spoonylove** [comment]
https://github.com/vgstation-coders/vgstation13/issues/17134

I requested something like this a year ago. Based. Thanks man. Although at that many things queued we should have some way of being able to mass select how many of something we want like protolathe rather than having to click one at a time into queue.

**Comment by spoonylove** [comment]
Wait this isnt for autolathe. Nvm reee

**Pull request merged**
