### PR TITLE
Prevents self-replenishing containers from being scanned by mechanics

### PR DESCRIPTION
**Pull request by jknpj**
03:17:06_ [0x2023d04] (Mechanics - 252,254,1) || sigma-964 spawned with the ability to replenish itself with paroxetine.
03:17:54 [0x2023dbc] (Mechanics - 252,254,1) || epsilon-503 spawned with the ability to replenish itself with drink.
03:17:56 [0x2023dc1] (Mechanics - 252,254,1) || kappa-125 spawned with the ability to replenish itself with nothing.
03:17:58 [0x2023dc3] (Mechanics - 252,254,1) || delta-999 spawned with the ability to replenish itself with moonrocks.
03:18:17 [0x20033f1] (Mechanics - 252,254,1) || kappa-393 spawned with the ability to replenish itself with hippiesdelight.
03:18:29 [0x2023e00] (Mechanics - 252,254,1) || epsilon-781 spawned with the ability to replenish itself with manlydorf.
03:21:35 [0x2023e4b] (Mechanics - 252,254,1) || omicron-938 spawned with the ability to replenish itself with manlydorf.
03:29:08 [0x2024503] (Mechanics - 252,254,1) || kappa-893 spawned with the ability to replenish itself with capsaicin.
03:29:10 [0x2024506] (Mechanics - 252,254,1) || omega-705 spawned with the ability to replenish itself with zombiepowder.
03:29:12 [0x202450d] (Mechanics - 252,254,1) || antaeres-133 spawned with the ability to replenish itself with holywater.
03:29:40 [0x2024515] (Mechanics - 252,254,1) || sigma-415 spawned with the ability to replenish itself with frostoil.
03:29:42 [0x202451a] (Mechanics - 252,254,1) || omega-420 spawned with the ability to replenish itself with blood.
03:29:44 [0x202450f] (Mechanics - 252,254,1) || iota-423 spawned with the ability to replenish itself with manlydorf.
03:30:23 [0x20245b6] (Mechanics - 252,254,1) || kappa-464 spawned with the ability to replenish itself with cleaner.
03:30:25 [0x20245b9] (Mechanics - 252,254,1) || antaeres-921 spawned with the ability to replenish itself with ethanol.
03:30:27 [0x20245c0] (Mechanics - 252,254,1) || alpha-169 spawned with the ability to replenish itself with capsaicin.
03:30:29 [0x20245c1] (Mechanics - 252,254,1) || antaeres-919 spawned with the ability to replenish itself with pwine.
03:34:26 [0x20246d7] (Mechanics - 252,254,1) || antaeres-514 spawned with the ability to replenish itself with pwine.
03:34:28 [0x20246ef] (Mechanics - 252,254,1) || beta-566 spawned with the ability to replenish itself with citalopram.
03:34:30 [0x202470c] (Mechanics - 252,254,1) || iota-601 spawned with the ability to replenish itself with hippiesdelight.
03:35:36 [0x20246fd] (Mechanics - 252,254,1) || beta-774 spawned with the ability to replenish itself with paroxetine.
03:35:38 [0x2024724] (Mechanics - 252,254,1) || antaeres-227 spawned with the ability to replenish itself with zombiepowder.
03:35:40 [0x2023655] (Mechanics - 252,254,1) || beta-362 spawned with the ability to replenish itself with drink

**This is why we can't have nice things.**

### CODE REVIEW

**Comment by SonixApache** [comment]
remove mechanics when

**Comment by Intigracy** [comment]
Aww.

Gotta love mechanics.

**Comment by Riekland** [comment]
I don't get why this is a bad thing though

**Comment by jknpj** [comment]
It makes containers with no icons and unlimited chems for dirty cheap, it is a very bad thing. You can cheese unlimited holy water/lube/blood really easily.

**Review by PJB3005 — APPROVED** [review]

**Comment by ComicIronic** [comment]
Should have used MECH_SCAN_FAIL : the item is not meant to be scannable at all, not even by antags.

**Comment by jknpj** [comment]
Yeah, i'll have to fix it

**Pull request merged**
