### PR TITLE
Wizard Spell: Invoke Emotion

### PR DESCRIPTION
**Pull request by GreatBigFailure**
Adds a new wizard spell called Invoke Emotion.
Costs 5 points. Does not require robes.

Targeting someone with it will invoke a paper and "quill" into your hands. The paper is bound to your target. You can write on it like a normal sheet of paper. Throwing the page looses your invoked emotions onto the target.
Once thrown the paper will teleport within 2 tiles of the target if not in their view. If it is in their view it will throw itself at them repeatedly. Those not targeted by the paper cannot pick it up.

**The paper cannot be burnt, melted with acid, folded, stored in an inventory, bag, locker, etc. It will destroy itself after being read and dropped by the target.**

Power upgrade costs 1, max level 5: 10% chance per level to deal a 1 brute damage paper cut when hitting the target. Non-targets trying to pick up the emotion invoker will receive brute damage to their hand equal to this upgrade's level. Each level also gives a 1% chance to knock the target down for half a second.

Move upgrade costs 5, max level 1: Adds a 20% chance for the emotion invoker to force itself into the targets hands when it hits them during a throw. Does not work if their hands are already full.

Cooldown upgrade costs 20, max level 1: Reduces the spell's cooldown from 15 seconds to 1 second. 

urafaget

:cl:
 * rscadd: New wizard spell: Invoke Emotion.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
I'll fix the dmi conflict after a review. I want to prevent needing to do it twice. Forgot to pull after the hangman spell was added.

**Comment by PrimeDSS13** [comment]
I literally only see this being used to force people to look at porn

**Comment by GreatBigFailure** [comment]
> I literally only see this being used to force people to look at porn

At no point did I imply otherwise.

**Comment by barbedwireqtip** [comment]
Awesome, can't wait to remotely goatse people.

**Comment by DeityLink** [comment]
Honestly I'd do it with that Ring Ring gif
You know the one

**Comment by jknpj** [comment]
This is terrible.

**Comment by DeityLink** [comment]
or an advert for Raid Shadow Legends

**Comment by DrSnips** [comment]
High amounts of FUN could come from this.

**Comment by Eneocho** [comment]
Remote forced WGW

**Comment by GreatBigFailure** [comment]
> Remote forced WGW

I considered making the cast phrase for it be "W'un Da'i Wy'le" but decided a bit of subtlety is important.

**Comment by Eneocho** [comment]
> 
> 
> > Remote forced WGW
> 
> I considered making the cast phrase for it be "W'un Da'i Wy'le" but decided a bit of subtlety is important.

How about "F'LL O'F T'YS", "H' C'LD N' L'NG'R H'LP H'MS'LF", "CH'RRY FL'VR'D L'BE", "J'CY K'WY' C'K" or "SQ'SHY WT' NOI'S'"? All of these are extracts from WGW, but aren't as obvious.

**Comment by KillFurries** [comment]
Annoying shit spam isn't fun for anyone but the one doing it. If something like this were to be added it also sucks how these spells are being bottle necked with the wizard. You're giving the annoying spam ability to the guy who also can turn invisible and teleport away. It would be far less annoying if a regular crew member got their hands on it, not the wizard, so they get immediately lynched after using it once.
Less wizardbloat please.

**Comment by Eneocho** [comment]
> 
> 
>It would be far less annoying if a regular crew member got their hands on it, not the wizard, so they get immediately lynched after using it once.

The crew already has this, it's called locutogen.

**Comment by GreatBigFailure** [comment]
@KillFurries Keep in mind there's plenty of other uses for this, but ya it'll mostly be used to send 20 letters that all say "benis :^)" to the HoS. The idea originally came from wanting to force more dialogue between the wiz and crew so every wiz round might not just be blink blink blink internal bleeding, blink, blink, dead. 

Gonna take this as a chance to go off about wizard content:

I like to make wizard spells that are extremely annoying but either totally non-lethal or require weird bullshit to be lethal with. This is because no one enjoys murderbone wizard, even the wiz often feels a little guilty about knowing he's turned the round into a death match most people have no chance to really play. The wiz still needs to be an antag though. The crew has to have reason to hate the wiz and the whole point of the wiz is no sense of right and wrong, giggling about being an absolute piece of shit. There's no one to giggle at if everyone is dead though.

I've been sold pretty hard on blob being the best designed antag because "The whole crew can participate". Wizard is often the total opposite, just blinks around and can only be stopped by a single shotgun bullet. So only sec and the wiz really get to participate in most cases. Traitors, vamps, etc get the advantage of initially being unknown so they have time to prepare gimmicks. Wizards are never on the crew manifest and know naming themselves "Kevin Johnson" instead of "Kevin McWizBeard the Magnificent" would summon homosexuality upon them. Wizards are far more limited in how they can interact with the crew because of that, and because of the threat of immediate IB-death the wiz can't stop for a second to talk.

Fixing all that would, currently, take a complete rework of the wizard. So instead I think it's best to add wiz content that doesn't lend itself to the issue, or reduces it as a band-aid. Giving the wizard more tools to do stupid gimmicks and involve more of the crew within the constraints listed above will help a lot. So ya, sending the captain a letter with a scribble of him eating the wizard's butthole will probably get the wizard shot, it's going to be easier for the rest of the crew to participate in the chase than if it was fireball, since everyone would be dead already or shortly after. Knowing the wizard doesn't have any spells like fireball or feint also increases the chances the crew won't immediately aim to murder him and instead keep him around for a trial, community service, etc. A lot of fun can result from those. 

Novel over

**Comment by gurfan** [comment]
wizard already embraces "annoying shit spam that isn't fun for anyone but the wizard" so this seems fine

**Comment by gurfan** [comment]
also make sure you can't put the paper in an envelope

**Comment by Blithering** [comment]
Upgrade should add a delivery owl.

**Comment by ShiftyRail** [comment]
Log the contents of the papers. I don't even want to think of the possible consequences.

**Comment by wotisjanitor** [comment]
Please don't merge this shit. If a wizard shows me porn I'm just logging off.

**Comment by DrSnips** [comment]
> Please don't merge this shit. If a wizard shows me porn I'm just logging off.

You must be 18 or older to play on this server.

**Comment by ShiftyRail** [comment]
@GreatBigFailure on top of adding proper logging, make a global list of emotions being invoked, and given admins the possibility to view them, prune them, or edit them. Should help with nasty porn being distributed to people.

I don't like this spell nor did I like the food spell, but that's just an opinion.

Making them unacidable is retarded, though. You need a way to deal with them.

**Comment by wotisjanitor** [comment]
> > Please don't merge this shit. If a wizard shows me porn I'm just logging off.
> 
> 
> 
> You must be 18 or older to play on this server.

sorry faggot i don't want literal shit forced onto my screen. This server has enough porn on it, and ways to distribute it as it is.

**Comment by DrSnips** [comment]
> > > Please don't merge this shit. If a wizard shows me porn I'm just logging off.
> > 
> > 
> > You must be 18 or older to play on this server.
> 
> sorry faggot i don't want literal shit forced onto my screen. This server has enough porn on it, and ways to distribute it as it is.

WOE IS ME, THERE'S BOBS AND A PEEPEE ON MY SCREEN.
Dail-8 m8.

**Comment by GreatBigFailure** [comment]
> @GreatBigFailure on top of adding proper logging, make a global list of emotions being invoked, and given admins the possibility to view them, prune them, or edit them. Should help with nasty porn being distributed to people.

Fair enough, I always forget to add admin things. This obviously has the potential to really, really need admin intervention though.

> I don't like this spell nor did I like the food spell, but that's just an opinion.

People bringing up summon snacks out of the blue like this is how I know I did a good job!

> Making them unacidable is retarded, though. You need a way to deal with them.

You deal with them by reading them. I even opted to not add any delay or prevention to closing the window, so you can "read" and close it immediately.
If a wizard casts just about any other spell on you the effect is immediate. This one the wizard needs to first get away and scribble his emotion down. You also only get one paper per cast so it's hard to really spam it.

**Comment by Blithering** [comment]
I'm just worried people will try to use this to lag others out

**Comment by GreatBigFailure** [comment]
@ShiftyRail Alright I added:

- A global list of invoked emotions
- Logging when someone writes on them and what was written. Though it will log when the paper is opened post-writing as well because of how paper works. If it becomes an issue you can easily just compare the logged messages  to see the origin.
- An admin panic button to ash all invoked emotions

I didn't add the editing because you can easily just var edit the info variable. This would be obvious to even non-codermins since it's likely a huge block of text that says "penis penis penis penis" in the var edit window.
Will fix the dmi conflict when I get the merge go-ahead.

@Blithering That's one reason I opted not to make it nanopaper after I was given the dark knowledge of adding videos to paper. One of many, many reasons that is.

@wotisjanitor Regarding forced scat porn or whatever, I think most admins would take action against that. Images also take long enough to load in most cases that you can close it before they do. I get the concern but the spell doesn't exist in a vacuum.

**Review by ShiftyRail — APPROVED** [review]
Just fix conflicts and we are good to go.

**Comment by Eneocho** [comment]
Make the spell phrase "J'CY K'WY' C'K" or "F'LL O'F T'YS".

**Pull request closed without merging**
