### PR TITLE
r*m*ve vector

### PR DESCRIPTION
**Pull request by SonixApache**
vectors are never used in their normal calibers, and often used in their retarded calibers, so the obvious solution is to r*m*ve vectors from general play and relegate them to bus-only

🆑 
 - rscdel: removed vectors from maps and the ammolathe

### CODE REVIEW

**Comment by ghost** [comment]
honestly fuck guncreep, we don't need like 50 guns with slightly different numbers so just start straight up removing them

**Comment by ghost** [comment]
Remove larger mag sizes, make assault rifles a more powerful vector, make vector a high mag-capacity gun.

**Comment by mentgah** [comment]
the PR that saved /vg/

**Comment by aceedex** [comment]
people add shit that enables retard strength roundstart
Instead of removing retard strength, I will remove a cool thing.
If youre seriously 100% on doing stupid shit like this, at the very least also revert the changes that make them spawn with a blacklisted adaptor

**Comment by yackemflam** [comment]
It's either removing the vector or the ammolathe, I say we remove both
You can always buy more ammo from cargo or print ammo from the autolathe
Or make the vector, and the ammolathe locked behind research like anything else that can kill easily
Throw in the glock for good measure because they're what started this mess

**Comment by aceedex** [comment]
Or just add the new mags to the blacklist and comment the ammolathe code to warn against adding stuff willy nilly. I don't like to get petty in GitHub but that's actually completely retarded thing you just said

**Comment by yackemflam** [comment]
Every ammo for the vector is brokenly op is the problem, even the base 15 brute because it does 30 dmg per click with the burst fire turned on, or if you have the autism to do it, you can go rubber/normal/rubber/normal/etc for a good 20 brute + tick stun per click
no matter how you slice it, it's pretty broken to have roundstart

**Comment by boy2mantwicethefam** [comment]
hahaha how is the vector real like just don't print it hahaha disposal it

**Comment by aceedex** [comment]
Yack you just made a bad egun

**Comment by yackemflam** [comment]
an egun that both stuns and does damage in the same shot
Also causes bleeding
Bypasses standard armor because the standard armor has 50 laser and 15 bullet

**Comment by DrSnips** [comment]
I find it ironic that sonix was for having vectors this way a year ago and having the blacklist was enough.
I'd like to blame the ammolathe getting retarded stuff added to it but sonix wants to stick it to me by removing them. _Its not like we have a specific var to solve this issue._ I for one fully embrace our cookie cutter gunplay where any form of players being innovative is removed within a week or two of them discovering it.

**Comment by BurntDevil** [comment]
This is stupid. Vectors were fine, and their gimmick was fine, because the mags were hard to come by and the ammo harder. Then some idiot decided to dump all the toys on a magic box. The solution isnt to remove vectors, its to make sec work to get the cool shit as intended. Remove the damn mags from the ammolathe.

**Comment by Accipitermaris** [comment]
biggest problem with vectors is that they can be trivially modded to accept all sorts of crazy ammo from the ammolathe like .357 that turns them into insane burstfire traitor revolvers in only a few minutes from roundstart

removing vectors works or removing their ammo modification feature also works

**Comment by DrSnips** [comment]
If you remove the ammo mod feature they just become glocks you can't dual wield. Might as well remove it at that point since that the entire point of them. A good ammolathe and vectors(without an updated blacklist) cant exist at the same time sadly.

**Comment by jknpj** [comment]
>using a blacklist

Your first mistake. Turn it into a whitelist.

**Comment by yclatious** [comment]
Ammolathe being about as shit as we all knew it could be. God bless hindsight, I get to tell you all it was a terrible idea and be 100% right.

**Comment by PrimeDSS13** [comment]
Why remove it, just limit which calibers it can use. You say that the issue is people switch calibers so maybe deal with that instead of removing vectors all together? This PR just seems a bit extreme.

**Comment by SonixApache** [comment]
the ammolathe being able to print exotic ammotypes is fine
makes it so that, inthe rare case where someone gets an exotic gun and wants more ammo, they're not gimped forever
being able to print ammo actually makes the ammolathe somewhat worthwhile

vectors on the other hand have to be nerfed into the fucking ground to make them anywhere near sane, and at that point they are essentially worthless

**Comment by aceedex** [comment]
or hear me out. hear me out. you keep the ammo there, we keep the vector there, we just dont put any retarded magazines in there. 
I dont know why youre being obtuse about this sonix, the non grudge code solution is also the simplest one that coulda been done without even opening dreakmseeker let alone doing map shit

**Comment by ShiftyRail** [comment]
But I want to feel like a Nuke Ops by using a vector with rubber bullets :(

**Comment by ArchSunder** [comment]
BRRRRRRRRRRTTTTT

**Comment by ghost** [comment]
make the gun blow up and kill whoever uses it with different calibers

**Comment by PrimeDSS13** [comment]
just nerf it aaaaaaaaaaaaaaaa

**Comment by 9percents** [comment]
as someone who actually has seen vector used, regular .380 caliber is used often too, the debraining variant is only used by antags or powergamers, having an automatic glock is better. The gun shouldn't take big damage ammunition at all, so just nerf it
.380 is a mistake, glock is a mistake

**Comment by Kammerjunk** [comment]
reminder: when the ammolathe was added, it was only with the assumption that it wouldn't get creeped and even then, it having two guns printable made it teeter on not being merged
remove the entire thing

**Comment by GoodG1448** [comment]
I still miss my 12 gauge buckshot game-crashing machinegun.

**Comment by SirSkeleto** [comment]
look im just saying having buckshot on 2 round burst was the greatest thing that ever happened to me as HoS and to the vampire who left mist form one tile away from me

**Comment by SonixApache** [comment]
drslimes has explained to me why i am wrong and as such i will be closing this

**Comment by SonixApache** [comment]
actually fuck that guy

**Comment by boy2mantwicethefam** [comment]
you should leave it for box tbh because everyone knows boxbabies are God's chosen people

**Comment by Kurfursten** [comment]
Currently this has a close but not-insignificant majority of votes, so I am inclined to merge it. However, there have been some good counter-proposals such as changing the vector, adapter, or changing the ammolathe.

I am going to give those people who want to see an alternate solution 3 days (until 29th) to post some counter PRs and see if those get a more positive reaction. If you want something different, therefore, put your code where your mouth is.

**Comment by dunsel-hordon** [comment]
Just remove being able to change the receiver on the vector. I mean you can get the extended mag from the ammo lathe and that is what makes it better than the glock.

**Comment by DrSnips** [comment]
Love you too sonix. I guess I can throw my hat into the ring.

**Comment by xeroxemnas** [comment]
Yeah let's take away more things instead of even attempting to balance them. This is an awful PR.

**Comment by xeroxemnas** [comment]
> Currently this has a close but not-insignificant majority of votes, so I am inclined to merge it. 

How is 5 votes even close to significant. Hold a server poll or something.

**Comment by yackemflam** [comment]
You can either nerf the vector into uselessness and against it's fundamental use because 9mm and .45 acp is too strong on the vector or you can just remove it overall

**Comment by Kurfursten** [comment]
I'd like people in this PR to go vote on this counterproposal.

#25940

**Comment by Kammerjunk** [comment]
I don't believe in voting

**Pull request closed without merging**
