### PR TITLE
Vampires changes

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
What initially started off as me looking into the discrepancies of blood sucking eventually rolled into a larger vampire change, aimed at tweaking vampires.

**The important stuff**
- Diseased Touch is removed. It's not fun.
- Vampires suck twice as much blood out of a target but still receive the same amount of blood. This means both that the vampire can't get about 500 usable blood out of someone and also that victims of a vampire suck will collapse significantly sooner from blood loss.
- Vampires can now examine a target to see whether they are eligible for having their blood sucked, and how much blood they carry. It won't tell them if the other is a vampire though.
- Silent biting is now silent. No longer has a wind-up time of 30 seconds, no longer alerts people that the vampire started chowing down on someone. It sucks at a rate of about 25%, people!
- Vampire darkness cloaking now only works in darkness, meaning vampires won't be transparent in the brightest places in existence, but the amount of visibility reduction has been intensified to compensate.
- If a null rod is carried by anyone that isn't a chaplain it will no longer backfire the mature vampire's abilities against the vampire but they will still be protected by the null rod.

**The less important but still good bits**
- Vampires will no longer suffer blood poisoning from having mismatched blood. They're universal receivers!
- Fixed a bug where Glare could work through blindfolds.
- Fixed a bug where Screech could still work on some targets even if it was nullified by a chaplain's null rod.
- Vampires revealing their true forms will now properly update their names.
- Vampires can't switch their bite types when sucking someone, if it started off silently it's going to remain silently until they take their teeth off their target.

:cl:
 * rscdel: The vampire's "Diseased Touch" ability has been removed.
 * rscadd: Vampires can now see from a distance whether a victim is eligible to be sucked and how much blood they are carrying. This will NOT reveal other vampires!
 * tweak: Vampires will now suck blood at a ratio of 1:2, meaning that for every unit of blood the vampire drains the victim will lose 2.
 * tweak: The vampire's "sleight of teeth" ability has been improved significantly; it no longer has an initial delay of 30 seconds and it no longer alerts anyone in the vicinity.
 * tweak: The vampire's "Cloak of Darkness" ability has been changed; it no longer works in bright light at all but in sufficiently dark areas it is even more potent.
 * tweak: Null rods carried by players that are not chaplains will no longer cause vampiric powers to backfire against mature vampires, instead it will only protect the wielder.
 * tweak: Vampires will now properly consume blood from beakers and other containers without getting blood poisoning from mismatching blood types.
 * bugfix: Fixed a bug where the vampire's "Glare" ability merely informed the vampire whether they were blindfolded or not, rather than actually stopping the ability from being done due to being blindfolded.
 * bugfix: Fixed a bug where the vampire's "Screech" ability would affect nearby victims even if it was nullified by a nearby chaplain with a null rod.
 * bugfix: Fixed a bug where vampires revealing their true forms would appear as "Nosferatu" right away rather than as "Unknown", not just because they are meant to be Unknown for as long as they are in their true forms but also because their identities would be visible even when there would be no way to discern their identities.

### CODE REVIEW

**Comment by Kromkar** [comment]
Seem like good changes

**Comment by AdrianoKing** [comment]
Not sure about this one.
In a way vampires could use a patch but...
First off making them need more bodies on a role that already plays the long game is downright atrocious.
Taking off diseased touch is a take i guess.
The rest i can very well fall behind but nerfing an antagonist that already has trouble getting himself up and only is a problem early on if used by some very niche veterans is just not it.
I'll end this on a personal take but i treat a Vampire as a Wizard that "earned" his powers, making things harder for them to rise is just not the way.

**Comment by boy2mantwicethefam** [comment]
The change to bodies is more so that they don't get to spam spells from sucking on one body too long, and to compensate for that victims will lose blood significantly faster.
It's important to note that vampires have a limit of 200 blood from the victims they can get from one victim that can be used for the purpose of becoming stronger (unlocking abilities, basically), any more blood only contributes to the vampire's resources for casting spells. With or without the change vampires still need 4 bodies to attain maximum power (more specifically 666 blood, which grants them the ability to revive and summon a cool cape). The vampire's most expensive spell is Enthrall for 150 blood, and that essentially turns someone into an antagonist subservient to them. Before the change a vampire can do 3 Enthralls out of all the blood they'd get from 1 body, about 17 Screeches, 25 Mist Forms...

**Comment by Eneocho** [comment]
`>2 PRs from 2 different coders that remove diseased touch`
hmmm

**Comment by githubuser4141** [comment]
Why.. is the 2x much blood a good change? It means they'll murderbone more, and literally means human life isn't as valuable as it was. So having 1-2 people as 'friendly' blood banks is not even worthwhile, you might as well just kill them.

**Comment by Killette2** [comment]
Removing diseased touch is too much without adding enough. Vampires very limited escapes are plagued by long cooldowns, so what utility would you put in its place where with it I can touch a head of staff or officer?

**Comment by wotisjanitor** [comment]
Cool we have to fight 2 shit pr's at the same time

**Comment by wotisjanitor** [comment]
What if vampires had to kill MORE people to get stronger but we made them weaker?

**Comment by wotisjanitor** [comment]
image
The best argument against this PR

**Comment by DorainGrey** [comment]
> Removing diseased touch is too much without adding enough. Vampires very limited escapes are plagued by long cooldowns, so what utility would you put in its place where with it I can touch a head of staff or officer?

They have both a variant of Jaunt & Blink, that's aside from their direct combat abilities such as a free Aheal in rejuvinate, screech, glare. Thrall, so they can make their own cult, to do the fighting for them.

You can't seriously be in good faith suggesting this somehow weakens vampires significantly, literally a dozen other way to kills heads.

**Comment by boy2mantwicethefam** [comment]
@githubuser4141 Vampires still get a lot of blood, and "blood banks" aren't ruined because their blood can always be refilled.
@Killette2 I wouldn't say that vampire escape abilities are very few in number. In fact they're among the highest an antagonist has, and innately too. Just gotta activate them at the right time. As for a replacement I'm not exactly sure, what replacement SHOULD a vampire have?
@wotisjanitor Vampires already are limited to a maximum of 200 blood for the purpose of getting stronger, any excess only contributes to casting spells. The change still lets them get more than 200 blood out of someone, they won't have to kill more people than they already do.

**Comment by SonixApache** [comment]
fuck it, why not

**Comment by gurfan** [comment]
>vampires limited escapes

Vampires currently have:

- A Jaunt (with bonus bats)
- A blink
- One instant stun-removal button
- One AOE stun
- One AOE stun with a longer range
- One reusable parapen 
- A revive button assuming they aren't beheaded or ashed
- the ability to heal literally any kind of damage without medbay or surgery as long as you have five planks of wood on you
- bats too I guess

oh and thralls exist too but that's a whole 'nuther can of worms

>so what utility would you put in its place where with it I can touch a head of staff or officer?

I don't know maybe one of the above. I don't think the ability to silently kill people (with a virus that has to cured somehow, too!) without any traces or meaningful interaction whatsoever is something worth keeping.

**Comment by Kurfursten** [comment]
I think most of this PR is good, but I think there are basically 2 things that people don't want:

- Remove diseased touch
This was already attempted in a more atomic matter quite recently, but now you're trying to bring it in under an umbrella PR which feels bad. You might argue that this is different because you're "giving" the vampire some things to balance the removal... but you're really only giving the vampire bugfixes and small quality of life features.

- 50% of sucked blood is wasted
I don't see what this is aiming to achieve other than making vampires kill more. Why are you removing a vampire attack while simultaneously trying to make them more combat oriented?

You can break this into atomic PRs, particularly the bug fixes.

**Comment by wotisjanitor** [comment]
ahahajahahhahahaahhhahahahahahajahjaa

**Comment by boy2mantwicethefam** [comment]
A shame that most of the changes have to be rendered atomic, sometimes you gotta bundle all that stuff up or else the end result can be severely unbalanced if some go through and the others don't. I can't really do any changes to buff vampires such as making the Nosferatu form far stronger (and more of a permanent transformation) since the vampire is already overloaded in spells and abilities and Diseased Touch seemed like a low branch to trim.
But I've also played a vampire again yesterday and haven't changed my mind on any of the PR's contents so I'll push for most of them, mostly individually.

**Pull request closed without merging**
