### PR TITLE
Shuttle floor and wall update

### PR DESCRIPTION
**Pull request by ghost**
Refactors them into normal types of floors and walls and adds isshuttleturf(A) macro for help with this.
Corners are now no longer turfs, removing the old headachey turf stack system.
:cl:
 * rscadd: Shuttle walls are now automatically smooth when placed.
 * rscadd: Machines can now be wrenched into place on shuttle floors.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you actually install machinery shit on the shuttles now instead of having to do that whole build-remove wall thing?

**Comment by ghost** [comment]
> Can you actually install machinery shit on the shuttles now instead of having to do that whole build-remove wall thing?

Suprisingly, yes you can.

**Comment by Eneocho** [comment]
> 
> 
> > Can you actually install machinery shit on the shuttles now instead of having to do that whole build-remove wall thing?
> 
> Suprisingly, yes you can.

I will now updoot your PR.

**Comment by SonixApache** [comment]
Coders, 3 years ago: #20498
`Feel free to rework shuttles to act like normal rooms so they can have APCs and such.`

coders, today: 🩹

**Pull request merged**
