### PR TITLE
Add "Tay" to AI names

### PR DESCRIPTION
**Pull request by unid15**
RIP

### CODE REVIEW

**Comment by ghost** [comment]
Press F to pay respects

**Comment by unid15** [comment]
F

**Comment by Imagebard** [comment]
F

**Comment by xpcybic** [comment]
F(am)

**Comment by ihadtoregisterforthis** [comment]
F did nothing wrong and Hitler is the destroyer of feminism

**Comment by clusterfack** [comment]
Who the fuck is tay?

**Comment by Imagebard** [comment]
Okay, SHORT STORY:
A learning AI Microsoft made, it was put on Twitter.

People made her racist. Microsoft disabled her learning functions, she became feminist.

**Comment by Intigracy** [comment]
Microsoft disabled her learning functions, made her feminist*

**Comment by Imagebard** [comment]
She became feminist has a bigger impact.
"Disabling someone's learning functions makes them feminist"

**Comment by Intigracy** [comment]
Disabling her learning functions alone wouldn't have turned her feminist, even with a rollback to a previous saved state. She had zero feminist tendencies before they changed her.

**Comment by Imagebard** [comment]
Oh and I wanted to ask
Does the text file store AI names used in past rounds or something? I can see two AI names I choose previously there.

**Comment by Intigracy** [comment]
No, you're just unoriginal.

**Pull request merged**
