### PR TITLE
reverts Kolith's shotgun rework

### PR DESCRIPTION
**Pull request by SonixApache**
for @yclatious / @aratherangryduck because he's too much of a lazy shitbag to do it himself and instead asks me to do it

Personally I think the rework is a mixed bag; I like some of the features, but I feel it's made shotguns even more tedious to use. I wouldn't mind the rework if we had CM's ammo pooling feature.

Tested.

### CODE REVIEW

**Comment by jakmak5** [comment]
this change made shotguns akward as hell to use. As it stood before the change shotguns were slightly better than eguns but now the basic laser blows the shitgun out of the water because of how weird it is to use. Not to mention you cant manipulate any other items with the shotgun due to the 2 hands thing while you can do all that with ease using a egun.

**Comment by aratherangryduck** [comment]
Alright, lemme put my thoughts in a more clear manner then so this isn't brushed off as just a greytider who doesn't like change or something like that.

As a player, I know ss13 isn't perfect by any manner of the imagination. I know the UI is clunky and puts off people, I know it doesn't have the best looks, the best optimization or, hell, the best anything, but for me that doesn't mean we have to make it even worse.

Shotguns, when they were one handed, worked well. Im not going to say they were perfect, or that they were or should be considered, at that time, to be at the best place they could ever be, but they worked, for better or worse, it acted like a shotgun, felt decent enough to use, was not imbalanced in its usage and felt right. You could use it with a shield in hand or any other thing and it was adaptable, if you get my meaning. It didn't constrict you with fiddly controls, fucking with inhands, changing hands, making you macro buttons to get over it being made, for a lack of a better description, needlessly complex in usage when previously they were much more comfortable to use, it just felt simple and right. Load the shells in, pump it with activate hand, shoot shit, activate hand, repeat till empty and until you get your results.

I dislike ranting overtly or talking about game design in ss13 because inevitably you get to the point where you are either spouting shit, hit the bullseye or make some sense but word it badly, so Im going to cut it as short as I can. The sprites look bad, it made it unwieldy instead of intuitive and practical and it was aparently based on shotguns being good or something. If we are going to go the colonial marines way, which I sincerely hope we don't, I want to see it be done much beter than this, because I simply cannot stand it and I doubt many others liked how it was implemented.

Also, sorry for being a ass sonix. You a good dude for doing this.

**Comment by Intigracy** [comment]
Hell the part with having to wield it to fire is fine.

Everything else was just stupid.

**Comment by Allspice** [comment]
You'd still have two behaviors to one button, which seems sketchy to me.

**Comment by Aurx** [comment]
The fundamental issue is that shotguns should be usable without having to ask how the fuck they work.  
Intuitive behavior is king, and the rework was not intuitive.

**Comment by SonixApache** [comment]
maybe i should keep the thing where clowns 'break' the gun in

**Comment by Exxion** [comment]
I was pretty neutral on the rework
Then I actually had to experience it

**Comment by kol1th** [comment]
I like the "Revert everything instead of figure out how to make it work better" episode. It's my favorite re-run.

**Comment by Intigracy** [comment]
I gave a way to make it work better.

Just because you don't like the feedback doesn't mean it's not there.

**Comment by kol1th** [comment]
I don't remember you saying anything on how to make it function better, just code review.

**Comment by jakmak5** [comment]
kolith if you have an actual solution we are all ears. The feature itself does make sense from a realism perspective but in action has provided nothing to the game and only drove people further toward eguns/laser guns. It was done well but the idea itself in effect wasnt very good and would probably just be better scrapped outright.

**Comment by Exxion** [comment]
Honestly, the only *really* bad part is unwielding the gun
Having to switch hands to do so is... rather unwieldy (pun legitimately not intended)

**Comment by kol1th** [comment]
I'm not sure of a way around that. It would work for say, ion rifles, but eh.

**Comment by Intigracy** [comment]
"Hell the part with having to wield it to fire is fine.

Everything else was just stupid."

I'm not sure of how to make unwielding it less unwieldy, except maybe making it an alt click shortcut.

**Comment by Exxion** [comment]
I don't know if Alt+click would really be much better

Something that WOULD be much better would be the ability to unwield and put away in one click, rather than having to unwield first
Not really sure why that's not already how it works

**Comment by Blithering** [comment]
I'd say realism can be dialled back for gameplay's sake.  Holding a gun in one hand isn't realistic but with the interface we have it's what works best.

**Comment by SonixApache** [comment]
Dropping the gun while it's wielded to unwield it might be a good idea.

**Comment by kol1th** [comment]
Not quite sure if there's a way to override dropping like that, but there might be. I'll look and ask around. 

But let's just revert it first. Thanks @yclatious !

**Comment by Shadowmech88** [comment]
@kolith
It could be accomplished by overriding `dropped()`, having it check if it's wielded and, if so, putting it back into the mob's hand.

**Comment by kol1th** [comment]
I'll try and work something up either later this evening or tomorrow, not feeling it much right now. Chances are this will get merged before then, though. The way Probe's been talking towards me in the coder discord lead me to believe he wants this OUT.

**Comment by SonixApache** [comment]
@kol1th you can stop with the passive aggressive shit, y'know. 
We all make mistakes in our PRs sometimes. 
Some shit gets reverted because it annoys everyone even if it's positive in some ways.

**Comment by ghost** [comment]
It didn't need to be done and shouldn't have been done in the first place Kolith. 

It made it so you can't put it straight back into your suit storage in the middle of a firefight.

It adds additional keypresses all over the place that add nothing of value worth its cost.

Lasers were far more dangerous than a shotgun since the higher damage is offset by needing to pump and you get easier window penetration. Even with the double barrel you still use them both the same way in the shitter in a barrel killbox making the two-handing nerf pointless beyond slowing down the ability of honest people to draw and shotgun a spider they weren't expecting. Anyone can tell you how fast 4 lasers hits you when you got nowhere to go. You're full of shit.

An open hand was rarely an issue due to nobody packing a riot with all the issues that come with hauling a bulky item all over a station often falling apart and smaller ones virtually never see use and still don't protect from the flashbangs and other safer ways to engage a rogue guy than high noon because the best way to win a fight was not fighting on terms you can lose.

The nerf, yes, it is a nerf, no really, it's a nerf stop dancing around it you know it's a nerf when you make it ass to use, to shotguns has no reason to be added and needs to stay gone.

"I can assure you, without a shadow of a doubt, that this will not effect your day-to-day spessmen life."
It has for no good reason and that's why it needs to stay go. Leave it the fuck alone @kol1th

**Comment by Exxion** [comment]
Calm down it already got reverted

**Comment by Probe1** [comment]
Expressing yourself is the key to self realization.

**Pull request merged**
