### PR TITLE
Adds a Street Alchemy One-Use Spellbook

### PR DESCRIPTION
**Pull request by GreatBigFailure**
What the title says. It's now available through both summon magic and the wizard bundle. 
Because it's a low-cost spell intended to be upgraded I also threw a murky potion into the summon magic version for funsies. I'll remove that if it seems snowflakey.

:cl:
 * tweak: Street alchemy can now be gained through summon magic and wizard bundles.

### CODE REVIEW

**Comment by Kurfursten** [comment]
It's fine to get a weak spell, some people get smoke, remember

Potion really doesn't have to do with street alchemy at all, it's an unrelated item

**Comment by GreatBigFailure** [comment]
Fair enough, was just going with the alchemy theme. I'll remove it when I fix the gonfligs.

**Comment by Kurfursten** [comment]
Given that there's now a summon potions PR on the way, it's treading on the toes of that one too (although you couldn't have known that at the time)

No big rush, it's only 20 hours old of course

**Comment by anunknownentity03** [comment]
gonfliggds

**Comment by GreatBigFailure** [comment]
I'm just so tired

**Pull request closed without merging**
