### PR TITLE
Politeness for spacemen - no longer pushing each other on airlocks

### PR DESCRIPTION
**Pull request by ShiftyRail**
## Motivation for this PR

_The station is in utter chaos. You frantically rush to the escape shuttle. At last, you make your way to the airlock and run to safety.
Wait a second, there's someone here. You push them back, after all, you **are** the protagonist.
They push you back, how rude of them. You are not going to let that slide. Asserting dominance, you push them back again.
They push you back. You push them --_

You get the idea. This PR is here to prevent such a thing from happening at round end. It is, admittedly, less of a problem now than it might have been in the past (airlocks open in 0.5 seconds as opposed to 1 or more seconds before), but I still think the QOL is noticeable.

## Fine print

You should still be able to shove people aside if you are on harm intent and they are on help intent.
Movecode is a bit of a mess, so I tried to make this as lightweight as possible without too much refactoring.
Problem is, making this properly (via an event that gets called/uncalled when you open the door or move) requires a tiny bit of refactoring as can be seen in the files changed. 

Some of the ... constraints ... required by movecode are detailled in comments.

## Testing

As I touched on airlock forcing procs, I tested if those still worked as intented (emagging, crowbaring). They work fine.
I used two clients, varedited on airlock to have a very long opening sequence (5 seconds), had one of my spessmen open it and the other try to bump into them. It works as intented.

## Why it's good for the game

QoL and less frustration on escape. 

:cl:
- tweak: You will no longer tileswap/push aside another spessmen who is trying to open an airlock if you both are on help intent.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
nvm there's some edge cases I've not looked at yet

**Comment by ShiftyRail** [comment]
There's an argument that the chaos at the shuttle is a core part of the game. That's somewhat understandable. I do think it's worth pointing out that the chaos of the shuttle is IMO an example of a "forced" chaos and that it gets old and tiring pretty quickly. Being a nuisance to other players should be a concious decision on the part of the player, not something that happens "automatically" due to the jankyness of the code. 

Moreover, I should mention that while the guy opening the door gets protected during the door opening, this doesn't last long enough to prevent the person following them to pass them over as soon as the door finishes opening. The feeling of chaos will still be there, it'll just be less frustrating to actually play through. You should also be aware that there'd still be chaos on the line behind the guy opening the door.

Again, it's just the guy opening the door that gets protected for 0.5 seconds so that it's less of an annoying blur everytime. I'm confident there's more than enough chaos in this configuration.

**Comment by MercuriusGH** [comment]
>coder that doesn't play the game
>abhorrent PR

is this also a prelude to europa lights ruining the server in november/december again?

**Comment by ShiftyRail** [comment]
@MercuriusGH you know, why not. I'll probably have time to spare back then and it'd be silly to break traditions.

**Comment by Eneocho** [comment]
snrub

**Comment by ShiftyRail** [comment]
I saw this from the pov of QoL but I realise now this is something people enjoy more than I anticipated. That's fair enough.

**Comment by hacker-on-steroids** [comment]
what the hell is this even supposed to do?
disable help-intent moveswapping?

**Comment by ShiftyRail** [comment]
In the split second window when someone was opening an airlock, yes.

**Pull request closed without merging**
