### PR TITLE
invulnerable walls are now bomb blocking instead of just bomb-proof

### PR DESCRIPTION
**Pull request by Intigracy**
I exploded the right one first and it blew everything up, the left one caused no damage except the floor in the middle.

### CODE REVIEW

**Comment by Exxion** [comment]
Whatever happened to Deitysplosions, anyway? Why are those never turned on?

**Comment by PJB3005** [comment]
@Exxion they are though?

**Comment by Exxion** [comment]
You sure? Because explosions on the server sure do look pretty circular, even when tough walls are involved

**Comment by ihadtoregisterforthis** [comment]
Use the button to predict a bomb and compare with a real bomb. Explosions aren't so different with regular walls and open space.

**Comment by Intigracy** [comment]
They're turned on, the explosion_blocks are just shit low.

**Comment by SkowronX** [comment]
Needs to protect the mob too if the explosion came from outside

**Comment by Intigracy** [comment]
Pretty sure it handles that way already.

Explosion_block removes strength from a bomb passing through it by that much.

**Comment by DeityLink** [comment]
@Exxion it's as they said. Walls and even Reinforced walls only slightly reduce the reach of an explosion in a given direction. Also that he's making those walls actually explosion-proof just by changing a var that I created proves that my method still works.

@SkowronX Unless you are standing on the turf that's supposed to block the explosion, you will be fine.

**Comment by 9600bauds** [comment]
Upping the bombcap for deitysplosions was a mistake, the bombcap is way too big and deitysplosions didn't compensate for that in any way

**Comment by DeityLink** [comment]
Adding 1 to the bombcap means that you need to add 1 layer of wall around the bomb to obtain the same effect. Unless we upped the bombcap by 3 I don't think that's necessary.

Closed doors also block explosions.

**Comment by Intigracy** [comment]
balancing explosions can be done seperately, I just want a wall that's going to block explosions from passing through, and invulnerable is already a great choice.

**Comment by ghost** [comment]
I've always thought of completely dumping the ex_act system and using an universal bomb energy value to determine the actual damage done, but it would need a large overhaul to work properly

In this case, walls could actively absorb bomb energy in a certain direction

Also yeah, change how Toxins work

**Comment by Intigracy** [comment]
That's literally what explosion_block does dylan.

**Comment by ghost** [comment]
I meant literally get rid of hardcoded ex_act() amounts (dev, dest, light, flash) and change it into a single energy value. Which is absolutely anything but trivial

**Comment by ghost** [comment]
Would this mean that, say, if some dumbdumb decided to explode the thunderdome on box, it wouldn't necessarily reach the emergency shuttle and damage that?

**Comment by DeityLink** [comment]
For that we still need to add a few lines of code, so explosions take the thunderdome's blockers into account, and the thunderdome's surroundings should use snowflake turfs/doors that have maximal explosion resistance

**Comment by Intigracy** [comment]
merge pls, invulnerable walls aren't used on any maps that I remember

I can rework the unsim wall var later, possibly rebalance explosions on sim turfs too.

**Comment by PJB3005** [comment]
[it makes fucking sense] tag when?

**Pull request merged**
