### PR TITLE
Make code support year 2019.

### PR DESCRIPTION
**Pull request by PJB3005**
There was a pretty bad date/time bug in the code for 2019, this fixes that.

:cl:
- bugfix: Prevented time anomalies in the code.

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
(changelog needed)

**Comment by DrSnips** [comment]
It's [current year] already.

**Comment by SirSkeleto** [comment]
what about https://github.com/vgstation-coders/vgstation13/blob/978ff1d1cfe8e826e8a7c806241213cae6f7bcba/code/modules/reagents/reagent_containers/food/drinks.dm ?

**Comment by MadmanMartian** [comment]
the vintage 2018 wine?

It still fits.

**Pull request merged**
