### PR TITLE
Christmas stuff

### PR DESCRIPTION
**Pull request by ghost**
Christmas stuff

Adds Christmas jumpers, santa hats (Not the space ready kind) and fixes the christmas cracker paper hat from having no worn sprite to having a silly worn sprite.

Also adds polar bears, snow crabs (Celts suggestion) and living gingerbread men (Thread suggestion)

Christmas jumpers, santa hats, festive wrapping paper, and christmas crackers can be bought from cargo via the "festive" crate under Hospitality.

Thank you to Celt for being my second opinion on the sprites.

Really shouldn't have left this so late.

### CODE REVIEW

**Comment by clusterfack** [comment]
Looks pretty neat

**Comment by Imagebard** [comment]
Where's the Snowtrooper Armor for star wars.
Was that someone else?

**Comment by Intigracy** [comment]
There's already star wars sprites ingame from that guy.

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
@clusterfack why did some of the files not merge properly?

**Comment by clusterfack** [comment]
I have no idea what you mean

**Pull request merged**
