### PR TITLE
[Box] Fix Telecommunications Atmospherics, add Mechanic Requests Console

### LINKED ISSUE #6264: No requests console in Mechanics office
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
7bf8e32a676c8693bcde1758601585c3d7cf2b36 

>General description of the issue
Box station mechanics office has no requests console. The addition would make it easier for people to request equipment from mechanics and for mechanics to request stuff.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

### LINKED ISSUE #6272: Map issue box: Tcoms waste and cold loop lines are both connected
onefuckingturftotheright

These two pipes are on the same layer in an impossible way, making them both in the same loop.

I tested this by attaching a canister of N2 to the waste line, then scanned the cold loop line. There was N2 in the cold loop line.

### PR DESCRIPTION
**Pull request by ghost**
- Fixed strange pipe layout in Telecommunications which led to unintended interconnected pipe loops. This also led to the cooling loop draining into space every single round
- Added a Requests Console to the Mechanic

repipe_tcomms_console_mechanic

Fixes #6272
Fixes #6264

### CODE REVIEW

**Comment by Kurfursten** [comment]
Does the requests console have a name and proper department-type flags?

**Comment by dylanstrategie** [comment]
Named Mechanic Request Console, department-type 2 (I just picked the same as R&D, because Mechanic is basically a second R&D lab with experimental machinery added in)

**Comment by Kurfursten** [comment]
4 might be preferable for mechanics given their role as eng+sci

You also need to set the department variable to "Mechanics"

**Comment by dylanstrategie** [comment]
Department variable is already Mechanic. I feel it's good enough as is

**Comment by PJB3005** [comment]
Fucking dylan use subtypes, these instances are bullshit.

Also fucking add it to the other maps too.

**Comment by dylanstrategie** [comment]
Done

**Pull request merged**
