### PR TITLE
Box Brig Rework

### PR DESCRIPTION
**Pull request by GeneralVeers25**
[box] [qol]

Inspired by and largely based on the work of @dylanstrategie, this PR aims to make the Box Brig a little more user-friendly for our hard(ish)working men and ("wo"men) in red.

Box Armory button courtesy of @ShiftyRail.

**Before:** https://lambda.sx/J4n.PNG

**After:** https://lambda.sx/56K.PNG

Key changes are in the Changelog below.

:cl:
 * experimental: All of the following apply to Box.
 * rscadd: Nanotrasen has decided that 'Carp' are not an appropriate pet for the Head of Security. To deter these and other space-based avian intruders, Nanotrasen has invested in some Privacy Shutters for the Office.
 * rscadd: More than one Security Officer has drowned to death while taking an unusually long shower in the middle of their shift. Central Command would prefer these tired officers lie down in the Security Dormitory instead.
 * rscadd: The Execution Chamber has been streamlined for sleek, high-efficiency executions.
 * rscadd: Security's Armory as been redesigned and expanded, to make it more functional and easier to loot. Notable additions include shutters to hand out guns freely to the redtide and a button to open all of the windoors.
* tweak: The Security Hardsuits in the main E.V.A. have been replaced with Survivor's Hardsuits. The Security rigs are now located in either Security's E.V.A. or are in the Secure Armory.
* bugfix: Found a lot of missing pipes and broken wires across the map and I generally tidied it up.

### CODE REVIEW

**Comment by SonixApache** [comment]
remove jokes from CL
unless there's actually survivor hardsuits in the armory, in which case
remove survivor hardsuits

**Comment by GeneralVeers25** [comment]
To clarify, there are no Survivor's Hardsuits in the Secure Armory. Those suit dispensers contain two more Security Hardsuits (largely intended for the Warden and Head of Security).

I took them from the main E.V.A. above the Bridge and replaced them with Survivor's Hardsuits. This ensures that there are still only five Security hardsuits available on Box at the start of each round, but concentrates them in the Brig.

**Comment by SonixApache** [comment]
Oh. That's kind of weird, but okay, I guess.
Why not replace them with straight-up softsuits, for civilian usage?
Why replace them at all?

**Comment by jknpj** [comment]
Remember when survivor suits were supposed to be a roid-only thing

**Comment by GeneralVeers25** [comment]
I 'member.

I'm open to putting the straight soft-suits there but I'd rather redesign EVA to accommodate more than two at that point.

**Comment by SonixApache** [comment]
throw the soft suits in for now, redesign it at a later date

**Review by MadmanMartian — APPROVED** [review]
Looks good. Worried that the greytide virus event may end up opening that new airlock to space though, might be worth testing just to be sure

**Pull request merged**
