### PR TITLE
SPORKS!

### PR DESCRIPTION
**Pull request by DeityLink**
This adds sporks to the game. 
image

:cl:
* rscadd: Added Sporks to the game. Metal ones can be obtained from the Dinnerware as a premium item, while plastic ones can be crafted from plastic sheets.
* imageadd: Forks, Spoons and Sporks now all have in-hand icons.

### CODE REVIEW

**Comment by SonixApache** [comment]
> I'll let someone else decide where they should be made available.

`code/game/machinery/vending.dm`
`code/modules/RCD/schematics/service.dm`

also a couple of Zam packs come with plastic/teflon forks, perhaps plastic/teflon sporks would be more fitting
`code/game/objects/items/weapons/storage/bags.dm`

**Comment by wotisjanitor** [comment]
Why nerf forks?

**Comment by DeityLink** [comment]
what?

**Comment by Hinaichigo** [comment]
*holds up spork*

**Comment by PrimeDSS13** [comment]
I'd just throw em in the culinary vendor
adminbus only items such as this essentially don't exist

**Comment by west3436** [comment]
utensil powercreep

**Comment by angryturnip** [comment]
What's next? Spifes??

**Comment by DeityLink** [comment]
> What's next? Spifes??

So that's what those are called
image

**Comment by Eneocho** [comment]
> > What's next? Spifes??
> 
> So that's what those are called image

Requesting 20% chance to cut your mouth if you mash eat with the spife

**Comment by DeityLink** [comment]
I'm not actually adding spifes in this PR

**Comment by SonixApache** [comment]
> What's next? Spifes??

tactical sporks that have a knife in them, we'll throw them in the alcatraz crate

**Comment by ManopolisJones** [comment]
metal sporks?????? also, where would you get these, is this a premium item in the kitchen vend?

**Comment by DeityLink** [comment]
Eh sure why not, here it is now.

**Comment by Theophrastus1** [comment]
hardcode in characters named Guido Scampanelli starting with a holstered spork

**Comment by SonixApache** [comment]
> hardcode in characters named Guido Scampanelli starting with a holstered spork

port the HRP-serb loadout system so guido can just choose to spawn with a holstered spork

**Comment by Kurfursten** [comment]
conflicts

**Comment by DeityLink** [comment]
fixed

**Pull request merged**
