### PR TITLE
Hulk Hotfix

### PR DESCRIPTION
**Pull request by Shadowmech88**
This oversight has existed for far too long.

:cl:
 * tweak: Hulks are now big guys.

### CODE REVIEW

**Comment by ghost** [comment]
I would say 'but there's no reset' but then again collapsing resets any transformation as it itself is a transformation.

Good shit

**Comment by ghost** [comment]
It appears I was mistaken

**Comment by Shadowmech88** [comment]
I did not account for the fact that being buckled in when you pass out causes your `transform` to not reset.
On the bright side it sounds like it was *really* funny.

**Comment by Probe1** [comment]
It was pretty damn funny.

**Comment by Exxion** [comment]
Yeah transform never resets unless you reset it
All changes are relative

**Pull request merged**
