### PR TITLE
Glass floors QoL + powercreep

### PR DESCRIPTION
**Pull request by SonixApache**
Doubled health for starters
Fat people and normal vehicles no longer crash through.
Removed some oldcode
Removed the crashing through code and messages
removed knocking so you don't waste time with the cooldown when you misclick
only hit the glass on red intent now
even hulks have manners when it comes to touching glass floors now

changelog later

### CODE REVIEW

**Comment by Coxswain-Navigator** [comment]
Fatties should break glass floors, this is a buff to fatasses

**Comment by SonixApache** [comment]
I understand that the fat thing is really funny, but in practice it's really really annoying and stupid.
Same thing for clowncars and janicarts and secways. Funny, but really annoying and stupid.

**Comment by VNLoverMay** [comment]
What if there were two variants? One normal one, and a boopy-trapped floor as an amusing antag option

**Comment by FudgePucker** [comment]
Maybe to please the people wanting fatties and vehicles to break glass floors, maybe have a version that is made out of normal glass instead of ref glass that has the old health and can be broken by fatties and vehicles.

**Comment by SonixApache** [comment]
t-the changelog

**Pull request merged**
