### PR TITLE
Adds a spawner that spawns all monkey subtypes

### PR DESCRIPTION
**Pull request by Kharkov72**
Coming to a deff maint near you (and maybe geneticist pens) eventually
Just an idea I've had rattling around my head for a while, I'll map it later when I make sure it won't turn off gliding.
Untitled

:cl:
 * rscadd: Monkey spawners are ready to be used by m*ppers

### CODE REVIEW

**Comment by Durgen** [comment]
vox chickens aren't a subtype of monkey?

**Comment by Kharkov72** [comment]
`/mob/living/carbon/monkey/vox`
huh, could have sworn they were a snowflaked subtype of chicken
I'll add them in

**Comment by Durgen** [comment]
they'll die without a pure NO2 atmosphere, so maybe don't add them. I was just curious.

**Comment by Kharkov72** [comment]
Also a good point that I totally forgot about with the vox animals
You've set me up, and now I must play the part of the fool

**Comment by Durgen** [comment]
gotta keep you c*ders on your toes

**Pull request merged**
