### PR TITLE
Adds Cuban Pete bombs as a rare prize from non-emagged arcade machines

### PR DESCRIPTION
**Pull request by 9600bauds**
There's been a few complaints about how emags have too many unique features, emags already do too many things, etc. so I thought I'd help this problem a little by adding alternate ways to get emag-exclusive items.
This makes it so that a patient antag can still get infinite bombs from arcade machines without HAVING to buy the emag, as well as be a little less suspicious. I think more bombs will help bring more action to the round.
This also technically gives bombs to non-antags but I'm not concerned with that because they can't use them anyways since it's against the rules, so I don't think anyone will really think too much of it when they get one so no-one will use them of course :^).

Also, the toy katana was defined twice

### CODE REVIEW

**Comment by ghost** [comment]
Looks fine to me

**Comment by ghost** [comment]
Does it make cute sounds?

**Comment by ihadtoregisterforthis** [comment]
> they can't use them anyways since it's against the rules

Extended happens. Extreme validing happens. Accidents happen. "Accidents" happen. Playerage0 griff happens. Bombing a blob happens. Snowballing happens.

**Comment by Exxion** [comment]
> [Controversial]

I don't see any controversy here. Not yet, at least

**Comment by Shadowmech88** [comment]
What's the exact % chance?

**Comment by 9600bauds** [comment]
One in thirty-something

**Comment by Kurfursten** [comment]
I'm not sure I like this just strictly because a newbie could be playing arcade in the bar and get the prize, have no idea what it does / think it's a toy like the rest, and blow up the main hallway (and himself) all without moving from the arcade cabinet.

Maybe put it behind a hacking minigame like the syndie juke.

**Comment by 9600bauds** [comment]
Requesting "IT'S JUST A PRANK BRO" tag

**Comment by WeinerMaster69** [comment]
I hope you're already for the immediate regret at this getting through. I know I am.

**Comment by 9600bauds** [comment]
I'm already getting my laugh's worth out of it

I can take that to the bank

**Comment by ghost** [comment]
> Controversial

This just keeps getting better.

**Comment by clusterfack** [comment]
So the answer to emags being too powerful is to have arcades have a 1 in 30 chance to give bombs? I don't really follow or agree with the logic there.

**Comment by clusterfack** [comment]
I checked the code, it's a million times worse than advertised

**Comment by Shadowmech88** [comment]
@clusterfack I believe the goal is to make emags less powerful by adding alternative ways to obtain previously emag-specific functions, rather than simply removing that functionality from the emag.
It's similar in concept to making the juke hackable with regular tools, thereby removing the necessity for an emag if you wanted a syndie juke.

**Comment by Kurfursten** [comment]
> That code

I don't know why I didn't just read it the first time

@Shadowmech88 Probably not convincing to clusterfack, he was always against that. I had to promise to make a difficult hacking puzzle so it wouldn't get hacked every shift. The upside is I think it turned out well, and you can un-syndie a juke. I was proud to do so last week on metaclub for the bartender whose juke got emagged.

**Comment by 9600bauds** [comment]
`world << "<span class=='big bold center'> :^) </span>"`

**Comment by ihadtoregisterforthis** [comment]
I read the code some hours ago and since then I've been thinking of a proper reaction to this.
ahmed

Does it need to be a transfer bomb?

**Comment by 9600bauds** [comment]
C4 wouldn't do it justice

**Comment by Exxion** [comment]
I love it. Merge now pls

**Pull request merged**
