### PR TITLE
Make some coins lucky.

### PR DESCRIPTION
**Pull request by twirling-jesters**
## What this does
Causes all coins to have a 0.2% chance to be lucky (their luckiness factor is dependent on their material-- lucky iron coins will only have 5 luckiness, but lucky diamond coins will have 500. Lucky Bananium coins will have 5000.)

Lets players know when something's up, but has an 80% false positive rate, so the only way to determine if it's truly lucky is to use it in luck-based activities.

## Why it's good
Makes coins a little more interesting, gives a little more incentive to mint coins beyond vending machine use.

## Changelog

:cl:
 * rscadd: Added lucky coins.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can I get a proper list of all coin luck values?

**Comment by twirling-jesters** [comment]
> Can I get a proper list of all coin luck values?

In the code itself, or just here as a comment for reference?

Iron: 5
Plasma: 20
Uranium: 100
Silver: 150
Gold: 200
Diamond: 500
Bananium: 5,000
Adamantine/Mithril: 500,000

**Comment by Eneocho** [comment]
For reference, yeah. Useful to update the luck page.

**Comment by pedr69** [comment]
i don't see where the 80% false positive is supposed to come from
unless coins have a non-0 base luckiness somehow i'm not seeing

**Comment by twirling-jesters** [comment]
> i don't see where the 80% false positive is supposed to come from unless coins have a non-0 base luckiness somehow i'm not seeing

They do, yeah. Coins have a base luckiness of `null`, which is why I included this conditional:

https://github.com/vgstation-coders/vgstation13/blob/73b6ba766f5155b2ca8cd46caa22cd769565c65b/code/modules/mining/ores_coins.dm#L549-L550

**Comment by pedr69** [comment]
oh right, ESL brain forgot the difference between null and 0 for a sec

**Comment by Dacendeth** [comment]
Great, first we had to deal with botanists making 5000 clovers lagging the game to cheat at slots now we'll have to deal with miners making thousands of coins to cheat at slots.

**Comment by calzilla1** [comment]
:-1: all stealth xenoarch buffs

**Comment by Eneocho** [comment]
I'd make lucky coins sparkle a bit or something, so people can notice and steal them.

**Comment by twirling-jesters** [comment]
Incorporated @Eneocho's suggestion and added a little sparkle overlay to the coins that are potentially lucky. Here's what it looks like ingame:
dreamseeker_2023-01-04_21-34-56

**Comment by xeroxemnas** [comment]
Can you make coins out of phazon? I forgot

**Comment by Eneocho** [comment]
> Can you make coins out of phazon? I forgot

You can, and they're random, they can be worth anywhere from 1 to 1000, so they can be the luckiest or most average coin. Also randomized siemenns coefficient for railgun calculations.

**Comment by Kurfursten** [comment]
I can foresee 500,000 being terminally stupid but on the other hand most people will forget about this feature fast

**Pull request merged**
