### PR TITLE
Remove Bagel

### PR DESCRIPTION
**Pull request by Kurfursten**
At this point Bagel is getting really out of date with changed objects. It's not being maintained.

If the Lowfat Bagel project ever comes to fruition - this isn't a 'strike' against that or anything. But this old version with the broken stuff should go so Travis doesn't check it.

### CODE REVIEW

**Comment by Kurfursten** [comment]
It's not a compile fail, it's failing travis because travis checks for bagel

**Comment by Zth--** [comment]
but bagel doesn't compile

**Comment by Zth--** [comment]
I disagree with removing it from the repo tho. I think removing it from travis is enough

**Comment by Kurfursten** [comment]
Both of those statements are fair

**Comment by N3X15** [comment]
I agree, remove from Travis and map rotation only, keep it in the repo if someone wants to fix it later on.

**Comment by SonixApache** [comment]
someone could easily just navigate to this PR and download the last up-to-date copy of the map, just like the other 10 maps Damian removed during cleanups.

**Comment by Kurfursten** [comment]
Zth took this off travis so it should not be an issue in the future, HOWEVER I still think we can just remove bagel for file cleanup, basically what Sonix said

**Comment by Zth--** [comment]
What if we move old/unmaintained maps to `maps/archived` and compress them? I just gzipped bagel and it's about 300kb. This way we preserve the work done so future souls can (easily) pick them up for restoration

>someone could easily just navigate to this PR and download the last up-to-date copy of the map, just like the other 10 maps Damian removed during cleanups.

That's cumbersome and requires previous knowledge about their existence

**Comment by Kurfursten** [comment]
Compressing them and moving them to a subfolder is a good idea.

While we're on the subject, related, can anyone name one good reason to uninclude the area files for specific maps? It just makes them unclear how to open for neophyte mappers and frankly sometimes we might want more hallway areas defined for maps.

**Comment by Exxion** [comment]
Not a good reason, no. It marginally improves compile time and shrinks our ridiculous object tree, but if we cared about either of those things there would be better ways to improve both

**Comment by SonixApache** [comment]
?

**Comment by Kurfursten** [comment]
I haven't had much time for space anymore with my new semester started up

How do I reach these kids, etc etc

**Comment by SonixApache** [comment]
😔

**Pull request closed without merging**
