### PR TITLE
Blinder is no longer a screenwide "I win" button against silicons

### PR DESCRIPTION
**Pull request by Shaska-**
This thing is far too powerful for an improvised weapon, especially considering how easy it is to obtain.

:cl:
 * tweak: Blinder flash radius reduced from 7 to 1. HE bulb has a range of 2.

### CODE REVIEW

**Comment by Tehsapper** [comment]
1 range seems to be exceptionally shitty, it's flash-tier.

**Comment by Kurfursten** [comment]
Range from 7 to 1?

If this passes I am personally making borgs slip on water, slippery plants, and shoveable. All easy to obtain stuns.

**Comment by boy2mantwicethefam** [comment]
Nah, just rope the borgs

**Comment by Shaska-** [comment]
It should never have been more than 1 range in the first place, for such an easily obtainable weapon.
Also, considering it's an AoE stun, the HE upgrade still makes it a very good weapon against borgs.

**Comment by arc166** [comment]
Should be flash 1 range, this 2, 3 with better light. Not that different to getting flashed by a vamp. 
7 range is ridiculous and ''equal to flash'' is pointless, if you want that, just grab a flash.

**Comment by Shaska-** [comment]
Problem is, if the range is increased to above 1, any module other than sec won't be able to fight back against anyone using this weapon, meaning it goes straight back to being an "I win" button.
It gets even worse if it's paired with an actual flash. The AoE can stun several borgs at once, and the flash can then be used to keep them stunned till they've been beaten to death. All of this without them ever being able to fight back in any way.

**Comment by arc166** [comment]
> 
> 
> Problem is, if the range is increased to above 1, any module other than sec won't be able to fight back against anyone using this weapon, meaning it goes straight back to being an "I win" button.
> It gets even worse if it's paired with an actual flash. The AoE can stun several borgs at once, and the flash can then be used to keep them stunned till they've been beaten to death. All of this without them ever being able to fight back in any way.

On top of that, nothing stops you from just carrying more lightbubls or cells. Switching them is instant. The worst part of it is when someone with sci access does it, since the stun is easily long enough to remove cell, effectively removing them from the round without help while also removing their ability to ask for help from most people, with 0 counter play.  
The blinder should probably not be instant if its going to be > the range of most borgs. But if its delayed, its just a ghetto flashbang that only targets borgs and has less range.

**Comment by Blithering** [comment]
Shocked doors also stun for long enough to take someone out of the round permanently.

**Comment by Shaska-** [comment]
As do tasers, normal flashes, stun batons, etc.
The difference is, you can guard yourself against those, or fight back against them.
Shocked doors are countered by insulated gloves. Tasers can miss, be dodged or reflected. In melee against flashes and batons, reaction time and accuracy decides the winner.
Blinders are different. You never get to fight against them if the range is above 1. You can't protect yourself from them as a borg, and the only way to fight against one is to get into melee range.
But you can't get into melee range, because the flasher outranges you. 
You can't fight it, you can't protect yourself against it, you're just fucked.
This isn't fun for anyone, and there's no way it can be considered balanced.

**Comment by Tehsapper** [comment]
still 1 range is bad: because of our fast&furious movement speed the chance of missing it is close to 100%. you could argue that flashes are also "1 range" because they're melee, however you have to actually mouseclick the target, and you can't waste the flash charge in any way, compared to activating the flasher prematurely and effectively wasting it.
what about making the stun duration scale with distance?

**Comment by Blithering** [comment]
The argument would be more convincing if borgs didn't have so many immunities and instant fuck-everything-on-screen strategies themselves. Sure a few niche tools like the blinder shut them down hard, but all the same a mediborg can just walk into a crowd, mix two beakers and be the only survivor.

**Comment by SonixApache** [comment]
make it equal to flashbangs

**Comment by Shaska-** [comment]
I still think having a weapon that's not even theoretically possible to defend yourself against is a bad idea, so, I'm thinking how about we change how it works entirely instead?
Best idea I can come up with right now, would be changing it into a sort of anti-borg ghetto flashbang, that can be modified with a HE bulb to make it strong enough to work on humans.

**Comment by arc166** [comment]
> 
> 
> The argument would be more convincing if borgs didn't have so many immunities and instant fuck-everything-on-screen strategies themselves. Sure a few niche tools like the blinder shut them down hard, but all the same a mediborg can just walk into a crowd, mix two beakers and be the only survivor.

That's just medborg which can do that, and technically, greys can do the same thing and also be immune to shocks, zas, flashes. Humanoid races can become immune or incredibly resistant to basically everything (even polyacid can just be walked out of if you have internals and react fast enough; I've doen so). Borgs defensive abilities are nearly entirely static. If an option always wins against borg it ALWAYS wins against borg because they can't just go wear sunglasses/welding goggles. So balancing them and balancing humanoids shouldn't be looked at the same way.

**Comment by Ratvar** [comment]
Or their balancing should be looked at the same way if the only alternative to human style adaptive defense is being immune to almost everything+having instakill weapons, which is shit.

**Comment by arc166** [comment]
> 
> 
> Or their balancing should be looked at the same way if the only alternative to human style adaptive defense is being immune to almost everything+having instakill weapons, which is shit.

No one said that. 
If someone tries to shoot you with chloral, for example, as a human, you can dodge it and shoot them back. If they flash you can wear glasses. If they zas or slip and its not space lube magboots work. Humanoids can, if they want, counter nearly everything borgs and each other can do with some prep.

If a borg gets rushed with a 2-3 tile 0 delay stun and its not a medborg, janiborg (who can both use spacelube, water and med can use gas) or sec, all they can do is run away. That's it. That's the be-all-end-all strategy. Because the moment they try to fight back, they get stunned from a range they can't contend with, ever, at all, short of getting a module change to one of the 3 who can deal with it.

Its not comparable at all.

**Comment by SonixApache** [comment]
I don't see an issue with borgs getting turbofucked from range.

**Comment by Shaska-** [comment]
It's not an issue of being turbofucked from range, but an issue of bing turbofucked without any counter.
Check the previous posts.

**Comment by SonixApache** [comment]
I don't see an issue with borgs getting turbofucked from range.

**Comment by Caboozles** [comment]
If you’re concerned about spam then add a delay to changing the bulb. As is though, they should absolutely get turbofucked from range. They have enough immunities that maybe they can stand to actually show some care next time borgs go rogue. If one guy flashes 3 of them he should absolutely be rewarded for that.

**Comment by Shaska-** [comment]
The problem isn't the ability to spam it, or that it's a ranged stun.
The problem is that it's a ranged AoE stun with no counter.
I don't see why some guy with 3 borgs in view should be rewarded for... what exactly? Clicking on the item he's holding? He's not exactly doing anything worthy of a "reward".
If borg immunities are a problem, they should be addressed in a different PR. 
With the changes in this PR, the blinder still remains a potent weapon against borgs, it's just not a free win anymore.

**Comment by Shaska-** [comment]
Well, it doesn't look like this is a solution worth pursuing.
For borgs, anything above 1 range makes it impossible to deal with, but for those using it 1 range is just not enough.
I'm gonna look into redesigning it instead, to be a more powerful weapon than what this PR suggests, but without it being an uncounterable "I Win" button.
I'm open to suggestions if anyone has any ideas for the redesign.

**Comment by Shadowmech88** [comment]
For the record, when it was designed 3 years ago, the blinder was intended to be a makeshift countermeasure to rogue borgs that was easy enough for regular crewmembers to obtain, with the primary goal of allowing crewmembers to merely escape/survive against borgs. At the time, unless you were Security, there was absolutely nothing you could do when faced with a silicon opponent, not even to escape from them or slow them down. Replacing the cell and bulb was, at the time, cumbersome enough that I doubted it would ever be used outside of a one-shot "smoke bomb" that would allow a crewmember to escape from a pursuing borg and hide.

I don't know how silicon combat or the functionality of cameras/blinders have been changed since then, but that was the original intent when I made the item. I never intended it to be used in open combat as an alternative to things like ion rifles.
From the original PR:
>Blinder: A device which, when triggered, blinds everyone onscreen as well as stunning borgs. It does not stun carbons. After every use the lightbulb must be replaced. It is highly likely its power cell will need to be replaced as well since it uses 10000 charge per use. Because of this, it can’t be reliably used to stunlock borgs, and because it blinds the user, attempting to do anything harmful to the borg during the stunlock would be challenging. This weapon was intended to be a makeshift defense against subverted/malfunctioning borgs that would allow the user to escape, since it stuns borgs but not carbons.

**Comment by SonixApache** [comment]
just turn it into a flashbang but with maybe 1 less tile range
or make it *always* flash the user, even through flash protection

**Comment by Shaska-** [comment]
Currently, it's probably the best weapon you can get against silicons, unless you need the off-screen stuns that the ion rifle provides.
The flashbang idea could work, but I'm thinking of keeping it working the way it is, but changing the stun to a slowdown. 
I think that would bring it very close to what it was originally designed to do.

**Comment by SonixApache** [comment]
\>what it was originally designed to do.
What would that be? I thought it was supposed to be a ghetto AoE flash.

Tasers already slowdown borgs somewhat, for the record.

**Comment by Shaska-** [comment]
>This weapon was intended to be a makeshift defense against subverted/malfunctioning borgs that would allow the user to escape, since it stuns borgs but not carbons.

>I never intended it to be used in open combat as an alternative to things like ion rifles.

It was meant to be a makeshift defensive weapon that allows you to escape rogue borgs.

**Comment by SonixApache** [comment]
Ah, I see.

**Comment by Blithering** [comment]
Maybe have it disorient them instead, randomising their movement

**Comment by Shaska-** [comment]
That could work. One potential problem I see with it though, is that it sort of randomizes you chance to escape. The random movement could send it away from you, increasing your chances of escaping it, or right at you,
Of course that might make it more fun for both parties as well, and it makes a lot more sense from an RP perspective than a slowdown does. I'll see if I can figure out how to do it.

**Comment by Blithering** [comment]
The idea would be to make it impossible to reliably give chase while disorientated, but random movement makes it hard to be caught yourself.

**Comment by Shaska-** [comment]
Yeah, good point. I'm not a 100% sure I can figure out how to code it, but it does sound like the best solution, so I'll try to make random movement work.

**Comment by Shadowmech88** [comment]
Perhaps it should temporarily disable the borg's modules as well. A security borg with randomized movement could still dump a taser into you.

**Comment by Blithering** [comment]
True.

**Comment by Shaska-** [comment]
If we disable modules though, we're almost just back to where we started.
The borg would be unable to fight back again, making it useful as an offensive weapon.
The random movement would be a decent defense, but borg movement is slower than humans, so it's much easier to hit than, for example, a drunk human running around randomly. I think it's a step too far.

**Comment by Blithering** [comment]
If it only affected movement, it becomes hugely less effective as a defensive tool, as it does nothing to stop a secborg tasing you until the effect wears off, or the aforementioned medibot screenwide kill.

**Comment by SonixApache** [comment]
If you just module-lock them, the borg can at least try to run away, unlike when stunned.

**Comment by Shadowmech88** [comment]
What if the borg doesn't run away, and instead gives chase? Module-lock only would be a fine compromise for borgs vs equipped crew, but it wouldn't be a great asset to civilian crew vs borgs. The humans only have so many cameras/cells/bulbs and the borg has all-access, it can simply keep pursuing them until they exhaust their countermeasure.

What if it just blinds the borg without stunning it, like it does to humans without eye protection, but the borg is blinded longer? It doesn't need vision to make evasive maneuvers and run around the room while it waits for the blindness to wear off, but it won't be able to attack or pursue crewmembers for the duration.
Or, if we want to get more creative, what about giving the borg a unique vision filter that causes 75%-80% of the tiles on its screen to have static overlaid on them, and they shift around every tick? The borg would still be able to orient itself and move through the station using the tiles it can still see, so it could run away instead of just running around, but its combat and chase ability would be severely hampered.

**Comment by SonixApache** [comment]
If it gives chase that's fine, worst it can do at that point is push you around.
If it can't stunbaton / zappyhand / taser / choral you, you can just toolbox it to death while you reload your blinder.

**Comment by Shadowmech88** [comment]
>If it gives chase that's fine, worst it can do at that point is push you around.

Until its modules come back online.
How many bulbs/cells would it take to keep a silicon disabled for the time it would take to toolbox it to death? How many more would be needed to cover the seconds lost while reloading/attempting to toolbox the borg as it evades you while still not actually running away or allowing you to escape?
I feel like it wouldn't be a very reliable method of survival at that point. Better than nothing, sure, but I feel like players would rather have a good chance of escape rather than a mediocre chance in combat if they're not already kitted out to fight the borgs.

**Comment by Shaska-** [comment]
Keep in mind, this is still a screenwide AoE, so we can't make it too powerful, or we'd have to weaken the range or remove the AoE effect to compensate. 
I think just the slowdown or the daze is fine. It does what it needs to do, it gives people a chance to run away from the borg. It also already does fuck with the borgs vision for those crucial first few seconds already.
A module lock would be a bad idea. It means it's no longer just a defensive weapon, but a great offensive weapon as well. You have to keep in mind that a borg can't run away, in the same way humans can, since it's slower than everyone else.
And if you start pairing a module lock effect with other weapons, it suddenly becomes a very powerful opening attack, giving you plenty of time to flash or wail away at some one who can't fight back or run away.
That's too much for an easily obtained screenwide AoE.

**Comment by Tokanova** [comment]
fuck silicons

**Pull request closed without merging**
