### PR TITLE
FEATURE FREEZE -- NO NEW FEATURES ALLOWED

### PR DESCRIPTION
**Pull request by N3X15**
```
<probe1> n3x15, hey guess what it's feature freeze time and we're not stopping until we're under 650, i don't care about your snowflake omgsocool feature
<probe1> pomf wants us to cut some bugs outo
```

### CODE REVIEW

**Comment by Kurfursten** [comment]
We have ***ten pages*** of Feature Requests, dating back two years and numbering 235 issues. I have a suggestion to this end: create a poll in which players can vote for as many items as they wish, and anything which does not receive 20% of votes (i.e.: less than 1 in 5 players are interested in seeing it coded) gets closed. This is a serious issue: feature requests constitute 31% of open issues.

**Comment by clusterfack** [comment]
Would be neat if we had a way for people to vote on feature requests *like gitlab did*

**Comment by Probe1** [comment]
but no one participated in it.  I'll set something up with google docs

**Comment by Kurfursten** [comment]
@Probe1 Is there any good way to perform voting/tabulation of the opinions of discrete users on Gdocs?

**Comment by Probe1** [comment]
Not as good as the in game polls pomf can set up but honestly we'd have to cut it down to like 5 at a time, no ones going to fill out a questionnaire.  

That's the heart of the problem.  We have 250 feature requests and probably 200 of them were only requested by one person who isn't willing to code it themselves.  

The feature requests the server wants as a whole are pretty well known and don't have issues for the most part (revamp genetics/virology/xenoarch, buff xenos, et cetera)

**Comment by Kurfursten** [comment]
One more practical solution may be to simply close all 235 and say "if you still want it/think it might happen, reopen the request". I doubt more than 20% (50) would resurface.

**Comment by FudgePucker** [comment]
The problem with having a vote based system is that many of those feature requests have gotten really dusty, people will be less likely to vote for feature requests that are over a month old.

**Comment by Kurfursten** [comment]
Does that matter? If there is no community interest in it, then why keep it open?

If it can't sustain interest over a long time, it hasn't demonstrably resonated with players.

**Comment by FudgePucker** [comment]
Still a ton of the issues are really really stale. Heres one to balance goof chem: https://github.com/d3athrow/vgstation13/issues/3053

Raise your hands if you think that we should actually keep any issues pertaining to something that will never be included in the game.

Also a lot of the issues on page 30 can be tested really quickly to see if they still happen.

I also went though all 30 pages of issues even though it is 1 AM ~~and I have a test tomorrow kill me please I want to die~~, 5 issues on the sme chamber leaking on box and meta, (fun fact: The sme chamber on deff might look like shit, but it has never ever leaked ~~fuck~~ thank you duny) so you could get 5 issues knocked out by just fixing it.

**Comment by mrpain666** [comment]
Finally. It was getting really out of hand for a while.

**Comment by FudgePucker** [comment]
Going though issues.

Is this issue relevent still (after economy changes) or can it be closed? #2942
I can't even check this one because its not on github, is it relevent enough to be open or has it been fixed yet? #2474
I think I remember this one being fixed.  #3903
Wasn't this one fixed, or was it just things in containers not lockers? #3820
Not a relevent issue. #4495
Is this still broken or was it fixed? #4984
Is this still broken or was it fixed? #5254

**Comment by dylanstrategie** [comment]
#2394 isn't going to happen, we're not removing Asimov in a lifetime
#2443 might not be an issue anymore. Needs checking
#2847 can be closed. Infrared emitters have been removed
#3455 and #3498 should no longer be an issue with the locked_to refactor

**Comment by mrpain666** [comment]
Consider closing all feature requests you see and telling them to repost them when the freeze is over.

**Comment by PJB3005** [comment]
@mrpain666 that's just cheating.

**Comment by Probe1** [comment]
It's not a bad idea at all.  I've been trying to figure out how to get the playerbase to vote on feature requests they want fulfilled.

How are you going to make a poll with 200 options?  No one will participate past the 3rd idea.

If your feature request hasn't been filled in 3 months just can it.

**Comment by Kurfursten** [comment]
I suggested it earlier, I stand by it. Close 'em all - or like Probe said, close all past a certain cutoff. If they REALLY want it, they can make a new request.

**Comment by Kurfursten** [comment]
With the rate that issues increase over time, the feature freeze has only been successful thus far in reducing issue count by 10. We need to take bold action and do something about the feature requests.

**Comment by mrpain666** [comment]
Man up and close them. Its making tracking the progress of the freeze difficult and the act of them creating the feature request right now is actually DELAYING the possibility of their idea being implemented.

**Comment by PJB3005** [comment]
## STOP SAYING FEATURE REQUESTS SHOULD BE CLOSED.

Add `-label:"Feature Request"` to the search and all feature requests are excluded.

## CLOSING FEATURE REQUESTS IS CHEATING.

**Comment by Probe1** [comment]
not really.  there are hundreds of issues that are out of date or are wishes and we're not make a dream foundation.  want less issues, close all those damn issues made by inactive players hoping someone else would code their idea for them.

**Comment by PJB3005** [comment]
@Probe1 except there's no fucking reason to close them, yes they might be fucking retarded but whatever.

**Comment by Kurfursten** [comment]
I would agree if feature requests weren't a third of our issues. It creates bloat and misperception, and many of the FRs are either:
* Filled but not closed
* Not relevant anymore
* Balance changes that will never happen

**Comment by PJB3005** [comment]
@Kurfursten if you don't want to see them, then hide them with the search thing I just mentioned here.

**Comment by Probe1** [comment]
We're currently in a feature freeze because of issues.  We have hundreds of issues that are outdated or feature requests that *will not* be filled.  There's a lot of reasons to close them.

**Comment by PJB3005** [comment]
@Probe1 as I said, those feature requests aren't causing the freeze, at all.

Just fucking count and EXCLUDE the feature requests.

**Comment by clusterfack** [comment]
If it'll satisfy you fags trying to cheat the system, the freeze is going to last until we are under 100 issues tagged as bug. /official

**Comment by PJB3005** [comment]
Told you cheating the system isn't gonna fucking work.

**Comment by Intigracy** [comment]
Should still close them anyway.

**Comment by PJB3005** [comment]
\>All these people who think they can cheat out of le feature freeze.

**Comment by Intigracy** [comment]
>If it'll satisfy you fags trying to cheat the system, the freeze is going to last until we are under 100 issues tagged as bug. /official

I'm not trying to cheat it my honest opinion is you should close them anyway.

**Comment by Kurfursten** [comment]
Yeah, I also think they should be closed after a certain age regardless of its impact on the Freeze

**Comment by mrpain666** [comment]
Count how many feature requests you close and then raise the standard by that much. Its simple book keeping.

**Comment by FudgePucker** [comment]
>we went from 150 bug issues to 155 bug issues

AAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
THIS FREEZE IS NEVER GOING TO END

**Comment by PJB3005** [comment]
@FudgePucker when it started it was at 200 bug issues.

**Comment by clusterfack** [comment]
Freeze over

**Comment by Probe1** [comment]
# TIME FOR DANCE

**Comment by Kurfursten** [comment]
trophy-clipart-7cagzxdca
Bug Fix Sprint trophy for Clusterfack

**Pull request merged**
