### PR TITLE
Adds various chips

### LINKED ISSUE #34610: some of the snaxi treadmills don't work
(WEB REPORT BY: poales REMOTE: 206.221.180.138:7777)
# Revision
beef675b67b304c13828255def6318a93a40546c

# Description
the ones where you have to face to the right don't seem to work, south of hydroponics

### PR DESCRIPTION
**Pull request by SonixApache**
I wanted to put something on the snaxi counter that isn't just donuts, so I made all this.
chips

+ added spicy chips. They're chips, but spicy. 
+ added nova chips, which are even hotter. 
+ added Dangles, our favorite vendor's take on the a certain brand of potato chip.
+ added hotsauce packets. ~~We should get the condimaster to make these out of any condiment.~~

+ added some more words to various trash items to differentiate them (danitos bag, popcorn box, etc) because i was in the file
+ removed some double definitions from vendingpacks.dm since i was in the file while i didn't need to be 

:cl: 
- rscadd: Added hot chips, made from 2 salt, a potato and a chili
- rscadd: Added nova chips, made from 2 salt, a potato and 2 nova flour
- imageadd: Chips sprites by ArthurDentist / Sage of Light / me
- rscadd: Added Dangles, a new line of crispy chips available from your local Discount Dan machines!
- imageadd: Dangles sprites by Sage of Light

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
can we call them hot chips instead of spicy chips

**Comment by Eneocho** [comment]
I'd make the spicy packet green instead of red, cause you can easily mistake it for ketchup.

**Comment by SalmonIsTasty** [comment]
> I'd make the spicy packet green instead of red, cause you can easily mistake it for ketchup.

Thats the point

**Comment by SonixApache** [comment]
@PrimeDSS13 done

**Comment by ShiftyRail** [comment]
They're not chips, they're crisps. Downvoted

**Comment by Cartlord** [comment]
> They're not chips, they're crisps. Downvoted

why are you british

**Pull request merged**
