### PR TITLE
SAC: Lockbox alerts

### PR DESCRIPTION
**Pull request by SonixApache**
### What
Adds SAC alerts when lockboxes are broken into.
This only happens if the lockbox is destroyed, be it through bullets or explosions (or mech drills).
EMPs and emagging isn't affected.
The alert won't be announced, and the SAC won't show that there's a new alert if this is the only newest alert, so it's not a 'priority'.

### Why
Scientists always having pocket guns has been a long-standing issue with constant discussion, and there's never been a pleasing answer to it.
I think this change allows for antag and non-antag escalation without 100% locking out people's abilities to gain useful stuff from science. And that's a good thing! People should be able to do 'bad'things without having to be an antag or having sec up their ass.  But if there's sec, and they're paying attention, and the scientists aren't, someone might notice, and that might be interesting for a change.
I also believe that lockboxes are completely pointless if they can very easily be broken open without anyone ever noticing. They don't leave behind any evidence apart from their contents. Surely they would have *some* sort of safety feature, right?

🆑 
 - experiment: Lockboxes now send a security alert when broken with brute force. This doesn't apply to EMPs or emagging.

### CODE REVIEW

**Comment by BomberBro** [comment]
Didn't we try this already?

**Comment by SonixApache** [comment]
yeah, but my specific brand of lockbox alarms wasn't tried yet

**Comment by JevilUndertale** [comment]
It's funny since this will probably only lead to sec arresting non-antags, given that antags will most likely use emags.

**Comment by SonixApache** [comment]
I don't see how that'd be a bad thing, necessarily.

**Comment by PrimeDSS13** [comment]
I don't like this PR but yeah that's not a bad thing, security shouldn't just be the valid killers. Non-antag crime is still crime.

**Comment by west3436** [comment]
wish I could give it two thumbs down for posting an ad in the middle of the PR

**Comment by Accipitermaris** [comment]
I think automated [valid] alarms in general discourage interaction & conversation and reward silently camping in the brig. In order for the good to outweigh the bad, it’s gotta reward social activity more than it discourages it

**Comment by SonixApache** [comment]
I don't think it's so much a [valid] alarm as a [something is going on here, go investigate] alarm. 
People that break into lockboxes aren't necessarily valid.

**Comment by Kharkov72** [comment]
not this shit again

**Comment by SonixApache** [comment]
is there some sort of timeline shift going on

there's been lockbox drama (including the creation of the lockbox) but never anything like this

**Comment by kilozombie** [comment]
I remember the "guns are damaged when their lockbox is broken" being a cataclysmic event that left everyone shaken permanently

**Comment by bathosbathtime** [comment]
Lock boxes should have dye boxes that stain your hands/the item blue if you break them open so security can investigate lock box theft without having a computer tell them when a lock box is broken into.

**Comment by yclatious** [comment]
FUCK OFF ALREADY

**Comment by dunsel-hordon** [comment]
i like the dye thing. Just have it apply the dye to whoever picks up the item immediately after its broken out the box

**Comment by tuypo1** [comment]
Same as the ai link PR, antags shouldn't be forced into only doing things with emags, although this is a little better since at least you can still emp

I would be open to putting this on the lawbringer though

**Comment by Kharkov72** [comment]
An alternative brought up in the coding discord:
`Why not just add the alert when the gun is printed off. Can make the alert not trigger if their ID has certain permissions. Not a big AAHH alert either, just a separate list that quietly creates evidence`
I like it better, it makes this less a COLLECT BRIG VALIDS HE HAS AN ILLEGAL GUN and more a "Why the fuck are they printing guns someone go investigate"

**Comment by BurntDevil** [comment]
The only acceptable way this works is if it has a limited detection range. Meaning, if they get broken into on the roid, it shouldnt detect it, or way off in the caves of Roid's roid field.

**Comment by SonixApache** [comment]
@Kharkov72 I'm not sure if adding (low-level) alerts to guns specifcally would be good. Adding a 'lockboxes' category that just lists off all lockboxes printed might be an idea?

@BurntDevil if you crack a lockbox on the roid or outside the station or in maint somewhere, the alert is worthless anyway - there's not going to be any way to trace it back to you, it just makes security aware that *a* lockbox has been cracked.

Had an idea after some discussion - lockbox alerts no longer trigger the "spoken" message from the SAC, and the SAC will not display a [!] new alerts indicator from lockbox warnings.
The idea is that lockboxes being broken into isn't necessarily a bad thing, but something that may need looking into at some point.

I hope I can get some actual feedback and not just downboating because it's Yet Another Lockbox PR.

**Comment by ghost** [comment]
We have a tool to tell if someone is making guns in science and accessing them illegally. It's called a security camera.

**Comment by SonixApache** [comment]
Your scum sense tingles, or maybe you're just really bored. You take a look at R&D through the security cameras. Here's what you see at any given time:
image
Here's what you don't see until you either break SOP and search them 4noraisins  or get shot at:
dreamseeker_2020-06-06_16-16-23

I suppose this is fine. Thinking about it, this PR wouldn't change much due to the EMP vulnerability anyway.

**Comment by juanototo2** [comment]
>upload board in baggie
>normal sized items in baggie
>no sprayers
>no shotguns
>assault rifle

Please update your image, my friend. You can get better things.

**Comment by GreatBigFailure** [comment]
This is a good addition. 

It doesn't remove any content or even limit it. In fact it adds another tool to sec, and for once that tool isn't a weapon or way of restraining someone.
All this does is cut out the guess work and unease when dealing with potentially armed criminals. It reduces the need for tasing before questioning and random searches. 
People complain about sec constantly but then get upset when they're given the ability to do their job without affecting other people's fun. If you're using the weapon or whatever for mining, vault hunting, or some gimmick then you're already long gone after they've seen the SPS notice and it won't effect you. If you're arming up to murderbone the whole station then they at least have reasonable grounds to search science and thus remove murderbone.

This will almost exclusively lead to more RP and fun sec questionings rather than tase cuff search "There's his emag", bang bang dead. 

I also remind you that no one checks the crew monitoring computer despite that being life and death rather than the RD having a super soaker. This rewards players who do their job, use their resources, and investigate and doesn't effect those who don't. 

>It's funny since this will probably only lead to sec arresting non-antags

Good, antags don't exist in RP. Traitors do but not designated antagonists. Sec is not there to shoot antags they're there to cut down on station crime. Antags just happen to also be criminals. 

 >An alternative brought up in the coding discord:
Why not just add the alert when the gun is printed off. Can make the alert not trigger if their ID has certain permissions. Not a big AAHH alert either, just a separate list that quietly creates evidence
I like it better, it makes this less a COLLECT BRIG VALIDS HE HAS AN ILLEGAL GUN and more a "Why the fuck are they printing guns someone go investigate"

I do however like this better though. Whichever handsome, intelligent, and charming man came up with it deserves a medal.

**Pull request closed without merging**
