### PR TITLE
Holosign Update

### LINKED ISSUE #20015: Surgery Holosign Switch
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
98ca78c6a1f8cc9f87798d1c6fd9e4ab2bbcd493

# Description

There is currently no limit on how much ghosts can poltergeist the surgery holosign.  As a result while most light switches have a 2 minute delay between poltergeists on it, the holosign has none. 

# Steps to Reproduce

Be ghost, spam holosign switch
# What you Expected

Delay like any other light switch
# What Actually Happened

No limits.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #20015

surgery
switchbiohazard
lightswitch

also added a few extra signs to box viro so people in medbay find the way to Virology more easily.
viroaccess

From now on, when placing holosign **switches** in a map, remember to set their id_data to match specific holosigns (currently there are only "surgery" and "virology").

:cl:
* imageadd: Holosign switches finally have their own sprite, allowing to easily distinguish them from light switches.
* tweak: Holosigns now emit a bit of light when activated.
* rscadd: Virology airlocks now feature holosigns as well. If you see them on, consider wearing a biosuit before coming in.
* bugfix: Added the missing light switch to snaxi's Virology.
* bugfix: Ghosts now share the same poltergeist cooldown that lets them interact with light switches with holosign switches.
* bugfix: Fixed light switches not glowing in the dark like they were meant to were they not missing a couple icons.

### CODE REVIEW

**Comment by SonixApache** [comment]
`code/game/machinery/holosign.dm:107:error: on: undefined var`

**Comment by DeityLink** [comment]
derp

**Comment by PrimeDSS13** [comment]
yes please more glowing signs

**Comment by anunknownentity03** [comment]
we need adverts now that suddenly pop up in the station halls

**Pull request merged**
