### PR TITLE
Fixes bug where deitysnow would layer inappropriately due to planes

### PR DESCRIPTION
**Pull request by ghost**
Fixes bug where deitysnow would layer inappropriately due to planes

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Plane should be `ABOVE_TURF_PLANE` instead.

**Comment by JMWTurner** [comment]
Wait I thought that thing had been reverted and forgotten like 2 days after being added in 2014

**Comment by ghost** [comment]
@JMWTurner Nope!

**Comment by PJB3005** [comment]
I did the effective equivalent for christmas so this can be closed.

**Pull request closed without merging**
