### PR TITLE
Salmonistasty addition of fartCooldown variable 

### PR DESCRIPTION
**Pull request by SalmonIsTasty**
[administration] [qol] [help] [dnm]

## What this does

Adds a variable "var/fartCooldown " to human.dm to line 6
Changes line 147 in emote.dm to " if(world.time - H.lastFart <= (H.disabilities & LACTOSE ? fartCooldown : fartCooldown  * 2)) "

## Why it's good

Lets admins to ~abuse~ bus players more. (Clown farting constantly)

## Changelog

:cl:
 * experiment: Added an experimental variable.

### CODE REVIEW

**Comment by pedr69** [comment]
https://github.com/vgstation-coders/vgstation13/blob/d02bc54a693d71e4e9d9ff457eaaf5f7dfd1e1ad/code/modules/mob/living/carbon/human/emote.dm#L82
you're gonna want to put the fartcooldown here instead
pretty sure this also lets superfart throw you through walls since you removed the checks

compile your code, bro

**Comment by west3436** [comment]
did you really need to sign the title of this

**Comment by SalmonIsTasty** [comment]
> did you really need to sign the title of this

This is my first pr, thats how git auto named it

**Comment by pedr69** [comment]
i believe he's using the github desktop app or someshit
unless he's eaten a roboburger and is slowly becoming an AI

**Comment by SalmonIsTasty** [comment]
Since I added this without prior syncing of my fork, Im gonna delet this and and make new pr with new branch

**Pull request closed without merging**
