### PR TITLE
Escape pod doors get locked on departure

### LINKED ISSUE #14428: The white shuttle airlocks can be opened midflight by bumping into them.
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
Griff too easy with plausible deniability. Should require crowbarring instead.

### PR DESCRIPTION
**Pull request by DamianX**
resolves #14428
:cl:
 * tweak: Escape pod doors will now be locked on departure.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by ghost** [comment]
absolutely not
we need to be able to throw lings and innocent people out the door

**Comment by DamianX** [comment]
Let's add the ability to open the emergency shuttle airlocks too, then?

**Comment by Exxion** [comment]
You already can, can't you?

**Comment by DamianX** [comment]
You totally can't.
Do you honestly believe you wouldn't get spaced on the shuttle way more than you already do now if you could open those?

**Comment by Lokiamis** [comment]
casuals get out

**Comment by Probe1** [comment]
Add an attackby that lets players unlock it then merge.

**Comment by Exxion** [comment]
My dude I buckle in and don't make trouble
I don't even remember the last time I got spaced on the shuttle, or even the last time someone tried to space me

**Comment by DamianX** [comment]
Nah, I don't want it to be like that.

**Comment by Durgen** [comment]
@unusualcrow https://www.youtube.com/watch?v=4MiqPQ1dVg4

**Pull request closed without merging**
