### PR TITLE
Adds Silicate Sprayer to MoMMI modules

### PR DESCRIPTION
**Pull request by JMWTurner**
I'd like to repair the station without someone stealing that sprayer I took from somewhere as soon as I drop it.

### CODE REVIEW

**Comment by Kurfursten** [comment]
More MoMMIcreep. They can already make all the windows they want with the matfab. They can even make rplasmawindows.

I'd say let @PJB3005 weigh in, since he may have consciously chosen to make it a human engineer item.

**Comment by JMWTurner** [comment]
Sure mommi can just deconstruct/reconstruct the windows, but the idea here is to gain time.

**Comment by PJB3005** [comment]
At the time I was worried about "muh MoMMI creep" and didn't want to start a balance discussion.

Now, I believe MoMMIs _should_ be nerfed, because 1 more MoMMI on the station means 1 less engineer that can actually _interact_ with the crew, thus making the round worse.

**Comment by JMWTurner** [comment]
Fair enough

**Comment by FudgePucker** [comment]
> MUH INTERACTION

FUCK
YOU

**Comment by ComicIronic** [comment]
If you hate interaction so much why don't I ban you from the repo

**Comment by FudgePucker** [comment]
You don't really get my point of being against the forced interaction do you?

Okay lets say that a MoMMI sees a busted window, he would have to vent crawl all the way across the map to get a silicate sprayer to fix it, or he can just go 'FUCK IT' and leave the shattered window sitting there.

What do you think is more likely, someone bothering to go across the map to get a tool or just going 'FUCK IT'?
Players are allergic to interacting with each other. They will only do it when it benefits them greatly both ways.

MoMMIs don't have to interact with anything. They don't have to ask the AI and hope they just don't ignore them to get into areas to fix. They don't have to beg for boards, they just go and print them. You think nerfing MoMMIs will increase the amount of engineers? Ha, bullshit, all it will do is cause there to be 0 MoMMIs and 0 Engineers.

Rounds are so short that having to deal with interacting with other players is pointless, all that work you did trying to get someone else to do something for you will be void in about an hour. The player base is composed of 90% sociopaths, who refuse to even acknowledge the existence of other people.

Of the last two out of three engineering rounds I played, one of them had me get succ'd in maint after fixing a hole that was caused by an admin pushing the rod button, then the changelings doing nothing for about an hour, the other was a round start hacked AI plasma flooding. Maybe people want to play MoMMI because dealing with other players is fucking shit when you are an engineer, those players would rather just go assistant and fuck around instead of having to play the bitch job.

If you have a project you want to do, you can play as an engineer and hope the stars align and you get a non shit cargo, science, AI, or you can go MoMMI and not have to deal with all that bullshit.

An example PJB used is the material magnet on goon, thinking that it was a good way to bring miners to the station rather than being off of it. The mining job on goon is a good example why trying to force interaction is fucking stupid.
So you push the magnet button, wait wait, look to see if you have any thing worth bothering to mine, mine if there is, otherwise push the magnet button after the cool down, wait wait, finally you get enough ore, oh wait, you can't make money because there is no one playing QM, you are out of luck, guess you just wasted those hours staring at a magnet. No one goes QM because it requires you to get other jobs to interact with you, guess what doesn't happen. Compared to our mining job you get to explore the asteroid, bring over mats to research, there is almost always a person in research because it highly benefits both of you, you get some toys, then you can mine some more for research or go hunt pokemans in the caves. The reason that mining works with our player base compared to goons is that it is very mutually beneficial for both parties to interact, one can exist with the other, but without each other they are less effective and fun. Research can still print a lot of things with out mats, mining can still go hunt pokemans without research, its just that they both benefit greatly from both parties working together.
A counter example would be cargo interactions with every other department, if your project or job depends on something out of cargo, flip a coin, if it comes up heads, be prepared to wait twenty minuets for them to process your order, if it comes up tails you are just shit out of luck. This is because cargo gets very little out of doing shit for you, they are pushing those buttons on that computer and dragging a crate to you for jack shit.

Using a carrot to encourage players to interact is better than using a stick to bash them into submission and force them to, because at the end of the day, going 'FUCK IT' is easier and less stressful than putting yourself and your time at the whims of other players.

**Comment by PJB3005** [comment]
> No one goes QM because it requires you to get other jobs to interact with you

That's 100% false and shows you have never played QM on goon before, so fuck off.

> The reason that mining works with our player base compared to goons is that it is very mutually beneficial for both parties to interact, one can exist with the other, but without each other they are less effective and fun.

Question: Are you brain damaged? My suggestion does EXACTLY that.

Can't be bothered to respond to the rest of your poorly thought out rant.

**Comment by JMWTurner** [comment]
> and shows you have never played QM on goon before

why do you keep talking about goon like it's the reference we should all be aware of? you did that in the R&D anomaly tech PR too.

**Comment by Kurfursten** [comment]
Wow that rant was barely even related to the topic at hand.

Here's what it boils down to:
- You think that interaction between departments is painful
- PJB (and I, with the Solder and Fuel Can) added items to human engineers to make up for the fact that they _have to interact with others_ - these items are to make their lives more fun/easier
- You want to give those items to the role that doesn't have to interact with people, so there's no longer a reward for putting up with that interaction/antag threat/whatever

This is what MoMMIcreep is. MoMMIs have a ton of amazingly powerful tools already, so people try to add something to make human engineers feel worthwhile. Then someone comes along and says: "That's a fun toy, I want it on MoMMI too." - not realizing the whole point was to buff human engineers to feel more relevant.

So stop complaining about a lack of a silicate sprayer when you have a mat synth, ZAS immunity, atmos immunity, pressure immunity, temperature immunity, slip immunity, rad immunity, built in blueprints, etc.

**Comment by PJB3005** [comment]
@JMWTurner he was bring up an example from goon and saying that nobody plays QM there, because they are 100% reliant on other roles.

Which is false.

As QM on goon a lot of your job is to make $$$ by buying low and selling high. There's a constantly evolving global market with values going up and down and such constantly.

**Comment by JMWTurner** [comment]
@Kurfursten Can't we just re-think what human engineers really do need over MoMMI? I'm not a fan of the "we give an item to make those guys job easier so they can put up with interaction" argument. MoMMI shouldn't been engineer-lite. Both jobs should have fields where they perform better than the other.

MoMMI are basically repair bots, so it doesn't make sense to me to give the Engineer a tool that lets them repair windows more efficiently than MoMMIs. Instead engineers should aim to provide things that the crew requests, such as new disposals, new rooms, new MULE Drop points, or stuff that we haven't coded yet ( and that could require electricity to work, thus giving us a reason to have more power in the grid )

**Comment by Kurfursten** [comment]
@JMWTurner So you think that new rooms are not in the MoMMI's kit, and they should lose the station blueprints / mat synth in exchange for the silicate sprayer? I really don't think that will be popular.

**Comment by JMWTurner** [comment]
@Kurfursten I always use the mat synth to repair. Station blueprints are necessary to be able to set up an APC as far as I know.

You don't get it. When a MoMMI builds a room it generally does it for its own entertainment since it has no incentive whatsoever to do stuff the crew wants. Unlike an engineer, who could expand rooms and offices as the crew requests it.

**Comment by Kurfursten** [comment]
It seems to me you're saying, "Humans and MoMMIs should have separate roles, HOWEVER, MoMMIs should have every tool humans have permanently attached to them, and then some, and also a boatload of immunities. If someone adds something for humans specifically so humans have nice things, MoMMIs should have that too."

I should also note that "no incentive whatsoever to do what the crew wants" is a bad thing. Why would we _want_ the objectively most powerful/best engineering role to be the one not at all incentivized to work with others/improve the round?

**Comment by JMWTurner** [comment]
Sure, let's give MoMMI accordions shall we?

Also is it me or did you entirely ignore my previous post?

**Comment by Kurfursten** [comment]
Since I quoted directly from it I don't know how you could come to that conclusion. But if you wanted me to respond to the first part: you do not need blueprints to repair an APC or build an APC in a room that had it destroyed, only to add a new one.

**Pull request closed without merging**
