### PR TITLE
adds special features for byond members

### PR DESCRIPTION
**Pull request by SonixApache**
BYOND members get a one-slot cardboard box.
In the box is either a BYOND pin accessory, balloon, or thermometer.
The pin looks horrible and gives you minor brain damage when you put it on.
The box folds into trash rather than cardboard, and the thermometer contains blood.
BYOND
(Silver medal for comparison)

🆑 
 - rscadd: BYOND members now get special privileges. Kudos to Bathos for putting up the coding bounty.

### CODE REVIEW

**Comment by bathosbathtime** [comment]
Very nice, it is about time we give byond members the thanks they deserve.

**Comment by ShiftyRail** [comment]
Why a thermometer

**Comment by ghost** [comment]
making sure they're not morbidly ill for supporting a 1999 game engine in 2019

**Comment by Kurfursten** [comment]
Presumably...

image

**Comment by DDihanov** [comment]
We pay2win now bois?

**Comment by SonixApache** [comment]
if you guys have any better ideas please do sound off
the function used returns the number of membership days someone has remaining, or -1 if they're a lifetime member
or 0 if they're not a member

**Comment by ShiftyRail** [comment]
Brain damage proportionnal to their contribution

**Comment by SonixApache** [comment]
idea being thrown around is a thermometer accessory, a different accessory like a BYOND mission patch or something would be cute as well
but that's a lot of special shit for people silly enough to pay lummox

**Comment by DDihanov** [comment]
Giving them more starting money?

**Comment by tuypo1** [comment]
More starting money would be actual pay to win, too far

**Comment by Blithering** [comment]
How about giving them an EXCLUSIVE byond skin for their PDA?

**Comment by jknpj** [comment]
Make them able to pick their OOC color and maybe some kind of little byond icon next to their name so people know that they're not admins.

**Comment by Exxion** [comment]
>Brain damage proportionnal to their contribution

This but unironically

**Comment by Arthurdentist** [comment]
How about a Byond Balloon?
(Shitty mockup below:)
byond balloon

**Comment by Exxion** [comment]
Only if it makes you valid

**Comment by Blithering** [comment]
an "I supported byond and this tshirt doesn't even have shading" tshirt
byondshirt

**Comment by Kurfursten** [comment]
Is this a WIP or should we merge it?

**Comment by Exxion** [comment]
neither

**Comment by plosky1** [comment]
Only if the thermometer gives you feed updates with RNG quotes from Higoten and an annoying beep.

**Comment by SonixApache** [comment]
~~merge it as-is, I'll throw in some more later maybe probably not~~
WAIT okay i need to add a box with a byond logo on it to put the thermometer in

**Comment by SonixApache** [comment]
updated, see OP

**Comment by tuypo1** [comment]
Wait a second isn't an entire box way too far, that's an actually real advantage.

**Pull request merged**
