### PR TITLE
Revert "Big band musical instrument update"

### PR DESCRIPTION
**Pull request by ghost**
you can play wind instruments through masks this is a gamebreaking bug

### CODE REVIEW

**Comment by kol1th** [comment]
literally unplayable

**Comment by CptWad** [comment]
memes

**Comment by SkowronX** [comment]
pls no :-:

**Comment by ghost** [comment]
I'm sorry but that is a bug that makes the game unplayable I'm sure once it is fixed we can add this PR back in

**Comment by troots** [comment]
space jazz 4 ur soul

**Comment by NigglyWiggly** [comment]
What if you quit making stupid joke PRs and just reported errors like a normal person

**Comment by kol1th** [comment]
@NigglyWiggly i'm sorry, but this makes it unplayable. if you play you'd understand.

**Comment by TheFriggenSawbones** [comment]
@NigglyWiggly niggly wigglyu

**Comment by clusterfack** [comment]
Celt if this is all you have to contribute I'm going to ban you

**Pull request closed without merging**
