### PR TITLE
Misc packedstation fixes

### LINKED ISSUE #16246: elite syndicate shuttle on Packed Station is not a thing
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
9581b7d21e6a406b19679d154d87da250cfe2187

# Description
the elite syndi shuttle is not a shuttle
# Steps to Reproduce
try to use the shuttle
# What you Expected
the shuttle to work
# What Actually Happened
it didnt

### LINKED ISSUE #16257: Packed QM office
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
There's an air alarm floating over my outpost camera console.

### LINKED ISSUE #16403: Packed outpost issues.
* The Hyperspectral Imager (which looks like a photocopier) has been mistaken for an actual photocopier and put into a more office-y room, instead of by the Fourier in the analysis room.
* There's no multitool.
* Hell just some more tools accessible to scientists would be nice.

### LINKED ISSUE #16421: Packedstation lacks secway keys in Warden's room
The keys don't spawn with Secways, you need the keys that normally spawn in the Warden's room. Every other map has them.

### PR DESCRIPTION
**Pull request by PromethTK11**
Fixes #16421 
Fixes #16403 
Fixes #16257 
Fixes #16246 

:cl:
 * tweak: Packed: Now the hyperspectral imager is on place on the outpost, and there are some tools for scientist now.
 * tweak: Packed: Elite-syndie shuttle works properly now.
 * tweak: Packed: Secway keys added to the warden locker.
 * tweak: Packed: And a lot of misc fixes/changes!

### CODE REVIEW

**Comment by Kurfursten** [comment]
This isn't your fault but your changes have brought it to my attention: it would seem the warden's office (and probably much of the brig/armory?) is unsimulated (blocks_air = 1).

I also notice you have made substantial changes to centcomm/evac and research outpost hallway A. Please post pictures of those changes.

**Comment by PromethTK11** [comment]
Ah okay now it got conflicts

@Kurfursten There you go:

https://cdn.discordapp.com/attachments/333585269502640138/389542690565521411/unknown.png <- Centcom docks

https://cdn.discordapp.com/attachments/333585269502640138/389543075183067156/unknown.png <- Outpost

I'm fixing that about blocks_air, i'll commit later

**Comment by Kurfursten** [comment]
Wow, all the way into the HoS office too?

On one hand, amazing no one noticed this
On the other hand, brig is pretty hard to breach on Packed

**Comment by PromethTK11** [comment]
Yeah, i don't know were i did got that turf tho

By the way, probably in two days i'll fix the conflicts

**Comment by PromethTK11** [comment]
NAh fuck this, remaking the PR

**Comment by PromethTK11** [comment]
Remaking the PR

**Pull request closed without merging**
