### PR TITLE
Enables manual screaming

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
Fun is allowed
Manual screaming is here, this is not a drill
10 seconds cooldown between audible screams
Next plan is to add half-life scientist screams for scientists

:cl:
* rscadd: Enabled manual screaming.
* tweak: Audible scream cooldown increased to 10 seconds

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Manual screaming is a dumb idea.

**Comment by DrSnips** [comment]
Pro tip: don't have your emotes do damage we LITERALLY just did this and it was a major issue. Just have it on a cooldown at most.
Also what was said already emotes that make sounds are dumb and are begging for abuse.

**Comment by boy2mantwicethefam** [comment]
Oxy damage removed but 10 second cooldown

**Comment by ghost** [comment]
This would be a nice immersive addition and prevent silent deaths in maint from vampires and similar.

Farting is the only sound a spaceman can make voluntarily at this moment.

**Comment by Dacendeth** [comment]
silicons can spam audio emotes, why not carbons too I guess?

**Comment by DrSnips** [comment]
Something something the flesh is weak and can't scream over and over.

**Comment by Gringonius** [comment]
Give it the same timer as the fart cooldown to please the naysayers.

**Comment by ShiftyRail** [comment]
The scream is much more audible than the fart sound.

**Comment by SonixApache** [comment]
fuck off

**Comment by Kitfox88** [comment]
> 
> 
> Manual screaming is a dumb idea.

*fart

**Comment by ShiftyRail** [comment]
The scream sound is much harsher on the ears than *ping or even *fart
Also, audible screams are just valuable feedback that someone got tased/doorcrushed in a game that lacks a lot of feedback

**Comment by jknpj** [comment]
Is there nothing sacred nowadays?

**Comment by spoonylove** [comment]
On the ww2 server they have manual screaming and let me tell you, they never let you forget that. I would say have a cooldown then after so many screams make people hoarse so they have to wait even longer.

**Comment by ghost** [comment]
Silicons have multiple really loud sounds that they can spam without any cooldown, AI has a voice synthesizer which can also make really annoying compositions. There's multiple sound playing items, including some that play the sound for each movement step, there's extremely low quality instrument sounds.

This is a sound with a 10 second cooldown, yet it somehow is a problem. I think the issue is less in what is being added and more in that it is something new and scary that people haven't played with for years already.

"X beeps/buzzes" 99x is a thing that happens nearly every round.

**Comment by ShiftyRail** [comment]
None of those sounds are as agressive as screaming nor associated with door-crushing or something like that

**Comment by ghost** [comment]
Clearly it's a new and scary thing.

**Comment by SonixApache** [comment]
@codeungabunga  
Screaming is what happens when people are being horribly injured. There's really no good reason to allow people to scream manually.
If you are used to people screaming constantly, or enjoy it, perhaps you should go back to where that's the norm.

**Comment by ghost** [comment]
There is a good reason to allow it, counter play to silent kidnappings by vampires for example. As with any new feature, it will most certainly be abused for the first weeks it is added, until it stops being new.

I think it's worth trying it out.

I also think it's not a very healthy attitude to tell people to go away because you disagree with them, when we're already struggling to keep players. You should reconsider your approach.

**Comment by SonixApache** [comment]
The example you gave is a perfect argument *against* this feature. It'd make antags even *more* reliant on chloral and other sleepy memes. As for trying it; we tried it on april fools, it went about as you would expect. It's a needless, obtrusive and most of the time downright annoying feature, and it is better left alone.

Furthermore, I believe it's not a very healthy attitude to take features from a place that is very dissimilar and bring them here. Instead, it may be better to just keep the two seperate, and stay with the one that has your preference.
In short; go back.

**Comment by ghost** [comment]
I'm not sure why you keep repeating "go back" or who you think you're talking to, but this is in no way a productive way to lead a conversation.

**Pull request closed without merging**
