### PR TITLE
Removes mineral cost from the RPED

### PR DESCRIPTION
**Pull request by jakmak3**
Removes gold and silver from the RPED in the protolathe and replaces it with a higher price of metal and glass

:cl:
* Increases the metal and glass cost of the RPED and removes the mineral cost

### CODE REVIEW

**Comment by Probe1** [comment]
That's not even remotely expensive enough to compensate.  It costs less than 1 sheet of metal and glass.

Make it something like 75,000 / 75,000.  Even at that price it's a no brainer always print this.

**Comment by jakmak3** [comment]
OK price is now 20 sheets of metal and 10 sheets of glass

**Comment by Probe1** [comment]
I'm not in love with the change but I withdraw objection to it.

**Comment by FudgePucker** [comment]
:+1:
Now to do it for tier three stock parts

**Comment by ComicIronic** [comment]
This counts as a continuation of #9664, and I still don't agree with making designs cheaper. Is there a reason to remove the mineral wall?

**Comment by jakmak3** [comment]
comic the problem with the rped costing minerals is that it is a simple piece of equipment needed for upgrading machinery in a timely manor. Yeah you can dismantle a machine in medbay and replace the parts by hand but if a doctor sees someone ripping apart their equipment they are just going to chloral stox and strait jacket. Also having the rped behind the mineral wall essentially puts all machine upgrades behind a mineral wall because no one is going to sit there and crowbar out circuit boards just to have security arrest them because they think they are trying to steal the machine boards

**Comment by Probe1** [comment]
There's no need to exaggerate things.  You can make a compelling argument without going deep into "that happened" territory.

Upgrading things in a timely manner is still locked behind the mineral wall if we only consider tier 3 parts to be worthwhile.  I'm sure someone has upgraded to tier 2 before but I've never done or nor have I ever seen it done.

**Comment by Intigracy** [comment]
Upgrading still costs minerals if you're using t3 parts, it just doesn't cost minerals to make the RPED as opposed to dismantling the machines manually.

**Comment by Kurfursten** [comment]
What this PR breaks down to is basically the question of "would some mechanics upgrade machines with just tier 2 parts?"

I don't really object to this PR but I would very strongly object to minerals being removed from tier 3 parts (unless they went back to plastic of course - I'm biased), which is where it feels like this is headed.

**Comment by jakmak3** [comment]
kurf i feel as though t3 parts should remain mineral gated and the pico manip have matts added to it (but super matter bin kept mineral free for r&d) and that we should consider T4 parts made out of diamond and shit so there would be a end game set of parts for making machines even better

**Comment by Kurfursten** [comment]
Tier 4 parts is a cool idea, you just need to make sure no machines would be broken by increasing to that number. I don't mean balance broken, I mean "actually broken because someone made a calculation assuming 3 was the highest"

hypothetical example:
`poweroutput = 10 / (4 - manipulatorlevel)`

**Comment by ComicIronic** [comment]
Being unable to upgrade a machine because other players assume you are stealing sounds like a player issue. Why is it not enough to say "I want to upgrade this machine"?

**Comment by Probe1** [comment]
There's a very valid point to be made about genetics DNA Scanner consoles.  If you disassemble them all the notes the geneticists have been making all round are lost.  Which really isn't worth a faster injector.

This is however the only machine that I know of that causes this problem.  Maybe cryo as well.

**Comment by 9600bauds** [comment]
Machinery upgrades are at an awful state as-is and anything that can help them gets my blessing

**Comment by PJB3005** [comment]
Consider this, what if manually replacing parts is the "tier 2" way of doing it, and the RPED is the tier 3 way?

**Comment by 9600bauds** [comment]
In this analogy, what is tier 1?

**Comment by Kurfursten** [comment]
Not replacing anything at all, since that's what machines start with. Or the flatpack machine.

**Comment by 9600bauds** [comment]
No, that's the part tiers. PJB is saying manually jamming in your tier 3 parts would be the "tier 2 way of doing it".

**Comment by Kurfursten** [comment]
I think we're having a miscommunication here. I understand PJB's analogy, but when you talk about building machines you're actually talking about two different things.

>Building the machine - stuffing parts into a frame or plugging the RPED into the frame
>Upgrading the machine - Disassembling a machine and stuffing in new parts OR plugging RPED into the assembled machine

PJB says the stuffing method is the tier 2 version of upgrading and building, so in his analogy, the tier 1 would be:

>Building: Use the flatpack machine (more expensive and restricted to tier 1, but requires no research)
>Upgrading: Don't upgrade the machine at all, this is the lowest tier of parts

**Comment by PJB3005** [comment]
Yeah I meant that manually upgrading the machine with reassembly would be on the level of tier 2 parts.

**Comment by FudgePucker** [comment]
@ComicIronic
Unrealistic expectations.
You tell a single medbay worker that you are upgrading machines his coworker doesn't know and shitter juices you. You inform them over the radio, one of them isn't up to date and shitter juices you.

Chloral is faster than say.

**Comment by Kurfursten** [comment]
@FudgePucker Was not able to reproduce on live, please take a webm so we can see what you're doing to produce this effect

**Comment by Intigracy** [comment]
I'm pretty sure if a shitter used shitterjuice on a mechanic upgrading things they'd get banned.

**Comment by Intigracy** [comment]
Though it was brought up that manually upgrading genetics stuff clears your saved buffers, it'd be nice if that were changed to work like arcades and save it.

**Comment by 9600bauds** [comment]
The hell happened to Needs Final Decision?

**Comment by Intigracy** [comment]
It went away after github added the review system.

If the code is good, approve it, and it shows an approved message on the PR page.

**Pull request merged**
