### PR TITLE
fixed teleport slip bug

### LINKED ISSUE #22699: wizard blinking onto slip
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
15a47a9af88dbb372aeb563348dc6e7e3609dbe7

# Description
if you blink onto a slip you get slipped even if you werent moving
# Steps to Reproduce
get blink
blink onto a lubed/watered floor
# What you Expected
to not slip
# What Actually Happened
i slipped

### PR DESCRIPTION
**Pull request by DDihanov**
[hotfix]

closes #22699

 :cl:

* bugfix: Teleporting(including spells like blink etc) no longer causes user to slip when arriving on the new location

### CODE REVIEW

**Comment by Kitfox88** [comment]
smdh at this wiz buff

**Comment by Exxion** [comment]
This should really use a flag rather than a whole new var
Even if it did need a whole new var, it wouldn't have to be on base `/mob`

**Comment by DDihanov** [comment]
> This should really use a flag rather than a whole new var
> Even if it did need a whole new var, it wouldn't have to be on base `/mob`

Where else though? The base method `forceMove()` is in atoms_moveable, but not all moveables should be able to slip, and mob being something that can slip, it makes sense the flag  to be there in mob as well. It made sense to me. `forceMove()` does not directly relate to `Move()` so there's no way to pass an argument, without any drastic reformatting I suppose...

**Comment by Exxion** [comment]
Not all mobs can slip. Only `/mob/living`.

**Comment by DDihanov** [comment]
I can move the logic in 'living', but it might be the case that someday you'd want not only 'living' to slip. It's your call dude I don't really mind.

**Comment by Exxion** [comment]
There is absolutely no reason we would ever want ghosts or AI eyes or the like to slip
But it's moot because the preferable solution is a flag, probably in `status_flags`, which is a mob-level var anyway

**Comment by DDihanov** [comment]
Okay so I should move the flag to `status_flags` or override `teleport_to` in `living` and add a flag there?

**Comment by Exxion** [comment]
Just add a flag in `status_flags`

**Comment by DDihanov** [comment]
Ok bois good to go.

**Comment by Exxion** [comment]
It looks like something went wrong with Git

**Comment by Kurfursten** [comment]
fix it

**Comment by DDihanov** [comment]
It's not bugged, I just rebased to the latest commit at the time, i.e. it pulled all the commits which were merged upstream.. It is good to go. If it's not you will get a merge conflict anyway.

**Pull request closed without merging**
