### PR TITLE
Island: Better kitchen/hydro

### PR DESCRIPTION
**Pull request by SonixApache**
Hydro has 5 more trays as requested by threadman, ranch windowified for threadman, added drive-thru for central hallways, added more windows to hydro and fixed up their cameras
Kitchen reworked to improve hydro communication, improve flow, reduce overal kitchen size and increase seating area
vending machine enclave has been destroyed by the service workers' union, no official statement from cargonia yet
moved central aft hallway APC down
got distracted and fixed people getting stuck in the disposals loop by removing the cross-over pipes and using the mirrored junction
includes the food press from #31400
~~**looking for input**~~ I think this one's about done, but feel free to post input.

pass3

:cl:
 - wip: Island: Reworked the kitchen and immediate area.

### CODE REVIEW

**Comment by BurntDevil** [comment]
Yea that beats what I did.

**Comment by MeetMan400** [comment]
Put the vending machines back. As a chef, I use those to grind out funny chemicals (mainly the Zam one TBH) for food. Don't make me walk down the hall for that. It was fine as is.

**Comment by SonixApache** [comment]
@MeetMan400 I could cut out one of the corner tables, but how about this for now?
image

**Comment by Eneocho** [comment]
Remove the northern walls to the diner so you can just walk in, please. 
Also if possible, move the xenobotany machines to the main botany room.

**Comment by MeetMan400** [comment]
@SonixApache Yeah, that works well enough. Long as all the machines are there to where the chef could go without being out of earshot/view of the diners, really.

**Comment by Eneocho** [comment]
Connected bar-kitchen is a staple. Can you try to merge them? One guy on the bread suggested that you merge both the kitchen diner and bar as one long megabar-diner. 
Bonus points if the hallway in between merges with the bar-diner.

**Comment by SonixApache** [comment]
@Eneocho What, like this?
image
Looks kinda bad, don't it?

**Comment by Eneocho** [comment]
I was thinking more like only the metal walls and airlock, but yeah, like that. I like the open flow. Having airlocks separate spessmen from food is bad in my opinion. I particularly like Synergy's kitchen. It has tables to the tiny diner outside the service area by science and tables to the bar, so you can serve both sides without flow disruption. People who want to be in the bar can access food as fast as people who were walking down the hall and saw the ass burger.

**Comment by SonixApache** [comment]
I think the 'floating' table feels out-of-place like that, so how about this?
image
I actually just really hate that open wall. Understand the need for flow, but it's clearly a missing wall.

**Comment by SonixApache** [comment]
image
I'm thinking this instead. Open feel, good vision, yet still enclosed.

**Comment by Eneocho** [comment]
I guess that works, though I'd still like for the kitchen (and it's food) to be accessible from the hallway.

**Comment by SonixApache** [comment]
@Eneocho came up with the perfect solution for that
drive-thru

**Comment by Eneocho** [comment]
Thanks I hate it. Guess that works though and would encourage MUH ARR PEE.

**Comment by Zth--** [comment]
Maybe this? I don't really like the lack of windows/access from east hydro's wall
image

**Comment by SonixApache** [comment]
like so?
image

**Comment by Zth--** [comment]
I think that's better, yes.

**Comment by Eneocho** [comment]
Please move the xenobotany machines to the main botany room.

**Comment by SonixApache** [comment]
I won't move the xenobotany machines. Them being back there is standard-issue and if needed the greenies can relocate the machines themselves.

**Comment by Rabbidx7** [comment]
> image I'm thinking this instead. Open feel, good vision, yet still enclosed.

As much as I like the idea of this, stop making the kitchen into a bar. Just move the bar there, and put something on the other side, I guess. Remove that bathroom, make it the bar backdoor, and put the bar just to the right. That way everything is connected. Makes the bar smaller, but its more concise and service gang is stronger for it.

**Comment by SonixApache** [comment]
The general consensus is that the bar and kitchen should be merged somehow, and although I agree with that sentiment, I won't be doing it in this PR.
If you have an idea of what to do with the empty space that moving the bar would leave behind, do let me know.

**Comment by BurntDevil** [comment]
Keeping them separate lets each one do their own gimmick, dont see a reason to combine them.

**Comment by Rabbidx7** [comment]
> The general consensus is that the bar and kitchen should be merged somehow, and although I agree with that sentiment, I won't be doing it in this PR. If you have an idea of what to do with the empty space that moving the bar would leave behind, do let me know.

One thing Island lacks is a building area, just generally. Box has one, bagel has one, and both are better off for it. It'll give people space for autism projects, or for general rooms people want to make. Give it a habitat vendor like bagel has, it'll be the biggest one yet.



> Keeping them separate lets each one do their own gimmick, dont see a reason to combine them.

Because it splits the playerbase, unironically. Service gang together STRONG.

**Comment by SonixApache** [comment]
I experienced first-hand why on my first round as island cook - i got four times as much traffic as the barkeep, to the point where he popped into complain about it.
As for a construction area, I feel like putting that in the core periphery is kinda awkward. There's definitely a better way to fill up that space, if it so happens.

**Comment by Eneocho** [comment]
> Them being back there is standard-issue

We have two maps that can vouch for the benefit of having the machines on the main botany room, namely waystation and synergy.

**Pull request merged**
