### PR TITLE
Increase EMP Stun to Borgs.

### PR DESCRIPTION
**Pull request by Sailol**
As the description says, it increases the stun that borgs recive when they get hit with an EMP to 15-20 for the strong part of the wave and to 10-15 for the weak part of the wave.
My reasoning for the change is as follows:

* EMP is a rare damage type whose sources are more often than not wasted after one shot, i.e granades, supermatter, admin intervention, etc. Hence, I belive it's nonsensical that a weapon that can be recharged over and over again, and is furthermore common such as the stun batton to do more stun damage than an EMP, even to a squishy carbon
* RP-wise I do not find any sense on flashes and flashbangs doing more to disable a borg than an electrical overload, considering that one only overloads the sensors on the borg and the other overloads the sensors, the servos, the components, basically everything that has circuitry on it.

I understand fully that borgs need to be stronger than carbons, and that a competent crew can stop a machine rebellion, but this fix is mostly for the other users of EMPs, chiefly traitors, raiders, and wizards.
Considering that traitors do not necesarilly have acces to the console nor do they always have acces to flashes (which, if you are not security or robotics, already implies stealing the one on the checkpoint, and you are not the only traitor and/or graytider around), they need some way to fight borgs with lawsets that allow them to kill the antag in question (all of the default lawsets allow for the birds to get valided by borgs).
Oh, and don't forget that EMPs burns flashes up.
In essence, I belive an increase in stun time allows for someone to either better gauge the situation and consider retreat if overwhelemed by borgs or wreck a managable number without wasting a lot of granades or shots on their ions, both of which will be on short supply in a prolonged fight.

I am ready to get memed now.

:cl:
* tweak: Changed EMP stun to borgs to 15-20 for strong EMP, 10-15 for weak EMP.

### CODE REVIEW

**Comment by clusterfack** [comment]
Bad change, makes the *minimum* possible stun time of the *weakest* EMP 10 times stronger

**Comment by Sailol** [comment]
Ok, consider this:
If the change was (2 , 6)
minimum possible stun time of the weakest EMP would be 2 times stronger., if it was 3, 3 times stronger.
The number 1, being the multiplicative identity, works in in such a maner that any increase is huge proportionally to the 1.
I don't belive that a 1 tick stun is a thing even worth considering, it makes such a little diference in combat it might not even be a stun at all.

**Comment by Exxion** [comment]
I think somewhere between that and what your change currently is would be good

Also please make the title better

**Comment by clusterfack** [comment]
Every mob tick is 2 seconds

**Comment by jakmak3** [comment]
Well i personally feel this doesn't go far enough but its a step in the right direction. merge when?

**Comment by jakmak3** [comment]
Well this change is a step in the right direction for making the anti borg weapons actually effective escpecially since traitor emp grenades and chem emp reactions are largely ineffective for borgs.

**Comment by Ephx1** [comment]
Hey, here's an idea, why don't you make more Borg damaging/stunning weapons or buff those grenades?
Ion guns are a stun and damaging weapon you don't even have to aim. Point vaguely and shoot.
Oh, and not only do they stun and damage but also remove some power from the Borg, fun huh?

**Comment by Sailol** [comment]
EMP damage is general, any buff to granades will buff ions.
To clusterfack, if you want to go that way, a weapon that is rare and specific, that could potentially cost the wizard a decent number of spell points can do 10 times less damage than a stun batton, and 8 times less than a flash. Why even bother with these abilities if they are so inefective in long range.
Also, I stand corrected, but a tick is still virtually no time.

**Comment by Ephx1** [comment]
You could make the grenades pulse more than once, y'know, that would be an excellent trade off for a one time use weapon.

Also for wizards, EMP's do a lot more than just zap borgs, they shock doors, activate firelocks, DRAIN WEAPONS, DISABLE HEADSETS, and do much more. If you want to kill a borg as a wizard you pick lightning and fuck them up miserably with a single shot.

**Comment by Sailol** [comment]
Well, I agree that EMPs do more than just blowing borgs, but considering how most people already field balistics when facing wizards, EMP is not that useful for draining weapons.
Also, does one two-power lightning zap does enough damage to break a borg's components?

**Comment by Ephx1** [comment]
Most people field chloral when dealing with wizards, sure ballistics are good but it's all based around what spells you get, what you get fucked over with is all how you choose to mold your powers.

Are you kidding me for lightning? One shot fucks you up, stuns you, then since you can't move you get shot repeatedly again. Second shot is a guaranteed break of components last I played, which is admittedly a while ago.

**Comment by Sailol** [comment]
I know that it two crits carbons, but considering that borgs have more health than squishy carbons and the calculations for component damage are not as straighforward as "go into crit when you get 100 damage total", I don't really know how much damage would a zap do. It also does not stun anymore, but it does slow you down.

**Comment by Ephx1** [comment]
You're definitely right on that, I've been wanting a cyborg components overhaul for a while but no one has wanted to touch the mess ever since we ported bay's system (who has since improved the system immensely). Fighting borgs can be a gamble, but there's a good chance it just turns into a hunk of metal that can walk, or stops moving in general due to the dice rolling on a component destruction.
Battery out? Nudging zombie
Actuator shot? You're a statue
Cameras poof? A nudging zombie that can talk
They may have more health, but it's like if on humans you went yellow and one of your organs shatter instantly, that's playing borg. Took damage? Well shit you have to pray to god that thing that damaged you, despite how weak it was, didn't break anything important. Anything below 80% is potential death zone.

**Comment by Sailol** [comment]
Thing is, this merge won't increase component damage, but bring EMP to the level of a stronger flashbang instead of a shittier one, considering that there are six nades on station, and you need to build any more that you need to procure (also known as never happens), I think that a rarer item should compensate for it's rarity with being better than the more common alternatives.

**Comment by Ephx1** [comment]
I think getting the weapons should just be more common. That's a borg's gimmick, they're an inflatable toy that can only be broken by a specific pin while everything else is piss poor. As I said, the Ion guns are already incredibly powerful being a damaging stun that has an AoE effect on impact making it easier to hit. 
Just making them stronger isn't a good idea, especially when most rogue borgs already just remove the small few that are on station.

Making the grenades stronger in some way I definitely agree with because they're pretty shit.

**Comment by AutismSpider** [comment]
you left out arm borers can make emps happen to be on par with getting shot by ion gun if your in its range

**Comment by Ephx1** [comment]
Goddamn I fucking hate the current borer system

**Comment by Allspice** [comment]
Nothing you do will realistically do will make an ion stronger than a flashbang vs borgs, just a heads up.

**Comment by Shadowmech88** [comment]
There's also the blinder, which can be built from Assistant-access-level materials and stuns all borgs on-screen.

**Comment by Intigracy** [comment]
Something EMP definitely should do but doesn't is drain some energy from the borg's powercell.

**Comment by clusterfack** [comment]
Are you sure

**Comment by Ephx1** [comment]
That's _exactly_ what it's supposed to do, Intigracy.
If it doesn't that's a bug.

**Comment by Intigracy** [comment]
Does it call emp_act() on the power cell in the borg automatically?

**Comment by clusterfack** [comment]
Last I checked yes it does

**Comment by Intigracy** [comment]
Clusterfack your initial comment on this is incorrect by the way if you were assuming 2 is the weakest emp severity, 3 is.

(EMP severity is backasswards and severity 1 is stronger than severity 3.)

Severity 3 EMP does nothing to cyborgs besides the flashing on the screen.

**Comment by Intigracy** [comment]
I think more reasonable numbers would be

```
switch(severity)
   if(3) (would be added)
      take_organ_damage(5)
      Stun(rand(1,5))
   if(2)
      unchanged damage (10)
      Stun(rand(5,10))
   if(1)
      unchanged damage (20)
      Stun(rand(10,15))
```

That's at most (in byond time, so probably a little longer) a 30 second stun from a direct hit, which is a fairly long time.

**Comment by Sprok0** [comment]
emp_act(3) doesn't happen from normal EMP bursts, and probably never at all. empulse() does 1 in the heavy range, and 2 outside of that, but never 3.
https://github.com/d3athrow/vgstation13/blob/a559bcf4e9f3004ad5969e1344680db1f37575a2/code/game/objects/empulse.dm

**Comment by clusterfack** [comment]
@Intigracy then you misinterpreted my first comment, I was saying only severity 1 and 2 occur for emp bursts genius.

**Comment by Intigracy** [comment]
This needs some sort of agreement somewhere.

**Comment by AutismSpider** [comment]
why make emp stun stonger when can stun lock a borg with flash bang spam with little to no down sides?

**Comment by jakmak3** [comment]
problem is with stunlocking a borg with a flash is if you miss the timing on the flash by 1 second either your flash burns out or the borg wakes up from the stun and memes you and with flashbangs even while wearing a helmet+sunglasses it still stuns you for ~3 seconds as oppose to the borg which gets a ~8 second stun depending on how far away the borg was from the blast which is around 5 seconds average stun in your favor.
Besides as it stands ion rifles/emp grenades/and uranium+water chem reactions are woefully underpowered when it comes to fighting borgs with how much of a production it is to get any of the aforementioned weaopns

**Comment by 9600bauds** [comment]
Why not make EMP stun stronger when you can stunlock a borg with flashbang spam with little to no downsides?

**Comment by jakmak3** [comment]
flashbang spam? you can only carry so many flashbangs at a single time and unless you have the helmet+sunglassess combo you are going to get stunned aswell and even with the right gear you still get a small stun. As it stands now improvised weapons like the blinder are better against sillicons than the actual anti sillicon weapons are

**Comment by Probe1** [comment]
You can pretty easily get boxes of flashbangs.

This is split and it should head to the server for the players to decide.  @Sailol is this PR ready to be voted on?

**Review by PJB3005 — APPROVED** [review]

**Review by Probe1 — DISMISSED** [review]
Pending server vote.

**Comment by Allspice** [comment]
30 brute and normal size or 60 and bulky. Plus boost the minimum stun of a weak EMP to 2-3 ticks.

My comment re. flashbangs still stands.

**Review by Probe1 — CHANGES_REQUESTED** [review]
User is going to change values to be less insane.

Ticks in life are two seconds each.  I.e. the range suggested is 20 seconds to 30 seconds for a weak emp and 30 seconds to 40 seconds for a strong emp.

One hit of an ion rifle.

**Comment by 9600bauds** [comment]
Continued in #13013

**Comment by Exxion** [comment]
So... close this one?

**Comment by 9600bauds** [comment]
k

**Pull request closed without merging**
