### PR TITLE
Allows admin test dummies to spawn with custom outfit and appearance

### PR DESCRIPTION
**Pull request by ghost**
[content][administration]

### CODE REVIEW

**Comment by Kurfursten** [comment]
I don't think I want this
It's an extra click every time I need to spawn in as a test dummy and honestly you shouldn't be appearing to players as a test dummy in most cases anyway.

**Comment by ghost** [comment]
> I don't think I want this It's an extra click every time I need to spawn in as a test dummy and honestly you shouldn't be appearing to players as a test dummy in most cases anyway.

Change it to a new secrets panel menu option then?

**Comment by Kurfursten** [comment]
Sure that would be fine

**Comment by ghost** [comment]
> Sure that would be fine

Done

**Pull request merged**
