### PR TITLE
Revert "Nofruit are completely random and have a static cycling animation."

### PR DESCRIPTION
**Pull request by kilozombie**
Reverts d3athrow/vgstation13#13786

Self-merged controversial issue that was still being discussed. More people against it than for it. A better PR was available with nearly universal praise and approval, and instead this one was self-merged over an argument N3X instigated over OOC in which he got mad.

This is sort of pathetic. I wanted to be civil for once. If you want to talk, N3X, I'm freely available for PMs on BYOND or whatever.

edit: The better PR is here: https://github.com/d3athrow/vgstation13/pull/13699 Does something similar to this self-merged PR, but everyone is happy instead of 45% of people.

### CODE REVIEW

**Comment by ghost** [comment]
http://i.imgur.com/dN6y624.png

**Comment by Durgen** [comment]
10000 hours

**Comment by kilozombie** [comment]
Reminder
https://github.com/d3athrow/vgstation13/pull/12696

**Comment by kol1th** [comment]
Can we just remove no-fruit already

**Comment by ScrambledSteak** [comment]
remember when No-Fruit was just a fun chowder reference and not the most controversial thing on the server

**Comment by kilozombie** [comment]
remember when Space Station 13 was just a fun atmospherics simulator and not the most waifu-infested shitfest on the planet

**Comment by ScrambledSteak** [comment]
i don't remember anybody bringing up waifus but okay

**Comment by 9600bauds** [comment]
Self-merged controversial PR with more thumbs down than up, this doesn't even warrant a discussion. It's a terrible violation of collaborator standards and it makes every collaborator look bad. DON'T do this please ~~or at the very least get someone else to merge it~~.

**Pull request merged**
