### PR TITLE
Silencing Spray

### LINKED ISSUE #25861: Feature Request: Silence spray
The invisible spray makes items invisible, a silent spray can make them silent. Same applies where clowns/mimes get a permanent version.

### PR DESCRIPTION
**Pull request by west3436**
## What this does

Adds Silencing Spray which can be used on anything Invisibility Spray works on and will prevent it from making any sounds for 5 minutes (regular) or permanently (clown/mime traitor item only). Also refactored invisibility spray so it shares the same parent as silencing spray.

## Why it's good

Sounds fun and closes #25861.

## How it was tested

- Spawned a mime and assigned a traitor role.
- Tested the invisibility spray to ensure proper behavior was maintained after the refactor.
- Tested spraying the silencing spray on various sound-emitting movable atoms.

## Changelog

:cl:
 * rscadd: Added Silencing Spray which can be used to silence any mob/obj/machine which it's sprayed on.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
What are some interesting uses for this?

**Comment by wotisjanitor** [comment]
Also it would be funny if it had a special interaction with mimes

**Comment by west3436** [comment]
> What are some interesting uses for this?

Loud items like guns, eswords, the organ extractor, etc can by used more stealthily now. Combining this with invisibility spray could make the shard super evil, though I haven't tested it yet.

**Comment by ErrorsWindows** [comment]
okay
but how well does this silencing spray work on



P̴̜̼̹̫͚͎͙̠̝̖̫͉̲͓͖̞̅̍̀̌̏̊͊̐͊̍̓̊̎̋͐́͘ͅ  ̶̧͙̞̼̬̀̋͋̔̈̓̿̕Ȩ̴̢̭͔͖̗͇͒͜ͅ ̷͙͙̘̦̉̈́͋͑̇̐̑́̚͠ Ọ̵̣͔͓̼͎͂̿̓̓̿́͒͜͝  ̵͙͚̭͔̼̦̮̹̻̓̑̚͜P̷̨̡̧̧̙̪̤̲̳̮͖̰̣͕̱̞͂̎  ̶̢̝̭͍͔̥̟̳͓̗̊͋̃̈́̈́̄̚͜͝͝Ļ̸̢̨̛̳̻̞͈̣̫͕̲̥͕͊̿̋͂̐̔̊  ̶̢͕̯͈̘̻̠̘̦̗̣͇̖̊̋̓̔̃̒͝Ẽ̶͓̮̓̏̈́́̔̉̔̄͊̚͘̚͠

**Comment by angryturnip** [comment]
I can't wait to spray the juke and antagonize the active admin for the round when he gets a bunch of ahelps about it not working

**Comment by angryturnip** [comment]
By the way, does this make bomb explosions silent or is the explosion sound separate from the object?

**Comment by west3436** [comment]
> By the way, does this make bomb explosions silent or is the explosion sound separate from the object?

My man this is 0% tested lmao but I'd assume this would silence the bomb.

**Comment by wotisjanitor** [comment]
You removed the untested label, how did you test it?

**Comment by west3436** [comment]
> You removed the untested label, how did you test it?

I literally updated the OP with details on how I tested it lol

**Pull request merged**
