### PR TITLE
The Great Unswitchening: The Final Chapter

### LINKED ISSUE #4447: Meta also got fucked up by the reseting and map merger fuck up

### PR DESCRIPTION
**Pull request by Exxion**
Unless I am mistaken, only Meta and Box were broken by 9c21244617fed55448b2fcc68170e18f205f65a0. Box has already been fixed. Here are the fixes to Meta.
There may still be issues, as this approach was substantially less manual than the approach I used for Box. Meta was vastly more fucked than Box, though, so it would have been impractical to do it that way. But any such issues will be much less bad than the current ones and will most likely be related to scrubbers not scrubbing the correct gases. There won't be anything major like scrubbers scrubbing O2 or N2 where they shouldn't, just some not scrubbing CO2 or Plasma when they should and maybe the same for N2O. They were already weird anyway, so it's unlikely anyone will notice a difference, if there even is one.

Fixes #4447.

### CODE REVIEW

**Comment by IratePirate** [comment]
I would kiss you.

**Comment by Exxion** [comment]
This is a Meta issue, not a general one
But I guess it doesn't really matter

**Comment by Exxion** [comment]
@d3athrow merge pls

OK but seriously
I don't mean to be impatient, but I am pretty confident that bad things could happen if a PR is opened that would merge conflict this
It doesn't even matter which is merged first. Something would be broken.
I've checked and no currently open PRs will conflict with this except one that has so many tags it looks like it will never get merged and probably a few very old ones which predate the breaking and thus shouldn't cause the problems I'm worrying about.

**Comment by Exxion** [comment]
@CptWad *You fool.*

**Comment by dylanstrategie** [comment]
RIP Metaclub being voted in for the next ten years

These fools voted for it before the fix was in

**Comment by IratePirate** [comment]
So things will basically continue as they were before?

**Comment by d3athrow** [comment]
hilarious that defficiency wasnt affected by the issue

**Comment by IratePirate** [comment]
Clearly there is a conspiracy at work.

**Comment by Exxion** [comment]
Too bad BYOND decided to make me redownload all assets when I tried to connect that round
I warned them not to vote Meta
They ignored me
It would have been fun to rub it in their faces as the entire station somehow flooded with plasma

My guess is that the plasma miner that is missing from atmos ended up somewhere on the station, but I can't find it on the map render and I can't be bothered to reset a branch to an earlier version and recompile to search with Dream Maker

**Comment by IratePirate** [comment]
I think someone said it was in the middle of medbay, which is pretty funny.

**Comment by Exxion** [comment]
I love how there was one specific place on each map that became vastly more deadly with the bug
On Box, it was the Goonecode room, which was bugged to contain 31 lethal turrets.
On Meta, it was... the whole station.

**Pull request merged**
