### PR TITLE
Makes Decoy Balloons Scannable

### LINKED ISSUE #14850: Decoy Balloon not Scannable
(WEB REPORT BY: starnightx REMOTE: 172.93.109.202:7777)
The special scanner from Mechanic doesn't allow to scan the Decoy Balloon for mass produce.
>Unplayable

### PR DESCRIPTION
**Pull request by Shadowmech88**
Decoy balloons can now be scanned by the mechanic's device analyzer.
Fixes #14850

:cl:
 * tweak: Decoy balloons can now be scanned by the mechanic's device analyzer.

### CODE REVIEW

**Comment by DrSnips** [comment]
Don't forget the `mech_flags = MECH_SCAN_ILLEGAL` since it's syndicate gear.

**Comment by Shadowmech88** [comment]
Just because an item can be purchased from a Syndicate uplink doesn't necessarily mean it's dangerous enough to warrant `MECH_SCAN_ILLEGAL`. Bug detectors and EMP grenades don't have it, for example.

**Comment by Diavill** [comment]
this is perfect
clone army when

**Comment by Riekland** [comment]
IT'S

**Comment by ghost** [comment]
20 clowns soon

**Comment by N3X15** [comment]
* Added [balance] because this PR affects availability of a traitor item.  Already have an argument  over MECH_SCAN_ILLEGAL, for instance.

**Comment by Blithering** [comment]
20 clowns was already possible, this paves the way for infinite clowns

**Comment by small-boss** [comment]
fuck yeah

**Pull request merged**
