### PR TITLE
Prevents using high gamma settings to see in the dark

### PR DESCRIPTION
**Pull request by spookydonut**
This sets default black lighting_overlay and sets completely dark tiles to have an opaque overlay to prevent players using high gamma settings to see through the darkness.

### CODE REVIEW

**Comment by PJB3005** [comment]
1. this is a feature but yes the gamma problem is sadly unfixable.
2. there's literally a define you can modify to disable this. Just set `LIGHTING_SOFT_THRESHOLD` to 0. You don't have to implement this hack into the lighting overlay code.

**Comment by spookydonut** [comment]
This fixed the darkness problem for CM-SS13.

**Comment by Exxion** [comment]
Completely dark tiles are already completely black. They aren't even sent to the client.
EDIT: Other than tiles immediately adjacent to you, which you can (partially) see while *blind* anyway

**Comment by PJB3005** [comment]
That's not completely true. They are if they're within your see_darkness
range (defaulting to one, so a 3x3 square around you). In that case they're
almost but not quite black (so that dark vision eyes aren't completely
useless)

The problem with that is that it's a mixed bag based on gamma. Gamma too
high and it's too easy to see through it.

**Comment by Exxion** [comment]
I did say that in the edit

Also I've never had trouble seeing through the darkness on default settings for any computer/monitor
I always thought it was a feature

**Comment by DamianX** [comment]
It also doesn't compile at the moment:
 `code/modules/lighting/lighting_overlay.dm:9:error: 0: expected color, list, or null`

**Comment by jknpj** [comment]
I'll just-

**Pull request closed without merging**
