### PR TITLE
Tag mode : Changeling Clown Among Regular Mimes

### LINKED ISSUE #170: Tag Mode
Implement Tag Mode:
- Everyone starts as a Mime
- One is actually a clown dressed as a mime with changeling powers.
- Clown must absorb as many mimes as possible.
- Whoever kills the clown becomes the clown.

### PR DESCRIPTION
**Pull request by ShiftyRail**
## Tag mode

Tag mode is our oldest feature request. In the distance past of 2013, a brave bald man named N3X15 dreamed of a "Clown VS Mimes" game mode. The principle is simple : 

- Everyone starts as a Mime
- One is actually a clown dressed as a mime with changeling powers.
- Clown must absorb as many mimes as possible.
- Whoever kills the clown becomes the clown.

And more than 7 years later, with the technology of antag datums, dynamic mode & dynamic rulesets, and outfit datums, the technology is finally here.

## What is it exactly

I tried to keep the mode as close to the original idea as possible. Everyone spawn in mime clothes. One of the mimes is a changeling clown. They get a clown mask and wig, as well as a few other clown items. Killing them, and equipping his mask, is the key to absorb the clown's powers. The mime will of course lose their 

I made it so everyone spawns with a captain's spare ID on their backpack to help the flow of the game moving. All mimes are equal in Mime station.

Latejoiners will automatically become Mimes as well.

## What niche does it fit

Besides honouring our oldest feature request, it can be a variety game mode played at semi-regular intervals, like Dorf, Monkey Madness (it's pretty close to it, in fact), Lamprey exploration rounds, Castle, or the TF2 modes that Bomber Harris managed to come up with.

It can be a way to bring new players to our server - because I'm pretty sure you wouldn't see this coded anywhere else.

As a low-medium pop filler, I think it might just work.

## Administrative nightmares and other issues

To be honest, I'm not sure if this would be very fun in the long run - would basically turn into a Free For All murderparty really quickly, especially given the Mimes' lack of communication to coordinate against the clown ling - but as an occasional thing, it can be fun. 

I would be of the opinion to treat non-antag Mimes with more freedom than regular players, but not to allow them to instantly attack anyone and check their backpack - that would ruin the game.

## Other remarks

I had to change a few of the inner workings of Dynamic to make it work, but overall the structure of dynamic rulesets made it very easy to implement. It's also a really good application of outfit datums (I didn't work several years on them on-and-off for nothing).

I wish I knew how to draw to make a sick cover art of the concept. 

Closes #170

:cl: 
- rscadd: Added tag mode! Changeling clown in a station of Mimes! More info on the wiki!

### CODE REVIEW

**Comment by ShiftyRail** [comment]
This is currently about 75% tested. The game-ending condition works.  The roles, outfits, objectives and power are correctly tested. The ling mask works, and latejoining works as well.

There are a few details that I didn't check yet and will try to solve tomorrow.

**Comment by iFlashYou** [comment]
What if someone just spaces the mask?

**Comment by ShiftyRail** [comment]
Why would someone refuse a free antag ticket ?

**Comment by iFlashYou** [comment]
The question still stands, and you know why someone would do something like that

**Comment by PrimeDSS13** [comment]
perhaps make it similar to the nuke disk where it respawns on the map somewhere

**Comment by Dacendeth** [comment]
Should you really give the mimes the oathbreak spell in this?

**Comment by ShiftyRail** [comment]
@Dacendeth I think it could lead to something more interesting, more interactions. But maybe it would means the clown ling would get instantly ratted out.

**Comment by ghost** [comment]
> It can be a way to bring new players to our server - because I'm pretty sure you wouldn't see this coded anywhere else.

I'm not sure we would want someone as a regular who found the server and went to it for a gamemode like this.

**Comment by ShiftyRail** [comment]
We have monkey madness, highlander, dorf, meteors, and many other little things like that. I think it's good if you want a little bit of variety for a given round.

**Comment by ghost** [comment]
So this at its basis will just be a station of all-access mimes (ew) who would probably be talking with emotes while silently validhunting so they can get a ticket to kill everyone else?  This sounds miserable to be a part of, even as a twice a year rarity.  There was a reason that meteors was hated so much, even as a rarity.  Anyone who this would be capable of attracting to the server sounds like the absolute opposite of the type of players who would be a benefit to have around.

**Comment by gurfan** [comment]
but I like meteors :(

**Comment by coronasaurus** [comment]
sounds fun and epic, upvoted

**Comment by Quhzk** [comment]
Sounds unbelievably based and fun.

**Comment by ghost** [comment]
finally I can play among us on my atmospherics simulator

**Comment by ShiftyRail** [comment]
@sumireiro-sora To be fair, the feature request predates Among Us by several years.

**Comment by jknpj** [comment]
gonflicts

**Comment by Blithering** [comment]
Now we just need the Send In The Clowns mode and all will be well.

**Comment by ShiftyRail** [comment]
Fixed.

**Pull request merged**
