### PR TITLE
(Revival) Mining bar

### PR DESCRIPTION
**Pull request by ghost**
[content][vault]

From #19700, ports the ancient AI component stuff to our modern event system too.

image
image
image

And I'm still not MadmanMartian.

# Original PR:

For when you need to tap out while mining.

## Contains:

* Dusky the barbot. Will talk while people are in vicinity, **respond to set phrases** and greet you when you come through the door. **(And when you leave through it too)**
* **Hearing AI component, with presents allowing for responses to set phrases including the current time.**
* Area entering **and exiting** AI component, for binding events to these actions.
* Some bar machines
That's about it.

## TODO:

* ~~Need a sprite for a wall-mounted PACMAN for miners to put plasma ore and sheets into.~~ **Not a fan of this.**
* Make an evaluate_surroundings component and a chemist component, so dusky can actually make drinks

:cl:
 * rscadd: A new strange abandoned bar can occasionally be found on the asteroid.

### CODE REVIEW

**Comment by ghost** [comment]
make the bar robot look like Lloyd from DRG and you have my support

**Comment by Eneocho** [comment]
thank you madm- I mean kanef, very cool

**Comment by BomberBro** [comment]
Make the robot throw a glass of whiskey at you when you say "Pour me a drink bar-tender"

**Comment by Eneocho** [comment]
> Make the robot throw a glass of whiskey at you when you say "Pour me a drink bar-tender"

Only if it has a 50% chance to break the glass when thrown across the table.

**Comment by ghost** [comment]
> Make the robot throw a glass of whiskey at you when you say "Pour me a drink bar-tender"

With the new hearing AI component, this is slowly becoming a reality. I'll see what I can do.

**Comment by Eneocho** [comment]
> 
> 
> > Make the robot throw a glass of whiskey at you when you say "Pour me a drink bar-tender"
> 
> With the new hearing AI component, this is slowly becoming a reality. I'll see what I can do.

If memory doesn't fail, the guy actually says "give me a drink", instead of "pour me a drink". Though making sure "drink" and "me" are in the sentence for a drink to be dispensed would probably be better.

**Comment by ghost** [comment]
@Kurfursten The whole chemistry component and making drinks thing isn't really necessary for getting done in this PR, so I dunno about a WIP label.

**Comment by Kurfursten** [comment]
>have a todo list
>but it's not actually todo?

**Comment by Kurfursten** [comment]
I looked over the code for this and I have to say that I think the phrases are too specific for most people to ever notice dusky can talk. This is why most voice activated items tell you their phrases.

It's a problem that exists a lot with modern digital assistants too.

**Pull request merged**
