### PR TITLE
Sleeper upgrade buff

### PR DESCRIPTION
**Pull request by jakmak3**
This piece of shitty code that i made a few months ago changes how upgraded sleepers chems without changing their base functionality. Mechanics like the anti OD chem limits, only invapro in crit and basic sleeper functionallity are untouched by this. Instead it changes the chems that are in the upgrades. T1 parts (roundstart) have had dremaline removed and replaced with kelotane for balance. T2 parts (nano manipulators and advanced scanners) remove the kelotane and put dremaline back in its place and adds in Imidazoline, Inacusiate, and tricordrazine. T3 (pico manipulators and phasic scanners) adds in all of the previously mentioned chems in T2 parts aswell as alkysine, tramadol, and activated charcoal. I had picked these random and marginally usefull chems as their are miscellaneous and usually not made by the wild ride but could still be usefull at that exact moment. I could not add anti tox otherwise you would be able to synthesize 700u of tricord by spamming invaprovaline and anti toxin so i went with activated charcoal instead.

:cl:
- tweak: Removes phalanxamine and spaceacillin from upgraded sleepers and replaces them with imidazoline, inacusiate and tricordrazine. Further upgrades unlock alkysine, tramadol, and activated charocal..

### CODE REVIEW

**Comment by ghost** [comment]
Refer back to this for the previous arguments for and against the change.  #11338

**Comment by clusterfack** [comment]
You didn't mention that it also adds activated charcoal on the third stage. I think the other chems are fine, but that chem is a bit too much.

**Comment by Shadowmech88** [comment]
Can't Medbay already get activated charcoal out of the Medivends?

**Comment by Sprok0** [comment]
A limited supply yeah, but then they need to get charcoal from the hydro bioprocessor if it runs out.

**Comment by jakmak3** [comment]
woops forgot that part and i think the wall mounted nanovends only vend a few syringes of it and besides its low quality chem with few uses and is inferior in every way to anti tox since poisonous chems usually are metabolized doing their damage before the charcoal eliminates enough of the toxic chemicals and the only reason i included it is because putting in anti tox would allow for the creation of 5000000u of tricord

**Comment by Sprok0** [comment]
Charcoal is strictly worse than waterpotass followed by antitox though, like he said

**Comment by jakmak3** [comment]
close because git is fucked and i need to re do the pr again

**Pull request closed without merging**
