### PR TITLE
Make job ban checking faster (draft)

### PR DESCRIPTION
**Pull request by xXxEMBERGHOSTSQUADDIExXx**
## What this does
i heard in #35446 that checking job bans at roundstart is a slow process. this is an idea to maybe make the jobban checking faster by using nested lists rather than a monolithic flat list

one potential tradeoff is that initially loading and modifying the database itself requires an extra intermediate step, but reading from the banlist should hopefully be faster, and we can expect checking jobbans to be a lot more frequent than issuing or removing jobbans.

i dont really have experience messing with the database stuff in this context or access to the ban database so maybe someone with more experience can look over the idea and point me in the right direction or help test it

or maybe someone with access to the jobban database file can share it with me

also this isnt fully optimized and de-duplicated, moreso a concept to put out there and see if its worth pursuing and polishing

[wip][help]

### CODE REVIEW

**Comment by ShiftyRail** [comment]
A nested list is going to be infinitely better than copytext() for sure. This implementation seems OK at a glance, except for the second part. Rather than building a list out of text, you should be build a text out of the list.

I cant remember how the jobban SQL part works, but I'm pretty sure it's already giving results in the form of a list.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
the SQL seems to output a flat list of strings like this
```
"shiftyrail - Chef ## nonantag murderboning as chef"
"shiftyrail - Assistant"
"shiftyrail - Captain ## killed everyone as captain"
```

>Rather than building a list out of text, you should be build a text out of the list.

what do you mean? and what do you mean by second part?

hmm actually there might not even be an SQL file being used, seems like bans are just stored as text in a .ban file? im not sure

**Comment by Eneocho** [comment]
Something about unforeseen consequences.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
yeah i want someone with access to the ban file to please test this otherwise i have to make a dummy banfile and im not even sure the exact format it gets saved in on disk for reference so it makes testing a little tricky

**Comment by d3athrow** [comment]
> yeah i want someone with access to the ban file to please test this otherwise i have to make a dummy banfile and im not even sure the exact format it gets saved in on disk for reference so it makes testing a little tricky

set up an sql database locally using mariadb and the schema files located in the sql folder, configure dbconfig and put sql_enabled 1 in your config.

**Comment by ShiftyRail** [comment]
A keys-in-hand solution is to use WAMP server (on Windows) or XAMP (on Linux). You just launch a .exe, and then http://localhost behaves as a webserver with a database. You have access to phpMyAdmin to look at your database in real time. I think WAMP is using MySQL instead of MariaDB database, but the SQL language is the same.

**Comment by xXxEMBERGHOSTSQUADDIExXx** [comment]
Ill try making one. I also want to fill it with dummy data so it matches the current size. How large is the current job ban file?

**Comment by Eneocho** [comment]
It is so sad Hina died of ligma...

**Comment by Kurfursten** [comment]
Given that Hina departed and is not going to pretend this isn't him, this is derelict

**Pull request closed without merging**
