### PR TITLE
Fixes null spell sound plays.

### PR DESCRIPTION
**Pull request by gbasood**
Caught by assertions but still breaking shit

### CODE REVIEW

**Review by N3X15 — APPROVED** [review]

**Comment by Exxion** [comment]
There might be some null sound that gets played sometimes in the vicinity of the bar, too. I've noticed, for the last few months, that you will sometimes, seemingly at random, stop hearing the juke until you either enter and exit the area or it starts the next song

**Comment by PJB3005** [comment]
Juke doesn't use regular sound procs, can't be affected by these kinds of bugs.

**Comment by Exxion** [comment]
Well then what the fuck
I swear that only started happening a few months ago, too

**Comment by gbasood** [comment]
Juke plays sounds over a web-embedded player, right?
Playing a null sound that way wouldn't kill sounds.
@Exxion If it uses playsound() then it'll crop up eventually but right now the ONLY one in the logs is forcewall spells which have cast_sound = null

**Pull request merged**
