### PR TITLE
Fixes missing Deff hallway tile.

### PR DESCRIPTION
**Pull request by Kharkov72**
I didn't fuck up that area on purpose honest
I'm not own I'm nOT OWNED
[hotfix] [deff]

### CODE REVIEW

**Comment by Probe1** [comment]
A one line change - even an emergency hotfix one line change, does not excuse you from making a PR with information about the change.

Do better for all of us.

**Comment by Irradiation** [comment]
nani

**Comment by SonixApache** [comment]
🤔

**Comment by ArchSunder** [comment]
> A one line change - even an emergency hotfix one line change, does not excuse you from making a PR with information about the change.
> 
> Do better for all of us.

do better for all of us by existing more often

**Pull request merged**
