### PR TITLE
toggle PDA flashlight on rightclick

### PR DESCRIPTION
**Pull request by toomykins**
this PR makes it so you can rightclick your pda (while its on your person) and toggle the flashlight in that context menu.
image

### CODE REVIEW

**Comment by pedr69** [comment]
turn on integer scaling bro

**Comment by toomykins** [comment]
no

**Comment by wotisjanitor** [comment]
was gonna downvote for no reason but honestly more right click menu features is awesome

**Comment by ValkyrieSkies** [comment]
Dare I ask if it's possible to add a "Mark Messages as Read" button too

**Comment by toomykins** [comment]
> Dare I ask if it's possible to add a "Mark Messages as Read" button too

you're treading into dangerous territory

**Comment by SonixApache** [comment]
yes but no

the ctrl / alt hotkeys were added to cut down on the rightclick menu nonsense
make it ctrl+altclick

**Comment by CrazyAmphibian** [comment]
> the ctrl / alt hotkeys were added to cut down on the rightclick menu nonsense make it ctrl+altclick

the issue with that is you kinda just have to know what the hotkey is to use it (or spend 10 minutes trying to find the right wiki page that tells you which combination of alt or control or shift does it).
right click menus are easier, especially for stuff like this. i don't think toggling the PDA flashlight *needs* to have its own hotkey, a right click context menu is just fine.

**Comment by Inorien** [comment]
> yes but no
> 
> the ctrl / alt hotkeys were added to cut down on the rightclick menu nonsense make it ctrl+altclick

por que no los dos

**Comment by Securitymain** [comment]
common sonix L

**Comment by Kurfursten** [comment]
> > the ctrl / alt hotkeys were added to cut down on the rightclick menu nonsense make it ctrl+altclick
> 
> the issue with that is you kinda just have to know what the hotkey is to use it (or spend 10 minutes trying to find the right wiki page that tells you which combination of alt or control or shift does it). right click menus are easier, especially for stuff like this. i don't think toggling the PDA flashlight _needs_ to have its own hotkey, a right click context menu is just fine.

All click shortcuts should be recorded on the shortcuts page, which is linked from the main page
image
image

**Comment by Kurfursten** [comment]
Adding verbs is generally bad since they are slow, but this is surprisingly popular and it's hardly going to bring down the neighborhood on its own

**Comment by Exxion** [comment]
> Adding verbs is generally bad since they are slow

This was pretty much fixed years ago

**Comment by Kurfursten** [comment]
I will continue to live in the past like an old man

**Pull request merged**
