### PR TITLE
ousted superfluous gas pumps from box and meta

### PR DESCRIPTION
**Pull request by DamianX**
# what
metaclub and box atmospherics had this thing with a vent from the air mix -> pipe -> gas pump -> pipe -> gas pump -> distro
this pr changes it to vent from the air mix -> pipe -> gas pump -> distro

defficiency and roid already work like this
packed uses the MSGS and I don't care about fighting for r-wording that shitty thing

# why
to help with #25418, mostly
pre-roundstart mice can still go fuck themselves but borers shouldn't die as soon as they enter a vent now
with these changes distro reaches 1atm at 12:07, whereas previously it would reach 1atm at approximately never o' clock

:cl:
 * rscadd: boxstation's and metaclub's atmospherics have a straight pipe where a gas pump previously was

### CODE REVIEW

**Comment by Irradiation** [comment]
>Damian made a PR

What has the world gone to?

**Comment by ghost** [comment]
don't forget, you're here forever

**Comment by PJB3005** [comment]
> packed uses the MSGS and I don't care about fighting for r-wording that shitty thing

*ahem?*

**Comment by DamianX** [comment]
Fixed conflicts

**Pull request merged**
