### PR TITLE
Trader Setup Display

### LINKED ISSUE #33455: Tweak Request: Change Trader Job Outfit (in Character Select)
Currently when you preview a trader slot you see the default grey jumpsuit. They should be in alien robes or something similar. This also matters for the merchant license because they are in a grey jumpsuit, so it looks odd.

This doesn't affect inventories in game at all, no relation to that.

### PR DESCRIPTION
**Pull request by Kurfursten**
New blend:
image
Appearance on Mushroom
image

closes #33455

🆑 
* tweak: If your highest job preference is trader, you will now preview an appropriate outfit instead of a grey jumpsuit.

### CODE REVIEW

**Comment by Eneocho** [comment]
Can you fix the silicons not appearing as a silicon but rather as a greyshirt while you're at it?

**Comment by Kurfursten** [comment]
There is actually a comment by them in the code that displaying as a human is intentional so you can customize your appearance (since borg sprites have nothing to do with your character settings). I don't have strong feelings about this one way or the other so I'm not planning to change it in this PR.

**Comment by Kurfursten** [comment]
In the OP picture you can't see the magboots, so I have changed those to overlay on top of the outfit in the latest commit

**Comment by NigglyWiggly** [comment]
How’s this work for non-Vox traders?
Just the pressure suit?

**Comment by Kurfursten** [comment]
You bring up a good point. I need to check what mushrooms spawn in.

**Comment by Kurfursten** [comment]
Done

**Review by DamianX — APPROVED** [review]

**Comment by Exxion** [comment]
Ah, a reminder of how goddamn awful the appearance preview code is

**Pull request merged**
