### PR TITLE
[box] Expanded maint, new thing in space and goonecode containment TRY TWO THE TRYIN-ING

### PR DESCRIPTION
**Pull request by CptWad**
1. Two areas of maint expanded. Behind the bar-chapel where there was plenty of room for it and between viro and xenbio where there was also room for it.
2. New cozy place in space to go loot/live in
3. Before goonecode was real piss easy to get now not so much but theres also FUN things besides the goonecode too
4. Toys now scattered across the station. Collect them all!

### CODE REVIEW

**Comment by CptWad** [comment]
ahahhahaha it works

**Comment by AutismSpider** [comment]
Make sure people cant hand tele off the sata like it does on deff

**Comment by CptWad** [comment]
I dont want to straight copy deff
ive been told I fucked up by cluster so rip

**Comment by Skullyton** [comment]
WHERE'S THE PICTURES?

**Comment by Skullyton** [comment]
Also holy shit you might want to redo the PR all the way down to the commit

**Comment by PJB3005** [comment]
Yep this PR's pretty broken.

**Comment by dylanstrategie** [comment]
Obviously that PR was not done properly, though I feel it's obvious by now

Looks like you worked from master, if that branch still exists, OR forced to rebase outside of the map

**Comment by Boxe** [comment]
screencaps gaybo

**Comment by 9600bauds** [comment]
picture or it was not of happenings

**Comment by CptWad** [comment]
dock
new maint
roid
hardmore

**Comment by Skullyton** [comment]
>Putting living things in the goonecode satelite
>Especially a fuckton of mateba-toting russians

What are you, duny?

Liking the maint expansion though, depending on what secrets lie within of course

**Comment by CptWad** [comment]
Well duny stole all the good ideas for goonecode traps. A russian controled sattelite seemed fun. Also as I said thats an older image. Since my shits fucked anyway anyone got any ideas till I get help on the whole github access?

**Comment by ihadtoregisterforthis** [comment]
Yeah but why? Both viro and xenobio lose safety. Also that maint lacks basic atmos that weren't needed when the tunnels were straight lines.
Too many hidden spots between walls, even if they are empty.

Since you are already managing Box you could try moving the bomb test area for dylan

**Comment by CptWad** [comment]
How far back do you want it?

**Comment by dylanstrategie** [comment]
I honestly don't like those changes. The maintenance between Viro and Xeno makes no sense as both workplaces are intended to be isolated. The expansion of Bar Maint seems a bit messy. The new asteroid room I can't tell for sure. The ruskies on the satellite seems a bit too extreme

**Comment by CptWad** [comment]
Maintenance isn't supposed to look clean. As for xeno/viro they are still pretty secure, viros behind two or more walls and xenobio maint is sectioned off.
As I said if you want anything straight changed I can do it, I moved toxins back a few tiles.

**Comment by CptWad** [comment]
well actually ill do it all over again. lets see if I can not fuck it up

**Comment by Boxe** [comment]
>nuke disk on telecomms

nigger the fuck you thinkin

**Comment by CptWad** [comment]
thats a book

**Comment by Boxe** [comment]
oh

what're in the present and lockbox?

**Comment by CptWad** [comment]
Preset?
Theres a clusterbang in the lockbox

**Comment by Boxe** [comment]
the present in that 1x4 room on the telecomms with meat in it

**Comment by 9600bauds** [comment]
firefox_2016-02-14_15-44-16
Looks like more than a book

**Comment by CptWad** [comment]
/obj/item/weapon/book/manual/nuclear
its the nukeops guide

**Pull request closed without merging**
