### PR TITLE
Put Hypospray in medical belt

### PR DESCRIPTION
**Pull request by chesse20**
I didn't test this becuase its adding one object to an array/list/whatever i wrote this code on the github web editor. 

:cl:
 * tweak: CMO's hypospray and all kinds of autoinjectors should fit in the medical belt.

### CODE REVIEW

**Comment by SonixApache** [comment]
:cl: should be below description
good PR, medibelts lack a lot of options that they should have

**Comment by chesse20** [comment]
> 
> 
> 🆑 should be below description
> good PR, medibelts lack a lot of options that they should have

Moved the CL

**Comment by ShiftyRail** [comment]
You did it wrong.

**Comment by DamianX** [comment]
`/obj/item/weapon/reagent_containers/hypospray/autoinjector` is no longer needed in `can_only_hold` since you're adding its parent `/obj/item/weapon/reagent_containers/hypospray` to the list.
Either remove that or if, for some reason, you don't want to include all hypospray subtypes, put a `=` before the type to cause a strict type check.

**Comment by chesse20** [comment]
I removed /obj/item/weapon/reagent_containers/hypospray/autoinjector

**Comment by chesse20** [comment]
why does this not pass checks

**Comment by SonixApache** [comment]
someone else changed the file you were working in
pull from bleeding-edge, merge-commit, resolve conflicts, push changes

**Comment by DamianX** [comment]
Should you decide to contribute changes again, you should read a guide on how to set things up so that you're not commiting your changes to your Bleeding-Edge branch.

**Comment by chesse20** [comment]
i forgot to make a separate branch thanks for fix

**Pull request merged**
