### PR TITLE
Revert "Adds a new HoS coat"

### LINKED ISSUE #14195: HoS Greatcoat
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

3d70cc1a8639361e4e012dfd46719ce3de35ca53 

>General description of the issue
The new Head of Security greatcoat gives me eye cancer. It's edgy as fuck and just looks bad. The only benefit is that it immediately identifies Heads of Security who use it as "THAT GUY"

>What you expected to happen
To not have my eyes assaulted by this abomination.

>What actually happened
My eyes were raped by the shitty coat.

>Steps to reproduce if possible
It's literally in the HoS locker. Find it. Pick it up. Put it on. Go blind.

### PR DESCRIPTION
**Pull request by ghost**
Reverts d3athrow/vgstation13#13983
Fixes #14195

It looks like ass, and I'm sure many agree. Would be a cool idea if it weren't for the fact that the sprite is awful, particularly that awful red banding.
If one of our spriters could make it better, that would really be nice. Otherwise it needs reverted because this is just going to give me an eye tumor.

### CODE REVIEW

**Comment by kol1th** [comment]
Works on my eyes

**Comment by Shadowmech88** [comment]
Until someone re-sprites the red gradient to look better, I'd rather we just change the coat's sprite to be all-black rather than remove it.
I like the idea of a bulky greatcoat for the HoS.

**Comment by ghost** [comment]
>Works on my eyes

Well then I'm glad you're happy with that ugly red banding

**Comment by Intigracy** [comment]
It'd probably look better on the warden tbh.

**Comment by Riekland** [comment]
NO
the warden's coat and hat are iconic parts of him and if you change it you'll have sec looking even more disparate
it's bad enough that the white shirts exist and that the HoS can go without their cap already

**Comment by Blithering** [comment]
I made an all black version as @Shadowmech88 suggested, since the red portion seems to be the leading cause of eye tumours. Any other suggestions for improvement?
sundowner allblack

**Comment by SonixApache** [comment]
@Blithering take that grey checker pattern and paint it over the ugly black thing in front of it

**Pull request closed without merging**
