### PR TITLE
adds mushroom people

### PR DESCRIPTION
**Pull request by MadmanMartian**
- Adds the IS_SPECIES_MUTE - Basically miming but tied to your species rather than your person.
- Adds REQUIRE_DARK - Steadily regenerate in the dark. If you spend too long in the light you start to take damage.
- Adds the moshrum species.  You're a sentient giant plump helmet mushroom that can't talk, but can communicate via telepathy.
- Adds the moshrum brain. Looks like a plump helmet pie, but is in fact a brain. Useful for research.
- Adds the walking mushroom monkeyform for the moshrum. It's one of the botany walking mushrooms. Can't talk, can't wear anything, but looks hilarious when running around.

Final outcome may be different from initial. This is dependent on how the sprite may come out.

Sprites courtesy of @Dizor 

:cl:
* rscadd: Adds mushroom people. Their seeds are acquirable from either the vox outpost or xenoarch seed sites.

### CODE REVIEW

**Comment by CptWad** [comment]
neat

**Comment by Dacendeth** [comment]
Will they have better dark vision?

**Comment by MadmanMartian** [comment]
yup. darkvision is 5

**Comment by vampirebat74** [comment]
Purpletide when

**Comment by Coxswain-Navigator** [comment]
Don't forget to give them brute damage weakness. Some other optional things are fire resist, (plump helmet men can survive being engulfed in magma but this isn't dwarf fortress), being able to walk on tables (they are as tall as dwarves) and giving them hivemind instead of telepathy, or at least making it a language only they understand.

**Comment by SonixApache** [comment]
Do they glow in the dark?

**Comment by Durgen** [comment]
deepest lore: they are blood enemies of dionas and are from the same planet or whatever

**Comment by Kurfursten** [comment]
Could be interesting to replace the Diona seeds in the trader seed vendor with mushroom people seeds instead. Play up that division some more.

**Comment by Jubisloviu** [comment]
Would be nice to have their seeds on xenoarch too, give peoples a reason to not ignore carbon digsites

**Comment by ghost** [comment]
roundstart mushroom people who die 5 minutes in to station lighting when?
no seriously roundstart mushroom people that spawn with a sun umbrella when

**Comment by Durgen** [comment]
I made a bad sprite to hopefully motivate someone else to make good sprites
mobspritesfull
screen shot 2018-03-21 at 5 28 29 pm

**Comment by vampirebat74** [comment]
Fucking nice

**Comment by Cockswain** [comment]
suggestion: give them diona regeneration (darkness instead of in light) BUT make them only have 70 max health and unable to regenerate brute damage

**Comment by ghost** [comment]
It'd be nice if their meat was a child of `food/snacks/grown/mushroom/plumphelmet` instead of `food/snacks/hugemushroomslice` so that we can cook them into pies.

**Pull request merged**
