### PR TITLE
Fixes RCS code.

### PR DESCRIPTION
**Pull request by PJB3005**
Partial port of the Paradise RCS, partial code rewritten from scratch.

Not used anywhere, I ported it for xpc.

### CODE REVIEW

**Comment by xpcybic** [comment]
:hand: :weary: :ok_hand:
Oldmap porting FULL SPEED AHEAD

**Comment by Shadowmech88** [comment]
What's an RCS?

**Comment by CptWad** [comment]
I already have claim to donut

**Comment by PJB3005** [comment]
It teleports crates to cargo telepads.

**Comment by ghost** [comment]
Rapid Crate sender, it would let you link up a crate and teleport it to a certain teleport beacon.

It makes transporting materials from cargo to science a doddle

**Comment by ihadtoregisterforthis** [comment]
Fulton or Bust

**Pull request merged**
