### PR TITLE
Better wheelchair animation + wheelchairs no longer protect from sprays

### PR DESCRIPTION
**Pull request by unid15**

### CODE REVIEW

**Comment by PJB3005** [comment]
There is actually a variable `dense_when_locking`.

**Comment by unid15** [comment]
But they're supposed to be dense when not locking

**Comment by PJB3005** [comment]
Oh, derp.

**Comment by unid15** [comment]
Should also fix projectiles

Now they'll only hit the wheelchair if the shooter clicks on it

**Pull request merged**
