### PR TITLE
Autobackup for Genetics colored SE tabs

### PR DESCRIPTION
**Pull request by 9600bauds**
And two VERY IMPORTANT MAP CHANGES!!!!!!!
Layers the Box cloning diskette box above the glasses box, so it's harder to miss
dreamseeker_2016-12-13_12-55-35
Layers the large beaker in Deff chemistry above everything else because it's important!!!
dreamseeker_2016-12-13_14-59-41

:cl:
 * tweak: Genetics colored SE tabs will now auto-backup if there is a diskette inserted in the console. This is so that your tab colors aren't irreversibly lost if the console gets damaged or deconstructed.

### CODE REVIEW

**Comment by 9600bauds** [comment]
Actually wait, meh, this makes it impossible to copy labels to another disk

**Comment by 9600bauds** [comment]
Yeah this is better

Also proper pooling

**Comment by 9600bauds** [comment]
this doesn't really deserve to be called "mapping" but w/e lol

**Comment by 9600bauds** [comment]
how is this conflicting

i hate that this is conflicting

**Comment by Probe1** [comment]
Because we just changed a fucking lot of deff for christmas

also did you really just varedit a beakers layer?  when you put it in a machine is it going t have its layer scrubbed or is it seriously going to be the eternal beaker that sits on top of every other layer forever

**Comment by Probe1** [comment]
bless you for that genetics change though.

when that mechanic, that bright eyed young mechanic, walks in and destroys all your fucking work because they didn't use an RPED and you want to monkey them then disposal the corpse.

**Comment by 9600bauds** [comment]
I didn't varedit the beaker I just changed the order of the tile's contents so that the beaker is on top

**Pull request merged**
