### PR TITLE
[Meta] Makes escape pod windows less gay

### PR DESCRIPTION
**Pull request by BestName**
Removes the full windows from escape pods
Replaces the secpods indestructible shuttle window with 4 one directional reinforced windows.

### CODE REVIEW

**Comment by BestName** [comment]
I think I may have missed some pods.
Gonna check it out tomorrow.

**Comment by BestName** [comment]
Done

**Comment by ComicIronic** [comment]
That's a very high linechange for what should only amount to a few tiles.

**Comment by BestName** [comment]
I don't know why it's so high. I only touched the windows, pinky swear.

**Comment by BestName** [comment]
Well I took a look at it with a diff viewer and it looked like there were a lot of changes completely unrelated to the windows which is weird considering that those were honestly the only thing I touched.
Guess I somehow managed to break everything, oh well.

**Comment by ComicIronic** [comment]
Are you using the map merger?

**Comment by BestName** [comment]
The batch files at maptools? Yes I am.

**Comment by BestName** [comment]
It looks like just opening and saving the map causes a lot of linechanges even when using the scripts. I don't know what's up with that or if anything is actually being changed but I did test the map and I didn't see anything obviously wrong with it, it seemed just fine.

**Pull request closed without merging**
