### PR TITLE
Fixes energy axes being unconcealable after activation

### PR DESCRIPTION
**Pull request by gbasood**
Sets energy axes and energy swords to use initial proc to return to their starting state after de-activation

### CODE REVIEW

**Comment by ghost** [comment]
This is already the most powerful melee weapon in the game don't buff it more you nerd

**Comment by Shadowmech88** [comment]
Why are energy axes supposed to be concealable in the first place?
The sprite suggests that it's a normal-sized axe with an energy blade on the head.

**Comment by Exxion** [comment]
When spawned, it fits in a backpack. Once turned on, it does not, and never will again even after it is turned off.

**Comment by Shadowmech88** [comment]
As powerful as it is, I don't think it should fit in backpacks in the first place. Not even the regular axe can fit into a backpack.

**Comment by CptWad** [comment]
Yeah nah its supposed to be a gigantic weapon, being able to backpack it, or even bag o holding it its gonna lead to some really horrible murderbone on deff

**Comment by Exxion** [comment]
It really just shouldn't be available at all outside of adminbus
I am of the opinion that having it on Deff is a mistake

Also, why ever turn it off if it doesn't provide any benefits at all?

**Comment by BestName** [comment]
> The axe can now be concealed.

Except it can't actually be concealed. This is clearly a bug, how is fixing it a bad thing? And why are energy axes even available outside of thunderdome/adminbus?

@CptWad Why do you think it's supposed to be gigantic? It uses magic space energy to make the blade deadlier. It doesn't have to be gigantic to work and based on the fact that you don't even have to dual wield it (and that it's a normal sized item) I'd say that it's actually smaller than the fire axe.

**Comment by Imagebard** [comment]
@Exxion 
What do you mean
Are you telling me that Defficiency has a energy axe in it by default?

@BestName 
Don't even try to argue about how big items are here. Perspective is all over the game in this place, just forget it.

**Comment by gbasood** [comment]
@Imagebard the vault safe has an energy axe built-in.
I could remove the lines changing its w_class and set the default w_class to 5, which would prevent it from being in your backpack at all, but the only way you'd have to carry it then would be to hold it in your hand. You would never be able to put it on your back or store it anywhere but the ground

**Comment by Shadowmech88** [comment]
> you would never be able to put it on your back

Couldn't you just add a SLOT_BACK flag to its slot flags?

**Comment by Imagebard** [comment]
It needs a sprite specifically for then its on your back to allow it to be put into your backpack slot, or let it be invisible(bad idea). 
You could ask Niggly or anyone else contributing to this repo's sprites if you want one, of course.

**Comment by BestName** [comment]
@gbasood If you're gonna do that you should also remove the de-activation line since it makes no sense.

**Comment by gbasood** [comment]
@NigglyWiggly pls

**Pull request merged**
