### PR TITLE
Seeing Stone

### PR DESCRIPTION
**Pull request by Shadowmech88**
seeing_stone_display
Adds the seeing stone, a tiny item that can be used to increase the user's `SEE_INVISIBLE`, allowing them to see things not normally visible, such as ghosts. The seeing stone can't be used while moving.

:cl:
 * rscadd: Added the seeing stone, a tiny item which can be used to allow the user to see things that are normally invisible.

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by BobdaBiscuit** [comment]
\>Seeing stone
Screeeeee now I can't use that name for the camera stone artifact.

Neat tho.

**Comment by ghost** [comment]
Should make this a wizard item.

**Comment by PJB3005** [comment]
Wizards already get the scrying orb so...?

**Comment by ghost** [comment]
oh right then no idea how this can be useful but it's still cool regardless

**Comment by Shadowmech88** [comment]
@BobdaBiscuit
I could rename it. I was thinking some kind of lens may be a more appropriate name anyway.

**Comment by Aurx** [comment]
Could be cheaper than the scrying orb.

**Comment by Shadowmech88** [comment]
Not nearly as useful for wizards though, since it doesn't let you hear what ghosts are saying, just see them.

**Comment by Shadowmech88** [comment]
Changelog added.

**Comment by Gunosaguki** [comment]
Librarian should be able to get this somehow so they can get ghost film from xenobio and report ghosts.

I still think Librarian Seances should be a thing

**Comment by Aurx** [comment]
Librarian Seances can be a thing just as soon as you code librarians and ghosts who don't abuse them to ruin everything forever.

**Pull request merged**
