### PR TITLE
Admin sanity things

### LINKED ISSUE #8888: Beef up Admin Who with some player stats
Have a look at this.  You know there's no single place that counts and tallys useful information to admins like how many players are alive, how many are observing, how many are antagonists et cetera.  Could we add those numbers at the bottom of admin/advanced who?  Counting every time really sux.  It's not so bad right here in an issue where you have nothing to do.  In game though, the chat logs jumping and you're trying to count asap to find the data you need, and its generally a pain.

dreamseeker_2016-03-16_10-39-07

### PR DESCRIPTION
**Pull request by gbasood**
Buffs who for admins
Resolves #8888

Messages admins when players join response team with name and key

### CODE REVIEW

**Comment by gbasood** [comment]
Also, some people apparently want who for admins to show up in a window
Need more opinions

**Comment by CptWad** [comment]
:+1:

**Comment by Boxe** [comment]
>Also, some people apparently want who for admins to show up in a window
>Need more opinions

yes

it'd be nice if it showed up in a window for everyone but hey

**Comment by gbasood** [comment]
I mean I can do that too but apparently @ririchiyo thinks that we tried it and everyone threw a fit so it got reverted

Also, I suppose I should say the madmen want me to embed a tab into the chat window that shows who info

**Comment by clusterfack** [comment]
The logging/administration tag shouldn't be red, it's my goto for thinking something should be merged

**Comment by Probe1** [comment]
The color of DO NOT MERGE is your go to for "I should definitely merge this"?

**Comment by clusterfack** [comment]
Yes that is of course more likely than me having made a typo

**Comment by Probe1** [comment]
we need way more reaction images.

**Comment by ghost** [comment]
Make DNM black.

**Comment by ghost** [comment]
https://youtu.be/vhLtbFKzPcQ

**Pull request merged**
