### PR TITLE
GOONLIGHTS IS HERE GUYS!

### PR DESCRIPTION
**Pull request by PJB3005**
**NOTE:** This performs worse than current lighting. There is no way to make it faster than current. I believe that with the scheduler and 510 this is not an issue.

### CODE REVIEW

**Comment by Reker45** [comment]
mmm look at dem fancy lights, but the question lies, how laggy will it be =O?

**Comment by PJB3005** [comment]
@Reker45 not much slower, especially with the scheduler.

**Comment by MercuryDoll** [comment]
Is dat sum gradient-smoothed lighting? Oh lawd.

**Comment by Shadowmech88** [comment]
Isn't Europa lighting similar in appearance to Goon lighting, but faster?

**Comment by PJB3005** [comment]
@Shadowmech88 nope, none of those.

Europa's lighting uses completely different mechanics and runs worse, but it is more accurate.

This can hold as a placeholder until Europa is up to shape.

**Comment by Shadowmech88** [comment]
Oh right, I remember that there's some feature being requested on the Byond forums that _would_ make Europalighting run faster. Something about appearance churn, I think.

**Comment by gbasood** [comment]
muh europa
also  PJB "burned out on ss13" 3005

**Comment by clusterfack** [comment]
Europa wont be ready until 511 at the earliest when mutable appearances are introduced.

**Comment by FudgePucker** [comment]
:+1: best part of goon
Hell yes

**Comment by kol1th** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAA YES :ok_hand:

**Comment by ScrambledSteak** [comment]
Holy fug
The future is now.

**Comment by Probe1** [comment]
Please include any instructions for testing.  After a standard compile and host lighting was like this.

image

**Comment by PJB3005** [comment]
Uh sounds like your colour matrices are failing to render...

**Comment by clusterfack** [comment]
Current problems I could find loading it up
- Just like baylights the tiny bulbs are a little too weak, they need about one more range and a bit of an intensity boost
- This version of goonlights has no soft lighting

Other than that it looks fucking great

**Comment by clusterfack** [comment]
Also heres another example of things that run into problems

**Comment by PJB3005** [comment]
@clusterfack I couldn't get soft lighting to work, sadly.

The only way I can think of fixing that screenshot (although I personally like the effect) is by giving walls a modified lighting overlay icon.

**Comment by clusterfack** [comment]
Why would soft lighting here be any different than the version under baylights?

**Comment by PJB3005** [comment]
When I touched the alpha var the top right corner of the overlays broke, I'll have to screw around with it more probably.

**Comment by clusterfack** [comment]
I think soft lighting would more likely have to be managed by the color matrix rather than the alpha var

**Comment by PJB3005** [comment]
Oh duh, I feel stupid now.

**Comment by Fox-McCloud** [comment]
How does this impact mesons/night vision goggles/etc or species darksight?

**Comment by PJB3005** [comment]
Should work exactly like without soft lighting at the moment.

**Comment by clusterfack** [comment]
The code is basically just baylights except this time you are setting the color/alpha of each corner instead of the whole overlay.

**Comment by Fox-McCloud** [comment]
Also, @PJB3005 do you have some profiling reports on old lights vs this lighting system?

**Comment by PJB3005** [comment]
Not yet.

**Comment by PJB3005** [comment]
http://pastebin.com/eehEcBYZ

http://pastebin.com/PARmSJyN

So that's a bit below 2x as expensive.

@clusterfack does that seem acceptable?

**Comment by PJB3005** [comment]
@clusterfack I tried to fix that "issue" where walls are dark and it resulted in this: http://i.imgur.com/Bf52UCz.png

I have no idea how to fix it then.

**Comment by ihadtoregisterforthis** [comment]
Gay

**Comment by PJB3005** [comment]
I couldn't find any immediate issues with it but if somebody else could come and test it that'd be nice.

**Comment by PJB3005** [comment]
Oh wait right I forgot about soft lighting.

**Comment by CptWad** [comment]
one way to fiddle with that is to give wall machinery and doors some sort of natural light that only applies to their tile

**Comment by PJB3005** [comment]
@CptWad nope because if both sides of the wall are lit up then the light would "leak" into maintenance.

**Comment by clusterfack** [comment]
We should modify it so opaque sprites get an overlay that has significantly less drop off from each corner I think so that nearly the entire tile is covered with light.

**Comment by PJB3005** [comment]
@clusterfack that's what I tried but I [couldn't get it to not look weird.](http://i.imgur.com/Bf52UCz.png)

**Comment by ComicIronic** [comment]
What's the issue, the wall corners?

**Comment by PJB3005** [comment]
Yep, the weirdly coloured spots on the corners.

**Comment by PJB3005** [comment]
Soft lighting is IN.

**Comment by clusterfack** [comment]
Yeah the issue is that lights only light up half of an opaque tile, which means that wall objects become extremely hard to see

**Comment by clusterfack** [comment]
Goon has custom sprites for their walls to make them look correctly, why don't we do something like that

**Comment by ComicIronic** [comment]
As a personal thing, I find Goon walls pretty ugly.
We need a general perspective change if you want to resprite walls. Airlocks, among other things, would need fixing to be consistent.

**Comment by Shadowmech88** [comment]
I also prefer our walls to Goon's.

**Comment by clusterfack** [comment]
You bunch of geniuses I'm saying the lighting overlays are custom to their walls

**Comment by PJB3005** [comment]
> Not wanting goon walls

also

> extremely hard to see

If your monitor is set to ultra low brightness maybe.

**Comment by MercuryDoll** [comment]
- Walls and hazardlocks are straight top-down.
- Mobs and airlocks straight frontal.
- All machinery have a birdview perspective.

A little late if ya wanna add consistency to sprites.

**Comment by ComicIronic** [comment]
It's a little late to be cleaning up the codebase after 12 years but I still insist on doing it.

**Comment by FudgePucker** [comment]
I think the shadows on the walls looks nice. Airlocks need to be fixed

**Comment by PJB3005** [comment]
What needs to be "fixed" about them?

**Comment by clusterfack** [comment]
After the wall issue gets **some** resolution I'll consider this ready for merge

**Comment by PJB3005** [comment]
I don't actually think it's fixable...

**Comment by ComicIronic** [comment]
You could do cluster's solution of a custom sprite for walls. Have a turf-based generate_lighting_overlay?

**Comment by PJB3005** [comment]
@ComicIronic I did but I [ran into shading issues.](http://i.imgur.com/Bf52UCz.png)

**Comment by ghost** [comment]
It looks to me as if it generates the overlay from the base sprite, before the wall is smoothed, or something like that

**Comment by PJB3005** [comment]
What?

Wall smoothing has fuckall to do with this.

**Comment by SkowronX** [comment]
gimme

**Comment by iwillkillmyself** [comment]
Projectiles are showing up over the darkness, which is neat for lasers but not for tasers

**Comment by MercuryDoll** [comment]
> but not for tasers

Why not? They're electric projectiles, it makes sense and i see no immediate balance issue.

**Comment by Shadowmech88** [comment]
I wouldn't mind lasers/tasers being visible in darkness, but I think they should emit an aura of light rather than just being _above_ the darkness.

**Comment by PJB3005** [comment]
@Shadowmech88 I wanted to say that's not possible because they move too fast but...

I need to code this.

**Comment by ComicIronic** [comment]
Flare shells already do it.

**Comment by PJB3005** [comment]
Unless they forcibly re-update their attached light every movement (which I doubt), I doubt it looks any good.

**Comment by PJB3005** [comment]
Alright just tested it, it does indeed look shit.

The lighting doesn't update fast enough.

**Comment by ghost** [comment]
@PJB3005, maybe like this? Found that on Soviet Station, someone trying to implement goonlight there.
it's not the taser case though

b01c79e22c

**Comment by PJB3005** [comment]
Here's the thing.

Goon's actual lighting uses instant updates. That works on there because the lights instantly update.

We don't, and it updates at a 5 decisecond interval.

I however do have experimental instant updating in my code, but it's disabled and would lag a TON more.

**Comment by Shadowmech88** [comment]
So as it is, the light generated by the projectile lags behind the projectile itself as it moves?

**Comment by ComicIronic** [comment]
Why are we still on a lighting ticker instead of updated lighting from procs?

**Comment by PJB3005** [comment]
@Shadowmech88 no, the light moves every 5 deciseconds so it updates like once mid flight. 

@ComicIronic well it's a heck of a ton more expensive.

**Comment by Shadowmech88** [comment]
Why don't, for example, spessman carrying flashlights suffer from the same delayed updating of the light's position?

**Comment by PJB3005** [comment]
They do, it's just way less noticeable because they move way less fast.

**Comment by Shadowmech88** [comment]
I'm pretty sure our taser bolts move just slightly faster than a full-speed human, if I'm remembering the last time I tested it right.
If you fire one and chase it you can keep it in view for a second or two.

**Comment by Probe1** [comment]
For a long time after the current lighting implementation that issue existed @Shadowmech88 
I'm glad we're clear of it.

**Comment by clusterfack** [comment]
COME ON PJB WE'RE SO CLOSE

**Comment by Probe1** [comment]
- looks great
- Walls are fucky half lit
- time between updates is way, way too slow and simply walking with a PDA light in the dark there's a noticable, large delay between lighting updates.  It'll still be illuminating where you were 1.5 seconds ago instead of where you are now.

**Comment by ghost** [comment]
We're going to need instant light updates, aren't we ?

Ideally we can tell if a light needs updating or not

**Comment by clusterfack** [comment]
Not necessarily instant but lighting updates that happen very close to instant would be nice.

Instant lighting updates would make explosions a hassle without some workaround code.

**Comment by PJB3005** [comment]
@clusterfack I can actually abuse spawn to make multiple updates at once be performed at the same time.

**Comment by ComicIronic** [comment]
spawn(0) is awful and you should never touch it.

**Comment by 9600bauds** [comment]
Can you elaborate on why spawn(0) is bad? I want 2 lern

**Comment by clusterfack** [comment]
I don't see how he could abuse spawn to do what he said in the first place

**Comment by PJB3005** [comment]
@clusterfack it's simple.

We keep the lighting controller on instant, BUT we make lights that update tell the lighting controller to update themselves. We do this behind a spawn and an if, so IF somebody blows up 3 lights:

First light spawns an update to the controller.
Second and third try, but can't because the controller is set to "updating".
Spawn stops pausing and lets the controller update.

**Comment by ComicIronic** [comment]
spawn(0) shoves the instructions immediately after it to the front of Byond's internal processing queue, which means they take up more resources from having to be completed IMMEDIATELY.

**Comment by 9600bauds** [comment]
wew

**Comment by Shadowmech88** [comment]
Habbening.

**Comment by PJB3005** [comment]
NOTE: TO PRESERVE THE SUPRISE PLEASE DON'T MENTION ON THE THREAD OR SERVER.

**Comment by ihadtoregisterforthis** [comment]
Borders were wacky the few seconds of round we had.
Shuttles were sometimes dark

**Comment by clusterfack** [comment]
What the literal fuck @ririchiyo

**Pull request merged**
