### PR TITLE
Alternate messages for stuff while hallucinating + some tweaks

### PR DESCRIPTION
**Pull request by unid15**
-Chance of fake shuttle call and fake delta alert reduced greatly, they should be very rare now
-Added is_blind() and is_deaf() procs for mobs
-Added spook() atom proc and reworked Boo! to use it
-visible_message proc has three more optional arguments - drugged_message, self_drugged_message and blind_drugged_message
-Added hallucinating() proc for mobs which determines if they see drugged_message, self_drugged_message and blind_drugged_message instead of their normal versions. If the user took space drugs / mindbreaker recently, it returns 1. It takes more mindbreaker to get the effect
-Added simple_message() proc for mobs which works like src<<"message", except that it takes two messages - one is shown normally, other one while hallucinating. Example: M.simple_message("You hit [A]", "You hug [A]")

-The following stuff now provides alternative messages while hallucinating:

-crematorium, gibber, telebatons, stun batons, soap, banana peels, welding tool, soldering iron, health analyzer, medbots and both secbots and more
-passive genetic powers have a random message when activated or deactivated, meaning you don't know which one you've got (doesn't affect disabilities, passive powers which give you an overlay i.e. heat resistance, and active powers)
-you can't make out reagents correctly in glasses and beakers

### CODE REVIEW

**Comment by FudgePucker** [comment]
>The hallucination text for calling the shuttle after a cascade is smoothjazz
>'oh god the universe is ripping itself apart, please send help'
>[Smooth jazz plays]

:+1:

**Comment by clusterfack** [comment]
Too many commits ahhhhhhhhhhhh

**Comment by Unfit** [comment]
Yes will squash tomorrow

**Comment by clusterfack** [comment]
Compile failure, I like this pls fix

**Comment by Unfit** [comment]
Added two more fun things

First one is a low-chance hallucination effect which replaces a random mob's appearance with a random piece of food (this can include you as well)
Second one is a chance to see a spooky monster inside of a closet (instead of its usual contents) if you open one while hallucinating. An appropriate sound will play, you'll be weakened and the monster will disappear after a few seconds

**Pull request closed without merging**
