### PR TITLE
Fixes plasmen not breathing

### LINKED ISSUE #8409: Plasmamen atmos fucked
(WEB REPORT BY: rebuildramiel REMOTE: 158.69.55.2:7777)
Revision 7a52c8089dace2561f54697a090ecc86b4358b44 
Plasmamen seem to be unaffected by their suits and the atmosphere anymore.

I took off my suit and expected to light on fire.

I did not light on fire, and could even breath the normal air mix.

Just take off your suit and tank to reproduce.

### PR DESCRIPTION
**Pull request by gbasood**
N3X official scapegoat for Sood PRs 2016

fixes #8409

### CODE REVIEW

**Comment by ghost** [comment]
How about them not reacting to oxygen in the air anymore?

**Comment by gbasood** [comment]
What was the behavior before?

**Comment by Exxion** [comment]
They would burst into flames
This is common knowledge

**Comment by gbasood** [comment]
I understand that, just wanted to make sure that specifically is what was broken

**Comment by gbasood** [comment]
Looks like it works right now. I don't know if that's because I fixed them breathing which removed a runtime which prevented them from reacting, or if it's more specific.

~~Also, as it is, oxygen is a toxic gas for plasmamen - so they take burn damage and also take toxins damage. Is that second part how it was before, or?~~ Whoops nevermind

**Pull request merged**
