### PR TITLE
Adds More Shit To Autolathes.

### PR DESCRIPTION
**Pull request by Kevak**
Been sitting on this for a good week cause I kept forgetting to PR it. 

Adds several things to autolathes. 

Notably Botany tools (Cause seriously, if a lathe can make wirecutters why can't it make plant clippers? Same goes for minihoes and whatnot.) As well hand labelers, and contraband bear traps by player request.

Tested and works.

:cl:
 * rscadd: Adds several items to autolathes that felt like they were missing/were requested. Including some botany tools, hand labelers, bear traps and so on.

### CODE REVIEW

**Comment by Pathid** [comment]
A couple observations:
* Clippers don't do anything wirecutters don't do, it's mechanically an alternate skin. Not that it matters much if they're added.
* 5000 iron for a 12 force, 15 throwforce hatchet is dirt cheap if we're comparing it to the 12000 iron 10 force kitchen knife also from the autolathe. Metal tomahawks fill this niche and there's little reason to make them if this is added

**Comment by Kevak** [comment]
-Yah. It's still more aesthetically pleasing to use clippers than wirecutters.
-Tweakable. What pricing would ya recommend for it? I wasn't really sure what was a good pricing for em.

**Comment by Durgen** [comment]
perhaps the botany stuff could be under a separate subsection instead of mingled with the other tools

**Comment by Kurfursten** [comment]
Botany tools, sure, bear traps, sure, hand labelers why not. Even if making bear traps readily available to everyone kind of takes away from the jani's special toys I guess he has plenty.

But spray bottles? Spray bottles are *really* robust and they are not very available for a reason. Being able to slip 3 tiles without much aim and not interrupting your yakity is pretty powerful even without access to lube, just water. Remember that you are giving an infinite number of these roundstart to *science*. It's true that Cargo can order in spray bottles but that's relatively slow and limited in scope compared to queuing up 40 at the autolathe and building them instantly, plus Cargo does not have easy access to a chem dispenser and do not have bottles roundstart. Science can get chem sprayers, true, but those are illegal tech+guns so much more likely to get arrested than holding a spray bottle. On top of that autolathes are not too difficult to build as an assistant so this means infinite bottles for tiding about whereas previously they would need to break into a department to get just one.  Not to mention just in general I think of spray bottles as being plastic and not a glass item.

**Comment by Pathid** [comment]
@Kevak 
Personally I woudn't put hatchets in there at all. Having a small size weapon at roundstart that is comparable to a circular saw in robustness should be a service department perk, and it stops being that when any cargo tech, scientist or trader can print one and stick it in their survival box a few seconds in. Seeing how circular saws and tomahawks can chop wood, and hatchets can be ordered, why is this needed?

Spray bottles are potentially a _way_ bigger deal though like Kurfurst said.

**Comment by Kevak** [comment]
-Beartrap price adjust: Can do. Wasn't certain of pricing.
-Hatchet: Fair point. Can axe em from the list if desired.
-Spray bottles: Requested by a couple players. Can axe em due to the potential balance concern though.

**Comment by Kevak** [comment]
Aaand tweaked. Beartrap price raised to 50000. Hatchets and sprays axed from the list (Although the recyclable bit remains.)

**Comment by SonixApache** [comment]
I'd remove the recyclable bit from the bottles, just so people don't accidentally destroy them.

**Comment by Kevak** [comment]
I'd find that hilarious tbh. Similar in entertainment value to accidentally destroying guns during a firefight.

**Comment by Irradiation** [comment]
>Muh beartrap IEDs
Dare you enter my beartrap realm, security?
t.Cargo

**Comment by jknpj** [comment]
Invisible-sprayed ied beartraps are no joke @Irradiation

**Comment by Blithering** [comment]
How about making the spray bottles take plastic to make instead of removing them completely? you can still order a weedkiller crate if you're that desperate to make a slippy sprayer

**Comment by Kevak** [comment]
That would require fucking with autolathes to permit plastic in the first place. Outside the scope of this PR.

**Comment by Blithering** [comment]
ah, forgot about that restriction, nevermind.

**Comment by DamianX** [comment]
power creeeeep

**Comment by Kevak** [comment]
Gooonna boop. Been over a week for the balance wait.

**Pull request merged**
