### PR TITLE
Microwaves can now be examined to check out the contents.

### PR DESCRIPTION
**Pull request by Zth--**
Microwave code is a bit messy but I didn't really want to touch much of it for such a simple feature. I'd tag this as a quality of life

:cl:
 * rscadd: Microwaves can now be examined to check out its contents

### CODE REVIEW

**Comment by Probe1** [comment]
God I hate how that giant if statement looks.

**Comment by jknpj** [comment]
jesus christ

**Comment by ghost** [comment]
Why doesn't it just use the item in question's display name instead of using a giant conditional that results in basically the same thing?

**Comment by d3athrow** [comment]
this is amazing

**Pull request merged**
