### PR TITLE
Fixes volumetric lights

### LINKED ISSUE #30637: Light from lit objects appear to occupy inventory space
#### Description of issue
image
I observed this extra inventory row in my toolbelt when I stuffed my lit flashlight into it.
I took one other item out of my belt besides the flashlight and was back at two rows of 13 items, but I could not put that item back into my belt, as if it was full despite the available inventory slot.
This also happened with a lit welder, so I assume this is caused by the light itself.

#### Difference between expected and actual behavior
I didn't expect light to have a large volume.

#### Server revision

7575865e3fd3c543339f2c64eb61a1c0d2387e1a

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #30637

Also fixes something related to light atom destruction

### CODE REVIEW

**Comment by Exxion** [comment]
Is there a particular reason you want the light object to be physically inside the storage item at all?

**Comment by ShiftyRail** [comment]
~~So that when you have a light in your pocket it still casts light.~~
Wait, that's not even needed

**Comment by Exxion** [comment]
Wouldn't you want the light to be on the turf in order to cast light?

**Comment by ShiftyRail** [comment]
Yeah that's my bad. Lights in pockets stay on the mob's turf. It works now and it's less retarded (kills the light if it's in inventory).

**Pull request merged**
