### PR TITLE
Bagel Viro Refresh

### PR DESCRIPTION
**Pull request by DeityLink**
More like a near-complete re-map but ok

image

the previous one:
* had no switch to toggle the holosign
* the access airlock in medbay had no holosign
* had no intercoms whatsoever
* had no newsreader HOW DARE THEY
* the mouse cage was empty WHYYYY
* the only fire alarm was outside of the fucking lab

the new one:
* has light green floors as god intended
* has several intercoms
* has entertainment monitors near all beds (except the monkey testing ones)
* allows for safe carrying of monkeys from their pen to their test chambers without having them cross the entire pathogen filled area.
* split the break room and patient room. Seriously stop taking that idea from box Viro, it sucks.
* has some windows between the patient room and lab
* the maint airlock no longer features props that could get ZAS'd (a single O2 locker was enough anyway)
* has layered pipes allowing easier maintaining without having to remove windows or walls.
* has its disease dishes on the tables instead of awkwardly layered over the machines
* the analyzer is adjacent to the pathogenic incubator allowing quick mutation-analysis without having to move.
* etc, 

:cl:
* experiment: Lowfat Bagel's Virology has underwent reconstruction. We're hoping you'll find the final product a little more functional.
* rscadd: The critter cage in there also now actually features a pet lab mice instead of being desperately empty.

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
I like the new airlock connecting the two maints, alongside the rest of the changes of course.

**Comment by DeityLink** [comment]
More tweaks, mainly I've added fire alarms and extinguishers that were completely missing from it as well.

image

**Comment by beesil** [comment]
The grass area is out of place on a space station, shower could use a windoor. Looks great otherwise.

**Comment by DeityLink** [comment]
Those are grass tiles, the same ones that botanists can place. You can crowbar them off if you want. I don't like monkeys being in such depressingly bland pens all the time.

**Comment by beesil** [comment]
It doesn't really matter ultimately but I don't think it makes sense for a sterile lab!

**Comment by DeityLink** [comment]
If we cared for realism they'd all be in cages 
image

**Comment by DeityLink** [comment]
That might be a gimmick for another Viro though.

**Comment by Kurfursten** [comment]
Multilevel cage structure?

**Pull request merged**
