### PR TITLE
Roller beds can now be worn on Labcoats.

### PR DESCRIPTION
**Pull request by ShiftyRail**
If First-Responders can have it, why can't I ?

:cl:

- rscadd: Can now carry rollerbeds on labcoat suit storage.

### CODE REVIEW

**Comment by Irradiation** [comment]
Because if you don't wear the /fa/ responder jacket, then it's your loss, you filthy medical doctor.

**Comment by gbasood** [comment]
Labcoats allow for mini hoes for botanists because they're actually scientists too what the fuck how insensitive

**Comment by ShiftyRail** [comment]
>Dude bombs lmao

I guess that makes sense now

**Comment by Unknown-as-Captain** [comment]
Wait, in like, the thing's tiny pocket?

**Comment by DrSnips** [comment]
I didn't want roller beds to fit in normal labcoats so it somewhat exclusive to paramedics and CMOs. The first responder vest was something I felt was more of a paramedic role coat so I gave it to it as well.
I personally don't think they should fit on normal labcoats.
The minihoe thing was from avada something a while back because they just wanted it for personal preference.

**Comment by ShiftyRail** [comment]
FR is not a paramedic role coat, in fact, a MD Alt-Title also spawn with it.

**Comment by Probe1** [comment]
how are people fitting beds in coats

????

**Comment by DrSnips** [comment]
I always viewed the armor slot like a back slot 2.0 where the coat/armor has some kind of rope, hook, strap, or other type of method to hold onto the items.

**Comment by Pathid** [comment]
Yes, suit storage is visible on examine so it's only logical that its *somewhere* on the outside of the suit.

**Comment by SonixApache** [comment]
@Probe1 how the fug do you fit a shotgun into a kevlar vest?

**Pull request merged**
