### PR TITLE
Adds CUT_WALL and CUT_AIRLOCK flags, uses it in melee energy weapons

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
It can cut through walls, airlocks, and girders. Wall cutting is about 10 seconds for a normal wall. Airlock cutting is about 20 or so seconds because nobody wants to spend time building a whole new airlock every time one is bricked (yes it's faster to cut the walls), might need some tuning. Can cut girders in 6 seconds.
:cl:
 * rscadd: Melee energy weapons can now cut walls (not reinforced walls!), airlocks, and girders! Make them active first and use harm intent!

### CODE REVIEW

**Comment by aceedex** [comment]
I like the idea but I feel it would be very loaded with the TC cost being kept the same. Though I do like the idea of adding easier chase to the energy sword. My suggestion would be uppting up the time it takes to break a girder, as to give people more time to react. The airlock thing has a heavy overlap with an emag and breaking a wall is as good as breaking an airlock, so why not make the sword unbolt bolted doors instead?

Also a request I have, is maybe separate everything into different flags, so people can pick and chose a bit freely if this ever gets used in other items

**Comment by Kurfursten** [comment]
I said this elsewhere but I don't like having such an accessible and already good tot item giving r-wall cutting. Eswords are great already without getting a diamond drill function rolled into them.

**Comment by SonixApache** [comment]
👍 cool features
👎  makes eswords stupidly powerful while they're relatively common and cheap
Remove functionality from the swords or make a (for now bus-only) subtype that has it for now.
Would be interesting for spess ninja.

**Comment by Sooose** [comment]
I'd rather just have the bolt removal from airlocks and not removing the airlocks entirely. Make it take like 5-10 seconds.

**Comment by DrSnips** [comment]
I like the idea and I hear the concerns as above but my take on it is that the Emag fills the role of opening everything instantly while this has a long and obvious setup time. Saying its a better emag isn't quite right since it also doesn't do all of the other things an emag can like unlock comms consoles or crates.

**Comment by ghost** [comment]
Remove rwall cutting and it's perfect.

**Comment by Hoshi-chan** [comment]
Space ninja soon... It's all coming together.

**Comment by bathosbathtime** [comment]
I would personally bump up the time to 30 seconds minimum for the sake of not making the esword a god-tier syndicate item while still keeping the feature as an emergency escape or planned action.  More importantly is that rwalls should be immune to esword cutting.

**Comment by boy2mantwicethefam** [comment]
I don't feel like removing the r-wall interaction, but I really should make the time it takes higher, right now it depends on hardness and it's 90 AKA it takes 9 seconds to destroy an r-wall, thinking of 30, convince me further to remove the r-wall cutting because I don't see a real downside in this except make it able to breach more secure areas (I'm basing these interactions depending on how long it would take to deconstruct them conventionally, except for the girder)
Increasing time it takes to destroy a wall to 10 seconds
Increasing time it takes to destroy a girder to 6 seconds
Separating the flags into CUT_WALL and CUT_AIRLOCK
Instead of outright destroying the airlock it applies an emag-like effect to it (broken circuits, forced open)

**Comment by SonixApache** [comment]
>convince me further to remove the r-wall cutting

You can get a sword that can fit in your pockets, through either an uplink or vault / roid loot, that lets you literally ignore any and all structural deterrents without the need for tools or welding protection and at triple the speed of using tools.

Pretty sure you also don't have any busy checks, meaning someone could just slice through multiple Rwalls at once.

**Comment by Kurfursten** [comment]
Sonix has done a good job of listing the balance reasons (besides that, it's on an already good weapon/defensive tool to begin with)

Here's a practical reason: you can probably convert most of the 👎 on your PR to at least neutral or 👍 if you get rid of r-wall cutting.

**Comment by boy2mantwicethefam** [comment]
It's not about the votes, it's about the content
Security(?) metaclub(?) wins again

**Comment by SonixApache** [comment]
fix the busy checks

**Comment by boy2mantwicethefam** [comment]
I admit that I don't know how to do that

**Comment by MadmanMartian** [comment]
fix confrictu

**Comment by Kevak** [comment]
I like the earlier suggestion of letting eswords cut door bolts. That'd give the weapon a solid utility niche that will come in handy for taitors that the AI is after without giving it a substantial enough powerbuff to warrant a TC cost boost.

**Comment by Kurfursten** [comment]
Conflicts were indeed fixed, and you've got twice the votes in your favor

**Comment by SonixApache** [comment]
>didn't fix the busy checks

**Comment by bathosbathtime** [comment]
Busy checks are for nerds, multitasking is the method of kings

**Pull request merged**
