### PR TITLE
The Tubes, They Wheel

### PR DESCRIPTION
**Pull request by help-maint**
dreamseeker_18_04_2021_03_21_21_02

Todo:
- [x] Quadruplecheck the sanity to verify it's correct
- [x] ~~Changing a conveyor's direction via multitool doesn't stop it~~ different PR
- [x] Write some code into the cloner that determines if the output tile is on top of a conveyor belt loop at least 10 tiles long, and if so, play https://youtu.be/jtIr55-ZJ1U?t=101 for the cloned person
- [x] ~~DNA scanner automatically starts a scan when conveyor_acting if connected to a cloner console~~ doesn't really do anything

:cl:
 * rscadd: Conveyor belts will now automatically load lying patients into Cryo, Sleepers, Thermal Homeostasis Regulators and DNA scanners, if the conveyor is turned on and points directly into the machine.
 * rscadd: You can now set a custom output tile for Cryo and Cloners by using a multitool, similar to how it works for autolathes and other fabricators. When automatically ejecting patients, they will go to the custom tile instead of on top of the machine.

### CODE REVIEW

**Comment by SageOfLight** [comment]
Ahahaha... AHAHAHAHAHA... HA HA HA HA HA YES.

**Comment by djkramer123** [comment]
holy shit

**Comment by Kurfursten** [comment]
Does anything automatically remove old bodies from the clone scanner?

**Comment by Brotanics** [comment]
Holy fuck.

**Comment by jwhitak** [comment]
Jesus Christ.

**Comment by toomykins** [comment]
Art.

**Comment by Eneocho** [comment]
This is so impossibly based I can't even describe it.

**Comment by Eneocho** [comment]
> 
> 
> Does anything automatically remove old bodies from the clone scanner?

It should scan then spit out the corpse. Possibly into a third conveyor line for corpses.

**Comment by calzilla1** [comment]
:+1: only if this plays anyone enters the ride [https://www.youtube.com/watch?v=KoLOtsm_Jow]

**Comment by arthropods** [comment]
https://www.youtube.com/watch?v=qaC0vNLdLvY

**Comment by ghost** [comment]
God bless for pulling through where glasseclipse failed. Soon we'll be able to construct entire factorio mining setups.

**Comment by ghost** [comment]
> God bless for pulling through where glasseclipse failed. Soon we'll be able to construct entire factorio mining setups.

Actually had this idea myself while playing factorio

**Comment by help-maint** [comment]
No, there is no way to automatically remove people from the scanner, nor any way to automatically clone people, or automatically eject from cryo (unless they eject themselves after 30 seconds).
This doesn't allow you to fully automate cloning, but it allows you to pretend you did.
Also the technology is now there for more conveyor_act()s, such as ashing cages when conveyed onto a shard

**Comment by APCUnlocked** [comment]
Now THIS is high speed medbay action.

**Comment by ghost** [comment]
> No, there is no way to automatically remove people from the scanner, nor any way to automatically clone people, or automatically eject from cryo (unless they eject themselves after 30 seconds).

Actually cryo tubes can with tier 3 scanning modules

**Comment by Blithering** [comment]
Now we just need the outflow from the mancrowave to lead into a suicide booth and the loop will be complete

**Comment by Kurfursten** [comment]
conveyor_act compatibility with guillotine would sadly leave uncloneable bodies

**Comment by GreatBigFailure** [comment]
I vow to make something stupid with conveyor_act() when this goes through.
Bless you for what you've done.

**Review by MadmanMartian — CHANGES_REQUESTED** [review]
You could absolutely babyjail somebody using a cryo tube and a conveyor belt.
Person self-ejects, has to lie on the floor due to celt-thermia (I presume you guys are still using that). Conveyor moves them towards the cryo tube, cryo tube puts them back in itself. Cycle repeats.

**Comment by Kurfursten** [comment]
You could also pull them out of the cloner without clothes or tools and put them behind a girder.

**Comment by MadmanMartian** [comment]
yeah, or handcuff them then stuff them in a locker and weld it.
But, at least you can actually see the game. Cryo baby jail is just a haze of darkness and you might as well exit as there's nothing better to do.

**Comment by GreatBigFailure** [comment]
The 50u sleep toxin pills medical starts with actually cause an OD that puts you in forever sleep as is. It's incredibly easy to round remove someone, even without killing them. We shouldn't balance new content around the potential to do so.

**Comment by help-maint** [comment]
`DNA modifier: grab | mouse | new
AAA modafier`

**Comment by BomberBro** [comment]
Strait jackets STILL can't be resisted out of

**Comment by help-maint** [comment]
```
DNA modifier: mouse | grab | new
locked_to       -   |  -   |  +
anchored        -   |  ?   |  +
animal/robot    -   |  ?   |  +
manifested      -   |  ?   |  +
occupant        -   |  -   |  +
robotquirk      -   |  ?   |  +
slimes          -   |  ?   |  +
msg             -   |  ?   |  +
stop_pulling()  -   |  ?   |  +
unlock_from()   -   |  ?   |  +

sleeper:      mouse | grab | new
locked_to       -   |  -   |  +
anchored        -   |  ?   |  +
animal/robot    -   |  ?   |  +
user not mouse  -   |  ?   |  +
occupant        -   |  -   |  +
robotquirk      -   |  ?   |  +
slimes          -   |  -   |  +
msg             -   |  ?   |  +
unlock_from     -   |  ?   |  +

cryo:         mouse | grab | new
locked_to       -   |  ?   |  +
anchored        -   |  ?   |  +
is silicon      -   |  ?   |  +
user not mouse  -   |  ?   |  +
occupant        -   |  -   |  +
panel_open      -   |  -   |  +
robotquirk      -   |  ?   |  +
slimes          -   |  -   |  +
unlock_from     -   |  ?   |  +
msg             -   |  ?   |  +
stop_pulling    -   |  ?   |  +
```

Sanity seems OK (author's note: to anyone who wants to add conveyor_act() to other machines, be wary of sanity oldcode you will have to nerve-wrackingly rewrite)

**Comment by help-maint** [comment]
PR is finished pending code review

**Comment by help-maint** [comment]
I tried adding something simple to change the exit location if there's a conveyor pointing towards us, but cryo is coded to never let you eject into its own tile, so there goes that idea. Probably won't be an issue either way, to be honest

**Comment by ghost** [comment]
> You could absolutely babyjail somebody using a cryo tube and a conveyor belt.
> Person self-ejects, has to lie on the floor due to celt-thermia (I presume you guys are still using that). Conveyor moves them towards the cryo tube, cryo tube puts them back in itself. Cycle repeats.

Nuggeting exists and so do many other "might as well close the game" situations. If someone abuses this to babyjail someone else then it's admins' duty to own them (assuming it wasn't justified).

**Comment by Exxion** [comment]
>You could absolutely babyjail somebody using a cryo tube and a conveyor belt.
Person self-ejects, has to lie on the floor due to celt-thermia (I presume you guys are still using that). Conveyor moves them towards the cryo tube, cryo tube puts them back in itself. Cycle repeats.

There are lots of ways to GBJ someone and this is both less practical and more funny than any others I can think of

**Pull request merged**
