### PR TITLE
Makes space not cold, but makes sunshine HOT

### PR DESCRIPTION
**Pull request by MadmanMartian**
while observing a prolonged argument in #ick over space being cold, I got bored and looked through the code.

Is_space_cold was a define that can be toggled, but it would mean that space is not as scary as it was (Was able to bust out of perma, and walk around the perimeter of the ship three times before succumbing to pressure damage, not heat-related damage)

So, I took a stab at making the sun a bit more terrifying and useful.

- Adds atom level proc for seeing if something is in sunlight
- Finds and unslaves the check_sun() human check from just being related to vampires

### Problems
- [ ] Now, if you step into space, you burn really quite quickly, even if you're in a hardsuit.
- [x] No way to predict the heat of the star. A suggestion from goldsteel would be an astronomer sub-job of scientist to identify characteristics of the star (Class, luminosity, heat, and maybe even have a pre-warning to stellar events)
- [x] Balance it
- [ ] This is a rather un-necessary level of tedium that detracts from gameplay because 'muh immulsions', so will require the server vote, or maybe even lock it behind hardcore mode.

### CODE REVIEW

**Comment by jknpj** [comment]
>Adds atom level proc for seeing if something is in sunlight

my hero

**Comment by Goldsteel** [comment]
Class and luminosity are fine. 'Heat' should be ambient radiation intensity for the orbital radius, based on the stars luminosity. For some level of realism, exposure to space without a spacesuit should _slowly_ give you minor radiation damage and additionally cool you down _slowly_ by black body radiation.

Bonus points: Anyone in space without mesons, proper space helmets or advanced welding goggles should observe https://en.wikipedia.org/wiki/Cosmic_ray_visual_phenomena perhaps as hallucinations with low probability as the 'sparks' effect.

**Comment by Aurx** [comment]
>stand in space
>burn to death from sun
>place lattice and tile at your feet
>cool down

This makes no sense unless we move the sun to be "behind" the station and rejigger solar panel logic.

**Comment by Goldsteel** [comment]
@Aurx 
Theoretically we could model a random polar co-ordinate for the suns position and translate accordingly, but it's far easier to say that the station rotates with one side facing head on towards the sun, two sides facing side on and one, for all intents and purposes, shielded from the sun.

Secondly, I get from a back of the cig packet calculation is that ~30 solar panels with an unknown specific height but approximate width of 2m (if we can assume a tile is 2m or the height of one spessman) and approximate height of 34m (ISS values) and an output of 80kW maximum from our solars means the ambient light intensity is ~1176W/m^2 which is a reasonable earth approximation. This varies on our solar panel size, but we can assume we're at an earth-like orbit and statistics about earths ambient radiation and other properties also apply to SS13.

What does this mean? It means that the average human with a surface area of 1.7m^2 is potentially exposed to ~2kW of heat whilst losing ~350watts (70kg, 37degrees human, water approximation, Stefan-Boltzmann). If our orbital radius is increased by ~2.2 times, the sun starts to lose over the human radiating heat and the spaceman freezes to death.

As before, these values depend on our orbital radius, star size, star class and if the human is wearing a hardsuit or not to protect him from the radiation with his lovely NT provided super effective spaceproof metamaterial equipment.

**Comment by Kurfursten** [comment]
I always wondered if there was a way we could make the sun light up the windows on the side of maint it's hitting. So for example, if the sun is north of the station it would light up the ghetto bar. I always thought it would probably be too costly or something since lights are not my forte.

Would be really interesting if we could do that though.

**Comment by Goldsteel** [comment]
@Kurfursten 
Plasma windows and plasma glass floors should light up slightly when exposed to an empty space tile to reflect the interaction (and sheilding) with radiation. I think regular windows should just act as standard shielding without the glow.

**Comment by Dacendeth** [comment]
vampires only dying to space tiles if it's in sunlight now seems interesting

**Comment by DrSnips** [comment]
Finally an award winning combo of radiation, heat, and pressure damage. You're effectively standing next to a super matter shard on each space tile.
I don't like the direction of this at all since it involves radiation damage that JUSTs you even after a few moments.

**Comment by MadmanMartian** [comment]
yeah, you're right. I don't even like thinking about playing with the game like this.

**Comment by Shadowmech88** [comment]
Is radiation damage really worse than the current cold damage? As long as the radiation isn't severe enough to knock you out, I feel like it'd be more survivable. Isn't one of the problems with the cold damage that the hypothermia causes you to pass out within a few seconds and then slowly freeze to death while unable to do anything?

**Pull request closed without merging**
