### PR TITLE
A little space pod love

### PR DESCRIPTION
**Pull request by brndd**
I heard space pods are being reworked by someone. Until that happens, here are some small numbers tweaks that I thought they needed. According to [the survey](https://imgur.com/zt58p5f) most people generally don't explore space, so maybe this will help slightly.

- The pod fabricator now builds them way faster (down from ~100 seconds to ~20 seconds on the basic parts; this should be about the same as the exosuit fabricator)
- They now emit light around them in a 1 tile radius
- They now have a toggle lights button to emit light in a 8 tile radius, consuming a little power (so don't forget to turn them off when disembarking!)
- They use 33% less energy to move around
- Added a new 'medium' speed
- Fixed a bug with constructing them not requiring any rods if you had fewer than the required 10
- Fixed a bug where the taxi pod was missing the speed button

:cl:
 * tweak: spacepods take much less time to build, consume slightly less energy when moving, emit light one tile around them, can turn on headlights to emit even more light (uses a little battery), and have a new medium move speed option
 * bugfix: space pods now properly require 10 rods to assemble
 * bugfix: the taxi space pod can now change its speed

### CODE REVIEW

**Comment by Intigracy** [comment]
Make the lights toggleable for an increase/decrease in power usage.

**Comment by brndd** [comment]
> Make the lights toggleable for an increase/decrease in power usage.

I thought about doing this but was too lazy to sprite a button. The existing buttons look like this, so if someone wants to make one that fits I have no qualms about adding a toggle for the lights. Though given the way the spacepod code works I don't know if I'm going to bother adding extra power usage to them (the code isn't really designed with passive modules in mind).

**Comment by MadmanMartian** [comment]
I think it might be me that was doing the pod rework?

This is pretty much the next step I wanted to go in.

The taxi pod is missing the gear shift button that regular pods have. Could you add that?

I'll sprite the light button in the meantime

**Comment by brndd** [comment]
Oh yeah, and the spacepod weapons cause a runtime whenever they're fired. I haven't taken a look at what could be going on yet, but if someone can figure it out in the mean time let me know: 

```
[17:16:20] Runtime in projectile.dm,542: Cannot read null.timestopped
  proc name: dumbfire (/obj/item/projectile/proc/dumbfire)
  usr: Alden Paulson (burneddi) (/mob/living/carbon/human)
  usr.loc: The reinforced floor (198, 225, 1) (/turf/simulated/floor/engine)
  src: the electrode (/obj/item/projectile/energy/electrode)
  src.loc: null
  call stack:
  the electrode (/obj/item/projectile/energy/electrode): dumbfire(1)
```

**Comment by MadmanMartian** [comment]
Looks to be some piss-poor code for some generic weapons fire. Does it runtime when it is fired, or when it collides with something?

Here's the sprite. Put it in pods/button_icons.dmi
pod_light

**Comment by brndd** [comment]
It runtimes when the taser projectiles collide with something. The lasers runtime too and don't work at all, but I don't think those can be acquired in-game.

```
[19:20:33] Runtime in beams.dm,236: Cannot read null.overlays
  proc name: dumbfire (/obj/item/projectile/beam/dumbfire)
  usr: Alden Paulson (burneddi) (/mob/living/carbon/human)
  usr.loc: space (249, 130, 5) (/turf/space)
```

**Comment by brndd** [comment]
If I wanted to make the lights drain power when active, what'd be the best way to do it? I see the spacepod code uses global_iterator datums for the air tank, so perhaps that would work for lights draining the cell too?

**Comment by MadmanMartian** [comment]
I'd say experiment with such if you're feeling confident.

**Comment by brndd** [comment]
Right, there's now a button to toggle the lights. The lights use 2 power per second when enabled. When disabled, the pod still emits light 1 tile outwards of itself as cabin glow. The taxi pod has all the relevant buttons now too.

**Comment by brndd** [comment]
As far as I'm concerned this is now done. Does anybody have any other (relatively) minor gripes with spacepods that could be put into this?

**Pull request merged**
