### PR TITLE
Portable (Buildable) Turrets can be loaded with a roulette revolver.

### PR DESCRIPTION
**Pull request by gurfan**
how many shots can your turret fire before blowing itself up? find out today!

[tweak]

:cl:
 * tweak: Roulette revolvers can now be placed in buildable turrets.

### CODE REVIEW

**Comment by djkramer123** [comment]
Oh no

**Comment by anunknownentity03** [comment]
Oh yes!

**Comment by ArchSunder** [comment]
the time for panic has come

**Comment by Manleto** [comment]
This is the single best idea I have ever heard in my entire life

**Comment by SonixApache** [comment]
This is the single worst idea I have ever heard in my entire life

**Comment by SageOfLight** [comment]
This is an idea.

**Pull request merged**
