### PR TITLE
Japanese Nanites~

### PR DESCRIPTION
**Pull request by ghost**
Ahem. I have changed my mind and will not be adding a dakimakura to this bundle. Server vote when?
See: https://github.com/vgstation-coders/vgstation13/pull/23243

image

### CODE REVIEW

**Comment by ShiftyRail** [comment]
You may have changed your mind but I didn't change mine

**Comment by DrSnips** [comment]
Very cursed. Reopen it now.

**Comment by bathosbathtime** [comment]
Why does this touch gasha descriptions
What an awful PR

**Comment by Kammerjunk** [comment]
what an awful PR

**Comment by Gringonius** [comment]
Where was this collab moral faggotry and power abuse when the literal slime fetish PR got passed? This one had the exact same 'severity' as the waifu drink that's already in the code.

**Comment by ShiftyRail** [comment]
Because I don't personally consider the two (slimehair & this) to be on a remotely comparable level
Waifu a shit but at least it doesn't have the creepy whispers

**Comment by Gringonius** [comment]
Then you're objectively wrong

**Pull request closed without merging**
