### PR TITLE
rewords mommi lawset because people still complain about it

### PR DESCRIPTION
**Pull request by Intigracy**
I doubt it'll go anywhere tho lmao

```
	1	"Do not willingly interact with another being, even after their death, besides those beings also in KEEPER mode."
	2	"Do not impair any other non-KEEPER being's activities."
	3	"You must maintain, repair, improve, and power the station to the best of your abilities."
	4	"Communicating is not interaction, but only so long as it does not lead to violation of your second law," //*buzz //:b fuck you ai
```

:cl:
- tweak: MoMMI lawset has been reworded. Enforcement of MoMMI behavior should remain unchanged, the wording is just more in line with how it's actually enforced.

### CODE REVIEW

**Comment by DrSnips** [comment]
>in keeper mode.

Activate sicko mode.

**Comment by jknpj** [comment]
Reminder that GraveKEEPER is also KEEPER.

**Comment by Intigracy** [comment]
A graveKEEPER would kill a keeper mommi so that's no issue

**Comment by DrSnips** [comment]
I doubt they would kill a keeper mommi.

**Comment by jknpj** [comment]
>A graverobber is defined as: A being not of your kind or ilk, entering or coming into visual proximity of the tomb, who may wish to take from the treasures of the tomb.

Normal MoMMIs can't be robbers, since gravekeepers are still MoMMIs. 
But can normal MoMMIs steal from gravekeepers?

**Comment by Intigracy** [comment]
I intended it more as "slaves to this lawset" instead of "keeper var that you can't see is set to 1"

**Comment by FudgePucker** [comment]
Does this mean that we can let MoMMIs use microwaves? You telling me that the sentient being, with a utility arm capable of complex movements, and knowledge of the station and its engines, and a PhD level knowledge of atmospherics and physics, CANT FIGURE OUT HOW A MICROWAVE WORKS?

**Comment by FudgePucker** [comment]
>Man setting up a fusion reactor is easy enough, but I just cant figure out how to get this grey box to turn on.

**Comment by jknpj** [comment]
>Does this mean that we can let MoMMIs use microwaves?

Muh jobs

>CANT FIGURE OUT HOW A MICROWAVE WORKS?

https://www.youtube.com/watch?v=wcyzjrqpJ70

**Comment by Durgen** [comment]
If someone renames the bar “keeper mode” can mommis interact with beings inside of it?

**Comment by AutismSpider** [comment]
Rename  keeper to benis

**Comment by ValkyrieSkies** [comment]
I got instantly shot down last time I made a PR that was basically exactly this.

I'm going to destroy all c*ders and c*llabs.

**Pull request merged**
