### PR TITLE
KITCHEN GUN!

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
[content]

## What this does
video
ADDS THIS TO SYNDICATE UPLINKS FOR 14 CREDITS, 10 FOR CHEFS AND JANITORS WITH NEW KITCHEN GUN!
THIS GUN HAS THE PROPERTY OF BEING ABLE TO REMOVE ANY DAILY STAIN AND DIRTY SURFACE ON THE TURF FIRED WITH JUST THREE SHOTS
* BANG!
* BANG!
* BANG!

AND IT SPARKLES LIKE NEW
COMES WITH SPECIAL KITCHEN GUN THEMED FIRING SOUND AND NIGHT VISION GOGGLES FOR AFTER DARK CLEANING!
MAKES YOUR VOICE YELLED LIKE A TELEVISION CLEANING PRODUCT ADVERTISER WHEN HELD IN AN ACTIVE HAND!

## Why it's good
LOOK HOW IT CLEANS THIS DEAD BODY SCENE!
* BANG!
* BANG!
* BANG!

WINDOWS FACING SPACE!
* BANG!
* BANG!
* BANG!

YOU CAN EVEN USE IT ON BLOOD STAINED ITEMS!
* BANG!
* BANG!
* BANG!

SHITCURITY ON YOUR TAIL!
* BANG!
* BANG!
* BANG!

THERE, ALL CLEAN AGAIN!

## How it was tested
GIBBING A MOB ON A TILE, THEN FIRING KITCHEN GUN! AT A DENSE OBJECT ON IT!

## Changelog
:cl:
 * rscadd: SAY GOODBYE TO DAILY STAINS, DIRTY SURFACES AND EVIDENCE OF A BLOODY SCENE WITH NEW KITCHEN GUN, FOR 14 TELECRYSTALS IN UPLINKS AND 10 DISCOUNTED FOR CHEFS AND JANITORS! COMES WITH TWO SPARE MAGAZINES AND NIGHT VISION GOGGLES FOR AFTER DARK CLEANING!

### CODE REVIEW

**Comment by west3436** [comment]
TEST YOUR CODE NOW AND I'LL EVEN THROW IN A FREE BONUS +1 REACT! DON'T WAIT, ACT NOW!
1MmOWJ3Q_400x400

**Comment by SECBATON-GRIFFON** [comment]
> TEST YOUR CODE NOW AND I'LL EVEN THROW IN A FREE BONUS +1 REACT! DON'T WAIT, ACT NOW! 1MmOWJ3Q_400x400

STILL WORKS LIKE NEW!

**Comment by west3436** [comment]
OOC: while the three shot thing is funny, it's already pretty difficult for a chef to obtain any form of ammunition, so I think most will just save their bullets for hard targets. Could you either give this a reagent buffer for cleaning mode or work out some other approach so they don't have to waste three bullets to clean a single tile?

**Comment by SECBATON-GRIFFON** [comment]
> OOC: while the three shot thing is funny, it's already pretty difficult for a chef to obtain any form of ammunition, so I think most will just save their bullets for hard targets. Could you either give this a reagent buffer for cleaning mode or work out some other approach so they don't have to waste three bullets to clean a single tile?

how does letting space cleaner refuel it for ammo sound, 10u per .380 bullet
either way, added 2 extra mags to cover this

**Comment by MercuriusGH** [comment]
does this fix broken microwaves?

**Comment by falcon2346** [comment]
Can we get a webm of this in action?

**Comment by Dacendeth** [comment]
the kitchen gun is modeled after a Beretta M9, which there is one of in the code, and not a glock though.

**Comment by SECBATON-GRIFFON** [comment]
> Can we get a webm of this in action?

added one now

> does this fix broken microwaves?

they don't use clean_act() so sadly not

**Comment by Eneocho** [comment]
Could make it so it shoots once but fires 3 bullets for the cost of one.

**Comment by Eneocho** [comment]
Toilet Grenade when?

**Comment by SECBATON-GRIFFON** [comment]
> Toilet Grenade when?

was debating this, and how to even implement it

**Comment by Eneocho** [comment]
>was debating this, and how to even implement it

Literally just make a grenade that explodes with mild damage (ideally no breaches) over a medium sized area, but also cleans a massive area. Say, you throw the toilet grenade in the middle of the bar, there's damaged wooden tiles around the grenade landing zone, but all the gunk/trash/etc gets cleaned.
Could alternatively work like a massive area pacid, it melts literally everything not bolted down, then cleans the pacid gunk (the limescale is gone bro).

**Comment by SECBATON-GRIFFON** [comment]
> > was debating this, and how to even implement it
> 
> Literally just make a grenade that explodes with mild damage (ideally no breaches) over a medium sized area, but also cleans a massive area. Say, you throw the toilet grenade in the middle of the bar, there's damaged wooden tiles around the grenade landing zone, but all the gunk/trash/etc gets cleaned. Could alternatively work like a massive area pacid, it melts literally everything not bolted down, then cleans the pacid gunk (the limescale is gone bro).

former sounds better

**Comment by Eneocho** [comment]
Also alternatively, it could explode into toilet shaped anvils, for strong area denial (plus cleaning the area, to remove the limescale).

**Comment by Eneocho** [comment]
Make it so the BANG screams do not pitch shift.

**Comment by SECBATON-GRIFFON** [comment]
> Make it so the BANG screams do not pitch shift.

i thought it sounded a bit more normal that way but if you insist

**Comment by PrimeDSS13** [comment]
I'd make it a beretta to make it more accurate to the original + actually worth the TC

**Review by west3436 — APPROVED** [review]

**Pull request merged**
