### PR TITLE
Taxi Fix 3: Straight to Video

### LINKED ISSUE #5472: (WEB REPORT BY: konater REMOTE: 198.245.63.50:7777) Taxistation robotics
Currently missing a cautery, disposal bin, proximity sensors, paper bin, bodybags, medkits for medibots. Only contains one stack of metal when it's the department that arguably eats the most of it during a round. Roboticists cannot enter the maintenance tunnel behind it either and have no very easy access to a fuel tank as a result

### LINKED ISSUE #5478: Ore belt in taxistation doesn't work properly
The conveyor corner leading to the unloader from outside is inverted. This is, if a crate comes from the start of the line, it gets pushed back when it reaches the corner.
The unloader still manages get the ores from it.

10 hours in paint

Now inside, the conveyor under the plastic flaps doesn't move at all, and it's needed to move a crate under the flaps or remove them to get the ores.

100 hours in paint

It might be late for the big taxi-fix, but taxi never wins the vote and the ore ~~processor~~ redemption machine wasn't kill back then.

### LINKED ISSUE #5492: MoMMI taxi nest isn't hooked up to the grid
Literally one wire off, in the middle of the two windoors that lead to space.
I also had an issue with a nameless item slamming into walls, but I don't know what caused that.

### LINKED ISSUE #5495: [Taxi] Tcoms
SMES doesn't appear to be interactable, might start with 0 charge? Also needs a suit so you can do maintenance without freezing.

### PR DESCRIPTION
**Pull request by Kurfursten**
- MoMMI nest now in the grid fixes #5492
- Ore belt directions/idtags repaired fixes  #5478
- Bioprinter added to Medbay (thread)
- Void Suit added to Tcoms, Tcoms SMES given terminal fixes #5495
- Bodybag Kit, empty medkits, 3 prox sensors, paper bin added to Robotics, Robotics maint door access adjusted fixes #5472
- Added a windoor to Robotics (thread)
- Newscasters given proper dirs
- Detective Office given coat rack (thread)
- Added RCD + ammo to CE office (thread)
- Added 2 very small fire closets (one on Engineering, one on Medical) so that each station would have one
- Removed an unlinked vent in Toxins
- Decrowded Toxins by moving the bhangometer one room north (thread)
- Fixed mailing to silicon/medical station. Previously, those packages would circle in space forever.
- Fixed mailing to the Head of Security's office
- Fixed mailing to the Quartermaster's office
- Added mail intake point to mining, allowing easy transport of minerals to the rest of the stations

Fully tested. My testing also turned up that large parcels do not get sorted properly, which is a code issue and not within scope of this PR (#5497)

This is my final PR to support Taxi for the foreseeable future.

### CODE REVIEW

**Comment by IratePirate** [comment]
I'd be happy to help maintain the map if more issues are noted.

**Comment by PJB3005** [comment]
Where is the bhangemeter now, is it next to an intercom?

**Comment by Kurfursten** [comment]
@IratePirate Thank you, please do

@PJB3005 It's not. On Taxi, the Bhangometer is out of range of the intercom for the room, and I thought that this may have been an intentional design decision, so I did not change it by adding an intercom.

**Comment by PJB3005** [comment]
It's possible that the bhangmeter not being next to an intercom is intended, it isn't on meta either but it IS on deff.

**Comment by Wizardcrying** [comment]
No camera in the MoMMI nest, should be fixed

**Comment by Kurfursten** [comment]
Ready to be moved to NFD I believe

**Pull request merged**
