### PR TITLE
Fixes (CA) href ; add a role panel shortcut

### LINKED ISSUE #19836: (CA) no longer checks antagonist in dynamic mode
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
8807e3dc60ec65f08ea3671d03a70b24bcba539c

# Description
(CA) in the special tab for admins no longer works for prayers or centcomm messages, i suspect across the board its borked
# Steps to Reproduce
get prayed at and smack (CA)
# What you Expected
antagu check
# What Actually Happened
denada

### PR DESCRIPTION
**Pull request by ShiftyRail**
Closes #19836 
Also add a link for role panel info
Yes it's unatomic but it's the same lines

### CODE REVIEW

**Comment by Exxion** [comment]
Holy shit these should really be using the document syntax
If they were, I could point you to exactly what failed

**Comment by ShiftyRail** [comment]
The document syntax, what do you mean ?
The compile failure is due to me not noticing a line and copypasting like a retard.

**Comment by Exxion** [comment]
The syntax the DM Ref calls the document syntax
`{"lol"}`

**Comment by DamianX** [comment]
I blame github for being useless, a different diff checker just works ™️ 
image

**Pull request merged**
