### PR TITLE
adds solanine version of plant-b-gone recipe

### LINKED ISSUE #16057: Getting Toxin
(WEB REPORT BY: seymourbutts REMOTE: 172.93.109.202:7777)
# Revision
4f0316c857c335cc03dfecfa274f5a5b0947b24b

# Description
Looks like since now botany has all these special snowflake chems that don't interact with the way their normal equivalent does, you can't make plant b gone because without medbay you can't get toxin
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by SonixApache**
Not sure if this fully resolves #16057 since there might be more toxin-related recipes. If there are, lemme know, I'll add them.

tested

🆑 
 - tweak: you can now make plant-b-gone with solanine

### CODE REVIEW

**Comment by SonixApache** [comment]
image
image
don't think i need to add it to the recipe specifically since it works with both toxin and it's plant-only equivalent

**Comment by Riekland** [comment]
changing it from "functions like" to "functions identically to" would be ideal
unless being vague is the intent

**Comment by SonixApache** [comment]
feel free to edit the wiki

**Comment by ghost** [comment]
Wiki's updated to include the alternative recipe in a way consistent with how it's shown on the drinks page (which is pretty inconsistent itself, probably need to update that)

**Pull request merged**
