### PR TITLE
Buildable shuttle turfs for custom shuttles

### PR DESCRIPTION
**Pull request by ghost**
[content]
Orderable from cargo in the DIY shuttle parts kit, (formerly known as DIY shuttle engine kit) price increased to 200 credits. Requires a shuttle license to be deployed in a custom area to use properly.
:cl:
 * rscadd: Deployable shuttle turfs can now be ordered from cargo

### CODE REVIEW

**Comment by SonixApache** [comment]
So what does this actually do?

**Comment by ghost** [comment]
> So what does this actually do?

Allows placing shuttle turfs (like in arrivals and escape shuttle) on areas designated as custom shuttles by the license from cargo.

**Comment by GreatBigFailure** [comment]
I think he's asking how shuttle turfs are mechanically different from a normal tile floor. While I've never gotten a custom shuttle to actually work I've been assuming all turfs within the designated shuttle area move with it, so that can't be the difference. Is it just aesthetic?

**Comment by ghost** [comment]
> I think he's asking how shuttle turfs are mechanically different from a normal tile floor. While I've never gotten a custom shuttle to actually work I've been assuming all turfs within the designated shuttle area move with it, so that can't be the difference. Is it just aesthetic?

Mostly done for aesthetics, yea.

**Comment by ghost** [comment]
Will do this in a better way some other day, not a fan of how I'm doing it. Will probably reopen if I end up prefering this one.

**Pull request closed without merging**
