### PR TITLE
Cryotheum Fixes

### LINKED ISSUE #36304: Air alarms temperature thresholds are all disabled
#### Description of issue

Air alarms are supposed to have temperature thresholds to raise alerts when a room gets too hot/cold, but these are all OFF on every air alarm:
image

I suspect something in #35365 has caused this

#### Difference between expected and actual behavior

They should have values

[bugfix]

### PR DESCRIPTION
**Pull request by ghost**
Cryotheum now operates properly in pipenets (this includes in pipes as well as canisters connected to a connector). 
Also while I was at it I slightly improved the temperature indicators for the atmospheric analyzer, pipe meter, and ghost "analyze air". It's not perfect but still better than before - shouldn't be telling you it's below absolute zero at least.

Also fixes #36304

🆑
* bugfix: Fixes gas reactions not working in pipes.
* bugfix: Fixes air alarm temperature thresholds being broken.
* tweak: Adjusts how temperatures are displayed on scanners (more precision at lower temperatures, so no more below absolute zero).

### CODE REVIEW

**Comment by ghost** [comment]
I guess I made this branch off of the compiler fix branch instead of Bleeding-Edge. That was merged though so shouldn't cause an issue, let me know if I need to fix it though.

**Comment by Eneocho** [comment]
Please add a changelog for the gas measuring and cryotheum bugfix stuff.

**Comment by Kurfursten** [comment]
While your wheelstation changes seem fine, I am curious why you didn't mention you did a map fix?

**Comment by Eneocho** [comment]
Those fixes are the same as the merged PR that fixes the compile issues with wheel and the hydro tools file (#36294). The man made the PR bugfixes on that branch instead of a branch of bleeding edge by accident.

**Comment by Kurfursten** [comment]
Right, that explains it

**Pull request merged**
