### PR TITLE
Fixes mimic spawning

### LINKED ISSUE #22964: Mimic spawns on cargo shuttle when it's not april fools
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/controllers/subsystem/supply_shuttle.dm#L212

Specifically says it only spawns on april fools, yet it had spawned today. I can't find anywhere else in code where mimics spawn on cargo shuttle.

[bugfix]

### PR DESCRIPTION
**Pull request by ghost**
Removes Z level 2 mimic near cargo shuttle.

[bugfix][box]

fixes https://github.com/vgstation-coders/vgstation13/issues/22964

:cl:
 * bugfix: Mimic can no longer appear on Box cargo shuttle when it's not april fools.

### CODE REVIEW

**Comment by ghost** [comment]
You're being dishonest with removing the bugfix part since https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/controllers/subsystem/supply_shuttle.dm#L212 clearly states it's only supposed to happen on april fools.

You can't even hold admins accountable for pushing the mimic onto the shuttle and bypassing logs, since pushing is not logged.

**Comment by Exxion** [comment]
That's a completely separate effect and you know it
You're removing something that was intentionally placed there, which is objectively not a bugfix
That doesn't mean it's an invalid change, and could certainly be considered an oversight, but it's not a bug

**Comment by ghost** [comment]
You're free to abuse your privileges as you see fit and there's nothing I can do about it but protest.

**Comment by Exxion** [comment]
Dude, I don't give a shit either way about the change
I'm just telling you what happened in the past and what the tags mean

**Comment by Kurfursten** [comment]
Codeungabunga is confused, he's not even looking at the correct PR

The mimic he's removing is one added as a feature in #16636 L12949 tgstation.dm

**Comment by ghost** [comment]
@Kurfursten

I don't see any intent from the author to kill cargo department on station.

**Comment by bathosbathtime** [comment]
If it kills me it's a bug

**Comment by KingofHONK** [comment]
coder

**Comment by MadmanMartian** [comment]
1. It's on more maps than just box
2. why

It's an extremely low chance to happen, through simply random AI interactions with one another, and only once a round.

You're more likely to have mimics appear from a random event

**Comment by kilozombie** [comment]
Hilarious PR, can't wait for April Fool's when we can merge it

**Comment by brndd** [comment]
is this what they call a \~reactionary\~ PR?

**Comment by ghost** [comment]
@jknpj

To reproduce, wait for the centcom mimic to get aggroed on an npc and get lured to the shuttle. You know this is how it happens but you choose to meme around and claim this is a great feature. Though I know you don't actually care about tag accuracy and only label as suits your interests with your powercreep tag spam.

The only result of this unintended behavior is random people being removed from round with no player interaction or fault of their own. Truly epitome of hilarity and good game design.

**Comment by SonixApache** [comment]
the tag is about you, not the PR

remember that other thread where i told you to stop being so snide
stop being so snide

**Comment by ghost** [comment]
@SonixApache

I have a better idea, I'll just not provide feedback and bugfixes for you.

**Comment by MadmanMartian** [comment]
good lord he ghosted

**Comment by Exxion** [comment]
A never-before-seen level of playing oneself

**Comment by SonixApache** [comment]
Sad!

**Pull request closed without merging**
