### PR TITLE
Improves mining crew morale

### PR DESCRIPTION
**Pull request by Gringonius**
for all maps but roidstation.
I'm trying out my first mapping-related PR, hoping this won't fuck anything up. 

:cl:
* tweak: Dave has decided to visit mining stations other than Roidstation.

### CODE REVIEW

**Comment by DrSnips** [comment]
You could use a changelog and a bit more in the OP on what this PR actually does.

**Comment by Gringonius** [comment]
I deleted the instructions for changelog formatting so I hope that's enough.

**Comment by Durgen** [comment]
screens?

**Comment by Gringonius** [comment]
dave

**Comment by ShiftyRail** [comment]
On the one hand, Dave is a good boy
On the other hand, he was supposed to be a R*id station exclusive

**Comment by ghost** [comment]
So were Survivor Suits, and we all know how that went.
I think it'd be just fine adding him to every station, but Shifty does have a point, I suppose.

**Comment by SonixApache** [comment]
>build station around a roid that some friendly alien showed you
>declare him station mascot and celebrated hero
>he gets cloned and thrown onto other mining stations for corporate reasons

sad

**Comment by Durgen** [comment]
such is the nature of space capitalism

**Comment by GeneralVeers25** [comment]
I personally am gonna thumb this down. I guess I'd _kinda_ be okay with it if you were adding Dave enclosures to the Asteroids but dumping him in the break rooms feels soulless.

#FreeDave

**Comment by Gringonius** [comment]
Isn't that how it is in roid? I always find Dave in the middle of a hallway or in the bar there.

**Comment by Gringonius** [comment]
Making another version of this PR since it involves a little bit more than just copy pasting dave.

**Pull request closed without merging**
