### PR TITLE
- tweak: Adjusts the new nuke sprite, making it look old and faded.

### PR DESCRIPTION
**Pull request by Intigracy**
As always, this gif is much slower than it appears ingame. The last one is rapidly blinking.

### CODE REVIEW

**Comment by clusterfack** [comment]
I like the colors a bit better but you took away some of the details

**Comment by Intigracy** [comment]
I can put those two gray spots back, I just had no idea what they were and without fading them down they clashed really bad.

**Comment by clusterfack** [comment]
I don't know what they are either :shrug:

**Comment by Intigracy** [comment]
I can change it and put them back in with faded color, if you want.

That's the only part of the sprite I actually edited rather than just color changed.

**Comment by Exxion** [comment]
Looks better, but I still have one issue with it
The brown stripe near the front of it looks less like a stripe straight around a circular thing and  more like a straight stripe around a rectangular thing
Or in other words, rather than a smooth curve, it appears to be two straight lines

**Comment by SangriaMonkey** [comment]
Why does it glow when activated?

**Comment by Probe1** [comment]
get the players opinion on this so we don't have to do it all again

**Comment by Intigracy** [comment]
It glows right before it explodes.

**Comment by ghost** [comment]
Dump the cartoony glow when it's about to explode and we're golden

SS13 has a grim but clean theme, and big bright outlines break that theme

**Comment by gbasood** [comment]
> get the players opinion on this so we don't have to do it all again

They liked it the first time they were polled, before this PR

**Comment by ghost** [comment]
The top needs more shading. Right now it looks rectangular.

**Comment by clusterfack** [comment]
Well this seems like an improvement, if anyone else wants a go at it they can feel free

**Pull request merged**
