### PR TITLE
Revert "Revert "Make the blast cannon a bit better""

### PR DESCRIPTION
**Pull request by yackemflam**
Reverts vgstation-coders/vgstation13#25945

You should've made a poll in the actual server to keep it or not first

### CODE REVIEW

**Comment by bathosbathtime** [comment]
It was an experimental merge. Those are supposed to be reverted at a set date. The date was even extended to ensure the change was actually used, but not extended indefinitely.
Now that we have had it in the game experimentally, however, it is perfect for a server poll to add it in proper.

**Comment by boy2mantwicethefam** [comment]
Your ban appeal should be finalized within the week, I've already discussed the matter with the headmin.
>I take it he was agreeable?

He didn't really have a choice.
>Did he make a PR?

Ah yes, most certainly. When I mentioned we could close down his PR and ban him from the repo, he was so willing it was almost pathetic.
>These changes, the rioting is intensifying to the point we may not be able to contain it.

Why contain it? Let the complaints spill over to the threads and forums, let the tears pile up in the Discord. In the end, they'll beg us to merge their PRs.

**Comment by 9percents** [comment]
>alright, I saw the blast cannon
>it works like an explosive railgun, I dislike it, give me an explosive tube back

copy of my opinion on the blast cannon from the revert PR

**Comment by KingofHONK** [comment]
It WAS kinda weird how this PR was handled. It was merged as experimental, then what seemed like 2 days later (not going back and checking) a revert for it is put through, and it was never really voted on? Shady shit bro, shady shit. Havent seen any other PR handled like this. not even the vector ones.

**Comment by DamianX** [comment]
shady shit bro

**Pull request closed without merging**
