### PR TITLE
Literally just flat halves all laser damage

### PR DESCRIPTION
**Pull request by MadmanMartian**
:cl:
 * tweak: All laser damage is halved.

### CODE REVIEW

**Comment by Goldsteel** [comment]
Whilst I agree that lasers do do a lot of damage, my issue here is that people will still just use ranged stuns and then execute with whatever weapon they decide upon. Reducing the laser damage doesn't really fix this problem. An e-gun is 30 damage, so 4 shots is a crit, unless you're a poor diona then it's 2. Reducing that damage to 20 from 30 would require 5 shots, not 4, to score a takedown on an unarmoured opponent. A flat 15 would mean 7 shots, so you might need to recharge even before someone is dead. There's 10 shots in a normal laser.

Bullets are now far more viable since the bullet speed buff, but lasers still travel instantly. My personal opinion in this matter is that lasers should do significant amounts of damage to unarmoured targets but little else to armour, as the laser just ablates more material from the surface. I don't think this should reduce the laser damage, though.

**Comment by ghost** [comment]
This does not address any mob balancing issues that will result from this, neither does it give any reasoning of what issue it is trying to solve.

**Comment by Durgen** [comment]
This pull request will induce people to carry the armory in their backpack

**Comment by DeityLink** [comment]
Alright then bring back double laser damage to xenos.

**Comment by DeityLink** [comment]
That aside, surely people in this community can balance stuff with middle grounds between "let's double this thing's damage/speed" and "let's halve that thing's damage/speed".

Like, why not decrease damage by 5, 10, 15, 20% etc, instead of directly 50% ?

**Comment by iFlashYou** [comment]
At least you should increase the ammo capacity of all laser weaponry.

**Comment by Accipitermaris** [comment]
I think [#20793] was a far more versatile solution to the topic of laser dominance, however since that was already shot down, I'm not really sure what to suggest.

As said by others, the damage output of lasers are (currently) a necessary evil in relation to Blobs&Xenos, foes which shrug off ballistics as if you spat on them, and a similar situation is true of the many simple mobs who are quite speedy and/or do a lot of brute damage in baymed.

**Comment by ShiftyRail** [comment]
I'd rather have the window thing, it's better for immulsions than >projectile lasers

**Comment by Sooose** [comment]
A slight nerf might be good but this has too many wide reaching implications. There's no way blob could lose with this change as is.

**Comment by mtpowell** [comment]
This is the joke PR, the real one is #21595 
See, if you give people the illusion of choice.. 
@MadmanMartian  is a genius.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It's pretty sneaky tbh especially with no prior discussion and it reeks of our streak of kneejerk nerfs/removals

**Pull request closed without merging**
