### PR TITLE
Ports Butterfly Knife from Hippiestation

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
**Available for 8TC**, deals **an additional 40 armor-penetrating damage to targets** if **you stab them in the back**, but otherwise deals 10 damage only. People will know if you slip up and tried to backstab them. Grab this if you feel you're brave enough to use this over the consistently 30 damage e-sword.
**Has an unique backstabbing sound and unique hit sound**
The oversight of having a wider area to backstab if the target is facing left or right is intentional because TF2 also has an oversight where a target's back is angled and it's better to backstab from there
Added miss sound functionality, where an item can now play a different sound if the attack fails to connect. Currently disabled for non-heavy-butterfly-knives

:cl:
 * rscadd: Added the Heavy Butterfly Knife, available for 8TC from a traitor uplink. Please backstab people with it.

### CODE REVIEW

**Comment by GreatBigFailure** [comment]
But we already have a butterfly knife

**Comment by boy2mantwicethefam** [comment]
I know but this is cooler

**Comment by BomberBro** [comment]
should be a bus item, little too on the nose as a reference imo

**Comment by d3athrow** [comment]
hipppie is agpl. did you get permission to port this under the gplv3 license?

**Comment by DrSnips** [comment]
Let's rephrase that. We already have an established butterfly knife. Why isn't this a child of or better yet built into the functionality of the parent? This seems like you just being too lazy to fit it in properly.

**Comment by boy2mantwicethefam** [comment]
i made it known in the hippie discord that ill take em, should i grab official pics?
@DrSnips mostly because they have an entirely separate functionality (create enemies), ill look into it tomorrow

**Comment by DrSnips** [comment]
We have a basic black (parent), the visc. red/black (a child), and crystal (another child). Put some of this code into the existing parent which already has 90% of your code (folding and etc). All you need to keep is the backstab proc.

**Comment by d3athrow** [comment]
@boy2mantwicethefam you need to find the original author and ask them and retain logs of such approval.

**Comment by Kurfursten** [comment]
As far as I can tell this does 2 discrete attacks: an initial parent call of attack (for 10 force) then backstab of 70. 80 damage feels comically high to me. Always hitting the chest with backstab damage regardless of where you target is... weird behavior. Maybe it should only try to backstab if you're actually aiming at the back? it is very odd to do 10 to the head and 70 to the back for a 'backstab'

To see how extreme an 80 force weapon (this is, mind you, nearly 3x an esword), I did testing. It did consistently 95 brute + bleed+ internal bleed + broken chest to sec officers in both sec vest, sec rig, and even on full riot armor, this was usually the outcome (because of how armor code works, the higher the incoming damage the less chance of blocking any), although once the riot armor was able to stop some of the damage (resulted in only 40+bleed). The knife inhand is very small and looks like a crayon to me: it doesn't scream "this will kill you instantly" like an esword does with its glow and sound.

I am sure the reply to all this will be "you could just get parapenned" (note: Esword and parapen are each 25% more expensive than this), but you can keep depopulating with this as much as you like instead of one use on a high value target - and unlike a parapen there's no delay where they can try to scream. At only 6TC(!!) you have 14 left to pick up loud equipment for when someone does catch on.

**Comment by boy2mantwicethefam** [comment]
What do you suggest the damage should be? I'm willing to go for 40-50 backstab damage and 8TC cost, armor penetration of the backstab is intentional
Also do not merge this until I actually find a way to contact the original author for permission

**Comment by Kurfursten** [comment]
I'm not 100% sure where we can land this where it feels good to the user and fair to the victim. The whole point is that it's "Surprise, you're dead". If it doesn't set them up to be finished in a few seconds, why not use a fast-knockout like chloral or parapen or just ebow+esword? On the contrary, if it's high enough that it instant crits them, that sucks too. I think this falls into the same realm as Deity's medigun concept from years ago. This is a weapon specifically designed to be in a team-based shooter game: one where you regularly shoot at teammates to "spy check" them because failure to do so is instant death. And like the medigun, I'm not sure it's the right fit here - I could be wrong on this, but it's my gut feeling.

One part that I think may be a sticking point is how not-deadly it looks. I get the point is to be subtle, but one thing I learned from my most-heckled and infamous syndicate murderbone item is that dangerous things should be visibly dangerous. That's why we eventually made the murderchair red after a lot of feedback, and that's why the esword has the iconic glowing appearance.

**Comment by boy2mantwicethefam** [comment]
the knife is very very conspicuous when you backstab someone with it
I'm gonna go for 40 backstabbing damage
And to be fair the kill is instant in TF2

**Comment by BurntDevil** [comment]
this isnt tf2, the way they balance things is irrelevant.

**Comment by tuypo1** [comment]
>how dare traitors actually be given a weapon that is worth the price

**Comment by boy2mantwicethefam** [comment]
It's safe to say that the code is different enough that licensing is no longer an issue, as sprites fall under Creative Commons

**Comment by BomberBro** [comment]
> > how dare traitors actually be given a weapon that is worth the price

Alright, I'll bite. If 6 TC is, at minimum, worth an item that does 90 brute with internal damages with infinite use, what the fuck do you put for the other items. What's worth 20, an immediate "I win" button?

**Comment by boy2mantwicethefam** [comment]
it's 8TC and deals 40 additional damage on backstabs only

**Comment by anunknownentity03** [comment]
could you rename the vicerator butterfly knife to avoid confusion?

**Comment by tuypo1** [comment]
>What's worth 20

an instagib laser

**Comment by GreatBigFailure** [comment]
Have damage depend on location is really interesting but I think you need to change the effect a bit. 80 damage was ridiculous. 40 damage is in my opinion probably fine considering eswords and eguns. 
Just having it be damage seems a bit lame considering the fun backstab mechanic. Like you'd stab someone once and they'd either fall over and now it might as well be an esword or they wouldn't and you wish you did ebow esword. I'd say give it some other effect that might result in the one shot kill but isn't just instant death they can't fight back from. Depending on that effect reduce the damage accordingly. Like we already have esword as the boring "Hit man he die" option.

**Comment by boy2mantwicethefam** [comment]
@GreatBigFailure if they fall over you can't backstab them, I'd say you can get a backstab or two on someone before they turn around and the damage hurts. 
Not sure what effect I could give butterfly knives and I don't want to give it any RNG as funny as it would be to have a message saying "You try to backstab but you stab them instead, fucking hitbox!"

**Comment by GreatBigFailure** [comment]
That's the issue though, at super high damage they're unfair and unfun for the person being stabbed. At reasonable damage they're fun but in my opinion not as useful/desirable as alternatives. 
Just off the top of my head what if instead of bonus damage the backstab caused stupid high bleeding? Then they still have a chance to fight back or run for help rather than "boop your shift is over" and the weapon is still effective. 
Again, top of my head thing but that's generally what I meant by additional effects.

**Comment by KingofHONK** [comment]
At least its not as boring as an esword, but still pretty boring.

**Comment by GermanSanta** [comment]
This actually is pretty cool. You might want to show screenshots of it, or perhaps a video of it in action to get more support. So you don't simply get the from hippie = bad votes.

**Comment by boy2mantwicethefam** [comment]
Went from "I hate this because this is too strong please nerf" to "I hate this because this is too weak"

**Pull request closed without merging**
