### PR TITLE
Food temp fixes & warm pizza

### LINKED ISSUE #35663: NT Lunchboxes Not Insulated
(WEB REPORT BY: dilt REMOTE: 209.222.101.3:7777)
# Revision
37fe9d03a91ce7acd84acce4f8d82c74c0e3d7f8

# Description
The Food Delivery Bags maintain temperature regulation of food, but the delivery bags do not.

### LINKED ISSUE #35664: Plated Food does not Steam
(WEB REPORT BY: dilt REMOTE: 209.222.101.3:7777)
# Revision
37fe9d03a91ce7acd84acce4f8d82c74c0e3d7f8

# Description
If you put steaming hot food on a plate, it will stop being hot and steamy.

### PR DESCRIPTION
**Pull request by DeityLink**
Fixes #35664
Fixes #35663

:cl:
* tweak: Lunchboxes, Pill Boxes and Pizza Boxes are now thermally insulated just like Food Delivery Bags.
* rscadd: Pizza ordered via cargo is now frozen.
* bugfix: Fixed food getting a bit colder when put on a plate.
* bugfix: Fixed eating food between 30 and 50 degrees causing your body temperature to rise above 400 degrees.

### CODE REVIEW

**Comment by wotisjanitor** [comment]
There should be a small chance that an cargo order with pizza can have a timer of 30 minutes, in which case the order is refunded.

**Comment by DeityLink** [comment]
By hilarious request, cargo pizza now spawns frozen rather than pre-heated.

**Comment by Kurfursten** [comment]
Frozen cargo pizza is great, I just wish there was an obvious way to heat things up that won't make a burned mess.

**Comment by DeityLink** [comment]
There's the microwave for one, and using a lighter/welding tool "might" work as well. And if nothing else, blowing room temperature air on it will work eventually.

**Pull request merged**
