### PR TITLE
Revert "Civil war of casters faction conversion of crew"

### LINKED ISSUE #34391: Wizard Conversion Spell SUCKS!
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
62635ef2fcd070eeaa6b51eeeb27ca64c274e4e7

# Description
The spell must not give converted minions a message as both wizards on a team with fellow red crewmembers were deliberately teamkilled. Haven't tested it, but I presume converted crewmembers receive no message telling them "DON'T KILL THE WIZARD THAT IS THE SAME COLOR AS YOU"
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by gurfan**
Fixes #34391 
Reopening this yet again since it has been over a week, like Kurfurst said. 
The spell sucks and shouldn't have been added.

bernie-sanders-financial-support

### CODE REVIEW

**Comment by nervere** [comment]
This spell sucks so much. It has literally never been fun. One of the wizards died and we all suddenly lost our antag status, no message in chat or anything. You are permanently the color of the guy who converted you even after losing antag status.
Who thought that was a good idea? Why must we keep fixing the 10,000 oversights of this God-awful spell? Just remove it.

**Comment by gurfan** [comment]
image-14
The jectie it gives you doesn't even say anything about supporting the wizard that converted you. It's just the survivor jectie.

**Comment by tinysaturn** [comment]
Why the fuck did I lose my HUD that showed me who my minions were when I got cloned
Why the fuck is the minion jectie the same as the survivor/magician/summon gunk one and not something about following the master

**Comment by nervere** [comment]
> image-14 The jectie it gives you doesn't even say anything about supporting the wizard that converted you. It's just the survivor jectie.

Every single part of this code screams zero effort. Christ.

**Comment by Exxion** [comment]
God why did we add an actual unironic TDM mode

**Comment by Kurfursten** [comment]
Going to give this one a few days. Personally I dislike the convert spell with you but I want to give any supporters it has a few days to come out of the woodworks if they want to.

**Comment by pedr69** [comment]
LIFE OR DEATH FOR KANEFBOY?

_Originally posted by @tinysaturn in https://github.com/vgstation-coders/vgstation13/issues/34268#issuecomment-1544169560_

**Comment by Inorien** [comment]
in its current form its shit

it looks like no edge cases (and relatively few normal cases) have been considered, maybe with some more work it'll be usable but lmao @ whoever picks that up

**Comment by ShiftyRail** [comment]
Conflicts, I would solve them if you allowed me to update your PR

**Comment by Kurfursten** [comment]
Fix conflicts for merge

**Comment by Kurfursten** [comment]
Fix conflicts

**Pull request closed without merging**
