### PR TITLE
fixed de-powered rechargers stealing your weapon

### LINKED ISSUE #5677: Can't Pull Gun Out of De-Powered Charger
Not sure if it's relevant, but the power cut out while the gun was already charging.

### PR DESCRIPTION
**Pull request by Intigracy**
Fixes #5677

### CODE REVIEW

**Comment by N3X15** [comment]
Changelog

**Comment by Intigracy** [comment]
Done.

**Comment by Intigracy** [comment]
Added changelog, fixed it having your name (oops)

**Comment by N3X15** [comment]
Travis is being a shit, so merging.

**Pull request merged**
