### PR TITLE
Fixed degenerate calcium affecting robotic or peg limbs

### PR DESCRIPTION
**Pull request by DamianX**

### CODE REVIEW

**Comment by Exxion** [comment]
This was deemed a feature in the original PR

**Comment by DamianX** [comment]
oh

**Comment by DamianX** [comment]
Well, it makes no sense but if people want to keep this I don't feel particularly strongly about it.

**Comment by Exxion** [comment]
Oh I don't care either
The label was just wrong

**Comment by Intigracy** [comment]
Do you have a link to the original PR by chance?

Edit: nvm https://github.com/vgstation-coders/vgstation13/pull/20041

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It was so people can't just cheese the downside with robot limbs, but you can cheese it anyways through other means so whatever

**Comment by Intigracy** [comment]
Also this still breaks robotic limbs the way it is due to the below else if

**Comment by DamianX** [comment]
I just assumed `fracture()` would do nothing for robotic limbs but apparently this is not the case

**Comment by Intigracy** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE did you actually not want this fixed?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I don't particularly care  ¯\\_(ツ)_/¯
If the playerbase deems breaking robot limbs stupid then so be it

**Pull request merged**
