### PR TITLE
Servbots

### PR DESCRIPTION
**Pull request by NigglyWiggly**
Added Servbot icons for borgs, one for each module except combat, which has two.

ss 2015-04-06 at 12 51 38

### CODE REVIEW

**Comment by wwjnc** [comment]
I love you.

**Comment by ComicIronic** [comment]
Not so sure about the colour-scheme, myself.
Any screenshots against a station background?

**Comment by NigglyWiggly** [comment]
research construct charlie 2015-04-06 125515

The one on the left has its cell taken out.

**Comment by PJB3005** [comment]
:+1:

**Comment by clusterfack** [comment]
I need dis

**Pull request merged**
