### PR TITLE
Bomb suit is spaceproof, nerfs advanced EOD suit

### PR DESCRIPTION
**Pull request by boy2mantwicethefam**
What's the point of supposedly resisting an explosion if you don't survive the hole it leaves
Also halves melee, bullet, and energy armor values of the advanced bomb suit as a trade-off
:cl:
 * tweak: Bomb suits are now spaceproof
 * tweak: Advanced bomb suit from R&D has halved melee, bullet, and energy armor values.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
For info, bomb resist does nothing. It's just to prevent you from being gibbed.

**Comment by boy2mantwicethefam** [comment]
I know

Nobody:
Test_box.dmm: 
maps/test_box.dmm:8016:error: undefined type: /obj/item/clothing/head/advancedeod_helmet
maps/test_box.dmm:8016:error: undefined type: /obj/item/clothing/suit/advancedeod
maps/test_box.dmm:8016:error: unknown type
maps/test_box.dmm:8016:error: unknown type

**Comment by SonixApache** [comment]
yes, make it so science can freely print armored spacesuits

what the fuck dude

**Comment by plosky1** [comment]
Maybe more resistance to pressure than it currently has, but not as much as a regular space suit if that's a variable you can edit.

No cold resistance.

**Comment by SonixApache** [comment]
Sadly, pressure resistance damage is basically binary; if you go one micropascal over your pressure limit, you take full damage.

**Comment by Blithering** [comment]
The one thing science can't currently get in large quantities is good spacesuits, they keep trying to sneak in ways to change this though. Be vigilant!

**Pull request closed without merging**
