### PR TITLE
Radio message sounds (and player prefs for them)

### PR DESCRIPTION
**Pull request by ghost**
[sound]

I made the sounds for this months ago and only decided to code this now
Three types of pref:

* "Never" is the default, never hear these sounds
* "Departments only" makes these appear from every radio channel except common
* "All" makes this appear in all radio messages

Don't know if SQL stuff needs secret repo stuff to work, but insert/update/whatever errors are gone now, just needs a review

:cl:
 * soundadd: Players can now hear radio messages from others if they choose to

### CODE REVIEW

**Comment by TGFH** [comment]
I've wanted something like this for a while. What sort of sound do you have in mind, something like a radio chirp or a burst of static?

**Comment by jwhitak** [comment]
From what I'm hearing when talking about this PR to other folks, there may be issues with the sfx used for this PR. Common comms are usually heavier than the nearby chatting, so the currently-used-in-PR sfx will overlap often and basically be very spammy (even though it's basically the same one that's used for nearby voices but with a radio overlay). There's been recommendations for using a similar, shorter radio sfx (mainly to indicate someone's chatted on radio at all, so a short <1sec clip would be sufficient). Like a beep, radio clicking in and out, or similar.

That said, thumbs up. We can change the sfx if needed! Giving people *the option* to hear a radio message is great. Good work.

Edit: The sfx are in the PR, you can download the 5 ogg files directly and listen to them.

**Comment by ShiftyRail** [comment]
After hearing the samples, it's absolutely indispensable to add additional constraints to this. (in my opinions)
Make it play on a timer, once every 8 messages, or once every 30 seconds, else it's just not worth having it

Make sure to check if the channel used to play that sound is free before sending it, or else clients will have stacking earrape waiting for them

**Comment by ghost** [comment]
> After hearing the samples, it's absolutely indispensable to add additional constraints to this. (in my opinions)
> Make it play on a timer, once every 8 messages, or once every 30 seconds, else it's just not worth having it
> 
> Make sure to check if the channel used to play that sound is free before sending it, or else clients will have stacking earrape waiting for them

Ideally I want to do this if it detects the same person talking as another radio message within that time frame, like with talking sounds in general

**Comment by Apogee-dev** [comment]
> > After hearing the samples, it's absolutely indispensable to add additional constraints to this. (in my opinions)
> > Make it play on a timer, once every 8 messages, or once every 30 seconds, else it's just not worth having it
> > Make sure to check if the channel used to play that sound is free before sending it, or else clients will have stacking earrape waiting for them
> 
> Ideally I want to do this if it detects the same person talking as another radio message within that time frame, like with talking sounds in general

i'll be honest, man. even if you take measures to space them out and even after all the editing you've done with them, the charlie brown voices are just too obtrusive to be hearing all round over the radio. these voices work for spoken chat precisely because they stick out a bit and call attention to the fact that somebody's right in front of you and talking to you. It's not just the possibility of overlap that's the issue when carrying them over to radio. Please consider using different sounds entirely.

**Comment by Theophrastus1** [comment]
man makes me miss the lfwb static noise for radio transmissions. Would be nice to see it implemented

**Comment by Kurfursten** [comment]
Since you haven't made progress on this in 3 weeks and are doing other projects I am temporarily closing it.

If you make a push to this branch or message me, I will reopen it for you.

**Comment by ghost** [comment]
> Since you haven't made progress on this in 3 weeks and are doing other projects I am temporarily closing it.
> 
> If you make a push to this branch or message me, I will reopen it for you.

Yeah sorry other stuff kinda got in the way

**Pull request closed without merging**
