### PR TITLE
man-portable mecha weapons

### PR DESCRIPTION
**Pull request by SonixApache**
I started this on may 25th 2017 and I doubt I'll ever finish it but maybe if I put this up and people bug me about it I'll be more motivated to finish it

TODO: 
 - [ ] initial desc for de-conversion
 - [ ] Delete rogue code 
 - [ ] Make it work for all ballistics
 - [ ] Unfuck launchers causing runtimes
 - [ ] Make it work for all launchers
 - [ ] Make it work for energy weapons
 - [ ] Make it work for ALL energy weapons
 - [ ] Convert Gatling gun to a mecha-attachable weapon
 - [ ] Special weapons like the grav catapult?
 - [ ] Tools like the RCD?
 - [ ] ICONS

### CODE REVIEW

**Comment by Durgen** [comment]
lmao

**Comment by ghost** [comment]
How will these be powered?

**Comment by jknpj** [comment]
haha, time for get_cell()!

**Comment by SonixApache** [comment]
I figured I'd leave recharging out. Stick it back on a mech when you're done with it.
Though that's not how it works in my inspiration source, so maybe I'll `get_cell` or whatever.

**Comment by FudgePucker** [comment]
Wait is this to turn mecha weapons into normal useable in hand weapons? Or the other way around?

**Comment by Blithering** [comment]
screw man portable, mech weapons as emplacements when

**Comment by SonixApache** [comment]
It's to make mecha weapons into man-portable weapons. Carrying around and firing a scattershot and such.
As for emplacements, we have literally no code for it.

**Comment by FudgePucker** [comment]
This would give science even more guns.
Black list the HONKER BLASTER and add NT research to it at least

**Comment by tuypo1** [comment]
This seems like too much to me.

**Comment by RealestEstate** [comment]
we lost planet now?

**Comment by Kurfursten** [comment]
You can request this reopened if you want to work on it

**Pull request closed without merging**
