### PR TITLE
Invisibility Spray Delay + examine to see if used

### PR DESCRIPTION
**Pull request by gurfan**
## What this does
Adds a two second delay to apply invisibility spray.
Lets you examine invisibility spray to see if the can has been used

## Why it's good
You will no longer accidentally spray your backpack for the fifteenth time. 

## Changelog

:cl:
* tweak: Invisibility spray now takes a couple seconds to apply.
* tweak: You can examine a can of invisible spray to see if it was used.

### CODE REVIEW

**Comment by DamianX** [comment]
The classic blunder. I'm pretty sure you made it possible to spam-click to queue multiple progress bars, so that you can spray many more items than you have uses.

**Comment by adacovsk** [comment]
the supermatter range should be at least 3 I think? you can get rad burns from pretty far away... I've died from Eneocho's autoharvest machines from like 5 tiles away

**Comment by gurfan** [comment]
> the supermatter range should be at least 3 I think? you can get rad burns from pretty far away... I've died from Eneocho's autoharvest machines from like 5 tiles away

I didnt change the radiation range at all. The radiation message was being duplicated for every person in the area and that is also fixed.

**Comment by adacovsk** [comment]
Oh, `visible_message` should have range=10, but if you're going to loop through each person, it should be `to_chat` right? Also you duplicated the "can is empty" logic

**Comment by gurfan** [comment]
> Oh, `visible_message` should have range=10, but if you're going to loop through each person, it should be `to_chat` right? Also you duplicated the "can is empty" logic

>it should be `to_chat`

yeah it should but theres a special message for blind people and i didnt want to spend more than 10 seconds fixing an unrelated bug

>Also you duplicated the "can is empty" logic

intentional

**Comment by adacovsk** [comment]
> intentional

Can you put a comment on each change because it's not self-evident and if some idiot like me saw it, I'd want to change it

**Comment by DamianX** [comment]
It's a very common pattern throughout the codebase. `do_after` and similar force you to write code like that. A comment wouldn't hurt, I guess.

**Comment by Eneocho** [comment]
> > the supermatter range should be at least 3 I think? you can get rad burns from pretty far away... I've died from Eneocho's autoharvest machines from like 5 tiles away
> 
> I didnt change the radiation range at all. The radiation message was being duplicated for every person in the area and that is also fixed.

Weird thing is that at first all the messages for radiation are ok. It just says that the item got ashed by the shard. After some unknown amount of ashings however it starts displaying the "radiation burns cover your body" message, even if you are wearing a radsuit.

**Pull request merged**
