### PR TITLE
Revert "Meme disease type is now admin-only. Fungii can only appear in random dishes."

### PR DESCRIPTION
**Pull request by DamianX**
Reverts vgstation-coders/vgstation13#25936

3 days

### CODE REVIEW

**Comment by DrSnips** [comment]
:+1: for maintaining standards for collaborators. I do support the changes regardless but I think we should hold it to the standards.

**Comment by DeityLink** [comment]
agreed, I have no idea why this got merged so quickly.

**Comment by tuypo1** [comment]
Yeah what the fuck was up with that
I wonder, maybe if memes could also be cured memeticly they wouldn't be so bad, just have one person take the cure and spread it to the rest of the station like that, probably kind of hard to implement with how the immunity system works though

**Comment by DeityLink** [comment]
I think it's a bad thing that any disease can have any symptom by default (without splicing), something that can spread as easily as memes should never have symptoms of danger 2+. Or even less easily spawning in latejoin humans (what was that about anyway?)

**Comment by Killette2** [comment]
I always argued that memes shouldn't start with glasgow as it's the only complaint. If they were manufactured then it would at least have player intent behind it rather than "RNG says fuck you, now find a doctor that knows about viruses or powergame yourself"

**Comment by PrimeDSS13** [comment]
"""""speedmerges"""""

**Comment by DamianX** [comment]
\>bleeding-edge experiment
what did he mean by this

**Comment by tuypo1** [comment]
Glasgow shouldn't even be in the game, I would rather just straight up die than get it
but you are right if we have to have glasgow it should at least require actually coming in contact with an infected individual or something

**Comment by ShiftyRail** [comment]
i did this late at night and thought this was a revert IN THREE DAYS

**Comment by Zth--** [comment]
@DeityLink could you reopen the original PR?

**Comment by Zth--** [comment]
Oh well, forgot about the changelog

**Pull request merged**
