### PR TITLE
The Ultimate Bartender Power Creep

### PR DESCRIPTION
**Pull request by DeityLink**
https://cdn.discordapp.com/attachments/246096207523348481/548656906751705089/dreamseeker_2019-02-23_01-02-37-04.webm
image

:cl:
* tweak: The bartender's shaker now acts as a stasis beaker! You can shake it by clicking it, which will cause the reagents to react after about 3 seconds of shaking.
* rscadd: Bartenders now also arrive on the station with a shaker already in their pocket.
* tweak: However, shakers bought at cargo are now discount shakers that don't have this new behaviour. Those found in asteroid ruins however do.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Is that the sound of an actual shaker?
It sounds like it's filled with gravel.

**Comment by DeityLink** [comment]
I heard a real one tonight and it sounds really close. They're generally filled with ice cubes.

**Comment by Coxswain-Navigator** [comment]
Cant wait to make my own shaker vape

**Comment by Exxion** [comment]
OK but why

**Comment by ghost** [comment]
This is something I never knew I needed until now.

On an actual note, though, the sound could maybe be a bit of a lower pitch — but seeing as I haven't done bartending in ages I'm gonna trust Deity on it sounding close enough.

**Comment by Exxion** [comment]
I thought this would just make it ridiculously clunky but then I realized that you could still use it normally and the stuff would just react when you pour it out rather than when you pour it in
I still don't see the point but there's also no harm so whatever

**Comment by ghost** [comment]
This makes the shaker a grenade.

**Comment by ghost** [comment]
On that note, maybe make it a do_after.

**Comment by DeityLink** [comment]
*It is a do_after
*Pitch is randomized
*You can still drink from it by clicking on yourself

**Comment by DeityLink** [comment]
@Exxion this is an opportunity for the bartender to sacrifice a few seconds while making a drink for style points. And thats it. Like you said they can still pour drinks immediately.

**Pull request merged**
