### PR TITLE
[WIP] lets brains (for posbrains / mmis) change their intent

### LINKED ISSUE #5070: [Mech] Posibrains and presumably MMI's cannot change intents
Alright so everyone knows, get in the mecha shinji and set your intent to harm so you can mech punch spiderlings instead of shooting 5 guys with bullets right? Well Posi's and mmi's have no intent block to toggle so, "the mech pushes the spiderling out of the way!". Using the intent hotkey didn't change it.

### PR DESCRIPTION
**Pull request by Intigracy**
fixes #5070

I need to test more and ensure it's actually working now, though I'll do it sometime soon rather than this specific moment.

### CODE REVIEW

**Comment by gbasood** [comment]
can we please pretend we can code and not have 300 character branch titles anymore

**Comment by Exxion** [comment]
> Hating fun

**Comment by Intigracy** [comment]
Meme branch names are great I dunno what you mean.

**Comment by Intigracy** [comment]
Also I'll have you know it's only 201 characters long.

**Comment by Intigracy** [comment]
some other time

**Pull request closed without merging**
