### PR TITLE
Corrects Incorrectly named Shirt

### PR DESCRIPTION
**Pull request by Arthurdentist**
Major bug fix, space is saved forever.

noticed this whilst playing couple rounds ago.

### CODE REVIEW

**Comment by Zth--** [comment]
liberty shit

**Comment by Arthurdentist** [comment]
why do you hate freedom Zth?

**Comment by Zth--** [comment]
That's the american suit, right?

**Comment by Arthurdentist** [comment]
yes

**Comment by Zth--** [comment]
Then, yeah, it's not a shirt, it's a shit!

**Pull request merged**
