### PR TITLE
This time in 300x300 instead of 512x512

### PR DESCRIPTION
**Pull request by ghost**
#7653 was too good for this world, so instead of doubling map size, we're going for a more reasonable size increase
- Map is now 1.39 times bigger instead of 4.09 times, thereby hopefully making sure load times stay reasonable
- 22.5 more tiles of clearance on all sides of every Z-level of every map. Some Z-levels were moved to a more central position to further increase distance from transition zone
- Updated thunderdome coordinates

Hopefully this time without problems

### CODE REVIEW

**Comment by AutismSpider** [comment]
Try 250x250 be on the safe side?

**Comment by ghost** [comment]
The map is 255x255 right now

**Comment by icantthinkofanameritenow** [comment]
It broke the first time. How do you know this won't break too? Besides, it's such a small change in size that it'll be worthless for expanding the station as you set out to do in the first place. 

I suggest you do more to fill out the existing Z-level instead or add entirely new ones, half of them are little more than blank space or just plain not worth the trouble of reaching.

**Comment by clusterfack** [comment]
I'm going to deal with the root of the startup time issue

**Comment by ghost** [comment]
I will close this in favor of re-applying #7653 if #7700 goes through and works

**Comment by ghost** [comment]
Conflicts I guess, also the PR in question went through, time for 500x500 times two

**Pull request closed without merging**
