### PR TITLE
fixes #7985

### LINKED ISSUE #7985: space pod nullspace
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> get sent to nullspace
> 
> What you expected to happen
> 
> What actually happened
> the escape shuttle ran over my space pod and it sent me into nullspace
> 
> Steps to reproduce if possible
> get run over while in a space pod and moving

### PR DESCRIPTION
**Pull request by ghost**
fixes #7985

### CODE REVIEW

**Comment by clusterfack** [comment]
Are the pods actually being deleted in this case?

**Comment by ghost** [comment]
@clusterfack I presume so, unid said it was not a shuttle issue and the pods were getting destroyed so I fixed that.

**Comment by clusterfack** [comment]
You assume that they are being destroyed and not merely sent to nullspace, I do not have the same assumption. I think it is wholly possibly they are being sent to nullspace, meaning this fix wouldn't help.

**Comment by ghost** [comment]
@clusterfack I'll test it. I'm pretty sure they're being destroyed

**Comment by ghost** [comment]
@clusterfack Worked in local testing on the supply shuttle.

**Comment by clusterfack** [comment]
Did you reproduce it with that same shuttle first?

**Comment by ghost** [comment]
Just reproduced it on live with the cargo shuttle.

**Pull request merged**
