### PR TITLE
Carshalash back at it again at krispy kreme. Antag cuff clowns.

### PR DESCRIPTION
**Pull request by carshalash**
You know what they say, 4th times the charm.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
Locked until role datums are out.

**Comment by Exxion** [comment]
For what reason? Locking conversation has nothing to do with preventing merge.

There's an approximately 0% chance it will be merged anyway, before or after that

**Comment by Exxion** [comment]
Oh and feel free to re-lock it in the not-exactly-unlikely event it devolves into shitposting, etc.

**Comment by carshalash** [comment]
Love you too exxion.

**Comment by DeityLink** [comment]
special_role is not longer used in datums. There's a list of antag roles in mind. just check that the list isn't empty.

**Comment by carshalash** [comment]
Fugg

**Comment by jknpj** [comment]
If you ever get around to fix this feel free to ping me in the discord to reopen it

**Comment by DeityLink** [comment]
image

**Pull request closed without merging**
