### PR TITLE
Replace tool istypes() with macros

### PR DESCRIPTION
**Pull request by unid15**

### CODE REVIEW

**Comment by Exxion** [comment]
THANK YOU
This allows for proper multitools!

**Comment by Probe1** [comment]
Didn't we move to absolute pathing for a reason?

**Comment by Iamgoofball** [comment]
that's not what absolute pathing means

**Comment by Exxion** [comment]
Yes, but this has nothing to do with that

**Comment by Probe1** [comment]
Whats the difference?  And I don't mean technically.  I appreciate that this isn't a relative path, it's a macro.

**Comment by Iamgoofball** [comment]
this is relative pathing:

``` DM
obj
     [CENSORED]
            proc
                   [CENSORED]_up(var/amount = 69)
```

this is absolute pathing:

``` DM
/obj/[CENSORED]/proc/[CENSORED]_up(var/amount = 69)
```

**Comment by Exxion** [comment]
https://github.com/d3athrow/vgstation13/wiki/Coding-standards-for-vgstation13

Basically, we use absolute pathing in type definitions because it's more readable and allows for fewer fuckups and absolute pathing everywhere else because it's required
But that doesn't mean we should use hardcoded paths over all other options

**Comment by Probe1** [comment]
> However, work has to be done to replace a lot of old color macros with the new standard, as well as prevent new color macros from being added in over the newer style. Old \red and \blue macros should be replaced with one of the following appropriate span classes:

See where I'm coming from?

**Comment by Exxion** [comment]
Color macros =/= code macros
See the edit to my last comment

**Comment by Probe1** [comment]
I don't see the difference.  Color macros are code macros with the specific label of color.

But I'll accept the expertise of others and accept this explanation even if it looks like the same shit with a different name.

**Comment by Exxion** [comment]
Color macros are _text_ macros, not code macros, and we moved away from them because we have a better option (`<span>` classes, etc.)
Same reason to move to code macros rather than hardcoded `istype()`s

**Comment by 9600bauds** [comment]
How the hell did relative pathing even come up in this conversation at all?

**Comment by PJB3005** [comment]
This'll make modular tools easy as shit!

**Comment by Probe1** [comment]
@9600bauds I brought it up because it looks like something that will put us back to where we were before.

**Comment by unid15** [comment]
what does this have to do with absolute pathing at all

**Comment by PJB3005** [comment]
@unid15, probe is just confused.

**Comment by gbasood** [comment]
what
could
go
wrong

@Probe1 This has nothing to do with relative pathing in any way, and the reasons for using relative pathing have nothing to do with what changes were made.

**Comment by Probe1** [comment]
I have been informed.

**Comment by clusterfack** [comment]
Best to merge it now before the conflicts start

**Pull request merged**
