### PR TITLE
Fixes the random lotto event problem with one simple trick doctors don't want you to know about (removal)

### PR DESCRIPTION
**Pull request by adacovsk**
There's a random event called "money_lotto" which gives a random amount of credits to a random account, including department accounts. We now have two well-developed RNG systems and luck for loadsa money/dosh. Random lotto isn't influenced by luck, isn't fun, doesn't do anything besides make a big number, and decreases odds of fun events.

Edit: this deletes money_lotto.dm

## What this does
- Increases odds of other events triggering that will be more enjoyable

## Why it's good
- Decreases compile time and increases chances for a fun random event

:cl:
 * rscdel: Decreased the odds of money lotto event to 0, boosting chances of actual fun events

### CODE REVIEW

**Comment by ManopolisJones** [comment]
What the fuck is this shit, if you're gonna remove the shitty old lotto event, just say you're removing it, don't try to word your way around like some underhanded PUSSY

**Comment by pedr69** [comment]
it made a fun situation for me ONCE; someone hit a million creds, and checking the accounts database none of the station accounts had it
only other possibility we saw was the trader debit, so a raiding party was organised to smash the voxstation and loot their card
lo and behold, the million was there, so we called the shuttle and went home rich as fuck

**Comment by adacovsk** [comment]
> What the fuck is this shit, if you're gonna remove the shitty old lotto event, just say you're removing it, don't try to word your way around like some underhanded PUSSY

I tried that already, and it was downvoted into oblivion lmao

**Comment by pedr69** [comment]
>it's real

#32017

**Comment by Exxion** [comment]
You've forgotten that half the players see the remove word and stop reading and downvote

**Comment by Armadingus** [comment]
> I tried that already, and it was downvoted into oblivion lmao

I'm in favour of both this and the previous PR, but surely you can see that misleading the community to make a change is detrimental? What precedent does this set for our Github? That you must obfuscate, omit information and lie your way to a merged PR? If you have an ounce of respect for transparency, you shouldn't resort to dancing around a certain R-word. It will only make you look worse if you do stick to this title and description.

**Comment by WindowsErrors** [comment]
> > I tried that already, and it was downvoted into oblivion lmao
> 
> I'm in favour of both this and the previous PR, but surely you can see that misleading the community to make a change is detrimental? What precedent does this set for our Github? That you must obfuscate, omit information and lie your way to a merged PR? If you have an ounce of respect for transparency, you shouldn't resort to dancing around a certain R-word. It will only make you look worse if you do stick to this title and description.

ok retard

**Comment by Eneocho** [comment]
I'd keep it as a space nigerian prince event. If you send them 1000c you have a 10% chance to actually get 1 million credits back.

**Comment by Hinaichigo** [comment]
The power of phrasing... not to be trifled with.

**Comment by BomberBro** [comment]
\>fix
Get this propaganda title out of here, slippery slope of labelling things that aren't actually fixes as fixes to court the illiterate voter bloc. This guy already tried it with an honest title and it failed.
\>Increases odds of other events triggering that will be more enjoyable
\>Decreases compile time and increases chances for a fun random event
Fake news from the mainstream media once again, none of the events are fun.

**Comment by DamianX** [comment]
viviamo in una società

**Comment by BomberBro** [comment]
imposter
STOP THE COUNT

**Comment by pedr69** [comment]
while we're talkin of rigged votes, #32461

**Comment by adacovsk** [comment]
Dingus betrays me

**Comment by adacovsk** [comment]
> >fix Get this propaganda title out of here, slippery slope of labelling things that aren't actually fixes as fixes to court the illiterate voter bloc. This guy already tried it with an honest title and it failed. >Increases odds of other events triggering that will be more enjoyable >Decreases compile time and increases chances for a fun random event Fake news from the mainstream media once again, none of the events are fun.

There is a difference now. There is an actual lotto system now. If you read the PR, you'd know this, retard

**Comment by Armadingus** [comment]
> Dingus betrays me

I just want you to be a straight and narrow coder, I don't think you should be encouraged with thumbs up to make PRs that obscure the actual change. I'll support you again if you change the title to something along the lines of "Deletes the random event newscaster lottery".

**Comment by Armadingus** [comment]
bruh

**Comment by djkramer123** [comment]
Just say you're removing it instead of acting like a fag

**Comment by Eneocho** [comment]
`>self upvote and obfuscated changes`
that's a no from me chief, even if nobody ever gets this (I got it once in 2 years).

**Comment by BomberBro** [comment]
Self upvote, obfuscated changes and refuses to take my good friend Armadingus's advice.... they aren't sending their best, folks! 

\>There is a difference now. There is an actual lotto system now. If you read the PR, you'd know this, retard
If it was a true fix the new system would've replaced the lottery in the original PR. This is removal plain and simple, a removal that the coders down in Washington want to hide from you!

**Comment by Exxion** [comment]
>This guy already tried it with an honest title and it failed.

It sounds like you're saying that changing the title alone significantly swings the emoji votes
I wonder what this says about the usefulness of the emoji votes

**Comment by WindowsErrors** [comment]
> > Dingus betrays me
> 
> I just want you to be a straight and narrow coder, I don't think you should be encouraged with thumbs up to make PRs that obscure the actual change. I'll support you again if you change the title to something along the lines of "Deletes the random event newscaster lottery".

> > This guy already tried it with an honest title and it failed.
> 
> It sounds like you're saying that changing the title alone significantly swings the emoji votes I wonder what this says about the usefulness of the emoji votes

another case of idealism vs. realism

unlike on every other server in this community where it would be the other way around, here, the blessing of a single administrator is infinitesimal compared to the will of a small number of highly motivated bulletin board schizophrenics

**Comment by Eneocho** [comment]
The spessmen will never drink the corn syrup.

**Comment by bathosbathtime** [comment]
I recall a time where voting on your own PR got it automatically closed. Like, with a bot. That was funny, we should do that again.

**Comment by bathosbathtime** [comment]
> > This guy already tried it with an honest title and it failed.
> 
> It sounds like you're saying that changing the title alone significantly swings the emoji votes I wonder what this says about the usefulness of the emoji votes

People supporting a bugfix more than they would support a design change is not shocking nor is it a condemnation of the emoji votes. There are enough issue with it, such as the fact that there is not requirement to play on the server at all to cast one, that you do not need to make up reasons to own people epic style on the internet with your sick passive-aggressive burns.

**Comment by luigil101** [comment]
upvoting your own PR is one of the most disgraceful things

**Comment by tuypo1** [comment]
The PR was never hiding what it did, if people are instinctually downvoting the moment they see the word remove we shouldn't be caring about their votes to begin with

**Comment by bathosbathtime** [comment]
People who disagree with a balance change might not even open a bugfix to look at it.

**Comment by adacovsk** [comment]
I used the r word and see what happened

**Comment by adacovsk** [comment]
> People who disagree with a balance change might not even open a bugfix to look at it.

what are you even talking about?

**Comment by WindowsErrors** [comment]
i think we should give this one the Black Market treatment by merging it even though all the thumb downers are coming out of the woodworks

**Comment by luigil101** [comment]
he tried to remove his thumbs up to hide his immeasurable shame
but it is too late for that

**Comment by adacovsk** [comment]
Just so everyone is aware, the expected value is once every five years for a person to win it, assuming an average of 20 players per day, and a round being 2h long, with four events. @west3436 you know what to do on your next lottery ticket update

**Comment by Hinaichigo** [comment]
Does the event itself 'use up' an event if nobody wins?

**Comment by adacovsk** [comment]
> Does the event itself 'use up' an event if nobody wins?

yes

**Comment by Hinaichigo** [comment]
Maybe you could make so that it always goes through but the event itself triggering is weighted super low relative to other events. Might require implementing event weighting.
Or maybe have it so when if nobody wins, it calls another random event. Could lead to infinite looping if more than one event does that though, so the first option might be better.

**Comment by angryturnip** [comment]
Genuine question: you PR'd this in February and it didn't pass. Why do you want this to be merged so badly?

**Comment by Hinaichigo** [comment]
I think the main issue is it "using up" an event call most of the time without doing anything. Weighted events would please all parties I think, and be good to have in general.

**Comment by adacovsk** [comment]
> Genuine question

a social experiment

**Comment by Kurfursten** [comment]
I honestly think this PR would pass if it didn't have hard feelings surrounding it. Truly, I think I'd be justified in just merging it today because of that. However, I think what the voters want is to send a message that circumlocutions and bad CL is not the way to do code, which is true, and that it would be bad form if I didn't acknowledge that.

I recommend trying this again as a clean slate where you tell people from the get go that the intent is to improve the bad lotto now that we have two very reasonable replacements for it with scratchoffs and slotmachine.

**Pull request closed without merging**
