### PR TITLE
Revert quickly-merged changelog-less balance changes AKA "Added CANKNOCKDOWN flag to aliens"

### PR DESCRIPTION
**Pull request by SonixApache**
Reverts vgstation-coders/vgstation13#15574

what the fuck guys

### CODE REVIEW

**Comment by gbasood** [comment]
Why this got reverted: 
 - Balance changed merged without gathering feedback from the players (no, codetalk is not the players)
 - No changelog
 - Everyone who DID give feedback thought it was bad

**Comment by IAGFPRMF** [comment]
RIP died before it could be hilariously abused

**Comment by Icychocobo** [comment]
Hey, I only thought it was *half* bad.

**Comment by gbasood** [comment]
well now you can tell deity what you liked in a new PR that actually has time to be yelled at

**Pull request merged**
