### PR TITLE
head revolutionaries get megaphones

### PR DESCRIPTION
**Pull request by gurfan**
loud and proud

:cl:
 * rscadd: Head Revolutionaries now start with a megaphone, in addition to their current tools.

### CODE REVIEW

**Comment by help-maint** [comment]
;someone has a megaphone call it

**Comment by FlintBarrel** [comment]
might wanna make it a bit less of a metacheck, but then again head revs have flashes, so what do I know. Also, updating the wiki for revs when?

**Comment by gurfan** [comment]
Headrevs already get an implant pinpointer which is a dead giveaway that there's a revolution. Plus the point of the megaphone is to gain style points when cover has already been blown.

**Comment by calzilla1** [comment]
Maybe make a subtype and give it a short-range, one time use vamp screech/ some sort of team buff so it doesn't just take up a backpack slot if the revhead wants to go all stealthy-like (and would be nice to have if the revs get caught early)

**Comment by gurfan** [comment]
Why should it stun or give any kind of tangible buff, I just thought that headrevs shouting orders or slogans with a megaphone would be neat. If a headrev doesn't want it to take up a backpack slot then they can get rid of it.

**Comment by KillFurries** [comment]
It's a bad idea. It gives revolutionaries another metacheck giveaway that they're a revolutionary.
A far better implementation would be to simply put a megaphone in one of the storage rooms next to the crayons and the spare camera. This way if the revolutionary really wants to go full revolution LARP they can do it, but having a megaphone doesn't lead to security immediately executing you. Less meta checks are better for the game.

**Comment by ShiftyRail** [comment]
It's not really more (or less) of a giveaway that someone is a rev than the old flash. It's definitively less of a giveaway than the new implant pinpointer they get.

A security officer executing someone for merely having a megaphone and/or a flash surely will get banned. I remember one officer getting a 15 days long vacation for trusting the word of an AI over a cult menace, for instance.

**Comment by help-maint** [comment]
Maybe give them a fake pen that unfolds into a megaphone if desired?

**Comment by cloutcode** [comment]
way to fix this: give heads of staff roundstart megaphones as well, so there's an excuse if there's megaphones drifting around in the round and also giving heads a way to better coordinate their retards

**Comment by Apogee-dev** [comment]
> way to fix this: give heads of staff roundstart megaphones as well, so there's an excuse if there's megaphones drifting around in the round and also giving heads a way to better coordinate their retards

A substantial number of maps give Heads a megaphone in their office (especially HoS). If you ask me, this should be a standard mapping thing- gives heads a way to herd their idiots and the megaphones could be handy to steal now and then

**Comment by calzilla1** [comment]
Ok if adding some sort of unique mechanic to the megaphone is no beuno, just have megaphones be a bit easier to come across. Maybe add one to dorms with the pAI or have cargo be able to print them. If you've gotten to the point where you're directing your rev-lings over common then you've most likely got cargo locked down. Having XBOX HEUG letters being mostly synonymous with "OH SHIT REVS" is a bad idea.

**Comment by calzilla1** [comment]
Either that or have the PDA also act like a watered-down version of an uplink with a bunch of minor gimmick items like the megaphone or, say, a crate of Russian attire.

**Comment by PrimeDSS13** [comment]
rev heads literally have magic pinpointers exclusive to them
a megaphone is no big deal

**Comment by APCUnlocked** [comment]
Nobody will get executed for having a megaphone, dumb theorycrafters. This is a good idea.

**Comment by ShiftyRail** [comment]
Ban all theorycrafters

**Pull request merged**
