### PR TITLE
plasteel tiles weld back into plasteel

### LINKED ISSUE #31721: Welding 4 plasteel floortiles back into plasteel doesn't work, instead they turn into regular steel.
#### Description of issue
You can weld 4 of any regular metal tile to make a metal sheet again, this gives you the source metal back. Metal tiles become metal sheets, silver tiles become silver, uranium tiles become uranium, etc.
If you try this with plasteel tiles, instead of becoming plasteel again, it somehow turns into regular steel.
#### Difference between expected and actual behavior
Expected plasteel back.
Somehow got metal.
#### Steps to reproduce
Get some plasteel and a fueled welder.
Turn some plasteel into reinforced floor tiles.
Weld those floor tiles back into plasteel.
Get metal instead.
#### Length of time in which bug has been known to occur
Probably since tilewelding became a thing.
[bugfix][oversight]

### PR DESCRIPTION
**Pull request by SonixApache**
[hotfix] fixes #31721

### CODE REVIEW

**Comment by Kurfursten** [comment]
Instead of this just create a var for the type of sheet for the tiles to weld into, then you can do it at the parent level

**Comment by SonixApache** [comment]
yeah we had a discussion on how to do this properly, i forgot to work on it

**Comment by DamianX** [comment]
this hotfix is feeling cold
might have to shove it in the microwave for a minute

**Comment by west3436** [comment]
hotfix

**Pull request closed without merging**
