### PR TITLE
More mining loot crate items (and updates)

### PR DESCRIPTION
**Pull request by SECBATON-GRIFFON**
## What this does
adds the following loot crates to the distribution:

 * plasma beaker
 * tier 2 stock parts, any 3 to 9
 * 3 lazarus injectors
 * borg upgrades (picks between the hookshot and autosmelter)
 * assemblies for medbots, cleanbots, cheapsky, floorbots or mining drones. parts for secbots and britsky can be found in these too, but without the batons needed to complete them.
 * borer egg

the following are locked behind crates that spawn with only 2 access attempts:

 * automatic ore loader
 * diamond mining drill
 * a hivelord OR basilisk hide
 * rig suit upgrades (any 2 to 3)
 * tier 3 stock parts, any 3 to 9
 * 3 advanced lazarus injectors
 * 3 random seeds from gold apples, silver pears, diamond carrots, plasma cabbages, glowberries, telriis or vale. also has a 10% chance to spawn a no fruit seed.

the following are locked behind crates that spawn with 1 attempt:

 * plasma cutter conversion kit
 * two hides either hivelord or basilisk
 * 3 hivelord cores

the distribution of these crates has also been weighted to prefer higher attempt (and low difficulty) crates in frequency

## Why it's good
the list of items in these are really barren, plain and not rewarding enough. PLEASE let me know if i didn't increase crate access difficulty in a fair or good way.

## Changelog
:cl:
 * rscadd: The selection of items founded in mine loot crates is now vastly greater, although some more valuable crates have less access attempts now.

### CODE REVIEW

**Comment by Kurfursten** [comment]
Can these crates be emittered/emagged? You are correct that currently they're terrible which is why I normally just guess 1 2 3 and make no serious effort to open.

**Comment by PrimeDSS13** [comment]
I wouldn't put bananium or phazon in these, since all you need is a single piece to scan infinite amounts of it.

**Comment by DorainGrey** [comment]
Phazon & Bananium feels a bit overkill, same with 5K cash.
Given it's a greater than 10% chance for tier two crates with a multitool and iirc these crates are fairly common.

**Comment by DorainGrey** [comment]
> I wouldn't put bananium or phazon in these, since all you need is a single piece to scan infinite amounts of it.

Just to note T4 parts also provide phazon when recycled and can thus be scanned as well but I'd be less concerned on the tier 3 crates.

**Comment by gurfan** [comment]
Powercreep

**Comment by SECBATON-GRIFFON** [comment]
> Can these crates be emittered/emagged? You are correct that currently they're terrible which is why I normally just guess 1 2 3 and make no serious effort to open.

seems so

**Comment by SECBATON-GRIFFON** [comment]
> Phazon & Bananium feels a bit overkill, same with 5K cash. Given it's a greater than 10% chance for tier two crates with a multitool and iirc these crates are fairly common.

moved it down to the 10% chance

**Comment by gurfan** [comment]
Why does the loot suddenly change depending on how many times you guess? It makes no sense.
Phazon/Bananium don't need to be more common. 
I don't like that miners can just stumble across xenoarcheology items too. Not every special item needs to be available in a million fucking ways.
Putting all those ridiculous credit rewards in what is essentially an RNG check is fucking silly. Miners already make a stupid amount of money, they don't need more. Credits already have so little real value and I hate that you're adding yet another way to get a stupid amount of them. (Also why I fucking hate the luck system and the botanists that use it to win slots jackpots)

Yes the abandoned mining crates suck but I would rather have shitty crates than stupid powercreeped ones.

**Comment by SECBATON-GRIFFON** [comment]
> Why does the loot suddenly change depending on how many times you guess? It makes no sense. 

made the wording a bit clearer 

> Phazon/Bananium don't need to be more common. I don't like that miners can just stumble across xenoarcheology items too. Not every special item needs to be available in a million fucking ways. Putting all those ridiculous credit rewards in what is essentially an RNG check is fucking silly. Miners already make a stupid amount of money, they don't need more. Credits already have so little real value and I hate that you're adding yet another way to get a stupid amount of them. (Also why I fucking hate the luck system and the botanists that use it to win slots jackpots)
> 
> Yes the abandoned mining crates suck but I would rather have shitty crates than stupid powercreeped ones.

got rid of all the contentious stuff you mentioned

**Comment by SECBATON-GRIFFON** [comment]
> > I wouldn't put bananium or phazon in these, since all you need is a single piece to scan infinite amounts of it.
> 
> Just to note T4 parts also provide phazon when recycled and can thus be scanned as well but I'd be less concerned on the tier 3 crates.

disabled this on the parts when distributed like this

**Comment by jwhitak** [comment]
Poor attempt at making the crates more interesting. The selections are mostly power creep (tier 4 parts lol) and the restrictions are meaningless and unfun. Additionally, you're forcing the miners to engage with a bad minigame for bad loot by removing the ability to get around the game.

You could be coding new antags/game modes right now, not making it harder for a hobo to get hydroponic trays.

**Comment by SECBATON-GRIFFON** [comment]
> Poor attempt at making the crates more interesting. The selections are mostly power creep (tier 4 parts lol)

decided to just remove them

> and the restrictions are meaningless and unfun. Additionally, you're forcing the miners to engage with a bad minigame for bad loot by removing the ability to get around the game.
> 
> You could be coding new antags/game modes right now, not making it harder for a hobo to get hydroponic trays.

wasnt quite sure on the restrictions honestly

**Comment by pedr69** [comment]
wait till they find out you can alt click the crates to open them instead of faffing with the multitool

**Comment by Eneocho** [comment]
My guesses usually are 5 9 7 or 5 1 3. I get to open 2 in 5 boxes with those numbers (and not checking with multitools). This is welcome.

**Comment by SECBATON-GRIFFON** [comment]
guess i didnt account for the alternate ways to open them. will close this and let someone else handle this topic at some other time.

**Pull request closed without merging**
