### PR TITLE
Double action(button) boogaloo

### PR DESCRIPTION
**Pull request by JustSumBody**
revives the fuck out of #11606 god I hope my rebasing didn't fuck something somehow

Ports the action button/datum system from TG for objects
This all JUST WORKS as it did six fucking months ago(which is perfectly fine, though I'm a bit uncomfortable with the way I made it work for holomap chips)

Reduces the need to hardcode number of action buttons, now can have as many action buttons as you need

Allows items to have multiple action buttons rather than being restricted to one, simply define the action datum and ``actions_types`` list of an item to include it. ~~then override the items ``ui_action_click`` to do the appropriate thing depending on which action gets clicked~~ Then define the action's ``Trigger`` proc to do whatever it is you need it to do
probably
Look it's been a WHILE since I looked at this code be gentle

image

### CODE REVIEW

**Comment by RemieRichards** [comment]
@JustSumBody 

This is going to sound hypocritical, but
>override the items ui_action_click to do the appropriate thing depending on which action gets clicked

Please do not do this. ```ui_action_click()``` was a holdover from when the action system was in VERY early development, and it's absolute horseshit, since the action system was finished I've been pushing for this way of doing things to die (replaced by using the appropriate procs on the datums that you already have to define anyway)

Up to you guys, but this is the one time you might get an edge on /tg/ :^)

**Comment by JustSumBody** [comment]
FRICK

**Comment by Exxion** [comment]
>the one time

I know you're memeing but it still makes me mad

**Comment by JustSumBody** [comment]
Actually that would involve typecasting the target in the Action's trigger for the most part, no?
So like 
```
/datum/action/thing/Trigger()
if(!istype(target, path with toggle proc defined))
     return
var/path with proc defined/T = target
T.toggle proc
```
That's fine right

**Comment by RemieRichards** [comment]
Yes it would involve casting, but it's nicer than the weird topic-clone that ```ui_action_click()``` is.

**Comment by Probe1** [comment]
[prepare for unforeseen consequences]

**Pull request merged**
