### PR TITLE
Bigger vox shuttle

### PR DESCRIPTION
**Pull request by ShiftyRail**
[dnm]

I ran into an issue while trying to update other maps than box. I figured I would just PR it at it is, and wait for feedback.

Vox shoal shuttle has been expended. Humans now ride at the back of the bus, with a few toys to pass the time as they are being hauled to God-knows-where.
The raiders have a flasher to ensure that they can put their prisoners here safely.

image

### CODE REVIEW

**Comment by Probe1** [comment]
Use the WIP or github built in draft feature for incomplete drafts please.  DNM is cool but when I see it, I think the PR has some BIG PROBLEM that would prevent its merge.

**Comment by incakola** [comment]
It would be nice to have the docking arrow line up with one of the doors like other shuttles
but that is more work for not much benefit other than mapping
or is there a reason it is like this?

**Comment by ShiftyRail** [comment]
image

Minor tweaks (harder to break the windows protecting the engines, larger prisoner transfer areas)
Did the remaining maps

**Comment by ShiftyRail** [comment]
Gotta fix this rogue lamp, hold on

**Pull request merged**
