### PR TITLE
Security now has an IQ cutoff

### PR DESCRIPTION
**Pull request by bthomas2**
:cl:
 * tweak: Security now has an IQ cutoff

### CODE REVIEW

**Comment by Irradiation** [comment]
Even if we're having a string of retarded PRs, keep that shit for April Fools.

**Comment by calzilla1** [comment]
Speed merge

**Comment by RealestEstate** [comment]
a bit redundant if you ask me

**Comment by bthomas2** [comment]
cmon, where's my test merge?

**Comment by bthomas2** [comment]
@jknpj

**Comment by ghost** [comment]
I fucking hate this server

**Comment by juanototo2** [comment]
@jackfailure see you next week!

**Comment by ShiftyRail** [comment]
Tempted to either merge this or either merge the revert of that retarded access "test" and then fuck off

**Comment by bthomas2** [comment]
holy shit lmao

**Pull request closed without merging**
