### PR TITLE
Ports Nar-Sie reality tearing animation from Bay

### PR DESCRIPTION
**Pull request by jknpj**
https://webmshare.com/JeJJO

### CODE REVIEW

**Comment by Shadowmech88** [comment]
The Nar-Sie in the animation seems to be at a different resolution than the Nar-Sie that appears when the animation is finished.
This is still cool, though.

**Comment by Aurx** [comment]
Reminds me of those old-timey jrpg battle intro animations.  
Seems a bit too cheesy for Narnar.

**Comment by Kitfox88** [comment]
He already turns everything he farts over into a White Wolf LARP, cheese is his middle name.

**Comment by kol1th** [comment]
@Shadowmech88 The animation one is a lower pixel count.

**Comment by PJB3005** [comment]
That's probably because Deity increased the resolution here.

**Comment by RemieRichards** [comment]
it's not from bay, I made this ages ago for NT/TG, just saying.

**Comment by ihadtoregisterforthis** [comment]
At least remake it with our current NarSie sprite

**Comment by clusterfack** [comment]
Wow that looks really silly, I thought he's force open a hole in space time with his and come through or something.

**Comment by JMWTurner** [comment]
> I thought he's force open a hole in space time with his hands and come through or something.

@clusterfack That's how I picture it as well. I've got an animation in mind already, which will go along with the upcoming cult revamp I have planned. But I guess that animation is nice in the meantime.

**Pull request merged**
